### ISSUE TITLE
Unexpected panic at 'explicit panic', src/librbml/lib.rs:436

### ISSUE THREAD

**Issue by mrkev** [rust-lang/rust#35153] opened 2016-08-01 04:54 UTC
I'm not the first one to see this one (#33733, #33015 -promise I'm not drunk tho heh) while building a brand new project with a single dependency:

```
[dependencies]
"synth" = "*"
```

The full trace;

```
$ RUST_BACKTRACE=1 cargo run --verbose
       Fresh num-traits v0.1.34
       Fresh fixedbitset v0.1.1
       Fresh interpolation v0.1.0
       Fresh sample v0.3.0
       Fresh rustc-serialize v0.3.19
       Fresh num-integer v0.1.32
       Fresh winapi v0.2.8
       Fresh winapi-build v0.1.1
       Fresh num-complex v0.1.33
       Fresh num-iter v0.1.32
       Fresh petgraph v0.2.7
       Fresh libc v0.2.14
       Fresh panning v0.1.1
       Fresh daggy v0.4.0
       Fresh rand v0.3.14
       Fresh dsp-chain v0.12.0
       Fresh kernel32-sys v0.2.2
       Fresh num-bigint v0.1.33
       Fresh time v0.1.35
       Fresh num-rational v0.1.32
       Fresh num v0.1.34
       Fresh mindtree_utils v0.3.0
       Fresh mindtree_utils v0.4.0
       Fresh time_calc v0.10.1
       Fresh pitch_calc v0.9.7
       Fresh envelope v0.7.0
       Fresh simple_gaussian v0.4.4
   Compiling synth v0.10.0
     Running `rustc /Users/Kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/synth-0.10.0/src/lib.rs --crate-name synth --crate-type lib -g -C metadata=86d40d54110626b3 -C extra-filename=-86d40d54110626b3 --out-dir /Users/Kevin/Desktop/rust/synthingy/target/debug/deps --emit=dep-info,link -L dependency=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps -L dependency=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps --extern pitch_calc=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libpitch_calc-429f283552a491e9.rlib --extern envelope=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libenvelope-e3af18ed054e064b.rlib --extern utils=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libutils-ba36ae19185040ae.rlib --extern dsp=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libdsp-4e01ff51bb6d3db2.rlib --extern panning=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libpanning-dcdbcf51cac96068.rlib --extern rand=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/librand-49a08859d086fffe.rlib --extern gaussian=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libgaussian-6283fda8084362e5.rlib --extern time_calc=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libtime_calc-e67463ca9b5e40e4.rlib --extern num=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libnum-262f3a136066b482.rlib --extern rustc_serialize=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/librustc_serialize-3561541d79c18212.rlib --cap-lints allow`
ERROR:rbml::reader: failed to find block with tag 32
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'explicit panic', src/librbml/lib.rs:436
stack backtrace:
   1:        0x10fce200b - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:        0x10fcee7d5 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:        0x10fcee30f - std::panicking::default_hook::hf3839060ccbb8764
   4:        0x10fcb44c7 - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:        0x10d94e9b4 - std::panicking::begin_panic::h4c14e704ed94392f
   6:        0x10d94c494 - rbml::reader::get_doc::h094521c645459139
   7:        0x10ca78d2d - rustc_metadata::decoder::item_name::hb367e4fbaed35644
   8:        0x10cac725c - rustc_metadata::csearch::_<impl rustc..middle..cstore..CrateStore<'tcx> for cstore..CStore>::item_name::h528d71e4f6c62e51
   9:        0x10d013e6d - rustc::ty::item_path::_<impl ty..context..TyCtxt<'a, 'gcx, 'tcx>>::push_item_path::hed22fb7501168c3f
  10:        0x10d0148df - rustc::ty::item_path::_<impl ty..context..TyCtxt<'a, 'gcx, 'tcx>>::push_item_path::hed22fb7501168c3f
  11:        0x10d0145eb - rustc::ty::item_path::_<impl ty..context..TyCtxt<'a, 'gcx, 'tcx>>::push_item_path::hed22fb7501168c3f
  12:        0x10cde7097 - rustc::ty::item_path::_<impl ty..context..TyCtxt<'a, 'gcx, 'tcx>>::node_path_str::he60e69ed977cf912
  13:        0x10c2dbf10 - rustc_trans::base::trans_fn::h7782f06042d5db89
  14:        0x10c31c233 - rustc_trans::callee::get_fn::h08e1b7cc1cce1c5c
  15:        0x10c2ba6de - rustc_trans::callee::Callee::def::h0b97eb29a598504b
  16:        0x10c39a684 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  17:        0x10c396d65 - rustc_trans::expr::trans_unadjusted::h52d6294d0df13b26
  18:        0x10c33425d - rustc_trans::expr::trans::h427751e1ef62f7c0
  19:        0x10c397fd6 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  20:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  21:        0x10c3e0b6a - rustc_trans::_match::mk_binding_alloca::h2d8ab9ab8a5baef1
  22:        0x10c2c5e44 - rustc_trans::base::init_local::hf3db19a232dc9f62
  23:        0x10c2db830 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  24:        0x10c398c54 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  25:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  26:        0x10c2dbc01 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  27:        0x10c2da3b1 - rustc_trans::base::trans_closure::h35301b2f12a8fbfd
  28:        0x10c33da91 - rustc_trans::closure::trans_closure_expr::hc2617046fce01d43
  29:        0x10c39a375 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  30:        0x10c396d65 - rustc_trans::expr::trans_unadjusted::h52d6294d0df13b26
  31:        0x10c33425d - rustc_trans::expr::trans::h427751e1ef62f7c0
  32:        0x10c332d9f - rustc_trans::callee::trans_args::h05fa193cad8805cb
  33:        0x10c2b9250 - rustc_trans::callee::Callee::call::h396922a7aeb1da16
  34:        0x10c398ba3 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  35:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  36:        0x10c2dbc01 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  37:        0x10c2da3b1 - rustc_trans::base::trans_closure::h35301b2f12a8fbfd
  38:        0x10c2dc46d - rustc_trans::base::trans_fn::h7782f06042d5db89
  39:        0x10c31c233 - rustc_trans::callee::get_fn::h08e1b7cc1cce1c5c
  40:        0x10c2ba6de - rustc_trans::callee::Callee::def::h0b97eb29a598504b
  41:        0x10c39a684 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  42:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  43:        0x10c2dbc01 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  44:        0x10c2da3b1 - rustc_trans::base::trans_closure::h35301b2f12a8fbfd
  45:        0x10c2dc46d - rustc_trans::base::trans_fn::h7782f06042d5db89
  46:        0x10c31c233 - rustc_trans::callee::get_fn::h08e1b7cc1cce1c5c
  47:        0x10c2bb38e - rustc_trans::callee::Callee::def::h0b97eb29a598504b
  48:        0x10c39a684 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  49:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  50:        0x10c2e2ae5 - rustc_trans::expr::trans_adt::hd9cba141eef6ed3b
  51:        0x10c2b8f9d - rustc_trans::callee::Callee::call::h396922a7aeb1da16
  52:        0x10c39a852 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  53:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  54:        0x10c2dbc01 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  55:        0x10c2da3b1 - rustc_trans::base::trans_closure::h35301b2f12a8fbfd
  56:        0x10c2dc46d - rustc_trans::base::trans_fn::h7782f06042d5db89
  57:        0x10c31c233 - rustc_trans::callee::get_fn::h08e1b7cc1cce1c5c
  58:        0x10c2ba6de - rustc_trans::callee::Callee::def::h0b97eb29a598504b
  59:        0x10c39a684 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  60:        0x10c2e487e - rustc_trans::expr::trans_into::h2970e88afa93225a
  61:        0x10c2dbc01 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  62:        0x10c2da3b1 - rustc_trans::base::trans_closure::h35301b2f12a8fbfd
  63:        0x10c2dc46d - rustc_trans::base::trans_fn::h7782f06042d5db89
  64:        0x10c31c233 - rustc_trans::callee::get_fn::h08e1b7cc1cce1c5c
  65:        0x10c2bb38e - rustc_trans::callee::Callee::def::h0b97eb29a598504b
  66:        0x10c317ac9 - rustc_trans::callee::Callee::method_call::h18549d8d1ee31a9a
  67:        0x10c398b0d - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  68:        0x10c396d65 - rustc_trans::expr::trans_unadjusted::h52d6294d0df13b26
  69:        0x10c33425d - rustc_trans::expr::trans::h427751e1ef62f7c0
  70:        0x10c332d9f - rustc_trans::callee::trans_args::h05fa193cad8805cb
  71:        0x10c2b9250 - rustc_trans::callee::Callee::call::h396922a7aeb1da16
  72:        0x10c398ba3 - rustc_trans::expr::trans_rvalue_dps_unadjusted::hc488f93b33940c5f
  73:        0x10c396d65 - rustc_trans::expr::trans_unadjusted::h52d6294d0df13b26
  74:        0x10c33425d - rustc_trans::expr::trans::h427751e1ef62f7c0
  75:        0x10c3a270e - rustc_trans::expr::trans_imm_cast::ha9cdae78a526f6a2
  76:        0x10c39711c - rustc_trans::expr::trans_unadjusted::h52d6294d0df13b26
  77:        0x10c2e46f6 - rustc_trans::expr::trans_into::h2970e88afa93225a
  78:        0x10c2dbc01 - rustc_trans::controlflow::trans_block::h7fec90725c0a9f0f
  79:        0x10c2da3b1 - rustc_trans::base::trans_closure::h35301b2f12a8fbfd
  80:        0x10c2dc46d - rustc_trans::base::trans_fn::h7782f06042d5db89
  81:        0x10c2e7a63 - rustc_trans::base::trans_item::h8c1b1b17ce2b6f35
  82:        0x10c3032bb - _<base..TransItemsWithinModVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::hf2a5fda0a4c4bb41
  83:        0x10c300fb8 - rustc::hir::intravisit::walk_item::h67f5c670fcbad42a
  84:        0x10c2f0d8b - rustc_trans::base::trans_crate::hdb9f0761c2bb8e02
  85:        0x10bb61f1a - rustc_driver::driver::phase_4_translate_to_llvm::he77984ef06ab7894
  86:        0x10bb5fdc5 - rustc_driver::driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::h8579006d7304381a
  87:        0x10bb5c4d6 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::h4bf34c9820399d99
  88:        0x10bb55d1a - rustc::ty::context::TyCtxt::create_and_enter::hbfd876096454bbd0
  89:        0x10bb1e4ce - rustc_driver::driver::compile_input::hda370d330171d8d7
  90:        0x10bb0a804 - rustc_driver::run_compiler::ha942b7e1d33fe553
  91:        0x10bb077ef - std::panicking::try::call::h929be2db59c0ff06
  92:        0x10fcf5d6b - __rust_try
  93:        0x10fcf5d05 - __rust_maybe_catch_panic
  94:        0x10bb0830b - _<F as std..boxed..FnBox<A>>::call_box::h6fc56a5ebed87bf3
  95:        0x10fced3b8 - std::sys::thread::Thread::new::thread_start::h9e5bde00f3b3e2e2
  96:     0x7fff9566699c - _pthread_body
  97:     0x7fff95666919 - _pthread_start

error: Could not compile `synth`.

Caused by:
  Process didn't exit successfully: `rustc /Users/Kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/synth-0.10.0/src/lib.rs --crate-name synth --crate-type lib -g -C metadata=86d40d54110626b3 -C extra-filename=-86d40d54110626b3 --out-dir /Users/Kevin/Desktop/rust/synthingy/target/debug/deps --emit=dep-info,link -L dependency=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps -L dependency=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps --extern pitch_calc=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libpitch_calc-429f283552a491e9.rlib --extern envelope=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libenvelope-e3af18ed054e064b.rlib --extern utils=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libutils-ba36ae19185040ae.rlib --extern dsp=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libdsp-4e01ff51bb6d3db2.rlib --extern panning=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libpanning-dcdbcf51cac96068.rlib --extern rand=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/librand-49a08859d086fffe.rlib --extern gaussian=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libgaussian-6283fda8084362e5.rlib --extern time_calc=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libtime_calc-e67463ca9b5e40e4.rlib --extern num=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/libnum-262f3a136066b482.rlib --extern rustc_serialize=/Users/Kevin/Desktop/rust/synthingy/target/debug/deps/librustc_serialize-3561541d79c18212.rlib --cap-lints allow` (exit code: 101)
```

## Meta

```
rustc 1.10.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.10.0
```
and 
```
cargo 0.11.0 (259324c 2016-05-20)
```

**Comment by Aatch** [comment] 2016-08-01 05:58
Interestingly, @filmor seems to have encountered the same issue with the same crate. While he did make sure it was a completely fresh build, could you do the same? This ICE normally comes from having old crates around.

**Comment by arielb1** [comment] 2016-08-01 18:16
dupe of #34027.

**Closed by arielb1** 2016-08-01 18:16 UTC
Labels: I-ICE
