### ISSUE TITLE
#[inline] attributes should be validated before translation.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#45738] opened 2017-11-03 13:49 UTC
At the moment `#[inline]` attributes are validated by the compiler during translation because that's the first time they are actually used. However, as the compiler [gets more lazy](https://github.com/rust-lang/rust/pull/45575), an inline function might be exported without the `#[inline]` attribute ever being validate. This can lead to the case of getting an error message only when the function is used in a downstream crate.

To solve this issue, modify the compiler so that [compile-fail/E0534.rs](https://github.com/michaelwoerister/rust/blob/8d4c92f80d97bc0e42d935ce7d23f6e3083a4937/src/test/compile-fail/E0534.rs) passes if the inline function is not called from anywhere.

**Comment by nikomatsakis** [comment] 2017-11-03 14:05
Here are some mentoring instructions:

Currently, the `inline` attributes are parsed by [this call here](https://github.com/rust-lang/rust/blob/9f3b09116b742b2606dc5f36f9145e0c89e4010b/src/librustc_trans/attributes.rs#L99), in `librustc_trans`. Conveniently, the real logic is done by a function `find_inline_attr` that lives in `libsyntax` -- one of the base crates of rustc (see the README for details). This is convenient because it means that these attributes are available much earlier.

(Actually, a good first task is to make a failing test. We should be able to create one based on the changes from #45575.)

Probably the best place to handle this would be in [the `ast_validation` pass](https://github.com/rust-lang/rust/blob/9f3b09116b742b2606dc5f36f9145e0c89e4010b/src/librustc_passes/ast_validation.rs), which runs earlier in the compiler. It just walks the tree checking for various sanity checks.

Sadly, I am running out of battery now, so I may have to stop here! But some quick notes I can elaborate later:

- The current helper takes a slice of attributes. We could invoke it from `visit_item`, `visit_trait_item` and `visit_impl_item`, and that would work fine. 
- Alternatively, and what I like somewhat better, we could refactor that function into one that takes a slice and a second that optionally traverses a single attribute. Then we could add the `visit_attribute` callback into the AST validation and invoke the "parse inline attribute" function from there.

**Comment by jgouly** [comment] 2017-11-03 16:49
I'd like to have a go at fixing this.

**Comment by zackmdavis** [comment] 2017-11-03 17:29
(This is also #40792, and will likely surface some error-index [doctest failures](https://github.com/rust-lang/rust/blob/525b81d570/src/libsyntax/diagnostic_list.rs#L45).)

**Comment by nikomatsakis** [comment] 2017-11-03 18:45
@zackmdavis thanks, I closed that bug in favor of this one since this one seems to have more

**Comment by jgouly** [comment] 2017-11-04 11:27
Trying to create a test case for the various issues here:

    #[inline(boo)]
    pub fn something(){}
    
    struct MyStruct<T>(T);
    impl<T> MyStruct<T> {
        #[inline(foo)]
        pub fn f(self) {}
    }
    
    #[inline]
    type Foo = u32;
    
    struct Foo { #[inline] f: u32 }

I've been extending check_inline (https://github.com/rust-lang/rust/blob/200c4d041059dd233c2181ff0fd0997b08bdc755/src/librustc/hir/check_attr.rs#L61) to perform the checks that find_inline_attr (https://github.com/rust-lang/rust/blob/9f3b09116b742b2606dc5f36f9145e0c89e4010b/src/libsyntax/attr.rs#L532) was doing.
This currently diagnoses the first 3 errors, but the last one gives:

    warning: unused attribute
      --> y.rs:17:14
       |    
    17 | struct Foo { #[inline] f: u32 }
       |              ^^^^^^^^^
       |
       = note: #[warn(unused_attributes)] on by default

@nikomatsakis is that warning ok for the last one, or do you want to actually diagnose it as 'error[E0518]: attribute should be applied to function'.

**Comment by jgouly** [comment] 2017-11-05 15:24
I pushed some progress to: https://github.com/jgouly/rust/commit/9a8927b2d606b340350c68e64852548783a3a49c

One of the issues I'm seeing with asserting that the inline attribute is used after hir validation is this:

    $ cat hello.rs
    fn main() { println!("Hello world") }
    $ ASSERT=1 ATTR=1 RUST_BACKTRACE=1 ./build/x86_64-apple-darwin/stage1/bin/rustc hello.rs
    find_inline_attr attr = Attribute { id: AttrId(3517), style: Outer, path: path(inline), tokens: TokenStream { kind: Empty }, is_sugared_doc: false, span: src/libstd/sync/mpsc/mod.rs:1838:39: 1838:48 }
    error: internal compiler error: unexpected panic
    thread 'rustc' panicked at 'Attr should be marked as used already!', src/libsyntax/attr.rs:569:12
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    stack backtrace:
       0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
       1: std::sys_common::backtrace::print
       2: std::panicking::default_hook::{{closure}}
       3: std::panicking::default_hook
       4: std::panicking::rust_panic_with_hook
       5: std::panicking::begin_panic
       6: syntax::attr::find_inline_attr
       7: syntax::attr::requests_inline
       8: rustc_trans_utils::common::requests_inline
       9: rustc_trans_utils::trans_item::TransItemExt::instantiation_mode
      10: rustc_trans_utils::collector::InliningMap::record_accesses

But that line doesn't have an inline attribute: https://github.com/jgouly/rust/blob/gh45738/src/libstd/sync/mpsc/mod.rs#L1838

Any ideas?

**Comment by nikomatsakis** [comment] 2017-11-06 17:47
@jgouly 

> is that warning ok for the last one, or do you want to actually diagnose it as 'error[E0518]: attribute should be applied to function'.

I think that warning is OK. In particular, we can't really make this a hard-error without going through a big warning period and so forth -- [it would break existing code!](https://play.rust-lang.org/?gist=9504fe3157687b4b843e6bc4766378ee&version=stable) -- which means we would need a warning anyhow. Let's start with *just* the warning, and decide late if we ever want it to be a hard error. (The main problem I see is that if we ever *wanted* `#[inline]` to have some semantics there, it would affect how existing code works, but in any `#[inline]` happens to be the kind of attribute whose effects the user shouldn't really be able to "observe" anyway.)

**Comment by nikomatsakis** [comment] 2017-11-06 17:55
@jgouly hmm, I wonder if we synthesize fake inline attributes for closures or something. (@eddyb on IRC says no.) Seems curious.

**Comment by nikomatsakis** [comment] 2017-11-06 17:56
*Ah*, I suspect that the problem is that the attribute is actually on the `send` or `unwrap` function that is being called -- when we create a local, monomorphized copy in this crate, we presumably make an `#[attr]` that was never visited. You might fix it @jgouly by adding some check for whether the attribute is attached to something in the `LOCAL_CRATE` or not.

**Comment by jgouly** [comment] 2017-11-09 19:20
Been very busy and unable to make progress the last few days. Hoping to get this near finished at the weekend.

**Comment by jgouly** [comment] 2017-11-19 12:54
@nikomatsakis I have two problems now.

One is that the signature for check_attribute was changed to take an ast::Item, in my code I added visit_trait_item and visit_impl_item, so I have ast::TraitItem and ast::ImplItem, what's the best way to abstract over those items?

The other problem is the LOCAL_CRATE bit, that seems to come from hir::def_id, which I don't have yet as this is at the AST stage. How can I check at this point?

**Comment by jgouly** [comment] 2017-11-22 22:27
After talking with @arielb1 and @nikomatsakis on IRC, I'm going to remove the assert, it seems more hassle than it's worth.

For the check_attribute I'm just going to pass the item's span, than the item itself.

**Comment by jgouly** [comment] 2018-03-04 10:10
If it wasn't obvious, someone else should take this over! My code is here as a starting point: https://github.com/jgouly/rust/tree/gh45738

**Comment by michaelwoerister** [comment] 2021-06-17 09:25
@wesleywiser Is it possible that you fixed this a while ago? I remember you did some work around querifying attributes.

**Comment by jackh726** [comment] 2022-01-29 00:47
Closing as it looks like this has been fixed.

**Closed by jackh726** 2022-01-29 00:47 UTC
Labels: C-enhancement, A-diagnostics, E-mentor, T-compiler, WG-compiler-middle
