### ISSUE TITLE
regression: std no longer in toolchain dir

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#132202] opened 2024-10-26 21:40 UTC
https://crater-reports.s3.amazonaws.com/beta-1.83-3/beta-2024-10-19/reg/bevy_dexterous_developer_library-0.4.0-alpha.3/log.txt

root is in prefer-dynamic crate, probably just needs a compat note

**Comment by apiraino** [comment] 2024-10-30 12:49
I quickly skimmed [at the most recent merges](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Amerged+sort%3Acreated-desc+label%3Arelnotes) with `relnotes` and didn't find anything from `{t-libs,-api}` about that. Very likely have missed that, just wanted to check if it's tagged for the changelog

**Comment by jieyouxu** [comment] 2024-10-30 16:06
> I quickly skimmed [at the most recent merges](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Amerged+sort%3Acreated-desc+label%3Arelnotes) with `relnotes` and didn't find anything from `{t-libs,-api}` about that. Very likely have missed that, just wanted to check if it's tagged for the changelog

As discussed in https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23132202.20regression.3A.20std.20no.20longer.20in.20toolchain.20dir, this is probably T-bootstrap (and *maybe* weakly T-compiler) change from #131188.

cc @Kobzol as you may know more about this, but I suspect the prefer-dynamic crate was relying on undocumented unguaranteed behavior and that this isn't considered a "breakage" in the strict sense.

**Comment by cuviper** [comment] 2024-11-22 21:39
This will be documented as a compat note via #133352.

**Comment by jieyouxu** [comment] 2024-11-30 05:10
I think this can be closed since 1.83.0 is already released containing said compat notes?

**Comment by apiraino** [comment] 2024-12-02 10:10
I think so, so I will go and close this one.

This thing of closing regressions accepted for one reason or another was mentioned [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/242269-t-release.2Ftriage/topic/beta.20regressions.20that.20are.20no.20more/near/456509338) but I'd want to document this reasoning in some place to make it more "official" and discoverable.

**Closed by apiraino** 2024-12-02 10:10 UTC
Labels: T-compiler, regression-from-stable-to-beta, T-bootstrap
