### ISSUE TITLE
Dead links in docs

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#21478] opened 2015-01-21 19:57 UTC
Clicking the [src] link here: http://doc.rust-lang.org/std/sync/struct.Arc.html will show a "not found" page. It seems to be something to do with the redirect, as the [src] link on http://doc.rust-lang.org/alloc/arc/struct.Arc.html works fine.

Can dead links like this be detected automatically by a test?

**Comment by steveklabnik** [comment] 2015-01-21 20:00
> Can dead links like this be detected automatically by a test?

/cc https://github.com/rust-lang/rfcs/issues/669

I _believe_ that this particular issue is a dup of a rustdoc bug. /cc @Gankro ?

**Comment by Gankro** [comment] 2015-01-21 20:08
Dupe of https://github.com/rust-lang/rust/issues/15309

**Closed by Gankro** 2015-01-21 20:08 UTC
Labels: A-rustdoc

**Comment by tomjakubowski** [comment] 2015-01-21 20:10
https://github.com/rust-lang/rust/issues/15309#issuecomment-65671894 has a good explanation of the cause of this bug (and why it only crops up in the standard docs for `alloc` re-exports).
