### ISSUE TITLE
Regression bug: Code never stops compiling (rustc>=1.45)

### ISSUE THREAD

**Issue by hiaselhans** [rust-lang/rust#94029] opened 2022-02-15 21:27 UTC
### Code

reproducer:
https://github.com/hiaselhans/rust_reproducer

I tried this code:

```rust
pub fn foo(val: u128) -> u128 {
    let (_sum, carry) = val.overflowing_add(val);
    u128::from(carry) << 64
```

with 
```
[build]
target = "thumbv6m-none-eabi"
```

##### I expected to see this happen:

- code should compile

#### Instead, this happened:

- cargo/rustc never stops compiling.
- one thread is stuck at 100% use.

### Version it worked on

It most recently worked on: Rust 1.44

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-unknown-linux-gnu
release: 1.44.0
LLVM version: 9.0
```

### Version with regression

`rustc --version --verbose`:
```
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 10.0
```

### Related Issue / Crate

@tspiteri 's [fixed crate](https://crates.io/crates/fixed)
https://gitlab.com/tspiteri/fixed/-/issues/45

**Comment by est31** [comment] 2022-02-17 01:54
Probably due to the LLVM update to version 10. Could you try with the nightly `2020-05-19` and nightly `2020-05-22`?

**Comment by hiaselhans** [comment] 2022-02-17 08:22
exactly.

- 2020-05-19 compiles fine
- 2020-05-22 hangs

**Comment by apiraino** [comment] 2022-02-17 09:36
Additional observation: does not happen setting `opt-level=1` in the cargo.toml:
```
[profile.dev]
opt-level = 1
```

**Comment by nikic** [comment] 2022-02-17 11:19
Duplicate of #75045.

**Closed by nikic** 2022-02-17 11:19 UTC
Labels: C-bug, I-prioritize, regression-untriaged
