### ISSUE TITLE
Compiler bug: type parameter `T/#0` (T/0) out of range when substituting

### ISSUE THREAD

**Issue by nicbn** [rust-lang/rust#69296] opened 2020-02-19 19:00 UTC
### Code

```
unsafe fn f<T: ?Sized>(ptr: *mut T, new: *mut u8) -> *mut T {
    use std::mem;

    let mut parts: [*mut u8; mem::size_of::<*mut T>() / mem::size_of::<*mut u8>()] =
        mem::transmute(ptr);
    parts[0] = new;
    mem::transmute(parts)
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0-nightly (13db6501c 2020-02-01)
binary: rustc
commit-hash: 13db6501c7273cd1997ce20e15106f362e5613c4
commit-date: 2020-02-01
host: x86_64-pc-windows-msvc
release: 1.42.0-nightly
LLVM version: 9.0
```

### Error output

```
error: internal compiler error: src\librustc\ty\subst.rs:565: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(fn() -> usize {std::mem::size_of::<*mut T>})) substs=[]

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (13db6501c 2020-02-01) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: src\librustc\ty\subst.rs:565: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(fn() -> usize {std::mem::size_of::<*mut T>})) substs=[]

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rustc::ty::structural_impls::<impl rustc::ty::context::Lift for rustc_span::span_encoding::Span>::lift_to_tcx
   8: rustc::ich::impls_hir::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext> for rustc_attr::builtin::InlineAttr>::hash_stable
   9: rustc::ich::impls_hir::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext> for rustc_attr::builtin::InlineAttr>::hash_stable
  10: rustc::util::bug::bug_fmt
  11: <rustc::ty::trait_def::TraitImpls as rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext>>::hash_stable
  12: <rustc::ty::trait_def::TraitImpls as rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext>>::hash_stable
  13: rustc::util::bug::bug_fmt
  14: rustc::util::bug::bug_fmt
  15: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  16: rustc::ty::structural_impls::<impl rustc::ty::context::Lift for rustc::ty::ParamEnv>::lift_to_tcx
  17: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  18: rustc::ty::error::<impl rustc::ty::TyS>::prefix_string
  19: rustc::ty::structural_impls::<impl rustc::ty::context::Lift for rustc::ty::ParamEnv>::lift_to_tcx
  20: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  21: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_const
  22: <rustc::mir::ProjectionElem<rustc::mir::Local,&rustc::ty::TyS> as rustc_mir::dataflow::move_paths::abs_domain::Lift>::lift
  23: <rustc::mir::ProjectionElem<rustc::mir::Local,&rustc::ty::TyS> as rustc_mir::dataflow::move_paths::abs_domain::Lift>::lift
  24: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
  25: <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt
  26: <rustc_mir::util::collect_writes::FindLocalAssignmentVisitor as rustc::mir::visit::Visitor>::visit_local
  27: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  28: <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt
  29: <rustc_mir::util::collect_writes::FindLocalAssignmentVisitor as rustc::mir::visit::Visitor>::visit_local
  30: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  31: rustc::ty::print::pretty::<impl core::fmt::Display for rustc::ty::sty::ProjectionTy>::fmt
  32: rustc::middle::weak_lang_items::<impl rustc::ty::context::TyCtxt>::is_weak_lang_item
  33: rustc::dep_graph::graph::DepGraph::assert_ignored
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::try_print_query_stack
  35: rustc::mir::interpret::queries::<impl rustc::ty::context::TyCtxt>::const_eval_resolve
  36: <rustc::traits::project::AssocTypeNormalizer as rustc::ty::fold::TypeFolder>::fold_const
  37: rustc::ty::structural_impls::<impl rustc::ty::context::Lift for rustc::ty::ParamEnv>::lift_to_tcx
  38: <rustc::traits::project::AssocTypeNormalizer as rustc::ty::fold::TypeFolder>::fold_ty
  39: <rustc_traits::lowering::ClauseDumper as rustc_hir::intravisit::Visitor>::visit_struct_field
  40: <chalk_engine::ExClause<rustc_traits::chalk_context::ChalkArenas> as rustc_traits::chalk_context::Upcast>::upcast
  41: <rustc_typeck::check::FnCtxt as rustc_typeck::astconv::AstConv>::normalize_ty
  42: <rustc_typeck::variance::terms::InferredIndex as core::fmt::Debug>::fmt
  43: <rustc_typeck::check::GatherLocalsVisitor as rustc_hir::intravisit::Visitor>::visit_local
  44: <rustc_typeck::namespace::Namespace as core::fmt::Debug>::fmt
  45: <rustc_typeck::check::GatherLocalsVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  46: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  47: <rustc_typeck::check::fixup_opaque_types::FixupFolder as rustc::ty::fold::TypeFolder>::fold_ty
  48: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  49: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  50: <rustc_typeck::namespace::Namespace as core::fmt::Debug>::fmt
  51: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  52: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  53: <rustc_typeck::check::CheckItemTypesVisitor as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_item
  54: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  55: <rustc_typeck::namespace::Namespace as core::fmt::Debug>::fmt
  56: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  57: rustc_typeck::check_crate
  58: rustc_interface::passes::QueryContext::print_stats
  59: <rustc_span::symbol::SymbolStr as core::fmt::Display>::fmt
  60: rustc_driver::pretty::print_after_hir_lowering
  61: <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref
  62: rustc_driver::pretty::print_after_hir_lowering
  63: rustc_driver::pretty::print_after_hir_lowering
  64: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  65: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  66: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  67: _rust_maybe_catch_panic
  68: rustc_driver::pretty::print_after_hir_lowering
  69: ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Send$u2b$core..marker..Sync$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  70: std::sys::windows::thread::Thread::new
  71: BaseThreadInitThunk
  72: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (13db6501c 2020-02-01) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [const_eval_raw] const-evaluating `f::{{constant}}#0`
#1 [const_eval_validated] const-evaluating + checking `f::{{constant}}#0`
#2 [const_eval_validated] const-evaluating + checking `f::{{constant}}#0`
#3 [typeck_tables_of] processing `f`
#4 [typeck_item_bodies] type-checking all item bodies
#5 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

</p>
</details>

**Comment by pnkfelix** [comment] 2020-02-20 13:32
triage: P-high. Removing nomination. Assigning to self.

**Comment by pnkfelix** [comment] 2020-03-05 14:44
triage: according to godbolt, this has ICE'd the compiler for as long as this the relevant methods were made const fn's.

which to me means this is not a critical bug

I'm leaving at P-high for now.

**Comment by pnkfelix** [comment] 2020-03-10 19:40
When  trying variants like:

```rust
unsafe fn g<T: ?Sized>(ptr: *mut T, new: *mut u8) {
    const S: usize = ::std::mem::size_of::<*mut T>();
    let mut parts: [u8; S];
}
```

I got the following error diagnostic:

```
error[E0401]: can't use generic parameters from outer function
  --> issue-69296.rs:12:47
   |
11 | unsafe fn g<T: ?Sized>(ptr: *mut T, new: *mut u8) {
   |             - type parameter from outer function
12 |     const S: usize = std::mem::size_of::<*mut T>();
   |                                               ^ use of generic parameter from outer function

error[E0080]: evaluation of constant value failed
  --> issue-69296.rs:13:25
   |
13 |     let mut parts: [u8; S];
   |                         ^ referenced constant has errors

error: aborting due to 2 previous errors
```

So, that to me implies that we're just missing some similar check somewhere in the code paths for array length constant evaluation.

**Comment by eddyb** [comment] 2020-03-26 19:42
This is a duplicate of #43408 (of which tend to be many, sadly).

**Closed by eddyb** 2020-03-26 19:42 UTC
Labels: C-bug, I-ICE, P-high, T-compiler, glacier
