### ISSUE TITLE
Macros: Unexpected token when metavariable is "tt", works with "expr"

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#27231] opened 2015-07-23 10:50 UTC
http://is.gd/GKzXeD

```rust
struct S(u8);

macro_rules! mac {
    ( $val:tt ) => ( S($val) );
    //( $val:expr ) => ( S($val) );
}

fn main() {
    let s: S = mac!(4);
    println!("{}", s.0);
}
```

```
<anon>:4:24: 4:28 error: unexpected token: `4`
<anon>:4     ( $val:tt ) => ( S($val) );
                                ^~~~
```

The token `4` should be perfectly valid there. Replacing `tt` with `expr` in the macro "fixes" this, but since `expr` is much stricter, this limits what can be expressed.

Is this intended behaviour?

Related: #24145

**Comment by jonas-schievink** [comment] 2015-07-23 13:56
Indirecting via another macro that interprets the `tt` as an `expr` works around the issue as well:
```rust
struct S(u8);

macro_rules! mkexpr {
    ( $e:expr ) => ( $e );
}

macro_rules! mac {
    //( $val:tt ) => ( S($val) );   // Doesn't work
    ( $val:tt ) => ( S(mkexpr!($val)) );
}

fn main() {
    let s: S = mac!(4);
    println!("{}", s.0);
}
```

**Comment by huonw** [comment] 2015-10-27 06:35
Dupe of https://github.com/rust-lang/rust/issues/5846. Thanks for filing!

**Closed by huonw** 2015-10-27 06:35 UTC
Labels: A-macros
