### ISSUE TITLE
Borrow checker permits use after move in if statements

### ISSUE THREAD

**Issue by Xaeroxe23** [rust-lang/rust#37891] opened 2016-11-20 10:21 UTC
Below code when compiled with Rust 1.13 (current stable) and Rust 1.15 (current nightly) will result in segmentation faults and memory corruption.  The unwrap call in the else if should consume the value and prevent further use but it does not.

```
fn main() {
    let vec = get_vec();
    if let Err(err) = vec {
        println!("Got an error: {:?}", err);
    }
    else if vec.unwrap().len() == 0 {
        println!("Vec was 0 length.");
    }
    else {
        for i in vec.unwrap() {
            println!("{}", i);
        }
    }
}

fn get_vec() -> Result<Vec<i32>, i32> {
    Ok::<Vec<i32>, i32>(vec![1,2,3])
}
```

I expected: the borrow checker to mark the for loop as a use after move due to calling unwrap() after the value had been consumed by checking it in the else if statement

What happened: The borrow checker did not prevent this from compiling which resulted in segfaults and memory corruption.

Reproduction tip: You will get slightly different behavior of this code on each execution as memory errors are a bit finicky like that, if it works the first time try it a few more times, I'm sure you'll see it crash before you get to 5 attempts.

## Meta
`rustc --version --verbose`:
rustc 1.15.0-nightly (ac635aa95 2016-11-18)
binary: rustc
commit-hash: ac635aa95ba851898e125b047ad7b8d6a8fecf8e
commit-date: 2016-11-18
host: x86_64-pc-windows-gnu
release: 1.15.0-nightly
LLVM version: 3.9

**Comment by TimNN** [comment] 2016-11-20 18:50
Related to, maybe a duplicate of #31287.

**Comment by Xaeroxe23** [comment] 2016-11-21 05:07
I agree, the issues are very similar.  Not knowing a ton about Rust compiler internals myself, my first thought is that the if let pattern and the match guard pattern may even create the same MIR.

**Comment by nikomatsakis** [comment] 2016-12-01 21:26
when desugared into HIR, this pretty-prints as:

```
use std::prelude::v1::*;
#[macro_use]
extern crate std as std;
fn main() {
              let vec = get_vec();
              match vec {
                  Err(err) => {

                      $crate::io::_print(::std::fmt::Arguments::new_v1({
                                                                           static __STATIC_FMTSTR:
                                                                                  &'static [&'static str]
                                                                                  =
                                                                               &["Got an error: ",
                                                                                 "\n"];
                                                                           __STATIC_FMTSTR
                                                                       },
                                                                       &match (&err,)
                                                                            {
                                                                            (__arg0,)
                                                                            =>
                                                                            [::std::fmt::ArgumentV1::new(__arg0,
                                                                                                         ::std::fmt::Debug::fmt)],
                                                                        }));
                  }
                  _ if vec.unwrap().len() == 0 => {
                      $crate::io::_print(::std::fmt::Arguments::new_v1({
                                                                           static __STATIC_FMTSTR:
                                                                                  &'static [&'static str]
                                                                                  =
                                                                               &["Vec was 0 length.\n"];
                                                                           __STATIC_FMTSTR
                                                                       },
                                                                       &match ()
                                                                            {
                                                                            ()
                                                                            =>
                                                                            [],
                                                                        }));
                  }
```

so I agree it's a dup of #31287. But definitely bad. We should move on fixing these. The plan of record has been MIR borrowck, however.

**Comment by nikomatsakis** [comment] 2016-12-01 21:29
Closing as a duplicate of #31287.

**Closed by nikomatsakis** 2016-12-01 21:29 UTC
Labels: A-borrow-checker, I-nominated, I-wrong, T-compiler

**Comment by nikomatsakis** [comment] 2016-12-01 21:31
Hmm, there is an argument for keeping this open, and addressing it by tweaking the desugaring, just because that can be done quickly, even if it's just a workaround.

**Comment by Xaeroxe23** [comment] 2016-12-03 06:48
If you can hit two birds with one stone by fixing 31287 though why bother addressing this?
