### ISSUE TITLE
 undefined reference to `_Unwind_Resume'

### ISSUE THREAD

**Issue by Jovons** [rust-lang/rust#84580] opened 2021-04-26 09:22 UTC
I am using Windows7, Mingw64, gcc is 
`gcc.exe (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0`
rustc is 1.51.0
```
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\tiina\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```
The issue is, when rustc compiles, it generates 32 `.o` files, but gcc is 64. So linker results in error.  
If I use 32 gcc, the link error is gone. I don't understand why rustc compiles with 32. I didn't have a ~/.cargo/config, and I even tried `cargo build --target=x86_64-pc-windows-gnu --verbose`. And I used 64 rustup_init.exe to install rust. 

```
 Compiling autocfg v1.0.1
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling proc-macro2 v1.0.26
   Compiling tinyvec_macros v0.1.0
   Compiling unicode-xid v0.2.1
   Compiling winapi v0.3.9
   Compiling libc v0.2.92
   Compiling syn v1.0.68
     Running `rustc --crate-name autocfg 'C:\Users\tiina\.cargo\registry\src\github.com-1ecc6299db9ec823\autocfg-1.0.1\src\lib.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=96b366d2a11339db -C extra-filename=-96b366d2a11339db --out-dir 'G:\workspace_rh\bbc\study2\diesel_demo\target\debug\deps' -L 'dependency=G:\workspace_rh\bbc\study2\diesel_demo\target\debug\deps' --cap-lints allow`

left out so many compilings...

   Compiling num-traits v0.2.14
     Running `rustc --crate-name build_script_build 'C:\Users\tiina\.cargo\registry\src\github.com-1ecc6299db9ec823\num-traits-0.2.14\build.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=6ab214958e0c460d -C extra-filename=-6ab214958e0c460d --out-dir 'G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\num-traits-6ab214958e0c460d' -L 'dependency=G:\workspace_rh\bbc\study2\diesel_demo\target\debug\deps' --extern 'autocfg=G:\workspace_rh\bbc\study2\diesel_demo\target\debug\deps\libautocfg-96b366d2a11339db.rlib' --cap-lints allow`
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.0.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.1.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.10.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.11.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.12.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.13.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.14.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.15.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.2.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.3.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.4.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.5.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.6.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.7.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.8.rcgu.o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.9.rcgu.o" "-o" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.exe" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\\build_script_build-02bf8129c9ba2a3f.dxhobp3qk1a4djr.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "G:\\workspace_rh\\bbc\\study2\\diesel_demo\\target\\debug\\deps" "-L" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-b3e05fb1c668425d.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-de6b1e1839bc55c3.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-d462ba5d23db4375.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-91f359062fcc4faa.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-1285b73e96b90384.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-2e399a6f31e1ac65.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-cdd2f8d624f05ca0.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-dfacd2ffb7ac7d0f.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-113950dd2d010a25.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-acaab9dfbd2da45f.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-c8a337935bf5603e.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-e81d86989503275b.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-037111c82a639dfe.rlib" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-78a80358c99fdc57.rlib" "-Wl,--end-group" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-ae4f14151f891fbb.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\tiina\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.0.rcgu.o: In function `build_script_build::main':
          C:\Users\tiina\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\build.rs:7: undefined reference to `_Unwind_Resume'
          G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.0.rcgu.o: In function `build_script_build::main::{{closure}}':
          C:\Users\tiina\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\build.rs:14: undefined reference to `_Unwind_Resume'
          G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.10.rcgu.o: In function `std::sys_common::backtrace::__rust_begin_short_backtrace':
          /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\std\src\sys_common/backtrace.rs:121: undefined reference to `_Unwind_Resume'
          G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.10.rcgu.o: In function `core::ops::function::FnOnce::call_once':
          /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ops/function.rs:227: undefined reference to `_Unwind_Resume'
          G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.10.rcgu.o: In function `core::ptr::drop_in_place<alloc::vec::Vec<u8>>':
          /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\core\src\ptr/mod.rs:179: undefined reference to `_Unwind_Resume'
          G:\workspace_rh\bbc\study2\diesel_demo\target\debug\build\winapi-x86_64-pc-windows-gnu-02bf8129c9ba2a3f\build_script_build-02bf8129c9ba2a3f.build_script_build.d3m6gegl-cgu.13.rcgu.o:/rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\std\src/env.rs:204: more undefined references to `_Unwind_Resume' follow
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libpanic_unwind-de6b1e1839bc55c3.rlib(panic_unwind-de6b1e1839bc55c3.panic_unwind.6i2g34lh-cgu.0.rcgu.o): In function `panic_unwind::real_imp::panic':
          /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\panic_unwind\src\gcc.rs:62: undefined reference to `_Unwind_RaiseException'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libpanic_unwind-de6b1e1839bc55c3.rlib(panic_unwind-de6b1e1839bc55c3.panic_unwind.6i2g34lh-cgu.0.rcgu.o): In function `rust_eh_personality':
          /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\panic_unwind\src\gcc.rs:273: undefined reference to `_GCC_specific_handler'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-d462ba5d23db4375.rlib(object-d462ba5d23db4375.object.3t6ssgfm-cgu.0.rcgu.o):object.3t6ssgfm-cg:(.text+0xa10c): undefined reference to `_Unwind_Resume'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-d462ba5d23db4375.rlib(object-d462ba5d23db4375.object.3t6ssgfm-cgu.0.rcgu.o):object.3t6ssgfm-cg:(.text+0xae9f): undefined reference to `_Unwind_Resume'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-d462ba5d23db4375.rlib(object-d462ba5d23db4375.object.3t6ssgfm-cgu.0.rcgu.o):object.3t6ssgfm-cg:(.text+0xf1e2): undefined reference to `_Unwind_Resume'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-d462ba5d23db4375.rlib(object-d462ba5d23db4375.object.3t6ssgfm-cgu.0.rcgu.o):object.3t6ssgfm-cg:(.text+0x11fe2): undefined reference to `_Unwind_Resume'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libobject-d462ba5d23db4375.rlib(object-d462ba5d23db4375.object.3t6ssgfm-cgu.0.rcgu.o):object.3t6ssgfm-cg:(.text+0x129c7): undefined reference to `_Unwind_Resume'
          C:\Users\tiina\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\lib\libgimli-1285b73e96b90384.rlib(gimli-1285b73e96b90384.gimli.5q92ydjl-cgu.0.rcgu.o):gimli.5q92ydjl-cgu:(.text+0x2e0a): more undefined references to `_Unwind_Resume' follow
          collect2.exe: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `winapi-x86_64-pc-windows-gnu`
```

**Comment by wh201906** [comment] 2021-12-08 04:56
I have the same issue as yours. Then I use mingw-w64 with seh(x86_64-8.1.0-posix-seh-rt_v6-rev0 rather than x86_64-8.1.0-posix-sjlj-rt_v6-rev0). Everything works fine now.

**Comment by mati865** [comment] 2022-09-27 15:06
Rust doesn't support SJLJ exception model for windows-gnu targets, I'm unaware of any plans to change it.

**Comment by Dylan-DPC** [comment] 2023-02-21 13:29
Closing this as duplicate of #53301

**Closed by Dylan-DPC** 2023-02-21 13:29 UTC
