### ISSUE TITLE
Future is not Send as this value is used across an await (even though I explicitly drop the value)

### ISSUE THREAD

**Issue by vedantroy** [rust-lang/rust#83631] opened 2021-03-29 04:05 UTC
Reference rustlang forums question: https://users.rust-lang.org/t/future-is-not-send-as-this-value-is-used-across-an-await-but-i-drop-the-value-before-the-await/57574

I tried this code:

```rust
async fn process(url: Url) -> Result<()> {
    let bytes = fetch(url.clone()).await?;
    let page = String::from_utf8(bytes.clone())?;
    let page = kuchiki::parse_html().one(page);

    drop(page);
    let links: Vec<Url> = vec![];
    for url in &links {
        add_url(&url).await.unwrap();
    }
    Ok(())
}
```

I expected to see this happen: *this could should compile (assuming there are no compile errors outside of this function)*

Instead, this happened:
I get the following error. This error seems confusing because I explicitly `drop` `page` before the `await`.

Furthermore, in a different code sample (presented below this error message) that does the same thing (I think), this error does not show up.
```
error: future cannot be sent between threads safely
   --> src/main.rs:310:22
    |
310 |         let handle = tokio::spawn(async move {
    |                      ^^^^^^^^^^^^ future created by async block is not `Send`
    | 
   ::: /home/vedantroy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/task/spawn.rs:129:21
    |
129 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::spawn`
    |
    = help: within `impl futures::Future`, the trait `std::marker::Send` is not implemented for `Rc<Node>`
note: future is not `Send` as this value is used across an await
   --> src/main.rs:253:9
    |
238 |     let page = kuchiki::parse_html().one(page);
    |         ---- has type `NodeRef` which is not `Send`
...
253 |         add_url(url).await.unwrap();
    |         ^^^^^^^^^^^^^^^^^^ await occurs here, with `page` maybe used later
...
256 | }
    | - `page` is later dropped here

error: aborting due to previous error; 1 warning emitted

error: could not compile `get-training-data`
```

Here is the different code sample that works. Instead of explicitly dropping, I use a block to get the value of `links`. However, I don't see why there should be a different. After-all, in the previous example I explicitly `drop` `page`.

```
async fn process(url: Url) -> Result<()> {
    let links = {
        let bytes = fetch(url.clone()).await?;
        // TODO: Is there a way to do this w/o clone?
        let page = String::from_utf8(bytes.clone())?;
        let page = kuchiki::parse_html().one(page);
        let input = get_training_input(&page).ok_or(anyhow!("No training input for: {:?}", url))?;
        let output = get_training_output(&page, &url);

        get_links(&page, url)
    };
    for url in &links {
        add_url(url).await.unwrap();
    }
    Ok(())
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0```

**Comment by jonas-schievink** [comment] 2021-03-29 10:13
duplicate of https://github.com/rust-lang/rust/issues/57478

**Closed by jonas-schievink** 2021-03-29 10:13 UTC
Labels: C-bug
