### ISSUE TITLE
Assertion failed when building ring

### ISSUE THREAD

**Issue by zethra** [rust-lang/rust#79538] opened 2020-11-29 18:25 UTC
### Code

Build [ring](https://crates.io/crates/ring). This isn't my library so I'm not sure what is causing the issue exactly. I'm specifically building latest master (`7514f7a4170439527ac802f223fcd203593614c7`) but version 0.16.16 also has the same error.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (6a889570e 2020-11-27)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:1268 ~ ring[8a88]::digest::sha2::)`,
 right: `DefId(0:1269 ~ ring[8a88]::digest::sha2::::GFp_sha256_block_data_order)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (6a889570e 2020-11-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [index_hir] index HIR
#1 [hir_owner] HIR owner of `{misc#0}`
end of query stack
error: could not compile `ring`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6a889570e46c03d7b156ec08f3f4cb4d145924a3/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/6a889570e46c03d7b156ec08f3f4cb4d145924a3/library/core/src/panicking.rs:92:14
   2: rustc_middle::hir::map::collector::NodeCollector::insert_entry
   3: rustc_hir::intravisit::walk_item
   4: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   5: rustc_hir::intravisit::walk_item
   6: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   7: rustc_hir::intravisit::walk_item
   8: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   9: rustc_middle::hir::map::index_hir
  10: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::get_query_impl
  14: core::ops::function::FnOnce::call_once
  15: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::get_query_impl
  19: rustc_middle::hir::map::Map::expect_item
  20: rustc_middle::hir::map::Map::visit_item_likes_in_module
  21: rustc_passes::hir_id_validator::check_crate
  22: rustc_interface::passes::analysis
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  24: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  25: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  26: rustc_data_structures::stack::ensure_sufficient_stack
  27: rustc_query_system::query::plumbing::get_query_impl
  28: rustc_interface::passes::QueryContext::enter
  29: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  30: rustc_span::with_source_map
  31: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-11-29 18:31
duplicate of https://github.com/rust-lang/rust/issues/79487

**Closed by jonas-schievink** 2020-11-29 18:31 UTC
Labels: C-bug, I-ICE, T-compiler
