### ISSUE TITLE
Incremental Compilation needs to rebuild everything when feature gates are changed

### ISSUE THREAD

**Issue by oberien** [rust-lang/rust#47820] opened 2018-01-28 10:54 UTC
Given this example:

main.rs
```rust
#![feature(nll)]

mod foo;

fn main() {
    foo::foo();
}
```

foo.rs
```rust
pub fn foo() -> Vec<usize> {
    let mut vec = Vec::new();
    vec.push(vec.len());
    vec
}
```

Without the feature gate `nll`, `foo::foo` won't compile, because `vec` is borrowed by `vec.push` which doesn't allow `vec.len` to borrow it again. With `nll`, this is solved and the code compiles.
With the annotation in main.rs, `cargo build` will build everything just fine.
After a successful build if we remove `#[feature(nll)]` and execute `cargo build` again, everything still compiles, even though it shouldn.

I think that this is due to incremental compilation. Cargo reuses the old module `foo` instead of recompiling it. If it would recompile it (e.g. after adding a newline to the end of foo.rs), the build breaks as expected.

**Comment by oberien** [comment] 2018-01-28 11:07
Oh wait, this belongs to cargo, doesn't it?

**Comment by alexcrichton** [comment] 2018-01-30 16:29
cc @michaelwoerister 

@oberien thanks for the report! I think this is a rustc issue because Cargo is reinvoking the compiler, but it looks like stale results may be getting used by incremental compilation?

**Comment by nikomatsakis** [comment] 2018-02-08 15:34
We should probably include the features in the hash of command line options that we give, I guess.

**Comment by nikomatsakis** [comment] 2018-02-08 15:35
triage: P-medium

**Comment by nikomatsakis** [comment] 2018-02-08 15:35
Well, I'll triage as P-high just to make sure @michaelwoerister sees this.

triage: P-high

**Comment by michaelwoerister** [comment] 2018-02-12 12:09
This is a duplicate of https://github.com/rust-lang/rust/issues/47003.

**Comment by nikomatsakis** [comment] 2018-02-12 20:00
Shall we close it then, @michaelwoerister ?

**Comment by michaelwoerister** [comment] 2018-02-13 09:46
Yes, closing as duplicate. Moving over the P-high tag to the original.

**Closed by michaelwoerister** 2018-02-13 09:46 UTC
Labels: A-incr-comp, C-bug, P-high, T-compiler
