### ISSUE TITLE
Tracking Issue for constifying `Result` methods that drop values

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#92384] opened 2021-12-29 02:01 UTC
Feature gate: `#![feature(const_result_drop)]`

### Public API

This is a tracking issue for the `const_result_drop` feature, which includes constness for the following methods:

```rust
impl<T, E> Result<T, E> {
    // will drop error
    pub const fn ok(self) -> Option<T>
    where
        E: ~const Drop;

    // will drop ok
    pub const fn err(self) -> Option<E>
    where
        T: ~const Drop;

    // will drop error or the argument
    pub const fn and<U>(self, res: Result<U, E>) -> Result<U, E>
    where
        T: ~const Drop,
        U: ~const Drop,
        E: ~const Drop;
    
    // will drop ok or the argument
    pub const fn or<F>(self, res: Result<T, F>) -> Result<T, F>
    where
        T: ~const Drop,
        E: ~const Drop,
        F: ~const Drop;

    // will drop error or the argument
    pub const fn unwrap_or(self, default: T) -> T
    where
        T: ~const Drop,
        E: ~const Drop;
}
```

Note that these depend on the semantics for `~const Drop`, which is (probably) tracked in #67792.

### Steps / History

- [x] Implementation: #92385
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by clarfonthey** [comment] 2021-12-29 02:07
Turns out you actually can't make these const, at least for now. So, closing.

**Comment by clarfonthey** [comment] 2021-12-29 16:43
Reopened now that I've found a proper way to do this. Linked the tracking issue for `~const` since this depends on the semantics of `~const Drop`.

**Comment by jhpratt** [comment] 2022-03-17 03:07
Duplicate of #82814?

**Comment by clarfonthey** [comment] 2022-03-17 03:10
That appears to be a meta tracking issue, this is specifically for these methods.

**Comment by jhpratt** [comment] 2022-03-17 03:12
At least when I created it, it was not intended to be a meta issue. `Result::as_mut` and `Result::transpose` point directly to that as their tracking issue.

**Comment by clarfonthey** [comment] 2022-03-17 03:13
Yes, but for now, these methods point to this one, since they presumably would need their own FCP.

**Comment by jhpratt** [comment] 2022-03-17 03:14
I figured it would be a partial stabilization of #82814. Not a big deal either way, just wanted to bring it to your attention :slightly_smiling_face:

**Comment by RalfJung** [comment] 2024-09-08 07:13
This got removed by https://github.com/rust-lang/rust/pull/110393.

**Closed by RalfJung** 2024-09-08 07:13 UTC
Labels: T-libs-api, C-tracking-issue, F-const_trait_impl
