### ISSUE TITLE
internal compiler error: unexpected panic - thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 2'

### ISSUE THREAD

**Issue by Sakul6499** [rust-lang/rust#99336] opened 2022-07-16 16:33 UTC
### Code

Not Rust code (at least not mine), trying to install [grcov]() to get Code Coverage reports inside GitHub Actions working, script is:

```YAML
name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup nightly toolchain
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    # Clean workspace
    - uses: actions-rs/cargo@v1
      with:
        command: clean

    # Run tests
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast  # Customize args for your own needs
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

    # Run grcov
    - id: coverage  
      uses: actions-rs/grcov@v0.1

    # Codecov.io upload
    - uses: codecov/codecov-action@v3
```  

**However, the failing (panicing) command is simply this:**

```Shell
cargo install grcov
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (23e21bdd2 2022-07-15) running on x86_64-unknown-linux-gnu
```

### Error output

```
  error: internal compiler error: unexpected panic
  Error: internal compiler error: unexpected panic
  note: the compiler unexpectedly panicked. this is a bug.
  
  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
  
  note: rustc 1.64.0-nightly (23e21bdd2 2022-07-15) running on x86_64-unknown-linux-gnu
  
  note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto
  
  note: some of the compiler flags provided by cargo are hidden
  
  query stack during panic:
  end of query stack
  error: could not compile `time`
  warning: build failed, waiting for other jobs to finish...
  error: failed to compile `grcov v0.8.11`, intermediate artifacts can be found at `/tmp/cargo-installBLAbYP`
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
  /home/runner/.cargo/bin/cargo install grcov
      Updating crates.io index
   Downloading crates ...
    Downloaded grcov v0.8.11
    Installing grcov v0.8.11
   Downloading crates ...
    Downloaded anyhow v1.0.58
    Downloaded failure v0.1.8
    Downloaded fnv v1.0.7
    Downloaded fastrand v1.7.0
    Downloaded digest v0.10.3
    Downloaded either v1.7.0
    Downloaded num-traits v0.2.15
    Downloaded generic-array v0.12.4
    Downloaded once_cell v1.13.0
    Downloaded rustc-demangle v0.1.21
    Downloaded adler v1.0.2
    Downloaded addr2line v0.17.0
    Downloaded backtrace v0.3.66
    Downloaded rayon v1.5.3
    Downloaded num_threads v0.1.6
    Downloaded serde v1.0.139
    Downloaded structopt-derive v0.4.18
    Downloaded tempfile v3.3.0
    Downloaded simplelog v0.12.0
    Downloaded slug v0.1.4
    Downloaded gimli v0.26.1
    Downloaded textwrap v0.11.0
    Downloaded walkdir v2.3.2
    Downloaded time v0.1.44
    Downloaded rustc-cfg v0.4.0
    Downloaded pest_generator v2.1.3
    Downloaded percent-encoding v2.1.0
    Downloaded is_executable v1.0.1
    Downloaded cargo-binutils v0.3.6
    Downloaded structopt v0.3.26
    Downloaded uncased v0.9.7
    Downloaded unic-char-range v0.9.0
    Downloaded unic-ucd-version v0.9.0
    Downloaded rustc-hash v1.1.0
    Downloaded remove_dir_all v0.5.3
    Downloaded same-file v1.0.6
    Downloaded rustc_version v0.4.0
    Downloaded siphasher v0.3.10
    Downloaded scopeguard v1.1.0
    Downloaded sha-1 v0.8.2
    Downloaded thread_local v1.1.4
    Downloaded vec_map v0.8.2
    Downloaded unic-common v0.9.0
    Downloaded proc-macro-error-attr v1.0.4
    Downloaded atty v0.2.14
    Downloaded autocfg v1.1.0
    Downloaded phf_codegen v0.10.0
    Downloaded block-buffer v0.10.2
    Downloaded phf_generator v0.10.0
    Downloaded block-padding v0.1.5
    Downloaded pest_derive v2.1.0
    Downloaded cargo-platform v0.1.2
    Downloaded chrono-tz-build v0.0.2
    Downloaded humansize v1.1.1
    Downloaded fomat-macros v0.3.1
    Downloaded failure_derive v0.1.8
    Downloaded fake-simd v0.1.2
    Downloaded digest v0.8.1
    Downloaded opaque-debug v0.2.3
    Downloaded deunicode v0.4.3
    Downloaded phf v0.10.1
    Downloaded heck v0.3.3
    Downloaded phf_shared v0.10.0
    Downloaded md-5 v0.10.1
    Downloaded itoa v1.0.2
    Downloaded memoffset v0.6.5
    Downloaded maplit v1.0.2
    Downloaded num_cpus v1.13.1
    Downloaded stable_deref_trait v1.2.0
    Downloaded pkg-config v0.3.25
    Downloaded msvc-demangler v0.9.0
    Downloaded globwalk v0.8.1
    Downloaded rand_chacha v0.3.1
    Downloaded rayon-core v1.9.3
    Downloaded semver v1.0.12
    Downloaded quick-xml v0.23.0
    Downloaded termcolor v1.1.3
    Downloaded serde_derive v1.0.139
    Downloaded ryu v1.0.10
    Downloaded time v0.3.11
    Downloaded toml v0.5.9
    Downloaded ucd-trie v0.1.4
    Downloaded regex v1.6.0
    Downloaded uuid v0.8.2
    Downloaded unicode-xid v0.2.3
    Downloaded unicode-width v0.1.9
    Downloaded aho-corasick v0.7.18
    Downloaded version_check v0.9.4
    Downloaded unicode-segmentation v1.9.0
    Downloaded time-macros v0.2.4
    Downloaded ansi_term v0.12.1
    Downloaded serde_json v1.0.82
    Downloaded pest_meta v2.1.3
    Downloaded crc32fast v1.3.2
    Downloaded chrono v0.4.19
    Downloaded cargo_metadata v0.14.2
    Downloaded pest v2.1.3
    Downloaded crossbeam-epoch v0.9.9
    Downloaded crossbeam-deque v0.8.1
    Downloaded cc v1.0.73
    Downloaded camino v1.0.9
    Downloaded crossbeam-channel v0.5.5
    Downloaded clap v2.34.0
    Downloaded zip v0.6.2
    Downloaded symbolic-common v8.8.0
    Downloaded ppv-lite86 v0.2.16
    Downloaded num-integer v0.1.45
    Downloaded miniz_oxide v0.5.3
    Downloaded memmap2 v0.5.5
    Downloaded debugid v0.7.3
    Downloaded rand v0.8.5
    Downloaded smallvec v1.9.0
    Downloaded rand_core v0.6.3
    Downloaded memchr v2.5.0
    Downloaded tera v1.16.0
    Downloaded ignore v0.4.18
    Downloaded strsim v0.8.0
    Downloaded byte-tools v0.3.1
    Downloaded uuid v1.1.2
    Downloaded block-buffer v0.7.3
    Downloaded globset v0.4.9
    Downloaded flate2 v1.0.24
    Downloaded crossbeam-utils v0.8.10
    Downloaded symbolic-demangle v8.8.0
    Downloaded unic-segment v0.9.0
    Downloaded unic-char-property v0.9.0
    Downloaded bstr v0.2.17
    Downloaded regex-syntax v0.6.27
    Downloaded cpp_demangle v0.3.5
    Downloaded libc v0.2.126
    Downloaded chrono-tz v0.6.1
    Downloaded generic-array v0.14.5
    Downloaded object v0.29.0
    Downloaded getrandom v0.2.7
    Downloaded byteorder v1.4.3
    Downloaded bitflags v1.3.2
    Downloaded unic-ucd-segment v0.9.0
    Downloaded typenum v1.15.0
    Downloaded synstructure v0.12.6
    Downloaded proc-macro-error v1.0.4
    Downloaded parse-zoneinfo v0.3.0
    Downloaded crypto-common v0.1.5
    Downloaded libz-sys v1.1.8
     Compiling libc v0.2.126
     Compiling version_check v0.9.4
     Compiling proc-macro2 v1.0.40
     Compiling cfg-if v1.0.0
     Compiling quote v1.0.20
     Compiling unicode-ident v1.0.2
     Compiling syn v1.0.98
     Compiling memchr v2.5.0
     Compiling autocfg v1.1.0
     Compiling serde_derive v1.0.139
     Compiling serde v1.0.139
     Compiling cc v1.0.73
     Compiling once_cell v1.13.0
     Compiling crossbeam-utils v0.8.10
     Compiling siphasher v0.3.10
     Compiling ppv-lite86 v0.2.16
     Compiling adler v1.0.2
     Compiling log v0.4.17
     Compiling regex-syntax v0.6.27
     Compiling bitflags v1.3.2
     Compiling typenum v1.15.0
     Compiling itoa v1.0.2
     Compiling unicode-xid v0.2.3
     Compiling pkg-config v0.3.25
     Compiling ucd-trie v0.1.4
     Compiling gimli v0.26.1
     Compiling failure_derive v0.1.8
     Compiling rustc-demangle v0.1.21
     Compiling semver v1.0.12
     Compiling serde_json v1.0.82
     Compiling ryu v1.0.10
     Compiling maplit v1.0.2
     Compiling rayon-core v1.9.3
     Compiling fnv v1.0.7
     Compiling lazy_static v1.4.0
     Compiling scopeguard v1.1.0
     Compiling unicode-width v0.1.9
     Compiling unic-char-range v0.9.0
     Compiling same-file v1.0.6
     Compiling unic-common v0.9.0
     Compiling camino v1.0.9
     Compiling crc32fast v1.3.2
     Compiling cpp_demangle v0.3.5
     Compiling strsim v0.8.0
     Compiling ansi_term v0.12.1
     Compiling unicode-segmentation v1.9.0
     Compiling uuid v0.8.2
     Compiling vec_map v0.8.2
     Compiling anyhow v1.0.58
     Compiling time-macros v0.2.4
     Compiling stable_deref_trait v1.2.0
     Compiling symbolic-demangle v8.8.0
     Compiling deunicode v0.4.3
     Compiling num_threads v0.1.6
     Compiling either v1.7.0
     Compiling byteorder v1.4.3
     Compiling remove_dir_all v0.5.3
     Compiling termcolor v1.1.3
     Compiling fastrand v1.7.0
     Compiling percent-encoding v2.1.0
     Compiling humansize v1.1.1
     Compiling fomat-macros v0.3.1
     Compiling is_executable v1.0.1
     Compiling smallvec v1.9.0
     Compiling rustc-hash v1.1.0
     Compiling uncased v0.9.7
     Compiling generic-array v0.14.5
     Compiling proc-macro-error-attr v1.0.4
     Compiling proc-macro-error v1.0.4
     Compiling num-traits v0.2.15
     Compiling memoffset v0.6.5
     Compiling crossbeam-epoch v0.9.9
     Compiling num-integer v0.1.45
     Compiling rayon v1.5.3
     Compiling thread_local v1.1.4
     Compiling backtrace v0.3.66
     Compiling miniz_oxide v0.5.3
     Compiling msvc-demangler v0.9.0
     Compiling libz-sys v1.1.8
     Compiling pest v2.1.3
     Compiling addr2line v0.17.0
     Compiling textwrap v0.11.0
     Compiling unic-char-property v0.9.0
     Compiling walkdir v2.3.2
     Compiling unic-ucd-version v0.9.0
     Compiling debugid v0.7.3
     Compiling heck v0.3.3
     Compiling slug v0.1.4
     Compiling pest_meta v2.1.3
     Compiling unic-ucd-segment v0.9.0
     Compiling getrandom v0.2.7
     Compiling atty v0.2.14
     Compiling time v0.1.44
     Compiling memmap2 v0.5.5
     Compiling num_cpus v1.13.1
     Compiling time v0.3.11
  thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 2', compiler/rustc_builtin_macros/src/format.rs:1001:28
  stack backtrace:
     0:     0x7fb5bda30930 - std::backtrace_rs::backtrace::libunwind::trace::hc933fa0cb8627706
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     1:     0x7fb5bda30930 - std::backtrace_rs::backtrace::trace_unsynchronized::h821571732dd332a1
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x7fb5bda30930 - std::sys_common::backtrace::_print_fmt::h557d50ac4a63aebc
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x7fb5bda30930 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h76b8147c2bdde75b
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x7fb5bda89f0c - core::fmt::write::h5d8be78170c85a1a
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/fmt/mod.rs:1198:17
     5:     0x7fb5bda21f35 - std::io::Write::write_fmt::h506eb24e7560f644
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/io/mod.rs:1672:15
     6:     0x7fb5bda335c1 - std::sys_common::backtrace::_print::h2201ccbfedce10bc
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x7fb5bda335c1 - std::sys_common::backtrace::print::hfac17af9266b406b
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x7fb5bda335c1 - std::panicking::default_hook::{{closure}}::h391a6c901adb4324
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:295:22
     9:     0x7fb5bda33293 - std::panicking::default_hook::hba36336a5210bb57
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:314:9
    10:     0x7fb5be25bc11 - rustc_driver[ce628f6b2a67333f]::DEFAULT_HOOK::{closure#0}::{closure#0}
    11:     0x7fb5bda33d96 - std::panicking::rust_panic_with_hook::hf5a9c547fa70e52e
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:702:17
    12:     0x7fb5bda33be7 - std::panicking::begin_panic_handler::{{closure}}::h458eb96a30055863
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:588:13
    13:     0x7fb5bda30e14 - std::sys_common::backtrace::__rust_end_short_backtrace::he0b6e245c28401ce
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/sys_common/backtrace.rs:138:18
    14:     0x7fb5bda33912 - rust_begin_unwind
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/panicking.rs:584:5
    15:     0x7fb5bd9f7c53 - core::panicking::panic_fmt::h9776dcd13d59b560
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:142:14
    16:     0x7fb5bd9f7b92 - core::panicking::panic_bounds_check::hc49ce542f03c88ff
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/core/src/panicking.rs:84:5
    17:     0x7fb5c067beb8 - rustc_builtin_macros[555fb7b74bb18701]::format::expand_preparsed_format_args
    18:     0x7fb5c06755fc - rustc_builtin_macros[555fb7b74bb18701]::format::expand_format_args_impl
    19:     0x7fb5bffb625d - <rustc_expand[315316ef4f9feff3]::expand::MacroExpander>::fully_expand_fragment
    20:     0x7fb5c0b17f8b - <rustc_expand[315316ef4f9feff3]::expand::MacroExpander>::expand_crate
    21:     0x7fb5c0450dd2 - <rustc_session[a00dc85a9977996c]::session::Session>::time::<core[675039967b0ce395]::result::Result<rustc_ast[5a87b50f347d23c0]::ast::Crate, rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_interface[7690044e2c4491ef]::passes::configure_and_expand::{closure#1}>
    22:     0x7fb5c0443bd7 - <rustc_interface[7690044e2c4491ef]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[7690044e2c4491ef]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[675039967b0ce395]::result::Result<rustc_ast[5a87b50f347d23c0]::ast::Crate, rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>
    23:     0x7fb5c043c3e2 - <rustc_interface[7690044e2c4491ef]::queries::Queries>::expansion
    24:     0x7fb5c040575c - <rustc_interface[7690044e2c4491ef]::interface::Compiler>::enter::<rustc_driver[ce628f6b2a67333f]::run_compiler::{closure#1}::{closure#2}, core[675039967b0ce395]::result::Result<core[675039967b0ce395]::option::Option<rustc_interface[7690044e2c4491ef]::queries::Linker>, rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>
    25:     0x7fb5c04019bf - rustc_span[715bcd6866f3f365]::with_source_map::<core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_interface[7690044e2c4491ef]::interface::create_compiler_and_run<core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_driver[ce628f6b2a67333f]::run_compiler::{closure#1}>::{closure#1}>
    26:     0x7fb5c041dc40 - rustc_interface[7690044e2c4491ef]::interface::create_compiler_and_run::<core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_driver[ce628f6b2a67333f]::run_compiler::{closure#1}>
    27:     0x7fb5c0431d72 - <scoped_tls[e6e812a5eee10b50]::ScopedKey<rustc_span[715bcd6866f3f365]::SessionGlobals>>::set::<rustc_interface[7690044e2c4491ef]::interface::run_compiler<core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_driver[ce628f6b2a67333f]::run_compiler::{closure#1}>::{closure#0}, core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>
    28:     0x7fb5c0403f2f - std[ed8ee9cb5bbd555]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7690044e2c4491ef]::util::run_in_thread_pool_with_globals<rustc_interface[7690044e2c4491ef]::interface::run_compiler<core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_driver[ce628f6b2a67333f]::run_compiler::{closure#1}>::{closure#0}, core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>::{closure#0}, core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>
    29:     0x7fb5c041e099 - <<std[ed8ee9cb5bbd555]::thread::Builder>::spawn_unchecked_<rustc_interface[7690044e2c4491ef]::util::run_in_thread_pool_with_globals<rustc_interface[7690044e2c4491ef]::interface::run_compiler<core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>, rustc_driver[ce628f6b2a67333f]::run_compiler::{closure#1}>::{closure#0}, core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>::{closure#0}, core[675039967b0ce395]::result::Result<(), rustc_errors[d21ca108a24cfd08]::ErrorGuaranteed>>::{closure#1} as core[675039967b0ce395]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
    30:     0x7fb5bda3d7e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb12c75146d360fc4
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/alloc/src/boxed.rs:1934:9
    31:     0x7fb5bda3d7e3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he05a53703329061d
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/alloc/src/boxed.rs:1934:9
    32:     0x7fb5bda3d7e3 - std::sys::unix::thread::Thread::new::thread_start::h45088dc5029897c3
                                 at /rustc/23e21bdd25026e2839ebe946c2a937c1904887d2/library/std/src/sys/unix/thread.rs:108:17
    33:     0x7fb5bd954609 - start_thread
    34:     0x7fb5bd877133 - clone
    35:                0x0 - <unknown>
  
  error: internal compiler error: unexpected panic
  Error: internal compiler error: unexpected panic
  note: the compiler unexpectedly panicked. this is a bug.
  
  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
  
  note: rustc 1.64.0-nightly (23e21bdd2 2022-07-15) running on x86_64-unknown-linux-gnu
  
  note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto
  
  note: some of the compiler flags provided by cargo are hidden
  
  query stack during panic:
  end of query stack
  error: could not compile `time`
  warning: build failed, waiting for other jobs to finish...
  error: failed to compile `grcov v0.8.11`, intermediate artifacts can be found at `/tmp/cargo-installBLAbYP`
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

</p>
</details>

**Comment by ehuss** [comment] 2022-07-16 17:03
Thanks for the report! Closing as a duplicate of #99261. This should be fixed by #99263 and should be in the next nightly.

**Closed by ehuss** 2022-07-16 17:03 UTC
Labels: I-ICE, T-compiler, C-bug
