### ISSUE TITLE
File from Path with Windows' invalid characters silently fails

### ISSUE THREAD

**Issue by Demiu** [rust-lang/rust#108409] opened 2023-02-23 20:24 UTC
I tried this code:

```rust
use std::path::PathBuf;
use std::fs::File;
use std::io::Write;

fn main() {
    let mut pb = PathBuf::new();
    pb.push("ok:err");
    pb.set_extension("ext");
    let mut file = File::create(pb).unwrap();
    file.write_all(b"test").unwrap();
    file.flush().unwrap();
}
```

I expected to see this happen: Since : is not allowed in filenames on windows I expected the filename to either be "okerr.ext" or at least "ok.ext". set_extension is a separate call and I would like it to be respected even if a previous push "failed". Expected a file with either of these names to be created and it's contents to be "test". Or, to receive an error if the write or flush fail.

Instead, this happened: A file named "ok" was created. It was empty even though neither of the unwraps failed.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-pc-windows-msvc
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by ChrisDenton** [comment] 2023-02-24 04:37
The `:` character denotes an [NTFS file stream](https://learn.microsoft.com/en-us/windows/win32/fileio/file-streams). When you create a file like "ok:err.ext" then you're opening a file called "ok" with the stream "err.ext".

In powershell you can view file streams using the command `Get-Item 'ok' -Stream *`.

Rust's path handling is currently not aware of file streams. See also #107276.

**Comment by workingjubilee** [comment] 2023-02-24 08:35
Is this a valid bug report, @ChrisDenton?

**Comment by ChrisDenton** [comment] 2023-02-24 08:43
I mean, it's a valid concern. But the path handling aspect would make this a duplicate of #107276. And making `File::create` error on file streams would need some very strong justification (and some alternative way to actually use file streams).

**Comment by workingjubilee** [comment] 2023-02-24 08:50
Fair enough. Needs a decision on the latter half then.

**Comment by joshtriplett** [comment] 2023-07-12 16:00
Closing as a duplicate of https://github.com/rust-lang/rust/issues/107276

**Closed by joshtriplett** 2023-07-12 16:00 UTC
Labels: T-libs-api, C-bug
