### ISSUE TITLE
Nested macros can't define any new variables

### ISSUE THREAD

**Issue by reem** [rust-lang/rust#26329] opened 2015-06-16 00:56 UTC
Example: http://is.gd/9LFIF2

The outer macro attempts to parse the new variables as existing ones, and errors when it can't find them.

**Comment by mitsuhiko** [comment] 2015-08-02 17:53
I just ran into this.  Very annoying issue.  If it's too hard to make the identity nesting work it would be possible to just use `$$` to refer to nested variables (with added repetition at each new level).

**Comment by mitsuhiko** [comment] 2015-08-02 17:55
This seems to be a duplicate of #6994.

**Comment by alexcrichton** [comment] 2015-08-03 17:18
Thanks for the reference @mitsuhiko!

**Closed by alexcrichton** 2015-08-03 17:18 UTC
Labels: A-macros
