### ISSUE TITLE
Incorrect "unused import" on using statement for `panic_handler` symbol declaration/definition

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#56957] opened 2018-12-18 20:37 UTC
Developing with no_std on an armv6, an incorrect "unused import" message is generated (1.33.0 nightly):

```
warning: unused import: `panic_semihosting`
  --> src/main.rs:29:5
   |
29 | use panic_semihosting;
   |     ^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default
```

The `use panic_semihosting` statement is required to pull the `panic_semihosting` crate's `panic_handler` symbol into the project, or else the following error occurs:

```
error: `#[panic_handler]` function required, but not found
```

**Comment by aurabindo** [comment] 2019-03-04 09:06
Happens on riscv32 no_std as well

**Comment by therealprof** [comment] 2019-03-04 09:48
Since 1.33 stable you can do `use panic_semihosting as _;`

**Comment by Enselic** [comment] 2023-11-20 09:56
Triage: Can this still be reproduced without the workaround? Wanted to ask since 5 years has passed and circumstances might have changed.

**Comment by ehuss** [comment] 2024-04-03 20:59
This still reproduces. However, I'm going to close this as a duplicate of #109261 which has a little bit more info (it is a general problem with any lang item).

**Closed by ehuss** 2024-04-03 20:59 UTC
Labels: A-lint, C-bug
