### ISSUE TITLE
fresh install on Windows 10, simple program gets linker error.

### ISSUE THREAD

**Issue by Nuclearfossil** [rust-lang/rust#30319] opened 2015-12-11 06:05 UTC
Installation of Rust 1.5 on windows 10 machine via this link: https://static.rust-lang.org/dist/rust-1.5.0-x86_64-pc-windows-msvc.msi

Visual Studio 2013 and 2015 are already installed as well as the associated Visual Studio extensions for Rust.

Generate a simple test program, as follows:

helloworld.rs
```
fn main()
{
	println!("Hello World!");
}
```

Running rustc through the new rust shell as follows:
```
rustc helloworld.rs
```

emits the following:

```
D:\dev\rust\helloworld>rustc helloworld.rs
error: linking with `link.exe` failed: exit code: 1181
note: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC/bin\\amd64\\link.exe" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC/lib\\amd64" "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.10586.0\\ucrt\\x64" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib" "helloworld.0.o" "/OUT:helloworld.exe" "/OPT:REF,ICF" "/DEBUG" "/LIBPATH:C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib" "/LIBPATH:D:\\dev\\rust\\helloworld\\.rust\\bin\\x86_64-pc-windows-msvc" "/LIBPATH:D:\\dev\\rust\\helloworld\\bin\\x86_64-pc-windows-msvc" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcollections-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_unicode-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\librand-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-35c36e89.rlib" "C:\\Program Files\\Rust stable 1.5\\bin\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-35c36e89.rlib" "ws2_32.lib" "userenv.lib" "advapi32.lib" "kernel32.lib" "shell32.lib" "msvcrt.lib" "compiler-rt.lib"
note: LINK : fatal error LNK1181: cannot open input file 'ws2_32.lib'

error: aborting due to previous error
```

Any ideas?

**Comment by retep998** [comment] 2015-12-11 10:10
Duplicate of https://github.com/rust-lang/rust/issues/30229

**Comment by alexcrichton** [comment] 2015-12-11 13:48
Indeed this is a dupe, thanks for the report though!

**Closed by alexcrichton** 2015-12-11 13:48 UTC

**Comment by Nuclearfossil** [comment] 2015-12-11 17:34
No worries. I did do a search looking for those symptoms.  Apparently my google-fu was weak yesterday.

**Comment by TomasHubelbauer** [comment] 2016-03-26 10:06
@Nuclearfossil Did you actually resolve this? I followed the link to issue #30229 and then to pull request #135. The way I understood it it was only necessary to run the `vcvars64.bat` file and things should work, so I did that, restarted Visual Studio (I also installed Rust through the MSVC MSI and am using the Rust extension for Visual Studio) and it didn't help. I'm getting the same error. Any pointers?

**Comment by Nuclearfossil** [comment] 2016-03-26 15:06
I've actually given up on Rust on the win32/64 platform for the time being.

**Comment by TomasHubelbauer** [comment] 2016-03-26 15:08
Thanks for the reply. :)

**Comment by qtamaki** [comment] 2017-11-15 11:53
I try add component "C++/CLI Support" by VS2017 installer.

**Comment by retep998** [comment] 2017-11-15 15:46
@qtamaki 
"C++/CLI Support" is not the component you want. That merely installs Managed C++ which is very different from the native C++ toolchain that Rust relies on.
