### ISSUE TITLE
Rustdoc: searching for "try_" doesn't show `try_send` and `try_recv`

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#46151] opened 2017-11-21 10:31 UTC
After typing "try_" into the search box, the results don't show methods `try_send` and `try_recv` from mpsc channels: https://doc.rust-lang.org/nightly/std/?search=try_

In fact, I don't think any of the presented results contain "try_" as substring anywhere. This is a bit odd.

**Comment by kennytm** [comment] 2017-11-21 19:39
Duplicate of #46021.

**Closed by kennytm** 2017-11-21 19:39 UTC
Labels: A-rustdoc, C-bug
