### ISSUE TITLE
Compiler panic when returning generator that yields reference

### ISSUE THREAD

**Issue by soro** [rust-lang/rust#46414] opened 2017-11-30 22:55 UTC
Minimized it as much as possible. Happens when lifetime is elided and generator is returned from method in impl block.

rustc 1.23.0-nightly (e21df8020 2017-11-13) running on x86_64-apple-darwin

[playground example](https://play.rust-lang.org/?gist=1065b7ca7e6f9acbaa790efd43660d72&version=nightly)

**Comment by arielb1** [comment] 2017-12-17 03:07
This is a duplicate of the impl trait lifetime elision bug, and has been fixed on nightly.

**Closed by arielb1** 2017-12-17 03:07 UTC
Labels: A-generators, C-bug, I-ICE, T-compiler
