### ISSUE TITLE
`warnings` is both a lint check and lint group

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust#45004] opened 2017-10-03 15:52 UTC
It appears impossible to deny all warnings and then warn for specific warning lint checks using `rustc` CLI parameters. One clear inconsistency that could be connected to this issue is that `warnings` is both a ‘lint check’ and a ‘lint group’.

```sh
rustc -W help
```

```
Lint checks provided by rustc:


                                         name  default  meaning
                                         ----  -------  -------
...
                                     warnings  warn     mass-change the level for lints which produce warnings
...
Lint groups provided by rustc:

                   name  sub-lints
                   ----  ---------
               warnings  all built-in lints
```

## Meta
```sh
rustc 1.22.0-nightly (185cc5f26 2017-10-02)
```

**Comment by zackmdavis** [comment] 2017-10-04 05:46
Duplicate of #41941. The [relevant code is in librustc/lint/levels.rs](https://github.com/rust-lang/rust/blob/f1938cf13b3/src/librustc/lint/levels.rs#L104-L115).

**Comment by RalfJung** [comment] 2020-08-18 13:04
Closing as duplicate.

**Closed by RalfJung** 2020-08-18 13:04 UTC
Labels: A-lint, C-enhancement
