### ISSUE TITLE
Internal compiler error, index out of bounds 

### ISSUE THREAD

**Issue by mgolub2** [rust-lang/rust#24474] opened 2015-04-15 19:13 UTC
I'm working on making rustboot work with the current rust nightly, and I am getting this output on compiling that ported code:

    RUST_BACKTRACE=1 rustc -O --target i686-unknown-linux-gnu --crate-type lib -o out.r --emit obj       main.rs
    error: internal compiler error: unexpected panic 
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust- lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: run with `RUST_BACKTRACE=1` for a backtrace
    thread 'rustc' panicked at 'index out of bounds: the len is 71 but the index is 71', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcollections/vec.rs:1358

    stack backtrace:
       1:        0x106fa0f2f - sys::backtrace::write::h075c290842c07241pSs
       2:        0x106fa9532 - panicking::on_panic::h5c42739cafe04010yQw
       3:        0x106f5f765 - rt::unwind::begin_unwind_inner::hcf6664e3afb4ed87hyw
       4:        0x106f5faf6 - rt::unwind::begin_unwind_fmt::h213281714a9d2341Vww
       5:        0x106fa908c - rust_begin_unwind
       6:        0x107002975 - panicking::panic_fmt::he51f1189e8161c3eSEC
       7:        0x1070109e8 - panicking::panic_bounds_check::hd46f6cc251228c72YDC
       8:        0x104246db6 -  middle::lang_items::LanguageItemCollector<'a>::collect_item::h18b1b0ae1ea915bdoHB
       9:        0x10424a9a1 - middle::lang_items::collect_language_items::hb102d33bddca3031aLB
      10:        0x1036e9474 - driver::phase_3_run_analysis_passes::h3ab988320c8f706fnGa
      11:        0x1036cd13c - driver::compile_input::h17f91a438cc7ef9aQba
      12:        0x103794893 - run_compiler::h5b3cf9f561f26f65F4b
      13:        0x1037923ba - boxed::F.FnBox<A>::call_box::h11605613984023911351
      14:        0x103791857 - rt::unwind::try::try_fn::h149173525045656329
      15:        0x1070322f8 - rust_try_inner
      16:        0x1070322e5 - rust_try
      17:        0x103791b30 - boxed::F.FnBox<A>::call_box::h11950230058861771556
      18:        0x106fa807d - sys::thread::create::thread_start::hfd5d0d6a18df65c3gVv
      19:     0x7fff8dd17267 - _pthread_body
      20:     0x7fff8dd171e4 - _pthread_start

Not sure what line in my code is causing this to happen, so I can't provide a minimal example.
##rustc --verbose --version

    rustc 1.0.0-nightly (16e1fcead 2015-04-15) (built 2015-04-14)
    binary: rustc
    commit-hash: 16e1fcead14628701e1b10b9d00c898d748db2ed
    commit-date: 2015-04-15
    build-date: 2015-04-14
    host: x86_64-apple-darwin
    release: 1.0.0-nightly

**Comment by arielb1** [comment] 2015-04-16 13:51
Which lang-items did you use? We don't try to detect broken lang-items ATM.

**Comment by perlun** [comment] 2015-10-19 20:49
Is this one still relevant?

**Comment by arielb1** [comment] 2015-10-19 21:10
@perlun 

I couldn't reproduce it.

**Comment by mgolub2** [comment] 2015-10-20 03:28
Seems to be okay now

**Comment by perlun** [comment] 2015-10-20 05:04
Great. Then I suggest we close this one.

**Closed** 2015-10-20 05:09 UTC
Labels: I-ICE
