### ISSUE TITLE
LLVM does not support PGO on Windows with -Cpanic=unwind

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#61002] opened 2019-05-21 09:53 UTC
LLVM's "IR-level" instrumentation, which is used by `rustc` to generate PGO instrumented binaries, does not yet work with exception handling on Windows MSVC. The problem has been reported to LLVM for C++ here: https://bugs.llvm.org/show_bug.cgi?id=41279

This also affects Rust programs built with `-Cpanic=unwind` for Windows MSVC. As long as LLVM does not support exception handling there, it is a known limitation that PGO can only be used with `-Cpanic=abort` on this platform.

**Comment by michaelwoerister** [comment] 2019-05-21 10:08
PGO does not yet work on `windows-gnu` for other reasons (see https://github.com/rust-lang/rust/issues/61002). Once it does, we should check if this problem is specific to MSVC.

**Comment by mati865** [comment] 2019-05-21 10:35
I have working x86_64 windows-gnu (64 bit builds use SEH) build with PGO I'll open PR once https://github.com/rust-lang/rust/pull/60981 is merged.
I can do testing in meantime.

FWIW simple hello world example works fine after going through PGO.

**Comment by michaelwoerister** [comment] 2019-05-21 11:24
@mati865 if you test, be sure to compile your LLVM with assertions: https://github.com/rust-lang/rust/pull/61005/files#diff-1c226b200b9385d77428f0b4418366e4R1277

Thanks for looking into it!

**Comment by mati865** [comment] 2019-05-21 11:27
I'll recompile it with assertions today later. Should the test case be using any specific code like `panic!()`?

**Comment by michaelwoerister** [comment] 2019-05-21 12:15
The following test case runs into the problem with MSVC:
https://github.com/rust-lang/rust/blob/master/src/test/run-make-fulldeps/pgo-use/main.rs

See https://github.com/rust-lang/rust/blob/master/src/test/run-make-fulldeps/pgo-use/Makefile for how the file is compiled.

**Comment by mati865** [comment] 2019-05-21 21:19
It does **not** reproduce with gnu toolchain with Rust and LLVM assertions enabled, I'll try to remember about fixing https://github.com/rust-lang/rust/pull/61005 along with gnu profiler.

**Comment by michaelwoerister** [comment] 2019-05-22 08:40
Cool!

**Comment by michaelwoerister** [comment] 2019-05-28 13:34
I just confirmed that (for me locally) PGO seems to work on Windows GNU. That is, I built `ripgrep` with instrumentation, ran it, and rebuilt it with the profiling data collected. It worked just fine, no crashes. So I updated the original issue text to just mention MSVC instead of Windows in general.

**Comment by EricRahm** [comment] 2019-06-08 00:18
It looks like #61005 is a bit too aggressive with its error reporting. For example when invoking rustc, but *not* compiling in our Firefox build we can the following [build error](https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=250280322&repo=try&lineNumber=6434-6446):

> 00:53:01     INFO -  error: failed to run `rustc` to learn about target-specific information
> 00:53:01     INFO -  Caused by:
> 00:53:01     INFO -    process didn't exit successfully: `z:/task_1559774436/build/src/rustc/bin/rustc.exe - --crate-name ___ --print=file-names -C opt-level=2 -C debuginfo=2 --cap-lints warn '-Zpgo-gen=rust-%m.profraw' --target i686-pc-windows-msvc --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (exit code: 1)
> 00:53:01     INFO -  --- stdout
> 00:53:01     INFO -  ___.exe
> 00:53:01     INFO -  lib___.rlib
> 00:53:01     INFO -  ___.dll
> 00:53:01     INFO -  ___.dll
> 00:53:01     INFO -  ___.lib
> 00:53:01     INFO -  ___.dll
> 00:53:01     INFO -  --- stderr
> 00:53:01     INFO -  error: Profile-guided optimization does not yet work in conjunction with `-Cpanic=unwind` on Windows when targeting MSVC. See https://github.com/rust-lang/rust/issues/61002 for details.
> 00:53:01    ERROR -  error: aborting due to previous error

I'm not sure the best solution while mw is away; perhaps we should revert #61005 for now.

**Comment by nikomatsakis** [comment] 2019-06-11 18:44
Maybe we can just convert the error to a warning?

**Comment by nikomatsakis** [comment] 2019-06-11 18:48
Not the best long-term solution but seems ok

**Comment by tmandry** [comment] 2020-07-08 23:25
It looks like the [upstream bug](https://bugs.llvm.org/show_bug.cgi?id=41279) was marked fixed a year ago. What's the status of this issue in rustc?

**Closed** 2021-07-22 15:10 UTC
Labels: A-LLVM, O-windows-msvc, T-compiler
