### ISSUE TITLE
type parameter `OpaqueType/#0` (OpaqueType/0) out of range when substituting, substs=[]

### ISSUE THREAD

**Issue by prejrdev** [rust-lang/rust#76648] opened 2020-09-12 17:25 UTC
### Code

```Rust
use std::mem;

struct OpaqueTag{
    offset: usize,
    len: usize,
    start_date: i128,
}

struct TagBlock<OpaqueType: ?Sized> {
    valid: u16, 
    tags: [OpaqueType; Self::FIELD_LEN],
}


impl<OpaqueType: ?Sized> TagBlock<OpaqueType> {
    const FIELD_LEN: usize = 16;
    const TAG_SIZE: usize = mem::size_of::<OpaqueType>();
    const TYPE_SIZE: usize = mem::size_of::<Self>();

    pub fn change<'lf>(&'lf mut self, i: usize, valid: bool) -> Option<&'lf mut OpaqueType>{
        None
    }

    pub fn tag<'lf>(&'lf self, i: usize) -> Option<&'lf OpaqueType> {
        
        None
    }   
}

fn main(){}
```

### Meta

`rustc --version --verbose`:
```
- 1.46.0
- beta 1.47
- nightly 
```

### Error output

```
error: internal compiler error: src/librustc_middle/ty/subst.rs:529:17: type parameter `OpaqueType/#0` (OpaqueType/0) out of range when substituting, substs=[]

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', /rustc/aa30bf3442be752e9f8dc9ff7fe70c258d41ac6b/src/librustc_errors/lib.rs:873:9
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::span_bug
   2: rustc_errors::Handler::span_bug
   3: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   4: rustc_middle::ty::context::tls::with_opt::{{closure}}
   5: rustc_middle::ty::context::tls::with_opt
   6: rustc_middle::util::bug::opt_span_bug_fmt
   7: rustc_middle::util::bug::span_bug_fmt
   8: <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
   9: rustc_middle::ty::fold::TypeFoldable::fold_with
  10: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::consts::Const>::super_fold_with
  11: <rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::TypeFolder>::fold_const
  12: rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::subst_and_normalize_erasing_regions
  13: rustc_mir::interpret::eval_context::InterpCx<M>::push_stack_frame
  14: rustc_mir::const_eval::eval_queries::const_eval_raw_provider
  15: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_raw>::compute
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::get_query_impl
  19: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  20: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  22: rustc_data_structures::stack::ensure_sufficient_stack
  23: rustc_query_system::query::plumbing::get_query_impl
  24: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  25: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  26: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  27: rustc_data_structures::stack::ensure_sufficient_stack
  28: rustc_query_system::query::plumbing::get_query_impl
  29: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id
  30: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_resolve
  31: <rustc_trait_selection::traits::project::AssocTypeNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_const
  32: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::TyS>::super_fold_with
  33: <rustc_trait_selection::traits::project::AssocTypeNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  34: rustc_data_structures::stack::ensure_sufficient_stack
  35: rustc_trait_selection::traits::project::normalize
  36: <rustc_infer::infer::InferCtxt as rustc_trait_selection::infer::InferCtxtExt>::partially_normalize_associated_types_in
  37: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  38: rustc_infer::infer::InferCtxtBuilder::enter
  39: rustc_typeck::check::wfcheck::check_item_well_formed
  40: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_item_well_formed>::compute
  41: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  42: rustc_data_structures::stack::ensure_sufficient_stack
  43: rustc_query_system::query::plumbing::get_query_impl
  44: rustc_query_system::query::plumbing::ensure_query_impl
  45: rustc_data_structures::sync::par_for_each_in
  46: rustc_hir::hir::Crate::par_visit_all_item_likes
  47: rustc_session::session::Session::track_errors
  48: rustc_typeck::check_crate
  49: rustc_interface::passes::analysis
  50: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  51: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  52: rustc_data_structures::stack::ensure_sufficient_stack
  53: rustc_query_system::query::plumbing::get_query_impl
  54: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  55: rustc_span::with_source_map
  56: rustc_interface::interface::create_compiler_and_run
  57: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.3 (aa30bf344 2020-09-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [const_eval_raw] const-evaluating `TagBlock::tags::{{constant}}#0`
#1 [const_eval_validated] const-evaluating + checking `TagBlock::tags::{{constant}}#0`
#2 [const_eval_validated] const-evaluating + checking `TagBlock::tags::{{constant}}#0`
#3 [check_item_well_formed] checking that `TagBlock` is well-formed
#4 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

```

</p>
</details>

**Comment by deltaphc** [comment] 2020-09-12 17:29
A more minimal reproduction based on a discussion elsewhere.

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=babd8a8ffccd4670304ec15cf9a3bd11

```rs
struct Foo<T: ?Sized> {
    bar: [T; Self::LENGTH],
}

impl<T: ?Sized> Foo<T> {
    const LENGTH: usize = 10;
}
```

**Comment by jonas-schievink** [comment] 2020-09-12 17:31
Duplicate of https://github.com/rust-lang/rust/issues/43408

**Closed by jonas-schievink** 2020-09-12 17:31 UTC
Labels: C-bug, I-ICE, T-compiler
