### ISSUE TITLE
Docs for fetch_add/fetch_sub/pow and overflow behavior

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#40916] opened 2017-03-29 23:56 UTC
[fetch_add](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicIsize.html#method.fetch_add) [fetch_sub](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicIsize.html#method.fetch_sub) [pow](https://doc.rust-lang.org/std/primitive.isize.html#method.pow)

Do docs for those methods need to explain what happens on overflow? There are three possible overflow behaviors: panic, saturate, wrap. Is it obvious what those methods do on overflow?

Perhaps we should explain? I guess `fetch_add` and `fetch_sub` wrap around, while `pow` panics in debug mode and wraps around in release mode.

cc @alexcrichton

**Comment by steveklabnik** [comment] 2017-03-30 13:42
The default behavior for overflow is "panic in debug mode, wrap in release mode." So anything that does that does not need a note. Anything else should get one.

**Comment by stjepang** [comment] 2017-03-30 13:59
In that case, we must add a note for `fetch_add` and `fetch_sub`. They don't panic in debug mode: https://is.gd/AnruSb

**Comment by ollie27** [comment] 2017-03-30 14:44
Dupe of #34618?

**Comment by alexcrichton** [comment] 2017-03-30 16:40
Yeah just adding a note here about overflow should be fine, but yeah looks like a dupe of #34618 so closing

**Closed by alexcrichton** 2017-03-30 16:40 UTC
Labels: T-doc
