### ISSUE TITLE
Drop skipped on panic

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#27906] opened 2015-08-19 18:14 UTC
I was working on a patch for @bluss's arrayvec and ran into the following issue. In the code below, I'm trying to keep the `Test` struct from dropping twice even if it panics on drop. If I explicitly drop the `Test` when reading it out of the array (using `ptr::read`), everything works. However, if I don't explicitly drop it (see XXX), it drops (good), panics (good), but then `guard` isn't dropped (bad) so the `Test` is dropped a second time (bad).

Sorry for the generic title.

```rust
use std::{mem, ptr};

struct Test;
impl Drop for Test {
    fn drop(&mut self) {
        println!("drop");
        panic!();
    }
}

struct Container(Option<[Test; 1]>);

impl Drop for Container {
    fn drop(&mut self) {
        /// Prevents Container's contents from dropping.
        struct Guard<'a>(&'a mut Container);
        impl<'a> Drop for Guard<'a> {
            fn drop(&mut self) {
                unsafe {
                    ptr::write(&mut (self.0).0, None);
                }
            }
        }
        {
            let guard = Guard(self);
            {
                unsafe {
                    let v = ptr::read(&mut (guard.0).0.as_mut().unwrap()[0]);
                    drop(v); // XXX: If removed, guard is never dropped and Test gets dropped twice.
                }
            }
        }
    }
}
fn main() {
    let c = Container(Some([Test]));
}
```

**Comment by bluss** [comment] 2015-08-19 18:41
cc @pnkfelix since it's drop related

**Comment by alexcrichton** [comment] 2015-08-20 00:51
I believe this is a dupe of #14875, so closing in favor of that

**Closed by alexcrichton** 2015-08-20 00:51 UTC

**Comment by Stebalien** [comment] 2015-08-20 03:29
@alexcrichton Looks like it. Thanks.

**Comment by bluss** [comment] 2015-08-20 16:16
@stebalien did you find a bug in arrayvec?

**Comment by Stebalien** [comment] 2015-08-20 16:49
@bluss https://github.com/bluss/arrayvec/issues/3

**Comment by bluss** [comment] 2015-08-20 19:39
FWIW, if feels like a panic safety bug in arrayvec, not really a bug in rust?

**Comment by Stebalien** [comment] 2015-08-20 19:55
The bug in rust is that my PR doesn't work unless the item is dropped explicitly by calling drop on it.
-- 
Steven Allen
