### ISSUE TITLE
rustc and cargo hanging on macOS Sierra Beta 2

### ISSUE THREAD

**Issue by davidzchen** [rust-lang/rust#34718] opened 2016-07-08 04:35 UTC
I just updated my machine to the second beta of macOS Sierra, and now both `cargo` and `rustc` hang when they are run. `cargo` produces no output but `rustc` prints the following:

```
❯❯❯ rustc --version
rustc(86084,0x7fff9a27d3c0) malloc: *** malloc_zone_unregister() failed for 0x7fff9a274548
```

**Comment by sfackler** [comment] 2016-07-08 04:37
Duplicate of #34674

**Closed by sfackler** 2016-07-08 04:37 UTC
