### ISSUE TITLE
Missed Optimization for NonZeroU32 to NonZeroUsize Conversions

### ISSUE THREAD

**Issue by zmtaub** [rust-lang/rust#119422] opened 2023-12-29 21:17 UTC
I tried this code:

```rust
use std::num::*;

pub fn f0(x: u32) -> u64 {
    x.try_into().unwrap()
}

pub fn f1(x: NonZeroU32) -> NonZeroU64 {
    x.try_into().unwrap()
}

pub fn f2(x: u32) -> usize {
    x.try_into().unwrap()
}

pub fn f3(x: NonZeroU32) -> NonZeroUsize {
    x.try_into().unwrap()
}
```

I expected to see this happen:

I expected equivalent assembly generated for each function on 64-bit platforms when compiling with `-C opt-level=3`.
Indeed, if `f3` is removed, this assembly is generated according to Compiler Explorer:

```assembly
example::f0:
        mov     eax, edi
        ret
```

Instead, this happened:

According to Compiler Explorer, this assembly is generated:

```assembly
core::ptr::drop_in_place<core::num::error::TryFromIntError>:
        ret

example::f0:
        mov     eax, edi
        ret

example::f3:
        test    edi, edi
        je      .LBB2_1
        mov     eax, edi
        ret
.LBB2_1:
        push    rax
        lea     rdi, [rip + .L__unnamed_1]
        lea     rcx, [rip + .L__unnamed_2]
        lea     r8, [rip + .L__unnamed_3]
        lea     rdx, [rsp + 7]
        mov     esi, 43
        call    qword ptr [rip + core::result::unwrap_failed@GOTPCREL]
        ud2

.L__unnamed_1:
        .ascii  "called `Result::unwrap()` on an `Err` value"

.L__unnamed_2:
        .quad   core::ptr::drop_in_place<core::num::error::TryFromIntError>
        .asciz  "\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000"
        .quad   <core::num::error::TryFromIntError as core::fmt::Debug>::fmt

.L__unnamed_4:
        .ascii  "/app/example.rs"

.L__unnamed_3:
        .quad   .L__unnamed_4
        .asciz  "\017\000\000\000\000\000\000\000\020\000\000\000\022\000\000"
```

The `try_into().unwrap()` isn't optimized away for `f3`, unlike the other functions.

[Compiler Explorer link](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:2,endLineNumber:17,positionColumn:1,positionLineNumber:15,selectionStartColumn:2,selectionStartLineNumber:17,startColumn:1,startLineNumber:15),source:'use+std::num::*%3B%0A%0Apub+fn+f0(x:+u32)+-%3E+u64+%7B%0A++++x.try_into().unwrap()%0A%7D%0A%0Apub+fn+f1(x:+NonZeroU32)+-%3E+NonZeroU64+%7B%0A++++x.try_into().unwrap()%0A%7D%0A%0Apub+fn+f2(x:+u32)+-%3E+usize+%7B%0A++++x.try_into().unwrap()%0A%7D%0A%0Apub+fn+f3(x:+NonZeroU32)+-%3E+NonZeroUsize+%7B%0A++++x.try_into().unwrap()%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:32.794812616771075,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:r1740,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'-C+opt-level%3D3+--edition+2021+--target%3Dx86_64-unknown-linux-gnu+',overrides:!(),selection:(endColumn:79,endLineNumber:36,positionColumn:79,positionLineNumber:36,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+rustc+1.74.0+(Editor+%231)',t:'0')),k:33.871854049895596,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.74.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+rustc+1.74.0+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4
```

**Comment by AngelicosPhosphoros** [comment] 2023-12-30 18:10
As I understand, the root cause of this is that LLVM doesn't support `!range` metadata on values (including function arguments) and return values.

This `!range` metadata is used when loading values from pointers so if we pass argument by reference, compiler optimizes code correctly: [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:2,endLineNumber:5,positionColumn:1,positionLineNumber:3,selectionStartColumn:2,selectionStartLineNumber:5,startColumn:1,startLineNumber:3),source:'use+std::num::*%3B%0A%0Apub+fn+conv1(a:+%26NonZeroU32)-%3ENonZeroUsize%7B%0A%09NonZeroUsize::try_from(*a).unwrap()%0A%7D%0A'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:r1740,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'-O+--emit%3Dllvm-ir',overrides:!((name:edition,value:'2021')),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+rustc+1.74.0+(Editor+%231)',t:'0')),header:(),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).
However, it probably would not work in practice because LLVM optimizes functions by promoting references to values in argpromotion pass.

The only good thing is that if your values are stored in memory (e.g. in some vector), it would be optimized correctly.

**Comment by AngelicosPhosphoros** [comment] 2023-12-30 18:40
Another example: [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DEArgoKkl9ZATwDKjdAGFUtEywYgATKUcAZPAZMADl3ACNMYhAAVlIAB1QFQjsGFzcPb3jE5IEAoNCWCKjYq0wbFKECJmICNPdPH1LygUrqgjyQ8MiYyyqauozGvvbAzsLu6IBKS1QTYmR2DjNMAGpzdBAQBndNgCoAUgBmACF9jQBBM/O4kzCVqgYVhgEAfQAvSNQX5BY4iCYQCtggIAFqfOSHLyTAC0R2wYVQrhW%2BwA7KcLitMUwAHTATAECCTZGHAAiRxJKw0V1RJI401onGivE8HC0pFQnAASmYCGtZvNVvsvIceKQCJo6dMANYgQ6HbFyxVK5UANn0nEkzIl7M4vAUIA0Yol0zgsCQaF%2BdEi5EoFriVqixC4KMkhpotAIkX1EDC2rCgWqAE9OKL/cxiIGAPJhbRlcXcXgWtiCSMMWjB1m8LBhEzAJxiWj6hOkLAsQzAcSZkt4YhxvAAN0wRbZmFUZRMnpDvECnoZVdoeDCxCDLiwXbFxDwLC70yoBmACgAanhMAB3SNxRjj/iCERidhSGSCRQqdRV3RcfTlkCmcz6Qf6yDTVBxWwCIvQyO8VCN4iTrCPlAzBsCAmD4G%2BDCkPWYgmIsXgaF4PCTNMTQQQ4DDOK49R6P4owFEUegJEkEEDJ4l5ETkDAdPh3SXqhFTDKRej0S0wzUV0UR0YxWEZFxbTseMnEofyCwSPSjJalWHIcCst4EMgKxcNiLrYhoKwQLghAkMiwpcJMvDxloyGkAgmBMFgUSEqQMpygqyr2XKap9pqpAsmy0l6gaRqZiaMCICgqCWvQZAUBAdoOjezqunwdCesQ3q%2BlWYZBuOyURtGsY2OOSaMAQqbptq2a5vmtCFuOpblpWbL4LW5SNs2vCtu2nbFj2mB9myA5DiOGCLKKBCTtOCazvOS4ruum4sqKO7CKI4iHjNJ5qNqug%2BAYRg3jy95hIBz6vikH6Ris0LQpgLCEOSpX1iw0I1t%2Bv7/k28AQMB7BgZRUEwXBCFISh7V1vYECOExl64fkHGEdkJE8WRWTESkAkEXR/3NAwrT9DDzEoxB6MjODgnMdx6Sw%2BY/F4RDekzHMomU32TKudq0myTyClKSpakaeB2lCiK%2BneUZ0qyvKDkOeqHAuW5366pYXmGZKYteJJ7nS3Lxm/kk9iSEAA)

```rust
pub fn non_zero_cmp(a: NonZeroU32)->bool {
   a.get() == 0
}
```

It should generate just `ret i1 0` but it generates test:

```asm
example::non_zero_cmp:
        test    edi, edi
        sete    al
        ret
```

@zmtaub May you rename your issue to "Compiler fails to optimize NonZero integers passed as function parameters".

**Comment by AngelicosPhosphoros** [comment] 2023-12-30 19:00
Made a LLVM issue.
https://github.com/llvm/llvm-project/issues/76628

**Comment by AngelicosPhosphoros** [comment] 2023-12-30 19:56
I started to work on issue.
https://github.com/rust-lang/rust/pull/119452

**Comment by nikic** [comment] 2023-12-30 20:47
Duplicate of https://github.com/rust-lang/rust/issues/49572.

**Closed by nikic** 2023-12-30 20:47 UTC
Labels: A-LLVM, I-slow, T-compiler, C-bug, I-heavy, C-optimization
