### ISSUE TITLE
Error messages wrt. patterns named the same as a type could be better

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#49145] opened 2018-03-18 20:39 UTC
Given:
```rust
struct f; fn main() { let f = 1; }
```

a rust compiler (playground, stable) will error with:
```rust
error[E0308]: mismatched types
 --> src/main.rs:1:27
  |
1 | struct f; fn main() { let f = 1; }
  |                           ^ expected integral variable, found struct `f`
  |
  = note: expected type `{integer}`
             found type `f`
```

this is morally right; but the error message could highlight the fact that the user most likely confused the pattern `f` (as in the equivalent unit struct pattern `f {}`) with a variable binding `f`.

Tho, the names coinciding is somewhat pathological, so it might not warrant special care; but perhaps it does?

**Comment by estebank** [comment] 2018-03-19 06:20
Duplicate of #48062.

**Closed by estebank** 2018-03-19 06:20 UTC
Labels: A-diagnostics, C-feature-request, WG-compiler-errors
