### ISSUE TITLE
ICE compiling cargo-graph v0.3.0 with today's nightly

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#36834] opened 2016-09-29 19:24 UTC
### STR

```
$ cargo clone cargo-graph --vers 0.3.0 && cd $_
$ rustup run nightly cargo build
   Compiling vec_map v0.6.0
   Compiling ansi_term v0.9.0
   Compiling rustc-serialize v0.3.19
   Compiling unicode-width v0.1.3
   Compiling bitflags v0.7.0
   Compiling libc v0.2.16
   Compiling unicode-segmentation v0.1.2
   Compiling strsim v0.5.1
   Compiling term_size v0.2.1
   Compiling clap v2.11.3
   Compiling toml v0.2.1
   Compiling cargo-graph v0.3.0 (file:///home/japaric/tmp/cargo-graph)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:     0x7fc0c579759f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x7fc0c57a6aad - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x7fc0c57a3f6e - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x7fc0c57a4658 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x7fc0c57a44f2 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x7fc0c57a4430 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x7fc0c57a43b1 - rust_begin_unwind
   8:     0x7fc0c57f1c3f - core::panicking::panic_fmt::h9af671b78898cdba
   9:     0x7fc0c57f1b6b - core::panicking::panic::h1a2d1a6b50eaa468
  10:     0x7fc0c4da15e2 - rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor::visit_invoc::h1ffde3beaeda5557
  11:     0x7fc0c4d99f75 - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::ha1f7cee58f82f9da
  12:     0x7fc0c200a2a6 - syntax::ext::expand::MacroExpander::collect_invocations::hac509c4490fb88f2
  13:     0x7fc0c2007f84 - syntax::ext::expand::MacroExpander::expand::h737d7f1635448d5d
  14:     0x7fc0c2006969 - syntax::ext::expand::MacroExpander::expand_crate::hd89d06b7a6333976
  15:     0x7fc0c2011c6d - syntax::ext::expand::expand_crate::h80012253cfa7f1f5
  16:     0x7fc0c5b631ad - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::hc795707fb140075e
  17:     0x7fc0c5b186d1 - rustc_driver::driver::phase_2_configure_and_expand::h04526112c643cb41
  18:     0x7fc0c5b1225b - rustc_driver::driver::compile_input::h5b63ccd49eeeb98b
  19:     0x7fc0c5b3e1f6 - rustc_driver::run_compiler::h5441e14d75f46685
  20:     0x7fc0c5a791b3 - std::panicking::try::do_call::h75a39c92a39808cb
  21:     0x7fc0c57ae9a6 - __rust_maybe_catch_panic
  22:     0x7fc0c5a982b9 - <F as alloc::boxed::FnBox<A>>::call_box::h8cd2c55f49278b86
  23:     0x7fc0c57a29c0 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  24:     0x7fc0bda9b453 - start_thread
  25:     0x7fc0c54737de - __GI___clone
  26:                0x0 - <unknown>

error: Could not compile `cargo-graph`.
```

This crate compiles fine with beta (0.13.0-beta.1) and stable (0.12.0).

### Meta

```
$ rustup run nightly rustc -V
rustc 1.14.0-nightly (86affcdf6 2016-09-28)
```

**Comment by japaric** [comment] 2016-09-29 19:30
Last nightly that worked: nightly-2016-09-27

```
$ rustup run nightly-2016-09-27 rustc -V
rustc 1.13.0-nightly (d0623cf7b 2016-09-26)
```

**Comment by TimNN** [comment] 2016-09-29 20:27
Could be a duplicate of #36816, cc @jseyfried

**Comment by pmarcelll** [comment] 2016-10-01 12:51
I have a fresh build from master, #36819 fixed this as well.

**Comment by alexcrichton** [comment] 2016-10-03 06:47
Yay!

**Closed by alexcrichton** 2016-10-03 06:47 UTC
Labels: I-ICE, regression-from-stable-to-nightly
