### ISSUE TITLE
Implement Default for all array sizes

### ISSUE THREAD

**Issue by shamatar** [rust-lang/rust#88744] opened 2021-09-08 13:47 UTC
I've made a simple [Godbolt](https://godbolt.org/z/bPMd9K6oG) for a demonstration of the approach.

In short, with array::map stabilized in 1.55 it's now possible to make an array `[T; N]` of default values of `T` by invoking `[(); N].map(|_| T::default())`. There is no difference in the emitted assembly for either O2 or O3 optimization levels in my short example for `usize` and user defined type (both ZST and not ZST), but obviously there is no guarantee that some more complex cases would not diverge.

I would expect that lifting a hard limitation of 32 on the size of the array would be handy in general.

**Comment by hellow554** [comment] 2021-09-08 14:41
There's an open issue for this... somewhere, I can't find it.
IIRC when implemented via const generics there was a regression with a zero sized array. Maybe somebody can link it here...

**Comment by shamatar** [comment] 2021-09-08 15:21
I've updated the Godbolt link to include creation of arrays of length 0 for both ZST and not ZST. It doesn't look like there is any difference as `array::map` already has a special case for `N == 0` that is optimized out by the compiler in both cases.

**Comment by paolobarbolini** [comment] 2021-09-08 16:04
> I've updated the Godbolt link to include creation of arrays of length 0 for both ZST and not ZST. It doesn't look like there is any difference as `array::map` already has a special case for `N == 0` that is optimized out by the compiler in both cases.

The issue is that `Default` must also be implemented for zero sized arrays where `T` doesn't implement `Default`.

**Comment by cuviper** [comment] 2021-09-08 18:51
There's some discussion in https://github.com/rust-lang/rust/pull/74060#issuecomment-658609636 and the references from there.

**Comment by shamatar** [comment] 2021-09-08 22:18
Ok, I see the point. It lead me to the question now posted in [zullip](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/Kind-of.20specialization.20for.20traits.20with.20adt-const-generics/near/252541920), may be it would be a nice feature that may go along and parallel with specialization (and potentially much easier to implement)

**Comment by Gankra** [comment] 2022-05-26 15:06
# Summary 

Before we had const-generics we had some macros manually implementing Default for a few different array sizes, and we were too clever and special-cased `[T; 0]` to be unconditionally `Default`. As a result when const-generics were introduced, providing a const-generic impl of Default for arrays would have been a regression because it would introduce a `T: Default` bound to the empty array case. This regression *may* be acceptable but was rejected because:

* It might break things (but seemingly no one actually did a crater run, citing the existence of non-public code)
* Compiler devs believed they could/should "solve" the issue and so it would be needless churn to "break" it just to fix it again later

This all happened about 2 years ago, and there is currently no clear roadmap to resolving the issue either way.

# History

* #74060 introduced const-generic impls for arrays but skipped on Default for the reasons above
* #74254 tried to solve this problem with some combination of specialization, but was rejected because specialization is a bit of a mess no one wants to make part of our public API/guarantees.
* #74326 further tested that approach
* #84838 attempted a more targeted approach with lang items, but the libs team rejected it on the grounds that it was going to be cursed/unmaintainable code.

**Comment by ryoqun** [comment] 2022-12-19 12:26
> There's an open issue for this... somewhere, I can't find it. IIRC when implemented via const generics there was a regression with a zero sized array. Maybe somebody can link it here...

@hellow554 I think https://github.com/rust-lang/rust/issues/61415 is the correct issue.

@Gankra hey, it's nice summary. could you update to include a pointer to the issue.

@shamatar also, now it's directed to the correct issue. this one can be closed, maybe?

**Comment by dtolnay** [comment] 2022-12-26 01:57
Yes, I'll close this in favor of #61415.

**Closed by dtolnay** 2022-12-26 01:57 UTC
Labels: T-libs-api, T-libs
