### ISSUE TITLE
Truncated text in rustdoc warning

### ISSUE THREAD

**Issue by jbr** [rust-lang/rust#70965] opened 2020-04-09 22:33 UTC
I got this error message while updating some docs, formatting retained. Thought I should probably file this somewhere. ~~Let me know if the specific code is important.~~ Thanks!

```
warning: doc comment contains an invalid Rust code block
   --> /…/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.5.0/src/utils.rs:243:42
    |
243 | rait impls that only appear in docs.
    |                                          ^^^^^^^^^^^
    |
    = help: mark blocks that do not contain Rust code as text: ```text

    Finished dev [unoptimized + debuginfo] target(s) in 1.95s
```

Edit: After filing this, I looked at that utils.rs line, and now I'm unsure if this is an async_std issue or a rustdoc issue, since it has something to do with macro expansion

**Comment by estebank** [comment] 2020-04-09 23:56
https://github.com/async-rs/async-std/blob/aebba2bd95c3977a9d54c540e417d793acfb5f97/src/utils.rs#L256-L257

Could you show us how you're using it? I think it might be a span issue exposed by async-std, but it could potentially be an issue on rustdoc's side. Could you make a minified repro case?

**Comment by jbr** [comment] 2020-04-10 00:01
@estabank This error occurs on master of https://github.com/http-rs/tide, but I'm not exactly sure what the source is

**Comment by estebank** [comment] 2020-04-10 00:49
There are two things here: the warning is probably _correct_ in that there's an invalid code block in _some_ doc comment, and `rustc` is losing the right span after going through the proc-macro.

**Comment by awoimbee** [comment] 2020-11-29 16:49
Cannot reproduce or find any issue that looks like this
Close ?

**Comment by jyn514** [comment] 2020-12-15 22:38
Since this is fixed in tide I think it makes sense to close this - if you can get a smaller MCVE feel free to re-open, but I think this is a bug in a proc-macro somewhere.

**Closed by jyn514** 2020-12-15 22:38 UTC
Labels: A-macros, C-bug, D-confusing, T-compiler, T-rustdoc
