### ISSUE TITLE
Compiler hangs when calculating integers inline

### ISSUE THREAD

**Issue by patrickgold** [rust-lang/rust#57347] opened 2019-01-04 22:03 UTC
While writing a simple Fahrenheit to Celsius converter, I came along with this line of code, which apparently let the rustc compiler hang in an infinite loop (`input_value`is an inputted number with type of `isize`):

```rust
println!("{0}°F is {1}°C", input_value, (input_value - 32) * (5/9));
```

First I thought I had an error in my code, so I went through the code again and saw, that I wanted to calculate floating point inputs as well, so I changed all variables to floating point numbers and my issue was fixed.
But I wanted to know why my previously code I wrote didn't compile, so I tried some combinations and came to the following result:

```rust
fn main() {
    // Gets stuck while compiling (exactly the same as above)
    let c = (120 - 32) * (5/9);
    println!("Calculation is {}", c); // should output 0

    // Compiles when using floats
    let c = (120.0 - 32.0) * (5.0/9.0);
    println!("Calculation is {}", c); // 48.88888888

    // Compiles when splitting up into two several variables
    let a = (120 - 32);
    let b = (5/9);
    let c = a * b;
    println!("Calculation is {}", c); // 0

    // Compiles when splitting up into two several variables and using float
    let a = (120.0 - 32.0);
    let b = (5.0/9.0);
    let c = a * b;
    println!("Calculation is {}", c); // 48.88888888
}
```
When compiling the above code, warnings like unnecessary parentheses for `a` and `b` used do appear, but the compiler hangs after outputting these warnings and has a high CPU usage.

I am using:
```sh
rustc 1.31.1 (b6c32da9b 2018-12-18)
binary: rustc
commit-hash: b6c32da9b0481e3e9d737153286b3ff8aa39a22c
commit-date: 2018-12-18
host: armv7-unknown-linux-gnueabihf
release: 1.31.1
LLVM version: 8.0
```

**Comment by nikic** [comment] 2019-01-04 22:31
Assuming you're compiling without optimization this looks like https://bugs.llvm.org/show_bug.cgi?id=39277 to me. There's a corresponding rust bug somewhere, but I can't find it. In any case, this issue should be fixed on beta, can you give it a try?

**Comment by nikic** [comment] 2019-01-04 22:35
Uh, that part about being fixed on beta isn't right, sorry. I thought this was part of the last LLVM update, but the fix is more recent than that.

**Comment by patrickgold** [comment] 2019-01-04 22:50
As you already mentioned, the issue only occurred when compiling without optimization. When I compile for release with the following options, everything is ok and the compiler completes within a second:
`rustc -C debuginfo=0 -C opt-level=3 main.rs`

**Comment by nikic** [comment] 2019-01-27 19:57
LLVM update is in, can you please check whether the issue is resolved on nightly?

**Comment by patrickgold** [comment] 2019-01-28 23:09
Just checked, the above code compiles successfully on the newest nightly channel `rustc 1.34.0-nightly (da6ab956e 2019-01-27)`.

**Comment by nikic** [comment] 2019-01-30 19:59
Thanks for the confirmation!

**Closed by nikic** 2019-01-30 19:59 UTC
Labels: A-LLVM, I-hang, T-compiler
