### ISSUE TITLE
`char::is_ascii_digit()` is slower than `char::is_digit(10)`

### ISSUE THREAD

**Issue by ThomasdenH** [rust-lang/rust#68453] opened 2020-01-22 13:22 UTC
Using the method `is_ascii_digit` on a char is about 17% slower than using `is_digit(10)`. I wouldn't expect there to be a difference, of if there was, I would expect the former to be faster. Could this be improved or are the two not actually equivalent?

**Comment by ThomasdenH** [comment] 2020-01-22 13:24
I just saw #67143, which I think fixes this.

**Comment by blankname** [comment] 2020-01-25 16:48
Might want to re-open this as #67143 has been closed.

**Comment by ThomasdenH** [comment] 2020-01-25 18:12
Alright.

**Comment by LeSeulArtichaut** [comment] 2020-02-19 23:42
This seems like a duplicate of #65127, which has been fixed by #67585

**Closed** 2020-02-26 19:28 UTC
