### ISSUE TITLE
No way to allow an unknown lint on the command line

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#81906] opened 2021-02-09 01:43 UTC
When migrating a large codebase to a new compiler version, frequently there are new lints. In codebases that enable `-Dwarnings`, this causes a problem: we'd like to allow the new lint temporarily before fixing in-tree, but passing `-Anew-lint-here` to the old compiler gives us an error. If we can't upgrade the compiler and build flags in lock step, we are stuck.

[`-Aunknown-lints`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unknown-lints) exists, but does not have the desired effect on the command line:

```
$ rustc -Aunknown-lints -Alegacy-derive-helpers hello.rs
error[E0602]: unknown lint: `legacy_derive_helpers`
  |
  = note: requested on the command line with `-A legacy_derive_helpers`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0602`.
```

Since the same problem that `unknown-lints` solves exists on the command line, I'd argue that this is a bug in the CLI.

As a corollary, it would be nice if we could do something like `-Aunknown-lints -Alegacy-derive-helpers -Dunknown-lints` to prevent misspellings elsewhere in the command line.

**Comment by jyn514** [comment] 2021-02-09 03:55
Duplicate of https://github.com/rust-lang/rust/issues/74722.

**Closed by jyn514** 2021-02-09 03:55 UTC
Labels: A-driver, C-bug, T-compiler
