### ISSUE TITLE
`use super as foo;` does not work.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#30275] opened 2015-12-09 01:12 UTC
Intuitively, it should.

**Comment by huonw** [comment] 2016-01-06 00:07
I think @nrc was looking at imports?

**Comment by dpc** [comment] 2016-01-06 00:27
BTW. Workaround:

```
mod foo {                                                                                                                       
      pub use super::super::*;                                                                                                      
}
```

**Comment by huonw** [comment] 2016-01-06 00:29
Oh, this is a dupe of https://github.com/rust-lang/rust/issues/29036. Thanks for filing!

**Closed by huonw** 2016-01-06 00:29 UTC
Labels: A-resolve, T-lang
