### ISSUE TITLE
`v[v.len()-1]` not accepted by borrow checker

### ISSUE THREAD

**Issue by Danvil** [rust-lang/rust#105678] opened 2022-12-14 01:45 UTC
I tried this code:
```rust
let mut v = vec![1,2,3];
v[v.len()-1] = 5;
```
and expected it to compile, but the borrow checker does not accept it.

This looks like a bug, because the following similar code works thanks to two-phase borrow:
```rust
use std::ops::IndexMut;
let mut v = vec![1,2,3];
*v.index_mut(v.len() - 1) = 5;
```

Another case which works fine:
```rust
let mut v = vec![1,2,3];
v.push(v.len());
```

**Comment by guchengxi1994** [comment] 2022-12-14 05:22
```rust
let mut v = vec![1,2,3];
let v_len = v.len() -1;
v[v_len] = 5;
println!("{:?}",v)
```

this works fine.
![image](https://user-images.githubusercontent.com/33513462/207512775-e99f471b-811c-457f-bea5-57636ed96f2e.png)

**Comment by pnkfelix** [comment] 2022-12-14 15:02
This is a duplicate of #74319.

We deliberately made a (conservative) choice to not apply two-phase borrow in the `v[...] = ...` scenario today:

https://github.com/rust-lang/rust/blob/96859dbaf6229f131fbd427a32aaa95d4f9cb132/compiler/rustc_typeck/src/check/place_op.rs#L376-L380

as documented here:

https://github.com/rust-lang/rust/blob/96859dbaf6229f131fbd427a32aaa95d4f9cb132/compiler/rustc_middle/src/ty/adjustment.rs#L135-L151

Closing as duplicate of #74319 (I'll post some more thoughts there though while this is on my mind).

**Closed by pnkfelix** 2022-12-14 15:02 UTC
Labels: C-bug
