### ISSUE TITLE
Non-specialized impl of ToString missing from docs

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#32841] opened 2016-04-08 21:30 UTC
In the nightly version of the docs, only the newly specialized str implementation is displayed on the page for the trait `ToString`, the general implementation for `T: Display` is not shown. https://doc.rust-lang.org/nightly/std/string/trait.ToString.html

**Comment by pmarcelll** [comment] 2016-04-09 14:33
Duplicate of #29503

**Closed** 2016-04-09 17:21 UTC
