### ISSUE TITLE
Broken MIR - call dest mismatch (warning appeared after updating to 1.8 stable)

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#32983] opened 2016-04-15 04:04 UTC
When compiling the conrod examples after updating to 1.8 stable, the following `Broken MIR` warning has been appearing:

```
examples/all_widgets.rs:145:39: 145:44 warning: broken MIR (var1 = conrod::ui::Ui<B>::new(tmp23, tmp25) -> [return: bb46, unwind: bb45]): call dest mismatch (conrod::ui::Ui<(gfx_texture::Texture<gfx_device_gl::Resources>, gfx_graphics::glyph::GlyphCache<gfx_device_gl::Resources, gfx_device_gl::factory::Factory>)> <- conrod::ui::Ui<(<gfx_graphics::back_end::GfxGraphics<'static, gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer> as graphics::graphics::Graphics>::Texture, gfx_graphics::glyph::GlyphCache<gfx_device_gl::Resources, gfx_device_gl::factory::Factory>)>): Sorts(ExpectedFound { expected: gfx_texture::Texture<gfx_device_gl::Resources>, found: <gfx_graphics::back_end::GfxGraphics<'static, gfx_device_gl::Resources, gfx_device_gl::command::CommandBuffer> as graphics::graphics::Graphics>::Texture })
examples/all_widgets.rs:145         Ui::new(glyph_cache.unwrap(), theme)
```

[Here is the code](https://github.com/PistonDevelopers/conrod/blob/master/examples/all_widgets.rs#L145) from the conrod example that causes the warning.

The same warning also appears in each of the other conrod examples at the same line (i.e. [here](https://github.com/PistonDevelopers/conrod/blob/master/examples/image.rs#L32) and [here](https://github.com/PistonDevelopers/conrod/blob/master/examples/canvas.rs#L35) and so on for the other examples).

I found #32959 which also gives a broken MIR warning, however the warning seems to be slightly different so I thought I'd post a new issue.

**Comment by Aatch** [comment] 2016-04-15 06:47
Looks like the associated type isn't getting normalized. Given that it "expects" an associated type.

**Comment by nagisa** [comment] 2016-04-15 17:14
Smaller example: 

```rust
trait A {
    type B;
}

struct C;

impl A for C {
    type B = u32;
}

struct D<B>(::std::marker::PhantomData<B>);

impl<B> D<B> {
    fn new() -> D<B> {
        D(::std::marker::PhantomData)
    }
}

type U = D<<C as A>::B>;

fn main() {
    let x = U::new();
}
```

**Comment by nagisa** [comment] 2016-04-15 20:36
This is a duplicate of https://github.com/rust-lang/rust/issues/28828. Thanks for the report.

**Closed by nagisa** 2016-04-15 20:36 UTC
Labels: A-mir
