### ISSUE TITLE
Compilation issues with debug and LTO enabled

### ISSUE THREAD

**Issue by iopq** [rust-lang/rust#29685] opened 2015-11-08 04:03 UTC
I get `Assertion failed: Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation.", file C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\llvm\lib\CodeGen\AsmPrinter\DwarfUnit.cpp, line 713` when trying to compile with debug and LTO at the same time

I am running Windows 8, using the MSVC 64 bit edition, 1.6 nightly

the project is https://github.com/ujh/iomrascalai if you want to reproduce the issue

**Comment by nagisa** [comment] 2015-11-08 13:18
Duplicate of https://github.com/rust-lang/rust/issues/25270

**Closed** 2015-11-08 16:02 UTC
