### ISSUE TITLE
Weird diagnostic for recursion in const fn

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust#126408] opened 2024-06-13 13:17 UTC
### Code

```Rust
const fn f() {
    const { f() };
}
```

### Current output

```Shell
error[E0391]: cycle detected when elaborating drops for `f`
 --> src/lib.rs:2:5
  |
2 |     const { f() };
  |     ^^^^^^^^^^^^^
  |
note: ...which requires simplifying constant for the type system `f::{constant#0}`...
 --> src/lib.rs:2:11
  |
2 |     const { f() };
  |           ^^^^^^^
note: ...which requires const-evaluating + checking `f::{constant#0}`...
 --> src/lib.rs:2:11
  |
2 |     const { f() };
  |           ^^^^^^^
note: ...which requires caching mir of `f` for CTFE...
 --> src/lib.rs:1:1
  |
1 | const fn f() {
  | ^^^^^^^^^^^^
  = note: ...which again requires elaborating drops for `f`, completing the cycle
  = note: cycle used when running analysis passes on this crate
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

For more information about this error, try `rustc --explain E0391`.
```

### Rationale and extra context

const blocks are stable, the user shouldn't care about any of the information in the error.

### Rust Version

```Shell
❯ rustc --version --verbose
rustc 1.81.0-nightly (8337ba918 2024-06-12)
binary: rustc
commit-hash: 8337ba9189de188e2ed417018af2bf17a57d51ac
commit-date: 2024-06-12
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Anything else?

I couldn't try on 1.79.0

**Comment by theemathas** [comment] 2024-06-13 13:31
Duplicate of #125713

**Closed** 2024-06-13 13:41 UTC
Labels: A-diagnostics, T-compiler
