### ISSUE TITLE
thread '<unnamed>' panicked at 'attempting to document proc-macro re-export', librustdoc/clean/inline.rs:474:39

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#52216] opened 2018-07-10 16:57 UTC
```
thread '<unnamed>' panicked at 'attempting to document proc-macro re-export', librustdoc/clean/inline.rs:474:39), http                             
stack backtrace:========================================>            ] 211/264: syn(doc), synstructure(doc)                                        
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: rustdoc::clean::inline::try_inline
   7: rustdoc::clean::inline::build_module::fill_in
   8: <rustdoc::doctree::Import as rustdoc::clean::Clean<alloc::vec::Vec<rustdoc::clean::Item>>>::clean
   9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
  10: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
  12: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::spec_extend
  14: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::Item>>::clean
  15: <rustdoc::visit_ast::RustdocVisitor<'a, 'tcx, 'rcx> as rustdoc::clean::Clean<rustdoc::clean::Crate>>::clean
  16: rustdoc::core::run_core::{{closure}}::{{closure}}
  17: rustc::ty::context::tls::enter_context
  18: <std::thread::local::LocalKey<T>>::with
  19: rustc::ty::context::TyCtxt::create_and_enter
  20: rustc_driver::driver::phase_3_run_analysis_passes
  21: <scoped_tls::ScopedKey<T>>::set
  22: rustdoc::core::run_core
  23: <scoped_tls::ScopedKey<T>>::set
  24: syntax::with_globals
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: rustc_driver::monitor
  29: rustdoc::rust_input
  30: rustdoc::main_args
  31: <scoped_tls::ScopedKey<T>>::set
  32: syntax::with_globals
  33: std::panicking::try::do_call
  34: __rust_maybe_catch_panic
  35: <F as alloc::boxed::FnBox<A>>::call_box
  36: std::sys::unix::thread::Thread::new::thread_start
  37: _pthread_body
  38: _pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (9bd8458c9 2018-07-09) running on x86_64-apple-darwin

error: Could not document `synstructure`.
```

**Comment by SimonSapin** [comment] 2018-07-11 11:32
This looks like a duplicate of https://github.com/rust-lang/rust/issues/52129, please reopen or comment if it’s not.

**Closed by SimonSapin** 2018-07-11 11:32 UTC
