### ISSUE TITLE
Compiler drops fn symbols from rlib when not inlined.

### ISSUE THREAD

**Issue by danakj** [rust-lang/rust#94138] opened 2022-02-18 23:45 UTC
### Repro
I tried this code, which I have saved as `repro.rs`:

```rust
#[inline(never)]
fn test_fn() {
}
 
extern "C" fn run_test_fn() {
    // Unfortunately, _ZN5repro7test_fn17hf3114ef58d23fd06E is undefined in the .rlib and
    // linker errors result.
    test_fn();
}
 
#[used]
#[link_section = ".init_array"]
static S_TEST_FN: unsafe extern "C" fn() = run_test_fn;
```

I run this:

```
../../third_party/android_rust_toolchain/toolchain/bin/rustc repro.rs \
  --crate-type rlib --edition=2018 -Copt-level=3 -o repro.rlib

objdump -t repro.rlib |grep test_fn|grep UND
```
### Result

I expected to see this happen:

Normally all the symbols for the functions are present in the rlib's object files. So the grep is empty. However..

Instead, this happened:

With this carefully crafted repro case, the test_fn() (symbol: _ZN15values_unittest7test_fn17h9cefd472d6bb8276E) gets dropped from the rlib's objects and shows as `*UND*` in `objdump`:
```
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro7test_fn17hf3114ef58d23fd06E
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro7test_fn17hf3114ef58d23fd06E
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro7test_fn17hf3114ef58d23fd06E
```

Then if you try to link this rlib into a binary you get a linking error for missing symbols.

If you modify the command line to not use `-Copt-level=3` you get fewer symbols but it remains undefined. Command lines:
```
../../third_party/android_rust_toolchain/toolchain/bin/rustc repro.rs \
  --crate-type rlib --edition=2018 -o repro.rlib

objdump -t repro.rlib |grep test_fn|grep UND
```
Result:
```
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro11run_test_fn28_$u7b$$u7b$closure$u7d$$u7d$17h3de3c5199c06a2ddE
```
### Notes
- It also repros with 2021 edition.
- I'm using the toolchain here: https://android.googlesource.com/platform/prebuilts/rust.git

I believe this is different from https://github.com/rust-lang/rust/issues/47384 as the missing symbol is not the static initializer, it's a function calling a non-inlined function. And this is all happening in the crate root.

### Meta
`rustc --version --verbose`:
```
rustc 1.58.1-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.58.1-dev
LLVM version: 13.0.0
```

**Comment by danakj** [comment] 2022-02-18 23:51
Originally I thought that `catch_unwind()` was involved, but that was just there to get `test_fn()` to be not called inline. I've updated the repro and title as such.

**Comment by danakj** [comment] 2022-02-18 23:53
I can also reproduce with upstream stable compiler:
```
% rustc repro.rs --crate-type rlib --edition=2018 -Copt-level=3 -o repro.rlib
% objdump -t repro.rlib |grep test_fn|grep UND
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro7test_fn17hf3114ef58d23fd06E
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro7test_fn17hf3114ef58d23fd06E
0000000000000000         *UND*	0000000000000000 .hidden _ZN5repro7test_fn17hf3114ef58d23fd06E
```
% rustc --version
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by nagisa** [comment] 2022-02-19 16:32
Most likely a duplicate of https://github.com/rust-lang/rust/issues/47384. 

> Then if you try to link this rlib into a binary you get a linking error for missing symbols.

More generally, Rust provides no guarantees about the `rlib`'s other than that they are suitable as an argument to the `rustc`'s `--extern`, and even then `rustc` which produced the `rlib` must be the same as the `rustc` that receives the `rlib` as an argument.

**Closed by nagisa** 2022-02-19 16:32 UTC
Labels: C-bug

**Comment by danakj** [comment] 2022-02-22 18:14
Thanks @nagisa for looking. It's well-known that linking rlibs isn't supported, but also that it's widely done at the moment: https://github.com/rust-lang/rust/issues/73632

I tried linking with rustc to verify and indeed the rlib has `UND` symbols but rustc links it without errors. So I went back to the drawing board to re-minimize my test-case and verify what's going on.

Here's my improved minimized repro:

```
#[inline(never)]
//#[no_mangle]
fn test_fn() {
    println!("test_fn");
}

//#[no_mangle]
extern "C" fn run_test_fn() {
    let _ = std::panic::catch_unwind(|| test_fn());
}

#[used]
#[link_section = ".init_array"]
static S_TEST_FN: unsafe extern "C" fn() = run_test_fn;
```

- Adding the `#[no_mangle]` on either function changes the rlib output such that the C++ linker no longer has missing symbols.
- Using the `catch_unwind()` _is_ important, a direct call to fest_fn() does not produce an actual linking error.

I link the `repro` crate in 3 different ways to demonstrate the behaviour:
```
../../third_party/android_rust_toolchain/toolchain/bin/rustc \
  repro.rs  -o librepro.rlib \
   --edition=2018 -Copt-level=3 \
  --crate-type rlib

../../third_party/android_rust_toolchain/toolchain/bin/rustc \
  repro.rs -o librepro.a \
  --edition=2018 -Copt-level=3 \
  --crate-type staticlib

../../third_party/android_rust_toolchain/toolchain/bin/rustc \
  repro.rs -o librepro.o \
  --edition=2018 -Copt-level=3 \
  --crate-type rlib  --emit obj
```
I use this rustc because I am linking the matching stdlib in with the C++ linker. As long as they match it should be fine. The repro crate is linked into C++ as:
```
../../third_party/llvm-build/Release+Asserts/bin/clang++ -fuse-ld=lld obj/build/rust/std/libstd.rlib \
  obj/build/rust/std/libaddr2line.rlib obj/build/rust/std/libadler.rlib obj/build/rust/std/liballoc.rlib \
  obj/build/rust/std/libcfg_if.rlib obj/build/rust/std/libcompiler_builtins.rlib \
  obj/build/rust/std/libcore.rlib obj/build/rust/std/libgetopts.rlib obj/build/rust/std/libgimli.rlib \
  obj/build/rust/std/libhashbrown.rlib obj/build/rust/std/liblibc.rlib obj/build/rust/std/libmemchr.rlib \
  obj/build/rust/std/libminiz_oxide.rlib obj/build/rust/std/libobject.rlib obj/build/rust/std/libpanic_abort.rlib \
  obj/build/rust/std/libpanic_unwind.rlib obj/build/rust/std/libproc_macro.rlib \
  obj/build/rust/std/librustc_demangle.rlib obj/build/rust/std/libstd_detect.rlib obj/build/rust/std/libtest.rlib \
  obj/build/rust/std/libunicode_width.rlib obj/build/rust/std/libunwind.rlib \
  -o ./main \
  -Wl,--start-group ./main.o obj/build/rust/std/remap_alloc/remap_alloc.o ${L} ./libmalloc_wrapper.so -Wl,--end-group \
  -ldl -lpthread -lrt -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -luuid
```

The main.o is generated with `../../third_party/llvm-build/Release+Asserts/bin/clang++ -c -o main.o main.cc` from main.cc:
```
int main() { return 0; }
```
Where the `${L}` changes which of the 3 rustc outputs we will use.

## Linking rlib
Linking against the rlib, with `${L}` set as:
```
export L="-Wl,--whole-archive ./librepro.rlib -Wl,--no-whole-archive"
```
produces the linking error I was seeing. Unless `#[no_mangle]` is used.
```
ld.lld: error: undefined hidden symbol: repro::test_fn::hf3114ef58d23fd06
>>> referenced by repro.3ccee6e3-cgu.0
>>>               librepro.repro.3ccee6e3-cgu.0.rcgu.o:(std::panic::catch_unwind::h66da5f62f7f85fc0) in archive ./librepro.rlib
>>> referenced by repro.3ccee6e3-cgu.1
>>>               librepro.repro.3ccee6e3-cgu.1.rcgu.o:(repro::run_test_fn::h77e7bc708aa27dd7) in archive ./librepro.rlib
>>> referenced by repro.3ccee6e3-cgu.3
>>>               librepro.repro.3ccee6e3-cgu.3.rcgu.o:(std::panicking::try::h06b8747ec7a353e1) in archive ./librepro.rlib
```

## Linking obj
Linking against the object file, with `${L}` set as below works fine.
```
export L="./librepro.o"
```

## Linking staticlib
Linking against the staticlib works as well, though is not a reasonable solution since we need the output to contain the repro crate only (https://github.com/rust-lang/rust/issues/73632).
```
export L="./librepro.a"
```

So my conclusion is the same as yours. This is symbols considered unreachable not being included as per https://github.com/rust-lang/rust/issues/47384. I presume the `#[no_mangle]` is changing their visibility in such a way as they get included. Using a `pub` also resolves the symbols in this reproduction, though doesn't if you introduce multiple crates. I will avoid building that further test case as I believe it is indeed a dupe.

This is also a problem of https://github.com/rust-lang/rust/issues/73632 where rlibs are the way you link intermediate rustc output currently, and this is an occurrence of that breaking.
