### ISSUE TITLE
LLVM error when building standard library on m68k-unknown-linux-gnu

### ISSUE THREAD

**Issue by xfxpositions** [rust-lang/rust#107597] opened 2023-02-02 15:18 UTC
I tried this code:

`cargo build -Zbuild-std --target m68k-unknown-linux-gnu`
```rust
println!("hello world from m68k");
```

I expected to see this happen: just building on m68k

Instead, this happened: i don't know what is this, i guess it's a llvm bug
LLVM ERROR: unable to allocate function return #2
error: could not compile `rustc-demangle`
error: could not compile `adler`

```
   Compiling core v0.0.0 (/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x3320e73)[0x7f1869e69e73]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f18667a2520]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm12SelectionDAG7getNodeEjRKNS_5SDLocENS_3EVTENS_7SDValueENS_11SDNodeFlagsE+0x4a)[0x7f1864f33b4a]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(+0x54f6e51)[0x7f1864ef6e51]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZNK4llvm14TargetLowering11LowerCallToERNS0_16CallLoweringInfoE+0xe6d)[0x7f1864e756ed]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm19SelectionDAGBuilder14lowerInvokableERNS_14TargetLowering16CallLoweringInfoEPKNS_10BasicBlockE+0x43)[0x7f1865207f03]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm19SelectionDAGBuilder11LowerCallToERKNS_8CallBaseENS_7SDValueEbbPKNS_10BasicBlockE+0xa20)[0x7f1865207560]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm19SelectionDAGBuilder9visitCallERKNS_8CallInstE+0x42f)[0x7f1865399a49]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0xecd)[0x7f18653962e5]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x410)[0x7f18653e7b10]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0xb0e)[0x7f18650ad6ce]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x2f)[0x7f18650acb85]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x210)[0x7f18650b1496]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x2821b92)[0x7f186936ab92]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x28215aa)[0x7f186936a5aa]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x281f77a)[0x7f186936877a]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282d70d)[0x7f186937670d]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282c6af)[0x7f18693756af]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282b763)[0x7f1869374763]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x275e0e6)[0x7f18692a70e6]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-6e3768d17ed5c91f.so(rust_metadata_std_d06b580815fa2207+0x10e793)[0x7f1866abc793]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7f18667f4b43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7f1866886a00]
   Compiling compiler_builtins v0.1.85
   Compiling libc v0.2.138
   Compiling alloc v0.0.0 (/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling cfg-if v1.0.0
   Compiling adler v1.0.2
   Compiling memchr v2.5.0
   Compiling rustc-demangle v0.1.21
LLVM ERROR: unable to allocate function return #2
error: could not compile `compiler_builtins`
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: unable to allocate function return #2
error: could not compile `libc`
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x3320e73)[0x7fb0454c1e73]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fb041dfa520]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(+0x5abf126)[0x7fb040abf126]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv+0x18e2)[0x7fb0405aa0ee]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0x1309)[0x7fb040996721]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x410)[0x7fb0409e7b10]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0xb0e)[0x7fb0406ad6ce]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x2f)[0x7fb0406acb85]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x210)[0x7fb0406b1496]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x2821b92)[0x7fb0449c2b92]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x28215aa)[0x7fb0449c25aa]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x281f77a)[0x7fb0449c077a]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282d70d)[0x7fb0449ce70d]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282c6af)[0x7fb0449cd6af]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282b763)[0x7fb0449cc763]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x275e0e6)[0x7fb0448ff0e6]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-6e3768d17ed5c91f.so(rust_metadata_std_d06b580815fa2207+0x10e793)[0x7fb042114793]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7fb041e4cb43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7fb041edea00]
LLVM ERROR: unable to allocate function return #2
error: could not compile `rustc-demangle`
error: could not compile `adler`

Caused by:
  process didn't exit successfully: `rustc --crate-name adler /home/josef/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="compiler_builtins"' --cfg 'feature="core"' --cfg 'feature="rustc-dep-of-std"' -C metadata=fe472d8e00ff1e5e -C extra-filename=-fe472d8e00ff1e5e --out-dir /home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps --target m68k-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps -L dependency=/home/josef/Belgeler/rust/m68k-test/target/debug/deps --extern compiler_builtins=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps/libcompiler_builtins-c500954323fd3d82.rmeta --extern core=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps/librustc_std_workspace_core-d40d5cf45004f620.rmeta --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2021 /home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=780dc78e03ef251a -C extra-filename=-780dc78e03ef251a --out-dir /home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps --target m68k-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps -L dependency=/home/josef/Belgeler/rust/m68k-test/target/debug/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
```

### Meta

```
`rustc 1.69.0-nightly (11d96b593 2023-02-01)
binary: rustc
commit-hash: 11d96b59307b1702fffe871bfc2d0145d070881e
commit-date: 2023-02-01
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7`:
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling core v0.0.0 (/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x3320e73)[0x7f58c4e9ae73]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f58c17d3520]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm12SelectionDAG7getNodeEjRKNS_5SDLocENS_3EVTENS_7SDValueENS_11SDNodeFlagsE+0x4a)[0x7f58bff33b4a]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(+0x54f6e51)[0x7f58bfef6e51]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZNK4llvm14TargetLowering11LowerCallToERNS0_16CallLoweringInfoE+0xe6d)[0x7f58bfe756ed]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm19SelectionDAGBuilder14lowerInvokableERNS_14TargetLowering16CallLoweringInfoEPKNS_10BasicBlockE+0x43)[0x7f58c0207f03]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm19SelectionDAGBuilder11LowerCallToERKNS_8CallBaseENS_7SDValueEbbPKNS_10BasicBlockE+0xa20)[0x7f58c0207560]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm19SelectionDAGBuilder9visitCallERKNS_8CallInstE+0x42f)[0x7f58c0399a49]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0xecd)[0x7f58c03962e5]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x410)[0x7f58c03e7b10]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0xb0e)[0x7f58c00ad6ce]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x2f)[0x7f58c00acb85]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x210)[0x7f58c00b1496]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x2821b92)[0x7f58c439bb92]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x28215aa)[0x7f58c439b5aa]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x281f77a)[0x7f58c439977a]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282d70d)[0x7f58c43a770d]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282c6af)[0x7f58c43a66af]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282b763)[0x7f58c43a5763]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x275e0e6)[0x7f58c42d80e6]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-6e3768d17ed5c91f.so(rust_metadata_std_d06b580815fa2207+0x10e793)[0x7f58c1aed793]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7f58c1825b43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7f58c18b7a00]
   Compiling compiler_builtins v0.1.85
   Compiling libc v0.2.138
   Compiling alloc v0.0.0 (/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling cfg-if v1.0.0
   Compiling memchr v2.5.0
   Compiling adler v1.0.2
   Compiling rustc-demangle v0.1.21
LLVM ERROR: unable to allocate function return #2
error: could not compile `compiler_builtins`
warning: build failed, waiting for other jobs to finish...
LLVM ERROR: unable to allocate function return #2
error: could not compile `libc`
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x3320e73)[0x7fb5eaa34e73]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fb5e736d520]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(+0x5abf126)[0x7fb5e60bf126]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel17CodeGenAndEmitDAGEv+0x18e2)[0x7fb5e5baa0ee]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE+0x1309)[0x7fb5e5f96721]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE+0x410)[0x7fb5e5fe7b10]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0xb0e)[0x7fb5e5cad6ce]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x2f)[0x7fb5e5cacb85]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.69.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x210)[0x7fb5e5cb1496]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x2821b92)[0x7fb5e9f35b92]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x28215aa)[0x7fb5e9f355aa]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x281f77a)[0x7fb5e9f3377a]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282d70d)[0x7fb5e9f4170d]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282c6af)[0x7fb5e9f406af]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x282b763)[0x7fb5e9f3f763]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-6c163cbf4223029c.so(+0x275e0e6)[0x7fb5e9e720e6]
/home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-6e3768d17ed5c91f.so(rust_metadata_std_d06b580815fa2207+0x10e793)[0x7fb5e7687793]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7fb5e73bfb43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7fb5e7451a00]
LLVM ERROR: unable to allocate function return #2
error: could not compile `rustc-demangle`
error: could not compile `adler`

Caused by:
  process didn't exit successfully: `rustc --crate-name adler /home/josef/.cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="compiler_builtins"' --cfg 'feature="core"' --cfg 'feature="rustc-dep-of-std"' -C metadata=fe472d8e00ff1e5e -C extra-filename=-fe472d8e00ff1e5e --out-dir /home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps --target m68k-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps -L dependency=/home/josef/Belgeler/rust/m68k-test/target/debug/deps --extern compiler_builtins=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps/libcompiler_builtins-c500954323fd3d82.rmeta --extern core=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps/librustc_std_workspace_core-d40d5cf45004f620.rmeta --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
error: could not compile `core`

Caused by:
  process didn't exit successfully: `rustc --crate-name core --edition=2021 /home/josef/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=780dc78e03ef251a -C extra-filename=-780dc78e03ef251a --out-dir /home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps --target m68k-unknown-linux-gnu -Z force-unstable-if-unmarked -L dependency=/home/josef/Belgeler/rust/m68k-test/target/m68k-unknown-linux-gnu/debug/deps -L dependency=/home/josef/Belgeler/rust/m68k-test/target/debug/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
<backtrace>
```

</p>
</details>

**Comment by nikic** [comment] 2023-02-16 11:37
Duplicate of #89498.

**Closed by nikic** 2023-02-16 11:37 UTC
Labels: I-crash, A-LLVM, C-bug, O-motorola68k
