### ISSUE TITLE
Type inference requires type of LHS to be known for binary operators

### ISSUE THREAD

**Issue by mihneadb** [rust-lang/rust#8280] opened 2013-08-04 05:53 UTC
This is the code:

``` rust
use std::hashmap;

fn main() {
    let mut map = hashmap::HashMap::new();

    let str = "Hello, world!";

    for &char in str.to_ascii().iter() {
        let count = map.find(&char);
        match count {
            Some(&x) => map.insert(char, x + 1),
            None => map.insert(char, 1)
        }
    }

    println!("{:?}", map);
}
```

Error message:

```
count_chars.rs:11:41: 11:42 error: the type of this value must be known in this context
count_chars.rs:11             Some(&x) => map.insert(char, x + 1),
                                                       ^
error: aborting due to previous error
```

**Comment by Aatch** [comment] 2015-01-20 12:15
Multidispatch should have fixed this, correct?

**Comment by nikomatsakis** [comment] 2015-01-20 16:06
@Aatch It did not. The distinction has to do with needing to decide between "builtin" operators like `+` on integers and trait-driven operations. Currently we do this at the moment of type-checking the `+` (or other operator). It'll take some rearchitecting but we could defer this decision.

**Comment by arielb1** [comment] 2015-06-21 20:30
This does compile (rather, type-check - of course it won't borrow-check) at 1.0 and above.

**Comment by wthrowe** [comment] 2015-06-21 21:13
The following does not work, however:
```rust
fn main() {
    0u8.into() == 0u8;
}
```
It gives: "error: unable to infer enough type information about `_`; type annotations or generic parameter binding required" (on the `into()`)

I'd been assuming that was this issue since it works if you switch the order of the operands, but if this one is solved perhaps it is a new one?

**Comment by steveklabnik** [comment] 2017-01-03 20:49
Triage: @arielb1 said that this compiles, but it at least needs some massaging due to changes. I tried to do some of them, but it wasn't totally clear to me what should be done, exactly.

It's not clear to me if @wthrowe 's example is the same thing or different.

**Comment by bstrie** [comment] 2017-12-02 23:41
My own attempt to concoct a modern reproduction no longer exhibits this bug:
```rust
    let mut v = Vec::new();
    
    match v.get(0) {
        Some(&x) => v.push(x + 1),  // A-OK
        None => v.push(1),
    }
```
In fact, our inference is so good these days that even this works:
```rust
    let mut v = Vec::new();
    
    match v.get(0) {
        Some(&x) => v.push(x + x),
        None => v.push(1),
    }
```
Given that this bug was filed so long before 1.0 that the test case no longer works and that nobody seems to have come up with a reproduction of the original behavior, I'm closing this.

**Closed by bstrie** 2017-12-02 23:41 UTC
Labels: A-inference, C-enhancement

**Comment by arielb1** [comment] 2017-12-03 00:11
So autoref for operators will make this stop working for the normal reasons. I suppose that would be a regression, but that's life..
