### ISSUE TITLE
Source file names are included into a release binary even if abort upon panic is enabled

### ISSUE THREAD

**Issue by dmitry-zakablukov** [rust-lang/rust#75263] opened 2020-08-07 17:33 UTC
Good day!

I have found, that if a library contains code that may panic (slices, unwraps, etc.), then a filename of such source file will be included in a binary. Release build doesn't change this behavior, neither debug symbols stripping do.

I have tried to turn on "abort" for panic in release profile. Even though this resulted in a smaller binary size, it doesn't wipe out source file names from the binary.

Here is a small reproducible code.

```
// "engine" library, file lib.rs

pub fn print_message() {
    let mut input = String::new();
    std::io::stdin().read_line(&mut input).unwrap();
}
``` 

```
// "main" program, file main.rs

fn main() {
    engine::print_message();
}
```

```
// main Cargo.toml

[package]
name = "symbols_test"
version = "0.1.0"
authors = ["Name Soname <test@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort"

[dependencies]
engine = { path = "../engine" }
```

If I build this example with a command `cargo build --release` on Windows, then a `symbols_test.exe` will contain a string `engine\src\lib.rs`.

==============================

So what should I do, if I want to distribute my program to the clients and do not want them to find out file names of my source files (which are a business secret)? How to strip source file names from the binary?

UPD: How to reproduce the problem on Windows:
```
git clone https://github.com/dmitry-zakablukov/rust-lang-issue-75263.git
cd rust-lang-issue-75263\symbols_test
cargo build --release
strings target\release\symbols_test.exe | grep "engine\src"
```
On *nix systems change slashes to '/' and remove '.exe' in the last command.

**Comment by rshackleford267** [comment] 2020-09-16 19:11
dont use rust. see #40552 privacy isnt a thing they want to think or fix. paths should be less issue than the username in your binary

**Comment by jyn514** [comment] 2020-09-16 20:30
`panic=abort` will still run the panic hook I'm pretty sure, which will print out the line where the panic occurred. So it's not _needlessly_ being added. Maybe there's some option to set a different panic hook?

**Comment by Dylan-DPC** [comment] 2020-09-16 23:57
Marking this for prioritisation request as some people have privacy concerns over file names showing up in their production apps

**Comment by sfackler** [comment] 2020-09-17 00:15
Why is `--remap-path-prefix` not sufficient to deal with privacy concerns?

**Comment by Monadic-Cat** [comment] 2020-09-17 00:36
I've never heard of `--remap-path-prefix` until today. Testing it out, it doesn't do enough.

I went ahead and threw this into a project's `.cargo/config`:
```toml
[build]
rustflags = ["--remap-path-prefix=/home/jmn/Projects/mprojects/mbot=src", "--remap-path-prefix=/home/jmn/.cargo=cargo", "--remap-path-prefix=/home/jmn/.rustup=rustup"]
```

It did get rid of mentions of `/home/jmn/Projects/mprojects/mbot`, but I'm still seeing `/home/jmn/.rustup/toolchains/...` stuff in `strings` output, even after stripping the binary.

**Comment by apiraino** [comment] 2020-09-17 10:08
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2375263.20Source.20file.20names.20are.20included.20into.20a.20r.E2.80.A6) and removing `I-prioritize`.

**Comment by unpavedmop** [comment] 2021-02-12 15:28
anyone from compiler team going to comment on this or just ignore it? workarounds dont actually work

**Comment by ssokolow** [comment] 2021-02-12 17:01
@unpavedmop This is a piece of team infrastructure that's open to the public, not a discussion forum. The "comment" was "Marking this for prioritisation request as some people have privacy concerns over file names showing up in their production apps" and receiving a [P-medium](https://github.com/rust-lang/rust/labels/P-medium) tag.

If you disagree, check out [P-high](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AP-high+) to see what kinds of bugs they consider more pressing concerns.

**Comment by jyn514** [comment] 2021-02-12 17:08
> It did get rid of mentions of /home/jmn/Projects/mprojects/mbot, but I'm still seeing /home/jmn/.rustup/toolchains/... stuff in strings output, even after stripping the binary.

This sounds like the compiler version is being embedded in the binary 

> I've never heard of `--remap-path-prefix` until today. Testing it out, it doesn't do enough.
> 
> I went ahead and threw this into a project's `.cargo/config`:
> 
> ```toml
> [build]
> rustflags = ["--remap-path-prefix=/home/jmn/Projects/mprojects/mbot=src", "--remap-path-prefix=/home/jmn/.cargo=cargo", "--remap-path-prefix=/home/jmn/.rustup=rustup"]
> ```
> 
> It did get rid of mentions of `/home/jmn/Projects/mprojects/mbot`, but I'm still seeing `/home/jmn/.rustup/toolchains/...` stuff in `strings` output, even after stripping the binary.

I can't reproduce this.

```
$ cargo new hello-world
$ cd hello-world
$ echo '[profile.release]
panic = "abort"' >> Cargo.toml
$ RUSTFLAGS="--remap-path-prefix=/home/joshua/test-rustdoc/hello-world=src --remap-path-prefix=/home/joshua/.local/lib/cargo=cargo --remap-path-prefix=/home/joshua/.local/lib/rustup=rustup" cargo run --release
$ strings /home/joshua/.local/lib/cargo/target/release/hello-world | grep home
home_dir
_ZN3std3sys4unix2os8home_dir17h5d3b091b9e7ed062E
home_dir
_ZN3std3sys4unix2os8home_dir8fallback17hb3ac94fa9a85ddbaE
_ZN3std3sys4unix2os8home_dir28_$u7b$$u7b$closure$u7d$$u7d$17ha072306bde63d38dE
_ZN3std3env8home_dir17h055eda4c1c3735acE

**Comment by jyn514** [comment] 2021-02-12 17:13
I tried using a library like in the original reproduction instructions, and if I modify `remap-path-prefix` slightly it still works fine:

```
> RUSTFLAGS="--remap-path-prefix=/home/joshua/src/rust/test-rustdoc=src --remap-path-prefix=/home/joshua/.local/lib/cargo=cargo --remap-path-prefix=/home/joshua/.local/lib/rustup=rustup" cargo run --release
   Compiling engine v0.1.0 (/home/joshua/src/rust/test-rustdoc/engine)
   Compiling hello-world v0.1.0 (/home/joshua/src/rust/test-rustdoc/hello-world)
    Finished release [optimized] target(s) in 0.52s
     Running `/home/joshua/.local/lib/cargo/target/release/hello-world`
$ strings /home/joshua/.local/lib/cargo/target/release/hello-world | grep homehome_dir
_ZN3std3sys4unix2os8home_dir17h5d3b091b9e7ed062E
home_dir
_ZN3std3sys4unix2os8home_dir8fallback17hb3ac94fa9a85ddbaE
_ZN3std3sys4unix2os8home_dir28_$u7b$$u7b$closure$u7d$$u7d$17ha072306bde63d38dE
_ZN3std3env8home_dir17h055eda4c1c3735acE
```

**Comment by unpavedmop** [comment] 2021-02-12 17:47
@jyn514 how do you propose that in a cargo.toml otherwise devs cant expect to tell people use this set of flags, and its hardcoded path

**Comment by ssokolow** [comment] 2021-02-12 17:53
@unpavedmop You put it in your README.

Same way ripgrep instructs people to use `RUSTFLAGS="-C target-cpu=native" cargo build --release --features 'simd-accel'` for best performance.

**Comment by jyn514** [comment] 2021-02-12 18:42
Hmm, I think this is duplicate of https://github.com/rust-lang/rust/issues/40552 (or the other way around).

**Comment by Subsentient** [comment] 2021-04-11 03:59
There is no excuse at all that this is still not fixed after 4 years. If it is a GDPR violation, I'd encourage any european developers to report this to their local DPA and light a fire under the rustc team. Maybe thousands and thousands of dollars of fines will encourage Rust to fix this. I won't be happy until a fix hits nightly.

**Comment by ssokolow** [comment] 2021-04-11 04:11
@Subsentient Rust is just inheriting legacy compiler behaviour habits also present in C, C++, and Go compilers (and probably anything else based on LLVM).

Also, I highly doubt this is a GDPR violation, or otherwise office suites like Microsoft Office and LibreOffice would be facing lawsuits for defaulting to embedding your name as author metadata in each document you create. (Don't believe me? Open up a `.odt` your LibreOffice created and grep for whatever name is in the "Created" field in `File > Properties` under the `General` tab.)

Likewise, Inkscape does the same thing with the `inkscape:export-filename` key, which embeds the last path you exported to PNG with in each SVG file you generate.

I'm not a lawyer, but I suspect the legal principle is "the GDPR requires you (the compiler runner) delete the personal information of you (the person whose information was embedded) from the file if you demand it of yourself". (ie. Because the compiler is running on your computer and doesn't automatically send the resulting binary anywhere outside your control, it's GDPR-compliant.)

**Comment by Subsentient** [comment] 2021-04-11 04:15
@ssokolow I'd fix the bug myself, but like other arrogant large FOSS projects, you wouldn't merge the patch. You've had 4 *years* to fix this, and your suggested workarounds don't even work most of the time! I'm getting really tired of the developer-hostile attitude of the Rust team and seeing this story in the news was the last straw.

**Comment by ssokolow** [comment] 2021-04-11 04:27
@Subsentient

* First, it's basic human nature that personal attacks (eg. calling me arrogant) are likely to get you ignored. Doesn't matter who you're talking to, in what profession.
* Second, I don't have commit access to this repo, so I *couldn't* merge such a patch. I'm just a user who's done his research.
* Third, this bug was triaged as `P-medium`. It *is* on their radar, but they (correctly) determined that, given how many other languages do the same thing, it's more urgent to fix other bugs first... bugs with labels like [I-unsound](https://github.com/rust-lang/rust/labels/I-unsound%20%F0%9F%92%A5).
* Fourth, note that @jyn514 (someone who *is* a member of the team) said things like "I can't reproduce this." that didn't get a reply. That means people are *interested* in fixing the problem but need help (which they're not getting) to track down where the bug is.
* Fifth, it takes time to restructure code to use the full path for the debugging information that goes to gdb/lldb/etc. from the paths that `strip` won't remove.)
* Finally, the story was "in the news" because another user with an attitude similar to yours decided to go nuclear in their efforts to bully the Rust developers into making this bug a higher priority, despite at least part of the holdup being "It's working fine for us. Please help us figure out why it's not working for you."

**Comment by Subsentient** [comment] 2021-04-11 04:31
@ssokolow 
>     * Finally, the story was "in the news" because another user with an attitude similar to yours decided to go nuclear in their efforts to bully the Rust developers into making this bug a higher priority,
I won't get into the list of grievances here, but suffice it to say, I've *tried* being civil, and in return people have not been civil to me. I've had it. The attitude of some members of the Rust team is absolutely unforgivable. I've dealt with developers like that before in other projects, the kind that lie to their users' faces and disregard the wishes of their userbase. You can ask around if you like and you'll find that it takes a lot for me to become uncivil, but I will not sit this one out any more. Rust is growing, and sooner or later I will have to deal with these awful decisions whether I like to or not. I'm not going to let that happen without a fight.

**Comment by ssokolow** [comment] 2021-04-11 04:42
@Subsentient As I said, doing it in just "a couple of lines" would completely break a lot of people's uses of `gdb` and `lldb`, and Rust is big on ensuring that `rustup update` won't break a build your company relies on to generate revenue.

That's why they'd reject any "a couple of lines" patch you contributed... because it'd break things.

To do it without that effect requires splitting apart handling of debuginfo paths and the kind of paths you're concerned with.

**Comment by Subsentient** [comment] 2021-04-11 04:47
@jyn514 As for not being able to reproduce the issue, try it on a different machine. Every machine I have, Windows or Linux, reproduces the issue in release mode.

**Comment by jyn514** [comment] 2021-04-11 04:53
@Subsentient could you please paste the exact commands you're running to replicate this? I'm running
```
cargo new hello-world
cd hello-world
echo '[profile.release]
panic = "abort"' >> Cargo.toml
RUSTFLAGS="--remap-path-prefix=/home/joshua/test-rustdoc/hello-world=src --remap-path-prefix=/home/joshua/.local/lib/cargo=cargo --remap-path-prefix=/home/joshua/.local/lib/rustup=rustup" cargo run --release
strings /home/joshua/.local/lib/cargo/target/release/hello-world | grep home
```
I've tried this on two different machines (one running Ubuntu 20.04, the other running Debian 10) and neither reproduces the issue.

**Comment by dmitry-zakablukov** [comment] 2021-04-11 07:20
@jyn514 , but what about the test in my original message? Remap flags are helpful to hide the names of the parent folders of a project. But these flags can't help to hide a _relative_ source file name.
P.S. It is still annoying to track down all parent folders names and can be easily messed up.

**Comment by dmitry-zakablukov** [comment] 2021-04-11 07:25
@Subsentient , what story in the news are you talking about? Can you please provide a link to it?

**Comment by Systemcluster** [comment] 2021-04-11 07:25
@jyn514 Also important to note that `--remap-path-prefix` does *not* work as expected in all cases, see e.g. https://github.com/rust-lang/rust/issues/73167

**Comment by Subsentient** [comment] 2021-04-11 07:56
@dmitry-zakablukov https://www.bleepingcomputer.com/news/security/most-loved-programming-language-rust-sparks-privacy-concerns/
@jyn514 For me, panic="abort" works, but --remap-path-prefix does nothing. I hadn't tried panic="abort" before because others said it did nothing. It seems, for me, the reverse is true. Both on MSYS2 Win10 and Fedora 33 x64.

**Comment by Subsentient** [comment] 2021-04-11 07:56
@dmitry-zakablukov Can you provide a dump of your cargo.toml? Maybe there's an option being set or something, idk.

**Comment by Subsentient** [comment] 2021-04-11 07:59
@jyn514 Is this metadata used for reading/locating files, or simply for debug information? if the latter, it might be better just to return only the base path of the file.

**Comment by daxpedda** [comment] 2021-04-11 09:20
See https://github.com/rust-lang/rust/issues/66955.
Which maybe might be why people are having re-production problems?

To summarize: there is a bug that `--remap-path-prefix` doesn't cause proper re-compilation and requires `cargo clean` to work properly.

**Comment by BurntSushi** [comment] 2021-04-11 13:00
**Moderation note:** Folks, please keep comments directed toward constructively resolving the problem at hand, just like you would any other issue. Further unconstructive meta commentary will be removed.

If you have questions about our moderation, please **do not respond here**. Instead, please email the mods at rust-mods@rust-lang.org.

**Comment by jyn514** [comment] 2021-04-11 13:06
Ok, this is related to release vs debug mode somehow, panic=abort has nothing to do with it. With a blank Cargo.toml this works properly:
```
$ RUSTFLAGS=--remap-path-prefix=/home/joshua/test-rustdoc/hello-world=src' --remap-path-prefix=/home/joshua/.local/lib/cargo=cargo --remap-path-prefix=/home/joshua/.local/lib/rustup=rustup' cargo run --release
$ strings target/release/hello-world | grep joshua | wc -l
0
```
but the same thing without --release (and without incremental) does not:
```
$ CARGO_INCREMENTAL=0 RUSTFLAGS=--remap-path-prefix=/home/joshua/test-rustdoc/hello-world=src' --remap-path-prefix=/home/joshua/.local/lib/cargo=cargo --remap-path-prefix=/home/joshua/.local/lib/rustup=rustup' cargo run -q
Hello, world!
$ strings target/debug/hello-world | grep joshua | wc -l
8
```

**Comment by dmitry-zakablukov** [comment] 2021-04-12 04:55
@Subsentient , @jyn514 , here is instruction to reproduce original problem (instruction was added to the first message).
```
git clone https://github.com/dmitry-zakablukov/rust-lang-issue-75263.git
cd rust-lang-issue-75263\symbols_test
cargo build --release
strings target\release\symbols_test.exe | grep "engine\src"
```

**Comment by jyn514** [comment] 2021-04-12 13:19
@dmitry-zakablukov I was able to omit those symbols altogether with `cargo run -Z build-std --target x86_64-unknown-linux-gnu -Zbuild-std-features=panic_immediate_abort --release`. It doesn't seem to work in debug mode (maybe because it's not stripping dead code?) but I would open a separate issue for that.

Again, the reason this happens with panic=abort is because that still runs the panic hook: https://github.com/rust-lang/rust/issues/75263#issuecomment-693648709. I would expect if you override the panic hook that might also let the compiler optimize out the strings: https://doc.rust-lang.org/std/panic/fn.set_hook.html.

---

I'm going to close this issue because there have been many different unrelated issues reported and most of them are being drowned in drama. I've opened https://github.com/rust-lang/rust/issues/84125 for the issue with --remap-path-prefix I ran into at the end, and there are already some other related open issues, such as https://github.com/rust-lang/rust/issues/66955. If you think --remap-path-prefix should be passed by default, see https://github.com/rust-lang/rust/issues/40552.

@Monadic-Cat I couldn't reproduce the bug in https://github.com/rust-lang/rust/issues/75263#issuecomment-693738512 - if you run into it again in release mode, could you please open a new issue? It might be https://github.com/rust-lang/rust/issues/73167 if you have rust-src installed. Debug mode is tracked by https://github.com/rust-lang/rust/issues/84125.

**Closed by jyn514** 2021-04-12 13:19 UTC
Labels: I-heavy, P-medium, T-compiler

**Comment by dmitry-zakablukov** [comment] 2021-04-12 15:13
@jyn514 , setting custom panic hook only doesn't resolve my issue.
I cannot afford to use a nightly compiler, so the workaround suggested by you is not suitable for me. How soon can I expect a `panic_immediate_abort` feature to be merged into stable compiler? And why this feature is not enabled even though I set a `panic = "abort"`?

**Comment by jyn514** [comment] 2021-04-12 15:17
> How soon can I expect a panic_immediate_abort feature to be merged into stable compiler?

I'm not sure there is a plan to stabilize this, I don't see a tracking issue.

> And why this feature is not enabled even though I set a panic = "abort"?

Because they do different things. Aborting immediately is different from printing a panic message and then aborting, and is much harder to debug.

**Comment by Monadic-Cat** [comment] 2021-04-12 15:45
I did have `rust-src` installed, yeah.
Removing the `rust-src` component and building in release mode has indeed removed the rustup paths from the final binary, so you're probably right.

**Comment by jyn514** [comment] 2021-04-12 15:51
> I'm not sure there is a plan to stabilize this, I don't see a tracking issue.

Oh sorry I misunderstood - the tracking repo for -Z build-std is https://github.com/rust-lang/wg-cargo-std-aware.

**Comment by crumblingstatue** [comment] 2021-05-01 10:23
@jyn514 
> This sounds like the compiler version is being embedded in the binary.
Is there a way to remove that information? Since --remap-prefix doesn't seem to affect it.

**Comment by crumblingstatue** [comment] 2021-05-01 10:57
A workaround I found to remove the home dir data from the .wasm binary I'm distributing:

`-Z build-std` generates duplicate lang item errors, but building with xargo worked.

Xargo.toml:
```toml
[dependencies]
std = {default-features=false, features=["panic_immediate_abort"]}
```

`xargo build --target=wasm32-unknown-unknown --release`

This removes all mentions of my home dir from the .wasm binary.

**Comment by jyn514** [comment] 2021-05-01 13:30
> -Z build-std generates duplicate lang item errors, 

Can you open an issue about that with more details?

**Comment by crumblingstatue** [comment] 2021-05-03 16:31
> Can you open an issue about that with more details?

Looks like there are already similar issues about this.

- https://github.com/rust-lang/cargo/issues/7359
- https://github.com/rust-lang/wg-cargo-std-aware/issues/56
