### ISSUE TITLE
Performance difference based on added no-op scope braces

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#34237] opened 2016-06-12 02:40 UTC
There appears to be an unexpected performance difference when adding an extra level of unneeded scope to a hot function.

Unfortunately, I ran into this while trying to make a raytracer, yet I've been having trouble finding a truly-minimal case that shows the disrepancy in performance (though I have made some progress). So, the MWE I have is 147 lines of a somewhat nonsensical reduction of the raytracer to some bare elements.

Anyway, here is the reproducible steps:

```
$ git clone git://genki.is/slow
$ cd slow
$ git fetch
$ git checkout master
$ cargo run --release
Time: 11.51502833100676 seconds
$ git checkout add-nop-scope
$ cargo run --release
Time: 8.3559323780064 seconds
```

This ~1.4-times discrepancy appears to scale with the amount of work done (the easiest way to test this is changing the value `750 * 750` in main()). Also note it only appears to have this difference when using  --release.

You can see that branch add-nop-scope adds an extra level of scope where it shouldn't be needed.

I expected to see this happen: Them to take just about the same amount of time.
## Further notes

I brought this up on #rust-beginners and received the help of @ubsan and @aatch in particular. My original observation was that it differed between a deconstructing-let vs a single-case-match. Here are my notes from what the two of them instead said [though please note that I could have misinterpreted them, and I could have missed some other key points]:

@ubsan noticed that it was simply the extra level of scope causing the difference. @aatch then noted that the discrepancy seems to be caused by the series of early-returns. He mentioned the idea that thus Rust generates a separate return slot for each return, but that one would think LLVM would optimize this away. And thus it is surprising that the one with the added scope block is faster. So note that for example, if one changes the last `Some(t)` to `return Some(t);`, it causes both master and add-nop-scope to take the same amount of time: about 10 seconds runtime.

@ubsan also noticed that with -Zorbit, both master and add-nop-scope appear to take about 10 seconds runtime, and thus that this would appear to be a MIR performance regression as well (but that the discrepancy disappears).

I apologize for the nonsensical manner of the code, again, it was hard to find a MWE from the ground up due to the changes seemingly caused by early returns being taken or not.
## Meta

```
$ rustc --version --verbose
rustc 1.11.0-nightly (a967611d8 2016-05-30)
binary: rustc
commit-hash: a967611d8ffececb5ed0ecf6a205b464d7a5a31e
commit-date: 2016-05-30
host: x86_64-unknown-linux-gnu
release: 1.11.0-nightly
```

Please don't hesitate to let me know if I can add any further details or help!

**Comment by eefriedman** [comment] 2016-06-12 06:33
Just looking at hit_t in isolation, the version without braces is getting caught in really ugly special case in trans (https://github.com/rust-lang/rust/blob/ee00760a14020d73e8ad509b2ddbd3054101db6f/src/librustc_trans/base.rs#L1379) that's causing a bunch of unnecessary stack traffic.  Not worth worrying about because this is going away with Zorbit.

Not sure why Zorbit is slower; I think the difference is outside of hit_t.  The first thing that strikes me is that the Zorbit code is loading and storing first-class aggregates, which is generally a bad idea.

**Comment by genkimarshall** [comment] 2016-06-12 16:56
Quoting eefriedman (2016-06-12 02:34:20)
> Just looking at hit_t in isolation, the version without braces is getting caught in really ugly special case in trans (https://github.com/rust-lang/rust/blob/ee00760a14020d73e8ad509b2ddbd3054101db6f/src/librustc_trans/base.rs#L1379) that's causing a bunch of unnecessary stack traffic.  Not worth worrying about because this is going away with Zorbit.

Ah okay I see, thanks for the clarification. I do vaguely recall aatch
mentioning something about nested returns. I still don't really feel I
understand it though, because my impression was that the default case
doesn't really seem like a case of 'return expr' where 'expr' has a
return in it. It is only when we add on a layer of nested {} that it
starts to seem like such a case, because it seems to say "Return this
{} block, were this {} block contains a return". The strange thing is,
that is the case that comes out faster. Typing this now, I think I
understand why aatch was saying that it is strange that it is faster
(as opposed to slower).

Regardless, if this mannerism is becoming obsolete soon then sure,
doesn't seem like it's worth worrying about indeed.

> Not sure why Zorbit is slower; I think the difference is outside of hit_t.  The first thing that strikes me is that the Zorbit code is loading and storing first-class aggregates, which is generally a bad idea.

Okay, I'm curious but don't understand this OTOH, I will read about it
later. Thanks for your thoughts.

**Comment by Mark-Simulacrum** [comment] 2017-05-14 19:45
I cannot clone, so I don't think there's much we can do here (without being able to reproduce, debugging performance problems is hard); closing.

```
$ git clone git://genki.is/slow
Cloning into 'slow'...
fatal: remote error: access denied or repository not exported: /slow
```

**Closed by Mark-Simulacrum** 2017-05-14 19:45 UTC
Labels: I-slow
