### ISSUE TITLE
Build -Zbuild-std with -Zsparse-registry failed.

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/rust#103245] opened 2022-10-19 12:56 UTC
Just found that, when build using `-Zbuild-std` and `-Zsparse-registry` got error like below.

```
error: failed to get `cfg-if` as a dependency of package `std v0.0.0

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of config.json failed

Caused by:
  failed to download from `sparse+https://index.crates.io/config.json`

Caused by:
  [1] Unsupported protocol (Protocol "sparse+https" not supported or disabled in libcurl)
```
Any suggestions? ...

**Comment by ehuss** [comment] 2022-10-19 14:02
Thanks for the report! This was a regression in Cargo. It should be fixed tomorrow. Closing as a duplicate of https://github.com/rust-lang/cargo/issues/11246.

**Closed by ehuss** 2022-10-19 14:02 UTC
Labels: C-bug
