### ISSUE TITLE
`where T: ?Sized` doesn't parse

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#30550] opened 2015-12-24 14:08 UTC
Example: http://is.gd/rB5WGc

RFC 490 says this should be accepted: https://github.com/rust-lang/rfcs/blob/master/text/0490-dst-syntax.md#detailed-design

> Change the syntax for traits for dynamically-sized types to have a prefix `?` instead of a postfix one:
> ```rust
> trait Foo for ?Sized { ... }
> ```
> Allow using this syntax in `where` clauses:
> ```rust
> fn foo<T>(x: &T) where T: ?Sized { ... }
> ```

Note that, if the parser is changed to accept this, type collection needs to be fixed to look at `where` clauses instead of just type param bounds when figuring out if a `Sized` bound should be added.

**Comment by Stebalien** [comment] 2015-12-24 17:22
Duplicate of #20503

**Closed** 2015-12-24 17:41 UTC
