### ISSUE TITLE
rustdoc nightly: search deduplication can cause missing items

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#45968] opened 2017-11-13 20:42 UTC
This example is outdated, but in it, `thread::spawn` is missing in nightly.

stable:
![](https://i.imgur.com/JhfAz96.png)

nightly:
![](https://i.imgur.com/1CYVDpZ.png)

Probably caused by https://github.com/rust-lang/rust/commit/ee7e372bbf2d6ce184e50aaf2679873eb961dc49.

**Comment by crumblingstatue** [comment] 2017-11-15 17:43
This seems fixed on `(ff0f5de3b 2017-11-14)`, but I don't know if a regression test should be added or something, so I'll leave this open for now.

**Comment by ollie27** [comment] 2017-11-16 15:03
This isn't fixed. Now `std::thread::Builder::spawn` is missing. I believe this was originally caused by ee7e372bbf2d6ce184e50aaf2679873eb961dc49 (cc @GuillaumeGomez). It seems to be de-duplicating search results based on `path + name` ignoring `parent` and `ty` so it's treating `std::thread::spawn` and `std::thread::Builder::spawn` as the same.

**Comment by GuillaumeGomez** [comment] 2017-11-24 20:42
I have to wait for both of my rustdoc PRs [here](https://github.com/rust-lang/rust/pull/46081) and [here](https://github.com/rust-lang/rust/pull/46175)) to be merged before looking for this.

**Comment by durka** [comment] 2017-11-28 23:07
Searching for `read_to_end` in the nightly docs doesn't come up with `std::io::Read::read_to_end`. Is this the same issue?

**Comment by GuillaumeGomez** [comment] 2017-11-29 09:07
Maybe? I'll take a look as well.

**Comment by GuillaumeGomez** [comment] 2017-12-01 19:47
Can you confirm once again? When I just tested on nightly, it worked as expected?

**Comment by GuillaumeGomez** [comment] 2017-12-01 19:48
@durka: However, your issue is still there. Taking a look.

**Closed** 2017-12-03 13:01 UTC
Labels: A-rustdoc, C-bug, regression-from-stable-to-nightly, T-dev-tools-rustdoc
