### ISSUE TITLE
cargo fix --edition breaks on serde deserialize_with attributes

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#87578] opened 2021-07-29 08:59 UTC
I tried this code:

```rust
#[derive(Debug, Deserialize)]
struct OwnedPair<T>(
    T,
    #[serde(deserialize_with = "::serde_utils::hex_bytes::deserialize")]
    Vec<u8>,
);
```

And `cargo fix --edition`

I expected to see this happen: the code gets fixed

Instead, this happened: It attempted to fix it like this: `#[serde(deserialize_with = crate::"::serde_utils::hex_bytes::deserialize")]` and obviously failed.

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

Same happens on nightly, 1.36, and 1.48

Context: I tried to convert https://github.com/rust-bitcoin/rust-bitcoin/ to edition 2018

**Comment by Kixunil** [comment] 2021-07-29 09:28
Note that after manually fixing `bitcoin` and applying `--edition-idioms` I get more errors - it seems to duplicate lifetime markers like this: `<'_><'_>`.

**Comment by ehuss** [comment] 2021-07-29 14:06
Thanks for the report!  I'm going to close as this is a duplicate of #56625.

To work around the issue, you can manually adjust the paths in the strings to start with `crate::` before doing the migration.  Alternatively, you can migrate with the `--broken-code` flag, and then fix the issues manually.

**Closed by ehuss** 2021-07-29 14:06 UTC
Labels: C-bug

**Comment by Kixunil** [comment] 2021-07-29 16:15
Damn, I didn't find #56625 I guess because of funny title. Yeah, `--broken-code` helped. Thanks!
