### ISSUE TITLE
Building Firefox with rustc 1.34.0-nightly fails with LLVM ERROR: broken function found.

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#58881] opened 2019-03-02 21:33 UTC
Unfortunately I haven't been able to reproduce outside of the Firefox build system. I assume this is a regression from #58408, cc @alexcrichton. 

```
 0:13.50 Wrong types for attribute: byval inalloca nest noalias nocapture nonnull readnone readonly signext sret zeroext dereferenceable(1) dereferenceable_or_null(1)
 0:13.50   call void (i8*, ...) %96(i8* %101, { i64, i64 } %115, { i64, i64 } %118, { [0 x i8]*, i64 } %120, { i64, i64 } byval noalias nocapture dereferenceable(16) %124, { [0 x i8]*, i64 }* %5), !dbg !1889
 0:13.50 in function _ZN97_$LT$cubeb_pulse..backend..context..PulseContext$u20$as$u20$cubeb_backend..traits..ContextOps$GT$34register_device_collection_changed17update_collection17h9f106daf4cf87a02E
 0:13.50 LLVM ERROR: Broken function found, compilation aborted!
 0:13.64 error: Could not compile `cubeb-pulse`.
 0:13.67 Caused by:
 0:13.67   process didn't exit successfully: `CARGO_MANIFEST_DIR=/home/emilio/src/moz/gecko/media/libcubeb/cubeb-pulse-rs CARGO_PKG_VERSION_PRE= CARGO_PKG_NAME=cubeb-pulse CARGO_PKG_HOMEPAGE= CARGO_PKG_AUTHORS='Dan Glastonbury <dglastonbury@mozilla.com>' CARGO_PKG_DESCRIPTION='Cubeb backed for PulseAudio written in Rust' LD_LIBRARY_PATH='/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/debug/deps:/home/emilio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/emilio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_REPOSITORY= CARGO_PKG_VERSION_MINOR=2 CARGO=/home/emilio/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION=0.2.0 /home/emilio/.cargo/bin/rustc --crate-name cubeb_pulse media/libcubeb/cubeb-pulse-rs/src/lib.rs --color always --crate-type staticlib --crate-type rlib --emit=dep-info,link -C opt-level=1 -C panic=abort -C debuginfo=2 -C debug-assertions=on --cfg 'feature="pulse-dlopen"' --cfg 'feature="pulse-ffi"' -C metadata=d5a9783431e388af -C extra-filename=-d5a9783431e388af --out-dir /home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C linker=/home/emilio/src/moz/gecko/build/cargo-linker -C incremental=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/debug/deps --extern cubeb_backend=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/deps/libcubeb_backend-44de29cd13d09317.rlib --extern pulse=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/deps/libpulse-1a07f564e62af458.rlib --extern pulse_ffi=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/deps/libpulse_ffi-3634bc0fd9d2e2d4.rlib --extern semver=/home/emilio/src/moz/gecko/obj-x86_64-pc-linux-gnu/x86_64-unknown-linux-gnu/debug/deps/libsemver-d5bc6c91229d5335.rlib -C opt-level=0 -C debuginfo=2 -Dwarnings` (exit code: 101)
```

**Comment by alexcrichton** [comment] 2019-03-04 15:45
Unfortuntely this probably isn't too actionable unless we can reduce it to the point where we can give it to upstream LLVM

**Comment by emilio** [comment] 2019-03-05 14:17
Ok, I tried to figure out why it wasn't reproducing outside of the build system, and manage to get some STR:

```
$ git clone https://github.com/djg/cubeb-pulse-rs && cd cubeb-pulse-rs
$ cargo update -p cubeb-backend --precise 0.5.0 # This was the bit that mattered, somehow.
$ cargo build
```

**Comment by emilio** [comment] 2019-03-05 14:38
v0.5.1 works, v0.5.0 does not.

https://github.com/djg/cubeb-rs/compare/98f5a8b4..d18f114f

cc @djg

**Comment by emilio** [comment] 2019-03-05 14:41
Well, the `cubeb_log!` macro is used in the borked `update_collection` function, so that's something. I'll try to reduce it further.

**Comment by emilio** [comment] 2019-03-05 14:58
Ok, this test-case crashes for me:

```
use std::os::raw::c_char;

pub type cubeb_log_callback = Option<unsafe extern "C" fn(*const c_char, ...)>;
extern "C" {
    pub static g_cubeb_log_callback: cubeb_log_callback;
}

pub fn foo(index: u32) {
    unsafe {
        let op = "Adding";
        let dev = "sink";
        if let Some(log_callback) = g_cubeb_log_callback {
            let cstr = ::std::ffi::CString::new("%s:%d: {} {} index {}\n").unwrap();
            log_callback(cstr.as_ptr(), file!(), line!(), op, dev, index);
        }
    }
}

fn main() {
    let args = ::std::env::args().count();
    foo(args as u32);
}
```

The code is completely unsound of course... Passing a static string into a C variadic function makes no sense. Maybe rustc should warn about that?

**Comment by emilio** [comment] 2019-03-05 15:12
This is the most reduced thing I could come up width;

```rust
extern "C" {
    pub static g_cubeb_log_callback: unsafe extern "C" fn(*const u8, ...);
}

fn main() {
    unsafe {
        let f = "file";
        let op = "Adding";
        let dev = "sink";
        let cstr = b"foo\0";
        g_cubeb_log_callback(cstr.as_ptr(), f, op, dev);
    }
}
```

**Comment by alexcrichton** [comment] 2019-03-05 15:41
Thanks for the reduction @emilio! I can indeed also reproduce with:

```rust
# Today's nightly, with LLVM assertions
$ rustup-toolchain-install-master a9da8fc9c267c08cfdb8cf5b39da14f154d12939 --alt
$ rustc +a9da8fc9c267c08cfdb8cf5b39da14f154d12939-alt foo.rs
warning: `extern` block uses type `()` which is not FFI-safe: tuples have unspecified layout
 --> foo.rs:2:38
  |
2 |     pub static g_cubeb_log_callback: unsafe extern "C" fn(*const u8, ...);
  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(improper_ctypes)] on by default
  = help: consider using a struct instead

Wrong types for attribute: byval inalloca nest noalias nocapture nonnull readnone readonly signext sret zeroext dereferenceable(1) dereferenceable_or_null(1)
  call void (i8*, ...) %4(i8* %5, { i64, i64 } %10, { i64, i64 } %14, { i64, i64 } byval noalias nocapture dereferenceable(16) %18)
in function _ZN3foo4main17h0e6b3bfd37376208E
LLVM ERROR: Broken function found, compilation aborted!
```

I'm gonna cc @rust-lang/compiler on this because this actually looks more like a codegen bug on our end than an LLVM bug, and LLVM may have just added more validation or something like that.

**Comment by emilio** [comment] 2019-03-05 15:46
Yeah, that sounds right. Thanks for taking a look Alex!

FWIW, I worked around the bug in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1532645 (by updating the dependency to one that doesn't have the unsound code), so this is no longer blocking anyone, hopefully.

**Comment by nagisa** [comment] 2019-03-05 15:50
looks like bad cidegen to me. dereferenceable attribute is put on an
argumant that has a non-pointer type. As other arguments have no attributes
at all i suspect that we end up setting attributes intended for other
arguments onto the last one.

**Comment by stefson** [comment] 2019-03-10 22:12
@emilio do you happen to know wether esr is affected as well? It has cubeb-0.4.1 pulled in, but I'm note sure if the logic here is that <=cubeb-0.5.0 is affected, or only =cubeb-0.5.0?

**Comment by emilio** [comment] 2019-03-11 11:38
@stefson I don't know off-hand, would need to test.

**Comment by pnkfelix** [comment] 2019-03-14 13:14
triage: assuming P-high since it originated as a Firefox build problem.

**Comment by pnkfelix** [comment] 2019-03-21 14:30
assigning to self for initial investigation.

**Comment by pnkfelix** [comment] 2019-03-21 15:16
(leaving nominated for now to keep myself honest in case I somehow get to next week's meeting without looking at this. if I do investigate and it bears fruit I'll remove nomination at that time.)

**Comment by pnkfelix** [comment] 2019-03-26 14:37
This version is a little bit smaller than @emilio's great reduction [above](https://github.com/rust-lang/rust/issues/58881#issuecomment-469716921):

```rust
extern "C" {
    fn variadic(arg: u8, ...);
}

fn main() {
    unsafe {
        let f = "file";
        variadic(0, f, f, f);
    }
}
```

(The main feature here is that it demonstrates the problem without using a callback to a static variable, which I had mistakenly thought was an important part of replicating the problem.)

**Comment by varkor** [comment] 2019-03-26 14:48
Might this be related to the recent variadic function changes? cc @dlrobertson

**Comment by pnkfelix** [comment] 2019-03-26 14:54
(FYI, bisection indicates this was injected between nightly-2019-02-28 and nightly-2019-03-01.)

**Comment by pnkfelix** [comment] 2019-03-26 14:55
@varkor that theory sounds very plausible, given the following bors merges from the point I bisected:

```
 % git log 7e001e5c6..350674b71 --author=bors --format=oneline
```
350674b7180a41c8e508d93c6ab8e203b69d3df7 Auto merge of #58250 - Zoxc:rustc-interface-1, r=oli-obk
1999a2288123173b2e487865c9a04386173025f7 Auto merge of #57760 - dlrobertson:varargs1, r=alexreg
190feb65290d39d7ab6d44e994bd99188d339f16 Auto merge of #58208 - taiki-e:libstd-2018, r=Centril

**Comment by dlrobertson** [comment] 2019-03-26 14:55
It is very likely I caused this. I'll look into it

**Comment by pnkfelix** [comment] 2019-03-26 14:58
reassigning to @dlrobertson and removing nominated tag.

tagging as regression from stable-to-nightly.

**Comment by dlrobertson** [comment] 2019-03-26 15:55
Appears to be an issue if a structure is passed to a C-variadic. E.g.

```rust
extern "C" {
    fn variadic(arg: u8, ...);
}

fn main() {
    unsafe {
        let f = b"file\0";
        variadic(0, f.as_ptr(), f.as_ptr(), f.as_ptr()); // does not ICE
        variadic(0, f, f, f); // will ICE
    }
}
```

**Closed** 2019-03-31 23:51 UTC
Labels: A-LLVM, A-codegen, C-bug, P-high, T-compiler, regression-from-stable-to-nightly
