### ISSUE TITLE
Rustdoc: leaves alias type's documetation empty

### ISSUE THREAD

**Issue by timthelion** [rust-lang/rust#107690] opened 2023-02-05 15:03 UTC
Types that are generated by a macro from another type using a decorator end up with empty documentation.  [Here is an example](https://docs.rs/ruma/0.7.4/ruma/events/room/message/type.OriginalSyncRoomMessageEvent.html#)

I expected to see this happen: I expected to see the fields and methods I can use with objects of this type. For example, [I know from context](https://github.com/matrix-org/matrix-rust-sdk/blob/main/examples/command_bot/src/main.rs#L14) that this type has a `content` attribute but no such attribute is shown in the docs.

Example code from the same project:

```rust
async fn on_room_message(event: OriginalSyncRoomMessageEvent, room: Room) {
    if let Room::Joined(room) = room {
        let MessageType::Text(text_content) = event.content.msgtype else {
            return;
        };

        if text_content.body.contains("!party") {
            let content = RoomMessageEventContent::text_plain("🎉🎊🥳 let's PARTY!! 🥳🎊🎉");

            println!("sending");

            // send our message to the room we found the "!party" command in
            // the last parameter is an optional transaction id which we don't
            // care about.
            room.send(content, None).await.unwrap();

            println!("message sent");
        }
    }
}
```

Instead, this happened: 

![image](https://user-images.githubusercontent.com/1391608/216827148-60c713d4-2b61-4739-baa3-e6768c830749.png)

**Comment by jyn514** [comment] 2023-02-05 21:26
@timthelion do you see the same problem if you write out the type alias without a macro? If so, it's probably related to the alias, not the macro.

**Comment by timthelion** [comment] 2023-02-05 21:30
I'm sorry but I don't know what the type alias without the macro is. How would I figure that out without docs? I didn't write the code in question and I'm still quite new to rust.

**Comment by jyn514** [comment] 2023-02-05 22:22
The one shown in the docs, `pub type OriginalSyncRoomMessageEvent = OriginalSyncMessageLikeEvent<RoomMessageEventContent>;`

**Comment by timthelion** [comment] 2023-02-06 09:31
Oh, wow, I didn't realize that. So basically it would be fixed if the docs contained the same thing as this page https://docs.rs/ruma/0.7.4/ruma/events/struct.OriginalSyncMessageLikeEvent.html but with `C` replaced with `RoomMessageEventContent`. Or maybe we can somehow detect that there is a type alias and change the UX like so:

![image](https://user-images.githubusercontent.com/1391608/216935890-3235d583-6201-48fb-a482-9e70fb2355cd.png)

**Comment by fmease** [comment] 2023-02-06 13:49
Duplicate of feature request #99952.

**Comment by timthelion** [comment] 2023-02-06 14:43
@fmease yeah, probably, thanks.

**Closed** 2023-02-06 14:43 UTC
Labels: C-bug
