### ISSUE TITLE
Impl with missing bounds compiles when used with specialization

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust#68765] opened 2020-02-02 11:06 UTC
Hi! I believe the following program should not compile, but it compiles fine:

```rust
#![feature(specialization)]

use core::ops::Deref;

pub trait HasId {
    fn id(&self) -> usize;
}

// Notice the lack of bound `<T as Deref>::Target : HasId`
impl<T:Deref> HasId for T {
    default fn id(&self) -> usize {
        let target:&<T as Deref>::Target = self.deref();
        target.id()
    }
}
```

**Comment by jonas-schievink** [comment] 2020-02-02 11:55
This ends up using the `impl<'a, T> Deref for &'a T`, and it also happens without specialization:

```rust
use core::ops::Deref;

pub trait HasId {
    fn id(&self) -> usize;
}

// Notice the lack of bound `<T as Deref>::Target : HasId`
impl<T:Deref> HasId for T {
    fn id(&self) -> usize {
        let target:&<T as Deref>::Target = self.deref();
        target.id()
    }
}
```

(This simply ends up calling the same method recursively)

Closing as not a bug.

**Closed by jonas-schievink** 2020-02-02 11:55 UTC
Labels: A-specialization, C-bug, F-specialization, T-compiler, requires-nightly
