### ISSUE TITLE
Futures involving uninhabited variables are incorrectly considered uninhabited.

### ISSUE THREAD

**Issue by Lymia** [rust-lang/rust#59972] opened 2019-04-14 19:58 UTC
[The following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=94e94d2007ff9c296483de69a0446837) crashes with an illegal instruction, presumably because all the code after `contains_never` is considered unreachable:

```rust
#![feature(futures_api, async_await, await_macro)]

pub enum Uninhabited { }

fn uninhabited_async() -> Uninhabited {
    unreachable!()
}

async fn noop() { }

async fn contains_never() {
    let error = uninhabited_async();
    await!(noop());
    let error2 = error;
}

fn main() {
    contains_never();
}
```

It seems the root cause is that the struct representing the future contains a field of type `Uninhabited` as it is preserved across the (unreachable) yield point and thus is considered uninhabited itself, despite being perfectly constructible.

**Comment by RalfJung** [comment] 2019-04-14 21:05
This sounds like it is caused by the fact that generators have an "incorrect" layout (claiming to have fields with certain types when really these might not be initialized), and some code not taking that special case into account proper.y

Cc @eddyb @cramertj

**Comment by cramertj** [comment] 2019-04-15 17:38
cc @tmandry

**Comment by tmandry** [comment] 2019-04-15 23:02
This is actually already fixed in #59897 (currently a WIP), [around here](https://github.com/rust-lang/rust/pull/59897/files#diff-64895729f1108bd9264638a0e6409485R634). I'll make sure to add this as a test to that PR!

**Comment by RalfJung** [comment] 2019-04-16 08:48
@tmandry does that mean that generators will no longer "cheat" in their layout, and https://github.com/rust-lang/rust/blob/a7cef0bf0810d04da3101fe079a0625d2756744a/src/librustc/ty/layout.rs#L1813 can be removed? That'd be cool :D

I'd also have to adjust https://github.com/rust-lang/rust/blob/master/src/librustc_mir/interpret/visitor.rs#L315 -- can that be treated like any other type then because the variants have all the right information?

**Comment by eddyb** [comment] 2019-04-17 07:58
@RalfJung I don't think it's that simple, we'd likely still need to keep uninitialized variables for now.
Although... I suppose the state variants, for yields across which they're not live, could just omit those variables, *despite* not using that space for anything else.

**Comment by tmandry** [comment] 2019-04-17 18:14
> @RalfJung I don't think it's that simple, we'd likely still need to keep uninitialized variables for now.
> Although... I suppose the state variants, for yields across which they're not live, could just omit those variables, _despite_ not using that space for anything else.

We could do that, yes, with some further changes to my PR. I would like to get there, and then we can have UB checking for our generators as well :)

**Comment by pnkfelix** [comment] 2019-04-18 11:48
triage: P-high. removing nominated tag.

**Comment by Centril** [comment] 2019-05-04 06:00
Reopening for the test that https://github.com/rust-lang/rust/pull/59897 didn't add (as far as I can tell; cc @eddyb & @tmandry)

**Closed** 2019-05-09 01:51 UTC
Labels: A-async-await, AsyncAwait-Blocking, C-bug, E-needstest, I-unsound 💥, P-high, T-compiler
