### ISSUE TITLE
returning a future from a function with an `impl Trait` argument references that argument even if not used in the future, causing lifetime errors

### ISSUE THREAD

**Issue by pushrax** [rust-lang/rust#125341] opened 2024-05-20 18:57 UTC
I minimized an error I encountered into this reproduction: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=85de243a39f64d49d42939066a2a824c

```rust
use std::future::Future;

fn fn2(_unused: impl AsRef<[u64]>) -> impl Future<Output = ()> {
    async move {}
}

fn fn1() -> impl Future<Output = ()> {
    let v = vec![1];
    fn2(&v)
}

#[tokio::main]
async fn main() {
    fn1().await;
}
```

This should compile.

Instead, this happened:

```
error[E0597]: `v` does not live long enough
  --> src/main.rs:9:9
   |
8  |     let v = vec![1];
   |         - binding `v` declared here
9  |     fn2(&v)
   |     ----^^-
   |     |   |
   |     |   borrowed value does not live long enough
   |     argument requires that `v` is borrowed for `'static`
10 | }
   | - `v` dropped here while still borrowed
```

The function argument is unused and it doesn't make sense that it should be borrowed for `'static`.

If the `impl AsRef<[u64]>` argument is changed to `&[u64]` the snippet compiles fine. It seems like any `impl Trait` argument passed by value will cause the issue.

In the original non-minimized code, the argument wasn't unused, but only used outside the returned future.

### Meta

repros on stable as well as latest nightly (1.80.0-nightly 2024-05-19 d84b9037541f45dc2c52)

cc @morgangallant

**Comment by jwong101** [comment] 2024-05-20 19:11
This happens with any generic type parameter, since those are automatically captured by RPITs. This needs the [precise captures](https://github.com/rust-lang/rust/issues/123432) feature in order to compile.

Minimized:

```rust
fn capture<T>(_: T) -> impl Sized { }

fn ret() -> impl Sized {
    let u = 0;
    capture(&u)
}
```

**Comment by traviscross** [comment] 2024-05-20 20:51
The analysis by @jwong101 is correct.  Let's close this as a duplicate of:

- https://github.com/rust-lang/rust/issues/42940

Thanks to @pushrax for the report.

**Closed by traviscross** 2024-05-20 20:51 UTC
Labels: A-lifetimes, A-impl-trait, C-bug, WG-async

**Comment by pushrax** [comment] 2024-05-20 22:56
Thanks for your help!!
