### ISSUE TITLE
Vec::with_capacity(u64) panics when built

### ISSUE THREAD

**Issue by JesperAxelsson** [rust-lang/rust#38277] opened 2016-12-10 04:03 UTC
Vec::with_capacity(u64) panics. 
Error message: 

    rustc main.rs -v
    error: internal compiler error: ../src/librustc_typeck\check/mod.rs:4396: unexpected definition: PrimTy(TyUint(u64))
    
    note: the compiler unexpectedly panicked. this is a bug.
    
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    
    thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:423
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

Minimal program: 
`fn main() {
    let vec = Vec::with_capacity(u64);
}
`

**Comment by Stebalien** [comment] 2016-12-10 05:52
Duplicate of  #38155 and #38188, fixed in #38154. /cc @petrochenkov

**Comment by steveklabnik** [comment] 2016-12-14 23:23
Closing as a duplicate, thank you!

**Closed by steveklabnik** 2016-12-14 23:23 UTC
Labels: I-ICE
