### ISSUE TITLE
Error with nested async fn and anonymous lifetimes

### ISSUE THREAD

**Issue by udoprog** [rust-lang/rust#63225] opened 2019-08-02 19:42 UTC
The following breaks on nightly (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a1aabca3f0059c24f101e3a149632fbd))

```rust
#![feature(async_await)]

struct Foo<'a>(&'a ());

impl Foo<'_> {
    fn test() {
        async fn test() {}
    }
}
```

With:

```
error[E0261]: use of undeclared lifetime name `'_`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0261`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

CC: dtolnay/async-trait#18

**Comment by Centril** [comment] 2019-08-02 21:18
Reduced:
```rust
#![feature(async_await)]

struct Foo<'a>(&'a ());

impl<'a> Foo<'a> {
    fn test() {
        async fn test() {}
    }
}
```

**Comment by udoprog** [comment] 2019-08-02 21:33
Forgot to mention in case this helps, giving the inner fn a _matching_ lifetime avoids this for some reason:
```rust
#![feature(async_await)]

struct Foo<'a>(&'a ());

impl Foo<'_> {
    fn test() {
        async fn test<'a>() {}
    }
}
```

**Comment by cramertj** [comment] 2019-08-06 17:11
The reason this is happening is that the desugared version of `async fn` applies all in-scope lifetimes to the returned existential type, which in this case is creating `-> Fut<'_>`, which is invalid. I'm not sure exactly what the best fix is for this, though, since elided lifetimes in the impl signature are intentionally unnameable. The closest idea I have would be to create some special new lifetime that is `'_` but can refer to lifetimes originating from the impl header. cc @nikomatsakis who may have opinions.

**Comment by nikomatsakis** [comment] 2019-08-07 09:42
Hmm @cramertj wouldn't you expect the nested `async fn` to not inherit *anything* from its enclosing scopes? Seems like a bug to me that it does? Am I confused about something?

**Comment by cramertj** [comment] 2019-08-07 16:06
@nikomatsakis The function in the middle is actually a bit of a source of confusion here, although it does indicate that there's a *second* bug since we shouldn't be inheriting generics since the nested `async fn` isn't part of the `impl`.

The bug I was focusing on is better illustrated by this example:

```rust
#![feature(async_await)]

struct Foo<'a>(&'a u8);

impl Foo<'_> {
    async fn bar() {}
}
```
which produces this error:
```
error[E0261]: use of undeclared lifetime name `'_`

error: aborting due to previous error
```

This is because the code is transformed into
```rust
impl Foo<'_> {
    fn bar() -> OpaqueTy<'_> {}
}
```

and in that case `'_` does not refer back to the usage from the `impl` header.

**Comment by nikomatsakis** [comment] 2019-08-12 12:51
@cramertj I see. Indeed, I would expect that, internally, we'd have some way to refer back to the `'_` from the impl header. I believe this should be possible, no? In particular, the `'_` in impls expands (internally) to `LifetimeName::Param(ParamName::Fresh(N))` for some integer N, which I believe is basically treated like any other named lifetime.

**Comment by cramertj** [comment] 2019-08-12 16:17
@nikomatsakis Yep, I would've expected so as well-- I'm not sure why that isn't working, I'd have to take a look.

**Comment by nikomatsakis** [comment] 2019-08-12 16:29
@cramertj I was looking and I think the bug lies here:

https://github.com/rust-lang/rust/blob/c01be67ea40266d6a4c3289654a07ddd7ce2a172/src/librustc/hir/lowering.rs#L2267-L2272

Probably `in_scope_lifetimes` needs to be a `Vec<ParamName>` instead, or we need to use something else for this purpose.

**Comment by nikomatsakis** [comment] 2019-08-12 18:33
A closer reading suggests I was mistaken. The `'_` lifetimes from the impl should show up in `lifetimes_to_define` -- `in_scope_lifetimes` includes only the explicitly declared lifetimes written by the user on the impl. I'm not quite sure what the problem is yet.

**Comment by nikomatsakis** [comment] 2019-08-12 18:58
OK, no, I was correct. When processing impl items, we convert the `'_` lifetimes into `in_scope_lifetime` entries.

**Comment by nikomatsakis** [comment] 2019-08-12 19:14
OK, I have a fix for the `async fn` method issue, but not the nested async fn item issue.

**Comment by nikomatsakis** [comment] 2019-08-12 19:16
I forked off https://github.com/rust-lang/rust/issues/63500 for the method issue

**Comment by nikomatsakis** [comment] 2019-08-12 21:05
@cramertj I didn't prep a fix for this one yet. It seems obvious that some internal state is not being reset when we enter a new item.

**Comment by nikomatsakis** [comment] 2019-08-12 21:06
but if you have a chance to investigate, would be appreciated

**Comment by nikomatsakis** [comment] 2019-08-12 23:50
Presumably the problem is that `visit_item` doesn't "reset" the `in_scope_lifetimes` vector -- it only seems to extend it...

https://github.com/rust-lang/rust/blob/c01be67ea40266d6a4c3289654a07ddd7ce2a172/src/librustc/hir/lowering/item.rs

**Comment by nikomatsakis** [comment] 2019-08-12 23:53
Indeed, in-band lifetimes are broken in the same way. This fails to compile ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=16cf7032d6071e7eb87ca5e70bf10226)):

```rust
#![feature(in_band_lifetimes)]

struct Foo<'a> {
    x: &'a u32
    
}

impl Foo<'a> {
    fn method(&self) {
        fn blah(f: Foo<'a>) { }
    }
}
```

**Comment by nikomatsakis** [comment] 2019-08-12 23:59
Working on a possible fix

**Comment by nikomatsakis** [comment] 2019-08-13 00:08
Yep, have a fix.

**Comment by Mark-Simulacrum** [comment] 2019-08-13 00:54
Inband lifetimes looks similar to https://github.com/rust-lang/rust/issues/52532 fwiw

**Comment by nikomatsakis** [comment] 2019-08-13 01:14
@Mark-Simulacrum thanks

**Closed** 2019-08-14 10:52 UTC
Labels: A-async-await, AsyncAwait-Blocking, C-bug, F-async_await, T-compiler
