### ISSUE TITLE
Large executable while compiling for windows from Linux systems

### ISSUE THREAD

**Issue by noelaugustin** [rust-lang/rust#60504] opened 2019-05-03 07:39 UTC
I have a simple Hello World program, which only has a single line in the main function of main.rs, which is
`
println!(Hello World);
`

Adding to the default package that is done by cargo init, the cargo.toml file has
`[profile.dev]`
` panic="abort"`

When I compile the code with target `i686-pc-windows-gnu`, with the linker being `i686-w64-mingw32-g++` on linux, for windows, I get an exe, which is 3052 kB, and when i do the same with target `i686-pc-windows-msvc`, for windows on windows, I get an exe, which is 112 kB. Could someone suggest as to how I can reduce the size while I cross compile my code for windows from Linux? This is a concern as the difference in size is almost 30 times.

**Comment by jonas-schievink** [comment] 2019-05-03 09:30
Those are separate targets (GNU vs. MSVC), what's the size when you build for the GNU target while on Windows?

**Comment by mati865** [comment] 2019-12-27 11:24
Binaries linked by GCC are not stripped. Therefore this is duplicate of https://github.com/rust-lang/rust/issues/46034

> what's the size when you build for the GNU target while on Windows?

The same as when cross compiling from Linux.

**Comment by jonas-schievink** [comment] 2019-12-27 11:26
Thanks, closing as a duplicate then.

**Closed by jonas-schievink** 2019-12-27 11:26 UTC
Labels: I-heavy, O-windows-gnu, T-compiler
