### ISSUE TITLE
Bug: Spawn a thread with a empty loop,  program will coredump when compile  with optimizations

### ISSUE THREAD

**Issue by biluohc** [rust-lang/rust#46076] opened 2017-11-18 12:35 UTC
I found the bug because of  i need a hand warmer.
My system is  openSUSE 42.3(Linux 4.4.92 x86-64).
My rustc is 1.23.0-nightly and  1.21.0.
My code is follows: 
```rust
fn main() {
    let handle = std::thread::spawn(||loop {});
    handle.join().unwrap()
}
```

**Comment by rkruppe** [comment] 2017-11-18 12:56
Duplicate of #28728

**Comment by rkruppe** [comment] 2017-11-18 12:58
Thanks for the bug report! This bug is already tracked at #28728

**Comment by biluohc** [comment] 2017-11-18 13:04
Oh, Thanks you.

**Comment by bluss** [comment] 2017-11-18 13:40
Note recent improvement #45920 that made such code into a memory safe albeit unpleasant crash. Closing since it's a duplicate of #28728.

**Closed by bluss** 2017-11-18 13:40 UTC
