### ISSUE TITLE
ICE in the face of malformed code

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#127981] opened 2024-07-19 17:33 UTC
### Code

```Rust
fn enum_upvar() {
    type T = impl Copy;
    let foo: T = Some((1u32, 2u32));
    let x = move || {
        match foo {
            None => (),
            Some(yield) => (),
        }
    };
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc version: 1.81.0-nightly (5affbb171 2024-07-18)
platform: x86_64-unknown-linux-gnu
```

### Error output

```
error: expected identifier, found reserved keyword `yield`
 --> f94.rs:7:18
  |
7 |             Some(yield) => (),
  |                  ^^^^^ expected identifier, found reserved keyword
  |
help: escape `yield` to use it as an identifier
  |
7 |             Some(r#yield) => (),
  |                  ++

error[E0658]: `impl Trait` in type aliases is unstable
 --> f94.rs:2:14
  |
2 |     type T = impl Copy;
  |              ^^^^^^^^^
  |
  = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
  = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable
  = note: this compiler was built on 2024-07-18; consider upgrading it if it is out of date

warning: unused variable: `x`
 --> f94.rs:4:9
  |
4 |     let x = move || {
  |         ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at compiler/rustc_mir_build/src/build/matches/mod.rs:1819:44:
called `Option::unwrap()` on a `None` value
```

https://github.com/rust-lang/rust/blob/411fcb6b2df7337377626680ef5ec5d99b5eba23/compiler/rustc_mir_build/src/build/matches/mod.rs#L1814-L1815

<strong>Backtrace</strong> attached

[rustc-ice-2024-07-19T17_25_21-3933070.txt](https://github.com/user-attachments/files/16315227/rustc-ice-2024-07-19T17_25_21-3933070.txt)

**Comment by estebank** [comment] 2024-07-19 17:34
cc @Nadrieril

**Comment by matthiaskrgr** [comment] 2024-07-19 17:39
duplicate of https://github.com/rust-lang/rust/issues/119786

**Closed** 2024-07-19 17:42 UTC
Labels: I-ICE, T-compiler, A-mir, C-bug, needs-triage
