### ISSUE TITLE
Funny help message "help: consider adding a leading `b`: `bstringify!(foo)`"

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#48872] opened 2018-03-09 09:08 UTC
Reduced testcase:
```rust
fn foo() -> bool {
    b"".starts_with(stringify!(foo))
}
```

Compiler output:
```
error[E0308]: mismatched types
 --> src/main.rs:2:21
  |
2 |     b"".starts_with(stringify!(foo))
  |                     ^^^^^^^^^^^^^^^
  |                     |
  |                     expected slice, found str
  |                     help: consider adding a leading `b`: `bstringify!(foo)`
  |
  = note: expected type `&[u8]`
             found type `&'static str`
```

**Comment by zackmdavis** [comment] 2018-03-09 16:02
(duplicate of #48835 and #48364, I think)

**Comment by kennytm** [comment] 2018-03-09 16:29
Closing as duplicate of #48835. Thanks for the bug report anyway!

**Closed by kennytm** 2018-03-09 16:29 UTC
