### ISSUE TITLE
Consider moving std::error::Error to `alloc`

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#62502] opened 2019-07-08 19:54 UTC
Now that `alloc` is stable, this is a somewhat visible omission from `no_std` contexts.

In practice, it being in `std` means that library crates that would otherwise be `no_std` (+ `alloc`) compatible which expose some sort of error type have to either:
1. Skip implementing `std::error::Error` for their error type, giving up error ergonomics for users regardless of whether or not they care about no_std
2. Hide the implementation of `std::error::Error` behind a feature, which is awkward.
    - And if you already have `alloc` behind a feature, now you end up with separate `alloc` and `std` features (which is the option I took [in one of my crates](https://github.com/thomcc/rust-base16/tree/a5321823aa9361279d12ee460aa99ca1a4e62ddf#no_std-usage), and is mostly why I'm filing this) but is tedious, and makes your library have a larger configuration surface than feels necessary.
3. Ignore no_std completely (what most crates do and will probably continue to do).

Bummers, all of them.

If Error is moved to `alloc`, while not *ideal* <sup>[1]</sup>, it would make things easier for the relatively common case of library crates that could otherwise be `no_std` + `alloc`, but don't want to give up error handling ergonomics.

---

<b>[1]</b>: I think having `Error` in `core` makes more sense, but IIUC it can't: https://github.com/rust-lang/rust/pull/33149 (my read of this, which is probably wrong in some way, is that it's more or less because `Error::downcast` needs to be able to return a `Box<T>`)

As far as I know nothing prevents it from being in `alloc` (since Box is present in `alloc`), but I could easily be missing something important.

anyway thx for coming to my ted talk

**Comment by clarfon** [comment] 2019-07-08 21:13
I think that longer term offering it in `core` is best, but allowing it in `alloc` in the meantime is a good idea.

**Comment by Lokathor** [comment] 2019-07-09 01:59
@clarfon core doesn't have Box

**Comment by hellow554** [comment] 2019-07-09 07:33
> @clarfon core doesn't have Box

true, but Box is only used for `downcast`, so that could live in alloc and the rest maybe in core? :/ not sure how to do that though.

**Comment by clarfon** [comment] 2019-07-09 14:29
It would require changes to how the language works, yes. But it'd be doable long term.

**Comment by cbeck88** [comment] 2019-08-02 03:08
Hi, as a user I want to say that this would really help our projects, especially if it is adopted in `serde`, because it allows them to expose the same interface in `std` and `alloc` configurations

**Comment by taiki-e** [comment] 2019-08-30 08:55
Moving to liballoc should be fine.
https://github.com/rust-lang/rust/blob/c7d4df0fcfc3ed3ee98a430e451c6776e90d65ae/src/libstd/error.rs#L5-L14

**Comment by Mark-Simulacrum** [comment] 2019-12-22 01:45
Given Error::backtrace and Backtrace, it's pretty clear that doing this would need something akin to an RFC -- we need to decide how to expose Backtrace to no_std users: an opaque blob, always an empty backtrace, or something else?

Given that, closing.

**Comment by cbeck88** [comment] 2020-02-16 04:24
@Mark-Simulacrum it was suggested in https://github.com/rust-lang/rust/pull/64017 that it can be a zero-width type, presumably with no contents

**Comment by Mark-Simulacrum** [comment] 2020-02-16 13:08
It's possible that's the right decision. I don't think it answers all the questions. I would suggest opening a PR to this repository after implementing this; if you're interested in discussing how to do so I believe internals is the right place for that.

**Comment by cbeck88** [comment] 2020-02-17 00:36
@Mark-Simulacrum ok

I don't think I have bandwidth to do that right at this moment, but yeah i'm probably interested

If you think an RFC is the right way to go I'm also potentially interested in driving that process or participating in it, though I've never done that before

**Comment by tarcieri** [comment] 2020-02-26 17:06
Doesn't the `backtrace` crate support `no_std`?

https://github.com/rust-lang/backtrace-rs/blob/3804dac/src/lib.rs#L67

**Comment by shepmaster** [comment] 2020-02-26 17:59
> Doesn't the `backtrace` crate support `no_std`?

[I've been told](https://github.com/shepmaster/snafu/issues/85#issuecomment-516616498)

>  backtrace-rs could in theory be no_std and in fact std is an optional feature, although I suspect all current backends require std (maybe the goblin/addr2line backend doesn't ?)

**Comment by tarcieri** [comment] 2020-02-27 05:16
> I suspect all current backends require std (maybe the goblin/addr2line backend doesn't ?)

@shepmaster well, regardless of whether it's possible to capture a backtrace or not (that's something that can always be fixed in the future), it'd be nice to be able to use its `Backtrace` type in `no_std` + `alloc` environments, which would solve the aforementioned issue:

> we need to decide how to expose Backtrace to no_std users: an opaque blob, always an empty backtrace, or something else?

Unfortunately I just confirmed one problem: the `Backtrace` type is presently gated on the `std` feature, ostensibly because it uses `Vec`. So, it seems, `backtrace` also needs an `alloc` feature as well to be able to use `Vec` in these environments.

That said, it seems like with a little work it should be possible to support the `Backtrace` type in `no_std` + `alloc` environments.

**Comment by yaahc** [comment] 2021-05-24 23:36
reconsidering attempting this

related convo: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/error.20in.20core

**Comment by Enselic** [comment] 2023-12-17 12:40
Triage: Error was moved to core in https://github.com/rust-lang/rust/pull/99917 (🎉 ). Closing this as fixed.

**Closed by Enselic** 2023-12-17 12:40 UTC
Labels: T-libs-api

**Comment by daxpedda** [comment] 2023-12-17 14:22
See https://github.com/rust-lang/rust/issues/103765 for actually stabilizing the move.
