### ISSUE TITLE
Compiling rust-uinput takes almost 20 minutes

### ISSUE THREAD

**Issue by Theemuts** [rust-lang/rust#37074] opened 2016-10-10 18:11 UTC
Hi,

A few minutes ago I opened an issue on the rust-uinput repo, but @meh advised me to open one here. If I compile that library, it takes a significant amount of time which I haven't experienced while compiling before, potentially due to `custom_derive`. My computer has an i5 2550K, 8GB of ram, is running Ubuntu 16.04 and rustc 1.12.

**Comment by jonas-schievink** [comment] 2016-10-10 18:19
It indeed gets stuck inside expansion. Can also reproduce on nightly. I'm on 64-bit Arch Linux with 24GB RAM.

cc @jseyfried and @nrc probably

**Comment by durka** [comment] 2016-10-10 19:45
It's probably because of enums (with macros running over them) like [this](https://github.com/meh/rust-uinput/blob/35d74308e1584e6eda355fd60dfcbe90bef9e7c1/src/event/keyboard.rs#L55) and [this](https://github.com/meh/rust-uinput/blob/35d74308e1584e6eda355fd60dfcbe90bef9e7c1/src/event/keyboard.rs#L359).

**Comment by nrc** [comment] 2016-10-11 00:28
Would be good to narrow this down. It could be the custom derive for a big enum, or it could be the input to the `custom_derive` macro itself. I'd recommend using macros 1.1 custom derive in any case. But we should try and find out why this takes so long to compile.

cc @rust-lang/compiler

**Comment by durka** [comment] 2016-10-11 05:12
Note that `custom_derive!` (and `IterVariants!` which it calls here) are token munchers.

**Comment by Mark-Simulacrum** [comment] 2016-11-25 21:31
@Theemuts Can you test with a recent nightly and see if the performance improvements were as-expected? We can close this then, since I don't know if there's anything overly helpful to be gained from keeping this open (other than a "expansion can be slow" issue?).

**Comment by Mark-Simulacrum** [comment] 2017-05-16 15:42
So there's certainly more room for improvement here, as always, but I think we made some fairly large advances with #37701 and #37569, so I'm going to close. If @Theemuts still sees extremely long compile times then we can reopen, but I think they should be down to something at least a little more manageable.

**Comment by oberien** [comment] 2017-06-05 23:02
On rustc 1.19.0-nightly (0418fa9d3 2017-06-04) compilation of uinput still takes 5 minutes. I mean this is way better than 20 minutes, but could definitely take some more improvements.

**Comment by Mark-Simulacrum** [comment] 2017-06-05 23:05
Hm, 5 minutes does seem rather long. I'll reopen and do some local testing to see if I can find any more clear slow spots.

**Comment by Mark-Simulacrum** [comment] 2017-06-07 23:44
Just a quick update: I have a local (relatively -- libstd builds) untested branch that runs expansion on rust-uinput in ~12 seconds. I've never actually waited for expansion to complete on nightly, though, so not sure how much of an improvement this is yet. It's most certainly in the ballpark of 6 minutes, though.

**Comment by eddyb** [comment] 2017-06-08 07:54
@Mark-Simulacrum Whoa, what'd you do?!

**Comment by oberien** [comment] 2017-06-08 08:51
12 seconds is amazing! Does it only influence rust-uinput or is it working for all code expansions? How could it influence other libraries?

**Closed** 2017-06-10 09:11 UTC
Labels: A-macros
