### ISSUE TITLE
Miri check does not support `slice::align_to` method

### ISSUE THREAD

**Issue by earthengine** [rust-lang/rust#55886] opened 2018-11-12 04:51 UTC
The following

```rust
fn main() {
    let data:[u8;200] = [0;200];
    let (_,m,_) = unsafe { data[1..].align_to::<i32>() };
    println!("m.len()={}", m.len());
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=d5228295a3c12be6aa1d36eed2cd41d8)

prints `m.len()=49` in normal run, but `m.len()=0` in Miri check.

**Comment by RalfJung** [comment] 2018-11-12 08:07
This is not a bug, this is expected behavior. `align_to` is explicitly documented to give a best-effort answer:

> The method does a best effort to make the middle slice the greatest length possible for a given type and input slice, but only your algorithm's performance should depend on that, not its correctness.

The reason is that miri cannot know "how aligned" the allocation is. The `49` in a normal run can change from execution to execution, it depends on which base address got picked. miri does not pick a base address.

**Comment by oli-obk** [comment] 2018-11-12 17:13
Closing since it is working as intended as per the RFC https://github.com/rust-lang/rfcs/pull/2043 

If anything is unclear about the motivation or documentation, don't hesitate to open an issue about that or ask here

**Closed by oli-obk** 2018-11-12 17:13 UTC
