### ISSUE TITLE
ICE typechecking closure object with bound lifetime

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#63031] opened 2019-07-27 01:36 UTC
I don't think this was previously submitted as an issue, though it was mentioned on the [Rust Internals forum](https://users.rust-lang.org/t/generic-closure-arguments-and-hrtbs/13185/5).

```rust
trait Lf<'a> { type Type; }

struct F32;
impl<'a> Lf<'a> for F32 { type Type = f32; }

struct RefI32;
impl<'a> Lf<'a> for RefI32 { type Type = &'a i32; }

fn add_closure<T: for<'b> Lf<'b> + 'static>(v: &mut Vec<Box<for<'a> FnMut(<T as Lf<'a>>::Type)>>) {
    v.push(Box::new(move |_| {
    }));
}

fn main() {
    // bug? compiler can't seem to deduce <F32 as Lf<'a>>::Type == f32 nor <RefI32 as Lf<'a>>::Type == &'a i32
    let mut v1 = Vec::<Box<for<'a> FnMut(<F32 as Lf<'a>>::Type)>>::new();
    let mut v2 = Vec::<Box<for<'a> FnMut(<RefI32 as Lf<'a>>::Type)>>::new();
    add_closure::<F32>(&mut v1);
    add_closure::<RefI32>(&mut v2);
}
```

This crashes both on stable and latest nightly.

```
error: internal compiler error: src/librustc/traits/codegen/mod.rs:55: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@src/main.rs:10:21: 11:6] as std::ops::FnMut<(<F32 as Lf<'_>>::Type,)>>), Binder(<[closure@src/main.rs:10:21: 11:6] as std::ops::FnMut<(f32,)>>), Sorts(ExpectedFound { expected: f32, found: <F32 as Lf<'_>>::Type }))` selecting `Binder(<[closure@src/main.rs:10:21: 11:6] as std::ops::FnMut<(f32,)>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:646:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error
```

[**Playground**](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4e5f020fab2c606cbfb0a19d6c7f7b3a)

**Comment by nagisa** [comment] 2019-08-01 13:31
Appears to be failing all the way back to at least 1.10.0.

**Comment by nagisa** [comment] 2019-08-01 13:40
Since the issue is ancient, marking it as `P-medium`. It would still be great to fix this ICE, regardless.

**Comment by alexreg** [comment] 2019-08-01 14:59
@nagisa Indeed... I'm surprised it went without discovery this long. Well, I guess it's a tad obscure. I'm probably not the best person take this on, but hopefully someone else will.

**Comment by jackh726** [comment] 2021-08-29 13:08
Closing as duplicate of #62529

**Closed by jackh726** 2021-08-29 13:08 UTC
Labels: A-codegen, I-ICE, P-medium, A-closures, T-compiler, C-bug, glacier
