### ISSUE TITLE
failed to parse manifest Cargo.toml

### ISSUE THREAD

**Issue by NivedhithaNatarajan** [rust-lang/rust#57187] opened 2018-12-29 03:35 UTC
$ rustc --version
rustc 1.29.0 (aa3ca1994 2018-09-11)
$ cargo build
```
error: failed to parse manifest at `/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature

```

after adding cargo-features = ["edition"] to all cargo.toml files, and switching to nightly version
this is the error I'm getting at multiple places
**error[E0494]: cannot refer to the interior of another static, use a constant instead**
if i switch to rust 1.31
$cargo +1.31.1-x86_64-apple-darwin build
 i'am gettting this error at multiple places
**error[E0425]: cannot find value `id` in this scope**

For different versions, I'm getting different errors
what is the correct version I need to use?

**Comment by jonas-schievink** [comment] 2019-01-26 23:06
Please refer to https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html

**Comment by jonas-schievink** [comment] 2019-04-21 22:23
Closing, since this is explained in the edition guide. If you still have trouble, please post on stackoverflow or the user forum at https://users.rust-lang.org/, and include the code needed to reproduce this issue.

**Closed by jonas-schievink** 2019-04-21 22:23 UTC
