### ISSUE TITLE
Self as default type isnt typechecked

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#61631] opened 2019-06-07 18:48 UTC
The following code compiles:
```Rust
struct B<P: Sized = [Self]>(P);
```
but shouldn't, because `[Self]` is NOT Sized.

If we change `[Self]` with a `[u8]`, like this:
```Rust
struct B<P: Sized = [u8]>(P);
```
it fails to compile, because `[u8]` isnt sized.

Also note that if we would write `impl B {}` in the case of P being of default type `[Self]`, we get an ICE:

Related to https://github.com/rust-lang/rust/issues/59956#issuecomment-482946649

**Comment by DutchGhost** [comment] 2019-06-07 19:10
Using godbolt, this slipped in with 1.32, where `Self` is allowed in type defs: https://github.com/rust-lang/rust/pull/56366/

**Comment by Centril** [comment] 2019-06-07 19:54
cc @alexreg

**Comment by alexreg** [comment] 2019-06-07 23:45
Thanks for the report.

@Centril I think the straightforward solution is to ban mentions of `Self` as type parameter defaults. After all, if you replace `Self` with `B` in the above example, you get:

```
error[E0391]: cycle detected when processing `B::P`
```

Sound fair?

**Comment by Centril** [comment] 2019-06-07 23:56
That's a breaking change; consider e.g.:

```rust
enum L<P = Self> {
    N,
    C(u8, Box<P>),
}

fn main() {
    L::C(0, Box::new(L::<()>::N));
}
```

I think the right thing to do is to account for `Self` when checking the bounds of a type definition.

**Comment by alexreg** [comment] 2019-06-07 23:57
Oh, I didn't realise `Self` was previously permitted...

**Comment by Centril** [comment] 2019-06-08 00:09
This appears to be an instance of a wider problem:

```rust
trait Foo<Bar: Sized = [Self]> {}
```

Has compiled, but shouldn't have, since 1.0.

cc @nikomatsakis

**Comment by alexreg** [comment] 2019-06-08 00:15
Thoughts after discussing this with @Centril: maybe we should be allowing this after all (or have no other choice due to the way the type system works), and should instead put in checks on things like `imp B { ... }` (with no binding for `P`) and possibly elsewhere.

**Comment by pnkfelix** [comment] 2019-06-13 13:54
triage: P-high. Leaving nominated for discussion at rustc meeting. Leaving unassigned for now.

**Comment by DutchGhost** [comment] 2019-06-17 14:04
I did some more playing around, and it's not just about the `Self` type:

The following code *compiles*, but shouldn't:
```Rust
use core::marker::PhantomData;

struct Bug<F: Fn(&u8) = fn() -> &'static u8> {
    F: P,
}
```

We only get a type error when we write:
```Rust
impl Bug {}
```

or
```Rust
let _: Bug;
```

**Comment by pnkfelix** [comment] 2019-06-20 19:10
ah, so is part of the issue that the type expression used as the default for the type parameter is not checked to actually meet its given trait bounds at its definition site. We wait until a usage site to do the checkk.

**Comment by jonas-schievink** [comment] 2019-06-20 19:20
That only seems to happen in *some* cases, eg. this example from the OP fails to compile despite being unused:

```rust
struct B<P: Sized = [u8]>(P);
```

    error[E0277]: the size for values of type `[u8]` cannot be known at compilation time

(the `: Sized` is implicit and can be removed, same effect)

The same happens here, ruling out a special-cased sizedness check:

```rust
struct B<P: Copy = String>(&'static P);
```

    error[E0277]: the trait bound `std::string::String: std::marker::Copy` is not satisfied

But for some reason @DutchGhost's example above is accepted, despite being clearly wrong:

```rust
struct Bug<F: Fn(&u8) = fn() -> &'static u8> {
    f: F,
}
```

**Comment by DutchGhost** [comment] 2019-06-20 19:45
@jonas-schievink , I think it only works for:
- Self
- References

Here I build an example playground to experiment:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ed387b9d7b2dcf055aaa7cb612cd041b

```Rust
use core::marker::{
    PhantomData,
    PhantomPinned,
};

// !Send + !Sync + !Pinned.
// lacks Copy + Clone
struct NoAutoTrait<T> {
    _mark: PhantomData<T>,
    nosend: PhantomData<*mut ()>,
    pinned: PhantomPinned,
}

struct Bug<'a, F: Copy + Send + Sync + Unpin = NoAutoTrait<&'a String>> {
    mark: PhantomData<&'a F>
}
```

However, if I changed `NoAutoTrait<&'a String>` to `NoAutoTrait<&'static String>`, I get compile errors.
Same goes for `&'a mut` to `&'static mut`.

**Comment by alexreg** [comment] 2019-06-20 21:30
> We wait until a usage site to do the checkk.

Yes, exactly. And I *think* the way that type-checking is implemented, you'll always end up in cycles if you try to do it at definition-site, since you don't have a concrete type yet... which is why @Centril and I thought that maybe we should allow this and solve the use-site issues (e.g., the situation with impls).

**Comment by pnkfelix** [comment] 2019-06-27 14:28
Discussed at T-compiler meeting. Sounds pretty thorny.

@eddyb put forward the idea that we might at least try to emit *warnings* for these cases even if we cannot reliably do hard errors for them.

In any case, needs further investigation before we'd commit to saying that we do not need to do it at the definition site.

Assigning to @eddyb and myself. But also Cc'ing @nikomatsakis in the hopes that they will also chime in.

**Comment by eddyb** [comment] 2019-06-27 16:04
> even if we cannot reliably do hard errors for them

To be clear, I was thinking of backwards-compatibility concerns, that would imply we might never be able to make something into a proper hard error, *even if* we have a reliable way to detect it.
<hr/>

But I missed the fact that this is specifically about `Self` in a default of a type parameter.

So here's what I think of `Self` in type parameter default:
We have logic in the compiler to forbid a default using an earlier parameter, or the one it's a default of:
https://github.com/rust-lang/rust/blob/a6b5d229c1ddd7659af82109377aa8a3568f68a1/src/librustc_resolve/lib.rs#L895-L944

Previous comments have mentioned this behavior, but I think it implies something stronger:
`Self`, by definition, is an alias for `TypeName<A, B, C, ...>`, so we should be denying `Self` in places where we deny any of the parameters.
<hr/>

But note that this applies to `struct`, `enum`, `union` and `impl`. `Self` in `trait` is a bit different, as it's effectively "the first parameter", so other parameters referring to it is fine - there appears to be a different bug @Centril spotted in https://github.com/rust-lang/rust/issues/61631#issuecomment-500074614.

**Comment by alexreg** [comment] 2019-06-27 22:59
> But note that this applies to `struct`, `enum`, `union` and `impl`. `Self` in `trait` is a bit different, as it's effectively "the first parameter", so other parameters referring to it is fine - there appears to be a different bug @Centril spotted in [#61631 (comment)](https://github.com/rust-lang/rust/issues/61631#issuecomment-500074614).

Well that's the whole point, surely? `Self` *is* the implicit first parameter, so its usage should be banned in this example per the rule "forbid a default using an earlier parameter".

**Comment by eddyb** [comment] 2019-07-01 09:41
@alexreg Oops, that was meant to say "using a *later* parameter" (that is, we *only* allow earlier ones).

**Comment by alexreg** [comment] 2019-07-01 16:58
@eddyb Ah, that makes sense then... in any case, maybe it makes sense to consider the `Self` type as an implicit final type parameter for this purpose?

**Comment by nikomatsakis** [comment] 2019-07-11 18:35
Clarification question:

When we last discussed this in the @rust-lang/lang meeting, the conclusion was that this was roughly the expected behavior -- except for the bug around `Self`. This is roughly what @eddyb outlined in [this comment](https://github.com/rust-lang/rust/issues/61631#issuecomment-506409368). This is still the case, right?

In which case, what we need to do is fix the bug around `Self` specifically?

**Comment by alexreg** [comment] 2019-07-11 20:49
@nikomatsakis What exactly are you referring to as "expected behaviour" here? That using later type params in defaults for earlier ones is disallowed?

For sure, there's a bug with `Self` though, yep...

**Comment by alexreg** [comment] 2019-07-11 20:50
@eddyb left some general guidance for me on Discord, which may be enough for me to tackle this along with his above comment:

> I think the problem is this code doesn't know about the Self in scope https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/lib.rs#L907-L926
hmmm
so the problem is entirely localized within  https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/lib.rs#L2492-L2502
walk_item ends up calling visit_generics

**Comment by DutchGhost** [comment] 2019-07-11 21:41
Discussed on discord with @alexreg I would make this comment to raise some awareness.

As I showed in my comment here: https://github.com/rust-lang/rust/issues/61631#issuecomment-504157673 , this issue isn't solely about the `Self` being able to compile when it shouldn't, but also about reference types and wrapped references showing the exact same wrong behaviour.

I'd argue the latter should get a fix as well.
Imagine I make a library containing the code I wrote in that comment. For me it compiles, but anyone using it *could* get compile errors whenever they use my type with the defaults, which seems wrong to me.

cc @nikomatsakis @alexreg

**Comment by nikomatsakis** [comment] 2019-07-11 22:21
Here is a [summary comment from the last discussion we had on this topic](https://github.com/rust-lang/rust/pull/46785#issuecomment-363219662). [This comment](https://github.com/rust-lang/rust/pull/46785#issuecomment-364255148) then covers the lang-team reasoning about the rules and some specific examples. The TL;DR is that, while it is true that you can get errors at use-sites that could've been detected at the caller site, it's also possible to create constructs that are useful (an example is in the comment). Moreover, we are reluctant to break existing code in general, so becoming more strict is always a trade-off.

In fact, the surprising behavior that you are pointing out, where changing from `'a` to `'static` starts to generate errors, is a **result** of the compromise we struck on our last foray here. In particular, we only check **if the default has no generic parameters appearing in it**. In this case, `&'static str` does not, so basically *any* use that leaves the default unspecified is known to be in error. In contrast, `&'a str` does have a parameter that is not yet known (`'a`), so we don't check it for consistency.

**Comment by nikomatsakis** [comment] 2019-07-11 22:33
I opened https://github.com/rust-lang-nursery/reference/issues/636 to document the intended behavior here -- this does not include the bugs around `Self`, though.

**Comment by alexreg** [comment] 2019-09-07 01:00
So... is someone tackling this issue?

**Comment by pnkfelix** [comment] 2019-09-27 09:18
I think I have a patch for this. PR forthcoming.

**Comment by pnkfelix** [comment] 2019-09-27 09:26
@eddyb [wrote](https://github.com/rust-lang/rust/issues/61631#issuecomment-506409368): 

> But note that this applies to `struct`, `enum`, `union` and `impl`.

Hey @eddyb, what were you referring to when you said `impl` here?

An `impl<generics ...> Trait for Type` (or `impl Type`) isn't an ADT definition, so I don't know where it would fall in your characterization of `Self` being an implicit type parameter (either the first one, in the case of `trait`, or the last one, in the case of ADT items).

And also, that `generics ...` list isn't allowed to have type parameter defaults, according to #36887

 I would imagine that the `generics ...` in the `impl` definition *could* have defaults that refer to `Self`, no?

**Closed** 2019-10-04 03:35 UTC
Labels: C-bug, E-needs-mentor, P-high, T-compiler, regression-from-stable-to-stable

**Comment by eddyb** [comment] 2019-10-04 10:41
> An `impl<generics ...> Trait for Type` (or `impl Type`) isn't an ADT definition, so I don't know where it would fall in your characterization of `Self` being an implicit type parameter (either the first one, in the case of `trait`, or the last one, in the case of ADT items).

I was talking about `Self` as an "alias" for `Adt<generics...>` *or* `Type` (in an `impl`), *not* an implicit parameter.

The reason we should disallow it in ADTs' type parameter defaults is because it contains *all* the parameters by necessity and expanding it by hand would always produce an error anyway.

**Comment by pnkfelix** [comment] 2019-10-07 08:19
> I was talking about `Self` as an "alias" for `Adt<generics...>` _or_ `Type` (in an `impl`), _not_ an implicit parameter.

Ah okay. I was adopting a model based on @alexreg's comments on this issue, and I overlooked the [point you made](https://github.com/rust-lang/rust/issues/61631#issuecomment-506409368) about what `Self` is "by definition."
