### ISSUE TITLE
Technically unsafe behavior in safe rust using #![no_main]

### ISSUE THREAD

**Issue by CensoredUsername** [rust-lang/rust#47685] opened 2018-01-23 21:00 UTC
Using `#![no_main]`, and a `#[no_mange] pub static main` array the linker will assume that the main array is actually the main function and execute whatever is in there. Outside of a warning for nonstandard naming this compiles fine on stable and nightly on both debug and release mode.

[Example](https://play.rust-lang.org/?gist=9b2ab7edf4ea84f3bb9249facc0a57f9&version=stable)

This example will print the text `Main is usually a function\n` on x64 linux and probably crash violently on anything else.

It's rather hard to trigger this behavior without trying, but it should probably not compile without errors. Maybe add a check for `#![no_main]` crates that whatever's declared as `#[no_mangle] main` is actually a function with the correct signature.

## Meta

The issue exists on `rustc 1.25.0-nightly`, `rustc 1.23.0` and anything in between.

**Comment by retep998** [comment] 2018-01-24 06:12
`#[no_mangle]` is dangerous and unsafe in general.

https://github.com/rust-lang/rust/issues/47449
https://github.com/rust-lang/rust/issues/28179

**Comment by CensoredUsername** [comment] 2018-01-24 12:05
Whoops, missed those while searching (only searched for no_main). 

It should be noted though that the proposed solution in the other issues (errors on duplicate symbols) would not work in this case as `#![no_main]` avoids emitting the main symbol in general.

**Comment by CensoredUsername** [comment] 2018-05-03 19:44
The correct place for it to be would be `.rodata` . But it used to be quite normal to map constants into the `.text` section. Mapping it into `.data` would be less efficient as `.data` has to be copied into the process memory space while `.text` can just be directly mapped into the process space.

**Comment by Laaas** [comment] 2018-05-04 10:57
I don't think this should result in a compilation error, since it might be useful occasionally. However I do think there should be a lint against it, or perhaps some kind of `unsafe {}` required?

**Comment by steveklabnik** [comment] 2020-03-02 23:20
Triage: no change

**Comment by jonas-schievink** [comment] 2020-04-20 22:42
This is basically a duplicate of https://github.com/rust-lang/rust/issues/28179, so closing in favor of that

**Closed by jonas-schievink** 2020-04-20 22:42 UTC
Labels: C-bug, T-compiler
