### ISSUE TITLE
ICE on all current Rust channels

### ISSUE THREAD

**Issue by vitalyd** [rust-lang/rust#42950] opened 2017-06-28 11:50 UTC
While playing around with the scenario mentioned in https://users.rust-lang.org/t/intoiterator-and-lifetimes/11574, I hit an ICE with the following message:

> error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<[closure@<anon>:70:23: 70:29] as std::ops::FnOnce<(Record<'_>,)>>)),depth=0),OutputTypeParameterMismatch(Binder(<[closure@<anon>:70:23: 70:29] as std::ops::FnOnce<(<&DataSet as std::iter::IntoIterator>::Item,)>>), Binder(<[closure@<anon>:70:23: 70:29] as std::ops::FnOnce<(Record<'_>,)>>), Sorts(ExpectedFound { expected: Record<'_>, found: <&DataSet as std::iter::IntoIterator>::Item })))]` resolving bounds after type-checking
> 
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
> 
> note: rustc 1.20.0-nightly (f590a44ce 2017-06-27) running on x86_64-unknown-linux-gnu
> 
> thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:426
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
This also happens on the current stable (rustc 1.18.0 (03fc9d622 2017-06-06)) channel as well.  [Here](https://is.gd/o4Vq9I)'s a repro on the playground.

**Comment by est31** [comment] 2017-06-28 15:50
[Minified](https://is.gd/EUpFa6)

**Comment by est31** [comment] 2017-06-28 16:26
Even more minified:

```rust
struct D;

trait Tr {
    type It;
    fn foo(self) -> Option<Self::It>;
}

impl<'a> Tr for &'a D {
    type It = ();
    fn foo(self) -> Option<()> { None }
}

fn run<F>(f: F)
    where for<'a> &'a D: Tr,
          F: Fn(<&D as Tr>::It),
{
    let d = &D;
    while let Some(i) = d.foo() {
        f(i);
    }
}

fn main() {
    run(|_| {});
}
```

**Comment by vitalyd** [comment] 2017-06-30 13:16
@arielb1 / @est31 , just wondering - should the formulation that I tried work? Or would it have failed compilation anyway if the ICE didn't come in the way? Thanks

**Comment by arielb1** [comment] 2017-07-02 09:18
Looks like a duplicate of #33364.

**Comment by steveklabnik** [comment] 2018-09-24 18:37
Triage: this still ICEs

**Comment by estebank** [comment] 2019-01-30 23:23
CC #29997.

**Comment by pnkfelix** [comment] 2019-07-10 10:20
closing as duplicate of #62529, which is where I will try to track future instances of this field of ICE.

**Closed by pnkfelix** 2019-07-10 10:20 UTC
Labels: C-bug, I-ICE
