### ISSUE TITLE
DOS Line Endings in install.sh on some rust-std nightlies

### ISSUE THREAD

**Issue by apmorton** [rust-lang/rust#62276] opened 2019-07-01 17:28 UTC
Since the change from travis to azure pipelines some of the rust-std archives have DOS line endings in their `install.sh` script, which results in errors like the following when trying to execute:
```
# ./install.sh
bash: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory
```

Running `dos2unix install.sh` works around the issue for now.

Not all archives have this issue. Specifically http://static.rust-lang.org/dist/rust-std-nightly-i686-pc-windows-gnu.tar.gz does. Possibly others as well, but our install process fails after the first error, so I am not sure.

See mattgodbolt/compiler-explorer-image#230 and mattgodbolt/compiler-explorer-image@4df231f265d7a083f1752f7bd69b6f212a740fd9

**Comment by pietroalbini** [comment] 2019-07-02 17:51
Thanks for reporting this!

A tentative fix for this landed in https://github.com/rust-lang/rust/pull/62279, hopefully tomorrow's nightlies will be fixed.

**Comment by maroux** [comment] 2019-07-08 17:57
Still happening on `1.38.0-nightly (6e310f2ab 2019-07-07)` :/

**Comment by pietroalbini** [comment] 2019-07-08 18:14
Oh, this is concerning, we'll need to look into it a bit more. Thanks for the update.

@rustbot modify labels: regression-from-stable-to-beta -regression-from-stable-to-nightly

**Comment by maroux** [comment] 2019-07-08 20:16
May have been [rust-installer](https://github.com/rust-lang/rust-installer/issues/95) actually .. Double checking.

**Comment by mati865** [comment] 2019-07-08 20:41
`rust-src-nightly.tar.gz` is also affected, does that mean src is now generated from Windows or this is broken even more than it seems?

**Comment by pietroalbini** [comment] 2019-07-08 22:12
This is caused by the Azure migration, as it started happening right after we switched nightlies production to it. The initial hypothesis was that git's `core.autocrlf` on Windows was the culprit, but that landed days ago so we need to look deeper :/

**Comment by pietroalbini** [comment] 2019-07-08 22:15
> rust-src-nightly.tar.gz is also affected, does that mean src is now generated from Windows or this is broken even more than it seems?

The source tarball is generated by all the dist builders and uploaded each time, so the last dist builder to finish will be the one producing the final tarball. I think we see the error there just because our slower builders are all Windows at the moment.

**Comment by pietroalbini** [comment] 2019-07-08 22:28
Assigning myself to investigate in the next few days.

**Comment by lzutao** [comment] 2019-07-09 17:29
Relevant:
* https://help.github.com/en/articles/configuring-git-to-handle-line-endings
* https://git-scm.com/docs/git-config
* https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Comment by pietroalbini** [comment] 2019-07-11 11:35
The fix should've landed in today's nightly. Thanks everyone for reporting this!

**Comment by EricRahm** [comment] 2019-07-12 00:15
@pietroalbini Just a note, you might want to spin up a beta build as well. `rust-src-beta` was affected by this as well.

**Comment by pietroalbini** [comment] 2019-07-12 05:51
@EricRahm yes, beta is still not fixed. The fix was nominated for beta backport though, so once the team approves we will backport it to the beta branch.

**Comment by pietroalbini** [comment] 2019-07-23 17:08
We backported the change!

**Closed** 2019-07-23 17:07 UTC
Labels: C-bug, P-high, T-infra, regression-from-stable-to-beta
