### ISSUE TITLE
ICE when const is used as `X;` in nested function

### ISSUE THREAD

**Issue by Peach1** [rust-lang/rust#34107] opened 2016-06-06 01:34 UTC
The following crashes the Rust compiler on nightly:

```rust
const X: i32 = 5;

fn main() {
    fn q() {
        X;
    }
}
```

"thread 'rustc' panicked at 'assertion failed: type_is_zero_size(bcx.ccx(), bcx.tcx().node_id_to_type(expr.id))', ../src/librustc_trans/expr.rs:158"

**Comment by niconii** [comment] 2016-06-07 04:39
Even worse, this produces the same result:
```rust
const X: i32 = 5;

fn main() {
    X;
}
```

**Comment by c3st7n** [comment] 2016-06-14 20:54
Dupe of https://github.com/rust-lang/rust/issues/34008?

**Comment by niconii** [comment] 2016-06-15 00:54
Looks like that is indeed the case, so I'll close in favor of that one.

**Closed by niconii** 2016-06-15 00:54 UTC
Labels: I-ICE
