### ISSUE TITLE
Failed to apply `type` on enum

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang/rust#28556] opened 2015-09-21 03:13 UTC
```rust
mod test_mod {
    enum A {
        Foo,
    }
}

type Alias = test_mod::A;

let _v = Alias::Foo; // Compile error
```

**Comment by christopherdumas** [comment] 2015-09-21 21:41
I changed your code to this so it would compile at all:
```rust
mod test_mod {
   enum A {
        Foo,
    }
}

type Alias = test_mod::A;

fn main () {
    let _v = Alias::Foo; // Compile error
}
``` 
(You needed a main function)

It seems like the alias is doing fine, but it can't find Foo. Odd.

**Comment by christopherdumas** [comment] 2015-09-21 21:42
I'd like to work on this, but I'm not sure where in the codebase to look. Can someone tell me?

**Comment by zonyitoo** [comment] 2015-09-22 01:44
@christopherdumas Hmm, I just omitted the main function. The error is just what you said, it can't find Foo.

**Comment by jonas-schievink** [comment] 2015-09-22 11:00
The type alias itself is correctly rejected if you remove the `let` binding, but with the let binding you get ``no associated item named `Foo` found for type `test_mod::A` in the current scope``. Looks like the order in which these are checked should be reversed (if this is even possible).

**Comment by nodakai** [comment] 2016-02-10 21:55
Possible duplicate of #26264

**Comment by alexcrichton** [comment] 2016-03-07 07:08
Ah yes, looks to be a dupe of https://github.com/rust-lang/rust/issues/26264 indeed!

**Closed by alexcrichton** 2016-03-07 07:08 UTC
Labels: A-resolve
