### ISSUE TITLE
rustdoc does not document Deref impls more than one level deep

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#53038] opened 2018-08-03 20:58 UTC
```rust
use std::ops::Deref;

pub struct Base;

impl Base {
    pub fn asdf(&self) {}
}

pub struct LevelOne {
    pub base: Base,
}

impl Deref for LevelOne {
    type Target = Base;

    fn deref(&self) -> &Base {
        &self.base
    }
}

impl LevelOne {
    pub fn qwop(&self) {}
}

pub struct LevelTwo {
    pub base: LevelOne,
}

impl Deref for LevelTwo {
    type Target = LevelOne;

    fn deref(&self) -> &LevelOne {
        &self.base
    }
}

impl LevelTwo {
    pub fn custom() {}
}
```

In this example, `LevelTwo` derefs to `LevelOne`, which derefs to `Base`. However in the docs, only the methods from `LevelOne` are shown. We should recursively look for Deref impls on items we're collecting impls for via Deref.

**Comment by aldanor** [comment] 2018-11-19 00:47
Just ran into this as well - a bit annoying, especially if `Deref` is used aggressively through the codebase, e.g. if there are multiple newtype layers. Are there any plans for this to be fixed?

**Comment by aldanor** [comment] 2018-11-19 00:50
Ok, apparently there's #26207 which has been open for over 3 years with no changes...

**Comment by jyn514** [comment] 2021-01-03 15:55
Duplicate of https://github.com/rust-lang/rust/issues/26207

**Closed by jyn514** 2021-01-03 15:55 UTC
Labels: C-bug, T-rustdoc
