### ISSUE TITLE
Pre-emptive assumption of inequality while optimizations make equality. 

### ISSUE THREAD

**Issue by OptimisticPeach** [rust-lang/rust#79759] opened 2020-12-06 05:37 UTC
I tried this code:

```rust
fn compare(a: fn(usize) -> u32, b: fn(u64) -> u32) {
    if a as usize == b as usize {
        println!("a == b: {} & {}", a as usize, b as usize);
    } else {
        println!("a != b: {} & {}", a as usize, b as usize);
    }
}

fn foo<T>(_: T) -> u32 {
    0
}

fn main() {
    compare(foo::<usize>, foo::<u64>);
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=86e350485394194b0a1f647fb2f2644b)

I expected to see this happen: 

Either it would say `a == b` and provide equal addresses, or print `a != b` and provide different addresses.

Instead, this happened: 

The playground prints this on December the 6th 2020:
```
a != b: 94588183998880 & 94588183998880
```

### Meta
This bug also seems to occur on the beta channel available on the playground and the nightly available there too.

**Comment by sfackler** [comment] 2020-12-06 12:22
Duplicate of #54685.

**Closed by sfackler** 2020-12-06 12:22 UTC
Labels: C-bug
