### ISSUE TITLE
Lifetimes not inferred when using `Self` constructor instead of named one

### ISSUE THREAD

**Issue by tomkarw** [rust-lang/rust#102494] opened 2022-09-29 23:57 UTC
### I tried this code:

```rust
struct A<'a> {
    x: &'a str,
}

impl<'a> A<'a> {
    pub fn new<'b>(x: &'b str) -> A<'b> {
        Self { x }
    }
}
```

Link to playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c11bc82b8e33841719b8e1fb765d0529.

### I expected to see this happen: 
The code to compile, the same way this snippet compiles (notice that only `Self -> A` changed)
```rust
struct A<'a> {
    x: &'a str,
}

impl<'a> A<'a> {
    pub fn new<'b>(x: &'b str) -> A<'b> {
        A { x }
    }
}

```

### Instead, this happened:
```
error: lifetime may not live long enough
 --> src/lib.rs:7:9
  |
5 | impl<'a> A<'a> {
  |      -- lifetime `'a` defined here
6 |     pub fn new<'b>(x: &'b str) -> A<'b> {
  |                -- lifetime `'b` defined here
7 |         Self { x }
  |         ^^^^^^^^^^ associated function was supposed to return data with lifetime `'b` but it is returning data with lifetime `'a`
  |
  = help: consider adding the following bound: `'a: 'b`

error: lifetime may not live long enough
 --> src/lib.rs:7:16
  |
5 | impl<'a> A<'a> {
  |      -- lifetime `'a` defined here
6 |     pub fn new<'b>(x: &'b str) -> A<'b> {
  |                -- lifetime `'b` defined here
7 |         Self { x }
  |                ^ this usage requires that `'b` must outlive `'a`
  |
  = help: consider adding the following bound: `'b: 'a`

help: `'a` and `'b` must be the same: replace one with the other
```

The actual fix is to unify the lifetimes, but the fact that changing the constructor from `Self` to named fixed the issue is confusing and unexpected. Seems like an edge-case during compiler lifetime resolution.

Real world occurrence: https://github.com/durch/rust-s3/pull/299/commits/a6adbf2b286e7d92106b31d65b9c7fb742b95645 (fails before this commit, but works after the `Self -> HyperRequest` change).

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```
I see same behavior on `rustc 1.65.0-beta.2 (e5da98475 2022-09-24)` and `rustc 1.66.0-nightly (98ad6a551 2022-09-17)`.

</p>
</details>

**Comment by compiler-errors** [comment] 2022-09-30 01:45
This is not a bug. The identifier `Self`, unlike `A`, is not a type constructor -- it's a single type in the scope of the `impl`. So when one writes `Self` within that `impl`, it _always_ means `A<'a>`, and never `A<'_>`.

**Comment by tomkarw** [comment] 2022-09-30 23:17
Got it. Two questions then:
- Why is `Self` alias for `A<'a>` and not the more relaxed `A<'_>`? 
- Could we at least make a better compiler message, that basically notices this specific case and suggest the proper change?
Something like:
```text
`Self` is an alias for `A<'a>` in this context, try using the type constructor `A<'_>` explicitly
```

**Comment by compiler-errors** [comment] 2022-10-01 20:32
> Why is Self alias for `A<'a>` and not the more relaxed `A<'_>`?

because `Self` refers to _exactly_ the type that's in the `impl` block's header, i.e. `A<'a>`. It does no processing of that type, just exactly refers to it.

> Could we at least make a better compiler message, that basically notices this specific case and suggest the proper change?

I think @aliemjay was working on a PR for this.

**Comment by aliemjay** [comment] 2022-10-09 14:06
The diagnostic issue is tracked in #101393, so this can be closed as a duplicate.

**Closed** 2022-10-09 21:57 UTC
Labels: C-bug
