### ISSUE TITLE
The current library uses procedural macros and does not recompile the procedural macro code for each compilation

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#86466] opened 2021-06-19 08:44 UTC
The current library uses procedure macros and does not recompile the procedure macro code for each compilation。

How do you get the current library to rebuild the red code process every time it compiles?

os：windows10

**Comment by fee1-dead** [comment] 2021-06-21 04:27
Can you elaborate? What are you trying to achieve, and what is the issue? 

If possible, please attach a Minimal, Complete and Verifiable Example (mcve).

**Comment by fmease** [comment] 2024-01-25 13:53
It's true that proc macros don't get rebuilt on each recompilation since that would be highly detrimental to compile times, impractical and would render incremental compilation practically useless once the dependency graph contains at least one proc macro crate (which is very likely).

I don't actually know what the rest of the ecosystem does (e.g., crates that fetch database schemas from a live database and translate them to Rust data types), how they trigger recompilation. Maybe via `build.rs` that `touch`'es `my_proc_macro/src/lib.rs` if the modtime of some database files changes?

**Comment by fmease** [comment] 2024-01-25 13:54
Note that there are some ongoing discussions about *tracked* (that's the keyword) file & environment variable access.

**Comment by fmease** [comment] 2024-01-25 13:56
Closing as won't fix / works as intended / there're already other GitHub issues tracking this kinda stuff.

**Closed by fmease** 2024-01-25 13:56 UTC
Labels: T-compiler, S-waiting-on-author, C-bug, A-proc-macros, S-needs-repro
