### ISSUE TITLE
cargo test no suppress of stdout for multi thread case

### ISSUE THREAD

**Issue by davemilter** [rust-lang/rust#56253] opened 2018-11-26 14:54 UTC
**Problem**

If I execute the below testcases with cargo test, the output of one_thread_test will be suppressed as stated in the documentation.

However the output from multi_thread_test will appear on stdout. 

```Rust
#[test]
fn one_thread_test() {
    println!("A");
    println!("B");
}

#[test]
fn multi_thread_test() {
    use std::thread;

    let mut threads = vec![];
    for _ in 0..5 {
        let t = thread::spawn(move || {
            println!("from thread");
        });
        threads.push(t);
    }
    for thread in threads {
        thread.join().unwrap();
    }
}
```
**Steps**

1. Run `cargo test`

Output of `cargo version`:

cargo 1.30.0 (a1a4ad372 2018-11-02)
rustc 1.30.1 (1433507eb 2018-11-07)
Linux/amd64

Link to SO: https://stackoverflow.com/questions/53480972/how-do-i-suppress-output-from-multiple-threads-when-running-cargo-test

**Comment by alexcrichton** [comment] 2018-11-26 20:05
Thanks for the report! I've transferred this issue to rust-lang/rust because it's a libtest issue, not a Cargo issue

**Comment by d-e-s-o** [comment] 2019-06-23 19:32
I agree, this issue is very annoying. Virtually all output emitted by tests using a runtime such as `tokio`'s emit visible output now.

**Comment by saethlin** [comment] 2022-07-30 17:05
Doesn't reproduce anymore on Rust 1.62.1.

**Closed** 2022-07-30 17:14 UTC
Labels: A-libtest
