### ISSUE TITLE
Inconsistent "attributes on expressions are experimental" error

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#59144] opened 2019-03-12 21:17 UTC
Given [the following code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4f5147bf9cc2e3a12cdcaf37623fc66c):

```rust
fn main() {
    #[allow(unused)]
    let mut x = 1;
    
    #[allow(unused)]
    x = 1;
}
```

There's an error generated about the `x = 1;` line, but not the `let mut x = 1;` line. I would expect that either a) neither of these are errors (since they're both statements, not expressions) or, b) both of these are errors.

(cc @cramertj )

**Comment by ehuss** [comment] 2019-03-12 22:10
I suspect the attribute is binding tightly to the place expression, instead of the entire statement. Attributes on statements are stable, but attributes on expressions are limited. This is partially documented here: https://doc.rust-lang.org/nightly/reference/expressions.html#expression-attributes.  I'm curious if that precedence is intended. It makes sense to me, but I see how it is confusing.  A work around is to wrap the assignment expression in {} or ().

**Comment by Centril** [comment] 2019-03-13 18:35
cc https://github.com/rust-lang/rust/issues/15701

**Comment by ehuss** [comment] 2019-03-13 18:39
Oh, I didn't see that the RFC specifies "Attributes bind tighter than any operator", so it is intended.

**Comment by Enselic** [comment] 2023-11-24 15:16
> so it is intended.

Triage: Closing as works as designed.

**Closed by Enselic** 2023-11-24 15:16 UTC
Labels: A-attributes, A-stability
