### ISSUE TITLE
Weird unreleased memory issue when reading from a file

### ISSUE THREAD

**Issue by MoSal** [rust-lang/rust#60114] opened 2019-04-19 15:42 UTC
# Test files

```
dd if=/dev/urandom of=/tmp/31M bs=1M count=31
dd if=/dev/urandom of=/tmp/32M bs=1M count=32

```

# Compiler
```
rustc 1.36.0-nightly (5d20ff4d2 2019-04-18)
cargo 1.36.0-nightly (b6581d383 2019-04-16)
```

# Code

## `bad.rs`
``` rust
use std::error::Error;
use std::thread;
use std::time::Duration;

use std::fs::File;
use std::io::Read;

fn from_file(file_path: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut f = File::open(file_path)?;
    // Emitating fs::read()
    let size = f.metadata().map(|m| m.len() as usize + 1).unwrap_or(0);
    let mut bytes = Vec::with_capacity(size);
    f.read_to_end(&mut bytes)?;
    Ok(bytes)
}

fn main() {
    let file_path = std::env::args().nth(1).expect("No file path arg passed");
    for i in 1..=8 {
        // Running process should be occupying almost the same small amount of memory here, no?
        eprintln!("sleeping {}", i);
        thread::sleep(Duration::new(3, 0));
        eprintln!("resuming");
        let _bytes = from_file(&file_path).unwrap();
    }
}
```

## `good.rs` (only difference is lack of extra allocated byte)
``` rust
use std::error::Error;
use std::thread;
use std::time::Duration;

use std::fs::File;
use std::io::Read;

fn from_file(file_path: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut f = File::open(file_path)?;
    // Emitating fs::read(), but without the +1 extra byte in buffer
    let size = f.metadata().map(|m| m.len() as usize).unwrap_or(0);
    let mut bytes = Vec::with_capacity(size);
    f.read_to_end(&mut bytes)?;
    Ok(bytes)
}

fn main() {
    let file_path = std::env::args().nth(1).expect("No file path arg passed");
    for i in 1..=8 {
        // Running process should be occupying almost the same small amount of memory here, no?
        eprintln!("sleeping {}", i);
        thread::sleep(Duration::new(3, 0));
        eprintln!("resuming");
        let _bytes = from_file(&file_path).unwrap();
    }
}
```

# Building

```
cargo build
RUSTFLAGS="-Z sanitizer=leak" cargo build --target x86_64-unknown-linux-gnu
```

# Testing

## Bug

```
./target/debug/bad /tmp/31M
```

## No Bug

```
./target/debug/bad /tmp/32M
./target/debug/good /tmp/31M
./target/x86_64-unknown-linux-gnu/debug/bad /tmp/31M
```

# What's Wrong

Watch memory usage not going down after "sleeping 3".

**Comment by jonas-schievink** [comment] 2019-04-19 15:46
How are you checking the memory usage? `top` or something similar? Then this is likely just an artifact of how the system allocator works. For example, it might cache the allocated memory differently depending on allocation sizes. It doesn't have to give the freed memory back to the OS right away.

**Comment by MoSal** [comment] 2019-04-19 17:59
> How are you checking the memory usage? top or something similar?

Watching the *resident* memory in `htop`, yes.

> Then this is likely just an artifact of how the system allocator works. For example, it might cache the allocated memory differently depending on allocation sizes. It doesn't have to give the freed memory back to the OS right away.

The system allocator keeps heap-allocated memory around when you call `free()`? 

----

Alright, let's do something stupid.

## Test File
```
brotli -9 -w 24 -o /tmp/31M.br /tmp/31M
```

## Code

``` rust
use std::error::Error;
use std::thread;
use std::time::Duration;

use brotli::{BrotliDecompressCustomAlloc, reader::StandardAlloc};

use std::fs::File;
use std::io::Read;
use std::mem;

fn from_file(file_path: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut f = File::open(file_path)?;
    // Emitating fs::read()
    let size = f.metadata().map(|m| m.len() as usize + 1).unwrap_or(0);
    let mut bytes = Vec::with_capacity(size);
    f.read_to_end(&mut bytes)?;
    let mut in_buf  = unsafe { mem::uninitialized::<[u8; 256*1024]>() };
    let mut out_buf = unsafe { mem::uninitialized::<[u8; 256*1024]>() };
    let mut decompressed = Vec::with_capacity(bytes.len()*16);
    let alloc = || StandardAlloc::default();
    BrotliDecompressCustomAlloc(&mut &*bytes, &mut decompressed, &mut in_buf, &mut out_buf, alloc(), alloc(), alloc())?;
    Ok(decompressed)
}

fn main() {
    let file_path = std::env::args().nth(1).expect("No file path arg passed");
    for i in 1..=8 {
        // Running process should be occupying almost the same small amount of memory here, no?
        eprintln!("sleeping {}", i);
        thread::sleep(Duration::new(3, 0));
        eprintln!("resuming");
        let _bytes = from_file(&file_path).unwrap();
    }
    eprintln!("sleeping for 1 minute");
    thread::sleep(Duration::new(60, 0));
}
```

## Build
``` rust
cargo build --release
RUSTFLAGS="-Z sanitizer=leak" cargo build --target x86_64-unknown-linux-gnu --release
```

## Run

```
./target/release/bad_br /tmp/31M.br
 ./target/x86_64-unknown-linux-gnu/release/bad_br /tmp/31M.br
```

Here, we are up to 50MiB. And it doesn't get freed (with time at least).
Is this still normal?

------

Is it normal for the system allocator to *cache* 1.5+ GiB in resident process memory?

In another case (can't share the code) that involves decompression, deserialization (50+ MiB data), templating, and serving. Every web page reload would cause caching extra 70MiB. Building with `RUSTFLAGS="-Z sanitizer=leak"` makes the problem go away.

**Comment by the8472** [comment] 2019-04-19 19:06
for such large allocations glibc should be using mmap/munmap. You can use `strace` to follow those..

**Comment by sfackler** [comment] 2019-04-19 19:06
> The system allocator keeps heap-allocated memory around when you call `free()`?

Yes, many allocators cache free memory regions to minimize mmap traffic.

**Comment by rslife** [comment] 2019-04-19 20:17
straced a webserver process after reloading the same page (reading from the same resource) 10 times.
The `release` process ends up with ~700MiB more resident memory used (~70MiB/reload).

[release](https://archive.org/download/unsorted_files/release-10reloads.strace.gz) | [release-sanitize-leak](https://archive.org/download/unsorted_files/release-sanitize-leak-10reloads.strace.gz)

If that's expected behavior, then this issues can be closed.

**Comment by MoSal** [comment] 2019-04-19 20:19
@rslife is my other account. Apologies for the double-comment.

**Comment by the8472** [comment] 2019-05-27 19:11
Since you're using glibc you can try tune it [via environment variables](https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation-Tunables.html) or call [malloc_trim](http://man7.org/linux/man-pages/man3/malloc_trim.3.html).

Note that these things should never be done by libraries and bins should only do it during major phase transitions, e.g. when going from an allocation-heavy to a quiescent state where the allocator might cling onto memory for longer than needed.

**Comment by Mark-Simulacrum** [comment] 2019-06-21 14:47
Closing -- this is likely attributable to expected, if perhaps undesirable, system allocator behavior that Rust has no control over itself. If there is something actionable for us to do let us know and we can reopen.

**Closed by Mark-Simulacrum** 2019-06-21 14:47 UTC
