### ISSUE TITLE
Strange issue with parametized types

### ISSUE THREAD

**Issue by Ereski** [rust-lang/rust#51164] opened 2018-05-29 11:26 UTC
I'm having a strange issue with autoderiving not working. Minimal example: https://play.rust-lang.org/?gist=2c413161b3b6d986b769d3eccea1a2ca&version=stable&mode=debug

```rust
use std::fmt::Debug;

trait DbTrait: Debug + Sized {
    type Id: Debug + PartialEq + Eq;
    
    fn get(&self) -> ItemId<Self>;
}

#[derive(Debug, PartialEq, Eq)]
struct ItemId<T: DbTrait>(T::Id);

fn test<T: DbTrait>(x: &T) {
    assert_eq!(x.get(), x.get());
}
```

And the error:

```
error[E0369]: binary operation `==` cannot be applied to type `ItemId<T>`
  --> src/main.rs:15:5
   |
15 |     assert_eq!(x.get(), x.get());
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `ItemId<T>`
```

I expected this to compile. For some reason, rustc sees that `ItemId` implementes `Debug` (otherwise the `assert_eq!` macro would error out there first) but not `PartialEq`.

**Comment by jonas-schievink** [comment] 2018-05-29 11:37
Duplicate of https://github.com/rust-lang/rust/issues/26925. The `#[derive(PartialEq)]` generates a `PartialEq` impl that has a `T: PartialEq` bound, which isn't satisfied by the `T` parameter of the `test` function.

**Closed** 2018-05-29 11:49 UTC
