### ISSUE TITLE
ICE when using &Path bind

### ISSUE THREAD

**Issue by blaenk** [rust-lang/rust#24969] opened 2015-04-30 00:24 UTC
I'm not sure if this is a regression of #23133 or what, but the following has produced an ICE ever since I can remember. I commented on the above issue that it had been fixed at the time I made such a comment, so I guess this is a regression of some sort.

``` rust
use std::path::{Path, PathBuf};
use std::collections::HashSet;

fn main() {
  let hm: HashSet<PathBuf> = HashSet::new();
  let p = PathBuf::new();
  let rp: &Path = &p;
  assert!(hm.contains(rp));
}
```

[playpen](http://is.gd/gWjyh8)

crashes on beta and nightly

```
λ ~/code/rust/scratch/ice
» RUST_BACKTRACE=1 rustc ice.rs
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/
IR/Instructions.h:782: llvm::Type* llvm::checkGEPType(llvm::Type*): Assertion `Ty && "Invalid GetElementPtrInst indices for type!"' failed.                                                             zsh: abort (core dumped)  RUST_BACKTRACE=1 rustc ice.rs
```

**Comment by blaenk** [comment] 2015-04-30 00:27
cc @aturon perhaps (if not, disregard)

**Comment by luqmana** [comment] 2015-05-02 18:57
This seems to be a dupe of #23261.

**Closed by luqmana** 2015-05-02 18:57 UTC
Labels: I-ICE

**Comment by blaenk** [comment] 2015-05-02 18:59
Haha yeah, and I commented on that too. Goes to show how long it's gone
unfixed that I forgot there already was an issue.

On Saturday, May 2, 2015, Luqman Aden <notifications@github.com> wrote:

> This seems to be a dupe of #23261
> <https://github.com/rust-lang/rust/issues/23261>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust/issues/24969#issuecomment-98386342>.
>


-- 
- Jorge Israel Peña

**Comment by luqmana** [comment] 2015-05-02 21:36
@blaenk I think I have a fix for it. I'll try to finish it up later today.

**Comment by blaenk** [comment] 2015-05-02 21:37
That's awesome!

On Saturday, May 2, 2015, Luqman Aden <notifications@github.com> wrote:

> @blaenk <https://github.com/blaenk> I think I have a fix for it. I'll try
> to finish it up later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rust-lang/rust/issues/24969#issuecomment-98406980>.
>


-- 
- Jorge Israel Peña
