### ISSUE TITLE
Compiler panics after giving  ``await` is only allowed inside `async` functions and blocks` error

### ISSUE THREAD

**Issue by zeon256** [rust-lang/rust#122023] opened 2024-03-05 13:55 UTC
### Code

Not exactly sure where the error is coming from. It happened in this [commit](https://github.com/lta-rs/lta-rs/pull/48/commits/ee8cd1b2c259154e10aeea033b3f3917fbf019b9). I am suspecting this line is the one causing it.

```Rust
    fn get_traffic_flow(client: &C) -> LTAResult<Vec<String>> {
        client
            .build_req_with_skip::<TrafficFlowRawResp, _>(
                &concat_string!(client.base_url(), "/TrafficFlow"),
                None,
            )
            .await
    }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (d18480b84 2024-03-04)
binary: rustc
commit-hash: d18480b84fdbf1efc34f62070951334aa833d761
commit-date: 2024-03-04
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/compiler/rustc_middle/src/hir/mod.rs:145:21:
no entry found for key
stack backtrace:
   0:     0x76a15d98964f - std::backtrace_rs::backtrace::libunwind::trace::h07530780ae6fd4ce
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x76a15d98964f - std::backtrace_rs::backtrace::trace_unsynchronized::h704260b9c062cb70
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x76a15d98964f - std::backtrace::Backtrace::create::h9a12f7732dca79c1
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/backtrace.rs:331:13
   3:     0x76a15d989590 - std::backtrace::Backtrace::force_capture::h11c190cdce79e5d2
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/backtrace.rs:312:9
   4:     0x76a15a484c2c - std[981fd4ed4739575b]::panicking::update_hook::<alloc[132db7f59cba46f8]::boxed::Box<rustc_driver_impl[749f5dee238868cc]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x76a15d9a4470 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc48f14a5fe592d5b
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/alloc/src/boxed.rs:2030:9
   6:     0x76a15d9a4470 - std::panicking::rust_panic_with_hook::hcf4e8eff7aa16d57
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:783:13
   7:     0x76a15d9a41b2 - std::panicking::begin_panic_handler::{{closure}}::hd0c7b3c0e108de55
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:657:13
   8:     0x76a15d9a16f6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbf62ba977fbec9c4
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys_common/backtrace.rs:171:18
   9:     0x76a15d9a3ee4 - rust_begin_unwind
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:645:5
  10:     0x76a15d9ee855 - core::panicking::panic_fmt::h7842b7ed4fa4381e
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/panicking.rs:72:14
  11:     0x76a15d9eea21 - core::panicking::panic_display::h9658b1a9c45d40f4
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/panicking.rs:196:5
  12:     0x76a15d9ee60b - core::panicking::panic_str::h1b3217f8d9ba29a7
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/panicking.rs:171:5
  13:     0x76a15d9ee60b - core::option::expect_failed::h13f60a08ed0a19f0
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/option.rs:1995:5
  14:     0x76a15ba70a3c - rustc_query_impl[ba07f112ececf296]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba07f112ececf296]::query_impl::hir_owner_parent::dynamic_query::{closure#2}::{closure#0}, rustc_middle[68d2122e788b4e56]::query::erase::Erased<[u8; 8usize]>>
  15:     0x76a15bf737f4 - rustc_query_system[befd840b966d7b93]::query::plumbing::try_execute_query::<rustc_query_impl[ba07f112ececf296]::DynamicConfig<rustc_query_system[befd840b966d7b93]::query::caches::VecCache<rustc_hir[efe8743a02a8a54c]::hir_id::OwnerId, rustc_middle[68d2122e788b4e56]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[ba07f112ececf296]::plumbing::QueryCtxt, true>
  16:     0x76a15bf72e08 - rustc_query_impl[ba07f112ececf296]::query_impl::hir_owner_parent::get_query_incr::__rust_end_short_backtrace
  17:     0x76a15bf6f9b5 - <rustc_middle[68d2122e788b4e56]::lint::ShallowLintLevelMap>::lint_level_id_at_node
  18:     0x76a15bf6f0bf - <rustc_middle[68d2122e788b4e56]::ty::context::TyCtxt>::lint_level_at_node
  19:     0x76a15b8eb1aa - rustc_hir_analysis[1571b917326fccba]::check_unused::check_unused_traits
  20:     0x76a15b8eaaf3 - rustc_query_impl[ba07f112ececf296]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba07f112ececf296]::query_impl::check_unused_traits::dynamic_query::{closure#2}::{closure#0}, rustc_middle[68d2122e788b4e56]::query::erase::Erased<[u8; 0usize]>>
  21:     0x76a15c5d22f9 - rustc_query_system[befd840b966d7b93]::query::plumbing::try_execute_query::<rustc_query_impl[ba07f112ececf296]::DynamicConfig<rustc_query_system[befd840b966d7b93]::query::caches::SingleCache<rustc_middle[68d2122e788b4e56]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[ba07f112ececf296]::plumbing::QueryCtxt, true>
  22:     0x76a15c5d189a - rustc_query_impl[ba07f112ececf296]::query_impl::check_unused_traits::get_query_incr::__rust_end_short_backtrace
  23:     0x76a15c0a3018 - rustc_hir_analysis[1571b917326fccba]::check_crate
  24:     0x76a15c4fa56f - rustc_interface[93d185007ae39b60]::passes::analysis
  25:     0x76a15c4fa1d9 - rustc_query_impl[ba07f112ececf296]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[ba07f112ececf296]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[68d2122e788b4e56]::query::erase::Erased<[u8; 1usize]>>
  26:     0x76a15c53d262 - rustc_query_system[befd840b966d7b93]::query::plumbing::try_execute_query::<rustc_query_impl[ba07f112ececf296]::DynamicConfig<rustc_query_system[befd840b966d7b93]::query::caches::SingleCache<rustc_middle[68d2122e788b4e56]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[ba07f112ececf296]::plumbing::QueryCtxt, true>
  27:     0x76a15c53ce5c - rustc_query_impl[ba07f112ececf296]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  28:     0x76a15c54d1c2 - rustc_interface[93d185007ae39b60]::interface::run_compiler::<core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>, rustc_driver_impl[749f5dee238868cc]::run_compiler::{closure#0}>::{closure#0}
  29:     0x76a15c7fb7a4 - std[981fd4ed4739575b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[93d185007ae39b60]::util::run_in_thread_with_globals<rustc_interface[93d185007ae39b60]::util::run_in_thread_pool_with_globals<rustc_interface[93d185007ae39b60]::interface::run_compiler<core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>, rustc_driver_impl[749f5dee238868cc]::run_compiler::{closure#0}>::{closure#0}, core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>>::{closure#0}, core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>>
  30:     0x76a15c7fb5d0 - <<std[981fd4ed4739575b]::thread::Builder>::spawn_unchecked_<rustc_interface[93d185007ae39b60]::util::run_in_thread_with_globals<rustc_interface[93d185007ae39b60]::util::run_in_thread_pool_with_globals<rustc_interface[93d185007ae39b60]::interface::run_compiler<core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>, rustc_driver_impl[749f5dee238868cc]::run_compiler::{closure#0}>::{closure#0}, core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>>::{closure#0}, core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7f073c1c527125c7]::result::Result<(), rustc_span[da67a7ac7bf98758]::ErrorGuaranteed>>::{closure#1} as core[7f073c1c527125c7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  31:     0x76a15d9adc15 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb797f91f140d0ba6
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/alloc/src/boxed.rs:2016:9
  32:     0x76a15d9adc15 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd391096fc24d509d
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/alloc/src/boxed.rs:2016:9
  33:     0x76a15d9adc15 - std::sys::pal::unix::thread::Thread::new::thread_start::hbe2aecbaafd6f0eb
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys/pal/unix/thread.rs:108:17
  34:     0x76a1572964dc - <unknown>
  35:     0x76a157320a8c - <unknown>
  36:                0x0 - <unknown>


rustc version: 1.78.0-nightly (d18480b84 2024-03-04)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [hir_owner_parent] getting HIR parent of `blocking::traffic::TrafficRequests::get_traffic_flow::{use#0}`
#1 [check_unused_traits] checking unused trait imports in crate
#2 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

**Comment by lqd** [comment] 2024-03-05 15:07
I believe this is a duplicate of #121096, and is already fixed on master (by #121664), so I'll close this issue as such. Feel free to reopen if the next nightly somehow doesn't fix this, but I checked with that PR's artifacts and it didn't reproduce. 

Thanks for opening an issue!

**Closed by lqd** 2024-03-05 15:07 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
