### ISSUE TITLE
Binary search performance regressed in 1.25

### ISSUE THREAD

**Issue by Emerentius** [rust-lang/rust#53823] opened 2018-08-30 14:30 UTC
The speedup obtained by the optimizations from https://github.com/rust-lang/rust/pull/45333 which hit stable in 1.23 were mostly lost again from 1.25 onwards, because the compiler started emitting a branch instead of a cmov.

**1.24**
```asm
14  cmp     qword ptr [rsi + 8*rax], rcx
15  cmova   rax, r8
```

**1.25**
```asm
18  cmp     qword ptr [rsi + 8*r9], rcx
19  ja      .LBB0_7
20  mov     r8, r9
21  .LBB0_7:
```

From godbolt: https://godbolt.org/z/DUDl-T

Bench comparison with 1.23 nightly (2017-11-20, 9 days after PR merge)

```
 name                        old_1.23 ns/iter  new_1.23 ns/iter  diff ns/iter   diff %  speedup 
 binary_search_l1            70                28                         -42  -60.00%   x 2.50 
 binary_search_l1_with_dups  46                28                         -18  -39.13%   x 1.64 
 binary_search_l2            94                42                         -52  -55.32%   x 2.24 
 binary_search_l2_with_dups  68                42                         -26  -38.24%   x 1.62 
 binary_search_l3            267               234                        -33  -12.36%   x 1.14 
 binary_search_l3_with_dups  198               236                         38   19.19%   x 0.84 
```

and status quo with 1.30 nightly (2018-08-15)

```
 name                        old_1.30 ns/iter  new_1.30 ns/iter  diff ns/iter   diff %  speedup 
 binary_search_l1            75                68                          -7   -9.33%   x 1.10 
 binary_search_l1_with_dups  46                61                          15   32.61%   x 0.75 
 binary_search_l2            99                89                         -10  -10.10%   x 1.11 
 binary_search_l2_with_dups  71                89                          18   25.35%   x 0.80 
 binary_search_l3            272               245                        -27   -9.93%   x 1.11 
 binary_search_l3_with_dups  212               256                         44   20.75%   x 0.83 
```

**Comment by Emerentius** [comment] 2018-08-31 17:17
The likely culprit is the upgrade from LLVM 4 to 6. The PR was merged on the 10th of Feb. It was fast on the 9th and slow on the 12th.

@estebank The behaviour did hit stable (if only for 2 releases), so does it not need the `regression-from-stable-to-stable` label?

**Comment by estebank** [comment] 2018-08-31 17:40
@Emerentius what do you mean for only 2 releases? Isn't the slowdown present in stable through nightly? Reading the assembly from godbolt it seems to me like there have been some changes but the code causing the slowdown presented in this issue is still there. If that is the case, then it would need that label, but if it was fixed in current stable, then we can close the ticket, as I do not believe we cut point releases for previous stable releases.

**Comment by Emerentius** [comment] 2018-08-31 19:38
@estebank I mean it was fast in 1.23 stable and slow from 1.25 stable on, so fast for 2 stable releases, then regressed.

**Comment by pnkfelix** [comment] 2018-11-29 15:56
discussed in T-compiler meeting. Re-prioritizing as P-high *just* for evaluating the scope of the regression (though some good work on that is already evident in this comment thread).

**Comment by pnkfelix** [comment] 2018-12-12 15:54
Not sure why I previously removed I-slow; I'm putting it back now.

**Comment by pnkfelix** [comment] 2018-12-12 16:05
Hey @Emerentius, what is the distinction you are making in the columns with the prefix "old_" and "new_" in the tables you present?

That is, I would have thought that "old_" somehow corresponds to the state prior to the changes from PR #45333 and "new_" corresponds to after PR #45333 landed; but you already established that PR #45333 landed in between the two versions that each have "old_" and "new_" labels applied to them.

So I don't understand what difference has been applied to either the code or the benchmark in between the two columns there. (Hypothesis: Is "old_" testing the binary search implementation prior to PR #45333, and "new_" testing the binary search implementation that was added by PR #45333 ?)

**Comment by pnkfelix** [comment] 2018-12-12 16:08
(In any case I definitely am able to reproduce a regression on [benches/slice](https://github.com/rust-lang/rust/blob/master/src/libcore/benches/slice.rs) between nightly-2018-02-09 and 2018-02-12, as anticipated/noted by https://github.com/rust-lang/rust/issues/53823#issuecomment-417733235 ; there's a fair amount of noise between runs when looking at binary_search_l3 in my own machine, but binary_search_l1 is much more consistent in illustrating a 2x regression for me.)

**Comment by Emerentius** [comment] 2018-12-12 17:22
@pnkfelix 
>Hypothesis: Is "old_" testing the binary search implementation prior to PR #45333, and "new_" testing the binary search implementation that was added by PR #45333 ?

That is exactly it

**Comment by pnkfelix** [comment] 2018-12-13 13:13
Okay so I've done some preliminary analysis of the scope of the problem.

On my desktop linux machine, I built the benchmark suite in `libcore/benches` atop the nightly compilers from 2018-02-09 and 2018-02-12. Then I did three runs of the suite on each compiler (for a total of six runs).

Here is the raw data from that exercise: https://gist.github.com/8f511af7012c750928a6bdbf8efa3e6f

Then I put it into a spreadsheet, took the min (of the three runs) of the reported ns/iter for each benchmark, and asked to see the ratio (i.e. slowdown, where 2.0 is a 2x slowdown, 1.0 is no change, and 0.5 is a 2x speedup), comparing the min for 2018-02-09 to 2018-02-12.

 * (One might argue I should use average instead of minimum... but for understanding compiler output, I go along with the argument presented [here](http://blog.kevmod.com/2016/06/benchmarking-minimum-vs-average/) that usually the outliers are much slower than normal, rather than faster, and so taking the minimum is more likely to filter out transient noise rather than artificial improvement)

Finally, when looking at the slowdown ratio, I asked for the values > 1.2 to be highlighted in red (so that we'd pay special attention to a 1.2x slowdown) and the values < 0.9 to be highlighted in green (so that we'd also notice reasonable speedups).

Here is that spreadsheet: https://www.dropbox.com/s/qznzchqhibi5o67/three-runs.xlsx?dl=0

**Comment by pnkfelix** [comment] 2018-12-13 13:32
A number of benchmarks improved significantly (i.e. the slowdown ratio is <0.9) over the time period specified. I'm not going to list them here, but there are ~44 of them.

But here are the 9 cases that regressed:

| test |   2018-02-09 min-of-3 ns/iter | 2018-02-12 min-of-3 ns/iter | slowdown |
|-----|  ----------------------------- | ----------------------------- | ---------- |
| char::methods::bench_to_digit_radix_10 | 16,208 | 20,078 |  1.24x
|  iter::bench_zip_then_skip      | 2,580 | 3,899                     |  1.51x
| num::bench_u32_from_str_radix_2 | 17,896 | 23,223          |  1.30x
| slice::binary_search_l1                      |   21      | 51                |  2.43x
| slice::binary_search_l1_with_dups    |   21      |  46               |  2.19x
|  slice::binary_search_l2                    |    31    | 67                 | 2.16x
| slice::binary_search_l2_with_dups   |    31    | 67                 | 2.16x
| slice::binary_search_l3                     | 108     | 141               | 1.31x
|  slice::binary_search_l3_with_dups |  109     | 142               | 1.30x

Obviously the latter six cases are the ones that were already being pointed out by this bug.

(The other three entries in the table may or may not have the same core cause.)

Obviously the libcore/benches benchmark should not be the sole decider about whether a regression is significant, but based on these results, the impact *does* seem to be somewhat restricted in scope...

**Comment by pnkfelix** [comment] 2018-12-14 12:59
Also, there are some pretty interesting discussions among LLVM developers about when they turn cmov *into* branches. It sounds there are a number of scenarios where this exhibits better performance due to the processors branch prediction or something.
 * https://reviews.llvm.org/D34769
 * https://bugs.llvm.org/show_bug.cgi?id=33954
 * https://reviews.llvm.org/D36081

**Comment by pnkfelix** [comment] 2018-12-14 13:12
In particular, in the LLVM developer discussions linked above, I saw mention of the following flag: `-x86-cmov-converter=false`

I gave that a whirl, and the results seem promising:

<details>

```
% rustc +nightly-2018-02-12 -O -C llvm-args=-x86-cmov-converter=false --test lib.rs -o ../benches-2018-02-12.nocmovconv
% rustc +nightly-2018-02-12 -O                                        --test lib.rs -o ../benches-2018-02-12
% rustc +nightly-2018-02-09 -O                                        --test lib.rs -o ../benches-2018-02-09
% ../benches-2018-02-09 --bench slice

running 6 tests
test slice::binary_search_l1                               ... bench:          21 ns/iter (+/- 0)
test slice::binary_search_l1_with_dups                     ... bench:          21 ns/iter (+/- 0)
test slice::binary_search_l2                               ... bench:          31 ns/iter (+/- 0)
test slice::binary_search_l2_with_dups                     ... bench:          31 ns/iter (+/- 0)
test slice::binary_search_l3                               ... bench:         110 ns/iter (+/- 1)
test slice::binary_search_l3_with_dups                     ... bench:         112 ns/iter (+/- 7)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured; 142 filtered out

% ../benches-2018-02-12 --bench slice

running 6 tests
test slice::binary_search_l1                               ... bench:          51 ns/iter (+/- 0)
test slice::binary_search_l1_with_dups                     ... bench:          46 ns/iter (+/- 0)
test slice::binary_search_l2                               ... bench:          67 ns/iter (+/- 1)
test slice::binary_search_l2_with_dups                     ... bench:          67 ns/iter (+/- 0)
test slice::binary_search_l3                               ... bench:         143 ns/iter (+/- 1)
test slice::binary_search_l3_with_dups                     ... bench:         142 ns/iter (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured; 142 filtered out

% ../benches-2018-02-12.nocmovconv --bench slice

running 6 tests
test slice::binary_search_l1                               ... bench:          21 ns/iter (+/- 0)
test slice::binary_search_l1_with_dups                     ... bench:          21 ns/iter (+/- 0)
test slice::binary_search_l2                               ... bench:          31 ns/iter (+/- 1)
test slice::binary_search_l2_with_dups                     ... bench:          31 ns/iter (+/- 0)
test slice::binary_search_l3                               ... bench:         114 ns/iter (+/- 2)
test slice::binary_search_l3_with_dups                     ... bench:         115 ns/iter (+/- 1)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured; 142 filtered out
```

**Comment by pnkfelix** [comment] 2018-12-14 13:17
To be clear: I am not suggesting that we should turn the `x86-cmov-converter` pass off by default in `rustc`. But 1. we should check whether the improved version from https://reviews.llvm.org/D36081 is in our LLVM (and if not, consider cherry-picking it over), and 2. if we can reproduce this issue on the current LLVM version, then we should file an issue with them upstream.

**Comment by nikic** [comment] 2018-12-14 13:53
I think the issue here might be that cmov conversion does not realize that it will not be possible to sink the cmovd chain into the created branches, because the condition also depends on them.

**Comment by nikic** [comment] 2018-12-14 17:51
I've filed an LLVM issue: https://bugs.llvm.org/show_bug.cgi?id=40027

**Comment by pnkfelix** [comment] 2018-12-17 11:48
Okay at this point I think I've convinced myself that the scope of this problem is somewhat limited, 

So I'm going to downgrade this to P-medium.

It also isn't really going to be addressed on our end (except perhaps via cherry-picking a patch for [the LLVM issue](https://bugs.llvm.org/show_bug.cgi?id=40027)).

So I'm tempted to close it, but I'll maybe wait to let other members of  @rust-lang/compiler weigh in before I do that.

**Comment by pnkfelix** [comment] 2018-12-17 11:50
I'll leave myself assigned for now, but mostly as a reminder to close it in the future.

If someone else wants to take this issue and run with it, feel free to assign yourself and unassign me.

**Comment by nikic** [comment] 2018-12-17 13:32
I think the main actionable point here is to try and change the binary search implementation in a way that does not run into this LLVM issue. Not sure how that would look like, but something that interchanges the order of the compare and the load (i.e. already load for the next iteration) might work, because this is a pattern that LLVM specifically checks for.

**Comment by arielb1** [comment] 2018-12-17 22:40
Putting this on T-libs if they can find a libs-level solution.

**Comment by pnkfelix** [comment] 2019-02-21 11:28
@fulmicoton have you tried passing ` -C llvm-args=-x86-cmov-converter=false` to rustc? I noted [here above](https://github.com/rust-lang/rust/issues/53823#issuecomment-447321359) that this seems to recover most of the lost performance on the relevant slice benchmarks.

**Comment by pnkfelix** [comment] 2019-05-17 10:40
Unassigning self: I don't think there's much for me to do here from the viewpoint of `rustc` compiler, apart from hypothetically turning off `x86-cmov-converter` by default, which seems like a bad idea.

**Comment by bstrie** [comment] 2021-07-03 19:53
I'm not fluent in asm but it looks as though the problem still exists.

1.24:
```asm
.LBB0_4:
        mov     r9, rdx
        shr     r9
        lea     rax, [r9 + r8]
        cmp     qword ptr [rsi + 8*rax], rcx
        cmova   rax, r8
        sub     rdx, r9
        cmp     rdx, 1
        mov     r8, rax
        ja      .LBB0_4
```

1.55-nightly:
```asm
.LBB0_3:
        shr     rdx
        add     rdx, rsi
        cmp     qword ptr [rdi + 8*rdx], r8
        jb      .LBB0_6
        je      .LBB0_9
        mov     rcx, rdx
        sub     rdx, rsi
        ja      .LBB0_3
```

**Comment by the8472** [comment] 2021-07-04 07:58
Note that #74024 significantly changed the binary_search implementation in the meantime so they are no longer comparable. Instead you'll have to copy the old implementation into godbolt to retain comparability. That said, the issue still exists there too.


https://godbolt.org/z/8cqKdxG4K


```rust
pub fn binary_search(slice: &[u64], key: u64) -> Result<usize, usize> {
    binary_search_by(slice, |val| val.cmp(&key) )
}

use std::cmp::Ordering::{self, Greater, Less, Equal};

fn binary_search_by<'a, T, F>(slice: &'a [T], mut f: F) -> Result<usize, usize>
    where F: FnMut(&'a T) -> Ordering
{
    let s = slice;
    let mut size = s.len();
    if size == 0 {
        return Err(0);
    }
    let mut base = 0usize;
    while size > 1 {
        let half = size / 2;
        let mid = base + half;
        // mid is always in [0, size).
        // mid >= 0: by definition
        // mid < size: mid = size / 2 + size / 4 + size / 8 ...
        let cmp = f(unsafe { s.get_unchecked(mid) });
        base = if cmp == Greater { base } else { mid };
        size -= half;
    }
    // base is always in [0, size) because base <= mid.
    let cmp = f(unsafe { s.get_unchecked(base) });
    if cmp == Equal { Ok(base) } else { Err(base + (cmp == Less) as usize) }
}
```

**Comment by the8472** [comment] 2021-07-04 11:32
> Putting this on T-libs if they can find a libs-level solution.

I have tested several older revisions of the binary_search and partition_point implementations. All of them had their conditional moves converted to cmp + branch due to this llvm change.

[This LLVM issue comment](https://bugs.llvm.org/show_bug.cgi?id=40027#c8) suggests that the primary heuristic which turns off this optimization only looks for binary tree searches (unpredictable pointer chasing) but not binary searches (unpredictable pointer arithmetic).

Another heuristic related to cost modelling has been added. Modifying its threshold via `-C llvm-args=-x86-cmov-converter-threshold=10` does revert the old binary search implementation (see previous comment) to conditional moves. This doesn't work for the current, short-circuiting implementation from #74024 (but running that one on rust 1.24 does produce cmovs).
I don't think there's anything we could do on the libs side to trigger that heuristic with its current default (4).

The options I currently see are:

1. wait for an llvm fix (might require a new `unpredictable` intrinsic)
2. special-case x86 with assembly
3. tweak llvm-args

Only option 2 would be a pure libs thing. Some of those options would still require changes to the current implementation and benchmark runs. The old `while size > 1` approach seems to be easier to turn into cmovs than current `while left < right` one. Or separate implementations `partition_point` and `binary_search` may be needed.

**Comment by yaahc** [comment] 2021-07-19 15:52
We discussed this issue in our last libs team meeting and concluded that there's nothing left for libs to do, and that we need to wait for the fix to happen upstream in https://bugs.llvm.org/show_bug.cgi?id=40027. Our plan is to hand this over to the compiler team for tracking as discussed in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/tracking.20an.20old.20regression. For now we've tagged both teams and nominated it so that the compiler team can confirm the handover in their next meeting.

**Comment by pnkfelix** [comment] 2021-07-22 14:00
@yaahc @joshtriplett  I'm happy to confirm handover to T-compiler, but the prioritization of this (currently P-low; P-medium as of 8 days ago) essentially means that we're never going to prioritize it for discussion in a meeting. It will just be task hanging out there for interested people to look at and discuss.

So, I just wanted to confirm: Is that an acceptable outcome from the point of view of you all? Or do you think this should be assigned higher priority?

**Comment by joshtriplett** [comment] 2021-07-22 18:28
@pnkfelix That's roughly the outcome we were expecting.

We do feel that this would be worthwhile to have on the radar of a team whose primary purview is LLVM-related fixes that would benefit Rust, but we also recognize that that's a "somebody should", and we don't have a somebody to offer.

**Comment by yaahc** [comment] 2021-07-22 23:44
What Josh said, I've gone ahead and removed the `T-libs` label, thanks for the confirmation @pnkfelix ^_^.

**Comment by vlovich** [comment] 2023-09-01 00:12
Could something like https://docs.rs/cmov/latest/cmov/ be used in the interim to force the usage of cmov to recover the performance?

**Comment by mohe2015** [comment] 2023-09-01 00:19
Is profile guided optimization able to do anything in this case maybe?

**Comment by the8472** [comment] 2023-09-14 10:33
There's [a discussion](https://internals.rust-lang.org/t/pre-rfc-stabilization-of-likely-bool-unlikely-bool-assume-bool-intrinsics/19409) what to do about `likely()/unlikely()` on IRLO. Adding an `unpredictable()` was mentioned too.

**Comment by Amanieu** [comment] 2024-07-26 23:40
See #128254 for a potential fix.

**Closed** 2024-08-02 10:58 UTC
Labels: A-LLVM, I-slow, P-low, T-compiler, regression-from-stable-to-stable
