### ISSUE TITLE
#[derive] generates unnecessary bound when field is associated type

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#50729] opened 2018-05-14 03:39 UTC
With this struct:

```rust
#[derive(Debug)]
struct Foo<T: std::str::FromStr> {
    field: T::Err,
}
```

The only bound needed on the generated impl is `where T::Err: Debug`. However, the generated code contains `where T: Debug, T::Err: Debug`. Why is the first one necessary? The deriving code already scans the field types to find `T::Err` so it should be able to see that bare `T` is not mentioned.

cc #26925

**Comment by fmease** [comment] 2024-12-21 02:33
This is simply an instance of https://github.com/rust-lang/rust/issues/26925 (Ctrl+F for *assoc*, *perfect deriving*, *`T::`*, etc.) which you've already cc'ed. Closing as duplicate of it.

**Closed by fmease** 2024-12-21 02:33 UTC
Labels: C-enhancement, A-macros, T-compiler
