### ISSUE TITLE
Nightly toolchain version different than rustc version

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust#53557] opened 2018-08-21 10:57 UTC
Hi,
So I noticed it in nightly `2018-04-12` but I'm sure this apply to other nightlys.
I install toolchain `rustup override set nightly-2018-04-12-x86_64-unknown-linux-gnu`
But the rustc version is different `rustc 1.27.0-nightly (ad610bed8 2018-04-11)`.

On the IRC people told me the reason is because the CI starts deployment at 11:00PM and it doesn't end until after the next day starts, this seems solvable pretty easy.

Don't you think it's better to have a consistent release date?

**Comment by eddyb** [comment] 2018-08-21 11:17
Note that the date in `(ad610bed8 2018-04-11)` is *not* a version, it's the timestamp of the last commit (from the last merged PR) *before* the nightly, i.e. ad610bed8. If no PRs get merged, *it doesn't change*.

cc @SimonSapin @alexcrichton This has been discussed before.

**Comment by SimonSapin** [comment] 2018-08-21 11:57
The previous attempt at fixing this broke some infra things and was reverted: https://github.com/rust-lang/rust-central-station/pull/27

**Comment by Mark-Simulacrum** [comment] 2019-09-02 14:38
Closing as duplicate of https://github.com/rust-lang/rust/issues/51533.

**Closed by Mark-Simulacrum** 2019-09-02 14:38 UTC
Labels: T-infra
