### ISSUE TITLE
The borrow checker fails when a raw pointer points to a trait object with a lifetime

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#40074] opened 2017-02-24 13:27 UTC
```
use std::collections::HashMap;

trait TestTrait {}
impl<T> TestTrait for T {}

struct Test<'r> {
    map: HashMap<usize, *mut (TestTrait + 'r)>,
}

impl<'r> Test<'r> {
    fn keys(&'r self) -> std::collections::hash_map::Keys<'r, usize, *mut (TestTrait + 'r)> {
        self.map.keys()
    }
}

struct Ecs<'r> {
    world: Vec<Test<'r>>,
}
impl<'r> Ecs<'r> {
    fn add_entity(&'r mut self) {
        {
            let p = self.world.iter().position(|t| t.keys().len() == 1);
        }
        self.world.push(Test { map: HashMap::new() });
    }
}
fn main() {}

```
```
error[E0502]: cannot borrow `self.world` as mutable because it is also borrowed as immutable
  --> src/main.rs:24:9
   |
22 |             let p = self.world.iter().position(|t| t.keys().len() == 1);
   |                     ---------- immutable borrow occurs here
23 |         }
24 |         self.world.push(Test { map: HashMap::new() });
   |         ^^^^^^^^^^ mutable borrow occurs here
25 |     }
   |     - immutable borrow ends here
```
http://play.integer32.com/?gist=eaf8df219b2f977a98fd48b25abf96fc&version=stable

**Comment by arielb1** [comment] 2017-02-24 21:33
That's what `fn keys(&'r self)`, aka `fn keys(Self: &'r Test<'r>)` means - it borrows the struct for the entirety of `'r`. 

keywords: diagnostics borrow-checker variance.

**Comment by arielb1** [comment] 2017-02-24 21:34
You probably want `fn keys(&self)`.

**Comment by Mark-Simulacrum** [comment] 2017-05-28 15:03
Closing as not a bug; to fix `Test::keys` should be changed to `fn keys<'a>(&'a self) -> std::collections::hash_map::Keys<'a, usize, *mut (TestTrait + 'r)> {` I believe.

**Closed by Mark-Simulacrum** 2017-05-28 15:03 UTC
Labels: A-borrow-checker, A-diagnostics, T-compiler
