### ISSUE TITLE
nested impl trait in return position (ITRP) forces argument lifetimes to be 'static

### ISSUE THREAD

**Issue by ajwerner** [rust-lang/rust#115849] opened 2023-09-14 17:30 UTC
I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=11aa31adacc364a4899457df8f026061)):

```rust
trait Goal {}

impl Goal for () {}

struct Holder<'a, T: ?Sized> {
    r: &'a T,
}

struct StaticHolder<T> {
    t: T,
}

fn make_goal<'a, T: 'a>(_s: &'a StaticHolder<T>) -> impl Goal + 'static {
    ()
}

fn outer() -> impl Goal {
    let s = String::from("hello world");
    let h = Holder { r: s.as_str() };
    let s = StaticHolder { t: h };
    make_goal(&s)
}

fn main() {
    outer();
}
```

I expected it to work. The value returned from `make_goal` is `impl Goal + 'static`, so i should be able to return it from `outer`.

Instead, this happened:
```
error[[E0597]](https://doc.rust-lang.org/stable/error_codes/E0597.html): `s` does not live long enough
  --> src/main.rs:19:25
   |
18 |     let s = String::from("hello world");
   |         - binding `s` declared here
19 |     let h = Holder { r: s.as_str() };
   |                         ^^^^^^^^^^ borrowed value does not live long enough
20 |     let s = StaticHolder { t: h };
21 |     make_goal(&s)
   |     ------------- argument requires that `s` is borrowed for `'static`
22 | }
   | - `s` dropped here while still borrowed

For more information about this error, try `rustc --explain E0597`.
```

### Meta

I compiled in the playground using 1.72.0 and 1.74.0.

**Comment by traviscross** [comment] 2023-09-16 01:06
Here's a minimized version:

```rust
struct Ref<'a>(&'a ());

fn capture<'o, T>(_x: T) -> impl Send + 'o {}

fn outlives<'o, T: 'o>(_t: T) {}
fn test<'o>(x: ()) -> impl Send + 'o {
    outlives::<'o, _>(capture::<'o, Ref<'_>>(Ref(&x))); // OK.
    capture::<'o, Ref<'_>>(Ref(&x))
//                             ^^
// ERROR: borrowed value does not live long enough.
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=struct+Ref%3C%27a%3E%28%26%27a+%28%29%29%3B%0A%0Afn+capture%3C%27o%2C+T%3E%28_x%3A+T%29+-%3E+impl+Send+%2B+%27o+%7B%7D%0A%0Afn+outlives%3C%27o%2C+T%3A+%27o%3E%28_t%3A+T%29+%7B%7D%0Afn+test%3C%27o%3E%28x%3A+%28%29%29+-%3E+impl+Send+%2B+%27o+%7B%0A++++outlives%3A%3A%3C%27o%2C+_%3E%28capture%3A%3A%3C%27o%2C+Ref%3C%27_%3E%3E%28Ref%28%26x%29%29%29%3B+%2F%2F+OK.%0A++++capture%3A%3A%3C%27o%2C+Ref%3C%27_%3E%3E%28Ref%28%26x%29%29%0A%2F%2F+++++++++++++++++++++++++++++%5E%5E%0A%2F%2F+ERROR%3A+borrowed+value+does+not+live+long+enough.%0A%7D%0A)

This is another manifestation of #42940.

As it applies here, it's not that the argument lifetimes need to be `'static`, it's that they have to be able to be *named*.  Consider, e.g., that this is accepted:

```rust
trait Captures<T> {}
impl<T, U: ?Sized> Captures<T> for U {}

struct Ref<'a>(&'a ());

fn capture<'o, T>(_x: T) -> impl Send + 'o {}

fn outlives<'o, T: 'o>(_t: T) {}
fn test<'o, 'b>(x: &'b ()) -> impl Send + Captures<&'b ()> + 'o {
    outlives::<'o, _>(capture::<'o, Ref<'b>>(Ref(x))); // OK.
    capture::<'o, Ref<'b>>(Ref(x)) // OK.
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=trait+Captures%3CT%3E+%7B%7D%0Aimpl%3CT%2C+U%3A+%3FSized%3E+Captures%3CT%3E+for+U+%7B%7D%0A%0Astruct+Ref%3C%27a%3E%28%26%27a+%28%29%29%3B%0A%0Afn+capture%3C%27o%2C+T%3E%28_x%3A+T%29+-%3E+impl+Send+%2B+%27o+%7B%7D%0A%0Afn+outlives%3C%27o%2C+T%3A+%27o%3E%28_t%3A+T%29+%7B%7D%0Afn+test%3C%27o%2C+%27b%3E%28x%3A+%26%27b+%28%29%29+-%3E+impl+Send+%2B+Captures%3C%26%27b+%28%29%3E+%2B+%27o+%7B%0A++++outlives%3A%3A%3C%27o%2C+_%3E%28capture%3A%3A%3C%27o%2C+Ref%3C%27b%3E%3E%28Ref%28x%29%29%29%3B+%2F%2F+OK.%0A++++capture%3A%3A%3C%27o%2C+Ref%3C%27b%3E%3E%28Ref%28x%29%29+%2F%2F+OK.%0A%7D%0A)

A full analysis of this issue is available [here](https://hackmd.io/83sY9XQjSiK79QdnqK0F3Q).

**Comment by aliemjay** [comment] 2023-09-16 05:55
> This is another manifestation of #42940.

Agree. Closing as a duplicate of #42940. Thanks for reporting!

**Closed by aliemjay** 2023-09-16 05:55 UTC
Labels: C-bug, needs-triage
