### ISSUE TITLE
OpenOptions::tuncate(true)   !=   File::open_mode(..., io::Truncate, ...)

### ISSUE THREAD

**Issue by dan-t** [rust-lang/rust#23178] opened 2015-03-08 12:01 UTC
I'm porting some code to Rust 1.0 and found a difference in the current and
the previous behaviour of truncating files.

Previously I had:

    File::open_mode(file, io::Truncate, io::ReadWrite)

and now I have:

    OpenOptions::new()
        .truncate(true)
        .read(true)
        .write(true)
        .open(file)

The previous version also worked if the file at 'file' wasn't present,
in this case the file was created. 

The new version doesn't work if the file isn't present and I'm getting -
the unfortunately not very telling - error:

    Error { repr: Os(2) }

~> rustc --version --verbose
    rustc 1.0.0-nightly (270a677d4 2015-03-07) (built 2015-03-07)
    binary: rustc
    commit-hash: 270a677d4d698916f5ad103f0afc3c070b8dbeb4
    commit-date: 2015-03-07
    build-date: 2015-03-07
    host: x86_64-unknown-linux-gnu
    release: 1.0.0-nightly

~> lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.1 LTS
    Release:        14.04
    Codename:       trusty

What is the right behaviour here, the previous one or the current?

**Comment by dan-t** [comment] 2015-03-08 13:18
Ok, it seems that `OpenOptions` needs an additional `create(true)' to behave in the
same way as `File::open_mode`.

So the bevaviour seems to be intended, but I'm not quite sure what I should
think about the new API, if it will increase errors instead of reducing them.

**Comment by dan-t** [comment] 2015-03-08 13:50
Thinking about the API of `OpenOptions`, I think it's fine to have an option like `create`,
but having it split into sepeate method calls seems error prone, because you aren't
forced to make a conscious decision.

**Comment by shepmaster** [comment] 2015-03-08 16:54
Conversely, your original code didn't indicate that it was OK to *create* the file:

```
File::open_mode(file, io::Truncate, io::ReadWrite)
```

Which also seems like there wasn't a conscious decision to create it.

**Comment by alexcrichton** [comment] 2015-03-08 17:55
This is currently intentional behavior, and as such I'm going to close this as working as intended. There are two distinct methods of truncating a file, if you do not specify `create` then you're declaring that you can only truncate an existing file where if you specify `create` you're saying that you'll truncate it if it already exists. This distinction was not present in the previous API.

> The new version doesn't work if the file isn't present and I'm getting - the unfortunately not very telling - error:

When displaying errors you should not be using `unwrap` or `{:?}` but rather `{}` to get errors that look like:

```
err: No such file or directory (os error 2)
```

**Closed by alexcrichton** 2015-03-08 17:55 UTC
Labels: A-libs
