### ISSUE TITLE
compile-time: massive regression during 2015

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#25069] opened 2015-05-03 11:23 UTC
I noticed earlier that the compile time of `image` increased massively during the beginning of 2015. Unfortunately it was hard to quantify this regression since we also changed a lot during this time. 

Fortunately I just found a good example that shows a 20-fold increase in compile time. It is a [single file](https://gist.github.com/nwin/b0b8bb23040a526b5b59) with no other dependencies (if somebody wants to try: the [original version](https://github.com/cmr/TEMP-rust-png) is even much older). The two revisions are exactly the same code, the newer just has been updated to compile on a recent rustc. Note that this is `rustc` only, no time is spend in llvm.

```
$ sudo rustc --version
rustc 0.13.0-nightly (7608dbad6 2014-12-31 10:06:21 -0800)
$ time sudo rustc --crate-type=lib -Z no-trans inflate.rs

real	0m1.176s
user	0m1.059s
sys	0m0.113s
```
(note that something is wrong with the old .pkg-file I used to install rustc, I need to use sudo to run it)

```
$ rustc --version
rustc 1.1.0-nightly (c4b23aec4 2015-04-29) (built 2015-04-28)
$ time rustc --crate-type=lib -Z no-trans inflate.rs

real	0m25.208s
user	0m23.919s
sys	0m1.213s
```

The [time profiles](https://gist.github.com/nwin/016c7e64ae270f519cdb) show that `driver::phase_1_parse_input` and `driver::phase_2_configure_and_expand` almost stayed constant while the time spent in `driver::phase_3_run_analysis_passes` exploded.

**Comment by bluss** [comment] 2015-05-03 12:39
If you can, bench after the merge of aecf3d8 / PR #24965 as well. Merged  Fri May 1 08:33:08 2015 +0000 so it should be in the nightlies.

**Comment by nwin** [comment] 2015-05-03 13:29
that improved marginally

```
$ rustc --version
rustc 1.1.0-nightly (c42c1e7a6 2015-05-02) (built 2015-05-01)
$ time rustc --crate-type=lib -Z no-trans inflate.rs

real	0m19.984s
user	0m18.948s
sys	0m1.033s
$ rustc --crate-type=lib -Z no-trans -Z time-passes inflate.rs
...
time: 18.775 	type checking
...
```

**Comment by arielb1** [comment] 2015-05-03 17:31
Your code has a >10kLOC method. Couldn't you split it?

**Comment by arielb1** [comment] 2015-05-03 17:39
Performance does seem O(n^2) in the number of `len!` calls.

**Comment by nwin** [comment] 2015-05-03 17:40
Maybe it is a duplicate of #23977?

**Comment by bluss** [comment] 2015-05-04 13:54
Tested current nightly after the PR to inline hashing better. Only reduces run time of the type checking pass by 6%.

**Comment by pnkfelix** [comment] 2015-05-04 16:25
Did binary search over the nightlies (thanks to [multirust](https://github.com/brson/multirust)); problem was injected between nightly-2015-03-30 and nightly-2015-03-31

In other words, this version is fast:
```
rustc 1.0.0-nightly (d8be84eb4 2015-03-29) (built 2015-03-29)
```
and this version is slow:
```
rustc 1.0.0-nightly (6cf3b0b74 2015-03-30) (built 2015-03-30)
```

**Comment by bluss** [comment] 2015-05-04 17:13
@pnkfelix That's what niko is  with the other issue too https://github.com/rust-lang/rust/issues/23977#issuecomment-89035822

**Comment by Manishearth** [comment] 2015-05-31 09:12
I have noticed a similar effect in Servo across a particular Rust upgrade (forgot which).

Can we give this priority now that 1.0 is out?

**Comment by arielb1** [comment] 2015-06-02 09:37
@Manishearth 

Are you sure that *this* is the issue?

**Comment by Manishearth** [comment] 2015-06-02 09:38
No, I'm not, but regardless, we should be fixing this with priority.

**Comment by arielb1** [comment] 2015-06-02 09:44
The problem is that literal inference creates tons of literal variables (`IntVid`/`FloatVid`) and obligations around them, and we uselessly try to resolve these obligations.


I think of 3 ways to solve this
    1) Make the operator impls built-in, essentially `impl<intvar T> Add<T> for T`. This would avoid creating bogus obligations.
    2) dually, make check_binop not try to `select_obligations_where_possible` when it ends up with a float/int var. This would prevent the `O(n^2)`-ness, but if there are other places that `select_obligations_where_possible` we would have `O(n m)`
    3) Quickly ignore obligations that didn't make progress during selection. I think this would improve selection performance, but this requires more complexity.
cc @nikomatsakis

**Comment by pnkfelix** [comment] 2016-06-02 10:46
Nominating for prioritization. I suspect at this point its merely P-medium, but best to discuss.  (Plus for all I know its actually been resolved, since #25916 was resolved by PR #31680, but then again that same PR notes that the quadratic behavior is still present; it just has less impact...)

**Comment by nikomatsakis** [comment] 2016-06-02 20:16
In compiler team meeting: we believe this to have been fixed. Would be good to verify whether the perf gap has been corrected in the meantime!

**Comment by nikomatsakis** [comment] 2016-06-02 20:16
triage: P-medium

**Comment by DemiMarie** [comment] 2016-10-02 23:40
Has anyone tried benchmarking the compiler?

**Comment by Mark-Simulacrum** [comment] 2016-10-02 23:47
I believe @nnethercote has been working on profiling and benchmarking the compiler, and there is also http://perf.rust-lang.org/ which attempts to keeps track of current compile times.

Ignore the 18000% regression on perf.rlo right now, we recently changed what we were benchmarking for syntex which caused that jump.

**Comment by nnethercote** [comment] 2016-10-03 01:32
Yes, I have been doing some benchmarking and profiling. So far I've landed #36734 and #36592, and I just opened #36917. I think there is still some low- to middle-hanging fruit to be picked.

I have also done some work on https://github.com/rust-lang-nursery/rustc-benchmarks. I added a script that lets you compare the speed of two different compilers. I also fixed it so that the `syntex` benchmark now measures the right thing, which explains the huge regression that @Mark-Simulacrum mentioned.

**Comment by pnkfelix** [comment] 2016-10-03 15:18
I just took the [gist linked earlier](https://gist.github.com/nwin/b0b8bb23040a526b5b59) and re-ran it on today's compiler.

(I had to add some extra `#![feature]` and `#![allow]` attributes to get it to compile without error, but that process is pretty mechanical and uninteresting.)

The performance of the compiler has not returned to the point where it was at circa March 29th. In particular:

Nightly  |  Commit  |  Time
--------|----------|-----------
nightly-2015-03-30 | d8be84eb4 | real    0m6.208s
nightly-2015-03-31  | 6cf3b0b74  | real    0m18.546s
nightly-2015-09-30  | 65d5c0833 | real    0m12.639s


so we've managed to recover from *part* of the regression, but not all of it.

**Comment by pnkfelix** [comment] 2016-10-03 15:47
I'm going to close this ticket since I believe we have addressed the specific compile-time regression described here.

**Closed by pnkfelix** 2016-10-03 15:47 UTC
Labels: I-compiletime, P-medium, T-compiler

**Comment by nnethercote** [comment] 2016-10-03 22:19
> I just took the gist linked earlier and re-ran it on today's compiler.

FWIW: that gist contains inflate.rs. A slightly different version of that file is in rustc-benchmarks, which means it's likely to get some attention. In fact, I've already done some profiling for it and found that it is totally dominated by operations involving `ObligationForest`. (It's the only benchmark I've seen for which this is true.) I will try to get around to looking at that one soon, though I don't know anything about `ObligationForest` so if someone more knowledgeable wants to look in the meantime, that would be fine with me :)

**Comment by nikomatsakis** [comment] 2016-10-04 19:20
@nnethercote feel free to ping me sometime if you want to look at it a bit together

**Comment by arielb1** [comment] 2016-10-04 19:27
@nnethercote 

That would be expected. The test-case triggers an O(n^2) case in `ObligationForest`. We have mitigated that case to take a reasonable amount of time on reasonable examples.

It is possible that this could be made O(n), but the ways seem to have bad overheads in the common case.
