### ISSUE TITLE
Error message could be improved in generic match arm

### ISSUE THREAD

**Issue by srinivasreddy** [rust-lang/rust#37282] opened 2016-10-19 17:52 UTC
In the following program instead of underscore, i put a hyphen. The error message i received is misleading. I think it can be improved. What do you guys think?

```
fn main() {
   let integer = 2;
   match integer {
    2 => { println!("this is two");}
    - => { println!("This is Not two"); }
    }
}
```

```
srinivas@Srini:~/workspace/github/rust-exercises$ rustc 3.rs
3.rs:5:7: 5:9 error: expected pattern, found `=>`
3.rs:5     - => { println!("This is None"); }
             ^~
error: aborting due to 2 previous errors

```

Here is the [playpen](https://is.gd/y8fmKy)

**Comment by estebank** [comment] 2016-10-24 02:18
I think this is because it is expecting a number (the pattern it couldn't find) after the `-`. I believe this might have to be special cased to point at the `-` instead of the `=>`.

**Comment by estebank** [comment] 2018-02-10 02:45
Duplicate of #29586.

**Closed by estebank** 2018-02-10 02:45 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
