### ISSUE TITLE
failed to process buffered lint - actix-web

### ISSUE THREAD

**Issue by tuxiqae** [rust-lang/rust#81805] opened 2021-02-05 20:51 UTC
### Code
Not sure what is the code which caused that panic, since the code snippet the panic shows is the following:

```rs
Err(e) => log::error!("Can not set HOST header {}", e),
```

### Meta
I am running the `nightly` toolchain, I could not reproduce the bug under `stable`.

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1

```

### Error output

```
error: internal compiler error: failed to process buffered lint here
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/client/h1proto.rs:58:27
   |
58 |                 Err(e) => log::error!("Can not set HOST header {}", e),
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `actix-http`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

<details><summary><strong>-Z macro-backtrace enabled</strong></summary>
<p>

```
error: internal compiler error: failed to process buffered lint here
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.13/src/macros.rs:77:45
   |
72 | / macro_rules! error {
73 | |     (target: $target:expr, $($arg:tt)+) => (
74 | |         log!(target: $target, $crate::Level::Error, $($arg)+);
75 | |     );
76 | |     ($($arg:tt)+) => (
77 | |         log!($crate::Level::Error, $($arg)+);
   | |                                             ^
78 | |     )
79 | | }
   | |_- in this expansion of `log::error!`
   |
  ::: /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-2.2.0/src/client/h1proto.rs:58:27
   |
58 |                   Err(e) => log::error!("Can not set HOST header {}", e),
   |                             -------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18

```

</p>
</details>

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0:     0x7f71fa292de7 - std::backtrace_rs::backtrace::libunwind::trace::h8bc78f7bc1f75bdb
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f71fa292de7 - std::backtrace_rs::backtrace::trace_unsynchronized::ha4c961c9576f95ba
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f71fa292de7 - std::sys_common::backtrace::_print_fmt::hc20cfdc233d6eb02
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f71fa292de7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04bea14549780a0f
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f71fa303ebc - core::fmt::write::h3868db8542c90941
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/core/src/fmt/mod.rs:1096:17
   5:     0x7f71fa285612 - std::io::Write::write_fmt::h55dd75636eef6a5c
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/io/mod.rs:1568:15
   6:     0x7f71fa296d45 - std::sys_common::backtrace::_print::h6439e8525077c7da
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f71fa296d45 - std::sys_common::backtrace::print::h02b685f728ce3931
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f71fa296d45 - std::panicking::default_hook::{{closure}}::h7c29625065fafae1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:208:50
   9:     0x7f71fa2968a3 - std::panicking::default_hook::hba441710bb71f4d5
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:225:9
  10:     0x7f71faaeff6b - rustc_driver::report_ice::h6029ac9bafd12823
  11:     0x7f71ea5ac716 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hdff29729df1eb137
                               at /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1502:9
  12:     0x7f71ea57f729 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h244e8e5e0fc209e6
                               at /home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7f71fa297646 - std::panicking::rust_panic_with_hook::ha936eb00e51bc4d9
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:595:17
  14:     0x7f71fa297167 - std::panicking::begin_panic_handler::{{closure}}::hcd15140e0238536e
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:497:13
  15:     0x7f71fa2932ac - std::sys_common::backtrace::__rust_end_short_backtrace::hb13a021bb64823a1
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7f71fa2970c9 - rust_begin_unwind
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:493:5
  17:     0x7f71fa29707b - std::panicking::begin_panic_fmt::h3ef6798fa589483b
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:435:5
  18:     0x7f71fdaebf03 - rustc_errors::HandlerInner::flush_delayed::hb4ed3fcc7df94332
  19:     0x7f71fdaea7b4 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::hb549d70799c8423b
  20:     0x7f71fcecbdcb - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::h8f774d493b3f6ea3
  21:     0x7f71fcecf220 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h40a806974fc760e5
  22:     0x7f71fceccd8d - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::h66cca9dc757d4a25
  23:     0x7f71fcec9fd1 - rustc_span::with_source_map::h0b3994d7a2f67198
  24:     0x7f71fce93477 - rustc_interface::interface::create_compiler_and_run::h4d7ef2129059135c
  25:     0x7f71fcecaabf - std::sys_common::backtrace::__rust_begin_short_backtrace::hcb0be55fe1a86377
  26:     0x7f71fceb03ca - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0363f9b03bb4d9ca
  27:     0x7f71fa2a7b5a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8ffdf8dc1f37e360
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/alloc/src/boxed.rs:1488:9
  28:     0x7f71fa2a7b5a - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h74f6ec149ce6acc8
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/alloc/src/boxed.rs:1488:9
  29:     0x7f71fa2a7b5a - std::sys::unix::thread::Thread::new::thread_start::h565bef3956c58d58
                               at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/sys/unix/thread.rs:71:17
  30:     0x7f71fa1933e9 - start_thread
  31:     0x7f71fa0b0293 - __GI___clone
  32:                0x0 - <unknown>

error: internal compiler error: unexpected panic

```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-05 20:53
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-05 20:53 UTC
Labels: C-bug, I-ICE, T-compiler

**Comment by tuxiqae** [comment] 2021-02-05 20:55
Thanks for the hasty reply :)
