### ISSUE TITLE
Misinterprets Raw String Literals as Code When Writing to File

### ISSUE THREAD

**Issue by Ham3798** [rust-lang/rust#122586] opened 2024-03-16 07:55 UTC
I tried this code:

```rust
#[cfg(test)]
mod tests {
    use std::io::Write;
    use std::fs::{self, File};
    use std::path::Path;

    #[test]
    fn sample() {
        let zok_contract_path = Path::new(&format!("./zok/verifier/verify_credential.zok"));
let mut file = File::create(&zok_contract_path).expect("Failed to create zok contract file");
        writeln!(file, r#"import "hashes/sha256/512bitPacked" as sha256packed;
import "hashes/sha256/1024bitPadded" as sha256;
import "utils/pack/bool/nonStrictUnpack256" as unpack256bool;
import "utils/pack/u32/nonStrictUnpack256" as unpack256u;
import "utils/casts/u32_8_to_bool_256";

struct BabyJubJubParams {
	field JUBJUB_C;
	field JUBJUB_A;
	field JUBJUB_D;
	field MONT_A;
	field MONT_B;
	field[2] INFINITY;
	field Gu;
	field Gv;
}

const BabyJubJubParams BABYJUBJUB_PARAMS = BabyJubJubParams {
    // Order of the curve for reference: 21888242871839275222246405745257275088614511777268538073601725287587578984328
    JUBJUB_C: 8, // Cofactor
    JUBJUB_A: 168700, // Coefficient A
    JUBJUB_D: 168696, // Coefficient D

    // Montgomery parameters
    MONT_A: 168698,
    MONT_B: 1,

    // Point at infinity
    INFINITY: [0, 1],

    // Generator
    Gu: 16540640123574156134436876038791482806971768689494387082833631921987005038935,
    Gv: 20819045374670962167435360035096875258406992893633759881276124905556507972311
};

def add(field[2] pt1, field[2] pt2, BabyJubJubParams context) -> field[2] {

    field a = context.JUBJUB_A;
    field d = context.JUBJUB_D;

    field u1 = pt1[0];
    field v1 = pt1[1];
    field u2 = pt2[0];
    field v2 = pt2[1];

    field uOut = (u1*v2 + v1*u2) / (1 + d*u1*u2*v1*v2);
    field vOut = (v1*v2 - a*u1*u2) / (1 - d*u1*u2*v1*v2);

    return [uOut, vOut];
}

def onCurve(field[2] pt, BabyJubJubParams context) -> bool {
    field a = context.JUBJUB_A;
    field d = context.JUBJUB_D;

    field uu = pt[0] * pt[0];
    field vv = pt[1] * pt[1];
    field uuvv = uu * vv;

    assert(a * uu + vv == 1 + d * uuvv);
    return true;
}

def scalarMult(bool[256] exponent, field[2] pt, BabyJubJubParams context) -> field[2] {
    field[2] infinity = context.INFINITY;

    field[2] mut doubledP = pt;
    field[2] mut accumulatedP = infinity;

    for u32 i in 0..256 {
        u32 j = 255 - i;
        field[2] candidateP = add(accumulatedP, doubledP, context);
        accumulatedP = exponent[j] ? candidateP : accumulatedP;
        doubledP = add(doubledP, doubledP, context);
    }

    assert(onCurve(accumulatedP, context));
    return accumulatedP;
}

def orderCheck(field[2] pt, BabyJubJubParams context) -> bool {
    field cofactor = context.JUBJUB_C;
    assert(cofactor == 8);

    // Co-factor currently hard-coded to 8 for efficiency reasons
    // See discussion here: https://github.com/Zokrates/ZoKrates/pull/301#discussion_r267203391
    // Generic code:
    // bool[256] cofactorExponent = unpack256(cofactor);
    // field[2] ptExp = multiply(cofactorExponent, pt, context);
    field[2] mut ptExp = add(pt, pt, context); // 2*pt
    ptExp = add(ptExp, ptExp, context);    // 4*pt
    ptExp = add(ptExp, ptExp, context);    // 8*pt

    return !(ptExp[0] == 0 && ptExp[1] == 1);
}

def verifyEddsa(field[2] R, field S, field[2] A, u32[8] M0, u32[8] M1, BabyJubJubParams context) -> bool {
    field[2] G = [context.Gu, context.Gv];

    // Check if R is on curve and if it is not in a small subgroup. A is public input and can be checked offline
    assert(onCurve(R, context)); // throws if R is not on curve
    assert(orderCheck(R, context));

    u32[8] Rx = unpack256u(R[0]);
    u32[8] Ax = unpack256u(A[0]);
    bool[256] hRAM = u32_8_to_bool_256(sha256(Rx, Ax, M0, M1));

    bool[256] sBits = unpack256bool(S);
    field[2] lhs = scalarMult(sBits, G, context);

    field[2] AhRAM = scalarMult(hRAM, A, context);
    field[2] rhs = add(R, AhRAM, context);

    bool out = rhs[0] == lhs[0] && rhs[1] == lhs[1];
    return out;
}

// main 함수 위의 모든 함수들은 조크라테스 기본 라이브러리에서 제공되는 코드들입니다.
// 무슨 이유인지 라이브러리 임포트가 안돼서 수동으로 불러왔습니다.
def main(private field context_hash, private field age, private field alumni_of_hash, private field credential_subject_hash, private field exp_hash, private field id_hash, private field issuance_date_hash, private field issuer_hash, private field name_hash, private field student_number_hash, private field type_hash, private field[2] R, private field S) {
    // 첫 번째 4개 입력에 대한 해시 계산
    field[2] first_hash = sha256packed([context_hash, age, alumni_of_hash, credential_subject_hash]);
    
    // 두 번째 4개 입력에 대한 해시 계산
    field[2] second_hash = sha256packed([exp_hash, id_hash, issuance_date_hash, issuer_hash]);

    // 세 번째 3개 입력 및 첫 번째 해시의 첫 요소에 대한 해시 계산
    // 세 번째 해시 계산에는 name_hash, student_number_hash, type_hash 및 first_hash의 첫 요소를 사용
    field[2] third_hash = sha256packed([name_hash, student_number_hash, type_hash, first_hash[0]]);
    
    // 첫 번째, 두 번째, 세 번째 해시 결과의 두 번째 요소들을 다시 해시하여 최종 해시를 계산
    field[2] final_hash = sha256packed([second_hash[1], third_hash[1], third_hash[0], first_hash[1]]);
    
    // final_hash의 각 field 요소를 u32[8] 타입으로 변환
    u32[8] M0 = unpack256u(final_hash[0]);
    u32[8] M1 = unpack256u(final_hash[1]);

    // Eddsa 서명 검증
    // 서명 :(R, S), 공개키 : A, Memo : M0, M1
    // 공개키는 issuer의 pk 파일의 값으로 바꿀 것
    field[2] A = [14897476871502190904409029696666322856887678969656209656241038339251270171395, 16668832459046858928951622951481252834155254151733002984053501254009901876174];
    bool signature_valid = verifyEddsa(R, S, A, M0, M1, BABYJUBJUB_PARAMS);
    assert(signature_valid == true);

     // 나이가 20살 이상인지 검사
    assert(age >= 20);

    return;
}
"#).expect("Failed to write zok contract");
    }
}

```

I expected to see this happen: *The source code written in ZoKrates has been converted into a raw string format and written into a file.*

Instead, this happened: *The compiler decodes the raw string back into source code.*

### Meta

`rustc --version --verbose`:
```
<version>
rustc 1.78.0-nightly (b11fbfbf3 2024-02-03)
binary: rustc
commit-hash: b11fbfbf351b94c7eecf9e6749a4544a6d4717fa
commit-date: 2024-02-03
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 17.0.6
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
error: invalid format string: expected `'}'`, found `'f'`
  --> zokrates_credential_core/src/verifier.rs:78:2
   |
77 | struct BabyJubJubParams {
   |                         - because of this opening brace
78 |     field JUBJUB_C;
   |     ^ expected `'}'` in format string
   |
   = note: if you intended to print `{`, you can escape it using `{{`
```

</p>
</details>

**Comment by Nilstrieb** [comment] 2024-03-16 09:32
I'm not sure I entirely understand what you expected. You put the zok source code in the raw string literal, so the zok code will be written to the file. Or is something else happening for you?

**Comment by lukas-code** [comment] 2024-03-16 10:32
The `{` and `}` in your string are interpreted as [format string parameters](https://doc.rust-lang.org/nightly/std/fmt/index.html). Using a raw string literal (`r#"..."`) will not prevent this.

To fix this, you can either escape all `{` and `}` with  `{{` and `}}` in the format like this:
```rust
fn main() {
    println!(r#"struct BabyJubJubParams {{ /* ... */ }}"#);
    // output: struct BabyJubJubParams { /* ... */ }
}
```

or pass the string that you want to print as a parameter, instead of as the format string, like this:
```rust
fn main() {
    println!("{}", r#"struct BabyJubJubParams { /* ... */ }"#);
    // output: struct BabyJubJubParams { /* ... */ }
}
```

**Comment by the8472** [comment] 2024-03-16 11:09
If you don't want the formatting machinery use `file.write_all()` instead of `writeln!(file, ...)`

**Comment by jieyouxu** [comment] 2024-03-16 13:37
I'm going to close this issue as not-actionable since it is not a bug but rather intended behavior in regards to format strings. Multiple solutions to the problem described in the issue have also been provided.

**Closed by jieyouxu** 2024-03-16 13:37 UTC

**Comment by Ham3798** [comment] 2024-03-16 13:48
I understand, and I'm very grateful for your help!
