### ISSUE TITLE
Type inference regression with zipped iterators

### ISSUE THREAD

**Issue by larsluthman** [rust-lang/rust#29278] opened 2015-10-24 17:12 UTC
The following code compiles with Stable and Beta but not with Nightly on https://play.rust-lang.org/ as of 2015-10-24:

    fn main() {
        let mut output = vec![Vec::<i32>::new(); 5];
        let input = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
        for chunk in input.chunks(5) {
            for (i, o) in chunk.iter().zip(output.as_mut()) {
                o.push(*i);
            }
        }
        println!("{:?}", output);
    }

With Stable and Beta I get the correct output:

    [[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9]]

With Nightly I get the error message

    <anon>:6:13: 6:23 error: the type of this value must be known in this context
    <anon>:6             o.push(*i);

**Comment by eefriedman** [comment] 2015-10-24 17:58
This isn't a type inference regression; the problem is that Vec acquired a couple implementations of `AsMut`, and they're impossible to distinguish based on only the information "the result must implement IntoIter".

**Comment by bluss** [comment] 2015-10-24 20:50
AsMut added in #28663. Unfortunately the smallest new trait impls cause issues like this :disappointed: 

I don't want to shift the blame, but `AsMut` is a conversion trait, used for generics. It shouldn't have been in the prelude, because it's not intended to be called like this IMO.

More idiomatic would be to write `chunk.iter().zip(&mut output)`, which continues to compile.

**Comment by alexcrichton** [comment] 2015-10-25 17:48
triage: I-nominated

**Comment by brson** [comment] 2015-10-28 22:17
This is on beta now.

**Comment by alexcrichton** [comment] 2015-10-29 17:27
The libs team discussed this during triage today, and the conclusion was to close this for now. This is indeed breakage with the addition of `AsMut` for `Vec<T>`, but it is covered under our [API evolution policy](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md) which is to say that a local elaboration (e.g. type annotations) will fix this. If this becomes a widespread problem we will consider reverting, but for now it seems minor enough to not warrant that.

**Closed by alexcrichton** 2015-10-29 17:27 UTC
Labels: I-nominated, regression-from-stable-to-beta, T-libs
