### ISSUE TITLE
infinite loop during function argument check

### ISSUE THREAD

**Issue by kocsis1david** [rust-lang/rust#101097] opened 2022-08-27 19:09 UTC
I tried this code:
```rust
struct A;
struct B;
struct C;

fn f(
    a1: A,
    a2: A,
    b1: B,
    b2: B,
    c1: C,
    c2: C,
) {}

fn main() {
    f(
        C,
        C,
        A,
        A,
        B,
        B,
    );
}
```

I expected to see this happen: the compiler giving an error and showing a hint that order of the argument are not correct.

Instead, this happened: it stucks, waits forever.

### Meta

It happens on both stable and nightly.

Might be related to this: https://github.com/rust-lang/rust/issues/100478

**Comment by compiler-errors** [comment] 2022-08-28 03:56
Yeah, this is probably a dupe of that other one. cc @chenyukang

**Comment by chenyukang** [comment] 2022-08-29 10:44
> Yeah, this is probably a dupe of that other one. cc @chenyukang

Yes, it's another bug in the same function, but the root cause is different.
I will working on the same PR for this issue.

**Closed** 2022-09-12 08:46 UTC
Labels: C-bug
