### ISSUE TITLE
`./x.py build` fails on Debian testing (Bullseye) due to missing /usr/bin/python

### ISSUE THREAD

**Issue by liuw** [rust-lang/rust#84306] opened 2021-04-18 16:24 UTC
Debian has removed `/usr/bin/python` due to deprecation of Python2. To quote https://wiki.debian.org/Python:

```
NOTE: Debian testing (bullseye) has removed the "python" package and the '/usr/bin/python' symlink
due to the deprecation of Python 2. No packaged scripts should depend on the existence of '/usr/bin/python': if they do,
that is a bug that should be reported to Debian. You can use the 'python-is-python3' or 'python-is-python2'
packages to restore an appropriate '/usr/bin/python' symlink for third-party or legacy scripts.
```

I tried this code:

```rust
./x.py build
```

I expected to see this happen: Build successfully executed.

Instead, this happened: /usr/bin/python cannot be found.

This can be solved by installing either `python-is-python2` or `python-is-python3` as suggested by the Debian wiki page.

There are other scripts in tree which use `#!/usr/bin/env python`. I think it would be good to either fix these scripts to explicitly use a version of Python or document Debian's behaviour somewhere.

**Comment by jyn514** [comment] 2021-04-18 20:27
Duplicate of https://github.com/rust-lang/rust/issues/71818. Note that rustbuild is compatible with both python2 and python3 (although some features, like `download-ci-llvm`, only work with python3).

**Closed by jyn514** 2021-04-18 20:27 UTC
Labels: C-bug
