### ISSUE TITLE
CI: Bootstrap no longer documents compiler crates

### ISSUE THREAD

**Issue by fmease** [rust-lang/rust#117430] opened 2023-10-31 07:39 UTC
Bootstrap no longer documents any `rustc_*` / `compiler/` crates or `rustdoc` in CI.
[The index](https://doc.rust-lang.org/nightly/nightly-rustc/index.html) now only contains a meager 20 or so crates.
This has to have regressed fairly recently.

**Comment by Nemo157** [comment] 2023-10-31 11:08
It regressed in the latest nightly, we have CI tests on docs.rs checking for some of these and the last daily test succeeded.

**Comment by ChrisDenton** [comment] 2023-10-31 11:26
If I'm reading the commit history right there were a number of PRs that touched one of CI, bootstrap or rustdoc itself:

* #112463
* #116939
* #117267
* #117328
* #117376
* #117383

**Comment by Mark-Simulacrum** [comment] 2023-10-31 12:04
This appears to have regressed in #117328... but I'm pretty confused by that.

```
$ for commit in $(git log --first-parent --format=%H | head -n30); do echo $commit; curl -sI "https://ci-artifacts.rust-lang.org/rustc-builds/$commit/rustc-docs-nightly-x86_64-unknown-linux-gnu.tar.xz" | grep content-length; done
ffb7ed9fa420e9bcd98d84b431b2009445b7b967
content-length: 5454792
650991d62c3a2c80ba27009d06839adbb038bf5e
content-length: 5456880
a395214a3a88be976eec9256987d5eb6b3584bdc
content-length: 5454420
31bc7e2c47e82798a392c770611975a6883132c8
content-length: 5456600
236ac911de2f4b6210ba99e25c6c4843c9381a1a
content-length: 5454984
e6e931dda5fffbae0fd87c5b1af753cc95556880
content-length: 5468104
6d1fc53cf4f61b0dce5fc84cebae3b9fb8a45436
content-length: 5468832
e324cf0f73f09388d494986550f46dc9e12badd3
content-length: 5468796
91bbdd927a5e53a2fe126304fe8adbedf339616c
content-length: 5468436
1dfb6b162be402d8ca37e8aad4f58898b44e3a15
content-length: 5468796
bcb5798dd890a691644af9d371f3bd7fcc465584
content-length: 22395756
608e9682f0a6482903de8d3332770104a0ad943c
content-length: 22390916
ec2b311914a4880235862f3cd65fe24e92e6d3a5
content-length: 22391560
88ae8c93854a1a67c6c0a45971c7198477456c33
content-length: 22396416
83c9732e0c7e1cae5f039677da4c51ee1d9b19b0
content-length: 22393792
160fd3ceb5143100d4e06f324b02af1f9e786372
content-length: 22375124
bbcc1691a4646a6d2ebb2189bdff5b878407fbe6
```

**Comment by lqd** [comment] 2023-10-31 14:11
> This appears to have regressed in #117328... but I'm pretty confused by that.

Since this mostly "only" allowed #81746 to have an effect, it could be that the issue is in the original PR.

**Comment by Nilstrieb** [comment] 2023-10-31 15:10
cc @bjorn3 and also @onur-ozkan maybe you happen to have an idea too

**Comment by bjorn3** [comment] 2023-10-31 15:16
I don't have a clue how either PR could have affected building docs.

**Comment by onur-ozkan** [comment] 2023-10-31 15:22
I am painting my apartment at the moment. ☹️

![image](https://github.com/rust-lang/rust/assets/39852038/86e1644a-1862-497b-8ac0-e525a1cbb7d7)

I would do quick check between the recently merged PRs as there are not many. It seems not to be so hard to find and fix the problem. But I can only do that later tonight.. I don't have access to my computers right now.

**Comment by onur-ozkan** [comment] 2023-10-31 23:12
Ok, so the problem is when we use `cranelift` as a backend with llvm, documentation outputs generated by these backends seem to conflict with each other during the invocations. It appears that one of them(most likely cranelift) is not generating the compiler documentation. As we purge the previously generated documentation output at https://github.com/rust-lang/rust/blob/50be22964035027398754e54cd3a497efb00f83e/src/bootstrap/src/core/builder.rs#L1290

we end up with output that doesn't have the compiler documentation.

I am currently unsure of the exact reason why cranelift is causing this issue. I will open a temporary fix PR and investigate further once I get more time.

**Comment by RalfJung** [comment] 2023-11-02 06:34
Indeed the search at https://doc.rust-lang.org/nightly/nightly-rustc/ is completely useless right now. If a fix would take more than a day, reverting the offending PR should also be considered, given that those docs are quite crucial for rustc constributors.

**Comment by onur-ozkan** [comment] 2023-11-02 06:52
> Indeed the search at https://doc.rust-lang.org/nightly/nightly-rustc/ is completely useless right now. If a fix would take more than a day, reverting the offending PR should also be considered, given that those docs are quite crucial for rustc contributors.

Fix PR is already open at https://github.com/rust-lang/rust/pull/117471

**Comment by RalfJung** [comment] 2023-11-02 07:15
Yeah I've seen that, but I can't tell if that's the lowest-risk approach. :shrug: Reverting (or un-setting `CODEGEN_BACKENDS` on whatever builder builds the docs) is something we know will obviously work.

**Comment by onur-ozkan** [comment] 2023-11-02 07:34
I am quite sure that PR contains no risk, but I am fine with reverting codegen environment variable updates in the runner containers

**Comment by RalfJung** [comment] 2023-11-02 08:47
I'm fine either way but can't approve your PR since I don't understand the context of it. So if we can have it reviewed fast, fine, but otherwise - the revert is trivial to review.

**Comment by onur-ozkan** [comment] 2023-11-02 22:06
https://github.com/rust-lang/rust/pull/117471 did fix it locally, but seems didn't fix it on actual environment..

**Comment by onur-ozkan** [comment] 2023-11-02 22:20
To fix this, we can either disable cranelift on the gh action which we build nightly documentation or revert https://github.com/rust-lang/rust/pull/117328 until we find out and fix the problem of compiler documentations with cranelift.

**Comment by RalfJung** [comment] 2023-11-03 05:50
>  disable cranelift on the gh action step which we build nightly documentation

Which one is that?

**Comment by onur-ozkan** [comment] 2023-11-03 06:25
> > disable cranelift on the gh action step which we build nightly documentation
> 
> Which one is that?

I guess (never worked on the infra side before) these ones 

https://github.com/rust-lang/rust/blob/2429818b20e6e67edc7c9d2f33b2dc0e9087b924/.github/workflows/ci.yml#L537-L542

https://github.com/rust-lang/rust/blob/2429818b20e6e67edc7c9d2f33b2dc0e9087b924/.github/workflows/ci.yml#L661-L666

https://github.com/rust-lang/rust/blob/2429818b20e6e67edc7c9d2f33b2dc0e9087b924/.github/workflows/ci.yml#L160-L165

**Comment by RalfJung** [comment] 2023-11-03 06:59
Those steps just do the uploading, the docs are most likely created before. We need to figure out which *runner* is doing this and disable cranelift there.

**Comment by onur-ozkan** [comment] 2023-11-03 07:04
It's done in multiple place(creating and uploading). I think the question is which one is getting deployed to https://doc.rust-lang.org/nightly/nightly-rustc/index.html.

**Comment by RalfJung** [comment] 2023-11-03 07:04
It's been 3 days without docs, clearly this is not entirely trivial to fix. Let's revert.
https://github.com/rust-lang/rust/pull/117535

**Closed** 2023-11-03 12:43 UTC
Labels: regression-from-stable-to-nightly, T-bootstrap, A-docs, C-bug, A-contributor-roadblock

**Comment by lqd** [comment] 2023-11-04 08:39
The docs are back.

**Comment by ChrisDenton** [comment] 2023-11-04 08:45
While the immediate issue is addressed, do we need an issue to track the underlying problem?

**Comment by lqd** [comment] 2023-11-04 10:23
We could. At the same time, @bjorn3 and @onur-ozkan are also still working on this, e.g. in this [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/how.20to.20locally.20run.20the.20docker.20container) as it's quite important to fix. There's little chance we'll forget about this, and it should hopefully will be fixed very soon.

**Comment by onur-ozkan** [comment] 2023-11-04 10:31
The underlying problem is that symlinks are being dropped in a wrong way between invocations. I can easily fix this by copying the document outputs instead of linking them, but I would prefer to invest a couple more hours in fixing the linking issue rather than replacing it.
