### ISSUE TITLE
vec!([]) macro causes "the compiler unexpectedly panicked"

### ISSUE THREAD

**Issue by hoodie** [rust-lang/rust#25881] opened 2015-05-29 16:11 UTC
Hi, I used vec! the wrong way, and the compiler panicked.
rustc -V -> rustc 1.0.0-dev (built 2015-05-17)

Sorry, if this is a dup, I looked but did not see a report of this.

```rust
fn main() {
    vec!([]);
    println!("Hello, world!");
}
```

produces 
```sh
~/code/rust/panic/ § RUST_BACKTRACE=1 rustc src/main.rs                                                                                                                      (master*) [18:07:43]
<std macros>:3:1: 3:76 error: internal compiler error: cat_expr Errd
<std macros>:3 < [ _ ] > :: into_vec ( $ crate:: boxed:: Box:: new ( [ $ ( $ x ) , * ] ) ) )
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:1:1: 4:58 note: in expansion of vec!
src/main.rs:2:5: 2:14 note: expansion site
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /build/rust/src/rustc-1.0.0/src/libsyntax/diagnostic.rs:149

stack backtrace:
   1:     0x7ff56b5d5189 - sys::backtrace::write::h85e36588f6ec519ed4r
   2:     0x7ff56b5dce96 - panicking::on_panic::h6e154bbd20295560jrw
   3:     0x7ff56b5a01a2 - rt::unwind::begin_unwind_inner::h58d8677c31c147e6t6v
   4:     0x7ff568b94a0d - rt::unwind::begin_unwind::h17109019831519213513
   5:     0x7ff568b949a2 - diagnostic::SpanHandler::span_bug::he871130351e8da9fEqB
   6:     0x7ff56942f163 - session::Session::span_bug::hf5507d592e7c6099PDq
   7:     0x7ff56a3d1a5d - check::regionck::visit_expr::h55b582b9adf67231Yhd
   8:     0x7ff56a3ce9d0 - check::regionck::Rcx<'a, 'tcx>::visit_fn_body::h894f2218ba6ba28epUc
   9:     0x7ff56a448546 - check::check_bare_fn::h16e5c54944c58ce3twn
  10:     0x7ff56a4463a2 - check::CheckItemBodiesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h960d90c3a6588469wtn
  11:     0x7ff56a50a34a - check_crate::closure.38028
  12:     0x7ff56a5056e0 - check_crate::h16da0c29bfd97789XcC
  13:     0x7ff56bb0fa08 - driver::phase_3_run_analysis_passes::h7268293564f4d974nGa
  14:     0x7ff56baf0b05 - driver::compile_input::hf89ed7761a9a5930Qba
  15:     0x7ff56bbb1fd1 - run_compiler::h61cd16b138828888z4b
  16:     0x7ff56bbafc22 - boxed::F.FnBox<A>::call_box::h3676213088059194772
  17:     0x7ff56bbaf159 - rt::unwind::try::try_fn::h2238843044414567073
  18:     0x7ff56b646b28 - rust_try_inner
  19:     0x7ff56b646b15 - rust_try
  20:     0x7ff56bbaf408 - boxed::F.FnBox<A>::call_box::h6492341214887270608
  21:     0x7ff56b5dbd81 - sys::thread::create::thread_start::ha66925ca4f47d19baqv
  22:     0x7ff566067353 - start_thread
  23:     0x7ff56b235bfc - __clone
  24:                0x0 - <unknown>
```

**Comment by mitaa** [comment] 2015-06-02 11:05
This has apparently been fixed in nightly
```
<std macros>:3:1: 3:76 error: cannot determine a type for this expression: unconstrained type [E0101]
<std macros>:3 < [ _ ] > :: into_vec ( $ crate:: boxed:: Box:: new ( [ $ ( $ x ) , * ] ) ) )
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:1:1: 4:58 note: in expansion of vec!
<anon>:2:5: 2:14 note: expansion site
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by hoodie** [comment] 2015-06-02 12:55
\0/

**Comment by arielb1** [comment] 2015-06-23 13:09
Duplicate of #22897 etc.

**Closed by arielb1** 2015-06-23 13:09 UTC
Labels: I-ICE
