### ISSUE TITLE
panic compiling pkg-config

### ISSUE THREAD

**Issue by scottlamb** [rust-lang/rust#38213] opened 2016-12-07 04:43 UTC
The latest nightly panics when compiling the latest version of pkg-config (on a Raspberry Pi 2, running Raspbian Jessie).

I tried this code:

https://github.com/alexcrichton/pkg-config-rs
at master tip (commit 4e563eb953b4ee8c1e0a06defd49f3c1a803081f).

I expected to see this happen: a successful build.

Instead, this happened: a compiler panic. Here's the lowlight:

```
thread 'rustc' panicked at 'assertion failed: eps.windows(2).all(|w| w[0].cmp(self, &w[1]) != Ordering::Greater)', /buildslave/rust-buildbot/slave/nightly-dist-rustc-cross-host-linux/build/src/librustc/ty/context.rs:1525
```

## Meta

```
rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)
binary: rustc
commit-hash: daf8c1dfce3b448fc581cc319f64632ec22bd0e1
commit-date: 2016-12-05
host: armv7-unknown-linux-gnueabihf
release: 1.15.0-nightly
LLVM version: 3.9
```

Backtrace: [build-failure.txt](https://github.com/rust-lang/rust/files/635686/build-failure.txt)

**Comment by bluss** [comment] 2016-12-07 09:32
Thank you. Closing as a duplicate of #38213

**Closed by bluss** 2016-12-07 09:32 UTC
