### ISSUE TITLE
Detect Merge Conflict Text

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#36879] opened 2016-10-01 00:36 UTC
I saw a tweet about [git merge conflict text](https://twitter.com/badedgecases/status/781928309059969029) in source code, and wondered what the Rust compiler does. As such, I created a [play.rust-lang.org sample](https://is.gd/mrisrn).

It currently detects more than two equals in a row, doesn't know what it means, and bails. Specifically, it looks like this:

```
rustc 1.12.0 (3191fbae9 2016-09-23)
error: expected one of `!`, `+`, `->`, `::`, `>`, or `as`, found `==`
 --> <anon>:4:1
  |
4 | =======
  | ^^

error: aborting due to previous error
```

I propose that when this happens, the compiler should look for the git merge conflict issues, and if it finds it, give a specific error message related to what is actually happening.

The error message could show the start and end of the merge sections, and actually give searchable text for what this strange textual artifact is for those who've never seen it before.

For an example of how it'd look:

```
error: Merge conflict detected.
 --> <anon>:2:1
  |
2 |<<<<<<< HEAD
  |^^^^^^^^^^^^ Note: Beginning of commit HEAD here.
  |
4 | =======
  | ^^^^^^^ Note: Divider between commits HEAD and ab890fb here.
  |
5 |>>>>>>> ab890fb
  |^^^^^^^^^^^^^^^ Note: End of commit ab890fb here.

error: aborting due to previous error
```

The only con I can think of is that we're specifically caring about the semantics of one tool that isn't really related to Rust. But at the same time, git is widely used.

**Comment by solson** [comment] 2016-10-01 00:51
Or do other merge tools use similar marks?

**Comment by 8573** [comment] 2016-10-01 00:55
Hm, I do seem to recall that `<<<...===....>>>` notation predating Git.

**Comment by 8573** [comment] 2016-10-01 01:08
Looks like it dates back to RCS, or even earlier.

**Comment by Havvy** [comment] 2016-10-01 01:12
Alright, removed the "Git" part from this.

**Comment by 8573** [comment] 2016-10-01 01:15
Still, I think trying to detect a VCS (lazily and memoizedly) would be useful for giving the user more context.

**Comment by rkruppe** [comment] 2016-10-01 11:28
> Still, I think trying to detect a VCS (lazily and memoizedly) would be useful for giving the user more context.

Why? Since the format is apparently not specific to one VCS, the compiler can just say "merge conflict" and the user (if they are in a position to resolve the merge conflict) will presumably know which VCS they are using. Not to mention that a merge conflict marker remains a merge conflict marker when it lives outside a VCS directory &mdash; for example, because the source code was downloaded from `crates.io`. Add to that the work needed to implement this feature and the danger of the detection being overly brittle or slowing down compilation, and it's a clear :-1: for me.

**Comment by TimNN** [comment] 2016-10-01 12:07
In my personal opinion a functionality like this does not belong in the rust compiler. The current error message already identifies one of the three locations, which I think should be enough.

**Comment by arielb1** [comment] 2016-10-01 14:31
GCC returns the following error:
```
test.c:1:1: error: version control conflict marker in file
 <<<<<<< HEAD
 ^~~~~~~
```

**Comment by 8573** [comment] 2016-10-01 18:42
> >Still, I think trying to detect a VCS (lazily and memoizedly) would be useful for giving the user more context.
> Why?

While I still think it *could* be useful, I've failed to think of any feature for which it would be *necessary*, save one: giving the user VCS-specific tips or URLs of documentation re resolving merge conflicts — and of course rustc could instead (in e.g. its `--explain` text) merely give the user a list of such and have them pick.

I am and have been quite okay with a generic "merge conflict detected" message, although looking at GCC's above, I think I would prefer "merge conflict _marker_ detected", as it doesn't necessarily mean there's an actual merge conflict.

**Comment by jfirebaugh** [comment] 2016-10-09 17:29
Duplicate of #32059.

**Closed** 2016-10-10 04:20 UTC
Labels: A-diagnostics, A-parser
