### ISSUE TITLE
"Fallback" to i32/f32 in error messages involving numeric inference

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#26328] opened 2015-06-16 00:42 UTC
Currently error messages where the type of a variable is a integer variable or a float variable just put `_` in for the type like a regular inference variable. For straight type mismatch errors, the elaborated version prints out something like `an integral variable`, which is fine, but other error messages don't. Like `trait core::ops::Div<_> is not implemented for f64`.

Given that we have fallbacks to `i32` and `f32` for integer and float literals respectively, it might be worth error messages acting as if that fallback has happened. `trait core::ops::Div<i32> is not implemented for f64` is much more helpful, since it's fairly clear that the issue is that you're dividing a float by an integer.

**Comment by pnkfelix** [comment] 2015-06-16 11:26
dupe of #24770 ?

**Comment by alexcrichton** [comment] 2015-06-16 17:12
I'd agree this is a dupe.

**Closed by alexcrichton** 2015-06-16 17:12 UTC
Labels: A-diagnostics, E-easy
