### ISSUE TITLE
Crash compiling on nightly with no network connection

### ISSUE THREAD

**Issue by MichaelAquilina** [rust-lang/rust#72301] opened 2020-05-17 15:53 UTC
Running `cargo run` failed for me with the error message below. 

I later noticed that my internet was being unreliable (DNS requests seemed to be timing out). This might have the original problem that caused rust to be in this state. However even after the network recovered I seemed to be getting the same issue.

I've committed the code that was causing this issue here https://github.com/MichaelAquilina/npmviewer-rust/commit/efe132fab85bee43f58874a193a1db3fc0bfd3ba: 

```
$ cargo run
Compiling npmviewer-rust v0.1.0 (/home/michael/Development/npmviewer-rust)
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (a74d1862d 2020-05-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `npmviewer-rust`.

To learn more, run the command again with --verbose.
```

More detailed output with `RUST_BACKTRACE=1`

https://gist.github.com/MichaelAquilina/cf5abe8b05366c41724bd57513f6ff78

```
$ rustc --version
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
```

**Comment by MichaelAquilina** [comment] 2020-05-17 16:15
Running `cargo clean` seems to resolve the issue.

After some further research it seems likely that this issue is related to https://github.com/rust-lang/rust/issues/70924

**Comment by jonas-schievink** [comment] 2020-05-17 16:18
rustc does not contact the network, this is a duplicate of #70924

**Closed by jonas-schievink** 2020-05-17 16:18 UTC
