### ISSUE TITLE
Compile panic on Rust nightly when compiling Rocket version 0.5.0-rc.1

### ISSUE THREAD

**Issue by Bernie** [rust-lang/rust#93972] opened 2022-02-13 20:23 UTC
### Code

Compile panic occurred while compiling Rocket version 0.5.0-rc.1
(rocket = "0.5.0-rc.1")

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (0c292c966 2022-02-08) running on x86_64-unknown-linux-gnu
```

### Error output

```

error: internal compiler error: encountered ambiguity selecting `Binder(<response::stream::reader::ReaderStream<impl futures::Stream<Item = response::stream::raw_sse::RawLinedEvent>> as std::convert::From<impl futures::Stream<Item = response::stream::raw_sse::RawLinedEvent>>>, [])` during codegen, presuming due to overflow or prior type error
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:54:32

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (0c292c966 2022-02-08) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -Z macro-backtrace

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rocket`
```

<details><summary><strong>Backtrace</strong></summary>
<p>
```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1176:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display::<&str>
   3: <rustc_errors::HandlerInner>::flush_delayed
   4: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   6: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   7: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   8: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
   9: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by ehuss** [comment] 2022-02-13 20:30
Thanks for the report!  Closing as a duplicate of #93831.  This should be fixed on the latest nightly.

**Closed by ehuss** 2022-02-13 20:30 UTC
Labels: I-ICE, T-compiler, C-bug
