### ISSUE TITLE
borrow diagnostic of dbg! leaks implementation

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#128312] opened 2024-07-28 17:58 UTC
### Code

```Rust
fn main() {
    let s = String::from("hello");
    dbg!(s);
    drop(s);
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0382]: use of moved value: `s`
 --> src/main.rs:4:10
  |
2 |     let s = String::from("hello");
  |         - move occurs because `s` has type `String`, which does not implement the `Copy` trait
3 |     dbg!(s);
  |     ------- value moved here
4 |     drop(s);
  |          ^ value used here after move
  |
help: borrow this binding in the pattern to avoid moving the value
 --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:364:13
  |
36|             ref tmp => {
  |             +++

For more information about this error, try `rustc --explain E0382`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0382]: use of moved value: `s`
 --> src/main.rs:4:10
  |
2 |     let s = String::from("hello");
  |         - move occurs because `s` has type `String`, which does not implement the `Copy` trait
3 |     dbg!(s);
  |     ------- value moved here
4 |     drop(s);
  |          ^ value used here after move
  |
help: borrow here
  |
3 |     dbg!(&s);
  |
```

### Rust Version

```Shell
1.79.0
```

**Comment by fmease** [comment] 2024-07-29 01:19
Duplicate of #120327.
Fixed on nightly via #120990.

Nightly output:

```
error[E0382]: use of moved value: `s`
 --> bw.rs:4:10
  |
2 |     let s = String::from("hello");
  |         - move occurs because `s` has type `String`, which does not implement the `Copy` trait
3 |     dbg!(s);
  |     ------- value moved here
4 |     drop(s);
  |          ^ value used here after move
  |
help: consider borrowing instead of transferring ownership
  |
3 |     dbg!(&s);
  |          +
```

In the future please double-check that the issue hasn't already been fixed on nightly before submitting a new GH issue. Thanks!

**Closed by fmease** 2024-07-29 01:19 UTC
Labels: A-diagnostics, T-compiler
