### ISSUE TITLE
Confusing error message for methods in formatting.

### ISSUE THREAD

**Issue by ckarmann** [rust-lang/rust#11724] opened 2014-01-22 15:23 UTC
Someone asked this question on StackOverflow: http://stackoverflow.com/questions/21273648/how-do-you-use-the-plural-method-in-rust/21274149#21274149

I'm just learning Rust, so I tried to research the subject and I was confused by the error message from rustc: 

```
error: argument used to format with `d` was attempted to not be used for formatting
```

While I'm not a native English speaker, I can usually understand any technical english text. However I find this error message very difficult to parse. What does "attempted to not be used" mean ?

So, this issue is mainly about the error message: can it be made clearer? or am I just lacking more context to understand it?

As for the StackOverflow problem itself, shouldn't an argument be usable for both format tokens {:d} and {0, format, ... } ?

**Comment by steveklabnik** [comment] 2015-02-11 00:53
Triage: same message today.

**Comment by steveklabnik** [comment] 2016-03-04 17:41
Triage: no change

**Comment by doppioslash** [comment] 2016-07-25 23:39
Still there...

**Comment by jonathandturner** [comment] 2016-09-27 22:10
I don't get an error with this:

```rust
fn main() {
    println!("This page has been visited {} {:0$}.", 1, 2);
}
```

And for the original from so, I get:
```
error: invalid format string: expected `'}'`, found `','`
 --> /Users/jturner/Source/bad_error.rs:9:22
  |
9 |     let s1 = format!("This page has been visited {:d} {0, plural, one{time} other{times}}.", count);
  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Mark-Simulacrum** [comment] 2017-05-30 14:08
I guess this has been fixed now, or at least I can't reproduce. I'm going to go ahead and close this issue.

**Closed by Mark-Simulacrum** 2017-05-30 14:08 UTC
Labels: A-diagnostics, I-papercut, T-compiler
