### ISSUE TITLE
u128 alignment is incorrect on x86_64

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#54949] opened 2018-10-10 05:48 UTC
In C and C++, on x86_64 Linux, `alignof(__int128)` is equal to `16`. However, in Rust, `align_of::<u128>()` is equal to `8`.

C++: https://gcc.godbolt.org/z/YAq1XC
Rust: https://gcc.godbolt.org/z/QvZeqK

This will cause subtle UB if you ever try to use `i128`s across FFI boundaries; for example:

C++: https://gcc.godbolt.org/z/PrtHlp
Rust: https://gcc.godbolt.org/z/_SdVqD

**Comment by leonardo-m** [comment] 2018-10-10 08:27
See also: https://github.com/rust-lang/rust/issues/54341

**Comment by nagisa** [comment] 2018-10-10 12:35
Duplicate of #54341, yes.

**Closed by nagisa** 2018-10-10 12:35 UTC
