### ISSUE TITLE
Compiler error after moving some files

### ISSUE THREAD

**Issue by ViliusN** [rust-lang/rust#91739] opened 2021-12-10 10:32 UTC
### Code

It's a rather messy project, and I have been moving some files around, so it would just take too much work to isolate the code, sorry.

### Meta
`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.57.0 (Arch Linux rust 1:1.57.0-1)
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
cargo test -- --nocapture (in directory: /home/vilius/Life/lightsout/src)
   Compiling lightsout v0.1.0 (/home/vilius/Life/lightsout)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.57.0 (Arch Linux rust 1:1.57.0-1) running on x86_64-unknown-linux-gnu
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `lightsout`
warning: build failed, waiting for other jobs to finish...
error: build failed
Compilation failed.
```

**Comment by BGR360** [comment] 2021-12-21 04:04
Potential dupe of https://github.com/rust-lang/rust/issues/91696. See also https://github.com/rust-lang/rust/pull/91919.

@rustbot label +A-incr-comp

**Comment by workingjubilee** [comment] 2023-02-26 11:32
Closing assuming the previous "it's a duplicate" is correct.

**Closed by workingjubilee** 2023-02-26 11:32 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
