### ISSUE TITLE
Rustdoc: generated documentation doesn't include Sized

### ISSUE THREAD

**Issue by quixotrykd** [rust-lang/rust#75413] opened 2020-08-11 17:33 UTC
In generated Rustdoc documentation, it would make sense to show whether a type is `Sized` or not.

Looking at the documentation for [slice](https://doc.rust-lang.org/std/primitive.slice.html#synthetic-implementations) (which is !Sized) and [Cell](https://doc.rust-lang.org/std/cell/struct.Cell.html#synthetic-implementations) (which is Sized), we see no reference to `Sized` in either location.

DSTs may largely be second class citizens at the moment, but it would still be useful to surface this information in the docs.

As I see it, there's two options which make sense:
1. Simply show `Sized` on all Sized types.
2. Instead, show nothing on Sized types and show `!Sized` on non-Sized types.

The first option is more in line with the way that the rest of the traits are surfaced. but may be somewhat confusing (in that `Sized` is special because it's implied to be implemented, unless you specifically specify otherwise in trait bounds).

The second option is more in line with the way we think about `Sized` with respect to bounds, but also seems confusing in that negative trait bounds are not a supported feature.

**Comment by jyn514** [comment] 2020-11-04 05:22
Duplicate of https://github.com/rust-lang/rust/issues/24183

**Closed by jyn514** 2020-11-04 05:22 UTC
Labels: C-feature-request, T-rustdoc
