### ISSUE TITLE
Function call in static results in compiler panic

### ISSUE THREAD

**Issue by grantslatton** [rust-lang/rust#26289] opened 2015-06-14 05:35 UTC
See http://is.gd/0FO78Z

Code:

```
pub type TypeWithLifetime<'a> = Box<Fn() -> () + 'a>;

static static_closure : TypeWithLifetime<'static> = Box::new(|| {
    panic!()
});

fn main() {}
```

Error:

```
6:3 error: function calls in statics are limited to struct and enum constructors [E0015]
<anon>:4 static static_closure : TypeWithLifetime<'static> = Box::new(|| {
<anon>:5     panic!()
<anon>:6 });
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
```

**Comment by nagisa** [comment] 2015-06-14 09:03
Does not happen in a recent nightly, therefore I believe this can be closed.

**Comment by arielb1** [comment] 2015-06-14 16:51
Duplicate of #25180

**Closed by arielb1** 2015-06-14 16:51 UTC
