### ISSUE TITLE
bootstrap: Normal compiler errors should not panic rustbuild

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53379] opened 2018-08-15 09:00 UTC
When there is an error building rustc, there always is a 20-line wall of text below the actual error message:
```
Caused by:
  process didn't exit successfully: `/home/r/src/rust/rustc/build/bootstrap/debug/rustc --crate-name rustc_mir librustc_mir/lib.rs --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=2 -C metadata=ff181b58e43e5a7e -C extra-filename=-ff181b58e43e5a7e --out-dir /home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps --extern arena=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libarena-b8f9e6fb5ae336d7.so --extern bitflags=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libbitflags-3907cba388d41ef0.rlib --extern byteorder=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libbyteorder-8246be02936c9b1b.rlib --extern either=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libeither-0a515e87c8afea9e.rlib --extern graphviz=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libgraphviz-45ae4394366d07fd.so --extern log=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblog-b6c566856a1e65b9.rlib --extern log_settings=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblog_settings-f501f9d595863bbf.rlib --extern polonius_engine=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libpolonius_engine-c6e8cf18dad58451.rlib --extern rustc=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc-b308e2da12bfc8a3.so --extern rustc_apfloat=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_apfloat-165c205e2819b15f.rlib --extern rustc_data_structures=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_data_structures-8b624a6d6082b2ff.so --extern rustc_errors=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_errors-89eed8215142aadd.so --extern rustc_target=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_target-20eb47b9c402fee3.so --extern serialize=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-8c9bc9ee6cc9592f.so --extern serialize=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libserialize-8c9bc9ee6cc9592f.rlib --extern syntax=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax-64bbe8e4870170a3.so --extern syntax_pos=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libsyntax_pos-3b51f50aecba154c.so -L native=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/backtrace-sys-01a673445b66da02/out -L native=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/miniz-sys-3c585aa15bfc4e69/out` (exit code: 1)
command did not execute successfully: "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--features" " jemalloc" "--manifest-path" "/home/r/src/rust/rustc/src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1119:9
```
Things get even worse when `RUST_BACKTRACE` is enabled because one is debugging something in the compiler, and the stage 1 build panics -- then we get two backtraces.

At least in the default configuration, bootstrap should not panic when cargo failed, it should exit gracefully.

**Comment by Mark-Simulacrum** [comment] 2018-08-15 13:39
We should get this I think in 4ish weeks, the fix has landed in cargo but we don't plan to backport it to beta.

**Comment by Mark-Simulacrum** [comment] 2018-08-15 13:39
Well, we can fix the panic, that's separate.

**Comment by Mark-Simulacrum** [comment] 2018-08-15 15:30
The caused by and process didn't execute successfully lines take up space too and are printed by Cargo.

**Comment by RalfJung** [comment] 2018-08-15 19:37
Ah I see. Yeah the biggest space-eater here is the "process didn't exit successfully".

However, once you run with RUST_BACKTRACE, the fact that it panics is also more than just aesthetics (panics are for unexpected errors, a compile failure is not so unexpected) -- it means that two backtraces are shown, the lower one usually filling the entire screen already.

**Closed** 2018-11-19 16:59 UTC
