### ISSUE TITLE
Tracking issue for opt-level={s,z}

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#35784] opened 2016-08-18 14:59 UTC
Added in https://github.com/rust-lang/rust/pull/32386 these options are still unstable, this issue will track their progress to becoming stable!

**Comment by alexcrichton** [comment] 2016-08-18 15:00
Also note that https://github.com/rust-lang/cargo/pull/3007 is adding Cargo support, currently through `opt-level = "z"` and `"s"`, but as [pointed out](https://github.com/rust-lang/cargo/pull/3007#issuecomment-240583754) we may want more human readable names.

**Comment by whitequark** [comment] 2016-08-18 15:14
I don't even think there is a single word that describes what `-Oz` does. As far as I know it was first introduced in clang and selected for its closeness to `-Os` and connotations of compression, but this doesn't help at all when you need an immediately understandable token in Cargo.toml.

**Comment by matklad** [comment] 2016-08-19 09:03
`size`/`size-1` for `s` and `size-2` for `z`?

**Comment by Timmmm** [comment] 2016-10-24 12:06
@matklad is right, "s" and "z" are not clear at all. I had no idea what "z" even did until I looked it up. [Apparently](http://stackoverflow.com/a/15548189/265521) it is the same as "s" but without loop vectorisation. According to [the BSD man page](https://www.freebsd.org/cgi/man.cgi?query=clang++&sektion=1&manpath=FreeBSD+9.0-RELEASE) it is intended to reduce size even further.

I like the "size-1"/"size-2" idea.

**Comment by bholley** [comment] 2017-02-02 19:07
We are potentially interested in this for Gecko's integration of Rust code, see [1]. We'd need to do more measurements to determine if the performance impact is acceptable though.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1328497

**Comment by alexcrichton** [comment] 2017-02-02 21:28
@bholley thanks for the info! We haven't seen a lot of movement here in awhile and we've got support in Cargo/build scripts now, so I'd like to propose we stabilize this:

@rfcbot fcp merge

**Comment by nrc** [comment] 2017-02-03 00:37
IS this properly documented? That can come after we've approved for stability, right?

**Comment by alexcrichton** [comment] 2017-02-03 19:18
@nrc good point! I think we should definitely make sure it's documented at least in `--help` or the various man pages.

**Comment by nikomatsakis** [comment] 2017-02-07 06:01
@nrc yes, that should come before the final PR itself lands though.

**Comment by wycats** [comment] 2017-02-26 23:04
It seems like there was an open concern that these tokens (especially for Cargo) aren't very clear. Do we want to take a short at single-word tokens before stabilizing?

**Comment by alexcrichton** [comment] 2017-02-27 20:04
@wycats I'm not personally motivated to do so as this is such a niche feature it seems like it's not worth the effort, but others may feel differently.

**Comment by Timmmm** [comment] 2017-02-28 10:05
I feel differently! If I change the patch to `size-1`, and `size-2` would that be acceptable? Or is it too late since Cargo has already merged `s` and `z`? If so then we should probably stick with that but they should be properly documented since clearly very few people know what they mean.

**Comment by alexcrichton** [comment] 2017-03-01 17:39
@Timmmm I think we're definitely still able to change, we just might have to have a small period of time where we support everything to deprecate s/z

**Comment by wycats** [comment] 2017-03-01 21:25
@alexcrichton @Timmmm is there any particular reason that, for Cargo, we need more than just `"size"`. In practice, the main historical distinction between `s` and `z` was that `z` was OSX-specific, and gave you "definitely, for realz optimize for size."

As far as I can tell, Cargo really only needs a way for people to say "I want you to optimize for size, please" and having multiple different versions of "optimize for size" at the Cargo level seems likely to introduce more confusion than help.

I propose that we add `"size"` to Cargo, and not leak `"s"` and `"z"`. I think I feel the same way about `rustc` but don't have as strong of an opinion there.

**Comment by alexcrichton** [comment] 2017-03-01 22:16
Sounds plausible to me!

In that case sounds like there's work to do, so I'll cancel the FCP

@rfcbot fcp cancel

**Comment by Timmmm** [comment] 2017-03-05 17:51
@wycats That's not what `z` does, as far as I can tell. According to Clang's manual:

> `-Oz` Like `-Os` (and thus `-O2`), but reduces code size further.

Also see [my previous link](https://stackoverflow.com/questions/15548023/clang-optimization-levels/15548189#15548189).

By the way, there is also [yet another optimisation setting](https://clang.llvm.org/docs/CommandGuide/clang.html#code-generation-options)! `-Og`, which:

> `-Og` Like `-O1`. In future versions, this option might disable different optimizations in order to improve debuggability.

Sounds like it could be useful. I suggest `opt-level = "debug"` for that.

**Comment by chrivers** [comment] 2017-05-06 11:31
I came here because I wasn't sure what -Oz did - now I know. I would like to point out that "size1" and "size2" is not much better, imho. Ok, so there's a size difference. But which one is supposed to be smaller? The bigger number, because it tries more agressively to make it smaller, or the smaller number, for intuitive reasons?

I can see the parallel with O1, O2, O3 -> increasing optimization for speed, and S1, S2, S3 -> increasing optimization for size, but perhaps this should be made more explicit then? We can always keep "s", "o", and so on as shorthand aliases

**Comment by vorner** [comment] 2018-03-22 12:31
Hello

This seems to have gone to sleep. I mean, the name for it is important, but no discussion seems to be happening for like 9 months ‒ is it likely to move forward? As for me, I'd rather have the feature stabilized (I'm often aiming at devices with chronic lack of storage space), no matter the actual values used.

Or is it blocked on anything else beside choosing the right name?

**Comment by nikomatsakis** [comment] 2018-03-22 15:32
Side note: the crash in https://github.com/rust-lang/rust/issues/48967 only reproduces with -Os (probably an LLVM bug)

**Comment by japaric** [comment] 2018-04-26 21:56
Since the lastest LLVM upgrade rustc / LLVM does more agressive inlining. This results in increased binary size of embedded / no_std programs: a hundreds of bytes increase, or about a 7x increase, in the case of the smallest Cortex-M binary cf. #49260.

As we are shooting for embedded Rust on stable it would be great to also provide a way to optimize for size (which is pretty important for embedded applications that target resource constrained devices) on stable.

@alexcrichton What can we do to move this forward. Can we at least stabilize "s" on rustc? Cargo already allows `opt-level = "s"` in the Cargo.toml but `-C opt-level=s` requires a nightly toolchain.

@aturon is this being discussed as part of the Cargo profile revamp?

**Comment by alexcrichton** [comment] 2018-04-26 22:51
@japaric I think those optimizations have baked long enough that it should be fine to stabilize now personally!

**Closed** 2018-05-21 14:45 UTC
Labels: B-unstable, C-tracking-issue, T-compiler, T-dev-tools
