### ISSUE TITLE
NLL / MIR-borrowck regression in getopts

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#48225] opened 2018-02-15 05:18 UTC
Compiling `getopts` version `0.2.15` with `cargo build` succeeds. However, compiling the same version with `RUSTFLAGS='-Z borrowck=mir -Z nll -Z two-phase-borrows' cargo build` fails with the following errors:

```
error[E0503]: cannot use `state` because it was mutably borrowed
    --> src/lib.rs:1033:19
     |
978  |       let mut machine = |cont: &mut bool, (i, c): (usize, char)| {
     |  _______________________-
979  | |         let whitespace = if c.is_whitespace() { Ws }       else { Cr };
980  | |         let limit      = if (i - slice_start + 1) <= lim  { UnderLim } else { OverLim };
981  | |
...    |
1027 | |         *cont
1028 | |     };
     | |_____- borrow of `state` occurs here
...
1033 |       while cont && match state { B | C => true, A => false } {
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of borrowed `state`

error[E0503]: cannot use `state` because it was mutably borrowed
    --> src/lib.rs:1033:33
     |
978  |       let mut machine = |cont: &mut bool, (i, c): (usize, char)| {
     |  _______________________-
979  | |         let whitespace = if c.is_whitespace() { Ws }       else { Cr };
980  | |         let limit      = if (i - slice_start + 1) <= lim  { UnderLim } else { OverLim };
981  | |
...    |
1027 | |         *cont
1028 | |     };
     | |_____- borrow of `state` occurs here
...
1033 |       while cont && match state { B | C => true, A => false } {
     |                                   ^ use of borrowed `state`

error: aborting due to 2 previous errors
```

**Comment by Aaron1011** [comment] 2018-02-15 05:23
I'll need to investigate further, but I suspect that this may have the same root cause as https://github.com/rust-lang/rust/issues/47680.

In particular, [this line](https://github.com/rust-lang-nursery/getopts/blob/8ec597273183155d233d2ea974f250c75248264e/src/lib.rs#L982):

```rust
state = match (state, whitespace, limit) {
```

seems to fit the pattern of 'borrow variable, manipulate borrow, assign manipulated borrow back to original' that appears in the many examples in the above issue.

**Comment by Aaron1011** [comment] 2018-02-15 05:29
This minimized example seems to confirm it: ([playground](https://play.rust-lang.org/?gist=0d8c835385ca715fb864ff9009fbba5b&version=nightly)):

```rust
#![feature(nll)]

enum State {
    A
}

fn bar() {
    let mut state = State::A;

    let mut closure = || {
        state = match state {
            State::A => State::A,
        };
    };

    while match state {  State::A => false } {
        closure();
    }
}

fn main() {}
```

Removing `#![feature(nll)]` allows this snippet to compile.

**Comment by nikomatsakis** [comment] 2018-06-29 19:19
Hmm, I'm tagging this as NLL-deferred because #47680 is out of scope for the present borrow checker (tackling that is Polonius's job). However, it's interesting that this is a regression. My *guess* is that the old borrow checker was unsound here, but I'm not entirely sure.

**Comment by pnkfelix** [comment] 2018-12-19 16:15
The minimized example from the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=c0a9e7d227a6615cfd094bb7ab51cdb2)  works now?



@Aaron1011 do you know off hand whether the problem in getopts is still arising today? And also, is it only exposed by `#![feature(nll)`? (I.e. how does just the migration mode enabled via the 2018 edition behave)

----

Marking as NLL-complete for now, as well as E-needs-test and P-medium.

**Comment by pnkfelix** [comment] 2018-12-19 16:16
(also assigning to self to make the test and followup with @Aaron1011 )

**Comment by Aaron1011** [comment] 2018-12-20 05:57
@pnkfelix: Running `RUSTFLAGS='-Z borrowck=mir' cargo +nightly buil` still reproduces the original error.

**Comment by pnkfelix** [comment] 2018-12-21 16:31
Its also worth revisiting @nikomatsakis 's note that the fact this compiled under AST-borrowck may represent unsoundness there. Its certainly suspicious that the closure bound to `machine` is (clearly?) doing a mutable borrow of `state`, and there are calls to `machine` before and after a use of `state`.

**Comment by pnkfelix** [comment] 2018-12-21 16:39
ah I *think* the reduced test case compiles because it reduces the intervening "read" of `state` to `match state { State::A => false }` and it looks like MIR borrowck manages to ... treat that as a no-op?

If I put two variants into the `State` enum and actually use them to drive the loop condition, then we get the error I expect here ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7f841578783abe5ef25c73ee1eadd2ac)):

```rust
#![feature(nll)]

enum State {
    A,
    B
}

fn bar() {
    let mut state = State::A;
    let state_ref = &mut state;

    let mut closure = || {
        *state_ref = match *state_ref {
            _ => State::A,
        };
    };

    while match state { State::A => true, State::B => false } {
        closure();
    }
}

fn main() { 
    bar();
}
```

**Comment by pnkfelix** [comment] 2018-12-21 16:47
@nikomatsakis do you actually think this is a duplicate of #47680 ?

#47680 is a case where you have a factoring of an expression into a separate method.

This is, I think, describing a factoring into a closure that makes use of free variables rather than passing them anew. But I don't know if its reasonable to expect that to work...?

In other words, this fails to compile under NLL ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=123482a82700eee419ea7bde5e645272)):

```rust
#![feature(nll)]
fn main() {
    enum State { A, B }
    let mut state = State::A;
    let closure = || {
        state = match state {
            State::A => State::B,
            State::B => State::A,
        };
    };
    while match state { State::A => false, State::B => true } {
        closure();
    }
}
```

but this variant below will compile and run fine, because instead of having a single mut borrow captured by the closure in a free variable, I now create free mutable borrows at each call ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e5043fc7cd5c1ae01cfd10c84114897a)):

```rust
#![feature(nll)]
fn main() {
    enum State { A, B }
    let mut state = State::A;
    let closure = |s: &mut _| {
        *s = match *s {
            State::A => State::B,
            State::B => State::A,
        };
    };
    while match state { State::A => false, State::B => true } {
        closure(&mut state);
    }
}
```

**Comment by pnkfelix** [comment] 2018-12-21 16:49
nominating for discussion at next NLL meeting, in case @nikomatsakis and/or @rust-lang/wg-compiler-nll doesn't get around to resolving the question I posed in the previous comment before then.

**Comment by nikomatsakis** [comment] 2019-01-03 13:38
@pnkfelix Indeed, I do not see the "hallmark" of #47680, which I consider to be:

- one branch that creates an outlives relationship, but kills the loan,
- and one branch that does not create an outlives relationship.

That said, the examples I see here look to me like they ought not to compile. Moreover, they don't compile, even in 2015 Rust.

But this example *does* compile in 2015 but not 2018: (you also posted it)

```rust
enum State {
    A,
    B
}

fn bar() {
    let mut state = State::A;
    let state_ref = &mut state;

    let mut closure = || {
        *state_ref = match *state_ref {
            _ => State::A,
        };
    };

    while match state { State::A => true, State::B => false } {
        closure();
    }
}

fn main() { 
    bar();
}
```

This seems like a bug in 2015 Rust, though.

**Comment by nikomatsakis** [comment] 2019-01-03 15:15
I'm taking over this issue, but I think at this point it looks like it should just be closed as "no bug here".

**Comment by nikomatsakis** [comment] 2019-01-10 14:31
Nominating for discussion in the next NLL meeting. I think we likely should just close this.

**Comment by nikomatsakis** [comment] 2019-01-16 20:46
We discussed this in the NLL meeting today and decided everything was working as expected. Closing.

**Closed by nikomatsakis** 2019-01-16 20:46 UTC
Labels: A-NLL, C-bug, I-nominated, NLL-complete, P-high, T-compiler, T-dev-tools
