### ISSUE TITLE
rustc 1.45.0 hangs when compiling criterion in release mode

### ISSUE THREAD

**Issue by vandenoever** [rust-lang/rust#74585] opened 2020-07-21 11:52 UTC
### Code

When compiling the criterion crate, starting with commit [1154c045655bdf6a750d0c3a21b42824e6e996e5](https://github.com/bheisler/criterion.rs/commit/1154c045655bdf6a750d0c3a21b42824e6e996e5) rustc 1.45.0 hangs (> 12 hours). This happens on NixOS with AMD or Intel compiler. The distribution is NixOS with Rust from the master branch of nixpkgs.

```bash
git clone https://github.com/bheisler/criterion.rs.git
cd criterion.rs
cargo build --release
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 9.0
```

### Error output

The compiler hangs in the compile step for the crate.

Here is a flamegraph (made with HotSpot) of the running rustc process of 12 minutes of running after running for 12 hours.

[flamegraph](https://aws1.discourse-cdn.com/business5/uploads/rust_lang/original/3X/f/4/f4e5f845dff830e3dc9c9874c9c4b828e1fbaf5b.png)

**Comment by jonas-schievink** [comment] 2020-07-21 12:17
Cannot reproduce using the officially distributed artifacts. Seems like NixOS needs to fix their LLVM. Closing as not-our-bug.

**Closed by jonas-schievink** 2020-07-21 12:17 UTC
Labels: C-bug, I-ICE, T-compiler

**Comment by xfix** [comment] 2020-07-22 13:38
Can confirm this happens with staging rustc in nixpkgs.

**Comment by xfix** [comment] 2020-07-22 16:02
Doesn't happen if I build rustc with LLVM 10 instead of LLVM 9.
