### ISSUE TITLE
Is there a way to get notified when feature becames stable?

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#58179] opened 2019-02-05 06:40 UTC
In my personal projects I use stable compiler and prefer not to switch to nightly. There are few lines in my code like this:
```
// TODO: Use foo, when foo becames stable /*link to github*/
// Commented code
```

I usually use some workaround before feature becames stable. Is there an annotation or something which will give me warning, when feature became stable and encourage me to update my code?

It seems for me, good addition to have.

**Comment by nagisa** [comment] 2019-02-05 06:51
Subscribe to the corresponding [`C-tracking-issue`](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AC-tracking-issue) issues.

**Comment by nagisa** [comment] 2019-02-05 06:53
Oh and the Rust compiler *will* warn for most features that have been stabilised but still have a corresponding unnecessary `#![feature(...)]`. [Example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7dc4735ee496eaf6161a124b6b59b35f).

**Comment by In-line** [comment] 2019-02-05 07:16
Hey, thanks for the response, but IMHO I don't agree with the idea of closing this issue.

1) Subscribing to the C-tracking-issue issues and manually checking code for updates is a bad idea. I'm asking about automatic solution.
2) I don't use nightly and code requiring feature in the most cases isn't written. A workaround is used.
3) This is the example, hypothetic use of the annotation I desire.

```
#[maybe_feature(some_feature)]
fn example() { /*....*/ }
```

Prints nothing on stable, when feature becames stable it prints.
```
Warning: the feature `some_feature` has been stable since 1.26.0```

**Comment by In-line** [comment] 2019-02-05 07:17
Friendly ping @nagisa

**Comment by abonander** [comment] 2019-02-05 07:21
> Subscribe to the corresponding [`C-tracking-issue`](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AC-tracking-issue) issues.

Given how much discussion can occur in some of these tracking issue threads, this is probably too noisy to be useful for someone who's just interested in the stability status.

I second using the `feature` flag to watch the status but it'll really only provide consistent updates if you're testing the project in CI, otherwise you have to remember to build under the nightly compiler from time to time if you prefer stable like @In-line. You can use `cfg_attr` and a Cargo feature so that it doesn't always require nightly at least:

```rust
// `nightly` is not a special feature name but it's sort-of the convention
#![cfg_attr(feature = "nightly", feature(...))]
```

You can also add `#![deny(stable_features)]` to trigger a lint error for stabilized features so it "breaks" the build and notifies you (if you have Travis-CI set up to do that).

Travis-CI will build open-source projects for free regardless of if they're published on Crates.io. It's relatively easy to configure as well. Here's a basic `.travis.yml` assuming you're using `nightly` as your Cargo feature for this:

```yaml
language: rust
rust:
  - stable
  - nightly
matrix:
  # this prevents the entire repostory's build status from being marked as failed
  # it depends on whether you want stabilized features to loudly notify you or not
  - allow_failures:
      - rust: nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  # this is how we test the `nightly` feature
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo build --features "nightly"; fi
```

**Comment by In-line** [comment] 2019-02-05 07:47
Thanks, for provided solution, but I don't like idea of relying on `nightly` builds, because they can fail. I'm sticking with the opinion to have dedicated annotation for this thing.

**Comment by hellow554** [comment] 2019-02-05 08:05
Reading the release notes also helps 😶

**Comment by estebank** [comment] 2019-02-05 09:59
It could make sense to have a dashboard view that collects the stability information for all features, as we already collect in the code meta information about stability state, since which version and tracking ticket information in order to provide error diagnostics. Having an analogous page to the [Error Index](https://doc.rust-lang.org/error-index.html) for features makes sense to me.

**Comment by jonas-schievink** [comment] 2019-02-05 10:20
Instead of subscribing to the tracking issue, you can also use https://tellmewhenitcloses.com to get *one* email when the issue is closed (which happens when the feature is stabilized).

**Comment by steveklabnik** [comment] 2021-01-27 20:26
Triage: I'm not sure that a ticket is the way to track this, or if this is something the team ever plans on doing, exactly.

**Comment by jonas-schievink** [comment] 2021-01-27 20:39
We already have:

* A detailed changelog listing all stabilized features
* A blog post explaining the most impactful new features
* Tracking issues that are closed when a feature is stabilized in the nightly channel
  * GitHub now natively supports subscribing only to the "closed" event
* Milestones that each PR is assigned to, which lets you see the first version containing it

I think that's enough options, and given that there wasn't a single update on this issue for 2 years, it seems that there isn't much demand either, so closing.

**Closed by jonas-schievink** 2021-01-27 20:39 UTC
Labels: T-release

**Comment by janpaul123** [comment] 2021-06-24 03:32
I'd actually like to add a +1 for a feature like this. If you have a large codebase it can be hard to keep track of which lines of code to change when a feature becomes stable, so it would be great if there's some mechanism to fail the build if the current Rust version has stabilized a feature. Something like `#[feature_is_stable(my_feature)]` or whatever would be nice.

For now @abonander has a fine workaround, I'll use that, but it is a little hacky.

**Comment by jonas-schievink** [comment] 2021-06-24 11:44
> it would be great if there's some mechanism to fail the build if the current Rust version has stabilized a feature.

That's what `#![deny(stable_features)]` does, so I'm not sure what you're asking for

**Comment by janpaul123** [comment] 2021-06-24 16:44
> That's what #![deny(stable_features)] does, so I'm not sure what you're asking for

Not quite. Let me explain my use case in more detail.

So, say I work on a production application, so I don't really want to run the nightly compiler much at all. I do have a CI system set up that runs a (stable) `cargo build` and `cargo test` and so on.

Now, I need to use the [memoffset](https://crates.io/crates/memoffset) crate for something. It unfortunately has a runtime cost, but look at that, it has experimental compile-time support, cool! However, since I work on a production application and don't want to use unstable feature or the nightly compiler, I can't use it yet..

![Screen Shot 2021-06-24 at 9 32 56 AM](https://user-images.githubusercontent.com/177461/123300443-6f90a000-d4cf-11eb-8d9b-738a8781c356.png)

Now, I could of course subscribe to the 4 relevant unstable features on Github, or keep some sort of document about which unstable features will unlock which things for me. But now take this scenario times one hundred, and maybe throw in a whole team of engineers working on this codebase — it becomes hard to manage this manually.

So let's look at the automated mechanisms that we have at our disposal. What if we write something like:
```rust
#![deny(stable_features)]
#![feature(const_ptr_offset_from, const_maybe_uninit_as_ptr, const_raw_ptr_deref, const_refs_to_cell)]
```
That crashes immediately, since I'm not using nightly! And I don't want to use nightly! So ideally we would have something similar to this that would crash when all these features are available in stable, but which doesn't crash compilation in stable when they are not.

For now, @abonander's suggestion is workable, though a little hacky. We add a nightly build to our CI system _just_ for this purpose, and we also add a "nightly" feature to our crate (or in my case, multiple crates), also _just_ for this purpose, so that we can write this:

```
#![deny(stable_features)]
#![cfg_attr(feature = "nightly", feature(const_ptr_offset_from, const_maybe_uninit_as_ptr, const_raw_ptr_deref, const_refs_to_cell))]
```

All this does is make sure that in CI, this special nightly build will fail once one of these features becomes available, so someone on the team can remove it from the list. When the list is empty, we can switch to compile-time `offset_of!` in memoffset, hurray! 🙂

I hope this makes sense!

**Comment by estebank** [comment] 2021-06-25 00:43
> I don't want to use nightly!

Just in case you are not aware, `rustup` lets you install multiple versions and you can invoke a specific version using `+version`. So if you have stable installed and set as the default, nothing changes, but if you use `rustup toolchain add nightly` then you can do `rustc +nightly foo.rs` or `cargo +nightly run`, without it affecting your other workflows.

**Comment by janpaul123** [comment] 2021-06-29 21:22
> Just in case you are not aware, `rustup` lets you install multiple versions and you can invoke a specific version using `+version`. So if you have stable installed and set as the default, nothing changes, but if you use `rustup toolchain add nightly` then you can do `rustc +nightly foo.rs` or `cargo +nightly run`, without it affecting your other workflows.

Yeah, that's what I'm basically doing right now — I run a nightly build in CI just for the purpose of getting notified when features hit stable. So that's a workaround for now, but not a great user experience.

**Comment by peter-lyons-kehl** [comment] 2025-11-25 23:40
@In-line  and @janpaul123 GitHub now has "Customize" link near the Subscribe button, so you can choose to get notifications only when a tracking issue is closed and/or re-opened.
