### ISSUE TITLE
Regression in helpful compiler error message when working with lifetimes

### ISSUE THREAD

**Issue by petergarnaes** [rust-lang/rust#66406] opened 2019-11-14 07:45 UTC
So I have the following code:
```
struct Article {
    proof_reader: ProofReader,
}

struct ProofReader {
    name: String,
}

pub trait HaveRelationship<To> {
    fn get_relation(&self) -> To;
}

impl HaveRelationship<&ProofReader> for Article {
    fn get_relation(&self) -> &ProofReader {
        &self.proof_reader
    }
}
```
Which on the stable compiler gives this helpful error message:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter in generic type due to conflicting requirements
  --> src/main.rs:14:5
   |
14 |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 14:5...
  --> src/main.rs:14:5
   |
14 | /     fn get_relation(&self) -> &ProofReader {
15 | |         &self.proof_reader
16 | |     }
   | |_____^
note: ...but the lifetime must also be valid for the lifetime '_ as defined on the impl at 13:23...
  --> src/main.rs:13:23
   |
13 | impl HaveRelationship<&ProofReader> for Article {
   |                       ^
   = note: ...so that the method type is compatible with trait:
           expected fn(&Article) -> &ProofReader
              found fn(&Article) -> &ProofReader
```
Yet on the nightly compiler the compiler error does not inform me about lifetimes, but tells me the signature needs to be what it already is:
```
error: `impl` item signature doesn't match `trait` item signature
  --> src/main.rs:14:5
   |
10 |     fn get_relation(&self) -> To;
   |     ----------------------------- expected fn(&Article) -> &ProofReader
...
14 |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found fn(&Article) -> &ProofReader
   |
   = note: expected `fn(&Article) -> &ProofReader`
              found `fn(&Article) -> &ProofReader`
```
[playground stable version](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=313facbea2943615fb338e2ddff03e07)
[playground nightly version](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f62a2c2bf90b45390e20be345141ea52)

**Comment by jonas-schievink** [comment] 2019-11-14 11:17
Happens on beta too

**Comment by estebank** [comment] 2019-11-14 19:16
For what is worth, the [correct code would be closer to](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a9952985c9126cfdc588c0429f8961fa):

```rust
pub trait HaveRelationship<'a, To: 'a> {
    fn get_relation(&'a self) -> To;
}

impl<'a> HaveRelationship<'a, &'a ProofReader> for Article {
    fn get_relation(&'a self) -> &'a ProofReader {
        &self.proof_reader
    }
}
```

The error is not _incorrect_, as there _is_ a discrepancy between the `trait` and the `impl`, but it should provide more information in this case, particularly to show that the lifetimes in `expected` and `found` are _not_ evaluated the same.

**Comment by estebank** [comment] 2019-11-14 19:21
This is caused by #65068. I believe this is now a duplicate of #41343.

CC @nikomatsakis do you have any ideas of what the appropriate output should be for these cases?

**Comment by pnkfelix** [comment] 2019-11-21 13:40
pnkfelix: triage: P-medium, removing nomination

**Comment by nikomatsakis** [comment] 2020-01-09 15:50
I don't think it's necessarily possible to tell what the correct code is here, but I would guess that

```rust
pub trait HaveRelationship<To> {
    fn get_relation(&self) -> &To;
}

impl HaveRelationship<&ProofReader> for Article {
    fn get_relation(&self) -> &ProofReader {
        &self.proof_reader
    }
}
```

is closer to the mark.

**Comment by nikomatsakis** [comment] 2020-01-09 15:55
Another good version:

```rust
struct Article {
    proof_reader: ProofReader,
}

struct ProofReader {
    name: String,
}

pub trait HaveRelationship<To> {
    fn get_relation(self) -> To;
}

impl<'a> HaveRelationship<&'a ProofReader> for &'a Article {
    fn get_relation(self) -> &'a ProofReader {
        &self.proof_reader
    }
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by nikomatsakis** [comment] 2020-01-09 15:55
In both cases, the principle is the same: move the `&` to the same place, whether that be the impl header, or the fn definition (in the trait).

**Comment by nikomatsakis** [comment] 2020-01-09 15:57
This version of the code also works, but it seems more complex than both of the above versions and it doesn't allow anything in particular that they don't, as far as I know. It still doesn't require the `To: 'a` annotation, though, @estebank:

```rust
struct Article {
    proof_reader: ProofReader,
}

struct ProofReader {
    name: String,
}

pub trait HaveRelationship<'a, To> {
    fn get_relation(&'a self) -> To;
}

impl<'a> HaveRelationship<'a, &'a ProofReader> for Article {
    fn get_relation(&'a self) -> &'a ProofReader {
        &self.proof_reader
    }
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by estebank** [comment] 2020-01-09 17:20
I feel that the first of the offered suggestions makes the most sense for the general case, changing the signature consume `Self` feels more drastic.

**Comment by estebank** [comment] 2020-01-09 23:31
I would rather not provide a structured suggestion for this case. What prose would you recommend here @nikomatsakis that would be suitable for a label on `To`'s definition or as a `note`?

**Comment by estebank** [comment] 2020-02-17 02:27
What do you think about this output?

```
error: `impl` item signature doesn't match `trait` item signature
  --> file5.rs:37:5
   |
31 | pub trait Bar<To, Fr> {
   |               --  -- this type parameter might not have a lifetime compatible with the `impl`
   |               |
   |               this type parameter might not have a lifetime compatible with the `impl`
32 |     fn get_relation(&self) -> (To, Fr);
   |     -----------------------------------
   |     |                          |   |
   |     |                          |   you might want to borrow this type parameter in the trait to make it match the `impl`
   |     |                          you might want to borrow this type parameter in the trait to make it match the `impl`
   |     expected `fn(&Article) -> (&ProofReader, &usize)`
...
37 |     fn get_relation(&self) -> (&ProofReader, &usize) {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found `fn(&Article) -> (&ProofReader, &usize)`
   |
   = note: expected `fn(&Article) -> (&ProofReader, &usize)`
              found `fn(&Article) -> (&ProofReader, &usize)`
   = note: the lifetime requirements from the `trait` could not be satisfied by the `impl`
   = help: verify the lifetime relationships in the `trait` and `impl` between the `self` argument, the other inputs and its output
```

**Comment by nikomatsakis** [comment] 2020-02-24 15:57
@estebank sorry for lack of replies, i've enqueued the PR back into my task queue...my first thought when reading the comments above are that it seems pretty complex, but I don't have any constructive ideas how to improve yet :)

**Comment by estebank** [comment] 2020-02-25 03:38
@nikomatsakis fair. Keep in mind that the case above is exercising a more complex case than the more likely one:

```
error: `impl` item signature doesn't match `trait` item signature
  --> file5.rs:37:5
   |
31 | pub trait Bar<To> {
   |               -- this type parameter might not have a lifetime compatible with the `impl`
32 |     fn get_relation(&self) -> To;
   |     -----------------------------
   |     |                         |
   |     |                         you might want to borrow this type parameter in the trait to make it match the `impl`
   |     expected `fn(&Article) -> &ProofReader`
...
37 |     fn get_relation(&self) -> &ProofReader {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ found `fn(&Article) -> &ProofReader`
   |
   = note: expected `fn(&Article) -> &ProofReader`
              found `fn(&Article) -> &ProofReader`
   = note: the lifetime requirements from the `trait` could not be satisfied by the `impl`
   = help: verify the lifetime relationships in the `trait` and `impl` between the `self` argument, the other inputs and its output
```

It is also difficult because anything I remove I feel like I'm hiding useful information.

**Comment by nikomatsakis** [comment] 2020-02-25 19:58
@estebank I think this comment in particular

> you might want to borrow this type parameter in the trait to make it match the `impl`

might be confusing to folks. Can we maybe just say "you might want to change this return type to make it match the `impl`"?

**Closed** 2020-05-30 03:24 UTC
Labels: A-diagnostics, A-lifetimes, C-bug, D-confusing, D-papercut, P-medium, T-compiler, regression-from-stable-to-stable
