### ISSUE TITLE
format!() sometimes ignores width while formatting Debug

### ISSUE THREAD

**Issue by xpe** [rust-lang/rust#87905] opened 2021-08-10 03:17 UTC
I tried this code:

```rust
// https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=be8ab0a90dce4f0e53f964e41a4ae89e
fn main() {
    println!("'{:5?}'", 1);
    println!("'{:w$?}'", 2, w=5);
    println!("'{:5}'", "3");
    println!("'{:w$}'", "4", w=5);
    println!("'{:5?}'", "5");
    println!("'{:w$?}'", "6", w=5);
}
```

I expected to see this happen:

```
'    1'
'    2'
'3    '
'4    '
'"5"  '
'"6"  '
```

Instead, this happened:

```
'    1'
'    2'
'3    '
'4    '
'"5"'
'"6"'
```

To summarize, `println!()` / `format!()` ignores width while formatting Debug in some cases but not others.

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-apple-darwin
release: 1.54.0
LLVM version: 12.0.1
```

I confirmed the unexpected behavior also happens in beta and nightly:
* [beta (playground)](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=be8ab0a90dce4f0e53f964e41a4ae89e)
* [nightly (playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=be8ab0a90dce4f0e53f964e41a4ae89e)

### See Also

* [Module std::fmt](https://doc.rust-lang.org/std/fmt/index.html)
* `format!()` macro : [Macro: std::format](https://doc.rust-lang.org/std/macro.format.html)

**Comment by oli-obk** [comment] 2021-09-17 06:49
closing as duplicate of #30164

**Closed by oli-obk** 2021-09-17 06:49 UTC
Labels: C-bug
