### ISSUE TITLE
LLVM assertion with tests on Windows

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#31501] opened 2016-02-08 23:34 UTC
Rust on msys2 configured with `./configure --prefix=/home/John/rust-install --enable-llvm-assertions --enable-debuginfo --enable-debug --enable-debug-assertions`

```
$ make check -j4
cfg: version 1.8.0-dev (26105b1a3 2016-02-08)
cfg: build triple x86_64-pc-windows-gnu
cfg: host triples x86_64-pc-windows-gnu
cfg: target triples x86_64-pc-windows-gnu
cfg: disabling rustc optimization (CFG_DISABLE_OPTIMIZE)
cfg: enabling debug assertions (CFG_ENABLE_DEBUG_ASSERTIONS)
cfg: enabling debuginfo (CFG_ENABLE_DEBUGINFO)
cfg: host for x86_64-pc-windows-gnu is x86_64
cfg: os for x86_64-pc-windows-gnu is pc-windows-gnu
cfg: disabling C++ optimization (CFG_DISABLE_OPTIMIZE_CXX)
cfg: no good valgrind for x86_64-pc-windows-gnu
cfg: using CC=gcc (CFG_CC)
cfg: disabling valgrind run-pass tests
cfg: including test rules
cfg: lexer tooling not available, skipping lexer test...
Warning: the console output code page is not UTF-8, some tests may fail. Use `cmd /c "chcp 65001"` to setup UTF-8 code page.
cp: x86_64-pc-windows-gnu/stage2/bin/compiletest.exe
maketest: compiler-lookup-paths-2
maketest: compiler-rt-works-on-mingw
maketest: crate-data-smoke
maketest: codegen-options-parsing
----- X:/Programmer/msys64/home/John/rust/src/test/run-make/codegen-options-parsing/ --------------------
------ stdout ---------------------------------------------
make[1]: Entering directory '/home/John/rust/src/test/run-make/codegen-options-parsing'
#Option taking a number
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C codegen-units dummy.rs 2>&1 | \
        grep 'codegen option `codegen-units` requires a number'
error: codegen option `codegen-units` requires a number (C codegen-units=<value>)
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C codegen-units= dummy.rs 2>&1 | \
        grep 'incorrect value `` for codegen option `codegen-units` - a number was expected'
error: incorrect value `` for codegen option `codegen-units` - a number was expected
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C codegen-units=foo dummy.rs 2>&1 | \
        grep 'incorrect value `foo` for codegen option `codegen-units` - a number was expected'
error: incorrect value `foo` for codegen option `codegen-units` - a number was expected
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C codegen-units=1 dummy.rs
#Option taking a string
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C extra-filename dummy.rs 2>&1 | \
        grep 'codegen option `extra-filename` requires a string'
error: codegen option `extra-filename` requires a string (C extra-filename=<value>)
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C extra-filename= dummy.rs 2>&1
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C extra-filename=foo dummy.rs 2>&1
#Option taking no argument
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C lto= dummy.rs 2>&1 | \
        grep 'codegen option `lto` takes no value'
error: codegen option `lto` takes no value
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C lto=1 dummy.rs 2>&1 | \
        grep 'codegen option `lto` takes no value'
error: codegen option `lto` takes no value
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C lto=foo dummy.rs 2>&1 | \
        grep 'codegen option `lto` takes no value'
error: codegen option `lto` takes no value
PATH="/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing:/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin;/X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/llvm/Release+Asserts/lib:/mingw64/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/bin:/c/Program Files (x86)/IntelSWTools/compilers_and_libraries_2016.1.146/windows/mpi/intel64/bin:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/mpirt:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32_win/compiler:/c/ProgramData/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files (x86)/CMake/bin:/c/Users/John/AppData/Local/atom/bin:/c/Program Files/TortoiseGit/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Rust nightly 1.6/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/IntelSWTools/Trace Analyzer and Collector/9.1.2.024/dll:/c/Ruby/bin:/c/Users/John/AppData/Local/atom/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/stage2/bin/rustc.exe --out-dir /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L /X/Programmer/msys64/home/John/rust/x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing -L native=X:Programmermsys64homeJohnrustx86_64-pc-windows-gnullvmRelease+Asserts/lib -C lto dummy.rs
Makefile:4: recipe for target 'all' failed
make[1]: Leaving directory '/home/John/rust/src/test/run-make/codegen-options-parsing'

------ stderr ---------------------------------------------
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: X:\Programmer\msys64\home\John\rust\x86_64-pc-windows-gnu\stage2\bin\rustc.exe
File: X:/Programmer/msys64/home/John/rust/src/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp, Line 724

Expression: Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."
make[1]: *** [all] Error 3

------        ---------------------------------------------

/home/John/rust/mk/tests.mk:1063: recipe for target 'x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing-2-T-x86_64-pc-windows-gnu-H-x86_64-pc-windows-gnu.ok' failed
make: *** [x86_64-pc-windows-gnu/test/run-make/codegen-options-parsing-2-T-x86_64-pc-windows-gnu-H-x86_64-pc-windows-gnu.ok] Error 2
make: *** Waiting for unfinished jobs....
maketest: compile-stdin
maketest: crate-name-priority
maketest: c-static-dylib
```

**Comment by dotdash** [comment] 2016-02-09 09:11
Closing as a dupe of #25270, thanks for reporting it though!

**Closed by dotdash** 2016-02-09 09:11 UTC
