### ISSUE TITLE
rust-lldb gives 'no locations (pending)' when trying to set a breakpoint on macOS Sierra

### ISSUE THREAD

**Issue by fusionbeam** [rust-lang/rust#40665] opened 2017-03-20 07:02 UTC
> lldb-360.1.70
> rustc 1.17.0-nightly (0aeb9c129 2017-03-15)

---
```
bash-3.2$ rust-lldb ./target/debug/bptree --debug
(lldb) command source -s 0 '/tmp/rust-lldb-commands.DxGpv8'
Executing commands in '/tmp/rust-lldb-commands.DxGpv8'.
(lldb) command script import "/Users/ra/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/lldb_rust_formatters.py"
(lldb) type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
(lldb) type category enable Rust
(lldb) target create "./target/debug/bptree"
Current executable set to './target/debug/bptree' (x86_64).
(lldb) breakpoint set -f src/main.rs -l 7
```
---

followed this guide: http://asquera.de/blog/2017-03-03/setting-up-a-rust-devenv/

--- is this a known issue? any pointers on a workaround? 
thanks,
rares

**Comment by Mark-Simulacrum** [comment] 2017-06-13 15:46
I cannot reproduce with the versions given below, and I think I recall lldb 360 being buggy in general, so I'm going to close this.

```
$ rust-lldb -v
lldb-370.0.42
  Swift-3.1
$ rustc -vV
rustc 1.19.0-nightly (cfb5debbc 2017-06-12)
binary: rustc
commit-hash: cfb5debbcb610eae16e8c5602416930f20fefa39
commit-date: 2017-06-12
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0
```

**Comment by pzuraq** [comment] 2017-07-30 16:56
I'm getting the same issue with the following versions of rust/rust-lldb:

```
$ rust-lldb -v
lldb-370.0.42
  Swift-3.1
$ rustc -vV
rustc 1.19.0 (0ade33941 2017-07-17)
binary: rustc
commit-hash: 0ade339411587887bf01bcfa2e9ae4414c8900d4
commit-date: 2017-07-17
host: x86_64-apple-darwin
release: 1.19.0
LLVM version: 4.0
```

I've also tried using nightly and have the same problem.

**Comment by pzuraq** [comment] 2017-08-06 16:53
Digging into this a bit more, it looks like it may be related to this issue: https://github.com/rust-lang/cargo/issues/4056

When I run the debugger on the output file in `./target/debug/deps` everything seems to work as expected

**Comment by jonas-schievink** [comment] 2020-08-01 13:05
https://github.com/rust-lang/cargo/issues/4056 has since been closed. Is this still an issue?

**Comment by davidtwco** [comment] 2023-07-17 14:31
I've tried to reproduce this locally and I'm not able to. If someone can provide a reproducible example, the versions of everything involved, and the commands you've used then we can re-open this. 

```shell-session
$ rust-lldb -v
lldb-1500.0.17.10
Apple Swift version 5.9 (swiftlang-5.9.0.120.7 clang-1500.0.34.3)
$ rustc -vV
rustc 1.72.0-nightly (5ea666864 2023-06-27)
binary: rustc
commit-hash: 5ea66686467d3ec5f8c81570e7f0f16ad8dd8cc3
commit-date: 2023-06-27
host: aarch64-apple-darwin
release: 1.72.0-nightly
LLVM version: 16.0.5
```

**Closed by davidtwco** 2023-07-17 14:31 UTC
Labels: A-debuginfo, T-compiler, C-bug
