### ISSUE TITLE
Error with cast in enum definition.

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#23304] opened 2015-03-12 10:16 UTC
The following code hits an error:
```rust
#![allow(dead_code)]

#[repr(u32)]
enum ValueTag {
    INT32                = 0x1FFF0u32 | (0x01 as u32),
    X,
}

#[repr(u64)]
enum ValueShiftedTag {
    INT32        = ValueTag::INT32 as u64,
    X,
}

fn main() {
    println!("{}", ValueTag::INT32 as u32);
}
```
```
/tmp/a.rs:7:42: 7:53 error: constant evaluation error: can't cast this type [E0080]
/tmp/a.rs:7     INT32                = 0x1FFF0u32 | (0x01 as u32),
                                                     ^~~~~~~~~~~
```

Note that the error doesn't reproduce without the `ValueShiftedTag` definition.

This blocks the current rust upgrade for Servo.

CC @eddyb.

**Comment by mahkoh** [comment] 2015-03-12 21:50
Minimal:

```rust
enum X { A = 0 as isize }

enum Y { A = X::A as isize }

fn main() { }
```

Work around:

```rust
#[repr(u32)] enum X { A = 0u32 | 1u32, B }

#[repr(u64)] enum Y { A = X::A as u64, B }

fn main() { }
```

**Comment by Ms2ger** [comment] 2015-03-13 12:18
Do you also have a workaround for this:

```rust
#![allow(dead_code)]

#[repr(u8)]
#[allow(dead_code)]
enum ValueType {
    DOUBLE              = 0x00,
    INT32               = 0x01,
}

#[repr(u32)]
enum ValueTag {
    INT32                = 0x1FFF0u32 | (ValueType::INT32 as u32),
    X,
}

#[repr(u64)]
enum ValueShiftedTag {
    INT32        = ValueTag::INT32 as u64,
    X,
}

fn main() {
    println!("{}", ValueTag::INT32 as u32);
}
```
?

**Comment by SimonSapin** [comment] 2015-03-13 12:58
This doesn’t look like a ICE when I reproduce this.

**Comment by mahkoh** [comment] 2015-03-13 13:17
>Do you also have a workaround for this:

Nope. Problem seems to come from using `as` too much.

**Comment by SimonSapin** [comment] 2015-03-13 13:17
I’m still not sure what was the root cause, but I worked around this by replacing these `enum`s with a bunch of `const`s: https://github.com/servo/rust-mozjs/pull/137

Feel free to close.

**Comment by ahwatts** [comment] 2015-03-13 21:57
It looks like this happens if it needs to recurse more than once to evaluate a constant, i.e, in order to evaluate `PieALaMode`, it needs to evaluate `ApplePie`, which in turn requires it to evaluate `Pie` and `Apple`.

```
#[derive(Debug)]
enum Delicious {
    Pie      =  0x1,
    Apple    =  0x2,
    IceCream = 0x40,
    Vanilla  = 0x80,
    ApplePie = Delicious::Apple as isize | Delicious::Pie as isize,
    PieALaMode = Delicious::ApplePie as isize | Delicious::IceCream as isize | Delicious::Vanilla as isize,
}

fn main() {
    println!("Apple Pie = {:?} ({:?})", Delicious::ApplePie, Delicious::ApplePie as isize);
    println!("Pie à la Mode = {:?} ({:?})", Delicious::PieALaMode, Delicious::PieALaMode as isize);
}
```

(Sorry, I apparently need to go eat dinner. And dessert.)

**Comment by SimonSapin** [comment] 2015-03-13 22:48
Also note that this code used to build with earlier compiler versions.

**Comment by frewsxcv** [comment] 2015-08-17 13:30
Update: @Ms2ger's [code he pasted](https://github.com/rust-lang/rust/issues/23304#issuecomment-78945624) currently compiles on nightly. It does not compile on beta or stable.

[Playpen link](http://is.gd/GZto9c)

I'll add a regression test to close this, unless I hear otherwise

**Closed** 2015-08-17 18:55 UTC
Labels: A-typesystem
