### ISSUE TITLE
Suggest &mut T for &T and vice versa for missing trait bound if applicable

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#65062] opened 2019-10-03 15:56 UTC
As seen on [Twitter](https://twitter.com/khyperia/status/1179518655790374912?s=19):

Missing trait does not hint (im)mutable reborrowing, at least in that specific case.

**Comment by estebank** [comment] 2019-10-03 19:54
dupe of https://github.com/rust-lang/rust/issues/63619

**Closed by estebank** 2019-10-03 19:54 UTC
Labels: A-diagnostics, A-suggestion-diagnostics, A-traits, C-enhancement, T-compiler
