### ISSUE TITLE
regression: temporary value dropped while borrowed

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#113237] opened 2023-07-01 16:36 UTC
https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/reg/munge-0.3.0/log.txt

```
[INFO] [stdout] error[E0716]: temporary value dropped while borrowed
[INFO] [stdout]    --> src/lib.rs:194:18
[INFO] [stdout]     |
[INFO] [stdout] 194 |         a = &mut MaybeUninit::uninit();
[INFO] [stdout]     |                  ^^^^^^^^^^^^^^^^^^^^^- temporary value is freed at the end of this statement
[INFO] [stdout]     |                  |
[INFO] [stdout]     |                  creates a temporary value which is freed while still in use
[INFO] [stdout] 195 |         b = &mut MaybeUninit::uninit();
[INFO] [stdout] 196 |         let _ = a;
[INFO] [stdout]     |                 - borrow later used here
[INFO] [stdout]     |
[INFO] [stdout] help: consider using a `let` binding to create a longer lived value
[INFO] [stdout]     |
[INFO] [stdout] 194 ~         let binding = MaybeUninit::uninit();
[INFO] [stdout] 195 ~         a = &mut binding;
[INFO] [stdout]     |
```

**Comment by asquared31415** [comment] 2023-07-01 19:38
searched nightlies: from nightly-2023-04-17 to nightly-2023-06-06
regressed nightly: nightly-2023-04-23
searched commit range: https://github.com/rust-lang/rust/compare/fec9adcdbc21469ef105162cc8cabf81c72d06be...b628260df0587ae559253d8640ecb8738d3de613
regressed commit: https://github.com/rust-lang/rust/commit/21fab435da99d6ef14c1c870650ee976499564f3

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 
```
</details>

**Comment by hameerabbasi** [comment] 2023-07-02 04:07
> edit: whoops there was an FCP for this in #104844 (which is the regressing PR)

This particular failure wasn't mentioned in that PR, however. Perhaps it was missed.

**Comment by Nilstrieb** [comment] 2023-07-02 07:30
cc @cjgillot, crater on the PR found no regressions but we got one here. @djkoloski this is your crate^^

**Comment by lqd** [comment] 2023-07-02 08:28
Interesting, `munge-0.3.0` didn't appear as a regression then because it was categorized "broken: missing some deps" by both the [before](https://crater-reports.s3.amazonaws.com/pr-104844/master%23d5833423a02e2373c5e3cceb238fb19192cd82f8/reg/munge-0.3.0/log.txt) and [after](https://crater-reports.s3.amazonaws.com/pr-104844/try%2384fd1b4dd8570faf7f3952e3ef25185025095260/reg/munge-0.3.0/log.txt) toolchains, so #104844 didn't run on it at the time.

**Comment by djkoloski** [comment] 2023-07-02 19:12
I've fixed the offending tests in tree. It looks like this regression only affected the specific test code, not any functional part of the crate.

**Comment by apiraino** [comment] 2023-08-01 10:46
WG-prioritization removing priority ([Zulip discussion](tbh I'm unsure on what is the best course of action here: maybe close the issue rather than leave in a undefined state?)), IIUC I see no clear actionable for us.

@rustbot label -I-prioritize

**Comment by apiraino** [comment] 2023-08-21 16:03
I think the previous evaluation still stands (again: unless I'm missing some context). @Mark-Simulacrum does it make sense to remove the prioritization? And/or closing the issue?

**Comment by Enselic** [comment] 2024-11-02 11:36
>  maybe close the issue rather than leave in a undefined state? IIUC I see no clear actionable for us.

No objections for over a year. Let's close!

**Closed by Enselic** 2024-11-02 11:36 UTC
Labels: T-compiler, regression-from-stable-to-stable
