### ISSUE TITLE
format!() ignores width while formatting Debug

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#83361] opened 2021-03-22 01:22 UTC
Related: https://github.com/rust-lang/rust/issues/55584

```rust
fn main() {
    // The code I was trying to get working
    println!("[{text:width$}]", text = "foo", width = 10);
    println!("[{text:width$?}]", text = "foo", width = 10);
    
    // A reduced reproducer
    println!("[{:10}]", "foo");
    println!("[{:10?}]", "foo");
}
```
[(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c3a969c2aaf4800439ac5f056a96cc46)
shows as result
```
[foo       ]
["foo"]
[foo       ]
["foo"]
```

I understand from #55584 that this might be “working as intended”, though I'm not really sure I understand why.

If there are technical reasons why width-setting can't work, would it be possible to error out at compile-time (well… lint and in the next edition error) when hitting such a construct? I must say that it was my first time attempting to get dynamic width working, and I was persuaded I did something wrong until I just tried removing `Debug` and all of a sudden everything worked.

And if there are practical reasons why one would not want that, would it be possible to update the documentation to make this behavior explicit? :)

**Comment by osa1** [comment] 2021-03-23 12:26
This is a duplicate of #55584. I think it makes sense to close this and have all the relevant discussion in one place.

**Comment by Ekleog** [comment] 2021-03-23 17:12
Well, precision and width are not the same flag, and I'm thinking it might make sense to have the behavior differ between them :) Now, if people think the behavior must be the same (I must say I still don't really get why #55584 would be the good behavior) then let's close this, but I can't think of any use case for `width` doing anything different between `Display` and `Debug`

**Comment by Enselic** [comment] 2023-12-17 07:50
Triage: While https://github.com/rust-lang/rust/issues/55584 is not a literal duplicate, the underlying principles are the same, so let's close as duplicate.

**Closed by Enselic** 2023-12-17 07:50 UTC
Labels: T-libs-api, C-bug, A-fmt
