### ISSUE TITLE
Rust 1.18 regression - mime_multipart-0.3.5

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#40958] opened 2017-03-31 17:19 UTC
[Regression logs](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/mime_multipart-0.3.5/log.txt)

This looks like a soundness fix, but this'll track ensuring we send a PR upstream and file this into the release notes.

**Comment by alexcrichton** [comment] 2017-04-04 17:31
```
commit b118d606feb62c15d0dbd4e3280597a02e004190
Author: Mike Dilger <mike@optcomp.nz>
Date:   Wed Dec 14 11:49:41 2016 +1300

    0.3.5
```

https://github.com/mikedilger/mime-multipart

**Comment by alexcrichton** [comment] 2017-04-04 17:32
[Code in question](https://github.com/mikedilger/mime-multipart/blob/b118d606feb62c15d0dbd4e3280597a02e004190/src/lib.rs#L260-L266)

**Comment by arielb1** [comment] 2017-04-04 17:34
Signature of `parse_headers`:
```Rust
pub fn parse_headers<'b: 'h, 'h>(src: &'b [u8], mut dst: &'h mut [Header<'b>])
```

This was caused by #40319 and indeed discussed in the thread with the author: https://github.com/rust-lang/rust/pull/40319#issuecomment-285198418.

**Comment by nikomatsakis** [comment] 2017-04-05 17:30
OK, closing this issue then.

**Comment by nikomatsakis** [comment] 2017-04-05 17:30
@mikedilger you may wish to publish the new versions of the crate, if you've not already done so.

**Closed by nikomatsakis** 2017-04-05 17:30 UTC
Labels: regression-from-stable-to-beta, T-compiler

**Comment by mikedilger** [comment] 2017-04-05 21:49
@nikomatsakis New versions were published 9th of March.  I hope 0.3.5 doesn't get pulled into regression testing of each subsequent rust version.
