### ISSUE TITLE
Wrapping simd call results in compiler panic (nightly)

### ISSUE THREAD

**Issue by dignifiedquire** [rust-lang/rust#59469] opened 2019-03-27 18:54 UTC
Expected the following code to compile

```rust
#[cfg(target_arch = "x86")]
use core::arch::x86::*;
#[cfg(target_arch = "x86_64")]
use core::arch::x86_64::*;

unsafe fn pclmul(a: __m128i, b: __m128i, imm8: i32) -> __m128i {
    _mm_clmulepi64_si128(a, b, imm8)
}
```

But getting

```
Standard Error

   Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'index out of bounds: the len is 2 but the index is 3', /rustc/fbd34efb32b9efb574899e4335bdc8c6525ac27e/src/libcore/slice/mod.rs:2539:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (fbd34efb3 2019-03-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

Repro: 

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=36e55f5180a9cf903585dead5b4c2a8d

**Comment by jonas-schievink** [comment] 2019-03-27 19:02
Also happens on beta, not on stable

**Comment by jonas-schievink** [comment] 2019-03-27 19:03
Stable says:

```
error: argument 3 is required to be a constant
 --> src/lib.rs:7:5
  |
7 |     _mm_clmulepi64_si128(a, b, imm8)
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by dignifiedquire** [comment] 2019-03-27 19:14
For reference, the function signature as defined [here](https://doc.rust-lang.org/core/arch/x86/fn._mm_clmulepi64_si128.html) is exactly the same.

**Comment by hellow554** [comment] 2019-03-28 10:23
The actual ICE occurs first in nightly-2019-03-03 (c1d2d83ca...0ea22717a).

But interesting enough, stable (as jonas pointed out) procuces an error, saying, that the third argument must be a constant. Since nightly-2019-02-16 (f47ec2ad5...a9410cd1a) this does not emit an error anymore, but also does not ICE.

**Comment by hellow554** [comment] 2019-03-28 10:26
I guess for the "does not emit an error anymore" @eddyb can say something about it. https://github.com/rust-lang/rust/pull/58403 should be responsible for it.

**Comment by pnkfelix** [comment] 2019-03-28 13:17
triage: P-high

**Comment by eddyb** [comment] 2019-03-29 03:50
@dignifiedquire Note that because of the `#[rustc_args_required_const(2)]` on the definition, you can't wrap it.

@hellow554 I don't think this is intentional, but I'm not sure why it would happen, maybe arguments are treated incorrectly in the qualifier. cc @oli-obk @gnzlbg

**Comment by gnzlbg** [comment] 2019-03-29 08:05
So I agree that this code can't compile, that's the expected behavior; @dignifiedquire if you want to wrap it, you have to use a macro - Rust functions aren't able to abstract over this type of hardware operations yet. 

The ICE is a regression over the error message that was being produced before. We should definitely add an ui test for that.

**Comment by pnkfelix** [comment] 2019-04-04 13:29
triage, assigning to self to fix.

**Comment by pnkfelix** [comment] 2019-04-05 09:59
The behavior here varies with edition as well as channel.

edition            |          2015            | 2018
------------------ | ------------------------ | ------------------------
stable             | expected error           | expected error
beta               | unexpected compile-pass  | unexpected compile-pass
nightly-2019-04-05 | unexpected compile-pass  | ICE

I think the most immediate thing to address is the unexpected compile-pass that has leaked into beta.

**Comment by pnkfelix** [comment] 2019-04-05 10:01
The easiest thing might be to revert #58403

**Comment by oli-obk** [comment] 2019-04-05 12:39
I have an actual fix in https://github.com/rust-lang/rust/pull/59724 (also easier to backport than a revert)

**Comment by pnkfelix** [comment] 2019-04-05 13:59
Okay then I'm reassigning to @oli-obk

**Closed** 2019-04-08 04:01 UTC
Labels: C-bug, I-ICE, P-high, T-compiler, regression-from-stable-to-beta
