### ISSUE TITLE
Rust program crashes when linked with -mwindows

### ISSUE THREAD

**Issue by anfractuosity** [rust-lang/rust#26604] opened 2015-06-26 18:59 UTC
I'm finding when I link my program with -mwindows, it will crash instantly 
when run

**Comment by anfractuosity** [comment] 2015-06-26 19:09
It seems it's only when you call println! interestingly

**Comment by mitaa** [comment] 2015-06-26 19:29
#24821 may be related.

**Comment by steveklabnik** [comment] 2015-06-26 21:57
Yes, closing as a duplicate of that for now. If you find a non-`println!` case, let me know and we can re-open!

**Closed by steveklabnik** 2015-06-26 21:57 UTC
