### ISSUE TITLE
Support targeting Windows XP

### ISSUE THREAD

**Issue by larsbergstrom** [rust-lang/rust#24776] opened 2015-04-24 18:06 UTC
It would be great for Rust to be able to build code that targets Windows down to Windows XP SP2. There are still a significant number of Firefox users on that platform, so any Rust code built into Firefox would also need to run on that platform.

The only issue I am aware of preventing this today is the use of condvars in std.

cc @brson

**Comment by alexcrichton** [comment] 2015-04-24 18:29
This is a dupe of https://github.com/rust-lang/rust/issues/12842, and I believe @vadimcn's [list of APIs](https://github.com/rust-lang/rust/issues/12842#issuecomment-76674381) is mostly still applicable today for things we're using that are not on XP.

**Comment by alexcrichton** [comment] 2015-04-24 18:33
Er as clarified with @larsbergstrom on IRC it possible to interpret #12842 as having the compiler run on XP and this as targeting XP, which are separate issues.

**Comment by vadimcn** [comment] 2015-04-25 04:21
AFAIK, it was always understood that the compiler itself will never run on XP.

**Comment by larsbergstrom** [comment] 2015-04-25 14:49
@vadimcn That other issue, #12842, has mixed comments and partial results evaluating both whether the toolchain runs on XP (which I do not care about) and whether binaries produces by rustc can run on XP (which I *do* care about). As long as the two are tracked separately - since I also suspect that running rustc.exe on XP is a non-goal - whatever selection of issues is fine by me.

**Closed** 2015-06-28 06:09 UTC
Labels: A-windows, I-enhancement
