### ISSUE TITLE
RangeFrom iterator overflows when it gets to the maximum value of the type

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#25696] opened 2015-05-22 03:05 UTC
So if you have `(0u8..)` and iterate over it, it will keep going forever (in a release build anyway), producing 0, 1, 2, ... 255, 0, 1, 2, ...

That is unexpected. It also panics in a debug build, so I assume it's also not intentional. I propose that instead of overflowing, the iterator instead returns `None`.

**Comment by XMPPwocky** [comment] 2015-05-22 15:02
Would that change be backwards compatible? Arguably not, since it changes observable behavior in stable code, and although nobody should be relying on it, [you never know.](https://xkcd.com/1172/)

(For the record, I agree this is surprising, probably wrong, behavior.

**Comment by Gankro** [comment] 2015-05-22 16:25
CC @nrc (who probably has the best memory on this precise decision)

**Comment by nrc** [comment] 2015-05-23 00:12
This is the intentional behaviour. The expectation is that you will only use such iterators along with `take()` or some other safe guard against overflow. (We basically chose what seemed like the least-worst option here).

**Comment by alexcrichton** [comment] 2015-05-26 16:41
I agree with @nrc that this is intended behavior currently. The precise semantics of when the overflow occurs I think is covered by https://github.com/rust-lang/rust/issues/25708, so I'm going to close this in favor of that. Feel free to reopen if you disagree though!

**Closed by alexcrichton** 2015-05-26 16:41 UTC
Labels: A-libs
