### ISSUE TITLE
`unresolved name` error when trying to construct a tuple struct through type alias

### ISSUE THREAD

**Issue by d3lio** [rust-lang/rust#39219] opened 2017-01-21 11:04 UTC
When I tried to construct a tuple struct with a type alias it gives me an error like

```rustc 1.15.0-beta.4 (ad78c04a9 2017-01-18)
error[E0425]: unresolved name `A`
   |
   |     let a: A = A(5);
   |                ^ unresolved name
```

Example:

```Rust
struct TupleStruct(u8);
struct NormalStruct {
    field: u8
}
type A = TupleStruct;
type B = NormalStruct;

fn main() {
    let a: A = A(5); // Error
    let b: B = B { field: 5 }; // This is fine
}
```

If I instead do `let a: A = TupleStruct(5)` the code is compiled perfectly fine.
Type `B` on the other hand has no problems compiling as it is in this example.

Another example would be returning the value from a function
```Rust
struct TupleStruct(u8);
type A = TupleStruct;

impl A {
    fn new() -> A {
        A(5) // Error
    }
}
```
What I expect are no compile errors when the tuple struct is constructed through the type alias `A`.

I've tried this on both 1.14.0 stable and 1.15.0-beta4 in https://play.rust-lang.org and 1.14.0 locally: 

`rustc --version --verbose`:

rustc 1.14.0 (e8a012324 2016-12-16)
binary: rustc
commit-hash: e8a0123241f0d397d39cd18fcc4e5e7edde22730
commit-date: 2016-12-16
host: x86_64-pc-windows-msvc
release: 1.14.0
LLVM version: 3.9

**Comment by TimNN** [comment] 2017-01-21 16:23
Duplicate of #17422.

Also see https://github.com/rust-lang/rfcs/blob/master/text/1506-adt-kinds.md for some background information.

**Comment by Mark-Simulacrum** [comment] 2017-05-20 02:01
Closing (duplicate issue #17422 was also closed).

**Closed by Mark-Simulacrum** 2017-05-20 02:01 UTC
