### ISSUE TITLE
unused_mut lint improvement: warn when variable only copied into closure

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/rust#47128] opened 2018-01-02 14:00 UTC
Minimal example of the lint failure to fire:
```
fn foo() -> bool {
    let mut res = false;
    
    let mut do_thing = move || res = true;
    do_thing();
    
    res
}
```

`foo` unconditionally returns false, but the top-level binding of `res` doesn't get an `unused_mut` warning.

**Comment by jakubadamw** [comment] 2019-08-13 20:43
This is related to or even a duplicate of #37707.

**Closed** 2020-05-29 23:43 UTC
Labels: A-lint, C-enhancement, T-compiler
