### ISSUE TITLE
Compiler: thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by cphoenix-google** [rust-lang/rust#54217] opened 2018-09-14 07:18 UTC
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "read_option: expected 0 for None or 1 for Some"', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: rustc_metadata::decoder::<impl rustc_metadata::cstore::MetadataBlob>::get_root
  11: rustc_metadata::locator::Context::extract_one
  12: rustc_metadata::locator::Context::find_library_crate
  13: rustc_metadata::locator::Context::maybe_load_library_crate
  14: rustc_metadata::creader::CrateLoader::load
  15: rustc_metadata::creader::CrateLoader::resolve_crate
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
  17: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  18: rustc_metadata::creader::CrateLoader::resolve_crate
  19: rustc_metadata::creader::CrateLoader::process_extern_crate
  20: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a, 'cl>>::build_reduced_graph_for_item
  21: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
  22: syntax::visit::walk_item
  23: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
  24: syntax::ext::expand::AstFragment::visit_with
  25: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a, 'crateloader>>::visit_ast_fragment_with_placeholders
  26: syntax::ext::expand::MacroExpander::collect_invocations
  27: syntax::ext::expand::MacroExpander::expand_fragment
  28: syntax::ext::expand::MacroExpander::expand_crate
  29: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  30: rustc::util::common::time
  31: rustc_driver::driver::phase_2_configure_and_expand
  32: rustc_driver::driver::compile_input
  33: rustc_driver::run_compiler_with_pool
  34: <scoped_tls::ScopedKey<T>>::set
  35: rustc_driver::run_compiler
  36: syntax::with_globals
  37: __rust_maybe_catch_panic
  38: rustc_driver::run
  39: rustc_driver::main
  40: std::rt::lang_start::{{closure}}
  41: std::panicking::try::do_call
  42: __rust_maybe_catch_panic
  43: std::rt::lang_start_internal
  44: main
  45: __libc_start_main
  46: _start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C linker=/[elided]/bin/clang -C incremental -C link-arg=--target=x86_64-unknown-linux-gnu -C opt-level=z -C link-arg=--sysroot=/[elided]/linux-x64/sysroot --crate-type lib
```

**Comment by Centril** [comment] 2018-09-14 20:29
Hi there; can you provide the commit hash at which this error occurred so that we can reproduce?

**Comment by cphoenix-google** [comment] 2018-09-15 00:46
Yeah, good luck reproducing it. When I deleted my out/ directory, the
problem disappeared.

**Comment by Centril** [comment] 2018-09-17 15:22
> Possibly incompatible serialized versions from two rustc versions?

seems plausible given that the ICE vanished when `out/` was removed.

**Comment by jonas-schievink** [comment] 2019-08-06 12:16
Duplicate of https://github.com/rust-lang/rust/issues/54167, closing in favor of that

**Closed by jonas-schievink** 2019-08-06 12:16 UTC
Labels: A-metadata, C-bug, I-ICE, T-compiler
