### ISSUE TITLE
Wrong pattern matching on enums

### ISSUE THREAD

**Issue by crone123** [rust-lang/rust#60824] opened 2019-05-14 12:50 UTC
Hello,
There is a bug with enums and pattern matching, please try this minimal code:

```
pub enum TEST
{
	A, B, C,
}
impl TEST
{
	pub fn match_half(&self) -> String
	{
		match(self)
		{
			A => String::from("A"),
			B => String::from("B"),
			C => String::from("C"),
		}
	}
	pub fn match_full(&self) -> String
        {
                match(self)
                {
                        TEST::A => String::from("A"),
                        TEST::B => String::from("B"),
                        TEST::C => String::from("C"),
                }
        }
}
fn main() {
	let v = vec!(TEST::A, TEST::B, TEST::C);
	for i in v
	{
		println!("Half: {} / Full: {}", i.match_half(), i.match_full());
	}
}
```

What I call "half" is when you type "A" instead of "TEST::A", and when I call "full" is the regular "TEST::A".

Result:

```
Half: A / Full: A
Half: A / Full: B
Half: A / Full: C
```
Attended result:

```
Half: A / Full: A
Half: B / Full: B
Half: C / Full: C
```

You see that, when you use the "half" notation, the pattern matching will always use the first case which is not the good behaviour.
This bug can make programs very hard to debug because generally we read: "Ok, it's a pattern matching with rust, so it's safe", but not here.

This bug was found with:
cargo 1.36.0-nightly (b6581d383 2019-04-16)
rustc 1.36.0-nightly (5d20ff4d2 2019-04-18)

On Ubuntu 19.04 LTS.

Note that is you do a pattern matching to implement a trait the bug is the same, I found this by implementing ToString in one of my projects.

Thank you !

**Comment by hellow554** [comment] 2019-05-14 13:46
```
warning: unreachable pattern
  --> src/main.rs:10:13
   |
9  |             A => String::from("A"),
   |             - matches any value
10 |             B => String::from("B"),
   |             ^ unreachable pattern
   |
   = note: #[warn(unreachable_patterns)] on by default

warning: unreachable pattern
  --> src/main.rs:11:13
   |
9  |             A => String::from("A"),
   |             - matches any value
10 |             B => String::from("B"),
11 |             C => String::from("C"),
   |             ^ unreachable pattern

warning: unused variable: `A`
 --> src/main.rs:9:13
  |
9 |             A => String::from("A"),
  |             ^ help: consider prefixing with an underscore: `_A`
  |
  = note: #[warn(unused_variables)] on by default

warning: unused variable: `B`
  --> src/main.rs:10:13
   |
10 |             B => String::from("B"),
   |             ^ help: consider prefixing with an underscore: `_B`

warning: unused variable: `C`
  --> src/main.rs:11:13
   |
11 |             C => String::from("C"),
   |             ^ help: consider prefixing with an underscore: `_C`

warning: variable `A` should have a snake case name
 --> src/main.rs:9:13
  |
9 |             A => String::from("A"),
  |             ^ help: convert the identifier to snake case: `a`
  |
  = note: #[warn(non_snake_case)] on by default

warning: variable `B` should have a snake case name
  --> src/main.rs:10:13
   |
10 |             B => String::from("B"),
   |             ^ help: convert the identifier to snake case: `b`

warning: variable `C` should have a snake case name
  --> src/main.rs:11:13
   |
11 |             C => String::from("C"),
   |             ^ help: convert the identifier to snake case: `c`
```

**Comment by hellow554** [comment] 2019-05-14 13:49
There's nothing as "half" notation. You have to use the full qualified name **or** import it into your local namespace by using `use TEST::*`. 
This is not a bug, but instead the intended behavoir with pattern matching.

I think the warnings are pretty clear in this case.

**Comment by jonas-schievink** [comment] 2019-05-14 13:51
Closing as working as intended.

If you have further questions, please ask in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Closed by jonas-schievink** 2019-05-14 13:51 UTC

**Comment by hellow554** [comment] 2019-05-14 13:52
As a sidenote and not really related to your problem:
Your code is not very idiomatic. You don't need brackets around the item you want to match. Enums should be named in `PascalCase`.  Curly brackets should be places in the same line.

All this can be found out by looking at the warnings the compiler gives you. **Don't ignore them!** If you do, you're on your own.
Also it's worth using `rustfmt` (`rustup component add rustfmt`) to format your code according to the community guidelines.

**Comment by crone123** [comment] 2019-05-15 07:55
Ok, now I understand, I forgot the possibility that A can be a new identifier instead of my enum value, sorry.
