### ISSUE TITLE
rustc is unable to build for vendored toolchains by default

### ISSUE THREAD

**Issue by zachreizner** [rust-lang/rust#41402] opened 2017-04-19 20:21 UTC
When rustc is given a target triple to compile for, the behavior, as defined by [librustc_back](https://github.com/rust-lang/rust/blob/9d11b089ad136432dff6c49c6eb3c48c7f6e5273/src/librustc_back/target/mod.rs), is to search the list of builtins for an exact match and then to search for the target triple as a file or a json configuration in some search directories. In every case, the target triple is treated as an opaque key to be searched for, contrary to the usual usage of a target triple.

The usual way is to parse the triple into its semantic parts (arch-vendor-system or arch-vendor-kernel-system) and use those parts to build up a target specification (i.e. a struct Target from librustc_back). The consequence of this deviation is that vendored toolchains (toolchains that have something other than a "default" vendor in their triple) won't be recognized by rustc, contrary to the purpose of having a vendor string, which is to allow vendors to use arbitrary toolchains.

The current workaround is either to explicitly add the needed vendor triple to rustc's list of builtins (which requires official support to get into master) or to add a TRIPLE.json to the appropriate path. Granted, these workaround are not onerous, but I believe the "right" way would be to handle the target triples properly by default. I'm putting this issue up for discussion.

**Comment by jmesmon** [comment] 2017-04-19 20:47
Related (but not quite the same): #33147

**Comment by metux** [comment] 2017-07-12 18:52
Just curios: which vendor toolchains are you using ?

**Comment by zachreizner** [comment] 2017-07-13 04:42
The toolchain's vendor string is "cros" as in "Chrome OS".

**Comment by jackh726** [comment] 2022-10-24 23:43
Closing as duplicate of #33147

**Closed by jackh726** 2022-10-24 23:43 UTC
Labels: T-compiler, C-feature-request
