### ISSUE TITLE
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9 when compiling packed_simd

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/rust#73377] opened 2020-06-15 16:27 UTC
Hello,
  I found an internal compiler error when compiling [this pull request](https://github.com/image-rs/jpeg-decoder/pull/146) with rust nightly on github CI. See the CI output at https://github.com/image-rs/jpeg-decoder/pull/146/checks?check_run_id=773387154

### Meta
rustc version:   nightly-x86_64-unknown-linux-gnu installed - rustc 1.46.0-nightly (4fb54ed48 2020-06-14)

### Error output

```
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:37: could not fully normalize `<A as sealed::SimdArray>::Tuple`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
```

<details>

```

2020-06-15T16:13:18.7189412Z     Updating crates.io index
2020-06-15T16:13:25.4320351Z  Downloading crates ...
2020-06-15T16:13:25.6227306Z   Downloaded simulated_packed_simd v0.0.1
2020-06-15T16:13:25.6250321Z   Downloaded byteorder v1.3.4
2020-06-15T16:13:25.6281625Z   Downloaded packed_simd v0.3.3
2020-06-15T16:13:25.6493457Z    Compiling packed_simd v0.3.3
2020-06-15T16:13:25.6495483Z      Running `rustc --crate-name build_script_build --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.3/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=494370d987ba403f -C extra-filename=-494370d987ba403f --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/build/packed_simd-494370d987ba403f -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --cap-lints allow`
2020-06-15T16:13:25.6500974Z    Compiling byteorder v1.3.4
2020-06-15T16:13:25.6504545Z      Running `rustc --crate-name build_script_build /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.3.4/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=edf26df6509e9d74 -C extra-filename=-edf26df6509e9d74 --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/build/byteorder-edf26df6509e9d74 -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --cap-lints allow`
2020-06-15T16:13:25.9961423Z    Compiling cfg-if v0.1.10
2020-06-15T16:13:25.9962948Z      Running `rustc --crate-name cfg_if --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=ccbfd7b907057858 -C extra-filename=-ccbfd7b907057858 --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --cap-lints allow`
2020-06-15T16:13:26.0516627Z    Compiling simulated_packed_simd v0.0.1
2020-06-15T16:13:26.0518563Z      Running `rustc --crate-name simulated_packed_simd --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/simulated_packed_simd-0.0.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=7ec0b7cd002d27da -C extra-filename=-7ec0b7cd002d27da --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --cap-lints allow`
2020-06-15T16:13:26.4082128Z      Running `/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/build/packed_simd-494370d987ba403f/build-script-build`
2020-06-15T16:13:26.4108555Z      Running `/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/build/byteorder-edf26df6509e9d74/build-script-build`
2020-06-15T16:13:26.4317419Z      Running `rustc --crate-name packed_simd --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=7e4bc3ec42dcdb52 -C extra-filename=-7e4bc3ec42dcdb52 --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --extern cfg_if=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps/libcfg_if-ccbfd7b907057858.rmeta --cap-lints allow`
2020-06-15T16:13:27.6962769Z      Running `rustc --crate-name byteorder /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.3.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=9c1d83eca87ff300 -C extra-filename=-9c1d83eca87ff300 --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --cap-lints allow --cfg byteorder_i128`
2020-06-15T16:13:42.1342947Z error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:37: could not fully normalize `<A as sealed::SimdArray>::Tuple`
2020-06-15T16:13:42.1343102Z 
2020-06-15T16:13:42.1343943Z thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
2020-06-15T16:13:42.1344095Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2020-06-15T16:13:42.1344169Z 
2020-06-15T16:13:42.1344290Z note: the compiler unexpectedly panicked. this is a bug.
2020-06-15T16:13:42.1344357Z 
2020-06-15T16:13:42.1344782Z note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
2020-06-15T16:13:42.1344901Z 
2020-06-15T16:13:42.1345238Z note: rustc 1.46.0-nightly (4fb54ed48 2020-06-14) running on x86_64-unknown-linux-gnu
2020-06-15T16:13:42.1345317Z 
2020-06-15T16:13:42.1345616Z note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
2020-06-15T16:13:42.1345915Z 
2020-06-15T16:13:42.1346025Z note: some of the compiler flags provided by cargo are hidden
2020-06-15T16:13:42.1346114Z 
2020-06-15T16:13:42.3475894Z error: aborting due to previous error
2020-06-15T16:13:42.3476123Z 
2020-06-15T16:13:42.3647063Z error: could not compile `packed_simd`.
2020-06-15T16:13:42.3647188Z 
2020-06-15T16:13:42.3647302Z Caused by:
2020-06-15T16:13:42.3648791Z   process didn't exit successfully: `rustc --crate-name packed_simd --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' -C metadata=7e4bc3ec42dcdb52 -C extra-filename=-7e4bc3ec42dcdb52 --out-dir /home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps -L dependency=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps --extern cfg_if=/home/runner/work/jpeg-decoder/jpeg-decoder/target/debug/deps/libcfg_if-ccbfd7b907057858.rmeta --cap-lints allow` (exit code: 101)
2020-06-15T16:13:42.3676561Z ##[error]Process completed with exit code 101.
```
</details>

**Comment by matthiaskrgr** [comment] 2020-06-15 16:37
Duplicate of https://github.com/rust-lang/rust/issues/73249

**Closed** 2020-06-15 16:38 UTC
Labels: A-associated-items, A-simd, C-bug, I-ICE, I-prioritize, T-compiler
