### ISSUE TITLE
-Zincremental causes ICE for libc crate

### ISSUE THREAD

**Issue by shahn** [rust-lang/rust#35282] opened 2016-08-04 00:55 UTC
Getting this while trying to compile libc 0.2.14:

```
$ export RUSTFLAGS=-Zincremental=target/INCREMENTAL
$ RUST_BACKTRACE=1 cargo build
   Compiling libc v0.2.14
error: internal compiler error: ../src/librustc/hir/map/mod.rs:510: expected item, found foreign item isalnum (id=97) 
note: the compiler unexpectedly panicked. this is a bug. 
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports 
note: run with `RUST_BACKTRACE=1` for a backtrace 
thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:636
stack backtrace:
   1:        0x1100006f9 - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:        0x11000f7f0 - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:        0x11000dc36 - std::panicking::default_hook::hbbe7fa36a995aca0
   4:        0x11000e302 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:        0x10fe4639a - std::panicking::begin_panic::hccc513334ab977d2
   6:        0x10fe5b6ac - rustc_errors::Handler::bug::h9fe35eb8aa73a45f
   7:        0x10c808466 - rustc::session::opt_span_bug_fmt::_{{closure}}::h62b0957667555cfe
   8:        0x10c7350a9 - rustc::session::opt_span_bug_fmt::hb71219f119a31511
   9:        0x10c734e5a - rustc::session::bug_fmt::h8de2935acd9a57e4
  10:        0x10c5fb23b - rustc::hir::map::Map::expect_item::hf4e9ba440db440e7
  11:        0x10c49f47a - _<rustc..ty..context..TyCtxt<'a, 'tcx, 'tcx> as rustc_incremental..calculate_svh..SvhCalculate>::calculate_item_hash::h1e4c3bc17238ac4e
  12:        0x10c4a7803 - rustc_incremental::persist::hash::HashContext::hash::h876cca71df6046a3
  13:        0x10c4b175e - rustc_incremental::persist::save::save_dep_graph::h02ed61b4823272f8
  14:        0x10b43d5ef - rustc_driver::driver::phase_4_translate_to_llvm::h54e99578fb1bb696
  15:        0x10b47cae4 - rustc_driver::driver::compile_input::_{{closure}}::h7236bd0d96fe8ce9
  16:        0x10b471d47 - rustc_driver::driver::phase_3_run_analysis_passes::_{{closure}}::h7f2cec505064b4bf
  17:        0x10b3ca087 - rustc::ty::context::TyCtxt::create_and_enter::hab8fd8369376d0f6
  18:        0x10b42ceeb - rustc_driver::driver::compile_input::hb4cc34cf85dc1edf
  19:        0x10b45394c - rustc_driver::run_compiler::h50f95674bd902ab5
  20:        0x10b39f166 - std::panicking::try::call::h4577500a5284c6ff
  21:        0x1100166aa - __rust_maybe_catch_panic
  22:        0x10b3b8a2b - _<F as alloc..boxed..FnBox<A>>::call_box::h24f3eb0b42327962
  23:        0x11000c975 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  24:     0x7fff96be899c - _pthread_body
  25:     0x7fff96be8919 - _pthread_start

error: Could not compile `libc`.
```

**Comment by Mark-Simulacrum** [comment] 2017-05-10 19:20
Cannot reproduce today, closing.

**Closed by Mark-Simulacrum** 2017-05-10 19:20 UTC
