### ISSUE TITLE
The links in the chapter about compiler plugins are broken.

### ISSUE THREAD

**Issue by Ticki** [rust-lang/rust#31569] opened 2016-02-11 09:02 UTC
The doc links are broken. cc @steveklabnik

**Comment by TimNN** [comment] 2016-02-11 10:46
Duplicate of #29893.

At the moment you can find these docs (hosted by @Manishearth) here: https://github.com/Manishearth/rust-internals-docs.

**Comment by steveklabnik** [comment] 2016-02-11 13:20
Yup!

**Closed by steveklabnik** 2016-02-11 13:20 UTC
