### ISSUE TITLE
unused-qualifications lint: Triggers in macro expansions while it should not

### ISSUE THREAD

**Issue by Sindbad-Walter** [rust-lang/rust#130277] opened 2024-09-12 14:36 UTC
Hello ! 

The "unused-qualifications" lint is currently being applied to macro expansions, which it should not be in my opinion. This can be annoying when using macros from external crates as we have not the hand on it. Below is a Minimal Reproducible Example on diesel, using rust 1.81.0.

## Minimal Reproducible Example

```rust
// Cargo.toml
[package]
name = "unused_qualifications_example"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "=2.2.0", features = ["postgres"] }
```

```rust
// src/main.rs
#![warn(unused_qualifications)]

#[derive(Debug, diesel::QueryableByName)]
struct RawTagValueStats {
    #[diesel(sql_type = diesel::sql_types::VarChar)]
    _tag_value: String,
}

fn main() {
    println!("This is a minimal example to demonstrate the unused-qualifications lint issue.");
}

```

## Current Behavior

When compiling this code we get the following warnings:

```rust
warning: unnecessary qualification
 --> src/main.rs:8:5
  |
8 |     _tag_value: String,
  |     ^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![warn(unused_qualifications)]
  |         ^^^^^^^^^^^^^^^^^^^^^
help: remove the unnecessary path segments
  |
8 |     _tag_value: String,
  |

warning: `unused_qualifications_example` (bin "unused_qualifications_example") generated 1 warning (run `cargo fix --bin "unused_qualifications_example"` to apply 1 suggestion)`
```
If I have missed crucial information, please let me know and I'll add it. 
Thank you for your help ! 🙏

**Comment by jieyouxu** [comment] 2024-09-16 01:09
Actually AFAICT `unused_qualifications` is already correctly guarded against macro expansions so as long as the spans constructed have proper hygiene:

https://github.com/rust-lang/rust/blob/d696a27c13a0a262a3e848859e300c700889e782/compiler/rustc_resolve/src/late.rs#L4888-L4892

I suspect `diesel`'s proc-macro here has improper hygiene on the span for whatever name is triggering the lint, because with improper hygiene `Span::from_expansion` will return `false`.

**Comment by jieyouxu** [comment] 2024-09-16 02:12
I checked out diesel@v2.2.0, then edited `diesel_derives/src/queryable_by_name.rs` to use mixed-site hygiene for the field spans:

```diff
[10:08] Joe:diesel (fix-hygiene) | git diff v2.2.0 -U3
diff --git a/diesel_derives/src/queryable_by_name.rs b/diesel_derives/src/queryable_by_name.rs
index 16763059a..75c392d1d 100644
--- a/diesel_derives/src/queryable_by_name.rs
+++ b/diesel_derives/src/queryable_by_name.rs
@@ -1,4 +1,4 @@
-use proc_macro2::TokenStream;
+use proc_macro2::{TokenStream, Span};
 use quote::quote;
 use syn::{parse_quote, parse_quote_spanned, DeriveInput, Ident, LitStr, Result, Type};

@@ -44,7 +44,7 @@ pub fn derive(item: DeriveInput) -> Result<TokenStream> {

     for field in model.fields() {
         let where_clause = generics.where_clause.get_or_insert(parse_quote!(where));
-        let span = field.span;
+        let span = Span::mixed_site().located_at(field.span);
         let field_ty = field.ty_for_deserialize();
         if field.embed() {
             where_clause
@@ -62,7 +62,7 @@ pub fn derive(item: DeriveInput) -> Result<TokenStream> {
         let field_check_bound = model.fields().iter().filter(|f| !f.embed()).flat_map(|f| {
             backends.iter().map(move |b| {
                 let field_ty = f.ty_for_deserialize();
-                let span = f.span;
+                let span = Span::mixed_site().located_at(f.span);
                 let ty = sql_type(f, model).unwrap();
                 quote::quote_spanned! {span =>
                     #field_ty: diesel::deserialize::FromSqlRow<#ty, #b>
```

Tested locally with

```toml
diesel = { path = "../diesel/diesel/", features = ["postgres"] }
```

Seems to not trigger `unused_qualifications` anymore because now `Span::from_expansion` will return `false`, whereas

```toml
diesel = { git = "https://github.com/diesel-rs/diesel", tag = "v2.2.0", features = ["postgres"] }
```

unmodified does.

**Comment by jieyouxu** [comment] 2024-09-16 02:16
My guess is that the related issue you were trying to workaround in diesel (as in `#[derive(diesel::Insertable)]` has the same root cause, that whatever span that came from the user code was naively forwarded by the proc-macro without modifying hygiene.

**Comment by jieyouxu** [comment] 2024-09-16 02:18
Unless there is more evidence that this is indeed a bug in the implementation of the `unused_qualifications` lint, I'm going to close this issue as "not-a-bug in rustc but a bug in the library".

**Closed by jieyouxu** 2024-09-16 02:18 UTC
Labels: C-discussion, L-unused_qualifications
