### ISSUE TITLE
rustbuild does not track changes to dependencies properly

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#35202] opened 2016-08-02 22:04 UTC
```
$ python src/bootstrap/bootstrap.py --step libstd --stage 2
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc v0.0.0 (file:///home/nagisa/Documents/rust/rust/src/librustc)
^CTraceback (most recent call last):
  File "src/bootstrap/bootstrap.py", line 413, in <module>
    main()
  File "src/bootstrap/bootstrap.py", line 406, in main
    rb.run(args, env)
  File "src/bootstrap/bootstrap.py", line 267, in run
    ret = proc.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
$ vim src/librustc_llvm/build.rs
$ python src/bootstrap/bootstrap.py --step libstd --stage 2
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc_llvm v0.0.0 (file:///home/nagisa/Documents/rust/rust/src/librustc_llvm)
^CTraceback (most recent call last):
  File "src/bootstrap/bootstrap.py", line 413, in <module>
    main()
  File "src/bootstrap/bootstrap.py", line 406, in main
    rb.run(args, env)
  File "src/bootstrap/bootstrap.py", line 267, in run
    ret = proc.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
$ python src/bootstrap/bootstrap.py --step libstd --stage 2
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc v0.0.0 (file:///home/nagisa/Documents/rust/rust/src/librustc)
^CTraceback (most recent call last):
  File "src/bootstrap/bootstrap.py", line 413, in <module>
    main()
  File "src/bootstrap/bootstrap.py", line 406, in main
    rb.run(args, env)
  File "src/bootstrap/bootstrap.py", line 267, in run
    ret = proc.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1658, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1608, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

What you see in this snippet is:
1. A compilation after rustc_llvm is already built. The bootstrap script attempts to build librustc next.
2. I change a source file for librustc_llvm;
3. On a first re-run of bootstrap script, the change is properly detected, but I cancel the build before librustc_llvm build completes;
4. On a 2nd re-run of the script, change to librustc_llvm is seemingly forgotten, and it attempts to build librustc as if librustc_llvm was already built, although the build was cancelled.

To successfully reproduce this issue it seems like it might be necessary to get timing of cancelling the build in step 3 just right. To reproduce this issue 2nd time it took me 2 or 3 attempts to do the step 3.

cc @alexcrichton

**Comment by alexcrichton** [comment] 2016-08-08 16:58
This may just be a Cargo bug because rustbuild is relying on Cargo to detect this kind of change to files, so it may be helpful to reproduce without rustbuild and report an issue to rust-lang/cargo

**Comment by Mark-Simulacrum** [comment] 2019-08-11 19:02
Closing as I believe this is indeed a Cargo bug; and possibly has been fixed since 2016(!), as I recall some recent work in this area.

**Closed by Mark-Simulacrum** 2019-08-11 19:02 UTC
Labels: A-rustbuild, C-bug
