### ISSUE TITLE
Improve 'not all control paths return a value' message

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#29307] opened 2015-10-25 18:44 UTC
Given the code:

```rust
fn foo() -> u16 {
    1;
}
```

Rustc shows the error:

```
error: not all control paths return a value [E0269]
```

However, I think this is slightly misleading. There isn't actual a control path here, just a semicolon that shouldn't be there.

I think rustc should say something like "function does not return a value" when the last expression in a function is a simple expression without any control flow.

**Comment by nagisa** [comment] 2015-10-25 18:49
Dupe of https://github.com/rust-lang/rust/issues/21838

**Comment by dylanmckay** [comment] 2015-10-27 03:47
This is caused because [liveliness analysis](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/liveness.rs#L1486) will only print the semicolon warning if the types of the last statement and the return value of the function are equivalent.

I have a fix incoming.

**Comment by birkenfeld** [comment] 2016-05-01 20:36
Duplicate of #30497.

**Closed** 2016-05-02 04:54 UTC
Labels: A-diagnostics
