### ISSUE TITLE
Const generic param disappears after rustfmt

### ISSUE THREAD

**Issue by n3d-qmp** [rust-lang/rust#124942] opened 2024-05-09 19:36 UTC
I tried <a href="https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=97cc9583bfbd3ae6a3210d3a4b2e1257">this code</a>:

```rust
#![feature(generic_const_items)]
trait Trait {
    const N: isize;
}

const C<T: Trait>: isize = T::N;
```

After rustfmt generic param disappears: 
```rust
#![feature(generic_const_items)]
trait Trait {
    const N: isize;
}

const C: isize = T::N;
```

### Meta

`rustc --version --verbose`:
Tested on playground

**Comment by fmease** [comment] 2024-05-10 09:43
In the future, please report rustfmt-specific issues over at [rust-lang/rustfmt](https://github.com/rust-lang/rustfmt).

Duplicate of rust-lang/rustfmt#5995.

**Closed by fmease** 2024-05-10 09:43 UTC
Labels: C-bug, A-const-generics, requires-nightly, A-rustfmt, F-generic_const_items
