### ISSUE TITLE
Infinite memory use with nested * repetition in macro

### ISSUE THREAD

**Issue by mindcat** [rust-lang/rust#24858] opened 2015-04-27 06:22 UTC
Play rust link: http://is.gd/DVjBtk
```Rust
macro_rules! a {(<$($($d:expr),*$($c:ident),*)*>) => (B<$($d,)*$($c,)*>);}a! (<>);
```

**Comment by huonw** [comment] 2015-10-12 06:24
Minimal example:

```rust
macro_rules! a {
    ($($($d:tt)*)*) => ();
}

a!();
```

**Comment by SCareAngel** [comment] 2015-10-12 15:10
So problem code is double repetition?
Is there any workaround?

**Comment by jonas-schievink** [comment] 2015-10-13 14:49
I don't think the root problem is a double-repetition, but rather a repetition of something that can be 0 tokens long. In this case `$($d:tt)*` can contain 0 tokens, which then cause the memory explosion on the attempt to repeat it. Replacing the inner repetition with `$($d:tt)+` prevents this bug, changing the outer repetition to use `+` doesn't.

See #28085, which I think is a duplicate of this (tl;dr: replacing the matcher with just `$()+` or `$()*` also causes this).

**Comment by jonas-schievink** [comment] 2015-10-29 11:29
Also, this looks like a duplicate of #5067

**Closed** 2015-10-29 16:08 UTC
Labels: A-macros, I-crash
