### ISSUE TITLE
ICE `rustc' panicked at expected `NodeId` when using `if let` in combination with a boolean test

### ISSUE THREAD

**Issue by digitalatigid** [rust-lang/rust#84795] opened 2021-05-01 20:53 UTC
### Code
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6f6c4cd7d48b722c8a675ad0072b34e4)
```Rust
fn main() {
    let a = Some("world");
    let b = true;
    if let Some(text) = a && b {
        println!("hello {}", text);
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1
```
<details><summary>rustc 1.53.0-nightly (42816d61e 2021-04-24) gives a reasonable error message and does not panic:</summary>

```
$ rustc +nightly oops.rs
error[E0658]: `let` expressions in this position are experimental
 --> oops.rs:4:8
  |
4 |     if let Some(text) = a && b {
  |        ^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
  = help: add `#![feature(let_chains)]` to the crate attributes to enable
  = help: you can write `matches!(<expr>, <pattern>)` instead of `let <pattern> = <expr>`

error: `let` expressions are not supported here
 --> oops.rs:4:8
  |
4 |     if let Some(text) = a && b {
  |        ^^^^^^^^^^^^^^^^^^
  |
  = note: only supported directly without parentheses in conditions of `if`- and `while`-expressions, as well as in `let` chains within parentheses

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
```

</details>

### Error output

```
thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(24),
)', compiler/rustc_ast_lowering/src/lib.rs:714:17
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ rustc oops.rs
error[E0658]: `let` expressions in this position are experimental
 --> oops.rs:4:8
  |
4 |     if let Some(text) = a && b {
  |        ^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(24),
)', compiler/rustc_ast_lowering/src/lib.rs:714:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: rustc_ast_lowering::LoweringContext::lower_node_id_generic
   3: rustc_ast_lowering::path::<impl rustc_ast_lowering::LoweringContext>::lower_qpath
   4: rustc_data_structures::stack::ensure_sufficient_stack
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
   7: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
   8: rustc_data_structures::stack::ensure_sufficient_stack
   9: rustc_data_structures::stack::ensure_sufficient_stack
  10: rustc_data_structures::stack::ensure_sufficient_stack
  11: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  12: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  15: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_exprs
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_ast_lowering::LoweringContext::lower_stmt
  18: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  19: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  20: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  21: rustc_arena::cold_path
  22: rustc_ast_lowering::LoweringContext::lower_block
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_ast_lowering::LoweringContext::lower_stmt
  25: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  26: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  27: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  28: rustc_arena::cold_path
  29: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if
  30: rustc_data_structures::stack::ensure_sufficient_stack
  31: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  32: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  33: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  34: rustc_arena::cold_path
  35: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_fn_body_block
  36: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_maybe_async_body
  37: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_item
  38: rustc_ast_lowering::LoweringContext::with_hir_id_owner
  39: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  40: rustc_ast_lowering::lower_crate
  41: rustc_interface::passes::BoxedResolver::access::{{closure}}
  42: rustc_interface::passes::configure_and_expand::{{closure}}
  43: rustc_interface::passes::BoxedResolver::access
  44: rustc_interface::queries::Queries::lower_to_hir
  45: rustc_interface::queries::Queries::global_ctxt
  46: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  47: rustc_span::with_source_map
  48: rustc_interface::interface::create_compiler_and_run
  49: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

</p>
</details>

**Comment by hellow554** [comment] 2021-05-03 05:57
Duplicate of https://github.com/rust-lang/rust/issues/82290#issuecomment-782114654 which has been fixed by https://github.com/rust-lang/rust/commit/f0637e4e185e8c3dda694004d1dfd31126ed1fbd so it should not occur on nightly and next stable. Can you check that please @digitalatigid

**Comment by digitalatigid** [comment] 2021-05-03 13:24
Beta and Nightly do not panic when compiling and instead show an appropriate error message. (`rustc 1.52.0-beta.7 (9a1dfd2dc 2021-04-30)` and `rustc 1.53.0-nightly (42816d61e 2021-04-24)`)

**Comment by hellow554** [comment] 2021-05-03 14:02
Then you can close this issue (:

Thanks for the report!

**Closed** 2021-05-03 19:20 UTC
Labels: C-bug, I-ICE, T-compiler
