### ISSUE TITLE
[ER] A simple case of missed type inference

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#94519] opened 2022-03-02 11:06 UTC
A type inference problem:

```rust
#![feature(generic_arg_infer)]
fn main() {
    let foo = |x| x + x; // OK
    let _a = foo(10_u8);

    let bar = |[a,b,c,d,e,f,g,h,i]: [_; _]| [c,f,i,b,e,h,a,d,g]; // OK
    let _b = bar([0_u8; 9]);

    let spam = |[a,b,c,d,e,f,g,h,i]| [c,f,i,b,e,h,a,d,g]; // error[E0282]: type annotations needed
    let _c = spam([0_u8; 9]);
}
```

In the second case the added : [_; _] adds very little information, at best it just states it's an array. I think Rustc could perform this little step and accept the "spam" case too.

**Comment by scottmcm** [comment] 2022-03-05 00:36
Possible dup of #76342 where it was pointed out that references are also possible: the `spam` closure could also validly type as `&[T; 9] -> [&T; 9]`.  It's always unclear to me when closures can care about things after themselves, to pick up call here that would disambiguate the rest of the way.

**Comment by leonardo-m** [comment] 2022-03-07 10:58
related:

    let test = |[[a,b,c], [d,e,f], [g,h,i]]: [[_; _]; _]| [[g,d,a], [h,e,b], [i,f,c]];

**Comment by jyn514** [comment] 2023-04-26 02:53
I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/76342; I think they have the same cause, that `[a,b,c,d,e,f,g,h,i]` could be inferred as either an array or a slice.

**Closed by jyn514** 2023-04-26 02:53 UTC
