### ISSUE TITLE
rustc fails to resolve trait implementation

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/rust#84548] opened 2021-04-25 12:10 UTC
I tried this code:

```rust
trait A<T> {
    fn a() -> T;
}

pub struct GlobalA;

impl A<usize> for GlobalA {
    fn a() -> usize {
        0
    }
}

pub struct GlobalB;

impl<T> A<Vec<T>> for GlobalB
where GlobalA: A<T>
{
    fn a() -> Vec<T> {
        let s: usize = GlobalA::a();
        let mut v = Vec::with_capacity(s);
        for _ in 0..s {
            v.push(GlobalA::a());
        }
        v
    }
}
```

I expected to see this happen:
Compile successfully.

Instead, this happened:
```
error[E0308]: mismatched types
  --> src/lib.rs:19:24
   |
15 | impl<T> A<Vec<T>> for GlobalB
   |      - this type parameter
...
19 |         let s: usize = GlobalA::a();
   |                -----   ^^^^^^^^^^^^ expected `usize`, found type parameter `T`
   |                |
   |                expected due to this
   |
   = note:        expected type `usize`
           found type parameter `T`

error: aborting due to previous error
```

Wrote `<GlobalA as A<usize>>::a()` as a workaround.

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: aarch64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by fmease** [comment] 2024-01-23 23:15
Closing as duplicate of Closing as duplicate of #24066.

**Closed by fmease** 2024-01-23 23:15 UTC
Labels: A-traits, A-inference, C-bug, T-types
