### ISSUE TITLE
[ER] Suggest from() instead of as for bool -> int/FP conversions.

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#92820] opened 2022-01-12 17:58 UTC
Currently for wrong code like this:

```rust
fn foo(x: u64, y: u32) -> bool {
    x == y
}
```

rustc suggests to use into():

```rust
error[E0308]: mismatched types
 --> .../test.rs:2:10
  |
2 |     x == y
  |          ^ expected `u64`, found `u32`
  |
help: you can convert a `u32` to a `u64`
  |
2 |     x == y.into()
  |           +++++++
```

For code like this:

```rust
fn foo(a: usize, b: usize) -> usize {
    (a != b) as usize
}
```

rustc could suggest to use instead from():

```rust
fn foo(a: usize, b: usize) -> usize {
    usize::from(a != b)
}
```

**Comment by compiler-errors** [comment] 2022-01-12 21:17
What's wrong with `(a != b) as usize`? `usize::from` uses `self as bool` [under the hood](https://doc.rust-lang.org/src/core/convert/num.rs.html#45-98).

**Comment by leonardo-m** [comment] 2022-01-12 21:32
The usage of "as" hard casts should be avoided and discouraged when possible. Hard "as" casts are sharp tools that can be dangerous. Rust offers from/into to replace casts where a conversion is statically known to be lossless.

**Comment by compiler-errors** [comment] 2022-01-12 21:43
This seems like a duplicate of #90467, and I agree that since this is not an error and doesn't hint at possible bugs (e.g. an unused `mut` lint), so it might be better implemented in clippy.

**Comment by Dylan-DPC** [comment] 2023-02-20 11:41
Closing this as duplicate of #90467

**Closed by Dylan-DPC** 2023-02-20 11:41 UTC
