### ISSUE TITLE
Superlinear compile time for large arrays of constants

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#52868] opened 2018-07-30 16:06 UTC
```rust
pub static FIELDS: [&i32; BIG_NUMBER] =[
    &("bar", 42, "foo", 3.14).1,
   ...
];
```
takes superlinear time to compile as `BIG_NUMBER` increases:
```
6 * 1024: 4s
12 * 1024: 20s
24 * 1024: 131s
```
Built using `CARGO_INCREMENTAL=0 cargo build --release` on current nightly.

Looks at least quadratic to me.

Cc @oli-obk 

<details><summary>Python script to generate code</summary>

```python
#!/usr/bin/python3
import sys

SIZE = int(sys.argv[1]) * 1024

def print_array_elems(elem):
    sys.stdout.write("[\n")
    for i in range(SIZE):
        sys.stdout.write("    "+elem+",\n")
    sys.stdout.write("]")

def print_array(name, elem_type, elem):
    sys.stdout.write("pub static {}: [{}; {}] =".format(name, elem_type, SIZE))
    print_array_elems(elem)
    sys.stdout.write(";\n")

print_array("FIELDS", "&i32", '&("bar", 42, "foo", 3.14).1')
```

</details>

**Comment by nagisa** [comment] 2018-07-30 19:08
This, I believe, is a duplicate of… (takes a look through I-compiletime)… let’s say https://github.com/rust-lang/rust/issues/37155.

**Comment by RalfJung** [comment] 2018-08-06 13:01
FWIW, the quadratic time occurs already with nightly-2018-07-07, i.e., before the CTFE loop checker landed.

**Comment by nagisa** [comment] 2018-08-06 13:52
Lets close this in order to not clutter the issue list then.

**Comment by nagisa** [comment] 2018-08-06 13:53
Since I’m pretty sure this is a duplicate of one of those I-compile time issues. I encourage to post your test case on one of those.

**Closed by nagisa** 2018-08-06 13:52 UTC
