### ISSUE TITLE
Can't mutably borrow out of box pattern twice

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#31667] opened 2016-02-15 02:48 UTC
See the following code
```rust
#![feature(box_patterns)]

struct A {
    b: u8,
    c: u8,
}

struct S<T>(T);

fn foo_s(a: &mut Option<S<A>>) {
    match a {
        &mut Some(S(A{ref mut b,ref mut c})) => println!("{}{}",b,c),
        &mut None => println!("none")
    }
}

fn foo_box(a: &mut Option<Box<A>>) {
    match a {
        &mut Some(box A{ref mut b,ref mut c}) => println!("{}{}",b,c),
        &mut None => println!("none")
    }
}
```
`foo_s` compiles fine, but `foo_box` generates an error:
```
<anon>:19:35: 19:44 error: cannot borrow `a.0` (here through borrowing `a.0.c`) as mutable more than once at a time [E0499]
<anon>:19         &mut Some(box A{ref mut b,ref mut c}) => println!("{}{}",b,c),
                                            ^~~~~~~~~
<anon>:19:35: 19:44 help: see the detailed explanation for E0499
<anon>:19:25: 19:34 note: previous borrow of `a.0` occurs here (through borrowing `a.0.b`); the mutable borrow prevents subsequent moves, borrows, or modification of `a.0` until the borrow ends
<anon>:19         &mut Some(box A{ref mut b,ref mut c}) => println!("{}{}",b,c),
                                  ^~~~~~~~~
<anon>:21:6: 21:6 note: previous borrow ends here
<anon>:18     match a {
<anon>:19         &mut Some(box A{ref mut b,ref mut c}) => println!("{}{}",b,c),
<anon>:20         &mut None => println!("none")
<anon>:21     }
              ^
```

**Comment by apasel422** [comment] 2016-02-16 03:16
This looks like a duplicate of #30104.

**Comment by alexcrichton** [comment] 2016-02-16 05:58
Indeed!

**Closed by alexcrichton** 2016-02-16 05:58 UTC
Labels: A-borrow-checker
