### ISSUE TITLE
TEXTREL in i686 since 1.41.0

### ISSUE THREAD

**Issue by Cogitri** [rust-lang/rust#68794] opened 2020-02-03 11:10 UTC
Hello,

I'm in the process of upgrading Rust to 1.41.0 on Alpine Linux and it appears that a TEXTREL has been introduced in 1.41.0:

```
TEXTREL /usr/lib/librustc_macros-4cbed8a36ab240e8.so
```

The full build log is located here if it's of interest: https://gitlab.alpinelinux.org/Cogitri/aports/-/jobs/44396

**Comment by jonas-schievink** [comment] 2020-02-05 20:56
This apparently breaks Android builds, since that forbids text relocations

**Comment by awakecoding** [comment] 2020-02-05 20:57
+1 I am one of the unfortunate winner of a release-blocking CI build failure for Android now that we've upgraded to 1.41.0. We've disabled android-x86 builds for now :(

**Comment by brainlock** [comment] 2020-02-06 00:49
I added a minimal repro to my repository here: https://github.com/brainlock/rust-1.41-android-linker-bug-repro, in the hope that it can help debugging this (and because I was curious to dig into this myself :-) ).

You can clone the repo, then

```docker build -t repro  .```

```docker run --rm -it repro bash```

In the container you can run `./repro-min.sh`.

I bisected it using rustup and nightly releases, 2012-12-09 is good, 2019-12-10 is bad:

```
root@dea5c1fdc0d5:/usr/src/repro# rustup default nightly-2019-12-09
info: using existing install for 'nightly-2019-12-09-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2019-12-09-x86_64-unknown-linux-gnu'

  nightly-2019-12-09-x86_64-unknown-linux-gnu unchanged - rustc 1.41.0-nightly (59947fcae 2019-12-08)

root@dea5c1fdc0d5:/usr/src/repro# ./repro-min.sh
   Compiling repro v0.1.0 (/usr/src/repro)
    Finished release [optimized] target(s) in 0.20s
root@dea5c1fdc0d5:/usr/src/repro# rustup default nightly-2019-12-10
info: using existing install for 'nightly-2019-12-10-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2019-12-10-x86_64-unknown-linux-gnu'

  nightly-2019-12-10-x86_64-unknown-linux-gnu unchanged - rustc 1.41.0-nightly (76a252ea9 2019-12-09)

root@dea5c1fdc0d5:/usr/src/repro# ./repro-min.sh
   Compiling repro v0.1.0 (/usr/src/repro)
    Finished release [optimized] target(s) in 0.20s
ld: target/i686-unknown-linux-gnu/release/librepro.a(std-c3eaafedbae89cb4.std.52ue7rpt-cgu.0.rcgu.o): warning: relocation against `__rust_probestack' in read-only section `.text._ZN3std3sys4unix2fs4copy17h783e034bf468da7dE'
ld: warning: creating a DT_TEXTREL in a shared object
root@dea5c1fdc0d5:/usr/src/repro#
```

When using nightly-2019-12-10:
```
root@28bb5be323b6:/usr/src/repro# rustc --version
rustc 1.41.0-nightly (76a252ea9 2019-12-09)
```

**Comment by Mark-Simulacrum** [comment] 2020-02-06 01:09
Conveniently, no rollups!

76a252ea9e7 Auto merge of #67110 - tmandry:bump-compiler-builtins, r=alexcrichton
7de9402b77d Auto merge of #67096 - mark-i-m:fix-rustc-guide-2, r=ehuss
3ff17e7c5fa Auto merge of #67016 - lqd:placeholder_loans, r=matthewjasper
dbbe4f10fa6 Auto merge of #67004 - estebank:issue-66958, r=eddyb
2b0e6d2643e Auto merge of #67003 - cjgillot:corrida, r=Mark-Simulacrum
14195e1f1dc Auto merge of #66984 - GuillaumeGomez:move-clean-types, r=kinnison

I would personally suspect #67110.

Can you try checking this via https://crates.io/crates/rustup-toolchain-install-master/?

**Comment by brainlock** [comment] 2020-02-06 08:46
While rustup-toolchain-install-master compiles ( 😅 ): I see that `https://github.com/rust-lang/rust/pull/67110` upgrades compiler-builtins. I had a look at the commits in compiler-builtins which touch `__rust_probestack`, and I think we can likely narrow it down to https://github.com/rust-lang/compiler-builtins/commit/2566aa663bef6e8ebc6379de81b538b2d6327a9d.

At this point I'm too much out of my depth, this needs people more knowledgeable than me 😉 . I hope I could help debugging this, and will continue watching the issue as I'm learning a great deal just by investigating this.

Besides the actual fix, there are two additional things I'd love to understand:

1) why doesn't `scanelf -qT std-c3eaafedbae89cb4.std.52ue7rpt-cgu.0.rcgu.o` detect this? It looks like the obj file is not marked in any way has having a TEXTREL, but maybe the inline asm from that commit defines __rust_probestack in such a way that relocating it needs touching the .text section (wild guess)

2) how would we go at testing this? Where in the rust project would I add a test for this? And given that scanelf can't detect this, maybe a good way to "integration test" this would be to build a minimal rust static lib, and try to link it into a shared object with `--warn-shared-textrel --fatal-warnings` like I'm doing in the repro code. Do I understand correctly that "all code produced by rustc should be relocatable" is a guaranteed property (thus worth testing), or am I completely mistaken?

**Comment by brainlock** [comment] 2020-02-06 09:10
Meanwhile, I can confirm that we got the right commit (76a252ea9e7be93a61ffdf33b3533e24a9cf459d):

```
albe@myo ~/code/repro [master] % docker build -t repro .
[...]
albe@myo ~/code/repro [master] % docker run --rm -it repro bash
root@c74a4c84b096:/usr/src/repro# rustup default 76a252ea9e7be93a61ffdf33b3533e24a9cf459d
info: default toolchain set to '76a252ea9e7be93a61ffdf33b3533e24a9cf459d'
root@c74a4c84b096:/usr/src/repro# rustc --version
rustc 1.41.0-nightly (76a252ea9 2019-12-09)
root@c74a4c84b096:/usr/src/repro# ./repro-min.sh
ld: target/i686-unknown-linux-gnu/release/librepro.a(std-c3eaafedbae89cb4.std.52ue7rpt-cgu.0.rcgu.o): warning: relocation against `__rust_probestack' in read-only section `.text._ZN3std3sys4unix2fs4copy17h783e034bf468da7dE'
ld: warning: creating a DT_TEXTREL in a shared object
root@c74a4c84b096:/usr/src/repro#
root@c74a4c84b096:/usr/src/repro#
root@c74a4c84b096:/usr/src/repro# rustup default 7de9402b77ded0d8ec9e1c554521b2121449ef2b
info: default toolchain set to '7de9402b77ded0d8ec9e1c554521b2121449ef2b'
root@c74a4c84b096:/usr/src/repro# rustc --version
rustc 1.41.0-nightly (7de9402b7 2019-12-09)
root@c74a4c84b096:/usr/src/repro# ./repro-min.sh
root@c74a4c84b096:/usr/src/repro# echo $?
0
root@c74a4c84b096:/usr/src/repro#
```

**Comment by pnkfelix** [comment] 2020-02-06 12:35
triage: P-high. Assigning to self. Leaving nominated because I'd like to discuss this at today's meeting.

**Comment by nikomatsakis** [comment] 2020-02-06 15:37
cc @tmandry, who did the rollup of compiler-builtins, do we know which of the following PRs may have caused the problem

- rust-lang/compiler-builtins#306
- rust-lang/compiler-builtins#309
- rust-lang/compiler-builtins#310
- rust-lang/compiler-builtins#311
- rust-lang/compiler-builtins#312
- rust-lang/compiler-builtins#313
- rust-lang/compiler-builtins#315
- rust-lang/compiler-builtins#317
- rust-lang/compiler-builtins#323
- rust-lang/compiler-builtins#324
- rust-lang/compiler-builtins#328

@pnkfelix hypothesizes https://github.com/rust-lang/compiler-builtins/pull/328, do you know that this could be the cause, @tmandry?

**Comment by tmandry** [comment] 2020-02-07 01:01
It could be. Likely the difference is in the attributes of the probestack function (before that change it was a `#[naked]` rust function, afterward it was defined in raw assembly).

@brianlock could you try adding the line `.hidden __rust_probestack` around [here](https://github.com/rust-lang/compiler-builtins/blob/master/src/probestack.rs#L65)?

If that fixes it, it may break it in other environments (e.g. when generating code for a shared vs static library). We'd probably need to thread some new cfg flags through, but I'm not sure if that's actually possible.

The other way is going back to defining the assembly in a naked function, but [a bug, probably in rustc](https://github.com/rust-lang/compiler-builtins/pull/328#issuecomment-561975210), prevented me from doing this the first time.

cc @alexcrichton

**Comment by Mark-Simulacrum** [comment] 2020-02-07 01:13
cc @Amanieu (though they're on vacation this week I believe) on the inline assembly options as potentially relevant for RFC and if they have thoughts on how to fix it for this case

**Comment by alexcrichton** [comment] 2020-02-07 13:55
I would agree with the conclusion that https://github.com/rust-lang/compiler-builtins/pull/328 is the most likely candidate here for a cause of the regression. That being said I have no idea what TEXTREL is, what's happening there to cause it, or how we might fix this.

**Comment by Amanieu** [comment] 2020-02-09 12:20
Looking at the objdump output, you can see the difference between the 2019-12-09 and 2019-12-10 nightlies:

```
2019-12-09:00000000 g     F .text.__rust_probestack	0000002f .hidden __rust_probestack
2019-12-10:00000000 g     F .text.__rust_probestack	00000031 __rust_probestack
```

The textrel happens because the `__rust_probestack` has global visibility and can therefore (in theory) be overridden at runtime, e.g. with LD_PRELOAD. This means that the dynamic linker will need to patch the .text section at load time to fix up the call instruction.

As @tmandry suggested, adding `.hidden __rust_probestack` should fix the problem since the linker will then resolve references to the symbol within the shared library itself.

**Comment by tmandry** [comment] 2020-02-11 00:48
> As @tmandry suggested, adding `.hidden __rust_probestack` should fix the problem since the linker will then resolve references to the symbol within the shared library itself.

That's probably the correct fix then, I'm just not 100% sure it will work on all targets . If it fails we should see it in CI, though.

**Closed** 2020-02-13 01:40 UTC
Labels: A-linkage, C-bug, O-android, O-x86, P-high, T-compiler, regression-from-stable-to-stable

**Comment by Cogitri** [comment] 2020-02-13 10:57
Will this be released in a 1.41.1, or should distros just apply this downstream? We'd very much like Rust 1.41.0 without TEXTRELs on x86.

**Comment by Cogitri** [comment] 2020-02-13 10:57
Also, thanks for the quick fix of course :)

**Comment by Mark-Simulacrum** [comment] 2020-02-13 11:30
I would not currently wait for a 1.41.1 release. I hope that it will make it into 1.42 though.

**Comment by Cogitri** [comment] 2020-02-13 11:33
Alright, thanks for the info.

**Comment by brainlock** [comment] 2020-02-14 13:42
Thanks for fixing this! I verified that this solves the issue on our end, and opened a PR with a simple regression test. The test fails on i686-unknown-linux-gnu when I revert compiler-builtins to 0.1.24.

**Comment by brainlock** [comment] 2020-03-02 10:56
I'm not sure this is the right place to bring it up, but without this fix it is impossible to deploy a rust static library to platforms that enforce properly-relocatable code (x86 android). It didn't make the cut for 1.41.1, is there any chance for 1.42? Can we help to make this happen?

Thanks!

**Comment by mati865** [comment] 2020-03-02 13:49
https://github.com/rust-lang/rust/pull/69086 is beta nominated, it will be backported soon and included in 1.42 release.

**Comment by brainlock** [comment] 2020-03-02 14:07
> #69086 is beta nominated, it will be backported soon and included in 1.42 release.

Fantastic, thanks. Do you think it would be worth it to also include the regression test (#69168) in the release?

**Comment by mati865** [comment] 2020-03-02 14:15
> Do you think it would be worth it to also include the regression test (#69168) in the release?

CCing the reviewers @tmandry @Mark-Simulacrum

**Comment by awakecoding** [comment] 2020-03-02 15:02
awesome, I am waiting for a release with this fix. Any idea when 1.42 is planned?

**Comment by Cogitri** [comment] 2020-03-02 15:54
Stable releases usually occur every 6 weeks, so it should land in ~2 weeks.

**Comment by Mark-Simulacrum** [comment] 2020-03-03 00:41
I've nominated the regression test as well!
