### ISSUE TITLE
Static lifetime deduced for constant, but not for return values of const fn

### ISSUE THREAD

**Issue by hniksic** [rust-lang/rust#90370] opened 2021-10-28 08:30 UTC
In rust borrowed constants have static lifetimes, even if the constants are simple literals in the middle of a function. For example, this compiles:

```rust
fn assert_static(_r: &'static u32) {}
fn main() {
    assert_static(&1); // compiles
}
```

This works even in more involved situations, such as when the "literal" is a macro-generated array of structs whose fields are literals. (That's my actual use case, but I'll refer to the simple case of just having a `u32` for simplicity.)

The problem is that it no longer works if the value is returned by a `const fn`:

```rust
const fn inc(n: u32) -> u32 {
    n + 1
}

fn assert_static(_r: &'static u32) {}

fn main() {
    assert_static(&1);
    assert_static(&inc(1)) // doesn't compile
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8c37fab93f623134ef82f97f9dfaeca6)

```
error[E0716]: temporary value dropped while borrowed
  --> src/main.rs:9:20
   |
9  |     assert_static(&inc(1)) // doesn't compile
   |     ---------------^^^^^^-
   |     |              |
   |     |              creates a temporary which is freed while still in use
   |     argument requires that borrow lasts for `'static`
10 | }
```

I would expect (or rather wish) for the latter code to compile since the former did. Note that, since `const` and `static` are `static`, it is possible to work around it by creating an explicit `const` or `static` inbetween. For example, all of these compile:

```rust
fn main() {
    assert_static(&1);
    {
        const TMP: u32 = inc(1);
        assert_static(&TMP);
    }
    {
        static TMP: u32 = inc(1);
        assert_static(&TMP);
    }
    assert_static({
        const TMP: u32 = inc(1);
        &TMP
    });
    assert_static({
        static TMP: u32 = inc(1);
        &TMP
    });
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f732893f3304164ab41c8134f8024d15)

While a workaround is available, it is not always obvious. Also it would be much nicer not to have to introduce all the temporary constants/statics, especially in code that calls several different const fns.

**Comment by PatchMixolydic** [comment] 2021-10-31 09:42
The `inline_const` feature will allow this to compile at the cost of some visual noise, though it's still less noisy than the workaround needed today ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=606e4dc6a7455386cc5a213512a86573)):

```rust
#![allow(incomplete_features)]
#![feature(inline_const)]

const fn inc(n: u32) -> u32 {
    n + 1
}

fn assert_static(_r: &'static u32) {}

fn main() {
    assert_static(&1);
    assert_static(&const { inc(1) });
}
```

**Comment by RalfJung** [comment] 2021-11-03 15:26
Indeed, this is expected behavior -- promoting `const fn` implicitly can lead to compile errors in code that really ought to compile, besides leading to nightmare consequences within rustc itself. The key difference between `&1` and `&const_fn()` is that the latter might panic or fail to evaluate for other reasons, so we cannot easily treat them the same.

So I will close this issue; the intended convenient way to write such code in the future is via inline consts, tracked at https://github.com/rust-lang/rust/issues/76001.

**Closed by RalfJung** 2021-11-03 15:26 UTC

**Comment by RalfJung** [comment] 2021-11-03 15:27
Oh, also, a shameless plug: I have a little crate that partially implements inline consts as a macro --  https://crates.io/crates/inline-const.
