### ISSUE TITLE
error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:966:9: no MIR available for DefId(20:9953 ~ cranelift_codegen[d26a]::machinst::buffer::{impl#3}::get_srclocs_sorted)

### ISSUE THREAD

**Issue by llaissue** [rust-lang/rust#92886] opened 2022-01-14 08:32 UTC
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (22e491ac7 2022-01-13)
binary: rustc
commit-hash: 22e491ac7ed454d34669151a8b6464cb643c9b41
commit-date: 2022-01-13
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0

```

### Error output

```
<output>
```   Compiling wasmer-compiler-cranelift v2.1.1
   Compiling massa_protocol_exports v0.1.0 (/root/massa/massa-protocol-exports)
   Compiling massa_pool v0.1.0 (/root/massa/massa-pool)
   Compiling massa_protocol_worker v0.1.0 (/root/massa/massa-protocol-worker)
error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:966:9: no MIR available for DefId(20:9953 ~ cranelift_codegen[d26a]::machinst::buffer::{impl#3}::get_srclocs_sorted)

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1169:9


<!--
Include a backtrace in the code block by setting `RUST_BACKTRACE=1` in your
environment. E.g. `RUST_BACKTRACE=1 cargo build`.
-->
<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by CryZe** [comment] 2022-01-14 12:11
Duplicate of https://github.com/rust-lang/rust/issues/92755

**Comment by ehuss** [comment] 2022-01-14 16:08
Closing as a duplicate of #92755.

**Closed by ehuss** 2022-01-14 16:08 UTC
Labels: I-ICE, T-compiler, C-bug
