### ISSUE TITLE
Adding targets for packaged rust installations is very hacky

### ISSUE THREAD

**Issue by yogo1212** [rust-lang/rust#108819] opened 2023-03-06 15:29 UTC
Having installed rust through the package manager on Endeavour OS, adding targets like `wasm32-unknown-unknown` is very painful.

The compiler suggests the installation through `rustup`:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`

error[E0463]: can't find crate for `compiler_builtins`
```

But `rustup` is incompatible with the `rust` package.
Installing a target without rustup is apparently not documented publicly or at all intended.
The manual installation involves listing files on static.rust-lang.org, picking an appropriate version of rust-std, and extracting parts of the archive into the Rust installation dir.
The installation resides in /usr/include/rustlib/ so packaging is advised and then it really gets out of hand.

I don't suppose Rust will become easily packagable any time soon but it would be nice to integrate targets with cargo so they can be used with system installations more nicely.

**Comment by yogo1212** [comment] 2023-03-06 16:10
@ChrisDenton Hello and thanks for your remark!
I'll have to check with Arch Linux then why they made the `rustup` package [conflict](https://github.com/archlinux/svntogit-community/blob/packages/rustup/trunk/PKGBUILD#L17) with `rust`.

**Comment by ChrisDenton** [comment] 2023-03-06 16:25
Maybe because this wasn't always the case? Not sure. There's a [documentation page](https://rust-lang.github.io/rustup/installation/package-managers.html) on using a manual install of rustup with distribution managed rustc. It requires a little bit of setup but I'm not aware of any reason why a package maintainer couldn't do this for you. If there are any issues then these should probably be reported on https://github.com/rust-lang/rustup so the relevant team can look into it.

**Comment by workingjubilee** [comment] 2023-03-06 19:43
@yogo1212 Hello, I also use Arch Linux with a rustup installation (and I am a Rustup contributor). If you use the rustup package, you can use the latest stable rustc, managed by rustup, and have Rustup managed by pacman. Since Rustup takes care of itself when it's uninstalled, and pacman knows where to find Rustup, this means everything is ultimately still fully managed by the package manager. And from the perspective of the distro tools, such as build scripts, etc., essentially the difference is completely invisible. So you can replace the rust package with the rustup package just fine.

**Comment by yogo1212** [comment] 2023-03-07 10:39
i think i'll have to give up the idea of sharing the toolchain across users :-D

**Comment by workingjubilee** [comment] 2023-03-07 23:33
Yes, it's very hard to reconcile "rustup allows you to install a toolchain without escalated privileges" with "you need superuser privileges to invoke the package manager" here. That sort of thing would probably need special support from the package manager, as well.

Honestly, it is fairly unreasonable for a package manager to fully support installing all of the 100 releases that Rustup supports installing.

**Comment by jyn514** [comment] 2023-04-08 17:54
I'm going to close this as not a bug; support for multiple rustup users is tracked in https://github.com/rust-lang/rustup/issues/313 and the Rust project can't control what targets Arch packages.

**Closed by jyn514** 2023-04-08 17:54 UTC

**Comment by Kreijstal** [comment] 2024-03-23 10:33
are there like user packages that add targets?
