### ISSUE TITLE
Importing private reexports does not work

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#32303] opened 2016-03-17 06:49 UTC
Testcase:

``` rust
#![crate_type = "lib"]

use std::vec::Vec as Vec;

mod foo {
    use Vec;
}
```

This should seemingly go through with no issue, but instead:

rustc output:

```
foo.rs:6:9: 6:12 error: unresolved import `Vec`. There is no `Vec` in `???`. Did you mean to use `Vec`? [E0432]
foo.rs:6     use Vec;
                 ^~~
foo.rs:6:9: 6:12 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
```

**Comment by cmr** [comment] 2016-03-17 07:03
Same error:

```rust


#![crate_type = "lib"]

use std::vec::Vec;

mod foo {
    use Vec;
}
```

```rust


#![crate_type = "lib"]

use std::vec::Vec as Foo;

mod foo {
    use Foo;
}
```

**Comment by cmr** [comment] 2016-03-17 07:06
If we don't want to support this feature, the error message should be more specific.

**Comment by petrochenkov** [comment] 2016-03-17 08:20
This is "by design" currently, but it's being fixed in https://github.com/rust-lang/rust/pull/32213 (which probably needs an RFC before merging).

**Closed** 2016-11-21 14:08 UTC
Labels: A-resolve
