### ISSUE TITLE
Rustdoc should mention OIBIT-derived Send/Sync impls

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#25896] opened 2015-05-30 08:09 UTC
The rustdoc output only mentions `Send`/`Sync` impls for types which explicitly opt in or opt out.

There's no easy way to figure out when something is `Send`/`Sync` otherwise, and it's misleading when it seems like most types aren't `Send`/`Sync`.

Perhaps it should autogenerate an impl when OIBIT does so internally? Type param bounds might be hard to handle though.

cc @alexcrichton

**Comment by alexcrichton** [comment] 2015-06-01 16:31
Dupe of https://github.com/rust-lang/rust/issues/17606

**Closed by alexcrichton** 2015-06-01 16:31 UTC
Labels: A-rustdoc, I-enhancement
