### ISSUE TITLE
internal compiler error after downgrade of rust nightly

### ISSUE THREAD

**Issue by edfraenkel** [rust-lang/rust#37865] opened 2016-11-18 17:15 UTC
platform: windows 8
No visual studio was installed yet.
First I installed rust nightly of Nov 18 2016. (msvc ABI)
I ran cargo on my project but unfortunately I ran into a compile error, so I decided to run on an older nightly version in which I knew that my project would work.
I uninstalled rust an re-installed the nightly build of 12 Oct 2016.
Then I ran cargo build again _without_ a clean and I got the backtrace below:
(The error disappears when running cargo clean and then cargo build again.)

```
C:\Users\xpar\Projects\Pilots\Robot\LEDController>cargo build
   Compiling quote v0.3.3
   Compiling serde v0.8.12
   Compiling either v1.0.0
   Compiling num-traits v0.1.36
   Compiling dtoa v0.2.2
   Compiling itertools v0.5.2
   Compiling itoa v0.1.1
   Compiling unicode-xid v0.0.3
   Compiling rustc-serialize v0.3.19
   Compiling syn v0.9.0
   Compiling serde_codegen_internals v0.10.0
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
aster/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'index out of bounds: the len is 18392 but the index
is 18392', ../src/libserialize\leb128.rs:46
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: Could not compile `serde_codegen_internals`.

To learn more, run the command again with --verbose.
```

rustc 1.14.0-nightly (a3bc191b5 2016-10-10)
binary: rustc
commit-hash: a3bc191b5f41df5143cc65084b13999896411817
commit-date: 2016-10-10
host: x86_64-pc-windows-msvc
release: 1.14.0-nightly

**Comment by alexcrichton** [comment] 2016-11-18 19:44
I believe this is a dupe of https://github.com/rust-lang/rust/issues/37803, so closing in favor of that

**Closed by alexcrichton** 2016-11-18 19:44 UTC
