### ISSUE TITLE
Trait Satisfiability Inconsistency

### ISSUE THREAD

**Issue by sheeldotme** [rust-lang/rust#72250] opened 2020-05-15 23:59 UTC
I tried this code:

```rust
#[derive(Default)]
struct Wrapper<T> {
    item: Option<T>
}

fn wrapped_default<T>() -> Wrapper<T> {
    Wrapper {
        ..Default::default()
    }
}

fn main() {
    let x = wrapped_default::<i32>();
}
```

I expected to see this happen:

I expect this to successfully compile because the `Default` trait is satisfied for `Option<T>`.  The compiler shouldn't require `T` to also satisfy the `Default` trait.

The fact that the following compiles successfully also demonstrates this behaviour is currently inconsistent.

```rust
fn test<T>() -> Option<T> {
    Default::default()
}
```

T shouldn't have to satisfy the Default trait in the first case and not in the second.

Instead, this happened:

```
error[E0277]: the trait bound `T: std::default::Default` is not satisfied
 --> src/main.rs:8:11
  |
8 |         ..Default::default()
  |           ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `T`
  |
help: consider restricting this type parameter with `T: std::default::Default`
 --> src/main.rs:6:20
  |
6 | fn wrapped_default<T>() -> Wrapper<T> {
  |                    ^
  = note: required because of the requirements on the impl of `std::default::Default` for `Wrapper<T>`
  = note: required by `std::default::Default::default`
```
### Meta

`rustc --version --verbose`:

```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-05-16 00:00
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2020-05-16 00:00 UTC
Labels: C-bug
