### ISSUE TITLE
Linking 'libstd' fails with "relocation truncated to fit" on 32bit/A7 target.

### ISSUE THREAD

**Issue by robertsonb** [rust-lang/rust#44458] opened 2017-09-09 18:29 UTC
Hello - 

Im not sure where to post this (here, LLVM; or the issue is purely on my end), but I'll start here. 

Trying get the Rust toolchain running inside a Yocto (Poky) system, targeting CortexA7 (iMX6, 32bit). Both the compiler and Cargo build alright; its just building 'libstd' that Im having this particular problem.

Here is the error output Im getting:
[libstd_link_error.txt](https://github.com/rust-lang/rust/files/1290002/libstd_link_error.txt)

It looks like the relocation is exceeding the relative addressing range, and Im not sure if this is due some particulars of building Rust itself, or stdlib, or something else (non Tier1 support?).

**Comment by robertsonb** [comment] 2017-09-10 14:41
Spent some more time on this this morning.

Looking at the assembly for core::ptr::drop_in_place I see:
```asm
00000000 <_ZN4core3ptr13drop_in_place17h032f94189ca657d1E>:
   0:   b570            push    {r4, r5, r6, lr}
   2:   4604            mov     r4, r0
   4:   6860            ldr     r0, [r4, #4]
   6:   b1a8            cbz     r0, 34 <_ZN4core3ptr13drop_in_place17h032f94189ca657d1E+0x34>
   8:   7a20            ldrb    r0, [r4, #8]
   a:   2802            cmp     r0, #2
   c:   bf38            it      cc
   e:   bd70            popcc   {r4, r5, r6, pc}
  10:   68e6            ldr     r6, [r4, #12]
  12:   e9d6 0101       ldrd    r0, r1, [r6, #4]
  16:   6809            ldr     r1, [r1, #0]
  18:   4788            blx     r1
  1a:   68b0            ldr     r0, [r6, #8]
  1c:   6841            ldr     r1, [r0, #4]
  1e:   b119            cbz     r1, 28 <_ZN4core3ptr13drop_in_place17h032f94189ca657d1E+0x28>
  20:   6882            ldr     r2, [r0, #8]
  22:   6870            ldr     r0, [r6, #4]
  24:   f7ff fffe       bl      0 <__rust_deallocate>
  28:   68e0            ldr     r0, [r4, #12]
  2a:   210c            movs    r1, #12
  2c:   2204            movs    r2, #4
  2e:   e8bd 4070       ldmia.w sp!, {r4, r5, r6, lr}
  32:   e7fe            b.n     0 <__rust_deallocate>
  34:   bd70            pop     {r4, r5, r6, pc}
  36:   4605            mov     r5, r0
  38:   68b0            ldr     r0, [r6, #8]
  3a:   6841            ldr     r1, [r0, #4]
  3c:   b119            cbz     r1, 46 <_ZN4core3ptr13drop_in_place17h032f94189ca657d1E+0x46>
  3e:   6882            ldr     r2, [r0, #8]
  40:   6870            ldr     r0, [r6, #4]
  42:   f7ff fffe       bl      0 <__rust_deallocate>
  46:   68e0            ldr     r0, [r4, #12]
  48:   210c            movs    r1, #12
  4a:   2204            movs    r2, #4
  4c:   f7ff fffe       bl      0 <__rust_deallocate>
  50:   4628            mov     r0, r5
  52:   f7ff fffe       bl      0 <_Unwind_Resume>
```
In this particular case I think the `b.n` instruction at offset 32 is wrong (?) because that is a 16bit Thumb2  instruction, that the linker must resolve (currently set to 0 offset). The ARM doc states that it should be considered an error if the jump range exceeds the range of the instruction. 

Note that at offset 42 the `bl` instruction is used which is 32 bits wide.

So now what to do about it?

Some searching around brings up:
1. https://lists.linaro.org/pipermail/linaro-dev/2011-February/002886.html (fits my issue exactly, albeit older)
2. https://github.com/tensorflow/tensorflow/issues/3139 (more recent, and aligns fairly closely).

For my current application, #1 seems to offer a perfect resolution, as a compiler flag ("-fno-optimize-sibling-calls") just constrains optimization and prevent sibling call optimization.

However, I thought Rust didn't support TCO, but after some digging it turns out it does under certain circumstances. What I don't see is what Rust does with Sibling Call Optimizations.

Im still not convinced I understand my problem 100%. However Im willing to run with it and have some actual questions now.

1. Under what conditions, if any, does `rustc` perform SCO's?
2. Is there a way through either `rustc` or LLVM to disable TCO's and SCO's? From the LLVM docs it doesn't seem that way (http://llvm.org/docs/CodeGenerator.html#sibling-call-optimization).

**Comment by robertsonb** [comment] 2017-09-10 15:19
Quick Update -

Just tried to built 'libstd' at O0 and it still failed but (according to the output) only a single function is having issues. At least, I don't see the "... additional relocation overflows omitted from the output ..." message that I would see before, building with --release.

Now Im just getting:
`R_ARM_THM_JUMP11 against symbol `__aeabi_uidiv'`
from core::ops::div.

Not sure if this is actually meaningful or not.

**Comment by robertsonb** [comment] 2017-09-11 13:39
I can workaround this by disabling thumb and just emitting ARM instructions. This works for my current application.

Im not sure if this is considered "working as intended", although it doesn't seem like it to me (could be wrong). So I'll leave open to ensure that someone else at least see's this before it's closed.

**Comment by Enselic** [comment] 2023-09-26 17:24
Triage: Is this still a problem? Wanted to check since 6 years have passed and circumstance might have changed.

**Comment by workingjubilee** [comment] 2024-08-03 05:00
This lacks reproduction instructions, with yocto or otherwise.

But even if it did have one, I'm sorry but I don't think we can really help with builds against yocto's custom targets if those go awry. We do already support multiple 32-bit Arm targets and build and ship libcores for them. Some of our libcore builds _require_ optimizations to work.

This issue seems like it _may_ be related to https://github.com/rust-lang/rust/issues/126527 which is better documented in any case.

As there doesn't seem to be anything left in this issue per se, I am closing it, though somewhat sadly, as it would have been nice to at least confirm a reproducer now succeeds instead of fails. Please let us know if you can recover one.

**Closed by workingjubilee** 2024-08-03 05:00 UTC
Labels: A-linkage, A-LLVM, O-Arm, T-compiler, C-bug
