### ISSUE TITLE
mysql beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43662] opened 2017-08-05 12:42 UTC
All crates that depend on [mysql](https://crates.io/crates/mysql) of various versions can't compile right now. Crater couldn't pick this up as root regression because this is probably a monomorphisation time error or something.

The error ([example log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/dbench-0.1.0/log.txt)):
```
error: type `io::IoPack + 'static` is private
    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/mysql-8.0.0/src/conn/mod.rs:1043:35
     |
1043 |         let (data, seq_id) = try!(self.get_mut_stream().as_mut().read_packet(old_seq_id));
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
cc @blackbeam

Versions that crates depend on:

* v10.0.0 ([dbench](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/dbmigrate-0.3.4/log.txt), [dbmigrate](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/dbmigrate-0.3.4/log.txt), [dbmigrate-lib](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/dbmigrate-lib-0.1.1/log.txt), [mysql-repo](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/mysql-repo-0.1.0/log.txt))
* v8.0.0 ([r2d2_mysql](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/r2d2_mysql-8.0.0/log.txt))
* v11.1.0([https://github.com/0xpr03/yayd#edf4e83a7a922c8069eef8dd0d0320dbc61d2ff4](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/gh/0xpr03.yayd.edf4e83a7a922c8069eef8dd0d0320dbc61d2ff4/log.txt))

**Comment by petrochenkov** [comment] 2017-08-05 12:49
I wasn't a root regression because the last version of `mysql` is good.
Some crates use old versions of `mysql` which leak private types.

**Comment by nikomatsakis** [comment] 2017-08-17 20:31
Probably it'd be good to ping the authors of the affected crates and encourage them to upgrade to the latest mysql, or else backport the fix to the older version. Perhaps after the compiler meeting I will try to scrape those usernames, if someone else doesn't get to it first. =)

**Comment by alexcrichton** [comment] 2017-08-22 21:22
I believe the compiler/lang teams won't be reverting https://github.com/rust-lang/rust/pull/42125, so I'm going to close this regression tracker.

**Closed by alexcrichton** 2017-08-22 21:22 UTC
Labels: C-bug, regression-from-stable-to-beta, T-compiler
