### ISSUE TITLE
ICE on unsound usage of existential types

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#52843] opened 2018-07-30 01:26 UTC
You can construct an existential type that implements traits that it shouldn't have like so:
```rust
#![feature(existential_type)]

existential type Foo<T>: Default;

#[allow(unused)]
fn foo<T: Default>(t: T) -> Foo<T> {
    t
}

struct NotDefault;

fn main() {
    let _ = Foo::<NotDefault>::default();
}
```
[Playground](https://play.rust-lang.org/?gist=710c77002bc679cc8a897658d4d73cea&version=nightly&mode=debug&edition=2015)

As you can see Foo's type parameter T doesn't have a Default bound, but it still implements the Default trait as a whole. If you actually abuse this with a type parameter that doesn't implement Default, you can construct a value even though the type doesn't implement Default. This results in an ICE atm:
```
$ cargo +nightly run
   Compiling unsound-existentials v0.1.0 (file:///C:/Projekte/one-offs/unsound-existentials)
error: internal compiler error: librustc\traits\codegen\mod.rs:68: Encountered error `Unimplemented` selecting `Binder(<NotDefault as std::default::Default>)` during codegen

thread 'main' panicked at 'Box<Any>', librustc_errors\lib.rs:578:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (866a71325 2018-07-29) running on x86_64-pc-windows-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `unsound-existentials`.

To learn more, run the command again with --verbose.
```

This may just be an unimplemented check due to existential types being brand new on nightly.

**Comment by oli-obk** [comment] 2019-01-25 13:52
`foo` should not be a defining use for `Foo`, because its bindings differ.

**Comment by JohnTitor** [comment] 2019-08-08 23:05
Doesn't reproduce in the latest nightly

**Comment by JohnTitor** [comment] 2019-08-08 23:09
Ah, wait, the latest example is [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8407a5bce6a49fce1e66615588993196), this is still ICE.

**Comment by Aaron1011** [comment] 2020-03-04 21:49
Updated version [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=7b8a0917b6be88a0d4d1b359398bf2c6):

```rust
#![feature(type_alias_impl_trait)]

type Foo<T> = impl Default;

#[allow(unused)]
fn foo<T: Default>(t: T) -> Foo<T> {
    t
}

struct NotDefault;

fn main() {
    let _ = Foo::<NotDefault>::default();
}
```

**Comment by JohnTitor** [comment] 2020-10-07 12:49
Triage: This is no longer ICE with the latest nightly, marking as E-needs-test.

**Closed** 2020-10-14 08:55 UTC
Labels: A-impl-trait, C-bug, E-needs-test, F-type_alias_impl_trait, I-ICE, T-compiler, glacier, requires-nightly
