### ISSUE TITLE
codegen regression for bool

### ISSUE THREAD

**Issue by Nugine** [rust-lang/rust#101048] opened 2022-08-26 16:14 UTC
### Code

I tried this code:

<https://rust.godbolt.org/z/3EW6zoffE>

```rust
pub fn all_zero(data: &[u64]) -> bool {
    data.iter().copied().fold(true, |acc, x| acc & (x == 0))
}
```

I expected to see this happen: 
```asm
.LBB0_3:
        cmp     qword ptr [rdi + rcx], 0
        sete    dl
        and     al, dl
        add     rcx, 8
        cmp     rsi, rcx
        jne     .LBB0_3
```

Instead, this happened: 
```asm
.LBB0_3:
        test    al, al
        setne   dl
        cmp     qword ptr [rdi + rcx], 0
        sete    al
        and     al, dl
        add     rcx, 8
        cmp     rsi, rcx
        jne     .LBB0_3
```

There are two unnecessary instructions:

```asm
        test    al, al
        setne   dl
```

### Version it worked on

It most recently worked on: Rust 1.63, Rust beta

### Version with regression

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (748038961 2022-08-25)
binary: rustc
commit-hash: 7480389611f9d04bd34adf41a2b3029be4eb815e
commit-date: 2022-08-25
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by Nugine** [comment] 2022-08-27 04:36
Related (maybe):
+ #101060

**Comment by alion02** [comment] 2022-08-27 19:26
The "canonical" code produces identical (and, since it has early exit, much more performant in most cases) assemblies between versions.

```rust
pub fn all_zero(data: &[u64]) -> bool {
    data.iter().all(|&x| x == 0)
}
```

**Comment by Nugine** [comment] 2022-08-28 03:43
> The "canonical" code produces identical (and, since it has early exit, much more performant in most cases) assemblies between versions.
> 
> ```rust
> pub fn all_zero(data: &[u64]) -> bool {
>     data.iter().all(|&x| x == 0)
> }
> ```

But constant-time functions can not early exit.
The "fold bool" variant should also be optimized when compiled with nighly. So I think it's regression.

**Comment by nikic** [comment] 2022-08-30 14:57
Upstream issue: https://github.com/llvm/llvm-project/issues/57448

**Comment by pnkfelix** [comment] 2022-09-01 14:48
Aside: I think our labels here are a bit too general; while the text for "regression-from-stable-to-nightly" label itself says "Performance or correctness regression from stable to nightly", I think it should probably be revised to be restricted to "correctness or *severe* performance regression ..."

@rustbot label: -regression-from-stable-to-nightly

**Comment by pnkfelix** [comment] 2022-09-01 14:51
I'm putting back the label for now; I want to get more consensus amongst the team about what the labels should be used for and what they denote (and how to get a narrower view when one wants to filter out cases like this)

@rustbot label: +regression-from-stable-to-nightly

**Comment by nikic** [comment] 2023-04-03 12:27
Fixed by the LLVM 16 upgrade.

**Closed** 2023-04-12 04:50 UTC
Labels: A-LLVM, I-slow, E-needs-test, P-medium, T-compiler, regression-from-stable-to-stable, C-bug
