### ISSUE TITLE
Compiler error compiling xrl while installing xi-term from AUR

### ISSUE THREAD

**Issue by ezequielventura** [rust-lang/rust#62130] opened 2019-06-25 21:50 UTC
Compiling xrl v0.0.7
error: internal compiler error: src/librustc/hir/def.rs:259: attempted .def_id() on invalid def: Err

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
stack backtrace:
   0: rust_metadata_std_2a4ec9a6b10f5d6fe32beb50c7bd9a38
   1: rust_metadata_std_2a4ec9a6b10f5d6fe32beb50c7bd9a38
   2: rust_metadata_std_2a4ec9a6b10f5d6fe32beb50c7bd9a38
   3: rust_metadata_std_2a4ec9a6b10f5d6fe32beb50c7bd9a38
   4: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
   5: std::panicking::rust_panic_with_hook
   6: rust_metadata_rustc_errors_618ea61e6d54d9c77234c8bef6b972fa
   7: rustc_errors::Handler::bug
   8: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
   9: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  10: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  11: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  12: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  13: rustc::util::bug::bug_fmt
  14: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  15: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  16: rust_metadata_rustc_cdb88de90aa3a082aa03e03c161d37d6
  17: rustc::middle::dead::check_crate
  18: <unknown>
  19: <unknown>
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler
  22: <unknown>
  23: __rust_maybe_catch_panic
  24: <unknown>
  25: rust_metadata_std_2a4ec9a6b10f5d6fe32beb50c7bd9a38
  26: start_thread
  27: __clone
query stack during panic:
end of query stack
error: aborting due to previous error

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.2 running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `xrl`.

**Comment by jonas-schievink** [comment] 2019-06-25 22:19
This looks like a duplicate of https://github.com/rust-lang/rust/issues/61732, but that one only seems to affect rustdoc?

**Comment by ezequielventura** [comment] 2019-06-26 04:16
> This looks like a duplicate of #61732, but that one only seems to affect rustdoc?

Sorry I can't tell if they are related. I'm not familiar with rust language, I was just trying to install some xi-editor front end (xi-term) and the compilation stopped there, I just posted the error because the message suggested it and I thought it might help the developers. Maybe this concerns the package maintainers.

**Comment by little-dude** [comment] 2019-06-27 05:38
Yeah this is the same bug.

**Comment by jonas-schievink** [comment] 2019-06-27 13:53
Okay, closing in favor of #61732 then. Thanks for the report @ezequielventura!

**Closed** 2019-06-28 12:47 UTC
