### ISSUE TITLE
core::ops::Range is Copyable but not Cloneable

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#21431] opened 2015-01-20 18:39 UTC
Range is an iterator, copyable when its index is copyable, but not cloneable even if its index is both copyable and cloneable. This interferes with traits like `itertools::Product`, which require cloneable iterators.

Specifically, this prevents one from doing something like:
```rust
iproduct!(0us..10, 0us..10).map(|x, y| x*y).all(|z| z >= 0)
```
which fails with the expected error:
```rust
<itertools macros>:2:12: 2:37 error: the trait `core::clone::Clone` is not implemented for the type `core::ops::Range<usize>`
<itertools macros>:2 { let it = $ crate :: Product :: new ( $ I , $ J ) ; it } ) ; (
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by csouth3** [comment] 2015-01-20 19:46
This is a dupe of #21384, and is fixed in #21386.
Thanks for reporting!

**Closed** 2015-01-21 07:14 UTC
