### ISSUE TITLE
building dylib on windows fails 

### ISSUE THREAD

**Issue by chuckries** [rust-lang/rust#24755] opened 2015-04-24 01:58 UTC
```
C:\Users\chuckr\Source\rust\src>rustc --version
rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)
```
lib.rs:
```
#![crate_type = "dylib"]

pub fn SayHello(a: u8) -> u8 {
    a + 1
}
```
'rustc lib.rs' fails with:
```
lib.rs:3:1: 5:2 warning: function `SayHello` should have a snake case name such
as `say_hello`, #[warn(non_snake_case)] on by default
lib.rs:3 pub fn SayHello(a: u8) -> u8 {
lib.rs:4     a + 1
lib.rs:5 }
error: linking with `gcc` failed: exit code: 1
note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nx
compat" "-static-libgcc" "-m64" "-L" "C:\Program Files\Rust beta 1.0\bin\rustlib
\x86_64-pc-windows-gnu\lib" "-o" "lib.dll" "lib.o" "lib.metadata.o" "C:\Program
Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libstd-4e7c5e5c.rlib"
"C:\Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libcollect
ions-4e7c5e5c.rlib" "C:\Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-window
s-gnu\lib\libunicode-4e7c5e5c.rlib" "C:\Program Files\Rust beta 1.0\bin\rustlib\
x86_64-pc-windows-gnu\lib\librand-4e7c5e5c.rlib" "C:\Program Files\Rust beta 1.0
\bin\rustlib\x86_64-pc-windows-gnu\lib\liballoc-4e7c5e5c.rlib" "C:\Program Files
\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\liblibc-4e7c5e5c.rlib" "C:\
Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libcore-4e7c5e
5c.rlib" "-L" "C:\Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\
lib" "-L" "C:\Users\chuckr\Source\rust\src\.rust\bin\x86_64-pc-windows-gnu" "-L"
 "C:\Users\chuckr\Source\rust\src\bin\x86_64-pc-windows-gnu" "-Wl,--whole-archiv
e" "-Wl,-Bstatic" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lws2_32" "-luserenv
" "-shared" "-lcompiler-rt"
note: C:\Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libco
re-4e7c5e5c.rlib(core-4e7c5e5c.o):(.text+0x7d95): undefined reference to `rust_b
egin_unwind'
C:\Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libcore-4e7
c5e5c.rlib(core-4e7c5e5c.o):(.xdata+0x20): undefined reference to `rust_eh_perso
nality'
ld: C:\Program Files\Rust beta 1.0\bin\rustlib\x86_64-pc-windows-gnu\lib\libcore
-4e7c5e5c.rlib(core-4e7c5e5c.o): bad reloc address 0x20 in section `.xdata'

error: aborting due to previous error
```

**Comment by alexcrichton** [comment] 2015-04-24 17:22
This is a dupe of https://github.com/rust-lang/rust/issues/18807, but thanks for the report!

**Closed by alexcrichton** 2015-04-24 17:22 UTC
