### ISSUE TITLE
Broken nightly toolchain for windows-gnu since 2018-03-17

### ISSUE THREAD

**Issue by rkarp** [rust-lang/rust#49438] opened 2018-03-28 07:24 UTC
This is the last working version:
```
$ rustup toolchain install nightly-2018-03-16-gnu
info: syncing channel updates for 'nightly-2018-03-16-x86_64-pc-windows-gnu'
info: latest update on 2018-03-16, rust version 1.26.0-nightly (392645394 2018-03-15)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rust-mingw'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: installing component 'rust-mingw'

  nightly-2018-03-16-x86_64-pc-windows-gnu installed - rustc 1.26.0-nightly (392645394 2018-03-15)
```

For nightly-2018-03-17 rustc doesn't work at all:
```
$ rustup toolchain install nightly-2018-03-17-gnu
info: syncing channel updates for 'nightly-2018-03-17-x86_64-pc-windows-gnu'
info: latest update on 2018-03-17, rust version 1.26.0-nightly (55c984ee5 2018-03-16)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rust-mingw'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: installing component 'rust-mingw'

  nightly-2018-03-17-x86_64-pc-windows-gnu installed - (error reading rustc version)
```

When trying to run rustc from that nightly, there's an error about not being able to find an entry point for `CreateMutexA` in `api-ms-core-synch-l1-2-0.dll`. This is on 2 different computers running Windows 7 Pro x64.

**Comment by leonardo-m** [comment] 2018-03-28 08:03
For me the last working Nightly version is:

```
rustc 1.26.0-nightly (9c9424de5 2018-03-27)
binary: rustc
commit-hash: 9c9424de51da41fd3d1077ac7810276f8dc746fa
commit-date: 2018-03-27
host: x86_64-pc-windows-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

**Comment by rkarp** [comment] 2018-03-28 08:30
The problem seems to be that `rustc-errors.dll` has gained a dependency on `api-ms-core-synch-l1-2-0.dll`. On nightly-2018-03-16 `CreateMutexA` is instead imported from `kernel32.dll`.

**Comment by retep998** [comment] 2018-03-28 15:02
Ah the joys of relying on import libraries from MinGW and hoping everything resolves where we want it...

This was likely caused by something depending on `synchronization.lib`/`libsynchronization.a` through `winapi` recently. Fixing it would require either reverting that dependency change or doing some complicated shenanigans involving `winapi`.

**Comment by Nostrocean** [comment] 2018-04-02 14:11
For my Windows 7 Pro x64, this error stopped at version `1.26.0-nightly (517f24025 2018-03-31)`

What commit fixed it?  I'm not able to locate it in Commits merged on Mar 31, 2018 at Master branch.

Versions:
```
rustup install nightly-2018-03-16-gnu
info: syncing channel updates for 'nightly-2018-03-16-x86_64-pc-windows-gnu'
info: latest update on 2018-03-16, rust version 1.26.0-nightly (392645394 2018-03-15)
[...]

** Ok **
```
```
rustup install nightly-2018-03-17-gnu
info: syncing channel updates for 'nightly-2018-03-17-x86_64-pc-windows-gnu'
info: latest update on 2018-03-17, rust version 1.26.0-nightly (55c984ee5 2018-03-16)
[...]

** Error **  rustc.exe : 
 The procedure entry point CreateMutexA could not be located 
 in the dynamic library api-ms-win-core-synch-l1-2-0.dll
```
    [...]
```
rustup install nightly-2018-03-31-gnu
info: syncing channel updates for 'nightly-2018-03-31-x86_64-pc-windows-gnu'
info: latest update on 2018-03-31, rust version 1.26.0-nightly (80785a547 2018-03-30)
[...]

** Error **  rustc.exe : 
 The procedure entry point CreateMutexA could not be located 
 in the dynamic library api-ms-win-core-synch-l1-2-0.dll
```
```
rustup install nightly-2018-04-01-gnu
info: syncing channel updates for 'nightly-2018-04-01-x86_64-pc-windows-gnu'
info: latest update on 2018-04-01, rust version 1.26.0-nightly (517f24025 2018-03-31)
[...]

** Ok **
```
```
rustup install nightly
info: syncing channel updates for 'nightly-x86_64-pc-windows-gnu'
info: latest update on 2018-04-02, rust version 1.26.0-nightly (06fa27d7c 2018-04-01)
[...]

** Ok **
```

**Comment by rkarp** [comment] 2018-04-08 13:29
It's not yet fixed for me on `version 1.27.0-nightly (056f589fb 2018-04-07)`.

**Comment by pnkfelix** [comment] 2018-04-12 14:57
Is one of the participants here interested in attempting to bisect down to a particular commit (rather than just a date) via  https://github.com/rust-lang-nursery/cargo-bisect-rustc ?

**Comment by retep998** [comment] 2018-04-12 18:11
After further investigation I have found that MinGW's `libsynchronization.a` is actually quite different from MSVC's `synchronization.lib`.

`synchronization.lib` has just these symbols:
```
WaitOnAddress
WakeByAddressAll
WakeByAddressSingle
```
`libsynchronization.a` meanwhile has all of these symbols:
```
AcquireSRWLockExclusive
AcquireSRWLockShared
CreateEventA
CreateEventExA
CreateEventExW
CreateEventW
CreateMutexA
CreateMutexExA
CreateMutexExW
CreateMutexW
CreateSemaphoreExW
DeleteCriticalSection
EnterCriticalSection
InitOnceBeginInitialize
InitOnceComplete
InitOnceExecuteOnce
InitOnceInitialize
InitializeConditionVariable
InitializeCriticalSection
InitializeCriticalSectionAndSpinCount
InitializeCriticalSectionEx
InitializeSRWLock
LeaveCriticalSection
OpenEventA
OpenEventW
OpenMutexW
OpenSemaphoreW
ReleaseMutex
ReleaseSRWLockExclusive
ReleaseSRWLockShared
ReleaseSemaphore
ResetEvent
SetCriticalSectionSpinCount
SetEvent
Sleep
SleepConditionVariableCS
SleepConditionVariableSRW
SleepEx
TryAcquireSRWLockExclusive
TryAcquireSRWLockShared
TryEnterCriticalSection
WaitForMultipleObjectsEx
WaitForSingleObject
WaitForSingleObjectEx
WaitOnAddress
WakeAllConditionVariable
WakeByAddressAll
WakeByAddressSingle
WakeConditionVariable
```
These exports lead to DLLs that only exist on newer versions of Windows, and are overriding the exports from `libkernel32.a`. Therefore this is *entirely* MinGW's fault for providing such shoddy import libraries that don't match their msvc equivalents. Also do note that this issue does not manifest when using `winapi` normally, only when building Rust because Rust does not use `winapi`'s bundled import libraries. So as far as I can see there are a few ways we can deal with this.

1. Get rid of or modify whatever dependency is enabling the `synchapi` feature of `winapi` which causes `libsynchronization.a` to be linked in.
2. Get this fixed upstream in MinGW.
3. Stop relying on MinGW import libraries so much. Either by building our own `libsynchronization.a` or by figuring out if we can somehow use `winapi`'s bundled import libraries.


As a workaround for users in the meantime, the `-msvc` toolchain still works fine on Windows 7 and you can cross to `-gnu` if you really need to work with MinGW.

**Comment by ThatBrickster** [comment] 2018-04-22 09:55
This issue now affects the beta channel after 1.26 beta 9 got the dodgy commit. MSVC works fine on Windows 7 x64.

**Comment by nikomatsakis** [comment] 2018-04-26 14:28
@retep007 which of those options do you think would be the best choice? Maybe we should file an issue with MinGW just to get their opinion? I guess my preference, in order, would be to (a) file an issue, then (b) remove the dependency if we can, else (c) use an alternate version of the library.

**Comment by nikomatsakis** [comment] 2018-04-26 14:28
cc @rust-lang/infra -- using an alternate version of the library seems more to fall in your domain =) at least, *I* don't really know what's involved

**Comment by alexcrichton** [comment] 2018-04-26 15:46
@rkarp and @leonardo-m, is this still happening for you on nightly? Looking at the dependencies on today's nightly it looks like the DLL dependency has disappeared so I'd just want to confirm that works so we can figure out what to backport.

**Comment by alexcrichton** [comment] 2018-04-26 15:50
I also can't see the dependency in beta.12 (today's beta release). Was this perhaps accidentally fixed? Could y'all who have been reproducing this confirm whether ornot it's been fixed?

**Comment by alexcrichton** [comment] 2018-04-26 15:52
The [difference between beta.9 and beta.12](https://github.com/rust-lang/rust/compare/7d025f4b8...1861fb587) doesn't really show much why this would be fixed one way or the other...

**Comment by retep998** [comment] 2018-04-26 16:40
https://github.com/retep998/winapi-rs/blob/0.3/build.rs#L388

The order in which winapi emits libraries is *random* so it occurs in *some* versions but not others, which means reproducing is like rolling a die.

**Comment by alexcrichton** [comment] 2018-04-26 18:31
I've excised the dependency which enables `synchapi` in https://github.com/rust-lang/rust/pull/50254 which should get rustc working again at least. It's not a complete solution unfortunately.

@Zoxc do you have thoughts on this? The `parking_lot` dependency is what's enabling the `synchapi` feature in `winapi` which is buggy here. Is it possible to not use `parking_lot`? Is it possible to have a different Windows implementation?

**Comment by alexcrichton** [comment] 2018-04-26 18:31
And to be clear https://github.com/rust-lang/rust/pull/50254 is intended to be a beta-only fix, a fix is still needed for master.

**Comment by Zoxc** [comment] 2018-04-26 22:06
We could just remove the dependency on `libsynchronization.a`, since that's only supposed to have Win 8+ symbols, which rustc can't use anyway.

**Comment by alexcrichton** [comment] 2018-04-26 22:51
@Zoxc would you be willing to look into removing `parking_lot`'s dependency on `synchapi` or otherwise fixing winapi on MinGW to not require `libsynchronization.a` in this case?

**Comment by alexcrichton** [comment] 2018-04-27 01:03
@retep998 we like to keep the builds of rustc as deterministic as possible. Ordering not only affects the final artifact but interediate rlibs. Would you accept a PR to make the ordering deterministic?

**Comment by alexcrichton** [comment] 2018-04-27 01:06
@retep998 this also seems like it's buggy on behalf of winapi? The [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298(v=vs.85).aspx) indicates that `Sleep`, despite being in the `Synchapi.h` header, resides in kernel32.dll. Activating the `synchapi` header doesn't seem like it should unconditionally activate linking to the synchronization library?

**Comment by retep998** [comment] 2018-04-27 01:37
@alexcrichton If you enable the `synchapi` module, then it will enable linking to any library necessary for all functions in that module. But as long as you don't actually *use* those functions then no references to those functions will be emitted and there will be no runtime dependence, which is why I chose to unconditionally enable linking to libraries and not offer finer grained control over which libraries actually get linked to. When used normally with the Windows SDK or the bundled import libraries this ends up working correctly with no issues.

In this specific case however, Rust is choosing to use import libraries from MinGW instead of using winapi's bundled import libraries **and** the `libsynchronization.a` import library from MinGW has imports that don't exist in `synchronization.lib` which may override the similar imports from `libkernel32.a`.

I will make the ordering deterministic though.

**Comment by alexcrichton** [comment] 2018-04-27 02:53
Switching the regression tag to nightly as this should be fixed on beta now.

@retep998 there's a whole mess of bugs here, and I'm looking for *any* route to fix it. Sounds like it's not the easiest to fix in winapi, so we won't rely on fixing it there then.

**Closed** 2018-04-27 23:32 UTC
Labels: C-bug, O-windows-gnu, P-high, T-infra, regression-from-stable-to-nightly
