### ISSUE TITLE
Slice patterns complain about move if type is not Copy

### ISSUE THREAD

**Issue by dgriffen** [rust-lang/rust#50639] opened 2018-05-10 23:58 UTC
**Compiler Version**: 1.26

Consider the following code:

```rust
struct Foo;

fn main() {
    let arr=[Foo,Foo];
    let [a,b]=arr;
}
```

Compiling will produce the following error:

```
error[E0382]: use of moved value: `arr[..]`
 --> src/main.rs:8:12
  |
8 |     let [a,b]=arr;
  |          - ^ value used here after move
  |          |
  |          value moved here
  |
  = note: move occurs because `arr[..]` has type `Foo`, which does not implement the `Copy` trait
```

The odd part is this works with tuple patterns:

```rust
struct Foo;

fn main() {
    let arr=(Foo,Foo);
    let (a,b)=arr;
}
```

**Comment by goodmanjonathan** [comment] 2018-05-11 00:04
duplicate of #26736

**Closed** 2018-05-11 08:27 UTC
