### ISSUE TITLE
compiler "did you mean" tips don't include macros: unresolved name `panic`. Did you mean `self`?

### ISSUE THREAD

**Issue by imbaczek** [rust-lang/rust#19788] opened 2014-12-12 23:21 UTC
e.g.

    error: unresolved name `panic`. Did you mean `self`?

it'd be helpful if the compiler could also check if there's a macro with that name and suggest that if so.

**Comment by nham** [comment] 2015-06-22 01:20
This seems to be a dupe of #5780

**Comment by alexcrichton** [comment] 2015-06-22 03:34
Indeed!

**Closed by alexcrichton** 2015-06-22 03:34 UTC
Labels: A-diagnostics, A-macros
