### ISSUE TITLE
Compiler regression on trust-dns-proto

### ISSUE THREAD

**Issue by joIivier** [rust-lang/rust#78598] opened 2020-10-31 13:20 UTC
The 30 Oct. nightly of the compiler cannot compile my project anymore because it crashes while compiling a dependency: `trust-dns-proto` versions 0.6.3 and 0.5.0. It seems to me that both versions of the library trigger the compiler crash based on the output of the compiler.

### Code
I am not sure the code of my project is relevant since it fails in a dependency whose versions are given in the error output.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (ffe52882e 2020-10-30)
binary: rustc
commit-hash: ffe52882ed79be67344dd6085559e308241e7f60
commit-date: 2020-10-30
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```
The same project compiles fine on a previous nightly given below:
```
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0

```

### Error output

```
Compiling trust-dns-proto v0.6.3
   Compiling trust-dns-proto v0.5.0
   Compiling postgres v0.18.1
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/_match.rs:931:18: trying to compare incompatible constructors Single and Str(Const { ty: &str, val: Value(Slice { data: Allocation { bytes: [105, 115, 115, 117, 101], relocations: Relocations(SortedMap { data: [] }), init_mask: InitMask { blocks: [31], len: Size { raw: 5 } }, size: Size { raw: 5 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, start: 0, end: 5 }) })

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:942:9
stack backtrace:
   0:     0x7fd0ba51e5f0 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x7fd0ba51e5f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2d26397c5720fdbb
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd0ba51e5f0 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fd0ba51e5f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d62bbfda6d5c836
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fd0ba58e52c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/core/src/fmt/mod.rs:1078:17
   5:     0x7fd0ba510252 - std::io::Write::write_fmt::h16a9fe7680ac245c
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/io/mod.rs:1518:15
   6:     0x7fd0ba5235a5 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fd0ba5235a5 - std::sys_common::backtrace::print::h5f20e41c85e91716
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fd0ba5235a5 - std::panicking::default_hook::{{closure}}::h5b7294ca19e8edab
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/panicking.rs:208:50
   9:     0x7fd0ba523248 - std::panicking::default_hook::hb3948d1f74b6ff4c
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/panicking.rs:227:9
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/_match.rs:931:18: trying to compare incompatible constructors Single and Str(Const { ty: &str, val: Value(Slice { data: Allocation { bytes: [105, 115, 115, 117, 101], relocations: Relocations(SortedMap { data: [] }), init_mask: InitMask { blocks: [31], len: Size { raw: 5 } }, size: Size { raw: 5 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, start: 0, end: 5 }) })

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:942:9
stack backtrace:
   0:     0x7fe3ca8165f0 - std::backtrace_rs::backtrace::libunwind::trace::h448c56741b6011d3
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x7fe3ca8165f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h2d26397c5720fdbb
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe3ca8165f0 - std::sys_common::backtrace::_print_fmt::h720a2f61f75b9f58
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fe3ca8165f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d62bbfda6d5c836
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fe3ca88652c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/core/src/fmt/mod.rs:1078:17
   5:     0x7fe3ca808252 - std::io::Write::write_fmt::h16a9fe7680ac245c
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/io/mod.rs:1518:15
   6:     0x7fe3ca81b5a5 - std::sys_common::backtrace::_print::h9ba51a6db618de7d
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fe3ca81b5a5 - std::sys_common::backtrace::print::h5f20e41c85e91716
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fe3ca81b5a5 - std::panicking::default_hook::{{closure}}::h5b7294ca19e8edab
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/panicking.rs:208:50
   9:     0x7fe3ca81b248 - std::panicking::default_hook::hb3948d1f74b6ff4c
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/panicking.rs:227:9
  10:     0x7fd0baded658 - rustc_driver::report_ice::h1ddbc5609a6e1f37
  11:     0x7fd0acdb534c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h65221e690226daf1
  12:     0x7fd0acdb7778 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h4b9fc50a86ab8540
  13:     0x7fd0ba523ea6 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/panicking.rs:597:17
  14:     0x7fd0bdde7d5d - std::panicking::begin_panic::{{closure}}::h4b123e1d8e3ae463
  15:     0x7fd0bdde7c96 - std::sys_common::backtrace::__rust_end_short_backtrace::ha21fec08f03d728b
  16:     0x7fd0bdde7d2f - std::panicking::begin_panic::hc0c81fab1e0acd00
  17:     0x7fd0bddf9c90 - rustc_errors::HandlerInner::bug::h26f9bc1a7147687e
  18:     0x7fd0bddf87e0 - rustc_errors::Handler::bug::h2149bffe74600666
  19:     0x7fd0bd8573c4 - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h9fafd217538ab02e
  20:     0x7fd0bd850eeb - rustc_middle::ty::context::tls::with_opt::{{closure}}::h6dc4ddb450eaa7bf
  21:     0x7fd0bd8508a2 - rustc_middle::ty::context::tls::with_opt::ha2cfd84f58be3d57
  22:     0x7fd0bd8572e9 - rustc_middle::util::bug::opt_span_bug_fmt::hc7cbb029c2646db9
  23:     0x7fd0bd85725e - rustc_middle::util::bug::bug_fmt::hb51c412c48cda8bb
  24:     0x7fd0bc01a8b5 - rustc_mir_build::thir::pattern::_match::Matrix::specialize_constructor::h36673621382da348
  25:     0x7fd0bbfe351a - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::hc5d1fe05ffff39c8
  26:     0x7fd0bc020568 - rustc_mir_build::thir::pattern::_match::is_useful::hf8efd6153416cf2d
  27:     0x7fd0bbfb4e68 - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h865c9f6d42685550
  28:     0x7fd0bbfbdd0a - rustc_hir::intravisit::walk_expr::hd0093ab50ae5a8d4
  29:     0x7fd0bbfb4aec - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h865c9f6d42685550
  30:     0x7fd0bbfb4813 - rustc_mir_build::thir::pattern::check_match::check_match::h2d5b60d42651dc41
  31:     0x7fd0bb03fcd9 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_match>::compute::h3dd4584521cdb95e
  32:     0x7fd0bafa6b94 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::ha5792d8d35599b62
  33:     0x7fd0bb00aff4 - rustc_data_structures::stack::ensure_sufficient_stack::h3626f02a47d49f69
  34:     0x7fd0baf9b45f - rustc_query_system::query::plumbing::get_query_impl::hfaed35f7e6414273
  35:     0x7fd0baf9cb42 - rustc_query_system::query::plumbing::ensure_query_impl::ha7327a13b80a3079
  36:     0x7fd0bb03bd89 - rustc_interface::passes::analysis::h78326215bfd650a0
  37:     0x7fd0bae2bc2b - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute::hf8d4bc54d08537f3
  38:     0x7fd0badf0c37 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h982af355bf58c5b3
  39:     0x7fd0bae0c660 - rustc_data_structures::stack::ensure_sufficient_stack::he424948b1b3ac791
  40:     0x7fd0bad9d6a0 - rustc_query_system::query::plumbing::get_query_impl::h448d10ab90370983
  41:     0x7fd0bae2ecef - rustc_interface::passes::QueryContext::enter::hbf7a36e966e91449
  42:     0x7fd0bae0a116 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h36c5ed3de81f7a3c
  43:     0x7fd0bad96bc7 - rustc_span::with_source_map::h4e49cbd9a39d01b4
  44:     0x7fd0bae05321 - scoped_tls::ScopedKey<T>::set::hca96dcfe1d32eebf
  45:     0x7fd0bae0cfd5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21cfd4855c5058aa
  46:     0x7fd0bad77518 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2df6ccf8e166462a
  47:     0x7fd0ba532eaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/alloc/src/boxed.rs:1307:9
  48:     0x7fd0ba532eaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/alloc/src/boxed.rs:1307:9
  49:     0x7fd0ba532eaa - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys/unix/thread.rs:89:17
  50:     0x7fd0ba275dd5 - start_thread
  51:     0x7fd0b9b92ead - __clone
  52:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (ffe52882e 2020-10-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `<rr::rdata::caa::Property as std::convert::From<std::string::String>>::from`
#1 [analysis] running analysis passes on this crate
end of query stack
  10:     0x7fe3cb0e5658 - rustc_driver::report_ice::h1ddbc5609a6e1f37
  11:     0x7fe3bd1b534c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h65221e690226daf1
  12:     0x7fe3bd1b7778 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h4b9fc50a86ab8540
  13:     0x7fe3ca81bea6 - std::panicking::rust_panic_with_hook::h55d23fef0ad751bc
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/panicking.rs:597:17
  14:     0x7fe3ce0dfd5d - std::panicking::begin_panic::{{closure}}::h4b123e1d8e3ae463
  15:     0x7fe3ce0dfc96 - std::sys_common::backtrace::__rust_end_short_backtrace::ha21fec08f03d728b
  16:     0x7fe3ce0dfd2f - std::panicking::begin_panic::hc0c81fab1e0acd00
  17:     0x7fe3ce0f1c90 - rustc_errors::HandlerInner::bug::h26f9bc1a7147687e
  18:     0x7fe3ce0f07e0 - rustc_errors::Handler::bug::h2149bffe74600666
  19:     0x7fe3cdb4f3c4 - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h9fafd217538ab02e
  20:     0x7fe3cdb48eeb - rustc_middle::ty::context::tls::with_opt::{{closure}}::h6dc4ddb450eaa7bf
  21:     0x7fe3cdb488a2 - rustc_middle::ty::context::tls::with_opt::ha2cfd84f58be3d57
  22:     0x7fe3cdb4f2e9 - rustc_middle::util::bug::opt_span_bug_fmt::hc7cbb029c2646db9
  23:     0x7fe3cdb4f25e - rustc_middle::util::bug::bug_fmt::hb51c412c48cda8bb
  24:     0x7fe3cc3128b5 - rustc_mir_build::thir::pattern::_match::Matrix::specialize_constructor::h36673621382da348
  25:     0x7fe3cc2db51a - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::hc5d1fe05ffff39c8
  26:     0x7fe3cc318568 - rustc_mir_build::thir::pattern::_match::is_useful::hf8efd6153416cf2d
  27:     0x7fe3cc2ace68 - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h865c9f6d42685550
  28:     0x7fe3cc2b5d0a - rustc_hir::intravisit::walk_expr::hd0093ab50ae5a8d4
  29:     0x7fe3cc2acaec - <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr::h865c9f6d42685550
  30:     0x7fe3cc2ac813 - rustc_mir_build::thir::pattern::check_match::check_match::h2d5b60d42651dc41
  31:     0x7fe3cb337cd9 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::check_match>::compute::h3dd4584521cdb95e
  32:     0x7fe3cb29eb94 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::ha5792d8d35599b62
  33:     0x7fe3cb302ff4 - rustc_data_structures::stack::ensure_sufficient_stack::h3626f02a47d49f69
  34:     0x7fe3cb29345f - rustc_query_system::query::plumbing::get_query_impl::hfaed35f7e6414273
  35:     0x7fe3cb294b42 - rustc_query_system::query::plumbing::ensure_query_impl::ha7327a13b80a3079
  36:     0x7fe3cb333d89 - rustc_interface::passes::analysis::h78326215bfd650a0
  37:     0x7fe3cb123c2b - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute::hf8d4bc54d08537f3
  38:     0x7fe3cb0e8c37 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h982af355bf58c5b3
  39:     0x7fe3cb104660 - rustc_data_structures::stack::ensure_sufficient_stack::he424948b1b3ac791
  40:     0x7fe3cb0956a0 - rustc_query_system::query::plumbing::get_query_impl::h448d10ab90370983
  41:     0x7fe3cb126cef - rustc_interface::passes::QueryContext::enter::hbf7a36e966e91449
  42:     0x7fe3cb102116 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h36c5ed3de81f7a3c
  43:     0x7fe3cb08ebc7 - rustc_span::with_source_map::h4e49cbd9a39d01b4
  44:     0x7fe3cb0fd321 - scoped_tls::ScopedKey<T>::set::hca96dcfe1d32eebf
  45:     0x7fe3cb104fd5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21cfd4855c5058aa
  46:     0x7fe3cb06f518 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2df6ccf8e166462a
  47:     0x7fe3ca82aeaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9e7afb7a0a438236
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/alloc/src/boxed.rs:1307:9
  48:     0x7fe3ca82aeaa - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70c646c4271337a1
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/alloc/src/boxed.rs:1307:9
  49:     0x7fe3ca82aeaa - std::sys::unix::thread::Thread::new::thread_start::h35d2b8d36f210d02
                               at /rustc/ffe52882ed79be67344dd6085559e308241e7f60/library/std/src/sys/unix/thread.rs:89:17
  50:     0x7fe3ca56ddd5 - start_thread
  51:     0x7fe3c9e8aead - __clone
  52:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (ffe52882e 2020-10-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `<rr::rdata::caa::Property as std::convert::From<std::string::String>>::from`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `trust-dns-proto`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

error: build failed

```

**Comment by jonas-schievink** [comment] 2020-10-31 13:24
Duplicate of https://github.com/rust-lang/rust/issues/78549

**Closed by jonas-schievink** 2020-10-31 13:24 UTC
Labels: C-bug, I-ICE, T-compiler
