### ISSUE TITLE
Bad interaction of smart pointers, auto-deref and closures

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#27106] opened 2015-07-18 13:08 UTC
The following code does not compile:

``` Rust
use std::rc::Rc;
use std::cell::RefCell;

pub struct Callbacks {
    callbacks: Vec<Rc<RefCell<FnMut(i32)>>>,
}

impl Callbacks {
    pub fn call(&mut self, val: i32) {
        for callback in self.callbacks.iter() {
            let mut closure = callback.borrow_mut();
            closure(val);
        }
    }
}
```

([Playpen](http://is.gd/oQk3Fm))

It says: "cannot borrow immutable borrowed content as mutable".

Instead, I have to explicitly dereference and borrow the closure in the loop, with `(&mut *closure)(val)`. Typically, Rust performs this automatically, so I expected that to also happen in this case. At the very least, the error message should be improved, as currently, it doesn't help with the actual issue at all.

**Comment by eefriedman** [comment] 2015-07-18 21:15
See https://github.com/rust-lang/rust/compare/master...eefriedman:fnmut-autoderef .

**Comment by Diggsey** [comment] 2016-09-10 23:02
This looks like a duplicate of #26186

**Comment by Mark-Simulacrum** [comment] 2017-05-13 18:25
Closing in favor of #26186.

**Closed by Mark-Simulacrum** 2017-05-13 18:25 UTC
Labels: A-typesystem
