### ISSUE TITLE
Rust derive(Clone) does not seem to work for more complicated examples

### ISSUE THREAD

**Issue by uzytkownik** [rust-lang/rust#48974] opened 2018-03-13 04:01 UTC
The code below is what I would expect the `Clone` to look like based on [`Clone` for `Addr`](https://actix.github.io/actix/actix/struct.Addr.html#impl-Clone). However while Rust doesn't emit doesn't emit any errors during compilation it does create some other implementation which is more restrictive and didn't worked in my code.

```rust
//#[derive(Clone)]
struct ActorData<T: Actor> {
	addr: Addr<Syn, T>
}

impl<T: Actor> Clone for ActorData<T> {
	fn clone(&self) -> ActorData<T> {
		ActorData {
			addr: self.addr.clone()
		}
	}
	fn clone_from(&mut self, source: &Self) {
		self.addr.clone_from(&source.addr)
	}
}
```

**Comment by oli-obk** [comment] 2018-03-13 07:38
Duplicate of https://github.com/rust-lang/rust/issues/26925

TLDR: You can't do this with derive because the derive impl adds a `Clone` bound to `T`

**Closed by oli-obk** 2018-03-13 07:38 UTC

**Comment by Ixrec** [comment] 2018-03-15 21:05
For completeness: https://github.com/rust-lang/rfcs/pull/2353 is an RFC that would help with cases like this.
