### ISSUE TITLE
Regression in wait-timeout-0.1.13 test suite in Rust 1.15

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38721] opened 2016-12-30 22:04 UTC
https://github.com/alexcrichton/wait-timeout at 23b9d5878a68f90bd4785ae767eb0f8341741360

```
brian@ip-10-145-43-250:~/dev/wait-timeout⟫ rustc +beta -Vv
rustc 1.15.0-beta.1 (d9a0f0df7 2016-12-19)
binary: rustc
commit-hash: d9a0f0df7051c603011d6b60fbdd155318fc47f3
commit-date: 2016-12-19
host: x86_64-unknown-linux-gnu
release: 1.15.0-beta.1
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/wait-timeout⟫ cargo +beta test
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/exit-f69dd916dbe62d32

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/deps/sleep-215b0cd4734ffe1e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/deps/smoke-d4c60bfffdf0becf

running 4 tests
test exit_codes ... FAILED
test smoke_insta_timeout ... FAILED
test smoke_success ... FAILED
test smoke_timeout ... FAILED

failures:

---- exit_codes stdout ----
        thread 'exit_codes' panicked at 'Command::new(me).arg(code.to_string()).spawn() failed with No such file or directory (os error 2)', tests/smoke.rs:27
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- smoke_insta_timeout stdout ----
        thread 'smoke_insta_timeout' panicked at 'Command::new(me).arg(ms.to_string()).spawn() failed with No such file or directory (os error 2)', tests/smoke.rs:20

---- smoke_success stdout ----
        thread 'smoke_success' panicked at 'Command::new(me).arg(ms.to_string()).spawn() failed with No such file or directory (os error 2)', tests/smoke.rs:20

---- smoke_timeout stdout ----
        thread 'smoke_timeout' panicked at 'Command::new(me).arg(ms.to_string()).spawn() failed with No such file or directory (os error 2)', tests/smoke.rs:20


failures:
    exit_codes
    smoke_insta_timeout
    smoke_success
    smoke_timeout

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured

error: test failed

```

This seems likely to be https://github.com/rust-lang/cargo/issues/3368

cc @alexcrichton

**Comment by alexcrichton** [comment] 2016-12-30 23:43
Ah yes this was fixed on master but just hasn't been published to crates.io, known breakage though!

**Comment by alexcrichton** [comment] 2016-12-30 23:44
Oh this was also caused by https://github.com/rust-lang/cargo/pull/3102 I believe, not `OUT_DIR` business.

**Closed by alexcrichton** 2016-12-30 23:43 UTC
Labels: regression-from-stable-to-beta
