### ISSUE TITLE
Trying to access std::sys_common::io::DEFAULT_BUF_SIZE; 

### ISSUE THREAD

**Issue by IgnoreAmos** [rust-lang/rust#39931] opened 2017-02-18 16:35 UTC
I was experimenting with BufReader code to make it work with bit streams and
wanted to use the same default buffer size:

const DEFAULT_BUF_SIZE: usize = std::sys_common::io::DEFAULT_BUF_SIZE;

## Meta

`rustc --version --verbose`:

rustc --version --verbose
rustc 1.15.1 (021bd294c 2017-02-08)
binary: rustc
commit-hash: 021bd294c039bd54aa5c4aa85bcdffb0d24bc892
commit-date: 2017-02-08
host: x86_64-pc-windows-gnu
release: 1.15.1
LLVM version: 3.9

Backtrace:

cargo build --verbose
   Compiling BitStream v0.1.0 (file:///E:/Ex%20nihilo/rust/BitStream)
     Running `rustc --crate-name BitStream src\lib.rs --crate-type lib -g -C metadata=68c310b10395856d -C extra-filename=-68c310b10395856d --out-dir "E:\Ex nihilo\rust\BitStream\target\debug\deps" --emit=dep-info,link -L "dependency=E:\Ex nihilo\rust\BitStream\target\debug\deps"`
error: module `sys_common` is private
  --> src\lib.rs:21:33
   |
21 | const DEFAULT_BUF_SIZE: usize = std::sys_common::io::DEFAULT_BUF_SIZE;
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: C:\bot\slave\stable-dist-rustc-win-gnu-64\build\src\librustc\middle\stability.rs:551: encountered unmarked API
  --> src\lib.rs:21:33
   |
21 | const DEFAULT_BUF_SIZE: usize = std::sys_common::io::DEFAULT_BUF_SIZE;
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', C:\bot\slave\stable-dist-rustc-win-gnu-64\build\src\librustc_errors\lib.rs:382
stack backtrace:
   0:         0x70a2f98e - <unknown>
   1:         0x70a2f154 - <unknown>
   2:         0x70a30b4a - <unknown>
   3:         0x6ea18fdb - <unknown>
   4:         0x6ebd55b7 - <unknown>
   5:         0x6ebd5355 - <unknown>
   6:         0x6ebd4bf4 - <unknown>
   7:         0x6ebb1761 - <unknown>
   8:         0x6ebb2329 - <unknown>
   9:         0x6eab515d - <unknown>
  10:         0x6ebb00b0 - <unknown>
  11:         0x6dcec747 - <unknown>
  12:         0x6dccf8a9 - <unknown>
  13:         0x6dcb852c - <unknown>
  14:         0x6dd05b06 - <unknown>
  15:         0x6dc0ad65 - <unknown>
  16:         0x70a338c8 - <unknown>
  17:         0x6dc27902 - <unknown>
  18:         0x70a2d432 - <unknown>
  19:     0x7ffd57228363 - <unknown>

error: Could not compile `BitStream`.

Caused by:
  process didn't exit successfully: `rustc --crate-name BitStream src\lib.rs --crate-type lib -g -C metadata=68c310b10395856d -C extra-filename=-68c310b10395856d --out-dir E:\Ex nihilo\rust\BitStream\target\debug\deps --emit=dep-info,link -L dependency=E:\Ex nihilo\rust\BitStream\target\debug\deps` (exit code: 101)

**Comment by sfackler** [comment] 2017-02-18 18:59
That constant is private - you won't be able to access it. The ICE should definitely be fixed, though.

**Comment by petrochenkov** [comment] 2017-02-18 19:05
Duplicate of https://github.com/rust-lang/rust/issues/38857

**Closed** 2017-02-18 19:06 UTC
Labels: I-ICE
