### ISSUE TITLE
num(f64) >u64::MAX cast to u64 has no panic

### ISSUE THREAD

**Issue by H-ZeX** [rust-lang/rust#64501] opened 2019-09-16 08:29 UTC
```rust
fn main() {
    let a = std::u64::MAX;
    let b = a as f64;
    let c = b as u64;
    let d = std::u64::MAX as f64 as u64;
    println!("{}, {}, {}, {}", a, b, c, d);
}
```
This program has no panic.

`u64::MAX` can not be repesented by 64bit num(IEE756) precisely, so `u64::MAX` as `f64` will get a num bigger than `u64::MAX`, that can not be represent by 64bit integer. So I think `u64::MAX as f64 as u64` should panic, because there is overflow. **And  this is undefined behavior**.

**I think for any `undefined behavior`, should panic, and let the user avoid to use such behavior**

**Comment by jonas-schievink** [comment] 2019-09-16 08:32
Duplicate of https://github.com/rust-lang/rust/issues/10184

**Closed by jonas-schievink** 2019-09-16 08:32 UTC
