### ISSUE TITLE
rustc panic compiling playform

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rust#43476] opened 2017-07-25 19:37 UTC
Hi,

while trying to build 21a57d51822d55974e04e6d50de4cd87b84bbc8e of https://github.com/bfops/playform with rustc 1.20.0-nightly (598eddf4f 2017-07-24) running on x86_64-unknown-linux-gnu I got:

    error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<CB as audio::AudioCallback>)),depth=0),Unimplemented)]` resolving bounds after type-checking

    note: the compiler unexpectedly panicked. this is a bug.

    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

    note: rustc 1.20.0-nightly (598eddf4f 2017-07-24) running on x86_64-unknown-linux-gnu

    thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8

while (I believe) compiling the sdl2 crate

All I did was:

    rustup self update
    rustup update
    git clone https://github.com/bfops/playform 
    cd playform
    rustup override set nightly
    cargo build --release

I have repeated this (from the clone) fresh twice, with the same result.

The full backtrace (`RUST_BACKTRACE=full cargo build --release`) is:

```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
stack backtrace:
   0:     0x7f6abd31f103 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1522c360a91efc38
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f6abd3197e4 - std::sys_common::backtrace::_print::ha3773971e7a0524b
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x7f6abd32cf83 - std::panicking::default_hook::{{closure}}::h27687d2e78ba1eb8
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:     0x7f6abd32cc78 - std::panicking::default_hook::ha02ba6f8e599dd44
                               at /checkout/src/libstd/panicking.rs:390
   4:     0x7f6abd32d487 - std::panicking::rust_panic_with_hook::h65fcd07ab00e8ccd
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x7f6aba00eef8 - std::panicking::begin_panic_new::h428b9015ade5740a
   6:     0x7f6ab9ff9301 - rustc_errors::Handler::span_bug::h2ff6f8e9cde67448
   7:     0x7f6aba236503 - rustc::session::opt_span_bug_fmt::{{closure}}::h4d4bb47ae7882b62
   8:     0x7f6aba2363e2 - rustc::session::opt_span_bug_fmt::h7caecea6e54a114b
   9:     0x7f6aba236123 - rustc::session::span_bug_fmt::h6c24fb7ac6672125
  10:     0x7f6aba2ee8ff - <&'gcx rustc::ty::TyS<'gcx> as rustc::infer::TransNormalize<'gcx>>::trans_normalize::h90cedc9d683de268
  11:     0x7f6aba1b023d - rustc::infer::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'tcx>>::normalize_associated_type_in_env::hbe88b9560bc259f6
  12:     0x7f6aba290881 - rustc::ty::layout::Layout::compute_uncached::h98c58344d728a22e
  13:     0x7f6aba2b49ba - rustc::ty::util::layout_raw::ha13af363ecc544cf
  14:     0x7f6aba35bcc9 - rustc::ty::maps::<impl rustc::ty::maps::queries::layout_raw<'tcx>>::try_get::h4d332afb6a147f97
  15:     0x7f6aba368aaf - rustc::ty::maps::TyCtxtAt::layout_raw::h828409183f93ee39
  16:     0x7f6aba363bbd - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::layout_raw::h7321e000b90b3117
  17:     0x7f6ababd17a4 - rustc_const_eval::eval::eval_const_expr_partial::{{closure}}::h3767bda412cdb317
  18:     0x7f6ababcb953 - rustc_const_eval::eval::eval_const_expr_partial::haf6cc46997e4e31e
  19:     0x7f6ababcb61b - rustc_const_eval::eval::eval_const_expr_partial::haf6cc46997e4e31e
  20:     0x7f6ababcb61b - rustc_const_eval::eval::eval_const_expr_partial::haf6cc46997e4e31e
  21:     0x7f6ababcef92 - rustc_const_eval::eval::eval_const_expr_partial::haf6cc46997e4e31e
  22:     0x7f6ababcacc0 - rustc_const_eval::eval::ConstContext::eval::hc2838350358bc14a
  23:     0x7f6abca8b760 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hc2bacfd5dde4e824
  24:     0x7f6abca8b5f5 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hc2bacfd5dde4e824
  25:     0x7f6abca8b1ee - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hc2bacfd5dde4e824
  26:     0x7f6abca8b3e7 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hc2bacfd5dde4e824
  27:     0x7f6abca8b5f5 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::hc2bacfd5dde4e824
  28:     0x7f6abca8a0d9 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h28a205947f76c65a
  29:     0x7f6abca8bdfc - rustc_passes::consts::check_crate::h6277687598e5f5ca
  30:     0x7f6abd6c9d05 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h2224069a1fe59067
  31:     0x7f6abd6be943 - rustc_driver::driver::phase_3_run_analysis_passes::h9c665f67f983692e
  32:     0x7f6abd6a8c50 - rustc_driver::driver::compile_input::h206bff36594a4d7e
  33:     0x7f6abd6ee045 - rustc_driver::run_compiler::h82d6005c4c2b0326
  34:     0x7f6abd607447 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94745f618237f479
  35:     0x7f6abd35c9cc - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  36:     0x7f6abd63efe0 - <F as alloc::boxed::FnBox<A>>::call_box::h741725e0b9490eb6
  37:     0x7f6abd32be7b - std::sys::imp::thread::Thread::new::thread_start::h50322047a200d5bc
                               at /checkout/src/liballoc/boxed.rs:661
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  38:     0x7f6ab84e1063 - start_thread
  39:     0x7f6abcfd262c - clone
  40:                0x0 - <unknown>
```

**Comment by est31** [comment] 2017-07-25 22:57
#43357

**Comment by eddyb** [comment] 2017-07-27 13:40
Closing as duplicate of #43357.

**Closed by eddyb** 2017-07-27 13:40 UTC
Labels: I-ICE
