### ISSUE TITLE
Possibly bogus private type warning with trait impls

### ISSUE THREAD

**Issue by arcnmx** [rust-lang/rust#32318] opened 2016-03-17 17:59 UTC
The following example triggers a E0446 complaining about a "private type in public interface" even though it's only used in a trait impl, and not actually exposed to the public.

``` rust
pub trait T {
    fn f() -> u8;
}

type Alias = u8;
impl T for () {
    fn f() -> Alias { 0 }
}
```

```
<anon>:9:15: 9:20 warning: private type in public interface, #[warn(private_in_public)] on by default
<anon>:9     fn f() -> Alias { 0 }
                       ^~~~~
<anon>:9:15: 9:20 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
<anon>:9:15: 9:20 note: for more information, see the explanation for E0446 (`--explain E0446`)
```

For some context, a more realistic usage pattern where I've seen this come up a few times is with associated types. This was valid before the change, though whether it was intentional or not I'm not sure... It seems reasonable to allow it to me:

``` rust
pub trait T {
    type Error;

    fn f() -> Result<u8, Self::Error>;
}

pub struct MyError;
type MyResult<T> = Result<T, MyError>;
impl T for () {
    type Error = MyError;

    fn f() -> MyResult<u8> { Ok(0) }
}
```

**Comment by petrochenkov** [comment] 2016-03-17 18:09
Duplicate of https://github.com/rust-lang/rust/issues/30503
(The fix is trivial, it only needs a decision from the lang team.)

**Comment by arcnmx** [comment] 2016-03-17 18:20
While I'd consider them to be slightly different issues (private type aliases in public signatures vs type aliases used internally/hidden in trait impls) where one could be allowed while the other not... If #30503 is decided on positively it certainly would fix this!

My inclination is that as far as trait impls are concerned, this sort of checking should at best only apply to associated types and `impl<>` trait bounds. If we just go through with allowing them wholesale that works too, though!

**Comment by petrochenkov** [comment] 2016-03-17 19:07
> type aliases used internally/hidden in trait impl

`impl T for ()` is not internal/hidden, it's an impl of a public trait `T` for a public type `()`, therefore signatures of its items are checked for the presence of private items.

**Comment by arcnmx** [comment] 2016-03-17 19:23
> impl T for () is not internal/hidden, it's an impl of a public trait T for a public type (), therefore signatures of its items are checked for the presence of private items.

The impl itself is not hidden, but the inner *implementation* of it is. The public/exposed part is that the impl exists, any of its associated type bindings, and that it may have generic trait bounds. I guess the conceptual difference for me is that the type signature of an impl'd method can never really change; it's just not possible, even if you use a type alias in place of another type.

Guess I'm splitting hairs though, either way I certainly would like to see the ability to use `type` as a true transparent alias in private situations. Are type macros stable yet? Maybe that's a better solution to distinguish between `type` and an unnamed alias...

**Comment by Mark-Simulacrum** [comment] 2017-05-02 01:54
The original code now compiles without any warnings, so I'm going to close this.

**Closed by Mark-Simulacrum** 2017-05-02 01:54 UTC
