### ISSUE TITLE
Built-in #[derive(...)]s fail when generics don't implement trait, even when the generic isn't directly used

### ISSUE THREAD

**Issue by Osspial** [rust-lang/rust#49920] opened 2018-04-12 23:14 UTC
Rust's built-in derives add a `where T: $trait` bound any time a generic type is included in the `struct`'s definition, even if the generic type isn't directly used and all of the struct's fields implement the trait.

This shouldn't happen. Instead, the derives should implement the traits when all of the struct's fields implement the trait, regardless of whether the generic parameter implements the trait or not. As an example, the following code should compile, but doesn't.

https://play.rust-lang.org/?gist=9f13519f1d4a1a4414d60c03eecc203b&version=stable
```rust
use std::marker::PhantomData;

#[derive(Debug, Clone)]
struct Foo<T: Trait> {
    a: T::Assoc
}

#[derive(Debug, Clone)]
struct Baz<T: Trait> {
    a: PhantomData<T>
}

trait Trait {
    type Assoc;
}

struct Bar;
impl Trait for Bar {
    type Assoc = i32;
}

fn main() {
    let f: Foo<Bar> = Foo {
        a: 0
    };
    
    println!("{:?}", f);
    let _y = f.clone();
    
    
    let b: Baz<Bar> = Baz {
        a: PhantomData
    };
    
    println!("{:?}", b);
    let _z = b.clone();
}
```

```
error[E0277]: `Bar` doesn't implement `std::fmt::Debug`
  --> src/main.rs:27:22
   |
27 |     println!("{:?}", f);
   |                      ^ `Bar` cannot be formatted using `:?`; add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `Bar`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `Foo<Bar>`
   = note: required by `std::fmt::Debug::fmt`

error[E0599]: no method named `clone` found for type `Foo<Bar>` in the current scope
  --> src/main.rs:28:16
   |
4  | struct Foo<T: Trait> {
   | -------------------- method `clone` not found for this
...
28 |     let _y = f.clone();
   |                ^^^^^
   |
   = note: the method `clone` exists but the following trait bounds were not satisfied:
           `Foo<Bar> : std::clone::Clone`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `clone`, perhaps you need to implement it:
           candidate #1: `std::clone::Clone`

error[E0277]: `Bar` doesn't implement `std::fmt::Debug`
  --> src/main.rs:35:22
   |
35 |     println!("{:?}", b);
   |                      ^ `Bar` cannot be formatted using `:?`; add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `Bar`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `Baz<Bar>`
   = note: required by `std::fmt::Debug::fmt`

error[E0599]: no method named `clone` found for type `Baz<Bar>` in the current scope
  --> src/main.rs:36:16
   |
9  | struct Baz<T: Trait> {
   | -------------------- method `clone` not found for this
...
36 |     let _z = b.clone();
   |                ^^^^^
   |
   = note: the method `clone` exists but the following trait bounds were not satisfied:
           `Baz<Bar> : std::clone::Clone`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `clone`, perhaps you need to implement it:
           candidate #1: `std::clone::Clone`

error: aborting due to 4 previous errors
```

**Comment by ollie27** [comment] 2018-04-12 23:26
Duplicate of #26925

**Closed** 2018-04-12 23:42 UTC
