### ISSUE TITLE
rustdoc ICE when documenting openssl 0.9.24

### ISSUE THREAD

**Issue by zrneely** [rust-lang/rust#48604] opened 2018-02-28 07:38 UTC
Somewhere in the dependency chain of my project, something depends on openssl 0.9.24. Running `RUST_BACKTRACE=full cargo doc` gives a lot of text, so I've attached [error.log](https://github.com/rust-lang/rust/files/1766073/error.log).

`rustc --version --verbose`:
```
rustc 1.26.0-nightly (29f5c699b 2018-02-27)
binary: rustc
commit-hash: 29f5c699b11a6a148f097f82eaa05202f8799bbc
commit-date: 2018-02-27
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

I'm running the compiler in the Windows Subsystem for Linux (or whatever it's officially called), if that's relevant.

Apologies if this is a duplicate, I searched for "openssl" and "rustdoc" and didn't see any open bugs.

**Comment by retep998** [comment] 2018-02-28 07:51
Duplicate of https://github.com/rust-lang/rust/issues/48498

**Closed by retep998** 2018-02-28 07:51 UTC
