### ISSUE TITLE
Lifetime declaration missing in cross-crate method definitions

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20719] opened 2015-01-07 22:12 UTC
http://doc.rust-lang.org/nightly/std/ops/trait.Index.html#method.index

```rust
    fn index(&'a self, index: &Index) -> &'a <Self as Index<Index>>::Output;
```

vs.

http://doc.rust-lang.org/nightly/core/ops/trait.Index.html#method.index

```rust
    fn index<'a>(&'a self, index: &Index) -> &'a Output;
```

---

http://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html#method.keys

```rust
    fn keys(&'a self) -> Keys<'a, K, V>
````

vs.

http://doc.rust-lang.org/nightly/collections/struct.BTreeMap.html#method.keys

```rust
    fn keys<'a>(&'a self) -> Keys<'a, K, V>
````

**Comment by tomjakubowski** [comment] 2015-01-18 13:20
It doesn't look like the `ty::Generics` gets includes any region parameters unless a type parameter is bound by them (like `<'a, T: 'a>`). Might be an encoder bug?

**Comment by alexcrichton** [comment] 2015-04-07 04:20
Closing as a dupe of #14462

**Closed by alexcrichton** 2015-04-07 04:20 UTC
Labels: A-rustdoc
