### ISSUE TITLE
Type inference for the `!` type behaves unexpectedly

### ISSUE THREAD

**Issue by IQBigBang** [rust-lang/rust#87245] opened 2021-07-18 07:20 UTC
In summary, for the following code:

```rust
fn ok() {
    let x: *const ! = std::ptr::null();
    let m = unsafe { &*x };
    println!("{}", m);
}

fn wrong() {
    let x: *const (!, u8) = std::ptr::null();
    let m = unsafe { (&*x).0 };
    println!("{}", m);
}
```

The first function compiles (and then obviously fails at runtime), but the second one doesn't compile and produces the following message:

```
error[E0277]: `()` doesn't implement `std::fmt::Display`
  --> src/main.rs:12:20
```

Which is wrong, because the type of `m` should be `!`.

Adding any sort of type constraints, such as the following, makes the code pass the type-checker:
```rust
fn foo() {
    let x: *const (!, u8) = std::ptr::null();
    let m: ! = unsafe { (&*x).0 };
    println!("{}", m);
}

// Or

fn bar() {
    let x: *const (!, u8) = std::ptr::null();
    let m = unsafe { (&*x).0 };
    f(m);
    println!("{}", m);
}

fn f(_: !) {}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.55.0-nightly (c7331d65b 2021-07-17)
binary: rustc
commit-hash: c7331d65bdbab1187f5a9b8f5b918248678ebdb9
commit-date: 2021-07-17
host: x86_64-pc-windows-msvc
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by inquisitivecrystal** [comment] 2021-07-18 08:48
Is this actually a bug? Obtaining a value of a value of type ! is [undefined behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). As I understand it, that means we're not obliged to compile a program that tries to do it, though I could be mistaken.

**Comment by IQBigBang** [comment] 2021-07-18 12:07
Even if code may exhibit undefined behavior at runtime, I feel like it should still be able to compile if it's type correct which IMHO this code is. Although feel free to correct me if I'm wrong, I'm no expert.

**Comment by jyn514** [comment] 2021-07-18 14:52
Duplicate of https://github.com/rust-lang/rust/issues/35121

**Closed by jyn514** 2021-07-18 14:52 UTC
Labels: C-bug
