### ISSUE TITLE
Cannot borrow from generic `Copy` types in a `const` context

### ISSUE THREAD

**Issue by kupiakos** [rust-lang/rust#120119] opened 2024-01-19 02:31 UTC
I tried this code:

```rust
trait C: Copy + 'static {
    type Val: Copy + 'static;
    const VAL: Self::Val;
    const S: Self;
}

#[derive(Clone, Copy)]
struct FooGen<T: C>(T);
impl<T: C> FooGen<T> {
    const VAL: &'static Self = &FooGen(T::S);
}

struct FooAssoc<T: C>(T::Val);
impl<T: C> Clone for FooAssoc<T> { fn clone(&self) -> Self { *self } }
impl<T: C> Copy for FooAssoc<T> {}
impl<T: C> FooAssoc<T> {
    const VAL: &'static Self = &FooAssoc(T::VAL);
}
```

I expected the `Copy` bounds to be sufficient to allow this to compile. `Copy` is an [imperfect analog](https://github.com/rust-lang/rfcs/pull/2944#issuecomment-1408183652) for a lack of interior mutability, much like it is an imperfect analog for `!Drop`.

Instead, this happened:

```
error[E0492]: constants cannot refer to interior mutable data
  --> src/lib.rs:10:32
   |
10 |     const VAL: &'static Self = &FooGen(T::S);
   |                                ^^^^^^^^^^^^^ this borrow of an interior mutable value may end up in the final value

error[E0492]: constants cannot refer to interior mutable data
  --> src/lib.rs:21:32
   |
21 |     const VAL: &'static Self = &FooAssoc(T::VAL);
   |                                ^^^^^^^^^^^^^^^^^ this borrow of an interior mutable value may end up in the final value

```

Ideally, stable code would be able to bound on a lack of interior mutability (like a `NoCell`/`Freeze` trait) to allow this sort of generic code to work without needing [`const_refs_to_cell`](https://github.com/rust-lang/rust/issues/80384) stabilized, as it's a [useful property](https://github.com/rust-lang/rust/issues/60715#issuecomment-1677858534) to be able to bound on for `unsafe` code.

### Meta

```
1.7.0-stable (2023-12-21 82e1608)
```

**Comment by fmease** [comment] 2024-03-01 10:40
cc #121675, #121840

**Comment by oli-obk** [comment] 2024-03-01 11:59
Duplicate of https://github.com/rust-lang/rust/issues/60715

**Closed by oli-obk** 2024-03-01 11:59 UTC
Labels: T-lang, T-compiler, C-bug, A-const-eval

**Comment by RalfJung** [comment] 2024-06-17 12:45
> Copy is an  imperfect analog for a lack of interior mutability

It is not, and anyone relying on this is risking breakage in future versions of Rust. It is quite probable that we will eventually allow people to do something like `unsafe impl Copy for`, at which point one can easily have `Freeze + Copy` types.
