### ISSUE TITLE
Compiler panic when running rustdoc

### ISSUE THREAD

**Issue by matthunz** [rust-lang/rust#108061] opened 2023-02-14 20:07 UTC
### Code

The [`skia-safe`](https://github.com/rust-skia/rust-skia) crate

### Meta

```
rustc 1.69.0-nightly (065852def 2023-02-13) running on aarch64-apple-darwin
```

### Error output

```
thread 'rustc' panicked at 'no resolution for "Path" MacroNS DefId(0:2566 ~ skia_safe[0ba6]::core::path_types)', src/librustdoc/passes/collect_intra_doc_links.rs:393:32
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x1039d014c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41165bc928a6a061
   1:        0x103a1fbf4 - core::fmt::write::hc1381c8a8889ae59
   2:        0x1039c3b7c - std::io::Write::write_fmt::h597fe54d40a99bca
   3:        0x1039cff60 - std::sys_common::backtrace::print::hffd3791d3c76c5bf
   4:        0x1039d2a40 - std::panicking::default_hook::{{closure}}::hdcf127fa35c85582
   5:        0x1039d2798 - std::panicking::default_hook::hea25b24bcf201545
   6:        0x10bda393c - rustc_driver_impl[bf58ad8ec9b96ac6]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x1039d3138 - std::panicking::rust_panic_with_hook::h1f31579a116a5567
   8:        0x1039d2f30 - std::panicking::begin_panic_handler::{{closure}}::h91adc5c2252dfa41
   9:        0x1039d05ac - std::sys_common::backtrace::__rust_end_short_backtrace::h1ce4494cc6011cab
  10:        0x1039d2c8c - _rust_begin_unwind
  11:        0x103a4ac38 - core::panicking::panic_fmt::he9b8054d565a504b
  12:        0x102686e20 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  13:        0x102686f14 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector>::resolve
  14:        0x10268a398 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_item
  15:        0x1026946d8 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_inner_recur
  16:        0x10268c134 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_item
  17:        0x1026946d8 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_inner_recur
  18:        0x10268c134 - <rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::LinkCollector as rustdoc[45017e1e30933be6]::visit::DocVisitor>::visit_item
  19:        0x102685cf4 - rustdoc[45017e1e30933be6]::passes::collect_intra_doc_links::collect_intra_doc_links
  20:        0x10264f104 - <rustc_session[89163586e80eb523]::session::Session>::time::<rustdoc[45017e1e30933be6]::clean::types::Crate, rustdoc[45017e1e30933be6]::core::run_global_ctxt::{closure#7}>
  21:        0x1026bc214 - rustdoc[45017e1e30933be6]::core::run_global_ctxt
  22:        0x10264f48c - <rustc_session[89163586e80eb523]::session::Session>::time::<(rustdoc[45017e1e30933be6]::clean::types::Crate, rustdoc[45017e1e30933be6]::config::RenderOptions, rustdoc[45017e1e30933be6]::formats::cache::Cache), rustdoc[45017e1e30933be6]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  23:        0x10254fb38 - <rustc_middle[1df477d6d6e6e6bb]::ty::context::GlobalCtxt>::enter::<rustdoc[45017e1e30933be6]::main_args::{closure#1}::{closure#0}::{closure#1}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  24:        0x1025812f0 - <rustc_interface[fd812d6d93653895]::interface::Compiler>::enter::<rustdoc[45017e1e30933be6]::main_args::{closure#1}::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  25:        0x10264e644 - rustc_span[bd1a3074b802070d]::with_source_map::<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  26:        0x1025bf678 - <scoped_tls[b65597938795c41d]::ScopedKey<rustc_span[bd1a3074b802070d]::SessionGlobals>>::set::<rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  27:        0x102660f90 - std[63e5474b8dbdb59]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[fd812d6d93653895]::util::run_in_thread_pool_with_globals<rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>
  28:        0x10271b890 - <<std[63e5474b8dbdb59]::thread::Builder>::spawn_unchecked_<rustc_interface[fd812d6d93653895]::util::run_in_thread_pool_with_globals<rustc_interface[fd812d6d93653895]::interface::run_compiler<core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>, rustdoc[45017e1e30933be6]::main_args::{closure#1}>::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[ffaedfe380a89c03]::result::Result<(), rustc_errors[684c395a6d8c68d2]::ErrorGuaranteed>>::{closure#1} as core[ffaedfe380a89c03]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:        0x1039db560 - std::sys::unix::thread::Thread::new::thread_start::h7b399846e2ac9979
  30:        0x1c49e1240 - __pthread_deallocate

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0-nightly (065852def 2023-02-13) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

```

</p>
</details>

**Comment by lukas-code** [comment] 2023-02-14 20:46
probably duplicate of https://github.com/rust-lang/rust/issues/107995

**Comment by petrochenkov** [comment] 2023-02-19 14:12
This is some different issue than https://github.com/rust-lang/rust/issues/107995, it's not resolved by https://github.com/rust-lang/rust/pull/108129.
I'll investigate in more detail in a couple of days.

**Comment by petrochenkov** [comment] 2023-03-20 13:07
Fixed in https://github.com/rust-lang/rust/pull/109266.

**Closed** 2023-03-20 20:05 UTC
Labels: T-rustdoc, I-ICE, T-compiler, C-bug
