### ISSUE TITLE
permit `Drop` types in constants (tracking issue for RFC #1440)

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#33156] opened 2016-04-22 21:01 UTC
Tracking issue for rust-lang/rfcs#1440: "Allow Drop types in statics/const functions"

- [x] Implement [amendment RFC](https://github.com/rust-lang/rfcs/pull/1817)
- [ ] [Improve error message](https://github.com/rust-lang/rust/pull/44212#discussion_r136288924)

**Comment by kornholi** [comment] 2016-06-03 01:40
Ran into an ICE: #34053

**Comment by brson** [comment] 2017-01-11 02:14
Is there anything holding up this feature? No activity.

This is [used by Rocket](https://github.com/SergioBenitez/Rocket/issues/19#issuecomment-269052006).

**Comment by coder543** [comment] 2017-02-06 18:27
Bumping this as well. It seems like a good candidate for stabilization?

**Comment by SimonSapin** [comment] 2017-02-26 09:59
+1 for stabilization.

Servo has a hack to work around this: a separate type with no destructor for using a static phf map, and a conversion during lookup. (This is in a crate used by Firefox, which runs on stable Rust.)

**Comment by nikomatsakis** [comment] 2017-03-02 18:32
I feel ok with stabilizing drop types in **statics** specifically.

**Comment by nikomatsakis** [comment] 2017-03-02 18:33
@rfcbot fcp merge

I propose that we stabilize this feature, which allows types that implement `Drop` to appear in `static` and `const fn`. It does not (yet) permit them in `const` initializers, though there is a pending RFC https://github.com/rust-lang/rfcs/pull/1817 on that topic (which has a few complications).

**Comment by eddyb** [comment] 2017-03-02 18:39
@rfcbot fcp concern We can't stabilize this until we ban temporaries that "would drop" (see #40036).

**Comment by aturon** [comment] 2017-03-14 21:09
@rfcbot fcp cancel

I'm cancelling FCP due to @eddy's comment, just to get it cleared out of the queue. Let's revisit when https://github.com/rust-lang/rust/issues/40036 is closed.

**Comment by brson** [comment] 2017-05-22 23:03
No progress here lately. @eddyb what's the likelihood of fixing https://github.com/rust-lang/rust/issues/40036 any time soon?

**Comment by eddyb** [comment] 2017-08-28 08:13
With rvalue promotion stabilized, #43932 produces no regressions and is waiting on review.
Once it's merged, we can implement the amendment RFC (for `const`s, including associated ones).
Do we need to delay stabilizing this feature, *including* the amendment, @rust-lang/lang?
Otherwise I'll propose to implement the amendment and stabilize it at once.

**Comment by aturon** [comment] 2017-08-28 19:46
@eddyb I think it's totally fine to stabilize the original feature at this point, but am *slightly* wary of stabilizing the amendment immediately upon implementation. OTOH, it's a little hard to imagine that we'll get much feedback on nightly about it.

**Comment by eddyb** [comment] 2017-08-31 05:12
@rfcbot fcp merge

I propose that we implement the amendment and stabilize this feature now that the main blocker has been resolved - see https://github.com/rust-lang/rust/issues/33156#issuecomment-325289795 also.

**Closed** 2017-09-13 05:32 UTC
Labels: B-RFC-implemented, B-unstable, C-tracking-issue, final-comment-period, T-lang
