### ISSUE TITLE
regression in deterministic codegen from 1.32 to 1.33 when using --remap-path-prefix to compensate for change in source dir

### ISSUE THREAD

**Issue by jhfrontz** [rust-lang/rust#59542] opened 2019-03-30 00:18 UTC
I use a [gitian build environment](https://github.com/devrandom/gitian-builder) to compile rust source in a well-defined/stabile environment.  When using rust 1.32 (rust-1.32.0-1.el7.x86_64.rpm on Centos 7), I can [deterministically build](https://github.com/rust-lang/rust/issues/34902) object/binary (with the help of `RUSTFLAGS="--remap-path-prefix=%{_builddir}=BUILDDIR -C link-arg=-Wl,--build-id=0x%{githash},-S"` while running inside an `rpmbuild`) -- like, the build process when using 1.32 is so deterministic between runs that I can use `diff` (or `cmp` or `sha256sum`) to verify that two products/executables produced on different runs are identical.

However, as of 1.33 (rust-1.33.0-2.el7.x86_64.rpm on Centos 7), I get significant variation from one run to another:
```
$ size *float-[12]/build/usr/bin/program
   text	   data	    bss	    dec	    hex	filename
6154818	 157808	    688	6313314	 605562	20190329-float-1/build/usr/bin/program
6148249	 157328	    688	6306265	 6039d9	20190329-float-2/build/usr/bin/program
```

Among other things, the layout of the address space seems to vary (sample):

```
$ sdiff <(objdump -d *float-1/build/usr/bin/program) <(objdump -d *float-2/build/usr/bin/program) | head -20

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx904e-20190329-float-1/bui |	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx904e-20190329-float-2/bui


Disassembly of section .init:					Disassembly of section .init:

00000000001438b0 <_init>:				      |	00000000001430b0 <_init>:
  1438b0:	48 83 ec 08          	sub    $0x8,%rsp      |	  1430b0:	48 83 ec 08          	sub    $0x8,%rsp
  1438b4:	48 8b 05 c5 19 6c 00 	mov    0x6c19c5(%rip) |	  1430b4:	48 8b 05 ed 00 6c 00 	mov    0x6c00ed(%rip)
  1438bb:	48 85 c0             	test   %rax,%rax      |	  1430bb:	48 85 c0             	test   %rax,%rax
  1438be:	74 05                	je     1438c5 <_init+ |	  1430be:	74 05                	je     1430c5 <_init+
  1438c0:	e8 53 01 00 00       	callq  143a18 <.plt.g |	  1430c0:	e8 53 01 00 00       	callq  143218 <.plt.g
  1438c5:	48 83 c4 08          	add    $0x8,%rsp      |	  1430c5:	48 83 c4 08          	add    $0x8,%rsp
  1438c9:	c3                   	retq   		      |	  1430c9:	c3                   	retq   

Disassembly of section .plt:					Disassembly of section .plt:

00000000001438d0 <.plt>:				      |	00000000001430d0 <.plt>:
  1438d0:	ff 35 ba 16 6b 00    	pushq  0x6b16ba(%rip) |	  1430d0:	ff 35 42 ff 6a 00    	pushq  0x6aff42(%rip)
  1438d6:	ff 25 bc 16 6b 00    	jmpq   *0x6b16bc(%rip |	  1430d6:	ff 25 44 ff 6a 00    	jmpq   *0x6aff44(%rip
```

Was something intentionally changed in 1.33 that might cause this behavior?

EDIT [incorporating subsequent info](https://github.com/rust-lang/rust/issues/59542#issuecomment-484719854):

I found a smallish open-source project that demonstrates the issue. Run
[build.sh.txt](https://github.com/rust-lang/rust/files/3096459/build.sh.txt) -- under 1.32, I get all good; under 1.33, I get bad stuff.

**Comment by jonas-schievink** [comment] 2019-03-30 14:15
AFAIK we have very few tests for reproducible builds, so this probably slipped in by accident.

cc @rust-lang/compiler - do we care enough about reproducible builds to consider this a stable-to-stable regression at this point? I know that quite a lot of people want reproducibility in their builds.

**Comment by eddyb** [comment] 2019-03-30 15:37
This looks like a linker thing? Did we do anything wrt using lld or something like that?
cc @alexcrichton

**Comment by eddyb** [comment] 2019-03-30 15:39
@jhfrontz Can you post a diff of symbol names and sizes? The assembly will ofc differ a lot, but I expect everything to be the same size, just shuffled around.

**Comment by jhfrontz** [comment] 2019-03-31 15:42
@eddyb asks:
> Can you post a diff of symbol names and sizes? 

Are you wanting the output of `nm` on the two same-but-different binaries?  Or maybe (since you said *size*) you're wanting the output of `objdump -t` ?  But since you said *shuffled around*, maybe you're wanting ` objdump -h` ?

I'll include the last (`objdump -h`): [diff-h.txt](https://github.com/rust-lang/rust/files/3026784/diff-h.txt)

**Comment by jhfrontz** [comment] 2019-04-01 10:24
@eddyb I got approval to include the full `objdump -t` output:
[objdump-t-1.txt.gz](https://github.com/rust-lang/rust/files/3028845/objdump-t-1.txt.gz)
[objdump-t-2.txt.gz](https://github.com/rust-lang/rust/files/3028846/objdump-t-2.txt.gz)

.

**Comment by alexcrichton** [comment] 2019-04-01 11:03
This is most frequently an accidental regression in LLVM, although we've had bugs slip in with rustc as well! No major change to linker behavior in 1.32 -> 1.33. 

@jhfrontz the best way to get this fixed is if a test case can be reduced to isolate the issue. Would it be possible to minimize this to extract a small piece of code which exhibits the reproducibility issue?

**Comment by jhfrontz** [comment] 2019-04-12 19:24
@alexcrichton asks:
> Would it be possible to minimize this to extract a small piece of code which exhibits the reproducibility issue?

I haven't been able to -- my simple "hello, world" toy programs always result in the same binary. It's only when I build production (proprietary) code that I'm seeing this.  Full disclosure: I barely know enough rust to be able to run `cargo`.  If there is a model "major project" in rust that I could/should run through my deterministic build environment, I'd be glad to try it and report back.

**Comment by eddyb** [comment] 2019-04-13 09:26
Sorry, I didn't see the notification. 
I was hoping for a diff that would be easy to spot the differences in, but I guess I'll download the two files and run kdiff3 on them, when I get to the office

**Comment by eddyb** [comment] 2019-04-13 17:59
I just did this:
```sh
gunzip ~/Downloads/objdump-t-{1,2}.txt.gz
cat ~/Downloads/objdump-t-1.txt | grep _ZN | sed -E 's/^.* +([^ ]+)$/\1/' | sort > sym1
cat ~/Downloads/objdump-t-2.txt | grep _ZN | sed -E 's/^.* +([^ ]+)$/\1/' | sort > sym2
```
And... the hashes don't match. These are using the same rustc binary, right?

Can you run `cargo` with `-v` and grab the `-C metadata` arguments? If they differ between the two runs, then your problem is not even in rustc/LLVM.
If they're the same, try getting the sorted symbol list from a small `rlib`.

**Comment by jhfrontz** [comment] 2019-04-16 23:44
I'm using the same binary (everything is the same, including the time -- via libfaketime).

```
---> Package rust.x86_64 0:1.33.0-2.el7 will be installed
--> Processing Dependency: rust-std-static(x86-64) = 1.33.0-2.el7 for package: rust-1.33.0-2.el7.x86_64
--> Processing Dependency: libLLVM-7.so(LLVM_7)(64bit) for package: rust-1.33.0-2.el7.x86_64
--> Processing Dependency: libLLVM-7.so()(64bit) for package: rust-1.33.0-2.el7.x86_64
```

I'm building with `cargo --frozen` so, I'm pretty sure by definition the actual contents metadata is the same (though `cargo -v -C metadata` yields `error: Found argument '-C' which wasn't expected, or isn't valid in this context`).

However, the *ordering* of the crates listed in the metadata from two builds is different.   Also, the src_path entries are different (but I would expect for that to be irrelevant in the presence of the `--remap-path-prefix` [mentioned above](https://github.com/rust-lang/rust/issues/59542#issue-427220343) ).  At least, the src_path is irrelevant when using 1.32.

Attached are the dumps from `nm` on two different runs' libuuid rlibs.  They're both quite different.

[3-libuuid-nm.txt](https://github.com/rust-lang/rust/files/3087277/3-libuuid-nm.txt)
[4-libuuid-nm.txt](https://github.com/rust-lang/rust/files/3087278/4-libuuid-nm.txt)


Just to recall -- this *still* works as expected (producing deterministic binary) if I revert to rustc version 1.32.

**Comment by eddyb** [comment] 2019-04-17 07:43
Ah, yeah, `--remap-path-prefix` isn't perfect, so this could be a regression related to that.

Also, by `cargo -v` and `-C metadata` I meant running whatever cargo command you're running with `-v` (i.e. verbose) and extracting the `-C metadata` from the `rustc` invocations it prints to stderr.

> I'm building with `cargo --frozen` so, I'm pretty sure by definition the actual contents metadata is the same

`--frozen` is for your dependencies, but if you're building in a different directory, that might still affect certain details.

> However, the ordering of the crates listed in the metadata from two builds is different.

Not sure what you mean by "metadata" here (I was referring to a hash Cargo passes to each rustc invocation).

**Comment by eddyb** [comment] 2019-04-17 07:44
Nominating for discussion at the next @rust-lang/compiler meeting, as this seems more and more like it's a regression in how we handle source paths.

**Comment by michaelwoerister** [comment] 2019-04-18 12:18
The ordering of `-C metadata` arguments should not make a difference. 

`--remap-path-prefix` can be used to map various paths that show up in panic messages and debuginfo to something deterministic/environment-independent. It doesn't do anything beyond that.

**Comment by eddyb** [comment] 2019-04-18 14:14
@michaelwoerister I was referring to the *contents*, not ordering.
As in, I was wondering whether `Cargo` was computing different values for each of the two builds.

But from what you're saying, `--remap-path-prefix` shouldn't have ever been relied on for deterministic outputs? Does that mean that between 1.32 and 1.33, we started hashing the input paths, whereas before we *weren't at all*?

Or did we start hashing the `remap-path-prefix` value itself?
What would even cause all of this to trickle down into mangled symbol hashes?

**Comment by michaelwoerister** [comment] 2019-04-18 15:08
I'd like to have an actual reproducer for this. Otherwise it's hard to dig any deeper.

**Comment by pnkfelix** [comment] 2019-04-18 22:09
We discussed in T-compiler team meeting [today](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-04-18.20.2354818/near/163658081). removing nominated tag.

**Comment by pnkfelix** [comment] 2019-04-18 22:09
(and I'm going to hijack the "S-waiting-on-author" tag to mean "waiting on more info from issue filer.")

**Comment by jhfrontz** [comment] 2019-04-18 23:16
I found a smallish open-source project that demonstrates the issue.   Run 
[build.sh.txt](https://github.com/rust-lang/rust/files/3096459/build.sh.txt) -- under 1.32, I get `all good`; under 1.33, I get `bad stuff`.

**Comment by eddyb** [comment] 2019-04-19 08:40
@michaelwoerister Oh, if `--remap-path-prefix` *is* supported for this usecase, maybe we could take a look at some incremental/query log, specifically when moving (or `ln -s`) the `one` directory to `two`, removing everything in `target` except incremental caches and re-running `cargo build`.
I suspect that the same issue affecting symbol hashes would also show up in there.

**Comment by jhfrontz** [comment] 2019-04-25 16:21
@eddyb wrote
>  maybe we could take a look at some incremental/query log, specifically when moving (or aliasing with `ln -s`) the `one` directory to `two`, removing everything in `target` except incremental caches and re-running `cargo build` in `two`.

I just realized that you may have been asking me to do some further data gathering -- if so, I'm not sure I understand what you're requesting.  Should I unroll the loop in  [build.sh.txt](https://github.com/rust-lang/rust/files/3096459/build.sh.txt) and have the `two` pass do something different?

**Comment by michaelwoerister** [comment] 2019-04-26 08:45
I don't think incremental compilation should be used at all when trying to create reproducible builds. @jhfrontz, could you try to set `CARGO_INCREMENTAL=0` in your test setup?

**Comment by jhfrontz** [comment] 2019-04-26 16:25
> I don't think incremental compilation should be used at all when trying to create reproducible builds. @jhfrontz, could you try to set `CARGO_INCREMENTAL=0` in your test setup?

No effect.

```
$ rustc --version
rustc 1.32.0
$ CARGO_INCREMENTAL=0 ./build.sh
...
all good
```

```
$ rustc --version
rustc 1.33.0
$ CARGO_INCREMENTAL=0 ./build.sh
...
bad stuff
```

**Comment by michaelwoerister** [comment] 2019-04-29 06:02
Thanks for checking, that's a valuable data point.

**Comment by michaelwoerister** [comment] 2019-04-30 09:44
It looks like Cargo is passing different `-C metadata` arguments to `rustc` when compiling the same crate from different directories, so `rustc` has to generate different symbol names for the two binaries (i.e. Cargo is basically telling `rustc` that these are two different versions of the same crate). So this is a regression in Cargo rather than `rustc`, I'd say.

**Comment by eddyb** [comment] 2019-04-30 11:54
@michaelwoerister Ah, I thought that had been ruled out upthread.

The reason I wanted incremental was to find where the hashes start to diverge, but that was assuming identical invocations (which is not the case here).

Also, unless we want Cargo to parse `RUSTFLAGS`, this may have been a legitimate bugfix?

**Comment by michaelwoerister** [comment] 2019-04-30 11:58
I don't know how Cargo generates the `-C metadata` argument. I assumed it was based the semver of a crate and not on things in `RUSTFLAGS`.

**Comment by eddyb** [comment] 2019-04-30 12:45
I meant that it seems potentially legitimate to include a crate's path (i.e. it may have fixed a different bug), and it presumably doesn't parse `RUSTFLAGS` to find out about `--remap-path-prefix` (so it doesn't do the remapping rustc does).

However, if Cargo had the equivalent flag, that applied to both Cargo and rustc, then that would solve the problem (assuming Cargo has a good reason for hashing the path).

**Comment by eddyb** [comment] 2019-04-30 13:57
Ironically, looks like this may be caused by hashing `RUSTFLAGS`, not the directory itself otherwise: @Eh2406 pointed me to https://github.com/rust-lang/cargo/pull/6503 (which would definitely cause this).

One alternative could be a relative `--remap-path-prefix` value, that `rustc` canonicalizes in the same way it does input paths, but I'm not sure that would actually work.

**Comment by jhfrontz** [comment] 2019-05-01 13:55
@eddyb writes:
>One alternative could be a relative --remap-path-prefix value, that rustc canonicalizes in the same way it does input paths, but I'm not sure that would actually work.

I don't understand -- is this something I should try?   If so, what is the format of the path I should use for the experiment?

**Comment by eddyb** [comment] 2019-05-01 16:13
I have no idea if it would work (i.e. it might cause rustc to error, or not do any remapping), but something like `--remap-path-prefix=.=BUILDDIR` (the `.` might need to be `..` or `../..` etc. -  depends on your setup).
At least Cargo wouldn't give rustc different `-C metadata` hashes.

**Comment by jhfrontz** [comment] 2019-05-01 19:16
I did
```
$ diff ../build.sh . 
38c38
<     RUSTFLAGS="--remap-path-prefix=$(dirname $PWD)=BUILDDIR -C link-arg=-Wl,--build-id=0xdeadbeef,-S"
---
>     RUSTFLAGS="--remap-path-prefix=.=BUILDDIR -C link-arg=-Wl,--build-id=0xdeadbeef,-S"
```
and got `all good` on 1.33.

I'm not sure I understand the magic, though. 

I'm going to try it on my production build and see if it makes things better.

**Comment by eddyb** [comment] 2019-05-01 20:40
The "magic" is that `Cargo` sees the same `RUSTFLAGS`, so it doesn't think anything is different, but then `rustc` normalizes the `.` to the right absolute directory (which you used to pass yourself).
Frankly, I'm surprised (and a bit suspicious) that it works!

Can you check in some way that no paths end up in the result, only `BUILDDIR`?

**Comment by apoelstra** [comment] 2019-05-01 20:49
Confirmed that only `BUILDDIR` appears in the binaries output from Jeff's script.

I'm also suspicious and surprised because I can't see where in the rustc remapping code `.` would get expanded.

**Comment by eddyb** [comment] 2019-05-01 21:07
I just checked the relevant source, and, yeah, I don't know why this would work.
@jhfrontz Does it pass if you remove `--remap-path-prefix=.=BUILDDIR` completely?

**Comment by apoelstra** [comment] 2019-05-01 21:19
It fails for me without the remapping. And checking the outputted binary it has a lot of stuff like
```
/home/apoelstra/Downloads/one/ff/vendor/clap/src/osstringext.rs
```
i.e. the full path is there, not the literal `.` or anything else.

**Comment by jhfrontz** [comment] 2019-05-01 21:49
Also -- `--remap-path-prefix=.=BUILDDIR` does **not** help for my production build (i.e., even with the `.`, I get different binary on each subsequent build).

**Comment by eddyb** [comment] 2019-05-01 22:06
I believe this would explain why at least some cases are handled: https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/encoder.rs#L346-L356

@jhfrontz I'm not sure I can figure that out without a binary diff between the two binaries.

I doubt `..` can work, since it's never canonicalized by rustc, so it would only affect a literal `..` in the input.
Maybe `src` instead of `.` might work? Or both (`.=BUILDDIR` and `src=BUILDIR/src`).

The problem is I don't know what kind of paths you have, and the first component in each path matters.
If the paths are absolute, then there's no way around having the absolute path in `--remap-path-prefix`.

But maybe the right approach would be https://github.com/rust-lang/cargo/pull/6503 being changed to not affect `-C metadata`, only Cargo's caching. cc @alexcrichton @ehuss Is that even possible right now?

**Comment by alexcrichton** [comment] 2019-05-02 15:01
Unfortunately the purpose of that Cargo PR is to affect `-C metadata`, but we could back that PR out if it causes too many problems (or add some flag/config to Cargo to not affect `metadata` but still do it by default or something like that)

**Comment by apoelstra** [comment] 2019-05-02 15:11
It would be nice if there were a flag. I wouldn't want to back out the PR. I'm surprised we didn't see more problems *before* the Cargo PR; I seem to recall a lot of trouble a year or so ago with Miri caused by not enough things going into `metadata` and builds using stale/incompatible dependencies.

Having said that, based on @jhfrontz's original post, and our inability to use the `.=BUILDDIR` trick in our production code, I'm not sure that the `metadata` issue is the only one at play here. I believe he is working on extracting a smaller test case that we can share.

**Comment by eddyb** [comment] 2019-05-03 02:15
@alexcrichton Ah, I misunderstood an important aspect: all the artifacts are kept in the same directory, and only `-C metadata` makes `rustc` ignore those from incompatible builds?

**Comment by alexcrichton** [comment] 2019-05-03 14:17
@eddyb that plus it's the granularity Cargo caches at. The intention of the PR was that if you oscillate back and forth on `RUSTFLAGS` values you'll have incremental builds each time, whereas previously it would recompile the whole crate graph.

**Comment by jhfrontz** [comment] 2019-05-03 16:07
@eddyb here're 4 binaries generated using our deterministic process on the same source -- two using 1.32 and two using 1.34 (sorry, I didn't save the 1.33 package before the new one rolled out -- if you want 1.33-generated ones specifically, I can try to roll back a development machine): [rust_issue_59542.zip](https://github.com/rust-lang/rust/files/3142592/rust_issue_59542.zip)  (sorry about the MacOS metacruft-- I had to convert my rejected tar file to a zip file on the fly).

These are the interesting contents:
```
$ find . -type f -name \*conf\* | grep usr/bin | sort | xargs sha256sum                
82208c253a3615cf9f5207e67e46054cb4329534852b6012e1be2c326f4c5e04  ./1.32build/artifacts-2/usr/bin/create_test_daemon_conf
82208c253a3615cf9f5207e67e46054cb4329534852b6012e1be2c326f4c5e04  ./1.32build/artifacts/usr/bin/create_test_daemon_conf
dc9d35006b5791055b2aa36d8d015ccb1df6ae392246e62e78523d0f790c81e1  ./1.34build/artifacts-2/usr/bin/create_test_daemon_conf
e63d1315133f4e795459deb5791b1070a3ae60d4df6cb7be856e8ad73d42a6ee  ./1.34build/artifacts/usr/bin/create_test_daemon_conf
```

**Comment by eddyb** [comment] 2019-05-03 22:35
@jhfrontz What `RUSTFLAGS` were being used? I can't find any paths left in those that don't start with `BUILDDIR` so I can't tell what's happening.
Do you have access to the `target` directory of the build? If so, can we arrange that we talk on IRC or Discord, in real time?

Sorry, but it's almost impossible to tell you what to look for, since I have almost no idea myself.
My latest guess is a build script producing different output, but I don't even know yet if the `.=BUILDDIR` trick fixes *all* `-C metadata` hashes, or just some (you can run `find` in the `target` directory of each build, sort, then diff the resulting file lists, to see if Cargo thinks they should be different).

**Comment by eddyb** [comment] 2019-05-03 22:57
Something I forgot to suggest would be to try using older Cargo with newer rustc and vice-versa.
This way we can at least know if the compiler regressed at all, or if it's all caused by rust-lang/cargo#6503.

**Comment by jhfrontz** [comment] 2019-05-04 00:25
@eddyb the exact RUSTFLAGS varies because the build is done in an `rpmbuild` environment, but the form is
```
RUSTFLAGS="--remap-path-prefix=%{_builddir}=BUILDDIR -C link-arg=-Wl,--build-id=0x%{githash},-S"
```
where `%{_builddir}` is filled in by the build environment, and of the form `/home/centos/tmprpmbuild/tmp.7d9wsOKK9I/BUILD`; `%{githash}` is similarly expanded to be a hex string.

I can regenerate a build at-will -- I should still have the original ones that were used for the attached examples.

I'll try to mix the cargo/rustc versions and see what that produces.

**Comment by jhfrontz** [comment] 2019-05-04 01:51
Two different runs of cargo-1.32/rustc-1.34 [create_test_daemon_conf.zip](https://github.com/rust-lang/rust/files/3143938/create_test_daemon_conf.zip)

**Comment by jhfrontz** [comment] 2019-05-04 19:18
```
find . -type d -name target | while read target
do
find ${target} | grep create_test_daemon_conf
done | sort  > target-create_test_daemon_conf.txt
```
[target-create_test_daemon_conf.txt](https://github.com/rust-lang/rust/files/3144724/target-create_test_daemon_conf.txt)

**Comment by eddyb** [comment] 2019-05-05 11:45
```sh
cat ~/Downloads/target-create_test_daemon_conf.txt | rg '/artifacts/' | sed 's|^.*/targe
t/debug/||' > files-1
cat ~/Downloads/target-create_test_daemon_conf.txt | rg '/artifacts-2/' | sed 's|^.*/target/debug/||' > files-2
kdiff3 files-{1,2}
```
So this is pretty nice, but I'm assuming the `deps` is elided to keep things small?
In that subset, only paths under `incremental` differ, which means that:
1. for that run, Cargo uses the same `-C metadata` (is that run "old Cargo, new rustc"?), at least for the final crate
2. AFAIK, the incremental thing is a random "session number", so it might not factor into the output, but maybe you could turn incremental off (such as building in release mode, if that's still a thing)

**Comment by apoelstra** [comment] 2019-05-05 13:35
We've overloaded our debug and release profiles with
```
[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-g`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false        # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
codegen-units = 1  # controls whether the compiler passes `-C codegen-units`
                   # `codegen-units` is ignored when `lto = true`
panic = 'abort'    # abort on panic

[profile.release]
opt-level = 3      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-g`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false        # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
codegen-units = 1  # controls whether the compiler passes `-C codegen-units`
                   # `codegen-units` is ignored when `lto = true`
panic = 'abort'    # abort on panic
```
Do we need to change any of these in order that "try building in release mode" will have the effect you're hoping for?

**Comment by eddyb** [comment] 2019-05-05 13:39
@apoelstra You should really try a local build with an empty `target` directory (what you're compiling doesn't matter, it could be a crate created by `cargo new`) and then check if the `incremental` directory is there.
(And you can use the exact versions of Cargo and `rustc` that you use in production)

That way we're not guessing at what's happening. Also, `CARGO_INCREMENTAL=0` in debug mode might be enough, and that would remove the potential issue of longer release builds.

**Comment by michaelwoerister** [comment] 2019-05-06 11:17
Hey, to re-iterate: There is no way to have reproducible builds via Cargo from different source directories if Cargo feeds the RUSTFLAGS value into the `-Cmetadata` argument to `rustc`. In my opinion this is a bug in Cargo. Either Cargo needs to provide a way to pass the `--remap-path-prefix` argument to `rustc` without RUSTFLAGS or the new behavior should be made optional.

**Comment by eddyb** [comment] 2019-05-06 12:32
@michaelwoerister Yes, but using an older Cargo without that behavior *does not* fix the issue.
So we're now trying to find the other (presumably in `rustc`, or a build script) bug.

**Comment by michaelwoerister** [comment] 2019-05-06 12:41
Ah, OK. Go on then `:)`

**Comment by jhfrontz** [comment] 2019-05-07 00:59
OK, it turns out that it **is** cargo that is causing the issue (@eddyb found that I wasn't actually using the 1.32 version of cargo in my earlier experiments).  Now, with cargo-1.32 and rust-1.34, I get deterministic output:

```
$ find . -name create_test_daemon_conf | grep build/usr/bin | xargs sha256sum
b0d3d894800eb6c80286e5830a6f9c28394f9bb0ed6d1a52827bd813e8848e6a  ./artifacts-2/build/usr/bin/create_test_daemon_conf
b0d3d894800eb6c80286e5830a6f9c28394f9bb0ed6d1a52827bd813e8848e6a  ./artifacts/build/usr/bin/create_test_daemon_conf
```

**Comment by eddyb** [comment] 2019-05-07 02:51
I've just hidden a bunch of comments that were really confusing because of unrigorous debugging.

Also, as we've determined this was entirely caused by Cargo, I've opened https://github.com/rust-lang/cargo/issues/6914 instead, and I'm closing this issue on the Rust side.

**Closed by eddyb** 2019-05-07 02:51 UTC
Labels: A-codegen, T-compiler
