### ISSUE TITLE
Regression of "mismatched types" error on trait method call with multiple candidates

### ISSUE THREAD

**Issue by divergentdave** [rust-lang/rust#101066] opened 2022-08-27 00:13 UTC
### Code

I tried this code:

```rust
pub trait FieldElement {
    type Integer: TryFrom<usize, Error = std::num::TryFromIntError>;

    fn valid_integer_try_from<N>(i: N) -> Result<Self::Integer, ()>
    where
        Self::Integer: TryFrom<N>,
    {
        Self::Integer::try_from(i).map_err(|_| ())
    }
}
```

I expected to see this happen: Successful compilation.

Instead, this happened: I now get the following compiler error.

```
error[E0308]: mismatched types
   --> src/lib.rs:8:33
    |
4   |     fn valid_integer_try_from<N>(i: N) -> Result<Self::Integer, ()>
    |                               - this type parameter
...
8   |         Self::Integer::try_from(i).map_err(|_| ())
    |         ----------------------- ^ expected `usize`, found type parameter `N`
    |         |
    |         arguments to this function are incorrect
    |
    = note:        expected type `usize`
            found type parameter `N`
note: associated function defined here
   --> /home/david/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:478:8
    |
478 |     fn try_from(value: T) -> Result<Self, Self::Error>;
    |        ^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `nightly-prio-regression` due to previous error
```

### Version it worked on

It most recently worked on: stable channel Rust 1.63.0, and nightly-2022-08-17.

### Version with regression

searched nightlies: from nightly-2022-08-11 to nightly-2022-08-26
regressed nightly: nightly-2022-08-18
searched commit range: https://github.com/rust-lang/rust/compare/86c6ebee8fa0a5ad1e18e375113b06bd2849b634...9c20b2a8cc7588decb6de25ac6a7912dcef24d65
regressed commit: https://github.com/rust-lang/rust/commit/9c20b2a8cc7588decb6de25ac6a7912dcef24d65

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 
```
</details>

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

While reducing this example, I noticed that the following changes to the code will make the error go away:

- Replacing the function call with `N::try_into(i)`
- Deleting the specification of `Error` in the associated type's trait bound
- Adding the same `Error` specification in the where clause's trait bound

**Comment by compiler-errors** [comment] 2022-08-27 03:00
This is caused by #100652, and therefore fixed by #100966.

**Comment by apiraino** [comment] 2022-08-31 11:47
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23101066.20Regression.20of.20.22mismatched.20types.22.20error.20on.20trait.20met.E2.80.A6)) to add visibility to the relevant pr fixing it

@rustbot label -I-prioritize +P-critical t-compiler

**Closed** 2022-09-03 03:48 UTC
Labels: regression-from-stable-to-nightly, T-compiler, C-bug, P-critical
