### ISSUE TITLE
Detected overflow in ranges should suggest inclusive ranges

### ISSUE THREAD

**Issue by porglezomp** [rust-lang/rust#50641] opened 2018-05-11 01:13 UTC
Now that inclusive ranges are stabilized, we have a good way to write (for example) `0..=255u8`. Right now compiling:
```rust
fn main() {
    for i in 0..256u8 {
        println!("{}", i);
    }
}
```
will give the error message:
```
warning: literal out of range for u8
 --> src/main.rs:2:17
  |
2 |     for i in 0..256u8 {
  |                 ^^^^^
  |
  = note: #[warn(overflowing_literals)] on by default
```
I believe it should additionally suggest using `0..=255u8` as a teaching aid.

**Comment by varkor** [comment] 2018-05-11 08:16
This is a duplicate of https://github.com/rust-lang/rust/issues/47213.

**Closed** 2018-05-11 08:27 UTC
