### ISSUE TITLE
`impl PartialEq for Option` forces both sides to contain the same `T`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#56598] opened 2018-12-07 14:52 UTC
The current `impl PartialEq for Option` looks like this:

```rust
impl<T> PartialEq<Option<T>> for Option<T> where
    T: PartialEq<T> { ... }
```

It could be more general and look like this instead:

```rust
impl<A, B> PartialEq<Option<A>> for Option<B> where
    A: PartialEq<B> { ... }
```

**Comment by nagisa** [comment] 2018-12-07 14:53
Specific use-case where I wanted this to work was:

```rust
if path.file_stem == Some("foo") { ... }
```

**Comment by ollie27** [comment] 2018-12-07 15:44
Duplicate of #20063?

**Closed** 2018-12-07 18:00 UTC
