### ISSUE TITLE
Crate stable-borrow-state regressed in 1.28 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#51840] opened 2018-06-27 13:02 UTC
The test suite of the `stable-borrow-state` crate failed to run, and after a quick glance at the source code I think that's caused by a change in the `RefCell` behavior.

* [stable-borrow-state](https://crates.io/crates/stable-borrow-state) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/stable-borrow-state-0.1.0/log.txt)) cc @tcr

**Comment by tcr** [comment] 2018-06-27 16:52
This crate was intentionally used as a stopgap until I could rely on a nightly feature, and months later is fully unused. I'm going to yank it.

**Comment by Mark-Simulacrum** [comment] 2018-06-27 21:14
Regression caused by aec00f97e1cdcea2b079e209a7e759201ba6ca7c - https://github.com/rust-lang/rust/pull/51466.

This is unsurprising as the library [was transmuting to get at internal details](https://github.com/tcr/stable-borrow-state/blob/master/src/lib.rs#L30). Closing.

**Closed by Mark-Simulacrum** 2018-06-27 21:14 UTC
Labels: T-libs, regression-from-stable-to-beta
