### ISSUE TITLE
`use` suggestions corrupted w/ nearby code when inside items

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#43769] opened 2017-08-09 16:48 UTC
This is... bizarre.

### STR

```rust
fn main() {
    type Dict<K, V> = HashMap<K, V>;
}
```

### Expected

```
help: possible candidates are found in other modules, you can import them into scope
  | use std::collections::HashMap;
  | use std::collections::hash_map::HashMap;
```

### Actual

```
help: possible candidates are found in other modules, you can import them into scope
  | fn main() use std::collections::HashMap;
  | fn main() use std::collections::hash_map::HashMap;
```

<br/>
The issue seems to arise from the erroneous code being inside another block. I originally encountered this with code generated by `lazy_static!`.

**Comment by oli-obk** [comment] 2017-08-09 17:27
Duplicate of https://github.com/rust-lang/rust/issues/42835

**Comment by durka** [comment] 2017-08-09 17:57
Is it a duplicate? Issue here is the suggestion text is invalid.

**Comment by Mark-Simulacrum** [comment] 2017-08-10 15:13
I don't think this is a duplicate of that issue; the diagnostic here needs to be enhanced to not be mangled with surrounding context, which isn't related to updating the message to note where to add the import.

cc @estebank, I seem to recall you doing something with this diagnostic recently that was potentially relevant, but I could be wrong.

**Comment by oli-obk** [comment] 2017-08-10 15:17
It is 100% related. I changed the suggestion placement and screwed up. The suggestions are placed at the beginning of the current module/function, but that just doesn't work in the presence of desugarings. So the suggestion you see doesn't mangle with surrounding context, it is actually placed there!

**Comment by oli-obk** [comment] 2017-08-10 15:21
Anyway, the original issue that's more related is https://github.com/rust-lang/rust/issues/42548, but they are all caused by the same underlying problem

**Comment by estebank** [comment] 2017-08-10 17:17
@Mark-Simulacrum I think the closest PRs I've worked on recently have been #42383 and #42904, but I doubt they affected the current issue given that I'm seeing the problem in the stable compiler as well. I can't find it now, and for all I know [it might have been fixed](https://play.rust-lang.org/?gist=174111eb5ce0832eea04606e7fafcdf4&version=nightly) by now, but there was an issue open about `use` suggestions being placed in weird locations when the suggestion machinery interacts with nested namespaces (which sparked my urgency on completing #42904, so that it'd be more obvious when it happens).

**Closed** 2017-08-21 07:46 UTC
Labels: A-diagnostics, C-enhancement
