### ISSUE TITLE
[Rust 2018] Inconsistent anonymous lifetimes

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#52142] opened 2018-07-07 19:09 UTC
This is allowed by Rust 2018:
```rust
impl<T: SomeTrait<'_>> SomeType<T> { ... }
```
while this is not allowed:
```rust
fn foo<T: SomeTrait<'_>>() { ... }
```

**Comment by CryZe** [comment] 2018-07-21 16:41
I replicated this on the playground: https://play.rust-lang.org/?gist=b7f75c8e5df6945c2065892882b59764&version=nightly&mode=debug&edition=2018

**Comment by aturon** [comment] 2018-07-24 22:16
Duplicate of https://github.com/rust-lang/rust/issues/45667

**Closed by aturon** 2018-07-24 22:16 UTC
Labels: A-lifetimes, A-rust-2018-preview, C-bug
