### ISSUE TITLE
Comparisons with concrete types break in the presence of inapplicable `where` bounds

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/rust#95777] opened 2022-04-07 18:30 UTC
See https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f6449d0fee6e0875b3f92612a5be84bd

**Comment by compiler-errors** [comment] 2022-04-07 23:28
This is probably due to [`SelectionContext::candidate_should_be_dropped_in_favor_of`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_trait_selection/traits/select/struct.SelectionContext.html#method.candidate_should_be_dropped_in_favor_of) preferring param-env candidates (in the where-clause) over impl candidates.

The reason that `&1u8 == &2u8` works in the first function's first line is that [this impl candidate](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#impl-PartialEq%3C%26%27_%20B%3E) applies first when we have `&_` compared to `&_` and doesn't overlap with the param-env candidate.

**Comment by compiler-errors** [comment] 2022-04-07 23:34
Not exactly sure how to fix this without either:
1. adjusting [the logic here](https://doc.rust-lang.org/stable/nightly-rustc/src/rustc_trait_selection/traits/select/mod.rs.html#1665-1675), but I would expect that to have fallout in many other places
2. doing some hacks to infer the real types of the generic arguments we pass to, e.g., `<_ as PartialEq<_>>::eq`, but I fear that would mess with coercions that are used to, e.g., let us do `String + &String` even without an impl that matches this signature exactly [(i.e. coercing into this impl)](https://doc.rust-lang.org/std/string/struct.String.html#impl-Add%3C%26%27_%20str%3E)

**Comment by fmease** [comment] 2024-01-24 13:36
Closing as duplicate of #24066 similar to #84218.

**Closed by fmease** 2024-01-24 13:36 UTC
Labels: A-traits, T-compiler, C-bug
