### ISSUE TITLE
i686 target spec disagrees with downstream definitions

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#82435] opened 2021-02-23 05:47 UTC
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973414.

**Comment by jyn514** [comment] 2021-02-23 05:57
IIUC, the issue is that rustc generates SSE2 instructions on a CPU that doesn't support SSE2? What would the fix be, to add a new target triple for Geode?

**Comment by sanxiyn** [comment] 2021-02-23 06:18
I think what's going on is that Debian and Rust disagree on what i686 is. Debian is clearly right and Rust is clearly wrong (80686 lacks SSE2), but it's what it is and neither here nor there. The issue is analogous to ARM v6/v7 situation.

Rust's i686-unknown-linux-gnu target requires SSE2, so can't run on Geode. Rust's i586-unknown-linux-gnu will run on Geode, but that's unfortunate, because Geode is 686 and not 586 and will miss 686 instructions (including CMOV).

**Comment by cuviper** [comment] 2021-02-23 08:54
Debian could further patch `rustc_target` to disable target-features on i686 -- it seems they already lowered the cpu target from "pentium4" to "pentiumpro".

**Comment by steveklabnik** [comment] 2021-02-23 14:36
I've changed the title to something more descriptive.

**Comment by Shnatsel** [comment] 2021-02-23 15:16
Geode does not support some instructions that Pentium Pro does, so this behavior seems WAI:

> Debian's rustc has a patch to reduce the i386 baseline from upstream's pentium4 to pentiumpro
> https://sources.debian.org/src/rustc/1.48.0+dfsg1-1/debian/patches/d-i686-baseline.patch/
> but apparently that's not sufficient for a Geode LX. i686 is in a weird situation where the Pentium Pro was the *first* i686 CPU, but is not a *baseline* i686 CPU.

from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973414#61

**Comment by sanxiyn** [comment] 2021-02-26 20:57
I would like to note that FreeBSD also changes baseline from pentium4 to pentiumpro: https://github.com/freebsd/freebsd-ports/blob/master/lang/rust/files/patch-compiler_rustc__target_src_spec_i686__unknown__freebsd.rs.

Ignoring Geode question for a moment, does it make sense for Rust to set i686 baseline to pentium4? Who is i686 for anyway? Wouldn't people use x86_64 for new hardwares?

**Comment by sanxiyn** [comment] 2021-02-26 21:01
I would like to note that FreeBSD also changes i686 baseline from pentium4 to pentiumpro: https://github.com/freebsd/freebsd-ports/blob/master/lang/rust/files/patch-compiler_rustc__target_src_spec_i686__unknown__freebsd.rs.

Ignoring Geode question for a moment, does it make sense for Rust to set i686 baseline to pentium4? Who is i686 for anyway? Wouldn't people use x86_64 for new hardwares?

**Comment by negge** [comment] 2021-03-01 17:17
Just ran into this with gentoo on a Pentium III today (yes in 2021):

https://bugs.gentoo.org/741708

Cross compiling your own dev-lang/rust-bin is not an option for everyone, and as more system packages like librsvg are written in Rust this cuts off more and more systems from reaping the benefit of a safe systems language.

I am one who would appreciate if i686 definition matched what distro's use.  Certainly the rust compiler can emit SSE2 instructions on those systems with these instructions present, even if it does not itself contain SSE2 instructions.

**Comment by cuviper** [comment] 2021-03-01 18:48
> I am one who would appreciate if i686 definition matched what distro's use.

There's no consensus between distros either. Fedora now builds C and C++ with `-march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign`, and that [change](https://fedoraproject.org/wiki/Changes/Update_i686_architectural_baseline_to_include_SSE2) called out the fact that i686 is primarily only used for multi-lib compatibility on x86_64 hosts. My impression is that Ubuntu is similar, but I'm not sure about that.

**Comment by sanxiyn** [comment] 2021-03-02 01:36
@cuviper linked to a change proposal accepted in Fedora 29, but that's misleading, since Fedora 31 dropped i686 install anyway: https://fedoraproject.org/wiki/Changes/Stop_Building_i686_Kernels. Of course Fedora's i686 target is solely used for multi-lib since Fedora can't be installed on i686.

**Comment by thomcc** [comment] 2021-03-02 08:48
> Ignoring Geode question for a moment, does it make sense for Rust to set i686 baseline to pentium4? Who is i686 for anyway? Wouldn't people use x86_64 for new hardwares?

Anecdotally, I've seen most use it as "32-bit x86 on more modern hardware", and the older i586 is "32-bit x86 on older hardware". I think this distinction is somewhat nice, even if it means the targets are misnamed.

Users of machines where this isn't viable might be better off with i586... But I guess that doesn't solve things for distros...

**Comment by negge** [comment] 2021-03-02 09:11
> Users of machines where this isn't viable might be better off with i586... But I guess that doesn't solve things for distros...

At least on gentoo this would help for a large set of users.

Just having a dev-lang/rust-bin that runs on the system is enough to build and install packages that require rust. This would unblock a number of users who are stuck back-porting older versions of librsvg, polkit, etc. which do not have dependencies that require rust.

But moreover, in gentoo there is a USE=system-bootstrap on the dev-lang/rust package. This means once you have a working rustc, you can build and install a bespoke i686 compiler that matches my exact i686 CPU architecture (MMX, SSE, or SSE2). This also provides an upgrade path when newer rust versions are released.

**Comment by workingjubilee** [comment] 2023-03-03 10:25
We discussed this as part of these issues:
- https://github.com/rust-lang/compiler-team/issues/543
- https://github.com/rust-lang/compiler-team/issues/548

We reviewed the evidence presented here and considered our alternatives. It was found that a _frankly ridiculous_ number of entities, including not only Fedora but _multiple_ Linux distributions, as well as **Clang**, disagree on what "i686" actually means. It is more of a "branding" than a clearly-defined, well-nailed-down feature level or target, partly due to the "i786" name never catching on like i686 did. In some cases OS, including some Linux distributions, will use "i586" or "i386" to refer to Pentium 4 feature levels!

If there was more consensus on what i686 means, it would be clear we should fix this. Even with less consensus, it might have been worth the breakage if done years ago. But now the Rust ecosystem has built heavily around this assumption, and staying in agreement on our defaults with other LLVM-based compilers is very valuable. Since the main goal is to improve support for lower-end machines, especially in the from-bootstrap case, it was decided that bumping some tier 2 i586 targets to having host tools would be preferred.

So this will, unfortunately, not be fixed.
Or, depending on your perspective, it will be fixed in another way.

**Closed by workingjubilee** 2023-03-03 10:25 UTC
Labels: O-x86, T-compiler, A-target-specs

**Comment by Fierelier** [comment] 2023-03-11 05:12
It IS clear you should fix it, because all normal compilers consider i686 as Pentium Pro. Why do they do this? If I had a Pentium Pro, I compile for i686, and then the Pentium III comes out, and I compile again, should the compile then break? OF COURSE NOT.

Do it RIGHT, and FIX it. i686 is TECHNICALLY this: https://en.wikipedia.org/wiki/P6_(microarchitecture)

Also see:
- GCC considers i686 = Pentium Pro: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
- LLVM considers i686 = Pentium Pro: https://web.archive.org/web/20221203055920/https://clang.llvm.org/doxygen/Basic_2Targets_2X86_8cpp_source.html (Archived here, since the page was down at the time of writing)

The logic of the people who want this is absolutely sound. i686 should be, and always has been Pentium Pro+.

#548
#1196
#100969

**Comment by workingjubilee** [comment] 2023-03-11 10:04
Yes, Clang does recognize "i686" **can** mean "the Pentium Pro".

However, that does not mean that the Pentium Pro defines the resulting architectural features that are actually selected when you pass the argument of `--target=i686-unknown-linux-gnu` to Clang. Please consider this Godbolt: https://llvm.godbolt.org/z/PP69efvfx

In particular, the attributes of the emitted IR, which I will indent here for better reading:
```llvm
attributes #0 = {
    noinline nounwind optnone uwtable
    "frame-pointer"="all"
    "min-legal-vector-width"="0"
    "no-trapping-math"="true"
    "stack-protector-buffer-size"="8"
    "target-cpu"="pentium4"
    "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87"
    "tune-cpu"="generic"
}
```

As seen here, Clang absolutely does pick the SSE2 feature for the i686-unknown-linux-gnu target and does pick the Pentium 4 as that target's baseline, not the Pentium Pro. So unfortunately, it seems it is not enough for logic to be sound. The LLVM toolchain simultaneously knows what is correct and also chooses to selectively disregard it. I assure you, I also find this vexing.

**Comment by Fierelier** [comment] 2023-03-13 03:06
Why does Rust override the CPU in Clang correctly for i386, i486, i586 (Which would all, as of now, otherwise reference the Pentium 4 in Clang) correctly, but not correctly for i686? See: https://github.com/llvm/llvm-project/issues/61347#issuecomment-1465430222

CPUs:
- i386 = i386: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/i386_unknown_linux_gnu.rs
- i486 = i486: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/i486_unknown_linux_gnu.rs
- i586 = pentium: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/i586_unknown_linux_gnu.rs
- i686 = pentium4: https://github.com/rust-lang/rust/blob/master/compiler/rustc_target/src/spec/i686_unknown_linux_gnu.rs

**Comment by workingjubilee** [comment] 2023-03-16 20:59
When the i686 targets were first minted, they did not:
https://github.com/rust-lang/rust/blob/6b130e3dd9547e233dca2cfd72a5968891672d9c/src/librustc_back/target/i686_unknown_linux_gnu.rs

However, when they did get adjusted, they were later specifically adjusted to match Clang:
- https://github.com/rust-lang/rust/pull/21646

This is because when the "flexible targets" were implemented, they came with explicitly setting the "generic" CPU target, which could affect even baseline features like SSE2 on x86-64 due to LLVM's peculiar interpretation of the word "generic". Thus, the overrides were added in, but overriding them to what the values were expected to be.

https://github.com/rust-lang/rust/blob/6b130e3dd9547e233dca2cfd72a5968891672d9c/src/librustc_back/target/mod.rs#L167-L172

**Comment by Fierelier** [comment] 2023-03-17 20:28
But as I already stated, Clang wrongly considers i386, i486, i586 triplets as Pentium 4, this was talked about in https://github.com/llvm/llvm-project/issues/61347#issuecomment-1465430222. Rust fixes Clang's definitions for these targets by overriding CPU. i686 does not get the same treatment.

**Comment by Fierelier** [comment] 2023-03-20 09:21
You assured me you find this vexing (admitting there is an issue), I've outlined a double standard of Rust, you've acknowledged it, yet you lack any initiative to want to set it right. If you are the position of the entire Rust team, then I really hope gcc's Rust compiler catches up soon.

**Comment by jayaddison** [comment] 2023-03-29 12:43
I feel like I'm at some slight risk of losing my sanity (not entirely related to i686), and despite that I would like to register my alignment with @Fierelier on this topic, even if it's a losing battle.

There seems to be momentum in both LLVM and Rust to increment the definition of i686 beyond what it originally referred to -- and in parallel, there are inbound efforts by Intel to improve the apparent security properties of both x86 and x86-64 architectures, some of which leverages (at baseline) an instruction from the "incremented" definitions of i686.

_Maybe_ that's worthwhile overall in terms of user safety -- if said safety measures do indeed prove worthwhile and reliable.

But there's another risk, which is a more pernicious and long-lasting one: if we begin to lose clear definitions of what architectures and instruction sets refer to, then it begins to require increasing levels of effort and research to understand what someone is talking about when they refer to an architecture.

_This is already true of computing in general_ - we add additional layers, iterate on technologies and rename things or repurpose names.  And to some extent we can use the layers and technological improvements themselves to help us forget details.  But the details are still there, and they do become relevant sometimes.

That's my attempt to restate and agree with the '[problem may accumulates over time](https://github.com/llvm/llvm-project/issues/61347#issuecomment-1465461823)' message echoed over on a similar LLVM thread.

I'm still not even entirely sure whether I really understand what's going on here: but that's precisely part of the problem.
