### ISSUE TITLE
`RUSTFLAGS` on Alpine

### ISSUE THREAD

**Issue by mo8it** [rust-lang/rust#127498] opened 2024-07-08 22:52 UTC
Compiling with `cargo` and `RUSTFLAGS` fails on Alpine.

Here is how to reproduce it:

```bash
# Docker
docker run -it --rm rust:alpine sh -c "cargo new foo && cd foo && RUSTFLAGS='-A warnings' cargo r"

# Podman
podman run -it --rm docker.io/library/rust:alpine sh -c "cargo new foo && cd foo && RUSTFLAGS='-A warnings' cargo r"
```

Note that the command works if you remove the RUSTFLAGS environment variable.

<details>
<summary>Output</summary>

```
error: output of --print=file-names missing when learning about target-specific information from rustc
command was: `/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-musl/bin/rustc - --crate-name ___ --print=file-names -A warnings --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg`
                                                                                                                                                                          
--- stdout
___
lib___.rlib
lib___.a
lib___.so
/usr/local/rustup/toolchains/1.79.0-x86_64-unknown-linux-musl
off
packed
unpacked
___
debug_assertions
panic="unwind"
proc_macro
target_abi=""
target_arch="x86_64"
target_endian="little"
target_env="musl"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```
</details>

This seems like an argument parsing problem to me.

The background is the following Rustlings issue: https://github.com/rust-lang/rustlings/issues/2036

**Comment by ehuss** [comment] 2024-07-09 01:06
Thanks for the report! I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/8010, so closing in favor of that.

**Closed by ehuss** 2024-07-09 01:06 UTC
Labels: needs-triage
