### ISSUE TITLE
io::Take's BufRead::fill_buf always attempts to fill the inner buffer

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#27463] opened 2015-08-02 03:35 UTC
Even if self.limit is 0, fill_buf will attempt to read from the underlying BufRead, possibly causing additional blocking read(2) calls from split/read_until/etc:

```
use std::os::unix::io::FromRawFd;
use std::fs::File;
use std::io::BufReader;
use std::io::BufRead;
use std::io::Write;
use std::io::Read;

extern "C" {
    pub fn pipe(fds: *mut i32) -> i32;
}

fn main() {
    let (reader, mut writer) = unsafe { 
        let mut pipes = [0, 0];
        assert_eq!(pipe(pipes.as_mut_ptr()), 0); 
        (File::from_raw_fd(pipes[0]), File::from_raw_fd(pipes[1]))
    };
    writer.write(&[1, 0]);
    writer.flush();
    let reader = BufReader::new(reader);
    println!("{:?}", reader.take(2).split(0).collect::<Result<Vec<_>, _>>());
}
```
Will block forever, while writing an additional byte that should never need to be read will succeed. (Similarly no writing and take(0) also fails when it should not).

An early check for self.limit == 0 in Take's fill_buf, like its read() implementation, should fix this.

**Comment by alexcrichton** [comment] 2015-08-03 17:13
This is actually working as intended, it looks like you've got the limiting on the wrong side of the buffering. Conceptually you're currently taking 2 bytes out of a buffered reader, but the buffered reader is free to read more itself. What you'll want to do is probably take the two bytes and then put that into the buffered reader to ensure that you can't read more than that many bytes in the buffer itself.

The check for `self.limit` being 0 in the `fill_buf` is possible, but isn't required for correctness, so I'm going to close this as working as intended. Feel free to file a PR for the small modification though!

**Closed by alexcrichton** 2015-08-03 17:13 UTC

**Comment by talchas** [comment] 2015-08-04 00:16
Conceptually though this seems like the obvious construction - making separate BufReaders for each take call seems extremely backwards. Also take(0) behaving differently on BufReader from Read (even if only on BufRead methods) seems weird.
