### ISSUE TITLE
f32::NAN as i128 different between miri and LLVM

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#65245] opened 2019-10-09 18:46 UTC
```
fn main() {
    let f = std::f32::NAN;
    assert_eq!(f as i128, 0x7fffffffffffffffffffffffffffffffi128); // LLVM
    assert_eq!(std::f32::NAN as i128, 0i128); // miri
}
```

**Comment by ollie27** [comment] 2019-10-09 18:56
Duplicate of #10184

**Closed by ollie27** 2019-10-09 18:56 UTC

**Comment by bjorn3** [comment] 2019-10-09 19:00
It doesn't seem like the LLVM case is caused by UB, as the compiler-builtins intrinsic returns `0x7fffffffffffffffffffffffffffffffi128` too.

**Comment by ollie27** [comment] 2019-10-09 20:16
Well it definitely is UB. I don't think it's really defined anywhere what the compiler-builtins intrinsic should return in this case so what it returns doesn't really mean anything.

**Comment by bjorn3** [comment] 2019-10-09 20:54
In that case the saturating-float-casts test shouldnt test for a specific value being returned.

**Comment by ollie27** [comment] 2019-10-09 21:45
That test needs to be compiled with `-Z saturating-float-casts`: https://github.com/rust-lang/rust/blob/c798dffac9dc8c82374db48f5b474690cc6e9686/src/test/ui/numbers-arithmetic/saturating-float-casts.rs#L3

See #10184 for more information.
