### ISSUE TITLE
Unexpected panic when exporting an item of renamed proc-macro dependency with select targets.

### ISSUE THREAD

**Issue by N3xed** [rust-lang/rust#79020] opened 2020-11-13 16:02 UTC
I get an internal compiler error (unexpected panic) when I export an item of an (in `Cargo.toml`) renamed proc-macro library dependency. This only happens with select targets and only on stable and nightly. It still fails to compile on beta, but with a different error (see Error output section).

I've tested the following targets which all have this bug (on stable, beta (different as described) and nightly):
 - `thumbv6m-none-eabi`  
    command `cargo +nightly/beta/stable build --target thumbv6m-none-eabi`
 - `thumbv7em-none-eabi`  
    command `cargo +nightly/beta/stable build --target thumbv6m-none-eabi`
 - `thumbv7em-none-eabihf`  
    command `cargo +nightly/beta/stable build --target thumbv7em-none-eabihf`
 - `thumbv7m-none-eabi`  
    command `cargo +nightly/beta/stable build --target thumbv7m-none-eabi`

It compiles fine with target `x86_64-pc-windows-msvc`.

### Code

[https://github.com/N3xed/rustc-proc-macros-dep-rename-bug](https://github.com/N3xed/rustc-proc-macros-dep-rename-bug)

### Meta

`rustc --version --verbose`:
#### Stable
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-pc-windows-msvc
release: 1.47.0
LLVM version: 11.0
```

<details><summary><strong>Beta</strong></summary>
<p>

```
rustc 1.48.0-beta.8 (121901459 2020-11-08)
binary: rustc
commit-hash: 1219014599fd873fcb640b675d8a662150c74e40
commit-date: 2020-11-08
host: x86_64-pc-windows-msvc
release: 1.48.0-beta.8
LLVM version: 11.0
```

</p></details>

<details><summary><strong>Nightly</strong></summary>
<p>

```
rustc 1.49.0-nightly (9722952f0 2020-11-12)
binary: rustc
commit-hash: 9722952f0bed5815cb22cb4878be09fb39f92804
commit-date: 2020-11-12
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
```

</p></details>

### Error output

For `stable` and `nightly`:
```
thread 'rustc' panicked at 'src\librustc_resolve\imports.rs:907:25: inconsistent resolution for an import', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\src\librustc_middle\util\bug.rs:34:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0 (18bf6b4f0 2020-10-07) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rustc-dep-rename-bug`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_dep_rename_bug --edition=2018 'src\lib.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=184209647542cd98 -C extra-filename=-184209647542cd98 --out-dir 'F:\proj\rustc-dep-rename-bug\target\thumbv7em-none-eabihf\debug\deps' --target thumbv7em-none-eabihf -C 'incremental=F:\proj\rustc-dep-rename-bug\target\thumbv7em-none-eabihf\debug\incremental' -L 'dependency=F:\proj\rustc-dep-rename-bug\target\thumbv7em-none-eabihf\debug\deps' -L 'dependency=F:\proj\rustc-dep-rename-bug\target\debug\deps' --extern 'inner=F:\proj\rustc-dep-rename-bug\target\debug\deps\inner_crate-b0ffcafb96ec16ac.dll'` (exit code: 101)
```

For `beta`:
```
error: inconsistent resolution for an import
 --> src\lib.rs:4:9
  |
4 | pub use inner::*;
  |         ^^^^^^^^

error: aborting due to previous error

error: could not compile `rustc-dep-rename-bug`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

Note: This is the backtrace with `RUST_BACKTRACE=full` because the backtrace with `RUST_BACKTRACE=1` was empty.
```
stack backtrace:
   0:     0x7ff906509f69 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4619ab1e0e7f537e
   1:     0x7ff906536f7b - core::fmt::write::h84ceeb961f15abff
   2:     0x7ff9064fbae4 - <std::io::IoSlice as core::fmt::Debug>::fmt::h9d23b0cc8f33253b
   3:     0x7ff90650f5cb - std::panicking::take_hook::h7242e84e70bd80e5
   4:     0x7ff90650f209 - std::panicking::take_hook::h7242e84e70bd80e5
   5:     0x7ff8ff2ebd4a - rustc_driver::report_ice::h7d9caf57ab1969dd
   6:     0x7ff90650ff60 - std::panicking::rust_panic_with_hook::hf4a559ff56f2af2e
   7:     0x7ff901cea348 - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
   8:     0x7ff901cea09f - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
   9:     0x7ff901d04636 - <rustc_session::config::SanitizerSet as core::fmt::UpperHex>::fmt::hdcb44dd35d63475d
  10:     0x7ff901ce0a93 - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
  11:     0x7ff901ce0941 - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
  12:     0x7ff901ce08a3 - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
  13:     0x7ff901ce09ec - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
  14:     0x7ff901ce09a5 - <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_ty::h7f22dfa4b757f3a7
  15:     0x7ff901dcf1c2 - rustc_resolve::imports::ImportResolver::finalize_imports::h78444ceb2da1444a
  16:     0x7ff901dcc478 - rustc_resolve::imports::ImportResolver::finalize_imports::h78444ceb2da1444a
  17:     0x7ff901d70f2d - rustc_resolve::Resolver::resolve_crate::hd2ff456bde7ce3ae
  18:     0x7ff8ff5de608 - rustc_interface::passes::BoxedResolver::to_resolver_outputs::hc2b95e96c6a88100
  19:     0x7ff8ff5b9677 - rustc_interface::interface::parse_cfgspecs::hf6674ffb8d3b457b
  20:     0x7ff8ff5a3f16 - <rustc_interface::util::ReplaceBodyWithLoop as rustc_ast::mut_visit::MutVisitor>::visit_mac::h7f03029727239706
  21:     0x7ff8ff5dcc77 - rustc_interface::interface::parse_cfgspecs::hf6674ffb8d3b457b
  22:     0x7ff8ff602d28 - rustc_interface::queries::Queries::expansion::h22ef0bc36e8f7ef3
  23:     0x7ff8ff30ae7b - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h7f567a06a647f4b8
  24:     0x7ff8ff2a2b8c - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h28b34d043f942f5d
  25:     0x7ff8ff30c88b - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h7f567a06a647f4b8
  26:     0x7ff8ff2f9c90 - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h7f567a06a647f4b8
  27:     0x7ff8ff30046f - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h7f567a06a647f4b8
  28:     0x7ff8ff29b5c3 - <rustc_middle::ty::SymbolName as core::fmt::Debug>::fmt::h6e3d1b05eaab99a2
  29:     0x7ff90651fcca - std::sys::windows::thread::Thread::new::hffe67e116ae8824f
  30:     0x7ff95c707034 - BaseThreadInitThunk
  31:     0x7ff95c83cec1 - RtlUserThreadStart
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-11-13 16:37
Duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2020-11-13 16:37 UTC
Labels: C-bug, I-ICE, T-compiler
