### ISSUE TITLE
Can't compile a file named "rust.rs" on Linux

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#35887] opened 2016-08-22 01:06 UTC
It is not possible to compile a file whose name is equal to a directory already created in the same folder:

```
$ rustc rust.rs
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "rust.0.o" "-o" "rust" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-39b92f95.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-39b92f95.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
note: /usr/bin/ld: cannot open output file rust: Is a directory
collect2: error: ld returned 1 exit status

error: aborting due to previous error
```

**Comment by durka** [comment] 2016-08-22 01:32
Not really a rust bug.

    $ mkdir foo
    $ echo "int main() { return 0; }" >foo.cpp
    $ g++ foo.cpp -o foo
    ld: can't open output file for writing: foo, errno=21 for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by c410-f3r** [comment] 2016-08-22 01:59
@durka Guess it is not a bug after all

**Comment by retep998** [comment] 2016-08-22 03:42
You cannot have both a file and a directory with the exact same name in the same directory.

**Comment by dashed** [comment] 2016-08-22 07:07
There could be a nicer error message to indicate to the user that there is a directory with the same name as the program.

**Comment by 0xmohit** [comment] 2016-08-22 14:17
FWIW, `gcc` behaves similarly.

``` sh
$ ls 
$ echo "int main() { return 0; }" > a.c
$ mkdir a.out
$ ls
a.c  a.out
$ gcc a.c
/usr/bin/ld: cannot open output file a.out: Is a directory
collect2: error: ld returned 1 exit status
$ 
```

**Comment by estebank** [comment] 2016-08-22 22:06
I could expand https://github.com/rust-lang/rust/pull/34005 when I get back to it to clean it up to pick this case up as well.

**Comment by alexcrichton** [comment] 2016-09-13 16:27
Ah yes I think this is "not a bug" where we can't create executables with a directory of the same name, so closing.

**Closed by alexcrichton** 2016-09-13 16:27 UTC

**Comment by varkor** [comment] 2018-01-30 22:57
Just to note: this is a duplicate of https://github.com/rust-lang/rust/issues/13098.
