### ISSUE TITLE
Segmentation fault on safe test panic

### ISSUE THREAD

**Issue by wthrowe** [rust-lang/rust#26298] opened 2015-06-14 19:08 UTC
This is as minimal an example as I've been able to reduce this to so far:
```rust
fn f(_: Vec<u32>, _: &Vec<u32>) {
    panic!();
}

fn identity(r: &Vec<u32>) -> &Vec<u32> { r }

#[test]
fn t() {
    f(vec![0], identity(&Vec::new()));
}
```

```
$ rustc --version
rustc 1.0.0 (built 2015-05-22)
$ rustc --test foo.rs
$ ./foo 

running 1 test
Segmentation fault
$ 
```

**Comment by sfackler** [comment] 2015-06-14 23:47
Looks like heap corruption. Valgrind output and backtrace: https://gist.github.com/sfackler/4ecc56dc1324ae07a2ce

Nominating.

**Comment by alexcrichton** [comment] 2015-06-15 05:02
Confirmed dupe of https://github.com/rust-lang/rust/issues/25089 (fixed by https://github.com/rust-lang/rust/pull/26062)

**Closed by alexcrichton** 2015-06-15 05:02 UTC
Labels: I-crash, I-nominated
