### ISSUE TITLE
Thread panic message to stderr kills windowed mode Windows binaries

### ISSUE THREAD

**Issue by rsaarelm** [rust-lang/rust#25643] opened 2015-05-20 08:32 UTC
Windows binaries built with the `-mwindows` linker flag can't have any output to stdout or stderr in them or Windows will instantly terminate the program. I want to have windowed mode binaries for GUI applications, since without the windowed mode flag the binary will spawn a visible console window in addition to the GUI window every time it's run.

Panicing threads seem to cause an unconditional print to stderr. I'm trying to write a panic handler that will pop up a Windows message dialog instead of printing to stdout when the program terminates with a panic, but currently can't do that because windowed mode programs die at the point of the panic and the handler is never reached.

To test this, write `panic.rs`:

```rust
fn f() { panic!("This kills the Windows"); }

fn main() {
    match std::thread::Builder::new().spawn(f).unwrap().join() {
        Err(_) => { std::fs::File::create("panic_log.txt"); }
        _ => {}
    }
}
```

Build it with `rustc -C link-args=-mwindows panic.rs`. Then run `panic.exe` *from the Windows explorer*. The program terminates and the `panic_log.txt` file never shows up. (It does seem to work if you run it from the Command Prompt, but end users will be clicking an icon.)

**Comment by nagisa** [comment] 2015-05-20 08:42
https://github.com/rust-lang/rust/issues/24099

**Comment by Diggsey** [comment] 2015-05-21 02:33
rust-lang/rfcs#1100

**Comment by retep998** [comment] 2015-05-23 15:22
https://github.com/rust-lang/rfcs/pull/1014

**Comment by alexcrichton** [comment] 2015-05-26 17:30
The linked issues by @nagisa, @Diggsey, and @retep998 I believe all cover our bases pretty well here, so I'm going to close this as a dupe of them. Thanks regardless for the report though!

**Closed by alexcrichton** 2015-05-26 17:30 UTC
Labels: A-windows
