### ISSUE TITLE
Most macro fragment specifiers cannot be re-parsed by consuming macros

### ISSUE THREAD

**Issue by Osspial** [rust-lang/rust#41472] opened 2017-04-22 20:34 UTC
With the exception of metavariables with `ident` and `tt` fragment specifiers, a macro that passes a metavariable into another macro which contains the raw tokens specified by that metavariable in the matcher will throw a `` no rules expected the token `{tokens}` `` error, despite the raw tokens matching up.

The code in this gist should all compile, but doesn't with the given error messages: https://gist.github.com/Osspial/d0eb4827d764aa40912bface538dd0ea

## Meta
```
> rustc --version --verbose
rustc 1.16.0 (30cf806ef 2017-03-10)
binary: rustc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-pc-windows-gnu
release: 1.16.0
LLVM version: 3.9
```

**Comment by jethrogb** [comment] 2018-12-27 13:03
I think this is the same issue?

```
macro_rules! m {
    ( a $(@$meta:meta)* ) => {
        m! ( b $(@$meta)* );
    };
    ( b @ meta ) => { "ok" };
    ( b ) => { "ok" };
}

fn main() {
    println!("{}", m!(a @meta));
    println!("{}", m!(a));
}
```

Why is this marked as C-enhancement? Should be C-bug

**Comment by jethrogb** [comment] 2018-12-27 13:19
Related #25875

**Comment by dtolnay** [comment] 2018-12-27 16:19
I believe this is by design to avoid parsing and re-parsing the same syntax tree nodes many times during recursive macro expansion. Most macro_rules matchers (everything other than \$:ident, \$:lifetime, \$:tt) become atomic opaque bundles when matched, and subsequent rules cannot inspect inside of them.

The bundling into an opaque atomic token is observable if you match one of those metavariables against \$:tt.

```rust
macro_rules! m {
    ($tt:tt) => {
        println!("it is a single token");
    };
}

macro_rules! n {
    ($meta:meta) => {
        m!($meta);
    };
}

fn main() {
    n!(recursion_limit = "128");
}
```

I am closing this issue because I believe changing the current behavior would require an RFC that addresses performance implications and backward compatibility implications.

**Closed by dtolnay** 2018-12-27 16:19 UTC
Labels: A-macros, C-feature-request
