### ISSUE TITLE
Type::AssociatedType::AssociatedType doesn't resolve

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#22138] opened 2015-02-10 11:09 UTC
```rust
trait Foo {
    type X;
}
trait Bar {
    type Y;
}

fn foo<T>(_: T::X::Y) 
    where T: Foo,
          T::X: Bar,
{}
```

```
<anon>:8:14: 8:21 error: failed to resolve. Use of undeclared type or module `T::X`
<anon>:8 fn foo<T>(_: T::X::Y) 
                      ^~~~~~~
<anon>:8:14: 8:21 error: use of undeclared type name `T::X::Y`
<anon>:8 fn foo<T>(_: T::X::Y) 
                      ^~~~~~~
```

**Comment by alexcrichton** [comment] 2015-02-10 16:33
I think this is a dupe of #20300 (not using `as` seems to be blocked on that bug)

**Closed by alexcrichton** 2015-02-10 16:33 UTC
Labels: A-associated-items
