### ISSUE TITLE
private_in_public warning for private methods

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#40844] opened 2017-03-26 20:34 UTC
The private in public warning triggers even for impl blocks that have no public methods. See code below to reproduce.

```rust
#![crate_type="lib"]

trait PrivateTrait {
}

pub struct Foo<T>(T);

impl<T: PrivateTrait> Foo<T> {
    fn new() -> Self {
        panic!()
    }
}
```

warning:

```rust
rustc 1.17.0-nightly (49c67bd63 2017-03-24)
warning: private trait `PrivateTrait` in public interface (error E0445)
  --> <anon>:8:1
   |
8  |   impl<T: PrivateTrait> Foo<T> {
   |  _^ starting here...
9  | |     fn new() -> Self {
10 | |         panic!()
11 | |     }
12 | | }
   | |_^ ...ending here
   |
   = note: #[warn(private_in_public)] on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
```

cc @petrochenkov, you probably know if this is as designed or not

**Comment by petrochenkov** [comment] 2017-03-26 21:56
@bluss 
`impl Foo<T>` is a public impl (because `Foo` is `pub` and `T` is... anything) so `PrivateTrait` can't be used in it's interface (see https://github.com/rust-lang/rfcs/pull/1671#r70170231 for the reason why).
So, this currently works as intended, but hopefully not for long - prohibiting private traits in bounds is the most unnecessary part of the private-in-public checker because https://github.com/rust-lang/rfcs/pull/1671#r70170231 has an alternative solution - https://github.com/rust-lang/rfcs/pull/1671#r70170548.
I hope to finish https://internals.rust-lang.org/t/lang-team-minutes-private-in-public-rules/4504/47 until the next weekend, and after that various private-in-public restrictions can be relaxed.

**Comment by petrochenkov** [comment] 2017-10-02 14:05
I'll close this since it works as expected with current rules.
See https://github.com/rust-lang/rfcs/pull/2145 for the proposed solution.

**Closed by petrochenkov** 2017-10-02 14:05 UTC
Labels: A-visibility, C-bug
