### ISSUE TITLE
Match checking doesn't handle static constants correctly.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#12501] opened 2014-02-23 19:40 UTC
I would guess it doesn't go (properly) through const eval, causing weird errors like this one:
```rust
static MAX: uint = -1;
match 0 {
    1u..MAX => {}, // error: mismatched types in range
    _ => {}
}
```
If the value of `MAX` is changed to `-1u`, the code compiles, showing that match checking looks at the value of the `static MAX` but not at its type or computed value.

Further experimentation - using `-1 as uint` for `MAX` - produces this ICE:
```rust
error: internal compiler error: node_id_to_type: no type for node `expr -1 as uint (id=26)`
```

**Comment by pnkfelix** [comment] 2015-03-31 17:21
cc #23897

**Comment by pnkfelix** [comment] 2015-04-19 02:05
@eddyb I cannot reproduce the issue now; i.e. when I try (e.g. by plugging in mismatched types for the initializer, and also experimenting with using `const` vs `static` to see if that tickles something), I seem to consistently get a type check error.

can you make another example at this point demonstrating the issue here?

**Comment by pnkfelix** [comment] 2015-04-19 02:06
e.g. here is one version of updated code, but it compiles and runs:

```rust
#![feature(negate_unsigned)]

fn main() {
    const MAX: usize = -1;
    match 0 {
        1usize...MAX => {}, // error: mismatched types in range
        _ => {}
    }
}
```

**Comment by eddyb** [comment] 2015-04-19 05:58
@pnkfelix it must have been fixed by adding more type information to const_eval, I guess.

**Comment by pnkfelix** [comment] 2015-04-19 06:54
closing, assumed fixed

**Closed by pnkfelix** 2015-04-19 06:54 UTC
Labels: A-typesystem
