### ISSUE TITLE
os error 45 on macOS 10.13.4

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#55733] opened 2018-11-06 21:11 UTC
I was just trying to use cargo as per the instructions here:

https://doc.rust-lang.org/book/2018-edition/ch01-03-hello-cargo.html#creating-a-project-with-cargo

and the compiler panicked. This user does not have sudo access, and compiling directly with `rustc` works perfectly.

I tried this code:

`fn main() {
    println!("Hello, world!");
}`

I expected to see this happen:

Successful compilation.

Instead, this happened:

```
error: incremental compilation: could not create session directory lock file: Operation not supported (os error 45)

thread 'main' panicked at 'librustc/session/mod.rs:802: Trying to get session directory from IncrCompSession `NotInitialized`', librustc/util/bug.rs:47:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `hello_cargo`.

```
## Meta

`rustc 1.30.0 (da5f414c2 2018-10-24)
binary: rustc
commit-hash: da5f414c2c0bfe5198934493f04c676e2b23ff2e
commit-date: 2018-10-24
host: x86_64-apple-darwin
release: 1.30.0
LLVM version: 8.0`

Backtrace:

```
Compiling hello_cargo v0.1.0 (/nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo)
     Running `rustc --crate-name hello_cargo src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=8ff1e17b8b58b3f4 -C extra-filename=-8ff1e17b8b58b3f4 --out-dir /nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo/target/debug/deps -C incremental=/nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo/target/debug/incremental -L dependency=/nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo/target/debug/deps`
error: incremental compilation: could not create session directory lock file: Operation not supported (os error 45)

thread 'main' panicked at 'librustc/session/mod.rs:802: Trying to get session directory from IncrCompSession `NotInitialized`', librustc/util/bug.rs:47:26
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `hello_cargo`.

Caused by:
  process didn't exit successfully: `rustc --crate-name hello_cargo src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=8ff1e17b8b58b3f4 -C extra-filename=-8ff1e17b8b58b3f4 --out-dir /nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo/target/debug/deps -C incremental=/nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo/target/debug/incremental -L dependency=/nfs/2018/a/arherrer/projects/rustlang-book/hello_cargo/target/debug/deps` (exit code: 101)
```

**Comment by Enselic** [comment] 2023-08-22 15:07
Triage: In #49773 it is discussed to make rustc more resilient towards lack of support for file locks on some file systems. Closing this as a duplicate of #49773.

**Closed by Enselic** 2023-08-22 15:07 UTC
Labels: O-macos, I-ICE, T-compiler, A-incr-comp, C-bug
