### ISSUE TITLE
Fix incorrect use of MaybeUninit::assume_init_mut in flt2dec

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#76092] opened 2020-08-30 01:23 UTC
Creating this issue to track this [FIXME note in float formatting](https://github.com/rust-lang/rust/blob/5e208efaa850efaa97495e81c49cf0f5767e8f49/library/core/src/fmt/float.rs#L21):

> This is calling `get_mut` on an uninitialized
         `MaybeUninit` (here and elsewhere in this file). Revisit this once
         we decided whether that is valid or not.
         We can do this only because we are libstd and coupled to the compiler.
         (FWIW, using `freeze` would not be enough; `flt2dec::Part` is an enum!)

The issue being mentioned when the fixme was closed without addressing this concern, and the new tracking issue doesn't raise it, so created this so that we can discuss it here and link it to the tracking issue 

cc @RalfJung

**Comment by RalfJung** [comment] 2020-08-30 07:13
Besides the float code, there's also the `Read` code doing something similar for allowing reads into uninitialized buffers. However, https://github.com/rust-lang/rfcs/pull/2930 should resolve that I think.

**Comment by danielhenrymantilla** [comment] 2020-08-30 09:29
Could we rename it to _validity of `.assume_init_mut()` on uninitialized `float`(s)_? or or _`&mut` on uninitialized floats_?

___

Regarding the issue at hand, obviously only `libstd` and other internal crates can rely on the internals of the `rustc` it is released with, so technically, we could go ahead with #76047 and "ignore" the FIXME, as long as we have this issue to remind us of fixing that.

Doing so is not that bad as when I attempted to tackle #66174, since by now we have initiatives such as the one I suggested there [having been implemented in a library crate](https://docs.rs/uninit/0.3.0/uninit/read/trait.ReadIntoUninit.html), using [a library version of out references](https://docs.rs/uninit/0.3.0/uninit/out_ref/struct.Out.html), and we also have the aforementioned RFC getting some progress. So this time, letting the FIXME without fixing it yet is not just a "useless procrastination of the problem", it is a meaningful "wait for the required language feature", I'd say 🙂

**Comment by RalfJung** [comment] 2020-08-30 09:55
The issue is not really specific to floats, it is tight to whether references are allowed to refer to uninitialized data.

So this is basically the rustc side of (a part of) https://github.com/rust-lang/unsafe-code-guidelines/issues/77.

**Comment by RalfJung** [comment] 2020-08-30 09:56
> So this time, letting the FIXME without fixing it yet is not just a "useless procrastination of the problem", it is a meaningful "wait for the required language feature", I'd say slightly_smiling_face

Agreed for the `Read` side. For the float usage, really that code should be converted to raw pointers.

**Comment by RalfJung** [comment] 2020-09-02 10:32
Actually, let's use https://github.com/rust-lang/rust/issues/42788 for the `Read` part (there's another FIXME in the code referencing that already).

This is just for flt2dec, and will be fixed by https://github.com/rust-lang/rust/pull/76241.

**Closed** 2020-09-02 17:35 UTC
Labels: C-bug, libs-impl
