### ISSUE TITLE
ICE during build of `curve25519-dalek` - index out of bounds

### ISSUE THREAD

**Issue by maxfunke** [rust-lang/rust#121139] opened 2024-02-15 11:13 UTC
### Meta
```
rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-pc-windows-msvc
```

### Error output

```log
thread 'rustc' panicked at compiler\rustc_metadata\src\rmeta\decoder.rs:962:10:
index out of bounds: the len is 0 but the index is 0

note: rustc 1.75.0 (82e1608df 2023-12-21) running on x86_64-pc-windows-msvc
note: compiler flags: --crate-type rlib -C opt-level=3 -C embed-bitcode=no
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [resolver_for_lowering] getting the resolver for lowering
end of query stack
   Compiling darling_core v0.20.3
error: could not compile `curve25519-dalek` (lib)
```

The error is not reproducable though.

**Comment by saethlin** [comment] 2024-03-09 17:25
I suspect this is another out-of-disk crash, that should hopefully be fixed by all my PRs, the last of which ships in 1.77. It's definitely not an incremental compilation issue.

**Comment by saethlin** [comment] 2024-03-27 13:50
I think the root cause of this issue was rustc incorrectly handling/reporting I/O errors. I've landed a number of PRs to address the problem; the most recent of those is https://github.com/rust-lang/rust/pull/119510 which is now part of the latest stable toolchain, 1.77. Therefore, even though I have not reproduced exactly what you've reported here, I'm going to close this because I am reasonably confident that this bug is now fixed on stable.

Of course it is possible that I am wrong and the bug you've reported here is not fixed. If you happen to run into problems like this in 1.77 or later please do not hesitate to open a new issue.

**Closed by saethlin** 2024-03-27 13:50 UTC
Labels: I-ICE, T-compiler, C-bug, S-needs-repro
