### ISSUE TITLE
`impl Trait` in return type does not compile if function returns `panic!()` / `todo!()` / `unimplemented!()`

### ISSUE THREAD

**Issue by UditDey** [rust-lang/rust#102410] opened 2022-09-28 14:31 UTC
The following code fails to compile:

```rust
trait Trait {}

struct Struct;

impl Trait for Struct {}

fn example() -> impl Trait {
    panic!()
}
```
```
error[E0277]: the trait bound `(): Trait` is not satisfied
 --> src/main.rs:7:17
  |
7 | fn example() -> impl Trait {
  |                 ^^^^^^^^^^ the trait `Trait` is not implemented for `()`
  |
  = help: the trait `Trait` is implemented for `Struct`
```

However, replacing the `impl Trait` with the regular generics syntax compiles fine:
```rust
fn example<T: Trait>() -> T {
    panic!()
}
```

This happens only if there is a single path in the function terminating in a `panic!()`. The following compiles fine too:
```rust
fn example(b: bool) -> impl Trait {
    if b {
        Struct {}
    }
    else {
        panic!()
    }
}
```

This also happens with `todo!()` and `unimplemented!()` since those macros are also basically just `panic!()`s.

If my understanding is correct, `impl Trait` and `<T: Trait>` should behave identically, but clearly they don't and the typecheck fails in the `impl Trait` version. This means that, for example, using `todo!()` in place of unfinished code is not possible in a function returning `impl Trait`.

This occurs on 1.64.0 stable as well as nightly

**Comment by UditDey** [comment] 2022-09-28 15:32
The same behavior can be seen with `!`. With `impl Trait` this does not compile, but replacing it with `<T: Trait>` works fine:
```rust
trait Trait {}

struct Struct;

impl Trait for Struct {}

fn never_return() -> ! {
    loop {}
}

fn example() -> impl Trait {
    never_return()
}
```

In fact, the error message seems to be incorrect as well:
```
error[E0277]: the trait bound `(): Trait` is not satisfied
  --> src/main.rs:11:17
   |
11 | fn example() -> impl Trait {
   |                 ^^^^^^^^^^ the trait `Trait` is not implemented for `()`
   |
   = help: the trait `Trait` is implemented for `Struct`

```

Shouldn't it be `trait bound '!: Trait' is not satisfied`? If the return type of `panic!()` is taken as `!` then this is where the problem stems from

**Comment by memoryruins** [comment] 2022-10-07 17:15
Duplicate of #36375

**Comment by thomcc** [comment] 2022-12-14 19:27
Closed as a duplicate.

**Closed by thomcc** 2022-12-14 19:27 UTC
Labels: C-bug
