### ISSUE TITLE
Async await mulitple lifetimes issue with `Box`

### ISSUE THREAD

**Issue by 95th** [rust-lang/rust#68759] opened 2020-02-02 05:03 UTC
Following code is not accepted ATM ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d7c4f1f4abd479080634d6b5e3bf08af)):

```rust
pub trait A {}

pub struct B {
    a: Box<dyn A>,
}

impl B {
    pub async fn new(a: Box<dyn A>, x: &(), y: &()) -> B {
        B { a }
    }
}
```
Error:

```rust
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> src/main.rs:10:56
   |
10 |     pub async fn new(a: Box<dyn A>, x: &(), y: &()) -> B {
   |                                                        ^
   |
note: hidden type `impl std::future::Future` captures the scope of call-site for function at 10:58
  --> src/main.rs:10:58
   |
10 |       pub async fn new(a: Box<dyn A>, x: &(), y: &()) -> B {
   |  __________________________________________________________^
11 | |         B { a }
12 | |     }
   | |_____^

```

However, the following code is accepted:

```rust
pub trait A {}

pub struct B<A> {
    a: A,
}

impl<X: A> B<X> {
    pub async fn new(a: X, x: &(), y: &()) -> B<X> {
        B { a }
    }
}
```

I know one can workaround this by using `impl trait` with explicit lifetimes, but this is an ergonomics issue.

**Comment by 95th** [comment] 2020-02-02 08:02
Note that non-async version of `Box` works:

```rust
pub trait A {}

pub struct B {
    a: Box<dyn A>,
}

impl B {
    pub fn new(a: Box<dyn A>, x: &(), y: &()) -> B {
        B { a }
    }
}
```

**Comment by tmandry** [comment] 2020-03-03 05:16
This looks like a duplicate of #68950 (which may have the same cause as #64552)

**Comment by tmandry** [comment] 2020-03-03 05:21
Closing as a duplicate of #64552, but noting on that issue that we should add a test with the code from this issue.

**Closed by tmandry** 2020-03-03 05:21 UTC
Labels: A-async-await, AsyncAwait-OnDeck, AsyncAwait-Triaged, C-feature-request, T-lang
