### ISSUE TITLE
Casting a function reference to a pointer producing an invalid pointer (0x1)

### ISSUE THREAD

**Issue by mgoszcz2** [rust-lang/rust#65499] opened 2019-10-17 13:33 UTC
Ran on stable 1.38.0 this prints the function pointer, but beta (1.39.0-beta.6) and nightly return '1'. ([Playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=124b7286b987a31eaf882c1efdf06fab))

Can't say I understand why this is happening but I've been [told](https://stackoverflow.com/questions/58416511/casting-a-function-reference-producing-an-invalid-pointer) it might be worth reporting anyway. I'm interested in finding out why this happens.

```rust
use libc::c_void;

pub unsafe fn foo() {}

fn main() {
    let ptr = &foo as *const _ as *const c_void;
    println!("{:x}", ptr as usize);
}
```

**Comment by jonas-schievink** [comment] 2019-10-17 13:39
If the println is replaced with this:

```rust
println!("0x{:x} {:p}", ptrp as usize, foo as unsafe fn());
```

On 1.38.0 it prints two different addresses:

```
0x55a31b0f9380 0x55a31b0d73c0
```

so I don't think the previous result was actually the function pointer.

I'd have expected it to print `0x1` is any case, since `foo` is a zero-sized type.

**Comment by Mark-Simulacrum** [comment] 2019-10-17 13:48
Bisection shows https://github.com/rust-lang/rust/commit/ea52be482ab4945fda63cb65b6a198309a041e3c as the origin of this which makes some sense -- we stopped putting zero-sized types at a specific address and instead return `0x1` (minimum aligned ptr).

I believe this is an intentional change, so I think we'll likely close, but let's mark as regression for compiler team to confirm.

**Comment by nagisa** [comment] 2019-10-17 17:19
Given that we used to previously produce function pointer when an address was taken for `fn {function} ()` types, we might have to continue maintaining this functionality. Even if it was accidental "feature".

**Comment by mgoszcz2** [comment] 2019-10-17 17:28
I found in the wild with eraserhd/parinfer-rust/pull/56

Curious, is my patch actually correct? Or does `foo as *const c_void` still potentially casts a zero-sized type to a pointer.

**Comment by Mark-Simulacrum** [comment] 2019-10-17 17:39
> Given that we used to previously produce function pointer when an address was taken for

As far as I can tell, this is not true. Or, at least, I can't seem to call the function when using the `&foo as ...` part: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8296afcad279652aa4e29204079b6d2b without causing a segfault. We produced something, sure, but I think it was either just a pointer into memory somewhere or possibly onto the stack, not sure.

This is the code I'd expect: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ecf238e0662e131bb5ff8787892fcc6e `foo as fn() as *const ()` to cast the function item to a "void like" function ptr.

**Comment by nagisa** [comment] 2019-10-17 17:43
@Mark-Simulacrum Amusing, in that case this would not be a bug/regression at all and can be closed!

@mgoszcz2 `foo as *const c_void` is a correct way to cast it. If you want to be absolutely sure use `foo as unsafe fn() as *const c_void` (cast function item to function pointer and then cast function pointer to an erased pointer).

**Comment by mgoszcz2** [comment] 2019-10-17 17:55
> As far as I can tell, this is not true. Or, at least, I can't seem to call the function when using the &foo as ...

The code I found this in didn't actually call the function, so you are probably right. It just returned a valid pointer in the current image which was needed for [dladdr(3)](http://man7.org/linux/man-pages/man3/dladdr1.3.html)

**Comment by nagisa** [comment] 2019-10-17 22:03
Closing in that case.

**Closed by nagisa** 2019-10-17 22:03 UTC
Labels: I-nominated, T-compiler, T-lang, regression-from-stable-to-beta
