### ISSUE TITLE
nightly-x86_64-apple-darwin unchanged - (toolchain not installed)

### ISSUE THREAD

**Issue by zhuscat** [rust-lang/rust#46396] opened 2017-11-30 12:28 UTC
Yesterday, I started to learn `rust`. 

I used vscode and installed `rls` extension on vscode, but I found the intelligence and jump to definition not work after I used the dependency `rand`(still don't know why).

So I uninstalled `rls` extension and uninstalled `rust` bu running `rustup self uninstall`, but it outputted can not find `xxxx/.cargo`, so I removed it manually.

Today, I try to install every thing again.

After I install `rls` extension, it shows:

<img width="717" alt="2017-11-30 20 15 56" src="https://user-images.githubusercontent.com/14963619/33430704-71d31f52-d60c-11e7-8bd6-f11a5053f3bc.png">

Then I press OK, it shows:

<img width="720" alt="2017-11-30 20 16 07" src="https://user-images.githubusercontent.com/14963619/33430722-804a7f4e-d60c-11e7-86c0-5ec212137dfc.png">

And I execute `rustup update nightly`, it shows:

```
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2017-11-30, rust version 1.24.0-nightly (0a2e9ade8 2017-11-29)

  nightly-x86_64-apple-darwin unchanged - (toolchain not installed)
```

**Comment by est31** [comment] 2017-11-30 12:43
#46391

**Comment by est31** [comment] 2017-11-30 12:47
@zhuscat there was an error with uploading the latest nightly. This means that mac OS users won't get a nightly today. Tomorrow everything will be fine! See the linked issue. Note that this is something very unusual -- sorry for this bad first impression of Rust :).

On the rustup side, you can work around the issue by pinning the version to yesterday's date. I'm not sure how that looks on the VS Code side or the RLS side however -- cc @matklad for that.

**Comment by kennytm** [comment] 2017-11-30 12:58
Closing as duplicate of #46391.

**Closed by kennytm** 2017-11-30 12:58 UTC

**Comment by matklad** [comment] 2017-11-30 15:34
@est31 I know nothing about VS Code or RLS, we don't use them for IntelliJ-Rust :)

**Comment by schmijos** [comment] 2017-11-30 19:50
What a bad luck...

**Comment by pjm17971** [comment] 2017-11-30 20:56
I tried Rust last night as well. On a mac. Lets just say it didn't go well. :(
