### ISSUE TITLE
target tuples for solaris not quite right

### ISSUE THREAD

**Issue by binarycrusader** [rust-lang/rust#40531] opened 2017-03-14 22:35 UTC
There are actually two different generally expected encodings of the host tuple and they're subtly different than what some might expect.

For example, 'x86_64-sun-solaris' should probably be x86_64-pc-solaris.  The reason for that is that the encoding schemes are actually:

```
#    CPU_TYPE-MANUFACTURER-OPERATING_SYSTEM
...
#    CPU_TYPE-MANUFACTURER-KERNEL-OPERATING_SYSTEM
```
https://github.com/gcc-mirror/gcc/blob/master/config.sub

So while 'sparcv9-sun-solaris' is correct because Sun is the (historical) manufacturer of sparc CPUs, 'x86_64-sun-solaris' is not, because the MANUFACTURER here is the manufacturer of the CPU *not* the operating system.  There are special cases for this, for example 'x86_64-apple-darwin', even though Apple doesn't make x86_64 CPUs, but following gcc/clang conventions leads us to x86_64-pc-solaris.

This issue has been assigned to @lzutao via [this comment](https://github.com/rust-lang/rust/issues/40531#issuecomment-501126039).

**Comment by Mark-Simulacrum** [comment] 2017-06-13 00:13
An interesting discrepancy here is that our target and the LLVM target currently don't match. I'm not sure whether we can/should change anything here for backwards compatibility reasons, though an alias seems fine.

```
$ rg 'x86_64-.*-solaris'
src/librustc_back/target/mod.rs
204:    ("x86_64-sun-solaris", x86_64_sun_solaris),

src/librustc_back/target/x86_64_sun_solaris.rs
21:        llvm_target: "x86_64-pc-solaris".to_string(),
```

**Comment by guruhegde** [comment] 2019-02-25 15:57
Hi, can I take this issue up? Can someone give a hint on how to fix this?

I am a rust beginner, interested in compilers. This would be my first contribution.

**Comment by varkor** [comment] 2019-04-27 11:04
@guruhegde: as far as I can tell, you should just be able to add a new line under:
https://github.com/rust-lang/rust/blob/597f432489f12a3f33419daa039ccef11a12c4fd/src/tools/build-manifest/src/main.rs#L120
containing `"x86_64-pc-solaris",`, and then add a new line under:
https://github.com/rust-lang/rust/blob/597f432489f12a3f33419daa039ccef11a12c4fd/src/librustc_target/spec/mod.rs#L432
containing:
```rust
// `x86_64-pc-solaris` is an alias for `x86_64_sun_solaris` for backwards compatibility reasons.
// (See https://github.com/rust-lang/rust/issues/40531.)
("x86_64-pc-solaris", x86_64_sun_solaris),
```
(Sorry for the delay: I only just saw your message.)

**Comment by psumbera** [comment] 2019-10-04 15:27
I wonder how it's supposed to work? Only x86_64-sun-solaris continues work for me:

```
$ /builds/rustc-1.37.0/bin/rustc --target=x86_64-sun-solaris test.rs
$ /builds/rustc-1.37.0/bin/rustc --target=x86_64-pc-solaris test.rs
ulx-0 17:17 /builds/psumbera/FIREFOX-2/TMP: /builds/rustc-1.37.0/bin/rustc --target=x86_64-pc-solaris test.rs
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-pc-solaris` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

This change make it harder for Mozilla Firefox to decide which target to use...

**Comment by varkor** [comment] 2019-10-07 22:54
I think we may have to introduce some changes in `src/tools/build-manifest/src/main.rs` to make rustc try to use the alias. I.e. `x86_64-pc-solaris` should try to use the target `x86_64-sun-solaris`. I haven't had time to look into what else needs to be changed.

**Comment by varkor** [comment] 2020-01-14 20:31
Closing as a duplicate of https://github.com/rust-lang/rust/issues/68214.

**Closed by varkor** 2020-01-14 20:31 UTC
Labels: A-rustbuild, A-target-specs, C-bug, O-solaris
