### ISSUE TITLE
Benchmark hang with `lto = true` and `target-cpu=native`

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/rust#49766] opened 2018-04-07 18:44 UTC
I first posted this in Cargo at https://github.com/rust-lang/cargo/issues/5312

I'm benchmarking some code and often get hangs with `$ RUSTFLAGS='-C target-cpu=native' cargo bench`.

My `Cargo.toml`:

```
[package]
name = "test_hang"
version = "0.1.0"

[profile.bench]
lto = true
```

It only happens when both LTO and target-cpu=native are enabled.

A typical output looks like this, where it hangs for as long as I've left it:

```
$ RUST_BACKTRACE=1 RUSTFLAGS='-C target-cpu=native' cargo bench -vv
       Fresh <crates>
    Finished release [optimized] target(s) in 0.0 secs
     Running `<path to crate>target/release/deps/<crate name>-86f63a8b1891302e --bench`

running 19 tests
<ignored tests>

test result: ok. 0 passed; 0 failed; 19 ignored; 0 measured; 0 filtered out

     Running `<path to crate>/target/release/deps/bench-3dd5f8be084d72c9 --bench`
```

I'm using `cargo 1.26.0-nightly (b70ab13b3 2018-04-04)`. The code requires nightly so I can't test whether this happens on stable.
$ rustc --print target-cpus says my processor is sandybridge.

## Meta

```
$ rustc --version --verbose
rustc 1.27.0-nightly (eeea94c11 2018-04-06)
binary: rustc
commit-hash: eeea94c11d02ff62fb011d1afdda9301fdf9726b
commit-date: 2018-04-06
host: x86_64-apple-darwin
release: 1.27.0-nightly
LLVM version: 6.0
```

**Comment by TheIronBorn** [comment] 2018-04-07 18:45
It doesn't seem to happen when using target-cpu=westmere, the preceding Intel CPU microarchitecture.

**Comment by TheIronBorn** [comment] 2018-04-07 18:45
I'm trying to find a minimal code example.

**Comment by TheIronBorn** [comment] 2018-04-07 20:25
Turns out it actually happens with a totally empty project:
```
├── Cargo.lock
├── Cargo.toml
├── benches
│   └── bench.rs
└── src
    └── lib.rs
```

**Comment by neachdainn** [comment] 2018-05-11 16:38
I have also experienced this issue.

```
rustc 1.27.0-nightly (e5f80f2a4 2018-05-09)
binary: rustc
commit-hash: e5f80f2a4f016bf724a1cfb580619d71c8fd39ec
commit-date: 2018-05-09
host: x86_64-apple-darwin
release: 1.27.0-nightly
LLVM version: 6.0
```

**Comment by TheIronBorn** [comment] 2018-05-11 18:43
@neachdainn what is your microarchitecture?

**Comment by neachdainn** [comment] 2018-05-11 19:12
[Core i7-4770HQ](https://ark.intel.com/products/83505/Intel-Core-i7-4770HQ-Processor-6M-Cache-up-to-3_40-GHz) (Haswell)

**Comment by TheIronBorn** [comment] 2018-05-11 19:27
Could you also test with a couple other target CPUs?

**Comment by TheIronBorn** [comment] 2018-05-11 21:03
Specifically Sandy Bridge and Westmere.

**Comment by neachdainn** [comment] 2018-05-13 01:02
Here's some tests on a different system:

```
rustc 1.26.0 (a77568041 2018-05-07)
binary: rustc
commit-hash: a7756804103447ea4e68a71ccf071e7ad8f7a03e
commit-date: 2018-05-07
host: x86_64-unknown-linux-gnu
release: 1.26.0
LLVM version: 6.0
```

[Core i5-2500k](https://ark.intel.com/products/52210/Intel-Core-i5-2500K-Processor-6M-Cache-up-to-3_70-GHz) (Sandybridge)

I am not seeing the bug on this system, so it may be a product of either the microarchitecture or it might also be macOS specific. I'll be able to test this on my Mac on Monday.

**Comment by Mark-Simulacrum** [comment] 2018-05-28 14:28
Can someone post a minimal example with code? Or at least some example?

This is probably a case of https://github.com/rust-lang/rust/issues/50422.

**Comment by TheIronBorn** [comment] 2018-05-28 18:28
As I mentioned here https://github.com/rust-lang/rust/issues/49766#issuecomment-379496816, it happens with a totally empty project.

**Comment by Mark-Simulacrum** [comment] 2018-05-28 19:12
I've confirmed I cannot reproduce on linux. I believe the hang occurs here, but I've not tracked this down further.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x0000000103f80550 bench-d5493d9f2fa74606`std::sys::unix::stack_overflow::imp::signal_handler::h373dcc530442aa18 (.llvm.16322965540172889217) + 112
bench-d5493d9f2fa74606`std::sys::unix::stack_overflow::imp::signal_handler::h373dcc530442aa18:
->  0x103f80550 <+112>: vmovdqa (%rax), %ymm0
    0x103f80554 <+116>: vmovaps 0x45c24(%rip), %ymm1
    0x103f8055c <+124>: vmovaps %ymm1, (%rax)
    0x103f80560 <+128>: movq   0x20(%rax), %rax
Target 0: (bench-d5493d9f2fa74606) stopped.
```

**Comment by TheIronBorn** [comment] 2018-05-28 20:38
Confirm it does not happen with `-C lto=thin`
```console,ignore
$ RUSTFLAGS='-C target-cpu=native -C lto=thin' cargo bench

**Comment by TheIronBorn** [comment] 2018-05-28 20:44
`-C lto=fat`: yes
`-C lto`: yes

**Comment by bluejekyll** [comment] 2018-06-06 15:31
I'm seeing a more general problem as well, where a binary running in an benchmark almost always hangs with `lto`, but when run independently hangs ~50% of the time. `lto-thin` appears to not have this issue.

I haven't investigated yet.

**Comment by steveklabnik** [comment] 2019-09-24 02:07
I'm on Windows, but I cannot reproduce this today.

**Comment by workingjubilee** [comment] 2022-07-06 03:10
Compiling from x86_64-unknown-linux-gnu to 
- x86_64-unknown-linux-gnu
- x86_64-apple-darwin (cross)

No repro with `Ctarget-cpu=sandybridge` or `-Ctarget-cpu=znver3` (native).
Closing, but feel free to bring this back if it repros on another x86_64-apple-darwin host.

**Closed by workingjubilee** 2022-07-06 03:10 UTC
Labels: A-LLVM, O-macos, C-enhancement, A-codegen, T-compiler
