### ISSUE TITLE
Parsing issues with Box'ed unboxed closures

### ISSUE THREAD

**Issue by bitonic** [rust-lang/rust#20640] opened 2015-01-06 17:01 UTC
The following code works:

``` rust
    pub fn new(delay: uint, callback: Box<FnMut() -> uint + 'a>, remove_on_drop: bool) -> Timer<'a> {
        ...
    }
```

But this doesn't:

``` rust
    pub fn new(delay: uint, callback: Box<(FnMut() -> uint) + 'a>, remove_on_drop: bool) -> Timer<'a> {
        ...
    }
```

`rustc` complains that

```
src/sdl2/timer.rs:33:43: 33:60 error: expected a path on the left-hand side of `+`, not `(FnMut() -> uint)` [E0178]
src/sdl2/timer.rs:33     pub fn new(delay: uint, callback: Box<(FnMut() -> uint) + 'a>, remove_on_drop: bool) -> Timer<'a> {
                                                               ^~~~~~~~~~~~~~~~~
src/sdl2/timer.rs:33:43: 33:60 note: perhaps you forgot parentheses? (per RFC 438)
src/sdl2/timer.rs:33     pub fn new(delay: uint, callback: Box<(FnMut() -> uint) + 'a>, remove_on_drop: bool) -> Timer<'a> {
                                                               ^~~~~~~~~~~~~~~~~
```

If I understand correctly the syntax is `trait + lifetime`, so I'd expect those parentheses to be fine (and imho they make the code more clear).  The note about forgetting parentheses is also puzzling.

**Comment by steveklabnik** [comment] 2015-09-27 01:02
Full example:

```
struct Timer<'a> {
    x: &'a i32,
}

impl<'b> Timer<'b> {
    pub fn new<'a>(delay: usize, callback: Box<(FnMut() -> usize) + 'a>, remove_on_drop: bool) -> Timer<'a> {
        unimplemented!()
    }
}

fn main() {}
```

Same error still happens today.

**Comment by pmarcelll** [comment] 2017-03-05 16:04
@petrochenkov if I understand it correctly, this is accepted today, but #40043 fixes the parser, so rejecting the parentheses is the correct behavior, and this is not a bug after all (and can be closed).

**Comment by petrochenkov** [comment] 2017-03-05 16:29
@pmarcelll 
Indeed.
I wasn't aware of this issue.
Confusing diagnistics `perhaps you forgot parentheses?` are fixed in https://github.com/rust-lang/rust/pull/40043 as well.
Closing as a duplicate of https://github.com/rust-lang/rust/issues/39318.

**Closed by petrochenkov** 2017-03-05 16:29 UTC
Labels: A-parser, I-papercut
