### ISSUE TITLE
Borrowing static array that contains another static array represented by literal doesn't work when expressed inline

### ISSUE THREAD

**Issue by pepyakin** [rust-lang/rust#54224] opened 2018-09-14 11:44 UTC
Why does this work:

```
use std::borrow::Cow;

pub const X: [u8; 3] = *b"ABC";
pub const Y: Cow<'static, [ [u8; 3] ]> = Cow::Borrowed(&[X]);
```

but this doesn't?

```
use std::borrow::Cow;

pub const Z: Cow<'static, [ [u8; 3] ]> = Cow::Borrowed(&[*b"ABC"]);
```

**Comment by Havvy** [comment] 2018-09-15 19:18
```
error[E0597]: borrowed value does not live long enough
 --> src/lib.rs:3:57
  |
3 | pub const Z: Cow<'static, [ [u8; 3] ]> = Cow::Borrowed(&[*b"ABC"]);
  |                                                         ^^^^^^^^^- temporary value only lives until here
  |                                                         |
  |                                                         temporary value does not live long enough
  |
  = note: borrowed value must be valid for the static lifetime...
```

**Comment by memoryruins** [comment] 2018-09-15 20:00
If we add ``#![feature(nll)]``, it compiles. [(playground)](https://play.rust-lang.org/?gist=735c1128be154aeacbe84175ea9e6e35&version=nightly&mode=debug&edition=2015)

It appears related to the issue described in #43058, which was fixed by nll.
cc @rust-lang/wg-compiler-nll is it correct to label this as NLL-fixed-by-NLL and close?

**Comment by nikomatsakis** [comment] 2018-09-19 20:50
This is a bit curious. I'm digging in a bit more.

**Comment by eddyb** [comment] 2018-09-19 22:31
It's a bug that NLL "fixes" this - see https://github.com/rust-lang/rust/pull/51990#discussion_r218967748.

@pepyakin This is not a bug (ignoring NLL), but we need to document it better.

`*b"ABC"` is not considered a "promotable-to-`'static` constant expression". We rely on evaluating it later to ensure that it *is* valid *where written*, but it's not treated as promotable because we don't track references/pointers in the promotion analysis, and promotion *could* change behavior.

We could maybe relax the rules a bit here, since we're in a constant *anyway*, and promotion rules require not involving named variables, but we'd need to be careful around `Drop` and unsafe code.

**Closed** 2018-10-12 15:00 UTC
