### ISSUE TITLE
rustc not search LIB path (or LIBPATH) on windows for static library

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/rust#43118] opened 2017-07-08 10:53 UTC
It works fine when linking dynamic library. But when linking static library it will complains:

>  could not find native static library `xxx`, perhaps an -L flag is missing?

Although I have configured LIB and LIBPATH to the correct path.

**Comment by retep998** [comment] 2017-07-08 11:46
This is a design flaw in how `kind=static` works, via rustc bundling the library instead of asking the linker to link it. An unstable alternative is `kind=static-nobundle` which will link to the static library the *normal* way ([tracking issue](https://github.com/rust-lang/rust/issues/37403)). Alternatively, just use `kind=dylib` for static libraries because on Windows the only difference between it and `kind=static-nobundle` is whether dllimport is applied to the symbols and for functions the linker is pretty lenient with that.

**Comment by Mark-Simulacrum** [comment] 2017-07-19 17:30
Closing as per the previous comment. I believe this is technically not a bug.

**Closed by Mark-Simulacrum** 2017-07-19 17:30 UTC

**Comment by retep998** [comment] 2017-07-19 18:38
I really wish it was considered a bug, so that the behavior of `kind=static` could change.

**Comment by Mark-Simulacrum** [comment] 2017-07-19 18:46
Yeah, I agree that the current situation isn't optimal. However, I think any change here would need an RFC anyway...
