### ISSUE TITLE
Overflowing integer crashes program

### ISSUE THREAD

**Issue by eflukx** [rust-lang/rust#45576] opened 2017-10-27 14:23 UTC
The following snippet, when built with `cargo run --release`

``` rust
fn main() {
    crash();
}

fn crash() {
    let mut count = 0u8;
    loop {
        count += 1;
    //    println!("cnt: {}", count);
    }
}
```

Results in the following on Windows 10 x64, rustc 1.20.0 (f3d6973f4 2017-08-27)

```
error: process didn't exit successfully: `target\release\bomb.exe` (exit code: 3221225501)
Illegal instruction
```

Tested on Ubuntu 14.04 Linux 3.13.0-129 x86_64, rustc 1.22-dev 
The result is:

```
thread 'main' panicked at 'assertion failed: c.borrow().is_none()', /home/piggy/code/avr-rust/src/libstd/sys_common/thread_info.rs:46:25
```

Both on Linux and Windows: When the `println!` is uncommented all seems to work as expected. When the code is not in `crash()` but directly in `main()` it also seems to work as expected.

**Comment by sfackler** [comment] 2017-10-27 14:42
It's not caused by the overflow - it's cause by LLVM removing the loop entirely because it has no side effects: https://github.com/rust-lang/rust/issues/28728.

**Comment by Mark-Simulacrum** [comment] 2017-10-30 02:08
Closing as duplicate of #28728.

**Closed by Mark-Simulacrum** 2017-10-30 02:08 UTC
