### ISSUE TITLE
rust-lld fails with "dyld: Library not loaded: @rpath/libLLVM.dylib" on 1.30.0-nightly (02cb8f2a4 2018-08-29)

### ISSUE THREAD

**Issue by parasyte** [rust-lang/rust#53813] opened 2018-08-30 03:55 UTC
Short description: I am building for a `no_std` environment using `cargo-xbuild`, and the embedded `lld` as my linker of choice. The linker fails to load since it depends on a dynamic library that doesn't actually exist.

```
$ rustc --version
rustc 1.30.0-nightly (02cb8f2a4 2018-08-29)

$ rustc --print sysroot
/Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin

$ /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
dyld: Library not loaded: @rpath/libLLVM.dylib
  Referenced from: /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
  Reason: image not found
Abort trap: 6

$ otool -L /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
/Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld:
	@rpath/libLLVM.dylib (compatibility version 1.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

Rolling back to `nightly-2018-08-27-x86_64-apple-darwin` works

```
$ rustup override set nightly-2018-08-27-x86_64-apple-darwin
info: using existing install for 'nightly-2018-08-27-x86_64-apple-darwin'
info: override toolchain for '/Users/parasyte/projects/technek' set to 'nightly-2018-08-27-x86_64-apple-darwin'

  nightly-2018-08-27-x86_64-apple-darwin unchanged - rustc 1.30.0-nightly (721913067 2018-08-26)

$ rustc --version
rustc 1.30.0-nightly (721913067 2018-08-26)

$ rustc --print sysroot
/Users/parasyte/.rustup/toolchains/nightly-2018-08-27-x86_64-apple-darwin

$ /Users/parasyte/.rustup/toolchains/nightly-2018-08-27-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-lld (WebAssembly) instead

$ otool -L /Users/parasyte/.rustup/toolchains/nightly-2018-08-27-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
/Users/parasyte/.rustup/toolchains/nightly-2018-08-27-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld:
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
```

**Comment by parasyte** [comment] 2018-08-30 04:06
Searching the source tree for `rpath` turns up some humorous comments...

https://github.com/rust-lang/rust/blob/4f1e2357447ef7e8066c49560d66c3e18f25d982/src/bootstrap/bin/rustc.rs#L199-L232

https://github.com/rust-lang/rust/blob/9d69e81e9b400805b0453b9262958c8e28faa8a0/src/librustc_codegen_llvm/back/linker.rs#L368-L371

**Comment by TejasQ** [comment] 2018-08-30 14:10
I have this issue too!

**Comment by GabrielMajeri** [comment] 2018-08-30 15:03
I believe this issue is caused by 3cf6f0db1ab61ed33c585b156a0d5c41279f0810: "Link LLVM tools dynamically...".

It only enables dynamic linking `libllvm` on Linux and Mac OS, and since no Windows users complained so far I can only assume it's the probable cause.

**Comment by japaric** [comment] 2018-08-30 15:14
@alexcrichton @michaelwoerister this may have been caused by #53245.

Also, I don't see this issue on Linux:

``` console
$ ldd $(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld
        linux-vdso.so.1 (0x00007ffe1cd74000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fab8c935000)
        libLLVM-7.so => /home/japaric/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM-7.so (0x00007fab88ecb000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fab88d46000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fab88d2c000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fab88b68000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fab8c984000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fab88b5c000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fab88b57000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fab889c8000)

$ rustc -V
rustc 1.30.0-nightly (02cb8f2a4 2018-08-29)
```

**Comment by japaric** [comment] 2018-08-30 15:46
@GabrielMajeri it seems that libLLVM.so is provided by the `llvm-tools-preview` component which I have installed. Try running `rustup component add llvm-tools-preview` and see if that fixes LLD.

@alexcrichton @michaelwoerister it sounds like libLLVM.so should *always* by shipped with the compiler since rust-lld depends on it.

**Comment by GabrielMajeri** [comment] 2018-08-30 16:09
@japaric I installed them, but it didn't help. The LLVM tools do seem to work, and I now have the `libLLVM.so` library in the `$(rustc --print sysroot)/lib` directory.

However, checking rust-lld's RPATH shows `$ORIGIN/../lib`,
i.e. it points to `$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib/`.

Doing
`ln -s $(rustc --print sysroot)/lib/libLLVM-7.so $(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib/`
does (temporarily) fix the problem.

**Comment by alexcrichton** [comment] 2018-08-30 16:44
I'm working on a fix for this!

**Comment by alexcrichton** [comment] 2018-08-30 16:50
@japaric's diagnosis is spot on and this should be fixed in https://github.com/rust-lang/rust/pull/53828

To recap, interim fixes include:

* `rustup component add llvm-tools-preview --toolchain nightly`
* Downgrading to an older nightly temporarily

**Comment by TejasQ** [comment] 2018-08-30 17:03
Thanks, @alexcrichton!

**Comment by pepyakin** [comment] 2018-08-31 16:05
> rustup component add llvm-tools-preview --toolchain nightly

Doesn't work for me on macOS by the way.

**Comment by thehappycoder** [comment] 2018-08-31 19:54
I get this with stable rust too (1.28.0):

```
192-168-1-4:wasm-game-of-life anton$ wasm-pack init
  
  [1/8] 🔧  Checking crate configuration...
  [2/8] 🎯  Adding WASM target...
\ [3/8] 🌀  Compiling to WASM...
Compilation of your program failed. stderr:

   Compiling wasm-game-of-life v0.1.0 (file:///Users/anton/projects/hacks/rust/wasm-game-of-life)
warning: function is never used: `set_panic_hook`
  --> src/utils.rs:11:9
   |
11 |         pub fn set_panic_hook() {}
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default

error: linking with `rust-lld` failed: signal: 6
  |
  = note: "rust-lld" "-flavor" "wasm" "-L" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/wasm_game_of_life.wasm_game_of_life.59gcvxac-cgu.0.rcgu.o" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/wasm_game_of_life.wasm_game_of_life.59gcvxac-cgu.1.rcgu.o" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/wasm_game_of_life.wasm_game_of_life.59gcvxac-cgu.2.rcgu.o" "-o" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/wasm_game_of_life.wasm" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/wasm_game_of_life.bxpq0uzydj2zf4e.rcgu.o" "--gc-sections" "-O3" "-L" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps" "-L" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/release/deps" "-L" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/libwasm_bindgen-f9f62e4f9e995bb5.rlib" "/Users/anton/projects/hacks/rust/wasm-game-of-life/target/wasm32-unknown-unknown/release/deps/libcfg_if-954cfacc8a40931a.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-b0efc82f64d03095.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libpanic_abort-4f93017645c0d252.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libunwind-c43a3d8cf78f9d5a.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/liblibc-68373f2b6bc18151.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/liballoc_system-40a64b71ec5a8f18.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libdlmalloc-f6caffaf44cc60a0.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/liballoc-863f2b2485046aef.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libcore-21433d3b7663b55b.rlib" "/Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-bf63ca2c3bc4de53.rlib" "--no-threads" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-entry" "--export-table"
  = note: dyld: Library not loaded: @rpath/libLLVM.dylib
            Referenced from: /Users/anton/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
            Reason: image not found
          

error: aborting due to previous error

error: Could not compile `wasm-game-of-life`.

To learn more, run the command again with --verbose.
```

**Comment by fitzgen** [comment] 2018-08-31 20:13
@thehappycoder `wasm-bindgen` only *just* had all of the features it relies on stabilize, so it is still nightly-only until those newly-stabilized features ride the release trains from nightly -> beta -> stable.

**Comment by thehappycoder** [comment] 2018-08-31 21:16
@fitzgen thanks for pointing out. I just noticed that it is using nightly version. I am new to rust, so I have no idea how to rollback to previous nightly version to use as a workaround.

**Comment by derekdreery** [comment] 2018-09-01 11:51
For future reference, you can use rustup to install any nightly, for instructions see [the rustup github page](https://github.com/rust-lang-nursery/rustup.rs#toolchain-specification)

**Comment by pepyakin** [comment] 2018-09-01 11:58
Still getting this issue on the latest nightly:


```
note: dyld: Library not loaded: @rpath/libLLVM.dylib
            Referenced from: /Users/pepyakin/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
            Reason: image not found

$ find ~/.rustup/toolchains/nightly-x86_64-apple-darwin | grep -i libLLVM.dylib | wc -l
       0

$ rustc +nightly -V
rustc 1.30.0-nightly (aaa170beb 2018-08-31)

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102

```

**Comment by derekdreery** [comment] 2018-09-01 12:06
It seems to work fine for me (on arch linux)

```
$ rustc +nightly --version
rustc 1.30.0-nightly (aaa170beb 2018-08-31)
```

**Comment by parasyte** [comment] 2018-09-01 18:58
I agree with @pepyakin It is still not working on macOS.

```
$ rustc --version
rustc 1.30.0-nightly (aaa170beb 2018-08-31)

$(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld -flavor gnu -version
dyld: Library not loaded: @rpath/libLLVM.dylib
  Referenced from: /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
  Reason: image not found
Abort trap: 6

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

**Comment by chinedufn** [comment] 2018-09-02 23:49
Seems like a number of people (including myself) are still having this issue, can we re-open?

**Comment by michaelwoerister** [comment] 2018-09-03 09:03
Apparently #53828 did not fix this entirely on Mac OS X.

**Comment by alexcrichton** [comment] 2018-09-04 19:58
I'm working on a fix for this and should be able to post it soon

**Comment by steveklabnik** [comment] 2018-09-04 19:59
I'm getting this on Linux too: https://travis-ci.org/intermezzOS/kernel/jobs/424491132#L185

**Comment by TejasQ** [comment] 2018-09-05 07:42
Thanks for your super-fast help, @alexcrichton! 🚀

**Closed** 2018-09-06 04:32 UTC

**Comment by dvdplm** [comment] 2018-09-06 06:36
For anyone wondering, the osx fix is not on the current nightly – `rustc 1.30.0-nightly (6e0f1cc15 2018-09-05)` – yet.

**Comment by jcaudle** [comment] 2018-09-06 11:32
> Why's this issue closed then? 🤔

Is it because the fox will be in tomorrow's nightly build?

**Comment by alexcrichton** [comment] 2018-09-06 16:30
Yes this fix missed last night's nightly but it should be in tonight's nightly!

**Comment by kzvi** [comment] 2018-09-07 01:09
I'm still getting this error with `rustc 1.30.0-nightly (a8c11d216 2018-09-06)`.

**Comment by alexcrichton** [comment] 2018-09-07 02:07
Looks like there's at least one more bug to fix -- https://github.com/rust-lang/rust/pull/54018

**Comment by thehappycoder** [comment] 2018-09-08 09:39
Finally, I managed to compile on a mac with the latest nightly build of rust!

**Comment by ssundarr3** [comment] 2020-09-19 13:17
I still seem to be getting this error on `rustc 1.48.0-nightly (bbc677480 2020-09-18)`. 

```
➜  ~ rustc --version
rustc 1.48.0-nightly (bbc677480 2020-09-18)
➜  ~ $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
dyld: Library not loaded: @rpath/libLLVM.dylib
  Referenced from: /Users/shridhar/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
  Reason: image not found
[1]    1641 abort      $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
```

It works on `rustc 1.46.0 (04488afe3 2020-08-24)`:

```
➜  ~ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
➜  ~ $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
➜  ~ rustup override set nightly-2018-09-12-x86_64-apple-darwin
info: using existing install for 'nightly-2018-09-12-x86_64-apple-darwin'
info: override toolchain for '/Users/shridhar' set to 'nightly-2018-09-12-x86_64-apple-darwin'

  nightly-2018-09-12-x86_64-apple-darwin unchanged - rustc 1.30.0-nightly (2f1547c0a 2018-09-11)
```

and works on and `rustc 1.30.0-nightly (2f1547c0a 2018-09-11)`:

```
➜  ~ rustc --version
rustc 1.30.0-nightly (2f1547c0a 2018-09-11)
➜  ~ $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-lld (WebAssembly) instead
➜  ~ rustup override set nightly-x86_64-apple-darwin
info: using existing install for 'nightly-x86_64-apple-darwin'
info: override toolchain for '/Users/shridhar' set to 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.48.0-nightly (bbc677480 2020-09-18)
```

I'm on MacOS Catalina version 10.15.16.
