### ISSUE TITLE
libsyntax not in 1.20 nightly rust-src component?

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42667] opened 2017-06-15 01:08 UTC
Per a [rustup report](https://github.com/rust-lang-nursery/rustup.rs/issues/1165), are the nightly rust-src packages not including libsyntax?

**Comment by brson** [comment] 2017-06-15 01:09
cc @gbip

**Comment by ishitatsuyuki** [comment] 2017-06-15 08:19
Yes, since they're rustc source, and only libstd source is needed for racer.

Blame #41546

**Comment by nrc** [comment] 2017-06-19 20:06
We discussed at the dev-tools meeting today, consensus was that this is by design and the decision to remove was good

**Comment by nrc** [comment] 2017-06-19 20:21
Further, we thought that for users who want the compiler sources, we should make available a separate rust-src-internals with the source for the compiler including libsyntax.

**Comment by alexcrichton** [comment] 2017-07-23 15:32
Untagging as a regression due to [previous comment](https://github.com/rust-lang/rust/issues/42667#issuecomment-309558390)

**Comment by sanmai-NL** [comment] 2019-03-17 14:14
@alexcrichton: can this be closed?

**Comment by oli-obk** [comment] 2019-03-18 16:07
fixed in https://github.com/rust-lang/rust/pull/58269

**Closed by oli-obk** 2019-03-18 16:07 UTC
Labels: A-rustbuild, C-feature-request, P-low, T-infra
