### ISSUE TITLE
Rustdoc doesn't handle square brackets in link text properly when using non-inline link targets

### ISSUE THREAD

**Issue by JanBeh** [rust-lang/rust#101133] opened 2022-08-28 19:30 UTC
I tried this code:

```rust
pub struct S;

/// Some inline documentation [`without brackets`][S]
pub fn dummy1() {}

/// Some inline documentation [`[with brackets]`][S]
pub fn dummy2() {}

/// Some non-inline documentation [`without brackets`]
///
/// [`without brackets`]: S
pub fn dummy3() {}

/// Some non-inline documentation [`[with brackets]`]
/// 
/// [`[with brackets]`]: S
pub fn dummy4() {}
```

When running `cargo rustdoc`, I expected each of the created documentation texts to contain a hyperlink.

Instead, this happened: Documentation of `dummy4` is

> Some non-inline documentation [[with brackets]]

where the inner brackets and the text inside the brackets is using a monospaced font. But there is no hyperlink.

Documentation of functions `dummy1`, `dummy2`, and `dummy3` work fine.

This is a problem when having something like `[T]` in the documentation and you want to link it to `prim@slice`.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (eaadb8947 2022-08-27)
binary: rustc
commit-hash: eaadb8947b850a025404082f6297766c4680a42a
commit-date: 2022-08-27
host: x86_64-unknown-freebsd
release: 1.65.0-nightly
LLVM version: 15.0.0
```

**Comment by ehuss** [comment] 2022-08-28 20:02
I believe this is working as intended. Rustdoc follows closely to the Markdown specification which does not permit unescaped square brackets (see [link label](https://spec.commonmark.org/0.30/#link-label)). 

If you want `[T]` to link to the slice documentation, I think ```[`[T]`][slice]``` or ```[`[T]`][prim@slice]``` should work.

**Comment by JanBeh** [comment] 2022-08-28 20:54
> I believe this is working as intended. Rustdoc follows closely to the Markdown specification which does not permit unescaped square brackets (see [link label](https://spec.commonmark.org/0.30/#link-label)).

I wasn't aware of that; in that case, I'd like to apologize for reporting this as a bug.

Does it still make sense to allow this syntax, or is adherence to Markdown specification of higher importance?

**Comment by GuillaumeGomez** [comment] 2022-09-01 11:34
We generally try to not make any rustdoc feature break the markdown specification.

**Comment by JanBeh** [comment] 2022-09-01 13:23
Okay, you can just close this issue then if you think it should not be supported. I wrongly assumed it was a bug but apparently it isn't.

**Comment by GuillaumeGomez** [comment] 2022-09-01 14:40
Ok, closing then!

**Closed by GuillaumeGomez** 2022-09-01 14:40 UTC
Labels: T-rustdoc, C-bug
