### ISSUE TITLE
ICE: no enclosing scope for id 7 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#94380] opened 2022-02-25 22:36 UTC
### Code

```Rust
struct Bug<A = [(); (let a = (), 1).1]> {
    a: A
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (4b043faba 2022-02-24)
binary: rustc
commit-hash: 4b043faba34ccc053a4d0110634c323f6c03765e
commit-date: 2022-02-24
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

### Error output

```
error: `let` expressions are not supported here
 --> ./11759.rs:1:22
  |
1 | struct Bug<A = [(); (let a = (), 1).1]> {
  |                      ^^^^^^^^^^
  |
  = note: only supported directly in conditions of `if`- and `while`-expressions
  = note: as well as when nested within `&&` and parentheses in those conditions

error[E0658]: `let` expressions in this position are unstable
 --> ./11759.rs:1:22
  |
1 | struct Bug<A = [(); (let a = (), 1).1]> {
  |                      ^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
  = help: add `#![feature(let_chains)]` to the crate attributes to enable

error: internal compiler error: compiler/rustc_middle/src/middle/region.rs:370:32: no enclosing scope for id 7

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1160:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: `let` expressions are not supported here
 --> ./11759.rs:1:22
  |
1 | struct Bug<A = [(); (let a = (), 1).1]> {
  |                      ^^^^^^^^^^
  |
  = note: only supported directly in conditions of `if`- and `while`-expressions
  = note: as well as when nested within `&&` and parentheses in those conditions

error[E0658]: `let` expressions in this position are unstable
 --> ./11759.rs:1:22
  |
1 | struct Bug<A = [(); (let a = (), 1).1]> {
  |                      ^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
  = help: add `#![feature(let_chains)]` to the crate attributes to enable

error: internal compiler error: compiler/rustc_middle/src/middle/region.rs:370:32: no enclosing scope for id 7

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1160:9
stack backtrace:
   0:     0x7fbc50b65d4c - std::backtrace_rs::backtrace::libunwind::trace::h853a1389f6e5e745
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fbc50b65d4c - std::backtrace_rs::backtrace::trace_unsynchronized::h141fba7f3343285a
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbc50b65d4c - std::sys_common::backtrace::_print_fmt::h3413d0b0d4b31c4c
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fbc50b65d4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbc867a15ccd0341f
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fbc50bc59fc - core::fmt::write::h35157148513e92bc
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fbc50b55e78 - std::io::Write::write_fmt::hc5517132c5cecddc
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/io/mod.rs:1657:15
   6:     0x7fbc50b69d27 - std::sys_common::backtrace::_print::hc5f683d445b22529
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fbc50b69d27 - std::sys_common::backtrace::print::hd841ed3190824cc9
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fbc50b69d27 - std::panicking::default_hook::{{closure}}::h9a0c56b9dbc35012
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:295:22
   9:     0x7fbc50b699df - std::panicking::default_hook::hc46807a97c7de333
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:314:9
  10:     0x7fbc512fb0d1 - rustc_driver[442ed871d20551d1]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fbc50b6a5f6 - std::panicking::rust_panic_with_hook::h1ad2fcf54bcf9bb5
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/panicking.rs:702:17
  12:     0x7fbc52364f11 - std[2a6da251afaa3124]::panicking::begin_panic::<rustc_errors[1b480dc045645b1a]::ExplicitBug>::{closure#0}
  13:     0x7fbc52364e76 - std[2a6da251afaa3124]::sys_common::backtrace::__rust_end_short_backtrace::<std[2a6da251afaa3124]::panicking::begin_panic<rustc_errors[1b480dc045645b1a]::ExplicitBug>::{closure#0}, !>
  14:     0x7fbc5236b37f - std[2a6da251afaa3124]::panicking::begin_panic::<rustc_errors[1b480dc045645b1a]::ExplicitBug>
  15:     0x7fbc523784ad - std[2a6da251afaa3124]::panic::panic_any::<rustc_errors[1b480dc045645b1a]::ExplicitBug>
  16:     0x7fbc52377737 - <rustc_errors[1b480dc045645b1a]::HandlerInner>::bug
  17:     0x7fbc52377230 - <rustc_errors[1b480dc045645b1a]::Handler>::bug
  18:     0x7fbc522ce7d9 - rustc_middle[cef953e2dc6653d0]::ty::context::tls::with_opt::<rustc_middle[cef953e2dc6653d0]::util::bug::opt_span_bug_fmt<rustc_span[cac29f2f15677c0e]::span_encoding::Span>::{closure#0}, ()>
  19:     0x7fbc522cea70 - rustc_middle[cef953e2dc6653d0]::util::bug::opt_span_bug_fmt::<rustc_span[cac29f2f15677c0e]::span_encoding::Span>
  20:     0x7fbc522ce9e6 - rustc_middle[cef953e2dc6653d0]::util::bug::bug_fmt
  21:     0x7fbc5303a9cf - <rustc_middle[cef953e2dc6653d0]::middle::region::ScopeTree>::var_scope
  22:     0x7fbc528d8310 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::bind_and_guard_matched_candidate
  23:     0x7fbc534b57bb - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::lower_let_expr
  24:     0x7fbc528cc0ef - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_into_dest
  25:     0x7fbc528c6be7 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::as_temp_inner
  26:     0x7fbc528c1067 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::as_operand
  27:     0x7fbc528c129d - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::as_operand
  28:     0x7fbc528c5060 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::as_rvalue
  29:     0x7fbc528c859e - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_into_dest
  30:     0x7fbc528c6be7 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::as_temp_inner
  31:     0x7fbc528c32ca - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_as_place
  32:     0x7fbc528c2f1f - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_as_place
  33:     0x7fbc528c3543 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_as_place
  34:     0x7fbc528ca4c1 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_into_dest
  35:     0x7fbc528c7ff3 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_into_dest
  36:     0x7fbc528c7ff3 - <rustc_mir_build[63d0f315beefaf09]::build::Builder>::expr_into_dest
  37:     0x7fbc534b05c6 - rustc_mir_build[63d0f315beefaf09]::build::construct_const
  38:     0x7fbc5290e213 - <rustc_infer[ac61a81e2eeb1199]::infer::InferCtxtBuilder>::enter::<rustc_middle[cef953e2dc6653d0]::mir::Body, rustc_mir_build[63d0f315beefaf09]::build::mir_build::{closure#1}>
  39:     0x7fbc528b8c13 - rustc_mir_build[63d0f315beefaf09]::build::mir_built
  40:     0x7fbc52b5b4e6 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::WithOptConstParam<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId>, &rustc_data_structures[fac9844b9b0de929]::steal::Steal<rustc_middle[cef953e2dc6653d0]::mir::Body>>>
  41:     0x7fbc52bc3174 - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::mir_built
  42:     0x7fbc525d8928 - rustc_mir_transform[66935fe77a7fe304]::check_unsafety::unsafety_check_result
  43:     0x7fbc525d6447 - <rustc_mir_transform[66935fe77a7fe304]::check_unsafety::provide::{closure#0} as core[a2af605994515733]::ops::function::FnOnce<(rustc_middle[cef953e2dc6653d0]::ty::context::TyCtxt, rustc_span[cac29f2f15677c0e]::def_id::LocalDefId)>>::call_once
  44:     0x7fbc52b70a51 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId, &rustc_middle[cef953e2dc6653d0]::mir::query::UnsafetyCheckResult>>
  45:     0x7fbc52bc45c1 - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::unsafety_check_result
  46:     0x7fbc525e33a3 - rustc_mir_transform[66935fe77a7fe304]::mir_const
  47:     0x7fbc52b5b4e6 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::WithOptConstParam<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId>, &rustc_data_structures[fac9844b9b0de929]::steal::Steal<rustc_middle[cef953e2dc6653d0]::mir::Body>>>
  48:     0x7fbc52bc32bb - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::mir_const
  49:     0x7fbc525d5571 - <rustc_mir_transform[66935fe77a7fe304]::provide::{closure#0} as core[a2af605994515733]::ops::function::FnOnce<(rustc_middle[cef953e2dc6653d0]::ty::context::TyCtxt, rustc_span[cac29f2f15677c0e]::def_id::DefId)>>::call_once
  50:     0x7fbc52b7ef32 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_span[cac29f2f15677c0e]::def_id::DefId, rustc_middle[cef953e2dc6653d0]::mir::query::ConstQualifs>>
  51:     0x7fbc52bc3017 - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::mir_const_qualif
  52:     0x7fbc525e429f - rustc_mir_transform[66935fe77a7fe304]::mir_promoted
  53:     0x7fbc52b5cacd - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::WithOptConstParam<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId>, (&rustc_data_structures[fac9844b9b0de929]::steal::Steal<rustc_middle[cef953e2dc6653d0]::mir::Body>, &rustc_data_structures[fac9844b9b0de929]::steal::Steal<rustc_index[c6d6c6f89e0fa15d]::vec::IndexVec<rustc_middle[cef953e2dc6653d0]::mir::Promoted, rustc_middle[cef953e2dc6653d0]::mir::Body>>)>>
  54:     0x7fbc52bc36ff - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::mir_promoted
  55:     0x7fbc529d2559 - <rustc_borrowck[3aeb548815c6b6a8]::provide::{closure#0} as core[a2af605994515733]::ops::function::FnOnce<(rustc_middle[cef953e2dc6653d0]::ty::context::TyCtxt, rustc_span[cac29f2f15677c0e]::def_id::LocalDefId)>>::call_once
  56:     0x7fbc52b6f9a1 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId, &rustc_middle[cef953e2dc6653d0]::mir::query::BorrowCheckResult>>
  57:     0x7fbc52bc4c7e - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::mir_borrowck
  58:     0x7fbc52ff0289 - <rustc_middle[cef953e2dc6653d0]::ty::context::TyCtxt>::mir_borrowck_opt_const_arg
  59:     0x7fbc525e6850 - rustc_mir_transform[66935fe77a7fe304]::mir_drops_elaborated_and_const_checked
  60:     0x7fbc52b5b4e6 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::WithOptConstParam<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId>, &rustc_data_structures[fac9844b9b0de929]::steal::Steal<rustc_middle[cef953e2dc6653d0]::mir::Body>>>
  61:     0x7fbc52bc35a7 - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::mir_drops_elaborated_and_const_checked
  62:     0x7fbc532e4c40 - rustc_mir_transform[66935fe77a7fe304]::inner_mir_for_ctfe
  63:     0x7fbc532e4475 - rustc_mir_transform[66935fe77a7fe304]::mir_for_ctfe
  64:     0x7fbc52b813b2 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_span[cac29f2f15677c0e]::def_id::DefId, &rustc_middle[cef953e2dc6653d0]::mir::Body>>
  65:     0x7fbc53605628 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::get_query::<rustc_query_impl[3c87bff9477a19b0]::queries::mir_for_ctfe, rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt>
  66:     0x7fbc51aba9d6 - <rustc_const_eval[2597fefd2201b516]::const_eval::machine::CompileTimeInterpreter as rustc_const_eval[2597fefd2201b516]::interpret::machine::Machine>::load_mir
  67:     0x7fbc53546446 - <rustc_const_eval[2597fefd2201b516]::interpret::eval_context::InterpCx<rustc_const_eval[2597fefd2201b516]::const_eval::machine::CompileTimeInterpreter>>::load_mir
  68:     0x7fbc52b2ddef - rustc_const_eval[2597fefd2201b516]::const_eval::eval_queries::eval_to_allocation_raw_provider
  69:     0x7fbc52b56be3 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::ParamEnvAnd<rustc_middle[cef953e2dc6653d0]::mir::interpret::GlobalId>, core[a2af605994515733]::result::Result<rustc_middle[cef953e2dc6653d0]::mir::interpret::value::ConstAlloc, rustc_middle[cef953e2dc6653d0]::mir::interpret::error::ErrorHandled>>>
  70:     0x7fbc52bc4ddf - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::eval_to_allocation_raw
  71:     0x7fbc52b2ccd7 - rustc_const_eval[2597fefd2201b516]::const_eval::eval_queries::eval_to_const_value_raw_provider
  72:     0x7fbc52b57d24 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::ParamEnvAnd<rustc_middle[cef953e2dc6653d0]::mir::interpret::GlobalId>, core[a2af605994515733]::result::Result<rustc_middle[cef953e2dc6653d0]::mir::interpret::value::ConstValue, rustc_middle[cef953e2dc6653d0]::mir::interpret::error::ErrorHandled>>>
  73:     0x7fbc52bc4f9b - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::eval_to_const_value_raw
  74:     0x7fbc52b2ca51 - rustc_const_eval[2597fefd2201b516]::const_eval::eval_queries::eval_to_const_value_raw_provider
  75:     0x7fbc52b57d24 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_middle[cef953e2dc6653d0]::ty::ParamEnvAnd<rustc_middle[cef953e2dc6653d0]::mir::interpret::GlobalId>, core[a2af605994515733]::result::Result<rustc_middle[cef953e2dc6653d0]::mir::interpret::value::ConstValue, rustc_middle[cef953e2dc6653d0]::mir::interpret::error::ErrorHandled>>>
  76:     0x7fbc52bc4f9b - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::eval_to_const_value_raw
  77:     0x7fbc52fe5987 - <rustc_middle[cef953e2dc6653d0]::ty::context::TyCtxt>::const_eval_global_id
  78:     0x7fbc53947fc9 - <rustc_middle[cef953e2dc6653d0]::ty::context::TyCtxt>::const_eval_resolve
  79:     0x7fbc538ad361 - <rustc_trait_selection[564dcb93ecd17cac]::traits::project::AssocTypeNormalizer as rustc_middle[cef953e2dc6653d0]::ty::fold::TypeFolder>::fold_const
  80:     0x7fbc52ef5b0b - <rustc_middle[cef953e2dc6653d0]::ty::Ty as rustc_middle[cef953e2dc6653d0]::ty::fold::TypeFoldable>::super_fold_with::<rustc_trait_selection[564dcb93ecd17cac]::traits::project::AssocTypeNormalizer>
  81:     0x7fbc52e8773a - <rustc_trait_selection[564dcb93ecd17cac]::traits::project::AssocTypeNormalizer as rustc_middle[cef953e2dc6653d0]::ty::fold::TypeFolder>::fold_ty
  82:     0x7fbc52696b3d - <&rustc_middle[cef953e2dc6653d0]::ty::list::List<rustc_middle[cef953e2dc6653d0]::ty::subst::GenericArg> as rustc_middle[cef953e2dc6653d0]::ty::fold::TypeFoldable>::try_fold_with::<rustc_trait_selection[564dcb93ecd17cac]::traits::project::AssocTypeNormalizer>
  83:     0x7fbc5272ceba - <rustc_middle[cef953e2dc6653d0]::ty::Predicate as rustc_middle[cef953e2dc6653d0]::ty::fold::TypeFoldable>::super_fold_with::<rustc_trait_selection[564dcb93ecd17cac]::traits::project::AssocTypeNormalizer>
  84:     0x7fbc533e6caa - <rustc_trait_selection[564dcb93ecd17cac]::traits::project::AssocTypeNormalizer>::fold::<rustc_middle[cef953e2dc6653d0]::ty::Predicate>
  85:     0x7fbc533e6594 - rustc_trait_selection[564dcb93ecd17cac]::traits::project::normalize::<rustc_middle[cef953e2dc6653d0]::ty::Predicate>
  86:     0x7fbc533a67fe - <rustc_infer[ac61a81e2eeb1199]::infer::InferCtxt as rustc_trait_selection[564dcb93ecd17cac]::infer::InferCtxtExt>::partially_normalize_associated_types_in::<rustc_middle[cef953e2dc6653d0]::ty::Predicate>
  87:     0x7fbc53357e90 - <rustc_typeck[ba0aa0ef58073783]::check::fn_ctxt::FnCtxt>::normalize_associated_types_in::<rustc_middle[cef953e2dc6653d0]::ty::Predicate>
  88:     0x7fbc52717cca - rustc_typeck[ba0aa0ef58073783]::check::wfcheck::check_where_clauses
  89:     0x7fbc533ae095 - <rustc_infer[ac61a81e2eeb1199]::infer::InferCtxtBuilder>::enter::<(), <rustc_typeck[ba0aa0ef58073783]::check::inherited::InheritedBuilder>::enter<<rustc_typeck[ba0aa0ef58073783]::check::wfcheck::CheckWfFcxBuilder>::with_fcx<rustc_typeck[ba0aa0ef58073783]::check::wfcheck::check_type_defn<rustc_typeck[ba0aa0ef58073783]::check::wfcheck::check_item_well_formed::{closure#2}>::{closure#0}>::{closure#0}, ()>::{closure#0}>
  90:     0x7fbc52715987 - rustc_typeck[ba0aa0ef58073783]::check::wfcheck::check_item_well_formed
  91:     0x7fbc52b71b07 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<rustc_span[cac29f2f15677c0e]::def_id::LocalDefId, ()>>
  92:     0x7fbc52bc69b5 - <rustc_query_impl[3c87bff9477a19b0]::Queries as rustc_middle[cef953e2dc6653d0]::ty::query::QueryEngine>::check_item_well_formed
  93:     0x7fbc526fc718 - rustc_data_structures[fac9844b9b0de929]::sync::par_for_each_in::<&alloc[712883fc59a62f7]::vec::Vec<rustc_hir[5f50d7fdb7b24348]::hir::MaybeOwner<&rustc_hir[5f50d7fdb7b24348]::hir::OwnerInfo>>, <rustc_middle[cef953e2dc6653d0]::hir::map::Map>::par_visit_all_item_likes<rustc_typeck[ba0aa0ef58073783]::check::wfcheck::CheckTypeWellFormedVisitor>::{closure#0}>
  94:     0x7fbc5339dba2 - <rustc_session[94f6c5c92635dd6]::session::Session>::track_errors::<rustc_typeck[ba0aa0ef58073783]::check_crate::{closure#5}, ()>
  95:     0x7fbc5339543b - rustc_typeck[ba0aa0ef58073783]::check_crate
  96:     0x7fbc53124d17 - rustc_interface[65caae14b4217ef3]::passes::analysis
  97:     0x7fbc535d898b - rustc_query_system[1880d9bd090da1b9]::query::plumbing::try_execute_query::<rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt, rustc_query_system[1880d9bd090da1b9]::query::caches::DefaultCache<(), core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>>
  98:     0x7fbc5361a845 - rustc_query_system[1880d9bd090da1b9]::query::plumbing::get_query::<rustc_query_impl[3c87bff9477a19b0]::queries::analysis, rustc_query_impl[3c87bff9477a19b0]::plumbing::QueryCtxt>
  99:     0x7fbc53102d38 - <rustc_interface[65caae14b4217ef3]::passes::QueryContext>::enter::<rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>
 100:     0x7fbc530f1faa - <rustc_interface[65caae14b4217ef3]::interface::Compiler>::enter::<rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}::{closure#2}, core[a2af605994515733]::result::Result<core[a2af605994515733]::option::Option<rustc_interface[65caae14b4217ef3]::queries::Linker>, rustc_errors[1b480dc045645b1a]::ErrorReported>>
 101:     0x7fbc530f4196 - rustc_span[cac29f2f15677c0e]::with_source_map::<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_interface[65caae14b4217ef3]::interface::create_compiler_and_run<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#1}>
 102:     0x7fbc530f19b1 - rustc_interface[65caae14b4217ef3]::interface::create_compiler_and_run::<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>
 103:     0x7fbc530dd372 - <scoped_tls[876471c7b20f8e0c]::ScopedKey<rustc_span[cac29f2f15677c0e]::SessionGlobals>>::set::<rustc_interface[65caae14b4217ef3]::interface::run_compiler<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>
 104:     0x7fbc530dcc2d - std[2a6da251afaa3124]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[65caae14b4217ef3]::util::run_in_thread_pool_with_globals<rustc_interface[65caae14b4217ef3]::interface::run_compiler<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>
 105:     0x7fbc530db419 - <<std[2a6da251afaa3124]::thread::Builder>::spawn_unchecked_<rustc_interface[65caae14b4217ef3]::util::run_in_thread_pool_with_globals<rustc_interface[65caae14b4217ef3]::interface::run_compiler<core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>, rustc_driver[442ed871d20551d1]::run_compiler::{closure#1}>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>::{closure#0}, core[a2af605994515733]::result::Result<(), rustc_errors[1b480dc045645b1a]::ErrorReported>>::{closure#1} as core[a2af605994515733]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 106:     0x7fbc50b76183 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hbda7b2dd6cb05b7b
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/alloc/src/boxed.rs:1854:9
 107:     0x7fbc50b76183 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e7c4e55f1ee6074
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/alloc/src/boxed.rs:1854:9
 108:     0x7fbc50b76183 - std::sys::unix::thread::Thread::new::thread_start::h272cda2d6cad9954
                               at /rustc/4b043faba34ccc053a4d0110634c323f6c03765e/library/std/src/sys/unix/thread.rs:108:17
 109:     0x7fbc50a7b259 - start_thread
 110:     0x7fbc509975e3 - __GI___clone
 111:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (4b043faba 2022-02-24) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `Bug::{constant#0}`
#1 [unsafety_check_result] unsafety-checking `Bug::{constant#0}`
#2 [mir_const] processing MIR for `Bug::{constant#0}`
#3 [mir_const_qualif] const checking `Bug::{constant#0}`
#4 [mir_promoted] processing `Bug::{constant#0}`
#5 [mir_borrowck] borrow-checking `Bug::{constant#0}`
#6 [mir_drops_elaborated_and_const_checked] elaborating drops for `Bug::{constant#0}`
#7 [mir_for_ctfe] caching mir of `Bug::{constant#0}` for CTFE
#8 [eval_to_allocation_raw] const-evaluating + checking `Bug::{constant#0}`
#9 [eval_to_const_value_raw] simplifying constant for the type system `Bug::{constant#0}`
#10 [eval_to_const_value_raw] simplifying constant for the type system `Bug::{constant#0}`
#11 [check_item_well_formed] checking that `Bug` is well-formed
#12 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
```

</p>
</details>

**Comment by DutchGhost** [comment] 2022-02-28 09:52
This looks like a dupe of https://github.com/rust-lang/rust/issues/92893

**Closed** 2022-04-16 12:08 UTC
Labels: I-ICE, T-compiler, C-bug, glacier
