### ISSUE TITLE
Debug info tried to be emitted for unreachable code

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#22852] opened 2015-02-27 00:19 UTC
This code causes an ICE:

```rust
fn main() {
    println!("x");
    return;
    let test = if x() { 1 } else { 2 };
}

fn x() -> bool { unreachable!() }
```

complaining that the the `test` variable isn't an alloca. This is true, since we don't output any LLVM IR for unreachable code, which is everything after the `return`. For some reason, this only happens with `if` expressions (or at least, it doesn't happen with plain expressions or ordinary blocks) on the RHS.

**Comment by michaelwoerister** [comment] 2015-03-04 13:39
Thanks for the report. Closing as duplicate of #21559.

**Closed by michaelwoerister** 2015-03-04 13:39 UTC
Labels: A-codegen, A-debuginfo, I-ICE
