### ISSUE TITLE
[Feature request] Setup and teardown for tests

### ISSUE THREAD

**Issue by Adrien-Bodineau** [rust-lang/rust#134171] opened 2024-12-11 13:38 UTC
What about introducing new tests attributes for edition 2024 to allow global setup/teardown in tests ?

Something like 
```rust
#[setup]
fn foo() {
    // do stuff...
}

#[teardown]
fn bar() {
    // undo stuff...
}
```

setup would run before all tests in its module and teardown after

**Comment by bjorn3** [comment] 2024-12-11 14:29
You might want to open an issue on https://github.com/rust-lang/libtest-next instead.

**Comment by GuillaumeGomez** [comment] 2024-12-11 14:58
Well, sounds like something that would definitely be useful to have without adding a dependency. I'd gladly use such a feature.

**Comment by bjorn3** [comment] 2024-12-11 15:22
libtest-next contains experiments for a rework of the existing testing support in rustc itself. I guess you could see the libtest-next issue tracker as a list of feature requests for whatever the new implementation of testing support  for rust will end up.

**Comment by jieyouxu** [comment] 2024-12-11 15:32
AFAIK `libtest` itself is more or less feature-frozen at the moment, and it is extremely unlikely to accept new feature requests.

**Comment by jieyouxu** [comment] 2024-12-11 15:37
Actually, this feature request is a duplicate of #117668. I'm going to close this in favor of the earlier request. Thank you for the request.

**Closed by jieyouxu** 2024-12-11 15:37 UTC
Labels: C-feature-request, A-libtest, T-testing-devex

**Comment by GuillaumeGomez** [comment] 2024-12-11 15:39
Oh I see. Didn't know `test` was in rework. It's great news!
