### ISSUE TITLE
Use of deprecated array declaration syntax throws internal compiler error

### ISSUE THREAD

**Issue by hahanein** [rust-lang/rust#40854] opened 2017-03-27 14:37 UTC
Use of deprecated array declaration syntax throws internal compiler error.

I tried this code:

`type SomeType = [i8, ..12];`

Then this happened:

    error: internal compiler error: /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:374: local_def_id: no entry for `203`, which has a map of `Some(EntryExpr(NodeId(5), expr(203: ::std::ops::RangeTo{end: 12,})))`

**Comment by arielb1** [comment] 2017-03-27 15:38
dupe of #40749.

**Closed by arielb1** 2017-03-27 15:38 UTC
