### ISSUE TITLE
Compiler panic on nightly

### ISSUE THREAD

**Issue by mtn** [rust-lang/rust#49310] opened 2018-03-23 16:36 UTC
The input code wasn't valid -- I had incorrectly tried to source a type (Address, at the top of src/blockchain.rs) from the wrong module. Compiling with this error in the input code, the linked backtrace was produced. After sourcing from the correct namespace, the compiler no longer panics.

Not at all familiar with the rust source, and this might be expected or usual given I'm running nightly!

I tried this code:

https://github.com/mtn/tulipchain/tree/compiler_panic

I expected to see this happen: The program fail to compile, with some errors

Instead, this happened: The compiler panicked

## Meta

`rustc --version --verbose`:

```
[12:30:16] mtn:tulipchain git:(compiler_panic) $ rustc --version --verbose
rustc 1.26.0-nightly (5508b2714 2018-03-18)
binary: rustc
commit-hash: 5508b27145cfb82896ae838e6aca0cd48750796f
commit-date: 2018-03-18
host: x86_64-apple-darwin
release: 1.26.0-nightly
LLVM version: 6.0
```

Backtrace:
https://raw.githubusercontent.com/mtn/tulipchain/compiler_panic/README.md

**Comment by pietroalbini** [comment] 2018-03-23 18:25
Duplicate of #49159. Thanks for reporting this!

**Closed by pietroalbini** 2018-03-23 18:25 UTC
