### ISSUE TITLE
binary applications and exiting pipes behave badly together by default

### ISSUE THREAD

**Issue by clux** [rust-lang/rust#49025] opened 2018-03-14 19:29 UTC
Consider an example program that produces a list to stdout, but takes some time doing so:

```rust
use std::{thread, time};

fn main() {
    let millis = time::Duration::from_millis(100);
    println!("a");
    thread::sleep(millis);
    println!("b");
    thread::sleep(millis);
    println!("c");
}
```

```sh
# works
./target/debug/piper | grep a
# crashes and shows me a rust backtrace
./target/debug/piper | grep -q a
```

The only related issue I found was https://github.com/rust-lang/rust/issues/35108 which talks about using `write!` instead so you could handle the errors.

Sure enough, instead of `println!` using:

```rust
   let _ = io::stdout().write(b"a\n");
```
everywhere does fix it. But is this really a good substitute?

If we are writing CLI tools and are printing formatted strings to stdout we now have to start stuff like:

```rust
let _ = io::stdout().write(&format!("{}\n", svc).as_bytes());
```

which feels like a lot of faff for a "println that i don't care if the program i wrote into disappeared or not".

**Comment by sfackler** [comment] 2018-03-14 20:35
Duplicate of #46016

**Closed** 2018-03-14 20:35 UTC
