### ISSUE TITLE
Mistaken "dropped here while still borrowed" with impl trait + match

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/rust#52706] opened 2018-07-25 16:32 UTC
This manifests identically on stable and nightly without and with nll.

```rust
struct X;
impl X {
    fn my_method<'a>(&'a self) -> impl Abc + 'a {
        ()
    }
}

trait Abc {}
impl Abc for () {}

fn main() {
    let my_struct = X;
    match my_struct.my_method() {
        _ => (),
    }
    // let _ = my_struct.my_method(); // uncommenting this makes it work
}

```

([Playground](https://play.rust-lang.org/?gist=3a2e1ba1f316ee741a4bc3a2d9bc075c&version=stable&mode=debug&edition=2015))

Errors:

```
error[E0597]: `my_struct` does not live long enough
  --> src/main.rs:13:11
   |
13 |     match my_struct.my_method() {
   |           ^^^^^^^^^ borrowed value does not live long enough
...
17 | }
   | - `my_struct` dropped here while still borrowed
   |
   = note: values in a scope are dropped in the opposite order they are created
```

**Comment by nikomatsakis** [comment] 2018-08-31 21:01
Curious, needs some more investigation.

**Comment by pnkfelix** [comment] 2018-09-04 19:55
assigning to self for preliminary investigation.

**Comment by pnkfelix** [comment] 2018-09-07 13:48
(removing NLL label since the bug is stated as occurring with and *without* NLL.)

**Comment by eddyb** [comment] 2018-09-13 14:58
You don't need *that specific statement*, even just adding a semicolon fixes it.

**Comment by pnkfelix** [comment] 2018-09-13 15:08
Discussed at meeting. This is similar to a number of other cases I was looking at today, in that `impl Trait`'s are assumed to potentially have a destructor, which in turn have implications for how they are treated during borrow-checking.

In our current implementation of the rvalue-lifetime and drop-check rules in particular  #21114 and #46413, you can end up in scenarios where the last expression in a block needs to have a semi-colon added to it, or you get borrow-check errors.

It would be good for us to address those cases, potentially as part of longer term NLL work, but its not something we're treating as a high priority item in the *short term*.

Therefore, I'm closing this bug as a duplicate of #21114

**Closed by pnkfelix** 2018-09-13 15:08 UTC
Labels: A-borrow-checker, I-nominated, T-compiler
