### ISSUE TITLE
debuginfo: Could not find scope info for node NodeExpr(expr(25180: !0 as u32))

### ISSUE THREAD

**Issue by flier** [rust-lang/rust#33957] opened 2016-05-30 09:07 UTC
<short summary of the bug>
I tried this code:

``` rust
pub type LcoreId = u32;

pub const LCORE_ID_ANY: LcoreId = u32::MAX;

/// Return the index of the lcore starting from zero.
pub fn index(lcore_id: LcoreId) -> Option<LcoreId> {
    match lcore_id {
        LCORE_ID_ANY => id(),
        0...ffi::RTE_MAX_LCORE => {
            Some(unsafe { ffi::lcore_config[lcore_id as usize].core_index as u32 })
        }
        _ => None,
    }
}
```

I expected to see this happen: <explanation>

> code could be compiled.

Instead, this happened: <explanation>

> compiler crashed.

If we use `!0 as u32` instead of `u32::MAX`, compiler could handle it

``` rust
pub const LCORE_ID_ANY: LcoreId = !0 as u32;
```
## Meta

`rustc --version --verbose`:

```
rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: x86_64-unknown-linux-gnu
release: 1.9.0
```

Backtrace:

```
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:536
stack backtrace:
   1:     0x7f660a191330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7f660a19a68b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7f660a19a1e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7f660a15e9ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7f6608604658 - sys_common::unwind::begin_unwind::h9906658967042121576
   6:     0x7f66086045fb - errors::Handler::span_bug::h5726204624752738450
   7:     0x7f6608700e5e - trans::debuginfo::metadata::scope_metadata::h2a0278ae90797211q4A
   8:     0x7f66086f2154 - trans::debuginfo::source_loc::set_source_location::h690a0853ac3dd340QtC
   9:     0x7f6608636f28 - trans::build::ICmp::h254a25bb5c74484dAkm
  10:     0x7f6608657a0f - trans::base::compare_scalar_types::h20928078d3499826rRh
  11:     0x7f6608746d6b - trans::_match::compile_submatch_continue::h4d6caf7565396624C4M
  12:     0x7f660874328b - trans::_match::compile_submatch::hceb2a6dee08762ef2YM
  13:     0x7f660874a9a3 - trans::_match::trans_match_inner::h24a90c2c25ff28a19yN
  14:     0x7f660870e1a4 - trans::expr::trans_rvalue_dps_unadjusted::h2d372f8621d2fbb1yVE
  15:     0x7f660867c361 - trans::expr::trans_into::h7652c0f3c8b5cd0cZND
  16:     0x7f660867896d - trans::controlflow::trans_block::hde5006322ab6cf144ry
  17:     0x7f6608676fde - trans::base::trans_closure::hba0c0872f549ec52KOj
  18:     0x7f660867932c - trans::base::trans_fn::hed9c6073728147b7TZj
  19:     0x7f660867dbd2 - trans::base::trans_item::h6acb22e4cadb1a91Xnk
  20:     0x7f660869b76b - trans::base::TransItemsWithinModVisitor<'a, 'tcx>.Visitor<'v>::visit_item::h17401197a5140e35bol
  21:     0x7f6608699697 - intravisit::walk_item::h12815294816522135271
  22:     0x7f660868913f - trans::base::trans_crate::he0efa1d5417c3e0bB7k
  23:     0x7f660a6c6d84 - driver::phase_4_translate_to_llvm::h6b8ee7bea6f9aad8O1a
  24:     0x7f660a6c558c - driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::closure.29535
  25:     0x7f660a6c1e57 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.28550
  26:     0x7f660a6bbc04 - middle::ty::context::ctxt<'tcx>::create_and_enter::h16192426302205697189
  27:     0x7f660a6b86ef - driver::phase_3_run_analysis_passes::h10920926650053012691
  28:     0x7f660a68ba15 - driver::compile_input::h7ae6a86e23de0774Hca
  29:     0x7f660a67ab47 - run_compiler::hb0408bcf47642fe6mPc
  30:     0x7f660a6782c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  31:     0x7f660a18ed1b - __rust_try
  32:     0x7f660a1871fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  33:     0x7f660a678b10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  34:     0x7f660a198c59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  35:     0x7f6603442dc4 - start_thread
  36:     0x7f6609dfecec - clone
  37:                0x0 - <unknown>
```

**Comment by eddyb** [comment] 2016-06-04 13:01
This is a problem with old trans inlining the expression which has no associated scope map entries. Shouldn't be a problem in MIR trans.

**Comment by danielpclark** [comment] 2016-06-22 22:49
I'm having a similar error.

```
src/basename_for_chop.rs:21:12: 21:26 error: internal compiler error: ../src/librustc_trans/debuginfo/metadata.rs:909: debuginfo: Could not find scope info for node NodeExpr(expr(3918: '/'))
src/basename_for_chop.rs:21       Some(MAIN_SEPARATOR) => { offset = offset + 1 },
                                       ^~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:545
```

**Comment by michaelwoerister** [comment] 2016-10-31 21:23
Is this fixed now that MIR-trans has taken over completely?

**Comment by Mark-Simulacrum** [comment] 2017-05-15 15:52
Well, I cannot reproduce since there's errors in the original code (incomplete example), and currently nightly doesn't seem to produce problems, so I'm closing.

**Closed by Mark-Simulacrum** 2017-05-15 15:52 UTC
Labels: A-debuginfo

**Comment by eddyb** [comment] 2017-05-15 18:26
This can't be a problem with MIR so I agree with closing this.
