### ISSUE TITLE
--emit dep-info produces useless rules

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#23165] opened 2015-03-08 06:13 UTC
Consider a simple Rust file with the filename `test.rs`:

``` rust
fn main() {}
```

Running `rustc --emit dep-info test.rs` on that file produces a dependency file with the following contents:

```
./test.d: test.rs
```

Which is hardly useful for the purposes of actually getting the dependencies of the produced binary.

I think this is a design mistake of putting `dep-info` as an emit type and not a standalone flag. The best work-about right now is to post-process the resultant file to stick the real filename in the rule.

**Comment by SiegeLord** [comment] 2015-03-08 06:23
Another work-about is to do `rustc -Zno-analysis --emit dep-info,link test.rs`, which, despite being a bit bizzare (is it really ok for one option to ask you to emit something, and another to partially sabotage it?), does not require post-processing.

**Comment by steveklabnik** [comment] 2016-06-06 20:50
Triage: 

```
$ cat foo.rs
fn main() {}

$ rustc --emit=dep-info foo.rs 
$ cat foo.d 
foo.d: foo.rs

foo.rs:
$ rustc --version
rustc 1.9.0 (e4e8b6668 2016-05-18)
```

So, looks like no change.

**Comment by steveklabnik** [comment] 2018-09-24 18:08
Triage: no change

**Comment by Mark-Simulacrum** [comment] 2019-08-31 21:33
This seems like expected behavior to me -- if you're asking for only dep-info to be emitted, then the only file we're producing is test.d and that depend only on test.rs. If you ask for other things to be emitted along side the dep-info, we'll include those in the file as well.

I'm going to close this.

**Closed by Mark-Simulacrum** 2019-08-31 21:33 UTC
Labels: A-frontend, C-bug
