### ISSUE TITLE
install script doesn't recognize --docdir option

### ISSUE THREAD

**Issue by kamathba** [rust-lang/rust#36451] opened 2016-09-13 14:58 UTC
ran ./configure && make && sudo make install

...
gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-install-script: 
gen-install-script: validating arguments
gen-install-script: 
install: error: Option '--docdir=/usr/local/share/doc/rust' is not recognized
/home/banjo/Work/dev/rust/mk/install.mk:21: recipe for target 'install' failed
make: *** [install] Error 1

Seems to be introduced by this commit, which was merged yesterday.

commit 5e9149d73f7d2912079f08e48eb257e8a6d4f0b3
Author: orbea <ovariegata@yahoo.com>
Date:   Thu Sep 8 23:18:20 2016 -0700

    Allow setting --docdir

**Comment by nodakai** [comment] 2016-09-14 07:30
Had we tested `make install` on buildbot... #19698

**Comment by andoriyu** [comment] 2016-09-14 19:38
@m10e you can always apply patch to rust-installer before it's merged upstream.

**Comment by m10e** [comment] 2016-09-14 20:25
@andoriyu Sure, so it's definitely not urgent. I was just weighing in with a +1. Thanks for the tip though!

**Comment by orbea** [comment] 2016-09-15 17:31
Ideally the merged pull request should of only been merged when both when both pull requests were ready to be merged followed by updating the submodule. Unfortunately it did not work out that way, sorry for any issues I have caused...

**Comment by cesarb** [comment] 2016-09-26 22:46
I believe this should be tagged with the label regression-from-stable-to-nightly. @alexcrichton ?

**Comment by alexcrichton** [comment] 2016-09-27 00:49
Ah, didn't realize it was a regression, but in that case indeed!

**Comment by cesarb** [comment] 2016-09-27 02:49
@alexcrichton Yes, `make install` on nightly is completely broken. If like me you follow Rust's master by doing `./configure --prefix=... && make && make install`, you have to revert commit 5e9149d, otherwise the `make install` step will fail.

The issue is that, since that commit, `install.sh` is called by `make install` with the nonexistent option `--docdir`, and Rust's `install.sh` doesn't ignore unknown options.

**Comment by cesarb** [comment] 2016-09-27 02:52
Related: https://github.com/rust-lang/rust/issues/29632

**Comment by alexcrichton** [comment] 2016-09-27 18:02
cc @orbea this may be caused by https://github.com/rust-lang/rust/pull/36360, mind helping to investigate?

**Comment by tikue** [comment] 2016-09-30 20:40
Is there a workaround for this currently? The latest nightly ICEs on code that previously compiled (I think due to #36816) so I wanted to compile from source with the merged fix, but now I'm hitting this.

**Comment by cesarb** [comment] 2016-09-30 22:31
@tikue Yes, the workaround is to revert commit 5e9149d73f7d2912079f08e48eb257e8a6d4f0b3. There will be a conflict when reverting, but it's easy to resolve. Nothing depends on that commit (and in fact it's broken), so reverting it causes no problems.

**Comment by brson** [comment] 2016-10-05 00:27
https://github.com/rust-lang/rust/pull/36971

**Closed** 2016-10-05 12:53 UTC
Labels: P-high, regression-from-stable-to-beta, T-tools
