### ISSUE TITLE
Generate documentation for all platforms by default

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#39423] opened 2017-01-31 15:27 UTC
e.g. https://doc.rust-lang.org/std/ does not contain documentation for windows-only crates/modules and I have to read them [here](https://ollie27.github.io/rust_doc_test/std/os/windows/index.html) instead.

CC @ollie27 in case he has comments. (Thanks for providing the docs!)

**Comment by steveklabnik** [comment] 2017-01-31 17:31
This is a duplicate of https://github.com/rust-lang/rust/issues/1998. Thanks for filing! I agree that this situation isn't great, but nobody has figured out the right way to do this.

**Closed by steveklabnik** 2017-01-31 17:31 UTC
