### ISSUE TITLE
Unrelated const generic selected during type inference

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/rust#103741] opened 2022-10-29 18:08 UTC
I tried this code:

[playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c9288533bc012203b34bce763d088dfe)
```rust
#![feature(portable_simd)]

use std::simd::{Simd, SimdElement, LaneCount, SupportedLaneCount};

struct Outer<const UNRELATED_LANES: usize>;

impl<const UNRELATED_LANES: usize> Outer<UNRELATED_LANES>
where
    LaneCount<UNRELATED_LANES>: SupportedLaneCount, // comment this line, and it compiles
{
    fn test(x: Simd<usize, 4>) {
        fn foo<T, const LANES: usize>(x: Simd<T, LANES>)
        where
            T: std::simd::SimdElement,
            LaneCount<LANES>: SupportedLaneCount,
        {
            unimplemented!()
        }
        foo(x);
    }
}
```

I expected to see this happen: it compiles

Instead, this happened: it errors
```
   |
19 |         foo(x);
   |         --- ^ expected `UNRELATED_LANES`, found `4`
   |         |
   |         arguments to this function are incorrect
   |
   = note: expected struct `Simd<_, UNRELATED_LANES>`
              found struct `Simd<usize, 4>`
```

I'm not sure why `UNRELATED_LANES` is selected for the second parameter of `Simd`, when it's not used at all.  This was discovered in rust-lang/portable-simd#292.

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (758f19645 2022-10-24)
binary: rustc
commit-hash: 758f19645b8ebce61ea52d1f6672fd057bc8dbee
commit-date: 2022-10-24
host: x86_64-apple-darwin
release: 1.66.0-nightly
LLVM version: 15.0.2
```

**Comment by compiler-errors** [comment] 2022-10-29 19:28
This is probably related to https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Why.20does.20an.20explicit.20.60Into.60.20bound.20prevent.20the.20no-op.20impl.3F/near/306742934

Where-clauses are always preferred over non-where clauses -- in this case, you should be able to fix this by using a turbofish.

**Comment by calebzulawski** [comment] 2022-10-29 21:03
I'm still a little confused why it would be considered a candidate at all.  I'd understand if there were two possible ambiguous impls, but `x` is `Simd<T, 4>`... why would `foo(x)` ever try anything other than `Simd<_, 4>`?  `UNRELATED_LANES` doesn't show up in any of the types in that function.

**Comment by compiler-errors** [comment] 2022-10-29 21:22
>  why would `foo(x)` ever try anything other than `Simd<_, 4>`

This is my theory, but it seems very likely given the curcumstances --

When you call `foo::<_T, _C>(x)` (where `_T` is a type inference variable, and `_C` is a const inference variable, which are inserted during lowering), it registers the obligation `LaneCount<_C>: SupportedLaneCount` as something that needs to be solved for the program's correctness during type checking (among others).

While checking argument compatibility for `foo`, we call [`resolve_vars_with_obligations`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/fn_ctxt/struct.FnCtxt.html#method.resolve_vars_with_obligations), which attempts to solve any pending obligations. 

Therefore we try to check if `LaneCount<_C>: SupportedLaneCount` holds without having yet equated `_C` with `4` (this happens after the resolve call) -- but that obligation holds even with that unsatisfied const variable `_C` because the where-clause always has precedence over `impl`s, so we infer `_C` to be `UNRELATED_LANES`.

That might seem silly in this example, but the ordering of these operations are required for function argument inference and coercion to work properly, so it's probably going to be hard to fix without breaking other types of function calls.

Hope that makes sense.

**Comment by calebzulawski** [comment] 2022-10-29 21:40
In that case, I'm surprised that adding `LaneCount<4>: SupportedLaneCount` to the where-clause has no affect, unless that requirement is immediately removed because it can be verified without generics.

**Comment by compiler-errors** [comment] 2022-10-29 21:57
> unless that requirement is immediately removed because it can be verified without generics.

It's not filtered out immediately, though it's likely dropped due to special selection logic that filters out non-global param-env candidates.

https://github.com/rust-lang/rust/blob/5e9772042948002f9c6f60c4c81603170035fffa/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1664

**Comment by fmease** [comment] 2024-01-26 01:14
Closing as a duplicate of #24066. If you feel it's worth keeping this open anyway, I can of course reopen it.

**Closed by fmease** 2024-01-26 01:14 UTC
Labels: A-traits, T-compiler, C-bug, A-const-generics
