### ISSUE TITLE
ReSkolemized can leak into error messages

### ISSUE THREAD

**Issue by jmmk** [rust-lang/rust#13998] opened 2014-05-06 22:43 UTC
```
examples/examples.rs:46:26: 46:34 error: lifetime of function argument does not outlive the function call
examples/examples.rs:46     let f = SlotAny::new(two_args);
                                                 ^~~~~~~~
note: the function argument is only valid for lifetime ReInfer(ReSkolemized(0u, BrAnon(0u)))
error: internal compiler error: unexpected failure
note: the compiler hit an unexpected failure path. this is a bug.
note: we would appreciate a bug report: http://static.rust-lang.org/doc/master/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' failed at 'assertion failed: !ty::type_needs_infer(ty)', /Users/rustbuild/src/rust-buildbot/slave/nightly-mac/build/src/librustc/middle/typeck/mod.rs:251
stack backtrace:
   1:        0x10c3c9a64 - rt::backtrace::imp::write::habc56a229da3d9445Ea::v0.11.pre
   2:        0x10c31e00e - rt::unwind::begin_unwind_inner::he30d2051ed995551bfa::v0.11.pre
   3:        0x10c31d4c7 - rt::unwind::begin_unwind_fmt::h6e44c556d6cd8deelea::v0.11.pre
   4:        0x109914c56 - middle::typeck::write_ty_to_tcx::h2b827da2c5dd52b30fu::v0.11.pre
   5:        0x10991135e - middle::typeck::check::writeback::resolve_type_vars_for_node::h56adc403301d71a1TS1::v0.11.pre
   6:        0x10991583a - middle::typeck::check::writeback::visit_expr::hf20f6553222bc96ft51::v0.11.pre
   7:        0x109915b3d - middle::typeck::check::writeback::visit_expr::hf20f6553222bc96ft51::v0.11.pre
   8:        0x109917a6e - middle::typeck::check::writeback::visit_local::h60d5d5890d438f00Ja2::v0.11.pre
   9:        0x109915570 - middle::typeck::check::writeback::visit_stmt::h57274c9f7367d7c8T41::v0.11.pre
   10:        0x109917023 - visit::walk_block::h4813911114547969337::v0.11.pre
  11:        0x10991a312 - middle::typeck::check::writeback::resolve_type_vars_in_fn::h648841adac5a5f12yn2::v0.11.pre
  12:        0x10996ae17 - middle::typeck::check::check_bare_fn::h727d76d1a8c0577cx36::v0.11.pre
  13:        0x109962d4e - middle::typeck::check::check_item::hb3e06af45cad1763Uz7::v0.11.pre
  14:        0x10996ab2d - middle::typeck::check::check_item_types::h4794d86cd018c594P26::v0.11.pre
  15:        0x109aad54f - util::common::time::h13076619411820452536::v0.11.pre
  16:        0x109aac47d - middle::typeck::check_crate::h979c5052f97482abIzu::v0.11.pre
  17:        0x109eb5b21 - driver::driver::phase_3_run_analysis_passes::ha118c3d47f9c07e1Ssf::v0.11.pre
  18:        0x109ebb572 - driver::driver::compile_input::h09b012d109a97ff53Rf::v0.11.pre
  19:        0x109ee1ba7 - run_compiler::h1896b068d115fa30akn::v0.11.pre
  20:        0x109ef9afd - main_args::closure.91270
  21:        0x109ef7e92 - monitor::closure.91145
  22:        0x109ef2a7b - task::TaskBuilder::try::closure.90911
  23:        0x109665d6c - task::spawn_opts::closure.7135
  24:        0x10c3bfa68 - rt::task::Task::run::closure.40347
  25:        0x10c3cec4c - rust_try
  26:        0x10c3bf8e7 - rt::task::Task::run::ha1efa04543646d12L57::v0.11.pre
  27:        0x109665bef - task::spawn_opts::closure.7107
  28:        0x10c3c8436 - rt::thread::thread_start::h2d864941e9d800a8YK8::v0.11.pre
  29:     0x7fff8ce75899 - _pthread_body
  30:     0x7fff8ce7572a - _pthread_struct_init
```

**Comment by nham** [comment] 2015-06-04 00:16
The error message for this code is looking much nicer:

```
13998.rs:24:22: 24:30 error: mismatched types:
 expected `fn(&_)`,
    found `fn(_) {two_args}`
(expected concrete lifetime,
    found bound lifetime parameter ) [E0308]
13998.rs:24     let f = Bar::new(two_args);
                                 ^~~~~~~~
13998.rs:24:22: 24:30 help: run `rustc --explain E0308` to see a detailed explanation
```

I think there's still room for improvement here. Perhaps the E0308 explanation could give an example and explain what the problem is (and what "concrete lifetime" and "bound lifetime parameter" mean, possibly)

**Comment by arielb1** [comment] 2015-08-18 18:36
crappy error message still possible:
```Rust
fn foo(f: for<'a,'b> fn(&'a ()) -> &'a &'b ()) {
    bar(f);
}

fn bar(f: for<'a,'b> fn(&'b ()) -> &'a &'b ()) {
}

fn main() {}
```

gives

```
<anon>:2:9: 2:10 error: mismatched types:
 expected `fn(&'b ()) -> &'a &'b ()`,
    found `fn(&'a ()) -> &'a &'b ()`
(expected concrete lifetime,
    found bound lifetime parameter 'a) [E0308]
<anon>:2     bar(f);
                 ^
<anon>:2:9: 2:10 help: see the detailed explanation for E0308
note: expected concrete lifetime is lifetime ReSkolemized(0, BrNamed(DefId { krate: 0, node: 31 }, 'b(64)))
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by shepmaster** [comment] 2016-08-23 01:54
Continuing on to 2016:

```rust
struct RunLoop<'a> {
    marker: &'a u8,
}

struct MyContext<'a> {
    rl: &'a mut RunLoop<'a>,
}

fn run<'a>(rl: &'a mut RunLoop<'a>) {
    let mut ctxt = MyContext { rl: rl };
}

fn register(func: fn(&mut RunLoop)) {}

fn main() {
    register(run);
}
```

```
error: mismatched types [--explain E0308]
  --> src/main.rs:16:14
16 |>     register(run);
   |>              ^^^ expected concrete lifetime, found bound lifetime parameter
note: expected type `fn(&mut RunLoop<'_>)`
note:    found type `fn(&'a mut RunLoop<'a>) {run}`
note: expected concrete lifetime is lifetime ReSkolemized(0, BrAnon(0))
```

**Comment by nathanaeljones** [comment] 2016-10-21 02:49
Still around

```
error[E0308]: mismatched types
  --> src/flow/nodes/scale_render.rs:78:13
   |
78 |             f
   |             ^ expected concrete lifetime, found bound lifetime parameter 
   |
   = note: expected type `fn(&mut flow::definitions::OpCtxMut<'_>, petgraph::graph::NodeIndex)`
   = note:    found type `fn(&'a mut flow::definitions::OpCtxMut<'a>, petgraph::graph::NodeIndex) {flow::nodes::scale_render::scale_def::f}`
   = note: expected concrete lifetime is lifetime ReSkolemized(0, BrAnon(0))
```

**Comment by arielb1** [comment] 2017-02-24 21:36
Updated for 1.17:
```Rust
fn foo(f: for<'a,'b> fn(&'a (), &'b ()) -> &'a &'b ()) {
    bar(f);
}

fn bar(f: for<'a,'b> fn(&'b (), &'a ()) -> &'a &'b ()) {
}

fn main() {}
```

**Comment by estebank** [comment] 2017-09-13 19:57
[Current output is](https://play.rust-lang.org/?gist=e59aa43cb354642893340da16aed7f5f&version=nightly):

```
error[E0308]: mismatched types
 --> src/main.rs:2:9
  |
2 |     bar(f);
  |         ^ expected concrete lifetime, found bound lifetime parameter 'b
  |
  = note: expected type `fn(&'b (), &'a ()) -> &'a &'b ()`
             found type `fn(&'a (), &'b ()) -> &'a &'b ()`
```

It no longer contains the following:

```
= note: expected concrete lifetime is lifetime ReSkolemized(1, BrNamed(CrateNum(0):DefIndex(2147483665), 'a(85)))
```
which is present in stable/beta. This *might* be enough for us to close this ticket. I don't know if suppressing that note is enough to make this output reasonable. In this case it is relatively clear because the two `fn`s are almost identical so it is easy to see the discrepancy visually, but I worry that in more complex errors it wouldn't be as clear...

**Comment by mark-i-m** [comment] 2019-10-09 23:04
This can still happen:

https://github.com/rust-lang/rust/blob/20cc75272619cc452e3ae6c131e61974f6aa9929/src/librustc/infer/error_reporting/mod.rs#L138-L145

**Comment by mark-i-m** [comment] 2019-10-10 03:25
@estebank This happens on master with nll enabled, e.g. this ui test:

https://github.com/rust-lang/rust/blob/ece4977138a8eda96c234982e482fb43f67f1bee/src/test/ui/async-await/issues/issue-63388-1.nll.stderr#L1-L7

Notice: `captures lifetime '_#22r `

**Comment by estebank** [comment] 2019-10-10 20:40
I feel that even though the general problem is the same as originally reported, it is different enough that it would have warranted making a new ticket.

That being said, thanks for digging up a relevant test to keep track of the fix.

**Comment by steveklabnik** [comment] 2020-09-18 17:38
Triage: this FIXME is still here https://github.com/rust-lang/rust/blob/41dc3942eb33e8e882b6e4782a9bd9d2b8970647/compiler/rustc_infer/src/infer/error_reporting/mod.rs#L103-L110

**Comment by estebank** [comment] 2022-07-26 18:35
https://github.com/rust-lang/rust/blob/master/src/test/ui/async-await/issues/issue-63388-1.stderr no longer shows a repro, but https://github.com/rust-lang/rust/blob/8cc87250efc5b5fcec85d43eaa73f7a9acc2198a/src/test/ui/nll/closure-requirements/escape-argument-callee.stderr does

**Comment by estebank** [comment] 2023-01-05 00:48
I believe that the only cases where we still show these is when using `-Zverbose`. Do we have any counter-example? Otherwise I'm tempted at just closing this.

**Comment by estebank** [comment] 2023-01-19 16:40
Steve's linked code is still there, but changing it has no effect anywhere in the test suite. This is not positive proof of anything, but I believe it might be code only accessible through `-Zverbose`. I will go ahead and close this.

**Closed by estebank** 2023-01-19 16:40 UTC
Labels: C-enhancement, A-diagnostics, T-compiler, D-papercut
