### ISSUE TITLE
cl.exe handling of llvm\include broken for VS 2019?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#60507] opened 2019-05-03 13:40 UTC
I am attempting to bootstrap rust atop Visual Studio 2019 Community Edition.

I have no `config.toml`, and am doing the build from the `rust.git` root directory, on this version:

```
commit 22fa4bb0ebdfe9fcd7962f1fa6e758c036c878e6 (HEAD -> master, origin/master, origin/HEAD)
Merge: 6c22051411 0a386baa5f
Author: bors <bors@rust-lang.org>
Date:   Fri Apr 19 09:57:26 2019 +0000

    Auto merge of #60063 - spastorino:place2_2, r=oli-obk

    Convert Place unroll to a proper iterator

    r? @oli-obk
```

From `x.py build`, during the build step for `rustc_llvm`, I am getting the following error:

```
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MT" "/O2" "-IC:\\Users\\Felix" "Klock\\Dev\\rust\\build\\x86_64-pc-windows-msvc\\llvm\\include" "/EHs-c-" "/GR-" "-D_CRT_SECURE_NO_DEPRECATE" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_NONSTDC_NO_DEPRECATE" "-D_CRT_NONSTDC_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-DUNICODE" "-D_UNICODE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "/DLLVM_COMPONENT_AARCH64" "/DLLVM_COMPONENT_ARM" "/DLLVM_COMPONENT_ASMPARSER" "/DLLVM_COMPONENT_BITREADER" "/DLLVM_COMPONENT_BITWRITER" "/DLLVM_COMPONENT_HEXAGON" "/DLLVM_COMPONENT_INSTRUMENTATION" "/DLLVM_COMPONENT_INTERPRETER" "/DLLVM_COMPONENT_IPO" "/DLLVM_COMPONENT_LINKER" "/DLLVM_COMPONENT_LTO" "/DLLVM_COMPONENT_MCJIT" "/DLLVM_COMPONENT_MIPS" "/DLLVM_COMPONENT_MSP430" "/DLLVM_COMPONENT_NVPTX" "/DLLVM_COMPONENT_POWERPC" "/DLLVM_COMPONENT_SPARC" "/DLLVM_COMPONENT_SYSTEMZ" "/DLLVM_COMPONENT_X86" "/DLLVM_RUSTLLVM" "/FoC:\\Users\\Felix Klock\\Dev\\rust\\build\\x86_64-pc-windows-msvc\\stage0-codegen\\x86_64-pc-windows-msvc\\release\\build\\rustc_llvm-73d9838d017541d9\\out\\../rustllvm\\PassWrapper.o" "/c" "../rustllvm/PassWrapper.cpp"
cargo:warning=cl : Command line warning D9024 : unrecognized source file type 'Klock\Dev\rust\build\x86_64-pc-windows-msvc\llvm\include', object file assumed
cargo:warning=cl : Command line warning D9027 : source file 'Klock\Dev\rust\build\x86_64-pc-windows-msvc\llvm\include' ignored
PassWrapper.cpp
C:\Users\Felix Klock\Dev\rust\src\rustllvm\rustllvm.h(1): fatal error C1083: Cannot open include file: 'llvm-c/BitReader.h': No such file or directory
exit code: 2

```

**Comment by ollie27** [comment] 2019-05-03 17:07
This looks like a duplicate of #56650.

**Closed by ollie27** 2019-05-03 17:07 UTC
Labels: A-LLVM, A-rustbuild, C-bug, O-windows-msvc
