### ISSUE TITLE
[ICE] Compiling the `select` crate

### ISSUE THREAD

**Issue by Razican** [rust-lang/rust#46840] opened 2017-12-19 15:52 UTC
Dear community, I tried to run the following command in a code I'm writing:

```
cargo test --verbose --jobs 1 --release
```

And once it gets to the `select` 0.4.2 crate, I get this error (with its backtrace:

```
Running `rustc --crate-name select /path/to/.cargo/registry/src/github.com-1ecc6299db9ec823/select-0.4.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=41536284123e2f65 -C extra-filename=-41536284123e2f65 --out-dir /path/to/target/release/deps -L dependency=/path/to/target/release/deps --extern html5ever=/path/to/target/release/deps/libhtml5ever-e6a9fd68468b9aa4.rlib --extern bit_set=/path/to/target/release/deps/libbit_set-9e3f9fcab576f1bf.rlib --cap-lints allow`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (dc39c3169 2017-12-17) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', /checkout/src/librustc_trans/type_.rs:293:8
stack backtrace:
   0:     0x7fa27770f2cb - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h1926165e1b36cfb3
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fa2777071fe - std::sys_common::backtrace::print::ha9b03f8537574de7
                               at /checkout/src/libstd/sys_common/backtrace.rs:68
                               at /checkout/src/libstd/sys_common/backtrace.rs:57
   2:     0x7fa277718590 - std::panicking::default_hook::{{closure}}::ha761f65ed43616d1
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7fa27771828b - std::panicking::default_hook::hbf975d28f2fde606
                               at /checkout/src/libstd/panicking.rs:391
   4:     0x7fa277718a6b - std::panicking::rust_panic_with_hook::hed519d1046029849
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7fa2777188be - std::panicking::begin_panic::h51fcb09f08730597
                               at /checkout/src/libstd/panicking.rs:538
   6:     0x7fa27771882a - std::panicking::begin_panic_fmt::h3d4f37c176de3801
                               at /checkout/src/libstd/panicking.rs:522
   7:     0x7fa276d0d1d2 - rustc_trans::type_::Type::padding_filler::h890d245371d9b2ff
   8:     0x7fa276d89232 - rustc_trans::type_of::struct_llfields::ha8f978202a9ade7b
   9:     0x7fa276d3eaca - <rustc::ty::layout::TyLayout<'tcx> as rustc_trans::type_of::LayoutLlvmExt<'tcx>>::llvm_type::ha277e14e0334c63b
  10:     0x7fa276d3eceb - <rustc::ty::layout::TyLayout<'tcx> as rustc_trans::type_of::LayoutLlvmExt<'tcx>>::llvm_type::ha277e14e0334c63b
  11:     0x7fa276d827b2 - rustc_trans::abi::FnType::llvm_type::hc4c6f88313a9f076
  12:     0x7fa276de0963 - rustc_trans::declare::declare_fn::h7dee317fe36eb035
  13:     0x7fa276dab3f0 - rustc_trans::trans_item::predefine_fn::he92eca9771e73247
  14:     0x7fa276d1cb34 - rustc_trans::trans_item::TransItemExt::predefine::h12a457a04501985d
  15:     0x7fa276cee344 - rustc_trans::base::compile_codegen_unit::hca6950c887a49133
  16:     0x7fa2737b1ce1 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::compute_result::h938a8535660b3359
  17:     0x7fa2736a400b - rustc::dep_graph::graph::DepGraph::with_task_impl::ha66325b12aaf0b82
  18:     0x7fa27339b501 - rustc_errors::Handler::track_diagnostics::hc8e1eae80fd70636
  19:     0x7fa2732654c0 - rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check::h0ff68d26efe3fb80
  20:     0x7fa2737b1d8f - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force::hf02f109f2a85248a
  21:     0x7fa2737b2778 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get::hae32d3ca6a777bab
  22:     0x7fa27355665e - rustc::ty::maps::TyCtxtAt::compile_codegen_unit::h42b98ce49b758926
  23:     0x7fa2732c60b9 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit::he36118865284d843
  24:     0x7fa276cec539 - rustc_trans::base::trans_crate::h3e62c0b92edbfaa1
  25:     0x7fa276d89696 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::hddcf3b4bd77449a5
  26:     0x7fa277b14d8d - rustc_driver::driver::phase_4_translate_to_llvm::h8f75cfac6818aba2
  27:     0x7fa277b64512 - rustc_driver::driver::compile_input::{{closure}}::hb499ea42753f8393
  28:     0x7fa277b5d241 - <std::thread::local::LocalKey<T>>::with::hb92f749835d8a4c9
  29:     0x7fa277b5f926 - <std::thread::local::LocalKey<T>>::with::hed06138de0c2dcea
  30:     0x7fa277bb92fc - rustc::ty::context::TyCtxt::create_and_enter::he394799bb6339b54
  31:     0x7fa277b09aad - rustc_driver::driver::compile_input::h5409c0e3df4029d1
  32:     0x7fa277b90f88 - rustc_driver::run_compiler::hf7ab608cab285f60
  33:     0x7fa277abe3e1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb46c15b4e473f11a
  34:     0x7fa27774da5e - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:101
  35:     0x7fa277a975f2 - <F as alloc::boxed::FnBox<A>>::call_box::h16e0ae6fb43d31a3
  36:     0x7fa277709b77 - std::sys_common::thread::start_thread::h8f325f936df43fbb
                               at /checkout/src/liballoc/boxed.rs:827
  37:     0x7fa277724288 - std::sys::unix::thread::Thread::new::thread_start::hec2e96890ab26caf
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  38:     0x7fa27140c608 - start_thread
  39:     0x7fa2773ede6e - __clone
  40:                0x0 - <unknown>

error: Could not compile `select`.

Caused by:
  process didn't exit successfully: `rustc --crate-name select /path/to/.cargo/registry/src/github.com-1ecc6299db9ec823/select-0.4.2/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=41536284123e2f65 -C extra-filename=-41536284123e2f65 --out-dir /path/to/target/release/deps -L dependency=/path/to/target/release/deps --extern html5ever=/path/to/target/release/deps/libhtml5ever-e6a9fd68468b9aa4.rlib --extern bit_set=/path/to/target/release/deps/libbit_set-9e3f9fcab576f1bf.rlib --cap-lints allow` (exit code: 101)
```

Let me know if I could help you with further information.

**Comment by arielb1** [comment] 2017-12-19 22:45
duplicate of #46769, should be fixed in the next nightly.

**Closed by arielb1** 2017-12-19 22:45 UTC
Labels: I-ICE
