### ISSUE TITLE
make check fails on c-dynamic-dylib on windows

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rust#28019] opened 2015-08-26 15:59 UTC
Running make check fails with this error message when run in on windows.

```
------ stderr ---------------------------------------------
error: linking with `gcc` failed: exit code: 1
note: "gcc" "-Wl,--enable-long-section-names" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-static-libgcc" "-m64" "-L" "C:\Users\Markus\rust\x86_64-pc-windows-gnu\stage2\bin\rustlib\x86_64-pc-windows-gnu\lib" "C:/Users/Markus/rust/x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib\foo.o" "-o" "C:/Users/Markus/rust/x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib\foo.dll" "C:/Users/Markus/rust/x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib\foo.metadata.o" "-L" "C:\Users\Markus\rust\x86_64-pc-windows-gnu\stage2\bin\rustlib\x86_64-pc-windows-gnu\lib" "-l" "std-d8ace771" "-L" "C:/Users/Markus/rust/x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib" "-L" "C:\Users\Markus\rust\x86_64-pc-windows-gnu\stage2\bin\rustlib\x86_64-pc-windows-gnu\lib" "-L" "C:\Users\Markus\rust\src\test\run-make\c-dynamic-dylib\.rust\bin\x86_64-pc-windows-gnu" "-L" "C:\Users\Markus\rust\src\test\run-make\c-dynamic-dylib\bin\x86_64-pc-windows-gnu" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-l" "cfoo" "-l" "ws2_32" "-l" "userenv" "-l" "advapi32" "-shared" "-l" "compiler-rt"
note: C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcfoo
collect2.exe: error: ld returned 1 exit status

error: aborting due to previous error
make[1]: *** [all] Error 101

------        ---------------------------------------------

/c/Users/Markus/rust/mk/tests.mk:1070: recipe for target 'x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib-2-T-x86_64-pc-windows-gnu-H-x86_64-pc-windows-gnu.ok' failed
make: *** [x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib-2-T-x86_64-pc-windows-gnu-H-x86_64-pc-windows-gnu.ok] Error 2
```

I don't get why gcc is unable to find cfoo as the library file exists in `C:/Users/Markus/rust/x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib` and `"-L" "C:/Users/Markus/rust/x86_64-pc-windows-gnu/test/run-make/c-dynamic-dylib"` is passed to gcc.

Might be related to https://github.com/rust-lang/rust/issues/18733

**Comment by vadimcn** [comment] 2015-08-29 01:02
Does `set MSYSTEM=MINGW32` help?

**Comment by Marwes** [comment] 2015-08-29 09:22
Running `MSYSTEM=MINGW32 make check` does work.

**Comment by vadimcn** [comment] 2015-09-14 06:09
[Exaplanataion]
1. Rust's make-test makefile looks for the `MINGW` substring in `uname` output to identify Windows and gets very confused when it doesn't find one.
2. By default MSYS2's `uname` identifies the host system as `MSYS_NT-X.Y`, (e.g. `MSYS_NT-6.3`).  
However, for compatibility with mingw, this prefix may be overridden by setting `MSYSTEM` environment variable: 
```
C:\>uname
MSYS_NT-6.3
C:\>set MSYSTEM=MINGW32&uname
MINGW32-NT-6.3
```

**Comment by Diggsey** [comment] 2015-09-14 15:52
It depends how you start the msys terminal: if you run `msys2_shell.bat`, then `uname` returns `MSYS_NT-X.Y` as you say, but you *should* be starting it by running `mingw32_shell.bat` or `mingw64_shell.bat` in which case `uname` will give the correct output: `MINGW64_NT-X.Y` or `MINGW32_NT-X.Y`. This is needed to make sure that the correct gcc is used as well.

**Comment by nodakai** [comment] 2016-04-04 04:26
Then shouldn't configure abort upon finding uname=MSYS*, perhaps with a message pointing to this ticket?

**Comment by steveklabnik** [comment] 2019-03-16 14:52
Triage: I'm not an mys user, and the build system has been completely re-written since then. Does anyone know of reproduction instructions for this bug today?

**Comment by mati865** [comment] 2020-09-08 11:41
Test no longer use `uname` to distinguish Windows, I think we can close this issue.

**Closed** 2020-09-08 15:29 UTC
Labels: A-rustbuild, C-bug, O-windows
