### ISSUE TITLE
The _popcnt64 intrinsic generates a jmp before popcnt on x86_64

### ISSUE THREAD

**Issue by dbdr** [rust-lang/rust#60625] opened 2019-05-08 05:23 UTC
Calling the `std::arch::x86_64::_popcnt64` intrinsic generates a jmp to `core::core_arch::x86_64::abm::_popcnt64`, which contains the actual popcnt instruction.

Source:
```rust
#[cfg(target_arch = "x86_64")]
pub fn popcnt64(x: u64) -> i32 {
    unsafe {
        std::arch::x86_64::_popcnt64(x as i64)
    }
}
```
Generated:
```asm
core::core_arch::x86_64::abm::_popcnt64:
        popcnt  rax, rdi
        ret

example::popcnt64:
        jmp     core::core_arch::x86_64::abm::_popcnt64
```
[Godbolt](https://godbolt.org/z/IXlz0L)

Unless I am missing something, this seems unnecessary and less efficient.

The expected code is generated when `-C target-feature=+popcnt` is added:
```asm
example::popcnt64:
        popcnt  rax, rdi
        ret
```

However, the point of using the intrinsic is to be able to generate popcnt in a binary that does not assume that the CPU supports it, and to select which version to call at runtime (otherwise it's easier to just use `count_ones`).

Tested on 1.34.0 and nightly.

**Comment by nagisa** [comment] 2019-05-08 18:04
Not a bug, duplicate of https://github.com/rust-lang/rust/issues/54353.

**Closed by nagisa** 2019-05-08 18:04 UTC
Labels: C-bug, I-slow, O-x86_64, T-compiler

**Comment by nagisa** [comment] 2019-05-08 18:09
As a side note, I recommend using `count_ones` inherent method available on most of integer types.
