### ISSUE TITLE
broken links in docs for String

### ISSUE THREAD

**Issue by lucasem** [rust-lang/rust#44947] opened 2017-09-30 16:14 UTC
All `String` methods which come from the borrowed `&str` have broken links. e.g. `char` in [`std::string::String::chars`](https://doc.rust-lang.org/std/string/struct.String.html#method.chars) (which is basically `std::str::chars`).

I'd fix it myself, but I'm not sure what the approach should be so that both docs pages, for `String` and for the primitive `str`, would work. Maybe there's a planned rustdoc feature which could help resolve this?

**Comment by steveklabnik** [comment] 2017-09-30 16:41
This is a duplicate of https://github.com/rust-lang/rust/issues/32130; thank you for filing! It's a tricky bug, and we're not 100% sure how to solve it yet. https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md will *probably* fix it, we'll see!

**Closed by steveklabnik** 2017-09-30 16:41 UTC
