### ISSUE TITLE
Matching on a struct variant enum

### ISSUE THREAD

**Issue by nicolaction** [rust-lang/rust#40666] opened 2017-03-20 09:17 UTC
I have been playing with rust enums recently, but I found that I can't seem to make them work the way I expect.

I defined struct variants for an enum:

```rust
pub enum Entity {
    Character {
        money: f64,
        ....
    },
    ...
}
```

And I want to match on them. If I match on self, in the module, I get this:

```rust
match self {
    Entity::Character(entity) => {
        entity.money = ...
```

But I get the following error message: 

> error[E0532]: expected tuple struct/variant, found struct variant `types::Entity::Character`

What to do? Am I doing this wrong?

PS: I know I can destructure the content of the enum, but I want to use it as if it was defined locally with the correct variant.

**Comment by rkruppe** [comment] 2017-03-20 14:30
The syntax you want would be very inconsistent. Besides, this is already possible [using `@`](https://doc.rust-lang.org/book/patterns.html#bindings):

```
match self {
    entity @ Entity::Character { .. } => {
        entity.money = ...
```

**Comment by petrochenkov** [comment] 2017-03-20 14:45
I suspect that @nicolaction wants something like https://github.com/rust-lang/rfcs/pull/1450 and `entity` is expected to have such variant type, and `money` is not a field of `Entity`, but a field of `Entity::Character` variant type.

So this issue is an RFC material and kinda duplicate of https://github.com/rust-lang/rfcs/pull/1450, and not a bug, so it should probably be closed.

>What to do? Am I doing this wrong?
>PS: I know I can destructure the content of the enum, but I want to use it as if it was defined locally with the correct variant.

Destructuring is not a bad variant
```rust
match self {
    Entity::Character { money, .. } => { .... }
}
```
but if you don't want to use it, then you can define a separate new type for characters:
```rust
struct Character { money: f64, .... }

enum Entity {
    Character(Character),
    ....
}

match self {
    Entity::Character(ref mut ch) { ch.money = .... }
}
```

**Closed by petrochenkov** 2017-03-20 14:45 UTC

**Comment by nicolaction** [comment] 2017-03-20 16:19
Thank you, I didn't know about @ bindings.
I tried to use:
```rust
&mut entity @ Entity::Character{..} => {
```
But the binding seems to occur before the variant selection somehow, so entity is an Entity, not an Entity::Character.

I think I will have to use a dedicated struct for each struct variant.

**Comment by 0X1A** [comment] 2018-12-07 00:05
This is an old issue, but I believe the match expression @nicolaction wanted was:
```rust
match self {
    Entity::Character { mut entity } => {
        entity.money = ...
```

**Comment by johnbchron** [comment] 2023-05-08 08:10
For posterity, the example provided by @0X1A adapted to the original problem without introducing a separate type for the fields of a given variant is as follows:
```rs
pub enum Entity {
    Character {
        money: f64,
        ....
    },
    ...
}
```
```rs
match self {
    Entity::Character {&mut money, ..} => {
        money = ...
```
