### ISSUE TITLE
Internal Compile Error on array without colon

### ISSUE THREAD

**Issue by bftjoe** [rust-lang/rust#23835] opened 2015-03-29 16:26 UTC
fn main() {
    let xs[i32; 1] = [1];
}

2:9: 2:11 error: internal compiler error: ident only path should have been covered already
2     let xs[i32; 1] = [1];
                 ^~
note: the compiler unexpectedly panicked. this is a bug.

**Comment by rprichard** [comment] 2015-03-29 16:34
This looks like a duplicate of #22972 (and #23597).

**Closed** 2015-03-29 17:40 UTC
Labels: I-ICE
