### ISSUE TITLE
WASM doesn't work on NixOS

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/rust#51304] opened 2018-06-02 15:44 UTC
I can't compile WASM on NixOS, using the binaries from Rustup, patched (with `patchelf`) to work on NixOS.

The problem seems to be that some files aren't linked properly. Comparing with wasm code produced on Ubuntu with the same version of Rustc shows that the wasm I get is smaller and contains many references to a variable named `env`, along with functions supposedly imported from `env`.

This sounds a lot like a link problem, but I don't know how to debug these, since the temporary files produced by Rustc before calling `lld` seem to get wiped off as soon as `lld` finishes its job.

Some NixOS-specific problems include the path to `lld`, but it seems the patched version supplied by rustup is the first in the path (at least from the command-line, I hope `rustc` looks for its linker in the same order as the shell).

**Comment by ben0x539** [comment] 2018-08-03 16:30
fwiw, in a `nix-shell -p rustup` shell, I can follow the instructions from eg. https://rustwasm.github.io/book/game-of-life/setup.html and get a working browser demo. With (targets-overridden) rust from the mozilla overlay, I get the behavior you're describing here/in mozilla/nixpkgs-mozilla#92.

**Comment by bendlas** [comment] 2019-05-15 16:06
I think this might be a good starting point https://github.com/WebGHC/wasm-cross/blob/master/cross.nix

**Comment by alexcrichton** [comment] 2019-12-16 22:32
I'm going to close this because it seems sort of unclear on how to reproduce, and lots in the wasm world has changed in the meantime. This was likely caused by version mismatches in tooling and is unlikely to be a rustc issue as well.

**Closed by alexcrichton** 2019-12-16 22:32 UTC
Labels: A-linkage, C-bug, O-NixOS, O-wasm, T-compiler
