### ISSUE TITLE
rustc internet compiler error after going stable (1.9) -> beta -> stable

### ISSUE THREAD

**Issue by rory** [rust-lang/rust#33978] opened 2016-05-31 09:38 UTC
I was using rust stable (1.9), then did a `multirust override beta` to try out the fs_time feature, but a library dependency didn't work (`simple_parallel` which depends on `crossbeam`), so I switched back to stable, with `multirust override stable` and got this error when doing a `cargo build`.

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0 }', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7f3dc049b570 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7f3dc04a8c6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7f3dc04a880c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7f3dc046d79f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7f3dc046f888 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7f3dc0498d81 - rust_begin_unwind
   7:     0x7f3dc04f285f - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7f3db7a25a0b - core::result::unwrap_failed::h82c81d60621f70bd
   9:     0x7f3db7a2597e - rbml::Doc::as_str_slice::hd88d17b04c3f2cca
  10:     0x7f3dbe27fa62 - rustc_metadata::decoder::maybe_get_crate_hash::h1c0939ce4d9ba236
  11:     0x7f3dbe2b301b - rustc_metadata::loader::Context::extract_one::h56453781fb65bffa
  12:     0x7f3dbe2aadb5 - rustc_metadata::loader::Context::find_library_crate::h30ea71d32623d713
  13:     0x7f3dbe290f96 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
  14:     0x7f3dbe28fe1f - rustc_metadata::creader::CrateReader::resolve_crate::h98decfaedbcfe12a
  15:     0x7f3dbe2916eb - rustc_metadata::creader::CrateReader::resolve_crate_deps::_$u7b$$u7b$closure$u7d$$u7d$::h4bd0eba4f8aa0bca
  16:     0x7f3dbe29149c - _<std..collections..HashMap<K, V, S> as std..iter..FromIterator<(K, V)>>::from_iter::h7ccc89cd3e9da036
  17:     0x7f3dbe28d1ba - rustc_metadata::creader::CrateReader::register_crate::hdfd966766b932c68
  18:     0x7f3dbe292562 - rustc_metadata::creader::CrateReader::read_extension_crate::hb0997de4fb0918fb
  19:     0x7f3dbe29485e - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  20:     0x7f3dbe2b80e8 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  21:     0x7f3dbe2b6eea - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  22:     0x7f3dc09d19ec - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  23:     0x7f3dc09b809a - rustc_driver::driver::compile_input::h6491aaddd9e61258
  24:     0x7f3dc09a04e4 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  25:     0x7f3dc099d941 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  26:     0x7f3dc0498d0b - __rust_try
  27:     0x7f3dc0498c9d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  28:     0x7f3dc099e18a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  29:     0x7f3dc04a6e04 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  30:     0x7f3db8e69183 - start_thread
  31:     0x7f3dc00f437c - clone
  32:                0x0 - <unknown>


```

    $ rustc --version
    rustc 1.9.0 (e4e8b6668 2016-05-18)

**Comment by rory** [comment] 2016-05-31 09:54
For the record, I did a `cargo clean` and now this problem has been fixed for me.

**Comment by retep998** [comment] 2016-05-31 10:27
Probably dupe of https://github.com/rust-lang/rust/issues/33778

**Comment by nagisa** [comment] 2016-05-31 12:50
It is.

**Closed by nagisa** 2016-05-31 12:50 UTC
