### ISSUE TITLE
Azure Pipelines sometimes doesn't report back its status to GitHub

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#63513] opened 2019-08-13 08:09 UTC
It happened a few times that Azure Pipelines doesn't report back the build status to GitHub, causing the commits to be in a permament "in progress" state. For example, a few times it happened yesterday:

* https://github.com/rust-lang/rust/runs/191033192
* https://github.com/rust-lang/rust/runs/191276265

Any idea why this is happening @rylev @ethomson?

cc @RalfJung

**Comment by Mark-Simulacrum** [comment] 2019-08-13 10:32
FWIW, I've also seen the checks just not starting, possibly after force pushing.

**Comment by pietroalbini** [comment] 2019-08-13 15:41
Happened again for a bors merge on rustc: https://github.com/rust-lang/rust/runs/192177675

**Comment by lkillgore** [comment] 2019-08-13 21:44
Hi @pietroalbini, I see from our telemetry the check-runs issue.  I'm tracking down the problem with GitHub now.  I'll reply back on this ticket when I have something more to report.  Apologies for the inconvenience.

**Comment by lkillgore** [comment] 2019-08-14 20:29
Quick update: I've made a few changes that seem to have mitigated the problem for now (I'm not seeing the error in our telemetry for your account).  I'm still working at verifying the root cause.

**Comment by lkillgore** [comment] 2019-08-15 19:29
Quick update: I think we found the root cause, and we have a fix, which should roll out over the next few days.  It appears the last mitigation I mentioned didn't fix the problem completely; our telemetry reports that your account had additional failures afterward.  I made another change, and I haven't noticed this problem on your account for the last few hours, so I think you should be good-to-go.  Please post back here if you notice any check-runs failures over the next few days.  I apologize for the inconvenience this caused.

**Comment by rylev** [comment] 2021-01-14 17:58
Closing this since Azure Pipelines is no longer being used.

**Closed by rylev** 2021-01-14 17:58 UTC
Labels: A-spurious, C-bug, T-infra
