### ISSUE TITLE
armv7 rustc panic

### ISSUE THREAD

**Issue by ngc0202** [rust-lang/rust#50215] opened 2018-04-25 07:32 UTC
Had this happen after wrestling with a couple of my raspberry pis failing to compile my project which has been compiling fine in the past. Unfortunately, this happened once out of about 20 retries to compile and I have not been able to reproduce. The problem occurs not only on the toml crate as in this paste, but with others such as syn, proc-macro2, serde_derive, which gives me the impression this has something to do with the procedural macros.

```
error: Could not compile `toml`.
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: librustc/ty/subst.rs:140: impossible case reached

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:535:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0 (84203cac6 2018-03-25) running on armv7-unknown-linux-gnueabihf

error: Could not compile `proc-macro2`.

```

**Comment by oli-obk** [comment] 2018-04-25 21:12
Could be miri related. The compilers at the end of march had a lot of bugs in that direction. Coun you try providing a backtrace or moving to a newer nightly?

**Comment by ngc0202** [comment] 2018-04-26 20:09
Sorry, unfortunately 99% of the time, the builds failed with no explanation whatsoever, and this rustc panic only happened once when I tried with both the stable and nightly compiler.

**Comment by botika** [comment] 2020-09-05 14:10
It is impossible to reproduce. Has no sense. would have to close it

**Comment by pwnorbitals** [comment] 2020-10-14 18:26
This is weird. Have you been able to find some more information to replicate the bug ?

**Comment by botika** [comment] 2020-10-14 18:49
I tried to replicate it on my raspberry pi 2, but no luck. I think it is impossible to replicate it since the information is minimal. If I could, I would close it.

**Comment by pwnorbitals** [comment] 2020-10-15 09:07
I agree, unless @ngc0202 or anyone else can replicate it, it's going to be hard to find I'm afraid

**Comment by Enselic** [comment] 2023-08-29 14:09
Triage: Consensus seems to be to close this, so let's close.

**Closed by Enselic** 2023-08-29 14:09 UTC
Labels: I-ICE, O-Arm, T-compiler, C-bug
