### ISSUE TITLE
Values are not dropped in the opposite order after a `if let`.

### ISSUE THREAD

**Issue by shawnscode** [rust-lang/rust#53595] opened 2018-08-22 09:49 UTC
```rust
use std::sync::RwLock;

#[derive(Debug)]
pub struct Number(Option<i32>);

fn main() {
    let num = RwLock::new(Number(Some(0)));
    
    if let Some(n) = num.read().unwrap().0 {
        println!("{:?}", n);
    }
}
```

([Playground](https://play.rust-lang.org/?gist=c1de20e85024a34c913bb485f12c5902&version=nightly&mode=debug&edition=2015))

It seems that `num` is dropped before the temporary RwLockGuard which is counter intuition.

**Comment by Havvy** [comment] 2018-08-22 18:35
It's any expression, not just an `if let`. It's sort of not a bug, although the issue open for it says C-Bug. See [my explanation on Reddit](https://www.reddit.com/r/rust/comments/6dynjz/psa_temporaries_in_final_expression_in_block_live/). There's still an issue for it open as #21114. As such, closing as a duplicate.

**Closed by Havvy** 2018-08-22 18:35 UTC
