### ISSUE TITLE
Rustdoc should ignore unresolved imports in function bodies

### ISSUE THREAD

**Issue by SpriteOvO** [rust-lang/rust#97976] opened 2022-06-10 21:25 UTC
I tried this code:

Cargo.toml

```toml
[package]
name = "issue-demo"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["debugapi"], optional = true }

```

src/main.rs

```rust
#[cfg(any(all(windows, feature = "winapi"), doc))]
fn doc_me() {
    use winapi::um::debugapi::OutputDebugStringW;

    let text = vec![0_u16];
    let text = text.as_ptr();
    unsafe { OutputDebugStringW(text) }
}

fn main() {
    println!("Hello, world!");
}
```

Run
```bash
cargo doc --all-features --open
# or
cargo +nightly doc --all-features --open
````
on platforms other than Windows.

---

I expected to see this happen: No errors in the terminal, the `doc_me` function should be displayed in the documentation page. (According to the Rustdoc documentation [Interactions between platform-specific docs](https://doc.rust-lang.org/rustdoc/advanced-features.html#interactions-between-platform-specific-docs))

Instead, this happened: Terminal outputs error:

```rust
$ cargo +nightly doc --all-features
 Documenting issue-demo v0.1.0 (REDACTED/issue-proj)
error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> src/main.rs:3:9
  |
3 |     use winapi::um::debugapi::OutputDebugStringW;
  |         ^^^^^^ use of undeclared crate or module `winapi`

error: Compilation failed, aborting rustdoc

For more information about this error, try `rustc --explain E0433`.
error: could not document `issue-demo`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type bin --crate-name issue_demo src/main.rs -o REDACTED/issue-proj/target/doc --cfg 'feature="winapi"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --document-private-items '-Arustdoc::private-intra-doc-links' -C metadata=9a8ace04a496849a -L dependency=REDACTED/issue-proj/target/debug/deps --crate-version 0.1.0` (exit status: 1)
```

If we change the code of `src/main.rs` to: (remove the `use` statement)

```rust
#[cfg(any(all(windows, feature = "winapi"), doc))]
fn doc_me() {
    let text = vec![0_u16];
    let text = text.as_ptr();
    unsafe { winapi::um::debugapi::OutputDebugStringW(text) }
}

fn main() {
    println!("Hello, world!");
}
```

It will work as expected.

---

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

`rustc +nightly --version --verbose`:
```
rustc 1.63.0-nightly (420c970cb 2022-06-09)
binary: rustc
commit-hash: 420c970cb1edccbf60ff2aeb51ca01e2300b09ef
commit-date: 2022-06-09
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

**Comment by eggyal** [comment] 2022-06-10 22:36
You've included your stable rustc version, but the given instructions use nightly.  Does the issue also exist on stable?  If not, could you just confirm the nightly version at issue?

**Comment by SpriteOvO** [comment] 2022-06-11 07:00
> You've included your stable rustc version, but the given instructions use nightly. Does the issue also exist on stable? If not, could you just confirm the nightly version at issue?

@eggyal Yes, it is also exist on stable. Issue edited.

**Comment by GuillaumeGomez** [comment] 2022-06-17 13:06
The problem isn't rustdoc here but your `cfg`. More precisely the `doc` inside. In here, rustdoc calls rustc so it can get information and rustc cannot find the import (as expected). You need to add the `cfg` on the import as well.

If I'm completely wrong about this, don't hesitate to reopen the issue. Closing it in the meantime.

**Comment by SpriteOvO** [comment] 2022-06-17 13:12
> The problem isn't rustdoc here but your `cfg`. More precisely the `doc` inside. In here, rustdoc calls rustc so it can get information and rustc cannot find the import (as expected). You need to add the `cfg` on the import as well.
> 
> If I'm completely wrong about this, don't hesitate to reopen the issue. Closing it in the meantime.

@GuillaumeGomez But Rustdoc promised in [the Book](https://doc.rust-lang.org/rustdoc/advanced-features.html#interactions-between-platform-specific-docs):

> To document your crate, Rustdoc only needs to know the public signature of your functions. In particular, it doesn't have to know how any of your functions are implemented, so it ignores all type errors and name resolution errors with function bodies.

This also covers import errors, doesn't it?

**Comment by GuillaumeGomez** [comment] 2022-06-17 13:13
This is an interesting point. We need some information. This section should be updated. Reopening the issue then.

**Comment by jyn514** [comment] 2022-06-20 04:36
You can use -Ztreat-err-as-bug and RIST_BACKTRACE to find which query is invoking type checking here.

**Comment by jyn514** [comment] 2022-06-22 05:03
It looks like I missed this in https://github.com/rust-lang/rust/pull/73566. I only ignored errors in late resolution, not early imports.

A workaround in the meantime is to avoid `use` statements that don't resolve:
```rust
#[cfg(any(all(windows, feature = "winapi"), doc))]
fn doc_me() {
    let text = vec![0_u16];
    let text = text.as_ptr();
    unsafe { winapi::um::debugapi::OutputDebugStringW(text) }
}
```

**Comment by jyn514** [comment] 2022-06-22 05:17
Honestly, if no one has noticed this until now, I'm inclined to just leave it broken - this entire "feature" is a giant hack anyway.

**Comment by jyn514** [comment] 2023-01-04 18:44
I'm going to close this, I don't think it was ever supported even with everybody_loops and we document the limitation in https://doc.rust-lang.org/beta/rustdoc/advanced-features.html#interactions-between-platform-specific-docs.

**Closed by jyn514** 2023-01-04 18:44 UTC
Labels: T-rustdoc, C-bug
