### ISSUE TITLE
Nightly cannot be installed on macOS

### ISSUE THREAD

**Issue by rex4539** [rust-lang/rust#57122] opened 2018-12-25 13:11 UTC
```
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-12-25, rust version 1.33.0-nightly (f960f377f 2018-12-24)
info: downloading component 'rustc'
 78.4 MiB /  78.4 MiB (100 %)  10.7 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 63.5 MiB /  63.5 MiB (100 %)  10.8 MiB/s ETA:   0 s                
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: rolling back changes
error: failed to install component: 'rust-std-x86_64-apple-darwin', detected conflict: '"lib/rustlib/x86_64-apple-darwin/lib/libLLVM.dylib"'
```

This bug was introduced in latest nightly. I never an issue before.

**Comment by ishitatsuyuki** [comment] 2018-12-25 13:16
Duplicate of #57111

**Closed by ishitatsuyuki** 2018-12-25 13:16 UTC
