### ISSUE TITLE
x.py tries to install x86_64-unknown-linux-gnu on x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#68389] opened 2020-01-20 15:29 UTC
```
$ ./x.py check
Updating only changed submodules
Submodules updated in 0.01 seconds
extracting /home/joshua/src/rustc/build/cache/2019-12-18/rust-std-beta-x86_64-unknown-linux-gnu.tar.gz
downloading https://static.rust-lang.org/dist/2019-12-18/rustc-beta-x86_64-unknown-linux-gnu.tar.gz
############################################################################## 100.0%
extracting /home/joshua/src/rustc/build/cache/2019-12-18/rustc-beta-x86_64-unknown-linux-gnu.tar.gz
downloading https://static.rust-lang.org/dist/2019-12-18/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
############################################################################## 100.0%
extracting /home/joshua/src/rustc/build/cache/2019-12-18/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
downloading https://static.rust-lang.org/dist/2019-12-18/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
############################################################################## 100.0%
extracting /home/joshua/src/rustc/build/cache/2019-12-18/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/home/joshua/src/rustc/src/bootstrap/bootstrap.py", line 951, in main
    bootstrap(help_triggered)
  File "/home/joshua/src/rustc/src/bootstrap/bootstrap.py", line 920, in bootstrap
    build.build_bootstrap()
  File "/home/joshua/src/rustc/src/bootstrap/bootstrap.py", line 712, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/home/joshua/src/rustc/src/bootstrap/bootstrap.py", line 136, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
$ ./x.py check -v
running: /home/joshua/src/rustc/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /home/joshua/src/rustc/src/bootstrap/Cargo.toml
... same crash ...
```

**Comment by jyn514** [comment] 2020-01-20 15:32
The problem is here, it defaults to `gnu` if it's on Linux and not on Android: https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L196

**Comment by jyn514** [comment] 2020-01-20 15:35
As a workaround, I set `build = "x86_64-unknown-linux-musl"` in `config.toml`.

**Comment by Mark-Simulacrum** [comment] 2020-01-20 15:37
I suspect we can't be 100% precise in detecting the triple so the workaround here is expected, but we would also likely be happy to accept a patch to do so. However, the behavior as-is is not a bug, so I'm going to go ahead and close this (I would be willing to review a PR, but I don't want to track that work in an issue, as I don't believe it's helpful).

**Closed by Mark-Simulacrum** 2020-01-20 15:37 UTC
