### ISSUE TITLE
Make deprecation reasons more prominent

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18042] opened 2014-10-14 20:11 UTC
Right now you have to hold your mouse over a tiny bar next to the function name to find out why it's been deprecated.

**Comment by kmcallister** [comment] 2015-01-07 19:45
Nominating for 1.0-stable.

**Comment by pnkfelix** [comment] 2015-01-08 21:50
closing as dupe of #15468

**Closed by pnkfelix** 2015-01-08 21:50 UTC
Labels: A-rustdoc, E-easy, I-nominated
