### ISSUE TITLE
trait bounds on concrete types erase other trait implementations

### ISSUE THREAD

**Issue by lolbinarycat** [rust-lang/rust#132959] opened 2024-11-12 18:22 UTC
I tried this code:

```rust
fn six<T>() -> usize where u8: Into<T> {
    6_u8.into()
}
```

I expected to see this happen: code compiles

Instead, this happened: type mismatch error

```
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn six<T>() -> usize where u8: Into<T> {
  |        -       ----- expected `usize` because of return type
  |        |
  |        found this type parameter
2 |     6_u8.into()
  |     ^^^^^^^^^^^ expected `usize`, found type parameter `T`
  |
  = note:        expected type `usize`
          found type parameter `T`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (759e07f06 2024-10-30)
binary: rustc
commit-hash: 759e07f063fb8e6306ff1bdaeb70af56a878b415
commit-date: 2024-10-30
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.1
```

**Comment by ChayimFriedman2** [comment] 2024-11-12 18:28
They are not erased, only preferred. And this is known. Use `<u8 as Into<usize>>::into(v)`.

**Comment by fmease** [comment] 2024-11-12 18:40
Duplicate of https://github.com/rust-lang/rust/issues/24066.

**Closed by fmease** 2024-11-12 18:40 UTC
Labels: C-bug, needs-triage
