### ISSUE TITLE
Enum size includes sizes of variants that can't be created

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#69028] opened 2020-02-10 16:21 UTC
I tried this code:

```rust
enum MyPhantomData<T> {
    Always,
    Never(T, core::convert::Infallible),
}

#[test]
fn size() {
    assert_eq!(core::mem::size_of::<MyPhantomData<i32>>(), 0); // Err 8 != 0
}
```

I expected `size` test to pass because there is only one value of type `MyPhantomData<i32>` (`MyPhantomData::Always`). However, it fails because the actual size of `MyPhantomData<i32>` is `8`. It's also notable that `MyPhantomData<()>` is actually ZST.

This concrete example may seem strange, but this could also appear in generic code like that:

```rust
enum MaybeArrayAndT<T> {
    Nothing,
    ArrayAndT(T, [u8; 1024]),
}

fn main() {
    assert_eq!(size_of::<MaybeArrayAndT<Infallible>>(), 0); // Err: 1025 != 0
}
```

I'm wondering if there are already issues like that? I couldn't find any...

### Meta

Rust playground (stable `1.41.0`/nightly `2020-02-09 71c7e149e42cb0fc78a8`)

**Comment by hanna-kruppe** [comment] 2020-02-11 11:50
Relevant discussion is unfortunately spread over many issues (e.g. https://github.com/rust-lang/unsafe-code-guidelines/issues/79, https://github.com/rust-lang/rust/issues/49298, https://github.com/rust-lang/rust/issues/58374, https://github.com/rust-lang/unsafe-code-guidelines/issues/216, and possibly more). I'll close this as a duplicate of #58374 to avoid even more fragmentation.

**Closed by hanna-kruppe** 2020-02-11 11:50 UTC
Labels: A-codegen, C-enhancement, T-compiler
