### ISSUE TITLE
bootstrap/rustbuild: `--test-args` has no effect for cargo tests

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66458] opened 2019-11-15 20:32 UTC
I tried running `./x.py test src/tools/cargo --test-args rustc`, expecting that only tests with "rustc" in their name would be run. However, this has no effect. It looks like `--test-args` is just ignored.

**Comment by jyn514** [comment] 2020-07-11 21:15
Looks like duplicate of https://github.com/rust-lang/rust/issues/72536

**Comment by jyn514** [comment] 2023-02-03 06:43
This has been fixed, `x t src/tools/cargo --stage 0 --test-args util::auth::Secret` only runs 3 tests for me locally.

**Closed by jyn514** 2023-02-03 06:43 UTC
Labels: T-bootstrap, C-bug
