### ISSUE TITLE
Problem with combile actix-http with rustc 1.51.0-nightly on Windows

### ISSUE THREAD

**Issue by jslupicki** [rust-lang/rust#82580] opened 2021-02-27 09:29 UTC
### Code

It is  actix-http library and particular actix-http-2.0.0\src\client\h1proto.rs:58:27

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-pc-windows-msvc
release: 1.51.0-nightly
LLVM version: 11.0.1

```

### Error output

```
   Compiling actix-web v3.1.0
error: internal compiler error: failed to process buffered lint here
  --> C:\Users\jansl\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.0.0\src\client\h1proto.rs:58:27
   |
58 |                 Err(e) => log::error!("Can not set HOST header {}", e),
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877\compiler\rustc_lint\src\early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `actix-http`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

<details><summary><strong>Backtrace</strong></summary>
<p>
I've run `set RUST_BACKTRACE=1; cargo build --verbose`

```
   Compiling actix-web v3.1.0
     Running `rustc --crate-name actix_web --edition=2018 C:\Users\jansl\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-3.1.0\src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=
no -C debuginfo=2 --cfg "feature=\"compress\"" --cfg "feature=\"default\"" -C metadata=1a2258a95378751a -C extra-filename=-1a2258a95378751a --out-dir C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps -L dependency=C:\Users\jansl\OneDrive\prog\CLionPr
ojects\rust-backend\target\debug\deps --extern actix_codec=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_codec-b9fcc1794d92aac9.rmeta --extern actix_http=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_
http-165dc09413e706a3.rmeta --extern actix_macros=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\actix_macros-233cf357fbef98de.dll --extern actix_router=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_router-9462
6bf5de005ea7.rmeta --extern actix_rt=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_rt-02d5edaf539a17b1.rmeta --extern actix_server=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_server-cd16adb73b7c4b06
.rmeta --extern actix_service=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_service-4da8937bbfba36e5.rmeta --extern actix_testing=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_testing-e72cf64a3c0bf683
.rmeta --extern actix_threadpool=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_threadpool-203bb4882bb58d9d.rmeta --extern actix_tls=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_tls-4178556994d0f276.r
meta --extern actix_utils=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_utils-f483b3cee471db36.rmeta --extern actix_web_codegen=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\actix_web_codegen-82d6debfe25be019.
dll --extern awc=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libawc-f854de58973f23d5.rmeta --extern bytes=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libbytes-e4a07d8dd8015f64.rmeta --extern derive_more=C:\Users\ja
nsl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\derive_more-6ff6c516bf1a7d82.dll --extern encoding_rs=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libencoding_rs-ecc73b86f104c3e3.rmeta --extern futures_channel=C:\Users\jansl\OneDr
ive\prog\CLionProjects\rust-backend\target\debug\deps\libfutures_channel-df8bc665f58d399f.rmeta --extern futures_core=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libfutures_core-eb8b4853090fa8d4.rmeta --extern futures_util=C:\Users\jansl\OneDri
ve\prog\CLionProjects\rust-backend\target\debug\deps\libfutures_util-57fdadc78013d5c0.rmeta --extern fxhash=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libfxhash-222cc05d2a07eb7a.rmeta --extern log=C:\Users\jansl\OneDrive\prog\CLionProjects\rus
t-backend\target\debug\deps\liblog-59cb010c58caf9fc.rmeta --extern mime=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libmime-948cb1d57bc96c1f.rmeta --extern pin_project=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\li
bpin_project-adaff55091c74bdb.rmeta --extern regex=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libregex-32bdce8ebf7c635b.rmeta --extern serde=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libserde-42e4ae961975d0b6.rm
eta --extern serde_json=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libserde_json-df00a650c1b29322.rmeta --extern serde_urlencoded=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libserde_urlencoded-3e31304741df1963.rm
eta --extern socket2=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libsocket2-f699ab77382d80db.rmeta --extern time=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libtime-e1941c1c37c6c09a.rmeta --extern tinyvec=C:\Users\
jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libtinyvec-605edadd1cecd93e.rmeta --extern url=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\liburl-ba793457ecda92c1.rmeta --cap-lints allow -L native=C:\Users\jansl\OneDrive\prog\C
LionProjects\rust-backend\target\debug\build\brotli-sys-20d694fd8a4f64c1\out`
error: internal compiler error: failed to process buffered lint here
  --> C:\Users\jansl\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.0.0\src\client\h1proto.rs:58:27
   |
58 |                 Err(e) => log::error!("Can not set HOST header {}", e),
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877\compiler\rustc_lint\src\early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `actix-http`

Caused by:
  process didn't exit successfully: `rustc --crate-name actix_http --edition=2018 C:\Users\jansl\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-http-2.0.0\src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metada
ta,link -C embed-bitcode=no -C debuginfo=2 --cfg "feature=\"brotli2\"" --cfg "feature=\"compress\"" --cfg "feature=\"default\"" --cfg "feature=\"flate2\"" -C metadata=165dc09413e706a3 -C extra-filename=-165dc09413e706a3 --out-dir C:\Users\jansl\OneDrive\prog\CLionProjects\r
ust-backend\target\debug\deps -L dependency=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps --extern actix_codec=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_codec-b9fcc1794d92aac9.rmeta --extern actix_connect=
C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_connect-3205485e244b9133.rmeta --extern actix_rt=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_rt-02d5edaf539a17b1.rmeta --extern actix_service=C:\Users\j
ansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_service-4da8937bbfba36e5.rmeta --extern actix_threadpool=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_threadpool-203bb4882bb58d9d.rmeta --extern actix_utils=C:\Use
rs\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libactix_utils-f483b3cee471db36.rmeta --extern base64=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libbase64-c39764132074fa2e.rmeta --extern bitflags=C:\Users\jansl\OneDrive\pro
g\CLionProjects\rust-backend\target\debug\deps\libbitflags-158395e3d13197d7.rmeta --extern brotli2=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libbrotli2-8a2879e0ce4e9747.rmeta --extern bytes=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-back
end\target\debug\deps\libbytes-e4a07d8dd8015f64.rmeta --extern cookie=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libcookie-de9772af60c2ecde.rmeta --extern copyless=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libco
pyless-677689e513331c71.rmeta --extern derive_more=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\derive_more-6ff6c516bf1a7d82.dll --extern either=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libeither-0947d4eaf367e3a3
.rmeta --extern encoding_rs=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libencoding_rs-ecc73b86f104c3e3.rmeta --extern flate2=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libflate2-ff3ef4f8978ec9ac.rmeta --extern fu
tures_channel=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libfutures_channel-df8bc665f58d399f.rmeta --extern futures_core=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libfutures_core-eb8b4853090fa8d4.rmeta --extern
futures_util=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libfutures_util-57fdadc78013d5c0.rmeta --extern fxhash=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libfxhash-222cc05d2a07eb7a.rmeta --extern h2=C:\Users\jans
l\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libh2-9c0a678820bcad6e.rmeta --extern http=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libhttp-a036df43bccf3c73.rmeta --extern httparse=C:\Users\jansl\OneDrive\prog\CLionProjects\rust
-backend\target\debug\deps\libhttparse-2fff68e417e55fac.rmeta --extern indexmap=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libindexmap-5f43f0b2d88214a0.rmeta --extern itoa=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\de
ps\libitoa-cd1fb984079cfa41.rmeta --extern language_tags=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\liblanguage_tags-b3632b5130865519.rmeta --extern lazy_static=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\liblazy_
static-85c80ceb047ff8eb.rmeta --extern log=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\liblog-59cb010c58caf9fc.rmeta --extern mime=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libmime-948cb1d57bc96c1f.rmeta --extern
 percent_encoding=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libpercent_encoding-3579b393ca058f11.rmeta --extern pin_project=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libpin_project-adaff55091c74bdb.rmeta --exte
rn rand=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\librand-8649d2246150baa1.rmeta --extern regex=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libregex-32bdce8ebf7c635b.rmeta --extern serde=C:\Users\jansl\OneDrive\p
rog\CLionProjects\rust-backend\target\debug\deps\libserde-42e4ae961975d0b6.rmeta --extern serde_json=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libserde_json-df00a650c1b29322.rmeta --extern serde_urlencoded=C:\Users\jansl\OneDrive\prog\CLionPr
ojects\rust-backend\target\debug\deps\libserde_urlencoded-3e31304741df1963.rmeta --extern sha1=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libsha1-e817ecaffb5f20f6.rmeta --extern slab=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\targ
et\debug\deps\libslab-3558282040bced52.rmeta --extern time=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\deps\libtime-e1941c1c37c6c09a.rmeta --cap-lints allow -L native=C:\Users\jansl\OneDrive\prog\CLionProjects\rust-backend\target\debug\build\brotli-
sys-20d694fd8a4f64c1\out` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed

```

</p>
</details>

**Comment by SNCPlay42** [comment] 2021-02-27 10:02
This is a duplicate of #81805, which is a duplicate of #81531. Updating to a more recent nightly should fix the issue.

**Closed** 2021-02-27 10:40 UTC
Labels: C-bug, I-ICE, T-compiler

**Comment by jslupicki** [comment] 2021-02-27 10:57
Confirm - with 1.52.0-nightly it compile just fine. Thanks.
