### ISSUE TITLE
Some compile errors within const block of associated constants are not evaluated

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rust#71403] opened 2020-04-21 21:22 UTC
Basically, if you put potential error into const block of associated constant, it doesn't gets evaluated.
Good example is `arithmetic_overflow`.
By default it triggers compilation error, but not when it is within const block of associated constant

Rust playgound sample:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6ae8ce6871821d8fce58cc05dbdd5984

Doubt it is expected behavior?

Instead, this happened: *explanation*

Happens in both latest stable and nightly

**Comment by jonas-schievink** [comment] 2020-04-21 21:26
Duplicate of https://github.com/rust-lang/rust/issues/71282

**Closed by jonas-schievink** 2020-04-21 21:26 UTC
Labels: C-bug
