### ISSUE TITLE
Chaining Arc<RefCell<..>> confuses borrowck.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#26706] opened 2015-07-01 05:20 UTC
http://is.gd/rNjThX

```
use std::sync::Arc;
use std::cell::RefCell;

struct A {
    a : Arc<RefCell<i32>>
}

struct B {
    b : Arc<RefCell<A>>
}

impl B {
    fn is_foo(&self) -> bool {
        *self.b.borrow().a.borrow() == 2
    }
}
```

This should compile, but it does not. Breaking the chain is a workaround.

**Comment by Aatch** [comment] 2015-07-01 05:23
cc @pnkfelix is this an issue with destruction scopes specifically, or related to rvalue lifetimes in general?

**Comment by arielb1** [comment] 2015-07-01 09:39
I think this is intentional well-known fallout of dropck.

**Comment by arielb1** [comment] 2015-07-01 13:48
@Aatch 

The issue here is that the first borrow must be valid during the destruction of the second borrow, but the current destruction-scope implementation requires it to be valid for the entire `is_foo` block.

**Comment by pnkfelix** [comment] 2015-07-01 21:46
cc #22321

**Comment by pnkfelix** [comment] 2015-07-01 21:47
this seems like a probable dupe of #22323

**Comment by alexcrichton** [comment] 2015-08-13 20:31
Yeah I think this is just a dupe of #22323 as well.

**Closed by alexcrichton** 2015-08-13 20:31 UTC
Labels: A-lifetimes
