### ISSUE TITLE
type cannot be shared between threads safely message could be more informative

### ISSUE THREAD

**Issue by vvuk** [rust-lang/rust#28378] opened 2015-09-12 20:29 UTC
If you hit an issue such as

```
misc.rs:26:5: 26:17 error: the trait `core::marker::Sync` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
misc.rs:26     require_sync(&x);
               ^~~~~~~~~~~~
misc.rs:26:5: 26:17 help: run `rustc --explain E0277` to see a detailed explanation
misc.rs:26:5: 26:17 note: `*mut libc::types::common::c95::c_void` cannot be shared between threads safely
misc.rs:26     require_sync(&x);
               ^~~~~~~~~~~~
error: aborting due to previous error
```

It's very difficult to track down the actual type that has the c_void (or whatever).  Sample gist with issue: https://gist.github.com/vvuk/333cef042169abbf9bfb

It would be very nice if rustc were to indicate that it's talking about the "p" field of OneStruct, which is the 'one' field of TwoStruct.  Even just having the note/error refer to OneStruct would be helpful, because as it is it's very difficult to track down where the actual problem is.

**Comment by huonw** [comment] 2015-09-13 08:46
Dupe of https://github.com/rust-lang/rust/issues/21793 , thanks for filing!

**Closed by huonw** 2015-09-13 08:46 UTC
Labels: A-diagnostics, I-papercut
