### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: index.end <= self.len()', ../src/libcore/slice.rs:544

### ISSUE THREAD

**Issue by cjcole** [rust-lang/rust#27602] opened 2015-08-08 13:31 UTC
$ rustc --version
rustc 1.2.0 (082e47636 2015-08-03)

$ RUST_BACKTRACE=1 cargo build
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'assertion failed: index.end <= self.len()', ../src/libcore/slice.rs:544

stack backtrace:
   1:        0x1058dd7b5 - sys::backtrace::write::hf5ea20500b66cd24uns
   2:        0x1058e6013 - panicking::on_panic::hbe02cb0d925cad49iGw
   3:        0x1058a1dd2 - rt::unwind::begin_unwind_inner::h12ba0ba9dffdecc2uow
   4:        0x1058a2b29 - rt::unwind::begin_unwind_fmt::hadf0dbf11d345ebfAnw
   5:        0x1058e5b9c - rust_begin_unwind
   6:        0x105939d95 - panicking::panic_fmt::h987a4890059dc6e0H8B
   7:        0x1059327e1 - panicking::panic::hfd3e1c225039d9cae7B
   8:        0x1029106ae - astconv::finish_resolving_def_to_ty::he5ea7cd41915b99d76v
   9:        0x1028cee6b - astconv::ast_ty_to_ty::hf914e7106582dfb2V8v
  10:        0x10291bf9f - astconv::ast_ty_arg_to_ty::hd7f3449b6ed7d80f3Zv
  11:        0x10291bc4a - vec::Vec<T>.FromIterator<T>::from_iter::h14554187055721803077
  12:        0x102919bb7 - astconv::convert_angle_bracketed_parameters::h1f04abd7bdcd3d52H2u
  13:        0x1028cc5aa - astconv::ast_path_substs_for_ty::h0a1cd0aaeb5403f5lLu
  14:        0x102920de5 - astconv::ast_path_to_ty::h8c49a0891a1ce609Brv
  15:        0x10290e149 - astconv::finish_resolving_def_to_ty::he5ea7cd41915b99d76v
  16:        0x1028cee6b - astconv::ast_ty_to_ty::hf914e7106582dfb2V8v
  17:        0x10291ce02 - astconv::convert_ty_with_lifetime_elision::h4459fb498cc71b5756u
  18:        0x102925bfd - astconv::ty_of_method_or_bare_fn::haa63c3b9895211a0Now
  19:        0x1029412b9 - collect::convert_method::h80cba98fe26dd14afLx
  20:        0x10292f9b6 - collect::convert_item::h2cca9c39f6b8d796R0x
  21:        0x102928706 - collect::collect_item_types::hf0bc00065ee6508bW7w
  22:        0x10297948a - check_crate::h117ec0c1269afe619fD
  23:        0x1021bad16 - driver::phase_3_run_analysis_passes::closure.15766
  24:        0x1021b9204 - middle::ty::with_ctxt::h14728011725879770170
  25:        0x1021b400a - driver::phase_3_run_analysis_passes::h16713467199444562124
  26:        0x102197107 - driver::compile_input::hb6d2be5b0fa2247fTba
  27:        0x10227313f - run_compiler::h21d74b88eec3fe3bx7b
  28:        0x1022709f3 - boxed::F.FnBox<A>::call_box::h1689969825914258414
  29:        0x1022701b7 - rt::unwind::try::try_fn::h11273853850686318048
  30:        0x105970cc8 - rust_try_inner
  31:        0x105970cb5 - rust_try
  32:        0x1058cfc95 - rt::unwind::try::inner_try::h480e3107f6a4b5b9nkw
  33:        0x1022703e8 - boxed::F.FnBox<A>::call_box::h888215220722514405
  34:        0x1058e4a9d - sys::thread::Thread::new::thread_start::hdb3d925f69c5da4aHIv
  35:     0x7fff9916d267 - _pthread_body
  36:     0x7fff9916d1e4 - _pthread_start

Any guidance on finding the code which is tickling this would be appreciated as I am dead in the water.

Thanks.

**Comment by cjcole** [comment] 2015-08-08 13:33
Possibly the same root cause: https://github.com/rust-lang/rust/issues/22968

**Comment by cjcole** [comment] 2015-08-08 13:34
$ rustc --version --verbose
rustc 1.2.0 (082e47636 2015-08-03)
binary: rustc
commit-hash: 082e4763615bdbe7b4dd3dfd6fc2210b7773edf5
commit-date: 2015-08-03
host: x86_64-apple-darwin
release: 1.2.0

**Comment by eefriedman** [comment] 2015-08-08 19:01
If I had to guess blindly just from the stack trace, I would say you're doing something weird with associated types in the signature of some method.

It's likely this is a duplicate of #22968.

**Closed** 2015-08-13 00:26 UTC

**Comment by cjcole** [comment] 2015-08-14 16:02
> It's likely this is a duplicate of #22968.

Fixed, thanks.
