### ISSUE TITLE
workspace members pick up features from other workspace members

### ISSUE THREAD

**Issue by becky112358** [rust-lang/rust#121183] opened 2024-02-16 10:59 UTC
My code example is here:

https://github.com/becky112358/rust_bug_features

Two workspace members call the same library.
One calls the library with a feature, the other without.
When I compile the workspace all together, the member without a feature compiles with a feature.
When I compile only the member without a feature, it compiles without the feature.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-msvc
release: 1.76.0
LLVM version: 17.0.6
```

Beta: The bug still exists
Nightly: The bug still exists

Thank you :) :) :)

**Comment by weihanglo** [comment] 2024-02-16 14:30
Thanks for the report. This is an expected behaviour called [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification). When building the entire workspace the feature set of each package would be merged together.

**Comment by weihanglo** [comment] 2024-02-16 14:31
Close as it is expected not a bug.

**Closed** 2024-02-16 14:31 UTC
Labels: T-cargo, C-bug

**Comment by becky112358** [comment] 2024-02-16 18:14
I see! Thank you for letting me know, and thank you for the documentation link.
