### ISSUE TITLE
ICE anonymous lifetime in struct wrong position 2018 edition

### ISSUE THREAD

**Issue by leshow** [rust-lang/rust#52747] opened 2018-07-26 18:01 UTC
related to but a bit different than https://github.com/rust-lang/rust/issues/52098

```rust
struct MnemonicResponse<'_> {
   pass: &str
}
```

I tried this without first reading where anon lifetimes were allowed, in any case, it ICE's:

```
❯ RUST_BACKTRACE=full cargo build
   Compiling rust_mnemonic v0.3.0 (file:///home/evan/personal/rust/rust_mnemonic)                                                                    
thread 'main' panicked at 'assertion failed: self.is_collecting_in_band_lifetimes', librustc/hir/lowering.rs:738:9
stack backtrace:
   0:     0x7eff9de5068e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he8af69b64cd628aa
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7eff9de27fc6 - std::sys_common::backtrace::print::hd007d8131d52db53
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7eff9de596ad - std::panicking::default_hook::{{closure}}::hd58f2759bdd5fc75
                               at libstd/panicking.rs:211
   3:     0x7eff9de59420 - std::panicking::default_hook::h2c1bf51c9795af05
                               at libstd/panicking.rs:227
   4:     0x7eff9a60e71d - rustc::util::common::panic_hook::h4747d9f4ae34e974
   5:     0x7eff9de59d73 - std::panicking::rust_panic_with_hook::h28562f4ec57f2c02
                               at libstd/panicking.rs:479
   6:     0x7eff9a5b2d46 - std::panicking::begin_panic::h97956caef989aaaa
   7:     0x7eff9a4794c5 - rustc::hir::lowering::LoweringContext::lower_lifetime::ha2401f7a1aee62f8
   8:     0x7eff9a4476f9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::h05420a4bd55f76b0
   9:     0x7eff99f6d946 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h4c0cab49953365d8
  10:     0x7eff9a4798fd - rustc::hir::lowering::LoweringContext::lower_generics::hb144c5396c8b57fc
  11:     0x7eff9a47e657 - rustc::hir::lowering::LoweringContext::lower_item::h39c8dd97ba06ea32
  12:     0x7eff9a46ff04 - <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item::hd413b9fc349b7b03
  13:     0x7eff9a0738bc - syntax::visit::walk_block::h0a43d4f671d549ff
  14:     0x7eff9a07eafc - syntax::visit::walk_item::h81c5fb3c345804c9
  15:     0x7eff9a47013f - <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item::hd413b9fc349b7b03
  16:     0x7eff9a07ed0b - syntax::visit::walk_item::h81c5fb3c345804c9
  17:     0x7eff9a47013f - <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item::hd413b9fc349b7b03
  18:     0x7eff9a46f0ab - rustc::hir::lowering::lower_crate::hd30fdf3288509cc4
  19:     0x7eff9e1e0be6 - rustc::util::common::time::hbaca18c84aca45af
  20:     0x7eff9e1d284d - rustc_driver::driver::phase_2_configure_and_expand::hd08620ae2876daea
  21:     0x7eff9e1cd3eb - rustc_driver::driver::compile_input::hf8af496cda30d169
  22:     0x7eff9e271ce0 - rustc_driver::run_compiler_with_pool::h63554a8a1074e873
  23:     0x7eff9e195f0c - <scoped_tls::ScopedKey<T>>::set::h2d0f977c46614714
  24:     0x7eff9e195c01 - <scoped_tls::ScopedKey<T>>::set::h058ba6dfb6a57aa9
  25:     0x7eff9e1f05ca - syntax::with_globals::h64800d12ee1ee8ca
  26:     0x7eff9e194692 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf130c8184a048d5d
  27:     0x7eff9de66be9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:106
  28:     0x7eff9e26f151 - rustc_driver::run::h49f3a1911b6c48bf
  29:     0x7eff9e27c8da - rustc_driver::main::h000c0f11b2e94126
  30:     0x562b423f8b52 - std::rt::lang_start::{{closure}}::h1492c8444d8ececb
  31:     0x7eff9de597b2 - std::panicking::try::do_call::hb494fa268bfac907
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  32:     0x7eff9de66be9 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:106
  33:     0x7eff9de3bf05 - std::rt::lang_start_internal::h910a443015422f4a
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  34:     0x562b423f8bb3 - main
  35:     0x7eff9da512e0 - __libc_start_main
  36:     0x562b423f8a38 - <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (6a1c0637c 2018-07-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `rust_mnemonic`.

To learn more, run the command again with --verbose.


```

**Comment by dtolnay** [comment] 2018-09-30 06:12
Closing as a duplicate of #52098 because the stacktrace is the same.

**Closed by dtolnay** 2018-09-30 06:12 UTC
Labels: A-diagnostics, A-lifetimes, A-parser, A-rust-2018-preview, I-ICE
