### ISSUE TITLE
ICE when coercing certain closures (with discarded arguments) to fn

### ISSUE THREAD

**Issue by archshift** [rust-lang/rust#40204] opened 2017-03-02 08:16 UTC
To replicate:
```rust
#![feature(closure_to_fn_coercion)]
fn main() {
    let bar: fn(&mut u32) = |_| {};
}
```

ICE details:
```
rustc 1.17.0-nightly (be760566c 2017-02-28)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/libcollections/vec.rs:1401
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rustc::infer::region_inference::RegionVarBindings::var_origin
   1: rustc::infer::error_reporting::<impl rustc::infer::InferCtxt<'a, 'gcx, 'tcx>>::note_issue_32330
   2: rustc::infer::error_reporting::<impl rustc::infer::InferCtxt<'a, 'gcx, 'tcx>>::report_and_explain_type_error
   3: rustc::infer::InferCtxt::report_mismatched_types
   4: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::demand_coerce
   5: rustc_typeck::check::FnCtxt::check_decl_initializer
   6: rustc_typeck::check::FnCtxt::check_decl_local
   7: rustc_typeck::check::FnCtxt::check_stmt
   8: rustc_typeck::check::FnCtxt::check_block_with_expected
   9: rustc_typeck::check::FnCtxt::check_expr_kind
  10: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  11: rustc_typeck::check::check_fn
  12: rustc_typeck::check::typeck_tables
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::try_get
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::get
  15: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::item_tables
  16: rustc_typeck::check::check_item_bodies
  17: rustc_typeck::check_crate
  18: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  19: rustc_driver::driver::phase_3_run_analysis_passes
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  24: <F as alloc::boxed::FnBox<A>>::call_box
  25: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:648
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  26: start_thread
  27: clone
```

ref #40025

**Comment by dtolnay** [comment] 2017-03-25 18:04
This looks a lot like #40000 and #40743.

**Comment by est31** [comment] 2017-05-03 23:48
With current nightly this doesn't ICE any more, but gives an error:

```
rustc 1.19.0-nightly (6a5fc9eec 2017-05-02)
error[E0308]: mismatched types
 --> <anon>:3:29
  |
3 |     let bar: fn(&mut u32) = |_| {};
  |                             ^^^^^^ expected concrete lifetime, found bound lifetime parameter
  |
  = note: expected type `fn(&mut u32)`
             found type `[closure@<anon>:3:29: 3:35]`

error: aborting due to previous error
```

Is this a problem?

**Comment by cramertj** [comment] 2017-05-05 16:51
@est31 That's related to https://github.com/rust-lang/rust/issues/39706, https://github.com/rust-lang/rust/issues/32600, and https://github.com/rust-lang/rust/issues/41078. Inference doesn't work quite right for lifetime-generic closures.

**Comment by nikomatsakis** [comment] 2017-05-05 16:53
@cramertj @est31 that's actually a different bug. I would say it is https://github.com/rust-lang/rust/issues/41755 -- in particular, if we were getting the expected type correctly, this inference error would go away.

**Comment by est31** [comment] 2017-05-05 18:09
okay, but [if you spell out the type annotations](https://is.gd/r9QVfT), the example compiles fine. Does that mean this bug is fixed?

**Comment by est31** [comment] 2017-05-05 20:32
Okay, I've obtained a copy of the compiler that ICE'd and apparently it doesn't ICE when you spell out the type annotation. So I'd say the ICE is fixed, and only  #41755 remains?

**Comment by est31** [comment] 2017-05-09 11:36
With #41838 merged, this issue seems to be resolved. @nikomatsakis  does this issue need a regression test or can it be closed?

**Comment by arielb1** [comment] 2017-05-09 11:37
duplicate of #40000.

**Closed by arielb1** 2017-05-09 11:37 UTC
Labels: E-needstest, I-ICE
