### ISSUE TITLE
Run hello world error on m1 mbp(macOS 12.0 (21A5506j)) 

### ISSUE THREAD

**Issue by xunfeng1980** [rust-lang/rust#89085] opened 2021-09-19 02:07 UTC
### Code

```Rust
fn main() {
    println!("Hello, world!");
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (aa8f2d432 2021-09-18)
binary: rustc
commit-hash: aa8f2d432b23575929a48f87b8746f41ba723318
commit-date: 2021-09-18
host: aarch64-apple-darwin
release: 1.57.0-nightly
LLVM version: 13.0.0

```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo build
   Compiling light v0.1.0 (/Users/lux/src/github.com/xunfeng1980/light)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "Provided allocation has wrong size for slot count 131072"', compiler/rustc_metadata/src/rmeta/decoder.rs:263:29
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: rustc_metadata::rmeta::decoder::CrateMetadata::new
   4: rustc_metadata::creader::CrateLoader::maybe_resolve_crate
   5: rustc_metadata::creader::CrateLoader::maybe_resolve_crate
   6: rustc_metadata::creader::CrateLoader::process_extern_crate
   7: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
   8: rustc_ast::visit::walk_item
   9: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
  10: rustc_expand::expand::AstFragment::visit_with
  11: rustc_resolve::macros::<impl rustc_expand::base::ResolverExpand for rustc_resolve::Resolver>::visit_ast_fragment_with_placeholders
  12: rustc_expand::expand::MacroExpander::collect_invocations
  13: rustc_expand::expand::MacroExpander::fully_expand_fragment
  14: rustc_expand::expand::MacroExpander::expand_crate
  15: rustc_session::utils::<impl rustc_session::session::Session>::time
  16: rustc_interface::passes::configure_and_expand
  17: rustc_interface::queries::Queries::expansion
  18: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  19: rustc_span::with_source_map
  20: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (aa8f2d432 2021-09-18) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `light`
```

</p>
</details>

**Comment by ryanolf** [comment] 2021-09-19 07:28
I also have m1 map and nightly 2021-09-18 does this for me but 2021-09-17 is fine.

**Comment by camelid** [comment] 2021-09-19 17:39
I haven't bisected, but #82183 looks to have landed in nightly-2021-09-18, so cc @michaelwoerister (also they are more knowledgeable about this code in general).

**Comment by hkratz** [comment] 2021-09-19 18:33
Indeed. Bisected to d6cd2c6c877110748296760aefddc21a0ea1d316 which is #82183.

**Comment by Aaron1011** [comment] 2021-09-19 19:44
This error comes from the ODHT crate: https://github.com/rust-lang/odht/blob/b58e329081c91d0636a35f3af2cc2bffaf84038c/src/memory_layout.rs#L64-L69

**Comment by Aaron1011** [comment] 2021-09-19 19:45
cc @michaelwoerister

**Comment by hkratz** [comment] 2021-09-20 05:20
Hmm, can't reproduce with rustc built locally on an M1 macbook, how are the nightlies built?

**Comment by tifrel** [comment] 2021-09-20 07:08
> Hmm, can't reproduce with rustc built locally on an M1 macbook, how are the nightlies built?

Opposing question, how do I build rustc locally?

**Comment by michaelwoerister** [comment] 2021-09-20 08:43
I'll look into it.

**Comment by michaelwoerister** [comment] 2021-09-20 09:09
I think this is a cross-compilation related issue. The `aarch64-apple-darwin` compiler [seems to be built on `x86_64-apple-darwin`](https://github.com/rust-lang/rust/blob/e71925aab9e28ce35363e3fdef27ca011ac6a1dc/.github/workflows/ci.yml#L323) and because of that the odht crate makes some assumptions that are true for `x86_64` but not for `aarch64`. So the bug is `odht` making platform dependent assumptions where it shouldn't.

I hope I can fix this without having an `aarch64-apple-darwin` device available. @rust-lang/infra, do we not run tests on `aarch64-apple-darwin`? Or is the compiler we use for testing built differently from the dist build?

@tifrel, you can find a description of how to build the compiler locally at https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html.

**Comment by shepmaster** [comment] 2021-09-20 11:20
> we not run tests on aarch64-apple-darwin

that’s correct. GitHub does not offer M1 machines for CI.

**Comment by camelid** [comment] 2021-09-20 21:46
The fix looks to have landed in time to be included in the 2021-09-20 nightly being released in a few hours.

**Comment by camelid** [comment] 2021-09-21 16:59
Note that there was an error building the 2021-09-20 nightly, so it wasn't actually released. Hopefully the 2021-09-21 nightly will build successfully and be released in ~8 hours.

**Comment by xunfeng1980** [comment] 2021-09-22 02:03
> Note that there was an error building the 2021-09-20 nightly, so it wasn't actually released. Hopefully the 2021-09-21 nightly will build successfully and be released in ~8 hours.

yep,  2021-09-21 nightly version is normal

**Closed** 2021-09-22 02:04 UTC
Labels: O-macos, I-ICE, A-metadata, O-ARM, regression-from-stable-to-nightly, T-compiler, C-bug, E-needs-bisection, I-prioritize

**Comment by michaelwoerister** [comment] 2021-09-22 08:26
Awesome `:)`
