### ISSUE TITLE
rustdoc: generated trait impls for arrays are very noisy

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#23986] opened 2015-04-02 23:55 UTC
For example, looking at the docs for `Vec`, some important trait implementations are hard to find in between all the `PartialEq` implementations for each size of fixed-size arrays: http://static.rust-lang.org/doc/master/std/vec/struct.Vec.html

Hopefully these impls will eventually become generic, but in the meantime we should consider some way of hiding or collapsing them in the docs.

**Comment by aturon** [comment] 2015-04-02 23:55
cc @alexcrichton

**Comment by alexcrichton** [comment] 2015-04-08 00:51
Dupe of #21660

**Closed by alexcrichton** 2015-04-08 00:51 UTC
Labels: A-rustdoc
