### ISSUE TITLE
likely/unlikely hints dropped in release mode

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rust#96275] opened 2022-04-21 08:02 UTC
I tried this code:

```rust
#![feature(core_intrinsics)]
#![feature(bench_black_box)]

use std::intrinsics::unlikely;

pub fn foo(a: bool) {
    if unlikely(a) {
        std::hint::black_box(42);
    }

    std::hint::black_box(0xDEAD);
    std::hint::black_box(0xBEEF);
}
```

I expected to see this happen: llvm.expect should be present in the IR
Instead, this happened: it's in debug mode, but gets dropped in release mode

Discovered here: https://github.com/rust-lang/rust/pull/93668#issuecomment-1104826453

**Comment by SUPERCILEX** [comment] 2022-04-21 08:28
From @Kobzol:

> When the `std::intrinsics::unlikely/likely` function is used, the codegen doesn't emit `llvm.expect` annotation in release mode. Curiously enough, in debug mode it _does_ emit it.
> 
> A minimal example:
> 
> ```rust
> #![feature(core_intrinsics)]
> 
> use std::intrinsics::unlikely;
> 
> pub fn foo(x: bool) {
>     if unlikely(x) {
>         println!("foo: {x}");
>     }
>     println!("bar");
> }
> ```
> 
> Playground link [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021). In debug mode, LLVM IR contains `llvm.expect`. In release mode, it doesn't.
> 
> This has been previously noted [here](https://github.com/rust-lang/rust/issues/26179#issuecomment-974744742) (maybe it indeed started with LLVM 13?) and more recently [here](https://github.com/rust-lang/rust/pull/93668#issuecomment-1104826453).
> 
> I can take a look into this, if you can point me into the right direction. There is a codegen test for `likely/unlikely`, but it uses `-C no-prepopulate-passes`, which does not correspond to what release (`-O`) does.

**Comment by nikic** [comment] 2022-04-21 08:30
The playground like doesn't work. Note that `llvm.expect` is expected to get dropped during optimization and replaced with branch weight metadata -- but I believe there is an open issue that the form in which rustc emits `if` does not allow LLVM to attach the metadata.

**Comment by Kobzol** [comment] 2022-04-21 08:36
Sorry, fixed link [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=6b2f45f9148e8f4f777eab115f054cb2).

Just so that I understand it correctly, "during optimization" means in `rustc` or in `LLVM`? I kind of assumed that even in "release" mode, the LLVM IR that gets emitted is IR before applying any LLVM opt passes/optimizations. That's why I expected to see `llvm.expect` in there.

**Comment by nikic** [comment] 2022-04-21 08:40
@Kobzol `--emit` output is always the final (optimized) result. You'd have to pass `-C no-prepopulate-passes` to disable optimization.

**Comment by Kobzol** [comment] 2022-04-21 08:44
Ooh, that makes sense, thanks. If that was not the case, the debug and release output would probably not even differ.

Then I'm not sure if this issue is really valid, since after optimization these annotations can indeed easily disappear. I guess the root of the issue is then the fact that the annotation isn't always behaving as expected (e.g. [here](https://github.com/rust-lang/rust/pull/93668#issuecomment-1104807779)), which might be caused by the issue that you have described, with attaching metadata to `if`s.

**Comment by nikic** [comment] 2022-04-21 12:28
Closing this as a duplicate of https://github.com/rust-lang/rust/issues/88767, which has a bit more analysis and a link to the relevant LLVM change.

**Closed by nikic** 2022-04-21 12:28 UTC
Labels: A-LLVM, I-slow, C-bug

**Comment by RalfJung** [comment] 2022-04-21 14:32
> You'd have to pass -C no-prepopulate-passes to disable optimization.

Just not passing `-O` should disable optimizations, no?

I've seen this "no-prepopulate" thing before and it's one of our worst-named options -- the name explains absolutely nothing about what it does, unless you already know very well how LLVM works...

**Comment by nikic** [comment] 2022-04-21 14:35
> > You'd have to pass -C no-prepopulate-passes to disable optimization.
> 
> Just not passing `-O` should disable optimizations, no?

Yes-ish. We both generate different code at `O0` (e.g. omitting some attributes) and LLVM does some optimization at `O0` (e.g. inlining `#[inline(always)]` functions), so not specifying `-O` and using `-O -C no-prepopulate-passes` are not quite the same. Though for many cases the distinction is not relevant.
