### ISSUE TITLE
nightly rustc breaks stable code for some type inferences

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#26279] opened 2015-06-13 17:46 UTC
```rust
use std::ops::Add;
trait Zero: Add<Self, Output=Self> {
    fn zero()->Self;
}

impl Zero for i32 {
    fn zero()->i32 {
        0
    }
}

fn main() {
    let mut x = Vec::<i32>::new();
    x.extend(vec![Zero::zero()].into_iter())
}
```
nightly (breaking) : http://is.gd/5Pl8DA
stable (compiles) : http://is.gd/ZLTyOv

**Comment by alexcrichton** [comment] 2015-06-14 04:44
triage: I-nominated

**Comment by bluss** [comment] 2015-06-14 09:23
There's a tag on PR #25989 already too.

**Comment by nikomatsakis** [comment] 2015-06-17 15:51
triage: P-high

**Comment by nikomatsakis** [comment] 2015-06-17 15:51
Gave P-high because this is a regression.

**Comment by bluss** [comment] 2015-06-17 16:09
It's deliberate, due to new Extend impls in libstd, on for example Vec.

**Comment by jroesch** [comment] 2015-07-06 18:52
@bluss I'm out of the std loop could you elaborate?

**Comment by bluss** [comment] 2015-07-06 19:19
Sure, `Vec<T>` and other collections used to implement only `Extend<T>` so `x.extend(vec![Zero::zero()].into_iter())` would infer the type for the `Zero` uniquely, from the type of `x`.

Now, `Vec<T>` implements both `Extend<T>` and `Extend<&T> where T: Copy`, so it is ambiguous which type the `Zero` call should produce.

One convenient workaround is to just use the explict form: `i32::zero()` (hm that's silly, but I suspect the original case has a type parameter). With a type parameter it can be written `T::zero()`.

**Comment by nikomatsakis** [comment] 2015-07-24 14:19
I'm going to close this issue, since we've decided that the breakage due to `extend` is acceptable.

**Closed by nikomatsakis** 2015-07-24 14:19 UTC
Labels: I-stable-regression, P-high, T-lang
