### ISSUE TITLE
rustc panics when run on a directory

### ISSUE THREAD

**Issue by yujiri8** [rust-lang/rust#74573] opened 2020-07-20 21:33 UTC
I tried running `rustc` on a directory, just to see what would happen. I expected it would error out cleanly. Instead (run with `RUST_BACKTRACE=full`):
```
error: unknown start of token: \u{3}
 --> .:1:1
  |
1 | 
  | ^

error: unknown start of token: \u{0}
 --> .:1:2
  |
1 | 
  | ^

error: unknown start of token: \u{0}
 --> .:1:3
  |
1 | 
  | ^

error: unknown start of token: \u{0}
 --> .:1:4
  |
1 | 
  | ^

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_session/config.rs:474:57
stack backtrace:
   0:        0x80113416b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6f3466a46ea1fa71
   1:        0x80117c94d - core::fmt::write::h4b3edf88f8821136
   2:        0x801119412 - <unknown>
   3:        0x80110cbb8 - <unknown>
   4:        0x80110c914 - <unknown>
   5:        0x8035966c8 - rustc_driver::report_ice::hfb8c91a979a11aee
   6:        0x80110d1aa - std::panicking::rust_panic_with_hook::h7581696dce7a5dca
   7:        0x80110cdbc - rust_begin_unwind
   8:        0x80117a7f0 - core::panicking::panic_fmt::h3090bfb5a1bab73b
   9:        0x80117a748 - core::panicking::panic::h875be7b3aac2ca74
  10:        0x808033329 - rustc_session::config::Input::filestem::h1ce567152a0eed98
  11:        0x8037ba40f - rustc_interface::util::build_output_filenames::h5bd25d47ef82cb53
  12:        0x803736f23 - <unknown>
  13:        0x803757051 - rustc_interface::queries::Queries::prepare_outputs::h9577dd08303e86f2
  14:        0x80354fa47 - <unknown>
  15:        0x8035f3228 - <unknown>
  16:        0x803550c16 - <unknown>
  17:        0x80357bce1 - <unknown>
  18:        0x8035a6c07 - <unknown>
  19:        0x8035a80c6 - <unknown>
  20:        0x80355eda0 - <unknown>
  21:        0x801114e8b - <unknown>
  22:        0x8011c1736 - thread_start
                               at /usr/src/lib/libthr/thread/thr_create.c:292

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly running on x86_64-unknown-freebsd

query stack during panic:
end of query stack
error: aborting due to 4 previous errors

```

`rustc --version --verbose`:
```
rustc 1.46.0-nightly
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.46.0-nightly
LLVM version: 10.0
```

OS is FreeBSD 12.1-RELEASE-p6.

**Comment by matthiaskrgr** [comment] 2020-07-20 22:50
What is the name of the directory? What command did you use?
When I do `mkdir a; rustc a` I only get
````
error: couldn't read a: Is a directory (os error 21)

error: aborting due to previous error
````

**Comment by yujiri8** [comment] 2020-07-21 05:57
My directory is `~/code/rust`, but I was running it as `rustc .`. When I run `rustc src`, I get a bunch of the `unknown start of token` errors, but not the panic.

Apparently it has to do with the directory being called `.` - even `rustc ../rust` doesn't crash, even though the actual directory referenced is the same.

My `~/code/rust` consists of a `Cargo.lock`, `Cargo.toml`, and `src/main.rs`. (I think when I first posted this, it was just `~/code/rust/main.rs`, but the original error persists with the current directory strucrure.)

Unrelated: how come Github says *I* added the C-bug label? I didn't.

**Comment by Lonami** [comment] 2020-07-21 06:00
> how come Github says I added the C-bug label? I didn't.

You selected the bug report template when creating the issue.

**Comment by yujiri8** [comment] 2020-07-21 06:09
New findings:

Running it on most directories doesn't yield the unknown start of token errors (and `rustc .` is fine too). There's some pattern to directories it does and doesn't happen with. I'm not sure what it is yet, but it seems to happen with all empty directories and some non-empty ones, and directories that get the `unknown start of token` errors always also get the panic when I run `rustc .` inside them.

**Comment by lzutao** [comment] 2020-07-21 06:11
Cannot reproduce on x86_64-unknown-linux-gnu. Maybe this is a specific platform (FreeBSD) bug.
Also do you run FreeBSD on virtual machine or similar?
Does your home dir is network disk?

**Comment by yujiri8** [comment] 2020-07-21 06:14
I'm running FreeBSD on bare metal, and ZFS (not a network disk). I will try on other platforms tomorrow.

**Comment by bjorn3** [comment] 2020-07-21 09:42
On FreeBSD trying to `read` a directory gives a list of filenames inside that directory instead of returning an error:

![image](https://user-images.githubusercontent.com/17426603/88038636-cd419d00-cb46-11ea-9ad3-f2edf366b7b6.png)

Fun fact: On the early UNIX systems `readdir` was just a utility function to call `read` on a directory and parse the resulting output.

**Comment by t6** [comment] 2020-07-21 11:26
Thankfully FreeBSD 13.0 now returns EISDIR when you attempt to read a directory.  This has also been merged to 12-STABLE.

https://svnweb.freebsd.org/changeset/base/363017

```bash
$ rustc .
error: couldn't read .: Is a directory (os error 21)

error: aborting due to previous error
```

**Comment by lzutao** [comment] 2020-07-21 15:35
I thought this problem was solved long ago in FreeBSD.
Last time I checked I cannot `cat <dir>`.

**Comment by yujiri8** [comment] 2020-07-21 21:10
I can still `cat` directories on FreeBSD. As t6 says, they apparently fixed it in 12-STABLE but not yet in 12.1-RELEASE.

I have never seen the output bjorn3 shows, though. For me the output on catting a directory is one byte long + 2 (matching the size shown by `stat`), and the first byte is always `\x03` and most of the others are `\x00`, though for a large number of files, other bytes appear like `\x43` and `\xff`.

I suppose it's FreeBSD's problem in this case. But for interest's sake, I think I found the pattern of which directories trigger the panic: directories with less than 6 files. If it has 6 or more files, `rustc` just says it's invalid UTF-8, but if it has 5 or less, it seems to try to parse the bytes as code. (I can see similar output writing bytes like `\x03\x00\x00\x00` to a text file and running `rustc` on it, but it can't panic that way because `.` can't refer to a non-directory.)

Who marked Lonami's comment as off-topic? That comment was helpful and I appreciated it :+1:

**Comment by jyn514** [comment] 2020-07-23 02:57
> it has 5 or less, it seems to try to parse the bytes as code. 

Maybe this is related to the shebang parsing? I think that's special cased in the lexer.

**Comment by lzutao** [comment] 2020-07-23 11:30
The unwrap happens here: https://github.com/rust-lang/rust/blob/2bbfa02b1b15974d5772b520aa027bf79f8c248e/src/librustc_session/config.rs#L474
Note that the panic happens if `ifile` is empty.

**Comment by yujiri8** [comment] 2022-12-06 21:46
Hey, just realized this is still open. AFAIK the panic only ever happened on FreeBSD <=12.1, which is now EOL, so even if it still happens, I think this should be closed?

**Closed** 2022-12-06 22:02 UTC
Labels: I-ICE, O-freebsd, C-bug
