### ISSUE TITLE
Higher-ranked `fn` pointers can be cast but no longer coerce

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#95132] opened 2022-03-20 04:18 UTC
### Code

[I tried this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8f3f65c31563b6a80aabbee8d3fb31ab):

```rust
fn f<'long: 'short, 'short>(_: &'short &'long ()) {
    let higher_ranked: for<'any> fn(&'any ()) = |_| {};
    let long: fn(&'long ()) = |_| {};
    let short: fn(&'short()) = |_| {};
    let stat: fn(&'static ()) = |_| {};

    // Contravariance: `fn(&'short ())` is a subtype of `fn(&'long ())`, etc.
    let _: fn(&'static ()) = long;
    let _: fn(&'long ()) = short;

    // The higher-ranked type is a subtype of all of them
    let _: fn(&'static ()) = higher_ranked;
    let _: fn(&'long ()) = higher_ranked;
    let _: fn(&'short ()) = higher_ranked;
}
```

I expected to see this happen: Successful compilation

Instead, this happened: Compiler error:
```

error[E0308]: mismatched types
  --> <source>:12:12
   |
12 |     let _: fn(&'static ()) = higher_ranked;
   |            ^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected fn pointer `fn(&'static ())`
              found fn pointer `for<'any> fn(&'any ())`

error[E0308]: mismatched types
  --> <source>:13:12
   |
13 |     let _: fn(&'long ()) = higher_ranked;
   |            ^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected fn pointer `fn(&'long ())`
              found fn pointer `for<'any> fn(&'any ())`

error[E0308]: mismatched types
  --> <source>:14:12
   |
14 |     let _: fn(&'short ()) = higher_ranked;
   |            ^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected fn pointer `fn(&'short ())`
              found fn pointer `for<'any> fn(&'any ())`
```

### Version it worked on

It most recently worked on: [Rust 1.35](https://rust.godbolt.org/z/YG3x7zjf4).

It works on every version before that which I spot checked (but I did not spot check all of them).

Versions before 1.18.0 cannot coerce a closure to a function pointer, but this variation:
```rust
fn g(_: &()) {}
fn f<'long: 'short, 'short>(_: &'short &'long ()) {
    let higher_ranked: for<'any> fn(&'any ()) = g;

    // The higher-ranked type is a subtype of all of them
    let _: fn(&'static ()) = higher_ranked;
    let _: fn(&'long ()) = higher_ranked;
    let _: fn(&'short ()) = higher_ranked;
}
```
Works all the way back to [Rust 1.0.0](https://rust.godbolt.org/z/q9b1e9oav).

### Versions with regression

[Rust 1.36.0](https://rust.godbolt.org/z/E546715W8) and all those which I spot-checked after this version.

The error changes in [Rust 1.56.0](https://rust.godbolt.org/z/jG7b66sG7) due to one of the #57374 fixes; I didn't track down which.

Current playground, any version.
* Stable version: 1.59.0
* Beta version: 1.60.0-beta.5 (2022-03-18 6ee5a408a3bbc7659863)
* Nightly version: 1.61.0-nightly (2022-03-18 1bfe40d11c3630254504)

### Workaround

[Casting still works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3dd3a39c85a8f44ba787df828fdd1c6c):
```
    let _: fn(&'static ()) = higher_ranked as _;
    let _: fn(&'long ()) = higher_ranked as _;
    let _: fn(&'short ()) = higher_ranked as _;
```

But [RFC 401](https://rust-lang.github.io/rfcs/0401-coercions.html) says this should not be necessary.

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by lcnr** [comment] 2022-03-21 06:44
this broke with the introduction of nll in the 2015 edition, see https://rust.godbolt.org/z/3sr77dP6z, and is caused by `UserTypeAnnotations` being broken in mir. Already working on fixing this, cc #93856

**Comment by apiraino** [comment] 2022-03-21 07:38
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2395132.20Higher-ranked.20.60fn.60.20pointers.20can.20be.20cast.20but.20no.20longe.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by Jules-Bertholet** [comment] 2022-11-08 01:34
The example code now compiles successfully. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dcff38bf18e7c10b3e21a8d3c65f4f26

I believe this issue can be closed.

**Comment by lcnr** [comment] 2022-11-08 09:35
already added tests for this issue in #96515. Closing

**Closed by lcnr** 2022-11-08 09:35 UTC
Labels: P-medium, regression-from-stable-to-stable, C-bug
