### ISSUE TITLE
Parser accepts and ignores arbitrary identifiers after tuple field name

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#59425] opened 2019-03-25 23:53 UTC
```rust
fn main() {
    println!("{}", (1, 2, 3).1XXXXXXXXXfoo_bar_wat_is_going_onXXXXXXX);
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dd23abb1ced10a8e65c7b8bdc45f4e58))

Output:

```
2

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.77s
     Running `target/debug/playground`

```

**Comment by varkor** [comment] 2019-03-26 00:03
Duplicate of https://github.com/rust-lang/rust/issues/59418.

**Closed by varkor** 2019-03-26 00:03 UTC
Labels: A-parser
