### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by miko** [rust-lang/rust#21863] opened 2015-02-02 09:25 UTC
While compiling rust-amqp on archlinux with:
```
$ rustc --version --verbose
rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)
binary: rustc
commit-hash: 1d00c545ede609b9d43fdf9f252c15da5a66dac7
commit-date: 2015-01-30 19:56:34 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```
I get:
```
[rust-amqp]$ RUST_BACKTRACE=1 cargo build
   Compiling rustc-serialize v0.2.10
   Compiling traverse v0.0.6
   Compiling matches v0.1.2
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/infer/region_inference/mod.rs:1015

stack backtrace:
   1:     0x7ffab1c92870 - sys::backtrace::write::h26b40214a7757117H8t
   2:     0x7ffab1cb5be0 - failure::on_fail::h7a79bf921b6662fbzkB
   3:     0x7ffab1c221f0 - rt::unwind::begin_unwind_inner::hfe1c0e12f5e834cfAZA
   4:     0x7ffab1c22d10 - rt::unwind::begin_unwind_fmt::hd85238b7766b1d9c6XA
   5:     0x7ffab1cb5a40 - rust_begin_unwind
   6:     0x7ffab1cfeb30 - panicking::panic_fmt::hbf14918471a5d16aARv
   7:     0x7ffab1d07200 - panicking::panic_bounds_check::h2f556216bcf9eddcBQv
   8:     0x7ffaafe2bf10 - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::infer_variable_values::hf801525cb54c3322mVv
   9:     0x7ffaafe2bba0 - middle::infer::region_inference::RegionVarBindings<'a, 'tcx>::resolve_regions::h243fc1b32cc41503Yyv
  10:     0x7ffaafe4b310 - middle::infer::InferCtxt<'a, 'tcx>::resolve_regions_and_report_errors::h778904889b2bb757d8z
  11:     0x7ffab141f720 - check::compare_method::compare_impl_method::h45a938553ccd0eda93k
  12:     0x7ffab1427d50 - check::check_item::hc325db96fe7f49f3j9l
  13:     0x7ffab142e3a0 - visit::walk_item::h14413110965835539520
  14:     0x7ffab142e3a0 - visit::walk_item::h14413110965835539520
  15:     0x7ffab14f7ad0 - check_crate::closure.33894
  16:     0x7ffab14f25b0 - check_crate::hd5b0ce5ac42bd86cIEz
  17:     0x7ffab221df50 - driver::phase_3_run_analysis_passes::h3a3da09b2eae9713NFa
  18:     0x7ffab2205330 - driver::compile_input::h802d2a6759ac022fBba
  19:     0x7ffab22cb230 - run_compiler::h4517938d3296cfc5l9b
  20:     0x7ffab22c98c0 - thunk::F.Invoke<A, R>::invoke::h5452441173088021345
  21:     0x7ffab22c87f0 - rt::unwind::try::try_fn::h8490101008730471441
  22:     0x7ffab1d20f60 - rust_try_inner
  23:     0x7ffab1d20f50 - rust_try
  24:     0x7ffab22c8aa0 - thunk::F.Invoke<A, R>::invoke::h13338196279056651375
  25:     0x7ffab1ca23b0 - sys::thread::thread_start::h395b8c6815673c5cN3w
  26:     0x7ffaabeea250 - start_thread
  27:     0x7ffab18b4219 - clone
  28:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
Could not compile `traverse`.                                                    
```

**Comment by jdm** [comment] 2015-02-02 09:32
Looks like a duplicate of #21750.

**Closed by jdm** 2015-02-02 09:32 UTC
Labels: I-ICE
