### ISSUE TITLE
rustc doesn't infer the default type parameter

### ISSUE THREAD

**Issue by Hirrolot** [rust-lang/rust#69035] opened 2020-02-10 18:04 UTC
I tried this code:

```rust
#[derive(Default)]
struct T<X = ()>(X);

fn main() {
    // Doesn't work!
    let _ = T::default();
}
```

I expected to see this happen: the compiler should infer `T<()>`, because this is the default type parameter.

Instead, the error is happened:

```
error[E0282]: type annotations needed for `T<X>`
 --> src/main.rs:6:13
  |
6 |     let _ = T::default();
  |         -   ^^^^^^^^^^ cannot infer type for type parameter `X` declared on the struct `T`
  |         |
  |         consider giving this pattern the explicit type `T<X>`, where the type parameter `X` is specified

```
Both the latest stable (1.41.0), beta (1.42.0-beta.3), and nightly (1.43.0) channels produce this error. Is it a bug in type inference?

The playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=89a32442edeabad1e11698eba9e6c4e5

**Comment by jonas-schievink** [comment] 2020-02-10 18:13
Closing as a duplicate of https://github.com/rust-lang/rust/issues/27336

**Closed by jonas-schievink** 2020-02-10 18:13 UTC
Labels: C-bug
