### ISSUE TITLE
"A non-empty glob must import something with the glob's visibility" regression from stable/beta to nightly?

### ISSUE THREAD

**Issue by utkarshkukreti** [rust-lang/rust#37995] opened 2016-11-25 09:10 UTC
The following program compiles on:

* rustc 1.13.0 (2c6933acc 2016-11-07)
* rustc 1.14.0-beta.2 (e627a2e6e 2016-11-16)

but does not compile on:

* rustc 1.15.0-nightly (3bf2be9ce 2016-11-22)

```rust
mod foo {
  mod bar {
    pub use super::*;
  }
}

fn main() {}
```

Error:

```
rustc 1.15.0-nightly (3bf2be9ce 2016-11-22)
error: A non-empty glob must import something with the glob's visibility
 --> <anon>:3:13
  |
3 |     pub use super::*;
  |             ^^^^^^^^^

error: aborting due to previous error
```

Tested both locally and on https://play.rust-lang.org/.

I could not find any mention of this [here](https://github.com/rust-lang/rust/issues?q=is%3Aissue+%22non-empty%22+is%3Aopen) or [here](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20%22non-empty%22%20).

**Comment by utkarshkukreti** [comment] 2016-11-25 09:15
Found this while trying to fix https://github.com/utkarshkukreti/speculate.rs for the latest nightly (it only works on nightly). The library adds `pub use super::*;` to every generated module which probably triggered this.

**Comment by jseyfried** [comment] 2016-11-26 23:06
@utkarshkukreti Thanks for the report!

This was intentional -- it was caused by #37127, which stabilized [RFC 1560](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md) (the error is described in the last paragraph of [this section](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md#re-exports-namespaces-and-visibility)).

This error can always be fixed by removing the `pub` (i.e. `pub use super::*;` -> `use super::*;`).

We would have phased this in with a warning, but we found no breakage on crates.io when we measured it ~1 month ago. The `pub use super::*;` were probably added after we tested for breakage but before #37127 landed.

**Comment by utkarshkukreti** [comment] 2016-11-27 06:42
Ah, I had used `pub` with `use super::*;` because the following code failed to compile previously (and still fails on Stable):

```
struct A;
mod foo {
    use super::*;
    mod bar {
        use super::*;
        fn a() -> A {
            A
        }
    }
}
```

But it looks like it does compile on the new Nightly now, so I'll just use that. Thanks @jseyfried!

**Closed** 2016-11-27 06:42 UTC
Labels: A-resolve

**Comment by utkarshkukreti** [comment] 2016-11-27 07:00
> The `pub use super::*;` were probably added after we tested for breakage but before #37127 landed.

It's been there since January 2015 in my crate but my crate only works on nightly as it's a compiler plugin so it probably isn't tested by Crater.
