### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL'

### ISSUE THREAD

**Issue by SStarosielec** [rust-lang/rust#92120] opened 2021-12-20 08:34 UTC
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\compiler\rustc_serialize\src\opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-pc-windows-msvc
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
error: could not compile `tracing-futures`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by hkratz** [comment] 2021-12-20 11:16
Duplicate of #91663, best to upgrade to a later nightly build.

**Closed** 2021-12-20 11:23 UTC
Labels: I-ICE, T-compiler, C-bug
