### ISSUE TITLE
`-Zthreads=8` starts panicking a lot more frequently since today's nightly

### ISSUE THREAD

**Issue by flippette** [rust-lang/rust#130088] opened 2024-09-07 19:44 UTC
Pretty much what the title says, I've narrowed it down to `-Zthreads=8` and today's nightly with the following:

```
$ rustup toolchain list
nightly-2024-09-05-x86_64-unknown-linux-gnu
nightly-2024-09-06-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
$ rustc +nightly-2024-09-05 -V
rustc 1.83.0-nightly (4ac7bcbaa 2024-09-04)
$ rustc +nightly-2024-09-06 -V
rustc 1.83.0-nightly (9c01301c5 2024-09-05)
$ rustc -V
rustc 1.83.0-nightly (26b5599e4 2024-09-06)
$ for i in $(seq 1 64); do cargo +nightly-2024-09-05 build -q; cargo clean -q; done
$ echo $?
0
$ for i in $(seq 1 64); do cargo +nightly-2024-09-06 build -q; cargo clean -q; done
$ echo $?
0
$ for i in $(seq 1 64); do env RUSTFLAGS="-Zthreads=1" cargo build -q; cargo clean; done
$ echo $?
0
$ for i in $(seq 1 64); do cargo build -q; cargo clean -q; done
<almost immediately ICEs>
```

I've attached some `rustc` backtraces.
[rustc-ice-2024-09-07T19_02_57-44339.txt](https://github.com/user-attachments/files/16919729/rustc-ice-2024-09-07T19_02_57-44339.txt)
[rustc-ice-2024-09-07T19_40_47-164056.txt](https://github.com/user-attachments/files/16919730/rustc-ice-2024-09-07T19_40_47-164056.txt)
[rustc-ice-2024-09-07T19_40_45-162317.txt](https://github.com/user-attachments/files/16919731/rustc-ice-2024-09-07T19_40_45-162317.txt)
[rustc-ice-2024-09-07T19_40_44-161289.txt](https://github.com/user-attachments/files/16919732/rustc-ice-2024-09-07T19_40_44-161289.txt)

**Comment by matthiaskrgr** [comment] 2024-09-07 19:50
probably duplicate of https://github.com/rust-lang/rust/issues/129112 but made more prevalent by next solver

**Comment by jieyouxu** [comment] 2024-09-07 21:30
Is it possible to provide a link to or a snippet of a reproducer? I know it probably happens to various crates, but it still would be nice to have something that reproduces.

**Comment by nuudlman** [comment] 2024-09-07 21:31
See https://github.com/rust-lang/rust/issues/130089 for an attached repro.

**Comment by flippette** [comment] 2024-09-07 21:49
The repro case is basically the same as #130089, but with other crates mentioned in the ICE logs from the issue comment.

**Closed** 2024-09-10 10:01 UTC
Labels: I-ICE, T-compiler, C-bug, WG-compiler-parallel, WG-trait-system-refactor, S-needs-repro
