### ISSUE TITLE
Specialization for StepBy<ops::Range<T>>

### ISSUE THREAD

**Issue by dhulke** [rust-lang/rust#108615] opened 2023-03-01 17:14 UTC
### Evidence

I remember seeing this commit that specialized StepBy for ops::Range<T> and today when looking back at the library's source code I saw that the specialization is gone.
Here's the specialization commit merged: https://github.com/rust-lang/rust/commit/95979dcfb201f1d6906a2f256e5e311513cab4ea
Here's the current code for StepBy::next(): https://github.com/rust-lang/rust/blob/master/library/core/src/iter/adapters/step_by.rs#L34

Why was this specialization removed and can we add it back?

**Comment by Nilstrieb** [comment] 2023-03-01 17:19
The PR was immediately reverted in #56049 because it was broken.

**Comment by jyn514** [comment] 2023-03-01 17:23
I don't think this should be treated as a regression.

**Comment by dhulke** [comment] 2023-03-01 17:26
@Nilstrieb Thank you, I missed that revert. I might pick this up in the next couple of weeks then. Should we close the issue and I open a new discussion with a PR pointing to this issue in the future?

**Comment by Nilstrieb** [comment] 2023-03-01 17:44
Keeping it open is fine, it's a suggestion for an improvement to the standard library

**Comment by the8472** [comment] 2023-03-01 22:43
This would be a welcome improvement, e.g. in #103779 I had to handroll loops because range + step_by wasn't up to snuff.

https://github.com/rust-lang/rust/blob/f77bfb7336f21bfe6a5fb5f7358d4406e2597289/library/core/src/str/pattern.rs#L1832-L1838

**Comment by the8472** [comment] 2023-05-20 15:21
Closing as duplicate of #51557

**Closed** 2023-05-20 15:21 UTC
Labels: C-enhancement, T-libs
