### ISSUE TITLE
Wrong uppercase for `ß`

### ISSUE THREAD

**Issue by vbrandl** [rust-lang/rust#79660] opened 2020-12-03 11:12 UTC
I tried this code:

```rust
println!("{}", 'ß'.to_uppercase());
```

I expected to see this happen:

I expected this to print `ẞ` (see [Capital `ẞ`](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E)).

Instead, this happened:

The code printed `SS` which is often use to represent `ß` in uppercase.

Since there is a dedicated character for the capital `ẞ` (which looks really similar to the lowercase `ß` in this font), I think `to_uppercase` should return the actual uppercase letter instead of `SS`.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

`rustc +nightly --version --verbose`:
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
binary: rustc
commit-hash: 1c389ffeff814726dec325f0f2b0c99107df2673
commit-date: 2020-11-24
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

**Comment by lcnr** [comment] 2020-12-03 13:08
> i.e. variants STRASSE vs. STRAẞE would be accepted as equally valid

(quickly scraped from https://en.wikipedia.org/wiki/%C3%9F#Capital_form)

I have never seen `ẞ`, even though I live in germany, and am not sure if changing this is preferable right now as the generally used capitalization is still `SS` from what I can tell.

**Comment by vbrandl** [comment] 2020-12-03 13:22
While both are valid and the former one is used more often (actually I've never seen a capital `ẞ` in use and I'm from Germany, too), `ẞ` is the correct uppercase letter for `ß`...

**Comment by nikic** [comment] 2020-12-03 13:44
Rust follows case mapping rules specified by Unicode, which specs that ß must map to SS under default SpecialCasing rules.

**Comment by bjorn3** [comment] 2020-12-03 14:02
This has been the case since https://github.com/rust-lang/rust/pull/26039

**Comment by RalfJung** [comment] 2020-12-20 14:30
> Rust follows case mapping rules specified by Unicode, which specs that ß must map to SS under default SpecialCasing rules.

So, given this -- is there even a bug here? One might consider this a Unicode bug, but even that is not clear, and Rust seems to be working as intended by matching what Unicode specifies.

**Comment by Alexendoo** [comment] 2020-12-21 13:05
Unicode doesn't consider it a bug - https://www.unicode.org/faq/casemap_charprop.html#11

**Comment by RalfJung** [comment] 2020-12-21 13:14
All right, closing as "not a bug" then. Thanks all!

**Closed by RalfJung** 2020-12-21 13:14 UTC
Labels: A-unicode, C-bug, T-libs
