### ISSUE TITLE
Error messages for `?` are not great

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#37671] opened 2016-11-09 19:03 UTC
```
fn main() {
    Ok("lol")?;
}
```

```
$ rustc test.rs
error[E0277]: the trait bound `(): std::ops::Carrier` is not satisfied
 --> test.rs:2:5
  |
2 |     Ok("lol")?;
  |     ^^^^^^^^^^ the trait `std::ops::Carrier` is not implemented for `()`
  |
  = note: required by `std::ops::Carrier::from_error`

error: aborting due to previous error
```

@eddyb says this can be improved by adding ` #[rustc_on_unimplemented = "the type `{Self}` cannot be used with `?`"]` to something (maybe the `Carrier` trait.

crib off of [fmt](https://github.com/rust-lang/rust/blob/02aa42860d6e74dfa57824f79bdc9c57665d6af0/src/libcore/fmt/mod.rs#L401-L403)

cc @jonathandturner @nikomatsakis @nrc

**Comment by nagisa** [comment] 2016-11-10 03:36
Duplicate of https://github.com/rust-lang/rust/issues/35946

**Comment by steveklabnik** [comment] 2016-11-10 17:43
Yes, and `on_unimplemented` is in that thread as well.

**Closed by steveklabnik** 2016-11-10 17:43 UTC
Labels: A-diagnostics, E-easy, I-enhancement, I-papercut, T-compiler
