### ISSUE TITLE
Compiler panic on extern function within struct implementation

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#22487] opened 2015-02-18 13:56 UTC
The compiler panics when you put an extern function inside a structure implementation.
```
struct Dummy;
impl Dummy {
    pub extern fn printme() {
        println!("Hello...");
    }
}

fn main() {
    Dummy::printme();
}
```

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: f.abi == Rust || f.abi == RustCall', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/trans/base.rs:2440
```
Try it: http://is.gd/MUQsZd

**Comment by nagisa** [comment] 2015-02-18 13:59
Duplicate of https://github.com/rust-lang/rust/issues/21238

**Closed** 2015-02-18 14:23 UTC
