### ISSUE TITLE
CJK letters in rustdoc are not rendered in serif font when using Firefox

### ISSUE THREAD

**Issue by osanshouo** [rust-lang/rust#76674] opened 2020-09-13 14:28 UTC
CJK letters in rustdoc are not rendered in serif font when using Firefox, although Chromium Edge renders them correctly.

### Steps to reproduce:
Open https://docs.rs/koyomi/0.3.0/koyomi/fn.era.html (Japanese) or https://docs.rs/chinese-variant/1.0.7/chinese_variant/ (Chinese) in Firefox.

Alternatively, run `cargo doc` command to generate a document including CJK letters, and open it in Firefox.

### Expected result:
CJK letters should be rendered in serif font, as ASCII letters. 

Here are screenshots of rendering by Chromium Edge (v85.0.564.51) on Windows 10 v1909. Here, CJK letters are rendered in serif font.

![image](https://user-images.githubusercontent.com/53166653/93020005-bcc51480-f615-11ea-9014-dd552a65d401.png)

![image](https://user-images.githubusercontent.com/53166653/93020318-49240700-f617-11ea-96b1-53250fe67958.png)

### Actual result:
With using Firefox v80.0.1 on Windows 10 v1909, CJK letters are not rendered in serif font, but in the browser's default font (san-serif font). Note that ASCII letters are rendered in serif font.

![image](https://user-images.githubusercontent.com/53166653/93020010-c189c880-f615-11ea-9b31-1a42bea1ff4c.png)

![image](https://user-images.githubusercontent.com/53166653/93020326-5214d880-f617-11ea-9353-bd5941d2063e.png)

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```

**Comment by nagisa** [comment] 2020-09-13 17:18
I can confirm this. Seems like a browser bug. Even if just `serif` is specified, the browser selects a sans-serif font (in my case `Source Han Sans`) even though I have a serif font available too (`Source Han Serif`).

**Comment by jyn514** [comment] 2020-09-13 21:46
> Seems like a browser bug.

Should this be closed then?

**Comment by jyn514** [comment] 2020-09-17 16:46
Closing this since it's not a bug in rustdoc.

**Closed by jyn514** 2020-09-17 16:46 UTC
Labels: C-bug, T-rustdoc
