### ISSUE TITLE
Include file in the documentation

### ISSUE THREAD

**Issue by Yamakaky** [rust-lang/rust#37901] opened 2016-11-20 20:11 UTC
It would be useful to be able a file in the documentation. My use-case is to include `examples/quickstart.rs` in the documentation of `lib.rs`. I could copy it, but it would be duplicated in the two files.

**Comment by euclio** [comment] 2016-11-21 14:59
This would also be useful for including markdown documents in the source.  For example,

`#![doc(include = "README.md")]`

Could avoid duplication between the main library documentation and the project's README file.

**Comment by Yamakaky** [comment] 2016-11-21 15:15
yes!

**Comment by steveklabnik** [comment] 2016-11-21 16:58
Duplicate of https://github.com/rust-lang/rust/issues/15470, thanks!

**Closed by steveklabnik** 2016-11-21 16:58 UTC
Labels: A-rustdoc

**Comment by gilescope** [comment] 2021-07-27 11:16
For anyone that gets here from google the answer after following the trail is now:

`#![doc = include_str!("core_arch_docs.md")]`

 (see https://github.com/rust-lang/stdarch/pull/1013 )
