### ISSUE TITLE
rustc freeze whole system

### ISSUE THREAD

**Issue by SCareAngel** [rust-lang/rust#28974] opened 2015-10-11 21:17 UTC
My system freezes when I try to compile this
https://gist.github.com/SCareAngel/9cb3e50c1734d4179fc4
rustc 1.5.0-nightly (e362679bb 2015-10-08)
ubuntu-15.04

**Comment by dotdash** [comment] 2015-10-11 21:32
Code:
```rust


macro_rules! foo {
    ( $e:expr) => { ($e) }
}

macro_rules! bar {
    ( < $x:ident > ) => { $x };
    ( $x:tt ) => { foo!($x) };
}

macro_rules! baz {
    ( $ ( $( $x:tt )|*)* ) => {
        {
            make($n, &[$(&[$(bar!($x)
	    ),*]),*])
        }
    };
}


fn main() {
    let bar = baz!["0","1","2","3","4","5","6","7","8","9"];
}
```

That's eating memory really really quickly. It's even enough to just say `let bar = baz![];`, the values aren't required.

**Comment by jonas-schievink** [comment] 2015-10-11 21:36
Might be related to #24858

**Comment by huonw** [comment] 2015-10-12 06:24
It does look like a dupe of #24858, closing. Thanks for filing!

**Closed by huonw** 2015-10-12 06:24 UTC
Labels: A-macros
