### ISSUE TITLE
Stack getting overflowed when Im boxing an array

### ISSUE THREAD

**Issue by 0xN1nja** [rust-lang/rust#110042] opened 2023-04-07 07:57 UTC
I tried this code:

```rust
let a=Box::new([0;10000000]);
```

I expected that it would allocate array on the heap but instead, it panicked : `thread 'main' has overflowed its stack`

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-pc-windows-msvc
release: 1.68.0
LLVM version: 15.0.6
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' has overflowed its stack
error: process didn't exit successfully: `target\debug\rusty-image-resizer.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)
```

</p>
</details>

**Comment by Nilstrieb** [comment] 2023-04-07 09:18
Thanks for the report, but I'll close it as a duplicate of #53827

**Closed by Nilstrieb** 2023-04-07 09:18 UTC
Labels: C-bug

**Comment by Nilstrieb** [comment] 2023-04-07 09:19
But the recommend workaround is to use `vec![0; 100000].into_boxed_slice().try_into().unwrap()` instead.
