### ISSUE TITLE
error: internal compiler error: unexpected concrete region in borrowck: ReStatic

### ISSUE THREAD

**Issue by MattiaFailla** [rust-lang/rust#87605] opened 2021-07-29 19:37 UTC
### Code
--> /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/evm-0.26.0/src/executor/stack/state.rs:496:2
```Rust
     
      |
  496 | /     pub fn deconstruct(
  497 | |         self
  498 | |     ) -> (impl IntoIterator<Item=Apply<impl IntoIterator<Item=(H256, H256)>>>,
  499 | |            impl IntoIterator<Item=Log>)
  500 | |     {
  501 | |         self.substate.deconstruct(self.backend)
  502 | |     }
      | |_____^
      |
```
 = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1
```

### Error output

```
  error: internal compiler error: unexpected concrete region in borrowck: ReStatic
     --> /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/evm-0.26.0/src/executor/stack/state.rs:496:2
      |
  496 | /     pub fn deconstruct(
  497 | |         self
  498 | |     ) -> (impl IntoIterator<Item=Apply<impl IntoIterator<Item=(H256, H256)>>>,
  499 | |            impl IntoIterator<Item=Log>)
  500 | |     {
  501 | |         self.substate.deconstruct(self.backend)
  502 | |     }
      | |_____^
      |
      = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44

  thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

  note: rustc 1.56.0-nightly (b70888601 2021-07-28) running on x86_64-unknown-linux-gnu

  note: compiler flags: -C opt-level=3 -C panic=abort -C linker-plugin-lto -C link-arg=--export-table -C link-arg=--import-memory -C link-arg=--export=__heap_base --crate-type lib

  note: some of the compiler flags provided by cargo are hidden

  query stack during panic:
  end of query stack
  error: could not compile `evm`
  warning: build failed, waiting for other jobs to finish...
  error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:19: recipe for target 'build' failed
make: *** [build] Error 101

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Caused by:
  process didn't exit successfully: `/home/mat/REEF/reef-chain/target/release/build/reef-runtime-e2dad6f953f2d837/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "rustup" "run" "nightly" "cargo" "-Zfeatures=build_dep" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/mat/REEF/reef-chain/target/release/wbuild/reef-runtime/Cargo.toml" "--color=always" "--release"
  Using rustc version: rustc 1.56.0-nightly (b70888601 2021-07-28)


  --- stderr
  warning: flag `-Z features` has been stabilized in the 1.51 release, and is no longer necessary
    The new feature resolver is now available by specifying `resolver = "2"` in Cargo.toml.
    See https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2 for more information.

     Compiling evm v0.26.0
     Compiling sp-runtime v3.0.0
  error: internal compiler error: unexpected concrete region in borrowck: ReStatic
     --> /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/evm-0.26.0/src/executor/stack/state.rs:496:2
      |
  496 | /     pub fn deconstruct(
  497 | |         self
  498 | |     ) -> (impl IntoIterator<Item=Apply<impl IntoIterator<Item=(H256, H256)>>>,
  499 | |            impl IntoIterator<Item=Log>)
  500 | |     {
  501 | |         self.substate.deconstruct(self.backend)
  502 | |     }
      | |_____^
      |
      = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44

  thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/b70888601af92f6cdc0364abab3446e418b91d36/library/std/src/panicking.rs:515:5
     1: std::panicking::begin_panic_fmt
               at /rustc/b70888601af92f6cdc0364abab3446e418b91d36/library/std/src/panicking.rs:457:5
     2: rustc_errors::HandlerInner::flush_delayed
     3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
     4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
     5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
     6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
     7: rustc_span::with_source_map
     8: rustc_interface::interface::create_compiler_and_run
     9: scoped_tls::ScopedKey<T>::set
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

  note: rustc 1.56.0-nightly (b70888601 2021-07-28) running on x86_64-unknown-linux-gnu

  note: compiler flags: -C opt-level=3 -C panic=abort -C linker-plugin-lto -C link-arg=--export-table -C link-arg=--import-memory -C link-arg=--export=__heap_base --crate-type lib

  note: some of the compiler flags provided by cargo are hidden

  query stack during panic:
  end of query stack

```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-07-29 19:54
duplicate of https://github.com/rust-lang/rust/issues/87455

**Closed by jonas-schievink** 2021-07-29 19:54 UTC
Labels: C-bug, I-ICE, T-compiler
