### ISSUE TITLE
ICE when compile redis on the last nightly

### ISSUE THREAD

**Issue by p0lunin** [rust-lang/rust#81600] opened 2021-01-31 17:06 UTC
### Code

https://github.com/teloxide/teloxide/pull/335/checks?check_run_id=1801759422#step:4:650

### Meta
```
rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu
```

### Error output

```
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.16.0/src/macros.rs:5:54
    |
5   |           return Err(::std::convert::From::from($expr));
    |                                                        ^
    | 
   ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.16.0/src/aio.rs:377:18
    |
377 |               _ => fail!((
    |  __________________-
378 | |                 ErrorKind::ResponseError,
379 | |                 "Redis server refused to switch database"
380 | |             )),
    | |______________- in this macro invocation
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Aaron1011** [comment] 2021-01-31 17:13
This will be fixed by https://github.com/rust-lang/rust/pull/81541

**Comment by WaffleLapkin** [comment] 2021-01-31 20:02
duplicate of #81531

**Comment by camelid** [comment] 2021-02-01 03:56
Closing as duplicate of #81531.

**Closed by camelid** 2021-02-01 03:56 UTC
Labels: C-bug, I-ICE, T-compiler
