### ISSUE TITLE
Linking errors on recent Nightly releases

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#65418] opened 2019-10-14 21:20 UTC
The compiler since some time gives a linking error:

Good:
rustc 1.40.0-nightly (898f36c83 2019-10-10)
binary: rustc
commit-hash: 898f36c83cc28d7921a1d7b3605323dc5cfcf533
commit-date: 2019-10-10
host: x86_64-pc-windows-gnu
release: 1.40.0-nightly
LLVM version: 9.0

Bad:
rustc 1.40.0-nightly (6767d9b90 2019-10-11)
binary: rustc
commit-hash: 6767d9b90b6b630ad8e2a9e5e02fd74c00c98759
commit-date: 2019-10-11
host: x86_64-pc-windows-gnu
release: 1.40.0-nightly
LLVM version: 9.0

error: linking with `gcc` failed: exit code: 1
...
  = note: gcc.exe: error: crt2.o: No such file or directory
          gcc.exe: error: rsbegin.o: No such file or directory
          gcc.exe: error: rsend.o: No such file or directory

**Comment by sfackler** [comment] 2019-10-14 21:32
Duplicate of #65335

**Closed by sfackler** 2019-10-14 21:32 UTC
