### ISSUE TITLE
1.41.0: extremely long compile times on some constants

### ISSUE THREAD

**Issue by antifuchs** [rust-lang/rust#68873] opened 2020-02-06 02:36 UTC
This is a re-run of #67539: That bug seems to have gotten fixed on nightly, but seems to have missed the window for stable, or something? 

Repro case: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac61ec2c5bdd65e3f5d488e18e457530 - rustc will time out compiling this (run for more than 20 minutes, I haven't seen it finish in my lifetime).

Is this something that will/can be fixed by the next stable release? It's blocking some of my (otherwise perfectly valid) code from running in CI.

**Comment by Mark-Simulacrum** [comment] 2020-02-06 02:50
https://github.com/rust-lang/rust/pull/67667 was not beta-nominated, likely because the original bug report was (mis?)categorized as a nightly regression. It appears to be in beta, though, so it should be in stable in ~5 weeks.

I don't believe that we are currently likely to issue a stable point release. However, I have nominated the relevant PR for approval by the compiler team.

Since the bug is fixed on nightly (and indeed on beta), closing this issue, as we don't generally track fixed bugs. In the future, if you've noticed that a bug is not fixed on beta but has been fixed on nightly, please don't hesitate to let us know (filing a new issue is the best bet).

**Closed by Mark-Simulacrum** 2020-02-06 02:50 UTC

**Comment by antifuchs** [comment] 2020-02-06 03:04
Thanks so much for the clarification & nominating this. Understandable that new patch releases aren't cut for any old bug. 5 weeks sounds like a reasonable time for a fix - I'll run that one crate's benchmarks on beta/nightly for now (:
