### ISSUE TITLE
ICE: serde_json triggers LLVM ERROR: Broken module found, compilation aborted!

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#56504] opened 2018-12-04 13:58 UTC
```toml
cargo-features = ["profile-overrides"]

[profile.dev.overrides."*"]
opt-level = 3
```
```
!dbg attachment points at wrong subprogram for function
!819 = distinct !DISubprogram(name: "deserialize<serde_json::de::MapKey<serde_js
on::read::StrRead>>", linkageName: "_ZN5serde2de5impls89_$LT$impl$u20$serde..de.
.Deserialize$LT$$u27$de$GT$$u20$for$u20$alloc..string..String$GT$11deserialize17
h1d523c846d175462E", scope: !821, file: !820, line: 418, type: !823, isLocal: tr
ue, isDefinition: true, scopeLine: 418, flags: DIFlagPrototyped, isOptimized: tr
ue, unit: !212, templateParams: !955, retainedNodes: !953)
void (%"core::result::Result<alloc::string::String, error::Error>"*, i64*)* @"_Z
N5serde2de5impls89_$LT$impl$u20$serde..de..Deserialize$LT$$u27$de$GT$$u20$for$u2
0$alloc..string..String$GT$11deserialize17h1d523c846d175462E"
  call void @llvm.dbg.value(metadata [0 x i8]* %24, metadata !1083, metadata !DI
Expression(DW_OP_LLVM_fragment, 0, 64)), !dbg !1091
!1091 = !DILocation(line: 1, scope: !1084)
!1084 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", link
ageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visito
r$LT$$u27$de$GT$$GT$9visit_str17hf7794eda537869afE", scope: !821, file: !820, li
ne: 322, type: !1085, isLocal: true, isDefinition: true, scopeLine: 322, flags:
DIFlagPrototyped, isOptimized: true, unit: !212, templateParams: !1089, retained
Nodes: !1087)
!1084 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", link
ageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visito
r$LT$$u27$de$GT$$GT$9visit_str17hf7794eda537869afE", scope: !821, file: !820, li
ne: 322, type: !1085, isLocal: true, isDefinition: true, scopeLine: 322, flags:
DIFlagPrototyped, isOptimized: true, unit: !212, templateParams: !1089, retained
Nodes: !1087)
!dbg attachment points at wrong subprogram for function
!819 = distinct !DISubprogram(name: "deserialize<serde_json::de::MapKey<serde_js
on::read::StrRead>>", linkageName: "_ZN5serde2de5impls89_$LT$impl$u20$serde..de.
.Deserialize$LT$$u27$de$GT$$u20$for$u20$alloc..string..String$GT$11deserialize17
h1d523c846d175462E", scope: !821, file: !820, line: 418, type: !823, isLocal: tr
ue, isDefinition: true, scopeLine: 418, flags: DIFlagPrototyped, isOptimized: tr
ue, unit: !212, templateParams: !955, retainedNodes: !953)
void (%"core::result::Result<alloc::string::String, error::Error>"*, i64*)* @"_Z
N5serde2de5impls89_$LT$impl$u20$serde..de..Deserialize$LT$$u27$de$GT$$u20$for$u2
0$alloc..string..String$GT$11deserialize17h1d523c846d175462E"
  call void @llvm.dbg.value(metadata [0 x i8]* %27, metadata !1083, metadata !DI
Expression(DW_OP_LLVM_fragment, 0, 64)), !dbg !1094
!1094 = !DILocation(line: 1889, scope: !1084, inlinedAt: !1095)
!1133 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", link
ageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visito
r$LT$$u27$de$GT$$GT$9visit_str17hf7794eda537869afE", scope: !821, file: !820, li
ne: 322, type: !1134, isLocal: true, isDefinition: true, scopeLine: 322, flags:
DIFlagPrototyped, isOptimized: true, unit: !212, templateParams: !1139, retained
Nodes: !1136)
!1133 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", link
ageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visito
r$LT$$u27$de$GT$$GT$9visit_str17hf7794eda537869afE", scope: !821, file: !820, li
ne: 322, type: !1134, isLocal: true, isDefinition: true, scopeLine: 322, flags:
DIFlagPrototyped, isOptimized: true, unit: !212, templateParams: !1139, retained
Nodes: !1136)
LLVM ERROR: Broken module found, compilation aborted!
error: Could not compile `serde_json`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

>  rustc 1.32.0-nightly (6bfb46e4a 2018-11-26)

Btw, it works without the profile override.

**Comment by nikic** [comment] 2018-12-04 14:11
Duplicate of #56265, which has been fixed in the meantime. I see that you're using the nightly from 2018-11-26, which was still broken. Updating to a newer nightly should resolve this issue :)

**Closed by nikic** 2018-12-04 14:11 UTC
