### ISSUE TITLE
Failure to build crates with `split-debuginfo = "packed"`, and `lto = "fat"`

### ISSUE THREAD

**Issue by Mythra** [rust-lang/rust#104042] opened 2022-11-06 04:19 UTC
I tried to build my codebase with the following, profile:

```toml
[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"
panic = "abort"
split-debuginfo = "packed"
strip = "none"
```

I expected to see this happen: to be able to build the binary, with debug info being split out.

Instead, this happened, I got an error:

```
error: failed to build archive: No such file or directory

error: could not compile `cfg-if` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `pin-project-lite` due to previous error
error: could not compile `scopeguard` due to previous error
error: could not compile `itoa` due to previous error
error: could not compile `once_cell` due to previous error
error: could not compile `smallvec` due to previous error
error: could not compile `bytes` due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

I tried on beta (output is the same):
`rustup run beta rustc --version --verbose`:

```
rustup run beta rustc --version --verbose
rustc 1.66.0-beta.1 (e080cc5a6 2022-11-01)
binary: rustc
commit-hash: e080cc5a659fb760c0bc561b722a790dad35b5e1
commit-date: 2022-11-01
host: x86_64-unknown-linux-gnu
release: 1.66.0-beta.1
LLVM version: 15.0.2
```

I also tried running on nightly (output is the same):
`rustup run nightly rustc --version --verbose`:

```
rustc 1.67.0-nightly (1286ee23e 2022-11-05)
binary: rustc
commit-hash: 1286ee23e4e2dec8c1696d3d76c6b26d97bbcf82
commit-date: 2022-11-05
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

<details><summary>No backtrace, but full command output</summary>
<p>

```
$ RUST_BACKTRACE=full cargo build --release
   Compiling libc v0.2.137
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.16.0
   Compiling itoa v1.0.4
   Compiling pin-project-lite v0.2.9
   Compiling smallvec v1.10.0
   Compiling bytes v1.2.1
   Compiling proc-macro2 v1.0.47
   Compiling quote v1.0.21
   Compiling syn v1.0.103
   Compiling serde_derive v1.0.147
   Compiling lock_api v0.4.9
   Compiling memchr v2.5.0
   Compiling log v0.4.17
   Compiling serde v1.0.147
   Compiling tokio v1.21.2
   Compiling generic-array v0.14.6
   Compiling scopeguard v1.1.0
   Compiling ahash v0.7.6
   Compiling slab v0.4.7
   Compiling futures-channel v0.3.25
   Compiling futures-task v0.3.25
   Compiling parking_lot_core v0.9.4
   Compiling futures-util v0.3.25
   Compiling typenum v1.15.0
error: failed to build archive: No such file or directory

   Compiling serde_json v1.0.87
   Compiling futures-core v0.3.25
error: could not compile `cfg-if` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `pin-project-lite` due to previous error
error: could not compile `scopeguard` due to previous error
error: could not compile `itoa` due to previous error
error: could not compile `once_cell` due to previous error
error: could not compile `smallvec` due to previous error
error: could not compile `log` due to previous error
error: could not compile `bytes` due to previous error
error: could not compile `memchr` due to previous error
error: could not compile `libc` due to previous error
```

</p>
</details>

**Comment by ehuss** [comment] 2022-11-06 14:09
Thanks for the report!  This has been reported earlier, closing as a duplicate of #103932.

**Closed by ehuss** 2022-11-06 14:09 UTC
Labels: C-bug

**Comment by Mythra** [comment] 2022-11-06 15:56
Thanks, I had seen that , but wasn't quite sure. Sorry for the dupe!
