### ISSUE TITLE
unused function is not monomorphized, so post-mono lints do not show up (in particular affects associated and inline consts)

### ISSUE THREAD

**Issue by zirconium-n** [rust-lang/rust#106617] opened 2023-01-09 04:15 UTC
I tried this code:

```rust
#![feature(inline_const)]

fn run() {
    const { assert!(false) };
}
```

I expected to see this happen: compile error.

Instead, this happened: compile passes.

If I change the visibility of `fn run` to `pub`, it will throw a compile error.

For comparison, const value always throw a compile error even if the const is never used.

```rust

const X: i32 = {
    assert!(false);   // This will error!
    1
};
```

**Comment by scottmcm** [comment] 2023-01-09 04:29
Hi lang (and maybe @RalfJung)!  I'll miss the meeting on Tuesday, but I figured I'd nominate this since the feature is in FCP now.

Do we expect that inline consts in non-generic unused private functions aren't evaluated?

**Comment by nbdd0121** [comment] 2023-01-09 04:55
This is intentional, as the same behaviour is true for associated consts.

```rust
fn run() {
    struct Foo;
    impl Foo {
        const A: () = assert!(false);
    }
    Foo::A
}
```

The use is not collected and evaluated if not monomorphized.

**Comment by zirconium-n** [comment] 2023-01-09 05:40
> This is intentional, as the same behaviour is true for associated consts.
> 
> ```rust
> fn run() {
>     struct Foo;
>     impl Foo {
>         const A: () = assert!(false);
>     }
>     Foo::A
> }
> ```
> 
> The use is not collected and evaluated if not monomorphized.

Actually I won't expect this would compile either. 😕 

Are you sure this is intentional, instead of some accidental behavior?

**Comment by nbdd0121** [comment] 2023-01-09 08:09
It's documented that they are not evaluated if not used, and generic associated consts are evaluated at mono (https://doc.rust-lang.org/beta/reference/items/associated-items.html#associated-constants).

It's not documented when a non-generic associated will evaluated, but it sounds rather inconsistent if it's not also evaluated at monomorphization time.

**Comment by RalfJung** [comment] 2023-01-09 10:47
The problem is that could can write code like this
```rust
fn run<T>() {
    const { assert!(std::mem::size_of::<T>() > 0) };
}
```
Asking to evaluate inline consts in an unused generic function is meaningless, since we can't know the generic parameters.

We could in principle add a special case that applies only to monomorphic functions like your original example. That would not have any direct relation to inline consts though, it affects associated consts just as much.

**Comment by zirconium-n** [comment] 2023-01-11 03:29
> The problem is that could can write code like this
> 
> ```rust
> fn run<T>() {
>     const { assert!(std::mem::size_of::<T>() > 0) };
> }
> ```
> 
> Asking to evaluate inline consts in an unused generic function is meaningless, since we can't know the generic parameters.
> 

Yes, I agree this is meaningless.

> We could in principle add a special case that applies only to monomorphic functions like your original example. That would not have any direct relation to inline consts though, it affects associated consts just as much.

@nbdd0121 gave a pretty good reason why it's handled like this. It's the combined behavior surprised me, but it's understandable.

I'm ok with either way, compile or not. Actually I would prefer less special cases (if we consider it one).

**Comment by nbdd0121** [comment] 2023-01-11 15:52
There is a `-C link-dead-code` option to force non-generic functions being monomorphized.

**Comment by tmandry** [comment] 2023-02-14 19:43
Deferring discussion for now to the design meeting in https://github.com/rust-lang/lang-team/issues/195.

@rustbot label: -I-lang-nominated

**Comment by RalfJung** [comment] 2023-05-25 07:47
Closing in favor of https://github.com/rust-lang/rust/issues/107503 which is basically the same underlying issue.

**Closed by RalfJung** 2023-05-25 07:47 UTC
Labels: C-bug, F-inline_const, A-monomorphization
