### ISSUE TITLE
Generators can't have HRTBs on resume argument.

### ISSUE THREAD

**Issue by kyren** [rust-lang/rust#69300] opened 2020-02-19 21:35 UTC
It seems as though it's not possible currently to write a generator that satisfies this bound:

```
fn accept<G: for<'a> Generator<&'a ()>>(g: G) {}
```

Trying something like this:

```
accept(|r| {
    let r = yield;
});
```

Gives:

```
5  | fn accept<G>(g: G)
   |    ------
6  | where
7  |     G: for<'a> Generator<&'a ()>,
   |        ------------------------- required by this bound in `accept`
...
12 |     accept(|r| {
   |     ^^^^^^
   |     |
   |     expected signature of `for<'a> fn(&'a ()) -> _`
   |     found signature of `fn(_) -> _`
```

I realize that generators are very unstable right now so I doubt this is high priority, but hopefully something like this could work eventually?  I think it might be useful for generators to accept something like a temporary buffer as a resume argument that should only be valid until the next call to yield.

Incidentally, I didn't run into this problem legitimately, I ran into it trying to abuse generators to enable automatic garbage collection ala https://github.com/kyren/gc-arena, but I think that there are also *valid* reasons to want this to work as well 😛

**Comment by jonas-schievink** [comment] 2020-02-19 21:44
Yeah, this would be nice to have. This seems like a duplicate of https://github.com/rust-lang/rust/issues/68923 though, so closing in favor of that.

**Comment by kyren** [comment] 2020-02-19 21:45
Shoot, sorry for the duplicate, I even looked for it and asked on matrix beforehand, my search skills are bad!

**Closed by jonas-schievink** 2020-02-19 21:44 UTC

**Comment by jonas-schievink** [comment] 2020-02-19 21:56
No worries!
