### ISSUE TITLE
[ICE] [NLL] More than one activation at the same location

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#49671] opened 2018-04-04 23:31 UTC
```
#![feature(nll)]
fn main() {
    let mut x = 10;
    let mut y = 10;
    std::mem::swap(&mut x, &mut y);
}


thread 'rustc' panicked at 'More than one activation introduced at the same location.', librustc_mir\dataflow\impls\borrows.rs:216:21
stack backtrace:
   0: mingw_set_invalid_parameter_handler
   1: mingw_set_invalid_parameter_handler
   2: mingw_set_invalid_parameter_handler
   3: mingw_set_invalid_parameter_handler
   4: mingw_set_invalid_parameter_handler
   5: mingw_set_invalid_parameter_handler
   6: mingw_set_invalid_parameter_handler
   7: mingw_set_invalid_parameter_handler
   8: mingw_set_invalid_parameter_handler
   9: mingw_set_invalid_parameter_handler
  10: mingw_set_invalid_parameter_handler
  11: mingw_set_invalid_parameter_handler
  12: mingw_set_invalid_parameter_handler
  13: mingw_set_invalid_parameter_handler
  14: mingw_set_invalid_parameter_handler
  15: mingw_set_invalid_parameter_handler
  16: mingw_set_invalid_parameter_handler
  17: mingw_set_invalid_parameter_handler
  18: mingw_set_invalid_parameter_handler
  19: mingw_set_invalid_parameter_handler
  20: mingw_set_invalid_parameter_handler
  21: mingw_set_invalid_parameter_handler
  22: mingw_set_invalid_parameter_handler
  23: mingw_set_invalid_parameter_handler
  24: mingw_set_invalid_parameter_handler
  25: mingw_set_invalid_parameter_handler
  26: mingw_set_invalid_parameter_handler
  27: mingw_set_invalid_parameter_handler
  28: mingw_set_invalid_parameter_handler
  29: mingw_set_invalid_parameter_handler
  30: mingw_set_invalid_parameter_handler
  31: mingw_set_invalid_parameter_handler
  32: mingw_set_invalid_parameter_handler
  33: mingw_set_invalid_parameter_handler
  34: mingw_set_invalid_parameter_handler
  35: mingw_set_invalid_parameter_handler
  36: mingw_set_invalid_parameter_handler

error: internal compiler error: unexpected panic

note: rustc 1.27.0-nightly (637ac17c5 2018-04-03) running on x86_64-pc-windows-gnu
```

**Comment by pietroalbini** [comment] 2018-04-05 06:55
Duplicate of #49635.
Thanks for reporting this!

**Closed by pietroalbini** 2018-04-05 06:55 UTC
Labels: A-NLL, C-bug, I-ICE, WG-compiler-nll
