### ISSUE TITLE
SIGSEGV on arm

### ISSUE THREAD

**Issue by xTachyon** [rust-lang/rust#63608] opened 2019-08-15 17:24 UTC
Hello. I've been directed to create a issue here after a talk on one of the rust discord servers. Hopefully I got right.

So I'm trying to compile one of my projects on a Raspberry Pi.
``` 
nightly-armv7-unknown-linux-gnueabihf (default)
rustc 1.38.0-nightly (c43d03a19 2019-08-14)
Linux raspberrypi 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux
```

However, something crashes, but I couldn't make much sense of it:

```andrei@raspberrypi:~/repos/x $ cargo build --release
   Compiling libc v0.2.61
   Compiling semver-parser v0.7.0
   Compiling autocfg v0.1.5
   Compiling rand_core v0.4.2
error: Could not compile `rand_core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rand_core /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.4.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="alloc"' --cfg 'feature="std"' -C metadata=75c38b01039d7ba5 -C extra-filename=-75c38b01039d7ba5 --out-dir /home/andrei/repos/x/target/release/deps -L dependency=/home/andrei/repos/x/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
munmap_chunk(): invalid pointer
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.61/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' --cfg 'feature="use_std"' -C metadata=e5dc31559086ca86 -C extra-filename=-e5dc31559086ca86 --out-dir /home/andrei/repos/x/target/release/build/libc-e5dc31559086ca86 -L dependency=/home/andrei/repos/x/target/release/deps --cap-lints allow` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: Could not compile `autocfg`.

Caused by:
  process didn't exit successfully: `rustc --crate-name autocfg /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/autocfg-0.1.5/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=ae28ae53598a464a -C extra-filename=-ae28ae53598a464a --out-dir /home/andrei/repos/x/target/release/deps -L dependency=/home/andrei/repos/x/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: Could not compile `semver-parser`.

Caused by:
  process didn't exit successfully: `rustc --crate-name semver_parser /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.7.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=b84782a7fa092166 -C extra-filename=-b84782a7fa092166 --out-dir /home/andrei/repos/x/target/release/deps -L dependency=/home/andrei/repos/x/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
```

What can I do ? Is this a compiler bug ?

**Comment by memoryruins** [comment] 2019-08-15 20:36
Thanks for reporting! Potentially a duplicate of #62896

**Comment by jonas-schievink** [comment] 2019-08-15 21:03
@xTachyon can you try to reproduce this on stable 1.37 and on the current beta?

**Comment by nagisa** [comment] 2019-08-15 21:32
Alternatively try to reproduce with `RUSTFLAGS='-Ccodegen-units=1'` environment variable set.

**Comment by xTachyon** [comment] 2019-08-16 09:09
So I made a new crate with the only dependency `libc = "0.2.62"` and tried to compile it on stable, beta, nightly, with and without that env variable.

```andrei@raspberrypi:~/repos/testy $ export RUSTFLAGS=""
andrei@raspberrypi:~/repos/testy $ echo ${RUSTFLAGS}

andrei@raspberrypi:~/repos/testy $ cargo -V
cargo 1.37.0 (9edd08916 2019-08-02)
andrei@raspberrypi:~/repos/testy $ rm -r Cargo.lock target
andrei@raspberrypi:~/repos/testy $ cargo build --release
    Updating crates.io index
   Compiling libc v0.2.62
   Compiling testy v0.1.0 (/home/andrei/repos/testy)
    Finished release [optimized] target(s) in 19.87s
andrei@raspberrypi:~/repos/testy $ rustup default beta
info: using existing install for 'beta-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'beta-armv7-unknown-linux-gnueabihf'

  beta-armv7-unknown-linux-gnueabihf unchanged - rustc 1.38.0-beta.1 (e450539c2 2019-08-13)

andrei@raspberrypi:~/repos/testy $ cargo -V
cargo 1.38.0-beta (e853aa976 2019-08-09)
andrei@raspberrypi:~/repos/testy $ rm -r Cargo.lock target
andrei@raspberrypi:~/repos/testy $ cargo build --release
    Updating crates.io index
   Compiling libc v0.2.62
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.62/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=2098fa4b2feb2f48 -C extra-filename=-2098fa4b2feb2f48 --out-dir /home/andrei/repos/testy/target/release/build/libc-2098fa4b2feb2f48 -L dependency=/home/andrei/repos/testy/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
andrei@raspberrypi:~/repos/testy $ rustup default nightly
info: using existing install for 'nightly-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'nightly-armv7-unknown-linux-gnueabihf'

  nightly-armv7-unknown-linux-gnueabihf unchanged - rustc 1.38.0-nightly (c43d03a19 2019-08-14)

andrei@raspberrypi:~/repos/testy $ cargo -V
cargo 1.38.0-nightly (e853aa976 2019-08-09)
andrei@raspberrypi:~/repos/testy $ rm -r Cargo.lock target/
andrei@raspberrypi:~/repos/testy $ cargo build --release
    Updating crates.io index
   Compiling libc v0.2.62
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.62/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=a233ac8b73169014 -C extra-filename=-a233ac8b73169014 --out-dir /home/andrei/repos/testy/target/release/build/libc-a233ac8b73169014 -L dependency=/home/andrei/repos/testy/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)





andrei@raspberrypi:~/repos/testy $ export RUSTFLAGS="-Ccodegen-units=1"
andrei@raspberrypi:~/repos/testy $ echo ${RUSTFLAGS}
-Ccodegen-units=1
andrei@raspberrypi:~/repos/testy $ rustup default stable
info: using existing install for 'stable-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'stable-armv7-unknown-linux-gnueabihf'

  stable-armv7-unknown-linux-gnueabihf unchanged - rustc 1.37.0 (eae3437df 2019-08-13)

andrei@raspberrypi:~/repos/testy $ cargo -V
cargo 1.37.0 (9edd08916 2019-08-02)
andrei@raspberrypi:~/repos/testy $ rm -r Cargo.lock target/
andrei@raspberrypi:~/repos/testy $ cargo build --release
    Updating crates.io index
   Compiling libc v0.2.62
   Compiling testy v0.1.0 (/home/andrei/repos/testy)
    Finished release [optimized] target(s) in 12.95s
andrei@raspberrypi:~/repos/testy $ rustup default beta
info: using existing install for 'beta-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'beta-armv7-unknown-linux-gnueabihf'

  beta-armv7-unknown-linux-gnueabihf unchanged - rustc 1.38.0-beta.1 (e450539c2 2019-08-13)

andrei@raspberrypi:~/repos/testy $ cargo -V
cargo 1.38.0-beta (e853aa976 2019-08-09)
andrei@raspberrypi:~/repos/testy $ rm -r Cargo.lock target/
andrei@raspberrypi:~/repos/testy $ cargo build --release
    Updating crates.io index
   Compiling libc v0.2.62
   Compiling testy v0.1.0 (/home/andrei/repos/testy)
    Finished release [optimized] target(s) in 12.94s
andrei@raspberrypi:~/repos/testy $ rustup default nightly
info: using existing install for 'nightly-armv7-unknown-linux-gnueabihf'
info: default toolchain set to 'nightly-armv7-unknown-linux-gnueabihf'

  nightly-armv7-unknown-linux-gnueabihf unchanged - rustc 1.38.0-nightly (c43d03a19 2019-08-14)

andrei@raspberrypi:~/repos/testy $ cargo -V
cargo 1.38.0-nightly (e853aa976 2019-08-09)
andrei@raspberrypi:~/repos/testy $ rm -r Cargo.lock target/
andrei@raspberrypi:~/repos/testy $ cargo build --release
    Updating crates.io index
   Compiling libc v0.2.62
   Compiling testy v0.1.0 (/home/andrei/repos/testy)
    Finished release [optimized] target(s) in 13.02s```

Looks like it fails only on beta and nightly without the env var set.

**Comment by nikic** [comment] 2019-08-16 09:58
Based on armv7-unknown-linux-gnueabihf target and libc dependency, this is very likely a duplicate of #62896.

**Closed by nikic** 2019-08-16 09:58 UTC
Labels: C-bug, I-crash, O-ARM, T-compiler
