### ISSUE TITLE
Trying to compile rocket_sync_db_pools with nightly

### ISSUE THREAD

**Issue by maccesch** [rust-lang/rust#95053] opened 2022-03-17 20:25 UTC
### Code

No special code. Error while compiling dependencies.

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (461e80780 2022-03-16)
binary: rustc
commit-hash: 461e8078010433ff7de2db2aaae8a3cfb0847215
commit-date: 2022-03-16
host: x86_64-apple-darwin
release: 1.61.0-nightly
LLVM version: 14.0.0

```

### Error output

```
   Compiling rocket_sync_db_pools v0.1.0-rc.1
thread 'rustc' panicked at 'assertion failed: !value.has_escaping_bound_vars()', /rustc/461e8078010433ff7de2db2aaae8a3cfb0847215/compiler/rustc_middle/src/ty/sty.rs:1089:9
stack backtrace:
   0:        0x1032f1fd4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf25e29788b77fb75
   1:        0x10334a66b - core::fmt::write::he0e4175a8acd2962
   2:        0x1032e4868 - std::io::Write::write_fmt::hb96bdfcc78ec7cec
   3:        0x1032f550d - std::panicking::default_hook::{{closure}}::hf3de0634dd6d2776
   4:        0x1032f51f1 - std::panicking::default_hook::h1acf3d7c28476d04
   5:        0x10c2a491a - rustc_driver[7d023222227bce03]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x1032f5c76 - std::panicking::rust_panic_with_hook::ha1ab7703f0656569
   7:        0x1032f5a7a - std::panicking::begin_panic_handler::{{closure}}::h47e0d0611cfa376d
   8:        0x1032f2457 - std::sys_common::backtrace::__rust_end_short_backtrace::h5158597020bda63a
   9:        0x1032f578a - _rust_begin_unwind
  10:        0x103373c53 - core::panicking::panic_fmt::h1067927c00c63e24
  11:        0x103373b37 - core::panicking::panic::he691de0318d78d5a
  12:        0x1104d8c1c - rustc_trait_selection[d0a2ae1080541e01]::traits::type_known_to_meet_bound_modulo_regions
  13:        0x10f069f59 - <rustc_infer[8e9fa3be2a1de28e]::infer::InferCtxtBuilder>::enter::<bool, rustc_ty_utils[cd8f02697b2ef00e]::common_traits::is_item_raw::{closure#0}>
  14:        0x10f0705bd - rustc_ty_utils[cd8f02697b2ef00e]::common_traits::is_item_raw
  15:        0x10f92b775 - rustc_query_system[69e431e24e8ae68]::query::plumbing::try_execute_query::<rustc_query_impl[1a64f2fe0929fb6b]::plumbing::QueryCtxt, rustc_query_system[69e431e24e8ae68]::query::caches::DefaultCache<rustc_middle[d0c5a6fd4c052f63]::ty::ParamEnvAnd<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>, bool>>
  16:        0x10fa131f4 - rustc_query_system[69e431e24e8ae68]::query::plumbing::get_query::<rustc_query_impl[1a64f2fe0929fb6b]::queries::is_sized_raw, rustc_query_impl[1a64f2fe0929fb6b]::plumbing::QueryCtxt>
  17:        0x1107e4806 - <rustc_middle[d0c5a6fd4c052f63]::ty::Ty>::is_sized
  18:        0x1107205ff - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached
  19:        0x110739a76 - rustc_middle[d0c5a6fd4c052f63]::ty::layout::layout_of
  20:        0x10fa46d28 - rustc_query_system[69e431e24e8ae68]::query::plumbing::get_query::<rustc_query_impl[1a64f2fe0929fb6b]::queries::layout_of, rustc_query_impl[1a64f2fe0929fb6b]::plumbing::QueryCtxt>
  21:        0x10fc90970 - <rustc_query_impl[1a64f2fe0929fb6b]::Queries as rustc_middle[d0c5a6fd4c052f63]::ty::query::QueryEngine>::layout_of
  22:        0x110768f74 - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt> as rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutOf>::layout_of
  23:        0x110759809 - <alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>> as alloc[103bd0370a37e0a1]::vec::spec_from_iter::SpecFromIter<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>, core[3b2bc5e37d261935]::iter::adapters::GenericShunt<core[3b2bc5e37d261935]::iter::adapters::map::Map<core[3b2bc5e37d261935]::slice::iter::Iter<rustc_middle[d0c5a6fd4c052f63]::ty::FieldDef>, <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached::{closure#5}::{closure#0}>, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::convert::Infallible, rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutError>>>>::from_iter
  24:        0x110758b3c - <alloc[103bd0370a37e0a1]::vec::Vec<alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>>> as alloc[103bd0370a37e0a1]::vec::spec_from_iter::SpecFromIter<alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>>, core[3b2bc5e37d261935]::iter::adapters::GenericShunt<core[3b2bc5e37d261935]::iter::adapters::map::Map<core[3b2bc5e37d261935]::slice::iter::Iter<rustc_middle[d0c5a6fd4c052f63]::ty::VariantDef>, <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached::{closure#5}>, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::convert::Infallible, rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutError>>>>::from_iter
  25:        0x11071f8f2 - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached
  26:        0x110739a76 - rustc_middle[d0c5a6fd4c052f63]::ty::layout::layout_of
  27:        0x10fa46d28 - rustc_query_system[69e431e24e8ae68]::query::plumbing::get_query::<rustc_query_impl[1a64f2fe0929fb6b]::queries::layout_of, rustc_query_impl[1a64f2fe0929fb6b]::plumbing::QueryCtxt>
  28:        0x10fc90970 - <rustc_query_impl[1a64f2fe0929fb6b]::Queries as rustc_middle[d0c5a6fd4c052f63]::ty::query::QueryEngine>::layout_of
  29:        0x110768f74 - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt> as rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutOf>::layout_of
  30:        0x110759809 - <alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>> as alloc[103bd0370a37e0a1]::vec::spec_from_iter::SpecFromIter<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>, core[3b2bc5e37d261935]::iter::adapters::GenericShunt<core[3b2bc5e37d261935]::iter::adapters::map::Map<core[3b2bc5e37d261935]::slice::iter::Iter<rustc_middle[d0c5a6fd4c052f63]::ty::FieldDef>, <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached::{closure#5}::{closure#0}>, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::convert::Infallible, rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutError>>>>::from_iter
  31:        0x110758b3c - <alloc[103bd0370a37e0a1]::vec::Vec<alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>>> as alloc[103bd0370a37e0a1]::vec::spec_from_iter::SpecFromIter<alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>>, core[3b2bc5e37d261935]::iter::adapters::GenericShunt<core[3b2bc5e37d261935]::iter::adapters::map::Map<core[3b2bc5e37d261935]::slice::iter::Iter<rustc_middle[d0c5a6fd4c052f63]::ty::VariantDef>, <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached::{closure#5}>, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::convert::Infallible, rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutError>>>>::from_iter
  32:        0x11071f8f2 - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached
  33:        0x110739a76 - rustc_middle[d0c5a6fd4c052f63]::ty::layout::layout_of
  34:        0x10fa46d28 - rustc_query_system[69e431e24e8ae68]::query::plumbing::get_query::<rustc_query_impl[1a64f2fe0929fb6b]::queries::layout_of, rustc_query_impl[1a64f2fe0929fb6b]::plumbing::QueryCtxt>
  35:        0x10fc90970 - <rustc_query_impl[1a64f2fe0929fb6b]::Queries as rustc_middle[d0c5a6fd4c052f63]::ty::query::QueryEngine>::layout_of
  36:        0x110768f74 - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt> as rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutOf>::layout_of
  37:        0x110759809 - <alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>> as alloc[103bd0370a37e0a1]::vec::spec_from_iter::SpecFromIter<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>, core[3b2bc5e37d261935]::iter::adapters::GenericShunt<core[3b2bc5e37d261935]::iter::adapters::map::Map<core[3b2bc5e37d261935]::slice::iter::Iter<rustc_middle[d0c5a6fd4c052f63]::ty::FieldDef>, <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached::{closure#5}::{closure#0}>, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::convert::Infallible, rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutError>>>>::from_iter
  38:        0x110758b3c - <alloc[103bd0370a37e0a1]::vec::Vec<alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>>> as alloc[103bd0370a37e0a1]::vec::spec_from_iter::SpecFromIter<alloc[103bd0370a37e0a1]::vec::Vec<rustc_target[27055f96b1306b35]::abi::TyAndLayout<rustc_middle[d0c5a6fd4c052f63]::ty::Ty>>, core[3b2bc5e37d261935]::iter::adapters::GenericShunt<core[3b2bc5e37d261935]::iter::adapters::map::Map<core[3b2bc5e37d261935]::slice::iter::Iter<rustc_middle[d0c5a6fd4c052f63]::ty::VariantDef>, <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached::{closure#5}>, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::convert::Infallible, rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutError>>>>::from_iter
  39:        0x11071f8f2 - <rustc_middle[d0c5a6fd4c052f63]::ty::layout::LayoutCx<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt>>::layout_of_uncached
  40:        0x110739a76 - rustc_middle[d0c5a6fd4c052f63]::ty::layout::layout_of
  41:        0x10fa46d28 - rustc_query_system[69e431e24e8ae68]::query::plumbing::get_query::<rustc_query_impl[1a64f2fe0929fb6b]::queries::layout_of, rustc_query_impl[1a64f2fe0929fb6b]::plumbing::QueryCtxt>
  42:        0x10fc90970 - <rustc_query_impl[1a64f2fe0929fb6b]::Queries as rustc_middle[d0c5a6fd4c052f63]::ty::query::QueryEngine>::layout_of
  43:        0x10fcf3330 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_debuginfo_type_name
  44:        0x10fcf51d9 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_debuginfo_type_name
  45:        0x10fcf8409 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_generic_params_internal
  46:        0x10fcf39b3 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_debuginfo_type_name
  47:        0x10fcf8409 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_generic_params_internal
  48:        0x10fcf39b3 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_debuginfo_type_name
  49:        0x10fcf8409 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_generic_params_internal
  50:        0x10fcf39b3 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_debuginfo_type_name
  51:        0x10fcf8409 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_generic_params_internal
  52:        0x10fcf39b3 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::push_debuginfo_type_name
  53:        0x10fcf24d7 - rustc_codegen_ssa[e58cb751afe2ce82]::debuginfo::type_names::compute_debuginfo_type_name
  54:        0x10c4ac15a - rustc_codegen_llvm[a1c0ad7a65e28a12]::debuginfo::metadata::enums::native::build_enum_type_di_node
  55:        0x10c5197b1 - rustc_codegen_llvm[a1c0ad7a65e28a12]::debuginfo::metadata::enums::build_enum_type_di_node
  56:        0x10c540a98 - rustc_codegen_llvm[a1c0ad7a65e28a12]::debuginfo::metadata::type_di_node
  57:        0x10c4f9d5e - <rustc_codegen_llvm[a1c0ad7a65e28a12]::context::CodegenCx as rustc_codegen_ssa[e58cb751afe2ce82]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn::get_function_signature
  58:        0x10c4de370 - <rustc_codegen_llvm[a1c0ad7a65e28a12]::context::CodegenCx as rustc_codegen_ssa[e58cb751afe2ce82]::traits::debuginfo::DebugInfoMethods>::dbg_scope_fn
  59:        0x10c4ddf78 - <rustc_codegen_llvm[a1c0ad7a65e28a12]::context::CodegenCx as rustc_codegen_ssa[e58cb751afe2ce82]::traits::debuginfo::DebugInfoMethods>::create_function_debug_context
  60:        0x10c549515 - rustc_codegen_ssa[e58cb751afe2ce82]::mir::codegen_mir::<rustc_codegen_llvm[a1c0ad7a65e28a12]::builder::Builder>
  61:        0x10c4355a9 - rustc_codegen_ssa[e58cb751afe2ce82]::base::codegen_instance::<rustc_codegen_llvm[a1c0ad7a65e28a12]::builder::Builder>
  62:        0x10c51ecaa - <rustc_middle[d0c5a6fd4c052f63]::mir::mono::MonoItem as rustc_codegen_ssa[e58cb751afe2ce82]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[a1c0ad7a65e28a12]::builder::Builder>
  63:        0x10c47cb57 - rustc_codegen_llvm[a1c0ad7a65e28a12]::base::compile_codegen_unit::module_codegen
  64:        0x10c4ba3ab - <rustc_query_system[69e431e24e8ae68]::dep_graph::graph::DepGraph<rustc_middle[d0c5a6fd4c052f63]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[d0c5a6fd4c052f63]::ty::context::TyCtxt, rustc_span[e6705d92d35d0465]::symbol::Symbol, rustc_codegen_ssa[e58cb751afe2ce82]::ModuleCodegen<rustc_codegen_llvm[a1c0ad7a65e28a12]::ModuleLlvm>>
  65:        0x10c47c416 - rustc_codegen_llvm[a1c0ad7a65e28a12]::base::compile_codegen_unit
  66:        0x10c45204f - <rustc_codegen_llvm[a1c0ad7a65e28a12]::LlvmCodegenBackend as rustc_codegen_ssa[e58cb751afe2ce82]::traits::backend::CodegenBackend>::codegen_crate
  67:        0x10c3fd272 - <rustc_session[80b02cea19563f86]::session::Session>::time::<alloc[103bd0370a37e0a1]::boxed::Box<dyn core[3b2bc5e37d261935]::any::Any>, rustc_interface[41a97a05c49db199]::passes::start_codegen::{closure#0}>
  68:        0x10c3b30db - <rustc_interface[41a97a05c49db199]::passes::QueryContext>::enter::<<rustc_interface[41a97a05c49db199]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[3b2bc5e37d261935]::result::Result<alloc[103bd0370a37e0a1]::boxed::Box<dyn core[3b2bc5e37d261935]::any::Any>, rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>
  69:        0x10c396fc9 - <rustc_interface[41a97a05c49db199]::queries::Queries>::ongoing_codegen
  70:        0x10c2352da - <rustc_interface[41a97a05c49db199]::interface::Compiler>::enter::<rustc_driver[7d023222227bce03]::run_compiler::{closure#1}::{closure#2}, core[3b2bc5e37d261935]::result::Result<core[3b2bc5e37d261935]::option::Option<rustc_interface[41a97a05c49db199]::queries::Linker>, rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>
  71:        0x10c257678 - rustc_span[e6705d92d35d0465]::with_source_map::<core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>, rustc_interface[41a97a05c49db199]::interface::create_compiler_and_run<core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>, rustc_driver[7d023222227bce03]::run_compiler::{closure#1}>::{closure#1}>
  72:        0x10c25563a - rustc_interface[41a97a05c49db199]::interface::create_compiler_and_run::<core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>, rustc_driver[7d023222227bce03]::run_compiler::{closure#1}>
  73:        0x10c22d8a5 - <scoped_tls[49a3ef24a8256ae4]::ScopedKey<rustc_span[e6705d92d35d0465]::SessionGlobals>>::set::<rustc_interface[41a97a05c49db199]::interface::run_compiler<core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>, rustc_driver[7d023222227bce03]::run_compiler::{closure#1}>::{closure#0}, core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>
  74:        0x10c229d29 - std[664e80904774930a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[41a97a05c49db199]::util::run_in_thread_pool_with_globals<rustc_interface[41a97a05c49db199]::interface::run_compiler<core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>, rustc_driver[7d023222227bce03]::run_compiler::{closure#1}>::{closure#0}, core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>::{closure#0}, core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>
  75:        0x10c25e752 - <<std[664e80904774930a]::thread::Builder>::spawn_unchecked_<rustc_interface[41a97a05c49db199]::util::run_in_thread_pool_with_globals<rustc_interface[41a97a05c49db199]::interface::run_compiler<core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>, rustc_driver[7d023222227bce03]::run_compiler::{closure#1}>::{closure#0}, core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>::{closure#0}, core[3b2bc5e37d261935]::result::Result<(), rustc_errors[21f4edb4558993d1]::ErrorGuaranteed>>::{closure#1} as core[3b2bc5e37d261935]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  76:        0x1032ff3e7 - std::sys::unix::thread::Thread::new::thread_start::h600547cf791897dd
  77:     0x7ff80ded84f4 - __pthread_start
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.61.0-nightly (461e80780 2022-03-16) running on x86_64-apple-darwin
note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [is_sized_raw] computing whether `dyn core::future::future::Future<Output = ()> + core::marker::Send` is `Sized`
#1 [layout_of] computing layout of `*const dyn core::future::future::Future<Output = ()> + core::marker::Send`
#2 [layout_of] computing layout of `core::ptr::unique::Unique<dyn core::future::future::Future<Output = ()> + core::marker::Send>`
#3 [layout_of] computing layout of `alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>`
#4 [layout_of] computing layout of `core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>>`
end of query stack
```

**Comment by aliemjay** [comment] 2022-03-17 20:35
probably a duplicate of #94998

**Comment by istankovic** [comment] 2023-10-22 13:59
@maccesch could you please check whether this is still relevant? Alternatively, could you provide a list of dependencies we could use to reproduce?

**Comment by maccesch** [comment] 2023-10-22 14:05
That project doesn't exist anymore. I guess you can safely close this issue.

**Closed** 2023-10-22 14:05 UTC
Labels: I-ICE, T-compiler, C-bug
