### ISSUE TITLE
Random compilation error with proc-macro

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#47332] opened 2018-01-10 18:40 UTC
Hi!
I randomly get the following compilation error when developing a proc-macro:
```
error: /path/to/rust/project/target/debug/deps/libmy_proc_macro_crate-bed23c204003db91.so: undefined symbol: __rustc_derive_registrar__b0028b8f317d7b045e78ce5c492cc011_18
 --> src/main.rs:3:1
  |
3 | extern crate my_proc_macro_crate;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Running `cargo clean` fix (temporarily) the issue.
Thanks to fix this issue.

**Comment by sfackler** [comment] 2018-01-10 19:10
Duplicate of #47292

**Closed by sfackler** 2018-01-10 19:10 UTC
