### ISSUE TITLE
Invalid trait resolution with HRTBs and blanket impls over closures

### ISSUE THREAD

**Issue by theInkSquid** [rust-lang/rust#77949] opened 2020-10-14 19:53 UTC
I tried this code:

```rust
trait Handler<'a> {
    type Output: 'a;
    fn call(&self, param: &'a i32) -> Self::Output;
}

impl<'a, F, T> Handler<'a> for F
where
    F: Fn(&'a i32) -> T,
    T: 'a,
{
    type Output = T;
    fn call(&self, param: &'a i32) -> T {
        self(param)
    }
}

fn call_handler(handler: impl for<'a> Handler<'a>) {
    let value: i32 = 10;
    let _ret = handler.call(&value);
}

fn main() {
    call_handler(|x: &'_ i32| x);
}
```

I expected to see this compile, since `|x: &'_ i32| x` should implement `for<'a> Fn(&'a i32) -> &'a i32`, and therefore implement `for<'a> Handler<'a>`.

Instead, it gives me this error: 
```
error: implementation of `Handler` is not general enough
  --> src/main.rs:28:5
   |
1  | / trait Handler<'a> {
2  | |     type Output: 'a;
3  | |     fn call(&self, param: &'a i32) -> Self::Output;
4  | | }
   | |_- trait `Handler` defined here
...
28 |       call_handler(|x: &'_ i32| x);
   |       ^^^^^^^^^^^^ implementation of `Handler` is not general enough
   |
   = note: `Handler<'1>` would have to be implemented for the type `[closure@src/main.rs:28:18: 28:32]`, for any lifetime `'1`...
   = note: ...but `Handler<'_>` is actually implemented for the type `[closure@src/main.rs:28:18: 28:32]`, for some specific lifetime `'2`
```

It does not make sense for the closure to only implement `Handler<'a>` for a specific lifetime `'a`. Further, if I write an equivalent function definition like this:
```rust
fn identity(x: &i32) -> &i32 {
    x
}

fn main() {
    call_handler(identity);
}
```
It compiles with no issue. 

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
Compiler returned: 0
```
The issue presents itself on nightly and beta as well.

**Comment by theInkSquid** [comment] 2020-10-14 20:28
The error message is different on rustc 1.32 and below. Nothing in the change log of 1.33 mentions anything that would cause a difference in error messages here.
```
error[E0271]: type mismatch resolving `for<'a> <[closure@<source>:28:18: 28:23] as std::ops::FnOnce<(&'a i32,)>>::Output == _`
  --> <source>:28:5
   |
28 |     call_handler(|x| x);
   |     ^^^^^^^^^^^^ expected bound lifetime parameter 'a, found concrete lifetime
   |
   = note: required because of the requirements on the impl of `for<'a> Handler<'a>` for `[closure@<source>:28:18: 28:23]`
note: required by `call_handler`
  --> <source>:17:1
   |
17 | fn call_handler(handler: impl for<'a> Handler<'a>) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0631]: type mismatch in closure arguments
  --> <source>:28:5
   |
28 |     call_handler(|x| x);
   |     ^^^^^^^^^^^^ ----- found signature of `fn(_) -> _`
   |     |
   |     expected signature of `for<'a> fn(&'a i32) -> _`
   |
   = note: required because of the requirements on the impl of `for<'a> Handler<'a>` for `[closure@<source>:28:18: 28:23]`
note: required by `call_handler`
  --> <source>:17:1
   |
17 | fn call_handler(handler: impl for<'a> Handler<'a>) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

**Comment by jyn514** [comment] 2020-10-15 03:00
This fixes it:
```rust
fn main() {
    fn f(x: &i32) { x; }
    call_handler(f);
}
```
and that means this is a duplicate of https://github.com/rust-lang/rust/issues/41078.

**Closed by jyn514** 2020-10-15 03:00 UTC
Labels: A-closures, A-diagnostics, A-lifetimes, A-traits, C-bug, I-prioritize, T-compiler

**Comment by camelid** [comment] 2020-10-15 03:04
I think you might have meant [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bf626736855eb29c83057f5b3f1990fd), but same idea:

```rust
fn main() {
    fn f(x: &i32) -> &i32 { x }
    call_handler(f);
}
```
