### ISSUE TITLE
 cargo bench   (signal: 11, SIGSEGV: invalid memory reference) 

### ISSUE THREAD

**Issue by Amdahl-rs** [rust-lang/rust#100939] opened 2022-08-24 02:02 UTC
I found that the compiler is getting more and more unstable.
The same code, in the following environment, although the compilation is slow, it can be successfully completed.

> rustc 1.62.0-nightly (f4a7ce997 2022-04-08)
> binary: rustc
> commit-hash: f4a7ce997a1d7546d2b737f8b87d36907bcea2ad
> commit-date: 2022-04-08
> host: x86_64-unknown-linux-gnu
> release: 1.62.0-nightly
> LLVM version: 14.0.0

However, under the new version, it can be cargo build --release , and the bench will report an error 

### Meta

`rustc --version --verbose`:
```
<version>
 rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-unknown-linux-gnu
release: 1.63.0
LLVM version: 14.0.5


### Error output

```
<output>
Caused by:
process didn't exit successfully: 
`rustc --crate-name query --edition=2021 query/src/lib.rs 
--error-format=json 
--json=diagnostic-rendered-ansi,artifacts,future-incompat 
--crate-type lib 
--emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 
--cfg 'feature="default"' 
--cfg 'feature="simd"' -C metadata=0f95fb33c3fd6325 -C extra-filename=-0f95fb33c3fd6325 
--out-dir /data/target/release/deps -L dependency=/data/target/release/deps 
--extern abomonation=/data/target/release/deps/libabomonation-c886bdf641ee1364.rmeta 
--extern abomonation_derive=/data/target/release/deps/libabomonation_derive-f38023a7e607e0e8.so 
--extern ahash=/data/target/release/deps/libahash-7a833d9d142be42a.rmeta -
-extern async_compat=/data/target/release/deps/libasync_compat-35058922e68a5fac.rmeta 
--extern async_recursion=/data/target/release/deps/libasync_recursion-03270c0398205993.so 
--extern async_stream=/data/target/release/deps/libasync_stream-46a6ec585bdb31ed.rmeta 
--extern async_trait=/data/target/release/deps/libasync_trait-d07e47214e70d33d.so 
--extern base_arrow=/data/target/release/deps/libbase_arrow-e277bb3369962af3.rmeta 
--extern base_datablocks2=/data/target/release/deps/libbase_datablocks2-c5ed95da6995f04d.rmeta 
--extern base_datavalue2=/data/target/release/deps/libbase_datavalue2-32c8fe38bbc19c13.rmeta 
--extern base_expr=/data/target/release/deps/libbase_expr-4f2d5dd5e19077b9.rmeta 
--extern bumpalo=/data/target/release/deps/libbumpalo-8039f2c1774db0c3.rmeta 
--extern byteorder=/data/target/release/deps/libbyteorder-9748a3ef57939560.rmeta 
--extern bytes=/data/target/release/deps/libbytes-0e5f9670de747b17.rmeta 
--extern cargo_license=/data/target/release/deps/libcargo_license-9170722660f96500.rmeta
--extern poem=/data/target/release/deps/libpoem-9c0780cb14447598.rmeta 
--extern storage_cell=/data/target/release/deps/libstorage_cell-2b0f99db1df864c8.rmeta 
--extern threadpool=/data/target/release/deps/libthreadpool-b4bdebb45dc5a5c2.rmeta 
--extern tokio_rustls=/data/target/release/deps/libtokio_rustls-39354448fabb5cb9.rmeta 
--extern tokio_stream=/data/target/release/deps/libtokio_stream-140171ba8db6c61f.rmeta 
--extern toml=/data/target/release/deps/libtoml-bb3dc8f1296f8b5e.rmeta 
--extern tonic=/data/target/release/deps/libtonic-99a7281a46e9427f.rmeta 
--extern uuid=/data/target/release/deps/libuuid-4c6a38e3e4ea66a1.rmeta 
--extern walkdir=/data/target/release/deps/libwalkdir-1a9d71a08e756818.rmeta 
--extern zstd_safe=/data/target/release/deps/libzstd_safe-b9e39aff6b90ef05.rmeta -L native=/data/target/release/build/libz-sys-13b912ea23cd04ce/out/lib -L native=/data/target/release/build/libz-sys-13b912ea23cd04ce/out/lib -L native=/data/target/release/build/lz4-sys-3b1b1ac7793bf689/out -L native=/data/target/release/build/zstd-sys-2ee7c676c8437554/out -L native=/data/target/release/build/ring-542ddb1198f07e42/out -L native=/data/target/release/build/tikv-jemalloc-sys-6ba3e19a4d0ea896/out/build/lib -L native=/data/target/release/build/rust-crypto-323cc68b592ba209/out` (signal: 11, SIGSEGV: invalid memory reference)

  

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by saethlin** [comment] 2022-08-24 02:57
Is there a way that anyone else can reproduce this? Without a reproducer it seems unlikely anyone can even confirm that this is a bug in the compiler as opposed to your system.

**Comment by Amdahl-rs** [comment] 2022-08-24 03:07
@saethlin  see #4793

**Comment by saethlin** [comment] 2022-08-24 03:32
So are you saying this issue can be closed as a duplicate of that issue? I still don't know what code you compiled here.

**Comment by Amdahl-rs** [comment] 2022-08-24 05:49
Right, you still don't know what code you compiled here. Because the compiler's error message cannot be located at all. As a programmer, don't you understand this? Your reply is like a fly humming, useless @saethlin

**Comment by WilliamVenner** [comment] 2022-08-24 07:30
How is one supposed to know if a bug has been fixed, if they can't reproduce it in the first place? How is a programmer supposed to understand a bug and fix it without being able to reproduce it in a codebase as complex as rustc?

**Comment by eaglgenes101** [comment] 2022-08-24 15:19
More to the point, _what_ code, when `cargo bench`ed, causes the error?

**Closed** 2022-08-25 01:06 UTC
Labels: I-ICE, T-compiler, C-bug

**Comment by Amdahl-rs** [comment] 2022-08-25 01:14
There are already many  about such issues, the attitude of the community, let me choose to close it
