### ISSUE TITLE
prettyprinter reorders comments to show before doc comments

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#6678] opened 2013-05-22 12:43 UTC
```
$ echo '/** foo */ /* bar */ fn f() {}' | rustc - --pretty
/* bar */
/** foo */
fn f() { }
```

I'm not sure this is supposed to happen, but maybe it's prettier this way...

**Comment by steveklabnik** [comment] 2015-01-21 18:40
Triage: still here.

**Comment by mrhota** [comment] 2016-04-27 22:38
Triage: still here in nightly (using rustup)

**Comment by steveklabnik** [comment] 2018-09-24 16:41
Triage: no change in behavior, though the flags have changed:

```
> rustc +nightly -Z unstable-options --pretty=normal .\foo.rs
/* bar */
/** foo */
fn f() { }
```

**Comment by workingjubilee** [comment] 2023-03-15 23:48
Closing this on the hypothesis of "if this was unintended behavior, someone would have fixed it within the past 10 years". Seems harmless, but maybe I'm wrong? :woman_shrugging:

**Closed by workingjubilee** 2023-03-15 23:48 UTC
Labels: A-pretty, C-enhancement

**Comment by varkor** [comment] 2023-03-17 04:41
@workingjubilee: seems less likely this is intended behaviour and more likely this is just low priority compared to other issues.
