### ISSUE TITLE
printing non-existent same name variable as struct field with `format_args_implicits` feature suggests incorrect `self.field_name`

### ISSUE THREAD

**Issue by MolotovCherry** [rust-lang/rust#123232] opened 2024-03-30 13:34 UTC
### Code

```Rust
struct Foo {
    bar: String
}

impl Foo {
    fn dest(&self) {
        println!("{bar}");
    }
}
```

### Current output

```Shell
error[E0425]: cannot find value `bar` in this scope
 --> src/main.rs:8:20
  |
8 |         println!("{bar}");
  |                    ^^^
  |
help: you might have meant to use the available field
  |
8 |         println!("{self.bar}");
  |                    +++++

For more information about this error, try `rustc --explain E0425`.
```

### Desired output

```Shell
error[E0425]: cannot find value `bar` in this scope
 --> src/main.rs:8:20
  |
8 |         println!("{bar}");
  |                    ^^^
  |
help: you might have meant to use the available field
  |
7 |         println!("{}", self.bar);
  |                      ++++++++++

For more information about this error, try `rustc --explain E0425`.
```
(Something like that, my formatting is probably off, but it should get the idea across)

### Rust Version

```Shell
1.77.1
```

**Comment by lukas-code** [comment] 2024-03-30 14:10
Duplicate of https://github.com/rust-lang/rust/issues/105520

**Comment by fmease** [comment] 2024-03-30 14:17
Ah thanks, I *knew* this was a duplicate but I couldn't find the original issue.

**Closed by fmease** 2024-03-30 14:17 UTC
Labels: A-diagnostics, A-resolve, A-macros, T-compiler, A-suggestion-diagnostics, D-invalid-suggestion, A-fmt
