### ISSUE TITLE
rust should complete stage2 build and install both stage2 libs and binaries

### ISSUE THREAD

**Issue by howarthjw** [rust-lang/rust#25546] opened 2015-05-17 18:31 UTC
On darwin, the rust 1.0.0 build completes in stage2 and install the libs built in stage2 in the rustlib subdirectory during 'make install' but also installs the binaries and libs built in stage1. The proposed debian packaging for rust at https://ftp-master.debian.org/new/rustc_1.0.0%7Ebeta.4-1%7Eexp1.html replaces the libs installed in rustlib with symlinks to the libs installed in the top-level libs subdirectory. Perhaps the build should be modified to rebuild the rust executables using the same libs installed in rustlib so that only a single set of libs are installed (which are built from the last stage of the bootstrap process).

**Comment by alexcrichton** [comment] 2015-05-17 20:36
Thanks for the report! This is similar enough to #11145 that I'm going to close this as a dupe of that.

**Closed by alexcrichton** 2015-05-17 20:36 UTC
