### ISSUE TITLE
"Foo is ambiguous" even though it's not

### ISSUE THREAD

**Issue by oberien** [rust-lang/rust#62768] opened 2019-07-17 21:45 UTC
[playpen](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=75fda319e5fcd1be7259ee46c608a710)

Given the following code:
```rust
mod foo {
    pub enum Foo {
        Foo(i32),
    }
}
use foo::*;
use Foo::*;
```
The compiler claims, that the `Foo` in `use Foo::*` could either mean the type `foo::Foo` imported by `use foo::*`, or the variant (value) `Foo::Foo` imported by `use Foo::*`:
```rust
error[E0659]: `Foo` is ambiguous (glob import vs glob import in the same module)
 --> src/lib.rs:7:5
  |
7 | use Foo::*;
  |     ^^^ ambiguous name
  |
note: `Foo` could refer to the enum imported here
 --> src/lib.rs:6:5
  |
6 | use foo::*;
  |     ^^^^^^
  = help: consider adding an explicit import of `Foo` to disambiguate
note: `Foo` could also refer to the variant imported here
 --> src/lib.rs:7:5
  |
7 | use Foo::*;
  |     ^^^^^^
  = help: consider adding an explicit import of `Foo` to disambiguate
```

How can a name refer to something that's not imported yet?

**Comment by petrochenkov** [comment] 2019-07-26 14:29
This is more or less a duplicate of https://github.com/rust-lang/rust/issues/62769, the root cause (https://github.com/rust-lang/rust/issues/62769#issuecomment-512619439) is the same.

**Comment by Mark-Simulacrum** [comment] 2019-08-05 12:56
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/62769 since the root causes and specific issues are so similar.

**Closed by Mark-Simulacrum** 2019-08-05 12:56 UTC
Labels: A-resolve, C-bug, T-compiler
