### ISSUE TITLE
Regression in crate ipfs-api on 1.30 beta

### ISSUE THREAD

**Issue by leodasvacas** [rust-lang/rust#54386] opened 2018-09-20 13:17 UTC
The crate [ipfs-api](https://crates.io/crates/ipfs-api) on version 0.5.0-alpha2 builds fine on stable. On beta and nightly fails with 84 name resolution errors. There are multiple instances of this error:
```
error: cannot determine resolution for the attribute macro `serde`
  --> ipfs-api/src/response/pin.rs:22:3
   |
22 | #[serde(rename_all = "PascalCase")]
   |   ^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports
```

Ping @petrochenkov who is an expert here.
Ping crate author @ferristseng.

**Comment by pnkfelix** [comment] 2018-09-20 14:40
visiting for triage. P-high.

**Comment by nikomatsakis** [comment] 2018-09-20 14:42
It would be great to bisect this with https://github.com/rust-lang-nursery/cargo-bisect-rustc

**Comment by pnkfelix** [comment] 2018-09-20 14:42
Assigning @petrochenkov  (but they should feel free to unassign themselves if they are unable to commit time to this.)

**Comment by eddyb** [comment] 2018-09-20 14:42
It might be caused by the [explicit import of something named `serde`](https://github.com/ferristseng/rust-ipfs-api/blob/c37a49f137637c1041186143788460e5ddf28822/ipfs-api/src/response/pin.rs#L9-L13):
```rust
use response::serde;
// ...
#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PinAddResponse {
```

**Comment by pietroalbini** [comment] 2018-09-22 13:46
Crater found more regressions similar to this.

```
 error: cannot determine resolution for the attribute macro `serde`
   --> src/response/bitswap.rs:12:3
    |
 12 | #[serde(rename_all = "PascalCase")]
    |   ^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports
```
```
 error: cannot determine resolution for the macro `json`
    --> src/models/data.rs:179:19
     |
 179 |         let obj = json!({
     |                   ^^^^
     |
     = note: import resolution is stuck, try simplifying macro imports
```

* Dependencies of `ipfs-api`:
  * [world_id](https://crates.io/crates/world_id) `0.1.0` (depends on `ipfs-api`) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/world_id-0.1.0/log.txt)) cc @icefoxen
* [libyobicash](https://crates.io/crates/libyobicash) `0.3.2` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/libyobicash-0.3.2/log.txt)) cc @chritchens
* [devnought/gitplz](https://github.com/devnought/gitplz) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/devnought.gitplz/log.txt)) cc @devnought

cc @petrochenkov

**Comment by devnought** [comment] 2018-09-22 14:49
> * [devnought/gitplz](https://github.com/devnought/gitplz) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/devnought.gitplz/log.txt)) cc @devnought

I was surprised to wake up to this today as I thought crater only ran against crates published on crates.io, which gitplz isn't.

In any case, I have a `rust-2018` branch that uses the edition and compiles on the latest nightly.

**Comment by pietroalbini** [comment] 2018-09-22 15:03
> I was surprised to wake up to this today as I thought crater only ran against crates published on crates.io, which gitplz isn't.

We also test repositories on GitHub `:D`

**Comment by petrochenkov** [comment] 2018-09-23 21:01
Minimized in https://github.com/rust-lang/rust/issues/54471#issuecomment-423847575

**Comment by petrochenkov** [comment] 2018-09-23 21:02
Closing as duplicate of https://github.com/rust-lang/rust/issues/54471

**Closed by petrochenkov** 2018-09-23 21:02 UTC
Labels: A-attributes, A-macros, A-resolve, E-needs-bisection, P-high, T-compiler, regression-from-stable-to-beta
