### ISSUE TITLE
Blanket impls constrained by different associated types falsely flagged as conflicting

### ISSUE THREAD

**Issue by boringcactus** [rust-lang/rust#86605] opened 2021-06-24 19:59 UTC
I tried this code (aggressively simplified from Diesel, with which I originally encountered this bug):

```rust
trait Backend {
    type RawValue;
}

trait FromSql<B: Backend> {}

impl<B: Backend<RawValue=()>> FromSql<B> for String {}
impl<B: Backend<RawValue=u8>> FromSql<B> for String {}
```

I expected to see this happen: this code compiles, because by definition nothing can implement both `Backend<RawValue=()>` and `Backend<RawValue=u8>`.

Instead, this happened: rustc gives `error[E0119]: conflicting implementations of trait 'FromSql<_>' for type 'std::string::String'`

### Meta

This happens across stable/beta/nightly on the Rust playground.

**Comment by jonas-schievink** [comment] 2021-06-24 20:19
Looks like a duplicate of https://github.com/rust-lang/rust/issues/20400

**Closed by jonas-schievink** 2021-06-24 20:19 UTC
Labels: C-bug
