### ISSUE TITLE
Internal compiler error on docs.rs after publishing the Windows crate

### ISSUE THREAD

**Issue by kennykerr** [rust-lang/rust#82988] opened 2021-03-10 21:31 UTC
I just noticed this error on docs.rs:

https://docs.rs/crate/windows/0.4.0/builds/360477

**Comment by jyn514** [comment] 2021-03-10 22:51
Duplicate of https://github.com/rust-lang/rust/issues/82991.

**Closed by jyn514** 2021-03-10 22:51 UTC
Labels: C-bug, I-ICE, T-compiler
