### ISSUE TITLE
ReSkolemized can leak into error messages

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#26404] opened 2015-06-18 17:21 UTC
## STR

```Rust
fn foo(f: for<'a,'b> fn(&'a ()) -> &'a &'b ()) {
    bar(f);
}

fn bar(f: for<'a,'b> fn(&'b ()) -> &'a &'b ()) {
}

fn main() {}
```

## Actual Results
```
<anon>:2:9: 2:10 error: mismatched types:
 expected `fn(&'b ()) -> &'a &'b ()`,
    found `fn(&'a ()) -> &'a &'b ()`
(expected concrete lifetime,
    found bound lifetime parameter 'a) [E0308]
<anon>:2     bar(f);
                 ^
<anon>:2:9: 2:10 help: see the detailed explanation for E0308
note: expected concrete lifetime is lifetime ReInfer(ReSkolemized(0, BrNamed(DefId { krate: 0, node: 31 }, "\'b"(64))))
error: aborting due to previous error
playpen: application terminated with error code 101
```

## Expected Results

No leak of rustc internals into error messages.

**Comment by Stebalien** [comment] 2015-06-19 02:16
Lines 172-174 of `src/librustc/util/ppaux.rs`. /cc @nikomatsakis

**Comment by jroesch** [comment] 2015-06-19 07:20
cc me

**Comment by jakub-** [comment] 2015-06-20 16:30
Gonna close this as a dupe of https://github.com/rust-lang/rust/issues/13998 if you don't mind.

**Closed** 2015-06-20 16:30 UTC
