### ISSUE TITLE
RELEASES.md is too big, move older content

### ISSUE THREAD

**Issue by tomaszs** [rust-lang/rust#111599] opened 2023-05-15 14:59 UTC
https://github.com/rust-lang/rust/blob/master/RELEASES.md:

![image](https://github.com/rust-lang/rust/assets/834977/7322b4d6-a04f-41ae-a48d-ad7274679d41)

**Comment by ehuss** [comment] 2023-05-15 20:53
Thanks for the report! This is an issue that sometimes clears up based on GitHub's servers and caching. I'm going to close as a duplicate of #101714.

**Closed by ehuss** 2023-05-15 20:53 UTC
