### ISSUE TITLE
rustdoc panic on stable 1.30: crate typenum

### ISSUE THREAD

**Issue by stevedonovan** [rust-lang/rust#55671] opened 2018-11-04 09:15 UTC
The panic was "error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached"

Caused by this command "rustdoc --crate-name typenum /home/steve/.cargo/registry/src/github.com-1ecc6299db9ec823/typenum-1.10.0/src/lib.rs --cap-lints allow --color always -o /home/steve/.cargo/.runner/static-cache/target/doc -L dependency=/home/steve/.cargo/.runner/static-cache/target/debug/deps"

rustc 1.30.0 (da5f414c2 2018-10-24)
binary: rustc
commit-hash: da5f414c2c0bfe5198934493f04c676e2b23ff2e
commit-date: 2018-10-24
host: x86_64-unknown-linux-gnu
release: 1.30.0
LLVM version: 8.0

**Comment by garro95** [comment] 2018-11-04 09:31
I can confirm. I get the following error message
```
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached
                                                                                
thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9         
note: Run with `RUST_BACKTRACE=1` for a backtrace.                              
                                                                                
note: the compiler unexpectedly panicked. this is a bug.                        
                                                                                
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                
note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-unknown-linux-gnu   
                                                                                
error: Could not document `typenum`.                                            
```

**Comment by pietroalbini** [comment] 2018-11-04 21:56
Duplicate of #52873

**Closed by pietroalbini** 2018-11-04 21:56 UTC
