### ISSUE TITLE
Compiler panics in 1.9.0-MSVC in cargo --release

### ISSUE THREAD

**Issue by drewhk** [rust-lang/rust#33984] opened 2016-05-31 15:26 UTC
I cannot pinpoint any particular code snippet that caused the issue. It worked with 1.8.0, but compiler panics with 1.9.0, when "--release" flag is used. It works with nightly, so the problem might have been fixed already. Backtrace is:

```
   0: 0x64a9d555 - std::panicking::set_hook::hb28f33acbf0b0356
   1: 0x64a64223 - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   2: 0x64a66200 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   3: 0x64a902f2 - rust_begin_unwind
   4: 0x63be7904 - rustc_metadata::index::IndexData::record_index::h5c51de9f7bcef1a1
   5: 0x63bc8aa7 - rustc_metadata::loader::Context::load_library_crate::h7787c1fa9559d604
   6: 0x63bc7a57 - rustc_metadata::cstore::CStore::add_used_crate_source::hb8cfca543a80958d
   7: 0x63bc95aa - rustc_metadata::cstore::CStore::get_crate_data::h3afadf99d67c051f
   8: 0x63bc932f - rustc_metadata::cstore::CStore::get_crate_data::h3afadf99d67c051f
   9: 0x63bc464f - rustc_metadata::cstore::crate_metadata::disambiguator::h3a15115684054a50
  10: 0x63bca752 - rustc_metadata::cstore::CStore::get_crate_data::h3afadf99d67c051f
  11: 0x63bcc8ab - rustc_metadata::creader::CrateReader::read_exported_macros::hf3b61431145aafb6
  12: 0x63bf7b04 - _<macro_import..MacroLoader<'a> as syntax..visit..Visitor<'v>>::visit_item::h668e7bfc1acab9b3
  13: 0x63bf673d - rustc_metadata::macro_import::read_macro_defs::h240a20dad60749cc
  14: 0x64db5a6c - rustc_driver::driver::phase_2_configure_and_expand::h505e157de342d54f
  15: 0x64d98fc5 - rustc_driver::driver::compile_input::h6491aaddd9e61258
  16: 0x64d864c2 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  17: 0x64d83485 - rustc_driver::run::h42f3df4e2bc31796
  18: 0x64a90201 - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  19: 0x64a9016e - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  20: 0x64d83e72 - rustc_driver::run::h42f3df4e2bc31796
  21: 0x64a9b47e - std::sys::thread::Thread::new::h0ce8c68d6db7e3f8
  22: 0x765038f3 - BaseThreadInitThunk
  23: 0x779d5de2 - RtlUnicodeStringToInteger
```

I can provide more information if you tell me what you need and how can I acquire it.
## Meta

rustc 1.9.0 (e4e8b6668 2016-05-18)
binary: rustc
commit-hash: e4e8b666850a763fdf1c3c2c142856ab51e32779
commit-date: 2016-05-18
host: i686-pc-windows-msvc
release: 1.9.0

**Comment by alexcrichton** [comment] 2016-05-31 16:09
@drewhk would it be possible to gist the code to reproduce this?

**Comment by drewhk** [comment] 2016-06-01 08:44
Well, it is a "test junkyard" where I play with both Rust and WinAPI (new to both), so probably a bit hairy, but I didn't mean it for the public anyway :) Nevertheless, here it is: https://gist.github.com/drewhk/657eb7ea2071ccb355410e816b462978

**Comment by nagisa** [comment] 2016-06-01 11:42
Potentially a duplicate of https://github.com/rust-lang/rust/issues/33778

**Comment by Mark-Simulacrum** [comment] 2017-05-04 17:59
I don't have a MSVC environment to test this on. Could someone check if this has been fixed?

**Comment by Mark-Simulacrum** [comment] 2017-06-22 16:45
"It works with nightly, so the problem might have been fixed already." from the description and the fact that https://github.com/rust-lang/rust/issues/33778 is closed means that I'm going to assume this is now fixed. If not, we'll reopen -- let me know.

**Closed by Mark-Simulacrum** 2017-06-22 16:45 UTC
Labels: I-ICE
