### ISSUE TITLE
Internal Compiler Error: thread 'rustc' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by traditionalism** [rust-lang/rust#84167] opened 2021-04-13 18:56 UTC
While using the winres crate this was the build.rs script for applying a .ico for my executable. As soon as the build.rs script was removed my project compiled successfully without either being hung up on the winres crate or failing/panicking. Oddly enough it compiles normally on a x64 nightly/stable-toolchain. Possible winres crate compatibility problem. 
### Code

```Rust
use std::io;
#[cfg(windows)] use winres::WindowsResource;

fn main() -> io::Result<()> {
    #[cfg(windows)] {
        WindowsResource::new()
            .set_icon("assets/app.ico")
            .compile()?;
    }
    Ok(())
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (d0695c908 2021-04-12)
binary: rustc
commit-hash: d0695c9081b16077d0aed368bccaf437d77ff497
commit-date: 2021-04-12
host: i686-pc-windows-msvc
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Some(Fingerprint(1288127715427098368, 6593689844980031578))`,
 right: `Some(Fingerprint(7144034568373601688, 1022598649938892905))`: found unstable fingerprints for predicates_of(core[610a]::ops::arith::Neg): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::Neg>), []), C:\Users\lucas\.rustup\toolchains\nightly-i686-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\arith.rs:653:1: 653:14 (#0))] }', /rustc/d0695c9081b16077d0aed368bccaf437d77ff497\compiler\rustc_query_system\src\query\plumbing.rs:593:5
error: internal compiler error: unexpected panic
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::Neg`
#1 [typeck] type-checking `main`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

N/A as using RUST_BACKTRACE=1 variable gives me "note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace." Meanwhile using RUST_BACKTRACE=full gives me a PowerShell error
```
N/A
```

</p>
</details>

**Comment by traditionalism** [comment] 2021-04-15 14:12
https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/ops/arith.rs#L653

**Comment by JohnTitor** [comment] 2021-04-28 12:58
cc #84341

**Comment by Aaron1011** [comment] 2021-05-02 01:00
Duplicate of https://github.com/rust-lang/rust/issues/84341. This is fixed in the latest nightly

**Closed** 2021-05-02 07:38 UTC
Labels: A-incr-comp, C-bug, I-ICE, T-compiler
