### ISSUE TITLE
Compile error when conditionally compilation nightly const_trait_impl

### ISSUE THREAD

**Issue by uselessgoddess** [rust-lang/rust#99675] opened 2022-07-24 13:40 UTC
I tried cfg nightly feature `const_trait_impl` and I get a compilation error with the following code:
```rust
#![cfg_attr(feature = "const_fn", feature(const_trait_impl))]

#[cfg(not(feature = "const_fn"))]
fn const_fn<T>(t: T) {}

#[cfg(feature = "const_fn")]
use std::marker::Destruct;

#[cfg(feature = "const_fn")]
const fn const_fn<T>(t: T)
where
    T: ~const Destruct,
{
}

fn main() {
    const_fn(12);
}
```
But this leads to compile error (with `cargo run`):
```
error[E0658]: const trait impls are experimental                                                 
  --> src\main.rs:12:8                                                                           
   |                                                                                             
13 |     T: ~const Destruct,                                                                     
   |        ^^^^^^                                                                               
   |                                                                                             
   = note: see issue #67792 <https://github.com/rust-lang/rust/issues/67792> for more information
   = help: add `#![feature(const_trait_impl)]` to the crate attributes to enable                 
                                                                                                 
For more information about this error, try `rustc --explain E0658`.
```

For example, with `try_blocks` feature there is no compile error:
```rust
#![cfg_attr(feature = "try_fn", feature(try_blocks))]

#[cfg(feature = "try_fn")]
fn try_fn() {
    let x: Option<_> = try { 123 };
}

#[cfg(not(feature = "try_fn"))]
fn try_fn() {}

pub fn main() {
    try_fn();
}
```
I think it looks like a bug, is it?
---
I use `nightly-x86_64-pc-windows-msvc - rustc 1.64.0-nightly (93ffde6f0 2022-07-23)`

**Comment by CAD97** [comment] 2022-07-24 17:57
So this is the difference between "syntax valid" and "semantics valid".

If an item is `#[cfg]`'d out, it is still checked for being valid syntax. Though various (perhaps incidental) decisions, `try { }` is a stable syntax, but `~const Trait` is an unstable syntax. The consequence of this is that `try { }` has to always be accepted syntax for `#[cfg(FALSE)]` and proc macro attribute input, but `~const Trait` syntax is gated such that if we decide we don't want `~const` (perhaps replacing it with a more general [keyword generics](https://github.com/rust-lang/keyword-generics-initiative) feature?) it can be fully removed from the compiler.

If you want to conditionally use unstable syntax, you need to hide the syntax in place where it is not validated, such as within a bang-style macro (where you are just subject to the lexical syntax) or in an outlined `#[cfg] mod` or `#[cfg] include!()`.

**Comment by uselessgoddess** [comment] 2022-07-24 18:01
Ok, thanks for your reply

**Comment by fmease** [comment] 2024-01-25 21:47
This works exactly as intended: We nowadays perform pre-expansion (in this case pre-`#[cfg]`) feature gate checks to make sure that experimental syntax is always enabled by `#![feature]`. Closing as works-as-intended.

**Closed by fmease** 2024-01-25 21:47 UTC
Labels: A-parser, A-macros, C-discussion
