### ISSUE TITLE
Doc test bug: recognize `/// -                       a` as doctest

### ISSUE THREAD

**Issue by gwy15** [rust-lang/rust#104810] opened 2022-11-24 08:25 UTC
I tried this code:

```rust
/// comment
///
/// -               panic!()
pub fn f() {}

```

I expected to see this happen when running `cargo test`: *nothing*

Instead, this happened: *thread 'main' panicked at 'explicit panic', src/lib.rs:3:1*

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: aarch64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by ehuss** [comment] 2022-11-24 13:24
Thanks for the report!  I understand this is a bit confusing, but it is mostly working as intended. The commonmark spec specifies that indented text is a code block. Rustdoc by default treats all code blocks as "rust" code unless otherwise specified.

I'm going to close since this has been reported before. Closing as a duplicate of #64162, #59867, #88590, #100225.

**Closed by ehuss** 2022-11-24 13:24 UTC
Labels: C-bug
