### ISSUE TITLE
macro fragment names are no longer idents

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#42019] opened 2017-05-15 21:58 UTC
This is a stable-to-beta regression, but it's such a weird thing to do that I don't know if it counts.

Consider the following code ([playpen](https://is.gd/RmWrlU)):

```rust
macro_rules! gen {
    ($name:ident ($($dol:tt $var:ident)*) $($body:tt)*) => {
        macro_rules! $name {
            ($($dol $var:ident)*) => {
                $($body)*
            }
        }
    }
}
```

The `gen` macro parses a macro argument spec by matching a dollar sign with `$dol` and the fragment name with `$var`. Then (in this toy example) it just regurgitates that adding `:ident` as the type of each fragment.

This works in 1.17, but fails when invoked in 1.18 and nightly with the message "expected identifier, found [the ident passed in for `$var`]", pointing at `$var` on line 4. All three channels work if `$var:ident` is changed to `$var:tt` on line 2.

**Comment by durka** [comment] 2017-05-15 22:00
cc @jseyfried

**Comment by jseyfried** [comment] 2017-05-15 23:26
I believe this is a duplicate of #41803; it should be fixed once #42005 lands.

**Comment by nagisa** [comment] 2017-05-18 16:26
Now that #42005 has landed, this should be re-reproduced.

**Comment by durka** [comment] 2017-05-18 17:00
It landed, but why is there no nightly?

**Comment by durka** [comment] 2017-05-19 06:13
This was **not fixed** by #42005. It is still broken with rustc 1.19.0-nightly (0ed1ec9f9 2017-05-18).

**Comment by brson** [comment] 2017-05-25 16:54
Still broken on beta?

**Comment by durka** [comment] 2017-05-25 19:34
Yes, the code in the playpen still fails to compile on beta and nightly.

**Comment by nikomatsakis** [comment] 2017-05-25 20:08
cc @Mark-Simulacrum -- it'd be great to know just what caused this problem. @jseyfried, are you going to have time to investigate?

**Comment by Mark-Simulacrum** [comment] 2017-05-25 20:11
If I have a chance I'll run bisect-rust, also cc @est31 -- they have it working locally as well.

**Comment by Mark-Simulacrum** [comment] 2017-05-25 21:27
Ran bisect: fe151194e9a919ab23c2bb356767a5cbfa3811e7 - #40597.

**Comment by jseyfried** [comment] 2017-05-25 21:41
Yeah, I'll investigate/fix this weekend.

**Comment by nikomatsakis** [comment] 2017-06-08 20:08
@jseyfried any progress?

**Comment by brson** [comment] 2017-07-13 16:16
This is a P-high bug and it is inactive cc @rust-lang/compiler

**Comment by jseyfried** [comment] 2017-07-13 21:13
Fixed in #43224.

**Closed** 2017-07-15 21:36 UTC
Labels: A-macros, I-nominated, I-wrong, P-high, regression-from-stable-to-stable, T-compiler
