### ISSUE TITLE
`#[expect(...)]` doen't catch lints from different `check_*` function

### ISSUE THREAD

**Issue by Jarcho** [rust-lang/rust#97660] opened 2022-06-02 18:32 UTC
Some lints are emitted from a from a different from the area they are linted. e.g. `clippy::ptr_arg` is linting from `check_body`, but it can be allowed from the argument (`fn foo(#[allow(clippy::ptr_arg)] x: &Vec<u32>) {}`).

The following lints in clippy (and probably more) lint from different `check_*` functions:
* `needless_borrow`
* `ref_binding_to_ref`
* `duplicate_mod`
* `multiple_inherent_impl`
* `macro_use_imports`
* `manual_non_exhaustive`
* `same_name_method`
* `async_yields_async`
* `await_holding_lock`
* `await_holding_refcell`
* `await_holding_invalid_type`
* `default_numeric_fallback`
* `ptr_arg`
* `redundant_clone`
* `logic_bug`
* `nonminimal_bool`
* `boxed_local`
* `implicit_return`
* `needless_return`
* `unnecessary_unwrap`
* `panicking_unwrap`

Some of these don't actually work with `allow` at a narrower scope either, but some of them check to see if the lint has been allowed on the target item before emitting the lint.

cc #54503

**Comment by xFrednet** [comment] 2022-06-06 09:54
@rustbot claim. I'll go through these lints one by one. The first two were caused by wrong emission functions on Clippy's side.

Todo List:
* [ ] `needless_borrow`
* [ ] `ref_binding_to_ref`
* [ ] `duplicate_mod`
* [ ] `multiple_inherent_impl`
* [ ] `macro_use_imports`
* [ ] `manual_non_exhaustive`
* [ ] `same_name_method`
* [ ] `async_yields_async`
* [ ] `await_holding_lock`
* [ ] `await_holding_refcell`
* [ ] `await_holding_invalid_type`
* [ ] `default_numeric_fallback`
* [ ] `ptr_arg`
* [ ] `redundant_clone`
* [ ] `logic_bug`
* [ ] `nonminimal_bool`
* [ ] `boxed_local`
* [ ] `implicit_return`
* [ ] `needless_return`
* [ ] `unnecessary_unwrap`
* [ ] `panicking_unwrap`

**Comment by xFrednet** [comment] 2022-06-10 19:36
The next step for this issue is to adapt the linting interface of rustc to allow the manual fulfillment of expectations. Then I have to take a look at the last few lints, but they should all be covered by these changes.

@Jarcho, have you also looked at rustc lints or just at Clippy's lints? :upside_down_face:

**Comment by Jarcho** [comment] 2022-06-22 18:36
It doesn't look like any of the rustc lints need to be changed. At least the behaviour of `expect` shouldn't be different than `allow` is.

**Comment by xFrednet** [comment] 2023-01-12 10:09
I believe this issue can be closed now. All of these have been the result of suboptimal handling in Clippy. Most of these should be fixed or tracked in a new issue in Clippy.

@Jarcho Could you close it, if you agree? :upside_down_face:

**Comment by Dylan-DPC** [comment] 2023-02-03 08:44
Closing this as rest of lints are [tracked here](https://github.com/rust-lang/rust-clippy/issues/9047)

**Closed by Dylan-DPC** 2023-02-03 08:44 UTC
Labels: C-bug, A-clippy, F-lint_reasons
