### ISSUE TITLE
`@ + identifier` not documented

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#35022] opened 2016-07-25 04:02 UTC
I have seen some Rust macros that use something like `@var` to select which arm of the macro to recursively call itself. This usage, however, is not documented anywhere, in the book or otherwise.

One usage of the @ identifier can be seen [here](https://github.com/rust-lang-nursery/bitflags/blob/master/src/lib.rs#L213).

**Comment by sfackler** [comment] 2016-07-25 04:44
The `@var` syntax is just a convention of some kinds of macros, it's not a special syntactic feature. It doesn't mean anything special other than a literal sequence of characters.

**Comment by eddyb** [comment] 2016-07-25 17:37
It is literally two tokens, `@` and an identifier, they can be separated by any number of spaces without changing the meaning.
To expand on what @sfackler said, `macro_rules` macros can match on any sequence on tokens (except for `$`, due to a lack of escaping in macros).
This ended up being used with `@` in a lot of macros, among other things, because `@` has only one use in the language atm, `identifier @ pattern` for binding *and* matching on a pattern, at the same time,
and this is not a prefix use of `@`, so no valid expressions, types or items can start with `@`.

**Comment by steveklabnik** [comment] 2016-07-25 20:26
Closing as "not a bug". Thanks!

**Closed by steveklabnik** 2016-07-25 20:26 UTC
