### ISSUE TITLE
Initializing wrapper struct private field blows up system memory.

### ISSUE THREAD

**Issue by meowjesty** [rust-lang/rust#119631] opened 2024-01-05 18:48 UTC
I tried initializing a private field from a wrapper struct `pub struct Foo(/*private fields*/)` that is defined in another crate, and Rust started to eat all my system memory, until I was forced to restart the computer.

Unfortunately the code that caused this from my side is closed source, but I was trying to initialize the [`Extensions`](https://docs.rs/x509-certificate/latest/x509_certificate/rfc5280/struct.Extensions.html) struct like this: 

```rust
let extensions = Extensions(
        license
            .certificate
            .iter_extensions()
            .cloned()
            .collect::<Vec<_>>(),
    );
```

I expected to see this happen: 

Either a compiler crash or just the compiler giving me an error saying that you can't do that!

Instead, this happened:

System memory usage kept going up and up, until it crashed my pc. Limiting `cargo check` memory usage just meant that the process was killed, so no error messages either.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (1fdfe1234 2023-12-06)
binary: rustc
commit-hash: 1fdfe1234795a289af1088aefa92ef80191cb611
commit-date: 2023-12-06
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

I've also tried (and got the same results) `nightly-2024-01-05`.

We got this issue in 3 different systems, 2 being linux x64 and one being macos (with the m1/2 arch, whatever that is called).

<details><summary>Backtrace</summary>
<p>

No backtrace, rust didn't produce any error output, it just got stuck in `checking {crate-name}` forever.

```
<backtrace>
```

</p>
</details>

**Comment by lukas-code** [comment] 2024-01-05 21:58
Probably duplicate of https://github.com/rust-lang/rust/issues/119625.

I tried this code:

```rust
// x509-certificate = "=0.23.1"

use x509_certificate::rfc5280::{Certificate, Extensions};

pub fn foo(cert: Certificate) {
    let _e = Extensions(cert.iter_extensions().cloned().collect::<Vec<_>>());
}
```

and it appears to be fixed by https://github.com/rust-lang/rust/pull/119638 as well:

```text
error[E0423]: cannot initialize a tuple struct which contains private fields
   --> src/lib.rs:4:14
    |
4   |     let _e = Extensions(cert.iter_extensions().cloned().collect::<Vec<_>>());
    |              ^^^^^^^^^^
    |
note: constructor is not visible here due to private fields
   --> /home/lukas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/x509-certificate-0.23.1/src/rfc5280.rs:483:23
    |
483 | pub struct Extensions(Vec<Extension>);
    |                       ^^^^^^^^^^^^^^ private field

For more information about this error, try `rustc --explain E0423`.
```

**Closed** 2024-01-07 01:06 UTC
Labels: I-crash, I-compilemem, C-bug
