### ISSUE TITLE
Stdout should be flushed on exit

### ISSUE THREAD

**Issue by tsion** [rust-lang/rust#23205] opened 2015-03-08 22:26 UTC
See http://is.gd/SH4nll

This fails to print anything since `"hey"` in only written to the buffer and then never printed. Other `BufWriter`s [flush on drop](https://github.com/rust-lang/rust/blob/master/src/libstd/io/buffered.rs#L213-L221) but this isn't happening for `Stdout` at program exit.

**Comment by shepmaster** [comment] 2015-03-09 13:15
Duplicate of #23191, which is closed in favor of #20012

**Comment by alexcrichton** [comment] 2015-03-09 15:55
Indeed, thanks @shepmaster!

**Closed by alexcrichton** 2015-03-09 15:55 UTC
