### ISSUE TITLE
NLL: match arm binding wrong suggestion in error message

### ISSUE THREAD

**Issue by martin-t** [rust-lang/rust#51554] opened 2018-06-14 14:52 UTC
Using this code on nightly:

```rust
#![feature(nll)]

enum E {
    Variant(i32),
}

fn main() {
    let e = E::Variant(5);
    match e {
        E::Variant(ref some_name) => *some_name += 10,
    }
}
```

I get this error message:

```
error[E0594]: cannot assign to data in a `&` reference
  --> src/main.rs:10:38
   |
10 |         E::Variant(ref some_name) => *some_name += 10,
   |                    -------------     ^^^^^^^^^^^^^^^^
   |                    |
   |                    help: consider changing this to be a mutable reference: `&mut ef some_name`
error: aborting due to previous error

For more information about this error, try `rustc --explain E0594`.
```

([playground link](http://play.integer32.com/?gist=d10f58bca147beb7bfbd4e369b6ad965&version=nightly&mode=debug))

The correct suggestion is `ref mut some_name`.

## Meta

`rustc --version --verbose`:

```
rustc 1.28.0-nightly (b907d9665 2018-06-13)
binary: rustc
commit-hash: b907d966528a6859ec847a2a4d32f092a5be6584
commit-date: 2018-06-13
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```

**Comment by ashtneoi** [comment] 2018-06-17 06:30
This looks like it has the same root cause as #51515.

**Comment by nikomatsakis** [comment] 2018-06-29 20:04
Current error that I see is:

```
error[E0594]: cannot assign to `*some_name` which is behind a `&` reference
  --> src/main.rs:10:38
   |
10 |         E::Variant(ref some_name) => *some_name += 10,
   |                                      ^^^^^^^^^^^^^^^^ cannot assign
```

**Comment by nikomatsakis** [comment] 2018-06-29 20:04
This seems pretty good to me. Closing as fixed. Thanks @martin-t

**Closed by nikomatsakis** 2018-06-29 20:04 UTC
Labels: A-NLL, C-enhancement, NLL-diagnostics, T-compiler, WG-compiler-nll
