### ISSUE TITLE
rustc suggests using a trait with a private path instead of a public ones

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#59269] opened 2019-03-18 06:25 UTC
These are the errors I get:
```
error[E0603]: module `to_tokens` is private=================>        ] 119/139: rustc_macros
  --> src\librustc_macros\src\query.rs:11:12
   |
11 | use quote::to_tokens::ToTokens;
   |            ^^^^^^^^^

warning: unused import: `quote::to_tokens::ToTokens`
  --> src\librustc_macros\src\query.rs:11:5
11 | use quote::to_tokens::ToTokens;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0599]: no method named `into_token_stream` found for type `syn::path::Path` in the current scope
  --> src\librustc_macros\src\query.rs:94:73
   |
94 |             panic!("attribute `{}` not supported on queries", attr.path.into_token_stream())
   |                                                                         ^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use quote::to_tokens::ToTokens;`

error: aborting due to 2 previous errors
```
rustc should instead suggest I use the public path `quote::ToTokens`.

**Comment by dtolnay** [comment] 2019-10-21 20:11
Closing as a duplicate of #21934.

**Closed by dtolnay** 2019-10-21 20:11 UTC
Labels: A-suggestion-diagnostics
