### ISSUE TITLE
Cannot return `never` type as impl Trait (like `unimplemented!()` stub)

### ISSUE THREAD

**Issue by ilyavenner** [rust-lang/rust#71715] opened 2020-04-30 17:38 UTC
I tried [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b9c8e6ce0e6f9fae3a5e36f186de34f2) code:

```rust
trait Foo {
    fn foo(&self);
}

impl Foo for i32 {
    fn foo(&self) {
        println!("<Foo as i32>::foo")
    }
}

fn bar() -> impl Foo {
    42
}

fn baz() -> impl Foo {
    unimplemented!()
}
```
I expected to see this happen: _successful compilation_. Instead, this happened: **compilation error**:
```
error[E0277]: the trait bound `(): Foo` is not satisfied
  --> src/lib.rs:15:13
   |
15 | fn baz() -> impl Foo {
   |             ^^^^^^^^ the trait `Foo` is not implemented for `()`
16 |     unimplemented!()
   |     ---------------- this returned value is of type `!`
   |
   = note: the return type of a function must have a statically known size
```
### Meta

`rustc --version --verbose`:
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-unknown-linux-gnu
release: 1.43.0
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment] 2020-04-30 17:40
Duplicate of https://github.com/rust-lang/rust/issues/69882

**Closed by jonas-schievink** 2020-04-30 17:40 UTC
Labels: C-bug

**Comment by ilyavenner** [comment] 2020-04-30 17:51
I looked at that problem. But I still did not understand how I can mark a function as unimplemented.

**Comment by jonas-schievink** [comment] 2020-04-30 17:54
I suggest you ask on https://users.rust-lang.org/, since this issue tracker is only really for bug reports
