### ISSUE TITLE
`unpretty=expanded` removes syntactically meaningful braces

### ISSUE THREAD

**Issue by Cerber-Ursi** [rust-lang/rust#118197] opened 2023-11-23 02:15 UTC
I tried macro-expanding this code:

```rust
enum E { A }

macro_rules! foo {
    () => { E::A { { } } }
}

fn main() {
    let _ = foo!();
}
```

I expected to see this happen: `foo!()` is expanded to exactly the tokens it provides, i.e. `E::A { { } }`.

Instead, this happened: `foo!()` is expanded to `E::A { }`, which hides the fact that the expansion has a syntax error.

### Meta

`rustc --version --verbose`:
```
rustc 1.74.0 (79e9716c9 2023-11-13)
binary: rustc
commit-hash: 79e9716c980570bfd1f666e3b16ac583f0168962
commit-date: 2023-11-13
host: x86_64-unknown-linux-gnu
release: 1.74.0
LLVM version: 17.0.4
```

Initially found [on URLO](https://users.rust-lang.org/t/mysterious-procedural-macro-error/102897) and reported as https://github.com/dtolnay/cargo-expand/issues/201.

**Comment by fmease** [comment] 2023-11-23 21:19
Hmm, well `-Zunpretty=expanded` pretty-prints the AST which is output by the parser which does parse error recovery and macros must expand to valid Rust syntax not arbitrary token streams. I don't see a bug.

`enum E { V; }` (with a semicolon) and `macro_rules! m { () => { enum E { V; } } } m! {}` both yield `enum E { V, }` with `-Zunpretty=expanded` since that's what the AST pretty-printer sees.

**Comment by fmease** [comment] 2023-11-25 09:31
I'd lean towards closing this issue as not planned. However, I admit that the issue encountered with `cargo expand` (dtolnay/cargo-expand#201) is unfortunate. Basically, the output of `cargo expand` / `-Zunpretty=expand` is not an accurate indicator for syntax errors in the original source code.

cc @dtolnay

**Comment by dtolnay** [comment] 2023-11-25 15:09
I agree with closing. This is intended behavior of error recovery in the parser.

**Closed** 2023-11-25 15:09 UTC
Labels: A-pretty, A-parser, A-macros, T-compiler, A-error-handling, requires-nightly, C-discussion
