### ISSUE TITLE
Internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by saresend** [rust-lang/rust#45705] opened 2017-11-01 23:45 UTC
I was working on cross compiling rust and I ran into the issue in the title. I was trying to run the following function:
<code> rustc --print target-list | pr -tw100 --columns 3 </code>
When it panicked. 

Rust Version: <code>rustc 1.20.0 (f3d6973f4 2017-08-27) running on x86_64-apple-darwin</code>

if it helps, the piped pr command gave the following output: 
<code> pr: illegal option -- - </code>

And here is the panic error from rust:

<code> thread 'rustc' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:692:8 </code>

**Comment by sinkuu** [comment] 2017-11-01 23:52
Duplication of #34376?

**Comment by estebank** [comment] 2017-12-07 01:42
Closing as duplicate of #34376.

**Closed by estebank** 2017-12-07 01:42 UTC
