### ISSUE TITLE
"list index out of range" during LLVM configuration

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#76408] opened 2020-09-06 13:29 UTC
When LLVM is built, the log shows this:
```
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.10.0
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Targeting X86
-- Targeting AVR
Traceback (most recent call last):
  File "<string>", line 22, in <module>
IndexError: list index out of range
-- Configuring done
-- Generating done
-- Build files have been written to: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/llvm/build
```
Notice the strange Python (?) backtrace in the middle of this -- that probably shouldn't be there.

Cc @Mark-Simulacrum

**Comment by jyn514** [comment] 2021-01-01 05:06
Duplicate of https://github.com/rust-lang/rust/issues/76470 (this came first, but has less discussion).

**Closed by jyn514** 2021-01-01 05:06 UTC
Labels: A-LLVM, A-rustbuild, C-bug
