### ISSUE TITLE
Major compile time regression for regex crate

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#34998] opened 2016-07-23 20:03 UTC
You can see it on http://perf.rust-lang.org/graphs.html around 6/30.

**Comment by nagisa** [comment] 2016-07-24 07:49
Duplicate of https://github.com/rust-lang/rust/issues/34831.

**Comment by alexcrichton** [comment] 2016-07-25 04:46
Closing (and copying tags to that issue)

**Closed by alexcrichton** 2016-07-25 04:46 UTC
Labels: I-nominated, I-slow, regression-from-stable-to-nightly, T-compiler
