### ISSUE TITLE
Add a special-cased error message for returning a Result from main, to indicate improper try! usage

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#29605] opened 2015-11-05 03:39 UTC
To beginners it's surprising that `try!` can only be used within a function with a `Result` return type, which in particular means it cannot be used from main. In the past we've mulled over language-level support for solving this problem but ultimately maybe we just need a better error message. How hard would it be to just detect `try!` being called from within main and give a nice and specific error message?

**Comment by steveklabnik** [comment] 2015-11-05 09:27
This is a duplicate of https://github.com/rust-lang/rust/issues/27112

**Closed by steveklabnik** 2015-11-05 09:27 UTC
Labels: A-diagnostics
