### ISSUE TITLE
Failed to remove rcgu: no such file or directory

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#54042] opened 2018-09-07 19:56 UTC
Discovered when investigating https://github.com/rust-lang/rust/issues/53794. When rustc is run, the following errors result:

```
error: failed to remove /usr/local/google/home/cramertj/src/tmp/link-error-repro/out_bin.2iwg8cehlsr9x4yn.rcgu.o: No such file or directory (os error 2)

error: failed to remove /usr/local/google/home/cramertj/src/tmp/link-error-repro/out_bin.2pkbt36vpf5knaqz.rcgu.o: No such file or directory (os error 2)

error: failed to remove /usr/local/google/home/cramertj/src/tmp/link-error-repro/out_bin.3qtydzyditwwd0wd.rcgu.o: No such file or directory (os error 2)

error: failed to remove /usr/local/google/home/cramertj/src/tmp/link-error-repro/out_bin.52wfm87ulo3v297x.rcgu.o: No such file or directory (os error 2)

error: failed to remove /usr/local/google/home/cramertj/src/tmp/link-error-repro/out_bin.57gef1f2kxtrvbuy.rcgu.o: No such file or directory (os error 2)

error: aborting due to 5 previous errors
``` 

To repro, check out https://github.com/cramertj/link-error-repro/commit/b4b055cadec6caa3aefa908df65e3ac1c2ee7506, grab `rustc 1.30.0-nightly (6e0f1cc15 2018-09-05)`, and run `./clone_sdk.sh && ./build_deps.sh && ./build_bin.sh`. If using a different `rustc`, the hashes in `./build_bin.sh` will need to be adjusted to match the suffixes of `libstructopt` and `librand` in the `target/` dir.

**Comment by cramertj** [comment] 2018-09-07 19:58
[Full logs are here](https://gist.github.com/cramertj/62a0fca3055d420446beffb488c1c860)

**Comment by matthiaskrgr** [comment] 2018-09-08 01:07
Just got this too (rustc 1.30.0-nightly (fc81e3624 2018-09-07), however my crate use monolithic lto
````
   [profile.release]
   lto = true
   codegen-units = 1
````
I thought this would be a thinlto problem?

**Comment by alexcrichton** [comment] 2018-09-10 23:19
I've confirmed this is a duplicate of https://github.com/rust-lang/rust/issues/53794#issuecomment-420092479, so closing in favor of that.

**Closed by alexcrichton** 2018-09-10 23:19 UTC
Labels: C-bug
