### ISSUE TITLE
Exhaustiveness of pattern matching for numerical values.

### ISSUE THREAD

**Issue by tmielcza** [rust-lang/rust#32381] opened 2016-03-20 21:16 UTC
When I try to compile this code:

```rust
fn main() {
    let t: u8 = 3;
    match t {
        0x00...0x100 => (),
    }
}
```
I got the following error:
```
src/main.rs:36:5: 38:6 error: non-exhaustive patterns: `_` not covered [E0004]
src/main.rs:36     match t {
src/main.rs:37         0x00...0x100 => (),
src/main.rs:38     }
```

while `0x00` to `0x100` covers all possible values for a `u8`.
Why is that?

**Comment by jonas-schievink** [comment] 2016-03-20 21:22
This is just not implemented. Last time this was brought up, it was closed in favor of an RFC.

(`0x100` is too large for `u8` by the way - you want `0xff` since `...` is inclusive)

**Comment by steveklabnik** [comment] 2016-03-21 15:13
Yes, this is a duplicate of https://github.com/rust-lang/rust/issues/12483, and would require an RFC.

**Closed by steveklabnik** 2016-03-21 15:13 UTC
