### ISSUE TITLE
LLVM ld64.lld

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust#85938] opened 2021-06-02 16:17 UTC
I tried to use the new MachO linker from LLVM:

```bash
RUSTFLAGS="-C linker=/Users/tschuett/modules/clang/git/bin/ld64.lld" cargo build

  = note: ld64.lld:
          ld64.lld: error: unknown argument '-Wl,-dead_strip'
          ld64.lld: error: must specify -platform_version
```

First issue, rust appends -Wl, which makes the linker unhappy. Dead stripping is supported since today (https://reviews.llvm.org/D103324).

Second issue the linker requires a platform version:
https://github.com/llvm/llvm-project/blob/06e047227d71b2c1c477e280172abed0f1eed2c8/lld/MachO/Driver.cpp#L598

platform_version was introduced into clang:
https://reviews.llvm.org/D71579

Did the `LinkerFlavor` detection fail?

https://github.com/rust-lang/rust/issues/39915

**Comment by tschuett** [comment] 2021-06-02 17:04
The full error message:
```bash
  = note: ld64.lld: error: unknown argument '-m64'
          ld64.lld: error: unknown argument '-Wl,-dead_strip'
          ld64.lld: error: unknown argument '-nodefaultlibs'
          ld64.lld: error: must specify -platform_version
```

**Comment by tschuett** [comment] 2021-06-02 18:51
The -m64 issue is:
https://github.com/llvm/llvm-project/blob/70804f2a2f7b87227a873cd6d8852ad295068e79/lld/MachO/Options.td#L1040

**Comment by tschuett** [comment] 2021-06-02 18:53
I couldn't find -nodefaultlibs neither in the ld man page nor in Options.td file. It seems to be a GNU thing.

**Comment by tschuett** [comment] 2021-06-03 08:43
`GccLinker`needs to distinguish between LLVM and Apple ld. It needs the Apple deployment target.

**Comment by tschuett** [comment] 2021-06-03 09:58
ld64.lld is missing here:
https://github.com/rust-lang/rust/blob/016e9b5e33ef1407bffb575ec63d24241912556d/compiler/rustc_codegen_ssa/src/back/link.rs#L957

**Comment by tschuett** [comment] 2021-06-03 20:07
Add platform_version:
https://github.com/rust-lang/rust/blob/257782579915963c9dbe7433102275743837b9a8/compiler/rustc_codegen_ssa/src/back/link.rs#L2209

```bash
xcrun --show-sdk-platform-version -sdk macosx
```

**Comment by petrochenkov** [comment] 2021-06-07 17:42
Closing as a duplicate of https://github.com/rust-lang/rust/issues/11937 since this issue is about using `ld64` directly rather than through a C compiler.

**Closed by petrochenkov** 2021-06-07 17:42 UTC
