### ISSUE TITLE
Auto-dereferencing bug?

### ISSUE THREAD

**Issue by wooque** [rust-lang/rust#24551] opened 2015-04-18 11:08 UTC
Auto-dereferencing is working if `&Box<Struct>` is in place of `&Struct` function argument, or in:

``` rust
let x: &Struct = &_boxed_struct; // &Box<Struct>
```

but not if Struct reference is destructured:

``` rust
let &Struct{a: a1, b: b1, c: c1} = &_boxed_struct; // &Box<Struct>
```

Example:

``` rust
struct A {
    x: i32,
    y: i32,
}

fn print_a(a: &A) {
    println!("x: {}, y: {}", a.x, a.y);
}

fn main() {
    let boxed_a = &Box::new(A{x: 1, y: 2});
    print_a(boxed_a); // this works

    let ref_a: &A = boxed_a; // this works
    print_a(ref_a);

    let &A{x: x1, y: y1} = boxed_a;
    /*
        this outputs:

        test.rs:17:10: 17:25 error: mismatched types:
        expected `Box<A>`,
            found `A`
        (expected box,
            found struct `A`) [E0308]
        test.rs:17     let &A{x: x1, y: y1} = boxed_a;
                            ^~~~~~~~~~~~~~~
        error: aborting due to previous error
    */
    println!("x: {}, y: {}", x1, y1);
}
```

Is it a bug or intended behaviour?

**Comment by akadark** [comment] 2016-09-30 10:14
This still reproduces in `rustc 1.14.0-nightly (86affcdf6 2016-09-28)`.

**Comment by Mark-Simulacrum** [comment] 2017-05-14 14:55
I feel like this is intentional behavior. Pattern matching on a `Box` requires the use of `box` patterns; that is, `let &box A { x: x1, y: y1 } = boxed_a;` is the intended way to make this work. Alternatively, you could do `let &A { x: x1, y: y1 } = &**boxed_a;`, which while ugly, does work on stable.

As such I'm going to close this issue; we simply don't deref in patterns (intentionally, as far as I know) though this could change with the recent match reform RFC.

**Closed by Mark-Simulacrum** 2017-05-14 14:55 UTC
Labels: A-typesystem
