### ISSUE TITLE
Instantiating a struct with default derive containing vector of generic types that do not implement default fails

### ISSUE THREAD

**Issue by stephanemagnenat** [rust-lang/rust#75489] opened 2020-08-13 15:32 UTC
I tried this code:

```rust
#[derive(Default)]
struct X<T> {
    v: Vec<T>
}
struct Y {}

fn main() {
    let x = X::<Y>::default();
}
```

I expected to see this happen: *successful compilation*, because `Vec` implements default regardless of whether the element type does.

Instead, this happened: *compilation fails with error E0599*. My understanding is that the expansion of `#[derive(Default)]` adds the constraint of Default on `T`, although that is not necessary. Indeed, looking at the expanded code:
```rust
#[automatically_derived]
#[allow(unused_qualifications)]
impl <T: ::core::default::Default> ::core::default::Default for X<T> {
    #[inline]
    fn default() -> X<T> {
        X{v: ::core::default::Default::default(),}
    }
}
```
we clearly see the added constraint. But that is wrong in general, and if we write the code by hand:
```rust
impl<T> Default for X<T> {
    fn default() -> X<T> {
        X {
            v: Vec::default()
        }
    }
}
```
compilation succeeds. [Link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1547982dabd77cc0162fdaff57a84244)

I tried to look for similar issue but did not find any, however I might have used the wrong search keywords.

### Meta

`rustc --version --verbose`:
```
rustc 1.45.2 (d3fb005a3 2020-07-31)
binary: rustc
commit-hash: d3fb005a39e62501b8b0b356166e515ae24e2e54
commit-date: 2020-07-31
host: x86_64-unknown-linux-gnu
release: 1.45.2
LLVM version: 10.0
```

**Comment by Aaron1011** [comment] 2020-08-13 15:37
This looks like a duplicate of https://github.com/rust-lang/rust/issues/26925

**Comment by jonas-schievink** [comment] 2020-08-13 15:46
Yes, another duplicate of that issue

**Closed by jonas-schievink** 2020-08-13 15:46 UTC
Labels: C-bug
