### ISSUE TITLE
Suggestion for E0627's message

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/rust#50659] opened 2018-05-11 16:02 UTC
The error message for E0627 is currently:

https://github.com/rust-lang/rust/blob/0a223d139cd26e5bfab23a478a5cad845eaab131/src/librustc_typeck/check/mod.rs#L4129

But could be something, IMHO more helpful, like:

> The containing function is not marked as `async`

**Comment by Arnavion** [comment] 2018-05-11 16:16
But the error message is correct. It's about `yield` statements outside of generator literals.

You're getting this error because you used `future-await`'s `await!` macro (which expands to code that uses `yield`) on a function that you didn't annotate with `#[async]` (which expands to code that creates a generator). The compiler can't special-case its error message just for a specific user crate macro. Native async-await syntax *would* have its own separate error message for `await` outside of `async` functions.

**Comment by estebank** [comment] 2018-05-14 17:39
@Arnavion I wouldn't be against the compiler having special case code for climbing the scope tree and suggesting marking the enclosing method as `#[async]` if the crate `futures-await` is available (and even suggest adding the crate dep if it isn't).

We shouldn't be encoding information in the compiler that depends on the community's crates, as things change over time, but I feel that the usability improvement in this case is worth it. That being said, we could try to implement something along the lines of `rustc_on_unimplemented` for `E0627` that could be generic and use messages provided by the available crates instead.

**Comment by jesskfullwood** [comment] 2018-08-20 20:08
FWIW this error confused me a lot while trying out async/await for the first time.

**Comment by nikomatsakis** [comment] 2019-02-22 16:27
Closing as duplicate of https://github.com/rust-lang/rust/issues/51751

**Closed by nikomatsakis** 2019-02-22 16:27 UTC
Labels: A-async-await, A-diagnostics, C-enhancement, T-compiler
