### ISSUE TITLE
Tracking issue for chunks_exact/_mut; slice chunks with exact size

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#47115] opened 2018-01-02 00:12 UTC
This is inspired by ndarray and generally seems to allow llvm to remove more bounds checks in the code using the iterator (because the slices will always be exactly the requested size), and doesn't require the caller to add additional checks.

A PR adding these for further discussion will come in a bit.

- Implemented in #47126 

Open questions:
- [x] Should the new iterators panic if the slice is not divisible by the `chunk_size`, or omit any leftover elements.
The latter is implemented right now and very similar to how `zip` works and @shepmaster even [argues](https://github.com/rust-lang/rust/pull/47126#issuecomment-356709770) that without this, this iterator is kind of useless and the optimization should be implemented as part of the normal chunks iterator (which seems non-trivial, [see](https://github.com/rust-lang/rust/pull/47126#issuecomment-357423490) ).
Omission of leftover elements is also how this iterator is implemented in [ndarray](https://docs.rs/ndarray/0.11.0/ndarray/struct.ArrayBase.html#method.exact_chunks) (but far more general).
~~~For the leftover elements a function could be provided, see https://github.com/rust-lang/rust/pull/51339 which implements that.~~~
A function for getting access to the remainder exists on the iterator, similar to how `slice::Iter` and `slice::IterMut` give access to the tail (note: the remainder are the odd elements that don't completely fill a chunk, it's not the tail!)
**The majority of people (who spoke up here) seem to prefer the non-panicking behaviour**

- [x] Should it be called `exact_chunks` or `chunks_exact`? The former is how it's called in `ndarray`, the latter is [potentially more discoverable](https://github.com/rust-lang/rust/issues/47115#issuecomment-403090815) in e.g. IDEs.
**It was renamed to `chunks_exact`**

**Comment by sdroege** [comment] 2018-01-02 07:47
Example can be found [here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRiBXAZwNK9Q7FkmEAHJumANQ90IFAFsADgFIAzACFlABgCCE6QVkh5meWs27tOtCx6SASgH0AmiEkdVAJklqAIpNoATgBWEPNJAHoIyS0AOk9AwMkAKkkANmDg1TSrGzsAcRc3D28/SVUADgAWAHYtcKiY2OCKmpT0zOzc1FsCSXUi9y8fVX8a2toG6LjaWir2jKycy11FDgAjSQAzFkkAd0IER2QEDhYAay4IK0lbyTwWR3QmAiY3ZU8c4PUOCuVg3ykG53AQEJ4vN4%2BT7yDh9f4/P4AoG6O73R48Yh4LDFLh4ABemGROlRoMcGKxIncuIJRNRB3QBCQVPxhKsAEofDULMS7kwuFxMMQwZgAI5gSAPcGvWIMTAsCAcj7BSRVUgxNnmYG3PkCoWOUXiiCk57S2XyxWeZWq9WalG8/mC4ViyDGiEyuUKyKSUnkrBqyUmpju81eyW%2BzAajRWLWSWV9SUMB6YRzrACeBEwXBG/npjPaVVtPNuce9sMciZYybTGazZVzCHzhZjOsdhoTSZT6czIwAwmUwwRMVhI9zUS2hYbSRWq13a6o%2B6NS2DwyPo3bblsSJIIO3K2qp0mOQ80VKmDHUbETmdLjv0YOKRr16jJLE8XhFEay4HL6cLlxHDCBCfsu97Do%2BRacqOz4blut6OIo%2B5looR67LumDwrEsRoZ2Nb/L457QS%2BV5/hAVTgYRz6vu%2BwHlkmGGxAelY4ZmeE/te/6AaRbLkYRyhcgR0Hjk6baPIowYKmqZGFhRY4OnqBoukh4lspJq4rBBFElpsZQlHIWzEKg8hwSo3z1ACakaYRJbANmQyeHpBlGZKJnqJM5nSTJxaYH0xC2bpID6YZxnwp4eEWZ5Xl9AAHn5XgOUFznwqoYVNk%2BmneZIwDEJgqa2VAvmpE4zgWuo242akhTFVCpUQJsqQDFVHw1TFqRaNxXqLF0UZpVZGVZTltn9blfLuH83WWdBpIuWZ/hlENHmeVN8JubNi7zeNEVLvBIV4YN2WpgtMlLd8yUArZ9QbbxNT4U%2BfE3Tod1rjoaybDs%2ByHPqUVMMgYLETeMYBhC7yfPCvx4bSIJfkDUJpIBPjfGDSIA3eQ6UtwLIQ7cPqgWj1Ksk%2B9Y4hj7KQc2cnCRKjzfmanpKiqaptYdQn6s6NHUx6FpWgz4X2rqFNs26NMctE2Oo/6VOCxzoYow%2BqUQSW2HVt2dZYnmqQFpdkVbdOzFzjmqsNurcuyXzIm0UxStzgu/gDqjPPauTk5ljrlu9mUouy%2BNMabr5cHTohYLTihAmSJgX0/ccv43oDrzi2SONslRH5h99v1RxxsIC7HW0rjxtx8VB0E%2B9uzkB/BKGh%2BHafsdcnxofRiuzuDKp5zJScQCnEd/RnQEfLDsLa3R3yYYxM64UiLet6iBchybjos2bYlC6ph0UczCk0UvHMr17PXQVpsX2QFjnBaZKWazJ1mH/FTmict5%2BF5fGW%2BTpcXHwld/fKF7kX%2Bl0XX%2B/W%2B20ToPyeptay%2B08oQAKg4FwJUyrtEqvA2q7QGrIJauqYWHQlir16n0Iae0BojTBr/Qix11AzUIQdUhk0kL3zOnNfauDaFghct/Va/h1qPwouQ06HCYjMM5Pdae11oyiPUh8U66gsCYgAG6YAgL4TA6wODAA1ACKwL0DCcB%2BpIbAVcezpzUD2MAogmBqgACpuFMWeVQ2BSZPlkcDNINj4bqAseDGMf0yQsiJjSMR90rBvU7tXP8xiPF2IgE4mG8IPET28XjPxEZJAAFo1D2P0anQx7FwnpIcRBIShoEkskkOKMojML4lmyvIWysjlJQmVMUgkh0SxmlqfUlJkhqmHUyT9bJf58kUWiX3WR9EzSeL3pIJplJpmYyEQEp6eAlAMGMTYyxeSewMB6FIYuvSCD9MuKssx6y7GDLuG9ZAWzKy1zSAKBgWwORpNOXsg5XAjnmMkBE%2BxM9JkvPTmczy0S7lbFiLIuZFFpluGBWxC4Pj/GTMerdcRD1kVWCWYoFZ841mfLyQASQzMQF4W5dkGKMVi45OLTk/IggQVMigpD4tMLZPurjYl4WNncSR8IHjTnZU%2BN6lYoq92hAPYFjy8kAHlFAEDwD0YxLKzFuLifhKl/FJl4C2NITA9zQX1OMVqnV0yAUyQAHLbJDndUODABTGr/tuLYPA1RcBYOgRUi5oV1K4BiwgjgXgQGhdM%2B2MkPW2WdegQRqIADKhkFEOoIFPTlyKRGBNup4KRPKh7CPObsPGjgEAPGFbc7VDzUl5IgOjGkkgpUyrlfOCt6E7GKjVRNWMGVdhlA9fU6IAao5wobdwu4EAWBqmjSYId3EYyIoeqm9NLBeUaP5bsNAZwgJitLac%2Bttq7jQqFpO1FM7uVzszd7XYLBGQ3LhsCtULAknitOdW2VLBjGRuLXIRlZhVUDq1v614Qp9zyOIFsLZew3X%2BBYAxADQHUAHDYABDgDB/XFphecPtQbUQaoMEwIUIxsAdqQ3UoWnI%2Bw1B7N6SDwGt3QRDWUPu8J2U0OfGaysFrrpWptdS8BGU5ToFsvIF4JxMNCh/JgZA5xMDoF9egdAiHDW9rxk2r9MlR0KK4BweQoG8nICUHIeQDwZMgoI9vaQamVKz0IkxqQfg8mduXmZ/Oojd4tvQ5q7jqTBN9DKe6pDRqOObW3fh5lINvj0cUxRCzdmhFscs82vzdwSxnobDRz4Hr4Q8CwwQTC3GQsRdRNRxcfcUvfG45hbLkyKLKaHYyBN0Ep0UVq4mlNEEuXfAzcxhdEE3rMB4Ppu99iH21p7C%2B%2B5b6Mwfu%2BTFwiGGbNS31T268fbKOMfNQi1j2r2MTc8iWNL2G8M6sMyGTpc3YV4wjXcCrBX8Opd/Rl2IKUVtZvs4E/dOh0WYpMRSr5khfACHWLKbALrxOMsJUQXyJKslkvex8z7vn85psPfOh72xT1hzBOsb65wL2iuLb1qt0rH3ys%2BKy74yq8kw%2BfFN/Der5wGpBT5jbprlststWt6LoW4sZQgHGp1LrQM091V6xMYI/XTYO3zwNp3bh5f8HGiXkgKthuq/MpFT3GuvfeScjJVdI0siB0S0HW4/k5PJVD0n/FntRDV8bjXkgABiEh0C65B9sA3pKjeQ%2BtzPZ7zXpGCjwPIxRyjVHqPulojEHBdGG7/AAWVhOrz51izGm8fsMwniq4ZsqRk%2BSFzJ4Uosa8Equkd2JwYILkyJKf%2B5wmJ83bP9aceR8uDH0v85of08KZAI1nn/AVMflUplZR9u00tFMuTLIWkZTaQPjpXTTA9Nd9HgeZPUQV7hqM4ewYJktuz7MvdKvFnLLj59x3xKXfg/Yk3w/SeYy0vpZId9gWXFp8X9XjRjnp5w5a0etriOBUo8x30NdJ5PrPHAbBVJgSQdPF/FVcbRTCnPbKnUjI7FDPGRbVEcLe7KLVA9nPoAgJQXjUwOQbKDFb6BRPuS9fDNUMg5/TQH%2BNnb9BATAJgdANUV4PABgXnXAsSAXH1F4EvfTZDVDWXKXSQVgzFOguXGNCABgpgxXerR7MBTlD/dQVrdCdrVEN6XNfNM9G5QAstetNUfrJ9OtE7RtRbeLUNSnQjbtbzUfZpBjIdEdSQlgCdZXBQ2HWdBHE9KZAQbQ3QjdFApffzHVXdVw9Sd/Dw49RdSQBLf/Gna9W9ddYAmtIwvsVPcAyA9xejGAkOEsH9dLf9QUKDEDWycDVAcjaDB4YAODBDJAwQhjKba7HDXbAzPVEjPiUjMowoijQIqjALJLSvNxUrJzO4dApnVba1VnCLEsVzMoPjAgATbbDLE4ETMTCTJg6TWo%2BTLA6CeXEzbMTTbTYwPTEXCSYzdTcFCKCzfY05E40zMrBrDlTyDDVzQ7RorvMXWwyY%2B43ovbB/DIoY2LW4UYzaZnCY7Y58EsTg/A%2BQQgzAYg4QWIj1SgkVKvGg3wNDCKXI6Q5gkQpgNgjgpQWIbgoXMETibjDEzbDnRwa9KrWybEok71EkvgxYik4NPoxcUQ2XKNJwqrCLOQ58fkqdSdJQlQvlDrXYLrVdbHRI3HZI59V9EAd9K/dVTVW43sD4%2BbAI%2BnMLRnOrcY9bcQrbRosofgwfR5DU47FkLBTYkpVIG0uw8Q87FEvnNfdQRYkrdye7XfBZdSS3d3Slexb7DYP7AHB3AlPXZ3XyBvLgC/K3AM41b3UUtQ7NaIlHFMdHRE6UoA2U/HecMAiA6gknT9EOOAlowjWbGwzUkpHopbZjDAlncEyEvA2YggkAIg5gBEqggAigmGf42gqYjKTg8sOUWyTg5SWXLExgnE0Qgkrgxk31UkzOIctpQ7Ssy0gkVk3Ldk/wbE2XCrGcljRHIU57P07FT7PZbXAkY/fXKM%2BfRvWPOM1vTQc3CIU8j7PJO3AUMMwUCMsHPpdOWM/0p8u6UQFSBgMQYIUQUgG9UQLQKC1AMQewbgAAgQIQSzNNWgKCggMQOC7iUgc4EAYIOITwcYIiwICoLQVQQITwWgYINIRgMQKoKCmCuC0gBC0QKCrgEALQUgbC2C0C0gOAWAJANAJQNgwUcgSgUSxQcS4gEAFgPAYABAAgBgVMUgLYNgglLi2qHCqC9YB4LDVMMQTC0gUSkwM9CVOdIy/i0gLAPjNgWUXS2yvAbKH6P3TMJysOETWEEQUQEygtbVJy%2B8GE/isC1gdgZCxgPAdYLiyAFSVAEA2wMQFJDo6VFJWUeRTFXwVQTi1C4QOgMCiC5ipy9izgHgZAaIxS5S1S7cXAQgLcSRegSQHsQyGS2UF%2BDCjkJCngLC3SvCgiqoQIWIGoS0QarQIINILQGoaoVUcC0QJi6CkqsQTi7i3ivqwq0QTwYqmy9i3q0KlSADXEHoEAKoIAA%3D%3D%3D)

The relevant part with differences in the assembly is

before:
```assembly
.LBB4_24:
  cmp r11, 4
  mov eax, 4
  cmovb rax, r11
  test rbx, rbx
  je .LBB4_18
  cmp rbx, 4
  mov edx, 4
  cmovb rdx, rbx
  test r13, r13
  je .LBB4_18
  mov qword ptr [rbp - 96], rax
  mov qword ptr [rbp - 48], rsi
  mov qword ptr [rbp - 56], r9
  cmp r11, 3
  jbe .LBB4_27
  mov qword ptr [rbp - 96], rdx
  mov qword ptr [rbp - 48], rsi
  mov qword ptr [rbp - 56], r9
  cmp rbx, 3
  jbe .LBB4_29
  cmp rax, 1
  je .LBB4_39
  lea r10, [r13 + rax]
  sub r11, rax
  lea r12, [r15 + rdx]
  sub rbx, rdx
  cmp rax, 3
  jb .LBB4_41
  je .LBB4_42
  movzx r14d, byte ptr [r13]
  movzx r8d, byte ptr [r13 + 1]
  movzx eax, byte ptr [r13 + 2]
  imul r13d, eax, 19595
  imul edi, r8d, 38470
  imul eax, r14d, 7471
  add eax, edi
  add eax, r13d
  shr eax, 16
  mov byte ptr [r15], al
  cmp rdx, 1
  je .LBB4_44
  mov byte ptr [r15 + 1], al
  cmp rdx, 3
  jb .LBB4_45
  mov byte ptr [r15 + 2], al
  je .LBB4_46
  mov byte ptr [r15 + 3], 0
  test r11, r11
  mov r15, r12
  mov r13, r10
  jne .LBB4_24
```

after:
```assembly
.LBB5_18:
  test rsi, rsi
  je .LBB5_20
  add rdx, -4
  movzx r10d, byte ptr [rsi]
  movzx eax, byte ptr [rsi + 1]
  movzx ebx, byte ptr [rsi + 2]
  lea rsi, [rsi + 4]
  imul r13d, ebx, 19595
  imul eax, eax, 38470
  imul ebx, r10d, 7471
  add ebx, eax
  add ebx, r13d
  shr ebx, 16
  mov byte ptr [rcx], bl
  mov byte ptr [rcx + 1], bl
  mov byte ptr [rcx + 2], bl
  mov byte ptr [rcx + 3], 0
  lea rcx, [rcx + 4]
  cmp rdx, 4
  jae .LBB5_18
```

**Comment by bluss** [comment] 2018-01-02 21:07
I don't want to derail your discussion too much. Const generics and value-level chunks both have their uses. I'm reminded of this existing implementation of the "const" kind of chunking, in this case in an iterator that actually allows access to the uneven tail at the end: [BlockedIter](https://docs.rs/odds/0.3.1/odds/slice/blocked/struct.BlockedIter.html). Note that a `Block<Item=T>` is an array of T.

**Comment by sdroege** [comment] 2018-01-02 21:38
Interesting, thanks for mentioning that. For my use case that would probably work more or less the same way, but it's slightly different indeed.

**Comment by bluss** [comment] 2018-01-02 21:51
BlockedIter was developed while looking at exactly the hand off between the blocks and the elementwise tail; the idea was to avoid some of the loss that otherwise shows up in code that converts between slices and slice iterators. In this case it's the same pointer being bumped through the whole iteration.

**Comment by bluss** [comment] 2018-01-02 22:08
The chunks iterators are a good canditate for zip specialization (TrustedRandomAccess trait)

**Comment by sdroege** [comment] 2018-01-02 22:16
True. I'll add that in a bit, as a separate PR for the existing chunked iterators and as a separate commit for the new ones.

**Comment by sdroege** [comment] 2018-01-02 23:27
I forgot to add some benchmark results earlier. This is with the code from https://github.com/rust-lang/rust/issues/47115#issuecomment-354715511 and running on a 1920*1080*4 byte slice. Basically 2.46x as fast.

```
running 2 tests
test tests::bench_with_chunks       ... bench:   7,702,902 ns/iter (+/- 177,747)
test tests::bench_with_exact_chunks ... bench:   3,132,468 ns/iter (+/- 202,032)
```

**Comment by shepmaster** [comment] 2018-01-13 15:05
> The latter is implemented right now and very similar to how zip works and @shepmaster even argues that without this, this iterator is kind of useless and the optimization should be implemented as part of the normal chunks iterator

Thinking of this from another direction, if either Rust or LLVM were to *magically* figure out how to perform this optimization in the case of `chunks` but `chunks_exact` didn't perform the length truncation, we'd then have two functions in the standard library that did the exact same thing. This would be annoying as a consumer.

**Comment by sdroege** [comment] 2018-01-15 15:45
This shouldn't have been closed by the merge, can someone reopen it? I don't have the permissions for that it seems

**Comment by SimonSapin** [comment] 2018-03-30 14:08
The libs team discussed this and the consensus was to stabilize this with the methods panicking before returning an iterator if the slice’s length is not a multiple of the requested chunk size. This is consistent with e.g. `[T]::copy_from_slice` panicking on unequal sizes. Callers can take a sub-slice before calling these methods if they wish to ignore extra items.

@rfcbot fcp merge

**Comment by sdroege** [comment] 2018-03-30 15:32
I can provide a PR for panicking if the size does not match, as long as everybody agrees that this is the desired behaviour. @shepmaster did not agree before, and to me it also seems suboptimal but it does not matter for any of my use-cases and code can easily work either way.

**Comment by shepmaster** [comment] 2018-03-30 15:46
Yup, I still disagree with that decision. I literally used this function in the last week for the purposes of SIMD work (chunking of 16 bytes). Having to perform the modulo operation multiple times feels counterproductive.

I'll point back at my [previous comment](https://github.com/rust-lang/rust/issues/47115#issuecomment-357441862) that this decision means that this function is basically only created for the purposes of codegen and will become useless if/when `chunks` produces the same code.

**Comment by SimonSapin** [comment] 2018-03-30 19:55
Alright, let’s hold off for now:

@rfcbot concern panicking 

@shepmaster Is silently ignoring extra element the desired behavior? Could you explain why that is, and why there’s no (or it’s worth the) risk of bugs due to failure to process those extra elements?

Does it sound like a good idea to return, instead of just an iterator, a tuple of an iterator and a slice for those extra elements?

**Comment by shepmaster** [comment] 2018-03-30 20:59
> Is silently ignoring extra element the desired behavior? Could you explain why that is, and why there’s no (or it’s worth the) risk of bugs due to failure to process those extra elements?

It's desired and non-buggy, but only because I am already handling those extra elements around the code I would been using `exact_chunks` in.

> a tuple of an iterator and a slice for those extra elements?

For my particular example, that would have been close to ideal. I have a byte string of arbitrary length and I need to chunk it into 16-byte slices and then specially handle the leftovers at the end. However, I also need to track the total number of bytes of the chunked amount to report back the full offset at the end.

In this SIMD case, even using slices at all generated unneeded assembly (tracking the length of each 16-element slice added ~2 operations and took a register in a hot loop, for example), so I don't know if `exact_chunks` would be ultimately usable in my case anyway. Thus I don't know if my opinion is extremely valid. 

Although the tuple idea seems nice on the surface, it feels awkward to use because you have to unpack the iterator:

```rust
let (chunks, _) = a.exact_chunks(16);
for c in chunks {}
// or
for c in a.exact_chunks(16).0 {}
```

And if you want the current panic behavior, it's not better:

```rust
let (chunks, extra) = a.exact_chunks(16);
assert!(extra.is_empty(), "Have extra data");
for c in chunks {}
```

So maybe there's no ergonomic solution other than panicking...?

The only other thing that comes to mind is an iterator with an inherent method:

```rust
// Don't care about extra
for c in a.exact_chunks(16) {}

// Shouldn't have extra
let mut chunks = a.exact_chunks(16); 
assert!(chunks.extra().is_empty(), "Had extra things");
for c in &mut chunks {}

// Handle extra
let mut chunks = a.exact_chunks(16); 
for c in &mut chunks {}
for b in chunks.extra() {}
```

**Comment by SimonSapin** [comment] 2018-04-01 13:11
> Having to perform the modulo operation multiple times feels counterproductive.

Why multiple times, though?

Extra items at the end of the slice:

```rust
// Unsigned integer division rounds toward zero / truncates
let (chunkable, extra) = slice.split_at(slice.len() / chunk_size * chunk_size)
```

Extra items at the start of the slice:

```rust
let (extra, chunkable) = slice.split_at(slice.len() % chunk_size)
```

Either way, continue with something like:

```rust
for item in extra {
    process_one(item)
}
for chunk in chunkable.exact_chunks(chunk_size) {
    process_many(chunk)
}
```

> In this SIMD case, even using slices at all generated unneeded assembly

Are you saying we should wait for const generics to be stable and change these iterators to yield fixed-size arrays rather than slices? And not stabilize anything in the meantime?

**Comment by sdroege** [comment] 2018-04-01 14:09
> Are you saying we should wait for const generics to be stable and change these iterators to yield fixed-size arrays rather than slices? And not stabilize anything in the meantime?

Const generics don't cover all my use-cases. The chunk size is not always known at compile-time. IMHO we need another function for this later with const generics.


The version that returns the remaining items as a slice together with the iterator seems fine to me.

**Comment by shepmaster** [comment] 2018-04-01 15:00
> Why multiple times, though?

Because `chunks_exact` [will perform the same modulo operation](https://github.com/rust-lang/rust/blob/39264539448e7ec5e98067859db71685393a4464/src/libcore/slice/mod.rs#L366-L371).

> const generics to be stable and change these iterators to yield fixed-size arrays

I can't have said that because I didn't even realize that might be a possibility. 😜 That certainly sounds ideal *for my case* though. I might even give it a shot with the non-generic form...

> not stabilize anything in the meantime

I don't want to be The Bad Guy that prevents things from stabilization. If there are clear wins for the function as it is today, it seems reasonable. I think I'd lean towards the inherent method on the iterator to retrieve the trailing extra bits of all the previous alternatives.

**Comment by sdroege** [comment] 2018-04-01 16:19
> I think I'd lean towards the inherent method on the iterator to retrieve the trailing extra bits of all the previous alternatives.

From what I understood the concern with the current behaviour is discoverability. That it's not necessarily obvious that the remaining items are simply ignored (which is btw consistent with how zip works for example, so I don't really see the problem here). An inherent method on the iterator is also not very discoverable, at least for myself. I usually don't look at the inherent methods of a specific iterator, assuming there are none.

**Comment by shepmaster** [comment] 2018-04-01 17:18
> the current behaviour is discoverability

I suppose panicking is very discoverable and hard to miss, but you still need to look at the docs (or hopefully the error message!) to understand why the panic occurred.

> I usually don't look at the inherent methods of a specific iterator, assuming there are none

There's goodies to be found in those iterators, especially when looking for performance wins. [`Chars::as_str`](https://doc.rust-lang.org/std/str/struct.Chars.html) comes to mind.

This is probably something that will get better over time because things will start returning `impl Trait` when they have nothing extra. Having a concrete type will be a sign that something interesting is present.

**Comment by bluss** [comment] 2018-04-01 19:40
I propose the chunked iters are rewritten with raw pointers, and that they provide an iterator to the rest / the tail using a method that returns a slice iterator. That should be the best possible we can do for tight code. Overly long explanation below.

No reason to implement that now, but I want to say I don't want to lock us in on returning a tail slice or a pair of iterator and a slice.

----


Returning the remainder as a slice is not entirely zero cost, in all situations. That's the kind of situation I was exploring with [BlockedIter @ crate odds](https://docs.rs/odds/0.3.1/odds/slice/blocked/struct.BlockedIter.html).

We can iterate in chunks, then creating a slice of the remaining tail, iterate the tail.

If we write that straightforwardly, the compiler cannot eliminate all the iter-to-slice-to-iter conversions and produces overly complicated code. It is not zero cost, because we can write better code with raw pointers.

The `BlockedIter` does that better, because you can iterate blocks, and then you get a slice iterator to the remaining tail (see method `BlockedIter::tail`). The difference is that with the blocked iterator + tail, we have the same pointer being bumped through both the block loop and on through the tail loop. That's all much better (as of the development of BlockedIter, which was long before llvm 6 in Rust.)

BlockedIter is formulated to be something like the const generics version, but the same applies both to constant and dynamic size blocks.

**Comment by shepmaster** [comment] 2018-04-02 00:40
@bluss is it your belief that if we did that rewrite then `chunks` would generate the nice optimized assembly in the [earlier comment](https://github.com/rust-lang/rust/issues/47115#issuecomment-354715511)? 

I would believe it as that's basically what I did for my SIMD case. If so, then I'd rather see `chunks` rewritten.

**Comment by sdroege** [comment] 2018-04-03 06:54
If that's the consensus, I can spend some time on that. However `chunks` has the disadvantage that it does not guarantee you that each chunk is of equal size and it has to be checked manually, either beforehand or on every chunk.

**Comment by Kerollmops** [comment] 2018-05-28 13:51
Just to make it more clear for users the `exact_chunks_mut` method must follow the `exact_chunks` one, in term of position in the documentation/declaration.

Like `split` and `split_mut`, `rsplit` and `rsplit_mut` and others...

**Comment by sdroege** [comment] 2018-05-30 06:05
> Returning the remainder as a slice is not entirely zero cost, in all situations.

@bluss Can you give an example? Currently all 4 chunks iterators are already storing the remainder as a slice inside their struct, so simply adding a way to return that should not make any difference. As such I assume you meant that with the current implementation this is already problematic in some cases?

**Comment by Kerollmops** [comment] 2018-05-31 19:09
I think that a method on the iterator adapter (i.e. `ExactChunks`) returning the tail/remaining of the slice after having been chunked is the way that could reconcile every one. Implementation can be benchmarked: raw pointers or two slices.

I prefer the _two slices_ option, but it's true that the first one can be implemented with only 3 pointer: one for the **start of the next chunk**, one for the **start of the remaining part** that is also the one to detect the **end of the chunks part** and the last one for the **end of the remaining part**.

```rust
struct ExactChunks<T> {
    chunk_size: usize,
    chunk_start: *const T,
    rem_start: *const T,
    rem_end: *const T,
}
```

An example usage of the `remaining` method:
```rust
let s = &[1, 2, 3, 4, 5];

let mut chunks = s.exact_chunks(2);

// the `remaining` method gives the part of the slice
// that will not be iterated over by the `ExactChunks` iterator.
let rem = chunks.remaining();
assert_eq!(rem, &[5]);

assert_eq!(chunks.next(), Some(&[1, 2]));
assert_eq!(chunks.next(), Some(&[3, 4]));
assert_eq!(chunks.next(), None);
```

**Comment by sdroege** [comment] 2018-05-31 20:32
Above a function for getting the current tail at any point was discussed, you have one for the remainder. Not sure which one would be more useful, but the first is more generic at least

**Comment by sdroege** [comment] 2018-06-01 10:55
Oh and the reason why I mentioned raw pointers here is that if you want to implement a function for getting the actual tail, you need to store both the tail used for iteration (potentially excluding the last few elements) and the real tail (including all remaining elements) and update both in sync. By using pointers you only need to store current position and the two ends in one way or another and only have to update the current position.

**Comment by Kerollmops** [comment] 2018-06-01 13:18
One thing to notice is that having the current tail at any point can can be achieved by chaining the remaining as I ear it (the part that will never be reached by the `ExactChunks` iterator) with a `FlatMap` of the iterator, [like so](https://play.rust-lang.org/?gist=ea275880e9e6f26d221126b6b7fe738d&version=nightly&mode=debug).

> Not sure which one would be more useful, but the first is more generic at least

What do you mean by "more generic" ?

You are right, the 3 pointers way can be a gain in performance.

**Comment by sdroege** [comment] 2018-06-01 13:31
> What do you mean by "more generic" ?

You proposed to add a function to get the final remainder (e.g. `exact_chunks(4)` on 6 elements gives you always the last two as remainder), while what was mentioned before was a function to get the tail at any point in time (e.g. `exact_chunks(4)` on 6 elements would first give you all as tail, then after the first `next()` give you the last 2 elements).

The latter seems to be usable in more situations and gives you the former at the end of the iteration anyway.

**Comment by Kerollmops** [comment] 2018-06-01 13:36
I agree, if someone needs the remaining part (the one that will never be iterated over) the only action to do is to reach the end of the `ExactChunks` iterator (i.e. by using `Iterator::last`) and call the `remaining` method.

I prefer the behavior you are talking about ! It's more generic like you said !

What is missing for that to be implemented ?

**Comment by sdroege** [comment] 2018-06-01 13:39
> What is missing for that to be implemented ?

Time, I've started locally but got sidetracked with other stuff that needed more urgent attention. I'll try finishing it (and moving to raw pointers for the above mentioned reasons) this weekend.

**Comment by sdroege** [comment] 2018-06-04 07:51
See https://github.com/rust-lang/rust/pull/51339

**Comment by Kerollmops** [comment] 2018-06-12 12:08
Why `ExactChunksMut` does not have a `remainder` method that gives the same thing that `into_remainder` gives but immutably ? It could be really useful, the user must drop the `&[T]` to be able to continue iterating. Adding it to the `IterMut` method could be interesting.

What do you think about that ? Am I wrong with borrowing rules here ?

**Comment by sdroege** [comment] 2018-06-12 12:15
> Why ExactChunksMut does not have a remainder method that gives the same thing that into_remainder gives but immutably ?

`next()` return value has the lifetime of the underlying slice, so you need to make it impossible to call `next()` while the remainder is borrowed (no matter if mutable or immutable), e.g. by borrowing with the lifetime of the iterator instead of the underlying slice. That however is inconsistent with how any of the other slice iterator functions work.

**Comment by cloudhan** [comment] 2018-07-06 16:58
maybe rename `exact_chunks` to `chunks_exact`, because there is another fn `reserve_exact`. This will make the API more accessible from IDE or editor, since you can just type `chunks` to discover `chunks_exact`, but with the original name, you can only discover it with docs

**Comment by kornelski** [comment] 2018-07-29 01:55
Can panicking be later changed to non-panicking? Does that count as a breaking change?

**Comment by kornelski** [comment] 2018-07-29 02:08
For my use cases panicking is fine. I do things like `.chunks(2)` and then unconditionally use `c[0],c[1]`, so my code would panic anyway.

I strongly dislike `.zip()`'s silent truncation. It has kept some bugs hidden in my code. Potential undetected off-by-one truncations sound pretty bad too.

For efficient iteration and zipping it's already best practice to explicitly take slices in the way that LLVM can "see" them. So for working with buffers with inexact length it'd make sense to explicitly slice them (otherwise the code wouldn't be obvious how exact chunks work on inexact buffers). I'm expecting that chunks' own modulo would be optimized out if it was redundant.

**Comment by sdroege** [comment] 2018-07-29 17:06
Currently there is no panicking and it behaves like `zip` and others and silently "ignores" anything that does not fit, but you can get the remainder via API on the iterator type.

I see your argument for not silently ignoring such mismatches but it's already common in other iterator functions and also in other languages, and from what I know it didn't cause many problems in practice after all.

> For efficient iteration and zipping it's already best practice to explicitly take slices in the way that LLVM can "see" them. So for working with buffers with inexact length it'd make sense to explicitly slice them (otherwise the code wouldn't be obvious how exact chunks work on inexact buffers). I'm expecting that chunks' own modulo would be optimized out if it was redundant.

That's unfortunately not the case currently, llvm can't optimize that away for `chunks` but can for `exact_chunk` (but even apart from optimization, I think `exact_chunks` has a use-case due to its different behaviour which at least for me is more often the required behaviour).

**Comment by alexcrichton** [comment] 2018-09-24 17:15
I think I've changed minds now and would be ok if these iterators don't panic. If we choose to not panic I think it makes sense to have an inherent method on the iterator to get the rest of the slice out, and that would do the necessary modulo computation if necessary.

For naming I might advocate going to `chunks_exact` if only to avoid clashing with `ndarray`, trying to head off those regressions we'd get from stabilizing!

**Comment by sdroege** [comment] 2018-09-24 19:49
Let's go for that then: https://github.com/rust-lang/rust/pull/54537

**Comment by DutchGhost** [comment] 2018-09-24 22:05
Recently I found myself wanting to iterate over slice in chunks, but starting from the end of the slice, towards the beginning.

for example, I wanted to Iterate ```[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]``` in chunks of 4, starting at the end. I'd like to get `[8, 9, 10, 11]`, `[4, 5, 6, 7]`, and as the remainder, `[1, 2, 3]`.

Currently ```[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].chunks_exact(4).rev()``` gives `[5, 6, 7, 8]`, `[1, 2, 3, 4]`, and its remainder is `[9, 10, 11]`.

So in the current way, I'd have to figure out what the remainder would be, split on an index to get ```[1, 2, 3]```, and pass in ```[4, 5, 6, 7, 8, 9, 10, 11]``` to .chunks_exact(4).

How would rchunks_exact() workout, where the Iterator starts at the end of the slice, going in chunks towards the beginning, and the remainder would give a slice from the beginning (if there is a remainder).

**Comment by sdroege** [comment] 2018-09-25 05:53
@DutchGhost That (`rchunks_exact`) wouldn't be very difficult to implement, but IMHO should come together with a `rchunks`, `rchunks_mut`, `rchunks_exact_mut` for consistency.

I'll take a look but let's handle that as a separate issue to not block stabilization of `chunks_exact` by concerns for that new API :)

**Comment by sdroege** [comment] 2018-09-26 07:06
With that done, how do we go from here to stabilization?

**Comment by alexcrichton** [comment] 2018-09-26 14:56
The next step would be FCP, but this issue is [already in FCP](https://github.com/rust-lang/rust/issues/47115#issuecomment-377531920). It has a blocking concern that would need to be resolved by @SimonSapin to make progress (assuming there's consensus about what to do with panicking)

**Comment by sdroege** [comment] 2018-10-05 19:28
> @shepmaster does this resolve your original concern?

I hope I didn't completely misunderstood @shepmaster but from what I understood he argued that with panicking this function would be useless and would not give any semantic advantage/difference over the existing chunks apart from codegen

**Comment by shepmaster** [comment] 2018-10-06 02:17
> @shepmaster does this resolve your [original concern](https://github.com/rust-lang/rust/issues/47115#issuecomment-377553674)?

I am happy with the current external behavior of the function.

**Comment by alexcrichton** [comment] 2018-10-06 17:29
Ok great! @SimonSapin can you `@rfcbot resolve panicking` ?

**Comment by sdroege** [comment] 2018-10-17 19:32
Are there any new concerns? @SimonSapin

**Comment by SimonSapin** [comment] 2018-10-17 19:39
@rfcbot resolve panicking

**Comment by SimonSapin** [comment] 2018-10-17 19:39
Ping checkbox @aturon, @sfackler, or @withoutboats

**Comment by alexcrichton** [comment] 2018-10-18 02:00
Ok! It's been quite awhile here so I think it's ok to shirt circuit the FCP slightly, @sdroege want to send the stabilization PR?

**Comment by SimonSapin** [comment] 2018-10-18 06:16
Should we consider https://github.com/rust-lang/rust/pull/54580 to be "trivially enough" similar to this to stabilize at the same time?

**Comment by sdroege** [comment] 2018-10-18 07:17
> @sdroege want to send the stabilization PR?

Yeah, preparing a PR now. I'll add `rchunks` in a separate commit into the same PR if it's agreed that it should be part of that

**Comment by sdroege** [comment] 2018-10-18 08:15
There's now https://github.com/rust-lang/rust/pull/55178 for the stabilization of this here (but not `rchunks`).

**Closed** 2018-10-19 12:14 UTC
Labels: B-unstable, C-tracking-issue, T-libs, disposition-merge, final-comment-period
