### ISSUE TITLE
On permission managed windows machines (eg. win7) rust generated binaries require administrator privileges to run

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#16455] opened 2014-08-12 18:53 UTC
From http://discuss.rust-lang.org/t/prioritizing-windows-issues/319/2?u=brson

It appears that on permission managed windows machines (eg. win7) rust generated binaries require administrator privileges to run, even for trivial case applications like println!("Hello World"); these permissions must be accepted ("Run this as administrator") every time the application is launched.

I have no idea how this is typically managed in win programming, but having to accept "run this as administrator" every time you run cargo test or launch a binary is really tedious.

**Comment by retep998** [comment] 2015-02-11 01:15
This issue would most likely be solved once we provide proper support for manifests. https://github.com/rust-lang/rfcs/issues/721

**Comment by vadimcn** [comment] 2015-02-20 02:20
@V01D-eXe, Is this a file permissions problem, i.e. only the file creator has rights to execute it?
If so, this is not a Rust issue and I would recommend closing this.

**Comment by V01D-eXe** [comment] 2015-02-22 04:41
@vadimcn 
retep998 is right, and manifests should be able to fix this problems. [I am not sure but i think `RequestedExecutionLevel` is the fix.] 
Generally it is a file permissions problem.

**Comment by vadimcn** [comment] 2015-02-22 08:20
@V01D-eXe, Would you mind describing your setup, so I could try to reproduce the problem locally?  Have you tried adding a manifest to your executable?

**Comment by V01D-eXe** [comment] 2015-02-22 10:33
@vadimcn 
I tried to create a user account with less privileges [standard user account] to provide a test case but my OS is giving some errors in loading it up.
So, I just used my admin user account , and then  -
    
First -
   
`a.rs`
```
fn main() {
  print!("Hello World");
}
```
  
`a.exe.manifest`

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
   <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
      <security>
         <requestedPrivileges>
            <requestedExecutionLevel
               level="requireAdministrator"
               uiAccess="False"/>
         </requestedPrivileges>
      </security>
   </trustInfo>
</assembly>
```
  
Second - Compiled using `rustc a.rs` and got a.exe .

Third - Used mt.exe from Windows SDK to embed the manifest manually into the exe.
```
mt.exe  -manifest "a.exe.manifest" -outputresource:"a.exe";1
```

Fourth - From a non-elevated cmd, start a.exe . => a.exe automatically starts up in elevated cmd.
[Remember I am not on any permission managed windows machine, and I have admin access].

Fifth - Change `level="requireAdministrator"` to `level="asInvoker"` and redo third and fourth.
=> It starts up as a non-admin process.

NOTE : Someone needs to check this in a permission managed machine, if it works or not.

**Comment by bombless** [comment] 2015-02-22 10:47
So I notice that we don't even have a tracking issue for this.
https://github.com/rust-lang/rust/issues/11207
https://github.com/rust-lang/rust/issues/21352

See this comment https://github.com/rust-lang/rust/issues/11207#issuecomment-31334910

**Comment by vadimcn** [comment] 2015-02-22 11:03
@V01D-eXe: I assumed that you are experiencing this problem as well because of your comment [here](https://github.com/rust-lang/rust/issues/16455#issuecomment-52752808).
I thought the issue was that **manifest-less** rust executables do not run without elevation, but it seems nobody can repro this...

**Comment by bombless** [comment] 2015-02-22 11:07
We need to add proper manifest for Windows any way.

I am thinking about would it be possible that we take manifest as a crate in some way.
So we can add manifest infomation in `Cargo.toml`, and cargo can link the resource for us.

**Comment by bombless** [comment] 2015-02-22 11:09
cc @vadimcn

**Comment by vadimcn** [comment] 2015-02-22 11:16
@bombless: perhaps so, but it is not clear at all that *this* particular issue is caused by the absent manifest.

**Comment by V01D-eXe** [comment] 2015-02-22 12:30
@vadimcn 
I didn't have this problem with rust.It was just that a few years back, i had got the problem with mingw.

**Comment by V01D-eXe** [comment] 2015-02-23 08:52
@vadimcn Since no one is having this problem, i think this should be either closed down, or a reproduce tag should be added.

**Comment by steveklabnik** [comment] 2016-06-06 20:47
Triage: not aware of any specific movement on this front.

**Comment by steveklabnik** [comment] 2018-09-24 17:30
Triage: not aware of any changes. Given that this is solved by proper manifests, and nobody has commented since 2015, i'm going to close this as a duplicate of https://github.com/rust-lang/rfcs/issues/721

**Closed by steveklabnik** 2018-09-24 17:30 UTC
Labels: C-bug, O-windows
