### ISSUE TITLE
function pointers as match patterns have optimization-dependent behavior

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#70861] opened 2020-04-06 22:09 UTC
I tried this code, supplied by @eddyb [play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a1a4aafc915c188318a377d0a20e36d3):
 
```rust
#![feature(test)]
use std::hint::black_box;

fn foo() {}
const FOO: fn() = foo;

fn bar() {}
const BAR: fn() = bar;

#[inline(never)]
fn print(s: &str) {
    println!("{}", s);
}

fn main() {
    match black_box(FOO) {
        FOO => print("FOO"),
        BAR => print("BAR"),
        _ => unreachable!(),
    }
    
    match black_box(FOO) {
        BAR => print("BAR"),
        FOO => print("FOO"),
        _ => unreachable!(),
    }
    
    match black_box(BAR) {
        FOO => print("FOO"),
        BAR => print("BAR"),
        _ => unreachable!(),
    }
    
    match black_box(BAR) {
        BAR => print("BAR"),
        FOO => print("FOO"),
        _ => unreachable!(),
    }
}
```

I expected to see this happen: print out of
```
FOO
FOO
BAR
BAR
```
(and in debug builds, that *is* what happens).

Instead, this happened: in release builds, it prints:

```
FOO
BAR
FOO
BAR
```

### Meta

This was on a playpen running 1.44.0-nightly, 2020-04-05.

This all arose from a conversation with @eddyb regarding structural match; you can read it on the [zulip archive](https://zulip-archive.rust-lang.org/131828tcompiler/22816Structuralmatchmarkertraits.html#193034951)

cc #31434

**Comment by pnkfelix** [comment] 2020-04-06 22:16
It is not clear to me what the best thing to do here is. @eddyb would like to disallow matching against function pointer constants entirely. I am thinking it might be better to issue a lint, since I know from experience some people simply *are* doing this, for better or for worse, and I suspect that its not a soundness issue, just a potential gotcha.

Also, for you archeaologists out there, here is a classic [rrrs-authors thread](https://groups.csail.mit.edu/mac/ftpdir/scheme-mail/HTML/rrrs-1985/msg00195.html) on this subject.

**Comment by eddyb** [comment] 2020-04-06 22:36
The scary thing to me is this same thing happening with `const` generics, because they use the same "structural match" requirement.

**Comment by eddyb** [comment] 2020-04-06 23:46
Looks like this is where the whitelisting is missing: https://github.com/rust-lang/rust/blob/6dee5f1126dfd5c9314ee5ae9d9eb010e35ef257/src/librustc_mir_build/hair/pattern/const_to_pat.rs#L260.

**Comment by eddyb** [comment] 2020-04-07 01:18
Very disconcertingly, it doesn't look like we turn `&T` constants into reference patterns, which means we can't fully correctly check leaves behind them (and I'm scared to look at how anything *works* with them, are they lazily expanded?).

Fixing that should probably be a priority, I wonder if @oli-obk already has plans for this.

**Comment by oli-obk** [comment] 2020-04-07 05:49
Not just that, I have an implementation of it! https://github.com/rust-lang/rust/pull/70743

**Comment by eddyb** [comment] 2020-04-07 10:17
Ah, thanks, I vaguely remembered some discussion, I should've checked your PRs first, sorry!

**Comment by hanna-kruppe** [comment] 2020-04-07 14:35
I believe the non-deterministic comparison of function pointers is already tracked by https://github.com/rust-lang/rust/issues/54685, though the question of what to do about it w.r.t. patterns seems novel and worth tracking independently.

**Comment by eddyb** [comment] 2020-04-07 15:56
Yesterday I wrote (https://github.com/rust-lang/rust/issues/70861#issuecomment-610072709):
> The scary thing to me is this same thing happening with const generics, because they use the same "structural match" requirement.
> (but there's no "runtime value" there, so it's more nebulous in a different way I suppose)

But today I filed #70889, due to which we might need to do a completely separate check for const generics, so we don't have to be as strict on pattern `match`-ing anyway.

**Comment by RalfJung** [comment] 2020-04-08 13:37
I think this is basically a duplicate of https://github.com/rust-lang/rust/issues/54685, caused by `unnamed_addr`.

> though the question of what to do about it w.r.t. patterns seems novel and worth tracking independently.

`match` with a constant and `==` are just two different ways to write a comparison. This definitely should be mentioned in the other issue but I feel separate tracking is confusing.

**Comment by pnkfelix** [comment] 2020-04-28 20:12
> I think this is basically a duplicate of #54685, caused by `unnamed_addr`.
> 
> > though the question of what to do about it w.r.t. patterns seems novel and worth tracking independently.
> 
> `match` with a constant and `==` are just two different ways to write a comparison. This definitely should be mentioned in the other issue but I feel separate tracking is confusing.

Separate tracking may indeed be confusing, but I just want to note that I do not consider `match` with a constant to be equivalent to using `==`.

In particular, the point of rust-lang/rfcs#1445 is that the compiler has not always treated such matches as being equivalent to `==` (namely in cases where `PartialEq` has not been implemented via `#[derive(..)]`), and we did not want to commit at that time to choosing between so-called "structural" vs "semantic" equality.

Having said that, certainly this is *related* to #54685, and it may indeed be a good idea to merge these two tickets. But I want to make sure we do it for the right reason.

**Comment by RalfJung** [comment] 2024-01-09 09:17
This code causes forward-compat lints now, so once pointer_structural_match is a hard error this can be closed.

**Closed** 2024-05-26 10:01 UTC
Labels: T-compiler, C-bug, A-patterns
