### ISSUE TITLE
error: internal compiler error: compiler\rustc_infer\src\infer\error_reporting\need_type_info.rs:856:33: unexpected path

### ISSUE THREAD

**Issue by kulicuu** [rust-lang/rust#97959] opened 2022-06-10 18:34 UTC
### Code

```Rust
#![feature(drain_filter)]

use super::precursors::*;
use super::pipeline_101::*;
use super::pipeline_102::*;

use erupt::{
    cstr,
    utils::{self, surface},
    vk, DeviceLoader, EntryLoader, InstanceLoader,
    vk::{Device, MemoryMapFlags},
};
use cgmath::{Deg, Rad, Matrix4, Point3, Vector3, Vector4};
use nalgebra_glm as glm;
use std::{
    ffi::{c_void, CStr, CString},
    fs,
    fs::{write, OpenOptions},
    io::prelude::*,
    mem::*,
    os::raw::c_char,
    ptr,
    result::Result,
    result::Result::*,
    string::String,
    sync::{Arc, Barrier, Mutex, mpsc},
    thread,
    time,
};
// use std::sync::mpsc;
use std::time::{Duration, Instant};
use std::thread::sleep;
use smallvec::SmallVec;
use raw_window_handle::{HasRawWindowHandle, RawWindowHandle};
use memoffset::offset_of;
use simple_logger::SimpleLogger;
use winit::{
    dpi::PhysicalSize,
    event::{
        Event, KeyboardInput, WindowEvent,
        ElementState, StartCause, VirtualKeyCode,
        DeviceEvent,
    },
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
    window::Window
};

use closure::closure;
use structopt::StructOpt;
const TITLE: &str = "vulkan-routine-6300";
const FRAMES_IN_FLIGHT: usize = 2;
const LAYER_KHRONOS_VALIDATION: *const c_char = cstr!("VK_LAYER_KHRONOS_validation");
const SHADER_VERT: &[u8] = include_bytes!("../spv/s_400_.vert.spv");
const SHADER_FRAG: &[u8] = include_bytes!("../spv/s1.frag.spv");
#[repr(C)]
#[derive(Debug, Clone, Copy)]
struct FrameData {
    present_semaphore: vk::Semaphore,
    render_semaphore: vk::Semaphore,
    command_pool: vk::CommandPool,
    command_buffer: vk::CommandBuffer,
}
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct VertexV3 {
    pos: [f32; 4],
    color: [f32; 4],
}

#[repr(C)]
#[derive(Clone, Debug, Copy)]
struct PushConstants {
    view: glm::Mat4,
}

#[repr(C)]
#[derive(Clone, Debug, Copy)]
struct UniformBufferObject {
    model: Matrix4<f32>,
    view: Matrix4<f32>,
    proj: Matrix4<f32>,
}

#[derive(Debug, StructOpt)]
struct Opt {
    #[structopt(short, long)]
    validation_layers: bool,
}

#[repr(C)]
#[derive(Debug, Clone, Copy)]
struct OldCamera {
    location: glm::Vec3,
    target: glm::Vec3,  // not necessarily normalized, this one to one with the look_at (or look_at_rh) function.
    up: glm::Vec3,  // yaw axis in direction of up
}

#[repr(C)]
#[derive(Debug, Clone, Copy)]
struct ControlInput {
    roll: i32,
    pitch: i32,
    yaw: i32,
    skew: i32,
}

// static mut log_300: Vec<String> = vec!();
unsafe extern "system" fn debug_callback(
    _message_severity: vk::DebugUtilsMessageSeverityFlagBitsEXT,
    _message_types: vk::DebugUtilsMessageTypeFlagsEXT,
    p_callback_data: *const vk::DebugUtilsMessengerCallbackDataEXT,
    _p_user_data: *mut c_void,
) -> vk::Bool32 {
    let str_99 = String::from(CStr::from_ptr((*p_callback_data).p_message).to_string_lossy());
    // log_300.push(str_99 );
    eprintln!(
        "{}",
        CStr::from_ptr((*p_callback_data).p_message).to_string_lossy()
    );
    vk::FALSE
}


pub unsafe fn vulkan_routine_8400
()
{
    println!("\n8400\n");
    let opt = Opt { validation_layers: false };
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_title(TITLE)
        .with_resizable(false)
        .with_maximized(true)
        
        .build(&event_loop)
        .unwrap();
    let entry = Arc::new(EntryLoader::new().unwrap());
    let application_name = CString::new("Vulkan-Routine-6300").unwrap();
    let engine_name = CString::new("Peregrine").unwrap();
    let app_info = vk::ApplicationInfoBuilder::new()
        .application_name(&application_name)
        .application_version(vk::make_api_version(0, 1, 0, 0))
        .engine_name(&engine_name)
        .engine_version(vk::make_api_version(0, 1, 0, 0))
        .api_version(vk::make_api_version(0, 1, 0, 0));
    let mut instance_extensions = surface::enumerate_required_extensions(&window).unwrap();
    if opt.validation_layers {
        instance_extensions.push(vk::EXT_DEBUG_UTILS_EXTENSION_NAME);
    }
    let mut instance_layers = Vec::new();
    if opt.validation_layers {
        instance_layers.push(LAYER_KHRONOS_VALIDATION);
    }
    let device_extensions = vec![
        vk::KHR_SWAPCHAIN_EXTENSION_NAME,
        vk::KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME,
        vk::KHR_RAY_QUERY_EXTENSION_NAME,
        vk::KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME,
        vk::KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME,
        vk::KHR_SHADER_FLOAT_CONTROLS_EXTENSION_NAME,
        vk::KHR_SPIRV_1_4_EXTENSION_NAME,
        vk::KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME,
        vk::EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME,
    ];
    let mut device_layers = Vec::new();
    if opt.validation_layers {
        device_layers.push(LAYER_KHRONOS_VALIDATION);
    }
    let instance_info = vk::InstanceCreateInfoBuilder::new()
        .application_info(&app_info)
        .enabled_extension_names(&instance_extensions)
        .enabled_layer_names(&instance_layers);
    let instance = Arc::new(InstanceLoader::new(&entry, &instance_info).unwrap());
    let messenger = if opt.validation_layers {
        let messenger_info = vk::DebugUtilsMessengerCreateInfoEXTBuilder::new()
            .message_severity(
                vk::DebugUtilsMessageSeverityFlagsEXT::VERBOSE_EXT
                    | vk::DebugUtilsMessageSeverityFlagsEXT::WARNING_EXT
                    | vk::DebugUtilsMessageSeverityFlagsEXT::ERROR_EXT,
            )
            .message_type(
                vk::DebugUtilsMessageTypeFlagsEXT::GENERAL_EXT
                    | vk::DebugUtilsMessageTypeFlagsEXT::VALIDATION_EXT
                    | vk::DebugUtilsMessageTypeFlagsEXT::PERFORMANCE_EXT,
            )
            .pfn_user_callback(Some(debug_callback));

        instance.create_debug_utils_messenger_ext(&messenger_info, None).expect("problem creating debug util.");
    } else {
        Default::default()
    };
    let surface = surface::create_surface(&instance, &window, None).unwrap();

    let (
        physical_device, 
        queue_family, 
        format, 
        present_mode, 
        device_properties
    ) = create_precursors
    (
        &instance,
        surface.clone(),
    ).unwrap();

    let queue_info = vec![vk::DeviceQueueCreateInfoBuilder::new()
        .queue_family_index(queue_family)
        .queue_priorities(&[1.0])];
    let features = vk::PhysicalDeviceFeaturesBuilder::new();
    let device_info = vk::DeviceCreateInfoBuilder::new()
        .queue_create_infos(&queue_info)
        .enabled_features(&features)
        .enabled_extension_names(&device_extensions)
        .enabled_layer_names(&device_layers);

    let device = Arc::new(Mutex::new(DeviceLoader::new(&instance, physical_device, &device_info).unwrap()));



    let (tx, rx) = mpsc::channel();

    let c1 = closure!(clone device, move rx, ||{
        // device;    
        // let queue = device.get_device_queue(queue_family, 0);


        // https://docs.rs/closure/0.3.0/closure/
        // let &(ref lock, ref cvar) = &*pair;
        // let mut started = lock.lock().unwrap();
        // *started = true;
        // // We notify the condvar that the value has changed.
        // cvar.notify_one();

        let device = &*device;


        let queue = device.lock().unwrap().get_device_queue(2, 0);
        true
    });


    thread::spawn(c1);

    // let thread_closure = closure!(move string, ref x, ref mut y, clone rc, |arg: i32| {

    // let thread_closure = closure!(clone device, || {
    //     false
    // };

    // thread::spawn(clone thread_closure);

}
```

### Meta

`rustc --version --verbose`:
```
note: rustc 1.63.0-nightly (420c970cb 2022-06-09) running on x86_64-pc-windows-msvc

```

### Error output

```
$ RUSTFLAGS=-Awarnings cargo run
   Compiling vulkan__march__22 v0.1.0 (C:\Users\wylie\Contexts\vulkan__march__22)
error: internal compiler error: compiler\rustc_infer\src\infer\error_reporting\need_type_info.rs:856:33: unexpected path: def=smallvec::alloc::ffi::CString substs=[] path=Path { span: src\vulkan_8400.rs:139:28: 139:35 (#0), res: Def(TyAlias, DefId(1:2774 ~ std[e88d]::ffi::CString)), segments: [PathSegment { ident: CString#0, hir_id: Some(HirId {
 owner: DefId(0:404 ~ vulkan__march__22[bfd5]::vulkan_8400::vulkan_routine_8400), local_id: 80 }), res: Some(Err), args: None, infer_args: true }] }

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef\compiler\rustc_errors\src\lib.rs:1334:9
stack backtrace:
   0:     0x7ffff4af9d1f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd00b3169bbebe7a6
   1:     0x7ffff4b34d1a - core::fmt::write::h83bcfd786d8d3c56
   2:     0x7ffff4aec119 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h88f033d9e0389ceb
   3:     0x7ffff4afd60b - std::panicking::default_hook::h0e842be4a4a3d598
   4:     0x7ffff4afd28b - std::panicking::default_hook::h0e842be4a4a3d598
   5:     0x7fffcefb9936 - rustc_driver[fcb7863660e03633]::pretty::print_after_hir_lowering
   6:     0x7ffff4afddb2 - std::panicking::rust_panic_with_hook::h6fca5b6121e98a07
   7:     0x7fffd358fd55 - <rustc_middle[5bc4195c4d9d0f10]::mir::interpret::allocation::ConstAllocation as rustc_middle[5bc4195c4d9d0f10]::ty::context::Lift>::lift_to_tcx
   8:     0x7fffd358d569 - <rustc_middle[5bc4195c4d9d0f10]::mir::interpret::allocation::ConstAllocation as rustc_middle[5bc4195c4d9d0f10]::ty::context::Lift>::lift_to_tcx
   9:     0x7fffd3aba789 - rustc_middle[5bc4195c4d9d0f10]::util::bug::bug_fmt
  10:     0x7fffd3526839 - <rustc_middle[5bc4195c4d9d0f10]::mir::GeneratorInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  11:     0x7fffd3524fd3 - <rustc_middle[5bc4195c4d9d0f10]::mir::GeneratorInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  12:     0x7fffd35249b2 - <rustc_middle[5bc4195c4d9d0f10]::mir::GeneratorInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  13:     0x7fffd351af19 - <rustc_middle[5bc4195c4d9d0f10]::ty::consts::valtree::ValTree>::zst
  14:     0x7fffd351d4bc - <rustc_middle[5bc4195c4d9d0f10]::ty::generics::GenericPredicates>::instantiate_identity
  15:     0x7fffd3ab7808 - rustc_middle[5bc4195c4d9d0f10]::util::bug::bug_fmt
  16:     0x7fffd33e1219 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::TypeAnnotationNeeded as core[4876a3596c0cda00]::convert::Into<rustc_errors[7ae4085755b62a09]::diagnostic::DiagnosticId>>::into
  17:     0x7fffd33e1971 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  18:     0x7fffd33e1710 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  19:     0x7fffd3430fef - <rustc_infer[e061849302d930c7]::infer::lexical_region_resolve::RegionResolutionError as core[4876a3596c0cda00]::fmt::Debug>::fmt
  20:     0x7fffd33e1724 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  21:     0x7fffd33e1297 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_local
  22:     0x7fffd3431206 - <rustc_infer[e061849302d930c7]::infer::lexical_region_resolve::RegionResolutionError as core[4876a3596c0cda00]::fmt::Debug>::fmt
  23:     0x7fffd33e1724 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  24:     0x7fffd3352ef1 - <rustc_infer[e061849302d930c7]::infer::InferCtxt>::emit_inference_failure_err
  25:     0x7fffd32f323c - <rustc_infer[e061849302d930c7]::infer::InferCtxt as rustc_trait_selection[df7763aa9895efc7]::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  26:     0x7fffd32df6b5 - <rustc_infer[e061849302d930c7]::infer::InferCtxt as rustc_trait_selection[df7763aa9895efc7]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  27:     0x7fffd1973bf4 - <rustc_typeck[f829abbe4c337b0d]::check::fn_ctxt::FnCtxt>::apply_adjustments
  28:     0x7fffd1a90b15 - <rustc_infer[e061849302d930c7]::infer::outlives::env::OutlivesEnvironment as rustc_typeck[f829abbe4c337b0d]::check::regionck::OutlivesEnvironmentExt>::add_implied_bounds
  29:     0x7fffd19d5c35 - rustc_typeck[f829abbe4c337b0d]::check::provide
  30:     0x7fffd258b208 - <&[rustc_span[794d72b76b0afba1]::def_id::LocalDefId] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7fffd2607aa2 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  32:     0x7fffd2747120 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  33:     0x7fffd26adbb3 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  34:     0x7fffd264bbb9 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  35:     0x7fffd34a6a63 - <rustc_middle[5bc4195c4d9d0f10]::ty::context::TyCtxt as rustc_query_system[f7153c0dd233211e]::dep_graph::DepContext>::try_force_from_dep_node
  36:     0x7fffd25f24ff - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7fffd26b4dba - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  38:     0x7fffd288abf3 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  39:     0x7fffd1837251 - <rustc_typeck[f829abbe4c337b0d]::outlives::explicit::ExplicitPredicatesMap as core[4876a3596c0cda00]::fmt::Debug>::fmt
  40:     0x7fffd19dbd13 - <rustc_typeck[f829abbe4c337b0d]::check::MaybeInProgressTables>::borrow_mut
  41:     0x7fffd258cffe - <&[rustc_span[794d72b76b0afba1]::def_id::LocalDefId] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  42:     0x7fffd262f85f - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7fffd27dd76d - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7fffd2855b59 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7fffd1a317cf - <rustc_typeck[f829abbe4c337b0d]::structured_errors::wrong_number_of_generic_args::GenericArgsInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  46:     0x7fffd1832cf6 - rustc_typeck[f829abbe4c337b0d]::check_crate
  47:     0x7fffcf0a8aff - rustc_interface[c454f779e74f683c]::passes::analysis
  48:     0x7fffd258caee - <&[rustc_span[794d72b76b0afba1]::def_id::LocalDefId] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  49:     0x7fffd262620f - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  50:     0x7fffd27c78a4 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  51:     0x7fffd288b076 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  52:     0x7fffcef6fbaf - <rustc_driver[fcb7863660e03633]::args::Error as core[4876a3596c0cda00]::fmt::Debug>::fmt
  53:     0x7fffcef47200 - <rustc_typeck[f829abbe4c337b0d]::collect::const_evaluatable_predicates_of::ConstCollector as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_const_param_default
  54:     0x7fffcefc80d5 - <rustc_driver[fcb7863660e03633]::Compilation as core[4876a3596c0cda00]::fmt::Debug>::fmt
  55:     0x7fffcef4845d - <rustc_typeck[f829abbe4c337b0d]::collect::const_evaluatable_predicates_of::ConstCollector as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_const_param_default
  56:     0x7fffcefaee66 - <rustc_metadata[daa9efe566ca3a6e]::rmeta::encoder::EncodeContext as rustc_serialize[7372cb0a439f061]::serialize::Encoder>::emit_raw_bytes
  57:     0x7fffcef72388 - <rustc_driver[fcb7863660e03633]::args::Error as core[4876a3596c0cda00]::fmt::Debug>::fmt
  58:     0x7ffff4b0ef5c - std::sys::windows::thread::Thread::new::h20e1250a6b16a9fb
  59:     0x7ff89b037034 - BaseThreadInitThunk
  60:     0x7ff89c3c2651 - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.63.0-nightly (420c970cb 2022-06-09) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `vulkan_8400::vulkan_routine_8400`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `vulkan__march__22`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/420c970cb1edccbf60ff2aeb51ca01e2300b09ef\compiler\rustc_errors\src\lib.rs:1334:9
stack backtrace:
   0:     0x7ffff4af9d1f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd00b3169bbebe7a6
   1:     0x7ffff4b34d1a - core::fmt::write::h83bcfd786d8d3c56
   2:     0x7ffff4aec119 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h88f033d9e0389ceb
   3:     0x7ffff4afd60b - std::panicking::default_hook::h0e842be4a4a3d598
   4:     0x7ffff4afd28b - std::panicking::default_hook::h0e842be4a4a3d598
   5:     0x7fffcefb9936 - rustc_driver[fcb7863660e03633]::pretty::print_after_hir_lowering
   6:     0x7ffff4afddb2 - std::panicking::rust_panic_with_hook::h6fca5b6121e98a07
   7:     0x7fffd358fd55 - <rustc_middle[5bc4195c4d9d0f10]::mir::interpret::allocation::ConstAllocation as rustc_middle[5bc4195c4d9d0f10]::ty::context::Lift>::lift_to_tcx
   8:     0x7fffd358d569 - <rustc_middle[5bc4195c4d9d0f10]::mir::interpret::allocation::ConstAllocation as rustc_middle[5bc4195c4d9d0f10]::ty::context::Lift>::lift_to_tcx
   9:     0x7fffd3aba789 - rustc_middle[5bc4195c4d9d0f10]::util::bug::bug_fmt
  10:     0x7fffd3526839 - <rustc_middle[5bc4195c4d9d0f10]::mir::GeneratorInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  11:     0x7fffd3524fd3 - <rustc_middle[5bc4195c4d9d0f10]::mir::GeneratorInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  12:     0x7fffd35249b2 - <rustc_middle[5bc4195c4d9d0f10]::mir::GeneratorInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  13:     0x7fffd351af19 - <rustc_middle[5bc4195c4d9d0f10]::ty::consts::valtree::ValTree>::zst
  14:     0x7fffd351d4bc - <rustc_middle[5bc4195c4d9d0f10]::ty::generics::GenericPredicates>::instantiate_identity
  15:     0x7fffd3ab7808 - rustc_middle[5bc4195c4d9d0f10]::util::bug::bug_fmt
  16:     0x7fffd33e1219 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::TypeAnnotationNeeded as core[4876a3596c0cda00]::convert::Into<rustc_errors[7ae4085755b62a09]::diagnostic::DiagnosticId>>::into
  17:     0x7fffd33e1971 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  18:     0x7fffd33e1710 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  19:     0x7fffd3430fef - <rustc_infer[e061849302d930c7]::infer::lexical_region_resolve::RegionResolutionError as core[4876a3596c0cda00]::fmt::Debug>::fmt
  20:     0x7fffd33e1724 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  21:     0x7fffd33e1297 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_local
  22:     0x7fffd3431206 - <rustc_infer[e061849302d930c7]::infer::lexical_region_resolve::RegionResolutionError as core[4876a3596c0cda00]::fmt::Debug>::fmt
  23:     0x7fffd33e1724 - <rustc_infer[e061849302d930c7]::infer::error_reporting::need_type_info::FindInferSourceVisitor as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_expr
  24:     0x7fffd3352ef1 - <rustc_infer[e061849302d930c7]::infer::InferCtxt>::emit_inference_failure_err
  25:     0x7fffd32f323c - <rustc_infer[e061849302d930c7]::infer::InferCtxt as rustc_trait_selection[df7763aa9895efc7]::traits::error_reporting::InferCtxtPrivExt>::maybe_report_ambiguity
  26:     0x7fffd32df6b5 - <rustc_infer[e061849302d930c7]::infer::InferCtxt as rustc_trait_selection[df7763aa9895efc7]::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  27:     0x7fffd1973bf4 - <rustc_typeck[f829abbe4c337b0d]::check::fn_ctxt::FnCtxt>::apply_adjustments
  28:     0x7fffd1a90b15 - <rustc_infer[e061849302d930c7]::infer::outlives::env::OutlivesEnvironment as rustc_typeck[f829abbe4c337b0d]::check::regionck::OutlivesEnvironmentExt>::add_implied_bounds
  29:     0x7fffd19d5c35 - rustc_typeck[f829abbe4c337b0d]::check::provide
  30:     0x7fffd258b208 - <&[rustc_span[794d72b76b0afba1]::def_id::LocalDefId] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  31:     0x7fffd2607aa2 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  32:     0x7fffd2747120 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  33:     0x7fffd26adbb3 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  34:     0x7fffd264bbb9 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  35:     0x7fffd34a6a63 - <rustc_middle[5bc4195c4d9d0f10]::ty::context::TyCtxt as rustc_query_system[f7153c0dd233211e]::dep_graph::DepContext>::try_force_from_dep_node
  36:     0x7fffd25f24ff - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  37:     0x7fffd26b4dba - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  38:     0x7fffd288abf3 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  39:     0x7fffd1837251 - <rustc_typeck[f829abbe4c337b0d]::outlives::explicit::ExplicitPredicatesMap as core[4876a3596c0cda00]::fmt::Debug>::fmt
  40:     0x7fffd19dbd13 - <rustc_typeck[f829abbe4c337b0d]::check::MaybeInProgressTables>::borrow_mut
  41:     0x7fffd258cffe - <&[rustc_span[794d72b76b0afba1]::def_id::LocalDefId] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  42:     0x7fffd262f85f - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  43:     0x7fffd27dd76d - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  44:     0x7fffd2855b59 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  45:     0x7fffd1a317cf - <rustc_typeck[f829abbe4c337b0d]::structured_errors::wrong_number_of_generic_args::GenericArgsInfo as core[4876a3596c0cda00]::fmt::Debug>::fmt
  46:     0x7fffd1832cf6 - rustc_typeck[f829abbe4c337b0d]::check_crate
  47:     0x7fffcf0a8aff - rustc_interface[c454f779e74f683c]::passes::analysis
  48:     0x7fffd258caee - <&[rustc_span[794d72b76b0afba1]::def_id::LocalDefId] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  49:     0x7fffd262620f - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  50:     0x7fffd27c78a4 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  51:     0x7fffd288b076 - <&[rustc_span[794d72b76b0afba1]::symbol::Ident] as rustc_serialize[7372cb0a439f061]::serialize::Decodable<rustc_query_impl[1e24416238fe6dd]::on_disk_cache::CacheDecoder>>::decode
  52:     0x7fffcef6fbaf - <rustc_driver[fcb7863660e03633]::args::Error as core[4876a3596c0cda00]::fmt::Debug>::fmt
  53:     0x7fffcef47200 - <rustc_typeck[f829abbe4c337b0d]::collect::const_evaluatable_predicates_of::ConstCollector as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_const_param_default
  54:     0x7fffcefc80d5 - <rustc_driver[fcb7863660e03633]::Compilation as core[4876a3596c0cda00]::fmt::Debug>::fmt
  55:     0x7fffcef4845d - <rustc_typeck[f829abbe4c337b0d]::collect::const_evaluatable_predicates_of::ConstCollector as rustc_hir[337e59735c2ec590]::intravisit::Visitor>::visit_const_param_default
  56:     0x7fffcefaee66 - <rustc_metadata[daa9efe566ca3a6e]::rmeta::encoder::EncodeContext as rustc_serialize[7372cb0a439f061]::serialize::Encoder>::emit_raw_bytes
  57:     0x7fffcef72388 - <rustc_driver[fcb7863660e03633]::args::Error as core[4876a3596c0cda00]::fmt::Debug>::fmt
  58:     0x7ffff4b0ef5c - std::sys::windows::thread::Thread::new::h20e1250a6b16a9fb
  59:     0x7ff89b037034 - BaseThreadInitThunk
  60:     0x7ff89c3c2651 - RtlUserThreadStart

```

</p>
</details>

**Comment by compiler-errors** [comment] 2022-06-10 19:14
I don't think this needs MCVEing, this is very common to some other issues recently posted due to `need_type_info`

**Comment by bjorn3** [comment] 2022-06-12 17:51
(edited the issue title to be more useful when searching if an issue is already reported)

**Comment by cjgillot** [comment] 2022-09-05 15:46
Closing as duplicate of closed https://github.com/rust-lang/rust/issues/97698.

**Closed by cjgillot** 2022-09-05 15:46 UTC
Labels: I-ICE, T-compiler, C-bug
