### ISSUE TITLE
Source is missing from docs for crates that use a procedural macro

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#43371] opened 2017-07-20 20:36 UTC
Running `./mach doc` on Servo's codebase yields a bunch of crates with the following warning:
```
warning: source code was requested to be rendered, but processing `<proc-macro source code>` had an error: No such file or directory (os error 2)
         skipping rendering of source code
```
This means that the source is available for [some types](http://doc.servo.org/constellation/constellation/struct.Constellation.html), but [not others](http://doc.servo.org/script/script_thread/struct.ScriptThread.html).

I'll try to figure out when this regressed.

**Comment by jdm** [comment] 2017-07-20 21:15
Minimal reproduction:
```rust
extern crate heapsize;
#[macro_use] extern crate heapsize_derive;

#[derive(HeapSizeOf)]
pub struct Range<I>(I);
```
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Josh Matthews <josh@joshmatthews.net>"]

[dependencies]
heapsize = "0.4"
heapsize_derive = "0.1"
```

**Comment by jdm** [comment] 2017-07-20 21:17
If I use `cargo +beta doc --open` then it works fine; `cargo +nightly doc --open` is broken.

**Comment by jdm** [comment] 2017-07-20 21:22
```
godot:foo jdm$ cargo --version
cargo 0.21.0-nightly (eb6cf012a 2017-07-02)
godot:foo jdm$ rustc --version
rustc 1.20.0-nightly (b2c070787 2017-07-13)
```

**Comment by jdm** [comment] 2017-07-20 21:42
The 7/6 nightly (3610a70ce) works fine, and the 7/7 nightly (696412de7) is broken.

**Comment by jdm** [comment] 2017-07-20 21:43
My money is on #40939.

**Comment by alexcrichton** [comment] 2017-07-23 15:46
cc @jseyfried, @nrc

**Comment by nrc** [comment] 2017-07-25 05:07
I believe the issue is that (since #40939) we no longer accurately track expansion info for names declared in a macro. That means that tools think some names are hand-written, when they are macro generated (this is also causing problems for the RLS). #43179 was meant to fix this, but it did not (at least not for all cases). I haven't looked into the details.

**Comment by oli-obk** [comment] 2017-07-25 05:51
Not just names. Clippy gets confused by the `true` or `false` inside the expansion of `cfg!`: https://github.com/rust-lang/rust/issues/43268

**Comment by Mark-Simulacrum** [comment] 2017-07-27 16:54
Nominating; needs investigation and a fix.

**Comment by nrc** [comment] 2017-07-28 05:01
This might get fixed by https://github.com/rust-lang/rust/pull/43230, although perhaps not (the example here is a 1.1 custom derive, but looking at 43230 I'm not sure if the filename makes sense, so I'm not convinced I know what it going on 100%)

**Comment by nrc** [comment] 2017-07-28 05:29
I can't reproduce the bug in the reduced example with today's nightly (perhaps it was fixed by #43179). @jdm can you still repro?

**Comment by nrc** [comment] 2017-07-28 05:40
And the link to https://doc.servo.org/script/script_thread/struct.ScriptThread.html works. So I think this is fixed. @jdm please re-open if not.

**Closed by nrc** 2017-07-28 05:40 UTC
Labels: A-rustdoc, C-bug, P-high, regression-from-stable-to-beta, T-compiler

**Comment by Aceeri** [comment] 2017-09-09 03:14
I'm receiving this error when trying to run rustdoc here: https://travis-ci.org/amethyst/website#L935

I'm unable to reproduce locally, but others on macos/linux have been able to. Unsure if this is related to this or not however.
