### ISSUE TITLE
'Self' cannot be used in enums

### ISSUE THREAD

**Issue by anirudhb** [rust-lang/rust#49636] opened 2018-04-04 01:44 UTC
I am trying to create a method on an enum, like this:
```rust
enum Foo {
    Bar(String),
    Baz
}

impl Foo {
    pub fn get_bar(self) -> Option<String> {
        match self {
//          vvvv error occurs
            Self::Bar(s) => Some(s),
            _ => None,
        }
    }
}
```

An error occurs: `No variant named 'Bar' found for type 'foo::Foo' in the current scope`

Is this intended behavior? If so, it should be made more clear. At least provide a better error message.
Honestly, if this isn't "implemented" yet, then it should be because it would make a better user experience.

edit (x2): formatting

**Comment by petrochenkov** [comment] 2018-04-04 09:09
Duplicate of https://github.com/rust-lang/rust/issues/26264

**Closed by petrochenkov** 2018-04-04 09:09 UTC
