### ISSUE TITLE
Functions/modules using unstable *syntax* (e.g., `impl Trait`) can't be CFGed out on stable

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#36478] opened 2016-09-14 16:33 UTC
This fails on stable because rust still parses the unstable module:

```rust
#[cfg(feature = "unstable")]
mod unstable {
    fn foo() -> impl Foo {}
}
```

It's possible to work around this by conditionally defining a macro and then having the macro define the module but that's a bit messy:

```rust
#[cfg(feature = "unstable")]
macro_rules! decl_unstable {
    () =>  {
        mod unstable {
            fn foo() -> impl Foo {}
        }
    }
}

#[cfg(not(feature = "unstable"))]
macro_rules! decl_unstable {
    () =>  {}
}

decl_unstable!();
```

**Comment by durka** [comment] 2016-09-14 16:47
Or implement the module in another file. I think this is a fundamental limitation -- you can't skip forward over an item if you don't understand the syntax that the item is using. The only way we could solve it is with time travel, i.e., doing a point release of stable that knows the `impl Trait` syntax but not what it means.

**Comment by Stebalien** [comment] 2016-09-14 17:19
> Or implement the module in another file.

That's actually what I'm doing in my project (still the same problem). That is, I have the following in my `lib.rs`:

```rust
#[cfg(feature="unstable")]
mod unstable;
```

And a module, `unstable.rs`

```rust
fn foo() -> impl Foo {}
```

**Comment by retep998** [comment] 2016-09-14 20:51
Modules are parsed before `#[cfg]`'s are parsed, which has been an issue for as long as I can remember. Can someone find whether there is an issue tracking this?

**Comment by durka** [comment] 2016-09-14 20:57
Dupe of #27873. cc @jseyfried (`cfg` expert!)

**Comment by durka** [comment] 2016-09-14 23:09
Though this'll be fixed by the above PR, the workaround for current stable is

```rust
#[cfg_attr(feature="nightly", path="nightly.rs")]
#[cfg_attr(not(feature="nightly"), path="stable.rs")]
mod stuff;
```

**Closed** 2016-09-17 09:51 UTC
