### ISSUE TITLE
thread 'rustc' panicked at 'Failed to recover key for codegen_fn_attrs(3b51ec5b25d9fa81-72de013b10257521) with hash 3b51ec5b25d9fa81-72de013b10257521', compiler/rustc_middle/src/ty/query/mod.rs:235:5

### ISSUE THREAD

**Issue by helfman** [rust-lang/rust#84282] opened 2021-04-17 22:53 UTC
### Code

```Rust
n main() {
    let x = Some(5);

    match x {
        Some(y) if y > 2 && y < 5 => println!("first"),
        Some(1) => println!("second"),
        _ => println!("else"),
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

### Error output

```
thread 'rustc' panicked at 'Failed to recover key for codegen_fn_attrs(3b51ec5b25d9fa81-72de013b10257521) with hash 3b51ec5b25d9fa81-72de013b10257521', compiler/rustc_middle/src/ty/query/mod.rs:235:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/compiler/rustc_codegen_ssa/src/back/write.rs:1437:21

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Failed to recover key for codegen_fn_attrs(3b51ec5b25d9fa81-72de013b10257521) with hash 3b51ec5b25d9fa81-72de013b10257521', compiler/rustc_middle/src/ty/query/mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:435:5
   2: rustc_middle::ty::query::try_load_from_on_disk_cache
   3: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   4: rustc_middle::ty::context::tls::with_context::{{closure}}
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore
   7: rustc_middle::ty::query::on_disk_cache::OnDiskCache::serialize
   8: rustc_session::utils::<impl rustc_session::session::Session>::time
   9: rustc_incremental::persist::save::save_in
  10: rustc_session::utils::<impl rustc_session::session::Session>::time
  11: rustc_data_structures::sync::join
  12: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  13: rustc_incremental::persist::save::save_dep_graph
  14: rustc_codegen_ssa::base::finalize_tcx
  15: rustc_codegen_ssa::base::codegen_crate
  16: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  17: rustc_session::utils::<impl rustc_session::session::Session>::time
  18: rustc_interface::passes::QueryContext::enter
  19: rustc_interface::queries::Queries::ongoing_codegen
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-04-17 23:15
@helfman: Did you modify that file before the crash happened? Could you zip and upload your entire `target` directory?

**Comment by helfman** [comment] 2021-04-17 23:20
[repro.zip](https://github.com/rust-lang/rust/files/6330204/repro.zip)
Here is the entire directory, including sources and target.

**Comment by jyn514** [comment] 2021-05-19 09:41
Likely a duplicate of https://github.com/rust-lang/rust/issues/83962.

**Closed by jyn514** 2021-05-19 09:41 UTC
Labels: A-incr-comp, C-bug, I-ICE, T-compiler
