### ISSUE TITLE
wrong lifetime on trait object type

### ISSUE THREAD

**Issue by kirillkh** [rust-lang/rust#32725] opened 2016-04-04 12:23 UTC
I tried this code: https://play.rust-lang.org/?gist=723ce853c236c7437770b4535d85f5e3&version=nightly&backtrace=0

The reason it does not compile seems wrong to me, at least I don't understand it (why must "&mut r" be valid for the whole main() {} block?). If I remove the type annotation on x, it compiles. It also compiles if I change the type annotation to "&mut (MyRng+'static)".

Another problem is that if I change the type annotation to "()", the type checker says "found `&mut MyRng`", not "found `&mut (MyRng+'static)`", so there is a hidden lifetime parameter in the type that the type checker doesn't print out.

**Comment by eefriedman** [comment] 2016-04-05 01:01
Reduces to:

```
use std::ops::DerefMut;
use std::fmt::Debug;

fn main() {
    let mut r: Box<Debug> = Box::new(1);
    let x : &mut Debug = Box::deref_mut(&mut r);
}
```

This should work, as far as I can tell.

**Comment by respeccing** [comment] 2016-04-06 15:29
Playground for @eefriedman 's code above: https://play.rust-lang.org/?gist=18331877c8d50e523b31223615b3b02c&version=nightly

What you see:
```rust
<anon>:6:46: 6:47 error: `r` does not live long enough
<anon>:6     let x : &mut Debug = Box::deref_mut(&mut r);
                                                      ^
<anon>:4:11: 7:2 note: reference must be valid for the block at 4:10...
<anon>:4 fn main() {
<anon>:5     let mut r: Box<Debug> = Box::new(1);
<anon>:6     let x : &mut Debug = Box::deref_mut(&mut r);
<anon>:7 }
<anon>:5:41: 7:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 5:40
<anon>:5     let mut r: Box<Debug> = Box::new(1);
<anon>:6     let x : &mut Debug = Box::deref_mut(&mut r);
<anon>:7 }
error: aborting due to previous error
playpen: application terminated with error code 101
Compilation failed.
```

**Comment by mbrubeck** [comment] 2016-04-22 21:22
I think the problem is that `Box<Debug>` is shorthand for `Box<Debug + 'static>`, so the `deref_mut` returns `&mut (Debug + 'static)` instead of just `&mut Debug`.  This compiles:

```rust
use std::ops::DerefMut;
use std::fmt::Debug;

fn main() {
    let mut r: Box<Debug> = Box::new(1);
    let x: &mut (Debug + 'static) = Box::deref_mut(&mut r);
}
```

**Comment by eefriedman** [comment] 2016-04-22 21:27
Yes, deref_mut returns an `&mut (Debug + 'static)`... the question is why the implicit conversion isn't kicking in when it should. The following compiles:

```
use std::ops::DerefMut;
use std::fmt::Debug;

fn main() {
    let mut r: Box<Debug> = Box::new(1);
    let x = Box::deref_mut(&mut r);
    let x : &mut Debug = x;
}
```

**Comment by c4rlo** [comment] 2016-04-23 16:43
I described a closely related issue [here on the Rust user forums](https://users.rust-lang.org/t/confused-about-deref-mut/5523/4).

**Comment by Mark-Simulacrum** [comment] 2017-05-03 17:58
The original example now compiles, closing.

**Closed by Mark-Simulacrum** 2017-05-03 17:58 UTC
