### ISSUE TITLE
Add error explanations for all error codes (tracking issue).

### ISSUE THREAD

**Issue by michaelsproul** [rust-lang/rust#24407] opened 2015-04-14 07:01 UTC
This is a metabug for `rustc --explain` error descriptions.

All the errors in need of descriptions are listed in [this spreadsheet][spreadsheet]. If you'd like to help out, comment with the bunch of errors you'd like to tackle, and list yourself as assigned on the spreadsheet!

Choosing a few errors in the same file is probably a good way to start.

# How to add an error explanation

Error explanations live in `src/librustc*/diagnostics.rs`. To add a new explanation you have to delete the error from the `register_diagnostics!` invocation and add it to the `register_long_diagnostics!` invocation, along with the explanation. The format for the explanation is 80 characters per line, with a newline at the very start and end of the string. Including code examples is encouraged, with full markdown formatting (single-tick for inline, triple for blocks). Copy the format of the existing errors and you should be good!

Once you've added an explanation you can test it out by compiling and running stage1 as follows:

```shell
$ make rustc-stage1
$ export PATH=x86_64-unknown-linux-gnu/stage1/bin:$PATH
$ export LD_LIBRARY_PATH=x86_64-unknown-linux-gnu/stage1/lib:$LD_LIBRARY_PATH
$ rustc --explain EXXXX
```

If you want to see how it renders as HTML you'll have to build the error index, which requires stage2:

```shell
$ make doc/error-index.html
```

You can add `-j 4` to use 4 parallel `make` processes.

Once you're happy with the result, submit a pull request and we'll review it.

# Progress

We're tracking progress with a shared spreadsheet. If you'd like to write an error message, put your name down for one of the unassigned errors.

[Rust Error Diagnostic Spreadsheet (click me!)][spreadsheet]

As you complete error descriptions it would also be great if you could mark the errors as "merged" on the spreadsheet :smile:

[spreadsheet]: https://docs.google.com/spreadsheets/d/1Qt8Bs6qp4NLP2FYQ361CZ4U-3OsUWNCLQX3c_jGtvqM/edit?usp=sharing

**Comment by lifthrasiir** [comment] 2015-04-14 07:05
This is going to be a good effort, but do not forget to add the following lists:

* https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/diagnostics.rs
* https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/diagnostics.rs
* https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/diagnostics.rs

**Comment by michaelsproul** [comment] 2015-04-14 07:08
Thanks! I wasn't aware of those!

**Comment by lfairy** [comment] 2015-04-14 07:19
I'll take E0152 through E0170.

Question: Should I squash all the additions into a single commit, or keep them separate?

**Comment by GuillaumeGomez** [comment] 2015-04-14 07:57
I'll take E0009 (a little start to begin).

**Comment by michaelsproul** [comment] 2015-04-14 08:01
@lfairy: Either is fine. If there are logical slabs of messages that could also work well.

@GuillaumeGomez: Sounds good :smile:

**Comment by michaelsproul** [comment] 2015-04-14 08:02
Thanks!

**Comment by ruud-v-a** [comment] 2015-04-14 16:09
I’ll take E0297 through E0302 (the ones in check_match).

**Comment by lfairy** [comment] 2015-04-15 07:40
@ruud-v-a I was already working on 158/162/165 (see my comment above), but meh

**Comment by michaelsproul** [comment] 2015-04-15 07:44
Sorry Chris, I only just noticed this now... If you have anything to add to Ruud's descriptions go ahead!

I was hoping I could transform the list into a more complete one, but my script is somewhat broken so I'm looking into better ways to extract error information (uniqueness checking, finding errors without descriptions, HTML output). For now I've marked who's working on what in the current list.

**Comment by michaelsproul** [comment] 2015-04-15 07:52
I just did E0296.

**Comment by michaelsproul** [comment] 2015-04-15 08:03
I'll also take the loop ones, E0267 and E0268.

**Comment by lfairy** [comment] 2015-04-15 09:00
@michaelsproul No worries :)

I'll take E0306 and E0307.

**Comment by cactorium** [comment] 2015-04-15 11:07
Could I try E0308-E0311?

**Comment by michaelsproul** [comment] 2015-04-15 11:12
@cactorium: Go for it! :smile:

**Comment by ruud-v-a** [comment] 2015-04-15 16:34
@lfairy: oops, my apologies. I hope you don’t mind.

**Comment by nham** [comment] 2015-04-16 05:52
I've tried my hand at E0015 and E0020

**Comment by GuillaumeGomez** [comment] 2015-04-16 17:29
I now take E0012 (should I open a new PR for it or not ?).

**Comment by michaelsproul** [comment] 2015-04-17 01:14
@GuillaumeGomez: You'll need a new PR as your previous one was just approved

**Comment by GuillaumeGomez** [comment] 2015-04-17 07:42
@michaelsproul: Yes, I just saw that.

**Comment by meqif** [comment] 2015-04-18 11:09
I took a stab at E0133.

**Comment by GuillaumeGomez** [comment] 2015-04-20 10:52
I'll now take E0271.

**Comment by Manishearth** [comment] 2015-04-20 10:54
@michaelsproul Thanks for taking the reins here and coordinating everything! :smile: 

Diagnostics are an area of the compiler that could do with a lot of improvement.


:heart:

**Comment by robinst** [comment] 2015-04-28 09:34
I'm looking at E0013.

**Comment by michaelsproul** [comment] 2015-04-28 09:38
@robinst :smile:

**Comment by GuillaumeGomez** [comment] 2015-04-28 09:40
@michaelsproul: could you take a look at #24728 please ? I'm kinda stuck to see what to add and/or improve (and @pnkfelix doesn't know what would be missing).

**Comment by ruud-v-a** [comment] 2015-04-29 22:28
I encountered a very misleading instance of E0282 just yet. I’m writing the long documentation for it as we speak and I improved the error message.

By the way, if any one wants to have a go at 298, 299 or 300, feel free to do so, I have not been able to reproduce them yet.

**Comment by michaelsproul** [comment] 2015-05-07 01:24
Ok, don't be scared but I've just added error codes from the rest of the compiler...

![Progress](http://imgur.com/1eOYJxy)

Who's up for round two?

@steveklabnik could you tag this issue as E-Easy to help new people find it? Thanks :smile:

**Comment by GuillaumeGomez** [comment] 2015-05-07 08:35
Well, as soon as my current one is finished, I'm totally up to ! :-)

**Comment by nham** [comment] 2015-05-07 19:40
:scream:

I've taken a shot at E0046 and E0054

**Comment by nham** [comment] 2015-05-08 00:22
And also E0062, E0063 and E0137.

I intended to do E0136, but so far I've been unable to reproduce it. This error message is `multiple 'main' functions`, but when trying to reproduce it with:

```rust
fn main() {}
fn main() {}
```
the error you get is not E0136, but

    E0136.rs:2:1: 2:13 error: duplicate definition of value `main`
    E0136.rs:2 fn main() {}
               ^~~~~~~~~~~~
    E0136.rs:1:1: 1:13 note: first definition of value `main` here
    E0136.rs:1 fn main() {}
               ^~~~~~~~~~~~
    error: aborting due to previous error

**Comment by GuillaumeGomez** [comment] 2015-05-08 11:25
@nham: Have you tried in another file ?

**Comment by Manishearth** [comment] 2015-05-08 11:31
```
#![feature(main)]
#[main]
fn main1(){}
#[main]
fn main2(){}
```

Another file won't work, `main` is supposed to be toplevel.

**Comment by Manishearth** [comment] 2015-05-08 11:31
Oh, wait, that's E0137.

**Comment by Manishearth** [comment] 2015-05-08 12:11
It seems like E0136 may never be hit. Hm.

**Comment by caipre** [comment] 2015-05-10 01:35
Taking E0067. I'll do a few others too if I can.

**Comment by michaelsproul** [comment] 2015-05-10 05:51
@caipre: Ideally all errors that are printed by the compiler should be assigned an error code. Nobody has sat down and done it yet though.

**Comment by meqif** [comment] 2015-05-10 09:58
I just did E0317.

**Comment by nham** [comment] 2015-05-10 10:04
I'm working on:

 - E0106
 - E0107
 - E0184
 - E0204
 - E0205
 - E0206
 - E0243
 - E0244.

**Comment by michaelsproul** [comment] 2015-05-10 10:14
Awesome work everyone! :smile:

**Comment by meqif** [comment] 2015-05-10 11:29
Meanwhile, I also did E0154, E0259 and E0260.

**Comment by nham** [comment] 2015-05-11 00:01
I've also added E0249 and E0250 in https://github.com/rust-lang/rust/pull/25272

**Comment by GuillaumeGomez** [comment] 2015-05-11 18:17
I'll take E0011 to E0019.

**Comment by nham** [comment] 2015-05-12 04:48
I'm now working on:

 - E0106, E0107 (as previously mentioned)
 - E0049, E0050
 - E0066
 - E0069
 - E0166

**Comment by michaelsproul** [comment] 2015-05-12 06:42
Should we use a shared spreadsheet to keep track of things? I had a go at making one:

https://docs.google.com/spreadsheets/d/1Qt8Bs6qp4NLP2FYQ361CZ4U-3OsUWNCLQX3c_jGtvqM/edit?usp=sharing

**Comment by nham** [comment] 2015-05-12 07:08
@michaelsproul Good idea. I'll keep the spreadsheet updated for the errors I do.

**Comment by michaelsproul** [comment] 2015-05-12 07:08
@nham: Great! I'll remove the clunky check list.

**Comment by Manishearth** [comment] 2015-05-12 08:27
@michaelsproul that sounds great!

I might also start adding more diagnostics later this week, too.

Btw, since you're coordinating these, feel free to ping me when one of them needs an r+, or if you plan on rolling them up (and asking me for an r+ on your rolled up PR) :smile:

**Comment by michaelsproul** [comment] 2015-05-12 10:43
Cheers @Manishearth :smile:

**Comment by Manishearth** [comment] 2015-05-12 10:46
(Just comment `@Manishearth r+ please` or something on them -- I've been largely ignoring these PRs since I knew you were coordinating them and didn't want to cause merge conflicts by reviewing the wrong ones -- but I shouldn't have to do that ^_^)

**Comment by cactorium** [comment] 2015-05-13 04:36
I can't figure out how to trigger E0311, but I'm up for trying a couple more! Could I grab E0197-E0199?

**Comment by Manishearth** [comment] 2015-05-13 04:59
Sure; just add your name next to them in the spreadsheet above!

**Comment by nham** [comment] 2015-05-23 18:55
It looks like E0134/E0135 ("modification of string types is not allowed") may not be triggerable. These were added in https://github.com/rust-lang/rust/pull/9750, back when it was possible to index individual bytes of strings, and I don't think it's possible to do that today. The error you get instead is

```
 the trait `core::ops::Index<_>` is not implemented for the type `collections::string::String` [E0277]
```

**Comment by jashank** [comment] 2015-06-09 09:00
I'm currently working on E0038, and may have a look at the other trait stuff.

**Comment by pnkfelix** [comment] 2015-06-19 10:34
@michaelsproul a policy question: Should error explanations include references to unstable features, that is, features that are hidden behind a feature-gate, and thus are unavailable in stable and beta channels of Rust?

A concrete example of this is #26396, which is explaining E0019 (that you cannot call functions from the initializer for a const definition).  It might be good to mention `const fn` in that explanation, since they were essentially added precisely to allow such code to be written.

My first thought was that we should not include such discussion, since it would confuse people on the stable/beta channels.

But my second thought was that it is better for us to make the error explanation documentation as complete as possible, at the moment when people are working on it.  It will be harder to try to go back over previous error explanations and update them as features land.

A third thought is that we could maybe extend the error explanation infrastructure to allow for an additional documentation string that is separated from the others and is *only* printed from a Rust that is on the nightly channel.  That way, people on stable/beta won't see such messages, while the people on nightly get the benefit of seeing how new features may help them resolve their problems.

**Comment by GuillaumeGomez** [comment] 2015-06-19 10:39
@pnkfelix: Adding an additionnal string would be nice, but it'd be even nicer if in stable/beta it's printed with a warning (or something similar) in order to say "it's not possible for now but hold on! Feature is coming!".

**Comment by GuillaumeGomez** [comment] 2015-06-24 09:10
@michaelsproul: The google doc wasn't up to date so I updated it. I think it's good now.

**Comment by michaelsproul** [comment] 2015-06-24 10:23
Great!

I also realised I never commented regarding unstable features. I think Felix's reasoning is solid. I'll have a play-around with a system for printing different strings on different versions.

**Comment by Manishearth** [comment] 2015-07-11 12:12
I'm not sure how to trigger E0079, E0308 keeps getting in the way. Anyone want to try?

**Comment by cactorium** [comment] 2015-07-11 15:41
It looks like the spreadsheet says michaelsproul already finished that one

**Comment by Manishearth** [comment] 2015-07-11 15:43
I'm working on improving existing ones

-----Original Message-----

**Comment by cactorium** [comment] 2015-07-11 15:53
Ah, my bad. I got E0079 to trigger though! Does triggering both E0079 and E0308 count?

```
enum Foo {
    Q = "32"
}

fn main() {
}
```

**Comment by tshepang** [comment] 2015-07-11 18:21
playpen: http://is.gd/cAbc2m

**Comment by Manishearth** [comment] 2015-07-19 15:28
Note: I'm taking a global lock on librustc/ for a while, trying to clear up all of them in https://github.com/rust-lang/rust/issues/26963. I'll comment here when I'm done :)

**Comment by jashank** [comment] 2015-07-20 01:35
Are the explanations intended to be read at a terminal or as a webpage?

I ask, because, in the former context, some of the pseudo-Markdown constructs are harder to follow.  For example, `for _all_ possible types` clearly emphasises one word; however, `containing _every object that implements the trait_` is harder to follow given it spans multiple words (and, in the context I've lifted this from, across multiple lines). IMHO, this would be fine were there emphasis in the console context; it reads fine in the web context as emphasis can be displayed.

(It occurs to me that a way out of this is to add console escape sequences to allow bold or underlined emphasis in `rustc --explain` output...)

**Comment by Manishearth** [comment] 2015-07-20 04:14
@jashank Both.

We may add rudimentary bolding and code formatting to the console version later.

**Comment by Manishearth** [comment] 2015-07-20 04:29
(I probably should remove the long-emphasis on that sentence though)

**Comment by jashank** [comment] 2015-07-20 04:31
OK, that seems reasonable; there are a few instances of long-emphasis that could probably be removed.

**Comment by AlisdairO** [comment] 2015-07-21 10:11
I'm taking a look at 382 now.

**Comment by AlisdairO** [comment] 2015-07-21 10:12
Just a note here in addition to the spreadsheet - I note that 225 and 223 appear to be assigned to @nham and are marked as merged, but I don't see them in the latest code.

**Comment by GuillaumeGomez** [comment] 2015-07-21 10:49
Then remove him from the assignee in the spreadsheet please (or maybe @nham is still working on it?). I don't see any PR either.

**Comment by AlisdairO** [comment] 2015-07-21 10:54
Yeah, I wasn't sure if it was accidentally marked as merged, or accidentally marked as assigned too :-)

**Comment by GuillaumeGomez** [comment] 2015-07-21 10:55
Maybe both ! :p

**Comment by AlisdairO** [comment] 2015-07-21 10:59
*grins* indeed!  Perhaps I'll remove it for now, but @nham can let us know if that's wrong.

**Comment by nham** [comment] 2015-07-21 16:23
Hrmm, I do not recall trying to do anything with those error codes. It's fine for anyone else to take them.

**Comment by AlisdairO** [comment] 2015-07-21 21:20
Fab - I'll take a look at 225 then.

**Comment by AlisdairO** [comment] 2015-07-22 09:40
I'm also taking 223.

**Comment by GuillaumeGomez** [comment] 2015-07-22 09:45
@AlisdairO: You're on fire ! :D

**Comment by AlisdairO** [comment] 2015-07-22 10:12
@GuillaumeGomez thanks :D.  I have a couple of days before my first child is due to arrive, so I'm squeezing in as much as I can now, as I figure I won't have much time for a while after :-).

**Comment by GuillaumeGomez** [comment] 2015-07-22 10:18
Congrats ! \o/

**Comment by AlisdairO** [comment] 2015-07-22 17:02
Thanks @GuillaumeGomez :-)

OK, I'm going to take a look at E0281 and E0373 next

**Comment by AlisdairO** [comment] 2015-07-22 17:04
Er, wait, 281 is in librustc.  @Manishearth am I OK to take a look at that, or do you want it?  I have a simple reproduction if that would help.

**Comment by Manishearth** [comment] 2015-07-22 18:17
Take it :smile: 

if you want to do something in librustc just check my mega PR first and leave a comment.

**Comment by AlisdairO** [comment] 2015-07-22 20:23
Fab, cheers!

**Comment by AlisdairO** [comment] 2015-07-23 09:20
Simple reproduction for 387 here, since I doubt I'll get time to do it.

```
fn bar<F: Fn()>(f: F) { }

fn foo() {
    let mut x = 0i32;
    bar(|| x = 2);
}
```

**Comment by Manishearth** [comment] 2015-07-25 11:39
Releasing lock on `librustc/`

**Comment by cactorium** [comment] 2015-07-26 02:49
Gonna grab E0074-E0077

**Comment by GuillaumeGomez** [comment] 2015-07-31 11:15
I updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1Qt8Bs6qp4NLP2FYQ361CZ4U-3OsUWNCLQX3c_jGtvqM/edit#gid=0). Only a few are now remaining, good job everyone ! \o/

**Comment by AgostonSzepessy** [comment] 2015-08-02 01:07
I'll try E0384.

**Comment by AlisdairO** [comment] 2015-08-02 17:13
I'll take 387.

**Comment by AlisdairO** [comment] 2015-08-09 14:14
I'll have a go at E0193.

**Comment by AlisdairO** [comment] 2015-08-09 16:39
Taking E0194 also.

**Comment by GuillaumeGomez** [comment] 2015-08-09 18:30
The E0404 has already be done (I didn't add these errors in the spreadsheet, you have to research for them before adding them, sorry about that ^^').

**Comment by AlisdairO** [comment] 2015-08-09 18:48
Ah yes, thanks for letting me know :)

**Comment by AlisdairO** [comment] 2015-08-09 19:14
I'll also have a go at 122.

**Comment by AlisdairO** [comment] 2015-08-10 20:08
I'll also take a look at E0248.

With this one I think we now have 3/4 of the diagnostics either assigned or merged :-)

**Comment by GuillaumeGomez** [comment] 2015-08-10 20:15
@AlisdairO: A bit more. Thanks for your help !

**Comment by AlisdairO** [comment] 2015-08-10 20:27
@GuillaumeGomez it's been fun!

**Comment by GuillaumeGomez** [comment] 2015-08-10 20:41
@AlisdairO: I hope so ! :D

**Comment by Manishearth** [comment] 2015-08-11 05:53
It's probably much more than that -- I think I still need to update the spreadsheet for my librustc PR

**Comment by Manishearth** [comment] 2015-08-11 05:55
Nevermind, someone seems to have helpfully updated the spreadsheet for me (or I did it and forgot :stuck_out_tongue_closed_eyes: )

**Comment by GuillaumeGomez** [comment] 2015-08-11 07:48
@Manishearth: I did. :p

**Comment by AlisdairO** [comment] 2015-08-11 11:10
I'll give E0329 a go too.

**Comment by nathankleyn** [comment] 2015-08-12 15:47
I'm happy to take on `E0385` as a first stab at a contribution! :smiley:

**Comment by Manishearth** [comment] 2015-08-12 15:50
Great! Let us know if you need any help!

**Comment by nathankleyn** [comment] 2015-08-12 19:38
Raised a PR for `E0383` at #27699, will now take `E0386`.

**Comment by GuillaumeGomez** [comment] 2015-08-12 20:17
I forgot to said (I just updated the spreadsheet, btw, don't forget to update it people !) but I'm on all these: E0103, E0323, E0324, E0325, E0369 and E0425. [Maybe more will come](https://github.com/rust-lang/rust/pull/27586) !

**Comment by AlisdairO** [comment] 2015-08-13 09:00
Also taking 321

**Comment by AlisdairO** [comment] 2015-08-15 16:28
I'm not convinced that E0247 is possible.  Any attempt to use a module in place of a type gets captured by E0412 use of undeclared type name `{}`

**Comment by AlisdairO** [comment] 2015-08-15 16:55
Here's a reproduction of E0390 for anyone that wants it. The error looks quite general (so this is certianly not exhaustive) and I'm probably not qualified to write diagnostics about it:

```
struct Foo {
    x: i32
}
impl *mut Foo { }
```

**Comment by GuillaumeGomez** [comment] 2015-08-15 17:47
@AlisdairO: I'll give a try to E0390 then.

**Comment by AlisdairO** [comment] 2015-08-15 18:23
Commit hash faf73028c9afe5790e9b4d83a348d93e4a098852 removed E0266, so removing from spreadsheet.

**Comment by Manishearth** [comment] 2015-08-16 02:45
Its still good to have an explanation for 247, in case things get moved around in the future. Mention in a comment that the error is currently unreachable.

**Comment by AlisdairO** [comment] 2015-08-16 09:58
OK, I'll take E0247 then.

**Comment by GuillaumeGomez** [comment] 2015-08-27 13:48
@AlisdairO: Hi ! Are you still working on E0321 and E0329 ? I'd like to give them a shot if you're not. :)

**Comment by AlisdairO** [comment] 2015-08-27 20:01
hey - still on them at the moment if that's alright!

**Comment by GuillaumeGomez** [comment] 2015-08-27 20:03
No worries, since it's been 11 days, I was just asking. Take good care of your little you ! :)

**Comment by AlisdairO** [comment] 2015-08-28 17:37
thanks :)

**Comment by joelmccracken** [comment] 2015-09-10 02:28
I'd like to see some description added to a specific error message: 

https://github.com/rust-lang/rust/blob/master/src/librustc_borrowck/borrowck/gather_loans/move_error.rs#L123

I notice that this is not in the spreadsheet/no EXXXX designation is associated with it. Is there any specific reason there is no error code associated with it?

**Comment by Manishearth** [comment] 2015-09-10 02:37
@joelmccracken No reason, we should fix that. @GuillaumeGomez has been working on these

That's basically the "next step" of this issue.

 - Step 1: Explain existing error codes
 - Step 2: Add more error codes and explain them
 - Step 3: Add inline notes to errors whenever there are one or two very common, non-obvious solutions or causes

**Comment by GuillaumeGomez** [comment] 2015-09-10 10:53
I will take a more global look when I have time. Thanks for reporting this @joelmccracken.

**Comment by AlisdairO** [comment] 2015-11-06 08:40
OK, it's clearly time for me to admit that I'm not going to get 321 done - apologies!  Reproduction below:

aux321.rs:

#![feature(optin_builtin_traits)]

pub trait DefaultedTrait { } 
impl DefaultedTrait for .. { }

321.rs:

extern crate aux321;

use aux321::DefaultedTrait;
struct C;

impl DefaultedTrait for C { } 
impl <'a> DefaultedTrait for &'a C { } 
impl DefaultedTrait for Box<C> { }

-----

> rustc --crate-type=lib aux321.rs
> rustc --crate-type=lib -L . 321.rs

Should yield E0321.

**Comment by GuillaumeGomez** [comment] 2015-11-06 09:24
@AlisdairO: Thanks! I'll write in the next days then.

**Closed** 2016-04-06 19:04 UTC
Labels: E-easy, metabug
