### ISSUE TITLE
"ambiguous associated type" when there's not ambiguity

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#50905] opened 2018-05-19 21:52 UTC
```
trait Bar {
    type Baz;
}

trait Foo {
    type Bar : Bar;
}

fn _qux<F : Foo>(param: F::Bar::Baz) {}


fn main(){
}
```

```
error[E0223]: ambiguous associated type
 --> src/main.rs:9:25
  |
9 | fn _qux<F : Foo>(param: F::Bar::Baz) {}
  |                         ^^^^^^^^^^^ ambiguous associated type
  |
  = note: specify the type using the syntax `<<F as Foo>::Bar as Trait>::Baz`
```

For me it looks like there's no ambiguity here: `Foo` has only one `Bar` and `Bar` has only one `Baz`.

https://play.rust-lang.org/?gist=347da3f223a841b8ee96ee4a744ba180&version=nightly&mode=debug

**Comment by kennytm** [comment] 2018-05-20 07:15
Thanks for the report. This is a duplicate of #38078.

**Closed by kennytm** 2018-05-20 07:15 UTC
