### ISSUE TITLE
LLVM ERROR: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#40438] opened 2017-03-11 09:59 UTC
```
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.17.0-nightly (b1e31766d 2017-03-03)

$ cargo +nightly install amethyst_tools
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing amethyst_tools v0.4.0
   Compiling libc v0.2.21
   Compiling vec_map v0.4.0
   Compiling gcc v0.3.43
   Compiling podio v0.1.5
   Compiling bitflags v0.4.0
   Compiling ansi_term v0.7.5
   Compiling strsim v0.4.1
   Compiling clap v1.5.6
   Compiling time v0.1.36
   Compiling msdos_time v0.1.5
   Compiling miniz-sys v0.1.9
Instruction does not dominate all uses!
  %27 = load i32, i32* %26, !range !2
  %71 = icmp eq i32 %27, 60
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `clap`.
Build failed, waiting for other jobs to finish...
error: failed to compile `amethyst_tools v0.4.0`, intermediate artifacts can be found at `/var/folders/pr/dsmnz7795h18nncdpws5d9h00000gp/T/cargo-install.aGXBs9Cimzhk`

Caused by:
  build failed
```

**Comment by nagisa** [comment] 2017-03-11 10:51
Duplicate of https://github.com/rust-lang/rust/issues/40214.

**Closed** 2017-03-11 10:54 UTC
