### ISSUE TITLE
Rustc panics on nightly with crate interpolate

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#54654] opened 2018-09-28 21:09 UTC
```toml
interpolate = "0.2.1"
```
```rust
#[macro_use] extern crate interpolate;
```
Any idea why rustc is crashing?
```
thread 'main' panicked at 'librustc_metadata\creader.rs:531: proc-macro crate not dylib', librustc\util\bug.rs:47:26
stack backtrace:
   0: <std::sys::windows::args::Args as core::ops::drop::Drop>::drop
   1: std::io::error::Error::get_ref
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_predicate
   5: std::panicking::rust_panic_with_hook
   6: <&'tcx rustc::hir::MacroDef as rustc_metadata::index_builder::DepGraphRead>::read
   7: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::read_u64
   8: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::read_u64
   9: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::read_u64
  10: rustc_metadata::decoder::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc_metadata::decoder::DecodeContext<'a, 'tcx>>::read_u64
  11: rustc_metadata::creader::CrateLoader::process_path_extern
  12: rustc_metadata::creader::CrateLoader::process_path_extern
  13: rustc_metadata::creader::CrateLoader::new
  14: rustc_metadata::creader::CrateLoader::process_extern_crate
  15: rustc_resolve::build_reduced_graph::<impl rustc_resolve::ToNameBinding<'a> for (&'a rustc_resolve::ModuleData<'a>, rustc::ty::Visibility, syntax_pos::span_encoding::Span, syntax_pos::hygiene::Mark)>::to_name_binding
  16: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
  17: <rustc_resolve::check_unused::UnusedImportCheckVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_use_tree
  18: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_item
  19: <rustc_resolve::check_unused::UnusedImportCheckVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::visit_use_tree
  20: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a, 'crateloader>>::visit_ast_fragment_with_placeholders
  21: syntax::ext::expand::MacroExpander::expand_crate
  22: syntax::ext::expand::MacroExpander::expand_crate
  23: syntax::ext::expand::MacroExpander::expand_crate
  24: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  25: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  26: rustc_driver::driver::count_nodes
  27: rustc_driver::driver::compile_input
  28: rustc_driver::run_compiler
  29: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  30: rustc_driver::run_compiler
  31: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  32: rustc_driver::target_features::add_configuration
  33: _rust_maybe_catch_panic
  34: rustc_driver::profile::dump
  35: rustc_driver::main
  36: <unknown>
  37: std::panicking::update_panic_count
  38: _rust_maybe_catch_panic
  39: std::rt::lang_start_internal
  40: <unknown>
  41: <unknown>
  42: BaseThreadInitThunk
  43: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (90d36fb59 2018-09-13) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by pnkfelix** [comment] 2018-10-11 14:43
visited for triage at compiler meeting. Assigning to self to do initial investigation.

**Comment by pnkfelix** [comment] 2018-10-24 10:35
I have not managed to reproduce this problem.

I tried atop:

% rustc --version -v
rustc 1.30.0-nightly (90d36fb59 2018-09-13)
binary: rustc
commit-hash: 90d36fb5905bbe5004f5b465ea14b53d10dae260
commit-date: 2018-09-13
host: x86_64-unknown-linux-gnu
release: 1.30.0-nightly
LLVM version: 8.0

but no dice.

In the details block are the steps I followed:

<details>

```console
% rustup default nightly-2018-09-14
info: using existing install for 'nightly-2018-09-14-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-2018-09-14-x86_64-unknown-linux-gnu'

  nightly-2018-09-14-x86_64-unknown-linux-gnu unchanged - rustc 1.30.0-nightly (90d36fb59 2018-09-13)

% cargo new issue-54654
     Created binary (application) `issue-54654` project
% cd issue-54654/
% echo 'interpolate = "0.2.1"' >> Cargo.toml
% cat Cargo.toml
[package]
name = "issue-54654"
version = "0.1.0"
authors = ["Felix S. Klock II <pnkfelix@pnkfx.org>"]
edition = "2018"

[dependencies]
interpolate = "0.2.1"
% echo '#[macro_use] extern crate interpolate; fn main() { }' > src/main.rs
% cat src/main.rs
#[macro_use] extern crate interpolate; fn main() { }
% cargo build
    Updating crates.io index
   Compiling proc-macro2 v0.4.20
   Compiling unicode-xid v0.1.0
   Compiling quote v0.6.8
   Compiling interpolate v0.2.1
   Compiling issue-54654 v0.1.0 (file:///tmp/issue-54654)
warning: unused `#[macro_use]` import
 --> src/main.rs:1:1
  |
1 | #[macro_use] extern crate interpolate; fn main() { }
  | ^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 2.99s
%
```

</details>

----

Its *possible* that this is a windows-specific bug.

But its also possible that there are other steps necessary to reproduce.

@Boscop can you provide a full transcript of steps to reproduce.

**Comment by pnkfelix** [comment] 2018-11-07 15:14
ping @Boscop can you provide more information about how to reproduce this bug please?

**Comment by pnkfelix** [comment] 2018-11-12 10:20
Since I have not been able to reproduce and we have not received any further information on this bug,I am going to close this as non-actionable at this time.

@Boscop : if you are able to provide more precise information in the future, please do so and reopen! Thanks!

**Closed by pnkfelix** 2018-11-12 10:20 UTC
Labels: A-macros, I-ICE, T-compiler, regression-from-stable-to-beta
