### ISSUE TITLE
Panic compiling conrod example on nightly

### ISSUE THREAD

**Issue by RichardlL** [rust-lang/rust#32411] opened 2016-03-21 20:27 UTC
To Reproduce:

`git clone https://github.com/PistonDevelopers/conrod`
 `cd conrod`
`env RUST_BACKTRACE=1 cargo build --example all_widgets`

Version (Arch AUR rust-nightly-bin)
```
rustc --version --verbose 
rustc 1.9.0-nightly (b12b4e4e3 2016-03-17)
binary: rustc

commit-hash: b12b4e4e3266644d519647afc2943cefa2026e07
commit-date: 2016-03-17
host: x86_64-unknown-linux-gnu
release: 1.9.0-nightly
```

Backtrace:
```
`error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:     0x7f79622b2170 - sys::backtrace::tracing::imp::write::h495bc662e480d01f2cv
   2:     0x7f79622bc36f - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44522
   3:     0x7f79622bbee3 - panicking::default_handler::h4e73712d1e927dfeH0z
   4:     0x7f796228435c - sys_common::unwind::begin_unwind_inner::h0e1be209f5e9e87dg2t
   5:     0x7f7962285d48 - sys_common::unwind::begin_unwind_fmt::h45dc2fac9b5e0d23m1t
   6:     0x7f79622afa71 - rust_begin_unwind
   7:     0x7f7962305cff - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:     0x7f79623067f8 - panicking::panic::hf105884501521a8dcQL
   9:     0x7f795f690f5f - middle::traits::specialize::specialization_graph::Graph::parent::hfc9265d759d9ab2cDj0
  10:     0x7f795f691287 - middle::traits::specialize::specialization_graph::Ancestors<'a, 'tcx>.Iterator::next::h70e8182c7f559aafyp0
  11:     0x7f795f691495 - iter::FlatMap<I, U, F>.Iterator::next::h15606808109838973867
  12:     0x7f795f66620e - middle::traits::project::assoc_ty_def::h64968093243f2983QMV
  13:     0x7f795f661d41 - middle::traits::project::opt_normalize_projection_type::h7696c56e42bd6a4eySU
  14:     0x7f795f64e1c6 - middle::traits::project::normalize_projection_type::h2cc6c58801c4609bnRU
  15:     0x7f795f58b5ab - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::h90476939514f1d774OU
  16:     0x7f795f638214 - middle::ty::fold::TypeFolder::fold_substs::h14609565292491853112
  17:     0x7f795f637dc4 - middle::ty::structural_impls::ty..Predicate<'tcx>.TypeFoldable<'tcx>::super_fold_with::h936236069883914270
  18:     0x7f795f68a243 - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>::fold::h16191537608909884419
  19:     0x7f795f689e63 - middle::traits::select::SelectionContext<'cx, 'tcx>::impl_or_trait_obligations::_$u7b$$u7b$closure$u7d$$u7d$::closure.94594
  20:     0x7f795f688f0e - iter::FlatMap<I, U, F>.Iterator::next::h10652811352369739358
  21:     0x7f795f688003 - vec::Vec<T>.FromIterator<T>::from_iter::h16681514746883308322
  22:     0x7f795f682b56 - middle::traits::select::SelectionContext<'cx, 'tcx>::impl_or_trait_obligations::hda32593c2b0ee3995YZ
  23:     0x7f795f683475 - middle::traits::select::SelectionContext<'cx, 'tcx>::vtable_impl::h34a98e15b5ed8c1dQjZ
  24:     0x7f795f6830f5 - middle::infer::InferCtxt<'a, 'tcx>::commit_if_ok::h3903056386491528327
  25:     0x7f795f671d01 - middle::traits::select::SelectionContext<'cx, 'tcx>::confirm_candidate::hfce4534efb1aaeeevRY
  26:     0x7f795f67781e - middle::traits::select::SelectionContext<'cx, 'tcx>::evaluate_candidate::_$u7b$$u7b$closure$u7d$$u7d$::closure.94171
  27:     0x7f795f67747e - middle::traits::select::SelectionContext<'cx, 'tcx>::evaluate_stack::h7b2b9bd24fbcc30ePcX
  28:     0x7f795f6766eb - middle::traits::select::SelectionContext<'cx, 'tcx>::evaluate_predicate_recursively::hf0ebdf91a60c78d023W
  29:     0x7f795f5861e8 - middle::traits::type_known_to_meet_builtin_bound::hfe793710cf647a7ecg2
  30:     0x7f795f6ba4f1 - middle::ty::util::ty..TyS<'tcx>::impls_bound::hbe76b13567cc048aTw8
  31:     0x7f795f5865cf - middle::ty::util::ty..TyS<'tcx>::moves_by_default::h386078b8aa04fc4eaz8
  32:     0x7f795f4ddabc - middle::infer::InferCtxt<'a, 'tcx>::type_moves_by_default::h7cbe235f3d197179r3D
  33:     0x7f795f6b7974 - middle::ty::util::ParameterEnvironment<'a, 'tcx>::can_type_implement_copy::h90616c8f10b6eaf4L57
  34:     0x7f79616d19e2 - coherence::CoherenceChecker<'a, 'tcx>::check_implementations_of_copy::_$u7b$$u7b$closure$u7d$$u7d$::closure.47304
  35:     0x7f79615d280c - coherence::check_coherence::h3c7554163b347120qeB
  36:     0x7f79615cb6b8 - check_crate::h926bf7fe149773bc6KC
  37:     0x7f79627e157c - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.30393
  38:     0x7f79627dfb74 - middle::ty::context::TyCtxt<'tcx>::create_and_enter::h6220199321413035733
  39:     0x7f79627dc752 - driver::phase_3_run_analysis_passes::h12147355201479411646
  40:     0x7f79627aef4f - driver::compile_input::h80200e293207f8e6Pca
  41:     0x7f796279c81c - run_compiler::h513ed7ebfac4786dJPc
  42:     0x7f7962799ea1 - sys_common::unwind::try::try_fn::h14749382277143468613
  43:     0x7f79622af9fb - __rust_try
  44:     0x7f79622af98d - sys_common::unwind::inner_try::he9b0b11c6b5b4e7fiZt
  45:     0x7f796279a6ea - boxed::F.FnBox<A>::call_box::h2105516385435625771
  46:     0x7f79622ba479 - sys::thread::Thread::new::thread_start::hf1ffcc04a41608eb9Xy
  47:     0x7f795a9be423 - start_thread
  48:     0x7f7961f37cbc - clone
  49:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
error: Could not compile `gfx_device_gl`.

To learn more, run the command again with --verbose.
Gemeni% 
`
```

Verbose output:

```
Caused by:
  Process didn't exit successfully: `rustc /home/richard/.cargo/registry/src/github.com-88ac128001ac3a9a/gfx_device_gl-0.8.2/src/lib.rs --crate-name gfx_device_gl --crate-type lib -g -C metadata=07fad6366869f182 -C extra-filename=-07fad6366869f182 --out-dir /home/richard/git/conrod/target/debug/deps --emit=dep-info,link -L dependency=/home/richard/git/conrod/target/debug/deps -L dependency=/home/richard/git/conrod/target/debug/deps --extern gfx_gl=/home/richard/git/conrod/target/debug/deps/libgfx_gl-eed872f0f37bdbbe.rlib --extern gfx_core=/home/richard/git/conrod/target/debug/deps/libgfx_core-22c5f89dd5038dce.rlib --extern log=/home/richard/git/conrod/target/debug/deps/liblog-0ec442df0ecb416b.rlib --cap-lints allow` (exit code: 101)
```

**Comment by RichardlL** [comment] 2016-03-21 21:08
Tested on beta, no panic.

**Comment by nikomatsakis** [comment] 2016-03-22 09:37
I've noticed that conrod runs afoul of https://github.com/rust-lang/rust/issues/32330. I am investigating that now, but it might be related to this ICE. In particular, this where clause:

```rust
for<'b> I: Iterator<Item=&'b str>,
```

on line 261 is invalid. This iterator `I` is promising to produce strings of any lifetime, and hence is this where clause is really equivalent to `I: Iterator<Item=&'static str>`, which is probably not what was intended. I suspect it ought to be:

```rust
I: Iterator<Item=&'a str>,
```

Anyway, I don't know that this is related to the ICE, but thought I'd mention it.

**Comment by nikomatsakis** [comment] 2016-03-22 11:34
cc @aturon

**Comment by sanxiyn** [comment] 2016-03-22 17:29
Backtrace suggests this is #32324, which is now fixed.

**Comment by aturon** [comment] 2016-03-22 18:41
Confirmed compiles without ICE on latest nightly. Thanks for the report!

**Closed by aturon** 2016-03-22 18:41 UTC
Labels: A-traits, I-ICE, I-nominated, regression-from-stable-to-nightly
