### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: pos.get() <= self.position()'

### ISSUE THREAD

**Issue by Indy2222** [rust-lang/rust#114671] opened 2023-08-09 20:03 UTC
### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.71.1
LLVM version: 16.0.5
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling bevy_render v0.11.0
thread 'rustc' panicked at 'assertion failed: pos.get() <= self.position()', compiler/rustc_metadata/src/rmeta/encoder.rs:428:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:117:5
   3: <rustc_metadata::rmeta::encoder::EncodeContext>::encode_crate_root
   4: rustc_metadata::rmeta::encoder::encode_metadata_impl
   5: rustc_data_structures::sync::join::<rustc_metadata::rmeta::encoder::encode_metadata::{closure#0}, rustc_metadata::rmeta::encoder::encode_metadata::{closure#1}, (), ()>
   6: rustc_metadata::rmeta::encoder::encode_metadata
   7: rustc_metadata::fs::encode_and_write_metadata
   8: rustc_interface::passes::start_codegen
   9: <rustc_middle::ty::context::GlobalCtxt>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Result<alloc::boxed::Box<dyn core::any::Any>, rustc_span::ErrorGuaranteed>>
  10: <rustc_interface::queries::Queries>::ongoing_codegen
  11: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  12: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  13: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.1 (eb26296b5 2023-08-03) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on -C target-cpu=native

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `bevy_render` (lib)
```

</p>
</details>

**Comment by Indy2222** [comment] 2023-08-11 09:28
This may (and may not) have something to do with my SSD being full.

**Comment by saethlin** [comment] 2023-08-12 00:25
Did a later attempt to build the project succeed? I'm wondering if this is related to incremental compilation or not. If just a `cargo clean` then `cargo build` made the ICE go away, this is probably incr comp.

**Comment by Indy2222** [comment] 2023-08-12 16:27
> Did a later attempt to build the project without code changes succeed? I'm wondering if this is related to incremental compilation or not. If just a `cargo clean` then `cargo build` made the ICE go away, this is probably incr comp.

I run another `RUST_BACKTRACE=1 cargo build --profile testing` soon after the issue and it worked (even without cleaning).

`testing` profile from `Cargo.toml`:

```toml
[profile.testing]
inherits = "release"
opt-level = 2
debug = true
debug-assertions = true
overflow-checks = true
```

> I doubt this is out of disk. It's possible, but I've never seen an out of disk look like this.

It looked unrelated to me but added the comment for the sake of completeness.

Note that I am using `rust-analyzer` which might have somehow interfered with the compiler.

**Comment by felipelalli** [comment] 2023-08-25 06:01
> This may (and may not) have something to do with my SSD being full.

`/dev/sdb        128G  128G     0 100% /mnt/hdd_aux`
Yes.

But the error output could be easier to understand.

I have received this message:
`error: the compiler unexpectedly panicked. this is a bug.`

**Comment by saethlin** [comment] 2023-09-04 17:43
Duplicate of https://github.com/rust-lang/rust/issues/115298

**Closed** 2023-09-20 23:34 UTC
Labels: I-ICE, T-compiler, C-bug
