### ISSUE TITLE
Rustdoc doesn't explain (or can't) linking to slice methods

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#62968] opened 2019-07-25 09:27 UTC
Rustdoc documentation tells you link to an item with `[text](rust::path::to::item)`. You can even use paths appropriate to the current context to name an item, and so because `i32` and other primitives are always in scope you can point a link at `i32::abs` or whatever. However, you seemingly can't direct a link at a method of a slice because you can't name the slice primitive type.

This is maybe just a docs issue, or maybe there needs to be special handling added in some way.

**Comment by jyn514** [comment] 2020-08-25 15:38
Duplicate of #63351

**Closed by jyn514** 2020-08-25 15:38 UTC
Labels: T-rustdoc
