### ISSUE TITLE
LLVM assert on associated type with trait object.

### ISSUE THREAD

**Issue by KokaKiwi** [rust-lang/rust#21426] opened 2015-01-20 15:27 UTC
The following code:
```rust
pub fn handle(_data: &[u8]) {}

pub fn handle_opt(iter: &mut Iterator<Item = &[u8]>) {
    for data in *iter {
        handle(data);
    }
}
```

give the following LLVM assert error:
```
$ rustc --crate-type lib lib.rs
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:281: void llvm::CallInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```

I really have no idea what's the LLVM IR code generated which cause this error, as I don't know how to disable LLVM IR checks at compile-time :/

My Rust version:
```
$ rustc -Vv
rustc 1.0.0-nightly (f4f10dba2 2015-01-17 20:31:08 +0000)
binary: rustc
commit-hash: f4f10dba2975b51c2d2c92157018db3ac13d4d4a
commit-date: 2015-01-17 20:31:08 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

**Comment by theemathas** [comment] 2015-01-25 01:40
dupe of #21379

**Comment by tamird** [comment] 2015-03-15 20:39
@jakub- #21379 is a duplicate of #20605 which is closed with a test. I think this is good to close

**Comment by jakub-** [comment] 2015-03-16 08:18
@tamird Certainly. Thanks!

**Closed by jakub-** 2015-03-16 08:18 UTC
Labels: E-needstest, I-ICE
