### ISSUE TITLE
Importing from the wrong module leads to privacy error, which is unhelpful

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#57619] opened 2019-01-15 03:33 UTC
```rust
use crate::foo::Bar;

mod foo {use crate::bar::Bar;}
pub mod bar {pub struct Bar;}
```

this kind of thing happens pretty often for me, where I try importing from the wrong module.

This gives me the following error:

```
error[E0603]: struct `Bar` is private
 --> src/main.rs:3:17
  |
3 | use crate::foo::Bar;
  |                 ^^^
```

this is misleading because most Rust mental models don't consider `use` statements to be private instances, they just work that way.

Ideally, this error would notice that it's a private _use_ statement, and instead backtrack it to find the _actual_ path that should be used.

**Comment by jplatte** [comment] 2021-06-03 11:20
Duplicate of #42909?

**Closed** 2021-06-03 17:49 UTC
Labels: A-diagnostics, A-resolve, C-enhancement, D-papercut, T-compiler
