### ISSUE TITLE
src/test/rustdoc/issue-27362.rs does not pass on beta

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#32019] opened 2016-03-03 00:39 UTC
cc https://github.com/rust-lang/rust/pull/32017

This test is checking for nightly-specific behavior in rustdoc (that `const fn` is displayed), but when gating is on, rustdoc does not display `const fn`, so the test fails.

**Comment by alexcrichton** [comment] 2016-03-03 00:39
cc https://github.com/rust-lang/rust/pull/31329, the PR where this behavior changed
cc @quodlibetor (author)

**Comment by Mark-Simulacrum** [comment] 2017-04-30 20:40
I'm going to close this issue as a duplicate of https://github.com/rust-lang/rust/issues/13745, which tracks a number of tests which are currently ignored. It doesn't seem all that useful to track them separately, but let me know (and reopen) if we don't want this.

**Closed by Mark-Simulacrum** 2017-04-30 20:40 UTC
