### ISSUE TITLE
Confusing errors when deriving traits with multiple library versions

### ISSUE THREAD

**Issue by porglezomp** [rust-lang/rust#43138] opened 2017-07-10 02:02 UTC
An issue that I've dealt with a few times now is depending on a library that requires a different version of Serde, and so the `#[derive]` isn't implementing the trait to that library's satisfaction. (For instance, I had set up Serde for 1.0, but Rocket is still using 0.9.) It seems like it would be very helpful if the compiler would warn about potential version conflicts if a trait is unimplemented, but a different trait with the same name is implemented.

**Comment by Mark-Simulacrum** [comment] 2017-07-19 17:13
Closing as a duplicate of https://github.com/rust-lang/rust/issues/22750.

**Closed by Mark-Simulacrum** 2017-07-19 17:13 UTC
