### ISSUE TITLE
rustc claims that "array lengths can't depend on generic parameters" for exactly one type of expression, while various other far more complex expressions involving const generics work perfectly

### ISSUE THREAD

**Issue by slightlyoutofphase** [rust-lang/rust#63249] opened 2019-08-03 23:40 UTC
Quite simply:

The fact that [this playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c567834235a3f1354b9a96fdbedfad35) gives an error (which is literally the only syntactic way I'm aware of to get that error), while on the other hand I was able to write this [fully-working-exactly-as-written crate](https://github.com/slightlyoutofphase/staticvec) that depends heavily on the error message in question being simply untrue, seems.... weird to me.

I don't intend to come off as abrasive or anything. Really my point here is that const generics actually work great! Really great! As it stands I rarely encounter any problems with them. Which makes me think this overly-specific error message that only surfaces with one exact (very simple) way you can use const generics is some kind of overlooked leftover from earlier development.

Of course I might be wrong, and absolutely disregard this issue if that's the case!

**Comment by Centril** [comment] 2019-08-04 00:58
Duplicate of https://github.com/rust-lang/rust/issues/43408.

**Closed by Centril** 2019-08-04 00:58 UTC
Labels: A-const-generics, A-lazy-normalization, T-compiler
