### ISSUE TITLE
Build failing on linux 32-bit

### ISSUE THREAD

**Issue by ursic** [rust-lang/rust#17912] opened 2014-10-10 05:05 UTC
Linux 3.2.0-4-686-pae
````
error: failed to compress bytecode from i686-unknown-linux-gnu/stage2/lib/rustlib/i686-unknown-linux-gnu/lib/rustc-4e7c5e5c.0.bc
````

**Comment by alexcrichton** [comment] 2015-03-23 18:20
Lots of time has passed since this was opened, and we've had 32-bit builds on linux going for quite some time, so I'm going to close this since we can't seem to reproduce unfortunately.

**Closed by alexcrichton** 2015-03-23 18:20 UTC
Labels: B-reproduce

**Comment by pnkfelix** [comment] 2015-03-23 20:05
(could the PAE been an important part of that bug?)
