### ISSUE TITLE
Incremental ICE in unsafety_check_result after a crash

### ISSUE THREAD

**Issue by tux3** [rust-lang/rust#88760] opened 2021-09-08 20:27 UTC
I was running a fresh `cargo build` (full build) when my computer froze (I have one of the bad 1st gen Zen chips, I still get crashes a few times a year).  
After a restart, I get a rustc ICE every time I call `cargo build`.

### Code

The source code by itself does not repro the ICE, so I don't have any code to show.  My `target/debug` folder is 1.3GiB.
(I'd be happy to upload the target folder, though I'm not sure if that still counts as a "MVCE"!)

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (1698e3cac 2021-09-06)
binary: rustc
commit-hash: 1698e3cac54aa8691d4e9e207567672af8231cb6
commit-date: 2021-09-06
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

If this matters, the filesystem is `/dev/nvme0n1p7 on / type ext4 (rw,relatime,lazytime)`.

### Error output

```
thread 'rustc' panicked at 'attempted to read from stolen value', /rustc/1698e3cac54aa8691d4e9e207567672af8231cb6/compiler/rustc_data_structures/src/steal.rs:37:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (1698e3cac 2021-09-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 -C linker=clang -C incremental -C link-arg=-fuse-ld=/usr/local/bin/mold --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `check_attr_args`
#1 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'attempted to read from stolen value', /rustc/1698e3cac54aa8691d4e9e207567672af8231cb6/compiler/rustc_data_structures/src/steal.rs:37:21
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_mir::transform::check_unsafety::unsafety_check_result
   2: core::ops::function::FnOnce::call_once
   3: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   4: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::get_query_impl
   7: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result
   8: rustc_mir::transform::check_unsafety::check_unsafety
   9: rustc_session::utils::<impl rustc_session::session::Session>::time
  10: rustc_interface::passes::analysis
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::force_query_with_job
  14: rustc_query_system::query::plumbing::get_query_impl
  15: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  16: rustc_interface::passes::QueryContext::enter
  17: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  18: rustc_span::with_source_map
  19: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

I suspect this will not be a very common bug to hit, so I completely understand if crash proofing incremental data is *way* out of scope for rustc =)  
Thank you!

**Comment by workingjubilee** [comment] 2022-07-18 00:09
Yes, I am not sure fixing inconsistent hardware bugs is within rustc's scope. It sounds like the crash may have left the incremental cache in a corrupted state, which is something we probably _should_ guard against. But this issue still seems like it is a duplicate of either one of

-#89178
-#89197

So I am going to close this.

**Closed by workingjubilee** 2022-07-18 00:09 UTC
Labels: I-ICE, T-compiler, C-bug
