### ISSUE TITLE
Internal compiler error compiling macro_rules_attribute on mipsel-unknown-linux-musl: inconsistent resolution for an import

### ISSUE THREAD

**Issue by detly** [rust-lang/rust#78871] opened 2020-11-08 03:17 UTC
Trying to compile a project that depends on [`macro_rules_attribute`](https://docs.rs/macro_rules_attribute/0.0.1/macro_rules_attribute/), I get the following error for `mipsel-unknown-linux-musl`. No error on `stable-x86_64-unknown-linux-gnu`.

Get the toolchain for `mipsel-unknown-linux-musl`:

    rustup toolchain install stable -t mipsel-unknown-linux-musl

### src/main.rs
```rust
fn main() {
}
```

### Cargo.toml
```rust
[package]
name = "rustc-bug-test"
version = "0.1.0"
authors = ["Jason Heeris <jason.heeris@gmail.com>"]
edition = "2018"

[dependencies]
macro_rules_attribute = "0.0.1"
```

### Meta

```text
test • cargo --version
cargo 1.47.0 (f3c7e066a 2020-08-28)
test • rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)
```

Also happens in nightly:

```text
test • cargo +nightly --version
cargo 1.49.0-nightly (d5556aeb8 2020-11-04)
test • rustc +nightly --version
rustc 1.49.0-nightly (b2d115f6d 2020-11-07)
```

### Error output

Run `cargo build --target mipsel-unknown-linux-musl` and get:

```text
    Updating crates.io index
   Compiling macro_rules_attribute-proc_macro v0.0.1
   Compiling macro_rules_attribute v0.0.1
thread 'rustc' panicked at 'src/librustc_resolve/imports.rs:907:25: inconsistent resolution for an import', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/src/librustc_middle/util/bug.rs:34:26
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   2: rustc_middle::ty::context::tls::with_opt::{{closure}}
   3: rustc_middle::ty::context::tls::with_opt
   4: rustc_middle::util::bug::opt_span_bug_fmt
   5: rustc_middle::util::bug::span_bug_fmt
   6: rustc_resolve::imports::ImportResolver::finalize_import
   7: rustc_resolve::imports::ImportResolver::finalize_imports
   8: rustc_resolve::Resolver::resolve_crate
   9: rustc_interface::passes::configure_and_expand_inner
  10: rustc_interface::passes::configure_and_expand::{{closure}}
  11: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  12: rustc_interface::passes::configure_and_expand
  13: rustc_interface::queries::Queries::expansion
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: rustc_interface::interface::create_compiler_and_run
  17: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0 (18bf6b4f0 2020-10-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `macro_rules_attribute`.

To learn more, run the command again with --verbose.
```

**Comment by detly** [comment] 2020-11-08 03:23
By the way, if you know of a workaround I'd appreciate it. I don't want to replace all of these macros in my project if I can avoid it.

**Comment by jonas-schievink** [comment] 2020-11-08 03:23
Duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2020-11-08 03:23 UTC
Labels: C-bug, I-ICE, T-compiler
