### ISSUE TITLE
Rust Docs should not include internal crates

### ISSUE THREAD

**Issue by wycats** [rust-lang/rust#23772] opened 2015-03-27 01:23 UTC
For example, when I was originally searching for serialize (in the wrong place, I suppose), I got a bunch of internal results. [Link to the search](http://doc.rust-lang.org/std/index.html?search=serialize).

![std_-_rust](https://cloud.githubusercontent.com/assets/4/6860404/1c0dd730-d428-11e4-96c7-8236805dfd0e.png)

**Comment by wycats** [comment] 2015-03-27 01:23
I also feel that we should not have duplicate `core` or `std` entries.

**Comment by aturon** [comment] 2015-03-27 01:25
Paring down what shows up in rustdoc is going to be a key step for 1.0 readiness. Nominating P-high, 1.0 polish.

triage: I-nominated ()

**Comment by richo** [comment] 2015-03-27 01:29
cc me, ideally there'll be a frob to still specify the old behaviour. rustdoc has been invaluable when I'm spelunking for something.

**Comment by aturon** [comment] 2015-03-27 01:31
@richo Yes indeed, it's important that this is still available in some form for people who want to hack on Rust itself.

**Comment by bombless** [comment] 2015-03-27 05:12
>I also feel that we should not have duplicate  core  and  std  entries.

+1

**Comment by tomjakubowski** [comment] 2015-03-27 11:00
I swear there was a pretty old open issue for this already but can't find it. Also cc #22083 which is important and related.

**Comment by tomjakubowski** [comment] 2015-03-27 11:02
> I also feel that we should not have duplicate core and std entries.

This would be addressed for the common Rust user by just removing internal crates (including core) from the docs for the release channel. Nightly users, or at least users of core, and people working on the Rust distribution itself, are likely going to want to keep duplicate items between core and std.

If you initiate your search from std/core then entries in those crates will come first anyway.

**Comment by tomjakubowski** [comment] 2015-03-27 22:24
Duplicate of #21297

**Comment by cmr** [comment] 2015-03-28 21:36
I'll have a PR for this soon (it's testing)

**Closed** 2015-03-30 14:25 UTC
Labels: A-rustdoc, I-nominated
