### ISSUE TITLE
Surrounding `unsafe` blocks are ignored for `static`s

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#47864] opened 2018-01-30 02:00 UTC
```
static mut A: i32 = 0;
fn main() {
    unsafe {
        static mut B: *const i32 = &A;
    }
}
```
results in this error:
```
warning: unnecessary `unsafe` block
 --> 3:5
  |
3 |     unsafe {
  |     ^^^^^^ unnecessary `unsafe` block
  |
  = note: #[warn(unused_unsafe)] on by default

error[E0133]: use of mutable static requires unsafe function or block
 --> 4:36
  |
4 |         static mut B: *const i32 = &A;
  |                                    ^^ use of mutable static

error: aborting due to previous error
```

**Comment by dtolnay** [comment] 2018-01-30 06:52
Would you expect the `unsafe` block to apply to *all* code inside, or just initializer expressions for `static` vars?

```rust
fn main() {
    unsafe {
        struct S;
        impl S {
            fn f() {
                *std::ptr::null::<u8>(); // unsafe
            }
        }
    }
}
```

**Comment by petrochenkov** [comment] 2018-01-30 09:13
Duplicate of https://github.com/rust-lang/rust/issues/35716

Interestingly, before Rust 1.6 `unsafe` blocks worked syntactically and the code was accepted - https://godbolt.org/g/7mv1jQ.
This *probably* changed accidentally when items were outlined into side tables in HIR.

**Closed** 2018-01-30 09:17 UTC
