### ISSUE TITLE
Docs don't show that pointer::is_null() is defined only where T: Sized

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust#36952] opened 2016-10-04 07:24 UTC

**Comment by xfix** [comment] 2016-10-04 09:51
To clarify the issue, documentation says (there is also similar implementation for `mut` pointers):

```rust
impl<T> *const T where T: ?Sized
```

But that doesn't match the actual implementation where T has to be `Sized`.

**Comment by durka** [comment] 2016-10-04 16:28
There's a `T: ?Sized` on the impl, but the actual function puts back `T: Sized` and the docs don't reflect this.

**Comment by bluss** [comment] 2016-10-04 16:42
Looks like the usual cross crate doc inclusion issue. The methods are defined in core.

**Comment by Kixunil** [comment] 2017-01-19 16:59
I've just encountered this issue. [Example](https://play.rust-lang.org/?gist=d1560528d215d399310b69fb56389557&version=stable&backtrace=0).

Any explanation why `T` must impl `Sized`? What's the correct approach to null-check in case of unsized types?

**Comment by Mark-Simulacrum** [comment] 2017-07-23 23:44
Closing as a duplicate of https://github.com/rust-lang/rust/issues/24183.

**Closed by Mark-Simulacrum** 2017-07-23 23:44 UTC
Labels: A-rustdoc, T-dev-tools
