### ISSUE TITLE
macro_rules panic without parens

### ISSUE THREAD

**Issue by bombela** [rust-lang/rust#25561] opened 2015-05-18 03:54 UTC
This code panic: 

```rust
macro_rules! foo { panic => () }
```

I expected to see this happen: missing some paren error or whatnot.

Instead, this happened: rustc panic.

`rustc --version --verbose`:

```
rustc 1.0.0-beta.5 (7b4ef47b7 2015-05-11) (built 2015-05-11)
binary: rustc
commit-hash: 7b4ef47b7805a402d756fb8157101f64880a522f
commit-date: 2015-05-11
build-date: 2015-05-11
host: x86_64-unknown-linux-gnu
release: 1.0.0-beta.5
```
Backtrace:
```
panic.rs:2:1: 2:33 error: internal compiler error: wrong-structured lhs for follow check (didn't find a TtDelimited or TtSequence)
panic.rs:2 macro_rules! foo { panic => () }
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:149

stack backtrace:
   1:     0x7f287557c429 - sys::backtrace::write::h3fdf06e7a8dd7bced4r
   2:     0x7f2875584136 - panicking::on_panic::hdc3f6d7788894b93jrw
   3:     0x7f2875547442 - rt::unwind::begin_unwind_inner::h93ec8cb6029f2822t6v
   4:     0x7f2872b1943d - rt::unwind::begin_unwind::h13038079570089827110
   5:     0x7f2872b193d2 - diagnostic::SpanHandler::span_bug::h81555737e15010e3EqB
   6:     0x7f2872c39abf - ext::base::ExtCtxt<'a>::span_bug::h83c05f27f3d6160eGf5
   7:     0x7f2872c393f6 - ext::tt::macro_rules::compile::h719307be0e0bc895Ckg
   8:     0x7f2872c38947 - ext::base::ExtCtxt<'a>::insert_macro::h3e1cd3e1c35c95casd5
   9:     0x7f2872cb8a42 - ext::expand::expand_item_mac::h38e3342682123271phb
  10:     0x7f2872ca8c20 - ext::expand::expand_annotatable::h476ee514bdcba4c3RLb
  11:     0x7f2872ca52be - ext::expand::expand_item::h3b9780ee2f6fd19eobb
  12:     0x7f2872cb1733 - iter::FlatMap<I, U, F>.Iterator::next::h3819157999333414927
  13:     0x7f2872cb1376 - vec::Vec<T>.FromIterator<T>::from_iter::h12843141179828651520
  14:     0x7f2872cacd9a - ext::expand::expand_item_underscore::h38a39a2241f9eadb0eb
  15:     0x7f2872d004b5 - fold::noop_fold_item_simple::h11776238884599738326
  16:     0x7f2872d002ba - ptr::P<T>::map::h16801527598131395308
  17:     0x7f2872ca9e76 - ext::expand::expand_annotatable::h476ee514bdcba4c3RLb
  18:     0x7f2872ca52be - ext::expand::expand_item::h3b9780ee2f6fd19eobb
  19:     0x7f2872d07491 - ext::expand::expand_crate::h6fa7cf76905f3408U8b
  20:     0x7f2875afc677 - driver::phase_2_configure_and_expand::closure.20241
  21:     0x7f2875ab1523 - driver::phase_2_configure_and_expand::h4743fcc3024e97e8Wsa
  22:     0x7f2875a9fb0d - driver::compile_input::hc5c2173550d25b21Qba
  23:     0x7f2875b62551 - run_compiler::h5fd7a3cba8c0dcd3z4b
  24:     0x7f2875b601a2 - boxed::F.FnBox<A>::call_box::h13268679164253669965
  25:     0x7f2875b5f6d9 - rt::unwind::try::try_fn::h1333595601538020842
  26:     0x7f28755f6aa8 - rust_try_inner
  27:     0x7f28755f6a95 - rust_try
  28:     0x7f2875b5f988 - boxed::F.FnBox<A>::call_box::h18060233810932446010
  29:     0x7f2875583021 - sys::thread::create::thread_start::h7002e49f5ed4f198aqv
  30:     0x7f286fe0ce99 - start_thread
  31:     0x7f28751cd38c - <unknown>
```

**Comment by Stebalien** [comment] 2015-05-19 01:50
Probably a dup of #25529

**Comment by alexcrichton** [comment] 2015-06-12 17:10
Agreed! (also a dupe of https://github.com/rust-lang/rust/issues/23389)

**Closed by alexcrichton** 2015-06-12 17:10 UTC
Labels: A-macros, I-ICE, T-compiler
