### ISSUE TITLE
RawVec growth strategy can be more efficient

### ISSUE THREAD

**Issue by handsomefox** [rust-lang/rust#111307] opened 2023-05-06 23:22 UTC
Currently, the RawVec implementation tries to double its internal capacity every time it has to grow, as can be seen in: https://github.com/rust-lang/rust/blob/31a4f2da575f5e335bdbbe7f12a694f9e74ad0a1/library/alloc/src/raw_vec.rs#L398

But, according to [Facebook's FBVector memory handling](https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md#memory-handling): it is suboptimal, as "[it can be mathematically proven that a growth factor of 2 is rigorously the worst possible because it never allows the vector to reuse any of its previously-allocated memory](https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md#memory-handling:~:text=it%20can%20be%20mathematically%20proven%20that%20a%20growth%20factor%20of%202%20is%20rigorously%20the%20worst%20possible%20because%20it%20never%20allows%20the%20vector%20to%20reuse%20any%20of%20its%20previously%2Dallocated%20memory)" because ["any new chunk requested will be larger than all previously used chunks combined, so the vector must crawl forward in memory; it can't move back to its deallocated chunks. But any number smaller than 2 guarantees that you'll at some point be able to reuse the previous chunks."](https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md#memory-handling:~:text=any%20new%20chunk%20requested%20will%20be%20larger%20than%20all%20previously%20used%20chunks%20combined%2C%20so%20the%20vector%20must%20crawl%20forward%20in%20memory%3B%20it%20can%27t%20move%20back%20to%20its%20deallocated%20chunks.%20But%20any%20number%20smaller%20than%202%20guarantees%20that%20you%27ll%20at%20some%20point%20be%20able%20to%20reuse%20the%20previous%20chunks.)

They use [a growth factor of 1.5](https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md#memory-handling:~:text=fbvector%20uses%20a%20growth%20factor%20of%201.5).

Maybe it is worth considering changing the growth factor for the standard library to a theoretically more optimal value.

**Comment by workingjubilee** [comment] 2023-05-07 01:55
In practice, changes like this have been attempted, and yielded nontrivial perf regressions in the compiler: 
- https://github.com/rust-lang/rust/pull/108718
- https://github.com/rust-lang/rust/pull/101341

As there is certainly not a shortage of Vecs in the compiler, it's reasonable to believe that this may not be a worthwhile improvement, as it trades off a potentially significant amount of runtime. However if someone can provide evidence otherwise, e.g. that the compiler is somehow distinct from every other common user of Vec, or if there is some conjoined changeset that makes this into an actual improvement, this remains open to change.

Obviously there is some reason to believe that the space efficiency is improved. However, it is enormously common for Vec to be used for small amounts, such that SmallVec is a significant optimization. We avoid the claim FB makes (that size is never reused) partly by simply allocating a nonzero capacity if the programmer hasn't requested a more specific size and is doing a first-time push:

https://github.com/rust-lang/rust/blob/a77c552485a19245a266bc03c450676c666b605f/library/alloc/src/raw_vec.rs#L104-L116

Notably, there are two possible biases here: the compiler is a batch-processing program, so its performance relies heavily on quickly allocating a lot of memory, so time efficiency matters. Facebook has a number of different programs they are interested in, but a fairly notable one for their C++ code (especially the many years ago that was written...) is a nontrivial server architecture, where data structures can be incredibly long-lived, thus space efficiency matters. Many programs instead live between these two.

I am closing this, but only because it is a duplicate of https://github.com/rust-lang/rust/issues/29931

**Closed by workingjubilee** 2023-05-07 01:55 UTC
