### ISSUE TITLE
FnOnce internal compiler bug

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#29321] opened 2015-10-26 13:19 UTC
It fails to compile `FnOnce impl`.
Code that does not compile
```
#![feature(unboxed_closures)]
#![feature(core)]

struct Data {
    identifier: String,
}

impl FnOnce<u64> for Data {
    type Output = u64;
    
    extern "rust-call" fn call_once(self, arg: u64) -> Self::Output {
        arg
    }
}

fn main() {
}
```
Code that compiles
```
#![feature(unboxed_closures)]
#![feature(core)]

struct Data {
    identifier: String,
}

impl FnOnce<(u64,)> for Data {
    type Output = u64;
    
    extern "rust-call" fn call_once(self, args: (u64,)) -> Self::Output {
        args.0
    }
}

fn main() {
}
```
Error message is not helpful.

**Comment by apasel422** [comment] 2015-10-26 13:24
This ICEs with `error: internal compiler error: argument to function with "rust-call" ABI is neither a tuple nor unit`, which is a duplicate of #22565 and #21139.

**Closed by apasel422** 2015-10-26 13:24 UTC
