### ISSUE TITLE
Doesn't work with Visual Studio 2017

### ISSUE THREAD

**Issue by CorruptComputer** [rust-lang/rust#38931] opened 2017-01-08 20:52 UTC
I have VS 2017RC installed, and running 'cargo build' gives an error, saying I need to install Visual Studio.

**Comment by est31** [comment] 2017-01-08 21:30
Dupe of #38584

**Comment by retep998** [comment] 2017-01-09 00:35
Rust works fine with Visual Studio 2017, it just doesn't automatically detect it yet. Use a vcvars bat file, or the VS developer command prompt, to get the environment setup with the right environment variables so Rust can invoke the linker correctly.

Closing as dupe.

**Closed by retep998** 2017-01-09 00:35 UTC
