### ISSUE TITLE
Unparseable type suggested in error message

### ISSUE THREAD

**Issue by mulkieran** [rust-lang/rust#40859] opened 2017-03-27 17:25 UTC
```
fn m(var: &[&mut u8]) {
    for i in var.iter_mut() {
        **i = 4;
    }
}

fn main() {
    let mut a = 1;
    let mut b = 2;
    let mut c = 3;
    let mut v = vec![&mut a, &mut b, &mut c];
    
    m(&mut v);
    println!("{:?}", v);
}
```

Gives error:

```
rustc 1.17.0-nightly (7846dbe0c 2017-03-26)
error: cannot borrow immutable borrowed content `*var` as mutable
 --> <anon>:2:14
  |
1 | fn m(var: &[&mut u8]) {
  |           ---------- use `&mut [&mut mut u8]` here to make mutable
2 |     for i in var.iter_mut() {
  |              ^^^ cannot borrow as mutable

error: aborting due to previous error
```

It suggests the type ```&mut [&mut mut u8]``` but that is not a valid Rust type. Happens in stable, beta, nightly.

**Comment by nagisa** [comment] 2017-03-27 18:27
Duplicate of https://github.com/rust-lang/rust/issues/40823.

**Comment by cuviper** [comment] 2017-03-28 18:37
#40823 says it only happens on nightly, but the example here does indeed have the same problem on stable and beta too, so maybe it's not actually a duplicate.  Here it is on the [playground](https://is.gd/6mPqCV).

```
rustc 1.16.0 (30cf806ef 2017-03-10)
error: cannot borrow immutable borrowed content `*var` as mutable
 --> <anon>:2:14
  |
1 | fn m(var: &[&mut u8]) {
  |           ---------- use `&mut [&mut mut u8]` here to make mutable
2 |     for i in var.iter_mut() {
  |              ^^^ cannot borrow as mutable

error: aborting due to previous error
```

**Closed** 2017-03-29 17:59 UTC
