### ISSUE TITLE
possible bug in procedural macro implementation?

### ISSUE THREAD

**Issue by db48x** [rust-lang/rust#47341] opened 2018-01-10 23:16 UTC
I wrote a procedural macro which emits code containing a reference to `std::foo::bar`, and got this error:

    error[E0433]: failed to resolve. Could not find `std` in `{{root}}`
     --> src/lib.rs:4:1
      |
    4 | #[lisp_fn]
      | ^^^^^^^^^^ Could not find `std` in `{{root}}`

I've made a simplified testcase and put it online at <https://github.com/db48x/legendary-octo-bassoon>; if you check it out and run `cargo test`, you'll see the same error message. Obviously the testcase itself could be at fault, but it doesn't seem likely.

**Comment by pietroalbini** [comment] 2018-02-06 16:45
Duplicate of #47314.

**Closed by pietroalbini** 2018-02-06 16:45 UTC
