### ISSUE TITLE
The implementation of `InPlaceIterable` for `Peekable` is unsound

### ISSUE THREAD

**Issue by SkiFire13** [rust-lang/rust#85322] opened 2021-05-15 10:59 UTC
This code leads to an out of bounds write, makes the assert fail and triggers miri:

```rust
fn main() {
    let v = vec![0; 5];
    let mut i = v.into_iter().peekable();
    i.peek();
    let v = i.clone().collect::<Vec<_>>();
    assert!(v.len() <= v.capacity());
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d5ae04e3e0e8609192bea44fd6782f55)

The problem is that after cloning a `Peekable` the inner iterator can no longer be considered advanced, but the `Peekable` may still yield the peeked element without advancing it, thus breaking the contract of `InPlaceIterable`.

**Comment by the8472** [comment] 2021-05-15 17:20
This can be fixed by either removing `InPlaceIterable` from `Peekable` or by changing the `Clone` impl of `IntoIter` to clone the exact state of `IntoIter` rather than allocating a smaller one. The latter may be unnecessarily costly when cloning a mostly-exhausted iterator, but on the other hand it would preserve the optimization.
So I'd try the first one first and do a perf run to see what the impact is (when it was introduced it mostly helped rustdoc) and try the latter if there's a significant regression.

**Comment by the8472** [comment] 2021-05-15 17:37
It may also be possible to fix this by specializing `Clone` on `Peekable` to look into its `SourceIter` (if available).
I'll see if specialization is powerful enough to pull that off.

**Comment by the8472** [comment] 2021-05-15 17:46
Hrm, I think it would be possible to do that but it would require some additional helper traits or methods tailored to just this use-case since `core` doesn't know about `alloc`. That's probably too much hackery for this optimiation.

**Comment by aDotInTheVoid** [comment] 2021-05-15 22:34
This also effects stable

https://godbolt.org/z/4P5sbP6xf

@rustbot modify lables: +regression-from-stable-to-stable

**Comment by hameerabbasi** [comment] 2021-05-18 12:25
Is it a regression though?

Marking as `P-critical` according to the [discussion in WG-prio](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2385322.20The.20implementation.20of.20.60InPlaceIterable.60.20for.20.60Peekabl.E2.80.A6).

@rustbot modify labels -I-prioritize +P-critical

**Comment by SkiFire13** [comment] 2021-05-18 13:06
> Is it a regression though?

Technically when #70793 was merged it broke any code that used code like this (which is not that unexpected like exploting panics and stuff like that). In fact I found this bug due to a project written in only safe rust code that was segfaulting

**Closed** 2021-05-20 00:21 UTC
Labels: C-bug, I-unsound 💥, P-critical, T-libs-impl, regression-from-stable-to-stable
