### ISSUE TITLE
Use const generics for stdarch intrinsics

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#83167] opened 2021-03-15 19:51 UTC
# Background

https://github.com/rust-lang/stdarch/issues/248

`core::arch` contains architecture-specific vendor intrinsics, some of which have arguments that are required to be compile-time constants. This is tricky because LLVM will often assert/ICE if a constant is not passed into the LLVM intrinsic at the LLVM IR level. This was previously handled by using a `match` statement to manually monomorphize the intrinsic:

```rust
#[inline]
#[target_feature(enable = "sse")]
#[cfg_attr(test, assert_instr(shufps, mask = 3))]
#[rustc_args_required_const(2)]
#[stable(feature = "simd_x86", since = "1.27.0")]
pub unsafe fn _mm_shuffle_ps(a: __m128, b: __m128, mask: i32) -> __m128 {
    let mask = (mask & 0xFF) as u8;

    macro_rules! shuffle_done {
        ($x01:expr, $x23:expr, $x45:expr, $x67:expr) => {
            simd_shuffle4(a, b, [$x01, $x23, $x45, $x67])
        };
    }
    macro_rules! shuffle_x67 {
        ($x01:expr, $x23:expr, $x45:expr) => {
            match (mask >> 6) & 0b11 {
                0b00 => shuffle_done!($x01, $x23, $x45, 4),
                0b01 => shuffle_done!($x01, $x23, $x45, 5),
                0b10 => shuffle_done!($x01, $x23, $x45, 6),
                _ => shuffle_done!($x01, $x23, $x45, 7),
            }
        };
    }
    macro_rules! shuffle_x45 {
        ($x01:expr, $x23:expr) => {
            match (mask >> 4) & 0b11 {
                0b00 => shuffle_x67!($x01, $x23, 4),
                0b01 => shuffle_x67!($x01, $x23, 5),
                0b10 => shuffle_x67!($x01, $x23, 6),
                _ => shuffle_x67!($x01, $x23, 7),
            }
        };
    }
    macro_rules! shuffle_x23 {
        ($x01:expr) => {
            match (mask >> 2) & 0b11 {
                0b00 => shuffle_x45!($x01, 0),
                0b01 => shuffle_x45!($x01, 1),
                0b10 => shuffle_x45!($x01, 2),
                _ => shuffle_x45!($x01, 3),
            }
        };
    }
    match mask & 0b11 {
        0b00 => shuffle_x23!(0),
        0b01 => shuffle_x23!(1),
        0b10 => shuffle_x23!(2),
        _ => shuffle_x23!(3),
    }
}
```

The downside of this approach is that it generates huge MIR and severely bloats the size of `libcore` to the point where it actually affects compilation time.

The `#[rustc_args_required_const]` attribute was used to restrict arguments to constants so that we could eventually replace this with const generics. Note that it effectively only acts as a hard lint, the `match` is still needed to manually monomorphize the LLVM intrinsic.

# New const generics support

https://github.com/rust-lang/stdarch/issues/1022

All the intrinsics in `stdarch` have been converted to use the newly stabilized const generics:

```rust
#[inline]
#[target_feature(enable = "sse")]
#[cfg_attr(test, assert_instr(shufps, mask = 3))]
#[rustc_legacy_const_generics(2)]
#[stable(feature = "simd_x86", since = "1.27.0")]
pub unsafe fn _mm_shuffle_ps<const mask: i32>(a: __m128, b: __m128) -> __m128 {
    static_assert!(mask: i32 where mask >= 0 && mask <= 255);
    simd_shuffle4(
        a,
        b,
        [
            mask as u32 & 0b11,
            (mask as u32 >> 2) & 0b11,
            ((mask as u32 >> 4) & 0b11) + 4,
            ((mask as u32 >> 6) & 0b11) + 4,
        ],
    )
}
```

To preserve backwards compatibility with the already stabilized intrinsics using `#[rustc_args_required_const]`, a new attribute `#[rustc_legacy_const_generics]` was added in #82447 which rewrites function calls of the form `func(a, b, c)` to `func::<{b}>(a, c)`.

This new attribute is not intended to ever be stabilized, it is only intended for use in `stdarch` as a replacement for `#[rustc_args_required_const]`.

```rust
#[rustc_legacy_const_generics(1)]
pub fn foo<const Y: usize>(x: usize, z: usize) -> [usize; 3] {
    [x, Y, z]
}

fn main() {
    assert_eq!(foo(0 + 0, 1 + 1, 2 + 2), [0, 2, 4]);
    assert_eq!(foo::<{1 + 1}>(0 + 0, 2 + 2), [0, 2, 4]);
}
```

# Open questions/issues

- `#[rustc_args_required_const]` allowed constant expressions derived from generic arguments in the caller, but this is not allowed with const generics. This technically makes this a breaking change.
- Another potential breaking change is that the intrinsics now use a post-monomorphization `static_assert` to validate constant arguments. Previously, intrinsics would either use runtime asserts or simply pick an arbitrary default behavior for out-of-range constants.
- Do we want to force all callers to use the const generics syntax in the 2021 edition?
  - Pros:
    - It makes it clearer that these intrinsics expect a constant as an argument.
    - Intrinsics are rendered with the const generics syntax in rustdoc.
  - Cons:
    - We will still need to support the `#[rustc_legacy_const_generics]` argument rewriting anyways for 2015/2018 code.
    - Intrinsics no longer have the same function signature as the original C vendor intrinsics.

**Comment by bstrie** [comment] 2021-03-17 20:50
Apparently the implementation of this so far reduces the size of libcore from 58MB to 40MB, which is still pretty substantial. Is this an acceptable size? Is there reason to think this will shrink further in the future?

**Comment by Amanieu** [comment] 2021-03-17 21:04
All of the functions have been converted to const generics, so I don't expect any further shrinkage.

**Comment by tmiasko** [comment] 2021-03-17 21:05
The `libcore_arch.rlib` is around 17 MB now.

**Comment by lqd** [comment] 2021-03-17 21:06
That size comment was about the size of `libcore_arch.rlib`, not `libcore` per se, and was before we had converted the huge AVX512 intrinsics: the latest size I saw during conversion was around 16MB.

**Comment by nikomatsakis** [comment] 2021-03-22 15:44
In the Edition 2021 meeting, @m-ou-se mentioned that the libs team had this idea as a compromise:

* New edition only accepts proper rust syntax (2nd one)
* But produce a warning with a machine applicable fix from the 1st one

**Comment by joshtriplett** [comment] 2021-03-23 21:03
We discussed this in today's @rust-lang/lang meeting. In today's discussion, there was some debate about this migration, particularly since we already need to maintain the `rustc_legacy_const_generics` mechanism indefinitely to support existing code.

We would, ideally, love to get some feedback from existing users of the SIMD intrinsics, perhaps by asking the maintainers of crates that use intrinsics such as `_mm_shuffle_ps`; perhaps a search through crates.io for occurrences of any of the intrinsics requiring a const parameter could turn up such usage. We'd also love to get some feedback from developers of tools that operate on Rust code, regarding the difficulty of supporting this.

On balance, we may potentially want to support this on an ongoing basis, in order to match the vendor intrinsics documentation, and in particular the argument order. There was concern that people *reading* such code would find that code harder to follow if the arguments in a different order.

The possibility also came up (though there was not consensus on it) of providing a macro for each such intrinsic, and rustfix-ing code using the function to use the macro rather than using const generics syntax.

**Comment by bstrie** [comment] 2021-03-23 21:21
A macro seems like the most principled way of doing this, especially considering that these are also implemented via macros in C. It would resolve the tension between wanting these APIs to look idiomatic vs wanting them to exactly mirror the vendor documentation. That sure would be a whole lot of macros, though...

**Comment by Mark-Simulacrum** [comment] 2021-03-23 21:47
I personally think that we should use the 'legacy' attribute on all intrinsics (both existing and potentially ones added in the future) that need the compile-time generic argument.

The intrinsics API has been designed to match the platform API (in particular, usually the one available in C), and the choice was explicitly made to note deviate from the vendor intrinsics in naming or calling convention. It would be odd, IMO, to change that choice in the case of the subset of intrinsics which need compile-time arguments. I think that these intrinsics are already pretty hard to read and changing the argument order by pulling out compile-time arguments is likely to be relatively painful for users, particularly if trying to align C and Rust code.

And since we have to support the legacy syntax on *some* intrinsics, I think it would be preferable to support it on all intrinsics, to avoid some having one API and some having a different API. Splitting the intrinsics into two groups just based on their stabilization date seems quite strange and not easily learnable by users.

I also think adding macros here may not necessarily be a bad idea, but it would be a lot of macros, and these intrinsics are not all that different compared to other intrinsics from the caller's perspective AFAIK -- Intel just made the choice to not embed the compile-time constant in the *name* of the intrinsic, as is done for some of the other implicit constants. Deviating for some intrinsics to macros seems like it needlessly complicates the interface; and moving *all* intrinsics to macros feels pretty obviously the wrong choice, and not very Rust-y.

It was proposed that we deprecate (i.e., with a warning) the non-const-generic invocation (i.e. where all arguments are given inside the parens, including the compile-time ones), which I think would cause needless churn -- there's not really anything wrong with the way these intrinsics have been called up until now.

Plus, I think there's some possibility that we may eventually want to add support for passing const values as function parameters (which would desugar to generics), similar to how we have added `foo: impl Trait` -- if we do, then there would be a potentially much smaller surface area of 'special case' added by these legacy attributes, and potentially they'd be entirely removable. While I don't think we should try to design that now, I do think it's meaningful to say that the idea is not entirely unlikely.

One thing I did think of is that we may want to consider that eventually the function-argument position for const generics may want to gain a `const { }` block around it to avoid an implicit promotion context that may otherwise exist. That may mitigate some of the concerns we had around tooling supporting in the meeting.

**Comment by bstrie** [comment] 2021-03-23 22:48
> there's not really anything wrong with the way these intrinsics have been called up until now.

That may not be entirely true; I have heard that the magical nature of these functions is a pain point for the IDE use case.

**Comment by nikomatsakis** [comment] 2021-03-24 19:35
I'd like to hear some folks who are creating tooling weigh in on that point. I was saying in the meeting that it seemed like two sets of people are affected by this:

* those *using* the intrinsics;
* tool makers, who have to consider all the edge cases of the language.

For most other folks, it hardly matters.

One other thing to consider is that we may want to support this use case natively at some point. I could imagine supporting something like 

```rust
fn shuffle(x: u32, const y: u32) { }
```

or -- perhaps closer to what is being proposed here --

```rust
fn shuffle<const N:usize>(x: u32, y: =N) { }
```

Obviously i don't want to block progress on some wild new features, it's just that I can imagine going the other way, and making this feature be something that people can use in all APIs to improve inference and make them more ergonomic.

**Comment by nikomatsakis** [comment] 2021-03-24 19:37
That said, having let this sit, I'm somewhat inclined to get stricter in Rust 2021, and we could always get loose again. But I would very much like to hear from affected users to have a sense of whether it will be a pain. I agree with @Mark-Simulacrum that trying to make the intrinsics match the documentation precisely was a design goal, and it does seem like a bit of a shame to give it up, especially given that we have to have the backwards compatibility code anyway. (On the other hand, if we get stricter in Rust 2021+, we may find we can remove that code at some point.)

**Comment by luojia65** [comment] 2021-03-26 16:42
This is remarkably convenient in RISC-V's vector V instruction set. V set contains [tons of](https://github.com/riscv/rvv-intrinsic-doc/blob/master/intrinsic_funcs/00_rvv_c_type_system.md) types and functions where it would not be clear to just make a huge list for all of them.

**Comment by nikomatsakis** [comment] 2021-03-26 19:53
@luojia65 can you elaborate on that? Do you mean specifically that being able to invoke the functions without using "turbofish syntax" is remarkable convenient?

**Comment by Lokathor** [comment] 2021-04-13 18:31
Hello. Maintainer of [safe_arch](https://github.com/lokathor/safe_arch). It covers all safe-able Stable intrinsics. As people have notes, many functions have been exposed via macro_rules.

Just this past weekend I've been updating it to use min_const_generics.

My impression is that the basic code readability is going *down* the more I convert and update things to the const generic version.

**Comment by nikomatsakis** [comment] 2021-04-13 18:38
@Lokathor and therefore you might prefer to keep the "in-place call" notation?

**Comment by Lokathor** [comment] 2021-04-13 18:50
Yeah.

The big problem is that turbofish is cute and I'll fight anyone who tries to remove it, but also it's cute because it's rare. Having to put a turbofish on every single call to a function quickly becomes a chore, and so far I'm not even writing "real usage code", just converting doc tests to integration tests.

That said I will continue to convert the crate to min_const_generics to not use macro_rules because for the purposes of wrapping unsafe code a function call is a much sturdier thing to trust than a macro_rules expansion (even if you think you probably really locked down that macro).

However, the long term "what makes const generics good to use with function calls?" solution will essentially require that the const value be passable within the parameters instead of as a turbofish. Anything less just reads super poorly for functions in in a way that doesn't happen as badly for types because types can infer or be trivially aliased, and functions not so much.

**Comment by nikomatsakis** [comment] 2021-04-14 15:02
> However, the long term "what makes const generics good to use with function calls?" solution will essentially require that the const value be passable within the parameters instead of as a turbofish. Anything less just reads super poorly for functions in a way that doesn't happen as badly for types because types can infer or be trivially aliased, and functions not so much.

This is roughly my opinion. I think we're going to want this feature sooner or later in some form. That is partly why I'm ok leaving this hack in for the time being.

**Comment by Mark-Simulacrum** [comment] 2021-04-14 15:54
The language team discussed this in the last triage meeting (8 days ago). The feeling was that additional feedback is going to be hard to source without active investment, and the status quo is quite reasonable to leave until the next edition (e.g., 2024). Indeed, some people in the room (e.g., me) felt that the legacy syntax is *better*, and should be preferred; feedback since then from @Lokathor continues to agree with this.

So, the current (meeting) consensus in the lang team was that we'd un-nominate this issue for the time being. We didn't feel there was a need to take action before the 2021 edition to deprecate and/or remove this pattern; it seemed fine to continue with the status quo.

However, one thing I'm not realizing we did *not* discuss, and seems like we may want an FCP for, is whether the legacy attribute should be added to not-yet stabilized intrinsics, or kept strictly to things that we cannot change due to backwards compatibility concerns. There was some discussion a few weeks back on this, but I don't believe there were firm conclusions from that discussion (even in the room). @rust-lang/lang -- I think an async FCP may be good here, but we may want some discussion as to which of these options to prefer. Libs may also have an opinion here.

1. Preserve exact status-quo. Do not stabilize any new intrinsics/functions using the legacy attribute, which enables both const-generic call syntax (i.e., turbofish) and parameter-as-const-value call syntax.
2. Newly added intrinsics stabilized with the legacy attribute.

(1) is, in my opinion, not really coherent. We don't gain anything by refusing to add more legacy attributes -- there are already 1424 instances of the legacy attribute on master stdarch (though not all may be on stable functions, I'd need to do more work to check that). We *do* gain overall cohesion with (2), though, as users can always use the same syntax to call any intrinsic. I wouldn't suggest expanding that to more general std/core functions (e.g., iterator methods) at this time, but intrinsics are always a bit special and IMO it makes sense to have a uniform calling syntax there (well, two alternatives, but still).

**Comment by Lokathor** [comment] 2021-04-14 16:04
I agree with (2). All of stdarch should use the same legacy attribute for consistency across the module. As was mentioned earlier in the thread: in a few years no one will care what historical order the intrinsics stabilized in as an explanation for an inconsistency, they will just see the inconsistency and consider it an annoying weird rule.

**Comment by nikomatsakis** [comment] 2021-04-19 20:13
I also agree with (2), for the obvious reasons.

**Comment by nikomatsakis** [comment] 2021-04-19 20:16
We also discussed this in our Edition 2021 meeting. We were considering removing this from the list of 2021 Edition candidates as a decision doesn't appear to be even close and our deadline has long since passed, but we were saying that we might want to have some more explicit decision from the teams to leave things as they are for Rust 2021 at least.  

That said, I'm not sure that an FCP makes sense, since this seems to be the status quo, and it's more that an FCP would be required to prevent it.

I will say that I personally am inclined **against** making changes here. I think the current form is more ergonomic and rather than forcing people to migrate, I would like to consider whether we can rationalize the form so that more functions can enjoy this property (as @Lokathor mentioned).

I would be happy to revisit the question after more progress on const generics and so forth has been made.

**Comment by nikomatsakis** [comment] 2021-04-19 20:25
I guess that thinking more about this, there is a decision to be made, to expose the new forms to the users. There is also a bit of a backwards compatibility question, in that it's unclear whether we wish to support `foo::<{b}>(a, c)` form (as opposed to, say, `foo::<{b}>(a, b, c)` or `foo(a, b, c)`). Supporting the form where the parameter is not provided at all somewhat constraints what future language developments might look like (I'm imagining, for example, that we might have a parameter whose "type" indicates that it is an "integer that equals the constant C", sort of like `fn foo<const C: usize>(len: =C)`, in which case passing a value for `len` would probably be mandatory).

So here are the range of behaviors we might choose:

1. Support `foo(a, b, c)` form on stable but keep `foo::<{b}>(a, c)` unstable (my preference).
2. Support both `foo(a, b, c)` and `foo::<{b}>(a, c)` on stable (not my preference, as I believe it interferes with possible future developments).
3. Support `foo(a, b, c)` form only on Rust 2018 and earlier, and require `foo::<{b}>(a, c)` in the future (not my preference because it seems strictly less ergonomic, also may present a problem if we try to rationalize it later, so likely to live on indefinitely as a special case).

There is also the "almost orthogonal" question of whether to apply the above policies only to *existing* intrinsics or also to newer ones. I'm inclined to be consistent across *all* SIMD intrinsics, regardless of when they were added, unless we opt for option 3 (in which case we are already migrating folks).

I think the main argument in favor of 3 is that it keeps the overall language smaller. This argument assumes we would never want to have a way to invoke functions with const generic arguments inline, but I am not convinced this is true (and I consider it quite likely to be false). 

Random observation that you can already write code like this ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b3f17c32213fb22804bad531db5fd130)):

```rust
fn foo<const C: usize>(x: Option<[u8; C]>) { }

fn main() {
    foo(None::<[u8; 22]>) // basically a way of specifying that `C = 22` without using turbofish
}
```

so it's not a huge stretch to imagine something like `x: C` working somehow.

**Comment by lqd** [comment] 2021-04-20 19:49
I've watched the 2021-04-06 lang meeting discussing this topic, and there was no mention of the open questions/issues in the OP, especially the fact that this is technically a breaking change. 

A crater run was done in [#83278](https://github.com/rust-lang/rust/pull/83278#issuecomment-821303273), with only around 4 root crates and overall 50 regressions. 2 of these 4 root regressions were fixed already, and semver-compatible versions released. A PR was opened for the 3rd.

Is this a concern for t-libs, a concern for t-lang, or not a concern given those crater results ?

**Comment by nikomatsakis** [comment] 2021-04-20 19:52
@lqd I was under the impression that the breaking change was not expected to occur in practice, but I guess this is not entirely true.

**Comment by Amanieu** [comment] 2021-04-20 19:54
That is the source of breakage for 2 of the crates. The other 2 were due to a missing `#[rustc_args_required_const]` on one of the previously stabilized intrinsics.

**Comment by nikomatsakis** [comment] 2021-04-20 19:57
@Amanieu I see. Does that mean that the const is not, in fact, required by the underlying LLVM intrinsic? Or was it that the optimizer was able to eventually figure out that the value is constant?

**Comment by lqd** [comment] 2021-04-20 20:22
I don't know about LLVM's behaviour for the intrinsic here, but the one case I fixed (the 2 already-fixed crates were the ones using the 2 intrinsics missing the `#[rustc_args_required_const]` attribute) was a simple shift with a constant, which I've seen LLVM optimize easily before.

**Comment by Amanieu** [comment] 2021-04-20 20:53
I did a bit of research on that specific intrinsic: [officially](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_srli_epi32) the argument of `_mm256_srli_epi32` must be a constant, but GCC, Clang and ICC all allow specifying a runtime value, in which case it is internally converted to use `_mm256_srl_epi32` which takes a vector argument that holds the shift value.

Note that the SSE2 variant of this instruction (`_mm_srli_epi32`) *does* have `rustc_args_required_const`.

**Comment by nikomatsakis** [comment] 2021-04-21 23:03
@lqd @Amanieu is a shift with a constant not a constant expression?

**Comment by lqd** [comment] 2021-04-22 07:44
@nikomatsakis yes, but to be clear it is the lack of `#[rustc_args_required_const]` in the 2 stable intrinsics which allowed this case to happen (not the switch to const generics): by using a custom type and `Shr` impl where it called the intrinsic, this case turned the constant used in the shift expressions into a runtime value in the impl.

**Comment by nikomatsakis** [comment] 2021-04-22 18:13
@lqd I admit I don't really understand. Is there a good link to the error etc?

**Comment by lqd** [comment] 2021-04-22 20:35
So there are a couple sources of breaking changes in the `stdarch` bump that have been hit in the crater run:
- one is related to using associated consts of generic parameters
- the other one is that a few shift-related AVX2 intrinsics were stabilized without the `#[rustc_args_required_const]` attribute that ensures the immediates are constants. Two of those were hit in the crater run, and I'll explain those below.

https://github.com/rust-lang/stdarch/pull/1025/files#diff-95541a10736e81b6d3dd51a3a94005c39f9ebc49fdf44c2956f925f74c39183a is Amanieu's PR noticing and fixing this by updating these intrinsics to const generics: they added the `#[rustc_legacy_const_generics]` attribute which for all intents and purposes in this explanation is the same as if they had only added the missing `#[rustc_args_required_const]` attribute.

[Here's an example](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=b2e1e20deb99afba21071095823a37be) of the difference on stable: the AVX2 example compiles even though the immediate is not a constant, while the SSE2 version only compiles when passed a constant immediate. (Amanieu explained above why it can also run fine).

The crater cases were very similar to these examples:
- different versions of `simdeez`: [using `_mm256_srli_epi32`](https://github.com/jackmott/simdeez/blob/796ac4d7817f066b5ccc2a7b11fdca67d83da192/src/avx2/avx2.rs#L530-L533) which caused [this error](https://crater-reports.s3.amazonaws.com/pr-83278/try%239cae4dca0b4ddbfe82616f4d5f1090fc817e2ffa/reg/simdeez-1.0.6/log.txt) for example on simdeez-1.0.6
```
error[E0435]: attempt to use a non-constant value in a constant
[INFO] [stdout]    --> src/avx2/avx2.rs:527:38
[INFO] [stdout]     |
[INFO] [stdout] 521 |               let mask = _mm256_setr_epi32(0, -1, 0, -1, 0, -1, 0, -1); // mask for high part containing only sign
[INFO] [stdout]     |  ______________-
[INFO] [stdout] 522 | |             Self::blendv_epi64(I64x4(sra3), I64x4(sign), I64x4(mask))
[INFO] [stdout] 523 | |         }
[INFO] [stdout] 524 | |     }
[INFO] [stdout] 525 | |     #[inline(always)]
[INFO] [stdout] 526 | |     unsafe fn srli_epi32(a: Self::Vi32, amt_const: i32) -> Self::Vi32 {
[INFO] [stdout]     | |_________________________________________________- help: consider using `const` instead of `let`: `const amt_const`
[INFO] [stdout] 527 |           I32x8(_mm256_srli_epi32(a.0, amt_const))
[INFO] [stdout]     |                                        ^^^^^^^^^ non-constant value
```
- `highway-0.6.3`: [using `_mm256_srli_epi64`](https://github.com/nickbabcock/highway-rs/blob/68ce47adaa4fd5a0b0c3cc9db8994254e1e2b1e8/src/v4x64u.rs#L170-L178) in the `Shr` impl of their custom vector type and which caused [this error](https://crater-reports.s3.amazonaws.com/pr-83278/try%239cae4dca0b4ddbfe82616f4d5f1090fc817e2ffa/reg/highway-0.6.3/log.txt)
```
error[E0435]: attempt to use a non-constant value in a constant
[INFO] [stdout]    --> src/v4x64u.rs:175:52
[INFO] [stdout]     |
[INFO] [stdout] 164 |           let mut new = V4x64U(self.0);
[INFO] [stdout]     |  __________-
[INFO] [stdout] 165 | |         new ^= other;
[INFO] [stdout] 166 | |         new
[INFO] [stdout] 167 | |     }
[INFO] [stdout] ...   |
[INFO] [stdout] 172 | |
[INFO] [stdout] 173 | |     fn shr(self, shift: i32) -> Self {
[INFO] [stdout]     | |______________________- help: consider using `const` instead of `let`: `const shift`
[INFO] [stdout] 174 |           let mut new = V4x64U(self.0);
[INFO] [stdout] 175 |           unsafe { new.0 = _mm256_srli_epi64(self.0, shift) }
[INFO] [stdout]     |                                                      ^^^^^ non-constant value
``` 

`simdeez` also uses the same technique as `stdarch` used to (before the switch to const generics) to ensure the immediates are effectively constant: a [macro covering all the values the immediate can take](https://github.com/jackmott/simdeez/blob/796ac4d7817f066b5ccc2a7b11fdca67d83da192/src/macros.rs#L9) and so [their fix](https://github.com/jackmott/simdeez/commit/2bd23df3068512172f44a663c6939440d6563139#diff-24d7b54d4b18942a95306088e6c4cd6e1e90267d616feb9a5b3b0629f9966ad4) was to use this for the intrinsic that should have required it.

`highway` does not use such a heavy trick (and funnily enough the author had noticed the discrepancy between their SSE and AVX code implementations, only the AVX code path could have that `Shr` impl). Since their only use of this custom operator was [with a constant shift amount](https://github.com/nickbabcock/highway-rs/blob/68ce47adaa4fd5a0b0c3cc9db8994254e1e2b1e8/src/avx.rs#L214-L222) it was easy to remove. 

I've seen LLVM excel in optimizing similar mathematical expressions with constants before, even with custom operators like `highway` did, and that could explain why the crates work fine today. But it seems that even if that's not the case, Amanieu's investigation shows that at least some of these intrinsics were made to handle runtime values instead of only constant immediates as one would expect from the official docs.

**Comment by Amanieu** [comment] 2021-05-13 18:22
I think there are two remaining issues that need to be addressed before this reaches stable:
- We've decided to continue allowing these intrinsics to be called with the old syntax in the 2021 edition. Should we also allow calling these intrinsics with the const generics syntax?
- Should we change rustdoc to render the const generics differently when `#[rustc_legacy_const_generics]` is present?

**Comment by RalfJung** [comment] 2021-05-14 14:25
> before this reaches stable

This has landed just after the recent beta cut, right? So it'll reach stable in 11 weeks, on July 29th?

**Comment by nikomatsakis** [comment] 2021-05-15 08:38
> We've decided to continue allowing these intrinsics to be called with the old syntax in the 2021 edition. Should we also allow calling these intrinsics with the const generics syntax?

I'm inclined not to support it, to give ourselves more room to design a first-class feature around this.

**Comment by RalfJung** [comment] 2021-05-15 09:32
I was briefly *very* confused by the term "intrinsics" here. These are not intrinsics in the rustc sense, are they? They are just regular functions? The true intrinsics are an internal implementation detail of stdarch, not visible to the user? Might be better to not call them "intrinsics" then in the rustc issue tracker...

**Comment by RalfJung** [comment] 2021-05-15 14:44
Another example of code that compiles on stable but not on nightly:
```rust
use std::arch::x86_64::*;
use std::mem::transmute;

#[target_feature(enable = "sse2")]
pub unsafe fn sse_constant_shift<const N: i32>(a: __m128i) {
    let x = 2;
    let r = _mm_slli_epi16(a, 4+N);
}
```

**Comment by bstrie** [comment] 2021-05-15 17:22
> I'm inclined not to support it, to give ourselves more room to design a first-class feature around this.

In particular it would be consistent for a hypothetical const-param-in-argument-position to act similarly to impl-trait-in-argument-position, where `fn foo(x: impl Bar)` can't be invoked as `foo::<Qux>()` (arguably this restriction is controversial, but it can always be lifted later).

**Comment by Lokathor** [comment] 2021-05-15 18:19
> I was briefly very confused by the term "intrinsics" here.

All the rust docs call them arch intrinsics, cpu intrinsics, or vendor intrinsics. It's simply the term for them by now, that train has long left the station.

**Comment by RalfJung** [comment] 2021-05-15 18:52
"arch intrinsics" is much less confusing than just plain "intrinsics". :)
I assume when reading the issue front-to-back this is clear from context, but when coming back to this discussion after weeks and just reading the last 2 or 3 messages, being more explicit helps.

**Comment by Amanieu** [comment] 2021-05-15 18:54
> Another example of code that compiles on stable but not on nightly:

We checked for this in crater and only 2 crates were affected. Both have since been fixed to work around this issue.

**Comment by RalfJung** [comment] 2021-05-15 19:21
Ah, and I guess those failures would be caught even by the check-only run.

**Comment by Mark-Simulacrum** [comment] 2021-07-15 22:57
> Should we change rustdoc to render the const generics differently when #[rustc_legacy_const_generics] is present?

I think there should be *some* indication that the "legacy" call signature is allowed. Perhaps even defaulting to that rendering would be preferable, given that it matches both (a) historical practice in Rust and (b) the convention in C or C++ when invoking these intrinsics.

@rust-lang/rustdoc, given that this is in 1.54 which ships in 2 weeks, do we think we can create a patch that adds some indication to the rendering by then? Right now a page for these intrinsics (e.g., https://doc.rust-lang.org/beta/core/arch/x86_64/fn._mm256_mask_extracti32x4_epi32.html) doesn't give any indication that both calling modes are supported, which seems quite confusing for any user coming across a call in the old convention.

@Amanieu Is it intentional that e.g. https://doc.rust-lang.org/stable/core/arch/x86_64/fn._mm256_mask_extracti32x4_epi32.html references "imm8" as the name of the parameter, but the const generic has now changed this to [IMM1](https://doc.rust-lang.org/beta/core/arch/x86_64/fn._mm256_mask_extracti32x4_epi32.html)? I am surprised to see us rewriting Intel's docs and names, given that the idea with x86_64 intrinsics was to try and stay "as close as possible" to the canonical names from the intel docs...

**Comment by Manishearth** [comment] 2021-07-15 23:12
> do we think we can create a patch that adds some indication to the rendering by then?

Maybe ... what kind of UI do you expect here?

**Comment by Mark-Simulacrum** [comment] 2021-07-15 23:22
I think there's a couple options:

1. Render them as-if they were still in the old format (i.e., re-inline the const generic, perhaps as something like `fn foo(const name: ty)` rather than `fn foo<const name: ty>()`).
2. Add a box like the unstable/target feature/etc with a note like "this function is also callable with the generic inline with the arguments"
   * it's not very clear how to indicate which argument with this form. Maybe something like "with the const generic as the 5th argument" could work, though.

I'm likely at least a little biased, but since I recall some expression from some members of @rust-lang/lang in meetings on this of potentially wanting to add the "not genericy" name as a stable alternative/feature instead of the #[rustc_legacy_const(...)] attributes, I'd probably roughly suggest option one. Maybe folks on T-libs or T-lang have opinions though.

**Comment by Manishearth** [comment] 2021-07-15 23:26
> it's not very clear how to indicate which argument with this form. Maybe something like "with the const generic as the 5th argument" could work, though.


a really cool way to do this would be to have this annotation, and you can _click it_ to swap the signature.

**Comment by GuillaumeGomez** [comment] 2021-07-16 09:18
> > it's not very clear how to indicate which argument with this form. Maybe something like "with the const generic as the 5th argument" could work, though.
> 
> a really cool way to do this would be to have this annotation, and you can _click it_ to swap the signature.

Let's try to keep the UI as simple as possible (even though that sounds good). :laughing: 

Once we've reached a consensus on the what the UI should look like, I can send a PR if you want.

**Comment by lqd** [comment] 2021-07-16 09:21
Note: Intel only uses the `imm8` name, and documents its acceptable width in the documentation, and in the guide's xml data like so: `<parameter type="int" varname="imm8" etype="IMM" immwidth="1"/>`.

**Comment by Mark-Simulacrum** [comment] 2021-07-26 19:50
I was not aware of that context, thanks @lqd -- in that case I think the names seem like an improvement indeed. Maybe we can put a quick section in the root (e.g., https://doc.rust-lang.org/nightly/core/arch/x86_64/index.html and https://doc.rust-lang.org/nightly/core/arch/x86/index.html) that mentions that the names of immediate parameters describe their widths (imm1 -> 1 bit, etc.)? Could help readers who are broadly unfamiliar otherwise.

I would still like to see improvements to the rendered documentation, though.

**Comment by GuillaumeGomez** [comment] 2021-10-15 21:18
Without checking too much, I think it wouldn't be too complicated. To be confirmed. I'll work on it in the following days.

**Closed** 2021-12-03 01:04 UTC
Labels: T-rustdoc, T-lang, T-libs-api, relnotes
