### ISSUE TITLE
Incremental compiliation is ineffective when building compiler

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#55500] opened 2018-10-30 07:23 UTC
Rebuilding the compiler took 15 minutes after simply running `touch` on a file. Given that nothing has actually changed, I would expect that rebuilding would be much faster.

Steps to reproduce:
1. Clone the `rust` repository.
2. Set `incremental = true` in the `rust` section of `config.toml`.
3. Run `./x.py clean` if you've previously built the compiler
4. Run `./x.py build`
5. Run `touch src/librustc/traits/auto_trait.rs`
6. Run `./x.py build` again.

The second `./x.py build` invocation takes *much* longer than it should (~15 minutes on my machine), considering that the only thing that's changed is a file timestamp.

**Comment by pnkfelix** [comment] 2019-06-06 12:24
It would be worth trying to figure out whether this phenomenon is due to some problem specific in the rustbuild bootstrap process, or if it something that affects other clients using incremental compilation (and therefore would be a potential blocker for turning on incremental in release mode, cc #57968)

**Comment by pnkfelix** [comment] 2020-10-06 12:50
discussed at wg-incr-comp meeting.

We think that the issue as described here is probably largely an artifact of the build process discussed above is building all the way to stage 2, which A. imposes work that is hard to avoid (at least automatically), and B. is no longer the default in x.py for rustc development, and thus should not be affecting most rustc developers.

closing as (presumed) "fixed" or at least "not a bug for wg-incr-comp"...

**Closed by pnkfelix** 2020-10-06 12:50 UTC
Labels: A-incr-comp, A-rustbuild, I-compiletime, T-compiler, WG-incr-comp
