### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by asdfasfdqw** [rust-lang/rust#34466] opened 2016-06-25 12:18 UTC
He says it's a bug, so. Panic while running following code:
```rust
use std::vec::IntoIter;

pub fn get_tok(it: &mut IntoIter<u8>) {
    let mut found_e = false;

    let temp: Vec<u8> = it.take_while(|&x| {
            if x != b'e' {
                true
            } else {
                found_e = true;
                false
            }
        })
        .cloned()
        .collect();
}

fn main() {
    let bc_str = b"qwe";
    get_tok(&mut bc_str.into_iter());
}
````
## Meta
`rustc --version --verbose`

```
rustc 1.11.0-nightly (ad7fe6521 2016-06-23)
binary: rustc
commit-hash: ad7fe6521b8a59d84102113ad660edb21de2cba6
commit-date: 2016-06-23
host: i686-pc-windows-gnu
release: 1.11.0-nightly
```

Backtrace:

`rustc main.rs`

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'begin <= end (163 <= 104) when slicing `type mismatch resolving `<std::iter::TakeWhile<&mut std::vec::IntoIter<u8>, [closure@main.rs:6:39: 13:10 found_e:_]> as std::iter::Iterator>::Item == &_`: expected u8, found &-ptr`', ../src/libcore\str/mod.rs:1709
stack backtrace:
   0: 0x6c93e24d - <unknown>
   1: 0x6c90459e - <unknown>
   2: 0x6c97d8cf - <unknown>
   3: 0x6c93fdb7 - <unknown>
   4: 0x6c90650c - <unknown>
   5: 0xff0dda5e - <unknown>
   6: 0xff18feda - <unknown>
```

**Comment by arielb1** [comment] 2016-07-08 19:25
This is the funky error message parsing logic looking for "expected" and "found".

**Comment by arielb1** [comment] 2016-07-08 20:11
duplicate of #31173.

**Closed by arielb1** 2016-07-08 20:11 UTC
Labels: I-ICE
