### ISSUE TITLE
Cycle detected when const-evaluating

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#67245] opened 2019-12-12 00:58 UTC
Only happens with `const_generics`.

Couldn't find anything related. Feel free to close this issue if it is duplicated.

```rust
#![feature(const_generics)]

fn foo<F>(bar: &mut [u8; 8], mut cb: F)
where
    F: FnMut(&mut [u8; 8]),
{
    cb(bar);
}
```

```rust
error[E0391]: cycle detected when const-evaluating + checking `foo::{{constant}}#0`
 --> src/lib.rs:5:24
  |
5 |     F: FnMut(&mut [u8; 8]),
  |                        ^
  |
note: ...which requires const-evaluating + checking `foo::{{constant}}#0`...
 --> src/lib.rs:5:24
  |
5 |     F: FnMut(&mut [u8; 8]),
  |                        ^
note: ...which requires const-evaluating `foo::{{constant}}#0`...
 --> src/lib.rs:5:24
  |
5 |     F: FnMut(&mut [u8; 8]),
  |                        ^
note: ...which requires processing `foo::{{constant}}#0`...
 --> src/lib.rs:5:24
  |
5 |     F: FnMut(&mut [u8; 8]),
  |                        ^
note: ...which requires processing `foo::{{constant}}#0`...
 --> src/lib.rs:5:24
  |
5 |     F: FnMut(&mut [u8; 8]),
  |                        ^
  = note: ...which again requires const-evaluating + checking `foo::{{constant}}#0`, completing the cycle
note: cycle used when processing `foo`
 --> src/lib.rs:3:1
  |
3 | / fn foo<F>(bar: &mut [u8; 8], mut cb: F)
4 | | where
5 | |     F: FnMut(&mut [u8; 8]),
6 | | {
7 | |     cb(bar);
8 | | }
  | |_^
```

**Comment by jonas-schievink** [comment] 2019-12-12 10:35
Duplicate of https://github.com/rust-lang/rust/issues/67185#issuecomment-564841120

**Closed by jonas-schievink** 2019-12-12 10:35 UTC
Labels: A-const-generics, C-bug, F-const_generics, T-compiler, requires-nightly
