### ISSUE TITLE
Tracking issue for Finalize defaulted type parameters (RFC 213)

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#21939] opened 2015-02-04 18:52 UTC
Tracking issue for Finalize defaulted type parameters, [RFC 213](https://github.com/rust-lang/rfcs/pull/213).

**Comment by aidanhs** [comment] 2016-01-28 23:24
Isn't this a duplicate of #27336?

This one was created first so I guess that one would be the dupe, but that has more discussion? Though this has more issues referencing it.

**Comment by nikomatsakis** [comment] 2016-02-01 20:22
Seems to be, a duplicate, yes.

**Closed** 2016-02-22 15:02 UTC
Labels: A-typesystem, B-RFC-approved, T-lang
