### ISSUE TITLE
u128::count_ones is broken on aarch64-unknown-none-softfloat

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#80374] opened 2020-12-26 01:54 UTC
```
#![no_std]

pub fn u128_count_ones(x: u128) -> u32 {
    x.count_ones()
}
```
when compiled with `cargo build --target aarch64-unknown-none-softfloat` it gives:
```
error: could not compile `testlib`

Caused by:
  process didn't exit successfully: `rustc --crate-name testlib --edition=2018 src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=ec790c6e5e4455bc -C extra-filename=-ec790c6e5e4455bc --out-dir C:\Users\aaron\Documents\github\testlib\target\aarch64-unknown-none-softfloat\debug\deps --target aarch64-unknown-none-softfloat -C incremental=C:\Users\aaron\Documents\github\testlib\target\aarch64-unknown-none-softfloat\debug\incremental -L dependency=C:\Users\aaron\Documents\github\testlib\target\aarch64-unknown-none-softfloat\debug\deps -L dependency=C:\Users\aaron\Documents\github\testlib\target\debug\deps` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
This is preventing upgrading the `compiler-builtins` used by rustc. See https://github.com/rust-lang/compiler-builtins/issues/398 and https://github.com/rust-lang/rust/pull/79863.

**Comment by LeSeulArtichaut** [comment] 2020-12-26 14:39
From the backtrace in https://github.com/rust-lang/compiler-builtins/issues/398#issuecomment-749219253, this appears to be a LLVM issue?

**Comment by nikic** [comment] 2020-12-26 14:57
IR test case (still reproduces on LLVM master):

```
; RUN: llc -mtriple=aarch64 -mattr=-neon < %s
define i128 @test(i128 %i) {
  %c = call i128 @llvm.ctpop(i128 %i)
  ret i128 %c
}

declare i128 @llvm.ctpop(i128)
```

**Comment by nikic** [comment] 2020-12-26 15:03
The problem is that https://github.com/llvm/llvm-project/blob/b21840751278128ef6942074ae89ea63c9c6ac58/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L15907-L15909 does not check whether the LowerCTPOP() call is successful and pushes an empty SDValue as the result.

**Comment by AaronKutch** [comment] 2020-12-26 17:06
I was able to remove the reference to `u128::count_ones` in `compiler-builtins`, so this isn't a severe issue. But, it should definitely be fixed quickly so that future versions of LLVM are fixed.

**Comment by nikic** [comment] 2020-12-26 20:39
I've put up https://reviews.llvm.org/D93825.

**Comment by nikic** [comment] 2021-03-14 20:06
This should be fixed on nightly, as a result of the LLVM 12 upgrade.

**Comment by est31** [comment] 2021-05-25 00:34
Can this be closed? Should one revert https://github.com/rust-lang/compiler-builtins/pull/399  to make sure the bug is fixed?

**Comment by nikic** [comment] 2021-08-28 13:09
Closing this as the upstream issue is fixed and we have long since updated to LLVM 12.

**Closed by nikic** 2021-08-28 13:09 UTC
Labels: A-LLVM, O-ARM, T-compiler, C-bug, T-libs
