### ISSUE TITLE
Template structures deriving `Clone` unreasonably require the template type to implement `Clone`

### ISSUE THREAD

**Issue by popzxc** [rust-lang/rust#70466] opened 2020-03-27 11:26 UTC
For template structures, which only use the type parameter to have a reference, deriving `Clone` does not seem to work properly (or at least works counterintuitively).

Simplified example:

```rust
struct NonCloneableStruct;

#[derive(Clone)]
struct DeriveCloneStruct<'a, T> {
    reference: &'a T,
}

fn main() {
    let object = NonCloneableStruct;

    let derive_object = DeriveCloneStruct {
        reference: &object,
    };
    
    // V-- Does not work.
    let _ = derive_object.clone();
}
```

The code above produces the following compile error:

```sh
   |
4  | struct DeriveCloneStruct<'a, T> {
   | ------------------------------- method `clone` not found for this
...
34 |     let _ = derive_object.clone();
   |                           ^^^^^ method not found in `DeriveCloneStruct<'_, NonCloneableStruct>`
   |
   = note: the method `clone` exists but the following trait bounds were not satisfied:
           `DeriveCloneStruct<'_, NonCloneableStruct> : std::clone::Clone`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `clone`, perhaps you need to implement it:
           candidate #1: `std::clone::Clone`
```

Since we only have a reference, this field can be just copied, and `Clone` implementation of `T` is not required.

And indeed, the manual `Clone` implementation` works just fine:

```rust
struct NonCloneableStruct;

struct ManualCloneImplementStruct<'a, T> {
    reference: &'a T,
}

impl<'a, T> Clone for ManualCloneImplementStruct<'a, T> {
    fn clone(&self) -> Self {
        Self {
            reference: self.reference,
        }
    }
}

fn main() {
    let object = NonCloneableStruct;

    let manual_object = ManualCloneImplementStruct {
        reference: &object,
    };
    
    // Works as expected.
    let _ = manual_object.clone();
}
```

[Link to the playground with this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc9236b7d32a579261ffd44edd60381b).

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

The same behaviour is observed on the `nightly`.

**Comment by jonas-schievink** [comment] 2020-03-27 11:28
duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2020-03-27 11:28 UTC
Labels: C-bug
