### ISSUE TITLE
compilation time hit from recent PR

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54083] opened 2018-09-09 14:19 UTC
Sadly, https://github.com/rust-lang/rust/pull/53949 seems to have been [very bad for compilation times](https://perf.rust-lang.org/compare.html?start=0198a1ea45e29af00d92423aa6d2ac876410c3f9&end=004bc5a33cd44cd0896cae917a75488579126da5&stat=instructions%3Au). I think we have to back it out until we find a way to do it more efficiently. :(

cc @estebank

**Comment by michaelwoerister** [comment] 2018-09-09 19:12
> tuple-stress-check:
> avg: 9711.2% | min: 6519.9% | max: 18808.1%
> avg: 9721.3% | min: 6350.5% | max: 17849.0%
> avg: 9692.6% | min: 6351.6% | max: 17734.3%

Woooooooooooooooooooooowwwwww!! `:)`

**Comment by estebank** [comment] 2018-09-09 21:30
> And here I was, all excited about the latest nll-dashboard results, which showed e.g. html5ever at at 1.01x ratio

> Woooooooooooooooooooooowwwwww!! :)

I feel like I deserve some kind of badge for this ^_^

> Sadly, #53949 seems to have been very bad for compilation times. I think we have to back it out until we find a way to do it more efficiently. :(

I'm pretty sure that the [check for margins in every close delimiter](https://github.com/rust-lang/rust/pull/53949/files#diff-1a14c281236eed1dcb52dd68eb43cc7eR94) is to blame. This could be moved to instead collect all the matching delimiter spans and check the left padding _only in the case of mismatched braces_. This should fix the performance regression for all cases, while keeping the behavior on bad code, at the expense of keeping a vec of _all_ braces' opening and closing span (instead of only the "suspicious" ones). I will be in flight until tomorrow afternoon. If the performance regression needs to be fixed before then, please revert the PR, otherwise I'll make the appropriate change (assuming I'm correct).

**Comment by michaelwoerister** [comment] 2018-09-11 15:35
perf.rust-lang.org looks like it's back to normal again. Thanks for fixing, @estebank!

**Closed by michaelwoerister** 2018-09-11 15:35 UTC
Labels: I-compiletime, P-high, T-compiler, regression-from-stable-to-nightly

**Comment by estebank** [comment] 2018-09-11 16:09
@michaelwoerister sorry to cause the epic slowdown to begin with :)
