### ISSUE TITLE
rustdoc source view: hover gap in file picker

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#100421] opened 2022-08-11 18:45 UTC
Steps to reproduce:

1. Visit https://doc.rust-lang.org/nightly/src/alloc/string.rs.html#2453
2. In the sidebar, hover mouse over "alloc". Note that mouse indicates a clickable item.
3. Slowly move the mouse leftwards towards the disclosure element (▶).
4. Note that at some point, the mouse hits a dead zone where it is no longer over a clickable item. When this happens, clicking does nothing.
5. If you continue moving the mouse leftwards, onto the disclosure element, it will indicate a clickable item again, and clicking it will open/close the folder.

Expected results:

The whole line, including the disclosure element and the folder name, should be clickable.

**Comment by GuillaumeGomez** [comment] 2022-08-23 09:45
I can't reproduce this bug. It is using `<details>` now, not sure if it was merged before or after you opened this issue though. Can you double-check you still have it please?

**Comment by jsha** [comment] 2022-08-26 15:05
This still reproduces for me. I forgot to mention: this is in Chrome on Linux.

**Closed** 2022-10-09 21:02 UTC
Labels: T-rustdoc, A-rustdoc-ui
