### ISSUE TITLE
Move out the std lib to crates.io

### ISSUE THREAD

**Issue by Binero** [rust-lang/rust#21822] opened 2015-01-31 23:21 UTC
I believe that it's a better choice to have the std library on crates.io, instead of in /usr/local. It makes it easier to have alternative standard libraries, and the compilers shouldn't really link with it automatically anyway. It also makes it easier to build for new targets, making cross compilation multiple grades of magnitude easier. 

The standard library requires on a rust version, but implementing a rustc version requirement shouldn't be too hard. 

The only argument I've so far heard against this, is that it'd require people to update their Cargo.lock if they are using cargo, or manually update the std if they are not. While this is true, most people *will* be using cargo or a dependency manager, and updating the lock file shouldn't be an issue.

Today I heard rust prefers explicit over implicit. Not implicitly linking against all the standard libraries would follow this.

**Comment by reem** [comment] 2015-01-31 23:25
The main technical issue I see with this is difficulty with bootstrapping.

In terms of non-technical issues, I see the standard libraries as being an extremely paired-down set of stuff almost every rust program is going to use. Forcing everyone to add std as a dependency, link against it, then import the prelude in every module is just a pain.

**Comment by richo** [comment] 2015-01-31 23:25
This probably warrants an RFC, however:

I strongly disagree. In my opinion the rust distribution should be independently useful, and a standard library should go along with a stable release of the language and compiler.

A good example of this is the amount of Boost that is making it's way into the C++ standard.

**Comment by steveklabnik** [comment] 2015-01-31 23:25
Closing as a duplicate of https://github.com/rust-lang/rust/issues/19314

**Closed by steveklabnik** 2015-01-31 23:25 UTC

**Comment by steveklabnik** [comment] 2015-01-31 23:26
Ehhh it's only _close_ to being a duplicate, there are some small differences. But there are significant technical issues here, and I would argue that this requires an RFC.

**Comment by steveklabnik** [comment] 2015-01-31 23:28
https://github.com/rust-lang/rust/issues/19240 was the other issue that's almost but not quite a dup here
