### ISSUE TITLE
Type mismatch in `for`'s pattern shows wrong type of iterator

### ISSUE THREAD

**Issue by jakubdabek** [rust-lang/rust#89052] opened 2021-09-17 18:54 UTC
Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5f0e3783d3fd771e9c586cb386bf5615)):

```rust
fn main() {
    let xs = Some(vec![(1, "abc")]);
    let (x, y) = &xs;
    for (x, y) in &xs {
        println!("{:?}", x);
    }
}
```

The current output is:

```rust
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
3 |     let (x, y) = &xs;
  |         ^^^^^^   --- this expression has type `&Option<Vec<({integer}, &str)>>`
  |         |
  |         expected enum `Option`, found tuple
  |
  = note: expected enum `Option<Vec<({integer}, &str)>>`
            found tuple `(_, _)`

error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
4 |     for (x, y) in &xs {
  |         ^^^^^^    --- this expression has type `&Vec<({integer}, &str)>`
  |         |
  |         expected struct `Vec`, found tuple
  |
  = note: expected struct `Vec<({integer}, &str)>`
              found tuple `(_, _)`
```

In both cases the expression underlined is `&xs`, but the second message shows a different type, the `<&Option<_> as IntoIterator>::Item`'s type, not `&xs`'.

**Comment by b-naber** [comment] 2021-09-21 15:24
Duplicate of https://github.com/rust-lang/rust/issues/82541

**Comment by compiler-errors** [comment] 2022-04-10 06:14
This error message seems consistent now:

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 [--> src/main.rs:3:9
](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)  |
3 |     let (x, y) = &xs;
  |         ^^^^^^   --- this expression has type `&Option<Vec<({integer}, &str)>>`
  |         |
  |         expected enum `Option`, found tuple
  |
  = note: expected enum `Option<Vec<({integer}, &str)>>`
            found tuple `(_, _)`

error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 [--> src/main.rs:4:9
](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)  |
4 |     for (x, y) in &xs {
  |         ^^^^^^    --- this expression has type `Option<&Vec<({integer}, &str)>>`
  |         |
  |         expected struct `Vec`, found tuple
  |
  = note: expected struct `Vec<({integer}, &str)>`
              found tuple `(_, _)`
```

Unless I am mistaken, I will close this then.

**Closed by compiler-errors** 2022-04-10 06:14 UTC
Labels: A-diagnostics, T-compiler, A-iterators, D-confusing
