### ISSUE TITLE
New IO stdout is not flushed at program exit

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#23191] opened 2015-03-08 16:47 UTC
I know that the new IO is being worked on, but I could see this being a sneaky thing that gets lost.

```rust
#![feature(io)]
use std::io::Write;
fn main() {
    write!(&mut std::io::stdout(), "Hello world").unwrap();
}
```

This code prints nothing. If we use `stderr` instead, there is output.

`rustc 1.0.0-nightly (270a677d4 2015-03-07) (built 2015-03-07)`

**Comment by alexcrichton** [comment] 2015-03-08 17:56
Unfortunately this is a duplicate of https://github.com/rust-lang/rust/issues/20012. The buffers would all be properly flushed if we actually ran the `at_exit` callbacks. I'll try to prioritize fixing that this coming week!

**Closed by alexcrichton** 2015-03-08 17:56 UTC
Labels: A-io
