### ISSUE TITLE
run-make tests fail when configured for multiple targets

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#11094] opened 2013-12-21 01:58 UTC
Something about the use of `%` seems to make these rules not expand correctly, resulting in

```
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu i686-unknown-linux-gnu
cfg: non-build target triples i686-unknown-linux-gnu
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: host for i686-unknown-linux-gnu is i386
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: os for i686-unknown-linux-gnu is unknown-linux-gnu
cfg: using gcc
cfg: no llnextgen found, omitting grammar-verification
cfg: including dist rules
cfg: including test rules
make -C x86_64-unknown-linux-gnu/rt/libuv CFLAGS="-Wall  -g -fPIC -m64 " LDFLAGS="-shared -fPIC -ldl -pthread  -lrt -g -m64" CC="gcc" CXX="g++" AR="ar"  builddir="." BUILDTYPE=Release NO_LOAD="run-benchmarks.target.mk run-tests.target.mk uv_dtrace_header.target.mk uv_dtrace_provider.target.mk" V=1
make[1]: Entering directory `/opt/dev/rust3/build/x86_64-unknown-linux-gnu/rt/libuv'
make[1]: Circular libuv.a <- libuv.a dependency dropped.
  ln -f "obj.target/libuv.a" "libuv.a" 2>/dev/null || (rm -rf "libuv.a" && cp -af "obj.target/libuv.a" "libuv.a")
make[1]: Leaving directory `/opt/dev/rust3/build/x86_64-unknown-linux-gnu/rt/libuv'
make: *** No rule to make target `x86_64-unknown-linux-gnu/test/run-make/bootstrap-from-c-with-uvio-1-T-i686-unknown-linux-gnu-H-x86_64-unknown-linux-gnu.ok', needed by `tmp/check-stage1-T-i686-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rmake.ok'.  Stop.
```

**Comment by frewsxcv** [comment] 2015-02-03 23:39
*visiting for triage*

The [FIXME for this issue](https://github.com/rust-lang/rust/blob/3b2ed14906fd9f9daa27cc7d1dad263d2f5ff450/mk/tests.mk#L1018) still exists in the `mk/test.mk` file, so I assume this is still a valid issue. I'm not well-versed enough in the Make process to know for sure though

**Comment by steveklabnik** [comment] 2016-03-04 16:47
Triage: echoing what @frewsxcv says, but also noting that rustbuild will eventually obviate this.

**Comment by alexcrichton** [comment] 2017-02-11 00:12
Make's now gone, so closing.

(rustbuild handles this I believe)

**Closed by alexcrichton** 2017-02-11 00:12 UTC
Labels: A-build

**Comment by Eh2406** [comment] 2017-09-03 20:25
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/runtest.rs#L2070
Now that the issue is closed can the FIXME be fix, or made more specific?
