### ISSUE TITLE
Mark `std::mem::size_of` and `std::mem::size_of_val` as const function

### ISSUE THREAD

**Issue by mzji** [rust-lang/rust#38772] opened 2017-01-02 10:58 UTC
This allows using `size_of` and `size_of_val` in constants contexts. Does this need an RFC?

**Comment by abonander** [comment] 2017-01-02 11:11
IIRC from the last time this came up, the data used by these intrinsics isn't available until the translation pass, long after const-expansion, and because of things like arrays, where you can use a const fn for the size, it becomes a chicken-or-egg problem. Imagine if you had something like this:

```rust
type MyArray = [i32; size_of::<MyArray>];
```

Of course, you could paper over this by making it an error to do something like this, but that would require an RFC.

**Comment by mzji** [comment] 2017-01-02 11:16
@abonander You are right. If we want to do this, we need to add a constrain to `size_of` and `size_of_val` to make them only accept "concrete" types (i.e. types with known size).

**Comment by nagisa** [comment] 2017-01-02 21:48
Duplicate of https://github.com/rust-lang/rust/issues/34078.

**Closed** 2017-01-03 23:34 UTC
