### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 2', compiler/rustc_builtin_macros/src/format.rs:1001:28

### ISSUE THREAD

**Issue by kmozurkewich** [rust-lang/rust#99338] opened 2022-07-16 16:53 UTC
note: rustc 1.64.0-nightly (23e21bdd2 2022-07-15) running on x86_64-apple-darwin
note: compiler flags: --crate-type lib -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2

### Meta

```
`rustc --version --verbose`: 
rustc 1.64.0-nightly (23e21bdd2 2022-07-15)
binary: rustc
commit-hash: 23e21bdd25026e2839ebe946c2a937c1904887d2
commit-date: 2022-07-15
host: x86_64-apple-darwin
release: 1.64.0-nightly
LLVM version: 14.0.6
```

```

stack backtrace:
   0:        0x10babbca4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4d86da9d3736a52d
   1:        0x10bb1368b - core::fmt::write::h4100c91e34b46860
   2:        0x10baae45c - std::io::Write::write_fmt::hbebacfc28bcb7e63
   3:        0x10babed77 - std::panicking::default_hook::{{closure}}::hd1401e79e66368b2
   4:        0x10babea80 - std::panicking::default_hook::h0d3c0f46f3eb5b87
   Compiling libsecp256k1-core v0.2.2
   Compiling sha2 v0.9.9
   Compiling crossbeam-deque v0.8.1
   5:        0x118916e5a - rustc_driver[73f94c78c1d7d2d0]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x10babf4ad - std::panicking::rust_panic_with_hook::h79b08049599e7781
   7:        0x10babf353 - std::panicking::begin_panic_handler::{{closure}}::h6759a4e79ddd7d62
   8:        0x10babc157 - std::sys_common::backtrace::__rust_end_short_backtrace::ha49d7b96ae0f3fdf
   9:        0x10babf02d - _rust_begin_unwind
  10:        0x10bb3e9f3 - core::panicking::panic_fmt::hc9b2ac84f45a78f2
  11:        0x10bb3e946 - core::panicking::panic_bounds_check::hd73082592787ac04
  12:        0x11b3a2272 - rustc_builtin_macros[4c4cf493c0067ce6]::format::expand_preparsed_format_args
  13:        0x11b39a9db - rustc_builtin_macros[4c4cf493c0067ce6]::format::expand_format_args_impl
  14:        0x11c88ae44 - <rustc_expand[219fa54abb38e138]::expand::MacroExpander>::fully_expand_fragment
  15:        0x11c88a15f - <rustc_expand[219fa54abb38e138]::expand::MacroExpander>::expand_crate
  16:        0x1189d78d6 - <rustc_session[6a4c6fef4db8af12]::session::Session>::time::<core[4765b6e14de13592]::result::Result<rustc_ast[941672277c0de11b]::ast::Crate, rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_interface[8a17d161f34c737e]::passes::configure_and_expand::{closure#1}>
  17:        0x1189cea23 - <rustc_interface[8a17d161f34c737e]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[8a17d161f34c737e]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[4765b6e14de13592]::result::Result<rustc_ast[941672277c0de11b]::ast::Crate, rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>
  18:        0x1189b0526 - <rustc_interface[8a17d161f34c737e]::queries::Queries>::expansion
  19:        0x118891ef1 - <rustc_interface[8a17d161f34c737e]::interface::Compiler>::enter::<rustc_driver[73f94c78c1d7d2d0]::run_compiler::{closure#1}::{closure#2}, core[4765b6e14de13592]::result::Result<core[4765b6e14de13592]::option::Option<rustc_interface[8a17d161f34c737e]::queries::Linker>, rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>
  20:        0x1188877f8 - rustc_span[b3c07a240d8aa70d]::with_source_map::<core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_interface[8a17d161f34c737e]::interface::create_compiler_and_run<core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_driver[73f94c78c1d7d2d0]::run_compiler::{closure#1}>::{closure#1}>
  21:        0x1188b1cf6 - rustc_interface[8a17d161f34c737e]::interface::create_compiler_and_run::<core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_driver[73f94c78c1d7d2d0]::run_compiler::{closure#1}>
  22:        0x118884825 - <scoped_tls[bbf5cad6a1edfb51]::ScopedKey<rustc_span[b3c07a240d8aa70d]::SessionGlobals>>::set::<rustc_interface[8a17d161f34c737e]::interface::run_compiler<core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_driver[73f94c78c1d7d2d0]::run_compiler::{closure#1}>::{closure#0}, core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>
  23:        0x11888e469 - std[51cc303cb6d2584d]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8a17d161f34c737e]::util::run_in_thread_pool_with_globals<rustc_interface[8a17d161f34c737e]::interface::run_compiler<core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_driver[73f94c78c1d7d2d0]::run_compiler::{closure#1}>::{closure#0}, core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>::{closure#0}, core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>
  24:        0x1188b2a01 - <<std[51cc303cb6d2584d]::thread::Builder>::spawn_unchecked_<rustc_interface[8a17d161f34c737e]::util::run_in_thread_pool_with_globals<rustc_interface[8a17d161f34c737e]::interface::run_compiler<core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>, rustc_driver[73f94c78c1d7d2d0]::run_compiler::{closure#1}>::{closure#0}, core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>::{closure#0}, core[4765b6e14de13592]::result::Result<(), rustc_errors[6b560b2f72f0dc1a]::ErrorGuaranteed>>::{closure#1} as core[4765b6e14de13592]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:        0x10bac8187 - std::sys::unix::thread::Thread::new::thread_start::hae41e3c2653ceb35
  26:     0x7ff80a57b4e1 - __pthread_start</strong></summary>



```

</p>
</details>

**Comment by lqd** [comment] 2022-07-16 18:08
This is a duplicate of #99261. It's already been fixed by #99263 and should be resolved in the next nightly. Thanks for opening an issue!

**Closed by lqd** 2022-07-16 18:08 UTC
Labels: I-ICE, T-compiler, C-bug
