### ISSUE TITLE
Shadowed enum variants lead to badness

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#28320] opened 2015-09-09 19:42 UTC
This is crate `c`:

``` rust
pub enum E {
    V(u8)
}

impl E {
    fn V(u: u8) -> E {
        println!("IN V!");

        E::V(u)
    }

    pub fn test(&self) {
        match *self {
            E::V(val) => println!("{}", val),
        }
    }
}
```

This compiles fine. The `E::V(u)` line seems to use the variant constructor instead of my function. **Note that the function V is private.** (`pub` = same problem)

I now have another crate that makes use of the `c` crate:

``` rust
extern crate c;
use c::E;

fn test(e: &E) {
    match *e {
        E::V(_) => println!("Yep"),
    }
}

fn main() {
    let e = E::V(123);

    e.test();
}
```

The match inside `test` causes this error, even though the implementation is the same as in crate `c`:

```
src\main.rs:7:9: 7:13 error: `V` is not an enum variant, struct or const [E0418]
src\main.rs:7         E::V(123) => println!("Yep"),
                      ^~~~
error: aborting due to previous error
```

**Comment by Aatch** [comment] 2015-09-10 23:55
This is less shadowing and more a conflict. Still, not good either way. Not sure of the best way to handle it. I think the conflict should be prevented to start with, since there's never going to be a reasonable way to resolve it.

/cc @rust-lang/compiler specifically @eddyb since he's done a reasonable amount of work here.

**Comment by eddyb** [comment] 2015-09-11 00:19
There seems to be a mismatch between the error and the code.
Also, methods aren't used unless the path *failed* to match as a whole.
Here `E::V` should always refer to the variant (and `<E>::V` could access the method), so this looks like a bug in cross-crate resolution.
But I don't see how. Can you access the variant at all, if the method is missing?

**Comment by eddyb** [comment] 2015-09-11 00:43
Turns out there was [one hack](https://github.com/rust-lang/rust/blob/5ff55943a38f2b581bd4ae5d521f57defd1a8b29/src/librustc/metadata/decoder.rs#L644-L646) that went under the radar when UFCS was implemented.

**Comment by jonas-schievink** [comment] 2015-09-11 11:11
Er, right. I changed the pattern from `E::V(123)` to `E::V(_)`. Same error.

If the method `fn V` is removed, everything compiles.

If I don't attempt to match against the enum, it complains that `V` is private when attempting to call it in `main`. If I make it public, it is used (`IN V!` is printed).

I kind of hoped that I could override the enum constructor with my own method, to allow things like:
```rust
fn V<T: Into<u8>>(t: T) -> E { ... }
```
(with types where this makes more sense, of course)

**Comment by eddyb** [comment] 2015-09-11 11:37
@jonas-schievink The same-crate behavior is correct, the inter-crate behavior isn't (and it's caused by that hack that can be simply removed).

There is no way to override the enum variant - it is a bug that the method is even seen at that point.
`Enum::Variant` is a direct resolution, whereas `Enum::method` desugars to `<Enum>::method` which later goes through type-dependent associated item resolution.

If I were to suggest anything, it would be an `Enum::variant` method, constructing an `Enum::Variant`.
This way, it would work and it would also follow style guidelines.

**Comment by jonas-schievink** [comment] 2015-09-11 12:20
> If I were to suggest anything, it would be an `Enum::variant` method, constructing an `Enum::Variant`.

Yep, that's probably what I'll end up doing. Thanks!

**Comment by nikomatsakis** [comment] 2015-09-11 16:15
If it can never be seen, I think that the declaration of the inherent fn `V` ought to be an error.

**Comment by eddyb** [comment] 2015-09-11 18:45
@nikomatsakis You can access such methods with `<E>::V` or method call syntax (the latter is not applicable in this case).

**Comment by nikomatsakis** [comment] 2015-09-14 20:25
@eddyb ok, but it's still unclear to me that one this sort of ambiguity should be permitted if we can avoid it. Basically longer term I would hope that we can eventually make the variants etc be *some* kind of inherent something or other.

**Comment by steveklabnik** [comment] 2017-03-08 17:21
Today:

```powershell
C:\Users\steve\tmp> vim c.rs
C:\Users\steve\tmp> rustc .\c.rs --crate-type=rlib
warning: method is never used: `V`, #[warn(dead_code)] on by default
  --> .\c.rs:6:5
   |
6  |       fn V(u: u8) -> E {
   |  _____^ starting here...
7  | |         println!("IN V!");
8  | |
9  | |         E::V(u)
10 | |     }
   | |_____^ ...ending here

warning: method `V` should have a snake case name such as `v`, #[warn(non_snake_case)] on by default
  --> .\c.rs:6:5
   |
6  |       fn V(u: u8) -> E {
   |  _____^ starting here...
7  | |         println!("IN V!");
8  | |
9  | |         E::V(u)
10 | |     }
   | |_____^ ...ending here

C:\Users\steve\tmp> vim d.rs
C:\Users\steve\tmp> rustc .\d.rs -L .
warning: function is never used: `test`, #[warn(dead_code)] on by default
 --> .\d.rs:4:1
  |
4 |   fn test(e: &E) {
  |  _^ starting here...
5 | |     match *e {
6 | |         E::V(_) => println!("Yep"),
7 | |     }
8 | | }
  | |_^ ...ending here

C:\Users\steve\tmp> .\d.exe
123
```

So, looks like this has been fixed. Closing!

**Closed by steveklabnik** 2017-03-08 17:21 UTC
Labels: I-wrong
