### ISSUE TITLE
no way to disable link suggestions

### ISSUE THREAD

**Issue by shahn** [rust-lang/rust#41592] opened 2017-04-28 02:47 UTC
When building a static library, rust emits a long list of libraries to link to. --quiet does not help in silencing it, and it really clutters the build output with completely redundant information.

    note: link against the following native artifacts when linking against this static library
    
    note: the order and any duplication can be significant on some platforms, and so may need to be preserved
    
    note: library: util
    
    note: library: dl
    
    note: library: rt
    
    note: library: pthread
    
    note: library: gcc_s
    
    note: library: c
    
    note: library: m
    
    note: library: rt
    
    note: library: pthread
    
    note: library: util

**Comment by jmesmon** [comment] 2017-04-28 17:46
Related: do we actually need to emit the extra newlines between each line here? That definitely contributes to making this an eyesore.

**Comment by alexcrichton** [comment] 2017-06-13 22:00
Closing as a duplicate of https://github.com/rust-lang/rust/issues/33173

**Closed by alexcrichton** 2017-06-13 22:00 UTC
