### ISSUE TITLE
Too-big literals can be smuggled into `println!`

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#118554] opened 2023-12-03 03:10 UTC
I tried this code:

```rust
fn main() {
    println!("{}", 0x1234567890123456789_i64);
}
```

I expected to see this happen:

Denial of an overflowing literal, like the following case would:

```rust
fn main() {
    let x = 0x1234567890123456789_i64;
    println!("{}", x);
}
```

Instead, this happened:

It worked??? It even printed out the right decimal number, 5373003641998677469065

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (8c2b57721 2023-12-01)
binary: rustc
commit-hash: 8c2b57721728233e074db69d93517614de338055
commit-date: 2023-12-01
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by workingjubilee** [comment] 2023-12-03 03:54
> @saethlin: I'm not actually sure if the issue you opened is a duplicate
> @saethlin: Behold, no constants in the MIR: https://godbolt.org/z/P56ooWxcz

Guess I'm wrong. :P

**Comment by gurry** [comment] 2023-12-04 05:04
A duplicate of #115423

**Closed** 2023-12-05 22:36 UTC
Labels: T-compiler, C-bug, A-fmt
