### ISSUE TITLE
ICE RLS 1.34.0 no type for node `expr <Self>::WROTE_NOTHING

### ISSUE THREAD

**Issue by samoylovfp** [rust-lang/rust#60514] opened 2019-05-03 17:03 UTC
steps to reproduce:
```
cargo new test_ice
cd test_ice
rustup override add stable-2019-04-25
rustup component add rls --toolchain stable-2019-04-25-x86_64-unknown-linux-gnu
echo 'ggez = "0.4.4"' >> Cargo.toml
rls --cli
```
observe 
```
...
{"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"toml","title":"Building"}}
{"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"euclid","title":"Building"}}
{"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"ordered_float","title":"Building"}}
{"jsonrpc":"2.0","method":"window/progress","params":{"id":"progress_1","message":"syn","title":"Building"}}
{"message":"src/librustc/ty/context.rs:541: node_type: no type for node `expr <Self>::RED (id=17020)`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src/librustc/ty/context.rs:541: node_type: no type for node `expr <Self>::RED (id=17020)`\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.1 (fc50f328b 2019-04-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

Os info
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
Please ping me for more information

**Comment by jonas-schievink** [comment] 2019-05-03 17:14
Duplicate of https://github.com/rust-lang/rust/issues/60484

**Closed by jonas-schievink** 2019-05-03 17:14 UTC
Labels: A-rls, I-ICE, I-nominated, T-compiler
