### ISSUE TITLE
No warning for an associated constant always hidden by an enum variant

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#76347] opened 2020-09-04 21:56 UTC
To my great surprise, this compiles fine, with no warnings:
```rust
pub enum Foo {
    A(i32),
}
impl Foo {
    pub const A: Self = Foo::A(0);
}
```

Trying to actually use that constant, however, doesn't work:
```rust
pub fn demo() -> Foo {
    Foo::A
}
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d1e7c140a60c78cc6ede62b677a74e5e
```rust
error[E0308]: mismatched types
 --> src/lib.rs:9:5
  |
2 |     A(i32),
  |     ------ fn(i32) -> Foo {Foo::A} defined here
...
8 | pub fn demo() -> Foo {
  |                  --- expected `Foo` because of return type
9 |     Foo::A
  |     ^^^^^^ expected enum `Foo`, found fn item
  |
  = note: expected enum `Foo`
          found fn item `fn(i32) -> Foo {Foo::A}`
help: use parentheses to instantiate this tuple variant
  |
9 |     Foo::A(_)
  |           ^^^
```

If that constant is going to compile, it should probably at least be linted against.

**Comment by petrochenkov** [comment] 2020-09-04 22:32
IIRC, when "variants as associated items" were accepted, the decision was to report an associated item overlap error similar to
```
struct S;
impl S { fn a() {} }
impl S { fn a() {} } //~ ERROR
```
in situations like this.

**Comment by jyn514** [comment] 2020-09-05 02:41
I recently discovered this in rustdoc: https://github.com/rust-lang/rust/pull/75756#discussion_r479807425. I guess rustdoc should track the rustc behavior (right now it's buggy and gives the const precedence): https://github.com/rust-lang/rust/blob/085e4170873f3e411c87ee009572f7d2b5130856/src/librustdoc/passes/collect_intra_doc_links.rs#L113-L122)
So give the variant precedence now and change it whenever rustc changes it.

**Comment by scileo** [comment] 2020-09-06 13:19
Can I start working on it?

**Comment by scileo** [comment] 2020-09-06 18:39
> IIRC, when "variants as associated items" were accepted, the decision was to report an associated item overlap error similar to
> 
> ```
> struct S;
> impl S { fn a() {} }
> impl S { fn a() {} } //~ ERROR
> ```
> 
> in situations like this.

@petrochenkov, can you post a link of where this has been discussed?

Also, this would break the test [ui/type-alias-enum-variants/enum-variant-priority-higher-than-other-inherent.rs]. I am not sure if I should just remove the relevant code.

By the way, should we emit an error when a function name is the same as an enum variant?

[ui/type-alias-enum-variants/enum-variant-priority-higher-than-other-inherent.rs]: https://github.com/rust-lang/rust/blob/master/src/test/ui/type-alias-enum-variants/enum-variant-priority-higher-than-other-inherent.rs

**Comment by scottmcm** [comment] 2021-06-21 18:57
Looks like this is related to https://github.com/rust-lang/rust/issues/48758#issuecomment-865257712

**Comment by petrochenkov** [comment] 2024-08-01 15:56
Closing as a duplicate of https://github.com/rust-lang/rust/issues/48758.

**Closed by petrochenkov** 2024-08-01 15:56 UTC
Labels: A-lint, A-associated-items
