### ISSUE TITLE
Type coercions does not apply in match statements

### ISSUE THREAD

**Issue by Ticki** [rust-lang/rust#30581] opened 2015-12-27 19:57 UTC
For example:

```rust
fn main() {
    let a = "Cats are cute".to_string();
    
    match &a {
        "Cats are cute" => println!("They are"),
        _               => panic!("Nope"),
    }
}
```

This will fail with the error:

```rust
<anon>:5:9: 5:24 error: mismatched types:
 expected `&collections::string::String`,
    found `&'static str`
(expected struct `collections::string::String`,
    found str) [E0308]
<anon>:5         "Cats are cute" => println!("They are"),
                 ^~~~~~~~~~~~~~~
<anon>:5:9: 5:24 help: see the detailed explanation for E0308
error: aborting due to previous error
```

**Comment by rphmeier** [comment] 2015-12-27 21:34
The issue here is that no deref coercion is applied to the match argument? For example, this runs as expected:
```rust
fn main() {
    let a = "Cats are cute".to_string();

    match &*a {
        "Cats are cute" => println!("They are"),
        _               => panic!("Nope"),
    }
}
```

Since deref coercions are one of those few cases in Rust where actions are implicit rather than explicit,  it could make sense to try and apply them to the matched expression.

**Comment by jonas-schievink** [comment] 2015-12-27 21:57
Duplicate of #28606

**Comment by arielb1** [comment] 2015-12-27 23:23
closing as a duplicate.

**Closed by arielb1** 2015-12-27 23:23 UTC
