### ISSUE TITLE
macros: it is possible to downcast a `tt` to most anything using nested macros

### ISSUE THREAD

**Issue by apoelstra** [rust-lang/rust#16036] opened 2014-07-28 02:44 UTC
The following code compiles:

``` rust
#![feature(macro_rules)]

macro_rules! print_doccomment(
  (
    $doc:tt
    fn $name:ident()
  ) => (
    macro_rules! dummy( () => (
      $doc
      fn $name() {
        println!("The doc for this function is `{}`", stringify!($doc));
      }
    ))
    dummy!()
  )
)

print_doccomment!(
  /// This is a doc comment
  fn function_to_doc()
)

fn main() {
  function_to_doc();
}
```

And prints "/// This is a doc comment". However, the token `/// This is a doc comment` is not an item, which is the only thing that should parse for the first `$doc` when `dummy!` is expanded (according to @chris-morgan on IRC).

Note that I am using (a variation on) this in some code to transmit the doc comments on RPC-handling functions in response to the RPC "help". It would be great if there were a sanctioned way to parse or construct doccomments in macros.

**Comment by huonw** [comment] 2015-10-27 06:34
I'm not sure I understand

> However, the token /// This is a doc comment is not an item, which is the only thing that should parse for the first $doc when dummy! is expanded

Could you clarify? (The doc comment is an attribute that ends up attached to the `fn`.)

**Comment by bltavares** [comment] 2015-11-14 20:28
Triaging: I was not able to compile on nightly. The code needed some `;` added, but now it fails with an error on parsing.

```
<anon>:19:3: 19:28 error: no rules expected the token `[`
<anon>:19   /// This is a doc comment
            ^~~~~~~~~~~~~~~~~~~~~~~~~
```

```rust
#![feature(macro_rules)]

macro_rules! print_doccomment(
  (
    $doc:tt
    fn $name:ident()
  ) => (
    macro_rules! dummy( () => (
      $doc
      fn $name() {
        println!("The doc for this function is `{}`", stringify!($doc));
      }
    ))
    dummy!()
  )
);

print_doccomment!(
  /// This is a doc comment
  fn function_to_doc()
);

fn main() {
  function_to_doc();
}
```

**Comment by Mark-Simulacrum** [comment] 2017-04-15 15:37
The original and updated code no longer compile, and I suspect it should be closed, since the original issue is, and I cannot reproduce.

@jseyfried Can you confirm?

**Comment by Mark-Simulacrum** [comment] 2017-07-21 22:56
Closing. Please reopen if that's not the correct decision here.

**Closed by Mark-Simulacrum** 2017-07-21 22:56 UTC
Labels: A-macros

**Comment by jseyfried** [comment] 2017-07-24 19:15
Yeah, this should be closed -- we can now downcast `tt`s anywhere.
