### ISSUE TITLE
#[derive(Default)] constraints type parameters despite not being required for a Default bound.

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#35263] opened 2016-08-03 20:33 UTC
```rust
#[derive(Default)]
struct Type<T> {
    vec: Vec<T>,
}
```

only derives `Type<T>: Default` if `T: Default`, which is unnecessary, given a `Vec<T>: Default` for any unbounded `T`.

**Comment by jonas-schievink** [comment] 2016-08-03 20:40
Sounds like #26925

**Comment by ticki** [comment] 2016-08-03 20:43
Certainly related, but not exactly a duplicate.

**Comment by apasel422** [comment] 2016-08-03 20:54
Since #32673 was a duplicate of #26925, I would argue this is as well.

**Comment by eddyb** [comment] 2016-08-03 23:10
Closing as duplicate of #26925.

**Closed by eddyb** 2016-08-03 23:10 UTC
