### ISSUE TITLE
New panic with env_logger and with #[windows_subsystem = "windows"]

### ISSUE THREAD

**Issue by parasyte** [rust-lang/rust#88576] opened 2021-09-01 23:18 UTC
This was initially reported in https://github.com/env-logger-rs/env_logger/issues/214, but I'm adding it here for additional eyes and because this issue doesn't occur on stable Rust. I could be wrong but this looks like this is caused by #87329 ... cc @sunfishcode ?

----

I spent an hour trying to reduce a minimal test case for this error I started experiencing with my app. So far I have produced the following:

```toml
[package]
name = "windows_explodey"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
env_logger = "0.9"

[profile.release]
panic = "abort"
```

```rust
#![windows_subsystem = "windows"]

fn main() {
    env_logger::init();

    println!("Hello, world!");
}
```

When running this on any nightly compiler since `nightly-2021-08-21`, I get an error like this:

```
$ cargo +nightly-2021-08-21 run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target\debug\windows_explodey.exe`
error: process didn't exit successfully: `target\debug\windows_explodey.exe` (exit code: 101)
```

Adjusting the profile to `panic = "abort"` causes an even more ominous error:

```
$ cargo +nightly-2021-08-21 run --release
    Finished release [optimized] target(s) in 0.03s
     Running `target\release\windows_explodey.exe`
error: process didn't exit successfully: `target\release\windows_explodey.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

Here's a stack trace from windbg:

```
[0x0]   windows_explodey!panic_abort::__rust_start_panic::abort + 0x5   
[0x1]   windows_explodey!panic_abort::__rust_start_panic + 0x6   
[0x2]   windows_explodey!std::panicking::rust_panic + 0x1b   
[0x3]   windows_explodey!std::panicking::rust_panic_with_hook + 0x297   
[0x4]   windows_explodey!std::panicking::begin_panic_handler::closure$0 + 0x6f   
[0x5]   windows_explodey!std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$> + 0x17   
[0x6]   windows_explodey!std::panicking::begin_panic_handler + 0x49   
[0x7]   windows_explodey!core::panicking::panic_fmt + 0x30   
[0x8]   windows_explodey!core::panicking::panic + 0x4c   
[0x9]   windows_explodey!std::os::imp::windows::io::handle::impl$11::from_raw_handle + 0x4c   
[0xa]   windows_explodey!std::os::imp::windows::io::raw::impl$7::from_raw_handle + 0x13   
[0xb]   windows_explodey!winapi_util::win::HandleRef::from_raw_handle + 0xe   
[0xc]   windows_explodey!winapi_util::win::HandleRef::stderr + 0x27   
[0xd]   windows_explodey!winapi_util::console::HandleKind::handle + 0x27   
[0xe]   windows_explodey!winapi_util::console::Console::create_for_stream + 0x22   
[0xf]   windows_explodey!winapi_util::console::Console::stderr + 0x1d   
[0x10]   windows_explodey!termcolor::BufferWriter::create + 0x59   
[0x11]   windows_explodey!termcolor::BufferWriter::stderr + 0x22   
[0x12]   windows_explodey!env_logger::fmt::writer::termcolor::imp::BufferWriter::stderr + 0x49   
[0x13]   windows_explodey!env_logger::fmt::writer::Builder::build + 0x133   
[0x14]   windows_explodey!env_logger::Builder::build + 0x46   
[0x15]   windows_explodey!env_logger::Builder::try_init + 0x1c   
[0x16]   windows_explodey!env_logger::try_init_from_env<env_logger::Env> + 0x39   
[0x17]   windows_explodey!env_logger::try_init + 0x1b   
[0x18]   windows_explodey!env_logger::init + 0x9   
[0x19]   windows_explodey!windows_explodey::main + 0x9   
```

If I'm reading this correctly, the panic is from this assertion: https://github.com/rust-lang/rust/blob/50171c310cd15e1b2d3723766ce64e2e4d6696fc/library/std/src/os/windows/io/handle.rs#L183

**Comment by ChrisDenton** [comment] 2021-09-01 23:41
Likely cause is that when the "windows" subsystem is used, the std handles will all be null (i.e. they don't exist). From the backtrace it looks like the std is expecting them to always be a valid handle value.

**Comment by parasyte** [comment] 2021-09-01 23:53
`termcolor` just does this: https://github.com/BurntSushi/termcolor/blob/dc7e7b93830579716fc180925a17551dee5cfddc/src/lib.rs#L893-L899

It expects a `Result`.

**Comment by sunfishcode** [comment] 2021-09-02 00:20
The crash goes away if I change the `env_logger` dependency in Cargo.toml to disable the "termcolor" and "atty" features:
```toml
env_logger = { version = "0.9", default-features = false, features = ["humantime", "regex"] }
```

As such, one option here would be to say that `io::stderr()` shouldn't be called in `#![windows_subsystem = "windows"]` mode, and have it panic with a descriptive panic message. There's a logic to that, since there seems to be no point in linking in and calling termcolor or other stdio-using things if there's no terminal to talk to. However, that's not backwards compatible.

Another option would be to say that `OwnedHandle::from_raw_handle` has to be able to accept NULL handles. That's doable, though if we want to preserve the FFI use case, that would mean introducing another struct like `HandleOrInvalid`, this time for NULL instead of `INVALID_HANDLE_VALUE`.

**Comment by sunfishcode** [comment] 2021-09-02 00:25
cc the [io_safety tracking issue](https://github.com/rust-lang/rust/issues/87074)

**Comment by parasyte** [comment] 2021-09-02 00:26
Maybe it would be worthwhile to get BurntSushi's thoughts, since this affects `winapi_util`?

Personally I would be with "just update your dependencies" as a solution, but maintaining backward compatibility might be more important for the libraries team...

**Comment by ChrisDenton** [comment] 2021-09-02 00:33
> As such, one option here would be to say that io::stderr() shouldn't be called in #![windows_subsystem = "windows"] mode, and have it panic with a descriptive panic message. There's a logic to that, since there seems to be no point in linking in and calling termcolor or other stdio-using things if there's no terminal to talk to. However, that's not backwards compatible.

In any case this would cause other problems. Windows processes can be freely attached or detached from consoles no mater which `windows_subsystem` they're using so we can't really make assumptions based on that.

**Comment by sunfishcode** [comment] 2021-09-02 01:32
Good catch; `HandleOrInvalid` will also need to be changed to accept NULL handles.

**Comment by sunfishcode** [comment] 2021-09-09 22:43
This is now implemented in https://github.com/rust-lang/rust/pull/88798.

**Comment by joshtriplett** [comment] 2021-09-10 15:16
@sunfishcode Would it make sense to just use `Option<HandleOrInvalid>` for that?

**Comment by sunfishcode** [comment] 2021-09-10 15:34
@joshtriplett User code [like this](https://github.com/BurntSushi/winapi-util/blob/master/src/win.rs#L139) means that `BorrowedHandle` needs to be able to hold a null, in `windows_subsystem = "windows"` mode. Then, `ManuallyDrop` and `IntoHandle` in `Drop` idioms imply that `OwnedHandle` needs to be able to hold any value that `BorrowedHandle` can hold.

**Comment by ChrisDenton** [comment] 2021-09-10 21:06
Ideally `stdout()` etc would return an `Option` (or `io::Result` I guess). But seeing as that's not the case, this is probably the best solution. Or I guess it could return a handle to the `\\.\NUL` device? That might cause more problems though.

**Comment by sunfishcode** [comment] 2021-09-30 23:44
I agree, returning a handle to `\\.\NUL` would be a significant change from how `std` currently works, and would likely break code that expects to be able to test `std::io::stdout()` and similar for null to see if a console is attached.

@joshtriplett Is there anything else I should investigate here?

**Comment by joshtriplett** [comment] 2021-10-04 03:59
This makes me sad, but this makes sense. I don't think this needs further investigation.

I posted a bit of code review on the PR, but otherwise this should probably go ahead.

**Comment by Subsentient** [comment] 2021-11-09 23:39
Why is this still not fixed after three months? The patch has been ready for a while now and nobody has reviewed it!

**Comment by glandium** [comment] 2021-11-10 00:36
> removed regression-from-stable-to-stable

why? this is a regression that shipped in 1.56!

**Comment by Mark-Simulacrum** [comment] 2021-11-10 00:39
My bad. I looked at the milestone and was worried it might've been mislabeled (by me) but I don't think that's actually the case.

**Comment by joshtriplett** [comment] 2021-11-10 19:16
I'll review the fix today.

**Comment by Subsentient** [comment] 2021-11-10 21:01
> I'll review the fix today.

Thank you Josh, it's much appreciated. The GUI target for the most popular OS being broken is a pretty severe thing imho (since so many crates use env_logger automatically), so definitely don't want that staying broken too long.

**Comment by joshtriplett** [comment] 2021-11-10 21:46
@Subsentient Many Rustaceans use Windows, and many build non-CLI apps, but I have the impression many do not combine that with things that get stdout handles.

**Comment by parasyte** [comment] 2021-11-10 21:58
This is the kind of issue that you are likely to hit accidentally as mentioned in https://github.com/rust-lang/rust/issues/88576#issuecomment-953282824. Not because you are building a Windows GUI application that also writes to stdout.

**Comment by Subsentient** [comment] 2021-11-10 22:06
> This is the kind of issue that you are likely to hit accidentally as mentioned in [#88576 (comment)](https://github.com/rust-lang/rust/issues/88576#issuecomment-953282824). Not specifically because you are building a Windows GUI application that also writes to stdout.

Correct, it seems a sizable percentage of crates initialize env_logger on their own, which means that if you're building a non-trivial application, odds are high that you'll hit this bug. Or maybe you just get lucky? But two of my non-trivial projects with no crates in common are hitting this bug.

**Comment by sunfishcode** [comment] 2021-11-12 14:04
#88798 has now landed, the latest Rust nightly (936238a92) now includes it, and using that, I can compile and run [the testcase](https://github.com/rust-lang/rust/issues/88576#issue-985818273) successfully.

**Comment by sunfishcode** [comment] 2021-11-13 15:40
I'm following the steps documented [here](https://forge.rust-lang.org/release/backporting.html) for backporting changes to beta.

**Comment by cuviper** [comment] 2021-11-19 16:41
Backported in #90938.

**Closed by cuviper** 2021-11-19 16:41 UTC
Labels: P-high, regression-from-stable-to-stable, C-bug, T-libs

**Comment by sunfishcode** [comment] 2021-12-02 19:49
Rust 1.57, which was just released, contains the fix for this. I've confirmed that the testcase reported here is fixed.
