### ISSUE TITLE
Conflicing implementations when implementing trait for type implementing Fn with different parameters.

### ISSUE THREAD

**Issue by nolanderc** [rust-lang/rust#58711] opened 2019-02-24 21:27 UTC
The compiler cannot differentiate between `Fn()` and `Fn(T)` when implementing a trait for a generic type.

Example: ([Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=27fbd19fd0ed174f9ff9f571ef4572fb))
```rust
trait Foo {
    fn foo(&self, a: i32);
}

impl<F> Foo for F where F: Fn(i32) {
    fn foo(&self, a: i32) {
        self(a)
    }
}

impl<F> Foo for F where F: Fn() {
    fn foo(&self, a: i32) {
        self()
    }
}
```

The compiler currently gives a not so helpful error message:
```rust
error[E0119]: conflicting implementations of trait `Foo`:
  --> src/lib.rs:13:1
   |
6  | / impl<F> Foo for F
7  | | where F: Fn(i32) {
8  | |     fn foo(&self, a: i32) {
9  | |         self(a)
10 | |     }
11 | | }
   | |_- first implementation here
12 | 
13 | / impl<F> Foo for F
14 | | where F: Fn() {
15 | |     fn foo(&self, a: i32) {
16 | |         self()
17 | |     }
18 | | }
   | |_^ conflicting implementation
```

I would expect this code to compile successfully since, to my mind, the type signatures `Fn(T)` and `Fn()` are different.

rustc 1.32.0 (9fda7c223 2019-01-16)

**Comment by sfackler** [comment] 2019-02-24 23:14
A single type can implement `Fn(i32)` and `Fn()`. This isn't any different than trying to have implementations for `T: Debug` and `T: Display`, for example.

**Comment by jonas-schievink** [comment] 2019-02-26 10:30
Closing as working as intended. Specialization might allow you to define both impls.

**Closed by jonas-schievink** 2019-02-26 10:30 UTC
