### ISSUE TITLE
Rust compiler sometimes uses too much RAM.

### ISSUE THREAD

**Issue by AraHaan** [rust-lang/rust#38306] opened 2016-12-11 20:05 UTC
I know that some Rust code when compiled with certain dependencies makes it reach over 1 GB of RAM being used.

It would be nice if something in the processing would be like it is but use less memory on it somehow?

Sadly it is the same way sometimes in Microsoft's ``cl.exe`` (from VS2015).

**Comment by bluss** [comment] 2016-12-11 20:50
Hi! Yes It's known that the rust compiler can use a lot of memory.

For your issue report to be useful, it has to be verifiable and reproducible. Please provide a link to code that exhibits this behaviour, and the steps needed to reproduce! Having a good reproduction increases the chances that the bug will be fixed. Thanks.

**Comment by steveklabnik** [comment] 2016-12-14 23:38
Hi @AraHaan ! yes, I second @bluss 's comment. Please provide some specifics, and we can see if there's something unusual going on. Since it's been a few days, and we haven't heard back from you, I'm going to give this a close, but please don't hesitate to post more details below, and then we can re-open. Thanks!

**Closed by steveklabnik** 2016-12-14 23:38 UTC
