### ISSUE TITLE
Exporting a function with the same name as a function in libc emits incorrect assembly

### ISSUE THREAD

**Issue by lineaar** [rust-lang/rust#68148] opened 2020-01-12 08:24 UTC
```rust
type flt = f64;

#[no_mangle]
pub extern "C" fn atan2(xx: flt, xy: flt, yx: flt, yy: flt) -> flt {
    let f = xx * yy + xy * yx;
    f.atan2(xx * yx + yx * yy)
}
```
```python
from ctypes import cdll, c_double as flt

lib = cdll.LoadLibrary("./libname.so")
atan2 = lib.atan2
atan2.argtypes = [flt, flt, flt, flt]
atan2.restype = flt

r = 0.0
for x in range(1000):
    for y in range(1000):
        r += atan2(flt(x), flt(y), flt(y), flt(x))

print(r)
```
Compiling the rust code with `rustc name.rs --crate-type cdylib -Copt-level=x` where `x` in [1, 2, 3] generates interesting assembly (https://rust.godbolt.org/z/a-32AR).

With `x`=0, a correct answer is computed.
With `x`=1, a wrong answer is computed.
With `x` in [2, 3], an infinite loop is emitted.

The issue stems from the fact that the name of the exported function and libc's `atan2` collide. This is reproduceable from rustc 1.12.0 to current nightly.

To avoid the issue one can rename the exported function to avoid the collision or use `f32` since that calls `atan2f` or use `&f64` for the inputs with byref in Python.

**Comment by jonas-schievink** [comment] 2020-01-12 12:47
This is a combination of https://github.com/rust-lang/rust/issues/28179 and https://github.com/rust-lang/rust/issues/28728, so closing in favor of those

**Comment by jonas-schievink** [comment] 2020-01-12 12:47
Actually https://github.com/rust-lang/rust/issues/28728 might not be involved, but the root cause is https://github.com/rust-lang/rust/issues/28179

**Closed by jonas-schievink** 2020-01-12 12:47 UTC
