### ISSUE TITLE
No warning on assigning to field of const that doesn't succeed

### ISSUE THREAD

**Issue by CraftSpider** [rust-lang/rust#74053] opened 2020-07-05 04:35 UTC
I tried this code:

- Playground Link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=053c3012c504c1cd85a98ff5feeeceab

I expected to see this happen: 

- Either successful assignment or a compiler error, I actually would prefer the first but I'm not sure the intended behavior either way.

Instead, this happened:

- Compile succeeds without warning, the value doesn't change.

### Meta

Occurs in Stable, Beta, and Nightly builds on the playground.

No backtrace is emitted

**Comment by lcnr** [comment] 2020-07-05 06:41
I am not completely sure if this behavior is intended. But even if this is not a bug,
we should still at least warn here.

Inline snippet
```rust
struct Foo {
    val: i32,
}

const FOO: Foo = Foo { val: 100 };

const fn bar() -> i32 {
    FOO.val = -100;
    FOO.val
}

fn main() {
    println!("{}", FOO.val);
    println!("{}", bar());
}
```

**Comment by lzutao** [comment] 2020-07-05 07:03
I think this is intentional behavior base on its MIR and how const works: <https://rust.godbolt.org/z/G-BPoi>.

**Comment by petrochenkov** [comment] 2020-07-05 07:07
cc https://github.com/rust-lang/rust-clippy/issues/829
(Also see the many issues linked to it.)

**Comment by leonardo-m** [comment] 2020-07-05 07:44
Is this better left in Clippy or better moved to Rustc? (I think the latter)

**Comment by CraftSpider** [comment] 2020-07-05 19:34
Ahhh, I get it. Because it's always inlined, the left hand is exactly equivalent to `<snip>.foo`, which is a valid assignment, but is immediately discarded. I'd definitely prefer the compiler warning, would make it much more clear what's going on.

**Comment by LeSeulArtichaut** [comment] 2020-07-06 15:56
Seems related to #16789. I also think we should emit an `unused_assignments` warn here, because this code behaves correctly, but is useless as the constant gets inlined but isn't assigned to a variable.

**Comment by Dylan-DPC** [comment] 2020-07-06 18:15
This doesn't require prioritisation. Removing it based on the [discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374053.20No.20warning.20on.20assigning.20to.20field.20of.20cons)

**Closed** 2020-09-10 08:07 UTC
Labels: A-lint, C-enhancement, D-newcomer-roadblock
