### ISSUE TITLE
Unused shadowing variable should suggest mutating the shadowed variable instead

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#91436] opened 2021-12-01 21:44 UTC
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4266164d35907aecdf2884e9f588b05e

```rust
let x = 5;
if maybe() {
    let x = 10;
}
used(x);
```

The current output is:

```
warning: unused variable: `x`
 --> src/main.rs:7:13
  |
7 |         let x = 10;
  |             ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default
```

Ideally, the compiler should notice that `x` shadows the outer binding, and suggest removing the `let` instead (and adding `mut`, if required).

This is likely the cause of this user's mistake: https://www.reddit.com/r/rust/comments/r5w7t0/why_does_this_not_work_completely_new_to_rust

If the outer binding is `mut`, the compiler even suggests removing the `mut` and silencing the unused warning, rather than making it actually assign to the outer binding.

```
warning: unused variable: `x`
 --> src/lib.rs:7:13
  |
7 |         let x = 10;
  |             ^ help: if this is intentional, prefix it with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: variable does not need to be mutable
 --> src/lib.rs:5:9
  |
5 |     let mut x = 5;
  |         ----^
  |         |
  |         help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default
```

**Comment by FabianWolff** [comment] 2021-12-07 00:29
Seems to be a duplicate of #84664.

**Comment by CAD97** [comment] 2021-12-10 00:43
Indeed.

**Closed** 2021-12-10 00:43 UTC
Labels: A-diagnostics, T-compiler
