### ISSUE TITLE
`repr(packed)` triggers internal compiler error

### ISSUE THREAD

**Issue by robsmith11** [rust-lang/rust#48638] opened 2018-03-01 13:24 UTC
Minimal example:
```
extern crate nalgebra;
use nalgebra::*;

#[repr(packed)]
struct S {
    x:Vector1<f64>,
}

fn main() {
}
```

```
$ rustc -vV
rustc 1.26.0-nightly (0ff9872b2 2018-02-28)
binary: rustc
commit-hash: 0ff9872b2280009f094af0df3dcdc542cc46a5fd
commit-date: 2018-02-28
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

```
$ cargo build
   Compiling err v0.1.0 (file:///tmp/err)
error: internal compiler error: librustc_typeck/check/wfcheck.rs:243: inference variables in nalgebra::Matrix<f64, nalgebra::U1, nalgebra::U1, nal\
gebra::MatrixArray<_, _, _>>
 --> src/main.rs:5:1
  |
5 | / struct S {
6 | |     x:Vector1<f64>,
7 | | }
  | |_^

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:482:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: core::ops::function::Fn::call
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:401
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: <std::thread::local::LocalKey<T>>::try_with
  11: <std::thread::local::LocalKey<T>>::with
  12: rustc::ty::context::tls::with
  13: rustc::ty::context::tls::with_opt
  14: rustc::session::opt_span_bug_fmt
  15: rustc::session::span_bug_fmt
  16: rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_type_defn::{{closure}}::{{closure}}::{{closure}}
  17: rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_item_well_formed
  18: <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item
  19: rustc_typeck::check_crate::{{closure}}
  20: rustc_typeck::check_crate
  21: rustc::ty::context::TyCtxt::create_and_enter
  22: rustc_driver::driver::compile_input
  23: rustc_driver::run_compiler

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (0ff9872b2 2018-02-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental -C target-cpu=native --crate-type bin
```

**Comment by gnzlbg** [comment] 2018-04-13 10:59
@bitshifter can you reproduce?

**Comment by bitshifter** [comment] 2018-04-13 11:15
@gnzlbg I can try, this is from Mar 2nd so not related to my recent changes right?

**Comment by bitshifter** [comment] 2018-04-13 11:27
@gnzlbg yes it fails for me with both stable rust 1.25 and the latest nightly rustc 1.27.0-nightly (ad610bed8 2018-04-11). It's not failing in a part of typeck that I'm familiar with but I'll have a look sometime and see if it makes any sense to me.

**Comment by gnzlbg** [comment] 2018-04-13 13:10
Yes this is unrelated to that PR (I think there isn't a nightly including it yet). But since this is related to `packed` I thought you might want to take a look.

**Comment by bitshifter** [comment] 2018-04-14 01:27
I started expanding the minimal example so that it didn't depend on nalgebra, it has expanded into quite a lot of code https://gist.github.com/bitshifter/afa4a3403802eebf9516ae7c3d174ba8

This example is enough to break the compiler but doesn't compile if the ICE is fixed (e.g. if the `#[repr(packed)]` is commented out). For it to compile it still needs some external dependencies.

It appears to be the associated type that is hitting the ICE.

**Comment by gnzlbg** [comment] 2018-04-14 09:17
Yeah @robsmith11 's example is huge. Maybe he doesn't know that minimal examples should have no dependencies.

**Comment by robsmith11** [comment] 2018-04-14 09:30
@gnzlbg 
I understand.  I'm a relative beginner to rust, so it would take quite a lot of time for me to figure out how to make a more minimal example.

I am able to work around this issue in my own code, so it's not that important to me, but I figured it might be easy for someone more experienced to spot what was going wrong.  If you don't think it's worth the effort to investigate further, I have no problem with you closing this until a more simple manifestation is discovered.

**Comment by gnzlbg** [comment] 2018-04-14 09:48
I've reduced it to the following (https://play.rust-lang.org/?gist=8678d365f2499392b15f00bc60eb42b8&version=stable):

```rust
pub trait D {}
pub struct DT;
impl D for DT {}

pub trait A<R: D>: Sized {
    type AS;
}

pub struct As<R: D>(R);

pub struct AT;
impl<R: D> A<R> for AT {
    type AS = As<R>;
}

#[repr(packed)] // comment to make this pass
struct S(<AT as A<DT>>::AS);

fn main() {}
```

**Comment by JohnTitor** [comment] 2019-10-14 00:11
It's no longer reproduced an ICE on the latest nightly, it seems from 1.38.0. marked as E-needstest

**Closed** 2019-10-14 13:51 UTC
Labels: A-attributes, C-bug, E-needstest, I-ICE, T-compiler
