### ISSUE TITLE
Cannot connect to abstract unix domain socket

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#52165] opened 2018-07-08 23:28 UTC
Hello,

I'm using stable Rust `1.27.0`.

According to `man 7 unix`, about abstract socket:

> an  abstract socket address is distinguished (from a pathname socket) by the fact that `sun_path[0]` is a `null` byte (`'\0'`).  The socket's address in this namespace is given by the additional bytes in `sun_path` that are covered by the specified length of the address structure.  (Null bytes in the name have  no  special  significance.)  The name has no connection with filesystem pathnames.  When the address of an abstract socket is returned, the returned `addrlen` is greater than `sizeof(sa_family_t)` (i.e., greater than 2), and the name of the socket is contained in the first `(addrlen  -  sizeof(sa_family_t))` bytes of `sun_path`.

I failed to run this:

```rust
use std::os::unix::net::UnixListener;
use std::path::PathBuf;

fn main() {
    let sock_path = PathBuf::from("\0test");
    match UnixListener::bind(&sock_path) {
        Ok(_) => println!("Server running at {:?}", &sock_path),
        Err(err) => eprintln!("Failed to start server: {}", &err),
    };
}
```

The error message was `paths may not contain interior null bytes`. I searched and found the code here:

<https://doc.rust-lang.org/src/std/sys/unix/ext/net.rs.html#61>

I consider this a bug, but I'm really not sure. May I ask if you could help?

Thank you,

**Comment by csmoe** [comment] 2018-07-09 02:33
cc https://github.com/rust-lang/rust/issues/14194
abstract socket is not supported right now.

**Comment by hkcorac** [comment] 2018-07-09 02:41
@csmoe 

Thank you. As I understand from that issue: abstract socket is not fully supported on all unix systems. However I think it would be great if the API simply returns any OS error. That won't break the `UnixListener::bind()` signature.

I'm not sure if I should close this issue. So I leave it open.

**Comment by Havvy** [comment] 2018-08-05 06:06
This is a dupe of #42048

**Closed** 2018-08-05 16:53 UTC
Labels: C-feature-request
