### ISSUE TITLE
regression: could not evaluate static initializer

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123277] opened 2024-03-31 17:04 UTC
```
[INFO] [stdout] error[E0080]: could not evaluate static initializer
[INFO] [stdout]    --> /rustc/c1195518c8ad7f37d15ecb82f39dec3da97f9c2f/library/core/src/num/nonzero.rs:335:21
[INFO] [stdout]     |
[INFO] [stdout]     = note: entering unreachable code
[INFO] [stdout]     |
[INFO] [stdout] note: inside `NonZero::<u32>::new_unchecked`
[INFO] [stdout]    --> /rustc/c1195518c8ad7f37d15ecb82f39dec3da97f9c2f/library/core/src/num/nonzero.rs:335:21
[INFO] [stdout] note: inside `Entry::new`
[INFO] [stdout]    --> src/lib.rs:154:17
[INFO] [stdout]     |
[INFO] [stdout] 154 |                 NonZeroU32::new_unchecked(c as u32)
[INFO] [stdout]     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout] note: inside `c`
[INFO] [stdout]    --> src/lib.rs:168:10
[INFO] [stdout]     |
[INFO] [stdout] 168 |     Some(Entry::new(c))
[INFO] [stdout]     |          ^^^^^^^^^^^^^
[INFO] [stdout] note: inside `MACROMAN`
[INFO] [stdout]    --> src/macroman.rs:2:2
[INFO] [stdout]     |
[INFO] [stdout] 2   |  c('\u{0000}'), c('\u{0001}'), c('\u{0002}'), c('\u{0003}'), c('\u{0004}'), c('\u{0005}'), c('\u{0006}'), c('\u{0007}'),
[INFO] [stdout]     |  ^^^^^^^^^^^^^
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/pdf_encoding-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/ClementNerma.Comic-Encoder/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/bennyboer.adobe-font-grabber/log.txt

This looks like UB to me, so probably an expected regression from additional checking the compiler is performing.

**Comment by workingjubilee** [comment] 2024-04-01 05:37
seems pdf-encoding 0.4.0 already exists: https://crates.io/crates/pdf_encoding

**Comment by apiraino** [comment] 2024-04-02 09:13
Yes, specifically in this [commit](https://togithub.com/pdf-rs/encoding/commit/f473ae1e8f0c1f262b00d6994136c6ff518f89d9) (IIUC)

@rustbot label -I-prioritize -needs-triage

**Comment by apiraino** [comment] 2024-10-12 09:05
Can this be closed since fixed by downstream?

@rustbot label -I-prioritize

**Comment by apiraino** [comment] 2024-10-15 09:00
Closing since regression is mentioned in the release notes

**Closed by apiraino** 2024-10-15 09:00 UTC
Labels: T-compiler, regression-from-stable-to-stable
