### ISSUE TITLE
Internal compiler error when running cargo tarpaulin

### ISSUE THREAD

**Issue by andy128k** [rust-lang/rust#49819] opened 2018-04-09 21:15 UTC
I've got this message when tried to run `cargo tarpaulin` for my [project](https://github.com/andy128k/getfavicon). 

cargo tarpaulin never worked on this project, but rustc's internal error is something new.

```
$ cargo tarpaulin
Building project
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive0.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive1.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive10.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive11.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive12.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive13.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive14.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive15.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive2.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive3.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive4.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive5.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive6.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive7.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive8.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.failure_derive9.rcgu.o" "-o" "/home/andy/projects/getfavicon/target/debug/deps/libfailure_derive-883b6509cf929391.so" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.crate.metadata.rcgu.o" "/home/andy/projects/getfavicon/target/debug/deps/failure_derive-883b6509cf929391.crate.allocator.rcgu.o" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/andy/projects/getfavicon/target/debug/deps" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/andy/projects/getfavicon/target/debug/deps/libsynstructure-6ef80717a69e6cad.rlib" "/home/andy/projects/getfavicon/target/debug/deps/libsyn-bbc9f13b2c0cc8ad.rlib" "/home/andy/projects/getfavicon/target/debug/deps/libsynom-a4234ecf1a591a4d.rlib" "/home/andy/projects/getfavicon/target/debug/deps/libunicode_xid-bd4939a0c587ed54.rlib" "/home/andy/projects/getfavicon/target/debug/deps/libquote-fe27e26531d06867.rlib" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-l" "proc_macro-7d531857c463fdf1" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax-a0f8084e7d2e8f23" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_errors-0442a147c1fbea3f" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_pos-a3c77f19bf623ee8" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_data_structures-6c5726675bdb8f04" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "term-74d3aea795746522" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "serialize-df58869bc5612287" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_cratesio_shim-f858a3ee752a9bb9" "-L" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-c10c01f750e28d27" "-Wl,-Bstatic" "/home/andy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-4e85b1507e729192.rlib" "-Wl,-Bdynamic" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util" "-shared" "-no-pie"
  = note: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crt1.o: In function `_start':
          (.text+0x20): undefined reference to `main'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: internal compiler error: librustc/ty/subst.rs:424: Region parameter out of range when substituting in region 'a (root type=Some(unsafe fn(*mut <Self as foreign_types::ForeignTypeRef>::CType) -> &'a mut Self {<Self as foreign_types::ForeignTypeRef>::from_ptr_mut::<'a>})) (index=1)

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:482:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0 (84203cac6 2018-03-25) running on x86_64-unknown-linux-gnu

Error during run
```
## Meta

```
$ rustc --version --verbose
rustc 1.25.0 (84203cac6 2018-03-25)
binary: rustc
commit-hash: 84203cac67e65ca8640b8392348411098c856985
commit-date: 2018-03-25
host: x86_64-unknown-linux-gnu
release: 1.25.0
LLVM version: 6.0
```

`cargo-tarpaulin version: 0.5.6`

**Comment by dtolnay** [comment] 2018-06-16 15:43
Based on the ICE message and the fact that cargo tarpaulin never worked on this project, I am going to guess this is a duplicate of #49362. If you are able to reproduce the crash with a smaller code sample and it is not like what is reported in that bug, please let us know. Thanks!

**Closed by dtolnay** 2018-06-16 15:43 UTC
Labels: I-ICE
