### ISSUE TITLE
Compiler crashed when rebuilding project in different OS

### ISSUE THREAD

**Issue by shanegibbs** [rust-lang/rust#35548] opened 2016-08-09 13:54 UTC
Project was built in linux. The `target` dir still existed when I tried compiling on MacOS.

I tried this code:

`cargo test`

I expected to see this happen: Rebuild project and run tests.

Instead, this happened: Compiler crashed
## Meta

`rustc --version --verbose`:

```
rustc 1.12.0-nightly (b30eff7ba 2016-08-05)
binary: rustc
commit-hash: b30eff7ba72a78e31acd61a2b6931919a0ad62e8
commit-date: 2016-08-05
host: x86_64-apple-darwin
release: 1.12.0-nightly
```

Backtrace:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:        0x1103b97fe - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:        0x1103c88ef - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:        0x1103c6dfd - std::panicking::default_hook::hbbe7fa36a995aca0
   4:        0x1103c7497 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:        0x1103c7354 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:        0x1103c7262 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:        0x1103c71c7 - rust_begin_unwind
   8:        0x110427a4d - core::panicking::panic_fmt::h19323e466869c656
   9:        0x110427954 - core::panicking::panic::hbfac80217e56ecbe
  10:        0x10bd704ae - rustc_trans::back::archive::ArchiveBuilder::build::h1952cdf1b375e1cb
  11:        0x10bd755e5 - rustc_trans::back::link::link_binary::h065439cf7e29e7cb
  12:        0x10b8b728d - rustc_driver::driver::phase_6_link_output::h5291117a6f0eac61
  13:        0x10b8a0750 - rustc_driver::driver::compile_input::hb4cc34cf85dc1edf
  14:        0x10b8c75b0 - rustc_driver::run_compiler::h50f95674bd902ab5
  15:        0x10b81729e - std::panicking::try::call::h4577500a5284c6ff
  16:        0x1103cf76a - __rust_maybe_catch_panic
  17:        0x10b82f791 - _<F as alloc..boxed..FnBox<A>>::call_box::h24f3eb0b42327962
  18:        0x1103c5ba5 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  19:     0x7fff9690399c - _pthread_body
  20:     0x7fff96903919 - _pthread_start

error: Could not compile `rust-crypto`.
```

**Comment by brson** [comment] 2016-08-12 20:11
Maybe the SVH or whatever mechanism we use for metadata consistency checks these days is not hashing target information.

**Comment by Mark-Simulacrum** [comment] 2017-05-10 23:59
I cannot reproduce today, closing.

**Closed by Mark-Simulacrum** 2017-05-10 23:59 UTC
Labels: I-ICE, I-wrong, T-compiler
