### ISSUE TITLE
Rustdoc renders the same feature gate twice

### ISSUE THREAD

**Issue by hirschenberger** [rust-lang/rust#67013] opened 2019-12-04 09:14 UTC
Rustdoc renders the same feature gate twice. See screenshots from this page:

https://docs.rs/tokio/0.2.2/tokio/sync/watch/index.html

![Screenshot_2019-12-04 tokio sync watch - Rust(1)](https://user-images.githubusercontent.com/1053180/70129271-b402e380-167e-11ea-9360-628dec0c1393.png)

![Screenshot_2019-12-04 tokio sync watch - Rust](https://user-images.githubusercontent.com/1053180/70129274-b7966a80-167e-11ea-9b32-7b0cd5ec0de3.png)

**Comment by sfackler** [comment] 2019-12-04 12:10
Duplicate of #66921

**Closed by sfackler** 2019-12-04 12:10 UTC
Labels: C-bug, T-rustdoc
