### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#113486] opened 2023-07-08 14:40 UTC
who's gonna triage this one?

**Comment by SparkyPotato** [comment] 2023-07-08 20:34
I think this was fixed in #c01efc6?

**Comment by ChrisDenton** [comment] 2023-07-08 20:59
Thank you for reporting this issue!

I spent some time looking into this today and now believe this is intended behaviour, thus I'm closing this as "working as intended". If you disagree then I'll be very happy to reopen.

**Closed by ChrisDenton** 2023-07-08 20:59 UTC
Labels: metabug
