### ISSUE TITLE
"can't create relative paths across filesystems" regression in rustc when using rpath

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#23204] opened 2015-03-08 22:02 UTC
rustc seems to have completely stopped working for me as of `rustc 1.0.0-nightly (270a677d4 2015-03-07) (built 2015-03-07)`. Every compile ends with:

```
101 brian@brianX1:~/dev/mvr⟫ RUST_BACKTRACE=1 rustc main.rs --test                                                                                                                                                                
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'can't create relative paths across filesystems', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_back/rpath.rs:115

stack backtrace:
   1:     0x7f9853a8c2d2 - sys::backtrace::write::he3277a63d69f5b66QBA
   2:     0x7f9853ab2322 - panicking::on_panic::h2a4421d00c8eaa07jHJ
   3:     0x7f98539f8a69 - rt::unwind::begin_unwind_inner::hb49f4d2d01640667mnJ
   4:     0x7f984cf622ac - rt::unwind::begin_unwind::h3368567567164428010
   5:     0x7f984cf727a0 - iter::Map<I, F>.Iterator::next::h3514843839896126350
   6:     0x7f984cf7062a - rpath::get_rpath_flags::h8689aee4bd8a62f8gOa
   7:     0x7f9853101ef6 - back::link::link_args::hfe241aaabc7064a0N8a
   8:     0x7f98530fb362 - back::link::link_natively::hc7581a064042a60bZYa
   9:     0x7f98530f5d81 - back::link::link_binary::h051d9e3fb98a999cVua
  10:     0x7f98540b2cfe - driver::phase_6_link_output::hb707e59c4a0a7cf4wQa
  11:     0x7f985408cfd9 - driver::compile_input::h4ead3acd85265c84Nba
  12:     0x7f9854150ebd - run_compiler::h297fa686def10927G6b
  13:     0x7f985414ec2c - thunk::F.Invoke<A, R>::invoke::h13212375243324058858
  14:     0x7f985414d880 - rt::unwind::try::try_fn::h15556897595580953244
  15:     0x7f9853b1e0f8 - rust_try_inner
  16:     0x7f9853b1e0e5 - rust_try
  17:     0x7f985414e00b - thunk::F.Invoke<A, R>::invoke::h6333748217615269386
  18:     0x7f9853a9fb25 - sys::thread::thread_start::h14dbe992a2cfcf49t8E
  19:     0x7f984daef181 - start_thread
  20:     0x7f985367147c - __clone
  21:                0x0 - <unknown>

```

I am using multirust, which uses the rpath flag to rustc, and I also do my development in a symlinked directory.

**Comment by mahkoh** [comment] 2015-03-08 22:50
Related: #23140

**Comment by alexcrichton** [comment] 2015-03-09 04:53
Yes, I believe this is a dupe of https://github.com/rust-lang/rust/issues/23140

**Closed by alexcrichton** 2015-03-09 04:53 UTC
Labels: A-libs, A-linkage
