### ISSUE TITLE
code can't be compiled for `wasm32-unknown-unknown` target with -Awarnings flag enabled

### ISSUE THREAD

**Issue by 1010adigupta** [rust-lang/rust#120106] opened 2024-01-18 18:27 UTC
this error appears:

```rust
error: output of --print=file-names missing when learning about target-specific information from rustc
command was: `.../.rustup/toolchains/nightly-2023-07-12-aarch64-apple-darwin/bin/rustc - --crate-name ___ --print=file-names -Awarnings --target wasm32-unknown-unknown --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg`
```
##Get the error:
Take any code that successfully compiles set the RUSTFLAG to -Awarnings with target wasm32-unknown-unknown then try to compile this code

**Comment by ehuss** [comment] 2024-01-18 19:15
Thanks for the report! I believe this is a duplicate of #116626, so closing in favor of that.

**Closed by ehuss** 2024-01-18 19:15 UTC
Labels: C-bug, needs-triage
