### ISSUE TITLE
Panic with 'Missing tokens for nt ";"' when passing statement to proc macro from declarative macro

### ISSUE THREAD

**Issue by Koxiaet** [rust-lang/rust#80760] opened 2021-01-06 19:31 UTC
This the the lib.rs of a proc macro crate `pm`:

```rust
use proc_macro::TokenStream;

#[proc_macro]
pub fn pm(input: TokenStream) -> TokenStream {
    // It works if this is `format!("{}", input)`
    format!("{:?}", input);
    TokenStream::new()
}
```

And here is the main.rs of another crate:

```rust
macro_rules! t {
    // It works if I take a tt
    ($s:stmt) => {
        pm::pm!($s);
    }
}

t!(;);
```

When building, this outputs:

```
error: proc macro panicked
 --> src/lib.rs:3:9
  |
3 |         pm::pm!($s);
  |         ^^^^^^^^^^^^
...
7 | t!(;);
  | ------ in this macro invocation
  |
  = help: message: Missing tokens at src/lib.rs:3:16: 3:18 (#6) for nt ";"
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

### Version it worked on

1.49.0, 1.50.0-beta.5

### Version with regression

rustc 1.51.0-nightly (da305a2b0 2021-01-05)  
binary: rustc  
commit-hash: da305a2b00530aa34dea4e48389204c26fa35dbb  
commit-date: 2021-01-05  
host: x86_64-unknown-linux-gnu  
release: 1.51.0-nightly

**Comment by camelid** [comment] 2021-01-06 21:02
cc #79812

**Comment by jyn514** [comment] 2021-01-07 10:37
cc @Aaron1011

**Comment by apiraino** [comment] 2021-01-07 10:46
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2380760.20Panic.20with.20'Missing.20tokens.20for.20nt.20.22.3B.22'.20when.20passing.20.E2.80.A6) and removing `I-prioritize`.

**Comment by pnkfelix** [comment] 2021-01-07 15:16
assigning to self to confirm if #79812 is the cause of the breakage, and if so, revert the PR until it can be revised to handle this case.

**Comment by Aaron1011** [comment] 2021-01-07 16:21
This is caused by us not handling `StmtKind::Empty` properly - I'm working on a fix.

**Comment by Aaron1011** [comment] 2021-01-07 16:44
Opened https://github.com/rust-lang/rust/pull/80789

**Closed** 2021-01-10 20:48 UTC
Labels: A-macros, A-proc-macros, C-bug, E-needs-bisection, P-high, T-compiler, regression-from-stable-to-nightly
