### ISSUE TITLE
Associated Type bounds not checked when checking for conflicting implementations of traits

### ISSUE THREAD

**Issue by ZerothLaw** [rust-lang/rust#52912] opened 2018-07-31 17:46 UTC
Not sure if this has already been brought up or discussed elsewhere, and if so, I apologize in advance. 

```rust
trait Xxx {
    type Target;
}
trait Yyy {}
trait Zzz {
    fn do_stuff(&self) -> i32;
}

struct Www{}
struct Uuu{}

struct Vvv {}
struct Qqq {}

impl Xxx for Vvv {
    type Target = Www;
}

//This is disallowed by the compiler
/*impl Xxx for Vvv {
    type Target = Uuu; 
}*/

impl<T> Zzz for T where T: Xxx<Target=Www> {
    fn do_stuff(&self) -> i32 {
        1
    }
}

//Therefore this should be possible. The two sets here are disjoint 
//with no possibility of overlap
impl<T> Zzz for T where T: Xxx<Target=Uuu> {
    fn do_stuff(&self) -> i32 {
        2
    }
}

fn main() {
}

```

([Playground](https://play.rust-lang.org/?gist=3633e14f4257fc9844ce014550b7fd89&version=stable&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0119]: conflicting implementations of trait `Zzz`:
  --> src/main.rs:32:1
   |
24 | impl<T> Zzz for T where T: Xxx<Target=Www> {
   | ------------------------------------------ first implementation here
...
32 | impl<T> Zzz for T where T: Xxx<Target=Uuu> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by dtolnay** [comment] 2018-08-13 08:14
Closing as a duplicate of #20400. Thanks anyway!

**Closed by dtolnay** 2018-08-13 08:14 UTC
