### ISSUE TITLE
Suggestion to use import to unstable feature on stable

### ISSUE THREAD

**Issue by Nokel81** [rust-lang/rust#86975] opened 2021-07-08 14:10 UTC
I tried this code:

```rust
trait DefaultResultOk<T: Default, E> {
    fn Ok() -> Result<T, E> {
        Ok(default())
    }
}

impl<T: Default, E> DefaultResultOk<T, E> for Result<T, E> {
    
}
```

I expected to see this happen: 

```
error[E0425]: cannot find function `default` in this scope
 --> src/lib.rs:3:12
  |
3 |         Ok(default())
  |            ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use std::default::Default::default;
  |
```

Instead, this happened:

```
error[E0425]: cannot find function `default` in this scope
 --> src/lib.rs:3:12
  |
3 |         Ok(default())
  |            ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use core::default::default;
  |
1 | use pin_utils::core_reexport::default::default;
  |
1 | use std::default::default;
  |
```

If I select the third option and compile again I get the following error:

```
error[E0658]: use of unstable library feature 'default_free_fn'
 --> src/lib.rs:1:5
  |
1 | use std::default::default;
  |     ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #73014 <https://github.com/rust-lang/rust/issues/73014> for more information
```

### Meta

`rustc --version --verbose`:
```
1.53.0
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3345aaf81ba391e16679c6af042c537f

**Comment by fmease** [comment] 2021-07-08 15:03
> I expected to see this happen:
> […]
> ```
> help: consider importing one of these items
>   |
> 1 | use std::default::Default::default;
>   |
> 
> ```

Note that you cannot import associated functions. So that suggestion shouldn't be there either.

```
error[E0253]: `default` is not directly importable
 --> src/lib.rs:1:5
  |
1 | use std::default::Default::default;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be imported directly
```

**Comment by Nokel81** [comment] 2021-07-08 15:05
Ah fair, still think the original suggestion is a bug though.

**Comment by jruderman** [comment] 2022-10-24 10:54
Duplicate of #78130?

**Comment by fmease** [comment] 2023-09-06 15:55
Closing as a duplicate of #78130. Feel free to raise objections

**Closed by fmease** 2023-09-06 15:55 UTC
Labels: A-diagnostics, C-bug
