### ISSUE TITLE
[rustbuild] should not rollback the submodules most of the time

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#42404] opened 2017-06-03 12:14 UTC
Currently rustbuild unconditionally forcefully checks out all the modules before building. This clashes with the workflow that probably should just work:

* Edit a submodule (could commit or not commit);
* Compile;

[rustbuild] will wipe all the changes, potentially losing significant amount of work. I’ve seen this happen to multiple people over time. Instead you have to do this:

* Edit a submodule;
* Commit changes to the submodule;
* Commit submodule update to the rustc repo;
* Compile

Which is super unobvious and failure prone. Miss any of the steps and your changes are wiped. My proposal would be to not forcefully checkout the submodules if the following are true:

* The working directory of the submodule is dirty;
* Submodule is “ahead” of the commit that would otherwise be checked out;

Potentially printing a warning or whatever.

**Comment by ollie27** [comment] 2017-06-04 15:21
You can add `submodules = false` to [`config.toml`](https://github.com/rust-lang/rust/blob/0da9721ab49d80bf74208e94a891b12c4a248507/src/bootstrap/config.toml.example#L108-L109) to disable the submodule handling. I assume the submodule handling is useful to someone but I just found it obnoxious and I'm perfectly capable of running `git submodule update --init` when I need to.

**Comment by nagisa** [comment] 2017-06-04 15:24
@ollie27 doesn’t help with rustbuild wiping out changes by default.

**Comment by Mark-Simulacrum** [comment] 2017-09-17 18:34
We need to remove/change [these lines](https://github.com/rust-lang/rust/blob/277476c4fb9e967ca28a7b529dbcf6b348cb787d/src/bootstrap/flags.rs#L316-L319) to do as @nagisa suggested above. I'm marking as needs-mentor, but if someone is familiar with git and would like to implement this, I'd be happy to review.

**Comment by jyn514** [comment] 2023-02-03 08:29
Duplicate of https://github.com/rust-lang/rust/issues/103485, which has been fixed :)

**Closed by jyn514** 2023-02-03 08:29 UTC
Labels: C-enhancement, T-bootstrap, E-needs-mentor
