### ISSUE TITLE
Cant compile rustc (phf_shared and std from two paths)

### ISSUE THREAD

**Issue by manfredbrandl** [rust-lang/rust#44981] opened 2017-10-02 16:33 UTC
Transcript:
```
manfred@xyz:~/src/rust$ ./x.py build --verbose
Updating submodules
running: git submodule -q sync
running: git submodule update --init --recursive src/llvm src/rt/hoedown src/jemalloc src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/doc/book src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri
running: git submodule -q foreach git reset -q --hard
running: git submodule -q foreach git clean -qdfx
running: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /home/manfred/src/rust/src/bootstrap/Cargo.toml --verbose
       Fresh num-traits v0.1.40
       Fresh getopts v0.2.15
       Fresh quote v0.3.15
       Fresh lazy_static v0.2.8
       Fresh itoa v0.3.4
       Fresh serde v1.0.15
       Fresh dtoa v0.4.2
       Fresh cc v1.0.0
       Fresh libc v0.2.31
       Fresh unicode-xid v0.0.4
       Fresh toml v0.4.5
       Fresh serde_json v1.0.3
       Fresh cmake v0.1.26
       Fresh num_cpus v1.6.2
       Fresh filetime v0.1.12
       Fresh synom v0.11.3
       Fresh build_helper v0.1.0 (file:///home/manfred/src/rust/src/build_helper)
       Fresh syn v0.11.11
       Fresh serde_derive_internals v0.16.0
       Fresh serde_derive v1.0.15
       Fresh bootstrap v0.0.0 (file:///home/manfred/src/rust/src/bootstrap)
    Finished dev [unoptimized] target(s) in 0.0 secs
running: /home/manfred/src/rust/build/bootstrap/debug/bootstrap build --verbose
finding compilers
CC_x86_64-unknown-linux-gnu = "cc"
AR_x86_64-unknown-linux-gnu = "ar"
CC_x86_64-unknown-linux-gnu = "cc"
AR_x86_64-unknown-linux-gnu = "ar"
CC_x86_64-unknown-linux-gnu = "cc"
AR_x86_64-unknown-linux-gnu = "ar"
CXX_x86_64-unknown-linux-gnu = "c++"
CXX_x86_64-unknown-linux-gnu = "c++"
running sanity check
...
running: "/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "24" "-v" "--release" "--manifest-path" "/home/manfred/src/rust/src/tools/rustdoc/Cargo.toml"
       Fresh bitflags v0.7.0
       Fresh cc v1.0.0
       Fresh void v1.0.2
       Fresh serde v1.0.15
       Fresh string_cache_shared v0.3.0
       Fresh quote v0.3.15
       Fresh siphasher v0.2.2
       Fresh precomputed-hash v0.1.0
       Fresh bitflags v0.8.2
       Fresh lazy_static v0.2.8
       Fresh libc v0.2.31
       Fresh unicode-xid v0.0.4
       Fresh rustc-serialize v0.3.24
       Fresh mac v0.1.1
       Fresh smallvec v0.3.3
       Fresh fnv v1.0.5
       Fresh matches v0.1.6
       Fresh procedural-masquerade v0.1.2
       Fresh log v0.3.8
       Fresh unreachable v0.1.1
       Fresh phf_shared v0.7.21
       Fresh filetime v0.1.12
       Fresh rand v0.3.16
       Fresh synom v0.11.3
       Fresh utf-8 v0.7.1
       Fresh env_logger v0.4.3
       Fresh debug_unreachable v0.1.1
       Fresh pulldown-cmark v0.0.14
       Fresh phf v0.7.21
       Fresh build_helper v0.1.0 (file:///home/manfred/src/rust/src/build_helper)
   Compiling phf_generator v0.7.21
       Fresh syn v0.11.11
       Fresh futf v0.1.3
       Fresh tendril v0.3.1
     Running `/home/manfred/src/rust/build/bootstrap/debug/rustc --crate-name phf_generator /home/manfred/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_generator-0.7.21/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=ebab8f8f4ab9095e -C extra-filename=-ebab8f8f4ab9095e --out-dir /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps -L dependency=/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps --extern phf_shared=/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libphf_shared-52a660f4c9fcee8a.rlib --extern rand=/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/librand-d3f6eabbea55abae.rlib --cap-lints allow`
error[E0460]: found possibly newer version of crate `std` which `phf_shared` depends on
 --> /home/manfred/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_generator-0.7.21/src/lib.rs:2:1
  |
2 | extern crate phf_shared;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: crate `std` path #1: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-5e8ebc384e5dfd82.rlib
  = note: crate `std` path #2: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-5e8ebc384e5dfd82.so
  = note: crate `phf_shared` path #1: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libphf_shared-52a660f4c9fcee8a.rlib

error: aborting due to previous error

error: Could not compile `phf_generator`.

Caused by:
  process didn't exit successfully: `/home/manfred/src/rust/build/bootstrap/debug/rustc --crate-name phf_generator /home/manfred/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_generator-0.7.21/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=ebab8f8f4ab9095e -C extra-filename=-ebab8f8f4ab9095e --out-dir /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps -L dependency=/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps --extern phf_shared=/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libphf_shared-52a660f4c9fcee8a.rlib --extern rand=/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/librand-d3f6eabbea55abae.rlib --cap-lints allow` (exit code: 101)


command did not execute successfully: "/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "24" "-v" "--release" "--manifest-path" "/home/manfred/src/rust/src/tools/rustdoc/Cargo.toml"
expected success, got: exit code: 101

Traceback (most recent call last):
  File "./x.py", line 20, in <module>
    bootstrap.main()
  File "/home/manfred/src/rust/src/bootstrap/bootstrap.py", line 756, in main
    bootstrap()
  File "/home/manfred/src/rust/src/bootstrap/bootstrap.py", line 747, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/home/manfred/src/rust/src/bootstrap/bootstrap.py", line 148, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /home/manfred/src/rust/build/bootstrap/debug/bootstrap build --verbose
manfred@xyz:~/src/rust$
```
full transcript: [transcript.txt](https://github.com/rust-lang/rust/files/1349599/transcript.txt)

**Comment by arielb1** [comment] 2017-10-03 09:04
Looks like a duplicate of #44739. Do the fix steps there work?

**Comment by manfredbrandl** [comment] 2017-10-03 15:16
The fix steps from #44739 did not help:
---
manfred@xyz:~/src/rust$ rm ./build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/*
manfred@xyz:~/src/rust$ ./x.py build
Updating submodules
    Finished dev [unoptimized] target(s) in 0.0 secs
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage1 test from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.0 secs
Copying stage1 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage2 compiler (x86_64-unknown-linux-gnu)
Uplifting stage1 std (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Copying stage2 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Uplifting stage1 test (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Copying stage2 test from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building rustdoc for stage2 (x86_64-unknown-linux-gnu)
   Compiling serde v1.0.15
   Compiling fnv v1.0.5
   Compiling log v0.3.8
   Compiling lazy_static v0.2.8
   Compiling string_cache_shared v0.3.0
   Compiling smallvec v0.3.3
   Compiling procedural-masquerade v0.1.2
   Compiling bitflags v0.8.2
   Compiling matches v0.1.6
   Compiling precomputed-hash v0.1.0
   Compiling mac v0.1.1
   Compiling bitflags v0.7.0
   Compiling void v1.0.2
   Compiling siphasher v0.2.2
   Compiling phf_generator v0.7.21
   Compiling pulldown-cmark v0.0.14
   Compiling unreachable v0.1.1
   Compiling utf-8 v0.7.1
error[E0460]: found possibly newer version of crate `std` which `phf_shared` depends on
 --> /home/manfred/.cargo/registry/src/github.com-1ecc6299db9ec823/phf_generator-0.7.21/src/lib.rs:2:1
  |
2 | extern crate phf_shared;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: crate `std` path #1: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-5e8ebc384e5dfd82.rlib
  = note: crate `std` path #2: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-5e8ebc384e5dfd82.so
  = note: crate `phf_shared` path #1: /home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libphf_shared-52a660f4c9fcee8a.rlib

error: aborting due to previous error

error: Could not compile `phf_generator`.
warning: build failed, waiting for other jobs to finish...
error: build failed


command did not execute successfully: "/home/manfred/src/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "24" "--release" "--manifest-path" "/home/manfred/src/rust/src/tools/rustdoc/Cargo.toml"
expected success, got: exit code: 101


failed to run: /home/manfred/src/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:00:15
manfred@xyz:~/src/rust$ cd ..
---

**Comment by TimNN** [comment] 2017-10-03 18:18
Can you try deleting all the `stage*` directories (or maybe start with `stage2*`)? That has usually "fixed" the problem in the past for me.

**Comment by manfredbrandl** [comment] 2017-10-04 08:58
`manfred@xyz:~/src/rust-compile-error$ rm -rf build/cache/* build/x86_64-unknown-linux-gnu/stage*`
solved the problem.

**Comment by sanmai-NL** [comment] 2017-12-27 20:16
@manfredbrandl: can this issue be closed?

**Closed** 2017-12-27 22:03 UTC
Labels: A-rustbuild, C-bug
