### ISSUE TITLE
Static checking

### ISSUE THREAD

**Issue by nujz** [rust-lang/rust#74174] opened 2020-07-09 04:05 UTC
I'm new here. I tried this code:

```rust
#![allow(dead_code)]
use std::marker::PhantomData;

struct Slice<'a, T: 'a> {
    start: *const T,
    end: *const T,
    phantom: PhantomData<&'a T>,
}

fn borrow_vec<T>(vec: &Vec<T>) -> Slice<'_, T> {
    let ptr = vec.as_ptr();
    Slice {
        start: ptr,
        end: unsafe { ptr.add(vec.len()) },
        phantom: PhantomData,
    }
}

fn f1() {
    let sl;
    {
        let vec = vec![1];
        sl = borrow_vec(&vec);
    }
    let __ = sl;
}

fn f2() {
    let sl;
    {
        let vec = vec![1];
        let ptr = vec.as_ptr();
        sl = Slice {
            start: ptr,
            end: unsafe { ptr.add(vec.len()) },
            phantom: PhantomData,
        };
    }
    let __ = sl;
}

fn main() {}
```

I expected to see this happen: *`fn f2()` compile failure*

Instead, this happened: *`fn f2()` compile success*

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (0cd7ff7dd 2020-07-04)
binary: rustc
commit-hash: 0cd7ff7ddfb75a38dca81ad3e76b1e984129e939
commit-date: 2020-07-04
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

**Comment by lcnr** [comment] 2020-07-09 09:28
Why do you expect `f2` to fail the compilation?

**Comment by lcnr** [comment] 2020-07-09 09:38
I think your concern is that`sl` contains a pointer to the storage of `vec`, which is dropped before the assignment `let __ = sl`.
This happens because raw pointers do not contain the lifetime of their target, and the lifetime of `PhantomData` is not bound to anything, so it can just be inferred to whatever compiles.

`fn borrow_vec<T>(vec: &Vec<T>) -> Slice<'_, T>` is syntactic sugar for `fn borrow_vec<'a, T:'a >(vec: &'a Vec<T>) -> Slice<'a, T>` resulting in the correct bound on the lifetime of `PhantomData`.

The issue tracker isn't really the best place for this, so please consider https://users.rust-lang.org/ or https://stackoverflow.com/ in case you have further questions about using rust.

**Comment by nujz** [comment] 2020-07-09 11:38
Thanks.

Does it mean that when using `PhantomData` the type constructor `Slice` must be wrapped  in a function?

It seems that `Slice` has `&Vec` in `f2`:

```rust
#![allow(dead_code)]
use std::marker::PhantomData;

struct Slice<'a, T: 'a> {
    start: *const T,
    // end: *const T,
    phantom: PhantomData<&'a T>,
}

fn borrow_vec<T>(vec: &Vec<T>) -> Slice<'_, T> {
    let ptr = vec.as_ptr();
    Slice {
        start: ptr,
        // end: unsafe { ptr.add(vec.len()) },
        phantom: PhantomData,
    }
}

fn f1() {
    let sl;
    {
        let vec = vec![1];
        sl = borrow_vec(&vec);
    }
    let __ = sl;
}

fn f2() {
    let sl;
    {
        let vec = vec![1];
        // let ptr = vec.as_ptr();
        sl = Slice {
            start: &vec,
            // end: unsafe { ptr.add(vec.len()) },
            phantom: PhantomData,
        };
    }
    let __ = sl;
}

fn main() {}
```

**Comment by jonas-schievink** [comment] 2020-07-09 11:54
Closing as this is not a bug. Please ask questions on https://users.rust-lang.org/.

**Closed by jonas-schievink** 2020-07-09 11:54 UTC
Labels: C-bug
