### ISSUE TITLE
_Unwind_Resume required for panic=abort again

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#34409] opened 2016-06-22 12:19 UTC
I'm using the `panic=abort` cargo profile option to disable unwinding. It compiled without problems [on nightly 2016-06-16](https://travis-ci.org/phil-opp/blog_os/builds/139156153) (and before), but throws a linker error [on nightly 2016-06-21](https://travis-ci.org/phil-opp/blog_os/builds/139444079):

```
target/x86_64-unknown-linux-gnu/debug/libblog_os.a(core-8102e29f.0.o): In function `core::fmt::write::hdac96890aec66a9a':
core.0.rs:(.text._ZN4core3fmt5write17hdac96890aec66a9aE+0x324): undefined reference to `_Unwind_Resume'
core.0.rs:(.text._ZN4core3fmt5write17hdac96890aec66a9aE+0x3eb): undefined reference to `_Unwind_Resume'
core.0.rs:(.text._ZN4core3fmt5write17hdac96890aec66a9aE+0x3f3): undefined reference to `_Unwind_Resume'
```

**Comment by alexcrichton** [comment] 2016-06-22 17:54
Just to clarify, but are you using the raw upstream libcore or recompiling it with `-C panic=abort`?

**Comment by phil-opp** [comment] 2016-06-23 09:45
I'm using the raw upstream libcore. Recompiling with `-C panic=abort` solves the problem.

So recompiling libcore etc. is required when using `panic=abort`?

**Comment by alexcrichton** [comment] 2016-06-23 21:16
Ah ok, in that case yeah I'm gonna close this as working as intended. Right now compiled binaries will have a dependency on `_Unwind_Resume` or various other symbols of the unwinding runtime, but to get rid of those entirely they'll have to be recompiled.

How it ever worked before is somewhat beyond me, but linkers do tend to do magical things after all!

**Closed by alexcrichton** 2016-06-23 21:16 UTC

**Comment by phil-opp** [comment] 2016-06-24 09:36
Thanks for the explanation!

**Comment by haxxpop** [comment] 2018-09-17 17:57
Any guide how to recompile libcore with ` -C panic=abort` ?

**Comment by phil-opp** [comment] 2018-10-09 10:48
@haxxpop You can add a `"panic-strategy": "abort"` key to your target toml and then use [cargo-xbuild](https://github.com/rust-osdev/cargo-xbuild) to recompile libcore etc. for your target.
