### ISSUE TITLE
unused_imports lint fails to trigger on traits that are considered but rejected

### ISSUE THREAD

**Issue by wthrowe** [rust-lang/rust#29920] opened 2015-11-19 02:09 UTC
This compiles:
```rust
#![forbid(unused_imports)]

mod foo {
    pub trait Tr {
        fn func(&self) {}
    }
    impl Tr for u8 {}

    pub trait Tr2 {
        fn func(&self);
    }
}

fn main() {
    use foo::Tr;
    use foo::Tr2; // This is unused
    1u8.func();
}
```

**Comment by sanxiyn** [comment] 2015-11-23 05:45
Closing as a duplicate of #25730.

**Closed by sanxiyn** 2015-11-23 05:45 UTC
