### ISSUE TITLE
Matching strings in beta and nightly

### ISSUE THREAD

**Issue by hank-der-hafenarbeiter** [rust-lang/rust#35044] opened 2016-07-26 14:30 UTC
when matching &str in nightly or beta the following code always returns the first match case:
```rust

#[derive(Debug, PartialEq)]
enum Reg {
    EAX,
    EBX,
    ECX,
    EDX,
    ESP,
    EBP,
    ISP,
}

fn string_to_reg(_s:&str) -> Reg {
    match _s.as_ref() {
        "EAX" => Reg::EAX,
        "EBX" => Reg::EBX,
        "ECX" => Reg::ECX,
        "EDX" => Reg::EDX,
        "EBP" => Reg::EBP,
        "ESP" => Reg::ESP,
        "ISP" => Reg::ISP,
        &_    => panic!("bla bla bla"),  //removing this "&" fixes it
    }
}

fn main() {
    let vec = vec!["EAX", "EBX", "ECX", "EDX", "ESP", "EBP", "ISP"];
    let mut iter = vec.iter();
    println!("{:?}", string_to_reg(""));
    println!("{:?}", string_to_reg(iter.next().unwrap()));
    println!("{:?}", string_to_reg(iter.next().unwrap()));
    println!("{:?}", string_to_reg(iter.next().unwrap()));
    println!("{:?}", string_to_reg(iter.next().unwrap()));
    println!("{:?}",  string_to_reg(iter.next().unwrap()));     
    println!("{:?}", string_to_reg(iter.next().unwrap()));
    println!("{:?}",  string_to_reg(iter.next().unwrap()));
}

```
Expected behaviour is returning the fitting case. This can be fixed by removing the "&" in front of the last case. 

##Meta

tested on my machine with: rustc 1.11.0-nightly (bb4a79b08 2016-06-15)
tested on [here](http://play.integer32.com/) with beta and nightly showing the bug and stable giving a runtime error.

**Comment by oli-obk** [comment] 2016-07-26 15:59
The MIR looks fine, and it works fine with `-Zorbit` enabled

**Comment by arielb1** [comment] 2016-07-27 06:04
I think I broke old trans `_match` with my slice-patterns PR (#32202).

**Comment by DemiMarie** [comment] 2016-07-29 03:33
Can we enforce MIR trans whenever slice patterns are in use?

**Comment by nikomatsakis** [comment] 2016-08-04 20:13
Discussed in @rust-lang/compiler meeting -- @arielb1 is going to try and revert PR #32202 on the beta branch only to fix this or else find a fix. We don't have to do anything on nightly because it's correct in MIR -- though it means that old trans is kind of broken.

Also, @arielb1 says it's all @eddyb's fault. ;)

**Comment by nikomatsakis** [comment] 2016-08-11 20:19
Update from @rust-lang/compiler meeting. @eddyb took a stab at fixing it but did not succeed. The problem is that, in the old code, literals (like `"foo"`) and `&_` are considered incompatible, and hence the match code just kind of does the wrong thing.

@eddyb points out that, on stable, this code does not currently compile. So to fix this for beta we could add some custom check that denies using `&` pattern to match an `&str` type. Or just using the old check-match.

**Comment by nikomatsakis** [comment] 2016-08-18 20:22
This is actually fixed on beta.

**Closed** 2016-08-18 20:22 UTC
Labels: I-wrong, P-high, regression-from-stable-to-beta, T-compiler
