### ISSUE TITLE
Can't compile rust 1.3.0 with Hombrew on OSX

### ISSUE THREAD

**Issue by jingweno** [rust-lang/rust#29133] opened 2015-10-18 01:22 UTC
```
$ brew install rust                                                     ==> Downloading https://static.rust-lang.org/dist/rustc-1.3.0-src.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/rust-1.3.0.tar.gz
==> ./configure --prefix=/opt/boxen/homebrew/Cellar/rust/1.3.0 --enable-clang --release-channel=stable
==> make
==> make install
==> Cloning https://github.com/rust-lang/cargo.git
Updating /opt/boxen/cache/homebrew/rust--cargo--git
==> Checking out tag 0.5.0
Synchronizing submodule url for 'test/rust-installer-v1'
Synchronizing submodule url for 'test/rust-installer-v2'
Synchronizing submodule url for 'test/rust-installer-v1'
==> Downloading https://static-rust-lang-org.s3.amazonaws.com/cargo-dist/2015-09-17/cargo-nightly-x86_
Already downloaded: /opt/boxen/cache/homebrew/rust--cargo-nightly-2015-09-17-nightly.tar.gz
==> ./install.sh --prefix=/private/tmp/rust--cargo20151017-41156-1txgsr0/target/snapshot/cargo
==> ./configure --prefix=/opt/boxen/homebrew/Cellar/rust/1.3.0 --local-rust-root=/opt/boxen/homebrew/C
==> make
Last 15 lines from /Users/owen/Library/Logs/Homebrew/rust/06.make:
   Compiling docopt v0.6.70
   Compiling toml v0.1.22
   Compiling curl v0.2.11
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to open archive") }) }', src/libcore/result.rs:732


Build failed, waiting for other jobs to finish...
Could not compile `libgit2-sys`.

To learn more, run the command again with --verbose.
make: *** [cargo-x86_64-apple-darwin] Error 101

READ THIS: https://git.io/brew-troubleshooting

Warning:
```

**Comment by DomT4** [comment] 2015-10-18 01:48
They'll probably find `brew gist-logs rust` useful.

**Comment by jingweno** [comment] 2015-10-18 01:50
`brew gist-logs rust`: https://gist.github.com/anonymous/65ff95aad491e3c9df92

**Comment by caipre** [comment] 2015-10-18 20:22
Duplicate of #29052, the error in both cases being `Could not compile 'libgit2-sys'.`

**Comment by steveklabnik** [comment] 2015-10-29 20:51
Yes, seems to be. Closing as a duplicate.

**Closed by steveklabnik** 2015-10-29 20:51 UTC
