### ISSUE TITLE
Can't reference function-scoped type from function-scoped module

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#114369] opened 2023-08-02 11:56 UTC
I tried this code:

```rust
fn main() {
    enum Outer {
        A,
        B,
    }
    
    mod inner {
        #[allow(unused_imports)]
        use super::*; // I was hoping this would help, but doesn't...
        
        // How do I reference the `Outer` type from here?
        type Foo = Outer;
    }
}
```

I expected to see this happen: I would expect it to compile, or to be a way of referencing `Outer`.

Instead, this happened:

```
error[E0412]: cannot find type `Outer` in this scope
```

The context is that I changed a macro from expanding to a plain function to expanding to a module (https://github.com/servo/rust-cssparser/pull/353), but that broke code that used that macro with a type from a function.

A workaround I found is to just expand to an empty type and use associated functions, rather than a module, but seems unfortunate :)

**Comment by emilio** [comment] 2023-08-02 12:05
For reference the work around is https://github.com/servo/rust-cssparser/pull/354. The code that wouldn't build otherwise would be [this](https://searchfox.org/mozilla-central/rev/85269d4444c2553e7f4c669fe4de72d64f4fe438/servo/components/style/properties/properties.mako.rs#1965-1993).

**Comment by fmease** [comment] 2023-08-02 20:34
Duplicate of #79260.

**Comment by ChrisDenton** [comment] 2023-08-11 11:58
Closing as duplicate of #79260.

**Closed by ChrisDenton** 2023-08-11 11:58 UTC
Labels: C-bug
