### ISSUE TITLE
rust-lld fails with "dyld: Library not loaded: @rpath/libLLVM.dylib" on rustc 1.48.0-nightly (bbc677480 2020-09-18)

### ISSUE THREAD

**Issue by ssundarr3** [rust-lang/rust#76921] opened 2020-09-19 13:32 UTC
`rust-lld --help` fails on rustc 1.48 nightly (it seems libLLVM.dylib is not included in this nightly version):
```
➜  ~ rustc --version
rustc 1.48.0-nightly (bbc677480 2020-09-18)
➜  ~ $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
dyld: Library not loaded: @rpath/libLLVM.dylib
  Referenced from: /Users/shridhar/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/rust-lld
  Reason: image not found
[1]    1641 abort      $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
```

It works on `rustc 1.46.0 (04488afe3 2020-08-24)`:
```
➜  ~ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
➜  ~ $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
```

This issue was fixed in rustc 1.30.0-nightly [here](https://github.com/rust-lang/rust/issues/53813). And it also works for me on rustc 1.30.0-nightly: 
```
➜  ~ rustc --version
rustc 1.30.0-nightly (2f1547c0a 2018-09-11)
➜  ~ $(rustc --print sysroot)/lib/rustlib/x86_64-apple-darwin/bin/rust-lld --help
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-lld (WebAssembly) instead
```

I am on MacOS Catalina version 10.15.16.

**Comment by jyn514** [comment] 2020-09-19 14:47
Duplicate of https://github.com/rust-lang/rust/issues/76698

**Closed by jyn514** 2020-09-19 14:47 UTC
Labels: C-bug
