### ISSUE TITLE
Confusing error message with `download-ci-llvm` on old checkout

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#107506] opened 2023-01-31 09:13 UTC
CI artifacts get deleted after a while, so using `download-ci-llvm` on old checkouts doesn't work. When the CI artifacts return a 404, bootstrap should note that the checkout might be outdated.

The current message is quite confusing, especially because it says "spurious failure", when it is not spurious at all.

```
spurious failure, trying again
downloading https://ci-artifacts.rust-lang.org/rustc-builds/8db8f48ea8c2443e969050fe4b6c829585048d5c/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
curl: (22) The requested URL returned error: 404
```

**Comment by albertlarsan68** [comment] 2023-01-31 09:23
(Personal opinion) I think bootstrap should fall back to building LLVM with a warning if CI LLVM is not available and the option is set to `if-available`. If the option is set to true, it should error and print a possible solution. This would allow the current workaround for the tier2 w/ host tools debug-assertions build (added in #107234) to be deleted.

**Comment by albertlarsan68** [comment] 2023-01-31 14:59
In any way, the benefits of any fixes will only be seen 180 days after the fix is merged.
cc @rust-lang/bootstrap Please select:
1. We just detect this case and print a pretty message with the fix
2. We fall back to building LLVM with a warning when `donwload-ci-llvm = "if-available"` and use 1. when `download-ci-llvm = true` (my choice)
3. We keep the status quo
4. Other possibilities?

**Comment by jyn514** [comment] 2023-01-31 15:18
> The current message is quite confusing, especially because it says "spurious failure", when it is not spurious at all.

Note that this has changed since the issue was opened:

```
downloading https://ci-artifacts.rust-lang.org/rustc-builds/c35035cefc709abddabfb28ecc6a326458d46ce2/rust-dev-nightly-x86_64-apple-darwin.tar.xz
curl: (22) The requested URL returned error: 404                                                                                                                                                          

error: failed to download llvm from ci

    help: old builds get deleted after a certain time
    help: if trying to compile an old commit of rustc, disable `download-ci-llvm` in config.toml:

    [llvm]
    download-ci-llvm = false
```

Given that I don't think this issue is super high priority. That said, I still have roughly the same opinion as in https://github.com/rust-lang/rust/issues/107225#issuecomment-1400519344:

> > The build should not fail if CI LLVM is not found, it should be built from source instead (is this the real bug?)

> 👍 this seems useful as long as the error is a 404, but we shouldn't build from source if static.rust-lang.org is having trouble (people should have to explicitly opt-in).

I do have some concerns that this will be hard to do correctly (e.g. large parts of src/bootstrap are loading this directly from config.toml and we need to make sure they're kept in sync) and also that it will "silently" regress compile times because people won't realize something has gone wrong.

I think until we find a bug that we *can't* solve by not trying to download the commits in the first place, we should continue solving the problem that way, both because it avoids an unnecessary network call and because it seems simpler than doing the logic dynamically.

**Comment by ozkanonur** [comment] 2023-01-31 17:07
> 2. We fall back to building LLVM with a warning when `donwload-ci-llvm = "if-available"` and use 1. when `download-ci-llvm = true` (my choice)

This seems good idea but I think we should do this only on certain errors. For example, if the problem is host-side(maybe user had temporary network problem on the bootstraping process), we can print the error and right after that let the user make this decision (start building LLVM from source or kill the process) via command prompt.

**Comment by jyn514** [comment] 2023-01-31 18:40
tbh I feel like the current error message already gives enough info to fix the problem and any additional work is overkill.

**Comment by jyn514** [comment] 2023-02-03 05:24
@Nilstrieb gave a 👍 so I'm going to assume that means this is solved.

**Closed by jyn514** 2023-02-03 05:24 UTC
Labels: T-bootstrap
