### ISSUE TITLE
ICE Compiling rustc_hir

### ISSUE THREAD

**Issue by JeremyRubin** [rust-lang/rust#102942] opened 2022-10-12 02:44 UTC
apologies if this is not too useful since it's coming out of CI for a private repo, and I don't have a minimal reproduction, but the following error came up so adding a report here:

```
thread 'rustc' panicked at 'unexpected unresolved segments', /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/compiler/rustc_hir/src/def.rs:475:9
[88](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:89)
stack backtrace:
[89](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:90)
   0:     0x7f8c09da75b0 - std::backtrace_rs::backtrace::libunwind::trace::h0bf6f02637fe6971
[90](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:91)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[91](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:92)
   1:     0x7f8c09da75b0 - std::backtrace_rs::backtrace::trace_unsynchronized::hca573de4ebdee142
[92](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:93)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
[93](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:94)
   2:     0x7f8c09da75b0 - std::sys_common::backtrace::_print_fmt::h78a3b0f3fa5431ce
[94](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:95)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:66:5
[95](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:96)
   3:     0x7f8c09da75b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h388012888db78658
[96](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:97)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:45:22
[97](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:98)
   4:     0x7f8c09e0359e - core::fmt::write::h8541eee12bfb22e1
[98](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:99)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/fmt/mod.rs:1209:17
[99](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:100)
   5:     0x7f8c09d97835 - std::io::Write::write_fmt::haf5892ef07750179
[100](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:101)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/io/mod.rs:1680:15
[101](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:102)
   6:     0x7f8c09daa353 - std::sys_common::backtrace::_print::hd2a58ab324867b58
[102](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:103)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:48:5
[103](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:104)
   7:     0x7f8c09daa353 - std::sys_common::backtrace::print::h62650e0a0854a421
[104](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:105)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:35:9
[105](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:106)
   8:     0x7f8c09daa353 - std::panicking::default_hook::{{closure}}::h0c0249b3670af819
[106](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:107)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:267:22
[107](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:108)
   9:     0x7f8c09daa02a - std::panicking::default_hook::hdd3bdd204a1e5f34
[108](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:109)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:286:9
[109](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:110)
  10:     0x7f8c0c6e6641 - rustc_driver[1f63e0707e3aafaf]::DEFAULT_HOOK::{closure#0}::{closure#0}
[110](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:111)
  11:     0x7f8c09daab8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f493fd9c4eb244a
[111](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:112)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1952:9
[112](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:113)
  12:     0x7f8c09daab8b - std::panicking::rust_panic_with_hook::hcdeb5a66936a633b
[113](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:114)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:673:13
[114](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:115)
  13:     0x7f8c09daa9e7 - std::panicking::begin_panic_handler::{{closure}}::h76d64f438650eafd
[115](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:116)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:560:13
[116](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:117)
  14:     0x7f8c09da7a5c - std::sys_common::backtrace::__rust_end_short_backtrace::h6159ba2d4e07f4de
[117](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:118)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys_common/backtrace.rs:138:18
[118](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:119)
  15:     0x7f8c09daa702 - rust_begin_unwind
[119](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:120)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/panicking.rs:556:5
[120](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:121)
  16:     0x7f8c09e00173 - core::panicking::panic_fmt::h811742b56cf0125a
[121](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:122)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:142:14
[122](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:123)
  17:     0x7f8c09e00031 - core::panicking::panic_display::h6303aa0d1e0b1fa9
[123](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:124)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:72:5
[124](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:125)
  18:     0x7f8c09dfffdb - core::panicking::panic_str::hbb50b0306ce7b150
[125](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:126)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/panicking.rs:56:5
[126](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:127)
  19:     0x7f8c09dffd16 - core::option::expect_failed::h4c43dc39e1c41a00
[127](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:128)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/core/src/option.rs:1876:5
[128](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:129)
  20:     0x7f8c0b3cd199 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor as rustc_ast[10d65a8be6722286]::visit::Visitor>::visit_fn
[129](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:130)
  21:     0x7f8c0b3bd736 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
[130](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:131)
  22:     0x7f8c0b3c90a6 - rustc_ast[10d65a8be6722286]::visit::walk_item::<rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>
[131](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:132)
  23:     0x7f8c0b3b86a1 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
[132](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:133)
  24:     0x7f8c0b3c90a6 - rustc_ast[10d65a8be6722286]::visit::walk_item::<rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>
[133](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:134)
  25:     0x7f8c0b3b86a1 - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor>::resolve_item
[134](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:135)
  26:     0x7f8c0b3b51ea - <rustc_resolve[290e47d8627a4365]::late::LateResolutionVisitor as rustc_ast[10d65a8be6722286]::visit::Visitor>::visit_item
[135](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:136)
  27:     0x7f8c0b3b5016 - <rustc_resolve[290e47d8627a4365]::Resolver>::late_resolve_crate
[136](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:137)
  28:     0x7f8c0b3b492a - <rustc_session[8b98ba4aacc9d309]::session::Session>::time::<(), <rustc_resolve[290e47d8627a4365]::Resolver>::resolve_crate::{closure#0}>
[137](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:138)
  29:     0x7f8c0b3b28c3 - <rustc_interface[cf2fa28a67e8bef]::passes::boxed_resolver::BoxedResolver>::access::<<rustc_interface[cf2fa28a67e8bef]::queries::Queries>::expansion::{closure#0}::{closure#0}, core[fae631be8e3c81b5]::result::Result<rustc_ast[10d65a8be6722286]::ast::Crate, rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
[138](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:139)
  30:     0x7f8c0b39d688 - <rustc_interface[cf2fa28a67e8bef]::queries::Queries>::expansion
[139](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:140)
  31:     0x7f8c0b39b39c - <rustc_interface[cf2fa28a67e8bef]::interface::Compiler>::enter::<rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}::{closure#2}, core[fae631be8e3c81b5]::result::Result<core[fae631be8e3c81b5]::option::Option<rustc_interface[cf2fa28a67e8bef]::queries::Linker>, rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
[140](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:141)
  32:     0x7f8c0b39643c - rustc_span[ddec628aeed15f05]::with_source_map::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#1}>
[141](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:142)
  33:     0x7f8c0b395e3f - rustc_interface[cf2fa28a67e8bef]::interface::create_compiler_and_run::<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>
[142](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:143)
  34:     0x7f8c0b395032 - <scoped_tls[4da31d6f3f5146b7]::ScopedKey<rustc_span[ddec628aeed15f05]::SessionGlobals>>::set::<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
[143](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:144)
  35:     0x7f8c0b39450f - std[7bd0f41fe60b70b6]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>
[144](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:145)
  36:     0x7f8c0b39437f - <<std[7bd0f41fe60b70b6]::thread::Builder>::spawn_unchecked_<rustc_interface[cf2fa28a67e8bef]::util::run_in_thread_pool_with_globals<rustc_interface[cf2fa28a67e8bef]::interface::run_compiler<core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>, rustc_driver[1f63e0707e3aafaf]::run_compiler::{closure#1}>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#0}, core[fae631be8e3c81b5]::result::Result<(), rustc_errors[d5334a4a25fbb394]::ErrorGuaranteed>>::{closure#1} as core[fae631be8e3c81b5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
[145](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:146)
  37:     0x7f8c09db4793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc67cb2c032770d7f
[146](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:147)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
[147](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:148)
  38:     0x7f8c09db4793 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he79e59a805a8533c
[148](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:149)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/alloc/src/boxed.rs:1938:9
[149](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:150)
  39:     0x7f8c09db4793 - std::sys::unix::thread::Thread::new::thread_start::hae509166483801f9
[150](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:151)
                               at /rustc/db0597f5619d5ed93feca28e61226d3581cc7867/library/std/src/sys/unix/thread.rs:108:17
[151](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:152)
  40:     0x7f8c09c7b609 - start_thread
[152](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:153)
  41:     0x7f8c09b9e133 - clone
[153](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:154)
  42:                0x0 - <unknown>
[154](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:155)

[155](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:156)
error: internal compiler error: unexpected panic
[156](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:157)

[157](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:158)
note: the compiler unexpectedly panicked. this is a bug.
[158](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:159)

[159](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:160)
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
[160](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:161)

[161](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:162)
note: rustc 1.66.0-nightly (db0597f56 2022-10-11) running on x86_64-unknown-linux-gnu
[162](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:163)

[163](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:164)
note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2
[164](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:165)

[165](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:166)
note: some of the compiler flags provided by cargo are hidden
[166](https://github.com/judica-org/mining-game/actions/runs/3231569000/jobs/5291230901#step:5:167)

```

**Comment by compiler-errors** [comment] 2022-10-12 05:27
This is a duplicate of #102946 (well, chronologically that issue is a duplicate of this one, but that issue has an MCVE :stuck_out_tongue_winking_eye: )

**Comment by JeremyRubin** [comment] 2022-10-12 06:06
cool closing as dup

**Closed** 2022-10-12 06:06 UTC
Labels: I-ICE, T-compiler, C-bug
