### ISSUE TITLE
Ice on build after weird character fix.

### ISSUE THREAD

**Issue by joachimm** [rust-lang/rust#93247] opened 2022-01-23 20:38 UTC
I got the below error when building locally,

### Code

I haven't been able to minimize the code, in fact I cannot repeat the error despite making a git commit of the exact code when the error was occurring. If you think the code would help with investigating I can supply it, but I would rather not in its current state.

For context:
I had a compile issue due to junk characters that I accidentally inserted (I have a "kvm" switch, for my mouse/keyboard job/home computer setup, and it sometimes makes the keyboard output weird charachters after switching).

```
$> cargo run
   Compiling langservice v0.1.0 (/Users/joachimm/Projects/langservice)
error: unknown start of token: \u{b4}
   --> src/main.rs:103:45
    |
103 |     use std::collections::HashMap;ƒ         ´Ω
    |                                             ^
    |
help: Unicode character '´' (Acute Accent) looks like ''' (Single Quote), but it is not
    |
103 |     use std::collections::HashMap;ƒ         'Ω
    |                                             ~

error: expected one of `!` or `::`, found `Ω`
   --> src/main.rs:103:46
    |
103 |     use std::collections::HashMap;ƒ         ´Ω
    |                                              ^ expected one of `!` or `::`

error: could not compile `langservice` due to 2 previous errors
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `warp::filter::or::Or<impl warp::filter::Filter+core::clone::Clone, impl warp::filter::Filter+core::clone::Clone>: warp::filter::Filter`
#1 [typeck] type-checking `filters::routes`
end of query stack
```

**Comment by canndrew** [comment] 2022-01-26 04:34
I just ran into this. Seems like a dupe of (at least) #93125, #93096, #93020 and #93013.

**Comment by Aaron1011** [comment] 2022-01-26 04:40
This should be fixed on the latest nightly

**Comment by workingjubilee** [comment] 2023-02-26 12:00
This is almost certainly a duplicate of this issue and was probably resolved in this PR:
- https://github.com/rust-lang/rust/issues/92987
- https://github.com/rust-lang/rust/pull/93064

**Closed by workingjubilee** 2023-02-26 12:00 UTC
Labels: I-ICE, T-compiler, C-bug
