### ISSUE TITLE
Adding `#[inline]` to function results in 10x slowdown when used in another crate

### ISSUE THREAD

**Issue by CeleritasCelery** [rust-lang/rust#107617] opened 2023-02-03 00:09 UTC
I am encountering an odd issue where adding the #[inline] annotation to a public function leads to it performing 10x worse in the criterion benchmark. This function is a SIMD implementation of character counting. Interestingly I only see the major slow down when benchmarking the SIMD version. If I switch it out for the scalar version, the inline annotation has no effect. I am also not able to reproduce this issue on x86_64, only with Aarch64 (Apple Silicon).

Here is the repo/branch used to reproduce the issue.

https://github.com/CeleritasCelery/str_indices/tree/benchmark_issue

Here is the call site in the benchmarks:

https://github.com/CeleritasCelery/str_indices/blob/benchmark_issue/benches/all.rs#L45-L64

and here are the function defintions:

https://github.com/CeleritasCelery/str_indices/blob/benchmark_issue/src/chars.rs#L8-L15

if you clone that repo on Aaarch64 and run `cargo criterion` I get

chars::count/en_10000   time:   306.93 *ns*
chars::count_inline/en_10000 3.1082 *µs*

so almost exactly 10x slower.

I opened an issue on the criterion repo with https://github.com/bheisler/criterion.rs/issues/649 but this seems like a code generation issue, and a pretty severe one at that.

#### EDIT: 
Here is the assembly dump for the [inline](https://gist.github.com/CeleritasCelery/69b46ca4be67dacf073f0b90576a8d07) and [non-inline](https://gist.github.com/CeleritasCelery/7b9754ee9fb3b886d6b53189a304516e) versions. Generated using [this](https://github.com/CeleritasCelery/rust_simd_inline_regression) repo.

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-beta.1 (efd27454a 2023-01-25)
binary: rustc
commit-hash: efd27454ae94386e11997b1158f60d3a79deeb7d
commit-date: 2023-01-25
host: aarch64-apple-darwin
release: 1.68.0-beta.1
LLVM version: 15.0.6
```

**Comment by workingjubilee** [comment] 2023-02-03 03:29
Normally rustc supports --emit=asm for this case but it's hard to support that for cargo commands so most simply do not. So your choices are finding a way to avoid criterion yet generate the same result, or finding the object file that criterion creates and using objdump on it.

As you have opened the same issue in two locations it feels like the logical thing to do is post the same response in both locations. Please enjoy the bounty of reading the same thing twice.

**Comment by saethlin** [comment] 2023-02-03 04:37
I'm on x86_64. I cannot reproduce a 10x difference, but I can reproduce a smaller difference. I'll post the output of criterion below, with the unimportant lines deleted. The inconsistent indentation is from criterion.

By default I see this:
```
chars::count/en_10000   time:   [201.76 ns 202.10 ns 202.48 ns]
chars::count_inline/en_10000
                        time:   [311.65 ns 311.99 ns 312.36 ns]
```

Adding `codegen-units = 1` to `[profile.release]` I get this:
```
chars::count/en_10000   time:   [199.83 ns 199.99 ns 200.16 ns]
chars::count_inline/en_10000
                        time:   [192.16 ns 192.28 ns 192.41 ns]
```

Adding `codegen-units = 1` and `lto = "fat"` I get this:
```
chars::count/en_10000   time:   [309.54 ns 309.66 ns 309.82 ns]
chars::count_inline/en_10000
                        time:   [198.52 ns 198.68 ns 198.83 ns]
```

The sequence of instructions in the tiny loop that's the target of the benchmark is exactly the same in all cases. I think this benchmark is highly sensitive to some aspect that LLVM doesn't or can't control. The alignment of the loop seems likely. 

This is a common problem in microbenchmarking, and I am not aware of any good solutions to it. Emery Berger did a project called Stabilizer which doesn't work anymore (it's tightly coupled to LLVM internals and an academic doesn't have the time to keep up with LLVM versions), but the explanation of the problem is pretty good: https://youtu.be/r-TLSBdHe1A There is a GitHub repo and a paper, they're pretty easy to find if you want to learn more.

I will also do my part to keep the duplicate issue you opened in sync.

**Comment by CeleritasCelery** [comment] 2023-02-03 05:48
Thanks for looking into this. I will watch the video you posted by Berger.

> I'm on x86_64. I cannot reproduce a 10x difference,

I was not able to reproduce it on x86 either. I am curious if others can reproduce on Aarch64.

I don't so much care about the microbenchmark, but I am concerned that someone would use this code is real world applications and hit the pathological worst case on get terrible performance. 10x slowdown is massive.

I tried the two options you suggested, and using a single code gen unit made no difference, but adding fat lto completely resolved the issue.

```
chars::count/en_10000   time:   [305.08 ns 305.20 ns 305.36 ns]
                        change: [-2.5422% -2.1875% -1.8291%] (p = 0.00 < 0.05)
                        Performance has improved.

chars::count_inline/en_10000
                        time:   [305.10 ns 305.27 ns 305.46 ns]
                        change: [-90.217% -90.196% -90.176%] (p = 0.00 < 0.05)
                        Performance has improved.
```

> The sequence of instructions in the tiny loop that's the target of the benchmark is exactly the same in all cases. I think this benchmark is highly sensitive to some aspect that LLVM doesn't or can't control. The alignment of the loop seems likely.

Are you referring to code alignment or data alignment? The simd routine only operates on aligned chunks, and I have reproduced the issue on strings over a million bytes. I wouldn't think that would be an issue.

> I will also do my part to keep the duplicate issue you opened in sync.
No need. I was not sure if this was criterion specific issue or was related to codegen. Since it seems to be the later I will close that in favor of this one. I appreciate the considerateness though.

**Comment by saethlin** [comment] 2023-02-04 14:51
I agree this is a shockingly large amount of variance for such a situation. Perhaps @nikic can offer some wisdom? Is this worth reporting to LLVM? I don't have experience with aarch64 so I don't know if this kind of performance swing is more typical on that architecture.

@rustbot label +A-LLVM

**Comment by saethlin** [comment] 2023-02-04 14:56
> completely resolved the issue.

FYI I do not think this is a correct characterization. I'm just toggling codegen flags to give LLVM cause to lay things out a bit differently. Since we get the same instructions with very different runtime performance across settings, I suspect there is no relevant optimization you've enabled with LTO. You just got lucky and any actual use of your library outside of benchmarks may see LTO be slower.

**Comment by CeleritasCelery** [comment] 2023-02-04 17:58
> FYI I do not think this is a correct characterization. I'm just toggling codegen flags to give LLVM cause to lay things out a bit differently.

I am suspicious of code layout being the root cause. I have tried to perturb the layout by adding dummy function, rearranging things, removing code etc. Nothing has made a measurable difference in performance gap.

And also it is not just this one particular function. This crate has many functions in different modules that count things like types of newlines, unicode separators, and byte offsets. All the functions exhibit the same behavior where the inline version runs 7-10x slower then the non-inline version. I would be shocked if every function had the same alignment issue. And this only shows up when simd is enabled, the scalar versions show no difference in performance.

**Comment by CeleritasCelery** [comment] 2023-02-06 14:48
I tried running the benchmark using the LLVM flags `-align-all-functions`, `-align-all-blocks`, and `-align-all-nofallthru-blocks` with values between 0 and 8 (256 byte alignment). None of the options did anything to close 10x performance gap between the inline and non-inline versions. I see this as more evidence that alignment is not to blame.

**Comment by workingjubilee** [comment] 2023-02-07 02:08
Does this still replicate if you remove all cases of `#[inline(always)]` and replace them with only `#[inline]` at most?

Does this still replicate if you remove the rest of the crate's code and leave only the necessary parts for the benchmarks? Or do the benchmarks have sufficient coverage to include the entire crate?

I will take a closer look at this. Which Apple Silicon SoC are you using to replicate this? Some of them have significantly different performance features. It is starting to sound like there is a runaway or degenerate behavior during LLVM inlining.

**Comment by CeleritasCelery** [comment] 2023-02-07 05:17
> Does this still replicate if you remove all cases of #[inline(always)] and replace them with only #[inline] at most?

Yes, there is no change if I replace them with `#[inline]` or remove the attribute entirely. 

> Does this still replicate if you remove the rest of the crate's code and leave only the necessary parts for the benchmarks?

Yes, if I removed all code but the char counting routine I still see the issue. Though there are many different SIMD routines in different modules within this crate and they all exhibit the same behavior (inline version about 10x slower then non-inline).

> Which Apple Silicon SoC are you using to replicate this? 

I have a 10-core M1 Pro in a MacBook Pro

**Comment by thomcc** [comment] 2023-02-07 15:42
I've seen this kind of thing a bunch before but don't have advice beyond "yeah, sometimes optimizations are nondeterministic". It's unfortunate.

It does feel like this issue in particular (where the precise placement of inline determines how well LLVM manages to optimize everything else) has gotten way worse lately.

**Comment by CeleritasCelery** [comment] 2023-02-07 18:36
> yeah, sometimes optimizations are nondeterministic

I recognize that, but decreasing performance by an entire order of magnitude seems like it is beyond the realm of just "non-deterministic optimizer". That is catastrophic failure of the optimizer and codegen.

**Comment by CeleritasCelery** [comment] 2023-02-07 20:23
> previous cases where inlining causes LLVM to use scalar instructions instead of vector instructions.

The scalar version is as fast as the SIMD version, so I don't think that is this particular issue.

> Calling this "catastrophic" doesn't help. A reproducer that anyone can observe would.

I certainly didn't intend calling it catastrophic to offend anyone. I am not placing blame. But I would consider this pretty catastrophic to performance.

I provided a [reproducer](https://github.com/CeleritasCelery/str_indices/tree/benchmark_issue) in the original issue. Not sure if anyone has had the right hardware to reproduce it yet though. I am anxious to see if others can.

Here is the assembly dump for the [inline](https://gist.github.com/CeleritasCelery/69b46ca4be67dacf073f0b90576a8d07) and [non-inline](https://gist.github.com/CeleritasCelery/7b9754ee9fb3b886d6b53189a304516e) versions. They are certainly different, but I am not able to determine which of those differences are meaningful. I generated those with [this](https://github.com/CeleritasCelery/rust_simd_inline_regression) repo.

**Comment by workingjubilee** [comment] 2023-02-07 23:09
"An entire full-fledged library crate" as a reproducer is... painful to go through. As you already have observed, dumping the assembly from benchmark tooling is nontrivial. I asked you to try removing everything and seeing if it still works because that's what I want to see: a minimal, verifiable, complete example. No dependencies, no `cargo`, something that can be compiled and run with *just* `rustc`.

We can trim it down to such a minimal, complete, verifiable example (MCVE) by hand, and I will eventually get around to it, but if I do that busywork and get a different result because I make a mistake in what to cull, that's not going to be very helpful for you or me.

**Comment by CeleritasCelery** [comment] 2023-02-08 00:11
is [this](https://github.com/CeleritasCelery/rust_simd_inline_regression) simple enough?

I unfortunately can't reproduce this issue within a single crate. It has to inline across crates (which is why I think LTO ["fixed" it for me](https://github.com/rust-lang/rust/issues/107617#issuecomment-1415045392)). So I moved only the code needed to reproduce it into a [sub-crate](https://github.com/CeleritasCelery/rust_simd_inline_regression/blob/master/str_indices/src/lib.rs) and [call the functions](https://github.com/CeleritasCelery/rust_simd_inline_regression/blob/master/src/lib.rs) from the main library. That will be buildable with just `rustc`. I left the benchmarks so that others can reproduce runtime discrepancy.

This is should make it easy dump the assembly for them, because the inline version is part of a wrapper function. That is how I dumped the assembly [earlier](https://github.com/rust-lang/rust/issues/107617#issuecomment-1421395786). Let me know if there is more work I need to do to create a MCVE. I appreciate your feedback and help.

**Comment by workingjubilee** [comment] 2023-02-08 04:49
> I unfortunately can't reproduce this issue within a single crate. It has to inline across crates (which is why I think LTO https://github.com/rust-lang/rust/issues/107617#issuecomment-1415045392).

Ohhh? Now _that's_ interesting to hear as a detail. In that case yes, it's understandable to have less than the most minimal possible example, but also changes significantly what is likely going on.

**Comment by thomcc** [comment] 2023-02-08 04:50
The issue here is you forgot to add any kind of inline to [this function](https://github.com/CeleritasCelery/rust_simd_inline_regression/blob/master/str_indices/src/byte_chunk.rs#L222).


Generally rustc compiles different crates separately, so if you want to call a function inside another crate, it will not be inlined unless the function in was marked `#[inline]`/`#[inline(always)]` (or is generic). Conversely, often it can inline functions found inside the same crate, even without inline hints.

This means when the compiler is compiling `count` (the non-`inline` version), it's able to see the implementation of `<Chunk as ByteChunk>::add` since it's inside the same crate, and inline it right away. However, for `count_inline`, it's actually not fully compiled until the point where it's called, which in this case is inside the other crate (the benchmarks). At that point, it doesn't have the source for `<Chunk as ByteChunk>::add` and needs to make a call. LTO fixes this because it has access to just about everything, ofc.

This can be figured out by noticing [this call](https://github.com/CeleritasCelery/rust_simd_inline_regression/blob/f82987622ee417e513c76ac5cc9a1d6b980cb778/inlined.s#L225), or possibly by running in a profiler, but... if you're going to do Rust SIMD code I would gently recomend that you learn to identify function calls in assembly. There are *several* easy to make mistakes (specifically target_feature mismatch in particular) that will lead to all your intrinsic use ending up as function calls.

**Comment by thomcc** [comment] 2023-02-08 04:53
I'm going to close this because it's the expected behavior. It's a subtle footgun, but it's hardly unique

**Closed by thomcc** 2023-02-08 04:53 UTC
Labels: A-LLVM, C-bug

**Comment by CeleritasCelery** [comment] 2023-02-08 05:02
Thank you @thomcc. This is was my first attempt at SIMD in Rust, so I appreciate coaching and tips. Everyone on this thread has been extremely helpful.

**Comment by saethlin** [comment] 2023-02-08 05:37
Is this case caught by this lint? https://rust-lang.github.io/rust-clippy/v0.0.212/#missing_inline_in_public_items

**Comment by CeleritasCelery** [comment] 2023-02-08 05:48
No, because the trait is only `pub(crate)`. If I make it `pub` then that lint catches it.

**Comment by thomcc** [comment] 2023-02-08 06:33
This is a different problem, it's really a case of "non-`#[inline]` function called transitively from a pub `#[inline]` function" which is a lot harder to meaningfully lint for since often enough it's fine or even desirable, just not if that function is in a tight loop.
