### ISSUE TITLE
`main` function has to implement wrong type.

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#21134] opened 2015-01-14 10:17 UTC
This is under the assumption that `main` should receive the same arguments and have the same return type as in C if it has the `#[start]` attribute:

Currently, the `#[start]` function has to have the type:

    fn main(argc: isize, argv: *const *const u8) -> isize;

This is not an accurate translation of the C prototype, it has to be

    fn main(argc: c_int, argv: *const *const u8) -> c_int;

And it's even wrong on `x86_64`, where `isize = i64` and `c_int = i32`.

**Comment by huonw** [comment] 2015-01-14 12:34
Dupe of https://github.com/rust-lang/rust/issues/20064.

There's no particular reason that we *have* to match the C types, the Rust compiler just needs to e.g. create a shim function that does the appropriate casts (it's not like the return value of `c_int` is that correct anyway: POSIX systems only look at the lower byte).

**Closed by huonw** 2015-01-14 12:34 UTC
