### ISSUE TITLE
tuple structs with all-public fields can not be instantiated if one of the fields has an external attribute

### ISSUE THREAD

**Issue by DarkKirb** [rust-lang/rust#66555] opened 2019-11-19 20:23 UTC
In current nightly (2019-11-18 and also 2019-11-16) and stable (1.39.0), tuple structs can not be instantiated from an outside module directly if

- all of the members are public
- at least one of the struct members has an attribute (like `#[serde(rename = "some_name")]`)

Example code that is broken:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7108f99f96b03247b7d44bdf47091a1a

In the same module the code works:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a896f6f28a050228c4e91d9e3bcc5557

Same with normal structs:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2083f2cae68b7378652bd239bb122d20

The broken code works in 1.38.0: 

https://godbolt.org/z/_8KX6P

## Meta

One of the affected installations:
```
rustc 1.41.0-nightly (5c5b8afd8 2019-11-16)
binary: rustc
commit-hash: 5c5b8afd80e6fa1d24632153cb2257c686041d41
commit-date: 2019-11-16
host: x86_64-apple-darwin
release: 1.41.0-nightly
LLVM version: 9.0
```

**Comment by Erk-** [comment] 2019-11-19 20:30
It seems to only happen with external attributes. Attributes like `#[deprecated]` and similar does not show this bug.

**Comment by petrochenkov** [comment] 2019-11-19 20:39
Minimized:
```rust
mod m {
    pub struct S(#[rustfmt::skip] pub u8);
}

fn main() {
    m::S(0);
}
```

**Comment by pnkfelix** [comment] 2019-11-21 13:35
Based on @petrochenkov 's assertion that this was introduced by PR #63468, marking this as a stable-to-stable regression.

**Comment by pnkfelix** [comment] 2019-11-22 09:35
Marking P-high for, though that's mostly because of the risk that a crate might rely on being able to use struct literal expressions in other modules, and then a later version of that crate wants to put an attribute on of the fields of the struct literal.

**Comment by petrochenkov** [comment] 2019-11-23 14:41
Fixed in https://github.com/rust-lang/rust/pull/66669.

**Closed** 2019-11-25 08:59 UTC
Labels: A-attributes, A-visibility, C-bug, P-high, T-compiler, regression-from-stable-to-stable
