### ISSUE TITLE
Generated debuginfo may apparently be ill-formed

### ISSUE THREAD

**Issue by vberger** [rust-lang/rust#27324] opened 2015-07-27 12:57 UTC
Coming from an issue with kcov, here: https://github.com/SimonKagstrom/kcov/issues/105

Apparently, the debuginfo generated in rust executables causes kcov to sometimes put breakpoints in the middle of some instructions. According to kcov developper, it is possibly because the debuginfo generated by rustc is ill-formed.

**Comment by alexcrichton** [comment] 2015-07-27 16:15
cc @michaelwoerister

**Comment by michaelwoerister** [comment] 2015-08-08 08:18
I'm pretty sure this has to be an error on the LLVM side. We are just assigning line numbers/scope ids to LLVM instructions, so what we do should be correct by construction (i.e. there is no way to tell LLVM "this line starts in the middle of this instruction").

With a minimal test case it would be possible to look at the LLVM IR generated by rustc and continue from there, and may try if something similar can be produced with clang.

**Comment by TheDoctorsLife** [comment] 2016-06-26 17:16
Any update on this?

**Comment by Mark-Simulacrum** [comment] 2017-05-06 03:15
Closing due to lack of ability to reproduce. Please do provide an example if you can, and we'll happily reopen!

**Comment by kw217** [comment] 2017-06-19 12:51
Very easy to repro:
```
$ uname -a
Linux <REDACTED> 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cargo init --bin hello
     Created binary (application) project
$ cd hello/
$ cargo build
   Compiling hello v0.1.0 (file:///data/ksw/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 0.42 secs
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/hello`
Hello, world!
$ cargo kcov
kcov: 121 invalid breakpoints skipped in /data/ksw/hello/target/debug/deps/hello-fb494c4f8a209fbc
[..]
$ kcov --verify --debug=4 foo target/debug/hello-fb494c4f8a209fbc
kcov: Address 0x17252 is not at an instruction boundary, skipping
kcov: Address 0x99a8c is not at an instruction boundary, skipping
kcov: Address 0x99b53 is not at an instruction boundary, skipping
kcov: Address 0x99c02 is not at an instruction boundary, skipping
kcov: Address 0x99cac is not at an instruction boundary, skipping
[..lots of others omitted..]
```
Using `objdump -d -g` to examine the binary, we see things like this:
```
  99a7c:       48 8d 0d bd d3 04 00    lea    0x4d3bd(%rip),%rcx        # e6e40 <je_index2size_tab>
   99a83:       4c 8b 34 c1             mov    (%rcx,%rax,8),%r14
   99a87:       89 54 24 0c             mov    %edx,0xc(%rsp)
   99a8b:       64 48 8b 04 25 00 00    mov    %fs:0x0,%rax
   99a92:       00 00 
   99a94:       48 8d 80 b0 ff ff ff    lea    -0x50(%rax),%rax
[..]
  [0x0003b1ca]  Special opcode 159: advance Address by 11 to 0x99a7c and Line by 0 to 635
  [0x0003b1cb]  Set File Name to entry 3 in the File Name Table
  [0x0003b1cd]  Advance Line by 1181 to 1816
  [0x0003b1d0]  Special opcode 229: advance Address by 16 to 0x99a8c and Line by 0 to 1816
```
which appears to the untrained eye to point file 3:line 1816 to the middle of the `mov %fs:0x0,%rax` instruction.

**Comment by kw217** [comment] 2017-09-07 13:49
Hi - any progress on this one? There's a simple repro above. I believe this is likely to be the cause of many inaccuracies in kcov coverage output. @michaelwoerister @Mark-Simulacrum how can I help progress this bug?

**Comment by michaelwoerister** [comment] 2017-09-07 14:01
@kw217, sorry nobody has had time to look into this, I'm afraid. One thing that might be helpful is trying to reproduce this problem in a recent clang version, to see if this is a general LLVM problem or if we are just using it incorrectly.

**Comment by kw217** [comment] 2017-09-07 14:02
@michaelwoerister thanks, I'll see what I can do.

**Comment by pkgw** [comment] 2018-01-23 03:46
FWIW, I've just been trying to get kcov working with a Rust project of my own. I've found that things work if I use an `--include-path=$(pwd)` argument to limit `kcov` to only insert breakpoints in code connected to the project at hand. This leads me to believe that the busted debug info might be somewhere in the Rust standard libraries as distributed by rustup. Or perhaps my OS, but I'm running this on a stock Ubuntu VM so I'd imagine that the debugging symbols there are likely to be OK.

**Comment by wesleywiser** [comment] 2022-07-18 15:10
Visited during wg-debugging triage. This doesn't appear to be a Rust specific issue, rather there is something wrong with libpthread and libgcc_s. Here's a repro in C:

```
$ cat test.c
int main() { }
$ clang -g test.c -o c_test -lgcc_s -lpthread
$ kcov --verify --debug=4 foo c_test
Cannot open linux-vdso.so.1
No debug symbols in /lib/x86_64-linux-gnu/libgcc_s.so.1.
kcov: Address 0x6000 is not at an instruction boundary, skipping
kcov: Address 0x10875 is not at an instruction boundary, skipping
kcov: Address 0x10881 is not at an instruction boundary, skipping
kcov: Address 0x1089c is not at an instruction boundary, skipping
kcov: Address 0x13022 is not at an instruction boundary, skipping
CRC mismatch for debug link /lib/x86_64-linux-gnu/libc-2.31.so. Should be 0xf854b801, is 0xef41b1a0!
No debug symbols in /lib/x86_64-linux-gnu/libc.so.6.
CRC mismatch for debug link /lib/x86_64-linux-gnu/libdl-2.31.so. Should be 0xf334bb32, is 0x2bb25318!
No debug symbols in /lib/x86_64-linux-gnu/libdl.so.2.
No debug symbols in /lib64/ld-linux-x86-64.so.2.
```

Now if we stop linking with those libraries:

```
$ cat test.c
int main() { }
$ clang -g test.c -o c_test
$ kcov --verify --debug=4 foo c_test
Cannot open linux-vdso.so.1
CRC mismatch for debug link /lib/x86_64-linux-gnu/libc-2.31.so. Should be 0xf854b801, is 0xef41b1a0!
No debug symbols in /lib/x86_64-linux-gnu/libc.so.6.
CRC mismatch for debug link /lib/x86_64-linux-gnu/libdl-2.31.so. Should be 0xf334bb32, is 0x2bb25318!
No debug symbols in /lib/x86_64-linux-gnu/libdl.so.2.
No debug symbols in /lib64/ld-linux-x86-64.so.2.
```

and those are the same issues I see when running a Rust "hello world" locally: 

```
$ kcov --verify --debug=4 foo target/debug/deps/hello-c008976f04459533
Cannot open linux-vdso.so.1
No debug symbols in /lib/x86_64-linux-gnu/libgcc_s.so.1.
kcov: Address 0x6000 is not at an instruction boundary, skipping
kcov: Address 0x10875 is not at an instruction boundary, skipping
kcov: Address 0x10881 is not at an instruction boundary, skipping
kcov: Address 0x1089c is not at an instruction boundary, skipping
kcov: Address 0x13022 is not at an instruction boundary, skipping
CRC mismatch for debug link /lib/x86_64-linux-gnu/libm-2.31.so. Should be 0x658b15c9, is 0x3cfca93f!
No debug symbols in /lib/x86_64-linux-gnu/libm.so.6.
CRC mismatch for debug link /lib/x86_64-linux-gnu/libdl-2.31.so. Should be 0xf334bb32, is 0x2bb25318!
No debug symbols in /lib/x86_64-linux-gnu/libdl.so.2.
CRC mismatch for debug link /lib/x86_64-linux-gnu/libc-2.31.so. Should be 0xf854b801, is 0xef41b1a0!
No debug symbols in /lib/x86_64-linux-gnu/libc.so.6.
No debug symbols in /lib64/ld-linux-x86-64.so.2.
```

because it links with libgcc_s and libpthread:

```
$ ldd target/debug/deps/hello-c008976f04459533
        linux-vdso.so.1 (0x00007fff71dce000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6d0e15a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6d0e137000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6d0dfe8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6d0dfe2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6d0ddf0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6d0e30c000)
```

Since this isn't a Rust problem, I'm going to go ahead and close this issue.

**Closed by wesleywiser** 2022-07-18 15:10 UTC
Labels: A-debuginfo, C-bug
