### ISSUE TITLE
A public fn in a private mod with a private type in its signature

### ISSUE THREAD

**Issue by IvanUkhov** [rust-lang/rust#25934] opened 2015-05-31 20:50 UTC
If a crate has a private module and a private type, the module cannot have a public function whose signature refers to the private type. Here is an [illustration](https://play.rust-lang.org/?gist=838f72a133d193c3d953&version=stable):

```rust
type Baz = isize;

mod foo {
    use Baz;

    pub fn bar(_: Baz) { // error: private type in exported type signature
    }
}
```

The public function cannot presumably be qualified as a [public-facing part](https://github.com/rust-lang/rfcs/blob/master/text/0136-no-privates-in-public.md) of the crate, and it is not presumably a [part of the public API](https://github.com/rust-lang/rust/pull/17401) of the crate.

Regards,
Ivan

**Comment by tomjakubowski** [comment] 2015-05-31 21:05
You can use `pub use Baz` inside the foo module. The idea is that the identifier `Baz` inside the module `foo` is private to it; you might some day replace `use Baz` with something like `type Baz = String` and suddenly break users of that module without appearing to change any public signatures.

Y

**Comment by IvanUkhov** [comment] 2015-05-31 21:10
@tomjakubowski, thank you for the response. But there are no users of that module as the module is private to the crate. `pub se Baz` inside the modules does not seem to help; the error in that case is `error: Baz is private`. `super` does not seem to help either. Could you please clarify what you have in mind?

**Comment by tomjakubowski** [comment] 2015-05-31 21:13
There are users of the module inside the crate. I don't mean users in the sense of people using it, just that other pieces of code ("users") are using it.

Anyway, it looks like I've internalized some old rules of privacy or something. Whoops. My mistake.

**Comment by alexcrichton** [comment] 2015-06-01 16:53
This is a dupe of https://github.com/rust-lang/rust/issues/25532 and https://github.com/rust-lang/rust/issues/25260, both of which are intended behavior, so closing (more details in those issues).

**Closed by alexcrichton** 2015-06-01 16:53 UTC
