### ISSUE TITLE
Inconsistency in Required where clauses on GAT 

### ISSUE THREAD

**Issue by zylthinking** [rust-lang/rust#110593] opened 2023-04-20 10:57 UTC
For trait `LendingIterator` and struct `WindowsMut<'t, T>`
```rust
trait LendingIterator {
    type Item<'a> ;
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>>;
    fn do_check(checker: Self::Item<'_>) {}
}

struct WindowsMut<'t, T> {
    slice: &'t mut T,
    start: usize,
    window_size: usize,
}

```
The following impl compiles, no requiring where clauses because of  `do_check` :

```rust
impl<'t> LendingIterator for WindowsMut<'t, bool> {
    type Item<'a> = &'a bool;

    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>> {
        None
    }
}

```
meaning GAT can conclude `'t : 'a`; 

but the following fails:
```rust
impl<'t, T> LendingIterator for WindowsMut<'t, T> {
    type Item<'a> = &'a T;

    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>> {
        None
    }
}
```

reporting:
> the parameter type `T` may not live long enough

Seems `Self : 'a` is not necessary, because return value of next may not be related to self, for example:

```rust
trait LendingIterator {
    type Item<'a>;
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>>;
}

struct WindowsMut<'t, T> {
    slice: &'t mut T,
    start: usize,
    window_size: usize,
}

impl<'t, T> LendingIterator for WindowsMut<'t, T> {
    type Item<'a> = &'a bool;

    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>> {
        Some(&true)
    }
}
```

but reports missing required bound on `Item`
```
error: missing required bound on `Item`
 --> src/lib.rs:4:5
  |
4 |     type Item<'a>;
  |     ^^^^^^^^^^^^^-
  |                  |
  |                  help: add the required where clause: `where Self: 'a`
  |
  = note: this bound is currently required to ensure that impls have maximum flexibility
  = note: we are soliciting feedback, [see issue #87479 <https://github.com/rust-lang/rust/issues/87479>](https://github.com/rust-lang/rust/issues/87479) for more information
```

And when it does reference Self, `&'a self` already indicates `T: 'a`

**Comment by jyn514** [comment] 2023-04-20 11:24
here is the full error message:
```

error[E0309]: the parameter type `T` may not live long enough
  --> src/lib.rs:14:21
   |
14 |     type Item<'a> = &'a T;
   |                     ^^^^^- help: consider adding a where clause: `where T: 'a`
   |                     |
   |                     ...so that the reference type `&'a T` does not outlive the data it points at

For more information about this error, try `rustc --explain E0309`.
error: could not compile `playground` due to previous error
```
So the problem is not inferring `'t: 'a`, but `T: 'a`.

I am not sure this is a bug? What here implies `T: 'a` for an arbitrary `'a`? Or is the idea that the bound should be added automatically somehow?

**Comment by jackh726** [comment] 2023-04-21 02:42
So, there's really two different sources of requirements that are at play here.

First is requirements for where clauses on GATs in traits, which is based solely on how the GAT is used in the trait. Importantly, we only require bounds that are provable in *every* use of the GAT. First your first example, no bounds are required, because `do_check` uses it without bounds. Removing that function later causes us to complain about missing required bounds.

The second source of requirements here is the well-formedness of associated types in impls. For your first impl, the type is `&'a bool`, which requires no bounds (because `bool: 'static`). However, later, using `&'a T` does require that we know that `T: 'a`. However, we don't know that anyone, because we didn't add the where clause in the trait. This is precisely why these required bounds rules were added.

Our concerns when designing these were actually focused around these being *too strict*. Seems like this is a pattern (having a method that takes a GAT without `&self`) where the rules are actually too lenient.

Interestingly, changing `do_check` to `fn do_check<'a>(&'a self, checker: Self::Item<'a>) {}` causes us to spit out the required bounds error.

While *technically* backwards-incompatible, I would be open to considering slight modifications to the required bounds logic that patch up this hole (provided a well-motivated and complete example of this coming up, a clear, straightforward, and simple adjustment, and a clean crater run). However, I'm going to close this issue (but can reopen with some action on the above).

**Closed by jackh726** 2023-04-21 02:42 UTC
Labels: A-lifetimes, F-generic_associated_types, C-discussion, T-types
