### ISSUE TITLE
LLVM ERROR: unknown codeview register

### ISSUE THREAD

**Issue by ian-p-cooke** [rust-lang/rust#53341] opened 2018-08-14 10:45 UTC
when compiling ripgrep with target-cpu=skylake-avx512 I get:

`LLVM ERROR: unknown codeview register
error: Could not compile regex-syntax.` 

does not error out when target-cpu=skylake so something about avx512?  

Possibly related to these LLVM issues:
https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg18483.html
https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg26087.html

happens with stable and nightly:
rustc 1.28.0 (9634041f0 2018-07-30)
binary: rustc
commit-hash: 9634041f0e8c0f3191d2867311276f19d0a42564
commit-date: 2018-07-30
host: x86_64-pc-windows-msvc
release: 1.28.0
LLVM version: 6.0

rustc 1.30.0-nightly (d5a448b3f 2018-08-13)
binary: rustc
commit-hash: d5a448b3f47b22c9cb010198bdcc49d4392b090b
commit-date: 2018-08-13
host: x86_64-pc-windows-msvc
release: 1.30.0-nightly
LLVM version: 7.0

**Comment by gamozolabs** [comment] 2018-08-27 09:44
This is an issue you will get when building with debug information. The issue is that LLVM does not support PDB generation for the AVX512 registers (in fact I don't think PDBs even have full support yet as windbg is lacking correct avx512 support).

Building with no debug might be aworkaround, but this is an issue that needs to be resolved at some point on the LLVM side.

**Comment by steveklabnik** [comment] 2020-07-26 18:39
Triage: are you still seeing this today?

**Comment by workingjubilee** [comment] 2021-10-05 02:15
The related LLVM bug is patched: https://bugs.llvm.org/show_bug.cgi?id=35306
so I am presumptively closing this.

**Closed by workingjubilee** 2021-10-05 02:15 UTC
Labels: A-LLVM, A-debuginfo, O-windows-msvc
