### ISSUE TITLE
Trivial cast warning for cast that can't be removed

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#23742] opened 2015-03-26 19:03 UTC
The following code yields warnings:

```
warning: trivial cast: `&mut T` as `*mut T`, #[warn(trivial_casts)] on by default
```

Warning spots are marked `// WARN` below

``` rust
#[warn(trivial_casts)]
enum Pair<T> {
    Both(T, T),
    One(T),
    None,
}

fn index_twice<T>(slc: &mut [T], a: usize, b: usize) -> Pair<&mut T>
{
    if a == b {
        slc.get_mut(a).map_or(Pair::None, Pair::One)
    } else {
        if a >= slc.len() || b >= slc.len() {
            Pair::None
        } else {
            // safe because a, b are in bounds and distinct
            unsafe {
                let ar = &mut *(slc.get_unchecked_mut(a) as *mut _); // WARN
                let br = &mut *(slc.get_unchecked_mut(b) as *mut _); // WARN
                Pair::Both(ar, br)
            }
        }
    }
}
```

The casts are non-trivial because without them the code does not pass the borrow check. Under the circumstances above we do so soundly by using an unsafe block.

Warning introduced in #23630

**Comment by bluss** [comment] 2015-03-26 19:09
Note: I've got another instance of this where I'm not doing it in a pair, but for a single `&mut`, so it's not just the pairing that's the pattern here.

**Comment by petrochenkov** [comment] 2015-03-27 12:16
"Trivial" doesn't mean "can be omitted", the warning triggers because type ascription is supposed to be used here and not `as`. The problem is that type ascription is not implemented yet. I guess temporary `#[allow(trivial_casts)]` will be the correct solution in this situation.

**Comment by Mark-Simulacrum** [comment] 2017-04-15 23:59
As far as I can tell, this isn't really something that we can fix; it's working as intended. Replacing the single-line casts with something like the following resolves both the lint and doesn't introduce any errors. I wasn't quite able to get it working with type ascription, though, but I feel like that's likely my fault.

Should this be closed?

```rust
let ar: *mut _ = slc.get_unchecked_mut(a);
let ar = &mut *(ar);
```

**Comment by Mark-Simulacrum** [comment] 2017-04-28 22:37
Closing, please reopen if this is still an issue.

**Closed by Mark-Simulacrum** 2017-04-28 22:37 UTC
Labels: A-lint

**Comment by bluss** [comment] 2017-04-29 10:03
Trivial cast warnings are no longer enabled by default, so the issue is fixed that way.
