### ISSUE TITLE
Attempting to declare static closure causes ICE

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#23391] opened 2015-03-15 13:14 UTC
```rust
static h: &'static Fn() = &|| { };

fn main() {}
```

```
/tmp $ rustc meow.rs
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: self.mode == Mode::Var', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustc/middle/check_const.rs:232
```
```
/tmp $ rustc -vV
rustc 1.0.0-nightly (3e4be02b8 2015-03-13) (built 2015-03-13)
binary: rustc
commit-hash: 3e4be02b80a3dd27bce20870958fe0aef7e7336d
commit-date: 2015-03-13
build-date: 2015-03-13
host: x86_64-apple-darwin
release: 1.0.0-nightly
```

**Comment by jakub-** [comment] 2015-05-14 11:26
Closing as a dupe of https://github.com/rust-lang/rust/issues/25180.

**Closed by jakub-** 2015-05-14 11:26 UTC
Labels: I-ICE
