### ISSUE TITLE
Boundary errors with some characters

### ISSUE THREAD

**Issue by fbbdev** [rust-lang/rust#34321] opened 2016-06-17 10:05 UTC
I'm seeing strange panics regarding regarding boundaries around characters like `'°'`, `'²'`, `'³'` and some others.

```
thread '<main>' panicked at 'index 1 and/or 5 in `°abc` do not lie on character boundary', ../src/libcore/str/mod.rs:1598
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This seems to happen mainly when such characters occur on the beginning of a string, but I have also seen this at the end or in the middle (`"m²"` or `"m²\n"`). I've not been able to reproduce the latter case, but it happened sometimes.

Example code on play.rust-lang.org: https://is.gd/5RHWli

**Comment by niconii** [comment] 2016-06-17 11:20
This isn't a bug; string slices in Rust are byte-indexed rather than character-indexed (mostly for performance reasons). Since they are UTF-8 encoded, non-ASCII characters are more than one byte long, so attempting to slice in the middle of a character will give that error.

For instance, the string `"°abc"` is encoded as the bytes `c2 b0 61 62 63`, with the two bytes `c2 b0` representing `'°'`. Taking a slice `&s[1..]` thus means trying to take the slice `b0 61 62 63`, which is invalid since index 1 is right in the middle of `'°'`.

Anyway, since it's not a bug, I'll close this issue.

**Closed by niconii** 2016-06-17 11:20 UTC

**Comment by fbbdev** [comment] 2016-06-17 11:49
Ah, my bad. I should have checked the UTF-8 representation of those chars. Its U+00B0 which gives `c2 b0` in UTF-8. Thank you and sorry for opening the issue.
