### ISSUE TITLE
future miscompiling to ud2

### ISSUE THREAD

**Issue by ambr-e** [rust-lang/rust#60709] opened 2019-05-10 18:53 UTC
Using rustc 1.36.0-nightly (3991285f5 2019-04-25), the following test compiles to `ud2`, when using the following command: `rustc --edition=2018  -Copt-level=z -Cdebuginfo=2 --test test.rs -o test`. Both the `opt-level` and `debuginfo` are necessary to get `ud2`.

```
#![feature(async_await, await_macro)]
#![allow(unused)]

#[cfg(test)]
mod tests {
    use std::future::Future;
    use std::task::Poll;
    use std::task::Context;
    use std::pin::Pin;
    use std::rc::Rc;
    
    struct Never();
    impl Future for Never {
        type Output = ();
        fn poll(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Self::Output> {
            Poll::Pending
        }
    }

    #[test]
    fn crashing_test() {
        let fut = async {
            let _rc = Rc::new(()); // Also crashes with Arc
            await!(Never());
        };
        let _bla = fut; // Moving the future is required.
    }
}
```

@cramertj @tmandry

**Comment by cramertj** [comment] 2019-05-10 18:56
This does not reproduce for me on current nightly (`rustc 1.36.0-nightly (a784a8022 2019-05-09)`). I wonder if some of @tmandry's generator representation work has affected this.

**Comment by Centril** [comment] 2019-05-10 20:29
@cramertj In that case, add it as a regression test?

**Comment by tmandry** [comment] 2019-05-10 20:43
It looks like this was fixed by #59897, specifically 5a7af5480c5f9a7d1b5964e3c77ef18326a3a67b. I'm not sure why, though.

**Comment by cramertj** [comment] 2019-05-10 20:54
@tmandry possibly the inhabitedness fix?

**Comment by tmandry** [comment] 2019-05-10 21:40
@cramertj I was thinking that, but `Never` in this example is very much inhabited.

**Comment by cramertj** [comment] 2019-05-11 14:49
@tmandry yeah- the stack slot that it returns to is never going to be hit, though, since it's always pending. Not sure if that matters...

**Comment by nikomatsakis** [comment] 2019-06-04 17:23
Marking as deferred, not blocking stabilization.

**Closed** 2019-06-29 15:21 UTC
Labels: A-async-await, AsyncAwait-Deferred, E-needstest, T-compiler
