### ISSUE TITLE
Regression: missing MIR for generic async fn across crates

### ISSUE THREAD

**Issue by divergentdave** [rust-lang/rust#81000] opened 2021-01-14 04:42 UTC
I'm getting an ICE when running a nightly version of clippy on https://github.com/smol-rs/smol. I bisected nightly toolchains, and the problem is present in +nightly-2021-01-14, and absent in +nightly-2021-01-13.

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0-nightly (a62a76047 2021-01-13)
binary: rustc
commit-hash: a62a76047ea24aad7639f14eb3ce0e620b77bdb7
commit-date: 2021-01-13
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

### Error output

```
error: internal compiler error: compiler/rustc_metadata/src/rmeta/decoder.rs:1189:17: get_optimized_mir: missing MIR for `DefId(18:48 ~ async_executor[37d1]::{impl#4}::run::{closure#0})`

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.51 (a62a760 2021-01-13)

query stack during panic:
#0 [optimized_mir] optimizing MIR for `async_executor::Executor::<'a>::run::{closure#0}`
#1 [layout_raw] computing layout of `[static generator@async_executor::Executor::run<(), futures_lite::future::Pending<()>>::{closure#0} for<'r, 's, 't0, 't1, 't2, 't3, 't4, 't5, 't6> {std::future::ResumeTy, &'r async_executor::Executor<'s>, futures_lite::future::Pending<()>, async_executor::Runner<'t0>, impl futures_lite::Future, futures_lite::future::Or<futures_lite::future::Pending<()>, impl futures_lite::Future>, ()}]`
end of query stack
error: aborting due to previous error

error: could not compile `smol`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::bug
   2: rustc_errors::Handler::bug
   3: rustc_middle::ty::context::tls::with_opt
   4: rustc_middle::util::bug::opt_span_bug_fmt
   5: rustc_middle::util::bug::bug_fmt
   6: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::optimized_mir
   7: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   9: rustc_data_structures::stack::ensure_sufficient_stack
  10: rustc_query_system::query::plumbing::force_query_with_job
  11: rustc_query_system::query::plumbing::get_query_impl
  12: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::generator_layout
  13: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
  14: rustc_middle::ty::layout::layout_raw
  15: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::layout_raw>::compute
  16: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::force_query_with_job
  20: rustc_query_system::query::plumbing::get_query_impl
  21: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  24: rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt>::layout_raw_uncached
  25: rustc_middle::ty::layout::layout_raw
  26: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::layout_raw>::compute
  27: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  28: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  29: rustc_data_structures::stack::ensure_sufficient_stack
  30: rustc_query_system::query::plumbing::force_query_with_job
  31: rustc_query_system::query::plumbing::get_query_impl
  32: <rustc_middle::ty::layout::LayoutCx<rustc_middle::ty::context::TyCtxt> as rustc_target::abi::LayoutOf>::layout_of
  33: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  34: rustc_mir::transform::run_passes
  35: rustc_mir::transform::optimized_mir
  36: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::compute
  37: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_data_structures::stack::ensure_sufficient_stack
  40: rustc_query_system::query::plumbing::force_query_with_job
  41: rustc_query_system::query::plumbing::get_query_impl
  42: <clippy_lints::implicit_return::ImplicitReturn as rustc_lint::passes::LateLintPass>::check_fn
  43: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_fn
  44: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  45: rustc_hir::intravisit::walk_expr
  46: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  47: rustc_hir::intravisit::walk_expr
  48: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  49: rustc_hir::intravisit::walk_expr
  50: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  51: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  52: rustc_hir::intravisit::walk_block
  53: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  54: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  55: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  56: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  57: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  58: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  59: rustc_hir::intravisit::walk_expr
  60: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  61: rustc_hir::intravisit::walk_expr
  62: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  63: rustc_hir::intravisit::walk_expr
  64: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  65: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  66: rustc_hir::intravisit::walk_block
  67: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  68: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  69: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  70: rustc_hir::intravisit::walk_block
  71: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  72: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  73: rustc_hir::intravisit::walk_arm
  74: rustc_hir::intravisit::walk_expr
  75: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  76: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  77: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  78: rustc_hir::intravisit::walk_block
  79: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_block
  80: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  81: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  82: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  83: rustc_hir::intravisit::walk_expr
  84: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  85: rustc_hir::intravisit::walk_expr
  86: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_expr
  87: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_nested_body
  88: rustc_hir::intravisit::walk_item
  89: rustc_hir::intravisit::Visitor::visit_nested_item
  90: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_stmt
  91: rustc_hir::intravisit::walk_block
```

</p>
</details>

**Comment by dtolnay** [comment] 2021-01-14 05:44
Minimal repro:

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2018"
```

```rust
// src/main.rs

fn main() {}

pub async fn f() {
    repro::g::<()>().await;
}
```

```rust
// src/lib.rs

pub async fn g<T>() {}
```

**Comment by csmoe** [comment] 2021-01-14 05:58
seems caused by https://github.com/rust-lang/rust/pull/80718
cc @tmiasko

**Comment by apiraino** [comment] 2021-01-14 11:20
mentioning issues #79559 and #73584 as possibly related

**Comment by tmiasko** [comment] 2021-01-14 16:51
Fixed by #81003.

**Comment by tmandry** [comment] 2021-01-14 19:38
Thanks @tmiasko!

**Closed by tmandry** 2021-01-14 19:38 UTC
Labels: A-async-await, C-bug, I-ICE, I-prioritize, T-compiler, regression-from-stable-to-nightly
