### ISSUE TITLE
broken MIR: bad assignment (&impl Trait = &S): NoSolution

### ISSUE THREAD

**Issue by oldoldman** [rust-lang/rust#77696] opened 2020-10-08 09:05 UTC
I am not sure if this is a issue in nightly build
<pre>
error: internal compiler error: broken MIR in DefId(0:12 ~ main[317d]::main[0]) (_6 = &(*_7)): bad assignment (&impl Trait = &S): NoSolution
  --> main.rs:28:26
   |
28 |   let b : & impl Trait = &S;
   |                          ^^
   |
   = note: delayed at src\librustc_mir\borrow_check\type_check\mod.rs:258:27

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src\librustc_errors\lib.rs:369:17
stack backtrace:
   0:     0x7ff807889f69 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h821f4dd582550bfb
   1:     0x7ff8078b6f7b - core::fmt::write::h312876c93103ed54
   2:     0x7ff80787bae4 - <std::io::IoSlice as core::fmt::Debug>::fmt::hfb43901216eaeee2
   3:     0x7ff80788f5cb - std::panicking::take_hook::h52d1f68705bfe58e
   4:     0x7ff80788f209 - std::panicking::take_hook::h52d1f68705bfe58e
   5:     0x7ff807d7f8da - rustc_driver::report_ice::h73e31dd3f37a0050
   6:     0x7ff80788ff60 - std::panicking::rust_panic_with_hook::heea127619d634446
   7:     0x7ff80c2ab7a4 - rustc_errors::diagnostic_builder::DiagnosticBuilder::code::h009cd739cbd841b8
   8:     0x7ff80c2aad9f - rustc_errors::diagnostic_builder::DiagnosticBuilder::code::h009cd739cbd841b8
   9:     0x7ff80c2a838d - rustc_errors::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter::ui_testing::heda1073e138862a3
  10:     0x7ff80c2727ff - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h1ca4616953ccd707
  11:     0x7ff807da3297 - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  12:     0x7ff807dc447a - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  13:     0x7ff807d47b1c - <rustc_middle::traits::chalk::RustInterner as chalk_ir::interner::Interner>::generic_arg_data::h9aab78c62ac3ba96
  14:     0x7ff807d34ed1 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h4d767eacfb9c0d6b
  15:     0x7ff807da082b - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  16:     0x7ff807d8d280 - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  17:     0x7ff807d93e3f - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  18:     0x7ff807d2d0f3 - <rustc_middle::ty::SymbolName as core::fmt::Debug>::fmt::h56077a367631f1cb
  19:     0x7ff80789fcca - std::sys::windows::thread::Thread::new::ha9abef9832621dc4
  20:     0x7ff886c14c5e - BaseThreadInitThunk
  21:     0x7ff8877cf43b - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25) running on x86_64-pc-windows-msvc

query stack during panic:
end of query stack
</pre>

**Comment by Stupremee** [comment] 2020-10-08 09:58
Can you share your code and probably update the issue title to be more precise?

**Comment by oldoldman** [comment] 2020-10-08 10:15
can reproduce with following code
<pre>
#![feature(impl_trait_in_bindings)]

struct S;
trait Trait {
  fn demo(&self) {}
}
impl Trait for S {}
fn main() {
  let a : &impl Trait = &S;
}
</pre>

**Comment by henryboisdequin** [comment] 2021-02-14 09:25
Link to [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=91ffbe02e7d33d3eff6e80a2d1c7476c)

**Comment by Alexendoo** [comment] 2021-07-22 18:42
Duplicate of #54840

**Closed by Alexendoo** 2021-07-22 18:42 UTC
Labels: A-impl-trait, A-mir, C-bug, F-impl_trait_in_bindings, I-ICE, T-compiler, glacier, requires-nightly
