### ISSUE TITLE
cross compiling from linux to windows not working..

### ISSUE THREAD

**Issue by cpt-n3mo** [rust-lang/rust#105959] opened 2022-12-20 15:34 UTC
im trying to compile something i made on linux to windows platform.. but i cant seem to get it to work..

i did the following..

`rustup install nightly-x86_64-pc-windows-gnu --force-non-host`

```
info: syncing channel updates for 'nightly-x86_64-pc-windows-gnu'
nightly-x86_64-pc-windows-gnu unchanged - (rustc does not exist)
info: checking for self-updates
```

` rustup target add x86_64-pc-windows-gnu`
```
info: downloading component 'rust-std' for 'x86_64-pc-windows-gnu'
info: installing component 'rust-std' for 'x86_64-pc-windows-gnu'
 27.8 MiB /  27.8 MiB (100 %)  14.0 MiB/s in  1s ETA:  0s
```

im keep getting `(rustc does not exist)`

`rustup update`

```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-pc-windows-gnu'

info: checking for self-updates

stable-x86_64-unknown-linux-gnu unchanged - rustc 1.66.0 (69f9c33d7 2022-12-12)
nightly-x86_64-pc-windows-gnu unchanged - (rustc does not exist)
info: cleaning up downloads & tmp directories
```

how can i solve this issue ..?

**Comment by bjorn3** [comment] 2022-12-20 17:15
You need to install rustc for Linux. Rustup giving a warning without `--force-non-host` is with a reason. A rustc compiled for Windows doesn't run on Linux. Just do `rustup install nightly` (or `rustup install stable` if you want to use stable) and then `rustup target add x86_64-pc-windows-gnu`. Do note that you will need to install MinGW and point rustc to MinGW's linker using `-Clinker=...`.

**Comment by Dylan-DPC** [comment] 2023-01-03 10:46
Closing this as it's not a bug and can be resolved. Thanks

**Closed by Dylan-DPC** 2023-01-03 10:46 UTC
