### ISSUE TITLE
`TokenStream::from_str` returns spurious `Ok`s

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#58772] opened 2019-02-27 08:17 UTC
#### Cargo.toml

```toml
[package]
name = "repro"
version = "0.0.0"
edition = "2018"

[lib]
proc-macro = true
```

#### src/lib.rs

```rust
extern crate proc_macro;

use proc_macro::TokenStream;
use std::str::FromStr;

#[proc_macro_derive(ParseTokenStream)]
pub fn derive(_input: TokenStream) -> TokenStream {
    println!("{:#?}", TokenStream::from_str("Foo::Bar { elem"));
    TokenStream::new()
}
```

#### src/main.rs

```rust
#[derive(repro::ParseTokenStream)]
struct S;

fn main() {}
```

Output of `cargo check`:

```
$ cargo check
   Compiling repro v0.0.0 (/media/david/coding/github/repro/repro)
error: this file contains an un-closed delimiter
 --> src/main.rs:1:10
  |
1 | #[derive(repro::ParseTokenStream)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^ un-closed delimiter

Ok(
    TokenStream [
        Ident {
            ident: "Foo",
            span: #4 bytes(9..32)
        },
        Punct {
            ch: ':',
            spacing: Joint,
            span: #4 bytes(9..32)
        },
        Punct {
            ch: ':',
            spacing: Alone,
            span: #4 bytes(9..32)
        },
        Ident {
            ident: "Bar",
            span: #4 bytes(9..32)
        },
        Group {
            delimiter: Brace,
            stream: TokenStream [
                Ident {
                    ident: "elem",
                    span: #4 bytes(9..32)
                }
            ],
            span: #4 bytes(9..32)
        }
    ]
)
error: aborting due to previous error

error: Could not compile `repro`.

To learn more, run the command again with --verbose.
```

---

I originally raised this issue [https://github.com/dtolnay/syn/issues/584](https://github.com/dtolnay/syn/issues/584). I'm writing a procedural macro and I'm unable to check for lexer errors because `TokenStream::from_str` can sometimes lie and say that lexing succeeded. The compiler secretly records that their was an error though and will fail my macro further down the line.

This seems related to https://github.com/rust-lang/rust/issues/58736, where the compiler will also not return an `Err(LexError)` and instead panics.

**Comment by petrochenkov** [comment] 2019-02-27 08:28
This is more or less the same issue as https://github.com/rust-lang/rust/issues/58736.

Token stream parsing doesn't currently work speculatively.
It either encounters an irrecoverable error and panics, or encounters and reports a recoverable errors and returns the recovered token stream.

**Comment by canndrew** [comment] 2019-02-27 08:46
Since `TokenStream` is used by syn this makes it impossible to write procedural macros which contain both rust and non-rust-friendly syntax. Could we instead make both these cases return `Err` and add a method to `LexError` which tries to return a recovered `TokenStream`?

**Comment by Enselic** [comment] 2023-11-16 00:54
Triage: closing as duplicate of https://github.com/rust-lang/rust/issues/58736.

**Closed by Enselic** 2023-11-16 00:54 UTC
Labels: A-macros
