### ISSUE TITLE
`type X = ::Y` vs `use ::Y as X` mismatch if ::Y is a enum

### ISSUE THREAD

**Issue by whitequark** [rust-lang/rust#44057] opened 2017-08-23 10:46 UTC
To reproduce, try to compile this:
```rust
mod foo {
    pub enum Bar { A }
}

// use foo::Bar as Baz; // this works
type Baz = foo::Bar; // this doesn't

fn main() {
    let _ = Baz::A;
}
```
This seems... counterintuitive.

**Comment by bluss** [comment] 2017-08-23 11:11
This is a duplicate of #26264

**Closed** 2017-08-23 11:14 UTC
