### ISSUE TITLE
#![deny(warnings)] doesn't work

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#33911] opened 2016-05-27 19:07 UTC
The following code:

```rust
#![deny(warnings)]

trait Foo {}

type MyType<R: Foo> = (R, ());

fn main() {
    let _t: MyType<u32>;
}
```

gives the following warning:

```shell
warning: trait bounds are not (yet) enforced in type definitions [--explain E0122]
 --> <anon>:5:1
5 |> type MyType<R: Foo> = (R, ());
  |> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However it compiles anyway.

**Comment by TimNN** [comment] 2016-05-27 19:44
Could it be that `#[deny(warnings)]` only works for lints?

**Comment by GuillaumeGomez** [comment] 2016-05-27 23:21
That's a possibility. But if it's the case, I find the "deny(warnings)" very badly named. :-/

**Comment by nagisa** [comment] 2016-05-28 11:40
Duplicate of https://github.com/rust-lang/rust/issues/21204

**Closed by nagisa** 2016-05-28 11:40 UTC
