### ISSUE TITLE
 2018 edition vs feature gate lint

### ISSUE THREAD

**Issue by dcarosone** [rust-lang/rust#53734] opened 2018-08-27 11:02 UTC
After a recent update, rustc/clippy gave me the following:

> :warning: the feature rust_2018_preview is included in the Rust 2018 edition

This is in code which, as per the migration guide at the time, has both

* `edition = '2018'` in `Cargo.toml`, and
* `#![feature(rust_2018_preview)]` at the top of `main.rs`

The message is trying to tell me that the latter is redundant, but is a little unclear about what's wrong or what to do about it. It could be improved:

* adding the word "redundant" somewhere in the warning, or perhaps replace "included" with "redundant".
* suggest an edit to remove the line.

(_refiled from rust-lang-nursery/rust-clippy#3088 which was closed because I originally raised it in what turned out to be the wrong place_)

**Comment by Enselic** [comment] 2023-11-20 10:20
Triage: Can this still be reproduced? If yes, how? Thanks!

**Comment by dcarosone** [comment] 2023-11-21 20:28
Honestly, I don't know, and don't remember what codebase / project it happened in to go look at. I assume the feature was nightly-only anyway.

The point of the issue, however, wasn't about functionality — just a suggestion for better message text. I assume that text can be reviewed, presumably now for the new edition, if anyone wants to.

**Comment by fmease** [comment] 2024-12-21 04:22
The feature `rust_2018_preview` has been removed. The diagnostic mentioned in the issue description no longer exists. Users will now be presented with:

```
error[E0557]: feature has been removed
 --> src/lib.rs:1:12
  |
1 | #![feature(rust_2018_preview)]
  |            ^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: 2018 Edition preview is no longer relevant
```

Which I deem acceptable. It's still a bit terse of course but the odds of someone encountering it are pretty low. I'm closing this because it's futile to address and we shouldn't spend any more resources on it.

Thanks for your original report though!

**Closed by fmease** 2024-12-21 04:22 UTC
Labels: A-diagnostics, F-rust_2018_preview, A-edition-2018-lints, D-confusing, D-terse, A-edition-2018
