### ISSUE TITLE
Fixed length array type with extremely high count causes excessive compile time

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#15918] opened 2014-07-23 15:03 UTC
A local variable with a fixed-length array type with an excessively. This is true even if there's no initializer expression.

```rust
fn main() {
    let x: [uint, ..18446744073709551615];
}
```

I haven't profiled to figure out what the compiler is actually doing. I also have no idea how long this actually runs for; I ended up killing rustc after about 30 seconds.

**Comment by bluss** [comment] 2015-05-07 12:32
This doesn't compile anymore:

`error: the type `[usize; 18446744073709551615]` is too big for the current architecture`

```rust
fn main() {
    let x: [usize; 18446744073709551615];
}
```

The largest rustc allows is a size of 2^46. It compiles fine, in short time!

```rust
fn main() {
    let x: [u8; 1 << 46];
}
```

**Comment by kballard** [comment] 2015-05-14 07:53
This is still a problem with zero-sized types if you have an initializer:

```rust
fn main() {
    let x = [(); 18446744073709551615];
}
```

I let it run for 10 seconds before killing it.

**Comment by bluss** [comment] 2015-05-14 08:49
Weird, I can't reproduce that. I tried different options like optimization or not, debug info or not.

```
rustc 1.1.0-nightly (4b88e8f63 2015-05-11) (built 2015-05-12)
binary: rustc
commit-hash: 4b88e8f63eeaf557c916a0a1e73150b028c44c52
commit-date: 2015-05-11
build-date: 2015-05-12
host: x86_64-unknown-linux-gnu
release: 1.1.0-nightly
```

**Comment by kballard** [comment] 2015-05-14 09:02
@bluss Oops, my bad. It's hanging on running the program, not compiling it.

**Comment by huonw** [comment] 2016-01-05 13:19
This seems to be (mostly) expected: without optimisations the very large initializer compiles to a (no-op) loop, which would be setting each element if they needed any setting.

```rust
.LBB0_1:
	movq	-16(%rsp), %rax
	addq	$1, %rax
	cmpq	$-1, %rax
	movq	%rax, -16(%rsp)
	jb	.LBB0_1
```

With optimisations this is of course eliminated. But compile times are very fast in either case, so I'm closing.

**Closed by huonw** 2016-01-05 13:19 UTC
Labels: I-compiletime
