### ISSUE TITLE
rustc fails with: LLVM ERROR: Broken function found, compilation aborted!

### ISSUE THREAD

**Issue by niconiconico9** [rust-lang/rust#25497] opened 2015-05-16 18:50 UTC
Rust compiler (rustc 1.1.0-nightly (e5394240a 2015-05-14) (built 2015-05-14) fails to compile this source:
```rust
#![feature(box_patterns)]

mod test {
    #[derive(Debug)]
    #[derive(Clone)]
    pub enum Expression {
        Var(String),
        Const(i64),
        Add(Box<Expression>, Box<Expression>),
        Mul(Box<Expression>, Box<Expression>)
    }

    pub use self::Expression::*;

    fn simplify1(exp: &Expression) -> Expression {
        match *exp {
            Add(box Const(0), ref n) | Add(ref n, box Const(0)) => *n.clone(),
            Mul(box Const(1), ref n) | Mul(ref n, box Const(1)) => *n.clone(),
            Mul(box Const(0), _) | Mul(_, box Const(0)) => Const(0),
            Add(box Const(n), box Const(m)) => Const(n + m),
            Mul(box Const(n), box Const(m)) => Const(n * m),
            _ => exp.clone()
        }
    }

    pub fn simplify(exp: &Expression) -> Expression {
        match *exp {
            Add(ref n, ref m) => simplify1(&(Add(Box::new(simplify1(n)), Box::new(simplify1(m))))),
            Mul(ref n, ref m) => simplify1(&(Add(Box::new(simplify1(n)), Box::new(simplify1(m))))),
            _ => exp.clone()
        }
    }
}
fn main() {
    use test::*;
    let e = Add(Box::new(Const(1)), Box::new(Const(29)));
    let e1 = simplify(&e);
    println!("{:?}", e1);
}
```

With the error:
```
Instruction does not dominate all uses!
  %10 = load %"test::Expression"** %2, align 8, !nonnull !0
  %96 = bitcast %"test::Expression"* %10 to i8*
Instruction does not dominate all uses!
  %91 = load %"test::Expression"** %3, align 8, !nonnull !0
  %99 = bitcast %"test::Expression"* %91 to i8*
Instruction does not dominate all uses!
  %10 = load %"test::Expression"** %2, align 8, !nonnull !0
  %100 = bitcast %"test::Expression"* %10 to i8*
Instruction does not dominate all uses!
  %91 = load %"test::Expression"** %3, align 8, !nonnull !0
  %102 = bitcast %"test::Expression"* %91 to i8*
Instruction does not dominate all uses!
  %10 = load %"test::Expression"** %2, align 8, !nonnull !0
  %103 = bitcast %"test::Expression"* %10 to i8*
LLVM ERROR: Broken function found, compilation aborted!
```

I can reproduce this ICE also on play.rust-lang.org

**Comment by luqmana** [comment] 2015-05-16 19:59
Reduced it a bit: http://is.gd/nkopPR

```Rust
#![allow(dead_code)]

#[derive(Clone)]
enum Expression {
    Dummy,
    Add(Box<Expression>),
}

use Expression::*;

fn simplify(exp: Expression) -> Expression {
    match exp {
        Add(n) => *n.clone(),
        _ => Dummy
    }
}

fn main() {}
```

**Comment by luqmana** [comment] 2015-05-16 20:18
The broken IR:

```llvm
*** IR Dump Before Module Verifier ***
; Function Attrs: uwtable
define internal i8* @_ZN8simplify20h85a1e2ef0fe110d4SaaE(i8*) unnamed_addr #4 {
entry-block:
  %sret_slot = alloca i8*
  %exp = alloca i8*
  %n = alloca i8***
  %1 = alloca i8**
  %2 = alloca { i8*, i32 }
  store i8* %0, i8** %exp, align 8
  %3 = load i8** %exp
  %4 = icmp ne i8* %3, null
  switch i1 %4, label %match_else [
    i1 true, label %match_case
  ]

case_body:                                        ; preds = %match_case
  %5 = load i8**** %n
  %6 = invoke noalias dereferenceable(8) i8** @"_ZN5boxed18Box$LT$T$GT$.Clone5clone21h17263907606676917116E"(i8*** noalias readonly dereferenceable(8) %5)
          to label %normal-return unwind label %unwind_custom_

case_body1:                                       ; preds = %match_else
  %7 = bitcast i8** %sret_slot to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %7, i8* bitcast (i8** @const861 to i8*), i64 8, i32 8, i1 false)
  br label %join

match_else:                                       ; preds = %entry-block
  br label %case_body1

match_case:                                       ; preds = %entry-block
  %8 = bitcast i8** %exp to i8***
  store i8*** %8, i8**** %n
  br label %case_body

normal-return:                                    ; preds = %case_body
  store i8** %6, i8*** %1, align 8
  %9 = load i8*** %1, align 8, !nonnull !0
  %10 = bitcast i8** %9 to i8*
  %11 = bitcast i8** %sret_slot to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %11, i8* %10, i64 8, i32 8, i1 false)
  call void @"_ZN21Box$LT$Expression$GT$9drop.112917hd039fb3d1a2bcdceE"(i8*** %5)
  %12 = bitcast i8*** %5 to i8*
  call void @llvm.memset.p0i8.i64(i8* %12, i8 29, i64 8, i32 8, i1 false)
  br label %join

unwind_custom_:                                   ; preds = %case_body
  %13 = landingpad { i8*, i32 } personality i32 (i32, i32, i64, %"1.std::rt::libunwind::_Unwind_Exception"*, %"1.std::rt::libunwind::_Unwind_Context"*)* @rust_eh_personality
          cleanup
  store { i8*, i32 } %13, { i8*, i32 }* %2
  br label %clean_custom_2

resume:                                           ; preds = %clean_custom_
  %14 = load { i8*, i32 }* %2
  resume { i8*, i32 } %14

clean_custom_:                                    ; preds = %unwind_custom_4, %clean_custom_2
  call void @_ZN10Expression9drop.112617h851faf19442a2b98E(i8** %exp)
  br label %resume

clean_custom_2:                                   ; preds = %unwind_custom_
  call void @"_ZN21Box$LT$Expression$GT$9drop.112917hd039fb3d1a2bcdceE"(i8*** %5)
  %15 = bitcast i8*** %5 to i8*
  call void @llvm.memset.p0i8.i64(i8* %15, i8 29, i64 8, i32 8, i1 false)
  br label %clean_custom_

join:                                             ; preds = %case_body1, %normal-return
  %16 = bitcast i8** %9 to i8*
  invoke void @_ZN4heap13exchange_free20h10b00cb3f415f504kfaE(i8* %16, i64 8, i64 8)
          to label %normal-return3 unwind label %unwind_custom_4

normal-return3:                                   ; preds = %join
  call void @_ZN10Expression9drop.112617h851faf19442a2b98E(i8** %exp)
  %17 = load i8** %sret_slot, align 8
  ret i8* %17

unwind_custom_4:                                  ; preds = %join
  %18 = landingpad { i8*, i32 } personality i32 (i32, i32, i64, %"1.std::rt::libunwind::_Unwind_Exception"*, %"1.std::rt::libunwind::_Unwind_Context"*)* @rust_eh_personality
          cleanup
  store { i8*, i32 } %18, { i8*, i32 }* %2
  br label %clean_custom_
}
```

**Comment by luqmana** [comment] 2015-05-16 20:29
Looking through it quickly, it seems like the order of the cleanups is messed up? If `exp` is `Dummy` then from the switch we go to the `%match_else` label which just jumps to `%case_body1` where we memcpy the value for `Dummy` into the `sret_slot` alloca and then continue to the `%join` label. This is where the problem is since it tries to call `heap::exchange_free` on the value returned from `boxed::Box<T>.Clone::clone`. But that's the thing, we wouldn't have called `clone` in that arm of the branch and hence shouldn't need to call free either.

**Comment by dotdash** [comment] 2015-05-16 20:34
Adding a block around `*n.clone()` suppresses the error. I feel like we had a similar problem not too long ago.

**Comment by dotdash** [comment] 2015-05-17 17:28
This is "caused" by the micro optimization for dereferencing owned pointer rvalues in `expr::deref_once::deref_owned_pointer`. Since `*n.clone()` is the "trailing" expression for the arm its cleanup will be scheduled in the same scope as the match expression.

cc @nikomatsakis

**Comment by jakub-** [comment] 2015-05-19 20:39
Either way, this is a dupe of https://github.com/rust-lang/rust/issues/18845. I believe @eddyb had an idea for a fix.

**Comment by eddyb** [comment] 2015-05-19 21:22
@jakub- it's simple, we ~~kill~~ remove the micro-optimization and always return an `Lvalue` datum from `expr::deref_once`.
The possibility of returning `Rvalue` datum also caused issues with field accesses - see #25595 for that fix.

We have a static type system and the `Lvalue`/`Rvalue` marker types are there for a reason.
If there is no answer to "how is an rvalue dereference or field meaningful?", then the return type for both of those should be `Datum<Lvalue>`.

**Closed** 2015-05-20 15:33 UTC
Labels: A-codegen, A-llvm
