### ISSUE TITLE
MIR borrowck doesn't accept the example of iterating and updating a mutable reference

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#46589] opened 2017-12-08 18:40 UTC
I expected this example from the NLL RFC to pass the MIR borrow checker:

```rust
struct List<T> {
    value: T,
    next: Option<Box<List<T>>>,
}

fn to_refs<T>(mut list: &mut List<T>) -> Vec<&mut T> {
    let mut result = vec![];
    loop {
        result.push(&mut list.value);
        if let Some(n) = list.next.as_mut() {
            list = n;
        } else {
            return result;
        }
    }
}

fn main() {
}
```

The idea here is that assigning to `list` is supposed to clear the existing borrows of `list.{value,next}`. However, it still gets errors for me:

```
lunch-box. rustc --stage1 iterate-mut-ref.rs  -Zborrowck=mir
error[E0499]: cannot borrow `list.value` as mutable more than once at a time
  --> iterate-mut-ref.rs:9:21
   |
9  |         result.push(&mut list.value);
   |                     ^^^^^^^^^^^^^^^ mutable borrow starts here in previous iteration of loop
...
16 | }
   | - mutable borrow ends here

error[E0499]: cannot borrow `list.next` as mutable more than once at a time
  --> iterate-mut-ref.rs:10:26
   |
10 |         if let Some(n) = list.next.as_mut() {
   |                          ^^^^^^^^^ mutable borrow starts here in previous iteration of loop
...
16 | }
   | - mutable borrow ends here

error[E0506]: cannot assign to `list` because it is borrowed
  --> iterate-mut-ref.rs:11:13
   |
9  |         result.push(&mut list.value);
   |                     --------------- borrow of `list` occurs here
10 |         if let Some(n) = list.next.as_mut() {
11 |             list = n;
   |             ^^^^^^^^ assignment to borrowed `list` occurs here

error: aborting due to 3 previous errors
```

cc @pnkfelix @arielb1

**Comment by nikomatsakis** [comment] 2017-12-12 21:39
It turns out the code for this was just never written.  What we need to do is "kill" the relevant borrows in the `borrows.rs` data flow code. The `StorageDead` case is doing something similar already, but specific to local variable places:

https://github.com/rust-lang/rust/blob/707d0708158dabd9b0a12af21a4b51bf1713cb9e/src/librustc_mir/dataflow/impls/borrows.rs#L265-L268

We would need to handle this in the case of a general assignment, but there the `Place` values that can be assigned can be any sort of path, so we need to be handling them all.

**Comment by Yoric** [comment] 2017-12-15 18:11
So, if I understand correctly, we want to duplicate/share the logics from `StorageDead` to `Assign(ref lhs, _)`, right? I'm starting to look into it.

**Comment by Yoric** [comment] 2017-12-15 19:45
As discussed with @pnkfelix over gitter, I'll try to first write a patch that works only if we `Assign` to a `Local`. Once this works, I'll see if I can understand what to do for a `Place::Projection`.

**Comment by nikomatsakis** [comment] 2017-12-15 21:48
@Yoric great! that's a good starting point.

**Comment by nikomatsakis** [comment] 2017-12-16 22:17
@Yoric great! that's a good starting point.

**Comment by Yoric** [comment] 2017-12-22 18:21
I'm now trying to tackle down the next part, but I can't find anything useful in [the RFC](https://github.com/nikomatsakis/nll-rfc/blob/master/0000-nonlexical-lifetimes.md), so I'm a bit blind here.

Looking at projections, I see the following cases:

1. `*a = expr`
2. `a.foo = expr`
3. `a[slice] = expr`
4. `a[literal] = expr`
5. `a[expr] = expr`
6. downcasts (not entirely sure what they are)

I imagine that case 1. is basically the same thing as what I have done already and that cases for 3 and 5, there isn't anything we can do. What about cases 2, 4 and 6?

**Comment by Yoric** [comment] 2018-01-02 18:05
needinfp @pnkfelix , @nikomatsakis ?

**Comment by nikomatsakis** [comment] 2018-01-04 10:41
@Yoric as I [wrote in gitter](https://gitter.im/rust-impl-period/WG-compiler-nll?at=5a4e023351915d962afda173), one way to approach this is to generalize the routine that is used to detect overlap between paths. This function is called `places_conflict`:

https://github.com/rust-lang/rust/blob/78f24d86b84882a02c15f27768e831d0342a3f5d/src/librustc_mir/borrow_check/mod.rs#L1769-L1777

However, presently it is "biased" towards returning that yes, places overlap. This is because it is used to detect illegal assignments. Specifically, with indexing, we wind up approximating -- that is, if you borrow `foo[i].bar`, and then assign to `foo[j].bar`, we assume that `i=j`. But for the purposes of *this* code, we do not know that those two paths overlap, so we do now want to kill the borrow of `foo[i].bar`. We could therefore make `places_overlap` return an `Option<bool>`, where `None` means unknown. Alternatively, we could give it a parameter indicating its "bias" -- that may be easier.

The part of the code that controls [how we handle array accesses is here](https://github.com/rust-lang/rust/blob/78f24d86b84882a02c15f27768e831d0342a3f5d/src/librustc_mir/borrow_check/mod.rs#L1746). Returning `EqualOrDisjoint` means that we will consider paths that involve two array accesses to be equal (i.e., overlapping) unless other parts of them are disjoint (so, e.g., `foo[i].bar` and `foo[i].baz` are disjoint because of `bar` and `baz` being disjoint). If we were threading down a "bias" parameter, we might here consider returning instead just `Disjoint`.

**Comment by nikomatsakis** [comment] 2018-04-03 20:28
This is not as general as it could be, but I'm marking as deferred rather than complete because honestly I think handling local variables is "good enough" for now, and we can always come back to it.

**Comment by nikomatsakis** [comment] 2018-07-03 18:50
Here is an example (from https://github.com/rust-lang/rust/issues/48001) of code that ought to pass when this is fully implemented:

```rust


#![feature(nll)]

struct Foo;

impl Foo {
    fn get_self(&mut self) -> Option<&mut Self> {
        Some(self)
    }

    fn new_self(&mut self) -> &mut Self {
        self
    }
    
    fn trigger_bug(&mut self) {
        let other = &mut (&mut *self);
        
        *other = match (*other).get_self() {
            Some(s) => s,
            None => (*other).new_self()
        };
        
        let c = other;
        
    }
}

fn main() {}
```

currently it fails with 

```
error[E0505]: cannot move out of `other` because it is borrowed
  --> src/main.rs:22:17
   |
17 |         *other = match (*other).get_self() {
   |                        -------- borrow of `**other` occurs here
...
22 |         let c = other;
   |                 ^^^^^ move out of `other` occurs here
```

**Comment by SimonSapin** [comment] 2018-07-30 22:41
I tried to write some code with an early-returned borrow inside a loop that I expected NLL would accept, but it didn’t. A reduced test case is below. Is this the same issue?

```rust
#![feature(nll)]

fn main() {}

pub struct Decoder {
    buf_read: BufRead,
}

impl Decoder {
    pub fn next<'a>(&'a mut self) -> &'a str {
        loop {
            let buf = self.buf_read.fill_buf();
            if let Some(s) = decode(buf) {
                return s
            }
            // loop to get more input data

            // At this point `buf` is not used anymore.
            // With NLL I would expect the borrow to end here,
            // such that `self.buf_read` is not borrowed anymore
            // by the time we start the next loop iteration.
        }
    }
}

struct BufRead;

impl BufRead {
    fn fill_buf(&mut self) -> &[u8] { unimplemented!() }
}

fn decode(_: &[u8]) -> Option<&str> { unimplemented!() }
```

([Playground](https://play.rust-lang.org/?gist=8f26fab1fcf7438d2739aa5635f443bc&version=nightly&mode=debug&edition=2015))

Errors:

```rust
   Compiling playground v0.0.1 (file:///playground)
error[E0499]: cannot borrow `self.buf_read` as mutable more than once at a time
  --> src/main.rs:12:23
   |
12 |             let buf = self.buf_read.fill_buf();
   |                       ^^^^^^^^^^^^^ mutable borrow starts here in previous iteration of loop
   |
note: borrowed value must be valid for the lifetime 'a as defined on the method body at 10:17...
  --> src/main.rs:10:17
   |
10 |     pub fn next<'a>(&'a mut self) -> &'a str {
   |                 ^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0499`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by SimonSapin** [comment] 2018-07-30 22:43
Interestingly, this a case where NLL is not "just" about making some code slightly nicer. As far as I can tell there is no way to write the algorithm without `unsafe` in current Stable Rust. As to the `unsafe` way, it compiles but it’s very tricky to convince myself that it’s actually valid, especially in the non-reduced code: https://play.rust-lang.org/?gist=ac9aa0aac36330cb52d113f26452a06a&version=stable&mode=debug&edition=2015

**Comment by pnkfelix** [comment] 2018-12-19 15:31
Re-triaging for #56754. Leaving assigned to @davidtwco. P-medium, NLL-complete.

**Closed** 2018-12-20 09:58 UTC
Labels: A-NLL, A-diagnostics, A-mir, C-bug, I-ICE, NLL-complete, P-medium, T-compiler

**Comment by goffrie** [comment] 2018-12-22 06:03
@nikomatsakis's [example](https://github.com/rust-lang/rust/issues/46589#issuecomment-402257979) still [doesn't work, right?](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=281593ddd000eb6b112009c172b7f3a9)

```

error[E0499]: cannot borrow `**other` as mutable more than once at a time
  --> src/main.rs:19:21
   |
17 |         *other = match (*other).get_self() {
   |                        -------- first mutable borrow occurs here
18 |             Some(s) => s,
19 |             None => (*other).new_self()
   |                     ^^^^^^^^
   |                     |
   |                     second mutable borrow occurs here
   |                     first borrow later used here

error: aborting due to previous error
```

**Comment by davidtwco** [comment] 2018-12-22 12:48
@goffrie @nikomatsakis’s example is now missing the second error that this issue was intended to solve, namely:

```
error[E0505]: cannot move out of `other` because it is borrowed
  --> src/main.rs:22:17
   |
17 |         *other = match (*other).get_self() {
   |                        -------- borrow of `**other` occurs here
...
22 |         let c = other;
   |                 ^^^^^ move out of `other` occurs here
```
