### ISSUE TITLE
no_std, #[start]: rustc core dump when defining extern main symbol with wrong type signature

### ISSUE THREAD

**Issue by lilred** [rust-lang/rust#31096] opened 2016-01-21 22:49 UTC
[Minimal test case](https://gist.github.com/lilred/cc2c8cdf9d4e28ebb81c)

```
carl@crust:~/repro$ rustc test.rs
test.rs:6:5: 6:15 warning: foreign function is never used: `main`, #[warn(dead_code)] on by default
test.rs:6     fn main();
              ^~~~~~~~~~
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Aborted (core dumped)
```

**Comment by durka** [comment] 2016-01-21 22:55
cc #9307

**Comment by nagisa** [comment] 2016-01-21 23:41
Yes, a duplicate of the issue linked above.

**Comment by nagisa** [comment] 2016-01-21 23:42
Or rather, I’ll keep this open, since it seems to refer to the `#[start]` attribute and not a language item.

**Comment by Mark-Simulacrum** [comment] 2017-04-16 00:38
Can someone provide a minimal test case for this issue? The one linked in the original comment no longer exists; the linked issue does still assert, though.

**Comment by nagisa** [comment] 2017-04-16 06:16
From comments it sounds like it was something like

```
#![feature(start)]

#[start]
fn main() {}
```

or 

```
extern {
    fn main();
}
fn main(){}
```

Both of these do not ICE anymore.

Either way, since we do not have the exact reproducer and it was indicated that the issue is kinda similar to the other linked issue, I’m inclined to close.

**Closed** 2017-04-19 13:59 UTC
Labels: I-ICE
