### ISSUE TITLE
Error bootstrapping latest rustc nightly with pinned stage0 compiler

### ISSUE THREAD

**Issue by donaldfilimon** [rust-lang/rust#77313] opened 2020-09-28 21:49 UTC
### Hello Everyone!
*I am new to filing issues so please let me know if I did anything wrong and I can edit this post.*

**On `x86_64-apple-darwin` stage0 I get a compiler error as shown below:**

```
error: const-stable function cannot use `#[feature(const_fn)]`
   --> library/core/src/task/wake.rs:136:9
    |
136 |         clone: unsafe fn(*const ()) -> RawWaker,
    |         ^^^^^
    |
    = note: otherwise `#[allow_internal_unstable]` can be used to bypass stability checks
help: if it is not part of the public API, make this function unstably const
    |
135 |     #[rustc_const_unstable(feature = "...", issue = "...")]
    |

error: aborting due to previous error

error: could not compile `core`

To learn more, run the command again with --verbose.
command did not execute successfully: "/Users/donaldfilimon/.rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-Zbinary-dep-depinfo" "-j" "4" "--release" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/Users/donaldfilimon/.rust/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /Users/donaldfilimon/.rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:03:45
```

### More Information
I am currently on an Apple DTK *(Developer Transition Kit)* trying to cross compile `x86_64-apple-darwin` to -> `aarch64-apple-darwin`. I have successfully done this in many past rustc nightlies and this error occurred on `2020-09-28` nightly rustc. I am also using rustfmt `nightly-2020-09-28` in the stage0. This occurred in the bootstrap phase so I doubt it to be a specific issue with `x86_64-apple-darwin` or `aarch64-apple-darwin` but I could be very wrong.

**Comment by jonas-schievink** [comment] 2020-09-28 21:56
What command did you run? (and on which commit?)

**Comment by donaldfilimon** [comment] 2020-09-28 22:06
Ran `./x.py build && ./x.py install` on master (commit fc2daaae610b5515438b551a2f3706196a997f35)

**Comment by Mark-Simulacrum** [comment] 2020-09-28 22:14
I am a bit confused as to what you mean by "on nightly rustc" -- are you overriding rustc in config.toml? Can you paste your config.toml?

Generally speaking it is not guaranteed that you can run the compiler at a given commit with any nightly; you need to checkout the rust-lang/rust repository at the same commit as the nightly for that to work. (Or use rustup-toolchain-install-master to get a rustc from any bors merge commit on master).

**Comment by donaldfilimon** [comment] 2020-09-28 22:24
Super sorry about the confusing wording I used there, not overriding rustc in config.toml. I'll paste both my config.toml & stage0.txt

### config.toml
```
changelog-seen = 1

[llvm]
optimize = true
assertions = false
ninja = true

[build]
build = "x86_64-apple-darwin"
host = ["aarch64-apple-darwin"]
target = ["aarch64-apple-darwin"]
extended = true

[rust]
optimize = true
debug = false
parallel-compiler = true

[dist]
missing-tools = true
```

### stage0.txt
```
date: 2020-09-28
rustc: nightly
cargo: nightly
rustfmt: nightly-2020-09-28
```

**Comment by Mark-Simulacrum** [comment] 2020-09-28 23:10
Yeah, that's basically an override of rustc, just via stage0.txt. So this is just an unsupported configuration that we can't really do much about; I am inclined to close as won't fix.

**Comment by jyn514** [comment] 2020-09-30 14:35
Closing this since it's not a bug in bootstrap. @donaldfilimon let me know if you need help getting this to work, I think it should be easy as `git checkout HEAD src/stage0.txt`.

**Closed by jyn514** 2020-09-30 14:35 UTC
Labels: A-rustbuild, T-compiler
