### ISSUE TITLE
Weird lifetimes cause a segfault in safe code

### ISSUE THREAD

**Issue by ithuleyho** [rust-lang/rust#121184] opened 2024-02-16 12:14 UTC
This contrived example compiles just fine, but running it results in a segmentation fault:

```rust
static UNIT: &'static &'static () = &&();

fn foo<'a, 'b, T>(_: &'a &'b (), v: &'b T) -> &'a T { v }

fn bad<'a, T>(x: &'a T) -> &'static T {
    let f: fn(_, &'a T) -> &'static T = foo;
    f(UNIT, x)
}

fn main() {
    let r = bad(&Box::new(&10));
    dbg!(r);
}

```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9d6dd81644b3f6c42dc4cce8d7bc3717)

The problem occurs on multiple rustc versions.

**Comment by lukas-code** [comment] 2024-02-16 12:17
duplicate of https://github.com/rust-lang/rust/issues/25860

**Comment by ithuleyho** [comment] 2024-02-16 12:20
> duplicate of #25860

Thanks, I tried to search for this but found no mention.

**Closed** 2024-02-16 12:20 UTC
Labels: C-bug, needs-triage
