### ISSUE TITLE
LLVM ERROR compiling Clap on 1.17.0 Nightly

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#40214] opened 2017-03-02 18:36 UTC
As reported here:
https://users.rust-lang.org/t/mandel-rust-v0-4/7481/3

Compiling this little project:
https://github.com/willi-kappler/mandel-rust

On x86_64-pc-windows-gnu, rustc 1.17.0-nightly, 691eba135 2017-03-01:

Instruction does not dominate all uses!
  %27 = load i32, i32* %26, !range !2
  %71 = icmp eq i32 %27, 60
LLVM ERROR: Broken function found, compilation aborted!
error: Could not compile `clap`.

Further notes:

> I can confirm this on MacOS and Linux. Stable and beta ran fine, but nightly has problems on both platforms

**Comment by TimNN** [comment] 2017-03-09 17:23
Only happens with `--release` for me on macOS.

**Comment by nagisa** [comment] 2017-03-09 18:02
First bad: `1572bf104 2017-02-25`
Last good: `08230775a 2017-02-24`

[Changes](https://github.com/rust-lang/rust/compare/08230775a...1572bf104)

**Comment by TimNN** [comment] 2017-03-09 18:07
Note that while the error does not occur when everything is compiled in debug mode, it does occur when clap itself is compiled with `-Copt-level=0` but all the dependencies are `-Copt-level=3`.

**Comment by nagisa** [comment] 2017-03-09 18:16
It also sounds a lot like an LLVM bug, since the issue happens during LLVM passes – should check if LLVM 4.0 works or not. Us giving LLVM more information is most likely the trigger.

**Comment by TimNN** [comment] 2017-03-09 18:26
@nagisa: This also fails with LLVM 4.0

**Comment by nagisa** [comment] 2017-03-09 19:54
Minimal-ish reproducer:

```rust
pub fn name(mut chars: Chars<'static>, c: char) -> bool {
    while let Some(c) = chars.next() {
        if c == ']' {
            break;
        }
    }
    c == '['
}
```

Another interesting case is

```rust
pub fn name(mut chars: Chars<'static>, c: char) -> bool {
    while let Some(c) = chars.next() {
        if c == ']' {}
    }
    c == '['
}
```

Which ICEs:

```
error: internal compiler error: /checkout/src/librustc_trans/mir/operand.rs:189: use of _12 before def
```

**Comment by nagisa** [comment] 2017-03-09 20:50
cc @cramertj

**Comment by nikomatsakis** [comment] 2017-03-09 21:07
cc me

**Comment by cramertj** [comment] 2017-03-09 23:46
Is this a dup of #40235? (Fixed in https://github.com/rust-lang/rust/pull/40242)

**Comment by nagisa** [comment] 2017-03-10 07:44
It reproduces with the nightly I updated to yesterday so probably not?

**Comment by nagisa** [comment] 2017-03-10 07:46
Reproduced, rather. I recommend trying to re-reproduce.

**Comment by cramertj** [comment] 2017-03-10 08:18
@nagisa Doing that now. The easy way to check if you have the bugfix from #40242 is to see if this compiles (it did before the bugfix):

```rust
pub fn name(c: char) -> char {
    while let Some(t) = Some('[') {
        break;
    }
    t
}
```

**Comment by nagisa** [comment] 2017-03-11 10:53
Seems to be fixed in master.

**Comment by cramertj** [comment] 2017-03-11 19:44
That was what I found, too. Sorry, forgot to post my results.

**Comment by steveklabnik** [comment] 2017-03-14 17:49
https://github.com/rust-lang/rust/issues/40214#issuecomment-285462234 does not reproduce on the current nightly. closing!

**Closed by steveklabnik** 2017-03-14 17:49 UTC
Labels: P-high, regression-from-stable-to-nightly, T-compiler
