### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', ...../compiler/rustc_serialize/src/opaque.rs:669:9

### ISSUE THREAD

**Issue by mskyttner** [rust-lang/rust#91702] opened 2021-12-09 12:59 UTC
### Code

I installed rust with "rustup" and used "cargo new hello_cargo", amended the Cargo.toml to have 

```bash
[dependencies]
polars = { git = "https://github.com/pola-rs/polars"}
connectorx = "0.2.2"
```

I then ran `rustup override set nightly` and `RUST_BACKTRACE=1 cargo build`

### Meta
`rustc --version --verbose`:
```
rustc 1.59.0-nightly (e6b883c74 2021-12-08)
binary: rustc
commit-hash: e6b883c74f49f32cb5d1cbad3457f2b8805a4a38
commit-date: 2021-12-08
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
roger@roger:~/repos/hello_
```

### Error output

```
   Compiling arrow2 v0.8.1 (https://github.com/jorgecarleitao/arrow2?rev=021a8e3aebca5562f5b7fa2f7547fb716843ae97#021a8e3a)
   Compiling connectorx v0.2.2
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type cdylib --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `connectorx`
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: build failed

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling arrow2 v0.8.1 (https://github.com/jorgecarleitao/arrow2?rev=021a8e3aebca5562f5b7fa2f7547fb716843ae97#021a8e3a)
   Compiling connectorx v0.2.2
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type cdylib --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `connectorx`
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: build failed

```

</p>
</details>

**Comment by mskyttner** [comment] 2021-12-09 13:06
Might be related to https://github.com/rust-lang/rust/issues/91696 since doing a `cargo clean` and then `cargo build` as suggested in one of the comments was successful.

**Comment by klensy** [comment] 2021-12-09 13:57
more like #91663, given the panic message

**Comment by ehuss** [comment] 2021-12-10 00:42
Closing as a duplicate of #91663.

**Closed by ehuss** 2021-12-10 00:42 UTC
Labels: I-ICE, T-compiler, C-bug
