### ISSUE TITLE
`std::io::FileStat` has a field named `created`, but it's not its creation time

### ISSUE THREAD

**Issue by lilydjwg** [rust-lang/rust#20946] opened 2015-01-11 13:58 UTC
Hi, I'm on Linux. I just saw this and I wondered how Rust gets this information when the kernel doesn't provide an API for it (I know ext4 has a so-called field `crtime` which is the file creation time but I can't get that via any syscall I know about). It turns out that Rust uses the field `ctime` as its creation time, but it is time of "last status change".

**Comment by alexcrichton** [comment] 2015-01-11 21:14
Closing as a dupe of https://github.com/rust-lang/rust/issues/15168

**Closed by alexcrichton** 2015-01-11 21:14 UTC
Labels: A-io, A-libs
