### ISSUE TITLE
cargo-doc: compiler panicked at 'Box<Any>' impossible case reached

### ISSUE THREAD

**Issue by sergeysova** [rust-lang/rust#55489] opened 2018-10-29 20:33 UTC
Steps to reproduce:
0. macOS Mojave 10.14 (18A389)
1. clone and checkout https://github.com/paholg/typenum/tree/284f456a707229bdbcac5a951d6e8b138a5abcc3
2. `cargo doc`

Result:

```
   Compiling typenum v1.10.0 (/Users/sergeysova/Projects/typenum)
 Documenting typenum v1.10.0 (/Users/sergeysova/Projects/typenum)
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached

thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0 (da5f414c2 2018-10-24) running on x86_64-apple-darwin

error: Could not document `typenum`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name typenum src/lib.rs --color always -o /Users/sergeysova/Projects/typenum/target/doc -L dependency=/Users/sergeysova/Projects/typenum/target/debug/deps` (exit code: 1)
```

Stable:
```
rustc 1.30.0 (da5f414c2 2018-10-24)
binary: rustc
commit-hash: da5f414c2c0bfe5198934493f04c676e2b23ff2e
commit-date: 2018-10-24
host: x86_64-apple-darwin
release: 1.30.0
LLVM version: 8.0
```

**Comment by memoryruins** [comment] 2018-10-29 21:03
Thanks for reporting!
This should be fixed by #55258, which is currently in  ``1.31.0-nightly (cae6efc37 2018-10-27)``+
cc #54002, except this report is on stable

**Comment by baloo** [comment] 2018-11-03 23:51
I was running the same issue, can't reproduce with `rustc 1.32.0-nightly (8b096314a 2018-11-02)`. I haven't checked the specific version you mentioned though.

**Comment by pietroalbini** [comment] 2018-11-04 21:55
Duplicate of #52873

**Closed by pietroalbini** 2018-11-04 21:55 UTC
Labels: I-ICE, T-rustdoc
