### ISSUE TITLE
stability.rs:516: encountered unmarked API (the compiler unexpectedly panicked. this is a bug.)

### ISSUE THREAD

**Issue by nanosankaku** [rust-lang/rust#38672] opened 2016-12-29 08:51 UTC
```
% cargo build
   Compiling bug v0.1.0 (file:///home/nanosankaku/projects/bug/bug)
error: internal compiler error: /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/middle/stability.rs:516: encountered unmarked API
 --> src/lib.rs:1:76
  |
1 | pub const INIT_MUTEX: std::cell::UnsafeCell<i32> = std::cell::UnsafeCell { value: 0 };
  |                                                                            ^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_errors/lib.rs:382
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `bug`.
```

% cat src/lib.rs
```rust
pub const INIT_MUTEX: std::cell::UnsafeCell<i32> = std::cell::UnsafeCell { value: 0 };
````
## Meta
Tried nightly and beta, same error

% rustc --version --verbose
rustc 1.15.0-beta.1 (d9a0f0df7 2016-12-19)
binary: rustc
commit-hash: d9a0f0df7051c603011d6b60fbdd155318fc47f3
commit-date: 2016-12-19
host: x86_64-unknown-linux-gnu
release: 1.15.0-beta.1
LLVM version: 3.9

% rustc --version --verbose
rustc 1.15.0-nightly (71c06a56a 2016-12-18)
binary: rustc
commit-hash: 71c06a56a120a0d5e3b224105ee3e6754f83e5fa
commit-date: 2016-12-18
host: x86_64-unknown-linux-gnu
release: 1.15.0-nightly
LLVM version: 3.9

`rustc --version --verbose`:

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_errors/lib.rs:382
stack backtrace:
   1:     0x7f643e07939a - std::sys::imp::backtrace::tracing::imp::write::hc924c01e14fdf084
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f643e08770f - std::panicking::default_hook::{{closure}}::h3c7e4ff009c61db6
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7f643e0872ad - std::panicking::default_hook::h4684c234c8ae64c1
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:359
   4:     0x7f643e087bb7 - std::panicking::rust_panic_with_hook::h03d5a3ece8e80bc6
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7f643b283b7b - std::panicking::begin_panic::had99e9b5f3114af5
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7f643b427023 - rustc::session::opt_span_bug_fmt::{{closure}}::h4ba716f3654cf892
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/obj/<panic macros>:3
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:782
   7:     0x7f643b426e7c - rustc::session::opt_span_bug_fmt::h178e4a512d9654c9
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1062
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:779
   8:     0x7f643b426d52 - rustc::session::span_bug_fmt::h9c6c6664f7d87df9
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:772
   9:     0x7f643b405d6f - rustc::middle::stability::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::check_stability::h388c8da62cf0b6f4
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/middle/stability.rs:516
  10:     0x7f643baec010 - rustc_typeck::check::FnCtxt::check_expr_struct_fields::h23d64a14be17ace9
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:3246
  11:     0x7f643baf12fd - rustc_typeck::check::FnCtxt::check_expr_kind::h6728cb2fc0c0f35e
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:3410
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:3958
  12:     0x7f643baee65c - rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref::h665bf8010bc589a2
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:3462
  13:     0x7f643badbc4f - rustc_typeck::check::check_const_with_type::hde77eb4865aa78e4
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:2803
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:2797
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:2790
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:1259
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:502
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/infer/mod.rs:442
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1033
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1030
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:846
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/infer/mod.rs:442
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:502
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:1249
  14:     0x7f643bad5eb2 - rustc_typeck::check::check_item_type::hcd7883623c025771
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:1276
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:852
  15:     0x7f643bacf9df - <rustc_typeck::check::CheckItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h941c32e1354ec13f
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:547
  16:     0x7f643bad1a57 - rustc_typeck::check::check_item_types::h31bc53364132279f
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/hir/itemlikevisit.rs:80
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/dep_graph/visit.rs:45
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/hir/mod.rs:456
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/dep_graph/visit.rs:67
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/mod.rs:2681
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:583
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:232
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/check/mod.rs:581
  17:     0x7f643bb3dbc0 - rustc_typeck::check_crate::habece8484d859582
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/lib.rs:345
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/util/common.rs:34
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_typeck/lib.rs:345
  18:     0x7f643e40df81 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h26fb48e320a3a494
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/driver.rs:895
  19:     0x7f643e401398 - rustc_driver::driver::phase_3_run_analysis_passes::h27dce08dd080b784
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1033
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1030
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1017
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/thread/local.rs:245
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:1014
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/ty/context.rs:782
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/driver.rs:865
  20:     0x7f643e3f1162 - rustc_driver::driver::compile_input::h301204ca2777f65d
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/driver.rs:171
  21:     0x7f643e436ad7 - rustc_driver::run_compiler::hc42fda54b73636c8
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/lib.rs:221
  22:     0x7f643e354fd8 - std::panicking::try::do_call::h2dfbc0654fb30278
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/lib.rs:1117
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/lib.rs:137
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc_driver/lib.rs:1051
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:458
  23:     0x7f643e0903da - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  24:     0x7f643e3762b8 - <F as alloc::boxed::FnBox<A>>::call_box::h1672b04377c8074b
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/thread/mod.rs:301
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  25:     0x7f643e086574 - std::sys::imp::thread::Thread::new::thread_start::h29f4c99db4339ba7
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  26:     0x7f6436f60463 - start_thread
  27:     0x7f643dd509de - __clone
  28:                0x0 - <unknown>
```

**Comment by petrochenkov** [comment] 2016-12-29 09:59
Duplicate of https://github.com/rust-lang/rust/issues/38672

**Comment by nanosankaku** [comment] 2016-12-29 12:00
Sorry, duplicate of itself?

**Comment by petrochenkov** [comment] 2016-12-29 12:13
Oops, duplicate of https://github.com/rust-lang/rust/issues/38412

**Closed** 2016-12-29 12:46 UTC
