### ISSUE TITLE
`rustdoc` doesn't show `cfg` items that can affect whether an item is available

### ISSUE THREAD

**Issue by Twey** [rust-lang/rust#66413] opened 2019-11-14 11:50 UTC
It's very frustrating and confusing to read the rustdoc for a crate and go to use some item, only to find out that the item isn't available — and the only way to figure out how to enable it is to read the source of the crate.

Instead, it would be nice to have documentation on items that indicates any `cfg` annotations that affect the the items' compilation.

**Comment by CAD97** [comment] 2019-11-26 01:06
This can be added by the crate author by using (unstable) [`#[doc(cfg(..))]`](https://github.com/rust-lang/rust/issues/43781). IIUC, it isn't possible for rustdoc to generally solve this problem in every case.

**Comment by Twey** [comment] 2019-12-04 15:41
This is more of a wishlist ticket: given rustdoc's tight integration with rustc, it is architecturally possible, and I think it would add a large UX benefit.  But I'm aware it's tricky :)

**Comment by Michael-F-Bryan** [comment] 2020-05-20 03:19
> it is architecturally possible

I don't think it is. From memory, the compiler will give `rustdoc` the parsed AST several steps *after* applying `#[cfg]` attributes, so the relevant items have already been stripped out by the time `rustdoc` gets it.

**Comment by jyn514** [comment] 2020-11-21 22:20
Duplicate of https://github.com/rust-lang/rust/issues/1998 (but I agree that https://github.com/rust-lang/rust/issues/43781 is realistically the only thing that will happen here in the foreseeable future).

**Closed by jyn514** 2020-11-21 22:20 UTC
Labels: T-rustdoc
