### ISSUE TITLE
Unable to compile inline assembly with an IntLike generic type

### ISSUE THREAD

**Issue by alistair23** [rust-lang/rust#73189] opened 2020-06-09 23:02 UTC
I am testing out the new [inline assembly](https://github.com/Amanieu/rfcs/blob/inline-asm/text/0000-inline-asm.md) in Rust nightly. I'm trying to run the RISC-V CSR read instruction, although the actual instruction doesn't matter.

I'm unable to use generic data types with the inline assembly. I have defined the type as `IntLike` but I still get this error:

```
error: cannot use value of type `T` for inline assembly
  --> libraries/riscv-csr/src/csr.rs:39:57
   |
39 |         unsafe { asm!("csrr {rd}, {csr}", rd = out(reg) r, csr = in(reg) self.value) }
   |                                                         ^
   |
   = note: only integers, floats, SIMD vectors, pointers and function pointers can be used as arguments for inline assembly

error: aborting due to previous error
```

The structure that defines the data type looks like this

```rust
pub struct ReadWriteRiscvCsr<T: IntLike, R: RegisterLongName = ()> {
    value: usize,
    associated_register: PhantomData<R>,
    associated_length: PhantomData<T>,
}
```

With the implementation looking like this

```rust
impl<T: IntLike, R: RegisterLongName> ReadWriteRiscvCsr<T, R> {
...
    #[cfg(all(target_arch = "riscv32", target_os = "none"))]
    #[inline]
    pub fn get(&self) -> T {
        let r: T;
        unsafe { asm!("csrr {rd}, {csr}", rd = out(reg) r, csr = in(reg) self.value) }
        r
    }
```

It makes sense that only certain types can be used with the inline assembly, but I would expect `IntLike` types to work.

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (fe10f1a49 2020-06-02)
binary: rustc
commit-hash: fe10f1a49f5ca46e57261b95f46f519523f418fe
commit-date: 2020-06-02
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

<details><summary>Backtrace</summary>
<p>

```
error: cannot use value of type `T` for inline assembly
  --> libraries/riscv-csr/src/csr.rs:39:57
   |
39 |         unsafe { asm!("csrr {rd}, {csr}", rd = out(reg) r, csr = in(reg) self.value) }
   |                                                         ^
   |
   = note: only integers, floats, SIMD vectors, pointers and function pointers can be used as arguments for inline assembly

error: aborting due to previous error

error: could not compile `riscv-csr`.

Caused by:
  process didn't exit successfully: `rustc --crate-name riscv_csr --edition=2018 libraries/riscv-csr/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=z -C panic=abort -Clinker-plugin-lto -C debuginfo=2 -C metadata=057902f18c6be072 -C extra-filename=-057902f18c6be072 --out-dir /scratch/alistair/software/tock/tock/target/riscv32imc-unknown-none-elf/release/deps --target riscv32imc-unknown-none-elf -L dependency=/scratch/alistair/software/tock/tock/target/riscv32imc-unknown-none-elf/release/deps -L dependency=/scratch/alistair/software/tock/tock/target/release/deps --extern tock_registers=/scratch/alistair/software/tock/tock/target/riscv32imc-unknown-none-elf/release/deps/libtock_registers-ce4c10e9dd89af94.rmeta -C link-arg=-Tlayout.ld -C linker=rust-lld -C linker-flavor=ld.lld -C relocation-model=dynamic-no-pic -C link-arg=-zmax-page-size=512 -C link-arg=-icf=all --remap-path-prefix=/scratch/alistair/software/tock/tock/= -C force-frame-pointers=no` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [../Makefile.common:236: /scratch/alistair/software/tock/tock/target/riscv32imc-unknown-none-elf/release/opentitan] Error 101

```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-06-09 23:10
Pretty sure this is expected behavior. Without making a closed-world assumption there's no way the compiler can know that `T` can only be a valid type.

**Comment by alistair23** [comment] 2020-06-09 23:13
Isn't `IntLike` enough to guarantee it's a valid type?

**Comment by jonas-schievink** [comment] 2020-06-09 23:17
`IntLike` is a library-defined trait. The compiler cannot make any assumptions about which types might implement it.

I suggest making your inline asm snippet use specific types and then convert between them and `T`.

**Comment by nagisa** [comment] 2020-06-12 00:40
> Is there anything that could be added to constrain it to work with inline asm?

Not really. Anybody can still write something along the lines

```
struct Banana;
impl BitAnd for Banana { ... }
impl BitOr for Banana { ... }
...
impl IntLike for Banana {}
```

and since the trait is public, it all can even be done in an external crate.

**Comment by nagisa** [comment] 2020-06-12 00:42
One way to do this, however is to add a method to `IntLike` and then implement said method with an assembly snippet from above. Since `Self` a that point is a specific type, type checking should pass.

**Comment by jonas-schievink** [comment] 2020-06-17 16:10
Closing as expected behavior.

**Closed by jonas-schievink** 2020-06-17 16:10 UTC
Labels: A-inline-assembly, F-asm, requires-nightly
