### ISSUE TITLE
rustc hangs forever, using 100% CPU, when building rust from source and when running cargo

### ISSUE THREAD

**Issue by jbg** [rust-lang/rust#34741] opened 2016-07-09 19:27 UTC
I’m using a clean installation of macOS Sierra beta 2. In case it matters, I have two Xcode toolchains installed and therefore two `clang` versions – the current stable Xcode 7.3 and the Xcode 8.0 beta. I tried each operation below once with each toolchain selected using `xcode-select`; there was no difference.

I tried to get started with Rust this afternoon without much luck.

First I tried to build it from source with `brew install rust` but after six hours of waiting for the compulation step to complete, with `rustc` using 100% CPU (on a current-model MacBook Pro, with `brew doctor` showing no issues other than the beta macOS warning), I decided that maybe I should download a binary package, so I downloaded the current 64-bit Mac OS X .pkg from rust-lang.org and installed this successfully.

Then I tried to start my first project with `cargo new mylib --lib`. It has hung for 30 minutes so far (`top` shows `rustc` using 100% CPU) and I don’t think it’s about to complete.

If I run `rustc --version` from the command line, I get:

```
macbook-pro% rustc --version
rustc(75943,0x7fffa5a1c3c0) malloc: *** malloc_zone_unregister() failed for 0x7fffa5a13548
```

… and it proceeds to use 100% CPU until I kill it.

**Comment by TimNN** [comment] 2016-07-09 20:27
Dupe of #34674 I believe which has been fixed by #34719 (the fix should be available in the next nightly).

**Comment by alexcrichton** [comment] 2016-07-10 00:21
Indeed!

**Closed by alexcrichton** 2016-07-10 00:21 UTC

**Comment by jbg** [comment] 2016-07-10 08:02
thanks!

**Comment by bosmacs** [comment] 2016-08-20 00:41
This appears to remain a problem in 10.12 beta 6, at least when installing from homebrew; both 1.11 and --HEAD.
