### ISSUE TITLE
[Not serious] Language not unstable enough

### ISSUE THREAD

**Issue by Hoverbear** [rust-lang/rust#24928] opened 2015-04-29 03:43 UTC
I mentioned on IRC to @bstrie that I  built a fresh [Raft](https://github.com/hoverbear/raft) which hadn't been bumped in 22 days and it still compiled.

This is obviously a bug. I'd like to propose we reopen #666 for good measure.

> I'm sorry if this makes anyone mad. It was a minor point of joy to me and I'd like to thank everyone for their incredible work!

**Comment by LaylConway** [comment] 2015-04-29 03:48
+1 this, I was appalled when after a weekend away from a project, it still compiled AND worked as intended.

**Comment by bstrie** [comment] 2015-04-29 03:49
There's been some concern in the community that a Rust without overwhelming, unceasing breakage is a betrayal of Rust's *joie de vivre*. It would be great if the developers could commit to some sort of "Instability Guarantee" to restore our faith in their leadership.

**Comment by bstrie** [comment] 2015-04-29 03:51
As we speak I'm working on a patch that changes the `fn` keyword to `func` in order to deliberately break every Rust program that has ever been written. Accepting this change in a timely and efficient manner would be just the show of good faith that the community needs right now.

**Comment by Hoverbear** [comment] 2015-04-29 03:52
@bstrie I propose something more complicated than something that could be fixed with a simple regex. We should implement hoisting one master, then decide it was a bad idea a few weeks later, just to keep things fresh.

**Comment by bstrie** [comment] 2015-04-29 03:53
While we're at it, is it too late to change the name of the language? What is "Rust" supposed to stand for, anyway?

**Comment by LaylConway** [comment] 2015-04-29 03:57
@Hoverbear What if to allow a function to borrow a value, it must call "promise_to_give_it_back" before doing anything else?

**Comment by Hoverbear** [comment] 2015-04-29 03:58
@bstrie Because it's where the metal interfaces with us air breathers.

**Comment by LaylConway** [comment] 2015-04-29 03:58
As well, is it too late to propose Rust support for the compile-time politeness enforcement feature that INTERCAL programmers enjoy?

**Comment by HeroesGrave** [comment] 2015-04-29 04:56
I propose we rename `isize`/`usize` again.

**Comment by LaylConway** [comment] 2015-04-29 08:58
Additionally, I suggest that any code within an unsafe block should not be written in Rust. Unsafe blocks should instead be written in Malbolge to disincentivice using unsafe blocks.

**Comment by soltanmm** [comment] 2015-04-29 09:07
Whatever the changes are, please ensure that they come with formal proofs of more headaches from the borrow checker.

**Comment by killercup** [comment] 2015-04-29 10:59
Well, now that the breaking language changes are coming to an end, I suggest we instead focus on introducing breaking changes to the most popular crates with patch-level version bumps!

**Comment by tailhook** [comment] 2015-04-29 12:42
I think we should introduce another "unsafe"-like construct. I.e. every non-pure function should be marked with "side_effects" marker.

**Comment by GuillaumeGomez** [comment] 2015-04-29 12:50
Closures haven't changed in a while, we need to fix that !

**Comment by alfiedotwtf** [comment] 2015-04-29 12:55
@bstrie with the 1.0 release coming in only a few weeks, please refrain from introducing new keywords. If you don't like "fn" for functions, how about swapping "fn" with "if" (i.e Is a Function). "fn" could then be the mnemonic for "ForseNda", which means "condition" in Icelandic.

**Comment by killercup** [comment] 2015-04-29 13:10
A very good idea, @alfiedotwtf! I'd like to make loops more explicit by prefixing every loop construct with the `loop` keyword: `loop while`, `loop for`, `loop loop`, etc.

**Comment by GuillaumeGomez** [comment] 2015-04-29 13:11
@killercup: Oh nice ! And then, to be even more precise on the condition, we could do `loop while for loop`, just in case. We're never sure.

**Comment by Stebalien** [comment] 2015-04-29 13:45
@killercup 
No no no. We don't need all these fancy loop variants. Just get rid of them and add guard statements to `loop` expressions:
```rust
loop {}
loop if x {}
loop if let Some(x) = iter.next() {}
```

**Comment by tshepang** [comment] 2015-04-29 15:41
@Stebalien I actually like that syntax proposal. Is there anything wrong with it that I don't see?

**Comment by Stebalien** [comment] 2015-04-29 15:45
@tshepang 
1. for loops store the iterator expression (`loop if let Some(x) = a.map(...).filter(...)` won't work).
2. It's guaranteed to needlessly confuse new users from other languages.

**Comment by tshepang** [comment] 2015-04-29 15:54
I don't understand (1). Do you mean your syntax can't work, or that it doesn't work?

**Comment by Diggsey** [comment] 2015-04-29 15:56
I think everyone's missing the obvious here: now would be the perfect time to introduce significant whitespace.

However, due to the disagreement about spaces vs tabs, it would be best to standardise on a unicode "em space" character, and error on any other character identified as whitespace according to the unicode spec.

**Comment by tshepang** [comment] 2015-04-29 16:11
This:

    for Some(x) in iterator {
        foo(x);
    }

could be mere sugar for:

    loop if Some(x) in iterator {
        foo(x);
    }

**Comment by Manishearth** [comment] 2015-04-29 16:15
I'm rather disappointed by the lack of PRs introducing ICEs in Rust. A compiler without errors is no compiler at all.


Additionally, where is all the undocumented code? I thought @steveklabnik was supposed to ensure that the majority of code is undocumented so that people instead figure stuff out by reading the beautiful Rust source!

**Comment by pythonesque** [comment] 2015-04-29 16:23
It is kind of disappointing.  How am I supposed to know whether a project has been abandoned or not when its source code doesn't have to have been updated within the last few weeks for it still to be working?

**Comment by Stebalien** [comment] 2015-04-29 16:25
@tshepang This syntax **can't** cover that use case (you'd need some sort of `loop with iter = a.map(..).filter(..) let Some(x) = iter.next()`).

**Comment by konstin** [comment] 2015-04-29 22:05
Now that you can't do real breaking changes for Rust 1.0 anymore, you should start writing Rust 2 which changes one of the key concept, e.g. replace the borrow checker with a garbage collecter, so you have to maintain two versions at once, which will ensure there are enough bugs for everyone in every version.

**Comment by alfiedotwtf** [comment] 2015-04-29 22:27
@konstin how about going full-circle: introduce manual memory allocation with two new keywords:

    * malloc
    * free

**Comment by Stebalien** [comment] 2015-04-29 22:47
@alfiedotwtf Keywords are so 20th century:

```rust
let my_var = 🎁 myvar;
my_var→ 🗑;
```

**Comment by Anachron** [comment] 2015-04-30 02:26
How about swapping all symbols with their name?

'''rust
let my_var be 1
let mut my_copy_var be a value reference to 2
'''

This will make it easier for people to code Rust, as they wont have to find the symbols in their keyboard anymore, thus speeding up the development even more.

**Comment by Stebalien** [comment] 2015-04-30 02:38
```rust
let MyVar be two
let mut MyCopyVar be a value reference to two
```

**Comment by Anachron** [comment] 2015-04-30 02:59
This would be the second step, which should follow after all people have successfully migrated to the new command, still allowing underscores in variable names and numbers. This will be a two step migration path leading to more acceptance.

**Comment by Gankro** [comment] 2015-04-30 03:54
This is clearly a regression. Breakage is happening too slow.

**Comment by sinistersnare** [comment] 2015-05-12 18:46
I think revisiting the mutapocalypse is a great idea 3 days before launch.

**Comment by Anachron** [comment] 2015-05-12 20:26
@Gankro I think I have to escalate this, things are going way too slowly in breakage and this is clearly an undesired effect by working code. Please have an emergency meeting with the core and discuss a few options mentioned in this thread.

I suggest https://github.com/rust-lang/rust/issues/24928#issuecomment-97636147 since this would clearly improve writing speed and thus will double if not triple the amount of crates that will come after 1.0 release.

**Comment by brson** [comment] 2015-05-28 16:05
I'm untagging all pre-1.0 regressions to repurpose it for stable regressions.

**Comment by steveklabnik** [comment] 2015-05-28 16:45
This bug was fun to have, but I'm gonna be the bad guy and finally close it as well.

Thanks for all the smiles, everyone :)

**Closed by steveklabnik** 2015-05-28 16:46 UTC
Labels: A-amusing, I-slow
