### ISSUE TITLE
E0507 suggests clone() in the wrong position when using the ? operator

### ISSUE THREAD

**Issue by NoobTracker** [rust-lang/rust#113368] opened 2023-07-05 15:19 UTC
### Code

```Rust
#[derive(Clone)]
struct SomethingThatDoesntImplCopy{
    x: i32
}
struct MyStruct {
  field: SomethingThatDoesntImplCopy
}
struct MyWrapper{
  field: Option<SomethingThatDoesntImplCopy>
}
fn test(param: &MyWrapper) -> Option<()>{
  let _ = MyStruct{
    field: param.field?
  };
  None
}
fn main() {

}
```

### Current output

```Shell
error[E0507]: cannot move out of `param.field` which is behind a shared reference
   --> src/main.rs:13:12
    |
13  |     field: param.field?
    |            ^^^^^^^^^^^-
    |            |
    |            `param.field` moved due to this method call
    |            move occurs because `param.field` has type `Option<SomethingThatDoesntImplCopy>`, which does not implement the `Copy` trait
    |
note: `branch` takes ownership of the receiver `self`, which moves `param.field`
   --> /home/noobtracker/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/try_trait.rs:218:15
    |
218 |     fn branch(self) -> ControlFlow<Self::Residual, Self::Output>;
    |               ^^^^
help: you can `clone` the value and consume it, but this might not be your desired behavior
    |
13  |     field: clone().param.field?
    |            ++++++++

For more information about this error, try `rustc --explain E0507`.
```

### Desired output

```Shell
error[E0507]: cannot move out of `param.field` which is behind a shared reference
   --> src/main.rs:13:12
    |
13  |     field: param.field?
    |            ^^^^^^^^^^^-
    |            |
    |            `param.field` moved due to this method call
    |            move occurs because `param.field` has type `Option<SomethingThatDoesntImplCopy>`, which does not implement the `Copy` trait
    |
note: `branch` takes ownership of the receiver `self`, which moves `param.field`
   --> /home/noobtracker/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/try_trait.rs:218:15
    |
218 |     fn branch(self) -> ControlFlow<Self::Residual, Self::Output>;
    |               ^^^^
help: you can `clone` the value and consume it, but this might not be your desired behavior
    |
13  |     field: param.field.clone()?
    |                       ++++++++

For more information about this error, try `rustc --explain E0507`.
```

### Rationale and extra context

Personally I would prefer it if the error *always* suggested adding `.clone()` instead of `clone().` but in this case it is not a matter of preference, rustc makes a bad recommendation. 

### Anything else?

Was tested in the latest stable, nightly and beta.

**Comment by compiler-errors** [comment] 2023-07-05 16:04
Partly a duplicate of https://github.com/rust-lang/rust/issues/112939, which I have a PR that's up to fix, but I just gotta rebase it and land it :sweat_smile:  thanks for the error report!

**Closed by compiler-errors** 2023-07-05 16:04 UTC
Labels: A-diagnostics, T-compiler
