### ISSUE TITLE
Inline direct calls to `transmute_copy` in the frontend

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#15398] opened 2014-07-04 05:28 UTC
When we see a direct call to `mem::transmute_copy`, we should just inline it in the frontend. This has two important benefits, one obvious and one not-so-obvious: (1) it reduces compilation time; (2) it can sometimes avoid one `memcpy` by translating the destination in place if the argument is an rvalue.

**Comment by nox** [comment] 2018-03-31 08:26
Does this still need to be done? Did anyone investigate it? The issue is not currently very actionable.

Cc @rust-lang/compiler @rust-lang/wg-codegen @rust-lang/wg-compiler-performance

**Comment by oli-obk** [comment] 2018-03-31 08:46
are there enough `transmute_copy` calls to actually make any difference? I agree that this issue needs some numbers or we should just close it until `transmute_copy` shows up in other perf discussions

**Comment by bjorn3** [comment] 2022-05-15 12:55
https://github.com/rust-lang/rust/pull/91743 should cause `transmute_copy` to be inlined before codegen.

**Comment by workingjubilee** [comment] 2022-07-06 01:57
That PR was merged so I am closing this on the presumption that it is happening just fine now and that if we need followups on that PR it can be tracked in another issue.

**Comment by bjorn3** [comment] 2022-07-06 11:20
It doesn't get inlined. I think the body of `transmute_copy` is too big. https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=1bb23b8a0df94e2aef6ea204baf6237d

**Comment by workingjubilee** [comment] 2022-07-18 01:51
Welp, my bad! Thank you for catching that, @bjorn3.

**Comment by istankovic** [comment] 2023-10-23 21:50
With current nightly and debug mode I get this:

```
playground::foo: # @playground::foo
# %bb.0:
	subq	$24, %rsp
	movq	%rdi, 16(%rsp)
	movq	16(%rsp), %rax
	movq	%rax, 8(%rsp)
	leaq	8(%rsp), %rdi
	callq	*core::mem::transmute_copy@GOTPCREL(%rip)
	addq	$24, %rsp
	retq
```

while with release mode I get
```
playground::foo: # @playground::foo
# %bb.0:
	movq	%rdi, %rax
	retq
```

Unless the call should also be inlined in debug mode, I'd say this works as expected.

**Closed** 2023-10-24 10:12 UTC
Labels: I-slow, C-enhancement, A-codegen, I-compiletime, T-compiler
