### ISSUE TITLE
Match not working properly with &str

### ISSUE THREAD

**Issue by sezna** [rust-lang/rust#28606] opened 2015-09-23 18:33 UTC
If I'm not mistaken, a string literal in rust is interpreted as a string slice, as in, the type of "hello" is &str.
If I want to pattern match a string, I would like to use &str's for syntactic simplicity, as in,

(if tmp is of type String):

```
match &tmp {
        "test" => println!("test"),
        _ => println!("not test"),
};
```

This does not compile.

```
main.rs:11:9: 11:15 error: mismatched types:
 expected `&collections::string::String`,
    found `&'static str`
(expected struct `collections::string::String`,
    found str) [E0308]
main.rs:11         "test" => println!("test"),
```

However, if I type:

```
if &tmp == "test" {println!("test");
else { println!("not test");}
```

This compiles and works. Are these two expressions not the same thing?

Thanks

**Comment by steveklabnik** [comment] 2015-09-23 18:39
The difference is if `Deref` coercions kick in. I don't believe that `match` is intended to make them work.

```
match &*tmp {
        "test" => println!("test"),
        _ => println!("not test"),
};
```

Will work just fine though.

@rust-lang/lang , is `match` supposed to use `Deref` or not? I think no, but figure it's good to double check.

**Comment by sezna** [comment] 2015-09-23 18:42
I will use that version of the code for now, and I'm not sure what Deref coercions are, so it looks like I have some reading material for the weekend. Thanks!

**Comment by steveklabnik** [comment] 2015-09-23 19:18
http://doc.rust-lang.org/book/deref-coercions.html

**Comment by arielb1** [comment] 2015-09-23 19:28
@steveklabnik 

`Deref`-coercions occur everywhere behind a reference. It's just that `match` coerces the discriminant before type-checking the patterns (and patterns don't do coercions).

**Comment by Ticki** [comment] 2015-12-10 07:02
Is there any plans for letting Deref coercions happen in match statement. I think that the status quo is ugly.

**Comment by nikomatsakis** [comment] 2015-12-10 11:54
On Wed, Dec 09, 2015 at 11:03:30PM -0800, Ticki wrote:
> Is there any plans for letting Deref coercions happen in match statement. I think that the status quo is ugly.

There are no current plans.

**Comment by nikomatsakis** [comment] 2015-12-10 11:55
On Wed, Dec 09, 2015 at 11:03:30PM -0800, Ticki wrote:
> Is there any plans for letting Deref coercions happen in match statement. I think that the status quo is ugly.

...sorry, sent the previous e-mail prematurely. I meant to say, there
are no *current* plans but it doesn't seem out of the question. Still, it might
be best to start with some specific tweaks, like targeting the `"foo"` case specifically.

**Comment by Ticki** [comment] 2015-12-10 12:24
Interesting. Shall I write up a RFC?

**Comment by Undeterminant** [comment] 2016-06-03 23:48
Just want to add onto this that this still applies in the lastest version of Rust. If there are no plans to implement a fix, because the errors are confusing, it makes sense to add it to the relevant page in the Rust book.

**Comment by aturon** [comment] 2016-06-06 16:48
It's worth improving docs and error messages here. But FWIW, @jonathandturner is also thinking about writing up an RFC to perform deref coercions for matches as well.

**Comment by ticki** [comment] 2016-06-06 16:53
I have yet to see a reason for match not to perform deref coercions.

**Comment by arielb1** [comment] 2016-06-06 20:59
@ticki

Deref coercions can break exhaustiveness checking.

**Comment by ticki** [comment] 2016-06-07 05:15
@arielb1 The type is still known.

**Comment by nikomatsakis** [comment] 2016-06-07 20:24
@arielb1 can you elaborate on this:

> Deref coercions can break exhaustiveness checking.

**Comment by ticki** [comment] 2016-06-07 20:38
The typing relation f : τ → υ from the values type to the match arm's type is known, so deref coercions can be done by checking for subtyping τ <: υ, and, if satisfied, apply coerce(τ) before matching. So in conclusion, there should be no problem what-so-ever.

**Comment by arielb1** [comment] 2016-06-07 20:40
@nikomatsakis 

I was confusing this with doing deref coercions in the middle of *patterns*. That would clearly be bad. Doing deref coercions only of the discriminant would be OK.

**Comment by ticki** [comment] 2016-06-07 20:43
@arielb1 That's not how coercions works. If a coerce to b, and c is some type constructor, `c a` coerces to `c b`, so neither that is a problem. In fact, it follows naturally from adding deref coercions in the discriminant.

**Comment by arielb1** [comment] 2016-06-07 20:46
@ticki 

> If `a` coerce to `b`, and `c` is some type constructor, `c a` coerces to `c b`

You are mixing things up. You are taking about *type-system* `eqty` coercions. Even subtyping isn't fully general (because of variance).

Rust coercions are nothing of that kind - they don't lift over type-constructions. And there certainly is no subtyping relationship between `str` and `String` (or `&str` and `String`).

**Comment by ticki** [comment] 2016-06-07 20:47
Yeah, that's right. But deref insertions is not a form of coercion.

**Comment by arielb1** [comment] 2016-06-07 20:49
@ticki 

There's still the lvalue/rvalue problem. If you have

```Rust
let mut x = &String::new();;
match x {
    ref mut x => *x = get_it();
}
```

and

```

let mut x = &String::new();
match x {
    "hello" => {}
    ref mut x => *x = get_it();
}
```

Assuming `get_it` can return both `String` and `&str`, one of these changing `x` and the other not would be confusing.

**Comment by steveklabnik** [comment] 2019-03-16 14:57
So: this is still true today, but it seems like expected behavior. Adding deref coercions here feels RFC worthy to me, so I'm going to close this in favor of that. If someone from the lang team disagrees, feel free to re-open.

**Closed by steveklabnik** 2019-03-16 14:57 UTC
Labels: C-feature-request, T-lang
