### ISSUE TITLE
`PhantomData<fn()>` is unstable in `const fn`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#69459] opened 2020-02-25 13:15 UTC
I tried this code:

```rust
use core::marker::PhantomData;

const fn test() {
    let _: PhantomData<fn()> = PhantomData;
}
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ceabf86e4f62df0dc2886678c88c0381))

I expected it to work, but it doesn't work.

Error:
```
error[E0723]: function pointers in const fn are unstable
 --> src/lib.rs:4:32
  |
4 |     let _: PhantomData<fn()> = PhantomData;
  |                                ^^^^^^^^^^^
  |
  = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
  = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

I use `PhantomData<fn(T) -> T>` to make type invariant over `T` & mark that I don't own `T`. I see no reason for this code to be unstable.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (433aae93e 2020-02-14)
binary: rustc
commit-hash: 433aae93e4ef866a1fdfefad136b32ed89acd3e7
commit-date: 2020-02-14
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

**Comment by KrishnaSannasi** [comment] 2020-02-25 19:19
To add to this, the only stable way to achieve const friendly non-owning invariance is with `PhantomData<*mut T>` which means that you must implement `Send` and `Sync` manually. This is unfortunate.

**Comment by WaffleLapkin** [comment] 2020-03-02 08:54
There is a similar issue with `PhantomData<dyn Fn(T)>` (I was trying to find a workaround...):
```
error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
  --> src/dimensions.rs:94:14
   |
94 |         Self(PhantomData)
   |              ^^^^^^^^^^^
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
   = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

**Comment by WaffleLapkin** [comment] 2020-03-02 09:02
I've found a workaround for my case (generic struct with `PhantomData` inside + `const fn new`) 🎉

```rust
pub struct Generic<T>(core::marker::PhantomData<fn(T) -> T>);

impl<T> Generic<T> {
    const NEW: Self = Self(core::marker::PhantomData);
}

impl<T> Generic<T> {
    pub const fn new() -> Self {
        Self::NEW
    }
}
```
([playgrond](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad5cb17daee7f9ad456178ccc4e469ff))

**Comment by jonas-schievink** [comment] 2020-05-07 13:46
Duplicate of https://github.com/rust-lang/rust/issues/67649

**Closed by jonas-schievink** 2020-05-07 13:46 UTC
Labels: A-const-fn, C-feature-request, T-lang

**Comment by KrishnaSannasi** [comment] 2020-05-07 16:29
Here is another workaround,

```rust
struct Invariant<T>(fn(T) -> T);
pub struct Generic<T>(core::marker::PhantomData<Invariant<T>>);

impl<T> Generic<T> {
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}
```
