### ISSUE TITLE
String::from_raw_parts example is potentially problematic

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#122743] opened 2024-03-19 19:33 UTC
### Location

[The example for](https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.from_raw_parts) `String::from_raw_parts`'s documentation.

### Summary

Two potential issues, which are *potentially* unsound depending on the exact dynamic borrow model and implementation of `String`:

- The example uses `.as_mut_ptr()` to get the raw pointer before calling `.len()` and `.capacity()`. It's better practice to extract the raw pointer *last* because calling other methods could potentially impact the provenance validity of the pointer.
- The `as_mut_ptr` called is `str::as_mut_ptr`. With a strict subslicing interpretation of provenance, the result pointer doesn't have provenance over the entire capacity

The example itself doesn't trip Miri, but a slight adjustment to get a nonexact capacity does trip UB because of the latter point: [[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6f04c3cf22b818e97a32df0a235064e6)

```rust
use std::mem;

unsafe {
    let mut s = String::from("hello");
    s.push('!'); // added

    // Prevent automatically dropping the String's data
    let mut s = mem::ManuallyDrop::new(s);

    let ptr = s.as_mut_ptr();
    let len = s.len();
    let capacity = s.capacity();

    let s = String::from_raw_parts(ptr, len, capacity);

    assert_eq!(String::from("hello!"), s);
}
```

`Vec::from_raw_parts`'s example also calls `.as_mut_ptr()` first, but has `Vec::as_mut_ptr` *specifically* to shadow `<[_]>::as_mut_ptr` and avoid an intermediate slice reference. `String` should definitely get its own `as_mut_ptr` method like `Vec` has.

Changing the order the deconstruction is done is more debatable, since it's unlikely to ever actually cause UB, this order is more natural (to the point of TB treating all mut borrows as "two-phase" in order to allow it), and the reason for the order is subtle enough that changing the example is unlikely to assist people in writing it in the better order when it actually matters.

cc @rust-lang/opsem (yet another case of ptr before len)

**Comment by RalfJung** [comment] 2024-03-19 19:37
Probably a duplicate of https://github.com/rust-lang/rust/issues/106593?

**Comment by RalfJung** [comment] 2024-03-19 19:38
> String should definitely get its own as_mut_ptr method like Vec has.

This was attempted in https://github.com/rust-lang/rust/pull/97483 but got rejected. Maybe it's worth another shot.

**Comment by CAD97** [comment] 2024-03-19 19:39
Yes, missed that in my quick search. Closing as

Duplicate of #106593

**Closed** 2024-03-19 19:41 UTC
Labels: needs-triage
