### ISSUE TITLE
panic when compiling with stable after compiling with nightly

### ISSUE THREAD

**Issue by mbr** [rust-lang/rust#37909] opened 2016-11-21 06:35 UTC
The issue:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'index out of bounds: the len is 384143 but the index is 384143', ../src/libserialize/leb128.rs:46
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

With a backtrace:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'index out of bounds: the len is 384143 but the index is 384143', ../src/libserialize/leb128.rs:46
stack backtrace:
   1:     0x7f999307b85f - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x7f999308adbd - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x7f999308822e - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x7f9993088918 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x7f99930887b2 - std::panicking::begin_panic::h6ed03353807cf54d
   6:     0x7f99930886f0 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:     0x7f9993088671 - rust_begin_unwind
   8:     0x7f99930d5fff - core::panicking::panic_fmt::h27224b181f9f037f
   9:     0x7f99930d5fa3 - core::panicking::panic_bounds_check::h19e9bbc59320a57e
  10:     0x7f998c4292ef - <serialize::opaque::Decoder<'a> as serialize::serialize::Decoder>::read_usize::hdb6b9929c2878103
  11:     0x7f9990d02798 - rustc_metadata::decoder::<impl rustc_metadata::cstore::MetadataBlob>::get_root::ha0bece0640a71bb4
  12:     0x7f9990d2b3bf - rustc_metadata::loader::Context::extract_one::h893f537a80fcaa7b
  13:     0x7f9990d28729 - rustc_metadata::loader::Context::find_library_crate::h0ae9ebab39601e07
  14:     0x7f9990d170b9 - rustc_metadata::creader::CrateReader::load::hbbb9048f37b5929d
  15:     0x7f9990d164d8 - rustc_metadata::creader::CrateReader::resolve_crate::h0ea8ce3f005d5018
  16:     0x7f9990d3459a - rustc_metadata::creader::CrateReader::resolve_crate_deps::{{closure}}::hba6352ef73c55dfc
  17:     0x7f9990ca8c16 - <std::collections::hash::map::HashMap<K, V, S> as core::iter::traits::FromIterator<(K, V)>>::from_iter::hfdd794029d934f9e
  18:     0x7f9990d1484f - rustc_metadata::creader::CrateReader::register_crate::h5c79c40329468538
  19:     0x7f9990d1b8bb - rustc_metadata::creader::CrateReader::read_macros::hbcdddd25556965a6
  20:     0x7f9990d2e5db - rustc_metadata::macro_import::load_macros::hf8ed055f967f056a
  21:     0x7f9990d20d0b - <rustc_metadata::creader::CrateLoader<'a> as rustc::middle::cstore::CrateLoader>::load_macros::h1c3dc5592ec08b80
  22:     0x7f9992675104 - <rustc_resolve::macros::ExpansionVisitor<'a, 'b> as syntax::visit::Visitor>::visit_item::he806776e3c2c5c85
  23:     0x7f999266c2ef - syntax::visit::walk_item::h9ee859a018283218
  24:     0x7f9992675eaa - <rustc_resolve::macros::ExpansionVisitor<'a, 'b> as syntax::visit::Visitor>::visit_item::he806776e3c2c5c85
  25:     0x7f9992672b9a - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::h095f31c8c14629f1
  26:     0x7f998cc720e6 - syntax::ext::expand::MacroExpander::collect_invocations::h3001d1fc85715c10
  27:     0x7f998cc6e432 - syntax::ext::expand::MacroExpander::expand::hba1d6fcc6652f3dc
  28:     0x7f998cc6dc92 - syntax::ext::expand::MacroExpander::expand_crate::hee7239fe3665f838
  29:     0x7f998cc79eed - syntax::ext::expand::expand_crate::h9213ee787f1c5e5d
  30:     0x7f9993446b5d - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::hb36e77d125a4fd93
  31:     0x7f99933fb48f - rustc_driver::driver::phase_2_configure_and_expand::h2f62e5b496da5c2b
  32:     0x7f99933f4efb - rustc_driver::driver::compile_input::hef221f9f618e92f5
  33:     0x7f9993421206 - rustc_driver::run_compiler::h7dddd4089f8330b4
  34:     0x7f999335d2c3 - std::panicking::try::do_call::h1e3ece12e3f812df
  35:     0x7f9993092cb6 - __rust_maybe_catch_panic
  36:     0x7f999337b4f9 - <F as alloc::boxed::FnBox<A>>::call_box::h05b222e46803eb30
  37:     0x7f9993086c80 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  38:     0x7f998bfef0a3 - start_thread
  39:     0x7f9992d4a62c - clone
  40:                0x0 - <unknown>
```

## Steps to reproduce:

0. `rustup default stable`
1. `cargo clean`
2. `rustup run nightly cargo build`
3. `cargo build`

A workaround is calling `cargo clean` between steps 2 and 3.

### Stable

* `cargo 0.13.0-nightly (eca9e15 2016-11-01)`
* `rustc 1.13.0 (2c6933acc 2016-11-07)`

### Nightly

* `cargo 0.16.0-nightly (d1bfc01 2016-11-18)`
* `rustc 1.15.0-nightly (0bd2ce62b 2016-11-19)`

**Comment by alexcrichton** [comment] 2016-11-21 15:04
I believe this is a dupe of https://github.com/rust-lang/rust/issues/37803, so closing in favor of that.

**Closed by alexcrichton** 2016-11-21 15:04 UTC
