### ISSUE TITLE
Regression when using `linker=arm-none-eabi-gcc`

### ISSUE THREAD

**Issue by adamgreig** [rust-lang/rust#113597] opened 2023-07-12 00:02 UTC
The [cortex-m](https://github.com/rust-embedded/cortex-m) CI tests building with all our supported linkers: Rust's provided `lld`, ARM GCC's `arm-none-eabi-ld`, and ARM GCC's `arm-none-eabi-gcc`. It recently encountered an error when using `arm-none-eabi-gcc` in nightly builds since #112910.

The most likely culprit is that the failing version has started added `"-fuse-ld=lld"` to the linker arguments, which was not present in previous working versions. @lqd, I wonder if we're meant to be adding some other argument to disable adding `-fuse-ld=lld`?

### Code

The error occurs with the cortex-m-rt CI and can be reproduced like so:

```
git clone https://github.com/rust-embedded/cortex-m
cd cortex-m/cortex-m-rt
rustup toolchain install nightly-2023-07-03
rustup target add thumbv6m-none-eabi --toolchain nightly-2023-07-03
cargo +nightly-2023-07-03 rustc --target thumbv6m-none-eabi --example alignment --features cortex-m/critical-section-single-core -- -C linker=arm-none-eabi-gcc -C link-arg=-nostartfiles
```

Or viewed in CI [here](https://github.com/rust-embedded/cortex-m/actions/runs/5525648825/jobs/10079495043?pr=483).

The error is:

```
error: linking with `arm-none-eabi-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="<snip>" VSLANG="1033" "arm-none-eabi-gcc" "/tmp/rustcFHUl0t/symbols.o" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/examples/alignment-c363c9558a2fe06e.15yn3mrxz53m7uw7.rcgu.o" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/examples/alignment-c363c9558a2fe06e.6wqau5vl49hu4fi.rcgu.o" "-Wl,--as-needed" "-L" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/deps" "-L" "/home/adam/Projects/re/cortex-m/target/debug/deps" "-L" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/build/cortex-m-rt-69b7ab10efe30aa1/out" "-L" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "-Wl,-Bstatic" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/deps/libpanic_halt-f60a67ec71296eeb.rlib" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/deps/libcortex_m_rt-9a1a89eba3425cf7.rlib" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/librustc_std_workspace_core-cc16e9be0f247487.rlib" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/libcore-b9a65150d0351313.rlib" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/libcompiler_builtins-2769d4646d3d396e.rlib" "-Wl,-Bdynamic" "-fuse-ld=lld" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/adam/.rustup/toolchains/nightly-2023-07-03-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "-o" "/home/adam/Projects/re/cortex-m/target/thumbv6m-none-eabi/debug/examples/alignment-c363c9558a2fe06e" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "-nostartfiles" "-Tlink.x"
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
```

### Version it worked on

nightly-2023-07-02

### Version with regression

nightly-2023-07-03

bisected to https://github.com/rust-lang/rust/commit/8e2d5e3a584b15ffee14984cb0b0986f00754b3d

from PR https://github.com/rust-lang/rust/pull/112910

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by jyn514** [comment] 2023-07-12 02:41
https://github.com/rust-lang/rust/blob/993deaa0bf8bab9dd3eadfd1fbeb093328e95afe/compiler/rustc_target/src/spec/thumb_base.rs#L37-L37
shows that the default for the target is rust-lld. i wonder if the new code uses the default instead of the linker in -C linker for some reason?

**Comment by lqd** [comment] 2023-07-12 06:31
On it

**Comment by lqd** [comment] 2023-07-12 08:49
I can't build a `thumbv6m-none-eabi` toolchain locally, via `./x build library/ --target thumbv6m-none-eabi`, which would be complete enough for this test to build. There are issues about missing core/std. 

I tried on a `no_std` example, and can also reproduce the `arm-none-eabi-gcc` issue and investigate more there, and that `rust-lld` and `arm-none-eabi-ld` work.

The code I added in #112910 is asked to add CLI arguments for a `Gnu(Cc::Yes, Lld::Yes)` flavor: this asks to link using `lld` via a c/c++ compiler, and why `-fuse-ld=lld` is added.  I assume that flavor is incorrect when using `-C linker=arm-none-eabi-gcc -C link-arg=-nostartfiles` @adamgreig ? 

`-C linker=arm-none-eabi-ld` and `-C linker=rust-lld` still work because they result in a non-`cc` request, and we don't do anything there as expected.

For my own understanding: does `arm-none-eabi-gcc` use `arm-none-eabi-ld` by default maybe ? 

I'll look into why this surprising flavor is used in this situation, as it seems to be the pre-existing issue here uncovered by the PR, and report back. It could be an issue in the flavor inference, or some information missing in the targets' definitions, and so on.

**Comment by workingjubilee** [comment] 2023-07-12 20:16
Technically, the target builds.
As a tier 2 target, we would strongly prefer it to not require additional antics to build.

**Comment by lqd** [comment] 2023-07-12 20:35
The linker flavor used is a mix between what can be inferred from the CLI (`-C linker`) and the target's default linker flavor:

- there is no linker flavor on the CLI (and that also offers another workaround on nightly: `-C linker-flavor=gnu-cc -Zunstable-options`), so it will have to be inferred [from here](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_codegen_ssa/src/back/link.rs#L1334-L1336) to [here](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_codegen_ssa/src/back/link.rs#L1321-L1327).
- in [`infer_linker_hints`](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_target/src/spec/mod.rs#L320-L352) `-C linker=arm-none-eabi-gcc` infers a `Some(Cc::Yes)` cc hint, and no hint about lld. 
- the target's `linker_flavor` is combined in `with_cli_hints` with these hints. We have our `Cc::Yes`, but there is no hint about lld, [so the target's flavor `lld` component is used](https://github.com/lqd/rust/blob/5dac6b320be868f898a3c753934eabc79ff2e406/compiler/rustc_target/src/spec/mod.rs#L356-L358). It's [`Gnu(Cc::No, Lld::Yes)`](https://github.com/rust-lang/rust/blob/993deaa0bf8bab9dd3eadfd1fbeb093328e95afe/compiler/rustc_target/src/spec/thumb_base.rs#L35-L36).
- so we now have our `Gnu(Cc::Yes, Lld::Yes)` flavor

@adamgreig @hannobraun @thejpster: is the linker people are expected to use on `thumbv6m-none-eabi` supposed to be some `lld` ? Is the default linker and flavor in `thumb_base.rs` correct ?

In the meantime, I'll see to change this so that the lld flags are only added when the unstable MCP510 options are used, to keep this stable and unfortunate behavior unchanged when the CLI and target conflict instead of compose.

**Comment by adamgreig** [comment] 2023-07-12 23:24
Thanks for looking into this quickly!

Most people building for `thumbv6m-none-eabi` will use the default `rust-lld` linker today. It works fine for (I believe) all Rust-only projects. However, it's not uncommon to use `arm-none-eabi-ld`, maybe to use specific GCC linker script directives, or just when hunting down linker-related bugs. For both of those use cases there's no problem with nightly, and I think the default in thumb_base is therefore fine.

Some people do need to use `arm-none-eabi-gcc` when linking with pre-compiled C libraries - I understand that using gcc pulls in a target specific libc, and a lot of pre-compiled C libraries will be trying to link against symbols it exports which Rust doesn't. I believe `arm-none-eabi-gcc` does delegate to `arm-none-eabi-ld`.

Passing either `-C linker-flavor=gnu-cc -Zunstable-options` or `-C link-arg=-fuse-ld=bfd` does work to get a build without errors, though I don't have a test case handy to check it's actually getting what people need out of `arm-none-eabi-gcc`. I'll try and dig around a bit more for the specific use cases where it's required over `arm-none-eabi-ld`.

**Comment by thejpster** [comment] 2023-07-13 18:18
My main recollection is that gcc requires you to put `-Wl,` in front of your linker arguments and using ld directly you don't 🤣

But I think `-nodefaultlibs` and friends are gcc options not ld options so maybe ld won't bring in libc and the C startup automatically. I'll test it out shortly.

**Comment by thejpster** [comment] 2023-07-13 18:37
main.c:
```c
int main() {
    puts("Hello, world");
    return 0;
}
```

Compile object code:
```console
$ arm-none-eabi-gcc -o main.o -c main.c -mcpu=cortex-m3
```

Link with GCC:
```console
$ arm-none-eabi-gcc -o main main.o -mcpu=cortex-m3
<bunch of errors about missing _close_r, _lseek_r and other syscalls that the newlib C library requires>
```

Link with ld:
```console
$ arm-none-eabi-ld -o main main.o -mcpu=cortex-m3
warning: cannot find entry symbol _start
main.o: in function `main` main.c: undefined reference to `puts`
```

This does imply that for trivial invocations `arm-none-eabi-gcc` will include both the default start code (which provides `_start`) and newlib (the C library), whilst `arm-none-eabi-ld` will not.

**Comment by thejpster** [comment] 2023-07-13 18:40
See also https://github.com/rust-lang/rust/pull/113535, where I set the default target for bare-metal SPARC to be gcc, precisely because the default libraries it links in are *so* useful - the include not only the start-up code (no idea how that works, didn't need to find out) but also a C library for talking to the stdout of the most popular CPU emulator.

So, yeah, GCC is a really useful linker driver in some scenarios and we don't want to stop that from working.

**Comment by lqd** [comment] 2023-07-13 20:23
Thanks for the information, it's very helpful.

The good news is that using GCC as a linker is still working 😅. In the future where we switch to lld, maybe rustc will also need an explicit linker flavor here, to make sure the flavor it guesses actually matches your expectations. But that's a topic for another day/stabilization: in the more immediate future, things will return to normal for the target and `cortex-m`'s tests in a day or two.

**Comment by thejpster** [comment] 2023-07-13 20:50
Thank you!

Just to come back to this point:

> I don't know who the target maintainers are

I was under the impression that Arm Ltd were maintaining the thumbv*m-none-eabi* targets. However, they don't appear to have the platform-support documentation that is required for more recently added targets. Maybe that could be addressed.

**Comment by lqd** [comment] 2023-07-14 13:39
This is on beta, reopening to track backport.

**Comment by workingjubilee** [comment] 2023-07-16 00:32
@thejpster Pursuant to your concern I have opened https://github.com/rust-lang/rust/issues/113739 to summarize the issue that affects indeed all our tier 2 targets.

**Comment by lqd** [comment] 2023-08-10 21:36
The backport of #113631 has landed on beta in https://github.com/rust-lang/rust/pull/113938. We can close this issue as fixed.

**Closed by lqd** 2023-08-10 21:36 UTC
Labels: A-linkage, P-medium, regression-from-stable-to-nightly, C-bug, A-cli
