### ISSUE TITLE
resolve failed for macro-2.0 

### ISSUE THREAD

**Issue by bvanjoi** [rust-lang/rust#114289] opened 2023-07-31 12:44 UTC
I tried this code:

```rust
#![feature(decl_macro)]
macro_rules! m {
    ($i:ident) => {
        mod $i {
            pub struct A;
        }
    }
}

m!(x);

fn main() {
    let a: x::A = x::A;
}

```

I expected to see this happen: *compile pass*

Instead, this happened: *compile failed and report: "error[E0412]: cannot find type `A` in module `x`"*

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (32303b219 2023-07-29)
binary: rustc
commit-hash: 32303b219d4dffa447aa606bc11c7a648f44a862
commit-date: 2023-07-29
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

**Comment by ehuss** [comment] 2023-07-31 14:13
Thanks for the report!  I believe this is the same as #91249. The identifiers in the macro have def-site hygiene, which makes them unavailable at the call-site. decl_macros are still unfinished, and I believe controlling hygiene is one of the things that still needs some work.

**Comment by ScottLL** [comment] 2023-07-31 17:33
Add the macro 'm!(x)' to the code which will declare the type 'x::A'. This should fix the error encountered.

**Comment by fmease** [comment] 2023-10-02 16:57
Your code actuall compiles, you'd need to replace `macro_rules!` with `macro` to get the error you mentioned.

In any case, as ehuss said, macros 2.0 employ def-site hygiene. Closing as duplicate of #91249.

**Closed by fmease** 2023-10-02 16:57 UTC
Labels: T-compiler, A-macros-2.0, C-bug, F-decl_macro
