### ISSUE TITLE
match String as str inside enum

### ISSUE THREAD

**Issue by DenisKolodin** [rust-lang/rust#28061] opened 2015-08-28 14:08 UTC
I've confused by this matching:

```rust
enum E {
    Container(String)
}

fn main() {
    let e = E::Container(String::from("data"));
    match e {
        E::Container("data") => println!("Match"),
        _ => println!("No match"),
    }
}
```

Error:
```rust
<anon>:9:22: 9:28 error: mismatched types:
 expected `collections::string::String`,
    found `&'static str`
(expected struct `collections::string::String`,
    found &-ptr) [E0308]
<anon>:9         E::Container("data") => println!("Match"),
                              ^~~~~~
<anon>:9:22: 9:28 help: see the detailed explanation for E0308
error: aborting due to previous error
playpen: application terminated with error code 101
```

How ti solve this pattern puzzle?
Many libs (like hyper) has String holder. Is it possible to blur the line between `String` and `str`?

**Comment by Stebalien** [comment] 2015-08-28 14:28
Currently, you have to use a guard:

```rust
enum E {
    Container(String)
}

fn main() {
    let e = E::Container(String::from("data"));
    match e {
        E::Container(ref s) if *s == "data" => println!("Match"),
        _ => println!("No match"),
    }
}
```

**Comment by arielb1** [comment] 2015-08-29 19:53
this will be fixed if/when we get `DerefPure` box patterns. Not a bug, closing.

**Closed by arielb1** 2015-08-29 19:53 UTC

**Comment by archshift** [comment] 2016-12-07 02:01
Has there been any movement on `DerefPure` patterns? This seems like a pretty reasonable feature for Rust to have.
