### ISSUE TITLE
conflicting impl since nightly-2024-05-01

### ISSUE THREAD

**Issue by conradludgate** [rust-lang/rust#125763] opened 2024-05-30 08:45 UTC
### Code

I tried this code:

https://github.com/conradludgate/measured/tree/b2978b32e2065cb6257244829b5fd6ae1dba4576

```rust
pub trait LabelGroupSet {
    type Group<'a>: LabelGroup;
}

impl<T: LabelSet> LabelGroupSet for T
where
    for<'a> T::Value<'a>: LabelGroup,
{
    type Group<'a> = T::Value<'a>;
}

pub trait LabelSet {
    type Value<'a>;
}

impl<T: LabelGroupSet + ?Sized> LabelGroupSet for &'static T {
    type Group<'a> = T::Group<'a>;
}

pub trait LabelGroup {}
```

I expected to see this happen: compiles successfully

Instead, this happened:

```
error[E0119]: conflicting implementations of trait `LabelGroupSet` for type `&'static _`
   --> core/src/label/value.rs:45:1
    |
45  | / impl<T: LabelSet> LabelGroupSet for T
46  | | where
47  | |     for<'a> T::Value<'a>: LabelGroup,
    | |_____________________________________^ conflicting implementation for `&'static _`
    |
   ::: core/src/label/group.rs:133:1
    |
133 |   impl<T: LabelGroupSet + ?Sized> LabelGroupSet for &'static T {
    |   ------------------------------------------------------------ first implementation here
    |
    = note: downstream crates may implement trait `label::value::LabelSet` for type `&'static _`
    = note: downstream crates may implement trait `label::group::LabelGroup` for type `<&'static _ as label::value::LabelSet>::Value<'a>`
```

### Version it worked on

It most recently worked on: `nightly-2024-04-30`

### Version with regression

according to cargo-bisect-rustc, the regression started with `nightly-2024-05-01` in https://github.com/rust-lang/rust/pull/117164

**Comment by lcnr** [comment] 2024-05-30 11:11
further minimized
```rust
pub trait Overlap {}
impl<T: Overlap + ?Sized> Overlap for &'static T {}
impl<T: LabelSet> Overlap for T
where
    for<'a> T::Value<'a>: LabelGroup,
{}

pub trait LabelGroup {}
pub trait LabelSet {
    type Value<'a>;
}
```
This pattern is #114061. Coherence now considers `for<'a> <&'static ?x as LabelSet>::Value<'a>: LabelGroup` to be unknowable, as downstream crates could implement `LabelSet` for `&'static LocalType` where there's an impl of `LabelGroup` for `LocalType`. This should break. The FCP in https://github.com/rust-lang/rust/pull/117164#issuecomment-1970903449 did not mention that this part of the change will immediately be a hard error instead of a future-compat lint.

We use `orphan_check_trait_ref` in two places: for the orphan check itself, and when checking whether some trait goal is "knowable" We only added the future compat lint behavior to the orphan check, always using the correct approach in `trait_ref_is_knowable`. This is the first regression caused by that. https://github.com/rust-lang/rust/blob/d43930dab36b81267d436fd16066419d3a66e054/compiler/rustc_trait_selection/src/traits/coherence.rs#L944-L948

---

Sorry for not mentioning this in the original FCP. I was aware of this immediate breakage but did not mention it.

Changing this to also be a future compat lint is annoying and I intentionally did not suggest this in #117164, as that is "inside of the trait solver" and has a smaller impact than the changes to the orphan check itself.

I would like to not revert this change as there have been some small follow-up PRs and I want to close these unsoundnesses asap. I propose accepting this breakage and to close this issue after adding it as a test. However, given that this has slipped through the FCP process, I am open to revert and re-land with another FCP in case there are any concerns by a @rust-lang/types member.

@rfcbot fcp close

**Comment by conradludgate** [comment] 2024-05-30 12:45
I'm fine with the decision but it would have been nicer to have some warning with info

**Comment by fmease** [comment] 2024-05-30 12:54
Yeah, that's understandable. Sorry about that! https://github.com/rust-lang/rust/issues/125763#issuecomment-2139472764 was addressed to T-types, not to you specifically. That's a bit unclear.

**Comment by conradludgate** [comment] 2024-05-30 15:53
> yes, we did no catch the breakage in your crate when running crater, unsure why that was the case 🤔

Strange. This particular impl has been on crates.io since February 10 🤔 those crater runs were Feb-27 and Apr-27 respectively and `measured` is not in the dataset at all. Very strange.

<https://docs.rs/measured/0.0.12/measured/label/group/trait.LabelGroupSet.html#impl-LabelGroupSet-for-T>

**Comment by lqd** [comment] 2024-05-30 17:00
> yes, we did no catch the breakage in your crate when running crater, unsure why that was the case 🤔

yeah it's not the first time this happened, there's https://github.com/rust-lang/crater/issues/727 and discussions on zulip IIRC

**Comment by nikomatsakis** [comment] 2024-06-04 13:54
@rfcbot reviewed

**Comment by fmease** [comment] 2024-06-04 14:27
> https://github.com/rust-lang/rust/issues/125763#issuecomment-2147600995

@nikomatsakis Your vote didn't register for some reason. https://github.com/rust-lang/rust/issues/125763#issuecomment-2139324219

**Closed** 2024-06-16 13:34 UTC
Labels: C-bug, finished-final-comment-period, disposition-close, T-types, A-coherence
