### ISSUE TITLE
Duplicate argument names allowed in extern function declarations

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#125862] opened 2024-06-01 15:32 UTC
I tried this code:

```rust
extern "C" {
    fn foo(a: u8, a: u8);
}
```

I expected to see this happen: Error as there are two arguments named `a`.

Instead, this happened: Compiles fine.

I found this issue while working on parsing the core_arch and generating code from it. It has the following declaration: `fn vcvtss2sd(a: f64x2, a: f32x4, src: f64x2, mask: u8, sae: i32) -> f64x2;`.

### Meta

Happens with both 1.78 stable and 1.80.0-nightly (2024-05-31 ada5e2c7b5427a591e30).

**Comment by petrochenkov** [comment] 2024-06-01 23:35
This is a duplicate of this old issue - https://github.com/rust-lang/rust/issues/33995.
I'm still not sure if this is worth changing.

**Comment by saethlin** [comment] 2024-06-03 04:49
Closing as duplicate

**Closed by saethlin** 2024-06-03 04:49 UTC
Labels: C-bug, needs-triage
