### ISSUE TITLE
Cow trait bound without ToOwned produces odd "`core::marker::Sized` is not implemented"

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#31691] opened 2016-02-16 00:20 UTC
Incorrect code, because `Cow` requires `ToOwned` on its parameter:

``` rust
fn into_cow<'a, T: ?Sized, S: Into<Cow<'a, T>>>(s: S) -> Cow<'a, T> {
    s.into()
}
```

Fixed:

``` rust
fn into_cow<'a, T: ?Sized + ToOwned, S: Into<Cow<'a, T>>>(s: S) -> Cow<'a, T>
                          ^^^^^^^^^
```

Makes sense, but rustc's error for the first version is odd:

```
exectool.rs:46:1: 48:2 error: the trait `core::marker::Sized` is not implemented for the type `T` [E0277]
exectool.rs:46 fn into_cow<'a, T: ?Sized, S: Into<Cow<'a, T>>>(s: S) -> Cow<'a, T> {
exectool.rs:47     s.into()
exectool.rs:48 }
exectool.rs:46:1: 48:2 help: run `rustc --explain E0277` to see a detailed explanation
exectool.rs:46:1: 48:2 note: `T` does not have a constant size known at compile-time
exectool.rs:46:1: 48:2 note: required by `core::convert::Into`
```

`Into` doesn't require `T` to be `Sized`, and indeed in the `Cow` case it usually isn't.

If I remove the `?Sized` from `T`, I get `the trait core::clone::Clone is not implemented for the type T`; stable produces this error for the original version too, along with the `Sized` error.  On IRC, aatch suggested this was might be caused by `impl<T: Clone> ToOwned for T`.  While `Clone` would be a sufficient bound due to that impl, it isn't necessary even for sized types, so that error too is misleading.

**Comment by Aatch** [comment] 2016-02-16 03:15
Related: #30976

**Comment by Mark-Simulacrum** [comment] 2019-09-15 13:51
Seems like a duplicate of https://github.com/rust-lang/rust/issues/64088 essentially

**Closed by Mark-Simulacrum** 2019-09-15 13:51 UTC
Labels: A-diagnostics, C-enhancement
