### ISSUE TITLE
Code works in Edition 2021 but not 2018 even though it should

### ISSUE THREAD

**Issue by kangalio** [rust-lang/rust#91046] opened 2021-11-19 17:49 UTC
I tried this code:

```rust
use std::collections::HashMap;
use std::hash::Hash;

pub fn get<'a, K: Eq + Hash, V, const N: usize>(
    map: &'a mut HashMap<K, V>,
    mut_index: &K,
    ref_indices: [&K; N],
) -> Option<(&'a mut V, [Option<&'a V>; N])> {
    if ref_indices.contains(&&mut_index) {
        panic!("Attempted to obtain a mutable and immutable reference to same item");
    }

    let mut_item = map.get_mut(mut_index)? as *mut V;
    let ref_items = ref_indices.map(|i| map.get(i));
    // SAFETY:
    // - aliasing: we got passed a unique reference to the map and made sure none of our immutable references point to mut_item
    // - lifetime: the reference has lifetime 'a which matches the HashMap it points into
    let mut_item = unsafe { &mut *mut_item as &'a mut V };

    Some((mut_item, ref_items))
}
```

I expected to see this happen: the code should compile on 2018 and not just 2021, because as far as I can tell, there are no 2021 features that should affect the `ref_indices.map(|i| map.get(i))` call

Instead, this happened: compiling that code in 2018 edition yields this error:

```rust
error[E0373]: closure may outlive the current function, but it borrows `map`, which is owned by the current function
  --> src/main.rs:15:37
   |
15 |     let ref_items = ref_indices.map(|i| map.get(i));
   |                                     ^^^ --- `map` is borrowed here
   |                                     |
   |                                     may outlive borrowed value `map`
   |
note: closure is returned here
  --> src/main.rs:21:5
   |
21 |     Some((mut_item, ref_items))
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: to force the closure to take ownership of `map` (and any other referenced variables), use the `move` keyword
   |
15 |     let ref_items = ref_indices.map(move |i| map.get(i));
   |                                     ++++
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

**Comment by nbdd0121** [comment] 2021-11-19 20:41
This is relaed to disjoint field capture in closure. Adding `#![feature(capture_disjoint_fields)]` will make it work in Rust 2018.

**Comment by nbdd0121** [comment] 2021-11-19 20:51
In Rust 2018 use of `map` will need to capture `&map`  (`&&'a mut HashMap<K, V>`), but in Rust 2021 it can captures `&*map` (`&'a HashMap<K, V>`), so I wouldn't consider this a bug. Your code could be fixed to compile in Rust 2018 with explicit reborrow:
```rust
use std::collections::HashMap;
use std::hash::Hash;

pub fn get<'a, K: Eq + Hash, V, const N: usize>(
    map: &'a mut HashMap<K, V>,
    mut_index: &K,
    ref_indices: [&K; N],
) -> Option<(&'a mut V, [Option<&'a V>; N])> {
    if ref_indices.contains(&&mut_index) {
        panic!("Attempted to obtain a mutable and immutable reference to same item");
    }

    let mut_item = map.get_mut(mut_index)? as *mut V;

    let map = &*map; // <- add this line

    let ref_items = ref_indices.map(|i| map.get(i));
    // SAFETY:
    // - aliasing: we got passed a unique reference to the map and made sure none of our immutable references point to mut_item
    // - lifetime: the reference has lifetime 'a which matches the HashMap it points into
    let mut_item = unsafe { &mut *mut_item as &'a mut V };

    Some((mut_item, ref_items))
}
```

**Comment by VorfeedCanal** [comment] 2021-11-21 20:40
Indeed, it's pretty hard to say "there are no differences which may effect this code" when you just need to read the appropriate book and find the whole chapter dedicated for just such a difference:
  https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html

**Comment by kangalioo** [comment] 2021-11-21 22:12
I see where the difference is coming from now, thank you.

> Indeed, it's pretty hard to say "there are no differences which may effect this code" when you just need to read the appropriate book and find the whole chapter dedicated for just such a difference:
https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html

I was aware of disjoint captures in closures. However that chapter only talks about "fields", implying fields of a struct. It's not very obvious in my opinion that "field" in that context also means the inner value of a reference

---

From my side, the issue can be closed now

**Comment by fmease** [comment] 2024-12-27 22:24
`#[rustc_capture_analysis] |i| map.get(i)` reports

- `Capturing map[Deref] -> Immutable` and additionally
- in Rust 2018: `Min Capture map[] -> Immutable`
- in Rust 2021: `Min Capture map[Deref] -> Immutable`

> I was aware of disjoint captures in closures. However that chapter only talks about "fields" […]

The docs are lacking in that regard, they could maybe be more comprehensive. Looking at rustc's source code, disjoint field capture considers *projections* in general, not just fields. Projections include fields, deref'ing, indexing, subslicing (and opaque to hidden casting).

Closing as works as intended.

**Closed by fmease** 2024-12-27 22:24 UTC
Labels: A-closures, A-borrow-checker, T-compiler, C-discussion, A-edition-2021
