### ISSUE TITLE
Multiple extern fn with same name should not error out

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#28870] opened 2015-10-06 18:49 UTC
See https://github.com/rust-lang/rust/issues/16403#issuecomment-66864518 and that issue in general.

Currently for each `extern fn` we generate a rust ABI function containing function body and a `C` ABI trampoline to the rust function. However we do not mangle the rust ABI function sufficiently, therefore this code does not compile:

```rust
fn main() {
    { extern fn a() {this} };
    { extern fn a() {that} };
}
```

**Comment by apasel422** [comment] 2015-10-28 01:15
Closing as a duplicate of #26201.

**Closed by apasel422** 2015-10-28 01:15 UTC
