### ISSUE TITLE
Incremental compilation doesn't update static strings.

### ISSUE THREAD

**Issue by pinkisemils** [rust-lang/rust#49301] opened 2018-03-23 11:18 UTC
When changing a static string in a way that doesn't change it's length, `cargo build` won't rebuild the changed string.
For instance, if the binary has already been built, changing `hello` to `xxxxx` will result in a binary that still outputs `hello`.
```rust
static HELLO: &str = "hello";

fn main() {
    println!("{}", HELLO);
}
```
If built with `CARGO_INCREMENTAL=0`, everything works as expected. If the length of the string is changed, everything also works as expected.
Tested on `rustc 1.26.0-nightly (75af15ee6 2018-03-20)`.

**Comment by michaelwoerister** [comment] 2018-03-23 11:28
Thanks for the bug report, @pinkisemils!

**Comment by michaelwoerister** [comment] 2018-03-23 11:48
OK, I can reproduce on nightly. Cannot reproduce on beta though. Could this be MIRI related, @oli-obk? Are we hashing just an ID instead of contents somewhere?

**Comment by oli-obk** [comment] 2018-03-23 12:08
Hashing for statics just hashes the `DefId`, yes. https://github.com/rust-lang/rust/blob/15add366faac554db51244d1e27e4d10a08ab6e8/src/librustc/ich/impls_ty.rs#L392

**Comment by oli-obk** [comment] 2018-03-23 12:19
So... we can't use recursion, because of recursive statics (which is the entire reason for the DefId-hashing), but we could keep a `Vec` of the current recursion stack and hash a `0` instead of recursing into an already seen memory and a `1` before every other "recursion" (hashing of an alloc that we're referring to).

This means we need to manually hash the allocation instead of using a generated impl.

**Comment by michaelwoerister** [comment] 2018-03-23 16:24
@oli-obk sounds good. I think you don't even need to hash the 0s and 1s as disambiguators, simply not recursing into allocations that have already been visited should be enough. Also, I would just use a `already_visited` hash set for keeping tracking of where to recurse. That should scale better than a stack that would require linear search. 
This additional state can be kept in the `StableHashingContext`. That's what it's there for.

**Comment by oli-obk** [comment] 2018-03-23 16:39
Oh so we could recurse! That makes things easier. I'll try to get to it on Sunday, but we might still end up needing to backport to beta.

**Comment by michaelwoerister** [comment] 2018-03-23 16:41
Probably, yes. But the fix should be small and self-contained, so that's fine.

**Comment by oli-obk** [comment] 2018-03-30 23:27
Fixed in https://github.com/rust-lang/rust/pull/49424/files

**Closed** 2018-03-30 23:27 UTC
Labels: A-incr-comp, C-bug, T-compiler
