### ISSUE TITLE
#[derive(Default)] should be smarter

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#45036] opened 2017-10-05 01:21 UTC
```rust
#[derive(Default)]
struct A<T> {
    a: Vec<T>,
}

enum D { Da, Db }

fn main() {
    let a = A::<D>::default();
}
```
[> error[E0599]: no function or associated item named `default` found for type `A<D>` in the current scope](https://play.rust-lang.org/?gist=2fa4cb474bcec535ac592affa7067f1f&version=stable)

`#[derive(Default)]` should be smarter so that it doesn't require T to be Default in Vec<T> or Option<T> etc.
This pattern occurs a lot in my real code, and it's very frustrating.

EDIT: It seems [`#[derive(SmartDefault)]`](https://github.com/idanarye/rust-smart-default) is smart enough to not put the Default bound on T. Then the builtin derive(Default) could be at least as smart, too!

**Comment by nagisa** [comment] 2017-10-05 15:49
Duplicate of https://github.com/rust-lang/rust/issues/26925.

**Closed by nagisa** 2017-10-05 15:49 UTC
