### ISSUE TITLE
DWARF loses information about public fields

### ISSUE THREAD

**Issue by tromey** [rust-lang/rust#32919] opened 2016-04-12 22:57 UTC
Consider a structure like

```
pub struct HiBob {
    pub field1: i32,
    field2: u64,
}
```

In the DWARF I see:

```
 <2><107>: Abbrev Number: 8 (DW_TAG_structure_type)
    <108>   DW_AT_name        : (indirect string, offset: 0x3d6): HiBob
    <10c>   DW_AT_byte_size   : 16
 <3><10d>: Abbrev Number: 9 (DW_TAG_member)
    <10e>   DW_AT_name        : (indirect string, offset: 0x3c8): field1
    <112>   DW_AT_type        : <0x7f5>
    <116>   DW_AT_data_member_location: 0
 <3><117>: Abbrev Number: 9 (DW_TAG_member)
    <118>   DW_AT_name        : (indirect string, offset: 0x3cf): field2
    <11c>   DW_AT_type        : <0x766>
    <120>   DW_AT_data_member_location: 8
 <3><121>: Abbrev Number: 0
```

That is, there is nothing distinguishing that `field1` is `pub`.

This can be done by adding `DW_AT_accessibility` to the member DIE.

For gdb this is primarily used to make `ptype` generate nicer output.  So, it is not critical.

**Comment by tromey** [comment] 2016-04-12 22:58
Note that the structure DIE itself should also have this attribute.

**Comment by michaelwoerister** [comment] 2016-04-19 19:08
I'm closing this as a duplicate of #9228.
Thanks for the report though `:)`

**Closed by michaelwoerister** 2016-04-19 19:08 UTC
Labels: A-debuginfo
