### ISSUE TITLE
Regression in compile times after LLVM was upgraded

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#31435] opened 2016-02-05 20:04 UTC
LLVM was recently upgraded in #30448 which appears to have caused a regression
in compile times. First up, let's talk numbers. The compiler revisions in
question are:

* 074f49a350f22b6f33890cd105b2ebe2c790ee3c - just before the LLVM upgrade
* 303892ee156e5c31222b10786e661abb24dcf241 - just after the LLVM upgrade

The `nightly-2016-01-30` toolchain conveniently corresponds exactly to
303892ee156e5c31222b10786e661abb24dcf241. The benchmarks here will all be
compiling libsyntax at these two revision in optimized mode. Note that
libsyntax did not change at all between these two revisions. For local
compilations I configured with:

```
./configure --enable-rpath --disable-optimize-tests --enable-ccache
```

and the C++ compiler version is:

```
$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### Nightly compiler (`nightly-2016-01-30`)

```
$ multirust run nightly-2016-01-30 rustc -vV
rustc 1.8.0-nightly (303892ee1 2016-01-30)
$ time multirust run nightly-2016-01-30 rustc src/libsyntax/lib.rs -O > out
multirust run nightly-2016-01-30 rustc src/libsyntax/lib.rs -O -Z time-passes  129.85s user 1.31s system 99% cpu 2:11.18 total
```

Summary: **2:11.18**s compile time, [full output of time-passes](https://gist.github.com/alexcrichton/6caa509afae7643ceff5)

### Locally compiled after LLVM upgrade (303892ee1)

```
$ ./x86_64-unknown-linux-gnu/stage2/bin/rustc -V
rustc 1.8.0-dev (303892ee1 2016-01-30)
$ time ./x86_64-unknown-linux-gnu/stage2/bin/rustc src/libsyntax/lib.rs -O -Z time-passes > out
./x86_64-unknown-linux-gnu/stage2/bin/rustc src/libsyntax/lib.rs -O -Z  > out  96.16s user 1.29s system 99% cpu 1:37.48 total
```

Summary: **1:37.48**s compile time, [full output of time-passes](https://gist.github.com/alexcrichton/34883cbe4e1e10be7b69)

### Locally compiled before LLVM upgrade (074f49a35)

```
$ ./x86_64-unknown-linux-gnu/stage2/bin/rustc -V
rustc 1.8.0-dev (074f49a35 2016-01-29)
$ time ./x86_64-unknown-linux-gnu/stage2/bin/rustc src/libsyntax/lib.rs -O -Z time-passes > out
./x86_64-unknown-linux-gnu/stage2/bin/rustc src/libsyntax/lib.rs -O -Z  > out  81.39s user 1.28s system 99% cpu 1:22.69 total
```

Summary: **1:22.69**s compile time, [full output of time-passes](https://gist.github.com/alexcrichton/30117ca8a7f97c526fe0)

## Summary

So there are some fascinating data points here:

* ~~The nightlies we're shipping are 35% slower than a locally compiled copy~~ -- Edit: nightly has LLVM assertions enabled where my local compilers did not
* The LLVM upgrade made compilation 18% slower
* Almost the entire compile time difference can be attributed to LLVM
  * [nightly] vs [local-upgraded] is 33s longer in LLVM, and 34s longer overall
  * [local-upgraded] vs [local-before] is 15s longer in LLVM, and 15s longer overall

[nightly]: https://gist.github.com/alexcrichton/6caa509afae7643ceff5#file-out4-L64
[local-upgraded]: https://gist.github.com/alexcrichton/34883cbe4e1e10be7b69#file-out2-L64
[local-before]: https://gist.github.com/alexcrichton/30117ca8a7f97c526fe0#file-out-L64

Ok, so something looks clearly suspicious with LLVM! Let's try and take a closer
look. First, some data dumps of `-Z time-llvm-passes`

* [`nightly-2016-01-30` compiler](https://gist.github.com/alexcrichton/33df0eb8d1bb89e7332b)
* [303892ee1 local compiler](https://gist.github.com/alexcrichton/94d68863313a9db8536d)
* [074f49a35 local compiler](https://gist.github.com/alexcrichton/8c66d83ca257fb473233)

Unfortunately I don't have much of a takeaway from this. Maybe others might
thought?

## Next steps

* Should we revert the LLVM upgrade? This would unfortunately not be trivial.
* Is there something here we can report to upstream LLVM? Is there a bug fix we
  can include in our local LLVM fork temporarily?
* Is this analysis a red herring and perhaps there's something else going on
  here?

**Comment by alexcrichton** [comment] 2016-02-05 20:05
Nominating for triage as well

cc @rust-lang/compiler 
cc @Manishearth 
cc @nikomatsakis 
cc @nrc 
cc @dotdash

**Comment by nagisa** [comment] 2016-02-05 20:11
> Locally compiled after LLVM upgrade (074f49a)

*before*?

**Comment by alexcrichton** [comment] 2016-02-05 20:25
@nagisa ah yeah oops that was a typo (corrected above)

Also I just realized that nightly compilers have LLVM assertions enabled whereas my local compilers did not, that would explain the discrepancy between those timings.

**Comment by Aatch** [comment] 2016-02-09 02:47
Looks like something to ping the LLVM guys about, at least to get some insight. Loop-invariant code motion seems like it's taken a significant hit, with the top 3 LICM passes all taking around twice the time now.

**Comment by dotdash** [comment] 2016-02-10 17:19
This is at least partially caused by the new AA handling which ends up being quadratic in the number of used passes. I've filed an LLVM bug at https://llvm.org/bugs/show_bug.cgi?id=26564

**Comment by nikomatsakis** [comment] 2016-02-11 21:14
triage: P-medium 

Not much to do here besides try to keep an eye on how LLVM progresses in fixes this issue, right? (Rolling back LLVM doesn't really seem like a viable plan.)

**Comment by Aatch** [comment] 2016-02-11 23:32
At the very least we could apply a temporary local patch if it's a quick hack vs. a longer proper fix.

**Comment by Manishearth** [comment] 2016-02-11 23:37
We could perhaps disable that pass? I'm not sure if it *is* a pass that's causing the problem.

**Comment by dotdash** [comment] 2016-02-12 00:15
We could remove TBAA which does nothing for us. That saves a few percent.
Am 12.02.2016 12:37 Vorm. schrieb "Manish Goregaokar" <
notifications@github.com>:

**Comment by alexcrichton** [comment] 2016-02-12 00:22
We've got a pretty long period of time before this reaches stable, so I'd be willing to give the LLVM bug report some more time to get some analysis on behalf of the LLVM folks. If this gets close to stable, however, backporting a change to just disable TBAA seems like it should definitely be worth it! In other words, ideally, there'd be an upstream patch to fix this regressions, we'd backport it to our branch, but failing that we can just locally disable the regression temporarily.

**Comment by jonas-schievink** [comment] 2016-02-12 00:28
This is perhaps a bit off-topic, but why are we running passes that don't do anything for us? Just to keep us close to the C/C++ pass pipeline?

**Comment by dotdash** [comment] 2016-02-20 09:44
Yes, as far as I'm aware that's it. The reason for that is that the default pass setup works reasonablly well so far, and having your own pass setup means more maintenance to keep compatible with different LLVM versions and that you don't automatically profit from improvements made to the default pass setup (obviously). That said, there have been various people who wanted to look into getting a more rust specific pass setup, it's just a ton of work and nothing has been completed (started?) yet.

Also, for this specific analysis, the extra time spent on TBAA was negligible, shouldn't have been much more than just checking for TBAA metadata, seeing that there is none and handing things over to the next AA analysis.

**Comment by sanxiyn** [comment] 2016-03-18 03:04
AA fix landed upstream in LLVM r262490.

**Comment by nikomatsakis** [comment] 2016-04-07 18:54
I'm not 100% sure what the status is here -- but it seems like we merged the fix from upstream, so going to close this as fixed. Feel free to re-open.

**Closed by nikomatsakis** 2016-04-07 18:54 UTC
Labels: I-compiletime, P-medium, regression-from-stable-to-nightly, T-compiler
