### ISSUE TITLE
Internal compiler error when cross compiling with cross for aarch64

### ISSUE THREAD

**Issue by 29988122** [rust-lang/rust#82599] opened 2021-02-27 17:46 UTC
This can be reproduced every time on my side. (vmware ubuntu 20 lts x86-64)

### Code

```Rust
git clone https://github.com/Fluidex/plonkit

then

cross build --target aarch64-unknown-linux-gnu --release
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

### Error output

```
   Compiling clap-v3 v3.0.0-beta.1
   Compiling bellman_vk_codegen v0.2.0 (https://github.com/Fluidex/solidity_plonk_verifier.git#77588cd4)
thread 'rustc' panicked at 'compiler/rustc_resolve/src/imports.rs:1049:33: inconsistent resolution for an import', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/compiler/rustc_middle/src/util/bug.rs:34:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C linker=aarch64-linux-gnu-gcc --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `clap-v3`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
I'm unable to produce even if export RUST_BACKTRACE=1.
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-27 18:00
duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2021-02-27 18:00 UTC
Labels: C-bug, I-ICE, T-compiler
