### ISSUE TITLE
ICE on LTO

### ISSUE THREAD

**Issue by coder543** [rust-lang/rust#47438] opened 2018-01-14 23:56 UTC
cargo output:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0 (766bd11c8 2018-01-01) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: !sess.lto()', /checkout/src/librustc_trans/back/link.rs:1291:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: _ZN11rustc_trans4back4link13link_natively17hbc0fdd9d75452ac3E.llvm.4DE6DCE7
   7: rustc_trans::back::link::link_binary
   8: <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::link_binary
   9: rustc_driver::driver::compile_input
  10: rustc_driver::run_compiler

error: Could not compile `asmtest`.

To learn more, run the command again with --verbose.
```

To reproduce, compile [this project](https://github.com/coder543/asmtest) with LTO enabled. It uses [libasm](https://github.com/coder543/libasm) to ease the use of assembly on stable Rust. For some reason, LTO stops working. Everything works fine without LTO enabled.

**Comment by matthiaskrgr** [comment] 2018-01-15 00:58
Maybe a duplicate of #45689 ?

**Comment by coder543** [comment] 2018-01-15 01:00
The ICE that I reported above is occurring on `1.23.0` (stable), which is a little different, and the circumstances do not involve rustfmt, but it is the same line of code that's crashing, and they could be related.

**Comment by Elinvynia** [comment] 2020-05-09 23:30
I was unable to reproduce this on:
```rustc --version --verbose
rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
binary: rustc
commit-hash: 7ebd87a7a1e0e21767422e115c9455ef6e6d4bee
commit-date: 2020-05-08
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0```

Same with stable:
```rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0```

**Comment by csmoe** [comment] 2022-02-11 12:19
cannot reproduced on latest nightly.

**Closed by csmoe** 2022-02-11 12:19 UTC
Labels: I-ICE, T-compiler, C-bug
