### ISSUE TITLE
API reference doesn't provide documentation for 'test' create.

### ISSUE THREAD

**Issue by lyuts** [rust-lang/rust#29127] opened 2015-10-17 21:32 UTC
While looking for API reference for ```Bencher``` noticed that test crate documentation is completely missing.

**Comment by steveklabnik** [comment] 2015-10-17 22:50
Yes, this is due to its internal status, all the internals docs only get generated with a special flag. This ends up being a duplicate of https://github.com/rust-lang/rust/issues/28309, so I'm going to give it a close. Thanks for filing though!

**Closed by steveklabnik** 2015-10-17 22:50 UTC
