### ISSUE TITLE
Cannot compile `todo!()` in functions returning `impl Trait` with associated types

### ISSUE THREAD

**Issue by nicklimmm** [rust-lang/rust#117293] opened 2023-10-27 17:32 UTC
I tried this code:

```rust
trait Trait {
    type Type;
}

fn foo() -> impl Trait<Type = ()> {
    todo!()
}
```

Expected: 

- Compile without errors, similar to when returning other types such as `i32`, etc.

Instead, this happened:
```
error[E0277]: the trait bound `(): Trait` is not satisfied
 --> src/main.rs:5:13
  |
5 | fn foo() -> impl Trait<Type = ()> {
  |             ^^^^^^^^^^^^^^^^^^^^^ the trait `Trait` is not implemented for `()`
  |
```

Question: 
- Could this be caused by the behavior of having the `!` type in the function body?
    -  `todo!()` macro uses [`core::panicking::panic()`](https://github.com/rust-lang/rust/blob/master/library/core/src/panicking.rs#L120), which returns `!`

### Meta

`rustc --version --verbose`:
```
rustc 1.75.0-nightly (aa1a71e9e 2023-10-26)
binary: rustc
commit-hash: aa1a71e9e90f6eb3aed8cf79fc80bea304c17ecb
commit-date: 2023-10-26
host: aarch64-apple-darwin
release: 1.75.0-nightly
LLVM version: 17.0.3
```

<details><summary>Backtrace</summary>
</details>

**Comment by fmease** [comment] 2023-10-27 17:49
Closing as duplicate of #113875.

**Closed** 2023-10-27 17:50 UTC
Labels: C-bug, needs-triage
