### ISSUE TITLE
ICE: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(for<'r, 's> fn(&'r T, &'s T))) substs=[]

### ISSUE THREAD

**Issue by xarvic** [rust-lang/rust#72542] opened 2020-05-24 17:23 UTC
### Code

```Rust
#![feature(const_generics)]
#![feature(const_compare_raw_pointers)]


struct A<T, const f: fn(&T, &T)> {
    _t: T,
}

impl<T, const f: fn(&T, &T)> A<T, f> {
    fn new(_t: T) -> Self{
        Self{_t}
    }
}
```

### Meta

The Bug appears on the nightly channel

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0

```

### Error output

```
error: internal compiler error: src/librustc/ty/subst.rs:565: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(for<'r, 's> fn(&'r T, &'s T))) substs=[]

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Compiling sorted_collections v0.1.0 (/home/christoph/Workspaces/Rust/sorted_collections)
     Running `rustc --crate-name sorted_collections --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=0139a7a01410b323 -C extra-filename=-0139a7a01410b323 --out-dir /home/christoph/Workspaces/Rust/sorted_collections/target/debug/deps -C incremental=/home/christoph/Workspaces/Rust/sorted_collections/target/debug/incremental -L dependency=/home/christoph/Workspaces/Rust/sorted_collections/target/debug/deps`
warning: the feature `const_generics` is incomplete and may cause the compiler to crash
 --> src/lib.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

error: internal compiler error: src/librustc/ty/subst.rs:565: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(for<'r, 's> fn(&'r T, &'s T))) substs=[]

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::span_bug
  14: rustc_errors::Handler::span_bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::span_bug_fmt
  20: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  21: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable for &rustc::ty::TyS>::super_fold_with
  22: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  23: rustc::ty::structural_impls::fold_list
  24: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable for &rustc::ty::TyS>::super_fold_with
  25: <rustc::ty::subst::SubstFolder as rustc::ty::fold::TypeFolder>::fold_ty
  26: rustc_typeck::check::FnCtxt::instantiate_value_path
  27: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_kind
  28: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation_and_needs
  29: rustc::ty::context::tls::with_context::{{closure}}
  30: rustc_typeck::check::typeck_tables_of
  31: rustc::ty::query::__query_compute::typeck_tables_of
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::typeck_tables_of>::compute
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  35: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  36: rustc_typeck::check::typeck_item_bodies
  37: rustc::ty::query::__query_compute::typeck_item_bodies
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  40: rustc_typeck::check_crate
  41: rustc_interface::passes::analysis
  42: rustc::ty::query::__query_compute::analysis
  43: rustc::dep_graph::graph::DepGraph::with_task_impl
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  45: rustc::ty::context::tls::enter_global
  46: rustc_interface::interface::run_compiler_in_existing_thread_pool
  47: scoped_tls::ScopedKey<T>::set
  48: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (698fcd38f 2020-01-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] processing `A::<T, f>::{{constant}}#0`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `sorted_collections`.

Caused by:
  process didn't exit successfully: `rustc --crate-name sorted_collections --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=0139a7a01410b323 -C extra-filename=-0139a7a01410b323 --out-dir /home/christoph/Workspaces/Rust/sorted_collections/target/debug/deps -C incremental=/home/christoph/Workspaces/Rust/sorted_collections/target/debug/incremental -L dependency=/home/christoph/Workspaces/Rust/sorted_collections/target/debug/deps` (exit code: 101)

Process finished with exit code 101

```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-05-24 17:25
Duplicate of https://github.com/rust-lang/rust/issues/71611

**Closed by jonas-schievink** 2020-05-24 17:25 UTC
Labels: C-bug, I-ICE, T-compiler
