### ISSUE TITLE
ICE for nightly rustc 1.12.0-dev (b6c1ef374 2016-07-14)  when compiling regex crate

### ISSUE THREAD

**Issue by alsam** [rust-lang/rust#34835] opened 2016-07-15 11:39 UTC
Hello,
I've got an internal compiler error with
```sh
rustc --version
rustc 1.12.0-dev (b6c1ef374 2016-07-14)
```
How to reproduce it:
```sh
git clone https://github.com/rust-lang-nursery/regex
Cloning into 'regex'...
remote: Counting objects: 8644, done.
remote: Total 8644 (delta 0), reused 0 (delta 0), pack-reused 8644
Receiving objects: 100% (8644/8644), 6.05 MiB | 2.90 MiB/s, done.
Resolving deltas: 100% (6849/6849), done.
Checking connectivity... done.
$ cd regex/
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling utf8-ranges v0.1.3
   Compiling regex-syntax v0.3.4 (file:///home/asamoilo/work/github/rust-samples/regex/regex-syntax)
   Compiling libc v0.2.14
   Compiling winapi v0.2.8
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling thread-id v2.0.0
   Compiling memchr v0.1.11
   Compiling thread_local v0.2.6
   Compiling aho-corasick v0.5.2
   Compiling regex v0.1.73 (file://.../work/github/rust-samples/regex)
error: internal compiler error: src/librustc/infer/region_inference/mod.rs:734: cannot relate bound region: '_#0r <= ReEarlyBound(TypeSpace, 0, 'r)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:580
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `regex`.
```

a backtrace:
```sh
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:580                                                                              
stack backtrace:                                                                                                                                   
   1:     0x7f27ea48e79f - std::sys::backtrace::tracing::imp::write::hf504bc08f2a3011f                                                             
   2:     0x7f27ea4a5e6b - std::panicking::default_hook::_{{closure}}::h49b28af2d05b6140                                                           
   3:     0x7f27ea49e9e7 - std::panicking::default_hook::hf5d79ad4f1ead81e                                                                         
   4:     0x7f27ea49f10c - std::panicking::rust_panic_with_hook::h9a3925e37821d434                                                                 
   5:     0x7f27e9ec36e8 - std::panicking::begin_panic::hdf32e6f0d48da313                                                                          
   6:     0x7f27e9f28cb5 - rustc::session::opt_span_bug_fmt::_{{closure}}::hfbd05ef01f930389                                                       
   7:     0x7f27e9f28a8d - rustc::ty::context::tls::with_opt::_{{closure}}::hf052d4aa2a56d43a                                                      
   8:     0x7f27e9f2731d - rustc::ty::context::tls::with::_{{closure}}::hb3938faea4e67369                                                          
   9:     0x7f27e896c2a4 - rustc::session::opt_span_bug_fmt::he49e515088fa8437                                                                     
  10:     0x7f27e896c1c4 - rustc::session::span_bug_fmt::h40548a94744de842                                                                         
  11:     0x7f27e88afd4e - rustc::infer::region_inference::RegionVarBindings::make_subregion::hea6d7f7feff509e8                                    
  12:     0x7f27e88af8db - rustc::infer::region_inference::RegionVarBindings::make_eqregion::h12e449b6d33201a8                                     
  13:     0x7f27e888c219 - _<rustc..infer..equate..Equate<'a, 'gcx, 'tcx> as rustc..ty..relate..TypeRelation<'a, 'gcx, 'tcx>>::regions::hb8d7946cee89a361
  14:     0x7f27e87da182 - _<&'a mut I as core..iter..iterator..Iterator>::next::h40c39ed3041b027d                                                       
  15:     0x7f27e89cba70 - rustc::ty::relate::relate_substs::ha20cc22e09ccff78                                                                           
  16:     0x7f27e89c6f36 - rustc::ty::relate::relate_item_substs::hf669fec513c5c374
  17:     0x7f27e888a50b - _<rustc..infer..equate..Equate<'a, 'gcx, 'tcx> as rustc..ty..relate..TypeRelation<'a, 'gcx, 'tcx>>::tys::he042e4faca40a521
  18:     0x7f27e8a3576f - rustc::ty::relate::relate_type_params::_{{closure}}::h27ac1d6284ceaedc
  19:     0x7f27e89cb2ea - rustc::ty::relate::relate_substs::ha20cc22e09ccff78
  20:     0x7f27e89c6f36 - rustc::ty::relate::relate_item_substs::hf669fec513c5c374
  21:     0x7f27e89d12b9 - _<rustc..ty..sty..TraitRef<'tcx> as rustc..ty..relate..Relate<'tcx>>::relate::h986b72a0959563fb
  22:     0x7f27e8a68881 - rustc::infer::InferCtxt::eq_trait_refs::_{{closure}}::h66412c5d53af9fe3
  23:     0x7f27e88cb0e2 - rustc::infer::InferCtxt::eq_trait_refs::h1a047bc0d7cb9287
  24:     0x7f27e8999e9d - rustc::traits::select::SelectionContext::match_impl::hc59fa4b835fb8273
  25:     0x7f27e8a7b3a5 - rustc::traits::select::SelectionContext::assemble_candidates_from_impls::_{{closure}}::_{{closure}}::h477fb8af4d02a8d4
  26:     0x7f27e89d92d0 - rustc::ty::trait_def::TraitDef::for_each_relevant_impl::h48255f01a2713db2
  27:     0x7f27e8991f06 - rustc::traits::select::SelectionContext::assemble_candidates::h5d6c8f4149f33306
  28:     0x7f27e898fc3a - rustc::traits::select::SelectionContext::candidate_from_obligation::h57e2e1988c8b0c1d
  29:     0x7f27e898dc46 - rustc::traits::select::SelectionContext::select::hb8e03770ff77bdb9
  30:     0x7f27e8a6a0a2 - rustc::traits::project::assemble_candidates_from_impls::_{{closure}}::h3bceaaae4cf282ac
  31:     0x7f27e8986154 - rustc::traits::project::opt_normalize_projection_type::hb3e854cc28a2d57e
  32:     0x7f27e8984e21 - rustc::traits::project::normalize_projection_type::he1f9e46d61d58258
  33:     0x7f27e89845cc - _<rustc..traits..project..AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc..ty..fold..TypeFolder<'gcx, 'tcx>>::fold_ty::h15923c441f55c226
  34:     0x7f27e8984854 - _<rustc..traits..project..AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc..ty..fold..TypeFolder<'gcx, 'tcx>>::fold_ty::h15923c441f55c226
  35:     0x7f27e8983df3 - rustc::traits::project::normalize_with_depth::hb7f7e51a4e47f9d6
  36:     0x7f27e89bd9de - rustc::ty::layout::normalize_associated_type::hb00ed9155d9e3b1b
  37:     0x7f27e89be996 - rustc::ty::layout::Layout::compute_uncached::hd0d122453c9f7281
  38:     0x7f27e89e2b27 - rustc::ty::util::_<impl rustc..ty..TyS<'tcx>>::layout::ha131ccfdd57ad834
  39:     0x7f27e89be9ae - rustc::ty::layout::Layout::compute_uncached::hd0d122453c9f7281
  40:     0x7f27e89e2b27 - rustc::ty::util::_<impl rustc..ty..TyS<'tcx>>::layout::ha131ccfdd57ad834
  41:     0x7f27e89c0a48 - rustc::ty::layout::Layout::compute_uncached::hd0d122453c9f7281
  42:     0x7f27eaa83d36 - _<rustc_lint..types..VariantSizeDifferences as rustc..lint..LateLintPass>::check_item::_{{closure}}::h3b1717a1203e5bc6
  43:     0x7f27eaa81633 - rustc::infer::InferCtxtBuilder::enter::_{{closure}}::h53c4b8b89c93e797
  44:     0x7f27eaa7d32b - _<rustc_lint..types..VariantSizeDifferences as rustc..lint..LateLintPass>::check_item::ha61bf20498c6f8a4
  45:     0x7f27e8a6d40f - _<rustc..lint..context..LateContext<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::_{{closure}}::h2802a30b44885b0e
  46:     0x7f27e88e8afc - _<rustc..lint..context..LateContext<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::hc8793eddc36b5a93
  47:     0x7f27e88eaccb - _<rustc..lint..context..LateContext<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_mod::h545bb6c839c10530
  48:     0x7f27e8a6d684 - _<rustc..lint..context..LateContext<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::_{{closure}}::h2802a30b44885b0e
  49:     0x7f27e88e8afc - _<rustc..lint..context..LateContext<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::hc8793eddc36b5a93
  50:     0x7f27e88eaccb - _<rustc..lint..context..LateContext<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_mod::h545bb6c839c10530
  51:     0x7f27e8a6cefe - rustc::lint::context::check_crate::_{{closure}}::h7bd599bdee209a50
  52:     0x7f27e88f216d - rustc::lint::context::check_crate::hc8fbee831bb2bd7c
  53:     0x7f27ea8e1e98 - rustc_driver::driver::phase_3_run_analysis_passes::_{{closure}}::he1de538a7584312e
  54:     0x7f27ea8d6db2 - rustc::ty::context::tls::enter_global::_{{closure}}::h8575bf8dd37062fa
  55:     0x7f27ea837a61 - rustc::ty::context::TyCtxt::create_and_enter::he5466411552b055e
  56:     0x7f27ea891f53 - rustc_driver::driver::compile_input::h2d1b58b831f06a86
  57:     0x7f27ea8b846c - rustc_driver::run_compiler::h833483649bdaa9c3
  58:     0x7f27ea92f097 - rustc_driver::run::_{{closure}}::hf976882a071eba86
  59:     0x7f27ea929f3b - rustc_driver::monitor::_{{closure}}::hd347b359cf4c5640
  60:     0x7f27ea80d31d - std::panicking::try::call::hd16aacc09eeeaf9e
  61:     0x7f27ea4b3d1b - __rust_try
  62:     0x7f27ea4b3bfe - __rust_maybe_catch_panic
  63:     0x7f27ea8d437d - std::thread::Builder::spawn::_{{closure}}::hf8ba3712412ac8f6
  64:     0x7f27ea82717e - _<F as alloc..boxed..FnBox<A>>::call_box::hbf614b3f826456b6
  65:     0x7f27ea49c934 - std::sys::thread::Thread::new::thread_start::h2e98425c7fffa990
  66:     0x7f27e5a24850 - start_thread
  67:     0x7f27ea0e190c - clone
  68:                0x0 - <unknown>

error: Could not compile `regex`.
```

Thanks

**Comment by TimNN** [comment] 2016-07-15 13:26
Looks like a duplicate of #34780.

**Comment by alsam** [comment] 2016-07-15 16:10
Yes, and duplicate of this one too https://github.com/rust-lang/rust/issues/34791
Thanks for noticing.

**Comment by alexcrichton** [comment] 2016-07-15 16:17
Indeed!

**Closed by alexcrichton** 2016-07-15 16:17 UTC
