### ISSUE TITLE
Copy derive is ignored by rustc

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust#56008] opened 2018-11-16 17:31 UTC
(Related with https://github.com/rust-lang/rust/issues/26925)

I have a type `Amount` defined like this (took all irrelevant pieces out):
```rust
use std::marker::PhantomData;

pub trait Precision {}

pub struct Satoshi;
impl Precision for Satoshi {}

type Inner = i64;

#[derive(Copy, Clone)]
pub struct Amount<P: Precision = Satoshi>(Inner, PhantomData<P>);
```

Now, in some unit test, I'm trying to do something like this (again, redacted):
```rust
#[test]
fn string_parse_roundtrip() {
    let amt = Amount::sat(42); // returns Amount<Satoshi>
    assert_eq!(Amount::from_str(&amt.to_string()), Ok(amt)); // line 647
    assert_eq!(Amount::from_str(&amt.to_string()), Ok(amt)); // line 648
    // repeats multiple times because in fact it's not to_string, 
    // but a slightly different method
}
```

For which rustc gives me the following error:
```
error[E0382]: use of moved value: `amt`                                                                                                                       
   --> src/util/amount.rs:648:38                                                                                                                              
    |                                                                                                                                                         
647 |         assert_eq!(Amount::from_str(&amt.to_string()), Ok(amt));                                                                           
    |                                                           --- value moved here                                                             
648 |         assert_eq!(Amount::from_str(&amt.to_string()), Ok(amt));                                                                      
    |                                      ^^^ value used here after move                                                                                     
    |                                                                                                                                                         
    = note: move occurs because `amt` has type `util::amount::Amount`, which does not implement the `Copy` trait 
```

**Comment by steveklabnik** [comment] 2018-11-16 17:39
I don't *believe* this is a bug. Your original code expands to

```rust
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;

use std::marker::PhantomData;

pub trait Precision {}

pub struct Satoshi;
impl Precision for Satoshi {}

type Inner = i64;

#[rustc_copy_clone_marker]
pub struct Amount<P: Precision = Satoshi>(Inner, PhantomData<P>);
#[automatically_derived]
#[allow(unused_qualifications)]
impl<P: ::std::marker::Copy + Precision> ::std::marker::Copy for Amount<P> {}
#[automatically_derived]
#[allow(unused_qualifications)]
impl<P: ::std::clone::Clone + Precision> ::std::clone::Clone for Amount<P> {
    #[inline]
    fn clone(&self) -> Amount<P> {
        match *self {
            Amount(ref __self_0_0, ref __self_0_1) => Amount(
                ::std::clone::Clone::clone(&(*__self_0_0)),
                ::std::clone::Clone::clone(&(*__self_0_1)),
            ),
        }
    }
}
~\tmp\foo [master +14 ~0 -0 !]>
```

Note that `Copy` is only implemented if `P` also implements `Copy`. `Satoshi` does not implement `Copy`, and therefore, neither does `Amount`.

**Comment by stevenroose** [comment] 2018-11-16 17:55
Well, before I used `PhantomData`, this was true. I had to define `Precision: Copy, Clone` (the compiler complained). [`PhantomData` implements `Copy` without the type parameter requiring to be `Copy`](https://doc.rust-lang.org/std/marker/struct.PhantomData.html#impl-Copy).

With this snipper, the compiler doesn't complain about the derives.

**Comment by stevenroose** [comment] 2018-11-16 17:59
Here is the original PR that contains this code: https://github.com/rust-bitcoin/rust-bitcoin/pull/192

**Comment by stevenroose** [comment] 2018-11-16 19:38
So something else came up in that test. I changed the snippet above to be the following:
```rust
use std::marker::PhantomData;

pub trait Precision: Copy + Clone + std::hash::Hash {}

#[derive(Copy, Clone, Hash)]
pub struct Satoshi;
impl Precision for Satoshi {}

type Inner = i64;

#[derive(Copy, Clone, Hash)]
pub struct Amount<P: Precision = Satoshi>(Inner, PhantomData<P>);
```

And then, my unit test, in complete looking like this: 
```rust
    #[test]
    fn to_string_in_from_str_roundtrip() {
        use super::Denomination as D;

        let amt = Amount::sat(42); // returns Amount<Satoshi>
        assert_eq!(Amount::from_str(&amt.to_string_in(D::Bitcoin)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::MilliBitcoin)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::MicroBitcoin)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::Bit)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::Satoshi)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::MilliSatoshi)), Ok(amt));

        let amt = Amount::msat(42); // returns Amount<MilliSatoshi>
        assert_eq!(Amount::from_str(&amt.to_string_in(D::Bitcoin)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::MilliBitcoin)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::MicroBitcoin)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::Bit)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::Satoshi)), Ok(amt));
        assert_eq!(Amount::from_str(&amt.to_string_in(D::MilliSatoshi)), Ok(amt));
    }
```

This test seems to crash `cargo test`. I get this message:
```
$ cargo test util::amount::tests::to_string_in_from_str_roundtrip
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s                                                                                                 
     Running target/debug/deps/bitcoin-5e6dd72e63c8bbee

running 1 test
error: process didn't exit successfully: `/home/steven/code/rust/bitcoin/target/debug/deps/bitcoin-5e6dd72e63c8bbee 'util::amount::tests::to_string_in_from_str_roundtrip'` (signal: 9, SIGKILL: kill)
```

Commenting out that test, removes the problem.

Would there be a problem with `PhantomData` deriving either `Copy`, `Clone` or `Hash`?

**Comment by cuviper** [comment] 2018-11-16 21:53
> `PhantomData` implements `Copy` without the `Copy` requirement on the type parameter.

It does, but `#[derive]` doesn't try to be that clever.  See #26925.

**Comment by bddap** [comment] 2018-11-17 00:44
I ran into the same issue.

```rust
use std::marker::PhantomData;

#[derive(Copy, Clone)]
struct SpookyThing<T> {
    phantom: PhantomData<*const T>,
}

#[derive(Clone)]
struct NotCopyable;

fn main() {
    let scary = SpookyThing::<NotCopyable> {
        phantom: PhantomData,
    };
    creep(scary, scary);
}

fn creep<T>(_creep1: SpookyThing<T>, _creep2: SpookyThing<T>) {}
```

```
error[E0382]: use of moved value: `scary`
  --> src/main.rs:15:18
   |                      
15 |     creep(scary, scary);
   |           -----  ^^^^^ value used here after move
   |           | 
   |           value moved here
   |
   = note: move occurs because `scary` has type `SpookyThing<NotCopyable>`, which does not implement the `Copy` trait
```

It seems derive pays attention to the type of template argument, not the actual data items.

**Comment by bddap** [comment] 2018-11-17 00:55
You can work around the issue by implementing Clone and Copy manually.

```rust
struct SpookyThing<T> {
    phantom: PhantomData<*const T>,
}

impl<T> Clone for SpookyThing<T> {
    fn clone(&self) -> Self {
        SpookyThing {
            phantom: PhantomData
        }
    }
}

impl<T> Copy for SpookyThing<T> {}
```

If you attempt to derive Copy, **and** implement Copy manually, rustc does report an error.

```rust
#[derive(Copy, Clone)]
struct SpookyThing<T> {
    phantom: PhantomData<*const T>,
}

impl<T> Clone for SpookyThing<T> {
    fn clone(&self) -> Self {
        SpookyThing {
            phantom: PhantomData
        }
    }
}

impl<T> Copy for SpookyThing<T> {}
```

```
error[E0119]: conflicting implementations of trait `std::marker::Copy` for type `SpookyThing<_>`:
  --> src/main.rs:3:10
   |
3  | #[derive(Copy, Clone)]
   |          ^^^^ conflicting implementation for `SpookyThing<_>`
...
16 | impl<T> Copy for SpookyThing<T> {}
   | ------------------------------- first implementation here

error[E0119]: conflicting implementations of trait `std::clone::Clone` for type `SpookyThing<_>`:
 --> src/main.rs:3:16
  |
3 | #[derive(Copy, Clone)]
  |                ^^^^^ conflicting implementation for `SpookyThing<_>`
...
8 | impl<T> Clone for SpookyThing<T> {
  | -------------------------------- first implementation here
```

**Comment by stevenroose** [comment] 2018-11-17 16:18
Yeah I also implemented the traits manually as a workaround. I put the original issue (https://github.com/rust-lang/rust/issues/26925) in the OP.

**Comment by oli-obk** [comment] 2018-11-18 13:11
Marking as duplicate of #26925

**Comment by rodrimati1992** [comment] 2018-11-19 08:45
You can work around this by creating a type alias which passes a PhantomData of P,
and using that type alias instead of the type.

```
use std::marker::PhantomData;

pub trait Precision {}

pub struct Satoshi;
impl Precision for Satoshi {}

type Inner = i64;

pub type Ammount<P=Satoshi>
    __Ammount<PhantomData<P>>;

#[derive(Copy, Clone)]
pub struct __Amount<P: Precision>(
    Inner,
    PhantomData<P>
);
```

**Comment by jonas-schievink** [comment] 2019-01-17 20:43
This is a duplicate of #26925, I suggest closing in favor of that

**Closed** 2019-01-18 11:41 UTC
