### ISSUE TITLE
ICE when trying to match on non-PartialEq slice.

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#61188] opened 2019-05-25 17:23 UTC
The following code will result in an ICE in ~~codegen~~ MIR construction:

```rust
struct B(i32);

const A: &[B] = &[];

fn main() {
    match &[][..] {
        A => (),
        _ => (),
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4db539e3f11d582083944d361b64cec9)

<details>

<summary>Error and Backtrace</summary>

```text
error: internal compiler error: src/librustc/traits/codegen/mod.rs:156: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<B as std::cmp::PartialEq>)),depth=2),Unimplemented)]` resolving bounds after type-checking

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:570:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:

 0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::span_bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::span_bug_fmt
  14: rustc::traits::codegen::<impl rustc::infer::InferCtxt>::drain_fulfillment_cx_or_panic
  15: rustc::ty::context::GlobalCtxt::enter_local
  16: rustc::traits::codegen::codegen_fulfill_obligation
  17: rustc::ty::query::__query_compute::codegen_fulfill_obligation
  18: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::codegen_fulfill_obligation>::compute
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  21: rustc::ty::instance::Instance::resolve
  22: rustc_mir::lints::check
  23: rustc::ty::context::GlobalCtxt::enter_local
  24: rustc_mir::build::mir_build
  25: rustc_mir::transform::mir_built
  26: rustc::ty::query::__query_compute::mir_built
  27: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_built>::compute
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  30: rustc_mir::transform::check_unsafety::unsafety_check_result
  31: rustc::ty::query::__query_compute::unsafety_check_result
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::unsafety_check_result>::compute
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  35: rustc_mir::transform::mir_const
  36: rustc::ty::query::__query_compute::mir_const
  37: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_const>::compute
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  40: rustc_mir::transform::mir_validated
  41: rustc::ty::query::__query_compute::mir_validated
  42: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_validated>::compute
  43: rustc::dep_graph::graph::DepGraph::with_task_impl
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  45: rustc_mir::borrow_check::mir_borrowck
  46: rustc::ty::query::__query_compute::mir_borrowck
  47: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::mir_borrowck>::compute
  48: rustc::dep_graph::graph::DepGraph::with_task_impl
  49: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  50: rustc::ty::<impl rustc::ty::context::TyCtxt>::par_body_owners
  51: rustc::util::common::time
  52: rustc_interface::passes::analysis
  53: rustc::ty::query::__query_compute::analysis
  54: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::analysis>::compute
  55: rustc::dep_graph::graph::DepGraph::with_task_impl
  56: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  57: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  58: rustc_interface::passes::create_global_ctxt::{{closure}}
  59: rustc_interface::interface::run_compiler_in_existing_thread_pool
  60: std::thread::local::LocalKey<T>::with
  61: scoped_tls::ScopedKey<T>::set
  62: syntax::with_globals
query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::cmp::PartialEq` fulfills its obligations
#1 [mir_built] processing `main`
#2 [unsafety_check_result] processing `main`
#3 [mir_const] processing `main`
#4 [mir_validated] processing `main`
#5 [mir_borrowck] processing `main`
#6 [analysis] running analysis passes on this crate
end of query stack
```

</details>

**Comment by estebank** [comment] 2019-05-25 19:29
CC #53708

**Comment by pnkfelix** [comment] 2019-06-06 11:22
As implied by @estebank above, this seems very likely to be a duplicate (or at least strongly related to) #53708 ...

**Comment by pnkfelix** [comment] 2019-06-06 11:31
Ah ha!

If you add `#[derive(PartialEq, Eq)]` to the `struct B(i32)` in the example above, then the code compiles successfully.

Which may be something a user *might* infer from the message ...
> Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<B as std::cmp::PartialEq>)),depth=2),Unimplemented)]`

... but probably not 🤣

**Comment by pnkfelix** [comment] 2019-06-06 11:38
triage: P-high. I want to know why we are not catching the failure to fulfill `B: PartialEq` earlier in the compilation. Is this perhaps a const-eval issue, based on the stack trace?

**Comment by eddyb** [comment] 2019-06-06 12:54
I suspect `rustc_typeck` is not enforcing it, and MIR borrowck, as I found recently, doesn't produce user errors from trait matching, but rather expects it to succeed, and only uses them to get lifetime obligations.

**Comment by pnkfelix** [comment] 2019-06-06 14:30
assigning to self with intent to try to mentor.

**Comment by pnkfelix** [comment] 2019-07-02 12:52
I started looking at this, with the intent of writing mentorship notes. I'm going to try to jot down notes on my process as I go, with the intent of showing a mentee what kinds of experiments one might do to figure out how to narrow down the code to the point of interest for finding a fix.

To be clear, I don't consider myself an expert in the MIR generation code; I've done some work in it, but I am at a point where I need to reacquaint myself with it before I'd feel comfortable hacking on it.

So, here's the steps I've done so far:

 1. Copy the test case into its own file (I named mine `issue-61188-match-nonpartialeq-graceful.rs`). I ran `rustc` on that, using `RUST_BACKTRACE=1` again just to confirm that it still fails, and to skim over the lines of code that panicked in context.
 2. Based on @eddyb's comment above, I decided I need to see some `RUSTC_LOG` output from the modules in question. So I ran `rustc` again, first using `RUST_LOG=rustc::ty::instance,rustc_mir::build`, and then after seing no debug output, using `RUSTC_LOG=rustc::ty::instance,rustc_mir::build` instead. (I keep forgetting that we renamed the environment variable back in PR #60401.)
 3. After skimming over the log and deciding I wanted to focus on instances of constants mentioned in the output of match processing, I loaded the log output into `emacs`, used `M-x highlight-regexp` to highlight all instances of `kind: Constant { value: Const`, and then starting searching for the instances of that string.
 4. I happened to notice one of the relevant lines said it was a test with `kind: Eq`. For some reason I had forgotten (or never knew about) this variant of `TestKind`, shown here:
https://github.com/rust-lang/rust/blob/ef064d2f66bf5851e1da1a016627ff1395f6c9ad/src/librustc_mir/build/matches/mod.rs#L743-L751

Look at that comment (added back in df3de7b4b3e9, many thanks @matthewjasper!); the fact that you see three types that really can be hard-coded into the compiler, and then *one* special case of `&[T]` is super-subtle, and perhaps a little suspicious.

That's where I decided I wanted to start taking some notes, since arguably I was supposed to be making mentorship instructions for this, but if I get further into the weeds without documenting the context, I won't be able to make sensible instructions.

**Comment by pnkfelix** [comment] 2019-07-02 13:03
To be clear, the reason that I saw the `TestKind::Eq` variant as a good place to take a note is because I see that as opening up a useful thing to search for in the code base (to find spots where that variant is created), and then do one of two thingss:

Either:
 1. Add a check, right before creating `TestKind::Eq`, that the given type implements `PartialEq`, or
 2. If it is still to late at this point to add said check, then use the context of where `TestKind::Eq` is created to figure out the shape of the data structure that we have in our hands, so that we can add the necessary check earlier in the compiler control flow.

**Comment by pnkfelix** [comment] 2019-07-02 13:32
And reading over rust-lang/rfcs#1445 led me to find that the current code (linked below) for linting use of `#[structural_match]` is, well, insufficient: it special cases matching `Adt` consts and matching `&Adt` consts, but fails to handle `& &Adt` consts and `&[Adt]` consts, etc.

https://github.com/rust-lang/rust/blob/ef064d2f66bf5851e1da1a016627ff1395f6c9ad/src/librustc_mir/hair/pattern/mod.rs#L988-L1012

**Comment by pnkfelix** [comment] 2019-07-02 14:03
Filed #62307 to track the insufficient check for `#[structural_match]`.

**Comment by pnkfelix** [comment] 2019-07-03 15:36
(the change suggested in PR #62339 fixes this and has a regression test for it.)

**Comment by matthewjasper** [comment] 2019-08-04 20:45
Reopening because there are still cases where we ICE:

```rust
#![deny(indirect_structural_match)]

#[derive(PartialEq, Eq)]
enum O<T> {
    Some(*const T), // Can also use PhantomData<T>
    None,
}

struct B;

const C: &[O<B>] = &[O::None];

pub fn foo() {
    let x = O::None;
    match &[x][..] {
        C => (),
        _ => (),
    }
}
```

We might want to move to a trait based approach as in https://github.com/rust-lang/rust/pull/63248#discussion_r310364215

**Comment by pnkfelix** [comment] 2019-09-19 13:39
visiting for triage. I agree with @matthewjasper about potentially moving to a trait-based approach.

part of me is tempted to jump into implementing that. But it probably makes more sense for me to write up mentorship instructions, maybe.

**Comment by pnkfelix** [comment] 2019-10-03 13:50
triage: this is probably easy to resolve but I have not had time myself to write up mentorship instructions. Marking bug accordingly (i.e. "need-mentor" is to be interpreted as "if you are willing to help make some instructions, I'd love it...")

**Comment by pnkfelix** [comment] 2019-10-08 08:42
Note: moving to a trait-based approach alone won't resolve *every* ICE. Not without regressing other stable code, least.

In particular:
 * We allow people to put function pointers in their constants (and in the types of their constants).
 * Function pointers like `fn(&T)` desugar to `for <'a> fn(&'a T)`.
 * `for <'a> fn(&'a T)` does not implement `PartialEq` (see https://github.com/rust-lang/rust/issues/46989#issuecomment-353805481 )

I discovered this while exploring cases related to #63438 and #63479 

Here is a concrete example ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=25aa88c69c6f04407fc3d44280baf72a)):

```rust
fn assert_partialeq<T: PartialEq>(_: &T) {}

fn rquux(_: &()) { }
const RQ: fn(&()) = rquux;
const LRQ: &[fn(&())] = &[];

fn main() {
    // assert_partialeq(&RQ); (RQ isn't PartialEq, and this will say so.)

    match RQ {
        RQ => println!("RQ"),
        _ => {}
    };

    let input: &[fn(&())] = &[][..];
    match input {
        LRQ => println!("LRQ"), // compiles if you comment this out
        &[] => println!("matched inlined pattern"),
        _ => {}
    };
}

```

(The "obvious solution" of just requiring const patterns to always implement `PartialEq` will break the matching of `RQ`, which is why we can't just adopt that solution.)

**Comment by pnkfelix** [comment] 2019-10-16 09:56
(closing this bug so we can let issue #65466 be dedicated to tracking the more subtle problem laid out in @matthewjasper 's [comment above](https://github.com/rust-lang/rust/issues/61188#issuecomment-539414038).)

**Closed by pnkfelix** 2019-10-16 09:56 UTC
Labels: A-mir, C-bug, E-needs-mentor, I-ICE, P-high, T-compiler, glacier
