### ISSUE TITLE
"Internal mode" for rustdoc

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#25568] opened 2015-05-18 12:42 UTC
For those writing larger software (e.g. Servo), `rustdoc` is a useful tool for exploring the internal methods of a crate. However, non-exported items aren't shown.

Perhaps an "internal" mode which doesn't filter out private items would be nice.

See also: http://www.reddit.com/r/rust/comments/36ce52/reflections_on_a_weekend_with_rust/crcv9kv.compact

**Comment by SimonSapin** [comment] 2015-05-18 16:24
This looks like a duplicate of https://github.com/rust-lang/rust/issues/15347 which is closed since there is a work around (`--no-defaults --passes "collapse-docs" --passes "unindent-comments"`). https://github.com/rust-lang/cargo/issues/1520 is about making it usable in `cargo doc`.

**Comment by alexcrichton** [comment] 2015-05-18 16:50
Agreed with @SimonSapin

**Closed by alexcrichton** 2015-05-18 16:50 UTC
