### ISSUE TITLE
async fn in trait: trait method with default impl doesn't work

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#102308] opened 2022-09-26 12:00 UTC
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=82e8d90150eb8019eccc5c13449d5228)

```rust
trait Foo {
    async fn bar(&mut self) {}
}
```

fails with

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:5:29
  |
5 |     async fn bar(&mut self) {}
  |                             ^^ expected associated type, found opaque type
  |
  = note: expected associated type `impl Future<Output = ()>` (trait associated opaque type at <src/main.rs:5:29>)
                 found opaque type `impl Future<Output = ()>` (opaque type at </rustc/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032/library/core/src/future/mod.rs:72:43>)
```

Nightly version: 1.66.0-nightly (2022-09-25 f5193a9fcc73dc09e41a)

@rustbot label +F-async_fn_in_traits

**Comment by compiler-errors** [comment] 2022-09-26 13:35
Duplicate of #101665

**Comment by compiler-errors** [comment] 2022-10-22 00:32
This works now.

**Closed by compiler-errors** 2022-10-22 00:32 UTC
Labels: F-async_fn_in_traits
