### ISSUE TITLE
ICE with borrowing with Futures

### ISSUE THREAD

**Issue by mersinvald** [rust-lang/rust#45437] opened 2017-10-21 23:20 UTC
Compiler ICEd on the code with mutable borrowing inside futures

#### I tried this code:

```rust
#![feature(conservative_impl_trait)] 
extern crate futures;

use futures::Future;
use futures::future::ok;

fn future1(data: &i32) -> impl Future<Item=&i32, Error=()> {
    ok(data)
}

fn main() {
    future1(&1).wait().unwrap();
}

```
https://play.rust-lang.org/?gist=62c4c9c732f500dab053d57fcd83fc11&version=nightly

#### I expected to see this happen:

Borrowing error saying me that I can't use anonymous lifetimes within futures 

#### Instead, this happened: 

ICE

## Meta

`rustc --version --verbose`:

```
rustc 1.22.0-nightly (f6d751454 2017-10-17)
binary: rustc
commit-hash: f6d7514545cbe83e771a400d04049b96dfb210cd
commit-date: 2017-10-17
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0
```

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:439:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::span_bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::span_bug_fmt
   9: rustc_typeck::check::Inherited::register_predicate
  10: <rustc::ty::fold::BottomUpFolder<'a, 'gcx, 'tcx, F> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
  11: rustc_typeck::check::check_fn
  12: rustc_typeck::check::typeck_tables_of::{{closure}}
  13: rustc_typeck::check::typeck_tables_of
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::force
  15: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  16: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::ensure
  18: rustc_typeck::check::typeck_item_bodies
  19: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::force
  20: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get
  21: rustc::ty::maps::TyCtxtAt::typeck_item_bodies
  22: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies
  23: rustc_typeck::check_crate
  24: rustc::ty::context::TyCtxt::create_and_enter
  25: rustc_driver::driver::compile_input
  26: rustc_driver::run_compiler
```

**Comment by mersinvald** [comment] 2017-10-21 23:27
Looks like an `impl Trait` is causing the problem. The following compiles well:
```rust
#![feature(conservative_impl_trait)] 
extern crate futures;

use futures::Future;
use futures::future::FutureResult;
use futures::future::ok;

fn future1(world: &i32) -> FutureResult<&i32, ()> {
    ok(world)
}

fn main() {
    future1(&1).wait().unwrap();
}
```

**Comment by mersinvald** [comment] 2017-10-21 23:30
Also, the **valid** code with explicit lifetimes compiles well.

```
#![feature(conservative_impl_trait)] 
extern crate futures;

use futures::Future;
use futures::future::ok;

fn future1<'a>(data: &'a i32) -> impl Future<Item=&'a i32, Error=()> + 'a {
    ok(data)
}

fn main() {
    future1(&1).wait().unwrap();
}
```

**Comment by kennytm** [comment] 2017-10-22 06:08
Duplicate of #43396, #42479.

**Closed by kennytm** 2017-10-22 06:08 UTC
