### ISSUE TITLE
GitHub Actions "tools" builder is broken

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#71184] opened 2020-04-16 06:54 UTC
In https://github.com/rust-lang/rust/pull/71173, the Azure "tools" PR builder succeeded, but the GHA "tools" builder failed twice because it considers rls and rustfmt broken, [saying](https://github.com/rust-lang/rust/runs/590568656)
```
error[E0464]: multiple matching crates for `getopts`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_session-651.0.0/lib.rs:6:1
  |
6 | extern crate getopts;
  | ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: candidates:
          crate `getopts`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-c1029da41ced9898.rlib
          crate `getopts`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-0ef7d7c079c561c3.rlib

error[E0463]: can't find crate for `getopts`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_session-651.0.0/lib.rs:6:1
  |
6 | extern crate getopts;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors
```
Looks to me like something is wrong with the GHA builder.

Cc @pietroalbini

**Comment by Mark-Simulacrum** [comment] 2020-04-16 10:51
This is almost certainly not spurious - rustfmt likely needs to update it's version of the autopublished rustc_session crate. I can take a look today at doing so.

**Comment by RalfJung** [comment] 2020-04-16 11:05
Well, it works fine on the Azure runners though (and the PR landed now).

**Comment by RalfJung** [comment] 2020-04-16 11:10
But also  #71159 landed in the mean time... but when the Azure runner ran I don't think it had landed already.

**Comment by pietroalbini** [comment] 2020-04-16 12:10
I'm pretty sure that's because GHA is using a fork of the toolstate repository in my own account, and updating the data is still broken. Let's see if it turns green once I update my fork.

**Comment by Mark-Simulacrum** [comment] 2020-04-16 12:12
Ah, yeah, that could explain it. Both the Azure and GHA builds failed the exact same way, just GHA considered that a regression (so it failed, as we're in beta week).

**Comment by pietroalbini** [comment] 2020-04-16 12:13
Updated the fork, let's see if it works now.

**Comment by pietroalbini** [comment] 2020-04-16 12:15
Opened https://github.com/rust-lang/rust/issues/71195 to track master failing.

**Comment by pietroalbini** [comment] 2020-04-17 17:28
After the updated fork this started working again, closing the issue.

**Closed by pietroalbini** 2020-04-17 17:28 UTC
Labels: A-github-actions, T-infra
