### ISSUE TITLE
Test runner filtering does not handle r# based module names (e.g. r#async)

### ISSUE THREAD

**Issue by taladar** [rust-lang/rust#98762] opened 2022-07-01 13:18 UTC
I have some code in my project similar to the following (the r#async part is the same)

```rust
pub mod r#async {
    #[cfg(test)] 
   mod test {
      #[test]
      fn foo_test() {
      }

      fn bar_test() {
      }
   }
}
```

and tried to run a test in this module using the r# based name selectively since the other tests in the project take a long time.

```shell
cargo test crate::r#async::test::foo_test
```

or

```shell
cargo test crate::async::test::foo_test
```

I expected to see this happen: running of 1 test

Instead, this happened: running of 0 tests

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.62.0
LLVM version: 14.0.5
```

**Comment by fmease** [comment] 2024-01-25 14:52
You need to run `cargo test async::test::foo_test` or `cargo test r#async::test_foo_test` (note the lack of `crate::`!) which does successfully pick up on the test.

Closing as works as intended.

**Closed by fmease** 2024-01-25 14:52 UTC
Labels: T-compiler, T-cargo, A-libtest, C-discussion
