### ISSUE TITLE
diagnostics: incorrect, redundant "expected/found" parse error

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#33188] opened 2016-04-25 02:55 UTC
Compiling the following:

``` rust
struct S(pub () ());
```

produces:

```
<anon>:1:17: 1:18 error: expected one of `+` or `,`, found `(`
<anon>:1 struct S(pub () ());
                         ^
<anon>:1:17: 1:18 error: expected one of `+`, `;`, or `where`, found `(`
<anon>:1 struct S(pub () ());
                         ^
```

**Comment by jseyfried** [comment] 2016-04-25 03:01
This is not a regression (it is currently an issue on stable).

**Comment by petrochenkov** [comment] 2016-04-25 08:44
The first one is correct, `()` can be followed by a next field (`struct S(pub (), u8);`) or operand of type sum (`struct S(pub () + Send);`).
The second one looks like it may be caused by some recent efforts on error recovery in parser, but I'm not sure.

**Comment by estebank** [comment] 2017-09-22 01:06
The underlying reason is the same as in https://github.com/rust-lang/rust/issues/44339, and the proposed solution can be generalized to also fix this case.

**Comment by nikomatsakis** [comment] 2017-09-25 17:30
Even though this one is older, I am closing it as a duplicate of https://github.com/rust-lang/rust/issues/44339, which has mentoring instructions.

**Closed by nikomatsakis** 2017-09-25 17:30 UTC
Labels: A-diagnostics, C-enhancement, E-mentor, T-compiler, WG-compiler-const
