### ISSUE TITLE
Tidy error: `src/test/ui` contains over 1418 files

### ISSUE THREAD

**Issue by henryboisdequin** [rust-lang/rust#82722] opened 2021-03-03 15:00 UTC
A directory with over 1418 files is not allowed by tidy. In #82720, the files exceeded the limit of tidy (it's hard coded). And produced this error:

```
tidy check
tidy error: following path contains more than 1418 entries, you should move the test to some relevant subdirectory (current: 1419): /checkout/src/test/ui
Found 435 error codes
Found 0 error codes with no tests
Done!
some tidy checks failed
some tidy checks failed
```

This issue calls for sorting of all strangling files in `src/test/ui`.

@rustbot claim

**Comment by Mark-Simulacrum** [comment] 2021-03-03 15:02
Closing as a duplicate of https://github.com/rust-lang/rust/issues/73494.

**Closed by Mark-Simulacrum** 2021-03-03 15:02 UTC
