### ISSUE TITLE
Performance regressions in nightly btwn nightly-2017-12-25 and nightly-2017-12-26

### ISSUE THREAD

**Issue by lloydmeta** [rust-lang/rust#48155] opened 2018-02-12 06:35 UTC
I *think* this is the right place to report that I am seeing some performance regressions in [Frunk](https://github.com/lloydmeta/frunk), namely in [the benchmark](https://github.com/lloydmeta/frunk/blob/master/benches/labelled.rs) for `LabelledGeneric`-based conversions, where I compare hand-written conversions between structs vs auto `LabelledGeneric`-driven conversions.

I've narrowed it to changes made between `nightly-2017-12-25` and `nightly-2017-12-26`

```rust
$ cargo +nightly-2017-12-25 bench big
running 4 tests
test big_from_24fields           ... bench:         128 ns/iter (+/- 10)
test big_from_25fields           ... bench:         159 ns/iter (+/- 27)
test big_transform_from_24fields ... bench:         136 ns/iter (+/- 68)
test big_transform_from_25fields ... bench:         186 ns/iter (+/- 36)

$ cargo +nightly-2017-12-26 bench big
test big_from_24fields           ... bench:         149 ns/iter (+/- 32)
test big_from_25fields           ... bench:         188 ns/iter (+/- 44)
test big_transform_from_24fields ... bench:       7,631 ns/iter (+/- 3,917)
test big_transform_from_25fields ... bench:       9,162 ns/iter (+/- 4,136)
```

As you can see above, the `LabelledGeneric`-based conversion (`big_transform_from_*`) went from being essentially the same as hand-written to **~70x** the overhead 😢 

Not really sure if it matters how `LabelledGeneric` struct-to-struct transformation works in Frunk, but it essentially gets the compiler to verify that for two given structs, their fields are "compatible" (target struct field names and fields types are a subset of source struct's) and then "just" aligns the generic representation of source to target and dumps one into the other. I say "just" because I still have no idea how Rust managed to make this a zero-overhead op 😆 

The bloody details are available in multipart on my blog ([part 1](https://beachape.com/blog/2017/03/04/labelledgeneric-in-rust-what-why-how/), [part 2](https://beachape.com/blog/2017/03/12/gentle-intro-to-type-level-recursion-in-Rust-from-zero-to-frunk-hlist-sculpting/), [part 3](https://beachape.com/blog/2017/04/12/boilerplate-free-struct-transforms-in-rust/)).

**Comment by alexcrichton** [comment] 2018-02-12 22:12
Thanks for the report! I was able to "fix" the regession by setting `codegen-units = 1`, which means this is probably due to https://github.com/rust-lang/rust/issues/47745

**Comment by Enselic** [comment] 2023-09-26 17:50
Triage: Yes, let's close as duplicate of https://github.com/rust-lang/rust/issues/47745.

**Closed by Enselic** 2023-09-26 17:50 UTC
Labels: I-slow, T-compiler, C-bug
