### ISSUE TITLE
Confusing error message when using traits of different versions

### ISSUE THREAD

**Issue by insanitybit** [rust-lang/rust#35424] opened 2016-08-06 16:56 UTC
E0277:
You tried to use a type which doesn't implement some trait in a place which
expected that trait. [...]

Unfortunately, this is very confusing when you do implement that trait, but the trait you implement is for a different version from what a consumer expects. It would be very helpful if rustc could point this out, something along the lines of "A trait of this name exists/ is implemented for that type, but is of a different version"? 

From: https://www.reddit.com/r/rust/comments/4wg56m/code_wont_compile_says_trait_is_not_implemented/

@jonathandturner

**Comment by TimNN** [comment] 2016-08-06 17:07
I believe this is a duplicate of the original issue described in #22750.

**Comment by insanitybit** [comment] 2016-08-06 18:09
Seems to be, yes.

**Closed** 2016-08-07 00:05 UTC
