### ISSUE TITLE
android standard libraries built in an incompatible way for use with stable rust builds

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust#31393] opened 2016-02-03 20:11 UTC
In https://bugzilla.mozilla.org/show_bug.cgi?id=1220307, I attempted to use a custom-built Rust (hosted on x86-64 Linux, if that makes a difference), built from the 1.6.0 stable branch, with the ARM Android standard libraries available from static.rust-lang.org.  I received [an error message](https://bugzilla.mozilla.org/show_bug.cgi?id=1220307#c9) about incompatible versions.  But AFAICT, the Android standard libraries and the Rust I was using were built from the same revision (c30b771ad), so they ought to have been compatible...?

@alexcrichton [said](https://bugzilla.mozilla.org/show_bug.cgi?id=1220307#c12)

> Oh hm it looks like it's actually just doing a string comparison of the CFG_VERSION values at build-time. This I think includes the version information like 1.6.0 vs nightly. That means that if the android library is configured as built from a nightly compiler at a specific revision it's incompatible with a stable compiler at the same revision (as the version numbers are different). That... may be a bug in our compiler!

It's possible I'm mistaken about how things are supposed to work; filing this as a place to discuss.

**Comment by alexcrichton** [comment] 2016-02-03 21:09
I believe this is because the custom-built Rust probably didn't say `--channel=stable`, so the version is subtly different than the stable branch (e.g. `rust 1.6.0 <hash>` vs `rust 1.6.0-nightly <hash>`)

cc @arielb1, the [currently checked string](https://github.com/rust-lang/rust/blob/8fc73c703ab175577346773ad93de3aa2c3f44a2/src/librustc_metadata/creader.rs#L260) originates from [`CFG_VERSION`](https://github.com/rust-lang/rust/blob/8fc73c703ab175577346773ad93de3aa2c3f44a2/src/librustc_metadata/common.rs#L246-L249), but was there any particular reason to choose this over, say, the [`CFG_VER_HASH`](https://github.com/rust-lang/rust/blob/8fc73c703ab175577346773ad93de3aa2c3f44a2/src/librustc_driver/lib.rs#L532-L535) (e.g. the git commit)? I think that if we only check git commits it'll suffice for "these should link together" and should also prevent a situation like this.

**Comment by Mark-Simulacrum** [comment] 2017-04-29 14:38
Do we want to make the change suggested above and check the `CFG_VER_HASH` instead of `CFG_VERSION`? If so, this seems like an `E-easy` issue; @alexcrichton what do you think?

**Comment by alexcrichton** [comment] 2017-04-29 18:02
Sounds reasonable!

**Comment by Mark-Simulacrum** [comment] 2017-05-03 21:27
Closing as a duplicate of #33286. However, in trying to summarize what needs to be done I realized we don't always have a commit hash on hand (e.g., when building from the source tarballs) so the solution reached here won't quite work I think, and I noted this there.

**Closed by Mark-Simulacrum** 2017-05-03 21:27 UTC
Labels: E-easy
