### ISSUE TITLE
Not all trait implementations are documented

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#42440] opened 2017-06-05 07:12 UTC
When implementing traits with type parameters (with your types) for types outside your crate, these aren't documented anywhere.

For example:

```rust
pub struct A;

impl From<A> for std::io::Error {
    fn from(a: A) -> Self {
        unimplemented!()
    }
}
```

This isn't documented in my crate, and it of course can't be documented in `std`, because `std` doesn't know about my type.

**Comment by QuietMisdreavus** [comment] 2017-09-29 01:03
Duplicate of https://github.com/rust-lang/rust/issues/25264 (at least my understanding of that issue)

**Closed by QuietMisdreavus** 2017-09-29 01:03 UTC
Labels: A-rustdoc, C-bug
