### ISSUE TITLE
Old forks in this GitHub organization

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust#38361] opened 2016-12-14 10:29 UTC
I was looking around at the projects under this GitHub organization, and saw some quite old forks. Are those still needed? Check e.g. https://github.com/rust-lang?page=2

BTW: I don't know for sure what would be the best place to find out more about or report this possible cleanup issue.

**Comment by steveklabnik** [comment] 2016-12-14 17:13
They're not needed to build today's compiler, but if you were going for the full bootstrap, they might be. I'm not totally sure though.

**Comment by est31** [comment] 2016-12-14 20:29
I'm not entirely sure, but if they are moved to https://github.com/rust-lang-deprecated/ , cloning them will still work, right?

**Comment by steveklabnik** [comment] 2016-12-14 20:51
Yes, and that might be a good idea.

**Comment by steveklabnik** [comment] 2016-12-14 23:11
We discussed this at the core team meeting today. As long as this doesn't _lose_ us history, this would be okay. But there's a few things:

1. This ticket as written is not yet actionable. Which specific repos are the problem? That'd need to be spelled out.
2. `rust-lang-deprecated` was intended to be used for things we intended others to take over and possibly keep developing. That doesn't mean that using it as a general sort of "dumping ground" isn't possible, but it'd be a change that we'd need slightly more consideration of.

**Comment by sanxiyn** [comment] 2016-12-15 08:31
To spell out the problem: rust-lang/gyp and rust-lang/libuv are not necessary any more.

**Comment by sanmai-NL** [comment] 2016-12-15 10:50
@steveklabnik: I'm not sure how to determine which repos are safe to (re)move. The two @sanxiyn mentioned appear to me as questionable. What's your policy on keeping (i.e. either not move or remove) old repos? What will happen with [downstream forks](https://github.com/rust-lang/gyp/network/members) once you move a repo?

**Comment by retep998** [comment] 2016-12-15 11:26
@sanmai-NL Downstream forks will continue to exist regardless. If the repo is simply moved, then downstream forks will have the repo's new location set as their "parent". If the repo is removed, another repo is picked to be at the top of the network. If the repo is merely moved, any references to the repo's old location will automatically redirect to the new location, including git. Therefore moving the repo won't break anything as long as github doesn't stop redirecting. Note that repos were already moved in the past, when Rust moved from the mozilla organization to its own rust-lang organization.

**Comment by Mark-Simulacrum** [comment] 2017-05-18 01:23
I'm going to close this -- if someone's motivated, a post on internals is probably the best way to go. Realistically, there's no current place to put these (rust-lang-deprecated doesn't quite fit, though could work), so this isn't really actionable, and no one other than owners can even move these, which is a limited set of people for whom this issue is unlikely to make a difference -- this doesn't have directly actionable steps.

**Closed by Mark-Simulacrum** 2017-05-18 01:23 UTC
Labels: I-cleanup
