### ISSUE TITLE
Investigate post-link optimization via BOLT for improving compiler speed

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#55137] opened 2018-10-17 03:10 UTC
Facebook has written a post-link optimizer called [BOLT](https://github.com/facebookincubator/BOLT). Its purpose is to analyze static binaries and reorder code segments in order to optimize icache utilization.

They have [an experience report on using this tool to optimize binaries of the Clang compiler](https://github.com/facebookincubator/BOLT/blob/master/docs/OptimizingClang.md). For a benchmark of building Clang, BOLT'd Clang binaries were 25% faster, or 12% faster when the Clang binary had first been compiled with LTO and PGO.

They have a paper with more details here: https://arxiv.org/pdf/1807.06735.pdf

The question is whether or not we can apply this tool to rustc. I'm not sure if the compiler binaries we distribute are built with LTO or any form of PGO (how well do we even support that?), and if they aren't then we might hope see a disproportionate benefit from doing so.

According to a developer, there is reason to suspect that it may not take much (any?) work to get it to operate on Rust code: https://github.com/facebookincubator/BOLT/issues/41#issuecomment-430470002 , as long as the code does not "rely on code layout properties, such as function pointer deltas" (I don't know if rustc generates any code that would violate that), and as long as binaries are linked with `--emit-relocs`.

**Comment by ishitatsuyuki** [comment] 2018-10-17 03:54
Duplicate of #50655.

**Comment by Mark-Simulacrum** [comment] 2018-10-17 03:55
(Typed up a comment to this, reposting to that thread)

**Closed by Mark-Simulacrum** 2018-10-17 03:55 UTC
Labels: I-compiletime
