### ISSUE TITLE
Detect git merge conlict markers

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#60151] opened 2019-04-21 13:09 UTC
They could be handled by either stopping with parsing immediately after finding one to prevent meaningless errors or by choosing one side and parse as if the conflict has been resolved by the user by choosing that side.

**Comment by jonas-schievink** [comment] 2019-04-21 13:12
Duplicate of https://github.com/rust-lang/rust/issues/32059

**Comment by bjorn3** [comment] 2019-04-21 13:13
I did search for an already existing one, but couldn't find it.

**Closed by jonas-schievink** 2019-04-21 13:12 UTC
