### ISSUE TITLE
rustup-init.exe was blocked

### ISSUE THREAD

**Issue by mcbrowny35** [rust-lang/rust#79618] opened 2020-12-02 02:16 UTC
It is Rustup-init.exe was blocked, and that it would harm my device. Is this a known issue when trying to install it, and I know rust is safe so what's going on?
![rustsomething](https://user-images.githubusercontent.com/73398125/100819576-7021f600-341a-11eb-8d62-85a77b62827f.PNG)

**Comment by JohnTitor** [comment] 2020-12-02 03:05
Duplicate of #67472 and/or #56815, this topic should not be discussed here but on the rustup repo, see https://github.com/rust-lang/rustup/issues/1568.

**Closed by JohnTitor** 2020-12-02 03:05 UTC
Labels: C-bug

**Comment by mcbrowny35** [comment] 2020-12-02 03:11
Okay thanks.
