### ISSUE TITLE
Add a version dropdown to the docs page

### ISSUE THREAD

**Issue by mathstuf** [rust-lang/rust#48470] opened 2018-02-23 14:41 UTC
Since Rust doesn't track "available since" in its documentation, it'd be nice to be able to switch to the documentation for the version I'm targeting easily. An example can be seen in the [CMake docs](https://cmake.org/cmake/help/latest/) where the dropdown lets you easily switch between documentation versions.

**Comment by pietroalbini** [comment] 2018-02-23 15:51
Duplicate of #44687.

**Closed by pietroalbini** 2018-02-23 15:51 UTC

**Comment by pietroalbini** [comment] 2018-02-23 17:27
Yep, it's mentioned in the [related RFC](https://github.com/rust-lang/rfcs/blob/master/text/1826-change-doc-default-urls.md#detailed-design) :)

**Comment by mathstuf** [comment] 2018-02-23 18:45
Thanks for the pointer :) .
