### ISSUE TITLE
Canonical urls for deduplication of google results in rustdoc

### ISSUE THREAD

**Issue by Seldaek** [rust-lang/rust#9461] opened 2013-09-24 09:11 UTC
When multiple versions of the documentation are available, it tends to pollute google results. As a way to prevent that, it would be good to always have the latest stable release available under /current/, and have all previous versions + the master docs contain canonical links to the current docs like:

```
<link rel="canonical" href="http://.../current/..." />
```

That way it consolidates all results under the current URL which will always be correct, and it also encourages people linking to docs in blog posts and such to use links that will not rot.

/cc @alexcrichton

**Comment by steveklabnik** [comment] 2015-04-20 22:09
Triage: no change.

**Comment by steveklabnik** [comment] 2016-06-27 21:56
Triage: no changes

**Comment by SamWhited** [comment] 2017-01-22 18:43
(sorry for the duplicate; moving relavant link here)

See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Choosing_between_www_and_non-www_URLs#Using_%3Clink_relcanonical%3E

This page from Google's help center [1] appears to suggest that they only use the canonical URL as a hint. While this doesn't explicitly say it, this seems to concur with behavior I've seen in the past where if the page pointed to by the canonical URL is a 404, Google simply uses the old URL (which I suspect is what we want in this case since it makes it easy: point canonical url's to the `/stable` path and if the module is deleted it doesn't really matter). 

[1]: https://support.google.com/webmasters/answer/139066?hl=en#2

**Comment by sanmai-NL** [comment] 2017-03-02 16:52
I would like to re-open discussion on this issue (@steveklabnik, I think you would be the one to ping).

With https://docs.rs/ in place, I think all `rustdoc` documentation for public crates should provide a canonical link to the appropriate documentation there. Why? Search for any popular crate on Google and you get  a litter of confusing, often outdated self-hosted versions of the docs. This may lead the programmer to accidentally study outdated publications of documentation (e.g. when not depending on a specific version of a library), and use and perhaps even bookmark publications that may be partially broken or are not as continuously available as on https://docs.rs/.

Google's former SEO representative has indicated that Google may [disregard](https://www.mattcutts.com/blog/rel-canonical-html-head/) canonical links that result in 404 HTTP response codes. Since Google is by far the most used search engine, and it addressed this issue already in a sensible way, I personally take little issue with the possibility of 404 canonical links.

Here's my logic:

- Only _published_ open-source code has a need for public, search engine accessible documentation of the current kind `rustdoc` produces.
- The only form of ‘publication’ of Rust crate source code that the Rust project supports is via https://crates.io and https://docs.rs/.
- Therefore, if a crate is to be published, it should be published on https://crates.io/ and its docs should be published on https://docs.rs/ and this should be the reference/canonical publication.
- The reference/canonical publication of a crate should suppress other publications (e.g. self-hosted) on search engine results pages for the reasons I gave in my first paragraph.
- Thus, docs for crates can be expected to be published on https://docs.rs, adding a canonical link that claims so is appropriate, and if not, that isn't a blocking issue for the `rustdoc` maintainer(s).

**Comment by steveklabnik** [comment] 2017-03-02 17:12
> I would like to re-open discussion on this issue (@steveklabnik, I think you would be the one to ping).

No need to re-open anything 😄 It's an open issue.

> With https://docs.rs/ in place, I think all rustdoc documentation for public crates should provide a canonical link to the appropriate documentation there

That would be nice, but without some improvements to docs.rs, it's not feasible. There are several people who do extra things to make their docs nicer and explicitly don't want their docs hosted on docs.rs at all.

**Comment by sanmai-NL** [comment] 2017-03-02 18:17
Interesting, could you point me to examples of what those people do?

**Comment by steveklabnik** [comment] 2017-03-02 20:03
I believe @briansmith, @retep998 , and @bluss are three of those people?

**Comment by retep998** [comment] 2017-03-02 20:17
I'm perfectly fine with my docs being hosted on docs.rs. I just haven't actually published a new winapi since docs.rs gained Windows support. There's a few features I'm waiting for like the ability to specify the default target to show docs for and which cargo features to enable. But once that's all set then I'd much rather use docs.rs than have to deal with rustdoc generating a hundred thousand files and then committing them to git and pushing them (which is a *really* slow process).

**Comment by bluss** [comment] 2017-03-04 01:02
@sanmai-NL A crate needs to be compiled to generate its docs, and the dependencies might not be present on docs.rs's builders, nor is there yet any way to indicate what dependencies to use.

My crates they should all have migrated their docs to docs.rs except ndarray. ndarray has lots of optional crate features and I want their items to be visible in the docs (and such items are marked in their doc string). It's not a big thing, but ndarray's docs are therefore technically superiour outside docs.rs. It also has blue boxes for example code, which is obviously nicer to the eye :wink:

And by the way, here's a group of crates where an author has done an amazing job with non-docs.rs docs http://nalgebra.org/

**Comment by sanmai-NL** [comment] 2017-03-06 16:31
Thanks for the comments. I deduce two extra issues. First, https://docs.rs should provide complete documentation and it  should combine well with features and optional dependencies, and it seems not to. Secondly, sometimes https://docs.rs docs should not be the canonical variant anyway. IMO, it should be canonical by default, and this may be overridden with some configuration setting coming with the source tree.

**Comment by bluss** [comment] 2017-03-06 20:59
onur/docs.rs/pull/73 can fix some of these issues

**Comment by sanmai-NL** [comment] 2017-03-07 10:19
The optional configuration setting may be a string that is an URL to the canonical API docs.

**Comment by briansmith** [comment] 2017-03-19 20:36
A while back, I filed https://github.com/onur/docs.rs/issues/74 to have docs.rs include the canonical link, and @onur comitted at least one change towards making that goal happen. 

https://github.com/onur/docs.rs/issues/73 will help a lot with the current main concrete problem with doc.rs. In the meantime I added a note to my documentation: “**IMPORTANT**: If you are reading this on docs.rs or another third-party site, you may not be seeing the complete documentation due to their limitations. Read it at https://briansmith.org/rustdoc/ring/signature/ instead.”

**Comment by skade** [comment] 2017-05-10 13:26
I see the problem that projects may want their official doc pages as the canonical page. Making docs.rs the canonical URL by default might give credit where no credit is due.

A stopgap would be a noindex tag for dependencies (#41882).

**Comment by luser** [comment] 2018-03-01 16:17
The docs.rs stuff feels like a separate discussion that could have its own issue. I think fixing the "every release version on doc.rust-lang.org shows up in Google search results" is a specific thing that's important to fix, and using `<link rel="canonical">` to point at the stable docs sounds like the simplest fix.

**Comment by luser** [comment] 2018-03-01 17:08
After poking around the rustdoc sources a little bit I have a concrete proposal. rustdoc already supports several options on the `#[doc]` attribute to control HTML output, such as `html_favicon_url`:
https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#at-the-crate-level

We should add support for a `html_canonical_base_url` option, and add it to the crates that wind up as part of the `std` documentation like:
`#![doc(html_canonical_base_url = "https://doc.rust-lang.org/stable/")]`

It would be picked up and stored into the `SharedContext` along with the other attributes here:
https://github.com/rust-lang/rust/blob/a85417f5938023d1491b44d94da705f539bb8b17/src/librustdoc/html/render.rs#L532

Callers of `render` would need to pass down the relative URL from the root for a page, possibly as a member of `Page` itself:
https://github.com/rust-lang/rust/blob/a85417f5938023d1491b44d94da705f539bb8b17/src/librustdoc/html/layout.rs#L25

This seems to mostly be useful for `Context::item`, which constructs on-disk paths:
https://github.com/rust-lang/rust/blob/a85417f5938023d1491b44d94da705f539bb8b17/src/librustdoc/html/render.rs#L1478

which calls `Context::render_item`:
https://github.com/rust-lang/rust/blob/a85417f5938023d1491b44d94da705f539bb8b17/src/librustdoc/html/render.rs#L1410

which calls `layout::render`. This might require some variation of `format::href`, which currently generates URLs relative to the current URL in order to generate URLs relative to the base URL:
https://github.com/rust-lang/rust/blob/a85417f5938023d1491b44d94da705f539bb8b17/src/librustdoc/html/format.rs#L393

Then finally, `layout::render` could join the base canonical URL, if present, with the relative URL to the page and include a `<link rel="canonical" href="{canonical_url}">`.

**Comment by steveklabnik** [comment] 2019-03-11 17:09
Triage: there has been some small movement; by now, this issue is getting larger and larger, and is affecting more and more people. I hope to have a plan sometime in the near-ish future; we'l see.

**Comment by pietroalbini** [comment] 2020-09-08 12:27
By the way, the issue with doc.rust-lang.org has been fixed, as we [now have a `robots.txt` in place](https://doc.rust-lang.org/robots.txt).

**Comment by jsha** [comment] 2021-11-30 02:15
I propose closing as a duplicate of https://github.com/rust-lang/docs.rs/issues/1438.

**Comment by workingjubilee** [comment] 2023-03-15 23:39
Closing as this seems fixed/taken on by docs.rs

**Closed by workingjubilee** 2023-03-15 23:39 UTC
Labels: T-rustdoc, C-feature-request
