### ISSUE TITLE
Nightly rustc segfaulting with "!dbg attachment points at wrong subprogram for function"

### ISSUE THREAD

**Issue by sstangl** [rust-lang/rust#56299] opened 2018-11-27 23:07 UTC
Our CI here is failing with rustc Nightly: https://gitlab.com/openpowerlifting/opl-data/-/jobs/126388055. The failure has reproduced across multiple runs.

The first error message is `!dbg attachment points at wrong subprogram for function`.

To reproduce:

1. `git clone https://gitlab.com/openpowerlifting/opl-data.git` (about 100mb or so)
2. `git checkout 77f366f4c48e72c1f7b50a7edd09668b52da3628` (the earliest push that started failing)
3. `cd server`
4. `cargo build`

**Comment by nikic** [comment] 2018-11-27 23:12
This is a duplicate of #56265.

**Closed** 2018-11-28 02:36 UTC
