### ISSUE TITLE
rustc `-Clink-dead-code` causes MSVC linker to produce invalid binaries with 'found invalid metadata files for crate' error

### ISSUE THREAD

**Issue by fadeevab** [rust-lang/rust#92141] opened 2021-12-20 21:38 UTC
**Error**: `error[E0786]: found invalid metadata files for crate ....`
**MSVC**: Visual Studio 2019, Visual Studio 2022.
**RUSTFLAGS**: `"-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off 
-Zpanic_abort_tests -Cpanic=abort"`

The flag `-Clink-dead-code` is used with `-Zprofile` to produce a code coverage using `nightly-msvc` toolchain.

I get the following error on random crates during `cargo build`:

```rust
error[E0786]: found invalid metadata files for crate `serde_derive`
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.118\src\lib.rs:286:1
    |
286 | extern crate serde_derive;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: failed to decompress metadata: \\?\<my local dir>\target\debug\deps\serde_derive-961e5eaa49da36c1.dll   

error[E0432]: unresolved import `ser`
  --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.118\src\de\value.rs:29:5
   |
29 | use ser;
   |     ^^^

Some errors have detailed explanations: E0432, E0786.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `serde` due to 2 previous errors
```

The error is not reproduced with the GNU toolchain.

**Comment by ehuss** [comment] 2022-01-09 22:10
Thanks for the report!  This is a duplicate of #90056, so closing in favor of that.

**Closed by ehuss** 2022-01-09 22:10 UTC
