### ISSUE TITLE
Integer formatting hex/bin ignores padding in alternate form

### ISSUE THREAD

**Issue by MattesWhite** [rust-lang/rust#77139] opened 2020-09-24 08:39 UTC
I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4fd5c86984be029c9001d017d41562e4)):

```rust
fn main() {
    let a = 0x04a9;
    let hex_manual = format!("0x{:04x}", a);
    let hex_pretty = format!("{:#04x}", a);
    let heX_manual = format!("0x{:04X}", a);
    let heX_pretty = format!("{:#04X}", a);
    let bin_manual = format!("0b{:016b}", a);
    let bin_pretty = format!("{:#016b}", a);
    
    println!("\n
hex_manual: {}\n
hex_pretty: {}\n
heX_manual: {}\n
heX_pretty: {}\n
bin_manual: {}\n
bin_pretty: {}\n
", hex_manual, hex_pretty, heX_manual, heX_pretty, bin_manual, bin_pretty);
    
    assert_eq!(hex_manual, hex_pretty);
    assert_eq!(heX_manual, heX_pretty);
    assert_eq!(bin_manual, bin_pretty);
}
```

I expected that each version of `*_manual` and `*_pretty`, i.e. the alternate version, should print the same results.

Instead, the alternate versions ignore the `0`-padding whereas the binary print does the most strange thing.

### Meta

stdout:

```
hex_manual: 0x04a9
hex_pretty: 0x4a9
heX_manual: 0x04A9
heX_pretty: 0x4A9
bin_manual: 0b0000010010101001
bin_pretty: 0b00010010101001
```

**Comment by the8472** [comment] 2022-01-26 20:03
> Instead, the alternate versions ignore the 0-padding whereas the binary print does the most strange thing.

Isn't that because the `0x` prefix is counted towards the length?

**Comment by cassaundra** [comment] 2022-09-13 01:27
Yeah, this seems like intended behavior to me. The width specifier indicates the width of entire format parameter, so you would use `format!("{:#06x}", a)` instead, for example.

**Comment by thomcc** [comment] 2022-09-13 01:29
Yes, this is the reason. It's admittedly a bit odd that the padding counts the `0b` and `0x` despite being on the right-hand side of it, but it's not like we can change it at this point.

**Comment by ChrisDenton** [comment] 2022-10-22 14:30
Closing this as "working as intended". Even though it may not be ideal, it would break too much to change it now.

**Closed by ChrisDenton** 2022-10-22 14:30 UTC
Labels: C-bug, T-libs, A-fmt
