### ISSUE TITLE
3rd party objects missing from nightly-2019-10-12

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#65335] opened 2019-10-12 13:06 UTC
```
$ rustup toolchain add nightly-2019-10-11
$ rustup toolchain add nightly-2019-10-12
$ rustup target add --toolchain nightly-2019-10-11 x86_64-fortanix-unknown-sgx
$ rustup target add --toolchain nightly-2019-10-12 x86_64-fortanix-unknown-sgx
$ ls .rustup/toolchains/nightly-2019-10-11-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-fortanix-unknown-sgx/lib/libunwind.a
.rustup/toolchains/nightly-2019-10-11-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-fortanix-unknown-sgx/lib/libunwind.a
$ ls .rustup/toolchains/nightly-2019-10-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-fortanix-unknown-sgx/lib/libunwind.a
ls: cannot access '.rustup/toolchains/nightly-2019-10-12-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-fortanix-unknown-sgx/lib/libunwind.a': No such file or directory
```

**Comment by jethrogb** [comment] 2019-10-12 13:18
x86_64-unknown-linux-musl is also affected

**Comment by mati865** [comment] 2019-10-12 13:42
I checked `rust-std`, `rustc` and `rustc-dev` components and libs mentioned above are totally gone.

@rustbot modify labels: +T-release +C-bug

**Comment by mati865** [comment] 2019-10-12 13:50
Tier-1 `windows-gnu` toolchain is also broken:
```
  = note: gcc.exe: error: crt2.o: No such file or directory
          gcc.exe: error: rsbegin.o: No such file or directory
          gcc.exe: error: rsend.o: No such file or directory
```

**Comment by pietroalbini** [comment] 2019-10-12 14:05
cc @rust-lang/release

**Comment by pietroalbini** [comment] 2019-10-12 14:11
So @rust-lang/release, as the `rustc-dev` PR broke tons of tier 2 targets and even a tier 1 target, I'd say for now we should revert the change and then land it again once it's properly fixed and tested on most of the platforms we support.

I think the priority should be keeping nightly as usable as possible (thus reverting the PR), reducing the stdlib size is less important and can be done later.

**Comment by cuviper** [comment] 2019-10-12 14:45
> Checkout the size difference:

That was the intent of #68423, but I'm very sorry that I neglected these extra runtime objects. My focus is on `linux-gnu` targets, which don't ship those, so I didn't see the difference.

I'm glad you already have a fix PR!

**Comment by RalfJung** [comment] 2019-10-12 16:10
> Tier-1 windows-gnu toolchain is also broken:

Ah, this probably explains why [Miri CI is failing on Windows](https://ci.appveyor.com/project/rust-lang-libs/miri/builds/28065152/job/si6sl9fmbn2q5bfy) with this change. (Though I think that's using windows-msvc?)

Executing the compiled Miri binary just fails without any stdout/stderr indicating why.

**Comment by pietroalbini** [comment] 2019-10-12 16:11
We're reverting the PR that caused the regression in https://github.com/rust-lang/rust/pull/65342.

**Comment by gnzlbg** [comment] 2019-10-14 08:19
All `libc` musl build jobs are also failing, probably due to this.

**Comment by cuviper** [comment] 2019-10-14 16:36
Revert #65342 landed 15 hours ago, so the next nightly should have the original full rust-std again. We'll retry the limited set later, _with_ any 3rd party objects needed, but first I want to figure out how to sanity-check the dist package in CI for all targets so this doesn't regress.

There is a `distcheck` job, but only for `86_64-unknown-linux-gnu`, which wasn't affected. On Discord we were talking about adding a simple "hello world" test as something quick for all targets.

**Comment by pietroalbini** [comment] 2019-10-15 08:12
This should be fixed in the latest nightly.

**Closed by pietroalbini** 2019-10-15 08:12 UTC
Labels: A-rustbuild, C-bug, I-nominated, O-musl, O-windows-gnu, P-high, T-release, regression-from-stable-to-nightly

**Comment by jethrogb** [comment] 2019-10-15 08:31
Yup it is!
