### ISSUE TITLE
rustc breaks when jemalloc is configured with abort:true,junk:true,redzone:true

### ISSUE THREAD

**Issue by fgsch** [rust-lang/rust#33165] opened 2016-04-23 14:36 UTC
```
$ lsb_release -d
Description:    Debian GNU/Linux testing-updates (sid)

$ dpkg -l | grep Rust
ii  cargo                                 0.8.0-2                              amd64        Rust package manager
ii  libstd-rust-1.8:amd64                 1.8.0+dfsg1-1                        amd64        Rust standard libraries
ii  libstd-rust-dev:amd64                 1.8.0+dfsg1-1                        amd64        Rust standard libraries - development files
ii  rust-gdb                              1.8.0+dfsg1-1                        amd64        Rust debugger (gdb)
ii  rustc                                 1.8.0+dfsg1-1                        amd64        Rust systems programming language

$ rustc -V
rustc 1.8.0
<jemalloc>: Corrupt redzone 1 byte before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 2 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 3 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 4 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 5 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 6 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 7 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 8 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 9 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 10 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 11 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 12 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 13 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 14 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 15 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 16 bytes before 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 0 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 1 byte after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 2 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 3 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 4 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 5 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 6 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 7 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 8 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 9 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 10 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 11 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 12 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 13 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 14 bytes after 0x7feffac50188 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 15 bytes after 0x7feffac50188 (size 8), byte=0x5a
Aborted (core dumped)

$ ls /etc/malloc.conf
lrwxrwxrwx 1 root root 33 Jul  8  2015 /etc/malloc.conf -> abort:true,junk:true,redzone:true
```

Same if I try to compile something:

```
$ rustc a.rs
<jemalloc>: Corrupt redzone 1 byte before 0x7fbf010228b8 (size 8), byte=0x5a
...
Aborted (core dumped)
```

@bluss tested other combinations with similar results so doesn't look like it's Debian specific: 
https://travis-ci.org/bluss/rust-itertools/builds/125225098

**Comment by nagisa** [comment] 2016-04-23 19:24
Can’t seem to reproduce with the `rustc 1.9.0-nightly (177905703 2016-04-08)` built by our buildbots myself.

(configuration as symlink??!)

**Comment by fgsch** [comment] 2016-04-23 21:07
Yes, symlink is one of the ways to do this. The environment and the malloc_conf variable are the others.

**Comment by alexcrichton** [comment] 2016-04-25 16:23
Could you perhaps try to get stack traces for when jemalloc starts deteting violations?

**Comment by fgsch** [comment] 2016-04-25 23:04
Sure, I will try to get them.

**Comment by fgsch** [comment] 2016-04-29 16:05
Sorry for the delay. Here's a trace from compiling rust 1.8.0:

```
rustc: x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore
<jemalloc>: Corrupt redzone 1 byte before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 2 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 3 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 4 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 5 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 6 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 7 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 8 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 9 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 10 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 11 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 12 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 13 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 14 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 15 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 16 bytes before 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 0 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 1 byte after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 2 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 3 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 4 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 5 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 6 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 7 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 8 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 9 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 10 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 11 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 12 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 13 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 14 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
<jemalloc>: Corrupt redzone 15 bytes after 0x7fec47c220e8 (size 8), byte=0x5a
Aborted (core dumped)
...
Reading symbols from x86_64-unknown-linux-gnu/stage0/bin/rustc...done.
[New LWP 24066]
[New LWP 24065]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0 -O --cfg rtopt -C rpath'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fec4947a478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fec48bff700 (LWP 24066))]
(gdb) thread apply all bt full

Thread 2 (Thread 0x7fec4a520a00 (LWP 24065)):
#0  0x00007fec4a1136dd in pthread_join (threadid=140652809549568, thread_return=0x0) at pthread_join.c:90
        __tid = 24066
        _buffer = {__routine = 0x7fec4a113600 <cleanup>, __arg = 0x7fec48bffd28, __canceltype = 0, __prev = 0x0}
        oldtype = 0
        pd = 0x7fec48bff700
        self = 0x7fec4a520a00
        result = 0
#1  0x000056509130762d in run::hd7b71f248f200162ANc ()
No symbol table info available.
#2  0x000056509132e86a in main::h5db63d7a27c2fc7cV1d ()
No symbol table info available.
#3  0x0000565093289945 in sys_common::unwind::try::try_fn::h15027524469598381028 ()
No symbol table info available.
#4  0x0000565093281bdc in __rust_try ()
No symbol table info available.
#5  0x00005650932893cf in rt::lang_start::h5aff6b64d0427d3aSVy ()
No symbol table info available.
#6  0x00007fec49467610 in __libc_start_main (main=0x565091306ca0 <main>, argc=22, argv=0x7fffc6640018, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffc6640008) at libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 7585037566227583536, 94904033241888, 140736521830416, 0, 0, 4187747206431576624, 
                4195881157581935152}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x5650932c6c00 <__libc_csu_init>, 0x7fffc6640018}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = -1825805312}}}
        not_first_call = <optimized out>
#7  0x0000565091306b49 in _start ()
No symbol table info available.

Thread 1 (Thread 0x7fec48bff700 (LWP 24066)):
#0  0x00007fec4947a478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 24065
        selftid = 24066
#1  0x00007fec4947b8fa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x10, sa_sigaction = 0x10}, sa_mask = {__val = {140652792914152, 94904080039280, 
              140652833919088, 2097865012304223517, 2097865012304223517, 2097865012304223517, 2097865012304223517, 2097865012304223517, 
              2097865012304223517, 2097865012304223517, 2097865012304223517, 78, 140652819167977, 78, 140652809519728, 2}}, sa_flags = 4023, 
          sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
---Type <return> to continue, or q <return> to quit---
#2  0x00005650932a2262 in je_arena_dalloc_junk_small ()
No locals.
#3  0x00005650932a40ce in je_arena_dalloc_bin_locked ()
No locals.
#4  0x00005650932b7995 in je_tcache_bin_flush_small ()
No locals.
#5  0x000056509329bd19 in sdallocx ()
No locals.
#6  0x0000565092095fe4 in std..collections..hash..table..RawTable$LT$collections..string..String$C$$u20$collections..vec..Vec$LT$u8$GT$$GT$::drop.8132::hf167d41c14958b9f ()
No symbol table info available.
#7  0x0000565091d9e2c6 in errors..emitter..EmitterWriter::drop.58063::h4a9eae2ebdfd8021 ()
No symbol table info available.
#8  0x0000565091c96684 in syntax..errors..Handler::drop.97877::hb7924b2a4245d3af ()
No symbol table info available.
#9  0x0000565091c973ca in syntax..parse..ParseSess::drop.97917::h94481e3d838729d8 ()
No symbol table info available.
#10 0x0000565091ca22e5 in iter::Map$LT$I$C$$u20$F$GT$.Iterator::next::h163319582608745325 ()
No symbol table info available.
#11 0x0000565091ca1999 in session::config::parse_cfgspecs::h6248adc8f573c6eb92r ()
No symbol table info available.
#12 0x0000565091ca4913 in session::config::build_session_options::hc33dff711bee715ea5r ()
No symbol table info available.
#13 0x000056509130a9b0 in run_compiler::h80bea8dcd0373b56HOc ()
No symbol table info available.
#14 0x0000565091308e12 in sys_common::unwind::try::try_fn::h3467303787998047441 ()
No symbol table info available.
#15 0x0000565093281bdc in __rust_try ()
No symbol table info available.
#16 0x000056509327d85e in sys_common::unwind::inner_try::h8c17dc316bf07366Pit ()
No symbol table info available.
#17 0x0000565091309661 in boxed::F.FnBox$LT$A$GT$::call_box::h3989221639792342286 ()
No symbol table info available.
#18 0x0000565093288b21 in sys::thread::Thread::new::thread_start::hd27008c66fbe3c4560x ()
No symbol table info available.
#19 0x00007fec4a112454 in start_thread (arg=0x7fec48bff700) at pthread_create.c:334
        __res = <optimized out>
        pd = 0x7fec48bff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140652809549568, -4187695495034105296, 0, 140736521827327, 3, 140652809941360, 
                4195877511436767792, 4195882607692943920}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
---Type <return> to continue, or q <return> to quit---
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#20 0x00007fec4952feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

**Comment by fgsch** [comment] 2016-04-30 12:45
And for a simpler test, running rustc -V.
Let me know if you need anything else and/or want me to try something.

```
...
Core was generated by `./rustc -V'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fc2fb8c3478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fc2fafff700 (LWP 20981))]
(gdb) thread apply all bt full

Thread 2 (Thread 0x7fc2fc969a00 (LWP 20980)):
#0  0x00007fc2fc55c6dd in pthread_join (threadid=140475411461888, thread_return=0x0) at pthread_join.c:90
        __tid = 20981
        _buffer = {__routine = 0x7fc2fc55c600 <cleanup>, __arg = 0x7fc2fafffd28, __canceltype = 0, __prev = 0x0}
        oldtype = 0
        pd = 0x7fc2fafff700
        self = 0x7fc2fc969a00
        result = 0
#1  0x0000559ed40df62d in run::hd7b71f248f200162ANc ()
No symbol table info available.
#2  0x0000559ed410686a in main::h5db63d7a27c2fc7cV1d ()
No symbol table info available.
#3  0x0000559ed6061945 in sys_common::unwind::try::try_fn::h15027524469598381028 ()
No symbol table info available.
#4  0x0000559ed6059bdc in __rust_try ()
No symbol table info available.
#5  0x0000559ed60613cf in rt::lang_start::h5aff6b64d0427d3aSVy ()
No symbol table info available.
#6  0x00007fc2fb8b0610 in __libc_start_main (main=0x559ed40deca0 <main>, argc=2, argv=0x7ffccee5af48, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffccee5af38) at libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -6565025173535672052, 94140650875680, 140723779645248, 0, 0, -1143798050367948532, 
                -1127022066127030004}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x559ed609ec00 <__libc_csu_init>, 0x7ffccee5af48}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = -703992832}}}
        not_first_call = <optimized out>
#7  0x0000559ed40deb49 in _start ()
No symbol table info available.

Thread 1 (Thread 0x7fc2fafff700 (LWP 20981)):
#0  0x00007fc2fb8c3478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 20980
        selftid = 20981
#1  0x00007fc2fb8c48fa in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x10, sa_sigaction = 0x10}, sa_mask = {__val = {140475394828912, 94140697673072, 
              140475436130416, 0, 0, 0, 0, 0, 140475438275144, 140475411458944, 140475438124648, 78, 140475421379305, 78, 140475411454352, 2}}, 
          sa_flags = 4023, sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000559ed607a262 in je_arena_dalloc_junk_small ()
No locals.
#3  0x0000559ed607c0ce in je_arena_dalloc_bin_locked ()
No locals.
#4  0x0000559ed6090585 in tcache_destroy ()
No locals.
#5  0x0000559ed6090e22 in je_tcache_cleanup ()
No locals.
#6  0x0000559ed609382d in je_tsd_cleanup ()
No locals.
#7  0x00007fc2fc55a529 in __nptl_deallocate_tsd () at pthread_create.c:176
        data = <optimized out>
        level2 = 0x7fc2fafffa10
        idx = <optimized out>
        round = 0
        cnt = 0
#8  0x00007fc2fc55b608 in __nptl_deallocate_tsd () at pthread_create.c:327
No locals.
#9  start_thread (arg=0x7fc2fafff700) at pthread_create.c:347
        pd = 0x7fc2fafff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140475411461888, 1142212746245880076, 0, 140723779642159, 3, 140475411853392, 
                -1127024092031436532, -1127011669632698100}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
              cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#10 0x00007fc2fb978eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
```

**Comment by fgsch** [comment] 2016-06-06 14:14
fwiw, just updated to rustc 1.9.0 and it's working as expected.

**Comment by Mark-Simulacrum** [comment] 2017-05-04 20:29
Closing since this presumably worked since 1.9.0 per the previous comment.

**Closed by Mark-Simulacrum** 2017-05-04 20:29 UTC
Labels: A-allocators, I-ICE
