### ISSUE TITLE
NLL mode causes ICE (region_obligations not empty)

### ISSUE THREAD

**Issue by danielrh** [rust-lang/rust#51771] opened 2018-06-25 07:32 UTC
The following code fails on nightly, but worked several nightlies ago (perhaps in the ~1.25 era)

```
#![no_std]
#![feature(nll)]

#[cfg(not(feature="no-stdlib"))]
extern crate std;
use core::default::Default;
pub use core::ops::IndexMut;
pub use core::ops::Index;
pub use core::ops::Range;
pub trait SliceWrapper<T> {
    fn slice(& self) -> & [T];
    fn len(&self) -> usize{
        self.slice().len()
    }
}

pub trait SliceWrapperMut<T> : SliceWrapper<T> {
  fn slice_mut (&mut self) -> & mut [T];
}

pub trait AllocatedSlice<T>
    : SliceWrapperMut<T> + SliceWrapper<T> + Default {
}

impl<T, U> AllocatedSlice<T> for U where U : SliceWrapperMut<T> + SliceWrapper<T> + Default {

}


pub struct AllocatedStackMemory<'a, T:'a> {
    pub mem : &'a mut [T],
}

macro_rules! define_index_ops_mut {

    ($T0: ident, $T:ident, $MemoryType:ty) => {
        impl<'a, $T> ::core::ops::Index<usize> for $MemoryType
        {
            type Output = T;

            #[inline]
            fn index(&self, index: usize) -> &Self::Output {
                ::core::ops::Index::index(&**self, index)
            }
        }
        
        impl<'a, $T> ::core::ops::IndexMut<usize> for $MemoryType
        {
            #[inline]
            fn index_mut(&mut self, index: usize) -> &mut Self::Output {
                ::core::ops::IndexMut::index_mut(&mut **self, index)
            }
        }
        
        


        impl<'a, $T> ::core::ops::Deref for $MemoryType {
            type Target = [T];
            
            fn deref(&self) -> &[T] {
                self.slice()
            }
        }
        impl<'a, $T> ::core::ops::DerefMut for $MemoryType {
            fn deref_mut(&mut self) -> &mut [T] {
                self.slice_mut()
            }
        }
    }
}
define_index_ops_mut!(a, T, AllocatedStackMemory<'a, T>);

impl<'a, T: 'a> core::default::Default for AllocatedStackMemory<'a, T> {
    fn default() -> Self {
        return AllocatedStackMemory::<'a, T>{mem : &mut[]};
    }
}


impl<'a, T: 'a> SliceWrapper<T> for AllocatedStackMemory<'a, T> {
    fn slice(& self) -> & [T] {
        return & self.mem;
    }
}

impl<'a, T: 'a> SliceWrapperMut<T> for AllocatedStackMemory<'a, T> {
    fn slice_mut(& mut self) ->& mut [T] {
        return &mut self.mem;
    }
}
```
The command invoked was:
```
$ rustc lib.rs --crate-type lib
thread 'main' panicked at 'region_obligations not empty: [
    (
        NodeId(
            167
        ),
        RegionObligation(sub_region='_#2r, sup_type=T)
    )
]', librustc/infer/mod.rs:1057:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.28.0-nightly (01cc982e9 2018-06-24) running on x86_64-apple-darwin

note: compiler flags: --crate-type lib
```

A standalone crate in the wild that shows the problem is:
https://github.com/dropbox/rust-alloc-no-stdlib/tree/nll

**Comment by danielrh** [comment] 2018-06-25 07:36
Probably a duplicate of https://github.com/rust-lang/rust/issues/51649

**Comment by nikomatsakis** [comment] 2018-07-03 19:03
Closing as duplicate of #51649

**Closed by nikomatsakis** 2018-07-03 19:03 UTC
Labels: A-NLL, I-ICE
