### ISSUE TITLE
Warn when two crates with different versions are in use in the same compilation unit

### ISSUE THREAD

**Issue by pwnorbitals** [rust-lang/rust#102882] opened 2022-10-10 13:03 UTC
I was faced with this error message, saying my `Memory` trait was both not implemented and implemented by the `Flash` type :
 
![image](https://user-images.githubusercontent.com/8146140/194871912-4a838057-9e4f-448e-b6f2-54dd14a1a3f6.png)

This particular issue was caused by having two different versions of the STM32H7 HAL, leading to this confusing and misleading error. 

**Should we consider adding a warning when two different versions of the same crate are in use in a single compilation unit ?**

**Comment by mejrs** [comment] 2022-10-10 15:10
Can you post the full error (from `cargo check`)? This looks like ide output.

**Comment by memoryruins** [comment] 2022-10-10 16:28
Looks like a duplicate of #22750 and/or #89143

**Comment by pwnorbitals** [comment] 2022-10-11 10:59
>  E:\Chris\GNCC\flight_software\GNCC_bootloader_l1>cargo check
>
>     Compiling libcsp-freertos v0.1.0 ([hidden])
>     Checking gncc-drivers v0.1.0 ([hidden])
>     Checking gncc-config v0.1.0 ([hidden])
>     Checking gncc_bootloader_l1 v0.1.0 ([hidden])
> error[E0277]: the trait bound `Flash: Memory` is not satisfied
>    --> src\main.rs:252:19
>     |
> 252 |     active_image: SoftwareImage<Flash>,
>     |                   ^^^^^^^^^^^^^^^^^^^^ the trait `Memory` is not implemented for `Flash`
>     |
>     = help: the following other types implement trait `Memory`:
>               CY15B104Q<SPI, CS, SPIE, CSE>
>               gncc_drivers::memory::nor_flash::NorFlash
>               stm32h7xx_hal::flash::Flash
> note: required by a bound in `SoftwareImage`
>    --> [hidden]/software_image.rs:9:31
>     |
> 9   | pub struct SoftwareImage<MEM: super::Memory> {
>     |                               ^^^^^^^^^^^^^ required by this bound in `SoftwareImage`
> For more information about this error, try `rustc --explain E0277`.
> 
> error: could not compile `gncc_bootloader_l1` due to previous error

**Comment by estebank** [comment] 2024-08-08 19:37
I believe this is fixed by #124944. Without a repro I can't confirm. If this comes up again, please reopen this ticket or open a new one.

**Closed by estebank** 2024-08-08 19:37 UTC
Labels: A-diagnostics, T-compiler, D-crate-version-mismatch
