### ISSUE TITLE
IndexMut

### ISSUE THREAD

**Issue by yzt1q** [rust-lang/rust#72824] opened 2020-05-31 15:56 UTC
This gives an error:

```rust
fn main() {
    let mut vec = vec![1; 3];
    vec[vec.len() - 1] = 2;
}
```

```
error[E0502]: cannot borrow `vec` as immutable because it is also borrowed as mutable
   |
   |     vec[vec.len() - 1] = 2;
   |     ----^^^-----------
   |     |   |
   |     |   immutable borrow occurs here
   |     mutable borrow occurs here
   |     mutable borrow later used here
```

But this gives no error:

```rust
use std::ops::IndexMut;
fn main() {
    let mut vec = vec![1; 3];
    *vec.index_mut(vec.len() - 1) = 2;
}
```

**Comment by Elinvynia** [comment] 2020-05-31 16:19
Related docs: https://doc.rust-lang.org/std/ops/trait.IndexMut.html

Assuming the docs are not the issue here, this should work in my opinion.

**Comment by RustyYato** [comment] 2020-06-04 00:22
This is because two-phased borrows only work with method syntax, maybe we should also allow it for index sugar?

**Comment by jonas-schievink** [comment] 2020-07-14 12:14
Duplicate of https://github.com/rust-lang/rust/issues/58419

**Closed by jonas-schievink** 2020-07-14 12:14 UTC
Labels: A-borrow-checker, C-bug, T-libs
