### ISSUE TITLE
rustdoc only writes one file for multiple items exported as `_`

### ISSUE THREAD

**Issue by SoftwareSheriff** [rust-lang/rust#80056] opened 2020-12-15 17:46 UTC
For example, generating documentation for this code:

```rust
mod traits {
    pub trait TraitA {
        fn a();
    }
    pub trait TraitB {
        fn b();
    }
}

pub use traits::{TraitA as _, TraitB as _};
```

results in two traits named `_`, which is correct, but, no matter which one you click on, you'll only ever see the `a()` xor the `b()` function since rustdoc tries to write the documentation for both traits to the same file. At least, I think that's what's happening.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

**Comment by jyn514** [comment] 2020-12-16 00:57
Duplicate of https://github.com/rust-lang/rust/issues/61592

**Closed by jyn514** 2020-12-16 00:57 UTC
Labels: C-bug, T-rustdoc
