### ISSUE TITLE
ICE when compiling toolshed on nightly

### ISSUE THREAD

**Issue by chris-laplante** [rust-lang/rust#99611] opened 2022-07-22 16:20 UTC
### Code

Just create an empty bin project with this dep in Cargo.toml:

```Rust
[dependencies]
toolshed = "0.8.1"
```

### Meta
This exists on nightly, but not stable or beta.

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (f8588549c 2022-07-18)
binary: rustc
commit-hash: f8588549c3c3d45c32b404210cada01e2a45def3
commit-date: 2022-07-18
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
laplante@laplante-lm-19:/tmp/wat/toolshed_ice$ cargo build
   Compiling toolshed v0.8.1
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: union fields that need dropping should be impossible
  --> /home/laplante/.cargo/registry/src/github.com-1ecc6299db9ec823/toolshed-0.8.1/src/arena.rs:41:13
   |
41 |             self.pointer.value = value;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at compiler/rustc_mir_transform/src/check_unsafety.rs:227:39

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1425:13
stack backtrace:
   0:     0x7fbc7bf69ed0 - std::backtrace_rs::backtrace::libunwind::trace::h6b3f9f41ee650c4f
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fbc7bf69ed0 - std::backtrace_rs::backtrace::trace_unsynchronized::he56cb04310aea81a
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbc7bf69ed0 - std::sys_common::backtrace::_print_fmt::h6d4ec34d6cd34171
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fbc7bf69ed0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h01911f0526d8b05c
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fbc7bfc52ac - core::fmt::write::h49f323f7091ea1c8
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/fmt/mod.rs:1198:17
   5:     0x7fbc7bf5ad85 - std::io::Write::write_fmt::hbf1f476d48d43edd
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/io/mod.rs:1672:15
   6:     0x7fbc7bf6cba1 - std::sys_common::backtrace::_print::h2bbdb393c4180f57
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fbc7bf6cba1 - std::sys_common::backtrace::print::h4200c2a0dbbbc055
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fbc7bf6cba1 - std::panicking::default_hook::{{closure}}::h393b25bd4d38364f
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:295:22
   9:     0x7fbc7bf6c873 - std::panicking::default_hook::h70f1f206e4c542c6
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:314:9
  10:     0x7fbc7aa2e5f1 - <rustc_driver[72308b4096139644]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[cd150e9e29982b29]::ops::function::FnOnce<(&core[cd150e9e29982b29]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7fbc7bf6d3d6 - std::panicking::rust_panic_with_hook::hdfebab2861adaf27
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:702:17
  12:     0x7fbc7ba8b331 - std[778605c8b9d7d939]::panicking::begin_panic::<rustc_errors[5ec552083a70b038]::ExplicitBug>::{closure#0}
  13:     0x7fbc7ba8b106 - std[778605c8b9d7d939]::sys_common::backtrace::__rust_end_short_backtrace::<std[778605c8b9d7d939]::panicking::begin_panic<rustc_errors[5ec552083a70b038]::ExplicitBug>::{closure#0}, !>
  14:     0x7fbc7ba85e46 - std[778605c8b9d7d939]::panicking::begin_panic::<rustc_errors[5ec552083a70b038]::ExplicitBug>
  15:     0x7fbc7ba88466 - std[778605c8b9d7d939]::panic::panic_any::<rustc_errors[5ec552083a70b038]::ExplicitBug>
  16:     0x7fbc7a559413 - <rustc_errors[5ec552083a70b038]::HandlerInner as core[cd150e9e29982b29]::ops::drop::Drop>::drop
  17:     0x7fbc7a127598 - core[cd150e9e29982b29]::ptr::drop_in_place::<rustc_session[b6be1dcf14d2202f]::parse::ParseSess>
  18:     0x7fbc7a111ae3 - <alloc[110eb368cf5d93ca]::rc::Rc<rustc_session[b6be1dcf14d2202f]::session::Session> as core[cd150e9e29982b29]::ops::drop::Drop>::drop
  19:     0x7fbc7a110b5d - core[cd150e9e29982b29]::ptr::drop_in_place::<rustc_interface[8ca32d3d634051a7]::interface::Compiler>
  20:     0x7fbc7a110474 - rustc_span[7c9df871791ece55]::with_source_map::<core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>, rustc_interface[8ca32d3d634051a7]::interface::create_compiler_and_run<core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>, rustc_driver[72308b4096139644]::run_compiler::{closure#1}>::{closure#1}>
  21:     0x7fbc7a10fc90 - rustc_interface[8ca32d3d634051a7]::interface::create_compiler_and_run::<core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>, rustc_driver[72308b4096139644]::run_compiler::{closure#1}>
  22:     0x7fbc7a10e722 - <scoped_tls[3f6da10b6a2c80a0]::ScopedKey<rustc_span[7c9df871791ece55]::SessionGlobals>>::set::<rustc_interface[8ca32d3d634051a7]::interface::run_compiler<core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>, rustc_driver[72308b4096139644]::run_compiler::{closure#1}>::{closure#0}, core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>>
  23:     0x7fbc7a10dbdf - std[778605c8b9d7d939]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8ca32d3d634051a7]::util::run_in_thread_pool_with_globals<rustc_interface[8ca32d3d634051a7]::interface::run_compiler<core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>, rustc_driver[72308b4096139644]::run_compiler::{closure#1}>::{closure#0}, core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>>::{closure#0}, core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>>
  24:     0x7fbc7a84c3e9 - <<std[778605c8b9d7d939]::thread::Builder>::spawn_unchecked_<rustc_interface[8ca32d3d634051a7]::util::run_in_thread_pool_with_globals<rustc_interface[8ca32d3d634051a7]::interface::run_compiler<core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>, rustc_driver[72308b4096139644]::run_compiler::{closure#1}>::{closure#0}, core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>>::{closure#0}, core[cd150e9e29982b29]::result::Result<(), rustc_errors[5ec552083a70b038]::ErrorGuaranteed>>::{closure#1} as core[cd150e9e29982b29]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7fbc7bf77193 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1a098e41f44eb0a6
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/boxed.rs:1935:9
  26:     0x7fbc7bf77193 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc5709f2569386b76
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/alloc/src/boxed.rs:1935:9
  27:     0x7fbc7bf77193 - std::sys::unix::thread::Thread::new::thread_start::h0444ab80c205eb75
                               at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7fbc77c436db - start_thread
                               at /build/glibc-CVJwZb/glibc-2.27/nptl/pthread_create.c:463
  29:     0x7fbc7796c61f - clone
                               at /build/glibc-CVJwZb/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  30:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (f8588549c 2022-07-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `toolshed`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
laplante@laplante-lm-19:/tmp/wat/toolshed_ice$ RUST_BACKTRACE=1 cargo build
   Compiling toolshed v0.8.1
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: union fields that need dropping should be impossible
  --> /home/laplante/.cargo/registry/src/github.com-1ecc6299db9ec823/toolshed-0.8.1/src/arena.rs:41:13
   |
41 |             self.pointer.value = value;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at compiler/rustc_mir_transform/src/check_unsafety.rs:227:39

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1425:13
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   3: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   4: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   6: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
   7: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
   8: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (f8588549c 2022-07-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `toolshed`

```

</p>
</details>

**Comment by ehuss** [comment] 2022-07-22 17:59
Thanks for the report!  This should be fixed in the latest nightly. Closing as a duplicate of #99375.

**Closed by ehuss** 2022-07-22 17:59 UTC
Labels: I-ICE, T-compiler, C-bug
