### ISSUE TITLE
CI: Windows GitHub runner build of rust 1.55.0 - x.py dist --stage 2 - failed to copy

### ISSUE THREAD

**Issue by georgik** [rust-lang/rust#88957] opened 2021-09-15 04:00 UTC
How to simulate:
- on Windows GitHub runner execute `x.py dist --stage 2` on Rust repo with initialized submodules

Failure:
```
Dist rust-docs-1.55.0-dev-x86_64-pc-windows-msvc
	finished in 82.913 seconds
Dist rustc-1.55.0-dev-x86_64-pc-windows-msvc
	finished in 67.779 seconds
Dist rust-std-1.55.0-dev-x86_64-pc-windows-msvc
	finished in 27.514 seconds
Dist rustc-dev-1.55.0-dev-x86_64-pc-windows-msvc
Error: failed to generate installer

Caused by:
    0: failed to copy 'D:\a\rust-build\rust-build\build\tmp\tarball\rustc-dev\x86_64-pc-windows-msvc\image\lib\rustlib\rustc-src\rust\compiler\rustc_codegen_cranelift\patches\0001-compiler-builtins-Disable-128bit-atomic-operations.patch' to 'D:\a\rust-build\rust-build\build\tmp\tarball\rustc-dev\x86_64-pc-windows-msvc\rustc-dev-1.55.0-dev-x86_64-pc-windows-msvc\rustc-dev\lib\rustlib\rustc-src\rust\compiler\rustc_codegen_cranelift\patches\0001-compiler-builtins-Disable-128bit-atomic-operations.patch'
    1: The system cannot find the path specified. (os error 3)


command did not execute successfully: "D:\\a\\rust-build\\rust-build\\build\\x86_64-pc-windows-msvc\\stage0-tools-bin\\fabricate.exe" "generate" "--image-dir" "D:\\a\\rust-build\\rust-build\\build\\tmp\\tarball\\rustc-dev\\x86_64-pc-windows-msvc\\image" "--component-name=rustc-dev" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust" "--success-message=rustc-dev installed." "--package-name=rustc-dev-1.55.0-dev-x86_64-pc-windows-msvc" "--non-installed-overlay" "D:\\a\\rust-build\\rust-build\\build\\tmp\\tarball\\rustc-dev\\x86_64-pc-windows-msvc\\overlay" "--output-dir" "D:\\a\\rust-build\\rust-build\\build\\dist" "--work-dir" "D:\\a\\rust-build\\rust-build\\build\\tmp\\tarball\\rustc-dev\\x86_64-pc-windows-msvc" "--compression-formats" "xz"
expected success, got: exit code: 1
```

Potential root cause:
- problem with too long paths on Windows, similar problem was noticed also with 1.54
- note: the problem occurs even when Long Paths are enabled in Windows registries

Workaround:
- build Rust on local machine in directory with very short path like `d:/r`

Example of failed GitHub action: https://github.com/esp-rs/rust-build/runs/3600031694?check_suite_focus=true#step:6:7814

Example of Workflow: https://github.com/esp-rs/rust-build/blob/main/.github/workflows/build-rust-windows-dispatch.yaml

**Comment by awslabspl** [comment] 2021-09-15 04:56
This shit ( `rustc` ) is doomed.

There are 23k+ super-errors in this so-called package alone..........

**Comment by ehuss** [comment] 2021-09-15 11:52
Thanks for the report, this is a duplicate of #88924, which GitHub claims to have fixed.

**Closed by ehuss** 2021-09-15 11:52 UTC
