### ISSUE TITLE
Cannot build rust on OS X 10.11 public beta

### ISSUE THREAD

**Issue by arynhard** [rust-lang/rust#26971] opened 2015-07-11 16:22 UTC
````
==> ./configure --prefix=/Users/andrewrynhard/develop/homebrew/Cellar/rust/HEAD --disable-rpath --enable-clang --release-channel=nightly
configure: 
configure: note, user-provided CC looks like clang; CC=clang.
configure: 
configure: CFG_USING_CLANG      := 1 
configure: error: bad CLANG version: 7.0.0, need >=3.0svn
````

**Comment by nagisa** [comment] 2015-07-11 16:47
Duplicate of https://github.com/rust-lang/rust/issues/26292

**Closed** 2015-07-11 20:06 UTC
