### ISSUE TITLE
Derives on deprecated items generate deprecation warnings

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#58822] opened 2019-02-28 21:57 UTC
The following code generates a warning on nightly and beta but not on stable:
```rust
#[deprecated = "oh no"]
#[derive(Default)]
struct X;
```

**Comment by Centril** [comment] 2019-02-28 22:00
Hmm; technically generating warnings seems like correct but annoying behavior (which we don't have to fix but probably should...). Putting `#[allow(deprecated)]` on generated impls seems like a solution?

**Comment by joshlf** [comment] 2019-03-01 01:28
This regression also breaks existing code with `#[deny(warnings)]`.

**Comment by nox** [comment] 2019-03-05 16:26
`derive` attributes can only be put on the type but the same people than the ones who control the `deprecated` attribute, so I don't see how that's technically correct. Derives should only ever generate a `deprecated` warning if the trait they derive is deprecated, never because of the type's deprecatedness.

**Comment by asajeffrey** [comment] 2019-03-05 16:30
Just hit this in servo...
```
warning: use of deprecated item 'vr_display_capabilities::VRDisplayCapabilities::presented_by_browser': please use `future_frame_data` instead
 --> /Users/ajeffrey/github/asajeffrey/rust-webvr/rust-webvr-api/src/vr_display_capabilities.rs:3:52
  |
3 | #[cfg_attr(feature = "serde-serialization", derive(Deserialize, Serialize))]
  |                                                    ^^^^^^^^^^^
  |
  = note: #[warn(deprecated)] on by default

warning: use of deprecated item 'vr_display_capabilities::VRDisplayCapabilities::presented_by_browser': please use `future_frame_data` instead
 --> /Users/ajeffrey/github/asajeffrey/rust-webvr/rust-webvr-api/src/vr_display_capabilities.rs:3:52
  |
3 | #[cfg_attr(feature = "serde-serialization", derive(Deserialize, Serialize))]
  |                                                    ^^^^^^^^^^^

warning: use of deprecated item 'vr_display_capabilities::VRDisplayCapabilities::presented_by_browser': please use `future_frame_data` instead
 --> /Users/ajeffrey/github/asajeffrey/rust-webvr/rust-webvr-api/src/vr_display_capabilities.rs:3:65
  |
3 | #[cfg_attr(feature = "serde-serialization", derive(Deserialize, Serialize))]
  |                                                                 ^^^^^^^^^
```
Caused by deprecating a field in a struct.

**Comment by joshlf** [comment] 2019-03-06 03:23
Just hit this in Mundane too. We `#![deny(warnings)]`, so it causes compilation failure.

```
error: use of deprecated item 'hash::InsecureSha1': SHA-1 is considered insecure
   --> src/hash.rs:102:10
    |
102 | #[derive(Default)]
    |          ^^^^^^^
    |
note: lint level defined here
   --> src/lib.rs:45:9
    |
45  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: #[deny(deprecated)] implied by #[deny(warnings)]

error: use of deprecated item 'hash::InsecureSha1': SHA-1 is considered insecure
   --> src/hash.rs:102:10
    |
102 | #[derive(Default)]
    |          ^^^^^^^

error: use of deprecated item 'hash::InsecureSha1': SHA-1 is considered insecure
   --> src/hash.rs:102:10
    |
102 | #[derive(Default)]
    |          ^^^^^^^
    |
note: lint level defined here
   --> src/lib.rs:45:9
    |
45  | #![deny(warnings)]
    |         ^^^^^^^^
    = note: #[deny(deprecated)] implied by #[deny(warnings)]

error: use of deprecated item 'hash::InsecureSha1': SHA-1 is considered insecure
   --> src/hash.rs:102:10
    |
102 | #[derive(Default)]
    |          ^^^^^^^

error: use of deprecated item 'hash::InsecureSha1::ctx': SHA-1 is considered insecure
   --> src/hash.rs:104:5
    |
104 |     ctx: CStackWrapper<boringssl::SHA_CTX>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by pnkfelix** [comment] 2019-03-07 14:46
triage: P-high

**Comment by nikomatsakis** [comment] 2019-03-07 15:42
I'm currently running a bisection with cargo-bisect-rustc.

**Comment by nikomatsakis** [comment] 2019-03-07 15:45
Regression is tracked to c84e7976423bb910bb5eb5eecffc7e33a897a97f

**Comment by pnkfelix** [comment] 2019-03-07 15:55
speculatively assigning to @oli-obk based on @nikomatsakis 's bisection.

**Comment by oli-obk** [comment] 2019-03-07 16:05
This is definitely caused by [this change](https://github.com/rust-lang/rust/pull/58098/files#diff-fe6fbe1c488f33762a812dfee7e5e919L564). We used to just not emit deprecation warnings inside `allow_internal_unstable` code. I'll extend derives to add `#[allow(deprecated)]` to replicate the previous behaviour, but we should probably create something more fine grained some day.

**Closed** 2019-03-17 23:51 UTC
Labels: A-lint, E-needs-bisection, P-high, T-compiler, regression-from-stable-to-beta
