### ISSUE TITLE
Dead link in rustc-nightly documentation

### ISSUE THREAD

**Issue by robinmoussu** [rust-lang/rust#79258] opened 2020-11-21 10:44 UTC
If you search for [`rustc_middle::ty::relate`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.Const.html?search=rustc_middle%3A%3Aty%3A%3Arelate), you will find a green item `rustc_middle::ty::relate`. That item points to a [dead link](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/type.Ty.html#method.relate).

I have no idea why this link is in the list. I'm not familiar enough with the rustc codebase to know if this item exists, and if yes what should be the correct link.

The only idea I have is that `rustc_middle::ty::Ty` is a public re-export of [`rustc_middle::ty::Tys`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/type.Ty.html)

**Comment by jyn514** [comment] 2020-11-21 13:56
Duplicate of https://github.com/rust-lang/rust/issues/78724

**Closed by jyn514** 2020-11-21 13:56 UTC
Labels: C-bug, T-rustdoc
