### ISSUE TITLE
Bad error when Rust's type inference fails

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#43378] opened 2017-07-21 05:37 UTC
https://play.rust-lang.org/?gist=715a11a60b064752776a9bb838845cb1&version=stable

It just kinda tells you that it can't figure out the type; it should probably say why.

note: this is obviously a contrived example, but I've run into it personally when using HashMap.

**Comment by Mark-Simulacrum** [comment] 2017-07-21 15:23
Duplicate of other issues too, but at least the first I found: https://github.com/rust-lang/rust/issues/41261. Thanks for filing, though!

**Closed by Mark-Simulacrum** 2017-07-21 15:23 UTC
