### ISSUE TITLE
tidy is not good at detecting untracked files

### ISSUE THREAD

**Issue by robinmoussu** [rust-lang/rust#78815] opened 2020-11-06 19:20 UTC
When running `x.py test`, I got a bazillion errors (434 to be more precise). I think that all those errors comes from `.js` files. Most (all?) of them being:

> missing trailing newline
> line longer than 100 chars

Is this "expected"? Because of those errors, the command finishes with an error code (exit code: `1`).

**Comment by jyn514** [comment] 2020-11-06 19:25
@robinmoussu that's from `tidy` - do you have untracked files maybe? tidy tries to avoid untracked files but it's not very good at it.

**Comment by robinmoussu** [comment] 2020-11-06 19:39
I was effectively that. I generated the doc for `rustc_parse` and `rustc_lexer` by running `cargo doc` directly in those folder. Even a cargo clean didn't clear the `target` directory, and I didn't noticed it.

**Comment by arora-aman** [comment] 2020-11-10 07:12
Duplicate of #75582

**Closed** 2020-11-10 12:14 UTC
Labels: A-contributor-roadblock, A-rustbuild, A-testsuite, C-enhancement
