### ISSUE TITLE
async fn inside fn fails to parse

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#51933] opened 2018-06-30 01:38 UTC
This fails to parse: `fn foo() { async fn bar() { } }`.

**Comment by memoryruins** [comment] 2018-06-30 16:28
Other variants:

```rust
async fn foo() { async fn bar() {} }
```

```rust
let inside_closure = || { async fn bar() {} };
```

```rust
let async_closure = async || {};
```

**Comment by memoryruins** [comment] 2018-06-30 20:44
All of these examples, including your original example, parse without an issue with the new 2018 edition option enabled on the playground.

**Comment by nikomatsakis** [comment] 2019-02-22 16:26
Closing as duplicate of #58652

**Closed by nikomatsakis** 2019-02-22 16:26 UTC
Labels: A-async-await, A-parser, C-bug, T-compiler
