### ISSUE TITLE
ICE: assertion failure in LLVM when returning a struct from "extern" function.

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#21454] opened 2015-01-21 04:21 UTC
Repro:
```rust
#[repr(C)]
pub struct Foo(u32);

pub extern fn bar() -> Foo {
    Foo(0)
}

fn main() {}
```
ICE:
```
File: C:/rust/src/llvm/lib/IR/Instructions.cpp, Line 1086

Expression: getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"
```

**Comment by skade** [comment] 2015-01-22 08:08
#17257 tracks a number of cases that throw the same error.

**Comment by vhbit** [comment] 2015-02-02 08:38
A couple of hints - it looks like it happens when structure size is actually smaller or equal to register of architecture. 

I had the similar report for failing on iOS with the following sample:
```
#![crate_type = "staticlib"]

#[derive(Copy)]
pub struct Pair {
    foo: u32,
    bar: u32,
}

#[no_mangle]
pub extern fn get_pair() -> Pair {
    Pair {
        foo: 42,
        bar: 10,
    }
}
```
It fails on `x86_64` and `aarch64` if `foo` + `bar` <= 64 bits, i.e. they are u16 or u32.
When switching to armv7 it fails if `foo` + `bar`<= 32 bits

**Comment by vhbit** [comment] 2015-02-02 14:47
@dotdash @Aatch after 6 hours bisecting the verdict is - 6ef08406dccdeeb828a6cfc7658ac149900e73ad, part of #20755

**Comment by dotdash** [comment] 2015-02-02 15:18
*sigh* I actually saw that when I was working on #20755 but didn't come up with a test case that would trigger a problem here and then forgot about it. Will look into this.

**Comment by vhbit** [comment] 2015-02-09 09:52
@dotdash will fix hit the upcoming beta?

**Comment by dotdash** [comment] 2015-02-09 09:57
Sorry, fixing a few regressions in LLVM that affected rust had higher priority for me than this issue (because LLVM is very close to its 3.6 release), so I couldn't devote much time to this issue yet.

But given that the beta is still ~3 weeks away, I'm positive that I'll get around to have it fixed by then.

**Comment by vhbit** [comment] 2015-02-09 09:58
Hmm, beta is on week of Feb 16, isn't it?

**Comment by skade** [comment] 2015-02-09 12:31
@vhbit Yes. http://blog.rust-lang.org/2014/12/12/1.0-Timeline.html

Although, as someone hitting that bug, I'd be okay if that were flagged as a known bug and would prefer if semantic issues were cared about first.

**Comment by vhbit** [comment] 2015-02-09 13:27
@skade @dotdash I have nothing against fixing regressions, still would like to see it fixed as I will be stuck on beta1 following 6 weeks till beta2 or rc1.

**Closed** 2015-02-11 03:15 UTC
Labels: A-codegen, I-ICE

**Comment by vhbit** [comment] 2015-02-11 06:59
@dotdash :tada: thanks a lot!
