### ISSUE TITLE
Link fails with actix-web when using GNU linker's default linker script

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/rust#75385] opened 2020-08-11 05:05 UTC
This code:
```rust
use actix_files::Files;
use actix_web::App;
fn main() {
    let _ = App::new().service(Files::new("/server", "/"));
}
```
fails to link on stable and nightly, with the error:
```
  = note: /home/roc/relocation-test/target/debug/deps/libactix_http-985964f86ff2d013.rlib(actix_http-985964f86ff2d013.actix_http.4hj7mioh-cgu.10.rcgu.o): in function `<core::slice::Iter<T> as core::iter::traits::iterator::Iterator>::next':
          /home/roc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:3179:(.text._ZN4time6format5parse5parse17hb3b97d77f0786e39E+0x50c3): relocation truncated to fit: R_X86_64_PC32 against `.rodata..Lanon.d2b4ff292dcde58115d76259b596ed15.85'
          collect2: error: ld returned 1 exit status
```
Stable 1.45.2, nightly 1.47.0-nightly (6c8927b0c 2020-07-26). This happens when using GNU ld 2.32-31.fc31 (Fedora). It does not happen with Fedora's LLD 9.0.1. It *does* happen if I run `/usr/bin/ld.bfd --verbose`, extract the linker script, and run with `RUSTFLAGS="-C link-arg=-Wl,-Tlinker-script"`. This only affects debug builds, not release builds, and only when I use
```
[profile.dev.package."*"]
opt-level = 2
```
in `Cargo.toml`.

Test repo: https://github.com/rocallahan/relocation-test

**Comment by rocallahan** [comment] 2020-08-11 05:06
The offending relocation does look rather unusual:
```
00000000000050c3 R_X86_64_PC32     .rodata..Lanon.d2b4ff292dcde58115d76259b596ed15.85+0x000000007ffffffa
```
Adding 2^31 minus a bit to a symbol location does seem like it could easily overflow the signed 32-bit RIP displacement.

**Comment by rocallahan** [comment] 2020-08-11 05:14
Building with 1.44.0 works, so this is a recent regression.

**Comment by petrochenkov** [comment] 2020-08-11 06:01
Does this reproduce with `-C code-model=medium` or `-C code-model=large`?

**Comment by rocallahan** [comment] 2020-08-11 06:38
`-C code-model=medium` does not build at all.
```
[roc@localhost relocation-test]$ RUSTFLAGS="-C code-model=medium" cargo build
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling libc v0.2.74
   Compiling syn v1.0.38
   Compiling cfg-if v0.1.10
   Compiling memchr v2.3.3
   Compiling version_check v0.9.2
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.2
   Compiling futures-core v0.3.5
   Compiling bytes v0.5.6
   Compiling proc-macro-hack v0.5.18
   Compiling futures-sink v0.3.5
   Compiling pin-project-internal v0.4.23
error: could not compile `futures-core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name futures_core --edition=2018 /home/roc/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -Cembed-bitcode=no -C debuginfo=2 -C debug-assertions=on --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=f2a9c760bbf5398e -C extra-filename=-f2a9c760bbf5398e --out-dir /home/roc/relocation-test/target/debug/deps -L dependency=/home/roc/relocation-test/target/debug/deps --cap-lints allow -C code-model=medium` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by rocallahan** [comment] 2020-08-11 06:42
Same thing happens with nightly.

**Comment by rocallahan** [comment] 2020-08-11 06:46
`-C code-model=large` works fine on stable.

**Comment by spastorino** [comment] 2020-08-12 14:30
Assigning `P-high` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2375385.20Link.20fails.20with.20actix-web.20when.20using.20GN.E2.80.A6) and removing `I-prioritize`.

**Comment by rocallahan** [comment] 2020-08-30 01:45
`-C code-model=large` does not always work unfortunately :-(.

**Comment by pnkfelix** [comment] 2022-12-16 16:04
@wesleywiser have you had any time to look at this? Should we reassign?

**Comment by jieyouxu** [comment] 2024-11-22 15:51
Visited during [T-compiler P-high review](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202024-11-22.20P-high.20review/near/483936778): the provided example *seems* to build, can't reproduce on latest stable.

Closing this issue, but please open a new issue if this is still problematic. Thanks for the report!

**Closed by jieyouxu** 2024-11-22 15:51 UTC
Labels: A-linkage, O-linux, P-high, T-compiler, regression-from-stable-to-stable, C-bug, A-linkers
