### ISSUE TITLE
Internal compiler error caused by generics and closure to fn pointer coercion

### ISSUE THREAD

**Issue by kriomant** [rust-lang/rust#42718] opened 2017-06-17 17:23 UTC
Following code causes internal compiler error on nighly:

```rust
pub struct A<T> {
    _item: T,
}
impl<T> A<T> {
    fn foo(&self) {
        let _: fn() = || {};
    }
}

fn main() {
    let a = A::<i32> { _item: 0 };
    a.foo();
}
```

Error:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.19.0-nightly (fe7227f6c 2017-06-16) running on x86_64-apple-darwin

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'substs of instance DefId { krate: CrateNum(0), node: DefIndex(2147483661) => associated_types/32d60c5::{{impl}}[0]::create[0]::{{closure}}[0] } not normalized for trans: Slice([T])', src/librustc/ty/instance.rs:112
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rustc::ty::instance::Instance::new
   7: rustc_trans::monomorphize::resolve_closure
   8: rustc_trans::monomorphize::resolve
   9: <rustc_trans::collector::MirNeighborCollector<'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_terminator_kind
  10: rustc::mir::visit::Visitor::visit_mir
  11: rustc_trans::collector::collect_items_rec
  12: rustc_trans::collector::collect_items_rec
  13: rustc_trans::collector::collect_items_rec
  14: rustc_trans::base::collect_and_partition_translation_items::{{closure}}
  15: rustc_trans::base::trans_crate
  16: rustc_driver::driver::phase_4_translate_to_llvm
  17: rustc_driver::driver::compile_input::{{closure}}
  18: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  19: rustc_driver::driver::phase_3_run_analysis_passes
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler
```

**Comment by est31** [comment] 2017-06-17 17:30
Also occurs on beta.

**Comment by Mark-Simulacrum** [comment] 2017-06-17 17:40
The regression here is only that this doesn't ICE on stable, presumably because the relevant code isn't reached. Still a regression once it goes through the trains, though.

**Comment by est31** [comment] 2017-06-17 17:43
@Mark-Simulacrum yeah its an ICE related to the freshly stabilized closure to fn coercion feature.

**Comment by est31** [comment] 2017-06-17 18:23
Smaller reproducing example:

```rust
fn foo<T>(_: T) {
    let _: fn() = || {};
}

fn main() {
    foo(0i8);
}
```

**Comment by est31** [comment] 2017-06-17 18:45
Hmm apparently the `TypeFlags::HAS_PARAMS` flag is still set (all other flags are not). No idea what that means though. Similar issue #36381 got fixed by making the check less strict.

**Comment by eddyb** [comment] 2017-06-18 13:29
@est31 Well that's a consequence of there being type parameters. And it's in the ICE message.
So the immediate conclusion is that parameters were not substituted correctly at some point.

Specifically, [this operation](https://github.com/rust-lang/rust/blob/78d8416caf65cfb50de61bb9423e9efa026bd45a/src/librustc_trans/collector.rs#L490-L491) is missing for [`source_ty` below](https://github.com/rust-lang/rust/blob/78d8416caf65cfb50de61bb9423e9efa026bd45a/src/librustc_trans/collector.rs#L495) it, for `ClosureFnPointer`.

**Closed** 2017-06-19 01:31 UTC
Labels: I-ICE, regression-from-stable-to-beta, T-compiler
