### ISSUE TITLE
Missing `Methods from Deref<Target={primitive}>` section in documentation for types in `#![no_std]` crates

### ISSUE THREAD

**Issue by mitaa** [rust-lang/rust#32553] opened 2016-03-28 14:29 UTC
The links to [`as_ptr`](https://doc.rust-lang.org/nightly/collections/string/struct.String.html#representation) and [`chars`](https://doc.rust-lang.org/nightly/collections/string/struct.String.html#utf-8) on the collection crates page of String are broken.

This is because they refer to methods of [`str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) but link to the same page (`String`), relying on the [`Methods from Deref<Target=str>`](https://doc.rust-lang.org/nightly/std/string/struct.String.html#deref-methods) section which is missing for some reason (seems to apply to the entire [`collections`](https://doc.rust-lang.org/nightly/collections/index.html) crate).

**Comment by steveklabnik** [comment] 2016-09-16 13:03
This is a duplicate of https://github.com/rust-lang/rust/issues/32129

**Comment by ollie27** [comment] 2017-03-22 19:05
This isn't a dupe of #32129. The issue here is the lack of the [`Methods from Deref<Target=str>`](https://doc.rust-lang.org/nightly/std/string/struct.String.html#deref-methods) section on the [`collections::string::String`](https://doc.rust-lang.org/nightly/collections/string/struct.String.html) page which I believe is because it's a `#![no_std]` crate. So this needs to be reopened.

**Comment by MaloJaffre** [comment] 2017-12-28 20:24
`collections` crate was removed (#45446), so here is a new reduced testcase:
```rust
#![no_std]
pub struct DeStr;
impl core::ops::Deref for DeStr {
    type Target = str;
    fn deref(&self) -> &str {
        unimplemented!()
    }
}

```

**Comment by jyn514** [comment] 2020-07-18 22:03
This looks like a duplicate of #73423.

**Comment by Nemo157** [comment] 2020-08-17 07:52
`no_std` doesn't seem relevant, removing it from the reduced testcase still fails to add a "Mtehods from Deref<Target = str>" section (though it does create a broken link to it in the sidebar).

**Comment by jyn514** [comment] 2021-04-08 18:27
This is fixed on master: 
![image](https://user-images.githubusercontent.com/23638587/114078083-7fa4c600-9876-11eb-877f-0cea42b9a9ef.png)

**Closed by jyn514** 2021-04-08 18:27 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
