### ISSUE TITLE
Maybe incorrect parsing of doc tests

### ISSUE THREAD

**Issue by frank-king** [rust-lang/rust#99041] opened 2022-07-08 04:07 UTC
Here is a fragment from some bindgen-generated code:

```rust
#[doc = "**"]
#[doc = "* <hr>"]
#[doc = "* ------------------ | -------------"]
#[doc = "*                    | Yes, "]
#[doc = "*/"]
pub struct Foo;
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4889086001ed72201de53fc29d6e3ccd).

I expected to see this happen: *when running `cargo test`, there is no tests to execute*.

Instead, this happened:
```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test src/lib.rs - Foo (line 4) ... FAILED

failures:

---- src/lib.rs - Foo (line 4) stdout ----
error: expected parameter name, found `}`
 --> src/lib.rs:6:1
  |
4 | } _doctest_main_src_lib_rs_4_0() }
  | ^ expected parameter name

error: aborting due to previous error

Couldn't compile the test.

failures:
    src/lib.rs - Foo (line 4)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s
```

Acutally, it is caused by this line,
```
#[doc = "*                    | Yes, "]
```
If removing it, then there is no doc tests.

It happens on both stable version and nightly version.

**Comment by ehuss** [comment] 2022-07-08 04:45
I think this is expected behavior.

The line `*                    | Yes, ` is rendered in markdown as a bullet list with an indented code block. All code blocks default to the "rust" language in rustdoc, and all rust codeblocks are tested by default.

There are several issues about this, such as #63193 for adding a control over that, and #88590 for providing better error messages.

**Comment by frank-king** [comment] 2022-07-08 06:33
Are there any ways to ignore all the doc tests in a mod? Like `#[cfg_attr(doctest, ignore)]` (I have tried, but it didn't work).

**Comment by ehuss** [comment] 2022-07-08 14:31
Sorry, I don't know of any workarounds other than disabling comments in bindgen or blocklisting the offending items.

**Comment by frank-king** [comment] 2022-07-09 02:31
Sigh. I think I'd better manully edit the generated code to pass the tests.

**Comment by GuillaumeGomez** [comment] 2022-07-21 09:32
You can wrap it into a code block like this:

``````
```text
you comment.
```
``````

Since it's not a bug, closing this issue.

**Closed by GuillaumeGomez** 2022-07-21 09:32 UTC
Labels: C-bug
