### ISSUE TITLE
Obscure compiler panic with async/await

### ISSUE THREAD

**Issue by thomhuds** [rust-lang/rust#56651] opened 2018-12-09 18:35 UTC
My code can be found [here](https://gitlab.com/thomhuds/acacia). While building, the compiler panics with
`src/librustc/infer/region_constraints/mod.rs:683: cannot relate bound region: ReLateBound(DebruijnIndex(1), BrAnon(2)) <= '_#0r`

I would give a short extract of the code but it's hard to isolate the problem, however I can say that it arises in `acacia::je_net::handle_client` only when calling `await!(receive_msg(socket_read))`, including after annotating the type of this expression.

Full error message:
```
error: internal compiler error: src/librustc/infer/region_constraints/mod.rs:683: cannot relate bound region: ReLateBound(DebruijnIndex(1), BrAnon(2)) <= '_#0r

thread 'main' panicked at 'Box<Any>', src/librustc_errors/lib.rs:538:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (4a45578bc 2018-12-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `acacia`.
```

**Comment by jonas-schievink** [comment] 2018-12-13 14:34
possibly a duplicate of https://github.com/rust-lang/rust/issues/53989

**Comment by lqd** [comment] 2019-02-22 20:12
Note: this depends on the tokio `async-await-preview` feature which currently doesn't build on nightly anymore (until at least https://github.com/tokio-rs/tokio/pull/919 or similar is merged)

**Comment by lqd** [comment] 2019-02-26 12:21
Now that a new `tokio-async-await` has been released, I've retested the `acacia` repo on the latest nightly and it builds correctly: this ICE looks fixed (like a few other ones I've retested recently).

**Comment by jonas-schievink** [comment] 2019-02-26 12:34
I'll close this in favor of https://github.com/rust-lang/rust/issues/57084 then, which contains a small playground example that would make a nice test case

**Closed by jonas-schievink** 2019-02-26 12:34 UTC
Labels: A-async-await, I-ICE
