### ISSUE TITLE
Rust stable, macro bomb

### ISSUE THREAD

**Issue by denisandroid** [rust-lang/rust#58823] opened 2019-02-28 22:25 UTC
**Rust:**
rustc 1.34.0-nightly (097c04cf4 2019-02-24)
rustc 1.33.0 (2aa4c46cf 2019-02-28)

**PlayGround:**
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=14643a4834e5ae92f13e1a1de5c5becb

(**OUT**) https://pastebin.com/Bv13Lf0M (signal: 9, SIGKILL: kill)

**Eng:**
Accidentally identified "macro bomb".
It completely clogs the computer's RAM, even on a stable version of Rust and when using RLS.

No warnings or errors.

PlayGround does not even work on a stable version (output is attached), please solve the problem.

**Ru:**
Случайно выявлена "macro bomb".
Забивает полностью ОЗУ компьютера, даже на стабильной версии Rust и при использовании RLS.

Никаких варнингов или ошибок.

Не отрабатывает PlayGround даже на стабильной версии (вывод прилагается), просьба решить проблему.

**Comment by jonas-schievink** [comment] 2019-02-28 22:45
The second macro arm puts `@RAW;` between each *token* of the input, so the first arm is never actually reached (you can remove it). This means that for every expansion of the second arm, the number of tokens is multiplied by 4. The recursion limit doesn't help in this case before the memory usage grows exponentially.

This also looks like a duplicate of https://github.com/rust-lang/rust/issues/51754, so closing in favor of that.

**Closed by jonas-schievink** 2019-02-28 22:45 UTC
