### ISSUE TITLE
rustc cannot see impls for other lifetimes in presence of specific where clause

### ISSUE THREAD

**Issue by djzin** [rust-lang/rust#38308] opened 2016-12-11 20:35 UTC
The following code fails to compile:

```rust
trait Foo {
    fn foo(&self) {}
}

fn fail<'a>() where &'a (): Foo {
    (&()).foo()
}

impl<'a> Foo for &'a () {}

fn main() {}
```

The temporary `&()` is deduced to have type `&'a ()` because of the where clause. If this where clause is removed, the code compiles. For some reason the compiler cannot see that `&()` still implements `Foo` for other lifetimes because of this where clause.

n.b. this came from reducing this reddit post
https://www.reddit.com/r/rust/comments/5hm2b6/my_lifetime_snafu/

**Comment by bluss** [comment] 2016-12-11 20:51
This looks like a duplicate of #38071

**Comment by rkruppe** [comment] 2016-12-11 22:00
I'm not sure if #38071 is a duplicate of #24066 but *this* definitely is a duplicate of #24066.

**Comment by Mark-Simulacrum** [comment] 2017-05-04 18:09
Closing in favor of #38071, which may be a duplicate of #24066, but since we're uncertain not closing both--these two issues (this and #38071) are highly likely to be identical, though.

**Closed by Mark-Simulacrum** 2017-05-04 18:09 UTC
Labels: A-traits
