### ISSUE TITLE
rustc warnings on armv7: '-d16' is not a recognized feature for this target (ignoring feature)

### ISSUE THREAD

**Issue by stefson** [rust-lang/rust#85364] opened 2021-05-16 11:05 UTC
hello everyone, 

I got around 2600 of these rustc warnings when compiling firefox on armv7 with neon+thumb:

```
1:02.59 '-d16' is not a recognized feature for this target (ignoring feature)
```
cargo was initially invoked with ` target_feature=+neon,-d16` as in: 

``
' CARGO_PKG_HOMEPAGE='https://github.com/alexcrichton/cfg-if' CARGO_PKG_LICENSE=MIT/Apache-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=cfg-if CARGO_PKG_REPOSITORY='https://github.com/alexcrichton/cfg-if' CARGO_PKG_VERSION=0.1.10 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=10 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox_build/release/deps:/usr/lib' /usr/bin/rustc --crate-name cfg_if --edition=2018 /usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox-90.0/third_party/rust/cfg-if-0.1.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C panic=abort -C embed-bitcode=no -C metadata=f10b9f12f0edf0f0 -C extra-filename=-f10b9f12f0edf0f0 --out-dir /usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox_build/thumbv7neon-unknown-linux-gnueabihf/release/deps --target thumbv7neon-unknown-linux-gnueabihf -C linker=/usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox-90.0/build/cargo-linker -L dependency=/usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox_build/thumbv7neon-unknown-linux-gnueabihf/release/deps -L dependency=/usr/armv7a-unknown-linux-gnueabihf/tmp/portage/www-client/firefox-90.0/work/firefox_build/release/deps --cap-lints warn -C force-frame-pointers=yes --cap-lints warn -C target_feature=+neon,-d16 -Cembed-bitcode=yes -C codegen-units=1` '
``

I'm using thumbv7neon-unknown-linux-gnueabihf std to compile, and my rustc is v1.51.0 

Not sure what this feature is, and why there is a warning issued, but everthing seems to work as expected.

**Comment by jonas-schievink** [comment] 2021-05-16 12:54
Is this a regression or does this happen on all supported Rust versions? Why is Firefox trying to turn off the `d16` feature?

**Comment by jonas-schievink** [comment] 2021-05-16 13:27
> Code-generation features cannot be used in cfg or #[target_feature],
> and may be renamed or removed in a future version of LLVM or rustc.

Since these don't have stability guarantees, closing this as not-a-bug.

**Closed by jonas-schievink** 2021-05-16 13:27 UTC
Labels: C-bug

**Comment by stefson** [comment] 2021-05-16 13:59
do you think this is a bug in how firefox does config its code-generation?

**Comment by jonas-schievink** [comment] 2021-05-16 14:05
yes, it needs to stop disabling the `d16` feature

**Comment by stefson** [comment] 2021-05-16 14:47
thanks for the clarification, I'll talk with the mozilla devs about this. 

(Its fallout from moz 1557229)

**Comment by stefson** [comment] 2021-05-28 12:14
fixed in upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1712947
