### ISSUE TITLE
Format string can't contain "<{var:}>"

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#68707] opened 2020-01-31 17:12 UTC
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7ce4bc1f30fade52a6c0b177d8b7e2da

```rust
fn main() {
    let c = "hello";
    println!("{ch:}", ch = c);
    println!("<{ch}>", ch = c);
    println!("<{ch:}>", ch = c);
}
```

This gives a formatting error on the 3rd line for unclear reasons. The playground link is for Nightly but this also appears to be a bug with Stable.

**Comment by dtolnay** [comment] 2020-01-31 18:44
Looks like the bug relates to an alignment character after `:}`. The following all trigger it: `"{ch:}<"`, `"{ch:}>"`, `"{ch:}^"`.

**Comment by sfackler** [comment] 2020-01-31 19:52
The `}` after the `:` is treated as the fill character, not as closing the format directive. `<{ch:}>}` compiles successfully, for example.

**Comment by xfix** [comment] 2020-02-01 11:41
This seems somewhat surprising when `}` cannot be a fill character in Python.

**Comment by LukasKalbertodt** [comment] 2020-02-01 13:05
We can of course disallowed `}` as fill character (as #68726 does). I agree that it's unlikely someone actually uses `}` as fill character, but it's still a backwards incompatible change. We could also try to allow `}` and fix this "bug" by continue to parse to check if the format specifier is closed later in the string. But this would require quite a large look-ahead and would make the parser way more complicated I guess. It might also lead to syntax ambiguity. 

An alternative is to declare that this current behavior is not a bug, but intended. As far as I see, there is absolutely no point in writing a trailing `:` within the `{` `}` format specifier, right? It only makes sense if you actually specify something afterwards (before the closing `}`). So we can just disallow a trailing `:` in the grammar. We could make the error message better in those cases, though. What do you think about this?

**Comment by xfix** [comment] 2020-02-01 13:32
Thinking about it, considering that to be a feature is not a terrible choice. Sure, it's not really all that intuitive, but the fill character is the first thing that gets parsed after `:`, so there is a perfectly fine option of not having `:` at end of a format.

**Comment by Lokathor** [comment] 2020-02-01 15:03
In this case, there were two formatters, {var:} and also {var2:?}, so it made a sort of sense to have a trailing : after each one. I wasn't actively looking for a parser bug it just happened this way.

It's a fine thing to leave it this way in terms of the parsing now that I understand what it's doing. The error message just meeds to be better.

**Comment by xfix** [comment] 2020-02-01 16:10
I think the errors could specifically check for `}` fill character, and specifically point out `:` when `}` is expected with an error message to remove `:`.

**Comment by LukasKalbertodt** [comment] 2020-02-05 07:38
@xfix Do you want to implement the new error message? No need to, of course. I'm just asking because you created that other PR.

**Comment by xfix** [comment] 2020-02-05 12:09
Nah, not interested currently.

**Comment by estebank** [comment] 2023-08-03 12:10
Current output:

```
error: invalid format string: expected `'}'` but string was terminated
 --> src/main.rs:7:22
  |
7 |     println!("<{ch:}>", ch = c);
  |                    - ^ expected `'}'` in format string
  |                    |
  |                    this is not interpreted as a formatting closing brace
  |
  = note: the character `'}'` is interpreted as a fill character because of the `:` that precedes it
```

**Closed by estebank** 2023-08-03 12:10 UTC
Labels: C-enhancement, A-diagnostics, A-macros, T-compiler, D-confusing
