### ISSUE TITLE
ICE in stable 1.57.0 when missing generic argument in return type

### ISSUE THREAD

**Issue by arknave** [rust-lang/rust#92305] opened 2021-12-26 22:46 UTC
Repro steps: create a new cargo binary with `cargo new`. Replace `src/main.rs` with the following code. Then run `cargo build`. Hope this is helpful! I've tried to minimize the code as much as possible. 

### Code

```Rust
use std::iter;

fn f<T>(data: &[T]) -> impl Iterator<Item = Vec> {
    iter::empty()
}

fn g<T>(data: &[T], target: T) -> impl Iterator<Item = Vec<T>> {
    f(data).filter(|x| x == target)
}

fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
error[E0107]: missing generics for struct `Vec`
 --> src/main.rs:3:43
  |
3 | fn f<T>(data: &[T]) -> impl Iterator<Item=Vec> {
  |                                           ^^^ expected at least 1 generic argument
  |
help: add missing generic argument
  |
3 | fn f<T>(data: &[T]) -> impl Iterator<Item=Vec<T>> {
  |                                           ~~~~~~

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: PlaceBuilder { base: Upvar { var_hir_id: HirId { owner: DefId(0:9 ~ ice_repro[c5a9]::g), local_id: 4 }, closure_def_id: DefId(0:12 ~ ice_repro[c5a9]::g::{closure#0}), closure_kind: FnMut }, projection: [] }', compiler/rustc_mir_build/src/build/expr/as_place.rs:306:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_built] building MIR for `g::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `g::{closure#0}`
end of query stack
For more information about this error, try `rustc --explain E0107`.
error: could not compile `ice_repro` due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: PlaceBuilder { base: Upvar { var_hir_id: HirId { owner: DefId(0:9 ~ ice_repro[c5a9]::g), local_id: 4 }, closure_def_id: DefId(0:12 ~ ice_repro[c5a9]::g::{closure#0}), closure_kind: FnMut }, projection: [] }', compiler/rustc_mir_build/src/build/expr/as_place.rs:306:69
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: rustc_mir_build::build::expr::as_place::PlaceBuilder::into_place
   4: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::expr_into_dest
   5: rustc_mir_build::build::expr::as_temp::<impl rustc_mir_build::build::Builder>::as_temp_inner
   6: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::as_operand
   7: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::as_call_operand
   8: rustc_mir_build::build::expr::as_operand::<impl rustc_mir_build::build::Builder>::as_call_operand
   9: <core::iter::adapters::copied::Copied<I> as core::iter::traits::iterator::Iterator>::fold
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  11: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::expr_into_dest
  12: rustc_mir_build::build::scope::<impl rustc_mir_build::build::Builder>::in_scope
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::expr_into_dest
  15: rustc_mir_build::build::scope::<impl rustc_mir_build::build::Builder>::in_scope
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_mir_build::build::expr::into::<impl rustc_mir_build::build::Builder>::expr_into_dest
  18: rustc_mir_build::build::construct_fn
  19: rustc_infer::infer::InferCtxtBuilder::enter
  20: rustc_mir_build::build::mir_built
  21: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  22: rustc_data_structures::stack::ensure_sufficient_stack
  23: rustc_query_system::query::plumbing::try_execute_query
  24: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_built
  25: rustc_mir_transform::check_unsafety::unsafety_check_result
  26: core::ops::function::FnOnce::call_once
  27: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  28: rustc_data_structures::stack::ensure_sufficient_stack
  29: rustc_query_system::query::plumbing::try_execute_query
  30: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result
  31: <rustc_mir_transform::check_unsafety::UnsafetyChecker as rustc_middle::mir::visit::Visitor>::visit_rvalue
  32: rustc_mir_transform::check_unsafety::unsafety_check_result
  33: core::ops::function::FnOnce::call_once
  34: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  35: rustc_data_structures::stack::ensure_sufficient_stack
  36: rustc_query_system::query::plumbing::try_execute_query
  37: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result
  38: rustc_mir_transform::mir_const
  39: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  40: rustc_data_structures::stack::ensure_sufficient_stack
  41: rustc_query_system::query::plumbing::try_execute_query
  42: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_const
  43: rustc_mir_transform::mir_promoted
  44: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  45: rustc_data_structures::stack::ensure_sufficient_stack
  46: rustc_query_system::query::plumbing::try_execute_query
  47: rustc_query_system::query::plumbing::get_query
  48: rustc_borrowck::mir_borrowck
  49: core::ops::function::FnOnce::call_once
  50: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  51: rustc_data_structures::stack::ensure_sufficient_stack
  52: rustc_query_system::query::plumbing::try_execute_query
  53: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::mir_borrowck
  54: rustc_typeck::collect::type_of::type_of
  55: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  56: rustc_data_structures::stack::ensure_sufficient_stack
  57: rustc_query_system::query::plumbing::try_execute_query
  58: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::type_of
  59: rustc_typeck::check::check::check_item_type
  60: rustc_middle::hir::map::Map::visit_item_likes_in_module
  61: rustc_typeck::check::check::check_mod_item_types
  62: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  63: rustc_data_structures::stack::ensure_sufficient_stack
  64: rustc_query_system::query::plumbing::try_execute_query
  65: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_mod_item_types
  66: rustc_middle::hir::map::Map::for_each_module
  67: rustc_typeck::check_crate
  68: rustc_interface::passes::analysis
  69: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  70: rustc_data_structures::stack::ensure_sufficient_stack
  71: rustc_query_system::query::plumbing::try_execute_query
  72: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  73: rustc_interface::passes::QueryContext::enter
  74: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  75: rustc_span::with_source_map
  76: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

...

query stack during panic:
#0 [mir_built] building MIR for `g::{closure#0}`
#1 [unsafety_check_result] unsafety-checking `g::{closure#0}`
#2 [unsafety_check_result] unsafety-checking `g`
#3 [mir_const] processing MIR for `g`
#4 [mir_promoted] processing `g`
#5 [mir_borrowck] borrow-checking `g`
#6 [type_of] computing type of `g::{opaque#0}`
#7 [check_mod_item_types] checking item types in top-level module
#8 [analysis] running analysis passes on this crate
end of query stack
```

</p>
</details>

**Comment by arknave** [comment] 2021-12-26 22:50
The same issue happens in the latest nightly as well.

```
$ rustup run nightly rustc --version --verbose 
rustc 1.59.0-nightly (51e8031e1 2021-12-25)
binary: rustc
commit-hash: 51e8031e14a899477a5e2d78ce461cab31123354
commit-date: 2021-12-25
host: x86_64-apple-darwin
release: 1.59.0-nightly
LLVM version: 13.0.0
```

**Comment by dtolnay** [comment] 2021-12-27 03:10
This bisects to nightly-2021-06-25. Commit range: https://github.com/rust-lang/rust/compare/5a7834050f3a0ebcd117b4ddf0bc1e8459594309...7c3872e6bfd555d2ad753ac1f871db3bd7f2a547.

It only reproduces with `edition = "2021"`, not `edition = "2018"`, which means bisecting to the old nightly needs `cargo-features = ["edition2021"]` in Cargo.toml.

In that range, #86536 looks the most relevant because it is the only thing introducing edition-specific behavior, and it's dealing with closure capture and the presence of a closure appears necessary in the minimal repro. @arora-aman would you be interested in taking a look?

**Comment by apiraino** [comment] 2021-12-27 10:36
For comparison, the same code with `edition=2018`  doesn't emit a compiler error and has a bit more info:
```
error[E0107]: missing generics for struct `Vec`
   --> src/main.rs:3:45
    |
3   | fn f<T>(data: &[T]) -> impl Iterator<Item = Vec> {
    |                                             ^^^ expected at least 1 generic argument
    |
note: struct defined here, with at least 1 generic parameter: `T`
   --> /home/jman/.rustup/toolchains/1.56.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:398:12
    |
398 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    |            ^^^ -
help: add missing generic argument
    |
3   | fn f<T>(data: &[T]) -> impl Iterator<Item = Vec<T>> {
    |                                             ~~~~~~

error[E0282]: type annotations needed
 --> src/main.rs:4:5
  |
4 |     iter::empty()
  |     ^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the function `empty`

error[E0720]: cannot resolve opaque type
 --> src/main.rs:7:35
  |
3 | fn f<T>(data: &[T]) -> impl Iterator<Item = Vec> {
  |                        ------------------------- returning this opaque type `Filter<impl Iterator, [closure@src/main.rs:8:20: 8:35]>`
...
7 | fn g<T>(data: &[T], target: T) -> impl Iterator<Item = Vec<T>> {
  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ recursive opaque type
8 |     f(data).filter(|x| x == target)
  |     ------------------------------- returning here with type `Filter<impl Iterator, [closure@src/main.rs:8:20: 8:35]>`

Some errors have detailed explanations: E0107, E0282, E0720.
For more information about an error, try `rustc --explain E0107`.
error: could not compile `issue-92305` due to 3 previous errors
```

**Comment by apiraino** [comment] 2021-12-28 09:10
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2392305.20ICE.20in.20stable.201.2E57.2E0.20when.20missing.20generic.20argument.20i.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-low

**Comment by ouz-a** [comment] 2021-12-28 20:01
In both `version=2018` and `version=2021`, [this](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/build/expr/as_place.rs#L204) function returns `Ok` value every time but somehow in `version=2021` value unwraps into error, even though it's `Ok`


This is the returned value:
 ```
PlaceBuilder { base: Local(_1), projection: [Deref, Field(field[0], &T), Deref] }
```

**Comment by JohnTitor** [comment] 2022-04-30 19:40
Triage: This is no longer ICE with the latest nightly, since #96548 (presumably #96516). Marked as `E-needs-test`.

**Closed** 2022-05-03 08:36 UTC
Labels: I-ICE, E-needs-test, P-low, T-compiler, regression-from-stable-to-stable, C-bug, glacier
