### ISSUE TITLE
strange errors with multiple impls of FnOnce

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#31560] opened 2016-02-11 03:45 UTC
If one maliciously attempts to hack function overloading into rust

``` rust
#![feature(unboxed_closures, fn_traits)]

use std::ops::FnOnce;

struct Nope;

impl FnOnce<()> for Nope {
    type Output = ();

    extern "rust-call" fn call_once(self, _: ()) {}
}

impl FnOnce<((),())> for Nope {
    type Output = ();

    extern "rust-call" fn call_once(self, _: ((),())) {}
}

fn main() {
    Nope();
}
```

then one receives appropriately inscrutable errors:

```
<anon>:20:5: 20:11 error: the type of this value must be known in this context
<anon>:20     Nope();
              ^~~~~~
<anon>:20:5: 20:11 error: cannot use call notation; the first type parameter for the function trait is neither a tuple nor unit [E0059]
<anon>:20     Nope();
              ^~~~~~
<anon>:20:5: 20:11 help: see the detailed explanation for E0059
error: aborting due to 2 previous errors
playpen: application terminated with error code 101
```

I don't understand which value rustc wants a type for, and the second error is clearly untrue. I assume this use case is not going to be supported, even if these features are stabilized, but the diagnostic is not good.

**Comment by qnighy** [comment] 2017-05-18 11:52
Looks like a duplicate of #18952.

**Comment by Mark-Simulacrum** [comment] 2017-05-18 11:53
Closing in favor, as duplicate.

**Closed by Mark-Simulacrum** 2017-05-18 11:53 UTC
Labels: A-diagnostics, T-libs
