### ISSUE TITLE
rustc produce considerably bigger release binaries after rustc 1.14.0-nightly (3caf63cc0 2016-10-24)

### ISSUE THREAD

**Issue by tjikini** [rust-lang/rust#38908] opened 2017-01-07 17:28 UTC
[Mentioned on /r/rust](https://www.reddit.com/r/rust/comments/5jserj/announcing_rust_114/dbj9et6/)

My little project for example:
`rustc +nightly-2016-10-21 -O`: 652K
`rustc +nightly-2016-10-26 -O`: 1.9M

Sizes after `strip` are the same (368K)

**Comment by michaelwoerister** [comment] 2017-01-09 16:41
Thanks for the report! We should definitely look into that.

cc @rust-lang/compiler @rust-lang/tools

**Comment by michaelwoerister** [comment] 2017-01-09 16:49
The change must have been introduced somewhere in this range: https://github.com/rust-lang/rust/compare/f09420685...3caf63cc0

**Comment by eddyb** [comment] 2017-01-09 16:54
My bet is on https://github.com/rust-lang/rust/commit/803576c17e24a5a9e680849346f58d6b6545fb79. If `libstd` is statically linked and it contains debug symbols, those add to the size, right?

**Comment by michaelwoerister** [comment] 2017-01-09 16:58
That could well be the cause.

**Comment by michaelwoerister** [comment] 2017-01-09 17:57
I can confirm @eddyb's hunch, it's the debuginfo for stdlibs which is causing the increased size. I'll add it to the list of reasons to have MIR-only rlibs (https://github.com/rust-lang/rust/issues/38913).

**Comment by alexcrichton** [comment] 2017-01-11 23:56
Thanks for the confirmation @michaelwoerister! With that in mind I feel that there's not a lot we can do about this because we don't want to remove the debug info from libstd yet.

**Comment by Mark-Simulacrum** [comment] 2017-05-19 15:42
We found the problem and decided to not do anything at least for now so I think closing makes sense for the time being.

**Closed by Mark-Simulacrum** 2017-05-19 15:42 UTC
