### ISSUE TITLE
"error: internal compiler error: unexpected panic" when building obsolete code

### ISSUE THREAD

**Issue by dripton** [rust-lang/rust#33292] opened 2016-04-30 17:17 UTC
I did a rustup to rustc 1.10.0-nightly (8da2bcac5 2016-04-28), and then ran make in my project, without first recompiling a dependency ("num") which had been built under rustc 1.7.0-nightly (81ae8be71 2015-12-09)

rustc gave me an excellent error message describing exactly what was wrong and what I needed to do.  But then it panicked.

```
dripton@al:~/git/projecteuler$ make
rustc --crate-type=lib math.rs -L . -L ../num/target/debug -L ../num/target/debug/deps
math.rs:3:1: 3:18 error: the crate `num` has been compiled with rustc 1.7.0-nightly (81ae8be71 2015-12-09), which is incompatible with this version of rustc [E0514]
math.rs:3 extern crate num;
          ^~~~~~~~~~~~~~~~~
math.rs:3:1: 3:18 help: consider removing the compiled binaries and recompiling with your current version of rustc
ERROR:rbml::reader: failed to find block with tag 275
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/librbml/lib.rs:436
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make: *** [libmath.rlib] Error 101
```

**Comment by dripton** [comment] 2016-04-30 17:20
Note: Once I recompiled the dependency with the latest rustc, the problem went away.  So this bug isn't really causing me any problems.  Just reporting it because rustc asked me to.

**Comment by nagisa** [comment] 2016-04-30 19:50
Note: I took liberty to re-fcrmat the original report.

This seems to be a duplicate of https://github.com/rust-lang/rust/issues/32857. Thanks for the report!

**Closed by nagisa** 2016-04-30 19:50 UTC
