### ISSUE TITLE
feature(generic_associated_types): compiler panicked

### ISSUE THREAD

**Issue by attdona** [rust-lang/rust#51148] opened 2018-05-29 05:46 UTC
I'm trying to use `generic_associated_types` feature but the compiler panics:

    #![feature(generic_associated_types)]

    use std::ops::Index;
    use std::fmt::Display;

    fn main() {

        let w = Wrap(vec!['a', 'b']);
        let mut v: Vec<&Index<usize, Output = Display>> = Vec::new();
        v.push(&w as &Index<usize, Output = Display>);

    }

    struct Wrap<T>(Vec<T>);

    impl<T> Index<usize> for Wrap<T>
    where T: Display {
        type Output<'a> = Display + 'a;
        fn index<'a>(&'a self, index: usize) -> &'a Self::Output {
            &self.0[index]
        }
    }

Output:

    thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:499:9
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    error: aborting due to previous error
    
    
    note: the compiler unexpectedly panicked. this is a bug.
    
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    
    note: rustc 1.27.0-nightly (9fae15374 2018-05-13) running on x86_64-unknown-linux-gnu
    
    note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin
    
    note: some of the compiler flags provided by cargo are hidden

**Comment by hellow554** [comment] 2018-05-29 06:15
can you please provide the backtrace? (Just do, what the compiler tells you ;) )

`note: Run with 'RUST_BACKTRACE=1' for a backtrace.`

**Comment by BartMassey** [comment] 2018-06-15 00:43
May have run into the same bug. <http://play.rust-lang.org/?gist=bab838d30f047184fea2088d52dec3c8&version=nightly&mode=debug>

**Comment by dtolnay** [comment] 2018-06-16 15:45
Closing as a duplicate of #49362. I believe generic associated types has not been implemented yet.

**Closed by dtolnay** 2018-06-16 15:45 UTC
Labels: A-associated-items, A-typesystem, C-bug, I-ICE, T-compiler
