### ISSUE TITLE
[Rejects-valid] with two-phase-borrows

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#46764] opened 2017-12-16 09:13 UTC
A little example code:

```
#![feature(asm)]

#[allow(unused_variables, unused_mut, unused_assignments)]
fn foo(a: u64, b: u64, x: u64) -> u64 {
    let mut w: u64;
    let mut result: u64;

    unsafe {
        asm!("mulq $3; divq $4;"
             : "=&{ax}"(w), "=&{dx}"(result)
             : "{ax}"(a), "r"(b), "r"(x)
             );
    }
    result
}

fn main() {
    foo(1, 2, 3);
}
```

Compiles and runs with no arguments:

`...>rustc test.rs`

But gives an error with two-phase-borrows:

```
...>rustc -Z borrowck=mir -Z two-phase-borrows test.rs
error[E0381]: use of possibly uninitialized variable: `result`
  --> test.rs:14:5
   |
14 |     result
   |     ^^^^^^ use of possibly uninitialized `result`
```

```
rustc 1.24.0-nightly (77efd6800 2017-12-15)
host: x86_64-pc-windows-gnu
```

**Comment by arielb1** [comment] 2017-12-17 02:13
Duplicate of #45695 - ASM statements are broken in moveck & MIR borrowck.

**Closed by arielb1** 2017-12-17 02:13 UTC
