### ISSUE TITLE
Can not disable sign-ext feature for wasm32 target

### ISSUE THREAD

**Issue by laizy** [rust-lang/rust#109807] opened 2023-03-31 08:40 UTC
I tried to build a wasm binary with MVP opcode only, so I disabled the features:

```bash
RUSTFLAGS='-C link-arg=-zstack-size=32768 -C target-feature=-mutable-globals,-sign-ext,-multivalue,-simd128'
 cargo build --release --target=wasm32-unknown-unknown
```

I expected to see no [sign-extension opcode](https://github.com/WebAssembly/sign-extension-ops/blob/master/proposals/sign-extension-ops/Overview.md) in the wasm binary.

Instead, this happened: 
```bash
$ wasm-tools parse -t target/wasm32-unknown-unknown/release/output.wasm -o hello.wat
$ cat hello.wat | grep i32.ext
                            i32.extend8_s
```

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (ec2f40c6b 2023-03-30)
binary: rustc
commit-hash: ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b
commit-date: 2023-03-30
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by CryZe** [comment] 2023-04-01 00:04
You can not deactivate default features, because std is prebuilt. You need `-Z build-std` to build std yourself. Also these features are considered the default by LLVM ever since the recent upgrade to LLVM 16:

https://github.com/llvm/llvm-project/blob/f991f30845bb464a1a8e240b3512bac0258417db/llvm/lib/Target/WebAssembly/WebAssembly.td#L99-L106

This should possibly be mentioned in the Rust 1.70 release notes though?

**Comment by nikic** [comment] 2023-04-01 08:05
cc @alexcrichton to confirm that we're fine with inheriting this change to default target features in Rust.

**Comment by alexcrichton** [comment] 2023-04-01 15:56
More context for this change can be found in these locations:

* https://github.com/WebAssembly/tool-conventions/issues/158#issuecomment-1282886845 - discussion about enabling new features in both Emscripten and LLVM.
* https://reviews.llvm.org/D125728 - the original LLVM patch for this
* https://reviews.llvm.org/D125729 - more follow-up discussion on LLVM

In that sense this is an expected change, but at the same time the change was made with the expectation that most users are running on an engine that implements sign-extension. @laizy could you expand a bit more on your motivation for excluding these sign-extension instructions?

I do agree, though, that this should be mentioned in the detailed release notes. It's unfortunately a bit opaque since not all users of wasm are intimately familiar with proposals and whether or not engines support them, but it's a change nonetheless worth mentioning.

**Comment by laizy** [comment] 2023-04-03 05:04
I have tried to use `-Z build-std=core, alloc`, still not work:
```bash
RUSTFLAGS="-C link-arg=-zstack-size=32768 -C target-feature=-mutable-globals,-sign-ext,-multivalue,-simd128" cargo build -Z build-std=core,alloc --release --target=wasm32-unknown-unknown
```

@alexcrichton Our blockchain platform has used Wasm as a virtual machine running smart contracts and has been running steadily for many years. The MVP opcodes is fully sufficient for our use case. I hope there are ways to turn off these default extension features to avoid frequent upgrades every time a new feature is introduced.

**Comment by alexcrichton** [comment] 2023-04-05 15:07
Could you share the code used to reproduce this?

These upgrades will not be frequent. This is the first time it's changed in 5 years.

**Comment by shanemadden** [comment] 2023-04-15 19:45
The use case I have for wanting to build without these extensions isn't critical (servers for a game which don't support the extensions in the old version of nodejs they're running), but a way to successfully disable them to be able to build for such environments would be appreciated!

**Comment by alexcrichton** [comment] 2023-04-15 19:58
It would be helpful to have a reproduction of this to run to test out fixes. I tested something locally and `-Ctarget-cpu=mvp` was sufficient to disable sign extension instructions. I don't know why `-C target-feature=-sign-ext` isn't working and that may be an LLVM bug. I can't confirm whether this works for others though without a means of reproduction.

**Comment by CryZe** [comment] 2023-04-15 20:17
I just tried the following:

```rust
#[no_mangle]
pub extern "C" fn foo(a: &i8, b: &i8) -> i32 {
    (*a + *b) as _
}
```
compiled with:
`RUSTFLAGS="-C target-feature=-sign-ext" cargo build --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort` 

and it totally still contains the sign-ext instructions:
```wasm
(func (;0;) (type 0) (param i32 i32) (result i32)
    local.get 1
    i32.load8_u
    local.get 0
    i32.load8_u
    i32.add
    i32.extend8_s)
```

So you are right, this is some sort of LLVM bug.

**Comment by shanemadden** [comment] 2023-04-16 00:20
Confirming that `-Ctarget-cpu=mvp` results in a file without the sign-ext opcodes, while `-Ctarget-feature=-sign-ext` does not, in my testing as well.

**Comment by alexcrichton** [comment] 2023-04-16 02:08
@sunfishcode would you perhaps know more about [this behavior](https://godbolt.org/z/Te5fczPhM)? I would expect that with `-sign-ext` on the function then even without `-mcpu=mvp` sign-extension instructions wouldn't get generated, but I'm not sure.

**Comment by kvinwang** [comment] 2023-06-03 09:54
> I just tried the following:
> 
> ```rust
> #[no_mangle]
> pub extern "C" fn foo(a: &i8, b: &i8) -> i32 {
>     (*a + *b) as _
> }
> ```
> 
> compiled with: `RUSTFLAGS="-C target-feature=-sign-ext" cargo build --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort`
> 
> to make sure std being precompiled isn't causing problems, and it totally still contains the sign-ext instructions:
> 
> ```webassembly
> (func (;0;) (type 0) (param i32 i32) (result i32)
>     local.get 1
>     i32.load8_u
>     local.get 0
>     i32.load8_u
>     i32.add
>     i32.extend8_s)
> ```
> 
> So you are right, this is some sort of LLVM bug.

It can also reproduce with: `RUSTFLAGS="-C linker-plugin-lto -C target-cpu=mvp" cargo build --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --no-default-features`

**Comment by kalzoo** [comment] 2023-09-03 23:16
FWIW, the above flags did not work for me with `wasm-pack` - the resulting binary still had sign-extension opcodes (namely `0xc0`) - but this served as a workaround ([ref](https://rustwasm.github.io/wasm-pack/book/cargo-toml-configuration.html)):

```
[package.metadata.wasm-pack.profile.dev]
wasm-opt = ["--signext-lowering"]
```

Command:

```
RUSTFLAGS="-C target-feature=-sign-ext -C target-cpu=mvp" wasm-pack build --dev . -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```

^ With the wasm-opt pass, sign-extension ops were gone; without the pass, still there. From the thread above, it sounds like those flags work for some people but not for others.

```
➜ rustc --version
rustc 1.74.0-nightly (35e416303 2023-09-01)
```

**Comment by stephanemagnenat** [comment] 2024-01-11 09:47
A slightly related issue is that the WebAssembly extensions used by default by the Rust compiler are not documented, I opened a specific issue for that (#119811) and just want to link it here.

**Comment by alexcrichton** [comment] 2024-08-01 19:04
As a heads up I've added documentation about features to https://github.com/rust-lang/rust/pull/128511 which I've currently got as flagged to close this issue. The documented solution for targetting MVP wasm is:


```sh
$ export RUSTFLAG=-Ctarget-cpu=mvp
$ cargo +nightly build -Zbuild-std=panic_abort,std --target wasm32-unknown-unknown
```

which should solve the original OP of this issue. Other solutions in this issue such as using `-Ctarget-feature=-sign-ext` or that in conjunction with `-Clto` or others don't work for one reason or another. Using the `mvp` target-cpu, however, plus recompiling the standard library with `-Zbuild-std`, does work.

**Closed** 2024-08-23 13:23 UTC
Labels: A-LLVM, A-codegen, T-compiler, O-wasm, C-bug, A-target-feature
