### ISSUE TITLE
Backwards-incompatible lifetime change (regression)

### ISSUE THREAD

**Issue by staktrace** [rust-lang/rust#85574] opened 2021-05-22 03:20 UTC
I tried this:

```
rustup update nightly
git clone https://github.com/rust-lang/git2-rs && cd git2-rs
cargo +nightly build
```

I expected to see this happen: build completes

Instead, this happened: build failed with this output:

```
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/attr.rs:74:15
   |
74 |         match (self, other) {
   |               ^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime defined on the method body at 73:26...
  --> src/attr.rs:73:26
   |
73 |     fn eq(&self, other: &AttrValue<'_>) -> bool {
   |                          ^^^^^^^^^^^^^
note: ...so that the types are compatible
  --> src/attr.rs:74:15
   |
74 |         match (self, other) {
   |               ^^^^^^^^^^^^^
   = note: expected `(&AttrValue<'_>, &AttrValue<'_>)`
              found `(&AttrValue<'_>, &AttrValue<'_>)`
note: but, the lifetime must be valid for the lifetime `'_` as defined on the impl at 72:30...
  --> src/attr.rs:72:30
   |
72 | impl PartialEq for AttrValue<'_> {
   |                              ^^
note: ...so that the types are compatible
  --> src/attr.rs:79:16
   |
79 |             | (Self::Bytes(bytes), AttrValue::String(string)) => string.as_bytes() == *bytes,
   |                ^^^^^^^^^^^^^^^^^^
   = note: expected `AttrValue<'_>`
              found `AttrValue<'_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`.
error: could not compile `git2`

To learn more, run the command again with --verbose.
```

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.54.0-nightly (5dc8789e3 2021-05-21)
binary: rustc
commit-hash: 5dc8789e300930751a78996da0fa906be5a344a2
commit-date: 2021-05-21
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

This was working with the rustc nightly from `rustc 1.54.0-nightly (f94942d84 2021-05-19)` so this is a very recent regression.

**Comment by Mark-Simulacrum** [comment] 2021-05-22 03:31
Might be https://github.com/rust-lang/rust/pull/85511, but would be good to bisect.

**Comment by ehuss** [comment] 2021-05-22 04:39
Bisect confirmed it is #85511.  This is blocking cargo's CI.  Let me know if there's any way I can help.

**Comment by ehuss** [comment] 2021-05-22 05:10
Here's a reproduction:

```rust
pub enum Foo<'string> {
    String(&'string str),
}

impl Foo<'_> {
    fn f(&self, other: &Foo<'_>) {
        match (self, other) {
            // Important: a and b swap between the two patterns
            (Foo::String(a), Foo::String(b))
            | (Self::String(b), Foo::String(a)) => {}
        }
    }
}
```

I couldn't get it smaller than that.

I don't know if this is helpful, but the following will ICE on stable/beta, but returns E0495 on nightly:

```rust
enum Foo<'a> {
    Var(&'a str)
}

impl Foo<'_> {
    fn f(other: Foo<'_>) {
        match other {
            Self::Var(..) => {}
        }
    }
}
```

**Comment by matthiaskrgr** [comment] 2021-05-22 08:47
Note for those also affected by this:
`git2` `0.12` still builds so you might be able to temporarily downgrade your git2 dependency as a workaround until there is a solution.

**Comment by Mark-Simulacrum** [comment] 2021-05-22 11:37
Cc @nikomatsakis 

I'd lean towards reverting for now (and potentially landing as future compat or something). I'm not sure if this is technically a soundness fix, Niko can likely give a better reading there. I think the problem is that Self::String as a constructor is now (I believe arguably correctly, but not sure if it has any soundness implications) requiring the argument to outlive the lifetime on Self - but of course this isn't necessarily true of the other branch.

This means that changing Self to the actual name of the type will fix this, so maybe patching git2 quickly is a good idea; it'll fix things before the next nightly at least for Cargo.

**Comment by staktrace** [comment] 2021-05-22 11:41
> This means that changing Self to the actual name of the type will fix this, so maybe patching git2 quickly is a good idea; it'll fix things before the next nightly at least for Cargo.

Replacing the `<'_>` with `<'a>` in `src/attr.rs` in git2 seems to fix the error.

**Comment by staktrace** [comment] 2021-05-22 11:51
> Note for those also affected by this:
> `git2` `0.12` still builds so you might be able to temporarily downgrade your git2 dependency as a workaround until there is a solution.

You can actually just downgrade to `0.13.17` and that will work too. The src/attr.rs code is new in `0.13.18`.

**Comment by Mark-Simulacrum** [comment] 2021-05-22 17:04
I haven't been able to come up with an example that uses the lifetime mismatch to do anything bad yet, but judging by the fact that other similar code seems to demand equality, it seems likely that this is indeed a bug fix.

Filed https://github.com/rust-lang/rust/pull/85584 to revert the PR on nightly for now.

**Comment by nikomatsakis** [comment] 2021-05-24 17:44
I believe the new behavior is correct, yes. In the minimized example, the variable `b` is being forced to have both types. I'm not sure if one can create an unsoundness *from pattern matching specifically*, but @Mark-Simulacrum we already found one soundness hole that was closed by the PR.

**Comment by nikomatsakis** [comment] 2021-05-24 17:45
Region errors like this are traditionally the sort of thing that is hard to manage with a warning period. We could potentially swing it but it'll take some effort.

**Comment by Mark-Simulacrum** [comment] 2021-05-24 17:56
Hm. Well, so far I think the only breakage we know of is in git2 and an easy fix -- and a patch release is already out there.

Let's not land the revert for now then since we do recognize it as a soundness bug "in theory" if not necessarily in practice, and we can see what beta crater (in the next cycle, this is in nightly for now) reveals.

**Comment by arturoc** [comment] 2021-08-11 08:37
I'm getting a similar problem on some rust code after updating stable from 1.53 to 1.54. Will try to find a small example to post but it seems related to use `for<'a> ...` to specify bounds on a trait implementation

**Comment by nbdd0121** [comment] 2021-10-04 20:32
A slightly modified version of @ehuss's mcve:
```rust
pub enum Foo<'string> {
    String(&'string str),
}

impl<'a> Foo<'a> {
    fn f<'b>(&self, other: &Foo<'b>) {
        match (self, other) {
            // Important: a and b swap between the two patterns, and one pattern uses `Self`
            (Foo::String(a), Foo::String(b))
            | (Foo::<'a>::String(b), Foo::String(a)) => {}
        }
    }
}
```
This wouldn't compile on 1.53. The only change is to spell `Self` out explicitly (with `Foo::<'a>`). So I would say this should indeed be considered as a bugfix. I guess the issue should be closed? (at least it shouldn't be P-critical)

Also the effected version is 1.54+, so retag:
@rustbot label -regression-from-stable-to-beta + regression-from-stable-to-stable

**Comment by apiraino** [comment] 2021-12-02 10:08
Demoting to P-high after reading the latest comments

@rustbot label -P-critical +P-high

**Closed** 2022-02-03 12:07 UTC
Labels: P-high, relnotes, regression-from-stable-to-stable, C-bug, T-release
