### ISSUE TITLE
[nll] attr-0.1.0 regression

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53569] opened 2018-08-21 17:45 UTC
Found during a crater run

[Minimized reproduction](https://play.rust-lang.org/?gist=46146e256a3e138cbd42d0ee34b43571&version=nightly&mode=debug&edition=2015)

**Comment by matthewjasper** [comment] 2018-08-21 18:52
Assigning myself since I've done some work in this locally. But I have a lot going on ATM, so anyone else can feel free to take it.

The issue is the same as #47917, #49822 and #52782 but for enums. I have plans to move all of this checking to happen in/after `places_conflict` which should also handle this case correctly.

**Comment by nikomatsakis** [comment] 2018-08-21 19:55
Further minimized:

https://play.rust-lang.org/?gist=3381ab532d051339d34a57a7ba395ec8&version=nightly&mode=debug&edition=2015

**Comment by nikomatsakis** [comment] 2018-08-21 21:05
Hmm, looking a bit more closely, I would say that this is a subtle situation. I agree with @matthewjasper that this is basically a "dangly paths" situation (cc #52782). That said, @matthewjasper, I'm not sure I understood the fix you were proposing. =) 

Let me lay out what is happening, as best as I understand it:

- First, the call to `self.get` returns a `Result<&'0 mut Value, String>`
- Then, the `let _res: &'a u32 = ...` forces `'0: 'a`
  - if you [remove that type annotation](https://play.rust-lang.org/?gist=f3a1a96d9c7198972c47eb836b540c96&version=nightly&mode=debug&edition=2015), everything builds
- Finally, we execute `Drop(v)` -- this is considered an error because there is an outstanding loan of `v.as<Ok>.0`. 
  - This is basically a **correct error** -- we should not drop things when their interior is borrowed
  - *However,* in this case, `Drop` itself does not have a destructor -- the destructor is on `String`, and of course if `String` is being dropped, then this is an `Err` case, and hence we know that the borrow never happened.

**Comment by nikomatsakis** [comment] 2018-09-04 19:42
@matthewjasper made a [topic on Zulip to discuss](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/.2353569.20even.20more.20dangly.20paths)

**Comment by nikomatsakis** [comment] 2018-09-04 19:44
Removing nomination but we do have to settle on a plan

**Comment by Mark-Simulacrum** [comment] 2018-09-07 01:39
@nikomatsakis @matthewjasper @pnkfelix It's not clear to me that this has sufficient momentum or decision-making to land for RC1 -- should this be pushed back to RC2, or is this truly a blocking issue?

**Comment by pnkfelix** [comment] 2018-09-19 10:10
(Since not everyone will follow the comments on every linked PR: this can be addressed by PR #54324, but we closed that because we are anticipating a better, broader fix from @matthewjasper , previewed here: https://github.com/rust-lang/rust/compare/master...matthewjasper:better-drop-access )

**Closed** 2018-09-24 17:37 UTC
Labels: A-NLL, NLL-complete
