### ISSUE TITLE
Trait inherits from other traits, but cannot be casted back to them

### ISSUE THREAD

**Issue by ihrwein** [rust-lang/rust#26918] opened 2015-07-09 13:10 UTC
I don't know why I cannot cast `FooBar` back to `Foo` or `Bar`.

I tried this code:

``` rust
trait Foo {}

trait Bar {}

trait FooBar: Foo + Bar {}

impl <T: Foo + Bar> FooBar for T {}

struct A;

impl Foo for A {}
impl Bar for A {}

fn test(fb: &FooBar) -> &Foo {
    fb as &Foo
}

fn main() {
    let a = A;
    test(&a);
}
```

I expected it to compile.

Instead, this happened:

```
<anon>:15:5: 15:15 error: cast to fat pointer: `&FooBar` as `&Foo`
<anon>:15     fb as &Foo
              ^~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```
## Meta

I used playpen with the stable channel.

**Comment by Mark-Simulacrum** [comment] 2017-04-30 19:19
This is effectively a duplicate of #5665.

**Closed by Mark-Simulacrum** 2017-04-30 19:19 UTC
Labels: A-typesystem
