### ISSUE TITLE
rustdoc should hide private members in a const definition

### ISSUE THREAD

**Issue by alexkazik** [rust-lang/rust#113768] opened 2023-07-16 21:33 UTC
When re-exporting a struct from another crate which has private fields and constant(s) then the "value" of the constants are printed in rustdoc.

[Original documentation](https://docs.rs/scientific/latest/scientific/struct.Scientific.html) of the external crate (as expected):
```doc
pub const ZERO: Scientific = _
```

I tried this code:

```rust
pub use scientific::Scientific;
```

I expected to see this happen: same documentation as above.

Instead, this happened:
```doc
pub const ZERO: Scientific = Scientific{ inner: Sci::ZERO,}
```

The general privacy of const seemed to be fixed in https://github.com/rust-lang/rust/issues/32735 but not this case.

### Meta
`rustc --version --verbose`:
```
binary: rustc
commit-hash: 8ede3aae28fe6e4d52b38157d7bfe0d3bceef225
commit-date: 2023-07-12
host: aarch64-apple-darwin
release: 1.71.0
LLVM version: 16.0.5

rustc 1.73.0-nightly (33a2c2487 2023-07-12)
binary: rustc
commit-hash: 33a2c2487ac5d9927830ea4c1844335c6b9f77db
commit-date: 2023-07-12
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

**Comment by fmease** [comment] 2023-07-16 22:54
Dupe of #99630.

**Closed** 2023-07-17 06:16 UTC
Labels: C-bug, needs-triage
