### ISSUE TITLE
ICE: Failing to compile gfx-backend-metal: Unexpected type for constructor

### ISSUE THREAD

**Issue by tuzz** [rust-lang/rust#89393] opened 2021-09-30 09:16 UTC
### Repro

When compiling on an Apple M1 processor:

```sh
git clone https://github.com/gfx-rs/gfx.git
cd gfx/src/backend/metal
RUST_BACKTRACE=1 cargo check
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (11491938f 2021-09-29)
```

### Error output

```
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/deconstruct_pat.rs:1191:22: Unexpected type for `Single` constructor: <&soft::Ref as soft::Resources>::BufferArray

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (11491938f 2021-09-29) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `soft::<impl at src/backend/metal/src/soft.rs:208:1: 476:2>::own_render`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `gfx-backend-metal`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_mir_build::thir::pattern::deconstruct_pat::Fields::wildcards
   8: rustc_mir_build::thir::pattern::deconstruct_pat::DeconstructedPat::specialize
   9: rustc_mir_build::thir::pattern::usefulness::is_useful
  10: rustc_mir_build::thir::pattern::usefulness::is_useful
  11: rustc_mir_build::thir::pattern::usefulness::is_useful
  12: rustc_mir_build::thir::pattern::usefulness::is_useful
  13: rustc_mir_build::thir::pattern::usefulness::compute_match_usefulness
  14: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  15: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  16: rustc_mir_build::thir::pattern::check_match::check_match
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::try_execute_query
  20: rustc_query_system::query::plumbing::get_query
  21: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  22: rustc_session::utils::<impl rustc_session::session::Session>::time
  23: rustc_session::utils::<impl rustc_session::session::Session>::time
  24: rustc_interface::passes::analysis
  25: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  26: rustc_data_structures::stack::ensure_sufficient_stack
  27: rustc_query_system::query::plumbing::try_execute_query
  28: rustc_query_system::query::plumbing::get_query
  29: rustc_interface::passes::QueryContext::enter
  30: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  31: rustc_span::with_source_map
  32: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by camdencheek** [comment] 2021-09-30 15:41
Can also reproduce this when compiling on an Intel Macbook

**Comment by P1n3appl3** [comment] 2021-09-30 20:14
I've encountered the same error on a different platform (x86_64). The project doesn't use cargo so repro is nontrivial, but from [our CI](https://ci.chromium.org/p/fuchsia/builders/toolchain.ci/rust_toolchain.core.x64-debug) I can see that the ICE started occurring at 6df1d82869d06b88ff413e63a1e8efbb311e3b5c which is a rollup of #88950.

### Error output

```
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (6dc08b909 2021-09-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dep-info-omit-d-target -Z mutable-noalias=off -Z panic_abort_tests -Z allow-features=min_specialization,specialization -C linker=../../prebuilt/third_party/clang/linux-x64/bin/lld -C link-arg=--sysroot=gen/zircon/public/sysroot/cpp -C link-arg=-L../../prebuilt/third_party/clang/linux-x64/bin/../lib/x86_64-unknown-fuchsia -C link-arg=-L../../prebuilt/third_party/clang/linux-x64/lib/clang/14.0.0/lib/x86_64-unknown-fuchsia -C link-arg=--pack-dyn-relocs=relr -C link-arg=-dynamic-linker=ld.so.1 -C link-arg=--icf=all -C force-frame-pointers -C opt-level=0 -C debuginfo=2 -C debug-assertions=yes -C link-args=-zstack-size=0x200000 -C panic=abort -C force-unwind-tables=yes -C link-arg=-Bdynamic -C link-arg=x64-shared/lib.unstripped/libcrypto.so --crate-type rlib

query stack during panic:
#0 [check_match] match-checking `ip::gmp::igmp::run_action`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1146:9
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_mir_build::thir::pattern::deconstruct_pat::Fields::wildcards
   8: rustc_mir_build::thir::pattern::deconstruct_pat::DeconstructedPat::specialize
   9: rustc_mir_build::thir::pattern::usefulness::is_useful
  10: rustc_mir_build::thir::pattern::usefulness::is_useful
  11: rustc_mir_build::thir::pattern::usefulness::compute_match_usefulness
  12: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  13: rustc_hir::intravisit::walk_expr
  14: <rustc_mir_build::thir::pattern::check_match::MatchVisitor as rustc_hir::intravisit::Visitor>::visit_expr
  15: rustc_mir_build::thir::pattern::check_match::check_match
  16: rustc_query_system::query::plumbing::try_execute_query
  17: rustc_query_system::query::plumbing::get_query
  18: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::par_body_owners
  19: rustc_session::utils::<impl rustc_session::session::Session>::time
  20: rustc_session::utils::<impl rustc_session::session::Session>::time
  21: rustc_interface::passes::analysis
  22: rustc_query_system::query::plumbing::try_execute_query
  23: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  24: rustc_interface::passes::QueryContext::enter
  25: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  26: rustc_span::with_source_map
  27: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by ndmitchell** [comment] 2021-10-01 08:22
Also seems to be hitting starlark-rust, https://github.com/facebookexperimental/starlark-rust, as per https://github.com/facebookexperimental/starlark-rust/runs/3764656763?check_suite_focus=true

**Comment by hkratz** [comment] 2021-10-01 17:13
Somewhat minimized standalone testcase:
```rust
pub trait Resources2 {
    type BufferArray;
}

pub enum RenderCommand2<R: Resources2> {
    BindBuffers { buffers: R::BufferArray },
}

pub struct Ref2;
impl<'a> Resources2 for &'a Ref2 {
    type BufferArray = (&'a u32, &'a u32);
}

pub fn own_render2(com: RenderCommand2<&Ref2>) -> u32 {
    match com {
        RenderCommand2::BindBuffers {
            buffers: (_buffers, _offsets),
        } => 0,
    }
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=12d9cc9e178e8cca88dcc0fb41704fd8)

Builds on stable, fails on nightly.

cc @Nadrieril

**Comment by Nadrieril** [comment] 2021-10-01 17:36
Thanks for the minimization! Seems like we've hit https://github.com/rust-lang/rust/issues/72476 again, but through a different code path. I'm investigating

**Comment by Lukas-Dresel** [comment] 2021-10-01 21:49
I think #89448 might be another duplicate of this, triggered when compiling the `smt2` crate.

**Closed** 2021-10-02 01:32 UTC
Labels: I-ICE, T-compiler, C-bug, A-exhaustiveness-checking
