### ISSUE TITLE
Regression: Fail to evaluate static slice with reference to internally-mutable data

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rust#120968] opened 2024-02-12 13:32 UTC
### Code

I tried this code:

```rust
use std::sync::OnceLock;

static LAZY_INIT: OnceLock<u32> = OnceLock::new();

static LAZY_INIT_REF: &[&OnceLock<u32>] = &[&LAZY_INIT];
```

I expected to see this happen: it compiles with `LAZY_INIT` being reachable through `LAZY_INIT_REF`.

Instead, this happened:

```
error[E0080]: it is undefined behavior to use this value
 --> src/main.rs:5:1
  |
5 | static LAZY_INIT_REF: &[&OnceLock<u32>] = &[&LAZY_INIT];
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value at .<deref>[0]: encountered reference to mutable memory in `const`
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 8, align: 8) {
              ╾─────alloc4<imm>─────╼                         │ ╾──────╼
          }

note: erroneous constant encountered
 --> src/main.rs:5:43
  |
5 | static LAZY_INIT_REF: &[&OnceLock<u32>] = &[&LAZY_INIT];
  |                                           ^^^^^^^^^^^^^
```

### Version it worked on

It most recently worked on: `nightly-2024-02-10`

### Version with regression

`nightly-2024-02-11`

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (6cc484351 2024-02-10)
binary: rustc
commit-hash: 6cc4843512d613f51ec81aba689180c31b0b28b6
commit-date: 2024-02-10
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 17.0.6
```

@rustbot modify labels: +regression-from-stable-to-nightly +A-const-eval +T-compiler -regression-untriaged

**Comment by nvzqz** [comment] 2024-02-12 13:34
Like #120949, this issue is not contrived since I also use this technique in [Divan](https://github.com/nvzqz/divan) in code generation for benchmarks of generic functions. The simple example I gave is just a minimal reproduction of the issue.

**Comment by oli-obk** [comment] 2024-02-12 13:46
Yea, this is a duplicate of https://github.com/rust-lang/rust/issues/120949

**Comment by nvzqz** [comment] 2024-02-12 13:47
@oli-obk this seems similar but the error messages suggest to me that it's not a duplicate.

**Comment by oli-obk** [comment] 2024-02-12 14:03
Let's keep it open an check

**Comment by RalfJung** [comment] 2024-02-12 14:21
Yeah it's the same root cause; https://github.com/rust-lang/rust/pull/120970 adds a test.

**Closed** 2024-02-13 02:47 UTC
Labels: regression-from-stable-to-nightly, T-compiler, C-bug, A-const-eval
