### ISSUE TITLE
borrowing error

### ISSUE THREAD

**Issue by sartajsartaj** [rust-lang/rust#117145] opened 2023-10-24 22:44 UTC
// I tried the following code and it runs okay
fn main() {
  let mut num = 8;
  let num_ref = &mut num;
  *num_ref += 12;
  println!("{}", num_ref);    // line 5
  println!("{}", num);          // line 6
}

// BUT if I reverse the order of line 5 and line 6 like:

fn main() {
  let mut num = 8;
  let num_ref = &mut num;
  *num_ref += 12;
  println!("{}", num);             // line 6
  println!("{}", num_ref);       // line 5
}

// It gives error saying:
// cannot borrow `num` as immutable because it is also borrowed as mutable.

**Comment by JustusAdam** [comment] 2023-10-25 01:42
This is because `println!` implicitly borrows every argument immutably with `&`, which creates an immutable borrow that conflicts with mutable borrows that are live at the same time.

The second piece of the puzzle is that Rust uses what's called "Non Lexical Lifetimes", which is a fancy term that really just means that each `&` or `&mut` borrow is live (exists) until the last point where it is used.

In the first code the last use of the mutable borrow `num_ref` is in line 5. Thus after that statement `num_ref` borrow is dropped and the new `&` borrow in line 6 can be created without conflict.

In contrast the second example uses the `&mut` borrow for the last time in line 6. As a result it has to be live until then. This means it is also live in line 5 when the implicit, immutable borrow is created. This causes a conflict because mutable and immutable borrow cannot exist simultaneously.

**Comment by fmease** [comment] 2023-10-29 07:27
Closing as works as intended.

**Closed by fmease** 2023-10-29 07:27 UTC
