### ISSUE TITLE
Rustdoc doesn't show methods from nested derefs

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#40155] opened 2017-02-28 20:05 UTC
If `Foo: Deref<Target=Bar>` and `Bar: Deref<Target=Meow>` then on the page for `Foo`, rustdoc will show the methods from `Bar`, but not the methods from `Meow`.

**Comment by ollie27** [comment] 2017-02-28 20:21
dupe of #26207

**Closed** 2017-02-28 20:34 UTC
Labels: A-rustdoc
