### ISSUE TITLE
Recover and suggest wrapping in block in const generic value application

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#61175] opened 2019-05-25 11:20 UTC
cc @varkor @rust-lang/wg-diagnostics 

Say we have:
```rust
#![feature(const_generics)]

fn foo<const N: usize>() {}

fn bar() {
    foo::<1 + 1>();
}
```
the parser now greets you with:
```
error: expected one of `,` or `>`, found `+`
 --> src/lib.rs:6:13
  |
6 |     foo::<1 + 1>();
  |             ^ expected one of `,` or `>` here
```

It would be good if you got:
```
error: expected one of `,` or `>`, found `+`
 --> src/lib.rs:6:13
  |
6 |     foo::<1 + 1>();
  |             ^ expected one of `,` or `>` here
  |
  | help: wrap the expression in a block:
6 |     foo::<{1 + 1}>();
```

or some such.

**Comment by oli-obk** [comment] 2019-05-25 16:04
Won't attempting to fix this issue hit exactly the same issues that just allowing `foo::<1 + 1>();` hits?

**Comment by estebank** [comment] 2019-05-25 16:46
@oli-obk allowing blockless const expressions result in ambiguous grammar for the general case, but there's a subset that is unambiguous, and we get away with best effort attempts for the sake of diagnostics. Being able to parse almost any const expression with the exception of those involving greater than is great for error recovery, but would be terrible for the feature/grammar.

**Comment by varkor** [comment] 2020-10-02 01:42
https://github.com/rust-lang/rust/issues/70753 is a duplicate of this issue, but I'm going to close this one because it has less discussion.

**Closed by varkor** 2020-10-02 01:42 UTC
Labels: A-const-generics, A-diagnostics, A-suggestion-diagnostics, C-enhancement, F-const_generics, T-compiler, const-generics-bad-diagnostics, requires-nightly
