### ISSUE TITLE
Footnotes are squished together by rustdoc when there's no empty line between them

### ISSUE THREAD

**Issue by CJKay** [rust-lang/rust#100638] opened 2022-08-16 17:43 UTC
### Problem

Footnote lines, when written on adjacent lines, squish into a single footnote:

```rust
//! [^1]: Footnote A.
//! [^2]: Footnote B.
//! [^3]: Footnote C.
```

![Screenshot 2022-08-16 at 18 39 09](https://user-images.githubusercontent.com/1470499/184943780-fa48dd00-4cbe-4b98-883e-9ea76729a3f4.png)

### Steps

1. Copy-paste the following snippet at the top of a new module:

    ```rust
    //! Reference to footnotes A[^1], B[^2] and C[^3].
    //!
    //! [^1]: Footnote A.
    //! [^2]: Footnote B.
    //! [^3]: Footnote C.
    ```
2. Run `cargo doc`.
3. Observe that the footnotes have been incorrectly rendered as a single footnote.

### Notes

One workaround is to separate the footnotes with empty lines:

```rust
//! [^1]: Footnote A.
//! 
//! [^2]: Footnote B.
//! 
//! [^3]: Footnote C.
```

It's not pretty, though.

### Version

```text
cargo 1.64.0-nightly (b1dd22e66 2022-07-09)
release: 1.64.0-nightly
commit-hash: b1dd22e668af5279e13a071ad4b17435bd6bfa4c
commit-date: 2022-07-09
host: x86_64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.5.0 [64-bit]
```
```

**Comment by ehuss** [comment] 2022-08-16 18:33
I think this is somewhat working as intended.  Footnote definitions need to be separated by blank lines.

That is not ideal, and I think https://github.com/raphlinus/pulldown-cmark/issues/20 is the closest thing tracking this issue.

**Comment by GuillaumeGomez** [comment] 2022-08-23 09:42
This is the expected behaviour from commonmark as you can see [here](https://spec.commonmark.org/dingus/?text=Reference%20to%20footnotes%20A%5B%5E1%5D%2C%20B%5B%5E2%5D%20and%20C%5B%5E3%5D.%0A%0A%5B%5E1%5D%3A%20Footnote%20A.%0A%5B%5E2%5D%3A%20Footnote%20B.%0A%5B%5E3%5D%3A%20Footnote%20C.).

Closing then.

**Comment by CJKay** [comment] 2022-08-23 11:26
> This is the expected behaviour from commonmark as you can see [here](https://spec.commonmark.org/dingus/?text=Reference%20to%20footnotes%20A%5B%5E1%5D%2C%20B%5B%5E2%5D%20and%20C%5B%5E3%5D.%0A%0A%5B%5E1%5D%3A%20Footnote%20A.%0A%5B%5E2%5D%3A%20Footnote%20B.%0A%5B%5E3%5D%3A%20Footnote%20C.).
> 
> Closing then.

Hi @GuillaumeGomez, CommonMark does not support footnotes at all. RustDoc is very explicit that it does, so the behaviour of RustDoc's footnotes probably be based on whatever library it uses for Markdown parsing rather than actual CommonMark.

You can see from this simple example that [CommonMark does not support footnotes](https://pandoc.org/try/?text=Hello%2C+World%5B%5E1%5D%21%0A%0A%5B%5E1%5D%3A+The+world+is+big%21&to=html5&from=commonmark&standalone=false&citeproc=false&files=%5Bobject+Object%5D):

```markdown
Reference to footnote A[^1].

[^1]: Footnote A.
```

```html
<p>Reference to footnote A[^1].</p>
<p>[^1]: Footnote A.</p>
```

But [CommonMark with "extensions" does](https://pandoc.org/try/?text=Hello%2C+World%5B%5E1%5D%21%0A%0A%5B%5E1%5D%3A+The+world+is+big%21&to=html5&from=commonmark&standalone=false&citeproc=false&files=%5Bobject+Object%5D):

```html
<p>Hello, World<a href="#fn1" class="footnote-ref" id="fnref1"
role="doc-noteref"><sup>1</sup></a>!</p>
<section id="footnotes" class="footnotes footnotes-end-of-document"
role="doc-endnotes">
<hr />
<ol>
<li id="fn1"><p>The world is big!<a href="#fnref1" class="footnote-back"
role="doc-backlink">↩︎</a></p></li>
</ol>
</section>
```

**Comment by GuillaumeGomez** [comment] 2022-08-23 11:43
Oh I see, my apologies. Reopening the issue then.

**Comment by fmease** [comment] 2024-01-25 21:53
Triage: Still an issue.

**Comment by GuillaumeGomez** [comment] 2024-01-26 13:20
Taking a look.

**Closed** 2024-01-30 15:50 UTC
Labels: T-rustdoc, C-bug, A-rustdoc-ui
