### ISSUE TITLE
std::io::BufReader reads incorrect data

### ISSUE THREAD

**Issue by cepreu2github** [rust-lang/rust#27396] opened 2015-07-30 06:18 UTC
Steps to reproduce:
1) Download test TGA image at https://drive.google.com/file/d/0B7COwFox9fT8Wk9WSk5iMWRaRFk/view?usp=sharing .
2) Past this code in `bug_example.rs`:
```Rust
use std::fs::File;
use std::io::BufReader;
use std::io::Read;
use std::path::Path;

fn main() {
    let path = Path::new("colors.tga");
    let mut file_buf = BufReader::new(File::open(&path).unwrap());
    let mut file = File::open(&path).unwrap();
    let mut header_bytes: [u8; 18] = [0; 18];
    file_buf.read(&mut header_bytes);
    file.read(&mut header_bytes);
    let xsize = header_bytes[12] as usize + header_bytes[13] as usize*256;
    let ysize = header_bytes[14] as usize + header_bytes[15] as usize*256;
    println!("{}x{}", xsize, ysize);
    let mut canvas = vec![vec![0;ysize];xsize];
    for iy in 0..ysize{
        for ix in 0..xsize{
            let mut bytes: [u8; 4] = [0; 4];
            file.read(&mut bytes);
            let mut bytes_buf: [u8; 4] = [0; 4];
            file_buf.read(&mut bytes_buf);
            println!("file: {} {} {} {}", bytes[0], bytes[1], bytes[2], bytes[3]);
            println!(" buf: {} {} {} {}", bytes_buf[0], bytes_buf[1], bytes_buf[2], bytes_buf[3]);
            assert!(bytes[0] == bytes_buf[0]);
            assert!(bytes[1] == bytes_buf[1]);
            assert!(bytes[2] == bytes_buf[2]);
            assert!(bytes[3] == bytes_buf[3]);
            canvas[ix][iy] = bytes[2] as u32 + ((bytes[1] as u32) << (8*1)) + ((bytes[0] as u32) << (8*2));
        }
    }
}
```
3) `rustc bug_example.rs ; ./bug_example`
4) It FAILS! But it not supposed to do that, because File and BufReader reading the SAME file. There must be same data in buffers.

Tested it with Ubuntu 14.04 x64 and Rust 1.1.

**Comment by barosl** [comment] 2015-07-30 09:29
`std::io::Read::read` does not guarantee the buffer to be fully filled. You must check the return value of `read` to see how many bytes are actually read. In my system, `file.read()` and `file_buf.read()` return the different numbers before the assertion failure:

```
file: 255 0 0 255
 buf: 255 0 0 255
Ok(4) / Ok(4)
file: 255 0 0 255
 buf: 255 0 0 255
Ok(4) / Ok(4)
file: 255 0 0 255
 buf: 255 0 0 0
Ok(4) / Ok(2)
thread '<main>' panicked at 'assertion failed: bytes[3] == bytes_buf[3]', 1.rs:41
```

This behavior [is documented](http://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read), so is not a bug.

**Comment by barosl** [comment] 2015-07-30 09:56
To fulfil your original intention, you should create another adaptor using [`Read::take`](http://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.take) and consume it with [`Read::read_to_end`](http://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.read_to_end). You can replace your code snippet with something like this:

```rust
(&mut file).take(4).read_to_end(&mut bytes).unwrap();
(&mut file_buf).take(4).read_to_end(&mut bytes_buf).unwrap();
```

Also, as a side note, you'd better append `.unwrap()` whenever you deal with I/O, such as the code above. Of course, a proper error handling is more appropriate, but a simple `.unwrap()` is still much better than not handling at all. Actually, the compiler may have already warned you about this ("unused result which must be used").

**Comment by alexcrichton** [comment] 2015-07-30 15:48
I agree with @barosl's analysis, so closing as working as intended.

**Closed by alexcrichton** 2015-07-30 15:48 UTC
