### ISSUE TITLE
Error message usage of `_` is unclear

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#21042] opened 2015-01-12 20:45 UTC
Error messages use `_` a lot but it's meaning is never explained. This could be improved.

[Playpen](http://is.gd/T4XGJW)

``` rust
fn test(o: Option<i32>) {}

fn main() {
    let i = 7;
    test(i);
}
```

Error:

``` cmd
// What is `_` supposed to mean? Apparently integral value but it still seems meaningless...
... error ... expected `core::option::Option<i32>`, found `_`  ... found integral variable)
<anon>:5     test(i);
                  ^
error: aborting due to previous error
```
 ---

6/8/2017: updated error message:

```rust
error[E0308]: mismatched types
 --> <anon>:5:10
  |
5 |     test(i);
  |          ^ expected enum `std::option::Option`, found integral variable
  |
  = note: expected type `std::option::Option<i32>`
             found type `{integer}`

error: aborting due to previous error
```

**Comment by mdinger** [comment] 2015-02-15 00:50
The book is getting a note which seems related: https://github.com/rust-lang/rust/pull/22293

**Comment by steveklabnik** [comment] 2016-03-04 20:15
Triage: no change.

**Comment by Mark-Simulacrum** [comment] 2017-05-31 19:26
Nominating for discussion. What do we expect `_` to mean? Ideally we'd get a decision on that and then see if we follow that throughout the code; but at least a consensus on the first would be good.

I believe the current state is that `_` is an inference variable that we couldn't elaborate to anything more specific.

**Comment by nikomatsakis** [comment] 2017-06-08 21:01
In the particular case of this example, we now print `{integer}`:

```
rustc 1.17.0 (56124baa9 2017-04-24)
error[E0308]: mismatched types
 --> <anon>:5:10
  |
5 |     test(i);
  |          ^ expected enum `std::option::Option`, found integral variable
  |
  = note: expected type `std::option::Option<i32>`
             found type `{integer}`

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment] 2017-06-08 21:02
Currently, `_` is used to mean (roughly) "some type we've not inferred yet". Perhaps we could use this `{}` convention for that? e.g., `{TBD}`?

**Comment by nikomatsakis** [comment] 2017-06-08 21:03
I will say that we've been back-and-forth on this point a lot. the primary advantage of `_` here is that it can be copied-and-pasted into user's code and has roughly the same meaning ("infer this"). However, we have many types where that cannot be done (including `{integer}`), so I'm not sure how important of a principle that really is.

**Comment by mdinger** [comment] 2017-06-08 22:18
FWIW, I think the it is definitely better than it used to be. I'm not sure what `{}` is though.

**Comment by nikomatsakis** [comment] 2017-06-09 21:36
@mdinger it's not anything, that's the point. :) It's just a way for us to insert "meta" stuff.

**Comment by nikomatsakis** [comment] 2017-07-06 21:05
I'm inclined to close this issue, absent a particular suggestion. The specific case in question has been improved and we don't know how to do much better. In any case, we have existing issues with more discussion, hence closing as a duplicate of https://github.com/rust-lang/rust/issues/25633 and https://github.com/rust-lang/rust/issues/40985.

**Closed by nikomatsakis** 2017-07-06 21:05 UTC
Labels: A-diagnostics, I-nominated, T-compiler
