### ISSUE TITLE
Show library version number in the rust doc

### ISSUE THREAD

**Issue by gbersac** [rust-lang/rust#28076] opened 2015-08-28 22:10 UTC
When I read the documentation of the rust standard library from google, I don't know to which version of rust it refers. It could be great to have a footer with the version and a text which appear when we put our cursor on the rust logo which display the version of the library this doc refer to.

That mean improving the documentation compilator of rust.

**Comment by steveklabnik** [comment] 2015-09-03 21:02
this is a duplicate of https://github.com/rust-lang/rust/issues/24336. thanks for filing!

**Closed by steveklabnik** 2015-09-03 21:02 UTC
