### ISSUE TITLE
Trait bound not satisfied when using trait constant in array expression

### ISSUE THREAD

**Issue by gardell** [rust-lang/rust#64866] opened 2019-09-28 07:27 UTC
The following code fails on `nightly`/`beta`/`stable`

```Rust
trait Trait {
    const SIZE: usize;
}

fn foo<T>(v: &T) where T: Trait {
    [0i32; <T as Trait>::SIZE];
}
```
with the following error:
```
error[E0277]: the trait bound `T: Trait` is not satisfied
 --> src/lib.rs:6:12
  |
6 |     [0i32; <T as Trait>::SIZE];
  |            ^^^^^^^^^^^^^^^^^^ the trait `Trait` is not implemented for `T`
  |
  = help: consider adding a `where T: Trait` bound
note: required by `Trait::SIZE`
 --> src/lib.rs:2:5
  |
2 |     const SIZE: usize;
  |     ^^^^^^^^^^^^^^^^^^
```

See playground at https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=94152b99b38a0faec9ef4231543cdc94

This is similar to the issues https://github.com/rust-lang/rust/issues/61021 and https://github.com/rust-lang/rust/issues/43580

However, the above compiles with a change of the offending line to
```Rust
vec![0i32; <T as Trait>::SIZE];
```

Suggesting that it is specific to the constant expression being used in the array expression?

**Comment by Centril** [comment] 2019-09-28 07:42
Duplicate of https://github.com/rust-lang/rust/issues/43408.

**Closed by Centril** 2019-09-28 07:42 UTC
Labels: A-lazy-normalization
