### ISSUE TITLE
edge-case in type inference for arithmetic expressions

### ISSUE THREAD

**Issue by swiftcoder** [rust-lang/rust#34620] opened 2016-07-03 00:17 UTC
Arithmetic expressions trailing a conditional expression are not accepted as the result statement for a block.

For example, the following function compiles fine:
```rust
fn edge_case() -> u32 {
    60 * if 1 > 2 {
        1
    } else {
        2
    }
}
```

but the next function fails, even though they appear semantically equivalent:

```rust
fn edge_case() -> u32 {
    if 1 > 2 {
        1
    } else {
        2
    } * 60
}
```

The errors in this case are:

```bash
src/main.rs:15:9: 15:10 error: mismatched types:
 expected `()`,
    found `_`
(expected (),
    found integral variable) [E0308]
src/main.rs:15         1
                       ^
src/main.rs:15:9: 15:10 help: run `rustc --explain E0308` to see a detailed explanation
src/main.rs:17:9: 17:10 error: mismatched types:
 expected `()`,
    found `_`
(expected (),
    found integral variable) [E0308]
src/main.rs:17         2
                       ^
src/main.rs:17:9: 17:10 help: run `rustc --explain E0308` to see a detailed explanation
src/main.rs:18:7: 18:11 error: type `_` cannot be dereferenced
src/main.rs:18     } * 60
                     ^~~~
error: aborting due to 3 previous errors
```

However, if I assign the expression to a variable, inference once again succeeds:
```rust
fn edge_case() -> u32 {
    let n = if 1 > 2 {
        1
    } else {
        2
    } * 60;
    n
}
```

Any idea what is up with this edge case?

**Comment by TimNN** [comment] 2016-07-03 07:46
If I remember correctly this is behaviour is deliberate: When starting to parse an if statement, the parser has to decide whether it should be parsed as a statement (the type of which is `()`) or as an expression.

So in you first and third case the if statement is parsed as an expression but in you second case it is parsed as a statement.

Otherwise this looks like a duplicate of #32368, which also has a more detailed explanation.

**Comment by arielb1** [comment] 2016-07-03 08:50
duplicate of #32368

**Closed by arielb1** 2016-07-03 08:50 UTC
