### ISSUE TITLE
Warning "variant is never used" is confusing when programmer just woke up

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#44565] opened 2017-09-14 12:55 UTC
I was changing some code from integer constants to a proper enum and was greeted by the following warning:

```
   Compiling script v0.0.1 (file:///Users/nox/src/servo/components/script)
warning: variant is never used: `HaveMetadata`
  --> /Users/nox/src/servo/components/script/dom/htmlmediaelement.rs:88:5
   |
88 |     HaveMetadata = HTMLMediaElementConstants::HAVE_METADATA as u8,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(dead_code)] on by default
```

The warning sounded weird to me because I was pattern-matching on that damn variant in various places of the code; but I was pointed out to the fact that I wasn't actually *creating* that value.

Maybe the warning should be rewritten to explicitly mention value creation?

Cc @arielb1

**Comment by arielb1** [comment] 2017-09-14 12:57
cc @Manishearth that looks like your thing

**Comment by ollie27** [comment] 2017-09-14 14:00
duplicate of #19140

**Comment by steveklabnik** [comment] 2017-09-14 14:21
Yup! Closing in favor of that.

**Closed by steveklabnik** 2017-09-14 14:21 UTC
Labels: A-lint
