### ISSUE TITLE
Internal compiler error when there is no enclosing scope.

### ISSUE THREAD

**Issue by vamsikal3** [rust-lang/rust#38979] opened 2017-01-11 01:30 UTC
This snippet gives the following error:

```Rust
const TEN : num::bigint::BigInt = match num::bigint::ToBigInt::to_bigint(&10) {
                                                       Some(x) => x,
                                                       None => panic!("Could not create bigint."),
                                                    };
```
```
vamsi@vamsi-laptop:~/learn/project_euler/257_to_384/problem_323$ cargo run
   Compiling problem_323 v0.1.0 (file:///home/vamsi/learn/project_euler/257_to_384/problem_323)
error: internal compiler error: ../src/librustc_typeck/check/dropck.rs:284: no enclosing scope found for scope: CodeExtent(10/Misc(NodeId(22)))
 --> src/main.rs:8:42
  |
8 |                                     Some(x) => x,
  |                                          ^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:383
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `problem_323`.

To learn more, run the command again with --verbose.

```

**Comment by arielb1** [comment] 2017-01-11 12:06
minified:

```Rust
const TEN : &'static usize = match &10 {
    x => x,
};

fn main() {}
```

**Comment by arielb1** [comment] 2017-01-11 12:08
cc #38520.

**Comment by oli-obk** [comment] 2017-01-26 15:32
dupe of #29093

**Comment by steveklabnik** [comment] 2017-01-26 16:43
closing as duplicate

**Closed by steveklabnik** 2017-01-26 16:43 UTC
Labels: I-ICE
