### ISSUE TITLE
segfault during stage2 build of dist x86_64-apple-darwin xcode 7.3

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#48866] opened 2018-03-09 08:00 UTC
So far not reproducible on newer xcode versions.

cc @varkor @kennytm 

https://github.com/rust-lang/rust/commit/52dec0e1c9e0fe5bbbe81385531e69c2c46ef56e obviously did not fix it and can be reverted.

Happens inside

```
rustc::ich::hcx::_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc..ich..hcx..StableHashingContext$LT$$u27$a$GT$$GT$$u20$for$u20$syntax_pos..span_encoding..Span$GT$::hash_stable::h069c687f17acced0 + 760
```

whenever it happens, but it's random during which crate's compilation it happens or whether it occurs at all.

Guesses so far are

* alignment issues with `Span`, which is `repr(packed)` and only has a `u32` field
* something to do with the `CACHE` thread_local (just because miri touched statics)

Is is possible to produce better stacktraces (with line info e.g.) on macs?

**Comment by kennytm** [comment] 2018-03-09 08:11
Interestingly this seems to be quite deterministic on #48326. The bug happened twice so far and only on that PR (besides the miri PR).

**Comment by pietroalbini** [comment] 2018-03-09 17:54
Also happened on #48757

**Comment by pietroalbini** [comment] 2018-03-09 19:12
Both #48757 ([log](https://api.travis-ci.org/v3/job/351377755/log.txt)) and #48388 ([log](https://api.travis-ci.org/v3/job/351415136/log.txt)) failed building the first two crates of cargo stage2 in parallel, receiving a SIGSEGV on both the rustc processes.

**Comment by kennytm** [comment] 2018-03-09 20:16
[Reproduced on Travis](https://travis-ci.org/rust-lang/rust/builds/351447033) and the offending artifact should have been uploaded to S3.

**Comment by kennytm** [comment] 2018-03-09 21:18
@oli-obk 

From the stack trace it is obviously caused by the `CACHE` TLS. The segfault happens during initialization of the `CACHE` i.e. when the HashMap was first created.

The instruction throwing the error is 

```
(lldb) fr sel 0
frame #0: 0x000000010162c7e8 librustc-863c36ebb34cad14.dylib`rustc::ich::hcx::_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc..ich..hcx..StableHashingContext$LT$$u27$a$GT$$GT$$u20$for$u20$syntax_pos..span_encoding..Span$GT$::hash_stable::h8d48a4ca8ec2db40 + 760
librustc-863c36ebb34cad14.dylib`rustc::ich::hcx::_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc..ich..hcx..StableHashingContext$LT$$u27$a$GT$$GT$$u20$for$u20$syntax_pos..span_encoding..Span$GT$::hash_stable::h8d48a4ca8ec2db40:
->  0x10162c7e8 <+760>: movdqa xmm0, xmmword ptr [rax]
    0x10162c7ec <+764>: movdqa xmm1, xmmword ptr [rax + 0x10]
    0x10162c7f1 <+769>: mov    rcx, -0x1
    0x10162c7f8 <+776>: movq   xmm2, rcx
```

where `rax` is **not aligned on the 16-byte boundary**. Thus the segfault is caused by unaligned access in the `movdqa` instruction.

```
(lldb) x $rax
0x104211488: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x104211498: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
```

The `rax` should be the address of the CACHE. I don't know why it needs to be aligned, and why it isn't aligned in stage2.

If you've got a Mac you may try to debug it yourself. There's no line info though.

* Stage 1 artifact: https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds-alt/7ad66eb8422bc359b0c8a1564dd9339380a6985f/stage1.xz
* Stage 2 artifact: https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds-alt/7ad66eb8422bc359b0c8a1564dd9339380a6985f/stage2.xz

**Comment by kennytm** [comment] 2018-03-10 06:30
Now #48891 has been merged, if we don't see any more errors like this next week we may close this issue as no-longer-reproducible.

**Comment by oli-obk** [comment] 2018-03-10 08:34
I'll still check why it isn't aligned. His is something I can check on Linux

**Comment by oli-obk** [comment] 2018-03-22 09:25
I give up. There's absolutely no reason the **address** of `CACHE` should ever be stored without alignment.

**Comment by alexcrichton** [comment] 2018-04-10 14:32
I think this was fixed with the xcode 9 updates, so presuambly this was a linker bug?

**Closed by alexcrichton** 2018-04-10 14:32 UTC
Labels: A-spurious, C-bug, O-macos, T-compiler
