### ISSUE TITLE
Release builds using AVX code produce incorrect output

### ISSUE THREAD

**Issue by vladglv** [rust-lang/rust#54583] opened 2018-09-26 04:58 UTC
# Code 

```
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;

fn main() {
    unsafe {
        let f = _mm256_set_pd(2.0, 2.0, 2.0, 2.0);
        let r = _mm256_mul_pd(f, f);

        println!("{:?}", r);
    }
}
```
# Output

The expected output is 
```
__m256d(4.0, 4.0, 4.0, 4.0)
```
The actual output is
```
__m256d(4.0, 4.0, 0.0, 0.0)
```

# Notes
- The code built in debug mode produces the expected result. This issue only occurs in a release build.
- Using `_mm` instead of `_mm256` results in correct output in both debug and release mode.
- Code using only `_mm` or `_mm256` yields the same performance (I have another piece of code for that. I can provide it if needed).

# Versions
The issue can be reproduced with 1.30.0-nightly (2018-09-24), 1.30.0-beta.7, 1.29.0.

**Comment by nicokoch** [comment] 2018-09-26 08:28
shouldn‘t be a ’#[target_feature(enable = "avx2“)]’ in there?

**Comment by rkruppe** [comment] 2018-09-26 10:14
Looks like a duplicate of #50154 at a glance.

**Comment by theotherphil** [comment] 2018-10-03 20:12
I just ran into this issue and spent quite a while getting very confused. It's very surprising that code using AVX2 intrinsics compiles and then behaves nonsensically without the correct target feature attribute.

**Closed** 2018-10-21 01:06 UTC

**Comment by andersk** [comment] 2018-12-22 11:35
This test case still produces the incorrect result with `-C opt-level=3` (or Cargo’s `--release`), in both 1.31.1 and 1.33.0-nightly (e40548bc4 2018-12-21).

[Playground link](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=066218cc6a714cf3b8b5bec7abb92bcd).

**Comment by nikic** [comment] 2018-12-22 12:10
Yes, the fix was reverted. I don't think it's necessary to reopen this one, as the general issue is already tracked at #50154. This is just one more manifestation of the same problem.
