### ISSUE TITLE
DWARF info for `static` vars in lib crates has stopped being produced reliably in LTO builds

### ISSUE THREAD

**Issue by cbiffle** [rust-lang/rust#90357] opened 2021-10-28 00:42 UTC
As of the 2021-09-23 nightly, rustc has stopped producing debug output for variables in a specific combination of circumstances:

- The variable is `static`
- It is defined in a lib crate.
- The lib crate is included in a bin crate.
- The bin crate is built with `lto = true`.

We noticed this after bumping past 09-23 to the 2021-10-27 nightly, when our debugger broke. The static is still being included in the ELF output (both allocated space, and represented correctly in the symtab), but is missing from DWARF. Bisecting indicates 2021-09-23 as the culprit (09-22 works).

Here is a repro case that I've reduced that works on linux x86-64, at least, and probably other DWARF platforms.

https://github.com/cbiffle/rustc-dwarf-regression-repro

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by cuviper** [comment] 2021-11-19 18:31
I think this may be a duplicate of #90301. Please test on a current nightly, and when `1.57.0-beta.4` goes out it should have the backport via #90938.

It's still possible that #89041 introduced its own problem, but maybe it just exacerbated the LLVM issue.

**Comment by pnkfelix** [comment] 2021-11-22 19:46
@cuviper it seems like it still reproduces to me on nightly.

```
% rustup show active-toolchain
nightly-x86_64-unknown-linux-gnu (directory override for '/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro')
% rustc --version
rustc 1.58.0-nightly (65f3f8b22 2021-11-21)
% cargo clean
% cargo build --release --verbose
   Compiling nodwarfrepro v0.1.0 (/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro)
     Running `rustc --crate-name nodwarfrepro --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-typ\
e lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C debuginfo=2 -C metadata=f2ccefc4246296b8 -C extra-filename=-\
f2ccefc4246296b8 --out-dir /media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps -L dependency\
=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps`
     Running `rustc --crate-name nodwarfrepro --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-ty\
pe bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 -C metadata=f4b2592c51b39d90 -C extra-filename=-f4b2592c51b39d90 --out\
-dir /media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps -L dependency=/media/pnkfelix/Rust/\
rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps --extern nodwarfrepro=/media/pnkfelix/Rust/rust-90357/objdir-\
dbgopt/rustc-dwarf-regression-repro/target/release/deps/libnodwarfrepro-f2ccefc4246296b8.rlib`
    Finished release [optimized + debuginfo] target(s) in 2.55s
% dwarfdump target/release/nodwarfrepro | grep THE_STATIC
% 
```

**Comment by pnkfelix** [comment] 2021-11-22 19:54
It looks to me like the problem still reoccurs on the current nightly:

```
% rustup override set nightly-2021-11-22
info: using existing install for 'nightly-2021-11-22-x86_64-unknown-linux-gnu'
info: override toolchain for '/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro' set to 'nightly-2021-11-22-x86_64-unknown-linux-gnu'

  nightly-2021-11-22-x86_64-unknown-linux-gnu unchanged - rustc 1.58.0-nightly (65f3f8b22 2021-11-21)

% rustup show active-toolchain
nightly-2021-11-22-x86_64-unknown-linux-gnu (directory override for '/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro')
% rustc --version
rustc 1.58.0-nightly (65f3f8b22 2021-11-21)
% cargo clean
% cargo build --release --verbose
   Compiling nodwarfrepro v0.1.0 (/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro)
     Running `rustc --crate-name nodwarfrepro --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C debuginfo=2 -C metadata=f2ccefc4246296b8 -C extra-filename=-f2ccefc4246296b8 --out-dir /media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps -L dependency=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps`
     Running `rustc --crate-name nodwarfrepro --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 -C metadata=f4b2592c51b39d90 -C extra-filename=-f4b2592c51b39d90 --out-dir /media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps -L dependency=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps --extern nodwarfrepro=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps/libnodwarfrepro-f2ccefc4246296b8.rlib`
    Finished release [optimized + debuginfo] target(s) in 2.55s
% dwarfdump target/release/nodwarfrepro | grep THE_STATIC
% 
```

<details>

<summary>For completeness, here is a transcript showing the behavior that is expected, from nightly-2021-09-22</summary>

```
% rustup override set nightly-2021-09-22
info: using existing install for 'nightly-2021-09-22-x86_64-unknown-linux-gnu'
info: override toolchain for '/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro' set to 'nightly-2021-09-22-x86_64-unknown-linux-gnu'

  nightly-2021-09-22-x86_64-unknown-linux-gnu unchanged - rustc 1.57.0-nightly (ac2d9fc50 2021-09-21)

% rustup show active-toolchain
nightly-2021-09-22-x86_64-unknown-linux-gnu (directory override for '/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro')
% rustc --version
rustc 1.57.0-nightly (ac2d9fc50 2021-09-21)
% cargo clean
% cargo build --release --verbose
   Compiling nodwarfrepro v0.1.0 (/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro)
     Running `rustc --crate-name nodwarfrepro --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C debuginfo=2 -C metadata=f2ccefc4246296b8 -C extra-filename=-f2ccefc4246296b8 --out-dir /media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps -L dependency=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps`
     Running `rustc --crate-name nodwarfrepro --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=2 -C metadata=f4b2592c51b39d90 -C extra-filename=-f4b2592c51b39d90 --out-dir /media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps -L dependency=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps --extern nodwarfrepro=/media/pnkfelix/Rust/rust-90357/objdir-dbgopt/rustc-dwarf-regression-repro/target/release/deps/libnodwarfrepro-f2ccefc4246296b8.rlib`
    Finished release [optimized + debuginfo] target(s) in 2.78s
% dwarfdump target/release/nodwarfrepro | grep THE_STATIC
                        DW_AT_name                  THE_STATIC
                        DW_AT_linkage_name          _ZN12nodwarfrepro10THE_STATIC17he3077d0fbb05bed3E
global die-in-sect 0x00000089, cu-in-sect 0x00000071, die-in-cu 0x00000023, cu-header-in-sect 0x00000066 'THE_STATIC'
name at offset 0x000000d1, length   10 is 'THE_STATIC'
name at offset 0x00000102, length   49 is '_ZN12nodwarfrepro10THE_STATIC17he3077d0fbb05bed3E'
% 
```

</details>

**Comment by cbiffle** [comment] 2022-04-04 17:31
This appears to still be reproducing as of `rustc 1.61.0-nightly (9c06e1ba4 2022-03-29)`; we're stuck on `2021-09-23` because basically anything newer breaks our debugger.

**Comment by cbiffle** [comment] 2022-04-04 20:18
So, after working out how to build a toolchain that includes our cross target and rust-lld and whatnot locally, I've tested today's mainline d5139f44690e7765df801ca33a7f627d128ac9e2 with a revert for PR #89041, commit d5de680e20def848751cb3c11e1182408112b1d3 -- which @luqmana had previously identified as the likely culprit.

I can confirm that DWARF output for our statics on thumbv7em and kin is restored after that commit is reverted. Shall I prepare a PR?

**Closed** 2022-07-16 02:59 UTC
Labels: A-debuginfo, P-high, T-compiler, regression-from-stable-to-stable, C-bug
