### ISSUE TITLE
rustdoc Trait impl list is strangely ordered since 1.19

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#42963] opened 2017-06-29 06:49 UTC
Compare:

* https://doc.rust-lang.org/1.18.0/std/cmp/trait.Eq.html
* https://doc.rust-lang.org/1.19.0/std/cmp/trait.Eq.html

In the beta and nightly docs, the impl for `fn`, tuples, arrays and primitives appear randomly. There does not seem to be any problem beyond the `libcore` mess. 

Similar problem in:

* https://doc.rust-lang.org/1.18.0/std/primitive.array.html (looks good, impl follows declaration order)
* https://doc.rust-lang.org/1.19.0/std/primitive.array.html (randomly ordered for each group of traits)
* https://doc.rust-lang.org/1.19.0/std/primitive.array.html

* https://doc.rust-lang.org/1.19.0/std/vec/struct.Vec.html

...

**Comment by QuietMisdreavus** [comment] 2017-09-29 01:58
Duplicate of https://github.com/rust-lang/rust/issues/40905 (this has better links though since you had the opportunity to get versioned links `>_>`)

**Closed by QuietMisdreavus** 2017-09-29 01:58 UTC
Labels: A-rustdoc, C-bug, T-dev-tools
