### ISSUE TITLE
indirect restrictions on Self in trait where clauses are not available when the trait is used as a bound

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#25409] opened 2015-05-14 17:57 UTC
``` rust
trait Bound where u8: Into<Self> {}

// u8: Into<Self> is enforced here:
// error: the trait `core::convert::From<u8>` is not implemented for the type `u16`  [E0277]
impl Bound for u16 {}
// ^~~~~~~~~~~~~~~~~~

fn test<B: Bound>() -> B {
    // but the compiler seems to be unaware of it here:
    // error: the trait `core::convert::From<u8>` is not implemented for the type `B` [E0277]
    0u8.into()
    //  ^~~~~~
}
```

As you can see, the compiler enforces the bound in the traits where clause when implementing the trait, but seems to be unaware of it when the trait is used itself as a bound.

I don't know if the traits where clause should be valid or not, however if it is valid, the compiler should be aware of the additional information provided by it.

At least if I haven't completely misunderstood something.

**Comment by arielb1** [comment] 2015-07-27 19:05
This is a known issue - only supertraits are elaborated. This is required to ensure a trait-ref elaborates only finitely many others. As a workaround, you can always duplicate the where-clause.

**Comment by TimNN** [comment] 2015-07-27 19:21
Thank you for the information and the suggested workaround, I don't think that idea crossed my mind at the time. Now if I could only remember what I needed this for in the first place...

**Comment by brson** [comment] 2017-01-26 17:32
This is what stable says today about the test case:

```
rustc 1.14.0 (e8a012324 2016-12-16)
error: main function not found

error[E0277]: the trait bound `Self: std::marker::Sized` is not satisfied
 --> <anon>:1:1
  |
1 | trait Bound where u8: Into<Self> {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Sized` is not implemented for `Self`
  |
  = help: consider adding a `where Self: std::marker::Sized` bound
  = note: required by `std::convert::Into`

error[E0277]: the trait bound `B: std::convert::From<u8>` is not satisfied
  --> <anon>:8:1
   |
8  | fn test<B: Bound>() -> B {
   | ^ the trait `std::convert::From<u8>` is not implemented for `B`
   |
   = help: consider adding a `where B: std::convert::From<u8>` bound
   = note: required because of the requirements on the impl of `std::convert::Into<B>` for `u8`
   = note: required by `Bound`

error: aborting due to 2 previous errors
```

**Comment by brson** [comment] 2017-01-26 17:34
Lang team can you P-tag?

**Comment by brson** [comment] 2017-01-26 17:34
NVM P-low

**Comment by jonas-schievink** [comment] 2017-01-26 18:28
Dupe of #20671 ?

**Comment by Mark-Simulacrum** [comment] 2017-05-20 02:40
I think so. Closing as a duplicate of #20671.

**Closed by Mark-Simulacrum** 2017-05-20 02:40 UTC
Labels: A-traits, A-typesystem, P-low, T-lang
