### ISSUE TITLE
Segfault involving mem::uninitialized using optimizations

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust#22581] opened 2015-02-20 15:36 UTC
I stumbled upon some behaviour, which I had not expected using `mem::uninitialized`. It has to do with [this commit](https://github.com/aepsil0n/carboxyl/commit/5d848f4cefc6cdbbb91e2c2aa65af208576f8fec). The essence is, that before the change there was a struct field that remained uninitialized at first and was only set later in the same function. When I tried to run a benchmark using this code compiled with `opt-level=3`, the program segfaulted.

Now I am perfectly aware, that there are a lot of reasons for why it is dangerous to do that and I am also fine using an `Option` here. Nonetheless, there are two reasons, why I am still reporting this as an issue:

- There were no runtime failures after I switched to using an `Option`, so I suspect that the code should not have crashed trying to drop uninitialized memory during unwinding.
- The error only occurred in the benchmarks, i.e. with `opt-level=3`. Manually compiling the same benchmark without optimizations was successful.

Given these observations I wonder, whether there might be a problem with the optimization passes here. I tried to reproduce this issue in a minimal example but did not succeed. (Sorry for that :/)

**Comment by alexcrichton** [comment] 2015-02-20 16:39
Unfortunately this is largely just where undefined behavior comes into play. Any read of undefined memory in LLVM will get propagated and then use of that read can trigger undefined behavior. In this sense the "undefined behavior" is that the optimizations assumed and invariant that was not true, producing code that segfaulted.

In general bugs which only appear with optimizations turned on are triggered by some form of undefined behavior in the code (such as using uninitialized memory in this case). It may be a bug sometimes, but this sounds like the former case. As a result, closing as working as intended.

**Closed by alexcrichton** 2015-02-20 16:39 UTC

**Comment by aepsil0n** [comment] 2015-02-20 16:54
Ah, good to know. Thanks for the feedback!
