### ISSUE TITLE
Error verifying hash from nightly build

### ISSUE THREAD

**Issue by qrush** [rust-lang/rust#21456] opened 2015-01-21 04:49 UTC
Looks like it's failing on using the rustup script:

https://gist.github.com/qrush/0dfe23da2d6f697c61d9

Some basic debugging with the `sha256` download available now:

```
% more ~/Downloads/rust-nightly-x86_64-apple-darwin.tar.gz.sha256 
7856dceb634065333f854dd7c3b8030c924c2bd7a3a7a2e2543499711bbbba90  rust-nightly-x86_64-apple-darwin.tar.gz

% curl -I https://static.rust-lang.org/dist/rust-nightly-x86_64-apple-darwin.tar.gz
HTTP/1.1 200 OK
Content-Type: application/x-tar
Content-Length: 111760958
Connection: keep-alive
Date: Tue, 20 Jan 2015 20:02:18 GMT
Last-Modified: Mon, 19 Jan 2015 21:13:29 GMT
ETag: "f0467a3cd7a0a2997c9fdfbccb2fe1fe-8"
Server: AmazonS3
Age: 31369
X-Cache: Hit from cloudfront
Via: 1.1 ef3c3da2db0b6d8b04cbafe19cb6a5d7.cloudfront.net (CloudFront)
X-Amz-Cf-Id: VqnIja-jOItZCyoLBubt-vxQ0TGUt7qEiKFISIfgAqvTKbkfMsWbUA==

% wget https://static.rust-lang.org/dist/rust-nightly-x86_64-apple-darwin.tar.gz
--2015-01-20 23:46:49--  https://static.rust-lang.org/dist/rust-nightly-x86_64-apple-darwin.tar.gz
Resolving static.rust-lang.org... 54.192.38.134, 54.192.36.136, 54.192.39.190, ...
Connecting to static.rust-lang.org|54.192.38.134|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 111760958 (107M) [application/x-tar]
Saving to: ‘rust-nightly-x86_64-apple-darwin.tar.gz’

100%[====================================================================================================================>] 111,760,958  740KB/s   in 1m 58s 

2015-01-20 23:48:48 (923 KB/s) - ‘rust-nightly-x86_64-apple-darwin.tar.gz’ saved [111760958/111760958]

% shasum -a 256 rust-nightly-x86_64-apple-darwin.tar.gz 
696589a4ecb20448007d3885c1b2e68db59042b77658bb7decff577c590b58f4  rust-nightly-x86_64-apple-darwin.tar.gz

```

Not good. So it seems like the sha is wrong, or the download is corrupted. Not sure what's going on here. Maybe one of the files is out of sync? Is there a validation process or something missing here? That all of this pipes through `sudo sh` makes me really nervous.

**Comment by bharadwaj6** [comment] 2015-01-21 12:59
It's working now. :)

**Comment by Gankro** [comment] 2015-01-21 19:50
Closing as resolved...?

**Comment by qrush** [comment] 2015-01-21 19:50
It doesn't seem like it's resolved. Why did this happen?

**Comment by Gankro** [comment] 2015-01-21 20:00
Butts.

We have some serious synching issues with our static file hosting, if I had to make a guess for the source of the problem.

**Comment by brson** [comment] 2015-01-21 20:07
Dupe of https://github.com/rust-lang/rust/issues/21239

**Closed by brson** 2015-01-21 20:07 UTC
