### ISSUE TITLE
Tracking issue for impl trait in const/static/let

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#44686] opened 2017-09-18 21:27 UTC
This is a tracking issue for `impl Trait` in the types of consts, statics, and lets, a part of rust-lang/rfcs#2071

Blocking stabilization:

- [ ] Implement
- [ ] Document

**Comment by nikomatsakis** [comment] 2017-10-21 17:08
I am closing this as a duplicate of https://github.com/rust-lang/rust/issues/34511

**Closed by nikomatsakis** 2017-10-21 17:08 UTC
Labels: A-impl-trait, A-traits, A-typesystem, C-tracking-issue, T-lang

**Comment by Centril** [comment] 2019-07-28 06:41
New tracking issue: https://github.com/rust-lang/rust/issues/63065
