### ISSUE TITLE
invalid "cannot return value referencing local variable" in current nightly

### ISSUE THREAD

**Issue by xMAC94x** [rust-lang/rust#57146] opened 2018-12-27 13:06 UTC
while compiling, rust throws an error "cannot return value referencing local variable" which is invalid in my opinion. It did not do this in `nightly of Dec02 2018`, but in current nightly it does.

I tried this code:

I compiled the veloren source code located at gitlab: https://gitlab.com/veloren/game (note: recently rust changes div_euc to div_euclid and mod_euc to rem_euclid, you have to adjust it before the bug will show up.)
The important part is this function:
```rust
    pub fn get_sample(&self, from: Vec3<VoxAbs>, to: Vec3<VoxAbs>) -> Result<ChunkSample, ChunkSampleError> {
        let mut map = HashMap::new();
        let chunk_from = terrain::voxabs_to_voloffs(from, self.vol_size);
        let chunk_to = terrain::voxabs_to_voloffs(to, self.vol_size);
        let lock = self.pers.read();
        for x in chunk_from.x..chunk_to.x + 1 {
            for y in chunk_from.y..chunk_to.y + 1 {
                for z in chunk_from.z..chunk_to.z + 1 {
                    let key = Vec3::new(x, y, z);
                    let cc = lock.get(&key).map(|v| v.clone());
                    if let Some(cc) = cc {
                        if cc
                            .data_try()
                            .take()
                            .map(|value| map.insert(key, Arc::new(value)))
                            .is_none()
                        {
                            debug!("Cannot get lock: {}", &key);
                            return Err(ChunkSampleError::CannotGetLock { key });
                        }
                        let _ = map.get(&key).unwrap();
                    } else {
                        debug!("Chunk does not exist: {}", &key);
                        return Err(ChunkSampleError::ChunkMissing { key });
                    }
                }
            }
        }
        Ok(ChunkSample::new_internal(self.vol_size, from, to, map))
    }
```
The function tries to aquire multiple locks, and if all locks are aquired it will return them, otherwise it will fail.
The last line, where we return OK(...) is borrowing from "if cc". my guess is, that the borrowing is detected via the map.insert inside the if. however key is newly created before and the Arc is also new created. This is why in my opinion the error is invalid.

I expected to see this happen: "compilation successfull"

Instead, this happened: 
```rust
error[E0515]: cannot return value referencing local variable `cc`
   --> common/src/terrain/chunk_mgr.rs:126:9
    |
109 |                         if cc
    |                            -- `cc` is borrowed here
...
126 |         Ok(ChunkSample::new_internal(self.vol_size, from, to, map))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returns a value referencing data owned by the current function

error: aborting due to previous error

For more information about this error, try `rustc --explain E0515`.
error: Could not compile `common`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Meta

The error is reproducible on multiple computers from me, and other people had the same problem. i think mostly linux-64bit.
nightly `2018-12-02` compiles this code fine without any problems

`rustc --version --verbose`:
```bash
rustc 1.33.0-nightly (a7be40c65 2018-12-26)
binary: rustc
commit-hash: a7be40c65ae8ace467c9c40b0a22642973e31a13
commit-date: 2018-12-26
host: x86_64-unknown-linux-gnu
release: 1.33.0-nightly
LLVM version: 8.0
```

Backtrace:

**Comment by jonas-schievink** [comment] 2019-01-26 23:17
@xMAC94x which commit of veloren have you used? Current master doesn't build because of a type error.

**Comment by mati865** [comment] 2019-08-22 14:49
@xMAC94x can you provide step by step instructions how to reproduce this bug?

**Comment by steveklabnik** [comment] 2019-12-25 15:48
Triage: going to close this one as "can't reproduce." @xMAC94x if you're still seeing this, please provide a reproduction that works today!

**Closed by steveklabnik** 2019-12-25 15:48 UTC
Labels: A-borrow-checker
