### ISSUE TITLE
Closure inference is destroyed by wrappers

### ISSUE THREAD

**Issue by ebfull** [rust-lang/rust#29834] opened 2015-11-14 17:52 UTC
This doesn't work:

```rust
struct Wrapper<F>(F);
struct Foo;

impl Foo {
    fn stuff(self) { }
}

fn api<F: Fn(Foo)>(f: Wrapper<F>) { }

fn main() {
    api(Wrapper(|b| {
        b.stuff();
    }))
}
```

yet without the wrapper it works just fine:

```rust
struct Foo;

impl Foo {
    fn stuff(self) { }
}

fn api<F: Fn(Foo)>(f: F) { }

fn main() {
    api(|b| {
        b.stuff();
    })
}
```

**Comment by arielb1** [comment] 2015-11-14 20:11
Overloading inference evaluates a function in visitor order, so this is expected.

**Comment by arielb1** [comment] 2015-11-14 20:14
I mean, even without closures:
```Rust
struct Foo;

impl Foo {
    fn stuff(self) {}
}

fn compiles() {
    let mut x = None;
    loop {
        x = Some(Foo);
        if let Some(s) = x { s.stuff(); }
    }
}


fn does_not_compile() {
    let mut x = None;
    loop {
        if let Some(s) = x { s.stuff(); } //~ ERROR the type of this value
        x = Some(Foo);
    }
}

fn main() {}
```

**Comment by ebfull** [comment] 2015-11-14 20:27
Can you reopen this? It merits more discussion I think.

This issue also manifests in another way: you cannot create wrappers around closures without screwing up the inference logic:

This doesn't work:

```rust
struct Wrapper<F>(F);
struct Foo;

impl Foo {
    fn stuff(self) { }
}

fn api<T, F: Fn(T, Foo)>(f: Wrapper<F>) { }

fn main() {
    api(Wrapper(|a: usize, b| {
        b.stuff();
    }))
}
```

yet without the wrapper it works just fine:

```rust
struct Wrapper<F>(F);
struct Foo;

impl Foo {
    fn stuff(self) { }
}

fn api<T, F: Fn(T, Foo)>(f: F) { }

fn main() {
    api(|a: usize, b| {
        b.stuff();
    })
}
```

The inability to do this, despite the fact the type is totally umambiguous, is definitely a language bug as far as I'm concerned. It's currently a blocker for an API I'm writing.

**Comment by ebfull** [comment] 2015-11-14 20:30
cc @nikomatsakis

**Comment by ebfull** [comment] 2015-11-14 21:16
You can keep this issue closed as a duplicate of #25165.

**Comment by arielb1** [comment] 2015-11-15 19:00
@ebfull 

Your second issue is different enough. Could you edit your OP to represent that?

From my investigation, the problem is that we don't relate the return type of `Wrapper` to the argument type of `api`, because we are afraid there might be a coercion involved. This means the bound information is not passed to the closure. We could try to be better here - cc @nikomatsakis @eddyb.

**Comment by eddyb** [comment] 2015-11-15 20:13
@arielb1 I think that downward propagation is always supposed to happen, this looks like a missing case.

**Comment by arielb1** [comment] 2015-11-22 12:25
Duplicate of #20841. Closing and nominating that one.

**Closed by arielb1** 2015-11-22 12:25 UTC
Labels: A-closures, A-typesystem
