### ISSUE TITLE
Generate more descriptive paths for items which have the same name in Rustdoc

### ISSUE THREAD

**Issue by RDambrosio016** [rust-lang/rust#74924] opened 2020-07-29 19:26 UTC
Currently rustdoc does not attempt to disambiguate between traits which have the same name and are used somewhere, say, implemented traits. This makes for an interesting time trying to figure out what it is actually implementing at a glance. The best example ive found is serde libraries and their Error struct: https://docs.serde.rs/serde_json/struct.Error.html#trait-implementations
It is not very easy to see what it is implementing at a glance. This could likely be solved by seeing if multiple names clash in the same "section" and if so, generating the full path. In which case it would generate something along the lines of

 ![proposal](https://imgur.com/iEa0ygn.png)
#73996 Could offer insights into how to implement this too.

**Comment by joshtriplett** [comment] 2020-08-09 14:22
I would love to see this as well. An example from the standard library: https://doc.rust-lang.org/std/process/struct.Command.html . Notice how both impls of `CommandExt` look identical but refer to different traits.

**Comment by jhpratt** [comment] 2020-08-09 22:59
Another example is the time crate, where traits are frequently implemented on both `time::Duration` and `std::time::Duration`. In some places, it will output the latter as `StdDuration` (due to aliased imports). Having this feature would be great and would provide a significant amount of clarity to end-users.

**Comment by jyn514** [comment] 2020-08-27 03:43
Closing as duplicate of https://github.com/rust-lang/rust/issues/42066 (wow, this is certainly reported a lot!)

**Closed by jyn514** 2020-08-27 03:43 UTC
Labels: C-enhancement, T-rustdoc
