### ISSUE TITLE
regression in 2019-10-01 nightly

### ISSUE THREAD

**Issue by krisselden** [rust-lang/rust#65028] opened 2019-10-02 22:59 UTC
I will try to make a reproduction later, but just wanted to open an issue now.  The code worked when compiling with the beta and the prior nightly.

```
error: internal compiler error: src/librustc/ich/impls_ty.rs:100: StableHasher: unexpected region '_#0r

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (702b45e40 2019-10-01) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error
```

**Comment by jonas-schievink** [comment] 2019-10-02 23:10
Duplicate of https://github.com/rust-lang/rust/issues/64964

**Closed by jonas-schievink** 2019-10-02 23:10 UTC
