### ISSUE TITLE
Inexact results from str::float::from_str

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#7648] opened 2013-07-08 10:11 UTC
Some inputs to `std::float::from_str` give a value that prints as an integer, but does not compare equal to it:

```
rusti> std::float::from_str("0.67e3").get()
670
rusti> std::float::from_str("0.67e3").get() == 670f
false
rusti> std::float::to_str_hex(670f)
~"29e"
rusti> std::float::to_str_hex(std::float::from_str("0.67e3").get())
~"29e.00000000002"
```

For comparison, Python does not have this issue:
```
>>> float('.67e3') == 670
True
```

**Comment by huonw** [comment] 2015-05-31 03:45
Closing as a forward-dupe of https://github.com/rust-lang/rust/issues/24557, since that issue has more info.

**Closed by huonw** 2015-05-31 03:45 UTC
Labels: A-libs, I-wrong, P-medium
