### ISSUE TITLE
nightly install fails since since rustc 1.32.0-nightly  2018-11-10

### ISSUE THREAD

**Issue by yaplu56** [rust-lang/rust#55917] opened 2018-11-13 12:14 UTC
Installing the nightly on linux fails since 2018-11-10.
Message is 
install: copying file /home/christoph/apps/rust-nightly/bin/rustfmt
install: installing component 'llvm-tools-preview'
install: copying file /home/christoph/apps/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-nm
cp: -r wurde nicht angegeben, daher wird das Verzeichnis '/home/christoph/xfer/rust-nightly-x86_64-unknown-linux-gnu/llvm-tools-preview/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-nm' ausgelassen
chmod: Zugriff auf '/home/christoph/apps/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-nm' nicht möglich: Datei oder Verzeichnis nicht gefunden
install: error: file creation failed. see logs at '/home/christoph/apps/rust-nightly/lib/rustlib/install.log'

Comparing the actual installation file with version with version 2018-11-09 shows that the llvm path is messed up.  The binary files have been replaced by empty directories with the same names.

working:
christoph@PC-Rapido:~/xfer/rust-nightly-x86_64-unknown-linux-gnu_works/llvm-tools-preview/lib/rustlib/x86_64-unknown-linux-gnu> ll bin
insgesamt 8628
-rwxr-xr-x 1 christoph users 1026688  9. Nov 10:03 llvm-nm
-rwxr-xr-x 1 christoph users 1169240  9. Nov 10:03 llvm-objcopy
-rwxr-xr-x 1 christoph users 1507040  9. Nov 10:03 llvm-objdump
-rwxr-xr-x 1 christoph users 1033632  9. Nov 10:03 llvm-profdata
-rwxr-xr-x 1 christoph users 1939360  9. Nov 10:03 llvm-readobj
-rwxr-xr-x 1 christoph users  977120  9. Nov 10:03 llvm-size
-rwxr-xr-x 1 christoph users 1169240  9. Nov 10:03 llvm-strip

NOT WORKING:
christoph@PC-Rapido:~/xfer/rust-nightly-x86_64-unknown-linux-gnu/llvm-tools-preview/lib/rustlib/x86_64-unknown-linux-gnu> ll bin
insgesamt 28
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-nm
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-objcopy
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-objdump
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-profdata
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-readobj
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-size
drwxr-xr-x 2 christoph users 4096 12. Nov 22:08 llvm-strip
All directories are EMPTY.

Replacing this part with the older version results in correct installation.

**Comment by jethrogb** [comment] 2018-11-15 15:41
Dupe of #55866 ?

**Comment by nagisa** [comment] 2018-11-18 12:48
Yes, a duplicate.

**Closed by nagisa** 2018-11-18 12:48 UTC
