### ISSUE TITLE
panic! does not warn about failing to provide an argument

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#43257] opened 2017-07-15 21:08 UTC
I expected `panic!` to behave like `println!` and warn me that I have a formatter argument that is unused. Tested with Rust 1.18.0.

### `println!`

```rust
println!("{:p}"); 
```

```
error: invalid reference to argument `0` (no arguments given)
 --> src/main.rs:2:5
  |
2 |     println!("{:p}");
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate
```

### `panic!`

```rust
panic!("{:p}");
```

```
thread 'main' panicked at '{:p}', src/main.rs:4
```

**Comment by ollie27** [comment] 2017-07-15 21:45
dupe of #22932

**Closed** 2017-07-15 21:50 UTC

**Comment by shepmaster** [comment] 2017-07-15 23:59
Thank you, @ollie27, I couldn't find that with a few minutes of searching 😊
