### ISSUE TITLE
Module declarations imported via `include!()` have unexpected relative paths

### ISSUE THREAD

**Issue by kotauskas** [rust-lang/rust#92666] opened 2022-01-08 09:43 UTC
Consider this directory structure:
```
┗━ proj
   ┣━ template.rs
   ┣━ examples
   ┃  ┗━ example1
   ┃     ┣━ client.rs
   ┃     ┣━ server.rs
   ┃     ┗━ main.rs
   ┗━ ...
```
the only line in `main.rs` being:
```rust
include!("../../template.rs");
```
then, in `template.rs`:
```rust
mod client;
mod server;
// some more code
```

The typical user expectation for `include!()` is to unhygienically copypaste tokens from the given file, as its documentation suggests (although very vaguely, as it only mentions this behavior with expressions). The above code, however, produces the following `E0583`:
```rust
error[E0583]: file not found for module `client`
 --> examples\example1\../../template.rs:5:1
  |
5 | mod client;
  | ^^^^^^^^^^^
  |
  = help: to create the module `client`, create file "examples\example1\../..\client.rs" or "examples\example1\../..\client\mod.rs"
```

This can be very easily worked around with a macro, but the behavior is very counter-intuitive and, at the very least, requires documentation to be adjusted, although I'm not sure if that's the correct solution, so I'm not sending a PR right away. Not sure whether this is a bug at all, but we definitely need a Crater run to determine whether disabling this behavior affects any public crates.

**Comment by sudipghimire533** [comment] 2022-01-08 14:16
Could you mention the platform this was compiled on?

**Comment by kotauskas** [comment] 2022-01-08 14:44
I heavily doubt this depends on the OS. For reference though, the compiler version string is `rustc 1.59.0-nightly (e012a191d 2022-01-06)` and the platform is Windows 10 on x86-64.

**Comment by ehuss** [comment] 2022-01-08 15:27
This isn't hygiene exactly (which is more to do with symbol resolution), but the fact that filesystem paths are interpreted relative to the file from which they are loaded from.  I believe this is relied upon, and not something that can be changed.  

Updating the documentation to clarify this behavior sounds reasonable, though.

**Comment by ehuss** [comment] 2022-07-27 19:34
Closing as a duplicate of #50132.

**Closed by ehuss** 2022-07-27 19:34 UTC
