### ISSUE TITLE
OutputTypeParameterMismatch ICE

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#85536] opened 2021-05-21 03:19 UTC
### Code

```Rust
fn main() {
    let receiver: fn(&mut <&Vec<String> as IntoIterator>::IntoIter) =
        |iter| iter.for_each(|s| println!("{}", s));
}
```

### Meta
[Discovered on playground,](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=156b2189c5a284ed38034b8cc1e1fd10) reproduces on all of Stable, Beta, and Nightly.  

### Error output
```
error: internal compiler error: compiler/rustc_trait_selection/src/traits/codegen.rs:78:17: Encountered error `OutputTypeParameterMismatch(Binder(<[closure@src/main.rs:3:9: 3:52] as std::ops::FnMut<(&mut <&std::vec::Vec<std::string::String> as std::iter::IntoIterator>::IntoIter,)>>), Binder(<[closure@src/main.rs:3:9: 3:52] as std::ops::FnMut<(&mut std::slice::Iter<std::string::String>,)>>), Sorts(ExpectedFound { expected: std::slice::Iter<std::string::String>, found: <&std::vec::Vec<std::string::String> as std::iter::IntoIterator>::IntoIter }))` selecting `Binder(<[closure@src/main.rs:3:9: 3:52] as std::ops::FnMut<(&mut std::slice::Iter<std::string::String>,)>>)` during codegen

thread 'rustc' panicked at 'Box<Any>', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.1 (9bc8c42bb 2021-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `std::ops::FnMut` fulfills its obligations
#1 [resolve_instance] resolving instance `<[closure@src/main.rs:3:9: 3:52] as std::ops::FnMut<(&mut std::slice::Iter<std::string::String>,)>>::call_mut`
end of query stack
error: aborting due to previous error; 1 warning emitted

error: could not compile `playground`

To learn more, run the command again with --verbose.
```
### Context
Perhaps irrelevant to the ICE, but [I was using the round-about ascription to (attempt to) work around what I believe is a missed type normalization.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6b7a647b338851bac639b28032ba28a1)

**Comment by FabianWolff** [comment] 2021-06-03 21:31
Here is a simplified example:
```rust
trait Tr { type Ty; }
struct S;
impl Tr for &S { type Ty = i32; }

fn main() {
    let f: fn(<&S as Tr>::Ty) = |i: i32| ();
}
```
The reference seems to be important, because changing both occurrences of `&S` to `S` does not lead to the ICE.

**Comment by jackh726** [comment] 2021-06-03 22:01
Duplicate of #62529

Going to close because there's many linked issues there and I'm not sure another one will actually help

**Closed by jackh726** 2021-06-03 22:01 UTC
Labels: C-bug, I-ICE, T-compiler
