### ISSUE TITLE
Improve illegal crate name importation error message

### ISSUE THREAD

**Issue by csmoe** [rust-lang/rust#52569] opened 2018-07-20 14:05 UTC
```rust
error: expected one of `;` or `as`, found `-`
 --> src/main.rs:1:17
  |
1 | extern crate foo-bar;
  |                 ^ expected one of `;` or `as` here

error: aborting due to previous error

error: Could not compile `hello`.

To learn more, run the command again with --verbose.
```
it'll be better to suggest using snake name here:
```rust
error: found illegal crate name
 --> src/main.rs:1:17
  |
1 | extern crate foo-bar;
  |              ^^^^^^^ consider changing this to: `foo_bar`

error: aborting due to previous error

error: Could not compile `hello`.

To learn more, run the command again with --verbose.
```

**Comment by estebank** [comment] 2018-07-20 22:42
Duplicate of #48437. We should not only provide the suggestion, the compiler should continue compiling and if the rest of the code is correct, no other errors should be emitted.

**Closed** 2018-07-20 22:42 UTC
Labels: A-diagnostics
