### ISSUE TITLE
use multiple names from different submodules at once

### ISSUE THREAD

**Issue by porky11** [rust-lang/rust#39629] opened 2017-02-07 22:36 UTC
It is possible to use multiple names with a single `use` from a module like this:
`use M::{A,B}` (similar to bash)
Especially when using mutliple names this is useful. But often multiple names are in different submodules, so I'd like to be able to write this too:
`use M::{X::A,Y::B}`
or even
`use M::{X::{A,B},Y::{C,D}}` (more similar to bash)

I hope this wasn't requested before, and the change is small enough for not having to write an RFC.

**Comment by petrochenkov** [comment] 2017-02-07 23:14
Duplicate of https://github.com/rust-lang/rfcs/issues/1400

**Comment by petrochenkov** [comment] 2017-02-07 23:16
>I hope this wasn't requested before, and the change is small enough for not having to write an RFC.

This is not a huge change, but it certainly crosses the line of not requiring an RFC.

**Closed** 2017-02-08 01:22 UTC
