### ISSUE TITLE
ICE on `cargo doc` with dependency `leptos@0.7.0-rc1` in current nightly

### ISSUE THREAD

**Issue by chipnertkj** [rust-lang/rust#133020] opened 2024-11-14 02:35 UTC
Please inform me if there is anything else I can do to help.
[rustc-ice-2024-11-14T02_19_01-19724.txt](https://github.com/user-attachments/files/17742078/rustc-ice-2024-11-14T02_19_01-19724.txt)

### Reproduce
I don't have another environment to test this in, but in my case, the steps appear to be:
1. Create a new crate, doesn't matter if it's a library.
2. Add `leptos@0.7.0-rc1` to dependencies.
3. Attempt to run `cargo doc`.

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (8adb4b30f 2024-11-13)
binary: rustc
commit-hash: 8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c
commit-date: 2024-11-13
host: x86_64-pc-windows-msvc
release: 1.84.0-nightly
LLVM version: 19.1.3
```

### Error output

```
thread 'rustc' panicked at compiler\rustc_metadata\src\rmeta\decoder.rs:1501:75:
called `Option::unwrap()` on a `None` value
error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-rustdoc&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `C:\Users\domek\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos-0.7.0-rc1\rustc-ice-2024-11-14T02_19_01-19724.txt` to your bug report

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
panicked at compiler\rustc_metadata\src\rmeta\decoder.rs:1499:14:
lock was already held
thread panicked while processing panic. aborting.
error: could not document `leptos`

Caused by:
  process didn't exit successfully: `C:\Users\domek\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\rustdoc.exe --edition=2021 --crate-type lib --crate-name leptos C:\Users\domek\.cargo\registry\src\index.crates.io-6f17d22bba15001f\leptos-0.7.0-rc1\src\lib.rs --cap-lints allow -o C:\Users\domek\self_managed\workspace\projects\ice-test\target\doc --check-cfg cfg(docsrs) --check-cfg "cfg(feature, values(\"base64\", \"csr\", \"default-tls\", \"delegation\", \"experimental-islands\", \"hydrate\", \"hydration\", \"leptos-spin-macro\", \"nightly\", \"nonce\", \"rand\", \"rkyv\", \"rustls\", \"spin\", \"ssr\", \"trace-component-props\", \"tracing\"))" --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=176 -C metadata=fcb90849b06b4265 -L dependency=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps --extern any_spawner=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libany_spawner-65935f02134093d7.rmeta --extern cfg_if=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libcfg_if-62a6993daf48d67c.rmeta --extern either_of=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libeither_of-3097bd51789e4cb6.rmeta --extern futures=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libfutures-810ce01e94e6b84a.rmeta --extern hydration_context=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libhydration_context-a46ec11ae5e8d8ae.rmeta --extern leptos_config=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libleptos_config-b1a57eb3e9228859.rmeta --extern leptos_dom=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libleptos_dom-50580d2d192f0e33.rmeta --extern leptos_hot_reload=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libleptos_hot_reload-801d64c6d4c56bc0.rmeta --extern leptos_macro=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\leptos_macro-fd738002a3a7b247.dll --extern leptos_server=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libleptos_server-e5dbbc7e966ee1a4.rmeta --extern oco_ref=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\liboco_ref-86957331e11b3518.rmeta --extern or_poisoned=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libor_poisoned-9841dc7b0725f6df.rmeta --extern paste=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\paste-a28619ffed47c32b.dll --extern reactive_graph=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libreactive_graph-5e762cd9f874ee27.rmeta --extern rustc_hash=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\librustc_hash-b2c555ac157add2a.rmeta --extern send_wrapper=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libsend_wrapper-3ec2f29747943fba.rmeta --extern serde=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libserde-9432fe754b3bf3d3.rmeta --extern serde_qs=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libserde_qs-17cab6050c0dca54.rmeta --extern server_fn=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libserver_fn-891268b074663b68.rmeta --extern slotmap=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libslotmap-d7d134336276bcd2.rmeta --extern tachys=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libtachys-5db54401ff533eea.rmeta --extern thiserror=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libthiserror-32733e380c5c4cde.rmeta --extern throw_error=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libthrow_error-f2bff0b68072a62e.rmeta --extern typed_builder=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libtyped_builder-e2032fbd0b438b2e.rmeta --extern typed_builder_macro=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\typed_builder_macro-65a888c780600d51.dll --extern wasm_bindgen=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libwasm_bindgen-f0f720608aa54c5e.rmeta --extern web_sys=C:\Users\domek\self_managed\workspace\projects\ice-test\target\debug\deps\libweb_sys-ee0f705e9c3e8329.rmeta --crate-version 0.7.0-rc1` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7ff84f3f5c41 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ff84f3f5c41 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff84f3f5c41 - std::sys::backtrace::_print_fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\sys\backtrace.rs:66
   3:     0x7ff84f3f5c41 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\sys\backtrace.rs:39
   4:     0x7ff84f427dea - core::fmt::rt::Argument::fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\rt.rs:177
   5:     0x7ff84f427dea - core::fmt::write
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\mod.rs:1189
   6:     0x7ff84f3ebe77 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\io\mod.rs:1839
   7:     0x7ff84f3f5a85 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\sys\backtrace.rs:42
   8:     0x7ff84f3f8973 - std::panicking::default_hook::closure$1
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\panicking.rs:268
   9:     0x7ff84f3f8752 - std::panicking::default_hook
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\panicking.rs:295
  10:     0x7ff850a1bc9e - memchr
  11:     0x7ff84f3f90b2 - alloc::boxed::impl$30::call
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/alloc\src\boxed.rs:1982
  12:     0x7ff84f3f90b2 - std::panicking::rust_panic_with_hook
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\panicking.rs:809
  13:     0x7ff84f3f8ec2 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\panicking.rs:667
  14:     0x7ff84f3f66ff - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\sys\backtrace.rs:170
  15:     0x7ff84f3f8afe - std::panicking::begin_panic_handler
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\panicking.rs:665
  16:     0x7ff852419e11 - core::panicking::panic_fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\panicking.rs:76
  17:     0x7ff852419ecd - core::panicking::panic
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\panicking.rs:148
  18:     0x7ff852419d8e - core::option::unwrap_failed
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\option.rs:2009
  19:     0x7ff84f18a0d0 - <rustc_metadata[292d98e81fa56d82]::creader::CrateMetadataRef>::get_mod_child
  20:     0x7ff84f185d83 - <rustc_metadata[292d98e81fa56d82]::creader::CStore as rustc_session[94c4dd1959dbb15d]::cstore::CrateStore>::def_path
  21:     0x7ff84f2f4fd9 - <rustc_middle[a854a0fdc623521d]::ty::context::TyCtxt>::def_path
  22:     0x7ff852104fa9 - <rustc_middle[a854a0fdc623521d]::ty::context::TyCtxt>::def_path_debug_str
  23:     0x7ff850c216b8 - <i128 as powerfmt[a17513592541b578]::smart_display::SmartDisplay>::metadata
  24:     0x7ff84f427dea - core::fmt::rt::Argument::fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\rt.rs:177
  25:     0x7ff84f427dea - core::fmt::write
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\mod.rs:1189
  26:     0x7ff84f427dea - core::fmt::rt::Argument::fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\rt.rs:177
  27:     0x7ff84f427dea - core::fmt::write
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\mod.rs:1189
  28:     0x7ff84f418d85 - core::fmt::Write::write_fmt::impl$1::spec_write_fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\mod.rs:226
  29:     0x7ff84f418d85 - core::fmt::Write::write_fmt
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/core\src\fmt\mod.rs:231
  30:     0x7ff84f418d85 - alloc::fmt::format::format_inner
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/alloc\src\fmt.rs:647
  31:     0x7ff85212214b - rustc_middle[a854a0fdc623521d]::util::bug::bug_fmt
  32:     0x7ff85210203d - rustc_middle[a854a0fdc623521d]::ty::consts::const_param_default
  33:     0x7ff852101e56 - rustc_middle[a854a0fdc623521d]::ty::consts::const_param_default
  34:     0x7ff852122092 - rustc_middle[a854a0fdc623521d]::util::bug::bug_fmt
  35:     0x7ff851e17f24 - <&[(rustc_middle[a854a0fdc623521d]::ty::predicate::Clause, rustc_span[80e1b09208171c39]::span_encoding::Span)] as rustc_serialize[fc33070f793e6c1e]::serialize::Decodable<rustc_metadata[292d98e81fa56d82]::rmeta::decoder::DecodeContext>>::decode
  36:     0x7ff8505166d4 - <rustc_metadata[292d98e81fa56d82]::creader::alloc_error_handler_spans::Finder as rustc_ast[a69777a8ed9933a7]::visit::Visitor>::visit_item
  37:     0x7ff8501ac400 - rustc_query_impl[96d1e27d075b1dcd]::plumbing::query_key_hash_verify_all
  38:     0x7ff85008fc20 - rustc_ty_utils[250a45cddf2b1c87]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  39:     0x7ff8501b6287 - rustc_query_impl[96d1e27d075b1dcd]::plumbing::query_key_hash_verify_all
  40:     0x7ff65e66cf01 - <unknown>
  41:     0x7ff65e6e0345 - <unknown>
  42:     0x7ff65e878dbc - <unknown>
  43:     0x7ff65e9ed6a5 - <unknown>
  44:     0x7ff65e6eaaed - <unknown>
  45:     0x7ff65e66a8a0 - <unknown>
  46:     0x7ff65e6fcd84 - <unknown>
  47:     0x7ff84f40acfd - alloc::boxed::impl$28::call_once
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/alloc\src\boxed.rs:1968
  48:     0x7ff84f40acfd - alloc::boxed::impl$28::call_once
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/alloc\src\boxed.rs:1968
  49:     0x7ff84f40acfd - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c\library/std\src\sys\pal\windows\thread.rs:55
  50:     0x7ff905d2257d - BaseThreadInitThunk
  51:     0x7ff906dcaf08 - RtlUserThreadStart
```

</p>
</details>

**Comment by lukas-code** [comment] 2024-11-14 02:51
Thanks for the report! This is a duplicate of https://github.com/rust-lang/rust/issues/132743, so closing in favor of that.

**Closed by lukas-code** 2024-11-14 02:51 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage

**Comment by chipnertkj** [comment] 2024-11-14 03:02
Ah, I missed it, my bad! Glad it's being worked on 😊
