### ISSUE TITLE
`use super as some_name` is invalid

### ISSUE THREAD

**Issue by surma** [rust-lang/rust#73647] opened 2020-06-23 09:33 UTC
I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5ffcd52efc5385c084e47faad5fc12e0)):

```rust
pub mod mod1 {
    pub const thing: bool = true;
    pub mod mod2 {
        use super as my_super;

        pub fn print() {
            println!("{}", my_super::thing);
        } 
    }
}

fn main() {
    mod1::mod2::print();
}
```

**I expected to see this happen:** It should compile and run.

**Instead, this happened:** It fails with

```
error[E0432]: unresolved import `super`
 --> mytest.rs:4:13
  |
4 |         use super as my_super;
  |             ^^^^^^^^^^^^^^^^^ no `super` in the root
```

Looking at [the relevant part of the reference](https://doc.rust-lang.org/reference/items/use-declarations.html), it seems the above is at least grammatically correct. 

I would love for this to work. However, if this is _supposed_ to not work, a better error message would be great.

### Meta

`rustc --version --verbose`:
```
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

**Comment by petrochenkov** [comment] 2020-06-23 09:37
Duplicate of https://github.com/rust-lang/rust/issues/35612 https://github.com/rust-lang/rust/issues/29036 https://github.com/rust-lang/rust/issues/37156

**Closed** 2020-06-23 09:49 UTC
Labels: C-bug
