### ISSUE TITLE
Make `saturating_add` and `saturating_sub` `const` functions

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#58030] opened 2019-01-31 16:51 UTC
These used to require `if` to work, but are forwarded to llvm intrinsics nowadays (https://github.com/rust-lang/rust/pull/58003). We can now implement them as const eval intrinsics, too.

Impl instructions:

1. add to https://github.com/rust-lang/rust/blob/0c0c585281740aba4c91cbfd385f5e1fbe313d11/src/librustc_mir/transform/qualify_min_const_fn.rs#L371
2. remove `unsafe` for calls to the intrinsic
3. add to https://github.com/rust-lang/rust/blob/51cc3cdcf060c1bf3e4d45947f7a6bc20f9960f7/src/librustc_mir/transform/qualify_consts.rs#L820
4. make functions calling the intrinsic `const fn`
5. Implement in https://github.com/rust-lang/rust/blob/79d8a0fcefa5134db2a94739b1d18daa01fc6e9f/src/librustc_mir/interpret/intrinsics.rs#L102 (implementation is basically the two `read_immediate` calls, a call to `binary_op_imm` with arguments similar to the other add/sub intrinsics, in case the overflow bool in the return value is false, write the actual value to the destination like in https://github.com/rust-lang/rust/blob/79d8a0fcefa5134db2a94739b1d18daa01fc6e9f/src/librustc_mir/interpret/operator.rs#L36 . In case the overflow bool is true, compute the min or max value of the type like in https://github.com/rust-lang/rust/blob/79d8a0fcefa5134db2a94739b1d18daa01fc6e9f/src/librustc_mir/interpret/operator.rs#L217 and write that value to `dest`.
6. Write some tests that use the saturating methods in constants

**Comment by pmccarter** [comment] 2019-01-31 18:01
I'd really like to do this!

**Comment by oli-obk** [comment] 2019-02-01 08:13
It's all yours! If anything is unclear, don't hesitate to ask.

**Comment by pmccarter** [comment] 2019-02-01 19:55
Thanks! I have some questions, please let me know if I'm misunderstanding anything...

Is it correct that the point of this ticket is to avoid code generation (LLVM intrinsics) by evaluating during compilation (const eval intrinsics), where previously LLVM branching code was generated? Is there already compiler logic to detect non immediate arguments/terms so that the LLVM code is generated even after the functions are whitelisted as const?

I can't find any compiler code where calls to n.saturating_add(m) are wrapped in unsafe blocks, and why would they be? Also, are the implementation guidelines saying that all functions with calls to these two functions can be marked as const? Why would that be, irregardless of other statements in the function?

**Comment by nikic** [comment] 2019-02-01 20:14
> Is it correct that the point of this ticket is to avoid code generation (LLVM intrinsics) by evaluating during compilation (const eval intrinsics), where previously LLVM branching code was generated? Is there already compiler logic to detect non immediate arguments/terms so that the LLVM code is generated even after the functions are whitelisted as const?

Not quite. For normal code, the LLVM intrinsics will still be generated (at which point LLVM may evaluate them during optimization, but that's a different matter). Making the intrinsics const just means that they can be used in contexts where the result *must* be evaluated during compilation. It allows you to write something like `const N = A.saturating_add(B);`.

> I can't find any compiler code where calls to n.saturating_add(m) are wrapped in unsafe blocks, and why would they be?

You need to separate two things here: The `saturating_add` methods on numeric types like `u32`, and the `saturating_add` intrinsic in `core::intrinsics`. By default all such intrinsics are unsafe, but for `saturating_add` in particular there is no reason for it to be. (I think this is already the case -- though maybe this has to be marked separate for const handling.)

> Also, are the implementation guidelines saying that all functions with calls to these two functions can be marked as const? Why would that be, irregardless of other statements in the function?

This refers to the functions that call the *intrinsics*, which should just be the `saturing_add`/`saturating_sub` methods in `core::num` (such as https://github.com/rust-lang/rust/blob/master/src/libcore/num/mod.rs#L885). Those are the only functions that should be marked as `const`.

**Comment by RalfJung** [comment] 2019-02-01 20:15
> Is it correct that the point of this ticket is to avoid code generation (LLVM intrinsics) by evaluating during compilation (const eval intrinsics), where previously LLVM branching code was generated?

No. This is to make the CTFE engine in Rust support these intrinsics.  When you write `const FOO: T = bar;` or `static FOO: T = bar;`, Rust has to evaluate `bar` at compile-time, that's called CTFE.  And the point of this issue is to enable `bar` to use `saturating_add`, to make [code like this work](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4e3c4b2765d7a7e5df6b6282281114ca):
```
fn main() {
    const x: u8 = 13u8.saturating_sub(66);
}
```

**Comment by pmccarter** [comment] 2019-02-04 22:33
Thanks for the help guys.

Currently the num module saturating_add() wrapper only uses the intrinsic for stage 1+, so the function can't just be marked as const because of the non const checked_add() call in the stage 0 compiler. Looks like other intrinsic calls don't need the stage guards so not sure what the issue is. Does this need to wait for the bootstrapping compile version to advance or something?

Also not sure about the special // ~> comments...

**Comment by nikic** [comment] 2019-02-04 22:53
@pmccarter I believe the way to handle this would be to move the cfg to cover the whole function. You'd have a stage0 variant that is non-const and also uses the old checked_add based implementation, and you'd have a not(stage0) variant that is const and uses the saturating_add intrinsic based implementation.

So basically instead of

```rust
pub fn saturating_add(self, rhs: Self) -> Self {
    #[cfg(stage0)]
    match self.checked_add(rhs) {
        Some(x) => x,
        None => Self::max_value(),
    }
    #[cfg(not(stage0))]
    {
        intrinsics::saturating_add(self, rhs)
    }
}
```

you'd have

```rust
#[cfg(stage0)]
pub fn saturating_add(self, rhs: Self) -> Self {
    match self.checked_add(rhs) {
        Some(x) => x,
        None => Self::max_value(),
    }
}

#[cfg(not(stage0))]
pub const fn saturating_add(self, rhs: Self) -> Self {
    intrinsics::saturating_add(self, rhs)
}
```

**Closed** 2019-02-12 05:50 UTC
Labels: A-const-eval, E-mentor
