### ISSUE TITLE
Const generics and transmute: cannot transmute between types of different sizes

### ISSUE THREAD

**Issue by bgourlie** [rust-lang/rust#62875] opened 2019-07-22 14:52 UTC
The following code should compile, but it doesn't:

```
#![feature(const_generics)]

use std::{
    mem::{self, MaybeUninit},
    ptr,
};

fn main() {
}

pub struct Foo<const SIZE: usize> {
    messages: [Option<String>; SIZE],
}

impl<const SIZE: usize> Default for Foo<{SIZE}> {
    fn default() -> Self {
        let arr = {
            let mut arr: [MaybeUninit<Option<String>>; {SIZE}] =
                unsafe { MaybeUninit::uninit().assume_init() };

            for elem in &mut arr[..] {
                unsafe { ptr::write(elem.as_mut_ptr(), None) }
            }

            unsafe { mem::transmute::<_, [Option<String>; {SIZE}]>(arr) }
        };
        Foo {
            messages: arr,
        }
    }
}
```

The error produced is

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> src\main.rs:25:22
   |
25 |             unsafe { mem::transmute::<_, [Option<String>; {SIZE}]>(arr) }
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `[std::mem::MaybeUninit<std::option::Option<std::string::String>>; _]` (this type does not have a fixed size)
   = note: target type: `[std::option::Option<std::string::String>; _]` (this type does not have a fixed size)
```

**Comment by DutchGhost** [comment] 2019-07-22 15:12
Duplicate of https://github.com/rust-lang/rust/issues/61956 .

To fix this for now, either use `transmute_copy`, or take a raw pointer to the MaybeUninit array, cast the ptr to the type you want, and `ptr::read` it, while making sure you `mem::forget` the MaybeUninit array!

**Comment by varkor** [comment] 2020-04-08 21:46
Closing as duplicate of https://github.com/rust-lang/rust/issues/61956.

**Closed by varkor** 2020-04-08 21:46 UTC
Labels: A-const-generics, C-bug, F-const_generics, T-compiler, requires-nightly

**Comment by hniksic** [comment] 2021-05-10 19:30
@DutchGhost Why is it necessary to `mem::forget()` the array of `MaybeUninit`? AFAIK `MaybeUninit` doesn't implement `Drop` so `mem::forget`-ing it should be no-op.
