### ISSUE TITLE
There is a little bug

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#43337] opened 2017-07-19 17:38 UTC
this program can run:

```
fn foo() -> bool {
    loop {
        return true;
    }
}

fn main() {
    println!("{}", foo());
}
```

but this can not:

```
fn foo() -> bool {
    while true {
        return true;
    }
}

fn main() {
    println!("{}", foo());
}
```
In other words, please give a warning first when we use `while true`.

**Comment by sfackler** [comment] 2017-07-19 17:53
Duplicate of #43154

**Closed by sfackler** 2017-07-19 17:53 UTC
