### ISSUE TITLE
Rust 1.29.0->1.30.0 breaks compilation on OSX

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [rust-lang/rust#55539] opened 2018-10-31 14:27 UTC
Sadly I dont think a minimal example is feasible; but I have a build involving some annoying binary dependencies like lapack; its been working fine on both linux and OSX for a year now no problem, but updating to rust 1.30.0 broke the OSX build with various seemingly unrelated compilation errors and complaints about lapack. On linux, everything is fine regardless of the rust version.

That is, using OSX and the following rust package:
rust:            1.30.0-1000             conda-forge
This is what happens.
```
   Compiling num-traits v0.2.6
   Compiling proc-macro2 v0.4.20                                                                                                                                          
   Compiling cc v1.0.25                                                                                                                                                   
   Compiling version_check v0.1.5                                                                                                                                         
dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib                               
dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib                               
  Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib                                               
  Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libLAPACK.dylib provides version 0.0.0                                                
  Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib                                               
  Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libLAPACK.dylib provides version 0.0.0                                                
error: Could not compile `proc-macro2`.                                                                                                                                   
warning: build failed, waiting for other jobs to finish...
dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib                               
  Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib                                               
  Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libLAPACK.dylib provides version 0.0.0                                                
dyld: Library not loaded: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib                               
  Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib                                               
  Reason: Incompatible library version: vecLib requires version 1.0.0 or later, but libLAPACK.dylib provides version 0.0.0                                                
error: Could not compile `cc`.                                                                                                                                            
warning: build failed, waiting for other jobs to finish...
error: Could not compile `version_check`.                                                                                                                                 
warning: build failed, waiting for other jobs to finish...
error: Could not compile `num-traits`.                                                                                                                                    
```

Pinning the rust version to 1.29.0, everything is totally fine.

Now to be fair getting this to build on both OSX and linux was originally a challenge and it may have been more through luck than best practice that we got it to work; so there probably is a way to get this to work again using the newer rust.... but maybe this error also contains actionable information for some of you. The package versions of the packages mentioned under 1.30.0 are the same under 1.29.0, and fiddling around with the seeming offending packages was to no avail.

**Comment by madsmtm** [comment] 2024-10-10 06:56
Triage: [There's a few thousand commits that could be the culprit](https://github.com/rust-lang/rust/compare/1.29.0...1.30.0), and without a reproducible example, it's impossible to know.

Besides, from the error message it sounds looks like `libLAPACK.dylib` is the problem, `dyld` is saying that it provides `vecLib`, which it clearly shouldn't, that's a system library!

I'm inclined to close this.

**Comment by jieyouxu** [comment] 2024-10-10 10:01
This is impossible to debug without a reproducer and more info. Closing, but feel free to reopen if you have any concrete reproducer.

**Closed by jieyouxu** 2024-10-10 10:01 UTC
Labels: O-macos, S-needs-repro, S-needs-info
