### ISSUE TITLE
Support tvOS and watchOS (and simulator) targets

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#48862] opened 2018-03-09 03:16 UTC
Apple's division of OS targets is a bit odd: apps for iPhones and iPads both use an iOS or "iPhoneOS" target, but watchOS and tvOS are treated as entirely separate targets or "platforms". 

rustc currently supports macOS (`{x86_64,i686}-apple-darwin`), iOS (`{armv7,armv7s,aarch64}-apple-ios`), and the iOS Simulator (`i386-apple-ios`), but not tvOS or watchOS.

Here's the full list of platforms.  (I'm not sure if the version-min argument is needed for rustc, but it would be needed in `cc-rs`, which is also missing support.)

**Edit** (9/10/19): Changes since this was originally posted:
- Simulators now have `-simulator` in the LLVM triple, e.g. `x86_64-apple-tvos12.4.0-simulator`
- Catalyst (which someone [already submitted a PR adding initial support for](https://github.com/rust-lang/rust/pull/63467)) has triples like `x86_64-apple-ios13.0-macabi`.  It still uses the macOS SDK, [but with a custom header/library search path](https://github.com/CocoaPods/CocoaPods/issues/8877#issuecomment-499258506).
- watchOS has an additional architecture, `arm64_32`; example LLVM triple: `arm64_32-apple-watchos6.0.0`.

OS Name | Xcode Platform Name | Valid Architectures | LLVM Triple | Clang `-mxxx-version-min`
-- | -- | -- | -- | --
macOS | `MacOSX` | i386 x86_64 | `x86_64-apple-macosx10.13.0` | `-mmacosx-version-min` or `-mmacos-version-min`
iOS | `iPhoneOS` | arm64 armv7 armv7s | `arm64-apple-ios11.2.0` | `-miphoneos-version-min` or `-mios-version-min`
iOS Simulator | `iPhoneOSSimulator` | i386 x86_64 | `x86_64-apple-ios11.2.0` | `-miphonesimulator-version-min` or `-mios-simulator-version-min`
watchOS | `WatchOS` | armv7k | `thumbv7k-apple-watchos4.2.0` | `-mwatchos-version-min`
watchOS Simulator | `WatchSimulator` | i386 x86_64 | `x86_64-apple-watchos4.2.0` | `-mwatchsimulator-version-min` or `-mwatchos-simulator-version-min`
tvOS | `AppleTVOS` | arm64 | `arm64-apple-tvos11.2.0` | `-mappletvos-version-min` or `-mtvos-version-min`
tvOS Simulator | `AppleTVSimulator` | x86_64 | `x86_64-apple-tvos11.2.0` | `-mappletvsimulator-version-min` or `-mtvos-simulator-version-min`

Example output of `xcodebuild -showsdks`:
```
iOS SDKs:
	iOS 11.2                      	-sdk iphoneos11.2

iOS Simulator SDKs:
	Simulator - iOS 11.2          	-sdk iphonesimulator11.2

macOS SDKs:
	macOS 10.13                   	-sdk macosx10.13

tvOS SDKs:
	tvOS 11.2                     	-sdk appletvos11.2

tvOS Simulator SDKs:
	Simulator - tvOS 11.2         	-sdk appletvsimulator11.2

watchOS SDKs:
	watchOS 4.2                   	-sdk watchos4.2

watchOS Simulator SDKs:
	Simulator - watchOS 4.2       	-sdk watchsimulator4.2
```

**Comment by appaquet** [comment] 2019-03-01 13:53
Starting from the iOS implementation in rustc, I got i386 and armv7k for watchos to compile and link in Xcode 10.2 beta 3. It requires quite a few modifications to support the `watchos` platform, but I think it's quite trivial as watchOS is based on iOS. Unfortunatelly, it will require changes in quite a few crates that have conditional compilation on iOS target (cc, compiler-rt, backtrace, etc.). 

Unfortunately, this isn't sufficient for Apple Store release... Apple now requires a new `arm64_32` target as of watchOS 5.0. There is a very recent proposal to [upstream it](https://lists.llvm.org/pipermail/llvm-dev/2019-January/129788.html). Xcode comes with a bitcode translation tool that takes armv7k code and translates it to arm64_32 (which I understand being possible as they have same pointer/int size), but couldn't make it work with armv7k generated by rustc...

As mentionned in #35968, in order to prevent this never ending catching up on Xcode, I think using Swift's llvm is the only way to fully support Apple ecosystem...

**Comment by lerouxrgd** [comment] 2019-03-01 15:17
Would it be feasible to add a `codegen-backends` implementation based on [Swift's llvm](https://github.com/apple/swift-llvm) ? (In the same way `emscripten` was added)

**Comment by pruthvikar** [comment] 2020-01-30 17:01
@appaquet Would you be able to share how you managed to do compile and link for armv7k?

**Comment by appaquet** [comment] 2020-01-30 17:07
@pruthvikar Unfortunately it's been a while and I haven't touched it since, so I may not be very helpful... But here are the changes I had made on rustc: https://github.com/rust-lang/rust/compare/master...appaquet:watchos

But as I had mentioned, arm64_32 was impossible to target since it required changes that had not been merged in LLVM back when I tested it.

**Comment by pruthvikar** [comment] 2020-01-30 17:11
That should come in very handy, thanks!

**Comment by iMonZ** [comment] 2022-06-05 01:44
`rustc --print target-list       ` shows "aarch64-apple-tvos" but then I get the error:

>  ~/Downloads/rust   …  rustup target add aarch64-apple-tvos                                                                                                       111ms  Sun  5 Jun 03:43:10 2022
> error: toolchain 'beta-aarch64-apple-darwin' does not contain component 'rust-std' for target 'aarch64-apple-tvos'; did you mean 'aarch64-apple-ios'?
> note: not all platforms have the standard library pre-compiled: https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by jinleili** [comment] 2022-09-26 09:38
From https://doc.rust-lang.org/nightly/rustc/platform-support.html, `aarch64-apple-tvos` target only supports no_std development.

**Comment by hakonk** [comment] 2023-06-18 09:05
Hi! Is support for Rust `std` on tvOS something that is worked on, and if so, are there any plans for when it will be rolled out?

**Comment by hakonk** [comment] 2023-06-18 09:21
I'm also curious about what's needed to make `std` work on tvOS.

**Comment by workingjubilee** [comment] 2023-07-22 18:42
See https://github.com/rust-lang/rust/pull/103503
All of these targets are at the status they should be, I believe.

Closing.

**Closed by workingjubilee** 2023-07-22 18:42 UTC
Labels: O-macos, O-ios, T-compiler, C-feature-request, A-target-specs, O-watchos, O-tvos

**Comment by hakonk** [comment] 2023-07-23 05:53
Great, @workingjubilee ! I'm happy to see this!

**Comment by bcardarella** [comment] 2023-09-08 12:46
am I understanding this issue as indicating that the TvOS simulator is supported? We cannot compile to it but we can compile directly to TvOS

**Comment by bcardarella** [comment] 2023-09-08 12:56
Just to confirm I'm on the correct version of rustc:

```
➜  ~ rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)
➜  ~ rustc --print target-list | grep tvos
aarch64-apple-tvos
x86_64-apple-tvos
```

**Comment by workingjubilee** [comment] 2023-09-09 01:20
The tuple naming may be somewhat nonintuitive. The `x86_64-apple-tvos` target *is* a simulator target, and the `aarch64-apple-tvos` target is not, as you can see by the table in comex's original post. I hope that clarifies things? If you desire a rename, more tuples, etc., I recommend pursuing that in a new proposal as due to various circumstances this one is about to be out-of-date for any discussion of how these targets actually are.

**Comment by bcardarella** [comment] 2023-09-09 01:37
@workingjubilee you're right, let me dig in and see why we're not able to compile for the simulator. Thank you for the quick reply

**Comment by bcardarella** [comment] 2023-09-09 02:16
@workingjubilee wouldn't the `x86_64-apple-tvos` architecture not work on the M1/M2 macs as the simulator?

**Comment by bcardarella** [comment] 2023-09-09 02:17
For example, if I get the compiler targets for WatchOS:

```
➜  ~ rustc --print target-list | grep watchos
aarch64-apple-watchos-sim
arm64_32-apple-watchos
armv7k-apple-watchos
x86_64-apple-watchos-sim
```

it includes both the x86 and aarch64 targets for the simulator

**Comment by bcardarella** [comment] 2023-09-09 02:19
This is Swift's own:

https://github.com/apple/swift/blob/ffbc65c8c48cb38db190fa0618fe2b5937a334b8/utils/build-script-impl#L649-L658

**Comment by workingjubilee** [comment] 2023-09-09 02:47
> @workingjubilee wouldn't the `x86_64-apple-tvos` architecture not work on the M1/M2 macs as the simulator?

Uhhh, it probably seems obvious to you, but for some reason I am missing the last 20% of context here so I'm not immediately certain what you're actually asking. Which is the other reason why I suggested you open a new issue: It would be nice to see the full "problem statement" ("I want to do X, I tried Y, it didn't work, this was what the compiler vomited out").

You can @ me in that issue if you want my attention specifically, but it is also more likely to get attention in general, because it _will_ be visible to people immediately triaging the issues (especially recently-opened ones). And we may need to determine it's a regression and triage it as such and so on.
