### ISSUE TITLE
Make errors without a span not output a span

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22222] opened 2015-02-12 14:35 UTC
E.g. 
```
../../../src/librustc_driver/lib.rs:1:1: 1:1 error: multiple dylib candidates for `std` found
../../../src/librustc_driver/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                                      ^
../../../src/librustc_driver/lib.rs:1:1: 1:1 note: candidate #1: /home/julian/rust/rust/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4e7c5e5c.so
../../../src/librustc_driver/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                                      ^
../../../src/librustc_driver/lib.rs:1:1: 1:1 note: candidate #2: /home/julian/rust/rust/x86_64-unknown-linux-gnu/stage1/lib/libstd-4e7c5e5c.so
../../../src/librustc_driver/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                                      ^
```

**Comment by nagisa** [comment] 2015-02-12 14:52
A more generic duplicate of #21021

**Comment by aochagavia** [comment] 2015-02-13 19:58
I guess this would require introducing a new `unspanned_err` method in `Session`. However, I am not so sure of the name `unspanned_err`. Do you have any ideas?

**Comment by nagisa** [comment] 2015-02-13 20:01
Alternative would be to simply not print any span if it is empty. I suppose we could call one empty if its both low and high bytes are set to 0.

**Closed** 2015-04-11 19:24 UTC
Labels: A-diagnostics, I-papercut
