### ISSUE TITLE
Lifetime error when indexing with borrowed index in beta but not in stable

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#74933] opened 2020-07-30 04:26 UTC
I tried to compile this code:

```rust
use std::mem;
use std::ops::{Index, IndexMut};

pub struct FieldMap;

pub fn insert(this: &mut FieldMap, field: &Field<'_>, value: ()) -> () {
    this[field] = value;
}

pub struct Field<'a> {
    x: &'a (),
}

impl<'a> Index<&'a Field<'a>> for FieldMap {
    type Output = ();

    fn index(&self, _: &'a Field<'a>) -> &() {
        unimplemented!()
    }
}

impl<'a> IndexMut<&'a Field<'a>> for FieldMap {
    fn index_mut(&mut self, _: &'a Field<'a>) -> &mut () {
        unimplemented!()
    }
}
```
I expected the code to compile

Instead, it failed to compile with this lifetime error:

```
error[E0623]: lifetime mismatch
 --> src/lib.rs:7:5
  |
6 | pub fn insert(this: &mut FieldMap, field: &Field<'_>, value: ()) -> () {
  |                                           ----------
  |                                           |
  |                                           these two types are declared with different lifetimes...
7 |     this[field] = value;
  |     ^^^^^^^^^^^ ...but data from `field` flows into `field` here
```

### Workarounds

If I change the function in these ways it compiles.

https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=ca6b8a2243d7116cb8180bb4300f6edc
```rust
pub fn insert<'a,'b,'c>(this: &'a mut FieldMap, field: &'b Field<'c>, value: ()) -> () {
    this[field as &'b Field<'b>] = value;
}
```

https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=21326b3dcd6c017d0e644ef7eab89769
```rust
pub fn insert<'a,'b,'c>(this: &'a mut FieldMap, field: &'b Field<'c>, value: ()) -> () {
    *this.index_mut(field) = value;
}
```

### Meta

This **compiles successfully** on Stable Rust 1.45.0 back to 1.26.0 (when `'_` lifetimes were stabilized)

This **fails to compile** on these versions(haven't tried previous ones in the same channels):

- 1.46.0-beta.2 (2020-07-23 6f959902b3103c49ca98)
- 1.47.0-nightly (2020-07-28 a7eff79135de09a49b50)

This issue has been assigned to @nbdd0121 via [this comment](https://github.com/rust-lang/rust/issues/74933#issuecomment-666502305).

**Comment by LeSeulArtichaut** [comment] 2020-07-30 09:08
Let’s find the culprit for this. @rustbot ping cleanup

**Comment by spastorino** [comment] 2020-07-30 13:23
Assigning `P-critical` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts) and removing `I-prioritize`.

**Comment by spastorino** [comment] 2020-07-30 13:37
```
searched nightlies: from nightly-2020-06-19 to nightly-2020-07-11
regressed nightly: nightly-2020-06-20
searched commits: from https://github.com/rust-lang/rust/commit/e55d3f9c5213fe1a25366450127bdff67ad1eca2 to https://github.com/rust-lang/rust/commit/2d8bd9b74dc0cf06d881bac645698ccbcf9d9c5e
regressed commit: https://github.com/rust-lang/rust/commit/72417d84fb51495a4f1d007fb2397a0b2609ab63
```

Regressed in https://github.com/rust-lang/rust/pull/73504 which is a roll-up, likely https://github.com/rust-lang/rust/pull/72280

**Comment by spastorino** [comment] 2020-07-30 13:38
cc @nbdd0121

**Comment by lcnr** [comment] 2020-07-30 14:53
The explicit lifetimes are
```rust
pub fn insert<'a, 'b>(this: &mut FieldMap, field: &'b Field<'a>, value: ()) -> () {
    this[field] = value;
}
```

**Comment by pnkfelix** [comment] 2020-07-30 14:54
assigning to @nikomatsakis but they will probably need to delegate as there time is limited in near future.

**Comment by nbdd0121** [comment] 2020-07-30 16:19
Will look into this today.

@rustbot claim

**Comment by nbdd0121** [comment] 2020-07-30 20:20
Okay, this is an issue near convert_place_op_to_mutable. Just re-infer the index type and re-do the coercion is sufficient to fix the regionck failure (https://github.com/nbdd0121/rust/commit/375a6d073b5944fecc7ca48c0e7ff53154180b2c).

However I am not sure why the existing code does not work. This piece of code is last touched in #72068. cc @estebank @oli-obk do you have any clue why the existing approach does not work well with regionck?

**Comment by oli-obk** [comment] 2020-07-31 09:50
Hmm.. I would not have expected that code to have to change, since the failure seems to try to make the anonymous lifetime on `&mut self` in the `index_mut` method match `'a`, which it should not. I think your patch is sound, but touching the "wrong" thing. Basically now we are creating new lifetimes for the index, when I would have thought that the container type's reference's lifetime needs adjustment. So looking at `convert_place_op_to_mutable`, I'm guessing https://github.com/nbdd0121/rust/blob/375a6d073b5944fecc7ca48c0e7ff53154180b2c/src/librustc_typeck/check/place_op.rs#L308 is taking the wrong region and should instead invent a new one?

**Comment by nbdd0121** [comment] 2020-07-31 15:33
@oli-obk This issue is not related to anonymous lifetime actually, if you spell out the lifetime explicitly it's still the same. The root cause has been identified and that line actually *is* the culprit, a detailed analysis can be found in #74960.

**Comment by rodrimati1992** [comment] 2020-07-31 17:49
I added a couple of examples of workarounds that allowed the function to compile, with the same signature.

**Closed** 2020-08-12 06:38 UTC
Labels: C-bug, P-critical, T-compiler, regression-from-stable-to-beta
