### ISSUE TITLE
HashSet/HashMap nesting results to methods not being defined properly

### ISSUE THREAD

**Issue by tijs14tijs** [rust-lang/rust#25946] opened 2015-06-01 19:51 UTC
###### This compiles just fine:
```rust
fn x(input: HashSet<usize>) {
    for i in input.iter() {}
}
```

###### This gives compile time error:
no method named `iter` found for type `std::collections::hash::set::HashSet<std::collections::hash::set::HashSet<usize>>` in the current scope

```rust
fn x(input: HashSet<HashSet<usize>>) {
    for i in input.iter() {}
}
```

I tested this code on multiple versions of rust using play.rust-lang.org and all versions seem to be affected in the same way. I also noticed that using a HashMap results to the same issue, and in both cases not only iter() is gone, but no single method seems to work. (I only tested ```iter(), capacity() and clear()```)

**Comment by tijs14tijs** [comment] 2015-06-01 19:54
Here is a live source code example http://is.gd/AEf0vx

**Comment by alexcrichton** [comment] 2015-06-01 20:31
This is actually because `HashSet<T>` does not itself implement `Hash`, so this is a dupe of https://github.com/rust-lang/rust/issues/20941, but thanks for the report!

**Closed by alexcrichton** 2015-06-01 20:31 UTC
