### ISSUE TITLE
'a: while break 'a{} results in illigal instruction

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#50856] opened 2018-05-18 10:06 UTC
Having the following main function results in an illigal instruction on stable, beta and nighlty.
It should be noted that when `n` is not used after the loop, the illigal instruction does not occur
https://play.rust-lang.org/?gist=96a11fd41327de4bf4e2c371dd7c1660&version=stable&mode=debug

```Rust
fn main() {
    let mut n = 0; 
    'a: while {break 'a; true} {
        n += 1;
    }
    n += 2;
}
```

Interestingly putting the same while-loop in a function works fine:
https://play.rust-lang.org/?gist=ed60d2118b970be39e09bc8653a25345&version=stable&mode=debug

**Comment by DutchGhost** [comment] 2018-05-18 10:32
Update:
A more simple version that also results in an illigal instruction:
https://play.rust-lang.org/?gist=489a23ba854eea0b1e435b447ba81dc1&version=stable&mode=debug
```Rust
fn main() {
   'a: while {break 'a; true} { }
   1;
}
```

**Comment by kennytm** [comment] 2018-05-18 19:28
Checking [the last example](https://github.com/rust-lang/rust/issues/50856#issuecomment-390166648) with godbolt,

* 1.25 and above: results in undefined instruction (this issue)
* 1.18 to 1.24: ICE with broken MIR
* 1.17: becomes no-op 
* 1.16 and below: Error "use of undeclared label `'a`"

**Comment by kennytm** [comment] 2018-05-18 19:48
Err the last example is even featured in [E0590](https://doc.rust-lang.org/stable/error-index.html#E0590) (introduced in #39864), but why this seems not tested at all 😒.

**Comment by varkor** [comment] 2018-05-18 21:31
> Err the last example is even featured in E0590 (introduced in #39864), but why this seems not tested at all 😒.

It's because in the example that is tested, there's no semicolon:
```rust
fn main() {
    'foo: while break 'foo {} // ok
}
```
```rust
fn main() {
    'foo: while break 'foo {}; // uh-oh
}
```
_Why_ that makes a difference, I haven't determined yet.

**Comment by kennytm** [comment] 2018-05-19 07:14
The problem is, for some reason, the type checker inferred `'a: while break 'a {};` to have type `!`, and thus the rest of the block is `unreachable`.

```rust
// compile-pass, but shouldn't.
#![feature(never_type)]
fn main() {
    let _: ! = { 'a: while break 'a {}; };
}
```

However, without the `;` the inferred type is just `()` as expected.

**Comment by varkor** [comment] 2018-05-19 09:18
Maybe slightly off-topic, but why are references to the label even allowed in the condition, rather than solely the body? You don't achieve extra expressiveness, as it's equivalent to returning false in the condition, and it makes things more complicated.

**Comment by DutchGhost** [comment] 2018-05-19 09:38
having code like this results in an ICE:

```Rust
const ARR: [(); 0] = [ 'a: while break 'a {}; 0];

fn main() {
    
}
```

```
error: internal compiler error: librustc_mir/transform/qualify_consts.rs:273: multiple assignments to _1
 --> src/main.rs:1:24
  |
1 | const ARR: [(); 0] = [ 'a: while break 'a {}; 0];
  |                        ^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:488:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0 (a77568041 2018-05-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.
```

https://play.rust-lang.org/?gist=56a8ce6081021416d64f4a056aeae8ca&version=stable&mode=debug

**Comment by nagisa** [comment] 2018-05-20 09:04
> Maybe slightly off-topic, but why are references to the label even allowed in the condition, rather than solely the body? You don't achieve extra expressiveness, as it's equivalent to returning false in the condition, and it makes things more complicated.

Because it is consistent with the desugaring of the while loop to a

```
'a: loop {
    if {break 'a} { break 'a }
}
```

which is a valid and fairly sensible code.

**Comment by nikomatsakis** [comment] 2018-05-24 14:33
I think the bug in in the type-checker then: it should not be giving `'a: while (break 'a)` the type of `!`, clear. @varkor — you interested in fixing? I can give a few tips...

**Comment by nikomatsakis** [comment] 2018-05-24 14:36
Marking as P-medium: technically a regression, but a very old one, and kind of a corner case. Still, I'll try to leave some notes on how to fix.

**Comment by varkor** [comment] 2018-05-24 15:26
@nikomatsakis: yeah, I can have a look into this. Might be a little delayed, but definitely within the next couple of weeks.

**Closed** 2018-05-26 21:26 UTC
Labels: A-typesystem, C-bug, I-unsound 💥, P-medium, T-compiler, regression-from-stable-to-stable
