### ISSUE TITLE
"invalid subrange count" LLVM error for large array of ZST

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#90805] opened 2021-11-11 18:38 UTC
I tried this code: <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=dc8566273663f5b7628c581a30dc3cfd>

```rust
fn main() {
    let _a = [(); usize::MAX-1];
}
```

But in debug mode only it fails with the following:

```text
invalid subrange count
!179 = !DISubrange(count: -2, lowerBound: 0)
invalid subrange count
!179 = !DISubrange(count: -2, lowerBound: 0)
LLVM ERROR: Broken module found, compilation aborted!
```

(Repro'd on playground with nightly 2021-11-09)

**Comment by tmiasko** [comment] 2022-01-21 18:19
Duplicate of #34127

**Closed by tmiasko** 2022-01-21 18:19 UTC
Labels: A-LLVM, A-debuginfo, C-bug
