### ISSUE TITLE
Stability is not checked for glob imports

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#23049] opened 2015-03-04 23:43 UTC
Just what it says on the tin: this is especially a problem when importing an unstable trait with stable methods.

**Comment by steveklabnik** [comment] 2015-12-18 22:46
Without `staged_api` anymore, I am not even sure of an easy way to reproduce this outside of the standard library itself...

**Comment by petrochenkov** [comment] 2015-12-18 23:18
Maybe I'm missing something, but what is the problem here?

Assume we imported something unstable with a glob import. We still have to name it to use it and the moment we name it it's caught by a stability checker (modulo bugs like https://github.com/rust-lang/rust/issues/30209).

**Comment by alexcrichton** [comment] 2015-12-18 23:25
This is pretty orthogonal to `staged_api` (this is still very relevant for libstd), but I believe this is still relevant for trait imports. We have to be careful to not have unstable traits with stable methods that *aren't* in the prelude because otherwise via this bug you can `use std::foo::*` and then call the methods.

**Comment by petrochenkov** [comment] 2015-12-18 23:53
>We have to be careful to not have unstable traits with stable methods that aren't in the prelude because otherwise via this bug you can use std::foo::* and then call the methods.

But.. if a method is explicitly marked as stable then we certainly can call it. I don't think it's a bug, it's just something library maintainers have to be aware of  - "don't make methods stable if you don't want people to call them on stable".

**Comment by alexcrichton** [comment] 2015-12-19 00:45
Perhaps, yeah, although I vaguely remember there being other reasons why this bug was opened that I can't quite recall now.

**Comment by bluss** [comment] 2015-12-19 06:56
This code compiles in the stable channel and it's not intentional:

```rust
fn main() {
    let s = SliceConcatExt::concat(&[""][..]);
}
```

The trait itself is supposed to be unstable, not usable by name like this.

**Comment by petrochenkov** [comment] 2015-12-19 10:59
@bluss 
This is covered by https://github.com/rust-lang/rust/issues/30209

**Comment by petrochenkov** [comment] 2017-02-19 21:57
Closing as per https://github.com/rust-lang/rust/issues/23049#issuecomment-165922872

**Closed by petrochenkov** 2017-02-19 21:57 UTC
Labels: A-lint
