### ISSUE TITLE
Add docs for keywords

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#51451] opened 2018-06-09 12:30 UTC
Since the `#[doc(keyword = "...")]` feature has been merged, we can now add documentation for keywords.

cc @rust-lang/docs

**Comment by QuietMisdreavus** [comment] 2018-06-14 20:36
Quickly dumping a list of the keywords in the compiler, based on [this list](https://github.com/rust-lang/rust/blob/2612bbcba08dd81730edd8f2139005fb7a409294/src/libsyntax_pos/symbol.rs#L328-L404). Pretty sure we don't need or want to make a page for *all* of them, but at least we can start from something. They're broken into sections with their explanatory comment.

"Special reserved identifiers used internally for elided lifetimes,
unnamed method parameters, crate root module, error recovery etc."

- [ ] `$crate`
- [ ] `_`

"Keywords used in the language."

- [ ] `as`
- [ ] `box`
- [ ] `break`
- [ ] `const`
- [ ] `continue`
- [ ] `crate`
- [ ] `else`
- [ ] `enum`
- [ ] `extern`
- [ ] `false`
- [ ] `fn`
- [ ] `for`
- [ ] `if`
- [ ] `impl`
- [ ] `in`
- [ ] `let`
- [ ] `loop`
- [ ] `match`
- [ ] `mod`
- [ ] `move`
- [ ] `mut`
- [ ] `pub`
- [ ] `ref`
- [ ] `return`
- [ ] `self`
- [ ] `Self`
- [ ] `static`
- [ ] `struct`
- [ ] `super`
- [ ] `trait`
- [ ] `true`
- [ ] `type`
- [ ] `unsafe`
- [ ] `use`
- [ ] `where`
- [ ] `while`

"Keywords reserved for future use."

- [ ] `abstract`
- [ ] `alignof`
- [ ] `become`
- [ ] `do`
- [ ] `final`
- [ ] `macro`
- [ ] `offsetof`
- [ ] `override`
- [ ] `priv`
- [ ] `pure`
- [ ] `sizeof`
- [ ] `typeof`
- [ ] `unsized`
- [ ] `virtual`
- [ ] `yield`

"Edition-specific keywords reserved for future use."

- [ ] `async`

"Special lifetime names"

- [ ] `'_`
- [ ] `'static`

"Weak keywords, have special meaning only in specific contexts."

- [ ] `auto`
- [ ] `catch`
- [ ] `default`
- [ ] `dyn`
- [ ] `union`

**Comment by GuillaumeGomez** [comment] 2018-06-15 10:04
I'll write the docs for one keyword so then we can open it for newcomers.

**Comment by bookofportals** [comment] 2018-11-03 19:48
@iirelu Which of these were you planning on doing?

**Comment by iirelu** [comment] 2018-11-04 05:57
I don't have the free time to write docs any more, so I'm hoping someone else continues where I left off.

**Comment by bookofportals** [comment] 2018-11-04 07:12
Alright, thanks. I may do some then.

**Comment by bookofportals** [comment] 2018-11-05 07:33
I am now working on this.

**Comment by bookofportals** [comment] 2019-02-05 08:35
Sorry for the lack of an update. I don’t have time for this at the moment. If I have a chance, I’ll open a PR with what I have although honestly it's mostly additions to the existing ones rather than anything new.

**Comment by DevQps** [comment] 2019-04-02 17:53
Just as an update, some keywords have been fixed:
- const
- if
- enum
- extern
- true/false (are referred to the primitive type boolean)
- as 
- crate

**Comment by steveklabnik** [comment] 2019-04-02 18:54
Closing as a duplicate of https://github.com/rust-lang/rust/issues/34601, it's older.

**Closed by steveklabnik** 2019-04-02 18:54 UTC
Labels: P-medium, T-doc
