### ISSUE TITLE
Unhelpful rustdoc [src] link for struct generated by macro

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#47817] opened 2018-01-28 03:59 UTC
In https://github.com/dtolnay/syn/issues/304 we have a macro_rules macro that adds some derive attributes to most of our syntax tree structs. Conceptually it looks like this:

```rust
macro_rules! ast_struct {
    (pub struct $name:ident $body:tt) => {
        #[derive(Clone)]
        pub struct $name $body
    }
}

ast_struct! {
    pub struct S {
        /* ... */
    }
}
```

In our case the macro definition and invocation are always in different files but the code above is sufficient to reproduce the issue. If you document this code with `cargo doc`, the [src] link at the top of *struct.S.html* points to the line `pub struct $name $body`, as far as I can tell because this is where the first non-attribute token (`pub`) of the final struct definition came from.

I propose that it would be more often correct to have [src] point to wherever the \*name\* token of the item came from, in this case the $name token which originates from the line `pub struct S`.

**Comment by jyn514** [comment] 2020-09-07 01:20
Closing as duplicate of https://github.com/rust-lang/rust/issues/39726

**Closed by jyn514** 2020-09-07 01:20 UTC
Labels: C-enhancement, T-dev-tools, T-rustdoc
