### ISSUE TITLE
Compiler error on resolving bounds after type-checking

### ISSUE THREAD

**Issue by Lapz** [rust-lang/rust#43391] opened 2017-07-21 18:50 UTC
It tried building this project [stylish](https://github.com/Thinkofname/stylish) on the latest version of rust and when I try I get a internal compiler error.

I tried this code `cargo run -p stylish_webrender --example demo --release`

I expected the code to compile fully but instead got this error message:

``` rust
error: internal compiler error: src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<CB as audio::AudioCallback>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (ae98ebfcb 2017-07-20) running on x86_64-apple-darwin

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:437:8
```

## Meta

**rustc --version --verbose:** 
```
rustc 1.20.0-nightly (ae98ebfcb 2017-07-20)
binary: rustc
commit-hash: ae98ebfcb9ad5a5384fd229a6ee91315b02ca969
commit-date: 2017-07-20
host: x86_64-apple-darwin
release: 1.20.0-nightly
LLVM version: 4.0
```

Backtrace:

```rust 
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_new
   5: rustc_errors::Handler::span_bug
   6: rustc::session::opt_span_bug_fmt::{{closure}}
   7: rustc::session::opt_span_bug_fmt
   8: rustc::session::span_bug_fmt
   9: <&'gcx rustc::ty::TyS<'gcx> as rustc::infer::TransNormalize<'gcx>>::trans_normalize
  10: rustc::infer::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'tcx>>::normalize_associated_type_in_env
  11: rustc::ty::layout::Layout::compute_uncached
  12: rustc::ty::util::layout_raw
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::layout_raw<'tcx>>::try_get
  14: rustc::ty::maps::TyCtxtAt::layout_raw
  15: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::layout_raw
  16: rustc_const_eval::eval::eval_const_expr_partial::{{closure}}
  17: rustc_const_eval::eval::eval_const_expr_partial
  18: rustc_const_eval::eval::eval_const_expr_partial
  19: rustc_const_eval::eval::eval_const_expr_partial
  20: rustc_const_eval::eval::eval_const_expr_partial
  21: rustc_const_eval::eval::ConstContext::eval
  22: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  23: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  24: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  25: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  26: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  27: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  28: rustc_passes::consts::check_crate
  29: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  30: rustc_driver::driver::phase_3_run_analysis_passes
  31: rustc_driver::driver::compile_input
  32: rustc_driver::run_compiler
```

**Comment by qnighy** [comment] 2017-07-22 15:05
Duplicate of #43394?

**Closed** 2017-08-04 14:15 UTC
Labels: C-bug, I-ICE
