### ISSUE TITLE
ICE: opaque type with non-universal region args

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#111906] opened 2023-05-24 13:03 UTC
all of the following examples result in the same ICE and should imo all be added as test cases once this is fixed:

this one should pass
```rust
fn foo<'a: 'a>() -> impl Sized {
    let _: () = foo::<'a>();
    loop {}
}
```
this one should error afaik
```rust
fn foo<'a: 'a>() -> impl Sized {
    let _: *mut &'a () = foo::<'a>();
    loop {}
}
```
this one should pass
```rust
fn foo<'a: 'a>() -> impl Sized + 'a {
    let _: *mut &'a () = foo::<'a>();
    loop {}
}
```
this one should error
```rust
trait Trait<'a, 'b> {}
impl<'a, 'b, T> Trait<'a, 'b> for T {}

fn foo<'a: 'a, 'b: 'b>() -> impl Trait<'a, 'b> {
    let _: *mut &'a () = foo::<'a, 'b>();
    let _: *mut &'b () = foo::<'a, 'b>();
    loop {}
}
```

they all ICE with
```rust
rror: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: opaque type with non-universal region substs
 --> src/lib.rs:2:12
  |
2 |     let _: () = foo::<'a>();
  |            ^^
  |
  = note: delayed at compiler/rustc_borrowck/src/region_infer/opaque_types.rs:94:35
```

**Comment by matthiaskrgr** [comment] 2023-05-24 17:02
Will this be fixed by https://github.com/rust-lang/rust/pull/110844 ?

**Comment by aliemjay** [comment] 2023-05-25 07:56
This is a regression of #103491. Cc @cjgillot.

The error variants should be changed to make the lifetime invariant. Otherwise we would infer `'static`:
```diff
fn foo<'a: 'a>() -> impl Sized {
-    let _: &'a () = foo::<'a>();
+    let _: *mut &'a () = foo::<'a>();
    loop {}
}
```

**Comment by matthiaskrgr** [comment] 2023-08-20 07:02
Right now ( rustc 1.73.0-nightly (6ef7d16be 2023-08-19) ) it seems that 1 and 3 still ICE and 2 and 4 error.
@rustbot prioritize since this affects stable

**Closed** 2024-03-28 11:56 UTC
Labels: I-ICE, P-high, T-compiler, regression-from-stable-to-stable, A-impl-trait, C-bug, glacier
