### ISSUE TITLE
On nightly rustc, E0599 emits a massive diagnostic to suggest wrapping the receiver in every combination of `{Box,Pin,Rc,Arc}::new({,&,&mut} expr)`

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust#84769] opened 2021-05-01 00:11 UTC
Given the following code ([playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=d129ca6f7559fe24438efcefc14eec4c)):

```rust
trait Bar {}
impl Bar for String {}

fn main() {
  let s = String::from("hey");
  let x: &dyn Bar = &s;
  x.as_ref();
}
```

The output on `1.53.0-nightly (2021-04-29 478a07df05e3fe8df964)` is:

<details>
<summary>Long diagnostic</summary>

```
error[E0599]: the method `as_ref` exists for reference `&dyn Bar`, but its trait bounds were not satisfied
   --> src/main.rs:7:5
    |
1   | trait Bar {}
    | --------- doesn't satisfy `dyn Bar: AsRef<_>`
...
7   |   x.as_ref();
    |     ^^^^^^ method cannot be called on `&dyn Bar` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `dyn Bar: AsRef<_>`
            which is required by `&dyn Bar: AsRef<_>`
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Box::new(x).as_ref();
    |   ^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Pin::new(x).as_ref();
    |   ^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Arc::new(x).as_ref();
    |   ^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Rc::new(x).as_ref();
    |   ^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Box::new(&mut x).as_ref();
    |   ^^^^^^^^^^^^^  ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Pin::new(&mut x).as_ref();
    |   ^^^^^^^^^^^^^  ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Arc::new(&mut x).as_ref();
    |   ^^^^^^^^^^^^^  ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Rc::new(&mut x).as_ref();
    |   ^^^^^^^^^^^^  ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Box::new(&x).as_ref();
    |   ^^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Pin::new(&x).as_ref();
    |   ^^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Arc::new(&x).as_ref();
    |   ^^^^^^^^^^ ^
help: consider wrapping the receiver expression with the appropriate type
    |
7   |   Rc::new(&x).as_ref();
    |   ^^^^^^^^^ ^
```
</details>

`Box`, `Pin`, `Arc`, and `Rc` are suggested three times each: once for `x`, once for `&x`, and once for `&mut x`. I'm not sure if this is a problem, but this seems incredibly verbose to me.

Note that the output on stable 1.51 and beta 1.52 is different:
```
error[E0599]: the method `as_ref` exists for reference `&dyn Bar`, but its trait bounds were not satisfied
 --> src/main.rs:7:5
  |
1 | trait Bar {}
  | --------- doesn't satisfy `dyn Bar: AsRef<_>`
...
7 |   x.as_ref();
  |     ^^^^^^ method cannot be called on `&dyn Bar` due to unsatisfied trait bounds
  |
  = note: the following trait bounds were not satisfied:
          `dyn Bar: AsRef<_>`
          which is required by `&dyn Bar: AsRef<_>`
  = help: items from traits can only be used if the trait is implemented and in scope
  = note: the following trait defines an item `as_ref`, perhaps you need to implement it:
          candidate #1: `AsRef`
```

**Comment by PatchMixolydic** [comment] 2021-05-01 00:20
My mistake, each repetition is actually different in that two suggest taking a reference to `x`:
```
7   |   Box::new(x).as_ref()
7   |   Box::new(&x).as_ref()
7   |   Box::new(&mut x).as_ref()
```

This still seems like a fairly massive diagnostic, though.

**Comment by Aaron1011** [comment] 2021-05-01 14:15
cc @estebank

**Comment by PatchMixolydic** [comment] 2021-05-01 19:31
Might be a duplicate of #84792, or at least fixed by the same PR that fixed it

**Comment by workingjubilee** [comment] 2021-05-01 21:40
Even if it was considered reasonable to suggest each and every possible type combination, there is no pressing reason for it to generate the intervening lines as well.

**Comment by camelid** [comment] 2021-05-01 22:46
> This remains unpatched on nightly, and is thus a stable-to-beta diagnostic regression.

AFAICT, this is *not* present on beta, and is only present on nightly, so it's a stable-to-nightly regression.

**Comment by steffahn** [comment] 2021-05-01 23:21
searched nightlies: from nightly-2021-01-01 to nightly-2021-04-24
regressed nightly: nightly-2021-04-09
searched commits: from https://github.com/rust-lang/rust/commit/361bfce305b8829eda7f3d133fe82a118685de1f to https://github.com/rust-lang/rust/commit/2e495d2e845cf27740e3665f718acfd3aa17253e
regressed commit: https://github.com/rust-lang/rust/commit/21185265915d0d472f3f0f54642700c7c693c7d7

That is:
```
Rollup of 5 pull requests

Successful merges:

 - #82497 (Fix handling of `--output-format json` flag)
 - #83689 (Add more info for common trait resolution and async/await errors)
 - #83952 (Account for `ExprKind::Block` when suggesting .into() and deref)
 - #83965 (Add Debug implementation for hir::intravisit::FnKind)
 - #83974 (Fix outdated crate names in `rustc_interface::callbacks`)
```
so it’s #83689. I guess @estebank has already been mentioned.

**Comment by estebank** [comment] 2021-05-02 00:22
Yes, yes, I introduced this regression. Mea culpa, everybody. In my defense I keep flip-flopping between being too restrictive and too permissive for new suggestions and someone always ends up getting the short end of the stick. This week, I'm leaning towards "too permissive" and if the suggestion triggers too often, _then_ detect the cases and make it more constrained, because the alternative is that the suggestion isn't shown when _it could_. This is IMO better, as long as regressions are caught in nightly, like it was in this case.&lt;/rant>

Anyways, #84808 fixes this.

**Comment by JohnTitor** [comment] 2021-05-02 08:46
Assigning `P-high` [as discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts) and removing `I-prioritize`.

**Comment by pietroalbini** [comment] 2021-05-04 15:36
This now affects 1.53.0 beta. Updating the labels accordingly.

**Comment by pietroalbini** [comment] 2021-05-05 22:18
Still needs to be backported.

**Comment by apiraino** [comment] 2021-05-13 11:17
@pietroalbini @Mark-Simulacrum the beta backport for patch #84808 was approved, can this now be closed?

**Comment by Mark-Simulacrum** [comment] 2021-05-13 11:39
I think we should wait until it actually lands onto beta

**Comment by estebank** [comment] 2021-05-13 18:03
This was merged in beta already, right? https://github.com/rust-lang/rust/pull/84996

**Comment by Mark-Simulacrum** [comment] 2021-05-13 18:07
Ah, so it was.

**Closed by Mark-Simulacrum** 2021-05-13 18:07 UTC
Labels: A-diagnostics, D-verbose, P-high, T-compiler, regression-from-stable-to-beta
