### ISSUE TITLE
str's trim_left and trim_right implicitly assume LTR text

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#30459] opened 2015-12-18 13:09 UTC
These functions and their `_matches` variants operate on the start and end of the string, which are only the left and right (respectively) of the displayed text when rendered left-to-right like English. For (readers/users of) RTL languages, `trim_right` is hinting that it will be trimming the prefix, but this is of course not the case (and similarly for `_left`).

These are stable and there is precedent in other languages for left/right e.g. Python (there's also significant precedent for start/end), so we may not be able/want to do anything here, but it seems worth noting.

**Comment by sfackler** [comment] 2015-12-18 21:11
I seem to recall Android adding `start` and `end` variants of some alignment constraints and deprecating the old `left` and `right` versions for this reason.

**Comment by SimonSapin** [comment] 2015-12-19 00:07
+1 for `start` and `end`. CSS introduced the same keywords when generalizing text layout to RTL and vertical text. (And `inline-start`, `inline-end`, `block-start`, `block-end` when disambiguation is needed.)

How does the libs team feel about deprecating stable APIs?

**Comment by cybergeek94** [comment] 2015-12-19 11:20
Can confirm: `left`/`right` => `start`/`end` on Android. In XML the form only linted against; I don't know if it's deprecated in the Java APIs. It's kind of annoying because I also use `left`/`right` for layout alignments that shouldn't change between LTR and RTL.

**Comment by huonw** [comment] 2015-12-19 11:58
> Do we even have a way to detect an RTL configuration anyways? 

No we don't.

> Perhaps this is best left to an external crate to implement these methods as a precursor to a more general localization framework. 

Also, I don't really understand what you mean by an external crate doing this: there is absolutely no intention for these functions to change so to have right == start for RTL text, i.e. `trim_left` will always operate on the start and `trim_right` always on the end. Consistently trimming at the start/end no matter the direction of text seems likely to be the desired behaviour in most circumstances (i.e. even ones that encounter non-LTR text).

**Comment by SimonSapin** [comment] 2015-12-19 23:41
I don’t think anything in the standard library should behave differently based on text direction. This stuff is more complex than you might think: http://www.unicode.org/reports/tr9/

(If you really want to do proper text layout, it’s a job for https://github.com/servo/unicode-bidi and other crates.)

Left and right in `str::trim_left` and `str::trim_right` really mean lower memory addresses and higher memory addresses, so that naming is only correct when the text happens to be left-to-right. I’m proposing to add `str::trim_start` and `str::trim_end` with the same behavior, but more correct naming. And maybe deprecating the old names. Similarly with other methods with `left` and `right` in the name.

Methods with an `r` prefix (like `rfind`) have the same problem, but I don’t have a good replacement to suggest right now.

**Comment by cybergeek94** [comment] 2015-12-19 23:56
Okay, I see now. The text gets reversed during rendering--in memory the start of the string is at index `0` regardless of configuration. In that case I don't really have anything against the change itself.

As for the `r` prefix, I assumed it meant "reverse", which still makes sense in RTL. We can clarify that in documentation.

**Comment by SimonSapin** [comment] 2015-12-20 10:22
Yes, http://www.unicode.org/reports/tr9/#Introduction explains that memory representation of Unicode text is in "logical order" and gives some more details.

Ok, `rfind` as "reverse find" rather than "find from the right" works.

**Comment by aturon** [comment] 2016-01-08 19:52
**Libs team consensus**: for now, we should make sure the documentation is clear about exactly what's happening here. In the long run, we'd be interested in a deprecation/renaming, but we'd like to have some better tools in place to do so. 

The problem is that if we just deprecate it normally, all crates using the functionality have to choose between deprecation messages and upping the version of Rust they require. Neither choice is great.

The core team has discussed the idea of regular "long term support" releases, or otherwise some way to flag releases in a coarser-grained way. That can be useful for deprecations like this -- they would give something more like a small "epoch of Rust" to attach things like deprecations to, rather than forcing lib authors to just arbitrarily require Rust v1.7+ or whatever.

More broadly, we'd like to establish a policy for this kind of minor cleanup -- where the change makes things more clear, but doesn't close any fundamental holes or anything.

**Comment by SimonSapin** [comment] 2016-01-08 20:04
This is a very valid concern. Has a more fine-grained `#[allow(deprecated(some feature))]` been considered?

**Comment by aturon** [comment] 2016-01-08 20:07
@SimonSapin yes, that idea has come up from time to time, and would definitely be helpful here.

The main drawback is that it loses some of the point of deprecation -- if it's easy to opt out of the deprecation, there's little incentive to actually improve your code.

Of course, in this particular case the use of deprecation is more about discoverability/documentation/API clarity than improving existing code per se.

**Comment by SimonSapin** [comment] 2016-01-08 20:13
Other random idea: add the new name and deprecate the new one in a way that’s visible in the documentation but doesn’t emit a warning yet. (At least until the new name hits the stable channel.)

**Comment by aturon** [comment] 2016-01-08 20:16
@SimonSapin Yes, that's a feature we absolutely want -- basically, the ability to say "deprecated since Rust 1.8" or some other future release, and have the compiler/rustdoc do the right things.

I'll open an issue for it.

**Comment by aturon** [comment] 2016-01-08 20:29
cc #30785

**Comment by sfackler** [comment] 2016-01-08 20:32
A possible alternative to `#[allow(deprecated(some feature))]` is something like `#[allow(deprecated(after = "1.3.0"))]`, i.e. you saying that you explicitly are supporting back to 1.3, so deprecations made after that point are probably not relevant to you.

**Comment by aturon** [comment] 2016-01-08 20:34
Oh, and another idea we've talked about: the ability to `cfg` on specific feature stabilizations or perhaps Rust versions. That makes it more feasible to straddle deprecations.

**Comment by steveklabnik** [comment] 2016-01-26 17:50
Removing docs since my PR is in, now just a libs question if we want new versions.

**Comment by huonw** [comment] 2016-05-27 18:36
I believe #31202 closed this accidentally, at least, I can't see any documented decision from the libs team.

**Comment by varkor** [comment] 2018-04-10 20:49
Now that https://github.com/rust-lang/rust/issues/30785 is merged, it would be feasible to add unstable `str::trim_start` and `str::trim_end` and deprecate `str::trim_left` and `str::trim_right` in a future version.

cc @rust-lang/libs

**Closed** 2018-09-06 02:09 UTC
Labels: C-enhancement, T-libs
