### ISSUE TITLE
Different behavior of lifetimes with aliases

### ISSUE THREAD

**Issue by uselessgoddess** [rust-lang/rust#101380] opened 2022-09-03 12:55 UTC
I tried this code:
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ad21ff588d5588bec14d4d9b9f7d114e)
```rust
type Alias1<'a, T> = &'a mut dyn FnMut() -> T;
type Alias2<T> = dyn FnMut() -> T;

trait Foo {
    fn foo<T>(&self, t: Alias1<'_, T>) -> T {
        t()
    }

    fn bar<T>(&self, t: &'_ mut Alias2<T>) -> T {
        t()
    }

    fn test1<T, F: FnMut() -> T>(&self, mut f: F) -> T {
        self.foo(&mut f)
    }

    fn test2<T, F: FnMut() -> T>(&self, mut f: F) -> T {
        self.bar(&mut f)
    }
}
```
But this leads to a compilation error in the second case
```
error[E0310]: the parameter type `F` may not live long enough
  --> src\lib.rs:18:18
   |
18 |         self.bar(&mut f)
   |                  ^^^^^^ ...so that the type `F` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound...
   |
17 |     fn test2<T, F: FnMut() -> T + 'static>(&self, mut f: F) -> T {
   |                                 +++++++++
```
I don't understand why this is happening. Is this an error or is it expected?

**Comment by uselessgoddess** [comment] 2022-09-03 13:02
<details>
<summary>Also, if you annotate F as `'static`. We get a similar mir:</summary>

```rust
fn Foo::test1(_1: &Self, _2: F) -> T {
    debug self => _1;                    // in scope 0 at [src/lib.rs:13:34: 13:39](https://play.rust-lang.org/#)
    debug f => _2;                       // in scope 0 at [src/lib.rs:13:41: 13:46](https://play.rust-lang.org/#)
    let mut _0: T;                       // return place in scope 0 at [src/lib.rs:13:54: 13:55](https://play.rust-lang.org/#)
    let mut _3: &Self;                   // in scope 0 at [src/lib.rs:14:9: 14:25](https://play.rust-lang.org/#)
    let mut _4: &mut dyn std::ops::FnMut() -> T; // in scope 0 at [src/lib.rs:14:18: 14:24](https://play.rust-lang.org/#)
    let mut _5: &mut F;                  // in scope 0 at [src/lib.rs:14:18: 14:24](https://play.rust-lang.org/#)
    let mut _6: &mut F;                  // in scope 0 at [src/lib.rs:14:18: 14:24](https://play.rust-lang.org/#)

    bb0: {
        _3 = _1;                         // scope 0 at [src/lib.rs:14:9: 14:25](https://play.rust-lang.org/#)
        _6 = &mut _2;                    // scope 0 at [src/lib.rs:14:18: 14:24](https://play.rust-lang.org/#)
        _5 = &mut (*_6);                 // scope 0 at [src/lib.rs:14:18: 14:24](https://play.rust-lang.org/#)
        _4 = move _5 as &mut dyn std::ops::FnMut() -> T (Pointer(Unsize)); // scope 0 at [src/lib.rs:14:18: 14:24](https://play.rust-lang.org/#)
        _0 = <Self as Foo>::foo::<T>(move _3, move _4) -> [return: bb1, unwind: bb3]; // scope 0 at [src/lib.rs:14:9: 14:25](https://play.rust-lang.org/#)
                                         // mir::Constant
                                         // + span: [src/lib.rs:14:14: 14:17](https://play.rust-lang.org/#)
                                         // + literal: Const { ty: for<'r, 's> fn(&'r Self, &'s mut (dyn FnMut() -> T + 's)) -> T {<Self as Foo>::foo::<T>}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        drop(_2) -> bb2;                 // scope 0 at [src/lib.rs:15:5: 15:6](https://play.rust-lang.org/#)
    }

    bb2: {
        return;                          // scope 0 at [src/lib.rs:15:6: 15:6](https://play.rust-lang.org/#)
    }

    bb3 (cleanup): {
        drop(_2) -> bb4;                 // scope 0 at [src/lib.rs:15:5: 15:6](https://play.rust-lang.org/#)
    }

    bb4 (cleanup): {
        resume;                          // scope 0 at [src/lib.rs:13:5: 15:6](https://play.rust-lang.org/#)
    }
}

fn Foo::test2(_1: &Self, _2: F) -> T {
    debug self => _1;                    // in scope 0 at [src/lib.rs:17:44: 17:49](https://play.rust-lang.org/#)
    debug f => _2;                       // in scope 0 at [src/lib.rs:17:51: 17:56](https://play.rust-lang.org/#)
    let mut _0: T;                       // return place in scope 0 at [src/lib.rs:17:64: 17:65](https://play.rust-lang.org/#)
    let mut _3: &Self;                   // in scope 0 at [src/lib.rs:18:9: 18:25](https://play.rust-lang.org/#)
    let mut _4: &mut dyn std::ops::FnMut() -> T; // in scope 0 at [src/lib.rs:18:18: 18:24](https://play.rust-lang.org/#)
    let mut _5: &mut F;                  // in scope 0 at [src/lib.rs:18:18: 18:24](https://play.rust-lang.org/#)
    let mut _6: &mut F;                  // in scope 0 at [src/lib.rs:18:18: 18:24](https://play.rust-lang.org/#)

    bb0: {
        _3 = _1;                         // scope 0 at [src/lib.rs:18:9: 18:25](https://play.rust-lang.org/#)
        _6 = &mut _2;                    // scope 0 at [src/lib.rs:18:18: 18:24](https://play.rust-lang.org/#)
        _5 = &mut (*_6);                 // scope 0 at [src/lib.rs:18:18: 18:24](https://play.rust-lang.org/#)
        _4 = move _5 as &mut dyn std::ops::FnMut() -> T (Pointer(Unsize)); // scope 0 at [src/lib.rs:18:18: 18:24](https://play.rust-lang.org/#)
        _0 = <Self as Foo>::bar::<T>(move _3, move _4) -> [return: bb1, unwind: bb3]; // scope 0 at [src/lib.rs:18:9: 18:25](https://play.rust-lang.org/#)
                                         // mir::Constant
                                         // + span: [src/lib.rs:18:14: 18:17](https://play.rust-lang.org/#)
                                         // + literal: Const { ty: for<'r, 's> fn(&'r Self, &'s mut (dyn FnMut() -> T + 'static)) -> T {<Self as Foo>::bar::<T>}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        drop(_2) -> bb2;                 // scope 0 at [src/lib.rs:19:5: 19:6](https://play.rust-lang.org/#)
    }

    bb2: {
        return;                          // scope 0 at [src/lib.rs:19:6: 19:6](https://play.rust-lang.org/#)
    }

    bb3 (cleanup): {
        drop(_2) -> bb4;                 // scope 0 at [src/lib.rs:19:5: 19:6](https://play.rust-lang.org/#)
    }

    bb4 (cleanup): {
        resume;                          // scope 0 at [src/lib.rs:17:5: 19:6](https://play.rust-lang.org/#)
    }
}
```
</details>

**Comment by wwylele** [comment] 2022-09-03 14:25
My guess:

The aliases are expanded to the following:
```rust
// `dyn T` always has a hidden lifetime that the compiler need to guess
type Alias1<'a, T> = &'a mut dyn FnMut() -> T + 'a; // because it is behind a &'a ref, compiler guess the `dyn T` has `'a`
type Alias2<T> = dyn FnMut() -> T + 'static; // No other lifetime involved, the compiler can only guess `'static`
```
So `foo` and `bar eventually become
```rust
fn foo<T, 'a>(&self, t: &'a mut dyn FnMut() -> T + 'a) -> T {
        t()
    }

    fn bar<T, 'a>(&self, t: &'a mut dyn FnMut() -> T + 'static) -> T {
        t()
    }
```

**Comment by uselessgoddess** [comment] 2022-09-03 20:13
This seems to be the truth. 

```rust
trait Alias2<'a, T> = dyn FnMut() -> T + 'a;
```
and
```rust
trait Alias2<T> = FnMut() -> T;
```
this is confirmed

**Comment by QuineDot** [comment] 2022-09-03 21:29
Yes, in that context (type aliases), `dyn Trait` has an implicit `'static` lifetime while `&'a mut dyn Trait` has an implicit `'a` lifetime.  See the RFCs [linked from this part of the reference.](https://doc.rust-lang.org/reference/lifetime-elision.html#default-trait-object-lifetimes)

**Comment by fmease** [comment] 2024-01-26 01:09
Closing as works as intended then.

**Closed by fmease** 2024-01-26 01:09 UTC
Labels: A-lifetimes, T-compiler, C-discussion, A-trait-objects
