### ISSUE TITLE
rustdoc ICE "tried to get index of builtin macros crate"

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#63392] opened 2019-08-08 21:58 UTC
```
 Documenting fuchsia_vfs_pseudo_fs v0.1.0 (/b/s/w/ir/k/out/default/gen/garnet/public/rust/fuchsia-vfs/pseudo-fs/pseudo-fs)
error: internal compiler error: src/librustc/hir/def_id.rs:51: Tried to get crate index of builtin macros crate

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:649:9
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: rustc_errors::Handler::bug
   6: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   7: rustc::ty::context::tls::with_opt::{{closure}}
   8: rustc::ty::context::tls::with_context_opt
   9: rustc::ty::context::tls::with_opt
  10: rustc::util::bug::opt_span_bug_fmt
  11: rustc::util::bug::bug_fmt
  12: rustc::ty::query::__query_compute::crate_name
  13: rustc::dep_graph::graph::DepGraph::with_task_impl
  14: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  15: rustdoc::clean::inline::record_extern_fqn
  16: rustdoc::clean::register_res
  17: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  19: rustdoc::fold::DocFolder::fold_inner_recur
  20: rustdoc::fold::DocFolder::fold_item_recur
  21: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  23: rustdoc::fold::DocFolder::fold_inner_recur
  24: rustdoc::fold::DocFolder::fold_item_recur
  25: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  26: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  27: rustdoc::fold::DocFolder::fold_inner_recur
  28: rustdoc::fold::DocFolder::fold_item_recur
  29: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  30: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_crate
  31: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  32: rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}
  33: rustc_interface::passes::create_global_ctxt::{{closure}}
  34: rustc_interface::interface::run_compiler_in_existing_thread_pool
  35: rustdoc::core::run_core
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: std::panicking::try::do_call
  38: __rust_maybe_catch_panic
  39: rustc_driver::report_ices_to_stderr_if_any
  40: rustdoc::main_options
  41: std::thread::local::LocalKey<T>::with
  42: scoped_tls::ScopedKey<T>::set
  43: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (f9477a77c 2019-07-19) running on x86_64-unknown-linux-gnu

error: Could not document `fuchsia_vfs_pseudo_fs`.
```

**Comment by petrochenkov** [comment] 2019-08-08 22:00
Duplicate of https://github.com/rust-lang/rust/issues/61804, fixed in https://github.com/rust-lang/rust/pull/62086.

**Closed by petrochenkov** 2019-08-08 22:00 UTC
Labels: I-ICE, T-rustdoc

**Comment by matthewjasper** [comment] 2019-08-08 22:02
Can you check this with the latest nightly? This should have been fixed with the removal of the built-in macros crate. cc @petrochenkov

**Comment by cramertj** [comment] 2019-08-08 22:15
I can't unfortunately, but I believe you that it is fixed now. Reproduces on my version with just a doc comment containing "/// - [`file`]".
