### ISSUE TITLE
nightly docs missing methods

### ISSUE THREAD

**Issue by klensy** [rust-lang/rust#84596] opened 2021-04-26 16:56 UTC
Currently nightly docs on https://doc.rust-lang.org/ broken:
1. For some pages methods not shown in main area, for example: https://doc.rust-lang.org/nightly/std/primitive.str.html (no methods in main area, clicks on methods in left part don't scroll to methods)
2. For some methods links on the left side not clickable, for example https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html try to click `clear`, `dedup` (expecting to move to clicked methods, nothing instead).

Last 2 or maybe slightly more days.

@rustbot label +A-rustdoc

**Comment by ehuss** [comment] 2021-04-26 17:53
I believe this is being fixed in #84552.

**Comment by jyn514** [comment] 2021-04-26 21:40
Duplicate of https://github.com/rust-lang/rust/issues/84558

**Closed by jyn514** 2021-04-26 21:40 UTC
Labels: A-rustdoc, C-bug
