### ISSUE TITLE
-C inline-threshold is ignored by LLVM when optimizing for size, while llvm-args=-inline-threshold works

### ISSUE THREAD

**Issue by neivv** [rust-lang/rust#61088] opened 2019-05-23 16:47 UTC
```rust
pub fn copy_u32(input: &[u8; 4], output: &mut [u8; 4])  {
    let a = &input[..4];
    let b = &mut output[..4];
    for b in b.chunks_exact_mut(4) {
        b.copy_from_slice(a);
    }
}
```
Complied with `-C opt-level=s -C inline-threshold=300` produces (same as just `-C opt-level=s`)
```asm
example::copy_u32:
        mov     rax, rsi
        mov     rdx, rdi
        mov     esi, 4
        mov     ecx, 4
        mov     rdi, rax
        jmp     qword ptr [rip + core::slice::<impl [T]>::copy_from_slice@GOTPCREL]
```
Complied with `-C opt-level=s -C llvm-args=-inline-threshold=300` produces
```asm
example::copy_u32:
        mov     eax, dword ptr [rdi]
        mov     dword ptr [rsi], eax
        ret
```
([Godbolt link](https://godbolt.org/z/nm1weX))

[The cause appears to be that LLVM keeps using a separate inlining threshold from the "primary" one given by rustc on functions with `optsize` attribute, but only when it didn't receive `-inline-threshold` itself.](https://github.com/llvm/llvm-project/blob/27b3b5d952c5981bb850832c86c797616ece8dd6/llvm/lib/Analysis/InlineCost.cpp#L2181-L2185)

Fixing this seems to either require converting the rustc-received argument to LLVM commandline one, or constructing a custom `llvm::InlineParams` structure instead of using one of LLVM-provided helper functions?

**Comment by hudson-ayers** [comment] 2021-06-11 13:54
I observed on rust nightly 2020-09-22 that 

Compling with `-C opt-level=z -C inline-threshold=300` produces a binary with a different size from `-C opt-level=z -C inline-threshold=0` *and* a different size from `-C opt-level=Z -C llvm-args=-inline-threshold=300`. So it does not seem that -C inline-threshold is completely ignored (presumably because some functions end up not being marked with the `optsize` attribute?)

**Comment by workingjubilee** [comment] 2022-07-06 10:07
These are now identical due to recent changes to LLVM's pass manager, making this functionally a duplicate of the other issue on what to do with `-Cinline-threshold`.

**Closed by workingjubilee** 2022-07-06 10:07 UTC
Labels: A-LLVM, T-compiler, C-bug

**Comment by hudson-ayers** [comment] 2022-07-07 14:35
Are they now identical in that both do nothing? Or they both work the way that `llvm-args=-inline-threshold` used to work?

**Comment by workingjubilee** [comment] 2022-07-19 00:31
> Are they now identical in that both do nothing? Or they both work the way that `llvm-args=-inline-threshold` used to work?

My experimentation suggests they both appear to do nothing.
