### ISSUE TITLE
magnet_app-0.0.1 beta regression because of diesel

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43672] opened 2017-08-05 13:14 UTC
[magnet_app](https://crates.io/crates/magnet_app) version 0.0.1 regressed from stable to beta because it depends on diesel 0.7.1 and diesel broke ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/magnet_app-0.0.1/log.txt)):

```
Aug 03 09:39:48.109 INFO kablam! error: unexpected end of macro invocation
Aug 03 09:39:48.109 INFO kablam!   --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/diesel-0.7.1/src/connection/mod.rs:49:9
Aug 03 09:39:48.109 INFO kablam!    |
Aug 03 09:39:48.109 INFO kablam! 49 |         assert_eq!(self.get_transaction_depth(), 0);
Aug 03 09:39:48.109 INFO kablam!    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 03 09:39:48.109 INFO kablam!    |
Aug 03 09:39:48.109 INFO kablam!    = note: this error originates in a macro outside of the current crate
```

cc @stefanoc

**Comment by arielb1** [comment] 2017-08-05 14:13
Looks like there's a `column` macro in https://github.com/diesel-rs/diesel/blob/v0.7.1/diesel/src/macros/mod.rs. Duplicate of #43057.

**Comment by alexcrichton** [comment] 2017-08-10 13:17
Fixed in https://github.com/rust-lang/rust/pull/43735

**Closed by alexcrichton** 2017-08-10 13:17 UTC
Labels: regression-from-stable-to-beta, T-libs
