### ISSUE TITLE
Closure vs. method reference for Fn accepting a GAT type

### ISSUE THREAD

**Issue by audunhalland** [rust-lang/rust#89573] opened 2021-10-05 20:26 UTC
I tried this code:

```rust
#![feature(generic_associated_types)]

struct Foo(usize);
struct Bar<'s>(&'s usize);

impl<'s> Bar<'s> {
    fn hello(&self) {
        println!("Hello {}", self.0);
    }
}

trait HardToGAT: 'static {
    type Gat<'s>
    where
        Self: 's;

    fn hard_to_gat(&self, func: &dyn for<'s> Fn(&Self::Gat<'s>));
}

impl HardToGAT for Foo {
    type Gat<'s> = Bar<'s>;

    fn hard_to_gat(&self, func: &dyn for<'s> Fn(&Self::Gat<'s>)) {
        let bar = Bar(&self.0);
        func(&bar);
    }
}

#[test]
fn test() {
    let foo = Foo(42);

    // works:
    foo.hard_to_gat(&|bar| {
        bar.hello();
    });

    // doesn't:
    foo.hard_to_gat(&Bar::hello);
}
```

I expected to see this happen: It compiles!

Instead, this happened: It doesn't compile, with,

```
  --> tests/closure2.rs:37:21
   |
37 |     foo.hard_to_gat(&Bar::hello);
   |                     ^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected type `for<'s> FnOnce<(&Bar<'s>,)>`
              found type `for<'r> FnOnce<(&'r Bar<'_>,)>`
```

I think the elegancy of being able to pass a method reference would be a big plus. So I'm filing this bug report to see if this is something which can be improved upon.

**Comment by jyn514** [comment] 2023-04-26 16:09
I think it's simpler than that - `Self` means `Bar<'s>`, while `Bar<'_>` infers a new fresh lifetime. In other words, `Bar` is a type constructor but `Self` is a single concrete type.

I'm going to close this since it's not a bug.

**Closed by jyn514** 2023-04-26 16:09 UTC
Labels: C-discussion
