### ISSUE TITLE
Derive not following trait bounds for associated types

### ISSUE THREAD

**Issue by lucasem** [rust-lang/rust#48512] opened 2018-02-24 19:08 UTC
When deriving a standard trait like `Clone`, trait bounds aren't being followed for associated types.

For example ([on playground](https://play.rust-lang.org/?gist=bc1d63f589290b377d610e581765cdce)):

```rust
#[derive(Clone)]
struct Efficiency<T: Transportation> {
    vehicle: T::Vehicle,
    mpg: f64,
}

trait Transportation: Sized {
    type Vehicle: Clone /* + other bounds */ ;
    
    fn milage_info() -> Vec<Vec<Efficiency<Self>>> {
        vec![vec![]; 8]
    }
}
```

I expected that the `Efficiency` type should be able to derive `Clone` because every `<T as Transportation>::Vehicle: Clone` and of course `f64: Clone`. The type error, however, appears to believe that `Clone` cannot be derived unless `Transportation: Clone`:

```
error[E0277]: the trait bound `Self: std::clone::Clone` is not satisfied
  --> src/main.rs:11:9
   |
11 |         vec![vec![]; 8]
   |         ^^^^^^^^^^^^^^^ the trait `std::clone::Clone` is not implemented for `Self`
   |
   = help: consider adding a `where Self: std::clone::Clone` bound
   = note: required because of the requirements on the impl of `std::clone::Clone` for `BarStuff<Self>`
   = note: required because of the requirements on the impl of `std::clone::Clone` for `std::vec::Vec<BarStuff<Self>>`
   = note: required by `std::vec::from_elem`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

An alternative is to duplicate the bounds defined for the associated type in the struct definition:

```rust
struct Efficiency<V: Clone /* + other bounds */> { .. }
```

Which is repetitive and seemingly unnecessary considering the appropriate bound is already defined by `Transportation`.

Tested on the latest stable (1.24.0) and nightly (2018-02-23).

**Comment by vitalyd** [comment] 2018-02-24 20:31
I think this is a dupe of https://github.com/rust-lang/rust/issues/26925

**Comment by pietroalbini** [comment] 2018-02-27 18:51
Closing as a duplicate.

**Closed by pietroalbini** 2018-02-27 18:51 UTC
