### ISSUE TITLE
mem::transmute to nevertype causes Illigal instruction

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#51005] opened 2018-05-23 18:21 UTC
transmuting to the never type causes an Illigal instruction: https://play.rust-lang.org/?gist=390b8739cfe0e25504f0602dcf546e7b&version=nightly&mode=release

```Rust
#![feature(never_type)]

use std::mem;

fn main() {
    let _: ! = unsafe { mem::transmute( {} ) };
}
```
Now, it's true that this requires unsafe, and might not even considered an issue or bug, and probably never happens in real productions code. However, many transmutes give a segfault when done wrong, this instead gives an illigal instruction.

**Comment by jonas-schievink** [comment] 2018-05-23 18:53
This is just UB, the code can do whatever. It's only an illegal instruction (`ud2`) because the compiler is nice. I think LLVM's trap-unreachable flag is doing this - otherwise `main` would just contain no instructions (since `!` cannot be created `main` can never be reached) and fall through to whatever code happens to follow it.

**Comment by cuviper** [comment] 2018-05-23 19:22
This is very similar to #50976.

**Comment by sfackler** [comment] 2018-05-23 21:45
Closing as a duplicate of #50976.

**Closed by sfackler** 2018-05-23 21:45 UTC
