### ISSUE TITLE
ICE when running cargo fix --edition with latest nightly

### ISSUE THREAD

**Issue by georgmu** [rust-lang/rust#134569] opened 2024-12-20 16:33 UTC
### Code

Not minimized yet

### Meta

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (9e136a30a 2024-12-19)
```

### Error output

```
error: internal compiler error: compiler/rustc_mir_build/src/builder/scope.rs:1724:17: cannot unwind from goto -> bb57

thread 'rustc' panicked at compiler/rustc_mir_build/src/builder/scope.rs:1724:17:
Box<dyn Any>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/builder/scope.rs:1724:17:
Box<dyn Any>
stack backtrace:
   0:     0x7fbdcbf50325 - std::backtrace::Backtrace::create::hb67bbbe26a0d3896
   1:     0x7fbdca56dcf5 - std::backtrace::Backtrace::force_capture::h04d7ae1c482d3231
   2:     0x7fbdc96f7ece - std[19739dcbdd52d894]::panicking::update_hook::<alloc[d24e20bba6540ab9]::boxed::Box<rustc_driver_impl[3177e72804664110]::install_ice_hook::{closure#0}>>::{closure#0}
   3:     0x7fbdca585c68 - std::panicking::rust_panic_with_hook::hd21771b96ea64164
   4:     0x7fbdc97322d1 - std[19739dcbdd52d894]::panicking::begin_panic::<rustc_errors[37abd7aad4ad5df0]::ExplicitBug>::{closure#0}
   5:     0x7fbdc97274b6 - std[19739dcbdd52d894]::sys::backtrace::__rust_end_short_backtrace::<std[19739dcbdd52d894]::panicking::begin_panic<rustc_errors[37abd7aad4ad5df0]::ExplicitBug>::{closure#0}, !>
   6:     0x7fbdc9723ec9 - std[19739dcbdd52d894]::panicking::begin_panic::<rustc_errors[37abd7aad4ad5df0]::ExplicitBug>
   7:     0x7fbdc973c231 - <rustc_errors[37abd7aad4ad5df0]::diagnostic::BugAbort as rustc_errors[37abd7aad4ad5df0]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
   8:     0x7fbdc9c8b76c - <rustc_errors[37abd7aad4ad5df0]::DiagCtxtHandle>::span_bug::<rustc_span[2a960e124d280c12]::span_encoding::Span, alloc[d24e20bba6540ab9]::string::String>
   9:     0x7fbdc9d10fe7 - rustc_middle[a45f2c6e02975f4b]::util::bug::opt_span_bug_fmt::<rustc_span[2a960e124d280c12]::span_encoding::Span>::{closure#0}
  10:     0x7fbdc9cf67ba - rustc_middle[a45f2c6e02975f4b]::ty::context::tls::with_opt::<rustc_middle[a45f2c6e02975f4b]::util::bug::opt_span_bug_fmt<rustc_span[2a960e124d280c12]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  11:     0x7fbdc9cf664b - rustc_middle[a45f2c6e02975f4b]::ty::context::tls::with_context_opt::<rustc_middle[a45f2c6e02975f4b]::ty::context::tls::with_opt<rustc_middle[a45f2c6e02975f4b]::util::bug::opt_span_bug_fmt<rustc_span[2a960e124d280c12]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  12:     0x7fbdc812b477 - rustc_middle[a45f2c6e02975f4b]::util::bug::span_bug_fmt::<rustc_span[2a960e124d280c12]::span_encoding::Span>
  13:     0x7fbdcb5ed5ef - <rustc_mir_build[e05bc5701fd211e7]::builder::Builder>::build_unwind_tree
  14:     0x7fbdcb5e510e - rustc_mir_build[e05bc5701fd211e7]::builder::mir_build
  15:     0x7fbdcac07714 - rustc_mir_transform[e79b9bef93d6360b]::mir_built
  16:     0x7fbdcac076d7 - rustc_query_impl[7b0f6e1e4ae2319d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7b0f6e1e4ae2319d]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a45f2c6e02975f4b]::query::erase::Erased<[u8; 8usize]>>
  17:     0x7fbdcae971ec - rustc_query_system[1e197417f2882beb]::query::plumbing::try_execute_query::<rustc_query_impl[7b0f6e1e4ae2319d]::DynamicConfig<rustc_data_structures[192c71b2dc5f58e0]::vec_cache::VecCache<rustc_span[2a960e124d280c12]::def_id::LocalDefId, rustc_middle[a45f2c6e02975f4b]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[1e197417f2882beb]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7b0f6e1e4ae2319d]::plumbing::QueryCtxt, true>
  18:     0x7fbdcb06a3f9 - rustc_query_impl[7b0f6e1e4ae2319d]::query_impl::mir_built::get_query_incr::__rust_end_short_backtrace
  19:     0x7fbdc7daeec5 - rustc_mir_build[e05bc5701fd211e7]::check_unsafety::check_unsafety
  20:     0x7fbdcb535327 - rustc_query_impl[7b0f6e1e4ae2319d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7b0f6e1e4ae2319d]::query_impl::check_unsafety::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a45f2c6e02975f4b]::query::erase::Erased<[u8; 0usize]>>
  21:     0x7fbdcb05e279 - rustc_query_system[1e197417f2882beb]::query::plumbing::try_execute_query::<rustc_query_impl[7b0f6e1e4ae2319d]::DynamicConfig<rustc_data_structures[192c71b2dc5f58e0]::vec_cache::VecCache<rustc_span[2a960e124d280c12]::def_id::LocalDefId, rustc_middle[a45f2c6e02975f4b]::query::erase::Erased<[u8; 0usize]>, rustc_query_system[1e197417f2882beb]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[7b0f6e1e4ae2319d]::plumbing::QueryCtxt, true>
  22:     0x7fbdcb05dd76 - rustc_query_impl[7b0f6e1e4ae2319d]::query_impl::check_unsafety::get_query_incr::__rust_end_short_backtrace
  23:     0x7fbdcb05a72c - rustc_interface[dfcc7ff3f03a05db]::passes::run_required_analyses
  24:     0x7fbdcbb46c5e - rustc_interface[dfcc7ff3f03a05db]::passes::analysis
  25:     0x7fbdcbb46c2f - rustc_query_impl[7b0f6e1e4ae2319d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7b0f6e1e4ae2319d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a45f2c6e02975f4b]::query::erase::Erased<[u8; 0usize]>>
  26:     0x7fbdcbb4c47c - rustc_query_system[1e197417f2882beb]::query::plumbing::try_execute_query::<rustc_query_impl[7b0f6e1e4ae2319d]::DynamicConfig<rustc_query_system[1e197417f2882beb]::query::caches::SingleCache<rustc_middle[a45f2c6e02975f4b]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[7b0f6e1e4ae2319d]::plumbing::QueryCtxt, true>
  27:     0x7fbdcbb4bcd5 - rustc_query_impl[7b0f6e1e4ae2319d]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  28:     0x7fbdcbb9ed9e - rustc_interface[dfcc7ff3f03a05db]::passes::create_and_enter_global_ctxt::<core[57d68807791337c0]::option::Option<rustc_interface[dfcc7ff3f03a05db]::queries::Linker>, rustc_driver_impl[3177e72804664110]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  29:     0x7fbdcbc10c43 - rustc_interface[dfcc7ff3f03a05db]::interface::run_compiler::<(), rustc_driver_impl[3177e72804664110]::run_compiler::{closure#0}>::{closure#1}
  30:     0x7fbdcbbf7711 - std[19739dcbdd52d894]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[dfcc7ff3f03a05db]::util::run_in_thread_with_globals<rustc_interface[dfcc7ff3f03a05db]::util::run_in_thread_pool_with_globals<rustc_interface[dfcc7ff3f03a05db]::interface::run_compiler<(), rustc_driver_impl[3177e72804664110]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  31:     0x7fbdcbbf7ba6 - <<std[19739dcbdd52d894]::thread::Builder>::spawn_unchecked_<rustc_interface[dfcc7ff3f03a05db]::util::run_in_thread_with_globals<rustc_interface[dfcc7ff3f03a05db]::util::run_in_thread_pool_with_globals<rustc_interface[dfcc7ff3f03a05db]::interface::run_compiler<(), rustc_driver_impl[3177e72804664110]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[57d68807791337c0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7fbdcbbf916f - std::sys::pal::unix::thread::Thread::new::thread_start::h71fe57097907b3f8
  33:     0x7fbdc5e43148 - start_thread
  34:     0x7fbdc5ec70cc - __GI___clone3
  35:                0x0 - <unknown>


rustc version: 1.85.0-nightly (9e136a30a 2024-12-19)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `local::_::<impl at src/local.rs:10:35: 10:46>::deserialize::<impl at src/local.rs:10:35: 10:46>::visit_seq`
#1 [check_unsafety] unsafety-checking `local::_::<impl at src/local.rs:10:35: 10:46>::deserialize::<impl at src/local.rs:10:35: 10:46>::visit_seq`
#2 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

**Comment by georgmu** [comment] 2024-12-20 16:34
Regression in 11663cd3bfefef7d34e8f0892c250bf698049392

searched nightlies: from nightly-2024-12-18 to nightly-2024-12-20
regressed nightly: nightly-2024-12-20
searched commit range: https://github.com/rust-lang/rust/compare/4ba4ac612d36e3409e8e1e31e12acc028808f85f...9e136a30a965bf4e63f03095c57df7257bf96fd6
regressed commit: https://github.com/rust-lang/rust/commit/11663cd3bfefef7d34e8f0892c250bf698049392

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.9</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve --start 2024-12-18 --end 2024-12-20 -- fix --edition --allow-dirty 
```
</details>

**Comment by compiler-errors** [comment] 2024-12-20 16:40
if you can, pls share some code, even if it's not minimized 🙏

**Comment by compiler-errors** [comment] 2024-12-20 17:08
Actually this is a duplicate of #134566, I'm gonna consolidate it over there.

**Closed by compiler-errors** 2024-12-20 17:08 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
