### ISSUE TITLE
Type inference regression on `nightly-2024-05-20`

### ISSUE THREAD

**Issue by oblique** [rust-lang/rust#125319] opened 2024-05-20 10:11 UTC
### Code

I tried this code:

```toml
[package]
name = "regression"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { version = "=0.3.34", features = ["parsing"] }
```

```rust
fn main() {}
```

I expected to see this happen: Compile successfully.

Instead, this happened: Compilation failed with the following.

```rust
error[E0282]: type annotations needed for `Box<_>`
  --> /home/oblique/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

### Version it worked on

It most recently worked on:

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (b1ec1bd65 2024-05-18)
binary: rustc
commit-hash: b1ec1bd65f89c1375d2cf2fb733a87ef390276d3
commit-date: 2024-05-18
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4
```

### Version with regression

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (d84b90375 2024-05-19)
binary: rustc
commit-hash: d84b9037541f45dc2c52a41d723265af211c0497
commit-date: 2024-05-19
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-nightly-regression-untriaged

**Comment by lukas-code** [comment] 2024-05-20 11:39
Regression in https://github.com/rust-lang/rust/pull/99969.

This code used to infer `_` as `[char]`, but now it is ambiguous between `[char]` and `str`. [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=18d837c1d1a5b5a4a8df090a938ea84a)
```rust
fn main() {
    let _: Box<_> = ['a'].into_iter().collect();
}
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged T-libs-api

**Comment by kpreid** [comment] 2024-05-20 16:39
Per https://github.com/rust-lang/rust/pull/99969#issuecomment-2088878740 this is a known breakage, which can be addressed by updating your project's `time` dependency to version 0.3.35 or later.

**Comment by workingjubilee** [comment] 2024-05-21 19:46
A type inference regression is [permitted breakage according to Rust RFC 1122](https://github.com/rust-lang/rfcs/blob/master/text/1122-language-semver.md#underspecified-language-semantics).

This is not even a change in type inference though, it's rather _because_ of type inference. In particular, when we add an impl and that means now 2 possible impls resolve, instead of 1, it can break things. Customarily, if the library teams expect a breakage may be particularly widespread, rejecting it is discussed and there is a formal decision to accept it or not. However it's not clear to me from the FCP's comments (or lack thereof) if T-libs-api discussed this breakage before/during the FCP, beyond the chatter that occurred there? https://github.com/rust-lang/rust/pull/99969#issuecomment-1911406898

@rust-lang/libs-api Can I just assume that if T-libs-api FCPs a new impl of something like From or FromIterator, and then a team member r+'s landing something that they said ["maybe a crater run"](https://github.com/rust-lang/rust/pull/99969#issuecomment-2002147908) about, that you have discussed the breakage possibility and said "worth it"? It may be helpful if you just formally note "probably will break someone relying on a particularly strained `.into()` somewhere, but that seems fine" on the FCP.

Spicy option: r+ it the moment it hits the final comment period so we might actually get any such reports in the 10 day period.

**Comment by billy1624** [comment] 2024-06-21 09:37
Sadly this is blocking our docs.rs builds
- https://docs.rs/crate/sea-orm/1.0.0-rc.6/builds/1254093

**Comment by workingjubilee** [comment] 2024-06-22 02:57
Nominating in hopes of getting an answer to the question here so we can take a disposition on this issue instead of having it hang on the issue tracker forever: https://github.com/rust-lang/rust/issues/125319#issuecomment-2123328644

**Comment by dtolnay** [comment] 2024-07-02 16:06
We discussed this regression in today's libs-api team meeting, and are inclined not to revert.

1.80 is in beta already so we'll start seeing fallout in the beta crater runs. The team will re-evaluate if the beta crater runs look disastrous with many crates other than `time` impacted.

**Closed** 2024-07-02 16:07 UTC
Labels: regression-from-stable-to-nightly, T-libs-api, A-inference, C-bug, I-libs-api-nominated
