### ISSUE TITLE
`Index` chosen over `IndexMut` incorrectly, with a confusing error message.

### ISSUE THREAD

**Issue by smarnach** [rust-lang/rust#75680] opened 2020-08-18 20:30 UTC
Retrieving an element from a vector of mutable references works fine calling `index_mut()` directly

```rust
use std::ops::IndexMut;

fn explicit_trait_call(mut a: Vec<&mut i32>) {
    let _i: &mut i32 = *a.index_mut(0);
}
```

but fails when using supposedly equivalent indexing syntax:

```rust
fn indexing(mut a: Vec<&mut i32>) {
    let _i: &mut i32 = a[0];
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c7eb87e0e318ccaf8986ad6e88fb599c))

The error message is rather surprising:

```
error[E0596]: cannot borrow data in an index of `std::vec::Vec<&mut i32>` as mutable
 --> src/lib.rs:4:24
  |
4 |     let _i: &mut i32 = a[0];
  |                        ^^^^ cannot borrow as mutable
  |
  = help: trait `IndexMut` is required to modify indexed content, but it is not implemented for `std::vec::Vec<&mut i32>`
```

It's clearly not true that `IndexMut` is not implemented for `Vec`, as evidenced by the first implementation.

The explicit trait call version only works because the explicit type annotation for `_i` triggers an implicit reborrow. My gut feeling is that the compiler is selecting `Index` instead of `IndexMut` here since the assignment looks like a move when not taking into account the implicit reborrow. I feel that the rejected code should be accepted. In any case, the error message should be fixed.

This post was inspired by a [question of StackOverflow today](
https://stackoverflow.com/questions/63468345/cannot-access-mutable-trait-object-reference-in-a-vector), and I [discussed this on the user forum as well](https://users.rust-lang.org/t/compiler-does-not-find-indexmut-impl-for-vec/47455).

**Comment by jonas-schievink** [comment] 2020-08-18 20:33
Duplicate of https://github.com/rust-lang/rust/issues/72002

**Closed by jonas-schievink** 2020-08-18 20:33 UTC
Labels: C-bug

**Comment by smarnach** [comment] 2020-08-18 20:45
@jonas-schievink I looked at that issue before filing this bug, but came to the conclusion this is separate. The problem with the error message is the same, but the reason that `Index` is chosen instead of `IndexMut` is a different one. (I should have linked the other issue here.)

**Comment by jonas-schievink** [comment] 2020-08-18 20:51
Hmm, right, this still doesn't work on stable, but https://github.com/rust-lang/rust/pull/72068 is on stable. Any idea what might have fixed your example on beta/nightly?

**Comment by jonas-schievink** [comment] 2020-08-18 20:53
Maybe https://github.com/rust-lang/rust/pull/72280?

**Comment by smarnach** [comment] 2020-08-18 21:17
Huh, I didn't realize it's fixed on beta and nightly! And no, I don't know why.

On the one hand, it convinces me that this actually isn't a dupe of the linked issue, because the code in that issue is already fixed on stable. On the other hand, it doesn't really matter anymore. :)
