### ISSUE TITLE
Build regression on nightly

### ISSUE THREAD

**Issue by Disasm** [rust-lang/rust#60835] opened 2019-05-14 20:16 UTC
Consider the program with the following `main.rs`:

```rust
#![deny(warnings)]
#[no_mangle]
static mut PERIPHERALS: bool = false;

fn main() {
    println!("Hello, world!");
}
```

```shell
$ cargo check
    Checking cargo-bug v0.1.0 (/tmp/cargo-bug)
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
$ cargo check
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
$ touch src/main.rs
$ cargo check      
    Checking cargo-bug v0.1.0 (/tmp/cargo-bug)
error: unused attribute
 --> src/main.rs:3:1
  |
3 | #[no_mangle]
  | ^^^^^^^^^^^^
  |
note: lint level defined here
 --> src/main.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: #[deny(unused_attributes)] implied by #[deny(warnings)]

error: aborting due to previous error

error: Could not compile `cargo-bug`.

To learn more, run the command again with --verbose.
```

This behavior causes almost every CI build with cache to fail for crates with such `no-mangle static mut` variable. First experienced with nightly ~10 days ago.

**Comment by jonas-schievink** [comment] 2019-05-14 20:21
Duplicate of https://github.com/rust-lang/rust/issues/60050

**Closed by jonas-schievink** 2019-05-14 20:21 UTC
