### ISSUE TITLE
Impossible to Specify Appropriate Lifetime with `for<'a> &'a ...`

### ISSUE THREAD

**Issue by phlopsi** [rust-lang/rust#67067] opened 2019-12-05 20:35 UTC
I had [asked for help](https://users.rust-lang.org/t/cannot-infer-appropriate-lifetime/35315) on the Rust user forum, but from what I've learned, Rust provides no way to specify lifetimes in a way to succesfully run the loop in the `drop`-method in the following example:
```rust
struct MyStruct<TCollection>
where
    for<'a> &'a TCollection: IntoIterator<Item = &'a ()>,
{
    references: TCollection,
}

impl<TCollection> Drop for MyStruct<TCollection>
where
    for<'b> &'b TCollection: IntoIterator<Item = &'b ()>,
{
    fn drop(&mut self) {
        for _ in &self.references {}
    }
}

fn main() {
    let _ = MyStruct {
        references: Vec::new(),
    };
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=68b57e15619bab6b751c78217d266498))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0367]: The requirement `for<'b> <&'b TCollection as std::iter::IntoIterator>::Item == &'b ()` is added only by the Drop impl.
  --> src/lib.rs:8:1
   |
8  | / impl<TCollection> Drop for MyStruct<TCollection>
9  | | where
10 | |     for<'b> &'b TCollection: IntoIterator<Item = &'b ()>,
11 | | {
...  |
14 | |     }
15 | | }
   | |_^
   |
note: The same requirement must be part of the struct/enum definition
  --> src/lib.rs:1:1
   |
1  | / struct MyStruct<TCollection>
2  | | where
3  | |     for<'a> &'a TCollection: IntoIterator<Item = &'a ()>,
4  | | {
5  | |     references: TCollection,
6  | | }
   | |_^

error[E0367]: The requirement `for<'b> &'b TCollection: std::iter::IntoIterator` is added only by the Drop impl.
  --> src/lib.rs:8:1
   |
8  | / impl<TCollection> Drop for MyStruct<TCollection>
9  | | where
10 | |     for<'b> &'b TCollection: IntoIterator<Item = &'b ()>,
11 | | {
...  |
14 | |     }
15 | | }
   | |_^
   |
note: The same requirement must be part of the struct/enum definition
  --> src/lib.rs:1:1
   |
1  | / struct MyStruct<TCollection>
2  | | where
3  | |     for<'a> &'a TCollection: IntoIterator<Item = &'a ()>,
4  | | {
5  | |     references: TCollection,
6  | | }
   | |_^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0367`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

Rust should be able to determine, that the `where`-clause in the struct and the `Drop`-impl are compatible. I consider this a bug.

**Comment by jonas-schievink** [comment] 2019-12-05 21:08
Duplicate of https://github.com/rust-lang/rust/issues/34426, will be fixed by https://github.com/rust-lang/rust/pull/67059

**Closed by jonas-schievink** 2019-12-05 21:08 UTC
