### ISSUE TITLE
Cannot build rust nightly: unresolved import `crate::os::unix::net`

### ISSUE THREAD

**Issue by MikaelUrankar** [rust-lang/rust#105467] opened 2022-12-08 18:09 UTC
```
error[E0432]: unresolved import `crate::os::unix::net`
 --> library/std/src/os/net/linux_ext/addr.rs:3:22
  |
3 | use crate::os::unix::net::SocketAddr;
  |                      ^^^ could not find `net` in `unix`
```

```
/usr/ports/lang/rust-nightly/work/bootstrap/bin/rustc -vV
rustc 1.66.0-beta.1 (e080cc5a6 2022-11-01)
binary: rustc
commit-hash: e080cc5a659fb760c0bc561b722a790dad35b5e1
commit-date: 2022-11-01
host: x86_64-unknown-freebsd
release: 1.66.0-beta.1
LLVM version: 15.0.2
```

**Comment by MikaelUrankar** [comment] 2022-12-14 12:07
Any ideas?

**Comment by MikaelUrankar** [comment] 2022-12-26 09:38
Regressed with [8f1e6eba343452ac48412f11d57aa7d206c8c3dd](https://github.com/rust-lang/rust/commit/8f1e6eba343452ac48412f11d57aa7d206c8c3dd)

**Comment by MikaelUrankar** [comment] 2022-12-26 09:39
cc @jmillikin

**Comment by jmillikin** [comment] 2022-12-26 11:21
Is there more information available from the error? The `linux_ext` module should not be part of the FreeBSD build.

Also, an error in resolving `crate::os::unix::net` doesn't make much sense to me because that module should exist regardless of whether the `abstract_unix_socket` feature is enabled.

Is it possible that there's either (1) another error further up in the build log, or (2) an existing incorrect dependency that's been exposed by the recent change?

**Comment by MikaelUrankar** [comment] 2022-12-26 15:25
The full log is available here:
http://mikael.urankar.free.fr/rust-1.66.0.log.txt

**Comment by MikaelUrankar** [comment] 2023-01-02 17:06
It only happens if I build the documentation.

Is it possible to fix this problem before rust 1.67 lands?

**Comment by jmillikin** [comment] 2023-01-09 05:06
Reproduced with the following command:
```
python3 x.py doc std --target=wasm32-unknown-unknown
```

@MikaelUrankar could you please see if the patch in https://github.com/rust-lang/rust/pull/106618 fixes the build for you?

**Comment by MikaelUrankar** [comment] 2023-01-09 08:18
Your patch fixes the issue.
Many thanks!

**Closed** 2023-01-29 10:20 UTC
Labels: C-bug
