### ISSUE TITLE
Errors in early passes should not bail until trans

### ISSUE THREAD

**Issue by ehiggs** [rust-lang/rust#36161] opened 2016-08-31 08:39 UTC
If you use clippy and set `deny` to a lint in an early phase, like checking docstring syntax, then rustc will bail when it is done finding the issues in this early pass. This can give the impression that the code is sound since 'oh it's only docstring issues, whatever' when actually there could be more serious issues lurking. Obviously you can stop the lint from flagging errors and denying instead, but rustc should also not bail until it hits the trans phase so it can report more errors. 

An example of the confusion can be seen here: https://github.com/autumnai/leaf/issues/106

I asked @Manishearth about this on IRC and he recommended I submit an issue to  rustc.

**Comment by jonas-schievink** [comment] 2016-08-31 18:18
There's been a lot of work on error recovery for rustc, doing exactly this. I can't find any code aborting compilation after early lints (there's no reason to abort), so it's probably some pass between that and late lints (which is almost the entire compiler). What's the last error you see in the example?

**Comment by Manishearth** [comment] 2016-09-01 02:18
There doesn't need to be an error after the lints, we have plenty of `abort_if_errors()` calls scattered throughout the compiler.

Early lint errors shouldn't be counted as errors till the last bit.

**Comment by ehiggs** [comment] 2016-09-02 13:08
[clippy-errors.txt](https://github.com/rust-lang/rust/files/452048/clippy-errors.txt)

I've uploaded an example text file of errors. It seems that there are a few more errors reported now before it bails but I'm pretty sure it's not all the lints since the project was EoL  soon after I reported the issue:

```
$ grep  'warn(' ~/clippy-errors.txt | sed 's/^.*warn(\([^)]*\)).*$/\1/'| sort | uniq -c
   1 assign_op_pattern
  35 doc_markdown
   1 explicit_iter_loop
   3 map_clone
   2 match_bool
   3 match_ref_pats
   1 match_same_arms
   7 needless_borrow
   4 too_many_arguments
   9 toplevel_ref_arg
  10 type_complexity
   3 unused_imports
   1 useless_attribute
   2 useless_let_if_seq
   3 useless_vec
```

**Comment by Mark-Simulacrum** [comment] 2019-09-15 13:53
Closing as duplicate of https://github.com/rust-lang/rust/issues/12166.

**Closed by Mark-Simulacrum** 2019-09-15 13:53 UTC
Labels: A-diagnostics, C-enhancement
