### ISSUE TITLE
The span of `function is never used` seem wrong

### ISSUE THREAD

**Issue by pmarcelll** [rust-lang/rust#35974] opened 2016-08-24 21:05 UTC
Sample code:

```rust
fn foo() { println!("foo"); }

fn bar() {
    println!("bar");
}

fn main() {

}
```

Output:

```
warning: function is never used: `foo`, #[warn(dead_code)] on by default
 --> <anon>:1:1
  |
1 | fn foo() { println!("foo"); }
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: function is never used: `bar`, #[warn(dead_code)] on by default
 --> <anon>:3:1
  |
3 | fn bar() {
  | ^

```

If the function is only one row, the whole function can be highlighted, but if the funcion consists of multiple lines, only the first character (the f from fn) is highlighted.

**Comment by nagisa** [comment] 2016-08-24 21:34
Duplicate of https://github.com/rust-lang/rust/issues/33961

**Closed** 2016-08-24 21:35 UTC
