### ISSUE TITLE
compile-fail/asm-src-loc.rs fails on ARM when compiled without optimizations

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#40555] opened 2017-03-15 19:44 UTC
(Cross) compiling this test for `arm-unknown-linux-gnueabihf` fails because the error span is missing. (Reproduced on `nightly-2017-03-04`)

```rust
#![feature(asm)]

fn main() {
    unsafe {
        asm!("nowayisthisavalidinstruction"); //~ ERROR instruction
    }
}
```

Output of `rustc --target=arm-unknown-linux-gnueabihf -Copt-level=0`:

```
error: <inline asm>:1:2: error: invalid instruction
        nowayisthisavalidinstruction
        ^


error: aborting due to previous error
```

Output of `rustc --target=arm-unknown-linux-gnueabihf -Copt-level=1`:

```
error: <inline asm>:1:2: error: invalid instruction
        nowayisthisavalidinstruction
        ^

 --> asmt.rs:5:9
  |
5 |         asm!("nowayisthisavalidinstruction"); //~ ERROR instruction
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by Amanieu** [comment] 2020-05-24 19:56
This seems to be an LLVM bug, I can reproduce the same behavior in Clang.
```
$ cat clang_asm.c 
int main() {
    asm("nowayisthisavalidinstruction");
    return 0;
}
$ clang -target arm-unknown-linux-gnueabihf clang_asm.c
<inline asm>:1:2: error: invalid instruction
        nowayisthisavalidinstruction
        ^
1 error generated.
$ clang -target arm-unknown-linux-gnueabihf clang_asm.c -O1
clang_asm.c:2:9: error: invalid instruction
    asm("nowayisthisavalidinstruction");
        ^
<inline asm>:1:2: note: instantiated into assembly here
        nowayisthisavalidinstruction
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Amanieu** [comment] 2020-05-24 20:41
LLVM bug: https://bugs.llvm.org/show_bug.cgi?id=46060

**Comment by Amanieu** [comment] 2020-05-31 01:19
Will be fixed by https://reviews.llvm.org/D80759

**Closed** 2020-06-17 00:00 UTC
Labels: A-diagnostics, A-inline-assembly, C-bug, O-ARM, T-compiler, requires-nightly
