### ISSUE TITLE
A pretty big performance hit after a recent change (PR #51361)

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#52849] opened 2018-07-30 07:30 UTC
Browsing the [perf page](https://perf.rust-lang.org/compare.html?start=75af9df71b9eea84f281cf7de72c3e3cc2b02222&end=70cac59031d5c33962a1f53cdca9359c0dcd1f9f&stat=instructions%3Au) I noticed a pretty big regression:
```
coercions-check | avg: 58.3%? | min: 31.0%? | max: 106.3%?
coercions-opt | avg: 31.8%? | min: 22.9%? | max: 49.1%?
coercions-debug | avg: 26.9%? | min: 19.8%? | max: 45.9%?
tuple-stress-check | avg: 31.7% | min: 9.0% | max: 43.4%
tuple-stress-opt | avg: 15.9% | min: 13.1% | max: 18.0%
tuple-stress-debug | avg: 15.7% | min: 12.9% | max: 18.0%
```
I have tracked it down to one of [these changes](https://github.com/rust-lang/rust/compare/75af9df71b9eea84f281cf7de72c3e3cc2b02222...70cac59031d5c33962a1f53cdca9359c0dcd1f9f). This might be a necessary evil, but I'd rather make sure.

cc @RalfJung, @oli-obk

**Comment by RalfJung** [comment] 2018-07-30 09:03
Are these CTFE-heavy crates? Still it's somewhat strange as only the final result of CTFE is supposed to be checked, not every intermediate value. (That's something I wanted to add, actually, but maybe that should be a miri-only feature.)

I opened https://github.com/rust-lang/rust/issues/52291 because I wasn't sure we are stressing CTFE enough in perf, but maybe we are?

**Comment by kennytm** [comment] 2018-07-30 09:23
[`tuple-stress`](https://github.com/rust-lang-nursery/rustc-perf/blob/master/collector/benchmarks/tuple-stress/src/main.rs) is a 2.4 MB source file consisting of a static array of length 65535.

```rust
static BIG_ARRAY_OF_TUPLES: [(i32, (f64, f64, f64)); 0xffff] = [
    (641161, (2.988, 10.544, 29.598)),
    ...
    (209150, (5.216, 15.229, 23.389)),
];

fn main() {
    assert!(BIG_ARRAY_OF_TUPLES.len() == 0xffff);
}
```

[`coercions`](https://github.com/rust-lang-nursery/rustc-perf/blob/master/collector/benchmarks/coercions/src/main.rs) is a similar 1.8 MB file again with a 65536-length array.

```rust
pub static MAPPING: [&'static str; 0xffff] = [
    "\u{0}",
    ...
    "",
];

fn main() { }
```

**Comment by oli-obk** [comment] 2018-07-30 09:43
Yea. A regression there is pretty much expected. But we can do better. Right now we'd keep reopening the allocation at least 2^20 times in the tuple-stress case.

We should move a bunch of methods from Memory to Allocation and just keep working the Allocation.

Candidates are the methods reading integers, pointers or primvals in general

**Comment by RalfJung** [comment] 2018-07-30 09:57
> Right now we'd keep reopening the allocation at least 2^20 times in the tuple-stress case.

That's just  `get_mut` though, right?

**Comment by RalfJung** [comment] 2018-07-30 13:16
> a 2.4 MB source file consisting of a static array of length 65535

Ah, so it's just a big constant.
Still, 64k is not *such* a big number for a machine, I am surprised it makes such a big impact.

**Comment by RalfJung** [comment] 2018-07-30 16:30
This looks like the same regression: The following code regressed from the previous nightly (2018-07-24) to today's (2018-07-30):
```rust
#![feature(const_fn, const_let)]

// Try to make CTFE actually do a lot of computation, without producing a big result.
// And without support for loops.

macro_rules! const_repeat {
    // Recursive case: Take a 16
    ([16 $($n: tt)*] $e: expr, $T: ty) => {{
        const fn e() -> $T { const_repeat!([$($n)*] $e, $T) }
        e(); e(); e(); e();
        e(); e(); e(); e();
        e(); e(); e(); e();
        e(); e(); e(); e()
    }};
    // Recursive case: Take a 2
    ([2 $($n: tt)*] $e: expr, $T: ty) => {{
        const fn e() -> $T { const_repeat!([$($n)*] $e, $T) }
        e(); e()
    }};
    // Base case
    ([] $e: expr, $T: ty) => {$e};

    // 16^4 * 2^2 = 2^(4*4+2) = 2^18 = 256k repetitions
    ($e: expr, $T: ty) => (const_repeat!([16 16 16 16 2 2] $e, $T));
}
macro_rules! expensive_static {
    ($name: ident : $T: ty = $e : expr) =>
        (pub static $name : $T = const_repeat!($e, $T);)
}

pub trait Trait: Sync {}
impl Trait for u32 {}
const fn nop<T>(t: T) -> T { t }
const fn inc(i: i32) -> i32 { i + 1 }

expensive_static!(RELOCATIONS : &'static str = "hello");
expensive_static!(SLOW_FIELDS: &'static i32 = &("bar", 42, "foo", 3.14).1);
expensive_static!(SLOW_CHECKED_INDEX: u8 = b"foomp"[3]);
expensive_static!(UNSIZING: &'static [u8] = b"foo");
expensive_static!(UNSIZE_TRAIT: &'static Trait = &42u32);
expensive_static!(CHAIN: usize = 42i32 as u8 as u64 as i8 as isize as usize);
expensive_static!(OPS: i32 = ((((10 >> 1) + 3) * 7) / 2 - 12) << 4);
expensive_static!(FORCE_ALLOC: i32 = *****(&&&&&5));
expensive_static!(CONST_FN_BASELINE: i32 = nop(42));
expensive_static!(CONST_FN_SIMPLE: i32 = inc(42));
```
Old:13s
New: 29s

With 2^20 runs, it doesn't even seem to terminate at all now, whereas it is 50s previously.

That's definitely fishy, because the final constant (that is supposed to be sanity checked only) is pretty small.

**Comment by RalfJung** [comment] 2018-07-30 16:39
Is it possible that it is now doing something for every allocation, even those that are not reachable from the final constant? That would explain why `FIELDS` specifically got slower.

**Comment by RalfJung** [comment] 2018-07-30 17:50
Interestingly, the "it diverges" part of the regression goes away when I change the macro to just repeat `$e` 16 times for the innermost part -- instead of wrapping it in a `const fn` and calling that 16 times.

Function calls seem to have regressed *a lot*.

Also, according to perf, all that time it diverges is spent hashing. Might be related to #51702? However, the "good" nightly 2018-07-24 already contains that PR as well.

**Comment by nnethercote** [comment] 2018-07-30 22:36
Presumably the "Sanity-check all constants" commit is the one responsible, given that `coercions` and `tuple-stress` both contains enormous constants.

**Comment by nnethercote** [comment] 2018-07-30 23:27
html5ever also took a smaller (but still substantial) hit:
```
html5ever-check
        avg: 1.8%       min: -2.0%      max: 5.1%
html5ever-debug
        avg: 2.0%       min: 0.4%       max: 3.6%
```

**Comment by nnethercote** [comment] 2018-07-30 23:36
Here's the top part of a Cachegrind diff, showing where the increase came from. The numbers are instruction counts. Lots of stuff in librustc_mir.
```
--------------------------------------------------------------------------------
           Ir
--------------------------------------------------------------------------------
4,121,321,316  PROGRAM TOTALS

--------------------------------------------------------------------------------
         Ir  file:function
--------------------------------------------------------------------------------
179,820,043  /home/njn/moz/rustN/src/librustc/ty/query/plumbing.rs:rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
100,660,499  /home/njn/moz/rustN/src/librustc/mir/interpret/mod.rs:rustc::mir::interpret::UndefMask::set_range
 95,548,806  /home/njn/moz/rustN/src/librustc/mir/interpret/mod.rs:rustc::mir::interpret::Pointer::offset
 94,250,157  /home/njn/moz/rustN/src/libcore/cell.rs:rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
 82,179,434  /home/njn/moz/rustN/src/librustc_mir/interpret/memory.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::get
 80,869,155  /home/njn/moz/rustN/src/librustc_mir/interpret/memory.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::check_align
 75,363,916  /home/njn/moz/rustN/src/librustc/ty/layout.rs:<rustc::ty::layout::LayoutCx<'tcx, rustc::ty::query::TyCtxtAt<'a, 'tcx, 'tcx>> as rustc_target::abi::LayoutOf>::layout_of
 73,870,463  /home/njn/moz/rustN/src/libstd/collections/hash/table.rs:rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
 71,369,937  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::step
 67,775,068  /home/njn/moz/rustN/src/libstd/collections/hash/map.rs:rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
 61,209,022  /home/njn/moz/rustN/src/librustc/mir/interpret/mod.rs:rustc::mir::interpret::UndefMask::grow
 60,553,924  /home/njn/moz/rustN/src/libstd/collections/hash/table.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::get
 60,487,853  /home/njn/moz/rustN/src/librustc_mir/interpret/place.rs:rustc_mir::interpret::place::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::place_field
 59,530,793  /build/glibc-OTsEL5/glibc-2.27/malloc/malloc.c:free
 57,801,198  /home/njn/moz/rustN/src/librustc_mir/interpret/memory.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::relocations
 56,127,203  ???:???
 51,661,186  /home/njn/moz/rustN/src/libcore/ptr.rs:rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
 49,020,227  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:<rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::validate_ptr_target
 48,627,289  /home/njn/moz/rustN/src/librustc/mir/interpret/mod.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::copy_repeatedly
 48,103,009  /home/njn/moz/rustN/src/libcore/iter/range.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::copy_repeatedly
 42,359,299  /build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:__memcpy_avx_unaligned_erms
 40,044,283  /home/njn/moz/rustN/src/librustc/mir/tcx.rs:rustc::mir::tcx::<impl rustc::mir::Place<'tcx>>::ty
 39,121,766  /build/glibc-OTsEL5/glibc-2.27/malloc/malloc.c:_int_malloc
 39,091,742  /build/glibc-OTsEL5/glibc-2.27/malloc/malloc.c:realloc
 38,927,504  /home/njn/moz/rustN/src/libstd/collections/hash/map.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::get
 38,609,260  /home/njn/moz/rustN/src/libcore/fmt/mod.rs:core::fmt::write
 37,747,369  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:<rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::write_value
 36,567,583  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:<rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::write_value_to_ptr
 35,716,347  /home/njn/moz/rustN/src/librustc_mir/interpret/place.rs:rustc_mir::interpret::place::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::eval_place
 35,391,276  /home/njn/moz/rustN/src/librustc_mir/borrow_check/nll/type_check/relate_tys.rs:<rustc_mir::borrow_check::nll::type_check::relate_tys::TypeRelating<'cx, 'bccx, 'gcx, 'tcx> as rustc::ty:
:relate::TypeRelation<'cx, 'gcx, 'tcx>>::tys
 34,601,512  /home/njn/moz/rustN/src/librustc_mir/interpret/memory.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::get_bytes_mut
-33,360,936  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:<rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::eval_rvalue_into_place
 33,098,069  /home/njn/moz/rustN/src/librustc/ty/relate.rs:<rustc_mir::borrow_check::nll::type_check::relate_tys::TypeRelating<'cx, 'bccx, 'gcx, 'tcx> as rustc::ty::relate::TypeRelation<'cx, 'gcx,
'tcx>>::tys
 32,710,110  /home/njn/moz/rustN/src/librustc/ty/mod.rs:rustc::ty::ParamEnv::and
 32,372,938  /home/njn/moz/rustN/src/librustc_mir/interpret/memory.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::write_scalar
 31,134,882  /home/njn/moz/rustN/src/librustc/ty/layout.rs:<rustc::ty::layout::LayoutCx<'tcx, rustc::ty::context::TyCtxt<'a, 'tcx, 'tcx>>>::record_layout_for_printing
 31,128,574  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:<&'a rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M> as rustc_target::abi::LayoutOf>::layout_of
 29,168,137  /home/njn/moz/rustN/src/libcore/num/mod.rs:rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
 28,114,083  /home/njn/moz/rustN/src/librustc_mir/interpret/memory.rs:<rustc_mir::interpret::memory::Memory<'a, 'mir, 'tcx, M>>::read_scalar
 27,851,882  /home/njn/moz/rustN/src/librustc/ty/layout.rs:<&'a rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M> as rustc_target::abi::LayoutOf>::layout_of
 27,249,214  /build/glibc-OTsEL5/glibc-2.27/malloc/malloc.c:malloc
 27,065,779  /home/njn/moz/rustN/src/librustc_mir/interpret/step.rs:rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::step
 26,803,051  /home/njn/moz/rustN/src/librustc_mir/interpret/eval_context.rs:<rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::force_allocation
```

**Comment by RalfJung** [comment] 2018-07-31 06:56
I verified (using [cargo-bisect-rustc](https://github.com/rust-lang-nursery/cargo-bisect-rustc)) that the regression reported above is also caused by the same PR:

> regression in 70cac59031d5c33962a1f53cdca9359c0dcd1f9f

**Comment by RalfJung** [comment] 2018-07-31 11:55
At least for my benchmark, the regression is entirely caused by <https://github.com/rust-lang/rust/pull/51361/files#diff-1651ba5b47f9ffa648d59265d3f94becR1671>: This leads to statics being CTFE'd at all in `check`, and (seemingly) to them being CTFE'd twice in `build`.

**Comment by RalfJung** [comment] 2018-07-31 11:59
`UnusedBrokenConstVisitor` does not actually make sure to only visit unused items. Also I am quite surprised to see that this lint is the *only* place that runs the check?

For example, with generic statics (which promoteds can create) or generic consts (which are proposed, AFAIK), this check couldn't do anything. There, we'd have to check on instantiation, right?

**Comment by RalfJung** [comment] 2018-08-03 08:26
I still was curious, so I did some more tests...

If I comment out the few lines in the "unusable constants" lint that touch statics, the slowdown goes down to 2% and sometimes the new code comes out faster than the old -- I think I am hitting the limits of what I can measure.

I guess that is expected as these benchmarks consists solely of big statics. But it means CTFE itself didn't get slower. And the lint does extra work, which has to take some time.

**Comment by RalfJung** [comment] 2018-08-03 08:33
With #52925, the slowdown in tuple-stress (according to my local measurements) is down to 3% aka 0.15s, and the slowdown in coercions is at 12% aka 0.18s. Given that these crates consist solely of big static arrays (both have 64k entries), it is somewhat expected that iterating over them takes some time. The percentage is large just because the crates both literally contains nothing else.

So my guess is that the patch works as intended, and yes it can incur a 0.15s perf hit on arrays with 54k entries. This can probably be optimized, but it doesn't seem like a "big performance hit" to me.

**Comment by ljedrz** [comment] 2018-08-03 08:39
Sounds reasonable, but since it was marked as **P-high**, I'll leave the issue to be closed by someone with greater experience.

**Comment by RalfJung** [comment] 2018-08-03 10:40
Oh, and I should mention that `check` of course still is way slower. Previously, `check` would not compute the statics at all. I guess we have to decide what is expected behavior here.

**Comment by oli-obk** [comment] 2018-08-03 10:46
I considered not computing the statics a bug. We have frequently had complaints that `cargo check` does not produce the same set of diagnostics that `cargo build` does.

**Comment by RalfJung** [comment] 2018-08-03 17:48
[Perf results are in](https://perf.rust-lang.org/compare.html?start=75af9df71b9eea84f281cf7de72c3e3cc2b02222&end=4dae47051315793d4d4d043b4b8b03c51e3dc877&stat=instructions%3Au)

`check` has big regressions as expected. `opt clean` are close to what I measured (5% and 18%). Incremental has bigger hits. I have no idea what is cached incrementally and whether we could cache some other/different query to make this faster?

**Comment by oli-obk** [comment] 2018-08-03 18:39
The lints aren't cached. so this is run again. would be fixable by the addition wrapper queries

**Comment by nnethercote** [comment] 2018-08-06 01:58
> Perf results are in

Sorry, what was that run measuring? There are over 250 commits separating the two revisions that were measured.

[This run](https://perf.rust-lang.org/compare.html?start=e94df4acb4c3f42fdc224a7164b63a99240add1e&end=daf753aef352e31e3c849c10ea2249502c24092a) showed that #52925 helped a bit with opt and debug builds, but it's still a long way short of undoing the original regression. Is there a plan for additional improvements?

**Comment by RalfJung** [comment] 2018-08-06 06:47
> showed that #52925 helped a bit with opt and debug builds, but it's still a long way short of undoing the original regression

The `check` regression is expected -- `check` does more work now, it actually evaluates the constants in `static FOO := ...` to provide diagnostics. We could probably disable the lint for check builds to undo the regression entirely, but the point of check builds is to obtain all(most all) of the diagnostics, right?

`build`, from what I can see, is actually not a very big regression -- at least in my local measurements of a release build (where I put #52925 directly on top of the PR introducing the problem), the time went up by <0.2s. Just to be clear, is that what you call "a long way" based on the fact that 0.2 is almost 20% in one benchmark? (I mostly want to make sure we are talking about the same thing.)

Given that #51361 did not regress expensive CTFE computations with small results (based on local execution of the benchmark in https://github.com/rust-lang-nursery/rustc-perf/pull/266), I think this is mostly due to checking a 64k entry array. This is a benchmark that consists of *nothing else* than a big static array, to the percentage is of course pretty big.

Further improvements are probably possible by looking at what miri does and optimizing that. @oli-obk suggested to try and re-use the result of `get_mut` for the allocation; I would be surprised if that helps. However, I also do not have much experience with profiling.

So, right now I plan to do other things first, and put this on the queue of "would be nice to come back to this".

**Comment by RalfJung** [comment] 2018-08-06 08:50
Actually I found a benchmark showing there is still some more serious problem than I thought:
```rust
#![feature(const_fn, const_let)]
#![allow(unused_must_use)]

// Try to make CTFE actually do a lot of computation, without producing a big result.
// And without support for loops.

macro_rules! const_repeat {
    // Base case: Use 16 at the end to avoid function calls at the leaves as much as possibele.
    ([16] $e: expr, $T: ty) => {{
        $e; $e; $e; $e;
        $e; $e; $e; $e;
        $e; $e; $e; $e;
        $e; $e; $e; $e
    }};
    ([1] $e: expr, $T: ty) => {{
        $e
    }};
    // Recursive case: Take a 16
    ([16 $($n: tt)*] $e: expr, $T: ty) => {{
        const fn e() -> $T { const_repeat!([$($n)*] $e, $T) }
        e(); e(); e(); e();
        e(); e(); e(); e();
        e(); e(); e(); e();
        e(); e(); e(); e()
    }};
    // Recursive case: Take a 8
    ([8 $($n: tt)*] $e: expr, $T: ty) => {{
        const fn e() -> $T { const_repeat!([$($n)*] $e, $T) }
        e(); e(); e(); e();
        e(); e(); e(); e()
    }};
    // Recursive case: Take a 4
    ([4 $($n: tt)*] $e: expr, $T: ty) => {{
        const fn e() -> $T { const_repeat!([$($n)*] $e, $T) }
        e(); e(); e(); e()
    }};
    // Recursive case: Take a 2
    ([2 $($n: tt)*] $e: expr, $T: ty) => {{
        const fn e() -> $T { const_repeat!([$($n)*] $e, $T) }
        e(); e()
    }};
}
macro_rules! expensive_static {
    ($name: ident : $T: ty = $e : expr) =>
        (pub static $name : $T = const_repeat!([8 16 16 16 16 16] $e, $T);)
}

expensive_static!(FIELDS: &'static i32 = &("bar", 42, "foo", 3.14).1);
```
With nightly-2018-07-24, this compiles in 10s. With nightly 2018-07-30, this quickly reaches using 10% of my RAM, then stays there at 100% CPU load forever. (Interestingly, my fan doesn't go very hard here. Seems to be a kind of CPU load that does not generate a lot of heat, if that makes any sense?)

@oli-obk Any idea what could be causing this? Looks a lot like the loop checker to me, but nightly-2018-07-24 already contains the loop checker.

**Comment by RalfJung** [comment] 2018-08-20 20:23
According to `perf` and `callgrind`, all that extra time is spent inside `core::hash::impls::<impl core::hash::Hash for (A, B)>::hash`. Unfortunately it doesn't say what `A` and `B` are...

Seems like this is somehow hitting a really bad case for the loop detector, but requires the sanity check to even happen? Isn't that odd? Somehow the static does not get properly evaluated without the sanity check. OTOH compile time goes up when I increase the number of iterations even pre-sanity, so it's not like it's skipping the static entirely...

**Comment by RalfJung** [comment] 2018-08-20 20:43
I think I have an idea what might be happening: These testcases might leak memory, and the hashing hashes all of memory and hence has quite a lot to do hashing all these unreachable allocations.

**Comment by RalfJung** [comment] 2018-08-20 21:13
Confirmed: If I make it hash only `machine` and `stack`, the regression goes away.

@oli-obk @ecstatic-morse What do you think the tradeoff is about including vs not including the memory in the hash?

It would likely also help to plug the leak, but even then we will leak static memory as e.g. we do not try to deduplicate strings AFAIK. A middle-ground might be to hash stack memory only (which currently leaks as well, but we should really fix *that*).

**Comment by oli-obk** [comment] 2018-08-21 07:14
@brunocodutra was working towards following only allocations reachable from the stack (in https://github.com/rust-lang/rust/pull/52626) We're only halfway there unfortunately.

Well, we should fix the leaks for sure, but also stop hashing the memory directly.

> hitting a really bad case for the loop detector, but requires the sanity check to even happen?

That makes no sense. The sanity checker runs after the loop checker and can't trigger the loop checker itself.

**Comment by brunocodutra** [comment] 2018-08-21 07:27
I'm mostly finished by the way, the only missing piece is to write a convenience macro to avoid code duplication, but I've been lacking the time to work on it. Hopefully by the end of the week I'll have it ready for review.

**Comment by nikomatsakis** [comment] 2018-08-23 14:16
According to @oli-obk, @RalfJung [has turned this from a perf regression into a perf win](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-08-23/near/132639967). Way to go!

**Comment by RalfJung** [comment] 2018-08-23 15:14
Uh, I think it is still slower than without the sanity check...  but that is expected.

However, there is also a known actual issue still open: https://github.com/rust-lang/rust/issues/52849#issuecomment-410635683. I am going to reopen this issue until we got that solved. I think we should stop hashing memory, also see https://github.com/rust-lang/rust/pull/52626#issuecomment-414600735.

**Comment by pietroalbini** [comment] 2018-08-25 12:41
PR for fixing this in beta is https://github.com/rust-lang/rust/pull/53425.

**Comment by RalfJung** [comment] 2018-08-25 12:45
That's not correct. That PR fixes a functional bug, it does not help with perf.

**Comment by pietroalbini** [comment] 2018-08-25 12:49
Uh, ok. So, since #53424 is not going to be backported, will the perf regression be fixed in another PR or should I mark this as "won't fix"?

**Comment by RalfJung** [comment] 2018-08-25 12:52
The full perf regression is not fixed in master yet but I plan to do so -- I am essentially waiting for https://github.com/rust-lang/rust/pull/52626 because that touches the same code (and actually that one might already do it). That will still be slower than it used to but that's expected, it is doing more work now.

As for beta -- @oli-obk any plans? We could (should, I think) backport https://github.com/rust-lang/rust/pull/52925, that would help. Beyond that, the only measures I can think of is to reduce what validation does -- make it stop at pointers, or disable it entirely.

**Comment by pnkfelix** [comment] 2018-08-30 14:29
visiting for triage. Assigning to @oli-obk to take the lead on the backport.

**Comment by oli-obk** [comment] 2018-09-06 14:29
visited for triage: I think @RalfJung has one more fix in this direction planned?

**Comment by RalfJung** [comment] 2018-09-06 14:46
Do I? Not that I know of.^^ I consider this done with https://github.com/rust-lang/rust/pull/52626.

**Comment by oli-obk** [comment] 2018-09-06 14:51
Awesome! I'll close this when #52626 is merged

**Closed** 2018-09-06 20:31 UTC
Labels: I-compiletime, P-high, T-compiler, WG-compiler-performance, regression-from-stable-to-nightly
