### ISSUE TITLE
Option and_then documentation clarity

### ISSUE THREAD

**Issue by Dev380** [rust-lang/rust#114493] opened 2023-08-05 02:54 UTC
https://github.com/rust-lang/rust/blob/e173a8e6634d787a1529ff6ec5dc63273425ca34/library/core/src/option.rs#L1381C8-L1381C8

Hi, I have a concern about the documentation here. It says that other languages call and_then a flat map operation. However, some searching has led me to this [SO answer](https://stackoverflow.com/a/40026523) which leads me to believe that this could be more accurately be called "functor map", which is what haskell's fmap means, according to the answer. This also has the benefit of improved clarity and reducing confusion with the iterator flat map operation.

**Comment by the8472** [comment] 2023-08-05 11:36
Well, haskell isn't the only other language in existence. Java [calls it flatMap](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#flatMap-java.util.function.Function-) for example.

**Comment by jdahlstrom** [comment] 2023-08-09 12:53
`Option::and_then` is *not* the functorial `map`. That's `Option::map`. `and_then` is the monadic "bind" operation and in Haskell it's spelled `>>=`. The reason it's often called `flat_map` (including by Rust's `Iterator´ trait) is that it's semantically a composition of `map` and `flatten`, ie. it removes one level of "option-ness" from a stack of nested `Option`s.

**Comment by Dylan-DPC** [comment] 2024-07-19 15:15
Closing this as it's not a issue and the documentation is as intended.

**Closed by Dylan-DPC** 2024-07-19 15:15 UTC
Labels: A-docs, T-libs
