### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', `/rustc/<snip>/compiler/rustc_hir/src/definitions.rs:452:14`

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang/rust#91696] opened 2021-12-09 07:11 UTC
### Code

The error happens when compiling [this project](https://github.com/TonalidadeHidrica/taiko-wiki-data-analysis/tree/fc0ca1e45e6ddf12c8370748316d1b15710912c8).  However, if I cloned this commit to another location (without copying `target`), it runs successfully.  So I doubt that this is an issue of cache-ish stuff.  I'm leaving the worktree as-is, so instruct me any steps required for troubleshooting if necessary.

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0
```

`export | grep RUST`:
```
RUSTC_WRAPPER /Users/username/.cargo/bin/sccache
```

### Error output

`$ cargo run --bin collect-songs-2`
```
   Compiling taiko-wiki-data-analysis v0.1.0 (/Users/username/dev/git/com/github/TonalidadeHidrica/clippy-bug)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental -C link-arg=-fuse-ld=/usr/local/bin/zld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `taiko-wiki-data-analysis`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling taiko-wiki-data-analysis v0.1.0 (/Users/username/dev/git/com/github/TonalidadeHidrica/clippy-bug)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id
   4: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover
   5: rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green
  13: rustc_query_system::query::plumbing::ensure_must_run
  14: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::coherent_trait
  15: rustc_session::session::Session::track_errors
  16: rustc_typeck::check_crate
  17: rustc_interface::passes::analysis
  18: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  19: rustc_data_structures::stack::ensure_sufficient_stack
  20: rustc_query_system::query::plumbing::try_execute_query
  21: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  22: rustc_interface::passes::QueryContext::enter
  23: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  24: rustc_span::with_source_map
  25: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental -C link-arg=-fuse-ld=/usr/local/bin/zld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `taiko-wiki-data-analysis`
```

</p>
</details>

**Comment by TonalidadeHidrica** [comment] 2021-12-09 07:12
I initially submitted an issue at https://github.com/rust-lang/rust-clippy/issues/8102 happening on similar project, but I found that this error also happens when `cargo run`-ning, not only `cargo clippy`-ing.

**Comment by TonalidadeHidrica** [comment] 2021-12-09 09:19
I doubt this is a duplicate of #89962.  By the way, another type of ICE `'assertion failed: sentinel == STR_SENTINEL'` (described in #91663) happens in the same project, but when compiling on `nightly`, not on `stable`.  So I suspect these two issues relate to each other.

**Comment by kud1ing** [comment] 2021-12-09 10:44
I too get `thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14` after I've renamed an enum.

**Comment by TonalidadeHidrica** [comment] 2021-12-09 10:51
@kud1ing Just curious, are you using `sccache`?

**Comment by kud1ing** [comment] 2021-12-09 11:27
@TonalidadeHidrica No, i am not.

**Comment by kud1ing** [comment] 2021-12-09 11:33
I've renamed another enum and hit it again right away:

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id
   4: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover
   5: rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green
   9: rustc_query_system::query::plumbing::ensure_must_run
  10: rustc_query_system::query::plumbing::get_query
  11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::fn_sig
  12: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_impl_item
  13: rustc_middle::hir::map::Map::visit_item_likes_in_module
  14: rustc_typeck::collect::collect_mod_item_types
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_query_system::query::plumbing::try_execute_query
  18: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_mod_item_types
  19: rustc_middle::hir::map::Map::for_each_module
  20: rustc_session::session::Session::track_errors
  21: rustc_typeck::check_crate
  22: rustc_interface::passes::analysis
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  24: rustc_data_structures::stack::ensure_sufficient_stack
  25: rustc_query_system::query::plumbing::try_execute_query
  26: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  27: rustc_interface::passes::QueryContext::enter
  28: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  29: rustc_span::with_source_map
  30: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type cdylib --crate-type staticlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [collect_mod_item_types] collecting item types in module `json_command_interpreter`
#1 [analysis] running analysis passes on this crate
end of query stack

**Comment by kud1ing** [comment] 2021-12-09 11:36
This might be a duplicate of https://github.com/rust-lang/rust/issues/91487

**Comment by Stargateur** [comment] 2021-12-10 12:31
same, and a cargo clean also fix it, close to impossible to produce a mcve cause it's not even a code problem.

**Comment by kud1ing** [comment] 2021-12-10 14:01
> > I've renamed another enum and hit it again right away:
> 
> @kud1ing this is very interesting. We've been struggling to reproduce this kind of bug. If you have a case where just renaming an enum triggers the ICE, I'd be glad to investigate it!

Thank you. Unfortunately it is not reliable. I couldn't reproduce it in a simple project. Where it happens, i am using a workspace.

**Comment by cjgillot** [comment] 2021-12-10 14:05
It's still a step forward. Can you share a snapshot of your workspace before and after the incriminating edit? I'll do the reduction myself.

**Comment by kud1ing** [comment] 2021-12-10 14:05
One commonality is that i am on macOS too:

```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0
```

**Comment by TonalidadeHidrica** [comment] 2021-12-10 14:05
@cjgillot @kud1ing FYI, I'm not using workspaces.

**Comment by cjgillot** [comment] 2021-12-10 14:08
@TonalidadeHidrica I believe this is the same bug. If you have a reproducer (= last version that compiled successfully, and the change that triggered the ICE), even if it's a huge one, I'll take it.

**Comment by TonalidadeHidrica** [comment] 2021-12-10 14:25
@cjgillot I have a pair of adjacent commits in which the older does not cause ICE but the newer does.  I confirmed that every time I switch between two commits, the behavior is reproducible, as long as I use the same `target` directory.  I have made two `.tar.gz` that includes every file in the directory, including `target/`, each of which of size ~512MB.  If this will help, I would like you to send these archives via e-mail because I'm not sure if this project contains any sensitive data, so please instruct me where to send it.

**Comment by TonalidadeHidrica** [comment] 2021-12-10 14:46
@cjgillot Or alternatively, I may [encrypt these files with your SSH key](https://superuser.com/questions/576506/how-to-use-ssh-rsa-public-key-to-encrypt-a-text) and share the link for the encrypted file.

**Comment by cjgillot** [comment] 2021-12-10 15:29
@TonalidadeHidrica let's keep it simple: can you send it the email address on my github profile?

**Comment by lopsided98** [comment] 2021-12-12 23:48
I have a project that reliably reproduces this bug, available here: https://drive.google.com/file/d/1ytZpN6UGrPaxBpuNdOGk8RFxGGP_oets/view?usp=sharing. The following sequence of actions triggers the bug for me:
1. Enter the `firmware` directory
2. `cargo clean`
3. `cargo build`
4. In `firmware/src/string/dac_driver.rs`, rename `WorkPacket` to `FillableBuffer`
5. `cargo build`
6. Rename `FillableBuffer::run()` to `FillableBuffer::fill()`
7. `cargo build`
8. Rename `FillableBuffer` back to `WorkPacket`
9. `cargo build`, which should ICE

Here is the error message with my environment information:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-arg=-Tlink.x --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
warning: `magnet-zither` (bin "magnet-zither") generated 1 warning
error: could not compile `magnet-zither`; 1 warning emitted
```

**Comment by Aaron1011** [comment] 2021-12-13 22:49
@lopsided98: Thanks - I've been able to reproduce this crash locally, and I'm working on minimizing it.

**Comment by Aaron1011** [comment] 2021-12-14 00:37
This appears to be caused by the way we handle decoding query values from the incremental cache. Decoding a `ty::AdtDef` calls `tcx.adt_def` with a decoded `DefId`. This causes us to start a **new query execution** in the middle of decoding the result of a different query: https://github.com/rust-lang/rust/blob/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/compiler/rustc_middle/src/ty/codec.rs#L311-L316

As a result, we can get a call stack like this:

1. We start executing the query `check_mod_liveness`, and begin recording query dependencies.
2. Inside the query, we make a call to the query `tcx.typeck`: https://github.com/rust-lang/rust/blob/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c/compiler/rustc_passes/src/liveness.rs#L520
3. We determine that the query result is green and cached on disk, so we start decoding its result from the incremental cache. At this point, we are still inside the `check_mod_liveness` query.
4. We try to decode an `AdtDef`, and call `tcx.adt_def`. This results in the `check_mod_liveness` query depending on the `adt_def` query, even though it would normally never have such an edge with an empty cache.

Normally, the design of the various queries enforces a certain order for the list of edges for a particular `DepNode`. For example, you need to call `hir_owner` to get the children of a module - then, you can lookup information using the `HirId`s of the children. If a child gets deleted or renamed, then the `hir_owner` node will be red, which will stop us from trying to mark the subsequent non-existent child `DepNode` as green. However, this weird 'decoding edge' bypasses that, injecting an HIR-related edge into some ancestor query's dependencies. 

It might be possible to make invoking queries during decoding work properly, but I think the query system is already quite complicated without adding in this weird form of recursion. We should ban new query execution inside the internals of the query system (in particular, during decoding), and encode the full contents of an `AdtDef` into the cache.

**Comment by pymongo** [comment] 2021-12-16 12:44
I reproduce this ICE when I modified some hyper source code and recompile

```
[w@ww hyper]$ cargo c
    Checking log v0.4.14
    Checking futures-util v0.3.15
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C link-arg=-fuse-ld=lld -C target-cpu=znver3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `log`
warning: build failed, waiting for other jobs to finish...
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C link-arg=-fuse-ld=lld -C target-cpu=znver3 --crate-type lib
```

**Comment by alexxbb** [comment] 2021-12-26 18:07
I also hit exactly the same ICE with my crate on stable 1.57, but in my case I only changed module item visibility, i.e. adding/ removing `pub`. `cargo clean` works as a workaround.

**Comment by Aaron1011** [comment] 2022-01-17 07:26
This should be fixed on the latest nightly.

**Closed by Aaron1011** 2022-01-17 07:26 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
