### ISSUE TITLE
compile error with bad cache state

### ISSUE THREAD

**Issue by rekby** [rust-lang/rust#94226] opened 2022-02-21 18:41 UTC
### Code
Can't show code now.

It is error with cache. It doesn't reproduce on other version of rust toolchain (beta, nightly) and stop reprocude when I remove folder target.

### Meta

`rustc --version --verbose`:
```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: aarch64-apple-darwin
release: 1.58.1
LLVM version: 13.0.0
```

### Error output

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.1 (db9d1b20b 2022-01-20) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: some of the compiler flags provided by cargo are hidden


error: internal compiler error: unexpected panic
query stack during panic:

#0 [analysis] running analysis passes on this crate
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
end of query stack

note: rustc 1.58.1 (db9d1b20b 2022-01-20) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `xxx`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
stack backtrace:
   0:        0x10372d598 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98d8e939df2a84c8
   1:        0x103776b30 - core::fmt::write::ha8927896f8d44e8d
   2:        0x10371ed78 - std::io::Write::write_fmt::h5be52fc0ae77f963
   3:        0x103730094 - std::panicking::default_hook::{{closure}}::h7ab34c9d6fd8d067
   4:        0x10372fc74 - std::panicking::default_hook::h6507a23c659c2199
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_metadata/src/rmeta/def_path_hash_map.rs:18:85
stack backtrace:
   0:        0x104cf1598 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98d8e939df2a84c8
   1:        0x104d3ab30 - core::fmt::write::ha8927896f8d44e8d
   2:        0x104ce2d78 - std::io::Write::write_fmt::h5be52fc0ae77f963
   3:        0x104cf4094 - std::panicking::default_hook::{{closure}}::h7ab34c9d6fd8d067
   4:        0x104cf3c74 - std::panicking::default_hook::h6507a23c659c2199
   5:        0x10a6edd60 - rustc_driver[e163ca5a867f5b73]::DEFAULT_HOOK::{closure#0}::{closure#0}
   5:        0x10bcb1d60 - rustc_driver[e163ca5a867f5b73]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x103730868 - std::panicking::rust_panic_with_hook::h032de7ae9e9d479f
   6:        0x104cf4868 - std::panicking::rust_panic_with_hook::h032de7ae9e9d479f
   7:        0x103730360 - std::panicking::begin_panic_handler::{{closure}}::ha7b561c0fbbe4ae5
   7:        0x104cf4360 - std::panicking::begin_panic_handler::{{closure}}::ha7b561c0fbbe4ae5
   8:        0x10372da58 - std::sys_common::backtrace::__rust_end_short_backtrace::h0ff1db7619f9e51e
   8:        0x104cf1a58 - std::sys_common::backtrace::__rust_end_short_backtrace::h0ff1db7619f9e51e
   9:        0x1037302f0 - _rust_begin_unwind
   9:        0x104cf42f0 - _rust_begin_unwind
  10:        0x1037a604c - core::panicking::panic_fmt::h660aa0926f67c6d3
  10:        0x104d6a04c - core::panicking::panic_fmt::h660aa0926f67c6d3
  11:        0x1037a5fd0 - core::panicking::panic::h87e190dcd64449c6
  11:        0x104d69fd0 - core::panicking::panic::h87e190dcd64449c6
  12:        0x10d874578 - <rustc_metadata[386c935a8c064e96]::creader::CStore as rustc_session[692bbed48032724a]::cstore::CrateStore>::def_path_hash_to_def_id
  12:        0x10ee38578 - <rustc_metadata[386c935a8c064e96]::creader::CStore as rustc_session[692bbed48032724a]::cstore::CrateStore>::def_path_hash_to_def_id
  13:        0x10f4dd084 - <rustc_middle[79e9e05f14eaf4f]::ty::context::TyCtxt>::def_path_hash_to_def_id
  13:        0x10df19084 - <rustc_middle[79e9e05f14eaf4f]::ty::context::TyCtxt>::def_path_hash_to_def_id
  14:        0x10f59730c - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::dep_node::DepNode<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind> as rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  15:        0x10ea9dc9c - rustc_query_impl[5080f9f1af2dd459]::query_callbacks::adt_def::force_from_dep_node
  16:        0x10f4c9fa0 - <rustc_middle[79e9e05f14eaf4f]::ty::context::TyCtxt as rustc_query_system[6cd4139aaa8a398a]::dep_graph::DepContext>::try_force_from_dep_node
  14:        0x10dfd330c - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::dep_node::DepNode<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind> as rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepNodeExt>::extract_def_id
  15:        0x10d4d9c9c - rustc_query_impl[5080f9f1af2dd459]::query_callbacks::adt_def::force_from_dep_node
  16:        0x10df05fa0 - <rustc_middle[79e9e05f14eaf4f]::ty::context::TyCtxt as rustc_query_system[6cd4139aaa8a398a]::dep_graph::DepContext>::try_force_from_dep_node
  17:        0x10d516304 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  17:        0x10eada304 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  18:        0x10eada2d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  19:        0x10eada2d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  20:        0x10eada2d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  21:        0x10eada2d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  22:        0x10eaa8838 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  23:        0x10e8a15e8 - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::ensure_must_run::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt, rustc_span[b8f4005862573342]::def_id::LocalDefId, rustc_span[b8f4005862573342]::def_id::LocalDefId>
  24:        0x10e93656c - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::get_query::<rustc_query_impl[5080f9f1af2dd459]::queries::mir_borrowck, rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  25:        0x10be488ac - <rustc_middle[79e9e05f14eaf4f]::hir::map::Map>::par_body_owners::<rustc_interface[2ff3308060262fe3]::passes::analysis::{closure#2}::{closure#0}>
  26:        0x10bdb7244 - rustc_interface[2ff3308060262fe3]::passes::analysis
  27:        0x10eb0e330 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[79e9e05f14eaf4f]::ty::context::TyCtxt, (), core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  18:        0x10d5162d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  19:        0x10d5162d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  28:        0x10e9d9690 - rustc_data_structures[43902d68869e4df6]::stack::ensure_sufficient_stack::<(core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepNodeIndex), rustc_query_system[6cd4139aaa8a398a]::query::plumbing::execute_job<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt, (), core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#3}>
  20:        0x10d5162d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  29:        0x10e8f5894 - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::try_execute_query::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt, rustc_query_system[6cd4139aaa8a398a]::query::caches::DefaultCache<(), core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>>
  21:        0x10d5162d4 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_previous_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  30:        0x10e96e964 - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::get_query::<rustc_query_impl[5080f9f1af2dd459]::queries::analysis, rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  31:        0x10bd06358 - <rustc_interface[2ff3308060262fe3]::passes::QueryContext>::enter::<rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  22:        0x10d4e4838 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::try_mark_green::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  23:        0x10d2dd5e8 - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::ensure_must_run::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt, rustc_span[b8f4005862573342]::def_id::LocalDefId, rustc_span[b8f4005862573342]::def_id::LocalDefId>
  24:        0x10d37256c - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::get_query::<rustc_query_impl[5080f9f1af2dd459]::queries::mir_borrowck, rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  25:        0x10a8848ac - <rustc_middle[79e9e05f14eaf4f]::hir::map::Map>::par_body_owners::<rustc_interface[2ff3308060262fe3]::passes::analysis::{closure#2}::{closure#0}>
  26:        0x10a7f3244 - rustc_interface[2ff3308060262fe3]::passes::analysis
  27:        0x10d54a330 - <rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepGraph<rustc_middle[79e9e05f14eaf4f]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[79e9e05f14eaf4f]::ty::context::TyCtxt, (), core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  32:        0x10bcc683c - <rustc_interface[2ff3308060262fe3]::interface::Compiler>::enter::<rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}::{closure#2}, core[fce59e73adef6839]::result::Result<core[fce59e73adef6839]::option::Option<rustc_interface[2ff3308060262fe3]::queries::Linker>, rustc_errors[b2cc875139393f97]::ErrorReported>>
  33:        0x10bcba974 - rustc_span[b8f4005862573342]::with_source_map::<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_interface[2ff3308060262fe3]::interface::create_compiler_and_run<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#1}>
  34:        0x10bcc73f8 - <scoped_tls[cacbb83edc611a9]::ScopedKey<rustc_span[b8f4005862573342]::SessionGlobals>>::set::<rustc_interface[2ff3308060262fe3]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[2ff3308060262fe3]::interface::run_compiler<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#0}::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  35:        0x10bcc4348 - std[fcb60cce0fbf018a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2ff3308060262fe3]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[2ff3308060262fe3]::interface::run_compiler<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  36:        0x10bd0b67c - <<std[fcb60cce0fbf018a]::thread::Builder>::spawn_unchecked<rustc_interface[2ff3308060262fe3]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[2ff3308060262fe3]::interface::run_compiler<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#1} as core[fce59e73adef6839]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:        0x104cfe1dc - std::sys::unix::thread::Thread::new::thread_start::h8d5e19fc4f27caac
  28:        0x10d415690 - rustc_data_structures[43902d68869e4df6]::stack::ensure_sufficient_stack::<(core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_query_system[6cd4139aaa8a398a]::dep_graph::graph::DepNodeIndex), rustc_query_system[6cd4139aaa8a398a]::query::plumbing::execute_job<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt, (), core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#3}>
  29:        0x10d331894 - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::try_execute_query::<rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt, rustc_query_system[6cd4139aaa8a398a]::query::caches::DefaultCache<(), core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>>
  30:        0x10d3aa964 - rustc_query_system[6cd4139aaa8a398a]::query::plumbing::get_query::<rustc_query_impl[5080f9f1af2dd459]::queries::analysis, rustc_query_impl[5080f9f1af2dd459]::plumbing::QueryCtxt>
  31:        0x10a742358 - <rustc_interface[2ff3308060262fe3]::passes::QueryContext>::enter::<rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  32:        0x10a70283c - <rustc_interface[2ff3308060262fe3]::interface::Compiler>::enter::<rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}::{closure#2}, core[fce59e73adef6839]::result::Result<core[fce59e73adef6839]::option::Option<rustc_interface[2ff3308060262fe3]::queries::Linker>, rustc_errors[b2cc875139393f97]::ErrorReported>>
  33:        0x10a6f6974 - rustc_span[b8f4005862573342]::with_source_map::<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_interface[2ff3308060262fe3]::interface::create_compiler_and_run<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#1}>
  34:        0x10a7033f8 - <scoped_tls[cacbb83edc611a9]::ScopedKey<rustc_span[b8f4005862573342]::SessionGlobals>>::set::<rustc_interface[2ff3308060262fe3]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[2ff3308060262fe3]::interface::run_compiler<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#0}::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  35:        0x10a700348 - std[fcb60cce0fbf018a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2ff3308060262fe3]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[2ff3308060262fe3]::interface::run_compiler<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>
  36:        0x10a74767c - <<std[fcb60cce0fbf018a]::thread::Builder>::spawn_unchecked<rustc_interface[2ff3308060262fe3]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[2ff3308060262fe3]::interface::run_compiler<core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>, rustc_driver[e163ca5a867f5b73]::run_compiler::{closure#1}>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#0}, core[fce59e73adef6839]::result::Result<(), rustc_errors[b2cc875139393f97]::ErrorReported>>::{closure#1} as core[fce59e73adef6839]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  37:        0x10373a1dc - std::sys::unix::thread::Thread::new::thread_start::h8d5e19fc4f27caac
  38:        0x1a6361240 - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.1 (db9d1b20b 2022-01-20) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
  38:        0x1a6361240 - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.1 (db9d1b20b 2022-01-20) running on aarch64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
#0 [analysis] running analysis passes on this crate
end of query stack
end of query stack
```

</p>
</details>

**Comment by workingjubilee** [comment] 2023-02-26 11:04
Closing as a probable duplicate of https://github.com/rust-lang/rust/issues/92163

**Closed by workingjubilee** 2023-02-26 11:04 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
