### ISSUE TITLE
Mentions of builtin types mark an import with the same name as used.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#44311] opened 2017-09-04 10:15 UTC
Found when implementing #44240: turns out `panic!()` in a module marks `std::u32` imports as used, even if they aren't actually needed.
Simple testcase:
```rust
// This should always warn:
use std::u32;
// If only the builtin type is used:
fn main() { let _: u32; }
```
cc @petrochenkov

**Comment by ollie27** [comment] 2017-09-04 14:34
Duplicate of #40774

**Comment by Mark-Simulacrum** [comment] 2017-09-04 14:52
Closing as a duplicate.

**Closed by Mark-Simulacrum** 2017-09-04 14:52 UTC
