### ISSUE TITLE
Compiler outputs error in pieces, creating spaghetti output.

### ISSUE THREAD

**Issue by muja** [rust-lang/rust#27468] opened 2015-08-02 12:09 UTC
Output:

```
$ cargo test -- --nocapture
   Compiling unrar v0.1.0 (file:///Users/danyel/workspace/rust/unrar)
src/archive.rs:151:17: 151:21src/archive.rs:151:17: 151:21  error: error: expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`

src/archive.rssrc/archive.rs::151151                  Some(Err(error))                Some(Err(error))

                                                                      ^~~~^~~~

Build failed, waiting for other jobs to finish...
Could not compile `unrar`.

To learn more, run the command again with --verbose.

$ cargo test -- --nocapture
   Compiling unrar v0.1.0 (file:///Users/danyel/workspace/rust/unrar)
src/archive.rs:151:17: 151:21 error: src/archive.rs:151:17: 151:21 expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`
src/archive.rs:error: 151                 Some(Err(error))expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`

                                   ^~~~src/archive.rs:
151                 Some(Err(error))
                                   ^~~~
Build failed, waiting for other jobs to finish...
Could not compile `unrar`.

To learn more, run the command again with --verbose.

$ cargo test -- --nocapture
   Compiling unrar v0.1.0 (file:///Users/danyel/workspace/rust/unrar)
src/archive.rs:151:17: 151:21 src/archive.rs:151:17: 151:21 error: expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`error:
expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`
src/archive.rs:151                 Some(Err(error))src/archive.rs
:151                 Some(Err(error))
                                   ^~~~
^~~~
Build failed, waiting for other jobs to finish...
Could not compile `unrar`.

To learn more, run the command again with --verbose.

$ cargo test -- --nocapture
   Compiling unrar v0.1.0 (file:///Users/danyel/workspace/rust/unrar)
src/archive.rs:151:17: 151:21src/archive.rs:151:17: 151:21  error: error: expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`expected one of `!`, `.`, `::`, `;`, `{`, `}`, or an operator, found `Some`

src/archive.rssrc/archive.rs::151151                  Some(Err(error))                Some(Err(error))

                                                                      ^~~~^~~~

Build failed, waiting for other jobs to finish...
Could not compile `unrar`.

To learn more, run the command again with --verbose.
```

**Comment by eddyb** [comment] 2015-08-02 12:48
Looking at [the current implementation of `term::stderr`](https://github.com/rust-lang/rust/blob/f7b3cd3337021ed16302fd6a9cc5bcf0afee6679/src/libterm/lib.rs#L124), wrapping `std::io::stderr()` in a `LineWriter` should help with at least keeping individual lines from being interleaved.
Since `libterm` is an internal library, this change should not affect anything else, right?
cc @rust-lang/compiler

**Comment by Aatch** [comment] 2015-08-03 00:50
I'm confused, how is this even happening? There's no multithreading going on in the compiler, so the compiler output itself shouldn't be interleaved. Could Cargo be trying to build `unrar` twice simultaneously?

**Comment by eddyb** [comment] 2015-08-03 19:21
@Aatch that's exactly what's happening (cargo needs to build both a library and a test binary, AFAICT), and it's interleaving because there are multiple `write` calls per error, instead of a single one.

**Comment by nikomatsakis** [comment] 2015-08-06 19:58
So. On a related note, I've been wanting to refactor the compiler to "bundle up" an error and its associated notes, helps, etc into an atomic unit and emit it once. This provides extra incentive.

**Comment by leodasvacas** [comment] 2017-01-29 12:44
Triage: Bug includes no code for reproduction. Diagnostics have changed a lot, has this been fixed?

**Comment by sfackler** [comment] 2017-01-29 20:31
I believe we emit diagnostics atomically now.

**Comment by nikomatsakis** [comment] 2017-02-04 02:10
Yes, I think we can close this.

**Closed by nikomatsakis** 2017-02-04 02:10 UTC
Labels: A-diagnostics
