### ISSUE TITLE
Poor diagnostic when returned `impl Fn` is not general enough

### ISSUE THREAD

**Issue by Luminiscental** [rust-lang/rust#93311] opened 2022-01-25 23:17 UTC
Given the [following code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b7e13e6ea588111e77cc85ec4faaef57):

```rust
fn main() {
    fn opaque<T, F: Fn(T) -> bool>(f: F) -> impl Fn(T) -> bool {
        f
    }
    (0..3).filter(opaque(|_| true));
}
```

The current output is a bit unhelpful:

```
error[E0308]: mismatched types
   --> src/main.rs:5:12
    |
2   |     fn opaque<T, F: Fn(T) -> bool>(f: F) -> impl Fn(T) -> bool {
    |                                             ------------------
    |                                             |
    |                                             the expected opaque type
    |                                             the found opaque type
...
5   |     (0..3).filter(opaque(|_| true));
    |            ^^^^^^        --------
    |            |             |
    |            |             the expected closure
    |            |             the found closure
    |            lifetime mismatch
    |
    = note: expected associated type `<impl Fn(&i32)-> bool as FnOnce<(&i32,)>>::Output`
               found associated type `<impl Fn(&i32)-> bool as FnOnce<(&i32,)>>::Output`
note: the lifetime requirement is introduced here
```

Ideally, I think a diagnostic more in line with the [following case](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=84cf83ec68caf1d9735a68d32fb07059) (replacing `impl ...` with just `F`) would be better:

```rust
fn main() {
    fn opaque<T, F: Fn(T) -> bool>(f: F) -> F {
        f
    }
    (0..3).filter(opaque(|_| true));
}
```

Which describes the actual issue of lifetime generality:

```
error: implementation of `FnOnce` is not general enough
 --> src/main.rs:5:12
  |
5 |     (0..3).filter(opaque(|_| true));
  |            ^^^^^^ implementation of `FnOnce` is not general enough
  |
  = note: closure with signature `fn(&'2 i32) -> bool` must implement `FnOnce<(&'1 i32,)>`, for any lifetime `'1`...
  = note: ...but it actually implements `FnOnce<(&'2 i32,)>`, for some specific lifetime `'2`
```

**Comment by compiler-errors** [comment] 2022-06-20 04:02
The error message for this has improved in nightly since NLL was enabled:

```
error: implementation of `FnMut` is not general enough
 --> src/main.rs:5:5
  |
5 |     (0..3).filter(opaque(|_| true));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `FnMut` is not general enough
  |
  = note: `impl Fn(&'2 i32)-> bool` must implement `FnMut<(&'1 i32,)>`, for any lifetime `'1`...
  = note: ...but it actually implements `FnMut<(&'2 i32,)>`, for some specific lifetime `'2`

error[E0308]: mismatched types
 --> src/main.rs:5:5
  |
2 |     fn opaque<T, F: Fn(T) -> bool>(f: F) -> impl Fn(T) -> bool {
  |                                             ------------------
  |                                             |
  |                                             the expected opaque type
  |                                             the found opaque type
...
5 |     (0..3).filter(opaque(|_| true));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
  |
  = note: expected associated type `<impl Fn(&i32)-> bool as FnOnce<(&i32,)>>::Output`
             found associated type `<impl Fn(&i32)-> bool as FnOnce<(&i32,)>>::Output`
note: the lifetime requirement is introduced here
```

The second error is vague, but the first one is pretty clear. I'm gonna close this because that's what the issue is asking for, I think.

**Closed by compiler-errors** 2022-06-20 04:02 UTC
Labels: A-diagnostics, T-compiler
