### ISSUE TITLE
7% regression in compile time of tuple-stress benchmark

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44677] opened 2017-09-18 15:59 UTC
According to [perf.rust-lang.org graphs](https://perf.rust-lang.org/?start=2017-09-10T00%3A00%3A00%2B00%3A00&end=2017-09-17T00%3A00%3A00%2B00%3A00&crates=%5B%22tuple-stress%22%5D&stat=cpu-clock) https://github.com/rust-lang/rust/pull/44275 caused a ~8% regression in compile time for this benchmark

cc @eddyb (an old nemesis!)

**Comment by eddyb** [comment] 2017-09-18 17:21
Yeah, we knew it would take a hit, but without absolute graphs it didn't seem that bad and we just took the risk.

cc @nikomatsakis Do you know of any caching missing here? We do cache the result of evaluation, is this just the cost of renormalizing over and over again?

**Comment by nikomatsakis** [comment] 2017-09-18 19:24
@eddyb I'm not sure! Would have to profile I guess.

**Comment by nikomatsakis** [comment] 2017-09-21 20:13
triage: P-high

Calling this P-high until we decide if (a) it is isolated or has a pervasive effect and (b) if we know the cause and can readily fix. It'd be great for someone to do some comparative profiling!

**Comment by nikomatsakis** [comment] 2017-09-21 20:13
Note: the sources to the benchmark can be found in https://github.com/rust-lang-nursery/rustc-benchmarks

**Comment by eddyb** [comment] 2017-09-21 20:16
I believe this might be `src/librustc_passes/consts.rs` at fault, since it evaluates everything in there, and it's probably interning `ty::Const`, not any of the deferred array length evaluation changes.
All of this should get better with `miri`, I would think, and I expect the effect to be isolated.

**Comment by nikomatsakis** [comment] 2017-09-21 20:20
Based on @eddyb's comment, lowering priority until miri is merged.

triage: P-low

**Comment by Mark-Simulacrum** [comment] 2017-09-21 21:40
Benchmarks are actually here: https://github.com/rust-lang-nursery/rustc-perf/tree/master/collector/benchmarks

**Comment by michaelwoerister** [comment] 2017-11-30 15:33
Discussed in triage. Closing since there isn't anything actionable here really.

**Closed by michaelwoerister** 2017-11-30 15:33 UTC
Labels: C-bug, I-compiletime, P-low, regression-from-stable-to-nightly, T-compiler
