### ISSUE TITLE
pattern binding exhibits inconsistent capture ordering

### ISSUE THREAD

**Issue by conradludgate** [rust-lang/rust#97244] opened 2022-05-21 07:34 UTC
Given a non copy type like
```rust
#[derive(Debug)]
enum NonCopy {
    Some(u8), 
    None,
}
```

You can pattern match on the variants without moving the original value:

```rust
let x = NonCopy::Some(42);
if let NonCopy::Some(bar) = x {
    dbg!(x, bar); // x is still live. 
}
```

Here, `bar` only needed to copy the u8 and not the whole `x`.

Interestingly, this doesn't work in the case of pattern bindings:

```rust
if let foo @ NonCopy::Some(bar) = x {
    dbg!(foo, bar);
}
```

```
error[[E0382]](https://doc.rust-lang.org/nightly/error-index.html#E0382): use of moved value: `x`
  --> src/main.rs:11:32
   |
8  |     let x = NonCopy::Some(42);
   |         - move occurs because `x` has type `NonCopy`, which does not implement the `Copy` trait
...
11 |     if let foo @ NonCopy::Some(bar) = x {
   |            --------------------^^^-
   |            |                   |
   |            |                   value used here after move
   |            value moved here
```

This hints that it seems to be re-writing this code as something like

```rust
let foo = x; // value moved here
if let NonCopy::Some(bar) = x {} // value used here after move.
```

This could be re-ordered like

```rust
if let NonCopy::Some(bar) = x {
    let foo = x;
}
```

To make it compile correctly.

---

Inconsistent results! If we update our `NonCopy` type to be a single-variant type (like a struct)

```rust
#[derive(Debug)]
struct NonCopy {
    bar: u8, 
}
```

Then our binding statements from before do again compile

```rust
let foo @ NonCopy{bar} = x;
dbg!(foo, bar);
```

> **Note**
> It's not enough for the pattern to be irrefutable, it only matters whether it's single or multi variant. 

> **Note**
> All behaviours shown above are visible on nightly and stable, as well as all editions of the compiler

**Comment by programmerjake** [comment] 2023-04-11 23:07
this is a duplicate of #90368

**Comment by jyn514** [comment] 2023-04-26 04:03
Closing as a duplicate of https://github.com/rust-lang/rust/issues/90368.

**Closed by jyn514** 2023-04-26 04:03 UTC
