### ISSUE TITLE
Function items will not coerce to function pointers when inferring the type of a generic function argument with a trait bound

### ISSUE THREAD

**Issue by hiddenhare** [rust-lang/rust#62621] opened 2019-07-12 12:15 UTC
Function items do not coerce to fn pointer types when they are passed as a generic function parameter with a trait bound. A manual cast or type annotation is required.

    trait Foo {}
    impl Foo for fn() {}
    
    fn non_generic(_f: fn()) {}
    fn generic_without_bound<F>(_f: F) {}
    fn generic_with_bound<F: Foo>(_f: F) {}
    
    fn function_item() {}
    
    fn main() {
        //succeeds
        non_generic(function_item); 
        
        //succeeds
        generic_without_bound(function_item);
        
        //fails: "the trait `Foo` is not implemented for `fn() {function_item}`"
        generic_with_bound(function_item);
        
        //succeeds
        generic_with_bound::<fn()>(function_item);
        
        //succeeds
        generic_with_bound(function_item as fn());
    }

Error first identified on rustc 1.37.0-nightly (400b409ef 2019-06-09), but the error reproduces on the playground for 1.36-stable and 1.37-beta2.

**Comment by gnzlbg** [comment] 2019-07-12 12:24
This is by design. Every function item gets its own anonymous type, just like closures. That's why you need the cast, and why the error message says that the type of the function is `fn() {function_item}` and not just `fn()`. There is an issue opened for a better error message in #62385

**Comment by jonas-schievink** [comment] 2019-07-12 12:28
Closing in favor of the diagnostics improvements in #62385, or an appropriate RFC adding these coercions

**Closed by jonas-schievink** 2019-07-12 12:28 UTC
Labels: A-coercions, C-feature-request, T-lang, needs-rfc

**Comment by hiddenhare** [comment] 2019-07-12 12:32
Thanks folks. Looks like my main misunderstanding was that I failed to spot this information in the nomicon: "Note that we do not perform coercions when matching traits [...] If there is an impl for some type `U` and `T` coerces to `U`, that does not constitute an implementation for `T`."
