### ISSUE TITLE
NLL gives weird/incorrect errors when enumerating parallel iterator

### ISSUE THREAD

**Issue by lovesegfault** [rust-lang/rust#52147] opened 2018-07-08 01:17 UTC
I wrote the following, incorrect, code on the Playground for playing around with NLL
```Rust
#![feature(nll)]
extern crate rayon; // 1.0.1

use rayon::prelude::*;

fn map(m: &mut Vec<Vec<usize>>, f: fn(&usize, &usize) -> (usize, usize)) -> Vec<Vec<usize>> {
    let mut out: Vec<Vec<usize>> = Vec::new();
    m.par_iter().enumerate().for_each(|(i, v1)| {
        v1.par_iter().enumerate().for_each(|(j, v2)| {
            let c = f(&i, &j);
            out[c.0][c.1] = *v2;
        })
    });
    out
}

fn main() {}
```
This spits out the following, very unhelpful, error message
```
error[E0596]: cannot borrow immutable item `out` as mutable
  --> src/main.rs:9:44
   |
9  |           v1.par_iter().enumerate().for_each(|(j, v2)| {
   |  ____________________________________________^
10 | |             let c = f(&i, &j);
11 | |             out[c.0][c.1] = *v2;
12 | |         })
   | |_________^ cannot borrow as mutable
```
Disabling NLL, however, gives me a much more comprehensible error regarding the incorrect borrow
```
error[E0387]: cannot borrow data mutably in a captured outer variable in an `Fn` closure
 --> src/main.rs:9:44
  |
9 |         v1.par_iter().enumerate().for_each(|(j, v2)| {
  |                                            ^^^^^^^^^
  |
help: consider changing this to accept closures that implement `FnMut`
 --> src/main.rs:8:39
  |
8 |       m.par_iter().enumerate().for_each(|(i, v1)| {
  |  _______________________________________^
9 | |         v1.par_iter().enumerate().for_each(|(j, v2)| {
10| |             let c = f(&i, &j);
11| |             out[c.0][c.1] = *v2;
12| |         })
13| |     });
  | |_____^
```
Here's a [link to the Playground](https://play.rust-lang.org/?gist=085a7f00261bd0e9627ad5c2adc68876&version=nightly&mode=debug&edition=2018)

**Comment by matthewjasper** [comment] 2018-07-22 10:30
New output:

<details>

```text
   Compiling playground v0.0.1 (file:///playground)
error[E0596]: cannot borrow `out` as mutable, as it is a captured variable in a `Fn` closure
  --> src/main.rs:11:13
   |
11 |             out[c.0][c.1] = *v2;
   |             ^^^ cannot borrow as mutable
   |
help: consider changing this to accept closures that implement `FnMut`
  --> src/main.rs:9:44
   |
9  |           v1.par_iter().enumerate().for_each(|(j, v2)| {
   |  ____________________________________________^
10 | |             let c = f(&i, &j);
11 | |             out[c.0][c.1] = *v2;
12 | |         })
   | |_________^

error[E0596]: cannot borrow `out` as mutable, as it is a captured variable in a `Fn` closure
  --> src/main.rs:9:44
   |
9  |         v1.par_iter().enumerate().for_each(|(j, v2)| {
   |                                            ^^^^^^^^^ cannot borrow as mutable
10 |             let c = f(&i, &j);
11 |             out[c.0][c.1] = *v2;
   |             --- mutable borrow occurs due to use of `out` in closure
   |
help: consider changing this to accept closures that implement `FnMut`
  --> src/main.rs:8:39
   |
8  |       m.par_iter().enumerate().for_each(|(i, v1)| {
   |  _______________________________________^
9  | |         v1.par_iter().enumerate().for_each(|(j, v2)| {
10 | |             let c = f(&i, &j);
11 | |             out[c.0][c.1] = *v2;
12 | |         })
13 | |     });
   | |_____^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0596`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

</details>

**Comment by nikomatsakis** [comment] 2018-08-06 20:27
Looking over the new output, it is obviously much better, but there are a few problems:

**We get two messages, when one would seem to suffice.** The problem here is that the inner closure gives us an error about `out`, but then the outer closure gives us the same variable -- in that case, the borrow is from constructing the inner closure, I imagine.

**The "consider this change this to accept closures that implement `FnMut`" message is kind of strange, too.** This is true without NLL as well, but it seems like it is highlighting **the closure**, where the problem is really that `for_each` does not accept `FnMut` closures but just `Fn` closures. 

I would probably prefer to see:

```
error[E0596]: cannot borrow `out` as mutable, as it is a captured variable in a `Fn` closure
  --> src/main.rs:11:13
   |
11 |             out[c.0][c.1] = *v2;
   |             ^^^ cannot borrow as mutable
   |
help: the function `for_each` accepts only `Fn` closures, not `FnMut` closures
  --> src/main.rs:9:44
   |
9  |           v1.par_iter().enumerate().for_each(|(j, v2)| {
   |                                     --------
10 | |             let c = f(&i, &j);
11 | |             out[c.0][c.1] = *v2;
12 | |         })
```

Regardless, I would classify this as a "minor" diagnostics issue at this point. I am going to move this from the RC milestone to the Rust 2018 Release milestone.

**Comment by bemeurer** [comment] 2018-08-07 05:15
@nikomatsakis Just to put some emphasis behind this, the very first time I encountered this issue I was confused because the error message ``
help: consider changing this to accept closures that implement `FnMut`
`` seems to suggest that there is something *I* can do to make `for_each` take an `FnMut` closure, which isn't true.

**Comment by nikomatsakis** [comment] 2018-08-07 10:13
@bemeurer yes. Thinking more about this, I wonder if we can "re-orient" the error a bit more:

```
error[E0596]: `for_each` does not permit mutating captured variables
  --> src/main.rs:11:13
   |
9  |           v1.par_iter().enumerate().for_each(|(j, v2)| {
   |                                     -------- `for_each` accepts only `Fn` closures
10 |             let c = f(&i, &j);
11 |             out[c.0][c.1] = *v2;
   |             ^^^ cannot borrow as mutable as a `Fn` closure, only `FnMut`
```

**Comment by nikomatsakis** [comment] 2018-08-07 10:14
It will require perhaps a bit of analysis on our part to put the blame so squarely on `for_each`—although, actually, I think that the only time that we infer a closure to be `Fn` when it mutates variables (and not `FnMut`) is if it is passed directly to a fn that requires `Fn`, so maybe we can just rely on that.

**Comment by bemeurer** [comment] 2018-08-07 14:54
Ah, yes! An error like that would be amazing, and much more clarifying. 

A small note is that I think we ought to say ``cannot borrow as mutable _in_ a `Fn` closure, only _in_ `FnMut`
``, no?

**Comment by steveklabnik** [comment] 2020-01-27 14:31
Now that nll is the only borrowcheck, this error message has improved, or rather, not regressed :)

```text
error[E0596]: cannot borrow `out` as mutable, as it is a captured variable in a `Fn` closure
  --> src/main.rs:10:13
   |
10 |             out[c.0][c.1] = *v2;
   |             ^^^ cannot borrow as mutable
   |
help: consider changing this to accept closures that implement `FnMut`
  --> src/main.rs:8:44
   |
8  |           v1.par_iter().enumerate().for_each(|(j, v2)| {
   |  ____________________________________________^
9  | |             let c = f(&i, &j);
10 | |             out[c.0][c.1] = *v2;
11 | |         })
   | |_________^

error[E0596]: cannot borrow `out` as mutable, as it is a captured variable in a `Fn` closure
  --> src/main.rs:8:44
   |
8  |         v1.par_iter().enumerate().for_each(|(j, v2)| {
   |                                            ^^^^^^^^^ cannot borrow as mutable
9  |             let c = f(&i, &j);
10 |             out[c.0][c.1] = *v2;
   |             --- mutable borrow occurs due to use of `out` in closure
   |
help: consider changing this to accept closures that implement `FnMut`
  --> src/main.rs:7:39
   |
7  |       m.par_iter().enumerate().for_each(|(i, v1)| {
   |  _______________________________________^
8  | |         v1.par_iter().enumerate().for_each(|(j, v2)| {
9  | |             let c = f(&i, &j);
10 | |             out[c.0][c.1] = *v2;
11 | |         })
12 | |     });
   | |_____^

error: aborting due to 2 previous errors

```

Closing!

**Closed by steveklabnik** 2020-01-27 14:31 UTC
Labels: A-NLL, NLL-diagnostics, P-medium
