### ISSUE TITLE
Incremental compilation fails on clean build of Alacritty

### ISSUE THREAD

**Issue by jwilm** [rust-lang/rust#41829] opened 2017-05-08 16:02 UTC
I received [a report] recently that Alacritty fails to compile when using `CARGO_INCREMENTAL=1`.

Repro instructions (courtesy of @mindriot101)

```bash
sudo apt-get update && sudo apt-get install -y git curl cmake libfreetype6-dev \
   libfontconfig1-dev xclip

curl https://sh.rustup.rs -sSf | sh

git clone https://github.com/jwilm/alacritty
cd alacritty
rustup override set nightly
CARGO_INCREMENTAL=1 cargo build --release
```

The master sha at time of writing is cbabef36edd39e179391685bc9368d92df1d5a01.

I've attached the build log in case it's of use. It's *quite* large at a whopping 2.1MB. Appears to have failed spectacularly during linking.
[build.txt](https://github.com/rust-lang/rust/files/984094/build.txt)

[a report]: https://github.com/jwilm/alacritty/issues/547

**Comment by jonhoo** [comment] 2017-05-08 16:12
I believe this is a dupe of #40034.

**Comment by Mark-Simulacrum** [comment] 2017-06-22 18:00
Yes, I agree, closing.

**Closed by Mark-Simulacrum** 2017-06-22 18:00 UTC
