### ISSUE TITLE
Type inference failure in small-logger 0.2.1, Rust 1.16

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39829] opened 2017-02-14 22:52 UTC
```
101 brian@ip-10-145-43-250:~/dev/small-logger⟫ git remote -v
origin  https://github.com/octplane/small-logger (fetch)
origin  https://github.com/octplane/small-logger (push)
brian@ip-10-145-43-250:~/dev/small-logger⟫ git log -1
commit 2057cb95c036f161af73656fdbf6de8bf62835c3
Author: Pierre Baillet <pierre@baillet.name>
Date:   Mon Apr 25 16:15:12 2016 +0200

    Bump version
```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.16.0-beta.1 (5276ba72e 2017-01-31)
binary: rustc
commit-hash: 5276ba72e8fe13597200254447fce9cb3783c583
commit-date: 2017-01-31
host: x86_64-unknown-linux-gnu
release: 1.16.0-beta.1
LLVM version: 3.9
```

```
101 brian@ip-10-145-43-250:~/dev/small-logger⟫ cargo +beta build
   Compiling libc v0.2.7
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.5
   Compiling rustc-serialize v0.3.17
   Compiling getopts v0.2.14
   Compiling kernel32-sys v0.2.1
   Compiling time v0.1.34
   Compiling small-logger v0.2.1 (file:///mnt2/dev/small-logger)
error[E0282]: unable to infer enough type information about `S`
   --> src/runner.rs:111:8
    |
111 |       .args(parms.as_ref())
    |        ^^^^ cannot infer type for `S`
    |
    = note: type annotations or generic parameter binding required

error: aborting due to previous error

error: Could not compile `small-logger`.

To learn more, run the command again with --verbose.
```

Not on 1.15.

cc @octplane

**Comment by octplane** [comment] 2017-02-15 09:45
Hello, I'm not used to be mentioned in rust-lang issues... do I have anything to do?

**Comment by arielb1** [comment] 2017-02-16 21:28
Looks like the `Command::new` issue. T-libs XIB.

**Comment by alexcrichton** [comment] 2017-02-17 15:38
Agreed dupe of https://github.com/rust-lang/rust/issues/39806, closing in favor of that.

@octplane oh this is mostly just a heads up on our part. Your crate small-logger may not compile on beta today due to inference changes (see #39806) and we'll discuss in the libs team soon whether we should revert the change or not. If it's difficult to update though for you please let us know as that'll help us reach a conclusion!

**Closed by alexcrichton** 2017-02-17 15:38 UTC
Labels: regression-from-stable-to-beta, T-libs
