### ISSUE TITLE
SIGSEGV when std::time::Instant::now() called

### ISSUE THREAD

**Issue by sunnyayyl** [rust-lang/rust#125290] opened 2024-05-19 19:13 UTC
I tried this code:

```rust
fn main() {
    let now=std::time::Instant::now();
    println!("{:#?}",now);
}
```

Then it crashed with signal SIGSEGV
signal SIGSEGV: address not mapped to object (fault address: 0x680)

### Meta
Unstable channel Nix
`rustc --version --verbose`:
```
rustc 1.77.2 (25ef9e3d8 2024-04-09) (built from a source tarball)
binary: rustc
commit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04
commit-date: 2024-04-09
host: x86_64-unknown-linux-gnu
release: 1.77.2
LLVM version: 17.0.6
```

**Comment by tbu-** [comment] 2024-05-19 21:46
Do you have a stack trace?

**Comment by Nilstrieb** [comment] 2024-05-19 22:40
I have no problems with my nixos-unstable. Have you built this executable before doing an update and it segfaults now after the update? That happens sometimes with nix and isn't a bug in rust

**Comment by workingjubilee** [comment] 2024-05-20 05:58
Please retry with `RUST_BACKTRACE=1`? Or a core dump...

**Comment by sunny0531** [comment] 2024-06-04 16:07
My apologies for the late reply, but I ran the code with lldb, here's the trace:
```
Process 985 launched: '/home/user/test/target/debug/app' (x86_64)
Process 985 stopped
* thread #1, name = 'app', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x680)
    frame #0: 0x0000000000000680
error: memory read failed for 0x600
```

**Comment by sunny0531** [comment] 2024-06-04 16:13
Here's the stack trace with GDB
```
Temporary breakpoint 1 at 0x8d37: file src/main.rs, line 2.
Starting program: /home/user/test/target/debug/app 
warning: File "/nix/store/p9ysh5rk109gyjj3cn6jr54znvvlahfl-glibc-2.38-66/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/xvzz97yk73hw03v5dhhz3j47ggwf1yq1-gcc-13.2.0-lib".
To enable execution of this file add
        add-auto-load-safe-path /nix/store/p9ysh5rk109gyjj3cn6jr54znvvlahfl-glibc-2.38-66/lib/libthread_db.so.1
line to your configuration file "/home/user/.config/gdb/gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/user/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

Temporary breakpoint 1, app::main () at src/main.rs:2
2           let now=std::time::Instant::now();
```
@Nilstrieb I've never build rust from scratch, so I don't think that is the cause of the issue. I do suppose it might be glibc bug.
When I run the code with VSCode debugger
Debugger report crash at `7FFFF7E88A6D`
```
; Symbol: clock_gettime@@GLIBC_2.17
; Source: unknown
7FFFF7E88A50: F3 0F 1E FA                endbr64 
7FFFF7E88A54: 48 8B 05 6D 74 10 00       movq   0x10746d(%rip), %rax
7FFFF7E88A5B: 48 8B 80 E8 02 00 00       movq   0x2e8(%rax), %rax
7FFFF7E88A62: 48 85 C0                   testq  %rax, %rax
7FFFF7E88A65: 74 19                      je     0x7ffff7e88a80  ; <+48>
7FFFF7E88A67: 48 83 EC 08                subq   $0x8, %rsp
7FFFF7E88A6B: FF D0                      callq  *%rax
7FFFF7E88A6D: 85 C0                      testl  %eax, %eax
7FFFF7E88A6F: 75 1F                      jne    0x7ffff7e88a90  ; <+64>
7FFFF7E88A71: 31 C0                      xorl   %eax, %eax
7FFFF7E88A73: 48 83 C4 08                addq   $0x8, %rsp
7FFFF7E88A77: C3                         retq   
7FFFF7E88A78: 0F 1F 84 00 00 00 00 00    nopl   (%rax,%rax)
7FFFF7E88A80: B8 E4 00 00 00             movl   $0xe4, %eax
7FFFF7E88A85: 0F 05                      syscall 
7FFFF7E88A87: 85 C0                      testl  %eax, %eax
7FFFF7E88A89: 75 1D                      jne    0x7ffff7e88aa8  ; <+88>
7FFFF7E88A8B: 31 C0                      xorl   %eax, %eax
7FFFF7E88A8D: C3                         retq   
7FFFF7E88A8E: 66 90                      nop    
7FFFF7E88A90: 48 8B 15 79 73 10 00       movq   0x107379(%rip), %rdx
7FFFF7E88A97: F7 D8                      negl   %eax
7FFFF7E88A99: 64 89 02                   movl   %eax, %fs:(%rdx)
7FFFF7E88A9C: B8 FF FF FF FF             movl   $0xffffffff, %eax  ; imm = 0xFFFFFFFF 
7FFFF7E88AA1: EB D0                      jmp    0x7ffff7e88a73  ; <+35>
7FFFF7E88AA3: 0F 1F 44 00 00             nopl   (%rax,%rax)
7FFFF7E88AA8: 48 8B 15 61 73 10 00       movq   0x107361(%rip), %rdx
7FFFF7E88AAF: F7 D8                      negl   %eax
7FFFF7E88AB1: 64 89 02                   movl   %eax, %fs:(%rdx)
7FFFF7E88AB4: B8 FF FF FF FF             movl   $0xffffffff, %eax  ; imm = 0xFFFFFFFF 
7FFFF7E88AB9: C3                         retq   
```

**Comment by tbu-** [comment] 2024-06-04 19:48
You can get a stack trace by typing `bt` into the lldb shell.

**Comment by workingjubilee** [comment] 2024-06-15 06:27
If the segfault is inside `clock_gettime` then I don't think we're going to be of help here, sorry!

**Comment by dev-ardi** [comment] 2024-06-16 10:48
Does the segfault still happen if you use musl?

**Comment by workingjubilee** [comment] 2024-06-22 23:19
Closing this given Nilstrieb's no-repro and the lack of confirmation this is something we can fix.

**Closed by workingjubilee** 2024-06-22 23:19 UTC
Labels: O-NixOS, C-discussion

**Comment by sunnyayyl** [comment] 2024-06-30 12:48
> If the segfault is inside `clock_gettime` then I don't think we're going to be of help here, sorry!

Oh I see, thanks for your help. It might be a glib issue? My apologies.
