### ISSUE TITLE
ICE: `assertion failed: i < this.fields.count()`

### ISSUE THREAD

**Issue by mr-systems** [rust-lang/rust#86050] opened 2021-06-06 03:13 UTC
The key line seems to be the `Box::from_raw_in(/*pointer*/, allocator)` where `allocator` is specifically coming out of an Option; other than that I haven't the faintest where this is coming from.

### Code

```Rust
#![feature(allocator_api)]

use std::alloc::{Allocator, Global};
use std::ops::Drop;

pub struct CirqueLog<A: Allocator> {
    allocator: Option<A>,
}

fn main() {
    CirqueLog::<Global>::new();
}

impl<A: Allocator> Drop for CirqueLog<A> {
    fn drop(&mut self) {
        match &self.allocator {
            None => (),
            Some(allocator) => unsafe {
                Box::from_raw_in(std::ptr::null_mut() as *mut u8, allocator);
            },
        }
        // also will error:
        //if let Some(allocator) = &self.allocator {
        //    unsafe { Box::from_raw_in(std::ptr::null_mut() as *mut u8, allocator); }
        //}
    }
}

impl<A: Allocator> CirqueLog<A> {
    pub fn new() -> CirqueLog<Global> {
        CirqueLog {
            allocator: Some(Global),
        }
    }
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.54.0-nightly (9111b8ae9 2021-05-26)
binary: rustc
commit-hash: 9111b8ae9793f18179a1336417618fc07a9cac85
commit-date: 2021-05-26
host: x86_64-apple-darwin
release: 1.54.0-nightly
LLVM version: 12.0.1
```

(also breaks on [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8c7a2042edba876663ec5bfd57ad0b7e))

### Error output

```
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/9111b8ae9793f18179a1336417618fc07a9cac85/compiler/rustc_middle/src/ty/layout.rs:2189:21
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rustc_middle::ty::layout::<impl rustc_target::abi::TyAndLayoutMethods<C> for &rustc_middle::ty::TyS>::field::ty_and_layout_kind
   4: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::scalar_pair_element_llvm_type
   5: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::scalar_pair_element_llvm_type
   6: <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_codegen_llvm::abi::FnAbiLlvmExt>::llvm_type
   7: rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn
   8: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  10: rustc_codegen_llvm::base::compile_codegen_unit
  11: rustc_codegen_ssa::base::codegen_crate
  12: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  13: rustc_interface::queries::Queries::ongoing_codegen
  14: rustc_span::with_session_globals
```

</p>
</details>

**Comment by jyn514** [comment] 2021-06-06 04:36
Duplicate of https://github.com/rust-lang/rust/issues/78459.

**Closed by jyn514** 2021-06-06 04:36 UTC
Labels: C-bug, I-ICE, T-compiler
