### ISSUE TITLE
rustdoc: Search returns weird and unhelpful results

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78038] opened 2020-10-17 04:10 UTC
I found this while [searching for `Vec::sort`](https://doc.rust-lang.org/nightly/std/?search=Vec%3A%3Asort):

![image](https://user-images.githubusercontent.com/37223377/96328060-f3ff5a80-0ff3-11eb-8e67-5d24f08af7dc.png)

This is an issue on nightly, beta, and stable.

**Comment by camelid** [comment] 2020-10-17 04:13
(I just created a label for rustdoc's search feature, `A-rustdoc-search`, to help categorize issues related to the search bar. Hope that's okay!)

**Comment by SNCPlay42** [comment] 2020-10-17 05:04
This is because `Vec` has no `sort` method, only `[T]` does.

Being able to search for methods from derefs using the pointer type's name does seem like a reasonable feature to have, though.

**Comment by ollie27** [comment] 2020-10-17 10:02
Duplicate of #63080

**Closed by ollie27** 2020-10-17 10:02 UTC
Labels: A-rustdoc-search, C-bug, T-rustdoc
