### ISSUE TITLE
WASI: Cannot open paths with nightly >= 2021-03-11 when linked with LLD 11.1

### ISSUE THREAD

**Issue by abbec** [rust-lang/rust#85840] opened 2021-05-30 21:15 UTC
I have code opening a path like `std::fs::read("/absolute/path.txt")` in WASI. All the surrounding code stays the same but when I upgrade nightly from `2021-03-10` to `2021-03-11` it does not work anymore.

## Version details:

```
# opening a path with leading "/" does _NOT_ work
rustc 1.52.0-nightly (f98721f88 2021-03-10)
binary: rustc
commit-hash: f98721f886ab52d32d622ad0a46216ad03f3e525
commit-date: 2021-03-10
host: x86_64-apple-darwin
release: 1.52.0-nightly
```

```
# opening a path with leading "/" _DOES_ work
rustc 1.52.0-nightly (3a5d45f68 2021-03-09)
binary: rustc
commit-hash: 3a5d45f68cadc8fff4fbb557780f92b403b19c19
commit-date: 2021-03-09
host: x86_64-apple-darwin
release: 1.52.0-nightly
LLVM version: 12.0.0
```

Looking at the [history](https://github.com/rust-lang/rust/compare/3a5d45f68cadc8fff4fbb557780f92b403b19c19...f98721f886ab52d32d622ad0a46216ad03f3e525), the only thing I can see that looks WASI-related is [this](https://github.com/rust-lang/rust/commit/fdb899ba4bd5dffab4eec9ea575991ec5499a527) but I have no idea here and any help would be appreciated!

EDIT: This description turned out to be somewhat incorrect, see below for a good repro case.

**Comment by abbec** [comment] 2021-05-30 21:41
I was wrong, actually it does not work at all on 2021-03-10 and onwards, with or without the leading "/":

```
failed to find a pre-opened file descriptor through which "relative/path.txt" could be opened
```
and
```
failed to find a pre-opened file descriptor through which "/absolute/path.txt" could be opened
```
whereas on 2021-03-10 the same code works fine.

**Comment by apiraino** [comment] 2021-05-31 07:53
hi @abbec thanks for filing a report. Do you imply that even a snippet like this returns that error?
```
use std::fs;
fn repro() {
    fs::read("/absolute/path.txt").unwrap();
}
fn main() {
    repro();
}
```
Can you attach a small but fully actionable reproducible snippet (along with the command to compile)? There might be more to investigate and that would be useful. Thanks!

**Comment by abbec** [comment] 2021-05-31 08:51
No, that does work and I am using my own version of wasilibc that I am linking against (which is the same version as the one currently used by std) but the strange thing is that it does work on one date and the same code stops working on the next.

**Comment by abbec** [comment] 2021-05-31 09:16
Seems to have something to do with using a custom linker and using the external wasilibc, I will investigate more, still something needs to have changed between these two versions.

**Comment by abbec** [comment] 2021-05-31 09:40
Seems to be only when using a custom linker (LLVM 11 in this case). Any tips for debugging would be very appreciated!

**Comment by apiraino** [comment] 2021-05-31 09:59
Which command and rustc flags do you use to compile the sources? Also, do you get an actual error stack? If yes, can you expand that error with `RUST_BACKTRACE=full`? Are you able to test against the latest LLVM 12?

**Comment by abbec** [comment] 2021-05-31 10:04
It seems to be the usage of `-Ctarget-feature=-crt-static` together with [this](https://github.com/rust-lang/rust/commit/fdb899ba4bd5dffab4eec9ea575991ec5499a527) change that causes the breakage.

Unfortunately, it would be some work to get the Nix-setup going with LLVM 12 (we are tracking the 20.09 release which does not have it).

And no callstack sadly.

**Comment by abbec** [comment] 2021-05-31 10:23
Or actually, it seems to be more the use of the non-internal linker (which is required for `-Ctarget-feature=crt-static`) that breaks it

**Comment by abbec** [comment] 2021-05-31 12:29
Yeah, it does work with LLVM 12 but not with LLVM 11.1.

# REPRO CASE:

```rust
use std::fs;

fn repro() {
    let s = fs::read("/absolute/path.txt").unwrap();
    println!("{:#?}", s);
}

fn main() {
    repro();
}
```

## Run this

```sh
$ rustup install nightly
$ rustup target add wasm32-wasi
$ export CARGO_TARGET_WASM32_WASI_LINKER=/path/to/llvm-11/bin/clang
$ export RUSTFLAGS=`-Clinker-flavor=gcc`
$ cargo build --target wasm32-wasi
$ echo "YES" > path.txt
$ wasmtime run --mapdir=absolute::. target/wasm32-wasi/debug/rust-repro.wasm
```

## Result
```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to find a pre-opened file descriptor through which \"/absolute/path.txt\" could be opened" }', src/main.rs:4:44
```

The same thing works fine with

```sh
$ rustup toolchain install nightly-2021-03-10
$ rustup target add wasm32-wasi
$ rustup default nightly-2021-03-10
```

**Comment by abbec** [comment] 2021-05-31 12:34
With latest nightly and LLD 12 I instead get: "note: wasm-ld: error: unknown argument: --as-needed"

**Comment by apiraino** [comment] 2021-06-02 09:14
great work @abbec for creating a reproducible example. 

pinging ICE breakers to try to identify where this started (need to be triaged with both LLVM installed), so also adding LLVM label

@rustbot ping icebreakers-cleanup-crew
@rustbot label A-llvm

**Comment by pietroalbini** [comment] 2021-06-14 14:42
This seems to have been introduced in 1.52.0 nightly given the affected version. Relabeling as a stable-to-stable regression.

**Comment by joshtriplett** [comment] 2021-06-23 18:19
cc @alexcrichton

**Comment by alexcrichton** [comment] 2021-06-23 18:53
@abbec could you describe a bit why you're linking with a non-Rust LLD, and specifically an older-than-LLVM-12 LLD?

Given your [range of nightlies for the regression](https://github.com/rust-lang/rust/compare/3a5d45f68...f98721f88) this seems most likely due to https://github.com/rust-lang/rust/pull/82924 which I could imagine relies on features and/or bug fixes in LLVM 12 to work.

In general the wasm targets right now are intended to work best with the LLD that Rust ships itself, and otherwise if you're looking to interop with C/C++ code it's recommended to say pretty up-to-date because there's still a good deal of feature development and bug fixes happening.

**Comment by abbec** [comment] 2021-06-23 20:17
Yeah to be fair, this issue popped up in passing and I am now using LLVM 12 which works fine.

Reason for using an external linker is a custom libc and other C libraries.

**Comment by alexcrichton** [comment] 2021-06-23 21:35
Ah ok, if that's the case I'd recommend closing this because the wasm target and toolchain are undergoing enough changes that not a lot of effort is put into making all versions of objects work with past and future toolchains. This will naturally evolve over time as wasm stabilizes, but at this time I think the guarantee of Rust is that if you want to intermix Rust & C on wasm you need to have matching LLVM versions.

**Comment by apiraino** [comment] 2021-06-24 07:36
ok, closing this as per Alex's suggestion. @abbec please feel free to action this issue again in case something relevant happens again. Thanks again for your time on this issue!

**Closed by apiraino** 2021-06-24 07:36 UTC
Labels: A-LLVM, C-bug, ICEBreaker-Cleanup-Crew, O-wasm, P-medium, T-libs, regression-from-stable-to-stable
