### ISSUE TITLE
Compiler must show real line in failed test

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#29253] opened 2015-10-23 15:57 UTC
Currently if some test fails then compiler shows error with relative position `<anon>:21:5`. This is very uncomfortable

**Comment by apasel422** [comment] 2015-10-23 16:25
Could you provide some more information or some example code / steps to reproduce this?

**Comment by KalitaAlexey** [comment] 2015-10-23 16:28
Any test, any syntax error or assert shows positition relative to test begin

**Comment by apasel422** [comment] 2015-10-23 16:30
Are you talking about the tests that are run by `make check`, `#[test]` functions in user code run through e.g. `cargo test`, or something else?

**Comment by KalitaAlexey** [comment] 2015-10-23 16:33
I mean documentation test running through `cargo test`

**Comment by apasel422** [comment] 2015-10-23 16:44
OK, so to elaborate, the issue here is that doc test failures don't include the name of the file that contains the doc test. This is a result of how rustdoc works, which is by passing the source code of the test, as extracted from the comment in the file, to rustc via stdin. We can probably add an unstable command-line argument to rustc that allows a file name to be specified in such scenarios and amend rustdoc to use it.

**Comment by KalitaAlexey** [comment] 2015-10-23 16:48
Do something, please.

**Comment by apasel422** [comment] 2015-10-23 17:01
I'm investigating implementing this now.

**Comment by apasel422** [comment] 2015-10-23 17:05
This doesn't actually need a command-line option added to rustc, as rustdoc calls `driver::compile_input` directly, making this change simpler.

**Comment by steveklabnik** [comment] 2015-10-26 13:08
> Do something, please.

Please try to recognize that this is an open source project, and many people are working in their spare time. Specifically, as far as I know, @apasel422 is not paid to work on Rust. While we want Rust to be great for everyone, the reality is that there are thousands of open bugs, and so some of them will take time to address.

**Comment by KalitaAlexey** [comment] 2015-10-26 13:16
@steveklabnik Do you want me to do that? Could you aim me to this? Should I examine cargo sources?

**Comment by apasel422** [comment] 2015-10-26 13:21
@KalitaAlexey If you're interested in implementing this yourself (I don't know when I'll be able to complete it), the general idea would be augmenting [`rustc::session::config::Input::String`](https://github.com/rust-lang/rust/blob/master/src/librustc/session/config.rs#L131) with an `Option<PathBuf>` or perhaps `Option<String>` that carries a "secondary" filename that will be used in [rustdoc](https://github.com/rust-lang/rust/blob/master/src/librustdoc/test.rs#L172).

**Comment by mitaa** [comment] 2016-02-19 20:34
Thanks @apasel422, I've implemented the filename part [here][0], but it turns out that solving the issue with line numbers being relative to the start of the codeblock instead of to the start of the file is kind of infeasible to solve (which is AIUI the main request from @KalitaAlexey).

The current `<anon>` is I think preferable to showing the correct filename with wrong line numbers.

[0]: https://github.com/mitaa/rust/commit/01f924d44bac9c21f81eb25f92de2f7bc46dd895

**Comment by GuillaumeGomez** [comment] 2017-05-23 19:01
I think we can close it? Just reopen it if you feel something is missing.

**Closed by GuillaumeGomez** 2017-05-23 19:01 UTC
Labels: A-rustdoc, T-dev-tools
