### ISSUE TITLE
winapi broken in recent nightly

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#65709] opened 2019-10-22 21:55 UTC
```
error: attempt to shift left with overflow
   --> src\macros.rs:350:29
    |
350 |                   let mask = ((1 << ($r.end - $r.start)) - 1) << $r.start;
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
    | 
   ::: src\shared\d3dukmdt.rs:257:1
    |
257 | / BITFIELD!{D3DDDICB_LOCK2FLAGS Value: UINT [
258 | |     Reserved set_Reserved[0..32],
259 | | ]}
    | |__- in this macro invocation
    |
    = note: `#[deny(const_err)]` on by default
```

Using `rustc 1.40.0-nightly (7979016af 2019-10-20)`

**Comment by jonas-schievink** [comment] 2019-10-22 22:05
cc @oli-obk

**Comment by Centril** [comment] 2019-10-22 22:05
and cc @wesleywiser

**Comment by wesleywiser** [comment] 2019-10-23 00:35
I assume in this context `UINT` is a 32-bit unsigned integer? If so, the lint appears to be triggering correctly. This has likely started triggering because of some recent improvements to the `ConstProp` pass. 

I believe this behavior is covered under [RFC 1129](https://github.com/rust-lang/rfcs/blob/master/text/1229-compile-time-asserts.md) so this is expected behavior.

If you want to continue using this code as is, you can either add `#![warn(const_err)]` or `#![allow(const_err)]` to the appropriate module. 

This won't break crates dependent on winapi since cargo passes `--cap-lints allow` to rustc when compiling dependencies.

**Comment by oli-obk** [comment] 2019-10-23 12:48
It may also have started getting reported due to https://github.com/rust-lang/rust/pull/65320 which makes sure that we report `const_err` even if the code causing the lint to trigger is part of a macro from another crate.

Closing as wontfix because this is the expected behaviour and is easily silenced by an `allow` attribute.

**Closed by oli-obk** 2019-10-23 12:48 UTC
Labels: A-const-eval, C-bug, I-nominated, T-compiler, regression-from-stable-to-nightly
