### ISSUE TITLE
panic!("{}") doesn't error out on compilation

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust#30026] opened 2015-11-24 13:31 UTC
Playground: http://is.gd/jaT7YG

IMO the behavior should be consistent with `println!`.

**Comment by tsion** [comment] 2015-11-24 13:35
This happens since [`panic!`](http://doc.rust-lang.org/stable/std/macro.panic!.html) special cases the one-argument case to not go through `format_args!`. It would be nice to have the message checked in this case anyway to make sure it doesn't have any un-escaped `{}`s, but it's not clear to me how we should do that.

**Comment by jonas-schievink** [comment] 2015-11-24 15:25
Duplicate of #22932

**Closed** 2015-11-24 15:31 UTC
