### ISSUE TITLE
False negatives for some unused features

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#39996] opened 2017-02-21 10:08 UTC
The two following feature attributes won't warn if there are no plugins no old-style custom derive plugins:

```rust
#![feature(custom_derive)]
#![feature(plugin)]
```

**Comment by keeperofdakeys** [comment] 2017-02-26 10:11
cc @jseyfried Is this an issue?

**Comment by sanmai-NL** [comment] 2017-05-23 13:37
Duplicate of #23528, @Mark-Simulacrum?

**Comment by Mark-Simulacrum** [comment] 2017-05-23 13:58
Yeah, I'd say so. Thanks!

**Closed by Mark-Simulacrum** 2017-05-23 13:58 UTC
