### ISSUE TITLE
Conflicts with traits with parameters

### ISSUE THREAD

**Issue by pijul** [rust-lang/rust#36447] opened 2016-09-13 09:00 UTC
The following code doesn't compile:

``` rust
trait A<B> {
    fn a(&self);
}

trait C<D> {
    fn c(&self);
}

impl <B, X:A<B>> C<B> for X {
    fn c(&self) {
        self.a()
    }
}

struct X<Y> {
    a:Y
}

impl<Y> C<Y> for X<Y> {
    fn c(&self) {
        println!("c !");
    }
}

fn main() {
    let x = X { a:25 };
    x.c()
}
```

But this one does:

``` rust
trait A {
    fn a(&self);
}

trait C {
    fn c(&self);
}

impl <X:A> C for X {
    fn c(&self) {
        self.a()
    }
}

struct X<Y> {
    a:Y
}

impl<Y> C for X<Y> {
    fn c(&self) {
        println!("c !");
    }
}

fn main() {
    let x = X { a:25 };
    x.c()
}
```

The only difference is, the second one uses plain traits, whereas the first one uses parameterized traits. I believe both should compile (or at least both should fail, but lots of code in `std` use the second form).

**Comment by mark-i-m** [comment] 2016-09-14 04:39
Hmm... If I understand correctly, the problem seems to be that the compiler incorrectly thinks that `struct X` implements `trait A` and therefore implements `C<B>` (the first impl of `trait C`). In reality, `X` does not impl `A`, so the generic impl of `C` should exclude struct `X`, and the `impl<Y> C<Y> for X<Y>` should succeed.

**Comment by pijul** [comment] 2016-09-14 07:19
Yes, apparently.

**Comment by apasel422** [comment] 2016-09-28 16:49
Appears to be a duplicate of #28881.

**Closed** 2016-09-29 21:41 UTC
Labels: A-traits
