### ISSUE TITLE
Unclear cause for a `type annotations needed` error

### ISSUE THREAD

**Issue by Alexendoo** [rust-lang/rust#114997] opened 2023-08-19 15:02 UTC
### Code

```Rust
fn f(s: &str, v: &[String]) {
    if let Ok(idx) = s.parse() {
        if let Some(val) = v.get(idx) {
            let val: String = val.clone();
        }
    }
}
```

### Current output

```Shell
error[E0282]: type annotations needed
 --> src/lib.rs:4:35
  |
4 |             let val: String = val.clone();
  |                                   ^^^^^ cannot infer type
```

### Rationale and extra context

The reason is clear when the line is commented out

```rust
fn f(s: &str, v: &[String]) {
    if let Ok(idx) = s.parse() {
        if let Some(val) = v.get(idx) {
            // let val: String = val.clone();
        }
    }
}
```
```
error[E0282]: type annotations needed
 --> src/lib.rs:2:24
  |
2 |     if let Ok(idx) = s.parse() {
  |                        ^^^^^ cannot infer type of the type parameter `F` declared on the method `parse`
  |
help: consider specifying the generic argument
  |
2 |     if let Ok(idx) = s.parse::<F>() {
  |                             +++++
```

### Anything else?

Adapted from [this reddit post](https://www.reddit.com/r/rust/comments/15uphv8/compiler_cannot_infer_type/)

**Comment by fmease** [comment] 2023-08-19 17:24
Duplicate of #105718.

**Closed** 2023-08-19 17:59 UTC
Labels: A-diagnostics, T-compiler
