### ISSUE TITLE
Support all formatting flags in `std::path::Display`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#44048] opened 2017-08-22 21:55 UTC
This regression was initially noted in https://github.com/rust-lang/rust/issues/43765 which was caused in https://github.com/rust-lang/rust/pull/42613 where this struct in the standard library no longer respects all formatting flags. This is a tracking issue for supporting all formatting flags all the time, not just when it's conveniently already a `&str`.

**Comment by bstrie** [comment] 2021-07-03 19:25
I'd like to make a test case here but I'm unclear on what the issue is. The PR that closed this added tests for the width/fill/alignment formatting flags, and I can't think of what other flags would apply to Path. I'm also not sure what "it" means in the sentence "not just when it's conveniently already a &str".

**Comment by m-ou-se** [comment] 2021-07-28 18:39
Relabeling this as a feature request rather than a regression, considering four years have passed without any comments here requesting for it.

@alexcrichton Can you clarify which flags you are talking about here? See the above comment.

**Comment by alexcrichton** [comment] 2021-07-28 20:01
Not that I remember 2017 off the top of my head, but rereading here I believe that the issue is that `Path`s which are valid utf-8 follow formatting flags correctly, but paths which are not valid utf-8 may not. I suspect at the time I was sure that invalid utf-8 paths did not follow formatting flags, but I'm not sure if that's the case still.

**Closed** 2023-11-30 18:48 UTC
Labels: P-low, T-libs-api, E-help-wanted, C-feature-request, A-fmt, Libs-Tracked
