### ISSUE TITLE
Internal Compiler Error when using mutable references to mutably index an `HashMap`

### ISSUE THREAD

**Issue by Arignir** [rust-lang/rust#51736] opened 2018-06-23 14:32 UTC
Hi,

I came across an `internal compiler error: re-trying op failed` this morning, so i'm putting this here.

I have no idea how or why this error is popping, as i'm no compiler-developer, but maybe one of you knows why and can fix it?

Here is a minimal code to reproduce the error: [link](https://play.rust-lang.org/?gist=98b142b91ee5928007f6796463eba58e&version=stable&mode=debug)

Cordially,

**Comment by ljedrz** [comment] 2018-06-23 15:18
Looks like a duplicate of [#44405](https://github.com/rust-lang/rust/issues/44405).

**Comment by pietroalbini** [comment] 2018-06-23 17:15
Closing as a duplicate.

**Closed by pietroalbini** 2018-06-23 17:15 UTC
