### ISSUE TITLE
LLVM ICE with #[no_core] toy

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#58459] opened 2019-02-14 08:42 UTC
Found this while experimenting with `#[no_core]`.

```rust
#![feature(no_core, lang_items, optin_builtin_traits)]
#![forbid(unsafe_code)]
#![no_core]

#[lang = "sized"]
pub trait Sized {}

#[lang = "copy"]
pub trait Copy {}

#[lang = "freeze"]
pub auto trait Freeze {}

#[lang = "start"]
fn start(main: fn(), argc: isize, _argv: *const *const u8) -> isize {
    main();
    argc
}

mod marker {
    pub use super::Copy;
}

#[no_mangle]
pub extern "C" fn rust_eh_personality() {}

#[no_mangle]
pub extern "C" fn __libc_csu_fini() {}

#[no_mangle]
pub extern "C" fn __libc_csu_init() {}

#[no_mangle]
pub extern "C" fn __libc_start_main() {
    start(main, 0, 0 as *const *const u8);
}

fn main() {}
```

```
Standard Error

   Compiling playground v0.0.1 (/playground)
rustc: /checkout/src/llvm-project/llvm/include/llvm/Support/Casting.h:255: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::Function, Y = llvm::Value]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
error: Could not compile `playground`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name playground src/main.rs [..snip..] (signal: 6, SIGABRT: process abort signal)
```

**Comment by jonas-schievink** [comment] 2019-02-14 10:42
Probably a duplicate of https://github.com/rust-lang/rust/issues/9307

**Comment by Mark-Simulacrum** [comment] 2019-06-24 15:38
Closing -- this is indeed most likely a duplicate of #9307.

**Closed by Mark-Simulacrum** 2019-06-24 15:38 UTC
Labels: A-LLVM
