### ISSUE TITLE
Link error regression on nightly

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#36155] opened 2016-08-31 01:59 UTC
When running `cargo test` inside the `futures-cpupool` folder of https://github.com/alexcrichton/futures-rs/commit/093a63825e3a2b0f93186afdf0e9ac47f0df2cfa, I get an error looking like:

```
$ cargo +nightly test
   Compiling crossbeam v0.2.10
   Compiling libc v0.2.15
   Compiling log v0.3.6
   Compiling futures v0.1.0 (file:///home/alex/code/futures)
   Compiling num_cpus v1.0.0
   Compiling futures-cpupool v0.1.0 (file:///home/alex/code/futures/futures-cpupool)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc.0.o" "-o" "/home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/alex/code/futures/futures-cpupool/target/debug/deps" "-L" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-411f48d3.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libfutures_cpupool.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libnum_cpus-f32c6a9cbd8fad0a.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libcrossbeam-2f53cae32cd2c9f1.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/libfutures.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/liblog-bf16bb9a4912b11d.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-411f48d3.rlib" "/home/alex/code/futures/futures-cpupool/target/debug/deps/liblibc-1bd8847afb79f283.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-411f48d3.rlib" "/home/alex/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-411f48d3.rlib" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-l" "compiler-rt"
  = note: /home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc.0.o: In function `futures_cpupool::{{impl}}::spawn<futures::lazy::Lazy<closure, core::result::Result<(), ()>>>':
/home/alex/code/futures/futures-cpupool/src/lib.rs:165: undefined reference to `_$LT$futures..task..Spawn$LT$Box$LT$futures..Future$LT$Error$u3d$$LP$$RP$$C$$u20$Item$u3d$$LP$$RP$$GT$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$::execute::he6071928c27d1a12'
/home/alex/code/futures/futures-cpupool/target/debug/smoke-d9fe7840395d70dc.0.o: In function `futures_cpupool::{{impl}}::spawn<Box<Future>>':
/home/alex/code/futures/futures-cpupool/src/lib.rs:165: undefined reference to `_$LT$futures..task..Spawn$LT$Box$LT$futures..Future$LT$Error$u3d$$LP$$RP$$C$$u20$Item$u3d$$LP$$RP$$GT$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$::execute::he6071928c27d1a12'
collect2: error: ld returned 1 exit status
$ rustc +nightly -vV
rustc 1.13.0-nightly (77d2cd28f 2016-08-29)
binary: rustc
commit-hash: 77d2cd28fd715d2b9751de82b14d28ce6e376728
commit-date: 2016-08-29
host: x86_64-unknown-linux-gnu
release: 1.13.0-nightly
```

I haven't had a chance to minimize this yet unfortunately, but I figure that a bug report is better than no bug report.

**Comment by nikomatsakis** [comment] 2016-09-01 20:04
cc @michaelwoerister -- could this be related to collector changes?

**Comment by nikomatsakis** [comment] 2016-09-01 20:06
triage: P-high -- this is a regression.

Going to assign to @michaelwoerister for now on the suspicion that it is related to the collector.

**Comment by michaelwoerister** [comment] 2016-09-01 20:53
This might have to do with the switch to MIR trans since on-demand monomorphization for functions went away with that. That might have exposed a preexisting hole in the collector.

**Comment by TimNN** [comment] 2016-09-07 07:45
`nightly-2016-08-22` is still fine, `nightly-2016-08-23` fails [changes](https://github.com/rust-lang/rust/compare/1576de0ce...3c5a0fa45).

**Comment by michaelwoerister** [comment] 2016-09-12 17:27
@TimNN Thanks for looking into this!

**Comment by michaelwoerister** [comment] 2016-09-12 17:31
The problem seems to be that the symbol is not exported from the upstream crate anymore. Making the `impl` generic, as @alexcrichton did, will give the compiler the chance to instantiate a new copy of the method in the current crate and thus side-steps the problem.

**Comment by michaelwoerister** [comment] 2016-09-12 18:21
Oh, yuck, the symbol is still exported, but the upstream and the downstream crate don't compute the same name b/c impl names are indeterministic, it seems:
```
_$LT$futures..task..Spawn$LT$Box$LT$futures..Future$LT$Item$u3d$$LP$$RP$$C$$u20$Error$u3d$$LP$$RP$$GT$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$::execute::he2c53ed21be0e6cc
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_$LT$futures..task..Spawn$LT$Box$LT$futures..Future$LT$Error$u3d$$LP$$RP$$C$$u20$Item$u3d$$LP$$RP$$GT$$u20$$u2b$$u20$Send$u20$$u2b$$u20$$u27$static$GT$$GT$$GT$::execute::he2c53ed21be0e6cc
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by eddyb** [comment] 2016-09-12 19:56
@michaelwoerister May be a good idea to [never take this branch](https://github.com/rust-lang/rust/blob/888970370a3f4b9e8be399869581422c67638d7b/src/librustc/ty/item_path.rs#L237) if the buffer is in absolute mode.

**Comment by michaelwoerister** [comment] 2016-09-12 20:31
@eddyb Maybe. Though in the long run, we should just not use `item_path` for anything in symbol names, I guess.

**Comment by vinipsmaker** [comment] 2016-09-12 22:43
> `nightly-2016-08-22` is still fine, `nightly-2016-08-23` fails; changes.

`rustup` is failing to download `nightly-2016-08-23` in my machine, but I've tried `2016-08-24` and it fails.

Yes, mine is a different project and fails because:

```
crust.cgu-0.rs:(.text._ZN4drop17h3e1234ed18e9763aE+0xd): undefined reference to `_$LT$alloc..rc..Weak$LT$T$GT$$u20$as$u20$core..ops..Drop$GT$::drop::heb9833ada23bd943'
/home/ubuntu/Projetos/crust/target/debug/deps/crust-c77ec8e2f8c19198.0.o: In function `drop::hd8b7fe7b4a4d2a8d':
crust.cgu-0.rs:(.text._ZN4drop17hd8b7fe7b4a4d2a8dE+0xd): undefined reference to `_$LT$alloc..rc..Weak$LT$T$GT$$u20$as$u20$core..ops..Drop$GT$::drop::hc1ce591e95fae7c5'
collect2: error: ld returned 1 exit status
```

The full log for a different build which failed for the same reason is available online: https://travis-ci.org/maidsafe/crust/jobs/159284568#L294

Is there anything I can do to help chase this error?

**Comment by michaelwoerister** [comment] 2016-09-12 23:06
@vinipsmaker That looks more like https://github.com/rust-lang/rust/issues/36260, which I'm going to look into next.

**Closed** 2016-09-15 16:58 UTC
Labels: A-linkage, P-high, regression-from-stable-to-nightly, T-compiler

**Comment by vinipsmaker** [comment] 2016-09-19 07:45
Just tested with `rustc 1.13.0-nightly (32571c05c 2016-09-17)` and it worked where previously failed.
