### ISSUE TITLE
Multi dimensional array of Option<Structs> cause expontial increase in release compile times, up to a limit

### ISSUE THREAD

**Issue by NoSuchThingAsRandom** [rust-lang/rust#80622] opened 2021-01-02 15:50 UTC
Using cargo build --release with a 3 dimensional array, causes exponential build times, up to a limit. 

This occurs both on stable and nightly, and only gets worse with larger structs.
However this does not occur on unoptimized builds.

Some example release compile times:
**Stable:**
24 - ~1.95 secs
32 - ~4.73 secs
40 - ~10.86 secs
50 - ~24.38 secs
74 - ~1m 56 secs
75 - ~0.33 secs

**Nightly**:
    50 - ~26.75 secs
    75 - ~0.55 secs
I tried this code:

```rust
// Changing this value, adjusts the compile time significantly
const ARRAY_SIZE: u16 = 32;

#[derive(Copy, Clone)]
struct SomeStruct {
    some_data: u16,
}

pub fn main() {
    let data: [[[Option<SomeStruct>; 3]; ARRAY_SIZE as usize]; ARRAY_SIZE as usize] = [[[None; 3]; ARRAY_SIZE as usize]; ARRAY_SIZE as usize];
    // To make sure the array is actually built
    let mut count = 0;
    for _ in 0..10 {
        let pos = (rand::random::<f64>() * (ARRAY_SIZE as f64)) as usize;
        if data[pos][pos][0].is_some() {
            count += 1;
        }
    }
    println!("{}", count);
}
```

Why does this occur, and is there a way of turning off the "optimisation" in release mode, as I have a larger project, and this causes a much bigger impact.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

**Comment by jyn514** [comment] 2021-01-02 17:07
```
$ rg -w '75' compiler/
compiler/rustc_codegen_llvm/src/back/write.rs
1041:            llvm::LLVMPassManagerBuilderUseInlinerWithThreshold(builder, 75);
```
This looks very suspicious.

**Comment by VBGS** [comment] 2021-03-01 02:01
Here is another simple snippet of code involving multi-dimensional arrays which is quite slow to compile just in case it may help solve the issue if this is related.

```rust
#[derive(Clone, Copy)]
enum Bool {
        True,
        False
}

fn main() {
        const TEST: [[[Bool; 256]; 256]; 256] = [[[Bool::True; 256]; 256]; 256];
}
```

It is slow only when TEST is declared as a constant.

`time rustc test.rs`
```sh
real    0m41.278s
user    0m41.222s
sys     0m0.068s
```

# Meta
`rustc --version --verbose`
```sh
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

**Comment by Mark-Simulacrum** [comment] 2024-01-16 00:20
Seems likely to be a duplicate of https://github.com/rust-lang/rust/issues/88580.

**Closed by Mark-Simulacrum** 2024-01-16 00:20 UTC
Labels: A-LLVM, I-compiletime, T-compiler, C-bug
