### ISSUE TITLE
Regression in #[derive(Eq)] on type with non-Eq members.

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/rust#36830] opened 2016-09-29 15:02 UTC
Playground: https://play.rust-lang.org/?gist=ca6a481e640668153d66259c0ef1dde6&version=stable&backtrace=0

```rust
#[derive(Eq)]
pub struct Signature([u8; 65]);

impl PartialEq for Signature {
    fn eq(&self, other: &Self) -> bool {
        &self.0[..] == &other.0[..]
    }
}

fn main() { }
```

Succeeds on `rustc 1.11.0 (9b21dcd6a 2016-08-15)`, but fails on `rustc 1.13.0-beta.1 (cbbeba430 2016-09-28)`

Seems to be related to `std::cmp::AssertParamIsEq`.

**Comment by bluss** [comment] 2016-09-29 15:13
Caused by #36043

**Comment by bluss** [comment] 2016-09-29 15:15
Explanation: previous ".assert_param_is_eq" used method resolution, finding slice methods on arrays. New code only looks at the type itself (the array).

cc @petrochenkov

**Comment by petrochenkov** [comment] 2016-09-29 15:20
Theoretically, this is a bugfix, because the previous implementation didn't enforced the bounds properly.
However, I'm [not sure](https://github.com/rust-lang/rust/issues/13101#issuecomment-246124564) if these restrictions on deriving `Eq` are necessary at all.

**Comment by bluss** [comment] 2016-09-29 15:24
Without this road block, there would be many more Eq implementations on structs with floats in them.

**Comment by durka** [comment] 2016-09-29 15:38
Should maybe crater #36384 to see the "bugfix" impact.

**Comment by alexcrichton** [comment] 2016-10-03 23:41
Discussed during libs triage, conclusion was that we're likely to let this slide (as it's a bug fix) but we'll wait for the next crater build to ensure that no massive impact is seen.

**Comment by alexcrichton** [comment] 2016-10-07 07:09
Ok, ran crater, there are two regressions related to this

* [xor_name-0.1.0](https://crates.io/crates/xor_name) ([before](https://tools.taskcluster.net/task-inspector/#P05zmeLnSLiGAbVg1BOgcw)) ([after](https://tools.taskcluster.net/task-inspector/#p53HolY1QNmHuxWRZ0h8Rw))
* [ethcore-bigint-0.1.0](https://crates.io/crates/ethcore-bigint) ([before](https://tools.taskcluster.net/task-inspector/#e7bGXD7gQIGcA-VHTyzzmw)) ([after](https://tools.taskcluster.net/task-inspector/#94G_WZE1TjKKDO4Xl_gYIw))

I believe the latter is yours, right @rphmeier? The former presumably hasn't been reported yet.

**Comment by alexcrichton** [comment] 2016-10-07 07:09
adding back the nominated tag to discuss again.

**Comment by rphmeier** [comment] 2016-10-07 10:05
@alexcrichton right, I haven't published the fix to crates.io yet though.

**Comment by alexcrichton** [comment] 2016-10-10 22:31
Ok, the libs team discussed this today and the conclusion was that we can just send PRs to fix these issues.

@rphmeier to clarify have you got this fixed locally? If you need any help I can send a PR!

**Comment by alexcrichton** [comment] 2016-10-10 22:33
@bluss holy cow thanks so much for [sending a PR](https://github.com/maidsafe-archive/xor_name/pull/24) to fix `xor_name`!

**Comment by rphmeier** [comment] 2016-10-10 23:17
@alexcrichton Yep, fixed in the repo, just haven't pushed the fix to crates.io yet. I'll try and do it tomorrow.

**Comment by alexcrichton** [comment] 2016-10-10 23:23
Ok, in that case I'm going to close this, thanks for the update though!

**Closed by alexcrichton** 2016-10-10 23:23 UTC
Labels: I-nominated, regression-from-stable-to-beta, T-libs
