### ISSUE TITLE
rustc hangs when RUST_BACKTRACE is on

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#38595] opened 2016-12-24 20:40 UTC
Rustc hangs for almost 20 seconds when trying to compile an empty file, but only when RUST_BACKTRACE is on.

```
$ touch /tmp/empty.rs

$ export RUST_BACKTRACE=0
$ time rustc /tmp/empty.rs
error: main function not found

error: aborting due to previous error


real    0m0.073s
user    0m0.057s
sys     0m0.010s


$ export RUST_BACKTRACE=1
$ time rustc /tmp/empty.rs
error: main function not found

error: aborting due to previous error


real    0m18.557s
user    0m18.497s
sys     0m0.057s

$ rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)
```

**Comment by retep998** [comment] 2016-12-24 23:12
Dupe of https://github.com/rust-lang/rust/issues/37477?

**Comment by sfackler** [comment] 2017-01-06 23:06
Closing as dup

**Closed** 2017-01-06 23:06 UTC
