### ISSUE TITLE
Rustdoc: the `Sized` bound on traits isn't shown

### ISSUE THREAD

**Issue by InnocentusLime** [rust-lang/rust#82581] opened 2021-02-27 09:55 UTC
`rustdoc` doesn't show that some traits require the type to be sized, which can get a bit misleading. 

For example, the docs for `std::default::Default` (https://doc.rust-lang.org/std/default/trait.Default.html) show

```rust
pub trait Default {
    pub fn default() -> Self;
}
```

While in reality it is actually

```rust
pub trait Default: Sized {
    /* Docs and stabilization attributes */
    fn default() -> Self;
}
```

When looking at a trait definition, `rust` assumes that the type the trait will be implemented for is `?Sized`, so dropping `Sized` is incorrect.

**Comment by jyn514** [comment] 2021-03-30 15:22
Duplicate of https://github.com/rust-lang/rust/issues/24183.

**Closed by jyn514** 2021-03-30 15:22 UTC
Labels: A-traits, C-bug, T-rustdoc
