### ISSUE TITLE
The struct parser does not like token trees, or maybe something weirder

### ISSUE THREAD

**Issue by sorear** [rust-lang/rust#29393] opened 2015-10-27 06:23 UTC
I'm writing an FFI binding with a number of structs that have a fixed part and a variable part.  I tried to factor it using a macro which takes the variable part as a sequence of token trees (to allow zero or more fields, possibly with `#[cfg]` modifiers), but I'm getting a strange parse error; golfed to:

```rust
macro_rules! bug1 {
    ($x:tt) => { struct _Bug2 { $x : i32, } }
}

bug1!(_abc);

fn main() {
}
```

(playpen: http://is.gd/i4195j)

If I change `:tt` to `:ident` the short example works, but that doesn't work for my real code which uses a repeated token tree.

Is this supposed to work with `:tt` ?

**Comment by huonw** [comment] 2015-10-27 06:36
Dupe of #5846. Thanks for filing!

**Closed by huonw** 2015-10-27 06:36 UTC
