### ISSUE TITLE
Rust 1.56.0+ no longer recognizes boundary checks as avoiding division overflow panic

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#99960] opened 2022-07-30 18:04 UTC
The following code (contrived for demonstration purposes) correctly checks for and avoids a division overflow condition (`i64::MIN` input coerced to `i64::MIN.abs()` output) but a regression in rustc 1.56.0 (still in latest nightly and latest 1.62.0 release) causes the optimizer to no longer skip the checked division and panic branch:

```rust
pub fn checked_div_i64(dividend: i64, divisor: i64) -> Option<i64> {
    if dividend > i64::min_value() && divisor != 0 {
        Some(dividend / divisor)
    } else {
        None
    }
}
```

[Godbolt link comparing 1.55.0 to 1.62.0](https://godbolt.org/z/x95rGbW4j)

@rustbot label +regression-from-stable-to-stable +A-codegen +A-llvm +I-heavy +I-slow +T-compiler

Edit:

It might be worth adding some regression tests for this because it's happened and then was fixed a few times before (e.g. introduced in 1.47.0 and fixed in 1.48.0).

**Comment by mqudsi** [comment] 2022-07-30 19:32
This bisects to something between 2021-08-21 and 2021-08-22 in the range of a0035916e01d8e644ccd44554c57f0874cef8c8c to d3e2578c31688619ddc0a10ddf8543bf4ebcba5b, which includes #87570 (the upgrade to llvm 13), which is the most likely culprit.

**Comment by workingjubilee** [comment] 2022-07-30 19:35
The only difference in our unoptimized LLVMIR is that we now emit noundef, which enables other optimizations. Typically we do not add regression tests to Rust's test suite based purely on LLVM optimizations, and this regression does seem to be due to that. Even if we wanted one here, there's so many valid code emissions and optimizations for division, I'm not seeing a simple path forward for a regression test here.

But we will be upgrading LLVM soon.

**Comment by mqudsi** [comment] 2022-07-30 19:45
Thanks for clarifying - I wasn't sure what was in-scope and what would purely be considered an upstream issue without any workarounds on our end. I should have checked `--emit=llvm-ir` and included that info in my original bug report - I've made a mental note to do that in the future.

I look forward to seeing if the migration to LLVM 15 will address this. In the meantime, I suppose this is what `core::hint::unreachable_unchecked()` was made for!

**Comment by nikic** [comment] 2022-07-30 19:54
Still fails to optimize on current LLVM: https://llvm.godbolt.org/z/n7x4e9TKP It does work if the first logical and is replaced with a bitwise and, so something is missing logical and handling.

**Comment by workingjubilee** [comment] 2022-07-30 19:55
It's a regression, so I see some value in tracking it on our issue tracker, I just don't see much value in a specific test for it because for the optimized forms of the LLVMIR, I thiiiink the only thing we could really do is check that bb6 is _not_ present: https://godbolt.org/z/M9brfTcj9

**Comment by nikic** [comment] 2022-08-02 14:53
Even this simple case doesn't get optimized: https://alive2.llvm.org/ce/z/jvVFVJ

**Comment by apiraino** [comment] 2022-08-09 09:37
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2399960.20Rust.201.2E56.2E0.2B.20no.20longer.20recognizes.20boundary.20checks.20as.E2.80.A6)).

@rustbot label -I-prioritize +P-low

**Comment by apiraino** [comment] 2023-04-03 14:39
thanks! Tentatively closing the issue. Please @mqudsi report back if you still experience the issue

**Closed by apiraino** 2023-04-03 14:39 UTC
Labels: A-LLVM, I-slow, A-codegen, E-needs-test, P-low, T-compiler, regression-from-stable-to-stable, C-bug, I-heavy
