### ISSUE TITLE
There is a bug with print!

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#38881] opened 2017-01-06 18:28 UTC
The prompt message (with out line feed) can not be output before input.
```
use std::io;
fn main(){
    print!("test\ntest");
	let mut input = String::new();
        io::stdin()
            .read_line(&mut input)
            .expect("Failed to read line");
	println!("{:?}",input);
}
```
[Screenshot](https://github.com/3442853561/homepage/blob/gh-pages/test.png)

**Comment by steveklabnik** [comment] 2017-01-06 18:30
I don't think this is a bug. `print!` doesn't flush `stdout` like `println!` does, so until you do so, it won't get printed. Its docs explain this: https://doc.rust-lang.org/stable/std/macro.print.html

**Comment by alexcrichton** [comment] 2017-01-06 18:34
Ah yes I believe this is a dupe of #38710, so closing in favor of that.

**Closed by alexcrichton** 2017-01-06 18:34 UTC

**Comment by 3442853561** [comment] 2017-01-06 18:36
@steveklabnik Thank you!

**Comment by steveklabnik** [comment] 2017-01-06 18:41
@alexcrichton did you mean a different issue? that one is about android...

**Comment by alexcrichton** [comment] 2017-01-06 18:43
Oops yes, https://github.com/rust-lang/rust/issues/23818 is the link I intended
