### ISSUE TITLE
No documentation for primitives in `core`

### ISSUE THREAD

**Issue by rossmacarthur** [rust-lang/rust#80334] opened 2020-12-23 16:25 UTC
There is no documentation for primitives in `core`, the only documentation exists in `std`. I don't think there is any reason for a user to assume that all associated functions and methods on primitive types that are available in `std` are also available in `core`.

Some confusing things:
- The primitives are not listed in the crate root. [See here](https://doc.rust-lang.org/core/index.html)
- The `core::primitive` module documentation primitives have no links. [See here](https://doc.rust-lang.org/core/primitive/index.html)
- The the primitive types modules such as `core::i32` link to the `std` documentation for primitives. [See here](https://doc.rust-lang.org/core/i32/index.html)

**Comment by jyn514** [comment] 2020-12-23 20:15
Duplicate of https://github.com/rust-lang/rust/issues/73423. See also https://github.com/rust-lang/rust/issues/62909.

**Closed by jyn514** 2020-12-23 20:15 UTC
Labels: A-rustdoc-ui, C-enhancement, T-doc, T-rustdoc
