### ISSUE TITLE
Spanning algorithm assumes all codepoints have width equal to 1

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#28899] opened 2015-10-07 22:38 UTC
```
/tmp/test.rs:2:23: 2:23 error: invalid unicode character escape
/tmp/test.rs:2     let a = "きききききき\u{}";
                                     ^
/tmp/test.rs:3:37: 3:37 error: invalid unicode character escape
/tmp/test.rs:3     let a = "ōōōōōōōōōō\u{}";
                                                   ^
error: aborting due to 2 previous errors
```

the first example has several codepoints that occupy space of more than one regular ASCII character and 2nd example has several codepoints that occupy no space (combining characters).

**Comment by huonw** [comment] 2015-10-07 22:47
This is essentially a dupe of https://github.com/rust-lang/rust/issues/8706. In particular, this issue (and that one) was fixed in https://github.com/rust-lang/rust/pull/21499, but https://github.com/rust-lang/rust/pull/24428 reverted it when moving the unicode functionality out.

**Closed** 2015-10-07 22:49 UTC
