### ISSUE TITLE
Bounds check not omitted

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#46863] opened 2017-12-20 01:50 UTC
```rust
pub fn f(l: &Vec<u64>) -> u64 {
  let mut sum = 0;
  for i in 0..l.len() {
    sum += l[i]
  }
  sum
}
```

Compiles with -C opt-level=3 -C panic=abort to:
```assembly
example::f:
        mov     rdx, qword ptr [rdi + 16]
        test    rdx, rdx
        je      .LBB0_1
        mov     rcx, qword ptr [rdi]
        xor     eax, eax
        xor     esi, esi
.LBB0_4:
        cmp     rdx, rsi
        jbe     .LBB0_5
        add     rax, qword ptr [rcx + 8*rsi]
        inc     rsi
        cmp     rsi, rdx
        jb      .LBB0_4
        jmp     .LBB0_2
.LBB0_1:
        xor     eax, eax
.LBB0_2:
        ret
.LBB0_5:
        push    rbp
        mov     rbp, rsp
        lea     rdi, [rip + panic_bounds_check_loc.1]
        call    core::panicking::panic_bounds_check@PLT
        ud2
```
It should be possible for the bounds check to be dropped.

**Comment by arielb1** [comment] 2017-12-21 13:09
This looks like a pass ordering issue - GVN is needed to simplify the doubly-nested load, while IndVarSimplify is needed to eliminate the bounds check.

**Comment by arielb1** [comment] 2017-12-21 13:32
Minimal example - I suppose the identical C code has the same problem.

Nothing but GVN can optimize loads across basic blocks, and nothing but indvars (I think) can fix up bounds checks.

Maybe there's another bounds check removal pass we can run later in the pipeline.

```Rust
#![crate_type="rlib"]
pub fn f(l: &usize) -> u64 {
  let mut sum = 0;
  let len_1 = *l;
  let mut i = 0;
  while i < len_1 {
    let len_2 = *l;
    assert!(i < len_2);
    i += 1;
  }
  sum
}
```

**Comment by AndrewGaspar** [comment] 2017-12-21 17:56
Assuming this is nightly, I believe I also ran into this regression. https://users.rust-lang.org/t/surprising-auto-vectorization-optimization-behavior/14537

**Comment by alexcrichton** [comment] 2018-02-10 19:15
I believe this was fixed by https://github.com/rust-lang/rust/pull/47828

**Closed by alexcrichton** 2018-02-10 19:15 UTC
Labels: A-LLVM
