### ISSUE TITLE
Missing links to src of implementors in docs of hir and ast visitors

### ISSUE THREAD

**Issue by b-naber** [rust-lang/rust#81190] opened 2021-01-19 17:31 UTC
In the docs for the compiler no links to the source code of the implementors of the [ast::Visitor](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/visit/trait.Visitor.html#implementors) and the [hir::Visitor](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/intravisit/trait.Visitor.html#implementors) are provided. @jyn514 said that this is likely a bug.

**Comment by jyn514** [comment] 2021-01-19 17:34
Related: https://github.com/rust-lang/rust/issues/76736

**Comment by camelid** [comment] 2021-01-20 22:34
I believe this is a duplicate of #78615.

**Comment by jyn514** [comment] 2021-01-21 00:23
Good catch, it is indeed a duplicate.

**Closed by jyn514** 2021-01-21 00:23 UTC
Labels: A-contributor-roadblock, T-rustdoc
