### ISSUE TITLE
`packed_simd_2` in `v0.3.8` not compiling with `rustc 1.72.0-nightly`

### ISSUE THREAD

**Issue by dlaehnemann** [rust-lang/rust#113530] opened 2023-07-10 09:34 UTC
The actual error is thrown when trying to compile a project via `cargo tarpaulin` to determine test coverage including `doctests`. The full CI run can be found here:
https://github.com/rust-bio/rust-bio/actions/runs/5506242163/jobs/10034670898?pr=542#step:4:167

As this output will be removed automatically at some point, the full tarpaulin run is shown below under `backtrace`.

### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (83964c156 2023-07-08) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: internal compiler error: /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/compiler/rustc_codegen_ssa/src/mir/constant.rs:70:22: Ty(
                                    Const { ty: [u32; 2], kind: IDX/#0 },
                                )
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:25:25
   |
25 |     simd_shuffle2(x, y, IDX)
   |                         ^^^
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Run actions-rs/tarpaulin@v0.1
  with:
    version: 0.22.0
    args: --workspace --all-features --run-types Tests,Doctests --out Lcov --timeout 300
    out-type: Xml
[tarpaulin] downloading cargo-tarpaulin from https://github.com/xd009642/tarpaulin/releases/download/0.22.0/cargo-tarpaulin-0.22.0-travis.tar.gz
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/46a32b86-7a7b-44cc-b94d-75902e2e6e57 -f /home/runner/work/_temp/a4551382-f5a4-4b28-89f7-c4d3b9a9d971
[tarpaulin] running tests with coverage tracking
/home/runner/.cargo/bin/cargo tarpaulin --out Xml --workspace --all-features --run-types Tests,Doctests --out Lcov --timeout 300
Jul 09 18:48:02.114  INFO cargo_tarpaulin::config: Creating config
Jul 09 18:48:04.136  INFO cargo_tarpaulin: Running Tarpaulin
Jul 09 18:48:04.136  INFO cargo_tarpaulin: Building project
Jul 09 18:48:04.136  INFO cargo_tarpaulin::cargo: Cleaning project
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.64
   Compiling quote v1.0.29
   Compiling unicode-ident v1.0.10
   Compiling libc v0.2.147
   Compiling libm v0.2.7
   Compiling syn v2.0.25
   Compiling num-traits v0.2.15
   Compiling cfg-if v1.0.0
   Compiling syn v1.0.109
   Compiling getrandom v0.2.10
   Compiling memchr v2.5.0
   Compiling rand_core v0.6.4
   Compiling thiserror v1.0.43
   Compiling version_check v0.9.4
   Compiling thiserror-impl v1.0.43
   Compiling num-integer v0.1.45
   Compiling ppv-lite86 v0.2.17
   Compiling serde v1.0.170
   Compiling rand_chacha v0.3.1
   Compiling serde_derive v1.0.170
   Compiling matrixmultiply v0.3.7
   Compiling rustversion v1.0.13
   Compiling io-lifetimes v1.0.11
   Compiling paste v1.0.13
   Compiling bytemuck v1.13.1
   Compiling safe_arch v0.7.0
   Compiling rand v0.8.5
   Compiling proc-macro-error-attr v1.0.4
   Compiling num-complex v0.4.3
   Compiling num-rational v0.4.1
   Compiling indexmap v1.9.3
   Compiling semver v0.1.20
   Compiling libm v0.1.4
   Compiling rustix v0.37.23
   Compiling rawpointer v0.2.1
   Compiling ucd-trie v0.1.6
   Compiling typenum v1.16.0
   Compiling pest v2.7.0
   Compiling rustc_version v0.1.7
   Compiling wide v0.7.10
   Compiling aho-corasick v1.0.2
   Compiling proc-macro-error v1.0.4
   Compiling approx v0.5.1
   Compiling tempfile v3.6.0
   Compiling packed_simd_2 v0.3.8
   Compiling lazy_static v1.4.0
   Compiling feature-probe v0.1.1
   Compiling bitflags v1.3.2
   Compiling linux-raw-sys v0.3.8
   Compiling regex-syntax v0.7.3
   Compiling hashbrown v0.12.3
   Compiling heck v0.4.1
   Compiling once_cell v1.18.0
   Compiling pest_meta v2.7.0
   Compiling regex-automata v0.3.2
   Compiling bv v0.11.1
   Compiling simba v0.6.0
   Compiling newtype_derive v0.1.6
   Compiling rand_distr v0.4.3
   Compiling nalgebra-macros v0.1.0
   Compiling bit-vec v0.6.3
   Compiling fixedbitset v0.4.2
   Compiling byteorder v1.4.3
   Compiling anyhow v1.0.71
   Compiling fastrand v1.9.0
   Compiling petgraph v0.6.3
   Compiling bit-set v0.5.3
   Compiling nalgebra v0.29.0
   Compiling regex v1.9.1
   Compiling pest_generator v2.7.0
   Compiling strum_macros v0.24.3
   Compiling derive-new v0.5.9
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/compiler/rustc_errors/src/lib.rs:995:33
stack backtrace:
   0:     0x7f122a4a8a71 - std::backtrace_rs::backtrace::libunwind::trace::h4e1458b4a9fb4e6f
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f122a4a8a71 - std::backtrace_rs::backtrace::trace_unsynchronized::hab78200fa9cb4924
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f122a4a8a71 - std::sys_common::backtrace::_print_fmt::hcfea8b2400713c36
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f122a4a8a71 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e59532c1e143911
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f122a50ed7f - core::fmt::rt::Argument::fmt::h9df7228410758d1a
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/core/src/fmt/rt.rs:138:9
   5:     0x7f122a50ed7f - core::fmt::write::h8469ff0e5aa7b2a8
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f122a49b4b7 - std::io::Write::write_fmt::hf942e53f0bebad10
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/io/mod.rs:1714:15
   7:     0x7f122a4a8885 - std::sys_common::backtrace::_print::hb60701aae549e88f
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f122a4a8885 - std::sys_common::backtrace::print::h5a926053ebf6acdd
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f122a4ab663 - std::panicking::default_hook::{{closure}}::h9cb2c77fd9d08a16
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/panicking.rs:269:22
  10:     0x7f122a4ab3f4 - std::panicking::default_hook::hc22d719f1e0a6564
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/panicking.rs:288:9
  11:     0x7f122d78cc6b - rustc_driver_impl[2d6a85f1efddecb1]::install_ice_hook::{closure#0}
  12:     0x7f122a4abe8e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h05534b3187a63b37
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/alloc/src/boxed.rs:2007:9
  13:     0x7f122a4abe8e - std::panicking::rust_panic_with_hook::h548300ff41a99ca1
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/panicking.rs:709:13
  14:     0x7f122d628441 - std[1ede75a6519e9681]::panicking::begin_panic::<rustc_errors[c0cefe3d099df7b4]::ExplicitBug>::{closure#0}
  15:     0x7f122d627fb6 - std[1ede75a6519e9681]::sys_common::backtrace::__rust_end_short_backtrace::<std[1ede75a6519e9681]::panicking::begin_panic<rustc_errors[c0cefe3d099df7b4]::ExplicitBug>::{closure#0}, !>
  16:     0x7f122d5eb986 - std[1ede75a6519e9681]::panicking::begin_panic::<rustc_errors[c0cefe3d099df7b4]::ExplicitBug>
  17:     0x7f122d607fd2 - <rustc_errors[c0cefe3d099df7b4]::HandlerInner>::span_bug::<rustc_span[2315e69a6c645816]::span_encoding::Span, alloc[b6f6cdd3965a641f]::string::String>
  18:     0x7f122d607df6 - <rustc_errors[c0cefe3d099df7b4]::Handler>::span_bug::<rustc_span[2315e69a6c645816]::span_encoding::Span, alloc[b6f6cdd3965a641f]::string::String>
  19:     0x7f122d61c2cd - rustc_middle[1f0c398aabd4ddf9]::util::bug::opt_span_bug_fmt::<rustc_span[2315e69a6c645816]::span_encoding::Span>::{closure#0}
  20:     0x7f122d61c2fa - rustc_middle[1f0c398aabd4ddf9]::ty::context::tls::with_opt::<rustc_middle[1f0c398aabd4ddf9]::util::bug::opt_span_bug_fmt<rustc_span[2315e69a6c645816]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  21:     0x7f122d61a97a - rustc_middle[1f0c398aabd4ddf9]::ty::context::tls::with_context_opt::<rustc_middle[1f0c398aabd4ddf9]::ty::context::tls::with_opt<rustc_middle[1f0c398aabd4ddf9]::util::bug::opt_span_bug_fmt<rustc_span[2315e69a6c645816]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  22:     0x7f122c07ae14 - rustc_middle[1f0c398aabd4ddf9]::util::bug::span_bug_fmt::<rustc_span[2315e69a6c645816]::span_encoding::Span>
  23:     0x7f122c0ddd3d - <rustc_codegen_ssa[8acbb851ca316c41]::mir::FunctionCx<rustc_codegen_llvm[213bd859a847529f]::builder::Builder>>::simd_shuffle_indices
  24:     0x7f122c0b16c3 - <core[29b2b76cf1b48b36]::iter::adapters::map::Map<core[29b2b76cf1b48b36]::iter::adapters::enumerate::Enumerate<core[29b2b76cf1b48b36]::slice::iter::Iter<rustc_middle[1f0c398aabd4ddf9]::mir::syntax::Operand>>, <rustc_codegen_ssa[8acbb851ca316c41]::mir::FunctionCx<rustc_codegen_llvm[213bd859a847529f]::builder::Builder>>::codegen_call_terminator::{closure#2}> as core[29b2b76cf1b48b36]::iter::traits::iterator::Iterator>::fold::<(), core[29b2b76cf1b48b36]::iter::traits::iterator::Iterator::for_each::call<rustc_codegen_ssa[8acbb851ca316c41]::mir::operand::OperandRef<&rustc_codegen_llvm[213bd859a847529f]::llvm_::ffi::Value>, <alloc[b6f6cdd3965a641f]::vec::Vec<rustc_codegen_ssa[8acbb851ca316c41]::mir::operand::OperandRef<&rustc_codegen_llvm[213bd859a847529f]::llvm_::ffi::Value>>>::extend_trusted<core[29b2b76cf1b48b36]::iter::adapters::map::Map<core[29b2b76cf1b48b36]::iter::adapters::enumerate::Enumerate<core[29b2b76cf1b48b36]::slice::iter::Iter<rustc_middle[1f0c398aabd4ddf9]::mir::syntax::Operand>>, <rustc_codegen_ssa[8acbb851ca316c41]::mir::FunctionCx<rustc_codegen_llvm[213bd859a847529f]::builder::Builder>>::codegen_call_terminator::{closure#2}>>::{closure#0}>::{closure#0}>
  25:     0x7f122c0b14c3 - <alloc[b6f6cdd3965a641f]::vec::Vec<rustc_codegen_ssa[8acbb851ca316c41]::mir::operand::OperandRef<&rustc_codegen_llvm[213bd859a847529f]::llvm_::ffi::Value>> as alloc[b6f6cdd3965a641f]::vec::spec_from_iter::SpecFromIter<rustc_codegen_ssa[8acbb851ca316c41]::mir::operand::OperandRef<&rustc_codegen_llvm[213bd859a847529f]::llvm_::ffi::Value>, core[29b2b76cf1b48b36]::iter::adapters::map::Map<core[29b2b76cf1b48b36]::iter::adapters::enumerate::Enumerate<core[29b2b76cf1b48b36]::slice::iter::Iter<rustc_middle[1f0c398aabd4ddf9]::mir::syntax::Operand>>, <rustc_codegen_ssa[8acbb851ca316c41]::mir::FunctionCx<rustc_codegen_llvm[213bd859a847529f]::builder::Builder>>::codegen_call_terminator::{closure#2}>>>::from_iter
  26:     0x7f122c066b50 - rustc_codegen_ssa[8acbb851ca316c41]::mir::codegen_mir::<rustc_codegen_llvm[213bd859a847529f]::builder::Builder>
  27:     0x7f122cd4436a - rustc_codegen_llvm[213bd859a847529f]::base::compile_codegen_unit::module_codegen
  28:     0x7f122cd43469 - rustc_codegen_llvm[213bd859a847529f]::base::compile_codegen_unit
  29:     0x7f122cda080f - rustc_codegen_ssa[8acbb851ca316c41]::base::codegen_crate::<rustc_codegen_llvm[213bd859a847529f]::LlvmCodegenBackend>
  30:     0x7f122cda0116 - <rustc_codegen_llvm[213bd859a847529f]::LlvmCodegenBackend as rustc_codegen_ssa[8acbb851ca316c41]::traits::backend::CodegenBackend>::codegen_crate
  31:     0x7f122c99d9a2 - <rustc_session[d2c5967be8e6b8f9]::session::Session>::time::<alloc[b6f6cdd3965a641f]::boxed::Box<dyn core[29b2b76cf1b48b36]::any::Any>, rustc_interface[b053cddf22540e47]::passes::start_codegen::{closure#0}>
  32:     0x7f122c99d4eb - rustc_interface[b053cddf22540e47]::passes::start_codegen
  33:     0x7f122c99719a - <rustc_middle[1f0c398aabd4ddf9]::ty::context::GlobalCtxt>::enter::<<rustc_interface[b053cddf22540e47]::queries::Queries>::ongoing_codegen::{closure#0}, core[29b2b76cf1b48b36]::result::Result<alloc[b6f6cdd3965a641f]::boxed::Box<dyn core[29b2b76cf1b48b36]::any::Any>, rustc_span[2315e69a6c645816]::ErrorGuaranteed>>
  34:     0x7f122c9961b3 - <rustc_interface[b053cddf22540e47]::interface::Compiler>::enter::<rustc_driver_impl[2d6a85f1efddecb1]::run_compiler::{closure#1}::{closure#2}, core[29b2b76cf1b48b36]::result::Result<core[29b2b76cf1b48b36]::option::Option<rustc_interface[b053cddf22540e47]::queries::Linker>, rustc_span[2315e69a6c645816]::ErrorGuaranteed>>
  35:     0x7f122c98f2a5 - rustc_span[2315e69a6c645816]::set_source_map::<core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>, rustc_interface[b053cddf22540e47]::interface::run_compiler<core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>, rustc_driver_impl[2d6a85f1efddecb1]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  36:     0x7f122c98ed16 - <scoped_tls[b9dcc93a263bd177]::ScopedKey<rustc_span[2315e69a6c645816]::SessionGlobals>>::set::<rustc_interface[b053cddf22540e47]::interface::run_compiler<core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>, rustc_driver_impl[2d6a85f1efddecb1]::run_compiler::{closure#1}>::{closure#0}, core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>>
  37:     0x7f122c98e2dc - std[1ede75a6519e9681]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b053cddf22540e47]::util::run_in_thread_pool_with_globals<rustc_interface[b053cddf22540e47]::interface::run_compiler<core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>, rustc_driver_impl[2d6a85f1efddecb1]::run_compiler::{closure#1}>::{closure#0}, core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>>
  38:     0x7f122c98e0a5 - <<std[1ede75a6519e9681]::thread::Builder>::spawn_unchecked_<rustc_interface[b053cddf22540e47]::util::run_in_thread_pool_with_globals<rustc_interface[b053cddf22540e47]::interface::run_compiler<core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>, rustc_driver_impl[2d6a85f1efddecb1]::run_compiler::{closure#1}>::{closure#0}, core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[29b2b76cf1b48b36]::result::Result<(), rustc_span[2315e69a6c645816]::ErrorGuaranteed>>::{closure#1} as core[29b2b76cf1b48b36]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7f122a4b6305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8fa82afee072a41e
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/alloc/src/boxed.rs:1993:9
  40:     0x7f122a4b6305 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h99bb2872d0c67e87
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/alloc/src/boxed.rs:1993:9
  41:     0x7f122a4b6305 - std::sys::unix::thread::Thread::new::thread_start::h51979755696e7814
                               at /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7f122a1fbb43 - <unknown>
  43:     0x7f122a28da00 - <unknown>
  44:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0-nightly (83964c156 2023-07-08) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C debuginfo=2 -C link-dead-code

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: Broken pipe (os error 32)
warning: build failed, waiting for other jobs to finish...
error: could not compile `packed_simd_2` (lib) due to previous error
Jul 09 18:48:58.918 ERROR cargo_tarpaulin: Failed to compile tests!
error: internal compiler error: /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/compiler/rustc_codegen_ssa/src/mir/constant.rs:70:22: Ty(
                                    Const { ty: [u32; 2], kind: IDX/#0 },
                                )
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:25:25
   |
25 |     simd_shuffle2(x, y, IDX)
   |                         ^^^


Error: "Failed to compile tests!\nerror: internal compiler error: /rustc/83964c156db1f444050a38b2498dbd0da6d5d503/compiler/rustc_codegen_ssa/src/mir/constant.rs:70:22: Ty(\n                                    Const { ty: [u32; 2], kind: IDX/#0 },\n                                )\n  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/codegen/llvm.rs:25:25\n   |\n25 |     simd_shuffle2(x, y, IDX)\n   |                         ^^^\n\n"
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1
```

</p>
</details>

**Comment by workingjubilee** [comment] 2023-07-10 10:34
Duplicate of https://github.com/rust-lang/rust/issues/113500

**Closed by workingjubilee** 2023-07-10 10:34 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage

**Comment by dlaehnemann** [comment] 2023-07-10 11:21
Sorry, I didn't see this when looking through existing issues. Thanks for pointing it out!
