### ISSUE TITLE
unstable fingerprints 

### ISSUE THREAD

**Issue by luoqiz** [rust-lang/rust#131047] opened 2024-09-30 03:06 UTC
error: internal compiler error: encountered incremental compilation error with evaluate_obligation(8861e14b9c39d943-e2a96f701c43f9e1)
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p wcf_client_rust_lib` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\compiler\rustc_query_system\src\query\plumbing.rs:734:9:    
Found unstable fingerprints for evaluate_obligation(8861e14b9c39d943-e2a96f701c43f9e1): Err(Canonical)
stack backtrace:
   0:     0x7ffe5114e551 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/7608018cbdac9e55d0[rustc-ice-2024-09-30T03_03_59-194312.txt](https://github.com/user-attachments/files/17183286/rustc-ice-2024-09-30T03_03_59-194312.txt)
d13529cf43adc33d53efcf\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffe5114e551 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffe5114e551 - std::sys::backtrace::_print_fmt
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\sys\backtrace.rs:66
   3:     0x7ffe5114e551 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\sys\backtrace.rs:39
   4:     0x7ffe51184d7a - core::fmt::rt::Argument::fmt
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/core\src\fmt\rt.rs:177
   5:     0x7ffe51184d7a - core::fmt::write
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/core\src\fmt\mod.rs:1186
   6:     0x7ffe51144807 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\io\mod.rs:1839
   7:     0x7ffe5114e395 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\sys\backtrace.rs:42
   8:     0x7ffe511512b7 - std::panicking::default_hook::closure$1
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\panicking.rs:268
   9:     0x7ffe5115106d - std::panicking::default_hook
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\panicking.rs:295
  10:     0x7ffe5276ff20 - memchr
  11:     0x7ffe511519f2 - alloc::boxed::impl$50::call
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/alloc\src\boxed.rs:2467
  12:     0x7ffe511519f2 - std::panicking::rust_panic_with_hook
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\panicking.rs:809
  13:     0x7ffe51151839 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\panicking.rs:674
  14:     0x7ffe5114f00f - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>  
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\sys\backtrace.rs:170
  15:     0x7ffe5115143e - std::panicking::begin_panic_handler
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\panicking.rs:665
  16:     0x7ffe540e5651 - core::panicking::panic_fmt
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/core\src\panicking.rs:74
  17:     0x7ffe5340e06b - <rustc_ty_utils[245fc586067fab61]::opaque_types::OpaqueTypeCollector as rustc_type_ir[3f649f1c6b346c68]::visit::TypeVisitor<rustc_middle[72f2e5bd51ed7e70]::ty::context::TyCtxt>>::visit_ty
  18:     0x7ffe51c7e604 - rustc_ty_utils[245fc586067fab61]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  19:     0x7ffe51c2d46a - rustc_ty_utils[245fc586067fab61]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  20:     0x7ffe51d458fe - rustc_query_impl[2c24b798d023d280]::plumbing::query_key_hash_verify_all
  21:     0x7ffe5204e9a9 - <rustc_infer[6a89d92c59942fa]::infer::InferCtxt as rustc_trait_selection[84f7a320e9326e6f]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation_no_overflow
  22:     0x7ffe52019862 - rustc_trait_selection[84f7a320e9326e6f]::traits::type_known_to_meet_bound_modulo_regions
  23:     0x7ffe51ba2d9c - rustc_ty_utils[245fc586067fab61]::common_traits::is_sized_raw
  24:     0x7ffe50d576fb - <dyn std[714d9606647da2df]::io::Write as nu_ansi_term[d3300defdc4f9328]::write::AnyWrite>::write_str        
  25:     0x7ffe51c3b2b5 - rustc_ty_utils[245fc586067fab61]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  26:     0x7ffe50d7455c - rustc_query_impl[2c24b798d023d280]::query_system
  27:     0x7ffe5260a70c - <rustc_middle[72f2e5bd51ed7e70]::query::on_disk_cache::CacheEncoder as rustc_span[8af91ef6878c4e5d]::SpanEncoder>::encode_def_id
  28:     0x7ffe52578237 - <rustc_middle[72f2e5bd51ed7e70]::ty::Ty>::is_unpin
  29:     0x7ffe51b858ce - rustc_privacy[aff96500120a1c4b]::check_private_in_public
  30:     0x7ffe51bc5437 - rustc_ty_utils[245fc586067fab61]::ty::asyncness
  31:     0x7ffe51b90ead - rustc_ty_utils[245fc586067fab61]::abi::fn_abi_of_instance
  32:     0x7ffe51d333cc - rustc_query_impl[2c24b798d023d280]::plumbing::query_key_hash_verify_all
  33:     0x7ffe50d3bb62 - <dyn std[714d9606647da2df]::io::Write as nu_ansi_term[d3300defdc4f9328]::write::AnyWrite>::write_str        
  34:     0x7ffe51c44e93 - rustc_ty_utils[245fc586067fab61]::ty::self_ty_of_trait_impl_enabling_order_dep_trait_object_hack
  35:     0x7ffe51d43001 - rustc_query_impl[2c24b798d023d280]::plumbing::query_key_hash_verify_all
  36:     0x7ffe5121b724 - rustc_interface[914a49c7ba921ee6]::proc_macro_decls::proc_macro_decls_static
  37:     0x7ffe5126adf1 - <rustc_codegen_llvm[11d42b48bb155dd3]::builder::Builder as rustc_codegen_ssa[66f3ef4e3423cad4]::traits::builder::BuilderMethods>::call
  38:     0x7ffe511fe63e - rustc_interface[914a49c7ba921ee6]::proc_macro_decls::proc_macro_decls_static
  39:     0x7ffe51267e7e - <rustc_target[4854e52e343c1e4d]::abi::call::FnAbi<rustc_middle[72f2e5bd51ed7e70]::ty::Ty> as rustc_codegen_llvm[11d42b48bb155dd3]::abi::FnAbiLlvmExt>::apply_attrs_callsite
  40:     0x7ffe4e257bd7 - llvm::DenseMap<llvm::StructType * __ptr64,llvm::detail::DenseSetEmpty,llvm::IRMover::StructTypeKeyInfo,llvm::detail::DenseSetPair<llvm::StructType * __ptr64> >::~DenseMap<llvm::StructType * __ptr64,llvm::detail::DenseSetEmpty,llvm::IRMover::StructTypeKeyIn
  41:     0x7ffe4e2b8ae7 - <rustc_codegen_llvm[11d42b48bb155dd3]::LlvmCodegenBackend as rustc_codegen_ssa[66f3ef4e3423cad4]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  42:     0x7ffe4e2bbd36 - <rustc_codegen_llvm[11d42b48bb155dd3]::LlvmCodegenBackend as rustc_codegen_ssa[66f3ef4e3423cad4]::traits::backend::CodegenBackend>::codegen_crate
  43:     0x7ffe4e213c2c - <rustc_interface[914a49c7ba921ee6]::queries::Linker>::codegen_and_build_linker
  44:     0x7ffe4e1c3167 - _rust_alloc_error_handler
  45:     0x7ffe4e1bebaf - _rust_alloc_error_handler
  46:     0x7ffe4e1c8adb - _rust_alloc_error_handler
  47:     0x7ffe5116313d - alloc::boxed::impl$48::call_once
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/alloc\src\boxed.rs:2453
  48:     0x7ffe5116313d - alloc::boxed::impl$48::call_once
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/alloc\src\boxed.rs:2453
  49:     0x7ffe5116313d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/7608018cbdac9e55d0d13529cf43adc33d53efcf\library/std\src\sys\pal\windows\thread.rs:55
  50:     0x7fff6372257d - BaseThreadInitThunk
  51:     0x7fff650aaf08 - RtlUserThreadStart

error: the compiler unexpectedly panicked. this is a bug.

**Comment by oli-obk** [comment] 2024-09-30 09:00
Duplicate of https://github.com/rust-lang/rust/issues/84970

**Closed by oli-obk** 2024-09-30 09:00 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
