### ISSUE TITLE
Confusing error message when including a module recursively

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#34157] opened 2016-06-08 04:57 UTC
Executing the following:

``` sh
cargo new --bin x
cd x
touch src/a.rs
echo 'mod a;' >> src/main.rs 
echo 'mod main;' >> src/main.rs 
cargo build
```

Results in this error message:

```
src/main.rs:4:5: 4:6 error: cannot declare a new module at this location
src/main.rs:4 mod a;
                  ^
src/main.rs:4:5: 4:6 note: maybe move this module `main` to its own directory via `main/mod.rs`
src/main.rs:4 mod a;
                  ^
src/main.rs:4:5: 4:6 note: ... or maybe `use` the module `a` instead of possibly redeclaring it
src/main.rs:4 mod a;
                  ^
```

None of which indicates that `main.rs` is being included recursively. Removing the `mod main;` line builds succesfully.

**Comment by jseyfried** [comment] 2017-02-08 07:30
Closing as duplicate of #36146.

**Closed by jseyfried** 2017-02-08 07:30 UTC
Labels: A-diagnostics
