### ISSUE TITLE
Regression in the Debug formatter

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#47619] opened 2018-01-20 20:50 UTC
The `Debug` formatter output was recently changed in #30967 to always include a decimal point, and apparently some crates' test suites depends on the exact output of the formatter. I don't know if it's worth to revert the change, but I reported it just in case.

* [caldyn](https://crates.io/crates/caldyn) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/caldyn-0.4.1/log.txt))
* [earlgrey](https://crates.io/crates/earlgrey) regressed from stable to beta ([crater log 1](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/earlgrey-0.0.7/log.txt) and [crater log 2](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/earlgrey-0.1.0/log.txt))
* [euclid](https://crates.io/crates/euclid) regressed from stable to beta ([crater log 1](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/euclid-0.15.6/log.txt) and [crater log 2](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/euclid-0.16.1/log.txt)), but it's fixed on master
* [expecttest](https://crates.io/crates/expectest) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/expectest-0.9.1/log.txt)), but it's fixed on master
* [mkv](https://crates.io/crates/mkv) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/mkv-0.0.7/log.txt))
* [postgis](https://crates.io/crates/postgis) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/postgis-0.4.0/log.txt))
* [pretty_assertions](https://crates.io/crates/pretty_assertions) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/pretty_assertions-0.4.1/log.txt)), but it's fixed on master
* [scanlex](https://crates.io/crates/scanlex) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/scanlex-0.1.0/log.txt))
* [spectral](https://crates.io/crates/spectral) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/spectral-0.6.0/log.txt))
* [vectors](https://crates.io/crates/vectors) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/vectors-0.1.0/log.txt))

 cc @dtolnay @luthaf @rodolf0

**Comment by pietroalbini** [comment] 2018-01-20 21:42
[euclid](https://crates.io/crates/euclid) and [expecttest](https://crates.io/crates/expectest) are also affected (but euclid now it's fixed on master).

cc @zummenix

**Comment by sfackler** [comment] 2018-01-20 21:57
We make zero guarantees as to what Debug implementations look like.

**Comment by Luthaf** [comment] 2018-01-21 02:37
I'm fine with this, I'll change my tests =)

**Comment by zummenix** [comment] 2018-01-21 04:15
I'll change my tests too. @pietroalbini thanks for cc me!

**Comment by pietroalbini** [comment] 2018-01-21 17:04
[mkv](https://crates.io/crates/mkv) is also affected.

cc @vi

**Comment by pietroalbini** [comment] 2018-01-21 17:46
[postgis](https://crates.io/crates/postgis) is also affected. cc @andelf @pka
[pretty_assertions](https://crates.io/crates/pretty_assertions) is also affected. cc @colin-kiegel
[scanlex](https://crates.io/crates/scanlex) is also affected. cc @stevedonovan

**Comment by colin-kiegel** [comment] 2018-01-21 20:32
Thanks for the heads up!

If you want to restore "consistent" behaviour across old and future rust versions, you can just replace `{:?}` with either `{:.0?}` or `{:.1?}`. This way you can still write testcases that depend on the exact debug output for floats:
```rust
print!("{:?}",   0.0); // stable: "0",   nightly "0.0"
print!("{:.0?}", 0.0); // stable: "0",   nightly "0"
print!("{:.1?}", 0.0); // stable: "0.0", nightly "0.0"
```

**Comment by vi** [comment] 2018-01-23 20:33
Shall there be a [clippy] lint against using Debug output for `assert_eq!`?

**Comment by pietroalbini** [comment] 2018-01-26 18:00
This also affects [spectral](https://crates.io/crates/spectral) ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/spectral-0.6.0/log.txt)). cc @cfrancia
This also affects [vectors](https://crates.io/crates/vectors) ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/vectors-0.1.0/log.txt)). cc @deepthought

**Comment by stevedonovan** [comment] 2018-01-29 08:31
Yes, it's foolish to depend on exact `Debug` representations, and I will fix accordingly. There was a similar situation in Lua 5.3 when the default formating for floats changed - broke a lot of naive code.

**Comment by Mark-Simulacrum** [comment] 2018-01-31 17:49
Closing as not a bug; we do not expect to make any changes here.

**Closed by Mark-Simulacrum** 2018-01-31 17:49 UTC
Labels: T-libs, regression-from-stable-to-beta

**Comment by sunjay** [comment] 2018-02-20 01:47
Broke the tests in the [turtle](https://github.com/sunjay/turtle) crate too. Any of our [tests using `should_panic`](https://github.com/sunjay/turtle/blob/7d0f7f7bbfbec068e950af0e7ded26a89e048a98/src/drawing.rs#L555) broke because they were relying on the entire message which included a formatted struct. 

```rust
#[test]
#[should_panic(expected = "Invalid color: Color { red: NaN, green: 0, blue: 0, alpha: 0 }. See the color module documentation for more information.")]
fn rejects_invalid_background_color() {
    // ...
}
```

Not a huge deal this time because there were just a few tests like that, but this really shouldn't be taken lightly either. Any breaking change, no matter how small for you can be really frustrating for someone else who doesn't see it coming. 

> Yes, it's foolish to depend on exact Debug representations, and I will fix accordingly. There was a similar situation in Lua 5.3 when the default formating for floats changed - broke a lot of naive code.

In this case, for `should_panic`, we only get to pass in a naive string, so of course changes like this will break a test like that. We don't even get to set formatting options so any of the workarounds suggested will not work. I'm including the debug representation in what I am testing because I want to make sure that its values match what I expect. Changing is a big deal and it broke my code in a way I really couldn't have prevented.

> We make zero guarantees as to what Debug implementations look like.

I'm fine with this, because it makes sense to me too, but as I said earlier I don't think any breaking change should be taken too lightly just because no explicit guarantees have been made. It's clear from this issue that a lot of people were relying on that being a certain way.
