### ISSUE TITLE
unconditional_recursion lint triger warning even when no recursion happens

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#23784] opened 2015-03-27 16:05 UTC
```rust
 fn main() { println!("{}", main as usize) }
```
[playpen](http://is.gd/0jUF21)
```
<anon>:1:1: 1:44 warning: function cannot return without recurring, #[warn(unconditional_recursion)] on by default
<anon>:1 fn main() { println!("{}", main as usize) }
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:1:28: 1:32 note: recursive call site
<anon>:1 fn main() { println!("{}", main as usize) }
```

**Comment by huonw** [comment] 2015-05-30 00:03
Dupe of #21705.

**Closed by huonw** 2015-05-30 00:03 UTC
Labels: A-diagnostics
