### ISSUE TITLE
Derive macro cannot derive manually defined trait implementations.

### ISSUE THREAD

**Issue by leeopop** [rust-lang/rust#59354] opened 2019-03-22 00:56 UTC
# Derive macro cannot derive manually defined trait implementations.

## Short Summary

A structure with all of its subfields deriving `Clone`, cannot automatically derive `Clone` when one of its template does not implement `Clone`.
I found that this happens for other traits such as `Copy`, `Hash`, and `Eq`.

## I tried this code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b309c9c370b38a55f608f91cbf6805bb

```{.rs}
use std::marker::PhantomData;

struct Dummy<T> {
    _phantom: PhantomData<*const T>,
}

impl<T> Default for Dummy<T> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData {},
        }
    }
}

impl<T> Clone for Dummy<T> {
    fn clone(&self) -> Self {
        Self {
            _phantom: PhantomData {},
        }
    }
}

pub trait Clonnable: Clone {}

#[derive(Clone)]
struct My<T> {
    dummy: Dummy<T>,
}

impl<T> Clonnable for My<T> {}

fn main() {}
```

## Expected behavior

`Dummy<T>` is a dummy type annotation and does not contain any actual instance of T.
Thus, for any `let a = Dummy::new()` and `let b = Dummy::new()`, `assert_eq!(a, b)` is satisfied.
The `Clone` trait is implemented for `Dummy` for any given type parameter `T`.
Thus, `My.dummy` is also `Clone`.

As all of its subfields are `Clone`, the auto-derive of `Clone` should work with `My`.

**Comment by petrochenkov** [comment] 2019-03-22 05:44
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by petrochenkov** 2019-03-22 05:44 UTC
