### ISSUE TITLE
rustdoc creates a second primitives page

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23917] opened 2015-03-31 22:54 UTC
http://doc.rust-lang.org/collections/#primitives

**Comment by tomjakubowski** [comment] 2015-04-01 21:42
This is a little tricky. The "second" page it creates is arguably the one in `std`. And since rustdoc has only a single-crate view of the world, when it's creating the `collections` docs it can't know that the module in `collections` is going to be re-exported in `std`.

A couple possible solutions:

1. Move the `slice` and `array` primitive docs into their own modules in `std` and/or `core`. That seems reasonable to me.
2. Pass a (possibly undocumented/unstable) flag to rustdoc to indicate whether to generate primitive pages or not.

**Comment by tomjakubowski** [comment] 2015-04-02 23:29
This also isn't such a huge deal for 1.0 since only `std` docs will be published, right?

**Comment by alexcrichton** [comment] 2015-04-08 00:50
@tomjakubowski's analysis is spot on, and this is also not a bug, but rather a feature. Users typically won't be landing on the libcollections docs, and the stdlib docs are all complete, so I'm going to close this.

**Closed by alexcrichton** 2015-04-08 00:50 UTC
Labels: A-rustdoc
