### ISSUE TITLE
cant find pkg-config windows

### ISSUE THREAD

**Issue by richmailYT** [rust-lang/rust#90902] opened 2021-11-14 15:02 UTC
Can not find pkg-config even though it is in path and i have all the needed dependencys

I tried this code:

```rust
#![allow(non_snake_case)]
//gtk4
use gtk4::prelude::*;
use gtk4::{Application, ApplicationWindow, Button};
use enigo::*;

fn main() {
    // Create a new application
    let app = Application::builder()
        .application_id("org.gtk-rs.example")
        .build();

    // Connect to "activate" signal of `app`
    app.connect_activate(build_ui);

    // Run the application
    app.run();
}

fn build_ui(app: &Application) {
    // Create a window and set the title
    let window = ApplicationWindow::builder()
        .application(app)
        .title("AutoClicker")
        .build();

    // Create a button with label and margins
    let StartClicker = Button::builder()
        .label("Press me!")
        .margin_top(12)
        .margin_bottom(12)
        .margin_start(12)
        .margin_end(12)
        .build();

    // Connect to "clicked" signal of `button`
    StartClicker.connect_clicked(move |StartClicker| {
        // Set the label to "Hello World!" after the button has been clicked on
        StartClicker.set_label("Started");
        AutoClicker()
    });

    // Add button
    window.set_child(Some(&StartClicker));

    // Present window to the user
    window.present();
}

fn AutoClicker() {
    let mut enigo = Enigo::new();
    enigo.mouse_move_to(500, 200);
    enigo.mouse_down(MouseButton::Left);
    enigo.mouse_move_relative(100, 100);
    enigo.mouse_up(MouseButton::Left);
}

```

I expected to see this happen:
compile nad run without error

Instead, this happened: 
can not find pkg-config

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-pc-windows-msvc
release: 1.56.1
LLVM version: 13.0.0
```
full error
```
https://pastebin.com/kc0ArqUM
```

**Comment by hkratz** [comment] 2021-11-14 15:49
You need pkg-config installed and in your PATH, see https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#pkg-config

Also this is definitely not a problem with Rust itself, you might want to ask questions related to gtk-rs here: https://gtk-rs.org/contact

**Comment by richmailYT** [comment] 2021-11-14 17:29
> You need pkg-config installed and in your PATH, see https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#pkg-config
> 
> Also this is definitely not a problem with Rust itself, you might want to ask questions related to gtk-rs here: https://gtk-rs.org/contact

nope, same error

**Comment by SNCPlay42** [comment] 2021-11-14 19:33
Duplicate of #90893

**Comment by workingjubilee** [comment] 2021-11-14 23:25
Directions on how to resolve this are included in the error message you posted:
>  Most likely, you need to install a pkg-config package for your OS.
> 
>  If you've already installed it, ensure the pkg-config command is one of the
>  directories in the PATH environment variable.
> 
>  If you did not expect this build to link to a pre-installed system library,
>  then check documentation of the glib-sys crate for an option to
>  build the library from source, or disable features or dependencies
>  that require pkg-config.

Unfortunately, we cannot meaningfully help you here with a crate that is working as-designed and features no errors in the Rust standard library or Rust compiler. Consider asking in a chatroom? This issue tracker is strictly for issues with Rust _per se_, not necessarily things made with Rust, so I am closing this.

**Closed by workingjubilee** 2021-11-14 23:25 UTC
Labels: C-bug
