### ISSUE TITLE
rustc 4x compilation time slowdown

### ISSUE THREAD

**Issue by bazald** [rust-lang/rust#88998] opened 2021-09-16 01:57 UTC
Moving from rustc 1.54 to 1.55, I'm observing a 4x compilation time slowdown for the examples for the `hash-trie` crate I'm working on. [permalink to current revision](https://github.com/bazald/hash-trie/tree/2ddf0a19863d3a2b5d28e7246b96086fab402901)

I'm not sure if this is a bug, or some new compilation feature, but compilation times increasing from 45-60s to 180-240s is not something I was expecting.

`cargo run --release --example set`
`cargo run --release --example set_xor`

Perhaps I'm doing something pathological in my crate, but I'd be very curious to know what change is causing this.

**Comment by jyn514** [comment] 2021-09-16 04:05
@bazald does this only happen with --release or does `cargo build` also reproduce the issue? Can you run `cargo rustc --release --example set -Z time-passes` and post the output? (`-Z self-profile` would also be helpful, it will generate a `profdata` file you can upload.)

**Comment by bazald** [comment] 2021-09-16 07:47
@jyn514 I can say that non-release build times seem marginally slower, but nothing I'd have noticed without the `--release` issue. Definitely appears that some optimization is going haywire on this code in 1.55... or is very expensive.

Regarding your other requests, I'm afraid I get the following message:

```
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
```

This sent me down a rabbit hole. Which nightlies are roughly equivalent? Can I even install old nightlies? If I can do that, can I basically run a bisect? Turns out I can.

nightly-2021-07-05-x86_64-pc-windows-msvc gives the old compilation time. (59.93s including dependencies)
nightly-2021-07-06-x86_64-pc-windows-msvc gives the new, drastically slowed compilation time. (3m 03s including dependencies)

I'm not sure I have the energy to run more commands tonight. Can you clarify whether you want `-Z time-passes` and `-Z self-profile` separately, and whether you want them for both 2021-07-05 and 2021-07-06 or just 06?

**Comment by hkratz** [comment] 2021-09-16 12:29
Some findings on a Mac M1:
* cargo clean; cargo +1.54.0 build --release --example set   # 17.24s
* cargo clean; cargo +1.55.0 build --example set   # 4.75s
* cargo clean; cargo +1.55.0 build --release --example set   # 57.07s
* cargo clean; cargo +beta build --release --example set    # (1.56.0-beta.2) - 16.44s
* cargo clean; cargo +nightly build --release --example set   # (2021-09-15) --> 16.61s

So only with 1.55.0 and `--release`, fixed in 1.56 beta and nightly.

**Comment by hkratz** [comment] 2021-09-16 13:03
Regression bisection led to #84560 (!), fix bisection lead to the update to LLVM 13 (#87570).

**Comment by jyn514** [comment] 2021-09-16 13:13
cc @nikic

**Comment by jyn514** [comment] 2021-09-16 13:13
Oh wait, I misread - this is only an issue with two releases of the rust compiler? I'm going to close this then since it's fixed on nightly.

**Closed by jyn514** 2021-09-16 13:13 UTC
Labels: I-slow, T-compiler, regression-from-stable-to-stable, I-prioritize
