### ISSUE TITLE
Ld error on Centos 6 with latest nightly

### ISSUE THREAD

**Issue by josephDunne** [rust-lang/rust#37801] opened 2016-11-16 17:42 UTC
I get the following error after upgrading to the latest nightly (reloc against `.debug_frame': error 2):

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/vagrant/rust/target/debug/build/nix-a4eb866b27c5afd7/build_script_build.0.o" "-o" "/home/vagrant/rust/target/debug/build/nix-a4eb866b27c5afd7/build_script_build" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/vagrant/rust/target/debug/deps" "-L" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/vagrant/rust/target/debug/deps/librustc_version-444dfb6f7755262a.rlib" "/home/vagrant/rust/target/debug/deps/libsemver-94c1b90d5b6dce88.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1357b93f.rlib" "/home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-1357b93f.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: /home/vagrant/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib(fileline.o)(.debug_frame+0x6c): reloc against `.debug_frame': error 2
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: final link failed: Nonrepresentable section on output
```

Reverting back to nightly-2016-11-03 fixed the problem for me. Unfortunately I don't really understand what this is or how to recreate.

**Comment by alexcrichton** [comment] 2016-11-16 17:54
Thanks for the report! This I believe is a dupe of https://github.com/rust-lang/rust/issues/37786 which should hopefully be fixed soon! (more info in that issue)

**Comment by josephDunne** [comment] 2016-11-16 17:55
Thank you

**Closed by alexcrichton** 2016-11-16 17:54 UTC
