### ISSUE TITLE
Why I can not attempted to repeat an expression

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#48037] opened 2018-02-06 16:31 UTC
This can run:

```rust
macro_rules! foo {
    ($name: ident) => {
        macro_rules! $name {
            ($x: tt) => {
                println!($x);
            }
        }
    }
}

fn main() {
    foo!(bar);
    bar!("test");
}
```

However, this can not:

```rust
macro_rules! foo {
    ($name: ident) => {
        macro_rules! $name {
            ($($x: tt),*) => {
                println!($($x),*);
            }
        }
    }
}

fn main() {
    foo!(bar);
    bar!("test");
}
```

**Comment by TimNN** [comment] 2018-02-06 17:57
This is a known limitation of `macro_rules!`: The macro parse thinks that the pattern in `$name` is a replacement in `foo`, in which case the error message would be correct.

Closing as a duplicate of #35853.

**Closed by TimNN** 2018-02-06 17:57 UTC
