### ISSUE TITLE
const size_of_val of variable 

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#76475] opened 2020-09-08 12:09 UTC
I think this is a reject-valid:

```rust
use std::mem::size_of_val;

fn main() {
    let mut k: u64 = 1_000_000_000;
    const N: usize = size_of_val(&k) * 8;
}
```

rustc (1.48.0-nightly 0d0f6b113 2020-09-03) gives:

```rust
error[E0435]: attempt to use a non-constant value in a constant
 --> C:\lavoro\bugs\temp.rs:5:35
  |
7 |     const N: usize = size_of_val(&k) * 8;
  |                                   ^ non-constant value
```

**Comment by jyn514** [comment] 2020-09-08 12:11
You have to say `const k`, not `let k`. The second introduces a runtime variable even if it stores a constant.

**Comment by jonas-schievink** [comment] 2020-09-08 12:13
Yes, closing as working as intended.

**Closed by jonas-schievink** 2020-09-08 12:13 UTC
Labels: C-bug

**Comment by leonardo-m** [comment] 2020-09-08 12:14
I need k variable in my code. The size of a variable is not influenced by it being mutable, variable or constant. So I don't agree with closing this down.

**Comment by jyn514** [comment] 2020-09-08 12:16
If the size is not influenced by the runtime value, you can use `size_of` instead which always works in a `const` context.

**Comment by leonardo-m** [comment] 2020-09-08 12:19
This is similar code in D and C++11 and it seems to work:

```d
void main() {
    ulong k = 1_000_000_000;
    enum size_t N = k.sizeof * 8;
    writeln(N);
}
```

```cpp
#include <stdint.h>
int main() {
    uint64_t k = 1'000'000'000;
    enum { N = sizeof(k) * 8 };
    return 0;
}
```

**Comment by leonardo-m** [comment] 2020-09-08 12:22
>If the size is not influenced by the runtime value, you can use size_of instead which always works in a const context.<

That sometimes forces me to define a type before:
```rust
use std::mem::size_of;

fn main() {
    type Int = u64;
    let mut k: Int = 1_000_000_000;
    const N: usize = size_of::<Int>() * 8;
}
```

The point of having a `size_of_val` is sometimes to avoid this.

**Comment by jyn514** [comment] 2020-09-08 12:27
No, the point of size_of_val is for dynamically sized types: https://doc.rust-lang.org/std/mem/fn.size_of_val.html

I'm sorry this doesn't meet your expectations from other languages, but you'd need an RFC or twenty to change it.

**Comment by leonardo-m** [comment] 2020-09-08 12:32
I see, thank you, it seems I missed the point of size_of_val. So what I needed is something like a constant size_of::<typeof(k)>()
