### ISSUE TITLE
Inference of argument type of async closure is broken

### ISSUE THREAD

**Issue by kriomant** [rust-lang/rust#127468] opened 2024-07-07 19:48 UTC
Well, it is maybe not a regression technically, because I use unstable feature. However, I wouldn't like this to get into stable channel.

### Code

I tried this code:

```rust
#![feature(async_closure)]

use std::future::Future;

pub struct A {}
impl A {
    fn method(&self) {}
}

pub fn call<B, F>(f: F)
    where F: FnOnce(A) -> B, B: Future<Output=()>
{
    f(A {});
}

pub fn test() {
    call(async move |a| {
        a.method();
    });
}
```

I expected to see this happen: I don't have to specify type of 'a' parameter as it may be inferred from `call` signature.

Instead, this happened:
```
error[E0282]: type annotations needed
  --> src/lib.rs:18:9
   |
18 |         a.method();
   |         ^ cannot infer type
```

I did compiler bisection, here is the result:

```
searched nightlies: from nightly-2023-03-17 to nightly-2024-06-12
regressed nightly: nightly-2024-02-07
searched commit range: https://github.com/rust-lang/rust/compare/f067fd6084d750f3797f54b71771c5dbc149726f...256b6fb19a2c018eaad4806d2369d1f6a71fc6ec
regressed commit: https://github.com/rust-lang/rust/commit/4a2fe4491ea616983a0cf0cbbd145a39768f4e7a

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-03-17 --end 2024-06-12
```
</details>
```

**Comment by compiler-errors** [comment] 2024-07-07 20:48
This is a duplicate of #127425.

Please rewrite your `call` function signature to use `async Fn` trait bounds to recover the signature inference: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bdff766a5208c09f202caeed0735ee86

```
#![feature(async_closure)]

pub struct A {}
impl A {
    fn method(&self) {}
}

pub fn call<B, F>(f: F)
where
    F: async FnOnce(),
{
    f(A {});
}

pub fn test() {
    call(async move |a| {
        a.method();
    });
}
```

Or if you're passing an async closure to a library you do, then I recommend either ascribing the types of your arguments, or probably just change your `async` closure back to using `|| async {}`, since there's nothing that async closures really buy you in this situation just yet.

**Closed by compiler-errors** 2024-07-07 20:48 UTC
Labels: C-bug, I-prioritize, regression-untriaged, needs-triage
