### ISSUE TITLE
ICE in travis on nightly/osx during compilation of `objc` dep

### ISSUE THREAD

**Issue by ozkriff** [rust-lang/rust#36923] opened 2016-10-03 10:04 UTC
https://travis-ci.org/ozkriff/zoc/jobs/164579863

**Comment by tormol** [comment] 2016-10-03 10:47
Duplicate of #36816.

It  has been fixed in master, but there haven't been a nightly in a few days.

**Closed** 2016-10-03 10:50 UTC
