### ISSUE TITLE
rustc crashed building gfx_graphics

### ISSUE THREAD

**Issue by mattwhiteside** [rust-lang/rust#23407] opened 2015-03-16 05:08 UTC
I was building this repo: https://github.com/pistondevelopers/gfx_graphics

using this command: cargo run --example image test

and got this backtrace:

```
   Compiling piston2d-gfx_graphics v0.1.7 (~/Documents/code/rust/gfx_graphics)
examples/imagetest.rs:42:10: 42:19 warning: use of deprecated item: use std::path instead, #[warn(deprecated)] on by default
examples/imagetest.rs:42         &Path::new("./assets/rust.png")).unwrap();
                                                    ^~~~~~~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'arithmetic operation overflowed', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/codemap.rs:73

stack backtrace:
   1:        0x1078afd1b - sys::backtrace::write::h3b83b15177f4f6b5fCC
   2:        0x1078d8afd - panicking::on_panic::h77e742d34f7c8b14DsI
   3:        0x1077f8b37 - rt::unwind::begin_unwind_inner::h8c5748c6ec61f668EbI
   4:        0x1077f930e - rt::unwind::begin_unwind_fmt::h09f57cab0d3c2b0cfaI
   5:        0x1078d85bd - rust_begin_unwind
   6:        0x107928325 - panicking::panic_fmt::h81bb86f758192917ZSs
   7:        0x1079202e7 - panicking::panic::h67ccdd3fa7b140bcbRs
   8:        0x106f67aaf - codemap::BytePos.Sub::sub::ha963a332df6226d2X7y
   9:        0x10479fa30 - middle::astencode::DecodeContext<'a, 'b, 'tcx>::tr_span::ha609caf2be923751UBa
  10:        0x1047b1bb4 - fold::noop_fold_expr::h6052110651558964661
  11:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  12:        0x1047b5385 - fold::noop_fold_expr::closure.65772
  13:        0x1047b200d - fold::noop_fold_expr::h6052110651558964661
  14:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  15:        0x1047b5385 - fold::noop_fold_expr::closure.65772
  16:        0x1047b200d - fold::noop_fold_expr::h6052110651558964661
  17:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  18:        0x1047b5385 - fold::noop_fold_expr::closure.65772
  19:        0x1047b1dea - fold::noop_fold_expr::h6052110651558964661
  20:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  21:        0x1047b27d8 - fold::noop_fold_expr::h6052110651558964661
  22:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  23:        0x1047b5322 - fold::noop_fold_expr::closure.65767
  24:        0x1047b9b5d - fold::noop_fold_local::closure.65998
  25:        0x1047b9558 - fold::noop_fold_decl::closure.65995
  26:        0x1047b7631 - fold::Folder::fold_stmt::closure.65925
  27:        0x1047b6ded - fold::noop_fold_block::closure.65876
  28:        0x1047b6a21 - iter::FlatMap<I, U, F>.Iterator::next::h8831031901394782976
  29:        0x1047b61ef - vec::Vec<T>.FromIterator<T>::from_iter::h390922894093893598
  30:        0x1047b5b04 - fold::noop_fold_block::closure.65785
  31:        0x1047b558a - fold::noop_fold_block::h2848417533559784555
  32:        0x1047b2cc4 - fold::noop_fold_expr::h6052110651558964661
  33:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  34:        0x1047b753f - fold::Folder::fold_stmt::closure.65925
  35:        0x1047b6ded - fold::noop_fold_block::closure.65876
  36:        0x1047b6a21 - iter::FlatMap<I, U, F>.Iterator::next::h8831031901394782976
  37:        0x1047b61ef - vec::Vec<T>.FromIterator<T>::from_iter::h390922894093893598
  38:        0x1047b5b04 - fold::noop_fold_block::closure.65785
  39:        0x1047b558a - fold::noop_fold_block::h2848417533559784555
  40:        0x1047b2cc4 - fold::noop_fold_expr::h6052110651558964661
  41:        0x1047b18d5 - ptr::P<T>::map::h7940627982087708418
  42:        0x1047b5322 - fold::noop_fold_expr::closure.65767
  43:        0x1047b5b90 - fold::noop_fold_block::closure.65785
  44:        0x1047b558a - fold::noop_fold_block::h2848417533559784555
  45:        0x1047d4df6 - fold::noop_fold_impl_item::closure.66340
  46:        0x1047d46fd - fold::noop_fold_impl_item::h1408433769782516448
  47:        0x1047a27ff - middle::astencode::decode_inlined_item::h98be5341b5740066vqa
  48:        0x104363b0c - trans::inline::instantiate_inline::closure.39503
  49:        0x104bc9c2f - metadata::decoder::maybe_get_item_ast::h9f3b16f53943285a3hg
  50:        0x1049aeb48 - metadata::csearch::maybe_get_item_ast::hc0376cacdb4fc82fVHi
  51:        0x10436236b - trans::inline::instantiate_inline::hcb4baf4731bceaee7hd
  52:        0x1043b4a06 - trans::callee::trans_fn_ref_with_substs::h3dd799fcfb10c61ankg
  53:        0x1043b3b84 - trans::meth::trans_static_method_callee::h87b6e738c13b7befj8x
  54:        0x1043b0654 - trans::callee::trans::hebb18e30873529a9eYf
  55:        0x1043c78ad - trans::callee::trans_call_inner::h11696719501217594510
  56:        0x1043d54dc - trans::expr::trans_rvalue_dps_unadjusted::he9f6005922fd4409xzi
  57:        0x1043d2e0c - trans::expr::trans_unadjusted::h9175a3adfcc3bf5723h
  58:        0x104383f5b - trans::expr::trans::h95e8c24c95ef80fcath
  59:        0x104483bae - trans::_match::trans_match_inner::hb05eebe09d542d345Ew
  60:        0x1043d48d3 - trans::expr::trans_rvalue_dps_unadjusted::he9f6005922fd4409xzi
  61:        0x1043823c6 - trans::expr::trans_into::h3e47f96968378458Smh
  62:        0x10449db76 - trans::_match::mk_binding_alloca::h6146964086414757799
  63:        0x104381830 - trans::base::init_local::h0459eb09a8f2f5e3Vys
  64:        0x1043831e2 - trans::controlflow::trans_block::hec4993ebaa40ee52t6d
  65:        0x104462739 - trans::base::trans_closure::h1c51c7ed964051ddRjt
  66:        0x10436a895 - trans::base::trans_fn::hd22a8a4bf4f7572dKut
  67:        0x10436c022 - trans::monomorphize::monomorphic_fn::hc946d75d050bcc6e2td
  68:        0x1043b4bbb - trans::callee::trans_fn_ref_with_substs::h3dd799fcfb10c61ankg
  69:        0x1043b314e - trans::callee::trans_fn_ref::h2efc8153c5a2595dX8f
  70:        0x1043b0810 - trans::callee::trans::hebb18e30873529a9eYf
  71:        0x1043c78ad - trans::callee::trans_call_inner::h11696719501217594510
  72:        0x1043d54dc - trans::expr::trans_rvalue_dps_unadjusted::he9f6005922fd4409xzi
  73:        0x1043d2e0c - trans::expr::trans_unadjusted::h9175a3adfcc3bf5723h
  74:        0x104383f5b - trans::expr::trans::h95e8c24c95ef80fcath
  75:        0x1043c2e11 - trans::callee::trans_args::he2b83edef17c4356F0g
  76:        0x1043ca547 - trans::callee::trans_call_inner::h37094392144590770
  77:        0x1043d405a - trans::expr::trans_rvalue_dps_unadjusted::he9f6005922fd4409xzi
  78:        0x1043823c6 - trans::expr::trans_into::h3e47f96968378458Smh
  79:        0x10449db76 - trans::_match::mk_binding_alloca::h6146964086414757799
  80:        0x104381830 - trans::base::init_local::h0459eb09a8f2f5e3Vys
  81:        0x1043831e2 - trans::controlflow::trans_block::hec4993ebaa40ee52t6d
  82:        0x104462739 - trans::base::trans_closure::h1c51c7ed964051ddRjt
  83:        0x10436a895 - trans::base::trans_fn::hd22a8a4bf4f7572dKut
  84:        0x10436c022 - trans::monomorphize::monomorphic_fn::hc946d75d050bcc6e2td
  85:        0x1043b4bbb - trans::callee::trans_fn_ref_with_substs::h3dd799fcfb10c61ankg
  86:        0x1043b314e - trans::callee::trans_fn_ref::h2efc8153c5a2595dX8f
  87:        0x1043b0810 - trans::callee::trans::hebb18e30873529a9eYf
  88:        0x1043c78ad - trans::callee::trans_call_inner::h11696719501217594510
  89:        0x1043d54dc - trans::expr::trans_rvalue_dps_unadjusted::he9f6005922fd4409xzi
  90:        0x1043823c6 - trans::expr::trans_into::h3e47f96968378458Smh
  91:        0x10449db76 - trans::_match::mk_binding_alloca::h6146964086414757799
  92:        0x104381830 - trans::base::init_local::h0459eb09a8f2f5e3Vys
  93:        0x1043831e2 - trans::controlflow::trans_block::hec4993ebaa40ee52t6d
  94:        0x104462739 - trans::base::trans_closure::h1c51c7ed964051ddRjt
  95:        0x10436a895 - trans::base::trans_fn::hd22a8a4bf4f7572dKut
  96:        0x10436627d - trans::base::trans_item::hb9b1cc2d4ac9a43fCSt
  97:        0x10446b9db - trans::base::trans_crate::h162d55e78175069bfPu
  98:        0x103dc1007 - driver::phase_4_translate_to_llvm::he30ee8c0cb343082kOa
  99:        0x103d9cd5a - driver::compile_input::h17478feb88f6e172Rba
  100:        0x103e5d193 - run_compiler::he252d03d9462df9cx2b
 ... <frames omitted>
```

**Comment by Byron** [comment] 2015-03-16 15:00
I am seeing the same, when building a different repository though.

### How to Reproduce

```bash
git clone https://github.com/rsaarelm/phage
cd phage
cargo build --release
```

### Meta

```bash
✗ rustc --version  --verbose
rustc 1.0.0-nightly (3e4be02b8 2015-03-13) (built 2015-03-13)
binary: rustc
commit-hash: 3e4be02b80a3dd27bce20870958fe0aef7e7336d
commit-date: 2015-03-13
build-date: 2015-03-13
host: x86_64-apple-darwin
release: 1.0.0-nightly
```

**Comment by mattwhiteside** [comment] 2015-03-16 17:28
When I submitted I forgot to include my version info, but it is the same as Sebastian’s.

**Comment by ihrwein** [comment] 2015-03-16 19:22
I have the same problem as @Byron :

```
$ rustc --version --verbose
rustc 1.0.0-nightly (c9b03c24e 2015-03-12) (built 2015-03-13)
binary: rustc
commit-hash: c9b03c24ec346e6405883032094f47805ef9c43e
commit-date: 2015-03-12
build-date: 2015-03-13
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

**Comment by tomaka** [comment] 2015-03-16 20:30
Probably a duplicate of #23115 and #23407

**Comment by kmcallister** [comment] 2015-03-17 19:05
I'm seeing this building html5ever as well.

**Comment by bltavares** [comment] 2015-10-31 21:30
The possible related bugs have been closed. Is this still happening?
Also, is there a minimal reproducible example?

**Comment by brson** [comment] 2017-04-04 17:58
Old crash with lots of related closes. Closing.

**Closed by brson** 2017-04-04 17:58 UTC
Labels: I-ICE
