### ISSUE TITLE
E0308 shows an incorrect suggestion if include_bytes! is used where &str is expected

### ISSUE THREAD

**Issue by difarem** [rust-lang/rust#51551] opened 2018-06-14 13:03 UTC
```rust
fn main() {
    let _: &str = include_bytes!("/etc/passwd");
}
```
[playground link](https://play.rust-lang.org/?gist=0081d8891f12e95fbd31cda3d9f704f4&version=stable&mode=debug)

```
error[E0308]: mismatched types
 --> bug.rs:2:19
  |
2 |     let _: &str = include_bytes!("bug.rs");
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^
  |                   |
  |                   expected str, found array of 58 elements
  |                   help: consider removing the leading `b`: `nclude_bytes!("bug.rs")`
  |
  = note: expected type `&str`
             found type `&'static [u8; 58]`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
```

The compiler (correctly) complains about a type mismatch, but suggests something that isn't applicable, as there is no literal to remove the `b` from.

Suggestion: define a special case for the `include_bytes!` and `include_str!` macros. The compiler should suggest replacing the former with the latter.

## Meta

Rustc version:
```
rustc 1.28.0-nightly (4a9c58c6b 2018-06-05)
binary: rustc
commit-hash: 4a9c58c6bd0e609538053a35685e206f66019820
commit-date: 2018-06-05
host: x86_64-unknown-linux-gnu
release: 1.28.0-nightly
LLVM version: 6.0
```

**Comment by kennytm** [comment] 2018-06-14 13:48
Duplicate of #48364.

**Closed by kennytm** 2018-06-14 13:48 UTC
