### ISSUE TITLE
Invalid "error: source trait is inaccessible" error

### ISSUE THREAD

**Issue by slimsag** [rust-lang/rust#28394] opened 2015-09-13 20:13 UTC
This code _*does not*_ compile ([playpen](http://is.gd/uKBOfD)):

```rust
pub mod mymod{

    mod foo {

        pub trait ToFoo{
            fn to_foo(self) -> i32;
        }
    }
    pub use self::foo::ToFoo;

}

pub fn foobar<T: mymod::ToFoo>(x: T) {
    let v = x.to_foo();
}

fn main() {}
```

Output:

```
<anon>:14:13: 14:23 error: source trait is inaccessible
<anon>:14     let v = x.to_foo();
                      ^~~~~~~~~~
<anon>:14:13: 14:23 note: module `foo` is private
<anon>:14     let v = x.to_foo();
                      ^~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```

Strangely as @bluss pointed out on IRC, this style _does_ compile ([playpen](http://is.gd/2GABjB)):

```
pub mod mymod{

    mod foo {

        pub trait ToFoo{
            fn to_foo(self) -> i32;
        }
    }
    pub use self::foo::ToFoo;

}

use mymod::ToFoo;

pub fn foobar<T: ToFoo>(x: T) {
    let v = ToFoo::to_foo(x);
}

fn main() {}
```

**Comment by Eljay** [comment] 2015-09-13 21:29
Duplicate of #16264.

**Closed** 2015-09-14 06:20 UTC
