### ISSUE TITLE
Backwards compatibility hazard with `Box` + `&mut` behaviour that cannot be replicated by a pure-library type

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#14270] opened 2014-05-18 02:45 UTC
With `Box` built deeply into the compiler, one can currently write

```rust
let mut y = 1;
let x: Box<&mut int> = box &mut y;
**x = 2;
```

That is, one can mutate through a `&mut` stored in the `Box`, even if the `Box` itself is not in a mutable slot. This is (presumably) because the compiler currently understands a lot about `Box`s behaviour, in particular, that it can act like an immutable unaliased pointer (`&uniq`).

There's currently no way to get this behaviour for library types, e.g. `Vec<&mut int>` is theoretically identical to `Box` in terms of ownership/aliasability of its contents, but, as it is a library type, the following cannot be made to work:

```rust
let mut y = 1;
let x: Vec<&mut int> = vec![&mut y];
// error: can't mutate a `& &mut int`
**x.get(0) = 2;
// error: can't borrow x as mutable
**x.get_mut(0) = 2;
```

We would need an immutable `&uniq` pointer for this behaviour to be possible for general simply-owned types like an in-library `Box`, `Vec`, `HashMap` etc.

Having this behaviour for `Box` represents a possible backwards compatibility hazard if we ever decide to move `Box` more into libraries. Specifically, moving `Box` into a library and preserving its current behaviour perfectly would require (at least) adding this new `&uniq` pointer type.

(Thanks to /u/SteveMcQwark on reddit for prompting this.)

(Nominating.)

**Comment by aturon** [comment] 2015-01-08 20:01
Re-nominating. This needs to be triaged again as part of our box story for beta.

**Comment by pnkfelix** [comment] 2015-01-08 21:35
Assigning 1.0-beta milestone.

**Comment by pnkfelix** [comment] 2015-02-10 13:34
nominating: someone needs to own this issue for the beta.

**Comment by pnkfelix** [comment] 2015-02-12 21:19
assigning to self.  (We may or may not resolve this by the beta, but we must address *whether* we are fixing it by then.)

**Comment by theemathas** [comment] 2015-02-14 09:08
What is the plan to fix this? `DerefMove`, `Box::into_inner()`, or something else?

**Comment by pnkfelix** [comment] 2015-03-26 21:19
We plan to change things to require the `mut` annotation on the binding in the example.

For now its a bug that it is not required.  We plan to fix the bug as part of 1.0 polish.

**Comment by pnkfelix** [comment] 2015-03-29 23:30
i have a potential patch for this.  (It is a kludge/hack that revises the `cmt::freely_aliasable` function (which is only called in spots that want to check if the input cmt is a precise path that we can thus uniquely write through) so that its result is more fine-grained, i.e. able to report that the cmt in question is not freely-aliasable but is nonetheless not writable (since it is e.g. going through an immutable container like the scenario described in this ticket).

**Closed** 2015-03-31 08:43 UTC
Labels: P-backcompat-lang

**Comment by nivkner** [comment] 2018-08-03 10:39
@pnkfelix this issue isn't fixed, the following code works on rust 1.28
```
fn main() {
    let mut y = 1;
    let x: Box<&mut i8> = Box::new(&mut y);
    **x = 2;
}
```

**Comment by nivkner** [comment] 2018-08-03 11:02
@pnkfelix the issue isn't fixed, the following code works on rust 1.28
```
fn main() {
    let mut y = 1;
    let x: Box<&mut i8> = Box::new(&mut y);
    **x = 2;
}
```

**Comment by pnkfelix** [comment] 2018-08-04 03:57
@nivkner Oh at this point I think its fair to say that we have punted, at least in the NLL work, on trying to avoid special casing of Box

See for example PR #52782

I do think there is talk of eventually allowing users to express similar features in their own library data types.

But I’m not sure that warrants reopening this particular ticket

**Comment by pnkfelix** [comment] 2018-08-04 04:02
Though I am curious ... I added a test when I “fixed” this originally ... did the test not actually cover this case, or has it regressed ...
