### ISSUE TITLE
Strange borrowing scope

### ISSUE THREAD

**Issue by Rexagon** [rust-lang/rust#96702] opened 2022-05-04 13:08 UTC
I tried this code:

```rust
pub struct Test {
    pub data: Option<u32>,
    pub other_data: u32,
}

impl Test {
    pub fn preload(&mut self) -> &u32 {
        if let Some(data) = &self.data {
            return data;
        }

        // Why `self.data` is still borrowed here?
        // Manually adding scope around `if {}` doesn't help.
        self.data = Some(123);

        &self.other_data
    }
}
```

I expected to see this happen: it compiles

Instead, this happened:
```
error[E0506]: cannot assign to `self.data` because it is borrowed
  --> <source>:12:9
   |
7  |     pub fn preload(&mut self) -> &u32 {
   |                    - let's call the lifetime of this reference `'1`
8  |         if let Some(data) = &self.data {
   |                             ---------- borrow of `self.data` occurs here
9  |             return data
   |                    ---- returning this value requires that `self.data` is borrowed for `'1`
...
12 |         self.data = Some(123);
   |         ^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.data` occurs here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0506`.
Compiler returned: 1
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

**Comment by ehuss** [comment] 2022-05-04 17:24
Thanks for the report!  As mentioned, this is a known limitation of the borrow checker.  Closing as a duplicate of #54663 (or one of the other issues linked there).

**Closed by ehuss** 2022-05-04 17:24 UTC
Labels: C-bug
