### ISSUE TITLE
ICE if generic destructor has several type parameters

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#14695] opened 2014-06-06 11:55 UTC
A generic destructor with more than one type parameter (one more than the struct in this case), causes an ICE. A bound like   `<T: Iterator<T>>` (for example) compiles, while `<A, T: Iterator<A>>` does not.

```rust
#![feature(unsafe_destructor)]
struct Test<T>(T);

#[unsafe_destructor]
impl <A, T: Iterator<A>> Drop for Test<T> {
    fn drop(&mut self) {  }
}

fn main() {
    let x = Test(2i);
    let _ = x;
}
```

ICE:

```
error: internal compiler error: unexpected failure
note: the compiler hit an unexpected failure path. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' failed at 'index out of bounds: the len is 1 but the index is 1', /build/rust-git/src/rust/src/librustc/middle/subst.rs:420
```

See also previous issue #4252 and its fix #12403

31 aug 2014: updated test code to compile with current rust, and updated to new different ICE msg.

**Comment by Twisol** [comment] 2015-01-04 22:54
Neither example currently causes an ICE, though some modernization changes needed to be made:

Original example (modified for associated types in `Iterator`):
```rust
$ rustc foo.rs
$ cat foo.rs
#![feature(unsafe_destructor)]
struct Test<T>(T);

#[unsafe_destructor]
impl <T: Iterator> Drop for Test<T> {
    fn drop(&mut self) {  }
}

fn main() {
    let x = Test(2i);
    let _ = x;
}
```

Second example (modified so `main` returns `()`):
```rust
$ rustc foo.rs
foo.rs:3:20: 3:24 warning: struct field is never used: `v`, #[warn(dead_code)] on by default
foo.rs:3 struct MyType<T> { v: T }
                            ^~~~
$ cat foo.rs
#![feature(unsafe_destructor)]
struct MyType<T> { v: T }

#[unsafe_destructor]
impl Drop for MyType<u8> {
    fn drop(&mut self) { () }
}

fn main() {
    let _foo = MyType{v:3u};
}
```

Version:
```rust
$ rustc --verbose --version
rustc 0.13.0-nightly (c6c786671 2015-01-04 00:50:59 +0000)
binary: rustc
commit-hash: c6c786671d692d7b13c2e5c68a53001327b4b125
commit-date: 2015-01-04 00:50:59 +0000
host: x86_64-apple-darwin
release: 0.13.0-nightly
```

**Comment by steveklabnik** [comment] 2015-01-16 21:51
The first example does ICE for me:

```
#![feature(unsafe_destructor)]
struct Test<T>(T);

#[unsafe_destructor]
impl <A, T: Iterator<Item=A>> Drop for Test<T> {
    fn drop(&mut self) {  }
}

fn main() {
    let x = Test(2i);
    let _ = x;
}
```

**Comment by tamird** [comment] 2015-03-15 23:13
```
#![feature(unsafe_destructor)]

struct Test<T>(T);

#[unsafe_destructor]
impl <A, T:Iterator <Item = A>> Drop for Test<T> {
  fn drop(&mut self) {}
}

fn main() {
  Test(2);
}
```

Still ICEs as of a6fea403d.

**Comment by pnkfelix** [comment] 2015-03-19 12:45
This is at least somewhat related to #8142, since this is an instance of a "specialized drop" where the `Drop` impl has bounds on `T` that are not present in the struct definition for `struct Test<T>` itself.

This variant has a proper compiler error message:
```rust
#![feature(unsafe_destructor)]

struct Test<T:Iterator>(T);

#[unsafe_destructor]
impl <A, T:Iterator<Item=A>> Drop for Test<T> {
  fn drop(&mut self) {}
}

fn main() {
  Test(2);
}
```

**Comment by tamird** [comment] 2015-04-21 21:41
None of these examples ICE today. I think this was fixed by https://github.com/rust-lang/rust/pull/23638.

@steveklabnik close?

**Comment by pnkfelix** [comment] 2015-04-21 22:01
@tamird I think at this point we just want to add regression tests (and/or at least check that all of the examples given here are reasonably covered by the existing test suite).

**Comment by tamird** [comment] 2015-04-21 22:04
@pnkfelix I think your tests at https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/reject-specialized-drops-8142.rs cover this.

**Comment by pnkfelix** [comment] 2015-04-21 22:08
@tamird While I'd love for that to be true, skimming over that test suite, I do not see any tests of parameter bounds that use the associated-item constraint syntax like `<A, T: Iterator<Item=A>>`.  So there may still be room for improved testing here.

**Comment by tamird** [comment] 2015-04-21 23:46
@pnkfelix would you mark this E-needstest?

**Comment by bluss** [comment] 2015-04-22 11:24
The issue was probably due to a configuration that can't be reached today -- Drop with two type parameters and struct with just one. The following compiles on nightly

```
struct Test<A, T: Iterator<Item=A>>(T);

impl <A, T: Iterator<Item=A>> Drop for Test<A, T> {
    fn drop(&mut self) {  }
}

fn main() {
    let x = Test(2..);
    let _ = x;
}
```

**Comment by steveklabnik** [comment] 2015-04-22 15:01
Seems good then :+1:

**Closed by steveklabnik** 2015-04-22 15:01 UTC
Labels: A-destructors, E-needstest, I-ICE
