### ISSUE TITLE
Confusing error message for re-exported types. Maybe show "aka"?

### ISSUE THREAD

**Issue by jhasse** [rust-lang/rust#29728] opened 2015-11-09 21:30 UTC
I'm doing the following:

``` rust
        gl::load_with(|s| window.get_proc_address(s));
```

which gives me

```
error: mismatched types:
 expected `*const libc::c_void`,
    found `*const ()`
```

So I added a cast:

``` rust
gl::load_with(|s| window.get_proc_address(s) as *const libc::c_void);
```

This results in:

```
error: mismatched types:
 expected `*const libc::c_void`,
    found `*const libc::types::common::c95::c_void`
```

And now I'm lost :D Why does it say it found `*const libc::types::common::c95::c_void`? I didn't write that. Apparently there's an older version of libc where `libc::c_void` is a re-export of the long type (durka42 told me that on IRC).

This is what I would expect the error message to look like:

```
error: mismatched types:
 expected `*const libc::c_void`,
    found `*const libc::c_void` aka `*const libc::types::common::c95::c_void`
```

This would still be a little bit confusing. Maybe include the version numbers somehow?

```
error: mismatched types:
 expected `*const libc::c_void` with libc 0.2,
    found `*const libc::c_void` aka `*const libc::types::common::c95::c_void` with libc 0.1
```

**Comment by steveklabnik** [comment] 2015-11-10 00:08
This should be a duplicate of another issue, but I can't seem to find it at the moment.

The only reason we don't do "aka" right now is that we don't actually have that information. I do believe that newer compilers have the version number though. @Manishearth was that you?

**Comment by Manishearth** [comment] 2015-11-10 00:34
No, I just made it mention that there may be two crates in scope when it hits the error. rust doesn't know about crate versions, though it can attempt to extract it from the `--extern` flags cargo passes to it.

**Comment by Mark-Simulacrum** [comment] 2017-06-01 20:08
I'm going to close in favor of https://github.com/rust-lang/rust/issues/17164 which is the "canonical" issue for diagnostics needing to print out type alias information.

**Closed by Mark-Simulacrum** 2017-06-01 20:08 UTC
Labels: A-diagnostics
