### ISSUE TITLE
Rustdoc and --disable-docs

### ISSUE THREAD

**Issue by petevine** [rust-lang/rust#30362] opened 2015-12-13 12:15 UTC
I'm not sure if I'm imagining this but did this option also disable building rustdoc in the past? It shouldn't be compulsory if never used.

I've noticed it's a rather long stage (librustdoc) so it might be a good idea to either skip it using the mentioned flag or add another dedicated one for that very purpose.

**Comment by sfackler** [comment] 2015-12-13 18:46
Not sure it makes sense to tie rustdoc into --disable-docs. Just because you don't want docs for libstd etc doesn't mean you don't want to be able to build docs for your own stuff.

**Comment by petevine** [comment] 2015-12-13 18:54
I meant if you don't want to waste time building rustdoc every time you shouldn't have to. 
You're right --disable-docs is not really related, just similar sounding :)

**Comment by alexcrichton** [comment] 2015-12-13 19:04
Thanks for the report! If you pass `--disable-docs` that just means that `make` won't build documentation by default, not that the documentation generator itself (rustdoc) won't be built. To prevent building standard build artifacts (e.g. those needed for a complete Rust installation) we could add another configure flag (e.g. --disable-rustdoc) or you'll need to tweak your `make` invocation.

For now though this is working as intended, so I'm going to close this.

**Closed by alexcrichton** 2015-12-13 19:04 UTC
