### ISSUE TITLE
Iterator.collect() not in documentation?

### ISSUE THREAD

**Issue by mchaput** [rust-lang/rust#19829] opened 2014-12-14 05:37 UTC
I'm trying to start learning Rust using Rust By Example and the standard library docs. Aside from trying to wrap my head around the difference between str and String (not helped by everyone calling them both "string" all the time), I noticed that RBE has this line:

```rust
let mut chars: Vec<char> = pangram.chars().collect();
```

RBE doesn't explain what `.collect()` does, so I tried looking it up in the docs. `.chars()` returns a `Chars` iterator. But looking at the `Chars` page (http://doc.rust-lang.org/std/str/struct.Chars.html) it has no information for `.collect()` (neither does the page for `Iterator`). Shouldn't that page list all of `Chars`'s methods and where they come from? Is this a bug in the documentation?

**Comment by kmcallister** [comment] 2015-01-16 18:26
Closing as a dupe of those.

**Closed by kmcallister** 2015-01-16 18:26 UTC
