### ISSUE TITLE
`unimplemented!()` not working with `-> impl Trait`

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#47367] opened 2018-01-11 22:41 UTC
This is a bit annoying:

```rust
#![feature(conservative_impl_trait, universal_impl_trait)]

fn running_count(iter: impl Iterator<Item = u32>) -> impl Iterator<Item = u32> {
    unimplemented!()
}

fn main() {}
```

```
error[E0277]: the trait bound `(): std::iter::Iterator` is not satisfied
 --> src/main.rs:3:54
  |
3 | fn running_count(iter: impl Iterator<Item = u32>) -> impl Iterator<Item = u32> {
  |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not an iterator; maybe try calling `.iter()` or a similar method
  |
  = help: the trait `std::iter::Iterator` is not implemented for `()`
  = note: the return type of a function must have a statically known size
```

**Comment by varkor** [comment] 2018-01-11 22:57
Similarly (which I think is the root cause), this fails:
```rust
#![crate_type = "lib"]
#![feature(conservative_impl_trait, universal_impl_trait)]
#![feature(never_type)]

trait T {}

fn f(x: !) -> impl T {
    x      // ^^^^^^ the trait `T` is not implemented for `!`
}
```

**Comment by Cobrand** [comment] 2018-01-12 02:54
This is a duplicate of #36375

**Comment by sfackler** [comment] 2018-01-12 04:25
Closing in favor of #36375.

**Closed** 2018-01-12 04:25 UTC
