### ISSUE TITLE
ICE ("this path should not cause illegal move")

### ISSUE THREAD

**Issue by aldanor** [rust-lang/rust#21506] opened 2015-01-22 11:38 UTC
This (bogus) piece of code seems to cause ICE:

```rust
pub struct Foo { x: usize }

fn main() {
    static mut FOO: *mut Foo = 0 as *mut Foo;
    let _foo = unsafe { *FOO.clone() };
}
```

```
ice1.rs:7:25: 7:37 error: internal compiler error: this path should not cause illegal move
ice1.rs:7     let _foo = unsafe { *FOO.clone() };
                                  ^~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:126

stack backtrace:
   1:     0x7f39eddf5a20 - sys::backtrace::write::h8a4dc9e73e8a435dvRt
   2:     0x7f39ede178c0 - failure::on_fail::h2ba8afb30d5ff67304z
   3:     0x7f39edd86180 - rt::unwind::begin_unwind_inner::h312ad0c8f7e45209eKz
   4:     0x7f39e85fb260 - rt::unwind::begin_unwind::h15315692592335573570
   5:     0x7f39e85fb1f0 - diagnostic::SpanHandler::span_bug::h11bfe9a4af254f3cEpF
   6:     0x7f39ebc46810 - session::Session::span_bug::ha51922765346cd16Qcp
   7:     0x7f39ec82fad0 - borrowck::build_borrowck_dataflow_data::hebc757194a8694e9cQe
   8:     0x7f39ec82c810 - borrowck::borrowck_fn::haef4dce7234d2ed4zNe
   9:     0x7f39ec82d720 - borrowck::borrowck_item::h1b395aabbbe3f362xMe
  10:     0x7f39ec82dc90 - borrowck::check_crate::h2223249b2c5fb97apHe
  11:     0x7f39ee383470 - driver::phase_3_run_analysis_passes::h3ddac035093704e2WFa
  12:     0x7f39ee370c90 - driver::compile_input::h8f87e6545ca866f1Cba
  13:     0x7f39ee43b8e0 - run_compiler::h01aa999b613651f1l9b
  14:     0x7f39ee43a050 - thunk::F.Invoke<A, R>::invoke::h5072366889563560254
  15:     0x7f39ee438fb0 - rt::unwind::try::try_fn::h15081826542860147634
  16:     0x7f39ede7e930 - rust_try_inner
  17:     0x7f39ede7e920 - rust_try
  18:     0x7f39ee439260 - thunk::F.Invoke<A, R>::invoke::h301471058200503190
  19:     0x7f39ede05550 - sys::thread::thread_start::h204ed77b5f1055c7QGw
  20:     0x7f39e7e0dd30 - start_thread
  21:     0x7f39eda273a9 - clone
  22:                0x0 - <unknown>
```

**Comment by jdm** [comment] 2015-01-22 15:36
Duplicate of #20801.

**Closed by jdm** 2015-01-22 15:36 UTC
