### ISSUE TITLE
Implement `IntoIterator` for fixed size arrays

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#29455] opened 2015-10-29 18:23 UTC
Size 0 to 12 or whatever.

Because otherwise it is only implemented via autoref and then you get references to the contents where you want the contents by value.

**Comment by Gankro** [comment] 2015-10-29 18:34
psuedo-blocked on ManuallyDrop https://github.com/rust-lang/rfcs/pull/197

There's no way to soundly partially move out of an array in a zero-cost way today. @bluss' [ArrayVec](https://github.com/bluss/arrayvec) crate accomplishes this by putting the array in a modified Option (one that supresses the null ptr optimization) and ptr::writeing None in the dtor.

**Comment by Gankro** [comment] 2015-10-29 18:35
We can certainly do the ArrayVec thing to get the job done if it's dire.

**Comment by bluss** [comment] 2015-10-29 18:55
This would be a breaking change since `[1, 2, 3].into_iter()` compiles in Rust 1.4. However it's a minor change by being avoidable with more specific/UFCS method calls.

Fortunately `for _ in [1, 2, 3]` does not compile in Rust 1.4.

**Comment by Gankro** [comment] 2015-10-29 18:59
Seems like acceptable breakage, since this is clearly desirable.

**Comment by steveklabnik** [comment] 2015-11-05 09:26
This is a duplicate of https://github.com/rust-lang/rust/issues/25725

**Closed by steveklabnik** 2015-11-05 09:26 UTC
Labels: A-libs
