### ISSUE TITLE
Compiler doesn't think trait is implemented in array size expression

### ISSUE THREAD

**Issue by sofia-m-a** [rust-lang/rust#77011] opened 2020-09-21 12:20 UTC
In the following code,

```rust
pub trait C {
    const SIZE: usize;
    type D;
}

pub struct A<B: C> {
    s: [B; <B as C>::SIZE],
    t: B::D,
}
```

both Rust Stable 1.46 and Nightly 1.48 report that 

```
error[E0277]: the trait bound `B: C` is not satisfied
 --> src/main.rs:6:12
  |
2 |     const SIZE: usize;
  |     ------------------ required by `C::SIZE`
...
6 |     s: [B; <B as C>::SIZE],
  |            ^^^^^^^^^^^^^^ the trait `C` is not implemented for `B`
  |
help: consider further restricting this bound
  |
5 | pub struct A<B: C + C> {
  |                   ^^^

error: aborting due to previous error
```
The bound `C` on the generic parameter `B` is correctly picked up at the type level, for `t: C::D`, but not at the constant-value level,
for `<B as C>::SIZE`

Moreover, the suggested fix is useless

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)
binary: rustc
commit-hash: 1fd5b9d516c035a898dcb437b2f982bea5d4bc88
commit-date: 2020-09-20
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

The bug also seems to affect Stable 1.46

If this is intended behavior, how are you meant to bound `B` appropriately to be able to use associated constants?

Is this something relating to const-generics awaiting stabilization? Either way, the error message is very misleading.

### Extended case
Extend the above code with

```rust
fn e<B: C>() {
    let s: [B; <B as C>::SIZE] = todo!();
}

struct F;
impl C for F {
    const SIZE: usize = 0;
    type D = F;
}

fn g() {
    let s: [F; <F as C>::SIZE] = todo!();
}
```

Then, `e` has the same error as `A`, but not `g`.

**Comment by jonas-schievink** [comment] 2020-09-21 12:35
Thanks for the report! This is currently a known issue where array lengths cannot make use of generic parameters, which is tracked in https://github.com/rust-lang/rust/issues/43408, so closing as a duplicate of that.

**Closed by jonas-schievink** 2020-09-21 12:35 UTC
Labels: C-bug
