### ISSUE TITLE
Error compiling Leptos project using cargo leptos

### ISSUE THREAD

**Issue by SleeplessOne1917** [rust-lang/rust#122525] opened 2024-03-15 02:00 UTC
The compilation error I ran into told me to open an issue here.

### Code

Unfortunately, I ran into this issue with a sizeable already existing project. [This is the project repo at the point the error occurred](https://github.com/LemmyNet/lemmy-ui-leptos/tree/e9e422a9d079cba824ea171e879aa891ae5e60e7).

### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (f4b771bf1 2024-03-14)
binary: rustc
commit-hash: f4b771bf1fb836392e1c510a625cdc81be09c952
commit-date: 2024-03-14
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0

```

### Error output

[rustc-ice-2024-03-15T01_37_21-19888.txt](https://github.com/rust-lang/rust/files/14609783/rustc-ice-2024-03-15T01_37_21-19888.txt)

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: cargo_leptos::run::{{closure}}
   2: tokio::runtime::park::CachedParkThread::block_on
   3: cargo_leptos::main
   4: std::sys_common::backtrace::__rust_begin_short_backtrace
   5: std::rt::lang_start::{{closure}}
   6: std::rt::lang_start_internal
   7: main
   8: <unknown>
   9: __libc_start_main
  10: _start

```

</p>
</details>

**Comment by SleeplessOne1917** [comment] 2024-03-15 02:09
cc. @gbj @benwis

**Comment by workingjubilee** [comment] 2024-03-15 06:15
Ah. Thank you for reporting. This looks like a duplicate of https://github.com/rust-lang/rust/issues/122508

Next nightly (not the current one) should have the fix.

**Comment by matthiaskrgr** [comment] 2024-03-15 06:21
you should be able to work around with `cargo check --release` or `cargo build --release`

**Comment by jieyouxu** [comment] 2024-03-16 00:02
Closing as a duplicate of #122508.

**Closed by jieyouxu** 2024-03-16 00:02 UTC
Labels: I-ICE, T-compiler, C-bug
