### ISSUE TITLE
Mir passes are hardcoded in `phase_3_run_analysis_passes`

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#45130] opened 2017-10-09 12:04 UTC
Currently, mir passes are hardcoded in `phase_3_run_analysis_passes` and it is being used in `compile_input`.

I write a Rust -> Spirv compiler which means I need to transform the mir myself and mir passes seem to be the best place for that. Afaik I cannot easily add mir passes from the outside as they are hardcoded in `phase_3_run_analysis_passes`.

Now I could easily write my own version of  `phase_3_run_analysis_passes` and `compile_input` but maybe it would be preferable if mir passes could be added from the outside?

I am not sure what the best place for it would be, maybe the passes could be passed into the `compile_input` function, or maybe they could be added in one of the `build_controller` callbacks?

**Comment by nikomatsakis** [comment] 2017-10-11 13:25
As discussed in #45147, this is basically "by design". We may wish to enable extension later, but for the time being, we'd prefer that you do this by requesting the optimized MIR (using the `optimized_mir` query), cloning the result, and then doing whatever changes you want to do. Closing this issue for now.

**Closed by nikomatsakis** 2017-10-11 13:25 UTC
Labels: C-feature-request
