### ISSUE TITLE
stack trace line numbers are missing on macos

### ISSUE THREAD

**Issue by MarkSwanson** [rust-lang/rust#25677] opened 2015-05-21 13:57 UTC
compile: cargo build
run: RUST_BACKTRACE=1 cargo run
I just created a new cargo package and tested: 
    let x: Option<u8> = None;
    x.unwrap();

I get:

```
$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/rust-test3`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362
stack backtrace:
   1:        0x1029e584f - sys::backtrace::write::hed569beb2862f85e32r
   2:        0x1029e8954 - panicking::on_panic::h6dbd1b68aa86e4f8uiw
   3:        0x1029e3e25 - rt::unwind::begin_unwind_inner::h0090d3e6f66b12ced0v
   4:        0x1029e412c - rt::unwind::begin_unwind_fmt::h47bc7a034f0ef64ejZv
   5:        0x1029e820c - rust_begin_unwind
   6:        0x102a05705 - panicking::panic_fmt::hbe1ae31b7ff09e37r3B
   7:        0x102a05084 - panicking::panic::h8a5faffa625e9e8aY1B
   8:        0x1029e29fe - option::Option<T>::unwrap::h6200398639833531646
   9:        0x1029e0d79 - main::h1c8acf58c698985ekaa
  10:        0x1029e98a8 - rust_try_inner
  11:        0x1029e9895 - rust_try
  12:        0x1029e90b0 - rt::lang_start::h212432a14b948ee6Zcw
  13:        0x1029e2a6e - main
An unknown error occurred
```
I'm on a mac.
$ rustc --version
rustc 1.2.0-nightly (0cc99f9cc 2015-05-17) (built 2015-05-17)

Fyi it works perfectly / as expected on Linux.

**Comment by sfackler** [comment] 2015-05-21 17:26
Not sure if debuginfo is quite the right label, but seems closeish.

**Comment by TimNN** [comment] 2015-08-10 09:30
Looks like a dupe of #24346

**Comment by jdm** [comment] 2015-08-10 13:48
Yep.

**Closed by jdm** 2015-08-10 13:48 UTC
Labels: A-debuginfo, A-mac-osx
