### ISSUE TITLE
flexible target specification breaks plugins lookup

### ISSUE THREAD

**Issue by farcaller** [rust-lang/rust#18699] opened 2014-11-06 16:16 UTC
I've got two crates failing to build after flexible target specification (https://github.com/rust-lang/rust/commit/6b130e3) was merged.

```
rustc \
  --opt-level 2 \
  -Z no-landing-pads \
  --cfg mcu_k20 --cfg arch_cortex_m4 \
  -g \
  -C no-stack-check \
  -L /Users/farcaller/src/zinc/build \
  --out-dir /Users/farcaller/src/zinc/build \
  /Users/farcaller/src/zinc/src/macro/ioreg.rs
```

builds `libmacro_ioreg.dylib` (and a matching `libmacro_ioreg.dylib.dSYM`).

The crate that depends on it fails to build though:

```
rustc \
  --opt-level 2 \
  -Z no-landing-pads \
  --cfg mcu_k20 --cfg arch_cortex_m4 \
  --target thumbv7em-none-eabi -Ctarget-cpu=cortex-m4 \
  -C relocation_model=static \
  -g \
  -C no-stack-check \
  -L /Users/farcaller/src/zinc/build \
  --out-dir /Users/farcaller/src/zinc/build  /Users/farcaller/src/zinc/src/zinc/lib.rs
/Users/farcaller/src/zinc/src/zinc/lib.rs:52:18: 52:43 error: can't find crate for `macro_ioreg`
/Users/farcaller/src/zinc/src/zinc/lib.rs:52 #[phase(plugin)] extern crate macro_ioreg;
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

if I remove `--target thumbv7em-none-eabi`, the macro_ioreg crate is resolved correctly.

target spec:
```json
{
    "data-layout": "e-m:e-p:32:32-i1:8:32-i8:8:32-i16:16:32-i64:64-v128:64:128-a:0:32-n32-S64",
    "llvm-target": "thumbv7em-none-eabi",
    "target-endian": "little",
    "target-word-size": "32",
    "arch": "arm",
    "os": "none",
    "morestack": false
}
```

**Comment by farcaller** [comment] 2015-01-10 19:04
Okay, I finally got down to exact problem which is this codepath in metadata loader:
```rust
        if triple != self.triple {
            info!("Rejecting via crate triple: expected {} got {}", self.triple, triple);
            self.rejected_via_triple.push(CrateMismatch {
                path: libpath.clone(),
                got: triple.to_string()
            });
            return false;
        }
```

failing with `Rejecting via crate triple: expected thumbv7m-none-eabi got x86_64-apple-darwin`.

honestly speaking I have not a single idea why this is working on linux :smile: it should be broken literally everywhere.

The problem here is that triple should be checked against rustc's current platform triple, not target triple in case of plugins.

**Comment by bgamari** [comment] 2015-01-10 20:36
I am able to reproduce this on Linux with,
`rustc 1.0.0-dev (6a697325c 2015-01-09 18:56:14 -0500)`

**Comment by larsbergstrom** [comment] 2015-01-11 00:52
@alexcrichton @brson I suspect this is the issue that had been breaking our Servo OSX->Android builds for the past couple of months, and am very afraid that it will break both our Linux Android and Gonk builds when we get whatever causes this to break Linux as well and block our upgrade to 1.0 alpha

**Comment by alexcrichton** [comment] 2015-01-11 04:35
@farcaller, @bgamari, @larsbergstrom, is there a small code example that I could reproduce this behavior with?

**Comment by farcaller** [comment] 2015-01-11 09:50
plugin.rs:
```rust
#![feature(plugin_registrar)]
#![crate_type="dylib"]

#[macro_use] extern crate log;
extern crate rustc;

use rustc::plugin::Registry;

#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
  info!("plugin registrar called");
}
```

main.rs:
```rust
#![feature(plugin)]
#![crate_type="staticlib"]

#[plugin] extern crate plugin;
```

```
% rustc plugin.rs
...
% rustc main.rs -L . --target arm-unknown-linux-gnueabi
main.rs:4:11: 4:31 error: can't find crate for `plugin`
main.rs:4 #[plugin] extern crate plugin;
                    ^~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
```

**Comment by farcaller** [comment] 2015-01-11 09:56
Also worth to mention that I had to modify the target spec json with this:

```json
"dll-prefix": "lib",
"dll-suffix": "dylib",
"is-like-osx": true
```

to get it to fail to rejection via triple otherwise the rlib isn't even considered (the defaults resolve only on linux which was the case for original breakage in Nov). It isn't really acceptable to make target spec to be dependent on host spec.

For the reference, our spec for thumbv7m-none-eabi is:
```json
{
    "arch": "arm",
    "cpu": "cortex-m3",
    "data-layout": "e-m:e-p:32:32-i1:8:32-i8:8:32-i16:16:32-i64:64-v128:64:128-a:0:32-n32-S64",
    "disable-redzone": true,
    "executables": true,
    "llvm-target": "thumbv7m-none-eabi",
    "morestack": false,
    "os": "none",
    "relocation-model": "static",
    "target-endian": "little",
    "target-word-size": "32",
}
```

**Comment by bgamari** [comment] 2015-01-11 17:23
I've put a modified version of @farcaller's example up as a [gist](https://gist.github.com/bgamari/68e4f3c431cee9e6976a). This fails for me with the reported error on Linux with,
```
$ rustc --version
rustc 1.0.0-dev (6a697325c 2015-01-09 18:56:14 -0500)
$ ./build.sh 
plugin.rs:4:14: 4:31 warning: use of unstable item: use the crates.io `log` library instead, #[warn(unstable)] on by default
plugin.rs:4 #[macro_use] extern crate log;
                         ^~~~~~~~~~~~~~~~~
plugin.rs:5:1: 5:20 warning: use of unstable item, #[warn(unstable)] on by default
plugin.rs:5 extern crate rustc;
            ^~~~~~~~~~~~~~~~~~~
plugin.rs:10:25: 10:28 warning: unused variable: `reg`, #[warn(unused_variables)] on by default
plugin.rs:10 pub fn plugin_registrar(reg: &mut Registry) {
                                     ^~~
main.rs:5:11: 5:31 error: couldn't find crate `plugin` with expected target triple arm-unknown-linux-gnueabi
main.rs:5 #[plugin] extern crate plugin;
                    ^~~~~~~~~~~~~~~~~~~~
main.rs:5:31: 5:31 note: crate `plugin`, path #1, triple x86_64-unknown-linux-gnu: /home/ben/68e4f3c431cee9e6976a/libplugin.so
error: aborting due to previous error
```

**Comment by larsbergstrom** [comment] 2015-01-11 18:23
You can also just use @huonw's compile_msg project. In Servo, you can see the error on OSX today by just building with `./mach build --android` and you will get:
```
/Users/larsberg/.cargo/git/checkouts/android-rs-glue-0edd59d2611b734a/servo/glue/src/lib.rs:8:1: 8:26 error: can't find crate for `compile_msg`
/Users/larsberg/.cargo/git/checkouts/android-rs-glue-0edd59d2611b734a/servo/glue/src/lib.rs:8 extern crate compile_msg;
```

**Comment by alexcrichton** [comment] 2015-01-11 21:08
@farcaller, @bgamari I think you both need the `#[no_link]` in addition to the `#[plugin]` attribute, otherwise it's trying to actually link to the crate (hence the error message).

@larsbergstrom it looks like you're using an older compiler, and I'm not quite sure what's going on there! That may have been a bug fixed in Cargo though?

**Comment by farcaller** [comment] 2015-01-11 21:28
@alexcrichton seems that I managed to workaround this problem with `#[macro_use] #[no_link] #[plugin] extern crate ioreg;`, but rustc still fails to locate the libioreg.dylib if there are no dll-prefix / dll-suffix / is-like-osx flags in target spec.

**Comment by alexcrichton** [comment] 2015-01-12 16:53
That does seem odd that it would require those flags for the *target* as opposed to the host... Sounds like a bug!

**Comment by farcaller** [comment] 2015-01-12 17:05
Well, effectively it is what this bug is originally about. The problem we raised two days ago here was apparently a misunderstanding of how `#[no_link]` works.

**Comment by farcaller** [comment] 2015-02-23 16:27
Seems to work as of 2b01a37ec.

**Comment by tamird** [comment] 2015-03-15 20:04
Is this inadvertently tested by 48b6aef6605794a9da0d9254960a91bbea0a0737?

**Comment by cmr** [comment] 2015-03-15 21:52
Seems so.

**Closed by cmr** 2015-03-15 21:52 UTC
Labels: A-plugin, E-needstest, I-wrong
