### ISSUE TITLE
Weird error when wrongly defining doc at end of struct

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#30322] opened 2015-12-11 10:03 UTC
Consider this code:
```rust
struct FunStruct {
    /// fun having errors
}
```
It is obviously wrong, doc comments have to be before items. The error rustc gives one is very weird however:
```
<anon>:3:1: 3:2 error: expected ident
<anon>:3 }
         ^
```
Is rust python?

Note this only seems to happen for structs. functions and traits display smarter error messages.

cc  @nikomatsakis bc I've heard on irc he wants to be notified on weird errors.

**Comment by steveklabnik** [comment] 2015-12-11 14:19
Documentation comments expect to have something to document. You want `//`.

This is a duplicate of https://github.com/rust-lang/rust/issues/27429.

**Closed by steveklabnik** 2015-12-11 14:19 UTC

**Comment by est31** [comment] 2015-12-11 19:47
Ah `ident` as in identifier, not indentation. Well then its not much worse than 27429.
