### ISSUE TITLE
Inline const block is not always an expression

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#82750] opened 2021-03-04 08:51 UTC
The following code:
```Rust
#![feature(inline_const)]

fn main() {
    dbg!(const {});
}
```
fails to compile, producing this error message:
```
error: no rules expected the token `const`
 --> src/main.rs:4:10
  |
4 |     dbg!(const {});
  |          ^^^^^ no rules expected this token in macro call
  ```
  
  However, if the entire `const {}` is placed in yet another `{}` block, it just works:
  ```Rust
  #![feature(inline_const)]

fn main() {
    dbg!({ const {} });
}
```

**Comment by petrochenkov** [comment] 2021-04-13 20:52
Closing as a duplicate of https://github.com/rust-lang/rust/issues/84155 (which is newer, but has some discussion).

**Closed by petrochenkov** 2021-04-13 20:52 UTC
Labels: F-inline_const, T-compiler
