### ISSUE TITLE
cargo doc fails to compile existential associated types

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/rust#58011] opened 2019-01-30 20:42 UTC
While building, testing and running the below code works fine, `cargo doc` fails with:

```
error[E0277]: the trait bound `(): D` is not satisfied
  --> test_existential_doc_crash.rs:13:5
   |
13 |     existential type B: D;
   |     ^^^^^^^^^^^^^^^^^^^^^^ the trait `D` is not implemented for `()`
   |
   = note: the return type of a function must have a statically known size
```

```rust
#![feature(existential_type)]

pub trait A {
    type B: D;
    fn c() -> Self::B;
}

pub trait D {}
impl D for u8 {}

pub struct E;
impl A for E {
    existential type B: D;
    fn c() -> Self::B {
        0u8
    }
}
```

**Comment by rasendubi** [comment] 2019-05-20 12:37
This happens with non-associated types, too.

Here is a smaller example:
```rs
#![feature(existential_type)]

pub trait A {}
impl A for u8 {}

existential type T: A;

fn f() -> T {
    0u8
}
```
```
error[E0277]: the trait bound `(): A` is not satisfied
 --> test.rs:6:1
  |
6 | existential type T: A;
  | ^^^^^^^^^^^^^^^^^^^^^^ the trait `A` is not implemented for `()`
  |
  = note: the return type of a function must have a statically known size
```

Basically, rustdoc treats all existential types as `()`.

**Comment by Nemo157** [comment] 2019-08-26 10:09
Updated example for `type_alias_impl_trait` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ea8a9f50caee2dc627c18b81639f99e0)):

```rust
#![feature(type_alias_impl_trait)]

pub struct Foo;

impl std::iter::IntoIterator for Foo {
    type IntoIter = impl Iterator<Item = Self::Item>;
    type Item = ();

    fn into_iter(self) -> Self::IntoIter {
        Some(()).into_iter()
    }
}

pub type FooIntoIter = impl Iterator<Item = ()>;

pub fn foo_into_iter(foo: Foo) -> FooIntoIter {
    foo.into_iter()
}
```

```
error[E0277]: `()` is not an iterator
 --> src/lib.rs:6:5
  |
6 |     type IntoIter = impl Iterator<Item = Self::Item>;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not an iterator
  |
  = help: the trait `std::iter::Iterator` is not implemented for `()`
  = note: the return type of a function must have a statically known size

error[E0277]: `()` is not an iterator
  --> src/lib.rs:14:1
   |
14 | pub type FooIntoIter = impl Iterator<Item = ()>;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not an iterator
   |
   = help: the trait `std::iter::Iterator` is not implemented for `()`
   = note: the return type of a function must have a statically known size
```

**Comment by varkor** [comment] 2020-01-12 17:19
Closing as a duplicate of https://github.com/rust-lang/rust/issues/65863 (which has more information).

**Closed by varkor** 2020-01-12 17:19 UTC
Labels: A-impl-trait, C-bug, F-type_alias_impl_trait, T-rustdoc, requires-nightly
