### ISSUE TITLE
rustdoc generates duplicate anchors

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#28479] opened 2015-09-18 00:08 UTC
For https://doc.rust-lang.org/nightly/std/collections/struct.HashMap.html : 

Anchor |	Lines
--- | ---
method.extend	|740, 741
assoc_type.IntoIter|	731, 734, 737
assoc_type.Item|	730, 733, 736
method.into_iter|	732, 735, 738
examples|	85, 218, 229, 243, 273, 296, 315, 330, 354, 382, 410, 439, 476, 509, 528, 549, 585, 608, 631, 654, 678, 708

**Comment by apasel422** [comment] 2015-09-18 12:31
Duplicate of #25001.

**Closed** 2015-09-18 16:58 UTC
