### ISSUE TITLE
inner module can import private items by name

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#29921] opened 2015-11-19 05:06 UTC
This code [compiles](http://is.gd/jt3seM):

```rust
fn bar() {}

mod inner {
    //use super::*; // doesn't pick up bar
    use super::bar; // ok
    
    pub fn foo() { bar(); }
}

fn main() { inner::foo(); }
```

It seems like it shouldn't compile because `bar` is private. I found #4366 which seems to agree, but that was a long time ago.

**Comment by huonw** [comment] 2015-11-19 05:13
Being able to import it is expected behaviour. Privacy controls access from outside the module, not inside it, including submodules. Note that #4366 is external.

Closing as not a bug, but thanks for filing!

**Closed by huonw** 2015-11-19 05:13 UTC

**Comment by durka** [comment] 2015-11-19 05:14
You're right #4366 is the opposite. Wildcard imports are just whack, but we already knew that.
