### ISSUE TITLE
intra-doc links: Links with unexpected characters are silently ignored

### ISSUE THREAD

**Issue by dylni** [rust-lang/rust#77199] opened 2020-09-25 18:13 UTC
Intra-doc links with unexpected characters are ignored here:

https://github.com/rust-lang/rust/blob/78a089487b5f6d5e4205ac4500410b442857bced/src/librustdoc/passes/collect_intra_doc_links.rs#L931-L933

However, it would be better if they caused a warning with `--display-doctest-warnings`. Developers might expect ``[`&[String]`]`` to link to the [slice primitive](https://doc.rust-lang.org/std/primitive.slice.html), but that link would be ignored without a warning.

cc @jyn514 
cc https://github.com/rust-lang/rust/issues/76106#issuecomment-699034205

**Comment by dylni** [comment] 2021-11-29 00:07
@camelid Thanks, I updated the option name. However, I am still not seeing a warning for ``[`&[String]`]``, which was my primary concern. It would be ideal if bracketed text could either be properly linked or give a warning in all cases.

**Comment by camelid** [comment] 2021-11-29 00:19
I've changed the title since `--display-doctest-warnings` is being removed and is not the right way to expose this anyway.

**Comment by dylni** [comment] 2021-11-29 00:23
That's great. Enabling the warnings by default is much better.

**Comment by camelid** [comment] 2021-11-29 00:34
> That's great. Enabling the warnings by default is much better.

I see the advantage of enabling them by default, but rustdoc intentionally silently ignores some links to avoid tons of lints being emitted for existing docs.

**Comment by jyn514** [comment] 2021-11-29 00:46
This is a duplicate of https://github.com/rust-lang/rust/issues/54191.

**Comment by dylni** [comment] 2021-11-29 00:46
> rustdoc intentionally silently ignores some links

Is there a plan to allow requesting stricter behavior when `--display-doctest-warnings` is removed? I read through #73314, but there seems to be some confusion about the many purposes the option serves, which I assume is why it's being removed.

**Comment by jyn514** [comment] 2021-11-29 00:48
@dylni what do you mean by stricter behavior? If you mean what's in this issue, I don't think it's a good idea for rustdoc to decide whether to resolve a link based on an option; it already does that for --document-private-items and it's pretty confusing IMO. If you mean something else, please open a new issue; I'm ok with adding additional lints but I'm not a fan of additional configuration.

**Comment by dylni** [comment] 2021-11-29 00:54
@jyn514 camelid mentioned

> `--display-doctest-warnings` is being removed and is not the right way to expose this anyway.

I was wondering if there was a particular replacement planned for the option. In the past, it enabled warnings when intra-doc links failed to resolve, but that part seems to be enabled by default now. I was wondering if there's any additional strictness/warnings that would be lost by removing the option.

> I don't think it's a good idea for rustdoc to decide whether to resolve a link based on an option

I agree. It doesn't matter to me if these links are resolved or fail. I would just prefer a warning when they're unresolved.

**Comment by camelid** [comment] 2021-11-29 01:08
> I was wondering if there was a particular replacement planned for the option. In the past, it enabled warnings when intra-doc links failed to resolve, but that part seems to be enabled by default now. I was wondering if there's any additional strictness/warnings that would be lost by removing the option.

Hmm, I didn't realize the flag used to enable intra-doc warnings. My understanding was that it was always used to show warnings in doctests (i.e., ` ``` ` code examples).

**Comment by dylni** [comment] 2021-11-29 01:13
> Hmm, I didn't realize the flag used to enable intra-doc warnings.

That was the only reason I mentioned it in this issue. IIRC, at the time this issue was created, not using `--display-warnings` caused no warnings to be displayed.

**Comment by jyn514** [comment] 2021-11-29 01:19
> IIRC, at the time this issue was created, not using --display-warnings caused no warnings to be displayed for all broken intra-doc links.

That can't be correct. I started working on intra-doc links about 2 months before you opened the issues and they still gave warnings at that time; AFAIK they've never been behind any sort of feature gate.

**Comment by jyn514** [comment] 2021-11-29 01:20
Anyway, I think this is a distraction. CLI options seem like the wrong model for this and I don't think we should add more; this should be a new lint if we add it at all.

**Comment by jyn514** [comment] 2021-11-29 01:21
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/54191.

**Closed by jyn514** 2021-11-29 01:21 UTC
Labels: T-rustdoc, I-needs-decision, A-intra-doc-links

**Comment by dylni** [comment] 2021-11-29 01:26
> AFAIK they've never been behind any sort of feature gate.

It's entirely possible this is correct, and you would know better than I. That is just what I recall being the reason.

> Anyway, I think this is a distraction.

Right, this got a little off-topic.

> I'm going to close this in favor of #54191.

Thanks for pointing out that issue!

**Comment by camelid** [comment] 2021-11-29 01:32
@dylni Perhaps you're thinking of `--deny warnings`?

**Comment by dylni** [comment] 2021-11-29 02:17
@camelid After investigating a bit, I think I may have falsely attributed the option with showing intra-doc warnings in addition to doctest warnings. Cached compilation not re-issuing warnings was likely what I was seeing instead. Sorry for the confusion.
