### ISSUE TITLE
Unsized function argument causes LLVM segfault

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#41229] opened 2017-04-11 20:18 UTC
## Meta
```
rustc 1.18.0-nightly (3b5754e5c 2017-04-10)
```
## STR

```Rust
pub fn example(ref s: str) {}

fn main() {}
```

## Result

```
rustc 1.18.0-nightly (3b5754e5c 2017-04-10)
warning: unused variable: `s`
 --> <anon>:1:16
  |
1 | pub fn example(ref s: str) {}
  |                ^^^^^
  |
  = note: #[warn(unused_variables)] on by default

Segmentation fault (core dumped)
```

This is not an LLVM assertion, but rather a `NULL` pointer passed to `val_ty`.

**Comment by nateozem** [comment] 2017-04-18 08:45
I tried to replicate issue, but failed to do so.

```
 $ rustc -vV
rustc 1.18.0-nightly (ad36c2f55 2017-04-09)
binary: rustc
commit-hash: ad36c2f5528d617db66c244d8bcbfc4b36da0ca0
commit-date: 2017-04-09
host: x86_64-apple-darwin
release: 1.18.0-nightly
LLVM version: 3.9

 $ rustc src/main.rs
warning: unused variable: `s`
 --> src/main.rs:1:16
  |
1 | pub fn example(ref s: str) {}
  |                ^^^^^
  |
  = note: #[warn(unused_variables)] on by default

 $ ./main

 $ 
```

What process and commands did you run?

**Comment by Mark-Simulacrum** [comment] 2017-06-21 22:58
I cannot reproduce today. Marking as E-needstest.

**Closed** 2017-09-10 15:32 UTC
Labels: A-codegen, A-LLVM, C-bug, E-needstest
