### ISSUE TITLE
sender Cannot exit while using nested

### ISSUE THREAD

**Issue by linkwik** [rust-lang/rust#64350] opened 2019-09-10 13:08 UTC
When I crawled the web pages with rust and curl, I needed to handle the redirected connections, so I created channels to handle the target, but when all the channels were finished, the program didn't quit and was still waiting

I tried drop(), but it didn't work

the code:

```rust
extern crate serde;
extern crate serde_json;
extern crate curl;
use curl::easy::Easy;
#[macro_use]
extern crate serde_derive;

use std::thread;
use std::sync::mpsc::{channel, Receiver, Sender};
use std::fs::File;
use std::io::Read;
use std::time::Duration;

#[derive(Serialize, Deserialize)]
struct Target {
    name: String,
    domain: String
}


struct ResultTarget {
    name: String,
    domain: String,
    status_code: u32,
    banner: String,
    ip: String
}

fn main() {
    let (task_send, task_rece) = channel();
    let (redict_send, redict_rece) = channel();

    let gen_task = thread::spawn(move|| gen_target("target.json".to_string(), task_send, redict_rece));
    let run_task = thread::spawn(move|| {
        for i in task_rece {
            get_html(i.name, i.domain, redict_send.clone());
        }
    });

    run_task.join().unwrap();
    gen_task.join().unwrap();

}


fn gen_target(filename:String, task_send: Sender<Target>, redict_rece:Receiver<Target>) {
    let mut data = String::new();

    let mut files = File::open(filename).ok().expect("ERROR: [read_files] Open file Error!");
    files.read_to_string(&mut data).ok().expect("ERROR: [read_files] Read to string!");

    // let mut target_list = Vec::new();
    for i in data.lines() {
        if i.eq("[") || i.eq("]") {
            continue;
        }
        let i = i.trim_end_matches(',');

        println!("{}", i);
        let t: Target = serde_json::from_str(&i).ok().expect("ERROR: [read_file] Serialize error!");
        task_send.send(t).unwrap();
    }


    for i in redict_rece {
        task_send.send(i).unwrap();
    }
}


fn get_html(name:String, domain: String, redict_send: Sender<Target>) {

    let mut dst = Vec::new();
    let mut c = Easy::new();
    // let url = gen_url(domain, urlprefix, urlsuffix);

    let url = domain;

    c.url(&url);
    c.show_header(true).ok().expect("Show Header Error!");
    c.timeout(Duration::new(20, 0));

    {
        let mut t = c.transfer();
        t.write_function(|data| {
            dst.extend_from_slice(data);
            Ok(data.len())
        }).ok().expect("ERROR: transfer");
        match t.perform() {
            Ok(_) => {},
            Err(_) => {
                println!("[DEBUG] ERROR: run perform");

                return;
            }
        }
    }

    let s;
    match String::from_utf8(dst) {
        Ok(v) => {s = v.to_string()},
        Err(_) => {
            println!("FromUtf8Error");
            return;
        }
    };

    let peer_ip = match c.primary_ip().unwrap() {
        Some(e) => {e.to_string()},
        None => {String::from("0.0.0.0")},
    };

    let redirect_url = match c.redirect_url().unwrap() {
        Some(v) => v.to_string(),
        None => "".to_string()
    };


    if !redirect_url.is_empty() {
        let t = Target {
            name:  name.clone(),
            domain: redirect_url.clone(),
        };
        redict_send.send(t).unwrap();
    }

    let status_code = c.response_code().ok().expect("ERROR: response_code");

    let data = ResultTarget{
        name: name.to_owned(),
        domain: url.to_owned(),
        status_code: status_code.to_owned(),
        banner: s.to_owned(),
        ip: peer_ip.to_owned(),
    };

    println!("name: {}, domain: {}, status_code: {}, ip:{}", data.name, data.domain, data.status_code, data.ip);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5df8459d891e6e4e020f12becf7a8434))

// target.json
```
[
  {"name": "google", "domain": "www.google.com"},
  {"name": "rust-lang", "domain": "doc.rust-lang.org"},
  {"name": "rust-lang", "domain": "rust-lang.org"}
]
```

**Comment by jonas-schievink** [comment] 2019-09-10 15:10
`for x in receiver` will block until the other side of the channel is dropped. How did you try to use `drop`?

**Comment by linkwik** [comment] 2019-09-11 02:19
> `for x in receiver` will block until the other side of the channel is dropped. How did you try to use `drop`?

In the get_html function, before return and after the sender is sent

**Comment by linkwik** [comment] 2019-09-11 02:20
> `for x in receiver` will block until the other side of the channel is dropped. How did you try to use `drop`?

What should I do ？

**Comment by sinkuu** [comment] 2019-09-11 02:46
It seems there is a circular-dependency: `gen_target` owns `task_send` and blocks on `for i in redirect_rece`, and the closure in `let run_task = thread::spawn(..)` owns `redirect_send` and blocks on `for i in task_rece`. You might need to reconsider the architecture.

**Comment by jonas-schievink** [comment] 2019-09-11 09:41
Yeah, this is not a bug in Rust, so closing. Feel free to ask on the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community though.

**Closed by jonas-schievink** 2019-09-11 09:41 UTC
