### ISSUE TITLE
std::net::Ipv6Addr::to_ipv4 maps ::1 to an invalid IP (0.0.0.1)

### ISSUE THREAD

**Issue by Drakulix** [rust-lang/rust#42174] opened 2017-05-23 15:20 UTC
`std::net::Ipv6Addr::to_ipv4` maps `::1` to an invalid IP (`0.0.0.1`)

I tried this code to make a very simple and crude IP filter (sufficient for my use case):

```rust
match
    match remote.ip() { // IP from web framework
        IpAddr::V4(ipv4) => Some(ipv4.octets()),
        IpAddr::V6(ipv6) => ipv6.to_ipv4().map(|ipv4| ipv4.octets())
    } {
        // ... other cases
        Some([127, 0, 0, _]) => {},
        x => {
            debug!("Invalid IP: {:?}", x);
            return Err(...);
        },
}
```

I expected to see this happen:

I expected `std::net::Ipv6Addr::to_ipv4` to return something like `Some(127.0.0.1)` for `::1` or at least `None`, because you could argue, that `::1` is not strictly the same as `127.0.0.1`, but then again loopback is loopback.

Instead, this happened:

But I did really not expect to get returned an **invalid** IPv4 address, which is why I consider this a bug, that has cost me far too much time.

## Meta

`rustc --version --verbose`:

```
rustc 1.19.0-nightly (81734e0e0 2017-05-22)
binary: rustc
commit-hash: 81734e0e06d24cf580dd5352c64d10110e4d3b7b
commit-date: 2017-05-22
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0
```

**Comment by nagisa** [comment] 2017-05-23 15:39
This works as documented:

> Converts this address to an IPv4 address. Returns None if this address is neither IPv4-compatible or IPv4-mapped.
> ::a.b.c.d and ::ffff:a.b.c.d become a.b.c.d

This conversion follows the RFC 4291 and will be the same everywhere.

**Comment by Drakulix** [comment] 2017-05-23 15:50
So returning an invalid IP Address is actually expected behavior?
In that case, I would very much like to see the documentation updated to state that and maybe to link to the RFC. I was not able to extract that Information from the documentation and I still think I was rightfully confused.

**Comment by nagisa** [comment] 2017-05-23 15:54
0.0.0.1 is a valid IPv4 address. See [RFC 6890](https://tools.ietf.org/html/rfc6890#section-2.2.2).

**Comment by Drakulix** [comment] 2017-05-23 16:15
Alright. Then sorry for filling an invalid issue, although I would like to see the docs to be improved for this method.

**Comment by Stebalien** [comment] 2017-05-24 00:35
Ideally, `to_ipv4` shouldn't translate IPv4 compatible addresses as they are deprecated and I have the feeling that including `::1` was a bug in the spec.

**Comment by Dylan-DPC** [comment] 2023-03-21 06:00
Closing this as it works as intended

**Closed by Dylan-DPC** 2023-03-21 06:00 UTC
Labels: T-libs-api, C-bug
