### ISSUE TITLE
error: internal compiler error

### ISSUE THREAD

**Issue by llxxbb** [rust-lang/rust#72805] opened 2020-05-31 03:31 UTC
error: internal compiler error: src\librustc_middle\ich\impls_ty.rs:94: StableHasher: unexpected region '_#90r

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:907:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (4bd32c980 2020-05-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `nature`.

**Comment by csmoe** [comment] 2020-05-31 03:51
Seems duplicate of https://github.com/rust-lang/rust/issues/72766
Could you append the backtrace?

**Comment by llxxbb** [comment] 2020-05-31 04:03
sorry, I had changed to stable and modified a lot, when change back to  nightly, it has gone.

**Comment by csmoe** [comment] 2020-05-31 04:09
Okay, thanks for your reporting.
 Feel free to reopen if this ice happens again, and don't forget to report with backtrace :)

**Closed by csmoe** 2020-05-31 04:09 UTC

**Comment by llxxbb** [comment] 2020-05-31 07:50
error: internal compiler error: src\librustc_middle\ich\impls_ty.rs:94: StableHasher: unexpected region '_#258r

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:907:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
error: internal compiler error: src\librustc_middle\ich\impls_ty.rs:94: StableHasher: unexpected region '_#258r

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:907:9
stack backtrace:
   6: std::panicking::rust_panic_with_hook
   7: <rustc_errors::json::Diagnostic::from_errors_diagnostic::BufWriter as std::io::Write>::flush
   8: rustc_errors::HandlerInner::err_count
   9: rustc_errors::Handler::bug
  10: rustc_middle::util::bug::bug_fmt
  11: rustc_middle::ty::walk::<impl rustc_middle::ty::subst::GenericArg>::walk_shallow
  12: rustc_middle::ty::walk::<impl rustc_middle::ty::subst::GenericArg>::walk_shallow
  13: rustc_middle::util::bug::bug_fmt
  14: rustc_middle::util::bug::bug_fmt
  15: rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::RegionKind>::hash_stable
  16: rustc_middle::ich::impls_syntax::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for [rustc_ast::ast::Attribute]>::hash_stable
  17: ZN12rustc_middle2ty3sty107_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_middle_ich_StableHashingContext_ctx_FOR_TyKind160_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc_middle..ich..hcx..StableHashingContext$GT$$u20$
  18: rustc_middle::ich::impls_syntax::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for [rustc_ast::ast::Attribute]>::hash_stable
  19: ZN12rustc_middle2ty3sty107_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_middle_ich_StableHashingContext_ctx_FOR_TyKind160_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc_middle..ich..hcx..StableHashingContext$GT$$u20$
  20: <rustc_trait_selection::traits::wf::Elaborate as core::fmt::Debug>::fmt
  21: <rustc_trait_selection::traits::util::TraitAliasExpansionInfo as core::fmt::Debug>::fmt
  22: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::suggestions::InferCtxtExt>::suggest_await_before_try
  23: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_selection_error
  24: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  25: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  26: rustc_typeck::check::FnCtxt::self_type_matches_expected_vid
  27: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  28: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  29: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  30: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  31: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  32: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  33: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  34: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt>::check_for_cast
  35: rustc_typeck::check::FnCtxt::check_decl_local
  36: rustc_typeck::check::FnCtxt::check_stmt
  37: rustc_typeck::check::FnCtxt::check_block_no_value
  38: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  39: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  40: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  41: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  42: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  43: rustc_typeck::check::FnCtxt::check_block_no_value
  44: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  45: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  46: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  47: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  48: rustc_typeck::check::FnCtxt::check_block_no_value
  49: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  50: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  51: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  52: <rustc_typeck::check::GatherLocalsVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  53: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  54: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  55: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  56: rustc_typeck::check::FnCtxt::self_type_matches_expected_vid
  57: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  58: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  59: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  60: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  61: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  62: <rustc_typeck::check::GatherLocalsVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  63: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  64: <rustc_typeck::check::fixup_opaque_types::FixupFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  65: <rustc_mir_build::hair::pattern::check_match::check_legality_of_bindings_in_at_patterns::AtBindingPatternVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  66: <rustc_ast::ast::Mutability as rustc_mir_build::hair::cx::expr::ToBorrowKind>::to_borrow_kind
  67: <rustc_passes::lib_features::LibFeatureCollector as rustc_hir::intravisit::Visitor>::visit_attribute
  68: <rustc_mir_build::build::expr::as_place::PlaceBuilder as core::convert::From<rustc_middle::mir::Local>>::from
  69: <rustc_mir_build::hair::pattern::check_match::check_legality_of_bindings_in_at_patterns::AtBindingPatternVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  70: <rustc_mir_build::build::ScopeId as core::fmt::Debug>::fmt
  71: <rustc_mir_build::build::matches::ArmHasGuard as core::fmt::Debug>::fmt
  72: <rustc_mir::transform::check_consts::ops::UnionAccess as core::fmt::Debug>::fmt
  73: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  74: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  75: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  76: <rustc_mir::transform::check_unsafety::UnusedUnsafeVisitor as rustc_hir::intravisit::Visitor>::visit_block
  77: <rustc_mir::borrow_check::places_conflict::PlaceConflictBias as core::fmt::Debug>::fmt
  78: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  79: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  80: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  81: rustc_mir::transform::run_passes
  82: <rustc_mir::borrow_check::places_conflict::PlaceConflictBias as core::fmt::Debug>::fmt
  83: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  84: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  85: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  86: rustc_mir::transform::run_passes
  87: <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt
  88: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  89: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  90: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  91: rustc_mir::borrow_check::provide
  92: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  93: rustc_hir::hir::Body::id
  94: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  95: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  96: <rustc_typeck::check::method::probe::ProbeScope as core::fmt::Debug>::fmt
  97: <rustc_hir::hir_id::HirId as rustc_typeck::check::writeback::Locatable>::to_span
  98: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::debug_node
  99: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::context::Lift for alloc::string::String>::lift_to_tcx
 100: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::context::Lift for rustc_target::asm::InlineAsmRegOrRegClass>::lift_to_tcx
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (4bd32c980 2020-05-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] type-checking `controller::act_store::duplicated_instance`
#1 [mir_built] building MIR for
#2 [unsafety_check_result] unsafety-checking `controller::act_store::duplicated_instance`
#3 [mir_const] processing `controller::act_store::duplicated_instance`
#4 [mir_validated] processing `controller::act_store::duplicated_instance`
#5 [mir_borrowck] borrow-checking `controller::act_store::duplicated_instance`
#6 [type_of] processing `controller::act_store::duplicated_instance::{{opaque}}#0`
#7 [check_mod_item_types] checking item types in module `rpc::actix`
#8 [analysis] running analysis passes on this crate
end of query stack
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: <rustc_errors::json::Diagnostic::from_errors_diagnostic::BufWriter as std::io::Write>::flush
   8: rustc_errors::HandlerInner::err_count
   9: rustc_errors::Handler::bug
  10: rustc_middle::util::bug::bug_fmt
  11: rustc_middle::ty::walk::<impl rustc_middle::ty::subst::GenericArg>::walk_shallow
  12: rustc_middle::ty::walk::<impl rustc_middle::ty::subst::GenericArg>::walk_shallow
  13: rustc_middle::util::bug::bug_fmt
  14: rustc_middle::util::bug::bug_fmt
  15: rustc_middle::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for rustc_middle::ty::sty::RegionKind>::hash_stable
  16: rustc_middle::ich::impls_syntax::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for [rustc_ast::ast::Attribute]>::hash_stable
  17: ZN12rustc_middle2ty3sty107_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_middle_ich_StableHashingContext_ctx_FOR_TyKind160_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc_middle..ich..hcx..StableHashingContext$GT$$u20$
  18: rustc_middle::ich::impls_syntax::<impl rustc_data_structures::stable_hasher::HashStable<rustc_middle::ich::hcx::StableHashingContext> for [rustc_ast::ast::Attribute]>::hash_stable
  19: ZN12rustc_middle2ty3sty107_DERIVE_rustc_data_structures_stable_hasher_HashStable_rustc_middle_ich_StableHashingContext_ctx_FOR_TyKind160_$LT$impl$u20$rustc_data_structures..stable_hasher..HashStable$LT$rustc_middle..ich..hcx..StableHashingContext$GT$$u20$
  20: <rustc_trait_selection::traits::wf::Elaborate as core::fmt::Debug>::fmt
  21: <rustc_trait_selection::traits::util::TraitAliasExpansionInfo as core::fmt::Debug>::fmt
  22: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::suggestions::InferCtxtExt>::suggest_await_before_try
  23: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_selection_error
  24: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  25: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_fulfillment_errors
  26: rustc_typeck::check::FnCtxt::self_type_matches_expected_vid
  27: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  28: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  29: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  30: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  31: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  32: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  33: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  34: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt>::check_for_cast
  35: rustc_typeck::check::FnCtxt::check_decl_local
  36: rustc_typeck::check::FnCtxt::check_stmt
  37: rustc_typeck::check::FnCtxt::check_block_no_value
  38: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  39: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  40: rustc_typeck::check::_match::<impl rustc_typeck::check::FnCtxt>::check_match
  41: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  42: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  43: rustc_typeck::check::FnCtxt::check_block_no_value
  44: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  45: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  46: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  47: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  48: rustc_typeck::check::FnCtxt::check_block_no_value
  49: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  50: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  51: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  52: <rustc_typeck::check::GatherLocalsVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  53: rustc_typeck::check::closure::<impl rustc_typeck::check::FnCtxt>::check_expr_closure
  54: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  55: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  56: rustc_typeck::check::FnCtxt::self_type_matches_expected_vid
  57: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  58: rustc_typeck::check::callee::<impl rustc_typeck::check::FnCtxt>::check_call
  59: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  60: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  61: rustc_typeck::check::expr::<impl rustc_typeck::check::FnCtxt>::check_expr_with_expectation
  62: <rustc_typeck::check::GatherLocalsVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  63: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  64: <rustc_typeck::check::fixup_opaque_types::FixupFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
  65: <rustc_mir_build::hair::pattern::check_match::check_legality_of_bindings_in_at_patterns::AtBindingPatternVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  66: <rustc_ast::ast::Mutability as rustc_mir_build::hair::cx::expr::ToBorrowKind>::to_borrow_kind
  67: <rustc_passes::lib_features::LibFeatureCollector as rustc_hir::intravisit::Visitor>::visit_attribute
  68: <rustc_mir_build::build::expr::as_place::PlaceBuilder as core::convert::From<rustc_middle::mir::Local>>::from
  69: <rustc_mir_build::hair::pattern::check_match::check_legality_of_bindings_in_at_patterns::AtBindingPatternVisitor as rustc_hir::intravisit::Visitor>::visit_pat
  70: <rustc_mir_build::build::ScopeId as core::fmt::Debug>::fmt
  71: <rustc_mir_build::build::matches::ArmHasGuard as core::fmt::Debug>::fmt
  72: <rustc_mir::transform::check_consts::ops::UnionAccess as core::fmt::Debug>::fmt
  73: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  74: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  75: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  76: <rustc_mir::transform::check_unsafety::UnusedUnsafeVisitor as rustc_hir::intravisit::Visitor>::visit_block
  77: <rustc_mir::borrow_check::places_conflict::PlaceConflictBias as core::fmt::Debug>::fmt
  78: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  79: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  80: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  81: rustc_mir::transform::run_passes
  82: <rustc_mir::borrow_check::places_conflict::PlaceConflictBias as core::fmt::Debug>::fmt
  83: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  84: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  85: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  86: rustc_mir::transform::run_passes
  87: <rustc_mir::interpret::validity::PathElem as core::fmt::Debug>::fmt
  88: <rustc_mir::transform::MirSource as core::fmt::Debug>::fmt
  89: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  90: <rustc_mir::borrow_check::type_check::ObligationAccumulator as core::fmt::Debug>::fmt
  91: rustc_mir::borrow_check::provide
  92: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  93: rustc_hir::hir::Body::id
  94: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  95: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  96: <rustc_typeck::check::method::probe::ProbeScope as core::fmt::Debug>::fmt
  97: <rustc_hir::hir_id::HirId as rustc_typeck::check::writeback::Locatable>::to_span
  98: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::debug_node
  99: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::context::Lift for alloc::string::String>::lift_to_tcx
 100: rustc_middle::ty::structural_impls::<impl rustc_middle::ty::context::Lift for rustc_target::asm::InlineAsmRegOrRegClass>::lift_to_tcx
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (4bd32c980 2020-05-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck_tables_of] type-checking `controller::act_store::duplicated_instance`
#1 [mir_built] building MIR for
#2 [unsafety_check_result] unsafety-checking `controller::act_store::duplicated_instance`
#3 [mir_const] processing `controller::act_store::duplicated_instance`
#4 [mir_validated] processing `controller::act_store::duplicated_instance`
#5 [mir_borrowck] borrow-checking `controller::act_store::duplicated_instance`
#6 [type_of] processing `controller::act_store::duplicated_instance::{{opaque}}#0`
#7 [check_mod_item_types] checking item types in module `rpc::actix`
#8 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error; 1 warning emitted

error: could not compile `nature`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error; 1 warning emitted

error: build failed

**Comment by csmoe** [comment] 2020-05-31 07:53
@llxxbb thanks :)
confirmed, this ice is duplicated of https://github.com/rust-lang/rust/issues/72766, which has a pending fix.
