### ISSUE TITLE
rustdoc does not render some `where` clauses on functions

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#67366] opened 2019-12-17 11:40 UTC
For example, the docs for [`pointer::offset`](https://doc.rust-lang.org/std/primitive.pointer.html?search=#method.offset) do not include the `where T: Sized` bound, which is very significant here.

(I could not find any existing issue about this, but there may well be one already since this seems pretty easy to spot)

**Comment by ollie27** [comment] 2019-12-31 00:36
Duplicate of #24183

**Closed by ollie27** 2019-12-31 00:36 UTC
Labels: C-bug, T-rustdoc
