### ISSUE TITLE
no type-dependent def ICE

### ISSUE THREAD

**Issue by cavedweller** [rust-lang/rust#52807] opened 2018-07-28 16:19 UTC
```error: internal compiler error: librustc/middle/dead.rs:102: no type-dependent def for method

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:580:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::bug_fmt
  14: <rustc::middle::dead::MarkSymbolVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  15: rustc::hir::intravisit::walk_expr
  16: <rustc::middle::dead::MarkSymbolVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  17: rustc::hir::intravisit::walk_expr
  18: <rustc::middle::dead::MarkSymbolVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  19: rustc::hir::intravisit::walk_block
  20: <rustc::middle::dead::MarkSymbolVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  21: <rustc::middle::dead::MarkSymbolVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  22: rustc::hir::intravisit::walk_item
  23: rustc::middle::dead::check_crate
  24: rustc::util::common::time
  25: rustc::ty::context::tls::enter_context
  26: <std::thread::local::LocalKey<T>>::with
  27: rustc::ty::context::TyCtxt::create_and_enter
  28: rustc_driver::driver::compile_input
  29: rustc_driver::run_compiler_with_pool
  30: <scoped_tls::ScopedKey<T>>::set
  31: <scoped_tls::ScopedKey<T>>::set
  32: syntax::with_globals
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  34: __rust_maybe_catch_panic
  35: rustc_driver::run
  36: rustc_driver::main
  37: std::rt::lang_start::{{closure}}
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
  40: std::rt::lang_start_internal
  41: main
  42: __libc_start_main
  43: _start
query stack during panic:
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C linker=/usr/local/google/home/bwb/fuchsia/buildtools/linux-x64/clang/bin/clang -C incremental -C link-arg=--target=x86_64-unknown-fuchsia -C link-arg=--sysroot=/usr/local/google/home/bwb/fuchsia/out/release-x64/sdks/zircon_sysroot/arch/x64/sysroot --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

**Comment by varkor** [comment] 2018-07-28 17:13
Is it possible to post a snippet of code that produces this error?

**Comment by cavedweller** [comment] 2018-07-29 14:39
sorry, I should have posted the snippet. I'll try to hunt down that code. also, cc: @cramertj since I might have shown him the snippet at the time.

**Comment by varkor** [comment] 2018-07-29 14:54
It's the same kind of error as https://github.com/rust-lang/rust/issues/52815, though in a different location.

**Comment by dtolnay** [comment] 2018-08-13 08:41
I am closing because I don't expect it will be productive to debug this without a snippet to reproduce the error. Let's reopen or open a new issue if we run into this again.

**Closed by dtolnay** 2018-08-13 08:41 UTC
Labels: I-ICE
