### ISSUE TITLE
rustc crashes if main is wrongly defined by the user

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#54930] opened 2018-10-09 11:20 UTC
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6373ceb34c1fd2de892861530777d98d

**Comment by Centril** [comment] 2018-10-09 21:00
I'm going to speculatively add `I-ICE` to this.

**Comment by euclio** [comment] 2018-10-23 18:43
Looks like a duplicate of #9307.

**Comment by estebank** [comment] 2019-05-08 01:08
This is certainly a duplicate of #9307.

**Closed by estebank** 2019-05-08 01:08 UTC
Labels: I-ICE
