### ISSUE TITLE
Error suggestions for import contain erroneous `derive`

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#44210] opened 2017-08-31 06:01 UTC
E.g.,
```
error[E0412]: cannot find type `Path` in this scope
  --> src/actions/compiler_message_parsing.rs:77:55
   |
77 | fn make_suggestions(message: &CompilerMessage, file: &Path) -> Vec<Suggestion> {
   |                                                       ^^^^ not found in this scope
   |
help: possible candidates are found in other modules, you can import them into scope
   |
20 | #[derive(use build::rustc::rustc::hir::Path;
   |
20 | #[derive(use build::rustc::syntax::ast::Path;
   |
20 | #[derive(use std::path::Path;
```

cc @oli-obk

**Comment by nrc** [comment] 2017-08-31 06:02
The first non-comment, non-use line in the file is `#[derive(Debug)]`, which might be where this is coming from?

**Comment by nikomatsakis** [comment] 2017-09-14 20:27
Closing as duplicate of https://github.com/rust-lang/rust/issues/44566.

**Closed by nikomatsakis** 2017-09-14 20:27 UTC
Labels: A-diagnostics, C-bug, regression-from-stable-to-beta, T-compiler
