### ISSUE TITLE
Generic associated consts can't currently be used to parameterize fixed array lengths

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#42863] opened 2017-06-23 17:02 UTC
The following program works, proving that associated consts ought to be able to be used to successfully parameterize the size of fixed-length arrays:
```rust
#![feature(associated_consts)]

trait Const {
    const VALUE: usize;
}

struct Foo;

impl Const for Foo {
    const VALUE: usize = 4;
}

fn test(x: [u8; Foo::VALUE]) {
    for _ in x.iter() {
        println!("hello");
    }
}

fn main() {
    let x = [1,2,3,4];
    test(x);
}
```
The following program ought to compile as well, but doesn't:
```rust
#![feature(associated_consts)]

trait Const {
    const VALUE: usize;
}

fn test<T: Const>(_: [u8; T::VALUE]) {}

fn main() {}
```
Output:
```
rustc 1.20.0-nightly (ab5bec255 2017-06-22)
error[E0599]: no associated item named `VALUE` found for type `T` in the current scope
 --> <anon>:7:27
  |
7 | fn test<T: Const>(_: [u8; T::VALUE]) {}
  |                           ^^^^^^^^
  |
  = help: items from traits can only be used if the trait is implemented and in scope
  = note: the following trait defines an item `VALUE`, perhaps you need to implement it:
          candidate #1: `Const`
```
Slightly altering the program to more fully qualify the associated const also doesn't work, though yields a different error message:
```rust
#![feature(associated_consts)]

trait Const {
    const VALUE: usize;
}

fn test<T: Const>(_: [u8; <T as Const>::VALUE]) {}

fn main() {}
```
Output:
```
rustc 1.20.0-nightly (ab5bec255 2017-06-22)
error[E0277]: the trait bound `T: Const` is not satisfied
 --> <anon>:7:27
  |
7 | fn test<T: Const>(_: [u8; <T as Const>::VALUE]) {}
  |                           ^^^^^^^^^^^^^^^^^^^ the trait `Const` is not implemented for `T`
  |
  = help: consider adding a `where T: Const` bound
  = note: required by `Const::VALUE`
```
Presumably both these programs should work, yes?

**Comment by bstrie** [comment] 2017-06-23 17:02
cc @eddyb, @ubsan

**Comment by ubsan** [comment] 2017-06-23 18:27
It should be written "associated consts can't be used as an argument to fixed size arrays" :)

parameters != arguments :P

**Comment by eddyb** [comment] 2017-06-23 18:45
This is a known issue mentioned in the tracking issue for associated constants.

**Comment by bstrie** [comment] 2017-06-23 18:58
Indeed, this appears to be similar to #39211 and #34344, though the fact there are four different compiler error messages between these three issues suggests these are exercising different paths. Would be nice to consolidate all four code examples into one issue for the sake of regression tests, if someone wants to arbitrarily pick one.

**Comment by Alfriadox** [comment] 2019-03-29 12:26
Is this any closer to being fixed?
Is there anything I can do to help?

**Comment by eddyb** [comment] 2019-03-30 10:26
Closing as duplicate of #43408.

@Alfriadox The canonical issue is #43408, and while it's closer to being fixed, @nikomatsakis hasn't really let people attack the problem directly for the past few years, so it's been a waiting game.
(The solution involves "lazy normalization", a slowly approaching rustc typesystem feature)

**Closed by eddyb** 2019-03-30 10:26 UTC
Labels: A-associated-items, C-bug, T-compiler
