### ISSUE TITLE
Replace ./configure with a script that generates config.toml

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#42051] opened 2017-05-17 08:29 UTC
The rustbuild code is really bloated with code handling options from both `config.mk` and `config.toml`. We can silently replace configure with a script that generates TOML instead.

That should be possible with bash, but we can also use Python due to it's advantage like being cross platform, and a more general purpose language.

**Comment by TimNN** [comment] 2017-05-17 08:35
Duplicate of #40730

**Closed by TimNN** 2017-05-17 08:35 UTC
