### ISSUE TITLE
Documentation uses wrong anchors for Modules/Structs/Enums/Traits/Types

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rust#72909] opened 2020-06-02 07:59 UTC
# Introduction
The documentation generated by _rustdoc_ has a feature, which I use fairly often: the links to the generated item groups, e.g. Re-exports, Structs and Enums in this screenshot: 
![image](https://user-images.githubusercontent.com/31166235/83493904-c63ace80-a4b5-11ea-9243-24d8242446f1.png)
This feature is essential, if a crate or module has a long explanatory introduction, which you already read and you want to go down to the traits/structs/modules/....

# Problem
If a user uses a heading like `# Traits`, the aforementioned links lead to the wrong anchor, i.e. to the heading in the top-level documentation instead of the list of traits. See:
![rustdoc anchors](https://user-images.githubusercontent.com/31166235/83494608-d1422e80-a4b6-11ea-9e3c-16971f79317a.gif)
As you can see, the links to "Modules" and "Enums" are working, but "Trait" leads to the crate level documentation. The shown documentation can be found [here](https://docs.rs/embedded-hal/0.2.3/embedded_hal).

# Observations
I feel like the anchors for the item groups should not be called `#modules`, `#traits`, etc. Instead a name, that won't be used by crate authors, should be used (e.g. `rustdoc_item_group_traits`).

Interestingly, rustdoc doesn't generate two `#traits` anchors. Instead the second one is called [`#traits-1`](https://docs.rs/embedded-hal/0.2.3/embedded_hal/#traits-1). So it might also be possible to use the anchor with the highest number after it, but I assume, that this is harder than just using different names.

**Comment by jyn514** [comment] 2020-11-05 04:26
Duplicate of https://github.com/rust-lang/rust/issues/55791

**Comment by jyn514** [comment] 2020-11-05 04:27
> Interestingly, rustdoc doesn't generate two #traits anchors. Instead the second one is called #traits-1. So it might also be possible to use the anchor with the highest number after it, but I assume, that this is harder than just using different names.

Rustdoc currently does not parse HTML at all. So I don't think parsing the HTML just to get the IDs is the best idea.

**Closed by jyn514** 2020-11-05 04:26 UTC
Labels: C-bug, T-rustdoc
