### ISSUE TITLE
Import suggestions misplaced when beginning of file is #[tokio::main]

### ISSUE THREAD

**Issue by scrabsha** [rust-lang/rust#89810] opened 2021-10-12 11:44 UTC
Given the following code:

```rust
#[tokio::main]
async fn main() {
    let _: PathBuf = todo!();
}
```

([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0e0f7f57375dc69fd67bec24959a68c))

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0412]: cannot find type `PathBuf` in this scope
 --> src/main.rs:3:12
  |
3 |     let _: PathBuf = todo!();
  |            ^^^^^^^ not found in this scope
  |
help: consider importing this struct
  |
2 | async use std::path::PathBuf;
  |       +++++++++++++++++++++++

For more information about this error, try `rustc --explain E0412`.
error: could not compile `playground` due to previous error
```

`async` imports look cool tbh, but that's not valid Rust.
This happens on stable, beta and nightly.

Ideally the `use std::path::PathBuf` should be placed in line 1 and before the `async` keyword.

I tried to keep the issue title and description super specific to this situation as I don't have time to investigate with other macros. Feel free to report similar problems so that I can make it more general.

**Comment by ehuss** [comment] 2021-10-12 14:05
I think this is a duplicate of #86241 which has some comments on why this happens.

@oli-obk I think this issue was known when this was added in #44215.  The `UsePlacementFinder` is unable to deal with active attributes since they are removed from the AST, and the span information is lost. There is a fixme for it [here](https://github.com/ehuss/rust/blob/2c7bc5e33c25e29058cbafefe680da8d5e9220e9/src/test/ui/resolve/use_suggestion_placement.rs#L13-L16) and [here](https://github.com/rust-lang/rust/blob/9475e609b8458fff9e444934a6017d2e590642cf/compiler/rustc_resolve/src/lib.rs#L347).

Recently, macros have been added to the HIR in #88019.  I'm not sure if that helps, but I think would be a start into maybe investigating.

**Comment by oli-obk** [comment] 2022-07-07 10:41
This has been resolved

**Closed by oli-obk** 2022-07-07 10:41 UTC
Labels: A-diagnostics, T-compiler
