### ISSUE TITLE
Missing coercion of function pointer argument

### ISSUE THREAD

**Issue by letheed** [rust-lang/rust#53876] opened 2018-09-01 02:31 UTC
When using `drain_filter`, passing a function directly I got the following error:

```
expected signature of `for<'r> fn(&'r mut Foo) -> _
found signature of `for<'r> fn(&'r Foo) -> _
```

Workaround is trivial with closure but I was a bit surprised `fn(&Foo)` doesn't coerce to `fn(&mut Foo)`. Any reason that's not allowed?

I've searched the tracker but couldn't find a similar issue, apologies if this is a duplicate.

**Comment by Havvy** [comment] 2018-09-01 07:25
I want to say that this coercion was in Rust before version 1.0, but removed because it caused too much confusion. But my memory of that era is getting fuzzier with each passing year.

**Comment by jonas-schievink** [comment] 2019-04-21 22:41
Closing as working as intended. Adding the coercion back would likely need an RFC.

**Closed by jonas-schievink** 2019-04-21 22:41 UTC
