### ISSUE TITLE
poor error message with question mark applied to non-Result

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#32175] opened 2016-03-10 15:50 UTC
This code

``` rust
#![feature(question_mark)]

fn main() {
    42?;
}
```

prints the error

```
<anon>:4:5: 4:9 error: mismatched types:
 expected `_`,
    found `core::result::Result<_, _>`
(expected integral variable,
    found enum `core::result::Result`) [E0308]
<anon>:4     42?;
             ^~~~
```

which is confusing. The error is that I put a non-Result where a Result was expected, but the error says the opposite.

cc @japaric

**Comment by durka** [comment] 2016-03-10 17:12
This is because it expands to

```rust
fn main() {
    match 42 {
        Err(err) => return Err(From::from(err)),
        Ok(val) => val,
    };
}
```

so the error comes from the match arms. I know the expansion is done before typechecking, but a possible way to fix it is with type ascription. This expansion produces a better error:

```rust
#![feature(type_ascription)]

fn main() {
    match 42: Result<_,_> {
        Err(err) => return Err(From::from(err)),
        Ok(val) => val,
    };
}
```

**Comment by japaric** [comment] 2016-03-10 17:30
I think we can swap the expected and found types for these errors when they originate from desugared syntax and seems like we do something like that for [if let](https://github.com/rust-lang/rust/blob/4b87655e69a6d07f03b104caaec80a042ad40bf1/src/librustc_typeck/check/_match.rs#L547-L551). I'll give it a try.

**Comment by durka** [comment] 2016-03-10 17:34
@japaric 

Heh, but if you switch them what of this code?

```rust
#![feature(question_mark, type_ascription)]

fn main() {
    (42: Result<_,_>)?;
}
```

**Comment by pnkfelix** [comment] 2016-06-03 16:21
cc me

**Comment by cbreeden** [comment] 2016-09-09 14:31
I am now seeing a new error message.  @durka, how do you feel about this?

```
error[E0277]: the trait bound `{integer}: std::ops::Carrier` is not satisfied
 --> src/main.rs:4:5
  |
4 |     42?;
  |     ^^^ trait `{integer}: std::ops::Carrier` not satisfied
  |
  = help: the following implementations were found:
  = help:   <std::ops::_DummyErrorType as std::ops::Carrier>
  = help:   <std::result::Result<U, V> as std::ops::Carrier>
  = note: required by `std::ops::Carrier::translate`

error[E0277]: the trait bound `(): std::ops::Carrier` is not satisfied
 --> src/main.rs:4:5
  |
4 |     42?;
  |     ^^^ trait `(): std::ops::Carrier` not satisfied
  |
  = note: required by `std::ops::Carrier::from_error`
```

**Comment by durka** [comment] 2016-09-09 17:26
That's a pretty terrible error message from a user perspective.

**Comment by carols10cents** [comment] 2016-10-11 22:24
Just to clarify: the examples in this issue are *also* showing the error messages when you try to use `?` in a function that does not return a `Result`, which is #35946/#36988, but this issue is for trying to *call* `?` on a non-`Result`, correct? To distinguish this issue from the other issues, I think a better example would be:

```rust
fn something() -> Result<(), ()> {
    42?;
    Ok(())
}
```

which currently results in this single error:

```
error[E0277]: the trait bound `{integer}: std::ops::Carrier` is not satisfied
 --> src/main.rs:5:5
  |
5 |     42?;
  |     ^^^ trait `{integer}: std::ops::Carrier` not satisfied
  |
  = help: the following implementations were found:
  = help:   <std::ops::_DummyErrorType as std::ops::Carrier>
  = help:   <std::result::Result<U, V> as std::ops::Carrier>
  = note: required by `std::ops::Carrier::translate`
```

**Comment by cengizIO** [comment] 2017-05-09 22:27
Hello
Any updates? I've just bumped into this.

cc @steveklabnik

**Comment by steveklabnik** [comment] 2017-05-09 22:34
hey @cengizIO 👋 

Not yet, no. There's some linked issues/PRs in the comments above, but it has not yet been fixed.

**Comment by nodakai** [comment] 2017-07-16 14:06
If #37671 had to be closed as a duplicate of #35946, so does this

**Comment by carols10cents** [comment] 2017-07-16 23:02
@nodakai no, this issue is for using the `?` on something that doesn't support the question mark operator, and this can happen in a function that *does* have a return type that supports a question mark. Please see my example in [this comment](https://github.com/rust-lang/rust/issues/32175#issuecomment-253065168), this is a distinct issue from both #37671 and #35946.

**Comment by estebank** [comment] 2018-02-05 21:08
[Current output](https://play.rust-lang.org/?gist=a85b46af1457aa780a37da94e5409899&version=nightly):

```
error[E0277]: the `?` operator can only be applied to values that implement `std::ops::Try`
 --> src/main.rs:2:5
  |
2 |     42?;
  |     ^^^ the `?` operator cannot be applied to type `{integer}`
  |
  = help: the trait `std::ops::Try` is not implemented for `{integer}`
  = note: required by `std::ops::Try::into_result`
```

**Closed** 2018-02-19 08:56 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
