### ISSUE TITLE
println! of an out of bound element in an array segfaults on Mac OS Yosemite

### ISSUE THREAD

**Issue by yoshrc** [rust-lang/rust#52139] opened 2018-07-07 19:02 UTC
```
// array_out_of_bound.rs
fn main() {
    let a = [1];
    println!("{}", a[1]);
}
```

This program segfaults on Mac OS 10.10.5.

```
$ rustc --version
rustc 1.27.0 (3eda71b00 2018-06-19)
$ rustc array_out_of_bound.rs 
$ ./array_out_of_bound 
zsh: segmentation fault  ./array_out_of_bound
```

I tried compiling and executing on Debian 9.4, which printed panic message correctly.

Without `println!`, Mac OS prints panic message.

```
// array_out_of_bound.rs
fn main() {
    let a = [1];
    a[1];
}
```

```
$ rustc array_out_of_bound.rs 
$ ./array_out_of_bound 
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', array_out_of_bound.rs:3:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sfackler** [comment] 2018-07-07 21:38
Duplicate of #51758

**Closed by sfackler** 2018-07-07 21:38 UTC
