### ISSUE TITLE
Match and binary operators in block body

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust#43338] opened 2017-07-19 17:38 UTC
Just ran across this issue and wondered, whether this is some kind of syntax limitation or a parser bug:

The following code does not compile:
```rust
let x = { match 2 { _ => 1 } - 2 };
```
([playground](https://play.rust-lang.org/?gist=a05fd06a07c4f4abda29a6075a4d9a7b&version=stable))

The error message is somewhat confusing:

```
  Compiling playground v0.0.1 (file:///playground)
error[E0308]: mismatched types
 --> src/main.rs:2:15
  |
2 |     let x = { match 2 { _ => 1 } - 2 };
  |               ^^^^^^^^^^^^^^^^^^ expected (), found integral variable
  |
  = note: expected type `()`
             found type `{integer}`

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

I would have expected it to be equivalent to the following code, which does work (evaluating `x` to `-1` as expected):
```rust
let x = match 2 { _ => 1 } - 2;
```

**Comment by durka** [comment] 2017-07-19 19:26
I think this is the same as #13012 and #17930?

**Comment by aepsil0n** [comment] 2017-07-19 20:41
Ah, I almost thought something like this must be the reason. Still feels a little surprising, but so be it.

So… close as duplicate then?

**Comment by Mark-Simulacrum** [comment] 2017-07-19 21:14
Yeah, this seems to be a duplicate of the latter at least, closing.

**Closed by Mark-Simulacrum** 2017-07-19 21:14 UTC
Labels: A-parser
