### ISSUE TITLE
mod names that collide with primitive types should link to primitive type docs

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#28014] opened 2015-08-26 13:48 UTC
A (personal) user experience:

While looking for matching functionality on `str`, I went to the following link:

  * `mod str`: https://doc.rust-lang.org/std/str/index.html
  * note that this is distinct from primitive `str`: https://doc.rust-lang.org/std/primitive.str.html
    * you may not realize that at first glance; see further commentary below
  * note also that the mod str link occurs first in the search results (primitive second): https://doc.rust-lang.org/std/str/?search=str

The mod str documentation, at first blush, seems promising; it describes the `str` type quickly, shows examples of `&str` and discusses its representation.  It then lists a bunch of structs that seem promising.  Things like `struct Matches` "created with the method `.matches()`"

But then I see no method list.  And the text "created with the method `.matches()`" does not have a hyperlink to that method.  Following the link to the page for `struct Matches` does not help.  (I can imagine reasons why we would not want to flood the embedded identifiers with hyperlinks; I'm just pointing out that one reasonable guess at how to find this method does not work out.)

Anyway, perhaps a lot of this confusion would be reduced if, at the very beginning of the documentation for `mod str`, we included a prominent link to the primitive `str` documentation page, which *does* have all of these methods.

----

But, there is a twist (which perhaps should be a different bug).

  * `mod str`: https://doc.rust-lang.org/std/str/index.html
  * note that this is distinct from primitive `str`: https://doc.rust-lang.org/std/primitive.str.html

Both of these pages start off with the exact same text.  Apart from the respective titles ("Module std::str" versus "Primitive Type str"), there is no visible difference in my web browser which is filling its vertical space on my laptop, because the differences only start after the "Representation" section, and I need to scroll to see that.

This is not great, because someone who is following links trying to find the right page after starting from the `mod str` docs might reasonably think that this link took them *back to* the `mod str` docs.

**Comment by pnkfelix** [comment] 2015-08-26 13:50
(I don't know if there's some broad policy decision here about the formatting of documentation for the std library, or if the real bug here is that we should be collapsing these two pages together in `rustdoc`'s output, which seems like a reasonable hack to me, but I'm not a libs guy.  :)  )

**Comment by steveklabnik** [comment] 2015-08-26 14:09
I _think_ this is a duplicate of a rustdoc bug, but I'm not sure.

**Comment by steveklabnik** [comment] 2015-08-26 14:10
Note that on nightly, we do differentiate: 
![2015-08-26-101001_702x136_scrot](https://cloud.githubusercontent.com/assets/27786/9495650/95f70042-4bda-11e5-839f-c0634de1056d.png)

So this will be getting better in the future.

**Comment by nixpulvis** [comment] 2015-08-26 17:55
Just my personal experience as I've been learning the language. Right now there are two place with partially duplicated documentation for `str`. There are a few ways this could be improved but one way I thought of could be to allow primitives in modules as a special category above struct.

I'm not sure how much of a change structurally this would be, but it makes sense to me to have the traits, structs, functions and types for `str` all in the same place as the primitive implementation.

**Comment by steveklabnik** [comment] 2015-10-07 16:50
This has been fixed, blocks like this have been placed in the docs of all the primitive types
![2015-10-07-125014_328x146_scrot](https://cloud.githubusercontent.com/assets/27786/10344565/f6f1298a-6cf1-11e5-8c2e-33af7994ad27.png)

**Comment by steveklabnik** [comment] 2015-11-04 09:25
I forgot to close!

**Closed by steveklabnik** 2015-11-04 09:25 UTC
Labels: A-docs
