### ISSUE TITLE
Cannot use ty followed by `>>` on macro

### ISSUE THREAD

**Issue by thelink2012** [rust-lang/rust#25274] opened 2015-05-10 18:49 UTC
Using `ty` followed by `>>` doesn't work in a macro but it does works when followed by `> >` instead. This seems very like one of the old C++03 template issues.

Using `>>`: http://is.gd/KTICUL

```
macro_rules! test {
    (
        fn fun() -> Option<Box<$t:ty>>;
    ) => {
        fn fun(x: $t) -> Option<Box<$t>>
        { Some(Box::new(x)) }
    }
}

test! {
    fn fun() -> Option<Box<i32>>;
}

fn main() {
    fun(0).unwrap();
}
```

Gives

```
<anon>:4:32: 4:37 error: `$t:ty` is followed by `>>`, which is not allowed for `ty` fragments
<anon>:4         fn fun() -> Option<Box<$t:ty>>;
                                        ^~~~~
```

Using `> >` instead of `>>` fixes it: http://is.gd/gSD3MR
## Meta

All the tests were conducted on the playpen using the nightly and beta option (no difference) so I'm not sure about the version but the issue also happens on my local installation `rustc 1.0.0-beta.3 (5241bf9c3 2015-04-25) (built 2015-04-25)` _(yep a bit outdated but cba to update eh)_.

**Comment by steveklabnik** [comment] 2016-11-29 20:14
Triage: no change

**Comment by keeperofdakeys** [comment] 2016-12-15 08:25
This might be fixed now
ping @jseyfried

**Comment by jseyfried** [comment] 2016-12-15 09:02
This is still a bug -- I believe the issue is that the follow set checker does not allow `>>` after `$t:tt`.
cc @leotestard

**Comment by LeoTestard** [comment] 2016-12-15 14:50
@jseyfried: I guess you meant `ty` instead of `tt`? Indeed, it seems to me that it's a bug since `>>` can already occur umambiguously after a type in the grammar so it should be added to the FOLLOW set.

I'm not sure what the procedure is for adding tokens to FOLLOW sets. Should we go through the RFC process or just assume that it's a bug in the current design and just make a PR for it?

**Comment by jseyfried** [comment] 2016-12-15 21:25
@LeoTestard 
> I guess you meant `ty` instead of `tt`?

Yeah, edited.

> I'm not sure what the procedure is for adding tokens to FOLLOW sets.

I think we should assume it is a bug and make a PR to fix. Adding a comment on the RFC PR or tracking issue would probably be a good idea, but I don't think we need to go through the RFC process.

**Closed** 2018-10-25 17:44 UTC
Labels: A-grammar, A-macros, C-feature-request
