### ISSUE TITLE
when i build the project, have an error: could not compile 'node-cli'. what can i do?

### ISSUE THREAD

**Issue by wjy19990622** [rust-lang/rust#66112] opened 2019-11-05 09:02 UTC
41:     0x7ff01c8696db - start_thread
  42:     0x7ff01c18688f - __clone
  43:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (2477e2493 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `node-cli`.

**Comment by wjy19990622** [comment] 2019-11-05 09:02
but when i check, it done ok.

**Comment by bkchr** [comment] 2019-11-05 09:12
Duplicate of: https://github.com/rust-lang/rust/issues/65462

**Closed** 2019-11-05 10:29 UTC
