### ISSUE TITLE
ICE in trans::type_of::in_memory_type_of from Option<str> in FFI

### ISSUE THREAD

**Issue by geofft** [rust-lang/rust#25637] opened 2015-05-20 04:26 UTC
The following code [ICEs in nightly on play.rust-lang.org](https://play.rust-lang.org/?gist=e60dc1ef64e84de09aae&version=nightly), as well as in 1.0 stable:

```rust
extern {
    fn foo(x: Option<str>);
}
fn main() {
}
```

```
<anon>:2:15: 2:26 warning: found type without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(...)] attribute to the type, #[warn(improper_ctypes)] on by default
<anon>:2     fn foo(x: Option<str>);
                       ^~~~~~~~~~~
<anon>:2:5: 2:28 warning: foreign function is never used: `foo`, #[warn(dead_code)] on by default
<anon>:2     fn foo(x: Option<str>);
             ^~~~~~~~~~~~~~~~~~~~~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Unexpected type returned from struct_tail: core::option::Option<str> for ty=core::option::Option<str>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/trans/type_of.rs:354
```

Between this and #25581, I'm increasingly believing that Rust should firmly disallow non-C-compatible types in `extern` functions, not merely lint on them. `extern "C"` means to use the C ABI, and there *is no* C ABI support for passing slices, `str`s, etc. around.

**Comment by arielb1** [comment] 2015-05-20 16:54
Duplicate of #25388.

**Closed** 2015-05-26 16:00 UTC
Labels: A-dst, I-ICE
