### ISSUE TITLE
Confusing error message on unspecific `collect()`

### ISSUE THREAD

**Issue by devonhollowood** [rust-lang/rust#38169] opened 2016-12-05 02:59 UTC
In the following code, `rustc` can't determine what type `collect()` should return:

```rust
fn main() {
    let line = "1 2 3";
    let nums: Vec<u64> = line.split_whitespace()
        .map(|num| num.parse())
        .collect()
        .unwrap();
    println!("{:?}", nums);
}
```

However, the error message emitted by `rustc` is:

```
rustc 1.13.0 (2c6933acc 2016-11-07)
error: the type of this value must be known in this context
 --> <anon>:3:26
  |
3 |     let nums: Vec<u64> = line.split_whitespace()
  |                          ^

error: aborting due to previous error
```
which is not really instructive in solving the issue: it makes it look like the type of `line` needs to be specificed, when the type of `line` is clearly `&str`. ([playground link](https://is.gd/vX6O6Z))

Instead, it would be nice if the compiler emitted an error message informing the user that it can't deduce the type to be returned by `collect()`. Moving the caret to point to `collect()` would probably be sufficient.

**Comment by nagisa** [comment] 2016-12-05 07:07
The span here is pointing to the whole expression: `line.split_whitespace().map(|num| num.parse()).collect().unwrap()`, but since it is split over multiple lines we hit the well-known issue ith dislpaying multiline spans.

cc @jonathandturner do you know what issue is this duplicate of?

**Comment by bluss** [comment] 2016-12-05 08:41
Error looks like this in `rustc 1.15.0-nightly (28d6623bc 2016-12-03)`

```rust
error: the type of this value must be known in this context
 --> spanerror1.rs:3:26
  |
3 |       let nums: Vec<u64> = line.split_whitespace()
  |  __________________________^ starting here...
4 | |         .map(|num| num.parse())
5 | |         .collect()
6 | |         .unwrap();
  | |_________________^ ...ending here

error: aborting due to previous error
```

**Comment by devonhollowood** [comment] 2016-12-05 22:01
@bluss That is much more clear. Glad to hear a fix is in the pipeline!

**Comment by devonhollowood** [comment] 2016-12-08 00:25
I'm not sure what the `rust-lang` policy is for closing issues--should I close this one, since a fix is already on nightly?

**Comment by bluss** [comment] 2016-12-08 13:00
Sure, when it's fixed in nightly it can be closed. But new issues about improving this error message are welcome, just use the current nightly's behaviour as the starting point.

**Closed by bluss** 2016-12-08 13:00 UTC
