### ISSUE TITLE
 impl Trait feature is not make code easy

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust#47348] opened 2018-01-11 08:42 UTC
```rust
#![feature(conservative_impl_trait, universal_impl_trait)]

use std::ops::Sub;

trait Trait: Sub + Copy {}

impl Trait for i32{}

fn test0(foo: impl Trait) -> <impl Trait as std::ops::Sub>::Output {
    foo - foo
}

fn test1<T: Sub + Copy>(foo: T) -> T::Output {
    foo - foo
}

fn main() {
    let foo = test0(1);
    let bar = test1(1);
    println!("{:?}", bar);
}
```
Only the `bar` can be debug.

**Comment by ExpHP** [comment] 2018-01-23 21:58
```rust
fn test0(foo: impl Trait) -> <impl Trait as std::ops::Sub>::Output {
    foo - foo
}
```

Should this even compile?  I would have figured that the `impl Trait` in the output type should be considered ambiguous.

**Comment by ExpHP** [comment] 2018-02-28 19:15
#48084 makes the snippet no longer compile.

```
   Compiling playground v0.0.1 (file:///playground)
error[E0667]: `impl Trait` is not allowed in path parameters
 --> src/main.rs:9:31
  |
9 | fn test0(foo: impl Trait) -> <impl Trait as std::ops::Sub>::Output {
  |                               ^^^^^^^^^^
```

That said, I can see what originally led the author to write this signature; observe the error message for an incorrect return type:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0308]: mismatched types
  --> src/main.rs:10:5
   |
9  | fn test0(foo: impl Trait)  {
   |                            - possibly return type missing here?
10 |     foo - foo
   |     ^^^^^^^^^ expected (), found associated type
   |
   = note: expected type `()`
              found type `<impl Trait as std::ops::Sub>::Output`
```

**Comment by jyn514** [comment] 2021-07-07 04:38
Triage: the error message for `foo0` is now
```
error[E0308]: mismatched types
  --> src/main.rs:10:5
   |
9  | fn test0(foo: impl Trait) {
   |                           - possibly return type missing here?
10 |     foo - foo
   |     ^^^^^^^^^ expected `()`, found associated type
   |
   = note:    expected unit type `()`
           found associated type `<impl Trait as Sub>::Output`
   = help: consider constraining the associated type `<impl Trait as Sub>::Output` to `()`
   = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
```
Maybe that's helpful enough? This definitely doesn't seem like a bug though, I'm going to change it to a diagnostic request.

**Comment by Dylan-DPC** [comment] 2024-12-11 13:20
Current output: [playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=88a2ad134c3ffed8776af529898740c2)
```
error[E0562]: `impl Trait` is not allowed in paths
 --> src/main.rs:8:31
  |
8 | fn test0(foo: impl Trait) -> <impl Trait as std::ops::Sub>::Output {
  |                               ^^^^^^^^^^
  |
  = note: `impl Trait` is only allowed in arguments and return types of functions and methods
```

**Comment by Dylan-DPC** [comment] 2024-12-11 13:40
Closing this issue as this code doesn't compile any more as intended, and maybe the diagnostic should be improved but i feel that's better as a new issue

**Closed** 2024-12-11 13:40 UTC
Labels: A-diagnostics, T-compiler, A-impl-trait
