### ISSUE TITLE
The compiler proposes to import non-existing trait

### ISSUE THREAD

**Issue by iamnotacake** [rust-lang/rust#39978] opened 2017-02-20 15:17 UTC
I am using `rustc 1.15.1 (021bd294c 2017-02-08)`, installed with `rustup` on Arch Linux

Here is code:
```rust
// use std::os::ext::fs::MetadataExt;

fn main() {
    let file = std::fs::File::open("/dev/null").unwrap();
    let metadata = file.metadata().unwrap();

    println!("{:?}", metadata.mode());
}
```

When I try to compile this, I get
```
error: no method named `mode` found for type `std::fs::Metadata` in the current scope
 --> src/main.rs:9:31
  |
9 |     println!("{:?}", metadata.mode());
  |                               ^^^^
  |
  = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
  = help: candidate #1: `use std::os::ext::fs::MetadataExt;`
```
but when I uncomment first line, I get
```
error[E0432]: unresolved import `std::os::ext::fs::MetadataExt`
 --> src/main.rs:3:5
  |
3 | use std::os::ext::fs::MetadataExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `ext` in `os`
```

The solution is to `use std::os::linux::fs::MetadataExt;` and then use `st_mode()` instead of `mode()` but that's not good. Compiler must not give me bad advices.

**Comment by aidanhs** [comment] 2017-02-20 17:24
This looks the same as https://github.com/rust-lang/rust/issues/26454

**Comment by Aatch** [comment] 2017-02-21 00:33
Duplicate of #26454

**Closed by Aatch** 2017-02-21 00:33 UTC
