### ISSUE TITLE
thread 'rustc' panicked at 'Box<dyn Any>'

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#113947] opened 2023-07-22 03:13 UTC
### Code

Sorry, didn't try to make minimal example. It likely broke in the latest nightly, because yesterday it worked fine in CI.

Error can be reproduced with
* checkout https://github.com/facebookexperimental/starlark-rust/ for example, latest revision b0928b782a94bd1b4237b07c668d33c1805db701
* `cargo check -p starlark`

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (0308df23e 2023-07-21)
binary: rustc
commit-hash: 0308df23e621e783e31a27ca5beaa01b9df60d4a
commit-date: 2023-07-21
host: aarch64-apple-darwin
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Error output

https://gist.github.com/stepancheg/8dea55bf07148397357073a6977ee5d4

</p>
</details>

**Comment by lqd** [comment] 2023-07-22 08:16
I'm pretty sure this is a duplicate of #113941, which was fixed by #113946. 

So I'll close this issue as already resolved, but feel free to reopen it if it's not actually fixed in tomorrow's nightly as we'd expect.

Thanks for opening an issue!

**Closed by lqd** 2023-07-22 08:16 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
