### ISSUE TITLE
rustdoc search on local machine does not work on Google Chrome on Windows

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/rust#28695] opened 2015-09-27 19:12 UTC
When documentation is generated for a local project everything works fine except the searching. I looked in the Chrome Console and saw that main.js was generating an error.

![image](https://cloud.githubusercontent.com/assets/4435960/10117518/97a381ba-6451-11e5-8eb7-493b086ab8b9.png)

When I commented out the whole history block searching worked again. Does someone know how to fix this and maintain the history setting thing?

**Comment by eefriedman** [comment] 2015-09-27 19:21
Duplicate of #25953. (Fixed on nightly.)

**Comment by steveklabnik** [comment] 2015-09-27 19:23
Yup! This has been fixed. @trolleyman , if you can reproduce on the latest nightly, please let me know, otherwise, this has been fixed. Thanks so much for the report!

**Closed by steveklabnik** 2015-09-27 19:23 UTC

**Comment by trolleyman** [comment] 2015-09-28 18:04
Thanks!
