### ISSUE TITLE
compiler panic

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#42962] opened 2017-06-29 06:30 UTC
## Command
```
m4b@efrit ::  [ ~/projects/panopticon ] RUST_BACKTRACE=1 cargo check --all --verbose
       Fresh rustc-demangle v0.1.4
       Fresh byteorder v0.5.3
       Fresh strsim v0.6.0
       Fresh xdg v2.1.0
       Fresh stable_deref_trait v1.0.0
       Fresh rustc-serialize v0.3.24
       Fresh unicode-xid v0.0.4
       Fresh num-traits v0.1.38
       Fresh cfg-if v0.1.1
       Fresh bit-vec v0.4.4
       Fresh libc v0.2.23
       Fresh byteorder v1.0.0
       Fresh unicode-width v0.1.4
       Fresh lazy_static v0.2.8
       Fresh ansi_term v0.9.0
       Fresh regex-syntax v0.3.9
       Fresh quote v0.3.15
       Fresh log v0.3.8
       Fresh winapi v0.2.8
       Fresh serde v1.0.8
       Fresh lazy_static v0.1.16
       Fresh futures v0.1.14
       Fresh cassowary v0.1.0
       Fresh winapi-build v0.1.1
       Fresh smallvec v0.4.0
       Fresh pkg-config v0.3.9
       Fresh utf8-ranges v0.1.3
       Fresh hamt v0.2.0
       Fresh gcc v0.3.50
       Fresh scroll v0.4.0
       Fresh bitflags v0.8.2
       Fresh vec_map v0.8.0
       Fresh multimap v0.3.0
       Fresh unicode-segmentation v1.2.0
       Fresh owning_ref v0.3.3
       Fresh synom v0.11.3
       Fresh num-complex v0.1.38
       Fresh num-integer v0.1.34
       Fresh bit-set v0.4.0
       Fresh thread-id v3.1.0
       Fresh rand v0.3.15
       Fresh memchr v0.1.11
       Fresh atty v0.2.2
       Fresh num_cpus v1.5.1
       Fresh time v0.1.37
       Fresh term_size v0.3.0
       Fresh serde_bytes v0.10.0
       Fresh cmake v0.1.24
       Fresh syn v0.11.11
       Fresh num-iter v0.1.33
       Fresh tempdir v0.3.5
       Fresh uuid v0.5.0
       Fresh parking_lot_core v0.2.2
       Fresh num-bigint v0.1.38
       Fresh aho-corasick v0.5.3
       Fresh futures-cpupool v0.1.5
       Fresh clap v2.24.2
       Fresh serde_cbor v0.6.0
       Fresh structopt-derive v0.0.5
       Fresh serde_derive_internals v0.15.1
       Fresh scroll_derive v0.4.0
       Fresh parking_lot v0.4.4
       Fresh num-rational v0.1.37
       Fresh structopt v0.0.5
       Fresh kernel32-sys v0.2.2
       Fresh backtrace-sys v0.1.11
       Fresh miniz-sys v0.1.9
       Fresh serde_derive v1.0.8
       Fresh goblin v0.0.9
       Fresh num v0.1.38
       Fresh thread-id v2.0.0
       Fresh backtrace v0.3.2
       Fresh flate2 v0.2.19
       Fresh panopticon-graph-algos v0.11.0 (file:///home/m4b/projects/panopticon/graph-algos)
       Fresh chrono v0.3.1
       Fresh chrono v0.2.25
       Fresh thread_local v0.2.7
       Fresh error-chain v0.8.1
       Fresh chrono-humanize v0.0.9
       Fresh regex v0.1.80
       Fresh env_logger v0.3.5
       Fresh quickcheck v0.3.2
   Compiling panopticon-core v0.16.0 (file:///home/m4b/projects/panopticon/core)
     Running `rustc --crate-name panopticon_core core/src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=f9ee24bb440baff8 -C extra-filename=-f9ee24bb440baff8 --out-dir /home/m4b/projects/panopticon/target/debug/deps -L dependency=/home/m4b/projects/panopticon/target/debug/deps --extern flate2=/home/m4b/projects/panopticon/target/debug/deps/libflate2-81e823f279494836.rmeta --extern libc=/home/m4b/projects/panopticon/target/debug/deps/liblibc-cb0c207ef9d2a5d6.rmeta --extern byteorder=/home/m4b/projects/panopticon/target/debug/deps/libbyteorder-538feeb5fc6bc0c4.rmeta --extern tempdir=/home/m4b/projects/panopticon/target/debug/deps/libtempdir-7faa5f18150b513e.rmeta --extern env_logger=/home/m4b/projects/panopticon/target/debug/deps/libenv_logger-a2bca5b4d127624e.rmeta --extern quickcheck=/home/m4b/projects/panopticon/target/debug/deps/libquickcheck-da797c013c5333b5.rmeta --extern serde=/home/m4b/projects/panopticon/target/debug/deps/libserde-70217ab196094126.rmeta --extern uuid=/home/m4b/projects/panopticon/target/debug/deps/libuuid-f14e40d9794c3fb7.rmeta --extern panopticon_graph_algos=/home/m4b/projects/panopticon/target/debug/deps/libpanopticon_graph_algos-2434021643b280e1.rmeta --extern serde_derive=/home/m4b/projects/panopticon/target/debug/deps/libserde_derive-e937075bddb28583.so --extern num=/home/m4b/projects/panopticon/target/debug/deps/libnum-c5127264b39e8c2b.rmeta --extern log=/home/m4b/projects/panopticon/target/debug/deps/liblog-34655b5cfc2c5d14.rmeta --extern serde_cbor=/home/m4b/projects/panopticon/target/debug/deps/libserde_cbor-ec669bf851ad0f19.rmeta --extern goblin=/home/m4b/projects/panopticon/target/debug/deps/libgoblin-84ca2ef672cc69a3.rmeta -L native=/home/m4b/projects/panopticon/target/debug/build/miniz-sys-96af03dfc552f613/out`
```

## Errors
```
error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:117:23
    |
117 |                 Some(&ControlFlowTarget::BasicBlock(ref bb)) => {
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:145:24
    |
145 |                 (Some(&ControlFlowTarget::BasicBlock(ref src_bb)), Some(&ControlFlowTarget::BasicBlock(ref tgt_bb))) => {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:145:74
    |
145 |                 (Some(&ControlFlowTarget::BasicBlock(ref src_bb)), Some(&ControlFlowTarget::BasicBlock(ref tgt_bb))) => {
    |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:151:24
    |
151 |                 (Some(&ControlFlowTarget::BasicBlock(ref src_bb)), Some(&ControlFlowTarget::Unresolved(Rvalue::Constant { value: ref c, .. }))) => {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:157:101
    |
157 |                 (Some(&ControlFlowTarget::Unresolved(Rvalue::Constant { value: ref c, .. })), Some(&ControlFlowTarget::BasicBlock(ref tgt_bb))) => {
    |                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:162:24
    |
162 |                 (Some(&ControlFlowTarget::BasicBlock(ref src_bb)), Some(&ControlFlowTarget::Unresolved(ref r))) => {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:166:69
    |
166 |                 (Some(&ControlFlowTarget::Unresolved(ref t)), Some(&ControlFlowTarget::BasicBlock(ref tgt_bb))) => {
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:170:74
    |
170 |                 (Some(&ControlFlowTarget::Failed(ref src_pos, _)), Some(&ControlFlowTarget::BasicBlock(ref tgt_bb))) => {
    |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:175:24
    |
175 |                 (Some(&ControlFlowTarget::BasicBlock(ref src_bb)), Some(&ControlFlowTarget::Failed(ref tgt_pos, _))) => {
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:262:40
    |
262 |                         ret.add_vertex(ControlFlowTarget::BasicBlock(bb));
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:281:28
    |
281 |             ret.add_vertex(ControlFlowTarget::BasicBlock(BasicBlock::from_vec(bblock)));
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:291:35
    |
291 |                             Some(&ControlFlowTarget::BasicBlock(ref bb)) => bb.mnemonics.last().map_or(false, |x| x.area.start == *src_off),
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:301:69
    |
301 |                             (&Rvalue::Constant { value, .. }, Some(&ControlFlowTarget::BasicBlock(ref bb))) => bb.area.start == value,
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:314:38
    |
314 |                         if let Some(&ControlFlowTarget::BasicBlock(ref bb)) = ret.vertex_label(to) {
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `BasicBlock` found for type `function::ControlFlowTarget` in the current scope
   --> core/src/function.rs:324:38
    |
324 |                         if let Some(&ControlFlowTarget::BasicBlock(ref bb)) = ret.vertex_label(from) {
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: internal compiler error: /checkout/src/librustc/middle/mem_categorization.rs:1158: tuple struct pattern didn't resolve to variant or struct Err
   --> core/src/function.rs:301:69
    |
301 |                             (&Rvalue::Constant { value, .. }, Some(&ControlFlowTarget::BasicBlock(ref bb))) => bb.area.start == value,
    |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Panic and backtrace
```
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (69c65d296 2017-06-28) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:426
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::span_bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::span_bug_fmt
  10: rustc::middle::mem_categorization::MemCategorizationContext::cat_pattern_
  11: rustc::middle::mem_categorization::MemCategorizationContext::cat_pattern_
  12: rustc::middle::mem_categorization::MemCategorizationContext::cat_pattern_
  13: rustc::middle::mem_categorization::MemCategorizationContext::cat_pattern_
  14: rustc::middle::expr_use_visitor::ExprUseVisitor::walk_expr
  15: rustc::middle::expr_use_visitor::ExprUseVisitor::consume_expr
  16: rustc::middle::expr_use_visitor::ExprUseVisitor::consume_body
  17: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  18: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  19: rustc::hir::intravisit::walk_block
  20: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  21: rustc::hir::intravisit::walk_block
  22: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  23: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  24: rustc::hir::intravisit::walk_block
  25: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  26: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  27: rustc::hir::intravisit::walk_block
  28: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  29: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  30: rustc::hir::intravisit::walk_block
  31: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  32: rustc::hir::intravisit::walk_block
  33: <rustc_typeck::check::upvar::InferBorrowKindVisitor<'a, 'gcx, 'tcx> as rustc::hir::intravisit::Visitor<'gcx>>::visit_expr
  34: rustc_typeck::check::typeck_tables_of::{{closure}}
  35: rustc_typeck::check::typeck_tables_of
  36: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  37: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  38: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  39: rustc_typeck::check::typeck_item_bodies
  40: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get
  41: rustc::ty::maps::TyCtxtAt::typeck_item_bodies
  42: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies
  43: rustc_typeck::check_crate
  44: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  45: rustc_driver::driver::phase_3_run_analysis_passes
  46: rustc_driver::driver::compile_input
  47: rustc_driver::run_compiler

error: Could not compile `panopticon-core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name panopticon_core core/src/lib.rs --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=f9ee24bb440baff8 -C extra-filename=-f9ee24bb440baff8 --out-dir /home/m4b/projects/panopticon/target/debug/deps -L dependency=/home/m4b/projects/panopticon/target/debug/deps --extern flate2=/home/m4b/projects/panopticon/target/debug/deps/libflate2-81e823f279494836.rmeta --extern libc=/home/m4b/projects/panopticon/target/debug/deps/liblibc-cb0c207ef9d2a5d6.rmeta --extern byteorder=/home/m4b/projects/panopticon/target/debug/deps/libbyteorder-538feeb5fc6bc0c4.rmeta --extern tempdir=/home/m4b/projects/panopticon/target/debug/deps/libtempdir-7faa5f18150b513e.rmeta --extern env_logger=/home/m4b/projects/panopticon/target/debug/deps/libenv_logger-a2bca5b4d127624e.rmeta --extern quickcheck=/home/m4b/projects/panopticon/target/debug/deps/libquickcheck-da797c013c5333b5.rmeta --extern serde=/home/m4b/projects/panopticon/target/debug/deps/libserde-70217ab196094126.rmeta --extern uuid=/home/m4b/projects/panopticon/target/debug/deps/libuuid-f14e40d9794c3fb7.rmeta --extern panopticon_graph_algos=/home/m4b/projects/panopticon/target/debug/deps/libpanopticon_graph_algos-2434021643b280e1.rmeta --extern serde_derive=/home/m4b/projects/panopticon/target/debug/deps/libserde_derive-e937075bddb28583.so --extern num=/home/m4b/projects/panopticon/target/debug/deps/libnum-c5127264b39e8c2b.rmeta --extern log=/home/m4b/projects/panopticon/target/debug/deps/liblog-34655b5cfc2c5d14.rmeta --extern serde_cbor=/home/m4b/projects/panopticon/target/debug/deps/libserde_cbor-ec669bf851ad0f19.rmeta --extern goblin=/home/m4b/projects/panopticon/target/debug/deps/libgoblin-84ca2ef672cc69a3.rmeta -L native=/home/m4b/projects/panopticon/target/debug/build/miniz-sys-96af03dfc552f613/out` (exit code: 101)
```

**Comment by est31** [comment] 2017-06-29 11:12
@m4b on which panopticon commit are you on? [Latest master](https://github.com/das-labor/panopticon/commit/dd48efccf3a964af34edfb06118758ee51909035) doesn't generate the ICE for me, at least when I cd into core and do `cargo check` (should check panopticon-core as well).

From the panic message, this seems very similar to #42880 . Maybe a dupe?

**Comment by m4b** [comment] 2017-06-29 17:09
@est31 sorry, should have added rustc:

```
m4b@efrit ::  [ ~/projects/panopticon ] rustc --version
rustc 1.20.0-nightly (69c65d296 2017-06-28)
m4b@efrit ::  [ ~/projects/panopticon ] cargo --version
cargo 0.21.0-nightly (abf01e1ed 2017-06-25)
```

Also, try using this script:

```bash
#!/bin/bash

from=$1
to=$2

echo "from=$1 to=$2"

function ren () {
    echo "renaming $1"
    for i in $1/src/*.rs; do
	sed -i "s/$from/$to/g" $i
    done
    for i in $1/tests/*.rs; do
	sed -i "s/$from/$to/g" $i
    done;
    return 0
}

ren abstract-interp
ren amd64
ren analysis
ren avr
ren cli
ren core
ren data-flow
ren glue
ren graph-algos
ren mos6502
ren qt
```

and then do something like `./rename ControlFlowTarget::Resolved ControlFlowTarget::BasicBlock`

it will rename everything except the enum def itself, and should repro the error exactly

**Comment by est31** [comment] 2017-07-16 10:09
@m4b is this still reproducible? If so, could you upload it to github somehow?

**Comment by steveklabnik** [comment] 2018-09-24 18:09
Triage: can't reproduce, so closing. @m4b if you're still seeing this today please let me know!

**Closed by steveklabnik** 2018-09-24 18:09 UTC
Labels: C-bug, I-ICE
