### ISSUE TITLE
Confusing error message when trying to pattern match on slice containing String

### ISSUE THREAD

**Issue by sivertjoe** [rust-lang/rust#90121] opened 2021-10-21 08:59 UTC
Given the following code: 

```rust
fn main()
{
    let foo = vec!["foo".to_string()];
    
    match foo.as_slice()
    {
        &["foo".to_string()] => {}
        _ => {}
    };
}
```

The current output is:

```
error: expected one of `,`, `...`, `..=`, `..`, `]`, or `|`, found `.`
 --> src/main.rs:8:16
  |
8 |         &["foo".to_string()] => {}
  |                ^
  |                |
  |                expected one of `,`, `...`, `..=`, `..`, `]`, or `|`
  |                help: missing `,`

error[E0531]: cannot find tuple struct or tuple variant `to_string` in this scope
 --> src/main.rs:8:17
  |
8 |         &["foo".to_string()] => {}
  |                 ^^^^^^^^^ not found in this scope

error[E0308]: mismatched types
 --> src/main.rs:8:11
  |
6 |     match foo.as_slice()
  |           -------------- this expression has type `&[String]`
7 |     {
8 |         &["foo".to_string()] => {}
  |           ^^^^^ expected struct `String`, found `&str`

Some errors have detailed explanations: E0308, E0531.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `playground` due to 3 previous errors
```

Ideally the output should look the same as if I did:
```rust
match foo.as_slice()
{
    &[String::from("foo")] => {}
    _ => {}
};
```
which is:
```
error[E0164]: expected tuple struct or tuple variant, found associated function `String::from`
 --> src/main.rs:8:11
  |
8 |         &[String::from("foo")] => {}
  |           ^^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
  |
  = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html

```

So maybe a better output for my first example would be
```
error[E0164]: expected tuple struct or tuple variant, found associated function `std::str::to_string`
 --> src/main.rs:8:11
  |
8 |          &["foo".to_string()] => {}
  |           ^^^^^^^^^^^^^^^^^^^ `fn` calls are not allowed in patterns
  |
  = help: for more information, visit https://doc.rust-lang.org/book/ch18-00-patterns.html

```

**Comment by Nadrieril** [comment] 2023-12-01 02:03
Closing as a duplicate of https://github.com/rust-lang/rust/issues/112593 (which has mentoring instructions)

**Closed by Nadrieril** 2023-12-01 02:03 UTC
Labels: A-diagnostics, A-parser, T-compiler, A-patterns
