### ISSUE TITLE
Lifetime leak in combination of double link and static

### ISSUE THREAD

**Issue by amarao** [rust-lang/rust#79632] opened 2020-12-02 12:52 UTC
I tried this code:

```rust
static I: i32 = 0;
static R: &'static & i32 = &&I;

fn aux<'a, 'b, T>(_: &'a &'b i32, arg: &'b T) -> &'a T
{
    return arg;
}

fn foo<'a, T>(arg: &'a T) -> &'static T
{
    let f: fn(_, &'a T) -> &'static T = aux;
    return f(R, arg);
}

fn bar() -> &'static i32
{
    let a: i32 = 0;
    return foo(&a);
}

fn main()
{
    let res: &i32 = bar();
    println!("{0}", *res);
}
```

I expected to see this happen: 0

Instead, this happened: 32765
### Meta
Reproducible on nightly and stable (1.48.0)

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2a5a193fc1e93f5976eb619fd113b0b1

Based on Russian discussion on Rust safety: https://habr.com/en/company/pvs-studio/blog/530856/?reply_to=22377206#comment_22376840, example was provided by KanuTaH.

**Comment by lcnr** [comment] 2020-12-02 13:02
closing as a duplicate of #25860

**Closed by lcnr** 2020-12-02 13:02 UTC
Labels: C-bug, I-prioritize, I-unsound 💥
