### ISSUE TITLE
Should `enum Foo { SingleVariant }` be zero-size?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#37649] opened 2016-11-08 15:31 UTC
This prints `1` in rustc 1.14.0-nightly (cae6ab1c4 2016-11-05):

```rust
pub enum Foo { SingleVariant }
fn main() {
    println!("{}", ::std::mem::size_of::<Foo>());
}
```

I’m guessing this one byte is the enum’s discriminant. But since there’s a single variant, that discriminant is useless. Could such a type be zero-size? For what it’s worth, an empty `enum Bar {}` is already zero-size.

This type could be written `struct Foo;` which is zero-size, but a single-variant enum could come up if it’s generated by a macro that can generate any number of variants depending on its arguments.

**Comment by SimonSapin** [comment] 2016-11-08 15:55
frewsxcv and misdreavus on IRC point out that the discriminant is already eliminated in some cases:

```rust
playbot: enum Foo { SingleVariant(i32) } ::std::mem::size_of::<Foo>()
4
playbot: enum Foo { SingleVariant(()) } ::std::mem::size_of::<Foo>()
0
playbot: enum Foo { SingleVariant{} } ::std::mem::size_of::<Foo>()
1

**Comment by arielb1** [comment] 2016-11-08 18:39
I'm quite sure it should be. This looks like a bug.

**Comment by ranma42** [comment] 2016-11-08 23:04
I agree that this inconsistency feels like a bug.

@arielb1 The section https://doc.rust-lang.org/reference.html#enumerations of the Rust reference seems to only state that it can be cast (using `as`) to get the discriminant. It would be possible to preserve this behaviour even with a 0-sized type.

The change would possibly break assumptions of existing crates on the size of such enumerations (for example when they are `transmute`d). Would a crater run be sufficient to evaluate the impact?

**Comment by arielb1** [comment] 2016-11-08 23:25
@ranma42 

Sure. The layout of `repr(Rust)` types is unspecified by design.

**Comment by petrochenkov** [comment] 2016-11-08 23:42
>I agree that this inconsistency feels like a bug.

What about the size of
```
enum E {
    A = 10 // Enum behaves like an integer constant, it should probably be layed out as one
}
```
and then the size of
```
enum E {
    A = 0 // Should behave like previous one, it would be strange for layout to depend on concrete initialized value
}
```
and then
```
enum E {
    A // This is exact equivalent to the previous enum, why should it be layed out differently?
}
```
and what about this
```
#[repr(C)]
enum E {
    A // Hey, it looks so C-like I can probably transmute it to `c_int`!
}
```

I mean, whatever the behavior is, it would be inconsistent with something.
Now "C-like" takes priority over "univariant" and not otherwise. Seems okay.

**Comment by SimonSapin** [comment] 2016-11-09 00:31
@petrochenkov I think all of your example except the `#[repr(C)]` should be zero-size. I don’t think it’s unexpected that a `repr` attribute changes the memory representation.

**Comment by eddyb** [comment] 2016-11-12 16:33
I agree with @SimonSapin here. There's also `#[repr(u8)]` and whatnot if you want to guarantee a specific size.

**Comment by mbrubeck** [comment] 2017-05-09 21:50
Duplicate of #15747.

**Closed by mbrubeck** 2017-05-09 21:50 UTC
