### ISSUE TITLE
Join is not implemented for Vec<&String>

### ISSUE THREAD

**Issue by Lesiuk** [rust-lang/rust#83140] opened 2021-03-15 11:04 UTC
I tried this code:

```rust
fn main() {
    let a = "a".to_string();
    let b = "b".to_string();
    
    assert_eq!(vec![&a, &b].join(","), "a,b".to_string());
}
```
I expected to see this happen: 
I expected &String to have access to .join same as String.

Instead, this happened: 
```error[E0599]: no method named `join` found for struct `Vec<&String>` in the current scope```

### Meta
`rustc --version --verbose`:
```
rustc 1.52.0-nightly (acca81892 2021-03-13)
binary: rustc
commit-hash: acca818928654807ed3bc1ce0e97df118f8716c8
commit-date: 2021-03-13
host: x86_64-pc-windows-msvc
release: 1.52.0-nightly
LLVM version: 12.0.0```

**Comment by osa1** [comment] 2021-03-16 07:10
@rustbot label +T-libs -C-bug

I'm curious to see how this will get resolved.

My personal opinion is that the type `Vec<&String>` is not too useful and you're better off with `Vec<&str>`, so in practice I'm not sure if this is a big deal.

**Comment by ccgauche** [comment] 2021-03-17 20:45
Maybe adding an
```rust
impl <T: ToString> Join for Vec<T>
```
To STD could be nice. This would make join far more usable.

What do you think ?

**Comment by estebank** [comment] 2021-03-17 22:01
Duplicate of https://github.com/rust-lang/rust/issues/82910

**Closed by estebank** 2021-03-17 22:01 UTC
Labels: T-libs
