### ISSUE TITLE
Digitally sign all the binary files with code signing certificate

### ISSUE THREAD

**Issue by asesh** [rust-lang/rust#123791] opened 2024-04-11 12:22 UTC
Hello, it would be great if all the binary files of Rust were digitally signed with a valid code signing certificate to ensure the file came from the publisher and hasn't been tampered after publication. 

Why this is necessary?
Some companies have policies to only allow running the apps from certain publishers.  Code signing files also ensures the file came from the publisher and is genuine.
```[tasklist]
### Tasks
```

**Comment by memoryruins** [comment] 2024-04-11 14:52
https://github.com/rust-lang/rust/issues/27694 tracks the progress of signing Rust packages and https://github.com/rust-lang/rustup/issues/1568 tracks the progress of rustup,

**Comment by ehuss** [comment] 2024-04-11 15:06
Thanks! Closing as a duplicate of the above linked issues.

**Closed by ehuss** 2024-04-11 15:06 UTC
Labels: needs-triage
