### ISSUE TITLE
`todo!()`, `unimplemented!()`, `panic!()`, … don't play well with `impl Trait`

### ISSUE THREAD

**Issue by robinmoussu** [rust-lang/rust#74363] opened 2020-07-15 12:34 UTC
I tried this code:

```rust
fn test() -> impl Iterator<Item=f32> {
    todo!()
}
```

I expected to see this happen: the code should compile (and fails at runtime).

Instead, this happened:

```rust
error[E0277]: `()` is not an iterator
 --> src/lib.rs:1:14
  |
1 | fn test() -> impl Iterator<Item=f32> {
  |              ^^^^^^^^^^^^^^^^^^^^^^^ `()` is not an iterator
2 |     todo!()
  |     ------- this returned value is of type `!`
  |
  = help: the trait `std::iter::Iterator` is not implemented for `()`
  = note: the return type of a function must have a statically known size

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.
```
---

Note: The issue exists for similar macros: `unimplemented`, `panic`, and most probably others that I'm not aware of.

---

I'm using the following workaround (which obviously works only for iterators, but can be adapted for any kind of object being iterated on):

```rust
fn test() -> impl Iterator<Item=f32> {
    const TODO: [f32; 0] = [];
    todo!();
    #[allow(unreachable_code)]
    TODO.iter().cloned()    
}
```

---

Note: I'm relatively sure that this issue is known (given how easy it is to reproduce it), but I didn't found it in the bug tracker.

**Comment by robinmoussu** [comment] 2020-07-15 12:38
Should this be added to #63066?

**Comment by robinmoussu** [comment] 2020-07-15 12:39
Consider adding the label `A-impl-trait`.

**Comment by wesleywiser** [comment] 2020-07-16 01:18
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/69882

**Comment by jonas-schievink** [comment] 2020-07-23 15:01
Yes, closing in favor of https://github.com/rust-lang/rust/issues/69882

**Closed by jonas-schievink** 2020-07-23 15:01 UTC
Labels: A-impl-trait, C-bug
