### ISSUE TITLE
rustc compiler unexpectedly panicked

### ISSUE THREAD

**Issue by franklucky001** [rust-lang/rust#82629] opened 2021-02-28 13:55 UTC
### Code
```rust
trait UseA{
    fn use_a(&self);
}
trait A {
    fn hello(&self) {
        println!("hello A ");
    }
}
#[derive(Debug)]
struct Base{
    name: String,
}
impl UseA for  Base {
    fn use_a(&self) {
        println!("aaaa");
    }
}
impl<T: UseA> A for T {
    fn hello(&self) {
        self.use_a();
        super().hello();
    }
}

fn main() {
   let base = Base{name: String::from("base")};
   base.hello();
}
```

### Meta

`rustc --version`: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-pc-windows-msvc

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_resolve\src\late\diagnostics.rs:138:36
error: internal compiler error: unexpected panic
error: could not compile `hello`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-28 14:24
This is fixed on nightly

**Comment by matthiaskrgr** [comment] 2021-02-28 14:32
>`super()`

Could be a duplicate of https://github.com/rust-lang/rust/issues/82156

**Comment by jonas-schievink** [comment] 2021-03-01 00:28
looks like it

**Closed by jonas-schievink** 2021-03-01 00:28 UTC
Labels: C-bug, I-ICE, T-compiler
