### ISSUE TITLE
compiler rejects to use self in match arm

### ISSUE THREAD

**Issue by stefanhoelzl** [rust-lang/rust#64607] opened 2019-09-19 11:44 UTC
Hi,

I have the following Code [(Playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c436b46fba25c33930edf4f984feec38)
```rust
struct S {
    first: usize,
    second: usize,
}

impl S {
    fn matches(&self, v: usize) -> &'static str {
        match v {
            self.first => "first",
            self.second => "second",
            _ => "none",
        }
    }
}

fn main() {
    let s = S{first: 20, second: 10};
    println!("{}", s.matches(10));
}
```
where I want to use `self` in the match arms, but the Compiler rejects to do so
```^ expected one of `::`, `=>`, `if`, or `|` here```

But I do not know or understand why this should not be allowed?
Can I achieve this somehow else?

`rustc 1.39.0-nightly (b9de4ef89 2019-09-03)`

**Comment by Mark-Simulacrum** [comment] 2019-09-19 11:47
No, the left hand side of a match arm is a pattern, and `self.first` is not a pattern.

You can do something similar with 
`_ if self.first == v => "first"` but it may be easier to use an if/else if/else block at that point

Closing since this is not a bug, general discussion should happen on users.rust-lang.org.

**Closed by Mark-Simulacrum** 2019-09-19 11:47 UTC
