### ISSUE TITLE
Generics confusion in docs

### ISSUE THREAD

**Issue by mvdnes** [rust-lang/rust#15977] opened 2014-07-25 14:44 UTC
## Description

Recently I was looking in the docs for [FilterMap](http://doc.rust-lang.org/std/iter/struct.FilterMap.html), where it says:

```rust
fn filter_map<B>(|B|: 'r -> Option<B>) -> FilterMap<'r, B, B, FilterMap<'a, A, B, T>>
```

However, it seems that not all `B`'s must be the same type. The definition of `filter_map` is namely:

```rust
fn filter_map<'r, B>(self, f: |A|: 'r -> Option<B>) -> FilterMap<'r, A, B, Self>
```

I believe this is due to the fact that the function `filter_map` is implemented for `Iterator<A>` and that FilterMap implements `Iterator<B>`.

**Comment by steveklabnik** [comment] 2015-01-24 00:24
These signatures have changed entirely, I'm not sure if they're still wrong, but they are slightly different...

**Comment by mvdnes** [comment] 2015-01-24 13:27
Confusion in some form arises in the following code

```rust
pub trait MyImpl<A> {
    fn myimpl_fun<B>(&self, _: A) -> Option<B> {
        None
    }   
}

pub struct MyStruct<B> {
    _data: B,
}

impl<B> MyImpl<B> for MyStruct<B> {}
```

Running the doc, we get

```rust
impl<B> MyImpl<B> for MyStruct<B>
    fn myimpl_fun<B>(&self, _: A) -> Option<B>
```

In this case, the A should actually be a B, and the B's from the function something else.

**Comment by alexcrichton** [comment] 2015-04-06 23:06
I believe this is a dupe of #14072, so closing in favor of that.

**Closed by alexcrichton** 2015-04-06 23:06 UTC
Labels: A-rustdoc
