### ISSUE TITLE
#[derive(Debug)] does not take into account inner uses of associated trait types in its predicate

### ISSUE THREAD

**Issue by DarkRyu550** [rust-lang/rust#77539] opened 2020-10-04 18:17 UTC
When trying to use `#[derive(Debug)]` in a structure whose inner elements use an associated type, it does not correctly take into account their required predicate. I'm not sure whether this is intended or not.

```rust

trait Bar {
    type Inner;
}
impl Bar for () {
    type Inner = u32;
}

#[derive(Debug)]
struct Functional<T: Bar> {
    value: T::Inner
}

#[derive(Debug)]
struct Broken<T: Bar> {
    value: Baz<T>
}

#[derive(Debug)]
struct Baz<T: Bar> {
    value: T::Inner
}


fn main() {
    println!("{:?}", Functional::<()> { value: 0 });
    println!("{:?}", Broken::<()> { value: Baz { value: 0 } })
    
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=66960bceb9b7dc3b9e92aad27d23589b))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: `<T as Bar>::Inner` doesn't implement `Debug`
  --> src/main.rs:16:5
   |
16 |     value: Baz<T>
   |     ^^^^^^^^^^^^^ `<T as Bar>::Inner` cannot be formatted using `{:?}` because it doesn't implement `Debug`
   |
   = help: the trait `Debug` is not implemented for `<T as Bar>::Inner`
   = note: required because of the requirements on the impl of `Debug` for `Baz<T>`
   = note: required because of the requirements on the impl of `Debug` for `&Baz<T>`
   = note: required for the cast to the object type `dyn Debug`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.

```

**Comment by jonas-schievink** [comment] 2020-10-04 18:19
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2020-10-04 18:19 UTC
