### ISSUE TITLE
E0383 is working now?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#33792] opened 2016-05-22 16:31 UTC
As far as I know, this code *shouldn't* compile:

```rust
fn main() {
    struct Foo {
        a: u32,
    }
    let mut x = Foo { a: 1 };
    drop(x); // `x` is now uninitialized
    x.a = 2; // error, partial reinitialization of uninitialized structure `t`
}

```

**Comment by durka** [comment] 2016-05-22 18:11
duplicate of #21232 I believe

**Comment by GuillaumeGomez** [comment] 2016-05-23 08:38
I think you're right. I close it.

**Closed** 2016-05-23 11:26 UTC
