### ISSUE TITLE
rustdoc: When view source, macro-expanded items are not shown at when macro is called

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#74818] opened 2020-07-27 10:43 UTC
Try this: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/parser/struct.Restrictions.html
(*Note: The link of rustc API may die*).

Click to view source `[src]` button, it will lead you to bitflag doc.

I expected to see this happen: The button should lead me to source code at call site:
https://github.com/rust-lang/rust/blob/1841fb97e17f5e41c609cd11ab114c7ac1f3de2a/src/librustc_parse/parser/mod.rs#L33-L38

**Comment by jyn514** [comment] 2020-10-11 03:22
Duplicate of https://github.com/rust-lang/rust/issues/39726

**Closed by jyn514** 2020-10-11 03:22 UTC
Labels: C-bug, T-rustdoc
