### ISSUE TITLE
Can't infer type of closure argument with explicit type

### ISSUE THREAD

**Issue by Diegovsky** [rust-lang/rust#77928] opened 2020-10-14 02:52 UTC
While trying to implement recursive directory creation, somehow rustc gave the following error message:

[consider giving this closure parameter a type](https://imgur.com/2QrHzKs)

code:
```rust
//dir is &str
let dir: PathBuf = match Path::new(dir).canonicalize() { 
         Ok(v) => v,
         Err(e) => {
             Path::new(dir).iter().fold(PathBuf::new(), |mut buf, x: &OsStr| {
                 buf.push(x);
                 if !buf.exists() {
                     std::fs::create_dir(<PathBuf as AsRef<Path>>::as_ref(&buf)).unwrap();
                 }
                 buf
             }).canonicalize().unwrap()
         }
     };
```
As can be seen, `buf` 
I didn't expect any type errors, but I might be wrong.

`rustc --version --verbose`:

```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```

**Comment by estebank** [comment] 2020-10-14 04:50
Could you provide a link to a reproduction in the playground? [I failed to create one with a naïve attempt](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8204f3c3ef4e6b1582e8e67997f40c96).

**Comment by Enselic** [comment] 2023-12-16 07:20
Triage: Closing as not reproducible since no reproducer was provided.

**Closed by Enselic** 2023-12-16 07:20 UTC
Labels: T-libs-api, C-bug, A-io
