### ISSUE TITLE
LLVM abort from deref of 0 in a const expression initializing a static

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24581] opened 2015-04-19 00:03 UTC
(imported from improperly closed bug #17452)

```rust
static X: usize = unsafe { *(0 as *const usize) };

fn main() {
    println!("X: {}", X);
}
```

[playpen](http://is.gd/QrfaqE)

This causes LLVM to abort, causing a core dump from `rustc`.  :(

(I suspect we should be more careful, somehow, about handling such things in our const expression evaluator.  Not 100% sure how best to resolve this though.)

**Comment by pnkfelix** [comment] 2015-04-19 00:04
(i don't want to tag this as `ICE` -- that implies to me that we are actually catching this and issuing the ICE message...)

**Comment by pnkfelix** [comment] 2015-04-19 00:04
(I suppose I could tag it as both `I-ICE` and `I-crash`, though that seems like it does more harm than good w.r.t. the labeling system.)

**Comment by jakub-** [comment] 2015-04-19 00:17
I think this issue is a dupe of https://github.com/rust-lang/rust/issues/13973 so I'm going to close it. @pnkfelix, feel free to reopen if you disagree.

**Closed by jakub-** 2015-04-19 00:17 UTC

**Comment by pnkfelix** [comment] 2015-04-19 02:12
well I'd say that one could probably argue that #13973 should actually compile successfully (and bind `BLOCK_UNSAFE_SAFE_PTR` to the address that corresponds to the number `0xdeadbeef`), while this code does not seem like it should compile successfully...

In other words, solving both of these problems may involve a more general solution than solving either independently...
