### ISSUE TITLE
Everything an async fn ever touches must be Send, if you want its futures to be Send

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#72148] opened 2020-05-12 18:02 UTC
I tried to compile this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=62b096a37946fa73586123ae9a1584ae):
```
use std::error::Error;

async fn consume_result() {
    let r: Box<dyn Error> = "oh no".into();
    std::mem::drop(r);
    async { () }.await
}

fn must_be_send<T: Send>(_: T) { }

fn main() {
    must_be_send(consume_result());
}
```
but Rust complains that the future of `consume_result`'s completion is not `Send`. Same results if I assign an `Rc` to `r` and drop it on the next line. Note that `r` is not live across any `await` or the function's initial suspension.

This is rather severe: it means that using any `!Send` value, even for a moment, makes it impossible to use your function with a multi-threaded executor.

I can't call a sync function that returns `Box<dyn Error>`, even if I handle the error immediately.

The error message is also misleading:
```
error: future cannot be sent between threads safely
  --> src/main.rs:12:5
   |
9  | fn must_be_send<T: Send>(_: T) { }
   |    ------------    ---- required by this bound in `must_be_send`
...
12 |     must_be_send(consume_result());
   |     ^^^^^^^^^^^^ future returned by `consume_result` is not `Send`
   |
   = help: the trait `std::marker::Send` is not implemented for `dyn std::error::Error`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:6:5
   |
4  |     let r: Box<dyn Error> = "oh no".into();
   |         - has type `std::boxed::Box<dyn std::error::Error>`
5  |     std::mem::drop(r);
6  |     async { () }.await;
   |     ^^^^^^^^^^^^^^^^^^ await occurs here, with `r` maybe used later
7  | }
   | - `r` is later dropped here
```
This is incorrect: `r` is definitely dropped on line 5, not line 7.

**Comment by jonas-schievink** [comment] 2020-05-12 18:07
You can enclose it in a block

```
    {
        let r: Box<dyn Error> = "oh no".into();
        std::mem::drop(r);
    }
```

Duplicate of https://github.com/rust-lang/rust/issues/57478

**Closed by jonas-schievink** 2020-05-12 18:07 UTC
Labels: C-bug
