### ISSUE TITLE
Nightly components are not available anymore on target 'x86_64-apple-darwin'

### ISSUE THREAD

**Issue by shisoft** [rust-lang/rust#55588] opened 2018-11-01 17:00 UTC
Hi all,

I tried to update my local components through `rustup update` on my macs but get following messages:
```
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2018-11-01, rust version 1.31.0-nightly (de9666f12 2018-10-31)
warning: component 'rustc' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'rust-std' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'cargo' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'rust-docs' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'rustfmt-preview' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'rls-preview' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'rust-analysis' is not available anymore on target 'x86_64-apple-darwin'
warning: component 'rust-src' is not available anymore
error: some components unavailable for download: 'rustc', 'cargo'
```

Stable is still fine for now. Nightly on other platforms, linux for example are working.

**Comment by kennytm** [comment] 2018-11-01 17:32
Thanks for the report, this is a duplicate of #55571. A fix is on the way.

**Closed by kennytm** 2018-11-01 17:32 UTC
