### ISSUE TITLE
Method lookup occurs before numeric fallback

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#39989] opened 2017-02-20 21:37 UTC
Method lookup fails on literals, e.g. `42.swap_bytes()` and `42.0.sqrt()`, even though it works once they are annotated with the type that they will get by default, `42i32.swap_bytes()` and `42.0f32.sqrt()` respectively.

**Comment by Aatch** [comment] 2017-02-21 00:35
Duplicate of #24124

**Closed by Aatch** 2017-02-21 00:35 UTC
