### ISSUE TITLE
Bug Report: Compiler Error with slices

### ISSUE THREAD

**Issue by Alfriadox** [rust-lang/rust#49126] opened 2018-03-18 03:03 UTC
I honestly don't really know what caused the bug (as it wasn't in my crate, but rather one of the dependencies while compiling on Travis CI.)

Rust version: 1.26.0 (nightly)
CI build target is a 32-bit system (cross-compiling to i686-unknown-linux-gnu).

a link to the build:
[https://travis-ci.org/Wright-Language-Developers/Wright-lang/jobs/354532259](https://travis-ci.org/Wright-Language-Developers/Wright-lang/jobs/354532259)
Here is what I found in the CI logs though. Hope it helps.

```
   Compiling void v1.0.2
   Compiling libc v0.2.39
   Compiling regex v0.2.10
   Compiling unicode-width v0.1.4
   Compiling ucd-util v0.1.1
   Compiling lazy_static v1.0.0
thread 'rustc' panicked at 'slice index starts at 4294967295 but ends at 30765555', libcore/slice/mod.rs:791:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.26.0-nightly (392645394 2018-03-15) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 --crate-type lib
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `ucd-util`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by oli-obk** [comment] 2018-03-18 12:37
dupe of https://github.com/rust-lang/rust/issues/49033

fix PR is already open (https://github.com/rust-lang/rust/pull/49079)

**Closed by oli-obk** 2018-03-18 12:37 UTC
