### ISSUE TITLE
next_power_of_two should panic on overflow

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#18604] opened 2014-11-04 04:22 UTC
If you feed in a number such that the next_power_of_two would overflow, it spits out 0. I'm fine with that honestly, since it's easy to detect, but maybe that isn't what we want here. Maybe it should return a Result/Option/panic/saturate?

Should be specified so that the behaviour can be relied upon, or explicitly documented as unspecified.

**Comment by theemathas** [comment] 2015-03-18 00:51
cc #22020

**Comment by steveklabnik** [comment] 2016-06-06 20:58
Triage: docs wise, this says " Unspecified behavior on overflow.". @theemathas has linked to the overflow RFC, and this discussion was well before that, so there's no reason for overflow behavior to be particularly exceptional here, right? It follows the same rules as everything else, unless @rust-lang/libs wants to make it special in some way.

**Comment by brson** [comment] 2016-06-09 23:42
Here's the implementation:

```
        pub fn next_power_of_two(self) -> Self {
            let bits = size_of::<Self>() * 8;
            let one: Self = Self::one();
            one << ((bits - self.wrapping_sub(one).leading_zeros() as usize) % bits)
        }
```

I think @Gankro's original comments were from before the overflow RFC so this no longer results in 0 on overflow but behaves per the RFC. And as stated there is now a `checked_` variant of this function. I think we should just update the documentation to state that it's overflow behavior corresponds to whatever setting controls overflow and move on. Is there existing precedent for methods in std allowing overflow internally?

**Comment by irfanhudda** [comment] 2017-03-21 13:28
I'll take a shot at this.

**Comment by Mark-Simulacrum** [comment] 2017-06-15 03:05
So, I was going to close this, but actually, it looks like the behavior the documentation currently specifies isn't the behavior the code produces. Namely, based on https://github.com/rust-lang/rust/pull/40706#issuecomment-293721599 I would expect https://is.gd/wRatpD to panic in debug mode, but it doesn't. Nominating for libs team discussion: Can we confirm that we want to panic (I think we should) in debug?

**Comment by alexcrichton** [comment] 2017-06-20 22:27
Yep this is just a bug, the intention is that it panics in debug mode on overflow.

**Closed** 2017-11-05 11:43 UTC
Labels: C-bug, P-medium, T-libs

**Comment by scottmcm** [comment] 2017-11-06 19:27
Confirmed in today's nightly: https://play.rust-lang.org/?gist=3bd6bdb2ff2c5ea633f9ae3091faf5d7&version=nightly&mode=debug
