### ISSUE TITLE
2018 edition allows ungated access to unstable crates

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#52489] opened 2018-07-18 15:03 UTC
When compiled with `--edition 2018` this code compiles just fine:

```rust
use rustc;

fn main() {}
```

That's bad!

**Comment by Mark-Simulacrum** [comment] 2018-07-31 23:01
@rust-lang/compiler Can we get some eyes on this, not necessarily to fix but at least to confirm that we believe a fix can be made and landed in time for RC? This is a hard-stop blocker for RC.

**Comment by eddyb** [comment] 2018-07-31 23:36
You *can't actually* use the path to resolve anything unstable, and funnily enough, `use rustc::{};` triggers the appropriate stability checks.

I'm suspecting this is caused by #51425 failing to create HIR imports in all the namespaces.

**Comment by eddyb** [comment] 2018-08-01 01:11
So this is generally harmless (you can't actually get anything from the unstable crate), except for it being a minor dead-code-but-allowed hazard.

The culprit appears to be this special-casing:
https://github.com/rust-lang/rust/blob/e94df4acb4c3f42fdc224a7164b63a99240add1e/src/librustc_resolve/resolve_imports.rs#L635-L641

Which loads the crate (producing an error if no crate with that name exists), *but doesn't record the resolution*. So there's nothing to check - and presumably no way to use that broken import.

The part that's missing is this (recording the import resolutions):
https://github.com/rust-lang/rust/blob/e94df4acb4c3f42fdc224a7164b63a99240add1e/src/librustc_resolve/resolve_imports.rs#L878-L884

But the special-casing exists early:
https://github.com/rust-lang/rust/blob/e94df4acb4c3f42fdc224a7164b63a99240add1e/src/librustc_resolve/resolve_imports.rs#L693-L694

Expected minimal diff (between the two lines in the last snippet):
```rust
let import = self.import_map.entry(directive.id).or_default(); 
import[TypeNS] = Some(PathResolution::new(binding.def())); 
```

**Closed** 2018-08-01 22:06 UTC
Labels: A-rust-2018-preview, I-nominated, T-compiler
