### ISSUE TITLE
#[repr(...)] not allowed on c-like univariant enums

### ISSUE THREAD

**Issue by Aatch** [rust-lang/rust#20146] opened 2014-12-22 22:14 UTC
This is currently an error:

```rust
#[repr(C)]
enum Foo {
    Foo
}
```

which is odd because it looks like a c-like enum. However it also looks like a univariant enum. We should specify which behaviour is correct.

More generally, should this be considered a c-like enum, or should it be a univariant enum. This affects several other aspects of the compiler.

**Comment by bluss** [comment] 2015-05-20 14:23
Duplicate of #10292

**Closed** 2015-05-26 15:57 UTC
Labels: A-ffi, A-typesystem
