### ISSUE TITLE
Associated things not found even though they do exist when used as array length

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#61730] opened 2019-06-11 06:39 UTC
```rust
struct Foo;

impl Bar for Foo {
    const BAR: usize = 1;
}

trait Bar {
    const BAR: usize;
}

struct Array<S> where S: Bar {
    data: [u8; S::BAR],
    s: S,
}
```

This errors out with:

```
error[E0599]: no associated item named `BAR` found for type `S` in the current scope
  --> src/lib.rs:12:19
   |
12 |     data: [u8; S::BAR],
   |                   ^^^ associated item not found in `S`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `BAR`, perhaps you need to implement it:
           candidate #1: `Bar`
```

Even though `S::BAR` clearly does exist. The same thing happens for constants within associated types (so `T::Bar::BAR`), with E0220, and this confused me a whole bunch. Instead apparently the problem is that array sizes currently require a literal or some other more consty consts (is that part of #133)?

cc @estebank.

**Comment by hellow554** [comment] 2019-06-11 06:58
Probably dup of https://github.com/rust-lang/rust/issues/43408

**Comment by estebank** [comment] 2019-06-11 18:42
It seems to be the same underlying problem, although it is hit in a separate part of the evaluation.

From https://github.com/rust-lang/rust/issues/43408#issuecomment-318258935:

> This is a limitation of array length - it can't use any parameters in scope - which also came up during the stabilization of associated consts (...) and the decision taken was to stabilize associated consts without it.
>
> The exact error here comes from the type parameter being resolved, but the ty::Generics and ty::GenericPredicates (bounds, including the default Sized on type parameters) of the array length are actually both empty. They have to be (for now), otherwise we get cycle errors.

**Comment by estebank** [comment] 2019-06-11 18:44
CC @rust-lang/wg-diagnostics if anyone wants to improve the error message while we await for this code to be accepted, but I would much rather we actually made the changes to make this code valid.

**Comment by estebank** [comment] 2019-06-11 18:48
If you [try to outsmart the compiler and write this in a more explicit way](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0aa16a038eebd154ca5e18a7910ef08b), you get the a similar error as #43408, but even more galling because it recommends the same code that already exists:

```
error[E0277]: the trait bound `S: Bar` is not satisfied
  --> src/lib.rs:12:16
   |
12 |     data: [u8; <S as Bar>::BAR],
   |                ^^^^^^^^^^^^^^^ the trait `Bar` is not implemented for `S`
   |
   = help: consider adding a `where S: Bar` bound
note: required by `Bar::BAR`
  --> src/lib.rs:8:5
   |
8  |     const BAR: usize;
   |     ^^^^^^^^^^^^^^^^^
```

`rustc` should say something along the lines of "you can't do this just yet".

**Comment by estebank** [comment] 2019-12-13 19:59
Current output, still problematic:

```
error[E0599]: no associated item named `BAR` found for type `S` in the current scope
  --> file12.rs:12:19
   |
12 |     data: [u8; S::BAR],
   |                   ^^^ associated item not found in `S`
   |
   = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `BAR`, perhaps you need to restrict type parameter `S` with it:
   |
11 | struct Array<S: Bar> where S: Bar {
   |              ^^^^^^
```

**Comment by brunoczim** [comment] 2020-01-09 22:02
Are there any ideas about when this will be possible (using generic associated constants on array lenght)?

**Comment by eddyb** [comment] 2020-04-07 14:39
Closing as duplicate of #43408.

**Closed** 2020-04-07 14:40 UTC
Labels: A-associated-items, A-const-eval, A-const-generics, A-diagnostics, D-confusing, D-invalid-suggestion, T-compiler
