### ISSUE TITLE
rustdoc replaces aliases used as trait type parameters

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#83675] opened 2021-03-30 10:35 UTC
```rust
use std::os::raw::c_long;

pub struct S(c_long);

impl From<c_long> for S {
    fn from(i: c_long) -> S { S(i) }
}
```

The documentation for the `S` trait implementations looks like this:

![image](https://user-images.githubusercontent.com/18604588/112975460-f8f43880-9153-11eb-9be3-851fa234e6f4.png)

While the `from` function itself is documented correctly to take a parameter of type `c_long`, the `From` trait has type parameter `i64` instead of `c_long`. I expected it to be `impl From<c_long> for S` instead.

### Meta

`rustc +nightly --version`:
```
rustc 1.53.0-nightly (4a20eb6a9 2021-03-28)
```

**Comment by jyn514** [comment] 2021-03-30 14:57
Duplicate of https://github.com/rust-lang/rust/issues/80557.

**Closed by jyn514** 2021-03-30 14:57 UTC
Labels: C-bug, T-rustdoc
