### ISSUE TITLE
Compiler panic.

### ISSUE THREAD

**Issue by lukebitts** [rust-lang/rust#31823] opened 2016-02-22 21:13 UTC
I was refactoring some code when this happened. I don't know what exactly causes it so I'm attaching the project. It's not really big, 4 files, 2 are empty and the other is the lib file which just re-exports things. The code probably shouldnt work even without the compiler panic since I was just copy pasting before fixing the dependencies.

Removing `use super::*;` from the quaternion.rs file "fixes" it.

**Edit**: replacing the line above with `use super::{Matrix4, Vector3, atan2, cross};` allows the project to compile.

[math.txt](https://github.com/rust-lang/rust/files/141434/math.txt)
(This is a zip file, I had to rename it because github wouldn't let me upload. Just rename it back to .zip)
## Meta

`rustc --version --verbose`:
rustc 1.8.0-nightly (57c357d89 2016-02-16)
binary: rustc
commit-hash: 57c357d89183df173b0e42a0f745d9cfdb67fb1a
commit-date: 2016-02-16
host: x86_64-pc-windows-gnu
release: 1.8.0-nightly

Backtrace:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'couldn't find node id 0 in the AST map', ../src/librustc\front\map/mod.rs:383
stack backtrace:
   0:         0x64c40d2c - strncmp
   1:         0x64c403ac - strncmp
   2:         0x64c04d6f - strncmp
   3:         0x64c055cb - strncmp
   4:         0x63aa705f - strncmp
   5:          0x5931cb0 - strncmp
   6:          0x5876a5e - strncmp
   7:         0x63d008bf - strncmp
   8:         0x63cfc22a - strncmp
   9:         0x63d0095b - strncmp
  10:         0x63d2138d - strncmp
  11:         0x63150fab - strncmp
  12:         0x6314a499 - strncmp
  13:         0x631461f2 - strncmp
  14:         0x63116ddd - strncmp
  15:         0x631061c1 - strncmp
  16:         0x6310377b - strncmp
  17:         0x64c2d6fa - strncmp
  18:         0x6310401c - strncmp
  19:         0x64c3ea69 - strncmp
  20:         0x76dc652c - strncmp

Could not compile `luck_math`.
```

**Comment by Stebalien** [comment] 2016-02-23 16:14
I can't reproduce on `rustc 1.8.0-nightly (c92e910c1 2016-02-21)` (linux, x86_64).

**Comment by Mark-Simulacrum** [comment] 2017-04-30 19:23
Checked with `rustc 1.18.0-nightly (036983201 2017-04-26)`. Cannot reproduce, though had to remove clippy due to dependency on rustc_front, which no longer exists... closing.

**Closed by Mark-Simulacrum** 2017-04-30 19:23 UTC
Labels: I-ICE
