### ISSUE TITLE
de-sugarring of async functions

### ISSUE THREAD

**Issue by petar-dambovaliev** [rust-lang/rust#82267] opened 2021-02-18 17:16 UTC
I expect this code to work.

```rust
async fn foo(
    _rp: &str,
    _b: &str,
    msg: &'static str,
) -> Result<String, ()> {
    let res = format!("{}", msg);
    Ok(res)
}
```

Instead, i got an error

```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
   --> tests/middleware.rs:152:6
    |
152 | ) -> Result<String, Infallible> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: hidden type `impl std::future::Future` captures lifetime smaller than the function body
```

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-apple-darwin
release: 1.49.0

```

If you remove one of the arguments, it works.
Which is rather strange.

```rust
async fn foo(
    _b: &str,
    msg: &'static str,
) -> Result<String, ()> {
    let res = format!("{}", msg);
    Ok(res)
}
```

**Comment by sfackler** [comment] 2021-02-18 18:09
Duplicate of #63033

**Closed by sfackler** 2021-02-18 18:09 UTC
Labels: C-bug
