### ISSUE TITLE
Unwinding in a drop() implementation skips remaining drops

### ISSUE THREAD

**Issue by dotdash** [rust-lang/rust#28387] opened 2015-09-13 12:02 UTC
Given this:
```rust
struct S;

impl Drop for S {
    fn drop(&mut self) {
        println!("Dropping S");
        panic!("DIE");
    }
}

struct T;
impl Drop for T {
    fn drop(&mut self) {
        println!("Dropping T");
    }
}
fn main() {
    let t = T;
    let s = S;
}
```

The output is:
```
Dropping S
thread '<main>' panicked at 'DIE', nounwind.rs:6
```

The `drop()` call for T is completely skipped, while I would have expected it to be called.

**Comment by dotdash** [comment] 2015-09-13 12:02
cc @rust-lang/lang @rust-lang/compiler

**Comment by steveklabnik** [comment] 2015-09-13 12:04
A double `panic` is an abort, no?

**Comment by dotdash** [comment] 2015-09-13 12:23
The is no double panic here.

**Comment by arielb1** [comment] 2015-09-13 13:59
Duplicate of #14875

**Closed by arielb1** 2015-09-13 13:59 UTC
