### ISSUE TITLE
rustc hangs on malformed format!() w/ first arg being a macro invocation declaring a type with a #[derive]

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#47188] opened 2018-01-04 16:35 UTC
```rust
macro_rules! foo {
    () => {
        {
            #[derive(Clone)]
            struct Ty;

            ""
        }
    }
}

fn main() {
    format!(foo!());
}
```

rustc seems to sit there consuming 100% CPU indefinitely. This code isn't valid because `format!()` wants a string literal as first argument, but it doesn't seem to get around to complaining about it, so I assume it's getting stuck somewhere formatting an error message.

**Comment by steffengy** [comment] 2018-01-11 07:31
Duplicate/Related to #44692

**Comment by steffengy** [comment] 2018-01-12 20:26
Seems like this causes an infinite loop in [libsyntax_pos/lib.rs#macro_backtrace](https://github.com/rust-lang/rust/blob/0258c6dacaa6e187ae9bf744fd3184e79f78f2ef/src/libsyntax_pos/lib.rs#L333).

The loop referenced above results in the same span for each iteration:
```rust
ExpnInfo { call_site: Span { lo: BytePos(86), hi: BytePos(96), ctxt: #4 }, 
callee: NameAndSpan { format: MacroAttribute(derive(Clone)), allow_internal_unstable: true, 
allow_internal_unsafe: false, span: None } }
ExpnInfo { call_site: Span { lo: BytePos(86), hi: BytePos(96), ctxt: #4 }, 
callee: NameAndSpan { format: MacroAttribute(derive(Clone)), allow_internal_unstable: true, 
allow_internal_unsafe: false, span: None } }
ExpnInfo { call_site: Span { lo: BytePos(86), hi: BytePos(96), ctxt: #4 }, 
callee: NameAndSpan { format: MacroAttribute(derive(Clone)), allow_internal_unstable: true, 
allow_internal_unsafe: false, span: None } }
ExpnInfo { call_site: Span { lo: BytePos(86), hi: BytePos(96), ctxt: #4 }, 
callee: NameAndSpan { format: MacroAttribute(derive(Clone)), allow_internal_unstable: true, 
allow_internal_unsafe: false, span: None } }
```

This seems to be related to the `#[derive(Clone)]` invocation, omitting it doesn't yield this error
and results in:
```rust
ExpnInfo { call_site: Span { lo: BytePos(5505012), hi: BytePos(5505043), ctxt: #2 }, 
callee: NameAndSpan { format: MacroBang(format_args), allow_internal_unstable: true, 
allow_internal_unsafe: false, span: None } }
ExpnInfo { call_site: Span { lo: BytePos(156), hi: BytePos(172), ctxt: #0 }, 
callee: NameAndSpan { format: MacroBang(format), allow_internal_unstable: false, 
allow_internal_unsafe: false, 
span: Some(Span { lo: BytePos(5504957), hi: BytePos(5505047), ctxt: #0 }) } }
ExpnInfo { call_site: Span { lo: BytePos(5505012), hi: BytePos(5505043), ctxt: #2 }, 
callee: NameAndSpan { format: MacroBang(format_args), allow_internal_unstable: true, 
allow_internal_unsafe: false, span: None } }
ExpnInfo { call_site: Span { lo: BytePos(156), hi: BytePos(172), ctxt: #0 }, 
callee: NameAndSpan { format: MacroBang(format), allow_internal_unstable: false, 
allow_internal_unsafe: false, 
span: Some(Span { lo: BytePos(5504957), hi: BytePos(5505047), ctxt: #0 }) } }
```

Notably, using the expanded version of `#[derive(Clone)]` generated with  `--pretty=expanded` in the macro declaration, also doesn't lead to the bug mentioned here.

Therefore it's possible, this is actually an issue with proc_macros/derive generating unexpected (in this case possibly self-referencing?) spans in an macro-invocation?

**Comment by dtolnay** [comment] 2019-02-19 21:58
Closing as a duplicate of #44692.

**Closed by dtolnay** 2019-02-19 21:58 UTC
Labels: A-macros, C-bug, I-compiletime
