### ISSUE TITLE
Trait bounds are not propagated through type equality constraints

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/rust#85243] opened 2021-05-13 03:33 UTC
I tried this code:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e13f9ef0a5c88c03fca13d57418f4986
```rust
pub trait Trait1 {
    fn f();
}

pub trait Trait2 {
    type Type: Trait1;
}

pub trait Trait3 {
    type Type2: Trait2<Type = Self>;
    fn f2() {
        <Self as Trait1>::f();
    }
}
```

I expected to see this compile successfully since in `Trait3`, `Self` is guaranteed to implement `Trait1` because `Self = Trait2::Type` and `Trait2::Type: Trait1`.

Instead, this happened:
```
error[E0277]: the trait bound `Self: Trait1` is not satisfied
```

**Comment by jonas-schievink** [comment] 2021-05-13 12:17
Duplicate of https://github.com/rust-lang/rust/issues/20671

**Closed by jonas-schievink** 2021-05-13 12:17 UTC
Labels: C-bug
