### ISSUE TITLE
compiler panic

### ISSUE THREAD

**Issue by galich** [rust-lang/rust#58971] opened 2019-03-06 14:45 UTC
Nightly compiler started to panic today

```
error: internal compiler error: src\librustc_codegen_llvm\debuginfo\metadata.rs:661: debuginfo: unexpected type in type_metadata: impl std::future::Future
thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:620:9
stack backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_predicate
   4: std::panicking::rust_panic_with_hook
   5: <rustc_errors::emitter::ColorConfig as core::fmt::Debug>::fmt
   6: rustc_errors::Handler::bug
   7: rustc::util::bug::bug_fmt
   8: rustc::ty::context::<impl rustc::infer::canonical::Canonical<'gcx, rustc::ty::context::UserType<'gcx>>>::is_identity
   9: rustc::ty::context::<impl rustc::infer::canonical::Canonical<'gcx, rustc::ty::context::UserType<'gcx>>>::is_identity
  10: rustc::ty::context::<impl rustc::infer::canonical::Canonical<'gcx, rustc::ty::context::UserType<'gcx>>>::is_identity
  11: rustc::util::bug::bug_fmt
  12: rustc::util::bug::bug_fmt
  13: <rustc_codegen_llvm::back::write::DiagnosticHandlers<'a> as core::ops::drop::Drop>::drop
  14: rustc_codegen_llvm::debuginfo::<impl rustc_codegen_ssa::traits::debuginfo::DebugInfoBuilderMethods<'tcx> for rustc_codegen_llvm::builder::Builder<'a, 'll, 'tcx>>::declare_local
  15: <rustc_codegen_llvm::llvm_::ffi::PassKind as core::fmt::Debug>::fmt
  16: <rustc_codegen_llvm::llvm_::ffi::debuginfo::DISPFlags as core::fmt::Debug>::fmt
  17: <unknown>
  18: rustc_codegen_llvm::type_::<impl rustc_codegen_ssa::traits::type_::LayoutTypeMethods<'tcx> for rustc_codegen_llvm::context::CodegenCx<'ll, 'tcx>>::reg_backend_type
  19: <unknown>
  20: <rustc_codegen_llvm::base::ValueIter<'ll> as core::iter::traits::iterator::Iterator>::next
  21: <rustc_codegen_llvm::llvm_::ffi::debuginfo::DISPFlags as core::fmt::Debug>::fmt
  22: <rustc_codegen_llvm::base::ValueIter<'ll> as core::iter::traits::iterator::Iterator>::next
  23: rustc_codegen_llvm::type_::<impl rustc_codegen_ssa::traits::type_::LayoutTypeMethods<'tcx> for rustc_codegen_llvm::context::CodegenCx<'ll, 'tcx>>::reg_backend_type
  24: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  25: <env_logger::fmt::WriteStyle as core::default::Default>::default
  26: rustc_driver::driver::phase_4_codegen
  27: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  28: <env_logger::Logger as log::Log>::flush
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler
  31: <env_logger::Logger as log::Log>::flush
  32: rustc_driver::run_compiler
  33: <env_logger::Logger as log::Log>::flush
  34: <env_logger::fmt::WriteStyle as core::default::Default>::default
  35: _rust_maybe_catch_panic
  36: <env_logger::fmt::WriteStyle as core::default::Default>::default
  37: std::sys::windows::thread::Thread::new
  38: BaseThreadInitThunk
  39: RtlUserThreadStart
query stack during panic:
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.35.0-nightly (f22dca0a1 2019-03-05) running on x86_64-pc-windows-msvc

note: compiler flags: -Z unstable-options -C debuginfo=2 -C incremental -C target-feature=+crt-static --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden
```

**Comment by jonas-schievink** [comment] 2019-03-06 15:22
Duplicate of https://github.com/rust-lang/rust/issues/58888

**Closed by jonas-schievink** 2019-03-06 15:22 UTC
