### ISSUE TITLE
Infinite Loop of Errors (rustc 1.8.0-nightly (d5558825b 2016-02-28))

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/rust#31988] opened 2016-03-01 16:31 UTC
On `rustc 1.8.0-nightly (d5558825b 2016-02-28)` attempting to compile the source 

```rust
#[test]
fn entity_offset_container_test() {
    let 
}
```

results in the following output from the compiler:

```
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
          ^
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
          ^
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
          ^
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
          ^
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
          ^
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
          ^
test.rs:5:1: 5:2 error: unexpected token: `<eof>`
test.rs:5 }
```

Repeated on indefinitely.

**Comment by mitaa** [comment] 2016-03-01 16:44
Duplicate of #31804

**Closed** 2016-03-01 17:17 UTC
