### ISSUE TITLE
Inner match doesn't narrow exhaustiveness scope based on outer binding

### ISSUE THREAD

**Issue by HackAttack** [rust-lang/rust#77542] opened 2020-10-04 19:48 UTC
It seems like the following should compile
```rust
enum Enum {
    A,
    B,
    C,
}

fn main() {
    match Enum::A {
        x @ Enum::A | x @ Enum::B => match x {
            Enum::A => println!("a"),
            Enum::B => println!("b"),
            // _ => unreachable!(),  // Won't compile without this line
        }
        Enum::C => println!("c"),
    }
}
```
because the inner match only executes on `A` and `B`. But exhaustiveness is checked over the whole enum even though only a subset of variants are possible in this context.

Maybe related: #8391

**Comment by jonas-schievink** [comment] 2020-10-04 19:54
Hi! This is currently working as intended, and changing this would be a language change. Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Closed by jonas-schievink** 2020-10-04 19:54 UTC
