### ISSUE TITLE
MIR always initializes variables with them in (debuginfo) scope.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#32949] opened 2016-04-14 12:29 UTC
That is, given `let x = expr;`, MIR will produce the same code as `let x; x = expr;` (modulo borrows).
When breaking inside `expr` in a debugger, `x` will be in scope, uninitialized.
It can be really annoying when dealing with shadowing or arguments.
For example, if you break on the call in `let x = ...; let x = f(x);` and try to print `x`, you will get the second `x`, which is uninitialized at that point.

cc @michaelwoerister

**Comment by michaelwoerister** [comment] 2016-04-14 14:04
This might be interesting here: https://github.com/rust-lang/rust/blob/c9f15013e0edc80989bf40b358bcefee14be5050/src/librustc_trans/debuginfo/create_scope_map.rs#L246

How would I best be able to take a look at what the scoping structure of a function looks like (i.e. what expression is assigned to what scope)?

**Comment by eddyb** [comment] 2016-04-14 14:07
@michaelwoerister MIR scopes? `rustc --unpretty=mir -Z unstable-options` on master should print scope IDs for all variables, statements and terminators.

**Comment by michaelwoerister** [comment] 2016-04-14 14:09
@eddyb Thanks! I'll take a look.

**Comment by michaelwoerister** [comment] 2016-04-14 17:03
r? @michaelwoerister
I'll review this if nobody minds.

**Comment by michaelwoerister** [comment] 2016-04-14 21:34
@eddyb This looks rather suspicious to me:
https://github.com/rust-lang/rust/blob/8b0937293bdb70ab4a5efed02b90a71af2b234f6/src/librustc_mir/build/block.rs#L55
At least from a visibility point of view, the init-scope should not be nested within the remainder-scope.

**Comment by eddyb** [comment] 2016-04-14 21:38
@michaelwoerister that nesting is necessary for MIR borrowck AFAICT - if a variable is not in scope, you can't actually initialize it, since it doesn't exist.

**Comment by michaelwoerister** [comment] 2016-04-14 21:55
Hm, then I'm inclined to suggest that we do not re-use these scopes for debuginfo and instead build an additional *visibility* scope tree, as not to conflate two things that are not really the same.

**Comment by eddyb** [comment] 2016-04-16 19:00
How terrible would it be to have two scopes, one starting before the `let` and one after it?
The visibility problems would be fixed by having each `VarDecl` track two scopes, the one in which it's declared and the one in which it's initialized.

**Comment by michaelwoerister** [comment] 2016-04-16 23:49
So, the this code...
```rust
let x = 3 + 4;
<subsequent statements>
```
... would map to the following?
```rust
{ // "lifetime scope"
    let x;
    {  // "initializer scope"
        tmp1 = 3 + 4;
        x = tmp1;
    }
    {  // scope within which x is visible, i.e. "remainder scope" of the let binding
        <subsequent statements>
    }
}
```
That would be worth a try, I think. If it turns out not to cause to many problems with "accidental" interactions with borrow-checking, it would save us the work of maintaining two scope trees.

**Comment by eddyb** [comment] 2016-04-16 23:52
@michaelwoerister Yeah, that's what I meant. I'm pretty sure it can work, although I'd like someone who actually is going to work on MIR borrowck look at it. @nikomatsakis?

**Comment by nikomatsakis** [comment] 2016-04-19 19:29
@eddyb having an extra scope (the innermost enclosing block) seems... fine. I'm still somewhat unconvinced that we want those variables to be visible before you have stepped to the `let` in question though, but I guess that's a (somewhat) separate question.

**Comment by eddyb** [comment] 2016-04-19 19:32
@nikomatsakis Why would they be visible before? I'm only suggesting changing the scope we use in debuginfo from starting "just before the `let`" to " just after the `let`", i.e. not including the `let` RHS.

**Comment by nikomatsakis** [comment] 2016-04-20 20:15
@eddyb oh, hmm, I was not understanding what you meant. The issue is that today the "suffix" scopes include the initializer, and you would rather that they do not? In any case, having an extra scope seems fine.

**Comment by eddyb** [comment] 2016-04-20 20:25
@nikomatsakis Correct, that would result in the expected behavior in a debugger.
But borrowck has to know that the initializer is in the scope of the definition, doesn't it?
Can we actually get away with only recording the post-initializer "suffix"?
Because that's the trivial fix @michaelwoerister mentioned, for `let`, while `match` already works like that.

**Comment by nikomatsakis** [comment] 2016-04-21 20:55
@eddyb I think borrowck does want the lifetime to include the initializer, in order to allow things like `let foo = &3`

**Comment by eddyb** [comment] 2016-04-27 12:13
So it appears that the whole "definition scope" isn't used right now, but rather "remainder scope", which is the visibility scope, and the problem, as @michaelwoerister pointed out, is that the initializer scope is nested in it at the MIR level (its parent is the remainder scope), *even though* they're not lexically nested.

**Closed** 2016-06-08 23:41 UTC
Labels: A-debuginfo, A-mir
