### ISSUE TITLE
derive Clone fails for struct with associated type field 

### ISSUE THREAD

**Issue by thiolliere** [rust-lang/rust#44876] opened 2017-09-26 21:54 UTC
(on stable, beta and nightly) the following code fails to compile:
```rust
trait Toto {
    type Item: Clone;
}

struct A;

impl Toto for A {
    type Item = ();
}

#[derive(Clone)]
struct Tata<T: Toto> {
    tata: T::Item,
}

fn main() {
    let tata = Tata::<A>{
        tata: ()
    };
    tata.clone();
}
```
error is:
```
error[E0599]: no method named `clone` found for type `Tata<A>` in the current scope
  --> src/main.rs:34:10
   |
34 |     tata.clone();
   |          ^^^^^
   |
   = note: the method `clone` exists but the following trait bounds were not satisfied:
           `Tata<A> : std::clone::Clone`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `clone`, perhaps you need to implement it:
           candidate #1: `std::clone::Clone`
```

if we implement clone by hand it works

**Comment by stephaneyfx** [comment] 2017-09-26 23:39
AFAIK, deriving `Clone` for a generic type generates an implementation with `Clone` trait bounds for the type parameters. In your case, this means:

```rust
impl<T: Clone + Toto> Clone for Tata<T> where T::Item: Clone {...}
```

This can be verified by passing `-Z unstable-options --pretty expanded` to nightly rustc.

**Comment by cuviper** [comment] 2017-09-28 21:28
Right, you'll get a `T: Clone` bound per #26925.

**Comment by nagisa** [comment] 2017-10-05 16:00
Closing as a duplicate of #26925.

**Closed by nagisa** 2017-10-05 16:00 UTC
