### ISSUE TITLE
Highlighted items are hidden in rustdoc

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust#57712] opened 2019-01-17 20:49 UTC
(Originally filed as https://github.com/rustwasm/wasm-bindgen/issues/1192; +cc @liamcurry)

> Highlighted items are hidden in the Github pages API docs. Tested in Brave and Firefox.
>
> - Example `gh-pages` URL: https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Element.html#method.set_inner_html
> - Example `docs.rs` URL: https://docs.rs/web-sys/0.3.9/web_sys/struct.Element.html#method.set_inner_html
>
> Highlighted items are invisible due this selector in `rustdoc.css`:
>
> ```css
> .in-band, code {
>     z-index: -5;
> }
> ```
>
> ![image](https://user-images.githubusercontent.com/77758/51337699-d1729300-1a55-11e9-8cd4-fc7629569653.png)
> 
> versus
>
> ![image](https://user-images.githubusercontent.com/77758/51337731-e64f2680-1a55-11e9-9d74-ea18da62a237.png)

**Comment by Centril** [comment] 2019-01-17 22:39
@fitzgen Seems like a dupe of https://github.com/rust-lang/rust/issues/57628?

**Comment by QuietMisdreavus** [comment] 2019-01-17 22:42
Yes, this is a duplicate. There's also an open PR to fix it: https://github.com/rust-lang/rust/pull/57646 I'm closing this as a duplicate.

**Closed by QuietMisdreavus** 2019-01-17 22:42 UTC
Labels: C-bug, T-rustdoc

**Comment by fitzgen** [comment] 2019-01-17 22:55
Thanks! :)
