### ISSUE TITLE
Cannot use `Self` to construct a tuple struct in a macro

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#57523] opened 2019-01-11 18:06 UTC
Reproduced on both on beta and nightly (not tested on stable since #51994 wasn't stabilized in 1.31).

```rust
#![warn(clippy::use_self)]

pub struct S(pub u16);

impl From<u8> for S {
    fn from(a: u8) -> Self {
        Self(a.into())            // <-- this is fine
    }
}

macro_rules! a {
    () => {
        impl From<u16> for S {
            fn from(a: u16) -> Self {
                // S(a)            // <-- this is fine but triggers the `clippy::use_self` warning
                Self(a)            // <-- ERROR E0423
                // Self { 0: a }   // <-- this is fine but ugly
            }
        }
    }
}

a!();

fn main() {}
```

This is particularly troublesome on nightly since `clippy::use_self` is recently upgraded to emit the lint in a local macro thanks to rust-lang/rust-clippy#3627, but the suggestion failed to compile.

**Comment by varkor** [comment] 2019-01-11 23:03
[This also applies to type aliases](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=658cc61fa2cf92c2adbfd14fd97a4a2f).
```rust
struct T;

type B = T;

macro_rules! a {
    () => {
        impl T {
            fn b() -> B {
                B()
            }
        }
    }
}

a!();
```
I suspect this is to do with
https://github.com/rust-lang/rust/blob/b43986184b8f4e0d633e8ae1704f0e19aec30cb2/src/librustc_resolve/lib.rs#L3557-L3558
cc @alexreg

**Comment by alexreg** [comment] 2019-01-11 23:37
Yes, I think @varkor is right.

@petrochenkov Maybe you could elaborate on this FIXME? What's stopping us from resolving paths in the macro NS here?

**Comment by petrochenkov** [comment] 2019-01-12 23:07
That FIXME is unrelated to the issue.
The issue is that `Self` in value namespace accidentally uses "`let` variable hygiene" rather than "item hygiene", so `macro_rules` "hides" it from the outside world like it would do for a `let` variable.

Regarding type aliases, `B` defined by `type B = T;` doesn't exist in value namespace, so `B()` doesn't resolve (with or without macros).

**Comment by petrochenkov** [comment] 2019-01-12 23:10
@varkor 
Looks like const generic parameters in https://github.com/rust-lang/rust/pull/53645 have the same issue.

**Comment by petrochenkov** [comment] 2019-01-12 23:35
Fixed in https://github.com/rust-lang/rust/pull/57560

**Comment by alexreg** [comment] 2019-01-12 23:54
@petrochenkov Ahh, that makes perfect sense. Feel free (but not obliged) to r? me for that PR.

**Closed** 2019-01-13 14:36 UTC
Labels: C-bug, T-compiler
