### ISSUE TITLE
Unsized type allowed in array declaration

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#70607] opened 2020-03-31 12:18 UTC
I tried this code:

```Rust
type A = [dyn Send; 2];
```

I expected to see this happen: Fail to compile because an array doesn't allow DST's

Instead, this happened: It just compiled

### Meta

`rustc --version --verbose`:
```
stable, beta and nightly
```

Whenever the type is used:
```Rust
type A = [dyn Send; 2];

fn using(a: A) {}
```

rustc complains correctly:
```
 Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `(dyn std::marker::Send + 'static)` cannot be known at compilation time
 --> src/lib.rs:3:1
  |
3 | fn using(a: A) {}
  | ^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `(dyn std::marker::Send + 'static)`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: slice and array elements must have `Sized` type

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Comment by jonas-schievink** [comment] 2020-03-31 12:30
duplicate of https://github.com/rust-lang/rust/issues/44075

**Closed by jonas-schievink** 2020-03-31 12:30 UTC
Labels: C-bug
