### ISSUE TITLE
2020-09-05 Nightly type ascription errors on macOS/Linux/Windows

### ISSUE THREAD

**Issue by CleanCut** [rust-lang/rust#76428] opened 2020-09-07 03:52 UTC
Amethyst game engine's [CI](https://github.com/amethyst/amethyst/pull/2455/checks?check_run_id=1078901336) crashes with type ascription errors on `rustc 1.48.0-nightly (cdc8f0606 2020-09-05)`

```shell
# macOS
cargo test --workspace --features=metal,tiles

# Linux, Windows
cargo test --workspace --features=vulkan,tiles
```

I expected to see this happen: Relatively the same result as stable/beta.

Instead, nightly failed while both beta and stable passed.  See [this run](https://github.com/amethyst/amethyst/pull/2455/checks?check_run_id=1078901336)

```
error: expected type, found `:`
  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-texture-0.4.1\src\format\image.rs:85:10
   |
85 | #[derive(Derivative, Debug, Clone, PartialEq, Eq)]
   |          ^^^^^^^^^^
   |          |
   |          expected type
   |          tried to parse a type due to this type ascription
   |          while parsing this struct
   |
   = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`
   = note: see issue #23416 <https://github.com/rust-lang/rust/issues/23416> for more information

error: expected expression, found `:`
  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-texture-0.4.1\src\format\image.rs:85:10
   |
85 | #[derive(Derivative, Debug, Clone, PartialEq, Eq)]
   |          ^^^^^^^^^^
   |          |
   |          expected expression
   |          while parsing this struct

error: proc-macro derive produced unparseable tokens
  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-texture-0.4.1\src\format\image.rs:85:10
   |
85 | #[derive(Derivative, Debug, Clone, PartialEq, Eq)]
   |          ^^^^^^^^^^

error[E0560]: struct `ImageTextureConfig` has no field named `gfx_hal`
  --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\rendy-texture-0.4.1\src\format\image.rs:85:10
   |
85 | #[derive(Derivative, Debug, Clone, PartialEq, Eq)]
   |          ^^^^^^^^^^ `ImageTextureConfig` does not have this field
   |
   = note: available fields are: `format`, `repr`, `kind`, `sampler_info`, `generate_mips`, `premultiply_alpha`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0560`.
error: could not compile `rendy-texture`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
##[error]Process completed with exit code 1.
```

**Comment by jyn514** [comment] 2020-09-07 04:49
Are you sure this is because of type ascription? It looks like something is going wrong in the proc macro.

Does `cargo expand` work if the project doesn't compile? I'd be interested to see what changed on nightly.

**Comment by CleanCut** [comment] 2020-09-08 00:14
> Are you sure this is because of type ascription? It looks like something is going wrong in the proc macro.

No, I'm not at all sure. I'm just pulling that out of the first error: `tried to parse a type due to this type ascription`.

> Does `cargo expand` work if the project doesn't compile? I'd be interested to see what changed on nightly.
`cargo expand` run under `rustc 1.48.0-nightly (73dc675b9 2020-09-06)`  appears to fail with [the same error (attached)](https://github.com/rust-lang/rust/files/5185432/output.txt).

**Comment by jyn514** [comment] 2020-09-08 00:25
Might be related to https://github.com/rust-lang/rust/issues/76399

**Comment by jyn514** [comment] 2020-09-08 00:26
Going to close this as a duplicate of https://github.com/rust-lang/rust/issues/76399 since it looks like the same issue.

**Closed by jyn514** 2020-09-08 00:26 UTC
Labels: A-proc-macros, C-bug, regression-from-stable-to-nightly
