### ISSUE TITLE
cargo check --message-format json regression of error span data on empty main.rs file

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust#68808] opened 2020-02-03 20:57 UTC
**Problem**
`cargo check --message-format json` returns invalid span data, particularly `line_end` and `line_start` are set to 0, though [it is guaranteed to be 1-based](https://github.com/oli-obk/cargo_metadata/blob/master/src/diagnostic.rs#L58-L61).
This happens with a completly empty `main.rs` file.

Tested on the following cargo version:
`cargo 1.42.0-nightly (9d32b7b01 2020-01-26)`

Whilst on the stable version the returned span array is empty:
`cargo 1.41.0 (626f0f40e 2019-12-03)`

**Steps**
1. Clone [this repo](https://github.com/Veetaha/cargo-check-regression-1.42-nightly)
2. Run `rustup default nightly`
3. Run `cargo check --message-format json > check.json`

Now you can see invalid span in `check.json` file.

I've already created and formatted `check-1.41.json` and `check-1.42.json` files with the output of different cargo versions.
Here are the crutial differences [1.41](https://github.com/Veetaha/cargo-check-regression-1.42-nightly/blob/861f9913465a8b880aee1e8e0d6ffa906c3fc637/check-1.41.json#L28) and [1.42](https://github.com/Veetaha/cargo-check-regression-1.42-nightly/blob/861f9913465a8b880aee1e8e0d6ffa906c3fc637/check-1.42.json#L28-L46)

**Context**
[The issue was initially reported at rust-analyzer project repo here.](https://github.com/rust-analyzer/rust-analyzer/issues/2973)

**Comment by ehuss** [comment] 2020-02-03 21:34
Moved to rust-lang/rust, where diagnostics live.

Seems to be caused by #67770, cc @Centril.

**Comment by Veetaha** [comment] 2020-02-03 22:14
@Centril additional info:
The regression is also present on the older version of nightly rustc:
`rustc 1.42.0-nightly (b5a3341f1 2020-01-20)`

This was the version I spotted the issue initially, but then updated and rechecked, but it was still present in `cargo 1.42.0-nightly (9d32b7b01 2020-01-26)`.

**Comment by Centril** [comment] 2020-02-03 23:02
Probably caused by https://github.com/rust-lang/rust/pull/67770/commits/20ebb807d523947f5fac710c4ae95ac9730ad995.

**Comment by pnkfelix** [comment] 2020-02-06 13:57
triage: P-high. Assigning to self.

**Closed** 2020-03-23 22:02 UTC
Labels: A-diagnostics, P-high, T-compiler, regression-from-stable-to-nightly
