### ISSUE TITLE
`rust-docs` and `rustc-docs` components conflict at `share/doc/rust/html/rustc`

### ISSUE THREAD

**Issue by kkysen** [rust-lang/rust#108535] opened 2023-02-07 00:40 UTC
### Problem

The `rust-docs` and `rustc-docs` components cannot be installed at the same time, as they conflict at `share/doc/rust/html/rustc` and `share/doc/rust/html`.  Only one of them can be installed at a single time, but I don't see a reason why they can't have different install locations and coexist.

If `rust-docs` is installed already, then `rustup component add rustc-docs` fails with `detected conflict: 'share/doc/rust/html/rustc'`.

If `rustc-docs` is installed already, then `rustup component add rust-docs` fails with `detected conflict: 'share/doc/rust/html'`.

### Steps

```sh
rustup component add rust-docs rustc-docs
```

More interactively, this is what happens when they're added and removed in different orders:

```shell
~/work/rust via 🐏 1GiB/8GiB | 0B/2GiB took 15ms
•100% at 07:29:58 PM ❯ cargo new rustup-component-test
     Created binary (application) `rustup-component-test` package

~/work/rust via 🐏 1GiB/8GiB | 0B/2GiB took 513ms
•100% at 07:30:04 PM ❯ cd rustup-component-test/

rustup-component-test on  master is 📦 v0.1.0 via 🦀 v1.67.0 via 🐏 1GiB/8GiB | 0B/2GiB took 7ms
✦ •100% at 07:30:06 PM ❯ rustup component add rustc-docs
info: downloading component 'rustc-docs'
info: installing component 'rustc-docs'
 17.0 MiB /  17.0 MiB (100 %)   5.1 MiB/s in  3s ETA:  0s
info: rolling back changes
error: failed to install component: 'rustc-docs-x86_64-unknown-linux-gnu', detected conflict: 'share/doc/rust/html/rustc'

rustup-component-test on  master is 📦 v0.1.0 via 🦀 v1.67.0 via 🐏 1GiB/8GiB | 0B/2GiB took 4s945ms
•100% at 07:30:20 PM ❯ rustup component add rust-docs
info: component 'rust-docs' for target 'x86_64-unknown-linux-gnu' is up to date

rustup-component-test on  master is 📦 v0.1.0 via 🦀 v1.67.0 via 🐏 1GiB/8GiB | 0B/2GiB took 120ms
•100% at 07:30:25 PM ❯ rustup component remove rust-docs
info: removing component 'rust-docs'

rustup-component-test on  master is 📦 v0.1.0 via 🦀 v1.67.0 via 🐏 1GiB/8GiB | 0B/2GiB took 2s850ms
•100% at 07:30:37 PM ❯ rustup component add rustc-docs
info: downloading component 'rustc-docs'
info: installing component 'rustc-docs'
 17.0 MiB /  17.0 MiB (100 %)   5.1 MiB/s in  3s ETA:  0s

rustup-component-test on  master is 📦 v0.1.0 via 🦀 v1.67.0 via 🐏 1GiB/8GiB | 0B/2GiB took 3s842ms
•100% at 07:30:43 PM ❯ rustup component add rust-docs
info: downloading component 'rust-docs'
info: installing component 'rust-docs'
 19.3 MiB /  19.3 MiB (100 %)   3.6 MiB/s in  4s ETA:  0s
info: rolling back changes
error: failed to install component: 'rust-docs-x86_64-unknown-linux-gnu', detected conflict: 'share/doc/rust/html'
```

### Possible Solution(s)

Install `rust-docs` and `rustc-docs` in different locations so there's no conflict.

### Rustup version

```console
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.67.0 (fc594f156 2023-01-24)`
```

### Installed toolchains

```console
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/kkysen/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2019-12-05-x86_64-unknown-linux-gnu
nightly-2022-08-08-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.65.0-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by jyn514** [comment] 2023-02-27 16:59
Relevant code: https://github.com/rust-lang/rust/blob/ae5473c9699eaf1998c414e0a8884383bb9ddcc3/src/bootstrap/dist.rs#L148

**Comment by dfireBird** [comment] 2023-10-05 02:56
Can I work on this issue? I'm assuming it won't be as simple as changing the path in relevant code right? If so what do I need to do to make it a proper fix?

**Comment by matthiaskrgr** [comment] 2023-11-04 12:49
duplicate of https://github.com/rust-lang/rust/issues/75833

**Closed** 2023-11-04 12:49 UTC
Labels: E-mentor, T-bootstrap, E-medium, A-docs, T-infra
