### ISSUE TITLE
CI is shown stuck on github

### ISSUE THREAD

**Issue by 95th** [rust-lang/rust#63547] opened 2019-08-14 06:17 UTC
The CI seems to be stuck on Github and jobs are shown running for more than a day but it has actually completed in Azure.

![Capture](https://user-images.githubusercontent.com/22871609/62998376-f2368600-be88-11e9-9216-d2617dc8b754.PNG)

![Capture](https://user-images.githubusercontent.com/22871609/62998458-3e81c600-be89-11e9-9b62-0d90584f4f25.PNG)

**Comment by phansch** [comment] 2019-08-14 07:16
Probably a duplicate of https://github.com/rust-lang/rust/issues/63513

**Comment by pietroalbini** [comment] 2019-08-14 07:57
Yeah duplicate of #63513.

**Closed by pietroalbini** 2019-08-14 07:57 UTC
