### ISSUE TITLE
Bad formatting in `core::ops::range`

### ISSUE THREAD

**Issue by tadaHrd** [rust-lang/rust#110372] opened 2023-04-15 19:52 UTC
### Location

The core::ops::range module at line 43 (the `RangeFull` struct)

### Summary

At line 26:
```/// Used as a [slicing index], `RangeFull` produces the full array as a slice.```
This is because of code at line 38:
```/// [slicing index]: crate::slice::SliceIndex```

## This is how it looks:
Used as a [slicing index], `RangeFull` produces the full array as a slice.

## It should look like:
Used as a [slicing index](crate::slice::SliceIndex), `RangeFull` produces the full array as a slice.

**Comment by dawnofmidnight** [comment] 2023-04-15 23:56
This correctly renders on rustdoc, as this is valid markdown syntax.
https://doc.rust-lang.org/nightly/std/ops/struct.RangeFull.html
![image](https://user-images.githubusercontent.com/78233879/232258988-2d167b28-15dd-4ac1-a2ae-1df5aa2c999c.png)

**Comment by jyn514** [comment] 2023-04-16 03:40
I'm going to close this, it's not a bug.

**Closed by jyn514** 2023-04-16 03:40 UTC
Labels: A-docs

**Comment by tadaHrd** [comment] 2023-04-16 08:18
It's in VS Code

**Comment by jyn514** [comment] 2023-04-16 10:07
We cannot be responsible for bugs in other tools. If VSCode can't handle this, it should be changed upstream.
