### ISSUE TITLE
Using retain() on a vector a lot slower in version 1.38.0 than 1.36.0

### ISSUE THREAD

**Issue by Miguel-c-s** [rust-lang/rust#65970] opened 2019-10-30 15:53 UTC
I posted  [this](https://stackoverflow.com/q/58583031/10111567) on stackoverflow.

What happens is that when using retain over a vector, it seems to be a lot slower in version 1.38.0. 
host is: x86_64-unknown-linux-gpu (according to rustc--version --verbose) and LLVM version is 8.0.

I'm using ubuntu 19.04.

As I wrote on SO, I tried:
```
use std::time::Instant;
fn main() {
    let start = Instant::now();
    let mut my_vec:Vec<u32>;
    for _ in 0..100_000{
        my_vec = (0..10_000).collect();
        my_vec.retain(|&x| x < 9000);
        my_vec.retain(|&x| x < 8000);
        my_vec.retain(|&x| x < 7000);
        my_vec.retain(|&x| x < 6000);
        my_vec.retain(|&x| x < 5000);
        my_vec.retain(|&x| (x < 5) & (x > 2));
    }
    let duration = start.elapsed();
    println!("Program took: {:?}", duration);
}
```
And changed between versions with `rustup default 1.36.0` and `rustup default stable`, having updated rust before with `rustup update`.
p.s.: From my complete program I also noticed that version 1.38.0 was still a little bit slower *without* using retain(). But the difference was minimal (~5%) and hard to come up with another culprit.

**Comment by peterjoel** [comment] 2019-10-30 17:01
Performance of this code in 1.37 is similar to that in 1.36, so this would appear to be a regression in 1.38.

**Comment by mati865** [comment] 2019-10-30 18:03
Minimal example: https://godbolt.org/z/f81qSU

**Comment by Miguel-c-s** [comment] 2019-10-30 19:39
In the nightly version it takes about the same time as in stable.

**Comment by lzutao** [comment] 2019-10-30 19:41
stable is Rust 1.38.0?

**Comment by Miguel-c-s** [comment] 2019-10-30 19:44
yes, stable is 1.38.0.

**Comment by crgl** [comment] 2019-11-01 01:00
It seems like this might have been due to #61224 which was merged for 1.38.0; that fixes a soundness issue for Vec::drain_filter but might have slowed down retain (which just calls drain filter)

**Comment by Miguel-c-s** [comment] 2019-12-06 19:41
Will this ever be fixed or looked at?

**Comment by mati865** [comment] 2019-12-07 00:30
I bet it's fallout from upgrade to LLVM 9 but bisecting it would greatly help (either manually or with https://github.com/rust-lang/cargo-bisect-rustc/blob/master/TUTORIAL.md).

**Closed** 2019-12-15 10:11 UTC
Labels: A-LLVM, A-collections, C-bug, I-slow, T-compiler, regression-from-stable-to-stable
