### ISSUE TITLE
Rustc panics with comments with non-ascii characters after an error

### ISSUE THREAD

**Issue by Goncalerta** [rust-lang/rust#63444] opened 2019-08-10 17:20 UTC
Running this on playground:
```rust
struct A {}

fn main() {
    let a = A; // é
}
```

Panics rustc:
```
   Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'byte index 44 is not a char boundary; it is inside 'é' (bytes 43..45) of `struct A {}

fn main() {
    let a = A; // é
}
`', src/libcore/str/mod.rs:2034:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0 (a53f9df32 2019-07-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

Surpressing the comment:
```rust
struct A {}

fn main() {
    let a = A;
}
```

Makes it fail to compile as intended (without crashing):
```
   Compiling playground v0.0.1 (/playground)
error[E0423]: expected value, found struct `A`
 --> src/main.rs:4:13
  |
4 |     let a = A;
  |             ^ did you mean `A { /* fields */ }`?
help: possible better candidates are found in other modules, you can import them into scope
  |
1 | use futures::future::Either::A;
  |
1 | use tokio::prelude::future::Either::A;
  |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0423`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

Removing the line that does not compile: 
```rust
struct A { }

fn main() {
    // é 
}
```
Also prevents panicing.
```
   Compiling playground v0.0.1 (/playground)
warning: struct is never constructed: `A`
 --> src/main.rs:1:1
  |
1 | struct A { }
  | ^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/playground`
```
`// é` can be placed in a lot of places and still behave correctly:
```rust
struct A { 
    // é 
}
// é
fn main() {
    // é 
    let _ = 0; // é 
    let // é
    _ // é
    = // é
    A;
    let _ = 0;
} // é
```
But it can't be after the `A` if it is in the same block as `A` is:
 ```rust
struct A {}

fn main() {
    let _ = 0;
    let _ = A // é 
    ; // é 
    let _ = 0; // é 
}
```
*Any* of those three comments alone would trigger a rustc panic.

NOTE: `// é` was an arbitrary choice. I believe this happens with most (if not all) non-ascii characters.

**Comment by Goncalerta** [comment] 2019-08-10 17:36
Note that this won't panic:
(removed `;`)
```rust
struct A {}

fn main() {
    let a = A//é 
}
```
Nor will this:
(`é` appears after at least 52 characters after `A` (counting `//`))
```rust
struct A {}

fn main() {
    let a = A//34567890123456789012345678901234567890123456789012é 
    ;
}
```

**Comment by ehuss** [comment] 2019-08-10 18:08
I believe this is a duplicate of #61226.

**Comment by jonas-schievink** [comment] 2019-08-10 18:20
Yep, looks like it. Closing.

**Closed by jonas-schievink** 2019-08-10 18:20 UTC
Labels: A-diagnostics, A-parser, C-bug, I-ICE, I-nominated, T-compiler
