### ISSUE TITLE
stability break in rust 1.54: generic `Self` types are currently not permitted in anonymous constants

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#88888] opened 2021-09-12 15:49 UTC
I tried this code:

```rust
use std::arch::x86_64::*;

struct Test<const X: u8>;

impl<const X: u8> Test<X> {
    const Y: i32 = (X | (X << 2) | (X << 4) | (X << 6)) as i32;

    unsafe fn f(v: __m128i) -> __m128i {
        _mm_shufflelo_epi16(v, Self::Y)
    }
}
```

I expected to see this happen:

This code was accepted in Rust 1.53, so newer versions should also accept it.

Instead, this happened:

```
error: generic `Self` types are currently not permitted in anonymous constants
 --> <source>:9:32
  |
9 |         _mm_shufflelo_epi16(v, Self::Y)
  |                                ^^^^
  |
note: not a concrete type
 --> <source>:5:19
  |
5 | impl<const X: u8> Test<X> {
  |                   ^^^^^^^

error: aborting due to previous error
```

### Meta

Tested using rustc 1.53 and 1.54 (and newer) from Compiler Explorer.

**Comment by Mark-Simulacrum** [comment] 2021-09-12 15:59
I suspect this might actually be down to https://github.com/rust-lang/rust/issues/83167, but not sure.

**Comment by eduardosm** [comment] 2021-09-12 16:25
This example, which does not use const generics, also compiled in 1.53 and fails in newer versions:
```rust
use std::arch::x86_64::*;

trait GenU8 {
    const X: i32;
}

unsafe fn f<X: GenU8>(v: __m128i) -> __m128i {
    _mm_shufflelo_epi16(v, X::X)
}
```

**Comment by Mark-Simulacrum** [comment] 2021-09-12 16:28
That example is similarly using const generics; just implicitly. From 1.54 onwards, the immediate parameter in _mm_shufflelo_epi16 is defined using const generics, with desugaring from the function form implicitly done by the compiler.

**Comment by eduardosm** [comment] 2021-09-12 16:36
> That example is similarly using const generics; just implicitly. From 1.54 onwards, the immediate parameter in _mm_shufflelo_epi16 is defined using const generics, with desugaring from the function form implicitly done by the compiler.

My point is that it breaks code that compiled much before (explicit) const generics were introduced.

**Comment by steffahn** [comment] 2021-09-12 18:23
Bisection on the [second example](https://github.com/rust-lang/rust/issues/88888#issuecomment-917667019)

searched nightlies: from nightly-2020-04-01 to nightly-2021-09-11
regressed nightly: nightly-2021-05-09
searched commits: from https://github.com/rust-lang/rust/commit/770792ff8d1ec542e78e77876ac936f43ffb8e05 to https://github.com/rust-lang/rust/commit/881c1ac408d93bb7adaa3a51dabab9266e82eee8
regressed commit: https://github.com/rust-lang/rust/commit/881c1ac408d93bb7adaa3a51dabab9266e82eee8

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2020-04-01 --access github --regress error 
```
</details>

<hr>

Which is #83278 which indeed belongs to #83167.

**Comment by apiraino** [comment] 2021-09-22 20:55
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2388888.20stability.20break.20in.20rust.201.2E54.3A.20generic.20.60Self.60.20types.20a.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by pnkfelix** [comment] 2022-11-18 15:09
Visited during [P-high review](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202022-11-18.20planning.20.2B.20compiler-team.23559.20P-high.20IV/near/310841624)

@rust-lang/project-const-generics , can you all spend some time trying to brainstorm best way to resolve this?

**Comment by oli-obk** [comment] 2022-11-19 08:43
This breakage was known and cratered. The fix is to get generic const expressions stabilized. Closing as duplicate of https://github.com/rust-lang/rust/issues/76560

**Closed by oli-obk** 2022-11-19 08:43 UTC
Labels: P-high, T-compiler, regression-from-stable-to-stable, A-simd, C-bug, A-const-generics, WG-project-const-generics
