### ISSUE TITLE
Implement an ability to only run tests on a particular platform

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#47459] opened 2018-01-15 17:14 UTC
Currently we have an ability to specify targets to ignore tests on some platforms in form of `//ignore-<arch>` comment appearing somewhere in the file.

These attributes, however, are hardly usable when a test is intended to target a single architecture, as you’d have to specify every architecture test is *not* targeting.

The idea is to implement an attribute `// only-<target>`, which essentially an equivalent to specifying `// ignore-*` for every target but the `<target>`.

The relevant location to change would be [here](https://github.com/rust-lang/rust/blob/57850e53602bfc1f66a12d20299c938925c1986a/src/tools/compiletest/src/header.rs#L44).

**Comment by Pulkit07** [comment] 2018-01-15 18:24
Thanks for the file link. I am going to try fix this.

**Comment by ollie27** [comment] 2018-01-15 18:38
dupe of #33581?

**Comment by Pulkit07** [comment] 2018-01-15 18:41
@ollie27 yes looks like so. I will jump to that. Thanks.

**Comment by nagisa** [comment] 2018-01-15 18:42
Well, this has (admittedly terse) instructions. Just make sure to note both issues as "Fixed" when submitting a PR, that’s about it.

**Closed** 2018-01-17 22:20 UTC
Labels: E-easy
