### ISSUE TITLE
Strange errors / suggestions when using `[T; Self::CONST]` in traits

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#67047] opened 2019-12-05 07:00 UTC
When using (wrong but intuitve) `[T; Self::CONST]` syntax rustc gives strange errors and suggestions those doesn't help:

```rust
trait Trait {
    const CONST: usize;
    
    fn fun() -> [(); Self::CONST];
}
```
```
error[E0599]: no associated item named `CONST` found for type `Self` in the current scope
 --> src/lib.rs:4:28
  |
4 |     fn fun() -> [(); Self::CONST];
  |                            ^^^^^ associated item not found in `Self`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `CONST`, perhaps you need to restrict type parameter `Self` with it:
  |
1 | Self: Trait
  |
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=580ea268d57b6842aae972b369aa78c5))

```rust
trait Trait {
    const CONST: usize;
    
    fn fun() -> [(); Self::CONST] where Self: Trait;
}
```
```
error[E0599]: no associated item named `CONST` found for type `Self` in the current scope
 --> src/lib.rs:4:28
  |
4 |     fn fun() -> [(); Self::CONST] where Self: Trait;
  |                            ^^^^^ associated item not found in `Self`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `CONST`, perhaps you need to restrict type parameter `Self` with it:
  |
1 | Self: Trait
  |
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5367a4cb59202cbf247103b21563ea1d))

```rust
trait Trait {
    const CONST: usize;
    
    fn fun() -> [(); <Self as Trait>::CONST];
}
```
```
error[E0277]: the trait bound `Self: Trait` is not satisfied
 --> src/lib.rs:4:22
  |
2 |     const CONST: usize;
  |     ------------------- required by `Trait::CONST`
3 |     
4 |     fn fun() -> [(); <Self as Trait>::CONST];
  |                      ^^^^^^^^^^^^^^^^^^^^^^ the trait `Trait` is not implemented for `Self`
  |
  = help: consider adding a `where Self: Trait` bound
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e7416009faec89d47df59b01445d6484))
```rust
trait Trait<T: Sized> {
    const CONST: usize;
    
    fn fun(_: T) -> [(); <Self as Trait<T>>::CONST];
}
```
```
error[E0277]: the size for values of type `T` cannot be known at compilation time
 --> src/lib.rs:4:26
  |
2 |     const CONST: usize;
  |     ------------------- required by `Trait::CONST`
3 |     
4 |     fn fun(_: T) -> [(); <Self as Trait<T>>::CONST];
  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `T`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = help: consider adding a `where T: std::marker::Sized` bound

error[E0277]: the trait bound `Self: Trait<T>` is not satisfied
 --> src/lib.rs:4:26
  |
2 |     const CONST: usize;
  |     ------------------- required by `Trait::CONST`
3 |     
4 |     fn fun(_: T) -> [(); <Self as Trait<T>>::CONST];
  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Trait<T>` is not implemented for `Self`
  |
  = help: consider adding a `where Self: Trait<T>` bound
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c77cd95bbf0497f06c3e993a03bc6975))

**Comment by Centril** [comment] 2019-12-05 07:34
Duplicate of #43408.

**Closed by Centril** 2019-12-05 07:34 UTC
Labels: A-lazy-normalization, F-const_generics, T-compiler, T-lang
