### ISSUE TITLE
Cargo build giving checksum mismatch error

### ISSUE THREAD

**Issue by neetabisht** [rust-lang/rust#120738] opened 2024-02-07 12:01 UTC
Hi All,
I have cargo.toml file present in windows 11 machine where trying to use rumqtt 0.31.0 version.

![cargo-toml](https://github.com/rust-lang/cargo/assets/105039104/4ea663a5-0887-44e2-8afd-a227cd96fbc8)
But when i am running "cargo build" cli, I'm getting below error:
```
**$ cargo build
    Updating crates.io index
  Downloaded autocfg v0.1.8
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to verify the checksum of `autocfg v0.1.8`**
```
can anyone please help me with this error.

**Comment by neetabisht** [comment] 2024-02-07 12:05
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.75.0 (82e1608df 2023-12-21)`

INNEBIS1@IN-L-7402183 MINGW64 /d/eventgrid_project/rust_project (master)
$

**Comment by ehuss** [comment] 2024-02-07 12:29
Closing as this seems to be a duplicate of https://github.com/rust-lang/cargo/issues/13414.

**Closed by ehuss** 2024-02-07 12:29 UTC
Labels: C-bug, needs-triage
