### ISSUE TITLE
Odd type inference failure: unable to infer enough type information about `_`

### ISSUE THREAD

**Issue by bgamari** [rust-lang/rust#21635] opened 2015-01-25 22:36 UTC
This,

```rust
/// A binary tree with nodes labelled with `T`
pub struct Tree<T> {
    pub value: T,
    pub left: Option<Box<Tree<T>>>,
    pub right: Option<Box<Tree<T>>>,
}

impl<T> Tree<T> {
    pub fn map_step<F, V>(self, f: &mut FnMut(T) -> V) -> Tree<V> {
        Tree {
            left: self.left.map(|x| { let a: Tree<V> = x.map_step(f);
                                      Box::new(x.map_step(f)) }),
            right: self.right.map(|x| Box::new(x.map_step(f))),
            value: f(self.value),
        }
    }
}

fn main() {}
```

fails with,

```
hi.rs:12:58: 12:69 error: unable to infer enough type information about `_`; type annotations required [E0282]
hi.rs:12             left: self.left.map(|x| { let a: Tree<V> = x.map_step(f);
                                                                  ^~~~~~~~~~~
```

All of my attempts at helping the compiler find the right types have failed, therefore I suspect it's a bug.

**Comment by Aatch** [comment] 2015-01-25 22:40
There isn't enough information for the compiler to infer the type of `F` in this case, since it's not used anywhere in the function signature.

The message could be more clear though, closing as a duplicate of #19477

**Closed by Aatch** 2015-01-25 22:40 UTC

**Comment by bgamari** [comment] 2015-01-25 23:08
@Aatch, I'm not sure I follow. The type of `f` is given explicitly in the signature of `map_step`.

**Comment by bgamari** [comment] 2015-01-25 23:40
Ahh, I missed the `F` type variable. It was a remnant from refactoring. Thanks again!
