### ISSUE TITLE
Compile message contains reference to an identifier not used by the erraneous code

### ISSUE THREAD

**Issue by svenschmidt75** [rust-lang/rust#63852] opened 2019-08-24 15:19 UTC
rustc 1.37.0 (eae3437df 2019-08-13)

Repo: https://github.com/svenschmidt75/Rust
Commit: https://github.com/svenschmidt75/Rust/commit/23ec34211661c8f77c040b751500c86157f01305

When building, I get error message

```
   Compiling ann v0.1.0 (/home/svenschmidt75/Develop/Rust/NeuralNetwork/lib/ann)
error[E0282]: type annotations needed
  --> lib/ann/src/ann/cost_function.rs:25:9
   |
25 |         diff2.iter().sum() as f64 / 2.0
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `S`
   |
   = note: type must be known at this point

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: Could not compile `ann`.
warning: build failed, waiting for other jobs to finish...
error[E0282]: type annotations needed
  --> lib/ann/src/ann/cost_function.rs:25:9
   |
25 |         diff2.iter().sum() as f64 / 2.0
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `S`
   |
   = note: type must be known at this point

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: Could not compile `ann`.

To learn more, run the command again with --verbose.

Process finished with exit code 101
```

Where does S come from? 

Thanks,

**Comment by jonas-schievink** [comment] 2019-08-24 15:24
`S` is the generic parameter of [`Iterator::sum()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.sum).

**Comment by estebank** [comment] 2019-08-25 20:43
@svenschmidt75 would [the following output](https://github.com/rust-lang/rust/pull/63901) be enough for you to understand what was happening?

```
error[E0282]: type annotations needed
  --> lib/ann/src/ann/cost_function.rs:25:9
   |
25 |         diff2.iter().sum() as f64 / 2.0
   |                      ^^^ cannot infer type for `S`
   |
   = note: type must be known at this point
```

**Comment by BO41** [comment] 2019-08-25 20:56
IMO it is better to see where the problem is coming from. But there is still no obvious connection between `'S'` and `sum()`.
But the explanation from @jonas-schievink and the doc does explain it good. 
>fn sum\<S>(self) -> S

**Comment by jonas-schievink** [comment] 2019-08-25 20:59
It would probably help a lot if the message tells you what `S` is. Something like

```
error[E0282]: type annotations needed
  --> lib/ann/src/ann/cost_function.rs:25:9
   |
25 |         diff2.iter().sum() as f64 / 2.0
   |                      ^^^ cannot infer type of type parameter `S`
   |
   = note: type must be known at this point
```

**Comment by svenschmidt75** [comment] 2019-08-25 21:26
@estebank It is definitely an improvement. Is there any way that the trait can be mentioned as well? I agree with @BO41...

**Comment by estebank** [comment] 2019-08-25 21:32
@svenschmidt75 I've been looking at doing that but will require a much larger refactor to mention either `Iterator::sum` or `Sum<Iterator::Item>`. I'll leave this ticket open, but I feel that the small PR I put together is a good stop gap to marginally improve things.

**Comment by compiler-errors** [comment] 2023-01-07 22:16
This has improved in the mean time slightly:

```
error[[E0282]](https://doc.rust-lang.org/stable/error-index.html#E0282): type annotations needed
 --> src/lib.rs:2:18
  |
2 |     diff2.iter().sum() as f64 / 2.0
  |                  ^^^ cannot infer type of the type parameter `S` declared on the associated function `sum`
  |
help: consider specifying the generic argument
  |
2 |     diff2.iter().sum::<S>() as f64 / 2.0
  |                     +++++

For more information about this error, try `rustc --explain E0282`.
```

I'm probably gonna close this because it suggests the turbofish and mentions that `S` is a parameter of `sum`

**Closed by compiler-errors** 2023-01-07 22:16 UTC
Labels: C-enhancement, A-diagnostics, T-compiler, A-inference
