### ISSUE TITLE
OSRng initialization crash on Windows

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#44911] opened 2017-09-28 23:14 UTC
Firefox is getting a rare but recurring crash on Windows due to OsRng failing to initialize.

The bug is being tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1385971), and you can see the crash reports [here](https://crash-stats.mozilla.com/signature/?signature=core%3A%3Aresult%3A%3Aunwrap_failed%3CT%3E%20%7C%20std%3A%3Acollections%3A%3Ahash%3A%3Amap%3A%3A%7B%7Bimpl%7D%7D%3A%3Anew%3A%3AKEYS%3A%3A__init&date=%3E%3D2017-09-21T22%3A48%3A00.000Z&date=%3C2017-09-28T22%3A48%3A00.000Z&_columns=moz_crash_reason&_sort=-date&page=1#summary)

Since the crash message isn't public on that page, just to give an idea, these are the kinds of crash reasons we have:

 - `failed to create an OS RNG: Error { repr: Os { code: 127, message: "OS Error 127 (FormatMessageW() returned error 15100)" } }` (15100 is `ERROR_MUI_FILE_NOT_FOUND`, i.e. it's unable to find the strings file to return the translated error message)
 - `failed to create an OS RNG: Error { repr: Os { code: 127, message: "OS Error 127 (FormatMessageW() returned error 5)" } }` (5 is `ERROR_ACCESS_DENIED`, so the translation string file is)
 - `failed to create an OS RNG: Error { repr: Os { code: -2146893801, message: "Provider type not defined." } }`
   - `failed to create an OS RNG: Error { repr: Os { code: -2146893801, message: "Tipo de proveedor no definido." } }` and basically the same thing in different languages
 - `failed to create an OS RNG: Error { repr: Os { code: -2146893818, message: "Invalid Signature." } }`

The FormatMessage errors are not a problem, they just mean that the formatter was unable to figure out what the error message was -- if we hit that we're erroring out already.

The actual OS error seems to mostly be error code 127 (`ERROR_PROC_NOT_FOUND`). I believe `-2146893801` is also one of these with some extra flags set. This is concerning; it doesn't seem like this should _happen_, because we are only feeding known system crypto provider (`PROV_RSA_FULL`) to `CryptAcquireContextA`. I'm unsure what the "invalid signature" error is about.

This might just be system DLLs being broken, but it's occurring regularly enough (we have a almost thousand crash reports) that we're having to work around it by disabling RandomState on systems where this doesn't work (which we can do because we've already forked HashMap for fallible allocations). Furthermore, Firefox code uses `CryptAcquireContext` and `CryptGenRandom` in a bunch of places and those don't seem to be particularly crashy.

We should see if this is an issue on our side, or perhaps make OsRng (or perhaps just `RandomState`'s initializer?) more resilient to this (perhaps with a more expensive fallback?).

**Comment by mattico** [comment] 2017-09-28 23:28
Possibly related: https://github.com/golang/go/issues/15655

They thought it was due to delay-loaded DLLs not loading, but didn't figure it out.

**Comment by Manishearth** [comment] 2017-09-29 05:36
Yeah, i saw that issue and figured it probably was something similar, but also this is crashing pretty often so having some built in mitigation (I don't know what) might be interesting.

**Comment by nagisa** [comment] 2017-09-29 10:51
What is the distribution of Windows’ versions that experience these failures?

**Comment by Manishearth** [comment] 2017-09-29 17:03
You can see that in the [crash report](https://crash-stats.mozilla.com/signature/?signature=core%3A%3Aresult%3A%3Aunwrap_failed%3CT%3E%20%7C%20std%3A%3Acollections%3A%3Ahash%3A%3Amap%3A%3A%7B%7Bimpl%7D%7D%3A%3Anew%3A%3AKEYS%3A%3A__init%20%7C%20style%3A%3Aproperties%3A%3Acascade) (I linked to an older one by accident).

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1617736/31026994-713671a6-a4fd-11e7-825c-d6524f2232c4.png">

**Comment by Manishearth** [comment] 2017-09-29 17:05
It's very likely that these numbers are representative of the actual distribution of Firefox users, since you can expect most Windows 8 users to have upgraded to 10. I don't know the actual numbers though.

**Comment by cpeterso** [comment] 2017-09-29 18:18
Windows 7 is overrepresented here. The distribution of Windows versions among Windows Firefox users is about 52% Windows 7 and 36% Windows 10.

https://hardware.metrics.mozilla.com/#goto-os-and-architecture

**Comment by Manishearth** [comment] 2017-09-29 18:21
That somewhat supports the broken DLL theory, you'd probably have more broken DLLs on older systems.

**Comment by jgraham** [comment] 2017-10-02 06:30
We started to see a similar error recently in geckodriver tests [1]. That seems to be on Linux 64, so it's possible that this is a different root cause to the Windows bug.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1404647

**Comment by cpeterso** [comment] 2018-06-28 21:47
@HouzuoGuo Which version of Windows is this? Do you have a backtrace? The caller might be able to switch from OsRng to one of the other rand RNGs that does panic on error: https://docs.rs/rand/0.5.3/rand/rngs/

**Comment by HouzuoGuo** [comment] 2018-06-29 14:51
@cpeterso The system is an old Windows 7 64-bit laptop running on a slow AMD A10 CPU, I'll try to turn on back trace on Tuesday.

**Comment by HouzuoGuo** [comment] 2018-07-03 11:28
Here is the back trace, perhaps not as useful as it could be...

<pre>
!!! could not start server on port 1512: [Exception... "Component returned failu
re code: 0x80004005 (NS_ERROR_FAILURE) [nsIServerSocket.init]"  nsresult: "0x800
04005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///C:/laitos-windows-
supplements/SlimerJS/omni.ja!/components/httpd.js :: _start :: line 556"  data:
no]


PhantomJS Javascript Exception
Error: 2147746065
thread '<unnamed>' panicked at 'failed to create an OS RNG: Error { repr: Os { c
ode: -2146893818, message: "Invalid Signature." } }', src\libcore\result.rs:906:
4
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: mozilla_dump_image
  10: mozilla_dump_image
  11: mozilla_dump_image
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: PRP_TryLock
  21: PR_MD_UNLOCK
  22: iswascii
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>

c:\gopath\src>
</pre>

Be aware that SlimerJS is not compatible with firefox version newer than 59, hence the error was captured from firefox version 59.0.3, launched via SlimerJS 1.0.0.

**Comment by cpeterso** [comment] 2018-07-06 07:31
Unfortunately, I don't have a lot of helpful information to share. The "Invalid Signature" error message might mean that:
* You have some anti-virus or internet security software or malware installed (and it is interfering with your program loading the advapi32.dll).
* Your advapi32.dll is corrupt, either on disk or due to some hardware issue like bad RAM.

99% of these "Invalid Signature" errors in Firefox happen on Windows 7.

**Comment by HouzuoGuo** [comment] 2018-07-06 07:42
thanks @cpeterso

**Comment by dhardy** [comment] 2019-02-15 12:37
@Manishearth @cpeterso is this still a thing?

Several things have changed since:

- the Rand lib has a backup entropy source based on CPU jitter (since Dec 2017, as you know)
- `RandomState` no longer uses the Rand lib, but uses a minimal `hashmap_random_keys` function
- `hashmap_random_keys` is a simplified re-implementation of `OsRng` and panics on failure (see [Windows implementation](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/rand.rs))

Note that `hashmap_random_keys` actually returns constants on [some](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/redox/rand.rs) [platforms](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasm/mod.rs#L97), hence it is somewhat surprising that other platforms will panic on error. It might make more sense if `hashmap_random_keys` returned an `Option` (it's not part of the public API).

Thus, I presume you still see occasional crashes of FF due to this?

Secondary question: do you believe having a backup entropy source in Rand is generally useful enough to be worth keeping? I ask because quite a few people [object](https://github.com/rust-random/rand/issues/699) to `JitterRng` due to it not being provably secure.

**Comment by cpeterso** [comment] 2019-02-15 19:29
> is this still a thing?

I don't this is currently a problem (for Firefox). I just looked for recent Firefox crashes that matched the original function signature and only found a few. So we can probably close this issue.

> do you believe having a backup entropy source in Rand is generally useful enough to be worth keeping?

*I* think it's useful for Rand to have a default that "just works" (i.e. has a backup entropy source). If people have a use case requires a secure RNG, then they can use a secure RNG in their code. 😃

OTOH, Rand could change to not use the backup entropy source by default and Rust std libs could explicitly opt into the backup entropy source for internal use cases that don't absolutely require a secure RNG (like seeding a hash map).

**Comment by the8472** [comment] 2021-12-07 17:05
> I don't this is currently a problem (for Firefox). I just looked for recent Firefox crashes that matched the original function signature and only found a few. So we can probably close this issue.

Doing so.

**Closed by the8472** 2021-12-07 17:05 UTC
Labels: O-windows, T-libs-api, C-bug
