### ISSUE TITLE
How to put a println for debug in rust src?

### ISSUE THREAD

**Issue by UncP** [rust-lang/rust#48839] opened 2018-03-08 07:55 UTC
I need to put a `println` in rust src and compile a local `rustc` to help debug, when I do that, I get such errors:
```
could not compile local rustc.

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Error during translation/LLVM phase.

error: Could not compile `core`.

Caused by:
process didn't exit successfully: `/home/pingcap/uncp/rust/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=e2f49b08d2bc06b5 -C extra-filename=-e2f49b08d2bc06b5 --out-dir /home/pingcap/uncp/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/pingcap/uncp/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/pingcap/uncp/rust/build/x86_64-unknown-linux-gnu/stage1-std/release/deps` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/home/pingcap/uncp/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-target" "x86_64-unknown-linux-gnu" "-j" "40" "release" "features" "panic-unwind jemalloc backtrace" "manifest-path" "/home/pingcap/uncp/rust/src/libstd/Cargo.toml" "-message-format" "json"
expected success, got: exit code: 101', bootstrap/compile.rs:886:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /home/pingcap/uncp/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:00:21
```

how can I put a `println` or an info log in rust src.

**Comment by varkor** [comment] 2018-03-08 09:17
You should be able to use `eprintln` to print to stderr now that https://github.com/rust-lang/rust/pull/47634 has been merged, though traditionally the easiest (although verbose) method is using the `debug!`/ `info!`/etc. logging macros with `RUST_LOG=debug/info` (you'll need to filter the output with the latter method, though, as there's a lot of noise).

**Comment by petrochenkov** [comment] 2018-03-08 10:45
Duplicate of https://github.com/rust-lang/rust/issues/43855

**Closed by petrochenkov** 2018-03-08 10:45 UTC
