### ISSUE TITLE
Compilation ICE on nphysics crate

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/rust#33096] opened 2016-04-19 16:52 UTC
When trying to compile nphysics on a nightly created on or after `2016-04-14`, the compiler errors. Before this date it is fine.

Example code:

``` bash
git clone https://github.com/sebcrozet/nphysics
rustup update nightly-2016-04-13 && rustup run nightly-2016-04-13 cargo build # Works fine
rustup update nightly-2016-04-14 && rustup run nightly-2016-04-13 cargo build # Errors
```

Presumably was [this commit](https://github.com/rust-lang/rust/commit/cd85120ef9be436b8cd32c7208a913cc41c66e13) that broke things, as it's a commit on that day that touches trans.

On Windows 64 bit GNU this is the output:

```
   Compiling nphysics3d v0.2.2 (https://github.com/sebcrozet/nphysics.git#b379109f)
error: internal compiler error: ../src/librustc_trans\debuginfo\type_names.rs:155: debuginfo: Trying to create type name for unexpected type: <na::Pnt3<f32> as nc::ncollide_math::Point>::Vect
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax\errors/mod.rs:575
```

**Comment by alexcrichton** [comment] 2016-04-19 18:17
cc @eddyb

**Comment by eddyb** [comment] 2016-04-19 18:50
You sure it's that innocent commit and not, you know, my changes to debuginfo, for MIR?
Specifically, [this normalization](https://github.com/rust-lang/rust/pull/32803/files#diff-86c1222a1321d7917414f33746d1d7d3L487) is gone, that could cause problems.

**Comment by eddyb** [comment] 2016-04-19 18:59
@trolleyman I can't reproduce on master (just rebased one of my branches containing unrelated changes, so I had a compiler to check with).

**Comment by trolleyman** [comment] 2016-04-19 19:54
Yeah I really am not sure which commit it is, was just a guess really.

Hmm, let me try this again, one sec...

**Comment by trolleyman** [comment] 2016-04-19 20:13
Ok so I was misinterpreting which crate was beign compiled. nphysics compiles fine, but [my crate](https://github.com/trolleyman/neat), which uses nphysics, doesn't. I'm trying to narrow down the code now.

**Comment by trolleyman** [comment] 2016-04-19 22:04
Here's some of the rust log that I got when compiling on debug builds:
```
INFO:rustc_trans::common: Cache hit: Binder(<nc::shape::Plane<na::Vec3<f32>> as nc::ray::RayCast<na::Pnt3<f32>, na::Iso3<f32>>>)
INFO:rustc::middle::region: CodeExtent(118736) = CallSiteScope { fn_id: 5171551, body_id: 5171571 } [parent=0]
INFO:rustc::middle::region: CodeExtent(118737) = ParameterScope { fn_id: 5171551, body_id: 5171571 } [parent=118736]
INFO:rustc::middle::region: CodeExtent(118738) = Misc(5171554) [parent=0]
INFO:rustc::middle::region: CodeExtent(118739) = Misc(5171557) [parent=0]
INFO:rustc::middle::region: CodeExtent(118740) = Misc(5171561) [parent=0]
INFO:rustc::middle::region: CodeExtent(118741) = Misc(5171566) [parent=0]
INFO:rustc::middle::region: CodeExtent(118742) = DestructionScope(5171571) [parent=118737]
INFO:rustc::middle::region: CodeExtent(118743) = Misc(5171571) [parent=118742]
INFO:rustc::middle::region: CodeExtent(118744) = Misc(5171572) [parent=118743]
INFO:rustc::middle::region: CodeExtent(118745) = Misc(5171573) [parent=118744]
INFO:rustc::middle::region: CodeExtent(118746) = Misc(5171574) [parent=118745]
INFO:rustc::middle::region: CodeExtent(118747) = Misc(5171575) [parent=118745]
INFO:rustc::middle::region: CodeExtent(118748) = Misc(5171576) [parent=118745]
INFO:rustc::middle::region: CodeExtent(118749) = Misc(5171577) [parent=118745]
INFO:rustc::middle::region: CodeExtent(118750) = Misc(5171578) [parent=118744]
INFO:rustc::middle::region: CodeExtent(118751) = CallSiteScope { fn_id: 5171578, body_id: 5171582 } [parent=118750]
INFO:rustc::middle::region: CodeExtent(118752) = ParameterScope { fn_id: 5171578, body_id: 5171582 } [parent=118751]
INFO:rustc::middle::region: CodeExtent(118753) = Misc(5171580) [parent=0]
INFO:rustc::middle::region: CodeExtent(118754) = DestructionScope(5171582) [parent=118752]
INFO:rustc::middle::region: CodeExtent(118755) = Misc(5171582) [parent=118754]
INFO:rustc::middle::region: CodeExtent(118756) = Misc(5171583) [parent=118755]
INFO:rustc::middle::region: CodeExtent(118757) = Misc(5171584) [parent=118756]
INFO:rustc::middle::region: CodeExtent(118758) = DestructionScope(5171551) [parent=0]
INFO:rustc::middle::region: CodeExtent(118759) = CallSiteScope { fn_id: 11887, body_id: 11907 } [parent=1]
INFO:rustc::middle::region: CodeExtent(118759) = CallSiteScope { fn_id: 11887, body_id: 11907 } [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(118759) = CallSiteScope { fn_id: 11887, body_id: 11907 } [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(118759) = CallSiteScope { fn_id: 11887, body_id: 11907 } [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(118759) = CallSiteScope { fn_id: 11887, body_id: 11907 } [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(118759) = CallSiteScope { fn_id: 11887, body_id: 11907 } [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(11868) = Misc(11909) [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(11868) = Misc(11909) [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(11868) = Misc(11909) [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(11868) = Misc(11909) [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(11868) = Misc(11909) [parent=1] BOGUS!
INFO:rustc::middle::region: CodeExtent(11868) = Misc(11909) [parent=1] BOGUS!
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as std::marker::Sized>))`
INFO:rustc::traits::fulfill: check_duplicate_trait hit: `Binder(TraitPredicate(<f32 as nc::ncollide_math::Scalar>))`
error: internal compiler error: ../src/librustc_trans\debuginfo\type_names.rs:155: debuginfo: Trying to create type name for unexpected type: <na::Pnt3<f32> as nc::ncollide_math::Point>::Vect
```

**Comment by eddyb** [comment] 2016-04-19 22:17
@trolleyman That's not really helpful, sadly, nightly doesn't use `-C debug-assertions` yet, so there's no `debug!` output.

**Comment by eddyb** [comment] 2016-04-19 23:17
@trolleyman This bug is not in beta, correct?

**Comment by trolleyman** [comment] 2016-04-20 00:17
@eddyb I'm afraid that I can't test that as I'm using `#[feature]`s.

**Comment by eddyb** [comment] 2016-04-20 00:20
@trolleyman Can you check the test from #33099 instead? Particularly interested about the nightlies you had issues with.

**Comment by trolleyman** [comment] 2016-04-20 00:26
@eddyb Sure, unfortunately that test case works fine for both pre and post-`2016-04-14`.

**Comment by eddyb** [comment] 2016-04-20 00:28
@trolleyman Ah, beats me then.

**Comment by trolleyman** [comment] 2016-04-20 00:29
I'll try and find which part of my code hits the error.

**Comment by trolleyman** [comment] 2016-04-20 12:14
@eddyb So I did some digging and I was wrong again, it turns out it _is_ the nphysics crate. This is a minimal test case:
```
extern crate nphysics3d;

pub fn main() {
	nphysics3d::world::World::new().step(1.0);
}
```

**Comment by eddyb** [comment] 2016-04-20 14:24
@trolleyman It depends on the `nphysics3d` crate, but it's not the crate itself, and that testcase is still large in terms of how much it needs to monomorphize.

**Comment by trolleyman** [comment] 2016-04-20 23:51
@eddyb True, sorry but I am not knowledgeable at all in rustc or nphysics, so it's the best I can do :/

**Comment by nikomatsakis** [comment] 2016-04-21 20:09
triage: P-high

**Comment by eddyb** [comment] 2016-04-26 10:38
Still need a good  regression test.

**Comment by nikomatsakis** [comment] 2016-05-05 18:52
triage: P-low

**Comment by Mark-Simulacrum** [comment] 2019-09-01 14:22
I'm going to go ahead and close this. It's somewhat unlikely we'll hit this again (at least, we haven't obviously done so in the past 3ish years), and coming up with a good test case when the current case is all of nphysics is likely to be quite hard.

**Closed by Mark-Simulacrum** 2019-09-01 14:22 UTC
Labels: C-bug, E-needstest, P-low, T-compiler
