### ISSUE TITLE
Erroneous "conflicting implementations" message

### ISSUE THREAD

**Issue by bfops** [rust-lang/rust#24165] opened 2015-04-07 17:57 UTC
This used to compile, but now it fails with `error: conflicting implementations for trait`.

    trait Foo {}

    impl<T> Foo for T where T: Copy {}
    impl<T> Foo for Vec<T> where T: Copy {}

    fn main() {
    }

**Comment by apasel422** [comment] 2015-04-07 18:15
This is not a bug, as these impls do conflict: `T` could be instantiated with `Vec<T>`. In other words, the impl that would be selected here is ambiguous:
```rust
fn foo<F: Foo>() {}

fn main() {
    foo::<Vec<i32>>();
}
```
One solution involves parameterizing `Foo` itself with `T`, as multidispatch will disambiguate the two impls:
```rust
trait Foo<T> {}

impl<T> Foo<T> for T where T: Copy {}
impl<T> Foo<T> for Vec<T> where T: Copy {}

fn main() {
}
```

**Comment by bfops** [comment] 2015-04-07 18:25
`T` couldn't be instantiated with `Vec<T>`, though, since `Vec<T>` doesn't implement `Copy`. And apparently, until recently, the compiler was aware of that. And it *should* be aware of that, since the `impl` must be in scope if it exists.

**Comment by apasel422** [comment] 2015-04-07 18:30
Oh, I see. This may be a result of #23867.

**Comment by apasel422** [comment] 2015-04-07 18:34
In particular, https://github.com/rust-lang/rfcs/blob/master/text/1023-rebalancing-coherence.md#type-locality-and-negative-reasoning seems relevant.

**Comment by nikomatsakis** [comment] 2015-04-07 19:46
Yes, this is now the intended behavior, due to rust-lang/rfcs#1023, as @apasel422 points out. And this is also one of the known cases where it'd be nice to be able to extend the system, though the best way to do that is not yet agreed upon.

**Comment by bfops** [comment] 2015-04-07 20:09
Ah. So given that the type system is now less powerful indefinitely, what's the appropriate course of action if I'm writing a `Flatten` trait? This *used* to work:

    pub trait Flatten<T> {
      /// Emit a value into a Vec of bytes.
      fn emit(v: &Self, dest: &mut Vec<u8>) -> Result<(), ()>;
      /// Parse a value out of a stream of bytes.
      fn read<'a>(s: &mut MemStream<'a>) -> Result<Self, EOF>;
    }

    #[macro_export]
    macro_rules! flatten_unit_struct_impl(
      ...
    );

    #[macro_export]
    macro_rules! flatten_struct_impl(
      ...
    );

    #[macro_export]
    macro_rules! flatten_enum_impl(
      ...
    );

    impl<T> Flatten for T where T: Copy {
      ...
    }

    impl<T> Flatten for T where T: Copy {
      ...
    }

    impl<T> Flatten for Vec<T> where T: Copy {
      ...
    }

    impl Flatten for String {
      ...
    }

@apasel422 I'm having some trouble using your fix for this, since not everything is neatly parameterized on some `T`.

**Comment by apasel422** [comment] 2015-04-07 20:29
@bfops: I'd suggest bringing this up in http://users.rust-lang.org/ and closing this issue, but the solution depends on how you want to be able to use this trait. My type parameter suggestion was just based on your reduced test case, but, in general, you won't be able to provide multiple `Flatten` impls if you have a blanket one for `T`. You may also want to take a look at [`rustc-serialize`](https://github.com/rust-lang/rustc-serialize) and [`serde`](https://github.com/erickt/rust-serde) for ideas.

**Closed** 2015-04-07 20:35 UTC
Labels: A-diagnostics, A-typesystem
