### ISSUE TITLE
Rustc panicked at 'found unstable fingerprints...

### ISSUE THREAD

**Issue by mariomatic** [rust-lang/rust#84898] opened 2021-05-04 08:16 UTC
### Code

```Rust
use std::fs::File;
use std::io::Error;


fn main() -> Result<(), Error > {
    let mut f = File::open("d:\\play")?;
    println! ( "{:?}", f.metadata()? );
    Ok(())
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-beta.7 (9a1dfd2dc 2021-04-30)
binary: rustc
commit-hash: 9a1dfd2dc5c42a2ee84b4606aa08cdadf8c0ee87
commit-date: 2021-04-30
host: x86_64-pc-windows-msvc
release: 1.52.0-beta.7
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[c0d5]::ops::function::Fn): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::FnMut<Args>>)), C:\Users\mmatic\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:67:21: 67:32 (#0)), (Binder(TraitPredicate(<Args as std::marker::Sized>)), C:\Users\mmatic\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:67:14: 67:18 (#0)), (Binder(TraitPredicate(<Self as std::ops::Fn<Args>>)), C:\Users\mmatic\.rustup\toolchains\beta-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:67:1: 67:32 (#0))] }', /rustc/9a1dfd2dc5c42a2ee84b4606aa08cdadf8c0ee87\compiler\rustc_query_system\src\query\plumbing.rs:593:5
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

stack backtrace:
   0:     0x7fff146f81fe - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfae6ccd854213db1
   1:     0x7fff1472334c - core::fmt::write::h44ad4f19d689cef1
   2:     0x7fff146ebc58 - <std::io::IoSlice as core::fmt::Debug>::fmt::hef43a6d5a8368ca5
   3:     0x7fff146fc39d - std::panicking::take_hook::h576dd54ad12ab799
   4:     0x7fff146fbe69 - std::panicking::take_hook::h576dd54ad12ab799
   5:     0x7ffedc6fcc77 - rustc_driver::report_ice::h0e8f32f8e59244df
   6:     0x7fff146fcbf5 - std::panicking::rust_panic_with_hook::hb37cfa34adb9ae3b
   7:     0x7fff146fc761 - rust_begin_unwind
   8:     0x7fff146f8b4f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfae6ccd854213db1
   9:     0x7fff146fc6b9 - rust_begin_unwind
  10:     0x7fff14754e5c - std::panicking::begin_panic_fmt::hc213a848dd3c30a4
  11:     0x7ffedf2c927c - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  12:     0x7ffedf2ecb84 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  13:     0x7ffedf521b1b - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::hb5811461be3bf9fd
  14:     0x7ffedf17f890 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  15:     0x7ffedf43fabd - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hdb6006e63bb98d44
  16:     0x7ffee072c302 - rustc_middle::ty::generics::GenericPredicates::instantiate_identity::hd6560ca2219c0438
  17:     0x7ffee072bfd7 - rustc_middle::ty::generics::GenericPredicates::instantiate_identity::hd6560ca2219c0438
  18:     0x7ffee0346743 - rustc_trait_selection::traits::object_safety::trait_has_sized_self::ha401491b40e947b7
  19:     0x7ffee0362402 - <rustc_trait_selection::autoderef::AutoderefKind as core::fmt::Debug>::fmt::h9d30ed7c3b0ddc93
  20:     0x7ffee0385ef6 - <rustc_trait_selection::traits::select::ProvisionalEvaluation as core::fmt::Debug>::fmt::h09a11af9605709a0
  21:     0x7ffee038f27f - <rustc_trait_selection::traits::select::ProvisionalEvaluation as core::fmt::Debug>::fmt::h09a11af9605709a0
  22:     0x7ffee0ae3122 - serde::private::de::content::Content::unexpected::hcdf7533a6ecf3e66
  23:     0x7ffee03a0399 - <rustc_trait_selection::traits::query::type_op::outlives::DropckOutlives as core::fmt::Debug>::fmt::h8c672a6260f616f4
  24:     0x7ffee036ee6c - rustc_trait_selection::traits::impossible_predicates::ha6883a6941a106f9
  25:     0x7ffedf3067e7 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  26:     0x7ffedf507699 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::hb5811461be3bf9fd
  27:     0x7ffedf2e58d3 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  28:     0x7ffedf51ea23 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::hb5811461be3bf9fd
  29:     0x7ffedf1cbe7e - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  30:     0x7ffedf445cae - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hdb6006e63bb98d44
  31:     0x7ffedf830e68 - <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_rvalue::hdbc596ee232d9751
  32:     0x7ffedf8355cb - <rustc_mir::monomorphize::collector::RootCollector as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_impl_item::h80686928bd6f6035
  33:     0x7ffedf82ddc3 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h43129fad64ba08dd
  34:     0x7ffedf82c748 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h43129fad64ba08dd
  35:     0x7ffedfb26f89 - rustc_mir::monomorphize::partitioning::partition::h1924b0707b0b680b
  36:     0x7ffedf30978a - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  37:     0x7ffedf507371 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::hb5811461be3bf9fd
  38:     0x7ffedf4765da - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hdb6006e63bb98d44
  39:     0x7ffedf52762b - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::hb5811461be3bf9fd
  40:     0x7ffedf26833b - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  41:     0x7ffedf21d0bb - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::hfd666d4312c2a266
  42:     0x7ffedf449ec8 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hdb6006e63bb98d44
  43:     0x7ffedc98f23a - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h77287877865bcd4f
  44:     0x7ffedc84f6b2 - rustc_interface::passes::BoxedResolver::to_resolver_outputs::h4ec63178a769446e
  45:     0x7ffedc85b4e6 - rustc_interface::queries::Queries::ongoing_codegen::hee71184e618ccde0
  46:     0x7ffedc715b17 - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::h143405f70f01b5db
  47:     0x7ffedc6ff97c - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5e3ec1c3f42432f1
  48:     0x7ffedc716d17 - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::h143405f70f01b5db
  49:     0x7ffedc707084 - rustc_driver::pretty::print_after_hir_lowering::hdbb70a4ca15139bc
  50:     0x7ffedc718c6f - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::h143405f70f01b5db
  51:     0x7ffedc73876d - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::h143405f70f01b5db
  52:     0x7fff1470bc9a - std::sys::windows::thread::Thread::new::h58f8eb2e5a02b455
  53:     0x7fff8f177034 - BaseThreadInitThunk
  54:     0x7fff90e42651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-beta.7 (9a1dfd2dc 2021-04-30) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::Fn`
#1 [vtable_methods] finding all methods for trait std::ops::Fn
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

</p>
</details>

**Comment by JohnTitor** [comment] 2021-05-04 09:35
Should be a duplicate of #84341, it has been fixed on the latest nightly. Updating the toolchain or running `cargo clean` (or turning off the incremental compilation) should get rid of the ICE. If you still find an ICE, feel free to re-open. Thanks!

**Closed by JohnTitor** 2021-05-04 09:35 UTC
Labels: C-bug, I-ICE, T-compiler
