### ISSUE TITLE
No backtrace on windows with current rustc stable

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-lang/rust#122857] opened 2024-03-21 13:46 UTC
Currently rustc beta in our CI is giving us backtraces like this with simple `cargo test`s (with Cargo.toml set for `opt-level = 1`):

```
0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
```

**Comment by workingjubilee** [comment] 2024-03-22 03:38
cc @michaelwoerister sorry but it seems the combination of everything actually merging together did in fact break backtraces!

**Comment by workingjubilee** [comment] 2024-03-22 03:42
For note it has not been confirmed in a beyond-a-shadow-of-a-doubt way that https://github.com/rust-lang/rust/pull/121297 is the guilty commit. @ChrisDenton could you do the honors of bisecting this?

**Comment by workingjubilee** [comment] 2024-03-22 06:08
hmm. the remarks in https://github.com/rust-lang/backtrace-rs/pull/594#issuecomment-2014406300 removes my confidence this is a stable->beta regression and not a stable->stable regression? could it have been https://github.com/rust-lang/cargo/pull/13257 instead?

people were relying on these backtraces working. but should they have not been? and how *do* PDBs work anyways?

**Comment by ChrisDenton** [comment] 2024-03-22 06:34
Also cc @wesleywiser, as I'm wondering what the semantics of `strip="debuginfo"` should be. Currently it's [treated the same](https://github.com/rust-lang/rust/blob/cdb683f6e4b0774b85c60eebe12af87f29d8ee4d/compiler/rustc_codegen_ssa/src/back/linker.rs#L968) as `strip="symbols"`.

**Comment by apiraino** [comment] 2024-03-22 06:55
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23122857.20No.20backtrace.20on.20windows.20with.20current.20rustc.20beta)).

@rustbot label -I-prioritize +P-high

**Comment by Kobzol** [comment] 2024-03-22 07:39
This indeed seems to by caused by my Cargo PR to remove debuginfo in release. Do I understand it correctly that on Windows, `strip = "debuginfo"` also strips symbols? 😨

**Comment by ChrisDenton** [comment] 2024-03-22 07:50
As it stands, yes. Well at least for msvc. It should also be noted that msvc debug information is always stored in a separate (.pdb) file so there's much less reason to strip debug info than there might otherwise be.

**Comment by Kobzol** [comment] 2024-03-22 08:00
I would argue that strip = debuginfo shouldn't strip *anything* from the binary in that case, not everything.

**Comment by michaelwoerister** [comment] 2024-03-22 08:28
To confirm, https://github.com/rust-lang/rust/pull/121297 as well as the backtrace-rs changes are in beta, so they could be the culprit. As far as I know, there have been a number of Windows-related changes in the new release (https://github.com/rust-lang/backtrace-rs/commits/0.3.70/).

`-C strip=debuginfo` on Windows currently does prevent the linker from generating a PDB file at all (as @ChrisDenton pointed out in https://github.com/rust-lang/backtrace-rs/pull/594#issuecomment-2014434355). This is a known issue that hasn't really been resolved yet (see https://github.com/rust-lang/rust/pull/115120) because it's not completely clear what the solution should be.

**Comment by michaelwoerister** [comment] 2024-03-22 08:30
But if Cargo now passes `-Cstrip=debuginfo` when targeting `*-pc-window-msvc` then I would fully expect to see backtraces not working in the way described here. I'd suggest reverting that behavior for those platforms.

**Comment by michaelwoerister** [comment] 2024-03-22 09:16
I can reproduce this on stable and beta for a simple hello world program. That means that the recent backtrace-rs and `/PDBALTPATH` changes are not the cause. It does not happen in `1.76` (previous stable). Also, removing the `-Cstip=debuginfo` argument on beta solves the problem.

I see two options:
- Fix this in rustc by merging some version of https://github.com/rust-lang/rust/pull/115120. We do a beta backport, not sure about a stable backport. 
- Fix this in Cargo, but with the expectation that that fix would be removed (or at least unnecessary) once https://github.com/rust-lang/rust/pull/115120 gets merged. We'd also need to do backports.

I'm somewhat in favor of fixing this in rustc since that is what we want to do anyway.

**Comment by workingjubilee** [comment] 2024-03-22 13:52
I assume that this has already reached the T-compiler agenda, but

**Comment by michaelwoerister** [comment] 2024-03-22 14:21
> I tried `RUSTFLAGS="-C debuginfo=line-tables-only" cargo test --features backtrace` and it seems to still fail with the same backtrace.

I suspect that is because Cargo does not look at the RUSTFLAGS and thus does not assume that debuginfo is enabled, which leads it to still pass `-Cstrip=debuginfo` to rustc. Modifying the Cargo profile should give a different result.

**Comment by Kobzol** [comment] 2024-03-22 14:42
Yes. The heuristic only looks at the contents of Cargo.toml profiles of the crate and its dependencies. RUSTFLAGS are completely opaque to Cargo.

Now that I think about it, that can actually be a bit problematic, since -Cstrip apparently overrides -Cdebug, and since Cargo uses -Cstrip, it cannot be easily overridden by RUSTFLAGS (OTOH, things that can be configured in a profile probably shouldn't be set in the flags...).

**Comment by icedrocket** [comment] 2024-03-22 14:47
If `-Cstrip` was limited to executables only, users would have no way to disable the generation of PDBs. Perhaps a combination with rust-lang/compiler-team#721 is needed.

**Comment by Mark-Simulacrum** [comment] 2024-03-22 16:38
Hi all! Release is happy to do a stable point release, please ping me once we have a backport-safe patch (maybe just to cargo, to disable the new default stripping?)

**Comment by Kobzol** [comment] 2024-03-22 17:01
If we want to do a point release quickly, I guess that we should disable the automatic stripping (preferably only on Windows though).

**Comment by workingjubilee** [comment] 2024-03-22 17:23
@Kobzol what if someone has cross-compiling to Windows working tho'

**Comment by Kobzol** [comment] 2024-03-22 17:33
I meant deciding based on the target for which we compile, not the host. That should be possible, or not?

**Comment by workingjubilee** [comment] 2024-03-22 17:40
Oh okay.
Probably yeah!

**Comment by Kobzol** [comment] 2024-03-23 14:33
I tried to cook up something in https://github.com/rust-lang/cargo/pull/13630, but I'm not sure if it's the right approach.

**Comment by ChrisDenton** [comment] 2024-03-23 16:06
@michaelwoerister It seems like #115120 will take time to design but there is perhaps an interim solution that's simpler and easier to backport. We could simply make `strip = "debuginfo"` the same as `strip = "none"` with the rationale that, whatever `strip = "debuginfo"` does or does not do, it should not be stripping symbols from anywhere.

**Comment by Kobzol** [comment] 2024-03-24 08:42
An alternative to https://github.com/rust-lang/cargo/pull/13630 that could fix the problem could be something like [this](https://github.com/rust-lang/rust/compare/master...Kobzol:rust:windows-strip).

**Comment by ChrisDenton** [comment] 2024-03-25 07:39
I think I'd suggest something more like [this](https://github.com/rust-lang/rust/commit/fb7687f310152ca8dea525e829248f9a2a011869#diff-3f87e69f5e21712681d6fca5b6b70542c10eaf49bf48ff16445ddd17f1ae6dad). This would lead to more consistent behaviour. We could additionally skip including natvis but I'm more "meh" on that, especially if the eventual intent is for strip to have no effect on external files.

**Comment by michaelwoerister** [comment] 2024-03-25 10:37
I think it is clear by now that we don't want `-Cstrip` to touch PDB files or other separate debuginfo. So I think that @ChrisDenton's [proposal](https://github.com/rust-lang/rust/issues/122857#issuecomment-2017393112) is a move in the right direction. 

However, given that the [current documentation of `-Cstrip`](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip) mentions debuginfo not being copied to separate files, I think we need an FCP to change that behavior, which we know can take a long time.

That being the case, I think we should temporarily revert Cargo's defaults when targeting `*-windows-msvc` as @Kobzol proposes in https://github.com/rust-lang/cargo/pull/13630.

**Comment by ChrisDenton** [comment] 2024-03-25 11:32
I created #123031 if you wanted to consider an fcp. In the meantime, backporting @Kobzol's proposal sounds good to me!

**Comment by weihanglo** [comment] 2024-03-26 19:40
stable cargo backport is up #123105

**Comment by VorpalBlade** [comment] 2024-03-27 18:00
> Now that I think about it, that can actually be a bit problematic, since -Cstrip apparently overrides -Cdebug, and since Cargo uses -Cstrip, it cannot be easily overridden by RUSTFLAGS (OTOH, things that can be configured in a profile probably shouldn't be set in the flags...).

@Kobzol  This might impact building packages for Linux distros too. I know Arch Linux build system sets RUSTFLAGS expecting it to take effect just like CFLAGS etc does. It is exposed in the user config at `/etc/makepkg.conf` too. I would expect other distros to be impacted as well.

**Comment by Kobzol** [comment] 2024-03-27 18:36
You can still overwrite the defaut by setting `RUSTFLAGS="-Cstrip=none"`.

**Comment by apiraino** [comment] 2024-03-28 10:05
I will remove the t-compiler nomination since a decision to fix this in cargo was reached way faster, so I guess there is not a lot to discuss right now :-)

@rustbot label -I-compiler-nominated

**Comment by ChrisDenton** [comment] 2024-03-28 10:07
Discussing what rustc should do has moved to https://github.com/rust-lang/rust/pull/115120#issuecomment-2022352769

**Comment by retep998** [comment] 2024-03-28 16:49
Windows MSVC has debuginfo in a separate file, and thus stripping provides no benefits to binary size. Given generating the .pdb file does not take that much time, and how useful they are for backtraces, you should thus *always* default to generating the .pdb on Windows MSVC regardless of debug vs release.

This is something that was already figured out years before but I guess people just forget after a while.

**Comment by ChrisDenton** [comment] 2024-03-28 17:27
The "striping" behaviour of rustc has existed for four years now https://github.com/rust-lang/rust/commit/a6c2f73b6e0d24af5396355886b26bb23885c37e. I don't think Cargo was necessarily wrong to use `strip` cross-platform but rustc should have treated it as a no-op because, as you say, there's nothing to strip from the binary.

**Comment by retep998** [comment] 2024-03-28 18:04
And I think that PR from four years ago was *wrong* to do so. Someone brought up the reason that people might want to not emit PDB files on Windows (https://github.com/rust-lang/rust/pull/71825#discussion_r419868766), but if you look into the linked issue (https://github.com/rust-lang/rust/issues/67012) you'll see that they actually just didn't want the full path to the PDB file embedded into the binary. However, that reason was solved by a different PR fairly recently (https://github.com/rust-lang/rust/pull/121297).

Thus we should *stop* having `strip` affect PDB generation on Windows MSVC at all. It was wrong to do in the first place, but it's not too late to fix it.

As when we originally chose to emit `/DEBUG`, it was clearly done intentionally *always* and not conditionally. https://github.com/rust-lang/rust/pull/28505

**Comment by apiraino** [comment] 2024-04-11 10:33
can this be closed now?

**Comment by lqd** [comment] 2024-04-15 18:19
Fixes have landed on stable, beta, and nightly. Closing.

**Closed by lqd** 2024-04-15 18:19 UTC
Labels: A-debuginfo, T-compiler, regression-from-stable-to-stable, O-windows-msvc, P-critical, WG-debugging
