### ISSUE TITLE
Using `#[no_mangle]` in extern block produces confusing warning/error message

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust#84204] opened 2021-04-14 22:22 UTC
Given the following code: [play.rust-lang.org](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ceb7d98ce703d1a0c868678bebd0059d)

```rust
extern {
    #[no_mangle]
    pub static FOO: u8;
}
```

The current output is:

```
warning: attribute should be applied to a function or static
 --> src/lib.rs:2:5
  |
2 |     #[no_mangle]
  |     ^^^^^^^^^^^^
3 |     pub static BAR: u8;
  |     ------------------- not a function or static
  |
  = note: `#[warn(unused_attributes)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```

This error message is clearly confusing as it is saying that the static `BAR` isn't a static. To my knowledge using `#[no_mangle]` here is incorrect for imports as `#[no_mangle]` has exporting semantics.

**Comment by asquared31415** [comment] 2021-06-16 02:00
Duplicate of #78989

**Closed** 2021-06-16 08:24 UTC
Labels: A-diagnostics, T-compiler
