### ISSUE TITLE
Lifetime resolution in generic assoc types makes rustc panic

### ISSUE THREAD

**Issue by mcobzarenco** [rust-lang/rust#46793] opened 2017-12-17 22:42 UTC
I wanted to try out the new lifetime resolution in generic associated types merged in #46706. 

```rust
#![feature(generic_associated_types)]

pub trait Tokenizer {
    type TokenIter<'a>: Iterator<Item = &'a str>;
}
```
The above makes `rustc` panic
```
error: internal compiler error: /checkout/src/librustc/ty/subst.rs:424: Region parameter out of range when substituting in region 'a (root type=Some(&'a str)) (index=1)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (3bee2b44c 2017-12-16) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:449:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
(rustc version above)

Is this expected behaviour for now?

**Comment by kamyuentse** [comment] 2017-12-23 16:29
cc @sunjay 
Is this feature available now? Or any example usage for the current stage?

**Comment by sunjay** [comment] 2017-12-23 16:33
Hi,
This feature is still being developed and is not ready to be used yet. We can parse generic associated types and resolve names and lifetimes, but they won't work correctly until the implementation is complete. Subscribe to the [tracking issue](https://github.com/rust-lang/rust/issues/44265) for updates on our progress. :)

**Comment by kamyuentse** [comment] 2017-12-23 16:36
Thanks a lot.

@mcobzarenco  Seems this issue can be closed?

**Comment by Boddlnagg** [comment] 2017-12-29 10:22
I just ran into the same issue. I think it should not be closed until it's actually fixed 😉

**Comment by fafhrd91** [comment] 2018-01-12 20:44
I got same error trying to compile openssl crate with beta compiler

```
Compiling openssl v0.9.23
error: internal compiler error: /checkout/src/librustc/ty/subst.rs:424: Region parameter out of range when substituting in region 'a (root type=Some(unsafe fn(*mut <Self as foreign_types::ForeignTypeRef>::CType) -> &'a mut Self {<Self as foreign_types::ForeignTypeRef>::from_ptr_mut::<'a>})) (index=1)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.24.0-beta.2 (a19122cfa 2018-01-10) running on x86_64-unknown-linux-gnu
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:451:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Could not compile `openssl`.
```

**Comment by ia0** [comment] 2018-02-01 21:36
In case it's not exactly the same issue, I have the same kind of error but with a type parameter instead of a lifetime parameter: https://play.rust-lang.org/?gist=368fe46eed85670e35b876bf1c4c95d3&version=nightly
```rust
#![feature(generic_associated_types)]
trait Foo { type Bar<T>; }
struct Lol;
impl Foo for Lol { type Bar<T> = T; }
```

**Comment by pietroalbini** [comment] 2018-02-22 23:00
Duplicate of #47309. Closing this one.

**Closed by pietroalbini** 2018-02-22 23:00 UTC
Labels: A-associated-items, A-lifetimes, C-bug, I-ICE, T-compiler
