### ISSUE TITLE
Windows Command regression - broken paths

### ISSUE THREAD

**Issue by Awpteamoose** [rust-lang/rust#95178] opened 2022-03-21 17:32 UTC
### Code

I tried this code:

```rust
fn main() {
	std::process::Command::new("folder/echo.bat")
		.args(["hello"])
		.status()
		.unwrap();
}
```

where `folder/echo.bat` is
```bat
echo %*
```

I expected to see this happen:
```
   Compiling repro v0.1.0 (D:\projects\2022-03-20-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 1.03s
     Running `target\debug\repro.exe`

D:\projects\2022-03-20-repro>echo hello
hello
```

Instead, this happened:
```
   Compiling repro v0.1.0 (D:\projects\2022-03-20-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.95s
     Running `target\debug\repro.exe`

The system cannot find the path specified.
```

### Version it worked on
`rustc --version --verbose`:
```
rustc 1.61.0-nightly (1bfe40d11 2022-03-18)
binary: rustc
commit-hash: 1bfe40d11c3630254504fb73eeccfca28d50df52
commit-date: 2022-03-18
host: x86_64-pc-windows-msvc
release: 1.61.0-nightly
LLVM version: 14.0.0
```
(aka `nightly-2022-03-19`)

### Version with regression
`rustc --version --verbose`:
```
rustc 1.61.0-nightly (8d60bf427 2022-03-19)
binary: rustc
commit-hash: 8d60bf427a4b055f464122062e76b3ec34d4f8ba
commit-date: 2022-03-19
host: x86_64-pc-windows-msvc
release: 1.61.0-nightly
LLVM version: 14.0.0
```
(aka `nightly-2022-03-20`)

**Comment by ChrisDenton** [comment] 2022-03-21 18:15
Ah, this was caused by the switch to using verbatim paths (aka `\\?\`) for `Command`. This allows for using longer paths but aren't supported by `cmd.exe`. The workaround is to call cmd directly:

```rust
std::process::Command::new("cmd")
    .args(["/c", r"folder\echo.bat"])
    .arg("hello")
    .status()
    .unwrap()
```

The ultimate fix will be to [properly support running script files](https://github.com/rust-lang/rust/issues/94743). But it should be possible to fix this specific issue in the meantime.

**Comment by Awpteamoose** [comment] 2022-03-22 11:29
I'm not sure not being able to run scripts is exactly the case as I've run into this issue initially while trying to invoke `nuget.exe` and having nuget crash. Also if I call `echo.bat` without putting it in `folder` it also works fine.

**Comment by wwylele** [comment] 2022-03-22 13:12
The problem might be on `/`. iirc `\\?\` path doesn't support the other slash.

**Comment by ChrisDenton** [comment] 2022-03-22 16:58
> the case as I've run into this issue initially while trying to invoke nuget.exe and having nuget crash. 

I cannot quickly reproduce this locally but I suspect that's another (though related) issue. Some applications may not be able to cope with `argv[0]` being a `\\?\` path. The fix here will be to set `argv[0]` to exactly what the user entered (this is similar to how shells usually work).

> Also if I call `echo.bat` without putting it in `folder` it also works fine.

Yes, if you pass in just `echo.bat` it will work due to an undocumented feature of `CreateProcessW` (the underlying function call). It automagically rewrites the command to call `cmd.exe` in a way that may or may not work. If instead Rust itself had proper support for running script files then it would be easier to avoid these kinds of issues.

**Comment by apiraino** [comment] 2022-03-23 20:05
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2395178.20Windows.20Command.20regression.20-.20broken.20paths) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by messense** [comment] 2022-03-24 06:46
Looks like `std::env::current_exe()` also returns UNC path on Windows which caused a breakage in `cargo-zigbuild`: https://github.com/messense/cargo-zigbuild/pull/17

**Comment by j-hc** [comment] 2022-04-21 11:37
sorry for hijacking but is the pull request for the fix going to be merged anytime soon?

**Closed** 2022-04-25 10:14 UTC
Labels: P-medium, C-bug, regression-untriaged
