### ISSUE TITLE
portable simd: -Zmir-opt-level=3 causes LLVM ERROR

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#98016] opened 2022-06-12 06:18 UTC
I tried this code:
code originally from `./src/test/codegen/simd-wide-sum.rs`
```rust
#![crate_type = "lib"]
#![feature(portable_simd)]

use std::simd::Simd;
const N: usize = 8;

#[no_mangle]
// CHECK-LABEL: @wider_reduce_into_iter
pub fn wider_reduce_into_iter(x: Simd<u8, N>) -> u16 {
    // CHECK: zext <8 x i8>
    // CHECK-SAME: to <8 x i16>
    // CHECK: call i16 @llvm.vector.reduce.add.v8i16(<8 x i16>
    x.to_array().into_iter().map(u16::from).sum()
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (ec55c6130 2022-06-10)
binary: rustc
commit-hash: ec55c61305eaf385fc1b93ac9a78284b4d887fe5
commit-date: 2022-06-10
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
```

When compile with `-Zmir-opt-level=3`, there is a `LLVM_ERROR` which does not occur with `-Zmir-opt-level=2`
` rustc ./src/test/codegen/simd-wide-sum.rs  --edition=2021 -Zmir-opt-level=3 -Zvalidate-mir`

````
Invalid bitcast
  %10 = bitcast <8 x i8> %9 to [8 x i8]
in function wider_reduce_into_iter
LLVM ERROR: Broken function found, compilation aborted!
````

**Comment by eggyal** [comment] 2022-06-12 10:51
Due to inlining of [`Simd::to_array`](https://doc.rust-lang.org/core/simd/struct.Simd.html#method.to_array):

```zsh
al@eggy rust % rustc +nightly ./src/test/codegen/simd-wide-sum.rs --edition=2021 -Zmir-opt-level=3 -Zvalidate-mir -Zfuel=simd_wide_sum=46
warning: optimization-fuel-exhausted: Inline Instance { def: Item(WithOptConstParam { did: DefId(2:23390 ~ core[a873]::core_simd::vector::{impl#0}::to_array), const_param_did: None }), substs: [u8, Const { ty: usize, val: Value(Scalar(0x0000000000000008)) }] } into MirSource { instance: Item(WithOptConstParam { did: DefId(0:10 ~ simd_wide_sum[31d5]::wider_reduce_into_iter), const_param_did: None }), promoted: None }

warning: 1 warning emitted

al@eggy rust % rustc +nightly ./src/test/codegen/simd-wide-sum.rs --edition=2021 -Zmir-opt-level=3 -Zvalidate-mir -Zfuel=simd_wide_sum=47
warning: optimization-fuel-exhausted: Inline Instance { def: Item(WithOptConstParam { did: DefId(2:8403 ~ core[a873]::iter::traits::iterator::Iterator::map), const_param_did: None }), substs: [std::array::IntoIter<u8, 8_usize>, u16, fn(u8) -> u16 {<u16 as std::convert::From<u8>>::from}] } into MirSource { instance: Item(WithOptConstParam { did: DefId(0:10 ~ simd_wide_sum[31d5]::wider_reduce_into_iter), const_param_did: None }), promoted: None }

Invalid bitcast
  %6 = bitcast <8 x i8> %5 to [8 x i8]
in function wider_reduce_into_iter
LLVM ERROR: Broken function found, compilation aborted!

al@eggy rust % rustc +nightly --version --verbose
rustc 1.63.0-nightly (99930ac7f 2022-06-11)
binary: rustc
commit-hash: 99930ac7f8cbb5d9b319b2e2e92794fd6f24f556
commit-date: 2022-06-11
host: x86_64-apple-darwin
release: 1.63.0-nightly
LLVM version: 14.0.5
```

**Comment by eggyal** [comment] 2022-06-12 11:30
MIR diff from before and after that pass is run:

```diff
diff --git a/simd-wide-sum.mir.before b/simd-wide-sum.mir.after
index a7f4347f669..d73408fdc1f 100644
--- a/simd-wide-sum.mir.before
+++ b/simd-wide-sum.mir.after
@@ -5,24 +5,21 @@ fn wider_reduce_into_iter(_1: Simd<u8, 8_usize>) -> u16 {
     let mut _3: std::array::IntoIter<u8, 8_usize>; // in scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:29
     let mut _4: [u8; 8];                 // in scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:17
     let mut _5: std::simd::Simd<u8, 8_usize>; // in scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:6
+    scope 1 (inlined Simd::<u8, 8_usize>::to_array) { // at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:17
+        debug self => _5;                // in scope 1 at /rustc/99930ac7f8cbb5d9b319b2e2e92794fd6f24f556/library/core/src/../../portable-simd/crates/core_simd/src/vector.rs:128:27: 128:31
+    }
 
     bb0: {
         _5 = _1;                         // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:6
-        _4 = Simd::<u8, 8_usize>::to_array(move _5) -> bb1; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:17
-                                         // mir::Constant
-                                         // + span: ./src/test/codegen/simd-wide-sum.rs:53:7: 53:15
-                                         // + literal: Const { ty: fn(Simd<u8, 8_usize>) -> [u8; 8] {Simd::<u8, 8_usize>::to_array}, val: Value(Scalar(<ZST>)) }
-    }
-
-    bb1: {
-        _3 = <[u8; 8] as IntoIterator>::into_iter(move _4) -> bb2; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:29
+        _4 = (_5.0: [u8; 8]);            // scope 1 at /rustc/99930ac7f8cbb5d9b319b2e2e92794fd6f24f556/library/core/src/../../portable-simd/crates/core_simd/src/vector.rs:129:9: 129:15
+        _3 = <[u8; 8] as IntoIterator>::into_iter(move _4) -> bb1; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:29
                                          // mir::Constant
                                          // + span: ./src/test/codegen/simd-wide-sum.rs:53:18: 53:27
                                          // + literal: Const { ty: fn([u8; 8]) -> <[u8; 8] as IntoIterator>::IntoIter {<[u8; 8] as IntoIterator>::into_iter}, val: Value(Scalar(<ZST>)) }
     }
 
-    bb2: {
-        _2 = <std::array::IntoIter<u8, 8_usize> as Iterator>::map::<u16, fn(u8) -> u16 {<u16 as From<u8>>::from}>(move _3, <u16 as From<u8>>::from) -> bb3; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:44
+    bb1: {
+        _2 = <std::array::IntoIter<u8, 8_usize> as Iterator>::map::<u16, fn(u8) -> u16 {<u16 as From<u8>>::from}>(move _3, <u16 as From<u8>>::from) -> bb2; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:44
                                          // mir::Constant
                                          // + span: ./src/test/codegen/simd-wide-sum.rs:53:30: 53:33
                                          // + literal: Const { ty: fn(std::array::IntoIter<u8, 8_usize>, fn(u8) -> u16 {<u16 as From<u8>>::from}) -> Map<std::array::IntoIter<u8, 8_usize>, fn(u8) -> u16 {<u16 as From<u8>>::from}> {<std::array::IntoIter<u8, 8_usize> as Iterator>::map::<u16, fn(u8) -> u16 {<u16 as From<u8>>::from}>}, val: Value(Scalar(<ZST>)) }
@@ -32,14 +29,14 @@ fn wider_reduce_into_iter(_1: Simd<u8, 8_usize>) -> u16 {
                                          // + literal: Const { ty: fn(u8) -> u16 {<u16 as From<u8>>::from}, val: Value(Scalar(<ZST>)) }
     }
 
-    bb3: {
-        _0 = <Map<std::array::IntoIter<u8, 8_usize>, fn(u8) -> u16 {<u16 as From<u8>>::from}> as Iterator>::sum::<u16>(move _2) -> bb4; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:50
+    bb2: {
+        _0 = <Map<std::array::IntoIter<u8, 8_usize>, fn(u8) -> u16 {<u16 as From<u8>>::from}> as Iterator>::sum::<u16>(move _2) -> bb3; // scope 0 at ./src/test/codegen/simd-wide-sum.rs:53:5: 53:50
                                          // mir::Constant
                                          // + span: ./src/test/codegen/simd-wide-sum.rs:53:45: 53:48
                                          // + literal: Const { ty: fn(Map<std::array::IntoIter<u8, 8_usize>, fn(u8) -> u16 {<u16 as From<u8>>::from}>) -> u16 {<Map<std::array::IntoIter<u8, 8_usize>, fn(u8) -> u16 {<u16 as From<u8>>::from}> as Iterator>::sum::<u16>}, val: Value(Scalar(<ZST>)) }
     }
 
-    bb4: {
+    bb3: {
         return;                          // scope 0 at ./src/test/codegen/simd-wide-sum.rs:54:2: 54:2
     }
 }
```

**Comment by eggyal** [comment] 2022-06-12 13:10
I don't read MIR very well, but `_4 = (_5.0: [u8; 8]);` is surely the culprit.  Presumably that is "bitcast place _5 (a `Simd<u8, 8>`) to `[u8; 8]`, precisely the error at issue?  I'll try and figure out what MIR the non-inlined function translates to...

**Comment by matthiaskrgr** [comment] 2022-06-12 13:18
does the no_mangle attr have done kind of effect? can't check on mobile right now

**Comment by eggyal** [comment] 2022-06-12 13:33
I think it's more likely the `Simd` struct's `repr(simd)` being ignored when performing that field access.

**Comment by eggyal** [comment] 2022-06-12 19:08
A slightly simplified example:

```rust
#![crate_type = "lib"]
#![feature(repr_simd)]

#[repr(simd)]
pub struct Simd<T>([T; 8]);

impl<T> Simd<T> {
    pub fn to_array(self) -> [T; 8] {
        self.0
    }
}

pub fn to_array(x: Simd<u8>) -> [u8; 8] {
    x.to_array()
}
```

It only arises when `Simd` is generic over `T`.

**Comment by bjorn3** [comment] 2022-06-12 19:44
The difference seems to be that `x.0` bitcasts a pointer to a vector, while the inlined `to_array_inner` bitcasts a vector directly. I suspect that the extra move that happens when `to_array_inner` is inlined causes vector value to be stored behind a pointer. I can reproduce the crash using just

```rust
pub fn to_array_outer(x: Simd) -> [u8; 8] {
    let y = x;
    y.0
}
```

to force an extra move. As for why `to_array_inner` puts the vector behind a pointer, the default rust abi passes vector types by-ref to ensure that changing target features doesn't change the abi.

**Comment by bjorn3** [comment] 2022-06-12 19:46
With `--emit llvm-ir -Cno-prepopulate-passes -Zverify-llvm-ir` that crashes at

```
Invalid bitcast
  %1 = bitcast <8 x i8> %y to [8 x i8], !dbg !11
LLVM ERROR: Broken module found, compilation aborted!
Compiler returned: 101
```

and without `-Zverify-llvm-ir` it gives the following LLVM ir:

```llvm
define i64 @_ZN7example14to_array_outer17h4eae74749e7c0538E(<8 x i8>* %x) unnamed_addr #0 !dbg !5 {
  %0 = alloca [8 x i8], align 1
  %y = load <8 x i8>, <8 x i8>* %x, align 8, !dbg !10
  %1 = bitcast <8 x i8> %y to [8 x i8], !dbg !11
  store [8 x i8] %1, [8 x i8]* %0, align 1, !dbg !11
  %2 = bitcast [8 x i8]* %0 to i64*, !dbg !13
  %3 = load i64, i64* %2, align 1, !dbg !13
  ret i64 %3, !dbg !13
}
```

**Comment by eggyal** [comment] 2022-06-12 20:30
> As for why `to_array_inner` puts the vector behind a pointer, the default rust abi passes vector types by-ref to ensure that changing target features doesn't change the abi.

It's interesting that the failure (in my example) required `to_array_inner` to be generic—that shouldn't affect the ABI of the monomorphized function, should it?

**Comment by bjorn3** [comment] 2022-06-12 20:48
Indeed. It shouldn't affect the ABI.

**Comment by Alexendoo** [comment] 2022-11-28 13:00
The original no longer ICEs since #96451, but https://github.com/rust-lang/rust/issues/98016#issuecomment-1153273587 still does

**Comment by JohnTitor** [comment] 2023-02-17 10:38
Triage: The above mentioned example now compiles fine with the latest nightly, I guess https://github.com/rust-lang/rust/pull/107449 is related. Marking as `E-needs-test`.

**Closed** 2023-07-13 18:15 UTC
Labels: I-crash, A-LLVM, E-needs-test, T-compiler, A-simd, C-bug, glacier, A-mir-opt, PG-portable-simd
