### ISSUE TITLE
VecDeque's Drain::drop writes to memory that a shared reference points to

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#60076] opened 2019-04-18 11:35 UTC
liballoc's `test_drain` fails when run in Miri. The error occurs in the `drain(...).collect()` call:

* `collect` is called with a `vec_deque::Drain<usize>` as argument. `Drain` contains `Iter` contains a shared reference to a slice; that slice is thus marked as "must not be mutated for the entire duration of this function call".
* `collect` calls `from_iter` calls `extend` calls `for_each` calls `fold`, which eventually drops the `Drain`.
* `Drain::drop` calls `source_deque.wrap_copy` to re-arrange stuff (I have not fully understood this yet), and in some cases this will end up writing to memory that the slice in `Iter` points to.

I am not sure what the best way to fix this is. We have to fix `Drain` holding (indirectly) a shared reference to something that it'll mutate during its `Drop`. The mutation is likely there for a reason, so I guess the shared reference has to go. (FWIW, this shared reference already caused other trouble, but that was fixed by https://github.com/rust-lang/rust/pull/56161.)

Cc @nikomatsakis @Gankro

**Comment by Gankro** [comment] 2019-04-18 14:21
yeah I guess just change it to `*const [T]` and toss in a PhantomData for the borrow. *shrug*

**Comment by RalfJung** [comment] 2019-04-18 15:38
You mean, change this in `Iter` as well? Sure, that should work. In principle this reduces the precision of compiler analyses on `VecDeque::iter()`.

**Comment by Gankro** [comment] 2019-04-18 16:26
ahh misread. maybe would just not use Iter then. depends on what the impl looks like now

**Comment by cuviper** [comment] 2019-04-18 22:25
> * `Drain::drop` calls `source_deque.wrap_copy` to re-arrange stuff (I have not fully understood this yet), and in some cases this will end up writing to memory that the slice in `Iter` points to.

But the *first* thing it does is `self.for_each(drop);` which should exhaust the `Iter` such that its `ring` is an empty slice. I suppose its pointer will still be somewhere in the deque's memory, but with length 0 it can't actually read anything. Is that not good enough to appease Miri?

**Comment by RalfJung** [comment] 2019-04-19 13:56
@cuviper
> But the first thing it does is self.for_each(drop); which should exhaust the Iter such that its ring is an empty slice. I suppose its pointer will still be somewhere in the deque's memory, but with length 0 it can't actually read anything. Is that not good enough to appease Miri?

No. This code still matches the pattern
```rust
fn foo(mut x: (T, &[U])) {
  // do some stuff with x that "semantically" "exhausts" the slice.
  // then write to it.
}
```
There is no notion of "exhausting" or "consuming" a shared reference. When you create a shared reference with a certain lifetime, you promise that until that lifetime ends, no mutation happens. `x` here is mutable so you can change what the slice points to, but that has no effect at all on the guarantees that have been made about the value that was initially passed to `foo`.

Now, lifetimes are an entirely static concept, so for Stacked Borrows a "lifetime" generally is "until the pointer is used for the last time". However, for the special case of a reference being passed to the function, Stacked Borrows asserts that the "lifetime" will last at least as long as the function the reference is pointed to. This is extremely useful for optimizations.

**Comment by RalfJung** [comment] 2019-04-19 14:03
> ahh misread. maybe would just not use Iter then. depends on what the impl looks like now

`Drain::{next, next_back, size_hint}` forward to `Iter`. I wouldn't want to copy those.

**Comment by cuviper** [comment] 2019-04-19 15:33
Oh, I also didn't realize that `Iter` doesn't actually shrink down to an empty slice -- it only updates its indexes. It would otherwise have to use two slices for the wrapped head and tail. So that full shared reference does still exist after the iterator is exhausted. (This also raises the validity question of having references to uninitialized data.)

Could we base it on `IterMut` instead? We could arrange `wrap_copy` to work through that mutable reference too, so there's no question of mutable aliasing.

**Comment by RalfJung** [comment] 2019-04-19 16:02
> Could we base Drain on IterMut instead? We could arrange wrap_copy to work through that mutable reference too, so there's no question of mutable aliasing.

That might work. However, `Drain::drop` must not access `deque.buf` in that case -- that woulod be in conflict with the unique reference in `IterMut`.

**Comment by cuviper** [comment] 2019-04-19 16:13
Hmm, does `Drain` need to be covariant over `T`? I guess `IterMut` would break that.

**Comment by RalfJung** [comment] 2019-04-19 20:34
Actually this idea of "consuming a shared ref" is far from unique to `VecDeque`... the following code also errors in Miri:
```rust
use std::cell::{RefCell, Ref};

fn break_it(rc: &RefCell<i32>, r: Ref<'_, i32>) {
    // `r` has a shared reference, it is passed in as argument and hence
    // a barrier is added that marks this memory as read-only for the entire
    // duration of this function.
    drop(r);
    // *oops* here we can mutate that memory.
    *rc.borrow_mut() = 2;
}

fn main() {
    let rc = RefCell::new(0);
    break_it(&rc, rc.borrow())
}
```

**Comment by Julius-Beides** [comment] 2019-04-20 08:37
As I understand it, Miri and stacked borrows should be "more powerful" than the Rust borrow checker, right?
So, is this an example where Miri does not match what Rust allows or is this a bug in Rust that could lead to undefined behaviour in safe code?
([Your example in the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=23f8da0e3d21390ee493583143087da9))

**Comment by cuviper** [comment] 2019-04-20 15:10
@Julius-Beides -- I believe @RalfJung is admitting that `RefCell` example as something that should be allowed. But this issue with `VecDeque` involved raw pointers, which rustc doesn't check at all, so miri is in uncharted waters here.

**Comment by RalfJung** [comment] 2019-04-20 17:29
> So, is this an example where Miri does not match what Rust allows or is this a bug in Rust that could lead to undefined behaviour in safe code?

This is up for us all to decide. I can't tell you. ;)

> I believe @RalfJung is admitting that RefCell example as something that should be allowed.

Not necessary. I have argued that `Ref`/`RefMut` are problematic long before "Stacked Borrows". The lifetimes there are, strictly speaking, wrong. I think it would be reasonable to rule that they have to use raw pointers.

**Comment by RalfJung** [comment] 2019-06-09 11:27
FWIW here is a stand-alone version of the testcase to reproduce this with Miri (but it needs access to some private `VecDeque` internals):
```rust
use std::collections::VecDeque;

fn main() {
    let mut tester: VecDeque<usize> = VecDeque::with_capacity(3);

    let cap = tester.capacity();
    for len in 0..=cap {
        for tail in 0..=cap {
            for drain_start in 0..=len {
                for drain_end in drain_start..=len {
                    tester.tail = tail;
                    tester.head = tail;
                    for i in 0..len {
                        tester.push_back(i);
                    }

                    // Check that we drain the correct values
                    println!("Testing {} {} {} {}", len, tail, drain_start, drain_end);
                    let drained: VecDeque<_> = tester.drain(drain_start..drain_end).collect();
                    let drained_expected: VecDeque<_> = (drain_start..drain_end).collect();
                    assert_eq!(drained, drained_expected);

                    // We shouldn't have changed the capacity or made the
                    // head or tail out of bounds
                    assert_eq!(tester.capacity(), cap);
                    assert!(tester.tail < tester.cap());
                    assert!(tester.head < tester.cap());

                    // We should see the correct values in the VecDeque
                    let expected: VecDeque<_> = (0..drain_start)
                        .chain(drain_end..len)
                        .collect();
                    assert_eq!(expected, tester);
                }
            }
        }
    }
}
```

**Comment by RalfJung** [comment] 2019-08-04 12:03
See https://github.com/rust-lang/unsafe-code-guidelines/issues/125 for the issue about whether Stacked Borrows should allow such code or not.

For now, with https://github.com/rust-lang/miri/pull/872, Miri accepts this code again. So I am going to close the issue here. It still represents an interesting data point to inform what Stacked Borrows rules *should* be.

**Comment by Gankro** [comment] 2019-08-07 03:28
*nods wisely*

just gotta stand still long enough for the spec to bend around *you*

**Comment by RalfJung** [comment] 2019-08-07 07:04
@Gankro ;-)

I don't think the decision is made either way, but for now with several counterexamples in libstd, it is not helpful for Miri to complain about this.

**Comment by RalfJung** [comment] 2019-08-21 14:48
See https://github.com/rust-lang/rust/issues/63787: there actually *is* a bug here right now, because we *do* emit `noalias` for `Drain` passed to a function. So what Miri found is actually UB in the LLVM IR that we are generating right now.

Reopening for now, but maybe it makes more sense to treat this as a duplicate of https://github.com/rust-lang/rust/issues/63787.

**Comment by 5225225** [comment] 2022-08-13 14:34
Smaller reproduction that I found in #99701 (a now closed dupe of this issue) that doesn't rely on VecDeque internals, that fails now with `-Zmiri-retag-fields`

```rust
use std::collections::VecDeque;

fn main() {
    let mut tester: VecDeque<usize> = VecDeque::with_capacity(3);

    for i in 0..3 {
        tester.push_back(i);
    }

    let _: VecDeque<_> = tester.drain(1..2).collect();
}
```

**Comment by RalfJung** [comment] 2022-08-13 18:26
`-Zmiri-retag-fields` re-enables the part of Stacked Borrows that got disabled to work around the issue.

**Closed** 2022-09-11 22:19 UTC
Labels: A-collections, T-libs-api, I-unsound, C-bug
