### ISSUE TITLE
Cargo clippy failing on rustc 1.50.0-nightly (6a889570e 2020-11-27) running on x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by xnuter** [rust-lang/rust#79491] opened 2020-11-28 07:44 UTC
### Code

It failed on `cargo clippy -- -D warnings` for me: https://github.com/xnuter/perf-gauge/runs/1466340454?check_suite_focus=true

### Error output

```
   Compiling aho-corasick v0.7.15
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:1268 ~ ring[a231]::digest::sha2::)`,
 right: `DefId(0:1269 ~ ring[a231]::digest::sha2::::GFp_sha256_block_data_order)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (6a889570e 2020-11-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z profile -Z panic_abort_tests -C embed-bitcode=no -C debuginfo=2 -C codegen-units=1 -C inline-threshold=0 -C link-dead-code -C overflow-checks=off -C panic=abort --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [index_hir] index HIR
#1 [hir_owner] HIR owner of `{misc#0}`
end of query stack
error: could not compile `ring`
Error: could not compile `ring`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
Warning: error: build failed
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

### Comments

I cannot run this with `stable` because the github action `grcov` works only with `nightly`

</p>
</details>

**Comment by jyn514** [comment] 2020-11-28 12:38
cc @rust-lang/clippy

**Comment by jonas-schievink** [comment] 2020-11-28 12:54
Duplicate of https://github.com/rust-lang/rust/issues/79487, not a Clippy bug

**Closed by jonas-schievink** 2020-11-28 12:54 UTC
Labels: A-clippy, C-bug, I-ICE, T-compiler
