### ISSUE TITLE
macro_rules treating ';' as an ident

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26444] opened 2015-06-19 23:26 UTC
This [playpen](https://play.rust-lang.org/?gist=bcaf5028ccb692e25803&version=stable) contains a macro with two *-repeating arguments, plus a non-repeating argument sandwiched between them. It works fine when the repeating arguments are supplied, but when I try to leave out the first one, rustc claims the syntax is ambiguous. But I can't see why.

**Comment by jFransham** [comment] 2015-09-10 13:11
I have this problem with = too, in the pattern `( $fname:ident $( $arg:pat )* = )`. I get "ambiguous syntax" for the = symbol.

**Comment by bluss** [comment] 2015-09-10 13:17
It's a known limitation of macros, see https://doc.rust-lang.org/book/macros.html#syntactic-requirements.

> The macro system does not deal with parse ambiguity at all.

**Comment by durka** [comment] 2015-09-10 15:35
What's strange is that it's perfectly capable of using `;` to terminate the repeating ident matcher, because `;` clearly isn't an ident. But it won't use that fact to disambiguate the match at the first token.

**Comment by durka** [comment] 2015-09-10 15:36
Also, the example at that point in the book doesn't make any sense. Neither `expr` or `E` can follow a `ty` fragment.

**Comment by brson** [comment] 2017-03-09 17:43
Current output:

```


rustc 1.15.1 (021bd294c 2017-02-08)
error: local ambiguity: multiple parsing options: built-in NTs ident ('beginning') or 1 other option.
 --> <anon>:9:25
  |
9 |     println!("{}", foo!(; f ;));
  |                         ^

Compilation failed.
```

**Comment by nikomatsakis** [comment] 2017-03-09 17:47
The problem is not that `;` is considered as an identifier (see e.g. <https://is.gd/lJjUHz>), but rather that once we start parsing a "fragment" (like `$x:tt`), parsing must succeed or macro parsing aborts. Fixing this turned out to be quite complex, and I expect we'll only address it in macros 2.0. Closing.

**Closed by nikomatsakis** 2017-03-09 17:47 UTC
Labels: A-macros, P-low, T-lang
