### ISSUE TITLE
Validate all `#[inline]` attributes earlier

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#40792] opened 2017-03-24 06:32 UTC
Today, the following compiles:
```rust
struct MyStruct<T>(T);

impl<T> MyStruct<T> {
    #[inline(foo)]
    pub fn f(self) {}
}
```

**Comment by jseyfried** [comment] 2017-03-24 06:32
cc @SergioBenitez

**Comment by kennytm** [comment] 2017-07-27 19:12
It does error when you actually instantiate `MyStruct<T>::f`.

```rust
struct MyStruct<T>(T);

impl<T> MyStruct<T> {
    #[inline(foo)]
    pub fn f(self) {}
}

fn main() {
    let f = MyStruct(4);
    f.f();  // <-- call this to raise error.
}
```

The problem is that the check is performed in `syntax::attr::{requests_inline, find_inline_attr}` which were called only during trans (and MIR inlining pass but it is disabled by default), so nothing will be checked if this is not monomorphized.

**Comment by nikomatsakis** [comment] 2017-11-03 18:45
Closing in favor of #45738, which has mentoring instructions.

**Closed by nikomatsakis** 2017-11-03 18:45 UTC
Labels: C-bug, T-compiler
