### ISSUE TITLE
Rustdoc links items in the standard library to the original crate, not the re-export

### ISSUE THREAD

**Issue by Evian-Zhang** [rust-lang/rust#78467] opened 2020-10-28 02:26 UTC
In my docs, I use ``[`String`]`` or even ``[`std::string::String`]``, I expect the generated link is to the [std page](https://doc.rust-lang.org/std/string/struct.String.html), but the generated link is to the [alloc page](https://doc.rust-lang.org/alloc/string/struct.String.html).

I know maybe `std` re-exports some structs in `alloc`, `core`, etc. but for a beginner who does not know well about rust, he may be confused when clicking the link to String and get an unfamiliar path. So what can I do if I want to link to `std` page?

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (a1dfd2490 2020-10-05)
binary: rustc
commit-hash: a1dfd2490a6cb456b92e469fa550dc217e20ad6d
commit-date: 2020-10-05
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by jyn514** [comment] 2020-10-28 05:03
This is not really supported by intra-doc links. How should it know which re-exports are canonical and which are not? The best it can do is the original place the item was defined.

**Comment by camelid** [comment] 2020-10-28 05:08
*Perhaps* we could add some kind of attribute to a re-export (something like `#[canonical]` or `#[rustdoc_canonical]`) but I don't think it's necessarily worth it.

**Comment by jyn514** [comment] 2020-10-28 05:11
Note that this is not specific to intra-doc links, if you have a function returning string, rustdoc will also link to alloc, not std.

**Comment by Nemo157** [comment] 2020-10-28 11:11
Is the data used to decide when to inline the docs available during intra-doc links (`#[doc(inline)]` + whatever makes it implicitly inline)? If rustdoc knows which re-export was used in a particular link (and other locations), and has that data available, it seems like the inlining of the docs matches up with when you would want to link to the inlined docs instead of the original location.

**Comment by jyn514** [comment] 2020-10-28 13:27
This logic is done by `fn href`: https://github.com/rust-lang/rust/blob/6bea76f175f1a565320a1a93a174fb80567dda7c/src/librustdoc/html/format.rs#L483
In particular, if it's not in `cache.paths`, it always looks in the original crate: https://github.com/rust-lang/rust/blob/6bea76f175f1a565320a1a93a174fb80567dda7c/src/librustdoc/html/format.rs#L497
I don't know what causes something to be in paths or extern_locations.

**Comment by jyn514** [comment] 2020-11-04 05:19
This is actually a duplicate of https://github.com/rust-lang/rust/issues/22083.

**Closed by jyn514** 2020-11-04 05:19 UTC
Labels: T-rustdoc, C-feature-request

**Comment by jyn514** [comment] 2021-04-08 17:51
> Is the data used to decide when to inline the docs available during intra-doc links (#[doc(inline)] + whatever makes it implicitly inline)? If rustdoc knows which re-export was used in a particular link (and other locations), and has that data available, it seems like the inlining of the docs matches up with when you would want to link to the inlined docs instead of the original location.

> This logic is done by fn href: 

So no: https://github.com/rust-lang/rust/pull/82014#issue-572242853
