### ISSUE TITLE
Cannot compile firefox anymore

### ISSUE THREAD

**Issue by calixteman** [rust-lang/rust#43808] opened 2017-08-11 13:36 UTC
1:54.98    Compiling webrender_bindings v0.1.0 (file:///home/calixte/dev/mozilla/mozilla-central.hg/gfx/webrender_bindings)
 1:54.98 error: internal compiler error: /checkout/src/librustc_typeck/astconv.rs:1267: anonymous bound region BrAnon(1) in return but not args
 1:54.98    --> /home/calixte/dev/mozilla/mozilla-central.hg/obj-x86_64-pc-linux-gnu/toolkit/library/x86_64-unknown-linux-gnu/release/build/style-b980317b2d512036/out/gecko/bindings.rs:532:9
 1:54.98     |
 1:54.98 532 |      -> RawGeckoNodeBorrowedOrNull;
 1:54.98     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
 1:54.98 
 1:54.98 note: the compiler unexpectedly panicked. this is a bug.
 1:54.98 
 1:54.98 note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
 1:54.98 
 1:54.98 note: rustc 1.21.0-nightly (13d94d5fa 2017-08-10) running on x86_64-unknown-linux-gnu
 1:54.98 
 1:54.98 note: run with `RUST_BACKTRACE=1` for a backtrace
 1:54.98 
 1:54.98 thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:434:8
 1:54.98 stack backtrace:
 1:54.98    0:     0x7f43083c1c83 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hc9320db76922c77f
 1:54.98                                at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
 1:54.98    1:     0x7f43083bc414 - std::sys_common::backtrace::_print::hd1cad143436e7e7b
 1:54.98                                at /checkout/src/libstd/sys_common/backtrace.rs:71
 1:54.98    2:     0x7f43083cf493 - std::panicking::default_hook::{{closure}}::h8ce44357afd55c76
 1:54.98                                at /checkout/src/libstd/sys_common/backtrace.rs:60
 1:54.98                                at /checkout/src/libstd/panicking.rs:380
 1:54.98    3:     0x7f43083cf18a - std::panicking::default_hook::h85c58325ebacf8fb
 1:54.98                                at /checkout/src/libstd/panicking.rs:390
 1:54.98    4:     0x7f43083cf997 - std::panicking::rust_panic_with_hook::hfa335e60391f47d9
 1:54.98                                at /checkout/src/libstd/panicking.rs:610
 1:54.98    5:     0x7f43057946a8 - std::panicking::begin_panic::h528dcfd1e0c95df0
 1:54.98    6:     0x7f43057902f3 - rustc_errors::Handler::span_bug::h9fb3bb385ec804bf
 1:54.98    7:     0x7f43057c3244 - rustc::session::opt_span_bug_fmt::{{closure}}::h40f5623c4951b591
 1:54.98    8:     0x7f43057c30d7 - rustc::session::span_bug_fmt::h5e14f6e6dbcf5753
 1:54.98    9:     0x7f430586bc36 - <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ty_of_fn::hbf7c6b4bfadb36b8
 1:54.98   10:     0x7f430587548a - rustc_typeck::collect::fn_sig::h21dc19594da6e3e2
 1:54.98   11:     0x7f430520cb4b - rustc::dep_graph::graph::DepGraph::with_task::hd60db530bfb970cb
 1:54.98   12:     0x7f43054235aa - rustc::ty::maps::<impl rustc::ty::maps::queries::fn_sig<'tcx>>::try_get::h146503a52e6d795a
 1:54.98   13:     0x7f430545f16f - rustc::ty::maps::TyCtxtAt::fn_sig::h9296197fe24db9bb
 1:54.98   14:     0x7f430545b927 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::fn_sig::h0082236b52519e8e
 1:54.98   15:     0x7f430586dac7 - <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h4a7caef92b58bbb6
 1:54.98   16:     0x7f430588cfdc - rustc_typeck::check_crate::{{closure}}::{{closure}}::h11dad5088c44b9ea
 1:54.98   17:     0x7f430588b1de - rustc_typeck::check_crate::he7514f54bbc90a21
 1:54.98   18:     0x7f43086f35b0 - rustc::ty::context::TyCtxt::create_and_enter::hf0b1401af74e7747
 1:54.99   19:     0x7f4308750ed1 - rustc_driver::driver::compile_input::h7e4322197bc87ab7
 1:54.99   20:     0x7f430876a782 - rustc_driver::run_compiler::h7ff66578813a854d
 1:54.99   21:     0x7f43086a8261 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2a0cfbdf7b97e796
 1:54.99   22:     0x7f43083feedc - __rust_maybe_catch_panic
 1:54.99                                at /checkout/src/libpanic_unwind/lib.rs:98
 1:54.99   23:     0x7f43086db900 - <F as alloc::boxed::FnBox<A>>::call_box::hb763c222ac18e463
 1:54.99   24:     0x7f43083ce3cb - std::sys::imp::thread::Thread::new::thread_start::h79a2d07a57977c8b
 1:54.99                                at /checkout/src/liballoc/boxed.rs:692
 1:54.99                                at /checkout/src/libstd/sys_common/thread.rs:21
 1:54.99                                at /checkout/src/libstd/sys/unix/thread.rs:84
 1:54.99   25:     0x7f43035e3493 - start_thread
 1:54.99   26:     0x7f4308089a8e - __clone
 1:54.99   27:                0x0 - <unknown>
 1:54.99 
 1:54.99 error: Could not compile `style`.

**Comment by Mark-Simulacrum** [comment] 2017-08-11 13:43
Thanks! This is a duplicate of https://github.com/rust-lang/rust/issues/43567 though.

**Closed by Mark-Simulacrum** 2017-08-11 13:43 UTC
