### ISSUE TITLE
Macro usage. Compiler error

### ISSUE THREAD

**Issue by MageSlayer** [rust-lang/rust#42029] opened 2017-05-16 08:24 UTC
Hi all

Attached example crashes current nightly Rust (rustc 1.19.0-nightly (75b056812 2017-05-15)) when built using RUST_BACKTRACE=1 cargo build

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Expected Def::Macro(..)', /checkout/src/librustc_resolve/build_reduced_graph.rs:528
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::get_macro
   7: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::resolve_invoc
   8: syntax::ext::expand::MacroExpander::expand
   9: syntax::ext::expand::MacroExpander::expand_crate
  10: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}
  11: rustc_driver::driver::phase_2_configure_and_expand
  12: rustc_driver::driver::compile_input
  13: rustc_driver::run_compiler

```

[macro-test.tar.gz](https://github.com/rust-lang/rust/files/1003716/macro-test.tar.gz)

**Comment by est31** [comment] 2017-05-16 09:50
Looks like a dupe of #41719

**Comment by MageSlayer** [comment] 2017-05-16 10:07
Yes.
Looks like removing #![feature(use_extern_macros)] and restructuring macro appropriately allows to workaround the issue.
Thanks for hint.

**Comment by Mark-Simulacrum** [comment] 2017-06-22 23:31
Closing in favor of https://github.com/rust-lang/rust/issues/41719.

**Closed by Mark-Simulacrum** 2017-06-22 23:31 UTC
