### ISSUE TITLE
Conflict  about Some(1|2) in 1.53

### ISSUE THREAD

**Issue by kkonghao** [rust-lang/rust#86408] opened 2021-06-17 18:06 UTC
hi when i use rust 1.53 version some code about pattern match  below make me confused,and i think this is a bug or  a problem that cannot be ignored.

```Rust
	let x = Some(2);
	assert!(matches!(x,Some(1 | 2)));//ok x is Some(2)
	assert!(matches!(Some(1),Some(1|2)));//ok
	assert!(matches!(Some(2),Some(1|2)));//ok

	let y = Some(1 | 2);//y is Some(3)
	// assert!(matches!(Some(3),Some(1|2)));// error, Some(1|2) =>is Some(1) | Some(2) or Some(3)?

```

**Comment by bugadani** [comment] 2021-06-17 18:54
This isn't new at all: https://github.com/rust-lang/rfcs/pull/2535#issuecomment-417946085

Since `1|2` already had the same ambiguoity, this has been kind of "ignored" as far as I understand, but don't quote me on the reasoning.

**Comment by jonas-schievink** [comment] 2021-06-17 18:55
or-patterns do not function as binary operators. This is working as intended, so closing.

**Closed by jonas-schievink** 2021-06-17 18:55 UTC
