### ISSUE TITLE
Compiling failed: could not compile image

### ISSUE THREAD

**Issue by DarwinSenior** [rust-lang/rust#41658] opened 2017-04-30 19:17 UTC
I created a new project with 'cargo'
And here is the configuration
```toml
[package]
name = "helloworld"
version = "0.1.0"
authors = ["darwinsenior <darwinsenior@gmail.com>"]

[dependencies]
image = "0.13.0"
```

And I met with the following error when running `cargo install`.

```
  Installing toolkit v0.1.0 (file:///home/darwinsenior/workspace/research/code/toolkit)
   Compiling image v0.13.0
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'assertion failed: !unsize', /checkout/src/librustc_typeck/check/mod.rs:2212
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: failed to compile `toolkit v0.1.0 (file:///home/darwinsenior/workspace/research/code/toolkit)`, intermediate artifacts can be found at `/home/darwinsenior/workspace/research/code/toolkit/target`

Caused by:
  Could not compile `image`.

To learn more, run the command again with --verbose.
```

**Comment by Mark-Simulacrum** [comment] 2017-04-30 19:20
This is a duplicate of #41604.

**Closed by Mark-Simulacrum** 2017-04-30 19:20 UTC
