### ISSUE TITLE
std::os::UnixListener has no support for Linux Abstract Namespace

### ISSUE THREAD

**Issue by HossainAdnan** [rust-lang/rust#65298] opened 2019-10-11 05:25 UTC
Currently `std::os::unix::net::UnixListener` does not seem to support the [Linux Abstract Namespace](http://blog.eduardofleury.com/archives/2007/09/13). I'm not familiar with the process of a feature request in the standard library so I haven't made a issue in the github repo yet.

Reproduce with:
```rust
fn main() {
    let addr_name = "\0/tmp/app.uniq.sock";

    match std::os::unix::net::UnixListener::bind(addr_name) {
        Ok(_) => {
            println!("Unique instance");
            loop {}
        }
        Err(e) => {
            match e.kind()  {
                std::io::ErrorKind::AddrInUse => {
                    println!("Duplicate instance");
                }
                _ => {
                    panic!("{:?}", e);
                }
            }
        }
    }
}
```
Compiler message:
> 
> $ cargo run
>    Compiling events v0.1.0 (/home/user0/proj/events)
>     Finished dev [unoptimized + debuginfo] target(s) in 0.18s
>      Running `target/debug/events`
> thread 'main' panicked at 'Custom { kind: InvalidInput, error: "paths may not contain interior null bytes" }', src
> /main.rs:15:21
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I believe Rust has the capability to allow interior null bytes in Linux with conditional compilation. And there are already a number of Linux-specific code in the standard. Currently the `nix` already crate [supports this](https://docs.rs/nix/0.15.0/nix/sys/socket/struct.UnixAddr.html#method.new_abstract).

Linux abstract namespace is a well-known feature, and it allows users to create sockets that automatically closes itself and avoids name collision with the file system. Section 57.6 in The [Linux Programming Interface book](https://www.nostarch.com/tlpi) explains its benefits in great detail.

Languages that already support this: 
D: https://dlang.org/phobos/std_socket.html (See the UnixAddress Class)
Go: https://golang-examples.tumblr.com/post/92025745979/pitfall-of-abstract-unix-domain-socket-address-in 
https://twitter.com/thatcks/status/633358601864769537
Python: https://docs.python.org/3/library/socket.html#socket-families

**Comment by sfackler** [comment] 2019-10-11 11:14
Duplicate of #42048.

**Closed by sfackler** 2019-10-11 11:14 UTC
Labels: C-feature-request, O-linux, T-libs
