### ISSUE TITLE
Can't "use" in macro without conflicts

### ISSUE THREAD

**Issue by tamird** [rust-lang/rust#44468] opened 2017-09-09 21:26 UTC
Consider a macro-only crate that wants its consumers to not have to link it (context in https://github.com/rust-lang-nursery/bitflags/pull/118), so it employs code like:
```rust
#[cfg(not(no_link))]
#[doc(hidden)]
pub extern crate core as _core;

macro_rules! foo {
    (
        ...
    ) => {
        #[cfg(no_link)]
        use ::core::fmt;

        #[cfg(not(no_link))]
        use $crate::_core::fmt;

        impl fmt::Debug for $... {
    }
}
```

Unfortunately, these use declarations "leak" into the type namespace and collide with multiple invocations of the macro.
```
error[E0252]: the name `fmt` is defined multiple times
   --> src/lib.rs:368:13
    |
368 |           use $crate::_core::fmt;
    |               ------------------
    |               |
    |               `fmt` reimported here
    |               previous import of the module `fmt` here
```

Possibly a duplicate, but I couldn't find another issue describing this. Previously discussed on the forum:
https://users.rust-lang.org/t/scoping-use-declaration-inside-macro/11854
https://users.rust-lang.org/t/how-to-import-in-a-macro-without-conflicting/12785

**Comment by petrochenkov** [comment] 2017-09-09 22:02
This is an expected behavior for `macro_rules` which provide hygiene only for local variables (and labels).
The rules are changed in macros 2.0 (`macro`), which provide hygiene for items as well, but this is very unlikely to be backported to `macro_rules`.

**Comment by Mark-Simulacrum** [comment] 2017-09-09 23:41
I believe it's expected that macro_rules crates won't use `use`. Since it seems that this is expected behavior, closing as not a bug.

**Closed by Mark-Simulacrum** 2017-09-09 23:41 UTC
