### ISSUE TITLE
Associated type declaration position in the source code of the trait implementation affects compilation

### ISSUE THREAD

**Issue by pavel-v-chernykh** [rust-lang/rust#29318] opened 2015-10-26 10:02 UTC
Looks like associated type declaration position in the source code of the trait implementation affects parsing process during compilation.

I tried this code:

```rust
fn main() {}

trait MyTrait {
    type AssocType;
    fn my_method();
}

struct MyStruct;

impl MyTrait for MyStruct {
    type AssocType = u32;

    #![allow(unused_variables)] // error: an inner attribute is not permitted in this context
    fn my_method() {}
}
```

I expected to see successful compilation.
Instead, this happened:
```
src/main.rs:13:7: 13:8 error: an inner attribute is not permitted in this context
src/main.rs:13     #![allow(unused_variables)]
                     ^
src/main.rs:13:7: 13:8 help: place inner attribute at the top of the module or block
error: aborting due to previous error
```

When I rearrange trait items in the implementation compilation passes successfully.

```rust
fn main() {}

trait MyTrait {
    type AssocType;
    fn my_method();
}

struct MyStruct;

impl MyTrait for MyStruct {
    #![allow(unused_variables)]
    fn my_method() {}
    type AssocType = u32;
}
```

## Meta
```
cargo --version                                                                                                                                                          
cargo 0.6.0-nightly (e1ed995 2015-10-22)
```
```
rustc --version --verbose
rustc 1.5.0-nightly (0be1bcd06 2015-10-24)
binary: rustc
commit-hash: 0be1bcd06a969987dde8da35199f413237ed0c0c
commit-date: 2015-10-24
host: x86_64-apple-darwin
release: 1.5.0-nightly
```

Looks like other versions (stable and beta) behave the same way

**Comment by apasel422** [comment] 2015-10-26 11:03
This is actually the intended behavior. The syntax `#![some_attribute]` (note the exclamation point) causes the attribute to be applied to the containing item (in this case, the impl). Such attributes can only be used before any inner items are declared, which is why your second example works but not your first.

Assuming your intention is to declare that unused variables are allowed in the `my_method` method, you should use:

```rust
impl MyTrait for MyStruct {
    #[allow(unused_variables)]
    fn my_method() {}
    type AssocType = u32;
}
```

or

```rust
impl MyTrait for MyStruct {
    type AssocType = u32;
    #[allow(unused_variables)]
    fn my_method() {}
}
```

Note the absence of the exclamation point.

**Comment by apasel422** [comment] 2015-10-26 11:56
By the way, the help note in the error message you provided helps clarify the problem: moving the inner attribute to the top of the block in your second example causes compilation to succeed. See also https://doc.rust-lang.org/stable/book/attributes.html.

Closing, but thanks for the report!

**Closed by apasel422** 2015-10-26 11:56 UTC

**Comment by pavel-v-chernykh** [comment] 2015-10-26 12:10
@apasel422, thanks for the explanation. I've finally understood the difference between inner and outer attributes. Hope this ticket will help someone too.
