### ISSUE TITLE
align_of u128 is 8

### ISSUE THREAD

**Issue by spacejam** [rust-lang/rust#47129] opened 2018-01-02 15:21 UTC
uname: `x86_64 GNU/Linux`

Causes things like [`CMPXCHG16B`](http://www.felixcloutier.com/x86/CMPXCHG8B:CMPXCHG16B.html) to segfault.

https://play.rust-lang.org/?gist=2c9d71615fe1839d3368b0a4364af9cd&version=nightly

P.S. @aweinstock314 it works _sometimes_ :D

**Comment by rkruppe** [comment] 2018-01-02 16:40
For comparison, `u64` is also not naturally aligned on (most? some?) 32 bit platforms. I don't see a strong reason to increase the alignment for {i,u}128 if the only use cases for 16 byte alignment are obscure instructions accessed via intrinsics and inline assembly. Niche use cases that need higher alignment can and should use `repr(align(N))`.

**Comment by eddyb** [comment] 2018-01-02 17:30
cc @alexcrichton @nagisa Can we just close this? As per my previous comment, it's not a bug IMO.

**Comment by rkruppe** [comment] 2018-01-02 17:37
> might not even be supported by LLVM.

Under-aligned loads and stores, at least, must be supported (e.g., for `repr(packed)`). But otherwise you're completely right.

**Comment by eddyb** [comment] 2018-01-02 17:48
@rkruppe I mean changing the alignment in the data layout, in order to still use LLVM's `i128`.

**Comment by nagisa** [comment] 2018-01-02 20:50
I feel like we should close, yeah. The alignment here is dictated by the platform, not our whim, although it is in our power to do at least stack `alloca`s with increased alignment, but I feel like that should be left up to user.

**Closed by nagisa** 2018-01-02 20:50 UTC
Labels: C-enhancement
