### ISSUE TITLE
Internal Compiler Error in CTFE engine

### ISSUE THREAD

**Issue by arturoc** [rust-lang/rust#71709] opened 2020-04-30 14:08 UTC
```
thread 'rustc' panicked at 'places should be checked on creation: InterpErrorInfo { kind: can't access mutable globals in ConstProp, backtrace: None }', src/librustc_mir/interpret/operand.rs:237:25
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1532
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: rustc_mir::interpret::operand::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::try_read_immediate
  16: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::eval_rvalue_into_place
  17: <rustc_mir::transform::const_prop::ConstPropagator as rustc_middle::mir::visit::MutVisitor>::visit_statement
  18: <rustc_mir::transform::const_prop::ConstPropagator as rustc_middle::mir::visit::MutVisitor>::visit_body
  19: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  20: rustc_mir::transform::run_passes
  21: rustc_mir::transform::run_optimization_passes
  22: rustc_mir::transform::optimized_mir
  23: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_query_system::query::plumbing::get_query
  26: rustc_mir::monomorphize::collector::collect_items_rec
  27: rustc_mir::monomorphize::collector::collect_items_rec
  28: rustc_mir::monomorphize::collector::collect_items_rec
  29: rustc_mir::monomorphize::collector::collect_items_rec
  30: rustc_mir::monomorphize::collector::collect_items_rec
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_mir::monomorphize::collector::collect_items_rec
  33: rustc_mir::monomorphize::collector::collect_items_rec
  34: rustc_session::utils::<impl rustc_session::session::Session>::time
  35: rustc_mir::monomorphize::collector::collect_crate_mono_items
  36: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  37: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  38: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  39: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  40: rustc_query_system::query::plumbing::get_query
  41: rustc_codegen_ssa::base::codegen_crate
  42: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  43: rustc_interface::passes::start_codegen
  44: rustc_middle::ty::context::tls::enter_global
  45: rustc_interface::queries::Queries::ongoing_codegen
  46: rustc_interface::interface::run_compiler_in_existing_thread_pool
  47: scoped_tls::ScopedKey<T>::set
  48: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (fa51f810e 2020-04-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C bitcode-in-rlib=no -C codegen-units=16 -C debuginfo=2 -C incremental -C link-arg=-fuse-ld=lld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `window::glfw_window::EventsPoll::new`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

The specified method, EventsPoll::new looks like:

```
static mut GLFW: Option<glfw::Glfw> = None;
pub fn new() -> Result<EventsPoll>{
        //TODO: Give the option to choose FAIL / LOG?
        let glfw = unsafe{ if let Some(glfw) = GLFW {
            glfw
        }else{
            let glfw = glfw::init(glfw::LOG_ERRORS)
                .map_err(|e| util::Error::with_cause("Error initializing glfw", e))?;
            GLFW = Some(glfw);
            glfw
        }};

        Ok(EventsPoll( Arc::new( RwLock::new(EventsPollData{
            glfw,
            should_close: 1,
        }))))
}
```

might be related with the static mut?, but haven't tried to replicate it on a smaller example, will report back if i do so

**Comment by jonas-schievink** [comment] 2020-04-30 20:45
cc @wesleywiser @felix91gr 

Would be good to find out if this was caused by https://github.com/rust-lang/rust/pull/71518, and to find an MCVE, so:

@rustbot ping cleanup

**Comment by felix91gr** [comment] 2020-04-30 20:56
Imma try to bisect this, it's as good an opportunity as any to learn about it!

**Comment by wesleywiser** [comment] 2020-04-30 21:10
@felix91gr here's a minimal example that is self-contained and shows the issue:

```rust
use std::sync::{Arc, RwLock};

#[derive(Copy, Clone)]
pub struct Glfw;

fn fun_call<T>(val: T) -> T { val }

static mut GLFW: Option<Glfw> = None;
pub fn new() -> Result<Arc<RwLock<Glfw>>, Box<dyn std::error::Error>> {
    //TODO: Give the option to choose FAIL / LOG?
    let glfw = unsafe { if let Some(glfw) = GLFW {
        glfw
    } else {
        let glfw = fun_call(Glfw);
        GLFW = Some(glfw);
        glfw
    }};

    Ok(Arc::new(RwLock::new(glfw)))
}
```

**Comment by felix91gr** [comment] 2020-04-30 21:22
Bisect shows the ICE was introduced **between the nightlies of the 26th (no ICE) and the 27th (ICE is present)**.

My pc is trying to find the particular commit still, but if that takes too long (like if it has to compile `rustc` (I have no idea, this is my first time bisecting)) I'll leave it to people with beefier computers :3

That said, @jonas-schievink I think you can at least rest assured-ish because our PR was merged on the 29th (according to Github).

**Comment by LeSeulArtichaut** [comment] 2020-04-30 21:22
Minimized a bit further:

```rust
#[derive(Copy, Clone)]
pub struct Glfw;

static mut GLFW: Option<Glfw> = None;
pub fn new() -> Glfw {
    unsafe { if let Some(glfw) = GLFW {
        return glfw;
    } else {
        todo!()
    }};
}
```

**Comment by felix91gr** [comment] 2020-04-30 21:22
Wait, bisect just finished. :laughing: 

---

# Regression found in the compiler

searched nightlies: from nightly-2020-04-26 to nightly-2020-04-28
regressed nightly: nightly-2020-04-27
searched commits: from https://github.com/rust-lang/rust/commit/0862458dad90a0d80827e22e3f86e33add6d847c to https://github.com/rust-lang/rust/commit/e83f7563495dbe2629b0cbc738afb0808c4482e1
regressed commit: https://github.com/rust-lang/rust/commit/b592b37fa31c0d81ca23fea9fe7998c3f0f4bd0b
source code: URL OF A REPOSITORY THAT REPRODUCES THE ERROR

## Instructions

Please give the steps for how to build your repository (platform, system dependencies, etc.)
## Error

<details><summary>COLLAPSIBLE ERROR STACKTRACE</summary>
<p>

```bash
Paste the error the compiler is giving
```

</p></details>

**Comment by felix91gr** [comment] 2020-04-30 21:23
(working on the stack trace)

**Comment by LeSeulArtichaut** [comment] 2020-04-30 21:24
@felix91gr Use the [`cargo-bisect-rustc`](https://rustc-dev-guide.rust-lang.org/ice-breaker/cleanup-crew.html#cargo-bisect-rustc) tool, which fetches the artifacts generated by @bors when testing a PR. Your CPU will be way happier :D

**Comment by felix91gr** [comment] 2020-04-30 21:25
> @felix91gr Use the [`cargo-bisect-rustc`](https://rustc-dev-guide.rust-lang.org/ice-breaker/cleanup-crew.html#cargo-bisect-rustc) tool, which fetches the artifacts generated by @bors when testing a PR. Your CPU will be way happier :D

Yaaas that's precisely what I used. It's sooooo goooooood :sparkles:

**Comment by LeSeulArtichaut** [comment] 2020-04-30 21:28
(I haven't been able to minimize since my last comment, so I think it is now minimal)

**Comment by felix91gr** [comment] 2020-04-30 21:31
Awesome. I'll bisect again with that one. For now, I've added the full backtrace taken from today's nightly to the bisect report. Do you know how I can compile using a specific rustc's commit? (I just did `rustup update` and used `cargo +nightly build`, which used today's nightly.

**Comment by LeSeulArtichaut** [comment] 2020-04-30 21:34
@felix91gr Now we know which PR regressed (#71566). It's a rollup of multiple PRs, so we'll need to guess which one is the culprit using the power of deduction :D

Here I'm pretty sure this has been caused by #71140, cc @oli-obk

**Comment by felix91gr** [comment] 2020-04-30 21:40
Kay, I'll leave it to Oli then. He knows way more than I do about static initialization soundness :D also, it's (apparently) his PR.

**I've done one last test:** did bisect with your minimal counterexample, which ICE'd on the same commit. I've edited the bisection report to have your `mcve` and its backtrace :3 @jonas-schievink

**Comment by pnkfelix** [comment] 2020-05-01 14:10
> @felix91gr Now we know which PR regressed (#71566). It's a rollup of multiple PRs, so we'll need to guess which one is the culprit using the power of deduction :D

I cannot tell if you are being facetious here, but there *is* the option of bisecting  over the individual PR's in the rollup itself, e.g. via `git bisect` directly on a local rust checkout. It is unfortunate that we don't have a way to do that mechanically within `cargo-bisect-rustc` itself (which would be a huge undertaking)

**Comment by wesleywiser** [comment] 2020-05-01 14:25
From some local testing, I can confirm that reverting af44cdf04fddf4d18efee49c0c683cb4bbce71fa from #71140 fixes the ICE. 

cc @oli-obk

**Comment by pnkfelix** [comment] 2020-05-01 14:32
@wesleywiser yeah I think @oli-obk posted PR #71751 which essentially reverted af44cdf by moving the check elsewhere (so that we still get the fix that #71140 was trying to land).

Its just waiting review; I looked at it briefly but I'm not an expert on that code so I'm going to wait for @RalfJung to look at it.

**Comment by LeSeulArtichaut** [comment] 2020-05-01 15:35
> I cannot tell if you are being facetious here, but there is the option of bisecting over the individual PR's in the rollup itself

Right, that sentence was unclear, sorry about that. I just wrote something quickly, to tell `@felix91gr` that they didn't need to bisect every PR in the rollup, that would have been a waste of time.

**Comment by felix91gr** [comment] 2020-05-01 18:09
> > I cannot tell if you are being facetious here, but there is the option of bisecting over the individual PR's in the rollup itself
> 
> Right, that sentence was unclear, sorry about that. I just wrote something quickly, to tell `@felix91gr` that they didn't need to bisect every PR in the rollup, that would have been a waste of time.

@LeSeulArtichaut it's completely fine! I got your friendly tone when you posted it. The `:D` was very helpful in that regard :rainbow: :slightly_smiling_face:

**Closed** 2020-05-04 12:58 UTC
Labels: A-const-eval, A-mir-opt, C-bug, I-ICE, I-prioritize, ICEBreaker-Cleanup-Crew, T-compiler, regression-from-stable-to-nightly
