### ISSUE TITLE
rustup: error: invalid sha256.

### ISSUE THREAD

**Issue by javalama** [rust-lang/rust#21293] opened 2015-01-17 10:18 UTC
I get

rustup: error: invalid sha256.

when trying to install on OS X

**Comment by brson** [comment] 2015-01-17 17:22
This seems to be intermittent, and happen when the cdn is syncing to s3. cc https://github.com/rust-lang/rust/issues/21239

**Comment by javalama** [comment] 2015-01-17 19:03
How intermittent? I've been getting the error for days.

**Comment by Gankro** [comment] 2015-01-21 20:24
Closing as effectively a dupe of #21239

**Closed by Gankro** 2015-01-21 20:24 UTC
Labels: A-infrastructure
