### ISSUE TITLE
dep-info for link is wrong when --emit is given a path.

### ISSUE THREAD

**Issue by TheDreadedAndy** [rust-lang/rust#102166] opened 2022-09-23 03:08 UTC
When compiling with `--emit link=path,dep-info`, the resulting dependency file is wrong.

Instead of containing the given path for `link`, the dependency file will contain the platform dependent default name for that link option. For example, I passed rustc the flags `--crate-type proc-macro --emit link=rust/build/output/libforward.so,dep-info=rust/build/output/forward.d`, and the resulting dependency file contained `libforward.so: rust/proc-macro/forward/forward.rs` instead of `rust/build/output/libforward.so: rust/proc-macro-forward/forward.rs`.

I observed this issue with both the rlib and proc-macro crate types on nightly 1.64.0.

Similar issue: #68839

**Comment by Enselic** [comment] 2024-07-10 19:13
Triage: Can you still reproduce since https://github.com/rust-lang/rust/issues/68839 was fixed?

**Comment by jieyouxu** [comment] 2024-11-12 10:51
Triage: closing due to missing recent repro, please feel free to reopen if this is still a problem.

**Closed by jieyouxu** 2024-11-12 10:51 UTC
Labels: C-bug, S-needs-repro
