### ISSUE TITLE
found unstable fingerprints for predicates_of(core[3998]::fmt::Debug)/predicates_of(core[3998]::clone::Clone)

### ISSUE THREAD

**Issue by engylemure** [rust-lang/rust#84116] opened 2021-04-12 02:13 UTC
### Code

I was not able to find some way to create a smaller example since I didn't understand the problem itself
the problem was found here https://github.com/engylemure/juniper/tree/rustc_crash/juniper_actix when using 
`cargo run --example actix_server` or `cargo test`, the problem seem to disappear when running the command with the only available feature `cargo run --example actix_server --features subscriptions` (the example don't make any usage of this feature) or `cargo test --features subscriptions` ( has a module with tests related to the feature ), the error itself seems to change depending on some unknown context I've found the errors with the `Clone` and `Debug` traits.

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::clone::Clone): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Sized>)), /home/jordao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/clone.rs:108:18: 108:23 (#0)), (Binder(TraitPredicate(<Self as std::clone::Clone>)), /home/jordao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/clone.rs:108:1: 108:23 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
```

```
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::fmt::Debug): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::fmt::Debug>)), /home/jordao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:550:1: 550:16 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:435:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   6: rustc_ty_utils::ty::param_env
   7: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   8: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   9: rustc_data_structures::stack::ensure_sufficient_stack
  10: rustc_query_system::query::plumbing::get_query_impl
  11: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::param_env
  12: <rustc_lint::noop_method_call::NoopMethodCall as rustc_lint::passes::LateLintPass>::check_expr
  13: rustc_hir::intravisit::walk_expr
  14: rustc_hir::intravisit::walk_expr
  15: rustc_hir::intravisit::walk_expr
  16: rustc_hir::intravisit::walk_expr
  17: rustc_hir::intravisit::walk_expr
  18: rustc_hir::intravisit::walk_block
  19: rustc_hir::intravisit::walk_expr
  20: rustc_hir::intravisit::walk_arm
  21: rustc_hir::intravisit::walk_expr
  22: rustc_hir::intravisit::walk_block
  23: rustc_hir::intravisit::walk_expr
  24: rustc_hir::intravisit::walk_stmt
  25: rustc_hir::intravisit::walk_block
  26: rustc_hir::intravisit::walk_expr
  27: rustc_hir::intravisit::walk_arm
  28: rustc_hir::intravisit::walk_expr
  29: rustc_hir::intravisit::walk_expr
  30: rustc_hir::intravisit::walk_stmt
  31: rustc_hir::intravisit::walk_block
  32: rustc_hir::intravisit::walk_expr
  33: rustc_hir::intravisit::walk_body
  34: <rustc_lint::late::LateContextAndPass<T> as rustc_hir::intravisit::Visitor>::visit_fn
  35: rustc_hir::intravisit::walk_impl_item
  36: rustc_hir::intravisit::Visitor::visit_nested_impl_item
  37: rustc_hir::intravisit::walk_item
  38: rustc_hir::intravisit::Visitor::visit_nested_item
  39: rustc_hir::intravisit::walk_item
  40: rustc_hir::intravisit::Visitor::visit_nested_item
  41: rustc_hir::intravisit::walk_item
  42: rustc_hir::intravisit::Visitor::visit_nested_item
  43: rustc_hir::intravisit::walk_crate
  44: rustc_lint::late::late_lint_crate
  45: rustc_data_structures::sync::join
  46: std::panic::catch_unwind
  47: rustc_session::utils::<impl rustc_session::session::Session>::time
  48: rustc_interface::passes::analysis
  49: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  50: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  51: rustc_data_structures::stack::ensure_sufficient_stack
  52: rustc_query_system::query::plumbing::force_query_with_job
  53: rustc_query_system::query::plumbing::get_query_impl
  54: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  55: rustc_interface::passes::QueryContext::enter
  56: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  57: rustc_span::with_source_map
  58: rustc_interface::interface::create_compiler_and_run
  59: scoped_tls::ScopedKey<T>::set
```

</p>

<p>

```
stack backtrace:
   0:     0x7fac7e5a4f80 - std::backtrace_rs::backtrace::libunwind::trace::h4dee703919bfd40a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fac7e5a4f80 - std::backtrace_rs::backtrace::trace_unsynchronized::h457e839f1a563e20
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fac7e5a4f80 - std::sys_common::backtrace::_print_fmt::h86a55fb30f8393c8
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fac7e5a4f80 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b3d6cac46d277e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fac7e6138df - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/fmt/mod.rs:1092:17
   5:     0x7fac7e599505 - std::io::Write::write_fmt::h6010cfbb4726588b
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/io/mod.rs:1578:15
   6:     0x7fac7e5a8cbb - std::sys_common::backtrace::_print::h79b4f9652330cc9d
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fac7e5a8cbb - std::sys_common::backtrace::print::h330bb326a76af8cf
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fac7e5a8cbb - std::panicking::default_hook::{{closure}}::heb6a42a7d50a472e
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:208:50
   9:     0x7fac7e5a8783 - std::panicking::default_hook::h17e521ba6d68d6e1
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:225:9
  10:     0x7fac7ed7af2b - rustc_driver::report_ice::ha40982d59fc75b99
  11:     0x7fac6bf8dcf3 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h584c93a09b3d2ec7
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1560:9
  12:     0x7fac6c002606 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h28db21f88ef96537
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7fac7e5a93d0 - std::panicking::rust_panic_with_hook::h70db735e3a6e70cb
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:595:17
  14:     0x7fac7e5a8fa7 - std::panicking::begin_panic_handler::{{closure}}::h777c71c8e5a7e25c
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:497:13
  15:     0x7fac7e5a543c - std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7fac7e5a8f09 - rust_begin_unwind
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
  17:     0x7fac7e56e3fb - std::panicking::begin_panic_fmt::h0b6b6d9d830486ef
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:435:5
  18:     0x7fac80dc01b8 - rustc_query_system::query::plumbing::incremental_verify_ich::h6b4efb8c1a8c93e3
  19:     0x7fac80dca83b - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h77ead32960e2aee5
  20:     0x7fac802da0b5 - rustc_query_system::query::plumbing::get_query_impl::h5afdd6968b77ec12
  21:     0x7fac80342879 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of::h32dac6f2fa98c3a6
  22:     0x7fac809556ce - rustc_middle::ty::generics::GenericPredicates::instantiate_identity_into::h1196dfaaf84c8eee
  23:     0x7fac809553f8 - rustc_middle::ty::generics::GenericPredicates::instantiate_identity::h5f04b06c20f64a98
  24:     0x7fac811e297e - rustc_trait_selection::traits::object_safety::generics_require_sized_self::he6e18d24160a0f34
  25:     0x7fac811ea5e6 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hbcebb92b37a5cccc
  26:     0x7fac811f047c - <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::h5e335734b9352829
  27:     0x7fac811f7868 - <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend::hdd350753bf4b480c
  28:     0x7fac7fc80928 - rustc_arena::cold_path::h9b250ed5a3bc85f2
  29:     0x7fac811f9fe9 - rustc_middle::arena::Arena::alloc_from_iter::h42dcda90dff02f83
  30:     0x7fac811ee398 - rustc_trait_selection::traits::vtable_methods::hafa9f7ab181ce4bb
  31:     0x7fac80dd73a2 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::vtable_methods>::compute::h1b6ee8a26472eef2
  32:     0x7fac7f52a6b4 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h50a95aa7545156f0
  33:     0x7fac7f46d16c - rustc_query_system::dep_graph::graph::DepGraph<K>::with_ignore::h55d51e401d6e8419
  34:     0x7fac7f30aaeb - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::hd45d7d37cbab87fc
  35:     0x7fac7f548289 - rustc_data_structures::stack::ensure_sufficient_stack::h063b7583e48dbf58
  36:     0x7fac80d7a27e - rustc_query_system::query::plumbing::get_query_impl::hd9c49281a7a6a306
  37:     0x7fac80e4b0b9 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::vtable_methods::h05aff39f4e16928d
  38:     0x7fac804df813 - <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_rvalue::he80e5002ec5d5ad0
  39:     0x7fac804e32dc - rustc_mir::monomorphize::collector::collect_neighbours::hc21fc044f9447dab
  40:     0x7fac804dd1ec - rustc_mir::monomorphize::collector::collect_items_rec::h2375063f753630bc
  41:     0x7fac8102f673 - rustc_session::utils::<impl rustc_session::session::Session>::time::ha8841ca60bb1c740
  42:     0x7fac80f99f10 - rustc_mir::monomorphize::collector::collect_crate_mono_items::h94968778b7c20b54
  43:     0x7fac8061604f - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::h1743864421ee0df1
  44:     0x7fac80dd94e6 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::collect_and_partition_mono_items>::compute::h23e28fb9afdb8334
  45:     0x7fac7f529b62 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h463a3b729f161942
  46:     0x7fac80e61869 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h43645b10a8941ec7
  47:     0x7fac80ebf509 - rustc_data_structures::stack::ensure_sufficient_stack::h67b1fbe3ddcb697a
  48:     0x7fac80d92206 - rustc_query_system::query::plumbing::force_query_with_job::h08bdd5324049fe39
  49:     0x7fac7f2af625 - rustc_query_system::query::plumbing::force_query_impl::h58fff661780cdc7f
  50:     0x7fac7f283f6b - rustc_query_system::query::plumbing::force_query::h0eb10c725d601a39
  51:     0x7fac7f38f34a - rustc_query_impl::query_callbacks::collect_and_partition_mono_items::force_from_dep_node::h57d556edfa2b5425
  52:     0x7fac8035dad8 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::hc25922935726b14d
  53:     0x7fac80ec82e0 - rustc_data_structures::stack::ensure_sufficient_stack::hc50a60b7b9896586
  54:     0x7fac80d5938a - rustc_query_system::query::plumbing::get_query_impl::h633d09d2ebd606f7
  55:     0x7fac80e4d9bf - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::exported_symbols::h8f572c6518978285
  56:     0x7fac806562b3 - rustc_metadata::rmeta::encoder::EncodeContext::encode_crate_root::h7732508c6d637392
  57:     0x7fac81077464 - rustc_metadata::rmeta::encoder::encode_metadata_impl::h29556fc2914280c5
  58:     0x7fac8108e9f1 - rustc_data_structures::sync::join::h1abd71e9530a4f22
  59:     0x7fac810834ae - rustc_metadata::rmeta::decoder::cstore_impl::<impl rustc_middle::middle::cstore::CrateStore for rustc_metadata::creader::CStore>::encode_metadata::h60ba4f4dae49ceab
  60:     0x7fac81294b49 - rustc_middle::ty::context::TyCtxt::encode_metadata::h4a367306415477b3
  61:     0x7fac809f34d3 - rustc_interface::passes::QueryContext::enter::hd4dee32b33d2c6db
  62:     0x7fac809fa686 - rustc_interface::queries::Queries::ongoing_codegen::ha121babd46d82e91
  63:     0x7fac809ae456 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h2731ac3c02105c7c
  64:     0x7fac809e3071 - rustc_span::with_source_map::h94d38a1c3089ae35
  65:     0x7fac809af3ee - rustc_interface::interface::create_compiler_and_run::h2bc2789fb7dc8d5b
  66:     0x7fac809a9b78 - scoped_tls::ScopedKey<T>::set::hc4c30e2561747f9c
  67:     0x7fac809af7c4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h904e8f4f3fa6a302
  68:     0x7fac809d10f5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he1a228660be11f81
  69:     0x7fac7e5b8cf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7f7bdfc757a1add0
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
  70:     0x7fac7e5b8cf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha294ad0fb99e9b3a
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/alloc/src/boxed.rs:1546:9
  71:     0x7fac7e5b8cf3 - std::sys::unix::thread::Thread::new::thread_start::h4614854ae73cd6b0
                               at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/sys/unix/thread.rs:71:17
  72:     0x7fac7e4c3299 - start_thread
  73:     0x7fac7e3d8053 - clone
  74:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

</p>
</details>

**Comment by messense** [comment] 2021-05-08 06:32
The same error with Rust 1.52 running under [cargo-tarpaulin](https://github.com/xd009642/tarpaulin)

```bash
/usr/share/rust/.cargo/bin/cargo tarpaulin --out Xml --all
May 08 06:25:46.057  INFO cargo_tarpaulin: Running Tarpaulin
May 08 06:25:46.057  INFO cargo_tarpaulin: Building project
May 08 06:25:46.057  INFO cargo_tarpaulin::cargo: Cleaning project
...
thread 'rustc' panicked at 'found unstable fingerprints for exported_symbols(bstr[a229]): [(NonGeneric(DefId(19:1743 ~ bstr[a229]::unicode::fsm::grapheme_break_fwd::{impl#0}::deref)), Rust), (NonGeneric(DefId(19:1753 ~ bstr[a229]::unicode::fsm::grapheme_break_fwd::{impl#1}::initialize)), Rust), (NonGeneric(DefId(19:1760 ~ bstr[a229]::unicode::fsm::grapheme_break_rev::{impl#0}::deref)), Rust), (NonGeneric(DefId(19:1770 ~ bstr[a229]::unicode::fsm::grapheme_break_rev::{impl#1}::initialize)), Rust), (NonGeneric(DefId(19:1794 ~ bstr[a229]::unicode::fsm::sentence_break_fwd::{impl#0}::deref)), Rust), (NonGeneric(DefId(19:1804 ~ bstr[a229]::unicode::fsm::sentence_break_fwd::{impl#1}::initialize)), Rust), (Generic(DefId(22:139 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_anchored), [&[u16], u16]), Rust), (Generic(DefId(22:139 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_anchored), [&[u8], u8]), Rust), (Generic(DefId(22:135 ~ regex_automata[88e7]::dense_imp::{impl#7}::start_state), [&[u16], u16]), Rust), (Generic(DefId(22:135 ~ regex_automata[88e7]::dense_imp::{impl#7}::start_state), [&[u8], u8]), Rust), (Generic(DefId(22:137 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_dead_state), [&[u16], u16]), Rust), (Generic(DefId(22:137 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_dead_state), [&[u8], u8]), Rust), (Generic(DefId(22:136 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_match_state), [&[u16], u16]), Rust), (Generic(DefId(22:136 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_match_state), [&[u8], u8]), Rust), (Generic(DefId(22:141 ~ regex_automata[88e7]::dense_imp::{impl#7}::next_state_unchecked), [&[u16], u16]), Rust), (Generic(DefId(22:141 ~ regex_automata[88e7]::dense_imp::{impl#7}::next_state_unchecked), [&[u8], u8]), Rust), (Generic(DefId(22:138 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_match_or_dead_state), [&[u16], u16]), Rust), (Generic(DefId(22:138 ~ regex_automata[88e7]::dense_imp::{impl#7}::is_match_or_dead_state), [&[u8], u8]), Rust), (NonGeneric(DefId(19:1777 ~ bstr[a229]::unicode::fsm::regional_indicator_rev::{impl#0}::deref)), Rust), (NonGeneric(DefId(19:1787 ~ bstr[a229]::unicode::fsm::regional_indicator_rev::{impl#1}::initialize)), Rust), (Generic(DefId(2:9271 ~ core[b0ed]::slice::index::{impl#5}::get_unchecked_mut), [u8]), Rust), (Generic(DefId(2:9273 ~ core[b0ed]::slice::index::{impl#5}::index_mut), [u8]), Rust), (Generic(DefId(5:6208 ~ alloc[9520]::vec::drain::{impl#6}::next_back), [ReErased, u8, std::alloc::Global]), Rust), (Generic(DefId(5:6209 ~ alloc[9520]::vec::drain::{impl#6}::next_back::{closure#0}), [ReErased, u8, std::alloc::Global, i32, extern "rust-call" fn((&u8,)) -> u8, ()]), Rust), (NonGeneric(DefId(19:1828 ~ bstr[a229]::unicode::fsm::whitespace_anchored_fwd::{impl#0}::deref)), Rust), (NonGeneric(DefId(19:1838 ~ bstr[a229]::unicode::fsm::whitespace_anchored_fwd::{impl#1}::initialize)), Rust), (NonGeneric(DefId(19:1845 ~ bstr[a229]::unicode::fsm::whitespace_anchored_rev::{impl#0}::deref)), Rust), (NonGeneric(DefId(19:1855 ~ bstr[a229]::unicode::fsm::whitespace_anchored_rev::{impl#1}::initialize)), Rust), (Generic(DefId(2:9290 ~ core[b0ed]::slice::index::{impl#7}::index), [u8]), Rust), (Generic(DefId(2:9291 ~ core[b0ed]::slice::index::{impl#7}::index_mut), [u8]), Rust), (Generic(DefId(2:9299 ~ core[b0ed]::slice::index::{impl#8}::index), [u8]), Rust), (Generic(DefId(2:9300 ~ core[b0ed]::slice::index::{impl#8}::index_mut), [u8]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::sparse_imp::SparseDFA<&[u8], u32>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u32> {<bstr::unicode::fsm::sentence_break_fwd::SENTENCE_BREAK_FWD as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::sparse_imp::SparseDFA<&[u8], u32>>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u32> {<bstr::unicode::fsm::sentence_break_fwd::SENTENCE_BREAK_FWD as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::dense_imp::DenseDFA<&[u8], u8>, fn() -> regex_automata::dense_imp::DenseDFA<&'static [u8], u8> {<bstr::unicode::fsm::whitespace_anchored_fwd::WHITESPACE_ANCHORED_FWD as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::dense_imp::DenseDFA<&[u8], u8>>, fn() -> regex_automata::dense_imp::DenseDFA<&'static [u8], u8> {<bstr::unicode::fsm::whitespace_anchored_fwd::WHITESPACE_ANCHORED_FWD as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::sparse_imp::SparseDFA<&[u8], u16>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u16> {<bstr::unicode::fsm::grapheme_break_fwd::GRAPHEME_BREAK_FWD as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::sparse_imp::SparseDFA<&[u8], u16>>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u16> {<bstr::unicode::fsm::grapheme_break_fwd::GRAPHEME_BREAK_FWD as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::sparse_imp::SparseDFA<&[u8], u32>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u32> {<bstr::unicode::fsm::word_break_fwd::WORD_BREAK_FWD as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::sparse_imp::SparseDFA<&[u8], u32>>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u32> {<bstr::unicode::fsm::word_break_fwd::WORD_BREAK_FWD as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::dense_imp::DenseDFA<&[u8], u8>, fn() -> regex_automata::dense_imp::DenseDFA<&'static [u8], u8> {<bstr::unicode::fsm::regional_indicator_rev::REGIONAL_INDICATOR_REV as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::dense_imp::DenseDFA<&[u8], u8>>, fn() -> regex_automata::dense_imp::DenseDFA<&'static [u8], u8> {<bstr::unicode::fsm::regional_indicator_rev::REGIONAL_INDICATOR_REV as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::sparse_imp::SparseDFA<&[u8], u16>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u16> {<bstr::unicode::fsm::grapheme_break_rev::GRAPHEME_BREAK_REV as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::sparse_imp::SparseDFA<&[u8], u16>>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u16> {<bstr::unicode::fsm::grapheme_break_rev::GRAPHEME_BREAK_REV as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::dense_imp::DenseDFA<&[u16], u16>, fn() -> regex_automata::dense_imp::DenseDFA<&'static [u16], u16> {<bstr::unicode::fsm::whitespace_anchored_rev::WHITESPACE_ANCHORED_REV as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::dense_imp::DenseDFA<&[u16], u16>>, fn() -> regex_automata::dense_imp::DenseDFA<&'static [u16], u16> {<bstr::unicode::fsm::whitespace_anchored_rev::WHITESPACE_ANCHORED_REV as std::ops::Deref>::deref::__static_ref_initialize})]), Rust), (Generic(DefId(24:30 ~ lazy_static[bac5]::lazy::{impl#0}::get::{closure#0}), [regex_automata::sparse_imp::SparseDFA<&[u8], u16>, fn() -> regex_automata::sparse_imp::SparseDFA<&'static [u8], u16> {<bstr::unicode::fsm::simple_word_fwd::SIMPLE_WORD_FWD as std::ops::Deref>::deref::__static_ref_initialize}, i32, extern "rust-call" fn(()), (&&lazy_static::lazy::Lazy<regex_automata::sparse_imp::SparseDFA<&[u8], u16>>, fn() -> 
...
...
/rustc/88f19c6dab716c6281af7602e30f413e809c5974/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0 (88f19c6da 2021-05-03) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-dead-code -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [exported_symbols] exported_symbols
#1 [upstream_monomorphizations] collecting available upstream monomorphizations `crate0`
end of query stack
```

**Comment by jyn514** [comment] 2021-05-19 09:56
https://github.com/rust-lang/rust/issues/84116#issuecomment-835142754 is tracked by https://github.com/rust-lang/rust/issues/85294. The original issues is a duplicate of https://github.com/rust-lang/rust/issues/83259.

**Closed by jyn514** 2021-05-19 09:56 UTC
Labels: C-bug, I-ICE, T-compiler
