### ISSUE TITLE
Dereference [RefCell] error when [use std::borrow::{Borrow, BorrowMut}]

### ISSUE THREAD

**Issue by herofqy** [rust-lang/rust#81078] opened 2021-01-16 13:24 UTC
### Code

```Rust
use std::rc::Rc;
use std::cell::RefCell;
use std::borrow::{Borrow, BorrowMut};

fn main() {
    let value = Rc::new(RefCell::new(5));
    *value.borrow_mut() += 10;
    println!("{:?}",value);
}
```

### Meta

`rustc --version --verbose`:
```
Rust toolchain version: 1.49.0 (e1884a8e3 2020-12-29) x86_64-pc-windows-msvc
rustup 1.23.1 (3df2264a9 2020-11-30)
cargo 1.49.0 (d00d64df9 2020-12-05)
```

### Error output

```
error[E0368]: binary assignment operation `+=` cannot be applied to type `Rc<RefCell<{integer}>>`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 --> src\main.rs:7:5
  |
7 |     *value.borrow_mut() += 10;
  |     -------------------^^^^^^
  |     |
  |     cannot use `+=` on type `Rc<RefCell<{integer}>>`
```

</p>
</details>

**Comment by SNCPlay42** [comment] 2021-01-16 14:10
Duplicate of #39232

**Closed** 2021-01-16 15:38 UTC
Labels: C-bug, I-ICE, T-compiler
