### ISSUE TITLE
Rustdoc has broken links for enum imports

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#29814] opened 2015-11-13 09:16 UTC
http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/

If you click on the `BuiltinBound` in pub use `self::sty::BuiltinBound::Send as BoundSend;`, you're taken to http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/sty/BuiltinBound/index.html instead of http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/enum.BuiltinBound.html.

Also the `sty` link is broken, probably due to privacy.

**Comment by mitaa** [comment] 2015-12-21 05:12
The problem is that the code formatting the path assumes that all path-segments except the last one are modules, emitting `BuiltinBound/index.html` instead of [`enum.BuiltinBound.html`][1]
https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/format.rs#L347

[1]: http://manishearth.github.io/rust-internals-docs/rustc/middle/ty/sty/enum.BuiltinBound.html

**Comment by mitaa** [comment] 2016-02-13 10:38
The deeper problem is that rustc (`hir::{Path, PathSegment, ..}`) doesn't give enough information (just an ident) about the path-segments to rustdoc so that we can ascertain the item-type necessary for creating the hyperlink.

I'm not sure how this ought to be solved:
* Somehow attaching resolved DefId's within rustc to the path-segments? (metadata bloat?)
* Running resolve within rustdoc and resolving each path-segment? (I've experimented with this some time ago and it *seemed* to be a viable solution, though a bit odd)
* Simply omit these possibly broken links

cc @alexcrichton

**Comment by alexcrichton** [comment] 2016-02-16 17:24
In theory when rustdoc runs we have the entire results of resolve, right? Along those lines I figured the resolution would be *somewhere*...

**Comment by Mark-Simulacrum** [comment] 2017-07-24 18:01
I don't think I can reproduce this today, but since there's not really a minimal example here it's hard to tell. The code below generates a valid link for `A` in `foo::bar::A` but no more than that, which seems to be enough to resolve this issue.

```rust
pub mod foo {
    pub enum Bar {
        A,
        B,
        C,
    }
}

pub use foo::Bar::A as Apple;

pub fn main() {}
```

**Closed by Mark-Simulacrum** 2017-07-24 18:01 UTC
Labels: A-rustdoc, C-bug, T-dev-tools
