### ISSUE TITLE
CARGO_INCREMENTAL=1 crashes `wayland_kbd` @ impls_ty.rs:78 - unexpected region

### ISSUE THREAD

**Issue by fschutt** [rust-lang/rust#45241] opened 2017-10-12 18:55 UTC
### Summary

The compiler panics when compiling `limn_layout` (https://github.com/christolliday/limn) because a dependency (wayland_kbd v0.9.1) panics:

```
/checkout/src/librustc/ich/impls_ty.rs:78: TypeIdHasher: unexpected region ReLateBound(DebruijnIndex { depth: 1 }, "BrEnv")
```

#### rustc version:

```
rustc 1.22.0-nightly (a47c9f870 2017-10-11)
binary: rustc
commit-hash: a47c9f870f13603a06ffe63ab4834fc716912843
commit-date: 2017-10-11
host: x86_64-unknown-linux-gnu
release: 1.22.0-nightly
LLVM version: 4.0
```

#### Full backtrace:

```rust
   Compiling wayland-kbd v0.9.1
error: internal compiler error: /checkout/src/librustc/ich/impls_ty.rs:78: TypeIdHasher: unexpected region ReLateBound(DebruijnIndex { depth: 1 }, BrEnv)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.22.0-nightly (a47c9f870 2017-10-11) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
stack backtrace:
   0:     0x7f402ba7b053 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h60105fb13a6e17c1
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f402ba75780 - std::sys_common::backtrace::_print::hb057308e22b27ba1
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
   2:     0x7f402ba88553 - std::panicking::default_hook::{{closure}}::h8be6f849b5a30341
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7f402ba8825a - std::panicking::default_hook::hbcb97f4d1eaa4b20
                               at /checkout/src/libstd/panicking.rs:391
   4:     0x7f402ba88a17 - std::panicking::rust_panic_with_hook::h73a02241f93cbf38
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7f402713b8b8 - std::panicking::begin_panic::he0504ffbd02c9db0
   6:     0x7f4027159415 - rustc_errors::Handler::bug::h0dedeb3fc1384305
   7:     0x7f402865c190 - rustc::session::opt_span_bug_fmt::{{closure}}::h55cba717e86faf75
   8:     0x7f402865c0a5 - rustc::session::opt_span_bug_fmt::h976cca6684257030
   9:     0x7f402865bd86 - rustc::session::bug_fmt::h733e7c4dc7077b14
  10:     0x7f40285b9936 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::RegionKind>::hash_stable::hc6a6331a59491afd
  11:     0x7f40285b9bcf - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable::h81b35d15fd4ffa63
  12:     0x7f40285b99e2 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::Binder<T>>::hash_stable::h05c4ed0f99b22b76
  13:     0x7f40285b9c04 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable::h81b35d15fd4ffa63
  14:     0x7f4028535fbd - <T as rustc::dep_graph::dep_node::DepNodeParams<'a, 'gcx, 'tcx>>::to_fingerprint::hcfabc2de2ed7bb17
  15:     0x7f4028720125 - rustc::dep_graph::dep_node::DepNode::new::h0194873353fd1be6
  16:     0x7f4028808317 - rustc::ty::maps::<impl rustc::ty::maps::queries::is_sized_raw<'tcx>>::try_get::h218d2f8e87627fd8
  17:     0x7f40288a9b16 - rustc::ty::maps::TyCtxtAt::is_sized_raw::h946f581dc74f2f83
  18:     0x7f40286f0709 - rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::is_sized::he0a6d5e9531b6d3c
  19:     0x7f4029bd5042 - rustc_trans::callee::get_fn::hc27dafcc28f7ba50
  20:     0x7f4029c0cff2 - rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_terminator::ha7f494e599da4990
  21:     0x7f4029c0819c - rustc_trans::mir::trans_mir::h748fe24b84d09cf0
  22:     0x7f4029bc4b4e - rustc_trans::base::trans_instance::h202b404337e1c89c
  23:     0x7f4029bd1131 - rustc_trans::base::compile_codegen_unit::hb0fa82088fdd60ab
  24:     0x7f4028899e45 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force::ha534608d28be5a5e
  25:     0x7f402889b8a1 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get::h53b926ccf3be830e
  26:     0x7f40288adaa3 - rustc::ty::maps::TyCtxtAt::compile_codegen_unit::h3bd8ef20be6de5af
  27:     0x7f40288a54f7 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit::h30a54b621ec4962f
  28:     0x7f4029bc74d3 - rustc_trans::base::trans_crate::haf85c064dc8766ee
  29:     0x7f4029c2d263 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::h5df6a45064f22a73
  30:     0x7f402be30003 - rustc_driver::driver::compile_input::{{closure}}::h78c3764a9b163973
  31:     0x7f402bdb08b7 - rustc::ty::context::TyCtxt::create_and_enter::h4b7ccfc9e0ff61c6
  32:     0x7f402be2dc5b - rustc_driver::driver::compile_input::h224eac3dc4f05da3
  33:     0x7f402be4990e - rustc_driver::run_compiler::haeed4a20a242ccd2
  34:     0x7f402bd68a17 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbdb57a55951ef241
  35:     0x7f402bac2dec - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  36:     0x7f402bda1990 - <F as alloc::boxed::FnBox<A>>::call_box::h21becb19e1f0c98e
  37:     0x7f402ba8741b - std::sys::imp::thread::Thread::new::thread_start::h1a6247f115117cfe
                               at /checkout/src/liballoc/boxed.rs:772
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  38:     0x7f40268ba6d9 - start_thread
  39:     0x7f402b74bd7e - __clone
  40:                0x0 - <unknown>

error: Could not compile `text_layout`.
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: /checkout/src/librustc/ich/impls_ty.rs:78: TypeIdHasher: unexpected region ReLateBound(DebruijnIndex { depth: 1 }, BrEnv)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.22.0-nightly (a47c9f870 2017-10-11) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace
limn
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
stack backtrace:
   0:     0x7f05b2083053 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h60105fb13a6e17c1
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f05b207d780 - std::sys_common::backtrace::_print::hb057308e22b27ba1
                               at /checkout/src/libstd/sys_common/backtrace.rs:69
   2:     0x7f05b2090553 - std::panicking::default_hook::{{closure}}::h8be6f849b5a30341
                               at /checkout/src/libstd/sys_common/backtrace.rs:58
                               at /checkout/src/libstd/panicking.rs:381
   3:     0x7f05b209025a - std::panicking::default_hook::hbcb97f4d1eaa4b20
                               at /checkout/src/libstd/panicking.rs:391
   4:     0x7f05b2090a17 - std::panicking::rust_panic_with_hook::h73a02241f93cbf38
                               at /checkout/src/libstd/panicking.rs:577
   5:     0x7f05ad7438b8 - std::panicking::begin_panic::he0504ffbd02c9db0
   6:     0x7f05ad761415 - rustc_errors::Handler::bug::h0dedeb3fc1384305
   7:     0x7f05aec64190 - rustc::session::opt_span_bug_fmt::{{closure}}::h55cba717e86faf75
   8:     0x7f05aec640a5 - rustc::session::opt_span_bug_fmt::h976cca6684257030
   9:     0x7f05aec63d86 - rustc::session::bug_fmt::h733e7c4dc7077b14
  10:     0x7f05aebc1936 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::RegionKind>::hash_stable::hc6a6331a59491afd
  11:     0x7f05aebc1bcf - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable::h81b35d15fd4ffa63
  12:     0x7f05aebc19e2 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::Binder<T>>::hash_stable::h05c4ed0f99b22b76
  13:     0x7f05aebc1c04 - rustc::ich::impls_ty::<impl rustc_data_structures::stable_hasher::HashStable<rustc::ich::hcx::StableHashingContext<'gcx>> for rustc::ty::sty::TypeVariants<'gcx>>::hash_stable::h81b35d15fd4ffa63
  14:     0x7f05aeb3dfbd - <T as rustc::dep_graph::dep_node::DepNodeParams<'a, 'gcx, 'tcx>>::to_fingerprint::hcfabc2de2ed7bb17
  15:     0x7f05aed28125 - rustc::dep_graph::dep_node::DepNode::new::h0194873353fd1be6
  16:     0x7f05aee10317 - rustc::ty::maps::<impl rustc::ty::maps::queries::is_sized_raw<'tcx>>::try_get::h218d2f8e87627fd8
  17:     0x7f05aeeb1b16 - rustc::ty::maps::TyCtxtAt::is_sized_raw::h946f581dc74f2f83
  18:     0x7f05aecf8709 - rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::is_sized::he0a6d5e9531b6d3c
  19:     0x7f05b01dd042 - rustc_trans::callee::get_fn::hc27dafcc28f7ba50
  20:     0x7f05b0214ff2 - rustc_trans::mir::block::<impl rustc_trans::mir::MirContext<'a, 'tcx>>::trans_terminator::ha7f494e599da4990
  21:     0x7f05b021019c - rustc_trans::mir::trans_mir::h748fe24b84d09cf0
  22:     0x7f05b01ccb4e - rustc_trans::base::trans_instance::h202b404337e1c89c
  23:     0x7f05b01d9131 - rustc_trans::base::compile_codegen_unit::hb0fa82088fdd60ab
  24:     0x7f05aeea1e45 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::force::ha534608d28be5a5e
  25:     0x7f05aeea38a1 - rustc::ty::maps::<impl rustc::ty::maps::queries::compile_codegen_unit<'tcx>>::try_get::h53b926ccf3be830e
  26:     0x7f05aeeb5aa3 - rustc::ty::maps::TyCtxtAt::compile_codegen_unit::h3bd8ef20be6de5af
  27:     0x7f05aeead4f7 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::compile_codegen_unit::h30a54b621ec4962f
  28:     0x7f05b01cf4d3 - rustc_trans::base::trans_crate::haf85c064dc8766ee
  29:     0x7f05b0235263 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::h5df6a45064f22a73
  30:     0x7f05b2438003 - rustc_driver::driver::compile_input::{{closure}}::h78c3764a9b163973
  31:     0x7f05b23b88b7 - rustc::ty::context::TyCtxt::create_and_enter::h4b7ccfc9e0ff61c6
  32:     0x7f05b2435c5b - rustc_driver::driver::compile_input::h224eac3dc4f05da3
  33:     0x7f05b245190e - rustc_driver::run_compiler::haeed4a20a242ccd2
  34:     0x7f05b2370a17 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbdb57a55951ef241
  35:     0x7f05b20cadec - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:99
  36:     0x7f05b23a9990 - <F as alloc::boxed::FnBox<A>>::call_box::h21becb19e1f0c98e
  37:     0x7f05b208f41b - std::sys::imp::thread::Thread::new::thread_start::h1a6247f115117cfe
                               at /checkout/src/liballoc/boxed.rs:772
                               at /checkout/src/libstd/sys_common/thread.rs:24
                               at /checkout/src/libstd/sys/unix/thread.rs:90
  38:     0x7f05acec26d9 - start_thread
  39:     0x7f05b1d53d7e - __clone
  40:                0x0 - <unknown>

error: Could not compile `limn-layout`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

#### Operating system

```
Linux 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

#### Reproducing

This bug occured when compiling the samples for `limn` (https://github.com/christolliday/limn):

```
git clone https://github.com/christolliday/limn
cargo run --example circles
```

**Comment by fschutt** [comment] 2017-10-12 18:58
Yep. It doesn't crash with `CARGO_INCREMENTAL=0`.

**Comment by mmstick** [comment] 2017-10-12 19:51
I get this issue with compiling the `calculate` crate.

**Comment by daboross** [comment] 2017-10-12 22:34
I have this issue compiling my own crate (http://github.com/daboross/screeps-rs) on `nightly-2017-10-11`.

**Comment by rkruppe** [comment] 2017-10-13 08:24
Duplicate of #45161, should be fixed in current nightly or at latest in the next nightly.

**Comment by kennytm** [comment] 2017-10-13 08:28
Closing as duplicate of #45161.

**Closed by kennytm** 2017-10-13 08:28 UTC
