### ISSUE TITLE
ICE in `librustc/middle/ty.rs`

### ISSUE THREAD

**Issue by swizard0** [rust-lang/rust#21779] opened 2015-01-30 15:04 UTC
Repeatable case: http://is.gd/kcejxG

% uname -a 
Darwin pair 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

% rustc --version --verbose
rustc 1.0.0-dev (a45e11773 2015-01-28 11:01:36 +0000)
binary: rustc
commit-hash: a45e117733b866302fa99390553d1c548508dcca
commit-date: 2015-01-28 11:01:36 +0000
host: x86_64-apple-darwin
release: 1.0.0-dev

% RUST_BACKTRACE=1 make
...
[ 96%] Making lib crate rs_cmset with /usr/local/bin/rustc
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: did.krate != ast::LOCAL_CRATE', /Users/swizard/distr/rust/src/librustc/middle/ty.rs:5369

stack backtrace:
   1:        0x1060db7a7 - sys::backtrace::write::ha7c2a314980a2c9fvbu
   2:        0x106101c5c - failure::on_fail::h6e454f5b61899a9aqbB
   3:        0x106063068 - rt::unwind::begin_unwind_inner::h197e2c88eee2bed0mTA
   4:        0x1030d9f6c - rt::unwind::begin_unwind::h15446879943960288925
   5:        0x10345a400 - middle::ty::lookup_trait_def::h88c5bce57aa634a31O7
   6:        0x10349cb77 - middle::ty::predicates_for_trait_ref::h459855321b274b287P7
   7:        0x103475438 - middle::traits::util::Elaborator<'cx, 'tcx>.Iterator::next::h670ac496f66d05c4wyT
   8:        0x10347b4e4 - middle::traits::util::Supertraits<'cx, 'tcx>.Iterator::next::ha6665f6ae93509757AT
   9:        0x102da1b98 - astconv::ast_ty_to_ty::closure.30847
  10:        0x102d39f10 - astconv::ast_ty_to_ty::h791f4e70b868f1e66jt
  11:        0x102d98239 - vec::Vec<T>.FromIterator<T>::from_iter::h17536640115762312557
  12:        0x102d95d5d - astconv::convert_angle_bracketed_parameters::h8a8cf081a61eaf4c7ss
  13:        0x102d99f92 - astconv::ast_path_to_trait_ref::h76759fc1ebf0bbe4yFs
  14:        0x102d467fb - astconv::instantiate_trait_ref::hce19a4879401779bfCs
  15:        0x102d9931a - astconv::instantiate_poly_trait_ref::h56d2fa5170cae6f6XAs
  16:        0x102dc9ae3 - collect::compute_bounds::h1a901096fd069158CDv
  17:        0x102db110b - collect::trait_def_of_item::hc3bcbaea1d0acb87U1u
  18:        0x102daf8ef - collect::CollectTraitDefVisitor<'a, 'tcx>.visit..Visitor<'v>::visit_item::h31c230bdcdecd31bneu
  19:        0x102dafb1f - collect::CollectTraitDefVisitor<'a, 'tcx>.visit..Visitor<'v>::visit_item::h31c230bdcdecd31bneu
  20:        0x102def55f - check_crate::closure.31984
  21:        0x102ded4d5 - check_crate::haecc3fe6465ec7b6ZNy
  22:        0x1027be8eb - driver::phase_3_run_analysis_passes::h79664d81b6b5b4e4NFa
  23:        0x1027a4e5c - driver::compile_input::hec1fc484fb82a3b3Bba
  24:        0x10286d50e - run_compiler::hc5f9e0285db79a55n9b
  25:        0x10286a62f - thunk::F.Invoke<A, R>::invoke::h4736678281155978274
  26:        0x1028692c0 - rt::unwind::try::try_fn::h3346791736825056138
  27:        0x10617aa09 - rust_try_inner
  28:        0x10617a9f6 - rust_try
  29:        0x102869984 - thunk::F.Invoke<A, R>::invoke::h14937575134341006880
  30:        0x1060ec313 - sys::thread::thread_start::hd065b218eff37dc2J3w
  31:     0x7fff87bec268 - _pthread_body
  32:     0x7fff87bec1e5 - _pthread_body

**Comment by nagisa** [comment] 2015-01-30 15:12
Looks like a duplicate of #20220.

**Comment by swizard0** [comment] 2015-01-30 15:23
yes, exactly

**Closed** 2015-01-30 18:42 UTC
Labels: I-ICE
