### ISSUE TITLE
timely-0.1.15 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43681] opened 2017-08-05 13:38 UTC
[timely](https://crates.io/crates/timely) version 0.1.15 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/timely-0.1.15/log.txt)):

```
Aug 04 00:58:05.190 INFO kablam! error: no rules expected the token `EventStreamLogger<OperatesEvent, File>`
Aug 04 00:58:05.190 INFO kablam!    --> src/logging.rs:160:35
Aug 04 00:58:05.190 INFO kablam!     |
Aug 04 00:58:05.190 INFO kablam! 160 |               __thread_local_inner!($t, $init);
Aug 04 00:58:05.190 INFO kablam!     |                                     ^^
Aug 04 00:58:05.190 INFO kablam! ...
Aug 04 00:58:05.190 INFO kablam! 164 | / thread_local!{
Aug 04 00:58:05.190 INFO kablam! 165 | |     /// Logs operator creation.
Aug 04 00:58:05.190 INFO kablam! 166 | |     pub static OPERATES: EventStreamLogger<OperatesEvent, File> = EventStreamLogger::new();
Aug 04 00:58:05.190 INFO kablam! 167 | |     /// Logs channel creation.
Aug 04 00:58:05.190 INFO kablam! ...   |
Aug 04 00:58:05.190 INFO kablam! 178 | |     pub static GUARDED_PROGRESS: EventStreamLogger<bool, File> = EventStreamLogger::new();
Aug 04 00:58:05.190 INFO kablam! 179 | | }
Aug 04 00:58:05.191 INFO kablam!     | |_- in this macro invocation
```
cc @frankmcsherry

**Comment by arielb1** [comment] 2017-08-05 13:55
cc @jseyfried

**Comment by arielb1** [comment] 2017-08-05 13:57
Actually, maybe this is using the "pirate" `__thread_local_inner` from std?

**Comment by arielb1** [comment] 2017-08-05 14:01
Yup. This compiles on stable and not on beta:

```Rust
fn xyz() {
   __thread_local_inner!(Vec<u32>, Vec::new());
}

fn main() {}
```

Please don't use obviously private libstd macros.

**Comment by arielb1** [comment] 2017-08-05 14:02
timely 0.2.0 uses the newly-stable `thread_local!`.

**Comment by durka** [comment] 2017-08-06 01:54
It looks like old versions of timely copied the new thread_local macro from the PR before it was merged. Unfortunately(?) stability attributes on macros don't do anything.

**Comment by alexcrichton** [comment] 2017-08-22 21:22
The libs team discussed this today and we decided that we're not going to actively try to fix this regression, so closing.

**Closed by alexcrichton** 2017-08-22 21:22 UTC
Labels: C-bug, I-nominated, regression-from-stable-to-beta, T-libs
