### ISSUE TITLE
No warning for unused function using `impl Trait` on beta and nightly

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#54754] opened 2018-10-02 16:25 UTC
The following code only warns that `f` is unused on stable, not on beta or nightly:

```rust
trait Trait {}
impl<T> Trait for T {}

fn f() -> impl Trait {}
```

(apologies if this is a duplicate, but a quick search didn't turn anything up)

**Comment by FelixMcFelix** [comment] 2018-10-04 08:11
Yeah, the likely fix for this is to create a query for lints that removes all levels under `AccessLevel::Reachable`, or manually strip the entries each time. The former probably makes more sense. I wasn't sure we'd need to do this at the time, it shouldn't take too long.

**Comment by jonas-schievink** [comment] 2018-10-04 10:41
I've implemented a more minimal fix at #54810. It should be safe to backport to beta, if this is wanted at all.

**Comment by pnkfelix** [comment] 2018-10-04 15:06
(assigning self just to make sure everything gets followed up on here)

**Comment by pnkfelix** [comment] 2018-10-04 15:06
tagged as P-high since it was a regression.

**Closed** 2018-10-07 22:00 UTC
Labels: A-diagnostics, A-lint, P-high, T-compiler, regression-from-stable-to-beta
