### ISSUE TITLE
print! and println! (and other similar macro pairs) accept differing types of "format strings"

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#47441] opened 2018-01-15 03:47 UTC
`println!` accepts non-string literals as the format string:

```rust
fn main() {
    println!(12.3);
}
```
`print!` does not:

```rust
fn main() {
    print!(12.3);
}
```

```
error: format argument must be a string literal.
 --> src/main.rs:2:12
  |
2 |     print!(12.3);
  |            ^^^^
```

---

This is because `println!` is implemented as calling `print!` with the result of `concat!`:

https://github.com/rust-lang/rust/blob/1.23.0/src/libstd/macros.rs#L150-L154

`print!` just calls `format_args`:
 
https://github.com/rust-lang/rust/blob/1.23.0/src/libstd/macros.rs#L119-L121

However, `concat!` stringifies its argument:

https://github.com/rust-lang/rust/blob/1.23.0/src/libsyntax_ext/concat.rs#L32-L54

This means that the "format string" can be any of:

- string literal
- floating point literal
- character literal
- integer literal
- boolean literal

**Comment by shepmaster** [comment] 2018-01-15 03:47
Personally, I don't think that `println!` *should* accept non-string arguments, but it may be too late to put that particular genie back in the bottle?

**Comment by eddyb** [comment] 2018-01-15 03:49
cc @jseyfried @alexcrichton

**Comment by shepmaster** [comment] 2018-01-15 03:52
The same applies for `write` / `writeln` and `eprint` / `eprintln`.

**Comment by sfackler** [comment] 2018-01-15 03:54
Duplicate of #30143. There's not really anything we can do here without breaking back compat.

**Comment by shepmaster** [comment] 2018-01-15 03:57
@sfackler 

> not really anything we can do here

Why not change `print!` to add a `concat!` call so they behave the same?

**Comment by sfackler** [comment] 2018-01-15 03:58
The writeln/etc behavior is a bug, not a feature.

**Comment by shepmaster** [comment] 2018-01-15 04:00
> is a bug, not a feature.

I mean... "bugs" get fixed. This has been declared unfixable, so it's now a "feature". Unless somehow epochs will allow us to undo that mistake, isn't it better to be consistently broken?

**Comment by sfackler** [comment] 2018-01-15 04:03
I do not agree that making a misfeature larger for "consistency" is a good idea.

**Comment by shepmaster** [comment] 2018-01-15 04:03
https://github.com/rust-lang/rust/pull/41192#issuecomment-300289463

> (In general, no one had a clear reason we didn't want this behavior even for print!)

**Comment by sfackler** [comment] 2018-01-15 04:07
I have a reason: it is really annoying to accidentally leave off format arguments and have the result compile and print your template string. `println!("foo: {}")`.

**Comment by shepmaster** [comment] 2018-01-15 04:08
I'm not understanding your example:

```
error: 1 positional argument in format string, but no arguments were given
  --> src/main.rs:10:5
   |
10 |     println!("foo: {}");
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate
```

**Comment by sfackler** [comment] 2018-01-15 04:13
Oops, I thought I remembered that doing weird things but must have been thinking of something else.

Regardless, though, this is a duplicate of that issue. As far as I know, no one actually intentionally uses this behavior. I don't know why we would go out of our way to extend the support of a weird oddity.

**Comment by sfackler** [comment] 2018-01-15 04:47
As a more real argument as to why this behavior is bad, it seems better to know that the formatting functions expect a string literal first always, as opposed to a string literal first, unless you want to print a *literal* value, in which case you can just put it in. If we did anything like this IMO, we'd want `println!(x)` to be equivalent to `println!("{}", x)`.

**Comment by Mark-Simulacrum** [comment] 2018-01-15 15:05
So I feel like overall consensus though is that this is a duplicate issue and we don't want to "fix" (i.e., for consistency) print! and also don't want to remove (non backwards compatibly) the `concat!` from `println!`. Is that correct? If so, then we should close.

**Comment by matthieu-m** [comment] 2018-01-15 19:05
@sfackler : I think you remembered your issue backward. If you use `println!(foo)` it will print `foo` (as the string) instead of reminding you that you're missing a format string.

**Comment by sfackler** [comment] 2018-01-15 19:14
Ah yeah that might have been it.

**Comment by Aaronepower** [comment] 2018-04-23 18:05
Closing as duplicate of #30143

**Closed by Aaronepower** 2018-04-23 18:05 UTC
Labels: T-libs
