### ISSUE TITLE
Missing some warnings about "literal out of range for its type"

### ISSUE THREAD

**Issue by tommit** [rust-lang/rust#14165] opened 2014-05-13 03:05 UTC
The places I'd expect to get warnings are indicated by the comments in this example:
```
fn main() {
    let a: u8 = 1000;
    let b = 1000u8;
    let c = 1000 as u8; // NO WARNING !!!

    let one: u8 = 1;
    let d = (one * 1000) as u32;
    let e = (one *   -1) as u32; // NO WARNING !!!
    let f = (one * -255) as u32; // NO WARNING !!!
    let g = (one * -256) as u32;

    println!("{}, {}, {}, {}, {}, {}, {}", a, b, c, d, e, f, g);
}
```

Here's the compiler output:
```
warning: literal out of range for its type, #[warn(type_overflow)] on by default
let a: u8 = 1000;
            ^~~~
warning: literal out of range for its type, #[warn(type_overflow)] on by default
let b = 1000u8;
        ^~~~~~
warning: literal out of range for its type, #[warn(type_overflow)] on by default
let d = (one * 1000) as u32;
               ^~~~
warning: literal out of range for its type, #[warn(type_overflow)] on by default
let g = (one * -256) as u32;
                ^~~
```

And here's the program output:
```232, 232, 232, 232, 255, 1, 0```

**Comment by huonw** [comment] 2015-01-13 02:34
Duplicate of #5477.

**Closed by huonw** 2015-01-13 02:34 UTC
Labels: A-lint
