### ISSUE TITLE
Internal compiler error when installing a package in nightly mode.

### ISSUE THREAD

**Issue by anurbol** [rust-lang/rust#70778] opened 2020-04-04 17:36 UTC
Internal compiler error, panic, while installing a package.

I tried this code:

`cargo install wasm-bindgen-cli`

I expected to see this happen: it installs

Instead, this happened: failed to install, output:
```
   -- snip --
   Compiling wasm-bindgen-threads-xform v0.2.60
   Compiling serde_json v1.0.50
   Compiling docopt v1.1.0
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src\librustc\hir\mod.rs:81:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

   Compiling rouille v3.0.0
   Compiling wasm-bindgen-cli-support v0.2.60
error: could not compile `docopt`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-bindgen-cli v0.2.60`, intermediate artifacts can be found at `C:\Users\nurbol\AppData\Local\Temp\cargo-install47ieKB`

Caused by:
  build failed
```
## Meta

Please note that building on the stable toolchain (rustc 1.42) is fine.

`rustc --version --verbose`:

rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-pc-windows-msvc
release: 1.44.0-nightly
LLVM version: 9.0

**Comment by jonas-schievink** [comment] 2020-04-04 18:26
Please post the error message

**Comment by anurbol** [comment] 2020-04-04 20:22
@jonas-schievink I have updated the issue. Sorry for not doing that right away

**Comment by jonas-schievink** [comment] 2020-04-04 20:30
another duplicate of https://github.com/rust-lang/rust/issues/70041

**Closed by jonas-schievink** 2020-04-04 20:30 UTC
