### ISSUE TITLE
morphism-0.4.1 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43673] opened 2017-08-05 13:17 UTC
[morphism](https://crates.io/crates/morphism) version 0.4.1 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/morphism-0.4.1/log.txt)):

```
Aug 03 10:51:38.783 INFO blam! ---- src/lib.rs - Morphism<'a, B, C>::head (line 92) stdout ----
Aug 03 10:51:38.783 INFO blam! 	error: type `morphism::Void` is private
Aug 03 10:51:38.783 INFO blam!  --> <anon>:5:9
Aug 03 10:51:38.783 INFO blam!   |
Aug 03 10:51:38.783 INFO blam! 5 | let f = Morphism::new::<Option<String>>()
Aug 03 10:51:38.783 INFO blam!   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 03 10:51:38.783 INFO blam!
```
cc @freebroccolo

**Comment by petrochenkov** [comment] 2017-08-05 13:27
This one and https://github.com/rust-lang/rust/issues/43659 are duplicates, see https://github.com/rust-lang/rust/issues/43659#issuecomment-320441704

**Comment by alexcrichton** [comment] 2017-08-12 22:14
Closing as a duplicate of https://github.com/rust-lang/rust/issues/43659

**Closed by alexcrichton** 2017-08-12 22:14 UTC
Labels: C-bug, regression-from-stable-to-beta, T-compiler
