### ISSUE TITLE
Cannot compile a file in a non-utf8 directory

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#15890] opened 2014-07-22 02:37 UTC
```
$ mkdir $(echo 'foo\xff') 
$ touch $(echo 'foo\xff')/foo.rs
$ rustc $(echo 'foo\xff')/foo.rs
error: couldn't read foo�/foo.rs: couldn't open file (no such file or directory (No such file or directory); path=foo�/foo.rs; mode=open; access=read)
```

**Comment by frewsxcv** [comment] 2015-02-02 14:08
I was able to perform the commands above successfully with both fish and bash

fish

```
/tmp $ mkdir (echo 'foo\xff')
/tmp $ touch (echo 'foo\xff')/foo.rs
/tmp $ echo "fn main() {}" > (echo 'foo\xff')/foo.rs
/tmp $ rustc (echo 'foo\xff')/foo.rs
```

bash

```
/tmp $ mkdir $(echo 'foo\xff')
/tmp $ touch $(echo 'foo\xff')/foo.rs
/tmp $ echo "fn main() {}" > $(echo 'foo\xff')/foo.rs
/tmp $ rustc $(echo 'foo\xff')/foo.rs
```

**Comment by steveklabnik** [comment] 2015-02-02 14:14
I get

```
note: /usr/bin/ld: cannot open output file foo: Is a directory
collect2: error: ld returned 1 exit status

```

**Comment by steveklabnik** [comment] 2015-02-02 14:15
I am able to as well. Closing! Thanks for the triage.

**Comment by alexcrichton** [comment] 2015-02-02 16:33
Hm I'm actually quite surprised that this works. What versions of the compilers were you using? For me it continues to not work:

```
$ mkdir $(echo 'foo\xff')    
$ touch $(echo 'foo\xff')/foo.rs 
$ rustc $(echo 'foo\xff')/foo.rs 
error: couldn't read "foo\u{fffd}/foo.rs": couldn't open path as file (no such file or directory (No such file or directory); path=foo�/foo.rs; mode=open; access=read)
$ rustc -V
rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)
```

**Comment by frewsxcv** [comment] 2015-02-02 16:34
`rustc 1.0.0-nightly (1d00c545e 2015-01-30 19:56:34 +0000)`

**Comment by alexcrichton** [comment] 2015-02-02 16:36
Oh this may be a shell thing (I'm using zsh), when running `ls` after executing the commands in bash I see:

```
$ ls
foo\xff
```

I think that the escape syntax for bash must be different.

**Comment by frewsxcv** [comment] 2015-02-02 16:38
I just tried zsh and got your error:

```
error: couldn't read "foo\u{fffd}/foo.rs": couldn't open path as file (no such file or directory (No such file or directory); path=foo�/foo.rs; mode=open; access=read)
```

**Comment by ebfe** [comment] 2015-02-02 16:45
Reproducable in bash (note the `-e`).

    $ mkdir $(echo -e 'foo\xff')
    $ touch $(echo -e 'foo\xff')/foo.rs
    $ echo "fn main() {}" > $(echo -e 'foo\xff')/foo.rs
    $ rustc $(echo -e 'foo\xff')/foo.rs
    error: couldn't read "foo\u{fffd}/foo.rs": couldn't open path as file (no such file or directory (No such file or directory); path=foo�/foo.rs; mode=open; access=read)

**Comment by cuviper** [comment] 2016-02-28 03:03
It now fails saying, "called `Result::unwrap()` on an `Err` value".  I believe this is simply due to `rustc_driver::main()` using `env::args()` rather than `env::args_os()`, so it panics on the non-utf8.  You can reproduce this with any bad argument at all, e.g. in bash:

```
$ rustc $'\xff'
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "\u{fffd}"', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Accepting `OsString` will require changes down through the `getopts` crate, and I guess all the other users of that should be updated too.  I'm interested to try, if this sounds ok...

**Closed** 2017-05-19 23:38 UTC
Labels: A-driver
