### ISSUE TITLE
Compiler crash on `cargo +nightly udeps`

### ISSUE THREAD

**Issue by petar-dambovaliev** [rust-lang/rust#92446] opened 2021-12-30 19:35 UTC
```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', compiler/rustc_query_impl/src/on_disk_cache.rs:500:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (f8abed9ed 2021-12-26) running on x86_64-apple-darwin

note: compiler flags: -Z binary-dep-depinfo -Z save-analysis -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `filters::<impl at src/filters.rs:348:48: 348:66>::to_input_value`
#1 [analysis] running analysis passes on this crate
end of query stack
```

`cargo clean` fixed it.
However, on `cargo check` now i get tons of the following messages
`WARN rustc_metadata::locator no metadata found: incompatible metadata version found: /Users/user/IdeaProjects/myprojecttarget/debug/deps/libproc_macro_error_attr-10f61cdaa9115e40.dylib`

**Comment by ehuss** [comment] 2021-12-31 00:17
Thanks for the report!  This is a known issue, so I am going to close as a duplicate of #92163.

As a workaround, I would recommend running `cargo clean`. If the problem persists, you can turn off incremental compilation with `CARGO_INCREMENTAL=0` environment variable, or using an older nightly (one user reported nightly-2021-12-01 as working, but I don't know for sure).

**Closed by ehuss** 2021-12-31 00:17 UTC
Labels: I-ICE, T-compiler, C-bug
