### ISSUE TITLE
Failed to compile code with manual drop()

### ISSUE THREAD

**Issue by sug0** [rust-lang/rust#89575] opened 2021-10-05 21:21 UTC
### Code

This code fails to compile under the `rustc` versions posted below. I tested it in the online version of the rust playground, which failed too.

```Rust
fn assert_is_send(_: impl Send) {}

struct NonSendThing(*const ());

async fn do_task() {}

fn main() {
    let x = async {
        let x = NonSendThing(std::ptr::null());
        drop(x);
        do_task().await;
    };
    assert_is_send(x);
}
```
Changing the code slightly, yields a different result (i.e. it compiles):

```rust
fn assert_is_send(_: impl Send) {}

struct NonSendThing(*const ());

async fn do_task() {}

fn main() {
    let x = async {
        { 
            let x = NonSendThing(std::ptr::null());
        }
        do_task().await;
    };
    assert_is_send(x);
}
```

Therefore, I believe there is a bug in the compiler related with either move or drop semantics. As far as I can tell, this code fails to compile because the resulting`GenFuture` includes the state of a `!Send` variable in itself, when it is not necessary (the `!Send` value should be dropped before the `.await`).

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: x86_64-unknown-linux-gnu
release: 1.55.0
LLVM version: 12.0.1
```
`rustc +nightly --version --verbose`:
```
rustc 1.57.0-nightly (003d8d3f5 2021-10-04)
binary: rustc
commit-hash: 003d8d3f56848b6f3833340e859b089a09aea36a
commit-date: 2021-10-04
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### Error output

```
error: future cannot be sent between threads safely
  --> a.rs:13:5
   |
1  | fn assert_is_send(_: impl Send) {}
   |                           ---- required by this bound in `assert_is_send`
...
13 |     assert_is_send(x);
   |     ^^^^^^^^^^^^^^ future created by async block is not `Send`
   |
   = help: within `impl Future`, the trait `Send` is not implemented for `*const ()`
note: future is not `Send` as this value is used across an await
  --> a.rs:11:9
   |
9  |         let x = NonSendThing(std::ptr::null());
   |             - has type `NonSendThing` which is not `Send`
10 |         drop(x);
11 |         do_task().await;
   |         ^^^^^^^^^^^^^^^ await occurs here, with `x` maybe used later
12 |     };
   |     - `x` is later dropped here

error: aborting due to previous error
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
N/A
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-10-05 21:23
Duplicate of https://github.com/rust-lang/rust/issues/57478

**Closed by jonas-schievink** 2021-10-05 21:23 UTC
Labels: I-ICE, T-compiler, C-bug
