### ISSUE TITLE
Possible improvement in lack-of-semicolon error messages

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#36413] opened 2016-09-12 05:11 UTC
Talking to some folks at RustConf recently a common point of confusion seemed to be "where are semicolons required?" The compiler seemingly has arcane restrictions at the beginning and this means that we can perhaps improve errors in this respect to help guide beginners!

For example, in this code:

``` rust
pub fn foo() {
    if true {
        3
    } else {
        foo();
    }
}
```

it yields the error:

```
error[E0308]: mismatched types
 --> foo.rs:3:9
  |
3 |         3
  |         ^ expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `{integer}`

error: aborting due to previous error
```

Perhaps we could detect that the other branch of the `if` has a semicolon, and as a result a semicolon here is probably also the fix?

**Comment by estebank** [comment] 2016-09-13 00:43
I believe PR https://github.com/rust-lang/rust/pull/36409 would handle this case.

**Comment by Mark-Simulacrum** [comment] 2017-06-04 02:57
Closing as a duplicate of https://github.com/rust-lang/rust/issues/41897.

**Closed by Mark-Simulacrum** 2017-06-04 02:57 UTC
Labels: A-diagnostics, T-compiler
