### ISSUE TITLE
std::fs::walk_dir never closes directories

### ISSUE THREAD

**Issue by clee** [rust-lang/rust#25184] opened 2015-05-07 16:40 UTC
I wrote a small utility to recursively parse time data from files in a given root directory, and when I try to run it on my $HOME it errors out with:

Error { repr: Os(24) }

According to the devs in #rust, this is the error code for 'too many open files'. After looking at the code for walk_dir, it looks like it never calls closedir, which would explain why this is happening for me.

**Comment by alexcrichton** [comment] 2015-05-07 17:04
We do actually [call closedir](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs2.rs#L169-L174) when the [`ReadDir` value goes out of scope](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs2.rs#L36), so I don't believe that's a problem. This is likely a dupe of #23715, however, so I'm going to close in favor of that, but thanks for the report!

**Closed by alexcrichton** 2015-05-07 17:04 UTC
