### ISSUE TITLE
Arithmetic not folded

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#41631] opened 2017-04-29 13:47 UTC
The following program:

```rust
#![crate_type = "lib"]
use std::ptr;
use std::slice;
pub struct RawSlice<'a>
{
        s: &'a mut [u8]
}
impl<'a> RawSlice<'a> {
    fn write(&mut self, buf: &[u8])  {
        let dest_data = self.s.as_mut_ptr();
        let src_data = buf.as_ptr();
        unsafe {
            ptr::copy_nonoverlapping(src_data, dest_data, buf.len());
            self.s = slice::from_raw_parts_mut(dest_data.offset(buf.len() as isize), self.s.len() - buf.len());
        }
    }
}
pub fn do_write(r: &mut RawSlice, k: [u8; 4]) {
    r.write(&[1, 2, 3, 4]);
    r.write(&[1, 2, 3, 4]);
    r.write(&[1, 2, 3, 4]);
    r.write(&[1, 2, 3, 4]);
}
```

Compiles to:

```
        pushq   %rbp
        movq    %rsp, %rbp
        movq    (%rdi), %rax
        movl    $67305985, (%rax)
        addq    $-4, 8(%rdi)
        movl    $67305985, 4(%rax)
        addq    $-4, 8(%rdi)
        movl    $67305985, 8(%rax)
        addq    $-4, 8(%rdi)
        movl    $67305985, 12(%rax)
        addq    $16, %rax
        movq    8(%rdi), %rcx
        addq    $-4, %rcx
        movq    %rax, (%rdi)
        movq    %rcx, 8(%rdi)
        popq    %rbp
        retq
```

Ideally all of the addq -4 would be folded together. I suspect that either rust is emitting the wrong aliasing info or llvm is not properly dealing with the information.

**Comment by jrmuizel** [comment] 2017-05-01 14:09
I guess this might be #31681

**Comment by jrmuizel** [comment] 2017-05-01 15:09
I confirmed that reverting #31545 fixes this.

**Comment by steveklabnik** [comment] 2019-09-22 14:57
Triage: 

1. the code still does not optimize properly today
2. @jrmuizel confirmed that it's because we removed the `noalias` stuff
3. since this has been filed, we've re-enabled and then re-disabled `noalias` again.
4. this means that this is an effective dup of https://github.com/rust-lang/rust/issues/54878; the new 're-enable noalias' bug.

Closing! Thanks for the report.

**Closed by steveklabnik** 2019-09-22 14:57 UTC
Labels: A-LLVM, C-enhancement, I-slow
