### ISSUE TITLE
Documentation: Add canonical relation to HTML output

### ISSUE THREAD

**Issue by SamWhited** [rust-lang/rust#39241] opened 2017-01-22 15:03 UTC
While searching for documentation I've come across out of date old info listed alongside (or in front of) the current stable documentation ("the Python problem") in search results. It would be nice if all generated documentation for rust could include a meta tag telling search engines that the version of the docs it should index is the stable version:

```html
<link href="https://doc.rust-lang.org/nightly/<path>.html" rel="canonical">
```

See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Choosing_between_www_and_non-www_URLs#Using_%3Clink_relcanonical%3E

**Comment by steveklabnik** [comment] 2017-01-22 18:19
This is a duplicate of https://github.com/rust-lang/rust/issues/9461. Thank you for filing, though! Adding some of these links on that issue would be helpful. I'm going to close it so that we have one canonical (:wink:) issue for this.

**Closed by steveklabnik** 2017-01-22 18:19 UTC
