### ISSUE TITLE
fn() -> impl T { todo!() } not compiling

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#116003] opened 2023-09-20 13:57 UTC
I tried this code:

```rust
trait Foo {}


fn not_implemented() -> impl Foo {
    todo!()
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=55e475624b24e243aef53a2ace435156

I expected to see this happen: compiles.

Instead, this happened: 

```
Compiling playground v0.0.1 (/playground)
error[[E0277]](https://doc.rust-lang.org/stable/error_codes/E0277.html): the trait bound `(): Foo` is not satisfied
 --> src/lib.rs:4:25
  |
4 | fn not_implemented() -> impl Foo {
  |                         ^^^^^^^^ the trait `Foo` is not implemented for `()`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (lib) due to previous error
```

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.73.0-nightly (180dffba1 2023-08-14)
binary: rustc
commit-hash: 180dffba142c47240ca0d93096ce90b9fd97c8d7
commit-date: 2023-08-14
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 17.0.0
```

**Comment by fmease** [comment] 2023-09-20 14:10
Thanks reporting this issue! As I've elaborated in #113875, this works as intended in my opinion and according to @compiler-errors. Closing as duplicate of #113875.

**Comment by fmease** [comment] 2023-09-20 14:13
Closing as duplicate of #113875.

**Closed by fmease** 2023-09-20 14:13 UTC
Labels: T-lang, C-bug
