### ISSUE TITLE
Provide colorised output in JSON 

### ISSUE THREAD

**Issue by davidhewitt** [rust-lang/rust#48792] opened 2018-03-06 22:14 UTC
E.g. [`cargo-web`](https://github.com/koute/cargo-web) invokes rustc via `cargo build`, parsing and displaying the JSON output.

While `cargo build` has lovely color output, `cargo web build` is simply plaintext, which I understand is because the JSON output by rustc doesn't contain any formatting codes.

The color and formatting for the regular rustc output is very nice for making errors easier to read and diagnose quickly; I think it'd be very nice if this could optionally be included in the JSON output for cargo subcommands like `cargo-web`.

**Comment by oli-obk** [comment] 2018-03-07 08:49
The regular message is produced in

https://github.com/rust-lang/rust/blob/master/src/libsyntax/json.rs#L209

The issue is that

https://github.com/rust-lang/rust/blob/master/src/librustc_errors/emitter.rs#L177

produces a `Raw` destination. We'll need another constructor that creates a dummy-[terminal](https://stebalien.github.io/doc/term/term/terminfo/struct.TerminfoTerminal.html).

**Comment by davidhewitt** [comment] 2018-03-13 19:31
I would be willing to volunteer some time to implment this, if it's desirable. I've not worked on the compiler before so will probably need a little bit of mentoring. I imagine that we'd want to put the colorized json behind a flag (rather than changing it for all json)?

**Comment by oli-obk** [comment] 2018-03-16 09:25
I think we could just check the regular --color flag. If someone requests colors and json at the same time I think we can assume they want the json to contain colored output.

**Comment by nico-abram** [comment] 2019-10-05 09:59
I think the links in https://github.com/rust-lang/rust/issues/48792#issuecomment-371067174 are outdated.

I'd be interested in trying to work on this, but have only partially read the rustc guide. Would this be small enough to be doable for someone new?

**Comment by ehuss** [comment] 2019-10-05 13:49
This is already implemented via the [`--json=diagnostic-rendered-ansi` flag](https://doc.rust-lang.org/rustc/command-line-arguments.html#--json-configure-json-messages-printed-by-the-compiler).  As such, I think it will be fine to close this.

**Closed by ehuss** 2019-10-05 13:49 UTC
Labels: C-enhancement, T-cargo
