### ISSUE TITLE
rustc panics with: assertion failed: match *region { ty::ReLateBound(..) => false, _ => true, }

### ISSUE THREAD

**Issue by tuxmark5** [rust-lang/rust#46446] opened 2017-12-02 13:40 UTC
This code snippet causes rustc to panic:
```
fn trim_lines(text: &str) -> impl Iterator<Item=&str> {
    let mut prefix_length = 0;
    for c in text.chars() {
      match c {
        ' ' => prefix_length += 1,
        '\n' => continue,
        _ => break,
      }
    }

    text.lines().map(|line| {
      if line.len() >= prefix_length {
        &line[prefix_length..]
      } else {
        line
      }
    })
  }

fn main() {
  trim_lines("hello");
}

```

## Meta
rustc 1.23.0-nightly (33374fa9d 2017-11-20)
binary: rustc
commit-hash: 33374fa9d09e2a790979b31e61100dfed4b44139
commit-date: 2017-11-20
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0

The same thing happens with 1.24 nightly too on rust playground.

**Comment by arielb1** [comment] 2017-12-03 00:25
Duplicate of #42479

**Closed by arielb1** 2017-12-03 00:25 UTC
