### ISSUE TITLE
ICE:  'assertion failed: !bounds.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/method/mod.rs:388:9

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#77910] opened 2020-10-13 18:44 UTC
### Code

```Rust
fn foo(s: &i32) -> &i32 {
    let xs;
    xs
}
fn main() {
    let y;
    assert_eq!(foo, y);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (3525087ad 2020-10-08)

binary: rustc

commit-hash: 3525087ada7018ef227b10846648660b7f07b6d1

commit-date: 2020-10-08

host: x86_64-unknown-linux-gnu

release: 1.49.0-nightly

LLVM version: 11.0
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: !bounds.has_escaping_bound_vars()', compiler/rustc_typeck/src/check/method/mod.rs:388:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (8dae8cdcc 2020-10-12) running on x86_64-unknown-linux-gnu

error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: rustc_errors::Handler::delay_good_path_bug
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::trimmed_def_paths>::compute
             3: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
             4: rustc_data_structures::stack::ensure_sufficient_stack
             5: rustc_query_system::query::plumbing::get_query_impl
             6: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
             7: rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_type
             8: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_type
             9: rustc_middle::ty::print::pretty::<impl core::fmt::Display for &rustc_middle::ty::TyS>::fmt
            10: core::fmt::write
                       at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/core/src/fmt/mod.rs:1076
            11: core::fmt::Write::write_fmt
                       at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/core/src/fmt/mod.rs:182
                alloc::fmt::format
                       at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/alloc/src/fmt.rs:577
            12: rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_overloaded_binop
            13: rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_binop
            14: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            15: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            16: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            17: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            18: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            19: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            20: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
            21: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            22: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            23: rustc_typeck::check::fn_ctxt::FnCtxt::check_block_with_expected
            24: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            25: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            26: rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match
            27: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            28: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            29: rustc_typeck::check::fn_ctxt::FnCtxt::check_block_with_expected
            30: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            31: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            32: rustc_typeck::check::fn_ctxt::FnCtxt::check_stmt
            33: rustc_typeck::check::fn_ctxt::FnCtxt::check_block_with_expected
            34: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
            35: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation
            36: rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
            37: rustc_typeck::check::check::check_fn
            38: rustc_infer::infer::InferCtxtBuilder::enter
            39: rustc_typeck::check::typeck
            40: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck>::compute
            41: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
            42: rustc_data_structures::stack::ensure_sufficient_stack
            43: rustc_query_system::query::plumbing::get_query_impl
            44: rustc_query_system::query::plumbing::ensure_query_impl
            45: rustc_typeck::check::typeck_item_bodies
            46: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::typeck_item_bodies>::compute
            47: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
            48: rustc_data_structures::stack::ensure_sufficient_stack
            49: rustc_query_system::query::plumbing::get_query_impl
            50: rustc_typeck::check_crate
            51: rustc_interface::passes::analysis
            52: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
            53: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
            54: rustc_data_structures::stack::ensure_sufficient_stack
            55: rustc_query_system::query::plumbing::get_query_impl
            56: rustc_interface::passes::QueryContext::enter
            57: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
            58: rustc_span::with_source_map
            59: scoped_tls::ScopedKey<T>::set
            60: std::sys_common::backtrace::__rust_begin_short_backtrace
            61: core::ops::function::FnOnce::call_once{{vtable.shim}}
            62: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
                       at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/alloc/src/boxed.rs:1042
                <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
                       at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/alloc/src/boxed.rs:1042
                std::sys::unix::thread::Thread::new::thread_start
                       at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys/unix/thread.rs:87
            63: start_thread
            64: clone


thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:961:13
stack backtrace:
   0:     0x7fe8fb9e0410 - std::backtrace_rs::backtrace::libunwind::trace::h622bab51c72c4e69
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x7fe8fb9e0410 - std::backtrace_rs::backtrace::trace_unsynchronized::h7e820b882ebd41ee
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe8fb9e0410 - std::sys_common::backtrace::_print_fmt::h64d46258114db92f
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys_common/backtrace.rs:79:5
   3:     0x7fe8fb9e0410 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h47111d0c1b5f0da5
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys_common/backtrace.rs:58:22
   4:     0x7fe8fba4edfc - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/core/src/fmt/mod.rs:1076:17
   5:     0x7fe8fb9d2222 - std::io::Write::write_fmt::h4604516fed3e5731
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/io/mod.rs:1516:15
   6:     0x7fe8fb9e520d - std::sys_common::backtrace::_print::h785e7a78d5ef272c
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys_common/backtrace.rs:61:5
   7:     0x7fe8fb9e520d - std::sys_common::backtrace::print::h108047ac5c4555d5
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys_common/backtrace.rs:48:9
   8:     0x7fe8fb9e520d - std::panicking::default_hook::{{closure}}::h1d0c271f0d087ebf
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/panicking.rs:208:50
   9:     0x7fe8fb9e4eb8 - std::panicking::default_hook::h692753e26f11b7b7
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/panicking.rs:227:9
  10:     0x7fe8fc2a02c8 - rustc_driver::report_ice::h94e1b9f0f92bafae
  11:     0x7fe8fb9e5a56 - std::panicking::rust_panic_with_hook::h74ddc20305301cd9
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/panicking.rs:581:17
  12:     0x7fe8fb9e55d9 - std::panicking::begin_panic_handler::{{closure}}::h1a9ca6427ceee1d0
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/panicking.rs:484:9
  13:     0x7fe8fb9e08cc - std::sys_common::backtrace::__rust_end_short_backtrace::h97e27b7ab754adde
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys_common/backtrace.rs:153:18
  14:     0x7fe8fb9e5599 - rust_begin_unwind
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/panicking.rs:483:5
  15:     0x7fe8fb9e554b - std::panicking::begin_panic_fmt::h45d0f154d1dd3395
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/panicking.rs:437:5
  16:     0x7fe8ff34af41 - rustc_errors::HandlerInner::flush_delayed::h7bddafb93bd8de90
  17:     0x7fe8ff3478fc - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::hd958c71a259d81a2
  18:     0x7fe8fc2d4b46 - core::ptr::drop_in_place::h40d5276e772edf19
  19:     0x7fe8fc2e7d26 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h6e883ca9dd0b7542
  20:     0x7fe8fc2b1f4d - core::ptr::drop_in_place::h0bc6a6c8123fa286
  21:     0x7fe8fc2a50fd - rustc_span::with_source_map::h62a26cc1f538b576
  22:     0x7fe8fc2bd221 - scoped_tls::ScopedKey<T>::set::h851e47b28a99a947
  23:     0x7fe8fc2c5e91 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcc10758615a842a8
  24:     0x7fe8fc24a3de - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdee37546948bd4b7
  25:     0x7fe8fb9f486a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h588ce842808b3fd0
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/alloc/src/boxed.rs:1042:9
  26:     0x7fe8fb9f486a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h46bc655f05471a92
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/alloc/src/boxed.rs:1042:9
  27:     0x7fe8fb9f486a - std::sys::unix::thread::Thread::new::thread_start::hb4b79d379b730058
                               at /rustc/8dae8cdcc8fa879cea6a4bbbfa5b32e97be4c306/library/std/src/sys/unix/thread.rs:87:17
  28:     0x7fe8fb925609 - start_thread
  29:     0x7fe8fb839293 - clone
  30:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (8dae8cdcc 2020-10-12) running on x86_64-unknown-linux-gnu

thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**NOTE: The bug is found by our work-in-progress compiler testing tool Kira, and the test program is reduced/minimized by [Perses](https://github.com/chengniansun/perses)**

**Comment by Stupremee** [comment] 2020-10-13 18:58
It also fails for every comparison of `foo` and `y`

**Comment by camelid** [comment] 2020-10-13 19:06
I found another potentially related weirdness:

```rust
fn foo(s: &i32) -> &i32 {
    let xs;
    xs
}
```

This fails with:

```
warning: unused variable: `s`
 --> src/lib.rs:1:8
  |
1 | fn foo(s: &i32) -> &i32 {
  |        ^ help: if this is intentional, prefix it with an underscore: `_s`
  |
  = note: `#[warn(unused_variables)]` on by default

error[E0381]: use of possibly-uninitialized variable: `xs`
 --> src/lib.rs:3:5
  |
3 |     xs
  |     ^^ use of possibly-uninitialized `xs`

error: aborting due to previous error; 1 warning emitted
```

But this (without the argument) fails with a different error, even though there should be no difference as `s` is not used:

```rust
fn foo() -> &i32 {
    let xs;
    xs
}
```

```
error[E0106]: missing lifetime specifier
 --> src/lib.rs:1:13
  |
1 | fn foo() -> &i32 {
  |             ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
  |
1 | fn foo() -> &'static i32 {
  |             ^^^^^^^^

error: aborting due to previous error
```

**Comment by camelid** [comment] 2020-10-13 19:10
searched nightlies: from nightly-2019-01-01 to nightly-2020-10-13
regressed nightly: nightly-2020-05-03
searched commits: from https://github.com/rust-lang/rust/commit/7f65393b9abf5e70d0b9a8080558f17c5625bd40 to https://github.com/rust-lang/rust/commit/f05a5240440b3eaef1684a7965860fab40301947
regressed commit: https://github.com/rust-lang/rust/commit/dae90c195989b09475b6c0225a3018cbd7afa587

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --regress=ice --start=2019-01-01 
```
</details>

**Comment by camelid** [comment] 2020-10-13 19:12
Darn, is it really the bitcode commit again? Or did it happen sometime around then? Cc @alexcrichton

**Comment by camelid** [comment] 2020-10-13 19:40
This bisection is incorrect due to:

```
error: unknown codegen option: `embed-bitcode`
```

**Comment by Dylan-DPC** [comment] 2020-10-13 23:54
Marking this as P-[medium] based on the [wg-prioritization discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2377910.20ICE.3A.20.20'assertion.20failed.3A.20!bounds.2Ehas_es.E2.80.A6)

**Comment by ldm0** [comment] 2020-12-18 18:47
claim

**Comment by Stupremee** [comment] 2020-12-18 18:53
You have to write `@rustbot claim` if you want to assign this issue.

**Comment by ldm0** [comment] 2020-12-18 19:16
> You have to write `@rustbot claim` if you want to assign this issue.

Thanks bro.

@rustbot claim

**Closed** 2020-12-21 07:00 UTC
Labels: A-lifetimes, A-typesystem, C-bug, E-needs-bisection, I-ICE, P-medium, T-compiler, glacier, regression-from-stable-to-stable
