### ISSUE TITLE
private macros break intra-doc links

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust#81633] opened 2021-02-01 17:06 UTC
```rust
mod bar {
    macro_rules! str {() => {}}
}

pub mod foo {
    use std::path::{Path, PathBuf};

    pub struct Foo(PathBuf);
    impl std::ops::Deref for Foo {
        type Target = Path;
        fn deref(&self) -> &Path { &self.0 }
    }
}
```

In the documentation of `Foo::to_str()` inherited from the deref impl, the documentation contains a link to ``[`&str`](str)`` that fails due to the presence of a `str!` macro in another module, even though that macro isn't accessible. (Even if it was, it shouldn't be affecting the resolution of an intra-doc link in the standard library.)

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0-nightly (0e63af5da 2021-01-31)
binary: rustc
commit-hash: 0e63af5da3400ace48a0345117980473fd21ad73
commit-date: 2021-01-31
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

**Comment by apiraino** [comment] 2021-02-05 11:52
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381633.20private.20macros.20break.20intra-doc.20links) and removing `I-prioritize`

**Comment by GuillaumeGomez** [comment] 2021-02-05 20:59
After a deeper look, this seems like a low priority considering how rare it is. I'll still continue to check what's going on.

**Comment by jyn514** [comment] 2021-08-05 04:09
I can't investigate this currently due to https://github.com/rust-lang/rust/issues/87783 :facepalm:

**Comment by jyn514** [comment] 2021-11-30 20:05
I continue to be stymied in investigating this :facepalm: https://github.com/rust-lang/rust/issues/91400

**Comment by jyn514** [comment] 2021-12-01 16:15
Ok, I managed to mostly reproduce this without using types from the standard library - this has different bugs but there are still bugs.

```rust
pub mod foo {
    pub struct Bar(Baz);
    impl std::ops::Deref for Bar {
        type Target = Baz;
        fn deref(&self) -> &Baz { &self.0 }
    }

    pub struct Baz {}
    impl Baz {
        /// [str]
        pub fn foo(&self) {
            str!()
        }
    }
}

mod bar {
    macro_rules! str {() => {}}
}
```

That has the following output when run with rustdoc:
```
warning: `str` is both a builtin type and a macro
  --> src/lib.rs:47:14
   |
47 |         /// [str]
   |              ^^^ ambiguous link
   |
   = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
help: to link to the builtin type, prefix with `prim@`
   |
47 |         /// [prim@str]
   |              +++++
help: to link to the macro, add an exclamation mark
   |
47 |         /// [str!]
   |                 +
```
and with rustc:
```
error: cannot find macro `str` in this scope
  --> src/lib.rs:49:13
   |
49 |             str!()
   |             ^^^
   |
   = help: have you added the `#[macro_use]` on the module/import?

warning: unused macro definition: `str`
  --> src/lib.rs:55:18
   |
55 |     macro_rules! str {() => {}}
   |                  ^^^
   |
   = note: `#[warn(unused_macros)]` on by default
```

**Comment by jyn514** [comment] 2021-12-01 16:18
Oh, and Deref isn't related, you get the same issues without it:
```rust
mod bar {
    macro_rules! str {() => {}}
}

pub mod foo {
    pub struct Baz {}
    impl Baz {
        /// [str]
        pub fn foo(&self) {
            // str!()
        }
    }
}
```

**Comment by jyn514** [comment] 2021-12-01 17:14
This is the code that's incorrectly resolving `str!`: https://github.com/rust-lang/rust/blob/f04a2f4b8e89eac1119061ea2055d33c97e618b4/src/librustdoc/passes/collect_intra_doc_links.rs#L413-L415

That was first added in https://github.com/rust-lang/rust/pull/47046, specifically https://github.com/rust-lang/rust/commit/00ce770e348a4d00985b8872fc4874480115f621. There are two other macro lookups in that function, `resolve_macro_path` and `resolve_str_path_error(MacroNS)`. `resolve_macro_path` was added in https://github.com/rust-lang/rust/commit/7ac48d793bc06d2646244e070c25cc129e539d17 in the same PR. `resolve_str_path_error` was added in https://github.com/rust-lang/rust/commit/4eda3f77bd1ec94a97229a3ff0610eee136aa0d5 / https://github.com/rust-lang/rust/pull/73183.

@Manishearth do you think we need all three of these? I'm tempted to remove everything but `resolve_str_path_error`.

**Comment by jyn514** [comment] 2021-12-01 17:15
> I'm tempted to remove everything but resolve_str_path_error.

Tried this and I'm not seeing any test failures :)

**Comment by petrochenkov** [comment] 2022-04-28 14:37
Fixed in https://github.com/rust-lang/rust/pull/96521.

**Closed** 2022-05-27 12:46 UTC
Labels: T-rustdoc, P-low, A-macros, C-bug, A-intra-doc-links
