### ISSUE TITLE
Invalid code after std::process::exit will cause compilation to fail

### ISSUE THREAD

**Issue by TheDutchMC** [rust-lang/rust#84723] opened 2021-04-29 21:03 UTC
I'm honestly not sure if Cargo's repository is the place to file this issue, if it is not, apologies! (Where should I file it then?)

**Problem**

When using std::process::exit, the code after it will prevent you from compiling if it is invalid. Take the following codeblock
```rs
pub struct Something {
   some_param: String
}

pub fn something() {
   let something: Something = get_something();
   std::process::exit(1);

   //Try to access a nonexistent field in Something will prevent you from compiling
   //Even though the std::process::exit call will always exit immediately after, so the code after it shouldn't even be compiled I'd think
   let not_something = something.this_param_does_not_exist;
}
```

Practical demo:
I ran into this while debugging some API call, instead of deserializing the json I just wanted to print the text. See the two screenshots.
![image](https://user-images.githubusercontent.com/28569170/116618100-ed588500-a93e-11eb-8f1c-be1d7defd5c8.png)
![image](https://user-images.githubusercontent.com/28569170/116618110-efbadf00-a93e-11eb-85de-5208208a2412.png)

**Steps**

1. Have a function with some invalid code
2. Stick std::process::exit in it
3. Observe that the code after the exit call will prevent you from compiling

**Possible Solution(s)**

A possible solution would be to not compile, or at least not fail to compile, (on) things after a call to std::process::exit

**Notes**
I do think it should be allowed to do as I showed above, considering this will compile successfully:
```rs
let x: String = if something {
   std::process::exit(1)
} else {
  "x".to_string()
};
```

Output of `cargo version`: cargo 1.50.0 (f04e7fab7 2021-02-04)

**Comment by ehuss** [comment] 2021-04-29 22:09
Transferred to rust-lang/rust as this is a language issue.

However, I think it is working as expected. The reason your second example works is because exit returns the never type (!). The never type can be coerced into any other type, so that is why that example is valid.

There have been requests to have things like `todo!` or `unimplemented!` squelch unused warnings, but I don't think they have been accepted.  Additionally, a language change like this would usually go through the RFC process.

**Comment by jonas-schievink** [comment] 2021-04-29 22:10
This is working as intended, all parts of the program need to be well-typed, even if they are unreachable at runtime.

**Closed by jonas-schievink** 2021-04-29 22:10 UTC
