### ISSUE TITLE
RangeArgument not exported to std::collections

### ISSUE THREAD

**Issue by Pscheidl** [rust-lang/rust#28517] opened 2015-09-19 17:18 UTC
Trait RangeArgument (currently new and unstable in Rust 1.3) is not exported into standard library. 
https://doc.rust-lang.org/stable/collections/range/trait.RangeArgument.html

**Comment by alexcrichton** [comment] 2015-09-19 19:01
This is currently intentional because the enum is unstable (and nightly users can get it through libcollections), co closing as working as intended. Thanks for the report though!

Also note that [soon this enum](https://github.com/rust-lang/rfcs/pull/1254) [may not be necessary](https://github.com/rust-lang/rfcs/pull/1257)

**Closed by alexcrichton** 2015-09-19 19:01 UTC
