### ISSUE TITLE
Bootstrap fails "No such file" for llvm-objcopy

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#132903] opened 2024-11-11 15:16 UTC
Recently, build of rustc is failing with:

```
src.symlink_metadata() failed with No such file or directory (os error 2) ("src = /rust/build/aarch64-unknown-linux-gnu/stage1/lib/rustlib/aarch64-unknown-linux-gnu/bin/llvm-objcopy")
```

Steps:

1. `git clone https://github.com/rust-lang/rust.git`
2. `cd rust`
3. `./x.py build`

### Meta

Currently on d4822c2d84c242cc7403118b50c571464f38ef8f

Tested on aarch64-unknown-linux-gnu and x86_64-unknown-linux-gnu

**Comment by onur-ozkan** [comment] 2024-11-11 15:21
cc @jieyouxu (I think you did some work related to this very recently, if I am not mistaken)

**Comment by jieyouxu** [comment] 2024-11-11 15:23
Maybe duplicate of #132719?

**Comment by ehuss** [comment] 2024-11-11 15:50
Yes, I verified that this is fixed by #132720, and that this was introduced by #131405.

**Comment by jieyouxu** [comment] 2024-11-11 15:53
Thanks, closing as a duplicate of #132719.

**Closed by jieyouxu** 2024-11-11 15:53 UTC
Labels: T-bootstrap, C-bug
