### ISSUE TITLE
SIGABRT in LLVM during stage0/librustc_typeck (RUSTFLAGS=-g)

### ISSUE THREAD

**Issue by ktossell** [rust-lang/rust#20951] opened 2015-01-11 17:34 UTC
```
git pull #2127e0d56d85ff48aafce90ab762650e46370b63
./configure --enable-clang --disable-libcpp --prefix=/home/ken/proj/rust --enable-ccache
make clean
make RUSTFLAGS=-g VERBOSE=1
```

```
CFG_LLVM_LINKAGE_FILE=/home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/stage0/lib:$LD_LIBRARY_PATH   x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0 -g -O --cfg rtopt --cfg debug -C prefer-dynamic -Z no-landing-pads --target=x86_64-unknown-linux-gnu  -W warnings -L "x86_64-unknown-linux-gnu/rt" -L "/home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/llvm/Release+Asserts/lib" -L ""  --out-dir x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib -C extra-filename=-4e7c5e5c /home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs
/home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs:68:1: 68:15 warning: unused attribute, #[warn(unused_attributes)] on by default
/home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs:68 #![staged_api]
                                                           ^~~~~~~~~~~~~~
rustc: /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/llvm/lib/IR/DebugInfo.cpp:159: uint64_t llvm::DIVariable::getPieceOffset() const: Assertion `isVariablePiece()' failed.
/home/ken/proj/rust/src/rust/mk/target.mk:165: recipe for target 'x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_typeck' failed
make: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_typeck] Aborted (core dumped)
```

```
~/p/r/s/rust git:master ❯❯❯ CFG_LLVM_LINKAGE_FILE=/home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/stage0/lib:$LD_LIBRARY_PATH  gdb --args x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0 -g -O --cfg rtopt --cfg debug -C prefer-dynamic -Z no-landing-pads --target=x86_64-unknown-linux-gnu  -W warnings -L "x86_64-unknown-linux-gnu/rt" -L "/home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/llvm/Release+Asserts/lib" -L ""  --out-dir x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib -C extra-filename=-4e7c5e5c /home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs
GNU gdb (GDB) 7.8.1
[...]
Reading symbols from x86_64-unknown-linux-gnu/stage0/bin/rustc...done.
(gdb) r
Starting program: /home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0 -g -O --cfg rtopt --cfg debug -C prefer-dynamic -Z no-landing-pads --target=x86_64-unknown-linux-gnu -W warnings -L x86_64-unknown-linux-gnu/rt -L /home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/llvm/Release+Asserts/lib -L '' --out-dir x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib -C extra-filename=-4e7c5e5c /home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff63ff700 (LWP 21477)]
/home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs:68:1: 68:15 warning: unused attribute, #[warn(unused_attributes)] on by default
/home/ken/proj/rust/src/rust/src/librustc_typeck/lib.rs:68 #![staged_api]
                                                           ^~~~~~~~~~~~~~
rustc: /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/llvm/lib/IR/DebugInfo.cpp:159: uint64_t llvm::DIVariable::getPieceOffset() const: Assertion `isVariablePiece()' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff63ff700 (LWP 21477)]
0x00007ffff6f28a97 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6f28a97 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6f29e6a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6f218bd in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff6f21972 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000555556f3b24a in llvm::DIVariable::getPieceOffset() const ()
#5  0x000055555721a756 in llvm::DwarfUnit::addComplexAddress(llvm::DbgVariable const&, llvm::DIE&, llvm::dwarf::Attribute, llvm::MachineLocation const&) ()
#6  0x000055555721ac3e in llvm::DwarfUnit::addVariableAddress(llvm::DbgVariable const&, llvm::DIE&, llvm::MachineLocation) ()
#7  0x000055555721f3d1 in llvm::DwarfUnit::constructVariableDIEImpl(llvm::DbgVariable const&, bool) ()
#8  0x000055555721f54c in llvm::DwarfUnit::constructVariableDIE(llvm::DbgVariable&, bool) ()
#9  0x0000555556a374fa in llvm::DwarfDebug::createScopeChildrenDIE(llvm::DwarfCompileUnit&, llvm::LexicalScope*, llvm::SmallVectorImpl<std::unique_ptr<llvm::DIE, std::default_delete<llvm::DIE> > >&, unsigned int*) ()
#10 0x0000555556a379f7 in llvm::DwarfDebug::createAndAddScopeChildren(llvm::DwarfCompileUnit&, llvm::LexicalScope*, llvm::DIE&) ()
#11 0x0000555556a37d7c in llvm::DwarfDebug::constructSubprogramScopeDIE(llvm::DwarfCompileUnit&, llvm::LexicalScope*) ()
#12 0x0000555556a3bdfc in llvm::DwarfDebug::endFunction(llvm::MachineFunction const*) ()
#13 0x0000555556a169f9 in llvm::AsmPrinter::EmitFunctionBody() ()
#14 0x0000555556826783 in llvm::X86AsmPrinter::runOnMachineFunction(llvm::MachineFunction&) ()
#15 0x0000555556ebee8f in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
#16 0x0000555556ebeedb in llvm::FPPassManager::runOnModule(llvm::Module&) ()
#17 0x0000555556ec061f in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
#18 0x000055555646174e in LLVMRustWriteOutputFile (Target=0x7fffd01b3e30, PMR=0x7fffcb0d72b0, 
    M=0x7ffff0004f90, 
    path=0x7fffdb9e9580 "x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/rustc_typeck-4e7c5e5c.0.o", FileType=llvm::TargetMachine::CGFT_ObjectFile)
    at /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/rustllvm/PassWrapper.cpp:211
#19 0x00005555558072f0 in back::write::write_output_file::h4a807fe5501cbdf3U6b ()
#20 0x0000555555809478 in back::write::optimize_and_codegen::unboxed_closure.36426 ()
#21 0x00005555558142cd in back::write::execute_work_item::had3c2de75e78498bVXc ()
#22 0x000055555580ab01 in back::write::run_passes::h27387495ebd9f18eVFc ()
#23 0x0000555555733834 in driver::phase_5_run_llvm_passes::h74facfaf246638e4IGa ()
#24 0x0000555555713d6e in driver::compile_input::h2f891483b4eb79a6vba ()
#25 0x00005555557db11e in thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h5746357467572345012 ()
#26 0x00005555557d7f0f in rt::unwind::try::try_fn::h1650409585031243765 ()
#27 0x0000555557433879 in rust_try_inner ()
#28 0x0000555557433866 in rust_try ()
#29 0x00005555557d8626 in thunk::F.Invoke$LT$A$C$$u{20}R$GT$::invoke::h7797410085787637463 ()
#30 0x000055555742d712 in sys::thread::thread_start::h6c63e7163c0f0d94Xkw ()
#31 0x00007ffff7bc6314 in start_thread () from /usr/lib/libpthread.so.0
#32 0x00007ffff6fdd24d in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by ktossell** [comment] 2015-01-11 17:37
```
❯❯❯ /home/ken/proj/rust/src/rust/x86_64-unknown-linux-gnu/stage0/bin/rustc -Vv
rustc 1.0.0-dev (9e4e524e0 2015-01-07 05:31:23 +0000)
binary: rustc
commit-hash: 9e4e524e0eb17c8f463e731f23b544003e8709c6
commit-date: 2015-01-07 05:31:23 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-dev
```

**Comment by michaelwoerister** [comment] 2015-01-14 10:21
Thanks for the report!

**Comment by michaelwoerister** [comment] 2015-01-14 10:23
I'm closing this as a duplicate of #20798

**Closed by michaelwoerister** 2015-01-14 10:23 UTC
Labels: A-debuginfo, A-llvm, I-ICE
