### ISSUE TITLE
Better error messages when mixing io::Result and non io::Result

### ISSUE THREAD

**Issue by xavierd** [rust-lang/rust#62125] opened 2019-06-25 18:25 UTC
See the following playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=98bf237ffb9961d9d598c4ed16194517

A better error message can suggest writing the nested function as: `Ok(bar()?)`

**Comment by estebank** [comment] 2023-01-05 19:15
Duplicate of https://github.com/rust-lang/rust/issues/47560

**Closed by estebank** 2023-01-05 19:15 UTC
Labels: C-enhancement, A-diagnostics, T-compiler, D-newcomer-roadblock
