### ISSUE TITLE
rustc panicked in RLS. "node type <G>::NodeId (...) cannot be placed in TypeckTables with local_id_root"

### ISSUE THREAD

**Issue by gentoid** [rust-lang/rust#64704] opened 2019-09-23 09:23 UTC
Not sure if there are similar issues, so I open a  new one.

In my project https://gitlab.com/gentoid/oxyfy/merge_requests/7 I updated deps (see [the diff](https://gitlab.com/gentoid/oxyfy/merge_requests/7/diffs?diff_id=55967431&start_sha=ef363f13ee24afe36fa22dc7c131cd9bc9c278cb)) and updated nightly Rust to the latest available. And after that I noticed, that RLS in VS Code cannot compile the project, while the command `cargo build` runs successfully. 

## Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.39.0-nightly (1dd188489 2019-09-22)
binary: rustc
commit-hash: 1dd1884891636d0eb51157d137230076bcf20627
commit-date: 2019-09-22
host: x86_64-pc-windows-msvc
release: 1.39.0-nightly
LLVM version: 9.0
```

`RUST_BACKTRACE=full rls --cli`:
```
......
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"crossbeam_epoch","percentage":null,"title":"Building"}}
{"message":"src\\librustc\\ty\\context.rs:211: node type <G>::NodeId (hir_id=HirId { owner: DefIndex(2599), local_id: 10 }) with HirId::owner DefId(0:2599 ~ petgraph[2251]::algo[0]::tarjan_scc[0]::Data[0]) cannot be placed in TypeckTables with local_id_root DefId(0:813 ~ petgraph[2251]::algo[0]::tarjan_scc[0])","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src\\librustc\\ty\\context.rs:211: node type <G>::NodeId (hir_id=HirId { owner: DefIndex(2599), local_id: 10 }) with HirId::owner DefId(0:2599 ~ petgraph[2251]::algo[0]::tarjan_scc[0]::Data[0]) cannot be placed in TypeckTables with local_id_root DefId(0:813 ~ petgraph[2251]::algo[0]::tarjan_scc[0])\n\n"}
thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:643:9
stack backtrace:
   0:     0x7ffa61d15aa9 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h40c797ea5e669f3b
   1:     0x7ffa61d441eb - core::fmt::write::h70ade69fe96ba4ab
   2:     0x7ffa61d089a4 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h6c5340d1685270e1
   3:     0x7ffa61d1a080 - std::panicking::take_hook::he56c301d6f51fb6a
   4:     0x7ffa61d19caa - std::panicking::take_hook::he56c301d6f51fb6a
   5:     0x7ffa36d168bb - rustc_driver::report_ice::he68a3557c9dce5cf
   6:     0x7ffa61d1a8fd - std::panicking::rust_panic_with_hook::h7d32e8d5cce086e7
   7:     0x7ffa389dab00 - rustc_errors::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter::ui_testing::h579d813dc4786078
   8:     0x7ffa389bfdf4 - rustc_errors::Handler::bug::h4ff81ebf5171872e
   9:     0x7ffa37f6f8c1 - rustc::util::bug::bug_fmt::h27374e8e08eecc4c
  10:     0x7ffa37f6ab96 - rustc::ty::wf::object_region_bounds::h0b3b8a9026febf62
  11:     0x7ffa37f6ab0a - rustc::ty::wf::object_region_bounds::h0b3b8a9026febf62
  12:     0x7ffa37f6ab4a - rustc::ty::wf::object_region_bounds::h0b3b8a9026febf62
  13:     0x7ffa37f6f7cf - rustc::util::bug::bug_fmt::h27374e8e08eecc4c
  14:     0x7ffa37f6f72d - rustc::util::bug::bug_fmt::h27374e8e08eecc4c
  15:     0x7ffa383cf7c9 - rustc::ty::context::validate_hir_id_for_typeck_tables::h4a6273e943b53f1e
  16:     0x7ffa383e5d6c - rustc::ty::context::TyCtxt::has_strict_asm_symbol_naming::hb8340dbc44d94248
  17:     0x7ffa383e5d42 - rustc::ty::context::TyCtxt::has_strict_asm_symbol_naming::hb8340dbc44d94248
  18:     0x7ffa383e439c - rustc::ty::context::TyCtxt::has_strict_asm_symbol_naming::hb8340dbc44d94248
  19:     0x7ffa383e43a9 - rustc::ty::context::TyCtxt::has_strict_asm_symbol_naming::hb8340dbc44d94248
  20:     0x7ffa383e5d59 - rustc::ty::context::TyCtxt::has_strict_asm_symbol_naming::hb8340dbc44d94248
  21:     0x7ffa383d01f3 - rustc::ty::context::TypeckTables::qpath_res::h8b9338525b1b775b
  22:     0x7ffa37b5c2e1 - rustc_save_analysis::SaveContext::get_path_res::h22865096683013cf
  23:     0x7ffa37b71ea2 - <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_ty::h70e54c1e9984e4cf
  24:     0x7ffa37bb488d - <rustc_save_analysis::dumper::Access as core::fmt::Debug>::fmt::hc8dbd908ebde2fa9
  25:     0x7ffa37b71eff - <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_ty::h70e54c1e9984e4cf
  26:     0x7ffa37b6be3b - <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item::h4f3ac72f1ca773ba
  27:     0x7ffa37b63d3f - rustc_save_analysis::dump_visitor::DumpVisitor::dump_compilation_options::hec032fcbb193cfd4
  28:     0x7ffa37b699dc - <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item::h4f3ac72f1ca773ba
  29:     0x7ffa37b6c6ec - <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item::h4f3ac72f1ca773ba
  30:     0x7ffa37b68e5a - <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_mod::h7a8f76018f3adafb
  31:     0x7ffa36cc10e8 - <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt::he09816576494fc65
  32:     0x7ffa36d3a81d - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5fb9ed3c549085bd
  33:     0x7ffa36d34e8c - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5fb9ed3c549085bd
  34:     0x7ffa36cdc02b - <rustc_driver::args::Error as core::fmt::Debug>::fmt::hb560277f8a9ab3c9
  35:     0x7ffa36da272e - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::compile::hd467ede6cf207209
  36:     0x7ffa36cdebcf - <rustc_driver::args::Error as core::fmt::Debug>::fmt::hb560277f8a9ab3c9
  37:     0x7ffa36cf2d36 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::hb560277f8a9ab3c9
  38:     0x7ffa36d195b1 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5fb9ed3c549085bd
  39:     0x7ffa36d351f9 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5fb9ed3c549085bd
  40:     0x7ffa36cadfac - <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt::he09816576494fc65
  41:     0x7ffa61d2c9c2 - _rust_maybe_catch_panic
  42:     0x7ffa36ccf152 - <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt::he09816576494fc65
  43:     0x7ffa61cf7af7 - ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Send$u2b$core..marker..Sync$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  44:     0x7ffa61d2a267 - std::sys::windows::thread::Thread::new::ha398ff2d90bbfcfb
  45:     0x7ffaa6ed7974 - BaseThreadInitThunk
  46:     0x7ffaa988a271 - RtlUserThreadStart
{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"audrey","percentage":null,"title":"Building"}}

{"jsonrpc":"2.0","method":"window/progress","params":{"done":null,"id":"progress_1","message":"walkdir","percentage":null,"title":"Building"}}
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (1dd188489 2019-09-22) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}
```

**Comment by jonas-schievink** [comment] 2019-09-23 10:09
Duplicate of https://github.com/rust-lang/rust/issues/64659

Please search for similar issues before opening a new one. Thanks!

**Closed by jonas-schievink** 2019-09-23 10:09 UTC
