### ISSUE TITLE
every f32 compared to 0 is true

### ISSUE THREAD

**Issue by jsen-** [rust-lang/rust#77266] opened 2020-09-27 14:32 UTC
I tried this code:

`main.rs`
```rust
#![no_std]
#![no_main]
#![feature(llvm_asm)]

pub fn black_box<T>(dummy: T) -> T {
    unsafe { llvm_asm!("" : : "r"(&dummy)) }
    dummy
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    use arduino_uno::prelude::*;
    let dp = arduino_uno::Peripherals::take().unwrap();
    let mut pins = arduino_uno::Pins::new(dp.PORTB, dp.PORTC, dp.PORTD);
    let mut led = pins.d13.into_output(&mut pins.ddr);
    loop {
        led.toggle().void_unwrap();
        arduino_uno::delay_ms(50);
    }
}

#[arduino_uno::entry]
fn main() -> ! {
    let x = 123.456;
    assert_eq!(x == 0f32, black_box(x) == 0f32);
    loop {}
}
```

`Cargo.toml`
```
[package]
name = "rust-arduino-blink"
version = "0.1.0"
edition = "2018"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1

[dependencies.arduino-uno]
git = "https://github.com/Rahix/avr-hal"
features = ["arduino-nano"]
```

`RUSTFLAGS="-Clink-args=-lc" cargo build --release --target avr-unknown-gnu-atmega328 -Z build-std=core`

I expected to see this happen: no blinking

Instead, this happened: blinking :)

### Meta
`rustc --version --verbose`:
```
rustc 1.48.0-nightly (0da580074 2020-09-22)
binary: rustc
commit-hash: 0da58007451a154da2480160429e1604a1f5f0ec
commit-date: 2020-09-22
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```
<details><summary>Backtrace</summary>
<p>
```
N/A
```
</p>
</details>

**Comment by jonas-schievink** [comment] 2020-09-27 14:34
Thanks for the report! This looks like a duplicate of https://github.com/rust-lang/rust/issues/77131, however, so closing in favor of that.

Please leave a comment on that issue if you have more information to contribute.

**Closed by jonas-schievink** 2020-09-27 14:34 UTC
Labels: C-bug
