### ISSUE TITLE
Incorrect Code Generation

### ISSUE THREAD

**Issue by npmccallum** [rust-lang/rust#63447] opened 2019-08-10 18:41 UTC
https://godbolt.org/z/Q0WgsL

```rust
use std::os::raw::c_char;
use std::ffi::c_void;

const RTLD_NEXT: *mut c_void = -1i64 as *mut c_void;

extern "C" {
    fn dlsym(handle: *mut c_void,
            symbol: *const c_char) -> *mut c_void;
}

#[allow(non_camel_case_types)]
type pid_t = i32;

#[inline(never)]
fn lookup<T: Copy>(_: T, name: *const u8) -> T {
    unsafe {
        let f = dlsym(RTLD_NEXT, name as *const c_char);
        let f = &f as *const *mut c_void as *const T;
        *f
    }
}

#[no_mangle]
pub extern "C" fn getpid() -> pid_t {
    let gp = lookup(getpid, "getpid\0".as_ptr());
    gp()
}
```

`-C opt-level=0`:

```asm
core::str::<impl str>::as_ptr:
  pushq %rax
  movq %rdi, %rax
  movq %rsi, (%rsp)
  popq %rcx
  retq

example::lookup:
  subq $24, %rsp
  movq $-1, %rax
  movq %rdi, 8(%rsp)
  movq %rax, %rdi
  movq 8(%rsp), %rsi
  callq *dlsym@GOTPCREL(%rip)
  movq %rax, 16(%rsp)
  addq $24, %rsp
  retq

getpid:
  subq $24, %rsp
  leaq .L__unnamed_1(%rip), %rax
  movq %rax, %rdi
  movl $7, %esi
  callq core::str::<impl str>::as_ptr
  movq %rax, 16(%rsp)
  movq 16(%rsp), %rdi
  callq example::lookup
  callq *getpid@GOTPCREL(%rip)
  movl %eax, 12(%rsp)
  movl 12(%rsp), %eax
  addq $24, %rsp
  retq

.L__unnamed_1:
  .asciz "getpid"
```

`-C opt-level=3`:
```asm
example::lookup:
  leaq .L__unnamed_1(%rip), %rsi
  movq $-1, %rdi
  jmpq *dlsym@GOTPCREL(%rip)

getpid:
  pushq %rax
.LBB1_1:
  callq example::lookup
  jmp .LBB1_1

.L__unnamed_1:
  .asciz "getpid"
```

The error is easiest to see under `-C opt-level=3`, though optimizers aren't causing the problem. The intent of the rust code is clearly to get the `RTLD_NEXT` version of `getpid()`. But for some reason Rust emits a recursive call.

**Comment by jonas-schievink** [comment] 2019-08-10 18:45
You're calling `lookup` with `T = getpid`, which is a zero-sized function type. Since those are only inhabited by the function they correspond to, rustc correctly concludes that `gp()` can only possibly refer to the `extern "C" fn getpid() -> pid_t` defined in the crate.

**Comment by npmccallum** [comment] 2019-08-10 19:18
1. That is black magic that non-compiler developers won't understand at first glance. The current behavior of silently compiling but doing something unexpected is not approachable. Either this code should be rejected with a clear warning or it should be made to do something expected.

2. Can you recommend an alternative way to write `lookup()`?

**Comment by jonas-schievink** [comment] 2019-08-10 19:45
The behavior is documented here: https://doc.rust-lang.org/reference/types/function-item.html

It is unlikely that this behavior will change. Function item types are documented, and so are raw pointer operations, and raw pointer ops on zero-sized type are specifically documented in the Rustonomicon here: https://doc.rust-lang.org/nomicon/vec-zsts.html

One thing I can suggest is not relying on type inference too much in unsafe code, and instead specifying types manually whenever the inferred type is not completely obvious.

(as an aside, `lookup` should be marked `unsafe`, since it allows reading arbitrary types from symbols)

Does it work if you invoke `lookup` like this?

    let gp = lookup::<extern fn() -> pid_t>(getpid, "getpid\0".as_ptr());

**Comment by nagisa** [comment] 2019-08-10 22:07
Closing as a not-a-bug.

As explained above, calling values of a function item type will call the function which this type represents – this is an expected and intended behaviour. The fact that a value of this type is obtained via a dubious sequence of unsafe operations does not make it black magic.

**Closed by nagisa** 2019-08-10 22:07 UTC

**Comment by npmccallum** [comment] 2019-08-11 00:40
@jonas-schievink That approach really defeats the point. In my code I'm combining it with this macro:

```rust
macro_rules! next {
    ($name:ident($($arg:expr),*)) => {
        crate::lookup(
            $name,
            concat!(stringify!($name), "\0").as_ptr()
        )($($arg),*)
    };
}
```

This basically means you can do this:

```rust
#[no_mangle]
pub extern "C" fn getpid() -> pid_t {
    // Do wrapper stuff...
    next!(getpid())
}

#[no_mangle]
pub extern "C" fn recv(fd: c_int, buf: *mut c_void, n: usize, flags: c_int) -> isize {
    // Do wrapper stuff..
    next!(recv(fd, buf, n, flags))
}
```

Since I have to override a lot of functions, this makes the code much more ergonomic. But the type which `dlsym()`'s return value needs to be casted to is variable.
