### ISSUE TITLE
Difficult to use format_args! with libcore (generates code in std::fmt)

### ISSUE THREAD

**Issue by Vaelden** [rust-lang/rust#21229] opened 2015-01-16 10:46 UTC
The `format_args!` built-in macro currently generates structures located in `std::fmt`, which makes it difficult to use with libcore, even though libcore has the correct traits to read the generated structure.
IMO it would be more logical to use core::fmt instead if possible.

It gives the following errors:
```rust
rust/main.rs:53:52: 53:55 error: failed to resolve. Maybe a missing `extern crate std`?
rust/main.rs:53     core::fmt::write(&mut uart, format_args!("{}", 42u64));
                                                                   ^~~
note: in expansion of format_args!
rust/main.rs:53:33: 53:59 note: expansion site
rust/main.rs:53:52: 53:57 error: unresolved name `std::fmt::String::fmt`
rust/main.rs:53     core::fmt::write(&mut uart, format_args!("{}", 42u64));
                                                                   ^~~~~
note: in expansion of format_args!
rust/main.rs:53:33: 53:59 note: expansion site
rust/main.rs:53:52: 53:55 error: failed to resolve. Maybe a missing `extern crate std`?
rust/main.rs:53     core::fmt::write(&mut uart, format_args!("{}", 42u64));
                                                                   ^~~
note: in expansion of format_args!
rust/main.rs:53:33: 53:59 note: expansion site
rust/main.rs:53:52: 53:57 error: unresolved name `std::fmt::argument`
rust/main.rs:53     core::fmt::write(&mut uart, format_args!("{}", 42u64));
                                                                   ^~~~~
note: in expansion of format_args!
rust/main.rs:53:33: 53:59 note: expansion site
rust/main.rs:53:46: 53:49 error: failed to resolve. Maybe a missing `extern crate std`?
rust/main.rs:53     core::fmt::write(&mut uart, format_args!("{}", 42u64));
                                                             ^~~
note: in expansion of format_args!
rust/main.rs:53:33: 53:59 note: expansion site
rust/main.rs:53:46: 53:50 error: unresolved name `std::fmt::Arguments::new`
rust/main.rs:53     core::fmt::write(&mut uart, format_args!("{}", 42u64));
                                                             ^~~~
note: in expansion of format_args!
rust/main.rs:53:33: 53:59 note: expansion site
```

I currently have a workaround for this by putting a `extern crate "core" as std;` but it is really ugly ...

**Comment by kmcallister** [comment] 2015-01-16 18:03
I think the usual workaround is the "curious inner-module":

```rust
mod std {
    pub use core::fmt;
}
```

This is closely related to #16803; I have an old PR fixing both, which I intend to revive soon.

**Comment by kmcallister** [comment] 2015-01-26 21:16
Closing as a duplicate of  #14342.

**Closed by kmcallister** 2015-01-26 21:16 UTC
Labels: A-syntaxext
