### ISSUE TITLE
Linking fails since nightly 1.15.

### ISSUE THREAD

**Issue by NickeZ** [rust-lang/rust#37796] opened 2016-11-16 08:46 UTC
Hey., I don't know if this is the right place to report such an error. I'm writing a simple application but I use a module that uses nightly features and therefore I have to use the nightly compiler (I think).

The following error started happening on my [travis build](https://travis-ci.org/NickeZ/rups/jobs/176181530) when nightly was bumped from 1.14 to 1.15:

```
Running `rustc /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/bit-set-0.2.0/src/lib.rs --crate-name bit_set --crate-type lib -g -C metadata=54466ecce1508045 -C extra-filename=-54466ecce1508045 --out-dir /home/travis/build/NickeZ/rups/target/debug/deps --emit=dep-info,link -L dependency=/home/travis/build/NickeZ/rups/target/debug/deps --extern bit_vec=/home/travis/build/NickeZ/rups/target/debug/deps/libbit_vec-6594644ffc5cc275.rlib --cap-lints allow`

error: linking with `cc` failed: exit code: 1

  |

  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/travis/build/NickeZ/rups/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef/build_script_build.0.o" "-o" "/home/travis/build/NickeZ/rups/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef/build_script_build" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/travis/build/NickeZ/rups/target/debug/deps" "-L" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/travis/build/NickeZ/rups/target/debug/deps/libbuild-493a7b0628804707.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-1357b93f.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"

  = note: /usr/bin/ld: /home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib(fileline.o)(.debug_frame+0x6c): reloc against `.debug_frame': error 2

/usr/bin/ld: final link failed: Nonrepresentable section on output

collect2: ld returned 1 exit status

error: aborting due to previous error

Build failed, waiting for other jobs to finish...

error: Could not compile `kernel32-sys`.

Caused by:

  process didn't exit successfully: `rustc /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/build.rs --crate-name build_script_build --crate-type bin -g -C metadata=d6afa5bd3d7cfaef --out-dir /home/travis/build/NickeZ/rups/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=/home/travis/build/NickeZ/rups/target/debug/deps --extern build=/home/travis/build/NickeZ/rups/target/debug/deps/libbuild-493a7b0628804707.rlib --cap-lints allow` (exit code: 101)
```

```
   Compiling clap v2.16.4

     Running `rustc /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.16.4/src/lib.rs --crate-name clap --crate-type lib -g --cfg feature=\"default\" --cfg feature=\"ansi_term\" --cfg feature=\"term_size\" --cfg feature=\"color\" --cfg feature=\"libc\" --cfg feature=\"strsim\" --cfg feature=\"suggestions\" --cfg feature=\"wrap_help\" -C metadata=9d7adcce84bc03a2 -C extra-filename=-9d7adcce84bc03a2 --out-dir /home/travis/build/NickeZ/rups/target/debug/deps --emit=dep-info,link -L dependency=/home/travis/build/NickeZ/rups/target/debug/deps --extern term_size=/home/travis/build/NickeZ/rups/target/debug/deps/libterm_size-9fd23557733de795.rlib --extern ansi_term=/home/travis/build/NickeZ/rups/target/debug/deps/libansi_term-aa5dcc2affa8dc75.rlib --extern bitflags=/home/travis/build/NickeZ/rups/target/debug/deps/libbitflags-0e272044714c8076.rlib --extern strsim=/home/travis/build/NickeZ/rups/target/debug/deps/libstrsim-b42a694875d9a3b0.rlib --extern unicode_width=/home/travis/build/NickeZ/rups/target/debug/deps/libunicode_width-bcfd50e6d35d16e0.rlib --extern vec_map=/home/travis/build/NickeZ/rups/target/debug/deps/libvec_map-d843695eff67d492.rlib --extern libc=/home/travis/build/NickeZ/rups/target/debug/deps/liblibc-ad32fde1bd850538.rlib --extern unicode_segmentation=/home/travis/build/NickeZ/rups/target/debug/deps/libunicode_segmentation-e3fd0169850011a0.rlib --cap-lints allow`

error: linking with `cc` failed: exit code: 1

  |

  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/travis/build/NickeZ/rups/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef/build_script_build.0.o" "-o" "/home/travis/build/NickeZ/rups/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef/build_script_build" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/travis/build/NickeZ/rups/target/debug/deps" "-L" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/travis/build/NickeZ/rups/target/debug/deps/libbuild-493a7b0628804707.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1357b93f.rlib" "/home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-1357b93f.rlib" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"

  = note: /usr/bin/ld: /home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib(fileline.o)(.debug_frame+0x6c): reloc against `.debug_frame': error 2

/usr/bin/ld: final link failed: Nonrepresentable section on output

collect2: ld returned 1 exit status

error: aborting due to previous error

Build failed, waiting for other jobs to finish...

error: Could not compile `kernel32-sys`.

Caused by:

  process didn't exit successfully: `rustc /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/kernel32-sys-0.2.2/build.rs --crate-name build_script_build --crate-type bin -g -C metadata=d6afa5bd3d7cfaef --out-dir /home/travis/build/NickeZ/rups/target/debug/build/kernel32-sys-d6afa5bd3d7cfaef --emit=dep-info,link -L dependency=/home/travis/build/NickeZ/rups/target/debug/deps --extern build=/home/travis/build/NickeZ/rups/target/debug/deps/libbuild-493a7b0628804707.rlib --cap-lints allow` (exit code: 101)

The command "cargo test --verbose" exited with 101.

Done. Your build exited with 1.
```

**Comment by nikomatsakis** [comment] 2016-11-16 09:03
I am also seeing this building rayon (or, at least, travis is). A quick google search landed me on this page:
http://stackoverflow.com/questions/1521859/nonrepresentable-section-on-output-error-during-linking-on-linux

**Comment by nikomatsakis** [comment] 2016-11-16 09:10
Marking as a regression.

**Comment by jonas-schievink** [comment] 2016-11-16 09:46
look like #37786 ?

**Comment by alexcrichton** [comment] 2016-11-16 15:22
Thanks for the report @NickeZ! I think this is indeed a dupe of #37786 with the problem [described in detail](https://github.com/rust-lang/rust/issues/37786#issuecomment-260800061) as well as a [fix deployed](https://github.com/rust-lang/rust/issues/37786#issuecomment-260801525). Hopefully in a few hours we'll have a new nightly which fixes these problems!

**Closed by alexcrichton** 2016-11-16 15:22 UTC
Labels: A-linkage, regression-from-stable-to-nightly, T-compiler
