### ISSUE TITLE
#[derive(Clone)] placing Clone bounds on associated types

### ISSUE THREAD

**Issue by iitalics** [rust-lang/rust#54513] opened 2018-09-23 20:42 UTC
With `#[derive(Clone)]`, when we reference an associating type directly, `Clone` correctly places a `Clone` constraint on the associated type, like below:

```rust
trait Tr {
  type AT;
}

// This is fine, it only enables First<T>: Clone when T::AT: Clone
#[derive(Clone)]
struct First<T: Tr> { at: T::AT }
```

However making another type that references this struct causes `#[derive(Clone)]` to complain that the `Clone` constraint on the associated type is not explicitly specified. This is problematic when we want `Clone` to be conditionally available when the associated type is `Clone` (like in `First<T>`)

```rust
// This is an error:
#[derive(Clone)]
struct Second<T: Tr>(First<T>);
```

Error text:
```
error[E0277]: the trait bound `<T as Tr>::AT: std::clone::Clone` is not satisfied
  --> src/lib.rs:10:22
   |
10 | struct Second<T: Tr>(First<T>);
   |                      ^^^^^^^^ the trait `std::clone::Clone` is not implemented for `<T as Tr>::AT`
   |
   = help: consider adding a `where <T as Tr>::AT: std::clone::Clone` bound
   = note: required because of the requirements on the impl of `std::clone::Clone` for `First<T>`
   = note: required by `std::clone::Clone::clone`
```

The suggested workaround makes `Second<T>` too restrictive, since we may want to enable creating instances where `T::AT` is not `Clone`. The only sufficient workaround is to manually implement `Clone` for this type. 

**Expected behavior:** `#[derive(Clone)]` should have been able to generate something like the following implementation:

```rust
impl <T> Clone for Second<T>
where T: Tr, First<T>: Clone {
    fn clone(&self) -> Self {
        Second(self.0.clone())
    }
}
```

**Comment by jonas-schievink** [comment] 2018-09-23 21:50
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Comment by sfackler** [comment] 2018-09-23 22:41
Closing as a dup of that issue.

**Closed** 2018-09-23 22:41 UTC
