### ISSUE TITLE
Disable unused_must_use for statically known bool values

### ISSUE THREAD

**Issue by HKalbasi** [rust-lang/rust#88017] opened 2021-08-13 22:52 UTC
In this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13b6c01bca742a083b0f48fee07b21d3)) compiler with warn `is_prime(x) || continue;` with `unused logical operation that must be used`. However, if we add a `let temp = is_prime(x) || continue;` the `temp` would be always true, if `is_prime(x)` is true it will be short-circuited with true, and otherwise it would be diverge and we will never see anything other than true. It is like warning unused_must_use on `Result<(), !>` which it is always `Ok(())` and using it is pointless. So is it good to turn off this warning? Or current behavior is intended?

I see that this isn't a good code, but unused_must_use isn't a good warning for preventing that. Another warning (probably in clippy) can say that `please don't abuse short circuit operators`.

**Comment by ecstatic-morse** [comment] 2021-08-14 15:54
Duplicate of #69466.

**Comment by Dylan-DPC** [comment] 2023-01-04 14:31
Closing as duplicate

**Closed** 2023-01-04 14:31 UTC
