### ISSUE TITLE
#[inline] is no longer accepted on closures

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#49632] opened 2018-04-04 00:05 UTC
Since #49291 `#[inline]` is no longer accepted on closures, despite the fact that this attribute does have an effect on code generation.

The generated LLVM IR (in debug builds) for this example is different if you remove `#[inline(always)]`:
```rust
#![feature(stmt_expr_attributes)] 
#![crate_type="rlib"]

pub fn main() {
    let x = #[inline(always)] || {};
    x();
}
```

**Comment by sanxiyn** [comment] 2018-04-05 04:36
While I think this should be fixed, this is not exactly a regression, since `stmt_expr_attributes` is unstable and this code never worked on stable.

**Comment by tejom** [comment] 2018-04-06 01:33
I can make a change, since I wrote that original patch. I'm curious if a better change would be to have closures always inlined? That seems like it might have been the expected behavior and the reason why it was suggested to me to write the check like this in the first place?

**Comment by Amanieu** [comment] 2018-04-06 01:37
I believe closures are currently always effectively `#[inline]`. However in some cases I need to force inlining with `#[inline(always)]` even when LLVM thinks it is a bad idea.

**Closed** 2018-04-27 23:32 UTC
Labels: T-compiler
