### ISSUE TITLE
Identifiers in range notation are not parsed correctly

### ISSUE THREAD

**Issue by aepsil0n** [rust-lang/rust#20830] opened 2015-01-09 21:46 UTC
The following example fails to compile currently:

```rust
let a = 3;
for i in 0..a {
    let b = i;
}
```

with
```
<anon>:4:9: 4:12 error: expected identifier, found keyword `let`
<anon>:4         let b = i;
                 ^~~
<anon>:4:13: 4:14 error: expected `:`, found `b`
<anon>:4         let b = i;
```

**Comment by alexcrichton** [comment] 2015-01-09 21:48
cc @nick29581

**Comment by aepsil0n** [comment] 2015-01-09 21:54
btw replacing `0..a` with `(0..a)` or `0..(a)` makes the compiler behave correctly.

**Comment by aepsil0n** [comment] 2015-01-09 22:25
Maybe this sheds some more light on it:

```rust
let a = 3;
for i in 0..a {}
```

Apparently the compiler parses it as `for i in 0..(a {})` interpreting `a {}` as a structure literal.

Error:
```
<anon>:3:19: 3:20 error: structure literal must either have at least one field or use functional structure update syntax
<anon>:3     for i in 0..a {}
                           ^
<anon>:4:1: 4:2 error: expected `{`, found `}`
<anon>:4 }
         ^
<anon>:4:1: 4:2 help: place this code inside a block
<anon>:4 }
         ^
```

**Comment by dgrunwald** [comment] 2015-01-10 00:06
Looks like the parser is replacing the restrictions with `RESTRICTION_NO_DOTS` when parsing the RHS of the range notation, thus deleting the `RESTRICTION_NO_STRUCT_LITERAL`. It should add to the existing restrictions instead of replacing them.

**Comment by huonw** [comment] 2015-01-10 09:50
Closing as a dupe of https://github.com/rust-lang/rust/issues/20241.

**Closed by huonw** 2015-01-10 09:50 UTC
Labels: I-nominated
