### ISSUE TITLE
Syntax context output in --pretty expanded,hygiene doesn't represent linked syntax contexts

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#16420] opened 2014-08-11 12:35 UTC
E.g.

``` rust
#![feature(macro_rules)]
// minimal junk
#![no_std]

macro_rules! foo {
    ($x: ident) => { y + $x }
}

fn bar() {
    let x = 1;
    foo!(x)
}
```

becomes

``` rust
#![feature(macro_rules)]
// minimal junk
#![no_std]


fn bar /* 61#0 */() { let x /* 58#2 */ = 1; y /* 60#4 */ + x /* 58#5 */ }
```

Specifically, the syntax contexts of `x /* 58#2 */` and `x /* 58#5 */` are linked (the `x`s refer to the same identifier, even with hygiene) but this is not represented in the output at all, so one might interpret them as being distinct identifiers.

**Comment by steveklabnik** [comment] 2016-02-02 21:52
There is no more pretty=hygene, was it replaced with something?

**Comment by Mark-Simulacrum** [comment] 2017-04-29 13:32
Closing. `pretty=hygiene` is apparently no longer a thing, and the output looks sufficiently different with `pretty=expanded,identified` that I don't think it's the same.

**Comment by Eh2406** [comment] 2017-09-06 01:26
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/librustc_driver/pretty.rs#L459
Now that the issue is closed can the FIXME be fix, or made more specific?

**Comment by Mark-Simulacrum** [comment] 2017-09-06 02:18
Looks like `pretty=expanded,hygiene` is a thing though so reopening... output today is below. I'm not completely sure whether this is fixed or not --- the output looks the same for the two `x`s, I guess? Not sure which are being referred to either...

```
error[E0425]: cannot find value `y` in this scope
  --> test.rs:5:22
   |
5  |     ($x: ident) => { y + $x }
   |                      ^ did you mean `x`?
...
10 |     foo!(x)
   |     ------- in this macro invocation

#![feature(prelude_import)]
#![no_std]
// minimal junk
#![no_std]
#[prelude_import]
use core /* 94#0 */::prelude /* 98#0 */::v1 /* 99#0 */::*;
#[macro_use]
extern crate core /* 94 */ as core /* 94#0 */;

macro_rules! foo /* 87#0 */(( $ x : ident ) => { y + $ x });

fn bar /* 91#0 */() { let x /* 88#0 */ = 1; y /* 90#2 */ + x /* 88#0 */ }
error: aborting due to previous error
```

**Closed** 2019-09-18 08:41 UTC
Labels: A-pretty, C-bug, T-compiler
