### ISSUE TITLE
`measureme` flame graphs have lots of missing info

### ISSUE THREAD

**Issue by icefoxen** [rust-lang/rust#65788] opened 2019-10-25 02:31 UTC
From the "Where rustc spends its time" article, I got a [request](https://www.reddit.com/r/rust/comments/dlk3fj/article_where_rustc_spends_its_time/f4r5oen?utm_source=share&utm_medium=web2x) to make a bug report.  So, here it is.  This is not a terribly *minimal* reproduction, unfortunately, but hopefully it's still useful for someone.

Basically, the flame graph produced from the results of `measureme`'s `stack_collapse` seem to have a big pile of missing stuff, and so look like this: https://alopex.li/data/images/ggraphics_flame.svg with nearly 50% of the time unaccounted for.  The thing I was building was this project:  https://github.com/ggez/ggraphics/ commit aacc2ac152c42c4289559076066f2ffe4745f775 .  This *seems* like an output bug of some kind or another, since the chart produced by `summarize` has more like 90+% of the time listed in the first few rows, which I didn't realize at the time.

Just let me know if you need anything else!

**Comment by andjo403** [comment] 2019-11-04 19:34
I think that the problem is in the handling of threads in the measureme tool
stack-collapse.
the reason that I think so is due to when I compare with the output from crox the missing data is from codegen of the create.

**Comment by wesleywiser** [comment] 2020-01-15 17:06
As far as we know, this was fixed in rust-lang/measureme#74. If you see this again, feel free to reopen this issue or create a new issue.

**Closed by wesleywiser** 2020-01-15 17:06 UTC
Labels: A-self-profile, C-bug, T-compiler
