### ISSUE TITLE
ICE with closure destructuring &str

### ISSUE THREAD

**Issue by dikaiosune** [rust-lang/rust#32943] opened 2016-04-13 20:50 UTC
When using `.iter().all(|(&&_, &_) do_stuff())` on the current nightly (2016-04-11), I get ICE. Details below.

Somewhat reduced test case:

```rust
use std::collections::BTreeMap;

fn main() {
    let mut m = BTreeMap::new();
    m.insert("a", true);
    let b = m.iter().all(|(&&_, &_)| true);
}
```

## Meta

I ran the above test case on playpen today, saw error on stable, beta, and nightly.

Backtrace:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: rows.iter().all(|r| r.len() == v.len())', ../src/librustc_const_eval/check_match.rs:690
stack backtrace:
   1:     0x7fb2cb909280 - std::sys::backtrace::tracing::imp::write::h714760a4c8c0cdd8
   2:     0x7fb2cb9169ab - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hff309ab1d83ffd90
   3:     0x7fb2cb91654c - std::panicking::default_hook::h08ad3bb09872855b
   4:     0x7fb2cb8db47f - std::sys_common::unwind::begin_unwind_inner::h406d5f1a330b854b
   5:     0x7fb2c5daa00f - std::sys_common::unwind::begin_unwind::h51df842978a11a26
   6:     0x7fb2c5ddc37a - rustc_const_eval::check_match::is_useful::hc33a46f7866b38ac
   7:     0x7fb2c5dfcaf3 - rustc_const_eval::check_match::is_useful_specialized::hfc72454076a1edd9
   8:     0x7fb2c5dfbd01 - rustc_const_eval::check_match::is_useful::_$u7b$$u7b$closure$u7d$$u7d$::h6d9c729c9396266f
   9:     0x7fb2c5dfb73d - _<std..option..Option<T>>::map::h3563068c47f84b8c
  10:     0x7fb2c5ddcd6a - rustc_const_eval::check_match::is_useful::hc33a46f7866b38ac
  11:     0x7fb2c5dfcaf3 - rustc_const_eval::check_match::is_useful_specialized::hfc72454076a1edd9
  12:     0x7fb2c5dfbd01 - rustc_const_eval::check_match::is_useful::_$u7b$$u7b$closure$u7d$$u7d$::h6d9c729c9396266f
  13:     0x7fb2c5dfb73d - _<std..option..Option<T>>::map::h3563068c47f84b8c
  14:     0x7fb2c5ddcd6a - rustc_const_eval::check_match::is_useful::hc33a46f7866b38ac
  15:     0x7fb2c5dfcaf3 - rustc_const_eval::check_match::is_useful_specialized::hfc72454076a1edd9
  16:     0x7fb2c5dfbd01 - rustc_const_eval::check_match::is_useful::_$u7b$$u7b$closure$u7d$$u7d$::h6d9c729c9396266f
  17:     0x7fb2c5dfb73d - _<std..option..Option<T>>::map::h3563068c47f84b8c
  18:     0x7fb2c5ddcd6a - rustc_const_eval::check_match::is_useful::hc33a46f7866b38ac
  19:     0x7fb2c5e00511 - rustc_const_eval::check_match::check_irrefutable::h4fe8685f7f250537
  20:     0x7fb2c5dd7fb0 - rustc_const_eval::check_match::check_fn::h46ce2a204bd4b692
  21:     0x7fb2c5dd515f - rustc_const_eval::check_match::check_expr::h84eca896bbe3e8d5
  22:     0x7fb2c5dd4dbf - rustc_const_eval::check_match::check_expr::h84eca896bbe3e8d5
  23:     0x7fb2c5dd7c8f - rustc_const_eval::check_match::check_local::h65f1ceaca4b31650
  24:     0x7fb2c5dd7f57 - rustc_const_eval::check_match::check_fn::h46ce2a204bd4b692
  25:     0x7fb2c5dd84e9 - rustc_const_eval::check_match::check_crate::h957128f3ce29308a
  26:     0x7fb2cbe5b014 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::h8148bf3bd7eb17b2
  27:     0x7fb2cbe57c1b - rustc::ty::context::TyCtxt::create_and_enter::h963727672a0d2ef1
  28:     0x7fb2cbe546ce - rustc_driver::driver::phase_3_run_analysis_passes::h035bf2dff707c080
  29:     0x7fb2cbe26f1f - rustc_driver::driver::compile_input::h650fe5b01cb8d74d
  30:     0x7fb2cbe0d464 - rustc_driver::run_compiler::h68d23e0e9b7b247d
  31:     0x7fb2cbe0a8c1 - std::sys_common::unwind::try::try_fn::h67fde221a73148bc
  32:     0x7fb2cb906a1b - __rust_try
  33:     0x7fb2cb9069ad - std::sys_common::unwind::inner_try::h4e97625a08807651
  34:     0x7fb2cbe0b10a - _<F as std..boxed..FnBox<A>>::call_box::hc8936fa120642c49
  35:     0x7fb2cb914b44 - std::sys::thread::Thread::new::thread_start::h74af400293164137
  36:     0x7fb2c37fe423 - start_thread
  37:     0x7fb2cb573cbc - clone
  38:                0x0 - <unknown>

playpen: application terminated with error code 101
```

**Comment by alexcrichton** [comment] 2016-04-13 20:52
cc @oli-obk

**Comment by alexcrichton** [comment] 2016-04-13 20:53
Looks like this isn't a regression though, so at least that's good!

**Comment by oli-obk** [comment] 2016-04-15 07:11
smaller test-case: `let (&&_, &_) = (&"a", &true);`

**Comment by arielb1** [comment] 2016-04-15 08:08
duplicate of #30240. I am working on a fix.

**Closed by arielb1** 2016-04-15 08:08 UTC
Labels: I-ICE
