### ISSUE TITLE
Compilation error introduced by new nightly version

### ISSUE THREAD

**Issue by thedewpoint** [rust-lang/rust#78635] opened 2020-11-01 17:50 UTC
This application is compiling using nightly version 1.49.0-nightly (ffa2e7ae8 2020-10-24)

### Code
Link to repo https://github.com/thedewpoint/expense-api
running the docker image using
docker build --pull --rm -f "expense-api/Dockerfile" -t expenseapi:latest "expense-api"

### Error output

```
Compiling trust-dns-proto v0.19.5
     Running `rustc --crate-name trust_dns_proto --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.19.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="tokio"' --cfg 'feature="tokio-runtime"' -C metadata=958c3b2f2c8ed6a5 -C extra-filename=-958c3b2f2c8ed6a5 --out-dir /usr/src/expense-api/target/release/deps -L dependency=/usr/src/expense-api/target/release/deps --extern async_trait=/usr/src/expense-api/target/release/deps/libasync_trait-39a267d90fb7baf6.so --extern backtrace=/usr/src/expense-api/target/release/deps/libbacktrace-461a90f97ceeda4e.rmeta --extern enum_as_inner=/usr/src/expense-api/target/release/deps/libenum_as_inner-869d709b2ab8c0df.so --extern futures=/usr/src/expense-api/target/release/deps/libfutures-6587ed04b264aa60.rmeta --extern idna=/usr/src/expense-api/target/release/deps/libidna-9b1d5b853f8f38b8.rmeta --extern lazy_static=/usr/src/expense-api/target/release/deps/liblazy_static-72fd4c50b9d3882e.rmeta --extern log=/usr/src/expense-api/target/release/deps/liblog-fe5eb1ec3d35d5a3.rmeta --extern rand=/usr/src/expense-api/target/release/deps/librand-e57af17df0797c18.rmeta --extern smallvec=/usr/src/expense-api/target/release/deps/libsmallvec-635254589d323286.rmeta --extern thiserror=/usr/src/expense-api/target/release/deps/libthiserror-a0de7fa3b2716d1f.rmeta --extern tokio=/usr/src/expense-api/target/release/deps/libtokio-0174de5c65a2ba40.rmeta --extern url=/usr/src/expense-api/target/release/deps/liburl-53ff79082acc4c48.rmeta --cap-lints allow`
error: internal compiler error: compiler/rustc_mir_build/src/thir/pattern/_match.rs:931:18: trying to compare incompatible constructors Single and Str(Const { ty: &str, val: Value(Slice { data: Allocation { bytes: [105, 115, 115, 117, 101], relocations: Relocations(SortedMap { data: [] }), init_mask: InitMask { blocks: [31], len: Size { raw: 5 } }, size: Size { raw: 5 }, align: Align { pow2: 0 }, mutability: Not, extra: () }, start: 0, end: 5 }) })

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:942:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (ffe52882e 2020-10-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_match] match-checking `<rr::rdata::caa::Property as std::convert::From<std::string::String>>::from`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `trust-dns-proto`

Caused by:
  process didn't exit successfully: `rustc --crate-name trust_dns_proto --edition=2018 /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.19.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="tokio"' --cfg 'feature="tokio-runtime"' -C metadata=958c3b2f2c8ed6a5 -C extra-filename=-958c3b2f2c8ed6a5 --out-dir /usr/src/expense-api/target/release/deps -L dependency=/usr/src/expense-api/target/release/deps --extern async_trait=/usr/src/expense-api/target/release/deps/libasync_trait-39a267d90fb7baf6.so --extern backtrace=/usr/src/expense-api/target/release/deps/libbacktrace-461a90f97ceeda4e.rmeta --extern enum_as_inner=/usr/src/expense-api/target/release/deps/libenum_as_inner-869d709b2ab8c0df.so --extern futures=/usr/src/expense-api/target/release/deps/libfutures-6587ed04b264aa60.rmeta --extern idna=/usr/src/expense-api/target/release/deps/libidna-9b1d5b853f8f38b8.rmeta --extern lazy_static=/usr/src/expense-api/target/release/deps/liblazy_static-72fd4c50b9d3882e.rmeta --extern log=/usr/src/expense-api/target/release/deps/liblog-fe5eb1ec3d35d5a3.rmeta --extern rand=/usr/src/expense-api/target/release/deps/librand-e57af17df0797c18.rmeta --extern smallvec=/usr/src/expense-api/target/release/deps/libsmallvec-635254589d323286.rmeta --extern thiserror=/usr/src/expense-api/target/release/deps/libthiserror-a0de7fa3b2716d1f.rmeta --extern tokio=/usr/src/expense-api/target/release/deps/libtokio-0174de5c65a2ba40.rmeta --extern url=/usr/src/expense-api/target/release/deps/liburl-53ff79082acc4c48.rmeta --cap-lints allow` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `expense-api v0.1.0 (/usr/src/expense-api)`, intermediate artifacts can be found at `/usr/src/expense-api/target`

Caused by:
  build failed
The command '/bin/sh -c cargo install --locked --verbose --path .' returned a non-zero code: 101
```

**Comment by jonas-schievink** [comment] 2020-11-01 17:53
Duplicate of https://github.com/rust-lang/rust/issues/78549

**Closed by jonas-schievink** 2020-11-01 17:53 UTC
Labels: C-bug, I-ICE, T-compiler
