### ISSUE TITLE
rustdoc table of content

### ISSUE THREAD

**Issue by Zenthae** [rust-lang/rust#80858] opened 2021-01-09 23:22 UTC
i know that it was already discussed before but i believe that it as more weight now since the language got quite a bit improved since then, lot of crate now have extensive documentation and it's quite tedious to read through them, so i think making rustdoc automatically generate a table of content on each page is a need (maybe having an inline comment to disable it on some page could be a good idea (for small pages)).

For the where to put it, i still have a lot of space available on the right side of the pages, (at least on my screen resolution) and for smaller screen it can be put at the beginning, as for what to use as title, i think just using the already parsed markdown headers with just a bit of indentation depending of the weight and it should be enough.

**Comment by jyn514** [comment] 2021-01-10 03:00
Duplicate of https://github.com/rust-lang/rust/issues/40273 and https://github.com/rust-lang/rust/issues/14475.

**Closed by jyn514** 2021-01-10 03:00 UTC

**Comment by Zenthae** [comment] 2022-05-17 17:22
more like the table of content of this readme

https://github.com/jonschlinkert/markdown-toc

**Comment by mightyiam** [comment] 2022-05-18 06:45
Well, that's just a different implementation. The point is this: this is a table of contents generated from the headings of a page.
It's not about the public items such as modules, functions and traits.

And I'd like this as well.

@jyn514 ?

**Comment by mightyiam** [comment] 2023-02-18 07:47
Here's what I have to do to implement this in my crate:
https://github.com/mobusoperandi/michie/blob/f2167bc6a0f835e2056dc7c47601db542123c737/Makefile.toml#L59-L66

And here's how I enforce that it is up-to-date:

https://github.com/mobusoperandi/michie/blob/f2167bc6a0f835e2056dc7c47601db542123c737/Makefile.toml#L14-L18

https://github.com/mobusoperandi/michie/blob/f2167bc6a0f835e2056dc7c47601db542123c737/Makefile.toml#L68-L76

**Comment by mightyiam** [comment] 2023-08-25 14:22
@jyn514 could you perhaps consider that this is a a different feature "request"?
