### ISSUE TITLE
Improve error message when moving out of a &-reference

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#15457] opened 2014-07-05 19:17 UTC
It would be nice if the following error message 

```
test.rs:7:9: 7:13 error: cannot move out of dereference of `&`-pointer
test.rs:7         self.option.map(|x| x)
                  ^~~~
error: aborting due to previous error
```

would give a hint why exactly something was moved in the following code

```
struct Type {
    option: Option<Vec<u8>>
}

impl Type {
    fn method(&self) -> Option<Vec<u8>> {
        self.option.map(|x| x)
    }
}

fn main() {
    let _ = Type { option: None }.method();
}
```

Ideally "map takes option by value" or something like that.

**Comment by estebank** [comment] 2017-12-14 19:57
Also reported in https://github.com/rust-lang/rust/issues/25507#issuecomment-262564469

**Comment by estebank** [comment] 2019-02-07 14:45
Possible final output:

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:7:9
6 |    fn method(&self) -> Option<Vec<u8>> {
  |              ----- `self` is borrowed here
7 |        self.option.map(|x| x)
  |        ^^^^^^^^^^^ --- `map` consumes `self.option` here, moving it
  |        |
  |        cannot move out of borrowed content
```

**Comment by estebank** [comment] 2019-05-25 02:35
Output with #61147 applied:

```
error[E0507]: cannot move out of borrowed content
 --> file2.rs:7:9
  |
7 |         self.option.map(|x| x)
  |         ^^^^^^^^^^^
  |         |
  |         cannot move out of borrowed content
  |         help: consider borrowing the `Option`'s content: `self.option.as_ref()`

```

If applying the suggestion, we'll emit

```
error[E0308]: mismatched types
 --> file2.rs:7:9
  |
6 |     fn method(&self) -> Option<Vec<u8>> {
  |                         --------------- expected `std::option::Option<std::vec::Vec<u8>>` because of return type
7 |         self.option.as_ref().map(|x| x)
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::vec::Vec`, found reference
  |
  = note: expected type `std::option::Option<std::vec::Vec<u8>>`
             found type `std::option::Option<&std::vec::Vec<u8>>`
```

**Comment by estebank** [comment] 2019-10-02 18:20
Current output:

```
error[E0507]: cannot move out of `self.option` which is behind a shared reference
 --> src/main.rs:7:9
  |
7 |         self.option.map(|x| x)
  |         ^^^^^^^^^^^
  |         |
  |         move occurs because `self.option` has type `std::option::Option<std::vec::Vec<u8>>`, which does not implement the `Copy` trait
  |         help: consider borrowing the `Option`'s content: `self.option.as_ref()`
```

**Comment by rylev** [comment] 2021-07-05 09:57
Triage: no change [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=06432a402731d79d7955d991d5b7826b).

I believe the original suggestion of pointing to `map` as taking `self` and thus trying to move out of a `&self` is the right way to go to close this issue.

**Comment by ibraheemdev** [comment] 2021-07-27 16:40
Duplicate of #43161

**Comment by TimJentzsch** [comment] 2022-08-11 13:51
Current output with `1.65.0-nightly (2022-08-10 29e4a9ee0253cd39e552)`

```rust
struct Type {
    option: Option<Vec<u8>>
}

impl Type {
    fn method(&self) -> Option<Vec<u8>> {
        self.option.as_ref().map(|x| x)
    }
}

fn main() {
    let _ = Type { option: None }.method();
}
```

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:7:9
  |
6 |     fn method(&self) -> Option<Vec<u8>> {
  |                         --------------- expected `Option<Vec<u8>>` because of return type
7 |         self.option.as_ref().map(|x| x)
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Vec`, found `&Vec<u8>`
  |
  = note: expected enum `Option<Vec<u8>>`
             found enum `Option<&Vec<u8>>`
```

**Comment by estebank** [comment] 2023-01-08 07:51
Current output

```
error[E0308]: mismatched types
 --> src/main.rs:7:9
  |
6 |     fn method(&self) -> Option<Vec<u8>> {
  |                         --------------- expected `Option<Vec<u8>>` because of return type
7 |         self.option.as_ref().map(|x| x)
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Vec`, found `&Vec<u8>`
  |
  = note: expected enum `Option<Vec<u8>>`
             found enum `Option<&Vec<u8>>`
help: use `Option::cloned` to clone the value inside the `Option`
  |
7 |         self.option.as_ref().map(|x| x).cloned()
  |                                        +++++++++
```

```
error[E0507]: cannot move out of `self.option` which is behind a shared reference
 --> src/main.rs:7:9
  |
7 |         self.option.map(|x| x)
  |         ^^^^^^^^^^^ ---------- `self.option` moved due to this method call
  |         |
  |         help: consider calling `.as_ref()` or `.as_mut()` to borrow the type's contents
  |         move occurs because `self.option` has type `Option<Vec<u8>>`, which does not implement the `Copy` trait
  |
note: `Option::<T>::map` takes ownership of the receiver `self`, which moves `self.option`
 --> /rustc/ee0412d1ef81efcfabe7f66cd21476ca85d618b1/library/core/src/option.rs:963:28
help: you can `clone` the value and consume it, but this might not be your desired behavior
  |
7 |         self.option.clone().map(|x| x)
  |                     ++++++++
```

**Closed by estebank** 2023-01-08 07:51 UTC
Labels: C-enhancement, A-diagnostics, T-compiler, E-needs-mentor, WG-diagnostics
