### ISSUE TITLE
Panic within syntax extension triggers ICE

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#17507] opened 2014-09-24 08:31 UTC
This code ICEs when the function in the crate `x`, marked with `#[plugin_registrar]` panics:

```
/// Crate x
#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
    panic!()
}

/// Another crate
#[phase(plugin)] extern crate x;
```

This code ICEs when the macro expansion fails

```
/// Crate x
#[plugin_registrar]
pub fn plugin_registrar(reg: &mut Registry) {
    reg.register_macro("wrong", expand);
}

fn expand(cx: &mut ExtCtxt, sp: codemap::Span, tts: &[ast::TokenTree]) -> Box<MacResult + 'static> {
    panic!()
}

/// Another crate
wrong!()
```

It would be nice to tell the user that the plugin registrar has panicked or that the macro expansion has panicked, respectively.

If there is a simple way to "catch" a `panic!` I would like to hear about it and fix this.

**Comment by steveklabnik** [comment] 2015-01-16 22:20
> If there is a simple way to "catch" a fail! I would like to hear about it and fix this.

There is no way to catch a `panic!`, by design. It ends the current `Thread`. So, the only way to fix this kind of thing would be to run each plugin in its own thread...

**Comment by kmcallister** [comment] 2015-01-16 22:25
Which would require major changes throughout rustc, as I understand it.

We could instead have a global flag that tells the existing panic handler what context rustc was in at the time of panic, e.g. built-in code or the name of a plugin.  We'd print this in the message and maybe use it to be more equivocal about whether to report the bug (kind of like Linux's taint bits).

**Comment by jakub-** [comment] 2015-04-16 11:57
I'm going to close this as a subissue of https://github.com/rust-lang/rust/issues/15509. Please yell or open if you disagree.

**Closed by jakub-** 2015-04-16 11:57 UTC
Labels: I-ICE
