### ISSUE TITLE
incorrect integer comparison in release build

### ISSUE THREAD

**Issue by adfernandes** [rust-lang/rust#116913] opened 2023-10-19 00:00 UTC
The following code is well-formed, as far as I can tell:

```rust
fn main() {
    let a = {
        let v = 0;
        &v as *const _ as usize
    };
    let b = {
        let v = 0;
        &v as *const _ as usize
    };
    println!("{a:?} == {b:?} evaluates to {}", a==b);
    println!("{a:?} == {b:?} evaluates to {}", a==b);
}
```
For **debug** builds, we see the expected output, where the two `println!` macros output the same string:
```
$ cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rust-bug-addr-scope`
140734029226756 == 140734029226772 evaluates to false
140734029226756 == 140734029226772 evaluates to false
```

However, for **release** builds, the second line no longer matches the first:
```
$ cargo run --release
    Finished release [optimized] target(s) in 0.00s
     Running `target/release/rust-bug-addr-scope`
140735084703752 == 140735084703752 evaluates to false
140735084703752 == 140735084703752 evaluates to true
```

[Rust Playground Link](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=dd5cd8fb7a11b730fa9f749b2c69997a)

Since both `a` and `b` are _integer_ constants, it should not matter that the variable pointed to goes out of scope.

I would expect that the `release` build gives identical output to the `debug` output.

**Note** that both `evaluates to true` and `evaluates to false` are acceptable.

However, the `release` build is implying that two identical integers can *mis-compare*, in that the boolean `a==b` is not constant!

### Meta

Occurs on **both** `x86_64-unknown-linux-gnu` and `aarch64-unknown-linux-gnu`.

`rustc --version --verbose`:
```
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 22.04 (jammy) [64-bit]
```
and
```
cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: aarch64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 20.04 (focal) [64-bit]
```

**Comment by fmease** [comment] 2023-10-19 01:18
Potential duplicate of #107975.

**Comment by Nilstrieb** [comment] 2023-10-19 06:03
closing as duplicate

**Closed by Nilstrieb** 2023-10-19 06:03 UTC
Labels: C-bug, needs-triage

**Comment by DoubleHyphen** [comment] 2023-10-19 16:20
Out of curiosity, what thought process led you to this bug?

**Comment by adfernandes** [comment] 2023-10-19 22:11
A colleague who dislikes rust sent it to me as an example of "memory unsafety" in rust, without realizing that it was a compiler bug.

I will admit, it took me discussing it with several friends before I started to realize it was _surely_ a compiler bug, esp with respect to the optimizer.

(In a past life I had many a shouting match, err, I mean "spirited discussion" with people who didn't realize just how dangerous things like `-ffast-math` _really_ are!)

**Anyhow**

From a `C / C++` perspective, this bug doesn't worry me too much because the [`C` repro'](https://github.com/llvm/llvm-project/issues/45725#issuecomment-1643796019) in upstream LLVM would be a relatively uncommon construction in C.

**However**, writing an idiom that triggers this bug would _not_ be uncommon in **embedded** rust, which is my primary interest!

**Comment by Nilstrieb** [comment] 2023-10-20 05:20
ferrocene is aware of all I-unsound issues already

**Comment by adfernandes** [comment] 2023-10-20 05:45
Ah! Was hoping that would be the case… cheers!

**Comment by DoubleHyphen** [comment] 2023-10-23 12:27
> A colleague who dislikes rust sent it to me as an example of "memory unsafety" in rust, without realizing that it was a compiler bug.

I'll admit that I find this curious, as this bug is rather niche. For a person who “dislikes Rust”, your colleague is oddly knowledgeable.

**Comment by adfernandes** [comment] 2023-10-23 17:55
> For a person who “dislikes Rust”, your colleague is oddly knowledgeable.

Yeah, that's an interesting story. My colleague is a _phenomenal_ C++ coder... the type of person who not only knows the standard, but understands the _reasoning_ behind the standard. So... very bright and thoughtful.

Unfortunately, they had the misfortune of working somewhere that decided to cargo-cult Rust for "safety". You know the attitude, I suspect: _"Build it in Rust, and it will be safe and secure!"_ Said colleague then had a very miserable time as the company shoehorned really bad software and really bad practices into Rust, believing that The One True Language would save them from themselves.

This appears to have left them very sour on Rust.

For what it's worth, I have _several_ friends and colleagues that work at companies that have experimented (poorly) with Rust. The common experience seems to be that they end up with the unholy combination of shoehorned-in C-like constructs **and** drag-down, knock-em-down fights with the borrow checker! The worst of both worlds!

I kind-of understand this, because I enjoyed writing Java for many years _before_ getting introduced to (now lampoon-able) "Enterprise Java". _These days_ I don't care how great Java is _in theory_... I'd rather jump off of a cliff than touch it. "Once burned, twice shy" and all that.

So what I suspect is happening is that many of my corporate-software-developer friends are doing the equivalent of "trying to learn Fortran by writing a full-stack modern web app", having a miserable experience, and then reverting via Stockholm Syndrome to PHP, where they are comfortable.

Make sense?

_And yes, I know that people have written a web framework in Fortran..._ :laughing:

**Comment by DoubleHyphen** [comment] 2024-02-08 14:49
> > For a person who “dislikes Rust”, your colleague is oddly knowledgeable.
> 
> Yeah, that's an interesting story. My colleague is a _phenomenal_ C++ coder... the type of person who not only knows the standard, but understands the _reasoning_ behind the standard. So... very bright and thoughtful.
> 
> Unfortunately, they had the misfortune of working somewhere that decided to cargo-cult Rust for "safety". You know the attitude, I suspect: _"Build it in Rust, and it will be safe and secure!"_ Said colleague then had a very miserable time as the company shoehorned really bad software and really bad practices into Rust, believing that The One True Language would save them from themselves.
> 
> This appears to have left them very sour on Rust.
> 
> For what it's worth, I have _several_ friends and colleagues that work at companies that have experimented (poorly) with Rust. The common experience seems to be that they end up with the unholy combination of shoehorned-in C-like constructs **and** drag-down, knock-em-down fights with the borrow checker! The worst of both worlds!
> 
> I kind-of understand this, because I enjoyed writing Java for many years _before_ getting introduced to (now lampoon-able) "Enterprise Java". _These days_ I don't care how great Java is _in theory_... I'd rather jump off of a cliff than touch it. "Once burned, twice shy" and all that.
> 
> So what I suspect is happening is that many of my corporate-software-developer friends are doing the equivalent of "trying to learn Fortran by writing a full-stack modern web app", having a miserable experience, and then reverting via Stockholm Syndrome to PHP, where they are comfortable.
> 
> Make sense?
> 
> _And yes, I know that people have written a web framework in Fortran..._ 😆

This does make sense. Still, I saw the C reproduction to which you linked, and… it appears oddly verbose, somehow. [This](https://github.com/rust-lang/rust/issues/107975#issuecomment-1430429347) is all that's needed to reproduce the bug:

```c
#include <stdio.h>
#include <stdint.h>

int main(void) {
    uintptr_t a;
    uintptr_t b;

    {
        int v[2] = {0, 0};
        a = (uintptr_t)&(v[0]);
    }

    {
        int v[2] = {0, 0};
        b = (uintptr_t)&(v[0]);
    }

    printf("%ld ==/^ %ld is %d, %ld\n", a, b, a == b, a ^ b);
    a ^= 1, b ^= 1;
    printf("%ld ==/^ %ld is %d, %ld\n", a, b, a == b, a ^ b);

    return 0;
}
```

As long as optimisations are enabled, this bug reproduces in both C and C++, in both `gcc` and `clang`. With that in mind, how likely is it that you'd hit this bug in embedded Rust but not in embedded C/C++?
