### ISSUE TITLE
[regression] stdsimd has started failing to link on travis x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#56153] opened 2018-11-22 08:44 UTC
The error is:

```
  = note: C:\Users\travis\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o:crtexe.c:(.rdata$.refptr.__onexitbegin[.refptr.__onexitbegin]+0x0): undefined reference to `__onexitbegin'
          C:\Users\travis\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-gnu\lib\crt2.o:crtexe.c:(.rdata$.refptr.__onexitend[.refptr.__onexitend]+0x0): undefined reference to `__onexitend'
          collect2.exe: error: ld returned 1 exit status
```

This was working before. Started failing around last week. See, e.g., https://travis-ci.org/rust-lang-nursery/stdsimd/jobs/457099080

**Comment by nagisa** [comment] 2019-10-01 00:19
Duplicate of #49078

**Closed** 2019-10-01 00:20 UTC
Labels: A-linkage, T-compiler
