### ISSUE TITLE
Suggest possible traits when none are imported

### ISSUE THREAD

**Issue by nick29581** [rust-lang/rust#20784] opened 2015-01-09 01:37 UTC
When we have `e.foo()` and there is an error because we can't find an implementation of `foo` we should search for any traits which include `foo` and suggest that the user might `use` one of those.

**Comment by huonw** [comment] 2015-01-09 01:43
Dupe of https://github.com/rust-lang/rust/issues/7643.

**Closed by huonw** 2015-01-09 01:43 UTC
Labels: A-diagnostics, A-traits
