### ISSUE TITLE
panic without stack info T..T

### ISSUE THREAD

**Issue by mybee** [rust-lang/rust#86570] opened 2021-06-23 07:01 UTC
thread panicked while panicking. aborting.
error: test failed, to rerun pass '--test article'

Caused by:
  process didn't exit successfully: `/Users/fengma/Desktop/drepo/target/debug/deps/article-46d67a674ecc1092 test_article` (signal: 4, SIGILL: illegal instruction)

**Comment by jfrimmel** [comment] 2021-06-23 07:31
The panic message tells it: while handling a (first) panic, a second panic occurs while unwinding. This is most likely caused by a `Drop` implementation called during unwinding of the first panic, which in turn panics again.

Rust aborts on double panic, to prevent even more bad things to happen.

Without the code one can only say, that this is expected behavior.

**Comment by fee1-dead** [comment] 2021-06-23 08:20
This is probably expected. You should provide a minimal, complete and verifiable example if you think otherwise.

**Comment by nagisa** [comment] 2021-06-23 11:07
Closing for reasons described in the 2 comments above.

**Closed by nagisa** 2021-06-23 11:07 UTC
