### ISSUE TITLE
Unhelpful diagnostic: 'expected `X<'_>`, found `X<'_>`'

### ISSUE THREAD

**Issue by cole-miller** [rust-lang/rust#81446] opened 2021-01-27 18:21 UTC
Compiling this code on stable/beta/nightly ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f948f226c1434f2323433f44e0978197)):

```rust
struct X<'x> {
    x: &'x str,
}

trait B {
    fn new(x: X) -> Self;
}

struct S<'x> {
    x: X<'x>,
}

impl<'x> B for S<'x> {
    fn new(x: X) -> S<'x> {
        S { x }
    }
}

```

correctly results in an error, but part of the diagnostic is less than helpful:

```text
   = note: expected `X<'_>`
              found `X<'_>`
```

<details>
<summary>click for full error text</summary>

```text
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'x` due to conflicting requirements
  --> src/lib.rs:15:9
   |
15 |         S { x }
   |         ^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 14:5...
  --> src/lib.rs:14:5
   |
14 |     fn new(x: X) -> S<'x> {
   |     ^^^^^^^^^^^^^^^^^^^^^
note: ...so that the expression is assignable
  --> src/lib.rs:15:13
   |
15 |         S { x }
   |             ^
   = note: expected `X<'_>`
              found `X<'_>`
note: but, the lifetime must be valid for the lifetime `'x` as defined on the impl at 13:6...
  --> src/lib.rs:13:6
   |
13 | impl<'x> B for S<'x> {
   |      ^^
note: ...so that the expression is assignable
  --> src/lib.rs:15:9
   |
15 |         S { x }
   |         ^^^^^^^
   = note: expected `S<'x>`
              found `S<'_>`
```
</details>

It seems like either this `note` should have some detail indicating what the difference between the expected and found conditions is, or it should be left out entirely, because currently it's not providing any information at all.

Reported on URLO [here](https://users.rust-lang.org/t/trait-impl-lifetime-nightmare/54735).

(Sorry if this is a duplicate, I don't know how to search effectively for previous reports of the same thing.)

**Comment by jyn514** [comment] 2021-01-29 21:27
Duplicate of https://github.com/rust-lang/rust/issues/75791

**Closed by jyn514** 2021-01-29 21:27 UTC
Labels: C-bug
