### ISSUE TITLE
regression in regionck / lifetime elision - "`T` may not live enough" errors

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#23136] opened 2015-03-07 02:53 UTC
### STR

This is an extract from [linalg.rs](https://github.com/japaric/linalg.rs/tree/19acc2c45861d3747f40763bfc3e5b921cc7f5cb) (sorry, it's a bit long)

``` rust
pub mod strided {
    use raw;

    pub struct Slice<'a, T>(pub raw::Slice<'a, T>) where T: 'a;
    impl<'a, T> Copy for Slice<'a, T> {}
    pub struct SliceMut<'a, T>(pub raw::Slice<'a, T>) where T: 'a;
}

pub mod raw {
    use std::marker::PhantomData;

    pub struct Slice<'a, T> where T: 'a {
        _marker: PhantomData<&'a T>,
        data: *mut T,
        len: usize,
    }

    impl<'a, T> Copy for Slice<'a, T> {}
}

pub struct MutRow<'a, T>(strided::SliceMut<'a, T>) where T: 'a;
pub struct Row<'a, T>(strided::Slice<'a, T>) where T: 'a;
impl<'a, T> Copy for Row<'a, T> {}
pub struct Scaled<T, M>(T, M);

#[cfg(yesterday)]
impl<'a, 'b, T> AddAssign<Scaled<T, Row<'a, T>>> for MutRow<'b, T> {
    fn add_assign(&mut self, rhs: &Scaled<T, Row<T>>) {
        let &mut MutRow(strided::SliceMut(lhs)) = self;
        let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;

        axpy(lhs, alpha, rhs)
    }
}

#[cfg(today)]
impl<'a, 'b, T> AddAssign<Scaled<T, Row<'a, T>>> for MutRow<'b, T>
    where T: 'a,  // <--
{
    fn add_assign(&mut self, rhs: &Scaled<T, Row<'a, T>>) {  // <-- `Row<['a], T>`
        let &mut MutRow(strided::SliceMut(lhs)) = self;
        let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;

        axpy(lhs, alpha, rhs)
    }
}

fn axpy<T>(_: raw::Slice<T>, _: &T, _: raw::Slice<T>) {}

pub trait AddAssign<Rhs> {
    fn add_assign(&mut self, &Rhs);
}

fn main() {}
```

### Stderr

``` rust
bug.rs:31:60: 31:63 error: the parameter type `T` may not live long enough [E0311]
bug.rs:31         let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;
                                                                     ^~~
bug.rs:31:63: 31:63 help: consider adding an explicit lifetime bound for `T`
bug.rs:29:55: 34:6 note: the parameter type `T` must be valid for the anonymous lifetime #3 defined on the block at 29:54...
bug.rs:29     fn add_assign(&mut self, rhs: &Scaled<T, Row<T>>) {
bug.rs:30         let &mut MutRow(strided::SliceMut(lhs)) = self;
bug.rs:31         let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;
bug.rs:32
bug.rs:33         axpy(lhs, alpha, rhs)
bug.rs:34     }
bug.rs:31:60: 31:63 note: ...so that the type `T` will meet its required lifetime bounds
bug.rs:31         let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;
                                                                     ^~~
error: aborting due to previous error
```

---

Both cfg(today) and cfg(yesterday) compile with yesterday's nightly (`(3b3bb0e68 2015-03-04) (built 2015-03-05)`) but cfg(yesterday) fails to compile with today's nightly (`(b0746ff19 2015-03-05) (built 2015-03-06)`), the `impl` had to be changed to `cfg(today)` to make the code compile.

I think the extra lifetime and bound in cfg(today) are redundant:

- `where T: 'a` should be inferred from the use of `Row<'a, T>`, since it seems that `T: 'b` is being inferred from the `RowMut<'b, T>`.
- The `'a` in `rhs: &Scaled<T, Row<'a, T>>` shouldn't be necessary, since its already spelled out in the `AddAssign<Scaled<T, Row<'a, T>>>`

In `linalg`s `src/add_assign.rs` there are several similar `impl`s where the lifetimes and bounds can be elided, and a few other `impl`s that need explicit annotation.

cc @nikomatsakis

**Comment by mahkoh** [comment] 2015-03-07 17:54
This does not necessarily look incorrect. After some thought and help from @eddyb I've come up with this:

```rust
pub mod strided {
    use raw;

    pub struct Slice<'a, T>(pub raw::Slice<'a, T>);
    impl<'a, T> Copy for Slice<'a, T> {}
    pub struct SliceMut<'a, T>(pub raw::SliceMut<'a, T>);
}

pub mod raw {
    use std::marker::PhantomData;

    pub struct Slice<'a, T> {
        // represents `index`
        _marker: PhantomData<fn() -> &'a T>,

        data: *const T,
        len: usize,
    }

    impl<'a, T> Copy for Slice<'a, T> {}

    pub struct SliceMut<'a, T> {
        // represents `index_mut`
        _marker: PhantomData<fn() -> &'a mut T>,

        data: *const T,
        len: usize,
    }
}

pub struct MutRow<'a, T>(strided::SliceMut<'a, T>);
pub struct Row<'a, T>(strided::Slice<'a, T>);
impl<'a, T> Copy for Row<'a, T> {}
pub struct Scaled<T, M>(T, M);

impl<'a, 'b, T> AddAssign<Scaled<T, Row<'a, T>>> for MutRow<'b, T> {
    fn add_assign(&mut self, rhs: &Scaled<T, Row<T>>) {
        let MutRow(strided::SliceMut(ref mut lhs)) = *self;
        let Scaled(ref alpha, Row(strided::Slice(rhs))) = *rhs;

        axpy(lhs, alpha, rhs)
    }
}

fn axpy<T>(_: &mut raw::SliceMut<T>, _: &T, _: raw::Slice<T>) {}

pub trait AddAssign<Rhs> {
    fn add_assign(&mut self, &Rhs);
}

fn main() {}
```

**Comment by mahkoh** [comment] 2015-03-07 17:55
Diff:

```patch
--- blaold.rs	2015-03-07 18:48:27.695438678 +0100
+++ bla.rs	2015-03-07 18:48:14.581938331 +0100
@@ -1,51 +1,46 @@
 pub mod strided {
     use raw;
 
-    pub struct Slice<'a, T>(pub raw::Slice<'a, T>) where T: 'a;
+    pub struct Slice<'a, T>(pub raw::Slice<'a, T>);
     impl<'a, T> Copy for Slice<'a, T> {}
-    pub struct SliceMut<'a, T>(pub raw::Slice<'a, T>) where T: 'a;
+    pub struct SliceMut<'a, T>(pub raw::SliceMut<'a, T>);
 }
 
 pub mod raw {
     use std::marker::PhantomData;
 
-    pub struct Slice<'a, T> where T: 'a {
-        _marker: PhantomData<&'a T>,
-        data: *mut T,
+    pub struct Slice<'a, T> {
+        _marker: PhantomData<fn() -> &'a T>,
+
+        data: *const T,
         len: usize,
     }
 
     impl<'a, T> Copy for Slice<'a, T> {}
+
+    pub struct SliceMut<'a, T> {
+        _marker: PhantomData<fn() -> &'a mut T>,
+
+        data: *const T,
+        len: usize,
+    }
 }
 
-pub struct MutRow<'a, T>(strided::SliceMut<'a, T>) where T: 'a;
-pub struct Row<'a, T>(strided::Slice<'a, T>) where T: 'a;
+pub struct MutRow<'a, T>(strided::SliceMut<'a, T>);
+pub struct Row<'a, T>(strided::Slice<'a, T>);
 impl<'a, T> Copy for Row<'a, T> {}
 pub struct Scaled<T, M>(T, M);
 
-#[cfg(yesterday)]
 impl<'a, 'b, T> AddAssign<Scaled<T, Row<'a, T>>> for MutRow<'b, T> {
     fn add_assign(&mut self, rhs: &Scaled<T, Row<T>>) {
-        let &mut MutRow(strided::SliceMut(lhs)) = self;
-        let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;
-
-        axpy(lhs, alpha, rhs)
-    }
-}
-
-#[cfg(today)]
-impl<'a, 'b, T> AddAssign<Scaled<T, Row<'a, T>>> for MutRow<'b, T>
-    where T: 'a,  // <--
-{
-    fn add_assign(&mut self, rhs: &Scaled<T, Row<'a, T>>) {  // <-- `Row<['a], T>`
-        let &mut MutRow(strided::SliceMut(lhs)) = self;
-        let &Scaled(ref alpha, Row(strided::Slice(rhs))) = rhs;
+        let MutRow(strided::SliceMut(ref mut lhs)) = *self;
+        let Scaled(ref alpha, Row(strided::Slice(rhs))) = *rhs;
 
         axpy(lhs, alpha, rhs)
     }
 }
 
-fn axpy<T>(_: raw::Slice<T>, _: &T, _: raw::Slice<T>) {}
+fn axpy<T>(_: &mut raw::SliceMut<T>, _: &T, _: raw::Slice<T>) {}
 
 pub trait AddAssign<Rhs> {
     fn add_assign(&mut self, &Rhs);
```

**Comment by eddyb** [comment] 2015-03-07 18:00
@mahkoh does it work if you replace `PhantomData<fn() -> X>` with `PhantomData<X>`?
The main issue I see so far is `&'a T` vs `&'a mut T` - the latter is invariant over T (in &'a mut Foo<'b>`, you can shorten `'a` but not `'b'` - we need a FAQ entry about this).

**Comment by mahkoh** [comment] 2015-03-07 18:04
@eddyb: `PhantomData<&'a T>` requires an unnecessary `T: 'a` bound which will cascade through the type system for no good reason. The code I posted above already does work, `SliceMut` is indeed supposed to be invariant over `T`.

**Comment by eddyb** [comment] 2015-03-07 18:19
@mahkoh I don't understand how `fn() -> &'a T` is supposed to be any different from `&'a T` - that seems like a bug.
Also, do we really need to keep `T: 'a` and `'a: 'b` explicit?
I've always thought @nikomatsakis was planning to add the automatic bounds back.

**Comment by mahkoh** [comment] 2015-03-07 18:35
IRC summary: You can create functions `fn() -> &'static T` with `T` not `'static`, which is why the code above does not require `T: 'a`. Example:

```rust
fn f<'a>(_: &'a u8) -> &'static &'a () { loop { } }

fn g<'a>(_: &'a u8, _: fn(&'a u8) -> &'static &'a ()) { }

fn main() {
    let x = 0;
    g(&x, f);
}
```

**Comment by japaric** [comment] 2015-03-09 17:50
@mahkoh @eddyb Thanks for looking into this, using `PhantomData<fn() -> &'a T>` lets me remove most of the lifetime bounds `T: 'a` and elide lifetimes in several function arguments while retaining the `ContravariantLifetime<'a>` semantics :+1:.

I do think that `PhantomData<&'a T>` should work the same though. I think that's a bug.

**Comment by nikomatsakis** [comment] 2015-03-23 21:07
On Mon, Mar 09, 2015 at 10:50:24AM -0700, Jorge Aparicio wrote:
> I do think that `PhantomData<&'a T>` should work the same though. I think that's a bug.

This is not a bug. For `(fn() -> T) : 'a` to hold, we do not require
that `T:'a` must hold. But you wouldn't be able to call that fn unless
you knew somehow that `T:'a`.

**Comment by steveklabnik** [comment] 2015-12-18 22:42
> This is not a bug

Closing

**Closed by steveklabnik** 2015-12-18 22:42 UTC
Labels: A-typesystem
