### ISSUE TITLE
Compiler keeps running after it emits a compilation error

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#51374] opened 2018-06-05 17:42 UTC
The following code does not compile, however the compiler keeps running after emitting a message it could not compile:
https://play.rust-lang.org/?gist=7dc801439d22e1d11c9025092d757099&version=stable&mode=debug
```Rust
const q: () = 'a: while (continue 'a != break 'a) {};

fn main() {
    let q: ();
}
```

The error is:
```
|                                         ^^^^^^^^
  |
  = note: #[warn(unreachable_code)] on by default

error[E0019]: constant contains unimplemented expression type
 --> src/main.rs:1:26
  |
1 | const q: () = 'a: while (continue 'a != break 'a) {};
  |                          ^^^^^^^^^^^

warning: Constant evaluating a complex constant, this might take some time
 --> src/main.rs:1:1
  |
1 | const q: () = 'a: while (continue 'a != break 'a) {};
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

when `let q: ();` is removed, it just fails to compile, and rustc stops running.

**Comment by betawaffle** [comment] 2018-06-05 17:48
Duplicate of https://github.com/rust-lang/rust/issues/50637

**Closed** 2018-06-05 21:51 UTC
