### ISSUE TITLE
ICE (assertion) on wrong lang-items signature

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#32861] opened 2016-04-09 20:53 UTC
If you specify the `"custom-unwind-resume": true` in target.json and use well-known (from guides/book) 
`#[lang = "eh_unwind_resume"] extern fn rust_eh_unwind_resume() {}`, you can see the llvm assert "Calling a function with bad signature!" at `src/llvm/lib/IR/Instructions.cpp:240`. 

Nightly rustc (all msvc/gnu/linux targets).

**Comment by Mark-Simulacrum** [comment] 2017-05-02 21:29
Could someone provide a list of steps to follow to reproduce this? It's hard to tell exactly how to do this from the issue itself and I've been unable to come up with them based on ~10 minutes of utilizing Google.

**Comment by Mark-Simulacrum** [comment] 2017-06-22 15:26
Going to close this in favor of https://github.com/rust-lang/rust/issues/9307 since it tracks the cause (lang items not being type checked).

**Closed by Mark-Simulacrum** 2017-06-22 15:26 UTC
Labels: I-ICE
