### ISSUE TITLE
Mutable references in field

### ISSUE THREAD

**Issue by clmuz** [rust-lang/rust#15868] opened 2014-07-21 18:24 UTC
Sorry, maybe it is hundred times solved problem, but I cannot use structure filed, which is mutable reference with longer lifetime, than the structure itself. In this code
```rust
struct A<'r> {
	v: &'r mut Vec<int>
}

impl<'r> A<'r> {
	fn create(v: &'r mut Vec<int>) -> A<'r> {
		A::<'r> {
			v: v
		}
	}

	fn get_mut(&mut self, i: uint) -> &'r mut int {
		self.v.get_mut(i)
	}
}
```
in function `get_mut` I got an error, `lifetime of 'self' is too short`. But without all `mut` keywords code runs without errors.

**Comment by alexcrichton** [comment] 2015-03-09 16:13
Hm upon re-reflection I believe this is actually intended behavior. You cannot take out a mutable borrow longer than the lifetime of the mutable borrow which granted mutable access. In this case the function is trying to borrow `&'a mut &'r mut int` to `&'r mut int` (essentially), but this is can lead to safety violations later on down the road, so closing this an expected error.

**Closed by alexcrichton** 2015-03-09 16:13 UTC
Labels: A-lifetimes
