### ISSUE TITLE
sepcomp-lib-lto test fails with --enable-llvm-assertions

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#25617] opened 2015-05-19 18:18 UTC
```
error: compilation failed!
status: signal: 6
command: x86_64-unknown-linux-gnu/stage1/bin/rustc /home/ariel/Rust/source.rfc401/src/test/run-pass/sepcomp-lib-lto.rs -L x86_64-unknown-linux-gnu/test/run-pass/ --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/run-pass/sepcomp-lib-lto.stage1-x86_64-unknown-linux-gnu.run-pass.libaux -o x86_64-unknown-linux-gnu/test/run-pass/sepcomp-lib-lto.stage1-x86_64-unknown-linux-gnu --cfg rtopt --cfg debug -O -L x86_64-unknown-linux-gnu/rt -C lto
stdout:
------------------------------------------
------------------------------------------
stderr:
------------------------------------------
rustc: /home/ariel/Rust/source.rfc401/src/llvm/lib/CodeGen/LexicalScopes.cpp:179: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(llvm::MDNode*): Assertion `DISubprogram(Scope).describes(MF->getFunction())' failed.
```

**Comment by dotdash** [comment] 2015-05-19 19:04
Looks like a dupe of #23566

**Closed** 2015-05-19 19:07 UTC
