### ISSUE TITLE
ICE: unexpected predicate TraitPredicate on opaque type

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#75983] opened 2020-08-27 13:22 UTC
Found in the `pr-75180` crater run:
````
git clone https://github.com/PaulGrandperrin/playground/  
cd playground
git checkout 572ff41ccdfa72771a37fd9ab89f37e9b5451041
cargo check
````
ICEs:

````
error: internal compiler error: unexpected predicate TraitPredicate(<<std::rc::Rc<impl non_volatile::object::any_rc_object::Object> as std::convert::TryFrom<non_volatile::object::any_rc_object::AnyRcObject>>::Error as std::fmt::Debug>) on opaque type
  --> src/non_volatile/object/any_rc_object.rs:34:52
   |
34 |         <Rc<Self> as TryFrom<AnyRcObject>>::Error: Debug;
   |                                                    ^^^^^
   |
   = note: delayed at src/librustc_ty/ty.rs:480:18

error: internal compiler error: unexpected predicate TraitPredicate(<std::rc::Rc<impl non_volatile::object::any_rc_object::Object> as std::convert::TryFrom<non_volatile::object::any_rc_object::AnyRcObject>>) on opaque type
  --> src/non_volatile/object/any_rc_object.rs:33:19
   |
33 |         Rc<Self>: TryFrom<AnyRcObject>,
   |                   ^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at src/librustc_ty/ty.rs:480:18

error: internal compiler error: unexpected predicate TraitPredicate(<std::rc::Rc<impl non_volatile::object::any_rc_object::Object> as std::marker::Sized>) on opaque type
   --> /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:494:23
    |
494 | pub trait TryFrom<T>: Sized {
    |                       ^^^^^
    |
    = note: delayed at src/librustc_ty/ty.rs:480:18

error: internal compiler error: unexpected predicate TraitPredicate(<non_volatile::object::any_rc_object::AnyRcObject as std::convert::From<std::rc::Rc<impl non_volatile::object::any_rc_object::Object>>>) on opaque type
  --> src/non_volatile/object/any_rc_object.rs:32:22
   |
32 |         AnyRcObject: From<Rc<Self>>,
   |                      ^^^^^^^^^^^^^^
   |
   = note: delayed at src/librustc_ty/ty.rs:480:18

error: internal compiler error: unexpected predicate TraitPredicate(<non_volatile::object::any_rc_object::AnyRcObject as std::marker::Sized>) on opaque type
   --> /home/matthias/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:386:20
    |
386 | pub trait From<T>: Sized {
    |                    ^^^^^
    |
    = note: delayed at src/librustc_ty/ty.rs:480:18

error: internal compiler error: unexpected predicate TraitPredicate(<non_volatile::object::any_rc_object::AnyRcObject as std::convert::From<impl non_volatile::object::any_rc_object::Object>>) on opaque type
  --> src/non_volatile/object/any_rc_object.rs:31:77
   |
31 | pub trait Object = Serializable + ConstObjType + Default where AnyRcObject: From<Self>,
   |                                                                             ^^^^^^^^^^
   |
   = note: delayed at src/librustc_ty/ty.rs:480:18

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:369:17
stack backtrace:
   0: std::panicking::begin_panic
   1: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   2: core::ptr::drop_in_place
   3: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place
   5: rustc_span::with_source_map
   6: rustc_interface::interface::create_compiler_and_run
   7: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (2d8a3b918 2020-08-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`.

To learn more, run the command again with --verbose.
````

This ICE happens on:
`rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25)`
`rustc 1.47.0-nightly (2d8a3b918 2020-08-26)`
but rustc `1.45.2 (d3fb005a3 2020-07-31)` builds fine.

**Comment by estebank** [comment] 2020-08-27 15:24
Is this going out in the new stable?

**Comment by jonas-schievink** [comment] 2020-08-27 15:32
Oh, this crate is full of unstable features, so no need to worry about stable

**Comment by LeSeulArtichaut** [comment] 2020-08-28 22:05
> Oh, this crate is full of unstable features, so no need to worry about stable

Then I guess it would be worth minimizing this to check that we're unable to reproduce this with no unstable features, and if we can't, it would still be good to have a test case for the "culprit feature".

**Comment by Skepfyr** [comment] 2020-08-29 00:05
I got it down to this, I haven't been able to remove `trait_alias` so I think short term it's fine.
```rust
#![feature(trait_alias)]

struct Bar;
trait Foo {}
impl Foo for Bar {}

trait Baz = Foo where Bar: Foo;

fn new() -> impl Baz {
    Bar
}
```

**Comment by apiraino** [comment] 2020-08-31 17:45
@rustbot ping cleanup-crew
I've tried roughly bisect some nightlies, it happens somewhere between 2020-06-09...2020-07-09.

**Comment by Skepfyr** [comment] 2020-08-31 19:46
I'm not sure why I didn't bisect this as I'm all set up to do it..... the regression was in nightly 2020-06-22, specifically somewhere in this rollup: https://github.com/rust-lang/rust/commit/7058471adec80a2a1e6092443e08546768c9c894

**Comment by spastorino** [comment] 2020-09-02 15:47
possibly https://github.com/rust-lang/rust/pull/72788

**Comment by spastorino** [comment] 2020-09-02 15:50
Assigning `P-medium` given this `requires-nightly` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2375983.20ICE.3A.20unexpected.20predicate.20TraitPredicat.E2.80.A6) and removing `I-prioritize`.

**Comment by JohnTitor** [comment] 2020-10-07 13:11
Triage: This (https://github.com/rust-lang/rust/issues/75983#issuecomment-683197396) is no longer ICE with the latest nightly, it'd be great if someone could confirm whether the original is also fixed, marking as E-needs-test for now.

**Closed** 2020-10-18 02:28 UTC
Labels: A-traits, C-bug, E-needs-test, F-trait_alias, I-ICE, ICEBreaker-Cleanup-Crew, P-medium, T-compiler, glacier, requires-nightly
