### ISSUE TITLE
rustdoc should not require a file to display -Whelp

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#98001] opened 2022-06-11 19:22 UTC
`$ rustc -Whelp`
`<lint list>`

`$ rustdoc -Whelp`
`error: missing file operand` 

You have to do something like `rustdoc file.rs -Whelp` in order to see the lint list which is a bit weird :smile: (it does not seem to actually process the file then at least...)

**Comment by GuillaumeGomez** [comment] 2022-06-18 13:27
Weirdly enough, it seems like we need to have a file to be able to run `register_plugins` in `lib.rs::main_options`. If we don't provide a file, the compiler doesn't allow us to build plugins. I think the reason behind this is that rustdoc should always be run with `cargo` which will always provide a file.

I'm not sure if it's worth fixing but just in case: do you think there is a way to fix this @rust-lang/compiler ?

**Comment by jyn514** [comment] 2022-06-20 04:30
Duplicate of https://github.com/rust-lang/rust/issues/88756 (which has an open PR if anyone wants to help take it over)

**Closed by jyn514** 2022-06-20 04:30 UTC
Labels: T-rustdoc
