### ISSUE TITLE
Incorrect object-safety with `where Option<Self>: Sized`

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#25204] opened 2015-05-08 07:25 UTC
Code:

``` rust
// This fails to compile:
// trait Foo: Sized {
// This compiles successfully
trait Foo where Option<Self>: Sized {
    fn some_fn(&self);
}

trait Foo2 where Box<Self>: Sized {
    fn some_fn2(&self);
}

struct Bar;
impl Foo for Bar {
    fn some_fn(&self) {}
}

impl Foo2 for Bar {
    fn some_fn2(&self) {}
}

fn option_sized<T: ?Sized>() where Option<T>: Sized {}

fn box_sized<T: ?Sized>() where Box<T>: Sized {}

fn main() {
    let x: Box<Bar> = Box::new(Bar);
    let y: Box<Foo> = x;
    // This fails to compile
    // y.some_fn();

    let x2: Box<Bar> = Box::new(Bar);
    let y2: Box<Foo2> = x2;
    // But this compiles successfully
    y2.some_fn2();

    // This also fails to compile
    // option_sized::<Foo>();

    // But this compiles successfully
    box_sized::<Foo>();
}

```

[playpen](http://is.gd/cFd4NZ)

I'm not sure which line is the compiler wrong, but this combination of compile successes/failures is very inconsistent.

**Comment by theemathas** [comment] 2015-05-08 07:34
Another weird case:

```rust
fn weird<T: ?Sized>(_: Option<T>) where Option<T>: Sized {}

fn main() {}
```
[playpen](http://is.gd/6eCCqM)

Error:
```
<anon>:25:1: 25:60 error: the trait `core::marker::Sized` is not implemented for the type `T` [E0277]
<anon>:25 fn weird<T: ?Sized>(_: Option<T>) where Option<T>: Sized {}
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<anon>:25:1: 25:60 note: `T` does not have a constant size known at compile-time
<anon>:25 fn weird<T: ?Sized>(_: Option<T>) where Option<T>: Sized {}
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by arielb1** [comment] 2015-05-08 14:28
@theemathas 

The compiler does not deduce `T: Sized` from `Option<T>: Sized`.

**Comment by theemathas** [comment] 2015-05-09 01:47
@arielb1 I pretty much figured out that the compiler *only sometimes* does that. I would prefer it to always do it, or never do it.

I expect the current code to have a compile error on this line:
```rust
let y: Box<Foo> = x;
```

**Comment by theemathas** [comment] 2015-05-10 03:00
I have realized that the `weird` function is not a bug, since `Option` requries its type parameter to be `Sized`.

However, this code somehow compiles:
http://is.gd/SzkZiN

**Comment by Kimundi** [comment] 2015-05-15 10:16
@theemathas Hm, I'd expect that code to compile, and only allow instance of `Wrap<T>` with `Sized` `T`.

**Comment by theemathas** [comment] 2015-06-09 07:57
Possibly related to #19182

**Comment by arielb1** [comment] 2015-06-09 10:14
@theemathas 

Its not the same issue, but the problem is that object safety does not consider non-supertrait predicates.

**Comment by arielb1** [comment] 2015-08-14 20:33
related to #27675

**Comment by pnkfelix** [comment] 2016-01-21 13:03
I think the compiler is now properly flagged this code under the warnings issued by RFC 1214:

```rust
trait OptSelfSized where Option<Self>: Sized { }
```

yields:

```
wf-15.rs:5:1: 5:49 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
wf-15.rs:5 trait OptSelfSized where Option<Self>: Sized { }
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wf-15.rs:5:1: 5:49 help: run `rustc --explain E0277` to see a detailed explanation
wf-15.rs:5:1: 5:49 note: `Self` does not have a constant size known at compile-time
wf-15.rs:5:1: 5:49 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
wf-15.rs:5 trait OptSelfSized where Option<Self>: Sized { }
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wf-15.rs:5:1: 5:49 note: required by `core::option::Option`
```

**Comment by Mark-Simulacrum** [comment] 2017-04-16 00:33
This appears to be fixed, but I'm not certain.

**Comment by Mark-Simulacrum** [comment] 2017-04-28 22:39
Closing, please reopen if this is still an issue.

**Closed by Mark-Simulacrum** 2017-04-28 22:39 UTC
Labels: A-typesystem
