### ISSUE TITLE
Unclear if AtomicBool implements Send

### ISSUE THREAD

**Issue by tbelaire** [rust-lang/rust#33021] opened 2016-04-16 01:51 UTC
I was looking through all the types, seeing how `Send` and `Sync` bounds relate to each other, when I noticed that unlike most other types in `sync`, in the `impl` section `AtomicBool` only says

```
impl Sync for AtomicBool
```
without any mention of `Send`, one way or the other.

I was expecting that like `Arc`, `Cell`, and `Mutex`, there would be an explicit listing of it's `Send`ness and `Sync`ness.

**Comment by retep998** [comment] 2016-04-16 02:05
`Send` and `Sync` only need to be explicitly implemented when they want to be `Send` and `Sync` in cases where they wouldn't automatically be `Send` and `Sync`. This is either closely related to or a duplicate of https://github.com/rust-lang/rust/issues/17606

**Comment by apasel422** [comment] 2016-06-17 19:06
Closing as duplicate.

**Closed by apasel422** 2016-06-17 19:06 UTC
