### ISSUE TITLE
serde no longer builds with latest rustc (master)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#62562] opened 2019-07-10 15:03 UTC
Looks like something that landed in the commit range https://github.com/rust-lang/rust/compare/0b680cfce544ff9a59d720020e397c4bf3346650...d4e15655092d1bdae79619eb0ff2c3cb5468fc36 broke [building serde](https://travis-ci.com/rust-lang/miri/jobs/214779163):
```
error[E0433]: failed to resolve: unresolved import
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/ast.rs:142:44
    |
142 |     variants: &'a Punctuated<syn::Variant, Token![,]>,
    |                                            ^^^^^^^^^
    |                                            |
    |                                            unresolved import
    |                                            help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
error[E0433]: failed to resolve: unresolved import
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.94/src/internals/ast.rs:187:40
    |
187 |     fields: &'a Punctuated<syn::Field, Token![,]>,
    |                                        ^^^^^^^^^
    |                                        |
    |                                        unresolved import
    |                                        help: a similar path exists: `syn::token`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
I would try to reproduce locally but `rustup-toolchain-install-master` takes many hours to download rustc+libstd currently. (This bug is not yet on nightly, just in master.)

Here's a [prior succeeding build](https://travis-ci.com/rust-lang/miri/jobs/214696148) for reference.

**Comment by Mark-Simulacrum** [comment] 2019-07-10 15:11
This is https://github.com/rust-lang/rust/pull/62393 almost certainly. @petrochenkov plans to investigate.

**Comment by petrochenkov** [comment] 2019-07-10 22:40
Minimized and reproduced.

https://github.com/rust-lang/rust/pull/62393 broke something unexpected - macro encoding in metadata, which is *also* done through pretty-printing at the moment (note that this is not a proper way to encode macro definitions, we don't have cross-crate hygiene due to this).

Nested macros in particular become broken in metadata:
```rust
macro_rules! generate_exported { () => {
    #[macro_export]
    macro_rules! exported {
        () => ($crate::S)
    }
}}

generate_exported!();
```

I still need to investigate why exactly this happens though, printing for metadata is done by `tts_to_string` which was supposed to print `$crate` as `$crate` without any conversions.

**Comment by petrochenkov** [comment] 2019-07-10 23:57
Fixed in https://github.com/rust-lang/rust/pull/62574.

**Comment by gbenattar** [comment] 2019-07-11 07:55
Can we get an update? I

**Comment by dtolnay** [comment] 2019-07-11 08:06
It will take a day or two for the bug to be fixed in nightly. I would recommend using an older nightly for now; *nightly-2019-07-10* or older should work.

**Comment by AlterionX** [comment] 2019-07-11 08:11
https://github.com/serde-rs/serde/issues/1568 actually, one more day before that, __nightly-2019-07-09__

**Comment by dtolnay** [comment] 2019-07-11 08:14
nightly-2019-07-10 does work. The version reported by the compiler binary is off by one. The first broken nightly is nightly-2019-07-11 which contains "rustc 1.38.0-nightly (cd2cd4c96 2019-07-10)".

**Comment by AlterionX** [comment] 2019-07-11 08:20
Ah, okay, my bad.

**Comment by pnkfelix** [comment] 2019-07-11 12:42
triage: P-high, has PR (#62574), assigning to @petrochenkov and removing nomination.

**Closed** 2019-07-11 13:35 UTC
Labels: A-resolve, C-bug, P-high, T-compiler, regression-from-stable-to-nightly

**Comment by dtolnay** [comment] 2019-07-11 21:17
Pinning for visibility until a new nightly is out.
