### ISSUE TITLE
Do not hint to use elided '_ lifetimes in errors

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#52743] opened 2018-07-26 16:22 UTC
https://play.rust-lang.org/?gist=96fc205e5162ae48cb27063a22ea4518&version=nightly&mode=debug&edition=2015

```rust
#![feature(nll)]
#![feature(in_band_lifetimes)]

struct Foo<'a, 'b> {
    x: &'a u32,
    y: &'b u32,
}

struct Bar<'b> {
    z: &'b u32
}

impl Foo<'_, '_> {
    fn take_bar(&mut self, b: Bar<'_>) {
        self.y = b.z
    }
}

fn main() { }
```

```
error[E0621]: explicit lifetime required in the type of `b`
  --> src/main.rs:15:9
   |
14 |     fn take_bar(&mut self, b: Bar<'_>) {
   |                            - consider changing the type of `b` to `Bar<'_>`
15 |         self.y = b.z
   |         ^^^^^^^^^^^^ lifetime `'_` required

error: aborting due to previous error
```

cc @davidtwco

**Comment by estebank** [comment] 2018-07-26 21:41
Closing as dupe of #52742.

**Closed by estebank** 2018-07-26 21:41 UTC
Labels: NLL-diagnostics
