### ISSUE TITLE
ICE - Option Refcount causes an LLVM assertion to fail.

### ISSUE THREAD

**Issue by DavidJFelix** [rust-lang/rust#21533] opened 2015-01-23 00:00 UTC
The following code:

```
use std::rc::Rc

struct ProblemType {
    children [Option<Rc<ProblemType>>; 8],
}

impl ProblemType {
    fn breaks_compiler() -> Option<Rc<ProblemType>> {
        None
    }
}
```

Causes LLVM to fail an assertion, claiming:

    rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/DataLayout.cpp:636: unsigned int llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed.

**Comment by dotdash** [comment] 2015-02-14 21:55
Reduced test case:

````rust
struct Outer(*mut ProblemType);
struct ProblemType ([Outer; 8]);

fn breaks_compiler(_: Outer) {}
````

**Comment by dotdash** [comment] 2015-02-15 21:10
This depends on the array in `ProblemType` being fixed sized, and `ProblemType` being either a struct or a single variant enum. Under those conditions, the code ends up trying to get the size of `Outer` in a state where the struct body has not yet been set.

**Comment by tamird** [comment] 2015-04-22 01:19
Triage: no longer ICEs.

The original case:
```rust
use std::rc::Rc;

struct ProblemType {
    children: [Option<Rc<ProblemType>>; 8],
}

impl ProblemType {
    fn breaks_compiler() -> Option<Rc<ProblemType>> {
        None
    }
}

fn main() {
    // Add code here
}
```
as well as the reduced test case now compile without error.

**Comment by pmarcelll** [comment] 2015-06-18 18:05
On my machine both test cases fail with the ICE mentioned in the first comment.
```
rustc 1.2.0-nightly (0250ff9a5 2015-06-17)
```

**Comment by arielb1** [comment] 2015-07-08 21:16
Confirming still ICEs

**Comment by wheals** [comment] 2015-10-25 22:55
This is strange: it compiles fine in [stable and beta](http://is.gd/mBfj4a) (also with rustc 1.2.0), but fails in [nightly](http://is.gd/9tP61n).

**Comment by arielb1** [comment] 2015-10-26 22:19
@wheals 

LLVM assertions are disabled in stable/beta.

**Comment by arielb1** [comment] 2015-10-27 20:14
duplicate of #19001

**Closed by arielb1** 2015-10-27 20:14 UTC
Labels: I-ICE
