### ISSUE TITLE
index out of bounds in libcore/slice/mod.rs running rustfmt under rls

### ISSUE THREAD

**Issue by matiu2** [rust-lang/rust#61636] opened 2019-06-07 21:25 UTC
I hit 'reformat document' in vscode with the rust-rls plugin and got this output:

```
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (7158ed9cb 2019-05-15) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'index out of bounds: the len is 29 but the index is 4294951088', /rustc/7158ed9cbea805adf8161d3deaadba2f85b7692e/src/libcore/slice/mod.rs:2695:10

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (7158ed9cb 2019-05-15) running on x86_64-unknown-linux-gnu

[Error - 7:21:20 am] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
```

**Comment by jonas-schievink** [comment] 2019-06-07 21:36
Is this reproducible, and can you provide a link to the code? Also, can you try running this with `RUST_BACKTRACE=1` set?

**Comment by matiu2** [comment] 2019-06-13 06:10
Could you tell me how I would re-run it on the command line ? my IDE (clion) ran it, and I don't know how it does it.

**Comment by lzutao** [comment] 2019-06-13 06:13
In the project root that has `Cargo.toml` file, open you terminal in there
and type `RUST_BACKTRACE=1 cargo build`.

**Comment by matiu2** [comment] 2019-06-14 07:09
I'm not seeing the error that way. Does 'cargo build' use the rls server ?

If it does, I guess we can just close this as unable to reproduce.

If it doesn't, how can I launch the RLS server, then use it to do a 'fmt' on my code from the command line with RUST_BACKTRACE=1.

Thank you for your patience.

**Comment by jonas-schievink** [comment] 2019-06-14 09:30
Ah, you probably want to run `cargo fmt` instead of `cargo build`

**Comment by Mark-Simulacrum** [comment] 2019-08-10 02:44
Closing since we don't have a way to reproduce, and this should be filed against RLS  most likely anyway.

**Closed by Mark-Simulacrum** 2019-08-10 02:44 UTC
Labels: C-bug, I-ICE, T-compiler
