### ISSUE TITLE
Memory leak when using println! in unit tests

### ISSUE THREAD

**Issue by ptagl** [rust-lang/rust#83209] opened 2021-03-16 17:27 UTC
While working on a Rust application, I ran some unit tests to check that I did not introduce any memory leak.

After some attempts, I discovered that the macro `println!` seems to **leak memory** when used **inside unit tests**.

The memory leak can be noticed by watching a process monitor (e.g. htop) and running the following code

```rust
#[test]
fn loop_test() {
    loop {
        println!("Hello world!");
    }
}
```

with ```cargo test```.

I expected to see the **memory usage** to stay constant, instead it **rapidly grows up**.

I was able to reproduce the memory leak with two different toolchains:

```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

The test has been performed on WSL 2 (Ubuntu 20) running on Windows 10.

**Comment by jonas-schievink** [comment] 2021-03-16 17:29
Console output of unit tests is captured in memory, so this is working as intended

**Comment by ehuss** [comment] 2021-03-16 18:21
Additionally, [`--nocapture`](https://doc.rust-lang.org/nightly/rustc/tests/index.html#--nocapture) can be used to avoid the buffering.

**Comment by jonas-schievink** [comment] 2021-03-16 18:55
Closing as expected behavior

**Closed by jonas-schievink** 2021-03-16 18:55 UTC
Labels: A-libtest, C-bug
