### ISSUE TITLE
Linking error between Rust crates

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#29164] opened 2015-10-19 13:58 UTC
How to reproduce:

1 - Clone the branch `rustc-bug` of https://github.com/tomaka/spine-rs
2 - Run `cargo test`

I get the following linking error with 32bits MinGW (`rustc 1.5.0-nightly (20a6938c0 2015-10-16)`) when the tests are linked:

```
note: D:\Projets\spine-rs\target\debug\test-f0708a7cba5cf230.0.o: In function `ZN4test4testE':
D:\Projets\spine-rs/tests/test.rs:11: undefined reference to `skeleton::animation::_$LT$impl$GT$::interpolate::h1389f3fa921899f7Y7b'
```

Everything is 100% pure safe Rust, so this linking error is clearly a bug.

I don't have time right now to find out precisely what causes it. Calling other functions from `SkinAnimation` also triggers the linking error. But for example if you only call `spine::Skeleton::from_reader` (which is another function from that same crate), then you don't get any error.

**Comment by tomaka** [comment] 2015-10-19 15:06
I just tried and got the same linking error on linux.

**Comment by alexcrichton** [comment] 2015-10-19 16:41
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/16734, so closing in favor of that, but thanks for the report!

If you add a `pub use` to the top of the crate of `SkinAnimation` it'll at least paper over the problem for now!

**Closed** 2015-10-19 16:41 UTC

**Comment by tafia** [comment] 2015-10-20 05:06
Thanks!
