### ISSUE TITLE
Panic on list items containing inline code blocks

### ISSUE THREAD

**Issue by jorisgio** [rust-lang/rust#24539] opened 2015-04-17 21:25 UTC
rustdoc panic in certain combinations of inline code blocks, list items and headlines : 

this works : 
```
//!     - `test`
```

this works too : 
```
//! # Overview 
//!     - `test`
```

But this fails :  
```
//! # Overview
//!
//!    - ` test`
```

with the following error : 

```
<stdin>:1:3: 1:4 error: unknown start of token: `
<stdin>:1 - `test`
            ^
thread '<unnamed>' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/parse/lexer/mod.rs:184
thread '<main>' panicked at 'called `Result::unwrap()` on an 
```
backtrace :
 
```
stack backtrace:
   1:     0x7f6c23a25939 - sys::backtrace::write::h479a8ad00fbfddd90Us
   2:     0x7f6c23a2d918 - panicking::on_panic::h5028078e4ae51e97fix
   3:     0x7f6c239eb682 - rt::unwind::begin_unwind_inner::hd4dec672e7375653pXw
   4:     0x7f6c213625ed - rt::unwind::begin_unwind::h389727515196150120
   5:     0x7f6c2141c445 - parse::lexer::StringReader<'a>::fatal_span::h6f198e45ef7825caMIN
   6:     0x7f6c2141eefd - parse::lexer::StringReader<'a>::fatal_span_char::h50230fe90eafded9oKN
   7:     0x7f6c21419493 - parse::lexer::StringReader<'a>::advance_token::hb4cd73d83e85192bmNN
   8:     0x7f6c21417d7e - parse::lexer::StringReader<'a>.Reader::next_token::hce70e69372b967c1cCN
   9:     0x7f6c2401c802 - html::highlight::highlight::h4de69d3743a51126aVj
  10:     0x7f6c24032b66 - html::markdown::render::block::h82612f4123cd4429Bmm
  11:     0x7f6c2416db3d - parse_block
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:1745
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:2400
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c:2354
  12:     0x7f6c2416fe56 - hoedown_document_render
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rt/hoedown/src/document.c
:2802
  13:     0x7f6c24031a5d - html::markdown::render::h54451570ba64cddalmm
  14:     0x7f6c2403a030 - html::markdown::Markdown<'a>.fmt..Display::fmt::h14a6a1448f1ca5719Pm
  15:     0x7f6c23a922b0 - fmt::write::h725b13cc543cb1131FN
  16:     0x7f6c23a8c851 - fmt::Formatter<'a>::write_fmt::h89b7141692180be4tWN
  17:     0x7f6c24076478 - html::render::document::hb92e21fb1283eb402cp
  18:     0x7f6c24071594 - html::render::Item<'a>.fmt..Display::fmt::h624519293bd64316jVo
  19:     0x7f6c23a92211 - fmt::write::h725b13cc543cb1131FN
  20:     0x7f6c2405ed96 - io::Write::write_fmt::h2029946465966684158
  21:     0x7f6c2406dc61 - html::render::Context::item::render::h3c786309288297a9qwo
  22:     0x7f6c24068ae1 - html::render::Context::recurse::h7309834789769284986
  23:     0x7f6c24045a23 - html::render::run::h1fc72b998f61687bvan
  24:     0x7f6c240c9035 - main_args::h7ab54dee6157b3a5fPt
  25:     0x7f6c240c49f0 - boxed::F.FnBox<A>::call_box::h6206483487655731891
  26:     0x7f6c240c39f9 - rt::unwind::try::try_fn::h14506545780071665698
  27:     0x7f6c23aa4e78 - rust_try_inner
  28:     0x7f6c23aa4e65 - rust_try
  29:     0x7f6c240c3cc5 - boxed::F.FnBox<A>::call_box::h1066950650817129193
  30:     0x7f6c23a2c4e1 - sys::thread::create::thread_start::h09b6c8d6cadbe2b5wgw
  31:     0x7f6c1de71373 - start_thread
  32:     0x7f6c2367427c - clone
  33:                0x0 - <unknown>
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:750
stack backtrace:
   1:     0x7f6c23a25939 - sys::backtrace::write::h479a8ad00fbfddd90Us
   2:     0x7f6c23a2d918 - panicking::on_panic::h5028078e4ae51e97fix
   3:     0x7f6c239eb682 - rt::unwind::begin_unwind_inner::hd4dec672e7375653pXw
   4:     0x7f6c239eb94c - rt::unwind::begin_unwind_fmt::he10562f3655cff5f3Vw
   5:     0x7f6c23a2d1d6 - rust_begin_unwind
   6:     0x7f6c23a7ed94 - panicking::panic_fmt::h0077c224f0419f55USC
   7:     0x7f6c240c3605 - main::hfe0e2a1069fe72452Kt
   8:     0x7f6c23aa4e78 - rust_try_inner
   9:     0x7f6c23aa4e65 - rust_try
  10:     0x7f6c23a2f13b - rt::lang_start::h67a4b8e9e9c38485Kcx
  11:     0x7f6c235ac7ff - __libc_start_main
  12:     0x7f6c24746738 - <unknown>
```

on `rustdoc 1.0.0-nightly (a52182ffd 2015-04-17) (built 2015-04-17)`, running on linux

**Comment by jorisgio** [comment] 2015-04-17 21:30
After an advice from asQuirreL on #rust i tried with only two spaces to indent the list block and it doesn't panic in this case.

**Comment by mitaa** [comment] 2016-03-08 09:23
Duplicate of #12834

**Closed** 2016-03-08 15:55 UTC
Labels: A-rustdoc
