### ISSUE TITLE
Unexpected compiler panic somewhere in Option

### ISSUE THREAD

**Issue by ebkalderon** [rust-lang/rust#29885] opened 2015-11-17 11:53 UTC
Hi everyone. I was working on a personal project for a while, and after adding some rustdoc comments to my code and recompiling, I was surprised to see a panic that appears to originate from the Option code inside of libcore.

Below are my results for `RUST_BACKTRACE=1 cargo build`:
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:365
stack backtrace:
   1: 0xf72dab84 - sys::backtrace::tracing::imp::write::h32714b78dcac54bdRlt
   2: 0xf72e2061 - panicking::log_panic::_<closure>::closure.39263
   3: 0xf72e1aeb - panicking::log_panic::hb456a1208990cebf3lx
   4: 0xf72a1c7a - sys_common::unwind::begin_unwind_inner::he01b3273505cc085ids
   5: 0xf72a2697 - sys_common::unwind::begin_unwind_fmt::h02f8d3512fb33605ocs
   6: 0xf72d8741 - rust_begin_unwind
   7: 0xf7333560 - panicking::panic_fmt::hd81b30dcb1056440dMK
   8: 0xf732c69d - panicking::panic::h211ad863d7cb3abdKKK
   9: 0xf6d47c6c - _<impl>::ensure_public::h49d1fe3a5a11351dh0a
  10: 0xf6d48eca - _<impl>::check_path::_<closure>::_<closure>::closure.12245
  11: 0xf6d4851e - _<impl>::check_path::_<closure>::closure.12243
  12: 0xf6d483e4 - _<impl>::check_path::h1a6edff431b60c84Kbb
  13: 0xf6d49806 - _<impl>::visit_path::h52e060852424c073jtb
  14: 0xf6d49799 - visit::walk_item::walk_item::h4928275435436548280
  15: 0xf6d492f4 - visit::walk_item::walk_item::h4928275435436548280
  16: 0xf6d492f4 - visit::walk_item::walk_item::h4928275435436548280
  17: 0xf6d4fd32 - check_crate::h92e7adb71138b7c9uXb
  18: 0xf75adea1 - driver::phase_3_run_analysis_passes::_<closure>::closure.21790
  19: 0xf7595109 - middle::ty::context::_<impl>::create_and_enter::create_and_enter::h1763093385775617242
  20: 0xf7590cff - driver::phase_3_run_analysis_passes::h3415820696787847509
  21: 0xf75712c2 - driver::compile_input::h4e4153a31a11408c3ba
  22: 0xf76c9354 - run_compiler::hf1f2a520e42c16f8wsc
  23: 0xf76c661f - boxed::_<impl>::call_box::call_box::h12044635053083472681
  24: 0xf76c5f28 - sys_common::unwind::try::try_fn::try_fn::h2365839236508184123
  25: 0xf72d8584 - __rust_try
  26: 0xf72cc987 - sys_common::unwind::try::inner_try::h8e065da1baff5dd7Q9r
  27: 0xf76c60c7 - boxed::_<impl>::call_box::call_box::h13233349464267272907
  28: 0xf72e0ab9 - sys::thread::_<impl>::new::thread_start::h05d7345206697ab4fEw
  29: 0xf2d31314 - start_thread
  30: 0xf7164d6d - __clone
  31:        0x0 - <unknown>

Could not compile `amethyst`.

To learn more, run the command again with --verbose.
```

I am running the 1.5.0 Nightly build of rustc. Can anyone else shed some light on this?

**Comment by apasel422** [comment] 2015-11-17 12:00
On first glance this appears to be a duplicate of #29161. Could you post the output of `rustc --version`?

**Comment by ebkalderon** [comment] 2015-11-17 12:05
Here you go: `rustc 1.5.0-nightly (80660d6ba 2015-10-06)`

**Comment by apasel422** [comment] 2015-11-17 12:07
#29161 was fixed in a more recent nightly. Can you confirm that the issue goes away with the latest one?

**Comment by ebkalderon** [comment] 2015-11-17 13:04
Confirmed; it works! Thanks for the help.

**Closed** 2015-11-17 13:15 UTC
