### ISSUE TITLE
Implementation cannot be defined for 'type' alias

### ISSUE THREAD

**Issue by araujol** [rust-lang/rust#13551] opened 2014-04-16 04:07 UTC
Code example:

Save this in `main.rs` and try to compile.

```
enum T {}
type New = T;

impl New {}

fn main() {}
```

Trying to compile, it shows this error:

impl.rs:4:1: 4:12 error: cannot associate methods with a type outside the crate the type is defined in; define and implement a trait or new type instead
impl.rs:4 impl New {}
          ^~~~~~~~~~~
error: aborting due to previous error

Using git master HEAD: 6fcf43e50e9dd8ad8dc83d550e25f738f821f1ce

**Comment by steveklabnik** [comment] 2015-01-21 00:00
Yes, this is a duplicate of that issue.

**Closed by steveklabnik** 2015-01-21 00:00 UTC
Labels: A-resolve
