### ISSUE TITLE
(E0603) "function `run_compiler` is private" fail during building miri

### ISSUE THREAD

**Issue by IdrisKalp** [rust-lang/rust#79582] opened 2020-12-01 00:29 UTC
Platform: Linux x86_64
Distro: PisiLinux 2.1.2

Building rust 1.48.0 from source with existing rust installed on system or with a binary package from site, build throws this error.

```
Building stage1 tool miri (x86_64-unknown-linux-gnu)
   Compiling getrandom v0.2.0
   Compiling miri v0.1.0 (/var/pisi/rust-1.48.0-17/work/rustc-1.48.0-src/src/tools/miri)
error[E0603]: function `run_compiler` is private
   --> src/tools/miri/src/bin/miri.rs:160:23
    |
160 |         rustc_driver::run_compiler(&args, callbacks, None, None, None)
    |                       ^^^^^^^^^^^^ private function
    |
note: the function `run_compiler` is defined here
   --> /var/pisi/rust-1.48.0-17/work/rustc-1.48.0-src/compiler/rustc_driver/src/lib.rs:182:1
    |
182 | / fn run_compiler(
183 | |     at_args: &[String],
184 | |     callbacks: &mut (dyn Callbacks + Send),
185 | |     file_loader: Option<Box<dyn FileLoader + Send + Sync>>,
...   |
189 | |     >,
190 | | ) -> interface::Result<()> {
    | |__________________________^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0603`.
error: could not compile `miri`
```

But process still continues and build finishes. Is it important or am I missing something?

**Comment by jyn514** [comment] 2020-12-01 01:51
@IdrisKalp miri is only supported on nightly (and 'supported' is not really the right word - maybe 'distributed'). Since miri is maintained out of tree, when the rustc API changes, miri won't build successfully until the submodule is updated; 1.48 happened to get released while it was broken.

I recommend using rustup + a nightly version miri instead.

**Comment by IdrisKalp** [comment] 2020-12-01 18:58
> 
> 
> @IdrisKalp miri is only supported on nightly (and 'supported' is not really the right word - maybe 'distributed'). Since miri is maintained out of tree, when the rustc API changes, miri won't build successfully until the submodule is updated; 1.48 happened to get released while it was broken.
> 
> I recommend using rustup + a nightly version of miri instead.

Thanks for answer. Actually I'm not a user, I'm a package maintainer at PisiLinux which is a small distribution. And because of the error above, build fails at our farm. So I want to ask is there a way to disable to build miri?

**Comment by jyn514** [comment] 2020-12-01 19:01
How are you building currently? It should be disabled by default.

**Comment by Mark-Simulacrum** [comment] 2020-12-01 19:12
I'm going to go ahead and close this as a duplicate of https://github.com/rust-lang/rust/issues/74709 -- we ideally wouldn't even try to build it, but otherwise it's totally fine to ignore this in build logs.

**Closed by Mark-Simulacrum** 2020-12-01 19:12 UTC
Labels: A-miri, A-rustbuild

**Comment by IdrisKalp** [comment] 2020-12-01 19:37
With `./x.py dist`

**Comment by maruel** [comment] 2020-12-11 20:44
Got this with `./x.py install` with the user/maintainer profile.
