### ISSUE TITLE
unreachable!() in match in loop results in error: match arms have incompatible types

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#37935] opened 2016-11-22 18:46 UTC
```rust
enum Foo {A,B,C}
let x = Foo::A;
for _ in 0..1 {
    match x {
        Foo::A => true,
        Foo::B => false,
        _ => unreachable!()
    }
}
```
```
error[E0308]: match arms have incompatible types
  --> <anon>:13:13
   |
13 |             match x {
   |             ^ expected bool, found ()
   |
   = note: expected type `bool`
   = note:    found type `()`
```
https://is.gd/8DaP31

It works with a semicolon after the `match {}` but the error is confusing.

**Comment by TimNN** [comment] 2016-11-22 18:59
On nightly, you get a better error (``expected type `()`, found type `bool` ``) which you can get on stable using:

```rust
        for _ in 0..1 {
            match x {
                Foo::A => true,
                Foo::B => false,
                _ => false,
            }
        }
```


The reasoning is as follows, I think:

* The block starting in the `for _ ...` line has the type `()`.
* Thus the match is expected to have type `()`.
* But it has type `bool`.
* The semicolon after the match ignores the result of the match, thus the type is `()` then.

**Comment by Mark-Simulacrum** [comment] 2017-05-16 15:26
This feels like not a bug to me, though I'll mark as a diagnostic issue since we probably should suggest adding a `;`.

**Comment by estebank** [comment] 2019-03-08 16:05
The current output is a bit misleading in this case, as the diagnostic doesn't handle the non divergence of unreachable/panic:

```
error[E0308]: match arms have incompatible types
  --> src/main.rs:16:22
   |
13 | /             match x {
14 | |                 Foo::A => true,
   | |                           ---- this is found to be of type `bool`
15 | |                 Foo::B => false,
   | |                           ----- this is found to be of type `bool`
16 | |                 _ => unreachable!()
   | |                      ^^^^^^^^^^^^^^ expected bool, found ()
17 | |             }
   | |_____________- `match` arms have incompatible types
   |
   = note: expected type `bool`
              found type `()`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by estebank** [comment] 2022-11-11 04:15
The current output is

```
error[E0308]: mismatched types
  --> src/main.rs:13:13
   |
13 | /             match x {
14 | |                 Foo::A => true,
15 | |                 Foo::B => false,
16 | |                 _ => unreachable!()
17 | |             }
   | |             ^- help: consider using a semicolon here: `;`
   | |_____________|
   |               expected `()`, found `bool`
```

The type error is because the match expression is the tail expression of a for loop, so it  has to be `()`, [the problem is not `unreachable!()`](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=321454ce935d6dbc8e2f4ecd6f964981). Applying the suggestion solves the issue. Ideally we would also explain what I just did, but I feel like we can close this ticket.

**Closed by estebank** 2022-11-11 04:15 UTC
Labels: C-enhancement, A-diagnostics, T-compiler
