### ISSUE TITLE
Overly verbose diagnostic when calling .as_ref() on type not implementing AsRef

### ISSUE THREAD

**Issue by 8051Enthusiast** [rust-lang/rust#89806] opened 2021-10-12 09:57 UTC
Following code seems to lead to overly long diagnostics: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20%20%200u8.as_ref()%0A%7D

```rust
fn main() {
    0u8.as_ref()
}
```

The current output is:

```
error[E0599]: no method named `as_ref` found for type `u8` in the current scope
   --> b.rs:2:9
    |
2   |     0u8.as_ref()
    |         ^^^^^^ method not found in `u8`
    |
   ::: ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:159:8
    |
159 |     fn as_ref(&self) -> &T;
    |        ------
    |        |
    |        the method is available for `Box<u8>` here
    |        the method is available for `Arc<u8>` here
    |        the method is available for `Rc<u8>` here
    |        the method is available for `Box<&mut u8>` here
    |        the method is available for `Arc<&mut u8>` here
    |        the method is available for `Rc<&mut u8>` here
    |        the method is available for `Box<&u8>` here
    |        the method is available for `Arc<&u8>` here
    |        the method is available for `Rc<&u8>` here
    |
   ::: ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/pin.rs:584:12
    |
584 |     pub fn as_ref(&self) -> Pin<&P::Target> {
    |            ------
    |            |
    |            the method is available for `Pin<&mut u8>` here
    |            the method is available for `Pin<&u8>` here
    |
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Box::new(0u8).as_ref()
    |     ^^^^^^^^^   ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Arc::new(0u8).as_ref()
    |     ^^^^^^^^^   ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Rc::new(0u8).as_ref()
    |     ^^^^^^^^   ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Box::new(&mut 0u8).as_ref()
    |     ^^^^^^^^^^^^^    ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Pin::new(&mut 0u8).as_ref()
    |     ^^^^^^^^^^^^^    ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Arc::new(&mut 0u8).as_ref()
    |     ^^^^^^^^^^^^^    ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Rc::new(&mut 0u8).as_ref()
    |     ^^^^^^^^^^^^    ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Box::new(&0u8).as_ref()
    |     ^^^^^^^^^^   ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Pin::new(&0u8).as_ref()
    |     ^^^^^^^^^^   ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Arc::new(&0u8).as_ref()
    |     ^^^^^^^^^^   ^
help: consider wrapping the receiver expression with the appropriate type
    |
2   |     Rc::new(&0u8).as_ref()
    |     ^^^^^^^^^   ^

```

Note that this happens not just with 0u8 but with most types not implementing AsRef as far as I can see.

**Comment by moxian** [comment] 2021-10-12 11:20
This regressed between 1.52.0 and 1.53.0. Bisection gives:

```
Regression in nightly-2021-04-09
<...>
found 8 bors merge commits in the specified range
  commit[0] 2021-04-07UTC: Auto merge of #82451 - jyn514:defaults, r=Mark-Simulacrum
  commit[1] 2021-04-08UTC: Auto merge of #83986 - Dylan-DPC:rollup-51vygcj, r=Dylan-DPC
  commit[2] 2021-04-08UTC: Auto merge of #82958 - camelid:res-docs, r=petrochenkov
  commit[3] 2021-04-08UTC: Auto merge of #83866 - jyn514:disambiguator-error, r=camelid
  commit[4] 2021-04-08UTC: Auto merge of #83981 - nagisa:nagisa/revert-cfg-wasm, r=Mark-Simulacrum
  commit[5] 2021-04-08UTC: Auto merge of #83500 - camelid:split-debuginfo-docs-cleanup, r=steveklabnik
  commit[6] 2021-04-08UTC: Auto merge of #83763 - alexcrichton:wasm-multivalue-abi, r=nagisa
  commit[7] 2021-04-08UTC: Auto merge of #84008 - Dylan-DPC:rollup-invxvg8, r=Dylan-DPC
  ```
it's very likely #83689 . cc @estebank

**Comment by estebank** [comment] 2021-10-24 00:07
@yuvaldolev the code is being suggested here:

https://github.com/estebank/rust/blob/6b64202d5eebdaddcc246412a795ec32dac0f8f2/compiler/rustc_typeck/src/check/method/suggest.rs#L988-L1070

For the case in the comment above, we might want to delay emitting a suggestion until we've confirmed that importing a trait wouldn't be enough to fix the problem. For the original report... we might want to check whether the trait we've found doesn't have a blanket impl, because those would otherwise always suggest the wrapper types, and would be always wrong.

**Comment by pitaj** [comment] 2021-12-11 05:47
Shouldn't this be closed now that the relevant PR is merged?

**Closed** 2021-12-16 04:52 UTC
Labels: E-easy, A-diagnostics, T-compiler, A-suggestion-diagnostics, D-invalid-suggestion, D-verbose
