### ISSUE TITLE
Crate level attribute does not work in file included by `include` macro

### ISSUE THREAD

**Issue by hehaoqian** [rust-lang/rust#99804] opened 2022-07-27 11:36 UTC
I want to share deny warnings settings among multiple crates,
so I want to use the include! macro to include files

I tried this code:

```
// main.rs
include!("deny_warnings.rs");

fn main() {
}
```

```
// deny_warnings.rs
#![deny(warnings)]
```

I expected to see this happen: *Compilation success*

Instead, this happened: 

error: an inner attribute is not permitted in this context
 --> deny_warnings.rs:1:1
  |
1 | #![deny(warnings)]
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files
  = note: outer attributes, like `#[test]`, annotate the item following them

error: expected item after attributes
 --> deny_warnings.rs:1:1
  |
1 | #![deny(warnings)]
  | ^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

<details><summary>Backtrace</summary>
<p>

</p>
</details>

**Comment by ehuss** [comment] 2022-07-27 19:42
Closing as a duplicate of #66920 (and #47995 and #18810 and https://github.com/rust-lang/rfcs/issues/752).

**Closed by ehuss** 2022-07-27 19:42 UTC
Labels: C-bug
