### ISSUE TITLE
Regression from nightly to nightly

### ISSUE THREAD

**Issue by 0xdeafbeef** [rust-lang/rust#104821] opened 2022-11-24 12:10 UTC
Project successfully compiles on stable.

Fails to compile with nightly:
```
error: `make_transactions_handler::{opaque#0}<'_>` does not live long enough
  --> src/core/generic_contract/mod.rs:43:62
   |
43 |                 on_transactions_found.as_mut().map(|handler| handler as _),
   |                                                              ^^^^^^^
```

How to reproduce:

```sh
cd $(mktemp -d)
git clone https://github.com/broxus/rustc-regression.git
cd rustc-regression
cargo-bisect-rustc --regress error --start 2022-09-24 --end 2022-09-26
```

searched nightlies: from nightly-2022-09-24 to nightly-2022-09-26
regressed nightly: nightly-2022-09-26
searched commit range: https://github.com/rust-lang/rust/compare/3f83906b30798bf61513fa340524cebf6676f9db...f5193a9fcc73dc09e41a90c5a2c97fc9acc16032
regressed commit: https://github.com/rust-lang/rust/commit/f5193a9fcc73dc09e41a90c5a2c97fc9acc16032

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc error --start 2022-09-24 --end 2022-09-26 
```
</details>

**Comment by 0xdeafbeef** [comment] 2022-11-24 12:14
Possibly related to https://github.com/rust-lang/rust/issues/104445https://github.com/rust-lang/rust/issues/104445

**Comment by Mark-Simulacrum** [comment] 2022-11-24 12:30
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/104445 and is a beta regression. Currently the expectation is that this is intentional and will land in stable with 1.66. If you have questions about your particular case I would ask in that thread.

**Closed by Mark-Simulacrum** 2022-11-24 12:30 UTC
