### ISSUE TITLE
ICE missing type for FullRange after different type error

### ISSUE THREAD

**Issue by indirect** [rust-lang/rust#21081] opened 2015-01-13 07:16 UTC
```
$ rustc --version --verbose
rustc 1.0.0-dev (431105a70 2015-01-10 23:40:20 +0000)
binary: rustc
commit-hash: 431105a70acaf6e0a1d64b6dd3f69563d6694287
commit-date: 2015-01-10 23:40:20 +0000
host: x86_64-apple-darwin
release: 1.0.0-dev

$ RUST_BACKTRACE=1 cargo run --example set02-challenge12                                                                                              
   Compiling matasano_challenges v0.0.1 (file:///Users/andre/src/indirect/matasano_challenges)
/Users/andre/src/indirect/matasano_challenges/examples/set02-challenge12.rs:49:30: 49:35 error: type `collections::vec::Vec<u8>` does not implement any method in scope named `dup`
/Users/andre/src/indirect/matasano_challenges/examples/set02-challenge12.rs:49         let mut input = base.dup();
                                                                                                            ^~~~~
error: internal compiler error: no type for node 290: expr FullRange (id=290) in fcx 0x109fed8f8
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/andre/src/rust-lang/rust/src/libsyntax/diagnostic.rs:182

stack backtrace:
   1:        0x10894a545 - sys::backtrace::write::h450bcd92a1930213oCt
   2:        0x10896c9ff - failure::on_fail::h5f135a792fd11d202Hz
   3:        0x1088d864a - rt::unwind::begin_unwind_inner::h586110a3a4113840Spz
   4:        0x106633287 - rt::unwind::begin_unwind::h14700227130892330230
   5:        0x106633bf8 - diagnostic::Handler::bug::h7575b86c5c618379tWF
   6:        0x105c289b8 - session::Session::bug::hef62e8a762f68d34lRq
   7:        0x1056f6837 - check::FnCtxt<'a, 'tcx>::node_ty::h23bf1bc6fe4a5e34wcm
   8:        0x105707e76 - check::writeback::WritebackCx<'cx, 'tcx>::visit_node_id::h7f37de8aa9093e40bEb
   9:        0x105705c43 - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h5ac00d4f168f565cbub
  10:        0x105705ead - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_expr::h5ac00d4f168f565cbub
  11:        0x10570724f - check::writeback::WritebackCx<'cx, 'tcx>.Visitor<'v>::visit_block::h54d45562db946da9qvb
  12:        0x105789200 - check::check_bare_fn::hdaeeb35bd05a454aG3j
  13:        0x105780b15 - check::check_item::haf214436ff902f12tmk
  14:        0x10584867f - check_crate::unboxed_closure.30679
  15:        0x105843e83 - check_crate::h498cd2b3aa1033f8Z4x
  16:        0x1051af202 - driver::phase_3_run_analysis_passes::h44b8025d7b2dd9b9gwa
  17:        0x105195c10 - driver::compile_input::h3e5fabea6c1b4a12xba
  18:        0x1052617aa - monitor::unboxed_closure.22560
  19:        0x10525ff05 - thunk::F.Invoke<A, R>::invoke::h1047963948223774393
  20:        0x10525ece0 - rt::unwind::try::try_fn::h10084835668746465240
  21:        0x108a143a9 - rust_try_inner
  22:        0x108a14396 - rust_try
  23:        0x10525f3dc - thunk::F.Invoke<A, R>::invoke::h15193227733317482430
  24:        0x10895a1e4 - sys::thread::thread_start::h0b03ecda2bd46a17frw
  25:     0x7fff8e9a12fc - _pthread_body
  26:     0x7fff8e9a1279 - _pthread_body

Could not compile `matasano_challenges`.

To learn more, run the command again with --verbose.
```

I think this covers everything in the bug report guide, but if I missed anything, let me know!

**Comment by jdm** [comment] 2015-01-13 07:20
A link to the code that reproduces this would be valuable :)

**Comment by indirect** [comment] 2015-01-13 17:22
@jdm oh, sure. :) [This commit](https://github.com/indirect/matasano_challenges/commit/4b98ecf9aae409d6b38b5914dc7a5da1e9427eb2) reproduces the panic when `cargo run --example set02-challenge12` is run.

**Comment by tamird** [comment] 2015-04-21 23:57
@indirect can you reduce this down to a standalone repro case?

**Comment by indirect** [comment] 2015-04-22 04:51
@tamird I doubt it, I'm not very familiar with rust. Is being able to check out the exact code that reproduces the error not enough to debug it?

**Comment by tamird** [comment] 2015-04-22 05:00
it's virtually a certainty that that code will not compile with today's `rustc` for reasons other than the ones reported here :(

**Comment by steveklabnik** [comment] 2015-04-22 15:06
From a glance, the code looks like it should work, with the new `extern crate` annotation.

**Comment by bltavares** [comment] 2015-10-25 00:35
The example file does not compile due to syntax changes.

**Comment by brson** [comment] 2017-03-23 16:50
Old bug without a test case. Closing.

**Closed by brson** 2017-03-23 16:50 UTC
Labels: I-ICE
