### ISSUE TITLE
Recursive type error is over-eager

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#68748] opened 2020-02-01 22:27 UTC
Example code:
```rust
use std::marker::PhantomData;

trait Request {
    type Downgraded: Request;
}

enum Test<R: Request> {
    A(PhantomData<dyn FnOnce() -> R>),
    B(Test<R::Downgraded>),
}
```

This code will error with `error[E0072]: recursive type `Test` has infinite size`, but it doesn't necessarily *have* infinite size, it depends how the chain of "request downgrades" is terminated.

For example, if I terminate the downgrade chain by defining a request that downgrades to itself, and is uninhabited, then the enum makes perfect sense.

**Comment by estebank** [comment] 2020-02-01 23:15
Rust needs to know how big `Test` is in memory. Because there's an infinite number of possible representations for the `enum Test` as written, it is denied with `E0072`. What you have to do so that Rust can know what the size of `Test` is regardless of what `B` is holding is to [use `Box<Test<R::Downgraded>>` ](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b05a2620c5349c8df7c5eda850330829).

**Comment by Diggsey** [comment] 2020-02-01 23:40
@estebank for a (well-terminated) set of `Request` types there is only one possible representation.

When  `R` is uninhabited, then the `A` branch of the enum is impossible. An enum with only a single branch should have zero size.

Here's a simpler (but less practically useful) example:
```rust
enum Test {
    Foo(Test)
}
```

This enum will give the same error, but it's only inhabited by a single value, and that value can be zero-sized.

**Comment by jonas-schievink** [comment] 2020-02-01 23:43
I suppose the issue comes down to rustc trying to prove that *any* possible substitution of generic parameters yields a nonrecursive type. I'm not sure this should be changed, since most reasoning the compiler does takes place on generic structures.

**Comment by Diggsey** [comment] 2020-02-01 23:46
My last example doesn't involve any generic types though.

**Comment by estebank** [comment] 2020-02-02 00:47
@Diggsey Rust needs to lay out the side of all data types in a single representation that ends up taking a certain size. If you have a `u32`, we know that it will take the following space in memory, where each `_` is 8 bits: `_, _, _, _`. When you have an `enum Foo { A, B }`, the memory required to represent it is only a single `_` because internally they are represented as "tagged enums", meaning an integer with a value assigned to each variant. When you have `enum Bar { A(u32), B(u32) }` the representation will be `_, _, _, _, _` because it needs 4 bytes to hold the `u32` values of either variant, plus 1 byte to hold enough information to know which variant we have.

When you try to represent `enum Test { Foo(Test) }` in memory, to know the size of `Test` we must know the size of `Foo(Test)`, which requires us to _know_ the size of `Test`, which means it is "infinitely" recursive when it comes to Rust's semantics. When you use `enum Test { Foo(Box<Test>), Bar }`, what you're saying is that `Test` has two variants, so we need `_` to hold which variant we are talking about, and a variant holding an owned pointer to some place in the heap that will hold some `Test`. Because pointers are _all_ the same size (architecture dependent, but for Rust's semantics: always `usize`), variant `Foo`, and by extension `Test`, is now representable with a single known size: `_, _, _, _, _, _, _, _, _`, 1 byte for the variant tagging and 8 bytes for the pointer to any `Test`. This is also why `enum Test<'a> { Foo(&'a Test) }` would also work, by the way: all borrows are also pointers internally.

The reason `Box` is not automatically used everywhere is because they require two lookups to do anything with the data, and if the data we're dealing with is smaller than a register, that makes it much slower, but in practice it is rarely a problem.

**Comment by Diggsey** [comment] 2020-02-02 00:59
@estebank I'm well aware of the semantics of boxes and references, and I'm definitely not suggesting that rustc insert them here - indeed the whole point of this is to avoid the (unnecessary) indirection.

Let me demonstrate the difference between a real infinitely sized type and another "not really" infinitely sized type:

```rust
struct ReallyInfinite {
    x: ReallyInfinite,
    y: i8,
}
```

Here you have `sizeof(ReallyInfinite) == sizeof(ReallyInfinite) + sizeof(i8)` which of course has no solution.

```rust
struct NotInfinite {
    x: NotInfinite,
}
```

Here you have `sizeof(NotInfinite) == sizeof(NotInfinite)` which has many solutions - the compiler would be free to pick any size to represent this type (and it should pick zero).

**Comment by Ixrec** [comment] 2020-02-02 16:36
Why would you want to write something like `struct NotInfinite { x: NotInfinite }` instead of something like `struct NotInfinite { x: () }` or even `struct NotInfinite;`? What semantics would make the former both possible to implement but also meaningfully different from the latter two?

Or in the original example, why do you want to define `enum Test`'s `B` variant as a recursive instance of `Test` instead of a second `TestInner` type, assuming I'm correctly guessing that you only intend to have "one layer of real nesting" there anyway?

**Comment by Diggsey** [comment] 2020-02-02 17:30
@Ixrec In practice, I have a chain of types like this:
`D -> C -> B -> A -> A -> A ...`

Each type implements a trait with an associated type indicating the next type in the sequence. Each implementation of the trait has logic like "can I handle this? If not, recurse into the associated type". To perform this recursion, it's required that the associated type also implement the trait, and this means there's no way (at compile time) to "terminate" the chain other than to have a type reference itself.

**Comment by Ixrec** [comment] 2020-02-02 18:00
But why can't there be a `Terminator` type with a dummy/default impl of the trait, so the chain becomes `D -> C -> B -> A -> Terminator`?

(this feels like a problem where we might have to see the whole application-level use case in full detail to be convinced that all these constraints are all genuine and not XY problems)

**Comment by Dylan-DPC** [comment] 2023-12-17 09:44
Closing this as it works as intended and the concerns are listed above why this isn't possible

**Closed by Dylan-DPC** 2023-12-17 09:44 UTC
Labels: T-lang, A-docs, C-feature-request
