### ISSUE TITLE
Capturing stdout from test code is inconsistent

### ISSUE THREAD

**Issue by MicahChalmer** [rust-lang/rust#12309] opened 2014-02-16 06:47 UTC
The feature that captures "stdout" for tests doesn't capture all the ways that a test could print to stdout.

``` rust
#[test]
fn output_capture_tests() {
    println!("This gets captured...");
    let _ = std::io::stdout().write_line("but this does not...");
    let _ = std::task::try(proc() { println!("..and neither does this...") });
    let _ = std::run::process_status("/bin/echo", [~"...nor this..."]);
    fail!();
}
```

Only the first `println!` call gets captured--the rest appear intermingled with the test output:

```
running 1 test
but this does not...
..and neither does this...
...nor this...
test output_capture_tests ... FAILED

failures:

---- output_capture_tests stdout ----
    This gets captured...
    task 'output_capture_tests' failed at 'explicit failure', subproc-test-stdout.rs:7


failures:
    output_capture_tests

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```

It would be nice if all of these got captured.

**Comment by steveklabnik** [comment] 2015-01-23 02:52
This is still true today with `Thread::scoped`.

**Comment by aturon** [comment] 2015-02-16 20:52
Nominating for 1.0-beta P-backcompat-libs. We need to finalize our capture story.

**Comment by pnkfelix** [comment] 2015-02-19 21:18
1.0 beta, P-backcompat-libs, I-needsdecision

**Comment by aturon** [comment] 2015-03-24 19:18
triage: (1.0)

**Comment by aturon** [comment] 2015-03-24 19:18
triage: P-high (1.0)

**Comment by dbrgn** [comment] 2016-03-16 13:34
I also stumbled over this issue when starting a test server as a child process. The stdout logged by the server does not get captured.

**Comment by nagisa** [comment] 2016-10-20 16:52
@alexcrichton just an idea, but how about we use something like `freopen` (and `dup` to keep stdout around as a different fd) to replace the stdout file descriptor for the duration of the testing? It should be cheap enough to be able to do that for tests, it would also capture all sorts of outputs and would let us to avoid that weird thread-local stdout overwrite code we have now.

**Comment by retep998** [comment] 2016-10-20 16:55
@nagisa Can't use `freopen` to deal with Rust's stdout on Windows.

**Comment by alexcrichton** [comment] 2016-10-20 17:03
@nagisa sounds plausible to me, I think there may also be ways to muck around with this on Windows as well. We'd likely still need to fiddle with private APIs in the standard library, however, as on Windows at least we cache the handles returned by the system so if they're reset we'd have to bust that cache.

**Comment by nagisa** [comment] 2016-10-20 17:14
@retep998 [SetStdHandle](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686244(v=vs.85).aspx)?

**Comment by retep998** [comment] 2016-10-20 18:51
@nagisa If Rust didn't cache the result of `GetStdHandle`, then yes that would work.

**Comment by sanmai-NL** [comment] 2018-02-17 17:13
@alexcrichton: [these many](https://github.com/rust-lang/rust/issues/12309#ref-issue-233811087) reports and suggestions for improvement can be circumvented by removing the whole output capturing code and instead optionally report test failures as JSON messages stdout, and assume tests themselves do not pollute stdout. Then we’d be done with these annoyances without putting in [effort](https://github.com/rust-lang/rust/issues/12309#issuecomment-255163503) to unbreak output capturing. Are you open to a PR?

Also, this issue should be moved to the Cargo issue tracker.

**Comment by alexcrichton** [comment] 2018-02-24 20:12
@sanmai-NL I think that such a PR would unfortunately be a breaking change and as a result needs to be considered a little more carefully (e.g. with the dev-tools team). This is still a rustc issue as-is so I don't think it should move.

**Comment by Mark-Simulacrum** [comment] 2019-09-01 13:11
Going to go ahead and close this as a duplicate of https://github.com/rust-lang/rust/issues/42474.

**Closed by Mark-Simulacrum** 2019-09-01 13:11 UTC
Labels: A-libtest, C-enhancement, P-low, T-libs

**Comment by glts** [comment] 2022-11-29 17:13
I suggest that this issue be reopened. It has not been fixed, and there is no explanation for why it should not be considered further, either above or in the linked issue.

I believe it is a current best practice to use `writeln!(std::io::stdout())?` in place of `println!` in programs that should not panic on I/O error. However, this idiom results in stdout not being captured.

**Comment by mathstuf** [comment] 2023-01-30 13:37
I think this is the issue to keep open; #42474 is "fixed" in that output is now captured. It is just "inconsistent".

FWIW, there will always be a way "around" it (talking to `/dev/tty`, using fd 1, etc.). Unless there's some mangling going on under `cfg(test)`, what kinds of effects would `std::io::stdout()` checking some TLS structure add to non-test code?

For child processes, there would need to be some file descriptor/handle juggling in `std::process` to detect `cfg(test)` and relocate the file descriptors if not otherwise set. This also leaves things like `tokio::process` in the dark unless the `test` crate grows some APIs to use (and stabilizes them).

**Comment by mathstuf** [comment] 2023-01-30 13:51
The docs for `std::oi::stdout` state:

> Constructs a new handle to the standard output of the current process.

I don't think that can get an asterisk for "unless running from a `#[test]` function in which case it is a handle to the capture output (if any)". Note that this also gives a way to guarantee bypassing any such capturing (assuming fd 1 isn't closed…which makes me think "what is the behavior on a closed fd 1 here? how about read-only?"). Similarly for `std::process`, bypassing may or may not be wanted in different contexts. That sounds like API design and, again, dependent upon the `test` crate being stabilized anyways.

**Comment by Finomnis** [comment] 2023-07-29 14:05
@Mark-Simulacrum Please re-open, this is not actually a duplicate, and the problem still persists.

**Comment by Houtamelo** [comment] 2023-12-24 23:26
@Mark-Simulacrum Please re-open, this is not actually a duplicate, and the problem still persists.

If not fixed, this should at least be on the documentation.

**Comment by Mark-Simulacrum** [comment] 2023-12-25 00:03
https://github.com/rust-lang/rust/issues/90785 appears to be the current issue tracking this.
