### ISSUE TITLE
Failed to install fortanix-sgx-tools

### ISSUE THREAD

**Issue by laocaoshilaocao** [rust-lang/rust#81773] opened 2021-02-05 04:47 UTC
HI! I was trying to install fortanix-sgx-tools on Linux 18.04 LTS using command 
`cargo install fortanix-sgx-tools sgxs-tools`
I strictly followed the instruction  https://edp.fortanix.com/docs/installation/guide/

The error is as follows:
```
error: internal compiler error: failed to process buffered lint here
   --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.4.1/src/usercalls/mod.rs:917:21
    |
917 |                     bail!("All enclave threads are waiting indefinitely without possibility of wakeup")
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.4.1/src/usercalls/mod.rs:920:21
    |
920 |                     bail!("The enclave performed an invalid usercall 0x{:x}", n)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.4.1/src/usercalls/mod.rs:922:52
    |
922 |                   Err(EnclaveAbort::MainReturned) => bail!(
    |  ____________________________________________________^
923 | |                     "The enclave returned from the main entrypoint in violation of the specification."
924 | |                 ),
    | |_________________^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debug-assertions=off --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `enclave-runner`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: failed to process buffered lint here
   --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.4.1/src/usercalls/mod.rs:917:21
    |
917 |                     bail!("All enclave threads are waiting indefinitely without possibility of wakeup")
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.4.1/src/usercalls/mod.rs:920:21
    |
920 |                     bail!("The enclave performed an invalid usercall 0x{:x}", n)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /home/laocao/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.4.1/src/usercalls/mod.rs:922:52
    |
922 |                   Err(EnclaveAbort::MainReturned) => bail!(
    |  ____________________________________________________^
923 | |                     "The enclave returned from the main entrypoint in violation of the specification."
924 | |                 ),
    | |_________________^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: failed to compile `sgxs-tools v0.8.3`, intermediate artifacts can be found at `/tmp/cargo-installF9qaLP`

Caused by:
  build failed
     Summary Failed to install fortanix-sgx-tools, sgxs-tools (see error(s) above).
error: some crates failed to install
```

Hope to hear from you if any help could be given.

**Comment by jonas-schievink** [comment] 2021-02-05 12:03
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-05 12:03 UTC
Labels: C-bug, I-ICE, T-compiler
