### ISSUE TITLE
Spurious failure while installing deploy dependencies

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#44159] opened 2017-08-29 17:11 UTC
Found in #43938

```
[0Ktravis_fold:end:dpl.0
[0Ktravis_time:start:0914d468
[0Ktravis_fold:start:dpl.1
[33mInstalling deploy dependencies[0m
ERROR:  Could not find a valid gem 'aws-sdk-core' (= 2.10.35) in any repository
ERROR:  Possible alternatives: aws-sdk-core
/home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- aws-sdk (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider.rb:85:in `requires'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/s3.rb:6:in `<class:S3>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/s3.rb:5:in `<class:Provider>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/s3.rb:4:in `<module:DPL>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/s3.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider.rb:59:in `const_get'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider.rb:59:in `block in new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider.rb:56:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/cli.rb:31:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:22:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:22:in `<main>'

travis_fold:end:dpl.1
failed to deploy
```

**Comment by kennytm** [comment] 2017-08-29 18:14
The error means the gem repository is not up-to-date, and a retry will usually fix it. This happened at least twice before:

* https://github.com/rust-lang/rust/pull/43114#issuecomment-315191182
* https://github.com/rust-lang/rust/pull/44012#issuecomment-324242882

Maybe we could do something like `gem update` before deploying to S3.

**Comment by kennytm** [comment] 2017-11-22 09:13
The attempt to fix this at 9cfdabaf3ca626685a3c6ff96f2b9306ee1412c2 **does not** work, it still cannot install an updated gem.

**Comment by kennytm** [comment] 2017-12-05 18:56
Update: We haven't got any simple solutions for this yet https://mozilla.logbot.info/rust-infra/20171205#c13967953-c13968089.

**Comment by kennytm** [comment] 2017-12-06 09:46
The most recent error has an upstream issue at travis-ci/travis-ci#8862, which was caused by Travis's deployment software `dpl` not pinning the AWS SDK version (travis-ci/dpl#718). Additionally AWS has some questionable release strategy which publishes an gem without publishing a required and updated dependency first (aws/aws-sdk-ruby#1667), causing the problem we see here.

An attempt to fix this on upstream can be found at travis-ci/dpl#724. If that (or similar PRs) has been merged, *and* we no longer see this spurious failure happening for 4 weeks, we could close this issue.

**Comment by alexcrichton** [comment] 2018-03-12 21:14
Today's [failure](https://travis-ci.org/rust-lang/rust/jobs/352489864) does seem to coincide with a release of the [`dpl` gem](https://rubygems.org/gems/dpl/versions/1.9.1) (March 12, 2018). As to what that means, no idea!

**Comment by pietroalbini** [comment] 2018-05-24 21:55
Seems like Travis failed to fetch some ruby dependencies again? https://github.com/rust-lang/rust/pull/50937#issuecomment-391857761

**Comment by alexcrichton** [comment] 2018-10-31 13:36
With https://github.com/rust-lang/rust/pull/55304 this should hopefully no longer happen as we're not using Travis's built-in deployment

**Closed by alexcrichton** 2018-10-31 13:36 UTC
Labels: A-spurious, C-bug, T-infra
