### ISSUE TITLE
Document details of Ord for Tuples, Option, Result, others?

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#50727] opened 2018-05-14 03:03 UTC
In #rust, we had a user ask if Ord for (A, B, C) checks left to right or right to left. (It's left to right.)

This should be documented in the stdlib docs somewhere.

Similarly, should be documented for other enums such as Option (Some(T) > None) and Result (uhh, didn't check) and possibly others where it could be something different.

**Comment by hellow554** [comment] 2018-05-14 11:19
Can you please explain why it is important? You may leave this undocumented for future performence optimizations?

**Comment by durka** [comment] 2018-05-14 14:49
Definitely seems like it can't be left undocumented. Changing the sort order of `Option` in a future release would be a breaking change.

The sort order of derived ordering is mentioned in the docs: https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html#derivable

Would you want it somewhere else as well?

**Comment by Havvy** [comment] 2018-05-14 17:40
@durka Even if the impl for these is via a `#[derive]`, that information is disconnected from the actual impls when you look at the docs. And when we look at the impls, we don't see the declaration order of the struct members.

**Comment by QuietMisdreavus** [comment] 2018-05-15 13:48
Documenting derived traits is a duplicate of https://github.com/rust-lang/rust/issues/44118.

Tuples, on the other hand, don't get their trait via derive. [All those traits are applied via a macro](https://github.com/rust-lang/rust/blob/master/src/libcore/tuple.rs), so it's possible to add docs there without extending the language to add arbitrary attributes to a derive.

**Comment by saleemjaffer** [comment] 2019-03-13 07:06
@steveklabnik @estebank I would like to take this up.

**Comment by poliorcetics** [comment] 2020-06-04 18:53
Is there still something to do about this issue ? If yes, I would like to do it, but I see tuples have been documented and from what I understand the rest is apparently not needed.

**Comment by bertptrs** [comment] 2022-05-26 12:07
The ordering for `Option` and `Result` is documented through a small note in the [Derivable](https://doc.rust-lang.org/std/cmp/trait.Ord.html#derivable) section:

> When `derive`d on enums, variants are ordered by their discriminants. By default, the discriminant is smallest for variants at the top, and largest for variants at the bottom. Here’s an example:

And then it lists two examples. The ordering for both `Result` and `Option` is indeed simply `derive`d so that covers that. However that fact could be considered an implementation detail, so I think it's still good to mention it explicitly on the relevant pages.

The sort order for `tuple`s is defined in the [`tuple documentation`](https://doc.rust-lang.org/core/primitive.tuple.html) and I think that should cover it.

**Comment by Dylan-DPC** [comment] 2024-05-17 05:22
Closing this as the documentation now mentions this albeit in different places

**Closed by Dylan-DPC** 2024-05-17 05:22 UTC
Labels: C-enhancement, P-medium, T-libs-api, E-medium, A-docs
