### ISSUE TITLE
Lifetimes are not hygenic

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#55744] opened 2018-11-07 09:15 UTC
I would expect the following to not compile ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=3b69ae86de6d2cf2692bb568b208780d)):
```rust
trait Trait {}

macro_rules! impl_trait_for {
    ($name:path) => { impl<'tcx> Trait for $name {} }
}

impl_trait_for!(Option<i32>);
impl_trait_for!(Option<&'tcx i32>);
```
The lifetime `'tcx` is bound in the macro, and used in a macro argument. This violates hygiene.

I am sure this has already been reported but I cannot find an issue that matches...

**Comment by RalfJung** [comment] 2018-11-07 09:16
Type parameters have the same issue. This compiles as well:
```rust
trait Trait {}

macro_rules! impl_trait_for {
    ($name:path) => { impl<T> Trait for $name {} }
}

impl_trait_for!(Result<T, T>);
```

**Comment by petrochenkov** [comment] 2018-11-07 09:50
This is by design in `macro_rules!`, but fixed in `macro`.

**Comment by pnkfelix** [comment] 2018-11-07 11:05
There's some truly ancient history here, see e.g. #12451 and [meeting from 2014-06-10](https://github.com/rust-lang/meeting-minutes/blob/master/weekly-meetings/2014-06-10.md#hygiene-and-lifetimes)

**Comment by eddyb** [comment] 2018-11-07 13:50
I thought we had to pass lifetimes to macros to make things work, are they hygienic *sometimes*?

**Comment by petrochenkov** [comment] 2018-11-07 13:56
Only labels are hygienic (if those can be counted as lifetimes).

**Comment by petrochenkov** [comment] 2019-01-27 09:36
(Closing as not an issue.)

**Closed by petrochenkov** 2019-01-27 09:36 UTC
Labels: A-lifetimes, A-macros-1.2
