### ISSUE TITLE
unused_extern_crates warns about extern crates that only supply macros

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#35081] opened 2016-07-28 00:23 UTC
I ran into this when using [quick_error](https://crates.io/crates/quick-error).  Minimal test case (along with a Cargo.toml including `quick-error="*"` in `[dependencies]`):

```rust
#![warn(unused_extern_crates)]

#[macro_use]
extern crate quick_error;

quick_error! {
    #[derive(Debug)]
    enum Error {
        Msg(msg: String) {
            from()
            from(s: &'static str) -> (s.to_string())
            description(msg)
            display("{}", msg)
        }
}
```

This produces:
```
src/main.rs:4:1: 4:26 warning: unused extern crate
src/main.rs:4 extern crate quick_error;
              ^~~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:1:9: 1:29 note: lint level defined here
src/main.rs:1 #![warn(unused_extern_crates)]
                      ^~~~~~~~~~~~~~~~~~~~
```

**Comment by sanxiyn** [comment] 2016-07-28 12:35
Closing as a duplicate of #30849. Thanks!

**Closed by sanxiyn** 2016-07-28 12:35 UTC
