### ISSUE TITLE
rustc crashes when trying to look up a field in a struct with an unnamed field

### ISSUE THREAD

**Issue by qwandor** [rust-lang/rust#129692] opened 2024-08-28 15:13 UTC
### Code

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1d1cf2059b339f16132221eeb5cdce33

```Rust
#[repr(C)]
struct Foo {
    _: u64,
    bar: u64,
}

fn f(foo: Foo) {
    foo.bar;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06) running on x86_64-unknown-linux-gnu)
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
error[E0658]: unnamed fields are not yet fully implemented
 --> src/lib.rs:3:5
  |
3 |     _: u64,
  |     ^
  |
  = note: see issue #49804 <https://github.com/rust-lang/rust/issues/49804> for more information

error: unnamed fields can only have struct or union types
 --> src/lib.rs:3:5
  |
3 |     _: u64,
  |     ^^^^^^

thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:892:49:
expect Adt for unnamed field
stack backtrace:
(see below)

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.80.1 (3f5fd8dd4 2024-08-06) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [find_field] find the index of maybe nested field `bar` in `Foo`
#1 [typeck] type-checking `f`
end of query stack
For more information about this error, try `rustc --explain E0658`.
error: could not compile `playground` (lib) due to 2 previous errors
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:892:49:
expect Adt for unnamed field
stack backtrace:
   0:     0x7f3d8deaff05 - std::backtrace_rs::backtrace::libunwind::trace::h23054e327d0d4b55
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f3d8deaff05 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cc587407d7f7f64
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3d8deaff05 - std::sys_common::backtrace::_print_fmt::h4feeb59774730d6b
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f3d8deaff05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3d8df00c4b - core::fmt::rt::Argument::fmt::h105051d8ea1ade1e
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
   5:     0x7f3d8df00c4b - core::fmt::write::hc6043626647b98ea
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
   6:     0x7f3d8dea4bdf - std::io::Write::write_fmt::h0d24b3e0473045db
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
   7:     0x7f3d8deafcde - std::sys_common::backtrace::_print::h62df6fc36dcebfc8
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f3d8deafcde - std::sys_common::backtrace::print::h45eb8174d25a1e76
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f3d8deb2719 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
  10:     0x7f3d8deb24ba - std::panicking::default_hook::hb5d3b27aa9f6dcda
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:298:9
  11:     0x7f3d90f3a0c1 - std[fba9fafec3bdacf8]::panicking::update_hook::<alloc[a325a9cea6fa5e89]::boxed::Box<rustc_driver_impl[ce01f96e2e949677]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f3d8deb2e4b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2026a29033a1b9f6
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
  13:     0x7f3d8deb2e4b - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:799:13
  14:     0x7f3d8deb2bc4 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
  15:     0x7f3d8deb03c9 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f3d8deb28f7 - rust_begin_unwind
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
  17:     0x7f3d8defd1e3 - core::panicking::panic_fmt::ha02418e5cd774672
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
  18:     0x7f3d8defcf8b - core::panicking::panic_display::h5e2ae27b741fd199
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:262:5
  19:     0x7f3d8defcf8b - core::option::expect_failed::h411c8586ddbfa53e
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:1995:5
  20:     0x7f3d9262bfe6 - rustc_hir_analysis[be96d916f40dad1b]::collect::find_field
  21:     0x7f3d9262bd9f - rustc_query_impl[c1633093ec927e0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1633093ec927e0e]::query_impl::find_field::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 4usize]>>
  22:     0x7f3d9262bd65 - <rustc_query_impl[c1633093ec927e0e]::query_impl::find_field::dynamic_query::{closure#2} as core[1a380081440346cb]::ops::function::FnOnce<(rustc_middle[ecc07153edf3c281]::ty::context::TyCtxt, (rustc_span[4d50fd03223eefaa]::def_id::DefId, rustc_span[4d50fd03223eefaa]::symbol::Ident))>>::call_once
  23:     0x7f3d92d135b8 - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::DefaultCache<(rustc_span[4d50fd03223eefaa]::def_id::DefId, rustc_span[4d50fd03223eefaa]::symbol::Ident), rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 4usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, false>
  24:     0x7f3d92d133a6 - rustc_query_impl[c1633093ec927e0e]::query_impl::find_field::get_query_non_incr::__rust_end_short_backtrace
  25:     0x7f3d9261a021 - <rustc_hir_typeck[624c394323d1dd51]::fn_ctxt::FnCtxt>::check_field
  26:     0x7f3d92e9da1e - <rustc_hir_typeck[624c394323d1dd51]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  27:     0x7f3d92e9752b - <rustc_hir_typeck[624c394323d1dd51]::fn_ctxt::FnCtxt>::check_block_with_expected
  28:     0x7f3d92e9cbad - <rustc_hir_typeck[624c394323d1dd51]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7f3d9263b9e7 - rustc_hir_typeck[624c394323d1dd51]::check::check_fn
  30:     0x7f3d92c9abfd - rustc_hir_typeck[624c394323d1dd51]::typeck
  31:     0x7f3d92c998cf - rustc_query_impl[c1633093ec927e0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1633093ec927e0e]::query_impl::typeck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 8usize]>>
  32:     0x7f3d9247faeb - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::VecCache<rustc_span[4d50fd03223eefaa]::def_id::LocalDefId, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, false>
  33:     0x7f3d9247f4e5 - rustc_query_impl[c1633093ec927e0e]::query_impl::typeck::get_query_non_incr::__rust_end_short_backtrace
  34:     0x7f3d92d04677 - rustc_hir_analysis[be96d916f40dad1b]::check_crate
  35:     0x7f3d92db862b - rustc_interface[c31201428b712578]::passes::analysis
  36:     0x7f3d92db8025 - rustc_query_impl[c1633093ec927e0e]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c1633093ec927e0e]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7f3d9308a622 - rustc_query_system[b257ee99c2874caa]::query::plumbing::try_execute_query::<rustc_query_impl[c1633093ec927e0e]::DynamicConfig<rustc_query_system[b257ee99c2874caa]::query::caches::SingleCache<rustc_middle[ecc07153edf3c281]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[c1633093ec927e0e]::plumbing::QueryCtxt, false>
  38:     0x7f3d9308a3cf - rustc_query_impl[c1633093ec927e0e]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  39:     0x7f3d92f3724d - rustc_interface[c31201428b712578]::interface::run_compiler::<core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>, rustc_driver_impl[ce01f96e2e949677]::run_compiler::{closure#0}>::{closure#1}
  40:     0x7f3d9306c869 - std[fba9fafec3bdacf8]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[c31201428b712578]::util::run_in_thread_with_globals<rustc_interface[c31201428b712578]::interface::run_compiler<core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>, rustc_driver_impl[ce01f96e2e949677]::run_compiler::{closure#0}>::{closure#1}, core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>>
  41:     0x7f3d9306c66a - <<std[fba9fafec3bdacf8]::thread::Builder>::spawn_unchecked_<rustc_interface[c31201428b712578]::util::run_in_thread_with_globals<rustc_interface[c31201428b712578]::interface::run_compiler<core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>, rustc_driver_impl[ce01f96e2e949677]::run_compiler::{closure#0}>::{closure#1}, core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1a380081440346cb]::result::Result<(), rustc_span[4d50fd03223eefaa]::ErrorGuaranteed>>::{closure#2} as core[1a380081440346cb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  42:     0x7f3d8debce3b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hdf5fcef8be77a431
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2063:9
  43:     0x7f3d8debce3b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8e8c5ceee46ee198
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2063:9
  44:     0x7f3d8debce3b - std::sys::pal::unix::thread::Thread::new::thread_start::hb85dbfa54ba503d6
                               at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys/pal/unix/thread.rs:108:17
  45:     0x7f3d8ddca609 - start_thread
  46:     0x7f3d8dced353 - clone
  47:                0x0 - <unknown>
```

</p>
</details>

**Comment by matthiaskrgr** [comment] 2024-08-28 15:25
looks like a duplicate of https://github.com/rust-lang/rust/issues/121263

**Comment by fmease** [comment] 2024-08-28 16:50
closing as such

**Closed by fmease** 2024-08-28 16:50 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
