### ISSUE TITLE
rustc is unsure if lto is allowed for rlibs

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#86997] opened 2021-07-09 11:09 UTC
```console
$ bat -p main.rs 
pub extern "C" fn f() -> i32 { 92 }
$ rustc -C lto=fat --crate-type rlib main.rs
$ rustc -C lto=fat --crate-type cdylib main.rs
$ rustc -C lto=fat --crate-type rlib,cdylib main.rs
error: lto can only be run for executables, cdylibs and static library outputs

error: aborting due to previous error
$ rustc --version
rustc 1.54.0-beta.1 (bf62f4de3 2021-06-23)
```

As you see, `rustc` agrees to compile rlib and cdylib with lto separately, but refuses when they are both specified.

**Comment by ehuss** [comment] 2021-07-09 13:56
I think this is a duplicate of #51009.

**Closed** 2021-07-12 14:17 UTC
Labels: A-lto, C-bug
