### ISSUE TITLE
Unexpected panic after opening cargo project with the IntelliJ Rust plugin

### ISSUE THREAD

**Issue by ptato** [rust-lang/rust#71281] opened 2020-04-18 12:31 UTC
`cargo run` with `RUST_BACKTRACE=1` 

```
   Compiling uu v1.0.0 (S:\uu)
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src\librustc_middle\ty\query\on_disk_cache.rs:456:17
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: <std::io::IoSliceMut as core::fmt::Debug>::fmt
   3: std::panicking::take_hook
   4: std::panicking::take_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: <rustc_middle::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
  11: ZN12rustc_middle2ty5print6pretty66_DERIVE_rustc_middle_ty_Lift_lifted_FOR_TraitRefPrintOnlyTraitPath121_$LT$impl$u20$rustc_middle..ty..context..Lift$u20$for$u20$rustc_middle..ty..print..pretty..TraitRefPrintOnlyTraitPath$GT$11lift_to_tcx17h7c265f21e6d9688
  12: <rustc_middle::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
  13: <rustc_builtin_macros::deriving::generic::find_type_parameters::Visitor as rustc_ast::visit::Visitor>::visit_mac
  14: <rustc_typeck::variance::terms::InferredIndex as core::fmt::Debug>::fmt
  15: <rustc_builtin_macros::deriving::generic::find_type_parameters::Visitor as rustc_ast::visit::Visitor>::visit_mac
  16: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  17: <rustc_typeck::variance::terms::VarianceTerm as core::fmt::Debug>::fmt
  18: <rustc_typeck::variance::terms::VarianceTerm as core::fmt::Debug>::fmt
  19: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  20: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  21: <rustc_typeck::astconv::Bounds as core::fmt::Debug>::fmt
  22: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  23: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  24: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  25: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  26: <rustc_typeck::astconv::Bounds as core::fmt::Debug>::fmt
  27: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  28: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  29: <rustc_typeck::check::wfcheck::check_where_clauses::{{closure}}::CountParams as rustc_middle::ty::fold::TypeVisitor>::visit_const
  30: <rustc_builtin_macros::deriving::generic::find_type_parameters::Visitor as rustc_ast::visit::Visitor>::visit_mac
  31: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  32: <rustc_typeck::astconv::Bounds as core::fmt::Debug>::fmt
  33: <rustc_typeck::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as core::fmt::Debug>::fmt
  34: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  35: <rustc_typeck::check::upvar::InferBorrowKind as rustc_typeck::expr_use_visitor::Delegate>::mutate
  36: <rustc_typeck::outlives::explicit::ExplicitPredicatesMap as core::fmt::Debug>::fmt
  37: <rustc_builtin_macros::deriving::generic::find_type_parameters::Visitor as rustc_ast::visit::Visitor>::visit_mac
  38: <rustc_typeck::check::op::Op as core::fmt::Debug>::fmt
  39: rustc_typeck::check_crate
  40: rustc_interface::passes::QueryContext::print_stats
  41: rustc_errors::snippet::MultilineAnnotation::increase_depth
  42: rustc_driver::pretty::print_after_hir_lowering
  43: rustc_driver::pretty::print_after_hir_lowering
  44: rustc_errors::snippet::MultilineAnnotation::increase_depth
  45: rustc_driver::pretty::print_after_hir_lowering
  46: rustc_driver::pretty::print_after_hir_lowering
  47: <rustc_middle::ty::subst::GenericArg as rustc_middle::ty::query::keys::Key>::query_crate
  48: <rustc_middle::ty::subst::GenericArg as rustc_middle::ty::query::keys::Key>::query_crate
  49: rustc_errors::snippet::MultilineAnnotation::increase_depth
  50: rustc_driver::pretty::print_after_hir_lowering
  51: ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Sync$u2b$core..marker..Send$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  52: std::sys::windows::thread::Thread::new
  53: BaseThreadInitThunk
  54: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (7f3df5772 2020-04-16) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [generics_of] processing `<editor::Mode as std::cmp::PartialEq>::eq`
#1 [crate_variances] computing the variances for items in this crate
#2 [variances_of] processing `buffer::PieceList`
#3 [check_item_well_formed] processing `buffer::PieceList`
#4 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `uu`.

To learn more, run the command again with --verbose.
```

Happened after I opened the folder in IntelliJ for the first time. Deleting the target folder fixed the problem and the panic hasn't come up again. Sorry I don't know more.

**Comment by jonas-schievink** [comment] 2020-04-18 12:36
Presumably a duplicate of https://github.com/rust-lang/rust/issues/70924 then

**Closed by jonas-schievink** 2020-04-18 12:36 UTC
