### ISSUE TITLE
unable to install: Option '--docdir=/usr/local/share/doc/rust' is not recognized

### ISSUE THREAD

**Issue by nickdesaulniers** [rust-lang/rust#36682] opened 2016-09-23 21:07 UTC
after a successful `configure` and `make` from top of tree, `make install` fails:

```
...
gen-install-script: 
gen-install-script: CFG_PRODUCT_NAME     := Rust-Documentation 
gen-install-script: CFG_REL_MANIFEST_DIR := rustlib 
gen-install-script: CFG_SUCCESS_MESSAGE  := Rust-documentation-is-installed. 
gen-install-script: CFG_OUTPUT_SCRIPT    := tmp/dist/rust-docs-1.13.0-dev-x86_6 ...
gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-install-script: 
gen-install-script: validating arguments
gen-install-script: 
install: error: Option '--docdir=/usr/local/share/doc/rust' is not recognized
```

**Comment by jedisct1** [comment] 2016-09-24 10:36
Duplicate of #36451

**Comment by alexcrichton** [comment] 2016-09-26 23:15
Indeed closing as a dupe

**Closed by alexcrichton** 2016-09-26 23:15 UTC
