### ISSUE TITLE
Variables moved from in match guards are still accessible in other match arms. 

### ISSUE THREAD

**Issue by Toby-S** [rust-lang/rust#29723] opened 2015-11-09 17:10 UTC
The following code segfaults at runtime on stable, beta, and nightly:

``` rust
fn main() {
    let x = 10;
    let s = Custom { val: Vec::new() };

    match x {
        10 if test(s) => println!("oops"),
        _ => println!("eek {:?}", s.val),
    }
}

#[derive(Debug)]
pub struct Custom {
    val: Vec<u8>,
}

impl Drop for Custom {
    fn drop(&mut self) { println!("Dropping"); }    
}

#[allow(unused_variables)]
fn test(s: Custom) -> bool { false }
```

**Comment by Toby-S** [comment] 2015-11-09 17:12
Possibly aided by #3478?

**Comment by eddyb** [comment] 2015-11-09 17:18
[Shorter testcase](http://is.gd/UNkhnC):
```rust
fn main() {
    let s = String::new();
    let _s = match 0 {
        0 if { drop(s); false } => panic!("oops"),
        _ => {
            // This should trigger an error,
            // s could have been moved from.
            s
        }
    };
}
```

**Comment by eddyb** [comment] 2015-11-09 17:20
cc @rust-lang/compiler

This would be solved by the MIR, right?
The way match guards would be desugared in the MIR, they would be potential ancestors of following match arms, and a MIR borrowck wouldn't be able to miss them.

**Comment by eddyb** [comment] 2015-11-09 17:28
The bug is likely caused by [CFG construction trying to be smart about match guards](https://github.com/rust-lang/rust/blob/00aa3cbecc6723898a04467050891c26a7fdb758/src/librustc/middle/cfg/construct.rs#L487-L496).

**Comment by SDBlumire** [comment] 2015-11-09 17:58
Bringing mine and @eddyb 's IRC conversation into here for readability.

The issue is that the path on the left in the image above does not chain into the path on the right, meaning that `drop(s)` can be followed by `{ s }`.

This seems to be a configuration issue in https://github.com/rust-lang/rust/blob/master/src/librustc/middle/cfg/construct.rs#L429-L529

**Comment by arielb1** [comment] 2015-11-09 21:47
Wait can you move in guards?

**Comment by Manishearth** [comment] 2015-11-10 01:36
@arielb1 you shouldn't be able to

**Comment by Aatch** [comment] 2015-11-10 03:57
Hmm, looks like I missed this case when I fixed a very similar issue (moving in multiple guard expressions). The issue is that the way the final guard is handled means that it acts as if it can't fail. Wiring up the contents of `prev_guards` to arm exit in the case where the arm has no guard and no bindings (including wildcard) should fix it. It should also do the same at the very end, adding edges from the remaining guards to the exit of the match expression.

@Manishearth I tried disallowing it, but there's some code around that moves in guards. Its also a breaking change.

**Comment by Aatch** [comment] 2015-11-10 05:28
Ok, in trying to fix this I ran into an issue that is probably why I didn't handle this case last time. Borrows due to by-ref bindings in matches are scoped the match expression itself, meaning that something like:

```rust
match foo_opt {
  Some(ref foo) if cond => { ... }
  None => { foo_opt.val = bar; }
}
```

will complain that you can't assign to `foo_opt.val` because it's already borrowed (which is clearly not true). It's essentially the canonical example for the kind of thing SEME will solve, except worse.

**Comment by bstrie** [comment] 2015-11-10 08:41
@eddyb How did you get rustc to spit out the CFG like that?

**Comment by Toby-S** [comment] 2015-11-10 09:03
@bstrie ```rustc file.rs -Z unstable-options --unpretty flowgraph=main > out.dot```

**Comment by Manishearth** [comment] 2015-11-10 09:04
Oh, it's `unpretty` now. I knew it used to be `--pretty` and was wondering why it wasn't working.

**Comment by eddyb** [comment] 2015-11-10 10:32
@brson What @Toby-S said, followed by `dot -O -Tpng out.dot` (I would do SVG instead, which tends to be nicer to browse, since you can easily Ctrl+F in it, but I don't know how to host it).

**Comment by Toby-S** [comment] 2015-11-10 10:40
@eddyb `s/brson/bstrie/` :-)

**Comment by nikomatsakis** [comment] 2015-11-12 21:19
Key question is whether it's worth trying to fix this now, or just accelerate efforts to port borrowck to MIR. There are already a number of these sorts of issues that would be fixed by such a thing. @Aatch what efforts did you make to fix this?

**Comment by nikomatsakis** [comment] 2015-11-12 21:19
triage: P-high

High because soundness but maybe we should downgrade to medium or otherwise try to solve via MIR.

**Comment by Aatch** [comment] 2015-11-17 10:44
@nikomatsakis I tried to change the CFG to represent the control flow more accurately but ran into the issue I described above. I think there needs to be a change to the regions around match arms, but I'm less familiar with the code there and not sure what to change or how.

**Comment by nrc** [comment] 2015-11-19 21:25
triage: P-medium

Since we're basically waiting for MIR to fix this, it's not really P-high

**Comment by pnkfelix** [comment] 2015-11-19 21:38
(tagging with `A-mir` since we are waiting for MIR to fix this)

**Comment by KiChjang** [comment] 2016-11-21 20:34
This is still relevant on the latest nightly.

**Comment by eddyb** [comment] 2016-11-21 20:45
@KiChjang I believe it needs MIR bororwck anyway, so that's expected.

**Comment by sp-1234** [comment] 2017-10-03 13:49
Is there an ETA for this or something?
This is defeated memory safety in the safe Rust subset so I guess this must be the top importance…

**Comment by eddyb** [comment] 2017-10-10 16:43
@bstrie "later"? Are you referring to MIR borrowck? That has nothing to do with "earlier" or "later" (in fact, at least until recently, borrowck has always ran second-to-last, just before lints, which probably still are the last thing in the analysis passes, before translation), but rather the underlying abstraction on which the the checking is performed - with MIR, complex language-level constructs do not require as complex of handling, sometimes even being subsumed by the generality of MIR dataflow.

**Comment by arielb1** [comment] 2017-10-31 11:43
Turns out we need either NLL or having differently-typed guard binding and body binding variables to make this work:
```Rust
use std::cell::RefCell;

fn assign<'a, 'b>(x: &RefCell<Option<&'a &'b mut u32>>, y: &'a &'b mut u32) {
    *x.borrow_mut() = Some(y);
}


fn main() {
    let (mut t, mut ten);
    ten = 10;
    t = Some(&mut ten);
    unsound(&mut t);
}

fn unsound<'a>(opt: &'a mut Option<&'a mut u32>) -> Option<&'a mut u32> {
    let store = RefCell::new(None);
    match *opt {
        Some(ref mut x) if {
            // this (making `x` escape from the arm) should be disallowed
            // - `x` shouldn't be `&'a mut &'a mut u32` here
            assign(&store, x);
            false
        } => {
           None
        }
        Some(ref mut x) if { false } => {
            // but just using `x` should be fine: `x` has the type `&'a mut &'a mut u32` here
            Some(x)
        }
        ref mut x => {
            *x = None;
            println!("{:?}", store.borrow());
            None
        }
    }
```

**Comment by pnkfelix** [comment] 2017-12-20 17:03
The current status of MIR-borrowck indicates that we can address the [first example][] and the [second example][]. We also correctly reject the `cfg(segfault)` case in the [third example][]; but it unfortunately *also rejects* the `cfg(not(segfault))` case in that same [third example][].

My inclination is to land regression tests, alongside `feature(nll)`, for the three cases that segfault under AST borrowck. We obviously can also deploy `feature(nll)` as long as it is opt-in while the `cfg(not(segfault))` case continues to be rejected. At that time, we should file a new ticket to investigate extending MIR-borrowck to accept the `cfg(not_segfault))` scenario outlined in the [third example][].

[first example]: https://github.com/rust-lang/rust/issues/29723#issue-115922164
[second example]: https://github.com/rust-lang/rust/issues/29723#issuecomment-155130061
[third example]: https://github.com/rust-lang/rust/issues/29723#issuecomment-340737840

**Comment by nikomatsakis** [comment] 2017-12-20 17:29
FWIW, testing with ariel's example, NLL + MIR borrowck seems to accept `cfg(not(segfault))` and reject `cfg(segfault)`.

**Comment by pnkfelix** [comment] 2018-01-09 15:04
I'm increasing priority on this because we should make sure we address it and other related issues as part of migration to NLL.

**Comment by nikomatsakis** [comment] 2018-01-11 14:53
This is fixed in MIR borrowck:

https://play.rust-lang.org/?gist=3e78648bb9001bd5a96f59d09457f13b&version=nightly

**Comment by nikomatsakis** [comment] 2018-01-18 15:19
Added to #47366 -- this is basically E-needstest now

**Comment by nikomatsakis** [comment] 2018-01-18 15:20
triage: P-medium

**Comment by Manishearth** [comment] 2018-01-18 15:55
https://github.com/rust-lang/rust/pull/47549

**Closed** 2018-01-23 19:57 UTC
Labels: A-borrow-checker, C-bug, E-needstest, I-unsound, P-medium, T-compiler

**Comment by Toby-S** [comment] 2018-01-23 23:09
Awesome! Thanks to everyone who was a part of resolving this
