### ISSUE TITLE
long float assignment crashed compiler

### ISSUE THREAD

**Issue by ford--prefect** [rust-lang/rust#32907] opened 2016-04-12 12:57 UTC
an assignment of pi with big precision makes rustc go nuts:
code line:

let pi: f64 = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067982148086513282306647093844609550582231725359408128481117450284102701938521105559644622948954930381964428810975665933446128475648233786783165271201909145648566923460348610454326648213393607260249141273724587006606315588174881520920962829254091715364367892590360011330530548820466521384146951941511609;

backtrace at http://pastebin.com/4Yb9ezpH

**Comment by alexcrichton** [comment] 2016-04-12 14:56
cc @oli-obk

**Comment by oli-obk** [comment] 2016-04-12 15:12
this is already "fixed": http://is.gd/6x7P43

see #31407 for more

**Comment by rkruppe** [comment] 2016-04-12 16:22
Well not fixed but known and already has an issue.

Man I should really get around to fixing that.

**Comment by alexcrichton** [comment] 2016-04-12 16:40
Ah ok, closing as a dupe of https://github.com/rust-lang/rust/issues/31407

**Closed by alexcrichton** 2016-04-12 16:40 UTC
