### ISSUE TITLE
ICE: type_of with ty_projection

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#23439] opened 2015-03-17 13:17 UTC
```
error: internal compiler error: type_of with ty_projection
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:190

stack backtrace:
   1:     0x7fab454c2034 - sys::backtrace::write::he62bcb548164e961YyC
   2:     0x7fab454e7df8 - panicking::on_panic::h3cb4936e695d67bdOGI
   3:     0x7fab4541efaa - rt::unwind::begin_unwind_inner::hfe13dbe91daef70cmnI
   4:     0x7fab428bd41d - rt::unwind::begin_unwind::h10911018176195016387
   5:     0x7fab428bdc65 - diagnostic::Handler::bug::h3c5d38abd490322elgB
   6:     0x7fab432d507b - session::Session::bug::h23eaba6d447e27ca3yn
   7:     0x7fab44b5f17f - trans::type_of::in_memory_type_of::hd518d125e463ffd5lEo
   8:     0x7fab44b5ef41 - trans::type_of::in_memory_type_of::hd518d125e463ffd5lEo
   9:     0x7fab44c61137 - trans::foreign::foreign_signature::h4618e8fc5486898feOB
  10:     0x7fab44c60603 - trans::foreign::foreign_types_for_fn_ty::hbb4f8804cec19fffKPB
  11:     0x7fab44c15e2f - trans::foreign::register_rust_fn_with_foreign_abi::hff88e81da38aeb0f6gB
  12:     0x7fab44b1e905 - trans::base::get_item_val::hfbaf01eba019b69eVnu
  13:     0x7fab44b1bb50 - trans::base::trans_item::h1506a2e4228c48caCSt
  14:     0x7fab44c1859c - trans::base::trans_crate::h6ca4511310a24dc9fPu
  15:     0x7fab45af55c3 - driver::phase_4_translate_to_llvm::h44ad816874743241kOa
  16:     0x7fab45ad11b3 - driver::compile_input::h3bad48bfc23f6006Rba
  17:     0x7fab45b88b02 - run_compiler::haa99afb1c99d7db1x2b
  18:     0x7fab45b8694c - thunk::F.Invoke<A, R>::invoke::h10898031602178947258
  19:     0x7fab45b859d0 - rt::unwind::try::try_fn::h4687345873392121579
  20:     0x7fab45558fc8 - rust_try_inner
  21:     0x7fab45558fb5 - rust_try
  22:     0x7fab45b85e76 - thunk::F.Invoke<A, R>::invoke::h18058446263424162958
  23:     0x7fab454d69f5 - sys::thread::thread_start::h8ed6b7636995fe24B1G
  24:     0x7fab3f39e373 - start_thread
  25:     0x7fab450a027c - __clone
  26:                0x0 - <unknown>
```

**Comment by cmr** [comment] 2015-03-17 13:22
```rust
struct C;

trait Num {
    type Float: Copy;
}

extern fn csrot_wrap(_: <C as Num>::Float) { }

impl Num for C {
    type Float = f32;
```

**Comment by cmr** [comment] 2015-03-17 13:25
cc @aturon, @nikomatsakis

**Comment by cmr** [comment] 2015-03-17 13:26
(Workaround: don't reference the associated type, replace it with its definition)

**Comment by davekong** [comment] 2015-03-25 16:36
I don't know if this is related, but I got the same error when ran the code
```rust
pub trait Factory {
    type W: Widget;
    
    fn new_widget(&self) -> Self::W;
}

pub trait Widget {
    fn turn(&mut self);
}

pub struct FailFactory {
    factory: Box<Factory>
}

impl FailFactory {
    /*
    pub fn fictious_type_fail(&mut self) {
    self.factory.new_widget();
    }
    */
    pub fn ty_projection_fail(&mut self) {
        let mut widget = self.factory.new_widget();
        widget.turn();
    }
}

fn main() {}
```
However, if I uncomment  `fictious_type_fail` and comment out `ty_projection_fail`, then I get the error:
```
error: internal compiler error: fictitious type <Factory as Factory>::W in sizing_type_of()
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:190
```

**Comment by SkylerLipthay** [comment] 2015-04-07 07:42
```rust
use std::collections::BTreeMap;

pub trait Versioned {
    type Version: Ord;

    fn version(&self) -> Self::Version;
}

#[allow(dead_code)]
pub struct Controller<T: Versioned + ?Sized> {
    migrations: BTreeMap<T::Version, Box<T>>
}

impl<T: Versioned + ?Sized> Controller<T> {
    pub fn new() -> Controller<T> {
        Controller { migrations: BTreeMap::new() }
    }
}

pub trait ExtendedVersioned : Versioned {
    type Version = i64;
}

#[allow(dead_code)]
pub struct ExtendedController {
    migrator: Controller<ExtendedVersioned>
}

impl ExtendedController {
    pub fn new() -> ExtendedController {
        ExtendedController { migrator: Controller::new() }
    }
}
```

```
error: internal compiler error: type_of with ty_projection
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:190

stack backtrace:
   1:        0x1134698f7 - sys::backtrace::write::h1feed23329bb1716DJC
   2:        0x113497813 - panicking::on_panic::hf92b99c53fdf643bPxI
   3:        0x1133bbc5e - rt::unwind::begin_unwind_inner::h0bdcab28492dff0aqfI
   4:        0x112b8e12e - rt::unwind::begin_unwind::h15271973076642037093
   5:        0x112b8e979 - diagnostic::Handler::bug::h690b37fb3bd82960EsB
   6:        0x110493077 - session::Session::bug::h605b11f6a18d940bFPq
   7:        0x10ff1c157 - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
   8:        0x10ff1c860 - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
   9:        0x110029776 - vec::Vec<T>.FromIterator<T>::from_iter::h10825907506224819013
  10:        0x10ff1ccbd - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
  11:        0x110029776 - vec::Vec<T>.FromIterator<T>::from_iter::h10825907506224819013
  12:        0x10ff1ccbd - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
  13:        0x110029776 - vec::Vec<T>.FromIterator<T>::from_iter::h10825907506224819013
  14:        0x10ff1ccbd - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
  15:        0x110029776 - vec::Vec<T>.FromIterator<T>::from_iter::h10825907506224819013
  16:        0x10ff1ccbd - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
  17:        0x110029776 - vec::Vec<T>.FromIterator<T>::from_iter::h10825907506224819013
  18:        0x10ff1ccbd - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
  19:        0x110029776 - vec::Vec<T>.FromIterator<T>::from_iter::h10825907506224819013
  20:        0x10ff1ccbd - trans::type_of::in_memory_type_of::h292c6bad712c2420fRo
  21:        0x10ff8305f - trans::type_of::type_of_rust_fn::hda44212bef235e44UEo
  22:        0x10ff8c3a4 - trans::base::decl_rust_fn::h4a3a494c31b34005CFr
  23:        0x10ff9f421 - trans::base::register_fn::h17a29763f3b2616cobu
  24:        0x10ffa23c1 - trans::base::register_method::hd8dd1d8c09735d22yOu
  25:        0x10fea141b - trans::base::get_item_val::h0ce72c8ec41fa0c2ayu
  26:        0x10fe9e79f - trans::base::trans_item::h0b33044d08b3fdbfP2t
  27:        0x10ffa4977 - trans::base::trans_crate::hbf9c1b509aba1c64lZu
  28:        0x10f8c647c - driver::phase_4_translate_to_llvm::h6cfd3a151775345eaOa
  29:        0x10f89ddce - driver::compile_input::hf63e92284d149049Qba
  30:        0x10f95b985 - run_compiler::h8e6dd56ee6a375c9S4b
  31:        0x10f959152 - boxed::F.FnBox<A>::call_box::h12642792261833469410
  32:        0x10f958647 - rt::unwind::try::try_fn::h10069384595608373564
  33:        0x113521b58 - rust_try_inner
  34:        0x113521b45 - rust_try
  35:        0x10f95893a - boxed::F.FnBox<A>::call_box::h1065465868264452274
  36:        0x113480cfd - sys::thread::create::thread_start::h056e16758443c21fweH
  37:     0x7fff94323267 - _pthread_body
  38:     0x7fff943231e4 - _pthread_start
```

**Comment by SkylerLipthay** [comment] 2015-04-08 01:48
cc @jroesch

**Comment by arielb1** [comment] 2015-07-07 12:16
@cmr-s example is the only one that ICE-s current rustc.

**Comment by arielb1** [comment] 2015-10-12 18:25
(the other 2 correctly report a "the value of the associated type `W` (from the trait `Factory`) must be specified" error).

**Comment by arielb1** [comment] 2015-10-12 18:36
duplicate of #28983

**Closed by arielb1** 2015-10-12 18:36 UTC
Labels: A-associated-items, I-ICE
