### ISSUE TITLE
Rustdoc freezes then runs out of memory with #[derive(RustcEncodable)]

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#36863] opened 2016-09-30 17:23 UTC
Cargo.toml:

```toml
[dependencies]
rustc-serialize = "*"
```

Lib.rs:
```rust
/// ```
/// extern crate rustc_serialize;
///
/// #[derive(RustcEncodable)]
/// struct MyStruct {
///     field1: String,
///     field2: i32,
/// }
///
/// ```
pub fn foo() { }
```

On Windows if you run `cargo test`, rustdoc will freeze for about 2 minutes then crash because it ran out of memory. Didn't try Linux.

Removing `#[derive(RustcEncodable)]` fixes the problem.

Version: nightly from 2016-09-28.

**Comment by TimNN** [comment] 2016-10-01 06:50
Earlier nightlies give the error:

```
	error[E0433]: failed to resolve. Did you mean `self::rustc_serialize`?
 --> <anon>:4:10
  |
4 | #[derive(RustcEncodable)]
  |          ^^^^^^^^^^^^^^ Did you mean `self::rustc_serialize`?
```

I already commented a bunch in #36881 (which is a duplicate of this issue), so I'm gonna close this in favour of that one.

**Closed by TimNN** 2016-10-01 06:50 UTC
