### ISSUE TITLE
Order of code affects lifetime resolution

### ISSUE THREAD

**Issue by chlai88** [rust-lang/rust#23108] opened 2015-03-06 07:21 UTC
This playpen code snippet now fails in compile : [playpen](https://play.rust-lang.org/?code=%23!%5Ballow%28unused_variables%29%5D%0Astruct%20Handle%3C%27a%3E%28Option%3C%26%27a%20DropCanary%3E%29%3B%0A%0Aimpl%3C%27a%3E%20Handle%3C%27a%3E%20%7B%0A%20%20%20%20pub%20fn%20set_data%28%26mut%20self%2C%20data%3A%20%26%27a%20DropCanary%29%20%7B%0A%20%20%20%20%20%20%20%20self.0%20%3D%20Some%28data%29%3B%0A%20%20%20%20%20%20%20%20%2F%2F%20save%20data%20raw%20ptr%0A%20%20%20%20%7D%0A%0A%20%20%20%20pub%20fn%20use_data%28%26self%29%20%7B%0A%20%20%20%20%20%20%20%20%2F%2F%20use%20data%20raw%20ptr%0A%20%20%20%20%20%20%20%20println!%28%22alive%3F%22%29%3B%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20main%28%29%20%7B%0A%20%20%20%20let%20mut%20handle%20%3D%20Handle%28None%29%3B%0A%20%20%20%20let%20long_enough_lifetime%20%3D%20DropCanary%7Blabel%3A%22long%22%7D%3B%0A%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20let%20short_lifetime%20%3D%20DropCanary%7Blabel%3A%22short%22%7D%3B%0A%20%20%20%20%20%20%20%20%2F%2Fhandle.set_data%28%26short_lifetime%29%3B%20%2F%2F%20This%20shouldn%27t%20be%20allowed!%0A%20%20%20%20%20%20%20%20handle.set_data%28%26long_enough_lifetime%29%3B%20%2F%2F%20This%20is%20OK%0A%20%20%20%20%7D%0A%0A%20%20%20%20handle.use_data%28%29%3B%0A%7D%0A%0A%2F%2F%2F%20---%20just%20for%20testing%20---%0A%0Astruct%20DropCanary%20%7B%0A%20%20%20%20label%3A%20%26%27static%20str%2C%0A%7D%0A%0Aimpl%20Drop%20for%20DropCanary%20%7B%0A%20%20%20%20fn%20drop%28%26mut%20self%29%20%7B%0A%20%20%20%20%20%20%20%20println!%28%22dropped%3A%20%7B%7D%22%2C%20self.label%29%3B%0A%20%20%20%20%7D%0A%7D)

with error 

    <anon>:23:26: 23:46 error: `long_enough_lifetime` does not live long enough
    <anon>:23         handle.set_data(&long_enough_lifetime); // This is OK
                                     ^~~~~~~~~~~~~~~~~~~~
    <anon>:17:34: 27:2 note: reference must be valid for the block suffix following statement 0 at 17:33...

But if you just swap the following 2 lines, line 17 with line 18, it compiles fine.
```rust
let long_enough_lifetime = DropCanary{label:"long"};
let mut handle = Handle(None);
```

**Comment by Thiez** [comment] 2015-03-06 09:32
I think this is intended. Because items are destroyed in the opposite order that they are created when they go out of scope, the `DropCanary` must live strictly longer than the `Handle`, or otherwise the `Handle` destructor could see a dropped canary :)

**Comment by pnkfelix** [comment] 2015-03-06 10:37
This is all by design.  See #21657 and https://github.com/rust-lang/rfcs/pull/769

**Closed by pnkfelix** 2015-03-06 10:37 UTC

**Comment by pnkfelix** [comment] 2015-03-06 10:45
(If we had a way to attach a lifetime to a struct `Handle <'a>` where the lifetime did not have to outlive the srruct value itself, then this code could be made to work.  There are not plans currently to add such a feature as of right now, though.

**Comment by pnkfelix** [comment] 2015-03-06 10:47
Note also that the reason it is okay to put them on the *same* line is because Handle does not implement Drop.
