### ISSUE TITLE
ICE: Associated Type Normalizer - Normalize Projection Type

### ISSUE THREAD

**Issue by kmcguire3413** [rust-lang/rust#20690] opened 2015-01-07 11:24 UTC
```
   Compiling water v0.14.34-alpha (file:///mnt/host/kmcg3413.net/water.rs)
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:53:1: 61:2 error: internal compiler error: impl `VtableImpl(impl_def_id=DefId { krate: 0, node: 6089 }:compat::MessagesIterator<'a, T>.Iterator, substs=Substs[types=[[_];[];[]], regions=[['_#0r];[];[]]], nested=[[Obligation(predicate=Binder(TraitPredicate(TraitRef(T, core::kinds::Send))),depth=1), Obligation(predicate=Binder(TraitPredicate(TraitRef(T, core::kinds::Sized))),depth=1)];[];[]])` did not contain projection for `Obligation(predicate=<compat::MessagesIterator<'a, T> as TraitRef(compat::MessagesIterator<'a, T>, core::iter::Iterator)>::Item,depth=0)`
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:53 impl<'a, T: Send> Iterator for MessagesIterator<'a, T> {
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:54     fn next(&mut self) -> Option<T> {
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:55         let result = self.proxy.recv_opt();
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:56         match result {
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:57             Result::Ok(t) => Option::Some(t),
/mnt/host/kmcg3413.net/water.rs/src/compat.rs:58             Result::Err(_) => Option::None,
                                                 ...
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123

stack backtrace:
   1:     0x7fb1ad3cf920 - sys::backtrace::write::h36422e877a8b3158yQs
   2:     0x7fb1ad3f5650 - failure::on_fail::hde5005d61795902da3y
   3:     0x7fb1ad35b4a0 - rt::unwind::begin_unwind_inner::ha0668a3a9d73b9a7RHy
   4:     0x7fb1a824baf0 - rt::unwind::begin_unwind::h9147230717703493418
   5:     0x7fb1a824ba80 - diagnostic::SpanHandler::span_bug::hee7de6e88971705bDFF
   6:     0x7fb1ab746c70 - middle::traits::project::project_type::ha3169b6d00cba236CYP
   7:     0x7fb1ab743dd0 - middle::traits::project::opt_normalize_projection_type::h52e80e1c888609adFQP
   8:     0x7fb1ab731890 - middle::traits::project::normalize_projection_type::had1d9d27edaeb68fgPP
   9:     0x7fb1ab745270 - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::h8977cf1010cf2ef8RNP
  10:     0x7fb1aca02990 - middle::ty_fold::TypeFolder::fold_trait_ref::h15244371943192340039
  11:     0x7fb1aca035c0 - middle::ty_fold::VecPerParamSpace<T>.TypeFoldable<'tcx>::fold_with::h3029018912722243389
  12:     0x7fb1aca1eb40 - check::FnCtxt<'a, 'tcx>::instantiate_bounds::haf69ce16fdf22227Nul
  13:     0x7fb1aca37870 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>::check_impl::closure.30018
  14:     0x7fb1aca33ce0 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>::with_fcx::h0df2a1129da2a633Hfi
  15:     0x7fb1aca3a760 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>.Visitor<'v>::visit_item::hc72c9294b1b3f21ftoi
  16:     0x7fb1aca3c5c0 - visit::walk_mod::h2450081392115226323
  17:     0x7fb1aca3a760 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>.Visitor<'v>::visit_item::hc72c9294b1b3f21ftoi
  18:     0x7fb1acc28bd0 - check_crate::unboxed_closure.40283
  19:     0x7fb1acc23820 - check_crate::h4ba306a17295b431iux
  20:     0x7fb1ad910600 - driver::phase_3_run_analysis_passes::h56810662503f92d8Sva
  21:     0x7fb1ad8feaa0 - driver::compile_input::h8d0abf631800220evba
  22:     0x7fb1ad9ca070 - thunk::F.Invoke<A, R>::invoke::h13263903969514368718
  23:     0x7fb1ad9c8e20 - rt::unwind::try::try_fn::h2272437873322108176
  24:     0x7fb1ad4598b0 - rust_try_inner
  25:     0x7fb1ad4598a0 - rust_try
  26:     0x7fb1ad9c9170 - thunk::F.Invoke<A, R>::invoke::h17236552692728063371
  27:     0x7fb1ad3e1490 - sys::thread::thread_start::hd19c7749b7af23e8EGv
  28:     0x7fb1a7a6fa80 - start_thread
  29:                0x0 - <unknown>

Could not compile `water`.

To learn more, run the command again with --verbose.
```
rustc 0.13.0-nightly (ad9e75938 2015-01-05 00:26:28 +0000)
binary: rustc
commit-hash: ad9e759382ad7daed26f86732f41f5f83cd673e2
commit-date: 2015-01-05 00:26:28 +0000
host: x86_64-unknown-linux-gnu
release: 0.13.0-nightly
```

**Comment by jroesch** [comment] 2015-01-07 18:29
cc @nikomatsakis @nick29581 you guys might be interested in this.

**Comment by nikomatsakis** [comment] 2015-01-07 21:13
I think this is a duplicate of https://github.com/rust-lang/rust/issues/20347 -- retest?

**Comment by nikomatsakis** [comment] 2015-01-08 14:40
I'm 99% sure this has been fixed, so going to speculatively close. Feel free to re-open if the error is still occurring. Thanks.

**Closed by nikomatsakis** 2015-01-08 14:40 UTC
Labels: A-associated-items, I-ICE
