### ISSUE TITLE
[error message][regression] Private fields in tuple-struct give unhelpful error message

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/rust#41540] opened 2017-04-25 19:06 UTC
I had a tuple-struct defined `pub Line(f32, f32, f32, f32)` and tried using it from another module without remembering to put `pub` on the fields.

Nightly and Stable have very different error messages, and the stable message is *much* better.

## Nightly and Beta
```
error: tuple struct `Line` is private
  --> testsuite/src/main.rs:44:95
   |
44 |     let lines = evaluator.get_polylines(&result, &ctx).into_iter().map(|((x1, y1), (x2, y2))| formats::lines::Line(x1, y1, x2, y2));
   |                                                                                               ^^^^^^^^^^^^^^^^^^^^
```

## Stable
```
error[E0450]: cannot invoke tuple struct constructor with private fields
  --> testsuite/src/main.rs:44:95
   |
44 |     let lines = evaluator.get_polylines(&result, &ctx).into_iter().map(|((x1, y1), (x2, y2))| formats::lines::Line(x1, y1, x2, y2));
   |                                                                                               ^^^^^^^^^^^^^^^^^^^^ cannot construct with a private field
   |
  ::: testsuite/src/formats.rs
   |
72 |     pub struct Line(f32, f32, f32, f32);
   |                     ---- ---- ---- ---- private field declared here
   |                     |    |    |
   |                     |    |    private field declared here
   |                     |    private field declared here
   |                     private field declared here
```

**Comment by petrochenkov** [comment] 2017-04-25 19:19
Duplicate of https://github.com/rust-lang/rust/issues/39703

**Closed** 2017-04-25 19:50 UTC
