### ISSUE TITLE
Internal Compiler Error

### ISSUE THREAD

**Issue by idokrn** [rust-lang/rust#105926] opened 2022-12-19 22:48 UTC
#### main.rs
```Rust
#[macro_use]
extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![index])
}
```

#### cargo.toml
```toml
[package]
name = "iamaster"
version = "0.1.0"
edition = "2021"


[dependencies]
aws-config = "0.52.0"
aws-sdk-iam = "0.22.0"
tokio = { version = "1", features = ["full"] }
rocket = { version = "0.5.0-rc.2" }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0-nightly (d0dc9efff 2022-12-18)
binary: rustc
commit-hash: d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0
commit-date: 2022-12-18
host: aarch64-apple-darwin
release: 1.68.0-nightly
LLVM version: 15.0.6

```

### Error output

```
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:971:13: failed to get layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>`: unable to determine layout for `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut server::shutdown::Graceful<rocket::http::private::Incoming<rocket::ext::CancellableListener<rocket::Shutdown, L>>, service::make::MakeServiceFn<[closure@rocket::server::<impl Rocket<Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::Shutdown, hyper::common::exec::Exec>>` cannot be normalized
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0:        0x10555a3b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb82c0483c591250d
   1:        0x1055ab8cc - core::fmt::write::hb2c102066b064f08
   2:        0x10554db84 - std::io::Write::write_fmt::hf557b1b61fe3515c
   3:        0x10555a1c4 - std::sys_common::backtrace::print::h21e4bda3f3f18189
   4:        0x10555cc74 - std::panicking::default_hook::{{closure}}::h8d8f9102f395ca1b
   5:        0x10555c9cc - std::panicking::default_hook::hfed120dbc81aa18d
   6:        0x10d7d3ec8 - rustc_driver[ca2e807f7dac3a1c]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x10555d36c - std::panicking::rust_panic_with_hook::h23864d88b5a25542
   8:        0x10d9ed054 - std[c49fdc62f524f5ae]::panicking::begin_panic::<rustc_errors[ac6459121bcf5402]::ExplicitBug>::{closure#0}
   9:        0x10d9e8aac - std[c49fdc62f524f5ae]::sys_common::backtrace::__rust_end_short_backtrace::<std[c49fdc62f524f5ae]::panicking::begin_panic<rustc_errors[ac6459121bcf5402]::ExplicitBug>::{closure#0}, !>
  10:        0x1119eb8ec - std[c49fdc62f524f5ae]::panicking::begin_panic::<rustc_errors[ac6459121bcf5402]::ExplicitBug>
  11:        0x10d9e884c - std[c49fdc62f524f5ae]::panic::panic_any::<rustc_errors[ac6459121bcf5402]::ExplicitBug>
  12:        0x10d9e110c - <rustc_errors[ac6459121bcf5402]::HandlerInner>::span_bug::<rustc_span[f195f32429fa3ca9]::span_encoding::Span, &alloc[f2fe4cb8f3bf02a9]::string::String>
  13:        0x10d9e0cb0 - <rustc_errors[ac6459121bcf5402]::Handler>::span_bug::<rustc_span[f195f32429fa3ca9]::span_encoding::Span, &alloc[f2fe4cb8f3bf02a9]::string::String>
  14:        0x10d911774 - ___rust_alloc_error_handler_should_panic
  15:        0x10d911640 - rustc_middle[9ef40bcf06decd99]::util::bug::opt_span_bug_fmt::<rustc_span[f195f32429fa3ca9]::span_encoding::Span>
  16:        0x1119eb960 - rustc_middle[9ef40bcf06decd99]::util::bug::span_bug_fmt::<rustc_span[f195f32429fa3ca9]::span_encoding::Span>
  17:        0x10d90d150 - <rustc_codegen_llvm[a60f45f91ccd752e]::context::CodegenCx as rustc_middle[9ef40bcf06decd99]::ty::layout::LayoutOfHelpers>::handle_layout_err
  18:        0x10d9064a4 - <rustc_codegen_llvm[a60f45f91ccd752e]::context::CodegenCx as rustc_middle[9ef40bcf06decd99]::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
  19:        0x10d90cd70 - <rustc_codegen_llvm[a60f45f91ccd752e]::context::CodegenCx as rustc_middle[9ef40bcf06decd99]::ty::layout::LayoutOf>::layout_of
  20:        0x10d9017e4 - <rustc_codegen_ssa[d2aa770e3cf52f93]::mir::place::PlaceRef<&rustc_codegen_llvm[a60f45f91ccd752e]::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>
  21:        0x10d9d90ec - <rustc_codegen_ssa[d2aa770e3cf52f93]::mir::FunctionCx<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>>::codegen_place
  22:        0x10d9cf838 - <rustc_codegen_ssa[d2aa770e3cf52f93]::mir::FunctionCx<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>>::codegen_rvalue_operand
  23:        0x10d9d59f8 - <rustc_codegen_ssa[d2aa770e3cf52f93]::mir::FunctionCx<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>>::codegen_block
  24:        0x10d9ccc70 - rustc_codegen_ssa[d2aa770e3cf52f93]::mir::codegen_mir::<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>
  25:        0x10d8e9238 - rustc_codegen_ssa[d2aa770e3cf52f93]::base::codegen_instance::<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>
  26:        0x10d987b24 - <rustc_middle[9ef40bcf06decd99]::mir::mono::MonoItem as rustc_codegen_ssa[d2aa770e3cf52f93]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[a60f45f91ccd752e]::builder::Builder>
  27:        0x10d9f30f8 - rustc_codegen_llvm[a60f45f91ccd752e]::base::compile_codegen_unit::module_codegen
  28:        0x10d950b90 - <rustc_query_system[c3fd5062add3438]::dep_graph::graph::DepGraph<rustc_middle[9ef40bcf06decd99]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[9ef40bcf06decd99]::ty::context::TyCtxt, rustc_span[f195f32429fa3ca9]::symbol::Symbol, rustc_codegen_ssa[d2aa770e3cf52f93]::ModuleCodegen<rustc_codegen_llvm[a60f45f91ccd752e]::ModuleLlvm>>
  29:        0x10d9f7e98 - <rustc_codegen_llvm[a60f45f91ccd752e]::LlvmCodegenBackend as rustc_codegen_ssa[d2aa770e3cf52f93]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  30:        0x10d8e8a14 - rustc_codegen_ssa[d2aa770e3cf52f93]::base::codegen_crate::<rustc_codegen_llvm[a60f45f91ccd752e]::LlvmCodegenBackend>
  31:        0x10d9f9024 - <rustc_codegen_llvm[a60f45f91ccd752e]::LlvmCodegenBackend as rustc_codegen_ssa[d2aa770e3cf52f93]::traits::backend::CodegenBackend>::codegen_crate
  32:        0x10d84ac14 - <rustc_session[3f32e368f2a21df4]::session::Session>::time::<alloc[f2fe4cb8f3bf02a9]::boxed::Box<dyn core[5ae742f38ca95b69]::any::Any>, rustc_interface[f766e045b919de4c]::passes::start_codegen::{closure#0}>
  33:        0x10d877860 - rustc_interface[f766e045b919de4c]::passes::start_codegen
  34:        0x10d876848 - <rustc_interface[f766e045b919de4c]::passes::QueryContext>::enter::<<rustc_interface[f766e045b919de4c]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[5ae742f38ca95b69]::result::Result<alloc[f2fe4cb8f3bf02a9]::boxed::Box<dyn core[5ae742f38ca95b69]::any::Any>, rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>>
  35:        0x10d8c77e0 - <rustc_interface[f766e045b919de4c]::queries::Queries>::ongoing_codegen
  36:        0x10d7b07b4 - rustc_span[f195f32429fa3ca9]::with_source_map::<core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>, rustc_interface[f766e045b919de4c]::interface::run_compiler<core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>, rustc_driver[ca2e807f7dac3a1c]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  37:        0x10d7a43f8 - <scoped_tls[89505061565bdd3d]::ScopedKey<rustc_span[f195f32429fa3ca9]::SessionGlobals>>::set::<rustc_interface[f766e045b919de4c]::interface::run_compiler<core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>, rustc_driver[ca2e807f7dac3a1c]::run_compiler::{closure#1}>::{closure#0}, core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>>
  38:        0x10d77911c - std[c49fdc62f524f5ae]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[f766e045b919de4c]::util::run_in_thread_pool_with_globals<rustc_interface[f766e045b919de4c]::interface::run_compiler<core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>, rustc_driver[ca2e807f7dac3a1c]::run_compiler::{closure#1}>::{closure#0}, core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>>
  39:        0x10d75fd34 - <<std[c49fdc62f524f5ae]::thread::Builder>::spawn_unchecked_<rustc_interface[f766e045b919de4c]::util::run_in_thread_pool_with_globals<rustc_interface[f766e045b919de4c]::interface::run_compiler<core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>, rustc_driver[ca2e807f7dac3a1c]::run_compiler::{closure#1}>::{closure#0}, core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5ae742f38ca95b69]::result::Result<(), rustc_errors[ac6459121bcf5402]::ErrorGuaranteed>>::{closure#1} as core[5ae742f38ca95b69]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:        0x1055659ec - std::sys::unix::thread::Thread::new::thread_start::h57e8ec793595de8e
  41:        0x19fa4c26c - __pthread_deallocate
```

</p>
</details>

**Comment by y21** [comment] 2022-12-19 22:56
Duplicate of #105809 ?

**Comment by idokrn** [comment] 2022-12-19 23:19
Seems like it. Closing !

**Closed** 2022-12-19 23:19 UTC
Labels: I-ICE, T-compiler, C-bug
