### ISSUE TITLE
Assertions about constants getting ignored

### ISSUE THREAD

**Issue by RyanDamerell** [rust-lang/rust#108850] opened 2023-03-07 08:58 UTC
So I was trying to use the `static_assertions` crate when I ran into a weird compiler error. I decided that, for testing purposes, it was worth it to just make it a runtime check rather than compile time. However, I ran into another issue. For example:

```rust
struct X {}
impl X{
    const CHECK: bool = false;
    fn new()->Self {
        assert!(Self::CHECK);
        Self {}
     }
}
fn main(){
    let _ = X::new();
    print!("done");
}
```
The assert won't produce an error at compile time, but it also won't produce an error at runtime (when `X::new()` is called). It gets completely compiled out, if you comment out the assert statement the exact same bytes are generated. 

I assume from a design perspective the expected behavior is essentially to replace the assert line with `panic!("...")`. That being said if it errored (or warned) at compile time I think that would also be reasonable. 

### Meta
This applies to both the stable and nightly versions of `rustc`.

**Comment by RyanDamerell** [comment] 2023-03-07 20:21
Sorry, forgot to include it, but it's exactly what you'd expect.

```rust
fn main(){
    let _ = X::new();
    print!("done");
}
```

This problem also persists if X is not a zero-sized struct, as can be seen [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d011ed440f2c3d76627396ddf5d821c2).

**Comment by zirconium-n** [comment] 2023-03-08 01:40
> Sorry, forgot to include it, but it's exactly what you'd expect.
> 
> ```rust
> fn main(){
>     let _ = X::new();
>     print!("done");
> }
> ```
> 
> This problem also persists if X is not a zero-sized struct, as can be seen [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d011ed440f2c3d76627396ddf5d821c2).

Your provided playground does panic in both debug and release mode.

**Comment by fmease** [comment] 2024-01-26 01:22
> but it also won't produce an error at runtime (when X::new() is called)

I cannot reproduce that, it does panic.

Closing as works as intended.

**Closed by fmease** 2024-01-26 01:22 UTC
