### ISSUE TITLE
[rustdoc] invalid trait doc generation

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#33919] opened 2016-05-28 00:22 UTC
When rustdoc generates doc from trait implementation, it could replace generic ones with the one we have. Example with http://doc.rust-lang.org/nightly/std/cell/struct.RefCell.html :

```text
fn eq(&self, other: &RefCell<T>) -> bool;

This method tests for self and other values to be equal, and is used by ==. Read more

fn ne(&self, other: &Rhs) -> bool;

This method tests for !=.
```

`eq()`'s other argument is &RefCell<T>, but that's not the case for `ne()`. It should be fixed.

cc @nox

**Comment by GuillaumeGomez** [comment] 2016-05-28 00:22
I'm working on it.

**Comment by alexcrichton** [comment] 2016-06-05 05:58
I believe this is a dupe of https://github.com/rust-lang/rust/issues/14072, so I'm going to close this in favor of that.

**Closed by alexcrichton** 2016-06-05 05:58 UTC
