### ISSUE TITLE
Confusing error messages when there are version conflicts

### ISSUE THREAD

**Issue by ksqsf** [rust-lang/rust#64577] opened 2019-09-18 11:05 UTC
```
    Checking cfg-if v0.1.9
    Checking byteorder v0.5.3
    Checking slab v0.4.2
    Checking libc v0.2.62
    Checking byteorder v1.3.2
    Checking log v0.4.8
    Checking iovec v0.1.2
    Checking positioned-io v0.2.2
    Checking bytes v0.4.12
    Checking lengine v0.1.0 (/Users/kaima/src/lengine)
error[E0277]: the trait bound `byteorder::LittleEndian: byteorder::ByteOrder` is not satisfied
  --> src/engine.rs:77:36
   |
77 |                 let len = self.log.read_u64_at::<LE>(offset)?;
   |                                    ^^^^^^^^^^^ the trait `byteorder::ByteOrder` is not implemented for `byteorder::LittleEndian`
```

This error message is too confusing and should be improved, e.g. point out the version numbers, or warn that there are possible conflicts before checking.

**Comment by Mark-Simulacrum** [comment] 2019-09-18 11:43
Duplicate of https://github.com/rust-lang/rust/issues/22750.

**Closed by Mark-Simulacrum** 2019-09-18 11:43 UTC
