### ISSUE TITLE
Emscripten optimizations are not used when building with the --release option 

### ISSUE THREAD

**Issue by davidMcneil** [rust-lang/rust#39626] opened 2017-02-07 20:47 UTC
Emscripten optimizations are not used when building a project with:

`cargo build --release --target asmjs-unknown-emscripten`

The Emscripten optimization level can be forced by placing the following in a .cargo/config
```
[target.asmjs-unknown-emscripten]
rustflags = [
    "-Clink-args=-O3 --memory-init-file 0",
]
```

For example when building the following code...
```rust
use std::time::Instant;

fn main() {
    let start_time = Instant::now();
    let duration = start_time.elapsed();
    println!("Runtime {:.5} ms",
             (duration.as_secs() as f64) * 1000.0 +
             (duration.subsec_nanos() as f64) / 1_000_000.0);
}
```
and then running it using `node target/asmjs-unknown-emscripten/release/example.js` with and without the optimizations forced there is a noticeable difference between the two runtimes.

## Meta
rustc 1.15.0 (10893a9a3 2017-01-19)
binary: rustc
commit-hash: 10893a9a349cdd423f2490a6984acb5b3b7c8046
commit-date: 2017-01-19
host: x86_64-unknown-linux-gnu
release: 1.15.0
LLVM version: 3.9

**Comment by RReverser** [comment] 2017-02-13 11:15
Looks like duplicate of https://github.com/rust-lang/rust/issues/36899 which is implemented in nightly

**Comment by alexcrichton** [comment] 2017-02-13 15:41
Yay!

**Closed by alexcrichton** 2017-02-13 15:41 UTC
