### ISSUE TITLE
[AVR] Invalid asm code "ldd rn, X+N" compiles and produces corrupted binary

### ISSUE THREAD

**Issue by Slickis** [rust-lang/rust#109360] opened 2023-03-19 21:01 UTC
AVR assembler instruction `ldd` is defined only for registers `Y` and `Z`, but not for `X`.
`asm!()` macro accepts it.

I tried this code:

```rust
#[no_mangle]
extern "C" fn main() {
    unsafe {
        ::core::arch::asm!("
                ldd   {tmp}, X+0
                ldd   {tmp}, X+1
            ",
            tmp = out(reg) _,
            in("X") &0xAABB_u16,
        );
    }
}
```

I expected to see this happen: compilation error.

Instead, this happened: rustc produces a binary with a corrupted code.

```
000000a6 <main>:
  a6:    a0 e0           ldi    r26, 0x00    ; 0
  a8:    b1 e0           ldi    r27, 0x01    ; 1
  aa:    88 81           ld     r24, Y
  ac:    89 81           ldd    r24, Y+1     ; 0x01
  ae:    08 95           ret
```
Pointer (0x0100) to a value is loaded into register `X` (`r26:r27`) following by reads from `*Y`.

### Meta

`rustc --version --verbose`:
```
rustc 1.70.0-nightly (22f247c6f 2023-03-13)
binary: rustc
commit-hash: 22f247c6f3ed388cb702d01c2ff27da658a8b353
commit-date: 2023-03-13
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 15.0.7
```

### Steps to reproduce:
repo: https://github.com/Slickis/rustc-ldd-x

```
git clone https://github.com/Slickis/rustc-ldd-x
cd rustc-ldd-x
make lss
```

**Comment by workingjubilee** [comment] 2023-03-27 05:14
Rust does not reject illegal assembly. It does not even inspect it. For the string of the `asm!` macro, Rust performs the formatting instantiation and nothing more. We only control the operands.

**Comment by workingjubilee** [comment] 2023-03-28 01:35
I believe this is more of a documentation issue, not a bug we can solve here. This _could_ be reported to LLVM regarding the AVR assembler implementation they use, as I believe they host the assembler for this. However, ultimately, I expect are a million other followup issues like this, and if they don't care to fix it, then, well, it won't be, and I don't think rustc should carry around an assembler linter inside it that can check every instruction you could possibly give it for every single architecture.

To this end I have opened https://github.com/rust-lang/reference/pull/1344

**Comment by workingjubilee** [comment] 2023-04-09 03:04
Reported upstream as https://github.com/llvm/llvm-project/issues/62012

Hope I got the details correct!

**Comment by Patryk27** [comment] 2023-08-10 17:49
fwiw, this got fixed with https://github.com/rust-lang/rust/pull/114048 🙂

**Closed** 2023-08-10 19:43 UTC
Labels: A-inline-assembly, A-docs, C-bug, O-AVR, llvm-17
