### ISSUE TITLE
Memory leak with all safe rust code

### ISSUE THREAD

**Issue by cgaebel** [rust-lang/rust#21683] opened 2015-01-27 05:31 UTC
```rust
#![allow(unstable)]
#![deny(unsafe_blocks)]

use std::sync::mpsc::{Receiver, SyncSender, sync_channel};
use std::thread::Thread;

struct DropPanics;

impl Drop for DropPanics {
    fn drop(&mut self) {
        panic!("Don't forget to bring your towel.");
    }
}

fn leak(ram_to_waste: usize) {
    let (tx, rx): (SyncSender<()>, Receiver<()>) = sync_channel(1);

    Thread::spawn(move || {
        drop((DropPanics, Vec::<u8>::with_capacity(ram_to_waste))); // <- HERE
        drop(tx);
    });

    match rx.recv() {
        Ok(()) => panic!("This should not be hit."),
        Err(_) => {},
    }
}

fn main() {
    leak(100000);
    println!("fin.");
}
```

**Comment by alexcrichton** [comment] 2015-01-27 05:53
I think this is a dupe of https://github.com/rust-lang/rust/issues/14875, but thanks for the report!

**Closed by alexcrichton** 2015-01-27 05:53 UTC
