### ISSUE TITLE
Borrow checker gets confused with a mutable pointer which should be moved

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#27487] opened 2015-08-03 04:59 UTC
``` rust
pub struct FragmentRepr(Vec<FragmentRepr>);
pub fn accepted(mut entry: &mut FragmentRepr) {
    loop {
        let FragmentRepr(ref mut discrs) = *{entry};
        entry = &mut discrs[0];
    }
}
pub fn rejected(mut entry: &mut FragmentRepr) {
    loop {
        let FragmentRepr(ref mut discrs) = *entry;
        entry = &mut discrs[0];
    }
}
fn main() {}
```

Rust accepts the first function, but rejects the second with "error: cannot borrow `entry.0` as mutable more than once at a time".  It would be nice not to be forced to insert random curly braces to convince the borrow checker that my code is correct.

**Comment by barosl** [comment] 2015-08-03 09:34
I think the reason why the first is accepted is that [blocks unintentionally move out the values of references](https://github.com/rust-lang/rust/issues/26978#issuecomment-120702026) in Rust. I believe this behavior is there by accident, so there's a question: is there an "official" way to do so?

**Comment by arielb1** [comment] 2015-08-03 20:53
If `entry` isn't moved, then the issue here is that borrowck doesn't reason about `&mut FragmentRepr` lacking drop glue - any such drop glue could invalidate `discrs` in the second example.

**Comment by bluss** [comment] 2015-08-04 20:01
@barosl  I think the identity function solution is the best.

```
/// Identity function. Move the input to output.
fn moving<T>(x: T) -> T { x }

let current: &mut _;

// Force move like this
moving(current).next

// we can also write it like this:
let tmp = current;
tmp.next

// or this:
{current}.next

**Comment by steveklabnik** [comment] 2017-01-03 22:24
Triage: so is this a bug or not?

**Comment by Mark-Simulacrum** [comment] 2017-05-19 11:54
@arielb1 Is the bug here "that borrowck doesn't reason about `&mut FragmentRepr` lacking drop glue"?

**Comment by memoryruins** [comment] 2019-01-30 22:17
Triage: both functions compile (as well as when applied to a `FragmentRepr`) on 2018 edition.
2015 errors:

<details>

```
error[E0499]: cannot borrow `entry.0` as mutable more than once at a time
  --> src/main.rs:11:26
   |
11 |         let FragmentRepr(ref mut discrs) = *entry;
   |                          ^^^^^^^^^^^^^^ mutable borrow starts here in previous iteration of loop
...
14 | }
   | - mutable borrow ends here

error[E0506]: cannot assign to `entry` because it is borrowed
  --> src/main.rs:12:9
   |
11 |         let FragmentRepr(ref mut discrs) = *entry;
   |                          -------------- borrow of `entry` occurs here
12 |         entry = &mut discrs[0];
   |         ^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `entry` occurs here

error: aborting due to 2 previous errors
```

</details>

`rustc: 1.32.0`

**Comment by arielb1** [comment] 2019-02-06 16:08
This is indeed intentionally fixed by NLL. `&mut FragmentRepr` can't possibly have drop glue (it is `Copy`).

**Comment by arielb1** [comment] 2019-02-06 16:13
keywords: "copy-vs-move", "orphaned borrow". I seriously need to find the root test for this.

**Comment by arielb1** [comment] 2019-02-06 16:17
duplicate of #46361

**Comment by arielb1** [comment] 2019-02-06 16:17
The test is 
https://github.com/rust-lang/rust/blob/b139669f374eb5024a50eb13f116ff763b1c5935/src/test/run-pass/nll/mutating_references.rs#L1-L26

**Comment by pnkfelix** [comment] 2019-02-27 14:30
okay since this has a test I won't tag it as E-needstest. (Presumably when NLL is turned on across the board we'll just remove `#![feature(nll)]` from all those tests.)

But I'm still going to leave it open since our policy is to leave NLL-fixed-by-NLL bugs open until we turn NLL on across the board

**Closed** 2019-04-22 15:06 UTC
Labels: A-borrow-checker, C-bug, NLL-fixed-by-NLL
