### ISSUE TITLE
ICE with conservative_impl_trait

### ISSUE THREAD

**Issue by tower120** [rust-lang/rust#48140] opened 2018-02-11 11:11 UTC
```
error: internal compiler error: src\librustc_typeck\check\mod.rs:634: escaping regions in predicate Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { substs: Slice([_]), item_def_id: DefId { krate: CrateNum(2), index: DefIndex(0:1693) => core[c2b0]::iter[0]::iterator[0]::Iterator[0]::Item[0] } }, &std::rc::Rc<track::Track>)),depth=0)
  --> src\song.rs:21:38
   |
21 |     pub fn tracks_iter(&mut self) -> impl Iterator<Item = &Rc<Track>>{
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0 (766bd11c8 2018-01-01) running on x86_64-pc-windows-msvc

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:418:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `hello_world_1`.
```

Attaching project as-is.
[RustHelloWorld1.zip](https://github.com/rust-lang/rust/files/1714281/RustHelloWorld1.zip)

**Comment by cramertj** [comment] 2018-02-12 06:31
This looks like the old error from back before lifetime elision was implemented for `impl Trait`. I can't reproduce on the latest nightly. @tower120 can you confirm that your ICE is fixed by updating to the latest nightly release?

**Comment by tower120** [comment] 2018-02-12 06:35
Yes, it is fixed in the latest nightly.

**Comment by cramertj** [comment] 2018-02-12 06:40
@tower120 Great! Let me know if you run into any more ICEs using the feature.

**Closed** 2018-02-12 06:39 UTC
Labels: A-impl-trait, C-bug, I-ICE, T-compiler
