### ISSUE TITLE
3.2_f32 formatted as 0 on powerpc64le

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/rust#96306] opened 2022-04-22 04:23 UTC
In my PR https://github.com/ParkMyCar/compact_str/pull/16 , when formatting 3.2 using std, it gives me 0 on target powerpc64le instead of 3.2 (it works on all other target).

P.S. ryu also format it as 0.0 on it https://github.com/dtolnay/ryu/issues/47

**Comment by mbartlett21** [comment] 2022-04-23 10:34
Did you mean https://github.com/dtolnay/ryu/issues/47 for the ryu issue?

@rustbot label +O-PowerPC

**Comment by NobodyXu** [comment] 2022-04-23 10:36
> Did you mean [dtolnay/ryu#47](https://github.com/dtolnay/ryu/issues/47) for the ryu issue?

Oh yes, thank you for pointing this our

**Comment by NobodyXu** [comment] 2022-04-23 15:17
I just tried to reproduce this on my own x86_64 linux box by running:

```
cross +nightly test --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc-unknown-linux-gnu
```

however, all tests passed without problem...

But the test running on github action still failed on powerpc64le

**Comment by nagisa** [comment] 2022-04-23 22:35
Marked this as I-unsound though I don’t really have a definite culprit here. Historically these sorts of problems have been caused by calling convention mismatches, codegen failures or some other similarly scary and “has potential to cause other code to break much more terribly” problem.

**Comment by nagisa** [comment] 2022-04-23 22:36
> I just tried to reproduce this on my own x86_64 linux box by running:

You used a 32-bit PPC target here. Does this reproduce with a `powerpc64le` target?

```
cross +nightly test --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc64le-unknown-linux-gnu
```

**Comment by NobodyXu** [comment] 2022-04-24 02:13
> `cross +nightly test --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc64le-unknown-linux-gnu`

Thanks for pointing this out again!

With the updated command, I was able to reproduce that.

**Comment by NobodyXu** [comment] 2022-04-24 02:15
Now I was also able to reproduce it using this:

```
fn main() {
    println!("{}", 3.2_f32);
}
```

And it gives me `0` using `cross +nightly run --release --target powerpc64le-unknown-linux-gnu`.

**Comment by NobodyXu** [comment] 2022-04-24 09:44
This is the assembly I get:

```
0000000000008d50 <tests::main>:
    8d50: 09 00 4c 3c  	addis 2, 12, 9
    8d54: b0 f1 42 38  	addi 2, 2, -3664
    8d58: a6 02 08 7c  	mflr 0
    8d5c: 10 00 01 f8  	std 0, 16(1)
    8d60: 51 ff 21 f8  	stdu 1, -176(1)
    8d64: fd ff 62 3c  	addis 3, 2, -3
    8d68: 6c c4 63 38  	addi 3, 3, -15252
    8d6c: 4d fb ff 4b  	bl 0x88b8
    8d70: 00 00 00 60  	nop
    8d74: 60 00 81 f8  	std 4, 96(1)
    8d78: 68 00 61 f8  	std 3, 104(1)
    8d7c: 60 00 61 e8  	ld 3, 96(1)
    8d80: 68 00 81 e8  	ld 4, 104(1)
    8d84: a0 00 81 f8  	std 4, 160(1)
    8d88: a8 00 61 f8  	std 3, 168(1)
    8d8c: a0 00 c1 38  	addi 6, 1, 160
    8d90: ff ff 62 3c  	addis 3, 2, -1
    8d94: c0 48 83 38  	addi 4, 3, 18624
    8d98: 70 00 61 38  	addi 3, 1, 112
    8d9c: 02 00 a0 38  	li 5, 2
    8da0: 01 00 e0 38  	li 7, 1
    8da4: c5 fd ff 4b  	bl 0x8b68
    8da8: 00 00 00 60  	nop
    8dac: 70 00 61 38  	addi 3, 1, 112
    8db0: 59 77 01 48  	bl 0x20508
    8db4: 00 00 00 60  	nop
    8db8: b0 00 21 38  	addi 1, 1, 176
    8dbc: 10 00 01 e8  	ld 0, 16(1)
    8dc0: a6 03 08 7c  	mtlr 0
    8dc4: 20 00 80 4e  	blr
		...
    8dd4: 00 00 00 60  	nop
    8dd8: 00 00 00 60  	nop
    8ddc: 00 00 00 60  	nop
```

**Comment by apiraino** [comment] 2022-05-03 15:18
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2396306.203.2E2_f32.20formatted.20as.200.20on.20powerpc64le) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical

**Comment by pnkfelix** [comment] 2022-05-04 13:17
@NobodyXu any chance you can run your test on older versions of the compiler? If this is a *regression*, then one can even use a tool like https://github.com/rust-lang/cargo-bisect-rustc to identify the point where the regression was injected.

**Comment by NobodyXu** [comment] 2022-05-04 14:10
> @NobodyXu any chance you can run your test on older versions of the compiler? If this is a _regression_, then one can even use a tool like https://github.com/rust-lang/cargo-bisect-rustc to identify the point where the regression was injected.

Yes, but since I don't have a power pc, I will have to use `cross` and `cargo-hack` to perform regression testing as `cross` does not work wit `cargo-bisect-rustc` https://github.com/cross-rs/cross/issues/699

**Comment by NobodyXu** [comment] 2022-05-04 14:24
It seems that the bug is fixed on `cargo 1.62.0-nightly (f63f23ff1 2022-04-28)`.

**Comment by NobodyXu** [comment] 2022-05-04 14:28
`cargo 1.60.0 (d1fd9fe 2022-03-01)` also passed the test, ran using command `cross run --target powerpc64le-unknown-linux-gnu`.

**Comment by NobodyXu** [comment] 2022-05-05 05:35
I think we need more regression tests in `rustc`, having float parsing being broken and randomly fixed isn't a sustainable approach to support `powerpc64le`.

**Comment by NobodyXu** [comment] 2022-05-05 06:15
There are still some strange errors on `powerpc64le` [here](https://github.com/ParkMyCar/compact_str/runs/6301527198?check_suite_focus=true):

```
    assert_eq!("-inf", f32::NEG_INFINITY.to_compact_str());
```

failed with:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"-inf"`,
 right: `"inf"`', compact_str/src/tests.rs:664:5
```

This works on all other platforms except for `powerpc64le`.

**Comment by NobodyXu** [comment] 2022-05-15 09:49
> There are still some strange bugs for `float` on `powerpc64le` [here](https://github.com/ParkMyCar/compact_str/runs/6301527198?check_suite_focus=true):
> 
> ```
>     assert_eq!("-inf", f32::NEG_INFINITY.to_compact_str());
> ```
> 
> failed with:
> 
> ```
> thread 'main' panicked at 'assertion failed: `(left == right)`
>   left: `"-inf"`,
>  right: `"inf"`', compact_str/src/tests.rs:664:5
> ```
> 
> This works on all other platforms except for `powerpc64le`.

On `cargo 1.62.0-nightly (3f052d8ee 2022-05-12)`, the problem described above is fixed.

**Comment by NobodyXu** [comment] 2022-05-16 05:24
@pnkfelix IMO we absolutely need more unit tests for it, as I just witnessed the regression of `f32::NEG_INFINITY` again on `1.63.0-nightly`.

This strange regression that coming back makes it impossible to use [`compact_str`](https://github.com/ParkMyCar/compact_str) or other crates that depends on the float formatting on `powerpc64le` reliably.

**Comment by Emilgardis** [comment] 2022-06-16 03:14
The issues mentioned here might've been issues with QEMU 3.0.1 and fixed with QEMU 5.1.0, see discussion in https://github.com/cross-rs/cross/pull/803#issuecomment-1157174559

It seems this specific case has not been tested on real hardware, but on newer QEMU versions this works just fine.

**Comment by NobodyXu** [comment] 2022-06-16 03:17
Out of curiosity, does rust-lang run CI on actual powerpc machine?

If not, then is this the reason for powerpc to be a tier 2 platform?

**Comment by nagisa** [comment] 2022-06-16 15:17
We don't run CI on a PowerPC host at all, emulated or baremetal, afaik. There are insufficient engineering resources for setting everything up and maintaining and there hasn't been a motivated party who would pick this sort of work up either.

16 Jun 2022 06:17:53 Jiahao XU ***@***.***>:

**Comment by nagisa** [comment] 2022-06-16 16:05
FWIW I’ve just tested the affected crate on a real ppc64le-linux machine running a POWER9 chip. All of 1.58.0, 1.59.0, 1.60.0, 1.61.0, nightly-2022-05-{11,15} successfully ran

```
cargo +$VER test --release --all-features --manifest-path=compact_str/Cargo.toml --target powerpc64le-unknown-linux-gnu -- --include-ignored
```

to completion at both [master](https://github.com/ParkMyCar/compact_str/commit/8449fb1c4ea820237e44ae6fcbfb8854f2d06d3a) and 0ed53d042202550091a71980458d18cbb3919e64.

**Comment by NobodyXu** [comment] 2022-06-17 03:21
@nagisa You would need to remove the cfg [here](https://github.com/ParkMyCar/compact_str/blob/8449fb1c4ea820237e44ae6fcbfb8854f2d06d3a/compact_str/src/tests.rs#L657) and [here](https://github.com/ParkMyCar/compact_str/blob/8449fb1c4ea820237e44ae6fcbfb8854f2d06d3a/compact_str/src/repr/traits.rs#L106).

Mind you that these implementation uses crate ryu to provide better performance.

It will still be able to detect compiler bugs on powerpc though, just that sometimes it gives even stranger bugs.

**Comment by NobodyXu** [comment] 2022-06-17 03:30
@nagisa Checkout this [repository](https://github.com/NobodyXu/rustc-powerpc-foat-bug-reproduce) I used to reproduce the bug.

**Comment by nagisa** [comment] 2022-06-17 10:11
As I wrote in the comment above, I tested the commit [0ed53d042202550091a71980458d18cbb3919e64](https://github.com/ParkMyCar/compact_str/pull/91/commits/0ed53d042202550091a71980458d18cbb3919e64) which removes the cfg in question as well. Was that insufficient?

**Comment by NobodyXu** [comment] 2022-06-17 11:39
> Was that insufficient?

That's sufficient.
Sorry I missed that part.

**Comment by pnkfelix** [comment] 2022-11-11 15:03
[Discussed in P-high review](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202022-11-11.20compiler-team.23559.20P-high.20III/near/309208596)

It appears that this problem is resolved, according to the comments here.

Therefore, closing.

**Closed by pnkfelix** 2022-11-11 15:03 UTC
Labels: P-high, T-compiler, I-unsound, O-PowerPC, C-bug
