### ISSUE TITLE
Rust BSOD on Windows

### ISSUE THREAD

**Issue by dragonDScript** [rust-lang/rust#96245] opened 2022-04-20 10:17 UTC
When trying to install Rust in WSL2 (ubuntu latest) windows continuously gives a BSOD with the code error MEMORY_MANAGEMENT when installing rustc

**Comment by ChrisDenton** [comment] 2022-04-20 10:38
Are you using rustup to installl? If so then this is likely a duplicate of https://github.com/rust-lang/rustup/issues/2887

**Comment by ChrisDenton** [comment] 2022-04-20 15:24
See [Standalone installers](https://forge.rust-lang.org/infra/other-installation-methods.html#standalone-installers).

If you like you can also discuss this issue with the rustup team on the [#wg-rustup discord channel](https://discord.com/channels/442252698964721669/463480252723888159)

**Comment by dragonDScript** [comment] 2022-04-20 18:31
The problem also comes when executing rustc via the standalone option

**Comment by ChrisDenton** [comment] 2022-04-20 18:52
Ah, that's concerning. It is ultimately a Windows bug because a WSL2 application should not be able to cause a BSOD. I found this bug report that may be related https://github.com/microsoft/WSL/issues/7630. The last comment suggests reinstalling wsl and the ubuntu subsystem.

**Comment by dragonDScript** [comment] 2022-04-20 19:04
Maybe it's because WSL2 causes the error, so reinstalling would downgrade to WSL1? a filesystem error?

**Comment by ChrisDenton** [comment] 2022-04-20 20:14
Hm, I don't know. I think it might be best to ask on that issue? It would need a fix there. Rust might be able to workaround it if we knew what triggered it. But then again we might not. It's hard to know either way without more detailed information than we currently have.

**Comment by gimbles** [comment] 2022-04-29 09:48
> Will leave it open to get more attention from people

But..there's no point?

It's a bug in WSL(2), I don't think that we can fix it from Rust's side.

So I believe that this *should* be closed

**Comment by nagisa** [comment] 2022-06-06 20:49
Sorry, broken operating systems are not a rustc bug. Please contact your operating system vendor.

**Closed by nagisa** 2022-06-06 20:49 UTC
Labels: C-bug
