### ISSUE TITLE
thread 'main' panicked at 'attempted to leave type uninitialized, which is invalid (regression 1.47 -> 1.48)

### ISSUE THREAD

**Issue by amarao** [rust-lang/rust#80485] opened 2020-12-29 20:48 UTC
### Code

I tried this code:
https://github.com/amarao/equart/tree/b07f31318b0529d3c01fe5d077497f3511dbc779

(sorry, it happens somewhere deep inside Pison library I use, so the whole application is needed to make it runable).

I expected to see this happen:

Application should work (display a picture).

Instead, this happened:

Application crashes if mouse is moved over the window (Linux).

`thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', .rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9`

It most recently worked on: Rust 1.47

### Version with regression

Rust 1.48.0

```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

### Backtrace

```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/amarao/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer
   4: winit::platform::platform::x11::EventsLoop::process_event
   5: glutin_window::GlutinWindow::poll_event
   6: <glutin_window::GlutinWindow as window::Window>::poll_event
   7: event_loop::Events::next
   8: equart::main
```

**Comment by RalfJung** [comment] 2020-12-29 21:21
This message is intentional, it indicates a bug in the code where the panic is raised. See https://github.com/rust-lang/rust/issues/66151 for further details.

**Comment by RalfJung** [comment] 2020-12-29 21:26
It looks like you are using a rather old version of winit. Does updating to the latest version help? There were some bugfixes there, such as https://github.com/rust-windowing/winit/commit/468b6b83ecd6780281dab352248cf941a201369c

**Comment by jonas-schievink** [comment] 2020-12-29 21:55
Closing as expected behavior

**Closed by jonas-schievink** 2020-12-29 21:55 UTC

**Comment by amarao** [comment] 2020-12-30 10:44
Yes, I've tried to upgrade all dependencies, it does not help. Thanks for reply, I'll try to report it to the piston repo.

**Comment by RalfJung** [comment] 2020-12-30 12:21
Potentially some dependency needs to change its upstream version as well -- you can check the lockfile to see which version of winit you are using. `cargo tree` can help to figure out where the dependency comes from.

**Comment by momomo** [comment] 2022-07-17 09:00
I have the same issue: 

`sslocal -b "127.0.0.1:1080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty" --plugin "v2ray-plugin" --plugin-opts "server;tls;host=github.com"
`thread 'main' panicked at '`UDP_REDIR` is not an id of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', src/service/local.rs:568:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace








`sslocal -b "127.0.0.1:1080" -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty" --plugin "v2ray-plugin" --plugin-opts "server;tls;host=github.com"
`thread 'main' panicked at '`UDP_REDIR` is not an id of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', src/service/local.rs:568:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: clap::parser::matches::arg_matches::ArgMatches::get_arg
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.8/src/parser/matches/arg_matches.rs:1273:17
   3: clap::parser::matches::arg_matches::ArgMatches::value_of
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.8/src/parser/matches/arg_matches.rs:352:19
   4: clap::parser::matches::arg_matches::ArgMatches::value_of_t
             at /Users/j/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.8/src/parser/matches/arg_matches.rs:490:17
   5: shadowsocks_rust::service::local::main
             at /Volumes/m/software/tunnels/shadowsocksrust/git/src/service/local.rs:568:23
   6: sslocal::main
             at /Volumes/m/software/tunnels/shadowsocksrust/git/bin/sslocal.rs:19:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by RalfJung** [comment] 2022-07-17 12:31
@momomo that is not the same issue, your panic message is very different. You will have to talk to the `sslocal` developers about this one.
