### ISSUE TITLE
ICE when attempting to manually implement FnMut

### ISSUE THREAD

**Issue by blaenk** [rust-lang/rust#21461] opened 2015-01-21 07:41 UTC
While trying to figure out how to properly implement `FnMut` for this struct I ran into this ICE. I still don't know how to properly implement it, chances are I was doing it wrong, but I imagine that an ICE isn't expected in any case so I decided to post this up in case it hasn't been brought up.

``` rust
#![feature(unboxed_closures)]

struct VecEnv<'a> {
    vec: Vec<i32>,
}

impl<'a> FnMut(&mut i32, &i32) -> i32 for VecEnv<'a> {
    extern "rust-call" fn call_mut(&mut self, (output, text): (&mut i32, &i32)) -> i32 {
        println!("CLOSURE");
        1i32
    }
}

fn main() {}
```

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: !generic_bounds.has_escaping_regions()', /build/rust-git/src/rust/src/librustc_typeck/check/mod.rs:1784
```

[playpen](http://is.gd/AwHrNx)

**Comment by tamird** [comment] 2015-04-21 23:50
No longer gets that far:
```shell
$ rustc main.rs
main.rs:7:35: 7:38 error: associated type bindings are not allowed here [E0229]
main.rs:7 impl<'a> FnMut(&mut i32, &i32) -> i32 for VecEnv<'a> {
                                            ^~~
error: aborting due to previous error
```

@blaenk can you update this?

**Comment by apasel422** [comment] 2015-10-24 22:00
I'm not sure if this can really be reproduced today. I got the following to compile:

```rust
#![feature(core, unboxed_closures)]

struct VecEnv<'a> {
    vec: Vec<i32>,
    marker: std::marker::PhantomData<&'a ()>,
}

impl<'a, 'b, 'c> FnOnce<(&'b mut i32, &'c i32)> for VecEnv<'a> {
    type Output = i32;

    extern "rust-call" fn call_once(self, (output, text): (&'b mut i32, &'c i32)) -> i32 {
        println!("CLOSURE");
        1i32
    }
}

fn main() {}
```

**Comment by arielb1** [comment] 2015-10-24 22:42
@apasel422 

They used the "impl Fn(i32) -> i32 for XYZ" syntax.

**Comment by arielb1** [comment] 2015-10-24 22:43
duplicate of #24682 + #26638.

**Closed by arielb1** 2015-10-24 22:43 UTC
Labels: A-closures, I-ICE
