### ISSUE TITLE
Beware of GCC 5.x

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#28962] opened 2015-10-11 02:59 UTC
Just a heads-up to others: mingw-w64 (not sure about other platforms) GCC 5.x appears to be subtly mis-compiling LLVM, which results in a segmentation fault during rustc's codegen. 
I've seen this with x86_64-5.1.0- and i686-5.2.0- toolchains.  In the former case LLVM had to be compiled with asserts (--enable-llvm-assertions) for this to occur.

GCC 4.9.3 seems to be OK.

**Comment by alexcrichton** [comment] 2015-10-21 16:23
Closing as a dupe of https://github.com/rust-lang/rust/issues/28260

**Closed by alexcrichton** 2015-10-21 16:23 UTC
Labels: A-build
