### ISSUE TITLE
Error message suggests using `core` when it ought to suggest using `std`

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#23355] opened 2015-03-14 02:31 UTC
Program:
```rust
fn main() {
    Vec::from_iter();
}
```
Output:
```
fri.rs:2:5: 2:19 error: type `collections::vec::Vec<_>` does not implement any method in scope named `from_iter`
fri.rs:2     Vec::from_iter();
             ^~~~~~~~~~~~~~
fri.rs:2:19: 2:19 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
fri.rs:2:19: 2:19 help: candidate #1: use `core::iter::FromIterator`
error: aborting due to previous error
```
Note that it suggests `core::iter::FromIterator` when it could be suggesting `std::iter::FromIterator`. Should a user follow this advice, they would need to also link libcore via `extern crate core`, which (IIRC) means that they will be opting out of 1.0-stable thanks to core's intentional lack of stability.

I don't know if it's worth nominating, but this is definitely a backcompat hazard *for users*.

**Comment by jakub-** [comment] 2015-03-14 13:20
Tempted to close this as a dupe of https://github.com/rust-lang/rust/issues/23224.

**Comment by bstrie** [comment] 2015-11-28 21:41
I think it's worth keeping this open as a more specific example of #23224, because it specifically has implications for stabilizing libcore. I can imagine a short-term hack to resolve this specific issue that would leave #23224 and #13065 for later.

**Comment by arielb1** [comment] 2015-11-28 23:09
@bstrie 

Such a hack will probably not be implemented.

**Comment by bstrie** [comment] 2015-11-29 00:08
@arielb1 I as well don't think it's likely, merely a possibility. :package: 

I also think this is a much bigger pain point for beginners than most people realize. The only reason why I'm suggesting an ugly hack at all is because this must be addressed before libcore hits stable, and its FCP will be coming to a close any day now.

**Comment by arielb1** [comment] 2015-11-29 14:00
@bstrie 

Why does this need to be addressed?

**Comment by bstrie** [comment] 2015-12-02 10:13
@arielb1 I was under the impression that using any API from core directly required a feature flag and hence was only possible on nightly, but I've just experimented and determined that's not the case. So I suppose stabilizing core at this point won't make us any worse off regarding this issue.

**Closed** 2016-03-31 16:03 UTC
Labels: A-diagnostics
