### ISSUE TITLE
Documentation for Iterator::step_by missing `where Self: ?Sized` bound

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#73786] opened 2020-06-27 03:42 UTC
https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.step_by

https://doc.rust-lang.org/nightly/src/core/iter/traits/iterator.rs.html#391-396

The function has the following signature: `fn step_by(self, step: usize) -> StepBy<Self> where Self: Sized`, however the where bound does not show up in the stdlib docs.

I'm not sure what's going on here; I attempted to replicate the situation but a similarly defined trait method in a bare crate works just fine.

cc @GuillaumeGomez

**Comment by ollie27** [comment] 2020-06-27 04:12
Duplicate of #24183

**Closed by ollie27** 2020-06-27 04:12 UTC
Labels: T-rustdoc
