### ISSUE TITLE
Cannot coerce to FnBox with references in arguments

### ISSUE THREAD

**Issue by ebfull** [rust-lang/rust#28222] opened 2015-09-04 01:30 UTC
It doesn't appear to be possible to return a FnBox which accepts references:

```rust
#![feature(fnbox)]

use std::boxed::FnBox;

type Callback = Box<FnBox(&mut usize, &usize)>;

fn get_cb() -> Callback {
    Box::new(|a, b| {})
}

fn main() { }
```

produces the following error on `rustc 1.4.0-nightly (cd138dc44 2015-09-02)`

```
<anon>:8:5: 10:7 error: type mismatch resolving `for<'r, 'r> <[closure@<anon>:8:14: 10:6] as alloc::boxed::FnBox<(&'r mut usize, &'r usize)>>::Output == ()`:
 expected bound lifetime parameter ,
    found concrete lifetime [E0271]
<anon>: 8     Box::new(|a, b| {
<anon>: 9         
<anon>:10     })
<anon>:8:5: 10:7 help: see the detailed explanation for E0271
<anon>:8:5: 10:7 note: required for the cast to the object type `for<'r, 'r> alloc::boxed::FnBox<(&'r mut usize, &'r usize), Output=()> + 'static`
<anon>: 8     Box::new(|a, b| {
<anon>: 9         
<anon>:10     })
<anon>:8:5: 10:7 error: type mismatch: the type `[closure@<anon>:8:14: 10:6]` implements the trait `core::ops::FnOnce<(_, _)>`, but the trait `for<'r, 'r> core::ops::FnOnce<(&'r mut usize, &'r usize)>` is required (expected concrete lifetime, found bound lifetime parameter ) [E0281]
<anon>: 8     Box::new(|a, b| {
<anon>: 9         
<anon>:10     })
<anon>:8:5: 10:7 help: see the detailed explanation for E0281
<anon>:8:5: 10:7 note: required for the cast to the object type `for<'r, 'r> alloc::boxed::FnBox<(&'r mut usize, &'r usize), Output=()> + 'static`
<anon>: 8     Box::new(|a, b| {
<anon>: 9         
<anon>:10     })
error: aborting due to 2 previous errors
```

#25647 is a similar bug when *calling* FnBox.

**Comment by eefriedman** [comment] 2015-09-04 04:16
This seems vaguely familiar... you can get around the error by annotating the types of the variables:
```rust
#![feature(fnbox)]
use std::boxed::FnBox;
type Callback = Box<FnBox(&mut usize, &usize)>;
fn get_cb() -> Callback {
    Box::new(|a: &mut _, b: &_| {})
}
fn main() { }
```

**Comment by arielb1** [comment] 2016-01-10 13:40
Duplicate of #20841.

**Closed by arielb1** 2016-01-10 13:40 UTC
Labels: A-typesystem
