### ISSUE TITLE
Illegal instruction building struct that recurses inside boxed array

### ISSUE THREAD

**Issue by emosenkis** [rust-lang/rust#24732] opened 2015-04-23 19:04 UTC
The following code produces an "Illegal instruction (core dumped)" when run (on linux/x86_64, both in debug and release mode):

```
fn main() {
    let x = T {f: Box::new([None])};
}

struct T {
    f: Box<[Option<T>; 1]>
}
```

**Comment by nagisa** [comment] 2015-04-23 19:09
@emosenkis does that mean you could compile the code successfully?

---

On rustc with LLVM assertions enabled this ICEs:

```
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/DataLayout.cpp:655: unsigned int llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed.
fish: Job 2, “rustc test.rs ” terminated by signal SIGABRT (Abort)
```

**Comment by emosenkis** [comment] 2015-04-23 20:12
@nagisa, yes, it builds just fine (rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16))

**Comment by WaDelma** [comment] 2015-05-22 23:13
Just stumbled to this same problem with code:
https://play.rust-lang.org/?gist=a4461127fde85e760fad&version=nightly

**Comment by emosenkis** [comment] 2015-07-06 18:59
Not sure if it helps any, but @WaDelma's code runs fine on play.rust-lang.org with Stable and Beta now (same error on Nightly) while [my code](https://play.rust-lang.org/?gist=eca09289a0e63281eef5&version=stable) fails with a different error *playpen: application terminated abnormally with signal 4 (Illegal instruction)* with Stable and Beta (still same error on nightly)

**Comment by ldanko** [comment] 2015-07-29 22:56
Sorry, reference to 27337 was added accidentially

**Comment by arielb1** [comment] 2015-10-27 20:19
duplicate of #19001.

**Closed by arielb1** 2015-10-27 20:19 UTC
Labels: I-ICE
