### ISSUE TITLE
Unused generic parameter E0392 not emitted in recursive type that is behind Cell 

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#92561] opened 2022-01-04 21:00 UTC
When you have an unused lifetime (or type) parameter, it is a hard error. If you "use" that parameter by having a recursive type,
`rustc` still notices that it's unused and gives the error. But if that recursion goes through `Cell` (also works with `RefCell`), the error is not emitted and the program works fine. 

Maybe this should be a diagnostics issue, but I put this under bug since it causes programs to compile that shouldn't under the normal rules.

I tried this code:

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f4b12a960ae70ed22f9ee4b753e5d316)

```rust
use std::cell::Cell;

struct GivesAnError<'a> {
    same: Box<GivesAnError<'a>>,
}

#[derive(Debug, Default)]
struct NoError<'a> {
    same: Box<Cell<NoError<'a>>>,
}
```

I expected to see this happen: 
E0392, because the lifetime is actually not used

Instead, this happened:
No error, and the program compiled

### Meta
This happens on the latest `nightly-2022-01-04` on the playground

**Comment by Aaron1011** [comment] 2022-01-04 22:21
This is a very subtle issue. The compiler is not actually checking if the lifetime `'a` get used - it's checking if has its *variance* inferred. With `Box<GivesAnError<'a>>`, there are no constraints placed in the variance of `'a` (`Box` is covariant). However, with `Box<Cell<NoError<'a>>>`, `Cell` ends up forcing `'a` to be **invariant**, allowing the code to compile.

**Comment by SNCPlay42** [comment] 2022-01-05 04:41
Duplicate of #74165

**Comment by Nilstrieb** [comment] 2022-01-05 07:04
Ah, so the normal error is not really a lint but the compiler being forced to abort, that makes sense. I guess it makes sense to close this, since it's a duplicate, I couldn't find the duplicate when searching for duplicates 😅

**Closed** 2022-01-07 10:29 UTC
Labels: C-bug, D-confusing, D-newcomer-roadblock, D-incorrect, A-variance
