### ISSUE TITLE
Nightly: internal compiler error compiling robigalia

### ISSUE THREAD

**Issue by Natrocx** [rust-lang/rust#48119] opened 2018-02-10 10:11 UTC
While compiling the sel4 project from robigalia (GitLab URL: https://gitlab.com/robigalia ; website URL: http://robigalia.org) an internal compiler error occurred.
Error Message: 
```
error: internal compiler error: librustc_metadata/cstore_impl.rs:131: get_optimized_mir: missing MIR for `DefId(2/0:35 ~ sel4_start[df8c]::lang_start[0])`

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:535:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (3bcda48a3 2018-02-09) running on x86_64-unknown-linux-gnu

```
Full Backtrace: https://pastebin.com/pJqkYpJS
No idea at what file it failed sorry

**Comment by Natrocx** [comment] 2018-02-10 10:15
Similiar error message: https://github.com/rust-lang/rust/issues/47858

**Comment by pietroalbini** [comment] 2018-02-10 10:37
The backtrace looks a bit different than #47858 though, I'll keep this open.

**Comment by canarysnort01** [comment] 2018-02-12 02:08
This error first appeared in rustc 1.24.0-nightly (1abeb436d 2017-12-27)

**Comment by canarysnort01** [comment] 2018-02-16 07:55
I think the root cause of this is rustc is incorrectly attempting to monomorphize the lang_start function ```sel4_start::lang_start```, which is in an external crate, when compiling the hello-word crate. I can take a stab at a pr for this.

**Comment by canarysnort01** [comment] 2018-02-17 01:58
hmm no that's not it, not that simple.

**Comment by canarysnort01** [comment] 2018-02-17 02:11
Pinging @bkchr 

Here is robigalia's start lang item function defined in crate ```sel4_start``` (separate from the main function in ```hello-world```):

```rust
#[lang = "start"]
fn lang_start(main: *const u8, _argc: isize, _argv: *const *const u8) -> isize {
    unsafe {
        core::intrinsics::transmute::<_, fn()>(main)();
    }
    panic!("Root server shouldn't ever return from main!");
}
```

Not sure why this is causing problems.

**Comment by canarysnort01** [comment] 2018-02-17 02:28
I think this is the same issue as #47040

**Comment by canarysnort01** [comment] 2018-02-17 06:23
I've modified robigalia to use the new lang_start format and am now getting an llvm assert which I assume is similar to the current problem in #47040 

```
rustc: /mnt/data/projects/rust/src/llvm/lib/IR/Instructions.cpp:2731: static llvm::CastInst* llvm::CastInst::CreateIntegerCast(llvm::Value*, llvm::Type*, bool, const llvm::Twine&, llvm::Instruction*): Assertion `C->getType()->isIntOrIntVectorTy() && Ty->isIntOrIntVectorTy() && "Invalid integer cast"' failed.
```

**Comment by canarysnort01** [comment] 2018-02-17 07:32
The llvm assert was generated when I had this signature for lang_start, from the RFC, returning !:
```rust
fn lang_start<T: Termination>(main: fn() -> T, _argc: isize, _argv: *const *const u8) -> !
```
To get it to work I had to make it use the same signature as the one in the standard library, where it returns isize:
```rust
fn lang_start<T: Termination + 'static>(main: fn() -> T, _argc: isize, _argv: *const *const u8) -> isize
```

**Comment by canarysnort01** [comment] 2018-02-17 09:23
@Natrocx fix merged to robigalia sel4-start master

**Comment by bkchr** [comment] 2018-02-17 11:44
@canarysnort01 sorry for the inconveniences. 
We had to change the `lang_start` function to return `isize`, because some platforms like `wasm` does not support early exit, so we have to return the result.
And in general, yeah, your `lang_start` needs to match the one in the stdlib.

**Comment by canarysnort01** [comment] 2018-02-17 21:46
@bkchr Ah, I see. The rfc kind of read like the changes were opt in so I was bit confused here, thanks for letting me know.

**Comment by sfackler** [comment] 2018-02-17 21:52
Sounds like this is resolved, so closing.

**Closed by sfackler** 2018-02-17 21:52 UTC
Labels: A-mir, C-bug, I-ICE, T-compiler
