### ISSUE TITLE
Inline Assembly cause segmentation fault when define label.

### ISSUE THREAD

**Issue by iseki-masaya** [rust-lang/rust#14375] opened 2014-05-23 11:39 UTC
OS: OS X 10.8.5
Architecture: x86_64

```
$ rustc -v
rustc 0.11.0-pre-nightly (6291955 2014-05-19 23:41:20 -0700)
host: x86_64-apple-darwin
```

```
fn main() {
    unsafe {
        asm!("label:");
    }
}
```

This code pass the compiler but cause segmentation fault.
Inline Assembly in LLVM is called at https://github.com/mozilla/rust/blob/master/src/rustllvm/RustWrapper.cpp#l173
The description of module level inline assembly about LLVM is here(http://llvm.org/docs/LangRef.html#module-level-inline-assembly)

**Comment by alexcrichton** [comment] 2015-03-02 17:40
This appears to have been fixed in more recent versions of LLVM (and the currently bundled one)

**Comment by freebroccolo** [comment] 2015-03-23 22:58
@alexcrichton This doesn't seem to be fixed on OS X, or at least it's happening again. Using labels seems to cause `SIGILL` or `SIGSEGV`. Seems to be the same thing noted [here](https://github.com/rust-lang/rust/issues/16378).

**Comment by alexcrichton** [comment] 2015-03-23 23:01
Aha I missed the OSX part of this!

**Comment by steveklabnik** [comment] 2016-11-15 20:08
Triage: a year and a half later, I'm not sure if this is fixed, as I don't have a mac. We've upgraded LLVM a number of times....

**Comment by Mark-Simulacrum** [comment] 2017-05-16 11:46
Verified as still broken today.

**Comment by Mark-Simulacrum** [comment] 2017-06-22 23:34
Appears to be fixed today... E-needstest.

**Comment by Mark-Simulacrum** [comment] 2017-07-21 18:52
This isn't actually fixed.

**Comment by Dylan-DPC** [comment] 2019-11-14 07:08
I can reproduce this bug. Still exists

**Comment by stevecheckoway** [comment] 2020-01-11 20:58
See https://github.com/rust-lang/rust/issues/63977#issuecomment-573353150

**Comment by Amanieu** [comment] 2020-05-23 01:34
You should only use [local labels](https://sourceware.org/binutils/docs/as/Symbol-Names.html#Local-Labels) in inline assembly. This is stated in the documentation for the new `asm!` macro.

**Closed by Amanieu** 2020-05-23 01:34 UTC
Labels: A-inline-assembly, C-bug, I-crash, O-macos, requires-nightly
