### ISSUE TITLE
Excessive repeated errors when unsized slice is used in a for loop

### ISSUE THREAD

**Issue by FreeFull** [rust-lang/rust#26956] opened 2015-07-10 23:33 UTC
This code:
``` rust
fn main() {
    let vec = vec![1,4,35,13,42,1];
    for x in vec[3..] {
        print!("{} ", x);
    }
}
```
produces the following errors
```
main.rs:3:5: 5:6 error: the trait `core::marker::Sized` is not implemented for the type `[_]` [E0277]
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 note: `[_]` does not have a constant size known at compile-time
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 error: the trait `core::iter::Iterator` is not implemented for the type `[_]` [E0277]
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 note: `[_]` is not an iterator; maybe try calling `.iter()` or a similar method
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 error: the trait `core::marker::Sized` is not implemented for the type `[_]` [E0277]
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 note: `[_]` does not have a constant size known at compile-time
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 error: the trait `core::marker::Sized` is not implemented for the type `[_]` [E0277]
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 note: `[_]` does not have a constant size known at compile-time
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 error: the trait `core::iter::Iterator` is not implemented for the type `[_]` [E0277]
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 note: `[_]` is not an iterator; maybe try calling `.iter()` or a similar method
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 error: the trait `core::iter::Iterator` is not implemented for the type `[_]` [E0277]
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
main.rs:3:5: 5:6 note: `[_]` is not an iterator; maybe try calling `.iter()` or a similar method
main.rs:3     for x in vec[3..] {
main.rs:4         print!("{} ", x);
main.rs:5     }
note: in expansion of for loop expansion
main.rs:3:5: 5:6 note: expansion site
error: aborting due to 6 previous errors
```
Both the Sized and Iterator errors repeat multiple times, and I suspect they would repeat indefinitely if rustc didn't have an error threshold.

**Comment by birkenfeld** [comment] 2016-05-02 06:51
Duplicate of #28416, I think.

Output is now better, in any case:
```
<anon>:5:5: 7:6 error: the trait bound `[_]: std::marker::Sized` is not satisfied [E0277]
<anon>:5     for x in vec[3..] {
<anon>:6         print!("{} ", x);
<anon>:7     }
<anon>:5:5: 7:6 help: see the detailed explanation for E0277
<anon>:5:5: 7:6 note: `[_]` does not have a constant size known at compile-time
<anon>:5:5: 7:6 note: required by `std::iter::IntoIterator::into_iter`
<anon>:5:5: 7:6 error: the trait bound `[_]: std::iter::Iterator` is not satisfied [E0277]
<anon>:5     for x in vec[3..] {
<anon>:6         print!("{} ", x);
<anon>:7     }
<anon>:5:5: 7:6 help: see the detailed explanation for E0277
<anon>:5:5: 7:6 note: `[_]` is not an iterator; maybe try calling `.iter()` or a similar method
<anon>:5:5: 7:6 note: required by `std::iter::IntoIterator::into_iter`
```

**Comment by arielb1** [comment] 2016-05-02 11:18
This looks fixed.

**Closed by arielb1** 2016-05-02 11:18 UTC
Labels: A-diagnostics
