### ISSUE TITLE
migrate to the LLVM toolchain

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#9367] opened 2013-09-20 21:13 UTC
Especially on Windows, we shouldn't have a dependency on either MinGW or MSVC++. LLVM's toolchain is not entirely mature, but they do have C/C++ working on Windows independently of other toolchains.

http://blog.llvm.org/2013/09/a-path-forward-for-llvm-toolchain-on.html
- [x] ~~libgcc -> compiler-rt (required to fix some other bugs like #8449)~~ (closed by #12027)
- [x] ~~libsupc++ (exception support) -> libc++abi (may still have a dependency on libgcc on some platforms)~~ (closed by #11121)
- [ ] gcc/ld -> lld
- [x] ~~ship clang with snapshot to build the C runtime bits, and drop the C++ bits (to avoid needing to build libc++ as a replacement for libstdc++ too)~~ (closed by 508b7b996e5d557ec1c49e1d11563ecf4fc9d287)

**Comment by alexchandel** [comment] 2015-01-16 06:00
As shown in IRC earler, LLD is now capable of dynamically linking Rust programs.

**Comment by tamird** [comment] 2015-04-20 17:58
@alexchandel can you provide a minimal recipe for this usage of lld?

**Comment by alexchandel** [comment] 2015-04-30 03:06
@tamird I wish I could, but LLVM's master's build is currently broken on OS X (at least through Homebrew), so I can't even build LLD, much less run it. But once upon a time, this did it:
```sh
RUSTLIB=/usr/local/lib/rustlib/x86_64-apple-darwin/lib
rustc --emit obj -Z no-landing-pads -C no-stack-check test.rs
$LLVM/lld -flavor darwin -arch x86_64 test.o $RUSTLIB/libmorestack.a -L $RUSTLIB -lstd-4e7c5e5c -lSystem -lcompiler-rt -o test
```

**Comment by tamird** [comment] 2015-04-30 19:40
Hey, it totally works with LLVM 3.6! https://github.com/tamird/rust_lld

**Comment by tamird** [comment] 2015-05-01 19:53
Updated to include static linking, which doesn't totally work.

**Comment by alexchandel** [comment] 2015-05-03 22:17
@tamird Lol static linking is the important one. I never got clang to obey `-B`; I always had to resort to manual `lld` invocations. Btw you realize that passing `-lSystem` makes `-lpthread -lc -lm` redundant, since OS X combines them all into libSystem?

**Comment by tamird** [comment] 2015-05-03 23:53
> @tamird Lol static linking is the important one.

Yep, just posting progress. As you know, LLVM HEAD is still [broken in homebrew](https://github.com/Homebrew/homebrew/issues/37167) so I haven't tested that yet.
> I never got clang to obey -B; I always had to resort to manual lld invocations.

Worked for me ¯\_(ツ)_/¯
> Btw you realize that passing -lSystem makes -lpthread -lc -lm redundant, since OS X combines them all into libSystem?

Yep, this call is taken verbatim from rustc's attempt to call `cc`. (see notes in https://github.com/tamird/rust_lld/blob/master/README.md)

**Comment by BigBoneDaddy** [comment] 2015-06-27 19:47
@tamird Can you give more detail about how static linking doesnot work?

**Comment by tamird** [comment] 2015-06-27 19:49
It's all in https://github.com/tamird/rust_lld

**Comment by BigBoneDaddy** [comment] 2015-06-27 19:52
@tamird 100 thanx that clears it up for me! :+1: :100:

**Comment by tamird** [comment] 2015-06-28 06:06
So this reminded me to check thing again, and they totally worked. Looks like LLD is able to link at least a trivial hello world rust program! I've updated https://github.com/tamird/rust_lld for those interested.

**Comment by pix64** [comment] 2015-07-06 11:47
"With this achievement, I think I can say that the new COFF linker is
now mostly feature complete for x86-64 Windows. I believe there are
still many lingering bugs, though."

http://reviews.llvm.org/rL241318

**Comment by tamird** [comment] 2015-07-18 22:55
I briefly explored getting rustc built with LLD today, but found the current linker situation complicated enough to discourage me from further work. In summary:
- In all cases except msvc:
  - rustc uses `cc` or `gcc` with `-Wl` to link stuff. This uses `ld` under the hood.
- In the MSVC case:
  - rustc uses `link.exe` to link stuff, and this logic lives in a parallel universe from everything else.

Note that LLD intentionally implements several command-line interfaces, designed to emulate `clang`, `gcc`, and `link.exe`. This means that moving to LLD can greatly simplify MSVC support and bring it inline with the other platforms.

There's a final snag:
- LLVM is migrating to `cmake`. The "old" build system is deprecated, but still present.
- rustc builds LLVM using the "old" build system (except in the msvc case).
- LLD fails to build using LLVM's "old" build system.

This means that in order to use LLD, rustc must depend on `cmake`.

If anyone is interested in picking up this torch (maybe @alexcrichton or @alexchandel?), see https://github.com/tamird/rust/tree/use-lld.

**Comment by alexcrichton** [comment] 2015-07-20 05:02
@tamird do you just need help getting lld integrated into our build system? Or do you need help getting it integrated into the compiler itself? You may be able to get by just installing lld into your `PATH` and having the compiler shell out to it. The compiler could possibly just have logic to pass different arguments in that situation.

**Comment by tamird** [comment] 2015-07-20 17:37
@alexcrichton yep, that's what I've done for now:
```
PATH=x86_64-apple-darwin/llvm/bin:$PATH time /usr/bin/make -j4 check-stage1
```

A bunch of tests are passing (but some are failing), so:
- how do I get the build system to put `lld` somewhere rustc can find it? I thought https://github.com/tamird/rust/commit/44f6fb320c66f67397a5661dba49bf23b38ae796 would do it, but apparently not
- should I open a PR? I'd be cool to have a try build with lld.

**Comment by tamird** [comment] 2015-07-20 19:41
@alexcrichton here's the full output: https://gist.github.com/tamird/88215c54395e29bd7d8e

**Comment by eddyb** [comment] 2015-08-29 23:40
@tamird Was that before or after @alexcrichton's change to unwinding? The one that made `-Z no-landing-pads` not emit the panic handler, thus *always* causing that error when panicking at stage1.
Have you tried `check-stage2`?

**Comment by tamird** [comment] 2015-08-29 23:46
@eddyb that exact error happens with the latest nightly. See repro instructions https://github.com/tamird/rust_lld

**Comment by lygstate** [comment] 2015-10-31 05:20
Microsoft has already opensource it's PDB/CodeView format and preparing implemented it in LLVM, that's would be a great news for lld.

**Comment by japaric** [comment] 2016-02-15 03:34
My experience using `lld` to link Rust programs on Linux: (**Spoilers** it didn't work at all)

I started with a hello world program:

```
$ cat hello.rs
fn main() {
    println!("Hello, world!");
}
```

Then produced an object file and got the linker arguments used by `rustc`:

```
$ rustc -C linker=/usr/bin/false hello.rs
"/usr/bin/false"
"-Wl,--as-needed"
"-Wl,-z,noexecstack"
"-m64"
"-L"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib"
"hello.0.o"
"-o"
"hello"
"-Wl,--gc-sections"
"-pie"
"-nodefaultlibs"
"-L"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib"
"-Wl,-Bstatic"
"-Wl,-Bdynamic"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-fd663c41.rlib"
"/home/japaric/.multirust/toolchains/nightly/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-fd663c41.rlib"
"-l"
"dl"
"-l"
"pthread"
"-l"
"gcc_s"
"-l"
"pthread"
"-l"
"c"
"-l"
"m"
"-l"
"rt"
"-l"
"compiler-rt"
```

These arguments don't work with `lld`, so I made the following changes:

- First argument: `-flavor gnu`
- Add /usr/lib to search path: `-L /usr/lib`, or `lld` won't be able to find C libraries like `libc` and `libm`
- Change arguments that look like `-Wl,$arg` to just `$arg`
- Add `crt1.o` and `crti.o` as input object files or I get these errors `undefined symbol: _start` and `undefined symbol: _init`
- These flags are not accepted so I omitted them:
    - `-m64`: unknown emulation
    - `-pie`: unknown argument
    - `-nodefaultlibs`: unknown argument (but not required I think because lld doesn't link to any library by default)

I ended with a `lld` call that looks like this:

``` bash
target=x86_64-unknown-linux-gnu
sysroot=$(rustc --print sysroot)
libdir=${sysroot}/lib/rustlib/${target}/lib

lld \
  -flavor gnu \
  -L /usr/lib \
  --as-needed \
  -z,noexecstack \
  -L ${libdir} \
  hello.0.o \
  /usr/lib/crt1.o \
  /usr/lib/crti.o \
  -o hello \
  --gc-sections \
  -Bstatic \
  -Bdynamic \
  ${libdir}/libstd-fd663c41.rlib \
  ${libdir}/libcollections-fd663c41.rlib \
  ${libdir}/librustc_unicode-fd663c41.rlib \
  ${libdir}/librand-fd663c41.rlib \
  ${libdir}/liballoc-fd663c41.rlib \
  ${libdir}/liballoc_jemalloc-fd663c41.rlib \
  ${libdir}/liblibc-fd663c41.rlib \
  ${libdir}/libcore-fd663c41.rlib \
  -l dl \
  -l pthread \
  -l gcc_s \
  -l c \
  -l m \
  -l rt \
  -l compiler-rt
```

Then I got the following segfault with the above `lld` call:

```
#0 0x0000000000515f35 (/usr/x86_64-pc-linux-gnu/bin/lld+0x515f35)
#1 0x0000000000514006 (/usr/x86_64-pc-linux-gnu/bin/lld+0x514006)
#2 0x000000000051417f (/usr/x86_64-pc-linux-gnu/bin/lld+0x51417f)
#3 0x00007f7f68a41c70 __restore_rt (/usr/x86_64-pc-linux-gnu/bin/../lib/libpthread.so.0+0x10c70)
#4 0x00000000017ba7b3 (/usr/x86_64-pc-linux-gnu/bin/lld+0x17ba7b3)
#5 0x000000000177668e (/usr/x86_64-pc-linux-gnu/bin/lld+0x177668e)
#6 0x0000000001787d00 (/usr/x86_64-pc-linux-gnu/bin/lld+0x1787d00)
#7 0x00000000017dc22d (/usr/x86_64-pc-linux-gnu/bin/lld+0x17dc22d)
#8 0x00000000017651d8 (/usr/x86_64-pc-linux-gnu/bin/lld+0x17651d8)
#9 0x00000000004a137e _init (/usr/x86_64-pc-linux-gnu/bin/lld+0x4a137e)
#10 0x00000000017688b5 (/usr/x86_64-pc-linux-gnu/bin/lld+0x17688b5)
#11 0x00000000004a90f1 _init (/usr/x86_64-pc-linux-gnu/bin/lld+0x4a90f1)
#12 0x000000000045b5ce _init (/usr/x86_64-pc-linux-gnu/bin/lld+0x45b5ce)
#13 0x00007f7f67e21620 __libc_start_main (/usr/x86_64-pc-linux-gnu/bin/../lib/libc.so.6+0x20620)
#14 0x00000000004a8439 _init (/usr/x86_64-pc-linux-gnu/bin/lld+0x4a8439)
Stack dump:
0.      Program arguments: (...)
```

Interestingly removing the `--gc-sections` flags "fixes" the segfault and produces a 2MB binary. However, running the binary generates a new segfault.

---

Other interesting bit is that `rustc -g` produces an object file that `lld` can't use:

```
$ rustc -g -C linker=/usr/bin/false hello.rs
$ lld -flavor gnu hello.0.o -o hello
SHF_MERGE section size must be a multiple of sh_entsize
$ echo $?
1
```

---

### Version

```
LLVM Linker Version: 3.9(/var/cache/paludis/distfiles/scm/lld e5f40891704022e82687c317c814377a485d73ba)
```

Can anyone reproduce these errors? Or perhaps someone can point out a fatal error I may have committed in the above steps?

**Comment by nagisa** [comment] 2016-02-15 12:11
ELF `lld` is being rewritten and the old version is not maintained much anymore to my knowledge. I wouldn’t be surprised about it (either version) not quite working yet.

**Comment by japaric** [comment] 2016-02-15 12:35
Aha, that would explain the errors. I'll try again at a later date :smile:.

**Comment by tamird** [comment] 2016-02-15 16:43
FWIW, I've updated https://github.com/tamird/rust_lld, and things seem to work as before against LLVM HEAD (`$(brew --prefix llvm)/bin/llvm-config --version` prints `3.9.0svn`).

That is, "hello world" works, but panic doesn't (illegal instruction). I'm not sure what you were doing wrong @japaric but I'd be happy to collaborate if you want to use my work as a starting point.

**Comment by alexchandel** [comment] 2016-02-15 16:47
@nagisa It *will* be fixed eventually right? It'd be a pity to only be able to link mach-o and windows binaries.

FWIW, by having a shell script called `link.exe` that adds the `./lib` folder of `~/i686-pc-windows-msvc` (itself a union of ~/i686-pc-windows-msvc-vc6 and ~/i686-pc-windows-msvc-w10) to the `LIB` env variable and then calls `lld-link`, (and doing a similar thing for `cl.exe` for projects with a `build.rs`,) I can cross-compile basically any Rust project to windows.

**Comment by nagisa** [comment] 2016-02-15 16:50
@alexchandel they’re rewriting it ELF backend from scratch.

**Comment by japaric** [comment] 2016-02-15 21:25
@tamird I think `lld` works in your case because you are using the `mach-o` backend (macos) instead of the `elf` backend (linux). I tried your scripts, I had to modify them to run on Linux, but `lld` is not being used at all. I think it's because `rustc` uses `cc` as a linker, `cc` calls `collect2` (instead of `ld`) with all the linker arguments and `collect2` then calls a prefixed `ld` (i.e. `/usr/bin/x86_64-pc-linux-gnu-ld`) on my system. Maybe `collect2` is ignoring the `-B .` flag used in your script?

Anyhow, I intended to add a `-Z use-lld` flag to `rustc` that forced the compiler to use `lld` as a linker as a way to start testing integration with `lld` but without a way to test locally I won't be able to. If anyone want to give that idea a try I can provide some pointers.

**Comment by tamird** [comment] 2016-02-15 21:41
> I think it's because `rustc` uses `cc` as a linker, `cc` calls `collect2` (instead of `ld`)...Maybe `collect2` is ignoring the `-B .` flag used in your script?

You must be using GCC; `-B` is an undocumented flag respected by clang.

Also, note that some of the scripts invoke `rustc` and `lld` in two steps, so even on your system, those should be using `lld`. See https://github.com/tamird/rust_lld/blob/master/manual_dynamic.sh#L11 and https://github.com/tamird/rust_lld/blob/master/manual_static.sh#L11.

**Comment by retep998** [comment] 2016-03-10 17:21
Just saying, if we had https://github.com/rust-lang/rust/issues/30027 then we wouldn't depend on import libraries from mingw/msvc on Windows.

**Comment by alexchandel** [comment] 2016-03-11 21:14
@retep998 This would mean that, using LLD, you could target windows without a toolchain right? Or would you still need a single `msvcrt.lib` for the entry point?

**Comment by retep998** [comment] 2016-03-11 21:18
If you don't care about statically linking with C/C++ code then you can easily write your own entry point and skip CRT initialization entirely.

**Comment by alexchandel** [comment] 2016-04-01 15:54
@retep998 So we could link against `msvcrt.dll` for `memcpy`/`memmove`/`memcmp`/`memset`/`strlen` using generated idata, because it maintains those symbols and does its own initialization, but skip CRT initialization in a pure rust executable? I wonder how microsoft got it so wrong, while apple got it right; their entry point (and crt initialization i.e. `crt1.o`) is literally inside `libSystem.dylib`.

@nagisa They've finished [rewriting](http://blog.llvm.org/2015/11/new-elf-linker-from-llvm-project.html) and are working on feature parity now.

**Comment by nagisa** [comment] 2016-04-01 16:10
> working on feature parity now.

I’m not sure I would call that state *finished* yet, but sure.

**Comment by retep998** [comment] 2016-04-01 23:20
@alexchandel How is that Microsoft getting it wrong? Is there a reason that statically linking the entry point might be a bad idea? On Windows every binary (exe or dll) has an entry point which is responsible for initializing all the statics and such in that binary. If you're using C/C++ in a given binary, then you need the CRT entry point. Since Rust doesn't have runtime static initializers, or any life outside of main for that matter, a pure Rust binary would have no need for the CRT entry point and could have its own minimal entry point. C/C++ code that is in DLLs, since they have their own entry points, they'll continue to work fine. If you link the CRT _statically_ then you definitely need the CRT entry point since that brings in C/C++ with a bunch of statics and stuff directly into your binary and thus it needs to be initialized correctly.

Whether we link to msvcrt via generated idata or an import library is rather irrelevant to whether we skip the CRT entry point. As long as the CRT is dynamically linked and we don't have any statically linked C/C++ then we can skip the CRT entry point. Note that generating idata instead of linking to an import library is a move that needs to be considered very carefully, especially with regards to things like the CRT. Imagine if we generated idata to some of the math functions and someone statically linked in some C/C++ code that calls those math functions and checks the result via `errno`. If it pulls in the math functions from the generated idata, but the `errno` from an import library, then they could very well end up being _different_ CRTs and things would fail horribly. Also consider the case of someone trying to use Rust to make a UWP app instead of a regular desktop app. They need to link to `onecore.lib` _instead_ of things like `kernel32.lib` so references can resolve to different DLLs. If libstd decides to generate idata for some of the system functions it uses it could end up generating them for the _wrong_ DLL and things would fail horribly.

**Comment by alexchandel** [comment] 2016-04-04 10:17
@retep998 There's more than just the entry point and static initializers in there, and the versioned `vcruntime140.dll` that the UCRT requires dynamically linked binaries to link has all kinds of stuff, including of exception handling, dispatch, and unwinding. Yet everything that Microsoft here claims must change between compiler versions, OSX has kept permanently stable since the introduction of libSystem by keeping it behind the libSystem facade. That's getting it wrong vs right. Rust executables on OS X, even those statically linked with C/C++ code, don't need anything other than a dynamic link to libSystem.dylib.

It sounds like Rust would have to reason whether any import libraries were included when deciding to generate idata. But in the case where C/C++ code is statically linked, a use case I often deal with on Windows, is it then necessary to use import libraries from a Windows toolchain?

**Comment by japaric** [comment] 2016-09-01 00:40
Update: #36120 is a PoC PR that embeds lld into rustc itself. It has only been tested with x86_64 ELFs though.

**Comment by alexcrichton** [comment] 2017-02-11 00:12
This is a pretty old bug at this point and the only remaining task, lld, is best tracked in a future issue (if necessary)

**Closed by alexcrichton** 2017-02-11 00:12 UTC
Labels: A-build, A-LLVM, I-enhancement, P-low

**Comment by alexchandel** [comment] 2017-02-11 00:43
Is it still the intention to eventually switch to using lld?

**Comment by alexcrichton** [comment] 2017-02-11 01:38
If it makes sense to, sure!
