### ISSUE TITLE
Mutex giving dropped while still borrowed errors.

### ISSUE THREAD

**Issue by Mr-Byte** [rust-lang/rust#44801] opened 2017-09-24 04:01 UTC
With the following program:

```rust
use std::sync::Mutex;

pub fn main() {
    let foo = Mutex::new(0u32);
    
    if let Ok(foo) = foo.lock() {
        println!("{}", foo);
    }
}
```

I get the following compiler error:
```
error[E0597]: `foo` does not live long enough
 --> src/main.rs:9:1
  |
6 |     if let Ok(foo) = foo.lock() {
  |                      --- borrow occurs here
...
9 | }
  | ^ `foo` dropped here while still borrowed
  |
  = note: values in a scope are dropped in the opposite order they are created
```

However when I modify the program as follows:

```rust
use std::sync::Mutex;

pub fn main() {
    let foo = Mutex::new(0u32);
    
    if let Ok(foo) = foo.lock() {
        println!("{}", foo);
    }
    
    {}
}
```

The program compiles and runs as expected.

It seems odd to me that inserting `{}` after the `lock` fixes the issue.  It appears that any code following the `lock` allows for the program to compile and run as expected, with an empty `{}` or `()` being the simplest way of doing this.

**Comment by bluss** [comment] 2017-09-24 12:02
Thanks, this is far from ideal and an issue that is already tracked. Semicolon is another symbol that can help you until it's fixed.

Duplicate of #22323

**Closed** 2017-09-24 14:39 UTC
Labels: A-borrow-checker, C-enhancement, T-compiler

**Comment by pnkfelix** [comment] 2018-09-19 12:36
(This is actually a duplicate of  #46413 )
