### ISSUE TITLE
[rustbuild] ignore single tests

### ISSUE THREAD

**Issue by davidak** [rust-lang/rust#49874] opened 2018-04-11 11:54 UTC
I'm packaging a rust program for the [Nix package manager](https://nixos.org/nix/). We build packages in a sandboxed environment to not rely on external state and have reproducible builds.

Now a test fail because it want's to use the network. I want to disable this one test with a commandline parameter.

Tests could also be grouped (https://github.com/rust-lang/rust/issues/35678), so i can disable all tests that need network like `--test offline`, but a simple list like `--test --disable-tests test_update_cache,test_missing_cache` would do it for now.

**Comment by jyn514** [comment] 2022-06-27 03:55
We'd want to implement this with `--exclude`, so I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/96342. I don't think we use any tests today that require network access, please open a new issue if that's not the case :)

**Closed by jyn514** 2022-06-27 03:55 UTC
Labels: A-testsuite, C-enhancement, A-rustbuild, T-infra
