### ISSUE TITLE
Associated consts cannot elide `'static

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#41792] opened 2017-05-06 21:09 UTC
```rust
#![feature(associated_consts)]

trait Foo {
    const X: &str;
}

impl Foo for () {
    const X: &str = "";
}

fn main() {}
```
https://play.rust-lang.org/?gist=84bbc056b2289ed71e169e8a4b9236df&version=nightly&backtrace=0

```
rustc 1.19.0-nightly (f4209651e 2017-05-05)
error[E0106]: missing lifetime specifier
 --> <anon>:4:14
  |
4 |     const X: &str;
  |              ^ expected lifetime parameter

error[E0106]: missing lifetime specifier
 --> <anon>:8:14
  |
8 |     const X: &str = "";
  |              ^ expected lifetime parameter
```

@eddyb

**Comment by eddyb** [comment] 2017-05-06 21:12
@withoutboats This was an intentional decision (in the RFC, I believe) that could be relaxed in `impl` blocks with no lifetime parameters.

**Comment by withoutboats** [comment] 2017-05-06 21:17
Can associated consts depend on the lifetime variables in scope? Was the decision just to avoid ambiguity?

**Comment by eddyb** [comment] 2017-05-06 21:22
I'm not sure, to be honest. https://github.com/rust-lang/rfcs/pull/1623#issuecomment-239559757 is the RFC's conclusion.
cc @rust-lang/lang

**Comment by petrochenkov** [comment] 2017-05-07 11:37
Duplicate of https://github.com/rust-lang/rust/issues/38831

**Closed** 2017-05-07 12:11 UTC
