### ISSUE TITLE
rustdoc: Private structs implementing public traits are visible as dangling links

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#19106] opened 2014-11-19 13:57 UTC
Seeing is believing: http://doc.rust-lang.org/std/ops/trait.Drop.html

`core::finally::Finallyalizer` and `collections::vec::PartialVecNonZeroSized` are two of many dangling links in the `Drop` page.  They shouldn't be visible at all because `core::finally` and `PartialVecNonZeroSized` are private items.

**Comment by alexcrichton** [comment] 2015-04-07 03:01
Closing as a duplicate of #14586

**Closed by alexcrichton** 2015-04-07 03:01 UTC
Labels: A-rustdoc
