### ISSUE TITLE
rustc 1.19.0-nightly panics while compiling crate image 0.13.0

### ISSUE THREAD

**Issue by codewiz** [rust-lang/rust#41642] opened 2017-04-30 02:08 UTC
Version: `rustc 1.19.0-nightly (afa1240e5 2017-04-29)`

Works with rustc 1.17 and also worked with nightly on 2017-04-22.

Full stack trace:
```
   Compiling image v0.13.0 (file:///home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0)
     Running `rustc --crate-name image src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="bmp"' --cfg 'feature="jpeg-decoder"' --cfg 'feature="png_codec"' --cfg 'feature="default"' --cfg 'feature="png"' --cfg 'feature="scoped_threadpool"' --cfg 'feature="tga"' --cfg 'feature="gif"' --cfg 'feature="jpeg"' --cfg 'feature="ico"' --cfg 'feature="gif_codec"' --cfg 'feature="hdr"' --cfg 'feature="webp"' --cfg 'feature="tiff"' --cfg 'feature="ppm"' -C metadata=46cff3f07bfcfb47 -C extra-filename=-46cff3f07bfcfb47 --out-dir /home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps -L dependency=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps --extern num_traits=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libnum_traits-a8c1b7cdefa880e5.rlib --extern num_iter=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libnum_iter-b399bbd189e5f67b.rlib --extern enum_primitive=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libenum_primitive-426259b3f2e82106.rlib --extern png=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libpng-891680363f77ff6c.rlib --extern scoped_threadpool=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libscoped_threadpool-58ec7837165a2885.rlib --extern gif=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libgif-9741810a2aef6c61.rlib --extern byteorder=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libbyteorder-190c8b8b4cb7f472.rlib --extern jpeg_decoder=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libjpeg_decoder-48b766e3b99e05bb.rlib --extern num_rational=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libnum_rational-10478f086e0c85c0.rlib`
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: !unsize', /checkout/src/librustc_typeck/check/mod.rs:2212
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
   6: rustc_typeck::check::FnCtxt::try_index_step
   7: rustc_typeck::check::method::confirm::ConfirmContext::confirm
   8: rustc_typeck::check::method::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::lookup_method
   9: rustc_typeck::check::FnCtxt::check_expr_kind
  10: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  11: rustc_typeck::check::FnCtxt::check_stmt
  12: rustc_typeck::check::FnCtxt::check_block_with_expected::{{closure}}
  13: rustc_typeck::check::FnCtxt::check_block_with_expected
  14: rustc_typeck::check::FnCtxt::check_expr_kind
  15: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  16: rustc_typeck::check::FnCtxt::check_return_expr
  17: rustc_typeck::check::check_fn
  18: rustc_typeck::check::typeck_tables_of
  19: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables_of<'tcx>>::try_get
  20: rustc::ty::maps::TyCtxtAt::typeck_tables_of
  21: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  22: rustc_typeck::check::typeck_item_bodies
  23: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get
  24: rustc::ty::maps::TyCtxtAt::typeck_item_bodies
  25: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_item_bodies
  26: rustc_typeck::check_crate
  27: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  28: rustc_driver::driver::phase_3_run_analysis_passes
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler
  31: std::panicking::try::do_call
  32: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  33: <F as alloc::boxed::FnBox<A>>::call_box
  34: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:658
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  35: start_thread
  36: clone

error: Could not compile `image`.

Caused by:
  process didn't exit successfully: `rustc --crate-name image src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="bmp" --cfg feature="jpeg-decoder" --cfg feature="png_codec" --cfg feature="default" --cfg feature="png" --cfg feature="scoped_threadpool" --cfg feature="tga" --cfg feature="gif" --cfg feature="jpeg" --cfg feature="ico" --cfg feature="gif_codec" --cfg feature="hdr" --cfg feature="webp" --cfg feature="tiff" --cfg feature="ppm" -C metadata=46cff3f07bfcfb47 -C extra-filename=-46cff3f07bfcfb47 --out-dir /home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps -L dependency=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps --extern num_traits=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libnum_traits-a8c1b7cdefa880e5.rlib --extern num_iter=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libnum_iter-b399bbd189e5f67b.rlib --extern enum_primitive=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libenum_primitive-426259b3f2e82106.rlib --extern png=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libpng-891680363f77ff6c.rlib --extern scoped_threadpool=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libscoped_threadpool-58ec7837165a2885.rlib --extern gif=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libgif-9741810a2aef6c61.rlib --extern byteorder=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libbyteorder-190c8b8b4cb7f472.rlib --extern jpeg_decoder=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libjpeg_decoder-48b766e3b99e05bb.rlib --extern num_rational=/home/bernie/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.13.0/target/debug/deps/libnum_rational-10478f086e0c85c0.rlib` (exit code: 101)
```

If needed I can try to reduce this to a minimal testcase.

**Comment by sfackler** [comment] 2017-04-30 02:20
Duplicate of #41604

**Closed by sfackler** 2017-04-30 02:20 UTC
