### ISSUE TITLE
Transmute does not see the size of generic-over-constants types

### ISSUE THREAD

**Issue by jonasmalacofilho** [rust-lang/rust#82334] opened 2021-02-20 16:55 UTC
I tried this code:

```rust
pub fn noop<const N: usize>(src: [i32; N]) -> [i32; N] {
    unsafe { std::mem::transmute::<_, _>(src) }
}
```

I expected a successful compilation.

Instead, this happened:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/lib.rs:2:14
  |
2 |     unsafe { std::mem::transmute::<_, _>(src) }
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `[i32; N]` does not have a fixed size
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (a143517d4 2021-02-16)
binary: rustc
commit-hash: a143517d44cac50b20cbd3a0b579addab40dd399
commit-date: 2021-02-16
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

Note: this also reproduces with the current beta (`1.51.0-beta.2`) on the Rust Playground [[link]](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=6002f984b0cdfb5470943805fa6aae12).

<details><summary>Backtrace</summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build
   Compiling transmute_no_fixed_size_with_min_const_generics v0.1.0 (/home/jonas/Code/issues/rust/transmute_no_fixed_size_with_min_const_generics)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/lib.rs:2:14
  |
2 |     unsafe { std::mem::transmute::<_, _>(src) }
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `[i32; N]` does not have a fixed size

error: aborting due to previous error

For more information about this error, try `rustc --explain E0512`.
error: could not compile `transmute_no_fixed_size_with_min_const_generics`

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by the8472** [comment] 2021-02-20 23:27
Have you tried `transmute_copy`?

**Comment by Mark-Simulacrum** [comment] 2021-02-20 23:34
I think this is expected - transmute doesn't work with generics of any kind AFAIK. That said, the error could be better.

I think this is a duplicate of https://github.com/rust-lang/rust/issues/61956, though. Thanks!

**Closed by Mark-Simulacrum** 2021-02-20 23:34 UTC
Labels: C-bug

**Comment by jonasmalacofilho** [comment] 2021-02-21 03:54
> I think this is expected - transmute doesn't work with generics of any kind AFAIK. That said, the error could be better.

Oh, I hadn't come across this yet.

> I think this is a duplicate of [...]

I also missed the other issue; apparently I made a typo somewhere when searching for existing issues.

Sorry about for noise, and thanks!

---

> Have you tried `transmute_copy`?

I did and it compiles, since it doesn't check the sizes.  And the optimizer appears to elide the copy away, as desired.

Still, thanks! : )
