### ISSUE TITLE
error: can't find crate for `std` when cross-compiling to i686-unknown-linux-gnu from x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by briansmith** [rust-lang/rust#29388] opened 2015-10-26 23:28 UTC
STR:
```
git clone https://github.com/briansmith/crypto-bench
cargo test --target=i586-unknown-linux-gnu --verbose
```

Actual Result:
````
/home/m/.cargo/registry/src/github.com-0a35038f75765ae4/lazy_static-0.1.15/src/lib.rs:1:1: 1:1 error: can't find crate for `std`
```

Expected result: Successful 32-bit build using the 64-bit compiler.

Note, in particular, that this affects the Rust Travis CI integration, because, AFAICT, it always installs 64-bit compilers.

**Comment by alexcrichton** [comment] 2015-10-27 00:09
This is actually currently intended behavior because you need to install the target Rust libraries (e.g. the standard library) before you're able to cross compile for new targets. For example any old rust compiler can't automatically succeed when targeting all the platforms Rust supports.

We're working on bolstering up the installation scripts (e.g. rustup) to allow much easier installation of these libraries, but in the meantime [you can manually install the target libraries](https://github.com/alexcrichton/gcc-rs/blob/e76ff5f3dcf36b798fa4997da40ae392ab543f76/.travis.yml#L8-L14).

As this is intended behavior, however, I'm going to close this.

**Closed by alexcrichton** 2015-10-27 00:09 UTC
