### ISSUE TITLE
error_index_generator can fail with no error messages

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#57151] opened 2018-12-27 18:02 UTC
See https://travis-ci.org/rust-lang/rust/jobs/472667448 for instance, in which the logs read:
```
[01:00:04] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/error_index_generator" "html" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc/error-index.html"
[01:00:04] expected success, got: exit code: 101
```
This is completely unhelpful as it gives the user no idea what the problem is.

**Comment by Mark-Simulacrum** [comment] 2019-06-03 18:31
Since we don't know what caused this and it's likely impossible/hard to reproduce I'm going to close this; if someone narrows down a reproduction then we can reopen to track a fix (though I suspect a PR would be relatively simple at that point, hopefully).

**Closed by Mark-Simulacrum** 2019-06-03 18:31 UTC
Labels: A-rustbuild, T-infra

**Comment by gilescope** [comment] 2019-07-28 18:43
In my case it was caused by #63016.
