### ISSUE TITLE
encountered incremental compilation error with item_children(qmeta_async[ed7c]) - ICE with a proc macro

### ISSUE THREAD

**Issue by rubdos** [rust-lang/rust#89223] opened 2021-09-24 15:12 UTC
### Code

I'm not sure what triggers this. It shows up, suddenly, in CI. I don't have it on my local machine. Since this is an unstable fingerprints related issue (#84970), I'm not clearing the CI cache until you folks have an idea how to proceed!

https://gitlab.com/whisperfish/whisperfish/-/jobs/1604136167

https://gitlab.com/whisperfish/whisperfish branch `sfdk`.

### Meta

[`rustc --version --verbose`](https://gitlab.com/whisperfish/whisperfish/-/jobs/1604136167#L867):
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
```

(coming from CI, so I'm not sure)

### Error output

```
error: internal compiler error: encountered incremental compilation error with item_children(qmeta_async[ed7c])
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p harbour_whisperfish` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information
thread 'rustc' panicked at 'Found unstable fingerprints for item_children(qmeta_async[ed7c]): [Export { ident: with_executor#0, res: Def(Macro(Attr), DefId(240:7 ~ qmeta_async[ed7c]::with_executor)), span: /builds/bWox63RA/1/whisperfish/whisperfish/qmeta-async/src/lib.rs:5:1: 8:29 (#0), vis: Public }]', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/compiler/rustc_query_system/src/query/plumbing.rs:624:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: encountered incremental compilation error with item_children(qmeta_async[ed7c])
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p harbour_whisperfish` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information
thread 'rustc' panicked at 'Found unstable fingerprints for item_children(qmeta_async[ed7c]): [Export { ident: with_executor#0, res: Def(Macro(Attr), DefId(240:7 ~ qmeta_async[ed7c]::with_executor)), span: /builds/bWox63RA/1/whisperfish/whisperfish/qmeta-async/src/lib.rs:5:1: 8:29 (#0), vis: Public }]', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/compiler/rustc_query_system/src/query/plumbing.rs:624:9
stack backtrace:
   0:     0x7fbf29e20b40 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fbf29e20b40 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fbf29e20b40 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fbf29e20b40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fbf29e8e6bc - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x7fbf29e122d5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x7fbf29e2489b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fbf29e2489b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fbf29e2489b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x7fbf29e24371 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x7fbf2a5fd251 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h6de3be617154114e
  11:     0x7fbf29e250c9 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
  12:     0x7fbf29e24b87 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  13:     0x7fbf29e2103c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x7fbf29e24ae9 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  15:     0x7fbf29dedaab - std::panicking::begin_panic_fmt::h7ab3d84aa4ae32a2
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
  16:     0x7fbf2ae37dac - rustc_query_system::query::plumbing::incremental_verify_ich::h89c7bc97eed12275
  17:     0x7fbf2ae5ee19 - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h17ce6c2f5a3ebe5a
  18:     0x7fbf2bca49eb - rustc_query_system::query::plumbing::get_query_impl::h9f22804c295d100b
  19:     0x7fbf2bcff2be - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::item_children::h22923e62dabe3f64
  20:     0x7fbf2bdbec70 - core::ops::function::FnOnce::call_once::hda03ecaa240882bc
  21:     0x7fbf2afabcda - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::hbc5e7ba174c42b1c
  22:     0x7fbf2af6de13 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h268088e0ee990d57
  23:     0x7fbf2b047854 - rustc_data_structures::stack::ensure_sufficient_stack::h25bf260acc6ee3be
  24:     0x7fbf2ae0f8d9 - rustc_query_system::query::plumbing::force_query_with_job::hebb48c5057cac5e0
  25:     0x7fbf2adf8563 - rustc_query_system::query::plumbing::force_query_impl::h954169508dead486
  26:     0x7fbf2adcc988 - rustc_query_system::query::plumbing::force_query::h628e92b49e5e4915
  27:     0x7fbf2bd01f5d - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::hebe559aa58bf1816
  28:     0x7fbf2bd01f35 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::hebe559aa58bf1816
  29:     0x7fbf2bd01f35 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green::hebe559aa58bf1816
  30:     0x7fbf2bd01d54 - rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green_and_read::h75827515110c1695
  31:     0x7fbf2c71b520 - rustc_data_structures::stack::ensure_sufficient_stack::hbfab430e35e7d877
  32:     0x7fbf2bcb6819 - rustc_query_system::query::plumbing::get_query_impl::hf096518971a8eed5
  33:     0x7fbf2bcfd730 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::eval_to_const_value_raw::h12296ddde415dda4
  34:     0x7fbf2c00dd9c - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_global_id::h5b3999d98f0f2b7b
  35:     0x7fbf2c00d31b - rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly::h87f48deab6768bf8
  36:     0x7fbf2c3b1605 - rustc_middle::ty::adt::AdtDef::eval_explicit_discr::h461b6ce9d4770ed3
  37:     0x7fbf2b8e6e68 - rustc_typeck::collect::convert_item::hd204d075b5daf8e3
  38:     0x7fbf2b8e0daa - <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_item::hfe85e96bd750177f
  39:     0x7fbf2b81e97b - rustc_middle::hir::map::Map::visit_item_likes_in_module::h1c760c73fdf2de62
  40:     0x7fbf2c3be3d2 - rustc_typeck::collect::collect_mod_item_types::h012865bda30bb635
  41:     0x7fbf2c687818 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h1b7ae25b17e19afa
  42:     0x7fbf2c71746a - rustc_data_structures::stack::ensure_sufficient_stack::h776ac0de7fa29c7b
  43:     0x7fbf2c5e72fc - rustc_query_system::query::plumbing::force_query_with_job::h95d4e7ee2ab3f130
  44:     0x7fbf2bcb07b2 - rustc_query_system::query::plumbing::get_query_impl::hdccbbfe1a19c3d83
  45:     0x7fbf2c67270b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_mod_item_types::hab5225346642323d
  46:     0x7fbf2c347f1b - rustc_session::session::Session::track_errors::h782177e235f44bae
  47:     0x7fbf2c33c35d - rustc_typeck::check_crate::h4575c24b66669750
  48:     0x7fbf2c1243ef - rustc_interface::passes::analysis::hf91740f5893e2dd6
  49:     0x7fbf2afaf363 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::he5722ca07eceeed2
  50:     0x7fbf2af78a47 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h96f2846afe4c135b
  51:     0x7fbf2af82a19 - rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task::h61fc0f5b6132f6c1
  52:     0x7fbf2b0460ce - rustc_data_structures::stack::ensure_sufficient_stack::h112bd9a1e5f14b8b
  53:     0x7fbf2ae0c82d - rustc_query_system::query::plumbing::force_query_with_job::hbbccc62bba484e69
  54:     0x7fbf2c5c7786 - rustc_query_system::query::plumbing::get_query_impl::hc496b7da6ca5195d
  55:     0x7fbf2c6707ed - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::h8d17f3fde386d772
  56:     0x7fbf2c0f8a68 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h2007d30ef68567cb
  57:     0x7fbf2c0e844c - rustc_span::with_source_map::hc5adfd8eb2dd5236
  58:     0x7fbf2c0f9c8a - rustc_interface::interface::create_compiler_and_run::h976ed8e22b4f89b8
  59:     0x7fbf2c0ece89 - scoped_tls::ScopedKey<T>::set::h4a2887b4d5b96c48
  60:     0x7fbf2c0e99aa - std::sys_common::backtrace::__rust_begin_short_backtrace::h220030c0c75c9d89
  61:     0x7fbf2c0e8df5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd62830e2741d6b63
  62:     0x7fbf29e31657 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6bff7798948b1075
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  63:     0x7fbf29e31657 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc2d25ac38f6b2342
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
  64:     0x7fbf29e31657 - std::sys::unix::thread::Thread::new::thread_start::hbba5bc368baac205
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
  65:     0x7fbf29d64ea7 - start_thread
  66:     0x7fbf29c81def - clone
  67:                0x0 - <unknown>
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.55.0 (c8dfcfe04 2021-09-06) running on x86_64-unknown-linux-gnu
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [item_children] collecting child items of `qmeta_async`
#1 [visible_parent_map] calculating the visible parent map
#2 [eval_to_const_value_raw] simplifying constant for the type system `config::settings::<impl at src/config/settings.rs:30:1: 49:2>::default::CppClosureInput::Input::{constant#0}`
#3 [collect_mod_item_types] collecting item types in module `config::settings`
#4 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `harbour-whisperfish` due to previous error
```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-09-24 18:13
I believe this should be fixed in the latest nightly.

**Comment by rubdos** [comment] 2021-09-24 19:13
> I believe this should be fixed in the latest nightly.

As far as I know, I cannot test this assumption, can I? If I would "upgrade" the compiler in any way, it would invalidate the incremental build cache?

**Comment by Aaron1011** [comment] 2021-09-24 19:16
@rubdos Thats's right. Unfortunately, the only thing that you can do is to upgrade (either now, or when the next stable version is released), and see if any crashes end up occuring.

**Comment by Enselic** [comment] 2023-09-10 11:34
Triage: Closing since there is no known way to reproduce.

**Closed by Enselic** 2023-09-10 11:34 UTC
Labels: I-ICE, T-compiler, C-bug
