### ISSUE TITLE
Upgrade to LLVM 12 caused AArch64 bare metal program run incorrectly

### ISSUE THREAD

**Issue by songzhi** [rust-lang/rust#83335] opened 2021-03-21 02:37 UTC
Here's the [project](https://github.com/lowenware/leos-kernel) (as an example).
It run correctly when the following toolchain is used: 
```toml
[toolchain]
channel = "nightly-2021-03-04"
targets = ["aarch64-unknown-none-softfloat"]
```
And incorrectly when the following toolchain is used:
```toml
[toolchain]
channel = "nightly-2021-03-05"
targets = ["aarch64-unknown-none-softfloat"]
```
So I think it related to #81451 the upgrade to LLVM 12.
I don't know the exact reason, but back to `nightly-2021-03-04` works for me now.

**Comment by jyn514** [comment] 2021-03-21 03:33
Can you describe what you mean by "incorrectly "?

**Comment by songzhi** [comment] 2021-03-21 03:54
> Can you describe what you mean by "incorrectly "?

I'm not saying the errors about feature gates that compiler throwing, I fixed that. And it complied successfully, but run incorrectly.
The correct behaviour of the leos-kernel in the project is like this:
```
000.00011 - Starting LeOS kernel
000.00021 * task 1: enable_preempt -> 0
000.00026 * core task preempt: 0
000.00029 - Starting task 2
000.00033 - Starting task 3
000.00034 - Starting task 4
000.00035 - Task: 1
001.00023 * task 1: disable_preempt -> 1
001.00028 * Switch context PID 1 -> 2
001.00030 * task 2: enable_preempt -> 0
001.00032 - Task: 2
002.00038 * task 2: disable_preempt -> 1
002.00041 * Switch context PID 2 -> 3
002.00043 * task 3: enable_preempt -> 0
002.00044 - Task: 3
...
```
But when using `nightly-2021-03-05` version rustc, the kernel prints nothing. And I believe it's not related to those feature gates or the restriction of naked function, because my own os kernel project without these features has the same situation.

**Comment by apiraino** [comment] 2021-03-21 09:26
@songzhi for us to frame the issue and we need a way to reproduce it, ideally with a small piece of code (possibly without external libraries) that shows the incorrect behaviour you described.
Also, can you report if you can reproduce on other toolchains (example beta and stable)?

**Comment by songzhi** [comment] 2021-03-21 10:25
I just found why. Here's the minimal reproducible code:
```
// Linker script
SECTIONS
{
. = 0xffff000040080000;
}
```
``` rust
#![no_std]
#![no_main]
#![feature(global_asm)]
#![feature(asm)]

use core::ptr;

global_asm!(r#"
.section .text.boot
.globl _start

_start:
    # the device tree address
    mov     x23, x0
    # read cpu affinity, start core 0, halt rest
    mrs     x19, mpidr_el1
    and     x19, x19, #3
    # compare and branch if non zero
    cbnz    x19, halt

    adrp    x0, _start
    sub     x0, x0, x19, lsl #16
    mov     sp, x0

    b       main_start

halt:
    # unreachable
    wfe
    b       halt
"#);

const UART_BASE: usize = 0x0900_0000;

#[inline]
fn halt() {
    unsafe { asm!("wfi", options(nomem, nostack)) }
}

#[inline]
fn wfe() {
    unsafe { asm!("wfe", options(nomem, nostack)) }
}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {
        wfe();
    }
}

extern "C" {
    fn _start();
}

#[no_mangle]
pub unsafe extern "C" fn main_start() {
    let x = _start as usize;
    // just used to prevent `x` is optimized.
    ptr::write_volatile(UART_BASE as *mut u8, (x % 10 + '0' as usize) as u8);

    halt();
}
```
Here's the difference of generated assembly code (based on generated ELF file), comparing `nightly-2021-03-04` version to `nightly-2021-03-05` version.
```
22,23c22,23
< ffff000040080028:     90000008        adrp    x8, ffff000040080000 <_start>
< ffff00004008002c:     91000108        add     x8, x8, #0x0
---
> ffff000040080028:     b0000008        adrp    x8, ffff000040081000 <etext>
> ffff00004008002c:     f9400108        ldr     x8, [x8]
34a35,45
>       ...
> 
> Disassembly of section .got:
> 
> ffff000040081000 <.got>:
> ffff000040081000:     40080000        .inst   0x40080000 ; undefined
> ffff000040081004:     ffff0000        .inst   0xffff0000 ; undefined
> 
> Disassembly of section .rodata:
> 
> ffff000040081008 <srodata>:
```
Actually QEMU load the kernel binary at address `0x40080000`, so the `adrp    x8, ffff000040080000 <_start>` is actually  ` adrp    x8, 40080000`, then the `_start` we got is `0x40080000`. But in later version of rustc, the `_start` is `0xFFFF000040080000`. In this specific case, the former value is considered correct.

It's a breaking change, but I don't know if it could be considered as a bug. Maybe this usage could be considered as a undefined behaviour? I don't know what do you think about it.

My own OS kernel still runs incorrectly, I'll keep digging to find out if it related to rustc, if not I'll close this issue.

**Comment by songzhi** [comment] 2021-03-21 15:22
Just found another, emmm, bug? Here's the code, using `qemu-system-aarch64 -M virt -kernel $(kernel)` to run it:
``` 
// linker script
SECTIONS
{
  .text : {
    *(.text.boot)
    *(.text .text.* .gnu.linkonce.t*)
    . = ALIGN(4K);
  }

  .rodata : {
    *(.rodata .rodata.* .gnu.linkonce.r*)
    . = ALIGN(4K);
  }

  .data : {
    *(.data .data.* .gnu.linkonce.d*)
    . = ALIGN(4K);
  }

  .stack : {
    . = ALIGN(4K);
    *(.bss.stack)
  }

  .bss : {
    . = ALIGN(32);
    *(.bss .bss.*)
    *(COMMON)
    . = ALIGN(4K);
  }

  /DISCARD/ : { *(.comment) *(.gnu*) *(.note*) *(.eh_frame*) }
}
```

```rust
#![no_std]
#![no_main]
#![feature(global_asm)]
#![feature(asm)]

use core::ptr;

global_asm!(
    r#"
.section .text.boot
.globl _start

_start:
    # read cpu affinity, start core 0, halt rest
    mrs     x19, mpidr_el1
    and     x19, x19, #3
    # compare and branch if non zero
    cbnz    x19, halt

    adrp    x0, _start
    sub     x0, x0, x19, lsl #16
    mov     sp, x0

    b       main_start

halt:
    # unreachable
    wfe
    b       halt

.section .data
.align 12
data_block:
    .space 0x1000 // 4K
data_block2:
    .space 0x1000 // 4K
"#
);

const UART_BASE: usize = 0x0900_0000;
const KERNEL_OFFSET: usize = 0xffff_0000_0000_0000;

#[inline]
fn halt() {
    unsafe { asm!("wfi", options(nomem, nostack)) }
}

#[inline]
fn wfe() {
    unsafe { asm!("wfe", options(nomem, nostack)) }
}

#[inline]
fn as_lower_range(addr: usize) -> usize {
    addr & !KERNEL_OFFSET
}

fn print_str(s: &str) {
    for c in s.as_bytes() {
        unsafe {
            ptr::write_volatile(UART_BASE as *mut u8, *c);
        }
    }
}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {
        wfe();
    }
}

extern "C" {
    fn _start();
    fn data_block();
    fn data_block2();
}

#[no_mangle]
pub unsafe extern "C" fn main_start() {
    let data_block2 = as_lower_range(data_block2 as usize) as *mut u8;
    if data_block2.is_null() {
        print_str("Null\n");
    } else {
        print_str("Not Null\n");
    }
    halt();
}
```
Generated assembly code difference, comparing `nightly-2021-03-04` to `nightly-2021-03-05`:
```  diff
24,25c24,25
<       30:     d0000009        adrp    x9, 2000 <data_block2>
<       34:     91000129        add     x9, x9, #0x0
---
>       30:     d0000009        adrp    x9, 2000 <data_block>
>       34:     f9400129        ldr     x9, [x9]
47a48,58
> Disassembly of section .got:
> 
> 0000000000001000 <.got>:
>     1000:     00002000        udf     #8192
>     1004:     00000000        udf     #0
> 
> Disassembly of section .rodata:
> 
> 0000000000001008 <.rodata>:
>       ...
> 
50c61
< 0000000000001000 <data_block>:
---
> 0000000000002000 <data_block>:
53c64
< 0000000000002000 <data_block2>:
---
> 0000000000003000 <data_block2>:
```
Output of the `nightly-2021-03-04` version code is `Not Null`, another is `Null`. The problem is, in the `nightly-2021-03-05` version code, it try to read the value from `0x40082000` as `data_block2`'s address, which is `0`/`nullptr`.
I don't know why such code is generated, but it seems like a real bug?

**Comment by jyn514** [comment] 2021-03-21 15:25
@rustbot ping llvm

I don't know assembly well enough to see if this is a real bug or not - it would be helpful to figure out what the expected behavior is.

**Comment by songzhi** [comment] 2021-03-21 15:41
@jyn514 The second case is pretty common, maybe we want to initialize the data_block2, since we get a null pointer, it's not possible. In my OS kernel, I allocate and operate some pagetables like this, it's inspired by [rCore](https://github.com/rcore-os/rCore).

**Comment by nagisa** [comment] 2021-03-21 17:30
Looks like with the new version the binary generated uses `pic` relocation model, and attempts to specify different relocation models get ignored.

Here's a more [minimal reproducer](https://rust.godbolt.org/z/snT4dh):

```rust
// RUN: --target=aarch64-unknown-none-softfloat -O -Cdebuginfo=0 -Crelocation-model=static
#![no_std]

extern "C" {
    fn _start();
}

#[no_mangle]
pub unsafe extern "C" fn main_start() {
    loop {
        core::ptr::read_volatile(_start as *mut u8);
    }
}
```

I'm not yet sure if its a genuine bug (probably is) that we ignore the `relocation-model`, but I think on the user's end this could also be fixed by adjusting their linker script to correctly handle the `.got` section.

**Comment by ojeda** [comment] 2021-03-23 01:08
We also run into this, in both arm64 and x86_64 (https://github.com/Rust-for-Linux/linux/issues/135).

**Comment by nagisa** [comment] 2021-03-23 12:34
Upstream issue report: https://bugs.llvm.org/show_bug.cgi?id=49693

**Comment by MaskRay** [comment] 2021-03-23 17:28
> Upstream issue report: https://bugs.llvm.org/show_bug.cgi?id=49693

Not implying dso_local for a declaration in --relocation-model=static is intented. See also https://internals.rust-lang.org/t/is-dso-local-set-in-llvm-ir-output/13725

**Comment by nagisa** [comment] 2021-03-23 23:31
Cool. I'm not super familiar with the relocation stuff, and reading the [referenced blog post](https://maskray.me/blog/2021-01-09-copy-relocations-canonical-plt-entries-and-protected) didn't really make anything much clearer to me. Admittedly I didn't have much capacity to think things through while reading it, so maybe a weekend will make things somewhat clearer to me ^^.

All that said, it is not obvious to me if we want to slap `dso_local` on everything with `-Crelocation-model=static` or not. If there's anybody who has all the relocation particularities internalized (esp. in context of Rust), advice would be appreciated.

**Comment by apiraino** [comment] 2021-03-31 10:17
Removing `I-prioritize`, PR is on the way ([Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2383335.20Upgrade.20to.20LLVM.2012.20caused.20AArch64.20bare.20metal.20program.E2.80.A6))

@rustbot  label -I-prioritize

**Closed** 2021-04-06 04:35 UTC
Labels: A-LLVM, C-bug, ICEBreaker-LLVM, O-ARM, T-compiler, regression-from-stable-to-nightly
