### ISSUE TITLE
rustdoc: Expandable function code snippets

### ISSUE THREAD

**Issue by Qard** [rust-lang/rust#21346] opened 2015-01-18 04:24 UTC
Rather than just having the current [src] link at the top of the doc pages, it'd be nice to be able to have a [src] link for each function that expands with a code snippet of that particular function. Just like what the [-] and [+] buttons already do for the markdown comments.

It'd be a really helpful learning tool to be able to jump directly to the code you want to use and see what it's actually doing behind the scenes. It could also help people to get acquainted enough with the core code base to start making useful contributions. :)

**Comment by steveklabnik** [comment] 2015-11-07 07:37
Triage: no change

**Comment by birkenfeld** [comment] 2016-05-09 16:04
Duplicate of #12932.

**Comment by alexcrichton** [comment] 2016-05-09 16:23
Indeed!

**Closed by alexcrichton** 2016-05-09 16:23 UTC
Labels: A-rustdoc
