### ISSUE TITLE
ICE on maybe build.rs

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust#85010] opened 2021-05-06 20:55 UTC
### Code

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0 (88f19c6da 2021-05-03) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0 (88f19c6da 2021-05-03)
binary: rustc
commit-hash: 88f19c6dab716c6281af7602e30f413e809c5974
commit-date: 2021-05-03
host: x86_64-apple-darwin
release: 1.52.0
LLVM version: 12.0.0
```

### Error output

```
   Compiling remote-apis v0.1.0 (/Users/tschuett/Work/rust-stuff/remote-apis)
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[7cda]::fmt::Debug): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::fmt::Debug>)), /Users/schuett/.rustup/toolchains/1.52.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:550:1: 550:16 (#0))] }', /rustc/88f19c6dab716c6281af7602e30f413e809c5974/compiler/rustc_query_system/src/query/plumbing.rs:593:5
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0:        0x1136dc474 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7c9bbbcf55ac7d45
   1:        0x1137407be - core::fmt::write::hc858fa51ad07feb2
   2:        0x1136cfd26 - std::io::Write::write_fmt::h13e13e9932df1a87
   3:        0x1136e0229 - std::panicking::default_hook::{{closure}}::hca29e9daefd4910e
   4:        0x1136dfd10 - std::panicking::default_hook::h39360a887d72e62b
   5:        0x10bf48bc8 - rustc_driver::report_ice::hf6ee0c6b441bcfd3
   6:        0x1136e09f8 - std::panicking::rust_panic_with_hook::h4a0037861340f650
   7:        0x1136e0515 - std::panicking::begin_panic_handler::{{closure}}::hf455655e1cea0b96
   8:        0x1136dc8d8 - std::sys_common::backtrace::__rust_end_short_backtrace::hd403f11cffc53200
   9:        0x1136e047a - _rust_begin_unwind
  10:        0x11376868b - std::panicking::begin_panic_fmt::hf7331a6ff837dbba
  11:        0x10eb8cd45 - rustc_query_system::query::plumbing::incremental_verify_ich::h30c186afdd3dda04
  12:        0x10ebbec2e - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::he02180e919661975
  13:        0x10ee60095 - rustc_data_structures::stack::ensure_sufficient_stack::h1c1ebb269489169b
  14:        0x10eaba09d - rustc_query_system::query::plumbing::get_query_impl::h87e3ad87171b99fa
  15:        0x10ed432dd - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of::h90a4b5d58fd53d83
  16:        0x10ffed6d7 - rustc_middle::ty::generics::GenericPredicates::instantiate_identity_into::h4899164b76027b7a
  17:        0x10ffed3dd - rustc_middle::ty::generics::GenericPredicates::instantiate_identity::h0f75e3f66e3653cc
  18:        0x10fbfe3a5 - rustc_trait_selection::traits::object_safety::generics_require_sized_self::h4be7f8d3f85ab28c
  19:        0x10fc1758a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hd5d2d18829b4a0b6
  20:        0x10fc3b916 - <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next::h06150c4b04494d9b
  21:        0x10fc471ac - <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend::h6ae20d3a9780d6a4
  22:        0x1103b316c - rustc_arena::cold_path::hbe385ffe92f6b3b1
  23:        0x10fc55f62 - rustc_middle::arena::Arena::alloc_from_iter::h21aeeefd6d0d9763
  24:        0x10fc2604b - rustc_trait_selection::traits::vtable_methods::h6008e9818b6db853
  25:        0x10ebca5c2 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::vtable_methods>::compute::hc611a8c48007a873
  26:        0x10ee44f01 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h8d01a5f53022743d
  27:        0x10ebb88ae - rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory::h947705da500cebee
  28:        0x10ee65c9b - rustc_data_structures::stack::ensure_sufficient_stack::h414c16af3855c534
  29:        0x10eadea27 - rustc_query_system::query::plumbing::get_query_impl::hc8213fad1682d378
  30:        0x10ed495b8 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::vtable_methods::h02854dfcbca5d47d
  31:        0x10f187b25 - <rustc_mir::monomorphize::collector::MirNeighborCollector as rustc_middle::mir::visit::Visitor>::visit_rvalue::h77cdbf21b5f80dc3
  32:        0x10f18c38a - rustc_mir::monomorphize::collector::collect_neighbours::h3f761dec92aa41d2
  33:        0x10f1850f8 - rustc_mir::monomorphize::collector::collect_items_rec::hfc77cf05e51bff73
  34:        0x10f18532c - rustc_mir::monomorphize::collector::collect_items_rec::hfc77cf05e51bff73
  35:        0x10f18532c - rustc_mir::monomorphize::collector::collect_items_rec::hfc77cf05e51bff73
  36:        0x10f18532c - rustc_mir::monomorphize::collector::collect_items_rec::hfc77cf05e51bff73
  37:        0x10f183d0b - rustc_mir::monomorphize::collector::collect_crate_mono_items::h4dcbbff984fcda48
  38:        0x10f48437c - rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items::hc8d8126b500e1cd3
  39:        0x10ebcd269 - rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::collect_and_partition_mono_items>::compute::h5aae43df8387f0d7
  40:        0x10ee3f464 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h4b3a7473faa21ea4
  41:        0x10eda50bd - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h833c225b3a6dbfe8
  42:        0x10ee80aee - rustc_data_structures::stack::ensure_sufficient_stack::hedae8047b0d04e57
  43:        0x10eb50955 - rustc_query_system::query::plumbing::force_query_with_job::h741ab9e92adade18
  44:        0x10eac9ce6 - rustc_query_system::query::plumbing::get_query_impl::ha3a4a42d8c0bd225
  45:        0x10ed4d8c4 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items::h985b913bc88c64f6
  46:        0x10c1b1081 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h6bc894c6fe50952b
  47:        0x10c07b8cf - rustc_interface::passes::QueryContext::enter::hbc2547ee20785fb4
  48:        0x10c08e810 - rustc_interface::queries::Queries::ongoing_codegen::h0ec5a3b80815853c
  49:        0x10bf5ea80 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hee16922a2fec6e91
  50:        0x10bf4a951 - rustc_span::with_source_map::h383e3e407d1721aa
  51:        0x10bf603c3 - rustc_interface::interface::create_compiler_and_run::hdfd9880ea1c8d4e1
  52:        0x10bf525d6 - scoped_tls::ScopedKey<T>::set::he115e8939c2081ab
  53:        0x10bf60c49 - std::sys_common::backtrace::__rust_begin_short_backtrace::he90d2fe78e348f03
  54:        0x10bf7db8d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd874d80d2b97518c
  55:        0x1136edfed - std::sys::unix::thread::Thread::new::thread_start::ha15385db9c193654
  56:     0x7fff2053e954 - __pthread_start
```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-05-06 22:48
Duplicate of https://github.com/rust-lang/rust/issues/84341. This is fixed in the latest nightly. As a workaround, you can run `cargo clean -p <your_package_name>` or `cargo clean`.

**Closed by Aaron1011** 2021-05-06 22:48 UTC
Labels: A-incr-comp, C-bug, I-ICE, T-compiler
