### ISSUE TITLE
Error text overlaps in rustc.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-lang/rust#42704] opened 2017-06-16 17:47 UTC
This might not be the right place to post it, but I'm getting strange overlapping text on the latest nightly build of Rust:

```rust
use std::mem;
fn main() {
    let chars: Option<&str> = unsafe { mem::uninitialized() };
    chars += 1;
}
```

Expected output (works on `rustc 1.18.0 (03fc9d622 2017-06-06)`):

```
  |
4 |     chars += 1;
  |     ^^^^^ cannot use `+=` on type `std::option::Option<&str>`
```

Actual output (on `rustc 1.19.0-nightly (258ae6dd9 2017-06-15)`):

```
  |
4 |     chars += 1;
  |     -----^^^^^ot use `+=` on type `std::option::Option<&str>`
```

Playground: https://is.gd/k0HSS8

**Comment by sfackler** [comment] 2017-06-16 17:51
Duplicate of https://github.com/rust-lang/rust/issues/42595.

**Closed by sfackler** 2017-06-16 17:51 UTC
