### ISSUE TITLE
Can't use a custom proc_macro_attribute at crate root

### ISSUE THREAD

**Issue by DanielShaulov** [rust-lang/rust#42699] opened 2017-06-16 15:26 UTC
I have a proc-macro crate `mycrate`, that defines a `#[proc_macro_attribute]` function `mymacro`.
There is no way to use it (that I could find) at crate root level

I tried this code:
```rust
#![feature(proc_macro)]
extern crate mycrate;
#![mycrate::mymacro]
```
And I get the following error:
`error: an inner attribute is not permitted in this context`
As I understand this is because I use it after the `extern crate`, but it won't resolve before it.

(I know this feature is not stable yet, just want to know if there is a plan/workaround for this)

## Meta
`rustc --version --verbose`:
```
rustc 1.19.0-nightly (554c685b0 2017-06-14)
binary: rustc
commit-hash: 554c685b0b3b25b7aa752717edf50b8d6bcab7a0
commit-date: 2017-06-14
host: x86_64-pc-windows-msvc
release: 1.19.0-nightly
LLVM version: 4.0
```

**Comment by kennytm** [comment] 2017-06-16 16:12
Duplicate of #41430?

**Comment by Mark-Simulacrum** [comment] 2017-06-16 17:04
I believe so, yes. Closing.

**Closed by Mark-Simulacrum** 2017-06-16 17:04 UTC
