### ISSUE TITLE
Compile Substrate fail because compiler error

### ISSUE THREAD

**Issue by jasl** [rust-lang/rust#65476] opened 2019-10-16 18:54 UTC
OS: Ubuntu 18.04.3 Kernel 5.0.0-31-generic

Rust: rustc 1.40.0-nightly (237d54ff6 2019-10-15) running on x86_64-unknown-linux-gnu

Substrate: [paritytech/substrate@e0f3fa3845654770f6d96dbaa2d3a76842ad44f3](https://github.com/paritytech/substrate/tree/e0f3fa3845654770f6d96dbaa2d3a76842ad44f3)

Output:

```
     Running `rustc --edition=2018 --crate-name substrate node/src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=f7fdf3904d78ac06 -C extra-filename=-f7fdf3904d78ac06 --out-dir /home/jasl/Workspaces/substrate/target/debug/deps -C incremental=/home/jasl/Workspaces/substrate/target/debug/incremental -L dependency=/home/jasl/Workspaces/substrate/target/debug/deps --extern ctrlc=/home/jasl/Workspaces/substrate/target/debug/deps/libctrlc-56b3c5891f2c52fc.rlib --extern futures=/home/jasl/Workspaces/substrate/target/debug/deps/libfutures-8044478ab292ec8c.rlib --extern cli=/home/jasl/Workspaces/substrate/target/debug/deps/libnode_cli-e098644483172d51.rlib -L native=/home/jasl/Workspaces/substrate/target/debug/build/clear_on_drop-d947fcbd8f8247d9/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/backtrace-sys-e930a9bb136e2680/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/ring-360fed56ad6bbbf1/out -L native=/usr/lib/x86_64-linux-gnu -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out`
thread 'rustc' panicked at 'Tried to access field 0 of union with 0 fields', src/librustc_target/abi/mod.rs:742:17
stack backtrace:
   0:     0x7f58ea5e4934 - backtrace::backtrace::libunwind::trace::h187f113b2abb647f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x7f58ea5e4934 - backtrace::backtrace::trace_unsynchronized::h38320d8128cd24b5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x7f58ea5e4934 - std::sys_common::backtrace::_print_fmt::h556c1c2dcb1a6658
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7f58ea5e4934 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc8b96dbda96cbdc1
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7f58ea61cbbc - core::fmt::write::h5df803e3899d44e6
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7f58ea5d8c07 - std::io::Write::write_fmt::h68c8001b57139b09
                               at src/libstd/io/mod.rs:1412
   6:     0x7f58ea5e916e - std::sys_common::backtrace::_print::hd5e7e75fe3073c40
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7f58ea5e916e - std::sys_common::backtrace::print::he7bb8f2987194f75
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7f58ea5e916e - std::panicking::default_hook::{{closure}}::hb1d0eb5b0ef71aca
                               at src/libstd/panicking.rs:189
   9:     0x7f58ea5e8e71 - std::panicking::default_hook::h180de3c633f62ee7
                               at src/libstd/panicking.rs:206
  10:     0x7f58eaae5963 - rustc_driver::report_ice::h943674422e887656
  11:     0x7f58ea5e994c - std::panicking::rust_panic_with_hook::hdbd08e13a7c982fe
                               at src/libstd/panicking.rs:473
  12:     0x7f58ea5e9402 - std::panicking::continue_panic_fmt::hce8732bd3590e67f
                               at src/libstd/panicking.rs:376
  13:     0x7f58ea5e935c - std::panicking::begin_panic_fmt::h9d3aff33cedf1e1a
                               at src/libstd/panicking.rs:331
  14:     0x7f58ec8c5cd1 - rustc_target::abi::FieldPlacement::offset::hfb3e4a2ad9e6cd16
  15:     0x7f58e5fad735 - rustc_codegen_ssa::mir::place::PlaceRef<V>::project_field::h38440b93c9633575
  16:     0x7f58e6053fad - rustc_codegen_ssa::mir::place::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_place::h17ebbf195998713d
  17:     0x7f58e60491f2 - rustc_codegen_ssa::mir::codegen_mir::h6bbcbf5809d154c8
  18:     0x7f58e602e2fe - rustc_codegen_ssa::base::codegen_instance::h37a157a3aca0e471
  19:     0x7f58e5f78322 - <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define::h8204968aa7461e7a
  20:     0x7f58e5f1eeda - rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::hc8273747e49b428e
  21:     0x7f58e5f5ebc5 - rustc::dep_graph::graph::DepGraph::with_task::h5de5c5fd16c8f299
  22:     0x7f58e5f1eba9 - rustc_codegen_llvm::base::compile_codegen_unit::hcedf321479019fbf
  23:     0x7f58e602cc08 - rustc_codegen_ssa::base::codegen_crate::hbe58b8768abdc62b
  24:     0x7f58e5fccd1e - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::h21ab9a02c80c1a8c
  25:     0x7f58eabc2f19 - rustc_interface::passes::start_codegen::{{closure}}::hcb30f75905d640ef
  26:     0x7f58eabbb925 - rustc::util::common::time::h3a5a6160a76b6f8c
  27:     0x7f58eab9644e - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::hf8fe0981326f5458
  28:     0x7f58eabc201a - rustc_interface::passes::create_global_ctxt::{{closure}}::h0c89f0086e4130ed
  29:     0x7f58eab8ff83 - rustc_interface::queries::Query<T>::compute::h0fb9d0d1e7bc9546
  30:     0x7f58eac41c54 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen::h9a0c1f75b9cdaf12
  31:     0x7f58eaaeacaa - rustc_interface::interface::run_compiler_in_existing_thread_pool::h01fe73e69f5e084a
  32:     0x7f58eaafedd2 - std::thread::local::LocalKey<T>::with::h029a205695963fd9
  33:     0x7f58eaae779e - scoped_tls::ScopedKey<T>::set::h52915fe63bb9c195
  34:     0x7f58eab1d3e2 - syntax::with_globals::h0256728050c39909
  35:     0x7f58eab225a2 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2e13ae95f5a5ea8a
  36:     0x7f58ea5fa01a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  37:     0x7f58eab2fd39 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdcb2a4680182bdfd
  38:     0x7f58ea5cb0af - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7da61bc7e02fb501
                               at /rustc/237d54ff6c4fb3577e02d4c5af02813c11b63d01/src/liballoc/boxed.rs:932
  39:     0x7f58ea5f8cc0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hba3e21cc97052690
                               at /rustc/237d54ff6c4fb3577e02d4c5af02813c11b63d01/src/liballoc/boxed.rs:932
  40:     0x7f58ea5f8cc0 - std::sys_common::thread::start_thread::h01615c70a0bd60b8
                               at src/libstd/sys_common/thread.rs:13
  41:     0x7f58ea5f8cc0 - std::sys::unix::thread::Thread::new::thread_start::h1b9e14f0dce26914
                               at src/libstd/sys/unix/thread.rs:79
  42:     0x7f58ea3656db - start_thread
  43:     0x7f58e9c8288f - __clone
  44:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (237d54ff6 2019-10-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `substrate`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name substrate node/src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=f7fdf3904d78ac06 -C extra-filename=-f7fdf3904d78ac06 --out-dir /home/jasl/Workspaces/substrate/target/debug/deps -C incremental=/home/jasl/Workspaces/substrate/target/debug/incremental -L dependency=/home/jasl/Workspaces/substrate/target/debug/deps --extern ctrlc=/home/jasl/Workspaces/substrate/target/debug/deps/libctrlc-56b3c5891f2c52fc.rlib --extern futures=/home/jasl/Workspaces/substrate/target/debug/deps/libfutures-8044478ab292ec8c.rlib --extern cli=/home/jasl/Workspaces/substrate/target/debug/deps/libnode_cli-e098644483172d51.rlib -L native=/home/jasl/Workspaces/substrate/target/debug/build/clear_on_drop-d947fcbd8f8247d9/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/backtrace-sys-e930a9bb136e2680/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/ring-360fed56ad6bbbf1/out -L native=/usr/lib/x86_64-linux-gnu -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out -L native=/home/jasl/Workspaces/substrate/target/debug/build/librocksdb-sys-f48a316ddd7270f3/out` (exit code: 101)
```

**Comment by jonas-schievink** [comment] 2019-10-16 18:59
Duplicate of https://github.com/rust-lang/rust/issues/65462

**Closed by jonas-schievink** 2019-10-16 18:59 UTC
