### ISSUE TITLE
dbench-0.1.0 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43661] opened 2017-08-05 12:37 UTC
[dbench](https://crates.io/crates/dbench) version 0.1.0 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/dbench-0.1.0/log.txt)):

```
error: type `io::IoPack + 'static` is private
    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/mysql-8.0.0/src/conn/mod.rs:1043:35
     |
1043 |         let (data, seq_id) = try!(self.get_mut_stream().as_mut().read_packet(old_seq_id));
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
cc @giovanniberti

**Comment by est31** [comment] 2017-08-05 12:42
hmmm #43662

**Comment by petrochenkov** [comment] 2017-08-05 12:46
Yeah, duplicate of https://github.com/rust-lang/rust/issues/43662

**Closed by petrochenkov** 2017-08-05 12:46 UTC
