### ISSUE TITLE
Private fields in aliased type should not be shown

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust#124938] opened 2024-05-09 17:56 UTC
I tried this code:

```rust
use std::collections::BTreeMap;

pub type FooBar = BTreeMap<u32, String>;
```

with `rustdoc` and `--document-private-items`.

I expected to see this happen: No internal fields of the `BTreeMap` should be displayed as users won't be able to use the fields, making their appearance confusing and useless.

Instead, this happened: The internal fields of the `BTreeMap` are displayed

![image](https://github.com/rust-lang/rust/assets/3616612/b6f266fd-a684-42a7-b9a5-802380936b33)

Real impact as can be seen [here](https://doc.rust-lang.org/nightly/nightly-rustc/cargo_util_schemas/manifest/type.TomlLints.html).

### Meta

`rustdoc --version --verbose`:
```
rustdoc 1.80.0-nightly (7d83a4c13 2024-05-06)
binary: rustdoc
commit-hash: 7d83a4c131ab9ae81a74c6fd825c827d74a2881d
commit-date: 2024-05-06
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4
```

**Comment by lqd** [comment] 2024-05-09 19:26
Dupe of #123860 and more discussion there

**Closed** 2024-05-12 00:02 UTC
Labels: T-rustdoc, C-bug, A-rustdoc-ui
