### ISSUE TITLE
ICE with Const Generic expression inside turbofish syntax

### ISSUE THREAD

**Issue by imbrem** [rust-lang/rust#60798] opened 2019-05-13 20:57 UTC
I found an ICE with the following:
```rust
#![feature(const_generics)]

struct Foo<const N : usize>();

fn main() {
    let _ = Foo::<3>();
}
```
Here's a link to the [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=94a30122e23b8227d3a8bc37e756b464)

I was poking around in `collect.rs`, where the error seems to be from, and it looks like some cases in a `match` statement are not being handled, but I'm not familiar enough with the code-base to see how to fix this.

**Comment by varkor** [comment] 2019-05-13 21:31
This should be fixed by https://github.com/rust-lang/rust/pull/60710.

**Comment by varkor** [comment] 2019-05-14 19:50
Actually, this is a duplicate of https://github.com/rust-lang/rust/issues/60818 (I'll close this issue simply because the other has more comments now).

**Closed by varkor** 2019-05-14 19:50 UTC
Labels: A-const-generics, I-ICE, T-compiler
