### ISSUE TITLE
Symbols blow up binary size to an unreasonable degree on x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust#46034] opened 2017-11-16 13:14 UTC
Standard hello world program generated with `cargo new --bin mytest`
```rust
fn main() {
    println!("Hello, world!");
}

```

Built with `cargo build --release`, the resulting binary size is 4270408 bytes.
This sounds unreasonably large for a hello world program.

After `strip --strip-all`, we get 449224.

The non-stripped version is almost 10 times larger than the stripped version. Why?

This is with `rustc 1.23.0-nightly (fa26421f5 2017-11-15)`, installed through rustup.

```
$ rustc -vV
rustc 1.23.0-nightly (fa26421f5 2017-11-15)
binary: rustc
commit-hash: fa26421f56e385b1055e65b29a55b36bb2eae23e
commit-date: 2017-11-15
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0
```

Here is stable `rustc 1.21.0 (3b72af97e 2017-10-09)` for good measure:
Normal: 4059968
Stripped: 404096

This time, the initial size is lower, but the stripped size is even smaller, making the non-stripped version slightly _more_ than 10 times larger.

(As a sidenote, I've been noticing that binary sizes for the same program have been steadily increasing with every new rustc, at least on `x86_64-unknown-linux-gnu`, but that's a separate issue, I suppose)

**Comment by kennytm** [comment] 2017-11-16 13:40
@crumblingstatue Can you show the `rustc -vV` output?

----

On x86_64-apple-darwin:

| Version | Size |
|---:|---:|
| `1.23.0-nightly (fa26421f5 2017-11-15)` | 525348 |
| `1.23.0-nightly (ff0f5de3b 2017-11-14)` | 525348 |
| `1.22.0-beta.3 (cc6ed0640 2017-11-13)` | 520164 |
| `1.21.0 (3b72af97e 2017-10-09)` | 452684 |
| `1.15.1 (021bd294c 2017-02-08)` | 390608 |

The size is definitely growing but not something that increases by 10×.

**Comment by crumblingstatue** [comment] 2017-11-16 13:42
@kennytm updated OP with `rustc -vV` info.

**Comment by kennytm** [comment] 2017-11-16 13:54
Repro'd on Linux with stable. (Not sure about the BSDs)

| Version | Size |
|---:|---:|
| `1.21.0 (3b72af97e 2017-10-09)` | 4062904 |
| `1.15.1 (021bd294c 2017-02-08)` | 3465968 |
| `1.10.0 (cfcb716cf 2016-07-03)` | 647760 |
| `1.5.0 (3d7cd77e4 2015-12-04)` | 557208 |
| `1.0.0 (a59de37e9 2015-05-13)` | 579688 |

The 10× size blow up comes somewhere between 1.10.0 to 1.15.1.

**Comment by kennytm** [comment] 2017-11-16 14:37
#43392 seems to be the same problem. Since Windows and macOS places the debug symbols externally (*.pdb and *.dSYM respectively), we don't see the size blow up on those platforms.

**Comment by est31** [comment] 2017-11-16 14:42
This seems like a very important thing. Size affects linkage time, affects compilation speed.

**Comment by kennytm** [comment] 2017-11-16 14:53
From the 1.14.0 release note I believe the cause of the 1.13.0 → 1.14.0 jump is introduced by #37280, where `libstd` starts to be built with `-C debuginfo=1`. However the underlying cause is still #43392, that release builds copy the debuginfo from libstd.

**Comment by michaelwoerister** [comment] 2017-11-16 16:53
Making the assumption that this is caused by `libstd` debuginfo, the size difference in percent should become smaller for larger programs, that is, running `strip` on a big crate should not reduce its size by 90%. Has anybody tried this?

**Comment by Michael-F-Bryan** [comment] 2018-01-04 09:38
On `mdbook`, a non-trivial sized project with about 5.5 kloc of Rust.

```
$ rustc --version
rustc 1.24.0-nightly (687d3d15b 2018-01-02)
$ cargo build --release
$ du -h ./target/release/mdbook
12M	./target/release/mdbook
$ strip ./target/release/mdbook 
$ du -h ./target/release/mdbook
6.3M	./target/release/mdbook
```

So stripping debug info goes from 12M to 6.3M.

**Comment by whitequark** [comment] 2018-01-08 12:44
C++/clang solves this with [-gsplit-dwarf](https://gcc.gnu.org/wiki/DebugFission); to anyone interested in implementing the support, it would be as simple as setting the appropriate LLVM codegen option (as seen in clang):

    llvm::TargetOptions &Options;
    // ...
    if (CodeGenOpts.EnableSplitDwarf)
      Options.MCOptions.SplitDwarfFile = CodeGenOpts.SplitDwarfFile;

**Comment by kennytm** [comment] 2018-01-08 13:23
Oh interesting. cc @main-- rust-lang/rfcs#2154.

**Comment by main--** [comment] 2018-01-08 14:25
Thanks. I actually knew about this "debug fission" but was not aware that LLVM already supports it. The nice thing about the old `.gnu_debuglink` is that it's so easy to implement - simply read your debug sections from somewhere else. Debug fission is certainly a more modern approach though. Note that even though that GCC page estimates a 70% reduction from dwo files, it only moves `.debug_info`, `.debug_types`, and `.debug_str`. Most notably, `.debug_line` remains in the original object (and finally the binary).

How good is toolchain support? Of course gdb reads info from dwo files but GNU addr2line does not. It's either just not implemented yet or not intended to work like that (which would be very disappointing since you need `.debug_info` for inlining info) - either way, it's a bad sign.

I'm still having a hard time finding pretty much any documentation at all about debug fissure (beyond that one GCC page) but these points lead me to believe that it's not the best approach for what I'm trying to do in rust-lang/rfcs#2154.

**Comment by whitequark** [comment] 2018-01-08 21:26
> GNU addr2line does not

But... if `.debug_line` remains in the binary, why would `addr2line` need to read .dwo files? Is it to handle inlined functions? (I am not familiar with that part of DWARF.)

**Comment by main--** [comment] 2018-01-09 01:11
>Is it to handle inlined functions?

Yes. `.debug_line` does not contain inlining info, you need `.debug_info` for that.

**Comment by matklad** [comment] 2018-03-19 07:58
>Making the assumption that this is caused by libstd debuginfo, the size difference in percent should become smaller for larger programs, that is, running strip on a big crate should not reduce its size by 90%. Has anybody tried this?

@michaelwoerister this is kind of true, but only kind of... Measurements in https://users.rust-lang.org/t/rust-binary-sizes-once-again/16287/2 for a crate with "with rocket, serde, wiringpi and pam-auth" should reduction 6.5M -> 1.6M. It is not 90%, but, still, is **very** significant.

Note also an interesting observation that LTO does not affect stripped binaries, but, for non-striped, goes from 6.5M -> 4.7M.


I wonder if there's any actionable items on this issue? Could there be some linker flag for "please, don't link-in the debuginfo into the final binary"?

**Comment by michaelwoerister** [comment] 2018-03-19 09:43
That's a good idea, @matklad. `ld` actually has a `--strip-debug`. We should pass that if the output binary does not request debuginfo.

**Comment by michaelwoerister** [comment] 2018-03-19 09:52
If anyone wants to give it a try, the relevant spot in the source code is here:
https://github.com/rust-lang/rust/blob/15add366faac554db51244d1e27e4d10a08ab6e8/src/librustc_trans/back/linker.rs#L283-L285

This method should add any linker flags relevant to debuginfo.

**Comment by axos88** [comment] 2018-03-20 12:35
I also stumbled upon this cross-compiling from OS X to arm-linux: https://users.rust-lang.org/t/rust-binary-sizes-once-again/16287/2

**Comment by elichai** [comment] 2019-11-11 13:51
Can be closed now that https://github.com/rust-lang/rust/pull/49212 is merged :)

**Comment by kennytm** [comment] 2019-11-12 05:58
@elichai As explained in the PR you need to pass `-Zstrip-debuginfo-if-disabled=yes` to `rustc` to take effect.

**Comment by benesch** [comment] 2020-04-18 22:27
What's the process for stabilizing that flag? It's working great for me, and seems to much better align with expectations of what "no debuginfo" means!

**Comment by petrochenkov** [comment] 2020-05-08 23:46
https://github.com/rust-lang/rust/pull/71825 suggests introducing `-Z strip=[none|debuginfo|symbols]`.

**Comment by petrochenkov** [comment] 2020-05-11 15:19
Closing in favor of the tracking issue for `-Z strip=val` - https://github.com/rust-lang/rust/issues/72110.

**Closed by petrochenkov** 2020-05-11 15:19 UTC
Labels: A-debuginfo, A-linkage, C-bug, E-help-wanted, E-mentor, I-heavy, O-linux

**Comment by est31** [comment] 2020-05-11 15:28
There's also #34651 which is about putting debuginfo into separate files (instead of deleting it completely like `-Z strip=val` does).

**Comment by crumblingstatue** [comment] 2022-01-09 10:43
To be clear, I originally opened this issue to clarify if 10 times larger binary size is expected compared to stripped.
If not, then the problem still persists that something is wrong with symbol generation, which stripping doesn't solve, only removes the symptom if you don't want any symbols.

**Comment by philipc** [comment] 2022-01-13 02:06
I think it's expected because the debuginfo is from libstd, so it'll be large.

**Comment by philipc** [comment] 2022-01-14 06:50
It's possibly not the whole of std, but it will include extra debuginfo since DWARF is not designed to cheaply use only portions of it (the alternative would be slower links, and links are already too slow).
