### ISSUE TITLE
Clarify transmute rules and behavior of `repr(C)`

### ISSUE THREAD

**Issue by apasel422** [rust-lang/rust#29702] opened 2015-11-08 23:05 UTC
I'm in the process of implementing #24545 using the [Nomicon](https://doc.rust-lang.org/nightly/nomicon/transmutes.html) for guidance, but it would be helpful to have a few things clarified:
1. What is the behavior of `transmute::<T, T>(foo)` when `T` is not `repr(C)`? A strict reading of the current text indicates that it is undefined.
2. If a struct (tuple or otherwise) contains only a single field and that field is `repr(C)`, is it safe to transmute to and from it? I assume the answer is no, for simplicity and future compiler optimizations and security features.
3. If a struct is declared `repr(C)` but contains fields that are not `repr(C)`, what is the behavior of transmuting to and from it? I assume it is undefined, which means that the proposed lint needs to recursively examine fields for their `repr(C)`-ness.

CC @Gankro.

**Comment by apasel422** [comment] 2015-11-08 23:40
[`libcore/cmp.rs` contains the following code:](https://github.com/rust-lang/rust/blob/2ef07f05192c98c7441977420efde6730d730b25/src/libcore/cmp.rs#L118-L120)

```rust
unsafe fn from_i8_unchecked(v: i8) -> Ordering {
    mem::transmute(v)
}
```
but `Ordering` is not `repr(C)`, nor does it define its size as one byte via `repr(u8)`. Is this an undefined operation?

**Comment by eefriedman** [comment] 2015-11-08 23:43
"Transmuting between non-repr(C) types is UB" isn't really true; the issue is just that transmuting to or from a non-repr(C) is a bad idea because compiler doesn't make any promises about how the data will be arranged in the structure.

**Comment by Gankro** [comment] 2015-11-08 23:45
I wanted to solidify these rules more but was unable to get a clear picture on this and push it through.

IMO: 1 is trivially sound, 2 *should* be sound, and 3 *could* be sound.

For 2, the only issue I could see is enum optimizations, but e.g. `Option<T>` is not repr(C) so it should be fine? Unless we decide to try to apply TBAA on all non-repr(C) types (CC @arielb1)?

For 3, I think it depends on what T and U look like. If it's like:

```rust
#[repr(C)] struct T(Vec<u8>, Vec<u8>, PhantomData<X>);
#[repr(C)] struct U(Vec<u8>, Vec<u8>, PhantomData<Y>);
```

I'd *like* it to be sound to transmute between these two types.

**Comment by Gankro** [comment] 2015-11-08 23:46
@apasel422 IMO that code should definitely require some more annotations.

**Comment by Gankro** [comment] 2015-11-08 23:50
@eefriedman I'm not really sure how that's distinct from Undefined Behaviour?

**Comment by Gankro** [comment] 2015-11-08 23:53
Some related discussions:

* https://internals.rust-lang.org/t/pre-rfc-solidifying-repr-rust/2306
* https://internals.rust-lang.org/t/safe-trasnsmute-for-slices-e-g-u64-u32-particularly-simd-types/2871/

**Comment by Gankro** [comment] 2015-11-08 23:56
This is a *major* @rust-lang/lang issue. It's not just documentation, an RFC needs to happen that settles these rules more concretely.

**Comment by eefriedman** [comment] 2015-11-09 00:11
For the following:

```rust
struct S(i32, i32);
fn t(s: S) -> i64 {
    assert!(size_of<S>() == size_of<i64>());
    transmute(s)
}
```

There's absolutely no reason this would ever lead to undefined behavior, in the same way that it wouldn't be undefined behavior to write out the operation using memcpy.  (Of course, that doesn't mean it's a good idea.)

**Comment by Gankro** [comment] 2015-11-09 00:25
Yeah I suppose that's fair enough. Still, it seems "simplest" to just declare unreliable transmutes as UB in-and-of-themselves. Particularly since padding is uninit and enums can do some really whacky stuff. Don't really want people trying to be "clever" with transmute, since it's basically the devil.

**Comment by bluss** [comment] 2015-11-09 12:58
I think if we have any further clarifications or rules around for example transmute and UB, it should go into the Rust reference and not just the nomicon, right?

**Comment by steveklabnik** [comment] 2017-03-08 20:09
Triage: I'd imagine the unsafe strike team should be doing this kind of work.

**Comment by steveklabnik** [comment] 2017-03-24 19:27
I'm moving this to https://github.com/rust-lang-nursery/nomicon/issues/6

**Closed by steveklabnik** 2017-03-24 19:27 UTC
Labels: A-nomicon, T-lang
