### ISSUE TITLE
The RELEASES.md file is too big

### ISSUE THREAD

**Issue by tomaszs** [rust-lang/rust#110676] opened 2023-04-22 07:46 UTC
As a result sometimes it does not render

**Comment by Nilstrieb** [comment] 2023-04-22 10:21
This is being discussed on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/Release.20blob.20too.20large

**Comment by ehuss** [comment] 2023-05-15 20:53
I'm going to close as a duplicate of #101714.

**Closed by ehuss** 2023-05-15 20:53 UTC
Labels: T-release
