### ISSUE TITLE
mem::size_of does not work with generic struct parameter

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#56512] opened 2018-12-04 16:59 UTC
The following struct definition does not work:

```rust
pub struct Foo<T> where T: ::std::marker::Sized {
    data: [u8; mem::size_of::<T>()],
    phantom: PhantomData<T>,
}
```

The following error occurs:

```
error[E0277]: the size for values of type `T` cannot be known at compilation time
  --> src/main.rs:10:16
   |
10 |     data: [u8; mem::size_of::<T>()],
   |                ^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `T`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = help: consider adding a `where T: std::marker::Sized` bound
   = note: required by `std::mem::size_of`
```

It works when I replace the generic type with some concrete type. I'm not sure whether this a bug or expected behavior, but the "consider adding a `where T: std::marker::Sized` bound" message does not make any sense.

**Comment by nikic** [comment] 2018-12-04 17:43
This is a duplicate of #43408, which has more information on this issue.

**Closed by nikic** 2018-12-04 17:43 UTC

**Comment by phil-opp** [comment] 2018-12-06 12:19
@nikic Thanks!
