### ISSUE TITLE
LLVM error

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#56271] opened 2018-11-27 07:32 UTC
```
!dbg attachment points at wrong subprogram for function
!766 = distinct !DISubprogram(name: "deserialize<serde_json::de::MapKey<serde_json::read::StrRead>>", linkageName: "_ZN5serde2de5impls89_$LT$impl$u20$serde..de..Deserialize$LT$$u27$de$GT$$u20$for$u20$alloc..string..String$GT$11deserialize17h5c6b0e7c1c46966eE", scope: !768, file: !767, line: 418, type: !772, isLocal: true, isDefinition: true, scopeLine: 418, flags: DIFlagPrototyped, isOptimized: true, unit: !193, templateParams: !860, retainedNodes: !858)
void (%"core::result::Result<alloc::string::String, error::Error>"*, i64*)* @"_ZN5serde2de5impls89_$LT$impl$u20$serde..de..Deserialize$LT$$u27$de$GT$$u20$for$u20$alloc..string..String$GT$11deserialize17h5c6b0e7c1c46966eE"
  call void @llvm.dbg.value(metadata [0 x i8]* %27, metadata !1010, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg !1018
!1018 = !DILocation(line: 1, scope: !1011)
!1011 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", linkageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visitor$LT$$u27$de$GT$$GT$9visit_str17h96701e21a65abda4E", scope: !768, file: !767, line: 322, type: !1012, isLocal: true, isDefinition: true, scopeLine: 322, flags: DIFlagPrototyped, isOptimized: true, unit: !193, templateParams: !1016, retainedNodes: !1014)
!1011 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", linkageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visitor$LT$$u27$de$GT$$GT$9visit_str17h96701e21a65abda4E", scope: !768, file: !767, line: 322, type: !1012, isLocal: true, isDefinition: true, scopeLine: 322, flags: DIFlagPrototyped, isOptimized: true, unit: !193, templateParams: !1016, retainedNodes: !1014)
!dbg attachment points at wrong subprogram for function
!766 = distinct !DISubprogram(name: "deserialize<serde_json::de::MapKey<serde_json::read::StrRead>>", linkageName: "_ZN5serde2de5impls89_$LT$impl$u20$serde..de..Deserialize$LT$$u27$de$GT$$u20$for$u20$alloc..string..String$GT$11deserialize17h5c6b0e7c1c46966eE", scope: !768, file: !767, line: 418, type: !772, isLocal: true, isDefinition: true, scopeLine: 418, flags: DIFlagPrototyped, isOptimized: true, unit: !193, templateParams: !860, retainedNodes: !858)
void (%"core::result::Result<alloc::string::String, error::Error>"*, i64*)* @"_ZN5serde2de5impls89_$LT$impl$u20$serde..de..Deserialize$LT$$u27$de$GT$$u20$for$u20$alloc..string..String$GT$11deserialize17h5c6b0e7c1c46966eE"
  call void @llvm.dbg.value(metadata [0 x i8]* %30, metadata !1010, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg !1021
!1021 = !DILocation(line: 1889, column: 12, scope: !1011, inlinedAt: !1022)
!1060 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", linkageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visitor$LT$$u27$de$GT$$GT$9visit_str17h96701e21a65abda4E", scope: !768, file: !767, line: 322, type: !1061, isLocal: true, isDefinition: true, scopeLine: 322, flags: DIFlagPrototyped, isOptimized: true, unit: !193, templateParams: !1066, retainedNodes: !1063)
!1060 = distinct !DISubprogram(name: "visit_str<serde_json::error::Error>", linkageName: "_ZN85_$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visitor$LT$$u27$de$GT$$GT$9visit_str17h96701e21a65abda4E", scope: !768, file: !767, line: 322, type: !1061, isLocal: true, isDefinition: true, scopeLine: 322, flags: DIFlagPrototyped, isOptimized: true, unit: !193, templateParams: !1066, retainedNodes: !1063)
error: Could not compile `serde_json`.
```

https://travis-ci.org/bjorn3/rustc_codegen_cranelift/jobs/460098080

**Comment by matthiaskrgr** [comment] 2018-11-27 07:40
Duplicate of https://github.com/rust-lang/rust/issues/56265

**Closed** 2018-11-27 10:03 UTC
