### ISSUE TITLE
many major compile-time perf regressions in jld-day15-parser

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#34042] opened 2016-06-02 16:09 UTC
[Look at the graph](http://perf.rust-lang.org/index.html?start=Wed%20Dec%2023%202015%2015%3A19%3A54%20GMT%2B0000%20%28UTC%29&end=Wed%20May%2018%202016%2012%3A04%3A26%20GMT%2B0000%20%28UTC%29&kind=benchmarks&crates=jld-day15-parser&phases=total&group_by=crate).

**Comment by brson** [comment] 2016-06-02 16:32
I'm having a hard time getting the rustc-perf comparison page to tell me which passes regressed.

**Comment by eddyb** [comment] 2016-06-02 20:28
Also see #33889.

**Comment by brson** [comment] 2016-06-04 01:50
The rustc-perf site changed and the link no longer goes somewhere useful.

**Comment by durka** [comment] 2016-06-04 07:32
[Fixed link](http://perf.rust-lang.org/graphs.html?start=Wed%20Dec%2023%202015%2015%3A19%3A54%20GMT%2B0000%20%28UTC%29&end=Wed%20May%2018%202016%2012%3A04%3A26%20GMT%2B0000%20%28UTC%29&kind=benchmarks&crates=jld-day15-parser&phases=total&group_by=crate)

**Comment by eddyb** [comment] 2016-06-04 08:12
@brson What I do is use Tab + Spacebar to bisect the pass set.

Regressions by passes:
* [macro loading](http://perf.rust-lang.org/graphs.html?start=Tue%20May%2003%202016%2011%3A23%3A13%20GMT%2B0000%20(UTC)&end=Fri%20Jun%2003%202016%2011%3A09%3A31%20GMT%2B0000%20(UTC)&kind=benchmarks&crates=jld-day15-parser&phases=macro%20loading&group_by=crate): `3ms -> 18ms`
* [translation](http://perf.rust-lang.org/graphs.html?start=Tue%20May%2003%202016%2011%3A23%3A13%20GMT%2B0000%20(UTC)&end=Fri%20Jun%2003%202016%2011%3A09%3A31%20GMT%2B0000%20(UTC)&kind=benchmarks&crates=jld-day15-parser&phases=translation&group_by=crate): `40s -> 47s -> 33s -> 74s -> 81s`

**Comment by eddyb** [comment] 2016-06-04 08:38
A rough approximation for the strange dip is [this range of commits](https://github.com/rust-lang/rust/compare/8492b6aa4545e3e86f3b144c9a3834c31c612e38...0667ae93fb72eb25594258e55de9b4ae8f9f02a8).

**Comment by eddyb** [comment] 2016-06-04 09:17
Looks like the first jump in translation, `40s -> 47s` is indeed caused by #33425. Or at least, the date matches.

**Comment by eddyb** [comment] 2016-06-04 09:27
For the last jump in translation, `74s -> 81s`, I have another [approximate range of commits](https://github.com/rust-lang/rust/compare/dd6e8d45e183861d44ed91a99f0a50403b2776a3...97e3a2401e4b2f659d69ed0c0822cae04e3495b7) with #33602 as a potential culprit (also my fault? :disappointed:).

@nrc Could we run the same process that generates the graphs on individual PRs, to confirm such regressions?

**Comment by arielb1** [comment] 2016-06-05 17:32
This seems to be fixed on the latest revision - translation takes 5s on my laptop. Probably #33816 too.

**Comment by nrc** [comment] 2016-06-07 08:51
@eddyb there is no way to do that, sorry. It's a feature nmatsakis has also requested. Easiest way to simulate is just to run time-passes locally before and after the PR.

**Comment by arielb1** [comment] 2016-06-07 09:46
@nrc

I think we should do benchmarks for each bors merge and store *that*. Maybe even do that on the buildbots?

**Comment by eddyb** [comment] 2016-06-07 09:54
@arielb1 Sadly some of the buildbots share resources so they're not deterministic at all.

**Comment by nrc** [comment] 2016-06-07 17:32
@arielb1 we don't have the hardware for that at the moment. We could do this if we decided it was useful enough to justify buying and maintaining more hardware, but I don't think that is the case for now.

**Comment by nikomatsakis** [comment] 2016-06-09 20:12
[This chart](http://perf.rust-lang.org/graphs.html?start=Wed%20Dec%2023%202015%2015%3A19%3A54%20GMT%2B0000%20(UTC)&end=Wed%20Jun%2008%202016%2004%3A38%3A30%20GMT%2B0000%20(UTC)&kind=benchmarks&crates=jld-day15-parser&phases=total&group_by=crate) suggests that our compilation time has (very recently, in the last few days) gotten better since Dec of 2015, which seems to be the point that @brson was originally comparing against.

**Closed** 2016-06-09 20:15 UTC
Labels: I-compiletime, regression-from-stable-to-nightly, T-compiler

**Comment by brson** [comment] 2016-06-11 00:42
Sweet.
