### ISSUE TITLE
cargo `rustflags = ["-Crpath"]` results in one too many ".."

### ISSUE THREAD

**Issue by bukzor** [rust-lang/rust#50485] opened 2018-05-06 20:10 UTC
### What I did:

```
$ tail -n999 src/main.rs Cargo.toml .cargo/config                                                                                                     
==> src/main.rs <==                  
fn main() {}                         

==> Cargo.toml <==                   
[package]                            
name = "null"                        
version = "0.1.0"                    

==> .cargo/config <==                
[build]                              
rustflags = ["-Cprefer-dynamic", "-Crpath"]                                

$ cargo build                        
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s              

$ ./target/debug/null                
./target/debug/null: error while loading shared libraries: libstd-034f91a8bdfaec49.so: cannot open shared object file: No such file or directory      
```

### What I expected:
The binary should do nothing, successfully.

### What happened:
```
$ ./target/debug/null                
./target/debug/null: error while loading shared libraries: libstd-034f91a8bdfaec49.so: cannot open shared object file: No such file or directory    
```

### Why it failed:

```
$ readelf -a ./target/debug/null | grep RUNPATH                            
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../../../../../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:/home/buck/scratch/rust/null/lib/rustlib/x86_64-unknown-linux-gnu/lib]                                                    
```

That's one too many ".."s! See?

```
$ ORIGIN=$PWD/target/debug           

$ ls -ld $ORIGIN/../../../../../../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib                       
ls: cannot access '/home/buck/scratch/rust/null/target/debug/../../../../../../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib': No such file or directory                          

$ ls -ld $ORIGIN/../../../../../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib                          
drwxr-xr-x 2 buck buck 20480 May  6 12:00 /home/buck/scratch/rust/null/target/debug/../../../../../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib
```

### Fixing it:

I believe you'll find in the implementation that ORIGIN is assumed to be the file's path, when actually it's the file's *directory* path.

**Comment by rinon** [comment] 2018-11-08 21:18
This looks like a duplicate of https://github.com/rust-lang/rust/issues/48102

**Comment by ehuss** [comment] 2023-09-26 20:39
Indeed, closing as a duplicate of https://github.com/rust-lang/cargo/issues/12746.

**Closed by ehuss** 2023-09-26 20:39 UTC
Labels: T-cargo, C-bug
