### ISSUE TITLE
rustc broken pipe panic when I piped a wrong command

### ISSUE THREAD

**Issue by lilianmoraru** [rust-lang/rust#30972] opened 2016-01-17 08:43 UTC
I was trying to get the version of the rust compiler I have:
```sh
rustc -V | cut -d '\(' -f 2 | cut -d ' ' -f 1
```
The issue is obviously in **`\(`** (was thinking regex) which should be swapped with **`(`**.
And yes, it's a "broken pipe" but I've never seen an application react like this to a wrong command being piped(And it's not rustc who receives something from the pipe, it's another application).
```
cut: the delimiter must be a single character
Try 'cut --help' for more information.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
```

**Comment by alexcrichton** [comment] 2016-01-17 19:15
I believe this is a dupe of https://github.com/rust-lang/rust/issues/14505, so closing in favor of that, but thanks for the report!

**Closed by alexcrichton** 2016-01-17 19:15 UTC
