### ISSUE TITLE
regression: ICE -- bad ConstKind after monomorphizing

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#94502] opened 2022-03-01 22:52 UTC
[Crater](https://github.com/rust-lang/rust/issues/94345) picked up this issue in a number of crates:

May be a duplicate of https://github.com/rust-lang/rust/issues/93002, but filing this as a dedicated bug with a rough list of affected crates in Crater.

* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/mpancia.aoc2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/gytis-ivaskevicius.ion-shell/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/redox-os.ion/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/AestheticIntegration.batsmt/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/BenF-B.Titan/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/DataTriny.Fortuna/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/Furetur.jex_vm/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/Kilerd.leetcode-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/SSebigo.iris-classification/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/SolarLiner.minigc.rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/TheArtistGuy.advent_of_code_2021/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/ajfrantz.advent2018/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/alexmailo.stack/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/andersmartini.workis/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/arnasjozonis.lz78/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/b4skyx.logchain/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/bantic.cryptopals/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/baoziv587.LoxLang/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/bitonic.puzzlescript-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/byronwasti.advent-of-code-2019/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/cameron-williams.zkru/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/carribus.rust_commander/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/catunlock.numbers-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/christian-blades-cb.aoc-2015/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/compenguy.rtf2text/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/curiousbirds.mint/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/davidsullins.AdventOfRust2018/log.txt 
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/dcheatha.graph-sketchpad/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/deaz.adventofcode-2018/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/garnish-lang.garnish-core/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/guilgaly.advent-of-code-2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/hsmtkk.super-duper-octo-potato/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/janglada.yahtzee_upper/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/jcrowgey.aoc_2018/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/jfrikker.minebot/log.txt
* (and more, not listing all of them here; we will rerun crater to confirm all are fixed.)

ty::ConstKind::Error constructed but no error reported (we should check, may be a distinct bug; maybe https://github.com/rust-lang/rust/issues/94506):

* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/MatsDK.CLI_File_Explorer/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/Qvist30.AocRust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/Rickgg.me_myself/log.txt

```
[INFO] [stdout] error: internal compiler error: /rustc/0a4f984a87c7ba6c74ec3e78442fec955a419e32/compiler/rustc_codegen_ssa/src/mir/constant.rs:42:20: encountered bad ConstKind after monomorphizing: Error(DelaySpanBugEmitted(()))
[INFO] [stdout]   --> parse/src/day02.rs:21:73
[INFO] [stdout]    |
[INFO] [stdout] 21 |     let char_count = count_dict.get(&password_rule.character).unwrap_or(&0);
[INFO] [stdout]    |                                                                         ^^
[INFO] [stdout] 
```

**Comment by b-naber** [comment] 2022-03-02 12:46
> cc @b-naber @lcnr does this ring a bell wrt recent const representation changes in MIR?

Does a crater run use nightly? 

None of the changes we made are in nightly right now. Only one PR was merged, but that was later reverted.

**Comment by matthiaskrgr** [comment] 2022-03-02 20:26
Reduced a bit from https://github.com/deaz/adventofcode-2018:

````rust
use std::collections::HashMap;

pub fn f(input: &str) {
    input
        .lines()
        .map(|s| -> (u32) { (1) })
        .fold(HashMap::new(), |mut map, (x)| {
            let prev = map.get(&(0, x)).unwrap_or(&0);
            map.insert((0, x), prev + 1);
            map
        });
}

pub fn main() {
    let _ = f("");
}
````

This crashes on beta but not on stable or nightly.

**Comment by lcnr** [comment] 2022-03-03 10:18
minimalized
```rust
struct Repro;
impl Repro {
    fn get(&self) -> &i32 {
        &3
    }

    fn insert(&mut self, _: i32) {}
}

fn main() {
    let x = &0;
    let mut conflict = Repro;
    let prev = conflict.get();
    conflict.insert(*prev + *x);
}
```
the issue is that `body.tainted_by_errors` is also set when only emitting a lint

**Comment by eddyb** [comment] 2022-03-03 10:54
Sounds like this comment might be relevant: https://github.com/rust-lang/rust/pull/93368#issuecomment-1048487073 - i.e. that PR ended up doing a drive-by fix because conflating errors and warnings became a type mismatch at the `DiagnosticBuilder` level.

So you can probably confirm that nightly was broken between #93691 landing (`nightly-2022-02-13`?) and #93368 landing (`nightly-2022-02-26`?), and I guess beta branched between the two?

**Comment by pietroalbini** [comment] 2022-04-01 15:50
Should be fixed by https://github.com/rust-lang/rust/pull/94552.

**Closed by pietroalbini** 2022-04-01 15:50 UTC
Labels: I-ICE, T-compiler, regression-from-stable-to-beta, I-prioritize
