### ISSUE TITLE
TAIT: type parameter `impl FnOnce()` is part of concrete type but not used in parameter list for the `impl Trait` type alias

### ISSUE THREAD

**Issue by Ddystopia** [rust-lang/rust#126407] opened 2024-06-13 13:13 UTC
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&code=%23%21%5Bfeature%28type_alias_impl_trait%29%5D%0A%0Afn+foo%28bar%3A+impl+FnOnce%28%29%29+%7B%0A++++type+T+%3D+impl+Sized%3B%0A++++let+x%3A+T+%3D+%7C%7C+%7B%7D%3B%0A%7D%0A%0Afn+main%28%29+%7B%7D%0A)): 

```rust
#![feature(type_alias_impl_trait)]

fn foo(bar: impl FnOnce()) {
    type T = impl Sized;
    let x: T = || {};
}

fn main() {}

```

I expected to see this happen: code compiles;

Instead, this happened: compile error

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (98489f248 2024-06-06)
binary: rustc
commit-hash: 98489f2487465f3765e5dd28d7305ebfd40f0865
commit-date: 2024-06-06
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.7
```

</p>
</details>

**Comment by Ddystopia** [comment] 2024-06-13 13:14
Here is even smaller example:
```rust
#![feature(type_alias_impl_trait)]

fn foo<T>(bar: T) {
    type T = impl Sized;
    let x: T = || {};
}

fn main() {}
```

**Comment by oli-obk** [comment] 2024-06-13 13:57
Yes, all of these don't work anymore. You need to move the TAIT out of the function for now

**Comment by traviscross** [comment] 2024-06-14 03:29
Probably adding the generic parameter is what is wanted:

```rust
#![feature(type_alias_impl_trait)]

fn foo<U>() {
    type T<V> = impl Sized;
    let x: T<U> = || (); //~ OK
}

fn main() {}
```

This is a duplicate of:

- https://github.com/rust-lang/rust/issues/65442

E.g.:

```rust
#![feature(type_alias_impl_trait)]

type Ty = impl Sized;

fn test<'v, T, const U: usize>() -> Ty {
    || ()
    //~^ ERROR type parameter `T` is part of concrete type but not
    //~|       used in parameter list for the `impl Trait` type alias
    //~^ ERROR const parameter `U` is part of concrete type but not
    //~|       used in parameter list for the `impl Trait` type alias
}

fn main() {}
```

So let's close in favor of that issue.

**Closed** 2024-06-14 03:30 UTC
Labels: T-compiler, C-bug, F-type_alias_impl_trait
