### ISSUE TITLE
[ER] Better error message for trying to open a missing file

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#91155] opened 2021-11-23 11:21 UTC
When I try to open a missing file in Rust with code like:

```rust
use std::fs::File;
fn main() {
    let _br = File::open("missing_file.txt").unwrap();
}
```

I get:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Impossibile trovare il file specificato." }', test.rs:3:46

stack backtrace:
...
```

While this Python code:

```python
f = open("missing_file.txt")
```

Gives an error message that tells me what's the file name I was trying to open:

```
Traceback (most recent call last):
  File "...\test.py", line 1, in <module>
    f = open("missing_file.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'missing_file.txt'
```

Could such information be added to the Rust error message?

**Comment by ehuss** [comment] 2021-11-23 15:10
Unfortunately this would require extra allocations which could have an effect on performance.  There is an open RFC at https://github.com/rust-lang/rfcs/pull/3084 to add this which has more detail.  Closing as a duplicate of #44938.

**Closed by ehuss** 2021-11-23 15:10 UTC
