### ISSUE TITLE
rustc build broken after #95906

### ISSUE THREAD

**Issue by klensy** [rust-lang/rust#96188] opened 2022-04-18 20:07 UTC
After #95906 (0516711ab057d9731f55511f00f9d426bc9db724), building rustc (stage0 stdlib) with `python x.py --stage=0 b` fails with
```
$ python x.py build --stage=0
Updating only changed submodules
  Submodules updated in 0.02 seconds
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.21s
thread 'main' panicked at '`should_run.paths` should correspond to real on-disk paths - use `alias` if there is no relevant path: src/llvm-project/llvm', src\bootstrap\builder.rs:391:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 0:00:01
```

The same true for perf runner: https://perf.rust-lang.org/status.html (https://perf.rust-lang.org/compare.html?start=6fd7e9010db6be7605241c39eab7c5078ee2d5bd&end=0516711ab057d9731f55511f00f9d426bc9db724)
cc @jyn514
@rustbot label +A-rustbuild

**Comment by jyn514** [comment] 2022-04-19 01:14
Thanks for catching this. The issue is that `src/llvm-project/llvm` doesn't exist if the `llvm-project` submodule isn't checked out locally. As a workaround, you can run `git submodule update --init src/llvm-project`.

I am not quite sure the right fix - I guess I could check in `Llvm::should_run` whether the submodule is checked out? But it seems confusing to have the possible paths be different based on your git state ... alternatively, I could revert the hard requirement, but then this will regress in the future.

I suppose a third alternative is to add a `ShouldRun::submodule_path` function that calls either `path` or `alias` depending on whether the submodule is checked out. But that seems a little overcomplicated.

cc @Mark-Simulacrum - happy to revert this assertion for now to unbreak things

**Comment by klensy** [comment] 2022-04-19 01:22
As consequence of that, every next perf run missing bootstrap timings.

P.S. Bootstrap timings in perf run missing, but no indication of error on the page (for example https://perf.rust-lang.org/compare.html?start=8305398d7ae6128811ec2b3223939bcd067530c2&end=311e2683e1bad87715b1558f7900e294d24ce491), except for first time (https://perf.rust-lang.org/compare.html?start=6fd7e9010db6be7605241c39eab7c5078ee2d5bd&end=0516711ab057d9731f55511f00f9d426bc9db724)

**Comment by jyn514** [comment] 2023-02-03 05:53
Fixed in https://github.com/rust-lang/rust/pull/96196

**Closed by jyn514** 2023-02-03 05:53 UTC
Labels: T-bootstrap, C-bug
