### ISSUE TITLE
`pub macro` defined in submodule is shown at the wrong path

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#74355] opened 2020-07-15 06:48 UTC
rustdoc is showing the `raw_mut` macro at the wrong path in libcore: https://doc.rust-lang.org/nightly/core/macro.raw_mut.html says `core::raw_mut` but really it is `core::ptr::raw_mut` (and the same goes for `core::ptr::raw_const`). Looks like `pub macro` is not handled correctly?

Cc @rust-lang/rustdoc

**Comment by petrochenkov** [comment] 2020-07-15 06:52
cc https://github.com/rust-lang/rust/issues/63268

**Comment by GuillaumeGomez** [comment] 2020-07-15 08:23
When a macro is marked as reexported, you can use it directly from the "top", so in this regard, isn't it the expected behavior?

**Comment by RalfJung** [comment] 2020-07-15 09:09
AFAIK that is not true for `macro` macros, just for `macro_rules!` macros.

**Comment by RalfJung** [comment] 2020-07-15 09:10
Note that there is no `#[macro_export]` here. This macro is exported via `pub`.

**Comment by RalfJung** [comment] 2020-07-15 09:15
Code example:
```rust
#![feature(raw_ref_macros)]

fn main() {
    let mut x = 5;
    // This works.
    let xptr = core::ptr::raw_const!(x);
    // This does not.
    let xptr = core::raw_const!(x);
}
```
So I think there is definitely a rustdoc bug here. The path it shows does not work.

**Comment by GuillaumeGomez** [comment] 2020-07-15 09:19
Oh I see. Indeed, it's a bug.

**Comment by yoshuawuyts** [comment] 2020-07-15 12:14
Not sure if helpful, but the way we got public exports to work in rustdoc in `async-std` was by creating a separate crate (`async-macros`), and then re-exporting from from the main crate. This enabled us to render [`async_std::task::ready!`](https://docs.rs/async-std/1.6.2/async_std/task/macro.ready.html) renders in rustdoc.

This issue will also affect the upcoming [`core::task::ready!`](https://github.com/rust-lang/rust/pull/70817) PR.

**Comment by RalfJung** [comment] 2020-07-27 12:58
@GuillaumeGomez how hard is it to fix this problem, and what does the rustdoc team's prioritization for this look like? We'd like to stabilize https://github.com/rust-lang/rust/issues/73394, and I am not sure if we want to stabilize this while its docs are rendered incorrectly.

**Comment by GuillaumeGomez** [comment] 2020-07-27 17:58
Sorry but no idea. I don't have much time lately so maybe someone else from the @rust-lang/rustdoc will give it a try? Otherwise I'll try to fix it as soon as I have time.

**Comment by Manishearth** [comment] 2020-07-27 19:08
Yeah so the problem here is that we have TypeKind::Macro which forces all macros to live at the root.

Given a Def or a Res, how do I tell if a macro is MBE or a newstyle macro?


(There's a possibility that our current code actually handles this correctly already and we need to remove the special case for TypeKind::Macro)

**Comment by Manishearth** [comment] 2020-07-28 03:41
Okay so here are the two offending bits of code:

https://github.com/rust-lang/rust/blob/ac48e62db85e6db4bbe026490381ab205f4a614d/src/librustdoc/visit_ast.rs#L75-L77

https://github.com/rust-lang/rust/blob/ac48e62db85e6db4bbe026490381ab205f4a614d/src/librustdoc/clean/inline.rs#L175-L179

The latter is more about linking to these items rather than rendering them.

So the problem is that by the time stuff gets to rustdoc, we're looking at the HIR and the two kinds of macros are squashed together on [`hir::Crate::exported_macros`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/struct.Crate.html#structfield.exported_macros). The newstyle macros are not a variant of `hir::Item` at all, they disappear from the HIR tree at that point and only exist as an array on the crate.

It would be nice if MBEs stayed on `krate` and newstyle macros were actually Items or at least stored separately on the module. We could handle these as we see their containing module, but that seems prone to issues when there are reexports and private modules in the mix.

**Comment by Manishearth** [comment] 2020-07-28 03:57
An option to do this purely in rustdoc would be to check the `def_path` and insert it in the appropriate modules after the fact, however this is kinda icky and i don't think this will be the last tooling problem encountered by newstyle macros living at the crate root in HIR.

**Comment by RalfJung** [comment] 2020-07-28 06:39
@petrochenkov will probably know best how to interpret this information; somenow macro name resolution also has to work with this, after all.

**Comment by Manishearth** [comment] 2020-07-28 06:42
I don't think name resolution actually operates on the hir that way.

**Comment by jyn514** [comment] 2020-09-29 21:07
> The newstyle macros are not a variant of hir::Item at all, they disappear from the HIR tree at that point and only exist as an array on the crate.

I think you can recover the module they came from using the [`HirId`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/struct.MacroDef.html#structfield.hir_id) and calling [`parent_module`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html?search=#method.parent_module) on it.

**Comment by jyn514** [comment] 2020-09-29 21:12
You can tell whether it's a `macro_rules` macro or a `pub macro` by looking at [`MacroDef.macro_rules`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/struct.MacroDef.html#structfield.macro_rules).

**Closed** 2021-01-10 08:01 UTC
Labels: A-macros, A-macros-2.0, C-bug, T-rustdoc
