### ISSUE TITLE
overflow evaluating the requirement `<[Test<'a>] as std::borrow::ToOwned>::Owned`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#67197] opened 2019-12-10 14:00 UTC
This code does not compile:

```rust
use std::borrow::Cow;

enum Test <'a> {
    Int(u8),
    Bytes(Cow<'a, [u8]>),
    Array(Cow<'a, [Test<'a>]>),
}
```

I would expect it to be the same as this code, which does compile:

```rust
use std::borrow::Cow;

enum Test <'a> {
    Int(u8),
    Bytes(Cow<'a, [u8]>),
    Array(VecOrSlice<'a>),
}

enum VecOrSlice<'a> {
    Vec(Vec<Test<'a>>),
    Slice(&'a [Test<'a>]),
}
```

I am not sure if this is a reasonable expectation or not, though.

**Comment by jonas-schievink** [comment] 2019-12-10 14:49
Duplicate of https://github.com/rust-lang/rust/issues/23714

**Closed by jonas-schievink** 2019-12-10 14:49 UTC

**Comment by Arnavion** [comment] 2019-12-30 21:33
This is more closely related to https://github.com/rust-lang/rust/issues/38962 and https://github.com/rust-lang/rust/issues/47032 than https://github.com/rust-lang/rust/issues/23714 , since https://github.com/rust-lang/rust/issues/23714 is doing shenanigans with a custom `ToOwned` impl that breaks for a different reason.
