### ISSUE TITLE
Where clause in GAT must be repeated in function definition

### ISSUE THREAD

**Issue by Cassy343** [rust-lang/rust#74798] opened 2020-07-26 23:33 UTC
Code:

```rust
#![allow(incomplete_features)]
#![feature(generic_associated_types)]

/* Setup traits */

trait Gen<T> {
    fn gen(&self) -> T;
}

trait ItemHolder {
    type Item;

    fn item(&self) -> &Self::Item;
}

/* Trait with the GAT */

trait Trait {
    type ItemHolder: ItemHolder where <Self::ItemHolder as ItemHolder>::Item: Gen<u32>;

    fn item_holder(&self) -> Self::ItemHolder;
}

/* Usage of `Trait` */

// This function compiles
fn ok<T: Trait>(trait_impl: &T) -> u32
where
    <<T as Trait>::ItemHolder as ItemHolder>::Item: Gen<u32>
{
    let x = trait_impl.item_holder();
    let x = x.item();
    Gen::<u32>::gen(x)
}

// This function does not
fn error<T: Trait>(trait_impl: &T) -> u32 {
    let x = trait_impl.item_holder();
    let x = x.item();

    // Error: the trait `Gen<u32>` is not implemented for `<<T as Trait>::ItemHolder as ItemHolder>::Item`
    Gen::<u32>::gen(x)
}
```

I would expect that the repetition of the bound would not be required as it is stated verbatim in the where clause of the GAT. The following is the error the compiler gives in full:

```
error[E0277]: the trait bound `<<T as Trait>::ItemHolder as ItemHolder>::Item: Gen<u32>` is not satisfied
  --> src/main.rs:31:21
   |
17 |     fn gen(&self) -> T;
   |     ------------------- required by `Gen::gen`
...
31 |     Gen::<u32>::gen(x)
   |                     ^ the trait `Gen<u32>` is not implemented for `<<T as Trait>::ItemHolder as ItemHolder>::Item`
   |
help: consider further restricting the associated type
   |
26 | fn error<T: Trait>(trait_impl: &T) -> u32 where <<T as Trait>::ItemHolder as ItemHolder>::Item: Gen<u32> {
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
binary: rustc
commit-hash: 346aec9b02f3c74f3fce97fd6bda24709d220e49
commit-date: 2020-07-11
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

**Comment by cuviper** [comment] 2020-07-27 17:48
This seems like it might be a variation of #20671, regardless of GAT.

**Comment by nikomatsakis** [comment] 2021-02-02 21:39
I believe the code is working as intended. This is a bit subtle. See the following table:

| Syntax | who proves it | who can assume it |
| --- | --- | --- |
| `type Foo: Bar = X` | the impl | generic code using `T::Foo` |
| `type Foo<A: Bar> = X` | generic code using `T::Foo<U>`, which must prove that `U: Bar` | the impl, when proving the type `X` is WF |
| `type Foo<A> = X where A: Bar` | generic code using `T::Foo<U>`, which must prove that `U: Bar` | the impl, when proving the type `X` is WF |

In particular, the where clause here is not acting the way the OP suggests. It is acting as something which must be proven in order to do `X::ItemHolder`.

Closing.

**Comment by nikomatsakis** [comment] 2021-02-02 21:40
Re-opening in case I'm missing something. We'll revisit the issue in a later triage pass!

**Comment by nikomatsakis** [comment] 2021-02-16 10:49
Closing, I still think this is "not a bug"

**Closed by nikomatsakis** 2021-02-16 10:49 UTC
Labels: C-bug, F-generic_associated_types, requires-nightly
