### ISSUE TITLE
Compiler should check signatures of lang item functions

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#47421] opened 2018-01-14 01:11 UTC
The `panic_fmt` lang item in particular has changed in recent memory (adding column information) and is being defined in basically every no_std binary, so there's a lot of potential for wrong/outdated definitions there. Those could easily cause very bad behavior, so we should check its signature like we check the signatures of declared intrinsics.

**Comment by ollie27** [comment] 2018-01-14 02:22
dupe of #9307

**Closed** 2018-01-14 02:53 UTC
