### ISSUE TITLE
Box::from(&str) -> Box<Error> regression

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#30634] opened 2015-12-30 11:20 UTC
The following code compiles fine on the stable channel but fails on the beta and nigthly channels:

    fn test() -> Box<std::error::Error> { Box::from("test") }
    fn main() { test(); }

The error message is:

    error: the trait `std::error::Error` is not implemented for the type `&str`

**Comment by bluss** [comment] 2015-12-30 13:18
cc @brson 

If the result type is `Box<Error + Send + Sync>` instead, it continues to compile. I'm not immediately sure why.

**Comment by bluss** [comment] 2015-12-30 13:37
Is  #29580 related?

**Comment by diwic** [comment] 2015-12-31 13:13
Side note - I discovered this when running `cargo test` on my dbus crate, as now [one of the examples](https://github.com/diwic/dbus-rs/blob/master/examples/rtkit.rs) fails to build. If the crater is run on all crates on crates.io and it includes a `cargo test`, this would have been discovered by crater as a root regression?

**Comment by brson** [comment] 2016-01-06 03:07
This has bit me. Crater had to be modified to not try to box strings as errors.

**Comment by aturon** [comment] 2016-01-06 21:25
@bluss That suggests that there's some bad interplay between the coercion that would throw away the extra constraints and the dispatch for `From` (which is indeed tied to `Box<Error + Send + Sync + 'a>`). Not sure why it was working before, honestly.

**Comment by brson** [comment] 2016-01-06 21:54
I'll try to bisect.

**Comment by brson** [comment] 2016-01-08 19:43
> If the crater is run on all crates on crates.io and it includes a cargo test, this would have been discovered by crater as a root regression?

Yes.

**Comment by brson** [comment] 2016-01-08 19:57
So this is working as intended, right? @bluss why doesn't one need to write the type with the lifetime in `Box<Error + Send + Sync + 'static>`? Is `'static` the default?

**Comment by bluss** [comment] 2016-01-08 23:26
Yep, `'static` is the default with `Box`. For `&'a Trait` it's `&'a (Trait + 'a)` instead.

**Comment by brson** [comment] 2016-01-11 19:25
I started bisecting last week to find the patch that made this change, but it's slow going.

**Comment by diwic** [comment] 2016-01-19 12:44
Might be solved by https://github.com/rust-lang/rust/pull/30509 ?

**Comment by bluss** [comment] 2016-01-19 12:55
Yes, it compiles on nightly now. The regression to beta still remains.

**Comment by brson** [comment] 2016-02-11 22:50
This has been ported to beta. Closing.

**Closed by brson** 2016-02-11 22:50 UTC
Labels: regression-from-stable-to-beta
