### ISSUE TITLE
Confusing move behavior

### ISSUE THREAD

**Issue by zonyitoo** [rust-lang/rust#27656] opened 2015-08-11 02:24 UTC
```rust
struct Foo {
    bar: u32,
}

fn main() {
    let mut foo = Foo { bar: 10 };
    let foo2 = foo; // <-- moved here
    
    foo.bar = 20; // <-- but still works!
    
    println!("{}", foo.bar); // <- failed because `foo` has been moved
}
```

**Comment by sfackler** [comment] 2015-08-11 02:39
This looks like a duplicate of #21232.

**Comment by Aatch** [comment] 2015-08-11 02:43
Agreed. Closing as duplicate of #21232

**Closed by Aatch** 2015-08-11 02:43 UTC
