### ISSUE TITLE
A `rustc` compiled from the `rust-*-src` tarballs can't be used with the `std` binaries from s.r-l.o/dist

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#33286] opened 2016-04-30 02:52 UTC
Originally reported [here](https://www.reddit.com/r/rust/comments/4h2ir3/the_crate_std_has_been_compiled_with_rustc_180/)

In the reported case the `rust` package provided by Arch Linux was compiled from [the `rustc-1.8.0-src.tar.gz` tarball](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rust#n14). Thus their `rustc` binary doesn't have a git commit hash encoded in it:

```
$ rustc -V
rust-1.8.0
```

And if you try to use this `rustc` to cross compile using the `std` binaries from [s.r-l.o](https://static.rust-lang.org/dist/) you get the following error:

```
$ cargo build --target=i686-pc-windows-gnu`
error: the crate `std` has been compiled with rustc 1.8.0 (db2939409 2016-04-11), which is incompatible with this version of rustc [E0514]
```

At the center of this issue is [this check](https://github.com/rust-lang/rust/blob/db2939409db26ab4904372c82492cd3488e4c44e/src/librustc_metadata/creader.rs#L261), this [rustc_version](https://github.com/rust-lang/rust/blob/db2939409db26ab4904372c82492cd3488e4c44e/src/librustc_metadata/common.rs#L245-L250) function and this [CFG_VERSION](https://github.com/rust-lang/rust/blob/master/mk/main.mk#L85) env variable which is set by the build system.

In the case of the `std` crate since it was compiled from a git checkout the value returned by `rustc_version` is `1.8.0 ($SOME_HASH $SOME_DATE)` whereas the same function just returns `1.8.0` in the case of a `rustc` that was compiled from a source tarball. The mismatch between these two strings is what causes the error reported above. But the error message is wrong because both binaries where compiled from the exact same source code and can be used together.

How to fix this? Possible solutions:
- Ask package maintaners to always build from a git checkout. This way the "rustc_version" string always contains a git commit hash.
- Tweak our build system so that building from a git checkout and from a source tarball yield the same "rustc_version" string. Two possible implementations:
  - Drop the commit hash/date part from the "rustc_version" string. This may be OK for the stable and beta channels because you can tell them apart from looking at the version number (e.g. 1.7.0 vs 1.8.0) but that's not the case for nightlies -- two consecutive nightlies would have the same version number (e.g. 1.10.0-nightly).
  - Include the commit hash part in the `rustc-*-src.tar.gz` tarballs, perhaps as a `.commit-hash` file and tweak the build system to use the contents of this file in the "rustc_version" string when one is not building from a git checkout.

Thoughts? @alexcrichton @brson

**Comment by brson** [comment] 2016-04-30 03:17
I've never considered that it *should* be possible to mix binaries from compilers of different origin - our metadata situation used to be so screwed up that I just assumed it wouldn't be, and I suspect we intentionally made it impossible at some point in the past.

I don't know if even today it's possible. I would assume that e.g. changing cfg values will invalidate the metadata, though perhaps we embed and validate cfg compatibility by now.

**Comment by brson** [comment] 2016-04-30 03:20
After considering it further, I don't see why this shouldn't be possible. This case wouldn't be mixing crates produced by different compilers. It's just reading a complete collection of crates produced by a different compiler.

**Comment by brson** [comment] 2016-04-30 03:23
There may still be some conditional values embedded in the compiler that could influence crate behavior.

Use of unstable features could be one, but that is mostly determined by the version number.

> Include the commit hash part in the rustc-*-src.tar.gz tarballs, perhaps as a .commit-hash file and tweak the build system to use the contents of this file in the "rustc_version" string when one is not building from a git checkout.

Something like this I think.

**Comment by arielb1** [comment] 2016-04-30 08:56
@brson

The original problem is that the metadata format occasionally changes *between* nightlies, so that `rustc 1.8.0` must not read the metadata created by `rustc 1.8.0 (777777777) 2015-01-01`.

**Comment by arielb1** [comment] 2016-04-30 08:59
I think we should just compare the commit hash - that means storing it in the tarball.

**Comment by Mark-Simulacrum** [comment] 2017-05-03 21:26
So this is a duplicate of #31393 (which I've closed in favor of this), but the conclusion reached there appears to be incorrect to me.

> The [currently checked string] originates from [`CFG_VERSION`], but we should be using [`CFG_VER_HASH`].

@alexcrichton noted in #31393 that if we only check git commits it'll suffice for "these should link together." However, that won't work for this issue's case since there is no commit hash for the version, as far as I can tell. I'm not sure what the right steps are in that case, so not marking as E-easy for the time being. @alexcrichton Any thoughts on this? Could you propose a solution?

[currently checked string]: https://github.com/rust-lang/rust/blob/8fc73c703ab175577346773ad93de3aa2c3f44a2/src/librustc_metadata/creader.rs#L260
[`CFG_VERSION`]: https://github.com/rust-lang/rust/blob/8fc73c703ab175577346773ad93de3aa2c3f44a2/src/librustc_metadata/common.rs#L246-L249
[`CFG_VER_HASH`]: https://github.com/rust-lang/rust/blob/8fc73c703ab175577346773ad93de3aa2c3f44a2/src/librustc_driver/lib.rs#L532-L535

**Comment by alexcrichton** [comment] 2017-05-04 03:54
I believe it boils down to [these lines of code](https://github.com/rust-lang/rust/blob/b16c7a235fa0f57fed6b7ec13ffd3cff1bcdd9ad/src/bootstrap/compile.rs#L479-L488) in the build system right now. They don't work (return `None`) when built from a tarball, and we need them to operate the same in and out of a tarball.

As to how to do that, I'd be fine with just generating some file during the creation of the source tarball.

**Comment by steveklabnik** [comment] 2018-10-31 20:04
Triage: the code is now here: https://github.com/rust-lang/rust/blob/master/src/bootstrap/tool.rs#L244-L253

**Comment by pwnorbitals** [comment] 2020-11-14 16:45
Do we have any progress on this issue ? Doesn't seem to be much activity

**Comment by Zapeth** [comment] 2021-04-20 14:09
Just got this error when trying to use the std binaries for the `armv7-unknown-linux-gnueabihf` target with src-compiled rustc `x86_64-pc-windows-gnu` ([mingw package](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-rust/PKGBUILD))

Is this just an issue of mismatched metadata (commit hash/date) that causes the compilation error, or is the problem deeper rooted (i.e. compilation for target necessary)?

**Comment by jyn514** [comment] 2022-06-27 04:15
I think this is just an issue of mismatched metadata; the compiler was built from the same sources, so it should be able to read libraries built by the same sources, even if they're a different physical binary.

It turns out that we already vendor the version hash when creating the `rustc-src` component: https://github.com/rust-lang/rust/blob/d50583eaecdf88b5ee59e1d77fe3b4a8d87cbe6e/src/bootstrap/dist.rs#L882

Mentoring instructions: In https://github.com/rust-lang/rust/blob/85c87f6c67f966e7b4fd292217c6db41fce88e0d/src/bootstrap/lib.rs#L1335, check if `self.rust_info.is_git().is_none()`. If so, manually add the git commit from `git-commit-hash`. It's ok to panic if that file isn't present; the only supported way to build without git sources is through the vendored source tarball.

@rustbot label +E-mentor +E-easy

**Closed** 2022-10-02 23:47 UTC
Labels: E-easy, E-mentor, A-bootstrap, C-bug
