### ISSUE TITLE
cargo: error on building fresh project

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#22822] opened 2015-02-26 01:17 UTC
I create a new project using `cargo new hello_world --bin`, and then run `cargo build -v`, but get the following error.

```
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: crate name cannot start with a hyphen: -
error: aborting due to previous error
```

This error just started appearing since I updated to the latest nightly.

Incidentally, there seems to be no different to the `Cargo.toml` file or directory structure or indeed `main.rs` file, regardless of whether I specify the `--bin` option or not to `cargo new`. Is this right?

**Comment by dguo** [comment] 2015-02-26 01:58
See https://github.com/rust-lang/cargo/issues/1342

**Comment by alexreg** [comment] 2015-02-26 02:02
Ah okay, so it should be fixed in the next nightly?

Any idea about the second issue (re `—bin`), incidentally?

**Comment by dguo** [comment] 2015-02-26 02:18
Yes, I assume the fix will be in the next nightly.

There should be a difference. Specifically, leaving off `--bin` should give you a `.gitignore` with `Cargo.lock` in it. See https://github.com/rust-lang/cargo/issues/315

In `src`, you should also have a `lib.rs` file with a test function instead of `main.rs` with main.

Maybe double check to make sure you aren't specifying `--bin`? I just tried again, and it works fine for me. I am also on the latest nightly.

**Comment by alexreg** [comment] 2015-02-26 02:20
Thanks for confirming.

And yes, my bad; I must have been too hasty in checking the `src/` dirs here.

**Comment by alexcrichton** [comment] 2015-02-26 08:23
Closing as a duplicate of https://github.com/rust-lang/cargo/issues/1342 (this should be fixed in the next nightly)

**Closed by alexcrichton** 2015-02-26 08:23 UTC
