### ISSUE TITLE
Building the rust code in librsvg 2.42.3 fails with rust compiler panic on powerpc-linux-unknown-gnu

### ISSUE THREAD

**Issue by sajanki** [rust-lang/rust#50288] opened 2018-04-27 17:41 UTC
When I try to build librsvg 2.42.3 on powerpc-linux-unknown-gnu (my unofficial port of Slackware Linux) I get a trace.

I expected the build to be successful but rustc appears to crash during the build process causing the build to fail. This looks like a problem with the rust compiler on 32-bit big-endian ppc targets.

Backtrace:

Live child 0x10405cf0 (/tmp/build/librsvg-2.42.3/target/release/librsvg_internals.a) PID 25687 
Need a job token; we have children
Live child 0x10405cf0 (/tmp/build/librsvg-2.42.3/target/release/librsvg_internals.a) PID 25687 
   Compiling libc v0.2.36
thread 'rustc' panicked at 'unexpected getrandom error: Invalid argument (os error 22)', /cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.2/src/os.rs:130:21
stack backtrace:
   0:   0x33c223 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb3a58eaff737b110
                       at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:   0x2fc2b3 - std::sys_common::backtrace::print::hb71ae1aa3b7afa21
                       at libstd/sys_common/backtrace.rs:71
                       at libstd/sys_common/backtrace.rs:59
   2:   0x322453 - std::panicking::default_hook::{{closure}}::h56d96e643c7b50f5
                       at libstd/panicking.rs:207
   3:   0x322127 - std::panicking::default_hook::hb9c821975771e728
                       at libstd/panicking.rs:223
   4:   0x31f53b - core::ops::function::Fn::call::he9b119d883710ae5
                       at /checkout/src/libcore/ops/function.rs:73
   5: 0xf610c1db - core::ops::function::Fn::call::h34e4f804d6924b1f
   6:   0x322d43 - std::panicking::rust_panic_with_hook::h5d34088f4977ec54
                       at libstd/panicking.rs:403
   7:   0x322a8b - std::panicking::begin_panic_fmt::h938d0b34a89a4ee2
                       at libstd/panicking.rs:349
   8: 0xf533fc3b - rand::os::imp::getrandom_fill_bytes::hf1399d2ae0fa6448
   9: 0xf533d48f - <rand::prng::isaac::IsaacRng as rand::Rand>::rand::h70826ebfa4b0a2c6
  10: 0xf533d9ef - rand::StdRng::new::h0d7a19e31210fa1e
  11: 0xf533e2f7 - rand::thread_rng::THREAD_RNG_KEY::__init::hb5c157ec7e7cf832
  12: 0xf533f73b - <std::thread::local::LocalKey<T>>::with::h05abd8de02ff26c5
  13: 0xf533e00f - rand::thread_rng::hd51d81d733885406
  14: 0xf0cdd68f - tempdir::TempDir::new::hf2ce294195c1e22b
  15: 0xf0b8303b - rustc_trans::back::link::link_binary::h8e42441f01644f4c
  16: 0xf0cc3c67 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::join_trans_and_link::{{closure}}::h19bedb8e12704e91
  17: 0xf0cb95db - rustc::util::common::time::haf53181b9485c23f
  18: 0xf0b762cf - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::join_trans_and_link::h8b68bb63758d357e
  19:   0x4c4c1b - rustc_driver::driver::compile_input::hac41cf70071113a3
  20:   0x58bcc3 - rustc_driver::run_compiler_impl::h0a76bdb64dc5f186
  21:   0x49c8d3 - syntax::with_globals::hf2c0cc5a677b63f7
  22:   0x4e25df - std::sys_common::backtrace::__rust_begin_short_backtrace::h5cf029d260e6d182
  23:   0x5aa1d7 - std::panicking::try::do_call::h0f6a3894848aec8a
  24:   0x356173 - __rust_maybe_catch_panic
                       at libpanic_unwind/lib.rs:102
  25:   0x4f0223 - <F as alloc::boxed::FnBox<A>>::call_box::hb68972c8e72b2afe
  26:   0x348a6f - std::sys_common::thread::start_thread::h98ff28575cf99248
                       at /checkout/src/liballoc/boxed.rs:794
                       at libstd/sys_common/thread.rs:24
  27:   0x34ee8f - std::sys::unix::thread::Thread::new::thread_start::hea2c78355cd038d6
                       at libstd/sys/unix/thread.rs:90
  28: 0xf5237403 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-beta.1 (18aaa1d2c 2018-04-03) running on powerpc-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

Obtained token for child 0x103f9580 (librsvg/librsvg-enum-types.h).
error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...

[build.log](https://github.com/rust-lang/rust/files/1956067/build.log)

root@darkstar:~# rustc --version --verbose
rustc 1.26.0-beta.1 (18aaa1d2c 2018-04-03)
binary: rustc
commit-hash: 18aaa1d2cd03b61567969a97d062b1407f07d9c9
commit-date: 2018-04-03
host: powerpc-unknown-linux-gnu
release: 1.26.0-beta.1
LLVM version: 6.0

I am willing to help out to fix rust for 32-bit big-endian powerpc targets on linux and maybe other operating systems such as freebsd/openbsd but I am new to rustc, so that may take a while.

**Comment by glaubitz** [comment] 2018-06-04 10:54
Rust on powerpc is currently broken, see #50960.

**Comment by pietroalbini** [comment] 2018-06-04 15:31
Duplicate of #50960

**Closed by pietroalbini** 2018-06-04 15:31 UTC
Labels: I-ICE, O-PowerPC
