### ISSUE TITLE
Matching a reference and making the resulting value mutable in one step

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#45708] opened 2017-11-02 01:36 UTC
It should be possible to match a reference and make the resulting value mutable in one step.
But this doesn't work:
```rust
println!("{:?}", { let v = [1, 2, 3]; v.iter().map(|&(mut x)| { x += 1; x }).collect::<Vec<_>>() } );
```
```
error: expected one of `,` or `@`, found `)`
 --> src/main.rs:2:64
  |
2 |     println!("{:?}", { let v = [1, 2, 3]; v.iter().map(|&(mut x)| { x += 1; x }).collect::<Vec<_>>() } );
  |  
```
https://play.rust-lang.org/?gist=f76143789ed3a6a4fef1d950580f7904&version=stable

It only works like this:
```rust
println!("{:?}", { let v = [1, 2, 3]; v.iter().map(|&x| { let mut x = x; x += 1; x }).collect::<Vec<_>>() } );
```
which is very verbose. It should also be possible with `&(mut x)` (or `mut &x`).

**Comment by cuviper** [comment] 2017-11-02 19:55
I think this is not directly an issue with references, but with `()`-grouping in patterns at all.  You also can't write something like `.map(|(x)| x + 1)`, but it's fine in type positions like `fn zero() -> (i32) { 0 }`.

References do give a strong motivation for this though, to distinguish `&(mut x)` from `&mut x`.

**Comment by Spoonbender** [comment] 2022-03-22 07:19
Triage: resolved.

The example compiles and works as intended on rust 1.59.0, [see here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0b055ed828fd1d9b9e068509dbb2fbff)

I think we can close this one.

**Comment by cuviper** [comment] 2022-03-22 20:42
Yes, that should be `pattern_parentheses` (#51087) which stabilized in 1.31 (#54497).

**Closed by cuviper** 2022-03-22 20:42 UTC
Labels: C-enhancement, T-lang
