### ISSUE TITLE
Can't call methods from re-exported traits

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#18296] opened 2014-10-24 22:51 UTC
Code of this form used to work, and this still compiles if I remove the call to `f`.

```rust
use foo::Trait;

mod foo {
    pub use self::bar::Trait;

    mod bar {
        pub trait Trait {
            fn f(self);
        }
    }
}

struct S;

impl Trait for S {
    fn f(self) { }
}

fn main() {
    S.f();
}
```

rustc 0.13.0-dev (a10917a6a 2014-10-24 17:32:04 +0000)

**Comment by arielb1** [comment] 2015-06-29 17:06
This gives a privacy error now. Not sure this is a bug.

**Comment by Ryman** [comment] 2015-07-29 00:38
Just noticed this is dupe of #18241?

**Comment by huonw** [comment] 2015-10-20 04:16
Looks like it! Closing as a dupe.

**Closed by huonw** 2015-10-20 04:16 UTC
Labels: A-resolve, A-traits
