### ISSUE TITLE
note: the compiler unexpectedly panicked. this is a bug.

### ISSUE THREAD

**Issue by AxHakan** [rust-lang/rust#92871] opened 2022-01-13 22:53 UTC
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `wasmer-compiler-cranelift`
warning: build failed, waiting for other jobs to finish...
error: build failed

### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by CryZe** [comment] 2022-01-14 12:12
This is a duplicate of https://github.com/rust-lang/rust/issues/92755

**Comment by ehuss** [comment] 2022-01-14 16:08
Closing as a duplicate of #92755.

**Closed by ehuss** 2022-01-14 16:08 UTC
Labels: I-ICE, T-compiler, C-bug
