### ISSUE TITLE
Regression in binary_search_by

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#85773] opened 2021-05-28 05:45 UTC
I don't see an issue for this.

The behavior of binary_search_by changed in https://github.com/rust-lang/rust/pull/74024 such that the result of the function after the patch is not the same as before.

While not directly responsible for the downtime, Polkadot ran into this problem while trying to recover from a network failure this week: https://polkadot.network/a-polkadot-postmortem-24-05-2021/

**Comment by slurps-mad-rips** [comment] 2021-05-28 06:07
How is this a regression? The documentation for `binary_search_by` *clearly* states

>  If there are multiple matches, then any one of the matches could be returned.

**Comment by workingjubilee** [comment] 2021-05-28 08:08
It being valid for a binary search to return any element is a sufficiently well-known property of the underlying algorithm that [even Wikipedia mentions it](https://en.wikipedia.org/wiki/Binary_search_algorithm#Duplicate_elements).

And from there we can find that C's [bsearch](https://pubs.opengroup.org/onlinepubs/9699919799/functions/bsearch.html) does not specify which element should be returned.
[java.util.Array.binarySearch](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/util/Arrays.html#binarySearch(java.lang.Object%5B%5D,java.lang.Object)) also does not specify.
C#'s [List<T>.BinarySearch](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.binarysearch?view=net-5.0) also does not specify.

Indeed, the cases where binary search methods do specify which value they would return are cases where the underlying algorithm is not required to be a binary search or when it returns the qualifying range.

**Comment by eddyb** [comment] 2021-05-28 10:38
> The behavior of `binary_search_by` changed in #74024 such that the result of the function after the patch is not the same as before.

We make behavioral changes all the time, I don't understand why *anyone* is bringing "determinism" into all of this.

If you want *the exact same behavior*, you have to use *the exact same* standard library version.
We *never* guaranteed "cross-version reproducibility", except wherever documented as such (or in situations where only one behavior can be observed).

I don't want to unilaterally close this for now, but I am removing `C-bug`.

**Comment by jonas-schievink** [comment] 2021-05-28 11:43
This specific behavior has been documented since 2018. Closing since this is not a bug. If you would like to discuss whether or not to make a multi-billion dollar financial system rely on implementation details without writing a test, please do that somewhere else.

**Closed by jonas-schievink** 2021-05-28 11:43 UTC
Labels: C-discussion

**Comment by brson** [comment] 2021-05-28 17:04
Wow, the hostility in this thread is stunning.

**Comment by solson** [comment] 2021-05-28 17:13
> Wow, the hostility in this thread is stunning.

Polkadot did lie by referring to this situation as a "compiler bug" in [their tweet](https://twitter.com/Polkadot/status/1396936062266716166) on the subject. To be honest, it might be a good idea to preemptively lock this thread, before it gets any more attention.

**Comment by nikomatsakis** [comment] 2021-05-29 01:06
My two cents:

I do indeed think that it's fair to change the details of which of many equal elements gets returned in a binary search, presuming that we have left this explicitly document as not specified. (That said, I think it'd potentially be useful to specify).

However, I agree with @brson that the general tenor of this thread felt hostile. We want to *encourage* people to file bugs when they see something that surprises them, even if they're not sure whether it's a bug or not.  A more encouraging response might have been something like, "Thanks for filing the issue! However, even though the behavior changed, I don't think this is a bug. Binary search is documented as returning an arbitrary element when there are multiple equal elements, as is the case here. Therefore, I'm going to close as behaving as expected. Let me know if you think I've got this wrong."
