### ISSUE TITLE
ICE with nightly in LvalyeTy<'tcx>::protection_ty

### ISSUE THREAD

**Issue by kvark** [rust-lang/rust#31504] opened 2016-02-09 02:41 UTC
> rustc 1.8.0-nightly (9d8e3a024 2016-02-04)

It works fine with rust-beta (1.7) and rust-stable (1.6).

Repro steps:
1. git clone http://github.com/gfx-rs/gfx
2. build with rust nightly (`cargo test`), assuming you have glfw3 and X libraries installed. I'll try to narrow down the problem to a simpler case.

Backtrace:
```
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:     0x7f357580d240 - sys::backtrace::tracing::imp::write::h25e8a89f9cb373ffYpu
   2:     0x7f3575814e3b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43046
   3:     0x7f3575814991 - panicking::default_handler::h2ce1c6a1dea5f1feqOy
   4:     0x7f35757ddb7c - sys_common::unwind::begin_unwind_inner::h47b5a8e37506c94ewit
   5:     0x7f35757de608 - sys_common::unwind::begin_unwind_fmt::ha90625204f89d411Cht
   6:     0x7f357580ae81 - rust_begin_unwind
   7:     0x7f357585b85f - panicking::panic_fmt::h1e48e4114ce9cc0cqYL
   8:     0x7f357585c358 - panicking::panic::h5b116cb444de10f6XWL
   9:     0x7f3572c65dbc - mir::tcx::LvalueTy<'tcx>::projection_ty::h5714fccab20a238fMPo
  10:     0x7f3572c66280 - mir::tcx::Mir<'tcx>::lvalue_ty::ha839b7f9519d497ajXo
  11:     0x7f3573ddd64f - trans::collector::MirNeighborCollector<'a, 'tcx>.MirVisitor<'tcx>::visit_lvalue::h84f7d7046786baccdNR
  12:     0x7f3573dd9769 - trans::collector::collect_items_rec::hc8cd3c9f4c3f007fSxR
  13:     0x7f3573dd9a58 - trans::collector::collect_items_rec::hc8cd3c9f4c3f007fSxR
  14:     0x7f3573dd9a58 - trans::collector::collect_items_rec::hc8cd3c9f4c3f007fSxR
  15:     0x7f3573d0b97d - trans::base::collect_translation_items::_$u7b$$u7b$closure$u7d$$u7d$::closure.61644
  16:     0x7f3573cf7ad7 - trans::base::trans_crate::h0435b9d851cf7d4f62k
  17:     0x7f3575d48bd4 - driver::phase_4_translate_to_llvm::hdd61956c6e2890eeG0a
  18:     0x7f3575d47433 - driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::closure.28786
  19:     0x7f3575d42530 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.27816
  20:     0x7f3575d21b2d - middle::ty::context::ctxt<'tcx>::create_and_enter::h8165751750365025443
  21:     0x7f3575d1c710 - driver::phase_3_run_analysis_passes::h8165887220225805103
  22:     0x7f3575ceef7c - driver::compile_input::h1d4ebbbb69cdadccAca
  23:     0x7f3575ce068e - run_compiler::h0ff710740da72a00fGc
  24:     0x7f3575cdd9b1 - sys_common::unwind::try::try_fn::h17883797362545364498
  25:     0x7f357580ae0b - __rust_try
  26:     0x7f35758029ed - sys_common::unwind::inner_try::h4dda564fff486709yft
  27:     0x7f3575cde200 - boxed::F.FnBox<A>::call_box::h2946617711430984355
  28:     0x7f35758133f0 - sys::thread::Thread::new::thread_start::hc9003707bc709661aLx
  29:     0x7f356dfaf6a9 - start_thread
  30:     0x7f357548aeec - clone
  31:                0x0 - <unknown>
```

**Comment by nagisa** [comment] 2016-02-09 16:38
Minimal-ish example:
```rust
use std::marker::PhantomData;

pub trait DataBind {
    type Data;
}

impl<T> DataBind for Global<T> {
    type Data = T;
}

pub struct Global<T>(PhantomData<T>);

pub struct Data {
    pub offsets: <Global<[f32; 1]> as DataBind>::Data,
}

pub fn main() {
    let mut d = Data { offsets: [0.0] };
    d.offsets[0] = 0.0;
}
```

**Comment by nagisa** [comment] 2016-02-09 16:45
@nikomatsakis this might be more up your alley than mine.

**Comment by arielb1** [comment] 2016-02-09 17:11
This is because `lvalue_ty` does not normalize things. We need to pass an infcx there.

**Comment by arielb1** [comment] 2016-02-09 17:13
Actually, normalizing will ruin regions, preventing borrowck from running (no, I don't want to run region inference each time). I guess that field expressions will have to store the normalized type.

**Comment by arielb1** [comment] 2016-02-09 23:12
Nominating because regression.

**Comment by kvark** [comment] 2016-02-10 01:07
@nagisa thanks for composing the test case!

**Comment by nikomatsakis** [comment] 2016-02-10 02:02
Storing the normalized type seems reasonable to me as a first step, though @arielb1 I'd expect typeck to revalidate that.

**Comment by nikomatsakis** [comment] 2016-02-10 02:24
However, the problem that @arielb1 referred to of having to re-run region inference suggests that perhaps there *is* a reason to resurrect that old patch of mine that "extracts" regions and types rather than inferring them when doing trait matching. It would avoid the need to re-run inference, I believe. (Also, lazy normalization seems like it would help here too, of course.)

**Comment by nikomatsakis** [comment] 2016-02-11 21:12
triage: P-high

**Comment by nikomatsakis** [comment] 2016-02-11 21:12
Note that this is fixed in @arielb1's branch.

**Comment by kvark** [comment] 2016-02-16 03:18
Looks like it's fixed now, thanks!

**Comment by kvark** [comment] 2016-02-17 04:18
Actually, I can still repro this by changing our code slightly (commenting out [this](https://github.com/gfx-rs/gfx/blob/3dafc23a95a39f4902d01bb70656c860b0fb1cd2/src/render/src/macros/pso.rs#L210) and [this](https://github.com/gfx-rs/gfx/blob/3dafc23a95a39f4902d01bb70656c860b0fb1cd2/src/render/src/macros/pso.rs#L225)), reopening.

**Comment by Yoric** [comment] 2016-02-17 20:48
If this is indeed #31603, I still encounter it with latest Nightly: https://travis-ci.org/fxbox/thinkerbell/jobs/109967451

**Comment by nagisa** [comment] 2016-02-18 09:40
Fix for this didn't land yet.

**Closed** 2016-02-20 14:33 UTC
Labels: A-mir, I-ICE, P-high, regression-from-stable-to-nightly, T-compiler

**Comment by Yoric** [comment] 2016-02-23 07:59
Ok, fix confirmed: https://travis-ci.org/fxbox/thinkerbell/jobs/111150793
