### ISSUE TITLE
regression 1.51: lifetime may not live long enough with `&impl Error`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#81460] opened 2021-01-28 04:07 UTC
This compiles on stable and beta, but not nightly (1.51):

```rust
use std::error::Error;
use std::iter;

fn walk_source_chain(error: &impl Error) {
    for e in iter::successors(error.source(), |e| e.source()) {
        println!("{}", e);
    }
}
```

Error with nightly-2021-01-27:

```
error: lifetime may not live long enough
 --> src/lib.rs:5:51
  |
5 |     for e in iter::successors(error.source(), |e| e.source()) {
  |                                                -- ^^^^^^^^^^ returning this value requires that `'1` must outlive `'2`
  |                                                ||
  |                                                |return type of closure is Option<&'2 dyn std::error::Error>
  |                                                has type `&'1 &dyn std::error::Error`

error: aborting due to previous error
```

Changing the closure parameter pattern to match `&e` fixes the borrow checker error in nightly.

_Originally posted by @mzabaluev in https://github.com/rust-lang/rust/issues/80949#issuecomment-768783279_

**Comment by camelid** [comment] 2021-01-28 04:12
Regressed yesterday (!).

**Comment by camelid** [comment] 2021-01-28 04:20
From that PR:

> ## What breaks?
> 
> A crater run revealed a few crates broke with something like the following:
> 
> ```rust
> // where e: &'short &'long dyn Error
> err.source()
> ```
> 
> previously we'd auto-deref that `&'short &'long dyn Error` to return a `Option<&'long dyn Error>` from `source`, but now will call directly on `&'short impl Error`, so will return a `Option<&'short dyn Error>`. The fix is to manually deref:
> 
> ```rust
> // where e: &'short &'long dyn Error
> (*err).source()
> ```
> 
> In the recent Libs meeting we considered this acceptable breakage.

Given that someone ran into this so quickly (the day after it was merged), should that decision be reconsidered?

**Comment by apiraino** [comment] 2021-01-28 11:47
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381460.20regression.201.2E51.3A.20lifetime.20may.20not.20live.20long.20enough) and removing `I-prioritize`.

**Comment by mzabaluev** [comment] 2021-01-28 12:15
> In the recent Libs meeting we considered this acceptable breakage.

I find it startling that breaking existing code _that isn't wrong_ could be considered acceptable.

**Comment by camelid** [comment] 2021-01-28 21:04
Nominating for T-libs discussion and removing T-compiler label (I don't think this issue has a compiler component).

@rustbot label: +I-nominated -T-compiler

**Comment by sfackler** [comment] 2021-01-28 21:33
> I find it startling that breaking existing code _that isn't wrong_ could be considered acceptable.

If we never considered a change that could break not-wrong existing code acceptable, we would, for example, never be able to add a new method to a trait, or add an implementation of a trait to an existing type.

**Comment by yaahc** [comment] 2021-02-03 20:45
related: https://github.com/yaahc/stable-eyre/pull/4

**Comment by m-ou-se** [comment] 2021-02-03 21:40
We discussed this in the library team meeting again just now, and agreed that this breakage still seems acceptable. Closing this issue for now.

If this turns out to cause any significant breakage in the ecosystem, feel free to re-open.

**Closed by m-ou-se** 2021-02-03 21:40 UTC
Labels: A-lifetimes, P-high, T-libs, regression-from-stable-to-nightly

**Comment by KodrAus** [comment] 2021-02-03 23:45
It's unfortunate that we no longer get that auto-deref for free that lops off the `'short` borrow. As noted in #80949 this can be fixed by using a reference binding:

```rust
fn walk_source_chain(error: &impl Error) {
    for e in iter::successors(error.source(), |&e| e.source()) {
        println!("{}", e);
    }
}
```

Or alternatively by accepting a `&(dyn Error + 'static)` when you can instead, since it's still a more useful bound:

```rust
fn walk_source_chain(error: &(dyn Error + 'static)) {
    for e in error.chain() {
        println!("{}", e);
    }
}
```

To make `impl Error` more useful, we could look at adding a `chain` method to the `Error` trait itself:

```rust
trait ChainExt: Error {
    fn chain(&self) -> Chain
    where
        Self: Sized + 'static,
    {
        <dyn Error + 'static>::chain(self)
    }
}

impl<E: Error> ChainExt for E {}

fn _assert_object_safe(_: &dyn ChainExt) {
    
}

fn walk_source_chain(error: &(impl Error + 'static)) {
    for e in error.chain() {
        println!("{}", e);
    }
}
```

which wouldn't clash with this:

```rust
fn walk_source_chain(error: &(impl Error + 'static)) {
    for e in error.chain() {
        println!("{}", e);
    }
}
```

but would with this:

```rust
fn dyn_walk_source_chain<'a>(error: &'a &'a (dyn Error + 'static)) {
    for e in error.chain() { // <-- would now fail to assert that `&'a (dyn Error + 'static)` is `'static`
        println!("{}", e);
    }
}
```

That's basically the same cause as above.

**Comment by Mark-Simulacrum** [comment] 2021-03-01 16:45
One case of this was found by beta crater: https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/strerror-0.6.3/log.txt
