### ISSUE TITLE
Why wrapping an Option inside a Some ?

### ISSUE THREAD

**Issue by addityasingh** [rust-lang/rust#44376] opened 2017-09-06 21:44 UTC
During pattern match we don't need to wrap a `None` inside a `Some` 

https://github.com/rust-lang/rust/blob/a20953906056f85f71896795e762ac242e1891aa/src/libcore/iter/mod.rs#L1521

and similarly for a `Some` inside a `Some`

https://github.com/rust-lang/rust/blob/a20953906056f85f71896795e762ac242e1891aa/src/libcore/iter/mod.rs#L1520

Is there any specific reason for doing this or can we get rid of the extraneous looking Option?

**Comment by estebank** [comment] 2017-09-06 23:46
The reason is in the definition:

https://github.com/rust-lang/rust/blob/a20953906056f85f71896795e762ac242e1891aa/src/libcore/iter/mod.rs#L1404-L1405

You can think of this as:

```rust
type PeekedIterResult = Option<Item>;
/// ...
peeked: Option<PeekedIterResult>,
```

The outer `Option` being `None` means that the `peek()` hasn't been called on this `Peekable`, While the inner `Option` being `None` means that the iterator has ended.

**Comment by steveklabnik** [comment] 2017-09-07 14:18
Yup! Closing as "not a bug". Thanks @addityasingh !

**Closed by steveklabnik** 2017-09-07 14:18 UTC

**Comment by addityasingh** [comment] 2017-09-07 18:27
Thanks @estebank for the quick and well explained answer :)
