### ISSUE TITLE
rust bin do not support static and dynamic library

### ISSUE THREAD

**Issue by VikingMew** [rust-lang/rust#51600] opened 2018-06-16 21:09 UTC
ref from the top answer of 
https://stackoverflow.com/questions/26946646/rust-package-with-both-a-library-and-a-binary

this sample works fine, but it is not working when `crate-type = ["staticlib"]` is added into `[lib]`

```rust
     Running `rustc --crate-name mylib src/lib.rs --crate-type staticlib --emit=dep-info,link -C debuginfo=2 -C metadata=f36b9f5bc9ab9f55 -C extra-filename=-f36b9f5bc9ab9f55 --out-dir D:\cargo_temp\temp1\target\debug\deps -C incremental=D:\cargo_temp\temp1\target\debug\incremental -L dependency=D:\cargo_temp\temp1\target\debug\deps`
     Running `rustc --crate-name mybin src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=2687d511ce54ac88 -C extra-filename=-2687d511ce54ac88 --out-dir D:\cargo_temp\temp1\target\debug\deps -C incremental=D:\cargo_temp\temp1\target\debug\incremental -L dependency=D:\cargo_temp\temp1\target\debug\deps`
error[E0463]: can't find crate for `mylib`
 --> src/main.rs:1:1
  |
1 | extern crate mylib;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

cargo ver: cargo 1.28.0-nightly (c3b09c968 2018-05-27)
rust ver: rustc 1.28.0-nightly (5bf68db6e 2018-05-28)

**Comment by VikingMew** [comment] 2018-06-16 21:40
is that possible to link as `dylib`, or `lib` is the only supported form?

I met error with `dylib`

```rust
 Running `rustc --crate-name mybin src/main.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=83480335185a07f8 -C extra-filename=-83480335185a07f8 --out-dir D:\cargo_temp\temp1\target\debug\deps -C incremental=D:\cargo_temp\temp1\target\debug\incremental -L dependency=D:\cargo_temp\temp1\target\debug\deps --extern mylib=D:\cargo_temp\temp1\target\debug\deps\mylib.dll`
error: cannot satisfy dependencies so `std` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `core` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `compiler_builtins` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

```

**Comment by jonas-schievink** [comment] 2020-02-09 18:53
Closing as a duplicate of #34909

**Closed by jonas-schievink** 2020-02-09 18:53 UTC
Labels: A-linkage
