### ISSUE TITLE
ICE on Miri: vtable not supported on type Pin<&mut dyn futures::Future<Output = i32>>

### ISSUE THREAD

**Issue by p0lunin** [rust-lang/rust#80645] opened 2021-01-03 11:00 UTC
### Code

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8b530e4722f0d660d0f5d8f2455b598d

Tools -> Miri

### Meta
```
-note: rustc 1.51.0-nightly (fde692739 2021-01-02) running on x86_64-unknown-linux-gnu
note: compiler flags: -Z miri-disable-isolation -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin
```
### Error output

```
error: internal compiler error: /rustc/fde692739576089729885b7f79aa2232cb9778c5/compiler/rustc_mir/src/interpret/place.rs:224:18: vtable not supported on type std::pin::Pin<&mut dyn futures::Future<Output = i32>>

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:958:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (fde692739 2021-01-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z miri-disable-isolation -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error
```

**Comment by RalfJung** [comment] 2021-01-03 13:15
Thanks for the report! This is a duplicate of https://github.com/rust-lang/miri/issues/1038.

**Closed by RalfJung** 2021-01-03 13:15 UTC
Labels: A-miri, C-bug, I-ICE, T-compiler
