### ISSUE TITLE
the compiler unexpectedly panicked. this is a bug.

### ISSUE THREAD

**Issue by sagiegurari** [rust-lang/rust#49113] opened 2018-03-17 14:33 UTC
I upgraded to a new rust nightly and now it seems the compiler crashes during build.

* I'm using raspberry pi 3
```console
> uname -a
Linux pidesk 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
``` 

* rust version:
```console
> rustc --version
rustc 1.26.0-nightly (55c984ee5 2018-03-16)
```

* code example which causes issue: https://github.com/sagiegurari/misc-test/tree/rust2
* error:
```console
> cargo check
Compiling test v0.0.1 (file:///media/projects/misc-test)
Finished dev [unoptimized + debuginfo] target(s) in 0.70 secs

> cargo build --verbose                                                                                                                                                     
   Compiling utf8-ranges v1.0.0
     Running `rustc --crate-name utf8_ranges /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8-ranges-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=0d901130be5be452 -C extra-filename=-0d901130be5be452 --out-dir /media/projects/misc-test/target/debug/deps -L dependency=/media/projects/misc-test/target/debug/deps --cap-lints allow`
thread 'rustc' panicked at 'index out of bounds: the len is 21696714 but the index is 21696714', /checkout/src/libserialize/opaque.rs:259:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (55c984ee5 2018-03-16) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `utf8-ranges`.

Caused by:
  process didn't exit successfully: `rustc --crate-name utf8_ranges /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8-ranges-1.0.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=0d901130be5be452 -C extra-filename=-0d901130be5be452 --out-dir /media/projects/misc-test/target/debug/deps -L dependency=/media/projects/misc-test/target/debug/deps --cap-lints allow` (exit code: 101)
```

**Comment by bjorn3** [comment] 2018-03-17 14:50
Looks like dup of #49065

**Comment by sagiegurari** [comment] 2018-03-17 14:51
ya maybe. tried to find something similar, but didn't find in the titles.

**Comment by sagiegurari** [comment] 2018-03-19 10:48
I guess #48923 is related as well as #49065 was just closed

**Comment by sagiegurari** [comment] 2018-03-19 10:52
Actually reading more, I see they complain on incremental builds and for me it is a simple clean build.
Might be wrong but it does look like high priority.

**Comment by bjorn3** [comment] 2018-03-19 16:46
Cargo uses incremental builds by default now (rust-lang/cargo#4817)

**Comment by nikomatsakis** [comment] 2018-03-22 14:23
Hopefully a duplicate of https://github.com/rust-lang/rust/issues/48923.

@sagiegurari can you verify if (a) using `CARGO_INCREMENTAL=0` stops the problem and (b) get the output using `RUST_BACKTRACE=1`?

**Comment by nikomatsakis** [comment] 2018-03-22 14:23
triage: P-high

Since likely incremental bug, assigning to @michaelwoerister

**Comment by sagiegurari** [comment] 2018-03-22 16:30
I upgraded to the latest nightly 2018-03-20 and it looks like everything is working find now.
Wasn't aware there was a fix already.

**Comment by michaelwoerister** [comment] 2018-03-23 09:35
This was probably MIRI related then. Thanks for the update, @sagiegurari!

**Closed by michaelwoerister** 2018-03-23 09:35 UTC
Labels: C-bug, I-ICE, O-ARM, P-high, regression-from-stable-to-nightly
