### ISSUE TITLE
Array initialization with repeated enum variant requires the whole enum type to be Copy

### ISSUE THREAD

**Issue by benw** [rust-lang/rust#30754] opened 2016-01-07 00:14 UTC
I want to initialize an array of `Option<Foo>` with `[None; 5]`. The `None` variant is constant and has no associated data, so there seems to be no reason that it couldn't be copied into all the entries in the array:

```rust
struct Foo;

fn main() {
    let mut array: [Option<Foo>; 5] = [None; 5];
}
```

Sadly this errors because `Foo` is not `Copy`, so `Option<Foo>` is not `Copy`.

```
<anon>:4:35: 4:44 error: the trait `core::marker::Copy` is not implemented for the type `Foo` [E0277]
<anon>:4     let array: [Option<Foo>; 5] = [None; 5];
                                           ^~~~~~~~~
```
I gather array initialization treats `None` as an expression in this case? Could it instead notice that `None` is a constant, and copy it to all the elements in the array?

**Comment by huonw** [comment] 2016-01-07 00:45
This is a dupe of https://github.com/rust-lang/rust/issues/5244 which (transitively) is a dupe of https://github.com/rust-lang/rfcs/issues/1109. Thanks for filing anyway!

**Closed by huonw** 2016-01-07 00:45 UTC

**Comment by benw** [comment] 2016-01-07 00:55
Thanks! I searched but did not find.
