### ISSUE TITLE
Spurious unused type alias warning (regression)

### ISSUE THREAD

**Issue by jseyfried** [rust-lang/rust#41203] opened 2017-04-10 21:00 UTC
This [example](https://play.rust-lang.org/?gist=ca7f01771b3c5e168c663cda4c34a5f2&version=nightly&backtrace=0) produced a spurious unused type alias warning:
```rust
struct S<T>(T);
type Alias<T> = S<T>;

trait Tr<T> { fn f(&self) {} }
impl<T> Tr<T> for S<T> {}

impl<T> S<T> where Alias<T>: Tr<T> {
    fn g(&self) { self.f() }
}

fn main() {
    S(0).g();
}
```

**Comment by Mark-Simulacrum** [comment] 2017-05-31 22:17
Bisected regression to aedb49cbc9977fee56bb51a20980b380aca53659 -- rollup #39199; not really sure what PR in there this was caused by. Nominating for compiler discussion since regression without priority, though this is in stable now so not overly important I guess.

**Comment by eddyb** [comment] 2017-06-01 17:32
@Mark-Simulacrum What's the "before" on that bisection? I've looked through the entire rollup and I can't find anything that would change the behavior there.

**Comment by Mark-Simulacrum** [comment] 2017-06-01 18:28
Never mind -- sorry for the runaround, my bisect was broken, missing [libstdc++6](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error); this does not bisect to any point since 2017-01-13.

**Comment by nikomatsakis** [comment] 2017-06-08 20:54
@jseyfried says they had this working on a nightly from october without warning.

**Comment by nikomatsakis** [comment] 2017-06-08 20:54
triage: P-high

**Comment by brson** [comment] 2017-06-15 16:04
@jseyfried do you mind self-assigning this P-high regression and taking a look?

**Comment by jseyfried** [comment] 2017-06-15 18:27
@brson sure.

**Comment by sanxiyn** [comment] 2017-07-13 07:23
#38051 implementing unused type alias landed in December, so of course October nightly would work.

**Comment by brson** [comment] 2017-07-13 16:18
cc @rust-lang/compiler another P-high bug

**Comment by Mark-Simulacrum** [comment] 2017-07-13 16:42
I can't find an issue, but I seem to recall this being a known problem of not checking impl signatures (everything outside the body) for "use"

**Comment by jseyfried** [comment] 2017-07-13 20:04
This was introduced between `nightly-2016-12-16` (8f02c429a) and `nightly-2016-12-19` (71c06a56a).

**Comment by nikomatsakis** [comment] 2017-07-17 14:54
Heh, sounds like a likely candidate!

**Comment by nikomatsakis** [comment] 2017-07-17 14:54
@sanxiyn think you'll have time to investigate @jseyfried's hypothesis?

**Comment by Mark-Simulacrum** [comment] 2017-07-22 00:41
Arguably this is the same/similar bug as https://github.com/rust-lang/rust/issues/18290 (this is the bug I was looking for earlier).

**Comment by Mark-Simulacrum** [comment] 2017-07-27 16:26
Closing as a duplicate of #18290.

**Closed by Mark-Simulacrum** 2017-07-27 16:26 UTC
Labels: A-lint, C-bug, I-nominated, P-high, regression-from-stable-to-stable, T-compiler
