### ISSUE TITLE
the compiler unexpectedly panicked

### ISSUE THREAD

**Issue by angelrain1** [rust-lang/rust#43210] opened 2017-07-13 08:09 UTC
<short summary of the bug>

I tried this code:

extern crate nanomsg;
extern crate futures;

use std::sync::mpsc::*;
use std::thread::{Thread, current};

pub use self::futures::{Future, Poll, Async};

pub use self::nanomsg::{PollFd, Socket, PollRequest, PollInOut};

type Notify = (PollFd, Thread);

pub struct NanoCore {
    tx: Sender<Notify>,
    rx: Receiver<Notify>
}

pub enum NanoCoreError {
    NanoError(nanomsg::Error),
    SendError(SendError<Notify>),
    RecvError(RecvError),
}

impl From<nanomsg::Error> for NanoCoreError {
    fn from(e: nanomsg::Error) -> Self {
        NanoCoreError::NanoError(e)
    }
}

impl From<SendError<Notify>> for NanoCoreError {
    fn from(e: SendError<Notify>) -> Self {
        NanoCoreError::SendError(e)
    }
}

impl From<RecvError> for NanoCoreError {
    fn from(e: RecvError) -> Self {
        NanoCoreError::RecvError(e)
    }
}

struct ReadReady {
    socket: Socket,
    sender: Sender<(PollFd, Thread)>,
}

impl ReadReady {
    fn new(socket: Socket, core: &NanoCore) -> ReadReady {
        ReadReady { socket: socket, sender: core.tx.clone() }
    }

    fn new_poll_fd(&self) -> PollFd {
        self.socket.new_pollfd(PollInOut::In)
    }
}

impl Future for ReadReady {
    type Item = Socket;
    type Error = NanoCoreError;

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        self.sender.send((self.new_poll_fd(), current()))?;
        Ok(Async::NotReady)
    }
}

impl NanoCore {
    pub fn new() -> NanoCore {
        let (tx, rx) = channel();
        NanoCore {
            tx: tx,
            rx: rx
        }
    }

    pub fn poll(&self) -> nanomsg::Result<()> {
        let timeout = 10;

        Ok(())
    }
}

I expected to see this happen: <explanation>

Instead, this happened: <explanation>

## Meta

`rustc --version --verbose`:

rustc 1.18.0 (03fc9d622 2017-06-06)
binary: rustc
commit-hash: 03fc9d622e0ea26a3d37f5ab030737fcca6928b9
commit-date: 2017-06-06
host: x86_64-pc-windows-msvc
release: 1.18.0
LLVM version: 3.9

Backtrace:

thread 'rustc' panicked at 'invalid lint-id `trivial_numeric_casts`', src\librustc\lint\context.rs:1322
stack backtrace:
   0: <std::time::SystemTimeError as core::fmt::Display>::fmt
   1: std::panicking::Location::line
   2: std::panicking::Location::line
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_fmt
   5: std::panicking::begin_panic_fmt
   6: <unknown>
   7: rustc_metadata::decoder::<impl rustc_metadata::cstore::CrateMetadata>::item_body_tables
   8: rustc_metadata::cstore_impl::provide
   9: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::try_get
  10: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::get
  11: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::item_tables
  12: rustc_const_eval::eval::provide
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::try_get
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::const_eval<'tcx>>::get
  15: rustc::ty::layout::Layout::compute_uncached
  16: rustc::ty::util::<impl rustc::ty::TyS<'tcx>>::needs_drop_uncached
  17: <unknown>
  18: <unknown>
  19: rustc::ty::layout::Layout::compute_uncached
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: rustc::ty::layout::Layout::compute_uncached
  25: <rustc_lint::types::VariantSizeDifferences as rustc::lint::LateLintPass<'a, 'tcx>>::check_item
  26: rustc::lint::context::gather_attrs
  27: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  28: rustc::hir::intravisit::NestedVisitorMap::inter
  29: rustc::lint::context::gather_attrs
  30: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  31: rustc::lint::context::check_crate
  32: rustc_driver::driver::count_nodes
  33: <unknown>
  34: rustc_driver::driver::count_nodes
  35: rustc_driver::driver::compile_input
  36: rustc_driver::run_compiler
  37: <unknown>
  38: _rust_maybe_catch_panic
  39: <unknown>
  40: std::sys::imp::thread::Thread::new
  41: BaseThreadInitThunk

**Comment by angelrain1** [comment] 2017-07-13 08:25
cased by
pub enum NanoCoreError {
NanoError(nanomsg::Error),

**Comment by kennytm** [comment] 2017-07-13 08:31
Please try if it crashes in 1.19-beta or nightly. If it doesn't, then this issue is a duplicate of #42546 which has been fixed.

**Comment by angelrain1** [comment] 2017-07-13 08:37
thx.

can be fixed by this.

impl From<nanomsg::Error> for NanoCoreError {
    fn from(e: nanomsg::Error) -> Self {
        NanoCoreError::NanoError(e.to_raw() as isize)
    }
}

it could cased by nanomsg::Error define 

pub enum Error {
    Unknown                    = 0 as isize,

**Closed** 2017-07-13 08:42 UTC
