### ISSUE TITLE
Spurious type deduced when using `?`

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#71685] opened 2020-04-29 17:19 UTC
I tried this code:

```rust
#![feature(associated_type_bounds)]
struct S;
fn fn1<I: IntoIterator<Item: AsRef<S>>>(_iter: I) -> Result<(), ()> {
    Ok(())
}

async fn fn2(s: &str) -> Result<(), ()> {
    let s = s.parse().map_err(|_| ())?; // <- Spurious type deduced
    fn1(std::iter::once(s)).map_err(|e| ())?;
    Ok(())
}
```

I expected to see this happen:

`error[E0282]: type annotations needed`, because type of `s` cannot be determined.

Instead, this happened: 

`error[E0277]: the trait bound '(): std::str::FromStr' is not satisfied`

As if `s` is assigned type `()`

**Comment by yshui** [comment] 2020-04-30 16:27
Looks like `?` triggers the problem.

This has the problem:

```rust
#![feature(associated_type_bounds)]
struct S;
fn fn1<I: IntoIterator<Item: AsRef<S>>>(_iter: I) {
}

fn fn2(s: &str) -> Result<(), ()> {
    let s = s.parse().map_err(|_| ())?; // <- Spurious type deduced
    fn1(std::iter::once(s));
    Ok(())
}
```

But not this:

```rust
#![feature(associated_type_bounds)]
struct S;
fn fn1<I: IntoIterator<Item: AsRef<S>>>(_iter: I) {
}

fn fn2(s: &str) {
    let s = s.parse().unwrap(); // <- Spurious type deduced
    fn1(std::iter::once(s));
}
```

**Comment by yshui** [comment] 2020-04-30 16:34
I think label "F-associated_type_bounds", "requires-nightly" should be removed. "A-diagnostics" should be added.

**Comment by jackh726** [comment] 2021-01-28 18:04
Minimal repro
```
fn fn2(s: &str) -> Result<(), ()> {
    let s = s.parse().map_err(|_| ())?;
    Ok(())
}
```
with
```
error[E0277]: the trait bound `(): FromStr` is not satisfied
 --> src/lib.rs:2:15
  |
2 |     let s = s.parse().map_err(|_| ())?;
  |               ^^^^^ the trait `FromStr` is not implemented for `()`
```

I agree with @yshui here: this is really just a diagnostics issue. `s` here is falling back to `()` since it's isn't used after being reassigned.

**Comment by estebank** [comment] 2023-08-14 13:52
Current output:

```
error[E0277]: the trait bound `(): FromStr` is not satisfied
    --> f71.rs:2:15
     |
2    |     let s = s.parse().map_err(|_| ())?;
     |               ^^^^^ the trait `FromStr` is not implemented for `()`
     |
     = help: the following other types implement trait `FromStr`:
               bool
               char
               isize
               i8
               i16
               i32
               i64
               i128
             and 29 others
note: required by a bound in `core::str::<impl str>::parse`
    --> /home/gh-estebank/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/mod.rs:2310:21
     |
2310 |     pub fn parse<F: FromStr>(&self) -> Result<F, F::Err> {
     |                     ^^^^^^^ required by this bound in `core::str::<impl str>::parse`
```

**Comment by estebank** [comment] 2024-02-15 02:39
This is a duplicate of #38508. Closing it in favor of the older one.

**Closed by estebank** 2024-02-15 02:39 UTC
Labels: A-diagnostics, T-compiler, A-inference, C-bug, D-confusing
