### ISSUE TITLE
ICE with deref raw pointer

### ISSUE THREAD

**Issue by dschatzberg** [rust-lang/rust#22154] opened 2015-02-10 19:54 UTC
I hit an ICE - I've reduced a reproducible test case here: http://is.gd/M5LB6P

    pub struct Foo<T, P>
        where P: DerefMut<Target=Bar<T>>
    {
        bar: P,
    }
    
    pub struct Bar<T> {
        nzp: NonZero<*mut Option<T>>
    }
    
    impl<T, P> Foo<T, P>
        where P: DerefMut<Target=Bar<T>>
    {
        fn fun(&mut self) {
            let p: *mut Option<T> = *self.bar.nzp;
            match unsafe {*p} {
                None => (),
                Some(t) => (),
            }
        }
    }

error is

    <anon>:22:23: 22:25 error: internal compiler error: this path should not cause illegal move
    <anon>:22         match unsafe {*p} {
                                    ^~

I'm not even sure what the workaround for this is. Any ideas?

**Comment by jdm** [comment] 2015-02-10 20:33
Duplicate of #20801.

**Closed by jdm** 2015-02-10 20:33 UTC
Labels: I-ICE
