### ISSUE TITLE
rustc and cargo do not display colors under the msys console

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#31459] opened 2016-02-07 03:52 UTC
Their tty detection on windows detects the windows console, but not the msys console. It is possible to detect msys and display color. TTY detection should probably be factored into [term](https://github.com/Stebalien/term) (cc @Stebalien), since both rustc and cargo have this code (differently), and the `atty` crate (cc @softprops) uses yet a different mechanism and also doesn't detect msys.

The type of `Terminal` created by `term` probably needs to take into account the type of terminal detected, once msys is taken into account.

**Comment by retep998** [comment] 2016-02-07 06:10
The issue is that mintty uses pipes for stdout and stderr, so they are indistinguishable from any other pipe. There's no way to tell if stdout is pointed towards the mintty console or a random file.

**Comment by brson** [comment] 2016-02-07 20:44
@retep998 [Here's a PR to git](https://github.com/git-for-windows/git/pull/102) about detecting msys terminals. I think that's the same as mintty. We can't take their code directly though because licenses.

**Comment by retep998** [comment] 2016-02-07 21:20
That code relies on [NtQueryObject](https://msdn.microsoft.com/en-us/library/bb432383(v=vs.85).aspx) to get the name of the pipe which I'd be rather wary of using considering msdn says "[This function may be changed or removed from Windows without further notice.]"

**Comment by Enamex** [comment] 2016-04-29 17:31
Would really like this. My scanning reflexes are suddenly cumbersome without the colors. Any updates?

**Comment by brson** [comment] 2016-05-09 22:36
@Enamex no updates.

**Comment by Stebalien** [comment] 2016-05-10 03:57
@Enamex I'm working on a new version of term that should fix this. It's just taking a while.

**Comment by steveklabnik** [comment] 2019-03-25 17:07
I attempted to try to reproduce this today, but `curl` can't seem to properly download rust inside of the version of msys i tried.

**Comment by ehuss** [comment] 2020-07-13 00:35
Closing, since I think this was fixed around version 1.20 (probably via https://github.com/rust-lang/cargo/pull/4176).

**Closed by ehuss** 2020-07-13 00:35 UTC
Labels: C-enhancement, T-dev-tools
