### ISSUE TITLE
Macro generated code fails to compile

### ISSUE THREAD

**Issue by AnickaBurova** [rust-lang/rust#58560] opened 2019-02-18 15:19 UTC
I  have a macro which generates bit of code.
```rust 
macro_rules! get_message {
    ($name: ident, $result: ty: $result_inner: ty, $($arg: ident: $arg_ty: ty,)* -> $main: ty, $fun: ident, -> $handler: ty => $code: block) => {
        pub struct $name {
            $(pub $arg: $arg_ty,)*
        }

        impl Message for $name {
            type Result = Addr<$result_inner>;
        }

        impl $name {
            pub fn new($($arg: $arg_ty,)*) -> Self {
                Self {
                    $($arg,)*
                }
            }
        }

        impl $main {
            pub fn $fun(&self, $($arg: $arg_ty,)*) -> impl Future<Item = $result, Error = Error> {
                self.inner
                    .send($name::new($($arg,)*))
                    .map(|inner| Light::new(inner))
                    .map_err(Error::from)
            }
        }

        #[cfg(not(feature = "manual"))]
        impl Handler<$name> for $handler {
            type Result = Addr<$result_inner>;

            #[allow(unused_variables)]
            fn handle(&mut self, msg: $name, ctx: &mut Context<Self>) -> Self::Result {
                let $name { $($arg,)* } = msg;
                $code
            }
        }
    }
}
```
Not the shortest nor the nicest macro, it is more poc for now.
It is used like this:
```rust
get_message!(CreateLight, Light: LightImpl, index: u8, name: String,
             -> Lighting, create_light,
             -> LightingImpl => {
                let addr = self
                    .lights
                    .entry(index)
                    .or_insert(LightImpl::new(ctx.address(), index));
                (*addr).clone()
             });

```
It generates these two errors:
```bash
error[E0424]: expected value, found module `self`
  --> src/lighting_impl.rs:35:28
   |
35 |                 let addr = self
   |                            ^^^^ `self` value is a keyword only available in methods with `self` parameter

error[E0425]: cannot find value `ctx` in this scope
  --> src/lighting_impl.rs:38:47
   |
38 |                     .or_insert(LightImpl::new(ctx.address(), index));
   |                                               ^^^ not found in this scope

error: aborting due to 2 previous errors

```
When I have the trait implementation written manually, not generated by the macro, all is working all right.
You can reproduce the whole problem in this repo [macro-bug](https://github.com/AnickaBurova/macro-bug)
Sorry for not simpler example, I tried to get least amount of code out of my project, but I am limited in time to play around.

It is failing in the latest stable and nightly.
My system is archlinux 4.20.8 x86_64.

Thanks

**Comment by jonas-schievink** [comment] 2019-02-18 15:24
I ma pretty sure this is working as intended and is just identifier hygiene applied to `self`: The declared `self` in the macro is not the same as the `self` you pass into the macro.

**Comment by AnickaBurova** [comment] 2019-02-18 15:32
Oh I forgot to mention, this stopped working after I changed the trait Result to the current type. It was working in macro before, but not working now. I can dig the old code and make an example if it is needed. But why is the "hygiene" not applied to "index" variable as well? That does not make sense.

**Comment by jonas-schievink** [comment] 2019-02-18 15:38
It is, but the declaration of `index` is being passed into the macro from the invocation, so those are considered the same idents.

**Comment by AnickaBurova** [comment] 2019-02-18 15:48
It looks like this is the "hygiene" of the macros, so I made a simple workaround, converting the code block in to a lambda.
```rust
        impl Handler<$name> for $handler {
            type Result = Addr<$result_inner>;

            #[allow(unused_variables)]
            fn handle(&mut self, msg: $name, ctx: &mut Context<Self>) -> Self::Result {
                let $name { $($arg,)* } = msg;
                let fun: fn (&mut Self, $($arg_ty,)* &mut Context<Self>) -> Self::Result = $code;
                fun(self, $($arg,)* ctx)
            }
        }
        get_message!(CreateLight, Light: LightImpl, index: u8, name: String,
             -> Lighting, create_light,
             -> LightingImpl => {
                 |this, index, name, ctx|{
                    let addr = this
                        .lights
                        .entry(index)
                        .or_insert(LightImpl::new(ctx.address(), index));
                    (*addr).clone()
                 }
             });

```

Thanks for help
I wonder if the compiler will remove the lambda and inline the code.

**Comment by jonas-schievink** [comment] 2019-02-18 15:53
Okay, seems like that solves it, so closing.

Generally you can rely on the compiler to optimize your code very well, and this seems like an obvious optimization, so it shouldn't miss it.

**Closed by jonas-schievink** 2019-02-18 15:53 UTC
