### ISSUE TITLE
[1.30 beta] Ambiguous macro names

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54472] opened 2018-09-22 13:48 UTC
Some crates in 1.30 beta are failing with ambiguous macro names errors:

```
 error[E0659]: `run_cancel` is ambiguous
    --> tests/pipeable.rs:156:5
     |
 156 |     run_cancel!(Simple(mock_must_cancel()));
     |     ^^^^^^^^^^ ambiguous name
     |
```

```
 error[E0659]: `try` is ambiguous
   --> src/lib.rs:52:10
    |
 52 | #[derive(Serialize, Deserialize, Debug)]
    |          ^^^^^^^^^ ambiguous name
    |
```

* [conch-runtime](https://crates.io/crates/conch-runtime) `0.1.4` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/conch-runtime-0.1.4/log.txt)) cc @ipetkov
* [off_blockway](https://crates.io/crates/off_blockway) `0.0.8` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/off_blockway-0.0.8/log.txt)) cc @ezragoss
* [reed-solomon-erasure](https://crates.io/crates/reed-solomon-erasure) `3.1.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/reed-solomon-erasure-3.1.0/log.txt)) cc @darrenldl
* [smpl_jwt](https://crates.io/crates/smpl_jwt) `0.3.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/smpl_jwt-0.3.0/log.txt)) cc @durch
* [tokio-postgres](https://crates.io/crates/tokio-postgres) `0.3.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/tokio-postgres-0.3.0/log.txt)) cc @sfackler 

cc @petrochenkov

**Comment by ipetkov** [comment] 2018-09-22 17:45
Only the `conch-runtime` tests were affected by this, which were fixed a while back but I didn't end up releasing a new version (an oversight which has now been corrected)

**Comment by petrochenkov** [comment] 2018-09-26 10:30
>One low-hanging fruit is treating glob imports from other crates as single imports for the purposes of restricted shadowing.

It actually won't help with regressions here, I've misinterpreted the error messages.

The ambiguities in listed crates are "`macro_rules` definition" vs "macro in module".
They need some disambiguation scheme similar to "`let` variable" vs "item in block", but at module level.
```rust
fn main() {
    let x = || 0;
    println!("{:?}", x());
    {
        println!("{:?}", x());
        fn x() -> i32 { 1 }
        println!("{:?}", x());
        let x = || 2;
        println!("{:?}", x());
    }
    println!("{:?}", x());
}
---
0
1
1
2
0
```

**Comment by petrochenkov** [comment] 2018-09-27 02:44
Partially fixed in https://github.com/rust-lang/rust/pull/54605 using subset of the `let` rules described in the previous comment.

**Comment by nagisa** [comment] 2018-09-27 15:10
@petrochenkov should we also warn when resolving in favour of `macro_rules!`?

**Comment by petrochenkov** [comment] 2018-09-27 15:29
I don't think so? In all the regressed cases the `macro_rules` resolution is expected, and modularized resolutions are "accidental" - either from globs, or from [`#[macro_export]` planted into the root module](https://github.com/rust-lang/rust/pull/52234).

It's not something deprecated/hacky either - I planned to implement the scoping rules from https://github.com/rust-lang/rust/issues/54472#issuecomment-424666659 eventually anyway since it's kinda "natural" expected behavior for `let`-like things, the regressions just made the matter more urgent.

**Comment by petrochenkov** [comment] 2018-09-27 19:16
Minimized reproduction for `smpl_jwt` and `off_blockway`:
```rust
use std::*;

fn main() {
    macro_rules! try { ($expr:expr) => () }
    
    try!(0);
}
```

**Comment by petrochenkov** [comment] 2018-10-02 14:34
https://github.com/rust-lang/rust/pull/54605 is updated with a fix for the remaining regressions.

**Closed** 2018-10-03 20:50 UTC
Labels: P-high, T-compiler, regression-from-stable-to-beta
