### ISSUE TITLE
error message does not include function it refers to, only says "this function" (E0061)

### ISSUE THREAD

**Issue by jmesmon** [rust-lang/rust#45633] opened 2017-10-30 14:45 UTC
```
error[E0061]: this function takes 2 parameters but 1 parameter was supplied
  --> src/main.rs:63:13
   |
63 |             std::net::SocketAddr::new(ia, 0u16)
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: aborting due to previous error
```

In this case, `this function` is `tokio_core::net::UdpSocket::bind`, but without looking at the code no hint is given:

```
        let sock = tokio_core::net::UdpSocket::bind(
            std::net::SocketAddr::new(ia, 0u16)
        ).unwrap();
```

Originally, this function call contained a match statement to calculate the value of `ia`, which caused the newline-following paren style to be used.

This appears to occur whenever both:

 - using a newline-following paren style (such that the function name does not get included in the context output)
 - calling a function from outside the current crate (so that it's definition is not printed)

**Comment by oli-obk** [comment] 2017-10-30 16:47
Duplicate of https://github.com/rust-lang/rust/issues/42855

**Comment by jmesmon** [comment] 2017-10-31 03:17
closing as dup of #42855

**Comment by jmesmon** [comment] 2017-10-31 03:21
Actually, this looks like a slightly different issue.

`ia` isn't the problem here. `std::net::SocketAddr::new()` takes two arguments, but `tokio_core::net::UdpSocket::bind` also takes 2 arguments, but isn't mentioned in the error message. (`this function` is `tokio_core::net::UdpSocket::bind`).

**Closed** 2017-12-14 12:50 UTC
Labels: A-diagnostics, C-enhancement, E-needs-mentor, WG-compiler-errors
