### ISSUE TITLE
`NonZero*` is not known non-zero to llvm

### ISSUE THREAD

**Issue by Kmeakin** [rust-lang/rust#114943] opened 2023-08-17 19:28 UTC
I tried this code:

```rust
use std::num::NonZeroU32;

pub fn is_zero(x: NonZeroU32) -> bool {
    x.get() == 0
}
```

I expected to see this happen:
`is_zero` should compile to a single `ret i1 false` LLVM instruction

Instead, this happened: 
`is_zero` compares `x` against 0 ([godbolt](https://godbolt.org/z/7qWfechbh))
```llvm
define noundef zeroext i1 @_ZN7example7is_zero17h8caeabc8058ffe90E(i32 noundef %x) unnamed_addr #0 {
  %_0 = icmp eq i32 %x, 0
  ret i1 %_0
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.73.0-nightly (180dffba1 2023-08-14)
binary: rustc
commit-hash: 180dffba142c47240ca0d93096ce90b9fd97c8d7
commit-date: 2023-08-14
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 17.0.0
Compiler returned: 0
```

**Comment by nikic** [comment] 2023-08-17 19:52
Duplicate of https://github.com/rust-lang/rust/issues/49572.

**Closed by nikic** 2023-08-17 19:52 UTC
Labels: I-slow, C-bug, needs-triage
