### ISSUE TITLE
"0u8.." panics

### ISSUE THREAD

**Issue by Christopher22** [rust-lang/rust#35589] opened 2016-08-11 11:02 UTC
The range for `u8` does not work properly, it panics at the (valid) value 255. If this behavior is expected for bytes it should be documentated.

I tried [this code](https://play.rust-lang.org/?code=fn%20main%28%29%20%7B%0A%20%20%20%20assert_eq!%28%280u8..%29.last%28%29%2C%20Some%28255%29%29%3B%0A%7D%0A&version=stable&backtrace=1) to check correctness and it panics:
`fn main() {
    assert_eq!((0u8..).last(), Some(255));
}`

> thread 'main' panicked at 'arithmetic operation overflowed', ../src/libcore/ops.rs:211
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Rusty greedings, Christopher
#24119

**Comment by TimNN** [comment] 2016-08-11 12:32
Mh, this issue looks interesting. Frist of all, in my opinition, `(0..).last()` would always overflow / be an "endless loop" since you're trying to get the last element of an open ended sequence.

I've been trying some things and found the following "interesting behaviour":

The code `println!("{:?}", (255u8..).next());`:

* tiggers `arithmetic operation overflowed` on **stable/debug**
* causes `timeout triggered!` (playpen) on **beta/debug**
* prints `Some(255)` on **nightly/debug**
* prints `Some(255)` on __*/release__

**Comment by nagisa** [comment] 2016-08-11 22:48
> prints Some(255) on nightly/debug 

That’s amusing. I feel like overflow on debug was intentional (i.e. the stable/debug behaviour is the intended one).

**Comment by nagisa** [comment] 2016-08-11 22:51
Duplicate of https://github.com/rust-lang/rust/issues/25708 by the way, but @TimNN points out a regression, so probably shouldn’t be closed?

**Comment by Mark-Simulacrum** [comment] 2017-05-10 23:20
Looks like another regression that slipped through. cc @alexcrichton @brson; I don't know what we want to do about this issue, but if the regression is no longer a priority, it can be closed as a duplicate. Nightly output today, without release optimizations, is below. With them, it simply hangs.

```
thread 'main' panicked at 'attempt to add with overflow', /home/mark/BuildDisk/rust/src/libcore/ops.rs:264
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by nagisa** [comment] 2017-06-09 14:44
This is what the documentation for `last` has to say:

> This method will evaluate the iterator until it returns None. While doing so, it keeps track of the current element. After None is returned, last() will then return the last element it saw.

Iterator `0u8..` can never return a `None` by definition, making `last` on this iterator divergent.

The fact that `0u8..` cannot yield 255 at all is tracked at issue https://github.com/rust-lang/rust/issues/25708. Therefore closing as a duplicate.

**Closed by nagisa** 2017-06-09 14:44 UTC
Labels: T-libs
