### ISSUE TITLE
error: the trait `core::marker::Sized` is not implemented for the type `std::error::Error + Sized + 'static`

### ISSUE THREAD

**Issue by julienw** [rust-lang/rust#33201] opened 2016-04-25 16:14 UTC
The error is not easy to understand for this code:

```rust
use std::error::Error;
use std::fmt;

#[derive(Debug, Clone)]
struct SomeError {
  cause: String
}

impl fmt::Display for SomeError {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    write!(f, "SomeError")
  }
}

impl Error for SomeError {
  fn description(&self) -> &str {
    "Some Error"
  }
  
  fn cause(&self) -> Option<&Error> {
    None
  }
}

#[derive(Debug, Clone)]
enum NewError {
  SomeCause(Error + Sized)
}

fn main() {
    let error = NewError::SomeCause(SomeError { cause: "some cause".to_string() });
    println!("{:?}", error);
}
```

(it's also in https://play.rust-lang.org/?gist=3d607f7ee08c09aa7eed9720712ee129&version=stable&backtrace=0)

If I understand properly, the issue is that I should have something like this instead:
```rust
enum NewError<T: Error> {
  SomeCause(T)
}
```
But the error is very misleading.

**Comment by julienw** [comment] 2016-04-25 17:13
Full error message:
```
<anon>:25:17: 25:22 error: the trait `core::marker::Sized` is not implemented for the type `std::error::Error + Sized + 'static` [E0277]
<anon>:25 #[derive(Debug, Clone)]
                          ^~~~~
<anon>:25:17: 25:22 note: in this expansion of #[derive_Clone] (defined in <anon>)
<anon>:25:17: 25:22 help: see the detailed explanation for E0277
<anon>:25:17: 25:22 note: `std::error::Error + Sized + 'static` does not have a constant size known at compile-time
<anon>:25:17: 25:22 note: required because it appears within the type `NewError`
<anon>:25:17: 25:22 note: required by `core::clone::Clone`
error: aborting due to previous error
```

**Comment by julienw** [comment] 2016-04-25 17:16
> If I understand properly, the issue is that I should have something like this instead:

So actually the error is that I have a Trait object that's not behind a pointer (Box or ref). As a result it's not sized even though I use `+ Sized`. Maybe the error message could explain better why it doesn't have a constant size known at compile-time. (damned, every word is important :) )

**Comment by arielb1** [comment] 2016-04-26 19:57
The `+ Sized` being allowed is an implementation bug,

**Comment by arielb1** [comment] 2016-04-27 15:41
duplicate of #33243.

**Closed by arielb1** 2016-04-27 15:41 UTC

**Comment by dataf3l** [comment] 2018-05-24 22:40
@julienw can you share the example with the solution?

**Comment by julienw** [comment] 2018-05-25 09:02
I described it at the end of my initial description, but [here is the full code](https://play.rust-lang.org/?gist=fbdd75399a7e6569581c8ef826bc0531&version=stable&mode=debug)
