### ISSUE TITLE
todo!() macro doesn't work in implementations of trait methods with return position impl Trait

### ISSUE THREAD

**Issue by licynthiax** [rust-lang/rust#125097] opened 2024-05-14 00:10 UTC
Hi! When there are `impl Trait` return types in trait definitions, the todo!() macro doesn't work as expected in them:

```rust
trait Foo {}

trait Bar {
    fn x() -> impl Foo;
}

struct Baz;

impl Bar for Baz {
    fn x() -> impl Foo {
        todo!()
    }
}
```

I expect this code to compile but panic at runtime if I call `x()`, but instead I get this compile-time error:

```
error[E0277]: the trait bound `(): Foo` is not satisfied
  --> src/main.rs:10:15
   |
10 |     fn x() -> impl Foo {
   |               ^^^^^^^^ the trait `Foo` is not implemented for `()`
   |
help: this trait has no implementations, consider adding one
  --> src/main.rs:1:1
   |
1  | trait Foo {}
   | ^^^^^^^^^
```

### Meta
`rustc --version --verbose`:
```
rustc 1.77.1 (7cf61ebde 2024-03-27)
```

Backtrace: n/a (output same as above)

**Comment by fmease** [comment] 2024-05-14 01:11
Duplicate of #113875.

**Closed by fmease** 2024-05-14 01:11 UTC
Labels: C-bug, needs-triage
