### ISSUE TITLE
Nightly thread_local segment fault

### ISSUE THREAD

**Issue by cybersoulK** [rust-lang/rust#115621] opened 2023-09-06 22:55 UTC
cargo 1.73.0-nightly (45782b6b8 2023-07-05)

Cross compiled from mac with "brew install mingw-w64" (stable 11.0.1)

cargo build --release --target x86_64-pc-windows-gnu
or 
cargo build --target x86_64-pc-windows-gnu

```rust
#[derive(Clone, Copy)]
pub enum EntityIdFlag {
    Normal,
    Hash,
}
        
#[thread_local]
pub static mut ENTITY_ID_FLAG: EntityIdFlag = EntityIdFlag::Normal;
```

segment faults here. This code is run inside a secondary thread + inside a tokio::spawn clousure (with current_thread runtime) if that matters
```rust
unsafe { ENTITY_ID_FLAG = EntityIdFlag::Hash; }
```

Unhandled exception at 0x00007FF6CD5B2382 in x86_64-pc-windows-gnu.exe: 0xC0000005: Access violation writing location 0x00000263F8689AA8.

**Comment by cybersoulK** [comment] 2023-09-06 23:21
when i replaced the previous with:

```rust
thread_local! {
    pub static ENTITY_ID_FLAG: RefCell<EntityIdFlag> = RefCell::new(EntityIdFlag::Normal);
}
```

it works without segfaulting

**Comment by ChrisDenton** [comment] 2023-09-07 00:20
It may help to provide a full example program that people can try.

**Comment by ChrisDenton** [comment] 2023-09-07 01:06
Oh, it's not expected to work. The tier 1 windows gnu targets do not support native thread locals. You can test this with:

```rust
#![feature(cfg_target_thread_local)]

fn main() {
    #[cfg(target_thread_local)] println!("native tls: true");
    #[cfg(not(target_thread_local))] println!("native tls: false");
}
```

**Comment by RalfJung** [comment] 2023-09-07 07:18
> Oh, it's not expected to work. The tier 1 windows gnu targets do not support native thread locals. You can test this with:

Shouldn't they reject `#[thread_local]` on a static then, or something like that?

**Comment by ChrisDenton** [comment] 2023-09-07 09:18
You should probably ask that on the tracking issue. I'd guess it probably would be if this were stabilized.

Closing this as "working as intended" even if the intended behaviour is weird.

**Closed by ChrisDenton** 2023-09-07 09:18 UTC
Labels: T-compiler, A-thread-locals, C-discussion

**Comment by cybersoulK** [comment] 2023-09-07 09:22
a weirder thing is that the executable actually runs "sometimes". it's not a consistent segfault

**Comment by ChrisDenton** [comment] 2023-09-07 09:34
Well the host OS and binary format support TLS, you can use them with `windows-msvc` and `windows-gnullvm` targets. But mingw emulates Unix TLS in its own way so I guess it leads to incompatibilities when attempting to use native TLS but access them via mingw's runtime.
