### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by jthornber** [rust-lang/rust#36797] opened 2016-09-28 10:13 UTC
A spurious semicolon meant this function was returning () rather than some form of io::Result.  I feel the error message could have been more helpful, since the type was just plain wrong, rather than inadequately specified.

use std::fs::File;
use std::io;
use std::os::unix::io::AsRawFd;
use std::path::Path;
 
pub struct DMIoctl {
    // FIXME: automate closing the fd                                                                                                
    control_file: File
 
}
 
static IOCTL_CONTROL_PATH: &'static Path = Path::new("/dev/mapper/control");
 
impl DMIoctl {
   fn new_specifying_control<P: AsRef<Path>>(path: &P) -> io::Result<DMIoctl> {
       let i = DMIoctl { control_file: try!(File::open(path)) };
 
       // main.rs:21:9: 71:11 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required\
[E0282]
       //main.rs:21         Ok(i);
                  ^~
 
       Ok(i);
   }
 
   fn new() -> io::Result<DMIoctl> {
       Self::new_specifying_control(IOCTL_CONTROL_PATH);
   }
}

**Comment by TimNN** [comment] 2016-09-28 10:32
Duplicate of #24889.

Also, @jthornber you can get better code formatting by surrounding your code like this:


    ```rust
    // your code goes here
    ```

That example would then render as

```rust
// your code goes here
```

**Closed** 2016-09-28 13:52 UTC
