### ISSUE TITLE
Abort in rustc on valid code

### ISSUE THREAD

**Issue by jleahy** [rust-lang/rust#21767] opened 2015-01-30 02:57 UTC
This is using "rustc 1.0.0-nightly (458a6a2f6 2015-01-25 21:20:37 +0000)".

Code:

    #![start]
    #[no_mangle]
    fn main() {}

Command line:

    rustc test.rs

Error:

    test.rs:1:1: 1:10 warning: unused attribute, #[warn(unused_attributes)] on by default
    test.rs:1 #![start]
              ^~~~~~~~~
    rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
    Aborted

**Comment by klutzy** [comment] 2015-01-30 05:53
Sub-issue of #10883. (There's internal `main` function which calls `main` function provided by user, so `#[no_mangle]` causes name clash.)

**Comment by jleahy** [comment] 2015-01-30 05:58
Aha, I should have tried removing the "#![start]" to minimize it further.

**Comment by nagisa** [comment] 2015-01-30 12:29
Duplicate of #19495

**Closed** 2015-01-30 18:45 UTC
