### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\compiler\rustc_hir\src\definitions.rs:452:14

### ISSUE THREAD

**Issue by kryton** [rust-lang/rust#91835] opened 2021-12-12 17:50 UTC
### Code

```Rust
sadly it doesn't give me a line and I have no idea what happened
```

### Meta

sadly .. nightly fails on something different.
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd\compiler\rustc_serialize\src\opaque.rs:669:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd\compiler\rustc_serialize\src\opaque.rs:669:9
when trying to build packages

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
   Compiling constellation-web-socket v0.1.0 (C:\Users\ihols\pfc\constellation-web-socket)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\compiler\rustc_hir\src\definitions.rs:452:14
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
PS C:\Users\ihols\pfc\constellation> cargo run
   Compiling constellation-web-socket v0.1.0 (C:\Users\ihols\pfc\constellation-web-socket)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\compiler\rustc_hir\src\definitions.rs:452:14
stack backtrace:
   0:     0x7ff9c11092cf - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h53606b08c01ef688
   1:     0x7ff9c113306a - core::fmt::write::he97f21b785b90134
   2:     0x7ff9c10fb448 - <std::io::IoSlice as core::fmt::Debug>::fmt::h967100caef347f28
   3:     0x7ff9c110cd96 - std::panicking::take_hook::hb46205f0055becfd
   4:     0x7ff9c110c797 - std::panicking::take_hook::hb46205f0055becfd
   5:     0x7ff952f0a295 - <tracing_subscriber::fmt::writer::TestWriter as std::io::Write>::flush::hff7a705da113f4ca
   6:     0x7ff9c110d6a9 - std::panicking::rust_panic_with_hook::hce0846b912adb5c5
   7:     0x7ff9c110d11f - rust_begin_unwind
   8:     0x7ff9c1109bf7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h53606b08c01ef688
   9:     0x7ff9c110d0a9 - rust_begin_unwind
  10:     0x7ff9c1169510 - core::panicking::panic_fmt::h58715deff5969a45
  11:     0x7ff9c116945c - core::panicking::panic::hc36befec1b90302c
  12:     0x7ff95678b97e - <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id::h9f7b03ae96e81f81
  13:     0x7ff95749eeb4 - rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover::he3ec8272ca40aa05
  14:     0x7ff9566b1dad - rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node::h913d78c1ee69fb04
  15:     0x7ff95670cb34 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  16:     0x7ff95670cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  17:     0x7ff95670cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  18:     0x7ff95670cb0b - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  19:     0x7ff9566e497d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  20:     0x7ff9563cb45e - <rustc_mir_dataflow::framework::cursor::CursorPosition as core::fmt::Debug>::fmt::hdad43e681eb5eae7
  21:     0x7ff9566d3283 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  22:     0x7ff955903b93 - <rustc_typeck::check::PlaceOp as core::fmt::Debug>::fmt::h2e3c14b4c6653d68
  23:     0x7ff9558bdaf3 - rustc_typeck::check_crate::h07f2a7631cf584be
  24:     0x7ff953073e8d - rustc_interface::passes::analysis::hc0b219c9fceabc88
  25:     0x7ff95668b8eb - ZN16rustc_query_impl13on_disk_cache260_$LT$impl$u20$rustc_serialize..serialize..Decodable$LT$rustc_query_impl..on_disk_cache..CacheDecoder$GT$$u20$for$u20$$RF$std..collections..hash..set..HashSet$LT$rustc_span..def_id..LocalDefId$C$core..hash..BuildHasher
  26:     0x7ff95671c61d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  27:     0x7ff956662972 - <rustc_span::def_id::LocalDefId as rustc_query_impl::profiling_support::SpecIntoSelfProfilingString>::spec_to_self_profile_string::h641e5a6d4a18de66
  28:     0x7ff956404849 - <rustc_mir_dataflow::framework::cursor::CursorPosition as core::fmt::Debug>::fmt::hdad43e681eb5eae7
  29:     0x7ff9566ce095 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_mark_green::h79c2867594abd9a1
  30:     0x7ff952f5e59a - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::h8e44660347c50da5
  31:     0x7ff952f28944 - rustc_driver::pretty::print_after_hir_lowering::h16ae7f3f7d316762
  32:     0x7ff952f607e6 - <tracing_subscriber::util::TryInitError as core::fmt::Display>::fmt::h8e44660347c50da5
  33:     0x7ff952f2ed63 - rustc_driver::pretty::print_after_hir_lowering::h16ae7f3f7d316762
  34:     0x7ff952f89a58 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h11014d06e9af86ea
  35:     0x7ff9c1119d8c - std::sys::windows::thread::Thread::new::h4046847bccf80b57
  36:     0x7ffa21a61350 - BaseThreadInitThunk
  37:     0x7ffa23072e78 - RtlUserThreadStart

```

</p>
</details>

**Comment by kryton** [comment] 2021-12-12 17:58
correction: 
ran rustup and received new nightly, and it builds fine.

**Comment by BGR360** [comment] 2021-12-21 04:03
Potential dupe of https://github.com/rust-lang/rust/issues/91696. See also https://github.com/rust-lang/rust/pull/91919.

@rustbot label +A-incr-comp

**Comment by evgeni-nabokov** [comment] 2022-01-03 07:27
I've got the same issue. Switching to nightly toolchaing resolved the issue.

**Comment by workingjubilee** [comment] 2023-02-26 11:32
Closing assuming the previous "it's a duplicate" is correct.

**Closed** 2023-02-26 11:31 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
