### ISSUE TITLE
./x.py --help sometimes doesn't work

### ISSUE THREAD

**Issue by keeperofdakeys** [rust-lang/rust#40055] opened 2017-02-23 11:06 UTC
If x.py is in the middle of a build, or hasn't downloaded a bootstrap file, `./x.py --help` doesn't seem to work.

Eg:
```'
<^C in the middle of a build>
user@host 0 rust $ ./x.py --help
   Compiling libc v0.2.20
   Compiling rustc-serialize v0.3.22
   Compiling cmake v0.1.20
   Compiling num_cpus v0.2.13
   Compiling filetime v0.1.10
```
and
```
user@host 130 rust $ ./x.py --help
info: the build system for Rust is written in Rust, so this
      script is now going to download a stage0 rust compiler
      and then compile the build system itself

info: in the meantime you can read more about rustbuild at
      src/bootstrap/README.md before the download finishes
downloading https://static.rust-lang.org/dist/2017-02-01/rust-std-beta-x86_64-unknown-linux-gnu.tar.gz
#####                                                                      7.1%
```

**Comment by petrochenkov** [comment] 2017-02-23 11:11
Duplicate of https://github.com/rust-lang/rust/issues/37305

**Comment by keeperofdakeys** [comment] 2017-02-23 11:24
Ah, I didn't find it when I did a search. I might close this one then.

**Closed** 2017-02-23 11:24 UTC
