### ISSUE TITLE
build-std seems broken in nightly (rustc 1.71.0-nightly (74c482104 2023-05-04))

### ISSUE THREAD

**Issue by gamozolabs** [rust-lang/rust#111225] opened 2023-05-05 01:30 UTC
When I attempt to build (seemingly anything) with `-Zbuild-std=core` on nightly I get an error with package `test` not having the feature `backtrace`.

This seems to affect a random sampling of targets I picked, it seems more fundamental than that:

```
pleb@gamey ~/regression $ cat src/main.rs 
```

```rust

#![no_std]
#![no_main]

#[panic_handler]
fn panic(pi: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[no_mangle]
extern fn efi_main() {
}
```

```
pleb@gamey ~/regression $ cat Cargo.toml 
[package]
name = "regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pleb@gamey ~/regression $ cargo build --target powerpc-unknown-freebsd -Zbuild-std=core
error: Package `test v0.0.0 (/home/pleb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have the feature `backtrace`
pleb@gamey ~/regression $ cargo build --target x86_64-unknown-none -Zbuild-std=core
error: Package `test v0.0.0 (/home/pleb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have the feature `backtrace`
pleb@gamey ~/regression $ cargo build --target x86_64-unknown-uefi -Zbuild-std=core
error: Package `test v0.0.0 (/home/pleb/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have the feature `backtrace`
```

**Comment by jyn514** [comment] 2023-05-05 02:45
Probably caused by https://github.com/rust-lang/rust/pull/108865

**Comment by mqudsi** [comment] 2023-05-06 00:55
Yes, #108865 is the one behind this. It should be fixed by https://github.com/rust-lang/cargo/pull/12088, probably in the next nightly build.

**Comment by ehuss** [comment] 2023-05-06 02:37
I believe this is now fixed in the latest nightly.

**Closed by ehuss** 2023-05-06 02:37 UTC
Labels: regression-from-stable-to-nightly, requires-nightly, -Zbuild-std
