### ISSUE TITLE
regression: parameter type may not live long enough

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123280] opened 2024-03-31 17:08 UTC
```
[INFO] [stdout] error[E0310]: the parameter type `EWA` may not live long enough
[INFO] [stdout]    --> src/worker_pool.rs:109:1
[INFO] [stdout]     |
[INFO] [stdout] 109 | / {
[INFO] [stdout] 110 | |     let mut handle_vec = Vec::with_capacity(default_worker);
[INFO] [stdout] 111 | |
[INFO] [stdout] 112 | |     let mut worker_sender_vec = Vec::with_capacity(default_worker);
[INFO] [stdout] ...   |
[INFO] [stdout] 128 | |     }
[INFO] [stdout] 129 | | }
[INFO] [stdout]     | | ^
[INFO] [stdout]     | | |
[INFO] [stdout]     | |_the parameter type `EWA` must be valid for the static lifetime...
[INFO] [stdout]     |   ...so that the type `EWA` will meet its required lifetime bounds
[INFO] [stdout]     |
[INFO] [stdout] help: consider adding an explicit lifetime bound
[INFO] [stdout]     |
[INFO] [stdout] 108 |     EWA: Clone + 'static,
[INFO] [stdout]     |                +++++++++
```

Smells similar to https://github.com/rust-lang/rust/issues/123279, but maybe not.

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/shishanyue.RW-RJR-Server/log.txt

**Comment by compiler-errors** [comment] 2024-04-01 03:19
searched toolchains b6d2d841bcf4b77343b159f134c7d39c2dd4ceaa through 7d3702e472b99be0f5de6608dd87af1df8f99428


********************************************************************************
Regression in 09bc67b9158392361780e779d32997f14cc75c39
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment

searched nightlies: from nightly-2024-02-01 to nightly-2024-04-01
regressed nightly: nightly-2024-03-07
searched commit range: https://github.com/rust-lang/rust/compare/b6d2d841bcf4b77343b159f134c7d39c2dd4ceaa...7d3702e472b99be0f5de6608dd87af1df8f99428
regressed commit: https://github.com/rust-lang/rust/commit/09bc67b9158392361780e779d32997f14cc75c39

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2024-02-01 
```
</details>

**Comment by compiler-errors** [comment] 2024-04-01 03:20
I can't tell upon a quick search whether this was an expected regression from #121679/#115008. cc @lcnr @aliemjay

**Comment by aliemjay** [comment] 2024-04-01 03:47
This is expected. This is the culprit bound:
https://github.com/shishanyue/RW-RJR-Server/blob/0343d1021fbbd3282e29377491b531d5a7bc98eb/src/worker_pool.rs#L23

Minimized:
```rust
struct WorkerPool<D: 'static>(Option<D>);

fn new_worker_pool<D>() -> impl Sized {
    async {
        WorkerPool(None::<D>)
    }
}
```

What is annoying though is the error span which points to the entire async block because, when inside the async block, we draw implied bounds from its output type, allowing us to assume `D: 'static`, which then fails to be proven in the parent fn. See #115173 for a partial fix.

**Comment by aliemjay** [comment] 2024-04-01 03:55
Ironically, this is accepted now nad since forever because the rvalue never get the chance to be checked for well-formedness:
```rust
struct WorkerPool<D: 'static>(Option<D>);

fn new_worker_pool<D>() {
    let _ = async {
        WorkerPool(None::<D>)
    };
}
```

**Comment by lcnr** [comment] 2024-04-02 01:32
closing as expected and we have provided a PR to fix the issue

**Closed by lcnr** 2024-04-02 01:32 UTC
Labels: T-compiler, regression-from-stable-to-beta, I-prioritize, needs-triage

**Comment by apiraino** [comment] 2024-04-02 11:22
@aliemjay @lcnr anything here that should be noted in the release notes?

**Comment by lcnr** [comment] 2024-04-02 11:49
added a comment to https://github.com/rust-lang/rust/pull/121679#issuecomment-2031832823
