### ISSUE TITLE
std::rc::Rc should accept DST

### ISSUE THREAD

**Issue by little-arhat** [rust-lang/rust#18248] opened 2014-10-23 07:33 UTC
It's currently impossible to store DST (Trait object, for example) inside RC:

```
let x:std::rc::Rc<Reader>;
```

gives you: `the trait 'core::kinds::Sized' must be implemented because it is required by 'alloc::rc::Rc'`. However, you can store trait object inside `Box`. `Rc` uses `Box` internally, so it seems inconsistent that one cannot use refcounted box as replacement for `Box`.

One could work around this issue by storing `Box<Trait>` inside `Rc`, but that would incur double indirection. 

Moreover, one couldn't implement their own `Rc` because of related ICE: #17959 .

(Maybe related to: #16918 )

**Comment by steveklabnik** [comment] 2015-02-16 22:49
This also impacts using closures, since they're trait objects.

**Comment by aepsil0n** [comment] 2015-02-20 16:16
Shouldn't this include `std::sync::Arc`? Or would that be a separate PR?

**Comment by steveklabnik** [comment] 2015-02-20 16:17
It could be the same, the root cause is the same.

**Comment by nrc** [comment] 2015-03-16 01:37
There are two pieces missing here: we need coercions of deeply DST objects in order to create `Rc<T>` and we need to handle `drop` - the latter uses a bunch of functions, mainly `size_of` which don't accept `?Sized` type params. The rest is just adding `?Sized` in a bunch of places (which I have on a branch).

I'm working on spec'ing then implementing the DST coercions atm. I guess #19063 will cover everything that needs doing to implement `drop`, but I haven't checked that.

`Arc` has exactly the same issues as `Rc` (drop and coercions).

**Comment by japaric** [comment] 2015-04-02 01:20
FWIW, I have an [out of tree implementation] of `Rc` that works with DST. I've mainly tested `Rc<str>` and `Rc<Fn(A, B) -> C>` and valgrind seems to be happy with it.

My implementation only supports strong references [1] and uses a different [data layout] than the one in libstd, which results in a simple implementation of the [constructor] and the [destructor]. I have also [documented] the (re)allocations that each constructor/conversion (e.g. `String` -> `Rc<str>`) may require.

[1] I didn't implement weak references because (I think) I don't need them (yet) for what I'm using the `Rc` for (I don't have to deal with cyclic structures, or have `RefCell`s in my code which AFAIK are required to create them)
[out of tree implementation]: https://github.com/japaric/rc.rs
[data layout]: https://github.com/japaric/rc.rs/blob/c7f3b2ddc6a6c9598f44ec99a511dab5d783eb01/src/lib.rs#L85-90
[constructor]: https://github.com/japaric/rc.rs/blob/c7f3b2ddc6a6c9598f44ec99a511dab5d783eb01/src/lib.rs#L156-167
[destructor]: https://github.com/japaric/rc.rs/blob/c7f3b2ddc6a6c9598f44ec99a511dab5d783eb01/src/lib.rs#L198-213
[documented]: http://japaric.github.io/rc.rs/rc/struct.Rc.html

**Comment by huonw** [comment] 2015-04-02 01:34
@japaric cool! Although, fwiw, that sort of pointer (with separate allocation for the refcounts) almost exists today via `Rc<Box<T>>`.

**Comment by japaric** [comment] 2015-04-02 02:31
> that sort of pointer (with separate allocation for the refcounts) almost exists today via Rc<Box<T>>.

Yes, but that one has double indirection, it's like `Box<Box<Trait>>` and `Box<String>`. Each call to `deref` has to go through one layer of indirection.

**Comment by huonw** [comment] 2015-04-02 02:37
Yeah, hence "almost". :)

**Comment by P1start** [comment] 2015-05-15 23:52
I believe this was fixed in #24619.

**Comment by alexcrichton** [comment] 2015-05-15 23:58
Yay!

**Closed by alexcrichton** 2015-05-15 23:58 UTC
Labels: A-dst, A-libs

**Comment by Eh2406** [comment] 2017-09-03 20:56
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/libcore/tests/hash/mod.rs#L72
Now that the issue is closed can the FIXME be fix, or made more specific?
