### ISSUE TITLE
cargo test gives up compiling after one error

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#64084] opened 2019-09-02 04:24 UTC
I'm making a big refactor. When attempting to clean up my tests, `cargo test` appears to go file by file, alphabetically when compiling the tests. As soon as one `#[test]` has a compile error, the build is aborted.

- `#[test]`s following the failure do not get compiled.
- Subsequent compile errors in the `#[test]` that fails to build are not reported.

This makes finding errors very tedious.

---

Editing to provide concrete case:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c040edc58966f3fcc662002e84ec57aa gives up after the first test but should continue to report errors

**Comment by Mark-Simulacrum** [comment] 2019-09-02 04:42
What error specifically? Can you post a build log and a link to a repo (or, ideally, playground) that reproduces this behavior?

**Comment by lopopolo** [comment] 2019-09-02 04:49
I know there are errors in the build. The problem is that cargo test stops compiling all of the tests once it encounters a single error.

**Comment by lopopolo** [comment] 2019-09-02 04:50
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=450dae1a87d178bafe63d854f70a02b0

**Comment by lopopolo** [comment] 2019-09-02 05:01
@Mark-Simulacrum This playground gives up after compiling `foo` test:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c040edc58966f3fcc662002e84ec57aa

**Comment by Mark-Simulacrum** [comment] 2019-09-02 12:49
This has nothing to do with tests and is just a consequence of how type inference errors are currently fatal in this case. Removing the `#[test]` annotations leads to the exact same error.

I'm going to close this issue as it's not really something that's fixable (well, it is, but not a targeted fix, and there's no real need to track this case separately). Thanks for the bug report, though!

**Comment by lopopolo** [comment] 2019-09-02 16:23
Is there a big for the broader issue that I can watch?

**Comment by Mark-Simulacrum** [comment] 2019-09-02 17:16
Not really in the sense that it's not a bug just a consequence of the current implementation.

**Closed** 2019-09-25 05:53 UTC
Labels: A-diagnostics, A-traits, C-enhancement, T-compiler
