### ISSUE TITLE
Setting O_NONBLOCK on stdin causes application to crash

### ISSUE THREAD

**Issue by retep007** [rust-lang/rust#66055] opened 2019-11-03 14:04 UTC
After setting stdin to nonblocking (instead of waiting returns error EAGAIN) cause program to crash without any reported error.

E.g `fcntl(0, FcntlArg::F_SETFL(OFlag::O_NONBLOCK))?;`

That wouldn't be so surprising since rust doesn't really support non-blocking I/O. However, more surprising fact is that it even crashes when writing to stdout without touching stdin at all.

<details>
<summary>Expand</summary>

``` rust
use failure::Error;
use nix::fcntl::fcntl;
use nix::fcntl::FcntlArg;
use nix::fcntl::OFlag;
use nix::poll::poll;
use nix::poll::PollFd;
use nix::poll::PollFlags;
use nix::unistd::dup2;
use nix::unistd::execv;
use nix::unistd::pipe;
use nix::unistd::read;
use nix::unistd::write;
use nix::unistd::{fork, ForkResult};
use std::ffi::CString;
use std::io::Read;
use std::io::Write;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

const BUF_SIZE_BYTES: usize = 8 * 1024;


pub fn main() -> Result<(), Error> {
    let (parent_read, child_write) = pipe()?;
    let (child_read, parent_write) = pipe()?;
    fcntl(parent_read, FcntlArg::F_SETFL(OFlag::O_NONBLOCK))?;
    fcntl(0, FcntlArg::F_SETFL(OFlag::O_NONBLOCK))?;

    let should_terminate: Arc<AtomicBool> = Arc::new(AtomicBool::new(false));
    let r = should_terminate.clone();

    ctrlc::set_handler(move || {
        debug!("received Ctrl+C!");
        if r.load(Ordering::SeqCst) {
            debug!("received Ctrl+C second time");
            info!("Ungraceful exit");
            std::process::exit(1);
        }
        r.store(true, Ordering::SeqCst);
    })?;

    match fork()? {
        ForkResult::Parent { child: _ } => {
            let mut flags = PollFlags::all();
            flags.remove(PollFlags::POLLOUT);
            flags.remove(PollFlags::POLLWRNORM);
            flags.remove(PollFlags::POLLWRBAND);
            let read_poold = PollFd::new(child_write, flags);
            let mut read_buf = [0; BUF_SIZE_BYTES];

            let _write_poold = PollFd::new(parent_write, PollFlags::all());
            let mut write_buf = [0; BUF_SIZE_BYTES];

            let stdin_poold = PollFd::new(0, flags);
            let mut stdout = std::io::stdout();
            debug!("{}", flags.bits());
            loop {
                poll(&mut [read_poold, stdin_poold], -1)?;
                debug!("Received interrupt");
                // Wait for either read or write availability
                if should_terminate.load(Ordering::SeqCst) {
                    write(parent_write, b"exit")?;
                    debug!("Child stopped");
                    break;
                }
                while {
                    debug!("Attempting read");
                    let bytes_read = read(parent_read, &mut read_buf);
                    match bytes_read {
                        Ok(bytes_read) => {
                            debug!("Read {} byes from child, writing to stdout", bytes_read);
// CRASHES HERE
                            stdout.write_all(&read_buf[0..bytes_read-1])?;
                            stdout.flush()?;
                            debug!("Done writing read data to parent stdout");
                            bytes_read != 0
                        }
                        err@Err(nix::Error::Sys(nix::errno::Errno::EAGAIN)) => {
                            debug!("Reading failed with {:?}, trying again later", err);
                            false
                        }
                        Err(err) => {
                            return Err(err.into());
                        }
                    }
                } {
                    debug!("reading...");
                }

            }
        }
        ForkResult::Child => run_child(child_write, child_read)?,
    }
    Ok(())
}

fn run_child(write_fd: i32, read_fd: i32) -> Result<(), Error> {
    debug!("Runnig child");
    dup2(read_fd, 0)?;
    dup2(write_fd, 1)?;
    execv(
        &CString::new("/usr/bin/ssh").unwrap(),
        &[
            CString::new("ssh").unwrap(),
            CString::new("host").unwrap(),
            CString::new("-T").unwrap(),
        ],
    )?;
    Ok(())
}
```
</details>

Now fix to this is questionable. Even documenting this behaviour could be enough or alternatively properly handle non-blocking files

**Comment by sfackler** [comment] 2019-11-03 15:43
Can you be more specific about what exactly the "crash" is?

**Comment by retep007** [comment] 2019-11-03 17:27
Process exits with 101, with no error message. I've tried dbg! macro and it experiences the same problem after printing a few characters program crashes
<details>
<summary>Expand</summary>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
 DEBUG crabbox::rcrab > 251
 DEBUG crabbox::rcrab > Runnig child

 DEBUG crabbox::rcrab > Received interrupt
 DEBUG crabbox::rcrab > Attempting read
 DEBUG crabbox::rcrab > Read 1675 byes from child, writing to stdout
[src/rcrab.rs:72] &read_buf[0..bytes_read ] = [
    87,
    101,
    108,
    99,
    111,
    109,
    101,
    32,
    116,
    111,
    32,
    85,
    98,
    117,
    110,
    116,
    117,
    32,
52,
    46,
    49,
    53,
    46,
    50,
    45,
    48,
    52,
    49,
    53,
    48,
    50,
    45,
    103,
    101,
    110,
    101,
    114,
    105,
    99,
    32,
    120,
    56,
    54,
    95,
    54,
    52,
    41,
    10,
    10,
    32,
    42,
    32,
    68,
    111,
    99,
    117,
    109,
thread '% 
```
</details>

**Comment by sfackler** [comment] 2019-11-03 17:41
I can't reproduce that, though I don't have the ability to ssh into that host if relevant. This issue tracker is not a general support forum. Posting on e.g. reddit.com/r/rust or users.rust-lang.org is a better place for these kind of more general questions.

**Comment by Mark-Simulacrum** [comment] 2019-12-06 18:56
Closing as we can't reproduce. If you can provide a backtrace or other details, we can reopen, but otherwise users/reddit as suggested are indeed better forums. Thanks!

**Closed by Mark-Simulacrum** 2019-12-06 18:56 UTC
