### ISSUE TITLE
error: internal compiler error: src/librustc/ty/context.rs:513: node_type: no type for node `expr 8 (hir_id=HirId { owner: DefIndex(3061), local_id: 87 })`

### ISSUE THREAD

**Issue by XVilka** [rust-lang/rust#64889] opened 2019-09-29 06:38 UTC
Running `cargo clippy` on a [scryer-prolog]() Rust project with a latest master (commit https://github.com/mthom/scryer-prolog/commit/5ec4dfedb0f7f2440316dc02792869ca45b91df0) checkout makes compiler fail:
```
scryer-prolog on  master took 26s 
[i] ℤ RUST_BACKTRACE=full cargo clippy --verbose                                                                                                                                                                     14:34:32 via 𝗥 v1.39.0 
       Fresh semver-parser v0.7.0
       Fresh cfg-if v0.1.10
       Fresh autocfg v0.1.6
       Fresh void v1.0.2
       Fresh nodrop v0.1.13
       Fresh static_assertions v0.3.4
       Fresh numtoa v0.1.0
       Fresh unicode-width v0.1.6
       Fresh utf8parse v0.1.1
       Fresh unicode-segmentation v1.3.0
       Fresh downcast v0.10.0
       Fresh indexmap v1.2.0
       Fresh ref_thread_local v0.0.0
       Fresh semver v0.9.0
       Fresh unreachable v1.0.0
       Fresh libc v0.2.62
       Fresh rustc_version v0.2.3
       Fresh ryu v1.0.0
       Fresh arrayvec v0.4.11
       Fresh bitflags v1.2.0
       Fresh log v0.4.8
       Fresh memchr v2.2.1
       Fresh num-traits v0.2.8
       Fresh dirs-sys v0.3.4
       Fresh nix v0.14.1
       Fresh termion v1.5.3
       Fresh num-traits v0.1.43
       Fresh dirs v2.0.2
       Fresh lexical-core v0.4.6
       Fresh ordered-float v0.5.2
       Fresh rustyline v5.0.3
       Fresh lexical v2.2.2
       Fresh gmp-mpfr-sys v1.1.14
    Checking rug v1.6.0
     Running `/home/akochkov/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --edition=2018 --crate-name rug /home/akochkov/.cargo/registry/src/github.com-1ecc6299db9ec823/rug-1.6.0/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="complex"' --cfg 'feature="default"' --cfg 'feature="float"' --cfg 'feature="gmp-mpfr-sys"' --cfg 'feature="integer"' --cfg 'feature="rand"' --cfg 'feature="rational"' -C metadata=0f596f6f482a1c66 -C extra-filename=-0f596f6f482a1c66 --out-dir /home/akochkov/prolog/scryer-prolog/target/debug/deps -L dependency=/home/akochkov/prolog/scryer-prolog/target/debug/deps --extern gmp_mpfr_sys=/home/akochkov/prolog/scryer-prolog/target/debug/deps/libgmp_mpfr_sys-59418c005e571e7a.rmeta --cap-lints allow --cfg try_from --cfg maybe_uninit --cfg gmp_limb_bits_64 -L native=/home/akochkov/prolog/scryer-prolog/target/debug/build/gmp-mpfr-sys-7213e6610a5ac6cc/out/lib`
error: internal compiler error: src/librustc/ty/context.rs:513: node_type: no type for node `expr 8 (hir_id=HirId { owner: DefIndex(3061), local_id: 87 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:812:9
stack backtrace:
   0:     0x7fcde7a1bae4 - backtrace::backtrace::libunwind::trace::hc496b60554206774
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x7fcde7a1bae4 - backtrace::backtrace::trace_unsynchronized::ha20a82d0af0c65c5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x7fcde7a1bae4 - std::sys_common::backtrace::_print_fmt::h41aff515dcee7039
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x7fcde7a1bae4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9cece4375f2f7fda
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x7fcde7a5412c - core::fmt::write::hecb5092b1fa0aafc
                               at src/libcore/fmt/mod.rs:1030
   5:     0x7fcde7a0fd07 - std::io::Write::write_fmt::h3a49fae144e74a2a
                               at src/libstd/io/mod.rs:1412
   6:     0x7fcde7a20315 - std::sys_common::backtrace::_print::h24134367c784cf37
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x7fcde7a20315 - std::sys_common::backtrace::print::ha95f6cb55d52824a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7fcde7a20315 - std::panicking::default_hook::{{closure}}::hf48b3987cc8265dd
                               at src/libstd/panicking.rs:196
   9:     0x7fcde7a20006 - std::panicking::default_hook::h6d285b42ab8557a8
                               at src/libstd/panicking.rs:210
  10:     0x7fcde7f55f83 - rustc_driver::report_ice::h45cf923dd58ab6c9
  11:     0x7fcde7a20afc - std::panicking::rust_panic_with_hook::h694c05b962beffa6
                               at src/libstd/panicking.rs:477
  12:     0x7fcde9d121fd - std::panicking::begin_panic::h46d3b006bb005b25
  13:     0x7fcde9d2b563 - rustc_errors::HandlerInner::bug::hcc4f7785c0bbe624
  14:     0x7fcde9d2a44a - rustc_errors::Handler::bug::hab74f2c21f11224d
  15:     0x7fcde95c76b3 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h6fc69d466ad28204
  16:     0x7fcde95c7183 - rustc::ty::context::tls::with_opt::{{closure}}::hfca6eae075a58800
  17:     0x7fcde95c6e53 - rustc::ty::context::tls::with_context_opt::hb524b2b02be1c26b
  18:     0x7fcde95c6e97 - rustc::ty::context::tls::with_opt::hd739a53bdacc1686
  19:     0x7fcde95c75c8 - rustc::util::bug::opt_span_bug_fmt::h7313400faf0ca111
  20:     0x7fcde95c7532 - rustc::util::bug::bug_fmt::hd38ca659e7f5fbf2
  21:     0x7fcde97bc2ed - rustc::ty::context::TypeckTables::node_type::{{closure}}::h45cfcdea8892a145
  22:     0x7fcde97bc8de - rustc::ty::context::TypeckTables::expr_ty::hdbc326f824822726
  23:     0x5568289f95f0 - clippy_lints::consts::ConstEvalLateContext::expr::h476dcfba85a16648
  24:     0x5568288efd03 - clippy_lints::utils::is_integer_const::h5d8f4fd63c6ca9be
  25:     0x55682890c5a5 - <clippy_lints::misc::MiscLints as rustc::lint::LateLintPass>::check_expr::haa042ea7cfedf4ca
  26:     0x7fcde93d2973 - <rustc::lint::context::LateLintPassObjects as rustc::lint::LateLintPass>::check_expr::h92fc9b6d5ac04045
  27:     0x7fcde80abb01 - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  28:     0x7fcde803fb56 - rustc::hir::intravisit::walk_expr::h22863d0f325bad4d
  29:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  30:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  31:     0x7fcde803f98f - rustc::hir::intravisit::walk_expr::h22863d0f325bad4d
  32:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  33:     0x7fcde80ac5b4 - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_nested_body::h30c84ae9e6e13e52
  34:     0x7fcde80abf8c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_local::h55de7e8fa8cea3cd
  35:     0x7fcde8039f9c - rustc::hir::intravisit::walk_block::h43c16f0d67fe242b
  36:     0x7fcde803f9fe - rustc::hir::intravisit::walk_expr::h22863d0f325bad4d
  37:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  38:     0x7fcde80ac5b4 - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_nested_body::h30c84ae9e6e13e52
  39:     0x7fcde804075e - rustc::hir::intravisit::walk_item::h95848141061b61dd
  40:     0x7fcde80bb221 - rustc::hir::intravisit::Visitor::visit_nested_item::hea2c814b2f7155c8
  41:     0x7fcde803a25e - rustc::hir::intravisit::walk_crate::he664d7e3ca6f8268
  42:     0x7fcde80bf617 - rustc::lint::context::late_lint_pass_crate::h12558ee0f7c1b24a
  43:     0x7fcde80beb5e - rustc::lint::context::late_lint_crate::h649fac40252f6658
  44:     0x7fcde8042853 - rustc::util::common::time::h19fe295c62a0d841
  45:     0x7fcde8043cdb - rustc::util::common::time::h78af02ba11ad31c0
  46:     0x7fcde7a3124a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  47:     0x7fcde7fc74d3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6e79df7223bdcbe5
  48:     0x7fcde7a3124a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  49:     0x7fcde804ae52 - rustc_interface::passes::analysis::{{closure}}::hf11984d88e167908
  50:     0x7fcde8043230 - rustc::util::common::time::h445708af66271f8e
  51:     0x7fcde8005584 - rustc_interface::passes::analysis::h8a47af605888fc80
  52:     0x7fcde7eee851 - rustc::ty::query::__query_compute::analysis::hb9ae680a51f13bb9
  53:     0x7fcde7efe17e - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h751f86f55fa3f327
  54:     0x7fcde7f2140a - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::h24275668f616227f
  55:     0x7fcde8081aaa - rustc_interface::passes::create_global_ctxt::{{closure}}::h279ea41337b1550b
  56:     0x7fcde7f236be - rustc_interface::interface::run_compiler_in_existing_thread_pool::h8f7b1ed446f84b95
  57:     0x7fcde7f57ce2 - std::thread::local::LocalKey<T>::with::h307a7a354e416993
  58:     0x7fcde7f5d8ae - scoped_tls::ScopedKey<T>::set::h2f6a18a3def76ab5
  59:     0x7fcde7f7e0a2 - syntax::with_globals::h1fcbc798c727ae20
  60:     0x7fcde7f13310 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a2ca6bd7bcfc1d4
  61:     0x7fcde7a3124a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  62:     0x7fcde7f14939 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h560e3eeff12b2618
  63:     0x7fcde7a021ef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbf2f21e18d2cee36
                               at /rustc/6ef275e6c3cb1384ec78128eceeb4963ff788dca/src/liballoc/boxed.rs:922
  64:     0x7fcde7a2fef0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h680214b55e06abc5
                               at /rustc/6ef275e6c3cb1384ec78128eceeb4963ff788dca/src/liballoc/boxed.rs:922
  65:     0x7fcde7a2fef0 - std::sys_common::thread::start_thread::ha3ffac07979d9757
                               at src/libstd/sys_common/thread.rs:13
  66:     0x7fcde7a2fef0 - std::sys::unix::thread::Thread::new::thread_start::hbce32216c8c0810e
                               at src/libstd/sys/unix/thread.rs:79
  67:     0x7fcde79535a2 - start_thread
  68:     0x7fcde7866023 - __clone
  69:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (6ef275e6c 2019-09-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread 'rustc' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x7fcde7a1bae4 - backtrace::backtrace::libunwind::trace::hc496b60554206774
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x7fcde7a1bae4 - backtrace::backtrace::trace_unsynchronized::ha20a82d0af0c65c5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x7fcde7a1bae4 - std::sys_common::backtrace::_print_fmt::h41aff515dcee7039
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x7fcde7a1bae4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9cece4375f2f7fda
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x7fcde7a5412c - core::fmt::write::hecb5092b1fa0aafc
                               at src/libcore/fmt/mod.rs:1030
   5:     0x7fcde7a0fd07 - std::io::Write::write_fmt::h3a49fae144e74a2a
                               at src/libstd/io/mod.rs:1412
   6:     0x7fcde7a20315 - std::sys_common::backtrace::_print::h24134367c784cf37
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x7fcde7a20315 - std::sys_common::backtrace::print::ha95f6cb55d52824a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7fcde7a20315 - std::panicking::default_hook::{{closure}}::hf48b3987cc8265dd
                               at src/libstd/panicking.rs:196
   9:     0x7fcde7a20006 - std::panicking::default_hook::h6d285b42ab8557a8
                               at src/libstd/panicking.rs:210
  10:     0x7fcde7f55f83 - rustc_driver::report_ice::h45cf923dd58ab6c9
  11:     0x7fcde7a20afc - std::panicking::rust_panic_with_hook::h694c05b962beffa6
                               at src/libstd/panicking.rs:477
  12:     0x7fcde7a205b2 - std::panicking::continue_panic_fmt::h6d9edb7f6134fa29
                               at src/libstd/panicking.rs:380
  13:     0x7fcde7a204a6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  14:     0x7fcde7a4daba - core::panicking::panic_fmt::h06aa024bca353ba1
                               at src/libcore/panicking.rs:85
  15:     0x7fcde7a4dcf7 - core::result::unwrap_failed::hef0e5f380db2d8ff
                               at src/libcore/result.rs:1165
  16:     0x7fcde9d2ae05 - rustc_errors::Handler::force_print_diagnostic::h7bc5ce1adc02a5e1
  17:     0x7fcde9609061 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::try_print_query_stack::h1f63bbe074ec7299
  18:     0x7fcde7f56b95 - rustc_driver::report_ice::h45cf923dd58ab6c9
  19:     0x7fcde7a20afc - std::panicking::rust_panic_with_hook::h694c05b962beffa6
                               at src/libstd/panicking.rs:477
  20:     0x7fcde9d121fd - std::panicking::begin_panic::h46d3b006bb005b25
  21:     0x7fcde9d2b563 - rustc_errors::HandlerInner::bug::hcc4f7785c0bbe624
  22:     0x7fcde9d2a44a - rustc_errors::Handler::bug::hab74f2c21f11224d
  23:     0x7fcde95c76b3 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h6fc69d466ad28204
  24:     0x7fcde95c7183 - rustc::ty::context::tls::with_opt::{{closure}}::hfca6eae075a58800
  25:     0x7fcde95c6e53 - rustc::ty::context::tls::with_context_opt::hb524b2b02be1c26b
  26:     0x7fcde95c6e97 - rustc::ty::context::tls::with_opt::hd739a53bdacc1686
  27:     0x7fcde95c75c8 - rustc::util::bug::opt_span_bug_fmt::h7313400faf0ca111
  28:     0x7fcde95c7532 - rustc::util::bug::bug_fmt::hd38ca659e7f5fbf2
  29:     0x7fcde97bc2ed - rustc::ty::context::TypeckTables::node_type::{{closure}}::h45cfcdea8892a145
  30:     0x7fcde97bc8de - rustc::ty::context::TypeckTables::expr_ty::hdbc326f824822726
  31:     0x5568289f95f0 - clippy_lints::consts::ConstEvalLateContext::expr::h476dcfba85a16648
  32:     0x5568288efd03 - clippy_lints::utils::is_integer_const::h5d8f4fd63c6ca9be
  33:     0x55682890c5a5 - <clippy_lints::misc::MiscLints as rustc::lint::LateLintPass>::check_expr::haa042ea7cfedf4ca
  34:     0x7fcde93d2973 - <rustc::lint::context::LateLintPassObjects as rustc::lint::LateLintPass>::check_expr::h92fc9b6d5ac04045
  35:     0x7fcde80abb01 - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  36:     0x7fcde803fb56 - rustc::hir::intravisit::walk_expr::h22863d0f325bad4d
  37:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  38:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  39:     0x7fcde803f98f - rustc::hir::intravisit::walk_expr::h22863d0f325bad4d
  40:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  41:     0x7fcde80ac5b4 - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_nested_body::h30c84ae9e6e13e52
  42:     0x7fcde80abf8c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_local::h55de7e8fa8cea3cd
  43:     0x7fcde8039f9c - rustc::hir::intravisit::walk_block::h43c16f0d67fe242b
  44:     0x7fcde803f9fe - rustc::hir::intravisit::walk_expr::h22863d0f325bad4d
  45:     0x7fcde80abb0c - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_expr::h12cebf9c1cf2cad7
  46:     0x7fcde80ac5b4 - <rustc::lint::context::LateContextAndPass<T> as rustc::hir::intravisit::Visitor>::visit_nested_body::h30c84ae9e6e13e52
  47:     0x7fcde804075e - rustc::hir::intravisit::walk_item::h95848141061b61dd
  48:     0x7fcde80bb221 - rustc::hir::intravisit::Visitor::visit_nested_item::hea2c814b2f7155c8
  49:     0x7fcde803a25e - rustc::hir::intravisit::walk_crate::he664d7e3ca6f8268
  50:     0x7fcde80bf617 - rustc::lint::context::late_lint_pass_crate::h12558ee0f7c1b24a
  51:     0x7fcde80beb5e - rustc::lint::context::late_lint_crate::h649fac40252f6658
  52:     0x7fcde8042853 - rustc::util::common::time::h19fe295c62a0d841
  53:     0x7fcde8043cdb - rustc::util::common::time::h78af02ba11ad31c0
  54:     0x7fcde7a3124a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  55:     0x7fcde7fc74d3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6e79df7223bdcbe5
  56:     0x7fcde7a3124a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  57:     0x7fcde804ae52 - rustc_interface::passes::analysis::{{closure}}::hf11984d88e167908
  58:     0x7fcde8043230 - rustc::util::common::time::h445708af66271f8e
  59:     0x7fcde8005584 - rustc_interface::passes::analysis::h8a47af605888fc80
  60:     0x7fcde7eee851 - rustc::ty::query::__query_compute::analysis::hb9ae680a51f13bb9
  61:     0x7fcde7efe17e - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::h751f86f55fa3f327
  62:     0x7fcde7f2140a - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::h24275668f616227f
  63:     0x7fcde8081aaa - rustc_interface::passes::create_global_ctxt::{{closure}}::h279ea41337b1550b
  64:     0x7fcde7f236be - rustc_interface::interface::run_compiler_in_existing_thread_pool::h8f7b1ed446f84b95
  65:     0x7fcde7f57ce2 - std::thread::local::LocalKey<T>::with::h307a7a354e416993
  66:     0x7fcde7f5d8ae - scoped_tls::ScopedKey<T>::set::h2f6a18a3def76ab5
  67:     0x7fcde7f7e0a2 - syntax::with_globals::h1fcbc798c727ae20
  68:     0x7fcde7f13310 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a2ca6bd7bcfc1d4
  69:     0x7fcde7a3124a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  70:     0x7fcde7f14939 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h560e3eeff12b2618
  71:     0x7fcde7a021ef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbf2f21e18d2cee36
                               at /rustc/6ef275e6c3cb1384ec78128eceeb4963ff788dca/src/liballoc/boxed.rs:922
  72:     0x7fcde7a2fef0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h680214b55e06abc5
                               at /rustc/6ef275e6c3cb1384ec78128eceeb4963ff788dca/src/liballoc/boxed.rs:922
  73:     0x7fcde7a2fef0 - std::sys_common::thread::start_thread::ha3ffac07979d9757
                               at src/libstd/sys_common/thread.rs:13
  74:     0x7fcde7a2fef0 - std::sys::unix::thread::Thread::new::thread_start::hbce32216c8c0810e
                               at src/libstd/sys/unix/thread.rs:79
  75:     0x7fcde79535a2 - start_thread
  76:     0x7fcde7866023 - __clone
  77:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (6ef275e6c 2019-09-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
error: could not compile `rug`.

Caused by:
  process didn't exit successfully: `/home/akochkov/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --edition=2018 --crate-name rug /home/akochkov/.cargo/registry/src/github.com-1ecc6299db9ec823/rug-1.6.0/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata -C debuginfo=2 --cfg 'feature="complex"' --cfg 'feature="default"' --cfg 'feature="float"' --cfg 'feature="gmp-mpfr-sys"' --cfg 'feature="integer"' --cfg 'feature="rand"' --cfg 'feature="rational"' -C metadata=0f596f6f482a1c66 -C extra-filename=-0f596f6f482a1c66 --out-dir /home/akochkov/prolog/scryer-prolog/target/debug/deps -L dependency=/home/akochkov/prolog/scryer-prolog/target/debug/deps --extern gmp_mpfr_sys=/home/akochkov/prolog/scryer-prolog/target/debug/deps/libgmp_mpfr_sys-59418c005e571e7a.rmeta --cap-lints allow --cfg try_from --cfg maybe_uninit --cfg gmp_limb_bits_64 -L native=/home/akochkov/prolog/scryer-prolog/target/debug/build/gmp-mpfr-sys-7213e6610a5ac6cc/out/lib` (signal: 4, SIGILL: illegal instruction)
```

**Comment by jonas-schievink** [comment] 2019-09-29 10:35
Duplicate of https://github.com/rust-lang/rust-clippy/issues/4579

**Closed by jonas-schievink** 2019-09-29 10:35 UTC
Labels: C-bug, I-ICE, T-compiler
