### ISSUE TITLE
Allocation of 137 gigabytes

### ISSUE THREAD

**Issue by p0lunin** [rust-lang/rust#71019] opened 2020-04-11 09:52 UTC
I runc command:

```
cargo clippy
```

And i get error when compiler try to compile crate `winapi`:
```
memory allocation of 137438945312 bytes failed
error: could not compile `winapi`.
```
I think allocation of 137 Gb is bug. When i ran `cargo clippy` second time winapi was installed correctly.

```
process didn't exit successfully: 
`C:\Users\Asus\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\clippy-driver.exe rustc --crate-name winapi C:\Users\Asus\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.8\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=ad999df6e03866f7 -C extra-filename=-ad999df6e03866f7 --out-dir C:\Users\Asus\PycharmProjects\slingshot\p2p\target\debug\deps -L dependency=C:\Users\Asus\PycharmProjects\slingshot\p2p\target\debug\deps --cap-lints allow` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```
### Meta

`rustc --version --verbose`:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-pc-windows-msvc
release: 1.41.0
LLVM version: 9.0
```

**Comment by matthiaskrgr** [comment] 2020-04-11 17:29
We are talking about  https://github.com/retep998/winapi-rs , right?
When I try to run an up to date clippy `clippy 0.0.212 (d342cee 2020-04-07)` from `rustc 1.44.0-nightly (94d346360 2020-04-09)`, I don't see any crashes.

**Comment by p0lunin** [comment] 2020-04-11 18:21
Yes, we talking about it.
Now i also cannot reproduce it crash at my machine. Crash like it with same allocation was got my acquaintance. I don't know under what circumstances does it occur.

**Comment by Centril** [comment] 2020-04-11 19:50
Closing since we cannot reproduce. :)

**Closed by Centril** 2020-04-11 19:50 UTC
Labels: C-bug
