### ISSUE TITLE
Weak::new() segfaults on uninhabited types

### ISSUE THREAD

**Issue by jleedev** [rust-lang/rust#48493] opened 2018-02-24 02:22 UTC
This gives a segmentation fault:

```rust
fn main() {
    enum Void {}
    std::rc::Weak::<Void>::new();
}
```

There's no rust backtrace to show; I could reproduce this on various platforms and compiler versions.

**Comment by vitalyd** [comment] 2018-02-24 02:40
`std::mem::uninitialized::<T>()` that gets called in `Weak::new()` is UB.  The x86 assembly that gets generated, however, doesn’t have the `ud` illegal instruction but rather it does a bogus `movq $0, 1`

This is a nice one :)

**Comment by vitalyd** [comment] 2018-02-24 15:30
@sfackler, yeah seems like that might work (admittedly, I’ve not thought about it _too_ deeply).  I’m assuming the unstable `T: Copy` requirement for the union wouldn’t be an issue for std types right?

**Comment by vitalyd** [comment] 2018-02-24 15:31
Or rather, std would allow `T: !Copy` (the `T: Copy` is required for stable).

**Comment by sfackler** [comment] 2018-02-24 16:39
Yeah, std doesn’t need to worry about that.

**Comment by sfackler** [comment] 2018-03-09 04:28
There is a bit of a complication unfortunately - `Unsize` isn't implemented for unions the same way it's implemented for structs currently which breaks the CoerceUnsized impls :(

**Comment by alexcrichton** [comment] 2018-03-12 18:34
@sfackler in the meantime while we wait for https://github.com/rust-lang/rust/pull/47650 I wonder, would it be possible to fix this otherwise? Could we perhaps, for example, use `MaybeInitialized` to create a value and place it in memory?

**Comment by sfackler** [comment] 2018-03-12 18:36
Not sure - if the inner struct contains a bare `T`, I think it's undefined behavior for an instance of it to exist at all if `T` is uninhabited. We could use `Option<T>` and an accessor that does `match value { Some(ref v) => v, None => intrinsics::unreachable() }` I think?

**Comment by sfackler** [comment] 2018-03-12 18:44
The `Option<T>` approach adds an extra tag byte in some cases though unfortunately.

**Comment by alexcrichton** [comment] 2018-03-12 18:48
Hm yeah ideally we'd avoid changing the actual memory layout. Do you have a minimal example of where the segfault is coming from? The [playground](https://play.rust-lang.org/?gist=c4b92d04bb062827defb5967635a6a9c&version=nightly) indicates that zero is being stored at the address 1, but I'm not actually sure where that comes from...

**Comment by alexcrichton** [comment] 2018-03-12 18:57
Hm so actually [this reduction](https://play.rust-lang.org/?gist=848ad6604a06ad82fd5a207c850328a0&version=nightly) indicates that the problem is actually with the destructor here, not with the constructor. Specifically `Box<RcBox<Void>>` is always represented as a pointer to 1 because `sizeof(RcBox<Void>) == 0` (AFAIK).

That means when we attempt to access the pointer in the destructor it segfaults as we're storing the decremented refcount to address 0.

I wonder if this fix doesn't need to hold off until we get unsized unions? (or rather it'd still be present even if we had unsized unions)

**Comment by rkruppe** [comment] 2018-03-12 19:02
`RcBox` contains the refcounts so its size should never be zero. The reason `RcBox<Void>` has size zero is because it's uninhabited (due to containing the uninhabited `Void`), if `Void` was for example a unit struct then `sizeof(RcBox<Void>)` would be `2 * sizeof(Cell<usize>) + sizeof(Void)`.

**Comment by sfackler** [comment] 2018-03-12 19:25
Is `size_of` a const fn yet? We could maybe replace the `T` with

```rust
struct MaybeInitialized<T> {
    _align: [T; 0],
    data: [u8; size_of::<T>()],
}
```

**Comment by rkruppe** [comment] 2018-03-12 19:34
@sfackler That doesn't work for DSTs either (since `size_of` requires `T: Sized`).

**Comment by alexcrichton** [comment] 2018-03-12 19:42
@rkruppe oh bug or not `mem::size_of::<RcBox<Void>>()` is currently 0

**Comment by rkruppe** [comment] 2018-03-12 19:48
@alexcrichton I was trying to say that the size being zero (and hence the dangling pointer being dereferenced in the destructor) is just is a consequence of the uninhabitedness.

**Comment by alexcrichton** [comment] 2018-03-12 20:05
Ah yeah definitely, but I also see now how `MaybeInitialized` would actually solve this issue because the size of that union would indeed be 0 and would force the outer struct to not necessarily be 0 as well.

**Comment by alexcrichton** [comment] 2018-03-21 20:23
I've sent a PR for this at https://github.com/rust-lang/rust/pull/49248

**Comment by vitalyd** [comment] 2018-03-21 22:03
@alexcrichton, not sure it really matters here but the constructor also fails:
```
fn main() {
    enum Void {}
    std::mem::forget(std::rc::Weak::<Void>::new());
}
```
The above still generates a bogus mov instruction.

**Comment by alexcrichton** [comment] 2018-03-22 16:47
@vitalyd interesting! Apparently that's reduced down to:

```rust
#![feature(box_syntax)]

use std::mem;

enum Void {}

struct RcBox<T> {
    _a: usize,
    _b: T,
}

pub unsafe fn bar() {
    mem::forget(box RcBox {
        _a: 1,
        _b: mem::uninitialized::<Void>(),
    });
}
```

The `box` keyword is necessary there to reproduce the issue (interestingly enough). I've fixed that in #49248 I believe

**Comment by alexcrichton** [comment] 2018-04-19 22:57
De-nominating as this is blocked on https://github.com/rust-lang/rust/pull/47650

**Comment by SimonSapin** [comment] 2018-06-27 19:09
I cannot reproduce this segfault anymore, neither with the original test case nor the one in https://github.com/rust-lang/rust/issues/48493#issuecomment-375376475. I believe this is because the size of `RcBox<!>` was changed from zero to that of `RcBox<()>` (https://github.com/rust-lang/rust/issues/49298, https://github.com/rust-lang/rust/pull/50622), so we’re no longer not-allocating zero bytes and then writing to a dangling pointer.

With the issue fixed in practice as far as I can tell and https://github.com/rust-lang/rust/pull/51851 removing the use of `mem::uninitialized` (and the question of whether that is UB for uninhabited types even if we end up never touching that value), I think that https://github.com/rust-lang/rust/pull/51851 can be marked as closing this bug.

**Comment by SimonSapin** [comment] 2018-06-27 19:10
(Tested in 1.28.0-nightly (84804c387 2018-06-26).)

**Comment by SimonSapin** [comment] 2018-06-27 20:20
Sorry, the above with only without optimization. With optimizations, the second test case fails with "illegal instruction" in Nightly and the first prints `memory allocation of 16 bytes failed` (which I can explain as: undefined behavior, whatever).

With https://github.com/rust-lang/rust/pull/51851 however, the first test case `Weak::<Void>::new()` appears to be fixed even with optimizations.

**Closed** 2018-07-07 05:54 UTC
Labels: C-bug, I-unsound 💥, T-libs
