### ISSUE TITLE
Associated const requires trait bounds that are already satisfied

### ISSUE THREAD

**Issue by willglynn** [rust-lang/rust#43243] opened 2017-07-14 23:03 UTC
This code ([playpen](https://play.rust-lang.org/?gist=f89ae88a4afe38c7fcf2cf6602fc25ec&version=nightly)):

```rust
trait Foo {
    const SIZE: usize;
}

struct Container<F: Foo> {
    bytes: [u8; <F as Foo>::SIZE],
}
```

Fails with: 

```
error[E0277]: the trait bound `F: Foo` is not satisfied
 --> src/main.rs:8:17
  |
8 |     bytes: [u8; <F as Foo>::SIZE],
  |                 ^^^^^^^^^^^^^^^^ the trait `Foo` is not implemented for `F`
  |
  = help: consider adding a `where F: Foo` bound
  = note: required by `Foo::SIZE`
```

Changing to `struct Container<F: Foo> where F: Foo`, as directed, fails with the same message.

**Comment by vitalyd** [comment] 2017-07-15 01:43
Probably a dupe of https://github.com/rust-lang/rust/issues/42863

**Comment by Mark-Simulacrum** [comment] 2017-07-19 16:19
I think so, or at least another issue mentioned in that one... closing as a duplicate of #42863.

**Closed by Mark-Simulacrum** 2017-07-19 16:19 UTC
