### ISSUE TITLE
Pretty printer isn't preserving macro calls with brackets

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#26072] opened 2015-06-07 19:24 UTC
This code block:

``` rust
fn main() {
    println!{"foo {}", "bar"}
}
```

While it compiles fine with `rustc test.rs`, when run with `rustc -Z unstable-options --pretty normal` it produces this, which doesn't compile:

``` rust
fn main() {
    println!("foo {}" , "bar")
}
```

**Comment by TheNeikos** [comment] 2015-06-07 19:48
What's the error? I seem unable to reproduce it. (On 1.2.0 nightly, nor on 1.0 stable)

**Comment by erickt** [comment] 2015-06-07 21:01
@TheNeikos: The problem is that the pretty printed version should really be printing either `println!{"foo {}", "bar"}`, to preserve the input syntax, or `println!("foo {}", bar");`, which includes the trailing semicolon. Generating `println!("foo {}", bar)` without the semicolon will result in an error if there are any statements following this statement.

**Comment by TheNeikos** [comment] 2015-06-08 03:31
Alright, I worded it wrong, and checking the referenced issue it makes sense how you stumbled upon the error, you are right of course that it shouldn't create bad code.

What I meant by error was the compiler error as your example does not error on compilation (for the versions I provided and tried) so I was wondering if something changed lately I was unaware of.

**Comment by steveklabnik** [comment] 2017-01-03 17:59
Today, this generates `fn main() { println!{"foo {}" , "bar" } }`, which does compile. Closing!

**Closed by steveklabnik** 2017-01-03 17:59 UTC
Labels: A-pretty
