### ISSUE TITLE
rust build seems to be stuck on macOS 10.12

### ISSUE THREAD

**Issue by TitanNano** [rust-lang/rust#36668] opened 2016-09-23 08:58 UTC
I'm trying to upgrade rust on macOS 10.12 via homebrew but after some time of compiling, it seems to get stuck:

```
[100%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_x86_64_osx.dir/atomic_flag_test_and_set_explicit.c.o
[100%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_x86_64_osx.dir/atomic_signal_fence.c.o
[100%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_x86_64_osx.dir/atomic_thread_fence.c.o
[100%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_x86_64_osx.dir/emutls.c.o
[100%] Building C object lib/builtins/CMakeFiles/clang_rt.builtins_x86_64_osx.dir/gcc_personality_v0.c.o
[100%] Linking C static library libclang_rt.builtins_x86_64_osx.a
[100%] Built target clang_rt.builtins_x86_64_osx
cp: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/libcompiler-rt.a
cp: x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib/libcompiler-rt.a
cp: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libcompiler-rt.a
rustc: x86_64-apple-darwin/stage0/lib/rustlib/x86_64-apple-darwin/lib/libcore
rustc(71390,0x7fffc3b373c0) malloc: *** malloc_zone_unregister() failed for 0x7fffc3b2d000
```
![screen shot 2016-09-23 at 10 53 37](https://cloud.githubusercontent.com/assets/4500858/18780141/6e17b2be-817c-11e6-890f-df8c8bc9545b.png)

It stays like this for hours...

**Comment by TimNN** [comment] 2016-09-23 13:54
This is a duplicate of #34674 I believe.

**Comment by alexcrichton** [comment] 2016-09-26 23:57
Indeed, thanks @TimNN!

**Closed by alexcrichton** 2016-09-26 23:57 UTC
