### ISSUE TITLE
beta/nightly fails against Debian LLVM 3.7

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#29490] opened 2015-10-31 15:05 UTC
Hi, I can't build either the beta or the nightly (currently 1.6), with Debian's LLVM 3.7 (maintained by @sylvestre) I get these errors:

~~~~
g++ -g -O2 -fstack-protector-strong -Wformat -Werror=format-security  -O2  -Wall -Werror -g -fPIC -m64 -fno-rtti -c -o  x86_64-unknown-linux-gnu/rustllvm/RustWrapper.o  -I//usr//lib//llvm-3.7//include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -g -O2 -fomit-frame-pointer -std=c++11 -fvisibility-inlines-hidden -fno-exceptions -fPIC -ffunction-sections -fdata-sections -Wcast-qual   -I /usr/lib/llvm-3.7/include -I /build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/include /build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/RustWrapper.cpp
/build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/RustWrapper.cpp: In function 'LLVMOpaqueValue* LLVMRustBuildLandingPad(LLVMBuilderRef, LLVMTypeRef, LLVMValueRef, unsigned int, const char*, LLVMValueRef)':
/build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/RustWrapper.cpp:972:69: error: invalid conversion from 'LLVMValueRef {aka LLVMOpaqueValue*}' to 'unsigned int' [-fpermissive]
     return LLVMBuildLandingPad(Builder, Ty, PersFn, NumClauses, Name);
                                                                     ^
/build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/RustWrapper.cpp:972:69: error: invalid conversion from 'unsigned int' to 'const char*' [-fpermissive]
/build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/RustWrapper.cpp:972:69: error: too many arguments to function 'LLVMOpaqueValue* LLVMBuildLandingPad(LLVMBuilderRef, LLVMTypeRef, unsigned int, const char*)'
In file included from //usr//lib//llvm-3.7//include/llvm/IR/Value.h:17:0,
                 from //usr//lib//llvm-3.7//include/llvm/IR/User.h:24,
                 from //usr//lib//llvm-3.7//include/llvm/IR/Instruction.h:22,
                 from //usr//lib//llvm-3.7//include/llvm/IR/BasicBlock.h:19,
                 from //usr//lib//llvm-3.7//include/llvm/IR/IRBuilder.h:21,
                 from /build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/rustllvm.h:11,
                 from /build/rustc-1.5.0~beta.2.20151029+dfsg1/src/rustllvm/RustWrapper.cpp:11:
//usr//lib//llvm-3.7//include/llvm-c/Core.h:2677:14: note: declared here
 LLVMValueRef LLVMBuildLandingPad(LLVMBuilderRef B, LLVMTypeRef Ty,
              ^
/build/rustc-1.5.0~beta.2.20151029+dfsg1/mk/rustllvm.mk:60: recipe for target 'x86_64-unknown-linux-gnu/rustllvm/RustWrapper.o' failed
make[2]: *** [x86_64-unknown-linux-gnu/rustllvm/RustWrapper.o] Error 1
~~~~

and the same error occurs for the nightly. However, 1.4 (current stable) builds fine, and 1.5 (nightly on 2015-09-18) also built fine.

I see that rust includes a custom LLVM; I wonder if someone knows which patches we need to also back-port to Debian's LLVM to fix the build (or if it is [Debian's patches](https://anonscm.debian.org/viewvc/pkg-llvm/llvm-toolchain/branches/3.7/debian/patches/) that are at fault, even).

**Comment by dotdash** [comment] 2015-10-31 15:25
This is caused by an accidental change in LLVM 3.7.0 which will be
fixed/reverted in 3.7.1. The patch is in the upstream release_37 branch on
which rust's fork is based.
Am 31.10.2015 16:06 schrieb "Ximin Luo" <notifications@github.com>:

**Comment by wthrowe** [comment] 2015-10-31 20:02
See #28830 for some discussion of this.

**Comment by sanxiyn** [comment] 2015-11-01 09:16
The exact revision you need to backport is [LLVM r247191](http://llvm.org/viewvc/llvm-project?view=revision&revision=247191), but you can also wait for LLVM 3.7.1.

**Comment by sylvestre** [comment] 2015-11-01 15:02
OK, I took commit r242372. I will upload a new version of llvm 3.7.0 with the patch later (when I have more changes)

**Comment by steveklabnik** [comment] 2015-11-11 15:59
So, is this not an sissue, I guess?

**Comment by sanxiyn** [comment] 2015-11-12 04:46
This is not an issue in the sense that we don't expect to make any change and expect the issue to resolve itself. But I am against closing because it still is the case that Rust fails to build against the latest LLVM release. I will close as soon as LLVM 3.7.1 is out.

**Comment by petevine** [comment] 2015-11-29 20:45
Hey, I've just bumped into this one on 32-bit Slackware current - I think configure should immediately abort on detecting local llvm 3.7.0.

**Comment by lucab** [comment] 2015-12-13 10:20
LLVM 3.7.1 has been tagged in [SVN r255206](http://llvm.org/viewvc/llvm-project?view=revision&revision=255206), but tarballs not yet announced. Preliminary Rust 1.5.0 debian package seems to be building fine with it.

**Comment by sanxiyn** [comment] 2016-01-08 07:33
LLVM 3.7.1 is released, closing.

**Closed by sanxiyn** 2016-01-08 07:33 UTC
Labels: A-build
