### ISSUE TITLE
Cannot fully install/use GNU Linux target from Windows

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#47629] opened 2018-01-21 04:28 UTC
Hello, I am trying to configure rustup to allow for cross-compilation targeting Linux binaries from a Windows host. However, the installation of the GNU Linux target appears to feature some kind of error message, and when I try to use this target via xargo, some part of the Rust system complains that it cannot find that target.

Trace:

```
$ rustup install stable-x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
252.1 KiB / 252.1 KiB (100 %) 113.5 KiB/s ETA:   0 s
info: latest update on 2018-01-04, rust version 1.23.0 (766bd11c8 2018-01-01)
info: downloading component 'rustc'
 45.0 MiB /  45.0 MiB (100 %)   1.2 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 61.2 MiB /  61.2 MiB (100 %) 489.6 KiB/s ETA:   0 s
info: downloading component 'cargo'
  4.0 MiB /   4.0 MiB (100 %)   1.2 MiB/s ETA:   0 s
info: downloading component 'rust-docs'
  4.5 MiB /   4.5 MiB (100 %)   1.1 MiB/s ETA:   0 s
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'

  stable-x86_64-unknown-linux-gnu installed - (rustc does not exist)

$ xargo build --target x86_64-unknown-linux-gnu
WARNING: the sysroot can't be built for the Stable channel. Switch to nightly.
   Compiling hello v0.0.1 (file:///C:/Users/a_pen/go/src/github.com/mcandre/toys/rust/hello)
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed

error: aborting due to previous error

error: Could not compile `hello`.

To learn more, run the command again with --verbose.
```

I tried configuring rustup to force the stable-x86_64-unknown-linux-gnu toolchain as default, but then when I run `rustc` after that, I get a panic message:

```
$ rustup default stable-x86_64-unknown-linux-gnu
info: using existing install for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - (rustc does not exist)

$ xargo build
thread 'main' panicked at 'unexpected -vV format', .cargo\registry\src\github.com-1ecc6299db9ec823\rustc_version-0.1.7\src\lib.rs:126:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Is it possible to build Linux binaries with Rust from Windows hosts without resorting to containers / virtual machines?

**Comment by FenrirWolf** [comment] 2018-01-21 07:40
I don't think Xargo is necessary for your use-case, since rustup already provides you with the core and standard libraries for linux. Have you tried just using Cargo to do the cross-compilation?

**Comment by mcandre** [comment] 2018-01-21 22:40
> Have you tried just using Cargo to do the cross-compilation?

Yes. I replaced `xargo` in my examples with `cargo` and got the same results either way.

**Comment by retep998** [comment] 2018-01-22 02:15
Don't install the linux *toolchain*. That gives you linux binaries that don't actually run on Windows. What you actually want is the linux *target*. Use a normal windows toolchain but then do `rustup target add x86_64-unknown-linux-gnu`.

However, if you really wanted to build linux binaries from Windows, you'd probably be better off natively building linux binaries inside the linux subsystem of Windows 10.

**Comment by TimNN** [comment] 2018-01-23 15:48
Closing as expected behavior. Feel free to reach out via users.rust-lang.org, via IRC or other avenues if you have any troubles getting Rust to work on windows.

**Closed by TimNN** 2018-01-23 15:48 UTC

**Comment by mcandre** [comment] 2018-01-23 23:15
Thank you for the update. I have installed the 64-bit GNU Linux target, and now I get a different error during compilation, about Rust complaining that "cc" is missing.

```console
$ cargo build --target x86_64-unknown-linux-gnu
   Compiling hello v0.0.1 (file:///C:/Users/a_pen/go/src/github.com/mcandre/toys/rust/hello)
error: could not exec the linker `cc`: The system cannot find the file specified. (os error 2)
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib" "C:\\Users\\a_pen\\go\\src\\github.com\\mcandre\\toys\\rust\\hello\\target\\x86_64-unknown-linux-gnu\\debug\\deps\\hello-b48813c72b5be0f1.hello0.rcgu.o" "C:\\Users\\a_pen\\go\\src\\github.com\\mcandre\\toys\\rust\\hello\\target\\x86_64-unknown-linux-gnu\\debug\\deps\\hello-b48813c72b5be0f1.hello1.rcgu.o" "-o" "C:\\Users\\a_pen\\go\\src\\github.com\\mcandre\\toys\\rust\\hello\\target\\x86_64-unknown-linux-gnu\\debug\\deps\\hello-b48813c72b5be0f1" "C:\\Users\\a_pen\\go\\src\\github.com\\mcandre\\toys\\rust\\hello\\target\\x86_64-unknown-linux-gnu\\debug\\deps\\hello-b48813c72b5be0f1.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "C:\\Users\\a_pen\\go\\src\\github.com\\mcandre\\toys\\rust\\hello\\target\\x86_64-unknown-linux-gnu\\debug\\deps" "-L" "C:\\Users\\a_pen\\go\\src\\github.com\\mcandre\\toys\\rust\\hello\\target\\debug\\deps" "-L" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib" "-Wl,-Bstatic" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\libstd-58a9e2944951d97f.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\libpanic_unwind-167b5e977a2ab35c.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\libunwind-b8892ba833aa6677.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\liballoc_system-17235785be0fea01.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\liblibc-2e9b8cf09e3563de.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\liballoc-d7195d5e94bc6586.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\libstd_unicode-963f18f265d9b8d3.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\libcore-48934815da5d2bfb.rlib" "C:\\Users\\a_pen\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-unknown-linux-gnu\\lib\\libcompiler_builtins-a6b6fad6cc543169.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"

error: aborting due to previous error

error: Could not compile `hello`.
```

Strange that a Windows installation of Rust is searching for `cc` in order to cross-compile Linux binaries. Does this cross-compilation setup require a Cygwin configuration providing `cc`, or is should Rust for Windows be looking for `cl` from Visual Studio to perform this compilation?

**Comment by retep998** [comment] 2018-01-24 03:16
You would need some sort of cygwin configuration that provides a cross compiler that can run on Windows and target Linux. It doesn't have to be named `cc` precisely because you can configure what linker rustc will look for for any given target by specifying it in your `.cargo/config`.
