### ISSUE TITLE
Undefined refrence to FILE_LINE in panic with -Z incremental

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#39910] opened 2017-02-17 14:51 UTC
Seen when compiling http://github.com/thepowersgang/rust_os (Kernel) with `-Z incremental`

```
.obj/amd64/libgui.rlib(gui.kernel-lib-mem-grc.volatile.o): In function `kernel::lib::mem::grc::{{impl}}::make_unique<core::sync::atomic::AtomicUsize,gui::windows::winbuf::WinBuf>':
/home/tpg/Projects/rust_os/Kernel/<panic macros>:4: undefined reference to `_$LT$kernel..lib..mem..grc..Grc$LT$C$C$$u20$T$GT$$GT$::make_unique::_MSG_FILE_LINE::hc8eec685da0aec8e'
```

**Comment by Nilstrieb** [comment] 2023-07-01 13:10
Since there is no reproduction (the exact commit is unknown) and this issue is 6 years old with many changes in incremental happening since then I'm going to close it. Feel free to open a new issue if new issues arise.

**Closed by Nilstrieb** 2023-07-01 13:10 UTC
Labels: T-compiler, A-incr-comp, C-bug
