### ISSUE TITLE
Regression in binary_macros-0.6.3, Rust 1.16

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40381] opened 2017-03-09 03:28 UTC
```
101 brian@ip-10-145-43-250:~/dev/binary_macros⟫ git remote -v
origin  https://github.com/golddranks/binary_macros (fetch)
origin  https://github.com/golddranks/binary_macros (push)
brian@ip-10-145-43-250:~/dev/binary_macros⟫ git log -1
commit 04008be68f8d71e8684c050d540c743eb50e5124
Author: Pyry Kontio <pyry.kontio@drasa.eu>
Date:   Fri Mar 3 14:49:04 2017 +0200

    Trying to get categories to work. 0.6.3

```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.16.0-beta.3 (ecbf0b59e 2017-03-02)
binary: rustc
commit-hash: ecbf0b59e409af1a09c1c7c3947858c5e78f416d
commit-date: 2017-03-02
host: x86_64-unknown-linux-gnu
release: 1.16.0-beta.3
LLVM version: 3.9

```

```
error: attempted to repeat an expression containing no syntax variables matched as repeating at this depth
  --> src/lib.rs:25:1
   |
25 | proc_macro_expr_decl!(base64_nopad! => base64_nopad_impl);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate

error: attempted to repeat an expression containing no syntax variables matched as repeating at this depth
  --> src/lib.rs:25:1
   |
25 | proc_macro_expr_decl!(base64_nopad! => base64_nopad_impl);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate

error: attempted to repeat an expression containing no syntax variables matched as repeating at this depth
  --> src/lib.rs:26:1
   |
26 | proc_macro_expr_decl!(base64url_nopad! => base64url_nopad_impl);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate

error: attempted to repeat an expression containing no syntax variables matched as repeating at this depth
  --> src/lib.rs:26:1
   |
26 | proc_macro_expr_decl!(base64url_nopad! => base64url_nopad_impl);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate

```

Not on 1.15. ***Not on 1.17 nightly***

cc @jseyfried can you think of a backport that will fix this?

cc @golddranks

**Comment by golddranks** [comment] 2017-03-09 03:41
Are other crates that depend on `proc-macro-hack` unaffected?

**Comment by golddranks** [comment] 2017-03-09 03:43
Ah, I think that this was documented by @dtolnay; it used to affect nightlies.

https://github.com/dtolnay/proc-macro-hack

> Note: Requires stable Rust 1.15, beta Rust 1.16, or nightly Rust 1.17 with a date 2017-03-01 or later due to a regression affecting earlier 1.17 nightlies (rust-lang/rust#39889).

**Comment by golddranks** [comment] 2017-03-09 03:45
At least the symptoms are the same, as far as I can remember. Was there some other backports from nightly that triggered this on beta? It was this: https://github.com/rust-lang/rust/pull/39419 that eventually fixed this, if this bug is what I think it is.

**Comment by dtolnay** [comment] 2017-03-09 03:53
This definitely used to work on 1.16.0-beta so it must have been triggered by a backport.

**Comment by nikomatsakis** [comment] 2017-03-09 17:11
@jseyfried do you have any idea what is the problem here? this really needs to be fixed in next 72 hours or so if we are to prepare the stable release.

**Comment by brson** [comment] 2017-03-09 17:14
Let's verify that it worked on previous betas, then try to bisect the backports.

**Comment by jseyfried** [comment] 2017-03-09 20:06
This was caused by #39370 -- I'll fix today.

**Comment by jseyfried** [comment] 2017-03-10 06:34
Fixed in #40411.

**Comment by pooyapeyravi** [comment] 2017-03-13 14:29
101 brian@ip-10-145-43-250:~/dev/binary_macros⟫ git remote -v
origin  https://github.com/golddranks/binary_macros (fetch)
origin  https://github.com/golddranks/binary_macros (push)
brian@ip-10-145-43-250:~/dev/binary_macros⟫ git log -1
commit 04008be68f8d71e8684c050d540c743eb50e5124
Author: Pyry Kontio <pyry.kontio@drasa.eu>
Date:   Fri Mar 3 14:49:04 2017 +0200

**Comment by pooyapeyravi** [comment] 2017-03-13 14:32
101 brian@ip-10-145-43-250:~/dev/binary_macros⟫ git remote -v
origin  https://github.com/golddranks/binary_macros (fetch)
origin  https://github.com/golddranks/binary_macros (push)
brian@ip-10-145-43-250:~/dev/binary_macros⟫ git log -1
commit 04008be68f8d71e8684c050d540c743eb50e5124
Author: Pyry Kontio <pyry.kontio@drasa.eu>
Date:   Fri Mar 3 14:49:04 2017 +0200

**Closed** 2017-03-14 05:09 UTC
Labels: P-high, regression-from-stable-to-beta, T-compiler
