### ISSUE TITLE
Cannot create rlibs when run in sandboxie

### ISSUE THREAD

**Issue by retep998** [rust-lang/rust#54297] opened 2018-09-17 15:18 UTC
`rustc main.rs` where the crate type is bin works just fine.
`rustc lib.rs` where the crate type is rlib fails with this error:
```
> rustc lib.rs
error: failed to build archive: permission denied

error: aborting due to previous error
```

Given the importance of sandboxing when building and testing random code off the internet, we should really try our best to support sandboxie.

**Comment by Enselic** [comment] 2023-10-15 11:48
Triage: Does this still reproduce? Wanted to check since 5 years has passed and circumstances might have changed.

If this still reproduces, can you please add step-by-step instructions on how to install sandboxie and install rustc inside of it? That makes it much easier for devs to debug this. Thanks!

**Comment by ChrisDenton** [comment] 2023-10-15 12:24
Seems to work for me now. Steps I took: installed [Sandboxie](https://sandboxie-plus.com/) and ran cmd using the default sandbox. Created a lib.rs file containing the following:

```rust
#![crate_type = "rlib"]

pub fn add(a: u32, b: u32) -> u32 {
    a + b
}
```

The I ran `rustc lib.rs`. It completed without error and successfully produced a `liblib.rlib` file.

**Comment by ChrisDenton** [comment] 2024-10-25 01:02
Closing as fixed

**Closed by ChrisDenton** 2024-10-25 01:02 UTC
Labels: O-windows, T-compiler
