### ISSUE TITLE
internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by rainboh** [rust-lang/rust#33080] opened 2016-04-18 18:35 UTC
I tried this code:

~~~
use std::io::Error as io_error;
use std::error;
use std::error::Error;

#[derive(Debug)]
pub enum MyError {
    FirstError(Error),
    SecondError(Error),
    ThirdError(Error),
}

fn main() {
    println!("Hello, world!");
}
~~~

stable reports

~~~
error: internal compiler error: unexpected panic
~~~

nightly reports

~~~
error: internal compiler error: ../src/librustc_trans/type_of.rs:134: Unexpected tail in unsized_info_ty: MyError for ty=MyError
~~~

## Meta

`rustc --version --verbose`:

~~~
rustc 1.8.0 (db2939409 2016-04-11)
binary: rustc
commit-hash: db2939409db26ab4904372c82492cd3488e4c44e
commit-date: 2016-04-11
host: x86_64-unknown-linux-gnu
release: 1.8.0
~~~

Backtrace:

~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Unexpected type returned from struct_tail: MyError for ty=MyError', ../src/librustc_trans/trans/type_of.rs:389
stack backtrace:
   1:     0x7feb529f6330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7feb529ff68b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7feb529ff1e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7feb529c39ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7feb529c4448 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x7feb50e936da - trans::type_of::in_memory_type_of::ha5e1d9a1ec61c2f438U
   7:     0x7feb50ec0147 - trans::type_of::arg_type_of::hb6e745989aab5394r7U
   8:     0x7feb50f6884d - trans::type_of::type_of_rust_fn::h4270d1811caadc430SU
   9:     0x7feb50eb26e8 - trans::declare::declare_rust_fn::h360e10fe55a29af4UmD
  10:     0x7feb50ee1ab5 - trans::base::register_fn::h8da7383655e57ddcHvk
  11:     0x7feb50ee38d1 - trans::base::register_method::h7f0f603090317548LVk
  12:     0x7feb50edd508 - trans::base::get_item_val::he0b8ef6390bb29dc7Hk
  13:     0x7feb50edb320 - trans::base::trans_item::h6acb22e4cadb1a91Xnk
  14:     0x7feb50ef876b - trans::base::TransItemsWithinModVisitor<'a, 'tcx>.Visitor<'v>::visit_item::h17401197a5140e35bol
  15:     0x7feb50ee5e4b - trans::base::trans_crate::he0efa1d5417c3e0bB7k
  16:     0x7feb52f2bd84 - driver::phase_4_translate_to_llvm::h6b8ee7bea6f9aad8O1a
  17:     0x7feb52f2a58c - driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::closure.29535
  18:     0x7feb52f26e57 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.28550
  19:     0x7feb52f20c04 - middle::ty::context::ctxt<'tcx>::create_and_enter::h16192426302205697189
  20:     0x7feb52f1d6ef - driver::phase_3_run_analysis_passes::h10920926650053012691
  21:     0x7feb52ef0a15 - driver::compile_input::h7ae6a86e23de0774Hca
  22:     0x7feb52edfb47 - run_compiler::hb0408bcf47642fe6mPc
  23:     0x7feb52edd2c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  24:     0x7feb529f3d1b - __rust_try
  25:     0x7feb529ec1fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  26:     0x7feb52eddb10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  27:     0x7feb529fdc59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  28:     0x7feb4bc9d6a9 - start_thread
  29:     0x7feb5266be9c - clone
  30:                0x0 - <unknown>
~~~

-------

`rustc --version --verbose`:

~~~
rustc 1.10.0-nightly (ed7c56796 2016-04-17)
binary: rustc
commit-hash: ed7c56796ef17f13227a50dc1a72a018b1d5e33f
commit-date: 2016-04-17
host: x86_64-unknown-linux-gnu
release: 1.10.0-nightly
~~~

Backtrace:

~~~
error: internal compiler error: ../src/librustc_trans/type_of.rs:134: Unexpected tail in unsized_info_ty: MyError for ty=MyError
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/errors/mod.rs:574
stack backtrace:
   1:     0x7f91c185da30 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x7f91c186b15b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x7f91c186acfc - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x7f91c182fcaf - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x7f91b9deca87 - std::sys_common::unwind::begin_unwind::h24c4c0fa2cfe995a
   6:     0x7f91b9dec8b5 - syntax::errors::Handler::bug::h9033aa2bf9160334
   7:     0x7f91bb0af0e2 - rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::hf0fb5697f8f25f40
   8:     0x7f91bb0aef72 - rustc::session::opt_span_bug_fmt::hc581ba88c4e2ec53
   9:     0x7f91bb0c6d76 - rustc::session::bug_fmt::had96c08cb43bd8a1
  10:     0x7f91c08ccd35 - rustc_trans::type_of::unsized_info_ty::hce316b0f61e418ac
  11:     0x7f91c07a981c - rustc_trans::type_of::in_memory_type_of::h97b017bde8fe1e03
  12:     0x7f91c079da51 - rustc_trans::abi::FnType::unadjusted::_$u7b$$u7b$closure$u7d$$u7d$::h70131b4b2d0cfbee
  13:     0x7f91c079b3ab - rustc_trans::abi::FnType::unadjusted::hca5902507eb050fc
  14:     0x7f91c07a92f7 - rustc_trans::type_of::in_memory_type_of::h97b017bde8fe1e03
  15:     0x7f91c0810303 - rustc_trans::callee::get_fn::h691a55e881985779
  16:     0x7f91c07b4860 - rustc_trans::callee::Callee::def::ha169529fef0048b5
  17:     0x7f91c07ded12 - rustc_trans::base::trans_item::hdc785ae68a9e6500
  18:     0x7f91c07f90cb - _<base..TransItemsWithinModVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_item::h22c1c36dec64effa
  19:     0x7f91c07e769b - rustc_trans::base::trans_crate::h6ed1dbd6e572a8c2
  20:     0x7f91c1dc403f - rustc_driver::driver::phase_4_translate_to_llvm::hd7579aae98641824
  21:     0x7f91c1dc26cf - rustc_driver::driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::h5534474dbe9371c4
  22:     0x7f91c1dbf040 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::h5a042a091cd7658c
  23:     0x7f91c1db8b1b - rustc::ty::context::TyCtxt::create_and_enter::h3f9051bcccbd93e4
  24:     0x7f91c1db55ce - rustc_driver::driver::phase_3_run_analysis_passes::h9c723484c588a35b
  25:     0x7f91c1d87f6f - rustc_driver::driver::compile_input::h0629572e6f316b31
  26:     0x7f91c1d6e4d4 - rustc_driver::run_compiler::h8902aebf8b1849a8
  27:     0x7f91c1d6b941 - std::sys_common::unwind::try::try_fn::h4c74456035d0fcc7
  28:     0x7f91c185b1cb - __rust_try
  29:     0x7f91c185b15d - std::sys_common::unwind::inner_try::h47a4d9cd4a369dcd
  30:     0x7f91c1d6c18a - _<F as std..boxed..FnBox<A>>::call_box::h27f542a39f1d61ef
  31:     0x7f91c18692f4 - std::sys::thread::Thread::new::thread_start::h6f266e069bf4ec2b
  32:     0x7f91b96916a9 - start_thread
  33:     0x7f91c14bde9c - clone
  34:                0x0 - <unknown>
~~~

**Comment by nagisa** [comment] 2016-04-18 20:17
Seems to be a duplicate of https://github.com/rust-lang/rust/issues/32765. Thanks!

**Closed by nagisa** 2016-04-18 20:17 UTC
