### ISSUE TITLE
sub-trait coercions

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#18600] opened 2014-11-04 01:27 UTC
Where `trait T: U { ... }` , implictly coerce from `&T` to `&U`, etc.

See [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md).

Part of #18469

**Comment by steveklabnik** [comment] 2015-01-27 18:42
another https://github.com/rust-lang/rust/issues/18469

**Comment by frewsxcv** [comment] 2015-11-18 03:10
What's the status of this?

**Comment by typelist** [comment] 2016-10-09 08:48
I think this is a duplicate of #5665 (although that bug was filed before RFC 401 was adopted).

**Comment by Mark-Simulacrum** [comment] 2017-07-22 00:50
Going to go ahead and close in favor of #5665.

**Closed by Mark-Simulacrum** 2017-07-22 00:50 UTC
Labels: A-dst, C-tracking-issue

**Comment by crlf0710** [comment] 2021-08-16 11:42
Current tracking issue for this is #65991
