### ISSUE TITLE
Missing source links in std::iter::Iterator docs

### ISSUE THREAD

**Issue by qrilka** [rust-lang/rust#80502] opened 2020-12-30 08:35 UTC
I was looking into https://doc.rust-lang.org/std/iter/trait.Iterator.html trying to find source code for the [`zip` method](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.zip)

I expected to see "src" with a link to the function source code.

Instead, there appear to be no such link and other methods (even [`next`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#tymethod.next)!) of this trait also lack source code links.

**Comment by ThePuzzlemaker** [comment] 2021-01-01 17:51
This appears to have been fixed in nightly. (see [https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html], the nightly docs for `std::iter::Iterator`).

**Comment by qrilka** [comment] 2021-01-01 18:03
Then probably this could be closed, one thing though is to find the reason that happened and have some measures against it reintroduced again.

**Comment by GuillaumeGomez** [comment] 2021-01-03 14:24
It'd require to add a test to prevent the regression (in `src/test/rustdoc`). I'll mark the issue as `E-medium` because it might require to extend those tests to be able to check directly on `std` docs.

**Comment by Stupremee** [comment] 2021-02-12 19:14
Is there a reason this issue is still open? Since this seems to be fixed already

**Comment by GuillaumeGomez** [comment] 2021-02-12 19:18
We still need to add a test to ensure that the `[src]` link is present, I'll do that so we can close it.

**Closed** 2021-02-13 10:55 UTC
Labels: C-bug, E-medium, T-rustdoc
