### ISSUE TITLE
Inline asm: The "=m" constraint causes an illegal instruction error

### ISSUE THREAD

**Issue by gnutick** [rust-lang/rust#24808] opened 2015-04-25 10:58 UTC
Hi!

Rust ends with an illegal instruction error when I try to compile this:
```rust
let mut c: u64;
asm!("" : "=m" (c));
```
Maybe because it generates wrong LLVM IR.

Rust/LLVM IR:
```llvm
%1 = call i64 asm "", "=m,~{dirflag},~{fpsr},~{flags}"(), !srcloc !0
store i64 %1, i64* %c
```
Clang/LLVM IR:
```llvm
call void asm "", "=*m,~{dirflag},~{fpsr},~{flags}"(i64* %c) #1, !srcloc !1
```

## Meta
`rustc --version --verbose`:
rustc 1.1.0-dev (2214860d4 2015-04-24) (built 2015-04-25)
binary: rustc
commit-hash: 2214860d4a979fe24d935277a74bd4d67e9bdb9f
commit-date: 2015-04-24
build-date: 2015-04-25
host: x86_64-unknown-linux-gnu
release: 1.1.0-dev

`clang --version`:
Ubuntu clang version 3.6.0-2ubuntu1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

**Comment by nagisa** [comment] 2015-04-25 13:33
Citing @huonw:

> Our constraints do not duplicate GCC; its just that we implement several of the same constraints GCC supports.

Anyway, duplicate of https://github.com/rust-lang/rust/issues/16383

**Comment by steveklabnik** [comment] 2015-04-28 17:52
Yes, this is a duplicate. Thanks though!

**Closed by steveklabnik** 2015-04-28 17:52 UTC
