### ISSUE TITLE
Borrow checking fails in case a closure appears in a const expression

### ISSUE THREAD

**Issue by YohDeadfall** [rust-lang/rust#81899] opened 2021-02-08 22:10 UTC
The following code causes compiler panics due to the first line without which the issue isn't reproducible. Calling the function outside of a constant context emits the right compiler errors.

### Code

```Rust
const CACHE: &[u32] = &const_sort(&[2, 3, 1], |a, b| a < b); // that line is a failure reason
const fn const_sort<F, const N: usize>(v: &[u32; N], mut is_less: F) -> [u32; N]
where
    F: FnMut(&u32, &u32) -> bool,
{
    let mut r = [0; N];
    
    let mut i = 0;
    while i < N {
        r[i] = v[i];
        i += 1;
    }
    
    let mut i = 1;
    while i < N {
        if is_less(&r[i], &r[i - 1]) {
            let tmp = r[i];
            
            r[i] = r[i - 1];
            
            let mut j = i - 1;
            while j > 0 && is_less(&tmp, &r[j - 1]) {
			    r[j] = r[j - 1];
			    j -= 1;
	    	}
	    	
	    	r[j] = tmp;
	    }
	    i += 1;
    }
    
    r
}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
   Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_mir/src/borrow_check/region_infer/mod.rs:2136:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (9778068cb 2021-02-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `CACHE`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `playground`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: rust_begin_unwind
             at /rustc/9778068cbc1e06cc3685422323ff38a2f397de26/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9778068cbc1e06cc3685422323ff38a2f397de26/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9778068cbc1e06cc3685422323ff38a2f397de26/library/core/src/panicking.rs:50:5
   3: rustc_mir::borrow_check::region_infer::RegionInferenceContext::find_outlives_blame_span
   4: rustc_mir::borrow_check::do_mir_borrowck
   5: rustc_infer::infer::InferCtxtBuilder::enter
   6: rustc_mir::borrow_check::mir_borrowck
   7: core::ops::function::FnOnce::call_once
   8: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  10: rustc_data_structures::stack::ensure_sufficient_stack
  11: rustc_query_system::query::plumbing::force_query_with_job
  12: rustc_query_system::query::plumbing::get_query_impl
  13: rustc_query_system::query::plumbing::ensure_query_impl
  14: rustc_session::utils::<impl rustc_session::session::Session>::time
  15: rustc_interface::passes::analysis
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::force_query_with_job
  20: rustc_query_system::query::plumbing::get_query_impl
  21: rustc_interface::passes::QueryContext::enter
  22: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  23: rustc_span::with_source_map
  24: rustc_interface::interface::create_compiler_and_run
  25: rustc_span::with_session_globals
```

</p>
</details>

**Comment by LeSeulArtichaut** [comment] 2021-02-08 22:46
Replacing the function body with `todo!()` still gives an ICE:

```rust
const CACHE: &[u32] = &const_sort(&[2, 3, 1], |a, b| a < b); // that line is a failure reason
const fn const_sort<F, const N: usize>(v: &[u32; N], mut is_less: F) -> [u32; N]
where
    F: FnMut(&u32, &u32) -> bool,
{
    todo!()
}
```

**Comment by memoryruins** [comment] 2021-02-08 23:11
Minimized slightly further, without const generics:
```rust
const _CONST: &[u8] = &f(&[], |_| {});

const fn f<F>(_: &[u8], _: F) -> &[u8]
where
    F: FnMut(&u8),
{
    panic!()
}
```

<details>
<summary>backtrace</summary>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_mir/src/borrow_check/region_infer/mod.rs:2136:35
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9778068cbc1e06cc3685422323ff38a2f397de26/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9778068cbc1e06cc3685422323ff38a2f397de26/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/9778068cbc1e06cc3685422323ff38a2f397de26/library/core/src/panicking.rs:50:5
   3: rustc_mir::borrow_check::region_infer::RegionInferenceContext::find_outlives_blame_span
   4: rustc_mir::borrow_check::do_mir_borrowck
   5: rustc_infer::infer::InferCtxtBuilder::enter
   6: rustc_mir::borrow_check::mir_borrowck
   7: core::ops::function::FnOnce::call_once
   8: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::mir_borrowck>::compute
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  10: rustc_data_structures::stack::ensure_sufficient_stack
  11: rustc_query_system::query::plumbing::force_query_with_job
  12: rustc_query_system::query::plumbing::get_query_impl
  13: rustc_query_system::query::plumbing::ensure_query_impl
  14: rustc_session::utils::<impl rustc_session::session::Session>::time
  15: rustc_interface::passes::analysis
  16: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  17: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  18: rustc_data_structures::stack::ensure_sufficient_stack
  19: rustc_query_system::query::plumbing::force_query_with_job
  20: rustc_query_system::query::plumbing::get_query_impl
  21: rustc_interface::passes::QueryContext::enter
  22: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  23: rustc_span::with_source_map
  24: rustc_interface::interface::create_compiler_and_run
  25: rustc_span::with_session_globals
```

</details>

The ICE occurs back to `1.41.0`. In `1.40.0`, it errors with
```
error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
 --> <source>:3:12
  |
3 | const fn f<F>(_: &[u8], _: F) -> &[u8]
  |            ^
  |
  = note: for more information, see issue https://github.com/rust-lang/rust/issues/57563
  = help: add `#![feature(const_fn)]` to the crate attributes to enable
```
By making small changes such as making the closure no longer take paramters or removing the reference at
```diff
- const _CONST: &[u8] = &f(&[], |_| {});
+ const _CONST: &[u8] = f(&[], |_| {});
```
It errors, instead of an ICE, on stable `1.49.0` and nightly with
```
error[E0723]: trait bounds other than `Sized` on const fn parameters are unstable
 --> src/lib.rs:3:12
  |
3 | const fn f<F>(_: &[u8], _: F) -> &[u8]
  |            ^
  |
  = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
  = help: add `#![feature(const_fn)]` to the crate attributes to enable

error[E0658]: panicking in constant functions is unstable
 --> src/lib.rs:7:5
  |
7 |     panic!()
  |     ^^^^^^^^
  |
  = note: see issue #51999 <https://github.com/rust-lang/rust/issues/51999> for more information
  = help: add `#![feature(const_panic)]` to the crate attributes to enable
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
```

**Comment by matthiaskrgr** [comment] 2021-02-08 23:16
searched nightlies: from nightly-2020-08-16 to nightly-2021-02-03
regressed nightly: nightly-2020-12-28
searched commits: from https://github.com/rust-lang/rust/commit/0b644e419681835bd0f5871c3bfbd648aa04f157 to https://github.com/rust-lang/rust/commit/257becbfe4987d1f7b12af5a8dd5ed96697cd2e8
regressed commit: https://github.com/rust-lang/rust/commit/1d517afcd0929450ded8f644fa8e8da3776db68b

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --test-dir=/home/matthias/vcs/github/rust_bisect/foo --start=2020-08-16 --end=2021-02-03
```

**Comment by jyn514** [comment] 2021-02-10 14:18
cc @lcnr

**Comment by LeSeulArtichaut** [comment] 2021-02-10 14:33
Just to clarify, this issue is not due to #79135, the `min_const_generics` stabilization just allowed code with const generics to run into this. @memoryruins's MCVE ICEs before #79135 and shows that this is a borrowck bug not related to const generics

**Comment by apiraino** [comment] 2021-02-10 16:02
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381899.20Borrow.20checking.20fails.20in.20case.20a.20closure.20appears.20in.20a.E2.80.A6) and removing `I-prioritize`.

**Comment by johnkjellberg** [comment] 2021-06-02 14:41
I'm not sure if this is identical problem or not. The error message is:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_mir/src/borrow_check/region_infer/mod.rs:2136:35

/.../

query stack during panic:
#0 [mir_borrowck] borrow-checking `COPY`
#1 [analysis] running analysis passes on this crate
end of query stack
```

and my code is:

```
#[derive(Clone, Copy)]
pub struct Something;
impl Something {
  pub const fn copy(&self) -> Self {
      *self
  }
}

pub const CLOSURE: &'static dyn Fn(&mut u8) = &(|_| ());
const BASE : Something = Something{};

const COPY : (&'static dyn Fn(&mut u8), &'static Something) = (CLOSURE, &(BASE.copy()) );
```

I need both parts or the COPY tuple for the error to trigger and I'm unsure why. And also, if I put `&(BASE.copy()` in its own  const the bug is not triggered.

**Comment by JohnTitor** [comment] 2021-08-15 21:47
Triage: No longer ICE with the latest nightly, I guess #87795 fixed it? Marking as `E-needs-test`.

**Closed** 2022-05-28 01:37 UTC
Labels: I-ICE, E-needs-test, P-medium, A-borrow-checker, T-compiler, regression-from-stable-to-stable, C-bug, glacier, F-min_const_generics, const-generics-bad-diagnostics
