### ISSUE TITLE
Rustc scoping regression

### ISSUE THREAD

**Issue by Rupsbant** [rust-lang/rust#40235] opened 2017-03-03 14:42 UTC
The following code does not compile with `rustc 1.17.0-nightly (c0b7112ba 2017-03-02)`. Compiles with `stable-x86_64-unknown-linux-gnu unchanged - rustc 1.14.0 (e8a012324 2016-12-16)`. Testing with updated stable release.

```
fn n(c: u64) -> u64 {
    c
}
pub fn main() {
    let v = vec![1,2,3];
    let mut it = v.iter();
    while let Some(n) = it.next() {
        println!("{}", n);
    }
    assert!(n(1) == 1);
}
```

**Comment by alexcrichton** [comment] 2017-03-03 15:11
cc @jseyfried

**Comment by TimNN** [comment] 2017-03-03 15:23
Slightly minified:

```rust
fn foo() {}

pub fn main() {
    while let Some(foo) = Some(1) {
        break;
    }
    foo();
}
```

Introduced between `nightly-2017-02-25` and `nightly-2017-02-27` ([changes](https://github.com/rust-lang/rust/compare/08230775a...60a0edc6c)).

After skimming the PR's merged during that time I guess this was caused by #39864.

**Comment by alexcrichton** [comment] 2017-03-03 15:26
cc @cramertj

**Comment by cramertj** [comment] 2017-03-03 17:14
I think the problem is [this missing `Ribs` line.](https://github.com/rust-lang/rust/pull/39864/files#diff-aeb0880081a991f34aef2ab889e1fb7aL2844) I fixed it locally and am currently testing.

**Comment by cramertj** [comment] 2017-03-03 17:42
Confirmed the fix and opened #40242.

**Comment by cramertj** [comment] 2017-03-03 18:29
Somewhat interestingly, there was a successful crater run done on that PR. IIUC, that means that @Rupsbant's [PR](https://github.com/bluss/petgraph/pull/127) just happens to be the first time anyone has added code like this to a crate.

**Comment by Rupsbant** [comment] 2017-03-04 11:56
@cramertj This bug originates from petgraph and was committed 5 months ago: bluss/petgraph@c85e189ca391710a1b585e6b9f97bf59053c117f. It was tested in the crater run and succeeded.

**Closed** 2017-03-04 12:33 UTC
Labels: I-wrong, regression-from-stable-to-nightly, T-compiler

**Comment by bluss** [comment] 2017-03-06 16:50
Crater doesn't run tests, it only compiles crates. the new cargobomb util addresses that.
