### ISSUE TITLE
rustc suggests to use a trait bound that is already present

### ISSUE THREAD

**Issue by grahamgower** [rust-lang/rust#77114] opened 2020-09-23 15:48 UTC
I tried this code:

```rust
fn idigits<T>(d: Vec<T>) -> u64
    where T: std::ops::Add<T>
{
    d.iter().fold(0_u64, |acc, x| x + 10*acc)
}
```

I hoped rustc would suggestion to me what the correct trait bound is for the addition. rustc spoke thus:
```
error[E0369]: cannot add `u64` to `&T`
  --> src/grg/misc.rs:32:37
   |
32 |     d.iter().fold(0_u64, |acc, x| x + 10*acc)
   |                                   - ^ ------ u64
   |                                   |
   |                                   &T
   |
help: consider further restricting this bound
   |
30 |     where T: std::ops::Add<T> + std::ops::Add<Output = u64>
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So I added the suggested trait bound, and reran rustc. To my surprise, I got the exact same suggestion!

```
error[E0369]: cannot add `u64` to `&T`
  --> src/grg/misc.rs:32:37
   |
32 |     d.iter().fold(0_u64, |acc, x| x + 10*acc)
   |                                   - ^ ------ u64
   |                                   |
   |                                   &T
   |
help: consider further restricting this bound
   |
30 |     where T: std::ops::Add<T> + std::ops::Add<Output = u64> + std::ops::Add<Output = u64>
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (0da580074 2020-09-22)
binary: rustc
commit-hash: 0da58007451a154da2480160429e1604a1f5f0ec
commit-date: 2020-09-22
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

**Comment by jonas-schievink** [comment] 2020-09-23 15:53
Thanks for the report! This looks like a duplicate of https://github.com/rust-lang/rust/issues/76539, however, so closing in favor of that.

Please leave a comment on that issue if you have more information to contribute.

**Closed by jonas-schievink** 2020-09-23 15:53 UTC
Labels: C-bug
