### ISSUE TITLE
The `push_*` printing in `librustc_monomorphize` should use the printing infrastructure

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#60582] opened 2019-05-06 13:56 UTC
E.g. `push_const_name` here:
https://github.com/rust-lang/rust/blob/d98a165e39a3634eeac2b1f35c81560f5a7e8ded/src/librustc_mir/monomorphize/item.rs#L398
See https://github.com/rust-lang/rust/pull/53645#discussion_r281194070.

**Comment by eddyb** [comment] 2019-05-06 17:04
I didn't mean const printing, sorry. But rather that entire `push_*` stuff, which was hacked together for the monomorphization collector but can now use the printing infrastructure.

**Comment by Mark-Simulacrum** [comment] 2019-06-22 00:42
This code now lives in https://github.com/rust-lang/rust/blob/929b48ec98aaff2239257574b5897f419cec2647/src/librustc/ty/print/obsolete.rs as far as I can tell, so this is probably a duplicate of https://github.com/rust-lang/rust/issues/61139 at this point. Closing as such.

**Closed by Mark-Simulacrum** 2019-06-22 00:42 UTC
Labels: C-cleanup, T-compiler
