### ISSUE TITLE
pretty printer ICE on large const-expr summation

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#24579] opened 2015-04-18 23:50 UTC
(imported from improperly closed bug #17406)

This code:

``` rust
static I104: int =
    0 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
        + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 +
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
        + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 +
        1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
        + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1;

fn main() {
}
```

when I hit the "format" button in the [playpen](http://is.gd/2Y1VHZ) (which I assume just calls `rustc -Z unstable-options --pretty`), it ICEs.

**Comment by pnkfelix** [comment] 2015-10-28 16:20
(the new playpen doesn't have a format button anymore ...)

**Comment by pnkfelix** [comment] 2015-10-28 16:31
Here is a way to emulate the problem in the playpen nonetheless (by creating the file in question and manually invoking rustc's pretty-printer to expose the ICE): http://is.gd/OF0lBs

**Comment by pmarcelll** [comment] 2017-03-11 14:33
Triage: I can't reproduce it.

**Comment by Mark-Simulacrum** [comment] 2017-06-12 22:54
Cannot reproduce -- closing.

**Closed by Mark-Simulacrum** 2017-06-12 22:54 UTC
Labels: I-ICE
