### ISSUE TITLE
std::time is stunted

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#17536] opened 2014-09-25 18:10 UTC
The only thing std::time contains is [`Duration`](http://doc.rust-lang.org/std/time/duration/struct.Duration.html), which isn't too useful on its own. The real meat of it is in [`::time`](http://doc.rust-lang.org/time/index.html).

Perhaps one should be moved into the other?

Alternatively, we can add some docs to `Duration` that explain how to work with it. One common way of getting a `Duration` is to subtract two instances of `time::now().to_timespec()`s, however this is completely not obvious on `std::time`. I don't mind adding these docs.

**Comment by steveklabnik** [comment] 2015-01-29 00:15
This is effectively a duplicate of https://github.com/rust-lang/rfcs/issues/619 today, so I'm giving it a close.

**Closed by steveklabnik** 2015-01-29 00:15 UTC
