### ISSUE TITLE
Simple async wrapper doubles the size of a future

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#72454] opened 2020-05-22 05:21 UTC
I'm using the following wrapper function:
```
pub async fn log_error<F>(future: F)
where
    F: Future<Output = Result<(), Box<dyn Error + Send + Sync + 'static>>>
{
    if let Err(err) = future.await {
        print_error(err);
    }
}
```

Using `std::mem::size_of_val`, the size of any future returned by this function is a bit more than twice the size of the future passed to it. This is a pretty severe penalty for a simple helper function.

**Comment by jonas-schievink** [comment] 2020-05-22 11:29
Duplicate of https://github.com/rust-lang/rust/issues/62958

**Closed by jonas-schievink** 2020-05-22 11:29 UTC
Labels: A-async-await, C-bug, I-heavy, T-compiler
