### ISSUE TITLE
Silent overflow on debug beta/nightly

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#36110] opened 2016-08-29 17:57 UTC
The standard wishlist

``` rust
fn main() {
    let mut it = 255u8..;
    println!("{:?}", it.next());
}
```

no longer panics, but AFAICT from the code this is not due to any deliberate change. The Iterator implementation is start.add_one()/swap, and add_one() is self + 1. This sounds like some overflow checks are being lost somehow.

**Comment by TimNN** [comment] 2016-08-29 18:46
related: #35589

**Comment by durka** [comment] 2016-08-31 15:50
This was indeed caused by MIR:

    seas779:cargo-script alex$ RUSTFLAGS=-Zorbit=off mr ru nightly-2016-08-23 cargo script --force --use-shared-binary-cache no --debug -e '(255u8..).next()'
       Compiling expr v0.1.0 (file:///Users/alex/.multirust/toolchains/nightly-2016-08-23/cargo/.cargo/script-cache/expr-24db503e5185c33f)
        Finished debug [unoptimized + debuginfo] target(s) in 0.41 secs
    thread 'main' panicked at 'attempt to add with overflow', ../src/libcore/iter/range.rs:103
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    seas779:cargo-script alex$ RUSTFLAGS=-Zorbit=on mr ru nightly-2016-08-23 cargo script --force --use-shared-binary-cache no --debug -e '(255u8..).next()'
       Compiling expr v0.1.0 (file:///Users/alex/.multirust/toolchains/nightly-2016-08-23/cargo/.cargo/script-cache/expr-24db503e5185c33f)
        Finished debug [unoptimized + debuginfo] target(s) in 0.39 secs
    Some(255)

cc @eddyb

**Comment by eddyb** [comment] 2016-08-31 21:33
Missing [`#[rustc_inherit_overflow_checks]`](https://github.com/rust-lang/rust/blob/7a187c39c79e21cd61d1688d449bdd52d7510281/src/libcore/iter/mod.rs#L1106) on the `Step` methods that do arithmetic (`add_one` and `sub_one`), introduced in #34530.

**Comment by ashrko619** [comment] 2016-09-01 04:56
Can I work on this ?

**Comment by eddyb** [comment] 2016-09-01 04:58
@ashrko619 Sure! The only change needed here is adding `#[rustc_inherit_overflow_checks]` before those 2 methods in all 3 implementations of `Step` and writing a test (not sure if it can be `#[test]` - cc @rust-lang/libs).

**Comment by ashrko619** [comment] 2016-09-01 05:12
@eddyb Thanks. About the test - why shouldn't it be ```#[test]``` ?

**Comment by eddyb** [comment] 2016-09-01 05:33
I don't know where we can put a `#[test]` for this, that's all. Also, it's dependent on having it in a separate crate, so `#[test]` might invalidate that requirement (i.e. it would have a local copy of `Step`).

However, it looks like [`libcoretest` has the tests](https://github.com/rust-lang/rust/blob/3135b7877a66e72ac4833588eb8654aa155876e8/src/libcoretest/iter.rs#L885) and it's a separate crate, so you should be able to add a test in that file.

**Comment by matthew-piziak** [comment] 2016-09-09 16:35
@ashrko619 Any update on this issue? If not I might like to work on it.

**Comment by ashrko619** [comment] 2016-09-11 03:51
@matthew-piziak Feel free to work on it. I have been caught up at work this week :)

**Comment by cramertj** [comment] 2017-01-24 07:37
@matthew-piziak Is issue fixed? I noticed your PR said "part of"-- is there more that needs to be done?

**Comment by matthew-piziak** [comment] 2017-01-24 15:34
@cramertj I _think_ we're done here. The "part of" idiom is just to identify the parent of the PR.

@talchas @eddyb What still needs to be done for this issue, if anything?

**Comment by brson** [comment] 2017-02-24 21:16
Closing per @matthew-piziak !

**Closed by brson** 2017-02-24 21:16 UTC
Labels: A-libs, E-easy
