### ISSUE TITLE
Type inference regression from 1.14.0 to 1.15.0

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#41194] opened 2017-04-10 19:40 UTC
This code:
```rust
struct S {
    v: Vec<(u32, Vec<u32>)>,
}

impl S {
    pub fn remove(&mut self, i: u32) -> Option<std::vec::Drain<u32>> {
        self.v.get_mut(i as _ /*usize*/).map(|&mut (_, ref mut v2)| {
            v2.drain(..)
        })
    }
}
```
stopped compiling in 1.15.0 with:
```
error: the type of this value must be known in this context
 --> src/main.rs:8:16
  |
8 |             v2.drain(..)
  |                ^^^^^
```

If you change the cast on line 7 to the concrete type `usize`, it compiles fine on 1.15.0 (and later)

**Comment by alexcrichton** [comment] 2017-04-10 20:51
Almost surely caused by https://github.com/rust-lang/rust/pull/36340, so nominating for libs discussion.

@jethrogb we're unlikely to revert the change as this is a routine "type inference can break from time to time", but if you have difficulty fixing this please let us know as it'd affect our discussion!

**Comment by jethrogb** [comment] 2017-04-10 21:00
It turned out to be an easy fix, but here's some points for your discussion:
* The fix would've been easier if the error was in the right place.
* If this code would've been in a public crate on crates.io at the time that PR was considered, what would've happenned?

**Comment by nagisa** [comment] 2017-04-10 21:21
> If this code would've been in a public crate on crates.io at the time that PR was considered, what would've happenned?

crater would’ve caught it and we would send PR/ping before the relevant version of rustc gets released as a stable version.

**Comment by alexcrichton** [comment] 2017-04-12 22:05
Ok we discussed this during libs triage the other day, and the conclusion was to close this. The known regressions have been fixed and we'd otherwise categorize this under "known breakage".

If this comes up over time though please let us know as we're always interested in understanding when changes like this cause problems!

**Closed by alexcrichton** 2017-04-12 22:05 UTC
Labels: I-nominated, regression-from-stable-to-stable, T-libs
