### ISSUE TITLE
ICE on trait with mixed lifetimes

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#27989] opened 2015-08-25 00:20 UTC
This code generates

```rust
trait Y<'a>: Sized {
    fn f(&'a self) {
    }
    
    fn g(&self) where Self: for<'r> Y<'r> {
        self.f();
    }
}
```

this ICE

```txt
<anon>:6:14: 6:17 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `Y<'_>` for the type `Self`
<anon>:6         self.f();
                      ^~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/diagnostic.rs:176


playpen: application terminated with error code 101
```

**Comment by frewsxcv** [comment] 2015-08-25 01:44
for the lazy: [playpen link](http://is.gd/E6cUtw)

**Comment by frewsxcv** [comment] 2015-08-25 01:50
reduced:

```rust
trait Y<'a>: Sized {
    fn g() where Self: for<'r> Y<'r> {
    }
}

fn main() {}
```

[playpen link](http://is.gd/fQzu7O)

**Comment by arielb1** [comment] 2015-08-25 14:44
Duplicate of #24424

**Closed** 2015-08-25 16:41 UTC
Labels: I-ICE
