### ISSUE TITLE
no ImplicitCtxt stored in tls

### ISSUE THREAD

**Issue by nadenf** [rust-lang/rust#117854] opened 2023-11-12 20:40 UTC
### Meta

`rustc --version --verbose`:
```
rustc 1.76.0-nightly (2c1b65ee1 2023-11-11)
binary: rustc
commit-hash: 2c1b65ee1431f8d3fe2142e821eb13c623bbf8a0
commit-date: 2023-11-11
host: aarch64-apple-darwin
release: 1.76.0-nightly
LLVM version: 17.0.4
```

`compiler flags`:
```
--crate-type lib -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -Z threads=16
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at /rustc/2c1b65ee1431f8d3fe2142e821eb13c623bbf8a0/compiler/rustc_middle/src/ty/context/tls.rs:111:50:
no ImplicitCtxt stored in tls
stack backtrace:
   0:        0x101a95314 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb9ebedcbc23b10d0
   1:        0x101ad72d8 - core::fmt::write::he0b2e8e8c929d646
   2:        0x101a8ba48 - std::io::Write::write_fmt::h0960618879d4216c
   3:        0x101a95150 - std::sys_common::backtrace::print::h68d22bbf1485ed7a
   4:        0x101a97b50 - std::panicking::default_hook::{{closure}}::h323a3c9be995dd8d
   5:        0x101a97898 - std::panicking::default_hook::h3178081fe3d6696e
   6:        0x10aeb3d50 - <alloc[3eec36f0695f91dd]::boxed::Box<rustc_driver_impl[b18e1ff6c233986d]::install_ice_hook::{closure#0}> as core[a3728727bc16c43f]::ops::function::Fn<(&dyn for<'a, 'b> core[a3728727bc16c43f]::ops::function::Fn<(&'a core[a3728727bc16c43f]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[a3728727bc16c43f]::marker::Sync + core[a3728727bc16c43f]::marker::Send, &core[a3728727bc16c43f]::panic::panic_info::PanicInfo)>>::call
   7:        0x101a981c8 - std::panicking::rust_panic_with_hook::hb82fa29ca1cfd15b
   8:        0x101a97f90 - std::panicking::begin_panic_handler::{{closure}}::hba8a5811f2860467
   9:        0x101a9577c - std::sys_common::backtrace::__rust_end_short_backtrace::h8d6f5d4f0729b511
  10:        0x101a97d2c - _rust_begin_unwind
  11:        0x101af1128 - core::panicking::panic_fmt::hec9d5dd17af33c2f
  12:        0x101af10f4 - core::option::expect_failed::h00cb97ef1c9c64c0
  13:        0x10ae5212c - rustc_interface[cd87de0d474aaed5]::util::run_in_thread_pool_with_globals::<rustc_interface[cd87de0d474aaed5]::interface::run_compiler<core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>, rustc_driver_impl[b18e1ff6c233986d]::run_compiler::{closure#1}>::{closure#0}, core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>>::{closure#2}
  14:        0x10ebb2060 - <rayon_core[c1c5018790b12f77]::sleep::Sleep>::sleep
  15:        0x10ebb1568 - <rayon_core[c1c5018790b12f77]::registry::WorkerThread>::wait_until_cold
  16:        0x10a59d8dc - <rayon_core[c1c5018790b12f77]::registry::ThreadBuilder>::run
  17:        0x10ae68d14 - rustc_span[27a5aeb524309f01]::set_session_globals_then::<(), rustc_interface[cd87de0d474aaed5]::util::run_in_thread_pool_with_globals<rustc_interface[cd87de0d474aaed5]::interface::run_compiler<(), rustc_driver_impl[b18e1ff6c233986d]::run_compiler::{closure#0}>::{closure#0}, ()>::{closure#3}::{closure#0}::{closure#0}::{closure#0}>
  18:        0x10ae524a8 - <<crossbeam_utils[70aa5f493d0c7305]::thread::ScopedThreadBuilder>::spawn<<rayon_core[c1c5018790b12f77]::ThreadPoolBuilder>::build_scoped<rustc_interface[cd87de0d474aaed5]::util::run_in_thread_pool_with_globals<rustc_interface[cd87de0d474aaed5]::interface::run_compiler<core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>, rustc_driver_impl[b18e1ff6c233986d]::run_compiler::{closure#1}>::{closure#0}, core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#0}, rustc_interface[cd87de0d474aaed5]::util::run_in_thread_pool_with_globals<rustc_interface[cd87de0d474aaed5]::interface::run_compiler<core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>, rustc_driver_impl[b18e1ff6c233986d]::run_compiler::{closure#1}>::{closure#0}, core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>>::{closure#3}::{closure#0}::{closure#1}, core[a3728727bc16c43f]::result::Result<(), rustc_span[27a5aeb524309f01]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0} as core[a3728727bc16c43f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  19:        0x10ae6fc68 - std[f3dc86d6d90ad197]::sys_common::backtrace::__rust_begin_short_backtrace::<alloc[3eec36f0695f91dd]::boxed::Box<dyn core[a3728727bc16c43f]::ops::function::FnOnce<(), Output = ()> + core[a3728727bc16c43f]::marker::Send>, ()>
  20:        0x10aea284c - <<std[f3dc86d6d90ad197]::thread::Builder>::spawn_unchecked_<alloc[3eec36f0695f91dd]::boxed::Box<dyn core[a3728727bc16c43f]::ops::function::FnOnce<(), Output = ()> + core[a3728727bc16c43f]::marker::Send>, ()>::{closure#1} as core[a3728727bc16c43f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  21:        0x101aa03c4 - std::sys::unix::thread::Thread::new::thread_start::hbf1197f3e522c03d
  22:        0x18a871034 - __pthread_joiner_wake
```

</p>
</details>
[rustc-ice-2023-11-12T20_38_52-47886.txt](https://github.com/rust-lang/rust/files/13329102/rustc-ice-2023-11-12T20_38_52-47886.txt)

**Comment by petrochenkov** [comment] 2024-01-05 23:28
Duplicate of https://github.com/rust-lang/rust/issues/111522.

**Closed by petrochenkov** 2024-01-05 23:28 UTC
Labels: I-ICE, T-compiler, C-bug, WG-compiler-parallel
