### ISSUE TITLE
Compiler panic on 1.8.0-nightly 2016-02-09

### ISSUE THREAD

**Issue by lilred** [rust-lang/rust#31558] opened 2016-02-11 03:14 UTC
On `rustc 1.8.0-nightly (32b2ef7ad 2016-02-09)`
    
    cargo rustc --target x86_64-unknown-xen -- -Z no-landing-pads
       Compiling alloc v0.1.0 (https://github.com/phil-opp/nightly-liballoc.git#71c37961)
    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    thread 'rustc' panicked at 'box_free language item is missing', ../src/libcore/option.rs:704
    stack backtrace:
       1:     0x7fb482c18800 - sys::backtrace::tracing::imp::write::h558d5f2978e55ac4ttu
       2:     0x7fb482c2039b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43238
       3:     0x7fb482c1fef3 - panicking::default_handler::hbf3975cab47e4b81VWy
       4:     0x7fb482be9dac - sys_common::unwind::begin_unwind_inner::h78f1521fe1f5d27biit
       5:     0x7fb482bea848 - sys_common::unwind::begin_unwind_fmt::h964018da5137d3feoht
       6:     0x7fb482c16301 - rust_begin_unwind
       7:     0x7fb482c66d9f - panicking::panic_fmt::h7eb7bd8738a5380b6YL
       8:     0x7fb482c868a4 - option::expect_failed::h87adce2046c3981eftO
       9:     0x7fb480dd2fba - build::scope::Builder<'a, 'tcx>::diverge_cleanup::h3921300aec2fd7f1Gad
      10:     0x7fb480db1db0 - build::scope::Builder<'a, 'tcx>::pop_scope::h0625f1997c9b671ae0c
      11:     0x7fb480dcd114 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb4bdf6637f5f62157a
      12:     0x7fb480dc731c - build::expr::as_rvalue::Builder<'a, 'tcx>::expr_as_rvalue::_$u7b$$u7b$closure$u7d$$u7d$::closure.19098
      13:     0x7fb480dbe7db - build::expr::as_rvalue::Builder<'a, 'tcx>::expr_as_rvalue::h0ab94e6328799876oCa
      14:     0x7fb480dcc923 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb4bdf6637f5f62157a
      15:     0x7fb480db54de - build::into::ExprRef<'tcx>.EvalInto<'tcx>::eval_into::h8d4f8b6bb51503d78pb
      16:     0x7fb480dcd103 - build::expr::into::Builder<'a, 'tcx>::into_expr::hdb4bdf6637f5f62157a
      17:     0x7fb480db54de - build::into::ExprRef<'tcx>.EvalInto<'tcx>::eval_into::h8d4f8b6bb51503d78pb
      18:     0x7fb480db2ed9 - build::block::Builder<'a, 'tcx>::ast_block::he45b75545bd4b7c3Cka
      19:     0x7fb480dae858 - build::construct::he10071c6f2b0cbfedca
      20:     0x7fb480df870e - mir_map::InnerDump<'a, 'm, 'tcx>.Visitor<'tcx>::visit_fn::hd88910231bcdb938iqg
      21:     0x7fb480e00017 - mir_map::OuterDump<'a, 'tcx>.Visitor<'tcx>::visit_impl_item::h856797710c67276bKog
      22:     0x7fb480df6b51 - mir_map::OuterDump<'a, 'tcx>.Visitor<'tcx>::visit_item::h86492f3725319a14tng
      23:     0x7fb480df5b9b - mir_map::build_mir_for_crate::h28ba6c860f5d5b74Clg
      24:     0x7fb48313131f - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.27964
      25:     0x7fb48312d20e - middle::ty::context::ctxt<'tcx>::create_and_enter::h5439679730299442922
      26:     0x7fb483129363 - driver::phase_3_run_analysis_passes::h12589397492560770879
      27:     0x7fb4830fc0d8 - driver::compile_input::hb24a9d779e578b83Bca
      28:     0x7fb4830ec3e8 - run_compiler::hf1f6ba491f28518acHc
      29:     0x7fb4830e98d1 - sys_common::unwind::try::try_fn::h10141810680521866859
      30:     0x7fb482c1628b - __rust_try
      31:     0x7fb482c0e7cd - sys_common::unwind::inner_try::h876b2793e1ec4011kft
      32:     0x7fb4830ea120 - boxed::F.FnBox<A>::call_box::h14464204619411869790
      33:     0x7fb482c1e960 - sys::thread::Thread::new::thread_start::h36aef2efeb591414fUx
      34:     0x7fb47b3fa6a9 - start_thread
      35:     0x7fb482896eec - clone
      36:                0x0 - <unknown>
    
    Could not compile `alloc`.
    
    To learn more, run the command again with --verbose.
    build/Rust.mk:14: recipe for target 'target/x86_64-unknown-xen/debug/crust' failed
    make: *** [target/x86_64-unknown-xen/debug/crust] Error 101

Repro at https://github.com/CRust-OS/CRust-OS/tree/0210-rustc-bug (not at all minimal, sorry in advance)

**Comment by durka** [comment] 2016-02-11 03:16
duplicate of #31477

**Closed** 2016-02-11 03:18 UTC
