### ISSUE TITLE
Range::step_by(0) loops forever

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#26239] opened 2015-06-12 08:04 UTC
I believe that the step_by(_) method of ranges should `panic!` if the argument is zero. Currently it loops forever, which is a footgun. At the very least, iterating over such a StepBy should `panic!` on debug builds. However, I think the earlier the error appears, the better.

Note that this may require us to specialize `step_by` to types whose `Add` implementation have a known [identity element](http://en.wikipedia.org/wiki/Identity_element) – at the moment that would mean bounding by the `num::Zero` trait, which is unstable, also it would probably reduce the usefulness of ranges to numeric types. However, special casing numeric ranges could solve this.

I have also filed an [issue](https://github.com/Manishearth/rust-clippy/issues/95) at rust-clippy to create a lint for cases where it can be statically detected. Still, that lint cannot detect cases where the argument is calculated at runtime.

The documentation of `.step_by(_)` should at least warn of the possibility of looping forever or panic once it is implemented.

**Comment by Thiez** [comment] 2015-06-12 09:14
There is nothing unsafe about looping forever, so I strongly oppose a `panic!()`. As a user I would expect `(a..b).step_by(c).take(n)` to work for all `c`, without having to special case for `c == 0`..

**Comment by llogiq** [comment] 2015-06-12 09:26
@Thiez: Agreed, this is not inherently *unsafe*. So maybe `panic!()` on building the StepBy is not the right option. Still, there are enough options to loop forever already, and as I said, the docs should at least remind the reader that supplying `0` as an argument creates an infinite range.

It may also be useful to be able to issue a warning on debug builds iff a `StepBy { step_by: 0, .. } is actually iterated; perhaps as an additional Debug option.

**Comment by alexcrichton** [comment] 2015-06-12 16:52
This is currently intended behavior, and for now I'm going to close this in favor of the [discussion in stabilizing `step_by`](https://internals.rust-lang.org/t/step-by-on-negative-numbers/2231/6) as this is definitely a useful data point, but perhaps not big enough to have its own issue right now.

**Closed by alexcrichton** 2015-06-12 16:52 UTC
