### ISSUE TITLE
Overflow while adding drop-check rules.

### ISSUE THREAD

**Issue by kaminsod** [rust-lang/rust#33545] opened 2016-05-10 20:24 UTC
Not sure if this is a bug or something I missed in my code, but seems to be the same as #29844. Issue present in stable, beta and nightly.

https://play.rust-lang.org/?gist=5d30e353c7fac8f23e871367f774f9b0&version=stable&backtrace=0

``` rust
#[derive(Debug)]
enum E1<T> {
    V1(T),
    V2(Box<E1<E2<T>>>)
}

#[derive(Debug)]
enum E2<T> {
    V1(usize, T),
    V2(usize, T, T)
}

fn main() {
    let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));

    println!("{:?}", wub);
}
```

Issues on stable (similar issues on beta and nightly):

> <anon>:14:9: 14:12 error: overflow while adding drop-check rules for E1<&str> [E0320]
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                   ^~~
> <anon>:14:9: 14:12 note: overflowed on enum E2 variant V1 field #0 type: usize
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                   ^~~
> <anon>:14:15: 14:57 error: overflow while adding drop-check rules for E1<&str> [E0320]
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> <anon>:14:15: 14:57 note: overflowed on enum E2 variant V1 field #0 type: usize
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> <anon>:14:22: 14:56 error: overflow while adding drop-check rules for Box<E1<E2<&str>>> [E0320]
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> <anon>:14:22: 14:56 note: overflowed on enum E1 variant V1 field #0 type: E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<E2<&str>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> <anon>:14:31: 14:55 error: overflow while adding drop-check rules for E1<E2<&str>> [E0320]
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));
>                                         ^~~~~~~~~~~~~~~~~~~~~~~~
> <anon>:14:31: 14:55 note: overflowed on enum E2 variant V1 field #0 type: usize
> <anon>:14     let wub = E1::V2(Box::new(E1::V1(E2::V1(1, "wub"))));

**Comment by kaminsod** [comment] 2016-05-10 21:12
Slightly simplified version of code producing same issue.

```rust
#[derive(Debug)]
enum A<T> {
    A1(T),
    A2(Box<A<B<T>>>)
}

#[derive(Debug)]
enum B<T> {
    B(T),
}

fn main() {
    let wub = A::A2(Box::new(A::A1(B::B("wub"))));

    println!("{:?}", wub);
}
```

https://play.rust-lang.org/?gist=25c40a3bfec6dc2962c55695c96af44c&version=stable&backtrace=0

**Comment by nagisa** [comment] 2016-05-10 21:44
Even more minimal:

```rust
enum A<T> {
    A1(T),
    A2(Box<A<::std::marker::PhantomData<T>>>)
}

fn main() {
    A::A1(());
}
```

**Comment by pnkfelix** [comment] 2016-05-10 21:45
I think this is a duplicate of #4287

**Comment by Mark-Simulacrum** [comment] 2017-05-04 00:34
Closing in favor of #4287.

**Closed by Mark-Simulacrum** 2017-05-04 00:34 UTC
Labels: A-diagnostics
