### ISSUE TITLE
rustc error inside chroot

### ISSUE THREAD

**Issue by rjohari23** [rust-lang/rust#66153] opened 2019-11-06 12:00 UTC
I am trying to compile rust code using rust compiler (rustc) but it is giving the below error.

**rust.rs**
```
fn main() {
    println!("Hello, world from Rust!");
}
```

**command**
```
rustc -o rust_main rust.rs
```

**error**
```
thread 'rustc' panicked at 'failed to get current_exe: no /proc/self/exe available. Is /proc mounted?', src/librustc/session/filesearch.rs:139:23
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0 running on x86_64-unknown-linux-gnu
```

Any help would be appreciated!
Thanks in advance,

**Comment by sfackler** [comment] 2019-11-06 12:05
The compiler expects the `/proc` pseudo-filesystem to be acessible: http://man7.org/linux/man-pages/man5/proc.5.html

**Comment by rjohari23** [comment] 2019-11-06 12:23
> The compiler expects the `/proc` pseudo-filesystem to be acessible: http://man7.org/linux/man-pages/man5/proc.5.html

proc is mounted inside chroot but still it is the same issue.

**Comment by jonas-schievink** [comment] 2019-11-06 13:05
Can you provide full instructions for reproducing this, including how the chroot was set up and entered? Can you also run `stat /proc/self/exe` and post the output of that?

**Comment by rjohari23** [comment] 2019-11-06 13:53
**entering chroot as**
```
chroot /chroot/domjudge
```

**mounting proc as**
```
sudo -n mount -n --bind /proc proc < /dev/null
```


**error after compile**
```
thread '<unnamed>' panicked at 'src/librustc_codegen_ssa/back/write.rs:1548: worker thread panicked', src/librustc/util/bug.rs:37:26 note: Runwith `RUST_BACKTRACE=1` environment variable to display a backtrace. error: could not write output to rust_main.1qz2con1ykhpg24i.rcgu.o: Permission denied error: aborting due to previous error
```

**Comment by sfackler** [comment] 2019-11-06 13:58
That is not the same error.

**Comment by nagisa** [comment] 2019-11-06 14:29
It also appears to be a user error wherein the location compiler expects to be writable is not.

**Comment by pnkfelix** [comment] 2019-11-07 14:13
This is suspected to be a user error, but maybe we should be giving better diagnostics nonetheless for such a situation.

triage: P-medium. Assigning to self.

**Comment by Raatty** [comment] 2020-04-27 03:52
```
thread 'rustc' panicked at 'failed to get realpath: No such file or directory (os error 2)', src/librustc_session/filesearch.rs:123:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
```
different error but also chroot, caused by an empty /proc because i forgot to mount it, maybe a better error message be nice like at least print the path that doesn't exist before panicking

**Comment by Enselic** [comment] 2023-08-24 17:42
Triage: The instructions on how to reproduce are incomplete. For starters, how is /chroot/domjudge popuplated?

@pnkfelix I suspect you didn't have time to look into this despite self-assigning?

**Comment by Enselic** [comment] 2023-10-12 04:37
Triage: Closing as not reproducible.

**Closed by Enselic** 2023-10-12 04:37 UTC
Labels: I-ICE, P-medium, T-compiler, C-bug
