### ISSUE TITLE
rustc panic with error "src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<T as data_type::DataType>)),depth=0),Unimplemented)]` resolving bounds after type-checking"

### ISSUE THREAD

**Issue by sunchao** [rust-lang/rust#43377] opened 2017-07-21 04:47 UTC
Just did `rustup update` today and got the following error while compiling my project with `RUST_BACKTRACE=full cargo build`. It used to be fine.
```
error: internal compiler error: src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<T as data_type::DataType>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (ae98ebfcb 2017-07-20) running on x86_64-apple-darwin

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:437:8
stack backtrace:
   0:        0x10a1ac1e3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h429df91372efc84c
   1:        0x10a1b9b3a - std::panicking::default_hook::{{closure}}::h8557ed0f281544bf
   2:        0x10a1b962b - std::panicking::default_hook::h9b9c764f09fdb424
   3:        0x10a1bbe12 - std::panicking::rust_panic_with_hook::hc31844f8e88f8142
   4:        0x108ba2adb - std::panicking::begin_panic_new::h16b2d97326dc54fe
   5:        0x108b8cd92 - rustc_errors::Handler::span_bug::h72b86846429f5b9a
   6:        0x108ddc2ca - rustc::session::opt_span_bug_fmt::{{closure}}::h94b190ff11f4eaf5
   7:        0x108ddc1b8 - rustc::session::opt_span_bug_fmt::he1e74edea23ec913
   8:        0x108ddc037 - rustc::session::span_bug_fmt::h7070da128b213faf
   9:        0x108e9e600 - <&'gcx rustc::ty::TyS<'gcx> as rustc::infer::TransNormalize<'gcx>>::trans_normalize::h277f38d9300e7fa3
  10:        0x108d517d6 - rustc::infer::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'tcx>>::normalize_associated_type_in_env::h6be12ad00e46f499
  11:        0x108e3cd5a - rustc::ty::layout::Layout::compute_uncached::he221331865ca5f50
  12:        0x108e62d4d - rustc::ty::util::layout_raw::hf64c3fda0557e731
  13:        0x108f15105 - rustc::ty::maps::<impl rustc::ty::maps::queries::layout_raw<'tcx>>::try_get::ha1ef458e73e72d94
  14:        0x108f23a85 - rustc::ty::maps::TyCtxtAt::layout_raw::h5dcc333076c9e029
  15:        0x108f1de15 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::layout_raw::h39f3174c177887df
  16:        0x104e2906c - rustc_const_eval::eval::eval_const_expr_partial::{{closure}}::hfa2d938ae064f9c4
  17:        0x104e22217 - rustc_const_eval::eval::eval_const_expr_partial::h1e6c919863ab5bd4
  18:        0x104e21e02 - rustc_const_eval::eval::eval_const_expr_partial::h1e6c919863ab5bd4
  19:        0x104e21e02 - rustc_const_eval::eval::eval_const_expr_partial::h1e6c919863ab5bd4
  20:        0x104e2611e - rustc_const_eval::eval::eval_const_expr_partial::h1e6c919863ab5bd4
  21:        0x104e2143b - rustc_const_eval::eval::ConstContext::eval::hb761c25ac4e7961f
  22:        0x104dbe4dd - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  23:        0x104dbdf5e - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  24:        0x104dbe365 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  25:        0x104dbe157 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  26:        0x104dbdf27 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  27:        0x104dbe09e - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  28:        0x104dbe157 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  29:        0x104dbe157 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h7a3b0b4024a638f1
  30:        0x104dbcdc9 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h38a91ae2fa176cd4
  31:        0x104dbf0ab - rustc_passes::consts::check_crate::h05b390fb47c06d30
  32:        0x1047bf14b - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::hb1c1d0eb7ac5c887
  33:        0x1047acb62 - rustc_driver::driver::phase_3_run_analysis_passes::h9994922fd3b8a782
  34:        0x10478eef5 - rustc_driver::driver::compile_input::h87812fb3cc538ca9
  35:        0x1047d4590 - rustc_driver::run_compiler::h27af08b507285c3e
  36:        0x1046f1229 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb4b1e34c3602f1ac
  37:        0x10a1ebe5c - __rust_maybe_catch_panic
  38:        0x104729b4f - <F as alloc::boxed::FnBox<A>>::call_box::h63f4992ca584bc92
  39:        0x10a1b8adb - std::sys::imp::thread::Thread::new::thread_start::h1eee904918ebae85
  40:     0x7fffad27a9ae - _pthread_body
  41:     0x7fffad27a8fa - _pthread_start
```

Output from `rustc --version --verbose`:
```
rustc 1.20.0-nightly (ae98ebfcb 2017-07-20)
binary: rustc
commit-hash: ae98ebfcb9ad5a5384fd229a6ee91315b02ca969
commit-date: 2017-07-20
host: x86_64-apple-darwin
release: 1.20.0-nightly
LLVM version: 4.0
```

**Comment by sciyoshi** [comment] 2017-07-21 04:56
Seeing this same error when trying to compile [ethcore](https://github.com/paritytech/parity/tree/master/ethcore)

**Comment by saethlin** [comment] 2017-07-21 06:07
Same error when trying to compile [matrixmultiply](https://github.com/bluss/matrixmultiply)

**Comment by qnighy** [comment] 2017-07-21 06:24
Related to or a duplicate of #43357 ?

**Comment by saethlin** [comment] 2017-07-21 06:26
Duplicate, but it's still around in the new nightly
```
rustc 1.20.0-nightly (ae98ebfcb 2017-07-20)
binary: rustc
commit-hash: ae98ebfcb9ad5a5384fd229a6ee91315b02ca969
commit-date: 2017-07-20
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0
```

**Comment by Mark-Simulacrum** [comment] 2017-07-21 15:20
Closing as a duplicate. Thanks for filing!

**Closed by Mark-Simulacrum** 2017-07-21 15:20 UTC
