### ISSUE TITLE
Add an API for lazy-cloning the key in a HashMap

### ISSUE THREAD

**Issue by Yoric** [rust-lang/rust#42505] opened 2017-06-07 13:25 UTC
Consider the following snippet:

```rust
let mut map = HashMap::new();
// ...
for key in foo.iter() {
  // This loop is performance-critical.
  map.entry(key.clone()).or_insert(0)
}
```

This snippet requires us to always clone `key`, even if the key is already present in `map`. In a short program I recently wrote, in which the same value of `key` appeared quite often in `foo`, this proved much more slower than:

```rust
for key in foo.iter() {
  // This loop is performance-critical.

  if map.get(key).is_none() { // Two lookups in `map`, but only one call to `clone`.
    map.insert(key.clone(), 0);
  }
}
```

I believe that we can do better by introducing an API along the lines of

```rust
pub fn lazy_entry(&mut self, key: &K) -> LazyEntry<K, V> where K: Clone
```

The behavior of `LazyEntry` being the same as `Entry`, except for the fact that cloning takes place only if the code attempts to insert in a `Vacant` `LazyEntry`.

**Comment by Mark-Simulacrum** [comment] 2017-06-07 13:30
Closing as a duplicate of https://github.com/rust-lang/rust/issues/35463, see also https://github.com/rust-lang/rfcs/pull/1769.

**Closed by Mark-Simulacrum** 2017-06-07 13:30 UTC

**Comment by Yoric** [comment] 2017-06-07 13:33
Thanks.
