### ISSUE TITLE
ICE on Nightly

### ISSUE THREAD

**Issue by AldaronLau** [rust-lang/rust#79492] opened 2020-11-28 08:12 UTC
### Code

Not quite sure how to make a minimal example for this, but I discovered the issue in this CI run: https://github.com/libcala/wavy/runs/1466769605?check_suite_focus=true

### Meta

`rustc --version --verbose`:
```
2020-11-28, rust version 1.50.0-nightly (6a889570e 2020-11-27)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:124 ~ wavy[cdf4]::ffi::asound::)`,
 right: `DefId(0:125 ~ wavy[cdf4]::ffi::asound::::free)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (6a889570e 2020-11-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [index_hir] index HIR
#1 [hir_owner] HIR owner of `{misc#0}`
end of query stack
error: could not compile `wavy`
Error: could not compile `wavy`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-11-28 12:53
duplicate of https://github.com/rust-lang/rust/issues/79487

**Closed by jonas-schievink** 2020-11-28 12:53 UTC
Labels: C-bug, I-ICE, T-compiler
