### ISSUE TITLE
ICE triggered by RPITIT function parameter

### ISSUE THREAD

**Issue by tamasfe** [rust-lang/rust#104878] opened 2022-11-25 10:05 UTC
I hit an ICE with RPITIT and async_functions_in_trait.

### Code

Unfortunately I have no exact repro yet, everything I tried compiles, but some combination triggers the ICE in a larger code base. Hopefully the traces can help track it down.

```Rust
// Take the following trait def.
//
// It has implementers, appears in generic parameters
trait Foo<T> {
    fn foo(&self, val: Option<impl Into<String>>) -> impl Future<Output = ()> + Send + '_;
}

// It has implementers like:
impl<T> Foo<T> for MyFoo {
    fn foo(&self, val: Option<impl Into<String>>) -> impl Future<Output = ()> + Send + '_ {
        let val = val.map(Into::into);
        async move {
            // ...
        }
    }  
}

// The following parameter change triggered the ICE:
trait Foo<T> {
    fn foo(&self, val: Option<&str>) -> impl Future<Output = ()> + Send + '_;
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (ff8c8dfbe 2022-11-22)
binary: rustc
commit-hash: ff8c8dfbe66701531e3e5e335c28c544d0fbc945
commit-date: 2022-11-22
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Error output

```
error: internal compiler error: /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/compiler/rustc_middle/src/ty/visit.rs:103:17: expect tcx.sess.has_errors return true

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (ff8c8dfbe 2022-11-22) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C codegen-units=512 -C debuginfo=2 -C linker=clang -C incremental=[REDACTED] -C link-arg=-fuse-ld=/usr/bin/mold

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task`
#1 [thir_body] building THIR for `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task`
#2 [mir_built] building MIR for `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task`
#3 [unsafety_check_result] unsafety-checking `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task`
#4 [mir_const] preparing `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task` for borrow checking
#5 [mir_promoted] processing MIR for `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task`
#6 [mir_borrowck] borrow-checking `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task`
#7 [type_of] computing type of `client::memory::<impl at crates/ora/ora-client/src/client/memory.rs:58:1: 58:38>::cancel_task::{opaque#0}`
#8 [check_mod_item_types] checking item types in module `client::memory`
#9 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/compiler/rustc_errors/src/lib.rs:1560:9
stack backtrace:
   0:     0x7f5082c71bb0 - std::backtrace_rs::backtrace::libunwind::trace::h8706adb1093146ed
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5082c71bb0 - std::backtrace_rs::backtrace::trace_unsynchronized::hf63de70ab53f1103
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5082c71bb0 - std::sys_common::backtrace::_print_fmt::h5957d298699ffe59
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f5082c71bb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcd957416de719678
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f507ec7965e - core::fmt::write::h984028dcea06bcfd
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f5082c65d85 - std::io::Write::write_fmt::he809968620ea8258
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/io/mod.rs:1682:15
   6:     0x7f5082c71975 - std::sys_common::backtrace::_print::hb0bd3686578e8d46
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f5082c71975 - std::sys_common::backtrace::print::hc5833b565793a292
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f5082c73c8f - std::panicking::default_hook::{{closure}}::h74c2f33bce600c62
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/panicking.rs:267:22
   9:     0x7f5082c739ca - std::panicking::default_hook::hfe2fefb386033115
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/panicking.rs:286:9
  10:     0x7f5081ece464 - <rustc_driver[9074794128a33992]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[f8fd3abe6b5d63cf]::ops::function::FnOnce<(&core[f8fd3abe6b5d63cf]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f5082c7447d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7730b0c8dcf873c1
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/alloc/src/boxed.rs:2032:9
  12:     0x7f5082c7447d - std::panicking::rust_panic_with_hook::he2509c58eec530df
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/panicking.rs:692:13
  13:     0x7f508231a8e1 - std[1e9db942fc5862bc]::panicking::begin_panic::<rustc_errors[962da50c5f46999b]::ExplicitBug>::{closure#0}
  14:     0x7f5082316ef6 - std[1e9db942fc5862bc]::sys_common::backtrace::__rust_end_short_backtrace::<std[1e9db942fc5862bc]::panicking::begin_panic<rustc_errors[962da50c5f46999b]::ExplicitBug>::{closure#0}, !>
  15:     0x7f5082368036 - std[1e9db942fc5862bc]::panicking::begin_panic::<rustc_errors[962da50c5f46999b]::ExplicitBug>
  16:     0x7f5082314956 - std[1e9db942fc5862bc]::panic::panic_any::<rustc_errors[962da50c5f46999b]::ExplicitBug>
  17:     0x7f5082314884 - <rustc_errors[962da50c5f46999b]::HandlerInner>::bug::<&alloc[9f61cdb96537af8e]::string::String>
  18:     0x7f50823144f0 - <rustc_errors[962da50c5f46999b]::Handler>::bug::<&alloc[9f61cdb96537af8e]::string::String>
  19:     0x7f50823c765d - rustc_middle[10860b0b9ad25f4]::ty::context::tls::with_context_opt::<rustc_middle[10860b0b9ad25f4]::ty::context::tls::with_opt<rustc_middle[10860b0b9ad25f4]::util::bug::opt_span_bug_fmt<rustc_span[452fb2538b9e8b2]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7f50823c7826 - rustc_middle[10860b0b9ad25f4]::util::bug::opt_span_bug_fmt::<rustc_span[452fb2538b9e8b2]::span_encoding::Span>
  21:     0x7f50805f3b73 - rustc_middle[10860b0b9ad25f4]::util::bug::bug_fmt
  22:     0x7f50801081db - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  23:     0x7f508059be2c - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_argument_types
  24:     0x7f508056f68e - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_call
  25:     0x7f50800fd9b9 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f508015845a - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  27:     0x7f50800ffada - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f508013adcc - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_block_with_expected
  29:     0x7f50800fe0fa - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:     0x7f5080101b67 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  31:     0x7f508013adcc - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_block_with_expected
  32:     0x7f50800fe0fa - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  33:     0x7f508015889d - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_match::{closure#0}
  34:     0x7f50800ffada - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  35:     0x7f508013adcc - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_block_with_expected
  36:     0x7f50800fe0fa - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:     0x7f50800e2846 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_return_expr
  38:     0x7f50800da332 - rustc_hir_typeck[2151af4c1ff040ad]::check::check_fn
  39:     0x7f5080177313 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_closure
  40:     0x7f5080101db1 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  41:     0x7f508059be2c - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_argument_types
  42:     0x7f508056f68e - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_call
  43:     0x7f50800fd9b9 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  44:     0x7f508013dbd2 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_decl
  45:     0x7f508013ac5e - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_block_with_expected
  46:     0x7f50800fe0fa - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  47:     0x7f50800e2846 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_return_expr
  48:     0x7f50800da332 - rustc_hir_typeck[2151af4c1ff040ad]::check::check_fn
  49:     0x7f5080177313 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_closure
  50:     0x7f5080101db1 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  51:     0x7f508059be2c - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_argument_types
  52:     0x7f508056f68e - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_call
  53:     0x7f50800fd9b9 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  54:     0x7f508013adcc - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_block_with_expected
  55:     0x7f50800fe0fa - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  56:     0x7f50800e2846 - <rustc_hir_typeck[2151af4c1ff040ad]::fn_ctxt::FnCtxt>::check_return_expr
  57:     0x7f50800da332 - rustc_hir_typeck[2151af4c1ff040ad]::check::check_fn
  58:     0x7f50800c8402 - <rustc_hir_typeck[2151af4c1ff040ad]::inherited::InheritedBuilder>::enter::<rustc_hir_typeck[2151af4c1ff040ad]::typeck_with_fallback<rustc_hir_typeck[2151af4c1ff040ad]::typeck::{closure#0}>::{closure#0}::{closure#1}, &rustc_middle[10860b0b9ad25f4]::ty::context::TypeckResults>
  59:     0x7f50800b9bab - rustc_hir_typeck[2151af4c1ff040ad]::typeck
  60:     0x7f50800c48e3 - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, &rustc_middle[10860b0b9ad25f4]::ty::context::TypeckResults>
  61:     0x7f50800b8364 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, &rustc_middle[10860b0b9ad25f4]::ty::context::TypeckResults>>
  62:     0x7f50818ad7ae - <rustc_query_impl[ab82b08c50b5ae34]::Queries as rustc_middle[10860b0b9ad25f4]::ty::query::QueryEngine>::typeck
  63:     0x7f5080760a5d - rustc_mir_build[abf21aab83edd7d4]::thir::cx::thir_body
  64:     0x7f5080f0e80c - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, core[f8fd3abe6b5d63cf]::result::Result<(&rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::thir::Thir>, rustc_middle[10860b0b9ad25f4]::thir::ExprId), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>
  65:     0x7f5080f063c7 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, core[f8fd3abe6b5d63cf]::result::Result<(&rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::thir::Thir>, rustc_middle[10860b0b9ad25f4]::thir::ExprId), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>>
  66:     0x7f5080efede3 - rustc_mir_build[abf21aab83edd7d4]::build::mir_built
  67:     0x7f5080e8b36c - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, &rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::mir::Body>>
  68:     0x7f5080e89f83 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, &rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::mir::Body>>>
  69:     0x7f5080e96045 - rustc_mir_transform[d07c6609224a5665]::check_unsafety::unsafety_check_result
  70:     0x7f5080e90828 - <rustc_mir_transform[d07c6609224a5665]::check_unsafety::provide::{closure#0} as core[f8fd3abe6b5d63cf]::ops::function::FnOnce<(rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::LocalDefId)>>::call_once
  71:     0x7f5080e95883 - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, &rustc_middle[10860b0b9ad25f4]::mir::query::UnsafetyCheckResult>
  72:     0x7f5080e8fd74 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, &rustc_middle[10860b0b9ad25f4]::mir::query::UnsafetyCheckResult>>
  73:     0x7f5080e8cfdb - rustc_mir_transform[d07c6609224a5665]::mir_const
  74:     0x7f5080e8b36c - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, &rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::mir::Body>>
  75:     0x7f5080e89f83 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, &rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::mir::Body>>>
  76:     0x7f5080d7c54f - rustc_mir_transform[d07c6609224a5665]::mir_promoted
  77:     0x7f5080d7bbbc - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, (&rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::mir::Body>, &rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_index[d838bdf4a7ea1602]::vec::IndexVec<rustc_middle[10860b0b9ad25f4]::mir::Promoted, rustc_middle[10860b0b9ad25f4]::mir::Body>>)>
  78:     0x7f5080d7a92b - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_middle[10860b0b9ad25f4]::ty::WithOptConstParam<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId>, (&rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_middle[10860b0b9ad25f4]::mir::Body>, &rustc_data_structures[62268d5764f625d4]::steal::Steal<rustc_index[d838bdf4a7ea1602]::vec::IndexVec<rustc_middle[10860b0b9ad25f4]::mir::Promoted, rustc_middle[10860b0b9ad25f4]::mir::Body>>)>>
  79:     0x7f5080d78800 - rustc_borrowck[ced2fe6c82a4cc11]::mir_borrowck
  80:     0x7f5080d782c1 - <rustc_borrowck[ced2fe6c82a4cc11]::provide::{closure#0} as core[f8fd3abe6b5d63cf]::ops::function::FnOnce<(rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::LocalDefId)>>::call_once
  81:     0x7f5080ef0723 - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, &rustc_middle[10860b0b9ad25f4]::mir::query::BorrowCheckResult>
  82:     0x7f5080eef5c3 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, &rustc_middle[10860b0b9ad25f4]::mir::query::BorrowCheckResult>>
  83:     0x7f50818adb58 - <rustc_query_impl[ab82b08c50b5ae34]::Queries as rustc_middle[10860b0b9ad25f4]::ty::query::QueryEngine>::mir_borrowck
  84:     0x7f5081704586 - rustc_hir_analysis[67af8bfa51b12d99]::collect::type_of::type_of
  85:     0x7f50806f02c3 - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::DefId, rustc_middle[10860b0b9ad25f4]::ty::Ty>
  86:     0x7f50806ed905 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::get_query::<rustc_query_impl[ab82b08c50b5ae34]::queries::type_of, rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt>
  87:     0x7f5080f53c69 - rustc_hir_analysis[67af8bfa51b12d99]::check::check::check_mod_item_types
  88:     0x7f508073f9e3 - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, ()>
  89:     0x7f508073da6e - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<rustc_span[452fb2538b9e8b2]::def_id::LocalDefId, ()>>
  90:     0x7f50812fe2e9 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::get_query::<rustc_query_impl[ab82b08c50b5ae34]::queries::check_mod_item_types, rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt>
  91:     0x7f50802ddd37 - <rustc_session[60eb0f9dbaf3963]::session::Session>::time::<(), rustc_hir_analysis[67af8bfa51b12d99]::check_crate::{closure#6}>
  92:     0x7f50802dcb84 - rustc_hir_analysis[67af8bfa51b12d99]::check_crate
  93:     0x7f50802dc80b - rustc_interface[6b7eaaa4ad5b511f]::passes::analysis
  94:     0x7f50816c6c4e - <rustc_query_system[5a7ebb5f2835af36]::dep_graph::graph::DepGraph<rustc_middle[10860b0b9ad25f4]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[10860b0b9ad25f4]::ty::context::TyCtxt, (), core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>
  95:     0x7f50816c5fc4 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::try_execute_query::<rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt, rustc_query_system[5a7ebb5f2835af36]::query::caches::DefaultCache<(), core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>>
  96:     0x7f50816c5a47 - rustc_query_system[5a7ebb5f2835af36]::query::plumbing::get_query::<rustc_query_impl[ab82b08c50b5ae34]::queries::analysis, rustc_query_impl[ab82b08c50b5ae34]::plumbing::QueryCtxt>
  97:     0x7f508119310d - <rustc_interface[6b7eaaa4ad5b511f]::passes::QueryContext>::enter::<rustc_driver[9074794128a33992]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>
  98:     0x7f508118f34f - <rustc_interface[6b7eaaa4ad5b511f]::interface::Compiler>::enter::<rustc_driver[9074794128a33992]::run_compiler::{closure#1}::{closure#2}, core[f8fd3abe6b5d63cf]::result::Result<core[f8fd3abe6b5d63cf]::option::Option<rustc_interface[6b7eaaa4ad5b511f]::queries::Linker>, rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>
  99:     0x7f508118a382 - rustc_span[452fb2538b9e8b2]::with_source_map::<core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>, rustc_interface[6b7eaaa4ad5b511f]::interface::run_compiler<core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>, rustc_driver[9074794128a33992]::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
 100:     0x7f5081189e79 - <scoped_tls[d8d79e187ce2c7fa]::ScopedKey<rustc_span[452fb2538b9e8b2]::SessionGlobals>>::set::<rustc_interface[6b7eaaa4ad5b511f]::interface::run_compiler<core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>, rustc_driver[9074794128a33992]::run_compiler::{closure#1}>::{closure#0}, core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>
 101:     0x7f5081189488 - std[1e9db942fc5862bc]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[6b7eaaa4ad5b511f]::util::run_in_thread_pool_with_globals<rustc_interface[6b7eaaa4ad5b511f]::interface::run_compiler<core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>, rustc_driver[9074794128a33992]::run_compiler::{closure#1}>::{closure#0}, core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>
 102:     0x7f50811891ac - <<std[1e9db942fc5862bc]::thread::Builder>::spawn_unchecked_<rustc_interface[6b7eaaa4ad5b511f]::util::run_in_thread_pool_with_globals<rustc_interface[6b7eaaa4ad5b511f]::interface::run_compiler<core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>, rustc_driver[9074794128a33992]::run_compiler::{closure#1}>::{closure#0}, core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f8fd3abe6b5d63cf]::result::Result<(), rustc_errors[962da50c5f46999b]::ErrorGuaranteed>>::{closure#1} as core[f8fd3abe6b5d63cf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 103:     0x7f5082c7b733 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1b5a13ff0dfa7f2f
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/alloc/src/boxed.rs:2000:9
 104:     0x7f5082c7b733 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hba33c2ecbf5798cf
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/alloc/src/boxed.rs:2000:9
 105:     0x7f5082c7b733 - std::sys::unix::thread::Thread::new::thread_start::hb6c57436b925359e
                               at /rustc/ff8c8dfbe66701531e3e5e335c28c544d0fbc945/library/std/src/sys/unix/thread.rs:108:17
 106:     0x7f507e97c8fd - <unknown>
 107:     0x7f507e9fea60 - <unknown>
 108:                0x0 - <unknown>
```

</p>
</details>

**Comment by compiler-errors** [comment] 2022-12-17 18:16
I cannot reproduce this. @tamasfe, if you have the full codebase to share, or still encounter this bug on the latest nightly, please let me know.

**Comment by tamasfe** [comment] 2022-12-18 11:19
Unfortunately I haven't been able to reproduce it either since then, not even in the larger codebase. I'll make sure to come back to this once I manage to trigger it again.

**Comment by compiler-errors** [comment] 2022-12-18 19:05
Gonna close this then -- feel free to reopen an issue and tag me if you encounter it again.

**Closed** 2022-12-18 19:05 UTC
Labels: I-ICE, T-compiler, C-bug
