### ISSUE TITLE
Spurious access violation (exit code: 3221225477) when compiling libsyntax with MSVC

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#50604] opened 2018-05-10 10:26 UTC
Symptom: On MSVC builders (Windows), when compiling libsyntax in either stage0 or stage1, the compiler `rustc` will crash with exit code 3221225477 (= 0xc0000005 = access violation). 

We suspect this is related to #50329 (merged at 2018-05-02T10:13:06Z).

<details><summary>Sample crash log</summary>

```
error: Could not compile `syntax`.
Caused by:
  process didn't exit successfully: `C:\projects\rust\build\bootstrap/debug/rustc --crate-name syntax libsyntax\lib.rs --color always --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C metadata=7ac7668085f2897f -C extra-filename=-7ac7668085f2897f --out-dir C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps --target i686-pc-windows-msvc -L dependency=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps -L dependency=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\release\deps --extern bitflags=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\libbitflags-9ba1f7028730cd0a.rlib --extern log=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\liblog-001e68131969f2ec.rlib --extern rustc_errors=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\rustc_errors-ffee8b3fc130b2b1.dll --extern syntax_pos=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\syntax_pos-1048adc53f632b89.dll --extern rustc_data_structures=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\rustc_data_structures-3a7257003acd8e8b.dll --extern scoped_tls=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\libscoped_tls-49f5fac2ae1c97d0.rlib --extern serialize=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\serialize-f37b7ca68fe29329.dll --extern serialize=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\libserialize-f37b7ca68fe29329.rlib --extern rustc_target=C:\projects\rust\build\i686-pc-windows-msvc\stage0-rustc\i686-pc-windows-msvc\release\deps\rustc_target-63878e92b639df83.dll` (exit code: 3221225477)
command did not execute successfully: "C:\\projects\\rust\\build\\i686-pc-windows-msvc\\stage0/bin\\cargo.exe" "build" "--target" "i686-pc-windows-msvc" "-j" "4" "--release" "--locked" "--color" "always" "--features" "" "--manifest-path" "C:\\projects\\rust\\src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap\compile.rs:1091:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

</details>

First seen on the following PRs:

* https://github.com/rust-lang/rust/pull/50503#issuecomment-387208721 (2018-05-07T21:14:30Z)
* https://github.com/rust-lang/rust/pull/50161#issuecomment-387980444 (2018-05-10T07:52:11Z)

cc #33434 (parent issue)

**Comment by ishitatsuyuki** [comment] 2018-05-10 10:48
cc @Zoxc Can you try to reproduce?

**Comment by Zoxc** [comment] 2018-05-10 15:32
I haven't seen this locally. Does it happen often?

**Comment by kennytm** [comment] 2018-05-10 15:39
As shown in the post, twice in the last 8 days so far. There are 3 other segfaults on Windows which might also be attributed here (https://github.com/rust-lang/rust/pull/50000#issuecomment-386269731, https://github.com/rust-lang/rust/pull/50418#issuecomment-386582312, https://github.com/rust-lang/rust/pull/50466#issuecomment-386852611).

**Comment by ishitatsuyuki** [comment] 2018-05-19 07:50
Have this occurred this week?

**Comment by kennytm** [comment] 2018-05-19 08:27
@ishitatsuyuki No

**Comment by steveklabnik** [comment] 2019-09-24 02:01
It's been a while; has anyone seen this lately?

**Comment by DhruvDh** [comment] 2020-02-19 15:53
```
error: process didn't exit successfully: `target\release\dip_viewer.exe -f easy.txt` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

happens at [this code](https://github.com/DhruvDh/dip_image_viewer) when running on particular machines build with `--release`.
Building without release gives -

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', C:\Users\ddhamani\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.4.2\src\hub.rs:120:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\dip_viewer.exe -f easy.txt` (exit code: 101)
```

but it works fine on my laptop. This happens due to missing something wgpu dynamically links against?

**Comment by kennytm** [comment] 2020-02-19 16:00
@DhruvDh hi, could you file a new issue for that? This issue only tracks spurious failure from the CI and thus unsuitable for problems in user code.

**Comment by DhruvDh** [comment] 2020-02-19 16:47
sorry, I did not realize that.

**Comment by crlf0710** [comment] 2021-06-13 07:11
Now that libsyntax is now renamed and splitted and crates structure changed a lot since then, i'd suggest we just close this?

**Closed** 2021-06-15 09:28 UTC
Labels: A-spurious, C-tracking-issue, O-windows-msvc, T-compiler, T-infra
