### ISSUE TITLE
Doctests failure in 54 crates in Rust 1.26

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49935] opened 2018-04-13 14:23 UTC
Rust 1.26 started testing more code blocks in the documentation. There was a warning in the previous releases about that, and this issue exists to notify crater authors about this.

* [ ] [anl](https://crates.io/crates/anl) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/anl-0.3.0/log.txt)) cc @snuk182
* [ ] [arraymap](https://crates.io/crates/arraymap) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/arraymap-0.1.0/log.txt)) cc @llogiq
* [ ] [asynchronous](https://crates.io/crates/asynchronous) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/asynchronous-0.4.5/log.txt)) cc @bcndanos
* [x] [blob-uuid](https://crates.io/crates/blob-uuid) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/blob-uuid-0.2.0/log.txt)) cc @ivanceras
* [x] [build_const](https://crates.io/crates/build_const) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/build_const-0.2.0/log.txt))
* [ ] [chiter](https://crates.io/crates/chiter) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/chiter-0.2.0/log.txt)) cc @boatboatboatboat
* [ ] [citadel](https://crates.io/crates/citadel) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/citadel-0.2.0/log.txt)) cc @natepisarski
* [ ] [cldap](https://crates.io/crates/cldap) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/cldap-0.1.0/log.txt)) cc @rossdylan
* [ ] [comp](https://crates.io/crates/comp) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/comp-0.2.1/log.txt)) cc @goandylok
* [ ] [config](https://crates.io/crates/config) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/config-0.8.0/log.txt)) cc @filipegoncalves
* [ ] [context_bind](https://crates.io/crates/context_bind) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/context_bind-0.0.2/log.txt)) cc @valarauca
* [ ] [cpp_utils](https://crates.io/crates/cpp_utils) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/cpp_utils-0.2.0/log.txt)) cc @Riateche
* [ ] [etrace](https://crates.io/crates/etrace) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/etrace-0.2.7/log.txt)) cc @KizzyCode
* [ ] [fastcgi](https://crates.io/crates/fastcgi) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/fastcgi-1.0.0-beta/log.txt)) cc @mohtar
* [ ] [flatbuffers-rust](https://crates.io/crates/flatbuffers-rust) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/flatbuffers-rust-0.1.2/log.txt)) cc @SleepPerformer
* [ ] [grafen](https://crates.io/crates/grafen) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/grafen-0.9.1/log.txt)) cc @pjohansson
* [ ] [hdf5](https://crates.io/crates/hdf5) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/hdf5-0.4.1/log.txt)) cc @IvanUkhov
* [x] [mg-settings](https://crates.io/crates/mg-settings) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/mg-settings-0.4.2/log.txt)) cc @antoyo
* [x] [multiaddr](https://crates.io/crates/multiaddr) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/multiaddr-0.3.0/log.txt)) cc @dignifiedquire
* [ ] [netbuf](https://crates.io/crates/netbuf) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/netbuf-0.4.0/log.txt)) cc @tailhook
* [x] [ngrammatic](https://crates.io/crates/ngrammatic) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/ngrammatic-0.3.0/log.txt)) cc @compenguy
* [ ] [onig_sys](https://crates.io/crates/onig_sys) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/onig_sys-68.0.1/log.txt)) cc @defuz
* [x] [openssl](https://crates.io/crates/openssl) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/openssl-0.9.24/log.txt)) cc @sfackler
* [ ] [optional](https://crates.io/crates/optional) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/optional-0.3.0/log.txt)) cc @llogiq
* [ ] [outils](https://crates.io/crates/outils) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/outils-0.1.0/log.txt)) cc @ouaffm
* [x] [panic-control](https://crates.io/crates/panic-control) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/panic-control-0.1.3/log.txt)) cc @mzabaluev
* [ ] [piston2d-graphics](https://crates.io/crates/piston2d-graphics) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/piston2d-graphics-0.26.0/log.txt)) cc @bvssvni
* [ ] [pretty](https://crates.io/crates/pretty) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/pretty-0.3.3/log.txt)) cc @Marwes
* [x] [query](https://crates.io/crates/query) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/query-0.1.2/log.txt)) cc @asynts
* [x] [queues](https://crates.io/crates/queues) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/queues-1.0.1/log.txt)) cc @savish
* [ ] [restson](https://crates.io/crates/restson) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/restson-0.2.0/log.txt)) cc @spietika
* [ ] [rotor-carbon](https://crates.io/crates/rotor-carbon) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/rotor-carbon-0.7.0/log.txt)) cc @tailhook
* [ ] [runtime-loop](https://crates.io/crates/runtime-loop) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/runtime-loop-0.0.3/log.txt)) cc @zutils
* [x] ~~[sacn](https://crates.io/crates/sacn) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/sacn-0.4.4/log.txt))~~ spurious failure
* [x] [seq](https://crates.io/crates/seq) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/seq-0.4.0/log.txt)) cc @frehberg
* [ ] [slime](https://crates.io/crates/slime) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/slime-0.4.0/log.txt)) cc @jaroslaw-weber
* [x] [slippy-map-tiles](https://crates.io/crates/slippy-map-tiles) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/slippy-map-tiles-0.14.0/log.txt))
* [x] [snes-bitplanes](https://crates.io/crates/snes-bitplanes) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/snes-bitplanes-0.2.0/log.txt)) cc @TooManyBees
* [ ] [spider](https://crates.io/crates/spider) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/spider-1.1.1/log.txt)) cc @madeindjs
* [x] [splay_tree](https://crates.io/crates/splay_tree) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/splay_tree-0.2.9/log.txt)) cc @silenuss 
* [x] [swagger](https://crates.io/crates/swagger) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/swagger-0.10.0/log.txt)) cc @bjgill
* [ ] [symbolic-debuginfo](https://crates.io/crates/symbolic-debuginfo) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/symbolic-debuginfo-3.0.1/log.txt)) cc @getsentry-bot
* [ ] [symbolics_calculus](https://crates.io/crates/symbolics_calculus) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/symbolics_calculus-0.1.0/log.txt)) cc @Nazek42
* [ ] [syntex_pos](https://crates.io/crates/syntex_pos) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/syntex_pos-0.59.1/log.txt)) cc @dtolnay
* [ ] [sysconf](https://crates.io/crates/sysconf) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/sysconf-0.3.1/log.txt)) cc @gmjosack
* [ ] [thrussh](https://crates.io/crates/thrussh) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/thrussh-0.16.2/log.txt)) cc @P-E-Meunier
* [ ] [timi](https://crates.io/crates/timi) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/timi-0.2.1/log.txt)) cc @bollu
* [ ] [tk-http](https://crates.io/crates/tk-http) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/tk-http-0.3.8/log.txt)) cc @tailhook
* [ ] [trace-macro](https://crates.io/crates/trace-macro) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/trace-macro-1.1.1/log.txt)) cc @DoumanAsh
* [x] [ucg](https://crates.io/crates/ucg) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/ucg-0.0.4/log.txt)) cc @zaphar
* [ ] [unique-type-id](https://crates.io/crates/unique-type-id) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/unique-type-id-0.2.0/log.txt)) cc @vityafx
* [ ] [users](https://crates.io/crates/users) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/users-0.5.3/log.txt)) cc @ogham
* [x] [waltz](https://crates.io/crates/waltz) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/waltz-0.3.0/log.txt)) cc @killercup

**Possible unrelated regressions:**

* [ ] [srp](https://crates.io/crates/srp) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/srp-0.2.4/log.txt)) cc @newpavlov

**Comment by newpavlov** [comment] 2018-04-13 14:37
In case of `srp`, at first glance it looks like there is a bug around tables, because at [line 35](https://github.com/RustCrypto/PAKE/blob/master/srp/src/lib.rs#L35)  there is nothing similar to code blocks.

**Comment by pietroalbini** [comment] 2018-04-13 14:41
Ugh, thanks for pointing that out! I didn't fully analyze all the 54 crates while triaging (just checked if it was a doctest compile error), but maybe someone should actually do that...

**Comment by vitiral** [comment] 2018-04-13 14:45
`build_const` fixed in https://github.com/vitiral/build_const/commit/5a3d8ffec23a8e59aeeef7591d100e72e0280c7e in version `0.2.1`

**Comment by killercup** [comment] 2018-04-13 14:56
Uhh, waltz's tests work and the log even says so? Not sure what's up the other output in the log, though

**Comment by rory** [comment] 2018-04-13 15:01
Thanks for the notification and spotting this. I've fixed the bug in `slippy-map-tiles`

**Comment by pietroalbini** [comment] 2018-04-13 15:07
> Uhh, waltz's tests work and the log even says so? Not sure what's up the other output in the log, though

Sorry, there was a bug in the script I used to generate the list from the crate names, and it picked up the log for the latest version while the bug was in a previous one. Fixed the bug and updated the list.

**Comment by killercup** [comment] 2018-04-13 15:11
> picked up the log for the latest version while the bug was in a previous one

@pietroalbini ah okay, that makes sense. I have no intention of updating that 0.3 release, though, as there are no crate that depend on it…

**Comment by lschmierer** [comment] 2018-04-13 15:41
`sacn` is actually not a doctest failure

Tests just fail if `RUST_TEST_THREADS` > 1

**Comment by pietroalbini** [comment] 2018-04-13 15:46
> sacn is actually not a doctest failure

Sorry for the notification! I'll configure crater to avoid running your crate's test suite in the future.

**Comment by vityafx** [comment] 2018-04-13 15:52
Could anyone help me with fixing this regression? I have a proc-macro crate and the directory structure as the following:

|--Cargo.toml
|--unique-type-id/Cargo.toml (provides `trait` and docs)
|--unique-type-id-derive/Cargot.toml (provides procedural macro implementation)

The doc test fails in `unique-type-id` because it can't find `unique-type-id-derive` crate. How do I fix this?

The repository is [here](https://crates.io/crates/unique-type-id).

**Comment by sfackler** [comment] 2018-04-13 15:59
The openssl failure is on an old release and has since been fixed.

**Comment by sile** [comment] 2018-04-14 02:05
I fixed the problem in `splay_tree`. Thanks for the notification.

**Comment by TooManyBees** [comment] 2018-04-14 05:00
Fixed `snes-bitplanes`. Monospaced text started getting run as a doc test without realizing it.

**Comment by asynts** [comment] 2018-04-14 08:00
I've yanked `query`. Thanks for the notification.

**Comment by mzabaluev** [comment] 2018-04-14 09:27
Fixed `panic-control` in version 0.1.4. The actual issue was that a `compile_fail` example stopped failing due to an expected feature having landed in Rust 1.26.

**Comment by savish** [comment] 2018-04-14 09:54
Fixed `queues` in version 1.0.2. No more warnings on `cargo doc`

**Comment by newpavlov** [comment] 2018-04-14 10:09
`srp` is fixed in `v0.2.5`, issues were with table formatting.

**Comment by llogiq** [comment] 2018-04-14 13:48
Thanks! I've fixed arraymap and bumped the version to 0.1.1.

**Comment by spietika** [comment] 2018-04-14 14:04
For `restson` it doesn't seem like doctest failure. At the moment the tests are not fully self-contained and they make outgoing HTTP requests (which probably explains the  HttpError(408) in build log). I ran the tests with both stable and beta locally and they pass. Nevertheless, thanks for the notification. It doesn't hurt to double check.

**Comment by compenguy** [comment] 2018-04-14 20:09
I just published an updated build of ngrammatic (0.3.1) with fixes to the
doctests.

**Comment by antoyo** [comment] 2018-04-14 20:38
`mg-settings` sohuld be fixed in version 0.4.3.

**Comment by tailhook** [comment] 2018-04-14 21:14
Thanks! `netbuf` and `tk-http` are updated now. `rotor-carbon` is unmaintained. Is it a good idea to yank unmaintained projects from crates.io? (I used to think yanking solves a different purpose).

**Comment by pietroalbini** [comment] 2018-04-14 21:29
Thanks to everyone fixing their crates!

> For `restson` it doesn't seem like doctest failure.

@spietika sorry about the notification then! I'll configure crater to avoid running the test suite of your crate to avoid more false positives.

**Comment by Marwes** [comment] 2018-04-14 22:08
`pretty,rs` has been fixed

**Comment by frehberg** [comment] 2018-04-15 23:12
Hello Pietro,

the following crate has been updated

  * seq <https://crates.io/crates/seq>

**Comment by bjgill** [comment] 2018-04-18 15:40
Thanks for the heads-up. `swagger` is now fixed as of 0.11.0

**Comment by dignifiedquire** [comment] 2018-04-21 19:02
Thank you `multiaddr` should be fixed on `master` now.

**Comment by ivanceras** [comment] 2018-04-21 20:03
`blob-uui` has been fixed in `0.2.1`.

**Comment by mohtar** [comment] 2018-04-22 05:08
`fastcgi` author here. The doctest has always failed because the program is supposed to run in a certain condition (some file descriptor needs to be a socket).

However, I'll update the code to actually check for that condition first before proceeding instead of panic.

**Comment by zaphar** [comment] 2018-04-23 23:37
ucg is fixed on master now.

**Closed** 2018-04-26 11:17 UTC
Labels: A-rustdoc, C-bug, I-nominated, T-dev-tools-rustdoc, regression-from-stable-to-beta
