### ISSUE TITLE
ICE: assertion failed: self.hashes.insert(k, v).is_none()

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rust#43259] opened 2017-07-15 23:13 UTC
This ICE happens sometimes when compiling the tests of https://github.com/Marwes/serde/tree/ice. Still investigating as to what is the cause of it though it is likely something to do with custom derive,

```
RUST_BACKTRACE=1 cargo test --all
   Compiling serde_test_suite v0.0.0 (file:///C:/Users/Markus/Dropbox/Programming/serde/test_suite)
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (d84693b93 2017-07-09) running on x86_64-pc-windows-msvc

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: self.hashes.insert(k, v).is_none()', src\librustc_incremental\calculate_svh\mod.rs:70:8
stack backtrace:
   0: _rdl_shrink_in_place
   1: std::panicking::Location::column
   2: std::panicking::Location::column
   3: std::panicking::rust_panic_with_hook
   4: <unknown>
   5: rustc_incremental::calculate_svh::IncrementalHashesMap::insert
   6: <rustc_incremental::calculate_svh::IncrementalHashesMap as core::ops::index::Index<&'a rustc::dep_graph::dep_node::DepNode>>::index
   7: <rustc_incremental::calculate_svh::ComputeItemHashesVisitor<'a, 'tcx> as rustc::hir::itemlikevisit::ItemLikeVisitor<'tcx>>::visit_item
   8: rustc_incremental::calculate_svh::compute_incremental_hashes_map
   9: rustc_driver::driver::count_nodes
  10: rustc_driver::driver::count_nodes
  11: rustc_driver::driver::compile_input
  12: rustc_driver::run_compiler
  13: <unknown>
  14: _rust_maybe_catch_panic
  15: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_trait_item
  16: std::sys::imp::thread::Thread::new
  17: BaseThreadInitThunk

error: Could not compile `serde_test_suite`.
warning: build failed, waiting for other jobs to finish...
```

```
$ rustc --version --verbose
rustc 1.20.0-nightly (d84693b93 2017-07-09)
binary: rustc
commit-hash: d84693b93dae3958e3504f817face0184c5c3fdd
commit-date: 2017-07-09
host: x86_64-pc-windows-msvc
release: 1.20.0-nightly
LLVM version: 4.0

$ cargo --version --verbose
cargo 0.21.0-nightly (70b89fdd7 2017-07-10)
release: 0.21.0
commit-hash: 70b89fdd7e5e77a3b88fc68982861d39d155be29
commit-date: 2017-07-10
```

**Comment by michaelwoerister** [comment] 2017-07-25 06:35
Sounds like two items end up with the same DefId/DefPathHash.

**Comment by quodlibetor** [comment] 2017-07-26 01:54
I am running into this when running tests (but not with just a plain `cargo run` if I copy the test file into a main.rs) with a `Cargo.toml` that includes:

```toml
[dependencies]
diesel = { version = "0.14.0", features = ["sqlite"] }
```

and a `tests/crash.rs` that looks like (note that I've actually deleted all the impls for the MyLargeId that was under test):

```rust
#![feature(main)]
#![feature(box_syntax, structural_match)]
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std as std;
extern crate diesel;

use std::rt;

struct MyLargeId(f64);

#[test]
pub fn can_serialize_large() {
    use diesel::types::ToSql;
    let mut st: Vec<u8> = Vec::new();
    let myid = MyLargeId(11f64);
    <MyLargeId as ToSql<diesel::types::Double, diesel::sqlite::Sqlite>>::to_sql(&myid, &mut st)
        .unwrap();
    {
        match (&st, &<[_]>::into_vec(box [0, 0, 0, 0, 0, 0, 38, 64])) {
            (left_val, right_val) => if !(*left_val == *right_val) {
                {
                    ::rt::begin_panic_fmt(
                        &::std::fmt::Arguments::new_v1(
                            {
                                static __STATIC_FMTSTR: &'static [&'static str] = &[
                                    "assertion failed: `(left == right)`\n  left: `",
                                    "`,\n right: `",
                                    "`",
                                ];
                                __STATIC_FMTSTR
                            },
                            &match (&left_val, &right_val) {
                                (__arg0, __arg1) => [
                                    ::std::fmt::ArgumentV1::new(__arg0, ::std::fmt::Debug::fmt),
                                    ::std::fmt::ArgumentV1::new(__arg1, ::std::fmt::Debug::fmt),
                                ],
                            },
                        ),
                        {
                            static _FILE_LINE_COL: (&'static str, u32, u32) =
                                ("tests/traits.rs", 41u32, 4u32);
                            &_FILE_LINE_COL
                        },
                    )
                }
            },
        }
    };
}
pub mod __test {
    extern crate test;
    #[main]
    pub fn main() -> () {
        test::test_main_static(TESTS)
    }
    const TESTS: &'static [self::test::TestDescAndFn] = &[];
}
```

```
$ RUST_BACKTRACE=full cargo +nightly test
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (598eddf4f 2017-07-24) running on x86_64-apple-darwin

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: self.hashes.insert(k, v).is_none()', src/librustc_incremental/calculate_svh/mod.rs:70:8
stack backtrace:
   0:        0x113179153 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h1c846d30ab9d2835
   1:        0x113186aaa - std::panicking::default_hook::{{closure}}::h5686ff0b2c6e4eb9
   2:        0x11318659b - std::panicking::default_hook::h9f2e51b0fbc325af
   3:        0x113188d82 - std::panicking::rust_panic_with_hook::hd0e3deaa5a3f3a11
   4:        0x1119ee9f7 - std::panicking::begin_panic_new::h9ddc3149addcd00d
   5:        0x111a2de2a - rustc_incremental::calculate_svh::IncrementalHashesMap::insert::h74e01598230aeac9
   6:        0x111a30280 - rustc_incremental::calculate_svh::ComputeItemHashesVisitor::compute_and_store_ich_for_item_like::hf675144d47908776
   7:        0x111a304be - <rustc_incremental::calculate_svh::ComputeItemHashesVisitor<'a, 'tcx> as rustc::hir::itemlikevisit::ItemLikeVisitor<'tcx>>::visit_item::h742bab9c5eaebc0f
   8:        0x111a30cce - rustc_incremental::calculate_svh::compute_incremental_hashes_map::h73e253fb72747d3c
   9:        0x10d7695bf - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h66b2b9a83b85e06c
  10:        0x10d759482 - rustc_driver::driver::phase_3_run_analysis_passes::hc18545f9a6fc068c
  11:        0x10d73fca5 - rustc_driver::driver::compile_input::haa173b6c5d780534
  12:        0x10d7854e0 - rustc_driver::run_compiler::hbd8c2d0cc1d7195f
  13:        0x10d6a2739 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha89ce0330978fd9d
  14:        0x1131b8dcc - __rust_maybe_catch_panic
  15:        0x10d6db3ff - <F as alloc::boxed::FnBox<A>>::call_box::hd33b69fc474605d5
  16:        0x113185a4b - std::sys::imp::thread::Thread::new::thread_start::h657456c8b9cbda9f
  17:     0x7fff8954d99c - _pthread_body
  18:     0x7fff8954d919 - _pthread_start
```

```
rustc 1.20.0-nightly (598eddf4f 2017-07-24)
binary: rustc
commit-hash: 598eddf4f785df12e79fba5a996f153dc6fdb7e0
commit-date: 2017-07-24
host: x86_64-apple-darwin
release: 1.20.0-nightly
LLVM version: 4.0

cargo 0.21.0-nightly (ffab51954 2017-07-18)
release: 0.21.0
commit-hash: ffab51954ec32d55631c37a8730bb24915fc090b
commit-date: 2017-07-18
```

**Comment by quodlibetor** [comment] 2017-07-29 19:57
The newest nightly I'm able to use that doesn't cause this error is nightly-2017-06-13, so I think the error is introduced somewhere in [these commits](https://github.com/rust-lang/rust/compare/cfb5debbc...03abb1bd7) (the difference from `rustc 1.19.0-nightly (cfb5debbc 2017-06-12)` ~ `rustc 1.19.0-nightly (03abb1bd7 2017-06-13)`), which conveniently includes commit d714b9790b  "incr.comp.: Don't use Ident in DefPath because that's unstable across compilation sessions"

**Comment by alexcrichton** [comment] 2017-09-15 14:42
@Marwes and @quodlibetor I can't seem to get anything to compile today mentioned in this thread, and this bug is suspected to be fixed by https://github.com/rust-lang/rust/commit/0cdc58a1bc6ea5ce9ba11c21bfd6d5b85b3efc87. Can either of y'all reproduce this issue on today's nightly? If not, we may be able to close!

**Comment by Marwes** [comment] 2017-09-15 17:48
Managed to get a reproduction with nightly-2017-09-07-x86_64-pc-windows-msvc but nut with the current nightly. Seems to be fixed!

**Comment by alexcrichton** [comment] 2017-09-15 17:52
Awesome, thanks for checking!

**Closed by alexcrichton** 2017-09-15 17:52 UTC
Labels: A-incr-comp, A-macros-2.0, C-bug, I-ICE
