### ISSUE TITLE
hyper not compiling when running "cargo expand"

### ISSUE THREAD

**Issue by zutils** [rust-lang/rust#56776] opened 2018-12-13 12:58 UTC
Checking hyper v0.12.17
    thread 'main' panicked at 'librustc\hir\map\hir_id_validator.rs:31:
    HirIdValidator: The recorded owner of path segment super (id=37553) is ::server[0]::conn[0]::{{?}}[34]    instead of ::server[0]::conn[0]::{{?}}[34]::{{?}}[0]
    HirIdValidator: Same HirId ::server[0]::conn[0]::{{?}}[34]::{{?}}[0]/2 assigned for nodes path segment super (id=37553) and path segment spawn_all (id=92331)', librustc\util\bug.rs:47:26
    stack backtrace:
     0: <std::future::SetOnDrop as core::ops::drop::Drop>::drop
     1: std::panicking::take_hook
     2: std::panicking::take_hook
     3: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_predicate
     4: std::panicking::rust_panic_with_hook
     5: rustc::ty::query::on_disk_cache::__ty_decoder_impl::<impl serialize::serialize::Decoder for rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x>>::read_u32
     6: rustc::ty::context::tls::track_diagnostic
     7: rustc::ty::context::tls::track_diagnostic
     8: rustc::ty::context::tls::track_diagnostic
     9: rustc::ty::context::tls::track_diagnostic
    10: rustc::util::bug::bug_fmt
    11: rustc::util::bug::bug_fmt
    12: <rustc::hir::def_id::LocalDefId as core::fmt::Debug>::fmt
    13: rustc::hir::map::map_crate
    14: rustc_driver::driver::build_output_filenames
    15: rustc_driver::driver::compile_input
    16: rustc_driver::run_compiler
    17: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
    18: rustc_driver::run_compiler
    19: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
    20: <rustc_driver::pretty::IdentifiedAnnotation<'hir> as rustc_driver::pretty::PrinterSupport>::sess
    21: _rust_maybe_catch_panic
    22: rustc_driver::target_features::add_configuration
    23: rustc_driver::main
    24: <unknown>
    25: std::panicking::update_panic_count
    26: _rust_maybe_catch_panic
    27: std::rt::lang_start_internal
    28: <unknown>
    29: <unknown>
    30: BaseThreadInitThunk
    31: RtlUserThreadStart
    query stack during panic:
    end of query stack
    error: internal compiler error: unexpected panic
    note: the compiler unexpectedly panicked. this is a bug.
    note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
    note: rustc 1.31.0-nightly (96064eb61 2018-10-28) running on x86_64-pc-windows-msvc
    note: compiler flags: -C debuginfo=2 --crate-type lib
    note: some of the compiler flags provided by cargo are hidden
    error: Could not compile `hyper`.

Please let me know if you need more information. I AM running stable - I don't know if that has anything to do with it. Thanks!

**Comment by bjorn3** [comment] 2018-12-13 13:22
> I AM running stable - I don't know if that has anything to do with it. Thanks!

You seem to be using nightly: `note: rustc 1.31.0-nightly (96064eb61 2018-10-28) running on x86_64-pc-windows-msvc`. `cargo expand` doesn't work on stable.

**Comment by sinkuu** [comment] 2018-12-19 22:46
The problem is on old nightly. #55376

**Comment by jonas-schievink** [comment] 2019-01-26 23:50
https://github.com/rust-lang/rust/issues/55376 was fixed, so I'll close this. Please comment if this is still an issue and I'll reopen.

**Closed by jonas-schievink** 2019-01-26 23:50 UTC
