### ISSUE TITLE
Error extending Fn trait then using it as a trait object: the value of the associated type `Output must be specified

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#24010] opened 2015-04-03 16:04 UTC
``` rust
trait Foo: Fn(i32) + Send { }
impl<T:?Sized + Fn(i32) + Send> Foo for T { }

fn wants_foo(t: Box<Foo>) {
}

fn main() {
  let f = Box::new(|x| println!("{}", x));
  wants_foo(f);
}
```

Output:

```
<anon>:9:13: 9:14 error: the value of the associated type `Output` (from the trait `core::ops::FnOnce`) must be specified [E0191]
<anon>:9   wants_foo(f);
                     ^
```

cc @nikomatsakis

**Comment by nikomatsakis** [comment] 2015-04-03 17:48
The problem is that the associated type is defined in a supertrait, and we don't consider that case when we check that the object type is well-formed.

**Comment by Diggsey** [comment] 2015-05-07 16:53
It can be quite painful to work around this problem, as it's the only way to create aliases for traits.

When you have bounds such as the following scattered all over the code: `Fn(&(Any + Send), &'static str, u32) + 'static`, it's *much* nicer to be able to give it a short name.

**Comment by jonhoo** [comment] 2015-06-01 20:01
@Diggsey: what workaround would you propose? I've been hitting my head against this wall for a while now, and am getting nowhere..

**Comment by Diggsey** [comment] 2015-06-01 20:42
@jonhoo I don't know about your particular use-case, but for me I was using this to create a short alias for a trait - the workaround was just to use the long name everywhere, ie. `Fn(&(Any + Send), &'static str, u32) + 'static`

**Comment by jonhoo** [comment] 2015-06-01 21:02
My use-case is exactly the same. I was hoping I might be able to use a macro that expanded to the type, but that doesn't seem to work either. I suppose I'll just have to use the full signature for now..

**Comment by Kimundi** [comment] 2015-09-05 15:12
@nikomatsakis Why is that case not considered?

**Comment by nikomatsakis** [comment] 2015-09-09 09:38
@Kimundi it's a bug, really.

**Comment by Kimundi** [comment] 2015-09-12 18:10
Ah, okay it sounded like that was intentional :)

**Comment by DGolubets** [comment] 2016-02-28 15:47
Is it going to be fixed in any upcoming version?

**Comment by nikomatsakis** [comment] 2016-05-05 20:14
Note that @durka points out in #29328 this does technically allow one to violate some stability restrictions, but probably not in a way that matters:

```rust
trait FnAlias: Fn() {}

fn main() {
    let _: FnAlias;            // error
    let _: FnAlias<Output=()>; // no error, but I shouldn't be able to do this!
}
```

**Comment by jimmycuadra** [comment] 2017-03-05 00:45
This bug is very annoying. I have the same use case as @Diggsey and @jonhoo: creating an alias of a trait with cumbersome bounds that I don't want to have to repeat everywhere.

In case it's not obvious from the title, this doesn't have to do with the `Fn` trait specifically. It's just about supertrait associated types being ignored when using the subtrait. Here's a simpler illustration:

``` rust
trait A {
    type Assoc;
    // Pretend there are several more associated types here to make uses of `Box<A>` inconvenient.
}

trait B: A<Assoc=()> {}

fn takes_b(b: Box<B>) {}
```

which results in:

```
error[E0191]: the value of the associated type `Assoc` (from the trait `A`) must be specified
 --> src/lib.rs:8:19
  |
8 | fn takes_b(b: Box<B>) {}
  |                   ^ missing associated type `Assoc` value
```

The compiler should be able to infer that `type Assoc = ()` here.

**Comment by maurer** [comment] 2017-05-23 22:34
```
use std::iter::Iterator;

pub trait LeapfrogIterator<T, V> : Iterator<Item=(T,V)> {
    fn next_above(&mut self, &T) -> Option<(T, V)>;
}

fn main () {
    let v: Box<LeapfrogIterator<i64, i64>> = unimplemented!();
}
```
https://is.gd/VcQmki

is another concrete use case - if I want to extend `Iterator` in this way, I need to write LeapfrogIterator<K, V, Item=(K, V)> every time I want to talk about the trait, even though this is the only legal value for Item to take on. (This doesn't express the bug in a new way, but is an example I ran into organically and eventually found this bug due to.)

**Comment by glyn** [comment] 2017-06-15 16:22
I hit this when trying to create an alias of a FnMut trait. One workaround is to use a macro (@jonhoo had trouble with this, but it was two years ago), although I'd like a solution in the type system.

**Comment by durka** [comment] 2017-07-04 19:02
@nikomatsakis 

> The problem is that the associated type is defined in a supertrait, and we don't consider that case when we check that the object type is well-formed.

> @Kimundi it's a bug, really.

Is it possible to give some mentoring hints for fixing this?

**Comment by alexreg** [comment] 2018-10-10 19:15
@mbrubeck I think so too. Have we confirmed it yet? If so, worth closing this as duplicate.

**Comment by alexreg** [comment] 2018-11-05 03:39
Okay, we have a fix! Waiting for review and merge on https://github.com/rust-lang/rust/pull/55687.

**Closed** 2018-11-11 09:07 UTC
Labels: A-associated-items, A-traits, C-bug
