### ISSUE TITLE
rustdoc crate stable version number is misleading

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41581] opened 2017-04-27 16:45 UTC
Every release I verify the docs, and go to [this page](https://doc.rust-lang.org/std/). Every release this page says, in big text at the top of the page, "1.0.0". Casual users will not understand what this label means - they will expect it to correspond to the current release.

I think this label provides little value (negative actually, considering this issue) - stability attributes only apply to in-tree crates, and the set of stable crates rarely changes.

I suggest removing this label and instead finding some way to indicate the version of the crate.

**Comment by neosilky** [comment] 2017-04-27 19:06
How about something like the following?

![2017-04-27-200515_681x270_scrot](https://cloud.githubusercontent.com/assets/964245/25499928/092ea6b0-2b85-11e7-9197-1e957242043a.png)

**Comment by marti1125** [comment] 2017-05-10 22:19
@brson I would like to contribute with this

**Comment by QuietMisdreavus** [comment] 2017-09-29 01:51
Closing as duplicate of https://github.com/rust-lang/rust/issues/24336, since this is just that issue applied to the (very visible example of) libstd. (I left a hint in there, but the implementation details are slightly up to a team decision to make sure we don't couple too tightly to Cargo.)

**Closed by QuietMisdreavus** 2017-09-29 01:51 UTC
Labels: A-rustdoc, C-feature-request, T-dev-tools
