### ISSUE TITLE
LLVM assertion error when dereferencing "&mut Iterator<Item=Something>" from function parameter

### ISSUE THREAD

**Issue by mottalli** [rust-lang/rust#21379] opened 2015-01-19 00:22 UTC
Offending code:
```rust
extern crate core;
use core::fmt;

fn show_all<I: fmt::String>(iter: &mut Iterator<Item=I>) {
    for i in *iter {
        println!("{}", i);
    }
}

fn main() {
    let v = vec![1i32, 2, 3, 4];
    show_all(&mut v.iter());
}
```

Compiler error (formatted):
```
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:281: 
void llvm::CallInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): 
Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && 
"Calling a function with a bad signature!"' failed.
```

Rust version:
```
$ rustc --version
rustc 1.0.0-nightly (f4f10dba2 2015-01-17 20:31:08 +0000)
```

**Comment by mottalli** [comment] 2015-01-19 03:07
I compiled Rust from source and the previous error becomes this:
```
Call parameter type does not match function signature!
  %11 = load { i8*, void (i8*)** }* %__fat_ptr
 { i8*, void (i8*)** }*  %12 = call i8* @"_ZN216fn$LP$$BP$mut$u{20}core..iter..Iterator$u{20}$u{2b}$u{20}$u{27}static$RP$$u{20}.$GT$$u{20}core..option..Option$LT$$LT$core..iter..Iterator$u{20}$u{2b}$u{20}$u{27}static$u{20}as$u{20}core..iter..Iterator$GT$..Item$GT$16object_shim.166317h29bc7de23a846978E"({ i8*, void (i8*)** } noalias nocapture dereferenceable(16) %11)
LLVM ERROR: Broken function found, compilation aborted!
```
Rust version:
```
$ rustc --version
rustc 1.0.0-dev (dcaeb6aa2 2015-01-18 11:28:53 +0000)
```

**Comment by mottalli** [comment] 2015-01-20 02:27
I found out that the problem is on the loop:

```rust
    for i in *iter {
        println!("{}", i);
    }
```
If I replace this with the expanded version of the loop:
```rust
    loop {
        match (*iter).next() {
            Some(ref i) => println!("{}", i),
            None => break
        }
    }
```
it compiles and works as expected. So, the problem seems to be that the compiler is unable to dereference the Iterator trait, maybe it has something to do with the fact that I am forcing Item to be of a specific type? (i.e. ```Iterator<Type=I>```)

**Comment by theemathas** [comment] 2015-01-25 01:38
Minimal code:

```rust
fn foo(it: &mut Iterator<Item = i32>) {
    for x in *it {}
}

fn main() { }
```
[playpen](http://is.gd/XtTVOy)

The ICE: 

```
rustc: /build/rust-git/src/rust/src/llvm/lib/IR/Instructions.cpp:281: void llvm::CallInst::init(llvm::Value*, llvm::ArrayRef<llvm::Value*>, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```

[Removing the associated type](http://is.gd/3XcDyc) results in a variant of #21137

**Comment by nikomatsakis** [comment] 2015-01-26 11:10
Gah, I feel like I've fixed this bug once before.

**Comment by japaric** [comment] 2015-01-26 13:59
Duplicate of #20605 

To avoid the LLVM assertion, don't dereference the iterator in the for loop. This doesn't crash:

``` rust
fn foo(it: &mut Iterator<Item = i32>) {
    for x in it {}
//~^ error: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
}

fn main() { }
```

Instead, you get a compiler error, I think that compiler error maybe be a different bug.

**Comment by japaric** [comment] 2015-01-26 14:21
I filled issue #21655 for the `for _ in ref_mut_trait_object {}` bug.

**Closed** 2015-01-31 07:20 UTC
Labels: A-associated-items, I-ICE
