### ISSUE TITLE
After I executed rustc main.rs, no executable was generated

### ISSUE THREAD

**Issue by rohero6** [rust-lang/rust#119309] opened 2023-12-26 03:20 UTC
question：After I executed rustc main.rs, no executable was generated
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}

```

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

### Meta

`rustc --version --verbose`:
```
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: aarch64-apple-darwin
release: 1.74.1
LLVM version: 17.0.4
macOS Sonoma 14.2.1 (23C71)
```

![image](https://github.com/rust-lang/rust/assets/52845010/9a74c899-dceb-48bb-8173-c29872a90814)

**Comment by bjorn3** [comment] 2023-12-26 12:50
What does `RUSTC_LOG=rustc_codegen_ssa::back::link rustc main.rs` show?

**Comment by rohero6** [comment] 2024-01-02 03:11
> What does `RUSTC_LOG=rustc_codegen_ssa::back::link rustc main.rs` show?

![image](https://github.com/rust-lang/rust/assets/52845010/84e119b0-082e-42d5-a8d8-e02cd7924535)

**Comment by bjorn3** [comment] 2024-01-02 13:45
Does it show anything below that? There should be logs with the stdout and stderr of the linker.

**Comment by rohero6** [comment] 2024-01-04 03:33
> Does it show anything below that? There should be logs with the stdout and stderr of the linker.

![image](https://github.com/rust-lang/rust/assets/52845010/39cbed13-06ff-4a13-b001-fcb7f437a7ce)

**Comment by rohero6** [comment] 2024-01-04 03:36
> Does it show anything below that? There should be logs with the stdout and stderr of the linker.

I updated everything, but still can't solve the problem, I don't know where to troubleshoot the problem, the only sure problem is that I compiled no errors, but also did not generate executable files

**Comment by rohero6** [comment] 2024-01-04 06:32
解决问题了 RUSTC_LOG=info rustc src/main.rs It was found that the cc command conflicted with other plug-ins I installed

**Comment by jieyouxu** [comment] 2024-02-14 23:44
> 解决问题了 RUSTC_LOG=info rustc src/main.rs It was found that the cc command conflicted with other plug-ins I installed

As the issue is solved, I am closing this issue.

**Closed by jieyouxu** 2024-02-14 23:44 UTC
Labels: O-macos, C-bug
