### ISSUE TITLE
wasm32-unknown-unknown: failed assert_eq! runs unreachable

### ISSUE THREAD

**Issue by davidhewitt** [rust-lang/rust#46996] opened 2017-12-25 12:54 UTC
Hello,

With the following code:

    fn main() {
        assert_eq! (2+2, 5);
    }

I get an error when trying to load the module (using `cargo web start`):

    Error loading Rust wasm module 'demo': 
    RuntimeError: unreachable executed
    Stack trace:
    wasm-function[47]@http://localhost:8000/js/app.js:13783:1
    wasm-function[46]@http://localhost:8000/js/app.js:12495:1
    wasm-function[45]@http://localhost:8000/js/app.js:12372:1
    wasm-function[2]@http://localhost:8000/js/app.js:812:1
    wasm-function[12]@http://localhost:8000/js/app.js:6213:1
    wasm-function[3]@http://localhost:8000/js/app.js:1267:1
    wasm-function[113]@http://localhost:8000/js/app.js:42579:1
    __load@http://localhost:8000/js/app.js:59:9
    __promise<@http://localhost:8000/js/app.js:76:17

If the assert_eq passes (e.g. change that 5 to a 4) then the module loads fine.

It may be that this is a bug in cargo-web but I suspect it's possibly a codegen issue? Happy to provide extra information. Platform is windows 10. Compiler versions:

    $ cargo -V
    cargo 0.25.0-nightly (930f9d949 2017-12-05)

    $ rustc -V
    rustc 1.24.0-nightly (169929308 2017-12-23)

**Comment by est31** [comment] 2017-12-25 13:37
This is no bug, but rather bad UI. If the assert fails, you need to do *something*. Panic backtraces or similar aren't implemented in wasm yet.

**Comment by davidhewitt** [comment] 2017-12-25 14:07
Oh ok, so I have to manually catch the panic?

This is slightly unfortunate in testing, as failing tests also hit this same unreachable.

**Comment by alexcrichton** [comment] 2017-12-26 01:04
Yes unfortunately this is expected behavior right now, all wasm code is effectively compiled with panic=abort. We could change this via codegen tweaks in rustc itself (a very large change) or wait for wasm to have native unwinding support (probably going to take awhile)

For the time being you unfortunately can't easily rely on catching panics. We need to do a better job with the error message as well, but that may unfortunately also take awhile :(

**Comment by alexcrichton** [comment] 2018-02-27 19:33
Since this is intended behavior for now I'm going to close this

**Closed by alexcrichton** 2018-02-27 19:33 UTC
Labels: O-wasm

**Comment by johnsonw** [comment] 2019-02-04 16:28
So from the manager's perspective it wasn't able to communicate with rabbitmq, which caused the services to fail. During this time, information has not been able to populate the IML database, but now that the services are up and running they are receiving information from the agent nodes. It's possible that the agent nodes had already failed and the manager is just now receiving that information and updating the state of the GUI. 

To provide more insight, it might be worth taking a look at /var/log/chroma-agent.log on one of the OSS nodes. If this continues, we can also put the agent into debug mode to track more verbose messages. If you don't mind, please log into one of the OSS nodes that failed and run "iml-diagnostics" and attached the compressed file.

Regards,

Will
