### ISSUE TITLE
Panicking when adding a unexpected keyword in a struct 

### ISSUE THREAD

**Issue by jens1o** [rust-lang/rust#53635] opened 2018-08-23 13:22 UTC
```
thread '<unnamed>' panicked at 'Forcing query with already existing DepNode.
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: std::sys_common::wtf8::Wtf8Buf }
- dep-node: IsCopy(708c04bc555674a6-c5c3cb1bac3120ad)', librustc\ty\query\plumbing.rs:531:9

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-pc-windows-msvc

thread '<unnamed>' panicked at 'Forcing query with already existing DepNode.
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: std::io::error::Repr }
- dep-node: IsCopy(8b763b6cc7456bab-227f7e3a79f66d3)', librustc\ty\query\plumbing.rs:531:9

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-pc-windows-msvc

error: expected one of `.`, `;`, `?`, or an operator, found `command`
  --> <stdin>:10:9
   |
9  |         let command = Command::new(self.name)
   |                                              - expected one of `.`, `;`, `?`, or an operator here
10 |         command.args(&args);
   |         ^^^^^^^ unexpected token

[Error - 3:17:01 PM] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
error: internal compiler error: Error constructed but not emitted

thread 'request-worker-1' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_errors-218.0.0\diagnostic_builder.rs:295:13
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-pc-windows-msvc

error: expected identifier, found keyword `mut`
 --> <stdin>:5:5
  |
5 |     mut command: Command
  |     ^^^ expected identifier, found keyword

error: expected `:`, found `command`
 --> <stdin>:5:9
  |
5 |     mut command: Command
  |         ^^^^^^^ expected `:`

[Error - 3:18:52 PM] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-pc-windows-msvc

error: expected identifier, found keyword `mut`
 --> <stdin>:5:5
  |
5 |     mut command: Command
  |     ^^^ expected identifier, found keyword

error: expected `:`, found `command`
 --> <stdin>:5:9
  |
5 |     mut command: Command
  |         ^^^^^^^ expected `:`

[Error - 3:18:54 PM] Request textDocument/formatting failed.
  Message: Reformat failed to complete successfully
  Code: -32603 
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.30.0-nightly (33b923fd4 2018-08-18) running on x86_64-pc-windows-msvc
```

The code:
```rust
use std::process::Command;

pub struct Binary {
    name: &'static str,
    command: Command,
}
```

Simply add the `mut ` keyword to the `command: Command,` line and it is panicking.

**Comment by estebank** [comment] 2018-08-24 00:59
I'm unable to reproduce with

```
use std::process::Command;

pub struct Binary {
    name: &'static str,
    mut command: Command,
}

fn main() {}
```

Could you provide a link to a reproduction at https://play.rust-lang.org/ and running the same command locally with RUST_BACKTRACE=1?

**Comment by jens1o** [comment] 2018-08-24 07:36
Oh, I think this is the wrong repo. This happened when using `rls` and then typing in the keyword. Is there some way to move the issue?

**Comment by estebank** [comment] 2018-08-24 15:56
Weird, they would both behave similarly.

**Comment by estebank** [comment] 2018-08-24 15:57
We can close this one an you can create one on the rls' issue tracker, linking to this one.

**Closed** 2018-08-24 15:57 UTC
Labels: I-ICE
