### ISSUE TITLE
rustc panicked at Box<Any>

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang/rust#23093] opened 2015-03-05 23:19 UTC
~~~
nathan@jarvis ~/Development/projects/presence-rs $ RUST_BACKTRACE=1 cargo build --verbose
       Fresh log v0.2.5
       Fresh gcc v0.3.1
       Fresh rustc-serialize v0.3.1
       Fresh libc v0.1.2
       Fresh websocket-stream v0.0.2
       Fresh sha1 v0.0.7 (https://github.com/mitsuhiko/rust-sha1#d6a54754)
       Fresh rand v0.1.4
       Fresh time v0.1.19
   Compiling presence v0.0.1 (file:///home/nathan/Development/projects/presence-rs)
     Running `rustc src/main.rs --crate-name presence --crate-type bin -g --out-dir /home/nathan/Development/projects/presence-rs/target --emit=dep-info,link -L dependency=/home/nathan/Development/projects/presence-rs/target -L dependency=/home/nathan/Development/projects/presence-rs/target/deps --extern websocket-stream=/home/nathan/Development/projects/presence-rs/target/deps/libwebsocket-stream-34c135eedc7bbec4.rlib --extern sha1=/home/nathan/Development/projects/presence-rs/target/deps/libsha1-a2be330fbadef0c7.rlib --extern rand=/home/nathan/Development/projects/presence-rs/target/deps/librand-6dfe5258ada5ebf2.rlib --extern time=/home/nathan/Development/projects/presence-rs/target/deps/libtime-f5c2f62bb1bdf976.rlib --extern rustc-serialize=/home/nathan/Development/projects/presence-rs/target/deps/librustc-serialize-2aa16a9a901fcba8.rlib -L native=/home/nathan/Development/projects/presence-rs/target/build/time-f5c2f62bb1bdf976/out`
/home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/mutex.rs:177:37: 180:2 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 18660, node: ExprStruct(Path { span: Span { lo: BytePos(4623140), hi: BytePos(4623151), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(1770102), hi: BytePos(1770106), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 18661, node: ExprPath(None, Path { span: Span { lo: BytePos(4623164), hi: BytePos(4623179), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4623164), hi: BytePos(4623179), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4623158), hi: BytePos(4623179), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(1770129), hi: BytePos(1770135), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 18662, node: ExprPath(None, Path { span: Span { lo: BytePos(4623193), hi: BytePos(4623210), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4623193), hi: BytePos(4623210), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4623185), hi: BytePos(4623210), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(4623140), hi: BytePos(4623213), expn_id: ExpnId(4294967295) } })
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129
stack backtrace:
   1:     0x7f2399a72f1f - sys::backtrace::write::hf79a3da4fdecb8a0OBA
   2:     0x7f2399a9dc32 - panicking::on_panic::h9f64f4c69e19f194hHJ
   3:     0x7f23999d2eda - rt::unwind::begin_unwind_inner::h37f4496c980fe936knJ
   4:     0x7f2396e03abd - rt::unwind::begin_unwind::h8320268356453106285
   5:     0x7f2396e03a63 - diagnostic::SpanHandler::span_bug::h83c8af232eaba6a9h0D
   6:     0x7f23976dfca3 - session::Session::span_bug::h857b2c7ae23c9286ISp
   7:     0x7f23991fd80c - trans::debuginfo::scope_metadata::hac54dfdbdcd04cd9SjE
   8:     0x7f2399110408 - trans::debuginfo::set_source_location::h1067a74086ed9dd48MD
   9:     0x7f23990c4e42 - trans::expr::trans_into::h95c6d2681fdd2548znh
  10:     0x7f23990c5109 - trans::expr::trans_into::h95c6d2681fdd2548znh
  11:     0x7f239912767f - trans::expr::trans_uniq_expr::h5f082eea62818f84ukj
  12:     0x7f23991282ef - trans::expr::trans_unary::h4412379888608420Jgj
  13:     0x7f239911280e - trans::expr::trans_unadjusted::hfd3a5e1b5cbe37d5z4h
  14:     0x7f23990c5417 - trans::expr::trans_into::h95c6d2681fdd2548znh
  15:     0x7f23991456f9 - trans::expr::trans_adt::h1af69b9b4e52152aO6i
  16:     0x7f23991481af - trans::expr::trans_struct::closure.42069
  17:     0x7f2399132016 - trans::expr::trans_struct::hcae8f9103f3460d5K2i
  18:     0x7f239911453d - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  19:     0x7f23990c53f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  20:     0x7f23990c6227 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  21:     0x7f239919d821 - trans::base::trans_closure::hab3cc3c679d5ff23Kkt
  22:     0x7f23990aeb08 - trans::base::trans_fn::he0569b8eb832adf9Dvt
  23:     0x7f23990b05a0 - trans::monomorphize::monomorphic_fn::hc1b7393dd1dc77f1usd
  24:     0x7f23990f5e4e - trans::callee::trans_fn_ref_with_substs::hd01acb4398310d154kg
  25:     0x7f23990f443e - trans::callee::trans_fn_ref::hb48e614c9b6dd9bcE9f
  26:     0x7f23990f188d - trans::callee::trans::ha56f4fe94448e6baVYf
  27:     0x7f2399107fbb - trans::callee::trans_call_inner::h9722042290657949952
  28:     0x7f23991149e0 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  29:     0x7f23990c53f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  30:     0x7f23991456f9 - trans::expr::trans_adt::h1af69b9b4e52152aO6i
  31:     0x7f23991481af - trans::expr::trans_struct::closure.42069
  32:     0x7f2399132016 - trans::expr::trans_struct::hcae8f9103f3460d5K2i
  33:     0x7f239911453d - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  34:     0x7f23990c53f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  35:     0x7f23991d5967 - trans::_match::mk_binding_alloca::h13035368140960659810
  36:     0x7f23990c47fd - trans::base::init_local::h1e7c96bb7077440dczs
  37:     0x7f23990c5f02 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  38:     0x7f239919d821 - trans::base::trans_closure::hab3cc3c679d5ff23Kkt
  39:     0x7f23990aeb08 - trans::base::trans_fn::he0569b8eb832adf9Dvt
  40:     0x7f23990b05a0 - trans::monomorphize::monomorphic_fn::hc1b7393dd1dc77f1usd
  41:     0x7f23990f5e4e - trans::callee::trans_fn_ref_with_substs::hd01acb4398310d154kg
  42:     0x7f23990f443e - trans::callee::trans_fn_ref::hb48e614c9b6dd9bcE9f
  43:     0x7f23990f188d - trans::callee::trans::ha56f4fe94448e6baVYf
  44:     0x7f2399107fbb - trans::callee::trans_call_inner::h9722042290657949952
  45:     0x7f23991149e0 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  46:     0x7f2399112668 - trans::expr::trans_unadjusted::hfd3a5e1b5cbe37d5z4h
  47:     0x7f23990c6b58 - trans::expr::trans::h23d7d0dd91a5190fHth
  48:     0x7f23991039f3 - trans::callee::trans_args::h29a92a6ed71c85ebm1g
  49:     0x7f2399108ea0 - trans::callee::trans_call_inner::h9722042290657949952
  50:     0x7f23991149e0 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  51:     0x7f2399112668 - trans::expr::trans_unadjusted::hfd3a5e1b5cbe37d5z4h
  52:     0x7f23990c6b58 - trans::expr::trans::h23d7d0dd91a5190fHth
  53:     0x7f23991039f3 - trans::callee::trans_args::h29a92a6ed71c85ebm1g
  54:     0x7f2399108ea0 - trans::callee::trans_call_inner::h9722042290657949952
  55:     0x7f23991149e0 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  56:     0x7f23990c53f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  57:     0x7f23991d5967 - trans::_match::mk_binding_alloca::h13035368140960659810
  58:     0x7f23990c47fd - trans::base::init_local::h1e7c96bb7077440dczs
  59:     0x7f23990c5f02 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  60:     0x7f2399113f7e - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  61:     0x7f23990c53f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  62:     0x7f23991bddf0 - trans::_match::trans_match_inner::hed8323987dcd430bCIw
  63:     0x7f2399113f22 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  64:     0x7f2399112668 - trans::expr::trans_unadjusted::hfd3a5e1b5cbe37d5z4h
  65:     0x7f23990c6b58 - trans::expr::trans::h23d7d0dd91a5190fHth
  66:     0x7f23990c48d2 - trans::base::init_local::h1e7c96bb7077440dczs
  67:     0x7f23990c5f02 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  68:     0x7f239919d821 - trans::base::trans_closure::hab3cc3c679d5ff23Kkt
  69:     0x7f23990aeb08 - trans::base::trans_fn::he0569b8eb832adf9Dvt
  70:     0x7f23990b05a0 - trans::monomorphize::monomorphic_fn::hc1b7393dd1dc77f1usd
  71:     0x7f23990f5e4e - trans::callee::trans_fn_ref_with_substs::hd01acb4398310d154kg
  72:     0x7f239910dea5 - trans::meth::trans_method_callee::h560647f9622b6732N6x
  73:     0x7f23991098e9 - trans::callee::trans_call_inner::h3649553240631627052
  74:     0x7f2399113789 - trans::expr::trans_rvalue_dps_unadjusted::hd47de7ac66e018254zi
  75:     0x7f23990c53f6 - trans::expr::trans_into::h95c6d2681fdd2548znh
  76:     0x7f23990c6227 - trans::controlflow::trans_block::h3e86dfa8c58560e6b5d
  77:     0x7f239919d821 - trans::base::trans_closure::hab3cc3c679d5ff23Kkt
  78:     0x7f23990aeb08 - trans::base::trans_fn::he0569b8eb832adf9Dvt
  79:     0x7f23990ab241 - trans::base::trans_item::h48fc370b7d259ac7vTt
  80:     0x7f23990ab078 - trans::base::trans_item::h48fc370b7d259ac7vTt
  81:     0x7f23991a67ec - trans::base::trans_crate::hc92be67ede893c70GPu
  82:     0x7f239a0abe83 - driver::phase_4_translate_to_llvm::h9904f5d5fc3fb761rNa
  83:     0x7f239a08783f - driver::compile_input::h3913ff7013f0c056Iba
  84:     0x7f239a14fcb7 - run_compiler::h28a4446bae1034e7H5b
  85:     0x7f239a14d829 - thunk::F.Invoke<A, R>::invoke::h6503055919709693733
  86:     0x7f239a14c4a0 - rt::unwind::try::try_fn::h1384674024000742916
  87:     0x7f2399b0dde8 - rust_try_inner
  88:     0x7f2399b0ddd5 - rust_try
  89:     0x7f239a14cc3f - thunk::F.Invoke<A, R>::invoke::h5780663349966142752
  90:     0x7f2399a88965 - sys::thread::thread_start::h4ab695857833a5dar8E
  91:     0x7f23938e3181 - start_thread
  92:     0x7f239964347c - __clone
  93:                0x0 - <unknown>

Could not compile `presence`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name presence --crate-type bin -g --out-dir /home/nathan/Development/projects/presence-rs/target --emit=dep-info,link -L dependency=/home/nathan/Development/projects/presence-rs/target -L dependency=/home/nathan/Development/projects/presence-rs/target/deps --extern websocket-stream=/home/nathan/Development/projects/presence-rs/target/deps/libwebsocket-stream-34c135eedc7bbec4.rlib --extern sha1=/home/nathan/Development/projects/presence-rs/target/deps/libsha1-a2be330fbadef0c7.rlib --extern rand=/home/nathan/Development/projects/presence-rs/target/deps/librand-6dfe5258ada5ebf2.rlib --extern time=/home/nathan/Development/projects/presence-rs/target/deps/libtime-f5c2f62bb1bdf976.rlib --extern rustc-serialize=/home/nathan/Development/projects/presence-rs/target/deps/librustc-serialize-2aa16a9a901fcba8.rlib -L native=/home/nathan/Development/projects/presence-rs/target/build/time-f5c2f62bb1bdf976/out` (exit code: 101)
~~~

Compiler info...

~~~
rustc --version
rustc 1.0.0-nightly (3b3bb0e68 2015-03-04) (built 2015-03-05)
~~~

Code has been compiling for the past week or so, today I get this.  Do not know exactly which section of the code base is causing the error?  Let me know if there are anymore flags I can set to get more information out of the compiler...

**Comment by golddranks** [comment] 2015-03-05 23:34
Seems to be a duplicate of https://github.com/rust-lang/rust/issues/23053

**Closed** 2015-03-05 23:36 UTC
