### ISSUE TITLE
Repeated macro rules cause an infinite loop

### ISSUE THREAD

**Issue by TheZoq2** [rust-lang/rust#34488] opened 2016-06-26 18:28 UTC
If you define a macro which contains the rule `$()*` the compiler seems to go into an infinite loop and quickly consume a lot of memory

When compiling the following code:
```rust
macro_rules! test {
    ($()*) => {}
}

pub fn main()
{
    test!();
}
```

The compiler freezes and starts consuming memory until it runs out at which point it seems to crash.
Using the above test code, I got this error message but when I encountered this bug in a bigger project, my computer froze for about 1 minute after which the operating system killed the compiler.
```
fatal runtime error: out of memory
zsh: illegal hardware instruction (core dumped)  rustc test.rs
```

This is the output of rustc --version --verbose
```
rustc 1.9.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.9.0
```

**Comment by jonas-schievink** [comment] 2016-06-26 18:31
Duplicate of #5067

**Comment by Aatch** [comment] 2016-06-27 03:44
Closing as duplicate

**Closed by Aatch** 2016-06-27 03:44 UTC
