### ISSUE TITLE
cannot relate bound region: '_#0r <= ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrNamed(DefId(0:351 ~ e24_epd[cbd0]::serial_1::serial_2::{impl#0}::split_method::{opaque#0}::'_#1), '_) })

### ISSUE THREAD

**Issue by mschnell1** [rust-lang/rust#109930] opened 2023-04-04 09:08 UTC
### Code

```Rust
Supposedly this snipped is critical:
impl<T: SPort + 'static> Serial<T>
   pub fn split_method(
        &mut self,
    ) -> (
        impl Fn(&mut Rx<dyn SPortRx>) -> std::result::Result<u8, nb::Error<std::io::Error>>,
        impl Fn(&mut Tx<T>, u8) -> std::result::Result<(), nb::Error<std::io::Error>>,
    ) {
        let rx = Rx::read;
        let tx = Tx::write;
        (rx, tx)
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06
host: x86_64-pc-windows-msvc
release: 1.68.0
LLVM version: 15.0.6
```

### Error output

```
error: internal compiler error: compiler\rustc_infer\src\infer\region_constraints\mod.rs:568:17: cannot relate bound region: '_#0r <= ReLateBound(DebruijnIndex(0), BoundRegion { var: 1, kind: BrNamed(DefId(0:351 ~ e24_epd[cbd0]::serial_1::serial_2::{impl#0}::split_method::{opaque#0}::'_#1), '_) })

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\compiler\rustc_errors\src\lib.rs:987:33
stack backtrace:
   0:     0x7ff8664d9d02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h792a027c2747e99d
   1:     0x7ff86651570b - core::fmt::write::h5d1fd4698cef7a98
   2:     0x7ff8664ccdfa - <std::io::IoSlice as core::fmt::Debug>::fmt::hba64fac32bc54252
   3:     0x7ff8664d9a4b - std::sys::common::alloc::realloc_fallback::hfe62d187ace61bcd
   4:     0x7ff8664dd3f9 - std::panicking::default_hook::hc7b7ee9dc8a166a2
   5:     0x7ff8664dd07b - std::panicking::default_hook::hc7b7ee9dc8a166a2
   6:     0x7ff8335dec34 - rustc_driver[6fce53b951639747]::describe_lints
   7:     0x7ff8664ddd5f - std::panicking::rust_panic_with_hook::h80ad08272951bba3
   8:     0x7ff833939a73 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
   9:     0x7ff833937c79 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  10:     0x7ff833937c19 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  11:     0x7ff833937c09 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  12:     0x7ff833937270 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  13:     0x7ff8339370c9 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  14:     0x7ff8338e27e9 - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  15:     0x7ff8338e284d - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  16:     0x7ff8338e19ff - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  17:     0x7ff8338e19a8 - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  18:     0x7ff8338e1966 - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  19:     0x7ff831babde8 - rustc_infer[1d2eee8e62f18ba3]::traits::util::supertraits
  20:     0x7ff831bdea09 - <rustc_infer[1d2eee8e62f18ba3]::infer::outlives::verify::VerifyBoundCx>::alias_bound
  21:     0x7ff831bd6748 - <rustc_infer[1d2eee8e62f18ba3]::infer::equate::Equate as rustc_middle[484603f84bd5edf8]::ty::relate::TypeRelation>::tys
  22:     0x7ff830ddeb38 - rustc_trait_selection[48a8fb49e3ee715f]::traits::wf::object_region_bounds
  23:     0x7ff830df6358 - rustc_trait_selection[48a8fb49e3ee715f]::traits::structural_match::search_for_adt_const_param_violation
  24:     0x7ff834214f08 - <rustc_trait_selection[48a8fb49e3ee715f]::traits::wf::Elaborate as core[ab957a7126758ba9]::fmt::Debug>::fmt
  25:     0x7ff8341fae09 - <rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::method_chain::CollectAllMismatches as rustc_middle[484603f84bd5edf8]::ty::relate::TypeRelation>::consts
  26:     0x7ff83428bed0 - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::suggestions::TypeErrCtxtExt>::report_closure_arg_mismatch
  27:     0x7ff83429ee96 - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  28:     0x7ff8342ab537 - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error 
  29:     0x7ff83429b96d - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors  
  30:     0x7ff831a43081 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  31:     0x7ff831a443d9 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  32:     0x7ff831aa47dd - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::check_struct_path
  33:     0x7ff831a456b5 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  34:     0x7ff831a6a271 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  35:     0x7ff831b04e67 - <rustc_hir_typeck[726d463412e15d63]::writeback::WritebackCx as rustc_hir[a0ba7d6a2d0a2d5c]::intravisit::Visitor>::visit_ty
  36:     0x7ff831b202e7 - <rustc_hir_typeck[726d463412e15d63]::inherited::Inherited as core[ab957a7126758ba9]::ops::deref::Deref>::deref
  37:     0x7ff830cd6f15 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  38:     0x7ff8322ad263 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  39:     0x7ff83237e743 - <rustc_query_impl[78e525705bed6840]::Queries as rustc_middle[484603f84bd5edf8]::ty::query::QueryEngine>::as_any
  40:     0x7ff831ed5ea8 - <rustc_mir_build[20a96c4a1e0f6c98]::thir::pattern::usefulness::PatStack>::head
  41:     0x7ff830ccd438 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  42:     0x7ff8322b7be4 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  43:     0x7ff831e5afad - <rustc_middle[484603f84bd5edf8]::lint::ShallowLintLevelMap>::lint_level_id_at_node
  44:     0x7ff830ccdb79 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  45:     0x7ff8322b35a7 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  46:     0x7ff832017005 - <rustc_mir_transform[447b65096884623e]::check_unsafety::UnsafetyChecker as rustc_middle[484603f84bd5edf8]::mir::visit::Visitor>::visit_place
  47:     0x7ff83200b2f8 - <rustc_mir_transform[447b65096884623e]::shim::DropShimElaborator as rustc_mir_dataflow[f943da5690917572]::elaborate_drops::DropElaborator>::drop_style
  48:     0x7ff830cd6f15 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  49:     0x7ff83227e62f - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  50:     0x7ff831feac67 - <rustc_mir_transform[447b65096884623e]::unreachable_prop::UnreachablePropagation as rustc_middle[484603f84bd5edf8]::mir::MirPass>::run_pass
  51:     0x7ff830ccdb79 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  52:     0x7ff8322b58be - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  53:     0x7ff831fed3f0 - <rustc_mir_transform[447b65096884623e]::unreachable_prop::UnreachablePropagation as rustc_middle[484603f84bd5edf8]::mir::MirPass>::run_pass
  54:     0x7ff830cce338 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  55:     0x7ff832237a74 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  56:     0x7ff8315e2248 - <rustc_middle[484603f84bd5edf8]::ty::sty::Region as rustc_borrowck[c87751c803a78843]::nll::ToRegionVid>::to_region_vid
  57:     0x7ff8315e1be8 - <rustc_middle[484603f84bd5edf8]::ty::sty::Region as rustc_borrowck[c87751c803a78843]::nll::ToRegionVid>::to_region_vid
  58:     0x7ff830cd6f15 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  59:     0x7ff832233576 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  60:     0x7ff83237e91f - <rustc_query_impl[78e525705bed6840]::Queries as rustc_middle[484603f84bd5edf8]::ty::query::QueryEngine>::as_any
  61:     0x7ff831945979 - <rustc_hir[a0ba7d6a2d0a2d5c]::lang_items::LanguageItems>::pointer_sized
  62:     0x7ff8323c589b - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_serialize[24aa371669c7d619]::serialize::Encoder>::emit_u32
  63:     0x7ff832315599 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  64:     0x7ff8307b90b4 - <<dyn rustc_hir_analysis[eefa32d64dd8432c]::astconv::AstConv>::create_substs_for_ast_path::{closure#0}::SubstsForAstPathCtxt as rustc_hir_analysis[eefa32d64dd8432c]::astconv::CreateSubstsForGenericArgsCtxt>::inferred_kind
  65:     0x7ff83198720d - rustc_hir_analysis[eefa32d64dd8432c]::check::check::check_abi
  66:     0x7ff830cd8685 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  67:     0x7ff830b9ab4c - <core[ab957a7126758ba9]::option::Option<rustc_middle[484603f84bd5edf8]::middle::privacy::Level> as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  68:     0x7ff830c9bf1f - <rustc_query_impl[78e525705bed6840]::Queries as rustc_middle[484603f84bd5edf8]::ty::query::QueryEngine>::try_mark_green
  69:     0x7ff8307c2a20 - rustc_hir_analysis[eefa32d64dd8432c]::hir_wf_check::provide
  70:     0x7ff8307adc03 - rustc_hir_analysis[eefa32d64dd8432c]::check_crate
  71:     0x7ff8308d1c2d - rustc_interface[8244ed7f36050a97]::passes::analysis
  72:     0x7ff830cf7c69 - <rustc_query_impl[78e525705bed6840]::on_disk_cache::CacheEncoder as rustc_type_ir[197ea4a31556d302]::codec::TyEncoder>::encode_alloc_id
  73:     0x7ff830c245c6 - <core[ab957a7126758ba9]::option::Option<rustc_middle[484603f84bd5edf8]::middle::privacy::Level> as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  74:     0x7ff830c99a2f - <rustc_query_impl[78e525705bed6840]::Queries as rustc_middle[484603f84bd5edf8]::ty::query::QueryEngine>::try_mark_green
  75:     0x7ff8306cd4c0 - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  76:     0x7ff8306de6e6 - rustc_driver[6fce53b951639747]::args::arg_expand_all
  77:     0x7ff8306c29dc - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  78:     0x7ff8306cce0f - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  79:     0x7ff8306cc5f3 - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  80:     0x7ff8306c42dd - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  81:     0x7ff8664f021c - std::sys::windows::thread::Thread::new::he1a8155b1a8cc29c
  82:     0x7ff8a7a67614 - BaseThreadInitThunk
  83:     0x7ff8a8f226a1 - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0 (2c8cc3432 2023-03-06) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method`
#1 [thir_body] building THIR for `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method`
#2 [mir_built] building MIR for `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method`
#3 [unsafety_check_result] unsafety-checking `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method`
#4 [mir_const] preparing `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method` for borrow checking
#5 [mir_promoted] processing MIR for `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method`
#6 [mir_borrowck] borrow-checking `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method`
#7 [type_of] computing type of `serial_1::serial_2::<impl at src\serial_1\serial_2.rs:70:1: 70:35>::split_method::{opaque#0}`
#8 [check_mod_item_types] checking item types in module `serial_1::serial_2`
#9 [analysis] running analysis passes on this crate
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
I did not see any additional output 
<p>

```
I did not see any backtrace output 
```

</p>
</details>

Thanks for listening,
-Michael

**Comment by lqd** [comment] 2023-04-04 09:33
Can you check on beta btw ? It should be fixed there.

**Comment by mschnell1** [comment] 2023-04-04 09:34
how to install that version ?

**Comment by lqd** [comment] 2023-04-04 09:38
`rustup install beta` should work, and then you can run your previous cargo/rustc commands that caused the error above, but with `+beta` to make sure that version is used, like `cargo +beta check`. It should show a compilation error rather than this "cannot relate bound region" ICE.

**Comment by lqd** [comment] 2023-04-04 09:54
do you have a link to your repository ?

**Comment by mschnell1** [comment] 2023-04-04 10:01
No. It's local right now. And the source code will be in the comnpabnies own GitLab server. The company right now is not inclined to contribute to the open source community (the dev department is wortking on that ....) 

Moreove my current code is mostly nonsense, anyways.

I in fact would like to be able to run the beta compiler though. (This is on Windows in the VSCode terminal. Ist tghat a problem)

**Comment by lqd** [comment] 2023-04-04 10:08
`rustc +beta -vV` and  `cargo +beta -vV` should work wherever `rustup` is in the $path. 

In any case, I'm sure this issue is solved on beta, and will become fixed on stable in 1.69 releasing in a couple weeks.

**Comment by mschnell1** [comment] 2023-04-04 10:13
rustc +beta -vV
does work 
```
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.69.0-beta.6 (6a97551bc 2023-04-02)`
```

cargo +beta -vV
does work 
```
$ cargo  +beta -vV
error: no such command: `+beta`
        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?
```

**Comment by jyn514** [comment] 2023-04-04 11:16
Duplicate of https://github.com/rust-lang/rust/issues/109361

**Closed by jyn514** 2023-04-04 11:16 UTC
Labels: I-ICE, T-compiler, C-bug
