### ISSUE TITLE
Could not compile `memorydb`.

### ISSUE THREAD

**Issue by fenrir63** [rust-lang/rust#50918] opened 2018-05-20 15:23 UTC
After updating rust, this error occurred. There was no similar problem before. Thanks for the help

```
error[E0053]: method `get` has an incompatible type for trait
   --> C:\Users\Ipa\.cargo\registry\src\github.com-1ecc6299db9ec823\memorydb-0.1.1\src\lib.rs:179:2
    |
179 |     fn get(&self, key: &H256) -> Option<DBValue> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `keccak::H256`, found struct `bigint::hash::H256`
    |
    = note: expected type `fn(&MemoryDB, &keccak::H256) -> std::option::Option<elastic_array::ElasticArray128<u8>>`
               found type `fn(&MemoryDB, &bigint::hash::H256) -> std::option::Option<elastic_array::ElasticArray128<u8>>`

error[E0053]: method `keys` has an incompatible type for trait
   --> C:\Users\Ipa\.cargo\registry\src\github.com-1ecc6299db9ec823\memorydb-0.1.1\src\lib.rs:190:2
    |
190 |     fn keys(&self) -> HashMap<H256, i32> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `keccak::H256`, found struct `bigint::hash::H256`
    |
    = note: expected type `fn(&MemoryDB) -> std::collections::HashMap<keccak::H256, i32>`
               found type `fn(&MemoryDB) -> std::collections::HashMap<bigint::hash::H256, i32>`

error[E0053]: method `contains` has an incompatible type for trait
   --> C:\Users\Ipa\.cargo\registry\src\github.com-1ecc6299db9ec823\memorydb-0.1.1\src\lib.rs:200:2
    |
200 |     fn contains(&self, key: &H256) -> bool {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `keccak::H256`, found struct `bigint::hash::H256`
    |
    = note: expected type `fn(&MemoryDB, &keccak::H256) -> bool`
               found type `fn(&MemoryDB, &bigint::hash::H256) -> bool`

error[E0053]: method `insert` has an incompatible type for trait
   --> C:\Users\Ipa\.cargo\registry\src\github.com-1ecc6299db9ec823\memorydb-0.1.1\src\lib.rs:211:2
    |
211 |     fn insert(&mut self, value: &[u8]) -> H256 {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `keccak::H256`, found struct `bigint::hash::H256`
    |
    = note: expected type `fn(&mut MemoryDB, &[u8]) -> keccak::H256`
               found type `fn(&mut MemoryDB, &[u8]) -> bigint::hash::H256`

error[E0053]: method `emplace` has an incompatible type for trait
   --> C:\Users\Ipa\.cargo\registry\src\github.com-1ecc6299db9ec823\memorydb-0.1.1\src\lib.rs:231:2
    |
231 |     fn emplace(&mut self, key: H256, value: DBValue) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `keccak::H256`, found struct `bigint::hash::H256`
    |
    = note: expected type `fn(&mut MemoryDB, keccak::H256, elastic_array::ElasticArray128<u8>)`
               found type `fn(&mut MemoryDB, bigint::hash::H256, elastic_array::ElasticArray128<u8>)`

error[E0053]: method `remove` has an incompatible type for trait
   --> C:\Users\Ipa\.cargo\registry\src\github.com-1ecc6299db9ec823\memorydb-0.1.1\src\lib.rs:250:2
    |
250 |     fn remove(&mut self, key: &H256) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `keccak::H256`, found struct `bigint::hash::H256`
    |
    = note: expected type `fn(&mut MemoryDB, &keccak::H256)`
               found type `fn(&mut MemoryDB, &bigint::hash::H256)`
```

**Comment by Mark-Simulacrum** [comment] 2018-05-28 18:42
This doesn't appear to be a compiler bug, but rather looks like one of the dependent crates to memorydb published a semver-breaking change in a release that does not break semver compatibility.  I can make it build at 0.1.1 if I lock `hashdb` to `0.1.1`. I'm not sure whether hashdb is at fault or it's dependency(s).

Either way, closing as not a bug for rust-lang/rust.

**Closed by Mark-Simulacrum** 2018-05-28 18:42 UTC
