### ISSUE TITLE
"associated function without body" error suggestion has incorrect span

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#83104] opened 2021-03-14 03:35 UTC
It suggests

```
fn foo({ <body> }
```

when it should suggest

```
fn foo() { <body> }
```

or at least suggest

```
fn foo(){ <body> }
```

-----

```rust
struct Foo;

impl Foo {
    fn foo()
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=66722d21ea825943bd00d51975489cb6))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `->`, `;`, `where`, or `{`, found `}`
 --> src/lib.rs:5:1
  |
4 |     fn foo()
  |        ---  - expected one of `->`, `;`, `where`, or `{`
  |        |
  |        while parsing this `fn`
5 | }
  | ^ unexpected token

error: associated function in `impl` without body
 --> src/lib.rs:4:5
  |
4 |     fn foo()
  |     ^^^^^^^-
  |            |
  |            help: provide a definition for the function: `{ <body> }`

error: aborting due to 2 previous errors

error: could not compile `playground`

To learn more, run the command again with --verbose.

```

**Comment by camelid** [comment] 2021-03-14 03:35
Probably the "free function without body" variant has this bug as well.

**Comment by camelid** [comment] 2021-03-14 03:36
The code at issue: https://github.com/rust-lang/rust/blob/acca818928654807ed3bc1ce0e97df118f8716c8/compiler/rustc_ast_passes/src/ast_validation.rs#L409-L419

**Comment by ThePuzzlemaker** [comment] 2021-03-23 18:48
I think I'll take a shot at this.
@rustbot claim

**Comment by ThePuzzlemaker** [comment] 2021-03-23 19:16
That was... an easy fix.
`end_point` to `next_point`
That provides this:
```rust
error: expected one of `->`, `;`, `where`, or `{`, found `}`
 --> <anon>:5:1
  |
4 |     fn foo()
  |        ---  - expected one of `->`, `;`, `where`, or `{`
  |        |
  |        while parsing this `fn`
5 | }
  | ^ unexpected token

error: associated function in `impl` without body
 --> <anon>:4:5
  |
4 |     fn foo()
  |     ^^^^^^^^- help: provide a definition for the function: `{ <body> }`

error: aborting due to 2 previous errors
```
which isn't *entirely* satisfactory imo cause the suggestion span is directly after the `)` rather than a space after, but it's at least valid Rust code that can be formatted into more "properly" formatted Rust code.

**Comment by ThePuzzlemaker** [comment] 2021-03-23 19:22
> Probably the "free function without body" variant has this bug as well.
It appears that it has a similar bug:
```rust
fn foo();
```
```
error: free function without a body
 --> <anon>:1:1
  |
1 | fn foo();
  | ^^^^^^^^^- help: provide a definition for the function: `{ <body> }`

error: aborting due to previous error
```
Looks like this can probably be fixed similarly.

**Comment by ThePuzzlemaker** [comment] 2021-03-23 19:23
Oh wait, that bug was caused by me. It looks like I'll probably have to implement a better solution.

**Comment by ThePuzzlemaker** [comment] 2021-03-23 19:25
Okay, so it appears that this bug is triggered in inherent impls with and without a semicolon, and in free functions with a semicolon. I'll have to find some kind of way to change the span depending on if it had a semicolon or not.

**Comment by ThePuzzlemaker** [comment] 2021-03-23 19:49
Okay, so it looks like in 99% of cases that trigger the same code path as this error:
- free fn
- free const
- free static
- free type
- inherent const
- inherent fn
- trait const
- trait type
- trait fn

the existing code is already correct, as in those cases a semicolon is (usually) required. Either we can modify the parser to give some kind of indication to the AST validator that an inherent fn/const/type has no semicolon at the end, or we can just use a hack to check if there's a semicolon at the end of the span

**Comment by ThePuzzlemaker** [comment] 2021-03-23 19:50
I'm not quite sure how this should be fixed :/

**Comment by camelid** [comment] 2021-03-23 20:41
> I'm not quite sure how this should be fixed :/

@ThePuzzlemaker I would suggest asking in `#t-compiler/help` since someone there can probably give advice.

**Closed** 2022-03-23 19:44 UTC
Labels: A-diagnostics, T-compiler, C-bug, A-suggestion-diagnostics, D-invalid-suggestion
