### ISSUE TITLE
Error while compling i3status-rust (current version)

### ISSUE THREAD

**Issue by mryvlin** [rust-lang/rust#105950] opened 2022-12-20 13:27 UTC
cargo install --path . --locked                                                                          ~/tmp/i3status-rust(master) [14:20:46]
  Installing i3status-rs v0.30.0 (/home/michael/tmp/i3status-rust)
    Updating crates.io index
   Compiling zbus v2.3.2
error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:971:13: failed to get layout for `Either<(std::result::Result<O, error::Error>, Pin<&mut [async block@/home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-2.3.2/src/connection.rs:830:30: 835:10]>), ((), Pin<&mut F>)>`: the type `O` has an unknown layout

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0:     0x7f067bd65a7a - std::backtrace_rs::backtrace::libunwind::trace::h06c3ddb908575635
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f067bd65a7a - std::backtrace_rs::backtrace::trace_unsynchronized::h8bfc3753e1cc3345
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f067bd65a7a - std::sys_common::backtrace::_print_fmt::h3c304feda98d6679
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f067bd65a7a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h98af9289a7a29dc2
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f067bdc87ae - core::fmt::write::h02538848739b7e2a
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/core/src/fmt/mod.rs:1208:17
   5:     0x7f067bd55f45 - std::io::Write::write_fmt::h4aac2f2c3f0128af
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/io/mod.rs:1682:15
   6:     0x7f067bd65845 - std::sys_common::backtrace::_print::h2e2acfe71f2fdb67
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f067bd65845 - std::sys_common::backtrace::print::h5bf077c253fab052
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f067bd6858f - std::panicking::default_hook::{{closure}}::h0ceeeedebdf177d0
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:267:22
   9:     0x7f067bd682cb - std::panicking::default_hook::h7d6f04e84940bd1d
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:286:9
  10:     0x7f067f040511 - rustc_driver[3622bb61b1ebe64a]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f067bd68dcd - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc60f5ae29562b326
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2032:9
  12:     0x7f067bd68dcd - std::panicking::rust_panic_with_hook::hce0f8648dbfb386b
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/panicking.rs:692:13
  13:     0x7f067eed3a81 - std[688abfdbcfe52504]::panicking::begin_panic::<rustc_errors[19d12f94925af316]::ExplicitBug>::{closure#0}
  14:     0x7f067eed3156 - std[688abfdbcfe52504]::sys_common::backtrace::__rust_end_short_backtrace::<std[688abfdbcfe52504]::panicking::begin_panic<rustc_errors[19d12f94925af316]::ExplicitBug>::{closure#0}, !>
  15:     0x7f067ee6cb46 - std[688abfdbcfe52504]::panicking::begin_panic::<rustc_errors[19d12f94925af316]::ExplicitBug>
  16:     0x7f067eed0376 - std[688abfdbcfe52504]::panic::panic_any::<rustc_errors[19d12f94925af316]::ExplicitBug>
  17:     0x7f067eed0299 - <rustc_errors[19d12f94925af316]::HandlerInner>::span_bug::<rustc_span[ea560f4838c45ec0]::span_encoding::Span, &alloc[b02cc7237b8b6455]::string::String>
  18:     0x7f067eecff00 - <rustc_errors[19d12f94925af316]::Handler>::span_bug::<rustc_span[ea560f4838c45ec0]::span_encoding::Span, &alloc[b02cc7237b8b6455]::string::String>
  19:     0x7f067eed33d9 - rustc_middle[f828bfe4cd5e1a59]::ty::context::tls::with_context_opt::<rustc_middle[f828bfe4cd5e1a59]::ty::context::tls::with_opt<rustc_middle[f828bfe4cd5e1a59]::util::bug::opt_span_bug_fmt<rustc_span[ea560f4838c45ec0]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  20:     0x7f067eed3276 - rustc_middle[f828bfe4cd5e1a59]::util::bug::opt_span_bug_fmt::<rustc_span[ea560f4838c45ec0]::span_encoding::Span>
  21:     0x7f067d78f694 - rustc_middle[f828bfe4cd5e1a59]::util::bug::span_bug_fmt::<rustc_span[ea560f4838c45ec0]::span_encoding::Span>
  22:     0x7f067ee76cc2 - <rustc_codegen_llvm[74aa7289b70d0100]::context::CodegenCx as rustc_middle[f828bfe4cd5e1a59]::ty::layout::LayoutOfHelpers>::handle_layout_err
  23:     0x7f067ee73801 - <rustc_codegen_llvm[74aa7289b70d0100]::context::CodegenCx as rustc_middle[f828bfe4cd5e1a59]::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
  24:     0x7f067ee766fa - <rustc_codegen_llvm[74aa7289b70d0100]::context::CodegenCx as rustc_middle[f828bfe4cd5e1a59]::ty::layout::LayoutOf>::layout_of
  25:     0x7f067ee6bb06 - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::place::PlaceRef<&rustc_codegen_llvm[74aa7289b70d0100]::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>
  26:     0x7f067d793c39 - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::FunctionCx<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>>::codegen_place
  27:     0x7f067d7ae88e - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::FunctionCx<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>>::codegen_rvalue
  28:     0x7f067d76fbbb - <rustc_codegen_ssa[cc351e334a9b8a56]::mir::FunctionCx<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>>::codegen_block
  29:     0x7f067d75d207 - rustc_codegen_ssa[cc351e334a9b8a56]::mir::codegen_mir::<rustc_codegen_llvm[74aa7289b70d0100]::builder::Builder>
  30:     0x7f067e50fd16 - rustc_codegen_llvm[74aa7289b70d0100]::base::compile_codegen_unit::module_codegen
  31:     0x7f067e6e6013 - <rustc_query_system[ffa0917f108ec877]::dep_graph::graph::DepGraph<rustc_middle[f828bfe4cd5e1a59]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[f828bfe4cd5e1a59]::ty::context::TyCtxt, rustc_span[ea560f4838c45ec0]::symbol::Symbol, rustc_codegen_ssa[cc351e334a9b8a56]::ModuleCodegen<rustc_codegen_llvm[74aa7289b70d0100]::ModuleLlvm>>
  32:     0x7f067e6e5e37 - <rustc_codegen_llvm[74aa7289b70d0100]::LlvmCodegenBackend as rustc_codegen_ssa[cc351e334a9b8a56]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  33:     0x7f067e6e3883 - rustc_codegen_ssa[cc351e334a9b8a56]::base::codegen_crate::<rustc_codegen_llvm[74aa7289b70d0100]::LlvmCodegenBackend>
  34:     0x7f067e6e3029 - <rustc_codegen_llvm[74aa7289b70d0100]::LlvmCodegenBackend as rustc_codegen_ssa[cc351e334a9b8a56]::traits::backend::CodegenBackend>::codegen_crate
  35:     0x7f067e2d7481 - <rustc_session[951b5ce950426db2]::session::Session>::time::<alloc[b02cc7237b8b6455]::boxed::Box<dyn core[62c015fcd585be4a]::any::Any>, rustc_interface[299971c75fff0058]::passes::start_codegen::{closure#0}>
  36:     0x7f067e2d6fa9 - rustc_interface[299971c75fff0058]::passes::start_codegen
  37:     0x7f067e2d4ca6 - <rustc_interface[299971c75fff0058]::passes::QueryContext>::enter::<<rustc_interface[299971c75fff0058]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[62c015fcd585be4a]::result::Result<alloc[b02cc7237b8b6455]::boxed::Box<dyn core[62c015fcd585be4a]::any::Any>, rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  38:     0x7f067e2d2156 - <rustc_interface[299971c75fff0058]::queries::Queries>::ongoing_codegen
  39:     0x7f067e2d1677 - <rustc_interface[299971c75fff0058]::interface::Compiler>::enter::<rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}::{closure#2}, core[62c015fcd585be4a]::result::Result<core[62c015fcd585be4a]::option::Option<rustc_interface[299971c75fff0058]::queries::Linker>, rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  40:     0x7f067e2cc658 - rustc_span[ea560f4838c45ec0]::with_source_map::<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  41:     0x7f067e2cc145 - <scoped_tls[6f6de2f0677d8068]::ScopedKey<rustc_span[ea560f4838c45ec0]::SessionGlobals>>::set::<rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  42:     0x7f067e2cb732 - std[688abfdbcfe52504]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[299971c75fff0058]::util::run_in_thread_pool_with_globals<rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>
  43:     0x7f067e903aba - <<std[688abfdbcfe52504]::thread::Builder>::spawn_unchecked_<rustc_interface[299971c75fff0058]::util::run_in_thread_pool_with_globals<rustc_interface[299971c75fff0058]::interface::run_compiler<core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>, rustc_driver[3622bb61b1ebe64a]::run_compiler::{closure#1}>::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[62c015fcd585be4a]::result::Result<(), rustc_errors[19d12f94925af316]::ErrorGuaranteed>>::{closure#1} as core[62c015fcd585be4a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f067bd72dc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h16c8b1a5112fc07f
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
  45:     0x7f067bd72dc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0cc5ff4fc4b4dcff
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/alloc/src/boxed.rs:2000:9
  46:     0x7f067bd72dc3 - std::sys::unix::thread::Thread::new::thread_start::ha7c6dff74603472f
                               at /rustc/935dc07218b4bf6e20231e44eb9263b612fd649b/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7f067ba90402 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  48:     0x7f067bb1f590 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  49:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (935dc0721 2022-12-19) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C debuginfo=1 -C strip=symbols

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

**Comment by matthiaskrgr** [comment] 2022-12-20 13:28
duplicate of https://github.com/rust-lang/rust/issues/105809 , should be fixed with next nightly

**Comment by jackh726** [comment] 2022-12-20 20:53
Closing as duplicate

**Closed by jackh726** 2022-12-20 20:53 UTC
Labels: I-ICE, T-compiler, C-bug
