### ISSUE TITLE
Negation of unsigned literals lint does not fire when literal type is deduced

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#16445] opened 2014-08-12 11:29 UTC
This leads to somewhat confusing results (see [this](http://stackoverflow.com/questions/25260919/playing-with-rusts-tuples) SO question). Example code:

```rust
fn main() {
    let pair = (2953495866u, -2953495866);

    println!("Tell me about {}", pair);
    match pair {
        (x, y) if x == y => println!("These are twins"),
        (x, y) if x + y == 0 => println!("Antimatter, kaboom!"),
        (x, _) if x % 2 == 1 => println!("The first one is odd"),
        _ => println!("No correlation..."),
    }
}
```

Prints
```
Tell me about (2953495866, 18446744070756055750)
Antimatter, kaboom!
```
No compiler output is produced.

However, when `u` is added to the second literal:

```rust
fn main() {
    let pair = (2953495866u, -2953495866u);

    println!("Tell me about {}", pair);
    match pair {
        (x, y) if x == y => println!("These are twins"),
        (x, y) if x + y == 0 => println!("Antimatter, kaboom!"),
        (x, _) if x % 2 == 1 => println!("The first one is odd"),
        _ => println!("No correlation..."),
    }
}
```

A warning is printed by the compiler:
```
<anon>:3:30: 3:42 warning: negation of unsigned int literal may be unintentional, #[warn(unsigned_negate)] on by default
<anon>:3     let pair = (2953495866u, -2953495866u);
                                      ^~~~~~~~~~~~
```

**Comment by kazagistar** [comment] 2015-01-08 07:30
Just to help provide a minimal test case:

    fn main() {
        let x: u32 = -10; -- no warning
        println!("{}", x);
    }

Basically, the linter seems to only fire if there is a `-` and `u` in the same literal, but does not actually care about negative literals being assigned to and unsigned datatype.

**Comment by huonw** [comment] 2015-01-13 02:33
Dupe of #5477.

**Closed by huonw** 2015-01-13 02:33 UTC
Labels: A-lint
