### ISSUE TITLE
`TryFrom` trait bound on trait definition complains about missing `From` impl

### ISSUE THREAD

**Issue by adamlesinski** [rust-lang/rust#80484] opened 2020-12-29 20:09 UTC
I tried this code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a9fcf72c4bbeb63baf3dffb724d37852

I expected it to compile successfully.

Instead, it fails to compile with the error:

```
error[E0277]: the trait bound `&'a <C as Container>::Item: From<&'a Wrapper>` is not satisfied
```

I do not expect that a `From` implementation is needed when implementing `TryFrom`.

If I remove the trait bound from the trait `Container`, and place it on the function `foo` instead, it works as expected: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a4bdca2f01cd2a33f85d18e5ebdb5181

Also, if the trait bound is changed to not include lifetimes or references, this works as well: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a2e8dbad7838e71b6c0b8a42fca57509

The issue happens on both Beta and Nightly.

**Comment by SkiFire13** [comment] 2020-12-29 22:44
This is a duplicate of #20671

It complains about `From` because when looking for candidate impls for `for<'a> &'a <C as Container>::Item: TryFrom<&'a Wrapper>` it found `impl<T, U> TryFrom<U> for T where U: Into<T>`, then `impl<T, U> Into<U> for T where U: From<T>`, which leads to `for<'a> &'a <C as Container>::Item: From<&'a Wrapper>`.

**Comment by adamlesinski** [comment] 2020-12-29 23:07
I see, but `impl<T, U> TryFrom<U> for T where U: Into<T>` shouldn't be a candidate, given that none of the bounds are satisfied. It should see my local implementation of TryFrom right?

**Comment by SkiFire13** [comment] 2020-12-30 09:22
It sees your local `TryFrom` implementation and correctly accepts it, however the problem isn't on the call `foo::<WrappedContainer>()` (you can even remove that call and the error will still be there, [playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=35271b53cac9d89e86d0ab9078e690a6)), the problem is on the definition of `foo` itself (`fn foo<C: Container>() {}`), in particular that `C: Container`. There the trait solver assumes that `C` implements the trait `Container`, however it doesn't assume it satisfies all the where clauses, in particular those that aren't directly on `Self` or on associated items (due to the bug I mentioned in the previous message), but it still tries to check that they're satisfied, and this obviously fails because they aren't valid for all `C`. This is why the error message mentions `for<'a> &'a <C as Container>::Item: TryFrom<&'a Wrapper>` with the generic `C` and not with your type substituted. 

ps: I think the way rustc works is that `impl<T, U> TryFrom<U> for T where U: Into<T>` becomes a candidate because it may apply without considering the bounds. Then the bounds are considered and they may lead to searching for other impls or to a dead end that removes it from the candidates. However i don't know why it's still there in the error message, I would expect it to show the original predicate it was trying to satisfy (`for<'a> &'a <C as Container>::Item: TryFrom<&'a Wrapper>`).

**Comment by Dylan-DPC** [comment] 2023-04-16 10:51
Current complete error:
```
error[[E0277]](https://doc.rust-lang.org/stable/error_codes/E0277.html): the trait bound `for<'a> &'a <C as Container>::Item: From<&'a Wrapper>` is not satisfied
  --> src/main.rs:30:11
   |
30 | fn foo<C: Container>() {}
   |           ^^^^^^^^^ the trait `for<'a> From<&'a Wrapper>` is not implemented for `&'a <C as Container>::Item`
   |
   = note: required for `&'a Wrapper` to implement `for<'a> Into<&'a <C as Container>::Item>`
   = note: required for `&'a <C as Container>::Item` to implement `for<'a> TryFrom<&'a Wrapper>`
note: required by a bound in `Container`
```

**Closed** 2024-02-18 18:20 UTC
Labels: C-bug, needs-triage-legacy
