### ISSUE TITLE
ICE documenting nalgebra

### ISSUE THREAD

**Issue by rep-nop** [rust-lang/rust#54978] opened 2018-10-11 00:15 UTC
While running `cargo doc --open`

```
error: internal compiler error: librustc/traits/select.rs:2775: Where clause `Binder(<base::default_allocator::DefaultAllocator as base::allocator::Allocator<_, _>>)` was applicable to `Obligation(predicate=Binder(TraitPredicate(<base::default_allocator::DefaultAllocator as base::allocator::Allocator<_, _, _>>)),depth=3)` butnow is not

thread '<unnamed>' panicked at 'Box<Any>', librustc_errors/lib.rs:599:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::bug
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   8: rustc::ty::context::tls::with_opt::{{closure}}
   9: rustc::ty::context::tls::with_context_opt
  10: rustc::ty::context::tls::with_opt
  11: rustc::util::bug::opt_span_bug_fmt
  12: rustc::util::bug::bug_fmt
  13: rustc::traits::select::SelectionContext::confirm_candidate
  14: rustc::infer::InferCtxt::probe
  15: rustc::traits::select::SelectionContext::evaluate_stack
  16: rustc::dep_graph::graph::DepGraph::with_anon_task
  17: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  18: rustc::infer::InferCtxt::probe
  19: <&mut I as core::iter::iterator::Iterator>::next
  20: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  21: rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache
  22: rustc::dep_graph::graph::DepGraph::with_anon_task
  23: rustc::traits::select::SelectionContext::candidate_from_obligation
  24: rustc::traits::select::SelectionContext::evaluate_stack
  25: rustc::dep_graph::graph::DepGraph::with_anon_task
  26: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  27: rustc::infer::InferCtxt::probe
  28: rustc::traits::select::SelectionContext::evaluate_stack
  29: rustc::dep_graph::graph::DepGraph::with_anon_task
  30: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  31: rustc::infer::InferCtxt::probe
  32: rustc::traits::select::SelectionContext::evaluate_stack
  33: rustc::dep_graph::graph::DepGraph::with_anon_task
  34: rustc::traits::select::SelectionContext::evaluate_predicate_recursively
  35: rustc::traits::select::SelectionContext::evaluate_obligation_recursively
  36: rustc::ty::context::tls::with_related_context
  37: rustc::infer::InferCtxtBuilder::enter
  38: rustc_traits::evaluate_obligation::evaluate_obligation
  39: rustc::ty::query::__query_compute::evaluate_obligation
  40: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::evaluate_obligation<'tcx>>::compute
  41: rustc::dep_graph::graph::DepGraph::with_task_impl
  42: rustc::ty::context::tls::with_related_context
  43: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  45: rustc::traits::query::evaluate_obligation::<impl rustc::infer::InferCtxt<'cx, 'gcx, 'tcx>>::evaluate_obligation
  46: rustc::ty::context::tls::with_context::{{closure}}
             at librustdoc/clean/blanket_impl.rs:110
             at librustc/infer/mod.rs:508
             at librustc/ty/context.rs:1676
             at librustc/ty/context.rs:2022
             at librustc/ty/context.rs:1961
             at librustc/ty/context.rs:2021
             at librustc/ty/context.rs:1675
             at librustc/ty/context.rs:2122
             at librustc/ty/context.rs:2106
  47: rustc::ty::context::GlobalCtxt::enter_local
             at librustc/ty/context.rs:2097
             at librustc/ty/context.rs:2106
             at librustc/ty/context.rs:2117
             at librustc/ty/context.rs:1668
  48: rustdoc::clean::blanket_impl::BlanketImplFinder::get_blanket_impls::{{closure}}
             at librustc/infer/mod.rs:507
             at librustdoc/clean/blanket_impl.rs:80
  49: rustc::ty::trait_def::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::for_each_relevant_impl
             at librustc/ty/trait_def.rs:106
  50: rustdoc::clean::blanket_impl::BlanketImplFinder::get_blanket_impls
             at librustdoc/clean/blanket_impl.rs:79
  51: rustdoc::clean::def_ctor::get_def_from_node_id
             at librustdoc/clean/blanket_impl.rs:42
             at librustdoc/clean/def_ctor.rs:59
  52: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector<'a, 'tcx, 'rcx, 'cstore> as rustdoc::fold::DocFolder>::fold_item
             at librustdoc/clean/blanket_impl.rs:40
             at librustdoc/clean/mod.rs:3368
             at librustdoc/passes/collect_trait_impls.rs:171
  53: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at librustdoc/fold.rs:73
             at libcore/iter/mod.rs:1640
             at liballoc/vec.rs:1782
  54: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  55: rustdoc::fold::DocFolder::fold_inner_recur
             at liballoc/vec.rs:1694
             at libcore/iter/iterator.rs:1415
             at librustdoc/fold.rs:110
             at librustdoc/fold.rs:37
  56: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector<'a, 'tcx, 'rcx, 'cstore> as rustdoc::fold::DocFolder>::fold_item
             at librustdoc/fold.rs:100
             at librustdoc/passes/collect_trait_impls.rs:178
  57: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at librustdoc/fold.rs:73
             at libcore/iter/mod.rs:1640
             at liballoc/vec.rs:1902
             at liballoc/vec.rs:1799
             at liballoc/vec.rs:1794
  58: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  59: rustdoc::fold::DocFolder::fold_inner_recur
             at liballoc/vec.rs:1694
             at libcore/iter/iterator.rs:1415
             at librustdoc/fold.rs:110
             at librustdoc/fold.rs:37
  60: <rustdoc::passes::collect_trait_impls::SyntheticImplCollector<'a, 'tcx, 'rcx, 'cstore> as rustdoc::fold::DocFolder>::fold_item
             at librustdoc/fold.rs:100
             at librustdoc/passes/collect_trait_impls.rs:178
  61: rustdoc::passes::collect_trait_impls::collect_trait_impls
             at librustdoc/fold.rs:115
             at libcore/option.rs:632
             at librustdoc/fold.rs:115
             at librustdoc/passes/collect_trait_impls.rs:26
  62: rustdoc::core::run_core::{{closure}}::{{closure}}
             at librustdoc/core.rs:611
  63: rustc::ty::context::tls::enter_context
             at librustc_driver/driver.rs:1351
             at librustc/ty/context.rs:2054
             at librustc/ty/context.rs:2022
             at librustc/ty/context.rs:1961
             at librustc/ty/context.rs:2021
  64: <std::thread::local::LocalKey<T>>::with
             at librustc/ty/context.rs:2053
             at librustc/ty/context.rs:2011
             at libstd/thread/local.rs:294
             at libstd/thread/local.rs:248
             at librustc/ty/context.rs:2003
             at libstd/thread/local.rs:294
             at libstd/thread/local.rs:248
  65: rustc::ty::context::TyCtxt::create_and_enter
             at librustc/ty/context.rs:1995
             at librustc/ty/context.rs:2033
             at librustc/ty/context.rs:1249
  66: rustc_driver::driver::spawn_thread_pool
             at librustc_driver/driver.rs:1259
             at librustdoc/core.rs:493
             at librustc_driver/driver.rs:76
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at librustc_driver/driver.rs:75
  67: rustdoc::core::run_core
             at librustdoc/core.rs:403
  68: <scoped_tls::ScopedKey<T>>::set
             at librustdoc/lib.rs:720
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at libsyntax/lib.rs:106
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  69: syntax::with_globals
             at libsyntax/lib.rs:105
  70: std::panicking::try::do_call
             at librustdoc/lib.rs:716
             at librustc_driver/lib.rs:1661
             at libstd/panic.rs:313
             at libstd/panicking.rs:310
  71: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  72: rustc_driver::monitor
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at librustc_driver/lib.rs:1575
             at librustc_driver/lib.rs:1586
             at librustc_driver/lib.rs:1660
  73: rustdoc::rust_input
             at librustdoc/lib.rs:716
  74: rustdoc::main_args
             at librustdoc/lib.rs:613
             at librustdoc/lib.rs:568
  75: <scoped_tls::ScopedKey<T>>::set
             at librustdoc/lib.rs:115
             at libcore/option.rs:424
             at librustdoc/lib.rs:115
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at libsyntax/lib.rs:106
             at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  76: syntax::with_globals
             at libsyntax/lib.rs:105
  77: std::panicking::try::do_call
             at libstd/thread/mod.rs:409
             at libstd/panic.rs:313
             at libstd/panicking.rs:310
  78: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  79: <F as alloc::boxed::FnBox<A>>::call_box
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/thread/mod.rs:408
             at liballoc/boxed.rs:672
  80: std::sys_common::thread::start_thread
             at liballoc/boxed.rs:682
             at libstd/sys_common/thread.rs:24
  81: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  82: start_thread
  83: clone

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (96cafc53c 2018-10-09) running on x86_64-unknown-linux-gnu

error: Could not document `nalgebra`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name nalgebra /home/repnop/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.16.4/src/lib.rs --cap-lints allow --color always -o /home/repnop/Dev/Rust/Help/rusty-fortyeight/target/doc--cfg 'feature="alga"' --cfg 'feature="default"' --cfg 'feature="matrixmultiply"'--cfg 'feature="rand"' --cfg 'feature="std"' --cfg 'feature="stdweb"' -L dependency=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps --extern alga=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libalga-c083721cbf712c69.rmeta --extern approx=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libapprox-da3626a877777f16.rmeta --extern generic_array=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libgeneric_array-cfd5d247a1824494.rmeta --extern matrixmultiply=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libmatrixmultiply-1118b9f253ccc604.rmeta --extern num_complex=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libnum_complex-4fb6a56bcf80ef9c.rmeta --extern num_traits=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libnum_traits-50fb4362b3b15032.rmeta --extern rand=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/librand-576c0327e3549b18.rmeta --extern typenum=/home/repnop/Dev/Rust/Help/rusty-fortyeight/target/debug/deps/libtypenum-b03ce29b3c644199.rmeta` (exit code: 1)```

**Comment by memoryruins** [comment] 2018-10-12 17:36
Duplicate of #54744

**Closed by memoryruins** 2018-10-12 17:36 UTC
Labels: I-ICE
