### ISSUE TITLE
operator overload: compiler ignores candidate Index "impls" that are "deeper" in the autoderef loop

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#26218] opened 2015-06-11 12:57 UTC
### STR

``` rust
use std::ops::{Deref, Index};

pub struct Foo(Bar);

pub struct Bar;

impl Deref for Foo {
    type Target = Bar;

    fn deref(&self) -> &Bar { &self.0 }
}

impl Index<()> for Foo {
    type Output = ();

    fn index(&self, _: ()) -> &() {
        unimplemented!()
    }
}

impl Index<i32> for Bar {
    type Output = ();

    fn index(&self, _: i32) -> &() {
        unimplemented!()
    }
}

fn test(foo: Foo) {
    foo[()]; // OK
    foo[0];
    //~^ error: expected `()` found `i32` (BUT, it should work just like the line below)
    foo.deref()[0]; // OK
}

fn main() {}
```
### Version

```
rustc 1.2.0-nightly (613e57b44 2015-06-01) (built 2015-06-02)
```

AFAIC, the problem is that the compiler only tries to unify against the first candidate implementation (in this case `Foo: Index<()>`) that finds in the autoderef loop, but in this case there was a matching candidate deeper in the autoderef loop: `Bar: Index<i32>` after one deref.
### Workaround

As a workaround, you can "forward" `Bar`'s `Index` implementation as an `Index` implementation on `Foo`:

``` rust
impl Index<i32> for Foo {
    type Output = ();

    fn index(&self, i: i32) -> &() {
        self.deref().index(i)
    }
}
```

Now the three expression type check:

``` rust
fn test(foo: Foo) {
    foo[()]; // OK
    foo[0];  // OK
    foo.deref()[0]; // OK
}
```

But this is annoying, if `Bar` has lots of `Index` implementations, then you'll need to forward each one.

The compiler should exhaustively try all the candidates in the autoderef loop instead of giving up on the first one.

cc @nikomatsakis

**Comment by nikomatsakis** [comment] 2015-06-11 21:32
This is the expected behavior; most things in autoderef loops stop at
the outermost level, and at the time we are autoderef'ing we do not
yet know the type of the index argument. I believe that's important
because we use it to supply an expected type hint when typing the
index. (Method calls work in a similar fashion, for example.)

It's possible we could experiment with changing it. Depending on the
precise rules we setup, that could be backwards incompatible.

**Comment by Popog** [comment] 2016-11-01 07:24
Ran into this and was very surprised that adding `Index` impl suddenly broke all my `Deref` coercion indexing.

This means either:
* `Deref` coercions provided by a crate can't be relied upon and `.deref()` should always be explicitly called
* or `Deref` coercions should be viewed as a contract never to add implementations that collide with the target type's impls.

Not really a fan of either of those, but if this is the plan for the moment, whichever one of those is true should probably be mentioned in the book.

**Comment by steveklabnik** [comment] 2019-12-25 16:11
Triage: given @nikomatsakis 's explanation that this is expected behavior, and there doesn't seem to be a ton of folks interested in changing it, I'm going to close this issue. Thank you!

**Closed by steveklabnik** 2019-12-25 16:11 UTC
Labels: A-typesystem, C-feature-request
