### ISSUE TITLE
Rustdoc rendering issue

### ISSUE THREAD

**Issue by jbcden** [rust-lang/rust#34501] opened 2016-06-27 16:27 UTC
When I render the documentation for the following:

```rust
fn into_path(mut self) -> PathBuf
```

I am seeing:

```rust
fn into_path(self) -> PathBuf
```
instead.

**Comment by GuillaumeGomez** [comment] 2016-06-27 16:28
Thanks, working on it!

**Comment by alexcrichton** [comment] 2016-06-27 16:38
@GuillaumeGomez hm wait hang on, the signatures here are the same as `mut` is an implementation detail in this case. I think this is intended behavior, so closing.

**Comment by alexcrichton** [comment] 2016-06-27 16:38
That is, from a client's point of view, the two signatures above are equivalent.

**Closed by alexcrichton** 2016-06-27 16:38 UTC
Labels: A-rustdoc

**Comment by GuillaumeGomez** [comment] 2016-06-27 16:39
Good, one less problem!
