### ISSUE TITLE
Windows: Self compiled rustdoc not interpreting `code` in markdown correctly

### ISSUE THREAD

**Issue by nhowell** [rust-lang/rust#26744] opened 2015-07-02 20:39 UTC
For example:
```
#![feature(rustdoc)]
extern crate rustdoc;

use rustdoc::html::markdown::Markdown;

fn main() {
    let x = "This program makes a variable binding named `x`.";
    println!("{}", Markdown(x));
}
```
This code runs fine in the playpen (http://is.gd/HVGloB) and when using the official nightly (`rustc -V` 
`rustc 1.3.0-nightly (bf3c979ec 2015-06-30)`). Expected output:
```
<p>This program makes a variable binding named <code>x</code>.</p>
```

However, I compiled Rust on my machine (`rustc -V` `rustc 1.3.0-dev (71a644136 2015-07-02)`) and I get the following output instead:
```
<p>This program makes a variable binding named <code>x</code>`x`.</p>
```
Needless to say, this is wreaking havoc on the generated docs, which I'm trying to test before I submit any significant pull requests for rustdoc or rustbook issues.

I'm running Windows 7 64-bit and I'm using MSYS2 to run `./configure` and `make`.

Any ideas? Or perhaps this is actually an issue with [Hoedown](https://github.com/hoedown/hoedown)?

**Comment by rkruppe** [comment] 2015-07-26 14:10
Duplicate of #24746

**Comment by alexcrichton** [comment] 2015-07-26 15:18
Thanks @rkruppe!

**Closed by alexcrichton** 2015-07-26 15:18 UTC
Labels: A-rustdoc
