### ISSUE TITLE
8/3 compile time regression

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#43656] opened 2017-08-05 12:09 UTC
I have noticed that mainly incremental compilation have degraded on 8/3, according to perf.rust-lang.org. Can someone do a bisect and update this issue?

**Comment by Mark-Simulacrum** [comment] 2017-08-05 13:19
It's a spurious regression; perf.rlo isn't properly tracking total time, since trans and llvm now overlap. I'm going to close this issue since there's nothing to track for this repo specifically.

**Closed** 2017-08-09 15:25 UTC
