### ISSUE TITLE
Non-`'static` lifetime inferred for return position `impl Trait` (fixed in beta)

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#65582] opened 2019-10-19 00:13 UTC
On beta and nightly, the following code is correctly rejected since the `impl Trait` in return position gets `'static` by default. However, on the current stable (1.38), it was wrongfully accepted. Replacing the trait object with another type seems to make the error appear on all versions.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=93b9e5b8b6f51eae9c9c6771a219becf)
```rust
use std::any::Any;

fn drain_dyn(v: &mut Vec<Box<dyn Any>>) -> impl Iterator<Item = Box<dyn Any>> {    
    v.drain()
}
```

This has already been fixed, so I'm not sure what the procedure is here. Observed in the crater run for 1.39 (#64962) and split out from #65527.

**Comment by Mark-Simulacrum** [comment] 2019-10-19 00:57
Nominating for compiler team -- I suspect we just want to close this, but wanted to raise this at least so we're aware. It's possible we can track down the fix and backport to stable, though at this point we're at 4 weeks out so it may not be worth it.

**Comment by Centril** [comment] 2019-10-19 05:50
I'm betting this is https://github.com/rust-lang/rust/pull/62849.

**Comment by pnkfelix** [comment] 2019-10-24 09:45
@jonas-schievink my understanding, based on the description, is that this is stable-to-stable regression that already has a fix that has ridden the trains to beta, not a stable-to-beta regression.

**Comment by pnkfelix** [comment] 2019-10-24 09:48
(unless the tagging as a regression is due to it being a user observable change in behavior from "stable rust". I need to track down what the behavior of this has been over time...)

**Comment by pnkfelix** [comment] 2019-10-24 09:56
If this *is* "just" a change in observable behavior, where we had "always" accepted the code previously, then I don't think there is any motivation to do a backport-to-stable; there is no need to speed up how soon the change lands. (If anything, we should be trying to evaluate the fallout from the change, and deciding if we need to do a *revert* of the change on beta. But I think the crater report that preceded this bug being filed is telling us that such a reversion is not necessary...)

**Comment by pnkfelix** [comment] 2019-10-24 10:03
Okay, so it looks like if you revise the test to work in older versions of Rust (by using `Box<Trait>` instead of `Box<dyn Train>` and fixing the call to `drain` to pass a range), then this has been accepted by the compiler ever since `impl Trait` in return position was stabilized, back in Rust 1.26.0.

So then the question is whether this is an old known bug in `impl Trait`; if not, then the question is if whetehr this fallout from whatever change injected this (presumably PR #62849) is acceptable/desirable.

**Comment by pnkfelix** [comment] 2019-10-24 10:04
I think resolving the questions in the previous comment is part of T-lang, not just T-compiler. Tagging with T-lang and leaving nomination tag in place for discussion at T-lang meeting.

**Comment by pnkfelix** [comment] 2019-10-24 10:08
(also, is this related to #53613 and #51525 ?)

**Comment by pnkfelix** [comment] 2019-10-24 10:17
triage: P-high. Leaving nomination tag in place, for both T-compiler and T-lang.

**Comment by jonas-schievink** [comment] 2019-10-24 14:38
According to https://github.com/rust-lang/rust/issues/65527#issuecomment-544005571, soketto 0.2.0 [broke](https://crater-reports.s3.amazonaws.com/beta-1.39-rustdoc-1/beta-2019-09-28/gh/efb9-860a-e752-0dac.rustchal/log.txt)

**Comment by nikomatsakis** [comment] 2019-10-24 18:39
Hey @twittner -- it looks like soketto 0.2.0 was affected by a recent bug fix that we did as part of the async-await work. Let us know if you need any help fixing the fallout.

**Comment by nikomatsakis** [comment] 2019-10-24 20:23
Looking more closely at this example, I am not convinced that this is related to #62849. If it were, I would expect an error message like

> return type cannot contain a projection or `Self` that references lifetimes from a parent scope

That said, this *does* really look like a bug fix -- I am pretty unclear on what fixed it, but I'm glad it got fixed! (Maybe we want to mark this as E-needs-test, even?)

**Comment by nikomatsakis** [comment] 2019-10-24 20:25
It also used to compile with `Vec`:

```rust
use std::any::Any;

fn drain_dyn(v: &mut Vec<Box<dyn Any>>) -> impl Iterator<Item = Box<dyn Any>> {
    v.drain(..)
}
```

[compiles on stable, but not nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e71ddd385cc651b1a62affcb301b812e)

**Comment by ecstatic-morse** [comment] 2019-10-24 20:57
#62849 also had a full crater run, which should have caught this (although sometimes the crate lists are updated).

**Comment by twittner** [comment] 2019-10-24 21:51
Thanks @nikomatsakis! This was fixed by https://github.com/paritytech/soketto/pull/1 and published as version 0.2.3 of soketto on 2019-08-19.

**Comment by pnkfelix** [comment] 2019-10-24 22:18
(so was this in fact fixed by #63376 ?  that might make sense...  )

**Comment by Centril** [comment] 2019-10-24 22:33
Heh; I've even left a comment wrt. soketto in that PR. 😆

**Comment by nikomatsakis** [comment] 2019-10-25 10:44
OK, I'm going to close this as "expected bug fix with no further action needed". Thanks all!

**Closed by nikomatsakis** 2019-10-25 10:44 UTC
Labels: A-impl-trait, E-needs-bisection, P-high, T-compiler, T-lang, regression-from-stable-to-beta

**Comment by nikomatsakis** [comment] 2019-10-25 10:45
Note that the PR includes a text that seems like the same basic scenario:

src/test/ui/object-lifetime/object-lifetime-default-dyn-binding-nonstatic1.rs
