### ISSUE TITLE
Rustdoc should show which marker traits a type implements

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#17606] opened 2014-09-28 04:51 UTC
I don't think there's any way right now to find out if some type is e.g. `Sync` without trying to compile code that depends on it.

**Comment by kballard** [comment] 2015-04-11 23:20
OIBITs didn't solve this. Well, it solved it for `Copy`, but the traits that have default impls (e.g. `unsafe impl Sync for .. { }`) still don't show up in rustdoc. A trait will show the negative impl if it has one, but not if it inherits its negative impl from a field.

**Comment by kballard** [comment] 2015-04-11 23:22
Nominating. I really think this needs to be fixed. Not having `Sync`/`Send` properly documented on types can be a real source of confusion. As this is a documentation issue, it could come after 1.0, but if we're expecting a bunch of people to start jumping into Rust as soon as 1.0 is released (which seems reasonable), then we should really try and have this done before then.

**Comment by tomjakubowski** [comment] 2015-04-12 02:44
I think the easiest solution is to walk all the impls for the type and check whether !Sized or !Share are among them. If not, synthesize a positive impl for documentation purposes. 



—

**Comment by pnkfelix** [comment] 2015-04-16 21:18
Not 1.0; P-low.  (Also, not clear how to solve this, since most of the time the presence/absence of an impl is dependent on the particular type parameters you are instantiated with.)

**Comment by aturon** [comment] 2015-04-23 21:30
Hm, I would prefer P-medium here; I think this is a very important piece of documentation to provide.

**Comment by gnzlbg** [comment] 2016-02-19 13:01
https://www.reddit.com/r/rust/comments/46e32h/structs_not_fully_described_w_r_t_send_sync_drop/

**Comment by kscz** [comment] 2016-03-28 00:50
As an additional urge to boost the priority on this: as someone who has been learning Rust, this is still super bewildering for Copy.  i32 and i64 both implement Copy (as far as I can tell), but https://doc.rust-lang.org/nightly/std/primitive.i32.html and https://doc.rust-lang.org/std/marker/trait.Copy.html don't list the integer types as being copy-able.

This is mostly confusing when I'm trying to explain to other people the difference between a type which implements move semantics and a type which implements copy semantics; some of the core types don't expose their underlying behavior in the documentation.

**Comment by aturon** [comment] 2016-03-28 17:56
So it looks like `Copy` is working OK *except* for primitive types, which suggests there's just a bug in the handling there. (Whereas "auto traits" like `Send` are trickier)

@jonathandturner, if you wanted to do some rustdoc hacking, fixing the issue around `Copy` might be a reasonable place to dive in.

**Comment by nagisa** [comment] 2016-07-27 19:16
Still an issue.

**Comment by frewsxcv** [comment] 2016-09-13 00:55
Worth mention this issue: https://github.com/rust-lang/rust/issues/33772 

Not directly related, but remotely similar

**Comment by RalfJung** [comment] 2017-04-26 07:44
My issue has been closed as a dupe of this one, so let me add that implemented kinds are not the only missing bit of information: Other things that rustdoc should show include variance of lifetime/type parameters and whether type parameters appear only below a pointer indirection (the latter being relevant for recursive types).

**Comment by Aaron1011** [comment] 2017-10-04 03:28
I'd like to work on this.

**Comment by gnzlbg** [comment] 2018-01-31 17:11
I wasted a reasonable amount of time today because I thought some type wasn't Send + Sync because rustdoc did not show this to me :/

**Comment by QuietMisdreavus** [comment] 2018-02-22 18:56
Thanks to https://github.com/rust-lang/rust/pull/47833 this issue is now resolved! Starting in tomorrow's nightly docs, there will be a new "Auto Trait Implementations" section showing off under what conditions a type impls Send or Sync.

**Closed by QuietMisdreavus** 2018-02-22 18:56 UTC
Labels: A-rustdoc, C-feature-request, P-low, T-dev-tools

**Comment by alexreg** [comment] 2018-02-22 19:01
Great work on this! I’ve been waiting for this feature for a while now. :-)
