### ISSUE TITLE
"Illegal instruction" from oxipng on old CPU (i5-650)

### ISSUE THREAD

**Issue by vkcz** [rust-lang/rust#75612] opened 2020-08-17 01:23 UTC
I was trying to run `oxipng` (PNG optimization software in Rust), but it did not finish correctly; it terminated with the message `Illegal instruction`.

The computer I was using was running Windows 7 on the x86_64 Intel Core i5-650, and I installed and ran `oxipng` through Cygwin bash.

I installed `oxipng` with `cargo install oxipng` and invoked `oxipng` with `oxipng example.png` (in a directory containing a valid `example.png`).

`oxipng` gave this output:
```
Processing: example.png
    2048x2048 pixels, PNG format
    4x8 bits/pixel, RGBA
    IDAT size = 183755 bytes
    File size = 183812 bytes
Illegal instruction
```

There were no errors when I was installing `oxipng`, nor when I ran `oxipng --help`. I have tried `oxipng` on other images with similar results.

(I understand this seems focused on `oxipng`, but someone I talked to outside of Github had `oxipng` working on their device and said the issue should be here.)

I was using `rustc` stable version `1.45.2` and `cargo 1.45.1`.

**Comment by Nicholas-Baron** [comment] 2020-08-17 04:21
What is the output of `lscpu`, specifically the 'flags' category? There may be some flag that the compiler assumes is enabled, when it is not truly enabled.

Is there a way you could use `gdb` or some other tool to determine what instruction causing the issue or even what function it is in?

**Comment by ollie27** [comment] 2020-08-17 08:24
This is a bit of a guess but `cloudflare-zlib` which is a dependency of `oxipng` is compiled with AVX enabled on Windows MSVC: https://gitlab.com/kornelski/cloudflare-zlib-sys/-/blob/c70f245e7c9533984aac95a28caed78df39e500a/sys/build.rs#L37. The i5-650 doesn't support AVX which would explain the illegal instruction. It would be worth checking if this also reproduces with the `x86_64-pc-windows-gnu` target assuming the issue is with `x86_64-pc-windows-msvc`.

If that's correct then this should be reported upstream instead.

**Comment by mati865** [comment] 2020-08-17 10:19
I don't think `cloudflare-zlib` does support MinGW.

**Comment by LeSeulArtichaut** [comment] 2020-08-17 16:52
@rustbot ping windows
Maybe someone can look into this? In particular, I think checking @ollie27's hypothesis would be great

**Comment by vkcz** [comment] 2020-08-17 19:37
> I don't think `cloudflare-zlib` does support MinGW.

I was using Cygwin.

> It would be worth checking if this also reproduces with the `x86_64-pc-windows-gnu` target assuming the issue is with `x86_64-pc-windows-msvc`.

I'll try that soon.

**Comment by retep998** [comment] 2020-08-17 20:29
`cc.flag_if_supported("/arch:AVX");` is definitely flat out wrong if intending to run the software on CPUs without AVX support. What is the current recommended approach to identifying the CPU target features for the target from the build script?

**Comment by ollie27** [comment] 2020-08-17 21:38
@vkcz could you try a different deflate implementation (i.e. passing `--zopfli` or `--libdeflater` to `oxipng`)? If they work it would suggest the issue is with `cloudflare-zlib`.

**Comment by vkcz** [comment] 2020-08-18 18:57
> (i.e. passing `--zopfli` or `--libdeflater` to oxipng)

Both of these also give `Illegal instruction`.

**Comment by shssoichiro** [comment] 2020-08-18 21:10
My initial guess was also that this was related to cloudflare-zlib, but that shouldn't be triggering with zopfli or libdeflater.

**Comment by spastorino** [comment] 2020-08-19 14:39
Removing `I-prioritize` label until there's evidence that this is an issue on rustc side. [Discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2375612.20.22Illegal.20instruction.22.20from.20oxipng.20on.20ol.E2.80.A6).

**Comment by vkcz** [comment] 2020-08-25 19:06
```
[New Thread 7288.0x4c58]
[New Thread 7288.0x4ac4]
[New Thread 7288.0x4c18]
[New Thread 7288.0x4af4]
[New Thread 7288.0x512c]

Thread 3 received signal SIGILL, Illegal instruction.
[Switching to Thread 7288.0x4ac4]
0x000000013f76f6be in ?? ()
```
This was added when I ran it with GDB

**Comment by shssoichiro** [comment] 2020-08-26 14:42
Are you able to get a backtrace? (typing "bt" when that exception occurs in gdb?) Might require recompiling oxipng with `debug = true` for the release profile.

**Comment by vkcz** [comment] 2020-08-28 17:01
```
(gdb) target exec target/release/oxipng
(gdb) set args example.png
(gdb) run
Starting program: /REDACTED/oxipng/target/release/oxipng example.png
Processing: example.png
    1200x800 pixels, PNG format
    4x8 bits/pixel, RGBA
    IDAT size = 32967 bytes
    File size = 33061 bytes
[New Thread 17760.0x46d8]
[New Thread 17760.0x5bf8]
[New Thread 17760.0x47b0]
[New Thread 17760.0x1f28]
[New Thread 17760.0x42e0]

Thread 5 received signal SIGILL, Illegal instruction.
[Switching to Thread 17760.0x1f28]
0x000000013f7b537e in ?? ()
(gdb) bt
#0  0x000000013f7b537e in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
It seems to be no. (I did `debug = true`)
`cargo run --release -- example.png` gives `error: process didn't exit successfully: target\release\oxipng.exe example.png (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)`

**Comment by mati865** [comment] 2020-08-28 18:00
In this case you'd have to type `d` in gdb.

**Comment by vkcz** [comment] 2020-08-28 22:05
Typing `d` in `gdb` (immediately after `run` or after `st`) gives no output -- not even a `Undefined command`.

**Comment by tasogare3710** [comment] 2021-03-14 22:48
Hi, I tried building oxipng with haswell pentium(pentium doesn't have AVX even with haswell cpu) and `x86_64-pc-windows-msvc` toolchain.

```
C:\Users\masked\path>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\me\.rustup

nightly-x86_64-pc-windows-msvc (default)
rustc 1.52.0-nightly (acca81892 2021-03-13)
```

Oxipng's main.rs see to always use cloudflare-zlib, libdeflater, zopfli, rayon. Therefore, the following command failed.

```
cargo install --no-default-features --features "binary" oxipng
```
See also:
https://github.com/shssoichiro/oxipng/blob/master/Cargo.toml#L69

`cargo install oxipng` command succeed in the installation, but when I run oxipng, it returns exit code -1073741795( == STATUS_ILLEGAL_INSTRUCTION ) and exits.

 ```
C:\Users\masked\path>echo %errorlevel%
0

C:\Users\masked\path>oxipng 001.png
Processing: 001.png
    1484x654 pixels, PNG format
    8 bits/pixel, 256 colors in palette
    IDAT size = 256172 bytes
    File size = 257056 bytes

C:\Users\masked\path>echo %errorlevel%
-1073741795
```

Next, after rewriting cloudflare-zlib-sys to always use SSE4.2 instead of AVX, build oxipng from the source code and executing the oxipng command obtained from that build returns exit code 0 and exits.

modify "/arch:AVX" in the following two places to "/arch:SSE4.2".

https://gitlab.com/kornelski/cloudflare-zlib-sys/-/blob/c70f245e7c9533984aac95a28caed78df39e500a/sys/build.rs#L37
https://gitlab.com/kornelski/cloudflare-zlib-sys/-/blob/c70f245e7c9533984aac95a28caed78df39e500a/sys/build.rs#L60

[cc::Build::is_flag_supported](https://docs.rs/cc/1.0.67/cc/struct.Build.html#method.is_flag_supported) is used incorrectly and that haven't retrieved the bool value from `Result`. but, I don't think this is relevant.

```
C:\Users\masked\path>echo %errorlevel%
0

C:\Users\masked\path>oxipng 001.png
Processing: 001.png
    1484x654 pixels, PNG format
    8 bits/pixel, 256 colors in palette
    IDAT size = 256172 bytes
    File size = 257056 bytes
Trying: 8 combinations
    IDAT size = 256172 bytes (0 bytes decrease)
    file size = 257056 bytes (0 bytes = 0.00% decrease)
File already optimized

C:\Users\masked\path>echo %errorlevel%
0
```

I think that issue with cloudflare-zlib-sys or cc( or others).

I agree with @retep998 opinion.

**Comment by nagisa** [comment] 2021-03-14 23:01
Closing this as a not-a-bug. Thank you for your experiments and information.

**Closed by nagisa** 2021-03-14 23:01 UTC
Labels: C-bug, O-windows, T-compiler
