### ISSUE TITLE
error: unable to get packages from source 

### ISSUE THREAD

**Issue by levivic** [rust-lang/rust#42296] opened 2017-05-29 14:47 UTC
Trying to build rust from source by `./x.py build --verbose`. However, it always reports `error: unable to get packages from source`. This always comes up after extracting cargo-nightly-s390x-unknown-linux-gnu.tar.gz. I am building rust 1.17.0 on Ubuntu 16.04 on s390x arch.

**Comment by Mark-Simulacrum** [comment] 2017-06-23 12:45
This appears to be a problem in Cargo; I suspect that perhaps your cache of the index isn't properly updated or something like that. Could you post the full log? I suspect this isn't a problem with rustbuild, but with Cargo, but tagging as rustbuild since it's the best approximation.

**Comment by levivic** [comment] 2017-06-23 14:14
Hi Mark, this is the log where it ends.

```
running: curl -# --retry 3 -Sf -o /tmp/tmpdouQvP.sha256 https://static.rust-lang.org/dist/2017-04-27/cargo-0.18.0-s390x-unknown-linux-gnu.tar.gz.sha256
######################################################################## 100.0%
downloading https://static.rust-lang.org/dist/2017-04-27/cargo-0.18.0-s390x-unknown-linux-gnu.tar.gz
running: curl -# --retry 3 -Sf -o /tmp/tmpr1Hsbp https://static.rust-lang.org/dist/2017-04-27/cargo-0.18.0-s390x-unknown-linux-gnu.tar.gz
######################################################################## 100.0%
verifying /tmp/tmpr1Hsbp
moving /tmp/tmpr1Hsbp to /root/lei_rust/rust/build/cache/2017-04-27/cargo-0.18.0-s390x-unknown-linux-gnu.tar.gz
removing /tmp/tmpdouQvP.sha256
extracting /root/lei_rust/rust/build/cache/2017-04-27/cargo-0.18.0-s390x-unknown-linux-gnu.tar.gz
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/manifest.in
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/bin
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/bin/cargo
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-run.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-search.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-update.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-init.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-rustdoc.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-yank.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-version.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-install.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-owner.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-pkgid.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-bench.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-package.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-login.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-clean.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-build.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-rustc.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-publish.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-test.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-doc.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-fetch.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-uninstall.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-generate-lockfile.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-metadata.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-new.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/man/man1/cargo-check.1
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/zsh
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/zsh/site-functions
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/zsh/site-functions/_cargo
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/doc
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/doc/cargo
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/doc/cargo/LICENSE-MIT
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/doc/cargo/LICENSE-APACHE
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/doc/cargo/README.md
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/share/doc/cargo/LICENSE-THIRD-PARTY
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/etc
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/etc/bash_completions.d
  extracting cargo-0.18.0-s390x-unknown-linux-gnu/cargo/etc/bash_completions.d/cargo
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading gcc v0.3.45
error: unable to get packages from source

To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:01:01

```

**Comment by Mark-Simulacrum** [comment] 2017-06-23 14:16
cc @alexcrichton -- any thoughts on what the reasons for this could be?

I'm not sure if this'll help, but if you rerun with `-vvv` does Cargo print out more information?

**Comment by levivic** [comment] 2017-06-23 14:19
Just keep getting the same error
```
root@csz25020:~/rust# ./x.py build -vvv
 Downloading cmake v0.1.22
error: unable to get packages from source

To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:00
root@csz25020:~/rust# ./x.py build -vvv
 Downloading libc v0.2.21
error: unable to get packages from source

To learn more, run the command again with --verbose.
Build completed unsuccessfully in 0:00:01
```

**Comment by alexcrichton** [comment] 2017-06-23 14:59
@levivic can you add `--verbose` to [this array](https://github.com/rust-lang/rust/blob/1.17.0/src/bootstrap/bootstrap.py#L371-L372) and try again?

**Comment by levivic** [comment] 2017-06-23 15:24
I got something like this, and every time the package which was unable to get is different.
```
root@csz25020:~/rust# ./x.py build --verbose
 Downloading toml v0.1.30
error: unable to get packages from source

Caused by:
  failed to unpack package `toml v0.1.30`

Caused by:
  failed to iterate over archive

Caused by:
  corrupt deflate stream
Build completed unsuccessfully in 0:00:00
```

**Comment by Mark-Simulacrum** [comment] 2017-06-23 15:26
Hm, interesting. If you manually download one of them, using https://gist.github.com/nikomatsakis/75e09ed314bea715e192ce226127d3c6, does that work?

**Comment by levivic** [comment] 2017-06-23 15:33
I have run 
```
curl -L https://crates.io/api/v1/crates/conrod/0.32.0/download | tar zxf -
```
and that would work

**Comment by alexcrichton** [comment] 2017-06-23 15:34
@levivic can you try `rm -rf $HOME/.cargo/registry`? This may have just been a corrupt download? That shouldn't happen inside of Cargo but that should hopefully confirm whether that was the issue or not.

**Comment by levivic** [comment] 2017-06-23 15:37
```
root@csz25020:~/rust# rm -rf ~/.cargo/registry
root@csz25020:~/rust# ./x.py build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading filetime v0.1.10
error: unable to get packages from source

Caused by:
  failed to unpack package `filetime v0.1.10`

Caused by:
  failed to iterate over archive

Caused by:
  corrupt deflate stream
Build completed unsuccessfully in 0:00:40

```

**Comment by alexcrichton** [comment] 2017-06-23 15:39
This may just be a bug in s390x, it is not a "guaranteed to work" platform.

**Comment by levivic** [comment] 2017-06-23 15:44
Are there any plans for a port?

**Comment by alexcrichton** [comment] 2017-06-23 15:48
We have one! It's just not guaranteed to work :)

The s390x platform right now works thorugh community contributions, so this'll require someone to debug why this is failing and likely submit an upstream patch to the right location to fix it.

**Comment by Mark-Simulacrum** [comment] 2017-09-15 01:17
Closing; this is not a bug in rust-lang/rust and should be refiled to rust-lang/cargo. Thanks!

**Closed by Mark-Simulacrum** 2017-09-15 01:17 UTC
Labels: A-rustbuild, C-bug
