### ISSUE TITLE
Loop evaluating Cow<'a, T>: Sized in recursive structure

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#23714] opened 2015-03-25 20:22 UTC
The example causes the checker to loop with build `rustc 1.0.0-dev (81938ec58 2015-03-25) (built 2015-03-25)`:

```
src/lib.rs:1:1: 1:1 error: overflow evaluating the requirement `collections::borrow::Cow<'static, Foo> : core::marker::Sized` [E0275]
```

It does still work using the Rust playpen [here](http://is.gd/pCiBsJ). I'm not sure if something changed in the API or if it's a bug or something else. The docs show `ToOwned::Owned: Sized` so the requirement should be satisfied. /cc @aturon 

``` rust
use std::borrow::*;

enum Foo {
    Bar,
    Baz { cow: Cow<'static, Foo> }
}

impl ToOwned for Foo {
    type Owned = Box<Foo>;
    fn to_owned(&self) -> Box<Foo> {
        let res = match self {
            &Foo::Bar => {
                Foo::Bar
            },
            &Foo::Baz { ref cow } => {
                Foo::Baz { cow: cow.to_owned() }
            }
        };
        Box::new(res)
    }
}

impl Borrow<Foo> for Box<Foo> {
    fn borrow(&self) -> &Foo {
        &**self
    }
}
```

**Comment by aturon** [comment] 2015-03-25 20:38
I believe that @nikomatsakis recently made a change that detected overflow, that may be related (I don't recall the details offhand).

**Comment by freebroccolo** [comment] 2015-03-26 00:43
I haven't pinpointed the commit which causes the issue but it is somewhere within 1be8fcb..c5c3de0.

**Comment by mitchmindtree** [comment] 2015-03-26 04:39
I think #23707 might be related

**Comment by nikomatsakis** [comment] 2015-03-26 19:40
so yes I think this is a dup of #23707 but the error was being swallowed somewhere

**Comment by nikomatsakis** [comment] 2015-03-26 19:40
and I think #23707 is a dup of an older issue too :)

**Comment by nikomatsakis** [comment] 2015-03-26 19:43
sorry I'm not sure if this is a dup of #23707 specifically; I was thinking of another issue

**Comment by jmgrosen** [comment] 2016-06-10 09:10
Any progress here? I'm running into this as well.

**Comment by aturon** [comment] 2016-06-10 17:37
Nominating for discussion at compiler team meeting.

**Comment by eddyb** [comment] 2016-06-23 21:07
This produces "error: overflow evaluating the requirement `Foo: std::marker::Sized` [E0275]":
```rust
use std::borrow::ToOwned;

enum Foo {
    Bar,
    Baz { cow: Result<&'static Foo, <Foo as ToOwned>::Owned> }
}

impl ToOwned for Foo {
    type Owned = Box<Foo>;
    fn to_owned(&self) -> Box<Foo> { loop {} }
}
```

However, this works:
```rust
use std::borrow::Borrow;

pub trait ToOwned {
    type Owned: Borrow<Self>;
    fn to_owned(&self) -> Self::Owned;
}

enum Foo {
    Bar,
    Baz { cow: Result<&'static Foo, <Foo as ToOwned>::Owned> }
}

impl ToOwned for Foo {
    type Owned = Box<Foo>;
    fn to_owned(&self) -> Box<Foo> { loop {} }
}
```

Does this have to do with coherence cross-crate interactions?

**Comment by jonas-schievink** [comment] 2017-02-16 13:52
Both of @eddyb's examples compile now, while the code in the OP still fails.

**Comment by steveklabnik** [comment] 2019-04-19 16:44
Triage: OP's code produces

```text
error[E0119]: conflicting implementations of trait `std::borrow::Borrow<Foo>` for type `std::boxed::Box<Foo>`:
  --> src/main.rs:25:1
   |
25 | impl Borrow<Foo> for Box<Foo> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `alloc`:
           - impl<T> std::borrow::Borrow<T> for std::boxed::Box<T>
             where T: ?Sized;

error[E0275]: overflow evaluating the requirement `<Foo as std::borrow::ToOwned>::Owned`
  |
  = note: required because it appears within the type `Foo`
  = note: required because of the requirements on the impl of `std::borrow::ToOwned` for `Foo`
  = note: required because it appears within the type `Foo`
```

**Comment by jonas-schievink** [comment] 2019-04-19 17:27
FWIW the issues I had with this in https://github.com/jonas-schievink/xml-rpc-rs/issues/10 are still very much there

**Comment by jonas-schievink** [comment] 2019-12-31 13:17
Minimized example:

```rust
use std::marker::PhantomData;

trait MyToOwned {
    type Owned;
}

// This has an implicit `T: Sized` bound
impl<'a, T> MyToOwned for &'a T {
    type Owned = ();
}

struct MyCow<B: MyToOwned + ?Sized> {
    _owned: <B as MyToOwned>::Owned,
}

struct Test {
    _f: MyCow<&'static Test>,
}
```

Adding `T: ?Sized` to the `MyToOwned` impl breaks the cycle. It seems that the `Test` definition will check wellformedness of `MyCow<&'static Test>`, which ends up requiring `&'static Test: MyToOwned`, which requires `Test: Sized` due to the `MyToOwned` impl. This then apparently requires wellformedness of `Test` again, or something similar.

I do not think this should be an error, since `MyCow<B>` is *always* `Sized`, regardless of `B`. It looks to me like `Sized` should maybe be treated more similarly to auto-traits like `Send` and `Sync`, but I'm not entirely sure either.

**Comment by jonas-schievink** [comment] 2019-12-31 15:43
Interestingly this is accepted:

```rust
trait MyToOwned {
    type Owned;
}

// This has an implicit `T: Sized` bound
impl<'a, T> MyToOwned for &'a T {
    type Owned = ();
}

struct MyCow<O, B: MyToOwned<Owned = O> + ?Sized> {
    _owned: (O, B),
}

struct Test {
    _f: MyCow<<&'static Test as MyToOwned>::Owned, &'static Test>,
}
```

**Comment by sunjay** [comment] 2022-01-01 02:00
Ran into this today with some code very similar to the original example. Reduced version below: ([Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5da609b4e7d29ae246fb7010804481f0))

```rust
use std::borrow::Cow;

struct Element {
    children: Cow<'static, [Element]>,
}
```

I believe this _should_ be accepted because the `Cow` ends up being an enum of either `&[Element]` or `Vec<Element>`, both of which are sized. 

The error message is initially pretty confusing because `ToOwned` is implemented for all `[T]` so it works in other cases. I did eventually realize it was because rustc is having trouble determining the size of `Element` without overflowing:

```
error[E0277]: the trait bound `[Element]: ToOwned` is not satisfied in `Element`
 --> src/lib.rs:4:28
  |
4 |     children: Cow<'static, [Element]>,
  |                            ^^^^^^^^^ within `Element`, the trait `ToOwned` is not implemented for `[Element]`
  |
  = help: the following implementations were found:
            <[T] as ToOwned>
note: required because it appears within the type `Element`
 --> src/lib.rs:3:8
  |
3 | struct Element {
  |        ^^^^^^^
  = note: slice and array elements must have `Sized` type

For more information about this error, try `rustc --explain E0277`.
```

It's definitely an issue with the traits because this version that just uses simple types directly compiles with no issues: ([Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8af43d5b0806eb6f9ee6ddf9d8a68767))

```rust
enum Array<'a, T> {
    Borrowed(&'a [T]),
    Owned(Vec<T>),
}

struct Element {
    children: Array<'static, Element>,
}
```

Something like this is probably a reasonable workaround for anyone else running into something similar.

**Comment by ice1000** [comment] 2023-01-11 21:37
@sunjay's example is exactly what I had when I ran into this issue. Writing my own cow array is not feasible because you not only need to define your own data type, but also all the operations, which is too much for me :(

**Comment by Enselic** [comment] 2024-11-25 19:05
Triage: According to https://github.com/rust-lang/rust/issues/129541#issuecomment-2315191649 this has been fixed by accident. Now we just need a regression test(s) to close this issue.

**Comment by Enselic** [comment] 2024-11-26 06:03
Triage: This should actually be covered by the test added via https://github.com/rust-lang/rust/pull/133473/files which belongs as another issue. Closing as obsolete.

**Closed by Enselic** 2024-11-26 06:03 UTC
Labels: E-needs-test, P-medium, A-borrow-checker, T-compiler, C-bug
