### ISSUE TITLE
rustc cannot detect never-ending while loop

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#49138] opened 2018-03-18 15:01 UTC
Hello,

IMHO both of these functions should compile, but in reality only the one with `loop` does:

```
fn borks() -> ! {
    while true {}
}

fn works() -> ! {
    loop {}
}
```

**Comment by sfackler** [comment] 2018-03-18 15:41
Duplicate of #43154

**Closed** 2018-03-18 20:30 UTC
