### ISSUE TITLE
Compiler error when trying to use riker actors

### ISSUE THREAD

**Issue by dantodor** [rust-lang/rust#59010] opened 2019-03-08 02:46 UTC
I'm trying to play with the riker actor library, with no luck.
The code is exactly the one described in the first page of the documentation, [Actors](https://riker.rs/actors/)
Using latest nightly, this is the result I get :

`error: internal compiler error: src/librustc_codegen_llvm/debuginfo/type_names.rs:176: debuginfo: Trying to create type name for unexpected type: impl std::future::Future`

`thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error`

`note: the compiler unexpectedly panicked. this is a bug.`

`note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports`

`note: rustc 1.35.0-nightly (88f755f8a 2019-03-07) running on x86_64-apple-darwin`

`note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin`

`note: some of the compiler flags provided by cargo are hidden`

Since I'm pretty new to Rust, please excuse my eventual inconsistency :)

**Comment by estebank** [comment] 2019-03-08 04:23
CC #58945

**Comment by jonas-schievink** [comment] 2019-03-08 13:51
Closing as a duplicate of #58945

**Closed by jonas-schievink** 2019-03-08 13:51 UTC
Labels: A-debuginfo, I-ICE, T-compiler
