### ISSUE TITLE
rustdoc should only include &self methods from Deref target

### ISSUE THREAD

**Issue by Storyyeller** [rust-lang/rust#39550] opened 2017-02-05 03:48 UTC
Currently, if Foo impls Deref<Target=Bar>, then the generated documentation for Foo will include every method defined on Bar, regardless of receiver type. &mut self methods should only be included if DerefMut is impled, and self methods shouldn't be included at all.

It may also be worth excluding methods on the Deref target from the generated documentation if a method of the same name is defined on the original type, since that's the one that will be called under normal circumstances.

**Comment by durka** [comment] 2017-02-06 20:08
This is a dupe of #35169 which was supposedly fix in #36266, has it regressed?

**Comment by Storyyeller** [comment] 2017-02-06 21:27
For example, https://docs.rs/easy_strings/0.1.0/easy_strings/struct.EZString.html#method.into_bytes

into_bytes(self) is included, despite taking self by value. Perhaps it only filters out &mut self methods, but doesn't filter self methods?

**Comment by durka** [comment] 2017-02-06 21:44
Yeah, I guess the work in #36266 needs to be extended to also filter out methods with by-value receivers.

**Comment by ollie27** [comment] 2017-02-07 14:04
Removing by-value methods was attempted and rejected in #33396.

**Comment by QuietMisdreavus** [comment] 2017-09-29 02:33
The issue that's causing this is that `DerefMut` confuses [the check that rustdoc does right here](https://github.com/rust-lang/rust/blob/3c96d40d326b64f6a50f4a902051fe71c4acdc92/src/librustdoc/html/render.rs#L3212-L3223). If DerefMut is implemented, then that allows anything that's not `self: Box<Self>`, where it should also check that it's not a by-value `self` as well. Extending this to add another `by_value` condition (which should only be true in that `_` branch, which corresponds to `SelfTy::SelfValue`) which further masks the bool that's handed to `render_method_item` in the above scope, will solve this.

**Closed** 2017-11-20 17:26 UTC
Labels: A-rustdoc, C-enhancement, E-easy, E-mentor, T-dev-tools
