### ISSUE TITLE
error: internal compiler error: static call to invalid vtable

### ISSUE THREAD

**Issue by robertfoss** [rust-lang/rust#21250] opened 2015-01-16 20:05 UTC
$ cargo --version --verbose 
cargo 0.0.1-pre-nightly (8154255 2015-01-14 19:14:12 +0000)

$ RUST_BACKTRACE=1 cargo build --verbose
       Fresh rustc-serialize v0.2.8
       Fresh regex v0.1.10
       Fresh typeable v0.0.7
       Fresh phantom v0.0.3
       Fresh unsafe-any v0.2.1
       Fresh unicase v0.0.2
       Fresh mucell v0.1.10
       Fresh pkg-config v0.1.4
       Fresh matches v0.1.2
       Fresh gcc v0.1.4
       Fresh modifier v0.0.7
       Fresh log v0.1.9
       Fresh error v0.1.1
       Fresh typemap v0.0.7
       Fresh url v0.2.16
       Fresh mime v0.0.6
       Fresh plugin v0.2.0
       Fresh openssl-sys v0.2.15
       Fresh time v0.1.12
       Fresh openssl v0.2.15
       Fresh cookie v0.1.8
       Fresh hyper v0.1.1
       Fresh iron v0.0.12 (https://github.com/iron/iron.git#5fc509a2)
   Compiling speedtest v0.0.1 (file:///home/david/speedtest)
     Running `rustc src/bin/speedtest.rs --crate-name speedtest --crate-type bin -g --out-dir /home/david/speedtest/target --emit=dep-info,link -L dependency=/home/david/speedtest/target -L dependency=/home/david/speedtest/target/deps --extern iron=/home/david/speedtest/target/deps/libiron-afb9726a49e90dd2.rlib --extern speedtest=/home/david/speedtest/target/libspeedtest-55fb5e30e4d68ad8.rlib -L native=/home/david/speedtest/target/build/time-7c7fc3eb0c12ad75/out`
error: internal compiler error: static call to invalid vtable: VtableObject(VtableObject(object_ty=error::Error + 'static))
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:182

stack backtrace:
   1:     0x7f7b20e31000 - sys::backtrace::write::h7e8ba1fc274cc36epRt
   2:     0x7f7b20e529e0 - failure::on_fail::h823798930ebe140a64z
   3:     0x7f7b20dc17b0 - rt::unwind::begin_unwind_inner::ha4a8df6010104da6ZJz
   4:     0x7f7b1ba2b330 - rt::unwind::begin_unwind::h2017061421562134061
   5:     0x7f7b1ba2bbd0 - diagnostic::Handler::bug::hd9668c89a1475b64I4F
   6:     0x7f7b1f0e2240 - session::Session::bug::h5b142cd57aa635b7Ybr
   7:     0x7f7b1fe0cb20 - trans::meth::trans_static_method_callee::h9cd746874bcc700fJdz
   8:     0x7f7b1fe09910 - trans::callee::trans::h29e4b3d00e840df8Oag
   9:     0x7f7b1fe13590 - trans::callee::trans_call_inner::h6471369785741005877
  10:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  11:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  12:     0x7f7b1fdd07e0 - trans::controlflow::trans_block::h28afa8af906ef58bQ3d
  13:     0x7f7b1fe9ac80 - trans::base::trans_closure::h9a0d2c21a0e18266U0t
  14:     0x7f7b1fdbbdd0 - trans::base::trans_fn::hc26bd010ed3bb393zbu
  15:     0x7f7b1fdbc370 - trans::monomorphize::monomorphic_fn::hf644309b2715d241Tpd
  16:     0x7f7b1fe0e050 - trans::callee::trans_fn_ref_with_substs::h733d043b48c390a3Zxg
  17:     0x7f7b1fe0cb20 - trans::meth::trans_static_method_callee::h9cd746874bcc700fJdz
  18:     0x7f7b1fe38ca0 - trans::expr::trans_def_fn_unadjusted::h3abf69032d54d880Lfj
  19:     0x7f7b1fe30480 - trans::expr::trans_def::h982a9743604bd027RIi
  20:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  21:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  22:     0x7f7b1fde1f70 - trans::callee::trans_args::h865154588ccb314aQch
  23:     0x7f7b1fe13590 - trans::callee::trans_call_inner::h6471369785741005877
  24:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  25:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  26:     0x7f7b1fed5fb0 - trans::tvec::write_content::h7c6464728e4ccf64lIy
  27:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  28:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  29:     0x7f7b1feb82a0 - trans::_match::trans_match_inner::heb55d312caaeda0dPkx
  30:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  31:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  32:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  33:     0x7f7b1fe33770 - trans::expr::trans_addr_of::h957baa9beeb8dce62Kj
  34:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  35:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  36:     0x7f7b1fde1f70 - trans::callee::trans_args::h865154588ccb314aQch
  37:     0x7f7b1fe13590 - trans::callee::trans_call_inner::h6471369785741005877
  38:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  39:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  40:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  41:     0x7f7b1fde1f70 - trans::callee::trans_args::h865154588ccb314aQch
  42:     0x7f7b1fe14b50 - trans::callee::trans_call_inner::h6248557073704095185
  43:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  44:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  45:     0x7f7b1fdd07e0 - trans::controlflow::trans_block::h28afa8af906ef58bQ3d
  46:     0x7f7b1fe9ac80 - trans::base::trans_closure::h9a0d2c21a0e18266U0t
  47:     0x7f7b1fdbbdd0 - trans::base::trans_fn::hc26bd010ed3bb393zbu
  48:     0x7f7b1fdbc370 - trans::monomorphize::monomorphic_fn::hf644309b2715d241Tpd
  49:     0x7f7b1fe0e050 - trans::callee::trans_fn_ref_with_substs::h733d043b48c390a3Zxg
  50:     0x7f7b1fe0cb20 - trans::meth::trans_static_method_callee::h9cd746874bcc700fJdz
  51:     0x7f7b1fe38ca0 - trans::expr::trans_def_fn_unadjusted::h3abf69032d54d880Lfj
  52:     0x7f7b1fe30480 - trans::expr::trans_def::h982a9743604bd027RIi
  53:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  54:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  55:     0x7f7b1fde1f70 - trans::callee::trans_args::h865154588ccb314aQch
  56:     0x7f7b1fe13590 - trans::callee::trans_call_inner::h6471369785741005877
  57:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  58:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  59:     0x7f7b1fed5fb0 - trans::tvec::write_content::h7c6464728e4ccf64lIy
  60:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  61:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  62:     0x7f7b1feb82a0 - trans::_match::trans_match_inner::heb55d312caaeda0dPkx
  63:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  64:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  65:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  66:     0x7f7b1fe33770 - trans::expr::trans_addr_of::h957baa9beeb8dce62Kj
  67:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  68:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  69:     0x7f7b1fde1f70 - trans::callee::trans_args::h865154588ccb314aQch
  70:     0x7f7b1fe13590 - trans::callee::trans_call_inner::h6471369785741005877
  71:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  72:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  73:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  74:     0x7f7b1fde1f70 - trans::callee::trans_args::h865154588ccb314aQch
  75:     0x7f7b1fe13590 - trans::callee::trans_call_inner::h6471369785741005877
  76:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  77:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  78:     0x7f7b1fdd07e0 - trans::controlflow::trans_block::h28afa8af906ef58bQ3d
  79:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  80:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  81:     0x7f7b1feb82a0 - trans::_match::trans_match_inner::heb55d312caaeda0dPkx
  82:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  83:     0x7f7b1fdd01e0 - trans::expr::trans_into::h1a40b70708c7d89d3yh
  84:     0x7f7b1fdd07e0 - trans::controlflow::trans_block::h28afa8af906ef58bQ3d
  85:     0x7f7b1fe9ac80 - trans::base::trans_closure::h9a0d2c21a0e18266U0t
  86:     0x7f7b1fdbbdd0 - trans::base::trans_fn::hc26bd010ed3bb393zbu
  87:     0x7f7b1fdbc370 - trans::monomorphize::monomorphic_fn::hf644309b2715d241Tpd
  88:     0x7f7b1fe0e050 - trans::callee::trans_fn_ref_with_substs::h733d043b48c390a3Zxg
  89:     0x7f7b1fe0c740 - trans::callee::trans_fn_ref::hfa89809617f52948amg
  90:     0x7f7b1fde95d0 - trans::meth::trans_method_callee::h50e6d0b2d8541f96q8y
  91:     0x7f7b1fe14b50 - trans::callee::trans_call_inner::h6248557073704095185
  92:     0x7f7b1fe18570 - trans::expr::trans_rvalue_dps_unadjusted::hf623caa4d0aad547mTi
  93:     0x7f7b1fe17910 - trans::expr::trans_unadjusted::hb6ffa8ee55ffe7847ji
  94:     0x7f7b1fdd13d0 - trans::expr::trans::hde666e6a090eadc0xCh
  95:     0x7f7b1fdcf650 - trans::controlflow::trans_stmt_semi::hfd04efb01b8ef536Z2d
  96:     0x7f7b1fdd07e0 - trans::controlflow::trans_block::h28afa8af906ef58bQ3d
  97:     0x7f7b1fe9ac80 - trans::base::trans_closure::h9a0d2c21a0e18266U0t
  98:     0x7f7b1fdbbdd0 - trans::base::trans_fn::hc26bd010ed3bb393zbu
  99:     0x7f7b1fdb71f0 - trans::base::trans_item::h1e3916042030bab0Uyu
  100:     0x7f7b1fea1f20 - trans::base::trans_crate::h035c45eac4628807Buv
 ... <frames omitted>

Could not compile `speedtest`.

Caused by:
  Process didn't exit successfully: `rustc src/bin/speedtest.rs --crate-name speedtest --crate-type bin -g --out-dir /home/david/speedtest/target --emit=dep-info,link -L dependency=/home/david/speedtest/target -L dependency=/home/david/speedtest/target/deps --extern iron=/home/david/speedtest/target/deps/libiron-afb9726a49e90dd2.rlib --extern speedtest=/home/david/speedtest/target/libspeedtest-55fb5e30e4d68ad8.rlib -L native=/home/david/speedtest/target/build/time-7c7fc3eb0c12ad75/out` (status=101)

**Comment by DisruptiveMind** [comment] 2015-01-16 21:09
Someone had a similar issue with using Iron: #21200 and it references a fix in #21089

**Comment by tamird** [comment] 2015-04-21 23:11
looks like a dupe of #21200. @steveklabnik close?

**Closed** 2015-04-21 23:16 UTC
Labels: I-ICE
