### ISSUE TITLE
Simple macro makes rustc use all CPU/memory

### ISSUE THREAD

**Issue by ctz** [rust-lang/rust#36715] opened 2016-09-25 10:26 UTC
I was trying to write a macro which [accepts any arguments and compiles to nothing](https://www.reddit.com/r/rust/comments/53g86c/hey_rustaceans_got_an_easy_question_ask_here/d80keno).

My first try was:

```
macro_rules! warn ( ( $()* ) => () );

fn main() {
    warn!("This will never be printed!");
}
```

Experienced behaviour: rustc uses up all CPU and memory, then get killed by the kernel OOM killer.

Expected behaviour: either a program with no output, or an error explaining why this macro is invalid.

Versions:
```
$ rustc --version --verbose
rustc 1.11.0 (9b21dcd6a 2016-08-15)
binary: rustc
commit-hash: 9b21dcd6a89f38e8ceccb2ede8c9027cb409f6e3
commit-date: 2016-08-15
host: x86_64-unknown-linux-gnu
release: 1.11.0
```

**Comment by TimNN** [comment] 2016-09-25 11:13
Duplicate of #5067.

**Comment by TimNN** [comment] 2016-09-25 16:58
I'm going to close this, since it's a duplicate.

**Closed by TimNN** 2016-09-25 16:58 UTC
