### ISSUE TITLE
The EXE file compiled by rust cannot export related export functions

### ISSUE THREAD

**Issue by zofoc** [rust-lang/rust#99749] opened 2022-07-26 06:42 UTC
I encountered a problem with the rust compiler. In the bin program made by rust, I exported a function in the main unit, but I couldn't find the exported function with a third-party tool. I also use several other languages to do the same thing, and I can find the relevant exported functions. The function is simple in the following format:
#[no_mangle]
pub extern "C" fn func1(data:String)->i32{}  
My final question is, does our Rust compile exe files that cannot export related export functions? This is the only language I have found that exe files cannot export functions. Does trust add such functions

**Comment by nagisa** [comment] 2022-08-01 00:21
This is probably a duplicate of #84161

**Comment by zofoc** [comment] 2022-08-01 12:42
"This is a tracking issue for the RFC "2841" (https://github.com/rust-lang/rfcs/pull/2841).
The feature gate for the issue is #![feature(export_executable_symbols)]. "  and "Add the ability to export symbols from executables, not just dylibs, via a new compiler flag: -C export-executable-symbols"" , But none of them worked

**Comment by csmoe** [comment] 2022-11-18 04:22
Could you test your code with `rustc -Zexport-executable-symbols`? it's not stabilized yet, and `#![feature(export_executable_symbols)]` is unneeded.

**Comment by jyn514** [comment] 2023-04-12 14:44
I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/84161; feel free to reopen if you try -Zexport-executable-symbols and it doesn't fix your problem.

**Closed by jyn514** 2023-04-12 14:44 UTC
