### ISSUE TITLE
create_dir_all is not thread safe

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#38045] opened 2016-11-28 10:10 UTC
For concurrent requests to create the same directory using `create_dir_all` it is possible that the request fails with `Error { repr: Os { code: 17, message: "File exists" }` because a second thread already has created that directory. The problem is caused by `create_dir_all` [function](https://github.com/rust-lang/rust/blob/master/src/libstd/fs.rs#L1710-L1716) in `DirBuilder`.

I see three solution for this problem:
1. Document this behaviour
2. Make `create_dir_all`
3. Make `create_dir_all` ignoring this error?

Platform: Ubuntu 16.04 x86_64

**Comment by durka** [comment] 2016-11-28 15:22
Duplicate of #33707.

**Comment by alexcrichton** [comment] 2016-11-28 15:29
Indeed!

**Closed by alexcrichton** 2016-11-28 15:29 UTC
Labels: A-libs
