### ISSUE TITLE
rust 1.38.0 produces "error[E0495]" with link to non-existent doc fragment.

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [rust-lang/rust#66811] opened 2019-11-27 14:19 UTC
rustc version 1.38.00 can produce this error:

```
------- Target 'workspace' starting
   Compiling runtime v0.8.2 (/Users/andrew/workspace/flow/runtime)
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> runtime/manifest.rs:20:35
   |
20 |     let client_mutex = Mutex::new(client);
   |                                   ^^^^^^
   |
```

Where "error[E0495]" is a link to https://doc.rust-lang.org/error-index.html#E0495, but no such fragment as #E0495 exists in that doc and it just shows the start of the doc. Error 492 and 496 exist so maybe 495 was removed from the doc at some point.

**Comment by estebank** [comment] 2019-11-27 14:47
This is in the playground, right?

**Comment by andrewdavidmackenzie** [comment] 2019-11-27 17:28
No, local. rustc 1.38.00 installed with rustup.

**Comment by estebank** [comment] 2019-11-27 21:45
Closing as duplicate of https://github.com/rust-lang/rust/issues/61137, which has a list of all the currently undocumented error codes.

**Comment by Alexendoo** [comment] 2019-11-27 21:59
This does have a documented code, it just doesn't to be present on the index page

https://github.com/rust-lang/rust/blob/master/src/librustc_error_codes/error_codes/E0495.md

**Comment by andrewdavidmackenzie** [comment] 2019-11-28 08:39
Aha, good news (as I wouldn’t be able to write it :-) ) ... I can look at how that page is built and try and do a PR to fix this if you think that makes sense?

I can also check to see if any others are missing, although I imagine some maybe left out on purpose and hard for me to know?

**Comment by Alexendoo** [comment] 2019-11-28 14:22
It's generated using https://github.com/rust-lang/rust/tree/master/src/tools/error_index_generator

I ran it locally and the result does include the missing sections 👍

I'll ask around about getting the live site updated

**Comment by Alexendoo** [comment] 2019-11-28 15:04
Mark-Simulacrum let me know that the index is updated alongside stable rust releases

 `E0495` was just a little late to make it into the current stable release. For now you can see it on [the nightly index](https://doc.rust-lang.org/nightly/error-index.html#E0495)

As for the linking, it would be your editor/IDE that changes `error[E0495]` into an actual link if that is being done

**Closed by Alexendoo** 2019-11-28 15:04 UTC
