### ISSUE TITLE
Tuple struct associated constants can't be initialized with Self()

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#44846] opened 2017-09-25 18:55 UTC
There's an inconsistency when initializing tuple structs as associated constants with `Self`:
```
struct Foo(i32);

impl Foo {
const A: Self = Self(1); // Fails with "did you mean `Self { /* fields */ }`?"
const B: Self = Self { 0: 2 }; // succeeds
}
```

I'd expect `Self(1)` to work if `Self { 0: 2 }` works.

**Comment by jsgf** [comment] 2017-09-25 19:08
Actually, this looks like a general problem with `Self` and tuple types. This also doesn't work:
```
impl Foo {
    fn new(x: i32) -> Self {
        Self(x) // same failure
    }
}
```

**Comment by petrochenkov** [comment] 2017-09-25 20:09
Duplicate of https://github.com/rust-lang/rust/issues/42601 and maybe a couple of other closed issues.

This is not *supposed* to work and the fix is kinda on RFC territory, but given that it's requested regularly, I think it's reasonable to make this change and support `Self` in value namespace as a constructor alias.

**Comment by TimNN** [comment] 2017-09-27 04:54
Closing as duplicate.

**Closed by TimNN** 2017-09-27 04:54 UTC
