### ISSUE TITLE
rustdoc links to type aliases that don't exist in search results

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#83991] opened 2021-04-08 09:17 UTC
There are bad (404) links in search results with nightly rustdoc. E.g. go to https://doc.rust-lang.org/nightly/std/?search=as_raw_fd and then click the `std::RawFd::as_raw_fd` result. This leads to https://doc.rust-lang.org/nightly/std/type.RawFd.html#method.as_raw_fd which does not exist.

Cc @rust-lang/rustdoc

**Comment by RalfJung** [comment] 2021-04-08 09:17
Actually, this issue seems to exist even on stable -- somehow it went unnoticed for quite a while, it seems.

**Comment by GuillaumeGomez** [comment] 2021-04-08 09:19
I think it's because we are badly handling a reexport/type alias.

**Comment by jyn514** [comment] 2021-04-08 17:46
I think this is a duplicate of https://github.com/rust-lang/rust/issues/78724.

**Closed** 2022-05-11 08:47 UTC
Labels: T-rustdoc, A-rustdoc-search
