### ISSUE TITLE
Compiler panic: type &'static str has size 8 instead of 16

### ISSUE THREAD

**Issue by rwestlund** [rust-lang/rust#36236] opened 2016-09-03 04:01 UTC
The compiler panics when the following standalone code is built:
```rust
use std::str;
fn main () {
    const filename: &'static str = "myfile";
    format!("File {} not found.", &*filename);
}
```
Here's the output of `cargo build`:
```
   Compiling test v0.0.1 (file:///usr/home/randy/code/test)
src/main.rs:4:5: 4:45 warning: constant `filename` should have an upper case name such as `FILENAME`, #[warn(non_upper_case_globals)] on by default
src/main.rs:4     const filename: &'static str = "myfile";
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@const3845 = internal unnamed_addr constant %str_slice { i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str3844, i32 0, i32 0), i64 6 }, align 8
{ i8*, i64 } undef
error: internal compiler error: src/librustc_trans/consts.rs:443: const expr(38: &*filename) of type &'static str has size 8 instead of 16
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', src/libsyntax/errors/mod.rs:575
```
Both the lowercase constant and the curly braces in the string are necessary to reproduce the panic.

Rust version:
```
rustc 1.9.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-freebsd
release: 1.9.0
```

**Comment by TimNN** [comment] 2016-09-03 05:50
This is fixed on beta (and looks like a duplicate of #30386).

**Closed** 2016-09-13 19:27 UTC
Labels: I-ICE
