### ISSUE TITLE
Rustdoc should show associated types for an impl under "implementors"

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#21584] opened 2015-01-24 10:26 UTC
Currently rustdoc doesn't show associated types under the "implementors" portion of the trait page (eg [here](http://doc.rust-lang.org/std/ops/trait.Index.html)) (though it does show them [on the page for the type](http://doc.rust-lang.org/std/primitive.slice.html)). Since associated types are as important as type parameters when inspecting an impl (and debugging a type mismatch), perhaps rustdoc should show an `(Output = [T])` or something similar next to each impl?

In case of a cross crate impl where the trait shares a crate with the impl, the associated type will be missing from rustdoc altogether.

**Comment by frewsxcv** [comment] 2015-01-24 18:16
This is probably a duplicate of https://github.com/rust-lang/rust/issues/21092

**Closed** 2015-01-24 18:17 UTC
Labels: A-rustdoc
