### ISSUE TITLE
[ER] Propose the use of XX::MAX instead of -1 for unsigned integers

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#77416] opened 2020-10-01 17:23 UTC
Another of those little enhancement suggestions. This code:

```rust
fn main() {
    let x: u32 = -1;
}
```

With rustc 1.48.0-nightly gives this error message:

```rust
error[E0600]: cannot apply unary operator `-` to type `u32`
 --> ...\temp.rs:2:18
  |
2 |     let x: u32 = -1;
  |                  ^^ cannot apply unary operator `-`
  |
  = note: unsigned values cannot be negated
```

I suggest to modify the note, to suggest that u32::MAX may be desired instead, because in C code often you see people use -1 to get the max unsigned value.

**Comment by varkor** [comment] 2020-10-01 22:01
This is related to (or possibly a duplicate of) https://github.com/rust-lang/rust/issues/76413.

**Closed** 2020-10-09 06:15 UTC
Labels: A-diagnostics, A-suggestion-diagnostics, C-enhancement, T-compiler
