### ISSUE TITLE
error: internal compiler error: "inference variables in ..." on packed type

### ISSUE THREAD

**Issue by zao** [rust-lang/rust#61402] opened 2019-05-31 15:57 UTC
Given the following source code in both `release 1.35.0` and `1.36.0-nightly (e305df184 2019-04-24)`, I encounter an internal compiler error using nalgebra 0.18.0.

The code is probably not legal to begin with as I ran into it as I was moving from my own homebrewn math code to nalgebra. I have the impression that the compiler probably shouldn't ICE regardless of what junk you feed it, so I'm still reporting this.

```rust
use nalgebra::Vector3;

#[derive(Debug, Clone, Copy)]
#[repr(C, packed)]
struct Vertex {
    pos: Vector3<f32>,
    clr: Vector3<f32>,
}
```

Build output from `cargo +nightly build`:
```
   Compiling nalgebra v0.18.0
   Compiling nalgebra-repro v0.1.0 (F:\Temp\nalgebra-repro)
error: internal compiler error: inference variables in nalgebra::base::matrix::Matrix<f32, nalgebra::base::dimension::U3, nalgebra::base::dimension::U1, nalgebra::base::array_storage::ArrayStorage<_, _, _>>
 --> src\lib.rs:5:1
  |
5 | / struct Vertex {
6 | |     pos: Vector3<f32>,
7 | |     clr: Vector3<f32>,
8 | | }
  | |_^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src\librustc_errors\lib.rs:355:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (e305df184 2019-04-24) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `nalgebra-repro`.

To learn more, run the command again with --verbose.
```

I unfortunately do not have a newer nightly to test with due to the lack of a more recent RLS blocking the rustup attempt.

**Comment by HeroicKatora** [comment] 2019-06-02 02:34
Still encountering this in `rustc 1.37.0-nightly (03ee55bb1 2019-06-01)`.

Indepent of the issue, you can install specific compiler versions with necessary components [according to this matrix](https://rust-lang.github.io/rustup-components-history/) and [this installation process](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#for-installing-rust).

**Comment by pnkfelix** [comment] 2019-06-06 13:34
This ICE itself arises from this line:

https://github.com/rust-lang/rust/blob/51dc52b9fe432a87ebbd5347fb64c1d9edc06b3e/src/librustc_typeck/check/wfcheck.rs#L264

**Comment by pnkfelix** [comment] 2019-06-06 13:44
triage: P-high, assigning to self. Removing nomination.

**Comment by pnkfelix** [comment] 2019-06-11 12:40
Okay I've narrowed the test case down to a standalone file ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e2fecbffdb6691b1e4dcf7a5fc0f1fc2)):

```rust
#![allow(unused_imports, dead_code)]

pub struct U1;

pub trait ArrayLength {  }
impl ArrayLength for U1 { }

pub trait Trait { type Output; }
impl Trait for U1 { type Output = U1; }

pub trait DimName { type Value; }
impl DimName for U1 { type Value = U1; }

pub struct ArrayStorage<R>
where
    R: DimName,
    R::Value: Trait,
    <R::Value as Trait>::Output: ArrayLength,
{
    data: <R::Value as Trait>::Output,
}

pub struct DefaultAllocator;

pub trait Allocator<R = U1> { type Buffer; }
impl<R: DimName> Allocator<R> for DefaultAllocator
where
    R::Value: Trait,
    <R::Value as Trait>::Output: ArrayLength,
{
    type Buffer = ArrayStorage<R>;
}

#[repr(C, packed)]
struct Vertex {
    pos: <DefaultAllocator as Allocator>::Buffer
}

fn main() { println!("Hello, world!"); }
```

**Comment by pnkfelix** [comment] 2019-06-11 12:44
This is a stable-to-stable regression, injected between rust 1.23 and 1.24.

**Comment by pnkfelix** [comment] 2019-06-11 12:50
(the fact that the bug goes away if you take away the `packed` on `struct Vertex` leads me to hypothesize that the bug is caused by some internal layout code for checking the validity of that use of `packed`)

**Comment by pnkfelix** [comment] 2019-06-17 13:49
(Also, bisection on my mac has shown this was injected by PR #44884 )

**Closed** 2019-07-04 03:12 UTC
Labels: A-inference, C-bug, I-ICE, P-high, T-compiler, regression-from-stable-to-stable
