### ISSUE TITLE
rustdoc: private items get `broken_intra_doc_links` warning even when using `--document-private-items`

### ISSUE THREAD

**Issue by hikari-no-yume** [rust-lang/rust#115788] opened 2023-09-12 15:13 UTC
### Code

```Rust
/// Used by [bar::qux].
fn foo() {}

mod bar {
    fn qux() {
        super::foo();
    }
}
```

### Current output

```
warning: unresolved link to `bar::qux`
 --> foo.rs:1:14
  |
1 | /// Used by [bar::qux].
  |              ^^^^^^^^ no item named `qux` in module `bar`
  |
  = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: 1 warning emitted
```

In addition to the warning, the link shows up as unformatted text (including the square brackets) rather than as a hyperlink.

### Desired output

No warning, and a hyperlink in the resulting HTML rather than unlinked text.

### Rationale and extra context

It's surprising that the link is unresolved, considering that the item linked to has a valid path, and a documentation page has been generated for it! If I were to manually write out the path of the generated HTML file, the link would work.

### Anything else?

My project has this problem in [the current trunk revision](https://github.com/hikari-no-yume/touchHLE/tree/0bb9092a346ab91c3ea92c504a002c72d4e5df5c):

```
warning: unresolved link to `crate::frameworks::core_animation::composition`
   --> src/frameworks/core_graphics/cg_bitmap_context.rs:460:19
    |
460 | ...cut for [crate::frameworks::core_animation::composition]. This is a
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `composition` in module `core_animation`
    |
    = note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default

warning: unresolved link to `super::cg_image::CGImageGetDataProvider`
   --> src/frameworks/core_graphics/cg_data_provider.rs:115:25
    |
115 | /// This is for use by [super::cg_image::CGImageGetDataProvider].
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `CGImageGetDataProvider` in module `cg_image`

warning: unresolved link to `crate::environment::mutex`
 --> src/libc/pthread/mutex.rs:8:10
  |
8 | //! See [crate::environment::mutex] for the internal implementation.
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `mutex` in module `environment`

warning: `touchHLE` (lib doc) generated 3 warnings
```

The project is not a library, so all the documentation is there to help others understand the code. I set `--document-private-items` using `.cargo/config.toml`; if I didn't use that flag, the generated documentation would be useless. I make extensive use of intra-doc links to explain how different components fit together.

**Comment by fmease** [comment] 2023-09-25 17:22
Closing as duplicate of #83049.

**Closed** 2023-09-25 17:22 UTC
Labels: T-rustdoc, A-lint, C-bug, A-intra-doc-links
