### ISSUE TITLE
Using an undefined module provokes some unexpected errors from rustc (in addition to the expected unresolved import error)

### ISSUE THREAD

**Issue by mhintz** [rust-lang/rust#32511] opened 2016-03-26 16:56 UTC
Hey all,

Huge fan of Rust! Thanks for all the hard work.

I ran across this one today, thought I would report it:

`use`ing a module that doesn't exist not only causes an unresolved import error, but it seems like names which are part of the Rust prelude are also reported as being undefined. The expected behavior would be that I see *just* the unresolved import error. I came across this when copying a bunch of files to a new repo, got a ton of these errors filling my console, and spent a while trying to figure out if I had somehow shadowed or un-`use`d the rust prelude...

Here's a minimal example that reproduces it for me ('Option' and 'Some' are reported as undefined): https://gist.github.com/mhintz/c40749d774f2e88ad5c9

`rustc --version --verbose:
rustc 1.8.0-beta.2 (2879d940a 2016-03-22)
binary: rustc
commit-hash: 2879d940a16adeaccc1bff4ad0eeb14ad7c91b37
commit-date: 2016-03-22
host: x86_64-apple-darwin
release: 1.8.0-beta.2`

edit: added --verbose output

**Comment by petrochenkov** [comment] 2016-03-26 17:03
This is a duplicate of something recently fixed by @jseyfried, it works as expected on nightly: http://is.gd/onCcvC

**Closed** 2016-03-26 17:35 UTC

**Comment by mhintz** [comment] 2016-03-26 17:46
Whoops, thanks! I searched but didn't see  any other issues

Mark
