### ISSUE TITLE
lifetime bound when returning impl Trait is not considered

### ISSUE THREAD

**Issue by estaban** [rust-lang/rust#98719] opened 2022-06-30 15:00 UTC
Lifetimes bounds added to returned `impl Trait` does not seem to be considered by the compiler.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=02f184ddb3ce9d04c049c93c9d8b25b5

I would expect the above example to compile: `wrap` is defined to return a `'static` Future, so why is the compiler saying that it should have the same lifetime as `&self` ?

The issue does not manifest when returning a concrete type like `MapErr` or `BoxFuture<'static, Reply>`, 

@LucioFranco

**Comment by aliemjay** [comment] 2022-07-02 11:25
Duplicate of #42940.

@rustbot label A-impl-trait

**Comment by tamird** [comment] 2023-09-16 10:55
@aliemjay should this be closed as duplicate?

**Closed** 2023-09-16 11:11 UTC
Labels: T-compiler, A-impl-trait, C-bug
