### ISSUE TITLE
Glob Time Travel

### ISSUE THREAD

**Issue by vlad20012** [rust-lang/rust#74556] opened 2020-07-20 12:56 UTC
I tried this code:

```rust
mod foo {
    pub mod bar {
        pub mod bar {
            pub fn foobar() {}
        }
    }
}

use foo::*;
use bar::bar;
use bar::foobar;



fn main() {
    bar::foobar();
}
```

I expected to see this happen: **Compilation error**. This `use bar::bar;` shadows one (glob-imported) `bar` with another `bar`. As far as I know, this should be forbidden.

Instead, this happened: **this code successfully compiled**.

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (d7f945163 2020-07-19)
binary: rustc
commit-hash: d7f94516345a36ddfcd68cbdf1df835d356795c3
commit-date: 2020-07-19
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0
```

c.c. @matklad
c.c. @petrochenkov

**Comment by HeroicKatora** [comment] 2020-07-21 06:03
> This use bar::bar; shadows one (glob-imported) bar with another bar. As far as I know, this should be forbidden.

Shadowing a glob import with a specific item is allowed and will unambiguously resolve to the specific one. This is also how the prelude works. The following compiles fine as well:

```rust
// implicit: use std::prelude::v1::*; containing Vec
struct Vec;

fn a() -> Vec { unimplemented!() }
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f07892dbe0f69232e66779000be2aeb9).

**Comment by matklad** [comment] 2020-07-21 06:20
To clarify, the problem is not shadowing, but time travel. We shadow identifier *which have been already used to resolve another import*, so we end up with `bar` meaning two things at the same time in the same scope.

**Comment by petrochenkov** [comment] 2020-07-21 11:32
This is a change from Rust 1.44, in Rust 1.43 this is an ICE "inconsistent resolution for an import".
Possibly a consequence of https://github.com/rust-lang/rust/pull/70236.

**Comment by petrochenkov** [comment] 2020-07-21 11:42
cc https://github.com/rust-lang/rust/issues/62769 (somewhat related)

**Comment by vlad20012** [comment] 2020-07-21 12:31
I think, the difference with `use my_crate;` is that `use my_crate;` doesn't replace one resolution with another. We already have a name `my_crate` that is resolved to a particular extern crate.

In my example, `use bar::bar;` uses `bar` name from the scope, and then rebinds this `bar` name to another item.

I can complicate by example a bit.

```rust
mod foo {
    pub mod bar {
        pub mod bar {
            pub fn foobar() { println!("111") }
        }
        pub fn foobar() { println!("222") }
    }
}

use foo::*;
use bar::bar;
use bar::foobar;

fn main() {
    foobar();
}
```

What this program prints, "111" or "222"? It'd say, it depends on imports resolution order.

**Comment by petrochenkov** [comment] 2020-07-21 12:52
>It'd say, it depends on imports resolution order

The intent for the resolution results is to never depend on internal resolution order.
(cc https://github.com/rust-lang/rust/pull/53778#issuecomment-419224049, order-dependence can probably happen in practice due to the current not very principled implementation, but hopefully still can be eliminated in backward-compatible-in-practice way by rewriting the main resolution/expansion loop more carefully.)

>but looks like it always prints "111"

That's what I'd expect.
- `foobar` resolves to `use bar::foobar`
- `bar` in `bar::foobar` resolves to `use bar::bar` (because non-globs shadow globs)
- first `bar` in `bar::bar` resolves to `use foo::*` (which the only `bar` in scope after excluding `use bar::bar` itself)

**Comment by petrochenkov** [comment] 2020-07-21 12:57
I'd still be ok with replacing the former ICE with an error though, since that's a more conservative choice.

**Comment by petrochenkov** [comment] 2020-07-21 13:04
Actually enabling the property "name resolve to the same thing whether some items were excluded during its resolution to avoid cycles or not" may be useful for using something like "inference variables" for unresolved imports and making import resolution more like unification in type inference.

That's an idea I had for quite some, but I hadn't realized that merging https://github.com/rust-lang/rust/pull/70236 went against it.

**Comment by petrochenkov** [comment] 2020-09-30 20:13
Sigh, the issue already affects three stable releases - from 1.44 to 1.46.
I'll try to prioritize it.

**Comment by petrochenkov** [comment] 2020-10-01 18:33
Addressed in https://github.com/rust-lang/rust/pull/77421.

**Comment by camelid** [comment] 2020-10-02 00:23
Assigning `P-high` so this isn't lost. See the [relevant discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374556.20Glob.20Time.20Travel).

**Closed** 2020-10-03 00:41 UTC
Labels: A-resolve, C-bug, P-high, T-compiler, T-lang, regression-from-stable-to-stable

**Comment by petrochenkov** [comment] 2020-10-05 18:35
The fix caused some regressions - https://github.com/rust-lang/rust/issues/77586.

**Comment by vlad20012** [comment] 2023-03-10 21:24
@petrochenkov The code in the issue produce no errors using Rust 1.67.1. Should we re-open the issue or is it not considered a bug now?

**Comment by petrochenkov** [comment] 2023-03-10 23:07
@vlad20012 
The fix was reverted due to breakage (https://github.com/rust-lang/rust/pull/78784) and the current behavior is considered by design since then.

**Comment by petrochenkov** [comment] 2023-03-10 23:08
(Also it's not exactly a time travel - https://github.com/rust-lang/rust/issues/77586#issuecomment-719705437.)
