### ISSUE TITLE
Suggested imports pointing to/through non-`pub` use-statements in nested modules.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#77679] opened 2020-10-07 22:48 UTC
```rust

mod local {
    use std::*;
    use io::BufReader;
}

type T1 = BufReader;
type T2 = BufWriter;
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5d6e4263dddfdb1907ce665ab2964af7))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0412]: cannot find type `BufReader` in this scope
 --> src/lib.rs:7:11
  |
7 | type T1 = BufReader;
  |           ^^^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
2 | use crate::local::BufReader;
  |
2 | use futures::io::BufReader;
  |
2 | use futures_util::io::BufReader;
  |
2 | use std::io::BufReader;
  |
    and 1 other candidate

error[E0412]: cannot find type `BufWriter` in this scope
 --> src/lib.rs:8:11
  |
8 | type T2 = BufWriter;
  |           ^^^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
2 | use crate::local::io::BufWriter;
  |
2 | use futures::io::BufWriter;
  |
2 | use futures_util::io::BufWriter;
  |
2 | use std::io::BufWriter;
  |
    and 1 other candidate

warning: unused import: `io::BufReader`
 --> src/lib.rs:4:9
  |
4 |     use io::BufReader;
  |         ^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0412`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

At least, applying the suggestion gives a new error message about the `use` not being public. But it is IMO particularly bad that these tend to be the _first_ suggestion.

@rustbot modify labels: T-compiler, A-diagnostics, D-papercut, C-bug

**Comment by nagisa** [comment] 2020-10-10 18:52
Duplicate of #21934 / #50923

**Closed** 2020-10-10 18:52 UTC
Labels: A-diagnostics, C-bug, D-papercut, T-compiler
