### ISSUE TITLE
Detect git conflict markers and give a more helpful error

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#86976] opened 2021-07-08 14:36 UTC
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7e5e8f5be813f62db32e0ca490fae525

```rust
fn main() {
<<<<<<< HEAD
    println!("do some work");
||||||| constructed merge base
=======
    println!("hello world");
>>>>>>> hello world!
}
```

The current output is:

```
error: expected one of `!`, `(`, `+`, `::`, `<`, `>`, or `as`, found `println`
 --> src/main.rs:3:5
  |
2 | <<<<<<< HEAD
  |             - expected one of 7 possible tokens
3 |     println!("do some work");
  |     ^^^^^^^ unexpected token
```

Ideally the output should look like:

```
error: version control marker in file
 --> src/main.rs:2:1
  |
2 | <<<<<<< HEAD
  |  ^^^^^^^^^^^^^^^ version control marker
```

Clang does this quite nicely, it would be great to match it:

```
    In file included from /.../api/http.c++:1:
    In file included from /.../api/http.h:6:
    In file included from /.../api/basics.h:6:
    /.../scheduling/request-context.h:775:1: error: version control conflict marker in file
```

Meta: tested with 1.55.0-nightly (2021-07-07 d2b04f075c0ce010758c).

**Comment by jonas-schievink** [comment] 2021-07-08 14:41
Duplicate of https://github.com/rust-lang/rust/issues/32059

**Closed by jonas-schievink** 2021-07-08 14:41 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
