### ISSUE TITLE
Regression in the behavior of `file!()` when using workspaces

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#47462] opened 2018-01-15 17:57 UTC
I'm not sure if this is a Rust issue or a Cargo issue, but since it manifests using `file!()` I figured I'd raise it here. I'm not sure when the actual regression occurred, as it was previously masked in our build by #47139.

The change we're seeing is that `file!()` is now returning a path relative to the root of the workspace, rather than the root of the project. This specifically breaks our tests which have code like:

```
let path = Path::new(file!())
    .parent()
    .unwrap()
    .join("other_stuff.txt");
File::open(&path).read_to_string(&mut s).unwrap();
```

**Comment by Mark-Simulacrum** [comment] 2018-01-15 18:06
cc @alexcrichton

**Comment by sgrif** [comment] 2018-01-15 18:07
I suspect this is a regression from stable to beta, but I will double check.

**Comment by sgrif** [comment] 2018-01-15 18:08
This is a regression from stable to beta.

**Comment by sgrif** [comment] 2018-01-15 18:11
To reproduce:

Cargo.toml:

```
[workspace]
members = ["bar"]
```

`cargo new bar`

bar/tests/foo.rs:

```
#[test]
fn test_stuff() {
    assert_eq!("tests/foo.rs", file!());
}
```

**Comment by alexcrichton** [comment] 2018-01-16 05:39
Yes this is an intentional (yet unfortunate) change on behalf of https://github.com/rust-lang/cargo/pull/4788. This has caused a fair bit of unintended breakage, although it's not clear to me whether we should back it out or not regardless (it's fixing a longstanding bug and an underlying reproducibility bug in Cargo).

@sgrif is it possible to update the usage of `file!()` and such or avoid it entirely?

**Comment by sgrif** [comment] 2018-01-16 16:12
Sure, I could hard code the paths. I think that it's a completely reasonable expectation that `File::open(file!())` opens the current file, though.

**Comment by alexcrichton** [comment] 2018-01-16 16:18
@sgrif just to make sure you understand the ramifications of the existing bug:

* In [this example](https://github.com/rust-lang/rust/issues/47462#issuecomment-357754678) `cargo test -p bar` from the workspace root fails.
* You get behavior like this:

  ```
  cd bar
  cargo test # passes
  cd ..
  cargo test # passes 
  rm -rf target
  cargo test # fails
  ```

* `File::open(file!())` *only* opens the current file if executed from the same cwd, otherwise it fails.

Relying on `file!()` (because it's relative) is *very* brittle in general.

**Comment by Mark-Simulacrum** [comment] 2018-01-31 17:52
@alexcrichton So am I correct that we expect to take no further action on this issue?

**Comment by alexcrichton** [comment] 2018-01-31 18:28
@Mark-Simulacrum that is my personal preference, yes. IIRC @rust-lang/cargo discussed this issue in a broader sense but we didn't reach a conclusion.

**Comment by alexcrichton** [comment] 2018-03-15 18:38
1.24 has shipped and I don't think this'll get reverted, so closing

**Closed by alexcrichton** 2018-03-15 18:38 UTC
Labels: C-bug, regression-from-stable-to-stable, relnotes
