### ISSUE TITLE
rustc panic with manual Fn implementation

### ISSUE THREAD

**Issue by sizeak** [rust-lang/rust#39163] opened 2017-01-18 21:11 UTC
I was attempting to implement Fn manually, possibly incorrectly!

I tried this code:
Playground URL: https://play.rust-lang.org/?gist=0c4c814bd6fe031a33f6673c27de9239&version=nightly&backtrace=0
Gist URL: https://gist.github.com/0c4c814bd6fe031a33f6673c27de9239

## Meta
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/abi.rs:374: argument to function with "rust-call" ABI is not a tuple

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by durka** [comment] 2017-01-18 21:24
It is incorrect, you need to use a tuple: https://is.gd/0lhHva

That said it should not ICE.

**Comment by sizeak** [comment] 2017-01-18 21:30
Yes I have since added the tuples. I've also found that this is probably a duplicate of #21139 and #22565.

**Comment by durka** [comment] 2017-01-18 22:05
Yes, dupe of #22565.

**Comment by Mark-Simulacrum** [comment] 2017-05-20 01:22
Closing in favor of #22565.

**Closed by Mark-Simulacrum** 2017-05-20 01:22 UTC
Labels: I-ICE
