### ISSUE TITLE
Documentation of collections::string::String and std::string::String is off.

### ISSUE THREAD

**Issue by contradictioned** [rust-lang/rust#27051] opened 2015-07-15 08:07 UTC
I noted that the documentation for `collections::string::String` and `std::string::String` is a little off. In _the_ IRC channel was said that this could be a serialization bug, so I'm reporting this here now.

The differences are that in `collections::string::String` there are lifetime parameters specified which are not in `std::string::String`, e.g. this from https://doc.rust-lang.org/collections/string/struct.String.html

    fn from_utf8_lossy<'a>(v: &'a [u8]) -> Cow<'a, str>

vs. this from https://doc.rust-lang.org/std/string/struct.String.html

    fn from_utf8_lossy(v: &'a [u8]) -> Cow<'a, str>

Here's a diff: http://pastie.org/10293533 (based on a HTML to text conversion of the two doc pages)

**Comment by alexcrichton** [comment] 2015-08-13 20:24
Closing as a dupe of #14462

**Closed by alexcrichton** 2015-08-13 20:24 UTC
Labels: A-rustdoc
