### ISSUE TITLE
ICE with ref pattern on integers

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#33499] opened 2016-05-08 17:39 UTC
```rust
fn main() {
    let x = (0,2);
    match x {
        (0, ref y) => { /* use y */}
        (y, 0) => { /* use y */ }
        _ => ()
    }
}
```

[playpen](http://is.gd/To9W0x)

This causes an ICE at `error: internal compiler error: ../src/librustc_trans/_match.rs:944: only string and byte strings supported in compare_values` on stable, beta, and nightly.

It goes away if you swap the match arms.

**Comment by jonas-schievink** [comment] 2016-05-08 17:41
Duplicate of #33498

**Closed** 2016-05-08 17:44 UTC
Labels: I-ICE
