### ISSUE TITLE
Can't `impl const From<T> for U` anymore

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/rust#111275] opened 2023-05-06 03:30 UTC
I tried this code:

```rust
#![feature(const_trait_impl)]
struct S;

impl const From<()> for S {
    fn from(value: ()) -> Self {
        Self
    }
}
```

I expected to see this happen: Code must compile

Instead, this happened:

Code doesn't compile in latest Nightly `rustc 1.71.0-nightly (f9a6b7158 2023-05-05)`, but worked fine (with corresponding features enabled) in `rustc 1.70.0-nightly (0599b6b93 2023-04-01)`

```
error: const `impl` for trait `From` which is not marked with `#[const_trait]`
 --> src/lib.rs:4:12
  |
4 | impl const From<()> for S {
  |            ^^^^^^^^
  |
  = note: marking a trait with `#[const_trait]` ensures all default method bodies are `const`
  = note: adding a non-const method body in the future would be a breaking change
```

Error message is also confusing to me because `From` does have `#[const_trait]` attribute and various types in standard library have const implementation, like `impl const From<u8> for usize`.

Does this mean it is no longer possible to have const implementations in user code?

### Meta

`rustc --version --verbose`:
```
rustc 1.71.0-nightly (f9a6b7158 2023-05-05)
```

**Comment by nazar-pc** [comment] 2023-05-06 03:47
Hm... looks like it is gone from latest nightly. I was using it with const generics alongside with `Ord` to determine size of arrays in a generic way.

**Comment by CraftSpider** [comment] 2023-05-06 04:28
I believe the types / const team is ripping out the current implementation of const traits entirely, pending a rework of implementation and possibly syntax. So this isn't a bug, simply a side effect of using an (I believe incomplete, so particularly likely to change) nightly feature.

**Comment by nazar-pc** [comment] 2023-05-06 04:30
Yes, it was an incomplete nightly feature indeed. It is a bit unfortunate though that it is going away. Do you happen to have a link about this discussion (not the generic tracking issue, there is not many updates there)?

**Comment by SkiFire13** [comment] 2023-05-06 12:39
https://github.com/rust-lang/rust/pull/110393 is the PR that removed them.

**Comment by Nilstrieb** [comment] 2023-05-06 13:00
See the tracking issue for work on const traits. Closing it as it's not a bug.

**Closed by Nilstrieb** 2023-05-06 13:00 UTC
Labels: C-bug
