### ISSUE TITLE
MSVC linker output is not UTF-8 if the VC is localized version.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#53382] opened 2018-08-15 10:41 UTC
It's giving escaped UTF-8 output if a linker error happens. Very hard to read.

It would be much better if it can detect the actual VS version and transcode those output.

**Comment by retep998** [comment] 2018-08-16 00:27
Duplicate of https://github.com/rust-lang/rust/issues/35785

**Closed by retep998** 2018-08-16 00:27 UTC
Labels: O-windows-msvc
