### ISSUE TITLE
Path does not properly split windows path when running on non-windows Os

### ISSUE THREAD

**Issue by kaifastromai** [rust-lang/rust#103589] opened 2022-10-26 17:56 UTC
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
    let p=std::path::Path::new("test1\\test2\\test3");
    
    println!("{:?}",p.components().last())
}
```

The result I would expect should be "test3", but it instead returns the entire path item. An example can be seen on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=933d57160e1f242b129ad04db8636b34)

### Meta

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (bed4ad65b 2022-10-25)
binary: rustc
commit-hash: bed4ad65bf7a1cef39e3d66b3670189581b3b073
commit-date: 2022-10-25
host: aarch64-apple-darwin
release: 1.66.0-nightly
LLVM version: 15.0.2
```

**Comment by the8472** [comment] 2022-10-26 19:18
The behavior of the `std::path` module is platform-dependent. On unix inputs are treated as unix-paths, on windows as windows-paths. So this is expected behavior.

**Comment by the8472** [comment] 2022-10-26 19:20
#66621 proposes a potential solution, so I'm closing this as a dupe of that.

**Closed by the8472** 2022-10-26 19:20 UTC
Labels: C-bug
