### ISSUE TITLE
Compile regression "cannot infer an appropriate lifetime for lifetime parameter"

### ISSUE THREAD

**Issue by gz** [rust-lang/rust#70917] opened 2020-04-08 02:55 UTC
On linux, the following works:
```
git clone https://github.com/AltSysrq/proptest.git
cd proptest
rustup update nightly-2020-04-06
rustup default nightly-2020-04-06
source ~/.cargo/env
rustc --version
cargo build
```
(rustc version is rustc 1.44.0-nightly (b543afca9 2020-04-05))

The following does not work:
```
rustup update nightly
rustup default nightly
source ~/.cargo/env
rustc --version
cargo build
```

Build fails with:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
  --> proptest/src/arbitrary/_core/iter.rs:47:23
   |
47 |         base.prop_map(Iterator::cloned).boxed()
   |                       ^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime `'a` as defined on the impl at 36:9...
```
(rustc version is: rustc 1.44.0-nightly (42abbd887 2020-04-07))

**Comment by Centril** [comment] 2020-04-08 03:40
Reproducer (working on shrinking it):
```rust
fn main() {}

use std::fmt;
use std::iter::Cloned;
use std::sync::Arc;

pub trait ValueTree {
    type Value: fmt::Debug;
}

pub trait Strategy: fmt::Debug {
    type Tree: ValueTree<Value = Self::Value>;
    type Value: fmt::Debug;

    fn prop_map<O: fmt::Debug, F: Fn(Self::Value) -> O>(
        self,
        fun: F,
    ) -> Map<Self, F>
    where
        Self: Sized,
    {
        loop {}
    }

    fn boxed(self) -> BoxedStrategy<Self::Value>
    where
        Self: Sized + 'static,
    {
        loop {}
    }
}


pub struct Map<S, F> {
    source: S,
    fun: Arc<F>,
}

impl<S: fmt::Debug, F> fmt::Debug for Map<S, F> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        loop {}
    }
}


impl<S: ValueTree, O: fmt::Debug, F: Fn(S::Value) -> O> ValueTree
    for Map<S, F>
{
    type Value = O;
}

impl<S: Strategy, O: fmt::Debug, F: Fn(S::Value) -> O> Strategy for Map<S, F> {
    type Tree = Map<S::Tree, F>;
    type Value = O;
}




macro_rules! proxy_strategy {
    ($typ:ty $(, $lt:tt)*) => {
        impl<$($lt,)* S : Strategy + ?Sized> Strategy for $typ {
            type Tree = S::Tree;
            type Value = S::Value;
        }
    };
}
proxy_strategy!(Box<S>);
proxy_strategy!(&'a S, 'a);
proxy_strategy!(&'a mut S, 'a);
proxy_strategy!(Arc<S>);

impl<T: ValueTree + ?Sized> ValueTree for Box<T> {
    type Value = T::Value;
}




type BoxedVT<T> = Box<dyn ValueTree<Value = T>>;

#[derive(Debug)]
pub struct BoxedStrategy<T>(Arc<dyn Strategy<Value = T, Tree = BoxedVT<T>>>);

impl<T> Clone for BoxedStrategy<T> {
    fn clone(&self) -> Self {
        BoxedStrategy(Arc::clone(&self.0))
    }
}

impl<T: fmt::Debug> Strategy for BoxedStrategy<T> {
    type Tree = BoxedVT<T>;
    type Value = T;
}

pub trait ArbitraryF1<A: fmt::Debug>: fmt::Debug + Sized {
    type Parameters: Default;

    fn lift1<AS>(base: AS) -> BoxedStrategy<Self>
    where
        AS: Strategy<Value = A> + 'static,
    {
        Self::lift1_with(base, Self::Parameters::default())
    }

    fn lift1_with<AS>(base: AS, args: Self::Parameters) -> BoxedStrategy<Self>
    where
        AS: Strategy<Value = A> + 'static;
}

impl<
        'a,
        T: 'static + Clone,
        A: fmt::Debug + 'static + Iterator<Item = &'a T>,
    > ArbitraryF1<A> for Cloned<A>
{
    type Parameters = ();

    fn lift1_with<S>(base: S, _args: Self::Parameters) -> BoxedStrategy<Self>
    where
        S: Strategy<Value = A> + 'static,
    {
        base.prop_map(Iterator::cloned).boxed()
    }
}
```

**Comment by Centril** [comment] 2020-04-08 15:46
```
cargo-bisect-rustc \
    --test-dir=proptest-regression \
    --end=42abbd8878d3b67238f3611b0587c704ba94f39c \
    --start=f6fe99c798cb65280a9a56f442b371adcb7b8aa2
````
reports that the regression happened in https://github.com/rust-lang/rust/commit/209b2be09fcaff937480d1fbbe8b31646e361c7a, i.e. https://github.com/rust-lang/rust/pull/70164. cc @eddyb

**Comment by eddyb** [comment] 2020-04-08 16:28
Reduced ([playground/stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b2ee3845061638d756ae082932ebea2e) -> [playground/nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b2ee3845061638d756ae082932ebea2e)):
```rust
fn assert_static<T: 'static>(_: T) {}

fn capture_type<T>() {}
fn capture_lifetime<'a: 'a>() {}

// Errors on stable & nightly.
fn test_type<'a>() {
    assert_static(capture_type::<&'a ()>);
}

// Errors *only* on nightly.
fn test_lifetime<'a>() {
    assert_static(capture_lifetime::<'a>);
}
```

@nikomatsakis Are we supposed to ignore *only* lifetime parameters in `ty::FnDef`s? If the argument is that the only thing you can do with a `ty::FnDef` is call it, why aren't *all* generics ignored?

cc @rust-lang/lang @matthewjasper

**Comment by eddyb** [comment] 2020-04-08 16:29
I should say, I didn't expect to fix a lifetime vs type inconsistency, the goal was to fix type vs const inconsistencies. Somehow we have a behavior with no tests, I'm not sure how intentional it was.

**Comment by Centril** [comment] 2020-04-08 16:31
(I'm perfectly happy to issue a point release, 0.9.6, to proptest btw if we decide the new compiler behavior is correct and proptest is in the wrong.)

**Comment by spastorino** [comment] 2020-04-08 19:14
Assigning `P-high` and leaving nomination. This was [discussed as part of pre-triage meeting in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/pre-meeting.20triage.202020-04-09.20.2354818/near/193365343).

**Comment by spastorino** [comment] 2020-04-08 19:43
As discussed in the meeting this is nominated for `T-lang`

**Comment by nikomatsakis** [comment] 2020-04-09 18:59
Let me leave a brief comment explaining what is going on, because it took me a bit to figure out what @eddyb was talking about.

The type in question is one of the "anonymous types" that we construct for functions. You can think of these types as being roughly `F<...>`, where `F` is the name of the function and `...` are the generic types from the function definition. In [this case](https://github.com/rust-lang/rust/issues/70917), the type would be something like `capture_lifetime<'a>`.

We are processing a constraint like `capture_lifetime<'a>: 'static`. The ordinary "outlives" rules for such types require that each component be `'static`, so in this case it would require that `'a: 'static`, which is not known to be true. These rules were defined in [RFC 1214](https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html).

I'm not sure why the old code seemingly ignored this requirement. It seems like a bug to me though, a kind of artifact of the structure of the code that @eddyb fixed "in passing" by making the code operate more uniformly.

**Comment by Centril** [comment] 2020-04-10 10:24
Notes from the language team meeting yesterday:
- We believe @eddyb's changes to be a fix, and not a bug.
- We try to assess the impact using crater (not sure how you do that -- @Mark-Simulacrum maybe you can help?)
- It seems to have broken proptest (I mistakenly suggested it broke structopt; it has not), but I am the maintainer of that crate so I am happy to publish a point release (I'll try to do so today).
- We could add a special case to have a warning period or accept this indefinitely (*Speaking personally*, I would prefer the former.)
- Niko does not believe the previous behavior is unsound, but interactions with `typeof(...)` could perhaps change that.

**Comment by Mark-Simulacrum** [comment] 2020-04-10 12:03
@craterbot run start=master#bf1f2eedda4fa02b7c9347dd849ed73ddd43dedc end=master#209b2be09fcaff937480d1fbbe8b31646e361c7a mode=check-only

**Comment by pnkfelix** [comment] 2020-04-10 16:26
Touched on briefly at the [ad hoc triage meeting](https://zulip-archive.rust-lang.org/131828tcompiler/35095adhoctriagemeeting2020041054818.html#193575463) today. But since we are awaiting crater results, there is nothing for us to discuss at the moment.

Leaving nominated for discussion at next week's triage meeting (or hopefully sooner, async), since by then the crater results should be available.

**Comment by Centril** [comment] 2020-04-11 20:45
I've gone ahead and released [proptest 0.9.6](https://crates.io/crates/proptest/0.9.6) which has a fix for the problem here.

**Comment by lqd** [comment] 2020-04-14 10:15
All these depend on `proptest`, except:
- [`zenroom_minimal-0.1.0`](https://crater-reports.s3.amazonaws.com/pr-70917/master%23209b2be09fcaff937480d1fbbe8b31646e361c7a/reg/zenroom_minimal-0.1.0/log.txt)
- [`luster`](https://crater-reports.s3.amazonaws.com/pr-70917/master%23209b2be09fcaff937480d1fbbe8b31646e361c7a/gh/kyren.luster/log.txt) 
- [`clint`](https://crater-reports.s3.amazonaws.com/pr-70917/master%23209b2be09fcaff937480d1fbbe8b31646e361c7a/gh/bjc.clint/log.txt)
- ([`xtp`](https://crater-reports.s3.amazonaws.com/pr-70917/master%23209b2be09fcaff937480d1fbbe8b31646e361c7a/reg/xtp-0.1.0-alpha.4/log.txt) is marked as a regressions but looks like a spurious issue maybe in crater)

**Comment by nikomatsakis** [comment] 2020-04-14 13:48
But oof, that's a lot of regressions. Looking at `zenroom_minimal` and `luster`, both issues seem to be related to lua. Not sure about clint.

**Comment by eddyb** [comment] 2020-04-14 17:23
We should probably allow this, since it's sound (AFAIK). If nothing else, we should be more intentional about a breaking change.

**Comment by nikomatsakis** [comment] 2020-04-15 13:53
I'm thinking similarly. To recap what I said in the meeting, we *could* allow this -- it might even be something we want to consider generalizing to other types.

I think we could adjust [RFC 1214] to be more permissive, and it would be useful in some cases.

**Comment by spastorino** [comment] 2020-04-15 18:18
Removed nomination as per [pre-triage discussions](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/pre-meeting.20triage.202020-04-16.20.2354818/near/194205565). This was already discussed on last compiler meeting and we'll probably again tomorrow because it's an unassigned regression.

**Comment by eddyb** [comment] 2020-04-16 19:13
Found where I introduced the breaking change: these were using `push_regions`:
* https://github.com/rust-lang/rust/blob/0d4705b0097a132cbb721095997d91090e8cdb21/src/librustc_middle/ty/outlives.rs#L175-L177
* https://github.com/rust-lang/rust/blob/0d4705b0097a132cbb721095997d91090e8cdb21/src/librustc_infer/infer/outlives/verify.rs#L155-L157

And `push_regions` was ignoring `ty::FnDef`'s substs: https://github.com/rust-lang/rust/commit/26199f0cbc947a09d21044aacaa1ae12af465e65#diff-4cbc928241996c3226a17d1a924c6ebaL2174.

Doesn't even look like the behavior was intentional, but at least now I know where to restore it (however it is annoying that this code is duplicated...).

**Comment by nikomatsakis** [comment] 2020-04-16 21:18
@eddyb yeah, I expected to see some code like that -- I agree the behavior was not *intentional*.

**Closed** 2020-04-18 17:41 UTC
Labels: A-borrow-checker, A-inference, A-lifetimes, P-critical, S-waiting-on-review, T-compiler, regression-from-stable-to-nightly
