### ISSUE TITLE
Type mismatch with "default impl"

### ISSUE THREAD

**Issue by josephlr** [rust-lang/rust#56493] opened 2018-12-04 08:17 UTC
The following code [currently works](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=631924319134ef31b2924c5b04bb76ab) on stable rust
```rust
use std::str::FromStr;

trait FromString: Sized {
    type Err;
    fn from_string(s: String) -> Result<Self, Self::Err>;
}

impl<T: FromStr> FromString for T {
    type Err = <T as FromStr>::Err;
    fn from_string(s: String) -> Result<Self, Self::Err> {
        s.parse()
    }
}
```

However, when using the [specialization feature](https://github.com/rust-lang/rust/issues/31844) and turning the trait `impl` into a `default impl`:
```rust
#![feature(specialization)]
use std::str::FromStr;

trait FromString: Sized {
    type Err;
    fn from_string(s: String) -> Result<Self, Self::Err>;
}

default impl<T: FromStr> FromString for T {
    type Err = <T as FromStr>::Err;
    fn from_string(s: String) -> Result<Self, Self::Err> {
        s.parse()
    }
}
```

The above code [stops working](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6069b9f0967cab2a78795550c789a313), erroring with:
```
type mismatch resolving `<T as std::str::FromStr>::Err == <T as FromString>::Err`
```

It would seem that the compiler cannot properly deduce equality between types when using `default impl`. Tested on `rustc 1.32.0-nightly (0c999ed13 2018-12-03)`

**Comment by jonas-schievink** [comment] 2019-09-15 19:48
I think this is intentional. The `default impl` means that both `Err` and `from_string` are specializable further, so the impl must not assume that `Err` has a concrete type. Moving the `default` to the `fn from_string` makes it compile by fixing `Err` to a concrete type.

Closing as working as intended.

**Closed by jonas-schievink** 2019-09-15 19:48 UTC
Labels: A-associated-items, A-specialization, A-typesystem, F-specialization
