### ISSUE TITLE
LLVM assertion when compiling a program that has `#[no_mangle]` on `main`

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#24105] opened 2015-04-06 07:20 UTC
Test case:
```rust
#[no_mangle]
fn main() {}
```
Output:
```
nom.rs:2:1: 2:13 warning: function main is marked #[no_mangle], but not exported, #[warn(private_no_mangle_fns)] on by default
nom.rs:2 fn main() {}
         ^~~~~~~~~~~~
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Aborted
```

**Comment by jdm** [comment] 2015-04-06 13:32
Duplicate of #19495.

**Closed by jdm** 2015-04-06 13:32 UTC
Labels: I-crash, I-ICE
