### ISSUE TITLE
Weird behavior when comparing function pointers

### ISSUE THREAD

**Issue by VictorKoenders** [rust-lang/rust#54695] opened 2018-09-30 13:59 UTC
As per the discussion on [twitter ](https://twitter.com/eddyb_r/status/1046398239950417921)

This piece of code in release mode has weird behavior when comparing 2 pointers twice. This behavior happens only in release mode and does appear on stable.

It looks like a LLVM optimization to me, @eddyb thinks it "*might* be an accidental optimization"

```rust
fn foo(_: i32) -> i32 {
    1
}
fn bar(_: i32) -> i32 {
    1
}

fn main() {
    let x: fn(i32) -> i32 = foo;
    let y: fn(i32) -> i32 = bar;
    
    if x == y {
        println!("true")
    } else {
        println!("false {:?}", x);
    }

    if x == y {
        println!("true")
    } else {
        println!("false {:?}", x);
    }
}

```
```
false 0x55eabbd342f0
true
```
[play.rust-lang.org link](https://play.rust-lang.org/?gist=51ec7b4d5775936cc5aa79366ece0e63&version=stable&mode=release&edition=2015)

**Comment by sfackler** [comment] 2018-09-30 14:03
Duplicate of #54685.

**Closed by sfackler** 2018-09-30 14:03 UTC
