### ISSUE TITLE
`faster` fails to migrate 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51211] opened 2018-05-30 09:27 UTC
@AdamNiederer [helpfully reported](https://github.com/rust-lang/rust/issues/51180#issuecomment-393063375) that `faster` fails to migrate successfully:

Failing: https://github.com/AdamNiederer/faster/commits/rust-2018-migration

```
$ cargo build
   Compiling faster v0.4.3
error[E0463]: can't find crate for `core_or_std`
  --> src/intrin/eq.rs:58:25
   |
58 |                       use core_or_std::mem::transmute;
   |                           ^^^^^^^^^^^ can't find crate
...
79 | / rust_fallback_eq! {
80 | |     impl Eq for u8x16 where "sse2" {
81 | |         eq_mask, eq => u8x16, u8, _mm_cmpeq_epi8(), [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];
82 | |     }
83 | | }
   | |_- in this macro invocation

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `faster`.

To learn more, run the command again with --verbose.
```

They write:

> It looks like `cargo fix` isn't applying a `crate::` prefix to my custom core/std module in a few cases. Manually fixing the imports fixes the build. It looks like `cargo fix` makes no attempt to fix imports in test modules, so the tests are still broken.

**Comment by Mark-Simulacrum** [comment] 2018-06-07 16:51
Possibly a case of https://github.com/rust-lang/rust/issues/48704.

**Comment by alexcrichton** [comment] 2018-07-16 17:48
I've minimized this to the following:

```rust
#![feature(rust_2018_preview)]
#![warn(rust_2018_compatibility)]

macro_rules! foo {
    () => {
        {
            use myself::f;
            f();
        }
    }
}

mod myself {
    pub fn f() {}
}

fn main() {
    foo!();
    foo!();
}
```

which yields:

```
warning: absolute paths must start with `self`, `super`, `crate`, or an external crate name in the 2018 edition
  --> foo.rs:7:17
   |
7  |             use myself::f;
   |                 ^^^^^^^^^ help: use `crate`: `crate::myself::f`
...
18 |     foo!();
   |     ------- in this macro invocation
   |
note: lint level defined here
  --> foo.rs:2:9
   |
2  | #![warn(rust_2018_compatibility)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   = note: #[warn(absolute_paths_not_starting_with_crate)] implied by #[warn(rust_2018_compatibility)]
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
   = note: for more information, see issue TBD

warning: absolute paths must start with `self`, `super`, `crate`, or an external crate name in the 2018 edition
  --> foo.rs:7:17
   |
7  |             use myself::f;
   |                 ^^^^^^^^^ help: use `crate`: `crate::myself::f`
...
19 |     foo!();
   |     ------- in this macro invocation
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
   = note: for more information, see issue TBD
```

It's unclear to me whether this falls under the purview of https://github.com/rust-lang/rust/issues/48704 or rustfix. The problem is that two duplicate suggestions are made and rustfix yields an error on this because it looks suspicious. I'm gonna send a fix to rustfix in the meantime as I've tested locally that it works and should at least help improve the situation.

**Comment by alexcrichton** [comment] 2018-07-16 17:49
I've attempted a fix for this in rustfix with https://github.com/rust-lang-nursery/rustfix/pull/131 which fixes this exact issue, and at least successfully got the `faster` crate to migrate!

**Comment by alexcrichton** [comment] 2018-07-16 17:51
Actually, closing this in favor of https://github.com/rust-lang/rust/issues/51205 as testing has shown that issue is the only thing that blocks `faster`

**Closed by alexcrichton** 2018-07-16 17:51 UTC
Labels: A-edition-2018-lints, A-rust-2018-preview, T-compiler, WG-epoch
