### ISSUE TITLE
Accessing union field inside unsafe function requires extra unsafe block

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#53193] opened 2018-08-08 12:46 UTC
[Playground](https://play.rust-lang.org/?gist=19b7580df577b46e00160d864ddbdc50&version=nightly&mode=debug&edition=2015)

Is this by design?

```rust
pub unsafe fn foo() -> u8 {
    union U {
        v: u8,
        c: u8,
    }
    // const C: u8 = unsafe { U { v: 0 }.c }; // OK
    const C: u8 = U { v: 0 }.c; // ERROR
    C
}
```

it produces:

```
error[E0133]: access to union field is unsafe and requires unsafe function or block
 --> src/main.rs:9:19
  |
9 |     const C: u8 = U { v: 0 }.c;
  |                   ^^^^^^^^^^^^ access to union field
  |
  = note: the field may not be properly initialized: using uninitialized data will cause undefined behavior
```

Wrapping the access in an `unsafe` block compiles, but since the function is already `unsafe`, that feels a bit redundant. 

In non-`unsafe` functions one doesn't need to open two unsafe blocks to perform union field access `unsafe { unsafe { ...union access... } }` :D Is this doubly-unsafe ? :D 

cc @oli-obk @RalfJung @eddyb

**Comment by oli-obk** [comment] 2018-08-08 13:04
huh... has it been this way since unions were introduced or is this a regression?

**Comment by gnzlbg** [comment] 2018-08-08 13:06
No idea. I use unions a lot and this is the first time I see this. I did not managed to find an open issue about it.

**Comment by oli-obk** [comment] 2018-08-08 13:13
Ah! I overlooked the constant. Yea, the body of the constant is its own scope and does require its own unsafe blocks.

This is working as intended to the best of my knowledge

**Comment by oli-obk** [comment] 2018-08-08 13:14
if you declare a safe function inside an unsafe block you don't expect to be able to use unsafe things inside that safe function either.

**Comment by petrochenkov** [comment] 2018-08-08 13:27
Fun fact: this worked before Rust 1.6.0 (not for unions, of course) - https://github.com/rust-lang/rust/issues/47864#issuecomment-361526011.

**Comment by oli-obk** [comment] 2018-08-08 13:37
duplicate of https://github.com/rust-lang/rust/issues/35716

**Closed by oli-obk** 2018-08-08 13:37 UTC

**Comment by gnzlbg** [comment] 2018-08-08 13:59
Thank you for the clarification @oli-obk - maybe that note ("the body of the constant is its own scope and requires its own unsafe block, just like safe functions inside unsafe functions") could be added to the error message in this case ?
