### ISSUE TITLE
Expected compile error because bad use of semicolon

### ISSUE THREAD

**Issue by wilmoz** [rust-lang/rust#28157] opened 2015-09-01 18:07 UTC
Actual result compile and output "bogus"

Code:
https://pastebin.mozilla.org/8844697

rustc 1.4.0-dev (7b7fc67dd 2015-08-13)

**Comment by jonas-schievink** [comment] 2015-09-01 18:31
Code in question:
```rust 
fn main(){
  if 4==4{;
    println!("bogus");
  }
}
```

The grammar docs indeed disallow a bare `;`.

**Comment by alexcrichton** [comment] 2015-10-21 23:55
triage: I-nominated

**Comment by alexcrichton** [comment] 2015-10-21 23:56
There's a PR to fix this issue (https://github.com/rust-lang/rust/pull/29215), but as it's a language change I wanted to circulate among the lang team to ensure that it's intended.

(fwiw I would personally consider this behavior fine, as shown by the fall out in the PR it's often convenient to rely on this in contexts like with macros)

**Comment by fhahn** [comment] 2015-10-22 08:15
If this comes out as wontfix, I think it still would make sense to remove the trailing semicolons after the few function definitions. I would also be happy to update the documentation and the reference parser.

**Comment by nikomatsakis** [comment] 2015-10-23 18:51
We discussed in the @rust-lang/lang and came to the conclusion that parsing an empty semicolon here is not a bug and we should not attempt to issue warnings or make it an error. In fact, most of us rather expected it to work, perhaps because of C precendent. 

However, @nrc pointed out that a clippy lint might be suitable or -- perhaps better yet -- modifying rustfmt to drop such statements. I too would personally prefer to have rustfmt silently clean things up behind my back than to have to some lint nag me about it. :)

**Comment by nikomatsakis** [comment] 2015-10-23 18:52
(Also, it seems like a case where being backwards incompatible just isn't really necessary.)

**Comment by fhahn** [comment] 2015-10-23 22:36
Sure that makes perfect senes. @jonas-schievink do you remember where you found the grammar definition which said a bare semicolon should not be allowed? I could not find it.

**Comment by jonas-schievink** [comment] 2015-10-23 22:40
I think I looked at http://doc.rust-lang.org/grammar.html#statements-and-expressions

**Closed** 2015-10-24 21:24 UTC
Labels: A-parser, I-nominated, T-lang

**Comment by fhahn** [comment] 2015-10-26 16:32
@jonas-schievink  thanks Jonas, I've updated the docs.
