### ISSUE TITLE
Support of cdylib crate types on iOS in Rust 1.46 breaks usual build workflows

### ISSUE THREAD

**Issue by vimmerru** [rust-lang/rust#79373] opened 2020-11-24 08:59 UTC
PR https://github.com/rust-lang/rust/pull/73516/ added support of `cdylib` crate types on iOS. This new feature in Rust 1.46 added a lot of headache for iOS builds with `cdylib` targets. `cdylib` target is near impossible to build on iOS if you are using any crate with native dependencies (ex. openssl, libsodium, zmq). You can't just find .so files for all architectures to perform correct linking and any vendored build paths don't support iOS properly. Usual workflow is the following:

1. You build `staticlib` and rely that native dependencies will be linked as frameworks later
2. You setup right cocoapods in ObjectiveC/Swift wrapper.

As cargo doesn't support platform-dependent crate types https://github.com/rust-lang/cargo/issues/4881 as a result a lot of projects that require iOS support are now broken on Rust 1.46.

Also seems usual iOS tools like `cargo lipo` don't support crate type overrides for the moment.

It works on 1.45 well because cargo just skips unsupported crate types on iOS and Android.

**Comment by jonas-schievink** [comment] 2020-11-24 12:21
That PR has been reverted in https://github.com/rust-lang/rust/pull/77716 since other people ran into problems as well. It will be fixed in Rust 1.49 (currently in beta).

You can help detect these regressions earlier by testing against the nightly Rust channel in addition to stable.

**Comment by cutsoy** [comment] 2020-12-03 18:52
I filed a PR in Cargo that makes it easier to switch crate-types at any step of your workflow: https://github.com/rust-lang/cargo/pull/8789. This allows running `cargo build --crate-type staticlib` to override the crate type of the "final" product (not necessarily its dependencies), which is what most of us want. Would that be helpful in your situation?

**Comment by jonas-schievink** [comment] 2020-12-06 18:37
Closing this, as the PR has already been reverted and approved for stable-backport. Whether a stable patch release happens is still unclear though.

**Closed by jonas-schievink** 2020-12-06 18:37 UTC
Labels: O-ios
