### ISSUE TITLE
bad location list debug info

### ISSUE THREAD

**Issue by xdje42** [rust-lang/rust#67992] opened 2020-01-08 00:14 UTC
Compiling this program produces bad debug info in the location list entry for argument "a" of function "foo". GDB crashes on it, which is GDB's problem (https://sourceware.org/bugzilla/show_bug.cgi?id=25353), but Rust should also not generate bad debug info.

```rust
const ARRAY_SIZE: usize = 1024;

struct Foo {
    x: [u64; ARRAY_SIZE],
}

fn foo(a: Foo, i: usize) -> u64 {
    a.x[i]
}

fn main() {
    println!("Hello, world!");

    println!("{}", foo(Foo{x: [0; ARRAY_SIZE]}, 42));
}
```

```
bash$ cargo build
bash$ readelf -w target/debug/location-lists
-->
 <2><cb0>: Abbrev Number: 3 (DW_TAG_subprogram)
...
    <cc3>   DW_AT_name        : (indirect string, offset: 0x7cb): foo
...
 <3><ccd>: Abbrev Number: 4 (DW_TAG_formal_parameter)
    <cce>   DW_AT_location    : 0x0 (location list)
    <cd2>   DW_AT_name        : (indirect string, offset: 0x85bf2): a
    <cd6>   DW_AT_decl_file   : 1
    <cd7>   DW_AT_decl_line   : 7
    <cd8>   DW_AT_type        : <0xd24>
...
Contents of the .debug_loc section:

    Offset   Begin            End              Expression
    00000000 0000000000004469 000000000000447f (DW_OP_breg5 (rdi): 0)
    00000014 000000000000447f 0000000000004490 (DW_OP_breg7 (rsp): 8; DW_OP_deref)
    00000029 0000000000004490 0000000000004499 (DW_OP_reg2 (rcx))
    0000003c 0000000000004499 00000000000044b0 (DW_OP_breg7 (rsp): 8; DW_OP_deref)
    00000051 00000000000044b0 00000000000044b2 (DW_OP_reg4 (rsi))
    00000064 <End of list>
```
Note the entries saying "a" lives in rcx and rsi (that is the value of "a" lives in the register, not its address).

**Comment by wesleywiser** [comment] 2023-08-21 14:16
Visited during wg-debugging triage. This seems to be resolved as both the current `.debug_loc` looks correct:

```
Contents of the .debug_loc section:

    Offset   Begin            End              Expression
    00000000 ffffffffffffffff 0000000000008ae0 (base address)
    00000010 0000000000008ae8 0000000000008aed (DW_OP_breg7 (rsp): 0; DW_OP_deref)
    00000025 0000000000008aed 0000000000008afe (DW_OP_breg5 (rdi): 0)
    00000039 0000000000008afe 0000000000008b30 (DW_OP_breg7 (rsp): 0; DW_OP_deref)
    0000004e <End of list>
```

and gdb itself no longer crashes and it able to display the value of `a` throughout the function as well. Marking this as `E-needs-test` as it would be great to have a regression test for this.

**Closed** 2023-08-29 21:17 UTC
Labels: A-debuginfo, E-needs-test, P-low, T-compiler, C-bug
