### ISSUE TITLE
[wish list] Confusing error message E0308 when using two diff versions of a library

### ISSUE THREAD

**Issue by jaredly** [rust-lang/rust#27420] opened 2015-07-31 03:51 UTC
I came across this confusing error message:

```
src/main.rs:17:37: 17:67 error: mismatched types:
 expected `&nalgebra::structs::vec::Vec3<f32>`,
    found `&nalgebra::structs::vec::Vec3<f32>`
(expected struct `nalgebra::structs::vec::Vec3`,
    found a different struct `nalgebra::structs::vec::Vec3`) [E0308]
```

:) and the problem was that the version of `nalgebra` that I depended on was different from that which another library depended on. But the error message didn't make that clear.

Is there a way to check for this (even just "the text of expected and found is the same"), and offer a helpful `you are probably using two diff versions of the library nalgebra`?

**Comment by steveklabnik** [comment] 2015-08-04 21:51
We have several issues open related to this, though I can't seem to find them right now... @alexcrichton i think you may know?

**Comment by alexcrichton** [comment] 2015-08-04 21:55
I think this is a dupe of either https://github.com/rust-lang/rust/issues/23252 or https://github.com/rust-lang/rust/issues/22750, so closing in favor of those.

**Closed by alexcrichton** 2015-08-04 21:55 UTC
