### ISSUE TITLE
regression: type annotations required cannot resolve `std::borrow::Cow<'_, str>: std::borrow::Borrow<_>`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61476] opened 2019-06-03 01:48 UTC
root: zmtp - 2 detected crates which regressed due to this; cc @jjpe
<details>

 * rustyq-0.6.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-1/1.35.0/reg/rustyq-0.6.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-1/beta-2019-05-30/reg/rustyq-0.6.0/log.txt); cc `@jjpe`
 * zmtp-0.6.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-1/1.35.0/reg/zmtp-0.6.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-1/beta-2019-05-30/reg/zmtp-0.6.0/log.txt); cc `@jjpe`

</details>

**Comment by eddyb** [comment] 2019-06-06 14:47
I can't find a library change that would cause this (and rustdoc confirms that `Borrow` has the same set of `impl`s on `stable` and `beta`), marking as `T-compiler`.

**Comment by pnkfelix** [comment] 2019-06-20 12:47
This regression was injected by commit 1962adea6ad9b992516ae56ad7f8c5bc33b951cb aka PR #60877, which rolled up the following PR's:

 - #59825 (string: implement From<&String> for String)
 - #59923 (Fix convert module's documentation links)
 - #60691 (Include expression to wait for to the span of Await)
 - #60769 (Update rustc book CLI docs.)
 - #60816 (README.md: Mention MSVC 2017+, not 2013(!))
 - #60851 (Move `box` from the stable keyword to unstable keywords list)

**Comment by pnkfelix** [comment] 2019-06-20 12:48
(could this regression have been caused by PR #59825 ?)

**Comment by pnkfelix** [comment] 2019-06-20 12:58
Apparently so; this appears to be a duplicate of #60958, which it seems has already been discussed amongst the libs team with the conclusion that this is acceptable fallout from PR #59825?

**Comment by pnkfelix** [comment] 2019-06-20 12:59
I would file a followup issue against the zmtp crate, but it is hosted on bitbucket.org, and apparently my account credentials there no longer work...

**Comment by pnkfelix** [comment] 2019-06-20 13:09
Closing as duplicate of #60958.

**Closed by pnkfelix** 2019-06-20 13:09 UTC
Labels: T-compiler, T-libs, regression-from-stable-to-beta

**Comment by jjpe** [comment] 2019-06-20 13:11
So this will require downstream libs (among which zmtp) to fix code that used to work on stable but no longer will once this rustc beta stabilizes, do I understand that correctly?

**Comment by pnkfelix** [comment] 2019-06-21 08:48
> So this will require downstream libs (among which zmtp) to fix code that used to work on stable but no longer will once this rustc beta stabilizes, do I understand that correctly?

@jjpe that interpretation is consistent with my understanding. See further discussion on #60958, for example [this comment](https://github.com/rust-lang/rust/issues/60958#issuecomment-495145878)

**Comment by pnkfelix** [comment] 2019-06-21 08:50
In particular, changes that cause crates to add more type annotations is allowed under the stability guarantees as described in [this blog post](https://blog.rust-lang.org/2014/10/30/Stability.html#what-are-the-stability-caveats)
