### ISSUE TITLE
Trying to create a >isize::MAX length slice crashes the compiler

### ISSUE THREAD

**Issue by petertodd** [rust-lang/rust#67714] opened 2019-12-30 01:42 UTC
```
fn main() {
    let bigarray = [(); 9223372036854775808];
    let _bigslice: &[()] = &bigarray;
}
```

results in:

```
invalid subrange count
!126 = !DISubrange(count: -9223372036854775808)
invalid subrange count
!126 = !DISubrange(count: -9223372036854775808)
LLVM ERROR: Broken module found, compilation aborted!
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Of course, this is invalid. But a better error message would be nice!

**Comment by petertodd** [comment] 2019-12-30 23:05
Related:

```
fn main() {
    // SAFETY: because () is a ZST, we can coerce a &() to a &[(); N] array.
    let arr: &[(); isize::max_value() as usize + 1] = unsafe { &*(&() as *const _ as *const _) };
}
```

Produces the same error.

**Comment by ollie27** [comment] 2019-12-31 00:30
Duplicate of #34127.

**Closed by ollie27** 2019-12-31 00:30 UTC
Labels: A-debuginfo, C-bug, I-crash, I-nominated, T-compiler
