### ISSUE TITLE
proc-macro param attrs dropping first attrs in impl fns

### ISSUE THREAD

**Issue by bbqsrc** [rust-lang/rust#64682] opened 2019-09-22 09:42 UTC
I have been able to reproduce https://github.com/rust-lang/rust/issues/64282.

If an `fn` inside an `impl` has a param attr on the first parameter, no matter how many, they are not visible in the `TokenStream`.

Repro repo: https://github.com/bbqsrc/params-attribute-example

Source: 

```rust

#[rename_params(send_help)]
fn hello(#[angery(true)] a: i32, #[a2] b: i32, #[what = "how"] c: u32) {}

#[rename_params(send_help)]
impl Foo {
  fn hello(#[angery(true)] a: i32, #[a2] b: i32, #[what = "how"] c: u32) {}
  fn hello2(#[a1] #[a2] a: i32, #[what = "how"] b: i32, #[angery(true)] c: u32) {}
  fn hello_self(#[a1] #[a2] &self, #[a1] #[a2] a: i32, #[what = "how"] b: i32, #[angery(true)] c: u32) {}
}
```

Printed output:

```rust
fn hello(#[angery(true)] a: i32, #[a2] b: i32, #[what = "how"] c: u32) { }
impl Foo {
    fn hello(a: i32, #[a2] b: i32, #[what = "how"] c: u32) { }
    fn hello2(a: i32, #[what = "how"] b: i32, #[angery(true)] c: u32) { }
    fn hello_self(#[a1] #[a2] &self, #[a1] #[a2] a: i32,
                  #[what = "how"] b: i32, #[angery(true)] c: u32) {
    }
}
```

As you can see, `hello` and `hello2` are missing their attrs on the `a` param. The addition of `self` however gives both `self` and the `a` param their attrs. Weird.

```
$ rustc --version
rustc 1.39.0-nightly (ed8b708c1 2019-09-21)
```

**Comment by bbqsrc** [comment] 2019-09-22 09:43
Ping @Centril

**Comment by bbqsrc** [comment] 2019-09-22 09:50
Also pinging @c410-f3r due to impact on https://github.com/rust-lang/rust/pull/64010.

**Comment by c410-f3r** [comment] 2019-09-25 00:22
I'm rather busy this week and I can only take a look into it this weekend

**Comment by pnkfelix** [comment] 2019-09-26 11:52
triage: P-high. Leaving nominated in hopes to find someone to look into it, since @c410-f3r  won't have time for next few days.

**Comment by pnkfelix** [comment] 2019-09-26 14:28
assigning to @Centril

**Comment by Centril** [comment] 2019-09-29 06:20
Investigation thus far: I don't think the problem is in pretty printing but somewhere else.

```rust
#![deny(unused_variables)]

struct Foo;

fn _f0(#[allow(unused_variables)] p0: u8) {}

impl Foo {
    fn _f1(#[allow(unused_variables)] p1: u8) {}
    
    fn _f2(&self, #[allow(unused_variables)] p2: u8) {}
}
```

results in:

```rust
error: unused variable: `p1`
 --> src/lib.rs:8:39
  |
8 |     fn _f1(#[allow(unused_variables)] p1: u8) {}
  |                                       ^^ help: consider prefixing with an underscore: `_p1`
  |
note: lint level defined here
 --> src/lib.rs:1:9
  |
1 | #![deny(unused_variables)]
  |         ^^^^^^^^^^^^^^^^
```

**Closed** 2019-09-29 22:21 UTC
Labels: A-attributes, A-macros, C-bug, P-high, T-compiler
