### ISSUE TITLE
ICE: translating unsupported cast: *const u8 (cast_pointer) -> *const [u8] (cast_other)

### ISSUE THREAD

**Issue by hyunsik** [rust-lang/rust#24709] opened 2015-04-23 00:59 UTC
Hi folks,

I'm getting an ICE from the following code fragment:

```rust
let xy: Vec<u8> = vec![0,1,2,3];
let slice = xy.as_ptr() as *const [u8];
```

rustc version is
```
workstation:~# rustc --version
rustc 1.0.0-nightly (2baf34825 2015-04-21) (built 2015-04-22)
```

backtrace results:
```
arena_tests.rs:49   let slice = xy.as_ptr() as *const [u8];
                        ^~~~~
error: internal compiler error: translating unsupported cast: *const u8 (cast_pointer) -> *const [u8] (cast_other)
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:209

stack backtrace:
   1:     0x7f5a17169bb9 - sys::backtrace::write::he1173a406c2335a83JC
   2:     0x7f5a1718e4b7 - panicking::on_panic::hfd4f10113591c07f9aJ
   3:     0x7f5a170d8322 - rt::unwind::begin_unwind_inner::h5dd2f870d997f851hQI
   4:     0x7f5a1466f8ad - rt::unwind::begin_unwind::h11948444363592342521
   5:     0x7f5a1466ff6b - diagnostic::Handler::bug::h8b610b99ced770c3AtB
   6:     0x7f5a1504ae6b - session::Session::bug::h9b57e3cf31a5ccf02Sq
   7:     0x7f5a168c5b37 - trans::expr::trans_imm_cast::hcc8d7dfc4709cde4XCC
   8:     0x7f5a168b9897 - trans::expr::trans_unadjusted::hf7cee925729ae17cJQA
   9:     0x7f5a1688f088 - trans::expr::trans_into::h6ab0ed2ab3f50b9a67z
  10:     0x7f5a1691005a - trans::_match::mk_binding_alloca::h7975878531167784623
  11:     0x7f5a167fd05e - trans::base::init_local::h091fe6ffe939a1f5VWg
  12:     0x7f5a1680d8ee - trans::controlflow::trans_block::h4cc709c0c234a1a9f5u
  13:     0x7f5a1680c6b1 - trans::base::trans_closure::hca42661a4cb8808aYDh
  14:     0x7f5a1680e1da - trans::base::trans_fn::h8c8ad1cfb018c3d1IOh
  15:     0x7f5a16811267 - trans::base::trans_item::h5f366b9cf5915577Yci
  16:     0x7f5a1681fadd - trans::base::trans_crate::h4d51da86e796d34d31i
  17:     0x7f5a177e20fa - driver::phase_4_translate_to_llvm::hb8e4f02386630e0djOa
  18:     0x7f5a177b9f4a - driver::compile_input::h7fb56cda9a0f227dQba
  19:     0x7f5a17878711 - run_compiler::hbdd9b2c4cacce291L4b
  20:     0x7f5a17876362 - boxed::F.FnBox<A>::call_box::h9433597520612747
  21:     0x7f5a17875899 - rt::unwind::try::try_fn::h10263588931191114294
  22:     0x7f5a17204348 - rust_try_inner
  23:     0x7f5a17204335 - rust_try
  24:     0x7f5a17875b48 - boxed::F.FnBox<A>::call_box::h17081069488870149893
  25:     0x7f5a1717be41 - sys::thread::create::thread_start::hb84d91b7ff5c0ddcrLH
  26:     0x7f5a111580a4 - start_thread
  27:     0x7f5a16d42cfc - __clone
  28:                0x0 - <unknown>

```

**Comment by jdm** [comment] 2015-04-23 02:44
Looks like a duplicate of #22955.

**Closed by jdm** 2015-04-23 02:44 UTC
