### ISSUE TITLE
Sync/Send mismatch for Iter?

### ISSUE THREAD

**Issue by sparecycles** [rust-lang/rust#53625] opened 2018-08-23 03:17 UTC
There are a few places where an `Iter` implements `Send` when the item/key/value traits are `Sync`.  The other related types (`IterMut`, etc...) implement `Sync` for `Sync` items and `Send` for `Send` items.

See line 1209 in 
https://github.com/rust-lang/rust/blob/917945d662c42053383fe3e71cb0f313d585e459/src/liballoc/collections/linked_list.rs#L1202-L1218

and also in
https://github.com/rust-lang/rust/blob/917945d662c42053383fe3e71cb0f313d585e459/src/libcore/slice/mod.rs#L2650-L2653

as well as
https://github.com/rust-lang/rust/blob/917945d662c42053383fe3e71cb0f313d585e459/src/libstd/collections/hash/table.rs#L916-L917

( Noticed this pattern in https://github.com/hyperium/http/pull/239 )

**Comment by qnighy** [comment] 2018-08-23 03:43
They just inherit the item type's sendability/syncability, not the generic parameter's. `&mut T: Send` if `T: Send` and `&T: Send` if `T: Sync`.

**Comment by sparecycles** [comment] 2018-08-23 04:29
Thanks, I see now why `Iter<Sync>` could be Send, but I'm not sure about related structs like `Drain` or `IntoIter`s.

It's interesting that `Iter<T: Send>` is not Send, but `IterMut<T: Send>` is.

**Comment by Dylan-DPC** [comment] 2022-12-06 13:01
I am closing this issue as it is not a bug and working as intended.

**Closed by Dylan-DPC** 2022-12-06 13:01 UTC
Labels: T-libs-api, A-iterators
