### ISSUE TITLE
Soundness hole in pattern matching on enums with an uninhabited variant

### ISSUE THREAD

**Issue by chrunchyjesus** [rust-lang/rust#61696] opened 2019-06-09 17:37 UTC
Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7a8a62d7a736d6bd54273422da29d7af

<details>
<summary> Click to see the example code from above link </summary>

```rust
#[derive(Debug)]
enum A {
    B(B),
    C(C),
    A1,
    A2,
}

#[derive(Debug)]
enum B {
    B1,
    B2,
    B3,
    B4,
    B5,
}

#[derive(Debug)]
enum C {}

fn main() {
    let a = A::B(B::B5);
    match a {
        A::B(_) => println!("success"),
        _ => println!("error: {:?}", a),
    }
}
```

</details>

Expected output: `success`

Actual output:
```
timeout: the monitored command dumped core
/root/entrypoint.sh: line 8:     7 Illegal instruction     timeout --signal=KILL ${timeout} "$@"
```

Running the above code on both Rust stable and nightly on my machine returns `illegal hardware instruction (core dumped)` with some number different on each run prefixing the output.

Some experimentations:
* Implementing variants for enum `C` solves this issue.
* Remove variants `A1` and `A2` solves this issue.
* Use any variant of `B` other than `B5` works.

I assume this is a bug in the compiler?

**Comment by Mark-Simulacrum** [comment] 2019-06-09 17:39
cc @eddyb since potentially has something to do with enum optimizations?

**Comment by Centril** [comment] 2019-06-09 17:59
First reduction (will iterate):
```rust
#![allow(dead_code)]

#[derive(Debug)]
enum A {
    B(B),
    C(C),
    A1,
    A2,
}

#[derive(Debug)]
enum B {
    B1 = 4,
    B5,
}

#[derive(Debug)]
enum C {}

fn main() {
    let a = A::B(B::B5);
    println!("error: {:?}", a);
}
```

**Comment by jonas-schievink** [comment] 2019-06-09 18:04
Regression between 1.23.0 and 1.24.0

**Comment by Centril** [comment] 2019-06-09 19:13
This seems like a rather serious soundness hole that I would suggest treating as P-high.

cc @rust-lang/compiler

**Comment by nagisa** [comment] 2019-06-09 21:08
Given

```rust
#![feature(never_type, core_intrinsics)]

pub enum E1 {
    V1 { f: E2 },
    V2 { f: ! },
    V3,
    V4,
}
pub enum E2 {
    V1 = 4,
    V2,
}

fn main() {
    match (E1::V1 { f: E2::V2 }) {
        E1::V2 { .. } => unsafe { ::core::intrinsics::unreachable() },
        _ => {},
    }
}
```

LLVM for the interesting code is:

```llvm
; test::main
; Function Attrs: nonlazybind uwtable
define internal void @_ZN4test4main17h4c216eb98fecdd36E() unnamed_addr #0 {
start:
  %_1 = alloca i8, align 1
  store i8 1, i8* %_1, align 1
  %0 = load i8, i8* %_1, align 1, !range !3    ; %0 = 1
  %1 = sub i8 %0, 0                            ; %1 = 1
  %2 = icmp ule i8 %1, 3                       ; %2 = 1 <= 3 = 1
  %3 = zext i8 %1 to i64                       ; %3 = 1
  %4 = select i1 %2, i64 %3, i64 0             ; %4 = 0
  %5 = icmp eq i64 %4, 1                       ; %5 = 0
  br i1 %5, label %bb1, label %bb2             ; -> bb1

bb1:                                              ; preds = %start
  unreachable

bb2:                                              ; preds = %start
  ret void
}

!3 = !{i8 0, i8 4}
```

**Comment by nagisa** [comment] 2019-06-09 21:30
This is probably not A-LLVM because the generated LLVM code is already wrong.

**Comment by eddyb** [comment] 2019-06-10 08:12
So the `!3` range is `0..=4`, right? But `E2::V2` should be `5`, so why does the range not include `5` and why does it store `1`?!

**Comment by RalfJung** [comment] 2019-06-10 10:56
MIR still looks okay to me, so this seems like a MIR -> LLVM-IR translation bug.

**Comment by nagisa** [comment] 2019-06-10 11:00
@eddyb I edited the code snippet – the reproducer above has changed in the time I was looking at things and I blindly copied it.

**Comment by eddyb** [comment] 2019-06-10 11:09
Much better, thanks!

So `%2 = icmp ule i8 %1, 3` is, I believe, the check for the "dataful variant", since it's used to select discriminant `0` (`E1::V1`) when `false`. But it's `true` because the condition is all wrong.
I suspect the comparison was originally designed with "zero is a niche" in mind, but in this case, the available niche values are `2..=255_u8` (from the `bool`), so it should be checking `>= 2` not `<= 3`.

Alternatively, `sub i8 %0, 0` should be "rebasing" the the integers in memory to the `enum` discriminants, which would require subtracting `1`, not `0`, so maybe it's "just" an off-by-one?

**Comment by hellow554** [comment] 2019-06-11 07:13
"More minimized" without match and unstable features:

```
pub enum Infallable {}

pub enum E1 {
    V1 { f: bool },
    V2 { f: Infallable },
    V3,
    V4,
}

fn main() {
    if let E1::V2 { .. } = (E1::V1 { f: true }) {
        unsafe { std::hint::unreachable_unchecked(); }
    }
}
```

Interesting enough: When one removes the `V4` in the enum, the MIR code is still the very same, but it does not print the line.
The LLVM-IR changes from

```
; playground::main
; Function Attrs: norecurse noreturn nounwind nonlazybind readnone uwtable
define internal void @_ZN10playground4main17h13d813b46f0ec3d7E() unnamed_addr #2 {
start:
  unreachable
}
```

to

```
; playground::main
; Function Attrs: norecurse nounwind nonlazybind readnone uwtable
define internal void @_ZN10playground4main17h13d813b46f0ec3d7E() unnamed_addr #1 {
start:
  ret void
}
```

(`noreturn` and `ret void` vs `unreachable`).

**Comment by pnkfelix** [comment] 2019-06-13 14:02
triage: P-high. Leaving nominated and unassigned for now.

**Comment by oli-obk** [comment] 2019-06-21 14:09
I compared what miri does (which doesn't fail) against what codegen does. The relevant difference is

https://github.com/rust-lang/rust/blob/38cd9489f75f4a4387296ee304e2287f7c32c211/src/librustc_mir/interpret/operand.rs#L652

vs

https://github.com/rust-lang/rust/blob/38cd9489f75f4a4387296ee304e2287f7c32c211/src/librustc_codegen_ssa/mir/place.rs#L269

where the latter (codegen) does not check whether `niche_variants.start() <= adjusted_discr`.

Other than that, both code paths are equivalent

> Interesting enough: When one removes the V4 in the enum, the MIR code is still the very same, but it does not print the line.

I'd guess that's just a result from other niche optimizations kicking in for the enum without `V4`.

**Comment by eddyb** [comment] 2019-06-25 14:34
I think I've figured out what's wrong here, why this wasn't triggered more often, and why `V4` is needed.

What we have is an `enum`, with 4 variants:
* `V1` contains the `bool` (which uses `0` and `1`, so `niche_start` will be `2`)
* `V2` is *excluded* because it's uninhabited
* `V3` and `V4` are the `niche_variants`

I was confused because *initially* I thought `V2` would be included and therefore `niche_variants.start()` would be `1` - but no, it's `2`! So the codegen of the `isub` instruction is correct, `delta` should be `0`.

The reason this hasn't caused many problems in the past is that `niche_variants.start()` has always been `1` (if the dataful variant is the first one) or `0` (otherwise), if no variant is uninhabited.

Currently, the check is:
```rust
discr - niche_start + niche_variants.start() <= niche_variants.end()
```
But the correct one-comparison trick, which I *meant* to use, would be:
```rust
discr - niche_start <= niche_variants.end() - niche_variants.start()
```
That is, you *have to* rely on rebasing the lowest value in the range to `0`, for this to work.

What miri does is less efficient, but that's fine, as it's an interpreter. For codegen we want something simple.

**Comment by RalfJung** [comment] 2019-06-25 14:54
> What miri does is less efficient, but that's fine, as it's an interpreter. For codegen we want something simple.

What Miri does is correct though? Including considering both `variants_start` and `variants_end` as *inclusive* bounds?

**Comment by eddyb** [comment] 2019-06-25 16:06
@RalfJung `a <= x && x <= b` is equivalent to `x - a <= b - a` (assuming unsigned integers).
This is because everything in `a..=b` will be shifted over to `0..=b-a` and `a <= x` becomes `0 <= x - a`.

And it would've worked, too, if I hadn't combined *a different* operation into it, ruining the trick.

Oh and miri should probably be using `.contains(...)` on a range, ideally the one from the layout.

**Comment by RalfJung** [comment] 2019-06-25 18:57
@eddyb 
> Oh and miri should probably be using .contains(...) on a range, ideally the one from the layout.

I tried, it doesn't really make things nicer and I am not even sure if moving the assertions around is correct: https://github.com/RalfJung/rust/commit/279adf8f7feac8c6dd542586fdb024cf4623dbe7.

The `adjusted_discr` actually is `raw_discr - niche_start + variants_start`, so comparing that with `variants_start` again is anyway a bit funny.

**Comment by eddyb** [comment] 2019-06-26 06:45
@RalfJung Hmm, the arithmetic probably needs to be done on the size of the discriminant, like here:
https://github.com/rust-lang/rust/blob/bdd4bda4d5fe7eb24a7209a6c0c968a54869d3b7/src/librustc_target/abi/mod.rs#L664-L669

Double-casting assertions can, and probably should, be replaced nowadays by `.try_into().unwrap()`.
Otherwise, your changes are in the right direction, IMO.

**Comment by RalfJung** [comment] 2019-06-26 07:12
>  Otherwise, your changes are in the right direction, IMO.

I am not so convinced... seems like the `VariantIdx` is a `u32`, but the discriminant may be way bigger, so probably casting things down before we know that it is in the "niche range" is wrong?

This avoids casting too early, but it's not really any safer than what we do right now: https://github.com/RalfJung/rust/commit/f311c4e84d

**Comment by pnkfelix** [comment] 2019-06-27 13:51
triage: assigning to @eddyb

**Comment by eddyb** [comment] 2019-06-27 13:56
> Regression between 1.23.0 and 1.24.0

I was going to argue that the bug is older, but 1.23 was early 2018, and the bug was introduced late 2017, as the code in question has been wrong in the same way since #45225.
So yeah, a 2-year-old `regression-from-stable-to-stable` codegen bug.

**Comment by pnkfelix** [comment] 2019-06-27 14:19
noted that issue appears under control at T-compiler meeting, and deliberately skipped discussion of it. Removing nomination label.

**Closed** 2019-07-14 00:21 UTC
Labels: A-codegen, C-bug, I-unsound 💥, P-high, T-compiler, regression-from-stable-to-stable
