### ISSUE TITLE
Build 1.53 fails

### ISSUE THREAD

**Issue by voncloft** [rust-lang/rust#86981] opened 2021-07-08 16:13 UTC
Tried to compile 1.53 using:

https://www.linuxfromscratch.org/blfs/view/svn/general/rust.html

and the README.md on this site

Got the following error:

`   Compiling cargo-miri v0.1.0 (/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/tools/miri/cargo-miri)
error: failed to run custom build command for `cargo-miri v0.1.0 (/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/tools/miri/cargo-miri)`

Caused by:
  process didn't exit successfully: `/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/release/build/cargo-miri-f53b4c1caa863776/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'Unable to generate vergen keys!: could not find repository from '/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/tools/miri/cargo-miri'; class=Repository (6); code=NotFound (-3)

  Stack backtrace:
     0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/vendor/anyhow-1.0.34/src/error.rs:464:25
     1: vergen::feature::git::configure_git
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/vendor/vergen/src/feature/git.rs:175:55
     2: vergen::config::Instructions::config
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/vendor/vergen/src/config.rs:139:9
     3: vergen::gen::config_from_instructions
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/vendor/vergen/src/gen.rs:81:32
     4: vergen::gen::vergen
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/vendor/vergen/src/gen.rs:69:5
     5: build_script_build::main
               at ./build.rs:10:5
     6: core::ops::function::FnOnce::call_once
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/core/src/ops/function.rs:227:5
     7: std::sys_common::backtrace::__rust_begin_short_backtrace
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:125:18
     8: std::rt::lang_start::{{closure}}
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/rt.rs:49:18
     9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/core/src/ops/function.rs:259:13
        std::panicking::try::do_call
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:379:40
        std::panicking::try
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:343:19
        std::panic::catch_unwind
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/panic.rs:431:14
        std::rt::lang_start_internal
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/rt.rs:34:21
    10: std::rt::lang_start
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/rt.rs:48:5
    11: main
    12: __libc_start_main
    13: _start
               at /sources/glibc-2.29/csu/../sysdeps/x86_64/start.S:120', src/tools/miri/cargo-miri/build.rs:10:24
  stack backtrace:
     0: rust_begin_unwind
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/core/src/panicking.rs:92:14
     2: core::result::unwrap_failed
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/core/src/result.rs:1355:5
     3: core::result::Result<T,E>::expect
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/core/src/result.rs:997:23
     4: build_script_build::main
               at ./build.rs:10:5
     5: core::ops::function::FnOnce::call_once
               at /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
command did not execute successfully: "/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--locked" "--frozen" "--manifest-path" "/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/tools/miri/cargo-miri/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
      < ToolBuild { compiler: Compiler { stage: 2, host: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None } }, target: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None }, tool: "cargo-miri", path: "src/tools/miri/cargo-miri", mode: ToolRustc, is_optional_tool: true, source_type: Submodule, extra_features: [] }
    < CargoMiri { compiler: Compiler { stage: 2, host: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None } }, target: TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None }, extra_features: [] }
thread 'main' panicked at 'Unable to build cargo miri', src/bootstrap/dist.rs:44:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:435:5
   2: bootstrap::dist::missing_tool
             at ./src/bootstrap/dist.rs:44:9
   3: <bootstrap::dist::Miri as bootstrap::builder::Step>::run::{{closure}}
             at ./src/bootstrap/dist.rs:1189:17
   4: core::option::Option<T>::or_else
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/option.rs:818:21
   5: <bootstrap::dist::Miri as bootstrap::builder::Step>::run
             at ./src/bootstrap/dist.rs:1186:25
   6: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:1521:23
   7: <bootstrap::install::Miri as bootstrap::builder::Step>::run
             at ./src/bootstrap/install.rs:178:32
   8: bootstrap::builder::Builder::ensure
             at ./src/bootstrap/builder.rs:1521:23
   9: <bootstrap::install::Miri as bootstrap::builder::Step>::make_run
             at ./src/bootstrap/install.rs:127:17
  10: bootstrap::builder::StepDescription::maybe_run
             at ./src/bootstrap/builder.rs:179:13
  11: bootstrap::builder::StepDescription::run
             at ./src/bootstrap/builder.rs:200:25
  12: bootstrap::builder::Builder::run_step_descriptions
             at ./src/bootstrap/builder.rs:575:9
  13: bootstrap::builder::Builder::execute_cli
             at ./src/bootstrap/builder.rs:567:9
  14: bootstrap::Build::build
             at ./src/bootstrap/lib.rs:510:13
  15: bootstrap::main
             at ./src/bootstrap/bin/main.rs:33:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "./x.py", line 27, in <module>
    bootstrap.main()
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/bootstrap/bootstrap.py", line 1191, in main
    bootstrap(help_triggered)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/bootstrap/bootstrap.py", line 1177, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/cache/scratchpkg/work/rust/src/rustc-1.53.0-src/build/bootstrap/debug/bootstrap install -v
==> ERROR: Build failed: rust-1.53.0-1
`

**Comment by jonas-schievink** [comment] 2021-07-08 16:19
duplicate of https://github.com/rust-lang/rust/issues/86436

**Closed by jonas-schievink** 2021-07-08 16:19 UTC
