### ISSUE TITLE
rustc 1.23.0 panic on windows

### ISSUE THREAD

**Issue by saarw** [rust-lang/rust#47684] opened 2018-01-23 20:33 UTC
Getting the following compiler panic in 1.23.0 stable on windows (and only on Windows, runs fine on Mac and Linux). Don't have direct access to the machine so can't get backtrace or try nightly on it right now, but may try later.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.23.0 (766bd11c8 2018-01-01) running on x86_64-pc-windows-msvc

thread 'rustc' panicked at 'specified instant was later than self', src\libcore\option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `ordered-float`.

**Comment by steveklabnik** [comment] 2018-01-23 20:38
I cannot reproduce with `ordered-float`:

```shell
> cargo clone ordered-float
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading ordered-float v0.5.0
> cd .\ordered-float\
> cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading num-traits v0.1.42
   Compiling num-traits v0.1.42
   Compiling void v1.0.2
   Compiling unreachable v0.1.1
   Compiling ordered-float v0.5.0 (file:///C:/Users/steve/tmp/ordered-float)
    Finished dev [unoptimized + debuginfo] target(s) in 4.53 secs
> rustc -vV
rustc 1.25.0-nightly (b5392f545 2018-01-08)
binary: rustc
commit-hash: b5392f54503fdaf04df4b9578510b2baa944f4af
commit-date: 2018-01-08
host: x86_64-pc-windows-msvc
release: 1.25.0-nightly
LLVM version: 4.0
> cargo +stable build
   Compiling num-traits v0.1.42
   Compiling void v1.0.2
   Compiling unreachable v0.1.1
   Compiling ordered-float v0.5.0 (file:///C:/Users/steve/tmp/ordered-float)
    Finished dev [unoptimized + debuginfo] target(s) in 3.99 secs
> rustc +stable -vV
rustc 1.23.0 (766bd11c8 2018-01-01)
binary: rustc
commit-hash: 766bd11c8a3c019ca53febdcd77b2215379dd67d
commit-date: 2018-01-01
host: x86_64-pc-windows-msvc
release: 1.23.0
LLVM version: 4.0
```

**Comment by saarw** [comment] 2018-01-23 20:41
It seems to happen in different crates. now got it with error: Could not compile `num-traits`.

Backtrace is
stack backtrace:
   0:     0x7ffc74fb4e79 - _rdl_grow_in_place
   1:     0x7ffc74fc6087 - std::panicking::Location::column::h28b40ec705c5e546
   2:     0x7ffc74fc5cec - std::panicking::Location::column::h28b40ec705c5e546
   3:     0x7ffc74fc66f1 - std::panicking::rust_panic_with_hook::h73a8ba19426dc4bc
   4:     0x7ffc74fc6560 - std::panicking::begin_panic_fmt::h30275337d16f3133
   5:     0x7ffc74fc6441 - std::panicking::begin_panic_fmt::h30275337d16f3133
   6:     0x7ffc74fc63b4 - rust_begin_unwind
   7:     0x7ffc74fd606e - core::panicking::panic_fmt::h2add2073c03e1b21
   8:     0x7ffc74fd60ea - core::option::expect_failed::h62aa32a627994376
   9:     0x7ffc74fb3eb1 - std::time::Instant::duration_since::hf205834512ea3c88
  10:     0x7ffc74fb3f0d - std::time::Instant::elapsed::he1bf1266b3bc527e
  11:     0x7ffc6ebc70c1 - <rustc_trans::abi::attr_impl::ArgAttribute as core::fmt::UpperHex>::fmt::h6b1a1f0f6eb32310
  12:     0x7ffc6ebdfd2e - <rustc_trans::builder::Builder<'a, 'tcx> as core::ops::drop::Drop>::drop::hf57064746f371aa4
  13:     0x7ffc6deaf5bc - rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::ensure::hb6f171946daebc1f
  14:     0x7ffc6e05873c - rustc::dep_graph::graph::DepGraph::in_ignore::hf1d621baac1d7bf2
  15:     0x7ffc6dd65b5a - rustc::util::ppaux::<impl core::fmt::Debug for rustc::ty::Predicate<'tcx>>::fmt::h676d3496cb3708f4
  16:     0x7ffc6e1fece4 - <rustc::ty::_match::Match<'a, 'gcx, 'tcx> as rustc::ty::relate::TypeRelation<'a, 'gcx, 'tcx>>::tys::haf26cce42371d08b
  17:     0x7ffc6deaf673 - rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::ensure::hb6f171946daebc1f
  18:     0x7ffc6deb00e8 - rustc::ty::maps::<impl rustc::ty::maps::queries::symbol_name<'tcx>>::try_get::haa9a36edf6ce9e19
  19:     0x7ffc6e015eb9 - rustc::ty::maps::TyCtxtAt::symbol_name::hf0fbafab8c3ef5d4
  20:     0x7ffc6e24bb8e - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::symbol_name::h0f11095c026f7986
  21:     0x7ffc6eb0b8ad - <rustc_trans::symbol_names_test::SymbolNamesTest<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item::h0378c6a841615dfc
  22:     0x7ffc6eae818a - <unknown>
  23:     0x7ffc6eb0cd55 - <rustc_trans::symbol_names_test::SymbolNamesTest<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item::h0378c6a841615dfc
  24:     0x7ffc6df24fff - rustc::ty::maps::<impl rustc::ty::maps::queries::exported_symbols<'tcx>>::ensure::h3028cd1cb66c60e8
  25:     0x7ffc6e07a14b - rustc::dep_graph::graph::DepGraph::in_ignore::hf1d621baac1d7bf2
  26:     0x7ffc6dd7476f - rustc::util::ppaux::<impl core::fmt::Debug for rustc::ty::Predicate<'tcx>>::fmt::h676d3496cb3708f4
  27:     0x7ffc6e20c2a4 - <rustc::ty::_match::Match<'a, 'gcx, 'tcx> as rustc::ty::relate::TypeRelation<'a, 'gcx, 'tcx>>::tys::haf26cce42371d08b
  28:     0x7ffc6df2509a - rustc::ty::maps::<impl rustc::ty::maps::queries::exported_symbols<'tcx>>::ensure::h3028cd1cb66c60e8
  29:     0x7ffc6df258aa - rustc::ty::maps::<impl rustc::ty::maps::queries::exported_symbols<'tcx>>::try_get::h7e5aadbe9d446c86
  30:     0x7ffc6e01b55e - rustc::ty::maps::TyCtxtAt::exported_symbols::h301ae61ce3d093cb
  31:     0x7ffc6e24cb36 - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::exported_symbols::hcdf79fa9e881e8b4
  32:     0x7ffc6eb9e836 - rustc_trans::back::write::start_async_translation::hf345ba6a81ddda07
  33:     0x7ffc6ebe6d3d - rustc_trans::base::trans_crate::ha8d10b8471f7723a
  34:     0x7ffc6eb8b8c7 - <rustc_trans::LlvmTransCrate as rustc_trans_utils::trans_crate::TransCrate>::trans_crate::h7a21b6007b1d2e8f
  35:     0x7ffc7541cf98 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h970bab471a268779
  36:     0x7ffc753b9c86 - rustc_driver::driver::default_provide_extern::h36c0e3cf673f237b
  37:     0x7ffc7540a96d - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h970bab471a268779
  38:     0x7ffc7540751e - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h970bab471a268779
  39:     0x7ffc75406a63 - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h970bab471a268779
  40:     0x7ffc7536731f - <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt::h75102f2bc4758c9c
  41:     0x7ffc753b2a2b - rustc_driver::driver::compile_input::hfb39c521f477ee8d
  42:     0x7ffc753f6b55 - rustc_driver::run_compiler::h334a80a4b6e644f4
  43:     0x7ffc75350d9d - <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt::h75102f2bc4758c9c
  44:     0x7ffc74fc9f51 - _rust_maybe_catch_panic
  45:     0x7ffc753e9a11 - <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_impl_item::h73b2f332badc5ded
  46:     0x7ffc74fc415b - std::sys::imp::thread::Thread::new::hc076c74f7dafca1e
  47:     0x7ffc8ae78363 - BaseThreadInitThunk

**Comment by retep998** [comment] 2018-01-24 06:17
What is your precise version of Windows and what is the exact CPU model you are using? This sounds very much like a system bug in that `QueryPerformanceCounter` is not returning a monotonic result.

**Comment by williamtcellio** [comment] 2018-01-24 08:12
Windows Server 2016 Datacenter (AWS t2.large)
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

AMD64 CPU 2.6Ghz
8GB Memory

**Comment by saarw** [comment] 2018-01-24 08:13
Windows Server 2016 Datacenter (AWS t2.large)
Major Minor Build Revision
10 0 14393 0

AMD64 CPU 2.6Ghz
8GB Memory

**Comment by saarw** [comment] 2018-01-24 08:28
Restarting the machine got the builds working again, so can no longer reproduce it.

**Comment by retep998** [comment] 2018-01-24 16:41
What was the uptime of the machine last time? It's possible that bug only manifests when the system timer gets high enough.

**Comment by pitdicker** [comment] 2019-01-31 17:58
All related issues where closed by https://github.com/rust-lang/rust/pull/56988, this one probably should also be closed.

**Closed** 2019-01-31 20:56 UTC
Labels: C-bug, I-ICE, O-windows
