### ISSUE TITLE
ICE on turbofish without parens followed by >= .

### ISSUE THREAD

**Issue by ogiekako** [rust-lang/rust#60499] opened 2019-05-03 02:53 UTC
Given main.rs: 
```
fn main() {
    std::mem::size_of::<i32> >= 0
}
```

$ rustc main.rs
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.36.0-nightly (3c3d3c177 2019-04-17) running on x86_64-apple-darwin

**Comment by JohnTitor** [comment] 2019-05-03 05:53
I cannot reproduce ICE on [playground with latest nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=92e83874f914c527f55ad919fa28b22c).

Could you update your local rustc and re-check?

**Comment by ogiekako** [comment] 2019-05-03 08:32
The issue is gone after I updated nightly (to the following version). Thanks!

```
$ rustc --version
rustc 1.36.0-nightly (08bfe1612 2019-05-02)
```

**Comment by jonas-schievink** [comment] 2019-05-03 08:54
Duplicate of https://github.com/rust-lang/rust/issues/60275 and closing as fixed

**Closed by jonas-schievink** 2019-05-03 08:54 UTC
