### ISSUE TITLE
Xous build failure due to naked_asm changes

### ISSUE THREAD

**Issue by xobs** [rust-lang/rust#134403] opened 2024-12-17 02:04 UTC
### Code

I tried this code:

```bash
$ RUST_COMPILER_RT_ROOT="$(pwd)/src/llvm-project/compiler-rt" RUSTFLAGS="-Zforce-unstable-if-unmarked=yes" cargo +nightly build --target riscv32imac-unknown-xous-elf -Zbinary-dep-depinfo --release --features "panic-unwind" --manifest-path "library/sysroot/Cargo.toml"
```

I expected to see this happen: Rust should build libstd for Xous

Instead, this happened: Rust errored out with `could not compile 'unwinding'`:

```
   Compiling unwinding v0.2.4
   Compiling unwind v0.0.0 (/opt/Xous/rust-nightly/rust/library/unwind)
   Compiling panic_unwind v0.0.0 (/opt/Xous/rust-nightly/rust/library/panic_unwind)
error: <inline asm>:11:1: this directive must appear between .cfi_startproc and .cfi_endproc directives
.cfi_def_cfa_offset 0x90
^

error: could not compile `unwinding` (lib)
```

### Version it worked on

It most recently worked on: Rust nightly 2024-12-11

### Version with regression

`rustc --version --verbose`:
```
rustc 1.85.0-nightly (6d9f6ae36 2024-12-16)
binary: rustc
commit-hash: 6d9f6ae36ae1299d6126ba40c15191f7aa3b79d8
commit-date: 2024-12-16
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.5
```

## More information

I have filed an issue [in unwinding](https://github.com/nbdd0121/unwinding/issues/41). This error likely appeared as a result of #128004. However, I am unable to merge PR 41 because CI is failing due to issue #80608.

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by xobs** [comment] 2024-12-17 02:07
I've created this Issue because Xous is now unable to build. There are several factors at play:

* `unwinding` now fails on nightly due to #128004 requiring `.cfi_startproc` and `.cfi_endproc` on all functions
* `unwinding` depends on `#[cfg(target_feature)]` which doesn't work in `--release` mode on RISC-V
* It's unclear whether #128004 is a regression or working as-designed

**Comment by workingjubilee** [comment] 2024-12-17 02:57
> unwinding depends on #[cfg(target_feature)] which doesn't work in --release mode on RISC-V

that should not be the case?

**Comment by xobs** [comment] 2024-12-17 03:00
Sure.

```
#![feature(naked_functions)]

#[naked]
pub extern "C-unwind" fn example() {
    #[cfg(target_feature = "d")]
    unsafe {
        core::arch::naked_asm!("fsd fs0, 0x140(sp)");
    }
}
```

If you build this with `cargo +nightly build --target riscv64gc-unknown-linux-gnu --release` it fails with the following error:

```
error: <inline asm>:6:1: instruction requires the following: 'D' (Double-Precision Floating-Point)
fsd fs0, 0x140(sp)
^
```

Even though it's gated by the `d` flag that should only be active when the `d` target feature is present.

**Comment by Noratrieb** [comment] 2024-12-17 06:21
Amanieu said on the PR that this is intended behavior, so requiring CFI directives iss not an accidental regression. It will need to be fixed in unwinding.

**Comment by jieyouxu** [comment] 2024-12-17 07:19
Reproducing [Amanieu's comment on the PR](https://github.com/rust-lang/rust/pull/128004#issuecomment-2542710979) here:

> The previous behavior was actually context-dependent: the compiler may or may not insert `cfi_startproc` depending on various factors such as whether the panic mode is unwind or abort, whether unwind info is force-enabled, etc.
>
> This makes writing code that uses CFI directives quite brittle and it's a problem I've hit before in libfringe (the predecessor of corosensei). It's much better to let users provide `.cfi_startproc` when they are providing unwind info for a naked function.

**Comment by workingjubilee** [comment] 2024-12-17 09:40
> If you build this with `cargo +nightly build --target riscv64gc-unknown-linux-gnu --release` it fails with the following error:

@xobs Hm. So, the riscv64gc target should have the "d" feature enabled, because "g" includes "d", thus the assembly _should_ be instantiated, and is. The problem isn't with the `cfg(target_feature)`... that's purely handled in Rust syntax, and the error you are getting is from LLVM. It is something more subtle which causes us to not communicate to LLVM the function context _has_ the feature.

**Comment by xobs** [comment] 2024-12-17 13:59
I marked it as a regression because it worked with `nightly-2024-12-12` but fails with `nightly-2024-12-13`:

```sh
cat > test.rs <<EOF
#![feature(naked_functions)]

#[naked]
pub extern "C-unwind" fn example() {
    #[cfg(target_feature = "d")]
    unsafe {
        core::arch::naked_asm!("fsd fs0, 0x140(sp)");
    }
}
EOF

echo -n "Building with 2024-12-12: "
rustc +nightly-2024-12-12 --target riscv64gc-unknown-linux-gnu --crate-type lib -O test.rs
echo "Done"
echo -n "Building with 2024-12-13: "
rustc +nightly-2024-12-13 --target riscv64gc-unknown-linux-gnu --crate-type lib -O test.rs
```

This produces:

```
Building with 2024-12-12: Done
Building with 2024-12-13: error: <inline asm>:6:1: instruction requires the following: 'D' (Double-Precision Floating-Point)
fsd fs0, 0x140(sp)
^
```

What are my options to fix the build for this target? I cannot build `unwinding` which is a prerequisite, due to #80608.

**Comment by Amanieu** [comment] 2024-12-17 14:43
You can work around it by wrapping the assembly code with:

```
".option push",
".option arch, +d",
// your asm here
".option push",
```

**Comment by xobs** [comment] 2024-12-17 16:05
Thank you for that suggestion. That does work, and I'll submit a patch to the unwinding project to add that. It still seems like a regression to me, in the sense that it used to work but now doesn't.

I'll keep this issue open at least until Xous builds again. Once `unwinding` is building again I can submit a PR to libstd to bump the version number to fix the build here.

**Comment by Noratrieb** [comment] 2024-12-17 18:21
The reason it's not labelled as a regression is because we only track regressions for stable features or accidental nightly regressions. Nightly features may break, and in this case a nightly feature had expected breakage.

**Comment by workingjubilee** [comment] 2024-12-17 21:18
@xobs Marking it as a non-regression is not "this is something we don't care about"!

It's "our regression tracking tags are implicitly for the purpose of tracking things we want to actively prevent hitting the next stable/beta release". This results in the oddity of "we would like your target to be fixed as soon as possible but we aren't too worried if the next stable release can't build it because as far as we're concerned only specific nightly releases can".

**Closed** 2024-12-27 06:07 UTC
Labels: T-compiler, A-naked, C-discussion, F-naked_functions, O-xous
