### ISSUE TITLE
ICE: librustc_const_eval/eval.rs: impossible case reached

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#34782] opened 2016-07-12 16:57 UTC
Code:
```rust
fn f() {}
const C: fn() = f;

fn main() {
    match C {
        C => {}
        _ => {}
    }
}
```
ICEs on stable/beta/nightly.

Backtrace:
```
#0  0x000000006e55e767 in rust_panic () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#1  0x000000006e544e3c in std::panicking::rust_panic_with_hook::h9a3925e37821d434 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#2  0x000000006b087e6b in std::panicking::begin_panic::hdf32e6f0d48da313 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_errors-f53fb285.dll
#3  0x000000006b087751 in rustc_errors::Handler::bug::hcfdd44029fe9af2b () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_errors-f53fb285.dll
#4  0x0000000002965a2d in rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::hfbd05ef01f930389 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#5  0x0000000002965798 in rustc::session::opt_span_bug_fmt::he49e515088fa8437 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#6  0x0000000002981581 in rustc::session::bug_fmt::h142e2dae8ab0314e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc-f53fb285.dll
#7  0x0000000063a85805 in rustc_const_eval::eval::const_expr_to_pat::h37a6e58018b5d21d () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_const_eval-f53fb285.dll
#8  0x0000000063abbd97 in _$LT$rustc_const_eval..check_match..StaticInliner$LT$$u27$a$C$$u20$$u27$tcx$GT$$u20$as$u20$rustc..hir..fold..Folder$GT$::fold_pat::hfaafeb51561d9a2c () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_const_eval-f53fb285.dll
#9  0x0000000063abb9fa in _$LT$core..iter..Map$LT$I$C$$u20$F$GT$$u20$as$u20$core..iter..iterator..Iterator$GT$::next::h7f2c43bd38b9e2ec () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_const_eval-f53fb285.dll
#10 0x0000000063ab55c4 in rustc_const_eval::check_match::check_expr::h42c99e18f0a67d4a () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_const_eval-f53fb285.dll
#11 0x0000000063ab97ab in rustc_const_eval::check_match::check_fn::h326077b0e7089c50 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_const_eval-f53fb285.dll
#12 0x0000000063ab9eb1 in rustc_const_eval::check_match::check_crate::h60a3a5b79da92966 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_const_eval-f53fb285.dll
#13 0x000000006ac993fa in rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::he1de538a7584312e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#14 0x000000006ac95d7e in rustc::ty::context::TyCtxt::create_and_enter::he5466411552b055e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#15 0x000000006ac5a76c in rustc_driver::driver::compile_input::h2d1b58b831f06a86 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#16 0x000000006ac4695d in rustc_driver::run_compiler::h833483649bdaa9c3 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#17 0x000000006ac438ca in std::panicking::try::call::hd16aacc09eeeaf9e () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#18 0x000000006e58f849 in __rust_maybe_catch_panic () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#19 0x000000006ac443c4 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hbf614b3f826456b6 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/rustc_driver-f53fb285.dll
#20 0x000000006e57d4da in std::sys::thread::Thread::new::thread_start::h150ac04d84605902 () from /home/we/rust/x86_64-pc-windows-gnu/stage1/bin/std-f53fb285.dll
#21 0x00007ffce27813d2 in KERNEL32!BaseThreadInitThunk () from /c/Windows/system32/KERNEL32.DLL
#22 0x00007ffce39554e4 in ntdll!RtlUserThreadStart () from /c/Windows/SYSTEM32/ntdll.dll
#23 0x0000000000000000 in ?? ()
```

**Comment by arielb1** [comment] 2016-07-17 14:39
duplicate of #34784

**Closed by arielb1** 2016-07-17 14:39 UTC
Labels: I-ICE
