### ISSUE TITLE
Confusing error message when using tuple struct constructor with private fields

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#45481] opened 2017-10-23 20:15 UTC
```rust
mod a {
    pub struct A(u64);
}

fn main() {
    let x: fn(u64) -> a::A = a::A;
}
```

Error message:
```
error[E0603]: tuple struct `A` is private
 --> src/main.rs:6:30
  |
6 |     let x: fn(u64) -> a::A = a::A;
  |                              ^^^^
```

But as you can see in the code, it's not the struct that's private, it's the constructor.

**Comment by jonas-schievink** [comment] 2017-10-23 20:41
Duplicate of https://github.com/rust-lang/rust/issues/39703

**Closed** 2017-10-23 21:10 UTC
