### ISSUE TITLE
rustdoc: Two modules with the same name that are re-exported show up twice with only the contents of the first one

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#43935] opened 2017-08-17 13:43 UTC
https://github.com/sdroege/gstreamer-rs/tree/50a1535771d711b419eee499fb6b7c48d72edd86

Here there is `auto::functions` and `functions` re-exported in lib.rs. The module `functions` appears twice on the main page of the docs, but only shows the content of the first module.

Also functions/etc exported from the second module do not show up anywhere (in the module index for example) unless searching for them explicitly by name.

Also in this case, `auto::functions::*` and `functions::*` are re-exported from lib.rs, but only the contents of the first module show up, e.g. on the main page for functions/structs/etc. When searching explicitly by name, they are found nonetheless.

For rustc, exporting a module name twice causes the module to be merged.

@GuillaumeGomez

**Comment by durka** [comment] 2017-08-19 04:33
> For rustc, exporting a module name twice causes the module to be merged.

Whoa. Is that an intended feature??? What if there are items with the same name after merging?

**Comment by sdroege** [comment] 2017-08-19 07:19
Probably nothing until you try to use it, then you need to specify which of the two by giving an unambiguous path. It's probably not handled differently than importing things into the current module's namespace, where you can also have conflicts.

Seems consistent to me, and useful, even if maybe not intentional.

FWIW, in my case it is:
```rust
mod auto;
pub use auto::*; // which has a functions sub-module
pub mod functions;
```

If that was forbidden, adding sub-modules would become a potentially breaking API change as it could cause a conflict in e.g. a completely different crate that re-exports things like above. That would seem undesirable. Just like adding other items to a module can cause conflicts like this, it shouldn't be a problem unless it's actually used, for the same reason. You wouldn't be able to add anything to your modules anymore without potentially breaking other people's code.

**Comment by petrochenkov** [comment] 2017-08-19 11:16
>Is that an intended feature?

[Yes.](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md)

"exporting a module name twice causes the module to be merged" is a bit weird wording for this though.
"Non-globs shadow globs" and "conflicts glob vs glob are not reported eagerly" would describe the situation better.

**Comment by jyn514** [comment] 2021-04-27 15:39
Duplicate of https://github.com/rust-lang/rust/issues/83375 (this was reported earlier, but doesn't have an MCVE).

**Closed by jyn514** 2021-04-27 15:39 UTC
Labels: A-rustdoc, C-bug, T-dev-tools
