### ISSUE TITLE
Compiler: option to show only the first error

### ISSUE THREAD

**Issue by tredoe** [rust-lang/rust#34225] opened 2016-06-11 16:46 UTC
The compiler shows all errors together, but it could have an option to show only the first or first errors.

Because the compiler shows enough information (which is great) about every error, the console screen shows a lot of information and you have to upload until find the first error.

**Comment by Mark-Simulacrum** [comment] 2017-07-25 15:53
Duplicate of https://github.com/rust-lang/rust/issues/27189.

**Closed by Mark-Simulacrum** 2017-07-25 15:53 UTC
Labels: T-dev-tools

**Comment by kirhgoff** [comment] 2019-04-09 11:41
What happened? The other one #27189 is closed like a duplicate to this one. It is a very common workflow, a lot of people voted to have that implement, can you add some comments?
