### ISSUE TITLE
breaking change on stable: handling of block doc comments

### ISSUE THREAD

**Issue by yaahc** [rust-lang/rust#83982] opened 2021-04-07 20:01 UTC
This issue was discovered in this PR on displaydoc https://github.com/yaahc/displaydoc/pull/22#issuecomment-797668433 and previously reported in this zulip thread https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/block.20doc.20comments.20broken.3F.

To summarize the issue, previously if you had a multiple line block doc comment that had asterisks on the start of each line the asterisks were stripped by rustc prior to them being passed into proc macros. After the change the asterisks are left in and must be removed by the author of a proc macro.

### Code

Based on this PR where we worked around the issue:

* https://github.com/yaahc/displaydoc/pull/23

I tried this code in a proc macro:

```rust
    /**
     * line 1
     *
     * line 2
     */
    struct Foo;
```

I expected to see as the content of the `#[doc]` attribute:

`"line 1\n\n line2"`

Instead, I see this as the content of the attribute:

```"* line 1\n     *\n     * line 2"```

**note**: github isn't displaying this well but this includes all leading white space as well, so a newline, five spaces, then an astrisk, repeat.

### Version it worked on

It most recently worked on: 1.46

### Version with regression

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```
</p>
</details>

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by jyn514** [comment] 2021-04-07 20:27
Hmm, so it turns out this is specific to proc-macros, it shows up fine in the docs: 
![image](https://user-images.githubusercontent.com/23638587/113929521-2c6f3c80-97be-11eb-8fa9-188b653fcd5a.png)
So I don't think this is actually related to rustdoc.

cc @Aaron1011 @petrochenkov does this change look familiar?

**Comment by ehuss** [comment] 2021-04-07 21:34
I believe this was changed as part of #74627.

**Comment by camelid** [comment] 2021-04-08 00:56
FWIW, #80545 was prioritized as `P-medium`.

**Comment by camelid** [comment] 2021-04-08 00:58
Hmm, no WG-prioritization stream was created for this issue. I'll try re-applying the label:
@rustbot label: -I-prioritize +I-prioritize

**Comment by jyn514** [comment] 2021-04-08 02:05
Closing as a duplicate of https://github.com/rust-lang/rust/issues/80545.

**Closed by jyn514** 2021-04-08 02:05 UTC
Labels: A-proc-macros, I-prioritize, T-compiler, regression-from-stable-to-stable
