### ISSUE TITLE
[1.38] `#[bench]` accepted on stable but not beta

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#63798] opened 2019-08-22 00:41 UTC
Initially reported by @e-oz [here](https://github.com/rust-lang/rust/issues/50297#issuecomment-523657376).

[[playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=b006497caba8892a0350a517d49c7a2d)]

```rust
fn main() {
    println!("Hello, world!");
}

#[bench]
fn example() {}
```

On stable, you're allowed to _define_ `#[bench]` tests in your library, even if calling them requires nightly. This broke at least one stable user, so we should at least consider continuing to ignore `#[bench]`-annotated functions when not run via `cargo bench`.

Is there some way to get a crater run to determine which libraries are using `#[bench]` in an otherwise stable crate, so we can suggest that they move benchmarks into a dedicated folder?

**Comment by djrenren** [comment] 2019-08-22 02:32
I think it's related to this: https://github.com/rust-lang/rust/issues/62048

Unsure how it got marked stable in the first place.

**Comment by ehuss** [comment] 2019-08-22 02:47
`[bench]` was unstabilized in #62507.  A crater run was done during that PR, the conclusion was written [here](https://github.com/rust-lang/rust/pull/62507#issuecomment-513872169).  I think it was deemed unusual enough to proceed.
cc @petrochenkov

**Comment by petrochenkov** [comment] 2019-08-22 09:00
Reverting the unstabilization and making a beta backport is always an option, it's a one line change.

Complaints filed so far:
https://github.com/rust-lang/rust/pull/62507#issuecomment-517719452 - `route-recognizer` broke, apparently it's used as a dependency somewhat commonly.
https://github.com/rust-lang/rust/issues/50297#issuecomment-521660469 and below - unspecified dependency broke, may be the case of `route-recognizer` as well.
https://github.com/iron/iron/issues/613 - `iron/router` doesn't build, again cause by `route-recognizer`

`route-recognizer` was fixed in https://github.com/rustasync/route-recognizer/pull/25 and a new patch version was published.
@e-oz does this fix your use case?

**Comment by Centril** [comment] 2019-08-22 12:35
I don't think we should re-stabilize especially given that some folks have already migrated.
(The one line change is not the issue, but forever committing to a stable `#[bench]`.)

**Comment by CAD97** [comment] 2019-08-22 13:23
I wish we had unsurpressable future-compat warnings so a cycle's worth of just a future-compat warning for `#[bench]` would actually be helpful for catching any other libraries mistakenly using (because it was stable that way) `#[bench]` as `#[cfg(test)] #[bench]`.

Because we don't, I assume said grace period wouldn't help find any remaining uses, just delay the errorification.

So I guess the question is: `#[bench]` has been (mistakenly?) stable as `#[cfg(false)]` for standard builds since Rust 1.0. Is that enough to force us into supporting it for nominal stability's sake, or do we consider it a long-standing low priority bug that just got fixed?

**Comment by pietroalbini** [comment] 2019-08-22 13:27
[Accidental stabilizations are not part of our stability guarantee](https://github.com/rust-lang/rfcs/pull/2405). Still, if possible I think we should try to avoid breaking crates.

**Comment by Centril** [comment] 2019-08-22 13:27
> I wish we had unsurpressable future-compat warnings so a cycle's worth of just a future-compat warning for `#[bench]` would actually be helpful for catching any other libraries mistakenly using (because it was stable that way) `#[bench]` as `#[cfg(test)] #[bench]`.

Implemented in https://github.com/rust-lang/rust/pull/59658; I'll be picking this up shortly to address the concerns raised there re. spam.

**Comment by petrochenkov** [comment] 2019-08-22 13:32
@CAD97 
If I'm reading your comment correctly, it has some misunderstanding.
`#[cfg(false)] #[bench]` *still* can be used on stable because `bench` is unconfigured before use.

What was unstabilized is the actual use of `bench`.
```rust
#[bench]
fn foo() {}
```
It previously didn't compile in `--test` mode due to requiring unstable things in the `fn` signature, but without `--test` it compile successfully and expanded into nothing (empty token stream / AST piece).

**Comment by petrochenkov** [comment] 2019-08-22 13:35
I'm not sure the back compat warning is a good solution since `#[bench]` doesn't seem to be deprecated in any way, on the contrary, it's going for stabilization with custom test frameworks making progress.

**Comment by CAD97** [comment] 2019-08-22 13:44
@petrochenkov That's just a wording issue. I meant that using `#[bench]` had the effect of using `#[cfg(test)] #[bench]`.

**Comment by e-oz** [comment] 2019-08-22 14:18
@petrochenkov 
I can't update version of `route-recognizer` because requirements of version are written not in mine Config.toml - it's dependency of `iron/router` (and updating `iron` version means rewriting my project from scratch, it's few months of work without any noticeable result).

**Comment by CAD97** [comment] 2019-08-22 14:22
@e-oz The new version of `route-recognizer` is semver-compatible with every other published version. A `cargo update` _should_ re-resolve your lock file to use the latest version of `route-recognizer`.

**Comment by e-oz** [comment] 2019-08-22 14:29
@CAD97 
this worked, thanks a lot!
`rm -f Cargo.lock && cargo update && cargo build`

Hope it will not be required after each rust update :)

**Comment by fbstj** [comment] 2019-08-22 14:53
@e-oz check out the [`--package`](https://doc.rust-lang.org/cargo/commands/cargo-update.html) option of `cargo update` and run something like `cargo update --package route-recognizer` to only update that package.

**Comment by e-oz** [comment] 2019-08-22 14:56
@fbstj thank you very much! Works great.

**Comment by petrochenkov** [comment] 2019-08-24 22:13
Despite the small number of root regressions, there seems to be a huge amount of indirect breakage - https://github.com/rust-lang/rust/issues/63628#issuecomment-524584111, we cannot leave this as is.

If someone wants to implement a lint reporting `#[bench]` without `feature(test)`, that would be great.
Reverting the unstabilization would be the simplest solution.

**Comment by Centril** [comment] 2019-08-29 14:38
If we are "fixing" this (allowing `#[bench]` on stable), then I think a warning **_must_** also be there... otherwise we are just stabilizing the feature.

**Comment by CAD97** [comment] 2019-08-30 13:03
At the _very_ least, the issue that it's pointing at should have a note about the destabilization. We can fix that now to help avoid future confusion: @Centril, do you mind editing the OP of #50297 to add a clear note about such?

**Comment by petrochenkov** [comment] 2019-09-01 14:08
Fixed in https://github.com/rust-lang/rust/pull/64066.

**Closed** 2019-09-08 02:12 UTC
Labels: A-libtest, A-stability, P-high, T-dev-tools, T-lang, regression-from-stable-to-beta
