### ISSUE TITLE
Is there a gentler way to land the assert_matches macro?

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#82913] opened 2021-03-08 23:03 UTC
As a user I'm really excited for `std::assert_matches!`, but I'm a little worried about the level of breakage it introduces and I'm hoping to discuss possible paths forward.

The Fuchsia roll to update rustc is currently blocked by [ambiguous macro resolution errors](https://github.com/rust-lang/rust/pull/82770#issuecomment-792999294) with code that glob-imports `matches::assert_matches!`. It seems that a locally defined glob import does not take precedence over macros defined in std.

This implies a workaround of changing all the glob imports to `use matches::assert_matches`, but this does not account for submodules which `use super::*;`. Unfortunately it seems that the [test_case](https://docs.rs/test-case/1.1.0/test_case/) crate wraps the function body in a submodule and adds a `use super::*`to the new module.

What this means in practice is that every function using the test_case crate must have an explicit import added or have the macro referenced via a fully qualified name. AIUI this change counts as an acceptable breakage and so I'm still putting together a diff which will resolve all of our roll blockers.

What I'm wondering though is whether knowing about this source of breakage offers a path to a smoother release. If so, we could revert the change and prepare to roll it out more gently.

Two options that came up in private discussions:

1. remove assert_matches from the prelude until the 2021 edition
  * this wouldn't make it immediately available but it would prevent the breakage
2. make local glob imports take precedence over std/prelude macros
  * this would make it immediately available but may not be possible within language constraints

Any other suggestions for how to make this change less disruptive? cc @m-ou-se @tmandry @joshtriplett

**Comment by estebank** [comment] 2021-03-08 23:31
cc @petrochenkov for resolution

**Comment by anp** [comment] 2021-03-08 23:43
I've prepared a [change](https://fuchsia-review.googlesource.com/c/fuchsia/+/497979) which should allow us to update to the current nightly and might give a sense of the frequency within our codebase (more than I'd expect but less than I'd feared). I'm not sure to what extent that holds for the rest of the ecosystem, maybe a crater run would be useful to determine the severity here.

**Comment by tmandry** [comment] 2021-03-15 20:47
This was a big enough breakage for Fuchsia (and the error messages are confusing enough) that I think a crater run is warranted.

I'm not sure if the release team wants to weigh in at this point or not, but nominating for discussion in the release team meeting.

@rustbot label: +T-release +I-nominated

**Comment by joshtriplett** [comment] 2021-03-17 20:43
We discussed this in today's @rust-lang/libs meeting.

We'd propose the following:

- Remove `assert_matches!` from the prelude, and only add it in a submodule. (Hopefully we don't have to extensively bikeshed the path to this.) People who want to use it can import it, for now.
- Consider adding `assert_matches!` to the prelude in the next edition.

**Comment by Mark-Simulacrum** [comment] 2021-03-17 21:24
(I think the libs team decision makes this a bit moot, but perhaps not)

I think for unexpected, extensive breakage it usually makes sense to revert and perhaps reland with no changes, just giving folks a chance to evaluate the breakage - potentially via crater. I think the compiler team has been moving towards reverting eagerly, too, though there's not been set policy yet, and I think there's not quite consensus.

I'll leave this nominated in case others on the release team have thoughts and bring it up in our meeting too.

**Comment by Mark-Simulacrum** [comment] 2021-04-12 19:12
It looks like the removal here hasn't happened, and has now hit beta. Tagging as a beta regression.

**Comment by Mark-Simulacrum** [comment] 2021-04-30 17:43
https://github.com/rust-lang/rust/pull/84759 takes care of the regression in beta (1.52), but we'll need a similar revert for 1.53 (branching ~today), and a proper fix for 1.54.

**Comment by pietroalbini** [comment] 2021-05-04 15:14
`assert_matches` has been reverted on the upcoming 1.53.0 beta too. Moving this to a nightly 1.54.0 regression.

**Comment by m-ou-se** [comment] 2021-06-04 09:35
>     * Remove `assert_matches!` from the prelude, and only add it in a submodule. (Hopefully we don't have to extensively bikeshed the path to this.) People who want to use it can import it, for now.
> 
>     * Consider adding `assert_matches!` to the prelude in the next edition.

I'm not sure if this is a good way forward. We could definitely move it into a submodule, but making this an edition change (including a migration lint etc.) seems like too much effort for the small breakage this caused.

Having `assert!()` and `assert_eq!()` etc. always available, but `assert_matches!()` only after importing it with `use std::bikeshed::assert_matches` doesn't seem great.

As Mark suggested above, we could do the same as we did for `usize::BITS`, and re-land it now that hopefully most of the breakage is fixed in the ecosystem.

ping @rust-lang/libs for opinions

**Comment by BurntSushi** [comment] 2021-06-04 10:00
Landing this despite the breakage feels not so great to me. Not horrible. But not great. In particular, it looks like the root cause to the breakage is import behavior. Which I think also in turn means that adding any new macro to the prelude could potentially result in this sort of breakage, which seems really quite unfortunate. (Did this happen when the `matches` macro was added?) Does the @rust-lang/lang team have any opinions here? Is it feasible to fix the import behavior? Otherwise, the general migration path for a macro living in the ecosystem to a macro living in the prelude seems quite fraught.

With that said, can we do another crater run to see if the breakage has actually been fixed? If it has, then that might indeed be the right way to go here. But I'm still worried about the longer term problem with imports.

> I'm not sure if this is a good way forward. We could definitely move it into a submodule, but making this an edition change (including a migration lint etc.) seems like too much effort for the small breakage this caused.
> 
> Having `assert!()` and `assert_eq!()` etc. always available, but `assert_matches!()` only after importing it with `use std::bikeshed::assert_matches` doesn't seem great.

Yeah I hear this. Having to import `assert_matches` kinda stinks. I don't have a good idea of how much work doing this via an edition is. We do have the upside that Rust 2021 is around the corner, so an explicit import wouldn't be needed for too long.

**Comment by SimonSapin** [comment] 2021-06-04 10:05
> In particular, it looks like the root cause to the breakage is import behavior.

Indeed. Maybe that behavior could be fixed? Quoting myself from https://github.com/SimonSapin/rust-std-candidates/issues/22#issuecomment-793086963:

> I’ve managed to reproduce this.
> 
> ```
> error[E0659]: `assert_matches` is ambiguous (glob import vs any other name from outer scope during import/macro resolution)
> ```
> 
> It’s unfortunate that the compiler does not resolve this ambiguity automatically (favoring the explicit `use` over the prelude).

**Comment by m-ou-se** [comment] 2021-06-04 12:00
> (Did this happen when the `matches` macro was added?)

Yes: https://github.com/rust-lang/rust/issues/66518

> Is it feasible to fix the import behavior? Otherwise, the general migration path for a macro living in the ecosystem to a macro living in the prelude seems quite fraught.

Apparetly that's tricky: https://github.com/rust-lang/rust/issues/65721#issuecomment-546441859

> I don't have a good idea of how much work doing this via an edition is. We do have the upside that Rust 2021 is around the corner, so an explicit import wouldn't be needed for too long.

It'd be pretty much trivial to add it only in `prelude::rust_2021`. But we made a promise to the world to detect and automatically fix future edition-incompatible code, and that part is a bit harder. And we technically already froze the set of changes for new edition, although I guess nobody would complain too loudly if we still sneak this in. The problem would still remain for any macros we add in the future though.

**Comment by nikomatsakis** [comment] 2021-06-04 16:39
> Having assert!() and assert_eq!() etc. always available, but assert_matches!() only after importing it with use std::bikeshed::assert_matches doesn't seem great.

@m-ou-se I'm confused by this -- if we did it in an edition, wouldn't all 3 be available? What makes this so hard to do in an edition? (I haven't thought about what migration is required)

**Comment by m-ou-se** [comment] 2021-06-04 16:46
Oh, the comment about `std::bikeshed::assert_matches` applies to Rust 2015 and 2018. (And Rust 2021 with #[no_prelude] i guess, since the others are imported through #[macro_use] and not the prelude.) What makes me reluctant to do it in the edition is specifically the migration. We'd need to detect cases where a macro with the same name is used that was imported through a glob import. It'd be a bit late to start working on a new migration lint now, since we're already supposed to be done with those by now.

And doing this edition trick won't work the next time when we run into this problem (without waiting three years). So I'd prefer some conslusion that we can re-use when this happens again in a few months or so.

**Comment by m-ou-se** [comment] 2021-06-14 10:03
Update: We don't have a solution here yet, and nightly is now at 1.55. So if we want to avoid the breakage, we need a backport again (to 1.54).

**Comment by m-ou-se** [comment] 2021-06-23 20:21
We discussed this today, and concluded that our best options here are either:

1. Just let it land on stable, and break a few things.
2. Only add it to the 2021 prelude, but without migration lint. We do normally require migration lints for edition changes, but this option is strictly less breaking than option 1.

To be discussed in the edition meeting on monday.

**Comment by m-ou-se** [comment] 2021-06-28 19:17
We discussed this in the edition meeting, and weren't too enthusiastic about making this an edition change without also adding an automatic migration for it. Breakage on upgrading to Rust 2021 without automatic migration is a reason for not upgrading at all, which we want to avoid. Adding a migration lint for this is also not easy.

@nikomatsakis encouraged a discussion of this general issue (macros from the std root/prelude breaking things) in a language meeting to see if something can be done about this problem. (As was suggested by @BurntSushi above.)

For now, we should move this macro to e.g. `std::assert::assert_matches` or something and backport that change to beta.

**Comment by Mark-Simulacrum** [comment] 2021-07-15 22:12
Going to reopen to track the beta backport.

**Comment by pietroalbini** [comment] 2021-07-26 08:52
Beta backport landed. Closing this.

**Closed by pietroalbini** 2021-07-26 08:52 UTC
Labels: A-macros, A-resolve, T-libs, T-libs-api, T-release, regression-from-stable-to-beta
