### ISSUE TITLE
Compiler crash on trying to return Self::Output from function using const generics.

### ISSUE THREAD

**Issue by Oli-Ar** [rust-lang/rust#84631] opened 2021-04-27 20:54 UTC
### Code

The compiler crashes on this function, specifically with the return type being `Self::Output`

```Rust
impl<T, const X: usize, const Y: usize> Mul<T> for Matrix<T, X, Y>
where
    T: Data + Mul<Output = T> + From<i32>,
    [T; X * Y]: Sized,
{
    type Output = Self;
    fn mul(self, rhs: T) -> Self::Output {
        let mut dat_copy = [0.into(); X * Y];
        for (i, e) in self.dat.iter().enumerate() {
            dat_copy[i] = rhs * *e;
        }
        Matrix { dat: dat_copy }
    }
}
```

I can get the code to compile by changing the return type of `mul()` to be `Matrix<T, X, Y>`. I've tested changing the value of `Self::Output` but the error doesn't change until I return something which isn't `Self::Output`.

<details><summary><strong>Matrix struct definition</strong></summary>
<p>

```Rust
#[derive(Debug, Eq, PartialEq, Clone, Copy)]
pub struct Matrix<D: Data, const X: usize, const Y: usize>
where
    [D; X * Y]: Sized,
{
    dat: [D; X * Y],
}
```

<p></details>

<details><summary><strong>Data trait alias</strong></summary>
<p>

```Rust
pub trait Data = Into<f64> + std::fmt::Display + std::fmt::Debug + Copy;
```

<p></details>

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (07194ffcd 2021-02-10)
binary: rustc
commit-hash: 07194ffcd25b0871ce560b9f702e52db27ac9f77
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### Error output

```
query stack during panic:
#0 [normalize_generic_arg_after_erasing_regions] normalizing `<matrix::matrix::Matrix<T, X, Y> as std::ops::Mul<T>>::Output`
end of query stack
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: rustc_errors::HandlerInner::bug
   3: rustc_errors::Handler::bug
   4: rustc_middle::ty::context::tls::with_opt
   5: rustc_middle::util::bug::opt_span_bug_fmt
   6: rustc_middle::util::bug::bug_fmt
   7: rustc_infer::infer::InferCtxtBuilder::enter
   8: rustc_traits::normalize_erasing_regions::normalize_generic_arg_after_erasing_regions
   9: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::force_query_with_job
  13: rustc_query_system::query::plumbing::get_query_impl
  14: rustc_middle::ty::util::fold_list
  15: rustc_middle::ty::layout::<impl rustc_middle::ty::instance::Instance>::fn_sig_for_fn_abi
  16: rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn
  17: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  18: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  19: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  20: rustc_codegen_llvm::base::compile_codegen_unit
  21: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  22: rustc_interface::passes::QueryContext::enter
  23: rustc_interface::queries::Queries::ongoing_codegen
  24: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  25: rustc_span::with_source_map
  26: rustc_interface::interface::create_compiler_and_run
  27: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by 756445638** [comment] 2021-04-28 04:25
what is Data struct Definition?

**Comment by Oli-Ar** [comment] 2021-04-28 06:57
It is this trait alias:
```Rust
pub trait Data = Into<f64> + std::fmt::Display + std::fmt::Debug + Copy;
```
I've updated the original issue too to show this

**Comment by BoxyUwU** [comment] 2021-04-28 12:31
having trouble reproducing this, could you make an example on the rust playground that gives this ICE?

**Comment by Oli-Ar** [comment] 2021-04-29 18:52
> having trouble reproducing this, could you make an example on the rust playground that gives this ICE?

I have now also tried to reproduce this in rust playground but have been unable to. However, I can verify this issue is not exclusive to my machine as I get the same crash on both my desktop and laptop, and my friend also gets the crash on his machine. 

I can post the entire project in which the code causes the crash if that could be helpful?

**Comment by BoxyUwU** [comment] 2021-04-29 20:58
A link to the project could work too yea

**Comment by Oli-Ar** [comment] 2021-04-30 17:21
[Here](https://github.com/Oli-Ar/compiler-bug) is the repository with the bug showcased. To see the bug use `cargo test`.

**Comment by BoxyUwU** [comment] 2021-04-30 17:56
This ICE is caused by not having `#![feature(const_evaluatable_checked, const_generics)]` in the tests crate when its enabled in the `matrix` crate. if you add the feature gates to your test file it should be fixed:
```
#![feature(const_generics, const_evaluatable_checked)]

use matrix::matrix::Matrix;

const X: usize = 3;
const Y: usize = 3;

#[test]
fn scalar() {
    let matrix = Matrix::<i32, X, Y>::new([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);
    let matrix_scalar_double = Matrix::<i32, X, Y>::new([[2, 4, 6], [8, 10, 12], [14, 16, 18]]);
    let matrix_mul = matrix * 2;
    assert_eq!(matrix_mul, matrix_scalar_double);
}

```

**Comment by Oli-Ar** [comment] 2021-04-30 18:16
That was it. Thank you! Should I close the issue?

**Comment by BoxyUwU** [comment] 2021-04-30 20:22
should be fine to close this :)

**Closed** 2021-04-30 21:07 UTC
Labels: C-bug, I-ICE, T-compiler
