### ISSUE TITLE
Unused feature warning doesn't show for non-lib features

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#26135] opened 2015-06-09 19:23 UTC
Features like `thread_local` or `unsafe_no_drop_flag` or `box_syntax`, which are needed to use language features, are not caught by the `unused_feature` lint.

Perhaps we should add some more robust usage-checking?

**Comment by Manishearth** [comment] 2015-06-09 19:23
cc @brson @Gankro

**Comment by brson** [comment] 2015-06-09 22:37
This is a known limitation of the current implementation. Should probably be fixed.

**Comment by steveklabnik** [comment] 2017-01-03 20:05
Triage: no changes I'm aware of.

**Comment by sanmai-NL** [comment] 2017-05-23 13:38
Duplicate of #23528, @Mark-Simulacrum?

**Comment by Mark-Simulacrum** [comment] 2017-05-23 13:58
Yep! Thanks.

**Closed by Mark-Simulacrum** 2017-05-23 13:58 UTC
Labels: A-stability, I-enhancement
