### ISSUE TITLE
Too hard to find methods available on `str`

### ISSUE THREAD

**Issue by Valloric** [rust-lang/rust#24097] opened 2015-04-05 20:31 UTC
I've been away from Rust code for a while, and here's how I went looking for methods on `str`:

1. Went to Rust homepage, clicked on beta [API docs](http://doc.rust-lang.org/1.0.0-beta/std/).
2. In the search bar, typed in `str`.
3. Clicked on first result, `std::str`.
4. Found no methods for `str`. Only structs are available, no stable traits that might have the methods.
5. Randomly clicked on [`Chars` struct](http://doc.rust-lang.org/1.0.0-beta/std/str/struct.Chars.html). Page says "Created with the method .chars()."
6. Typed `chars` into the search box. Lots of results, found a method `core::str::StrExt::chars`. Saw that `StrExt` was unstable, and I only want stable APIs so closed the tab.
7. Clicked around some more, gave up, asked on `#rust` IRC about `str` methods.
8. Was given link to [Primitive type str](http://doc.rust-lang.org/1.0.0-beta/std/primitive.str.html).

Hopefully we'll have a better experience for the flood of newcomers at 1.0.

@steveklabnik

**Comment by cmr** [comment] 2015-04-05 21:31
Closing as dupe of https://github.com/rust-lang/rust/issues/23511

**Comment by cmr** [comment] 2015-04-05 21:32
(Thanks for the great bug report, though)

**Closed by cmr** 2015-04-05 21:31 UTC
Labels: A-rustdoc
