### ISSUE TITLE
Failed to process buffered lint

### ISSUE THREAD

**Issue by Eligioo** [rust-lang/rust#81958] opened 2021-02-10 08:31 UTC
### Code
I ran `cargo check` on the following Rust project: https://github.com/nimiq/core-rs-albatross/tree/e7205ccd6fc9a481018dd01a2395f13a84b0d3bd, which tries to compile the `libp2p-mdns` crate.

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
cargo check
   Compiling nimiq-jsonrpc-server v0.1.0 (https://github.com/nimiq/jsonrpc.git#1d17aa26)
    Checking crypto-primitives v0.1.0 (https://github.com/nimiq/zexe?branch=nimiq#d364f586)
   Compiling nimiq-jsonrpc-client v0.1.0 (https://github.com/nimiq/jsonrpc.git#1d17aa26)
    Checking libp2p-kad v0.28.0
    Checking libp2p-mdns v0.28.0
   Compiling libp2p-floodsub v0.27.0
error: internal compiler error: failed to process buffered lint here
   --> /home/stefan/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.28.0/src/service.rs:293:37
    |
293 |                         Err(err) => log::error!("if watch returned an error: {}", err),
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `libp2p-mdns`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: failed to process buffered lint here
   --> /home/stefan/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.28.0/src/service.rs:293:37
    |
293 |                         Err(err) => log::error!("if watch returned an error: {}", err),
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run

```

</p>
</details>

**Comment by ivan770** [comment] 2021-02-10 09:08
Duplicate of #81531

**Closed** 2021-02-10 09:15 UTC
Labels: C-bug, I-ICE, T-compiler
