### ISSUE TITLE
unused_variable: applying suggestion causes compiler error

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#104904] opened 2022-11-25 18:14 UTC
Given the following code: 

```rust
fn main() {
    let res = { if true { return; } else { return; }; }; if res {}
}

```

The current output is:

```
warning: unreachable expression
 --> src/main.rs:2:58
  |
2 |     let res = { if true { return; } else { return; }; }; if res {}
  |                           ------                         ^^^^^^^^^ unreachable expression
  |                           |
  |                           any code following this expression is unreachable
  |
  = note: `#[warn(unreachable_code)]` on by default

warning: unused variable: `res`
 --> src/main.rs:2:9
  |
2 |     let res = { if true { return; } else { return; }; }; if res {}
  |         ^^^ help: if this is intentional, prefix it with an underscore: `_res`
  |
```
The problem is while the `if res {}` at the end is technically unreachable, it will still cause a compiler error if we auto-apply the `let res = ..` -> `let _res = ...`  with cargo fix.

Could we somehow make the "remove ` if res {}`" suggestion apply automatically so that it is performed before the `res` to `_res` rename?

**Comment by camsteffen** [comment] 2022-11-25 18:46
Related: https://internals.rust-lang.org/t/should-dead-code-count-toward-var-liveness/16996

**Comment by ehuss** [comment] 2023-05-06 20:08
I'm going to close as a duplicate of #104904.

**Closed by ehuss** 2023-05-06 20:08 UTC
Labels: A-diagnostics, T-compiler

**Comment by matthiaskrgr** [comment] 2023-05-06 20:53
@ehuss this IS #104904 :sweat_smile:

**Comment by ehuss** [comment] 2023-05-06 22:27
Sorry, copy/paste error. :smile: It should have been #107734.
