### ISSUE TITLE
could not find native static library `crypto` on ubuntu

### ISSUE THREAD

**Issue by richardchey** [rust-lang/rust#66861] opened 2019-11-29 08:06 UTC
rust: 1.39.0
host: Ubuntu 18.04.3 LTS

I have installed the "libssl-dev", but it still got the error "could not find native static library `crypto`". 
and if i change it to `cargo:rustc-link-lib=crypto` or create a bin crate(rename `lib.rs` to `main.rs`) using the same code, it will be ok.

build.rs: 
```rust
fn main() {
    println!("cargo:rustc-link-lib=static=crypto");
}
```

lib.rs:
```rust
extern "C" {
    pub fn ERR_get_error() -> ::std::os::raw::c_ulong;
}

fn main() {
    let err: u64;
    unsafe {
        err = ERR_get_error() as u64;
    }
    println!("study-main: {:?}", err);
}
```

**Comment by csmoe** [comment] 2019-11-29 08:35
```rust
fn main() {
    println!("cargo:rustc-link-search=<crypto-path>");
    println!("cargo:rustc-link-lib=static=crypto");
}
```
might help here, and this issue belongs to https://github.com/rust-lang/cargo , if you this doesn't work, please file an issue there.

**Comment by richardchey** [comment] 2019-12-05 09:59
your code can solve the problem , but it isn't my attention. my real problem is why this error occurred  only in this case.

**Comment by richardchey** [comment] 2019-12-09 01:50
The problem has been figured out in https://github.com/rust-lang/cargo/issues/7639. Now, the key is that rustc linking a static library in different way when dealing with binaries and libraries. It seems to be inconsonant. Will you make any changes for this?

**Comment by Enselic** [comment] 2023-12-10 10:40
Triage: Closing as there seems to be nothing actionable here with regards to the original bug. The proposed inconsistency is better handled in a separate issue with clear step-by-step instructions on how to reproduce.

**Closed by Enselic** 2023-12-10 10:40 UTC
Labels: A-linkage, T-compiler, C-bug
