### ISSUE TITLE
Iffy document generation with crates and versioning

### ISSUE THREAD

**Issue by mzap** [rust-lang/rust#23663] opened 2015-03-24 17:13 UTC
There is a problem with the doc generation when generating it for external crates and coupled with versioning. As an example, the term-related items will 404 on this search http://doc.rust-lang.org/std/index.html?search=term because it lacks the /nightly/ part.

**Comment by steveklabnik** [comment] 2015-03-24 17:17
Oh, this is a duplicate of https://github.com/rust-lang/rust/issues/22168 :(

**Closed by steveklabnik** 2015-03-24 17:17 UTC
Labels: A-rustdoc
