### ISSUE TITLE
statics in closures returned using impl Trait: undefined symbols

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#40839] opened 2017-03-26 15:55 UTC
I have Code like the following:

```rust
impl Docker {
    // #[inline] // marking this as inline fixes the problem
    pub fn new(handle: &Handle) -> impl Future<Item = Docker, Error = io::Error> {
        let client = hyper::Client::new(&handle);

        let docker = Docker {
            client: client,
        };

        // docker.version() returns a `impl Future`
        docker.version().map(|version| {
            println!("connected to docker {:?}", version);
            docker
        })
    }
}
```

When I'm calling `Docker::new` from another crate I get the following linker error:

```
  = note: Undefined symbols for architecture x86_64:
            "docker_run::Docker::new::_$u7b$$u7b$closure$u7d$$u7d$::__STATIC_FMTSTR::h39c0733cea565f9a", referenced from:
                docker_run::Docker::new::_$u7b$$u7b$closure$u7d$$u7d$::h260aa00d780d89c7 in docker_run-8e8c301168781829.0.o
```

Related symbols from the linked rlib:

```
$ objdump -t .../libdocker_run-b777eed0df4fdfc5.rlib | grep -F '6Docker3new28_$u7b$$u7b$closure$'
00000000000d5950 l       0e SECT   01 0000 [.text] __ZN10docker_run6Docker3new28_$u7b$$u7b$closure$u7d$$u7d$17h2a2bb6ebe6df45e4E
00000000000f96a0 l       0e SECT   05 0000 [.const_data] __ZN10docker_run6Docker3new28_$u7b$$u7b$closure$u7d$$u7d$15__STATIC_FMTSTR17h39c0733cea565f9aE
```

And from the object file in question:

```
objdump -t .../docker_run-8e8c301168781829.0.o  | grep -F '6Docker3new28_$u7b$$u7b$closure$'
00000000000033b0 l       0e SECT   01 0000 [.text] __ZN10docker_run6Docker3new28_$u7b$$u7b$closure$u7d$$u7d$17h260aa00d780d89c7E
0000000000000000 g       01 UND    00 0000 __ZN10docker_run6Docker3new28_$u7b$$u7b$closure$u7d$$u7d$15__STATIC_FMTSTR17h39c0733cea565f9aE
```

I hope this is enough for someone to get an idea, where the problem might be, other wise I can see about publishing a smaller testcase.

cc @michaelwoerister I guess this is related to the collector, which I believe is your area of expertise.

**Comment by oli-obk** [comment] 2017-03-27 09:28
Probably needs another `||` on this check: https://github.com/rust-lang/rust/blob/7846dbe0c8de17f59cdfc3d2b914d58faad7eade/src/librustc_metadata/encoder.rs#L566

**Comment by michaelwoerister** [comment] 2017-03-27 14:57
Yes, this could well be the collector not finding the instance.

Nominated for priority assignment.

**Comment by pnkfelix** [comment] 2017-03-30 20:26
@TimNN marking as P-medium under the assumption that this is relatively easy to work-around. Let us know if I misunderstand

**Comment by Mark-Simulacrum** [comment] 2017-06-20 20:44
@eddyb, perhaps you could comment here -- is this the same issue as https://github.com/rust-lang/rust/issues/35870? It looks similar, at least.

**Comment by eddyb** [comment] 2017-06-21 09:09
@Mark-Simulacrum Yes, they're both `static`s.

**Comment by Nemo157** [comment] 2017-07-09 22:12
This also appears to affect using `panic!()` inside a closure in an impl Trait because of the implicit statics for the file location:

```
= note: Undefined symbols for architecture x86_64:
    ...::_$u7b$$u7b$closure$u7d$$u7d$::_FILE_LINE_COL::h989fc96fbef4eca7
```

**Comment by michaelwoerister** [comment] 2017-08-09 12:26
I have not yet managed to reproduce this. I must be doing something wrong.

**Comment by Nemo157** [comment] 2017-08-09 12:29
@michaelwoerister try https://github.com/Nemo157/impl-trait-across-crates

**Comment by michaelwoerister** [comment] 2017-08-09 15:17
@Nemo157 Thanks!

**Comment by Nemo157** [comment] 2017-08-09 15:43
It seems at some point between `nightly-2017-07-08` and `nightly-2017-08-09` this error stopped occurring for my testcase in https://github.com/Nemo157/impl-trait-across-crates, now both testcases there produce the error in #43135.

**Comment by michaelwoerister** [comment] 2017-08-11 14:01
The root cause here some that compiler does not properly handle closures that are returned from a function via `-> impl Fn()`. The MIR of the closure will be exported to crate metadata (because that is done for all closures) but things referenced by the closure are not. When the compiler then tries to instantiate the closure's `TransItem` in a downstream crate, it fails because it can neither link to nor create a local copy of these referenced things.

A straightforward solution to this problem would be to fix the [privacy pass](https://github.com/rust-lang/rust/blob/59675d29eb47eb743026dcc0737884f548f2197a/src/librustc_privacy/lib.rs#L376-L381), as @eddyb pointed out.

**Comment by maximih** [comment] 2017-08-13 12:39
Using `#[inline]` does not seem to always help. See #43135 for details. 

Could this issue be prioritized, please?

Thank you

**Comment by maximih** [comment] 2017-08-15 20:57
I tried the latest nightly (which I guess includes https://github.com/rust-lang/rust/pull/43857) but compilation never ends. It seem to get stuck in : 

```
INFO:rustc_metadata::cstore: topological ordering: [CrateNum(2), CrateNum(3), CrateNum(5), CrateNum(4), CrateNum(7), CrateNum(6), CrateNum(8), CrateNum(9), CrateNum(10), CrateNum(11), CrateNum(1), CrateNum(61), CrateNum(56), CrateNum(20), CrateNum(15), CrateNum(16), CrateNum(14), CrateNum(19), CrateNum(18), CrateNum(17), CrateNum(22), CrateNum(21), CrateNum(23), CrateNum(24), CrateNum(25), CrateNum(27), CrateNum(26), CrateNum(28), CrateNum(29), CrateNum(32), CrateNum(34), CrateNum(33), CrateNum(35), CrateNum(31), CrateNum(36), CrateNum(37), CrateNum(30), CrateNum(39), CrateNum(40), CrateNum(41), CrateNum(42), CrateNum(38), CrateNum(13), CrateNum(59), CrateNum(60), CrateNum(62), CrateNum(58), CrateNum(57), CrateNum(55), CrateNum(49), CrateNum(43), CrateNum(68), CrateNum(51), CrateNum(52), CrateNum(50), CrateNum(45), CrateNum(46), CrateNum(47), CrateNum(44), CrateNum(65), CrateNum(66), CrateNum(67), CrateNum(64), CrateNum(63), CrateNum(53), CrateNum(48), CrateNum(54), CrateNum(12)]
```

**Comment by michaelwoerister** [comment] 2017-08-16 10:00
@maximih Thanks for giving it a try! That's interesting. What test case did you use exactly?

**Comment by maximih** [comment] 2017-08-16 14:50
I have a test crate (crate A) which is using another crate (crate B). Crate B has several methods with return type `impl Future<>`.   I can build crate B just fine but I cannot build crate A (it gets stuck and never ends).

Before #43857, I used to get the error in #43135 when building crate A.

**Comment by maximih** [comment] 2017-08-17 18:40
@michaelwoerister I cannot reproduce it after  a `cargo clean && cargo update && cargo build`. I will open a new issue if I see it again. I think this and the related issues should be closed. 

Thanks for your time!

**Comment by Enselic** [comment] 2023-09-15 20:10
> I think this and the related issues should be closed.

Triage: All related issues already seems closed, so let's close this one too.

**Closed by Enselic** 2023-09-15 20:10 UTC
Labels: A-linkage, P-medium, T-lang, T-compiler, C-bug
