### ISSUE TITLE
rustdoc enhancement: indent all lines by 4 spaces in the playground

### ISSUE THREAD

**Issue by Wilfred** [rust-lang/rust#39947] opened 2017-02-19 01:09 UTC
For example, https://doc.rust-lang.org/std/env/fn.args.html includes the following code sample:

```rust
use std::env;

// Prints each argument on a separate line
for argument in env::args() {
    println!("{}", argument);
}
```

However, the run button produces this URL:

https://play.rust-lang.org/?code=fn%20main()%20%7B%0Ause%20std%3A%3Aenv%3B%0A%0A%2F%2F%20Prints%20each%20argument%20on%20a%20separate%20line%0Afor%20argument%20in%20env%3A%3Aargs()%20%7B%0A%20%20%20%20println!(%22%7B%7D%22%2C%20argument)%3B%0A%7D%0A%7D

which gives the following code in the playground:

```rust
fn main() {
use std::env;

// Prints each argument on a separate line
for argument in env::args() {
    println!("{}", argument);
}
}
```

This is a papercut: could we just indent all lines by four spaces? Ideally we'd show the code in the playground with indentation that looks pretty similar to code in a full program.

An alternative option would be to run rustfmt when code is sent to the playground. This risks changing the formatting of the example, which potentially surprising to readers. The advantage of this is that it works with multiline string literals too:

```rust
// indenting every line by 4 spaces here would change the value oft he string
let x = "
";

**Comment by frewsxcv** [comment] 2017-02-19 01:31
This looks like a duplicate of https://github.com/rust-lang/rust/issues/35483. Thanks for filing though!

**Closed by frewsxcv** 2017-02-19 01:31 UTC

**Comment by Wilfred** [comment] 2017-02-19 01:36
Argh, I missed it. Sorry for the noise. @frewsxcv would you mind correcting the spelling in the title of #35483?

**Comment by frewsxcv** [comment] 2017-02-20 20:04
@Wilfred Ah, good catch, fixed
