### ISSUE TITLE
write! should not need external `use`

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#21826] opened 2015-02-01 00:46 UTC
I have to

``` rust
use std::fmt::Writer;
```

outside the macro invocation.

**Comment by tomjakubowski** [comment] 2015-02-01 01:33
Dupe of #21615 I think.

**Comment by alexcrichton** [comment] 2015-02-01 04:07
Somewhat but not entirely I think. We could solve this by solving #21615, but I'm not sure we can solve that issue. This can, however, be independently solved by adding `use $crate::fmt::Writer` and `use std::io::Writer` imports to the relevant macro I believe, however.

**Comment by huonw** [comment] 2015-11-18 06:26
This is still a reality, although the traits are now `Write` (no trailing `r`).

Adding the imports to `write!` has a few downsides/problems:

1. it requires being able to import duplicate names, where only one is used
2. it may trigger unused-import lints, and so would need to handle this properly (including in the presence of `#[forbid(unused_imports)]`)
3. it would mean a type that implements both traits cannot be used with `write!` at all, whereas it is possible now (just have to ensure that only one of the traits is in scope)

Example (currently can only triggers 1, but if/when that is fixed 2 and 3 will be a problem):

```rust
mod foo {
    pub trait Write {
        fn write(&self) {}
    }
    
    impl Write for u8 {}
}
mod bar {
    pub trait Write {
        fn write(&self) {}
    }
    
    impl Write for u8 {}
}
macro_rules! write {
    ($x: expr) => { {
        use foo::Write;
        use bar::Write;
        
        $x.write()
    }}
}

fn main() {
    write!(1u8);
}
```
```
<anon>:18:13: 18:23 error: a trait named `Write` has already been imported in this module [E0252]
<anon>:18         use bar::Write;
                      ^~~~~~~~~~
<anon>:25:5: 25:17 note: in this expansion of write! (defined in <anon>)
<anon>:18:13: 18:23 help: see the detailed explanation for E0252
<anon>:17:9: 17:24 note: previous import of `Write` here
<anon>:17         use foo::Write;
                  ^~~~~~~~~~~~~~~
<anon>:25:5: 25:17 note: in this expansion of write! (defined in <anon>)
```

**Comment by steveklabnik** [comment] 2017-03-08 20:18
Triage: no changes

**Comment by steveklabnik** [comment] 2018-09-24 18:04
Triage: no changes. Given the above list of problems, and no comments since 2015, I'm going to give this issue a close.

**Closed by steveklabnik** 2018-09-24 18:04 UTC
Labels: A-macros, C-enhancement
