### ISSUE TITLE
Potentially swap arrow keys and tab in rustdoc keyboard shortcuts

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#65212] opened 2019-10-08 15:27 UTC
Currently rustdoc's keyboard shortcuts use <kbd><kbd>Tab</kbd></kbd> to cycle between the tabs at the top of search results, and the arrow keys for moving through search results.

It's much more common for <kbd><kbd>Tab</kbd></kbd> and <kbd><kbd>Shift</kbd> + <kbd>Tab</kbd></kbd> to be used for navigating a list, and you can autosupport this by adding `tabindex`es, I think those autoskip `display:none` elements as well. It's pretty bad form to override <kbd><kbd>Tab</kbd></kbd>. Perhaps we should use `tabIndex` for this and use something else for switching the search result tabs?

**Comment by Manishearth** [comment] 2019-10-09 14:56
tabindex won't work if we override tab, that's the problem

this is a well-established pattern

**Comment by GuillaumeGomez** [comment] 2019-10-10 14:01
Even with tabindex, we'll still have to bind 'enter' key I assume to change the current search tab, no? Also, we can't bind right and left arrows to do this so we're kinda limited to find replacements. The last option would be to add a setting to disable like you proposed in #65211 I guess? But we have other issues to answer on this other one.

**Comment by Manishearth** [comment] 2019-10-10 14:05
No, if you're using tab navigation the enter key should automatically work
to "click" the currently selected thing.

The browser functionality around this is quite robust, let's not reinvent
it.

**Comment by steveklabnik** [comment] 2020-12-06 17:36
Triage: not aware of any work here

**Comment by GuillaumeGomez** [comment] 2020-12-07 10:53
After coming back to this issue after such a long time, I think we should keep the current behavior.

**Comment by Manishearth** [comment] 2020-12-07 22:09
I still disagree. I haven't had the time to prototype this, but this is very much not following the norms for keyboard navigation which has accessibility implications.

**Comment by GuillaumeGomez** [comment] 2020-12-08 10:02
I don't see how accessibility can be impacted by this. I assume they don't go through text content the same way and that changing how the interactions are done will change anything for them. In addition to that, when included in docs.rs, adding more tabindex could be problematic depending on docs.rs evolutions (we added some tabindex there as well).

**Comment by Manishearth** [comment] 2020-12-08 18:32
Firstly, keyboard accessibility is not only for the blind. People may prefer keyboards over mice for many accessibiltiy reasons. However, tab navigation is a huge part of accessibility for the blind in many cases.

>  In addition to that, when included in docs.rs, adding more tabindex could be problematic depending on docs.rs evolutions (we added some tabindex there as well).

No, that's the point, we _don't_ actually need to add tabindex, currently we're _overriding_ tab defaults via JS which is almost always _really_ bad. The tab defaults for the page are quite good already, what would happen is that you would tab through focus on the top tabs, and then through all of the links and summary short strings. We may potentially want to exclude the summary short strings from tab navigation, but other than that we wouldn't be doing special tabindex stuff.

**Comment by jyn514** [comment] 2020-12-08 18:37
> Perhaps we should use tabIndex for this and use something else for switching the search result tabs?

Maybe we could use left/right arrows instead of tab for switching between 'In Names' and 'In Parameters'? I think that's more clear than tabs anyway.

**Comment by Manishearth** [comment] 2020-12-08 18:38
My rough proposal is that we remove all JS that consumes <kbd><kbd>Tab</kbd></kbd>, potentially use `tabindex=-1` on the summary entries (and `tabindex=0` on the links, if necessary, but i don't think it will be).


(Negative tab index = "do not tab-focus this". Zero tab index = "please tab focus this in document order", this does not interfere with any explicitly defined positive tab indices)


We could also add arrow key navigation, but people _also_ use arrow keys for editing typed search phrases so that's more complex. At the very least we need to get rid of the custom JS IMO.

**Comment by jyn514** [comment] 2020-12-08 18:41
> We could also add arrow key navigation, but people also use arrow keys for editing typed search phrases so that's more complex. At the very least we need to get rid of the custom JS IMO.

Hmm, personally I think I'd prefer for left/right to switch the search tabs and have to use `s` explicitly to bring the search bar into focus. I don't think we should get rid of keyboard shortcuts for tabbing without having *some* replacement, even if it's a few more keystrokes.

**Comment by Manishearth** [comment] 2020-12-08 18:52
> Hmm, personally I think I'd prefer for left/right to switch the search tabs and have to use `s` explicitly to bring the search bar into focus. I don't think we should get rid of keyboard shortcuts for tabbing without having _some_ replacement, even if it's a few more keystrokes.

Oh sure, I meant that we should not be capturing left/right whilst focused on the search box. We can add that event listener to the search results area, that should be fine.

**Comment by GuillaumeGomez** [comment] 2020-12-08 19:27
> > Perhaps we should use tabIndex for this and use something else for switching the search result tabs?
> 
> Maybe we could use left/right arrows instead of tab for switching between 'In Names' and 'In Parameters'? I think that's more clear than tabs anyway.

But then how do you move in the search input? ;)

> Firstly, keyboard accessibility is not only for the blind. People may prefer keyboards over mice for many accessibiltiy reasons. However, tab navigation is a huge part of accessibility for the blind in many cases.

@Manishearth I don't see how the current behavior blocks that? You can still move through answers using up and down arrows. But I think I'm starting to understand your issue: it's the `tab` overload we added in the JS, right? Then, with what would you replace it? Also, you can use `esc` and then use `tab` afterwards.

**Comment by Manishearth** [comment] 2020-12-08 19:46
> Then, with what would you replace it?
Nothing. The browser has acceptable default tab navigation behavior, though we can improve on it by applying some `tabindex=-1`s if we want

**Comment by GuillaumeGomez** [comment] 2020-12-08 19:55
> Nothing. The browser has acceptable default tab navigation behavior, though we can improve on it by applying some `tabindex=-1`s if we want

Then I'm lost: how do you switch between the three tabs?

> You only do this when focused on the search results area

But then you need to focus on the search results area, which is almost never the case as far as can I can tell. That doesn't sound like a great idea. :-/

**Comment by Manishearth** [comment] 2020-12-08 20:04
> Then I'm lost: how do you switch between the three tabs?

Tab navigate to a different "tab" and hit space.

> But then you need to focus on the search results area, which is almost never the case as far as can I can tell. That doesn't sound like a great idea. :-/

You will after hitting tab a few times. This is how keyboard navigation usually works.

**Comment by GuillaumeGomez** [comment] 2020-12-08 20:08
> Tab navigate to a different "tab" and hit space.

That seems **very** counter-intuitive. Even more considering that switching between elements using `tag` isn't that common.

> You will after hitting tab a few times. This is how keyboard navigation usually works.

Which is exactly why I don't think this is a good idea here. It's much more complicated than the current behavior.

**Comment by Manishearth** [comment] 2020-12-08 20:29
> That seems **very** counter-intuitive. Even more considering that switching between elements using `tag` isn't that common.

This is literally how keyboard navigation typically works on the web. There are norms for how to do this, many people use this to a fair amount, some people rely strongly on it.

> Which is exactly why I don't think this is a good idea here. It's much more complicated than the current behavior.

The current behavior tab-locks you which is a _huge_ accessibility hazard. Furthermore, it's nonintuitive, it does not follow the typical model of tab-navigation on the web.

**Comment by antoyo** [comment] 2020-12-08 20:58
I'm only using keyboard on my computer and I never use tab to switch between elements and I also find current shortcuts good enough.

**Comment by GuillaumeGomez** [comment] 2020-12-08 20:59
You can switch to the "default" behavior by simply pressing "esc". I don't see why it's a problem then.

**Comment by Manishearth** [comment] 2020-12-09 01:16
Firstly, no, the escape key exits the search pane altogether.

Secondly, keyboard users will not know to expect such a thing.

_No matter what_, it is a problem that our webpages tablock by default. I can't believe that we're having a hard time coming to agreement on that, I would have expected accessibility to be valued here :/

**Comment by Manishearth** [comment] 2020-12-09 02:07
Some citations:

From https://www.csun.edu/universal-design-center/web-accessibility-criteria-tab-order 

> Tab order is important for proper navigation through a keyboard interface. The keyboard tab order must be coordinated with the structure of the webpage. The default keyboard navigation order must be logical and intuitive. The tab order should follow the visual flow of the page: left to right, top to bottom – header first, then main navigation, then page navigation (if present), and finally the footer.



We are currently not coordinated with the structure of the webpage, and we do not follow the visual flow.

From https://www.w3.org/WAI/WCAG21/quickref/#no-keyboard-trap:

> If keyboard focus can be moved to a component of the page using a keyboard interface, then focus can be moved away from that component using only a keyboard interface, and, if it requires more than unmodified arrow or tab keys or other standard exit methods, the user is advised of the method for moving focus away.



From https://www.w3.org/WAI/WCAG21/quickref/#focus-order:

> If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability.

From https://www.w3.org/WAI/WCAG21/quickref/#on-focus:

> When any user interface component receives focus, it does not initiate a change of context.

Tab navigation, which is primarily how you change focus, is changing the context of the page here.

**Comment by Manishearth** [comment] 2020-12-09 02:11
@katie-martin-fastly mentioned that she had been having trouble with this as well.

**Comment by GuillaumeGomez** [comment] 2020-12-09 10:25
What you're reporting isn't about accessibility but about personal preference: not using a mouse is a choice in most cases. Even though I think the current behavior is completely fine, I suggested to replace `tab` with another key. I don't want to lose the possibility to navigate the docs only with the keyboard, which is currently possible. Having to focus on tabs' title to switch between them is an absolute non-sense.

**Comment by steveklabnik** [comment] 2020-12-09 14:21
> not using a mouse is a choice in most cases.

Even if this is true, what about the cases that are not the "most" case? That would be things like accessibility. Which does matter.

**Comment by GuillaumeGomez** [comment] 2020-12-09 15:30
They can completely use rustdoc without a mouse, which was the whole point of those bindings. Accessibility does matter, I just don't agree with the arguments used here to support this.

**Comment by Manishearth** [comment] 2020-12-09 16:44
> What you're reporting isn't about accessibility but about personal preference: not using a mouse is a choice in most cases

This ... is an aspect of accessibility. Accessibility is about making your software accessible to the most number of people as possible; this includes people who are used to interacting with the web via keyboard. Even if it's a choice, it might introduce a barrier to entry to deliberately not use the choice (what if you don't even have a mouse attached to your computer and need to find one?)

I do not think we should start a discussion about specific disabilities here, but there can be situations where someone has strong reasons for doing this where it's not "just a choice", as well.

_Furthermore_ tab-locking is absolutely a problem for blind users since the tab key is a key part of how blind users interact with the web and software in general. It feels roughly equivalent to locking 

> Having to focus on tabs' title to switch between them is an absolute non-sense.

Feel free to introduce a different keyboard shortcut for them that doesn't use tabs. My recommendation, to make this take the least amount of effort and least amount of change, was to use the default focus behavior and do nothing else. We don't have to force users to use the default focus behavior to navigate the page, I just want that to _work_. Alternatives would be good too; I'm having a hard time coming up with alternatives because most keys are used during typing.

Note that with some tweaks we can make it so that  literally the first tab-out of the search box will go to the tabs. So the workflow would be "tab, then hit tab more times to select your 'tab', and space"

Also my personal feeling is that the tabs are not that used as much so I'm personally okay not having this.

I'll point out that you are calling the default accessibility guidelines of the web as nonsense. This is stuff that has had a lot of work and research put into it, by people who are experts on this topic. The focus model of the web isn't perfect, but it's way better than what we'll be able to come up with.

> They can completely use rustdoc without a mouse, which was the whole point of those bindings. Accessibility does matter, I just don't agree with the arguments used here to support this.

No, they cannot, because these are not clear at all, and there are _norms_ about this so that people don't need to learn bespoke keyboard combinations for each website, because they won't. That's _way_ too much overhead to just use a website.

@katie-martin-fastly just _didn't use search_ because of this. The tab-locking made it worse so she would _refresh_ the page (not knowing that Esc works) to exit the search since the tab lock wouldn't let her otherwise, and over time stopped. She was **typing URLs for documentation items directly** instead of using search, which is an illustration of how bad this failure is. I'm sure she can talk more about her experience, but it is absolutely unacceptable for the answer to an accessibility issue to be "they can theoretically use it" when it is not designed for people to practically do it, since there's no obvious way to learn. Help text is not going to help here either, because, again, keyboard navigation on the web is largely a matter of norms, so people will not look for information on how to correctly keyboard navigate, they will simply dismiss the website as broken. That's a huge failure.

**Comment by GuillaumeGomez** [comment] 2020-12-09 16:58
> This ... is an aspect of accessibility. Accessibility is about making your software accessible to the most number of people as possible; this includes people who are used to interacting with the web via keyboard. Even if it's a choice, it might introduce a barrier to entry to deliberately not use the choice (what if you don't even have a mouse attached to your computer and need to find one?)

You can completely use rustdoc without a mouse (I don't have one for example), this isn't the issue here in my opinion.

> I do not think we should start a discussion about specific disabilities here, but there can be situations where someone has strong reasons for doing this where it's not "just a choice", as well.

Well, we still need to keep that in mind in such discussions.

> Furthermore tab-locking is absolutely a problem for blind users since the tab key is a key part of how blind users interact with the web and software in general. It feels roughly equivalent to locking

I have to admit it's a bit hard to read this when I had to fight to keep rustdoc usable even without JS. But I'm glad that it's now an important parameter of rustdoc and that I'm not the only one to think about it. :)

> Feel free to introduce a different keyboard shortcut for them that doesn't use tabs. My recommendation, to make this take the least amount of effort and least amount of change, was to use the default focus behavior and do nothing else. We don't have to force users to use the default focus behavior to navigate the page, I just want that to work. Alternatives would be good too; I'm having a hard time coming up with alternatives because most keys are used during typing.

Yes, it's my whole point: I don't mind removing the current tab-locking (even less if it improves experience for people with no mouse!), but it needs to be replaced by something else.

> I'll point out that you are calling the default accessibility guidelines of the web as nonsense. 

You're getting out of scope here, please not give me intentions I don't have. What I said is that the rustdoc search works without keyboard and that if we wanted to not tab-lock anymore, I'm okay with it **but** we needed to replace it with another key to be able to keep the same behavior overall.

> Note that with some tweaks we can make it so that literally the first tab-out of the search box will go to the tabs. So the workflow would be "tab, then hit tab more times to select your 'tab', and space"

I'd rather simply switch fully out of the `tab` instead of doing such hacks if possible. We just need to agree on another key to have the same results.

> No, they cannot, because these are not clear at all, and there are norms about this so that people don't need to learn bespoke keyboard combinations for each website, because they won't. That's way too much overhead to just use a website.

I agree with that part, but then it's a complete different issue.

> @katie-martin-fastly just didn't use search because of this. The tab-locking made it worse so she would refresh the page (not knowing that Esc works) to exit the search since the tab lock wouldn't let her otherwise, and over time stopped. She was typing URLs for documentation items directly instead of using search, which is an illustration of how bad this failure is. I'm sure she can talk more about her experience, but it is absolutely unacceptable for the answer to an accessibility issue to be "they can theoretically use it" when it is not designed for people to practically do it, since there's no obvious way to learn. Help text is not going to help here either, because, again, keyboard navigation on the web is largely a matter of norms, so people will not look for information on how to correctly keyboard navigate, they will simply dismiss the website as broken. That's a huge failure.

You're using **one** person to back all the reasoning here, which isn't great. I'm sorry if @katie-martin-fastly had a bad experience with rustdoc. But **one** person had issue with rustdoc doesn't mean it's a failure. Once again, it'd be nice to consider that people spent a lot of time on rustdoc and that if they knew about this, they'd be very happy about trying to improve the situation.

However, I repeat myself once again: I agree that tab-locking isn't the best and I agree we should **replace** it and not **remove** it.

**Comment by Manishearth** [comment] 2020-12-09 17:09
> You can completely use rustdoc without a mouse (I don't have one for example), this isn't the issue here in my opinion.

You _theoretically_ can, practically it is hard to discover this keyboard setup and it does not follow norms, so people will not use it.

> You're using **one** person to back all the reasoning here, which isn't great. I'm sorry if @katie-martin-fastly had a bad experience with rustdoc. But **one** person had issue with rustdoc doesn't mean it's a failure. Once again, it'd be nice to consider that people spent a lot of time on rustdoc and that if they knew about this, they'd be very happy about trying to improve the situation.

> Yes, it's my whole point: I don't mind removing the current tab-locking (even less if it improves experience for people with no mouse!), but it needs to be replaced by something else.

It is! The default focus behavior of the web! Which is what is used _everywhere_, including on Google Search, which _also has search results and tabs_. 

> I'd rather simply switch fully out of the tab instead of doing such hacks if possible. We just need to agree on another key to have the same results.

This isn't a hack! This is how _focus works on the web by default_! We would not even have to write code to support this, our page is laid out in a way that works well without any javascript!

> You're using one person to back all the reasoning here, which isn't great. I'm sorry if @katie-martin-fastly had a bad experience with rustdoc. But one person had issue with rustdoc doesn't mean it's a failure. Once again, it'd be nice to consider that people spent a lot of time on rustdoc and that if they knew about this, they'd be very happy about trying to improve the situation.

No, I also had the same problem here, I just am more comfortable with switching to a mouse. I'm highlighting Katie's experience because she hit the worst failure mode -- she stopped using search entirely.

> However, I repeat myself once again: I agree that tab-locking isn't the best and I agree we should **replace** it and not **remove** it.

Thank you.

I do not mind coming up with something better, but I do not want to block it on coming up with additional keyboard shortcuts, because I think this is hard. I want to _remove_ this, and then consider coming up with something that can _replace_ it, keeping in mind that tab-switching would be possible by default via the keyboard the same way it is on Google. I think tab-locking is _very very bad_ and should be gotten rid of as soon as possible.

**Comment by Manishearth** [comment] 2020-12-09 17:10
Honestly, the fact that Google works this way should be a strong signal that we should follow suit, since most people using keyboard navigation will be used to doing it the same way there.

**Comment by dns2utf8** [comment] 2020-12-09 17:17
Hi all,

I was around when @GuillaumeGomez implemented the feature and I have grown quite fond of how it works because it is very intuitive for me. 
What would you do with the tab key when it is not bound to tabbing trough the results?
After pressing escape, the tab is free anyways.

Just because Google does something, feels like an ad-hominem argument. Unless you would like rustdoc to collect the most common searches and report them (for a subscription?) to the crate authors too?

Can you elaborate on the No-JS idea? Because this is hard for me to imagine since the filtering is very powerful at the moment and I love the reverse search which I need in like 30% of my queries.

Cheers,
Stefan

**Comment by sersorrel** [comment] 2020-12-09 17:33
a data point: i was wildly surprised to find that <kbd>tab</kbd> switches between tabs, and it took me a while to work out that it only happens when the textfield has focus.

i usually use vimium to navigate the search results, which works because the results are just (pairs of) links:

![image](https://user-images.githubusercontent.com/9433472/101664538-dffc3600-3a43-11eb-8029-bb7e479393fc.png)

...though you might notice that the tab titles don't get annotations, because they're just `<div>`s, so they're not keyboard-accessible.

**Comment by iximeow** [comment] 2020-12-09 17:34
> You're using *one* person to back all the reasoning here, which isn't great. I'm sorry if *@katie-martin-fastly* had a bad experience with rustdoc. But *one* person had issue with rustdoc doesn't mean it's a failure

how many people are necessary?

even if the accessibility point is not compelling for some reason, the current tab mechanic has a very surprising behavior: if you begin a search, then empty the box (backspace, or ctrl+a and then backspace), the docs page reverts to the crate documentation as if no search had been done, but focus is still locked to the search bar. the page is visually identical to having not done a search, where tab could cycle between elements.

before seeing this issue, i had encountered this and assumed that docs.rs simply had some flaky javascript, did not make time to investigate, and moved on. i thought it was a bug.

to return to a mode where the tab key is useful again, you have to know to press `esc`. this means `esc` does a different thing for docs.rs than it does _by default on every browser_: `esc` is a shortcut for "stop", which stops all connections. _the escape key has an expected behavior_. it will not occur to someone who primarily navigates the internet by keyboard to press the escape key.

> What would you do with the tab key when it is not bound to tabbing trough the results?

i would have the tab key to cycle through through tabs and continue to the "in names" content, from top to bottom. cycling from "In Return Types" to "In Names" is an extremely narrow repurposing of tab (and shift+tab, to go backwards in tab order) command.

**Comment by GuillaumeGomez** [comment] 2020-12-09 17:35
> You theoretically can, practically it is hard to discover this keyboard setup and it does not follow norms, so people will not use it.

Then that is a problem we should address!

> This isn't a hack! This is how focus works on the web by default! We would not even have to write code to support this, our page is laid out in a way that works well without any javascript!

Well, you can't get this page if you don't have javascript enabled, so in that sense, it wouldn't improve anything. :laughing: 

And it's exactly what I suggest by **replacing** instead of **removing**. The default web behavior exists but requires multiple actions. We can do better than that (like we currently do for example).

> It is! The default focus behavior of the web! Which is what is used everywhere, including on Google Search, which also has search results and tabs.

Because the page is much simpler and I think the comparison is a bit out of context here.

> This isn't a hack! This is how focus works on the web by default! We would not even have to write code to support this, our page is laid out in a way that works well without any javascript!

For reference, I was commenting on this: `So the workflow would be "tab, then hit tab more times to select your 'tab', and space` and I misunderstood what you meant. But that still makes more interactions than the current behavior (one), which is why I want a **replacement** and not a **removal**.

And again, without javascript, you can't have the search results page.

> No, I also had the same problem here, I just am more comfortable with switching to a mouse for this. I'm highlighting Katie's experience because she hit the worst failure mode -- she stopped using search entirely.

And I'm sorry about that. Which is why we're currently discussing about fixing it.

**Comment by GuillaumeGomez** [comment] 2020-12-09 17:41
> how many people are necessary?

@iximeow 1. The whole point here is about prioritization. Until recently, I was mostly alone working on this. @dns2utf8 suggested this new feature, I thought it was nice and would improve everyone's life. Now I realize it didn't, I'm sorry about it but I still want to be able to switch tabs without losing focus on the search bar. We just need to agree on a key to do so and then it's done.

Please all remember that it's mostly about priority. I don't voluntarily want to make people rustdoc's experience bad. If something doesn't feel right to you, well, it's simply because I ignored it could be used this way.

@sersorrel Could you open a separate issue about this please?

**Comment by sersorrel** [comment] 2020-12-09 17:42
@GuillaumeGomez will do.

another point: in current versions of chrome, without vimium installed, pressing <kbd>esc</kbd> does not release focus from the text field, it cancels the search altogether. so as far as i can see, if you don't use vimium, there's no way to recover the usual behaviour of <kbd>tab</kbd> once you've done a search.

**Comment by Manishearth** [comment] 2020-12-09 17:43
>  What would you do with the tab key when it is not bound to tabbing trough the results?

Browsers by default use the tab key for focus, which is an important accessibility property. It would just use the default behavior, which lets you switch through "tabs" and the search results

> Just because Google does something, feels like an ad-hominem argument. Unless you would like rustdoc to collect the most common searches and report them (for a subscription?) to the crate authors too?

This was an argument about norms: When people interact with the web, there are norms as to how things work. You can expect to find a search box at the top or top right of the page. You can expect to find a contact us at the bottom. Nobody is going to learn a billion minute things about how to use a particular website, a lot of this is based on norms. If you follow norms, you do not need to educate your users on how to use your website, which is exactly the problem we have here. Furthermore, the fact that Google -- an organization large enough to have accessibility teams to actually _do_ the research on this -- picked the default behavior on their main website, is a pretty large signal.

But okay, Bing has similar behavior, except focus starts on the first search entry, and you can shift-tab to get back to the "tabs". This is also easy behavior to replicate with a little javascript. Wikipedia doesn't have "tabs" but it has options at the top of the search and it works the same way.


> Can you elaborate on the No-JS idea? Because this is hard for me to imagine since the filtering is very powerful at the moment and I love the reverse search which I need in like 30% of my queries.

Oh no i'm not saying we remove all the JS here, I'm just saying that if we remove the JS around the tab key the default behavior is actually quite okay.

**Comment by Manishearth** [comment] 2020-12-09 17:47
> Well, you can't get this page if you don't have javascript enabled, so in that sense, it wouldn't improve anything. 😆

I meant no further custom JS.


> For reference, I was commenting on this: `So the workflow would be "tab, then hit tab more times to select your 'tab', and space` and I misunderstood what you meant. But that still makes more interactions than the current behavior (one), which is why I want a **replacement** and not a **removal**.

I understood what you meant. That is more interactions, but what i'm saying is that -- we are not _losing_ the ability to do this, it's just harder (but following web norms, so nobody has to learn them!!), and given that we are currently violating many accessibility guidelines I would like to remove this behavior as soon as possible (there was less urgency for me when I filed this because I had not noticed the tablocking), and perhaps introduce new behavior later if possible. I'm having trouble imagining a good option for new behavior. The best I can think of is using the up/down arrow keys for this, which isn't super intuitive.

**Comment by GuillaumeGomez** [comment] 2020-12-09 17:54
> I understood what you meant. That is more interactions, but what i'm saying is that -- we are not losing the ability to do this, it's just harder (but following web norms, so nobody has to learn them!!), and given that we are currently violating many accessibility guidelines I would like to remove this behavior as soon as possible (there was less urgency for me when I filed this because I had not noticed the tablocking), and perhaps introduce new behavior later if possible. I'm having trouble imagining a good option for new behavior. The best I can think of is using the up/down arrow keys for this, which isn't super intuitive.

up/down is already used to go through items in the current tab, so we'll need another one haha. tab was very convenient for that... Well anyway, let's just pick a key, whichever the one we take and I'll open a PR so we can move on.

**Comment by GuillaumeGomez** [comment] 2020-12-09 17:58
Just got an idea for the key:

 * ctrl (or shift) + up/down would go through tabs
 * up/down alone go through items in the list

How does that sound?

**Comment by GuillaumeGomez** [comment] 2020-12-09 18:00
@sersorrel It's voluntary (just realized it). The search page results is supposed to be switched into/out quickly by using escape or focusing on the search bar. We should really add all the rustdoc interactions into the help... I'll do that once we've settled down here.

**Comment by spearman** [comment] 2020-12-09 18:01
My expectation is that arrow keys are for scrolling and tab is for selecting. It took me some time to get used to rustdoc doing things differently.

**Comment by iximeow** [comment] 2020-12-09 18:02
> ctrl (or shift) + up/down would go through tabs

shift + up/down should be a non-option: shift+up will select the text being searched for.

why must the list of tabs be a cyclic? is going from the third tab to first tab in one keystroke a common task?

i do not understand why tab cannot move focus from the third tab to the first item in the selected tab of results

**Comment by Manishearth** [comment] 2020-12-09 18:02
@GuillaumeGomez that seems great! It seems a little unintuitive to me but that is fine, I don't think tab-switching is a particularly common operation. If you're okay with people learning the key combos I'm all for it.

**Comment by Manishearth** [comment] 2020-12-09 18:07
> i do not understand why tab cannot move focus from the third tab to the first item in the selected tab of results

I think I can explain this, @GuillaumeGomez wants a way to go through search results without having to defocus the search field, so that you can keep typing

**Comment by GuillaumeGomez** [comment] 2020-12-09 18:09
> My expectation is that arrow keys are for scrolling and tab is for selecting. It took me some time to get used to rustdoc doing things differently.

Not if you in a input field. And that problem will be solved when we'll stop tab-locking. ;)

> shift + up/down should be a non-option: shift+up will select the text being searched for.

Good point, ctrl+arrows then!

> why must the list of tabs be cyclic? is going from the third tab to first tab in one keystroke a common task?
>
> i do not understand why tab cannot move focus from the third tab to the first item in the selected tab of results

That's a completely different behavior. But since we won't have tab-lock anymore, it'll now be possible so I guess it's all good? You'll have the choice between using rustdoc events through the search input or you can simply use the normal events by unfocusing the search input.

> I think I can explain this, @GuillaumeGomez wants a way to go through search results without having to defocus the search field, so that you can keep typing

Exactly!

> @GuillaumeGomez that seems great! It seems a little unintuitive to me but that is fine, I don't think tab-switching is a particularly common operation. If you're okay with people learning the key combos I'm all for it.

Great! I'll send the PR shortly then. We really need to improve the help popup.

**Comment by iximeow** [comment] 2020-12-09 18:09
>  go through search results without having to defocus the search field

ah, so pressing enter to (say) select an alternate tab would be out of the question since it would defocus? i can see that

**Comment by katie-martin-fastly** [comment] 2020-12-09 18:16
Hello! Pardon the late response. As mentioned above, I would like to reiterate that `Tab` is not only a conventional choice for navigating through lists such as this, but also a _specified_ best practice for web accessibility. The W3C Working Groups's Authoring Practices says [the following](https://www.w3.org/TR/wai-aria-practices/#grid).

> All focusable elements contained in a table are included in the page tab sequence.

I will try not to rehash the accessibility discussion above, but I will say that I do not _own_ a mouse. Regardless of whether or not that is "by choice" due to a disability, this means that the tablocking behavior makes the generated documentation difficult for me to use. In many situations, rather than using the search feature, I often opt to manually type the URL's myself to navigate to a given type.

While today I am a Rust engineer by trade, until very recently I worked as a front-end engineer, often focusing on improving the accessibility features of existing websites. The behavior that @Manishearth is requesting is not a matter of preference, it is considered an industry-wide best practice. I do not believe that citing other websites' conformance to this is an ad-hominem argument, it is reasonable supporting evidence of this position.

**Comment by rbalicki2** [comment] 2020-12-09 18:18
I use vimium for navigation and browser use. I find the rust docs to be very amenable to use of a keyboard with vimium.

**Comment by dns2utf8** [comment] 2020-12-09 18:21
Could you @Manishearth and @katie-martin-fastly implement it? Since you seem more knowledgeable in this area.

**Comment by Manishearth** [comment] 2020-12-09 18:28
@dns2utf8 I mean, we were suggesting switching to the default behavior of the browser, so there's nothing new to implement, just code to use. I'm happy to do this or implement Guillaume's proposed keyboard shortcuts but it seems like he's already working on it? If not, happy to do this myself.

There's a follow-up I'd like to experiment with which I'll implement, but I'll do that once we resolve this

**Comment by GuillaumeGomez** [comment] 2020-12-09 18:53
> There's a follow-up I'd like to experiment with which I'll implement, but I'll do that once we resolve this

Arf, another issue? :-/

**Comment by katie-martin-fastly** [comment] 2020-12-09 19:03
> Could you @Manishearth and @katie-martin-fastly implement it? Since you seem more knowledgeable in this area.

While I appreciate the invitation to do so, I have very little familiarity with the internals of `rustdoc`, and unfortunately very little bandwidth to contribute as of late. I _do_ want to make a note of appreciation for all of the work that goes into maintaining this project, but I should disclaim that I was offering a comment describing my experience from the perspective of **(a)** a user of the Rust documentation impacted by keyboard accessibility, and **(b)** an engineer that has some previous experience with web accessibility guidelines and standards.

**Comment by Manishearth** [comment] 2020-12-09 19:05
> Arf, another issue? :-/

Nothing pressing, I just have ideas for how we can be _even better_ here and want to experiment. I'll open PRs if I find something that works well

**Closed** 2020-12-10 00:42 UTC
Labels: A-rustdoc-search, A-rustdoc-ui, T-rustdoc
