### ISSUE TITLE
Nested macro invocation doesn't follow proper scoping rules

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#9323] opened 2013-09-19 07:02 UTC
When one macro invokes another macro, it always looks up the nested macro from the point of the outer invocation, instead of from the point of the macro definition. I don't know if this is intentional.

Example:

``` rust
fn main() {
    macro_rules! foo(
        () => (println!("outer"))
    );
    {
        macro_rules! bar(
            () => (foo!())
        );
        {
            macro_rules! foo(
                () => (println!("inner"))
            );
            bar!()
        }
    }
}
```

If these were functions, it would print `outer`, but instead it prints `inner`.

**Comment by frewsxcv** [comment] 2015-03-23 13:44
@kballard Are you able to confirm if this is still valid with the latest Rust? Your original code block doesn't compile currently.

**Comment by kballard** [comment] 2015-03-23 17:49
@frewsxcv It's still broken. I just updated the original code block with something that compiles.

**Comment by Ryman** [comment] 2015-06-10 18:38
I think this example is related:

```rust
macro_rules! foo {
    ($v:ident) => (
        let $v = 3;
        println!("{}", $v); // If you comment this then it's fine.
    );
}

fn main() {
    foo!(x);
    println!("{}", x);
}
```

**Comment by jbclements** [comment] 2015-06-11 18:38
@Ryman  No... I think that's a different problem. Can you file a separate issue for that, and send me mail when you're done? (BTW, be sure to include the expected and actual behavior when you do.)

**Comment by Ryman** [comment] 2015-06-11 18:54
@jbclements Opened #26223

**Comment by steveklabnik** [comment] 2017-01-03 20:07
Triage: same error today.

**Comment by steveklabnik** [comment] 2018-09-24 16:46
Triage: `macro_rules` is not being worked on anymore, with `macro` as its replacement. Given that there's been no substantial comments since 2015, and it still reproduced in 2017, I don't believe this will be changed. Closing.

**Closed by steveklabnik** 2018-09-24 16:46 UTC
Labels: A-syntaxext, C-feature-request

**Comment by petrochenkov** [comment] 2018-09-24 21:43
This is expected behavior for `macro_rules` macros which are hygienic only for local variables and labels.

Macros 2.0 (`macro`) change this behavior and the example prints "outer".
```rust
#![feature(decl_macro)]

fn main() {
    macro foo{
        () => (println!("outer"))
    }
    {
        macro bar{
            () => (foo!())
        }
        {
            macro foo{
                () => (println!("inner"))
            }
            bar!()
        }
    }
}
```

Macros 2.0 are deeply unstable and `macro_rules` is still the primary declarative macro system in Rust, so they are worked on in terms of both bugs and occasionally extensions.
