### ISSUE TITLE
stage 1 ui test fails but only once: too big for the current architecture

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53429] opened 2018-08-16 14:29 UTC
When I run stage 1 ui tests, it sometimes happens that I get a failure in `ui/huge-array.rs`:

> the type `[[u8; 1518599999]; 1518600000]` is too big for the current architecture

But then, when I rerun the tests, it works. That is rather odd, isn't it?

**Comment by RalfJung** [comment] 2018-08-16 15:08
I didn't realize that this is an expected-to-fail test. The problem is that it segfaults:
```
error: Error: expected failure status (Some(1)) but received status None.
status: signal: 11
command: "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/home/r/src/rust/rustc.2/src/test/ui/huge-array.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/test/ui/huge-array/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/test/ui/huge-array/auxiliary" "-A" "unused"
```

**Comment by eddyb** [comment] 2018-08-17 11:02
I don't think it's OOM, if you enable assertions you'll them spuriously failing on this test.

cc @alexcrichton @pnkfelix @nikomatsakis some of us have seen this before (in `compile-fail`).

**Comment by pnkfelix** [comment] 2018-09-14 16:04
(Could this perhaps be caused by async LLVM, which may explain why it is spurious/transient? See also #49928)

**Comment by Enselic** [comment] 2023-10-12 19:06
Triage: Is this still happening? If not I think we can close this issue. (I will do so at a later point unless this is reported to still be a problem.)

**Comment by RalfJung** [comment] 2023-10-12 21:43
I haven't seen this in a long time.

**Comment by Enselic** [comment] 2024-11-04 18:12
Triage: Thanks for the update. Let's close this then.

**Closed by Enselic** 2024-11-04 18:12 UTC
Labels: T-compiler, C-bug
