### ISSUE TITLE
`./x.py build -i` does not fill stage2 directory

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#43177] opened 2017-07-12 02:36 UTC
Just like `./x.py build` ends by filling the stage 2 directory...
```
Copying stage1 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Copying stage2 compiler (x86_64-unknown-linux-gnu)
Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
```
... I would expect `./x.py build -i` to do the same. But it does not, the output ends with
```
Copying stage1 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Build completed successfully in 0:00:03
```
So to get a usable stage 2 while using incremental compilation, I need to `./x.py build -i && ./x.py build`. That seems wrong.

**Comment by Mark-Simulacrum** [comment] 2017-07-28 00:43
`./x.py build -i` defaults the stage to `1` (https://github.com/rust-lang/rust/blob/5cc1baa2900ab344e8e8386aa8314b59051868ca/src/bootstrap/flags.rs#L309-L311) so we don't build a stage2 directory. However, you can pass `--stage 2` to override that. Closing as not a bug.

**Comment by RalfJung** [comment] 2017-07-28 05:59
That is very confusing. Why should the `-i` flag affect the stage at all? There is no reason for the user to expect this, nor is it documented in `--help`.

I still think there is a bug here.

**Comment by Mark-Simulacrum** [comment] 2017-07-28 12:09
Hm, perhaps so. I'll reopen.

The thought here I believe is that if you want an incremental build, you probably want to only build to stage 1, since only stage 0 is incrementally built. However, since I believe @nikomatsakis added the logic in 83453bc673a, I'll let them try to explain why. cc @alexcrichton as well.

**Comment by RalfJung** [comment] 2017-07-28 19:54
> The thought here I believe is that if you want an incremental build, you probably want to only build to stage 1, since only stage 0 is incrementally built.

Notice that `x.py build --stage 1` does build everything. The only thing it does not do is copy the output of the stage 1 compilation into the stage 2 folder.

**Comment by Mark-Simulacrum** [comment] 2017-07-28 19:58
Note that the fact that `./x.py build --stage 1` basically builds everything is only a side-effect of having `full-bootstrap` turned off, and hence us promoting stage1's target libdir into stage2's sysroot. It's somewhat true that as it is today, `./x.py build --stage 1` is *mostly* not what you want.

**Comment by RalfJung** [comment] 2017-07-28 20:00
Ah, so probably behavior was different when the `-i` flag was made to behave the way it does.

**Comment by Mark-Simulacrum** [comment] 2017-07-28 20:05
So the one thing here is that as it is today, most of the time you don't need to build the stage1 compiler artifacts, so `-i`'s behavior of setting the stage to `1` is nice, since `./x.py test -i src/test/run-pass` just does what you (probably) want: builds libstd and libtest in stage 1, and runs run pass tests using that.

**Comment by RalfJung** [comment] 2017-07-28 20:07
>  most of the time you don't need to build the stage1 compiler artifacts

Wouldn't that be an argument to generally make `--stage 1` the default? Wiring this to `-i` seems strange to me.

**Comment by Mark-Simulacrum** [comment] 2017-07-28 20:08
Perhaps, yes. I don't really know why stage 2 is the default.. maybe @alexcrichton can comment there? It seems to be the wrong default...

**Comment by nikomatsakis** [comment] 2017-07-29 17:56
As @Mark-Simulacrum noted, the reason that `--incremental` implies `--stage 1` was that it is what you almost certainly want. That is, we are not able to build stage 2 (from stage 1) incrementally, since the stage 1 compiler will have changed since the last build.

**Comment by RalfJung** [comment] 2017-07-29 20:23
@nikomatsakis As I already said, however, if you run `./x.py build -i`, the entire stage 2 does get built in the stage 1 output directories. The only thing that does not happen is copying it to the stage 2 directories. The default stage should be 0 if you want to make sure that everything that gets built, gets built incrementally.

**Comment by xftroxgpx** [comment] 2017-08-08 07:33
> As I already said, however, if you run ./x.py build -i, the entire stage 2 does get built in the stage 1 output directories. The only thing that does not happen is copying it to the stage 2 directories. 

>the entire stage 2 does get built in the stage 1 output directories

^ That's interesting... I hope that does not happen.
I'm just gonna do this to be sure `./x.py build --incremental --stage 1 --keep-stage 0 -j 4`

**Comment by RalfJung** [comment] 2017-08-08 17:45
> That's interesting... I hope that does not happen.

What's the problem with this?

**Comment by Mark-Simulacrum** [comment] 2017-09-17 18:20
The block that sets [stage 1] when incremental is passed can be removed to fix this. Since stage 2 isn't going to take much time in practice due to copying libs forward, this shouldn't be a problem.

[stage 1]: https://github.com/rust-lang/rust/blob/277476c4fb9e967ca28a7b529dbcf6b348cb787d/src/bootstrap/flags.rs#L316-L319

**Closed** 2018-04-08 21:41 UTC
Labels: A-rustbuild, C-feature-request, E-mentor, WG-infra-rustbuild
