### ISSUE TITLE
Rust homepage cannot demonstrate arithmetic overflow

### ISSUE THREAD

**Issue by vks** [rust-lang/rust#23965] opened 2015-04-02 07:51 UTC
This should probably be harmonized with the behavior of normal operators: Panic if an overflow occurs, and offer wrapping in-place operations.

The example on Rust's frontpage shows this problem.

**Comment by pnkfelix** [comment] 2015-04-03 15:10
triage: P-backcompat-lang (1.0)

**Comment by pnkfelix** [comment] 2015-04-03 16:38
@vks this appears to be working as expected to me.  Can you please show an example where it is not?

(Note that just running the example in the Rust web page may not replicate the expected behavior, in particular because I do not know what flags it compiles with.  The web page may be compiling with optimizations and without `-C debug-assertions=on`.)

**Comment by pnkfelix** [comment] 2015-04-03 16:39
Demo of it working as expected:
```rust
fn main() {
    let mut x = std::i32::MAX - 1;
    x += 2;
    println!("x: {}", x);
}
```

Out of the box:
```
% rustc /tmp/oflo.rs && ./oflo
thread '<main>' panicked at 'arithmetic operation overflowed', /tmp/oflo.rs:3
```

(but adding `-O` will make it skip the checks.)

**Comment by vks** [comment] 2015-04-04 08:35
You are right, that seems to be an issue with the example on the frontpage only. Shouldn't it panic on overflows though, showcasing Rust's default behavior?

**Comment by pnkfelix** [comment] 2015-04-04 09:12
cc @brson @alexcrichton what do you two think?  It seems like disabling optimizations on the homepage could be the simplest answer here...

**Comment by alexcrichton** [comment] 2015-04-04 17:39
What example are we talking about? The one [on our homepage](http://rust-lang.org/) doesn't overflow for me?

**Comment by pnkfelix** [comment] 2015-04-04 19:05
@alexcrichton yes, that is true.  But a trivial modification to the code *should* be able to demonstrate overflow, if we compiled without optimizations.

For example, changing the accumulators initial value to `int::MAX`.  Or, if you prefer, use this program:
```rust
    let program = "+ **** **** **** **** **** **** **** **";
```

I suspect this conversation makes more sense in the context of this [users.rust-lang.org thread](http://users.rust-lang.org/t/is-the-homepage-example-wrong-on-purpose/763)

**Comment by alexcrichton** [comment] 2015-04-05 16:37
Oh dear I may continue to be confused, is this not actually a bug? The `play.rust-lang.org` site optimizes by default, and is this just a question of if we should do that?

**Comment by pnkfelix** [comment] 2015-04-05 16:48
@alexcrichton right: as far as I can tell this has been filed somewhat in error, due to @vks misinterpreting the results that they got when they interactively experimented with the code within the homepage itself.

Its not so bad that `play.rust-lang.org` optimizes by default, since at least in that case, one can see that it is doing so, and can change it to be `-O0` instead.

**Comment by pnkfelix** [comment] 2015-04-05 16:49
triage: P-low (not 1.0)

**Comment by steveklabnik** [comment] 2015-10-29 21:39
Moving to rust-lang/rust-www

**Closed by steveklabnik** 2015-10-29 21:39 UTC
Labels: P-low
