### ISSUE TITLE
Rustc dumping AST in json fails on nightly

### ISSUE THREAD

**Issue by alobb** [rust-lang/rust#33796] opened 2016-05-22 19:33 UTC
Attempting to use the '-Z ast-json' option to nightly fails to print any output.

Steps to reproduce:

```
cargo new --bin temp
cd temp
rustc -Z ast-json src/main.rs
```

I expected to see this happen: JSON output to the terminal

Instead, this happened: Nothing is printed to stdout

## Meta

`rustc --version --verbose`:
rustc 1.10.0-nightly (476fe6eef 2016-05-21)
binary: rustc
commit-hash: 476fe6eefe17db91ff7a60aab34aa67a0a750a18
commit-date: 2016-05-21
host: x86_64-apple-darwin
release: 1.10.0-nightly

I am using the new version of rustup to manage toolchains, but I don't think that is important here.  Just in case:
`rustup --version`:
rustup 0.1.12 (c6e430a 2016-05-12)

`rustup show`:
installed toolchains
--------------------

stable-x86_64-apple-darwin
beta-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.10.0-nightly (476fe6eef 2016-05-21)

**Comment by jseyfried** [comment] 2016-06-10 04:09
This was caused by #33450 and fixed in #33997 (cc @nrc).

**Closed** 2016-06-10 14:54 UTC
