### ISSUE TITLE
cargo new creates additional git folder

### ISSUE THREAD

**Issue by allexgray** [rust-lang/rust#95549] opened 2022-04-01 03:19 UTC
Folder Tree

- .git
- Cargo.toml

### After executing
```cargo new hello``` & ```cargo new app``` 

Folder Tree 

- .git
- app
  - src
  - Cargo.toml
- hello
  - .git
  - src
  - Cargo.toml
- Cargo.toml

#### Root Cargo.toml file
```toml
[workspace]
resolver = "2"
```

This happens once in every folder after executing ```cargo new hello``` & then ```cargo new app```  git was instantiated only in hello (first package of every directory) running ```cargo new package/hello``` will also produce same result.

**Comment by ehuss** [comment] 2022-04-01 23:17
This appears to be a duplicate of https://github.com/rust-lang/cargo/issues/10529

**Closed by ehuss** 2022-04-01 23:17 UTC
