### ISSUE TITLE
`-> impl Fn()` fails with closures used as `FnMut` but actually Fn

### ISSUE THREAD

**Issue by mtak-** [rust-lang/rust#59022] opened 2019-03-08 18:21 UTC
It's clear that the closure could implement `Fn`, but for some reason this code does not compile.

```rust
fn constrain<F: FnMut()>(f: F) -> F {
    f
}

pub fn foo() -> impl Fn() { // works if FnMut
    constrain(|| {})
}
```

Error
```
error[E0277]: expected a `std::ops::Fn<()>` closure, found `[closure@src/lib.rs:6:15: 6:20]`
 --> src/lib.rs:5:17
  |
5 | pub fn foo() -> impl Fn() { // works if FnMut
  |                 ^^^^^^^^^ expected an `Fn<()>` closure, found `[closure@src/lib.rs:6:15: 6:20]`
  |
  = help: the trait `std::ops::Fn<()>` is not implemented for `[closure@src/lib.rs:6:15: 6:20]`
  = note: wrap the `[closure@src/lib.rs:6:15: 6:20]` in a closure with no arguments: `|| { /* code */ }
  = note: the return type of a function must have a statically known size
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a97dd1def3526265d57cfa1f8236e38a

This bit someone at our company who's relatively new to rust while trying to return a `std::iter::Map<.., impl Fn(..)->..>`. The `Iterator::map` function appears to have the same effect as `constrain`.

**Comment by cuviper** [comment] 2019-03-14 19:15
I can reproduce this without `impl Fn`, just by constraining it different ways:

```rust
fn constrain_mut<F: FnMut()>(f: F) -> F { f }
fn constrain<F: Fn()>(f: F) -> F { f }

fn main() {
    // This is fine:
    constrain_mut(constrain(|| {}));
    
    // This complains that `Fn` is not implemented:
    constrain(constrain_mut(|| {}));
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=73333612c7172c48eb68ca7cbc243c3b

**Comment by cuviper** [comment] 2019-04-04 15:55
Closing as a dupe of #26085, which has more details.

**Closed by cuviper** 2019-04-04 15:55 UTC
Labels: A-closures, A-impl-trait
