### ISSUE TITLE
Compiler gives odd context in error that isn't relevant to the actual issue

### ISSUE THREAD

**Issue by rep-nop** [rust-lang/rust#51752] opened 2018-06-24 07:13 UTC
Playground link: https://play.rust-lang.org/?gist=41596a413b9d567407a84423bd63174a&version=stable&mode=debug

Error:
```rs
error[E0308]: mismatched types
 --> src/main.rs:7:39
  |
1 | fn main() {
  |           - expected `()` because of default return type
...
7 |         thingy(if let Some(r) = opt { r } else { None });
  |                                       ^ expected enum `std::option::Option`, found mutable reference
  |
  = note: expected type `std::option::Option<&mut i32>`
             found type `&mut {integer}`
```

For some reason `rustc` appears to include the return type of `main` as if it was important here, even though the expression is passing the return value to the `thingy` function.

**Comment by estebank** [comment] 2018-06-25 23:45
Duplicate of #46302.

**Closed by estebank** 2018-06-25 23:45 UTC
