### ISSUE TITLE
libtest captures stdout&stderr only on first thread.

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#31983] opened 2016-03-01 04:45 UTC
Hi,

When testing anything multithreaded, the output of non-first thread are directly printed on the console.

I wonder if libtest could maybe expose the `set_panic` and `set_print` handlers, so other spawned threads can installed it manually as a workaround.

**Comment by Mark-Simulacrum** [comment] 2019-09-01 13:10
Closing as duplicate of https://github.com/rust-lang/rust/issues/42474.

**Closed by Mark-Simulacrum** 2019-09-01 13:10 UTC
Labels: A-libtest, C-bug, T-libs
