### ISSUE TITLE
Rustdoc does not show `Into` implementations, only `From` implementations

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#39991] opened 2017-02-20 23:53 UTC
This code:

```rust
pub struct Hello;

impl Into<Hello> for String {
    fn into(self) -> Hello {
        Hello
    }
}

impl From<u8> for Hello {
    fn from(_: u8) -> Hello {
        Hello
    }
}
```

Documents the implementation of `From` (presumably because it's implemented for a local type), but not `Into`, (presumably because it's an implemented on a non-local type).

In many cases, this is "OK" because we build the whole documentation and so we can see the implementors of a trait. This doesn't work when the trait is in the standard library, which doesn't regenerate docs with `cargo doc`.

I'm sure this is a duplicate issue, I just haven't found it yet. This can serve as a signpost when we do!

/cc #33417, which will encourage more cases of implementing a trait we don't own parameterized with a type we do own for a type we don't own.

```
rustc 1.15.1 (021bd294c 2017-02-08)
binary: rustc
commit-hash: 021bd294c039bd54aa5c4aa85bcdffb0d24bc892
commit-date: 2017-02-08
host: x86_64-apple-darwin
release: 1.15.1
LLVM version: 3.9
```

**Comment by RReverser** [comment] 2017-04-23 12:17
I can't even get all my `From` implementations documented :(

**Comment by QuietMisdreavus** [comment] 2017-09-29 02:01
Duplicate of https://github.com/rust-lang/rust/issues/25264

**Closed by QuietMisdreavus** 2017-09-29 02:01 UTC
Labels: A-rustdoc, C-bug, T-dev-tools
