### ISSUE TITLE
decimal d128 macro panics in 1.49.0-nightly

### ISSUE THREAD

**Issue by EclipsedSolari** [rust-lang/rust#77804] opened 2020-10-10 21:43 UTC
On 1.49.0-nightly running under Windows 10, the `d128` macro in the [`decimal` crate](https://crates.io/crates/decimal/) panics on use. This does not occur on 1.46.0 (stable).

Repro code is about as minimal as it gets:

```rust
use decimal::d128;

fn main() {
    let test_decimal: d128 = d128!(10);
}
```

On 1.46.0 (stable), this runs without issue. On 1.49.0-nightly (nightly), this panics with the following message:
```thread 'main' panicked at 'attempted to leave type `context::Context` uninitialized, which is invalid', C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\mem\mod.rs:659:9```

### Meta

`rustc --version --verbose`:

- Stable:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-pc-windows-msvc
release: 1.46.0
LLVM version: 10.0
```

- Nightly:
```
rustc 1.49.0-nightly (91a79fb29 2020-10-07)
binary: rustc
commit-hash: 91a79fb29ac78d057d04dbe86be13d5dcc64309a
commit-date: 2020-10-07
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
LLVM version: 11.0
```

<details><summary>Build Log + Backtrace</summary>
<p>

```
C:/Users/<User>/.cargo/bin/cargo.exe run --color=always --package Testbed --bin Testbed
warning: unused variable: `test_decimal`
 --> src\main.rs:4:9
  |
4 |     let test_decimal: d128 = d128!(10);
  |         ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_test_decimal`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: crate `Testbed` should have a snake case name
  |
  = note: `#[warn(non_snake_case)]` on by default
  = help: convert the identifier to snake case: `testbed`

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\Testbed.exe`
thread 'main' panicked at 'attempted to leave type `context::Context` uninitialized, which is invalid', C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\mem\mod.rs:659:9
stack backtrace:
   0:     0x7ff6baefa659 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6baefa659 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6baefa659 - std::sys_common::backtrace::_print_fmt
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff6baefa659 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff6baf07e6b - core::fmt::write
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\core\src\fmt\mod.rs:1080
   5:     0x7ff6baef85d8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\io\mod.rs:1516
   6:     0x7ff6baefce74 - std::sys_common::backtrace::_print
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff6baefce74 - std::sys_common::backtrace::print
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff6baefce74 - std::panicking::default_hook::{{closure}}
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:208
   9:     0x7ff6baefca58 - std::panicking::default_hook
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:227
  10:     0x7ff6baefd72f - std::panicking::rust_panic_with_hook
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:577
  11:     0x7ff6baefd295 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:484
  12:     0x7ff6baefaf1f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff6baefd249 - std::panicking::begin_panic_handler
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:483
  14:     0x7ff6baf07100 - core::panicking::panic_fmt
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\core\src\panicking.rs:85
  15:     0x7ff6baf0704c - core::panicking::panic
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\core\src\panicking.rs:50
  16:     0x7ff6baef16ff - core::mem::uninitialized
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\mem\mod.rs:659
  17:     0x7ff6baef16ff - decimal::dec128::d128::default_context
                               at C:\Users\<User>\.cargo\registry\src\github.com-1ecc6299db9ec823\decimal-2.0.4\src\dec128.rs:482
  18:     0x7ff6baef190e - decimal::dec128::CTX::__init
                               at C:\Users\<User>\.cargo\registry\src\github.com-1ecc6299db9ec823\decimal-2.0.4\src\dec128.rs:26
  19:     0x7ff6baef1f31 - core::ops::function::FnOnce::call_once<fn() -> core::cell::RefCell<decimal::context::Context>,tuple<>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  20:     0x7ff6baef19a3 - std::thread::local::lazy::LazyKeyInner<core::cell::RefCell<decimal::context::Context>>::initialize<core::cell::RefCell<decimal::context::Context>,fn() -> core::cell::RefCell<decimal::context::Context>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:304
  21:     0x7ff6baef2c64 - std::thread::local::fast::Key<core::cell::RefCell<decimal::context::Context>>::try_initialize<core::cell::RefCell<decimal::context::Context>,fn() -> core::cell::RefCell<decimal::context::Context>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:473
  22:     0x7ff6baef2da9 - std::thread::local::fast::Key<core::cell::RefCell<decimal::context::Context>>::get<core::cell::RefCell<decimal::context::Context>,fn() -> core::cell::RefCell<decimal::context::Context>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:456
  23:     0x7ff6baef1955 - decimal::dec128::CTX::__getit
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:183
  24:     0x7ff6baef244c - std::thread::local::LocalKey<core::cell::RefCell<decimal::context::Context>>::try_with<core::cell::RefCell<decimal::context::Context>,closure-0,core::result::Result<decimal::dec128::d128, tuple<>>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:271
  25:     0x7ff6baef23c8 - std::thread::local::LocalKey<core::cell::RefCell<decimal::context::Context>>::with<core::cell::RefCell<decimal::context::Context>,closure-0,core::result::Result<decimal::dec128::d128, tuple<>>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:248
  26:     0x7ff6baef17e4 - decimal::dec128::d128::with_context<closure-0,core::result::Result<decimal::dec128::d128, tuple<>>>
                               at C:\Users\<User>\.cargo\registry\src\github.com-1ecc6299db9ec823\decimal-2.0.4\src\dec128.rs:490
  27:     0x7ff6baef146f - decimal::dec128::{{impl}}::from_str
                               at C:\Users\<User>\.cargo\registry\src\github.com-1ecc6299db9ec823\decimal-2.0.4\src\dec128.rs:194
  28:     0x7ff6baef105e - Testbed::main
                               at D:\Programming\Rust\Testbed\src\main.rs:4
  29:     0x7ff6baef132b - core::ops::function::FnOnce::call_once<fn(),tuple<>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  30:     0x7ff6baef10fb - std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:137
  31:     0x7ff6baef11e1 - std::rt::lang_start::{{closure}}<tuple<>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
  32:     0x7ff6baefd933 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\library\core\src\ops\function.rs:280
  33:     0x7ff6baefd933 - std::panicking::try::do_call
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:381
  34:     0x7ff6baefd933 - std::panicking::try
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panicking.rs:345
  35:     0x7ff6baefd933 - std::panic::catch_unwind
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\panic.rs:382
  36:     0x7ff6baefd933 - std::rt::lang_start_internal
                               at /rustc/91a79fb29ac78d057d04dbe86be13d5dcc64309a\/library\std\src\rt.rs:51
  37:     0x7ff6baef11b3 - std::rt::lang_start<tuple<>>
                               at C:\Users\<User>\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
  38:     0x7ff6baef10c0 - main
  39:     0x7ff6baf34364 - invoke_main
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  40:     0x7ff6baf34364 - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  41:     0x7ffd6b226fd4 - BaseThreadInitThunk
  42:     0x7ffd6c43cec1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\Testbed.exe` (exit code: 101)

Process finished with exit code 101
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-10-10 22:13
This is UB: https://github.com/alkis/decimal/blob/c27d9a165afc55ec98fb4db79b12841df578387e/src/dec128.rs#L199

We now detect this case and raise an error instead of silently invoking UB. Therefore, closing as intended behavior.

**Closed by jonas-schievink** 2020-10-10 22:13 UTC
Labels: C-bug

**Comment by EclipsedSolari** [comment] 2020-10-10 22:40
Makes sense. Thanks for clarifying!
