### ISSUE TITLE
The `char` hyperlinks are broken in section "Methods from Deref<Target=str>" of page: Struct std::string::String

### ISSUE THREAD

**Issue by HongbinZhou** [rust-lang/rust#40727] opened 2017-03-22 06:04 UTC
Hi,

I happen to find that the `char` hyperlinks are broken in section "Methods from Deref<Target=str>" of page: https://doc.rust-lang.org/std/string/struct.String.html

For example, in section: https://doc.rust-lang.org/std/string/struct.String.html#method.char_indices, when you click `char`, you will get a new page https://doc.rust-lang.org/std/string/primitive.char.html which is "Not found".

Thanks!

**Comment by steveklabnik** [comment] 2017-03-22 17:17
I believe this is a duplicate issue, that is, this happens because these docs are rendered in two places and so the links only work in one.

That said, I can't find it right now, so let's keep it open until I do.

**Comment by ollie27** [comment] 2017-03-22 18:29
Dupe of #32129.

**Comment by steveklabnik** [comment] 2017-03-22 19:46
Thanks!

**Closed by steveklabnik** 2017-03-22 19:46 UTC
Labels: A-rustdoc
