### ISSUE TITLE
ICE compiling structopt_derive

### ISSUE THREAD

**Issue by conradludgate** [rust-lang/rust#91787] opened 2021-12-11 12:48 UTC
### Code

(will look into a minimal repro later)

https://github.com/ellie/atuin/commit/d98ee3573d5565f75689da7161d21a1f7ad0003e

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (e6b883c74 2021-12-08)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 --crate-type proc-macro

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `structopt-derive`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0: rust_begin_unwind
   0: rust_begin_unwind
   0: rust_begin_unwind
   0: rust_begin_unwind
   0: rust_begin_unwind
   0: rust_begin_unwind
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   1: core::panicking::panic_fmt
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   1: core::panicking::panic_fmt
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
   2: core::panicking::panic
   2: core::panicking::panic
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
   0: rust_begin_unwind
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/core/src/panicking.rs:48:5
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   3: <alloc::string::String as rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext>>::decode
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   4: <rustc_metadata::locator::CrateLocator>::extract_one
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   5: <rustc_metadata::locator::CrateLocator>::extract_lib
   6: <rustc_metadata::locator::CrateLocator>::find_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   8: <rustc_metadata::creader::CrateLoader>::load
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   8: <rustc_metadata::creader::CrateLoader>::load
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
   7: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
   8: <rustc_metadata::creader::CrateLoader>::load
   9: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  10: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  11: <rustc_metadata::creader::CrateLoader>::maybe_process_path_extern
  12: <rustc_resolve::Resolver>::extern_prelude_get
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  12: <rustc_resolve::Resolver>::extern_prelude_get
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  12: <rustc_resolve::Resolver>::extern_prelude_get
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  13: <rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope
  12: <rustc_metadata::creader::CrateLoader>::process_extern_crate
  13: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  14: <rustc_resolve::Resolver>::resolve_path_with_ribs
  15: <rustc_resolve::imports::ImportResolver>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::resolve_imports
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  14: <rustc_expand::expand::AstFragment>::visit_with::<rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor>
  15: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::visit_ast_fragment_with_placeholders
  16: <rustc_expand::expand::MacroExpander>::collect_invocations
  17: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  18: <rustc_expand::expand::MacroExpander>::expand_crate
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  19: <rustc_session::session::Session>::time::<core::result::Result<rustc_ast::ast::Crate, rustc_errors::ErrorReported>, rustc_interface::passes::configure_and_expand::{closure#1}>
  20: rustc_interface::passes::configure_and_expand
  20: rustc_interface::passes::configure_and_expand
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  20: rustc_interface::passes::configure_and_expand
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  20: rustc_interface::passes::configure_and_expand
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  21: <rustc_interface::queries::Queries>::expansion
  21: <rustc_interface::queries::Queries>::expansion
  21: <rustc_interface::queries::Queries>::expansion
  21: <rustc_interface::queries::Queries>::expansion
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic




error: internal compiler error: unexpected panic
error: internal compiler error: unexpected panic
error: internal compiler error: unexpected panic


error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.


error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

error: internal compiler error: unexpected panic
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md


note: the compiler unexpectedly panicked. this is a bug.
note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu



note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib



note: the compiler unexpectedly panicked. this is a bug.
note: some of the compiler flags provided by cargo are hidden
note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

query stack during panic:

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
note: the compiler unexpectedly panicked. this is a bug.
note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu
end of query stack


error: internal compiler error: unexpected panic
note: some of the compiler flags provided by cargo are hidden



query stack during panic:
end of query stack
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: the compiler unexpectedly panicked. this is a bug.
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu


note: some of the compiler flags provided by cargo are hidden


note: compiler flags: -C prefer-dynamic -C embed-bitcode=no -C debuginfo=2 --crate-type proc-macro
query stack during panic:
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

end of query stack
note: some of the compiler flags provided by cargo are hidden


note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu
query stack during panic:

end of query stack
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md


query stack during panic:
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
end of query stack

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu


note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by matthiaskrgr** [comment] 2021-12-11 13:01
duplicate of https://github.com/rust-lang/rust/issues/91663

**Closed** 2021-12-11 14:40 UTC
Labels: I-ICE, T-compiler, C-bug
