### ISSUE TITLE
rustc `master` has a flaky failure when compiled against LLVM `main`

### ISSUE THREAD

**Issue by durin42** [rust-lang/rust#99432] opened 2022-07-18 18:43 UTC
LLVM commit [ede600377cb6df1bef71f070130d8cfe734cc5b7](https://github.com/llvm/llvm-project/commit/ede600377cb6df1bef71f070130d8cfe734cc5b7) moved some stuff from being `ManagedStatic` to just thread-local static, and it seems we're not correctly blocking on LLVM threads being complete. If I apply this:

```diff
diff --git a/compiler/rustc_driver/src/lib.rs b/compiler/rustc_driver/src/lib.rs
index b71cdad718a..96f34c9ec3b 100644
--- a/compiler/rustc_driver/src/lib.rs
+++ b/compiler/rustc_driver/src/lib.rs
@@ -1336,6 +1336,10 @@ pub fn main() -> ! {
         let end_rss = get_resident_set_size();
         print_time_passes_entry("total", start_time.elapsed(), start_rss, end_rss);
     }
-
-    process::exit(exit_code)
+    if 1 == 200 {
+        process::exit(exit_code)
+    }
+    unsafe {
+    libc::_exit(exit_code)
+    }
 }
```

then I no longer see the failure in 10,000 attempts, which [always looks like this when it happens](https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/11871#0181e78f-2ce6-4ee3-8508-21556f4f7ef4):
```
---- [ui] src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs stdout ----
 
error: Error: expected failure status (Some(1)) but received status Some(101).
status: exit status: 101
command: "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs" "-Zthreads=1" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Clinker=/usr/bin/clang-13" "--target" "thumbv8m.main-none-eabi" "--crate-type" "lib" "-L" "/var/lib/buildkite-agent/builds/rust-llvm-integrate/llvm-project/rust-llvm-integrate-prototype/build/x86_64-unknown-linux-gnu/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack/auxiliary"
stdout: none
--- stderr -------------------------------
error: <unknown>:0:0: in function test i32 (i32, i32, i32, i32, i32): call to non-secure function would require passing arguments on stack
 
error: aborting due to previous error
 
LLVM ERROR: Do not know how to split the result of this operator!
------------------------------------------
 
 
 
failures:
[ui] src/test/ui/cmse-nonsecure/cmse-nonsecure-call/params-on-stack.rs
```

On our CI VM (which is fairly small) this appears to happen roughly a third or half the time. On my workstation it's less than 1% of the time, best guess about 0.3% of the time, so 10k runs is necessary to reliably see the issue.

I'll hopefully have time to fix this in the near future, but wanted to record this ASAP so we don't forget when the LLVM upgrade is due.

**Comment by nikic** [comment] 2022-07-19 16:54
I think the problem is that https://github.com/rust-lang/rust/blob/a289cfcfb32593c63d75f113547f63ffe2dde285/compiler/rustc_codegen_ssa/src/back/write.rs#L1534 just returns. We also have a different CodegenAborted message that does wait for other workers: https://github.com/rust-lang/rust/blob/a289cfcfb32593c63d75f113547f63ffe2dde285/compiler/rustc_codegen_ssa/src/back/write.rs#L1489

**Comment by nikic** [comment] 2022-07-20 08:58
I saw a related failure in src/test/ui/invalid/invalid-llvm-passes.rs and came up with this patch: https://gist.github.com/nikic/25518d8c0373145d586b7d6dfd602676

That *does* fix the issue for the invalid-llvm-passes.rs test, but *doesn't* fix it for the params-on-stack.rs test. I think this is because this is a codegen error that gets reported in a different way.

**Comment by nikic** [comment] 2022-07-20 09:25
Okay, I was quite off track here. I believe the actual problem is that we emit a fatal error in the LLVM worker, which will send an SharedEmitterMessage::Fatal message, and then raise a fatal error in the main thread: https://github.com/rust-lang/rust/blob/03d488b48af9f66b91e9400387f781b82411fa82/compiler/rustc_codegen_ssa/src/back/write.rs#L1819 This will unwind and exit the process. However, there might still be other LLVM threads active, and more importantly, I believe the thread that emitted the diagnostic (if it is a codegen diagnostic) will also continue running.

**Comment by nikic** [comment] 2022-07-20 14:31
I've included a fix for this in https://github.com/rust-lang/rust/pull/99512. Turned out to be less straightforward than I hoped.

**Closed** 2022-07-29 04:23 UTC
