### ISSUE TITLE
Latest changes in nightly cause it to produce executable named "-pie" in the crate directory.

### ISSUE THREAD

**Issue by berkus** [rust-lang/rust#48884] opened 2018-03-09 18:20 UTC
Updated to `rustc 1.26.0-nightly (2789b067d 2018-03-06)` via rustup.

I have a [custom target file](https://github.com/metta-systems/vesper/blob/rust-boot-experiments/targets/aarch64-vesper-metta.json) and additional [cargo configs](https://github.com/metta-systems/vesper/blob/rust-boot-experiments/.cargo/config#L3-L9) which specify additional rustc arguments.

Now if I run 
```
export RUST_TARGET_PATH=$(pwd)/targets/
xargo run --target aarch64-vesper-metta
```

The build will succeed but then fail to run qemu because
```
     Running `qemu-system-aarch64 -M raspi3 -d in_asm -serial stdio -kernel target/aarch64-vesper-metta/debug/vesper`
qemu-system-aarch64: could not load kernel 'target/aarch64-vesper-metta/debug/vesper'
```

Instead, there's a file named `-pie` in the directory where xargo was run from.

To fix this I had to change the target json file with these options:

```
-  "linker-is-gnu": true,
+  "linker-is-gnu": false,
```

I'm afraid this could subtly break my builds elsewhere, as the linker is, in fact, GNU ld.

I believe this is related to the latest -pie/-no-pie patches which somehow interfere with custom cargo linker arguments specifications (where `-pie` ends up landing instead of output file name).

**Comment by sfackler** [comment] 2018-03-09 18:21
Seems like #48076 is likely to be related? @canarysnort01

**Comment by berkus** [comment] 2018-03-09 18:22
That's my suspicion @sfackler

**Comment by canarysnort01** [comment] 2018-03-10 00:40
hmm my change shouldn't have impacted when the -pie flag was sent, only added the -no-pie flag. what version were you using before?

**Comment by canarysnort01** [comment] 2018-03-10 00:52
Could you please build with ```RUST_LOG=rustc_trans=info xargo build --target aarch64-vesper-metta``` and post the output related to the link step (after the ```preparing CrateTypeExecutable to ...``` line)

**Comment by nikomatsakis** [comment] 2018-03-15 14:42
triage: P-high

Not assigning this to anyone immediately, since @canarysnort01 seems to be on it -- @berkus, if you could take a shot at supplying that debug output it would be very helpful, thanks. =)

**Comment by berkus** [comment] 2018-03-22 08:57
Yes, sorry, will generate the debug log today.

**Comment by berkus** [comment] 2018-03-22 10:47
```
 INFO 2018-03-22T10:46:46Z: rustc_trans::back::link: preparing CrateTypeExecutable to "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/vesper-b63e9d46780781be"
 INFO 2018-03-22T10:46:46Z: rustc_trans::back::link: "aarch64-unknown-linux-musl-ld" "-nodefaultlibs" "-nostdlib" "-L" "/Users/berkus/.xargo/lib/rustlib/aarch64-vesper-metta/lib" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/vesper-b63e9d46780781be.vesper2.rcgu.o" "-o" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/vesper-b63e9d46780781be" "--gc-sections" "-no-pie" "-z,relro,-z,now" "-O1" "-L" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps" "-L" "/Users/berkus/Hobby/Metta/vesper/target/release/deps" "-L" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/build/vesper-6d63ef12987ec0c8/out/src/boot" "-L" "/Users/berkus/.xargo/lib/rustlib/aarch64-vesper-metta/lib" "-Bstatic" "--whole-archive" "-l" "aarch64" "--no-whole-archive" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/librlibc-ffb0a67b04c0940a.rlib" "-static" "-Tlinker/aarch64.ld" "-Bdynamic"
 INFO 2018-03-22T10:46:46Z: rustc_trans::back::link: linker stderr:
aarch64-unknown-linux-musl-ld: warning: -z ,relro,-z,now ignored.

 INFO 2018-03-22T10:46:46Z: rustc_trans::back::link: linker stdout:

    Finished release [optimized + debuginfo] target(s) in 1.69 secs
     Running `/Users/berkus/Hobby/Metta/vesper/.cargo/runscript.sh target/aarch64-vesper-metta/release/vesper`
aarch64-unknown-linux-musl-objcopy: 'target/aarch64-vesper-metta/release/vesper': No such file
```

**Comment by nikomatsakis** [comment] 2018-03-22 14:12
@canarysnort01 does that contain the info you needed?

**Comment by canarysnort01** [comment] 2018-03-23 01:54
Yes, that helps. I think this is what is happening:

- Even though you have set in your target file to produce position-independent-executables (pass the "-pie" flag), the code overrides this because it sees "-static" on the linker's command line and decides not to generate PIE.
- My PR made it pass "-no-pie" in this case, and fall back to removing -no-pie if the link fails
- For some reason this seems to be confusing ld instead of causing it to generate an error

@berkus Can you confirm this by manually running:

```"aarch64-unknown-linux-musl-ld" "-nodefaultlibs" "-nostdlib" "-L" "/Users/berkus/.xargo/lib/rustlib/aarch64-vesper-metta/lib" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/vesper-b63e9d46780781be.vesper2.rcgu.o" "-o" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/vesper-b63e9d46780781be" "--gc-sections" "-z,relro,-z,now" "-O1" "-L" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps" "-L" "/Users/berkus/Hobby/Metta/vesper/target/release/deps" "-L" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/build/vesper-6d63ef12987ec0c8/out/src/boot" "-L" "/Users/berkus/.xargo/lib/rustlib/aarch64-vesper-metta/lib" "-Bstatic" "--whole-archive" "-l" "aarch64" "--no-whole-archive" "/Users/berkus/Hobby/Metta/vesper/target/aarch64-vesper-metta/release/deps/librlibc-ffb0a67b04c0940a.rlib" "-static" "-Tlinker/aarch64.ld" "-Bdynamic"```

(same command line without -no-pie) to see if it works correctly, and also a ```aarch64-unknown-linux-musl-ld --version```?

I need to look more into ld to see if -no-pie is even necessary for it, I think maybe the default pie stuff might only be applicable with the gcc front-end. If so, I think the fix would be to change the code not to generate -no-pie if linking with ld.

**Comment by canarysnort01** [comment] 2018-03-24 10:14
nm, I think I was able to reproduce this. I don't see -no-pie documented for ld so I think that is the problem. I'll work on a fix.

**Closed** 2018-03-29 00:41 UTC
Labels: P-high, T-compiler, regression-from-stable-to-nightly

**Comment by berkus** [comment] 2018-04-02 09:57
Thanks, I will test this asap!

**Comment by berkus** [comment] 2018-04-02 11:26
Works! Thank you!
