### ISSUE TITLE
Wrong function pointers in DynamicLib::symbol

### ISSUE THREAD

**Issue by Kintaro** [rust-lang/rust#18796] opened 2014-11-09 03:45 UTC
When I use these two files
```
// main.rs, rustc -C prefer-dynamic main.rs
use std::dynamic_lib::DynamicLibrary;
use std::mem::transmute;
use std::path::posix::Path;

fn main() {
    let filename = Path::new("./libfoo.so");
   
    unsafe {
        match DynamicLibrary::open(Some(filename)).and_then(|library| library.symbol("bar")) {
            Ok(symbol) => {
                let f = transmute::<*mut u8, extern fn() -> u32>(symbol);
                println!("here: {}", f());
            },
            _ => ()
        }
    }
}
```
and
```
// foo.rs, rustc -C prefer-dynamic --crate-type dylib foo.rs
#[no_mangle]
pub extern fn bar() -> u32 {
    42
}
```

I get this error:

```
[1]    6914 illegal hardware instruction (core dumped)  ./main
```

**Comment by steveklabnik** [comment] 2015-01-27 19:07
Closing as intended behavior.

**Closed by steveklabnik** 2015-01-27 19:07 UTC
