### ISSUE TITLE
error: internal compiler error: add_outlives_bounds: unexpected regions

### ISSUE THREAD

**Issue by smallreset** [rust-lang/rust#109208] opened 2023-03-16 08:27 UTC
error: internal compiler error: /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010\compiler\rustc_infer\src\infer\outlives\env.rs:145:26: add_outlives_bounds: unexpected regions

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010\compiler\rustc_errors\src\lib.rs:1644:9
stack backtrace:
   0:     0x7ffba9dd6c32 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1c4010effb789961
   1:     0x7ffba9e1539b - core::fmt::write::hc94abc869942d9f3
   2:     0x7ffba9dcbeba - <std::io::IoSliceMut as core::fmt::Debug>::fmt::hec2b8caa3d4506f4
   3:     0x7ffba9dd697b - std::sys::common::alloc::realloc_fallback::h44ee2e364c6ddfc3
   4:     0x7ffba9dda2d9 - std::panicking::default_hook::h435f9ab809f76d93
   5:     0x7ffba9dd9f5b - std::panicking::default_hook::h435f9ab809f76d93
   6:     0x7ffb6b3d68de - rustc_driver_impl[8191dd4a2de3396e]::describe_lints
   7:     0x7ffba9ddac42 - std::panicking::rust_panic_with_hook::hdff5151369ed00f4
   8:     0x7ffb6d793213 - <rustc_middle[9c2f7d0e6aac5258]::ty::print::pretty::ForceTrimmedGuard as core[1c8d95a93626d45b]::ops::drop::Drop>::drop
   9:     0x7ffb6d792f39 - <rustc_middle[9c2f7d0e6aac5258]::ty::print::pretty::ForceTrimmedGuard as core[1c8d95a93626d45b]::ops::drop::Drop>::drop
  10:     0x7ffb6d7a86c9 - <rustc_middle[9c2f7d0e6aac5258]::traits::solve::Response as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  11:     0x7ffb6d772439 - <rustc_middle[9c2f7d0e6aac5258]::mir::GeneratorInfo as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  12:     0x7ffb6d76e650 - <rustc_middle[9c2f7d0e6aac5258]::mir::GeneratorInfo as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  13:     0x7ffb6d76e1d2 - <rustc_middle[9c2f7d0e6aac5258]::mir::GeneratorInfo as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  14:     0x7ffb6d7e3b8a - rustc_middle[9c2f7d0e6aac5258]::util::bug::bug_fmt
  15:     0x7ffb6d7e22fd - rustc_middle[9c2f7d0e6aac5258]::mir::spanview::escape_attr
  16:     0x7ffb6d7e22c1 - rustc_middle[9c2f7d0e6aac5258]::mir::spanview::escape_attr
  17:     0x7ffb6d7e3ac8 - rustc_middle[9c2f7d0e6aac5258]::util::bug::bug_fmt
  18:     0x7ffb6d7e3a45 - rustc_middle[9c2f7d0e6aac5258]::util::bug::bug_fmt
  19:     0x7ffb6a6a2c51 - <rustc_middle[9c2f7d0e6aac5258]::ty::Visibility as rustc_privacy[e828782cfd4e85e0]::VisibilityLike>::new_min
  20:     0x7ffb6a72abf3 - <rustc_hir_analysis[14fd5c16ca0a0472]::collect::generics_of::has_late_bound_regions::LateBoundRegionsDetector as rustc_hir[cfe12899dbc7776a]::intravisit::Visitor>::visit_ty
  21:     0x7ffb6940aa02 - <(rustc_middle[9c2f7d0e6aac5258]::ty::Ty, rustc_type_ir[76052faf48bc9e48]::TyVid) as rustc_infer[afded1ac8327eacd]::infer::nll_relate::VidValuePair>::vid
  22:     0x7ffb6a6d64d2 - rustc_hir_analysis[14fd5c16ca0a0472]::check::check::check_abi
  23:     0x7ffb6a6db300 - rustc_hir_analysis[14fd5c16ca0a0472]::check::check::check_abi
  24:     0x7ffb697760a6 - <&rustc_data_structures[b17d4f450b2b3392]::unord::UnordSet<rustc_span[d687cf4323ae4e7c]::def_id::LocalDefId> as rustc_serialize[70147b9799dbe0ee]::serialize::Decodable<rustc_query_impl[ca14707135d96a86]::on_disk_cache::CacheDecoder>>::decode
  25:     0x7ffb6966e600 - <rustc_query_impl[ca14707135d96a86]::Queries as rustc_middle[9c2f7d0e6aac5258]::ty::query::QueryEngine>::try_mark_green
  26:     0x7ffb693da60e - <rustc_hir_analysis[14fd5c16ca0a0472]::check::check::check_opaque_for_inheriting_lifetimes::ProhibitOpaqueVisitor as rustc_type_ir[76052faf48bc9e48]::visit::TypeVisitor<rustc_middle[9c2f7d0e6aac5258]::ty::context::TyCtxt>>::visit_ty
  27:     0x7ffb6a6a703b - rustc_hir_analysis[14fd5c16ca0a0472]::check_crate
  28:     0x7ffb68ca66df - rustc_interface[4baad7117af5d0c6]::passes::analysis
  29:     0x7ffb697ebff2 - <&rustc_data_structures[b17d4f450b2b3392]::unord::UnordSet<rustc_span[d687cf4323ae4e7c]::def_id::LocalDefId> as rustc_serialize[70147b9799dbe0ee]::serialize::Decodable<rustc_query_impl[ca14707135d96a86]::on_disk_cache::CacheDecoder>>::decode
  30:     0x7ffb6966a7e1 - <rustc_query_impl[ca14707135d96a86]::Queries as rustc_middle[9c2f7d0e6aac5258]::ty::query::QueryEngine>::try_mark_green
  31:     0x7ffb68c65a30 - <rustc_middle[9c2f7d0e6aac5258]::ty::SymbolName as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  32:     0x7ffb68c64787 - <rustc_middle[9c2f7d0e6aac5258]::ty::SymbolName as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  33:     0x7ffb68c62699 - <rustc_middle[9c2f7d0e6aac5258]::ty::SymbolName as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  34:     0x7ffb68c61afa - rustc_driver_impl[8191dd4a2de3396e]::args::arg_expand_all
  35:     0x7ffb68c8222d - <rustc_middle[9c2f7d0e6aac5258]::ty::SymbolName as core[1c8d95a93626d45b]::fmt::Debug>::fmt
  36:     0x7ffba9deca8c - std::sys::windows::thread::Thread::new::h4295e347c8eee272
  37:     0x7ffc37807614 - BaseThreadInitThunk
  38:     0x7ffc381026a1 - RtlUserThreadStart

note: rustc 1.70.0-nightly (ab654863c 2023-03-15) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C codegen-units=1

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [check_mod_item_types] checking item types in module `de`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `bincode` (lib)
warning: build failed, waiting for other jobs to finish...

**Comment by lqd** [comment] 2023-03-16 08:36
This is a duplicate of #109199 so I'll close it as such. This has already been fixed on master, but too late to appear in today's nightly. The fix will be available in the tomorrow's nightly though.

Thanks for opening an issue!

**Closed by lqd** 2023-03-16 08:36 UTC
Labels: I-ICE, T-compiler, C-bug
