### ISSUE TITLE
RPIT with 'static bound lifetime capture issue with generic parameter

### ISSUE THREAD

**Issue by drdo** [rust-lang/rust#125075] opened 2024-05-13 14:18 UTC
I tried this code:

```rust
pub fn bar(x: &str) -> impl Iterator<Item=String> + 'static {
    foo(x)
}
            
pub fn foo<A>(_arg: A) -> impl Iterator<Item=String> + 'static {
    std::iter::empty()
}
```

I expected to see this happen:
Successful compilation.

Instead, this happened:
```
error[E0700]: hidden type for `impl Iterator<Item = String> + 'static` captures lifetime that does not appear in bounds
 --> main.rs:4:5
  |
3 | pub fn bar(x: &str) -> impl Iterator<Item=String> + 'static {
  |               ----     ------------------------------------ opaque type defined here
  |               |
  |               hidden type `impl Iterator<Item = String> + 'static` captures the anonymous lifetime defined here
4 |     foo(x)
  |     ^^^^^^

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0700`.
  ```

The RPIT returned from `foo` has a `'static` bound so it is unclear why there would be any complaints about
capturing a smaller lifetime (which still doesn't happen in this case as the RPIT returned from `foo` does not depend on `_arg` at all).

If the definition of `foo` above is changed to (by replacing the generic parameter `A` with `&str`):
```rust
pub fn foo(_arg: &str) -> impl Iterator<Item=String> + 'static {
    std::iter::empty()
}
```
then the code compiles without a problem.
### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (ef0027897 2024-05-12)
binary: rustc
commit-hash: ef0027897d2e9014766fb47dce9ddbb925d2f540
commit-date: 2024-05-12
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.4
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by fmease** [comment] 2024-05-13 15:08
Closing as dupe of #106684 (which is probably a dupe itself).

**Closed by fmease** 2024-05-13 15:08 UTC
Labels: T-compiler, A-impl-trait, C-bug, needs-triage
