### ISSUE TITLE
ICE: librustc_trans/mir/constant.rs:682: Unexpected non-fat-pointer operand

### ISSUE THREAD

**Issue by fenollp** [rust-lang/rust#38942] opened 2017-01-09 10:31 UTC
Here is the Travis job that fails: https://travis-ci.org/fenollp/minrs/jobs/190200414
Which is part of this build https://travis-ci.org/fenollp/minrs/builds/190200409

```
$ rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)
$ cargo --version
cargo 0.15.0-nightly (298a012 2016-12-20)
```

This only happens on `i686-apple-darwin` & on Travis' OSX hardware.

Possibly linked: https://github.com/rust-lang/rust/issues/38727 https://github.com/rust-lang/rust/issues/16383 https://github.com/rust-lang/rust/issues/37437 https://github.com/rust-lang/rust/issues/38735

**Comment by nagisa** [comment] 2017-01-09 11:53
Inline assembly cannot be an issue as this is on stable rustc. https://github.com/rust-lang/rust/issues/38727 is fixed on nightly, so you’ll have to test/do travis run on i686 apple with nightly rustc.

**Comment by fenollp** [comment] 2017-01-09 14:08
Here's a Travis run on nightly rustc with i686 apple platform: https://travis-ci.org/fenollp/minrs/jobs/190236515#L233

That bug looks fixed. However now I have

```
error: internal compiler error: /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustc_trans/mir/constant.rs:682: Unexpected non-fat-pointer operand
```

which Google doesn't seem to know about!

**Comment by nagisa** [comment] 2017-01-10 06:26
cc @eddyb @Mark-Simulacrum stuff related to type_is_immediate change could have caused this.

**Comment by eddyb** [comment] 2017-01-10 09:54
#38854 hasn't landed so it's not *that*. @dotdash may have also ran into this but I'm not sure.

**Comment by nikomatsakis** [comment] 2017-01-12 17:47
So all it takes to reproduce is building https://github.com/fenollp/minrs on an i686-mac?

**Comment by nikomatsakis** [comment] 2017-01-12 17:47
Or must it specifically be run on travis? If so, we should try to isolate what is different there!

**Comment by nikomatsakis** [comment] 2017-01-12 21:32
Assigning to @pnkfelix for now, who will attempt to reproduce with a cross-compile.

**Comment by pnkfelix** [comment] 2017-01-13 13:33
Hmm, well I think I have the cross-compile set up now (I wrote the steps I followed below), but I think I am hitting the first ICE described ("internal compiler error: ../src/librustc_trans/mir/operand.rs:82: impossible case reached"), so I have not yet replicated the "Unexpected non-fat-pointer operand").

### Steps to set up cross compile

  1. On a Mac, you need to make sure you have the ability to cross-compile to i686-apple-darwin. I used https://rustup.rs/ with a default of the nightly channel as an easy way to get that set up.

```
% rustup default nightly
% rustup target add i686-apple-darwin
%
```

2. With cross compiling support established, we do a build to demonstrate the ICE:

```
% cargo build -j1 --target i686-apple-darwin 
   [...]
   Compiling cocoa v0.5.2
error: internal compiler error: /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustc_trans/mir/operand.rs:82: impossible case reached
```

**Comment by eddyb** [comment] 2017-01-13 14:19
Can you use `RUST_LOG=rustc_trans::base` to reduce it to at least one function? (This works on release compilers too, I think, since it's `info!`)

**Comment by pnkfelix** [comment] 2017-01-13 14:28
Talked to @eddyb on IRC. The last line of output from the rust log for `rustc_trans::base` is:

```
INFO:rustc_trans::base: trans_instance(<appkit::NSEventMask as std::fmt::Debug>::fmt::dummy::fmt)
```

**Comment by fenollp** [comment] 2017-01-13 14:28
I noticed this before, might be of interest:

```
   Compiling cocoa v0.3.3
```

appears when the constant.rs bug gets triggered, however the operand.rs one has `cocoa v0.5.2`.

**Comment by pnkfelix** [comment] 2017-01-13 16:52
(Also reproduced minimized example against a more recent nightly: `rustc 1.16.0-nightly (1a2ed98d3 2017-01-13)`)

**Comment by eddyb** [comment] 2017-01-13 16:56
Oh this is a non-immediate `CEnum`, I bet #38854 fixes it, and I can't think of a nicer solution.

**Comment by nagisa** [comment] 2017-01-13 17:02
The more-minimal version. Thanks for minimizing @pnkfelix!

```rust
#![crate_type = "rlib"]

#[repr(u64)]
pub enum NSEventType {
    NSEventTypePressure,
}

pub const A: u64 = 1 << (NSEventType::NSEventTypePressure as u64);

fn banana() -> u64 {
    A
}
```

**Comment by pnkfelix** [comment] 2017-01-13 17:02
(if #38854 does fix it, we probably should try to encode this as a regression test if possible, assuming we can readily do cross target unit test.)

**Comment by eddyb** [comment] 2017-01-13 17:07
Do you even need the shift? I bet it's just the cast. The test doesn't need to be special as long as we build for 32-bit targets, it will get caught.

**Comment by nagisa** [comment] 2017-01-14 07:20
Tried compiling the test case compiled with commit d70cd49071 (inlcudes the https://github.com/rust-lang/rust/pull/38854), but it still ICEs.

**Closed** 2017-01-21 03:25 UTC
Labels: E-needstest, I-ICE, P-high, regression-from-stable-to-nightly, T-compiler
