### ISSUE TITLE
Rustdoc lists functions for each stability level

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#23487] opened 2015-03-18 19:35 UTC
[ptr Functions section](http://doc.rust-lang.org/std/ptr/index.html#functions)

**Comment by steveklabnik** [comment] 2015-03-18 22:23
To be clear, the issue here is that they're being duplicated, yes? I think there's also something about these being `use .. as` too.

I think we may have an issue open for this already.

**Comment by dfockler** [comment] 2015-03-19 22:30
This is the other issue https://github.com/rust-lang/rust/issues/23054

**Comment by alexcrichton** [comment] 2015-04-07 23:45
When this was still a part of `std::ptr` I think that this was a duplicate of #23054, so closing in favor of that.

**Closed by alexcrichton** 2015-04-07 23:45 UTC
Labels: A-rustdoc
