### ISSUE TITLE
`ch as u32 < 0x80` syntax misinterpreted as a type parameter

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#20078] opened 2014-12-20 17:04 UTC
Code like this:
```rust
    pub fn push(&mut self, ch: char) {
        if ch as u32 < 0x80 {
            // ...
```

Gives a parse error:

```
error: expected type, found `0x80`
        if ch as u32 < 0x80 {
                       ^~~~
```

Adding parentheses to disambiguate works around the issue:
```rust
    pub fn push(&mut self, ch: char) {
        if (ch as u32) < 0x80 {
            // ...
```

I understand that `u32` is being parsed as a type and so `<` is assumed to be the start of type parameters. But maybe when that fails, the parser should backtrack and try to parse `<` as an operator?

**Comment by bombless** [comment] 2015-04-14 14:57
I think this is a little similar as https://github.com/rust-lang/rust/issues/22644 .
I imagine if we change the parser's front-end to parse this ideally, of course it is potentially a breaking-change, but I doubt if it would actually break a single line of existing code.

**Comment by huonw** [comment] 2016-01-08 07:15
There's been more discussion on #22644, so I'm closing this as a dupe of that.

**Closed by huonw** 2016-01-08 07:15 UTC
Labels: A-diagnostics, A-parser
