### ISSUE TITLE
nightly-2017-04-30 ICE regression - thread 'rustc' panicked at 'assertion failed: !unsize'

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#41660] opened 2017-04-30 19:55 UTC
https://github.com/PistonDevelopers/image currently doesn't compile. trying to minimize right now.

**Comment by est31** [comment] 2017-04-30 19:57
Dupe of  #41604, fixed by #41651

**Comment by Mark-Simulacrum** [comment] 2017-04-30 19:57
Thanks! This is a duplicate of #41604.

**Closed** 2017-04-30 19:57 UTC
Labels: I-ICE
