### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by melody-ju** [rust-lang/rust#110580] opened 2023-04-20 05:58 UTC
Branch is melody/weather-polish, commit 40196b500260c547e2bdfa50d949e93e83ff83ef

```
PS C:\Users\melody.ju\ark-modules> cargo build --release
   Compiling global-weather-behavior-impl v0.1.0 (C:\Users\melody.ju\ark-modules\sandbox\t2\global-weather-behavior-impl)
error: internal compiler error: compiler\rustc_infer\src\infer\region_constraints\mod.rs:568:17: cannot relate bound region: ReLateBound(DebruijnIndex(0), BoundRegion { var: 2, kind: BrNamed(DefId(0:870 ~ global_weather_behavior_impl[fb52]::clouds::{impl#3}::init::'_#2), '_) }) <= ReLateBound(DebruijnIndex(0), BoundRegion { var: 2, kind: BrNamed(DefId(50:15432 ~ sandbox_api[4c46]::behavior::{impl#33}::'_#2), '_) })

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\compiler\rustc_errors\src\lib.rs:987:33
stack backtrace:
   0:     0x7ff999af9d02 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h792a027c2747e99d
   1:     0x7ff999b3570b - core::fmt::write::h5d1fd4698cef7a98
   2:     0x7ff999aecdfa - <std::io::IoSlice as core::fmt::Debug>::fmt::hba64fac32bc54252
   3:     0x7ff999af9a4b - std::sys::common::alloc::realloc_fallback::hfe62d187ace61bcd
   4:     0x7ff999afd3f9 - std::panicking::default_hook::hc7b7ee9dc8a166a2
   5:     0x7ff999afd07b - std::panicking::default_hook::hc7b7ee9dc8a166a2
   6:     0x7ff94679ec34 - rustc_driver[6fce53b951639747]::describe_lints
   7:     0x7ff999afdd5f - std::panicking::rust_panic_with_hook::h80ad08272951bba3
   8:     0x7ff946af9a73 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
   9:     0x7ff946af7c79 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  10:     0x7ff946af7c19 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  11:     0x7ff946af7c09 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  12:     0x7ff946af7270 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  13:     0x7ff946af70c9 - <<rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt>::construct_generic_bound_failure::SubOrigin as core[ab957a7126758ba9]::fmt::Debug>::fmt
  14:     0x7ff946aa27e9 - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  15:     0x7ff946aa284d - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  16:     0x7ff946aa19ff - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  17:     0x7ff946aa19a8 - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  18:     0x7ff946aa1966 - <rustc_infer[1d2eee8e62f18ba3]::traits::project::ProjectionCacheEntry as core[ab957a7126758ba9]::fmt::Debug>::fmt
  19:     0x7ff944d6bde8 - rustc_infer[1d2eee8e62f18ba3]::traits::util::supertraits
  20:     0x7ff944d9f1bd - <rustc_infer[1d2eee8e62f18ba3]::infer::outlives::verify::VerifyBoundCx>::alias_bound
  21:     0x7ff944d96748 - <rustc_infer[1d2eee8e62f18ba3]::infer::equate::Equate as rustc_middle[484603f84bd5edf8]::ty::relate::TypeRelation>::tys
  22:     0x7ff943f9eb38 - rustc_trait_selection[48a8fb49e3ee715f]::traits::wf::object_region_bounds
  23:     0x7ff943fb6358 - rustc_trait_selection[48a8fb49e3ee715f]::traits::structural_match::search_for_adt_const_param_violation
  24:     0x7ff9473d4f08 - <rustc_trait_selection[48a8fb49e3ee715f]::traits::wf::Elaborate as core[ab957a7126758ba9]::fmt::Debug>::fmt
  25:     0x7ff9473bae09 - <rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::method_chain::CollectAllMismatches as rustc_middle[484603f84bd5edf8]::ty::relate::TypeRelation>::consts
  26:     0x7ff94744bed0 - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::suggestions::TypeErrCtxtExt>::report_closure_arg_mismatch
  27:     0x7ff94745ee96 - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::TypeErrCtxtExt>::report_selection_error
  28:     0x7ff94746b537 - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::InferCtxtPrivExt>::report_fulfillment_error
  29:     0x7ff94745b96d - <rustc_infer[1d2eee8e62f18ba3]::infer::error_reporting::TypeErrCtxt as rustc_trait_selection[48a8fb49e3ee715f]::traits::error_reporting::TypeErrCtxtExt>::report_fulfillment_errors
  30:     0x7ff944c53ec8 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::probe_instantiate_query_response
  31:     0x7ff944c3fee9 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::probe_instantiate_query_response
  32:     0x7ff944c05b03 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  33:     0x7ff944c6466f - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::check_struct_path
  34:     0x7ff944c056b5 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  35:     0x7ff944c2a271 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::demand_coerce
  36:     0x7ff944cc4e67 - <rustc_hir_typeck[726d463412e15d63]::writeback::WritebackCx as rustc_hir[a0ba7d6a2d0a2d5c]::intravisit::Visitor>::visit_ty
  37:     0x7ff944ce02e7 - <rustc_hir_typeck[726d463412e15d63]::inherited::Inherited as core[ab957a7126758ba9]::ops::deref::Deref>::deref
  38:     0x7ff94546cd05 - <rustc_middle[484603f84bd5edf8]::ty::Visibility as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  39:     0x7ff944c9acb4 - <rustc_hir_typeck[726d463412e15d63]::fn_ctxt::FnCtxt>::resolve_fully_qualified_call
  40:     0x7ff943a132d1 - <rustc_hir_typeck[726d463412e15d63]::inherited::Inherited>::build
  41:     0x7ff943d47014 - <core[ab957a7126758ba9]::option::Option<rustc_middle[484603f84bd5edf8]::middle::privacy::Level> as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  42:     0x7ff943e5c562 - <rustc_query_impl[78e525705bed6840]::Queries as rustc_middle[484603f84bd5edf8]::ty::query::QueryEngine>::try_mark_green
  43:     0x7ff943982d9a - rustc_hir_analysis[eefa32d64dd8432c]::hir_wf_check::provide
  44:     0x7ff94396dc23 - rustc_hir_analysis[eefa32d64dd8432c]::check_crate
  45:     0x7ff943a91c2d - rustc_interface[8244ed7f36050a97]::passes::analysis
  46:     0x7ff943de42f0 - <core[ab957a7126758ba9]::option::Option<rustc_middle[484603f84bd5edf8]::middle::privacy::Level> as rustc_privacy[7356e04eccd2b68]::VisibilityLike>::new_min
  47:     0x7ff943e59a2f - <rustc_query_impl[78e525705bed6840]::Queries as rustc_middle[484603f84bd5edf8]::ty::query::QueryEngine>::try_mark_green
  48:     0x7ff94388d4c0 - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  49:     0x7ff94389e6e6 - rustc_driver[6fce53b951639747]::args::arg_expand_all
  50:     0x7ff9438829dc - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  51:     0x7ff94388ce0f - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  52:     0x7ff94388c5f3 - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  53:     0x7ff9438842dd - <rustc_data_structures[e9c5cab0f88c0c68]::temp_dir::MaybeTempDir>::new
  54:     0x7ff999b1021c - std::sys::windows::thread::Thread::new::he1a8155b1a8cc29c
  55:     0x7ff9d9807034 - BaseThreadInitThunk
  56:     0x7ff9daf82651 - RtlUserThreadStart

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0 (2c8cc3432 2023-03-06) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C target-feature=+simd128

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `clouds::<impl at sandbox\t2\global-weather-behavior-impl\src\clouds.rs:127:1: 127:40>::build`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `global-weather-behavior-impl`
PS C:\Users\melody.ju\ark-modules> 
```

**Comment by Ezrashaw** [comment] 2023-04-20 07:19
I can't seem to find the repository you are talking about. Could you please provide a link.

**Comment by jyn514** [comment] 2023-04-20 11:10
Duplicate of  https://github.com/rust-lang/rust/issues/109361

**Closed by jyn514** 2023-04-20 11:10 UTC
Labels: I-ICE, T-compiler, C-bug
