### ISSUE TITLE
Nightly can't compile syntex_syntax 0.30.0

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#41496] opened 2017-04-24 06:33 UTC
rustc 1.18.0-nightly (2bd4b5c6d 2017-04-23) can't compile syntex_syntax 0.30.0, which previously could be compiled. This looks like a break from the post-1.0 compatibility goals.

## Steps to reproduce

```
rustup update
rustup default nightly
cargo install --force --vers 0.4.1 rustfmt
```

## Actual results

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing rustfmt v0.4.1
   Compiling getopts v0.2.14
   Compiling log v0.3.7
   Compiling diff v0.1.10
   Compiling winapi v0.2.8
   Compiling unicode-segmentation v0.1.3
   Compiling winapi-build v0.1.1
   Compiling regex-syntax v0.3.9
   Compiling rustc-serialize v0.3.24
   Compiling bitflags v0.5.0
   Compiling term v0.4.5
   Compiling utf8-ranges v0.1.3
   Compiling unicode-xid v0.0.3
   Compiling libc v0.2.21
   Compiling kernel32-sys v0.2.2
   Compiling strings v0.0.1
   Compiling memchr v0.1.11
   Compiling term v0.2.14
   Compiling thread-id v2.0.0
   Compiling aho-corasick v0.5.3
   Compiling thread_local v0.2.7
   Compiling regex v0.1.80
   Compiling syntex_syntax v0.30.0
   Compiling toml v0.1.30
error[E0308]: mismatched types
   --> /home/hsivonen/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.30.0/src/ext/base.rs:487:33
    |
487 |                                 ext::quote::expand_quote_item));
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected concrete lifetime, found bound lifetime parameter 'cx
    |
    = note: expected type `fn(&'cx mut ext::base::ExtCtxt<'_>, codemap::Span, &[ast::TokenTree]) -> std::boxed::Box<ext::base::MacResult + 'cx>`
               found type `fn(&mut ext::base::ExtCtxt<'_>, codemap::Span, &[ast::TokenTree]) -> std::boxed::Box<ext::base::MacResult> {ext::quote::expand_quote_item::<'_>}`
    = note: lifetime parameter `'cx` declared on fn `ext::quote::expand_quote_item` appears only in the return type, but here is required to be higher-ranked, which means that `'cx` must appear in both argument and return types
    = note: this error is the result of a recent bug fix; for more information, see issue #33685 <https://github.com/rust-lang/rust/issues/33685>

error: aborting due to previous error

error: Could not compile `syntex_syntax`.
Build failed, waiting for other jobs to finish...
error: failed to compile `rustfmt v0.4.1`, intermediate artifacts can be found at `/tmp/cargo-install.QuzPS9zOEkrc`

Caused by:
  build failed
```

**Comment by TimNN** [comment] 2017-04-24 07:47
This seems to be expected the issue linked from the error message: #33685

**Comment by arielb1** [comment] 2017-04-24 08:50
Sure enough. Duplicate of #40960.

**Closed by arielb1** 2017-04-24 08:50 UTC
Labels: regression-from-stable-to-nightly, T-compiler
