### ISSUE TITLE
run-pass tests are failing on travis with "fatal runtime error: failed to initiate panic, error 3"

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#35011] opened 2016-07-24 16:45 UTC
For example https://travis-ci.org/rust-lang/rust/builds/147001444

Log excerpt:

```
test [run-pass] run-pass/autoderef-method-priority.rs ... ok
test [run-pass] run-pass/autoderef-method-twice.rs ... ok
test [run-pass] run-pass/autoderef-method-twice-but-not-thrice.rs ... ok
test [run-pass] run-pass/autoderef-method.rs ... ok
test [run-pass] run-pass/autoderef-privacy.rs ... ok
test [run-pass] run-pass/backtrace-debuginfo-aux.rs ... ignored
test [run-pass] run-pass/autoref-intermediate-types-issue-3585.rs ... ok
fatal runtime error: failed to initiate panic, error 3
Aborted (core dumped)
make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rpass.ok] Error 134
/build/mk/tests.mk:769: recipe for target 'tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rpass.ok' failed
```

From the timing I suspect this is related to #34832, cc @alexcrichton @vadimcn 

**Edit**: The failing test is probably either `run-pass/backtrace.rs` or `run-pass/backtrace-debuginfo.rs`.

**Edit2**: very likely caused by #34832, since it's travis build is the first to exhibit this error.

**Comment by vadimcn** [comment] 2016-07-24 19:54
Any ideas what's different about Travis?  This test passed on my local builds (as well as on buildbots, obviously).

(BTW, am I the only one who's always getting confused about which test has failed?  I don't see anything in the compiletest's output to indicate the culprit).

**Comment by TimNN** [comment] 2016-07-24 19:59
No idea what's different about travis, everything worked fine locally for me as well. We may want to just do a PR with some additional logging to see which one (if any) of the `return _URC_FATAL_PHASE1_ERROR` triggers the error.

Yeah, I can also only guess, I'm believe compiletest only prints something *after* running the test...

**Comment by alexcrichton** [comment] 2016-07-25 00:35
@vadimcn I wonder if it's different ubuntu versions on Travis here? It may be some glibc version thing going on. If you execute tests in the dockerfile it should in theory reproduce.

**Comment by cgswords** [comment] 2016-07-25 02:19
I'm experiencing this on #35018 and it's working fine locally.

**Comment by cgswords** [comment] 2016-07-25 02:26
This has also caused the following PRs to fail:
- #35001 
- #35003 
- #35004 
- #35009 
- #35010
- #35012
- #35013
- #35015

**Comment by vadimcn** [comment] 2016-07-25 07:58
> I wonder if it's different ubuntu versions on Travis here? It may be some glibc version thing going on. 

If I read our Dockerfile correctly, it uses LLVM 3.7 release, not whatever dev version is currently in rust-lang/llvm?  I think that's far more likely to cause codegen differences than a different glibc.

**Comment by alexcrichton** [comment] 2016-07-25 15:56
@vadimcn ah yeah that makes sense too yeah

**Comment by jhod0** [comment] 2016-07-25 18:00
This is also causing #34970 to fail

**Comment by jhod0** [comment] 2016-07-30 05:47
Looks like the PRs were merged - should this be closed?

**Comment by alexcrichton** [comment] 2016-07-30 05:48
Indeed!

**Closed by alexcrichton** 2016-07-30 05:48 UTC
Labels: A-testsuite
