### ISSUE TITLE
backtraces are hard to read

### ISSUE THREAD

**Issue by heycam** [rust-lang/rust#66652] opened 2019-11-22 23:56 UTC
I find Rust backtraces hard to read at a glance.  I think it's because many irrelevant (to me) stack frames are shown -- I'm getting 11 frames at the top relating to panicking and backtrace printing, and at the bottom there are 8 relating to panic catching and other initialization.  The frames I really want to look at are somewhere in the middle, but I have trouble scanning the output to find them.

Two potential ideas for improving the readability:

1. Omit the panic / backtrace / initialization frames by default, and only show them when `RUST_BACKTRACE=full` is used.
2. Color code the output so that the panic / backtrace / initialization frames are de-emphasized.

**Comment by jonas-schievink** [comment] 2019-11-23 07:33
Duplicate of https://github.com/rust-lang/rust/issues/58554

**Closed by jonas-schievink** 2019-11-23 07:33 UTC
