### ISSUE TITLE
Illegal instruction (core dumped) on std::thread

### ISSUE THREAD

**Issue by linouxis9** [rust-lang/rust#58439] opened 2019-02-13 20:44 UTC
```rust
use std::thread;

fn main() {
                thread::spawn(||{loop {}}).join();
}
```

When building this code in release mode using stable or the latest nightly, the produced binary fails with the Illegal instruction (core dumped) processor error.

It is reproducible on the [playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=b118f2369efda806c4cf07682b846728).

## Meta
rustc 1.33.0-nightly (19f8958f8 2019-01-23) on x86_64, Intel 6th generation.

**Comment by sfackler** [comment] 2019-02-13 21:37
Duplicate of #28728

**Closed by sfackler** 2019-02-13 21:37 UTC
