### ISSUE TITLE
cargo test fail when with '--release'

### ISSUE THREAD

**Issue by hawkingrei** [rust-lang/rust#59481] opened 2019-03-28 09:44 UTC
I am writing a lib which is the ffi binding with libwebp ,libpng and so on. so I write some test for them. when I use 'cargo test' to test them, it passes, but it will fail using 'cargo test --release'.
but when I change opt-level to 0 in  `profile.release`,  it passes with '--release'

# how to reproducing the error?

you need install latest libwebp ,libpng and libjpeg-turbo.in mac, you can ```brew install webp  jpeg-turbo libpng```

```
git clone https://github.com/hawkingrei/libwebp-rs.git
cd libwebp-rs
git submodule update --init
cargo test --release
```

I have no idea about this problem.Have you meet similar problem？

**Comment by hawkingrei** [comment] 2019-03-28 12:01
I use lldb to breakpoint at the error site.then i find that non-release the more a line of asm than release.


![图片](https://user-images.githubusercontent.com/3427324/55156221-4e2b9700-5194-11e9-8b35-50282185dea7.png)

**Comment by jonas-schievink** [comment] 2019-03-28 13:12
There is a lot of unsound code in that library. For example, doing `webp_config: &mut Default::default()` when `webp_config` is a `*mut _` will create a dangling pointer, which might then later be used in `WebPPicture::encode`.

Closing, since this is likely caused by incorrect unsafe code. If you can show that this issue happens even in the absence of any unsoundness, I can reopen.

If you have questions regarding FFI and unsafe code, feel free to ask them in the user forum at https://users.rust-lang.org/

**Closed by jonas-schievink** 2019-03-28 13:12 UTC
