### ISSUE TITLE
rustc 1.83 lexing regression in the 2015 edition: 'r#x'y

### ISSUE THREAD

**Issue by mattheww** [rust-lang/rust#133479] opened 2024-11-25 23:48 UTC
rustc 1.82 accepts forms like `'r#x'y` in the 2015 edition, but rustc 1.83 (beta) rejects them.

As I understand it, #126452 wasn't intended to have any effect on the 2015 edition.

[playground]

````rust
macro_rules! lexes {($($_:tt)*) => {}}

fn main() {
    lexes!('r#x'y);
}
````

[playground]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=ef856c60421a39a2a3155be5b8113d7a

I think this is fallout from the beta-backport of #132341.

**Comment by compiler-errors** [comment] 2024-11-26 00:02
I'm tempted to say that this is a purely theoretical regression, and we should perhaps fix it in 1.84 but it's possibly a bit too late for 1.83? Especially because I'm not certain *how* to prepare a fix for this other than perhaps reverting raw lifetime functionality altogether.

**Closed** 2024-12-01 22:32 UTC
Labels: A-parser, P-medium, C-bug, regression-untriaged
