### ISSUE TITLE
Casting enum causes ICE or unexpected result

### ISSUE THREAD

**Issue by elliottc** [rust-lang/rust#26377] opened 2015-06-17 21:50 UTC
Example here: http://is.gd/LKsPyZ

    enum Foo {
        Bar(u8)
    }

    fn main() {
        let x = Foo::Bar as u32;
        println!("{:?}", x);
    }

In rust 1.0.0 stable, rustc prints "LLVM ERROR: expected relocatable expression"

In nightly, it currently compiles and when run, the application prints "3964760960"

**Comment by arielb1** [comment] 2015-06-17 22:40
`Foo::Bar` is a function - you are casting it (as a function pointer) to an integer. Duplicate of #18154 anyway.

**Closed by arielb1** 2015-06-17 22:40 UTC
