### ISSUE TITLE
Regression in pwd of cargo doc

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#47434] opened 2018-01-14 22:57 UTC
For one of my projects I build and publish docs of the master branch from CI. I use the command `RUSTDOC=./rustdoc cargo doc` with a script that looks like:

```bash
#!/bin/sh

exec rustdoc "$@" --html-after-content script.js
```

This works as of stable rustc 1.23.0. But with rustc 1.24.0-beta.3 it no longer works because the `RUSTDOC` is resolved relative to `/path/to/registry/src/github.com-$hash/$crate-$version` instead of relative to the directory from which I ran `cargo doc`. This is different from how `RUSTC=./foo cargo build` is resolved so I believe it is a bug.

**Comment by dtolnay** [comment] 2018-01-14 22:59
Mentioning some rustdoc contributors: @QuietMisdreavus @GuillaumeGomez

**Comment by QuietMisdreavus** [comment] 2018-01-14 23:12
😕 If it's a problem of resolving the `RUSTDOC` environment variable, it seems more like Cargo being weird? @rust-lang/cargo What do y'all think?

**Comment by Mark-Simulacrum** [comment] 2018-01-15 02:13
This looks like it's probably caused by https://github.com/rust-lang/cargo/commit/8647a87d29fdd046592faed5f870aa7b2141cc24, and as such probably intentional (cc @alexcrichton).

However, the behavior where a `cargo doc` invoked in the "root" package doesn't use that packages workspace root does seem rather odd, so perhaps we can make some changes there, or resolve `RUSTDOC` relative to the current working directory first, by calling canonicalize. It would be logical to do the same for `RUSTC`, then.

**Comment by dtolnay** [comment] 2018-01-15 02:24
> resolve `RUSTDOC` relative to the current working directory first

Haven't read through that Cargo commit, but this is what I would consider the correct behavior. From what I can tell, this is how it works for `RUSTC`.

Note that there are two relevant directory issues and I maybe should have mentioned the second one above:

- Directory where `RUSTDOC` is resolved
- Directory that the script given by `RUSTDOC` sees as its current directory

My shell script refers to script.js which exists in the directory from which `cargo doc` was invoked, and that used to work as of rustc 1.23.0. As of 1.24.0-beta.3 the script no longer sees that directory as its current directory.

**Comment by alexcrichton** [comment] 2018-01-15 16:20
Ok so there's two things going on here I think. As @Mark-Simulacrum pointed out this is caused by https://github.com/rust-lang/cargo/pull/4788, so strictly speaking it's a bug in Cargo, not rustc. In any case:

* It's a bug in Cargo that `RUSTDOC=./foo` doesn't work. That should be resolved relative to the invoking cwd and should be used as an absolute path from then on out.
* It's "expected breakage" that the cwd is changing during compiles which would break the original script here @dtolnay is it possible to use an absolute path to `script.js` instead?

**Comment by wycats** [comment] 2018-01-15 19:05
@alexcrichton can we fix the Cargo bug?

**Comment by alexcrichton** [comment] 2018-01-16 05:43
@wycats the bug about `RUSTDOC=./foo` certainly, the "bug" about changing cwd is much less clear.

**Comment by Mark-Simulacrum** [comment] 2018-01-31 17:54
@rust-lang/cargo We need to discuss and resolve the relative rustdoc path issue `RUSTDOC=./foo` soon. The other discussion (cwd changing) is I believe expected, though may also be worth discussing. Nominating and setting P-high.

**Comment by alexcrichton** [comment] 2018-03-06 20:48
Since this ended up hitting stable I'm going to close.

**Closed by alexcrichton** 2018-03-06 20:48 UTC
Labels: I-nominated, P-high, T-cargo, regression-from-stable-to-stable
