### ISSUE TITLE
ICE: Broken MIR: generator contains type (on build)

### ISSUE THREAD

**Issue by langbamit** [rust-lang/rust#83971] opened 2021-04-07 15:07 UTC
Minimal example
### Code
[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=a4e9cadebe5bffb98e9f1c3333471a34)

`cargo run`: ok.
`cargo build`: failed.
```sh
// https://github.com/http-rs/tide/blob/v0.16.0/src/middleware.rs
use async_trait::async_trait;
use std::future::Future;
use std::pin::Pin;

pub type Result = std::io::Result<()>;

#[async_trait]
pub trait Middleware<State>: Send + Sync + 'static {
    /// Asynchronously handle the request, and return a response.
    async fn handle(&self, req: Request<State>, next: Next<'_, State>) -> crate::Result;

    /// Set the middleware's name. By default it uses the type signature.
    fn name(&self) -> &str {
        std::any::type_name::<Self>()
    }
}

pub struct Next<'a, State>(&'a str, State);

pub struct Request<State>(State);

#[async_trait]
impl<State, F> Middleware<State> for F
where
    State: Clone + Send + Sync + 'static,
    F: Send
        + Sync
        + 'static
        + for<'a> Fn(
            Request<State>,
            Next<'a, State>,
        ) -> Pin<Box<dyn Future<Output = crate::Result> + 'a + Send>>,
{
    async fn handle(&self, req: Request<State>, next: Next<'_, State>) -> crate::Result {
        (self)(req, next).await
    }
}

fn main() {

}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (c051c5ddd 2021-04-06) running on x86_64-unknown-linux-gnu
```

### Error output

```
error: internal compiler error: compiler/rustc_mir/src/transform/generator.rs:751:13: Broken MIR: generator contains type Pin<Box<dyn Future<Output = std::result::Result<(), std::io::Error>> + Send>> in MIR, but typeck only knows about for<'r, 's, 't0> {ResumeTy, &'r F, Request<State>, Next<'s, State>, Pin<Box<(dyn Future<Output = std::result::Result<(), std::io::Error>> + Send + 't0)>>, ()}
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```   Compiling playground v0.0.1 (/playground)
warning: function is never used: `main`
  --> src/lib.rs:39:4
   |
39 | fn main() {
   |    ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

error: internal compiler error: compiler/rustc_mir/src/transform/generator.rs:751:13: Broken MIR: generator contains type Pin<Box<dyn Future<Output = std::result::Result<(), std::io::Error>> + Send>> in MIR, but typeck only knows about for<'r, 's, 't0> {ResumeTy, &'r F, Request<State>, Next<'s, State>, Pin<Box<(dyn Future<Output = std::result::Result<(), std::io::Error>> + Send + 't0)>>, ()}
  --> src/lib.rs:34:89
   |
34 |       async fn handle(&self, req: Request<State>, next: Next<'_, State>) -> crate::Result {
   |  _________________________________________________________________________________________^
35 | |         (self)(req, next).await
36 | |     }
   | |_____^

thread 'rustc' panicked at 'Box<Any>', /rustc/c051c5ddda79f45fad196ca3a4690251e377d043/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (c051c5ddd 2021-04-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `<impl at src/lib.rs:23:1: 37:2>::handle::{closure#0}`
#1 [layout_raw] computing layout of `[static generator@src/lib.rs:34:89: 36:6 for<'r, 's, 't0> {std::future::ResumeTy, &'r F, Request<State>, Next<'s, State>, std::pin::Pin<std::boxed::Box<(dyn std::future::Future<Output = std::result::Result<(), std::io::Error>> + std::marker::Send + 't0)>>, ()}]`
end of query stack
error: aborting due to previous error; 1 warning emitted

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by SNCPlay42** [comment] 2021-04-07 15:56
Duplicate of #83737

**Closed** 2021-04-09 20:15 UTC
Labels: C-bug, I-ICE, T-compiler
