### ISSUE TITLE
Overlapping `From` impls produce confusing errors in async code

### ISSUE THREAD

**Issue by DomantasJ** [rust-lang/rust#69632] opened 2020-03-02 09:39 UTC
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a7041631c4284e665915d3eadc14771f)

```rust
struct MyError;

impl<T> From<T> for MyError {
    fn from(error: T) -> Self {
        MyError::from(error)
    }
}

async fn test() -> Result<(), MyError> {
    block().await?;
    Ok(())
}

async fn block() -> Result<(), MyError> {
    Ok(())
}
```

This produces a rather confusing error:

```
error[E0283]: type annotations needed
  --> src/lib.rs:10:18
   |
10 |     block().await?;
   |                  ^ cannot infer type for struct `MyError`
   |
   = note: cannot resolve `MyError: std::convert::From<MyError>`
   = note: required by `std::convert::From::from`
```

If you make functions non-async and remove the await then [you get a proper error about overlapping `From` impls](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e166fc6602626e9af329cdcd080daf9a):

```
error[E0119]: conflicting implementations of trait `std::convert::From<MyError>` for type `MyError`:
 --> src/lib.rs:3:1
  |
3 | impl<T> From<T> for MyError {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T> std::convert::From<T> for T;
```
### Meta

Rust version 1.41.1 (current version on playground)
Same problem appears on beta and nightly.

**Comment by tmandry** [comment] 2020-03-03 18:13
Duplicate of #67651

**Closed by tmandry** 2020-03-03 18:13 UTC
Labels: A-async-await, A-diagnostics, C-bug, T-compiler
