### ISSUE TITLE
Transmute doesn't work on arrays of generic types

### ISSUE THREAD

**Issue by mbartlett21** [rust-lang/rust#80899] opened 2021-01-11 03:56 UTC
I tried transmuting an array of [T; 10] to itself, but rustc gives an error.

```rust
fn transmute_to_self<T: Sized>(v: [T; 10]) -> [T; 10] {
    unsafe { core::mem::transmute(v) }
}
```

Error:
```text
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/lib.rs:4:14
  |
4 |     unsafe { transmute(v) }
  |              ^^^^^^^^^
  |
  = note: `[T; 10]` does not have a fixed size
```

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0-nightly (e22670468 2020-12-30)
binary: rustc
commit-hash: e2267046859c9ceb932abc983561d53a117089f6
commit-date: 2020-12-30
host: x86_64-pc-windows-msvc
release: 1.51.0-nightly
```

**Comment by camelid** [comment] 2021-01-11 04:20
Hmm, that does seem weird.

**Comment by camelid** [comment] 2021-01-11 04:23
This compiles fine, so it's not that rustc thinks `[T; 10]` is unsized:

```rust
fn transmute_to_self<T: Sized>(v: [T; 10]) -> impl Sized {
    v
}
```

**Comment by mbartlett21** [comment] 2021-01-11 05:11
The error also comes from transmuting generics:

```rust
fn transmute_to_self<T>(t: T) -> T {
    unsafe { core::mem::transmute(t) }
}
```
gives the same error.

**Comment by camelid** [comment] 2021-01-11 05:23
Looks like the code that does this check might not work on generic parameters:

https://github.com/rust-lang/rust/blob/26d451f4b3bcbea68eb80856aeddf37af52991ac/compiler/rustc_passes/src/intrinsicck.rs#L71-L73

It does say that it's conservative:

https://github.com/rust-lang/rust/blob/26d451f4b3bcbea68eb80856aeddf37af52991ac/compiler/rustc_middle/src/ty/layout.rs#L1792-L1810

**Comment by DutchGhost** [comment] 2021-01-11 08:46
See https://github.com/rust-lang/rust/issues/61956 for a previously opened issue

**Comment by mbartlett21** [comment] 2021-01-11 09:26
If and when the Project Safe Transmute's [ext-layout-traits rfc](https://github.com/rust-lang/project-safe-transmute/blob/master/rfcs/0000-ext-layout-traits.md) goes through the process, `transmute` could be changed to have a bound where the types are `SizeEq`, which should stop this problem.

**Comment by JohnTitor** [comment] 2021-01-12 12:08
Closing as duplicate of #61956 and removing `I-prioritize`.

**Closed by JohnTitor** 2021-01-12 12:08 UTC
Labels: C-bug, I-prioritize, T-compiler, T-lang
