### ISSUE TITLE
Simple recursion but get weird result when optimization is enabled

### ISSUE THREAD

**Issue by vita-dounai** [rust-lang/rust#80445] opened 2020-12-28 17:59 UTC
I tried this code:

```rust
fn main() {
    let ret = fn1(42);
    println!("it returns! {}", ret);
}

fn fn1(i: u32) -> u32 {
    fn2(i)
}

fn fn2(i: u32) -> u32 {
    fn1(i)
}
```

I expected to see this happen: ***in the code above, `fn1`  and `fn2` just simply call each other, and there is indeed a infinitely recursion. I expect that when the `main` is executed, the call to `f1` inside `main` should never return, and the stack will be overflowed at some point.***

Instead, this happened: ***when I enable `lto` or set `opt-level`  to 1 or higher,  the call to `f1`  suprisingly returns,  and the return value is always zero.***

![image](https://user-images.githubusercontent.com/44284897/103233930-4dcbbb80-4979-11eb-8b58-43b0278db628.png)

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-pc-windows-msvc
release: 1.48.0
LLVM version: 11.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ehuss** [comment] 2020-12-28 19:20
I believe that infinite loops are undefined behavior in LLVM, which can result in anything happening.  See issue #28728.

**Comment by jonas-schievink** [comment] 2020-12-28 20:43
Yes, closing as a duplicate of that

**Closed by jonas-schievink** 2020-12-28 20:43 UTC
Labels: C-bug
