### ISSUE TITLE
ICE: thread 'rustc' panicked at 'Box<Any>',

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#48413] opened 2018-02-21 22:58 UTC
I have this code (sorry, I don't have time to minimize it):

```rust
pub extern crate futures;
#[cfg(feature="test_utils")]
extern crate void;

use futures::Future;

pub trait Proceed: Sized {
    type Error: std::fmt::Debug;
    type RequestFuture: Future<Item=PaymentStatus<Self>, Error=Self::Error>;

    fn proceed(self) -> Self::RequestFuture;
}

pub enum PaymentStatus<N: Proceed> {
    Display { url: String, next: N },
    Paid,
    Error,
}

pub trait PaymentGateway {
    type Error: std::fmt::Debug;
    type Next: Proceed<Error=Self::Error>;
    type RequestFuture: Future<Item=PaymentStatus<Self::Next>, Error=Self::Error>;

    fn request(&self, amount: u64, currency: &str) -> Self::RequestFuture;
}

#[cfg(feature="test_utils")]
pub mod test_utils {
    use void::Void;
    use futures::future::FutureResult;
    use futures::IntoFuture;

    pub struct AlwaysPaid {}

    impl ::PaymentGateway for AlwaysPaid {
        type Error = Void;
        type Next = Void;
        type RequestFuture = FutureResult<::PaymentStatus<Self::Next>, Self::Error>;

        fn request(&self, _amount: u64, _currency: &str) -> Self::RequestFuture {
            Ok(::PaymentStatus::Paid).into_future()
        }
    }
    impl ::Proceed for Void {
        type Error = Void;
        type RequestFuture = FutureResult<::PaymentStatus<Self>, Void>;

        fn proceed(self) -> Self::RequestFuture {
            match self {
            }
        }
    }

    #[test]
    fn test_always_paid() {
        use ::PaymentGateway;
        use ::futures::Future;

        let gateway = AlwaysPaid {};
        match gateway.request(42, "BTC").poll() {
            Ok(::futures::Async::Ready(::PaymentStatus::Paid)) => (),
            _ => panic!("Bad result"),
        }
    }
}
```

When running cargo test, it produces this panic:

```
error: internal compiler error: librustc_trans/type_of.rs:145: layout: TyLayout {
    ty: PaymentStatus<void::Void>,
    details: LayoutDetails {
        variants: Tagged {
            discr: Scalar {
                value: Int(
                    I64,
                    false
                ),
                valid_range: 1..=2
            },
            variants: [
                LayoutDetails {
                    variants: Single {
                        index: 0
                    },
                    fields: Union(
                        2
                    ),
                    abi: Uninhabited,
                    align: Align {
                        abi: 0,
                        pref: 0
                    },
                    size: Size {
                        raw: 0
                    }
                },
                LayoutDetails {
                    variants: Single {
                        index: 1
                    },
                    fields: Arbitrary {
                        offsets: [],
                        memory_index: []
                    },
                    abi: Aggregate {
                        sized: true
                    },
                    align: Align {
                        abi: 0,
                        pref: 3
                    },
                    size: Size {
                        raw: 8
                    }
                },
                LayoutDetails {
                    variants: Single {
                        index: 2
                    },
                    fields: Arbitrary {
                        offsets: [],
                        memory_index: []
                    },
                    abi: Aggregate {
                        sized: true
                    },
                    align: Align {
                        abi: 0,
                        pref: 3
                    },
                    size: Size {
                        raw: 8
                    }
                }
            ]
        },
        fields: Arbitrary {
            offsets: [
                Size {
                    raw: 0
                }
            ],
            memory_index: [
                0
            ]
        },
        abi: Aggregate {
            sized: true
        },
        align: Align {
            abi: 0,
            pref: 3
        },
        size: Size {
            raw: 1
        }
    }
} stride: Size { raw: 1 } offset: Size { raw: 8 }

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:535:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (27a046e93 2018-02-18) running on x86_64-unknown-linux-gnu

error: Could not compile `payment_interface`.
warning: build failed, waiting for other jobs to finish...
error: internal compiler error: librustc_trans/type_of.rs:145: layout: TyLayout {
    ty: PaymentStatus<void::Void>,
    details: LayoutDetails {
        variants: Tagged {
            discr: Scalar {
                value: Int(
                    I64,
                    false
                ),
                valid_range: 1..=2
            },
            variants: [
                LayoutDetails {
                    variants: Single {
                        index: 0
                    },
                    fields: Union(
                        2
                    ),
                    abi: Uninhabited,
                    align: Align {
                        abi: 0,
                        pref: 0
                    },
                    size: Size {
                        raw: 0
                    }
                },
                LayoutDetails {
                    variants: Single {
                        index: 1
                    },
                    fields: Arbitrary {
                        offsets: [],
                        memory_index: []
                    },
                    abi: Aggregate {
                        sized: true
                    },
                    align: Align {
                        abi: 0,
                        pref: 3
                    },
                    size: Size {
                        raw: 8
                    }
                },
                LayoutDetails {
                    variants: Single {
                        index: 2
                    },
                    fields: Arbitrary {
                        offsets: [],
                        memory_index: []
                    },
                    abi: Aggregate {
                        sized: true
                    },
                    align: Align {
                        abi: 0,
                        pref: 3
                    },
                    size: Size {
                        raw: 8
                    }
                }
            ]
        },
        fields: Arbitrary {
            offsets: [
                Size {
                    raw: 0
                }
            ],
            memory_index: [
                0
            ]
        },
        abi: Aggregate {
            sized: true
        },
        align: Align {
            abi: 0,
            pref: 3
        },
        size: Size {
            raw: 1
        }
    }
} stride: Size { raw: 1 } offset: Size { raw: 8 }

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:535:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.25.0-nightly (27a046e93 2018-02-18) running on x86_64-unknown-linux-gnu
```

Same thing with `rustc 1.24.0 (4d90ac38c 2018-02-12) running on x86_64-unknown-linux-gnu`.

Note: the panic started to happen only after I added test.

**Comment by josevalaad** [comment] 2018-09-24 08:41
I believe I have this error, but with the stable 1.29 branch. Somebody could cast some light on this? Maybe telling what could be triggering this and how can I bypass it? I'm mostly a newcomer. Thank you.

The stack trace seems to say that the error is caused by this code (at least it prints a reference to it):

```rust
pub struct ProjectWrapper {
    processing_project:Arc<Mutex<Cell<Project>>>,
    project:Option<Project>,
    processed:bool
}

impl ProjectWrapper {
    /// Creates the new Wrapper for the given project.
    pub fn new(project:Project) -> Self {
        ProjectWrapper {
            processing_project:Arc::new(Mutex::new(Cell::new(project))),
            project:None,
            processed:false
        }
    }
}
```
Error output: 

```
error: internal compiler error: librustc/traits/structural_impls.rs:178: impossible case reached

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
stack backtrace:
   0:        0x10a732cbf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hdfdb4ba75a1dcb88
   1:        0x10a70b74a - std::sys_common::backtrace::print::h5823bdde4d2f8639
   2:        0x10a73b4c3 - std::panicking::default_hook::{{closure}}::h06fc925781e26cfe
   3:        0x10a73b24c - std::panicking::default_hook::hdfdcc6f72e7aec0a
   4:        0x1090575a0 - rustc::util::common::panic_hook::h26f30d7c34565ba6
   5:        0x10a73bc08 - std::panicking::rust_panic_with_hook::h28749c6c929f49fc
   6:        0x10a399ae3 - std::panicking::begin_panic::h74819760f7034835
   7:        0x10a3acdbc - rustc_errors::Handler::bug::h569ea2875a33cf9e
   8:        0x108c01bf5 - rustc::session::opt_span_bug_fmt::{{closure}}::hd70e80d759b8fb67
   9:        0x108cc522c - rustc::ty::context::tls::with_opt::{{closure}}::hc45f9ec880dcc4d1
  10:        0x108c02b68 - rustc::ty::context::tls::with_context_opt::h3bb916d5118fbd79
  11:        0x108cc4de4 - rustc::ty::context::tls::with_opt::h9aaef94ca9547ca7
  12:        0x108b72ae4 - rustc::session::opt_span_bug_fmt::h06e42769e414de85
  13:        0x108b72a31 - rustc::session::bug_fmt::h55b97131b3dda3ce
  14:        0x1090bcda6 - rustc::traits::structural_impls::<impl rustc::ty::context::Lift<'tcx> for rustc::traits::SelectionError<'a>>::lift_to_tcx::h8ab9a5521706506e
  15:        0x108ec20eb - rustc::ty::context::TyCtxt::lift_to_global::h90a1d7aa3c8deba1
  16:        0x1090b0bad - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  17:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  18:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  19:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  20:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  21:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  22:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  23:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  24:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  25:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  26:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  27:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  28:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  29:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  30:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  31:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  32:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  33:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  34:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  35:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  36:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  37:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  38:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  39:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  40:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  41:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  42:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  43:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  44:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  45:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  46:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  47:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  48:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  49:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  50:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  51:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  52:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  53:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  54:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  55:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  56:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  57:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  58:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  59:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  60:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  61:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  62:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  63:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  64:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  65:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  66:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  67:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  68:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  69:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  70:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  71:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  72:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  73:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  74:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  75:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  76:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  77:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  78:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  79:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  80:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  81:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  82:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  83:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  84:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  85:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  86:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  87:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  88:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
  89:        0x108a5b9ff - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h1cf9563d32f68fb6
  90:        0x1090b14ad - rustc::traits::select::SelectionContext::candidate_from_obligation_no_cache::h7e5fe5220b6e4845
  91:        0x108c05b3e - rustc::ty::context::tls::with_context::h0a0b26ca1e7f3af8
  92:        0x108b10178 - rustc::dep_graph::graph::DepGraph::with_anon_task::h49082979cfb26042
  93:        0x1090b0a63 - rustc::traits::select::SelectionContext::candidate_from_obligation::hd5735456ebe579c4
  94:        0x1090afd89 - rustc::traits::select::SelectionContext::evaluate_stack::h181353db9d9f4cc3
  95:        0x108c424e7 - rustc::ty::context::tls::with_context::hee4360d6cc3d0047
  96:        0x108b12cb2 - rustc::dep_graph::graph::DepGraph::with_anon_task::h7f9ad6ef4c05da49
  97:        0x1090aeacd - rustc::traits::select::SelectionContext::evaluate_predicate_recursively::h29ea1dba922fbcae
  98:        0x108f35acd - rustc::infer::InferCtxt::probe::h8c977ce0f0d2dda8
  99:        0x10901bfef - <&'a mut I as core::iter::iterator::Iterator>::next::hb2cb701dbb76a2f2
query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `&_: std::io::Write`
#1 [typeck_tables_of] processing `core::watcher::project::Project::new`
#2 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0 (aa3ca1994 2018-09-11) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

**Comment by jakubadamw** [comment] 2019-07-14 20:03
No longer ICEs. To verify, one needs to put the original code in a Cargo package with a `futures` dependency.

**Comment by Mark-Simulacrum** [comment] 2019-07-14 20:05
Closing as per the previous. Not marking E-needstest as no minimal example exists (and doesn't seem super warranted in this case).

**Closed by Mark-Simulacrum** 2019-07-14 20:05 UTC
Labels: C-bug, I-ICE, T-compiler
