### ISSUE TITLE
Compiling Rust on Ubuntu 16.04 raises compilation error

### ISSUE THREAD

**Issue by aqjune** [rust-lang/rust#52278] opened 2018-07-12 00:40 UTC
Running `./x.py build` raises following error:

```
...
   Compiling syntax v0.0.0 (...)
   Compiling termcolor v0.3.6
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rustc_target`.

Caused by:
  process didn't exit successfully: `/home/user/rust/build/bootstrap/debug/rustc --crate-name build_script_build librustc_target/build.rs --error-format json --crate-type bin --emit=dep-info,link
 -C opt-level=3 --cfg feature="jemalloc" -C metadata=3de51117304bc201 -C extra-filename=-3de51117304bc201 --out-dir /home/user/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/build/rustc
_target-3de51117304bc201 -L dependency=/home/user/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `syntax`.
Caused by:                                                                                                                                                                                                 [0/1974]
  process didn't exit successfully: `/home/user/rust/build/bootstrap/debug/rustc --crate-name build_script_build libsyntax/build.rs --error-format json --crate-type bin --emit=dep-info,link -C op
t-level=3 -C metadata=f3807f78d3aa8d7c -C extra-filename=-f3807f78d3aa8d7c --out-dir /home/user/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/build/syntax-f3807f78d3aa8d7c -L dependenc
y=/home/user/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `cc`.

Caused by:
  process didn't exit successfully: `/home/user/rust/build/bootstrap/debug/rustc --crate-name cc /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.10/src/lib.rs --error-format
 json --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=c5a471959419d0da -C extra-filename=-c5a471959419d0da --out-dir /home/user/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/r
elease/deps -L dependency=/home/user/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps --cap-lints allow` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/home/user/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "12" "--release" "--features" " jemalloc
" "--manifest-path" "/home/user/rust/src/rustc/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1091:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /home/user/rust/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:36:48

```

I'm using GCC 7.3. I set `prefix` in config.toml as a local directory (/home/user/...) and `sysconfdir` as ".". I used stable branch.

**Comment by Mark-Simulacrum** [comment] 2018-07-12 00:46
A full log, with `x.py build -vvv` and config.toml would be helpful; as well as the commit hash you are trying to build.

**Comment by aqjune** [comment] 2018-07-12 00:50
Yep, it is `5f2b325f64ed6caa7179f3e04913db437656ec7e`. My `config.toml` is the default file with `prefix` set as a local directory and `sysconfdir` as ".". I'm running `x.py build -vvv`
I succeeded in compiling Rust with this option on another Ubuntu 16.04 with the same GCC version in only a few days ago (the commit hash was `3eda71b00ad48d7bf4eef4c443e7f611fd061418`), but now it is not reproduced.

**Comment by aqjune** [comment] 2018-07-12 01:06
[log.txt](https://github.com/rust-lang/rust/files/2186688/log.txt)

I attach the output of `x.py build -vvv`.

**Comment by Mark-Simulacrum** [comment] 2018-07-12 13:04
Can you try doing the same on master? Also, running `x.py clean` before the build may be helpful. Otherwise I'm not sure why this is happening; it's probably a result of stale files or some such.

**Comment by Mark-Simulacrum** [comment] 2019-06-03 18:37
I'm going to close this since it probably is a duplicate of some other bug and tracking it separately in any case isn't super helpful (this is our traditional "something is stale" bug most likely which is nearly impossible to stamp out completely with current architecture).

**Comment by rossmacarthur** [comment] 2019-12-25 18:19
@Mark-Simulacrum could you actually close this?

**Closed** 2019-12-25 18:25 UTC
Labels: A-rustbuild
