### ISSUE TITLE
undefined behaviour checks for statics should be consistent with checks for variables

### ISSUE THREAD

**Issue by pypypypypypypypypyp** [rust-lang/rust#79140] opened 2020-11-17 15:50 UTC
```rust
static mut FOO: Vec<()> = unsafe { std::mem::transmute([0u64; 3]) };
```
this code fails to compile, stating that it may be undefined behaviour to use this value, which is of course true.
```rust
let mut foo: Vec<()> = unsafe { std::mem::transmute([0u64; 3]) };
```
but this code works just fine. (note: transmute is a stand-in for mem::zeroed since that's not [yet] a constant function)

the mutable static is inaccessible without an unsafe {} block, so there is no way that this can cause UB in safe code, the only risk is that the user will read FOO without first initializing it using a ptr::write, which is exactly the same risk as in the second example.

this is a restriction on what unsafe code can do, which seems wrong to me, only safe code should be restricted in ways like this.

**Comment by jonas-schievink** [comment] 2020-11-17 15:57
This check runs during constant evaluation, so the behavior here is expected. https://github.com/rust-lang/rfcs/pull/3016 specifies precisely what compiler behavior is acceptable during constant evaluation, so you might want to read that.

Closing this as expected behavior, however.

**Closed by jonas-schievink** 2020-11-17 15:57 UTC

**Comment by oli-obk** [comment] 2021-01-05 22:41
> but this code works just fine. (note: transmute is a stand-in for mem::zeroed since that's not [yet] a constant function)

Note that "works just fine" in the presence of UB is meaningless. Your example does exhibit UB, because the `foo` variable contains an invalid `Vec<()>`. You can see this [on the playground, by running Tools -> Miri](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ed4e77d7ea4965f86856d546fe5f6d4f).

If you want to do this, you need to wrap the `Vec<()>` in a `MaybeUninit`:

```rust
let mut foo = MaybeUninit::<Vec<()>>::uninit(); // or `zeroed`, but if you plan to overwrite it anyway, you can leave it uninitialized.
```

**Comment by pypypypypypypypypyp** [comment] 2021-01-08 02:15
obviously reading the value is UB, but initializing it with a ptr::write before it is read should make sure no UB is possible right?

regardless, "works fine" was referring to the fact that it compiled with no errors, when the first example would not compile, and that was inconsistent.

**Comment by oli-obk** [comment] 2021-01-11 11:02
> regardless, "works fine" was referring to the fact that it compiled with no errors, when the first example would not compile, and that was inconsistent.

Ah, we have this with all errors around const eval. For example `static FOO: () = panic!();` will cause a compiler error, while `fn main() { panic!() }` will not cause an error, but panic at runtime. The UB checks are just something which doesn't even cause panics at runtime but causes errors at compile-time.

> obviously reading the value is UB, but initializing it with a ptr::write before it is read should make sure no UB is possible right?

It may not be too obvious in your example, so I have a different example for you:

```rust
let x: &i32 = unsafe { std::mem::zeroed() };
```

This line of code is UB just by itself. The reason is that if the optimizer sees a reference whose value is `0`, then it knows that this code must be dead code, because it is *impossible* for any Rust-reference to ever have the value `0`. So it can not just remove this code, it can also replace it by `std::hint::unreachable()`. At this point all bets are off, the optimizer will cause havoc with your code.
