### ISSUE TITLE
item-bodies/item-types timings regressed for issue-32062-equality-relations

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#33889] opened 2016-05-26 19:40 UTC
See [this][t1] and [this][t2].

[t1]: http://perf.rust-lang.org/index.html?start=Mon%20Apr%2018%202016%2002:11:20%20GMT+0000%20(UTC)&end=Wed%20May%2018%202016%2012:04:26%20GMT+0000%20(UTC)&kind=benchmarks&crates=issue-32062-equality-relations-complexity&phases=item-bodies%20checking,item-types%20checking&group_by=crate

[t2]: http://perf.rust-lang.org/index.html?start=Mon%20Apr%2018%202016%2002:11:20%20GMT+0000%20(UTC)&end=Wed%20May%2018%202016%2012:04:26%20GMT+0000%20(UTC)&kind=benchmarks&crates=issue-32062-equality-relations-complexity&phases=total&group_by=crate

**Comment by nagisa** [comment] 2016-05-26 19:43
cc @eddyb @nikomatsakis

**Comment by jonas-schievink** [comment] 2016-05-26 19:51
cc @Marwes

**Comment by Marwes** [comment] 2016-05-27 17:05
While testing #33816 on my projects I figured I'd run through this example on that version of rustc as well and it seems it doesn't seem to give this slowdown and given that #33816 seems to be rebased on top of master after this slowdown occurred it might have been fixed by that PR (if only by chance?). I may take a look at this sometime this weekend if I get the time though as it still seems unfortunate. (It would be really nice if perf.rust-lang.org could display the commit hash of each run it does. That would make it much easier to pin down which version introduced a regression).

**Comment by nikomatsakis** [comment] 2016-06-02 20:24
Probably the same problem is causing a regr in jld-day15-parser

**Comment by nikomatsakis** [comment] 2016-06-02 20:24
triage: P-high

**Comment by nikomatsakis** [comment] 2016-06-02 20:25
It'd be great to do some sort of bisection to try to narrow down what is causing this.

**Comment by eddyb** [comment] 2016-06-04 08:14
@nikomatsakis Doesn't look like it, [the regression is in translation](https://github.com/rust-lang/rust/issues/34042#issuecomment-223743432) for jld-day15-parser.

**Comment by arielb1** [comment] 2016-06-04 13:31
The problematic PR here is 75e23e1b032d87300392a4f3835bde8d5d873823 (#33137). Seems logical - that probably broke the caching

**Comment by eddyb** [comment] 2016-06-04 13:34
@arielb1 So the solution is to move forward with #33816?

**Comment by arielb1** [comment] 2016-06-04 13:34
That sounds like it.

**Comment by arielb1** [comment] 2016-06-05 17:27
This is fixed as #33816 landed.

**Closed by arielb1** 2016-06-05 17:27 UTC
Labels: A-typesystem, I-compiletime, P-high
