### ISSUE TITLE
Build fails on windows when using `-C codegen-units=4`

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#21303] opened 2015-01-17 17:22 UTC
```
$ make rustc-stage1 RUSTFLAGS='-C codegen-units=4'
cfg: build triple i686-pc-windows-gnu
cfg: host triples i686-pc-windows-gnu
cfg: target triples i686-pc-windows-gnu
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for i686-pc-windows-gnu is i386
cfg: os for i686-pc-windows-gnu is pc-windows-gnu
cfg: good valgrind for i686-pc-windows-gnu is
cfg: using CC=gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: no lualatex found, deferring to xelatex
cfg: no xelatex found, deferring to pdflatex
cfg: no pdflatex found, disabling LaTeX docs
cfg: no pandoc found, omitting PDF and EPUB docs
rustc: i686-pc-windows-gnu/stage0/bin/rustlib/i686-pc-windows-gnu/lib/libunicode
C:\Users\...\Desktop\rust\src\libunicode\lib.rs:25:1: 25:15 warning: unused attribute, #[warn(unused_attributes)] on by default
C:\Users\...\Desktop\rust\src\libunicode\lib.rs:25 #![staged_api]
                                                      ^~~~~~~~~~~~~~

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\Users\Adolfo\Desktop\rust\i686-pc-windows-gnu\stage0\bin\rustc.exe
File: C:/bot/slave/snap3-win-32/build/src/llvm/lib/IR/Constants.cpp, Line 1609

Expression: S->getType()->isPtrOrPtrVectorTy() && "Invalid cast"
/c/Users/.../Desktop/rust/mk/target.mk:165: recipe for target 'i686-pc-windows-gnu/stage0/bin/rustlib/i686-pc-windows-gnu/lib/stamp.unicode' failed
make: *** [i686-pc-windows-gnu/stage0/bin/rustlib/i686-pc-windows-gnu/lib/stamp.unicode] Error 3
```

**Comment by nagisa** [comment] 2015-01-17 17:44
Dupe of #19826

**Closed** 2015-01-17 19:51 UTC
