### ISSUE TITLE
Bump `XCode`  on `macos-14`

### ISSUE THREAD

**Issue by arttet** [rust-lang/rust#131494] opened 2024-10-10 09:59 UTC
Now, we use `Xcode` [14.3.1](https://github.com/rust-lang/rust/blob/df1b5d3cc2117f1ee96abca25678bc5f5604d450/src/ci/github-actions/jobs.yml#L332) on `macos-14`
It will be removed soon. So, we need to update it ASAP.

https://github.com/rust-lang/rust/blob/df1b5d3cc2117f1ee96abca25678bc5f5604d450/src/ci/github-actions/jobs.yml#L303
https://github.com/rust-lang/rust/blob/df1b5d3cc2117f1ee96abca25678bc5f5604d450/src/ci/github-actions/jobs.yml#L332

See https://github.com/actions/runner-images/issues/10703

**Comment by ehuss** [comment] 2024-10-10 13:14
Thanks for the report. I'm going to close as a duplicate of https://github.com/rust-lang/rust/issues/121058 which is already tracking the update and the issues involved with that.

**Closed by ehuss** 2024-10-10 13:14 UTC
Labels: O-macos, needs-triage
