### ISSUE TITLE
dead_code doesn't show unused struct as unused

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#39558] opened 2017-02-05 09:04 UTC
Hi everybody.

I am sorry I tried to minify the example, but I can't find a pattern.
There is a PR: https://github.com/rust-lang-nursery/rls/pull/168
There is an commit: "Replaced uses of unwrap with expect.".
In the commit in the src/actions/build.mod file there are two structs: `CompilerMessageCode`, `CompilerMessage` which are unused.
The compiler doesn't show any warning.

**Comment by durka** [comment] 2017-02-06 20:03
They were marked `pub`.

**Comment by KalitaAlexey** [comment] 2017-02-06 20:06
@durka,
They were in a function.
Can I use `pub` outside of the function?

**Comment by durka** [comment] 2017-02-06 20:11
To be honest, I would have expected some other error saying that `pub` doesn't make any sense inside a function :) As far as I know, the lint ignored them for that reason though.

**Comment by KalitaAlexey** [comment] 2017-02-06 20:12
@durka,
It compiled and worked.

**Comment by petrochenkov** [comment] 2017-02-06 20:18
@durka 
>To be honest, I would have expected some other error saying that pub doesn't make any sense inside a function

It *was* an error a year ago (see https://github.com/rust-lang/rust/issues/31776)

**Comment by durka** [comment] 2017-02-06 20:21
This case would ideally be caught by the possibly-upcoming ["this item is not as public as it looks" lint](https://github.com/rust-lang/rust/issues/32409#issuecomment-277435130).

**Comment by steveklabnik** [comment] 2017-02-07 19:59
So it appears this is not a bug. Closing!

**Closed by steveklabnik** 2017-02-07 19:59 UTC
