### ISSUE TITLE
unimplemented!() doesn't work with return impl 

### ISSUE THREAD

**Issue by crone123** [rust-lang/rust#81518] opened 2021-01-29 16:24 UTC
Hello,
I tried this code:

```rust
fn test() -> impl Fn(i32) -> i32
{
    unimplemented!()
}
```
Or this code:
```rust
fn test() -> impl Display
{
    unimplemented!()
}
```

I expected to see this happen: Compilation works, but panic with unimplemented at runtime.

Instead, this happened: Unable to compile, I got these errors:
```
error[E0277]: expected a `Fn<(i32,)>` closure, found `()`
 --> bug.rs:1:14
  |
1 | fn test() -> impl Fn(i32) -> i32
  |              ^^^^^^^^^^^^^^^^^^^ expected an `Fn<(i32,)>` closure, found `()`
  |
  = help: the trait `Fn<(i32,)>` is not implemented for `()`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

```
error[E0277]: `()` doesn't implement `std::fmt::Display`
 --> bug.rs:6:14
  |
6 | fn test() -> impl Display
  |              ^^^^^^^^^^^^ `()` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `()`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```
In theory, unimplemented!() dosen't return, and just panic, so the type problem is not to be solved. And this is the purpose of unimplemented, to let functions.... unimplemented... just a draft... if we need to implements unimplemented functions.... they become implemented....

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (44e3daf5e 2020-12-31)
binary: rustc
commit-hash: 44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e
commit-date: 2020-12-31
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

Thank you :)

**Comment by memoryruins** [comment] 2021-01-29 16:58
Thanks for reporting! This is a duplicate of https://github.com/rust-lang/rust/issues/36375

**Closed** 2021-01-29 17:30 UTC
Labels: C-bug
