### ISSUE TITLE
&[Path] causes rustc to fail

### ISSUE THREAD

**Issue by kie0tauB** [rust-lang/rust#29971] opened 2015-11-21 12:56 UTC
Rust should probably not accept the following program, but currently it crashes and asks me to file a bug report:

```
% rustc --version
rustc 1.4.0 (8ab8581f6 2015-10-27)
```

```rust
use std::path::{Path};
fn f(files:&[Path]) {}
fn main(){}
```

Here is the requested backtrace:
```
stack backtrace:
   1:     0x7f52d5341479 - sys::backtrace::tracing::imp::write::he18882fa84e6b00ePnt
   2:     0x7f52d533e9c6 - panicking::on_panic::h495226a97f084523enx
   3:     0x7f52d5309d2e - sys_common::unwind::begin_unwind_inner::h7a4ee06c0d57e26affs
   4:     0x7f52d47dc33f - sys_common::unwind::begin_unwind::h9561900542512663647
   5:     0x7f52d48cac1a - trans::debuginfo::metadata::vec_slice_metadata::h6f4a9b6ea7bdbcc5VBy
   6:     0x7f52d48c88cc - trans::debuginfo::metadata::type_metadata::h5b50fe90aa8ec4edeKy
   7:     0x7f52d48de694 - trans::debuginfo::create_function_debug_context::get_function_signature::haff6c26c3e358e87dYA
   8:     0x7f52d4827434 - trans::base::new_fn_ctxt::heb357a1e5a49a5beGpi
   9:     0x7f52d4839d59 - trans::base::trans_closure::h53952d415f7e8be4vQi
  10:     0x7f52d483db2f - trans::base::trans_fn::h6ab7f891fb676433i0i
  11:     0x7f52d48417d8 - trans::base::trans_item::h621871e28d6543ef9qj
  12:     0x7f52d484ea89 - trans::base::trans_crate::hafc571e2b3eb933evfk
  13:     0x7f52d586a98c - driver::phase_4_translate_to_llvm::h46999cce2ec68525lPa
  14:     0x7f52d5865143 - driver::phase_3_run_analysis_passes::closure.21543
  15:     0x7f52d584420c - middle::ty::context::ctxt<'tcx>::create_and_enter::h15289880893681309157
  16:     0x7f52d583f9f1 - driver::phase_3_run_analysis_passes::h6659992598722710863
  17:     0x7f52d581fdad - driver::compile_input::h335e6fb0e622005d0ba
  18:     0x7f52d597f0ab - run_compiler::hdc2ad537dbabfa44qqc
  19:     0x7f52d597c916 - boxed::F.FnBox<A>::call_box::h1406622963181190011
  20:     0x7f52d597c224 - sys_common::unwind::try::try_fn::h10504571807779950300
  21:     0x7f52d533e2c8 - __rust_try
  22:     0x7f52d5332a62 - sys_common::unwind::try::inner_try::h9a6d6e6aac7d4481Dbs
  23:     0x7f52d597c3be - boxed::F.FnBox<A>::call_box::h6188408694345742314
  24:     0x7f52d5346793 - sys::thread::Thread::new::thread_start::h745044ae17db5a99dGw
  25:     0x7f52cf2d20a3 - start_thread
  26:     0x7f52d4fc506c - clone
  27:                0x0 - <unknown>
```

**Comment by huonw** [comment] 2015-11-21 13:26
Duplicate of https://github.com/rust-lang/rust/issues/27819. Thanks for filing!

**Closed by huonw** 2015-11-21 13:26 UTC
