### ISSUE TITLE
Glob import with auto-derive

### ISSUE THREAD

**Issue by truchi** [rust-lang/rust#75061] opened 2020-08-02 16:27 UTC
I tried this code:

```rust
#[derive(Copy, Clone)] // Or anything really...
pub enum A {
    A,
    B,
}
pub use A::*; // `A` is ambiguous
```

I expected this code to work the same as:
```rust
pub enum A {
    A,
    B,
}
impl Copy for A {}
impl Clone for A {
    fn clone(&self) -> A { *self }
}
pub use A::*; // No issue here
```

Instead, this happened: :cry:

### Meta

`rustc --version --verbose`: (Same on stable btw)
```
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0

```

<details><summary>Backtrace</summary>
<p>

```
error[E0659]: `A` is ambiguous (glob import vs macro-expanded name in the same module during import/macro resolution)
 --> src/main.rs:6:9
  |
6 | pub use A::*;
  |         ^ ambiguous name
  |
note: `A` could refer to the enum defined here
 --> src/main.rs:2:1
  |
2 | / pub enum A {
3 | |     A,
4 | |     B,
5 | | }
  | |_^
note: `A` could also refer to the variant imported here
 --> src/main.rs:6:9
  |
6 | pub use A::*;
  |         ^^^^
  = help: consider adding an explicit import of `A` to disambiguate

error: aborting due to previous error
```
</p>
</details>

[Question on users](https://users.rust-lang.org/t/glob-import-with-auto-derive/46754)

_Hope this helps!
Below 20 IQ Rust noob_
:heart:

**Comment by SNCPlay42** [comment] 2022-10-10 01:56
This is a duplicate of #62769

**Comment by Dylan-DPC** [comment] 2023-04-01 16:50
Closing this as duplicate

**Closed by Dylan-DPC** 2023-04-01 16:50 UTC
Labels: A-resolve, T-compiler, C-bug
