### ISSUE TITLE
Compiles with std on aarch64 even though `no_std` is specified

### ISSUE THREAD

**Issue by humenda** [rust-lang/rust#92387] opened 2021-12-29 04:58 UTC
I am depending on two libraries that are known to build with `no_std` on aarch64-unknown-none.
The libraries are heapless and nom. Using them separately works fine, but using them together leads to the situation that a dependency of these dependencies is configured to use `std`. Furthermore, the issue can only be reproduced if this takes place in a workspace. A minimal working example is at <https://github.com/humenda/mwe-cargo-nostd

To reproduce:

1. `rustup component add aarch64-unknown-none`
2. Clone the mentioned repository and cd to it.
3. `cargo build --target aarch64-unknown-none`, output is:

    ```
    error[E0463]: can't find crate for `std`
  |
  = note: the `aarch64-unknown-none` target may not support the standard library
  = note: `std` is required by `memchr` because it does not declare `#![no_std]`
```

4. Uncommenting heapless or the nom stanza in `ex/Cargo.toml` makes it compile.
5.`cp -dpr ex /tmp && cd /tmp/ex && cargo build --target aarch64-unknown-none` succeeds.

At this point I am stuck and would appreciate feedback. Is it a misconfiguration or a bug?

**Comment by hkratz** [comment] 2021-12-29 15:04
Looks like a cargo issue, as memchr is being built with default features enabled (but only in the workspace):
> $ cargo build -v
> [...]
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `aarch64-unknown-none` target may not support the standard library
>   = note: `std` is required by `memchr` because it does not declare `#![no_std]`
> 
> For more information about this error, try `rustc --explain E0463`.
> error: could not compile `memchr` due to previous error
> 
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name memchr --edition=2018 /Users/hans/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=401aea4f8775932d -C extra-filename=-401aea4f8775932d --out-dir /Users/hans/dev/spikes/mwe-cargo-nostd/target/aarch64-unknown-none/debug/deps --target aarch64-unknown-none -L dependency=/Users/hans/dev/spikes/mwe-cargo-nostd/target/aarch64-unknown-none/debug/deps -L dependency=/Users/hans/dev/spikes/mwe-cargo-nostd/target/debug/deps --cap-lints allow` (exit status: 1)

**Comment by ehuss** [comment] 2021-12-29 15:32
You'll need to place `resolver = "2"` in the workspace definition.  The new feature resolver is able to avoid unifying features in some cases like this.  

There is more information at https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2

Closing as this is working as intended (though I understand it can be confusing).

**Closed by ehuss** 2021-12-29 15:32 UTC
Labels: C-bug

**Comment by humenda** [comment] 2021-12-30 02:47
Thanks for the explanation. This has been a long debugging session, so your
pointer is appreciated :).

>You'll need to place `resolver = "2"` in the workspace definition.  The new feature resolver is able to avoid unifying features in some cases like this.  

Ok, I was assuming that it would be active with all crates being at edition=2021.

Thanks again
