### ISSUE TITLE
Soundness regression with `for<'lt>` closure having an implied bound from return type

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#114936] opened 2023-08-17 14:34 UTC
Bug originally found by @ast-ral, [over Discord](https://discord.com/channels/273534239310479360/1120175689124036669/1141229090603552910), which I've then reduced.

### Code

I tried this code:

```rust
fn whoops(
    s: String,
    f: impl for<'s> FnOnce(&'s str) -> (&'static str, [&'static &'s (); 0]),
) -> &'static str
{
    f(&s).0
}
```

I expected to see this happen:

```rust
error[E0597]: `s` does not live long enough
 --> <source>:6:7
  |
6 |     f(&s).0
  |     --^^-
  |     | |
  |     | borrowed value does not live long enough
  |     argument requires that `s` is borrowed for `'static`
7 | }
  | - `s` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

Instead, this happened: **code compiles successfully**

### Version it soundly rejected this code:

[1.64.0](https://rust.godbolt.org/z/7G4x1PW94)

### Version with soundness regression

[1.65.0](https://rust.godbolt.org/z/G6vv7rzev) and onwards

### Proof of unsoundness:

```rs
fn static_str_identity()
  -> impl for<'s> FnOnce(&'s str) -> (
        [&'static &'s (); 0],
        &'static str,
    )
{
    |s: &/* 's */ str| ( // <----------------+ inputs restricted to `'s`.
        [], // `: [&'static &'s (); 0]`,     |
            //   thus `'s : 'static` ->------+
            //            +-<----------------+
            //            |
            //            v
        s, // `: &'s str <: &'static str`
    )
}
​
fn main()
{
    let f = static_str_identity();
    let local = String::from("...");
    let s: &'static str = f(&local).1; // <- should be rejected!
    drop(local);
    let _unrelated = String::from("UB!");
    dbg!(s); // <- compiles and prints `"UB!"`
}
```

@rustbot modify labels: +I-unsound +regression-from-stable-to-stable -regression-untriaged

### Observations

  - This does not occur if the implied-lifetime-bounds array is in closure _parameter_ position; so it looks like a bug w.r.t. not properly checking the closure _output_ type implied bounds?

  - `-Ztrait-solver=next` does not help (as of `2023-08-16`)

**Comment by lqd** [comment] 2023-08-17 16:32
Bisected to nightly-2022-08-10:
- #98863
- #100205
- #100304
- #100089
- #100318
- #99217 <- looks maybe interesting
- #100150

**Comment by apiraino** [comment] 2023-08-17 16:35
@lqd you beat me by one minute :) 

cc @lcnr for #99217 being possible cause of this unsoundness?

**Comment by apiraino** [comment] 2023-08-17 16:35
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23114936.20Soundness.20regression.20with.20.60for.3C'lt.3E.60.20closure.20having.E2.80.A6)).

@rustbot label -I-prioritize +P-high +T-compiler -needs-triage

**Comment by ast-ral** [comment] 2023-08-17 21:58
Oh, neat it did turn out to be a new soundness bug instead of a dupe of #25860. Thanks for figuring out this was a regression, @danielhenrymantilla.

**Comment by lcnr** [comment] 2023-09-07 13:45
for
```rust
fn whoops<'a, F: for<'s> FnOnce(&'s str) -> (&'static str, [&'static &'s (); 0])>(
    s: &'a str,
    f: F,
) -> &'static str
{
    f(s).0
}
```
we have a call terminator calling ` extern "rust-call" fn(F, (&'?4 str,)) -> <F as FnOnce<(&'?4 str,)>>::Output {<F as FnOnce<(&'?4 str,)>>::call_once}`. i.e. a function which returns `<F as FnOnce<(&'?4 str,)>>::Output`. This does not include the implied bounds. Checking that `<F as FnOnce<(&'?4 str,)>>::Output` is WF requires proving `F: FnOnce<(&'?4 str,)>` which succeeds without checking the usable implied bounds of the trait-ref. This is very related to other soundness bugs (TODO: link to them)

**Comment by BoxyUwU** [comment] 2023-09-07 15:44
This soundness bug is effectively only reproducible via the `Fn*` traits because the impls for it are builtin and so a little screwy. An attempt to write an explicit impl for the builtin `Fn*` impls would require an explicit bound that `'s: 'static` holds which is not present on the builtin `Fn*` impl.

There is an assumption that all it takes for an assoc type to be wf is the where clauses on it and the impl hold, and that all parameters in the traitref are wf. The builtin `Fn*` impls violate this by not having the required `'s: 'static` implied bound on the impl so we end up with `<F as Fn<...>>::Output` being able to be proven wf without proving the implied bounds.

When calling `f` we check that the fn sig of `<F as FnOnce<(&'?4 str,)>>::call_once` is wf which is `fn(F, (&'?4 str,)) -> <F as Fn<(&'?4 str,)>>::Output`. Before #99217 we would check the _normalized_ signature is wf so the return type would be `-> (&'static str, [&'static &'s (); 0])` which would cause us to prove `'s: 'static`. Now that we check the _unnormalized_ signature is wf we end up never seeing the normalized form with the `&'static &'s ()` which introduces the `'s: 'static` implied bound.

It is generally an invariant of the type system that `wf(ty)` holding should imply `wf(normalize(ty))` also holds. The fact that `F::Output` can be well formed but `(&'static str, [&'static &'s (); 0])` is not, is concerning. In an ideal world proving the `Fn* traits would require also proving all the implied bounds hold but right now that is not possible afaik.

A simple fix (albeit hacky until we make implied bounds desugared to actual bounds) would be to make us also check `wf(normalized(sig))` not just `wf(sig)`.

**Closed** 2024-02-14 05:26 UTC
Labels: P-high, regression-from-stable-to-stable, I-unsound, C-bug, T-types
