### ISSUE TITLE
Higher ranked lifetimes cannot cross type boundaries

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#28721] opened 2015-09-29 01:28 UTC
This currently does not compile:

```rust
struct Message<'a> {
    data: &'a u32,
}

struct Handler<T>(Option<Box<Fn(T)>>);

struct Cfg {
    handler: for<'a> Handler<Message<'a>>, // error: `Handler` is not a trait [E0404]
}
```

This precludes a lot of useful patterns.

**Comment by eefriedman** [comment] 2015-09-29 01:55
What you've written isn't really what you want... what you want is something more like:

```rust
struct Message<'a> {
    data: &'a u32,
}

// The second for<> is written out for clarity, but could be elided.
struct Handler<for<'a> T<'a>>(Option<Box<for<'a> Fn(T<'a>)>>);

struct Cfg {
    handler: Handler<Message>,
}
```

That's completely reasonable... but sort of complicated to implement.  Possibly a duplicate of https://github.com/rust-lang/rfcs/issues/324 .

**Comment by Diggsey** [comment] 2015-09-29 02:13
Ah, I was wondering if this was the same as HKT or not: the frustrating part about this it's that it's already possible if you get rid of `Handler` and always write the signature in full, so it feels like a failure of the language that you can't refactor out the common code.

**Comment by arielb1** [comment] 2015-09-29 18:19
As this is equivalent to HKT, I am closing (feel free to open an RFC).

**Closed by arielb1** 2015-09-29 18:19 UTC
Labels: A-lifetimes
