### ISSUE TITLE
Some errors only show up with `cargo build` not `cargo check`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#70923] opened 2020-04-08 11:05 UTC
This is partially due to the fact that our `analysis` query https://github.com/rust-lang/rust/blob/537ccdf3ac44c8c7a8d36cbdbe6fb224afabb7ae/src/librustc_interface/passes.rs#L775 does not invoke the `optimized_mir` query on all items in the current crate, and also because we don't run monomorphization when building bin crates.

* [ ] run `optimized_mir` query in `analysis`
    * this may cause slowdowns for `cargo check` because we'd be doing optimizations now
    * All const propagation lints are emitted in `optimized_mir`, but we may add more in the future.
* [ ] run monomorphization where possible.
    * Not sure how useful this is, it will only give us additional lints in very specific situations. (e.g. when we subtract something form an associated constant, we may get an overflow error depending on the value of the constant).
    * This will also be significantly more expensive than just running `optimized_mir`

cc @Centril

**Comment by RalfJung** [comment] 2020-04-08 13:28
Or maybe it is a bad idea to emit lints during optimization, and we should move the lints from const-prop to elsewhere?

**Comment by ehuss** [comment] 2020-04-08 14:53
This gets reported occasionally, like #49292 and #61330.

**Comment by oli-obk** [comment] 2020-04-08 15:38
the reason the lints are part of const prop is to ensure we don't do the work twice, once for linting and once for the const prop optimization. I'm not sure how we could do that differently.

Also I was envisioning adding more lints to the optimization pipeline instead of the other way around.

**Comment by RalfJung** [comment] 2020-04-30 06:44
Do we have a concrete example / test case demonstrating this?

**Comment by mati865** [comment] 2020-04-30 18:04
cc https://github.com/rust-lang/rust/issues/52484

**Comment by RalfJung** [comment] 2020-04-30 18:13
@ehuss has an example of this: it passes with `cargo check`, but fails `cargo build`, latest nightly `rustc 1.45.0-nightly (fa51f810e 2020-04-29)`.

```rust
fn main() {
    let a: u8 = 42;
    let b = ((a | 0x0F) - 1) >> 31 > 0;
    println!("{}", b);
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4998a76829fb44657cd8ed814fb2a191

**Comment by RalfJung** [comment] 2023-08-24 10:55
Closing as a duplicate of https://github.com/rust-lang/rust/issues/49292 (for the diagnostics emitted in MIR passes) and https://github.com/rust-lang/rust/issues/99682 (for errors during monomorphization).

**Closed by RalfJung** 2023-08-24 10:55 UTC
Labels: C-enhancement, T-compiler
