### ISSUE TITLE
compiletest crashes on CI with: expected success, got: signal: 11 (core dumped)

### ISSUE THREAD

**Issue by klensy** [rust-lang/rust#93384] opened 2022-01-27 17:48 UTC
runner: x86_64-gnu-llvm-12, ubuntu-20.04-xl
Occured in multiple pr across CI:
#93361: https://github.com/rust-lang/rust/runs/4969749566?check_suite_focus=true
#93381: https://github.com/rust-lang/rust/runs/4969258442?check_suite_focus=true
#93375: https://github.com/rust-lang/rust/runs/4967313356?check_suite_focus=true
#93239: https://github.com/rust-lang/rust/runs/4963643970?check_suite_focus=true
and others

**Comment by JakobDegen** [comment] 2022-01-27 21:04
Possibly this was #91840 ? Looking at what's been merged in the last day, that seems to be the most relevant thing

**Comment by matthiaskrgr** [comment] 2022-01-27 21:39
You mean it might have introduced a new miscompilation that made compiletest crash?

**Comment by JakobDegen** [comment] 2022-01-27 21:48
Maybe. Its also possible that there was some existing UB elsewhere that happened to get set off by this, don't really know. My observation just mostly comes from where the segfault is happening and what commits in the last day have touched nearby code

**Comment by klensy** [comment] 2022-01-27 22:34
`Warning: Skipping "src/test/ui": not a regular file or directory`
`Warning: Skipping "src/test/mir-opt": not a regular file or directory`

Why this even triggered? Looks unrelated, but still suspicious.

**Comment by ehuss** [comment] 2022-01-27 23:31
Those warnings are unrelated.  I'll post a patch soon to fix it.

**Comment by klensy** [comment] 2022-01-28 10:50
Funny thing: #93352 been merged even with crashed compiletest: https://github.com/rust-lang/rust/pull/93352#issuecomment-1022696785, how this works?

**Comment by fee1-dead** [comment] 2022-01-28 11:00
> Funny thing: #93352 been merged even with crashed compiletest: [#93352 (comment)](https://github.com/rust-lang/rust/pull/93352#issuecomment-1022696785), how this works?

The comment by @rust-log-analyzer is about the CI run not the bors run.

**Comment by klensy** [comment] 2022-01-28 11:09
> The comment by @rust-log-analyzer is about the CI run not the bors run.

Yes, it failed on PR check, not on check-all-platforms-and-merge.
So fast approving PR, so it merged even with failed PR check :-(

**Comment by klensy** [comment] 2022-01-28 17:58
@JakobDegen can you try to revert that #91840 pr and see, will it fail or not on test?

**Comment by JakobDegen** [comment] 2022-01-28 20:34
Yeah, I can do that before the end of the day

**Comment by JakobDegen** [comment] 2022-01-29 01:18
Reverting #91840 didn't fix it. Its still very suspicious that this started right after that got merged though

**Comment by tmiasko** [comment] 2022-01-29 12:27
The issue appears to be caused by a copy of dirent made in `<ReadDir as Iterator>::next`. Only a part of the structure as described by `d_reclen` is actually dereferenceable: https://github.com/rust-lang/rust/blob/ca43894e0e350af2245ba7d9ad8b6e31e0d4786d/library/std/src/sys/unix/fs.rs#L492-L497

**Comment by Mark-Simulacrum** [comment] 2022-01-29 15:32
It sounds like reverting that PR would be a good first step, since the bugs it fixes look less critical to me given that diagnosis.

(Of course, maybe there is a more forward-moving fix, but a revert seems like something we can merge with less caution).

cc @joshtriplett @tavianator

**Comment by tavianator** [comment] 2022-01-29 15:43
I'll take a look.  @tmiasko do you mean the `entry: *entry_ptr` part?  I didn't expect `d_reclen < sizeof(struct dirent)` but maybe it's possible.

**Comment by tavianator** [comment] 2022-01-29 15:44
Oh indeed that seems to happen all the time.  One sec I'll put up a patch

**Closed** 2022-01-30 13:38 UTC
Labels: A-spurious, T-infra, P-critical
