### ISSUE TITLE
"future cannot be sent between threads safely" error too conservative, doesn't account for moved/dropped objects

### ISSUE THREAD

**Issue by gh2o** [rust-lang/rust#72100] opened 2020-05-11 03:29 UTC
I tried this code:

```rust
struct NonSend(*mut ());

async fn foo() {
    let ns = NonSend(0 as *mut ());
    drop(ns);
    async{}.await;
}

pub fn main() {
    assert_send(foo());
}

fn assert_send<S: Send>(_: S) {}
```

I expected to see this happen: Successful compilation

Instead, this happened: Following error was produced:

```
error: future cannot be sent between threads safely
  --> test.rs:10:5
   |
10 |     assert_send(foo());
   |     ^^^^^^^^^^^ future returned by `foo` is not `Send`
...
13 | fn assert_send<S: Send>(_: S) {}
   |    -----------    ---- required by this bound in `assert_send`
   |
   = help: within `impl std::future::Future`, the trait `std::marker::Send` is not implemented for `*mut ()`
note: future is not `Send` as this value is used across an await
  --> test.rs:6:5
   |
4  |     let ns = NonSend(0 as *mut ());
   |         -- has type `NonSend`
5  |     drop(ns);
6  |     async{}.await;
   |     ^^^^^^^^^^^^^ await occurs here, with `ns` maybe used later
7  | }
   | - `ns` is later dropped here

error: aborting due to previous error
```

It looks like the compiler is a bit too conservative about when `ns` is dropped. In the case of the `if` branch being taken, `ns` gets dropped before await and thus should be a "dead" variable by the time the await occurs, but the compiler still thinks that the drop occurs at the end of the function.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment] 2020-05-11 11:26
Duplicate of https://github.com/rust-lang/rust/issues/57478

**Closed by jonas-schievink** 2020-05-11 11:26 UTC
Labels: C-bug
