### ISSUE TITLE
[Rustbuild] Found possibly newer version of crate `std` which `rustc_serialize` depends on

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#39396] opened 2017-01-29 17:04 UTC
It's hard to tell exactly what causes this sort of error, but I see similar errors quite often after pulling from GitHub. Let me know if there's other artifacts or anything else I can provide to help diagnose this.

Verbose log:
```
$ ./x.py test src/test/run-pass --stage 1 --verbose
    Finished debug [unoptimized] target(s) in 0.0 secs
finding compilers
CC_x86_64-unknown-linux-gnu = "cc"
AR_x86_64-unknown-linux-gnu = "ar"
CXX_x86_64-unknown-linux-gnu = "c++"
running sanity check
collecting channel variables
updating submodules
running: "git" "submodule" "sync"
Synchronizing submodule url for 'src/compiler-rt'
Synchronizing submodule url for 'src/jemalloc'
Synchronizing submodule url for 'src/liblibc'
Synchronizing submodule url for 'src/llvm'
Synchronizing submodule url for 'src/rt/hoedown'
Synchronizing submodule url for 'src/rust-installer'
running: "git" "reset" "--hard"
HEAD is now at a8fc4c16 Merge pull request #28 from xen0n/preprocessor-firefighting
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at 11bfb0d Merge pull request #16 from glandium/rust
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at 7d57bdcd Auto merge of #484 - eddyb:dox-unops, r=alexcrichton
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at ceb177eeefa Merge pull request #60 from japaric/gh38406
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at a3736a0 Merge pull request #6 from intelfx/patch-1
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at 4f99485 Merge pull request #54 from brson/docdir
running: "git" "clean" "-fdx"
learning about cargo
bootstrap top targets:
	Step { name: "check-rpass", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
bootstrap build plan:
	Step { name: "create-sysroot", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "create-sysroot", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "rustc", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "startup-objects", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "build-crate-std_shim", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libstd-link", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libstd", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "build-crate-test_shim", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libtest-link", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libtest", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "llvm", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "build-crate-rustc-main", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "librustc-link", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "librustc", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "rustc", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "startup-objects", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "build-crate-std_shim", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libstd-link", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libstd", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "build-crate-test_shim", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libtest-link", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "libtest", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "tool-compiletest", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "test-helpers", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "android-copy-libs", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
	Step { name: "check-rpass", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "create-sysroot", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "create-sysroot", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "rustc", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "startup-objects", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "build-crate-std_shim", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
running: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/home/mark/Build/rust/src/rustc/std_shim/Cargo.toml"
       Fresh build_helper v0.1.0 (file:///home/mark/Build/rust/src/build_helper)
       Fresh core v0.0.0 (file:///home/mark/Build/rust/src/libcore)
       Fresh gcc v0.3.40
       Fresh alloc v0.0.0 (file:///home/mark/Build/rust/src/liballoc)
       Fresh std_unicode v0.0.0 (file:///home/mark/Build/rust/src/libstd_unicode)
       Fresh rand v0.0.0 (file:///home/mark/Build/rust/src/librand)
       Fresh collections v0.0.0 (file:///home/mark/Build/rust/src/libcollections)
       Fresh libc v0.0.0 (file:///home/mark/Build/rust/src/rustc/libc_shim)
       Fresh compiler_builtins v0.0.0 (file:///home/mark/Build/rust/src/libcompiler_builtins)
       Fresh panic_abort v0.0.0 (file:///home/mark/Build/rust/src/libpanic_abort)
       Fresh unwind v0.0.0 (file:///home/mark/Build/rust/src/libunwind)
       Fresh alloc_system v0.0.0 (file:///home/mark/Build/rust/src/liballoc_system)
       Fresh panic_unwind v0.0.0 (file:///home/mark/Build/rust/src/libpanic_unwind)
       Fresh alloc_jemalloc v0.0.0 (file:///home/mark/Build/rust/src/liballoc_jemalloc)
       Fresh std v0.0.0 (file:///home/mark/Build/rust/src/libstd)
       Fresh std_shim v0.1.0 (file:///home/mark/Build/rust/src/rustc/std_shim)
    Finished release [optimized] target(s) in 0.0 secs
executing step Step { name: "libstd-link", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
executing step Step { name: "libstd", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "build-crate-test_shim", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Building stage0 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
running: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--manifest-path" "/home/mark/Build/rust/src/rustc/test_shim/Cargo.toml"
       Fresh term v0.0.0 (file:///home/mark/Build/rust/src/libterm)
       Fresh getopts v0.0.0 (file:///home/mark/Build/rust/src/libgetopts)
       Fresh test v0.0.0 (file:///home/mark/Build/rust/src/libtest)
       Fresh test_shim v0.1.0 (file:///home/mark/Build/rust/src/rustc/test_shim)
    Finished release [optimized] target(s) in 0.0 secs
executing step Step { name: "libtest-link", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Copying stage0 test from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
executing step Step { name: "libtest", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "llvm", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "build-crate-rustc-main", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
running: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--features" " jemalloc" "--manifest-path" "/home/mark/Build/rust/src/rustc/Cargo.toml"
       Fresh rustc_bitflags v0.0.0 (file:///home/mark/Build/rust/src/librustc_bitflags)
       Fresh log v0.0.0 (file:///home/mark/Build/rust/src/liblog)
       Fresh gcc v0.3.40
       Fresh arena v0.0.0 (file:///home/mark/Build/rust/src/libarena)
       Fresh fmt_macros v0.0.0 (file:///home/mark/Build/rust/src/libfmt_macros)
       Fresh graphviz v0.0.0 (file:///home/mark/Build/rust/src/libgraphviz)
       Fresh rustc_i128 v0.0.0 (file:///home/mark/Build/rust/src/librustc_i128)
       Fresh build_helper v0.1.0 (file:///home/mark/Build/rust/src/build_helper)
       Fresh rustc_platform_intrinsics v0.0.0 (file:///home/mark/Build/rust/src/librustc_platform_intrinsics)
       Fresh serialize v0.0.0 (file:///home/mark/Build/rust/src/libserialize)
       Fresh syntax_pos v0.0.0 (file:///home/mark/Build/rust/src/libsyntax_pos)
       Fresh rustc_data_structures v0.0.0 (file:///home/mark/Build/rust/src/librustc_data_structures)
       Fresh rustc_errors v0.0.0 (file:///home/mark/Build/rust/src/librustc_errors)
       Fresh flate v0.0.0 (file:///home/mark/Build/rust/src/libflate)
       Fresh rustc_llvm v0.0.0 (file:///home/mark/Build/rust/src/librustc_llvm)
       Fresh syntax v0.0.0 (file:///home/mark/Build/rust/src/libsyntax)
       Fresh proc_macro v0.0.0 (file:///home/mark/Build/rust/src/libproc_macro)
       Fresh rustc_const_math v0.0.0 (file:///home/mark/Build/rust/src/librustc_const_math)
       Fresh rustc_back v0.0.0 (file:///home/mark/Build/rust/src/librustc_back)
       Fresh syntax_ext v0.0.0 (file:///home/mark/Build/rust/src/libsyntax_ext)
       Fresh rustc v0.0.0 (file:///home/mark/Build/rust/src/librustc)
       Fresh rustc_privacy v0.0.0 (file:///home/mark/Build/rust/src/librustc_privacy)
       Fresh rustc_const_eval v0.0.0 (file:///home/mark/Build/rust/src/librustc_const_eval)
       Fresh rustc_metadata v0.0.0 (file:///home/mark/Build/rust/src/librustc_metadata)
       Fresh rustc_resolve v0.0.0 (file:///home/mark/Build/rust/src/librustc_resolve)
       Fresh rustc_save_analysis v0.0.0 (file:///home/mark/Build/rust/src/librustc_save_analysis)
       Fresh rustc_incremental v0.0.0 (file:///home/mark/Build/rust/src/librustc_incremental)
       Fresh rustc_typeck v0.0.0 (file:///home/mark/Build/rust/src/librustc_typeck)
       Fresh rustc_mir v0.0.0 (file:///home/mark/Build/rust/src/librustc_mir)
       Fresh rustc_passes v0.0.0 (file:///home/mark/Build/rust/src/librustc_passes)
       Fresh rustc_lint v0.0.0 (file:///home/mark/Build/rust/src/librustc_lint)
       Fresh rustc_plugin v0.0.0 (file:///home/mark/Build/rust/src/librustc_plugin)
       Fresh rustc_trans v0.0.0 (file:///home/mark/Build/rust/src/librustc_trans)
       Fresh rustc_borrowck v0.0.0 (file:///home/mark/Build/rust/src/librustc_borrowck)
       Fresh proc_macro_plugin v0.0.0 (file:///home/mark/Build/rust/src/libproc_macro_plugin)
       Fresh rustc_driver v0.0.0 (file:///home/mark/Build/rust/src/librustc_driver)
       Fresh rustdoc v0.0.0 (file:///home/mark/Build/rust/src/librustdoc)
       Fresh rustc-main v0.0.0 (file:///home/mark/Build/rust/src/rustc)
    Finished release [optimized] target(s) in 0.0 secs
executing step Step { name: "librustc-link", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
executing step Step { name: "librustc", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "rustc", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Copying stage1 compiler (x86_64-unknown-linux-gnu)
executing step Step { name: "startup-objects", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "build-crate-std_shim", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
running: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/home/mark/Build/rust/src/rustc/std_shim/Cargo.toml"
       Fresh core v0.0.0 (file:///home/mark/Build/rust/src/libcore)
       Fresh build_helper v0.1.0 (file:///home/mark/Build/rust/src/build_helper)
       Fresh gcc v0.3.40
       Fresh rand v0.0.0 (file:///home/mark/Build/rust/src/librand)
       Fresh alloc v0.0.0 (file:///home/mark/Build/rust/src/liballoc)
       Fresh std_unicode v0.0.0 (file:///home/mark/Build/rust/src/libstd_unicode)
       Fresh collections v0.0.0 (file:///home/mark/Build/rust/src/libcollections)
       Fresh libc v0.0.0 (file:///home/mark/Build/rust/src/rustc/libc_shim)
       Fresh unwind v0.0.0 (file:///home/mark/Build/rust/src/libunwind)
       Fresh panic_abort v0.0.0 (file:///home/mark/Build/rust/src/libpanic_abort)
       Fresh alloc_system v0.0.0 (file:///home/mark/Build/rust/src/liballoc_system)
       Fresh compiler_builtins v0.0.0 (file:///home/mark/Build/rust/src/libcompiler_builtins)
       Fresh alloc_jemalloc v0.0.0 (file:///home/mark/Build/rust/src/liballoc_jemalloc)
       Fresh panic_unwind v0.0.0 (file:///home/mark/Build/rust/src/libpanic_unwind)
       Fresh std v0.0.0 (file:///home/mark/Build/rust/src/libstd)
       Fresh std_shim v0.1.0 (file:///home/mark/Build/rust/src/rustc/std_shim)
    Finished release [optimized] target(s) in 0.0 secs
executing step Step { name: "libstd-link", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
executing step Step { name: "libstd", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "build-crate-test_shim", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Building stage1 test artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
running: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--manifest-path" "/home/mark/Build/rust/src/rustc/test_shim/Cargo.toml"
       Fresh getopts v0.0.0 (file:///home/mark/Build/rust/src/libgetopts)
       Fresh term v0.0.0 (file:///home/mark/Build/rust/src/libterm)
       Fresh test v0.0.0 (file:///home/mark/Build/rust/src/libtest)
       Fresh test_shim v0.1.0 (file:///home/mark/Build/rust/src/rustc/test_shim)
    Finished release [optimized] target(s) in 0.0 secs
executing step Step { name: "libtest-link", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Copying stage1 test from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
executing step Step { name: "libtest", stage: 1, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
executing step Step { name: "tool-compiletest", stage: 0, host: "x86_64-unknown-linux-gnu", target: "x86_64-unknown-linux-gnu" }
Building stage0 tool compiletest (x86_64-unknown-linux-gnu)
running: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--manifest-path" "/home/mark/Build/rust/src/tools/compiletest/Cargo.toml"
       Fresh log v0.3.6
       Fresh rustc-serialize v0.3.19
       Fresh env_logger v0.3.5
   Compiling compiletest v0.0.0 (file:///home/mark/Build/rust/src/tools/compiletest)
     Running `/home/mark/Build/rust/build/bootstrap/debug/rustc --crate-name compiletest src/tools/compiletest/src/main.rs --crate-type bin -C opt-level=2 -C metadata=73c24ea7041cbcca -C extra-filename=-73c24ea7041cbcca --out-dir /home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps --emit=dep-info,link --target x86_64-unknown-linux-gnu -L dependency=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/release/deps --extern log=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/liblog-8fea599810f87f11.rlib --extern rustc_serialize=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/librustc_serialize-ae20735284b6aaa6.rlib --extern env_logger=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libenv_logger-2ed6b4d5cbd2041d.rlib --cfg cargobuild`
error[E0460]: found possibly newer version of crate `std` which `rustc_serialize` depends on
  --> src/tools/compiletest/src/main.rs:26:1
   |
26 | extern crate rustc_serialize;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: crate `std` path #1: /home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f143d936af1f194.rlib
   = note: crate `std` path #2: /home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f143d936af1f194.so
   = note: crate `rustc_serialize` path #1: /home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/librustc_serialize-ae20735284b6aaa6.rlib

error: aborting due to previous error

error: Could not compile `compiletest`.

Caused by:
  process didn't exit successfully: `/home/mark/Build/rust/build/bootstrap/debug/rustc --crate-name compiletest src/tools/compiletest/src/main.rs --crate-type bin -C opt-level=2 -C metadata=73c24ea7041cbcca -C extra-filename=-73c24ea7041cbcca --out-dir /home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps --emit=dep-info,link --target x86_64-unknown-linux-gnu -L dependency=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/release/deps --extern log=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/liblog-8fea599810f87f11.rlib --extern rustc_serialize=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/librustc_serialize-ae20735284b6aaa6.rlib --extern env_logger=/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps/libenv_logger-2ed6b4d5cbd2041d.rlib --cfg cargobuild` (exit code: 101)


command did not execute successfully: "/home/mark/Build/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "-j" "8" "--target" "x86_64-unknown-linux-gnu" "-v" "--release" "--manifest-path" "/home/mark/Build/rust/src/tools/compiletest/Cargo.toml"
expected success, got: exit code: 101
```

cc @alexcrichton

**Comment by nagisa** [comment] 2017-01-29 17:06
Libraries for `stage0-tools` are not recompiled properly when their dependencies change.

Doing a `rm -rf build/<target>/stage0-tools` usually fixes the issue for me.

**Comment by est31** [comment] 2017-01-29 17:16
Yup, every time I saw that issue @nagisa 's workaround worked for me as well.

**Comment by alexcrichton** [comment] 2017-01-29 21:24
The cause of this issue is [this FIXME](https://github.com/rust-lang/rust/blob/4be49e1937e25cc9c78d7758e095046563052dec/src/bootstrap/compile.rs#L390-L397).

**Comment by shepmaster** [comment] 2017-02-13 02:43
Sadly, [the workaround](https://github.com/rust-lang/rust/issues/39396#issuecomment-275928311) does not seem to apply to the issue closed as a dupe, where I run `python ../x.py test ../src/test/compile-fail/`.

**Comment by nagisa** [comment] 2017-02-13 04:22
The underlying issue is the same, libraries which conflict are different. In your case nuking the whole build directory is probably the easiest workaround.

**Closed** 2017-04-13 23:01 UTC
Labels: A-rustbuild
