### ISSUE TITLE
rustdoc: enum fields should use fully-qualified type

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#86640] opened 2021-06-26 00:16 UTC
Right now, when an enum field is rendered, it uses the bare type name without module or crate qualifiers. For instance: https://docs.rs/rustls/0.19.1/rustls/enum.TLSError.html

```
pub enum TLSError {
    ...
    WebPKIError(Error),
    InvalidSCT(Error),
```

Those `Error` are two different error types from other crates: webpki::Error and sct::Error. And indeed you can see that by hovering them. I think the displayed name should also use the fully qualified form.

**Comment by jyn514** [comment] 2021-06-26 01:33
This is a duplicate of an existing issue, but I can't find it.

**Comment by camelid** [comment] 2021-07-05 02:20
I found it: #42066.

**Closed** 2021-07-05 02:40 UTC
Labels: A-rustdoc-ui, T-rustdoc
