### ISSUE TITLE
Confusing error message on error [E0599]

### ISSUE THREAD

**Issue by Razican** [rust-lang/rust#66289] opened 2019-11-11 10:53 UTC
Hi!
I was doing some work with `async_std` when I got a confusing error message. With this minimal code:
```rust
use async_std::{stream::Stream, task::Poll};

pub fn test_poll_next<F, T>(first: F) -> Poll<Option<T>>
where
    F: Stream<Item = T>,
{
    first.poll_next()
}
```

I got this error:
```
error[E0599]: no method named `poll_next` found for type `F` in the current scope
 --> src/lib.rs:7:11
  |
7 |     first.poll_next()
  |           ^^^^^^^^^ method not found in `F`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following traits define an item `poll_next`, perhaps you need to restrict type parameter `F` with one of them:
  |
3 | pub fn test_poll_next<F: futures_core::stream::Stream, T>(first: F) -> Poll<Option<T>>
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3 | pub fn test_poll_next<F: futures_core::stream::Stream, T>(first: F) -> Poll<Option<T>>
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

If I follow the suggestion, import `futures_core` and so on, I get the following error message:
```
error[E0599]: no method named `poll_next` found for type `F` in the current scope
 --> src/lib.rs:7:11
  |
7 |     first.poll_next()
  |           ^^^^^^^^^ method not found in `F`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following traits define an item `poll_next`, perhaps you need to restrict type parameter `F` with one of them:
  |
3 | pub fn test_poll_next<F: futures_core::stream::Stream + futures_core::stream::Stream, T>(first: F) -> Poll<Option<T>>
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3 | pub fn test_poll_next<F: futures_core::stream::Stream + futures_core::stream::Stream, T>(first: F) -> Poll<Option<T>>
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Which seems to be redundant. So, this seems not to be the issue I'm facing. What is really happening here?

**Comment by TimoFreiberg** [comment] 2019-11-11 20:27
The error message is not that helpful, but the problem is that [poll_next](https://docs.rs/async-std/1.0.0/async_std/stream/trait.Stream.html#tymethod.poll_next) takes a `Pin<&mut Self>`, not a `Self`.

Adding the `unstable` feature and changing the function signature to
```
fn test_poll_next<F,T>(first: Pin<&mut F>) -> Poll<Option<T>> 
where
    F: Stream<Item = T>
{
    first.poll_next()
}
```
, I get the following error:

```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
  --> src/main.rs:11:11
   |
11 |     first.poll_next()
   |           ^^^^^^^^^ expected 1 parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`.
error: could not compile `test-66289`.

To learn more, run the command again with --verbose.
```

Which makes sense as `poll_next` also takes a `&mut Context` argument.

**Comment by nagisa** [comment] 2020-02-18 03:33
Duplicate of #65149

**Closed by nagisa** 2020-02-18 03:33 UTC
Labels: A-diagnostics, A-suggestion-diagnostics, C-enhancement, D-confusing, D-invalid-suggestion, T-compiler
