### ISSUE TITLE
ARMv6 architecture support broken in nightly-2019-07-18

### ISSUE THREAD

**Issue by Majkl578** [rust-lang/rust#62841] opened 2019-07-21 01:27 UTC
The support for ARMv6 architecture was broken somewhere between 07e0c3651...bc2e84ca0: `nightly-2019-07-16` compiles file while `nightly-2019-07-17` produces binary that crashes with `Illegal instruction`.

More specifically, this is a binary cross-compiled from `x86_64-unknown-linux-gnu` for `arm-unknown-linux-gnueabihf` arch, linked with a [custom linker for ARMv6](https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/arm-linux-gnueabihf).

The hardware is part of Raspberry Pi Zero rev. 1.1, the processor information is as follows:
```
$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 000000005f455245
```

**Comment by nikic** [comment] 2019-07-21 08:29
Presumably due to LLVM update. Can you determine what the illegal instruction is? (E.g. via gdb and `disassemble`.)

**Comment by acnologia000** [comment] 2019-07-23 08:08
did you try compiling code on your raspberry pi 0  ? 
this might be issue with gcc cross compiler (code generator part) rather than Rust

**Comment by Majkl578** [comment] 2019-07-23 11:16
Looks like even compilation directly on RPi0 is broken as the compiler crashes:
```
 $ cargo build --examples
    Updating crates.io index
Illegal instruction
```

Running under gdb:
```
 $ gdb -q --args cargo build
Reading symbols from cargo...done.
(gdb) r
Starting program: /home/pi/.cargo/bin/cargo build
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
process 1600 is executing new program: /home/pi/.rustup/toolchains/nightly-2019-07-20-arm-unknown-linux-gnueabihf/bin/cargo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
    Updating crates.io index
[New Thread 0xb6d7b2f0 (LWP 1615)]
[Thread 0xb6d7b2f0 (LWP 1615) exited]

Thread 1 "cargo" received signal SIGILL, Illegal instruction.
0x00566c54 in cargo::util::progress::State::tick ()
(gdb) bt full
#0  0x00566c54 in cargo::util::progress::State::tick ()
No symbol table info available.
#1  0xbeff856c in ?? ()
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) layout asm
   lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
   x0x566c30 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+88>   ldrb   r0, [r4, #144]  ; 0x90                                                                                                                                                                         x
   x0x566c34 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+92>   mvn    r1, #0                                                                                                                                                                                         x
   x0x566c38 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+96>   str    r1, [r4, #140]  ; 0x8c                                                                                                                                                                         x
   x0x566c3c <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+100>  cmp    r0, #0                                                                                                                                                                                         x
   x0x566c40 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+104>  ldrbne r0, [r4, #145]  ; 0x91                                                                                                                                                                         x
   x0x566c44 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+108>  cmpne  r0, #0                                                                                                                                                                                         x
   x0x566c48 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+112>  bne    0x566dc8 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+496>                                                                                                 x
   x0x566c4c <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+116>  vmov   s0, r7                                                                                                                                                                                         x
   x0x566c50 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+120>  vldr   d8, [pc, #1008] ; 0x567048 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+1136>                                                                              x
  >x0x566c54 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+124>  vcvt.f64.u32   d16, s0                                                                                                                                                                                x
   x0x566c58 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+128>  vmov   s0, r6                                                                                                                                                                                         x
   x0x566c5c <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+132>  vcvt.f64.u32   d17, s0                                                                                                                                                                                x
   x0x566c60 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+136>  ldr    r2, [r4, #140]  ; 0x8c                                                                                                                                                                         x
   x0x566c64 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+140>  add    r2, r2, #1                                                                                                                                                                                     x
   x0x566c68 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+144>  str    r2, [r4, #140]  ; 0x8c                                                                                                                                                                         x
   x0x566c6c <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+148>  stmib  sp, {r6, r7}                                                                                                                                                                                   x
   x0x566c70 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+152>  vdiv.f64       d16, d17, d16                                                                                                                                                                          x
   x0x566c74 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+156>  vmov   r0, r1, d16                                                                                                                                                                                    x
   x0x566c78 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+160>  vldr   d17, [pc, #1008]        ; 0x567070 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+1176>                                                                      x
   x0x566c7c <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+164>  bic    r1, r1, #-2147483648    ; 0x80000000                                                                                                                                                           x
   x0x566c80 <_ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568+168>  vmov   d18, r0, r1                                                                                                                                                                                    x
   mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
multi-thre Thread 0xb6ff0010 ( In: _ZN5cargo4util8progress5State4tick17hfa4ef476c56b997eE.llvm.6020787217439157568                                                                                                                                                                      L??   PC: 0x566c54
```

@nikic I'm not sure if this helpful at all, I can send (e-mail) you the coredump or do anything else you need, unfortunately I have basically no experience debugging low-level ASM issues.

**Comment by nikic** [comment] 2019-07-23 11:52
The problematic instruction is `vcvt.f64.u32`, which [requires](https://github.com/llvm/llvm-project/blob/53f9fec8e8b58f5a904bbfb4a1d648cde65aa860/llvm/lib/Target/ARM/ARMInstrVFP.td#L1409) vfp2 and dpvfp. The [arm-unknown-linux-gnueabihf](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/arm_unknown_linux_gnueabihf.rs) target builds with `+vfp2`.

There were some changes in LLVM 9 around the sp/dp handling on ARM (`+fp-only-sp` became `-fp64`), possibly we flipped a default there...

**Comment by Majkl578** [comment] 2019-07-23 12:23
According to the ARM1176JZF-S™ Technical Reference Manual (which is the CPU used in Raspberry Pi Zero) it contains a VFP11 coprocessor (VFP2 implementation with full support for single-precision and double-precision math operations).
Maybe VFP11 is somehow slightly different from what LLVM assumes?

ARM refs:
- [ARM1176JZF-S™ Technical Reference Manual](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0301h/index.html)
- [VFP11 ™ VectorFloating-point Coprocessor Technical Reference Manual
for ARM1136JF-S](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0274h/index.html)
- [ARM Architecture Reference Manual ARMv7-A and ARMv7-R edition *+ later ARMv6 architecture releases for ARM11 processors*](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0406c/index.html)

**Comment by nikic** [comment] 2019-07-23 17:32
Thanks for the references. So both vfp2 and fp64 should be supported.

Something I missed before is that the instruction uses the `d16` register, while the VFP11 coprocessor only has 16 double-precision registers. To target this CPU `-d32` needs to be added to the target features.

It looks like the corresponding [armv7 target](https://github.com/rust-lang/rust/blob/0324a2b309cd66cb7bd4a156bd0b84cb136e254f/src/librustc_target/spec/armv7_unknown_linux_gnueabihf.rs) does disable `d32`.

Possibly the default flipped here, in which case we should just add `-d32` to all the older ARM targets.

**Comment by gnzlbg** [comment] 2019-07-24 15:10
This issue might be related to this one #62932

**Comment by jonas-schievink** [comment] 2019-07-24 15:22
This is probably caused by https://github.com/llvm/llvm-project/commit/760df47b778a530e9368a4b8706940ba103d57ba

**Comment by nikic** [comment] 2019-07-26 21:19
Reopening until there is confirmation that this is fixed...

**Comment by Majkl578** [comment] 2019-07-28 01:07
Hi @nikic, with the recent ´*1.38.0-nightly (c43753f91 2019-07-26)* both local toolchain / cargo and the cross-compiled binary seem to work. 👌

**Comment by jonas-schievink** [comment] 2019-07-28 08:25
Great, closing as fixed

**Closed by jonas-schievink** 2019-07-28 08:25 UTC
Labels: A-LLVM, C-bug, I-crash, O-ARM, P-high, T-compiler, regression-from-stable-to-nightly
