### ISSUE TITLE
nixos: `note: rust-lld: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory `

### ISSUE THREAD

**Issue by thedavidmeister** [rust-lang/rust#55979] opened 2018-11-15 14:14 UTC
`note: rust-lld: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`

when building `wasm32-unknown-unknown` on nixos

seems similar or the same as this IRC log https://logs.nix.samueldr.com/nixos/2018-09-15#1568323;

cause wasm to fail to build

```
error: linking with `rust-lld` failed: exit code: 127
  |
  = note: "rust-lld" "-flavor" "wasm" "-L" "/home/holochain/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/home/holochain/holochain-rust/core/src/nucleus/wasm-test/target/wasm32-unknown-unknown/release/deps/debug.debug.4fhiz1r9-cgu.5.rcgu.o" "-o" "/home/holochain/holochain-rust/core/src/nucleus/wasm-test/target/wasm32-unknown-unknown/release/deps/debug.wasm" "--export" "debug_hello" "--export" "debug_stacked_hello" "--export" "debug_multiple" "--gc-sections" "-O2" "-L" "/home/holochain/holochain-rust/core/src/nucleus/wasm-test/target/wasm32-unknown-unknown/release/deps" "-L" "/home/holochain/holochain-rust/core/src/nucleus/wasm-test/target/release/deps" "-L" "/home/holochain/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/home/holochain/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-7cd1fa06f8e8a370.rlib" "--no-threads" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-entry" "--export-table" "--fatal-warnings"
  = note: rust-lld: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
          

error: aborting due to previous error

error: Could not compile `debug`.
```

**Comment by thedavidmeister** [comment] 2018-11-16 07:39
maybe dupe https://github.com/rust-lang/rust/issues/51304

**Comment by Tmplt** [comment] 2018-11-20 21:10
I also get this error, but when linking an embedded Rust project; specifically https://docs.rs/cortex-m-quickstart/0.3.1/cortex_m_quickstart/.

**Comment by kevincox** [comment] 2018-12-08 21:10
I think this is a dupe of #51304. Do you want to close it @thedavidmeister?

**Comment by Tmplt** [comment] 2018-12-08 23:35
For the sake of resolving the problem I had: setting
```
LD_LIBRARY_PATH="${stdenv.cc.cc.lib}/lib64:$LD_LIBRARY_PATH";
```
fixed my problem.

**Comment by kevincox** [comment] 2018-12-09 10:38
Thanks @Tmplt, I used this work work around the issue. For something outside of nix the following worked:

```
export LD_LIBRARY_PATH=$(nix-build -E 'import <nixpkgs>' -A 'gcc.cc.lib')/lib64
```

**Comment by jonas-schievink** [comment] 2020-03-12 21:19
The workaround of setting `LD_LIBRARY_PATH` sometimes breaks programs by making them load an incompatible library. It also seems no longer necessary on the current nixpkgs version.

**Closed** 2020-03-27 08:04 UTC
Labels: A-LLVM, A-linkage, C-bug, O-NixOS, T-compiler

**Comment by nh2** [comment] 2025-07-13 16:51
Fix for `mold` and `lld` with correct wrapping, see [this comment](https://github.com/NixOS/nixpkgs/issues/215260#issuecomment-3067161637).
