### ISSUE TITLE
Failure to install cargo package

### ISSUE THREAD

**Issue by ZNielsen** [rust-lang/rust#64370] opened 2019-09-11 03:32 UTC
When attempting to install a binary via cargo, I got a build failure.

I tried this code:

`cargo install fd-find` 

I expected to see this happen: Successful installation of fd.

Instead, this happened:

```
cargo install fd-find                                                                                                                  [4:18:39]
    Updating crates.io index
  Installing fd-find v7.3.0
   Compiling libc v0.2.62
   Compiling memchr v2.2.1
   Compiling bitflags v1.1.0
   Compiling log v0.4.8
thread 'rustc' panicked at 'internal error: entered unreachable code', src/librustc_metadata/schema.rs:230:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0 (eae3437df 2019-08-13) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C opt-level=3 -C codegen-units=1 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `log`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `fd-find v7.3.0`, intermediate artifacts can be found at `/tmp/cargo-installoBWQ0Q`

Caused by:
  build failed
○ ~ ❯
```

## Meta

`rustc --version --verbose`:
```
rustc 1.37.0 (eae3437df 2019-08-13)
binary: rustc
commit-hash: eae3437dfe991621e8afdc82734f4a172d7ddf9b
commit-date: 2019-08-13
host: armv7-unknown-linux-gnueabihf
release: 1.37.0
LLVM version: 8.0
```

Backtrace:
```
○ ~ ❯ RUST_BACKTRACE=1 cargo install fd-find                                                                                                 [4:28:38]
    Updating crates.io index
  Installing fd-find v7.3.0
   Compiling libc v0.2.62
   Compiling memchr v2.2.1
   Compiling bitflags v1.1.0
   Compiling log v0.4.8
   Compiling lazy_static v1.4.0
error: Could not compile `libc`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build /home/pi3/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.62/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C codegen-units=1 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=87ba4dede3034d42 -C extra-filename=-87ba4dede3034d42 --out-dir /tmp/cargo-installoYrpPN/release/build/libc-87ba4dede3034d42 -L dependency=/tmp/cargo-installoYrpPN/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `fd-find v7.3.0`, intermediate artifacts can be found at `/tmp/cargo-installoYrpPN`

Caused by:
  build failed
○ ~ ❯                
```

**Comment by ZatchBo** [comment] 2019-09-11 04:07
I was able to build when running with `cargo install fd-find -j1`.

**Comment by mati865** [comment] 2019-09-11 10:02
I believe this is duplicate of https://github.com/rust-lang/rust/issues/64355

**Comment by Nilstrieb** [comment] 2023-07-05 05:08
The suspected duplicate has been fixed and I know from experience that cargo installing fd-find doesn't usually ICE these days. So in the absence of a reproduction here, I'm going to close this issue. If you encounter new problems, feel free to open a new issue.

**Closed by Nilstrieb** 2023-07-05 05:08 UTC
Labels: I-ICE, A-metadata, T-compiler, C-bug
