### ISSUE TITLE
rustdoc: intradoc links to `std` don't behave as expected

### ISSUE THREAD

**Issue by Skirmisher** [rust-lang/rust#85106] opened 2021-05-09 08:55 UTC
Currently, rustdoc links to types in `std` that come from `core` or `alloc` resolve to the latter two crates. (They also link to nightly docs even on stable versions, but that's orthogonal.) This behavior is debatably appropriate for crates using `std`, but it's not a big deal.

However, explicit intradoc links (e.g. `[std::vec::Vec]`) also exhibit this behavior, which as a documentation writer I find confusing: if a path resolves to a different crate than the one I specified, I'm surprised.

**Comment by jyn514** [comment] 2021-06-05 12:34
Duplicate of https://github.com/rust-lang/rust/issues/83976.

**Closed by jyn514** 2021-06-05 12:34 UTC
Labels: C-bug
