### ISSUE TITLE
Warn when a higher-ranked trait bound variable is unused

### ISSUE THREAD

**Issue by SNCPlay42** [rust-lang/rust#82998] opened 2021-03-11 00:24 UTC
This use of HRTB currently compiles without any warnings:

```rust
pub fn foo<T>() where for<'a> T: Sized {}
```

It would be helpful for the compiler to warn that the `'a` lifetime is unnecessary.

@rustbot label A-lint A-lifetimes C-feature-request

**Comment by Aaron1011** [comment] 2021-12-16 21:07
This produces a warning with `#![warn(unused_lifetimes)]`. See https://github.com/rust-lang/rust/issues/41960

**Comment by Mark-Simulacrum** [comment] 2022-02-16 02:26
Going to go ahead and close this in favor of https://github.com/rust-lang/rust/issues/94038 since this is otherwise working as intended (just needs that to be enabled).

**Closed by Mark-Simulacrum** 2022-02-16 02:26 UTC
Labels: A-lint, A-lifetimes, C-feature-request
