### ISSUE TITLE
Zero sized DST struct item causes invalid free

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#23491] opened 2015-03-18 22:11 UTC
```
struct Node<T: ?Sized>(T);

fn main() {
   let x: Box<Node<[isize]>> = box Node([]);
}
```

seems to result in a call to ```foo::heap::exchange_free(1, 0, 1)``` in the drop glue (and no allocates), which results in a crash. Just doing ```Box<[isize]>``` works, as do non-empty input arrays.

**Comment by alexcrichton** [comment] 2015-03-18 22:19
cc @nrc

**Comment by nrc** [comment] 2015-03-19 01:33
cc @eddyb should this have been fixed by #23376? Or did #23376 cause a regression?

**Comment by eddyb** [comment] 2015-03-19 14:36
@nrc it appears to have been fixed, this example doesn't crash in my local branch (assuming it's not something else I've done since).

**Comment by fhahn** [comment] 2015-04-23 14:13
I have added 2 tests based on @talchas example, one using the `box` syntax and one using `Box::new`. Interestingly, using `Box::new` causes a compile time error:

    issue-23491-2.rs:5:41: 5:49 error: mismatched types:
         expected `Node<[isize]>`,
         found `Node<[isize; 0]>`
     (expected slice,
        found array of 0 elements) [E0308]
    issue-23491-2.rs:5    let x: Box<Node<[isize]>> = Box::new(Node([]));
                                                               ^~~~~~~~
    issue-23491-2.rs:5:32: 5:40 error: the trait `core::marker::Sized` is not implemented for the type  `[isize]` [E0277]
    issue-23491-2.rs:5    let x: Box<Node<[isize]>> = Box::new(Node([]));
                                                       ^~~~~~~~
    issue-23491-2.rs:5:32: 5:40 note: `[isize]` does not have a constant size known at compile-time
    issue-23491-2.rs:5    let x: Box<Node<[isize]>> = Box::new(Node([]));
                                                        ^~~~~~~~
    error: aborting due to 2 previous errors

Shouldn't they both behave similar in this case?

**Comment by apasel422** [comment] 2015-07-18 22:17
@fhahn's test with `Box::new` doesn't compile because the argument to that function must be `Sized`. However, the code does compile and run successfully with the `box` syntax, so a PR containing src/test/run-pass/issue-23491.rs
 from https://github.com/fhahn/rust/commit/e8d712274a9248f90cfc313b932e590fa3981b9d should close this issue.

**Closed** 2015-07-20 04:52 UTC
Labels: A-dst, E-needstest
