### ISSUE TITLE
link failure on nightly, windows

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#67483] opened 2019-12-21 13:21 UTC
Since `rustc 1.42.0-nightly (01a46509a 2019-12-20)` I'm getting link failures on travis ci that did not occur previously (`rustc 1.42.0-nightly (0de96d37f 2019-12-19)`)
https://travis-ci.org/matthiaskrgr/cargo-cache/jobs/628012845#L195

````
  = note: C:\Users\travis\build\matthiaskrgr\cargo-cache\target\debug\deps\liblibgit2_sys-b28d7af61e5f6f84.rlib(cache.o): In function `printf':
          C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/include/stdio.h:349: undefined reference to `__imp___acrt_iob_func'
          C:\Users\travis\build\matthiaskrgr\cargo-cache\target\debug\deps\liblibgit2_sys-b28d7af61e5f6f84.rlib(diff_print.o): In function `git_diff_print_callback__to_file_handle':
          C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\libgit2-sys-0.10.0/libgit2/src/diff_print.c:744: undefined reference to `__imp___acrt_iob_func'
          C:\Users\travis\build\matthiaskrgr\cargo-cache\target\debug\deps\liblibgit2_sys-b28d7af61e5f6f84.rlib(xdiffi.o): In function `xdl_bug':
          C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\libgit2-sys-0.10.0/libgit2/src/xdiff/xdiffi.c:816: undefined reference to `__imp___acrt_iob_func'
          C:\Users\travis\build\matthiaskrgr\cargo-cache\target\debug\deps\liblibgit2_sys-b28d7af61e5f6f84.rlib(util.o): In function `printf':
          C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/include/stdio.h:349: undefined reference to `__imp___acrt_iob_func'
````

I'm wondering if this is related to https://github.com/rust-lang/rust/pull/67020

Edit: travis config can be found here: https://github.com/matthiaskrgr/cargo-cache/blob/master/.travis.yml#L15

**Comment by Mark-Simulacrum** [comment] 2019-12-21 13:33
cc @michaelwoerister @pnkfelix 

Given our desire to keep nightly working over the holidays if we confirm it is indeed this PR and do not have a fix in the pipeline I will work on reverting it today/tomorrow.

**Comment by Mark-Simulacrum** [comment] 2019-12-21 13:38
@matthiaskrgr informs me that this appears only broken on Travis, and one of the symbols in the log is repeatedly mentioned in https://github.com/rust-lang/rust/issues/47048 which leads me to suspect that it's a change in the environment rather than a bug on our side, so I withdraw my eagerness to revert at least until we have more information.

**Comment by mati865** [comment] 2019-12-21 17:20
I also think something has changed in Travis environment or dependencies. Can you try running old nightly in the Travis?

**Comment by Mark-Simulacrum** [comment] 2019-12-21 17:27
Oh, I forgot to make a note here. @matthiaskrgr confirmed on Discord that both nightlies (today's and yesterday's) fail on Travis with the current travis environment, so something changed there. This is then not strictly a bug on our side (or at least is a duplicate of #47048 I expect), so closing.

**Closed by Mark-Simulacrum** 2019-12-21 17:27 UTC
Labels: I-nominated, T-compiler

**Comment by kpcyrd** [comment] 2019-12-23 15:28
It seems travis also broken stable rust on windows: https://travis-ci.org/kpcyrd/sn0int/jobs/628652634

**Comment by cup** [comment] 2020-01-21 02:02
https://github.com/rust-lang/rust/issues/47048
https://github.com/rust-lang/rust/issues/49078
https://github.com/rust-lang/rust/issues/53454
https://github.com/rust-lang/rust/issues/59604
https://github.com/rust-lang/rust/issues/60912

https://github.com/rust-lang/rust/issues/67483
https://github.com/rust-lang/rust/pull/67429
