### ISSUE TITLE
compiler allowed referencing &mut self from inside a move + Send closure (caused SEGV)

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#23398] opened 2015-03-15 19:02 UTC
Ok, so I believe that this may be a compiler bug. If it isn't, then I misunderstood something that changed recently (removing 'static from Send) and the library does have some unsafe code, though it isn't directly related to the bit that is causing problems (I think).

The compiler allowed referencing `&mut self` from inside a `move` + `Send` closure that ends up getting moved off the stack and lives longer than the original lifetime, so the `&mut self` is no longer valid and causes a crash.

The illegal reference is here: https://github.com/carllerche/syncbox/blob/how-did-this-compile/src/util/async/sequence.rs#L149

The `move` is 7 lines above. The `receive` function is defined here: https://github.com/carllerche/syncbox/blob/how-did-this-compile/src/util/async/mod.rs#L107-L108. It's only marked as `Send` and not `Send + 'static` because the compiler permitted it, so I am not entirely sure if it is a compiler bug vs. something related to unsafe code I have in the implementation...

**Comment by carllerche** [comment] 2015-03-16 00:24
Ok, so this is a bug with rustc. It involves traits and implementations. Here is a repro:

```rust
use std::old_io::timer;
use std::time::Duration;
use std::thread;

trait Action {
    fn one<F>(&self, f: F) where F: FnOnce() + Send {
        self.two(f);
    }

    fn two<F>(&self, f: F) where F: FnOnce() + Send;
}

pub struct Zomg(Vec<u32>);

impl Zomg {
    fn action(&self) {
        self.one(|| println!("SIZE: {}", self.0.len()));
    }
}

impl Action for Zomg {
    fn two<F>(&self, f: F) where F: FnOnce() + Send + 'static {
        thread::spawn(move || {
            timer::sleep(Duration::milliseconds(50));
            f()
        });
    }
}

pub fn main() {
    let z = Zomg(vec![1, 2, 3, 4]);
    z.action();
    drop(z);

    let mut v = Vec::new();

    for i in 0..1_000_000 {
        v.push("ZOOOOOMG".to_string());
    }

    timer::sleep(Duration::milliseconds(400));
}
```

**Comment by huonw** [comment] 2015-03-16 01:18
I believe this is a dupe of https://github.com/rust-lang/rust/issues/22779: a trait impl allows for more restrictive bounds than in the trait to be imposed. In particular, the `+ 'static` in `impl Action for Zomg` shouldn't be allowed.

**Closed by huonw** 2015-03-16 01:18 UTC
