### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by aseyboldt** [rust-lang/rust#32335] opened 2016-03-18 13:24 UTC
rustc 1.7.0 panics on this code using https://github.com/netvl/xml-rs:

``` rust
extern crate xml;

use xml::reader::XmlEvent;

struct Foo {
    tmp: XmlEvent::StartDocument
}
```

I'm using the arch linux package of cargo and rust:

```
$ rustc --version --verbose
rustc 1.7.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.7.0
```

backtrace:

```
RUST_BACKTRACE=1 cargo build                                                                                                                                  :(
   Compiling mzml v0.1.0 (file:///home/adr/git/QBiC/mzml-rs)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:330
stack backtrace:
   1:     0x7f53c9831ac0 - sys::backtrace::tracing::imp::write::h19a75f57079ca7d6Eju
   2:     0x7f53c9838965 - panicking::default_handler::_<closure>::closure.42502
   3:     0x7f53c98383ce - panicking::default_handler::heecbc8b8a021fa9bGwy
   4:     0x7f53c9801186 - sys_common::unwind::begin_unwind_inner::hd4253a1812044857bct
   5:     0x7f53c9801b88 - sys_common::unwind::begin_unwind_fmt::h281339998baa4cbdhbt
   6:     0x7f53c982f8f1 - rust_begin_unwind
   7:     0x7f53c98782bf - panicking::panic_fmt::h0d7335d3d6686f32zYL
   8:     0x7f53c9878db8 - panicking::panic::h64c7ea62c5c222316WL
   9:     0x7f53c8c348c4 - astconv::finish_resolving_def_to_ty::h222b4e72d7249e64gdw
  10:     0x7f53c8bdc640 - astconv::ast_ty_to_ty::h5ae146dd47eb55e0Kew
  11:     0x7f53c8cb6d2c - collect::convert_field::h0fad19dff0dc9a419Ox
  12:     0x7f53c8ca4788 - collect::convert_item::hca74eee61cc53108hUx
  13:     0x7f53c8ca290d - collect::CollectItemTypesVisitor<'a, 'tcx>.intravisit..Visitor<'v>::visit_item::h94fc315c258fbbe1Pjx
  14:     0x7f53c8ba57fd - collect::collect_item_types::h8760836d5303318edcx
  15:     0x7f53c8ba19e9 - check_crate::he83b63c674cfb338rNC
  16:     0x7f53c9d52257 - driver::phase_3_run_analysis_passes::_<closure>::closure.26763
  17:     0x7f53c9d38f4d - middle::ty::context::ctxt<'tcx>::create_and_enter::h9886975242668009234
  18:     0x7f53c9d34842 - driver::phase_3_run_analysis_passes::h4778203650522424616
  19:     0x7f53c9d053bb - driver::compile_input::hbc7144eff304cc7enca
  20:     0x7f53c9cf691b - run_compiler::h9947f6ff221ed46f7wc
  21:     0x7f53c9cf3751 - sys_common::unwind::try::try_fn::h15363083919275164358
  22:     0x7f53c982f888 - __rust_try
  23:     0x7f53c982709b - sys_common::unwind::try::inner_try::ha2ff38ef4cd20984J8s
  24:     0x7f53c9cf3ab0 - boxed::F.FnBox<A>::call_box::h16963941508860420611
  25:     0x7f53c9836b33 - sys::thread::Thread::new::thread_start::h75fdeb8aaf6deb4eCtx
  26:     0x7f53c3004423 - start_thread
  27:     0x7f53c94b6cbc - clone
  28:                0x0 - <unknown>
```

**Comment by Aatch** [comment] 2016-03-26 07:39
This should be an error, since `XmlEvent::StartDocument` is an enum variant, not a type.

**Comment by Mark-Simulacrum** [comment] 2017-05-02 12:19
There's not quite enough information to reproduce exactly since there's no git hash for the commit of xml-rs, but with master I cannot reproduce. Closing.

**Closed by Mark-Simulacrum** 2017-05-02 12:19 UTC
Labels: I-ICE
