### ISSUE TITLE
On error due to reference introduced by default binding modes, point out where reference was introduced

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#70933] opened 2020-04-08 19:08 UTC
Simple example:

```rust
fn example(x: &Option<S>) {
    match x {
        Some(val) => drop::<S>(val),
        None => (),
    }
}
```

```
error[E0308]: mismatched types
 --> src/lib.rs:6:32
  |
6 |         Some(val) => drop::<S>(val),
  |         ^^^^^^^^^              ^^^
  |         |                      |
  |         |                      expected struct `S`, found `&S`
  |         |                      help: consider dereferencing the borrow: `*val`
  |         note: borrow introduced here because pattern has type `&std::option::Option<crate::S>`
  |         help: consider destructuring the borrow here: `&Some(val)`
```

(plus if/when `Some(&val)` works to destrucure the borrow, suggest that instead)

[Initially suggested on irlo](https://internals.rust-lang.org/t/is-ref-more-powerful-than-match-ergonomics/12111/28?u=cad97), cc @joshtriplett @rpjohnst 

This should help remove some of the pain points people have had around default binding modes ("match ergonomics") introducing needless borrows, as the error message now also points at the pattern, like it did before default binding modes were introduced.

(As a side note: a (clippy) lint for binding a `Copy` value by reference that could be bound by copy would also help here, independently of improving the error message.)

@rustbot modify labels: +A-diagnostics

**Comment by Centril** [comment] 2020-04-08 19:39
Duplicate of https://github.com/rust-lang/rust/issues/70047.

**Closed by Centril** 2020-04-08 19:39 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
