### ISSUE TITLE
Rustdoc-Json: Reference to missing item with 2 glob imports

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#100973] opened 2022-08-24 22:38 UTC
```rust
#![feature(no_core)]
#![no_core]
mod m1 {
    pub fn f() {}
}
mod m2 {
    pub fn f(_: u8) {}
}
pub use m2::*;
pub use m1::*;
```

Produces an output with references to non existant items: `0:3:1564` and `0:1:1563`

```json
{
  "crate_version": null,
  "external_crates": {},
  "format_version": 18,
  "includes_private": false,
  "index": {
    "0:0:1565": {
      "crate_id": 0,
      "id": "0:0:1565",
      "inner": {"is_crate": true, "is_stripped": false, "items": ["0:5", "0:6"]},
      "kind": "module",
      "name": "glob_private_simple",
      "visibility": "public"
    },
    "0:5": {
      "crate_id": 0,
      "id": "0:5",
      "inner": {"glob": true, "id": "0:3:1564", "name": "m2", "source": "m2"},
      "kind": "import",
      "name": null,
      "visibility": "public"
    },
    "0:6": {
      "crate_id": 0,
      "id": "0:6",
      "inner": {"glob": true, "id": "0:1:1563", "name": "m1", "source": "m1"},
      "kind": "import",
      "name": null,
      "visibility": "public"
    }
  },
  "root": "0:0:1565"
}
```

<details>

<summary> Full </summary>

```json
{
  "crate_version": null,
  "external_crates": {},
  "format_version": 18,
  "includes_private": false,
  "index": {
    "0:0:1565": {
      "attrs": ["#![feature(no_core)]", "#![no_core]"],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:0:1565",
      "inner": {"is_crate": true, "is_stripped": false, "items": ["0:5", "0:6"]},
      "kind": "module",
      "links": {},
      "name": "glob_private_simple",
      "span": {
        "begin": [1, 0],
        "end": [12, 14],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "public"
    },
    "0:5": {
      "attrs": [],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:5",
      "inner": {"glob": true, "id": "0:3:1564", "name": "m2", "source": "m2"},
      "kind": "import",
      "links": {},
      "name": null,
      "span": {
        "begin": [11, 0],
        "end": [11, 14],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "public"
    },
    "0:6": {
      "attrs": [],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:6",
      "inner": {"glob": true, "id": "0:1:1563", "name": "m1", "source": "m1"},
      "kind": "import",
      "links": {},
      "name": null,
      "span": {
        "begin": [12, 0],
        "end": [12, 14],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "public"
    }
  },
  "paths": {"0:0:1565": {"crate_id": 0, "kind": "module", "path": ["glob_private_simple"]}},
  "root": "0:0:1565"
}
```

</details>

If you remove one of the imports, everything is fine

```rust
#![feature(no_core)]
#![no_core]
mod m1 {
    pub fn f() {}
}
mod m2 {
    pub fn f(_: u8) {}
}
pub use m2::*;
```

```json
{
  "crate_version": null,
  "external_crates": {},
  "format_version": 18,
  "includes_private": false,
  "index": {
    "0:0:1565": {
      "crate_id": 0,
      "id": "0:0:1565",
      "inner": {"is_crate": true, "is_stripped": false, "items": ["0:5"]},
      "kind": "module",
      "name": "glob_private_simple",
      "visibility": "public"
    },
    "0:3:1564": {
      "crate_id": 0,
      "id": "0:3:1564",
      "inner": {"is_crate": false, "is_stripped": true, "items": ["0:4:630"]},
      "kind": "module",
      "name": "m2",
      "visibility": "crate"
    },
    "0:4:630": {
      "crate_id": 0,
      "id": "0:4:630",
      "inner": { ... },
      "kind": "function",
      "name": "f",
      "visibility": "public"
    },
    "0:5": {
      "crate_id": 0,
      "id": "0:5",
      "inner": {"glob": true, "id": "0:3:1564", "name": "m2", "source": "m2"},
      "kind": "import",
      "name": null,
      "visibility": "public"
    }
  },
  "root": "0:0:1565"
}
```

<details>

<summary> Full </summary>

```json
{
  "crate_version": null,
  "external_crates": {},
  "format_version": 18,
  "includes_private": false,
  "index": {
    "0:0:1565": {
      "attrs": ["#![feature(no_core)]", "#![no_core]"],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:0:1565",
      "inner": {"is_crate": true, "is_stripped": false, "items": ["0:5"]},
      "kind": "module",
      "links": {},
      "name": "glob_private_simple",
      "span": {
        "begin": [1, 0],
        "end": [11, 14],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "public"
    },
    "0:3:1564": {
      "attrs": [],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:3:1564",
      "inner": {"is_crate": false, "is_stripped": true, "items": ["0:4:630"]},
      "kind": "module",
      "links": {},
      "name": "m2",
      "span": {
        "begin": [7, 0],
        "end": [7, 6],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "crate"
    },
    "0:4:630": {
      "attrs": [],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:4:630",
      "inner": {
        "decl": {
          "c_variadic": false,
          "inputs": [["_", {"inner": "u8", "kind": "primitive"}]],
          "output": null
        },
        "generics": {"params": [], "where_predicates": []},
        "header": {"abi": "Rust", "async": false, "const": false, "unsafe": false}
      },
      "kind": "function",
      "links": {},
      "name": "f",
      "span": {
        "begin": [8, 4],
        "end": [8, 22],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "public"
    },
    "0:5": {
      "attrs": [],
      "crate_id": 0,
      "deprecation": null,
      "docs": null,
      "id": "0:5",
      "inner": {"glob": true, "id": "0:3:1564", "name": "m2", "source": "m2"},
      "kind": "import",
      "links": {},
      "name": null,
      "span": {
        "begin": [11, 0],
        "end": [11, 14],
        "filename": "/home/nixon/dev/rust/rust/src/test/rustdoc-json/reexport/glob_private_simple.rs"
      },
      "visibility": "public"
    }
  },
  "paths": {"0:0:1565": {"crate_id": 0, "kind": "module", "path": ["glob_private_simple"]}},
  "root": "0:0:1565"
}
```

</details>

This should have been caught by `check_missing_items.py`, but wasn't. Instead is was caught by [`jsondoclint`](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/check_missing_items.2Epy.20Replacement.2E), a rust based replacement (PR soon).

@rustbot modify labels: +A-rustdoc-json +T-rustdoc

**Comment by Urgau** [comment] 2022-08-24 22:41
Seems like a duplicate of https://github.com/rust-lang/rust/issues/99513

**Comment by aDotInTheVoid** [comment] 2022-08-24 22:52
I don't thinks so, as that occors with just 1 import, whereas this requires 2. Also thats for importing foreign items, whereas this happens for local items.

**Comment by aDotInTheVoid** [comment] 2022-08-27 22:38
Smaller version:
```rust
#![feature(no_core)]
#![no_core]

mod m2 {}
pub use m2::*;
```

```json
{
  "crate_version": null,
  "external_crates": {},
  "format_version": 18,
  "includes_private": false,
  "index": {
    "0:0:1567": {
      "crate_id": 0,
      "id": "0:0:1567",
      "inner": {"is_crate": true, "is_stripped": false, "items": ["0:2"]},
      "kind": "module",
      "name": "bug"
    },
    "0:2": {
      "crate_id": 0,
      "id": "0:2",
      "inner": {"glob": true, "id": "0:1:1566", "name": "m2", "source": "m2"},
      "kind": "import",
      "name": null
    }
  },
  "root": "0:0:1567"
}
```

It looks like empty modules are being stripped. This also happens in the above example because both functions are named `f`, so because the name clashes none are callable. renaming one of them, or adding items with non classing names to both modules fixes this

**Comment by aDotInTheVoid** [comment] 2022-08-27 22:42
Caused by https://github.com/rust-lang/rust/blob/eaadb8947b850a025404082f6297766c4680a42a/src/librustdoc/json/conversions.rs#L52

@rustbot claim

**Closed** 2022-08-30 01:30 UTC
Labels: T-rustdoc, A-rustdoc-json
