### ISSUE TITLE
ld.lld: error: undefined symbol: hashbrown::raw::Bucket...

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#72471] opened 2020-05-22 03:24 UTC
**Problem**

```
          ld.lld: error: undefined symbol: hashbrown::raw::Bucket$LT$T$GT$::as_mut::h17a5616906d4548a
          >>> referenced by map.rs:852 (/cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/map.rs:852)
          >>>               rcc-51c66ac989f8d3c5.4ecfujcnmkq7jcjv.rcgu.o:(hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::insert::ha9fbaa5b9f695ac0) in archive /home/joshua/.local/lib/cargo/target/debug/deps/librcc-51c66ac989f8d3c5.rlib
          
          ld.lld: error: undefined symbol: hashbrown::raw::RawTable$LT$T$GT$::reserve::h5da6b3a04cbac1f7
          >>> referenced by map.rs:583 (/cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.6.2/src/map.rs:583)
          >>>               rcc-51c66ac989f8d3c5.4ecfujcnmkq7jcjv.rcgu.o:(hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::reserve::h6e6157315bd86437) in archive /home/joshua/.local/lib/cargo/target/debug/deps/librcc-51c66ac989f8d3c5.rlib
          
          ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
          collect2: error: ld returned 1 exit status
```

**Steps**

I am not sure how to replicate this bug. I found it while compiling https://github.com/jyn514/rcc/pull/446/commits/efc37d2ce1d885b839451cbff969bd2ac398293d with `--all-features`. I think it might be related to incremental compilation? I have `$CARGO_TARGET_DIR` set to a global directory and it has a lot of junk in it, in case that matters. I tried `rm -rf /home/joshua/.local/lib/cargo/target/debug/deps/*rcc*` without success.

Output of `cargo version`:

cargo 1.43.0 (3532cf738 2020-03-17) (stable)

**Comment by alexcrichton** [comment] 2020-05-22 16:30
I've transferred this issue to rust-lang/rust since this is unlikely to be a Cargo-specific issue, but thanks for the report!

**Comment by jyn514** [comment] 2020-12-21 04:37
I have not run into this in a very long time, I'd be ok with closing it.

**Comment by RodBurman** [comment] 2024-12-28 19:20
If jyn514 is happy with closing the issue, why don't we just close it?

**Closed** 2024-12-28 19:29 UTC
Labels: A-linkage, T-compiler, A-incr-comp, C-bug

**Comment by imthatgin** [comment] 2025-01-18 12:10
I run into this fairly often when using `linker = "rust-lld.exe"` on a larger multi-crate project.

**Comment by RodBurman** [comment] 2025-01-18 13:46
Does it clear-up with a clean cache as it did for jyn514? That would seem to indicate a problem with the cache code, either what is written to cache or what/how it is retrieved. or do you have a "minimal" way to reproduce?

**Comment by imthatgin** [comment] 2025-01-19 09:54
> Does it clear-up with a clean cache as it did for jyn514? That would seem to indicate a problem with the cache code, either what is written to cache or what/how it is retrieved. or do you have a "minimal" way to reproduce?

It does work after cleaning. I’m getting it from a Bevy repo where the dynamic linking feature is enabled occasionally. Not sure how to reproduce other than to make small changes with a hot reload enabled.

**Comment by imthatgin** [comment] 2025-01-19 13:46
> Are you ever canceling a build while it is running? If so there is already an issue for getting linker errors when compiling after aborting an incr comp build at the right point.

Yeah I think that could be the cause of it, yeah.
