### ISSUE TITLE
Internal Compiler Error on OSX Sierra

### ISSUE THREAD

**Issue by trevoranderson** [rust-lang/rust#38403] opened 2016-12-16 01:33 UTC
Test case created with cargo new --bin on rustc 1.15.0-nightly (ebeee0e27 2016-12-04)

```
fn repro()
{
    let q = Some(str);
}
fn main() {
    println!("Hello, world!");
}
```

Compiler Output:
```
   Compiling repro v0.1.0 (**censored**)
error: internal compiler error: ../src/librustc_typeck/check/mod.rs:4396: unexpected definition: PrimTy(TyStr)

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:423
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `repro`.

To learn more, run the command again with --verbose.
```

**Comment by est31** [comment] 2016-12-16 01:52
This is a duplicate of #38155

**Comment by est31** [comment] 2016-12-16 01:52
Should be fixed by the next time we have a nightly.

**Comment by sanxiyn** [comment] 2016-12-16 02:27
Closing as a duplicate.

**Closed by sanxiyn** 2016-12-16 02:27 UTC
