### ISSUE TITLE
rustc should complain when language items are not correctly implemented.

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#48342] opened 2018-02-18 23:52 UTC
While filing issue #48339, I made a mistake in how I was defining the `panic_fmt` language item. It was missing both a `pub` and `#[no_mangle]`. While rustc does complain when the language item is not present when building with no-std, it doesn't complain when it is present, but badly setup, and that leads to the error happening at the linker level. But by the time the linker errors out, the function has a different name, and the reason why it happens is not clear.

```
/checkout/src/libcore/panicking.rs:71: undefined reference to `rust_begin_unwind'
```
is the error as it appears, despite the language item having a different name (`panic_fmt`), and the function as defined in the source might have yet another name.

**Comment by ollie27** [comment] 2018-02-19 00:12
Dupe of #9307?

**Comment by glandium** [comment] 2018-02-19 00:16
Surely related, but that bug doesn't talk about pub and no_mangle, only about the function signatures (arguments and return value, which I've also noticed the compiler doesn't care about)

**Comment by pietroalbini** [comment] 2018-02-20 14:23
Duplicate of #9307, closing this.

Even if that issue doesn't mention pub and no_mangle explicitly, I'm confident that will be checked as part of the function signature (if the check will be implemented in the future).

**Closed by pietroalbini** 2018-02-20 14:23 UTC
