### ISSUE TITLE
discrepancy between debug and release: panic at `attempt to add with overflow`

### ISSUE THREAD

**Issue by LollipopFt** [rust-lang/rust#94663] opened 2022-03-06 04:53 UTC
I tried this code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc2817fac40c3b63807d4375a34fd70a

this works in release, but not in debug.
### Meta

`rustc --version --verbose`:
```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-pc-windows-msvc
release: 1.59.0
LLVM version: 13.0.0
```
note: this problem appears in both rust playground and my offline rustc.

<details><summary>Backtrace</summary>
<p>

```
Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 2.73s
     Running `target/debug/playground`
thread 'main' panicked at 'attempt to add with overflow', [src/main.rs:8](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc2817fac40c3b63807d4375a34fd70a#):18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: playground::putpixel
             at ./src/main.rs:8:18
   4: playground::main
             at ./[src/main.rs:3](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc2817fac40c3b63807d4375a34fd70a#):9
   5: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by LollipopFt** [comment] 2022-03-06 05:06
found issue:
when a function is used:
```rust
fn main() {
    let x = -180 as i16;
    putpixel(x);
}

fn putpixel(x: i16) {
    let coordx = 960+x as u32;
    println!("{coordx}");
}
```
this is allowed in release as it seems it does some conversions and panics in debug, but when it is not a function:
```rust
fn main() {
    let x = -180;
    let coordx = 960+x as u32;
    println!("{coordx}");
}
```
the linter catches it:
```
Compiling playground v0.0.1 (/playground)
error: this arithmetic operation will overflow
 --> src/main.rs:3:18
  |
3 |     let coordx = 960+x as u32;
  |                  ^^^^^^^^^^^^ attempt to compute `960_u32 + 4294967116_u32`, which would overflow
  |
  = note: `#[deny(arithmetic_overflow)]` on by default

error: could not compile `playground` due to previous error
```

**Comment by Badel2** [comment] 2022-03-06 15:06
This is the expected behavior, see here for more info:

https://doc.rust-lang.org/book/ch03-02-data-types.html?highlight=overflow#integer-overflow

Also the `as` operator has higher precedence than the `+` operator, so your code is equivalent to:

```rust
fn main() {
    for i in -100..100 {
        putpixel(i);
    }
}

fn putpixel(x: i16) {
    let coordx = 960+(x as u32);
    println!("{coordx}");
}
```

While you probably intended to do:

```rust
fn main() {
    for i in -100..100 {
        putpixel(i);
    }
}

fn putpixel(x: i16) {
    let coordx = (960+x) as u32;
    println!("{coordx}");
}
```

**Comment by ehuss** [comment] 2022-03-06 20:51
Closing per the comment above.  This is expected behavior as `--release` will disable overflow checks.  More about what `--release` does can be found in the [profile documentation](https://doc.rust-lang.org/cargo/reference/profiles.html#release) along with explanations of the various settings like [`overflow-checks`](https://doc.rust-lang.org/cargo/reference/profiles.html#overflow-checks).

As for the `arithmetic_overflow` lint, this is limited by the situations where `rustc` is able to do compile-time function evaluation.  It is not able to do constant evaluation for all expressions (it is limited to only a few situations).

**Closed by ehuss** 2022-03-06 20:51 UTC
Labels: C-bug
