### ISSUE TITLE
BufRead read_line should give error on EOF

### ISSUE THREAD

**Issue by tfogal** [rust-lang/rust#22685] opened 2015-02-22 20:32 UTC
Currently it is just returning a 0-length buffer, but this is unintuitive; one expects IO functions to give back EOF when they are finished.

AFAICT (line 833 of mod.rs?), the current implementation will pop off the newline.  This is nice (IMHO)! However, without EOF, it means that the user of the method cannot differentiate between end of file and a blank line in the file (or whatever they're reading from).

**Comment by alexcrichton** [comment] 2015-02-23 07:44
Dupe of #22588, but thanks!

**Closed by alexcrichton** 2015-02-23 07:44 UTC
