### ISSUE TITLE
ICE "no type for node..."

### ISSUE THREAD

**Issue by lexxvir** [rust-lang/rust#44869] opened 2017-09-26 19:30 UTC
The compiler unexpectedly panicked on wrong code.

Reduced version of code:

```rust
fn main() {
    bug("", "");
}

fn bug<'a>(v1: &mut'a str, v2: &mut'a str) {
    let _ = v1.chars();
    let _ = v2.split('.').map(|p| p.parse::<u64>());
    
    std::mem::swap(v1, v2);
}
```

Output:
```
error: expected type, found `'a`
 --> src/main.rs:5:20
  |
5 | fn bug<'a>(v1: &mut'a str, v2: &mut'a str) {
  |                    ^^

error: expected type, found `'a`
 --> src/main.rs:5:36
  |
5 | fn bug<'a>(v1: &mut'a str, v2: &mut'a str) {
  |                                    ^^

error[E0425]: cannot find value `v1` in this scope
 --> src/main.rs:6:13
  |
6 |     let _ = v1.chars();
  |             ^^ not found in this scope

error[E0425]: cannot find value `v2` in this scope
 --> src/main.rs:7:13
  |
7 |     let _ = v2.split('.').map(|p| p.parse::<u64>());
  |             ^^ not found in this scope

error[E0425]: cannot find value `v1` in this scope
 --> src/main.rs:9:20
  |
9 |     std::mem::swap(v1, v2);
  |                    ^^ not found in this scope

error[E0425]: cannot find value `v2` in this scope
 --> src/main.rs:9:24
  |
9 |     std::mem::swap(v1, v2);
  |                        ^^ not found in this scope

error: internal compiler error: /checkout/src/librustc_typeck/check/mod.rs:2015: no type for node 33: type u64 (id=33) in fcx 0x7f53da9f2000

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.22.0-nightly (6c476ce46 2017-09-25) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:492:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

## Meta

rustc 1.22.0-nightly (6c476ce46 2017-09-25)
[Link to playground](https://play.rust-lang.org/?gist=3dae9a1f60754433110198442b28e040&version=nightly)

**Comment by TimNN** [comment] 2017-09-27 05:09
Likely related to ##44814.

**Comment by nikomatsakis** [comment] 2017-09-28 20:23
triage: P-high

Assigning to @petrochenkov as the theory is that is same cause as #44814, which is believed to be due to https://github.com/rust-lang/rust/pull/44633.

**Comment by petrochenkov** [comment] 2017-09-30 10:52
This is an exact duplicate of https://github.com/rust-lang/rust/issues/44814

**Closed by petrochenkov** 2017-09-30 10:52 UTC
Labels: C-bug, I-ICE, P-high, regression-from-stable-to-nightly, T-compiler
