### ISSUE TITLE
1.32.0 cargo binary for powerpc64le linux SIGILLs

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#58334] opened 2019-02-09 22:08 UTC
Using the `cargo` from [this](https://static.rust-lang.org/dist/rust-1.32.0-powerpc64le-unknown-linux-gnu.tar.gz) we get the following SIGILL. The `rustc` is fine however.

Using gdb to set a breakpoint in `rand_pool_acquire_entropy` and then single-stepping, we eventually reach:

~~~~
   │0x10087fac8 <rand_pool_acquire_entropy+136>     mr      r4,r3161,3 
  >│0x10087facc <rand_pool_acquire_entropy+140>     bl      0x100000000
   │0x10087fad0 <rand_pool_acquire_entropy+144>     nop              87ebc0 <rand_pool_bytes_needed+240>
~~~~

which does not seem to be a real address to actual code. When jumping to this address, the gdb disassembler then executes one instruction (probably it decodes by accident) and then it SIGILLs at address 0x100000004:

~~~~
  >│0x100000000     .long 0x464c457f
   │0x100000004     .long 0x10102
~~~~

~~~~
Program received signal SIGILL, Illegal instruction.
0x0000000100000004 in ?? ()
~~~~

The Debian `cargo` 1.32.0 binary works fine, partly this is because it dynamically links to the system openssl.

**Comment by nagisa** [comment] 2019-02-09 22:52
This is a duplicate of https://github.com/rust-lang/cargo/issues/6320. Closing in favour of that.

**Comment by nagisa** [comment] 2019-02-09 22:53
Alternatively, https://github.com/rust-lang/rust/issues/57345.

**Closed by nagisa** 2019-02-09 22:52 UTC
