### ISSUE TITLE
Bringing a trait alias into scope doesn't allow calling methods from its component traits

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#56485] opened 2018-12-03 23:05 UTC
```rust
#![feature(trait_alias)]

mod some_module {
    pub trait Foo {
        fn foo(&self);
    }
    
    pub struct Qux;
    
    impl Foo for Qux {
        fn foo(&self) {}
    }
    
    pub trait Bar = Foo;
}

use some_module::{Bar, Qux};

fn use_baz(object: Qux) {
    // Should this work because Bar is in scope?
    object.foo();
}
```

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=169f5809b367991b8a9547b424eefe1e)) currently produces an error:

```
error[E0599]: no method named `foo` found for type `some_module::Qux` in the current scope
  --> src/lib.rs:21:12
   |
8  |     pub struct Qux;
   |     --------------- method `foo` not found for this
...
21 |     object.foo();
   |            ^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
17 | use some_module::Foo;
   |
```

cc #41517

**Comment by alexreg** [comment] 2018-12-03 23:54
Thanks for opening this. @Centril, what does your intuition say about this?

**Comment by Centril** [comment] 2018-12-04 00:03
@alexreg The thing I'm currently thinking about is what makes sense when you extend it beyond this simple example; in particular, if we say: `trait Foo = TraitA + TraitB;` and then we `use path::to::Foo;`, does that then bring into scope both `TraitA` and `TraitB`s methods? what if there is a conflict in naming?

In other words, consider:

```rust
#![feature(trait_alias)]

mod alpha {
    pub trait A { fn foo(); }
    pub trait B { fn foo(); }
    pub trait C = A + B;
}

use alpha::C;
```
(this incidentally causes an ICE)

**Comment by alexreg** [comment] 2018-12-13 01:11
This very much looks like a duplicate of #56488.

**Comment by seanmonstar** [comment] 2019-03-08 04:22
If I were to import an alias, I'd likely often do so to call the methods off the trait as well as to set bounds. It'd be surprising if it didn't. If there is a name conflict, we can differentiate the way we do already: using UFCS with the specific trait, instead of the alias.

Is this the last thing needed to decide on for stabilization? The tracking issue makes it look that :D

**Comment by alexreg** [comment] 2019-03-08 05:01
@seanmonstar That's the last "feature" that really needs to be implemented, yeah. I'd be glad to help fix it, but I'd need some advice from someone who understand the import system, really. I've not touched that before.

**Comment by seanmonstar** [comment] 2019-03-13 17:42
I was playing around with this, trying to discover where the error happens, when I found that this *doesn't* happen if you make the function generic on the trait.

```rust
fn generic<T: Bar>(object: T) {
    // works!
    object.foo();
}

fn concrete_to_generic(object: Qux) {
    // works!
    generic(object);
}
```

As for if the trait alias contains multiple traits with the same name, the method conflict is already as expected: `"multiple applicable items in scope"`, and qualifying with `some_module::Fooz::foo(&object)` works.

**Comment by alexreg** [comment] 2019-03-13 17:47
I'm not sure what you mean. Could you post a complete example on the playground?

**Comment by seanmonstar** [comment] 2019-03-13 17:54
Seems like nightly on the playground is timing out for me, but works locally: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=92e4a4878c40c2a7a6af7a04f9cfd9ed

**Comment by alexreg** [comment] 2019-03-13 18:09
Ah right, I see. That makes sense because the type system resolves the type alias then, and not name resolution.

Nightly on the playground has been broken for a while now...

**Comment by petrochenkov** [comment] 2019-03-14 05:26
@seanmonstar 
Candidates from bounds on a type parameters are treated like inherent and are found even if the trait is not in scope (the relevant code is in `fn assemble_inherent_candidates_from_param`).

@Centril 
The example seems equivalent to
```rust
#![feature(trait_alias)]

mod alpha {
    pub trait A { fn foo() {} }
    pub trait B { fn foo() {} }
    // pub trait C = A + B;
    
    impl A for u8 {}
    impl B for u8 {}
}

// use alpha::C;
use alpha::*;

fn main() {
    u8::foo(); // ERROR multiple applicable items in scope
}
```
, the ambiguity error is already reported during resolution of a specific method in this case.

**Comment by petrochenkov** [comment] 2019-03-26 06:47
One interesting effect is that the traits become in scope in the module that defines (rather than imports) the alias.

```rust
#![feature(trait_alias)]

mod m {
    pub trait A { fn foo() {} }
    pub trait B { fn bar() {} }
    
    impl A for u8 {}
    impl B for u8 {}
}

trait C = m::A + m::B;

fn main() {
    u8::foo(); // OK
}
```

**Closed** 2019-04-02 19:32 UTC
Labels: A-resolve, A-traits, I-needs-decision, T-lang
