### ISSUE TITLE
Rustdoc does not properly render higher-ranked lifetimes on the left-hand side of where clause bounds

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#39213] opened 2017-01-21 03:53 UTC
Rustdoc confusingly renders the following function:

```rust
pub fn takes_ref<T>(foo: &T) where for<'a> &'a T: Sized {}
```
(`Sized` bound just used for demonstration, I know this doesn't add any meaning.)

as this:

```rust
pub fn takes_ref<T>(foo: &T) 
where &'a T: Sized
```

The `for<'a>` is omitted when it shouldn't be, because there's now magically a lifetime parameter that doesn't appear to be declared anywhere.

This doesn't just affect functions, of course:

```rust
pub struct Foo<T>(T) where for<'a> &'a T: Sized;
// Rendered:
pub struct Foo<T>(_) where &'a T: Sized;
```
```rust
pub trait Foo<T> where for<'a> &'a T: Sized {}
// Rendered: 
pub trait Foo<T> where &'a T: Sized { }
```

Higher-ranked lifetimes on the right-hand side of a `where` clause bound are rendered correctly:
```rust
pub trait Foo<T> where T: for<'a> Bar<'a> {}
pub trait Bar<'a> {}

// `Foo` rendered:
pub trait Foo<T> where T: for<'a> Bar<'a> { }
```

**Comment by durka** [comment] 2017-02-21 06:51
[Causing confusion in the wild.](https://www.reddit.com/r/rust/comments/5v1acp/hey_rustaceans_got_an_easy_question_ask_here_82017/de0bmxw/)

**Comment by jyn514** [comment] 2021-07-07 04:19
Triage: duplicate of https://github.com/rust-lang/rust/issues/78482 (or the other way around), fixed on nightly by https://github.com/rust-lang/rust/pull/84814.

![image](https://user-images.githubusercontent.com/23638587/124699556-ffafeb80-deb8-11eb-8dee-c3495eed26fd.png)

**Closed by jyn514** 2021-07-07 04:19 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
