### ISSUE TITLE
Sanitize the output of `llvm-config` when building with external LLVM

### ISSUE THREAD

**Issue by Jurily** [rust-lang/rust#14663] opened 2014-06-05 02:57 UTC
My LLVM, built with clang:

```
$ llvm-config --cflags

-I/usr/include -march=native -pipe -O3 -fPIC -Wall -W -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```

Building with gcc:

```
$ ../configure --llvm-root=/usr --prefix=$HOME/sys && make
<snip>
g++: error: unrecognized command line option ‘-Wcovered-switch-default’
/home/jurily/cucc/src/rust/rust/mk/rustllvm.mk:46: recipe for target 'x86_64-unknown-linux-gnu/rustllvm/RustWrapper.o' failed
make: *** [x86_64-unknown-linux-gnu/rustllvm/RustWrapper.o] Error 1
```

**Comment by tfogal** [comment] 2015-02-23 16:38
I am hitting this error message just trying to build Rust:

```shell
llvm[2]: Compiling ConvertUTF.c for Debug+Asserts build
gcc: error: unrecognized command line option ‘-Wcovered-switch-default’
/bin/rm: cannot remove ‘/home/tfogal/dev/rust/x86_64-unknown-linux-gnu/llvm/lib/Support/Debug+Asserts/ConvertUTF.d.tmp’: No such file or directory
make[2]: *** [/home/tfogal/dev/rust/x86_64-unknown-linux-gnu/llvm/lib/Support/Debug+Asserts/ConvertUTF.o] Error 1
make[2]: Leaving directory `/home/tfogal/dev/rust/x86_64-unknown-linux-gnu/llvm/lib/Support'
make[1]: *** [all] Error 1
```

I configure via:

```
#!/bin/sh

./configure \
  --disable-docs \
  --disable-optimize-llvm \
  --disable-jemalloc \
  --prefix=${HOME}/sw/ \
  --local-rust-root=${HOME}/sw/ \
  $@
```

Is there a workaround?

**Comment by tamird** [comment] 2015-06-01 17:23
Relevant: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61864

**Comment by petevine** [comment] 2016-01-05 17:22
I updated llvm-3.7 on Slackware current hoping it would be free of this [issue](https://github.com/rust-lang/rust/issues/29490) but suddenly I'm getting the above-mentioned build error using `gcc 5.3.0`

Did this flag get there from building with clang or sth?

````
$ /mnt/usr/bin/llvm-config --cflags

-I/mnt/usr/include -O2 -march=i586 -mtune=i686 -fPIC -Wall -W -Wno-unused-parameter -Wwrite-strings -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -ffunction-sections -fdata-sections -O3 -DNDEBUG  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
````

**Comment by petevine** [comment] 2016-01-18 06:21
It's about compiling just three C++ files so it's a minor mistake in the build scripts.
The correct logic would clear this flag from `llvm-config` output in case g++ is being used and not clang.

**Comment by petevine** [comment] 2016-06-11 20:32
@alexcrichton Someone has just got bitten by this [again](https://github.com/rust-lang/rust/issues/14663)

**Comment by corvinux** [comment] 2016-06-18 12:09
I'm trying to build rustc-1.9.0-src.tar.gz
with clang version 3.8.0 (tags/RELEASE_380/final), Target: armv7l-unknown-linux-gnueabihf,
and I'm getting this error:
compile: arm-unknown-linux-gnueabihf/rustllvm/ExecutionEngineWrapper.o
g++: error: unrecognized command line option '-Wcovered-switch-default'
make: *** [arm-unknown-linux-gnueabihf/rustllvm/ExecutionEngineWrapper.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.

**Comment by Mark-Simulacrum** [comment] 2017-05-05 23:51
Okay, to triage this issue a little, I think this is about us using llvm-config's output to generate gcc parameters, which breaks on external LLVM's, since those can get built with different gcc/linker params.

The current situation appears to be unchanged, but cc @brson for confirmation.

**Comment by Mark-Simulacrum** [comment] 2017-06-25 20:35
I don't believe this is a bug anymore, closing -- if someone reproduces, let us know and we'll reopen.

**Closed by Mark-Simulacrum** 2017-06-25 20:35 UTC
Labels: A-build, A-LLVM
