### ISSUE TITLE
timely-0.1.5 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43664] opened 2017-08-05 12:53 UTC
[timely](https://crates.io/crates/timely/0.1.15) version 0.1.5 regressed from stable to beta. Cargobomb couldn't pick it up directly as root regression and reported it on other crates. Error excerpt:

```
    Compiling timely v0.1.15
 error: no rules expected the token `EventStreamLogger<OperatesEvent, File>`
    --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/timely-0.1.15/src/logging.rs:160:35
     |
 160 |               __thread_local_inner!($t, $init);
     |                                     ^^
 ...
 164 | / thread_local!{
 165 | |     /// Logs operator creation.
 166 | |     pub static OPERATES: EventStreamLogger<OperatesEvent, File> = EventStreamLogger::new();
 167 | |     /// Logs channel creation.
 ...   |
 178 | |     pub static GUARDED_PROGRESS: EventStreamLogger<bool, File> = EventStreamLogger::new();
 179 | | }
     | |_- in this macro invocation
 
 error: Could not compile `timely`.
```
Affects crates:

* [differential-dataflow-0.1.0](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/differential-dataflow-0.1.0/log.txt)

cc @frankmcsherry

**Comment by arielb1** [comment] 2017-08-05 14:00
Duplicate of #43681.

**Closed by arielb1** 2017-08-05 14:00 UTC
Labels: regression-from-stable-to-beta, T-compiler

**Comment by kennytm** [comment] 2017-08-05 14:13
The old 0.1.15 version used a self-implemented `thread_local!` which directly invokes the private macro `__thread_local_inner!` (crate reverted the hack in frankmcsherry/timely-dataflow@ecad85d95318025aba1a3c87d5c986e06ed4ae40). The signature of `__thread_local_inner!` was changed in #43185.

XIB.
