### ISSUE TITLE
No way to call inherent method on `dyn Trait` when a function of the same name exists in the trait

### ISSUE THREAD

**Issue by SparkyPotato** [rust-lang/rust#109077] opened 2023-03-13 13:50 UTC
Given:

```rs
trait Foo { fn foo(&self) -> i32 { 0 } }

impl<'a> dyn Foo + 'a {
    fn foo(&self) -> i32 { 1 }
}

struct Bar;
impl Foo for Bar {}
```

There seems to be no way to call `foo` implemented on `dyn Foo + 'a`:
```rs
let x = Bar;
let dx = &x as &dyn Foo;
println!("{}", dx.foo());
```
Gives the expected error:
```rs
error[E0034]: multiple applicable items in scope
  --> src/main.rs:13:23
   |
13 |     println!("{}", dx.foo());
   |                       ^^^ multiple `foo` found
   |
note: candidate #1 is defined in an impl for the type `(dyn Foo + 'a)`
  --> src/main.rs:4:5
   |
4  |     fn foo(&self) -> i32 { 1 }
   |     ^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `Foo`
  --> src/main.rs:1:13
   |
1  | trait Foo { fn foo(&self) -> i32 { 0 } }
   |             ^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #2
   |
13 |     println!("{}", Foo::foo(&dx));
   |                    ~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0034`.
```
The compiler suggests a way to call candidate #&#8203;2, but even with
```rs
let x = Bar;
let dx = &x as &dyn Foo;
println!("{}", <dyn Foo>::foo(dx));
```
The error persists, with no seeming way to call candidate #&#8203;1.

### Meta

Version:
```
rustc 1.70.0-nightly (8a73f50d8 2023-03-11)
```

**Comment by fmease** [comment] 2023-03-13 14:26
Duplicate of #51402. #82357 related.

**Closed** 2023-03-14 10:30 UTC
Labels: C-bug
