### ISSUE TITLE
rustdoc links to private structs, causing 404s

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#23912] opened 2015-03-31 22:35 UTC
See http://doc.rust-lang.org/std/primitive.char.html#method.into_searcher as an example, `CharEqPattern` goes nowhere

**Comment by rprichard** [comment] 2015-04-01 01:12
Another example: https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.align. The `core::fmt::rt::v1::Alignment` type is public in this case, but it's explicitly hidden.

**Comment by steveklabnik** [comment] 2015-04-01 02:25
Yeah, there's a _lot_ of these.

**Comment by tomjakubowski** [comment] 2015-04-01 22:38
For `CharEqPattern`, it could be related to re-exported signatures. The same method in `core` doesn't have this issue: http://doc.rust-lang.org/core/primitive.char.html#method.into_searcher

Also, is it a bug that you can have private items in a public signature's `QPath`? Or private items in an impl for a public type? cc @alexcrichton @nikomatsakis

**Comment by tomjakubowski** [comment] 2015-04-01 22:45
I wonder if rustdoc should be resolving qualified paths that it encounters.

**Comment by mitaa** [comment] 2016-04-29 07:43
Is there still some unresolved issue here?

**Comment by QuietMisdreavus** [comment] 2017-08-15 18:08
Still a thing; for example, [Copy](https://doc.rust-lang.org/1.19.0/std/marker/trait.Copy.html) tries to link to types in rand, but the doc link is broken. (That link goes to 1.19.0, but it's still there in today's nightly docs.)

If i were to guess, it probably has to do with rustdoc seeing types that are in dependencies of std, but aren't being documented alongside it.

**Comment by GuillaumeGomez** [comment] 2017-11-26 22:07
Wrote a fix for it. Will make the PR tomorrow or after tomorrow.

**Comment by QuietMisdreavus** [comment] 2017-11-29 15:23
This issue was actually fixed by https://github.com/rust-lang/rust/pull/44026. The issue i actually referenced in that PR was apparently a duplicate of this one. `>_>`

**Closed by QuietMisdreavus** 2017-11-29 15:23 UTC
Labels: A-rustdoc, C-bug, T-dev-tools
