### ISSUE TITLE
modifying immutable refenrences via unsafe no longer works, when building a nightly release

### ISSUE THREAD

**Issue by hacbit** [rust-lang/rust#124338] opened 2024-04-24 16:20 UTC
I tried this code:

```rust
type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

pub struct ResMut<T>(*mut T);

impl<T> ResMut<T> {
    pub fn new(t: &T) -> Self {
        Self(t as *const T as *mut T)
    }

    pub fn patch_by<F>(&self, f: F) -> Result<()>
    where
        F: FnOnce(&mut T),
    {
        unsafe {
            f(&mut *self.0);
        }
        Ok(())
    }
}

#[derive(Debug)]
struct A {
    a: B,
}

#[derive(Debug)]
enum B {
    Foo,
    Bar,
}

fn main() {
    let v = vec![
        A { a: B::Foo },
        A { a: B::Foo },
        A { a: B::Foo },
        A { a: B::Foo },
    ];
    foo(&v);
    dbg!(&v);
}

fn foo(v: &[A]) {
    ResMut::new(&v[0])
        .patch_by(|x| x.a = B::Bar).unwrap();
}
```
debug build output is expected
```
[src/main.rs:40:5] &v = [
    A {
        a: Bar,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
]
```
but release is not expected:
```
[src/main.rs:40:5] &v = [
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
]
```
v[0] did not change as i expected.
But what’s interesting is that if you add a line of `dbg!(&v)` before modification (but it needs to be in the same function), it will be modified as expected.
like this:
```
fn foo(v: &[A]) {
    // add dbg here
    dbg!(&v);
    ResMut::new(&v[0])
        .patch_by(|x| x.a = B::Bar).unwrap();
}
```
now release output is expected
```
[src/main.rs:44:5] &v = [
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
]
[src/main.rs:40:5] &v = [
    A {
        a: Bar,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
    A {
        a: Foo,
    },
]
```

### Meta

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (8b2459c1f 2024-04-09)
binary: rustc
commit-hash: 8b2459c1f21187f9792d99310171a15e64feb9cf
commit-date: 2024-04-09
host: x86_64-pc-windows-msvc
release: 1.79.0-nightly
LLVM version: 18.1.3
```

**Comment by Nilstrieb** [comment] 2024-04-24 16:38
closing as not a bug

**Closed by Nilstrieb** 2024-04-24 16:38 UTC

**Comment by Soveu** [comment] 2024-04-24 17:13
Well, in more simple terms, you're just modifying immutable data - that is instant UB in Rust.
Maybe what you're looking for is [UnsafeCell](https://doc.rust-lang.org/core/cell/struct.UnsafeCell.html) or some kind of its derivative (RefCell, Mutex, RwLock)
