### ISSUE TITLE
Compiler panic on renaming a struct

### ISSUE THREAD

**Issue by danielkeller** [rust-lang/rust#91705] opened 2021-12-09 13:41 UTC
I got a compiler panic when renaming a struct from `StackPos` to `Reg`. It went away when I ran `cargo clean`, and didn't come back, so I'm not sure how to reproduce it.

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/compiler/rustc_hir/src/definitions.rs:452:14
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_query_impl::on_disk_cache::OnDiskCache as rustc_middle::ty::context::OnDiskCache>::def_path_hash_to_def_id
   4: rustc_middle::dep_graph::dep_node::<impl rustc_query_system::dep_graph::dep_node::DepNodeParams<rustc_middle::ty::context::TyCtxt> for rustc_span::def_id::LocalDefId>::recover
   5: rustc_query_impl::query_callbacks::hir_owner::force_from_dep_node
   6: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
   9: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_previous_green
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::try_mark_green
  11: rustc_query_system::query::plumbing::ensure_must_run
  12: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::coherent_trait
  13: rustc_session::session::Session::track_errors
  14: rustc_typeck::check_crate
  15: rustc_interface::passes::analysis
  16: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  17: rustc_data_structures::stack::ensure_sufficient_stack
  18: rustc_query_system::query::plumbing::try_execute_query
  19: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  20: rustc_interface::passes::QueryContext::enter
  21: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  22: rustc_span::with_source_map
  23: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by BGR360** [comment] 2021-12-21 04:04
Potential dupe of https://github.com/rust-lang/rust/issues/91696. See also https://github.com/rust-lang/rust/pull/91919.

@rustbot label +A-incr-comp

**Comment by workingjubilee** [comment] 2023-02-26 11:32
Closing assuming the previous "it's a duplicate" is correct.

**Closed by workingjubilee** 2023-02-26 11:32 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
