### ISSUE TITLE
thread 'rustc' panicked at 'no entry found for key', src/libcore/option.rs:1166:5

### ISSUE THREAD

**Issue by bbigras** [rust-lang/rust#63795] opened 2019-08-21 18:11 UTC
```
thread 'rustc' panicked at 'no entry found for key', src/libcore/option.rs:1166:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', src/librustc_codegen_ssa/back/write.rs:1506:21

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (c43d03a19 2019-08-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `someproject`.

To learn more, run the command again with --verbose.
```

**Comment by bbigras** [comment] 2019-08-21 18:18
I don't have this problem with:
rustc 1.38.0-nightly (8a58268b5 2019-07-31)

**Comment by jonas-schievink** [comment] 2019-08-21 18:22
Can you post the backtrace (run with `RUST_BACKTRACE=1`)? Can you post the code that causes this?

**Comment by bbigras** [comment] 2019-08-21 19:24
I tried to make a simpler version and I can't reproduce anymore. I wonder if the problem could have been caused by low disk space.

**Comment by jonas-schievink** [comment] 2019-08-21 19:32
Ah, then it's very likely that this is due to incremental compilation and a duplicate of https://github.com/rust-lang/rust/issues/62412, so closing in favor of that

**Closed by jonas-schievink** 2019-08-21 19:32 UTC
