### ISSUE TITLE
Unexpected panic when building code using interpolate_idents

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#35059] opened 2016-07-27 01:13 UTC
I'm not exactly sure what is causing the problem but the initial [poc](https://github.com/rust-av/rust-av/commit/0eeaf58a39b2cf69bf67090e5a37a79928d23eea) has no problems while [extending](https://github.com/rust-av/rust-av/commit/c42516d74465e556a37cdb21bea01d94d0c8e801) the macro triggers the following panic:

```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: "expected type, found `->`"', ../src/libcore/result.rs:788
stack backtrace:
   1:        0x10a9f933b - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:        0x10aa0fa8a - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:        0x10aa08019 - std::panicking::default_hook::hbbe7fa36a995aca0
   4:        0x10aa08758 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:        0x10aa085b6 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:        0x10aa084c8 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:        0x10aa0841f - rust_begin_unwind
   8:        0x10aa6f570 - core::panicking::panic_fmt::h19323e466869c656
   9:        0x10b087b00 - core::result::unwrap_failed::h3fc9aa60ec9cee26
  10:        0x10b080e3c - _<core..result..Result<T, E>>::unwrap::hd36bf1f781e1b741
  11:        0x10b0d30d9 - _<interpolate_idents..parser_any_macro..ParserAnyMacro<'a> as syntax..ext..base..MacResult>::make_items::hc79e200ea4639f73
  12:        0x10a3a73ae - syntax::ext::expand::expand_multi_modified::_{{closure}}::hbfc31b6642efd7fd
  13:        0x10a3084a1 - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  14:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  15:        0x10a310ad1 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  16:        0x10a135d92 - _<core..iter..FlatMap<I, U, F> as core..iter..iterator..Iterator>::next::h30777c87c469be7a
  17:        0x10a140587 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..FromIterator<T>>::from_iter::he529d819adae1916
  18:        0x10a2f32a0 - _<syntax..util..small_vector..SmallVector<syntax..ptr..P<syntax..ast..Item>> as syntax..ext..expand..MacroGenerable>::fold_with::h4d023a922487d1a9
  19:        0x10a3a9380 - syntax::ext::expand::expand_multi_modified::_{{closure}}::hbfc31b6642efd7fd
  20:        0x10a3084a1 - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  21:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  22:        0x10a310ad1 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  23:        0x10a1d47eb - syntax::fold::noop_fold_mod::h2d77441ecaa79d92
  24:        0x10a1ca43e - syntax::fold::noop_fold_item_kind::h36b5e3bd517f1177
  25:        0x10a1dcfe0 - syntax::fold::noop_fold_item_simple::hcc8ddb83674034a2
  26:        0x10a39648a - syntax::fold::noop_fold_item::_{{closure}}::h69a2bb7906eb478f
  27:        0x10a29408f - _<syntax..ptr..P<T>>::map::h279fe63aed2b3282
  28:        0x10a30889b - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  29:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  30:        0x10a311132 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  31:        0x10a1d47eb - syntax::fold::noop_fold_mod::h2d77441ecaa79d92
  32:        0x10a1ca43e - syntax::fold::noop_fold_item_kind::h36b5e3bd517f1177
  33:        0x10a1dcfe0 - syntax::fold::noop_fold_item_simple::hcc8ddb83674034a2
  34:        0x10a39648a - syntax::fold::noop_fold_item::_{{closure}}::h69a2bb7906eb478f
  35:        0x10a29408f - _<syntax..ptr..P<T>>::map::h279fe63aed2b3282
  36:        0x10a30889b - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  37:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  38:        0x10a310da9 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  39:        0x10a1d47eb - syntax::fold::noop_fold_mod::h2d77441ecaa79d92
  40:        0x10a1ca43e - syntax::fold::noop_fold_item_kind::h36b5e3bd517f1177
  41:        0x10a1dcfe0 - syntax::fold::noop_fold_item_simple::hcc8ddb83674034a2
  42:        0x10a39648a - syntax::fold::noop_fold_item::_{{closure}}::h69a2bb7906eb478f
  43:        0x10a29408f - _<syntax..ptr..P<T>>::map::h279fe63aed2b3282
  44:        0x10a30889b - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  45:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  46:        0x10a310da9 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  47:        0x10a1d47eb - syntax::fold::noop_fold_mod::h2d77441ecaa79d92
  48:        0x10a1ca43e - syntax::fold::noop_fold_item_kind::h36b5e3bd517f1177
  49:        0x10a1dcfe0 - syntax::fold::noop_fold_item_simple::hcc8ddb83674034a2
  50:        0x10a39648a - syntax::fold::noop_fold_item::_{{closure}}::h69a2bb7906eb478f
  51:        0x10a29408f - _<syntax..ptr..P<T>>::map::h279fe63aed2b3282
  52:        0x10a30889b - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  53:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  54:        0x10a310da9 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  55:        0x10a1d47eb - syntax::fold::noop_fold_mod::h2d77441ecaa79d92
  56:        0x10a1ca43e - syntax::fold::noop_fold_item_kind::h36b5e3bd517f1177
  57:        0x10a1dcfe0 - syntax::fold::noop_fold_item_simple::hcc8ddb83674034a2
  58:        0x10a39648a - syntax::fold::noop_fold_item::_{{closure}}::h69a2bb7906eb478f
  59:        0x10a29408f - _<syntax..ptr..P<T>>::map::h279fe63aed2b3282
  60:        0x10a30889b - syntax::ext::expand::expand_annotatable::he10687f1f71324a3
  61:        0x10a301540 - syntax::ext::expand::expand_item::h26a928b599bd1ab4
  62:        0x10a310da9 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::hda4a78ec0eda02fe
  63:        0x10a30fb3e - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_crate::h3d2c22bc23783ddf
  64:        0x10a312e93 - syntax::ext::expand::expand_crate::h1e4c4debc3e6d4d6
  65:        0x105b7e238 - rustc_driver::driver::phase_2_configure_and_expand::_{{closure}}::h650e136516de4da2
  66:        0x105b2ca3a - rustc_driver::driver::phase_2_configure_and_expand::h23617908add5ca02
  67:        0x105b23946 - rustc_driver::driver::compile_input::hb4cc34cf85dc1edf
  68:        0x105b4ccb5 - rustc_driver::run_compiler::h50f95674bd902ab5
  69:        0x105bb9f00 - rustc_driver::run::_{{closure}}::h578f58fb80a79b9c
  70:        0x105bb4b80 - rustc_driver::monitor::_{{closure}}::he296944eac047e81
  71:        0x105ab73e1 - std::panicking::try::call::h4577500a5284c6ff
  72:        0x10aa163fb - __rust_try
  73:        0x10aa162b5 - __rust_maybe_catch_panic
  74:        0x105b63106 - std::thread::Builder::spawn::_{{closure}}::haaf8628155e4305c
  75:        0x105ad1f28 - _<F as alloc..boxed..FnBox<A>>::call_box::h24f3eb0b42327962
  76:        0x10aa06a98 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  77:     0x7fff83b7699c - _pthread_body
  78:     0x7fff83b76919 - _pthread_start

error: Could not compile `av`.
```

> rustc 1.12.0-nightly (936bfea94 2016-07-20)

**Comment by Aatch** [comment] 2016-07-27 05:36
Looks like this is a bug in the `interpolate_idents` crate.

**Comment by lu-zero** [comment] 2016-07-27 14:29
That's what I initially though, but `interpolate_idents` passes its tests.

**Comment by Aatch** [comment] 2016-07-28 02:57
@lu-zero that only means the things `interpolate_idents` tests for are working. If there's no test for this case, then obviously its tests won't fail. The reason I think it might be an `interpolate_idents` issue is that the panic is triggered from within `interpolate_idents`.

**Comment by lu-zero** [comment] 2016-07-28 07:13
Looks like it is impossible to report syntax errors from within a `MacResult` in a nicer way so the plugin happily uses `unwrap()` over the `Parser` functions return values.

Should the plugin not do that or should I open an issue about it instead?

**Comment by Aatch** [comment] 2016-07-28 07:54
The plugin probably shouldn't do that. It is possible to report errors, there's some other code in `interpolate_idents` that does it.

**Comment by lu-zero** [comment] 2016-08-02 09:55
It does that by doing an explicit `emit()` over the error and then triggers a panic, it is still confusing.

**Comment by lu-zero** [comment] 2016-08-10 16:49
Would make sense changing  `MacResult` so it can forward the parsing errors?

**Comment by Mark-Simulacrum** [comment] 2017-05-10 22:06
I think the conclusion here is mainly that this is not really a rust-lang/rust problem; and I can't build the relevant commit today. I also feel like in general `MacResult` will be less used with time as we move towards macros 2.0, so I'm going to close this issue since I can't reproduce.

**Closed by Mark-Simulacrum** 2017-05-10 22:06 UTC
