### ISSUE TITLE
rustc hangs and takes increasing amounts of memory when compiling `json` crate as dependency

### ISSUE THREAD

**Issue by adrian17** [rust-lang/rust#89647] opened 2021-10-07 20:59 UTC
Reproduction:

- use nightly rustc (with wasm target installed)
- clone https://github.com/ruffle-rs/ruffle
- `cd web`
- `cargo build --release --verbose -j1 --target=wasm32-unknown-unknown`

Result: under a minute into the build, the compiler hangs when compiling the `json` dependency, taking increasingly more memory; after 40s it spiked to 1GB, then 2GB and more. The `json` crate is tiny with no dependencies of its own, normally it should take <5s to build.

Weirdly, I cannot reproduce it when building the `json` crate's repo on its own, but I may be missing some build configuration difference.

Reproduced on builds starting with `nightly-2021-09-26` (`rustc 1.57.0-nightly (addb4da68 2021-09-25)`), it works fine on earlier build. Also someone else managed to reproduce this on latest nightly too.

**Comment by saethlin** [comment] 2021-10-08 00:19
This might be the same bug as in https://github.com/rust-lang/rust/issues/89524, I see the same sort of behavior. I need to be compiling `toml` as a dependency, not just a version of `toml` that produces the very long build time. I also see some memory growth initially, but it stops at ~0.5 GB. I think the biggest difference is that in #89524 memory growth eventually stops and LLVM does its best to optimize a tremendous amount of IR.

**Comment by adrian17** [comment] 2021-11-18 16:51
Do you think this set of issues could be considered a NewPM (I'm assuming it's NewPM-related) blocker?
I just verified that this reproduces on GH Actions and kills the build: https://github.com/adrian17/ruffle/runs/4253768752?check_suite_focus=true#step:8:292

**Comment by apiraino** [comment] 2022-01-06 11:33
@adrian17 I'm not 100% sure but I'm thinking if a smaller reproducible would help correlating this to #89524 and  - by extension - to the new LLVM pass manager. Do some of the debugging done in #89524 also apply to this issue?

**Comment by adrian17** [comment] 2022-02-25 09:35
Looks like this regression is now on stable 1.59.
This makes it impossible to build our project locally and on CI, so we'll have to lock version to 1.58 for the time being.

@apiraino sorry, I missed the notification back then; but I didn't investigate this further. (I also don't know how to pass `--debug-pass=Details`)

**Comment by apiraino** [comment] 2022-02-26 15:08
Summarizing here (for SEO purposes) from the linked issues the mitigating flags that make the issue disappear: setting the release build profile `opt-level` != 3 ([mentioned here](https://github.com/rust-lang/rust/issues/91011#issuecomment-974787195))

```diff
 [profile.release]
 panic = "abort"
+opt-level = 0       # or 2
```

or disabling the new LLVM pass manager altogether:

```
$ RUSTFLAGS="-Z new-llvm-pass-manager=no" \
    cargo +nightly build --release --verbose -j1 --target=wasm32-unknown-unknown
```

**Comment by nikic** [comment] 2022-03-10 15:52
This is *supposed* to be fixed by https://github.com/rust-lang/rust/pull/94764, but as mentioned above, I already couldn't reproduce this on nightly before that, so I can't verify whether this specific instance of the problem has been addressed.

If someone still sees hangs with the new pass manager, please let me know.

**Closed by nikic** 2022-03-10 15:52 UTC
Labels: A-LLVM, T-compiler, regression-from-stable-to-stable, C-bug, I-prioritize, I-compiler-nominated
