### ISSUE TITLE
"impl Clone for HashMap" appears twice in API documentation

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#22938] opened 2015-03-01 19:07 UTC
http://doc.rust-lang.org/std/collections/struct.HashMap.html

![screen shot 2015-03-01 at 2 06 43 pm](https://cloud.githubusercontent.com/assets/416575/6432359/39e8c60e-c01c-11e4-842e-595fc4f711ce.png)

**Comment by nagisa** [comment] 2015-03-01 20:28
Dupe of https://github.com/rust-lang/rust/issues/21474

**Closed** 2015-03-01 20:28 UTC
