### ISSUE TITLE
Blanket impls aren't considered disjoint when bounded on traits with disjoint associated types

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#60886] opened 2019-05-16 18:55 UTC
[Playground Example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8e009e18864839ea976c5d15543eb462)

```rust
use std::borrow::ToOwned;

#[derive(Copy, Clone)]
struct S1;
#[derive(Copy, Clone)]
struct S2;
trait T {}

impl<R> T for R where R: ToOwned<Owned = S1> {}

impl<R> T for R where R: ToOwned<Owned = S2> {}
```

**Comment by jonas-schievink** [comment] 2019-05-16 19:33
Duplicate of https://github.com/rust-lang/rust/issues/20400

**Closed by jonas-schievink** 2019-05-16 19:33 UTC
