### ISSUE TITLE
Weird (and possibly wrong) E0308

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#36095] opened 2016-08-29 04:10 UTC
Continuing after issue 36092, I ended up with the following code:
```rust
use std::iter::{Iterator,Peekable};

trait PeekableTrait {
    type Item;
    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator;
}

impl<I: Iterator> PeekableTrait for Peekable<I> {
    type Item = I::Item;
    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator {
        Peekable::peek(&mut self)
    }
}
```

Compiling it fails with:
```
error: main function not found

error[E0308]: mismatched types
  --> <anon>:11:9
   |
11 |         Peekable::peek(&mut self)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::iter::Peekable`, found type parameter
   |
   = note: expected type `std::option::Option<&<std::iter::Peekable<I> as std::iter::Iterator>::Item>`
   = note:    found type `std::option::Option<&<I as std::iter::Iterator>::Item>`

error: aborting due to previous error
```

FWIW, because this was created incrementally, it turns out the type Item is not necessary, and removing it doesn't change anything.

Anyways, talchas on irc figured how to make it compile:

```rust
use std::iter::{Iterator,Peekable};

trait PeekableTrait: Iterator {
    fn peek(&mut self) -> Option<&<Self as Iterator>::Item>;
}

impl<I: Iterator> PeekableTrait for Peekable<I> {
    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> {
        Peekable::peek(&mut self)
    }
}
```

But simply adding redundant `where Self: ITerator` clauses causes the same E0308 error:
```rust
use std::iter::{Iterator,Peekable};

trait PeekableTrait: Iterator {
    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator;
}

impl<I: Iterator> PeekableTrait for Peekable<I> {
    fn peek(&mut self) -> Option<&<Self as Iterator>::Item> where Self: Iterator {
        Peekable::peek(&mut self)
    }
}
```

Relatedly, the message ```expected struct `std::iter::Peekable`, found type parameter``` doesn't make sense to me and I can't reconcile it with the notes that follow it (expected type... found type...)

**Comment by TimNN** [comment] 2016-08-29 06:35
Regarding the ``expected struct `std::iter::Peekable`, found type parameter`` message:

As far as I understand the situation, the real message is basically in the notes:

```
note: expected type `std::option::Option<&<std::iter::Peekable<I> as std::iter::Iterator>::Item>`
note:    found type `std::option::Option<&<I as std::iter::Iterator>::Item>`
```

The ``expected struct `std::iter::Peekable`, found type parameter`` is some kind of summary, focusing only on the actual difference between the expect / found types (in this case `std::option::Option` and `std::iter::Iteratertor`, etc. are ignored since these parts are the same).

**Comment by glandium** [comment] 2016-08-29 08:28
Aaah, so it kind of makes sense now, but the `found type parameter` is not really making things clear. It should however figure that `std::iter::Peekable<I> as std::iter::Iterator>::Item` and `I as std::iter::Iterator>::Item` are, in fact, the same thing.

**Comment by arielb1** [comment] 2016-08-29 17:03
Duplicate of #31760,

**Closed by arielb1** 2016-08-29 17:03 UTC
Labels: A-diagnostics
