### ISSUE TITLE
rustdoc: many methods do not have [src] link (any more?)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#70393] opened 2020-03-25 15:23 UTC
Looking at pages like [this one](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/interpret/struct.Allocation.html), I feel there used to be `[src]` links there to directly view the method source code, but those links are gone now.

I am not sure if this is indeed a regression (I might be misremembering), but in any case having these links would be really useful.

**Comment by ollie27** [comment] 2020-03-25 21:32
Duplicate of #70025

**Closed by ollie27** 2020-03-25 21:32 UTC
Labels: C-bug, T-rustdoc
