### ISSUE TITLE
Rust failing to compile and build on OS X 10.9

### ISSUE THREAD

**Issue by Porkepix** [rust-lang/rust#51455] opened 2018-06-09 13:53 UTC
Rust is supposed to support OS X up to version 10.7.

While it was possible to compile it on 10.9 until version 1.24.1, versions 1.25 and later would not compile anymore using Homebrew formula.

Here are errors:

```
==> Upgrading rust
==> Downloading https://static.rust-lang.org/dist/rustc-1.26.2-src.tar.gz
###################################################################################################################################### 100.0%
==> ./configure --prefix=/usr/local/Cellar/rust/1.26.2 --release-channel=stable
==> make
Last 15 lines from /Users/clement/Library/Logs/Homebrew/rust/02.make:

Internal error occurred: Command "clang" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=x86_64-apple-darwin" "-stdlib=libc++" "--target=x86_64-apple-darwin" "-fno-builtin" "-fvisibility=hidden" "-ffreestanding" "-fomit-frame-pointer" "-DVISIBILITY_HIDDEN" "-o" "/private/tmp/rust-20180609-84611-1invj3x/rustc-1.26.2-src/build/x86_64-apple-darwin/stage0-std/x86_64-apple-darwin/release/build/compiler_builtins-8bee530f001b77a3/out/../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatundidf.o" "-c" "../../libcompiler_builtins/compiler-rt/lib/builtins/x86_64/floatundidf.S" with args "clang" did not execute successfully (status code exit code: 1).

', /private/tmp/rust-20180609-84611-1invj3x/rustc-1.26.2-src/.brew_home/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.9/src/lib.rs:2070:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/private/tmp/rust-20180609-84611-1invj3x/rustc-1.26.2-src/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/private/tmp/rust-20180609-84611-1invj3x/rustc-1.26.2-src/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1064:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /private/tmp/rust-20180609-84611-1invj3x/rustc-1.26.2-src/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 0:14:08
make: *** [all] Error 1
```
This output in when trying to install through Homebrew.
Even if I used `RUST_BACKTRACE=1` on the line, it didn't seem to change the output probably because ran through Homebrew.

In case it would provide more informations, I also ran by hand the build from 1.26.2 sources, here's the output:
```
mbp :: /tmp/rust-1.26.2 » RUST_BACKTRACE=1 ./x.py build
downloading https://static.rust-lang.org/dist/2018-03-29/rust-std-1.25.0-x86_64-apple-darwin.tar.gz
######################################################################## 100,0%
extracting /private/tmp/rust-1.26.2/build/cache/2018-03-29/rust-std-1.25.0-x86_64-apple-darwin.tar.gz
downloading https://static.rust-lang.org/dist/2018-03-29/rustc-1.25.0-x86_64-apple-darwin.tar.gz
######################################################################## 100,0%
extracting /private/tmp/rust-1.26.2/build/cache/2018-03-29/rustc-1.25.0-x86_64-apple-darwin.tar.gz
downloading https://static.rust-lang.org/dist/2018-03-29/cargo-0.26.0-x86_64-apple-darwin.tar.gz
######################################################################## 100,0%
extracting /private/tmp/rust-1.26.2/build/cache/2018-03-29/cargo-0.26.0-x86_64-apple-darwin.tar.gz
error: failed to read `/private/tmp/rust-1.26.2/src/tools/clippy/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
failed to run: /private/tmp/rust-1.26.2/build/x86_64-apple-darwin/stage0/bin/cargo build --manifest-path /private/tmp/rust-1.26.2/src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:04:13
```
It's also failing, even if I'm not sure the issue is quite the same.

**Comment by follower** [comment] 2018-11-21 06:32
FWIW, if anyone finds encounters this issue themselves and just wants to get Rust installed the packaged installer at https://static.rust-lang.org/dist/rust-1.30.1-x86_64-apple-darwin.pkg (via https://www.rust-lang.org/en-US/other-installers.html) installed and ran okay on a OS X 10.9 machine.

May also be relevant for #50776.

**Comment by Porkepix** [comment] 2018-11-21 15:29
Would still make fail the dependencies resolutions for Homebrew's package depending on Rust though.

**Comment by follower** [comment] 2020-04-22 20:35
Update: FWIW can confirm https://static.rust-lang.org/dist/rust-1.42.0-x86_64-apple-darwin.pkg (via <https://www.rust-lang.org/en-US/other-installers.html>) installed and seems to run okay on a Mac OS X 10.9 machine.

**Comment by sanxiyn** [comment] 2022-01-19 06:33
Closing, presuming to be a duplicate of #50776.

**Closed by sanxiyn** 2022-01-19 06:33 UTC
Labels: O-macos, T-compiler, A-rustbuild, C-bug, T-release
