### ISSUE TITLE
ICE when installing cargo-spellcheck

### ISSUE THREAD

**Issue by KiChjang** [rust-lang/rust#88309] opened 2021-08-24 21:30 UTC
### Code

No code requried, but just the following command:

```bash
cargo +nightly install cargo-spellcheck
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (af140757b 2021-08-22)
binary: rustc
commit-hash: af140757b4cb1a60d107c690720311ba8e06e7de
commit-date: 2021-08-22
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 13.0.0
```

### Error output

```
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:1098 ~ cargo_spellcheck[8d20]::documentation::literal::detect_comment_variant), const_param_did: None }) (end of phase Optimization) at bb147[0]:
use of local _242, which has no storage here
   --> /home/keith/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-spellcheck-0.8.13/src/documentation/literal.rs:301:13
    |
301 |             };
    |             ^
    |
    = note: delayed at compiler/rustc_mir/src/transform/validate.rs:121:36

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1134:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (af140757b 2021-08-22) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: failed to compile `cargo-spellcheck v0.8.13`, intermediate artifacts can be found at `/tmp/cargo-installSnpLJG`

Caused by:
  could not compile `cargo-spellcheck`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af140757b4cb1a60d107c690720311ba8e06e7de/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/af140757b4cb1a60d107c690720311ba8e06e7de/library/std/src/panicking.rs:460:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-08-24 22:02
Presumably a duplicate of https://github.com/rust-lang/rust/issues/88307

**Closed by jonas-schievink** 2021-08-24 22:02 UTC
Labels: I-ICE, T-compiler, C-bug
