### ISSUE TITLE
rustdoc intra-rustdoc-linking appears erratic

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#53917] opened 2018-09-03 05:18 UTC
I'm running with `rustdoc 1.30.0-nightly (33b923fd4 2018-08-18)`.

At [this line](https://github.com/Ekleog/erlust/blob/master/erlust/src/theater.rs#L27), `TheaterBox` is not turned into a link. However, by its definition at [this line of the same file](https://github.com/Ekleog/erlust/blob/master/erlust/src/theater.rs#L83), I think it should be considered in scope, if my understanding of [rfc1946](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md) is correct.

On the other hand, at [this line](https://github.com/Ekleog/erlust/blob/master/erlust/src/theater.rs#L45), `Message` is indeed turned into a link, which is logical as it is imported from [here](https://github.com/Ekleog/erlust/blob/master/erlust/src/theater.rs#L6).

When I try to append:
```rust
/// [`TheaterBox`]: super::TheaterBox
```
to the first example, rustdoc starts complaining that `super::TheaterBox` is not found in this scope.

So… I don't understand how rustdoc does the linking. Maybe this is all correct, but if so I don't understand how :)

**Comment by GuillaumeGomez** [comment] 2018-09-03 19:11
The whole being: it's still under heavy development. But thanks for opening the issue, it'll help us improving it!

**Comment by jyn514** [comment] 2020-08-19 21:26
I tried reproducing the error, but `erlust` does not compile on master. I'm going to close this since intra-doc links were in a very different state when it was opened, but feel free to re-open if you're still having issues.

<details><summary>Compile errors</summary>

```
    Checking miniz_oxide v0.4.0
error[E0053]: method `poll` has an incompatible type for trait
  --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:64:5
   |
64 |     fn poll(self: Pin<&mut Self>, waker: &Waker) -> Poll<T> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
   |
   = note: expected fn pointer `fn(std::pin::Pin<&mut future::future_obj::LocalFutureObj<'a, T>>, &mut std::task::Context<'_>) -> std::task::Poll<_>`
              found fn pointer `fn(std::pin::Pin<&mut future::future_obj::LocalFutureObj<'a, T>>, &std::task::Waker) -> std::task::Poll<_>`

error[E0053]: method `poll` has an incompatible type for trait
   --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:114:5
    |
114 |     fn poll(self: Pin<&mut Self>, waker: &Waker) -> Poll<T> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
    |
    = note: expected fn pointer `fn(std::pin::Pin<&mut future::future_obj::FutureObj<'a, T>>, &mut std::task::Context<'_>) -> std::task::Poll<_>`
               found fn pointer `fn(std::pin::Pin<&mut future::future_obj::FutureObj<'a, T>>, &std::task::Waker) -> std::task::Poll<_>`

error[E0308]: mismatched types
  --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/mod.rs:86:19
   |
86 |         self.poll(waker)
   |                   ^^^^^ types differ in mutability
   |
   = note: expected mutable reference `&mut std::task::Context<'_>`
                      found reference `&std::task::Waker`

error[E0308]: mismatched types
   --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:118:44
    |
118 |         LocalFutureObj::poll(pinned_field, waker)
    |                                            ^^^^^ types differ in mutability
    |
    = note: expected mutable reference `&mut std::task::Context<'_>`
                       found reference `&std::task::Waker`

error[E0308]: mismatched types
   --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:165:20
    |
165 |         F::poll(p, waker)
    |                    ^^^^^ types differ in mutability
    |
    = note: expected mutable reference `&mut std::task::Context<'_>`
                       found reference `&std::task::Waker`

error[E0308]: mismatched types
   --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:182:25
    |
182 |         F::poll(future, waker)
    |                         ^^^^^ types differ in mutability
    |
    = note: expected mutable reference `&mut std::task::Context<'_>`
                       found reference `&std::task::Waker`

error[E0308]: mismatched types
   --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:203:26
    |
203 |             F::poll(pin, waker)
    |                          ^^^^^ types differ in mutability
    |
    = note: expected mutable reference `&mut std::task::Context<'_>`
                       found reference `&std::task::Waker`

error[E0308]: mismatched types
   --> /home/joshua/.local/lib/cargo/git/checkouts/futures-rs-4ca77cb4f4f05ac4/c949076/futures-core/src/future/future_obj.rs:225:26
    |
225 |             F::poll(pin, waker)
    |                          ^^^^^ types differ in mutability
    |
    = note: expected mutable reference `&mut std::task::Context<'_>`
                       found reference `&std::task::Waker`

error: aborting due to 8 previous errors
```

</details>

**Closed by jyn514** 2020-08-19 21:26 UTC
Labels: A-intra-doc-links, T-rustdoc
