### ISSUE TITLE
Take_while removes extra char from std::str::Chars

### ISSUE THREAD

**Issue by naomijub** [rust-lang/rust#76184] opened 2020-08-31 23:51 UTC
I tried this code:

```rust
fn main() {
    let mut a = ":hello-b true)".chars();
    let next = a.next();
    let chars = ble(&mut a);
    
    println!("{:?}", a);
    println!("{:?}", next);
    println!("{:?}", chars);
   
}  

fn ble(chars: &mut std::str::Chars) -> String {
    chars.take_while(|c| !c.is_whitespace() && c != &')')
        .collect::<String>()
}
```

I expected to see this the following output:
```
Chars([' ', 't', 'r', 'u', 'e', ')'])
Some(':')
"hello-b"
```
`take_while` should stop at `' '` and it should be included in `Chars([])`.

Instead, this happened: 
```
Chars(['t', 'r', 'u', 'e', ')'])
Some(':')
"hello-b"
```
Chars doesn't have `' '`

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-apple-darwin
release: 1.45.0
LLVM version: 10.0
```

**Comment by jonas-schievink** [comment] 2020-08-31 23:59
The `' '` was consumed by `take_while`. It has to do this because it has no way to put an element back into the iterator when the closure returns `false` for the element. Closing as expected behavior (but if you think the `take_while` documentation can be improved to clarify this, feel free to send a PR).

**Closed by jonas-schievink** 2020-08-31 23:59 UTC
Labels: C-bug

**Comment by naomijub** [comment] 2020-09-01 02:22
Now that you have said it makes sense. Can't we just use .peekable().peek() to prevent taking elements like what happen here?

**Comment by jonas-schievink** [comment] 2020-09-01 10:29
That might work for your use case, but using that in `take_while` might incur additional overhead that not all users need to pay.
