### ISSUE TITLE
Multiple Higher Kinded Trait Bounds bug

### ISSUE THREAD

**Issue by hikitrbogithub** [rust-lang/rust#57750] opened 2019-01-19 03:32 UTC
```rust
use std::fmt::Debug;

//consume x
fn consume_print_return<T>(x: T) -> T
where
// how do I express that these ---*
//                                |
//  *-----------------------------*
//  |
//  *------------------v
/*  | */     for<'a> &'a T: IntoIterator,
//  *-------------------v
/*  | */     for<'a> <&'a T as IntoIterator>::Item: Debug,
//  |
{/* | */
//  *--- lifetimes are equal to the lifetime of this borrow?
//  |
//  *-----------v
    for item in &x {
        println!("{:?}", item);
    }

    //return x
    x
}

fn main() {
    consume_print_return(vec![1, 2]);
}
```
Gives the following error
error[E0277]: `<&'a _ as std::iter::IntoIterator>::Item` doesn't implement `std::fmt::Debug`

**Comment by sfackler** [comment] 2019-01-19 05:44
Duplicate of #56556

**Closed by sfackler** 2019-01-19 05:44 UTC
