### ISSUE TITLE
Segmentation fault on nightly and beta when running with --release

### ISSUE THREAD

**Issue by joe-hauns** [rust-lang/rust#49010] opened 2018-03-14 09:49 UTC
I encountered  a segmentation fault when running a program on nightly or beta in release mode. 
The segfault occurs somewhere in [another crate](https://github.com/tokio-rs/tokio-timer/issues/39) but within safe code and only if `--release` is passed to cargo. 
I created a crate which is minimal setup to encounter this error:
https://github.com/joeschman/tokio-timer-segfault
A more detailed description can be found in the readme.

**Comment by termhn** [comment] 2018-03-16 04:39
I am also experiencing this in https://github.com/termhn/nano-rs on `nightly-x86_64-pc-windows-msvc` however not when running on my Mac also on nightly.

**Comment by termhn** [comment] 2018-03-16 05:29
This fixes it https://github.com/tokio-rs/tokio-timer/pull/40 ... not sure what that means or if it is helpful (some optimization to do with continue breaking things maybe?)

**Comment by michaelwoerister** [comment] 2018-03-16 10:32
cc @rust-lang/compiler

**Comment by nikomatsakis** [comment] 2018-03-16 16:44
Do we know if this is a regression? Can one of you try to reproduce on older nightly builds and see if you can find some point that worked?

**Comment by nikomatsakis** [comment] 2018-03-16 16:44
My *guess* would be that it is some kind of optimization gone wrong in LLVM, but whether that's LLVM's fault or ours is sort of unclear.

**Comment by joeschman** [comment] 2018-03-19 08:18
> Can one of you try to reproduce on older nightly builds and see if you can find some point that worked?

I'd test that but pittily I could not find out how to revert to older nightly/beta versions using rustup :/

**Comment by oli-obk** [comment] 2018-03-19 08:28
You can use `rustup override set nightly-2018-01-15` to set to e.g. 15th January.

**Comment by joeschman** [comment] 2018-03-19 12:58
I checked older nightly versions and the segfault appears first when using `nightly-2018-02-11-x86_64-apple-darwin`.

**Comment by nikomatsakis** [comment] 2018-03-19 20:40
@joeschman Thanks! Btw, jfyi there is a new shiny tool by @Mark-Simulacrum that can do the bisection for you:

https://github.com/rust-lang-nursery/cargo-bisect-rustc

It will even find the problem down to the PR level if it arose in the last 90 days.

In any case, these are the diffs between those two nightlies, if I'm not mistaken:

https://github.com/rust-lang/rust/compare/3bcda48a3...45fba43b3

**Comment by nikomatsakis** [comment] 2018-03-19 20:40
One thing jumps out at me:

https://github.com/rust-lang/rust/commit/6b7b6b63a928479a29d9fc1282e553e409c66934

Upgrade to LLVM 6 =)

**Comment by termhn** [comment] 2018-03-19 20:59
Indeed. Definitely seems like the kind of bug a new LLVM version could introduce.

**Comment by nikomatsakis** [comment] 2018-03-20 16:07
cc @rust-lang/compiler -- anybody want to try to track down a potential LLVM bug introduced by LLVM 6 transition? 

@nagisa seems like your speciality :)

**Comment by nagisa** [comment] 2018-03-20 20:36
Okay, I’ll try to take a look at this tomorrow.

**Comment by nagisa** [comment] 2018-03-21 18:20
Ugh, I cannot reproduce the fault on Linux, so it is very hard for me to even start investigating this more seriously.

The supposed error location is within a huge inlined 1.5k line blob of IR and the function with and without the fix at https://github.com/tokio-rs/tokio-timer/pull/40 appears to be optimised down into identical code, at least for that specific function.

**Comment by termhn** [comment] 2018-03-21 18:24
Anything I could provide from the windows side that would help with this—artifacts from building etc? I’m not super knowledgeable about everything that happens but willing to help if I can :)

**Comment by nagisa** [comment] 2018-03-21 18:33
Can you see if the issue is reproducible on windows with the minimal sample provided in the first comment?

**Comment by joeschman** [comment] 2018-03-22 08:25
If there‘s any more information i can provide for the problem ln macos, just tell me what ;)

**Comment by nagisa** [comment] 2018-03-22 09:08
Wrote this comment yesterday but forgot to hit submit.

---

So here’s the thing that sticks out as a sore thumb to me in the optimised IR as far as differences between the "bad" and "fixed" versions goes:

```llvm
  %min.0.ph32.i.i.i = phi i64* [ null, %bb8.lr.ph.i.lr.ph.lr.ph.i.i.i ], [ %.lcssa23.i164.pre-phi.i.pre-phi.i.pre-phi, %bb11.i165.i.i ]
  ; ...
  %328 = icmp ne i64* %min.0.ph32.i.i.i, null
  ; a while later
  call void @llvm.assume(i1 %328) #13, !noalias !213
```

I still haven’t checked the IR closely enough to confirm whether the CFG allows for this assume to ever called on falsy value, but this is really the only notable difference between the fixed and non-fixed version anyway.

Surprisingly, this `%328` is never ever used again.

**Comment by nagisa** [comment] 2018-03-22 09:14
Things that would be helpful and make it easier to debug this:

1. A single-file minimal reproducer with as few dependencies on system utilities (such as threads) as possible;
2. Backtrace from a debugger, register dump at the time of the fault and disassembly of the function.

A minimal reproducer that works on windows would be better as I have an access to a windows VM, though perhaps it is as good a time as ever to figure out how to make a mac VM… hmm.

**Comment by nikomatsakis** [comment] 2018-03-22 14:40
triage: P-high

**Comment by nikomatsakis** [comment] 2018-03-22 14:44
Assigning to @pnkfelix to try and reproduce on mac

**Comment by joeschman** [comment] 2018-03-23 10:56
I now minimized the example. All the code is now in the repository without dependencies to crates that are outside the repository. Pittily a one-file reproducer was not possible. It seems that the bug only occurs when the code is called from another crate. I minimized the size of that crate to 20 lines of code. When the same code is run from an internal module, no segfault occurs.
Both (calling the module & the crate function) is included in the last commit of the crate i linked above.

Furthermore I found out that with yesterday's nightly build ( `nightly-2018-03-21-x86_64-apple-darwin`) the segfault does not occur anymore. I get the segfaut with `nightly-2018-02-11-x86_64-apple-darwin` to`nightly-2018-02-15-x86_64-apple-darwin`. (Didn't test it with `*-03-16-*` to `*-03-20-*` ).

   > Backtrace from a debugger, register dump at the time of the fault and disassembly of the function.

Any recommendations for a debugger for rust on a mac? I have hardly any experience with using debuggers at all.

**Comment by termhn** [comment] 2018-03-24 01:05
Alright so I was testing on my Windows machine and confirmed the same behavior as @joeschman has on mac. I also pinpointed that it is *fixed* in `nightly-2018-03-03` and later, but broken in `nightly-2018-03-02` and earlier.

**Comment by pnkfelix** [comment] 2018-03-26 11:10
I have reproduced the problem on my mac, using the [joeschman/tokio-timer-segfault](https://github.com/joeschman/tokio-timer-segfault) repo and the `nightly-2018-03-02` rustc. I'll report more as I dissect further.

**Comment by pnkfelix** [comment] 2018-03-26 11:17
Here is a gist https://gist.github.com/pnkfelix/fdab1b374d49e8850073a357d4f492f4 with the things that @nagisa had asked for (a stack backtrace, dump of the register file, and a disassembly of the function).

**Comment by pnkfelix** [comment] 2018-03-26 11:38
@joeschman by the way, the way I got the info in the above gist is I just ran the binary under `lldb`, like so:

```
% lldb target/release/tokio-timer-segfault
```
 and then when I got the debugger prompt (`(lldb)`), I ran the program with `r`:

```
(lldb) r
```

and then after the program exception occurred, I used the following commands (included in the gist output above) `bt`, `register read`, and `dis`.

`lldb` has an online help mechanism you can use to explore its set of commands; or you can google for cheat sheets online.

**Comment by pnkfelix** [comment] 2018-03-26 15:14
@nagisa pointed out that I was using an old head of the source repo.

I updated and re-ran the same `lldb` commands, and updated the gist (which I'll relink for convenience: https://gist.github.com/pnkfelix/fdab1b374d49e8850073a357d4f492f4 )

**Comment by pnkfelix** [comment] 2018-03-26 15:45
Experimentation and Discussion with @nagisa  and  @alexcrichton has led us to the hypothesis that this is a bug injected by thinlto, which is on by default for `--release` builds ...

**Comment by nikomatsakis** [comment] 2018-04-05 14:12
commit range from nightly-2018-03-02 to nightly-2018-03-03 is 3eeb5a665 .. 9cb18a92a

**Comment by nikomatsakis** [comment] 2018-04-12 14:17
I doubt these are the culprits, but skimming the commit log shows @alexcrichton's ["rustc: Tweak funclet cleanups of ffi functions"](https://github.com/rust-lang/rust/pull/48653/commits/804666f4ad5a66e6a1bae3b2e326efa030135a05), which seems ... at least in the neighborhood.

**Comment by pnkfelix** [comment] 2018-04-20 10:36
We may need to appoint someone to be the official "LTO debugging" expert based on the number of bugs we currently have that have sort of stalled at the point of determining "oh, this appears to be injected by [Thin]LTO."

**Comment by nikomatsakis** [comment] 2018-05-03 14:46
triage: P-medium

Next steps are to diagnose the LLVM problem. Filing under https://github.com/rust-lang/rust/issues/50422.

**Comment by steveklabnik** [comment] 2019-09-22 15:00
Triage: looks like the energy to reproduce this one kinda petered out. Can anyone reproduce this today?

**Comment by Aaron1011** [comment] 2020-10-02 22:53
This no longer segfaults with the latest nightly (`2020-10-02`) under macos. I ran `cargo-bisect-rust`, and managed to narrow the the range of commits where the segfault was fixed:

```
searched toolchains nightly-2018-03-02 through nightly-2020-10-02


********************************************************************************
Regression in nightly-2019-07-27
********************************************************************************

fetching https://static.rust-lang.org/dist/2019-07-26/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2019-07-26: 40 B / 40 B [==================================================================================================================] 100.00 % 228.10 KB/s converted 2019-07-26 to 890881f8f4c77e8670d4b32104c0325fcfefc90f
fetching https://static.rust-lang.org/dist/2019-07-27/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2019-07-27: 40 B / 40 B [==================================================================================================================] 100.00 % 146.96 KB/s converted 2019-07-27 to c43753f910aae000f8bcb0a502407ea332afc74b
looking for regression commit between 2019-07-26 and 2019-07-27
cloning rust repository
fetching (via local git) commits from 890881f8f4c77e8670d4b32104c0325fcfefc90f to c43753f910aae000f8bcb0a502407ea332afc74b
opening existing repository at "rust.git"
refreshing repository
looking up first commit
looking up second commit
checking that commits are by bors and thus have ci artifacts...
finding bors merge commits
found 5 bors merge commits in the specified range
  commit[0] 2019-07-25UTC: Auto merge of #60340 - mgeier:cap-vs-capacity, r=alexcrichton
  commit[1] 2019-07-25UTC: Auto merge of #62990 - Centril:rollup-k9n0hvs, r=Centril
  commit[2] 2019-07-26UTC: Auto merge of #60260 - videolabs:rust_uwp2, r=alexcrichton
  commit[3] 2019-07-26UTC: Auto merge of #62914 - ehuss:update-cargo, r=alexcrichton
  commit[4] 2019-07-26UTC: Auto merge of #63015 - Centril:rollup-ydhpcas, r=Centril
ERROR: no commits between 890881f8f4c77e8670d4b32104c0325fcfefc90f and c43753f910aae000f8bcb0a502407ea332afc74b within last 167 days
```

Unfortunately, none of these PRs looks obviously related. To make matters worse, the two rollups contain 15 and 22 (!) PRs respectively, which will make bisecting this further very time-consuming.

**Comment by steveklabnik** [comment] 2020-10-05 14:24
One year later, with no reproduction instructions, I'm going to give this one a close. If anyone can make a reproduction, please let me know and we can re-open, thanks!

**Closed by steveklabnik** 2020-10-05 14:24 UTC
Labels: A-LLVM, C-bug, I-unsound 💥, P-medium, T-compiler, regression-from-stable-to-stable
