### ISSUE TITLE
rustdoc hangs indefinitely on /// <b

### ISSUE THREAD

**Issue by sjackman** [rust-lang/rust#71658] opened 2020-04-29 00:33 UTC
I tried this code `foo.rs` and ran `rustdoc foo.rs`:

```rust
/// <b
pub fn foo() {}
```

I expected to see this happen: `rustdoc foo.rs` to complete.

Instead, this happened: `rustdoc foo.rs` hung indefinitely.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-apple-darwin
release: 1.43.0
LLVM version: 9.0
```

**Comment by ehuss** [comment] 2020-04-29 01:58
Closing as a duplicate of #70871.  I believe it is waiting for an upstream release of pulldown-cmark.

**Closed by ehuss** 2020-04-29 01:58 UTC
Labels: C-bug
