### ISSUE TITLE
ICE: thread 'rustc' panicked at 'unsized_part_of_type failed even though ty is unsized'

### ISSUE THREAD

**Issue by bitvoid** [rust-lang/rust#23370] opened 2015-03-14 20:27 UTC
I just got an ICE while working on a testcase for another issue.

``` rust
enum SomeEnum {
    Something(i8),
    SomethingElse([u8])
}

fn some_function(arg: &SomeEnum) -> () {
    ()
}

fn main() {
    some_function(&SomeEnum::Something(1));
}
```

```
<anon>:3:5: 3:24 warning: variant is never used: `SomethingElse`, #[warn(dead_code)] on by default
<anon>:3     SomethingElse([u8])
             ^~~~~~~~~~~~~~~~~~~
<anon>:6:18: 6:21 warning: unused variable: `arg`, #[warn(unused_variables)] on by default
<anon>:6 fn some_function(arg: &SomeEnum) -> () {
                          ^~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'unsized_part_of_type failed even though ty is unsized', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/trans/common.rs:168


playpen: application terminated with error code 101
```

http://is.gd/qkbk29

**Comment by frewsxcv** [comment] 2015-08-20 02:43
Visiting for triage: this is still an issue

**Comment by apasel422** [comment] 2015-10-24 22:16
I think this is a duplicate of #16812.

**Closed** 2015-10-24 22:32 UTC
Labels: I-ICE
