### ISSUE TITLE
`impl<S> Trait<Struct> for S {}` blanket impl shows up multiple times in docs for `Struct`

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#81483] opened 2021-01-28 18:20 UTC
I tried documenting this code with `cargo doc`:

```rust
pub struct Struct;

pub trait Trait<T> {}

impl<S> Trait<Struct> for S {}
```

I expected to see this happen: The `impl<S> Trait<Struct> for S {}` blanket impl appears only once in the docs for `Struct`

Instead, this happened: The blanket impl appears 23 times.
<details><summary>Picture of the blanket impls in the docs for `Struct`</summary>
<img src="https://user-images.githubusercontent.com/18036327/106181330-3d774e00-617c-11eb-85f4-03fa77a4421a.png"/>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (a2f8f6281 2021-01-27)
binary: rustc
commit-hash: a2f8f6281817d430e20726128b739d3c6708561c
commit-date: 2021-01-27
```

**Comment by fmease** [comment] 2024-01-23 22:22
No longer reproducible on stable or nightly. Likely same root cause as #96036. Probably fixed by #96091. Closing as completed.

**Closed by fmease** 2024-01-23 22:22 UTC
Labels: T-rustdoc, C-bug, A-synthetic-impls, A-rustdoc-ui
