### ISSUE TITLE
ICE in `cargo test` with CARGO_INCREMENTAL=1 on Cargo

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#39585] opened 2017-02-06 16:45 UTC
I've checked out Cargo at rust-lang/cargo@4ce099bf4c0abd73e01695a4dee71d8fa62806a9 and from a clean build directory I get:

```
$ CARGO_INCREMENTAL=1 cargo +nightly test
...
   Compiling cargo v0.18.0 (file:///home/alex/code/cargo)
   Compiling cargotest v0.1.0 (file:///home/alex/code/cargo/tests/cargotest)
error: failed to remove /home/alex/code/cargo/target/debug/deps/metadata-2a6cfcba5e51f525.metadata.o: No such file or directory (os error 2)

warning: Error finalizing incremental compilation session directory `/home/alex/code/cargo/target/debug/incremental/metadata-2kp13d1pc45a0/s-emvufj4cj6-1f76yqu-working`: No such file or directory (os error 2)

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at '/buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:450: Trying to invalidate IncrCompSession `InvalidBecauseOfErrors { session_directory: "/home/alex/code/cargo/target/debug/incremental/metadata-2kp13d1pc45a0/s-emvufj4cj6-1f76yqu-working" }`', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:782
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `cargo`.
Build failed, waiting for other jobs to finish...
error: build failed
```

The compiler in use is the current latest nightly, specifically:

```
$ rustc +nightly -vV
rustc 1.17.0-nightly (ea7a6486a 2017-02-04)
binary: rustc
commit-hash: ea7a6486a26af085862cd7a5596bb69e83d85e12
commit-date: 2017-02-04
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9

```

**Comment by alexcrichton** [comment] 2017-02-06 16:46
cc @michaelwoerister

**Comment by michaelwoerister** [comment] 2017-02-06 17:27
Thanks for the report!

**Comment by Marwes** [comment] 2017-02-07 10:14
Possible duplicate of #39508 ? Same error and it seems like both fail on testing a file called `tests/metadata.rs`

**Closed** 2017-02-10 00:41 UTC
Labels: A-incr-comp, I-ICE
