### ISSUE TITLE
cargo doc --all does not document proc macro crates if target is explicitly specified

### ISSUE THREAD

**Issue by leo60228** [rust-lang/rust#62940] opened 2019-07-24 15:50 UTC
If a target is explicitly specified on the command line, even if it is the same target as the host, then proc macro crates will not be documented by `cargo doc --all`. When a cargo configuration file is used to set a default target for cross-compliation, this can prevent documenting proc macro crates at all.

Minimal testcase: https://github.com/leo60228/minimal_testcase

```
[leo60228@leotop2:~/minimal_testcase]$ rustc --version --verbose
rustc 1.38.0-nightly (273f42b59 2019-07-21)
binary: rustc
commit-hash: 273f42b5964c29dda2c5a349dd4655529767b07f
commit-date: 2019-07-21
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 9.0
```

**Comment by jyn514** [comment] 2020-08-25 16:11
Possible duplicate of https://github.com/rust-lang/cargo/issues/7677

**Comment by ehuss** [comment] 2020-09-02 19:58
Yea, I'm going to close as I think this is mostly a cargo issue.

**Closed by ehuss** 2020-09-02 19:58 UTC
Labels: A-cross, A-macros, C-bug, T-rustdoc
