### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37

### ISSUE THREAD

**Issue by staktrace** [rust-lang/rust#70353] opened 2020-03-24 12:04 UTC
### Code

```
git clone https://github.com/docopt/docopt.rs
cd docopt.rs
git reset --hard 1.1.0
cargo build --release --verbose
```

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `docopt`.

Caused by:
  process didn't exit successfully: `rustc --crate-name docopt_wordlist --edition=2018 src/wordlist.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=29b01667b3ffabde -C extra-filename=-29b01667b3ffabde --out-dir /home/ubuntu/docopt.rs/target/release/deps -L dependency=/home/ubuntu/docopt.rs/target/release/deps --extern docopt=/home/ubuntu/docopt.rs/target/release/deps/libdocopt-2fe2a3326b9dd8cc.rlib --extern lazy_static=/home/ubuntu/docopt.rs/target/release/deps/liblazy_static-998e5d1115c8a9cd.rlib --extern regex=/home/ubuntu/docopt.rs/target/release/deps/libregex-b98fc02de35a0584.rlib --extern serde=/home/ubuntu/docopt.rs/target/release/deps/libserde-142eefc639cfe4cb.rlib --extern strsim=/home/ubuntu/docopt.rs/target/release/deps/libstrsim-81d38e34be74e3cb.rlib` (exit code: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::panicking::panic
             at src/libcore/panicking.rs:54
  15: core::ops::function::FnOnce::call_once
  16: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::hir_owner>::compute
  17: rustc::dep_graph::graph::DepGraph::with_task_impl
  18: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  19: rustc::hir::map::Map::get_entry
  20: rustc::hir::map::Map::find
  21: rustc_passes::dead::MarkSymbolVisitor::check_def_id
  22: rustc_hir::intravisit::walk_item
  23: rustc_passes::dead::check_crate
  24: rustc_session::utils::<impl rustc_session::session::Session>::time
  25: rustc_interface::passes::analysis::{{closure}}::{{closure}}
  26: rustc_session::utils::<impl rustc_session::session::Session>::time
  27: rustc_interface::passes::analysis
  28: rustc::ty::query::__query_compute::analysis
  29: rustc::dep_graph::graph::DepGraph::with_task_impl
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  31: rustc::ty::context::tls::enter_global
  32: rustc_interface::interface::run_compiler_in_existing_thread_pool
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-03-24 12:06
duplicate of https://github.com/rust-lang/rust/issues/70041

**Closed by jonas-schievink** 2020-03-24 12:06 UTC
Labels: C-bug, I-ICE, T-compiler

**Comment by staktrace** [comment] 2020-03-24 12:11
Thanks. @jonas-schievink Tangential, but do you happen to know if there's an issue tracking the missing components in latest nightlies? i.e. when I do `rustup update nightly` it has to go back to the 2020-03-18 version before it finds one which has all the necessary components (more recent ones are missing things like `rustfmt-preview` and `clippy-preview`).

**Comment by jonas-schievink** [comment] 2020-03-24 12:43
issues for that get opened automatically, eg. https://github.com/rust-lang/rust/issues/70280

**Comment by staktrace** [comment] 2020-03-24 12:52
Thanks!
