### ISSUE TITLE
"help: possible candidate is found in another module" points to incorrect Span

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#44514] opened 2017-09-12 01:00 UTC
Consider the following error:

```rust
error[E0412]: cannot find type `Formatter` in this scope
  --> src/main.rs:17:27
   |
17 |     fn fmt(&self, f: &mut Formatter) -> fmt::Result {
   |                           ^^^^^^^^^ not found in this scope
   |
help: possible candidate is found in another module, you can import it into scope
   |
11 | #[derive(use std::fmt::Formatter;
   |
```

This should be:

```diff
help: possible candidate is found in another module, you can import it into scope
   |
- 11 | #[derive(use std::fmt::Formatter;
   |

help: possible candidate is found in another module, you can import it into scope
   |
+ 11 | use std::fmt::Formatter;
   |
```

The `#[derive(` bit should not be there.

This issue has been occurring for at least the last ~7 nightlies.

**Comment by zackmdavis** [comment] 2017-09-12 02:16
Duplicate of #44210?

**Comment by SergioBenitez** [comment] 2017-09-12 02:20
Looks like it! I'll close this out.

**Closed** 2017-09-12 02:20 UTC
