### ISSUE TITLE
It should be possible to use uninitialized memory in statics

### ISSUE THREAD

**Issue by robsmith11** [rust-lang/rust#57445] opened 2019-01-08 15:39 UTC
In the past, I've found it useful to "initialize" statics using uninitialized memory and then do the actual initialization (requiring non-const fns) at the beginning of my `main()`.

In recent nightlies, this strategy seems to be longer possible.  Is there an alternative or could this be allowed again?  I'm already using an `unsafe` block, so it shouldn't be a problem to risk UB.

Example:
```
#![feature(const_transmute)]
#![feature(const_fn)]
#![feature(maybe_uninit)]
#![feature(type_ascription)]

use std::collections::BTreeMap;
use std::mem::{MaybeUninit,transmute};

static mut STATE:State = State::uninit();

#[derive(Default)]
struct State {
    x:BTreeMap<u64,f64>,
    y:f64,
}

impl State {
    const fn uninit() -> Self {
        unsafe { transmute(MaybeUninit::uninitialized():MaybeUninit<State>) }
    }
}

fn main() {
    unsafe { STATE = State::default(); }
}
```

```
error[E0080]: it is undefined behavior to use this value --> src/main.rs:9:1
| 9 | static mut STATE:State = State::uninit();
 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered uninitialized bytes at .x.root.node, but expected something in the range 1..=18446744073709551615 
| = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rust compiler repository if you believe it should not be considered undefined behavior error: aborting due to previous error
```

**Comment by jonas-schievink** [comment] 2019-01-08 16:37
Wouldn't the assignment try to run drop glue for the old value?

**Comment by nagisa** [comment] 2019-01-08 16:53
Right, the `State` struct is not `Copy`, so assigning to `STATE` like is done in `main` is definitely UB. However there are ways about that specifically (e.g. using `std::ptr::write`).

The correct and working approach is to [lift the `MaybeUninit` into the static](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=d43612d3f218ed717db5982758eca718).

**Comment by robsmith11** [comment] 2019-01-08 19:44
Ah right, I do use `ptr::write` for types that drop.  In other cases where I just have a large struct of scalars and want to use `Default`, that's not needed.

I use the static values all over my program, so having to use a wrapper on every access isn't ideal.

**Comment by Amanieu** [comment] 2019-01-09 13:01
I think the source of the problem here is that `BTreeMap` contains a `NonNull`, which means that setting it to zero is UB. The proper solution in this case is to put  the `MaybeUninit` in the `static` itself.

**Comment by robsmith11** [comment] 2019-01-09 18:40
I see there's now a `const_transmute` function.  Using that instead of my `union` trick allows me to use arrays of any size wtihout triggering the error, so this particular case is no longer a problem (but I still think it should work as written in the previous comment).

**Comment by robsmith11** [comment] 2019-01-10 08:34
I found a solution that works for scalars and arrays of scalars:
```
#![feature(const_transmute)]

static mut ST:St = unsafe { std::mem::transmute([0u8;std::mem::size_of::<St>()]) };

struct St {
    x:f64,
    y:[f64;5],
}
```

Should this also work for `Vec`s or are they similar to `BTreeMap`?

**Comment by jonas-schievink** [comment] 2019-01-26 22:41
`Vec` also makes use of `NonNull` for the data pointer AFAIK.

**Comment by oli-obk** [comment] 2019-02-01 13:00
I don't see anything actionable wrt the behavior. We can't ever allow this. What we can do is improve the diagnostics. Any suggestions how to improve the error message to make it clearer what the problem is?

**Comment by oli-obk** [comment] 2020-11-05 16:26
I don't know how to improve the suggestion here, and this issue hasn't gotten any activity in over a year, so I'm closing it

**Closed by oli-obk** 2020-11-05 16:26 UTC
Labels: A-const-eval, A-diagnostics, C-enhancement, E-easy, T-compiler
