### ISSUE TITLE
PanicInfo nearly useless in no_std enviroment without nightly features

### ISSUE THREAD

**Issue by Gip-Gip** [rust-lang/rust#110098] opened 2023-04-09 00:06 UTC
I'm writing a simple panic handler for my embedded system which flashes an LED in pseudo-morse code to tell the user what error occurred. I *need* the error message, however I can't get it without the nightly `PanicInfo.message()`. There is no reason I should be forced to use nightly to use such a basic feature.

I get why it may have not been stabilized immediately, but `.message()` [was basically left to die in 2019](https://github.com/rust-lang/rust/issues/66745) and my panic handler is 100% useless without `.message()` since panics using core have no payload.

It is very frustrating to develop a substantial firmware and not have a user friendly panic handler without relying on unstable features, especially since *`.message()` has been unstable for over 4 years*. There is no reason this important feature shouldn't have been addressed by now.

**Comment by jyn514** [comment] 2023-04-09 01:57
This is a duplicate of #66745. I'm sorry you're frustrated by the slow progress here, but that's the nature of open source projects, work only happens if someone volunteers to work on it.

I'm happy to give you pointers on how to move it towards stabilization if you're interested in working on that; it looks like there's only a small amount of work left: https://github.com/rust-lang/rust/issues/66745#issuecomment-1006112016

**Closed by jyn514** 2023-04-09 01:57 UTC

**Comment by jonas-schievink** [comment] 2023-04-09 03:49
`PanicInfo` has implemented `Display` since 2018

**Comment by Gip-Gip** [comment] 2023-04-09 06:15
> `PanicInfo` has implemented `Display` since 2018

My bad I missed that, most code examples I've seen extract the value from the payload and I was too focused on that I didn't even look at the traits.
