### ISSUE TITLE
C++ compiler cache causes compiler segfaults on ARM

### ISSUE THREAD

**Issue by msizanoen** [rust-lang/rust#64034] opened 2019-08-31 11:35 UTC
Since the LLVM 9 update, rustc will segfault on ARM hosts with opt-level > 0 and codegen-units > 1.
The possible cause is that GCC ARM C++ ABI is not very stable (sometimes you will see the "parameter passing of argument of type ... changed in GCC \<version\>" note) and sccache did not properly handle this.
Possibly GCC was updated when we was using LLVM 8 and the undefined behavior is somehow only triggered when we upgrade to LLVM 9.
More information: https://github.com/rust-lang/rust/issues/62896#issuecomment-526801500

**Comment by Mark-Simulacrum** [comment] 2019-08-31 20:28
cc @alexcrichton @aidanhs since this sounds like maybe it's an sccache issue?

We can temporarily deal with this by clearing out our caches and rebuilding beta, but that's not a great place to be in (where we can apparently accidentally cause segfaults due to sccache lacking granularity...

**Comment by alexcrichton** [comment] 2019-09-03 14:54
I'm not really sure how this is connected to `sccache`, there's a huge number of things different in a CI build environment than a local build environment, so if local works and CI doesn't that doesn't imply `sccache` as the root cause. I think more investigation is needed into what's going wrong here, and it's probably not `sccache` but likely how we're compiling nightlies with glibc versions/flags/etc.

**Comment by Mark-Simulacrum** [comment] 2019-09-03 17:10
We discussed this briefly in infra team meeting and mostly concluded that we agree with @alexcrichton here that this is probably not an infrastructure problem but rather wrong args being passed around somewhere or an incorrect version getting linked (which may be in rustbuild, but introduced during LLVM upgrade it sounds like).

As such, we're going to close this since it's then a duplicate of https://github.com/rust-lang/rust/issues/62896 which'll likely be resolved by the compiler team.

**Closed by Mark-Simulacrum** 2019-09-03 17:10 UTC
Labels: I-nominated, T-infra
