### ISSUE TITLE
rust warns about unused assignment erroneously

### ISSUE THREAD

**Issue by rajatgoel** [rust-lang/rust#28570] opened 2015-09-21 17:58 UTC
Like in the program below - 

```
fn f() -> Option<i32> {
    None
}

fn main() {
    let mut v = 5;
    while v != 4 {
        let _ = match f() {
            Some(x) => x,
            None => {
                v = 4;
                continue
            },
        };

        v = 2;
    }
}

<anon>:11:17: 11:18 warning: value assigned to `v` is never read, #[warn(unused_assignments)] on by default
<anon>:11                 v = 4;
                          ^
```

Rust playground - http://is.gd/k1Zum7

**Comment by arielb1** [comment] 2015-09-21 18:05
middle::liveness does not use the CFG, but we are killing it anyway as part of the MIR work.

**Comment by malbarbo** [comment] 2016-10-20 18:05
Here another example

```rust
fn main() {
    let mut r = vec![1, 2].into_iter();
    let mut flag = true;
    'out: while flag {
        flag = false;
        if let Some(x) = r.next() {
            flag = true;
            println!("{}", x);
            continue 'out;
        }
    }
}
```

```text
warning: value assigned to `flag` is never read, #[warn(unused_assignments)] on by default
 --> <anon>:7:13
  |
7 |             flag = true;
  |             ^^^^

```

**Comment by reverendhomer** [comment] 2016-12-27 11:52
Looks like MIR didn't help. This bug is still reproducible: https://is.gd/LNFdkl

So, any progress with that?

**Comment by arielb1** [comment] 2017-01-09 12:44
MIR liveness was still not implemented.

**Comment by Mark-Simulacrum** [comment] 2017-07-24 16:42
This is the same underlying problem as https://github.com/rust-lang/rust/issues/22630, closing in favor of that.

**Closed by Mark-Simulacrum** 2017-07-24 16:42 UTC
Labels: A-lint, T-compiler
