### ISSUE TITLE
rustdoc shows __arg0 for mutable parameter to async function

### ISSUE THREAD

**Issue by Hawk777** [rust-lang/rust#77533] opened 2020-10-04 16:58 UTC
I tried this code:

```rust
/// Does a thing.
pub async fn do_thing(mut x: u32) {
	x
}
```

I expected to see this happen: In the Rustdoc output, a parameter named `x`.

Instead, this happened: In the Rustdoc output, `pub async fn do_thing(__arg0: u32)`.

### Meta
`rustc --version --verbose`:
```
rustc 1.46.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```

**Comment by camelid** [comment] 2020-10-04 18:32
Minimized to:

```rust
async fn foo(mut x: i32) {}
```

**Comment by camelid** [comment] 2020-10-04 18:33
Applying `P-medium` since I think this is important to fix.

**Comment by jyn514** [comment] 2020-10-05 01:46
Duplicate of https://github.com/rust-lang/rust/issues/76517

**Closed by jyn514** 2020-10-05 01:46 UTC
Labels: A-async-await, C-bug, P-medium, T-rustdoc
