### ISSUE TITLE
downgrade_to_delayed_bug: cannot downgrade Warning(None) to DelayedBug: not an error

### ISSUE THREAD

**Issue by thomasyonug** [rust-lang/rust#120082] opened 2024-01-18 02:44 UTC
### Code

```Rust

trait ThreeCellFragment {
    fn ext_cells<'a>(&'a self) -> Box<dyn Foo> + 'a {
        self.ext_adjacent_cells()
    }

    fn ext_adjacent_cells<'a>(&'a self) -> Box<dyn Foo> + 'a;
}
fn main() {}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.77.0-nightly (595bc6f00 2024-01-05)
binary: rustc
commit-hash: 595bc6f00369475047538fdae1ff8cea692ac385
commit-date: 2024-01-05
host: x86_64-unknown-linux-gnu
release: 1.77.0-nightly
LLVM version: 17.0.6
```

### Error output

```
ICE
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_hir_analysis/src/astconv/lint.rs:127:22:
downgrade_to_delayed_bug: cannot downgrade Warning(None) to DelayedBug: not an error
stack backtrace:
   0:     0x7f859595e806 - std::backtrace_rs::backtrace::libunwind::trace::hccd39fe91d56daec
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f859595e806 - std::backtrace_rs::backtrace::trace_unsynchronized::hb9c211c184511b77
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f859595e806 - std::sys_common::backtrace::_print_fmt::ha68911449431f29f
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f859595e806 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34c6aa4d9ef2549f
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f85959b0f00 - core::fmt::rt::Argument::fmt::h97f0cd02ba3737ef
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/fmt/rt.rs:142:9
   5:     0x7f85959b0f00 - core::fmt::write::heb4624e14e98aea7
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f859595215f - std::io::Write::write_fmt::h25504a918ea5c052
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/io/mod.rs:1810:15
   7:     0x7f859595e5e4 - std::sys_common::backtrace::_print::h16efe88e7fa25a23
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f859595e5e4 - std::sys_common::backtrace::print::h4f2dda7c938219d4
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f8595961377 - std::panicking::default_hook::{{closure}}::hdfd96bdc522bbb15
  10:     0x7f85959610d9 - std::panicking::default_hook::hf1cac0ca04453e02
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:292:9
  11:     0x7f859873814c - std[4bc72880d5231e4c]::panicking::update_hook::<alloc[8519608b14536aba]::boxed::Box<rustc_driver_impl[13f857263de4d0ff]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f8595961ac6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h237f4118e41609d8
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/alloc/src/boxed.rs:2030:9
  13:     0x7f8595961ac6 - std::panicking::rust_panic_with_hook::hd39b254275236486
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:783:13
  14:     0x7f8595961812 - std::panicking::begin_panic_handler::{{closure}}::h5bbe5cb47793ee20
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:657:13
  15:     0x7f859595ed06 - std::sys_common::backtrace::__rust_end_short_backtrace::h464decb1e79e1351
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f8595961570 - rust_begin_unwind
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:645:5
  17:     0x7f85959ad605 - core::panicking::panic_fmt::h679166b76d3d88f6
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:72:14
  18:     0x7f8597d9b128 - <rustc_errors[97e5471a9bbf658f]::diagnostic::Diagnostic>::downgrade_to_delayed_bug
  19:     0x7f859885a612 - <dyn rustc_hir_analysis[fed3235f881802f1]::astconv::AstConv>::maybe_lint_impl_trait
  20:     0x7f859881457c - <<dyn rustc_hir_analysis[fed3235f881802f1]::astconv::AstConv>::maybe_lint_bare_trait::{closure#1} as core[25a4dcbb3cee7009]::ops::function::FnOnce<(&mut rustc_errors[97e5471a9bbf658f]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
  21:     0x7f859882f672 - <alloc[8519608b14536aba]::boxed::Box<dyn for<'a, 'b> core[25a4dcbb3cee7009]::ops::function::FnOnce<(&'a mut rustc_errors[97e5471a9bbf658f]::diagnostic_builder::DiagnosticBuilder<'b, ()>,), Output = ()>> as core[25a4dcbb3cee7009]::ops::function::FnOnce<(&mut rustc_errors[97e5471a9bbf658f]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once
  22:     0x7f859a876624 - rustc_middle[a971313bcac29b13]::lint::struct_lint_level::struct_lint_level_impl::<&str>
  23:     0x7f8599bb68e6 - <dyn rustc_hir_analysis[fed3235f881802f1]::astconv::AstConv>::ast_ty_to_ty_inner
  24:     0x7f8599bb3ab6 - <dyn rustc_hir_analysis[fed3235f881802f1]::astconv::AstConv>::ty_of_fn
  25:     0x7f8599bb2b6e - rustc_hir_analysis[fed3235f881802f1]::collect::infer_return_ty_for_fn_sig
  26:     0x7f8599bb1dfc - rustc_hir_analysis[fed3235f881802f1]::collect::fn_sig
  27:     0x7f8599bab105 - rustc_query_impl[d834e4f78e079c87]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d834e4f78e079c87]::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a971313bcac29b13]::query::erase::Erased<[u8; 24usize]>>
  28:     0x7f8599bab0d5 - <rustc_query_impl[d834e4f78e079c87]::query_impl::fn_sig::dynamic_query::{closure#2} as core[25a4dcbb3cee7009]::ops::function::FnOnce<(rustc_middle[a971313bcac29b13]::ty::context::TyCtxt, rustc_span[3a08aed223fea3cd]::def_id::DefId)>>::call_once
  29:     0x7f8599baa713 - rustc_query_system[e673152937f37d93]::query::plumbing::try_execute_query::<rustc_query_impl[d834e4f78e079c87]::DynamicConfig<rustc_query_system[e673152937f37d93]::query::caches::DefaultCache<rustc_span[3a08aed223fea3cd]::def_id::DefId, rustc_middle[a971313bcac29b13]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[d834e4f78e079c87]::plumbing::QueryCtxt, false>
  30:     0x7f8599baa135 - rustc_query_impl[d834e4f78e079c87]::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f8599e7264f - <rustc_hir_analysis[fed3235f881802f1]::collect::CollectItemTypesVisitor as rustc_hir[84af96d42540fa18]::intravisit::Visitor>::visit_trait_item
  32:     0x7f8599e85c97 - rustc_hir_analysis[fed3235f881802f1]::collect::collect_mod_item_types
  33:     0x7f8599e85b51 - rustc_query_impl[d834e4f78e079c87]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d834e4f78e079c87]::query_impl::collect_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a971313bcac29b13]::query::erase::Erased<[u8; 0usize]>>
  34:     0x7f859a3ba2cf - rustc_query_system[e673152937f37d93]::query::plumbing::try_execute_query::<rustc_query_impl[d834e4f78e079c87]::DynamicConfig<rustc_query_system[e673152937f37d93]::query::caches::DefaultCache<rustc_span[3a08aed223fea3cd]::def_id::LocalModDefId, rustc_middle[a971313bcac29b13]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[d834e4f78e079c87]::plumbing::QueryCtxt, false>
  35:     0x7f859a3b9e03 - rustc_query_impl[d834e4f78e079c87]::query_impl::collect_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  36:     0x7f8599c162e1 - rustc_hir_analysis[fed3235f881802f1]::check_crate
  37:     0x7f859a603319 - rustc_interface[51292d701ac247ab]::passes::analysis
  38:     0x7f859a602f5f - rustc_query_impl[d834e4f78e079c87]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d834e4f78e079c87]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[a971313bcac29b13]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7f859a977164 - rustc_query_system[e673152937f37d93]::query::plumbing::try_execute_query::<rustc_query_impl[d834e4f78e079c87]::DynamicConfig<rustc_query_system[e673152937f37d93]::query::caches::SingleCache<rustc_middle[a971313bcac29b13]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[d834e4f78e079c87]::plumbing::QueryCtxt, false>
  40:     0x7f859a976f55 - rustc_query_impl[d834e4f78e079c87]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:     0x7f859a724e75 - rustc_interface[51292d701ac247ab]::interface::run_compiler::<core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>, rustc_driver_impl[13f857263de4d0ff]::run_compiler::{closure#0}>::{closure#0}
  42:     0x7f859a9a74c6 - std[4bc72880d5231e4c]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[51292d701ac247ab]::util::run_in_thread_with_globals<rustc_interface[51292d701ac247ab]::util::run_in_thread_pool_with_globals<rustc_interface[51292d701ac247ab]::interface::run_compiler<core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>, rustc_driver_impl[13f857263de4d0ff]::run_compiler::{closure#0}>::{closure#0}, core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>>::{closure#0}, core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>>
  43:     0x7f859a9a72f3 - <<std[4bc72880d5231e4c]::thread::Builder>::spawn_unchecked_<rustc_interface[51292d701ac247ab]::util::run_in_thread_with_globals<rustc_interface[51292d701ac247ab]::util::run_in_thread_pool_with_globals<rustc_interface[51292d701ac247ab]::interface::run_compiler<core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>, rustc_driver_impl[13f857263de4d0ff]::run_compiler::{closure#0}>::{closure#0}, core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>>::{closure#0}, core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[25a4dcbb3cee7009]::result::Result<(), rustc_span[3a08aed223fea3cd]::ErrorGuaranteed>>::{closure#1} as core[25a4dcbb3cee7009]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7f859596b9f5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2001850c7d8d32d3
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/alloc/src/boxed.rs:2016:9
  45:     0x7f859596b9f5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7c86f6f83b95073a
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/alloc/src/boxed.rs:2016:9
  46:     0x7f859596b9f5 - std::sys::unix::thread::Thread::new::thread_start::hb8a567c3fcdea6b4
                               at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7f8595856609 - start_thread
                               at /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:477:8
  48:     0x7f8595779353 - clone
                               at /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  49:                0x0 - <unknown>
```

</p>
</details>

**Comment by compiler-errors** [comment] 2024-01-18 02:56
Please double check that this still ICEs on the latest nightly compiler

**Comment by thomasyonug** [comment] 2024-01-18 04:46
I try it on the rustc version
```
rustc 1.77.0-nightly (6ae4cfbbb 2024-01-17)
binary: rustc
commit-hash: 6ae4cfbbb080cafea7f6be48ce47678ee057352c
commit-date: 2024-01-17
host: x86_64-apple-darwin
release: 1.77.0-nightly
LLVM version: 17.0.6
```

and the backtrace is
```
thread 'rustc' panicked at compiler/rustc_hir_analysis/src/astconv/lint.rs:127:22:
downgrade_to_delayed_bug: cannot downgrade Warning to DelayedBug: not an error
stack backtrace:
   0:        0x103581ac5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h60fcf3d7a1f6a3df
   1:        0x1035ce773 - core::fmt::write::h76cd412b8772acdf
   2:        0x103577a2e - std::io::Write::write_fmt::haef1ab8bc4233797
   3:        0x103581899 - std::sys_common::backtrace::print::hff388d8ab2e59d0f
   4:        0x103584b85 - std::panicking::default_hook::{{closure}}::h22308cbc456fc3cc
   5:        0x1035848fe - std::panicking::default_hook::h1428a3351b8fcf92
   6:        0x10d3bbdfc - std[10d919ad3866ceb7]::panicking::update_hook::<alloc[51bd1bd92521fe7b]::boxed::Box<rustc_driver_impl[8448b6c3c65e5244]::install_ice_hook::{closure#0}>>::{closure#0}
   7:        0x103585235 - std::panicking::rust_panic_with_hook::h0810018ee8479480
   8:        0x103584fc4 - std::panicking::begin_panic_handler::{{closure}}::h29ca29b96951fae4
   9:        0x103581fb9 - std::sys_common::backtrace::__rust_end_short_backtrace::h3f85e4c55404649e
  10:        0x103584d06 - _rust_begin_unwind
  11:        0x1035eab15 - core::panicking::panic_fmt::hf2860a3800f0f49c
  12:        0x10d43329d - <rustc_errors[77202b8e7554afa2]::diagnostic::Diagnostic>::downgrade_to_delayed_bug
  13:        0x10d5e1967 - <dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::maybe_lint_impl_trait
  14:        0x10d760e8c - <<dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::maybe_lint_bare_trait::{closure#1} as core[1c01109e239739fc]::ops::function::FnOnce<(&mut rustc_errors[77202b8e7554afa2]::diagnostic_builder::DiagnosticBuilder<()>,)>>::call_once::{shim:vtable#0}
  15:        0x10d75f432 - rustc_middle[ab6258147952bdf3]::lint::struct_lint_level::struct_lint_level_impl::<&str>
  16:        0x10d75ad16 - rustc_middle[ab6258147952bdf3]::lint::struct_lint_level::<&str, <dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::maybe_lint_bare_trait::{closure#1}>
  17:        0x10d611a2a - <rustc_middle[ab6258147952bdf3]::ty::context::TyCtxt>::struct_span_lint_hir::<rustc_span[a5e86a27697130dc]::span_encoding::Span, &str, <dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::maybe_lint_bare_trait::{closure#1}>
  18:        0x10d5e273b - <dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::maybe_lint_bare_trait
  19:        0x10d6063b0 - <dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::ast_ty_to_ty_inner
  20:        0x10d607708 - <dyn rustc_hir_analysis[405ec0c6aedc355d]::astconv::AstConv>::ty_of_fn
  21:        0x10d6a6fc4 - rustc_hir_analysis[405ec0c6aedc355d]::collect::infer_return_ty_for_fn_sig
  22:        0x10d6b3586 - rustc_hir_analysis[405ec0c6aedc355d]::collect::fn_sig
  23:        0x10e92d4fd - rustc_query_impl[4a165c6509075809]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4a165c6509075809]::query_impl::fn_sig::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ab6258147952bdf3]::query::erase::Erased<[u8; 24usize]>>
  24:        0x10e9be9b3 - <rustc_query_impl[4a165c6509075809]::query_impl::fn_sig::dynamic_query::{closure#2} as core[1c01109e239739fc]::ops::function::FnOnce<(rustc_middle[ab6258147952bdf3]::ty::context::TyCtxt, rustc_span[a5e86a27697130dc]::def_id::DefId)>>::call_once
  25:        0x10e807fb6 - rustc_query_system[72cea6b20a0528c1]::query::plumbing::try_execute_query::<rustc_query_impl[4a165c6509075809]::DynamicConfig<rustc_query_system[72cea6b20a0528c1]::query::caches::DefIdCache<rustc_middle[ab6258147952bdf3]::query::erase::Erased<[u8; 24usize]>>, false, false, false>, rustc_query_impl[4a165c6509075809]::plumbing::QueryCtxt, false>
  26:        0x10ea5c594 - rustc_query_impl[4a165c6509075809]::query_impl::fn_sig::get_query_non_incr::__rust_end_short_backtrace
  27:        0x10d69ad3a - <rustc_hir_analysis[405ec0c6aedc355d]::collect::CollectItemTypesVisitor as rustc_hir[305781ea438edded]::intravisit::Visitor>::visit_trait_item
  28:        0x10d71ff6a - <rustc_middle[ab6258147952bdf3]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis[405ec0c6aedc355d]::collect::CollectItemTypesVisitor>
  29:        0x10d699415 - rustc_hir_analysis[405ec0c6aedc355d]::collect::collect_mod_item_types
  30:        0x10e92b6ef - rustc_query_impl[4a165c6509075809]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4a165c6509075809]::query_impl::collect_mod_item_types::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ab6258147952bdf3]::query::erase::Erased<[u8; 0usize]>>
  31:        0x10eaa602c - <rustc_query_impl[4a165c6509075809]::query_impl::collect_mod_item_types::dynamic_query::{closure#2} as core[1c01109e239739fc]::ops::function::FnOnce<(rustc_middle[ab6258147952bdf3]::ty::context::TyCtxt, rustc_span[a5e86a27697130dc]::def_id::LocalModDefId)>>::call_once
  32:        0x10e87b3f6 - rustc_query_system[72cea6b20a0528c1]::query::plumbing::try_execute_query::<rustc_query_impl[4a165c6509075809]::DynamicConfig<rustc_query_system[72cea6b20a0528c1]::query::caches::DefaultCache<rustc_span[a5e86a27697130dc]::def_id::LocalModDefId, rustc_middle[ab6258147952bdf3]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[4a165c6509075809]::plumbing::QueryCtxt, false>
  33:        0x10e9e8eba - rustc_query_impl[4a165c6509075809]::query_impl::collect_mod_item_types::get_query_non_incr::__rust_end_short_backtrace
  34:        0x10d71f960 - <rustc_middle[ab6258147952bdf3]::hir::map::Map>::for_each_module::<rustc_hir_analysis[405ec0c6aedc355d]::check_crate::{closure#0}::{closure#0}>
  35:        0x10d73c121 - rustc_hir_analysis[405ec0c6aedc355d]::check_crate
  36:        0x10dbef18f - rustc_interface[1957001f5c558641]::passes::analysis
  37:        0x10e92d64d - rustc_query_impl[4a165c6509075809]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[4a165c6509075809]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[ab6258147952bdf3]::query::erase::Erased<[u8; 1usize]>>
  38:        0x10ea17b89 - <rustc_query_impl[4a165c6509075809]::query_impl::analysis::dynamic_query::{closure#2} as core[1c01109e239739fc]::ops::function::FnOnce<(rustc_middle[ab6258147952bdf3]::ty::context::TyCtxt, ())>>::call_once
  39:        0x10e825df9 - rustc_query_system[72cea6b20a0528c1]::query::plumbing::try_execute_query::<rustc_query_impl[4a165c6509075809]::DynamicConfig<rustc_query_system[72cea6b20a0528c1]::query::caches::SingleCache<rustc_middle[ab6258147952bdf3]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[4a165c6509075809]::plumbing::QueryCtxt, false>
  40:        0x10ea59ae1 - rustc_query_impl[4a165c6509075809]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  41:        0x10d35d361 - <rustc_middle[ab6258147952bdf3]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[8448b6c3c65e5244]::run_compiler::{closure#0}::{closure#0}::{closure#3}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>
  42:        0x10d33e47a - <rustc_interface[1957001f5c558641]::interface::Compiler>::enter::<rustc_driver_impl[8448b6c3c65e5244]::run_compiler::{closure#0}::{closure#0}, core[1c01109e239739fc]::result::Result<core[1c01109e239739fc]::option::Option<rustc_interface[1957001f5c558641]::queries::Linker>, rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>
  43:        0x10d39efba - rustc_span[a5e86a27697130dc]::set_source_map::<core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>, rustc_interface[1957001f5c558641]::interface::run_compiler<core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>, rustc_driver_impl[8448b6c3c65e5244]::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
  44:        0x10d38fde5 - <scoped_tls[4e1c2d48448d1e73]::ScopedKey<rustc_span[a5e86a27697130dc]::SessionGlobals>>::set::<rustc_interface[1957001f5c558641]::util::run_in_thread_pool_with_globals<rustc_interface[1957001f5c558641]::interface::run_compiler<core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>, rustc_driver_impl[8448b6c3c65e5244]::run_compiler::{closure#0}>::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>
  45:        0x10d3ab083 - std[10d919ad3866ceb7]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1957001f5c558641]::util::run_in_thread_with_globals<rustc_interface[1957001f5c558641]::util::run_in_thread_pool_with_globals<rustc_interface[1957001f5c558641]::interface::run_compiler<core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>, rustc_driver_impl[8448b6c3c65e5244]::run_compiler::{closure#0}>::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>
  46:        0x10d3969b9 - <<std[10d919ad3866ceb7]::thread::Builder>::spawn_unchecked_<rustc_interface[1957001f5c558641]::util::run_in_thread_with_globals<rustc_interface[1957001f5c558641]::util::run_in_thread_pool_with_globals<rustc_interface[1957001f5c558641]::interface::run_compiler<core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>, rustc_driver_impl[8448b6c3c65e5244]::run_compiler::{closure#0}>::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1c01109e239739fc]::result::Result<(), rustc_span[a5e86a27697130dc]::ErrorGuaranteed>>::{closure#1} as core[1c01109e239739fc]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  47:        0x10358df69 - std::sys::pal::unix::thread::Thread::new::thread_start::ha1f806490b79322d
  48:     0x7ff81682c202 - __pthread_start
```

**Comment by matthiaskrgr** [comment] 2024-01-18 08:54
https://github.com/rust-lang/rust/issues/119633

**Comment by Nilstrieb** [comment] 2024-01-20 10:38
closing as a duplicate of #119633

**Closed by Nilstrieb** 2024-01-20 10:38 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
