### ISSUE TITLE
panicked at 'failed to lookup `SourceFile`

### ISSUE THREAD

**Issue by s0lst1ce** [rust-lang/rust#72473] opened 2020-05-22 16:39 UTC
Hello. I'm new to Rust and I've been building a small web api using `rocket` and `serde_json`. All was going well until I started making use of `std::sync::Once` in my test suite (provided in #Code). Now I can't run my tests nor compile the binary (should I link the code to it as well?).
### Code

```Rust
use std::fs;
use std::path::Path;
use std::sync::Once;

const BASE_PATH: &str = "emulated/";
const SERVER_PATH: &str = "emulated/servers/";

static INIT: Once = Once::new();
fn setup_env() {
    fs::create_dir_all(SERVER_PATH).expect("Couldn't setup environement");
    fs::write(
        Path::new(BASE_PATH).join("settings.py"),
        "AVAILABLE_LANGS = [\"en\", \"fr\"]",
    )
    .expect("Couldn't setup environement");
    fs::write(Path::new(SERVER_PATH).join("54654564.json"), "{}")
        .expect("Couldn't setup environement");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_server_all() {
        INIT.call_once(|| {
            setup_env();
        });
    }
    #[test]
    fn test_server_one() {
        INIT.call_once(|| {
            setup_env();
        });
    }

    #[test]
    fn test_server_conf() {
        INIT.call_once(|| {
            setup_env();
        });
    }

    #[test]
    fn test_available_langs() {
        INIT.call_once(|| {
            setup_env();
        });
    }

    #[test]
    fn test_overwrite_conf() {
        INIT.call_once(|| {
            setup_env();
        });
    }
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
binary: rustc
commit-hash: a74d1862d4d87a56244958416fd05976c58ca1a8
commit-date: 2020-05-14
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

### Error output

```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (a74d1862d 2020-05-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `linker`.

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', src/librustc_middle/ty/query/on_disk_cache.rs:456:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/liballoc/boxed.rs:1048
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/a74d1862d4d87a56244958416fd05976c58ca1a8/src/libproc_macro/bridge/client.rs:312
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  14: rust_begin_unwind
             at src/libstd/panicking.rs:385
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  16: core::option::expect_failed
             at src/libcore/option.rs:1264
  17: <rustc_middle::ty::query::on_disk_cache::CacheDecoder as serialize::serialize::SpecializedDecoder<rustc_span::span_encoding::Span>>::specialized_decode
  18: <rustc_middle::mir::SourceInfo as serialize::serialize::Decodable>::decode
  19: <rustc_middle::mir::Statement as serialize::serialize::Decodable>::decode
  20: serialize::serialize::Decoder::read_seq
  21: <rustc_middle::mir::BasicBlockData as serialize::serialize::Decodable>::decode
  22: serialize::serialize::Decoder::read_seq
  23: <rustc_middle::mir::Body as serialize::serialize::Decodable>::decode
  24: rustc_middle::ty::query::on_disk_cache::OnDiskCache::try_load_query_result
  25: rustc_middle::query::<impl rustc_query_system::query::config::QueryDescription<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::optimized_mir>::try_load_from_disk
  26: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
  27: rustc_query_system::query::plumbing::get_query_impl
  28: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir
  29: rustc_mir::monomorphize::collector::collect_neighbours
  30: rustc_data_structures::stack::ensure_sufficient_stack
  31: rustc_mir::monomorphize::collector::collect_items_rec
  32: rustc_session::utils::<impl rustc_session::session::Session>::time
  33: rustc_mir::monomorphize::collector::collect_crate_mono_items
  34: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
  35: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_and_partition_mono_items>::compute
  36: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  37: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  38: rustc_data_structures::stack::ensure_sufficient_stack
  39: rustc_query_system::query::plumbing::get_query_impl
  40: rustc_codegen_ssa::base::codegen_crate
  41: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  42: rustc_session::utils::<impl rustc_session::session::Session>::time
  43: rustc_interface::passes::start_codegen
  44: rustc_middle::ty::context::tls::enter_global
  45: rustc_interface::queries::Queries::ongoing_codegen
  46: rustc_interface::interface::run_compiler_in_existing_thread_pool
  47: scoped_tls::ScopedKey<T>::set
  48: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (a74d1862d 2020-05-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] processing `main`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: could not compile `linker`.
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-05-22 16:54
Duplicate of https://github.com/rust-lang/rust/issues/70924

**Closed by jonas-schievink** 2020-05-22 16:54 UTC
Labels: C-bug, I-ICE, T-compiler
