### ISSUE TITLE
Rust-defined extern fns can't be debugged

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#22071] opened 2015-02-08 00:12 UTC
Trying to implement a C interface, if I break in this function gdb doesn't know the source location:

```
#[no_mangle]
pub unsafe extern "C" fn BN_bin2bn(s: *const c_uchar, len: c_int, ret: *mut BIGNUM) -> *mut BIGNUM {
        let s = slice::from_raw_parts(&s, len as usize);
        match ret.as_mut() {
            Some(ret) => {
                unimplemented!()
            }
            None => {
                unimplemented!()
            }
        }
}
```

I can though wrap the entire function in a Rust function and break on *it*

```
#[no_mangle]
pub unsafe extern "C" fn BN_bin2bn(s: *const c_uchar, len: c_int, ret: *mut BIGNUM) -> *mut BIGNUM {
    unsafe fn BN_bin2bn2(s: *const c_uchar, len: c_int, ret: *mut BIGNUM) -> *mut BIGNUM {
        let s = slice::from_raw_parts(&s, len as usize);
        match ret.as_mut() {
            Some(ret) => {
                unimplemented!()
            }
            None => {
                unimplemented!()
            }
        }
    }
    BN_bin2bn2(s, len, ret)
}
```

**Comment by jdm** [comment] 2015-02-08 01:07
#15218 suggests that we have line number information here, but local symbols are all messed up.

**Comment by michaelwoerister** [comment] 2015-02-26 14:44
I can't seem to be reproduce this. How exactly do you compile and debug this? Is the function linked into a C program and debugged from there?

I've written an auto test that works just fine (can break and read out variable values):
```rust

#[no_mangle]
pub unsafe extern "C" fn fn_with_c_abi(s: *const u8, len: i32) -> i32 {
    let local0 = len - 1;
    let local1 = len > 2;
    let local2 = (len as f64) + 0.5;

    zzz(); // #break

    return 0;
}

fn main() {
    unsafe {
        fn_with_c_abi(b"abcd\0".as_ptr(), 20);
    }
}

#[inline(never)]
fn zzz() {()}
```
You must be doing something differently somewhere.

**Comment by michaelwoerister** [comment] 2015-11-04 14:14
Since the auto-test listed above is in-tree for quite some time and it seems to work, I'm closing this issue.

**Closed by michaelwoerister** 2015-11-04 14:14 UTC
Labels: A-debuginfo
