### ISSUE TITLE
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13

### ISSUE THREAD

**Issue by cooksey14** [rust-lang/rust#87592] opened 2021-07-29 15:54 UTC
I set up a new project and tried to install microserver by running:
`cargo new bug_repro`
`cargo install microserver`

But received the following when doing so:
`thread 'rustc' panicked at 'no errors encountered even though delay_span_bug issued', compiler/rustc_errors/src/lib.rs:1050:13`

### Meta

`rustc --version --verbose`:

```
rustc 1.56.0-nightly (2faabf579 2021-07-27)
binary: rustc
commit-hash: 2faabf579323f5252329264cc53ba9ff803429a3
commit-date: 2021-07-27
host: x86_64-apple-darwin
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Error output

```
error: internal compiler error: unexpected concrete region in borrowck: ReStatic
   --> /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.5/src/filters/sse.rs:457:5
    |
457 | /     pub fn stream<S>(
458 | |         self,
459 | |         event_stream: S,
460 | |     ) -> impl TryStream<
...   |
476 | |         }
477 | |     }
    | |_____^
    |
    = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44

error: internal compiler error: unexpected concrete region in borrowck: ReStatic
   --> /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.5/src/filters/sse.rs:492:1
    |
492 | / pub fn keep<S>(
493 | |     event_stream: S,
494 | |     keep_interval: impl Into<Option<Duration>>,
495 | | ) -> impl TryStream<
...   |
514 | |     }
515 | | }
    | |_^
    |
    = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:        0x10ebfc2f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbf0f7aeb2a01393a
   1:        0x10ec60bec - core::fmt::write::h8160330c41daaf61
   2:        0x10ebee1da - std::io::Write::write_fmt::haa5623a2a8d2ec9f
   3:        0x10ebffebf - std::panicking::default_hook::{{closure}}::h5fe994d86d862da0
   4:        0x10ebff9bd - std::panicking::default_hook::hba89cfe1e23145fb
   5:        0x107286f90 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h136005a01e20e30f
   6:        0x10ec00716 - std::panicking::rust_panic_with_hook::h674e3a191f056728
   7:        0x10ec00195 - std::panicking::begin_panic_handler::{{closure}}::hc97521b9fa6c7ab0
   8:        0x10ebfc798 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a967faa138ad029
   9:        0x10ec000fa - _rust_begin_unwind
  10:        0x10ec8aeab - std::panicking::begin_panic_fmt::h4d9d4e08b31fe5f2
  11:        0x10b4ab719 - rustc_errors::HandlerInner::flush_delayed::h02d3c29affb897eb
  12:        0x10b4a7878 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h1273a0b1c832b19b
  13:        0x1072f0fba - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::h84e21477af0fb76b
  14:        0x1072f804b - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::h34cf49ebee641f9a
  15:        0x10728c4e2 - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::hc0a3a11eac145004
  16:        0x107288f5c - rustc_span::with_source_map::h7eb115613350f2ce
  17:        0x1072c8662 - rustc_interface::interface::create_compiler_and_run::he762e971fde55423
  18:        0x10729eb2f - scoped_tls::ScopedKey<T>::set::hda7dedb82dbd83ea
  19:        0x10728ed59 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb605b95fc8774c85
  20:        0x10728b2fd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7aae44cb08890327
  21:        0x10ec0badb - std::sys::unix::thread::Thread::new::thread_start::h76f99c3976df8852
  22:     0x7fff2044f8fc - __pthread_start
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-07-29 15:56
duplicate of https://github.com/rust-lang/rust/issues/87455

**Closed by jonas-schievink** 2021-07-29 15:56 UTC
Labels: C-bug, I-ICE, T-compiler
