### ISSUE TITLE
Lifetime inference fails for closures returning references to their parameters

### ISSUE THREAD

**Issue by 0xdeafbeef** [rust-lang/rust#125124] opened 2024-05-14 15:09 UTC
I tried this code:
```rust
#[derive(Default)]
struct Struct {
    field: String,
}

fn consume_closure<'a, F>(data: &'a Struct, f: F) -> &'a String
where
    F: Fn(&'a Struct) -> &'a String,
{
    f(data)
}

fn main() {
    let s = Struct::default();
    let naive = |f: &Struct| &f.field;
    consume_closure(&s, naive);
}
```

I expected to see this happen: code compiles

Instead, this happened: 
```
   |
18 |     let naive = |f: &Struct| &f.field;
   |                     -      - ^^^^^^^^ returning this value requires that `'1` must outlive `'2`
   |                     |      |
   |                     |      return type of closure is &'2 String
   |                     let's call the lifetime of this reference `'1`
   ```

This workaround involves defining a helper function just to handle the lifetimes explicitly, which complicates the code unnecessarily. It feels like a cumbersome solution to what should be a simpler problem.

```rs
fn identity<'a, F, A, R>(f: F) -> F
where
    F: Fn(A) -> R,
    A: 'a,
    R: 'a,
{
    f
}

let f = identity(move |point: &Struct| -> &String { &point.field });
let s = Struct::default();
consume_closure(&s, f);
```

[full example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0d0c427a259b1440c5458e6df5c8abe6)

**Comment by fmease** [comment] 2024-05-14 15:30
Duplicate of #58052. Nightly solution: Feature `closure_lifetime_binder`.
CC #116869, #111662.

**Closed** 2024-05-14 15:31 UTC
Labels: A-lifetimes, A-closures, T-compiler, C-bug
