### ISSUE TITLE
regression: parameter type may not live long enough

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#97607] opened 2022-06-01 00:59 UTC
See https://crater-reports.s3.amazonaws.com/beta-1.62-1/beta-2022-05-20/gh/FSMaxB.rust-genealogy/log.txt:

```
[INFO] [stdout] error[E0311]: the parameter type `Extracted` may not live long enough
[INFO] [stdout]   --> genealogy-java-apis/src/comparator.rs:24:13
[INFO] [stdout]    |
[INFO] [stdout] 24 |             compare: Box::new(move |left, right| match (self.compare)(left, right) {
[INFO] [stdout]    |                      ^^^^^^^^ ...so that the type `Extracted` will meet its required lifetime bounds...
[INFO] [stdout]    |
[INFO] [stdout] note: ...that is required by this bound
[INFO] [stdout]   --> genealogy-java-apis/src/comparator.rs:21:28
[INFO] [stdout]    |
[INFO] [stdout] 21 |         for<'a> Extracted: Ord + 'a,
[INFO] [stdout]    |                                  ^^
[INFO] [stdout] help: consider adding an explicit lifetime bound...
[INFO] [stdout]    |
[INFO] [stdout] 21 |         for<'a> Extracted: Ord + 'a + 'a,
[INFO] [stdout]    |                                     ++++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error: aborting due to previous error
```

This is a 1.62 regression, it seems, based on Crater. At the very least, it's a diagnostics issue that we're suggesting adding an already existing lifetime bound.

**Comment by compiler-errors** [comment] 2022-06-01 04:44
## Bisected
searched nightlies: from nightly-2022-04-01 to nightly-2022-05-31
regressed nightly: nightly-2022-05-14
searched commit range: https://github.com/rust-lang/rust/compare/a5ad0d29a401007b51715852cc702e441ac2248c...f1f721e64014863f41c1a386b04af04c2de25321
regressed commit: https://github.com/rust-lang/rust/commit/a7d6408b05912396618dfdcc9cc713d3ace2aa9a

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.3</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2022-04-01 --end=2022-05-31 
```
</details>

#96899, cc @oli-obk

## Minimized
https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=8bcb86adc0a98d57aecbe3e2b80229c0
```rust
fn test<T, F, U>(f: F) -> Box<dyn Fn(T) -> U + 'static>
where
    F: 'static + Fn(T) -> U,
    for<'a> U: 'a, // < This is the problematic line -- remove it, and it passes.
{
    Box::new(move |t| f(t))
}
```

**Comment by compiler-errors** [comment] 2022-06-01 05:00
The issue is that `for<'a> U: 'a` bound is causing the new wf check introduced in #96899 to fail.

Regarding the diagnostics being weird, the issue is probably because we don't handle the case where a higher-ranked lifetime doesn't outlive itself. We just see a borrowck error, see that it's due to the binder's `'a` lifetime, and suggest adding it. Not sure if that needs fixed, personally think it's not worth it.

**Comment by apiraino** [comment] 2022-06-08 16:12
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2397607.20regression.3A.20parameter.20type.20may.20not.20live.20long.20enough) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by oli-obk** [comment] 2022-06-14 10:13
This got fixed on nightly by enabling nll by default

**Comment by Rageking8** [comment] 2022-10-20 15:19
@rustbot claim
For the test

**Closed** 2022-10-22 02:28 UTC
Labels: E-needs-test, T-compiler
