### ISSUE TITLE
temporary value is freed at the end of this statement

### ISSUE THREAD

**Issue by tivrfoa** [rust-lang/rust#90760] opened 2021-11-10 11:34 UTC
Hi,

Can't the compiler generate the piece of code that works below, so the developer
doesn't need to break the lines manually?

```rust
fn main() {
    let x = 123;
    
    // doesn't work
    let x = x.to_string().as_bytes();
    
    // but this works ...
    // let x = x.to_string();
    // let x = x.as_bytes();
    
    let _len = x.len();
}
```

Error:

```rust
   Compiling playground v0.0.1 (/playground)
error[E0716]: temporary value dropped while borrowed
  --> src/main.rs:5:13
   |
5  |     let x = x.to_string().as_bytes();
   |             ^^^^^^^^^^^^^           - temporary value is freed at the end of this statement
   |             |
   |             creates a temporary which is freed while still in use
...
12 |     let _len = x.len();
   |                ------- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `playground` due to previous error
```

**Comment by AngelicosPhosphoros** [comment] 2021-11-10 19:24
It shouldn't.

```rust
let x = x.to_string(); // Create local owner of string
let x = x.as_bytes(); // Create reference to local variable
```
so here is clear owner of value.

And you are suggesting that compiler should somehow decide to extend lifetime of temporary. This makes code longer and less obvious. E.g.

```rust
fn do_few_actions_on_mutexes(m: &Mutex<String>){
    let reference = &*m.lock().unwrap();
    // If we extend lifetime as you suggested,
    // lock should be held here
    // but the fact that we keep mutex locked is surprising for reader.
}
```

**Comment by AngelicosPhosphoros** [comment] 2021-11-10 19:26
Current behaviour is simple and predictable: lifetime is tied to named variable in a scope so if you put it here, it is extended, otherwise it isn't.

**Comment by Dylan-DPC** [comment] 2023-02-11 09:31
Closing this as it works as intended.

**Closed by Dylan-DPC** 2023-02-11 09:31 UTC
