### ISSUE TITLE
[edition 2024] `missing_unsafe_on_extern` in macros with older editions

### ISSUE THREAD

**Issue by daxpedda** [rust-lang/rust#132425] opened 2024-10-31 21:47 UTC
I tried this code:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
unsafe extern {
    pub fn test();
}
```

I expected to see this happen: it should compile.
Instead, this happened: it fails to compile.

### Meta

`rustc --version --verbose`:
```
rustc 1.84.0-nightly (1e4f10ba6 2024-10-29)
binary: rustc
commit-hash: 1e4f10ba6476e48a42a79b9f846a2d9366525b9e
commit-date: 2024-10-29
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.1
```

<details><summary>Compile Error</summary>
<p>

```
error: extern blocks must be unsafe
  --> src/main.rs:5:12
  |
5 |     pub fn test();
  |            ^^^^
```

</p>
</details>

---

Basically the problem is that the `#[wasm-bindgen]` proc-macro generates `extern "C"` blocks which aren't prefixed with the `unsafe` keyword.
However, my understanding is that proc-macros should carry the edition from the crate they are coming from, which in this case is edition 2021. The rules of edition 2024 should not be applied to the generated code from this edition 2021 proc-macro.

That said, this is easily fixable in `wasm-bindgen`, but the bug will probably break other libraries as well.

Cc https://github.com/rustwasm/wasm-bindgen/issues/4218.

**Comment by ehuss** [comment] 2024-10-31 21:51
cc @spastorino Do you by chance know what is happening? Is it possible that wasm-bindgen is using the wrong hygiene?

**Comment by spastorino** [comment] 2024-11-04 20:55
Just gave it a very quick look ... this error is emitted in https://github.com/spastorino/rust/blob/2dece5bb62f234f5622a08289c5a3d1555cd7843/compiler/rustc_ast_passes/src/ast_validation.rs#L964-L977.
The if part is using `span.at_least_rust_2024` https://github.com/spastorino/rust/blob/2dece5bb62f234f5622a08289c5a3d1555cd7843/compiler/rustc_ast_passes/src/ast_validation.rs#L965-L966 so it shouldn't be the problem.
What is probably being executed is https://github.com/spastorino/rust/blob/2dece5bb62f234f5622a08289c5a3d1555cd7843/compiler/rustc_ast_passes/src/ast_validation.rs#L968-L975 as a forward incompatible lint (allow by default).
I'm not sure why this would be failing though. Would need to try things out and debug it.

**Comment by ehuss** [comment] 2024-11-04 23:52
I believe the problem is [here](https://github.com/rustwasm/wasm-bindgen/blob/f1d60abe8244eceff2d08d0e7e9b55b07a8b2e1f/crates/backend/src/codegen.rs#L1417-L1441).

wasm-bindgen is modifying the tokens of the generated extern block to use the span of the identifier from the input. That identifier will have the 2024 hygiene. Thus the entire extern block will have 2024 hygiene, and thus the validation will think it is a 2024 extern block.

I think this might need to be fixed on the wasm-bindgen side. I don't know how the edition hygiene of the item span is computed if the item is built from a mix of tokens, but I'm wondering if wasm-bindgen could not modify the span of the `extern "C" {` tokens. That is, only respan [this line](https://github.com/rustwasm/wasm-bindgen/blob/f1d60abe8244eceff2d08d0e7e9b55b07a8b2e1f/crates/backend/src/codegen.rs#L1847) and [these lines](https://github.com/rustwasm/wasm-bindgen/blob/f1d60abe8244eceff2d08d0e7e9b55b07a8b2e1f/crates/backend/src/codegen.rs#L1851-L1857), and not the surrounding stuff like `extern "C"`.

**Comment by ehuss** [comment] 2024-11-04 23:54
Another alternative solution is for wasm-bindgen to include the `unsafe` identifier if the input includes it. That way, the caller can update their `extern` block to include `unsafe`. However, `cargo fix` probably won't work with that.

**Comment by spastorino** [comment] 2024-11-05 17:23
@ehuss should we close this issue then?

**Comment by ehuss** [comment] 2024-11-05 18:29
I'm not sure, yet. We'll discuss in our call today.  Not working with wasm-bindgen I think is a pretty big deal, and will want to at least follow up to see if we can fix it on their side.

I was also wondering if it is in the realm of possibility to check the `ExpnKind` of the span to suppress the error? Do we ever do that anywhere else? Does that even fix this particular scenario?

**Comment by ehuss** [comment] 2024-11-15 20:40
I'm going to close this particular issue as resolved by https://github.com/rustwasm/wasm-bindgen/pull/4259.

As for the general problem of proc-macros re-spanning their output (particularly with `quote_spanned!` to generate better error messages), I'm going to link to my comment over at https://github.com/rust-lang/rust/issues/132963#issuecomment-2474366113. I don't know if that is fixable (I have no ideas yet), or if there are possible mitigations. I'm concerned about how common that seems to be, and it breaks our assumptions about how macros are compatible with editions.

**Closed by ehuss** 2024-11-15 20:40 UTC
Labels: C-bug, A-edition-2024, F-unsafe_extern_blocks
