### ISSUE TITLE
[1.38] Regression: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `is`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63890] opened 2019-08-25 16:46 UTC
https://github.com/rust-lang/rust/issues/63628#issuecomment-524590824

>expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `is`

```
./reg/google-games1/1.0.10+20190627/beta-2019-08-13.txt:[INFO] [stdout] error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `is`
```

Minimized reproduction, run with `rustdoc --test` (all the whitespace is important!):
```rust
/// #
///
///     ident ident
fn f() {}
```
Apparently something makes this comment look like code to `rustdoc`, so it tries to doctest it.

Actually, stable rustdoc also gives an error for this, from what I tried locally, not sure why it passed on crater.
cc @rust-lang/rustdoc 

@shepmaster explains what happens in https://github.com/rust-lang/rust/issues/63628#issuecomment-524629917.

**Comment by GuillaumeGomez** [comment] 2019-08-30 09:00
It's not a bug, it's markdown, litterally. Like @shepmaster wrote, it's considered as a code block.

**Comment by Aloso** [comment] 2019-08-31 18:13
@GuillaumeGomez it's a code block, but it's not a doctest, it might not even by Rust syntax.

Doctests can only be written with the

````markdown
```
```
````

syntax.

**Comment by GuillaumeGomez** [comment] 2019-09-02 12:10
No:

```rust
/// # Foo
///
///     let x = 12;
///
/// indeed
///
/// ``````
/// println!("foo");
/// ``````
pub fn foo() {}
```

Running with `rustdoc --test`, I had two tests.

**Comment by Mark-Simulacrum** [comment] 2019-09-19 16:05
Closing as won't fix / expected breakage.

**Closed by Mark-Simulacrum** 2019-09-19 16:05 UTC
Labels: T-rustdoc, regression-from-stable-to-beta
