### ISSUE TITLE
No warning about unnecessary `extern crate foo` items

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#25011] opened 2015-04-30 23:16 UTC
rustc warns about unnecessary `use` items, which is great. But it doesn't do the same with `extern crate foo` items.

For example, in Servo, components/net/lib.rs currently has an unnecessary `extern crate profile` item (and a corresponding `[dependencies.profile]` entry in components/net/Cargo.toml). This means the `net` crate is rebuilt unnecessarily if the `profile` crate changes.

**Comment by alexcrichton** [comment] 2015-04-30 23:56
I think this is a dupe of #24505 [where I commented](https://github.com/rust-lang/rust/issues/24505#issuecomment-93854610) that [this lint actually exists](https://github.com/rust-lang/rust/blob/master/src/librustc/lint/builtin.rs#L25-L29), it's just allow-by-default because linking to a crate is not something the compiler can 100% guarantee is a noop or not.

**Closed by alexcrichton** 2015-04-30 23:56 UTC
