### ISSUE TITLE
Rustdoc: cannot type "add_assign" into the search box

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#49115] opened 2018-03-17 16:54 UTC
This is a really strange bug. It manifests in both Firefox and Chrome.

How to reproduce:

1. Go to https://doc.rust-lang.org/nightly/std/
2. Type `add_assign` into the search box.
3. Only `add_` will show up in the box. The rest of the entered characters are ignored.

**Comment by rkruppe** [comment] 2018-03-17 18:02
Can't reproduce on Firefox 59.0.1 (64-Bit), Windows 10.

**Comment by sfackler** [comment] 2018-03-17 18:03
Seems to work for me on Chrome in Windows 10.

**Comment by bluss** [comment] 2018-03-17 18:06
I am at times having problems with typing s into the search box, and that happened when I tried to reproduce this bug as well (So you get `add_aign`). Browser Firefox 59.0.1.

**Comment by stjepang** [comment] 2018-03-17 18:17
Ok, here's some more information.

If I type `add_a` and wait for two seconds until the search results show up, then I can continue typing `ssign`. It's all good.

But if I don't wait after typing `add_a`, and just continue typing `s`, then search results will never show up. The page is simply stuck in an odd state and I cannot type in any more letters.

The only way of "fixing" it seems to be by hitting backspace and waiting for the results to show up. After that I can type `assign`.

**Comment by kennytm** [comment] 2018-03-17 19:15
Duplicate of #49075.

**Closed by kennytm** 2018-03-17 19:15 UTC
