### ISSUE TITLE
compilation stuck while resolving futures_async_stream

### ISSUE THREAD

**Issue by xxchan** [rust-lang/rust#103147] opened 2022-10-17 12:01 UTC
### Code

```
INFO rustc_trait_selection::traits::query::normalize normalize::<rustc_middle::mir::ConstantKind>: result=Ok(Val(ZeroSized, for<'a, 'b, 'c> fn(std::pin::Pin<&'a mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>>, &'b mut std::task::Context<'c>) -> std::task::Poll<std::option::Option<<futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]> as tokio_stream::Stream>::Item>> {<futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]> as tokio_stream::Stream>::poll_next})) with 4052 obligations
INFO rustc_trait_selection::traits::query::normalize normalize::<rustc_middle::ty::subst::GenericArg>: result=Ok(unsafe fn(&mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>) -> std::pin::Pin<&mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>> {std::pin::Pin::<&mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>>::new_unchecked}) with 4052 obligations
INFO rustc_trait_selection::traits::query::normalize normalize::<rustc_middle::mir::ConstantKind>: result=Ok(Val(ZeroSized, unsafe fn(&mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>) -> std::pin::Pin<&mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>> {std::pin::Pin::<&mut futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:760:5: 760:61]>>::new_unchecked})) with 4052 obligations
```

It seems that Rust is very slow with resolving futures_async_stream. It took about 1sec for each resolving. As a comparison, previous builds only have 0 obligations for all these things.

_Originally posted by @skyzh in https://github.com/risingwavelabs/risingwave/issues/5119#issuecomment-1280114090_
      
And we have located the problem occurs on this function: https://github.com/risingwavelabs/risingwave/blob/2c5bc306cb063376e3497bc27f14f80ed15a6a97/src/stream/src/executor/hash_join.rs#L604-L605

After removing the `#[for_await]` in the function body, it will compiles quickly.

I expected to see this happen: it compiles.

Instead, this happened: it got stuck.

### Version it worked on

It most recently worked on: nightly-2022-07-29

### Version with regression

`rustc --version --verbose`:
```
rustc 1.66.0-nightly (b8c35ca26 2022-10-15)
binary: rustc
commit-hash: b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1
commit-date: 2022-10-15
host: aarch64-apple-darwin
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by skyzh** [comment] 2022-10-17 13:23
Probably I'll get some easy-to-reproduce examples...

**Comment by skyzh** [comment] 2022-10-18 00:56
The difference:

```
INFO rustc_trait_selection::traits::query::normalize normalize::<rustc_middle::ty::subst::GenericArg>: result=Ok(fn(futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:604:5: 604:61]>) -> std::pin::Pin<std::boxed::Box<dyn tokio_stream::Stream<Item = <futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:604:5: 604:61]> as tokio_stream::Stream>::Item> + std::marker::Send>> {<futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:604:5: 604:61]> as futures::StreamExt>::boxed::<'_>}) with 4052 obligations
```

where in nightly-07-29

```
INFO rustc_trait_selection::traits::query::normalize normalize::<rustc_middle::ty::subst::GenericArg>: result=Ok(fn(futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:604:5: 604:61]>) -> std::pin::Pin<std::boxed::Box<dyn tokio_stream::Stream<Item = <futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:604:5: 604:61]> as tokio_stream::Stream>::Item> + std::marker::Send>> {<futures_async_stream::try_stream::from_generator::GenTryStream<[static generator@src/stream/src/executor/hash_join.rs:604:5: 604:61]> as futures::StreamExt>::boxed}) with 0 obligations
```

Note that the latest nightly has an extra `::<'_>` after `boxed`. Not sure if this is the contributing factor of so many obligations... still working on a minimum reproducible example.

**Comment by skyzh** [comment] 2022-10-18 01:52
Not related to futures_async_stream. Need investigate where are the 4000+ obligations from. cc @xxchan let's close for now until we find the root cause and submit another issue?

**Comment by skyzh** [comment] 2022-10-18 13:14
Probably has fixed by https://github.com/rust-lang/rust/pull/102945? Let's try again.

**Closed** 2022-10-18 13:41 UTC
Labels: C-bug, I-prioritize, regression-untriaged
