### ISSUE TITLE
Promote powerpc-unknown-linux-musl to Tier 2 target

### ISSUE THREAD

**Issue by halvors** [rust-lang/rust#106932] opened 2023-01-16 11:24 UTC
I was wondering why powerpc-unknown-linux-musl isn't a Tier 2 target yet, as i understand it it is very similar to the Promote powerpc-unknown-linux-gnu target, only difference is the C library

Was hoping that there could be a tracking issue for this, but somewhat unsure about whom to ask this question to.

As compiler already supports this target what is lacking here, std library support?

**Comment by est31** [comment] 2023-01-17 03:25
@halvors the relevant document can be found [here](https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html#tier-2-target-policy). It requires, among other things, a compiler team MCP and a maintainer team (at least 2 people according to the document). I suggest opening an MCP and going from there.

**Comment by halvors** [comment] 2023-01-17 08:48
@est31 Thx, but my question also is couldn't this be handled by the same compiler team etc as the already existing powerpc-unknown-linux-gnu?

I want to bring attention to this issue (to hopefully attract people that could be maintainers etc) shouldn't ideally be a tracking issue for that? is that what you mean by Major Change Proposal? How and where would i go about creating that?

**Comment by workingjubilee** [comment] 2023-01-17 11:23
The tier policy linked answers why: promoting a target from tier 3 to tier 2 increases the burden on _every PR submitted to rustc_, because after that, it is no longer acceptable to make a change that causes the target to no longer build, even if it doesn't have to pass most tests. That means it is not acceptable to not have someone who can answer questions about how it should be fixed. When a target is no longer maintainable at a higher tier, it may be demoted to tier 3, or even removed entirely. This has certainly happened before. It has even happened to tier 1 targets.

The musl targets do require additional maintenance support because they don't have the same build requirements as the GNU targets.

MCPs are described here:
https://forge.rust-lang.org/compiler/mcp.html

**Comment by jyn514** [comment] 2023-04-08 18:32
I am going to close this as not a bug; if you know someone willing to be a target maintainer for `powerpc-unknown-linux-musl` or are willing to become one, you're welcome to open an MCP.

**Closed by jyn514** 2023-04-08 18:32 UTC
