### ISSUE TITLE
Same types with same name on the same level

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#43967] opened 2017-08-17 22:13 UTC
The following code:

```rust
mod foo {
    pub use bar::*;
    pub mod bar {
        pub trait Foo {
            fn foo();
        }
    }
}

pub trait Foo {
    fn bar();
}

pub use foo::bar::*;
pub use foo::*;

fn main() {}
```

compiles perfectly. However, I think it shouldn't. How can the compiler knows which to use? And if not an error, at least a lint about this because this seems really dangerous to me.

**Comment by sdroege** [comment] 2017-08-17 22:18
This is probably fine and intended. It will fail once you try to use "Foo" unqualified, but not before that.

If it was different, a backwards compatible change in two different traits could break unrelated software: "use foo::*" and "use bar::*" in your code, both "foo" and "bar" have no conflicts. Then both decide to add a struct "Baz", but your code would be expected to continue compiling just fine unless you want to use "Baz" unqualified. In which case the compiler wouldn't know which one to use, and complain.

**Comment by GuillaumeGomez** [comment] 2017-08-17 22:21
And from my point of view this is just a horrible behaviour. Let's see what others think about it. ;)

**Comment by jonas-schievink** [comment] 2017-08-17 22:22
It won't fail if you try to use `Foo` in the root module, it uses the `Foo` from the root module. Being able to shadow glob imports has been a feature since a long time. This example complains because `Foo` is ambiguous:

```rust
mod foo {
    pub trait Foo {
        fn foo();
    }
    
    pub mod bar {
        pub trait Foo {
            fn foobar();
        }
    }
}

/*pub trait Foo {
    fn bar();
}*/

pub use foo::bar::*;
pub use foo::*;

fn _f<T: Foo>() {}

fn main() {}
```

Not a bug.

**Comment by petrochenkov** [comment] 2017-08-17 22:42
Non-globs shadow globs, that's [RFC 1560](https://github.com/rust-lang/rfcs/blob/master/text/1560-name-resolution.md).

**Comment by Mark-Simulacrum** [comment] 2019-09-01 19:54
Closing since this is expected behavior.

**Closed by Mark-Simulacrum** 2019-09-01 19:54 UTC
Labels: C-bug, I-needs-decision, T-lang
