### ISSUE TITLE
intra doc links to `std::env` render incorrectly by including `module@` disambiguator

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#75706] opened 2020-08-19 13:58 UTC
I tried this code at the suggestion of the compiler to disanbiguate between the `std::env` module and `std::env!` macro:

```rust
//! - **core-env-system** - Activates the [`module@std::env`] backend for the
//!   [`ENV` object][core-obj-env]. When this feature is disabled, access to the
//!   environ is emulated with an in-memory store.
```

I expected to see this happen: a rendered docstring like:

> core-env-system - Activates the [`std::env`](https://doc.rust-lang.org/std/env/index.html) backend for the ENV object. When this feature is disabled, access to the environ is emulated with an in-memory store.

Instead, this happened: The module disambiguator was included in the rendered docs:

> core-env-system - Activates the [`module@std::env`](https://doc.rust-lang.org/std/env/index.html) backend for the ENV object. When this feature is disabled, access to the environ is emulated with an in-memory store.

### Meta

```shell
$ cargo +nightly --version
cargo 1.47.0-nightly (ab32ee88d 2020-08-10)
[06:56] [~/dev/artichoke/artichoke]
$ rustc +nightly -Vv
rustc 1.47.0-nightly (30f0a0768 2020-08-18)
binary: rustc
commit-hash: 30f0a07684f6c1f5df62d69e9519d82e13d6bf2d
commit-date: 2020-08-18
host: x86_64-apple-darwin
release: 1.47.0-nightly
LLVM version: 10.0
[06:56] [~/dev/artichoke/artichoke]
$ rustdoc +nightly -Vv
rustdoc 1.47.0-nightly (30f0a0768 2020-08-18)
binary: rustdoc
commit-hash: 30f0a07684f6c1f5df62d69e9519d82e13d6bf2d
commit-date: 2020-08-18
host: x86_64-apple-darwin
release: 1.47.0-nightly
LLVM version: 10.0
```

**Comment by lopopolo** [comment] 2020-08-19 13:59
A workaround is to write the doc string like this:

```rust
//! - **core-env-system** - Activates the [`std::env`](module@std::env) backend
//!   for the [`ENV` object][core-obj-env]. When this feature is disabled,
//!   access to the environ is emulated with an in-memory store.
```

**Comment by jyn514** [comment] 2020-08-19 14:28
Duplicate of https://github.com/rust-lang/rust/issues/65354

**Closed by jyn514** 2020-08-19 14:28 UTC
Labels: A-intra-doc-links, C-bug, T-rustdoc
