### ISSUE TITLE
Function is not linked in docs if is has the same name as a struct and is re-exported

### ISSUE THREAD

**Issue by nwin** [rust-lang/rust#37342] opened 2016-10-22 10:12 UTC
While docs for `fn Foo` are generated in the following they are not linked anywhere and can’t be found by using the search. `fn Bar` is linked on the other hand.

``` rust
mod internal {
    pub struct Foo {
        _val: ()
    }

    #[allow(non_snake_case)] 
    pub fn Foo() -> Foo {
        Foo { _val: () }
    }   
}

pub struct Bar {
    _val: ()
}

#[allow(non_snake_case)] 
pub fn Bar() -> Bar {
    Bar { _val: () }
}

pub use internal::Foo;

fn main() {
    let _ = Foo();
    let _ = Bar();
}
```

On the other hand, when using `pub use internal::*` it works like expected. This is inconsistent as the function is clearly accessible from `fn main` in both cases.

**Comment by QuietMisdreavus** [comment] 2018-06-23 02:28
Duplicate of https://github.com/rust-lang/rust/issues/34843, which was fixed in https://github.com/rust-lang/rust/pull/51425.

**Closed by QuietMisdreavus** 2018-06-23 02:28 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
