### ISSUE TITLE
Failure to compile Rocket master using nightly

### ISSUE THREAD

**Issue by matthewrobertbell** [rust-lang/rust#81704] opened 2021-02-03 11:53 UTC
### Code
```
[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket/" }
```

```Rust
#[macro_use]
extern crate rocket;

#[get("/")]
fn hello() -> &'static str {
    "Hello, world! This is Rocket!"
}

#[launch]
fn rocket() -> rocket::Rocket {
    let port: u16 = std::env::var("PORT")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(9000);

    let figment = rocket::Config::figment()
        .merge(("address", "0.0.0.0"))
        .merge(("port", port));
    rocket::custom(figment).mount("/", routes![hello])
}

```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-apple-darwin
release: 1.51.0-nightly
LLVM version: 11.0.1
```

(This also happens on Github Actions here: https://github.com/matthewrobertbell/rocket-hello-world/runs/1798855771?check_suite_focus=true)

### Error output

```
   Compiling rocket v0.5.0-dev (https://github.com/SergioBenitez/Rocket/#c24f15c1)
error: internal compiler error: failed to process buffered lint here
  --> /Users/m/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/logger.rs:94:68
   |
94 | macro_rules! info_ { ($($args:expr),+) => { log_!(info: $($args),+); }; }
   |                                                                    ^
   |
  ::: /Users/m/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/server.rs:85:23
   |
85 |             Ok(()) => info_!("{}", Paint::green("Response succeeded.")),
   |                       ------------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
  --> /Users/m/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/logger.rs:92:70
   |
92 | macro_rules! error_ { ($($args:expr),+) => { log_!(error: $($args),+); }; }
   |                                                                      ^
   |
  ::: /Users/m/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/server.rs:86:23
   |
86 |             Err(e) => error_!("Failed to write response: {:?}.", e),
   |                       --------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

**Comment by jonas-schievink** [comment] 2021-02-03 12:17
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-03 12:17 UTC
Labels: C-bug, I-ICE, T-compiler
