### ISSUE TITLE
ReStatic ICE with nll and thread_local

### ISSUE THREAD

**Issue by robsmith11** [rust-lang/rust#51269] opened 2018-06-01 07:24 UTC
I'm getting a ICE when compiling my crate with the current nightly.  This minimal example reproduces it:

```
#![feature(nll)]
#![feature(thread_local)]

#[thread_local] static mut X1:u64 = 0;

struct S1 {
    a:&'static mut u64,
}

impl S1 {
    fn new(_x:u64) -> S1 {
        S1 { a:unsafe { &mut X1 } }
    }
}

fn main() {
    S1::new(0).a;
}
```

```
error: internal compiler error: unexpected region for local data ReStatic
  --> src/main.rs:12:30
   |
12 |         S1 { a:unsafe { &mut X1 } }
   |      
```

**Comment by robsmith11** [comment] 2018-06-01 07:40
Note that it's the argument to `S1::new()` that triggers the error.  I'm able to work around the issue by using a wrapper function with no arguments that constructs `S1` and then another function that takes arguments and modifies `S1`.

**Comment by DutchGhost** [comment] 2018-06-05 13:23
I got the exact same error with this code: 
```Rust
#![feature(nll)]

fn main() {
    let f: &'static Vec<_> = &vec![loop{}];
}
```

without nll, it fails to compile:
```
error[E0597]: borrowed value does not live long enough
 --> src/main.rs:4:31
  |
4 |     let f: &'static Vec<_> = &vec![loop{}];
  |                               ^^^^^^^^^^^^ temporary value does not live long enough
5 | }
  | - temporary value only lives until here
  |
  = note: borrowed value must be valid for the static lifetime...
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by robsmith11** [comment] 2018-06-06 13:44
So is what I wrote not supposed to be allowed (pointing a mutable static reference to a mutable static thread_local value)?

After using the function wrapper workaround, it seems to work fine and allows me to use a thread_local value all over my crate without having to use `unsafe` every time.

**Comment by nikomatsakis** [comment] 2018-06-29 20:12
We do have some special rules around `#[thread_local]` variables, yes, and I guess they haven't been ported to the MIR borrow checker. I'm not sure how that *ought* to work anyway. But I think this doesn't make the cut for an Edition Preview blocker -- going to put down as a release blocker.

**Comment by matthewjasper** [comment] 2018-07-08 09:38
The examples in this thread now compile, but it's not clear that they should.

For thead local statics are treated as going out of scope when the function ends by MIR borrowck to prevent creating a `'static` reference to them. However `static mut`s are unsafe to access, so no error is reported here.

For this example

```rust
fn main() {
    let f: &'static () = &loop {break};
}
```

In mir this looks no different to this

```rust
fn main() {
    let f: &'static (); {
        loop {break};
        f = &() // () is a constant expression, so can promote to static
    }
}
```

which should compile, but it's not clear whether we should guarantee that the first example is equivalent to this one.

**Comment by nikomatsakis** [comment] 2018-07-23 18:47
hmm, for the original example at least, the AST-based borrow checker still forbids it -- presumably beacuse the `#[thread_local]` restrictions apply regardless of whether the variable is `static` or `static mut`.

**Comment by nikomatsakis** [comment] 2018-08-08 09:39
> However static muts are unsafe to access, so no error is reported here.

I investigated briefly changing this, because I feel like I would rather have an error here than not. It's a bit tricky though. We currently ignore borrows of unsafe places -- I removed that, but then we *also* consider paths rooted in "static mut" values to not conflict with one another. I can remove that but I think it will lead to errors being reported (e.g., if you borrow a static mut more than once and those borrows overlap). 

Now, admittedly, those errors may indicate UB, so maybe that's ok.

In fact, in the *original* borrow checker, I think we ignored borrows of all statics. This would actually be a nice extension to https://github.com/rust-lang/rust/pull/53177. But in the new one, if we do that, we'll not be able to enforce the "borrows of thread locals should not outlive current fn" rules, I don't think. Huh. Annoying.

**Comment by pnkfelix** [comment] 2018-09-18 19:17
Nominating for discussion. This is a potentially subtle change to our static semantic, and I don't know if we can just push it under the umbrella of "oh well that's `unsafe` anyway" or even "oh well that's UB anyway"

**Comment by pnkfelix** [comment] 2018-09-18 19:47
Discussed at [WG-nll meeting](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/weekly.20meeting.20September.2018/near/134187789). Setting milestone to "RC2" for us to make a decision (and implement it if necessary).

**Comment by pnkfelix** [comment] 2018-09-18 19:49
(also @nikomatsakis openly mused about adding the T-lang label to this and popping it up to discussiom there... just making a note...)

**Comment by nikomatsakis** [comment] 2018-09-18 20:11
@eddyb pointed out that `#[thread_local]` is unstable. So, I think that for the purposes of NLL, we should keep the current behavior, but add comprehensive tests around `static`, `static mut`, and `#[thread_local]` applied to both of them. Then we should file a follow-up issue around what rules (if any) to put on `#[thread_local]` when applied to `static mut`

**Comment by nikomatsakis** [comment] 2018-09-19 20:50
I filed #54366 and added to the `#[thread_local]` tracking issue

**Comment by nikomatsakis** [comment] 2018-10-02 14:13
@spastorino added a regression test in https://github.com/rust-lang/rust/pull/54367, I think we can close this for now (with final resolution of the thread-local question deferred)

**Closed by nikomatsakis** 2018-10-02 14:13 UTC
Labels: A-NLL, E-needstest, I-needs-decision, NLL-sound
