### ISSUE TITLE
Unique function types are not unique enough

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#23733] opened 2015-03-26 15:29 UTC
In this example
```
trait Check: std::marker::MarkerTrait {
    fn check();
}
impl Check for u8 {
    fn check() { println!("u8"); }
}
impl Check for u16 {
    fn check() { println!("u16"); }
}

fn f<T: Check>() {
    T::check();
}



fn main() {
    fn same_type<T>(_: T, _: T) {}
    same_type(f::<u8>, f::<u16>);
    println!("{} {}", f::<u8> as usize, f::<u16> as usize);
}
```
functions `f::<u8>` and `f::<u16>` have the same type `fn() {f}` tied to the id of the generic function item, but different function pointers. So, in general case a function pointer can't be unambiguosly obtained from function item's type.

cc @nikomatsakis

**Comment by petrochenkov** [comment] 2015-03-26 16:04
Related to #19925

**Comment by nikomatsakis** [comment] 2016-01-14 21:12
Duplicate of #19925 basically, which is already P-high (but hasn't happened...sadly).

**Closed by nikomatsakis** 2016-01-14 21:12 UTC
Labels: A-traits, A-typesystem, I-nominated, T-compiler
