### ISSUE TITLE
Trait re-exports fail due to privacy of containing module

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#18241] opened 2014-10-22 20:03 UTC
This was working previously before `rustc 0.13.0-nightly (3d2cf6063 2014-10-22 00:22:04 +0000)`.

If this is an intended change, we should probably give the error where the re-export is defined and not on use of the trait.

````
use foo::Bar;

mod foo {
    pub use self::bar::Bar;
    
    mod bar {
        pub trait Bar {
            fn call(&self) -> bool;
        }
    }
}

impl foo::Bar for uint {
    fn call(&self) -> bool {
        true
    }
}

fn main() {
    println!("{}", 0u.call())
    //^~ ERROR source trait is inaccessible
}
````

**Comment by zargony** [comment] 2015-01-23 10:44
I'm facing the same problem for quite some time now (currently rustc 1.0.0-nightly (29bd9a06e 2015-01-20 23:03:09 +0000)). Is this a bug or is it intended behavior?

**Comment by steveklabnik** [comment] 2015-01-29 04:08
@nikomatsakis is this expected?

**Comment by Syntaf** [comment] 2015-10-20 04:35
Just ran into this bug in my code, would love to see a fix for this!

**Comment by zargony** [comment] 2015-10-21 08:36
Im also still running into this from time to time (rustc 1.3.0). I'd love to see it fixed or clarified whether this is intended or a bug.

**Comment by AndiDog** [comment] 2015-10-28 14:10
I also have this with rustc nightly (from PPA: "201510280406~e0e2627~wily")

**Comment by nikomatsakis** [comment] 2015-10-28 19:58
@steveklabnik I think this is a bug, actually. @nrc @alexcrichton do you agree?

**Comment by nikomatsakis** [comment] 2015-10-28 19:58
@steveklabnik yes I realize I'm responding to a comment from Jan 28 :) a bit late, I know

**Comment by Eljay** [comment] 2015-10-28 20:35
@nikomatsakis this was "fixed" by #28504 but reverted by #29325 due to a regression.

Personally, I think that the correct fix for the regression should be to make `pub trait Pub: Priv` a privacy error, but as far as I can tell, it's not easy to implement this currently, and it's likely to cause further regressions. Trait privacy is hard :(

**Comment by steveklabnik** [comment] 2015-10-28 20:55
@nikomatsakis better late than never :heart:

**Comment by alexcrichton** [comment] 2015-10-28 23:45
@nikomatsakis yeah this looks like a bug to me, and I think @Eljay is right in that #28504 is probably the right fix if we deal with `trait Pub: Priv`, which I think is the cause of some other visibility/privacy bug around here...

**Comment by sgrif** [comment] 2015-12-23 20:47
This can be simplified even further to: http://is.gd/QG9LGU. Also an additional note, this only affects usage in the same crate. Other crates are able to use the re-exports fine.

**Comment by LukasKalbertodt** [comment] 2016-01-25 09:29
Still a bug in 1.6 :cry:

**Comment by sorpaas** [comment] 2016-02-07 12:24
+1

**Comment by gbersac** [comment] 2016-02-16 18:48
still a bug in cargo 0.8.0-nightly (28a0cbb 2016-01-17)

**Comment by tomaka** [comment] 2016-03-01 13:46
For those who may fall on this issue, it can be bypassed by using the UFCS syntax: `TraitName::method(&trait_implementor, params...)`.

For example http://is.gd/QG9LGU becomes http://is.gd/zYo5Qm

**Closed** 2016-03-06 05:35 UTC
Labels: A-resolve, A-traits
