### ISSUE TITLE
"rustc_metadata::locator no metadata found" during x.py clippy

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#89934] opened 2021-10-16 03:18 UTC
while running `x.py clippy`, I noticed a bunch of warnings
`WARN rustc_metadata::locator no metadata found: failed to mmap rmeta metadata: '/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/librustc_macros-c7dd3fafd0fbc8a3.rmeta'`
that kept showing up. I never saw these during `x.py check` or `x.py build`.

What does that mean?

**Comment by petrochenkov** [comment] 2021-10-16 10:45
Duplicate of https://github.com/rust-lang/rust/issues/89795.

**Closed by petrochenkov** 2021-10-16 10:45 UTC
