### ISSUE TITLE
diagnostics: "one type is more general" for two identical types?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#75791] opened 2020-08-21 23:24 UTC
While looking through some clippy lint warnings in https://github.com/rust-lang/rust-clippy/issues/5939 I found this very confusing error message:

```rust
use std::io::{self};
use std::path::{Path, PathBuf};

pub fn main() {
    let path = &PathBuf::from("a");
    do_op(path, "remove file", std::fs::remove_file); // redundant closure
}

fn do_op<F>(path: &Path, _desc: &str, mut f: F)
where
    F: FnMut(&Path) -> io::Result<()>,
{
    match f(path) {
        Ok(()) => {}
        Err(ref _e) => {}
        Err(_e) => {}
    }
}
```

````
error[E0308]: mismatched types
 --> src/main.rs:6:5
  |
6 |     do_op(path, "remove file", std::fs::remove_file); // redundant closure
  |     ^^^^^ one type is more general than the other
  |
  = note: expected type `std::ops::FnOnce<(&std::path::Path,)>`
             found type `std::ops::FnOnce<(&std::path::Path,)>`

````
note that `expected type` and `found type` are identical which is not helpful :sweat_smile: 

This happens on 
````
rustc 1.47.0-nightly (e15510ca3 2020-08-20)
binary: rustc
commit-hash: e15510ca33ea15c893b78710101c962b11459963
commit-date: 2020-08-20
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0
````

and also on `1.46.0-beta.4`.

On stable `1.45.2`, the message looks different though:

````
error[E0631]: type mismatch in function arguments
  --> src/main.rs:6:32
   |
6  |     do_op(path, "remove file", std::fs::remove_file); // redundant closure
   |                                ^^^^^^^^^^^^^^^^^^^^
   |                                |
   |                                expected signature of `for<'r> fn(&'r std::path::Path) -> _`
   |                                found signature of `fn(_) -> _`
...
9  | fn do_op<F>(path: &Path, _desc: &str, mut f: F)
   |    ----- required by a bound in this
10 | where
11 |     F: FnMut(&Path) -> io::Result<()>,
   |        ------------------------------ required by this bound in `do_op`

error[E0271]: type mismatch resolving `for<'r> <fn(_) -> std::result::Result<(), std::io::Error> {std::fs::remove_file::<_>} as std::ops::FnOnce<(&'r std::path::Path,)>>::Output == std::result::Result<(), std::io::Error>`
  --> src/main.rs:6:5
   |
6  |     do_op(path, "remove file", std::fs::remove_file); // redundant closure
   |     ^^^^^ expected bound lifetime parameter, found concrete lifetime
...
9  | fn do_op<F>(path: &Path, _desc: &str, mut f: F)
   |    ----- required by a bound in this
10 | where
11 |     F: FnMut(&Path) -> io::Result<()>,
   |                        -------------- required by this bound in `do_op`
````

**Comment by Dylan-DPC** [comment] 2020-08-25 23:27
Marking this as P-high based on the [wg-prioritization discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2375791.20diagnostics.3A.20.22one.20type.20is.20more.20general.22.E2.80.A6)

**Comment by matthiaskrgr** [comment] 2020-08-26 09:24
I tried to get cargo-bisect-rustc to work and it seems the regression merge is 1557fb031b272b4c5bfcc7de5df7eddc7b36a584

**Comment by nikomatsakis** [comment] 2020-08-27 14:49
This is almost certainly due to #72493. The error seems legit, as discussed [here](https://zulip-archive.rust-lang.org/238009tcompilermeetings/49871weeklymeeting2020082754818.html#208226050). The error *message* is quite misleading, what's really happening is that the type of `std::fs::remove_file` doesn't implement `for<'a> FnMut(&'a Path)` but just `FnMut(&'b Path)` for some `'b`. We have some specializd diagnostic paths to try and express this more clearly but they are not triggering here for reasons I'm not entirely sure of.

**Comment by pnkfelix** [comment] 2020-09-03 14:42
discussed in T-compiler meeting. Assigning to @estebank to see if they can make progress on it over next week. Also nominating to ensure we circle back around to it next week if progress *isn't* made

**Comment by spastorino** [comment] 2020-09-03 14:49
Is this one a stable regression now?, also is it the same as https://github.com/rust-lang/rust/issues/74400 ?

**Comment by lqd** [comment] 2020-09-03 16:10
yes that's on [stable now](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=949c55a051453a5d0934f0cfc18a91a9)

**Comment by lqd** [comment] 2020-09-03 20:19
and to answer the question: both are indeed duplicates of each other, they are higher-ranked subtype errors involving placeholder regions. NLL's nice region error reporting code doesn't kick in because [it handles TraitRefs](https://github.com/rust-lang/rust/blob/3edf11cf811707cde49b30a80896c24189649d95/compiler/rustc_infer/src/infer/error_reporting/nice_region_error/placeholder_error.rs#L30-L48) while these are PolyTraitRefs.

**Comment by estebank** [comment] 2020-09-04 01:11
I can get the following output:

```
error: implementation of `std::ops::FnOnce` is not general enough
   --> fil3.rs:6:5
    |
6   |       do_op(path, "remove file", std::fs::remove_file); // redundant closure
    |       ^^^^^ doesn't satisfy where-clause
    |
   ::: /Users/ekuber/workspace/rust/library/core/src/ops/function.rs:219:1
    |
219 | / pub trait FnOnce<Args> {
220 | |     /// The returned type after the call operator is used.
221 | |     #[lang = "fn_once_output"]
222 | |     #[stable(feature = "fn_once_output", since = "1.12.0")]
...   |
227 | |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
228 | | }
    | |_- trait `std::ops::FnOnce` defined here
    |
note: due to this where-clause on `do_op`...
   --> fil3.rs:11:24
    |
11  |     F: FnMut(&Path) -> io::Result<()>,
    |                        ^^^^^^^^^^^^^^
    = note: ...`std::ops::FnOnce<(&'1 std::path::Path,)>` would have to be implemented for the type `fn(&std::path::Path) -> std::result::Result<(), std::io::Error> {std::fs::remove_file::<&std::path::Path>}`, for any lifetime `'1`...
    = note: ...but `std::ops::FnOnce<(&'2 std::path::Path,)>` is actually implemented for the type `fn(&'2 std::path::Path) -> std::result::Result<(), std::io::Error> {std::fs::remove_file::<&'2 std::path::Path>}`, for some specific lifetime `'2`
```

But I feel it is not yet ideal.

**Comment by lqd** [comment] 2020-09-04 07:55
Is there enough information at this point of type-checking to output either previous errors (or both ? the E0631 seems more user-friendly, but these spans look more like the previous E0271), so that even if the message doesn't improve it at least doesn't regress anymore ? 

Maybe having the previous signatures would be clearer ?
```
expected signature of `for<'r> fn(&'r std::path::Path) -> _`
   |                                found signature of `fn(_) -> _`
```

I wonder how we should explain these kinds of errors, maybe linking to closures/Fn* documentation, suggesting wrapping in a closure (but that doesn't always work). Maybe those suggestions are also too tailored to these 2 specific issues but higher-ranked subtyping errors could be arbitrarily complicated.

**Comment by spastorino** [comment] 2020-09-09 20:31
Adding `T-compiler` label so this can be picked up by our automated prioritization tool and added to the following `T-compiler` weekly meeting agenda.

**Comment by spastorino** [comment] 2020-09-17 15:02
This [was discussed on today's compiler weekly meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/80943weeklymeeting2020091754818.html#210401890)

**Comment by solson** [comment] 2020-10-30 13:24
I hope this is the right place for this — it seems like all relevant issues are getting closed as duplicates of this one. For reference, here is more minimal reproduction of the problem, from @khyperia:

```rust
fn thing(x: impl FnOnce(&u32)) {}

fn main() {
    let f = |_| ();
    thing(f);
}
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1e1e6e3859a058319f1c065fd92eb5b1)

It can be worked around like this:

```rust
fn thing(x: impl FnOnce(&u32)) {}

fn main() {
    let f = |_: &_| ();
    thing(f);
}
```

**Comment by estebank** [comment] 2021-09-30 16:42
Current output:

```
error: implementation of `FnOnce` is not general enough
 --> src/main.rs:6:5
  |
6 |     do_op(path, "remove file", std::fs::remove_file); // redundant closure
  |     ^^^^^ implementation of `FnOnce` is not general enough
  |
  = note: `fn(&'2 Path) -> Result<(), std::io::Error> {remove_file::<&'2 Path>}` must implement `FnOnce<(&'1 Path,)>`, for any lifetime `'1`...
  = note: ...but it actually implements `FnOnce<(&'2 Path,)>`, for some specific lifetime `'2`

```

```
error: implementation of `FnOnce` is not general enough
 --> src/main.rs:5:5
  |
5 |     thing(f);
  |     ^^^^^ implementation of `FnOnce` is not general enough
  |
  = note: closure with signature `fn(&'2 u32)` must implement `FnOnce<(&'1 u32,)>`, for any lifetime `'1`...
  = note: ...but it actually implements `FnOnce<(&'2 u32,)>`, for some specific lifetime `'2`
```

I think this might be a duplicate of https://github.com/rust-lang/rust/issues/71723

**Comment by jackh726** [comment] 2022-02-03 04:54
Closing as a duplicate of #71723

**Closed by jackh726** 2022-02-03 04:54 UTC
Labels: A-diagnostics, A-lifetimes, P-high, T-compiler, regression-from-stable-to-stable, C-bug
