### ISSUE TITLE
Error compiling mongodb crate with Nightly

### ISSUE THREAD

**Issue by alosarjos** [rust-lang/rust#81640] opened 2021-02-01 20:30 UTC
Just compile an empty lib with the mongodb library pointing to 1.1.1 version (Latest stable). This was working with Nigtly before updating today, but I don't know from when the working version was (Haven't updated in a while)

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1

```

### Error output

```
error: internal compiler error: failed to process buffered lint here
   --> /home/alosarjos/.cargo/registry/src/github.com-1ecc6299db9ec823/mongodb-1.1.1/src/coll/mod.rs:227:23
    |
227 |           pipeline.push(doc! {
    |  _______________________^
228 | |             "$group": {
229 | |                 "_id": 1,
230 | |                 "n": { "$sum": 1 },
231 | |             }
232 | |         });
    | |_________^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /home/alosarjos/.cargo/registry/src/github.com-1ecc6299db9ec823/mongodb-1.1.1/src/coll/mod.rs:227:23
    |
227 |           pipeline.push(doc! {
    |  _______________________^
228 | |             "$group": {
229 | |                 "_id": 1,
230 | |                 "n": { "$sum": 1 },
231 | |             }
232 | |         });
    | |_________^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: rust_begin_unwind
             at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run

```

</p>
</details>

**Comment by alosarjos** [comment] 2021-02-01 20:33
Compiling with stable works fine:

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

**Comment by jonas-schievink** [comment] 2021-02-01 20:34
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-01 20:34 UTC
Labels: C-bug, I-ICE, T-compiler
