### ISSUE TITLE
how can i upgrade a Weak<UnsafeCell<T>> to a Arc<UnsafeCell<T>>?

### ISSUE THREAD

**Issue by egmkang** [rust-lang/rust#21802] opened 2015-01-31 08:53 UTC
```rust
let arc = Arc::new(UnsafeCell::new(10i32));
let weak = arc.downgrade();
let arc2 = weak.upgrade();
```
compiler tell me:
error: type `alloc::arc::Weak<core::cell::UnsafeCell<i32>>` does not implement any method in scope named `upgrade`

how can i solve this problem?

**Comment by cybergeek94** [comment] 2015-01-31 09:15
This is because `UnsafeCell` does not implement `Send` nor `Sync`, both of which are required for `Weak::upgrade()`. `UnsafeCell` is not meant to be used across threads and thus cannot be used this way.

If you don't need to send the `UnsafeCell` across threads then you can use `Rc` instead of `Arc`, which does not have these requirements and can be used with `UnsafeCell`. Otherwise, you should probably use the safe interfaces exposed by `Mutex` and `RWLock`.

**Comment by egmkang** [comment] 2015-01-31 09:49
You mean i cannot use UnsafeCell/RefCell to implement a cpp style shared_ptr, because which cannot work through threads?
But if i want a container like `Key =>  shared_ptr<Value>`, how can i solve this problem in rust?

**Comment by cybergeek94** [comment] 2015-01-31 10:02
`Arc` itself does basically what `shared_ptr` does, however you have to keep in mind that it will not give you a mutable reference to the object. `shared_ptr` is an unsafe, racy construct that has little use in safe Rust. If you want to access an object mutably across threads you'll want a `Mutex` wrapped in an `Arc`.

**Comment by egmkang** [comment] 2015-01-31 10:11
yes. threads modify one object is not safe; but threads copy one shared_ptr/weak_ptr object is thread safe.

**Comment by steveklabnik** [comment] 2015-01-31 10:24
I am giving this issue a close, because it is not a bug.

I would suggest moving this discussion to users.rust-lang.org or StackOverflow, thank you!

**Closed by steveklabnik** 2015-01-31 10:24 UTC
