### ISSUE TITLE
Into::into possibly unsound for SIMD

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#46682] opened 2017-12-12 11:15 UTC
See: https://github.com/rust-lang-nursery/stdsimd/pull/233

Basically SIMD code in the wild prefers to use the more convenient `.into()` over `_::from(x)` everywhere (e.g. see [gimli](https://github.com/quininer/gimli/blob/5f512d1cbb5c38a915ee8758be436754f3f19be3/gimli-permutation/src/sse.rs#L30)) to convert between the different SIMD types.

The problem is that while:

```rust
#[target_feature = "+avx"]
unsafe fn from_passes() {
    let a = i64x4::new(
        4611686019492741120, 4647714816524288000,
        4665729215040061440, 4683743613553737728
    );
    let e = f32x8::new(1., 2., 3., 4., 5., 6., 7., 8.);
    // this always works:
    let r = _mm256_castsi256_ps(__m256i::from(a));
    assert_eq!(e, r);
}

fn main() {
    if !cfg_feature_enabled("avx") { return; }
    unsafe { from_passes() }
}
```

always works, replacing that `__m256i::from(a)` with `a.into()` segfaults on some targets (e.g. `i586-unknown-linux-gnu`):

```rust
#[target_feature = "+avx"]
unsafe fn into_fails() {
    let a = i64x4::new(
        4611686019492741120, 4647714816524288000,
        4665729215040061440, 4683743613553737728
    );
    let e = f32x8::new(1., 2., 3., 4., 5., 6., 7., 8.);
    // this segfaults on some targets:
    let r = _mm256_castsi256_ps(a.into());
    assert_eq!(e, r);
}

fn main() {
    if !cfg_feature_enabled("avx") { return; }
    unsafe { into_fails() }
}
```

The only difference between `From::from` and `Into::into` seems to be that the implementations of `From::from` for the SIMD types are `#[inline(always)]` while the default implementation of `Into::into` is "just" `#[inline]`.

It is unclear to me whether this "segfaulting" is reliable or just a symptom of unsoudness / undefined behavior. Some SIMD intrinsics rely on inlining for good codegen, but until now the consequences of bad codegen were only degraded performance as opposed to different program semantics or undefined behavior.

While LTO / ThinLTO might help here, we probably don't want to introduce unsoundness in the binaries of those users that don't want to/can use any of these.

**Comment by gnzlbg** [comment] 2017-12-12 11:32
The only two ideas I've had that can possibly fix in some cases are: 

- making the blanket impl of `Into::into` for `From` `#[inline(always)]` instead of `#[inline]` (because `Into::into` is tiny and its intent is to transparently dispatch to an implementation of `From`).
- making the blanket impl of `Into::into` for `From` `default` so that `stdsimd` can implement specializations marked `#[inline(always)]` for the SIMD types (because the previous solution might incur a non-trivial compile-time, binary size, ... cost).

However, I don't think any of these approaches will work if one puts a SIMD type behind an `Into<__m256i>` a trait object:

```rust
fn now_what(x: Box<Into<__m256i>>) {
    if !cfg_target_feature!("avx") { return; }
    unsafe { _mm256_castsi256_ps(x.into()) }; // unsound ?
}
```

**Comment by jonas-schievink** [comment] 2017-12-12 12:03
There's no unsoundness involved, this is just bad codegen, right? Why not fix that instead of regressing compile times of almost every crate ever written? Even the `#[inline(always)]` on the `From` impls seems to much, a normal `#[inline]` should suffice.

**Comment by gnzlbg** [comment] 2017-12-12 12:17
> Why not fix that instead of regressing compile times of almost every crate ever written?

I share your concerns about this and I don't know its impact: `Into::into` is already `#[inline]` and a one liner so I wouldn't be surprised if it is already being inlined almost anywhere anyways already. Since this solution has downsides I'd very much prefer a solution without downsides.

**Comment by jonas-schievink** [comment] 2017-12-12 12:23
Inlining calls to `.into()` is perfectly fine in release mode, but `#[inline(always)]` instructs LLVM to **always** inline, even in debug mode. Technically, this is still just a hint and there's no guarantees that it will actually happen (IIRC), but in practice LLVM will inline those calls if no recursion is involved (as that would result in an infinite amount of code).

**Comment by parched** [comment] 2017-12-12 19:32
Isn't this just https://github.com/rust-lang/rust/issues/44367?

**Comment by alexcrichton** [comment] 2017-12-13 05:29
Yes I believe so

**Comment by alexcrichton** [comment] 2017-12-16 16:23
Closing as a dupe of #44367

**Closed by alexcrichton** 2017-12-16 16:23 UTC
Labels: A-simd, C-bug, I-crash

**Comment by gnzlbg** [comment] 2017-12-18 12:22
@parched yes I think so, I thought I had other types of failures, but I can't reproduce them.
