### ISSUE TITLE
Lifetime error when using `Self` instead of `<StructName>`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#66176] opened 2019-11-07 02:15 UTC
The following code compiles:

```rust
struct MyStruct<'a> {
    val: &'a bool
}

impl<'a> MyStruct<'a> {
    fn make_new() {
        let new_val = true;
        let my_val = MyStruct { val: &new_val };
    }
}
```

However, changing `MyStruct { val: &new_val }` to `Self { val: &new_val }`:

```rust
struct MyStruct<'a> {
    val: &'a bool
}

impl<'a> MyStruct<'a> {
    fn make_new() {
        let new_val = true;
        let my_val = Self { val: &new_val };
    }
}
```

gives the following error:

```
error[E0597]: `new_val` does not live long enough
 --> src/lib.rs:8:34
  |
5 | impl<'a> MyStruct<'a> {
  |      -- lifetime `'a` defined here
...
8 |         let my_val = Self { val: &new_val };
  |                                  ^^^^^^^^
  |                                  |
  |                                  borrowed value does not live long enough
  |                                  requires that `new_val` is borrowed for `'a`
9 |     }
  |     - `new_val` dropped here while still borrowed
```

Minimized from https://github.com/rust-lang/rust/issues/65897#issuecomment-550575678 (specifically, [bcder v0.1.0](https://crater-reports.s3.amazonaws.com/pr-65897-1/try%235e633973aa9255a88b65a39484627bb54e6044b3/gh/mfontanini.rpki-validator/log.txt) ([github](https://github.com/NLnetLabs/bcder/blob/f535db98939c77a0de281dfeea291a625f434a3b/src/decode/content.rs#L381)))

**Comment by Centril** [comment] 2019-11-07 08:29
Seems like the error is correctly emitted in this case.

When we write `Self`, we really mean `MyStruct<'a>` with that lifetime argument applied to the parameter. In particular, we expect `&'a bool`. We have `&new_val` which is of type `&'0 new_val` but we cannot prove that `'0 <: 'a` and so therefore `Self { val: &new_val }` is ill-typed.

The same error message can be seen if we use `MyStruct::<'a>` directly:

```rust
struct MyStruct<'a> {
    val: &'a bool
}

impl<'a> MyStruct<'a> {
    fn make_new() {
        let new_val = true;
        let my_val = MyStruct::<'a> { val: &new_val };
        //~^ ERROR `new_val` does not live long enough
    }
}
```

**Comment by Aaron1011** [comment] 2019-11-07 14:31
That seems extremely counterintuive to me - I would expect `Self` to just refer to the type name.

At a minimum, I think we should add something to the error message to indicate that this is going on (I assume changing the expansion of `Self` would be a breaking change)

**Comment by eddyb** [comment] 2019-11-07 14:35
I wrote a longer message but then I noticed this:
The example provided does *not* compile on stable, and the linked crater failure involves `Self::new(...)` calls, *not* `Self {...}` struct creation syntax.

> I would expect `Self` to just refer to the type name

It never did, in any position. It's always a fully applied type and `Self<...>` never works.
It would be quite less useful in several situations if it were just the name.
For example, the common case of `fn new() -> Self`.

**Comment by pnkfelix** [comment] 2019-11-07 14:36
triage: closing as not a bug.

**Closed by pnkfelix** 2019-11-07 14:36 UTC
Labels: A-NLL, A-lifetimes, T-compiler, regression-from-stable-to-beta

**Comment by Centril** [comment] 2019-11-07 14:39
> At a minimum, I think we should add something to the error message to indicate that this is going on (I assume changing the expansion of `Self` would be a breaking change)

Might be difficult, but worth if not too intrusive? If so, a new issue should probably be opened for that aspect.
