### ISSUE TITLE
intra-doc links: `crate::` considers the traits in the crate scope, not the current scope

### ISSUE THREAD

**Issue by pitaj** [rust-lang/rust#78696] opened 2020-11-03 05:13 UTC
I tried this code:

```rust
#![allow(unused_imports, dead_code)]

// Uncomment this and the warning will go away
// use crate::io::Read;

pub mod io {
    pub trait Read {
        fn read(&mut self, buf: &mut [u8]) -> usize;
    }
}

pub mod bufreader {
    use crate::io::Read;

    /// It can be excessively inefficient to work directly with a [`Read`] instance.
    /// For example, every [`Read::read`] call to [`TcpStream::read`] or [`TcpStream::yes`] on [`TcpStream`]
    ///
    /// [`TcpStream::yes`]: crate::net::TcpStream::yes
    /// [`TcpStream::read`]: crate::net::TcpStream::read
    /// [`Read::read`]: Read::read
    /// [`TcpStream`]: crate::net::TcpStream
    pub struct BufReader;
}

pub mod net {
    pub struct TcpStream;

    impl TcpStream {
        fn yes() -> bool {
            true
        }
    }

    impl crate::io::Read for TcpStream {
        fn read(&mut self, buf: &mut [u8]) -> usize {
            buf.len()
        }
    }
}
```

I expected to see this happen: Rustdoc should complete with no warnings

Instead, this happened:

Only the following warning is output by rustdoc
```sh
warning: unresolved link to `self::net::TcpStream::read`
  --> src/main.rs:13:30
   |
13 |     /// [`TcpStream::read`]: crate::net::TcpStream::read
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the struct `TcpStream` has no field or associated item named `read`
   |
   = note: `#[warn(broken_intra_doc_links)]` on by default
```

If you uncomment the line as it says, the warning goes away.

### Meta

`rustc +stage2 --version --verbose`:
```
rustc 1.49.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.49.0-dev
```

Commit hash: b2025326088b54fb3f083bebeba14e0a15bf00d3

Here's a crate that repros this issue: https://github.com/pitaj/rustdoc-78006-repro

@rustbot modify labels: T-doc, A-intra-doc-links

@jyn514 Here's the repro I promised.

First came across this in #78006

**Comment by jyn514** [comment] 2020-11-03 05:22
Slightly smaller:

```rust
// Uncomment this and the warning will go away
// use crate::io::Read;

pub mod io {
    pub trait Read {
        fn read(&mut self);
    }
}

pub mod bufreader {
    use crate::io::Read;

    /// [`crate::TcpStream::read`]
    pub struct BufReader;
}

pub struct TcpStream;

impl crate::io::Read for TcpStream {
    fn read(&mut self) {
    }
}
```

**Comment by jyn514** [comment] 2020-11-03 05:24
The issue is that rustdoc thinks the trait isn't in scope for some reason:

```
2:rustcDEBUG rustdoc::passes::collect_intra_doc_links looking for associated item named read for item DefId(0:8 ~ impl[8787]::TcpStream)
2:rustcDEBUG rustdoc::passes::collect_intra_doc_links considering traits {}
2:rustcDEBUG rustdoc::passes::collect_intra_doc_links the candidates were []
2:rustcDEBUG rustdoc::passes::collect_intra_doc_links got associated item kind None
2:rustcDEBUG rustdoc::passes::collect_intra_doc_links self::TcpStream::read resolved to Err(()) in namespace ValueNS
```

**Comment by jyn514** [comment] 2020-11-03 05:26
Because it's resolving the scope of the crate, because of the hack I did to fix `crate::` across crates: https://github.com/rust-lang/rust/pull/77253. If you use `super::TcpStream::read` instead, it works fine.

**Comment by jyn514** [comment] 2020-11-03 05:29
@pitaj you could get https://github.com/rust-lang/rust/pull/78006 working by using super instead for now.

**Comment by jyn514** [comment] 2020-11-05 01:19
@petrochenkov how hard would it be to allow `$crate` in `resolve_str_path_error`? Rustdoc has both the original and current scope available, but right now it can only pass one or the other to resolve.

Using $crate would fix this issue and also some other hacks in rustdoc (see the PR above).

**Comment by petrochenkov** [comment] 2020-11-05 08:41
`resolve_str_path_error` should already support `$crate` internally, but rustdoc passing path as a string (without span) will mean that `$crate` will always resolve to the current crate. Resolve needs correct spans to perform resolution in cases like this.

**Comment by jyn514** [comment] 2020-11-05 17:41
Mentoring instructions: everywhere that currently calls `resolve_str_path_error` with `DUMMY_SP` needs to instead pass the span of the item. You can get the span from [`item.source`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/struct.Item.html#structfield.source). `fn resolve` needs to be changed to take the span as a parameter:

https://github.com/rust-lang/rust/blob/b385598c9658fef4a143a770c21db38b7872c134/src/librustdoc/passes/collect_intra_doc_links.rs#L1190

There are many different calls to `resolve_str_path_error` and not all of them go through `fn resolve`; those will need to be updated as well.

**Comment by petrochenkov** [comment] 2022-03-26 17:24
Fixed in https://github.com/rust-lang/rust/pull/95337.

**Closed** 2022-04-05 06:59 UTC
Labels: T-rustdoc, E-mentor, E-medium, C-bug, A-intra-doc-links
