### ISSUE TITLE
Clean up toggle logic in rustdoc

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#83332] opened 2021-03-21 00:05 UTC
I was working on https://github.com/rust-lang/rust/issues/82114 and discovered that the toggle logic is written scattered all throughout `main.js`. This seems suboptimal; I'd rather not be _generating_ HTML in main.js. A lot of the toggle logic does things like check the classes of nearby items, etc, which seems super brittle.

I propose we move the toggle logic to Rust code instead; writing a `wrapToggle()` method that wraps some HTML in a toggle.

Thoughts? @rust-lang/rustdoc 

Might be worth creating a meta issue for reducing the size of main.js in general. We seem to do a fair amount of additional codegen there, not just for toggles.

**Comment by Manishearth** [comment] 2021-03-21 01:41
Also the way toggles are handled is a global click event that bubbles down. There's a very complicated `collapseDocs` function that has a whole bunch of special logic, and furthermore the global click event handler basically reimplements a broken version of bubbling.

It feels to me that adding a toggle should just be a matter of wrapping the relevant block in a toggle div + toggle, and at runtime we simply need to hook up event listeners.

**Comment by Manishearth** [comment] 2021-03-21 01:44
Also there are a whole bunch of hardcoded pixel values in the css that guess the sizes of toggle buttons. We ... shouldn't be doing that.

**Comment by Manishearth** [comment] 2021-03-21 01:45
Overall the toggle code needs a _major_ refactor, I think. I can make my changes without such a refactor but I think we need to redo the JS/CSS side of this entirely.

**Comment by camelid** [comment] 2021-03-21 01:46
> I propose we move the toggle logic to Rust code instead; writing a `wrapToggle()` method that wraps some HTML in a toggle.

I am definitely 👍 on moving JS code to Rust.

> Might be worth creating a meta issue for reducing the size of main.js in general. We seem to do a fair amount of additional codegen there, not just for toggles.

Yeah, `main.js` is pretty complicated. It would be great to simplify it and move more to Rust.

> Also there are a whole bunch of hardcoded pixel values in the css that guess the sizes of toggle buttons.

Hmm, what does that mean?

**Comment by Manishearth** [comment] 2021-03-21 01:51
> > Also there are a whole bunch of hardcoded pixel values in the css that guess the sizes of toggle buttons.
> 
> Hmm, what does that mean?


[This](https://github.com/rust-lang/rust/blob/61edfd591cedff66fca639c02f66984f6271e5a6/src/librustdoc/html/static/rustdoc.css#L976) is used to keep the toggle block the same size. [This](https://github.com/rust-lang/rust/blob/61edfd591cedff66fca639c02f66984f6271e5a6/src/librustdoc/html/static/rustdoc.css#L1042-L1046) seems to be related to attribute rendering but I can't be sure since I can't get rustdoc to render any attributes on enum variants or struct fields.

Those pixel values are roughly the size of the little +. We should never be doing this.

**Comment by camelid** [comment] 2021-03-21 02:02
> but I can't be sure since I can't get rustdoc to render any attributes on enum variants or struct fields.

That CSS that you linked to uses `.enum > .toggle-wrapper` and `.struct > .toggle-wrapper` which IIUC means it will only apply to toggle wrappers that are direct children of `.enum`s or `.struct`s. Is that why you can't get it rendering or is it unrelated?

**Comment by Manishearth** [comment] 2021-03-21 02:05
It was just an example, there are lots of manual margins throughout to make abspos on the toggle wrappers work right, and I don't think it should be necessary?

**Comment by camelid** [comment] 2021-03-21 02:05
> Those pixel values are roughly the size of the little +. We should never be doing this.

Ah, I see what you mean. When I turn off the `height: 25px` in dev tools I get:

![image](https://user-images.githubusercontent.com/37223377/111891301-2bad6c80-89af-11eb-8447-6bb0bc12a0be.png)

You're right, this code really does need refactoring!

**Comment by camelid** [comment] 2021-03-21 02:08
So what do you think we should start with to clean this up?

**Comment by Manishearth** [comment] 2021-03-21 03:20
I think we should first come up with a plan as to how it should work, get that reviewed by the team, and then work on it.

A very rough plan is:

 - Tear out all JS toggle code. Perhaps all CSS as well.
 - Anything that needs to be toggled should be wrapped in `<div class=toggle-wrap data-toggle-text="Show foobar">` during Rust code generation. I kinda think this should always be a separate div so that we can have `toggle_start` and `toggle_end` in Rust, but I guess mixing it with other divs may be okay too. I'd prefer not to.
 - We use a couple direct-descendant CSS selectors (`>`) where we shouldn't. These will break, fix them
   - Make sure this div renders cleanly
 - Add very simple JS code that iterates through all of these and adds a toggle button sibling. There should be no special cases in this code. The codegen can later be moved into `toggle_start` in Rust if we want.
 - Get this sibling to render correctly. All special cases should be handled by adding additional classes to the `toggle-wrap` element and using CSS, so we could have things like `toggle-wrap toggle-section` or whatever.
 - Make the above JS hook up an event listener that can find the element to be toggled, and toggle it
 - Make the above JS set defaults based on settings. We should use another css class for indicating which setting to pull from.
 - The show/hide all button just does a `getElementsByClassName` to do its thing.

**Comment by GuillaumeGomez** [comment] 2021-03-21 13:17
As extra information: we have four kind of toggles iirc:
 * For documentation blocks
 * For items' inner content (fields and variants for example)
 * For attributes
 * For default elements on implemented traits

I opened an issue to improve the toggles for the documentation blocks already (here: https://github.com/rust-lang/rust/issues/56442). Currently, the documentation follows the item it documents. In my idea, it could be simplified by making it a child of the item instead (in the DOM). Then we could eventually try to handle the toggle through CSS only, which would allow us to remove a lot of JS.

I didn't look for the other toggles yet.

**Comment by Manishearth** [comment] 2021-03-21 14:38
Yeah restructuring toggles to be inside a wrapping element would be very good. We should unify these types of toggles so that their mechanism is exactly the same (but their css might be slightly different)

**Comment by GuillaumeGomez** [comment] 2021-03-21 14:42
Well, it's been in my TODO list for a while. :laughing:

**Comment by Manishearth** [comment] 2021-03-21 14:44
Sounds good, I think if we're going to refactor this we should have a concrete plan in the issue before moving ahead though.

**Comment by GuillaumeGomez** [comment] 2021-03-21 14:50
The "only" thing missing is how to do it with CSS only. Someone suggested it but I didn't investigate it yet. Once we have a solution for this, we can go to the next step.

Here is what I have in mind: we keep the current DOM but move the "docblock" elements into the element they document, as simple as that. From what I tested, it seems to be working as is but to be confirmed once again, I tested a while ago after all and some DOM changes happened in the meantime, but I think it'll still work. The only changes required would then be in the CSS once again and to check that there is no difference in the rendering.

What we can do is maybe split the work between each kind of toggle and then merge the CSS at the end? I don't think we can merge all of them though. For example, I think that the types' fields/variants' toggles will still remain on their own. Only the logic will be the same.

I expect a huge reduction of JS after this change. It would bring a huge improvement in the rendering speed.

**Comment by GuillaumeGomez** [comment] 2021-03-21 14:53
Well, it was easy enough to find: https://stackoverflow.com/a/17731854

I can send a first PR for the "normal" doc blocks then so we can have a base to discuss on.

**Comment by Manishearth** [comment] 2021-03-22 05:45
> What we can do is maybe split the work between each kind of toggle and then merge the CSS at the end? I don't think we can merge all of them though. For example, I think that the types' fields/variants' toggles will still remain on their own. Only the logic will be the same.

Honestly given the state of the code I'd prefer if we did it from scratch.

> For example, I think that the types' fields/variants' toggles will still remain on their own. Only the logic will be the same.

What do you mean? Yes, the code generating them will be in different spots, and their CSS will be different, but any relevant JS should be the same I think.

**Comment by Manishearth** [comment] 2021-03-22 05:46
> EDIT: Well, got super motivated and actually started the implementation. More to come soon.

Can you write a concrete plan first? I'm worried we'll do something similarly hard to work with. Though if it makes all the JS go away I guess it's fine either way.

**Comment by jsha** [comment] 2021-04-19 01:03
Update on the plan: @GuillaumeGomez started work on the HTML-ification in #83355. I did some additional work setting up CSS to use `<details>` in place of the current JS toggles, and landed that as part of @Manishearth's #83337. I think we have general consensus that turning the JS toggles into `<details>` tags is the way to go.

I've got one PR open (#84320) converting one more set of toggles to `<details>`, and @Swatinem has one for sub-variants (#84321). I think the best path forward is to do these one chunk at a time, which allows more attention and testing on each one. I plan to do some more of the chunks as I have time, and will plan to post here when starting on the next chunk to avoid duplicated effort.

One open question: I've noticed there are some toggle types (undocumented items; sub-variants) that don't have corresponding settings entries. Should we add settings for these or (my preference) group them under some other setting?

**Comment by Manishearth** [comment] 2021-04-19 03:37
Thanks for taking point on this, @jsha!

Overall I don't think every toggle must have a config option, rather config options are useful when asked for. Otherwise having lots  of niche configs can be pretty confusing, indeed a lot of folks used to be confused by our hyperspecific toggle settings before.

So basically: don't add a config unless someone asks, and if someone asks figure out if it their needs can be met without a config (but if not, nbd, just add it)

**Comment by Nemo157** [comment] 2021-04-19 09:56
Has there been a check on how the `<details>` looks on iOS Safari? IIRC it doesn't allow hiding the default ➤ toggle button.

**Comment by jsha** [comment] 2021-04-19 16:23
I checked safari on iPad OS 1.13 and the toggle is displayed correctly.

**Comment by GuillaumeGomez** [comment] 2021-04-19 16:50
Can someone check on an iPhone too? It's on this platform specifically that we encountered the most issues.

**Comment by Nemo157** [comment] 2021-04-19 17:37
I checked on an iPhone, it is suppressing the default toggle button because of the inherited `list-style-type` (at least on the changes from #84320).

**Comment by GuillaumeGomez** [comment] 2021-04-19 18:54
So I guess it's all good. :)

**Comment by jsha** [comment] 2021-04-20 03:02
Remaining things with toggles to port to `<details>`:

 - [ ] methods
 - [ ] trait implementations
 - [ ] trait implementors (#84320)
 - [ ] sub-variants of an enum (#84321)
 - [ ] associated constants
 - [ ] the documentation for non-exhaustiveness ([e.g. on ErrorKind](https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html#variants))
  - [ ] undocumented / default items in trait implementation / implementor documentation (#84326)

**Comment by jyn514** [comment] 2021-04-20 03:17
>  the documentation for non-exhaustiveness (e.g. on ErrorKind)

I think we should fix this by removing the documentation about what `#[non_exhaustive]` is and linking to the official docs instead: https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute

**Comment by jsha** [comment] 2021-04-20 04:41
Let's have some more discussion about how to handle `#[non_exhaustive]` and other attributes over at #84309, where we already had a bit of the conversation.

**Comment by GuillaumeGomez** [comment] 2021-04-28 16:26
Currently working on methods and trait implementations.

**Comment by GuillaumeGomez** [comment] 2021-05-03 19:22
I updated https://github.com/rust-lang/rust/issues/83332#issuecomment-822937616. So now only remains two things: 

* the documentation for non-exhaustiveness (e.g. on ErrorKind - see discussion on #84309)
* the global doc comment

**Comment by GuillaumeGomez** [comment] 2021-05-08 11:42
Working on the two last points.

**Comment by jsha** [comment] 2021-05-09 20:30
The main refactoring (switching to `<details>`) is close to finished. I wanted to follow up on a couple of other points @Manishearth made early in this issue. Click handlers and bubbling are fixed in https://github.com/rust-lang/rust/pull/85117.

> there are a whole bunch of hardcoded pixel values in the css that guess the sizes of toggle buttons. We ... shouldn't be doing that.

There are some hardcoded negative offsets in the CSS, like `left: -23px` (as seen in https://github.com/rust-lang/rust/pull/84602/). These are not ideal, but they don't correspond to the size of the toggle buttons, they correspond to the indent at which the content occurs. That is, a doc block might be indented at 23px, but we want to "outdent" the toggles so we can use the padding space effectively. I haven't been able to think of a nice clean way to get rid of this need for negative offsetting, but I'd welcome ideas.

**Comment by jsha** [comment] 2021-05-11 06:21
Reopening because I think these JS lines still deal with toggling open / closed sections and need cleaning up: https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L888-L1018. I don't fully understand what they do yet.

**Comment by jsha** [comment] 2021-05-11 06:29
Also we still need to remove the `<span class="loading-content">Loading content...</span>` from the HTML, and

```js
        onEachLazy(main.getElementsByClassName("loading-content"), function(e) {
            e.remove();
        });
```

**Comment by camelid** [comment] 2021-05-13 23:45
This may be related: it looks like the CSS for `h2 + div` has `display: none` as the default and then the JS goes in and adds inline `display: block` styles. It seems like that should be removed? An example of this occurring is the "Layout" section; e.g., scroll to the bottom of https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/symbol/struct.Symbol.html, then "Inspect Element", and then notice that there's an inline `display: block` style. Removing that style causes the contents of the layout section to disappear due to the `display: none` CSS.

**Comment by jsha** [comment] 2021-05-14 01:31
@camelid: I think that was fixed in #85175, which was just merged so presumably doesn't show up in that nightly doc link.

**Comment by camelid** [comment] 2021-05-14 20:20
> @camelid: I think that was fixed in #85175, which was just merged so presumably doesn't show up in that nightly doc link.

Indeed, it is now fixed!

**Comment by jsha** [comment] 2021-05-14 20:29
Great! We have one last cosmetic cleanup in #85289, then I think this is done.

**Comment by GuillaumeGomez** [comment] 2021-05-15 10:48
🎉

**Comment by jsha** [comment] 2021-05-15 16:23
Alright, now I think this is well and truly done. Congrats all!

**Closed by jsha** 2021-05-15 16:23 UTC
Labels: A-rustdoc, A-rustdoc-ui, C-discussion
