### ISSUE TITLE
ICE non-eager expansion without a parent scope

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#66804] opened 2019-11-27 09:38 UTC
When running the following code, the compiler crashes. This bug is reproducible is nightly, beta and stable:

```rust
macro_rules! doc_comment {
    ($x:expr) => {
        #[doc = $x]
        extern {}
    };
}

macro_rules! some_macro {
    ($t1: ty) => {
        doc_comment!{format!("{coor}", coor = stringify!($t1)).as_str()}}
}

fn main() {
    some_macro!(u8);
}
```

**Comment by jonas-schievink** [comment] 2019-11-27 09:49
Backtrace:

```
thread 'rustc' panicked at 'non-eager expansion without a parent scope', src/libcore/option.rs:1190:5
stack backtrace:
  <snip>
  15: core::option::expect_failed
             at src/libcore/option.rs:1190
  16: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver>::resolve_macro_invocation
  17: syntax::ext::expand::MacroExpander::fully_expand_fragment
  18: syntax::ext::expand::MacroExpander::expand_crate
  19: rustc_interface::passes::configure_and_expand_inner::{{closure}}
  20: rustc::util::common::time
  21: rustc_interface::passes::configure_and_expand_inner
  22: rustc_interface::passes::configure_and_expand::{{closure}}
  23: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  24: rustc_interface::passes::configure_and_expand
  25: rustc_interface::queries::Query<T>::compute
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::expansion
  27: rustc_interface::interface::run_compiler_in_existing_thread_pool
  28: std::thread::local::LocalKey<T>::with
  29: scoped_tls::ScopedKey<T>::set
  30: syntax::with_globals
```

**Comment by petrochenkov** [comment] 2019-11-27 20:36
Duplicate of https://github.com/rust-lang/rust/issues/55414.

**Closed** 2019-11-27 20:38 UTC
Labels: A-macros, C-bug, I-ICE, I-nominated, T-compiler
