### ISSUE TITLE
Symbol matching on experimental "or pattern" causes nightly compiler to crash

### ISSUE THREAD

**Issue by Caxpy** [rust-lang/rust#72185] opened 2020-05-14 03:42 UTC
Symbol matching an entire or pattern does not work. Not sure if this is allowed or not but I would expect and error message or something if disallowed, not a compiler crash.

I tried this code:

`#![feature(or_patterns)]`
`#![allow(incomplete_features)]`
`fn main() {`
`  match 1 {`
`    i @ (10..=20 | 30..=40) => println!("{} is between [10, 20] or [30, 40]", i),`
`    i => println!("{} is not between [10, 20] or [30, 40]", i),`
`  }`
`  // No crash if 'i' matched to each pattern`
`  // match 1 {`
`  //   i @ 10..=20 | i @ 30..=40 => println!("{} is between [10, 20] or [30, 40]", i),`
`  //   i => println!("{} is not between [10, 20] or [30, 40]", i),`
`  // }`
`}`

I expected to see this happen:
"1 is not between [10, 20] or [30, 40]"

Instead, this happened:

error: internal compiler error: src\librustc_mir\hair\pattern\_match.rs:1806: support for or-patterns has not been fully implemented yet.

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:892:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0-nightly (412f43ac5 2019-11-24) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type 
bin

note: some of the compiler flags provided by cargo are hidden

## Meta

`rustc --version --verbose`:
rustc 1.41.0-nightly (412f43ac5 2019-11-24)
binary: rustc
commit-hash: 412f43ac5b4ae8c3599e71c6972112e9be4758fa
commit-date: 2019-11-24
host: x86_64-pc-windows-msvc
release: 1.41.0-nightly
LLVM version: 9.0

Backtrace:
sorry not sure what this is.

**Comment by jfrimmel** [comment] 2020-05-14 07:33
Cannot reproduce with the latest nightly (both locally and on the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fcc6084172c83da0c2782ae9fa8465e8)):
```bash
$ rustc +nightly --version
rustc 1.45.0-nightly (75e1463c5 2020-05-13)
```

You're using a very old nightly (almost half a year). Update your compiler to a more recent version and the ICE will be gone.

Note: the backtrace is the sort of output you're getting, if you run the compiler/cargo with the environment variable `RUST_BACKTRACE` set to `1`.

**Comment by jonas-schievink** [comment] 2020-05-14 10:54
Closing as fixed.

**Closed by jonas-schievink** 2020-05-14 10:54 UTC
