### ISSUE TITLE
Missing `compiler-rt` when trying to run `./x.py test` on Windows 10

### ISSUE THREAD

**Issue by ThatsGobbles** [rust-lang/rust#47405] opened 2018-01-13 04:15 UTC
I'm trying to get Rust working on my Windows VM so that I can create a testing environment so that I can make some Windows tests so I can add them to my pull request so that I can finally get path normalization in Rust. Whew.

However, I'm seeing this error, and I'm stumped:

```
C:\rust\rust>python x.py test
Updating submodules
   Compiling bootstrap v0.0.0 (file:///C:/rust/rust/src/bootstrap)
    Finished dev [unoptimized] target(s) in 17.20 secs
 Downloading jobserver v0.1.9
tidy check (x86_64-pc-windows-msvc)
Building stage0 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
   Compiling compiler_builtins v0.0.0 (file:///C:/rust/rust/src/rustc/compiler_builtins_shim)
error: could not find native static library `compiler-rt`, perhaps an -L flag is missing?

error: Could not compile `compiler_builtins`.

Caused by:
  process didn't exit successfully: `C:\rust\rust\build\bootstrap/debug/rustc --crate-name compiler_builtins rustc\compiler_builtins_shim\../../libcompiler_builtins/src/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 --cfg feature="c" --cfg feature="compiler-builtins" --cfg feature="default" --cfg feature="rustbuild" -C metadata=179baef82819633d -C extra-filename=-179baef82819633d --out-dir C:\rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps --target x86_64-pc-windows-msvc -L dependency=C:\rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps -L dependency=C:\rust\rust\build\x86_64-pc-windows-msvc\stage0-std\release\deps --extern core=C:\rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\deps\libcore-026abf2e51bc0a9e.rlib -L native=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib\amd64 -L native=C:\Users\IEUser\rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\build\compiler_builtins-435f6beb92c14554\out --cfg use_c -l static=compiler-rt` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "C:\\rust\\rust\\build\\x86_64-pc-windows-msvc\\stage0/bin\\cargo.exe" "build" "--target" "x86_64-pc-windows-msvc" "-j" "1" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "C:\\rust\\rust\\src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', bootstrap\compile.rs:886:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\rust\rust\build\bootstrap\debug\bootstrap test
Build completed unsuccessfully in 0:01:05
```

Any clues on what could be causing this?

**Comment by projektir** [comment] 2018-01-13 05:40
If I were to guess I would say something relating to MSVC is not installed/identified properly.

Have you installed Visual Studio with C++ tools and Windows SDK?

Have you ran `python x.py build`?

Is this a fresh clone of the compiler?

**Comment by retep998** [comment] 2018-01-13 12:23
`compiler-rt` is supposed to be built during the normal Rust build process. If it is missing, then it isn't an issue with VC++, but rather with rustbuild. Have you tried wiping your `build` folder and doing a fresh build?

**Comment by ollie27** [comment] 2018-01-13 18:00
> `-L native=C:\Users\IEUser\rust\rust\build\x86_64-pc-windows-msvc\stage0-std\x86_64-pc-windows-msvc\release\build\compiler_builtins-435f6beb92c14554\out`

Is clearly not correct, it should be looking in `C:\rust\rust`. I don't know where cargo got that path from, did you maybe try building in `C:\Users\IEUser\rust\rust` and then move it without deleting the `build` folder? If that's the case then wiping the `build` folder should fix it and this could probably be considered a bug in `cargo` and/or the `cc` crate.

**Comment by Aaronepower** [comment] 2018-04-23 19:58
Closing due to lack of information to reproduce this bug. Feel free to re-open if this still is an issue!

**Closed by Aaronepower** 2018-04-23 19:58 UTC
Labels: A-rustbuild
