### ISSUE TITLE
Compiler optimizer issue?

### ISSUE THREAD

**Issue by nsforth** [rust-lang/rust#66599] opened 2019-11-21 07:36 UTC
Hi all,
I caught strange compiler behavior.
Reproducer is there:
https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=8447146347d99118034f50649c83cc25
It works well in debug mode, but fails in release. Reproduced on x86_64 and thumbv7arm hard float.
I've found two workarounds:
1. Changing type from u32 to i32, works fine for me.
2. [inline(never)]  on "encode" method.
It looks like optimizer completely thrown away "encode" method but "assert" is left in code.

**Comment by hellow554** [comment] 2019-11-21 08:46
This boils down to something like this:

```rust
fn a(x: f32) -> u32 {
    x as u32
}

fn main() {
    dbg!(a(-1.0));
}
```

Debug: `[src/main.rs:6] a(-1.0) = 4294967295`
Release: `[src/main.rs:6] a(-1.0) = 0`

Not sure what is correct here.

**Comment by pnkfelix** [comment] 2019-11-21 09:08
Is this "just" an instance of #10184 ?

**Comment by hellow554** [comment] 2019-11-21 09:10
@pnkfelix looks like it. So nothing we could do atm? (Weird that a unsound bug is open for more than 6 years now, but I see that it's partially rusts fault)

**Comment by pnkfelix** [comment] 2019-11-21 09:16
Actually, the freeze instruction has finally landed in LLVM, and from my reading of #10184, having that available is a fundamental part of the preferred solution, I think.

**Comment by memoryruins** [comment] 2019-11-21 09:17
Manually inlining and placing in a loop:

<details>
<summary>code</summary>

```rust
fn main() {
    for _ in 0..20 {
        let mut coords = 0;

        let x5sm = (-0.4 / 0.05) as u32;
        let y5sm = (-0.7 / 0.05) as u32;
        let z5sm = (-0.8 / 0.05) as u32;

        coords |= x5sm << 21;
        coords |= y5sm << 10 & 0x1ffc00;
        coords |= z5sm & 0x3ff;

        println!("{}", coords);
    }
}
```

</details>

<details>
<summary>debug</summary>

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.69s
     Running `target/debug/playground`

0
2098177
4196354
6294531
8392708
10490885
12589062
14687239
16785416
18883593
20981770
23079947
25178124
27276301
29374478
31472655
33570832
35669009
37767186
39865363
```

</details>

<details>
<summary>release</summary>

```
   Compiling playground v0.0.1 (/playground)
    Finished release [optimized] target(s) in 0.78s
     Running `target/release/playground`

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```

</details>

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cdcc747351cc8ad122e2148362ef8a6f

**Comment by pnkfelix** [comment] 2019-11-21 09:27
Closing as duplicate of #10184

**Closed by pnkfelix** 2019-11-21 09:27 UTC

**Comment by vagola** [comment] 2019-11-22 09:44
I dont think this is duplicate. The behaivor are diffrent on `release` and `debug`

**Comment by jonas-schievink** [comment] 2019-11-22 09:46
@vagola Undefined Behavior means that any behavior may happen, at the leisure of LLVM's optimizations (or anything else, really)
