### ISSUE TITLE
Box<FnMut> and Box<Fn> should implement FnMut and Fn

### ISSUE THREAD

**Issue by Riamse** [rust-lang/rust#47024] opened 2017-12-26 22:00 UTC
`Box<FnMut>` and `Box<Fn>` should implement `FnMut` and `Fn`. The Rust Book [encourages](https://doc.rust-lang.org/book/second-edition/ch19-05-advanced-functions-and-closures.html) you to use boxed closures when returning closures in order to satisfy the `Sized` requirement, but since boxed closures don't actually implement these traits, it's hard to use them in practice, especially when returning iterators that have composition involved. For example, the following code:

```rust
use std::iter::Map;

fn map_parity<T: Iterator<Item=u8>>(it: T) -> Map<T, Box<FnMut(u8) -> bool>> {
    it.map(Box::new(|x| x % 2 == 0))
}

fn main() {
    for i in map_parity((1..10).into_iter()) {
        println!("{}", i);
    }
}
```
fails to compile:
```
error[E0277]: the trait bound `std::boxed::Box<std::ops::FnMut(u8) -> bool>: std::ops::FnMut<(u8,)>` is not satisfied
 --> test.rs:4:8
  |
4 |     it.map(Box::new(|x| x % 2 == 0))
  |        ^^^ the trait `std::ops::FnMut<(u8,)>` is not implemented for `std::boxed::Box<std::ops::FnMut(u8) -> bool>`

error[E0277]: the trait bound `std::boxed::Box<std::ops::FnMut(u8) -> bool>: std::ops::FnMut<(u8,)>` is not satisfied
  --> test.rs:8:5
   |
8  | /     for i in map_parity((1..10).into_iter()) {
9  | |         println!("{}", i);
10 | |     }
   | |_____^ the trait `std::ops::FnMut<(u8,)>` is not implemented for `std::boxed::Box<std::ops::FnMut(u8) -> bool>`
   |
   = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Map<std::ops::Range<u8>, std::boxed::Box<std::ops::FnMut(u8) -> bool>>`

error: aborting due to 2 previous errors
```

There is no way to make this compile as is. An alternative solution would be turning the closure into a function and then replacing the `Box<FnMut>` with `fn(u8) -> bool`, but the ideal solution is that what the Rust Book says actually works.

Rustc version:
```$ rustc --version --verbose
rustc 1.24.0-nightly (250b49205 2017-12-21)
binary: rustc
commit-hash: 250b492052e94d76bd318a4b932159395da55981
commit-date: 2017-12-21
host: x86_64-unknown-linux-gnu
release: 1.24.0-nightly
LLVM version: 4.0
```

**Comment by qnighy** [comment] 2017-12-27 03:10
Seems to be a duplicate of #38132.

**Comment by bluss** [comment] 2017-12-27 20:07
Seems to be a perfect duplicate, closing in favour of the older one.

**Closed by bluss** 2017-12-27 20:07 UTC
