### ISSUE TITLE
'index out of bounds: the len is 0 but the index is 0' building gfx-backend-metal

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#72593] opened 2020-05-26 00:30 UTC
To reproduce, clone https://github.com/gfx-rs/gfx, then `cd src/backends/metal; cargo build`:
```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', src/librustc_mir_build/hair/pattern/_match.rs:1184:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (46e85b432 2020-05-24) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `gfx-backend-metal`.
```

This regressed between the 5/20 and 5/25 nightlies. I'm having trouble bisecting in between those dates because the rustfmt component isn't available, even though I don't have the rustfmt component installed.

**Comment by JohnTitor** [comment] 2020-05-26 03:25
Duplicate of #72467

**Closed** 2020-05-26 03:26 UTC
Labels: I-ICE, I-prioritize, O-macos, regression-from-stable-to-nightly
