### ISSUE TITLE
rust-url's debugger_visualizer tests are broken in rustc nightly-2024-08-13

### ISSUE THREAD

**Issue by valenting** [rust-lang/rust#130431] opened 2024-09-16 12:56 UTC
I was looking into https://github.com/servo/rust-url/pull/967 but I wasn't able to reproduce the failures locally. Then I realized I was running an older nightly.

I used bisect-rustc and got the following output:

---

searched nightlies: from nightly-2024-08-01 to nightly-2024-09-16
regressed nightly: nightly-2024-08-13
searched commit range: https://github.com/rust-lang/rust/compare/41dd149fd6a6a06795fc6b9f54cb49af2f61775f...91376f416222a238227c84a848d168835ede2cc3
regressed commit: https://github.com/rust-lang/rust/commit/13f8a57cfb57d527abe797230beabb64758bb888

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.9</summary>

Host triple: x86_64-pc-windows-msvc
Reproduce with:
```bash
cargo bisect-rustc --start=2024-08-01 --end=2024-09-16 --test-dir=rust-url -- test --test debugger_visualizer --features url/debugger_visualizer,url_debug_tests/debugger_visualizer -- --test-threads=1 --nocapture
```
</details>

---

The PR that introduced the issue seems to be: https://github.com/rust-lang/rust/pull/126793

Example failing job: https://github.com/servo/rust-url/actions/runs/10879435038/job/30184131451

**Comment by jieyouxu** [comment] 2024-09-16 13:44
cc @saethlin since you authored https://github.com/rust-lang/rust/pull/126793 and are more familiar with debuggers

**Comment by saethlin** [comment] 2024-09-16 14:10
The issue is that you need to update your natvis file for the new level of nesting in Vec, probably this line:
https://github.com/servo/rust-url/blob/22b823708a59a50ea2505c3fcdb5c4b26ab9b080/debug_metadata/url.natvis#L4

You could use the changes to our own natvis file in that PR you bisected to as a guide.

I've removed the regression and bug labels, because (unfortunately) doing cool debugger stuff like this means you are depending on unstable library internals. If only we could teach debuggers how to go through our stable APIs to get the information 🙃

**Comment by valenting** [comment] 2024-09-17 11:55
@saethlin thank you for the suggestion. Very much appreciated!
Feel free to close this bug.

**Comment by jieyouxu** [comment] 2024-09-17 12:44
Closing as unfortunately not super actionable in terms of rustc/std.

**Closed by jieyouxu** 2024-09-17 12:44 UTC
Labels: C-discussion, WG-debugging
