### ISSUE TITLE
Unexpected code elimination of using `..` instead of `..=` 

### ISSUE THREAD

**Issue by huangjj27** [rust-lang/rust#85750] opened 2021-05-27 15:07 UTC
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=950b2783e2eeb27d37840d5669f0f730)):

```rust
#[inline(never)]
fn trans(i: usize) -> bool {
    if i == 1 {
        true
    } else if i % 2 == 0 {
        trans(i / 2)
    } else {
        trans(3 * i + 1)
    }
}

pub fn main() {
    for i in 1..5_0000 {  // using `..` instead of `..=`
        if !trans(i) {
            println!("{}", i);
            return;
        }
    }
}
```

I expected to see this happen: the asm output should have things in `playground::main` like when using `..=`:

```rust
pub fn main() {
    for i in 1..=5_0000 { // here we use `..=`
        if !trans(i) {
            println!("{}", i);
            return;
        }
    }
}
```

```asm
playground::main: # @playground::main
# %bb.0:
	pushq	%r14
	pushq	%rbx
	pushq	%rax
	movl	$1, %ebx

.LBB6_1:                                # =>This Inner Loop Header: Depth=1
	leaq	1(%rbx), %r14
	movq	%rbx, %rdi
	callq	playground::trans
	cmpq	$50000, %rbx                    # imm = 0xC350
	movq	%r14, %rbx
	jb	.LBB6_1
# %bb.2:
	addq	$8, %rsp
	popq	%rbx
	popq	%r14
	retq
                                        # -- End function
```

Instead, this happened: the asm output of the original code is  **just a `retq`**

```asm
playground::main: # @playground::main
# %bb.0:
	retq
                                        # -- End function
```

### Meta

`rustc --version --verbose`:
```
Build using the Nightly version: 1.54.0-nightly

(2021-05-26 9111b8ae9793f18179a1)
```

**Comment by jonas-schievink** [comment] 2021-05-27 15:15
duplicate of https://github.com/rust-lang/rust/issues/85742

**Closed by jonas-schievink** 2021-05-27 15:15 UTC
Labels: C-bug
