### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by AlterionX** [rust-lang/rust#60842] opened 2019-05-14 22:53 UTC
The compiler crashed and told me to report it.

I shaved off the excess and found this to be a minimally working (breaking) example:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=10a2d80c7a36cc12edaa39cd3d6a5781

I expected it to tell me that the `T` in `a::<'_, T>` is an error.

## Meta

`rustc --version --verbose`:

Backtrace:
```
rustc 1.34.2 (6c2484dc3 2019-05-13)
binary: rustc
commit-hash: 6c2484dc3c532c052f159264e970278d8b77cdc9
commit-date: 2019-05-13
host: x86_64-unknown-linux-gnu
release: 1.34.2
LLVM version: 8.0
```

**Comment by jonas-schievink** [comment] 2019-05-14 22:56
Thanks for the report and the small example!

This is possibly a duplicate of https://github.com/rust-lang/rust/issues/60622

**Comment by jonas-schievink** [comment] 2019-05-14 22:58
Jup, this one also regressed between 1.29.2 and 1.30.0, so I'll close this as a duplicate of #60622

**Closed by jonas-schievink** 2019-05-14 22:58 UTC
Labels: C-bug, I-ICE, I-nominated, T-compiler
