### ISSUE TITLE
Some additional bounds on implemented trait methods are permitted, but not respected

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#29250] opened 2015-10-23 15:08 UTC
This code successfully compiles on stable and nightly, but should supposedly be rejected for one of two reasons - incompatible method signature or "`a` does not live long enough"
```
trait Tr {
    fn f<T>(_: T) {}
}

impl Tr for u8 {
    fn f<T>(_: T) where T: 'static {} // Should this be rejected?
}

fn main() {
    let a = 10;
    u8::f(a);
    u8::f(&a); // Or should *this* be rejected?
}
```

cc @arielb1

**Comment by arielb1** [comment] 2015-10-23 17:38
duplicate of #18937

**Closed by arielb1** 2015-10-23 17:38 UTC
