### ISSUE TITLE
Derive Copy/Clone on generic Union working incorrectly.

### ISSUE THREAD

**Issue by rickvanprim** [rust-lang/rust#62427] opened 2019-07-05 23:53 UTC
The following code reports an error about the value being moved:
```
use std::marker::PhantomData;

trait Foo {}

struct Bar {}

impl Foo for Bar {}

#[derive(Copy, Clone)]
union U<T>
where T: Foo
{
    value1: u32,
    value2: *const (),
    phantom: PhantomData<*const T>
}

fn test()
{
    let a: U<Bar> = U { value1: 5 };
    let b = a;
    let c = a;
}
```

While the following code works as expected:
```
use std::marker::PhantomData;

trait Foo {}

struct Bar {}

impl Foo for Bar {}

union U<T>
where T: Foo
{
    value1: u32,
    value2: *const (),
    phantom: PhantomData<*const T>
}

impl<T> Copy for U<T> where T: Foo {}

impl<T> Clone for U<T> where T: Foo
{
    fn clone(&self) -> Self
    {
        *self
    }
}

fn test()
{
    let a: U<Bar> = U { value1: 5 };
    let b = a;
    let c = a;
}
```

**Comment by ecstatic-morse** [comment] 2019-07-06 06:27
This seems like a duplicate of of #41481?

**Comment by rickvanprim** [comment] 2019-07-06 18:46
Seems fair @ecstatic-morse .  Also looking at #56008 was useful for me.

**Closed** 2019-07-06 18:46 UTC
