### ISSUE TITLE
Proc macro dependencies bleed into another crate's

### ISSUE THREAD

**Issue by TooManyBees** [rust-lang/rust#51234] opened 2018-05-30 22:33 UTC
Not 100% sure if this is an issue with Cargo or Rust. I'm also not sure if it's a bug, or just my expectations butting up against reality.

When a project depends on some proc macro `Crate P`, and both `Crate P` and the project separately depend on `Crate L`, some library, `Crate L` will be compiled into both with the same feature sets, even when the parent project and the proc macro request different features.

It's my understanding that when a crate is required multiple times as a dependency, its feature sets are unified together. **What I see as a bug is the fact that this is happening with the dependencies of proc macro crates and the project that uses the proc macro crate to generate its code.** (More detailed example below.) My expectation is that, since the proc macro is a build dependency rather than a runtime dep, its own dependencies should be "insulated" from those of the project that's using it.

## example

A Rust project needs some structs written into the code with a proc macro. These structs come from `Library L`. `Library L`'s structs implement Quote's `ToTokens` trait. Since we do not want `Quote` to be compiled into the final binary, `Library L` has a feature `codegen` that includes Quote and enables the trait impls. `Proc Macro P` requires `Library L` with the codegen feature. The parent project requires `Library L` without it.

Ultimately, both the parent project and the proc macro end up using `Library L` with the `codegen` feature turned on. You wouldn't notice that Quote snuck into the projects dependencies until you compiled it as a `cdylib` crate type (say, in order to build it for the wasm32-unknown-unknown target) which Quote can't be compiled for (or maybe it was Syn that couldn't be compiled for cdylibs? I can't remember), and compilation fails.

My solution for this was to abandon crate features and just write `Library L`'s structs' constructor literals right into the `quote!` macros in `Proc Macro P`, which is a shame because now the proc macro crate and the library are coupled tightly and must be updated together if the internals of a struct changes.

## p.s.

I suspect(???) but have not yet confirmed that the same issue causes the `std` crate to get pulled into `#![no_std]` projects if it uses a proc macro that uses `std`. Rustc fails when `panic_fmt` is not defined due to no_std, but also fails when it is defined because `std` was mysteriously pulled in (by the proc macro crate?) which already defined it.

**Comment by sfackler** [comment] 2018-05-30 23:27
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/4361.

**Comment by TooManyBees** [comment] 2018-05-31 04:17
Clearly, the art of searching GitHub issues is a fickle one to master.

**Closed** 2018-05-31 04:28 UTC
