### ISSUE TITLE
Suggest derefence operator when mismatched types related to reference

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#39942] opened 2017-02-18 22:53 UTC
[Playpen](https://is.gd/AlJIIF)

Code:

```rust
fn main() {
    let a = &1;
    let b = 1;
    if a == b {
        println!("equal");
    } else {
        println!("not equal");
    }
}
```

Error:

```
error[E0277]: the trait bound `&{integer}: std::cmp::PartialEq<{integer}>` is not satisfied
 --> <anon>:4:8
  |
4 |     if a == b {
  |        ^^^^^^ the trait `std::cmp::PartialEq<{integer}>` is not implemented for `&{integer}`
  |
  = help: the following implementations were found:
  = help:   <&'a A as std::cmp::PartialEq<&'b B>>
  = help:   <&'a mut A as std::cmp::PartialEq<&'b mut B>>
  = help:   <&'a A as std::cmp::PartialEq<&'b mut B>>
  = help:   <&'a mut A as std::cmp::PartialEq<&'b B>>
  = help: and 586 others

error: aborting due to previous error
```

This error message is somewhat intimidating. Assuming the user knows to add a `*` or `&`, which side do they add it to? It might be not too difficult with this example to deduce that, but when dealing with double nested references and other shenanigans, it'd be a lot easier if we just suggested where to put the `*` and `&`.

**Comment by frewsxcv** [comment] 2017-02-18 22:53
cc @oconnor663

**Comment by oconnor663** [comment] 2017-02-18 23:29
This is especially tricky when you're dealing with iterators or other container methods that add extra `&`'s onto your types, and you've made an `&&T` without realizing it. The error message doesn't include an `&&` anywhere (I think), and it becomes very hard to figure out what's wrong.

**Comment by estebank** [comment] 2019-09-22 02:10
Current output:

```
error[E0277]: can't compare `&{integer}` with `{integer}`
 --> src/main.rs:6:10
  |
6 |     if a == b {
  |          ^^ no implementation for `&{integer} == {integer}`
  |
  = help: the trait `std::cmp::PartialEq<{integer}>` is not implemented for `&{integer}`
```

I don't think we'll get to suggesting dereferencing for these cases in the short term.

**Comment by estebank** [comment] 2019-09-27 00:39
Closing as duplicate of #45109 and #40660.

**Closed by estebank** 2019-09-27 00:39 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
