### ISSUE TITLE
RustC Panic

### ISSUE THREAD

**Issue by NightBalance** [rust-lang/rust#64300] opened 2019-09-09 05:37 UTC
```
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/libsyntax/source_map.rs:842:17
stack backtrace:
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/libsyntax/source_map.rs:842:17
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
   0: <unknown>
  12: <unknown>
   1: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
  18: <unknown>
  19: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  18: <unknown>
  35: <unknown>
  36: <unknown>
  19: <unknown>
  20: <unknown>
  37: <unknown>
  21: <unknown>
  38: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
query stack during panic:
end of query stack
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (6e310f2ab 2019-07-07) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C ar=/usr/bin/ar -C linker=/usr/bin/gcc -C incremental

note: some of the compiler flags provided by cargo are hidden


error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0-nightly (6e310f2ab 2019-07-07) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C ar=/usr/bin/ar -C linker=/usr/bin/gcc -C incremental --crate-type staticlib --crate-type cdylib --crate-type rlib

note: some of the compiler flags provided by cargo are hidden
```
when is cross compile x86_64-unknown-linux-gnu

**Comment by hellow554** [comment] 2019-09-09 06:23
The log looks very incoplete.
Can you try it again please and surround it by three backticks?

\`\`\`
your
backtrace
goes
here
\`\`\`

Also, do you can share the code that produces the problem?

**Comment by estebank** [comment] 2019-09-10 18:23
This is likely caused by a malformed span pointing at the middle of an unicode grapheme. We _can't_ know for sure the culprit is the parser without the stack trace :-/

**Comment by estebank** [comment] 2019-12-14 01:28
Thank you for pointing this to us. As this ticket stands, we have no way of acting on this so I will close it.

@NightBalance if you the code to reproduce this or a non-elided stacktrace we can reopen this ticket.

**Closed by estebank** 2019-12-14 01:28 UTC
Labels: A-cross, A-parser, A-unicode, I-ICE, T-compiler
