### ISSUE TITLE
`./configure --prefix=$HOME && make && make install` not working on master - `--docdir=/home/d33tah/share/doc/rust' is not recognized`

### ISSUE THREAD

**Issue by d33tah** [rust-lang/rust#36697] opened 2016-09-24 16:57 UTC
```
(virtualenv)[][18:57:15][~/workspace/src/rust]$ make install 2>&1             
cfg: version 1.13.0-dev (bdad70213 2016-09-24)
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: have good valgrind for x86_64-unknown-linux-gnu
cfg: using CC=gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to "/usr/bin/valgrind" --error-exitcode=100 --fair-sched=try --quiet --soname-synonyms=somalloc=NONE --suppressions=/home/d33tah/workspace/src/rust/src/etc/x86.supp  --tool=memcheck --leak-check=full
cfg: including prepare rules
cfg: including dist rules
cfg: including install rules
make[1]: Entering directory '/mnt/sda/d33tah/workspace/src/rust'
cfg: version 1.13.0-dev (bdad70213 2016-09-24)
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: have good valgrind for x86_64-unknown-linux-gnu
cfg: using CC=gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: valgrind-rpass command set to "/usr/bin/valgrind" --error-exitcode=100 --fair-sched=try --quiet --soname-synonyms=somalloc=NONE --suppressions=/home/d33tah/workspace/src/rust/src/etc/x86.supp  --tool=memcheck --leak-check=full
cfg: including prepare rules
cfg: including dist rules
cfg: including install rules
cleaning destination tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/bin
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_bitflags-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_abort-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-*.rlib
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libsyntax-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libsyntax_ext-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libsyntax_pos-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_typeck-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_mir-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_borrowck-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_resolve-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_trans-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_back-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_privacy-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_lint-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_data_structures-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_platform_intrinsics-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_errors-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_plugin-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_metadata-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_passes-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_save_analysis-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_const_eval-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_const_math-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_incremental-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_macro-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustdoc-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libfmt_macros-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libflate-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libarena-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgraphviz-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblog-*.so
prepare: tmp/dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserialize-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/bin
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/rustlib/etc
build: dist/rust-std-1.13.0-dev-x86_64-unknown-linux-gnu.tar.gz
gen-installer: looking for programs
gen-installer: 
gen-installer: found tar
gen-installer: found cp
gen-installer: found rm
gen-installer: found mkdir
gen-installer: found echo
gen-installer: found tr
gen-installer: found awk
gen-installer: 
gen-installer: processing arguments
gen-installer: 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/share/man/man1
gen-installer: CFG_PRODUCT_NAME     := Rust 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libstd-*.so
gen-installer: CFG_COMPONENT_NAME   := rust-std-x86_64-unknown-linux-gnu 
gen-installer: CFG_PACKAGE_NAME     := rust-std-1.13.0-dev-x86_64-unknown- ...
gen-installer: CFG_REL_MANIFEST_DIR := rustlib 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libterm-*.so
gen-installer: CFG_SUCCESS_MESSAGE  := std-is-standing-at-the-ready. 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/liblog-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libarena-*.so
gen-installer: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libfmt_macros-*.so
gen-installer: CFG_NON_INSTALLED_OVERLAY :=  
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libflate-*.so
gen-installer: CFG_BULK_DIRS        :=  
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libgetopts-*.so
gen-installer: CFG_IMAGE_DIR        := tmp/dist/rust-std-1.13.0-dev-x86_64 ...
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libgraphviz-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_llvm-*.so
gen-installer: CFG_WORK_DIR         := tmp/dist 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_platform_intrinsics-*.so
gen-installer: CFG_OUTPUT_DIR       := dist 
gen-installer: 
gen-installer: validating arguments
gen-installer: 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libtest-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libserialize-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libsyntax_pos-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_data_structures-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_errors-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libsyntax-*.so
gen-install-script: looking for install programs
gen-install-script: 
gen-install-script: found sed
gen-install-script: found chmod
gen-install-script: found cat
gen-install-script: 
gen-install-script: processing arguments
gen-install-script: 
gen-install-script: CFG_PRODUCT_NAME     := Rust 
gen-install-script: CFG_REL_MANIFEST_DIR := rustlib 
gen-install-script: CFG_SUCCESS_MESSAGE  := std-is-standing-at-the-ready. 
gen-install-script: CFG_OUTPUT_SCRIPT    := tmp/dist/rust-std-1.13.0-dev-x86_64 ...
gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-install-script: 
gen-install-script: validating arguments
gen-install-script: 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_back-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_const_math-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_macro-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libsyntax_ext-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc-*.so
build: dist/rust-docs-1.13.0-dev-x86_64-unknown-linux-gnu.tar.gz
gen-installer: looking for programs
gen-installer: 
gen-installer: found tar
gen-installer: found cp
gen-installer: found rm
gen-installer: found mkdir
gen-installer: found echo
gen-installer: found tr
gen-installer: found awk
gen-installer: 
gen-installer: processing arguments
gen-installer: 
gen-installer: CFG_PRODUCT_NAME     := Rust-Documentation 
gen-installer: CFG_COMPONENT_NAME   := rust-docs 
gen-installer: CFG_PACKAGE_NAME     := rust-docs-1.13.0-dev-x86_64-unknown ...
gen-installer: CFG_REL_MANIFEST_DIR := rustlib 
gen-installer: CFG_SUCCESS_MESSAGE  := Rust-documentation-is-installed. 
gen-installer: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-installer: CFG_NON_INSTALLED_OVERLAY :=  
gen-installer: CFG_BULK_DIRS        := share/doc/rust/html 
gen-installer: CFG_IMAGE_DIR        := tmp/dist/rust-docs-1.13.0-dev-x86_6 ...
gen-installer: CFG_WORK_DIR         := tmp/dist 
gen-installer: CFG_OUTPUT_DIR       := dist 
gen-installer: 
gen-installer: validating arguments
gen-installer: 
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_const_eval-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_resolve-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_incremental-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_privacy-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_lint-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_metadata-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_passes-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_save_analysis-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_mir-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_typeck-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_trans-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_plugin-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_borrowck-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/libproc_macro-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustc_driver-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/lib/librustdoc-*.so
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/bin/rustc
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/share/man/man1/rustc.1
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/bin/rustdoc
prepare: tmp/dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu-image/share/man/man1/rustdoc.1
build: dist/rustc-1.13.0-dev-x86_64-unknown-linux-gnu.tar.gz
gen-installer: looking for programs
gen-installer: 
gen-installer: found tar
gen-installer: found cp
gen-installer: found rm
gen-installer: found mkdir
gen-installer: found echo
gen-installer: found tr
gen-installer: found awk
gen-installer: 
gen-installer: processing arguments
gen-installer: 
gen-installer: CFG_PRODUCT_NAME     := Rust 
gen-installer: CFG_COMPONENT_NAME   := rustc 
gen-installer: CFG_PACKAGE_NAME     := rustc-1.13.0-dev-x86_64-unknown-lin ...
gen-installer: CFG_REL_MANIFEST_DIR := rustlib 
gen-installer: CFG_SUCCESS_MESSAGE  := Rust-is-ready-to-roll. 
gen-installer: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-installer: CFG_NON_INSTALLED_OVERLAY := tmp/dist/rustc-1.13.0-dev-x86_64-un ...
gen-installer: CFG_BULK_DIRS        :=  
gen-installer: CFG_IMAGE_DIR        := tmp/dist/rustc-1.13.0-dev-x86_64-un ...
gen-installer: CFG_WORK_DIR         := tmp/dist 
gen-installer: CFG_OUTPUT_DIR       := dist 
gen-installer: 
gen-installer: validating arguments
gen-installer: 
gen-install-script: looking for install programs
gen-install-script: 
gen-install-script: found sed
gen-install-script: found chmod
gen-install-script: found cat
gen-install-script: 
gen-install-script: processing arguments
gen-install-script: 
gen-install-script: CFG_PRODUCT_NAME     := Rust 
gen-install-script: CFG_REL_MANIFEST_DIR := rustlib 
gen-install-script: CFG_SUCCESS_MESSAGE  := Rust-is-ready-to-roll. 
gen-install-script: CFG_OUTPUT_SCRIPT    := tmp/dist/rustc-1.13.0-dev-x86_64-un ...
gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-install-script: 
gen-install-script: validating arguments
gen-install-script: 
gen-install-script: looking for install programs
gen-install-script: 
gen-install-script: found sed
gen-install-script: found chmod
gen-install-script: found cat
gen-install-script: 
gen-install-script: processing arguments
gen-install-script: 
gen-install-script: CFG_PRODUCT_NAME     := Rust-Documentation 
gen-install-script: CFG_REL_MANIFEST_DIR := rustlib 
gen-install-script: CFG_SUCCESS_MESSAGE  := Rust-documentation-is-installed. 
gen-install-script: CFG_OUTPUT_SCRIPT    := tmp/dist/rust-docs-1.13.0-dev-x86_6 ...
gen-install-script: CFG_LEGACY_MANIFEST_DIRS := rustlib,cargo 
gen-install-script: 
gen-install-script: validating arguments
gen-install-script: 
make[1]: Leaving directory '/mnt/sda/d33tah/workspace/src/rust'
install: error: Option '--docdir=/home/d33tah/share/doc/rust' is not recognized
/home/d33tah/workspace/src/rust/mk/install.mk:23: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by 0xmohit** [comment] 2016-09-24 18:12
See #36451

**Comment by alexcrichton** [comment] 2016-09-26 16:56
Ah yes I think this is a dupe of https://github.com/rust-lang/rust/issues/36451, so closing in favor of that.

**Closed by alexcrichton** 2016-09-26 16:56 UTC
