### ISSUE TITLE
where clause trait bounds not included in trait implementors section

### ISSUE THREAD

**Issue by niax** [rust-lang/rust#20534] opened 2015-01-04 18:53 UTC
`std::borrow::ToOwned`'s [doc page](http://doc.rust-lang.org/std/borrow/trait.ToOwned.html) lists `impl<T> ToOwned<T> for T` as an implementor which is not accurate. Only through reading the source does it becomes apparent that it should read `impl<T> ToOwned<T> for T where T: Clone`.

**Comment by bluss** [comment] 2015-01-04 22:14
It's a bug in doc inclusion indirection, it should be correct in libcore docs  -- compare http://doc.rust-lang.org/core/borrow/trait.ToOwned.html?gotosrc=40579

**Comment by kmcallister** [comment] 2015-01-07 19:41
Nominating for 1.0-stable.

**Comment by kmcallister** [comment] 2015-01-07 19:41
Dupe of #20203?

**Closed** 2015-01-14 02:52 UTC
Labels: A-rustdoc, I-nominated
