### ISSUE TITLE
object-safe traits can have associated types with unchecked bounds

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#27675] opened 2015-08-11 20:15 UTC
## STR

``` Rust
trait Foo { type Assoc: PartialEq<Box<Self>>; }
impl Foo for u32 { type Assoc = Box<u32>; }

fn foo<T: Foo+?Sized>(u: Box<T>, v: T::Assoc) -> bool {
    &v == &u
}

fn main() {
    let bar: Box<Foo<Assoc=Box<u32>>> = Box::new(4);
    foo(bar, Box::new(5));
}
```
### Result

```
<anon>:5:5: 5:13 error: internal compiler error: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<Box<u32> as core::cmp::PartialEq<Box<Foo<Assoc=Box<u32>> + 'static>>>)),depth=1),Unimplemented)]` fulfilling during trans
```

I guess this should be banned.

cc @nikomatsakis

**Comment by arielb1** [comment] 2015-08-11 20:50
Related:

```Rust
use std::fmt;

trait Foo {
    type Assoc: 'static;
}

fn foo<T: Foo+?Sized>(t: T::Assoc) -> Box<fmt::Display+'static>
        where T::Assoc: fmt::Display {
    Box::new(t)
}

fn wat() -> Box<fmt::Display+'static> {
    let x = 42;
    foo::<Foo<Assoc=&u32>>(&x)
}

fn main() {
    println!("{}", wat());
}
```

**Comment by nikomatsakis** [comment] 2015-08-11 21:42
Interesting. I agree that it should be illegal and we should amend WF relations for object types to check that the bindings cover the requirements of the trait -- the RFC was incomplete on this topic.

**Comment by pnkfelix** [comment] 2016-01-21 13:08
The example from the first comment (https://github.com/rust-lang/rust/issues/27675#issuecomment-130067761) is actually scarier than the original bug description; at least, I usually can think "oh, an ICE, well that *might* just be something that won't actually ever compile"; but the first comment is showing code that is indeed a case of "wat"!

**Comment by pnkfelix** [comment] 2016-07-07 20:23
triage: P-medium

**Comment by HeroicKatora** [comment] 2020-09-22 20:19
Since this has not been demonstrated: We can indeed build a safe, arbitrary transmutation primitive from this, though this will ICE in practice except if used only for the purpose of the second comment, casting away lifetimes.

```rust
trait Id<T>: Sized {
    fn id(self) -> T;
}
impl<T> Id<T> for T {
    fn id(self) -> T { self }
}

trait Setup<T> {
    type From: Id<T>;
}

fn transmute<T, U: Setup<T> + ?Sized>(from: U::From) -> T {
    Id::id(from)
}

// compiles fine
pub fn safe_transmute<T, U>(t: T) -> U {
    transmute::<U, dyn Setup<U, From=T>>(t)
}
```

```rust
fn main() {
    let static_word = {
        let st = String::from("Hello!");
        safe_transmute::<_, &'static mut str>(&*st)
    };
    
    println!("{:?}", static_word);
}
```

```rust
// ICE
fn main() {
    safe_transmute::<usize, &'static str>(0usize);
}
```

**Comment by HeroicKatora** [comment] 2020-09-22 20:19
Uuups, we can make any type `Copy`:

```rust
trait Setup {
    type From: Copy;
}

fn copy<U: Setup + ?Sized>(from: &U::From) -> U::From {
    *from
}

pub fn copy_any<T>(t: &T) -> T {
    copy::<dyn Setup<From=T>>(t)
}

fn main() {
    let st = String::from("Hello");
    copy_any(&st);
}
```

**Comment by HeroicKatora** [comment] 2020-09-22 20:38
Feature `unsize` gives the ability to do some other interesting coercions that enable arbitrary reference transmute.

```rust
#![feature(unsize)]

trait Setup<T> {
    type From: std::marker::Unsize<[T]>;
}

fn unsize<T, U: Setup<T> + ?Sized>(from: &U::From) -> &[T] {
    from
}

fn unsize_to_any<T, U>(t: &T) -> &U {
    &unsize::<U, dyn Setup<U, From=[T]>>(core::slice::from_ref(t))[0]
}

fn main() {
    let trust_me_im_64: u8 = 0;
    println!("{}", unsize_to_any::<u8, u64>(&trust_me_im_64))
}
```

**Comment by camelid** [comment] 2020-09-22 21:22
Decided on `P-high` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2327675.20object-safe.20traits.20can.20have.20associated.20.E2.80.A6) in the prioritization working group procedure.

**Comment by HeroicKatora** [comment] 2020-09-22 22:11
For completeness sake. This may be used to send any reference across threads:

```rust
trait Id<T> {
    fn id(&self) -> &T;
}

impl<T> Id<T> for T {
    fn id(&self) -> &T { self }
}

trait SyncSetup<T> {
    type From: Id<T> + Sync + 'static;
}

fn cast<T, U>(from: &T) -> &(dyn Id<U> + Sync) {
    fn do_it<T, U: ?Sized + SyncSetup<T>>(val: &U::From) -> &(dyn Id<T> + Sync) {
        val
    }
    
    do_it::<U, dyn SyncSetup<U, From=T>>(from)
}

fn syncify<T>(from: &T) -> &'static (dyn Id<T> + Sync) {
    let x: &(dyn Id<T> + Sync) = cast(from);
    let y: &(dyn Id<&'static (dyn Id<T> + Sync)>) = cast(&x);
    let x: &'static (dyn Id<T> + Sync) = *(y.id());
    x
}

use std::cell::Cell;
fn main() {
    let st = Cell::new(0u32);
    let x = syncify(&st);
    
    std::thread::spawn(move || {
        x.id().set(1);
    });
    
    while st.get() == 0 {}
    println!("Spooky");
}
```

**Comment by Aaron1011** [comment] 2020-09-23 00:53
I suspect that this will be fixed by https://github.com/rust-lang/rust/pull/73905

**Comment by lqd** [comment] 2020-09-24 14:03
The 4 weaponized examples above will indeed be rejected with #73905

**Comment by Aaron1011** [comment] 2020-10-09 20:12
A regression test was added in https://github.com/rust-lang/rust/pull/77663.

**Closed by Aaron1011** 2020-10-09 20:12 UTC
Labels: A-traits, A-typesystem, C-bug, I-ICE, I-unsound 💥, P-high, T-compiler
