### ISSUE TITLE
internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by yiguihai** [rust-lang/rust#79504] opened 2020-11-28 14:17 UTC
### Code

```Rust
```

### Meta

`rustc --version --verbose`:
```
nightly-x86_64-unknown-linux-gnu installed - rustc 1.50.0-nightly (6a889570e 2020-11-27)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:1268 ~ ring[a607]::digest::sha2::)`,
 right: `DefId(0:1269 ~ ring[a607]::digest::sha2::::GFp_sha256_block_data_order)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (6a889570e 2020-11-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C target-feature=+aes,+pclmul,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,adx --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [index_hir] index HIR
#1 [hir_owner] HIR owner of `{misc#0}`
end of query stack
error: could not compile `ring`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by SNCPlay42** [comment] 2020-11-28 14:35
Duplicate of #79487

**Closed** 2020-11-28 14:48 UTC
Labels: C-bug, I-ICE, T-compiler
