### ISSUE TITLE
`Copy` as a parent trait has weird simplification rules

### ISSUE THREAD

**Issue by reinerp** [rust-lang/rust#66582] opened 2019-11-20 19:28 UTC
This compiles, which it should:

```rust
trait Tr1 {}
trait Tr2: Tr1 {}

struct A<T>(T);

impl<T> Tr1 for A<T> where T: Tr1 {}
impl<T> Tr2 for A<T> where T: Tr2 {}

struct B<T>(A<T>);

impl<T> Tr1 for B<T> where A<T>: Tr1 {}
impl<T> Tr2 for B<T> where A<T>: Tr2 {}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f835c3c0b83ba608cca84f9bcf42a650))

Now replace Tr1 with Copy, and #[derive] it instead of implementing it manually. You get this, which fails to compile:

```rust
trait Tr2: Copy {}

#[derive(Clone, Copy)]
struct A<T>(T);

impl<T> Tr2 for A<T> where T: Tr2 {}

#[derive(Clone, Copy)]
struct B<T>(A<T>);

impl<T> Tr2 for B<T> where A<T>: Tr2 {}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=98a37830457736ebbb7dfd6bfc19855d))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `T: std::marker::Copy` is not satisfied
  --> src/lib.rs:11:9
   |
11 | impl<T> Tr2 for B<T> where A<T>: Tr2 {}
   |         ^^^ the trait `std::marker::Copy` is not implemented for `T`
   |
   = help: consider adding a `where T: std::marker::Copy` bound
   = note: required because of the requirements on the impl of `std::marker::Copy` for `B<T>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

The latter should compile as well. 

Instances like this come up naturally when writing deriving macros: it's natural to write the constraint of the form `A<T>: Tr2` because that's the constraint on the underlying field. However, that fails to compile, and so it has to be rewritten to the form `T: Tr` which is not possible to produce by a proc-macro deriving.

**Comment by jonas-schievink** [comment] 2019-11-20 19:33
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2019-11-20 19:33 UTC
