### ISSUE TITLE
'missing lifetime specifier' regression in protobuf-1.0.1

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#27248] opened 2015-07-23 21:19 UTC
As [reported by crater](https://internals.rust-lang.org/t/new-crater-reports-1-1-stable-vs-beta-2015-07-10-and-nightly-2015-07-10/2358), Rust 1.3 nightlies appear to have [introduced a regression in lifetime elision](https://tools.taskcluster.net/task-inspector/#cuF_XQCSRQafsszsN6-0qw), probably related to default trait bounds.

cc @nikomatsakis @nrc @pnkfelix

Nominating in hopes a fix for this will appear before 1.3 beta.

**Comment by eefriedman** [comment] 2015-07-23 21:54
Reduces to:
```rust
fn main() {
    fn _message_down_cast(_m: &std::any::Any) -> &i8 {
        panic!()
    }
}
```

**Comment by eefriedman** [comment] 2015-07-24 04:55
[RFC 141](https://github.com/rust-lang/rfcs/blob/master/text/0141-lifetime-elision.md]) says that "a *lifetime position* is anywhere you can write a lifetime in a type".  According to that rule, `fn(m: &(Sized+'static)) -> &i8` is ambiguous because there are two lifetime positions in the input, and this isn't a bug.

On the other hand, I'm pretty sure that isn't actually what we want, so we need a more precise rule which specifies exactly what lifetimes qualify as a "lifetime position".

Other random observations: nightly accepts the following, but stable doesn't:
```rust
fn main() {
    type T<'a> = &'a &'a i8;
    fn s(m: T) -> &i8 { m }
    static S: i8 = 1;
    static S2: &'static i8 = &S;
    s(&S2);
}
```

Neither nightly nor stable accept the following:
```rust
fn main() {
    type T<'a> = &'a &'static i8;
    fn s(m: T) -> &i8 { m }
    static S: i8 = 1;
    static S2: &'static i8 = &S;
    s(&S2);
}
```

**Comment by arielb1** [comment] 2015-07-24 10:09
I think I accidentally introduced the regression as part of #26667. The previous version ignored object lifetime bounds - I should have caught this. I think the root cause here is that lifetime elision wasn't updated to respect object bounds.

**Comment by brson** [comment] 2015-09-10 23:50
@nikomatsakis Per [irlo](https://internals.rust-lang.org/t/regression-report-stable-2015-08-06-vs-nightly-2015-09-04/2618/4) this seems to affect some crates. Is there any way we can get this fixed this week in time for beta, or if not sometime in the next cycle for a backport?

**Comment by brson** [comment] 2015-09-11 04:16
cc @rust-lang/compiler

**Comment by nikomatsakis** [comment] 2015-09-11 14:10
triage: P-high

**Comment by nikomatsakis** [comment] 2015-09-11 14:10
Sorry, I dropped the ball on compiler triage, but trying to get that wagon back on track now. Anyway, I'll look at this.

**Comment by nikomatsakis** [comment] 2015-09-11 14:14
Ah, yes, I remember this issue now. I think this relates to the discussion about `'_`, and [this comment of mine][c] in particular. Basically I agree with @eefriedman that technically there is no bug here -- rather, a bug was fixed. *However,* the behavior doesn't seem right nonetheless, for the reasons I argued on the thread. It seems to me that trait object lifetimes, which follow distinct defaulting rules, should not affect elision in quite the way they currently do.

[c]: https://github.com/rust-lang/rfcs/pull/1177#issuecomment-124283746

**Comment by nikomatsakis** [comment] 2015-09-11 14:22
To be more specific, I think the rule we want is that object lifetimes only affect the elision rules if they are written *explicitly*, and not if defaults are used. I have to investigate how easy that will be to implement.

**Comment by nikomatsakis** [comment] 2015-09-11 14:23
cc @rust-lang/lang -- see previous two comments

**Comment by nikomatsakis** [comment] 2015-09-11 14:23
also cc @wycats -- see previous two comments

**Comment by nikomatsakis** [comment] 2015-09-11 14:33
OK, as I thought, the elision determination is made based on the `Ty<'tcx>`, which has no information about whether the object lifetime was derived from a default or not. So this would be mildly tricky to implement. Basically, we would want to walk the AST instead of the type, I think. Of course we're already doing this walk when we convert, so it might be nice if we could gather the information that we need as we do it. I'll have to think about it. But it IS an interesting question as to precisely what rules we want here that we ought to settle first.

I think that approaching this basic on the *position* where the lifetime appears is probably best. However, one might also approach by making special treatment for `'static` (after all, the object lifetime defaulting rules will either pick `'static`  or they will pick the lifetime of an enclosing `&` or some lifetime parameter placed on the trait, so if we behave differently around `'static` that would also cover this case). For example, one might expect this to compile:

```rust
struct Foo<'s> { x: &'s i32 }
fn foo(x: &Foo<'static>) -> &Foo<'static> { x }
fn main() { }
```

But it does not today, since there are two lifetimes (in principle) one might choose in the return type: the anonymous one, or `'static`. If we made the rules treat `'static` as "non-conflicting" -- i.e., only pick `'static` if there is nothing else to pick, it would address this case, but perhaps that is bit too creepy.

(Mostly just thinking through the possibilities here, not endorsing a plan of action.)

**Comment by nikomatsakis** [comment] 2015-09-11 14:34
I'm going to re-nominate, but this time for `T-lang`, since I think we need a policy call.

**Comment by brson** [comment] 2015-09-15 18:45
This is going into stable.

**Comment by aturon** [comment] 2015-09-15 19:12
Note: we need to discuss the logistics that let this slip through and try to make sure it doesn't happen again.

**Comment by arielb1** [comment] 2015-09-15 20:05
If we want to change this, it probably requires an RFC. The rules as they are today are somewhat confusing, which is somewhat inevitable with the invisible trait lifetime bounds.

The new rules means that code like
```Rust
fn foo(t: Box<Trait>) -> &u8
```

will compile with the interpretation `fn(Box<Trait+'static>) -> &'static u8`

Because duplicate lifetimes are ignored, this code can only cause an issue if either the user explicitly specifies an object lifetime bound (e.g. `fn foo<'a>(a: Box<Trait+'a>, b: &u8) -> &u8`), which I feel OK with breaking, or an object lifetime gets forced to `'static`.

My preferred solution is to prevent elision to `'static`, probably after a warning cycle with soft elision.

**Comment by nikomatsakis** [comment] 2015-09-17 21:56
We discussed in the language subteam meeting today and reached the conclusions that:

1. The current behavior is correct in that it follows the RFC.
2. Changes might be warranted but an RFC amendment is required, and further discussion would be helpful.

To that end, I'm going to close this issue and open (shortly) an RFC issue with a summary of the various cases that arise and the proposed solutions.

**Closed by nikomatsakis** 2015-09-17 21:56 UTC
Labels: I-needs-decision, I-nominated, I-stable-regression, P-high, T-lang
