### ISSUE TITLE
No warning issued for name clash.

### ISSUE THREAD

**Issue by sandeep-datta** [rust-lang/rust#34041] opened 2016-06-02 15:44 UTC
[Playpen][1]

```rust
pub trait Skip<I: Iterator> {
    fn skip(&mut self, steps: usize);
}

impl<I: Iterator> Skip<I> for I {
    fn skip(&mut self, mut steps: usize) {
        for _ in self {
            steps -= 1;
            if steps <= 0 {
                break;
            }
        }
    }
}

fn main() {
    let s  = "abc123def";
    let mut chars = s.chars();
    chars.skip(2);
    println!("{:?}", chars.collect::<String>());
}
```

Error:

    error: use of moved value: `chars` [--explain E0382]
      --> <anon>:20:22
    19 |>     chars.skip(2);
       |>     ----- value moved here
    20 |>     println!("{:?}", chars.collect::<String>());
       |>                      ^^^^^ value used here after move
    <anon>:20:22: 20:27: note: in this expansion of format_args!
    <anon>:20:22: 20:27: note: in this expansion of print! (defined in <std macros>)
    <anon>:20:22: 20:27: note: in this expansion of println! (defined in <std macros>)
    note: move occurs because `chars` has type `std::str::Chars<'_>`, which does not implement the `Copy` trait
    
    error: aborting due to previous error
    playpen: application terminated with error code 101

Also see: http://stackoverflow.com/a/37596285/39648

  [1]: https://play.rust-lang.org/?gist=82132ae019215582e5d2eae28b70c9a5&version=nightly&backtrace=0

**Comment by shepmaster** [comment] 2016-06-02 15:49
I would have expected the "multiple applicable methods in scope" message on the `chars.skip(2)` line. 

A smaller reproduction:

```rust
trait One: Sized {
    fn foo(self) { println!("One") }
}

trait Two {
    fn foo(&self) { println!("Two") }
}

impl One for i32 {}
impl Two for i32 {}

fn main() {
    42.foo();
}
```

If you change `One::foo` to accept `&self`, then the error occurs. Perhaps we are grouping methods by receiver type and picking the first?

**Comment by arielb1** [comment] 2016-06-02 15:55
duplicate of #33697. This is intended behaviour and would require an RFC to change. Maybe clippy could lint against it?

**Closed by arielb1** 2016-06-02 15:55 UTC

**Comment by shepmaster** [comment] 2016-06-02 16:16
> This is intended behaviour and would require an RFC to change

@arielb1 I'm not suggesting that the actual method lookup path change, just that the warning be generated based on the entire path, not just the first level. Do you think enhancing the warning requires an RFC?
