### ISSUE TITLE
Expected "type annotations needed", but inferred unit type instead

### ISSUE THREAD

**Issue by Riateche** [rust-lang/rust#96927] opened 2022-05-10 23:03 UTC
I tried this code:

```rust
fn main() -> serde_json::Result<()> {
    let v = serde_json::from_str("null")?;
    println!("{:?}", v);
    Ok(())
}
```

I expected to see this happen:
```
error[E0282]: type annotations needed
 --> src/main.rs:2:9
  |
2 |     let v = serde_json::from_str("null").unwrap();
  |         ^ consider giving `v` a type
```

Instead, this code compiles and outputs `()`, i.e. `v` is inferred to have type `()`.

The code continues to compile if `println` is removed. The inferred type can be confirmed with `type_name`:
```rust
fn print_name<T: core::any::Any>(_val: &T) {
    println!("{}", std::any::type_name::<T>());
}

fn main() -> serde_json::Result<()> {
    let v = serde_json::from_str("null")?;
    print_name(&v);
    Ok(())
}
```

The code stops compiling when `.unwrap()` is used instead of `?`.

### Meta

Tested on current stable (1.60.0) and nightly (1.62.0-nightly (2022-05-09 88860d5474a32f507dde)) at https://play.rust-lang.org/.

**Comment by compiler-errors** [comment] 2022-05-11 03:50
Huh, seems to be due to the default `C = ()` parameter on [`std::ops::ControlFlow`](https://doc.rust-lang.org/nightly/std/ops/enum.ControlFlow.html).

**Comment by compiler-errors** [comment] 2022-05-11 03:57
Actually, this behavior has existed ever since the `?` operator was stabilized back in like 1.13

**Comment by Xiretza** [comment] 2022-06-12 20:21
Duplicate of #94902.

**Comment by fmease** [comment] 2024-01-25 14:44
Closing in favor of #94902. If you disagree and I can always reopen this issue.

**Closed by fmease** 2024-01-25 14:44 UTC
Labels: T-compiler, A-inference, C-bug
