### ISSUE TITLE
diagnostic about typoed path separator could be better

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#84566] opened 2021-04-25 22:06 UTC
Given this code, where a path separator is typoed as a single instead of double colon:
```rust
struct Foo { a: () }

fn main() {
    Foo:new();        
}
```

the compiler currently outputs:

```
error[E0423]: expected value, found struct `Foo`
 --> src/main.rs:4:5
  |
1 | struct Foo { a: () }
  | -------------------- `Foo` defined here
...
4 |     Foo:new();        
  |     ^^^ help: use struct literal syntax instead: `Foo { a: val }`

error[E0412]: cannot find type `new` in this scope
 --> src/main.rs:4:9
  |
4 |     Foo:new();        
  |        -^^^ not found in this scope
  |        |
  |        help: maybe you meant to write a path separator here: `::`
```

This output is quite decent already: the second diagnostic correctly identifies that I meant to write a path separator and suggests a fix.  However, before I read the second diagnostic, I naturally read the first diagnostic, which is entirely unhelpful.  It would be better if the suggestion could be on the first diagnostic, or if the diagnostics could be combined in some way.

**Comment by nsunderland1** [comment] 2022-04-26 21:52
Another example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb829e88ed7b85f4d0bc0b6fc2b6f388

```rust
#[allow(unused)]
use tokio;
#[allow(unused)]
use std::time::Duration;

fn main() {
    tokio::time::sleep(Duration:from_millis(200))
}
```

The full output is this:

```
Compiling playground v0.0.1 (/playground)
error: invalid `struct` delimiters or `fn` call arguments
 [--> src/main.rs:7:5
](https://play.rust-lang.org/#)  |
7 |     tokio::time::sleep(Duration:from_millis(200))
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
help: if `tokio::time::sleep` is a struct, use braces as delimiters
  |
7 |     tokio::time::sleep { Duration:from_millis(200) }
  |                        ~                           ~
help: if `tokio::time::sleep` is a function, use the arguments directly
  |
7 -     tokio::time::sleep(Duration:from_millis(200))
7 +     tokio::time::sleep(from_millis(200))
  | 

error: could not compile `playground` due to previous error
```

This case doesn't suggest fixing the path separator at all, which is super confusing.

**Comment by fmease** [comment] 2024-12-28 00:44
Since the removal of the original type ascription syntax, the compiler output is:

```
error: path separator must be a double colon
 --> src/main.rs:4:8
  |
4 |     Foo:new();        
  |        ^
  |
help: use a double colon instead
  |
4 |     Foo::new();        
  |         +

error[E0599]: no function or associated item named `new` found for struct `Foo` in the current scope
 --> src/main.rs:4:9
  |
1 | struct Foo { a: () }
  | ---------- function or associated item `new` not found for this struct
...
4 |     Foo:new();        
  |         ^^^ function or associated item not found in `Foo`

```

Which I deem perfectly acceptable.

Similarly for https://github.com/rust-lang/rust/issues/84566#issuecomment-1110285486:

```
error: path separator must be a double colon
 --> src/main.rs:7:32
  |
7 |     tokio::time::sleep(Duration:from_millis(200))
  |                                ^
  |
help: use a double colon instead
  |
7 |     tokio::time::sleep(Duration::from_millis(200))
  |                                 +

error[E0308]: mismatched types
 --> src/main.rs:7:5
  |
6 | fn main() {
  |          - expected `()` because of default return type
7 |     tokio::time::sleep(Duration:from_millis(200))
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- help: consider using a semicolon here: `;`
  |     |
  |     expected `()`, found `Sleep`

```

**Comment by fmease** [comment] 2024-12-28 00:44
Since we have a (regression) test for this already like `tests/ui/suggestions/type-ascription-instead-of-path.rs` I'll just close this as completed!

**Closed by fmease** 2024-12-28 00:44 UTC
Labels: A-diagnostics, A-resolve, T-compiler, D-verbose, F-type_ascription
