### ISSUE TITLE
rustc fails to compile to asmjs on Windows

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#38489] opened 2016-12-20 08:41 UTC
After following the steps in the ["Compiling to the web with Rust and Emscripten" guide](https://users.rust-lang.org/t/compiling-to-the-web-with-rust-and-emscripten/7627), running `rustc --target=asmjs-unknown-emscripten hello.rs` gives the following output:

```
λ rustc --target=asmjs-unknown-emscripten hello.rs | clip
error: could not exec the linker `emcc`: The system cannot find the file specified. (os error 2)
  |
  = note: "emcc" "-L" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib" "hello.0.o" "-o" "hello.js" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libstd-17342542cc541012.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\librand-46ed9b788a6928f6.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libpanic_unwind-f78756b576499725.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcollections-e32369d7fef31fbf.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liballoc-24699c1ddb055eb0.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liballoc_system-3e467e865c8fa572.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libunwind-11f7709e0c71505b.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liblibc-60365c932e50e382.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\librustc_unicode-844a33a197b559a5.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcore-d9873b515905cac5.rlib" "C:\\Users\\crame\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcompiler_builtins-e428224f6caf212a.rlib" "-l" "c" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"

error: aborting due to previous error
```

See https://github.com/kripken/emscripten/issues/4741 for discussion. @juj believes it to be an issue with `rustc` invoking `emcc` without enabling shell expansion.

**Comment by schulzch** [comment] 2016-12-21 14:52
[Potential fix](https://github.com/schulzch/rust/commit/8b70cb405ba5f226d2b4d397bb20c483bfa43152)  for #38489 - not sure if there is a better way.

**Comment by schulzch** [comment] 2016-12-22 16:27
Invoking `emcc.bat` fixes the error above, even though another one pops up:
```
"emcc.bat" "-L" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib" "hello.0.o" "-o" "hello.js" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libstd-7b9cfd6f0a997baf.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\librand-1f96068a42f0a0b6.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcollections-b4791b2dfe46be1e.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libstd_unicode-7b202cc7d92cb8d1.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libpanic_unwind-2f1533adf7ff3ff3.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libunwind-de8aa143210530bf.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liballoc-211bab41c663db5f.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liballoc_system-8e09e9870a86b3c0.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liblibc-2b71c62d09e24a20.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcore-fe91fc115ee44cb0.rlib" "C:\\Projects\\rust\\build\\x86_64-pc-windows-msvc\\stage1\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcompiler_builtins-957f2e3e652a4694.rlib" "-l" "c" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
python: can't open file 'C:\Projects\hello-rs\\emcc': [Errno 2] No such file or directory
```

Removing the quotes around `emcc.bat` or invoking `"%EMSCRIPTEN%\emcc.bat"` would fix this. Ideas?

**Comment by chris-morgan** [comment] 2016-12-24 10:41
Here is a workaround: instead of invoking `cargo build --target=asmjs-unknown-emscripten`, invoke `cargo rustc --target=asmjs-unknown-emscripten -- -C linker=emcc.bat`.

(*Wow*, it takes a long time—90 seconds until it fails in optimisation for a very basic thing seems inordinate!)

**Comment by RReverser** [comment] 2016-12-29 21:22
Same, when trying to invoke given `emcc` command directly, getting instead:

```
error: Unknown attribute kind (52)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Invalid type for value
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (52)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Invalid type for value
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (48)
error: Unknown attribute kind (52)
Traceback (most recent call last):
  File "C:\Program Files\Emscripten\emscripten\1.35.0\\emcc", line 1309, in <module>
    final = shared.Building.llvm_opt(final, link_opts, DEFAULT_FINAL)
  File "C:\Program Files\Emscripten\emscripten\1.35.0\tools\shared.py", line 1471, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations:
```

**Comment by RReverser** [comment] 2016-12-29 21:23
Ah, this seems to be rather related to https://github.com/rust-lang/rust/issues/38588

**Comment by schulzch** [comment] 2016-12-29 22:25
Indeed. PR #38601 is work in progress.
Also emscripten 1.35.0 (latest pre-build binary) does not work (see llvm assertion above). I haven't had the chance to try out emscripten 1.37.0 (`emsdk install sdk-incoming-64bit`)

**Comment by RReverser** [comment] 2016-12-29 23:47
@schulzch Yep, that's what was suggested in that other issue and I can confirm it works.

**Comment by schulzch** [comment] 2016-12-30 01:38
For the sake of completeness, I finally had the time to test everything. This works for windows:

Get emscripten 1.37.0:

1. Install VS 2013 Community (required by emscripten)
2. `"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64`
3. `emsdk install sdk-incoming-64bit`
4. `emsdk activate sdk-incoming-64bit`

Rewire rustc to `emcc.bat`:

- Workaround for rust 1.14: `rustc --target=asmjs-unknown-emscripten -C linker=emcc.bat`
- Fix: PR #38601

I guess `rustc` should check for a minimal required emscripten version, but this is probably out of scope.

**Comment by brson** [comment] 2016-12-30 23:38
Thanks for the investigations and the patch @RReverser @schulzch @cramertj @chris-morgan

**Comment by brson** [comment] 2017-01-03 21:00
Looks like the fix is merged.

**Closed by brson** 2017-01-03 21:00 UTC
Labels: A-asmjs, A-wasm

**Comment by jeffwllms** [comment] 2017-03-07 19:50
I get the same error.  Unless I run rustc from the same cmd windows I used to run emsdk activate.  Running emsdk activate with --global doe not seem to change anything.  This may just be how it is intended to work.

**Comment by RReverser** [comment] 2017-03-07 23:07
@jeffwllms Did you run emsdk activate --global in elevated cmd? That's what it would take for it to work and permanently store generated environment variables in registry.
