### ISSUE TITLE
Empty top-level doc comment causes panic when trying to run doc tests (index out of bounds).

### ISSUE THREAD

**Issue by d2718** [rust-lang/rust#96266] opened 2022-04-21 01:23 UTC
### Code

A minimal example involves a brand new lib crate (`cargo new --lib bug_report`) with a single file containing code: `src/lib.rs`. Both `cargo test` and `cargo doc` cause a panic when reaching the doc tests. If there is text in the top-level doc comment, the panic doesn't happen.

Contents of `src/lib.rs`:

```Rust
/*!
*/

pub fn foo() {
    println!("Foo!");
}

#[cfg(test)]
mod tests {

    #[test]
    fn should_be_fine() {
        ()
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

### Error output

```
dan@lauDANum:~/dev/bug_report$ RUST_BACKTRACE=full cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests (target/debug/deps/bug_report-c2e012fdc0118790)

running 1 test
test tests::should_be_fine ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/bug_report-40b3e22a725fc2c3)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bug_report
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/rustc_ast/src/util/comments.rs:55:28
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```

stack backtrace:
   0:     0x7ff9054ee86d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff9054ee86d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff9054ee86d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7ff9054ee86d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7ff90554e4ec - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7ff9054dea98 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7ff9054f2847 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7ff9054f2847 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7ff9054f2847 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7ff9054f2510 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7ff905c7e2c1 - rustc_driver[6eeb127b85fe99ac]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7ff9054f3124 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
  12:     0x7ff9054f2dd7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  13:     0x7ff9054eed34 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7ff9054f2ae9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  15:     0x7ff9054bb863 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  16:     0x7ff9054bb7a2 - core::panicking::panic_bounds_check::h7777e18766a27b0b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
  17:     0x7ff906e1ba42 - rustc_ast[47f98cd2af115e8]::util::comments::beautify_doc_string
  18:     0x564bf1a297e5 - <&mut <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#0} as core[2734bb1f7d9ec6a5]::ops::function::FnMut<((&rustc_ast[47f98cd2af115e8]::ast::Attribute, core[2734bb1f7d9ec6a5]::option::Option<rustc_span[4b4bb4534443c42f]::def_id::DefId>),)>>::call_mut
  19:     0x564bf1a0e80c - <core[2734bb1f7d9ec6a5]::iter::adapters::chain::Chain<core[2734bb1f7d9ec6a5]::iter::adapters::flatten::FlatMap<core[2734bb1f7d9ec6a5]::option::IntoIter<(&[rustc_ast[47f98cd2af115e8]::ast::Attribute], rustc_span[4b4bb4534443c42f]::def_id::DefId)>, core[2734bb1f7d9ec6a5]::iter::adapters::map::Map<core[2734bb1f7d9ec6a5]::slice::iter::Iter<rustc_ast[47f98cd2af115e8]::ast::Attribute>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#1}::{closure#0}>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#1}>, core[2734bb1f7d9ec6a5]::iter::adapters::map::Map<core[2734bb1f7d9ec6a5]::slice::iter::Iter<rustc_ast[47f98cd2af115e8]::ast::Attribute>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#2}>> as core[2734bb1f7d9ec6a5]::iter::traits::iterator::Iterator>::try_fold::<(), core[2734bb1f7d9ec6a5]::iter::traits::iterator::Iterator::find_map::check<(&rustc_ast[47f98cd2af115e8]::ast::Attribute, core[2734bb1f7d9ec6a5]::option::Option<rustc_span[4b4bb4534443c42f]::def_id::DefId>), rustc_ast[47f98cd2af115e8]::ast::Attribute, &mut <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#0}>::{closure#0}, core[2734bb1f7d9ec6a5]::ops::control_flow::ControlFlow<rustc_ast[47f98cd2af115e8]::ast::Attribute>>
  20:     0x564bf19c3c65 - <alloc[9a009599db7253ec]::vec::Vec<rustc_ast[47f98cd2af115e8]::ast::Attribute> as alloc[9a009599db7253ec]::vec::spec_from_iter::SpecFromIter<rustc_ast[47f98cd2af115e8]::ast::Attribute, core[2734bb1f7d9ec6a5]::iter::adapters::filter_map::FilterMap<core[2734bb1f7d9ec6a5]::iter::adapters::chain::Chain<core[2734bb1f7d9ec6a5]::iter::adapters::flatten::FlatMap<core[2734bb1f7d9ec6a5]::option::IntoIter<(&[rustc_ast[47f98cd2af115e8]::ast::Attribute], rustc_span[4b4bb4534443c42f]::def_id::DefId)>, core[2734bb1f7d9ec6a5]::iter::adapters::map::Map<core[2734bb1f7d9ec6a5]::slice::iter::Iter<rustc_ast[47f98cd2af115e8]::ast::Attribute>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#1}::{closure#0}>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#1}>, core[2734bb1f7d9ec6a5]::iter::adapters::map::Map<core[2734bb1f7d9ec6a5]::slice::iter::Iter<rustc_ast[47f98cd2af115e8]::ast::Attribute>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#2}>>, <rustdoc[a32c9c6374e2ed81]::clean::types::Attributes>::from_ast::{closure#0}>>>::from_iter
  21:     0x564bf1a7b799 - <rustdoc[a32c9c6374e2ed81]::doctest::HirCollector>::visit_testable::<rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  22:     0x564bf1b609a3 - <rustc_interface[afc566840a941718]::passes::QueryContext>::enter::<rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}::{closure#0}::{closure#0}, rustdoc[a32c9c6374e2ed81]::doctest::Collector>
  23:     0x564bf1ace8af - <rustc_interface[afc566840a941718]::interface::Compiler>::enter::<rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  24:     0x564bf1b2bbca - rustc_span[4b4bb4534443c42f]::with_source_map::<core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustc_interface[afc566840a941718]::interface::create_compiler_and_run<core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}>::{closure#1}>
  25:     0x564bf1abc5f0 - rustc_interface[afc566840a941718]::interface::create_compiler_and_run::<core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}>
  26:     0x564bf194c58e - <scoped_tls[bdf82395e763c2d2]::ScopedKey<rustc_span[4b4bb4534443c42f]::SessionGlobals>>::set::<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  27:     0x564bf1a99dca - std[cd3cf6af28dff6de]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>
  28:     0x564bf194c0f7 - <<std[cd3cf6af28dff6de]::thread::Builder>::spawn_unchecked_<rustc_interface[afc566840a941718]::util::run_in_thread_pool_with_globals<rustc_interface[afc566840a941718]::interface::run_compiler<core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>, rustdoc[a32c9c6374e2ed81]::doctest::run::{closure#1}>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#0}, core[2734bb1f7d9ec6a5]::result::Result<(alloc[9a009599db7253ec]::vec::Vec<test[779f73948b3cbc30]::types::TestDescAndFn>, alloc[9a009599db7253ec]::sync::Arc<std[cd3cf6af28dff6de]::sync::mutex::Mutex<alloc[9a009599db7253ec]::vec::Vec<rustdoc[a32c9c6374e2ed81]::doctest::UnusedExterns>>>, usize), rustc_errors[bd800fb2a5e0b9f5]::ErrorReported>>::{closure#1} as core[2734bb1f7d9ec6a5]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7ff9054fed03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  30:     0x7ff9054fed03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  31:     0x7ff9054fed03 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  32:     0x7ff905423d80 - start_thread
                               at ./nptl/./nptl/pthread_create.c:481:8
  33:     0x7ff9051c776f - clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  34:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0 (7737e0b5c 2022-04-04) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no

query stack during panic:
end of query stack
error: test failed, to rerun pass '--doc'
```

</p>
</details>

**Comment by csmoe** [comment] 2022-04-21 04:36
Duplicate of #96201

**Closed by csmoe** 2022-04-21 04:36 UTC
Labels: I-ICE, T-compiler, C-bug
