### ISSUE TITLE
Crash (SEGFAULT) when building Firefox for ARMv7 or x86 Android with 1.72

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#115142] opened 2023-08-23 18:30 UTC
Building Firefox for the thumbv7neon-linux-androideabi and i686-linux-android fails with a rust compiler crash:
```
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x3116d63)[0x7fd329284d63]
/lib/x86_64-linux-gnu/libc.so.6(+0x3bf90)[0x7fd325e27f90]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm12DIExpression15getFragmentInfoENS0_16expr_op_iteratorES1_+0x21)[0x7fd3231624e1]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x65f448b)[0x7fd3231f448b]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x661387c)[0x7fd32321387c]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit24constructVariableDIEImplERKNS_11DbgVariableEb+0xf19)[0x7fd322c9f459]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x4a9)[0x7fd322a73469]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit25createAndAddScopeChildrenEPNS_12LexicalScopeERNS_3DIEE+0x729)[0x7fd322a736e9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DwarfCompileUnit27constructSubprogramScopeDIEEPKNS_12DISubprogramEPNS_12LexicalScopeE+0xe9)[0x7fd322c9fde9]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm10DwarfDebug15endFunctionImplEPKNS_15MachineFunctionE+0x210)[0x7fd322c9c650]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm16DebugHandlerBase11endFunctionEPKNS_15MachineFunctionE+0x5e)[0x7fd322d4031e]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm10AsmPrinter16emitFunctionBodyEv+0x1a5b)[0x7fd322b8511b]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x7c7f637)[0x7fd32487f637]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(+0x7c7f637)[0x7fd32487f637]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0xc02)[0x7fd32293a018]
/builds/worker/fetches/rustc/lib/libLLVM-16-rust-1.72.0-nightly.so(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x26d)[0x7fd3229a7b39]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x273ce36)[0x7fd3288aae36]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x273c838)[0x7fd3288aa838]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x273a9d8)[0x7fd3288a89d8]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x2602f27)[0x7fd328770f27]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x2602467)[0x7fd328770467]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x2600794)[0x7fd32876e794]
/builds/worker/fetches/rustc/lib/librustc_driver-796e47691512e4e9.so(+0x25f9ce6)[0x7fd328767ce6]
/builds/worker/fetches/rustc/lib/libstd-fe004512c8383174.so(rust_metadata_std_49ba9e76e27f693e+0x1032d5)[0x7fd3260e52d5]
/lib/x86_64-linux-gnu/libc.so.6(+0x88fd4)[0x7fd325e74fd4]
/lib/x86_64-linux-gnu/libc.so.6(__clone+0x40)[0x7fd325ef4820]
```

I wish I could give something more detailed, but I haven't had the time to try to yet. I however identified the regression to come from 642c92e63008ffb49f6ad8344e07bfa7d5b0d9bb (Enable ScalarReplacementOfAggregates in optimized builds) and building with `-Zmir-enable-passes=-ScalarReplacementOfAggregates` avoids the crash.

**Comment by saethlin** [comment] 2023-08-23 18:38
Duplicate of https://github.com/rust-lang/rust/issues/115113

**Comment by apiraino** [comment] 2023-08-24 12:54
going to close as such.

thanks for reporting @glandium !

**Closed by apiraino** 2023-08-24 12:54 UTC
Labels: C-bug
