### ISSUE TITLE
`rustdoc`: "Methods from `Deref`" section references functions from completely unrelated types.

### ISSUE THREAD

**Issue by olson-sean-k** [rust-lang/rust#128124] opened 2024-07-24 01:06 UTC
I recently published [a crate](https://crates.io/crates/mitsein) with types that implement `Deref`. On `docs.rs`, version `0.2.0` of this crate shows [incorrect and **completely unrelated** methods](https://docs.rs/mitsein/0.2.0/mitsein/vec1/type.Vec1.html#deref-methods-Slice1%3CT%3E) for the `Deref` implementation for `Vec1`. I see the same thing when I build the documentation with recent versions of the nightly toolchain locally (including but not limited to `1.78.0-nightly (f4b771bf1 2024-03-14)`).

I only expect the methods [of this type (`Slice1`)](https://docs.rs/mitsein/0.2.0/mitsein/slice1/type.Slice1.html) to show up in the `Deref` section for `Vec1`. However, completely unrelated methods [like this](https://docs.rs/mitsein/0.2.0/mitsein/vec1/type.Vec1.html#method.as_vec_deque) from this [unrelated type](https://docs.rs/mitsein/0.2.0/mitsein/vec_deque1/type.VecDeque1.html#method.as_vec_deque) are shown in this section, causing a very large, misleading, and mostly useless list of functions to display.

There are some open bugs regarding the "Methods from `Deref`" section, but none that seem to observe such unrelated functions. Sorry if I missed something and this is a duplicate and thanks for taking a look!

**Comment by theemathas** [comment] 2024-07-24 03:32
MCVE:

```rust
use std::ops::Deref;

pub struct NonEmpty<T: ?Sized>(T);

pub type Slice1 = NonEmpty<[i32]>;
pub type Vec1 = NonEmpty<Vec<i32>>;
pub type Unrelated = NonEmpty<()>;

impl Deref for Vec1 {
    type Target = Slice1;

    fn deref(&self) -> &Self::Target {
        unimplemented!()
    }
}

impl Unrelated {
    pub fn unrelated_method(&self) {}
}
```

Running `cargo doc --open`, and navigating to the `Vec1` documentation, gives the following:

<img width="414" alt="image" src="https://github.com/user-attachments/assets/67a0f2fa-aa5e-458d-974c-247c11a1c0ee">

**Comment by theemathas** [comment] 2024-07-24 03:36
MCVE:

```rust
use std::ops::Deref;

pub struct Common<T>(T);

pub type RefType = Common<i32>;
pub type Unrelated = Common<i64>;

pub struct OwnedType;

impl Deref for OwnedType {
    type Target = RefType;

    fn deref(&self) -> &Self::Target {
        unimplemented!()
    }
}

impl Unrelated {
    pub fn unrelated_method(&self) {}
}
```

Running `cargo doc --open`, and navigating to the `OwnedType` documentation, gives the following:

<img width="419" alt="image" src="https://github.com/user-attachments/assets/cac5b015-4918-4d06-b5c6-f089014531ce">

**Comment by theemathas** [comment] 2024-07-24 03:40
Duplicate of #24686

**Comment by tgross35** [comment] 2024-07-24 07:04
Thanks @olson-sean-k for filing this issue, and @theemathas for finding the duplicate. Closing as such.

Kind of unfortunate that issue has been around for as long as it has, probably needs somebody to dig a bit and see if solving it has since gotten easier.

**Closed by tgross35** 2024-07-24 07:04 UTC
Labels: T-rustdoc, C-bug, needs-triage
