### ISSUE TITLE
Internal compiler error encountered while using Nightly v1.51.0-nightly (04caa632d 2021-01-30)

### ISSUE THREAD

**Issue by saki-osive** [rust-lang/rust#81690] opened 2021-02-03 03:36 UTC
While building Polkadot, I encountered this error at the module `Compiling libp2p-mdns v0.26.0`

### Code

The code lives here: https://github.com/paritytech/polkadot

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1

```

### Error output

```
Compiling libp2p-mdns v0.26.0
error: internal compiler error: failed to process buffered lint here
   --> /home/vagrant/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.26.0/src/service.rs:293:37
    |
293 |                         Err(err) => log::error!("if watch returned an error: {}", err),
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `libp2p-mdns`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `polkadot v0.8.27 (https://github.com/paritytech/polkadot?tag=v0.8.27#2f845699)`, intermediate artifacts can be found at `/tmp/cargo-install30MKt1`

Caused by:
  build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-03 12:18
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-03 12:18 UTC
Labels: C-bug, I-ICE, T-compiler
