### ISSUE TITLE
Miscompile with nested slice patterns

### ISSUE THREAD

**Issue by eefriedman** [rust-lang/rust#26157] opened 2015-06-09 23:35 UTC
Testcase:
```rust
#![feature(slice_patterns)]
fn main() { let x: &[String] = &[]; match x { [[b..]..] => { println!("Fun{}", b.len()); } } }
```

Running this gives `playpen: application terminated abnormally with signal 4 (Illegal instruction)`.  A quick look at the IR shows that b somehow ends up uninitialized.

**Comment by arielb1** [comment] 2015-06-10 18:28
Duplicate of #26158 (this seems like a soundness issue, not a miscompilation).

**Closed** 2015-06-10 18:30 UTC
