### ISSUE TITLE
Recursive type with `Cow`, `'static` and slice triggers "overflow evaluating the requirement"

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#47032] opened 2017-12-27 16:28 UTC
The following compiles with rustc 1.7.0 and earlier, but not in 1.8.0 and later:

```rust
use std::borrow::Cow;

#[derive(Clone)]
pub struct Node {
	// ...
	pub children_a: &'static [Node], // Works
	pub children_b: Vec<Node>, // Works
	pub children_c: Cow<'static, [Node]> // Doesn't compile
}
```

The errors:
```
error[E0275]: overflow evaluating the requirement `<[Node] as std::borrow::ToOwned>::Owned`
 --> src/lib.rs:6:2
  |
6 |     pub children_a: &'static [Node],
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: required because it appears within the type `Node`
  = note: required because of the requirements on the impl of `std::borrow::ToOwned` for `[Node]`
  = note: required because it appears within the type `Node`
  = note: slice and array elements must have `Sized` type
```

Since it compiles fine with the first two members (reference to slice, and Vec), I'd expect a Cow of a slice to also work. Is this a regression, or is this supposed to not compile?

**Comment by sgrif** [comment] 2018-01-03 22:14
This is related to https://github.com/rust-lang/rust/issues/34260

**Comment by nikomatsakis** [comment] 2018-02-01 15:32
triage: P-medium

@sgrif and I are working on this a bit =)

**Comment by jesskfullwood** [comment] 2019-02-14 09:55
Is there a workaround for this? It has me completely stumped

**Comment by bkchr** [comment] 2019-02-28 08:28
@nikomatsakis any update on this?

**Comment by Licenser** [comment] 2019-05-16 08:19
Same, ran into this too and unsure how to resolve this. It seems it's a regression from 2016?

**Comment by kyleedwardsny** [comment] 2019-12-24 17:52
I believe I found a workaround until this is fixed. The trick is to put the `Cow` inside a dummy struct:

```rust
#[derive(Clone)]
pub struct DummyHolder<T> {
    pub data: T,
}

#[derive(Clone)]
pub struct Node {
    pub children: DummyHolder<Cow<'static, [Node]>>,
}
```

**Comment by kyleedwardsny** [comment] 2019-12-24 18:07
I just made an interesting discovery. The following does not compile:

```rust
#[derive(Clone)]
pub struct DummyHolder<T: ?Sized> { // <-- Triggers the error
    pub data: T,
}

#[derive(Clone)]
pub struct Node {
    pub children: DummyHolder<Cow<'static, [Node]>>,
}
```

So it seems that enforcing a `Sized` constraint somewhere in the loop makes this example compile (`Cow` allows the borrowed type to be `?Sized`.)

**Comment by Enselic** [comment] 2024-11-26 05:56
Triage: This began to compile in 1.79 and was retroactively stabilized via FCP. See https://github.com/rust-lang/rust/issues/129541 for details.

Regression test added via https://github.com/rust-lang/rust/pull/133473/files which I bet is equivalent to the code in this issue.

Closing as duplicate of #100347 although it should probably be the other way around since this issue is much older.

**Closed by Enselic** 2024-11-26 05:56 UTC
Labels: P-medium, T-compiler, regression-from-stable-to-stable, C-bug
