### ISSUE TITLE
Support multiple `#[unstable]` features for library item

### ISSUE THREAD

**Issue by Noratrieb** [rust-lang/rust#134319] opened 2024-12-14 22:56 UTC
Sometimes a library item is unstable for multiple reasons, for example implementing an unstable trait for an unstable type (in this case it matters less because of impl stability rules being a bit special but it happens in other cases too).

desired example:
```rust
#[unstable(feature = "unique_rc_arc", issue = "112566")]
#[unstable(feature = "pin_coerce_unsized_trait", issue = "123430")]
unsafe impl<T: ?Sized, A: Allocator> PinCoerceUnsized for UniqueRc<T, A> {}
```

This way, when one feature is stabilized, the other unstable attribute is still present, ensuring that it's still unstable (the stable attribute shouldn't be added in that case of course).

User code would then also have to enable all the feature gates to use it (of course for trait impls that doesn't apply again).

**Comment by fmease** [comment] 2024-12-14 23:19
Dupe of #94770?

**Comment by Noratrieb** [comment] 2024-12-14 23:28
yes. i tried searching for it but was unable to find anything (even my most precise keywords yielded dozens of results)

**Closed** 2024-12-14 23:29 UTC
Labels: A-stability, T-compiler, C-feature-request, F-staged_api

**Comment by fmease** [comment] 2024-12-15 00:28
I found it via `in:title unstable attribute` which narrowed it down to just 4 open issues. `in:title` often comes in clutch :^)

**Comment by Noratrieb** [comment] 2024-12-15 09:09
ohhhhhhhhhh, I was not aware of that search modifier. thanks
