### ISSUE TITLE
[1.38] Regression: failed to resolve: could not find `rustc_serialize` in `{{root}}`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63885] opened 2019-08-25 16:41 UTC
https://github.com/rust-lang/rust/issues/63628#issuecomment-524585041

Caused by https://github.com/rust-lang/rust/pull/63449.
Tests in `rustc-serialize` and its fork `rustc-serialize2` are broken, no other crates are affected.
(Can be fixed with `extern crate self as rustc_serivalize;`.)
Probably no action required.

**Comment by nikomatsakis** [comment] 2019-09-05 14:20
Check-in from compiler team:

This is some sort of issue triggered by upgrading RustcSerialize to Rust 2018. It is specific to the rustc-serialize crate itself, as partially caused by having `derive(RustcSerialize)` in a "semi-blessed" state, i.e., built-in to compiler but also in a crate. Not a general purpose problem. Closing as "no action required".

**Closed by nikomatsakis** 2019-09-05 14:20 UTC
Labels: T-compiler, regression-from-stable-to-beta

**Comment by petrochenkov** [comment] 2019-09-05 14:28
The reason of breakage is that https://github.com/rust-lang/rust/pull/63449 migrated `derive(RustcEncodable, RustcDecodable)` to 2018 edition as a part of compiler simplification (these macros now take their edition from libcore in which they are defined).

As a result, code like this was broken:
```rust
extern crate serialize;
use serialize as rustc_serialize;

// uses `::rustc_serialize` internally,
// on 2018 edition it means *crate* rustc_serialize,
// not a name in root module.
#[derive(RustcEncodable)]
struct S;
```

Code like this appears either in code using unstable crate `serialize` from sysroot, or inside `rustc-serialize` itself in testing mode, which uses a similar construction:
```
mod rustc_serialize {
    pub use serialize::*;
}

#[derive(RustcEncodable)]
struct S;
```
