### ISSUE TITLE
cargo doc on windows doesn't work

### ISSUE THREAD

**Issue by Dragonrun1** [rust-lang/rust#61975] opened 2019-06-19 22:04 UTC
Let me know if you need anything more than this to help track it down.

error: internal compiler error: src\librustc\hir\def_id.rs:51: Tried to get crate index of builtin macros crat
e

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:643:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (04a3dd8a8 2019-06-18) running on x86_64-pc-windows-msvc

error: Could not document `cfg-if`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name cfg_if C:\Users\mgcum\.cargo\registry\src\github.com
-1ecc6299db9ec823\cfg-if-0.1.2\src\lib.rs --cap-lints allow --color always -o C:\repos\local\rustyhp\target\do
c -L dependency=C:\repos\local\rustyhp\target\debug\deps` (exit code: 1)

**Comment by jonas-schievink** [comment] 2019-06-19 22:08
Duplicate of https://github.com/rust-lang/rust/issues/61804

**Closed by jonas-schievink** 2019-06-19 22:08 UTC
