### ISSUE TITLE
ICE: index out of bounds when using #[lang = "panic_location"]

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/rust#78031] opened 2020-10-16 23:50 UTC
### Code

```Rust
#![feature(no_core)]
#![feature(lang_items)]
#![feature(optin_builtin_traits)]
#![feature(associated_type_defaults)]
#![no_core]
#![no_main]

#[lang = "panic_location"]
struct P;

#[lang = "sized"]
auto trait Sized { }

#[lang = "copy"]
auto trait Copy { }

#[lang = "add"]
trait Add<Rhs = Self>: Sized {
    type Output = Self;

    fn add(self, other: Rhs) -> Self::Output;
}

impl Add for i32 {
    fn add(self, other: i32) -> i32 {
        self + other
    }
}

pub fn f() -> i32 {
    2.add(2)
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.48.0-nightly (7f7a1cbfd 2020-09-27)
binary: rustc
commit-hash: 7f7a1cbfd3b55daee191247770627afab09eece2
commit-date: 2020-09-27
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

### Error output

```
error: internal compiler error: unexpected panic
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/rustc_target/src/abi/mod.rs:695:59
stack backtrace:
   0:     0x7fdc1b6d8680 - std::backtrace_rs::backtrace::libunwind::trace::he85dfb3ae4206056
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7fdc1b6d8680 - std::backtrace_rs::backtrace::trace_unsynchronized::h1ad28094d7b00c21
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7fdc1b6d8680 - std::sys_common::backtrace::_print_fmt::h901b54610713cd21
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/sys_common/backtrace.rs:79
   3:     0x7fdc1b6d8680 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0ad78ee1571f7e0
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/sys_common/backtrace.rs:58
   4:     0x7fdc1b7465ac - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/core/src/fmt/mod.rs:1080
   5:     0x7fdc1b6ca9a2 - std::io::Write::write_fmt::hf7b7d7b243f84a36
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/io/mod.rs:1516
   6:     0x7fdc1b6dd1ed - std::sys_common::backtrace::_print::hd093978a5287b8ff
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/sys_common/backtrace.rs:61
   7:     0x7fdc1b6dd1ed - std::sys_common::backtrace::print::h20f46787581d56d7
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/sys_common/backtrace.rs:48
   8:     0x7fdc1b6dd1ed - std::panicking::default_hook::{{closure}}::h486cbb4b82ffc357
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/panicking.rs:208
   9:     0x7fdc1b6dce98 - std::panicking::default_hook::h4190c9e3edd4d591
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/panicking.rs:227
  10:     0x7fdc1bf64e44 - rustc_driver::report_ice::h33b98c6312de22d9
  11:     0x7fdc1b6dda36 - std::panicking::rust_panic_with_hook::h72e78719cdda225c
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/panicking.rs:581
  12:     0x7fdc1b6dd5b9 - std::panicking::begin_panic_handler::{{closure}}::h8bd07dbd34150a96
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/panicking.rs:484
  13:     0x7fdc1b6d8b0c - std::sys_common::backtrace::__rust_end_short_backtrace::hdb6b3066ad29028a
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/sys_common/backtrace.rs:153
  14:     0x7fdc1b6dd579 - rust_begin_unwind
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/panicking.rs:483
  15:     0x7fdc1b7430c1 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/core/src/panicking.rs:85
  16:     0x7fdc1b743082 - core::panicking::panic_bounds_check::hec58b3e6eeb445f1
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/core/src/panicking.rs:62
  17:     0x7fdc1f0088f4 - rustc_target::abi::FieldsShape::offset::h1cbd516eb57ef038
  18:     0x7fdc1d64aaf5 - rustc_mir::interpret::intrinsics::caller_location::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::alloc_caller_location::h446f1ef12298dda2
  19:     0x7fdc1d2b115d - rustc_mir::const_eval::const_caller_location::h293704febfdb50de
  20:     0x7fdc1c30c799 - rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_caller_location>::compute::h1d224cb05ab5cab6
  21:     0x7fdc1c35df0d - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl::h224107c598c6a1ec
  22:     0x7fdc1c3e01af - rustc_data_structures::stack::ensure_sufficient_stack::h96b8ac0f1c461eee
  23:     0x7fdc1c2daa1c - rustc_query_system::query::plumbing::get_query_impl::h622ead14a2bdd11e
  24:     0x7fdc1c313ca4 - rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::get_caller_location::habf054de751cf5d3
  25:     0x7fdc1c3116fe - rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_block::h2f244e07e56ea3d8
  26:     0x7fdc1c30df9e - rustc_codegen_ssa::mir::codegen_mir::h8d642bcb147d41c1
  27:     0x7fdc1c41fc68 - rustc_codegen_ssa::base::codegen_instance::h894322accffbeb70
  28:     0x7fdc1c27d604 - <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define::h39a2dd069eed710b
  29:     0x7fdc1c2c0ceb - rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::hb573a456da1f50eb
  30:     0x7fdc1c369e8a - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h9e34e57f77fd95f5
  31:     0x7fdc1c2c080a - rustc_codegen_llvm::base::compile_codegen_unit::h6bde4cdd8ac24228
  32:     0x7fdc1c41dc60 - rustc_codegen_ssa::base::codegen_crate::h1469a17db97addb4
  33:     0x7fdc1c416a85 - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h213008e5539f00d1
  34:     0x7fdc1c1b8bb1 - rustc_interface::passes::QueryContext::enter::h696fdc98b1a21464
  35:     0x7fdc1c1fbf83 - rustc_interface::queries::Queries::ongoing_codegen::h14106579db5182fd
  36:     0x7fdc1bfb0454 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::he4e35b4eaa2694c6
  37:     0x7fdc1bf44527 - rustc_span::with_source_map::hb500901462ee52b5
  38:     0x7fdc1bfb2488 - rustc_interface::interface::create_compiler_and_run::heaaaf154744ddc30
  39:     0x7fdc1bf9792a - scoped_tls::ScopedKey<T>::set::h3b254e0349c75e04
  40:     0x7fdc1bfb4673 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1aa7101e3f5fb15d
  41:     0x7fdc1bf304de - core::ops::function::FnOnce::call_once{{vtable.shim}}::h31069caa752da237
  42:     0x7fdc1b6ec70a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1080dfe0ef616bdf
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/alloc/src/boxed.rs:1042
  43:     0x7fdc1b6ec70a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd2747e1f2d5cec32
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/alloc/src/boxed.rs:1042
  44:     0x7fdc1b6ec70a - std::sys::unix::thread::Thread::new::thread_start::hd0f336b4ef6808a7
                               at /rustc/7f7a1cbfd3b55daee191247770627afab09eece2/library/std/src/sys/unix/thread.rs:87
  45:     0x7fdc1b5f23e9 - start_thread
  46:     0x7fdc1b51a293 - __GI___clone
  47:                0x0 - <unknown>
```

</p>
</details>

**Comment by GoldsteinE** [comment] 2020-10-16 23:51
Removing `auto` from `auto trait Copy` gives new, different ICE.

**Comment by jonas-schievink** [comment] 2020-10-16 23:58
Duplicate of https://github.com/rust-lang/rust/issues/9307

**Closed by jonas-schievink** 2020-10-16 23:58 UTC
Labels: C-bug, I-ICE, T-compiler
