### ISSUE TITLE
Block doc comments incorrectly processed into attributes

### ISSUE THREAD

**Issue by myrrlyn** [rust-lang/rust#53478] opened 2018-08-18 22:50 UTC
It seems that I am the only remaining Rust programmer who uses these, which is why this hasn't (to my knowledge) been reported before; and because I read early on that some folks considered block comments to be unofficially deprecated, I assumed that reporting this bug would go nowhere and have been sitting on it for two years.

Block comments with a left column of stars do not have the stars stripped during comment-to-attribute conversion, resulting in a comment body entirely of `<li>` elements instead of `<p>`.

Rust code:

```rust
/*! This is the introduction to a module comment.
 *
 * My editor automatically inserts space-star-space for each line in a block comment.
 * It is visually appealing to some, and is part of a tradition of block comments.
!*/
```

`rustdoc` output (current as of 2018-08-15, has been seen since 2016):

```html
<div class="docblock">
<p>This is the introduction to a module comment.</p>
<ul>
<li></li>
<li>My editor automatically inserts space-star-space
for each line in a block comment. It is visually appealing
to some, and is part of a tradition of block comments.</li>
</ul>
</div>
```

Expected `rustdoc` output:

```html
<div class="docblock">
<p>This is the introduction to a module comment.</p>
<p>My editor automatically inserts space-star-space
for each line in a block comment. It is visually appealing
to some, and is part of a tradition of block comments.</p>
</div>
```

**Comment by jyn514** [comment] 2020-11-04 06:51
Duplicate of https://github.com/rust-lang/rust/issues/32088.

**Closed by jyn514** 2020-11-04 06:51 UTC
Labels: C-bug, T-rustdoc
