### ISSUE TITLE
"Expected operator, found `/`" when passing operator to macro

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#27660] opened 2015-08-11 11:15 UTC
```rust
macro_rules! apply_op {
    ( $op:tt ) => {{ 4 $op 5 }};
}

fn main() {
    let _ = apply_op!(/);
}
```
gives:
```
<anon>:2:24: 2:27 error: expected one of `.`, `;`, `}`, or an operator, found `/`
<anon>:2     ( $op:tt ) => {{ 4 $op 5 }};
                                ^~~
```

The same thing happens for other operators as well as `.` and `;`.

**Comment by Stebalien** [comment] 2015-08-11 15:21
That's because rust currently needs to be told how to interpret the token:
```rust
macro_rules! expr_identity {
    ($e:expr) => { $e }
}
macro_rules! apply_op {
    ( $op:tt ) => { expr_identity!(4 $op 5)};
}

fn main() {
    let _ = apply_op!(/);
}
```
dup of #27231

**Comment by jonas-schievink** [comment] 2015-08-11 15:32
Ah, so these are caused by the same issue. The error message has definitely confused me there.

**Comment by steveklabnik** [comment] 2015-08-13 20:02
tagging as 'diagnostics' since it's not actually incorrect code

**Comment by huonw** [comment] 2015-10-27 06:35
Dupe of #27231 and #5846. Thanks for filing!

**Closed by huonw** 2015-10-27 06:35 UTC
Labels: A-diagnostics
