### ISSUE TITLE
Some macros are not well formatted

### ISSUE THREAD

**Issue by rleungx** [rust-lang/rust#49649] opened 2018-04-04 13:40 UTC
There are some macros which are not well formatted in std, such as [writeln](https://doc.rust-lang.org/std/macro.writeln.html).

```
macro_rules! writeln {
    ( $ dst : expr ) => { ... };
    (
$ dst : expr , $ fmt : expr ) => { ... };
    (
$ dst : expr , $ fmt : expr , $ ( $ arg : tt ) * ) => { ... };
}
```

Another example is [unreachable](https://doc.rust-lang.org/std/macro.unreachable.html).

```
macro_rules! unreachable {
    (  ) => { ... };
    (
$ msg : expr ) => { ... };
    (
$ fmt : expr , $ ( $ arg : tt ) * ) => { ... };
}
```

**Comment by sinkuu** [comment] 2018-04-04 15:04
If they are ones reexported from libcore, this is #26560.

**Comment by pietroalbini** [comment] 2018-04-05 07:16
Duplicate of #26560
Thanks for reporting this!

**Closed by pietroalbini** 2018-04-05 07:16 UTC
