### ISSUE TITLE
Error in stdout, position of error not correctly printed

### ISSUE THREAD

**Issue by fschutt** [rust-lang/rust#62159] opened 2019-06-26 18:51 UTC
## Steps to reproduce

```
git clone https://github.com/fschutt/webrender
cd webrender
git checkout cac72f1 # alternatively "checkout remove-sha2"
cargo check
```

## Output

```
   Compiling webrender v0.60.0
error: invalid format string: expected `'}'`, found `'p'`
  --> webrender/build.rs:83:20
   |
83 | /// If someone is building on a network share, I'm sorry.
   |              -     ^ expected `}` in format string
   |              |
   |              because of this opening brace
   |
   = note: if you intended to print `{`, you can escape it using `{{`

error: aborting due to previous error

error: Could not compile `webrender`.

To learn more, run the command again with --verbose.
```

Source code for that line is [here](https://github.com/fschutt/webrender/blob/cac72f12f3091658ddd22e9c987c3aeb4d114d10/webrender/build.rs#L83). For some reason, the line count is off by a few lines, the actual error happens within the expansion of the `include_str!` macro on line 75:

```rust
write!(shader_file, include_str!("./combined_shaders.rs"), shader_source_code);
```

My goal was to use a "template" file in the "./combined_shaders.rs" file - however, I used `{}` instead of `{{}}` to show where the dynamic content should be inserted [here](https://github.com/fschutt/webrender/blob/cac72f12f3091658ddd22e9c987c3aeb4d114d10/webrender/combined_shaders.rs#L17). Nevermind, this is still a bug (since the line count should at least be on line 75 and underline the `include_str!`).

## Compiler version
```
rustc 1.35.0 (3c235d560 2019-05-20)
binary: rustc
commit-hash: 3c235d5600393dfe6c36eeed34042efad8d4f26e
commit-date: 2019-05-20
host: x86_64-unknown-linux-gnu
release: 1.35.0
LLVM version: 8.0
```

**Comment by Elrendio** [comment] 2020-03-02 16:12
This is actually really hard to debug !

I've created a minimal repro example: https://github.com/Elrendio/invalid_compilation_error

**Comment by Enselic** [comment] 2023-07-24 19:46
The original project is gone.

@Elrendio can you still reproduce? Using your reproducer, I see nothing wrong:

```console
$ cargo check >/dev/null
    Checking invalid_compilation_error v0.1.0 (/home/martin/src/invalid_compilation_error)
error: invalid format string: expected `'}'`, found `'b'`
 --> src/main.rs:2:13
  |
2 |     format!(include_str!("./small"));
  |             ^^^^^^^^^^^^^^^^^^^^^^^ expected `'}'` in format string
  |
  = note: if you intended to print `{`, you can escape it using `{{`
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: invalid format string: expected `'}'`, found `'b'`
 --> src/main.rs:3:13
  |
3 |     format!(include_str!("./medium"));
  |             ^^^^^^^^^^^^^^^^^^^^^^^^ expected `'}'` in format string
  |
  = note: if you intended to print `{`, you can escape it using `{{`
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: invalid format string: expected `'}'`, found `'b'`
 --> src/main.rs:4:13
  |
4 |     format!(include_str!("./large"));
  |             ^^^^^^^^^^^^^^^^^^^^^^^ expected `'}'` in format string
  |
  = note: if you intended to print `{`, you can escape it using `{{`
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `invalid_compilation_error` (bin "invalid_compilation_error") due to 3 previous errors
```

Maybe we can close this issue?

**Comment by Enselic** [comment] 2023-08-17 15:04
Triage: Closing, because it seems prohibitively hard to come up with an MCVE since the original project is gone.

**Closed by Enselic** 2023-08-17 15:04 UTC
Labels: A-diagnostics, T-compiler, C-bug
