### ISSUE TITLE
Macro does not work in impl block

### ISSUE THREAD

**Issue by kunerd** [rust-lang/rust#43496] opened 2017-07-26 20:08 UTC
After a short discussion on IRC #rust it was stated that this could be a compiler bug. I have found some possible related issues, but all are closed, so it may be some kind of regression.

I tried this code:
```
#[macro_use]
extern crate cfg_if;

struct Lcd;

impl Lcd {
    fn new() -> Self {
        Lcd{}
    }
    
    fn write(&self) {
        println!("write");
    }
    
    cfg_if! {
        if #[cfg(read)] {
            fn read(&self) {
                println!("read");
            }
            
            fn read_busy_flag(&self) {
                println!("read busy flag");
            }
        }
    }
}
```
https://play.rust-lang.org/?gist=a1208631aadf943b1bd51714caf3a5da&version=stable

I expected to see this happen: code should compile

Instead, this happened: the following error was thrown by the comiler:
```
error: expected one of `::` or `:`, found `)`
  --> src/main.rs:17:26
   |
17 |             fn read(&self) {
   |                          ^ expected one of `::` or `:` here

error: expected one of `::` or `:`, found `)`
  --> src/main.rs:21:36
   |
21 |             fn read_busy_flag(&self) {
   |                                    ^ expected one of `::` or `:` here

error: expected one of `::` or `:`, found `)`
  --> src/main.rs:17:26
   |
17 |             fn read(&self) {
   |                          ^ expected one of `::` or `:` here

error: expected one of `::` or `:`, found `)`
  --> src/main.rs:21:36
   |
21 |             fn read_busy_flag(&self) {
   |                                    ^ expected one of `::` or `:` here

error: expected one of `const`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `fn read(?) { println!("read"); }`
 --> <__cfg_if_apply macros>:1:57
  |
1 | ( $ m : meta , $ ( $ it : item ) * ) => { $ ( # [ $ m ] $ it ) * }
  |                                                        -^^^^ unexpected token
  |                                                        |
  |                                                        expected one of 7 possible tokens here
```

## Meta

I tested it on playground, stable

**Comment by Mark-Simulacrum** [comment] 2017-07-27 21:27
Macros work fine, it's just that https://github.com/rust-lang/rust/issues/22694 prevents using `:item` generating macros in impls. So this is a duplicate of that bug, closing.

**Closed by Mark-Simulacrum** 2017-07-27 21:27 UTC
Labels: A-macros, C-bug
