### ISSUE TITLE
Regression in asynchronous-0.4.5, Rust 1.17

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40953] opened 2017-03-31 16:52 UTC
https://github.com/bcndanos/asynchronous

```
101 ec2-user@ip-10-145-56-122:~/triage/asynchronous$ git log -1
commit 5423c7e714e46117a75f8b89086b12f8e31da170
Author: bcndanos <rinnegatobcn@gmail.com>
Date:   Fri May 22 19:38:07 2015 +0200

    Update Readme

```

```
ec2-user@ip-10-145-56-122:~/triage/aligner$ rustc +beta -Vv
rustc 1.17.0-beta.2 (b7c276653 2017-03-20)
binary: rustc
commit-hash: b7c27665307704a9b158fe242e88e83914029415
commit-date: 2017-03-20
host: x86_64-unknown-linux-gnu
release: 1.17.0-beta.2
LLVM version: 3.9
```

```
        error[E0282]: type annotations needed
 --> <anon>:3:1
  |
3 | asynchronous::Deferred::new(|| {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `T`

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

---- src/lib.rs - Deferred<T, E>::then (line 175) stdout ----
        error[E0282]: type annotations needed
 --> <anon>:8:4
  |
8 |    Ok(34)
  |    ^^ cannot infer type for `E`

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

---- src/lib.rs - Promise<T, E>::chain (line 628) stdout ----
        error[E0282]: type annotations needed
  --> <anon>:12:4
   |
12 |    Ok(34)
   |    ^^ cannot infer type for `E`

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

---- src/lib.rs - Promise<T, E>::fail (line 685) stdout ----
        error[E0282]: type annotations needed
 --> <anon>:3:1
  |
3 | asynchronous::Promise::new(|| {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `T`

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

---- src/lib.rs - Promise<T, E>::then (line 598) stdout ----
        error[E0282]: type annotations needed
 --> <anon>:8:4
  |
8 |    Ok(34)
  |    ^^ cannot infer type for `E`

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203


failures:
    src/lib.rs - Deferred<T, E>::chain (line 214)
    src/lib.rs - Deferred<T, E>::fail (line 289)
    src/lib.rs - Deferred<T, E>::then (line 175)
    src/lib.rs - Promise<T, E>::chain (line 628)
    src/lib.rs - Promise<T, E>::fail (line 685)
    src/lib.rs - Promise<T, E>::then (line 598)

test result: FAILED. 22 passed; 6 failed; 0 ignored; 0 measured

error: test failed
```

Not on nightly.

cc @bcndanos

**Comment by alexcrichton** [comment] 2017-03-31 17:03
Looks like it also [affects](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/dotfiler-0.1.0/log.txt) [dotfiler](https://github.com/matthunz/dotfiler)

cc @matthunz

**Comment by alexcrichton** [comment] 2017-03-31 17:04
Like also [affects](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/error_defs-0.1.0/log.txt) [error_defs](https://crates.io/crates/error_defs)

cc @canndrew

**Comment by brson** [comment] 2017-03-31 17:04
Also fiber cc @TileHalo

**Comment by brson** [comment] 2017-03-31 17:05
Also gimli cc @fitzgen

**Comment by alexcrichton** [comment] 2017-03-31 17:07
Also futures 0.1.0

**Comment by alexcrichton** [comment] 2017-03-31 17:11
[Also](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/hematite_server-0.0.3/log.txt) hematite_server 

cc @bvssvni

**Comment by alexcrichton** [comment] 2017-03-31 17:12
Also [imag](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/imag-0.2.0/log.txt)

cc @matthiasbeyer

**Comment by fitzgen** [comment] 2017-03-31 17:13
@brson:
> Also gimli cc @fitzgen

I pinged @aturon about this a few weeks ago. Then I landed a commit to work around the regression within gimli and a new version published to crates.io. Are you saying that the most recent version on crates.io is still affected (or that perhaps this is a different-but-similar regression)? Are the crates listed here the results of a crater (or its new replacement whose name I forgot)?

**Comment by alexcrichton** [comment] 2017-03-31 18:24
@fitzgen these results are from cargobomb (a crater equivalent-ish) and the [full results](https://internals.rust-lang.org/t/cargobomb-report-stable-v-nightly-2017-03-29/5020/2) are [posted online](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/index.html) with the two [regression](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/gimli-0.11.0/log.txt) [logs](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-03-29/res/nightly/reg/gimli-0.12.0/log.txt) for gimli, downloaded from crates.io.

Do you remember why this fix was needed? It'd be good to track down why inference started failing to see if we want to revert that change.

**Comment by Yamakaky** [comment] 2017-03-31 18:33
I modified the broken test from error-chain so that it doesn't fail anymore, btw.

**Comment by alexcrichton** [comment] 2017-03-31 18:36
@Yamakaky can you point to the fix? It's not clear to me at least currently why this regression happened and affected so many crates.

**Comment by nikomatsakis** [comment] 2017-03-31 19:41
This **may** be fixed by https://github.com/rust-lang/rust/pull/40636 -- which has yet to be backported to beta.

**Comment by fitzgen** [comment] 2017-03-31 19:44
Here is the gimli fix I had made: https://github.com/gimli-rs/gimli/commit/dbec0320b5fc975973e6456fc8b9a0e7d65cf682

**Comment by Yamakaky** [comment] 2017-03-31 20:49
@alexcrichton https://github.com/brson/error-chain/commit/3fab94a57899f875a8d201454c7050bad90671be

**Comment by alexcrichton** [comment] 2017-04-01 00:15
Thanks for looking into this Niko! Thanks also for the links to fixes, let's land the backport and go from there

**Comment by nikomatsakis** [comment] 2017-04-04 10:59
OK, so, the backport landed. @alexcrichton, when do you think we'll spin off a new beta so we can most easily test if this is fixed? (That is still a manual process, right?)

**Comment by alexcrichton** [comment] 2017-04-04 17:49
@nikomatsakis we'll try to get a new beta scheduled today

**Comment by alexcrichton** [comment] 2017-04-06 04:51
New beta is here and bug appears fixed! Closing.

**Closed by alexcrichton** 2017-04-06 04:51 UTC
Labels: regression-from-stable-to-beta
