### ISSUE TITLE
no way to not ship panic strings inside the compiled binary 

### ISSUE THREAD

**Issue by pocesar** [rust-lang/rust#60105] opened 2019-04-19 06:02 UTC
Already have `panic = "abort"` in cargo, and it doesn't seem to leave the panic!() strings out of the compiled binary, even on `--release` build. I don't care about panic strings, I just want a slim generated exe that fails if something goes wrong. 
`tokio`, `crossbeam` and `chrono` are adding a lot of useless strings in the `.rdata` on Windows, for example. also `opt-level = "s"` (and `"z"`)
tried to use `panic::set_hook` as well, it didn't do anything. tried to make the long path names using `remap-path-prefix` but it seemed to have no effect (the paths are still full absolute paths to current user folder/.cargo/registry). doesn't matter if I use windows paths (eg: C:\\Users or Unix C:/Users) and besides the #40552 that's two years old, but a minor issue when you need to rely on std and size optimizations.

also tried a lot of other stuff (like `link-arg=-s`, `debuginfo=0`, `no-landing-pads`, etc), while the generated exe is smaller than a full blown `cargo build --release`, so it's really an unexpected output from the compiler

**Comment by jonas-schievink** [comment] 2019-04-19 12:33
You can do this by using a custom panic implementation like [panic-abort](https://github.com/japaric/panic-abort) which doesn't use the strings. Also see [RFC 2070](https://github.com/rust-lang/rfcs/blob/master/text/2070-panic-implementation.md) which introduced this feature and is currently the best source of information on how to use it.

**Comment by pocesar** [comment] 2019-04-19 23:29
I've already tried that and doesn't work on the program that is using std... unless I'm missing something obvious

**Comment by jonas-schievink** [comment] 2019-04-19 23:41
Can you provide a reproduction for that? It definitely works on embedded `no_std` code, but it should also work with libstd-using code.

**Comment by pocesar** [comment] 2019-04-19 23:44
```
error: duplicate lang item in crate `panic_abort`: `panic_impl`.
  |
  = note: first defined in crate `std`.

error: aborting due to previous error

error: Could not compile `bin`.

To learn more, run the command again with --verbose.
```

**Comment by jonas-schievink** [comment] 2019-04-19 23:47
Ah, I misunderstood what you meant. Looks like that RFC indeed only targets `#![no_std]`.

**Comment by Julius-Beides** [comment] 2019-04-20 08:05
Linux has a `strip` command that discards symbols from object files. Maybe there is an equivalent under Winows.

**Comment by pocesar** [comment] 2019-04-21 05:00
maybe the default panic implementation should use `#[cfg(...)]` to literally omit the strings on https://github.com/rust-lang/rust/blob/9ebf47851a357faa4cd97f4b1dc7835f6376e639/src/libcore/macros.rs#L12 like `#[cfg(not(panic="abort"))]` (but this doesn't work, of course) before the call to panic fn, since even assert_* macros panic with strings. I usually do that for debug strings, with a `#[cfg(debug_assertions)]] println!()` (when I actually *do* care about the information, during profile.dev / test)

**Comment by sfackler** [comment] 2019-04-21 14:29
You can do this by building your own std (xargo can help with this) with this Cargo feature enabled: https://github.com/rust-lang/rust/blob/master/src/libstd/Cargo.toml#L60

**Comment by NickeZ** [comment] 2019-11-28 10:52
Did you ever solve this issue? It is easy to make the strings deterministic that are from the crate you are actually compiling. But there are strings that point to dependencies in `/home/<user>/.cargo` which I need to get rid of.

I compile with `opt-level=z` and my panic implementation does not reference the strings:

```
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    #[cfg(debug_assertions)]
    print_debug!(0, "Error: {}", info);
    #[cfg(not(debug_assertions))]
    print_debug!(0, "Error");
    loop {}
}
```

**Comment by jyn514** [comment] 2021-05-19 10:45
Duplicate of https://github.com/rust-lang/rust/issues/54981.

**Closed by jyn514** 2021-05-19 10:45 UTC
Labels: C-enhancement, I-heavy
