### ISSUE TITLE
Hygiene for function-like procedural macros

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#40356] opened 2017-03-08 13:01 UTC
Hello.
I wonder how the hygiene works for function-like procedural macros.
I made a test with these macros that you can find [here](https://github.com/antoyo/function-proc-macro).

However, it does not compile.
I get the following error:
```rust
error[E0425]: cannot find value `vector` in this scope
 --> src/main.rs:9:5
  |
9 |     pp!(vector);
  |     ^^^^^^^^^^^^ not found in this scope
```
while if the call is:
```rust
pp!(vec![1, 2, 3]);
```
it will compile and works.

Is this an issue with hygiene?

Thanks.

**Comment by abonander** [comment] 2017-03-09 03:46
There is no hygiene support for procedural macros yet. @jseyfried is working on this, though.

**Comment by petrochenkov** [comment] 2021-07-14 14:21
Closing as a duplicate of https://github.com/rust-lang/rust/issues/54724.

**Closed by petrochenkov** 2021-07-14 14:21 UTC
Labels: A-macros, A-proc-macros, C-enhancement
