### ISSUE TITLE
rustc forever stuck compiling.

### ISSUE THREAD

**Issue by Aaronepower** [rust-lang/rust#38030] opened 2016-11-27 16:39 UTC
Rust will essentially hang until the system kills it. Easiest way to reproduce is to build [tokei](https://github.com/Aaronepower/tokei/tree/a0b12fc4a2cbdbf1d6aadfa87d1a5c760beb974b) with `--features all`. I'm on macOS, but according to both travis and appveyor it fails on Linux, and Windows.

[Travis log](https://travis-ci.org/Aaronepower/tokei/jobs/179224475#L472)

```
rustc 1.13.0 (2c6933acc 2016-11-07)
binary: rustc
commit-hash: 2c6933acc05c61e041be764cb1331f6281993f3f
commit-date: 2016-11-07
host: x86_64-apple-darwin
release: 1.13.0
```

**Comment by the-kenny** [comment] 2016-11-27 19:05
I've seen this in the `rustc` build in [nixos/nixpkgs](https://github.com/NixOS/nixpkgs). For us, it was `src/test/run-pass/issue-36474.rs` that was causing an infinite loop. Disabling the test fixed it.

**Comment by steveklabnik** [comment] 2016-11-29 18:42
Nominating, as this seems like a regression of some kind?

**Comment by nikomatsakis** [comment] 2016-12-01 21:34
Marking as stable-to-nightly regression, presumably...unclear if this ever worked?

**Comment by nikomatsakis** [comment] 2016-12-01 21:36
cc @rust-lang/compiler -- anybody care to investigate? 

@the-kenny @Aaronepower can either of you confirm if this is in fact a regression (i.e., did these tests ever work)?

**Comment by the-kenny** [comment] 2016-12-01 22:42
@nikomatsakis Definitely. All our `rustc-1.12.1` builds worked fine. [One sample's build log](http://hydra.nixos.org/build/43625259/log/raw). Right now we're simply deleting the file as a workaround. 

If it helps I can try to reproduce the issue again.

**Comment by Aaronepower** [comment] 2016-12-01 22:45
@nikomatsakis Sorry for being unclear. tokei does run tests which pass without the features. However it gets stuck on *build* not on test. For tokei it's probably due to codegen from generating `Serialize, Deserialize` for JSON, CBOR, YAML, TOML. As that is the key difference from compiling without `features = all`. And if I do put in a syntax error, rustc will catch that and exit out as usual. It's only when the code contains no errors does this happen. The speed of the compile is probably the fault of `serde-codegen`, but rustc shouldn't get killed for long compile times.

**Comment by jseyfried** [comment] 2016-12-02 00:27
@Aaronepower 
The hang when building `tokei` with `--features all` appears to be #36881, triggered by [this erroneous `use`](https://github.com/Aaronepower/tokei/blob/a0b12fc4a2cbdbf1d6aadfa87d1a5c760beb974b/src/input.rs#L66`). This issue was caused by #36573 (currently in stable) and fixed by #36882 (currently in beta). Thus,  #36881 is a regression from `1.12` to `1.13`, but only for code that wouldn't have compiled anyway.

@the-kenny's [issue](https://github.com/rust-lang/rust/issues/38030#issuecomment-263140239) appears to be unrelated.

**Comment by nikomatsakis** [comment] 2016-12-08 21:09
@the-kenny since the original issue appears to have been solved, I'm going to close this ticket. Can you open a new one with a bit more information to help us reproduce the problem?

**Closed by nikomatsakis** 2016-12-08 21:09 UTC
Labels: A-compiler, I-nominated, regression-from-stable-to-nightly, T-compiler

**Comment by the-kenny** [comment] 2016-12-09 09:58
Niko Matsakis <notifications@github.com> writes:

> @the-kenny since the original issue appears to have been solved, I'm going to close this ticket. Can you open a new one with a bit more information to help us reproduce the problem?

Yup, no problem! I hope I'll be able to allocate some time for research
into this issue today.
