### ISSUE TITLE
missing_fragment_specifier hard error

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#76605] opened 2020-09-11 16:01 UTC
In [the beta run for Rust 1.47](https://crater-reports.s3.amazonaws.com/beta-1.47-rustdoc-1/index.html) the release team discovered that https://github.com/rust-lang/rust/pull/75516 is breaking more than 475 crates or git repositories currently compiling, across *at least* the following crates:

* `js-sys`
* `clap`
* `time-macros-impl`

cc @petrochenkov @matklad @rust-lang/release

**Comment by pietroalbini** [comment] 2020-09-11 16:02
Personally I think that's too much breakage to land, even though it was a deprecation warning since 2017.

**Comment by petrochenkov** [comment] 2020-09-11 17:52
I agree that it's not an acceptable breakage, although I suspect that most of it happens due to committed `Cargo.lock`s.
I think we can add a hack accepting a missing fragment specifier for the 2-3 specific crates responsible for majority of the breakage, like it was done in https://github.com/rust-lang/rust/pull/73345.
(In a more local way than before https://github.com/rust-lang/rust/pull/75516, without `Option<NonterminalKind>` in `MetaVarDecl`, and without `missing_fragment_specifiers` in session.)

**Comment by Mark-Simulacrum** [comment] 2020-09-11 18:08
We could also make it a hard warning rather than error for all crates, but I'm not sure if that's better. It also doesn't need session state.

**Comment by tmandry** [comment] 2020-09-12 01:56
To expand a bit: cargo hides warnings generated by your dependencies, so crate owners don't feel the pain of depending on these old versions. I believe it passes `-Awarnings` to rustc, but otherwise passes through the output unchanged. If we had a warning that printed in spite of `-Awarnings` it would encourage people to update their deps.

I assume that is what is meant by "hard warning"?

**Comment by Mark-Simulacrum** [comment] 2020-10-02 15:49
I've posted a revert to current beta (https://github.com/rust-lang/rust/pull/77456) but we still need to fix this on master. Moving milestone to 1.48, though.

**Comment by Aaron1011** [comment] 2020-10-02 15:59
I think this is another case where https://github.com/rust-lang/rust/issues/71249 would help (see https://github.com/rust-lang/rust/pull/75534)

**Comment by petrochenkov** [comment] 2020-10-03 07:38
I'll try to address this on nightly until the next release (the revert has landed on beta only https://github.com/rust-lang/rust/pull/77456).

**Comment by pietroalbini** [comment] 2020-10-04 19:27
Changed this to a nightly regression (so 1.48 regression) since we reverted the change on beta.

**Comment by jhpratt** [comment] 2020-10-20 08:13
What needs to change in time-macros-impl? There's no warnings currently emitted by any of my code, as verified in CI. I certainly would have run across it at some point while developing otherwise.

In the future though, a friendly ping would be appreciated 🙂

**Comment by Mark-Simulacrum** [comment] 2020-11-06 15:52
Assigning to @estebank to change the lint on nightly to a hard warning, which should both prevent hard errors (and as such regressions).

**Comment by petrochenkov** [comment] 2020-11-10 20:26
So, I assumed that `$i` without a "fragment specifier" would behave like some actual fragment specifier, e.g. `tt`, but apparently it doesn't and it always produces an error on attempt to match, so the `Option` in `MetaVarDecl` is necessary.

**Comment by estebank** [comment] 2020-11-13 01:20
@petrochenkov does that mean we need to revert #75516 in master too (and potentially on the upcoming beta)?

**Comment by petrochenkov** [comment] 2020-11-13 07:20
I think we need to revert on master and then do any other work starting from that state.

**Comment by Mark-Simulacrum** [comment] 2020-12-10 18:33
#75516 does not seem to revert cleanly on current beta (1.49). @estebank @petrochenkov could one of you prepare a revert PR targeting beta? (I agree we should also revert on master)

**Closed** 2020-12-25 17:04 UTC
Labels: A-parser, C-bug, P-critical, T-compiler, T-release, regression-from-stable-to-beta
