### ISSUE TITLE
Regression: Inlined loops not fully evaluating with `const`-eable dependencies

### ISSUE THREAD

**Issue by sno2** [rust-lang/rust#101082] opened 2022-08-27 12:13 UTC
I tried this code:

```rust
pub fn arr() -> usize {
  let values = [23, 16, 54, 3, 60, 9];
  let mut acc = 0;
  for item in values { 
    acc += item;
  }
  acc
}
```

I expected to see this happen: The loop should be inlined because `values` is const-known. For example, here is the generated assembly on Rust 1.63.0 ([Godbolt](https://godbolt.org/z/75Y1c63cE)) and Rust Beta ([Godbolt](https://godbolt.org/z/KhcozT55j)):

```asm
example::arr:
        mov     eax, 165
        ret
```

Instead, this happened: On nightly, the loop is inlined. However, the entire function is not computed despite the stable and beta Rust inlining it.  Here is the generated assembly on Nightly ([Godbolt](https://godbolt.org/z/7bTWPh15s)):

```asm
.LCPI0_0:
        .quad   23
        .quad   16
.LCPI0_1:
        .quad   54
        .quad   3
.LCPI0_2:
        .quad   60
        .quad   9
example::arr:
        sub     rsp, 72
        movaps  xmm0, xmmword ptr [rip + .LCPI0_0]
        movaps  xmmword ptr [rsp], xmm0
        movaps  xmm0, xmmword ptr [rip + .LCPI0_1]
        movaps  xmmword ptr [rsp + 16], xmm0
        movaps  xmm0, xmmword ptr [rip + .LCPI0_2]
        movaps  xmmword ptr [rsp + 32], xmm0
        mov     qword ptr [rsp + 56], 6
        xor     ecx, ecx
        xor     edx, edx
        jmp     .LBB0_1
.LBB0_3:
        lea     rdi, [rcx + 1]
        mov     qword ptr [rsp + 48], rdi
        mov     rdx, qword ptr [rsp + 8*rcx]
        mov     esi, 1
        mov     rcx, rdi
        add     rdx, rax
        test    rsi, rsi
        je      .LBB0_5
.LBB0_1:
        mov     rax, rdx
        cmp     rcx, 5
        jbe     .LBB0_3
        xor     esi, esi
        add     rdx, rax
        test    rsi, rsi
        jne     .LBB0_1
.LBB0_5:
        add     rsp, 72
        ret
```

### Meta

n/a - disclosed at usages

Keywords: const inline loop, const loop, const loop not evaluated

Relevant discord thread: https://discord.com/channels/273534239310479360/592856094527848449/1013050670942793808

**Comment by apiraino** [comment] 2022-08-31 11:04
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23101082.20Regression.3A.20Inlined.20loops.20not.20fully.20evaluating.20with.E2.80.A6)).

@rustbot label -I-prioritize +P-high t-compiler

**Comment by nikic** [comment] 2022-09-01 08:53
Partial fix: https://github.com/llvm/llvm-project/commit/5b219dd9e906c94a97c92e6bf9b2360f6f279f96 This at least allows the loop to be unrolled, though it only gets fully constant folded in the backend.

**Comment by nikic** [comment] 2022-09-01 09:09
```
  %_2.sroa.4.0.iter.sroa_idx = getelementptr inbounds i8, ptr %iter, i64 48
  store i64 0, ptr %_2.sroa.4.0.iter.sroa_idx, align 8
  %_2.sroa.5.0.iter.sroa_idx = getelementptr inbounds i8, ptr %iter, i64 56
  store i64 6, ptr %_2.sroa.5.0.iter.sroa_idx, align 8
  %self1.i = getelementptr inbounds %"core::array::iter::IntoIter<usize, 6>", ptr %iter, i64 0, i32 1
  %_4.i.i = getelementptr inbounds %"core::array::iter::IntoIter<usize, 6>", ptr %iter, i64 0, i32 1, i32 1
  %_4.val.i.i = load i64, ptr %_4.i.i, align 8, !alias.scope !2
  %0 = load i64, ptr %self1.i, align 8, !alias.scope !2
```

Oh my, if it isn't yet another casualty of LLVM's dumb typed GEP representation. This might get fixed by https://github.com/rust-lang/rust/pull/98615 as well.

**Comment by nikic** [comment] 2022-09-01 14:41
This turns out to be surprisingly tricky due to phase ordering issues. Even with canonical GEPs, the loop bounds only become known after full unrolling, by which point it is too late. I think the best shot at this would be to generalize LICM scalar promotion to perform load promotion in the presence of potentially aliasing loads. https://reviews.llvm.org/D133111 is preparation to move in that direction.

**Comment by nikic** [comment] 2022-09-02 09:46
https://reviews.llvm.org/D133192 for improved LICM promotion. Still needs to be combined with canonical GEPs to work.

**Comment by nikic** [comment] 2022-12-16 15:33
@pnkfelix We need both #98615 and https://reviews.llvm.org/D133192 to fully resolve this, as far as I remember. We should probably land #98615 ASAP to give us a chance to address regressions from it in LLVM 16.

**Comment by nikic** [comment] 2023-04-03 12:26
Fixed by the LLVM 16 upgrade.

**Closed** 2023-04-03 15:02 UTC
Labels: A-LLVM, I-slow, E-needs-test, regression-from-stable-to-nightly, P-high, T-compiler, C-bug
