### ISSUE TITLE
rustup.sh installs nighty cargo on the stable channel

### ISSUE THREAD

**Issue by wigy-opensource-developer** [rust-lang/rust#36494] opened 2016-09-15 14:46 UTC
After running into an issue with the `clippy_lints` compilation, I found out I had a stable `rustc` with a nightly `cargo`. Since I had no idea how I got into that situation, I have uninstalled everything and made sure I have no `cargo` nor `rustc` lying around, then I started reinstalling the stable channel:

I have just run `curl -sf https://static.rust-lang.org/rustup.sh >rustup.sh` and made it executable.

```
$ ./rustup.sh --channel=stable
rustup: gpg available. signatures will be verified
rustup: downloading manifest for 'stable'
rustup: downloading toolchain for 'stable'
######################################################################## 100,0%
gpg: assuming signed data in `/home/.../.rustup/dl/be644b01552c9dba7a05/rust-1.11.0-x86_64-unknown-linux-gnu.tar.gz'
gpg: Signature made 2016. aug. 16., kedd, 13.35.16 CEST using RSA key ID 7B3B09DC
gpg: Good signature from "Rust Language (Tag and Release Signing Key) <rust-key@rust-lang.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 108F 6620 5EAE B0AA A8DD  5E1C 85AB 96E6 FA1B E5FE
     Subkey fingerprint: C134 66B7 E169 A085 1886  3216 5CB4 A934 7B3B 09DC
rustup: installing toolchain for 'stable'
rustup: extracting installer
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-x86_64-unknown-linux-gnu'
install: installing component 'rust-docs'
install: installing component 'cargo'

    Rust is ready to roll.

$ cargo --version
cargo 0.12.0-nightly (6b98d1f 2016-07-04)
$ rustc --version
rustc 1.11.0 (9b21dcd6a 2016-08-15)
```

I see that the world is moving towards `curl https://sh.rustup.rs -sSf`, but that does not seem to check signatures. Is there a workaround to get the stable cargo with the old rustup.sh? Are you planning to release fixes to the old rustup.sh?

**Comment by durka** [comment] 2016-09-15 14:52
Cargo is always nightly, but the version distributed with stable and beta is frozen.

**Comment by wigy-opensource-developer** [comment] 2016-09-15 15:10
Oh, that is confusing. So basically the branching strategy is different on the 2 repositories and there are no hotfixes coming out for older releases of cargo?

**Comment by durka** [comment] 2016-09-15 15:19
There have never been hotfixes for either rustc or cargo as far as I know.

**Comment by steveklabnik** [comment] 2016-11-22 18:27
Closing this as "not a bug", thanks @wigy-opensource-developer !

**Closed by steveklabnik** 2016-11-22 18:27 UTC
