### ISSUE TITLE
Up to 8% RSS regression because of #44142

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#44576] opened 2017-09-14 20:55 UTC
http://perf.rust-lang.org/?start=2017-08-15T00%3A00%3A00%2B00%3A00&end=2017-09-14T00%3A00%3A00%2B00%3A00&crates=%5B%22futures-rs-test-all%22%2C%22helloworld%22%2C%22html5ever-2016-08-25%22%2C%22hyper.0.5.0%22%2C%22inflate-0.1.0%22%2C%22issue-20936-deep-vector%22%2C%22issue-32062-equality-relations-complexity%22%2C%22issue-32278-big-array-of-strings%22%2C%22issue-43572-unused-uses%22%2C%22jld-day15-parser%22%2C%22piston-image-0.10.3%22%2C%22regex-0.1.80%40010-baseline%22%2C%22regex-0.1.80%40020-incr-from-scratch%22%2C%22regex-0.1.80%40030-compile_one%22%2C%22regex-0.1.80%40040-is_valid_cap_letter%22%2C%22regex-0.1.80%40050-expand%22%2C%22regex-0.1.80%40060-Compiler-new%22%2C%22regex-0.1.80%40070-BYTE_FREQUENCIES%22%2C%22regex-0.1.80%40080-SparseSet%22%2C%22regex-0.1.80%40090-Job%22%2C%22regex-0.1.80%40100-incr-no-change%22%2C%22regex.0.1.30%22%2C%22rust-encoding-0.3.0%22%2C%22syntex-0.42.2%40000-base%22%2C%22syntex-0.42.2%40010-incr%22%2C%22syntex-0.42.2%40020-clean%22%2C%22tokio-webpush-simple%40000-base%22%2C%22tokio-webpush-simple%40010-incr%22%2C%22tokio-webpush-simple%40020-clean%22%2C%22tokio-webpush-simple%40030-minor-change%22%2C%22tuple-stress%22%5D&stat=max-rss

This is an 8% regression with incremental enabled, 1% without it. #44142

**Comment by alexcrichton** [comment] 2017-09-15 01:02
[A more focused graph](http://perf.rust-lang.org/?start=2017-09-06T00%3A00%3A00%2B00%3A00&end=2017-09-10T00%3A00%3A00%2B00%3A00&crates=%5B%22futures-rs-test-all%22%2C%22helloworld%22%2C%22html5ever-2016-08-25%22%2C%22hyper.0.5.0%22%2C%22inflate-0.1.0%22%2C%22issue-20936-deep-vector%22%2C%22issue-32062-equality-relations-complexity%22%2C%22issue-32278-big-array-of-strings%22%2C%22issue-43572-unused-uses%22%2C%22jld-day15-parser%22%2C%22piston-image-0.10.3%22%2C%22regex-0.1.80%40010-baseline%22%2C%22regex-0.1.80%40020-incr-from-scratch%22%2C%22regex-0.1.80%40030-compile_one%22%2C%22regex-0.1.80%40040-is_valid_cap_letter%22%2C%22regex-0.1.80%40050-expand%22%2C%22regex-0.1.80%40060-Compiler-new%22%2C%22regex-0.1.80%40070-BYTE_FREQUENCIES%22%2C%22regex-0.1.80%40080-SparseSet%22%2C%22regex-0.1.80%40090-Job%22%2C%22regex-0.1.80%40100-incr-no-change%22%2C%22regex.0.1.30%22%2C%22rust-encoding-0.3.0%22%2C%22syntex-0.42.2%40000-base%22%2C%22syntex-0.42.2%40010-incr%22%2C%22syntex-0.42.2%40020-clean%22%2C%22tokio-webpush-simple%40000-base%22%2C%22tokio-webpush-simple%40010-incr%22%2C%22tokio-webpush-simple%40020-clean%22%2C%22tokio-webpush-simple%40030-minor-change%22%2C%22tuple-stress%22%5D&stat=max-rss)

**Comment by alexcrichton** [comment] 2017-09-15 02:19
Interestingly if you [widen the view a bit](http://perf.rust-lang.org/?start=2017-09-06T00%3A00%3A00%2B00%3A00&end=2017-09-14T00%3A00%3A00%2B00%3A00&crates=%5B%22syntex-0.42.2%40020-clean%22%5D&stat=max-rss) you'll see:

* An 8% regression due to https://github.com/rust-lang/rust/pull/44142
* A 4% improvement due to https://github.com/rust-lang/rust/pull/44316
* A 7% improvement due to https://github.com/rust-lang/rust/pull/44435
* A 7% regression due to https://github.com/rust-lang/rust/pull/44275

May be worth looking into #44275 as well?

**Comment by alexcrichton** [comment] 2017-09-15 03:19
Specifically before/after #44142, [massif snapshots](https://gist.github.com/alexcrichton/3330184972bde9ac52b22ee7e1da9aaa) -- I've only included the peak snapshot in the output there.

**Comment by alexcrichton** [comment] 2017-09-15 03:26
Looks like basically all of the memory [is here](https://github.com/rust-lang/rust/blob/master/src/librustc/dep_graph/edges.rs#L233-L238), aka we have a bigger dep graph. Turns out adding more queries makes a bigger dep graph :)

**Comment by alexcrichton** [comment] 2017-09-15 04:33
I cashed in some easy savings in https://github.com/rust-lang/rust/pull/44586, but it doesn't actually fix the "regression", but we likely shouldn't call it a regression as it also fixed a number of would-be bugs!

**Comment by alexcrichton** [comment] 2017-09-18 14:53
Looks like we've [recovered the losses](http://perf.rust-lang.org/?start=2017-09-06T00%3A00%3A00%2B00%3A00&end=2017-09-18T00%3A00%3A00%2B00%3A00&crates=%5B%22syntex-0.42.2%40020-clean%22%5D&stat=max-rss) and this particular peak may also [go away soon](https://github.com/rust-lang/rust/pull/44586#issuecomment-329744597), so closing.

**Closed by alexcrichton** 2017-09-18 14:53 UTC
Labels: I-nominated, regression-from-stable-to-nightly, T-compiler
