### ISSUE TITLE
Compiler suggestion for attempt to move out of indexed content

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#38887] opened 2017-01-06 20:03 UTC
This code:

    use std::collections::HashMap;
    fn encode2(vals: &[u32], encoding: &HashMap<u32, String>) -> String {
        vals.iter().map(|k| encoding[k]).collect()
    }
    fn main() {}

It doesn't compile:

    error[E0507]: cannot move out of indexed content
     --> ...\test.rs:3:25
      |
    3 |     vals.iter().map(|k| encoding[k]).collect()
      |                         ^^^^^^^^^^^ cannot move out of indexed content
    
        error: aborting due to previous error

Perhaps the compiler could suggest the programmer to add a &* :

    vals.iter().map(|k| &*encoding[k]).collect()

**Comment by Phlosioneer** [comment] 2017-05-01 22:49
Duplicate of #25507?

**Comment by Mark-Simulacrum** [comment] 2017-06-22 12:43
Yes, I'm going to close in favor of https://github.com/rust-lang/rust/issues/25507. Thanks!

**Closed by Mark-Simulacrum** 2017-06-22 12:43 UTC
