### ISSUE TITLE
"lifetime may not live long enough" error wrong way round with contravariant type.

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#119419] opened 2023-12-29 20:15 UTC
### Code

```Rust
pub fn assert_cov<'short, 'long: 'short>(id: fn(&'long ())) -> fn(&'short ()) {
    id
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d99e4d4de72f9813406e865f876d6534)

(thanks to @compiler-errors for the minimization)

### Current output

```Shell
error: lifetime may not live long enough
 --> src/lib.rs:2:5
  |
1 | pub fn assert_cov<'short, 'long: 'short>(id: fn(&'long ())) -> fn(&'short ()) {
  |                   ------  ----- lifetime `'long` defined here
  |                   |
  |                   lifetime `'short` defined here
2 |     id
  |     ^^ function was supposed to return data with lifetime `'long` but it is returning data with lifetime `'short`
  |
  = help: consider adding the following bound: `'short: 'long`
```

### Desired output

```Shell
^^ function was supposed to return data with lifetime `'short` but it is returning data with lifetime `'long`
```

version: 1.77.0-nightly (2023-12-28 fb5ed726f72c6d16c788)

**Comment by compiler-errors** [comment] 2023-12-29 20:23
The error reporting for `ConstraintCategory::Return` doesn't take into account the (contra)variance of relations. All it sees is a failed outlives relation, and presumes (covariantly) that the shorter region must've come from the return type.

**Comment by QuineDot** [comment] 2024-01-21 05:32
Dupe of #108636

**Comment by fmease** [comment] 2024-01-21 16:03
Closing as duplicate.

**Closed by fmease** 2024-01-21 16:03 UTC
Labels: A-diagnostics, A-borrow-checker, T-compiler, A-NLL, D-incorrect, A-variance
