### ISSUE TITLE
doc: provide epub download of The Book

### ISSUE THREAD

**Issue by akavel** [rust-lang/rust#20866] opened 2015-01-10 11:18 UTC
Could you possibly add an .epub version of The Book for download on the website?

The epub format seems at least mentioned in some Makefiles, so I hope this should be not very hard  -- unless it's defunct and unsupported, and would have to be done from scratch? If not, then still there are some tools like pandoc, that I think support making epubs from Markdown already, so at least should be doable without reinventing the tools...

I'd be very grateful, thanks.

**Comment by killercup** [comment] 2015-01-10 12:23
I've thought about this, as well. @steveklabnik, [too](http://www.reddit.com/r/rust/comments/2ru6re/the_rust_programming_language_book_all_the_guides/cnjjnj5).

Technically, this might a bit tricky, partially because of #20826.

What you need to do is create one markdown document with a correct outline (i.e. cleverly interpreting and changing headline levels) and in order of the table of contents (i.e. parsing the TOC file which is a markdown list containing links). But then it would be trivial to feed that to pandoc and generate all sorts of formats!

**Comment by akavel** [comment] 2015-01-10 15:43
As to #20826, I've just sent a pull request that might (or might not) close the issue.

**Comment by killercup** [comment] 2015-01-10 15:49
@akavel I don't think that'll solve this problem by itself, since all the chapter headings are actually _level two_ in the global table of contents.

E.g., "2.8. Compound Data Types" should be a level 2 heading in an ebook, therefore the content of that chapter should start headings at level 3. (In an epub/book, heading level 1 might be a "part", level 2 might be a "chapter" and level 3+ might be subsections.)

Your changes might simplify the script needed to compile the book contents though.

**Comment by killercup** [comment] 2015-01-11 12:16
@akavel I created an epub version of the book!

- [Explanation on reddit with download link](http://www.reddit.com/r/rust/comments/2s1zj2/the_rust_programming_language_book_as_epub/)
- [Gist with the script to generate the file](https://gist.github.com/killercup/a793e09638379dbc74e4)

**Comment by akavel** [comment] 2015-01-11 19:39
Woohoo, awesome, thanks a lot! And the code samples seem to wordwrap quite nicely on my nook too, big thanks! :)

**Comment by Gankro** [comment] 2015-01-21 22:31
@killercup would it be possible to integrate this back into our toolchain for us to officially provide it?

**Comment by killercup** [comment] 2015-01-21 22:47
@Gankro please do! Consider the code to be in the public domain; just take it, it's yours.

I don't think it'd take much time to rewrite this in Rust, it's just a bunch of calls to pandoc. It would be a nice feature for rustbook.

**Comment by killercup** [comment] 2015-05-17 08:13
Just an update: Last week I redid most of that script I posted above. This now also deals with normalizing code blocks and fixing links. You can find it [here](https://github.com/killercup/trpl-ebook) and the results (html, epub, pdf) [here](http://killercup.github.io/trpl-ebook/).

**Comment by steveklabnik** [comment] 2016-01-04 17:40
Further update: I am still interested in getting this done, but takes some infrastructure work. @brson and @edunham and I should chat about it, maybe.

**Comment by asolove** [comment] 2016-01-11 14:14
Working on a general way to do this in https://github.com/azerupi/mdBook/issues/88.

In the meantime, a rust book-specific version is probably as simple as:

```
pandoc -S -o book.epub {list of markdown files in the order they should be included}`.
```

**Comment by brson** [comment] 2016-01-11 19:54
It's not too difficult to make *one of our doc builders* produce the epub files and for us to publish it. The big wart here though is that we produce doc packages for every platform we publish, so *every* builder needs pandoc in order to keep them at parity.

One thing we might do in the interim is to make epub artifacts opt-in, set up pandoc on our linux builder only (the one that we use to publish the docs to the website). Then we would be publishing the epubs, but e.g. the mac doc packages wouldn't contain it.

Incidentally, splittiing non-api docs out of the repo would (with a lot of other work) fix this problem since we could build all the docs on linux.

**Comment by okulev** [comment] 2016-03-26 17:38
@killercup doesn't generate epubs anymore :-(

**Comment by okulev** [comment] 2016-03-26 17:44
@killercup doesn't generate epubs anymore :-( So I made a script that generates proper Table Of Contents:

```sh
#!/bin/sh

if [ ! -d "$1" ]; then
	echo Usage: $(basename $0) BOOKDIR \> trpl.md
	echo Then: pandoc -S -o trpl.epub trpl.md
	exit 1
fi

cat "$1/README.md"
echo

grep '^[[:space:]]*\*' "$1/SUMMARY.md" |
sed 's/^\*/main/g' |
sed 's/^[[:space:]]\+\*/sub/g' |
sed 's/\[.*\](\(.*\))/\1/g' |
while read level filename; do
	cat "../$filename" |
	if [ "$level" = "main" ]; then
		sed 's/^\(#\+ \)/#\1/g' |
		sed 's/^% /# /g'
	else
		sed 's/^\(#\+ \)/##\1/g' |
		sed 's/^% /## /g'
	fi |
	sed 's/^\(```rust\),.*$/\1/g'
	echo
done
```

**Comment by pravic** [comment] 2016-05-31 08:37
> @killercup doesn't generate epubs anymore :-(

@okulev, but you can find it in [PRs](https://github.com/killercup/trpl-ebook/pull/36) as I did.

**Comment by edunham** [comment] 2016-08-22 23:13
Help wanted: Write a .travis.yml to do this build on Travis and upload it to GitHub's releases storage. (ping me for help if this is confusing)

**Comment by bkoehm** [comment] 2017-03-03 01:09
Script from @okulev worked nicely for me, so +1 for that.
I wanted a PDF instead of an EPUB so I added this step:

`ebook-convert trpl.epub trpl.pdf`

ebook-convert is from [Calibre](http://calibre-ebook.com/).

I tried ebook-convert directly on the md instead of epub and it produced a PDF, but the resulting PDF is better if you use pandoc to convert it to epub first.

**Comment by pravic** [comment] 2017-04-03 04:38
Any download links to the recent book versions?

**Comment by codingHahn** [comment] 2017-05-23 16:48
@killercup 's repo works, but the files need to be updated. @killercup how would I do this?

**Comment by pravic** [comment] 2017-08-22 19:48
Since there is no any progress:
https://github.com/lise-henry/books - not perfect, but from June 2017.
https://github.com/killercup/trpl-ebook/pull/47 PR for killercup's books from May 2017, but unmerged.

That's all I found, rest are just talks and wishes.

**Comment by jasonwilliams** [comment] 2018-05-10 00:38
@steveklabnik @brson any update on this? There’s still no easy way to read the rust book offline on an iPad. I wonder if we can use service workers to cache all the pages on the site, the single page html doesn’t work as it chokes my tablet

**Comment by steveklabnik** [comment] 2018-05-10 14:08
No changes; print to PDF is still the best option.

**Comment by jasonwilliams** [comment] 2018-05-10 16:44
On iOS the default option is to add the PDF to ibooks where it doesn’t come out right, you can’t use the built in features such as bookmark, take notes, page numbers, index. Is there not an easy way to auto generate an epub file on each update?

**Comment by steveklabnik** [comment] 2018-05-10 21:29
> Is there not an easy way to auto generate an epub file on each update?

Not currently.

> If it’s a case of time anyway I can help?

Sure! The first thing we'd need is support in mdbook; then we'd have to change the infrastructure to actually use that new code.

**Comment by jasonwilliams** [comment] 2018-05-10 21:57
@steveklabnik I’m not sure if this is the right repo to raise it,  but could we take advantage of service workers to cache the book so it can be read offline? I would be happy to work on this if it’s possible.

**Comment by pravic** [comment] 2018-05-11 08:50
May be offline version is abandoned in favor of a [printed version](https://www.nostarch.com/Rust)?

**Comment by steveklabnik** [comment] 2018-05-28 15:40
> May be offline version is abandoned in favor of the printed version?

It's not, it's abandoned because nobody has wanted to put in the work to get it working. The second edition online is literally the same as the printed book / ebook as far as the text goes; No Starch has their own typesetting and such that makes their PDF worth buying, but that doesn't preclude us from generating one ourselves as well.

**Comment by hawkins** [comment] 2018-12-08 03:15
FWIW, a PR was opened against the book to add support for building an ePub just last week: https://github.com/rust-lang/book/pull/1654

**Comment by gluons** [comment] 2019-01-03 13:00
I'm also waiting for EPUB. I'm frequently reading on mobile in train. Reading on web isn't comfortable for me. ☹️

**Comment by jasonwilliams** [comment] 2019-01-03 14:14
@gluons yep i had the same issue, I ended up buying the e-book of Amazon because i needed an offline version for train reading.

is it possible to take @jmoy's [PR ](https://github.com/rust-lang/book/pull/1654) and apply it to https://github.com/rust-lang-nursery/mdBook/issues/88 instead?

**Comment by monokrome** [comment] 2019-04-11 03:22
What's the status here? I'd love to get this book on my Kobo reader :)

**Comment by Holyprogrammer** [comment] 2019-05-04 07:48
Any updates?

**Comment by justacec** [comment] 2019-05-15 14:37
Ohhh please....

This is me not reading the rust documentation on my flight from San Diego to DC...

**Comment by dolph** [comment] 2019-05-15 14:43
Resolving this issue would be entirely worth the effort. For Rust to be successful, people need to be able to learn about it, and this issue is fundamentally about accommodating alternative learning environments.

**Comment by steveklabnik** [comment] 2019-05-16 12:22
@justacec you can `rustup doc --book` to read the book in HTML form locally.

@dolph nobody disagrees that this isn't worth doing. Nobody has stepped up to actually do it.

**Comment by jiacai2050** [comment] 2019-05-17 01:58
Is there anyone try [Calibre](https://manual.calibre-ebook.com/conversion.html). looks promising.

**Comment by vitali2y** [comment] 2019-05-26 02:26
Next **quick** "life hack" for **many** formats (e. g. _epub_, _docbook_, or _fb2_) works for **up-to-date** and **any** doc from [Learn Rust](https://www.rust-lang.org/learn) page:

1. click "_Print this book_" icon on top right corner,
2. "_Cancel_" print popup,
3. press _F12_,
4. copy-n-paste-n-enter next into "_Console_" tab:

```
document.getElementById('sidebar').remove();
document.getElementById('menu-bar').remove();
Array.from(document.querySelectorAll("div.buttons")).forEach(el => el.remove());
Array.from(document.querySelectorAll("img.ferris")).forEach(el => el.remove());
document.getElementById('page-wrapper').classList.remove('page-wrapper');
Array.from(document.getElementsByTagName('script')).forEach(el => el.remove());
document.getElementById('sections').remove();
```
_Hint:_ next extra line is required for [WebAssembly Book](https://rustwasm.github.io/docs/book/print.html ) (because paths to images are broken in print mode):

`Array.from(document.getElementsByTagName('img')).forEach(function(el) { if (el.src.indexOf('https://rustwasm.github.io/docs/images/') > -1) el.src = 'https://rustwasm.github.io/docs/book/images/game-of-life/' + el.src.split(/[/ ]+/).pop() });`

5. right mouse click, "_Save as..._" HTML (e. g. _TheRustcBook190626.html_) file (use "_Webpage, Complete_" file type for saving!),
6. from _CLI_ execute:

`F="TheRustcBook190626" && pandoc $F.html --to=epub --output=$F.epub && ls -l $F.epub`

7. enjoy _TheRustcBook190626.epub_ on your e-reader!

**Comment by DevQps** [comment] 2019-08-08 20:58
For people that are curious about what it would look like:

<img width="960" alt="With Margin" src="https://user-images.githubusercontent.com/46896178/62737305-c140f600-ba2f-11e9-9578-1b09a2d94708.png">

As an extra tip!: If you want the page to be broader (so you don't have to zoom in on some E-readers) you can also add:

```
document.getElementsByTagName("main")[0].style.maxWidth = "auto";
```

You would then get something like this:

<img width="960" alt="Without Margin" src="https://user-images.githubusercontent.com/46896178/62737306-c1d98c80-ba2f-11e9-92c7-8421019730ce.png">

I am not sure how hard it would be to create a small program that could also generate a PDF or EPUB file and add a button to download it on each webpage. I might try to look into that if I can find some time!

**Comment by jasonwilliams** [comment] 2019-08-09 12:34
As a slight update to this thread, I'm going to see if i can get https://github.com/rust-lang-nursery/mdBook/issues/546 moving again, as the people previously working on it have left.

**Comment by DevQps** [comment] 2019-08-09 16:44
@jasonwilliams That would be great! Let us know if there's any progress! (Y)

**Comment by jasonwilliams** [comment] 2019-08-13 15:31
@DevQps 
There is progress, see https://github.com/rust-lang-nursery/mdBook/pull/1000
Feel free to test it out and give feedback, there are instructions in the PR

**Comment by kaizhang91** [comment] 2019-10-14 02:29
> pandoc

a

**Comment by kaizhang91** [comment] 2019-10-14 02:32
Hello everyone, I use `pandoc` inspired by <https://github.com/rust-lang/rust/issues/20866#issuecomment-170563129>

**Comment by antoneliasson** [comment] 2019-12-20 21:47
> Hello everyone, I have generated the `epub` and `pdf` version by `pandoc` inspired by [#20866 (comment)](https://github.com/rust-lang/rust/issues/20866#issuecomment-170563129). And here is the links:
> 
>     * https://github.com/kaizhang91/book/blob/feature-epub-and-pdf/assets/The-Rust-Programming-Language-2019-10-13.epub
> 
>     * https://github.com/kaizhang91/book/blob/feature-epub-and-pdf/assets/The-Rust-Programming-Language-2019-10-13.pdf
> 
> 
> Hope it helps.

Thanks for generating the offline ebooks! Your epub lacks the "ferrises" in the code boxes and some words are hyphenated in strange ways, but otherwise it looks great and is perfectly usable! I've so far enjoyed about the first quarter of it.

The PDF on the other hand has a few major problems. Some code boxes are completely missing content (e.g. page 22, pages 74-80). In at least one place a big chunk of text is missing. Some of it has not compiled properly and is shown as a compressed super long line of TeX code (page 29).

An epub rendering is what I wanted the most though, so thanks again for that!

**Comment by kaizhang91** [comment] 2020-01-10 13:09
@antoneliasson Thank you for you detailed bug report! I'm very happy to hear about that the offline book is helpful. However, let me clarify some points first:

- epub version:
    - It does not lack "ferrises". It's true that they aren't shown on `duokan` or `iReader`, but they are shown on `calibre`. So the bug is related to the capacity of epub reader for rendering some `css` syntax.
    - Actually, `image` and code block are also not supported by some epub reader
- pdf version:
    - As you kindly explained, there are some serious bugs in `2019-10-13` version, so I create `2019-10-17` version
    - In `2019-10-17` version, I have solved code box bug. And I think it's true for page 22, pages 74-80, etc.
    - In `2019-10-17` version, there are still some super long line. This bug is related to <https://github.com/gpoore/minted/issues/194>. Maybe I have no time to fix it recently.

In fact, I have read through the `2019-10-17` pdf version instead of the `2019-10-13` epub version. :smiley: Maybe some serious bugs you most care about have already been fixed. Give it a try if you're interested in the pdf version someday. :wink:

**Comment by jasonwilliams** [comment] 2020-02-25 23:38
Help Needed!

https://github.com/rust-lang/mdBook/pull/1000 seems to be working pretty well from what i can see so far, I just need some feedback now. The PR allows the rust book to be read offline, new changes will still take affect.

You can just navigate to https://jason-williams.co.uk/book/ and try it out, then leave any feedback in the issue.

**Comment by Sjord** [comment] 2021-06-30 18:16
I recently used [mdbook-epub](https://github.com/Michael-F-Bryan/mdbook-epub) to build an epub version of several mdbooks, and this worked reasonably well.

**Comment by shirshak55** [comment] 2022-01-08 12:21
For pdf:
I managed to automate somehow. Let me know
https://github.com/shirshak55/Rust-Book-In-PDF/releases

**Comment by vitali2y** [comment] 2022-01-08 12:33
Letting you know that *.epub* version of *the Book* would be nice to have here.

**Comment by peterbartha** [comment] 2022-04-10 21:12
Latest DIY steps for converting (any) **[Rust learning material](https://www.rust-lang.org/learn)** to EPUB (or other ebook formats).
Steps and required files: https://gist.github.com/peterbartha/54708ae739478a45b52612311d49717c

Samples:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/7854312/162639910-d8e51d58-2bd0-48ee-874c-f5df428f5a3e.png">
---
<img width="616" alt="image" src="https://user-images.githubusercontent.com/7854312/162640021-178d275f-9491-47cb-885c-d36ea92cfa47.png">

**Comment by vitali2y** [comment] 2022-04-10 21:42
> Latest DIY steps for converting (any) **[Rust learning material](https://www.rust-lang.org/learn)** to EPUB (or other ebook formats). Steps and required files: https://gist.github.com/peterbartha/54708ae739478a45b52612311d49717c

What are principal improvements in comparison with [~3 years old receipt](#issuecomment-495962961)?

**Comment by peterbartha** [comment] 2022-04-10 23:27
> > Latest DIY steps for converting (any) **[Rust learning material](https://www.rust-lang.org/learn)** to EPUB (or other ebook formats). Steps and required files: https://gist.github.com/peterbartha/54708ae739478a45b52612311d49717c
> 
> What are principal improvements in comparison with [~3 years old receipt](#issuecomment-495962961)?

The following:
1. More readable source code (previously problems with nested `<pre>` tags, and pandoc optimizations),
2. Clickable "Table of Contents" section added,
3. Code legend (Ferris) is present (instead of removing from the samples),
4. Handle unsupported HTML tags (i.e. `<details>`),
5. (Optional) Consistent stylesheet for the ebook.

**Comment by johnroyer** [comment] 2022-05-02 11:50
The file below, published at 2022-01-13, is convert via Epubor. Download if you need.

https://s3.ap-northeast-1.amazonaws.com/assets.blog.zeroplex.tw/2022/2022-01-13-The-Rust-Programming-Language.epub

**Comment by CeresCa** [comment] 2022-06-25 15:32
This browser extension can convert HTML to EPUB easily.
https://github.com/dteviot/WebToEpub

**Comment by anzbert** [comment] 2022-08-07 09:44
thx @CeresCa .
I've used that extension to create create an epub for the latest book version
[The_Rust_Programming_Language_1.59.epub.zip](https://github.com/rust-lang/rust/files/9276553/The_Rust_Programming_Language_1.59.epub.zip)

**Comment by miguno** [comment] 2023-01-10 16:40
@peterbartha's instructions (https://gist.github.com/peterbartha/54708ae739478a45b52612311d49717c) worked for me. Thanks!

**Comment by lapwat** [comment] 2023-01-23 10:42
You can easily create the ebook yourself with [papeer](https://github.com/lapwat/papeer). It keeps content, text formatting, images and code blocks.

Install it with: `go install github.com/lapwat/papeer@latest`

Use the CSS selector `ol>li>a` to select all table of content items. Specify `epub` format.

```sh
papeer get --selector='ol>li>a' --format=epub https://doc.rust-lang.org/book/
# [===========>] The Rust Programming Language - The Rust Programming Language (104 / 104)
# Ebook saved to "The_Rust_Programming_Language_-_The_Rust_Programming_Language.epub"
```
[The_Rust_Programming_Language_-_The_Rust_Programming_Language.epub.zip](https://github.com/rust-lang/rust/files/10478882/The_Rust_Programming_Language_-_The_Rust_Programming_Language.epub.zip)

**Comment by ivanglushko** [comment] 2023-05-25 18:40
Here's a **pdf** print from the site - And I manually aded **table of contents** there.

[The Rust Programming Language.pdf](https://github.com/rust-lang/rust/files/11568252/The.Rust.Programming.Language.pdf)

**Comment by vitali2y** [comment] 2023-05-25 19:25
> Here's a **pdf** print from the site - And I manually added **table of contents** there.

Cool. How about [.epub](https://github.com/rust-lang/rust/issues/20866#issuecomment-1007977579) as on title on the top?

**Comment by shirshak55** [comment] 2023-06-01 02:44
@impredicative  if you are seeking pdf then you can find it here. Updated daily. https://github.com/shirshak55/Rust-Book-In-PDF/releases

**Comment by ivanglushko** [comment] 2023-06-01 08:56
> How does one go about finding such a link for a future version?
I don't plan on keeping this up to date sorry. Maybe it's possible to write a script that will link all the chapters in pdf but I didn't find a fast solution. So had to do it manually.

**Comment by dralley** [comment] 2023-09-04 22:13
This is a duplicate of https://github.com/rust-lang/book/issues/3669 - in any case, book related issues should be filed over there.

**Comment by Dylan-DPC** [comment] 2023-11-18 18:19
Closing this as the book issue already covers this

**Closed by Dylan-DPC** 2023-11-18 18:19 UTC
Labels: P-low, E-help-wanted, A-docs, C-feature-request

**Comment by dieterplex** [comment] 2024-02-07 02:36
Like shirshak55's daily PDF https://github.com/shirshak55/Rust-Book-In-PDF/releases,
here's my daily ePub https://dieterplex.github.io/rust-ebookshelf/ in case someone is still interested.
