### ISSUE TITLE
module names differing only in capitalization cause "unrelated" error messages on windows

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#19139] opened 2014-11-20 12:07 UTC
on windows, two files/folders whose names only differs in capitalization cannot exist.
So when i compile the following program, the error message has (nearly) nothing to do with the actual problem.

```rust
// main.rs
mod mod_a;
mod moD_a;
fn main() {}
```

```rust
// mod_a/mod.rs
pub mod mod_b {
    use mod_a::StructA;

    impl PartialEq for StructA {
        fn eq(&self, other: &StructA) -> bool { true }
    }
}
struct StructA;
```

```
mod_a\mod.rs:5:5: 7:6 error: conflicting implementations for trait `core::cmp::PartialEq` [E0119]
mod_a\mod.rs:5     impl PartialEq for StructA {
mod_a\mod.rs:6         fn eq(&self, other: &StructA) -> bool { true }
mod_a\mod.rs:7     }
moD_a\mod.rs:5:5: 7:6 note: note conflicting implementation here
moD_a\mod.rs:5     impl PartialEq for StructA {
moD_a\mod.rs:6         fn eq(&self, other: &StructA) -> bool { true }
moD_a\mod.rs:7     }
```
it does not matter whether the actual folder's name is "mod_a" or "moD_a", the error is exactly the same. When the two mod lines are exchanged, the error messages also change their order.

Note: the warning about snake case only occurs if there is no conflicting implementation error, so this does not help finding the problem.

The easy fix would be to check that the name of the folder and filename of the module are exactly the same.
But this also shows the issue, that two modules whose name only differs in caps might exists on e.g. linux.

**Comment by kmcallister** [comment] 2015-01-28 03:53
Not sure this is really a bug. You get the same thing with

```rust
mod mod_a;
#[path="mod_a/mod.rs"] mod mod_b;
```

although in this case it's more obvious, and not a platform detail, that you've included the same code twice in the crate.

The error message also looks correct, although the difference in the file names is certainly easy to miss.

**Comment by oli-obk** [comment] 2015-01-28 08:46
could a windows-only lint find this before the conflicting implementations error?

**Comment by alexcrichton** [comment] 2015-08-13 21:00
I don't think this is a windows-specific issue (as pointed out) and otherwise the diagnostics here are correct, so I'm going to close this as not a bug.

**Closed by alexcrichton** 2015-08-13 21:00 UTC
Labels: A-diagnostics, A-windows
