### ISSUE TITLE
rustc' panicked at 'assertion failed: declare::get_defined_value(ccx, &symbol).is_none()'

### ISSUE THREAD

**Issue by aschoerk** [rust-lang/rust#32749] opened 2016-04-05 16:54 UTC
Hello,

I tried to compile: https://github.com/willi-kappler/mandel-rust.git
and was requested to send a bug report:

rustc --version
rustc 1.9.0-dev (30a3849f2 2016-03-30)

cargo --version
cargo 0.10.0 (12f76a5 2016-04-02)

--verbose and backtrace:
 cargo run --verbose
       Fresh log v0.3.6
       Fresh bitflags v0.3.3
       Fresh libc v0.2.9
       Fresh rustc-serialize v0.3.19
       Fresh ansi_term v0.7.2
       Fresh winapi v0.2.6
       Fresh variance v0.1.3
       Fresh vec_map v0.4.0
       Fresh crossbeam v0.1.6
       Fresh winapi-build v0.1.1
       Fresh num_cpus v0.2.11
       Fresh rand v0.3.14
       Fresh scopeguard v0.1.2
       Fresh scoped_threadpool v0.1.7
       Fresh crossbeam v0.2.8 (https://github.com/aturon/crossbeam.git#22ed9ba3)
       Fresh strsim v0.4.0
       Fresh simple_parallel v0.3.0
       Fresh crossbeam v0.2.8
       Fresh deque v0.3.1
       Fresh jobsteal v0.2.4
       Fresh num v0.1.31
       Fresh kirk v0.0.1 (https://github.com/kinghajj/kirk.git#cff7bca7)
       Fresh clap v1.5.5
       Fresh scoped-pool v0.1.9
       Fresh rayon v0.2.0
       Fresh kernel32-sys v0.2.1
       Fresh time v0.1.35
   Compiling mandel v0.3.0 (file:///home/aschoerk/projects/rust/mandel-rust)
     Running `rustc src/main.rs --crate-name mandel --crate-type bin -g --out-dir /home/aschoerk/projects/rust/mandel-rust/target/debug --emit=dep-info,link -L dependency=/home/aschoerk/projects/rust/mandel-rust/target/debug -L dependency=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps --extern num_cpus=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libnum_cpus-a5254d7bdb51bb96.rlib --extern time=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libtime-71756e48b8b5b73b.rlib --extern simple_parallel=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libsimple_parallel-66bb3de1dace7bcd.rlib --extern clap=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libclap-81a4ff70e0d5e08c.rlib --extern rayon=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/librayon-2b74ed11820e27fc.rlib --extern scoped_threadpool=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libscoped_threadpool-649c3cfa7627d5dd.rlib --extern scoped_pool=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libscoped_pool-fbc45ed9d1001008.rlib --extern crossbeam=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libcrossbeam-975110fb6f48296c.rlib --extern num=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libnum-a2e6e61627ca7fe5.rlib --extern jobsteal=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libjobsteal-dd23a253ed766422.rlib --extern kirk=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libkirk-5697a0e90b754e17.rlib`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'assertion failed: declare::get_defined_value(ccx, &symbol).is_none()', src/librustc_trans/monomorphize.rs:94
stack backtrace:
   1:     0x7f08bec15340 - std::sys::backtrace::tracing::imp::write::h3152d690c5b90b0c
   2:     0x7f08bec22a1b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hb638acea7c29901b
   3:     0x7f08bec225b7 - std::panicking::default_hook::h508c3dab3df347d6
   4:     0x7f08bebe632f - std::sys_common::unwind::begin_unwind_inner::h5cd31b1580026517
   5:     0x7f08bd76c18f - std::sys_common::unwind::begin_unwind::h422885d31fe250dc
   6:     0x7f08bd813ef5 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
   7:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
   8:     0x7f08bd80d86f - rustc_trans::callee::Callee::method_call::h2d0c04406cd201d6
   9:     0x7f08bd870cff - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  10:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  11:     0x7f08bd8ab6bd - rustc_trans::_match::mk_binding_alloca::h13fd639ad8987aa8
  12:     0x7f08bd7c965d - rustc_trans::base::init_local::h8473d4381ca140d0
  13:     0x7f08bd7deac4 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  14:     0x7f08bd870e30 - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  15:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  16:     0x7f08bd7deded - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  17:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  18:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  19:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  20:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  21:     0x7f08bd80d86f - rustc_trans::callee::Callee::method_call::h2d0c04406cd201d6
  22:     0x7f08bd870cff - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  23:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  24:     0x7f08bd7deded - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  25:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  26:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  27:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  28:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  29:     0x7f08bd8714bf - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  30:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  31:     0x7f08bd7deded - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  32:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  33:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  34:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  35:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  36:     0x7f08bd80d86f - rustc_trans::callee::Callee::method_call::h2d0c04406cd201d6
  37:     0x7f08bd870cff - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  38:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  39:     0x7f08bd84d41b - rustc_trans::controlflow::trans_stmt_semi::he5fc3098b8797bcf
  40:     0x7f08bd7deaa0 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  41:     0x7f08bd870e30 - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  42:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  43:     0x7f08bd7deded - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  44:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  45:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  46:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  47:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  48:     0x7f08bd8849b7 - rustc_trans::glue::trans_struct_drop::h1ba4ff24ef161f06
  49:     0x7f08bd8844c4 - rustc_trans::glue::trans_struct_drop_flag::hd5a179a713658dc9
  50:     0x7f08bd881a38 - rustc_trans::glue::get_drop_glue_core::hb344afb791d11021
  51:     0x7f08bd82cf95 - rustc_trans::glue::drop_ty_core::hf948489b2dcfe8f2
  52:     0x7f08bd82b860 - _<cleanup..DropValue<'tcx> as cleanup..Cleanup<'tcx>>::trans::hdac66e0659394f10
  53:     0x7f08bd82ae07 - _<common..FunctionContext<'blk, 'tcx> as cleanup..CleanupHelperMethods<'blk, 'tcx>>::trans_cleanups_to_exit_scope::ha42760eb78a7abf5
  54:     0x7f08bd82c50b - _<common..FunctionContext<'blk, 'tcx> as cleanup..CleanupHelperMethods<'blk, 'tcx>>::get_or_create_landing_pad::h23c8131d22dfd35a
  55:     0x7f08bd7c8463 - _<common..FunctionContext<'blk, 'tcx> as cleanup..CleanupMethods<'blk, 'tcx>>::get_landing_pad::h24ab095fd77d709f
  56:     0x7f08bd7c8050 - rustc_trans::base::invoke::h8a9aa9b99b9a9fe3
  57:     0x7f08bd7bde7a - rustc_trans::callee::Callee::call::h19b66818aa33602f
  58:     0x7f08bd7bcece - rustc_trans::base::malloc_raw_dyn::hea8d9188e2d9f23a
  59:     0x7f08bd877154 - rustc_trans::expr::trans_uniq_expr::hc4a05302f152a17a
  60:     0x7f08bd86f229 - rustc_trans::expr::trans_unadjusted::h1b27fd93a8fc3de1
  61:     0x7f08bd7e743d - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  62:     0x7f08bd8ab6bd - rustc_trans::_match::mk_binding_alloca::h13fd639ad8987aa8
  63:     0x7f08bd7c965d - rustc_trans::base::init_local::h8473d4381ca140d0
  64:     0x7f08bd7deac4 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  65:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  66:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  67:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  68:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  69:     0x7f08bd8714bf - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  70:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  71:     0x7f08bd8ab6bd - rustc_trans::_match::mk_binding_alloca::h13fd639ad8987aa8
  72:     0x7f08bd7c965d - rustc_trans::base::init_local::h8473d4381ca140d0
  73:     0x7f08bd7deac4 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  74:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  75:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  76:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  77:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  78:     0x7f08bd8714bf - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  79:     0x7f08bd86f40d - rustc_trans::expr::trans_unadjusted::h1b27fd93a8fc3de1
  80:     0x7f08bd8269e9 - rustc_trans::expr::trans::h2a1eefba3fa0b5db
  81:     0x7f08bd7c972a - rustc_trans::base::init_local::h8473d4381ca140d0
  82:     0x7f08bd7deac4 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  83:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  84:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  85:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  86:     0x7f08bd7beaee - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  87:     0x7f08bd8714bf - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  88:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  89:     0x7f08bd8ab6bd - rustc_trans::_match::mk_binding_alloca::h13fd639ad8987aa8
  90:     0x7f08bd7c965d - rustc_trans::base::init_local::h8473d4381ca140d0
  91:     0x7f08bd7deac4 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
  92:     0x7f08bd7dd167 - rustc_trans::base::trans_closure::hab0bbfdf7f78389b
  93:     0x7f08bd7df6b0 - rustc_trans::base::trans_fn::hde3bb018b7978cd9
  94:     0x7f08bd812db1 - rustc_trans::callee::get_fn::h7ef29e7f5ef4be1c
  95:     0x7f08bd7bec50 - rustc_trans::callee::Callee::def::h6d1e0026eca7dcee
  96:     0x7f08bd8714bf - rustc_trans::expr::trans_rvalue_dps_unadjusted::h25a69c48d600dd77
  97:     0x7f08bd7e7574 - rustc_trans::expr::trans_into::hf4dacfb7852c1e66
  98:     0x7f08bd8ab6bd - rustc_trans::_match::mk_binding_alloca::h13fd639ad8987aa8
  99:     0x7f08bd7c965d - rustc_trans::base::init_local::h8473d4381ca140d0
  100:     0x7f08bd7deac4 - rustc_trans::controlflow::trans_block::h1902d345489b6fad
 ... <frames omitted>

error: Could not compile `mandel`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name mandel --crate-type bin -g --out-dir /home/aschoerk/projects/rust/mandel-rust/target/debug --emit=dep-info,link -L dependency=/home/aschoerk/projects/rust/mandel-rust/target/debug -L dependency=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps --extern num_cpus=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libnum_cpus-a5254d7bdb51bb96.rlib --extern time=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libtime-71756e48b8b5b73b.rlib --extern simple_parallel=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libsimple_parallel-66bb3de1dace7bcd.rlib --extern clap=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libclap-81a4ff70e0d5e08c.rlib --extern rayon=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/librayon-2b74ed11820e27fc.rlib --extern scoped_threadpool=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libscoped_threadpool-649c3cfa7627d5dd.rlib --extern scoped_pool=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libscoped_pool-fbc45ed9d1001008.rlib --extern crossbeam=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libcrossbeam-975110fb6f48296c.rlib --extern num=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libnum-a2e6e61627ca7fe5.rlib --extern jobsteal=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libjobsteal-dd23a253ed766422.rlib --extern kirk=/home/aschoerk/projects/rust/mandel-rust/target/debug/deps/libkirk-5697a0e90b754e17.rlib` (exit code: 101)
.

**Comment by dotdash** [comment] 2016-04-05 17:02
Thanks for the bug report. This is a duplicate of #32530 which has been fixed already, downloading a current nightly build should allow you to build the crate.

**Closed by dotdash** 2016-04-05 17:02 UTC
