### ISSUE TITLE
Weird import suggestion

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#105373] opened 2022-12-06 14:35 UTC
I think it'll be pretty explicit by itself:

```
error[E0432]: unresolved import `rustc_infer::traits::ObligationCtxt`
  --> src/librustdoc/clean/mod.rs:21:56
   |
21 | use rustc_infer::traits::{Obligation, ObligationCause, ObligationCtxt};
   |                                                        ^^^^^^^^^^^^^^ no `ObligationCtxt` in `traits`
   |
help: a similar name exists in the module
   |
21 | use rustc_infer::traits::{Obligation, ObligationCause, Obligation};
   |                                                        ~~~~~~~~~~
help: consider importing this struct instead
   |
21 | use rustc_infer::traits::{Obligation, ObligationCause, rustc_trait_selection::traits::ObligationCtxt;
   |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It is suggesting to add an item from another dependency directly inside the current one, which is obviously wrong.

**Comment by est31** [comment] 2022-12-29 22:48
Dupe of #103943

**Closed** 2023-01-10 06:22 UTC
Labels: A-diagnostics, T-compiler, A-suggestion-diagnostics, D-invalid-suggestion
