### ISSUE TITLE
Rust build failure on Solaris SPARC - error[E0093]: unrecognized intrinsic function: `read_via_copy`

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#109492] opened 2023-03-22 16:16 UTC
My Rust language build (latest git sources) fails on Solaris SPARC with:
```
Building stage0 library artifacts (sparcv9-sun-solaris)
   Compiling cc v1.0.77
   Compiling core v0.0.0 (/builds2/psumbera/rust-lang-build/library/core)
   Compiling libc v0.2.139
   Compiling memchr v2.5.0
   Compiling std v0.0.0 (/builds2/psumbera/rust-lang-build/library/std)
   Compiling compiler_builtins v0.1.87
   Compiling unwind v0.0.0 (/builds2/psumbera/rust-lang-build/library/unwind)
error[E0093]: unrecognized intrinsic function: `roundevenf32`
    --> library/core/src/intrinsics.rs:1624:5
     |
1624 |     pub fn roundevenf32(x: f32) -> f32;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unrecognized intrinsic

error[E0093]: unrecognized intrinsic function: `roundevenf64`
    --> library/core/src/intrinsics.rs:1630:5
     |
1630 |     pub fn roundevenf64(x: f64) -> f64;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unrecognized intrinsic

error[E0093]: unrecognized intrinsic function: `read_via_copy`
    --> library/core/src/intrinsics.rs:2031:5
     |
2031 |     pub fn read_via_copy<T>(p: *const T) -> T;
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unrecognized intrinsic

For more information about this error, try `rustc --explain E0093`.
error: could not compile `core` due to 3 previous errors
Build completed unsuccessfully in 0:15:48
```

I did configure it like this:
```
./configure --default-linker=gcc --enable-local-rust  --enable-extended --tools="cargo,rustfmt"
```

and have Rust 1.70-dev (from March 7th) in my PATH.

Any suggestion please? I also wonder why it downloads rustfmt-nightly-sparcv9-sun-solaris.tar.xz and rustc-nightly-sparcv9-sun-solaris.tar.xz (which I had to prepare myself) when I do use `--enable-local-rust`.

**Comment by workingjubilee** [comment] 2023-03-23 00:28
Something is amiss with this attempt to bootstrap. These are intrinsics introduced recently into the core library. During bootstrap, however, the expectation to compile them should be omitted. What is the post-configure invocation you attempted and what is the actual `rustc --version --verbose` of the rustc you are trying to build with?

**Comment by workingjubilee** [comment] 2023-03-23 01:23
Apparently `--enable-local-rust`, by setting `build.rustc`, implies that it will not use `--cfg bootstrap`. That seems... incorrect. Regardless, the current answer to your question is to either not use `--enable-local-rust` (and thus not setting `build.rustc`) or to do something like directly set `--cfg bootstrap` in RUSTFLAGS (and then rebuild with the bootstrapped compiler, probably).

**Comment by cuviper** [comment] 2023-03-23 02:10
The `cfg(bootstrap)` code only works with the prior version (1.69) for stage0. If the version looks the same, we treat it as a rebuild matching the current feature set of the tree. We can't handle the feature gradient of everything that changed between those positions, so if your 1.70-dev is older than some current change, it won't work.

**Comment by jyn514** [comment] 2023-03-23 16:24
> I wonder why there is no commit hash in verbose version:

This is intentional, to avoid rebuilding the world after each change in development mode. https://github.com/rust-lang/rust/blob/99c49d95cd7d704d2226859cfdc419c930cde9c6/config.example.toml#L576-L580

If you are building a production toolchain, you should set `channel = "nightly"` or some other supported channel; `dev` influences several other defaults that you probably don't want for a distro build.

**Comment by jyn514** [comment] 2023-03-23 16:26
Hmm, I wonder if we should change the default channel to `nightly` for `profile = user`

cc the suggestion to disallow building without a `profile` set in https://jyn.dev/2023/01/12/Bootstrapping-Rust-in-2023.html#misc-breaking-changes

**Comment by cuviper** [comment] 2023-03-23 17:29
I don't think any profile changes will help the root cause here. No matter how we look at the versions, we don't have any configuration that will work with stage0 "1.70 from March 7th". We have `cfg(bootstrap)` that will work with 1.69-ish features, or `cfg(not(bootstrap))` that works with *current* 1.70 features, and the rebuild mode only makes stage0 act like the latter too.

(The "rebuild" version matching only looks at the first 1.N part anyway, so e.g. using stage0 `1.68.0` is still a rebuild as far as features go for building `1.68.1`.)

**Comment by jyn514** [comment] 2023-03-25 20:19
I'm going to close this since it's not a bug in bootstrap or the standard library.

**Closed by jyn514** 2023-03-25 20:19 UTC
Labels: T-bootstrap, C-discussion
