### ISSUE TITLE
rust-release-1.1.0 cannt configure on osx 10.11(beta 4)

### ISSUE THREAD

**Issue by imiskolee** [rust-lang/rust#27492] opened 2015-08-03 13:14 UTC
the ./configure output is :  

configure: looking for configure programs
configure: found program cmp
configure: found program mkdir
configure: found program printf
configure: found program cut
configure: found program head
configure: found program grep
configure: found program xargs
configure: found program cp
configure: found program find
configure: found program uname
configure: found program date
configure: found program tr
configure: found program sed
configure: found program file
configure: found program make
configure: inspecting environment
configure: recreating config.tmp
configure:
configure: processing ./configure args
configure:
configure: CFG_LOCALSTATEDIR    := /var/lib
configure: CFG_SYSCONFDIR       := /etc
configure: CFG_DATADIR          := /share
configure: CFG_INFODIR          := /share/info
configure: CFG_LLVM_ROOT        :=
configure: CFG_JEMALLOC_ROOT    :=
configure: CFG_BUILD            := x86_64-apple-darwin
configure: CFG_ANDROID_CROSS_PATH := /opt/ndk_standalone
configure: CFG_RELEASE_CHANNEL  := dev
configure: CFG_MUSL_ROOT        := /usr/local
configure: CFG_BUILD            := x86_64-apple-darwin
configure: CFG_LIBDIR           := /usr/local/lib
configure:
configure: validating ./configure args
configure:
configure: CFG_BOOTSTRAP_KEY    := 21:11:31
configure:
configure: looking for build programs
configure:
configure: CFG_CURLORWGET       := /usr/bin/curl (7.37.1)
configure: CFG_PYTHON           := /usr/bin/python2.7
configure: CFG_GIT              := /usr/bin/git (2.3.8)
configure: git: no git directory. disabling submodules
configure: CFG_MD5              := /sbin/md5
configure: CFG_MD5SUM           :=
configure: CFG_HASH_COMMAND     := /sbin/md5 -q | head -c 8
configure: CFG_CLANG            := /usr/bin/clang++ (7.0.0)
configure: CFG_CCACHE           :=
configure: CFG_GCC              := /usr/bin/gcc (7.0.0)
configure: CFG_LD               := /usr/bin/ld
configure: CFG_VALGRIND         :=
configure: CFG_PERF             :=
configure: CFG_ISCC             :=
configure: CFG_ANTLR4           :=
configure: CFG_GRUN             :=
configure: CFG_FLEX             := /usr/bin/flex (2.5.35)
configure: CFG_BISON            := /usr/bin/bison (2.3)
configure: CFG_PANDOC           :=
configure: CFG_XELATEX          :=
configure: CFG_GDB              :=
configure: CFG_LLDB             := /usr/bin/lldb (340.4.53.3)
configure: CFG_DISABLE_VALGRIND_RPASS := 1
configure: CFG_LLDB_VERSION     := lldb-340.4.53.3
configure: CFG_LLDB_PYTHON_DIR  := /Library/Developer/CommandLineTools ...
configure:
configure: looking for target specific programs
configure:
configure: CFG_ADB              :=
configure:
configure: on OS X >=10.9, forcing use of clang
configure:
configure: CFG_ENABLE_CLANG     := 1
configure: CFG_USING_CLANG      := 1
configure: error: bad CLANG version: 7.0.0, need >=3.0svn

**Comment by barosl** [comment] 2015-08-03 13:47
This was fixed by #27006, but not backported to the 1.1 branch. You will have to apply the patch manually.

**Comment by nagisa** [comment] 2015-08-03 14:33
Duplicate of https://github.com/rust-lang/rust/issues/26292

**Closed** 2015-08-03 17:51 UTC

**Comment by barosl** [comment] 2015-08-03 18:46
Note that Rust 1.2.0, which will be released this week, [has this patch applied](https://github.com/rust-lang/rust/pull/27494). You may wait a few days and try again!
