### ISSUE TITLE
ICE on serde_json::json

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#79939] opened 2020-12-11 17:38 UTC
### Code

This is private project, which I can't share.

I was refactoring code using `serde_json::json!` (version `1.0.55`) macro, there was particular key 
```rust
json!(
{
      "ra": (
      ex.modify_for(maxlen)
      .generators
      .iter()
      .map(|q| q.electricity)
      .iter()
      .enumerate()
     .find(|(_, a)| a.correct)
      .map(|(id, _)| id+1)
     .unwrap_or(0).to_string())
     .join(";")
     )
})
```

Changing from `IterTools::join` (version 0.9.0) to `.collect::<Vec<String>>().join(";")` fixes ICE.

After clean building can't reproduce anymore, seems to be incremental `cargo check` issue.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (d32c320d7 2020-12-10)
binary: rustc
commit-hash: d32c320d7eee56706486fef6be778495303afe9e
commit-date: 2020-12-10
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly

```

### Error output

No error

<details><summary><strong>Backtrace</strong></summary>
<p>

```
    Checking gq v0.1.0 (/home/alik/gq)
thread 'rustc' panicked at 'Failed to recover key for type_of(c7f3ae400006c251-6b016703f8cece60) with hash c7f3ae400006c251-6b016703f8cece60', compiler/rustc_middle/src/ty/query/mod.rs:235:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/d32c320d7eee56706486fef6be778495303afe9e/library/std/src/panicking.rs:435:5
   2: rustc_middle::ty::query::try_load_from_on_disk_cache::{{closure}}
   3: rustc_middle::ty::query::try_load_from_on_disk_cache
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::exec_cache_promotions
   5: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   6: rustc_incremental::persist::save::save_in
   7: rustc_data_structures::sync::join
   8: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
   9: rustc_incremental::persist::save::save_dep_graph
  10: rustc_codegen_ssa::base::finalize_tcx
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  12: rustc_session::utils::<impl rustc_session::session::Session>::time
  13: rustc_interface::passes::QueryContext::enter
  14: rustc_interface::queries::Queries::ongoing_codegen
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: rustc_interface::interface::create_compiler_and_run
  18: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (d32c320d7 2020-12-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `gq`

To learn more, run the command again with --verbose.

```

</p>
</details>

**Comment by jyn514** [comment] 2020-12-11 17:55
Duplicate of https://github.com/rust-lang/rust/issues/79932; this should be fixed in the next nightly.

**Closed by jyn514** 2020-12-11 17:55 UTC
Labels: C-bug, I-ICE, T-compiler
