### ISSUE TITLE
internal compiler error: failed to process buffered lint here

### ISSUE THREAD

**Issue by TheAifam5** [rust-lang/rust#81714] opened 2021-02-03 17:23 UTC
### Code

```Rust
// rocket = { git = "https://github.com/SergioBenitez/Rocket.git", commit = "c24f15c18f02319be83af4f3c1951dc220b52c5e" }
// rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket.git", commit = "c24f15c18f02319be83af4f3c1951dc220b52c5e" }
#![feature(async_closure)]

#[rocket::launch]
fn rocket() -> rocket::Rocket {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-apple-darwin
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
error: internal compiler error: failed to process buffered lint here
  --> /Users/xxx/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/logger.rs:94:68
   |
94 | macro_rules! info_ { ($($args:expr),+) => { log_!(info: $($args),+); }; }
   |                                                                    ^
   | 
  ::: /Users/xxx/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/server.rs:85:23
   |
85 |             Ok(()) => info_!("{}", Paint::green("Response succeeded.")),
   |                       ------------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
  --> /Users/xxx/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/logger.rs:92:70
   |
92 | macro_rules! error_ { ($($args:expr),+) => { log_!(error: $($args),+); }; }
   |                                                                      ^
   | 
  ::: /Users/xxx/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/server.rs:86:23
   |
86 |             Err(e) => error_!("Failed to write response: {:?}.", e),
   |                       --------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rocket`
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-03 17:25
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-03 17:25 UTC
Labels: C-bug, I-ICE, T-compiler
