### ISSUE TITLE
Unexpected end

### ISSUE THREAD

**Issue by notoria** [rust-lang/rust#33055] opened 2016-04-17 15:11 UTC
I tried this code in stable, beta and nightly https://play.rust-lang.org/?gist=279e937d1680d46069c20f7040ca8723&version=stable&backtrace=0 .
In release mode the program ended. I expected to have a infinite loop. In debug mode the program loop forever.

**Comment by GuillaumeGomez** [comment] 2016-04-17 16:06
Just by adding a `printlln!` call, the output is the expected one: http://is.gd/9gD7ec

**Comment by arielb1** [comment] 2016-04-17 16:09
known LLVM problem - duplicate of #28728.

**Closed by arielb1** 2016-04-17 16:09 UTC
