### ISSUE TITLE
incr.comp.: "change nothing" test fails.

### ISSUE THREAD

**Issue by lseugene** [rust-lang/rust#42538] opened 2017-06-08 16:41 UTC
I've been slightly modified incremental/struct_change_nothing.rs test with impl block added. And now it fails.

```
// Copyright 2014 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

// Test incremental compilation tracking where we change nothing
// in between revisions (hashing should be stable).

// revisions:rpass1 rpass2
// compile-flags: -Z query-dep-graph

#![feature(rustc_attrs)]
#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![rustc_partition_reused(module="struct_change_nothing", cfg="rpass2")]

#[cfg(rpass1)]
pub struct X {
    pub x: u32,
}

#[cfg(rpass2)]
pub struct X {
    pub x: u32,
}

#[cfg(rpass1)]
impl X {
    fn get(&self) -> u32 {
        self.x
    }
    pub fn dbl(&self) -> u32 {
        self.get() + self.get()
    }
}

#[cfg(rpass2)]
impl X {
    fn get(&self) -> u32 {
        self.x
    }
    pub fn dbl(&self) -> u32 {
        self.get() + self.get()
    }
}

pub struct EmbedX {
    x: X,
}

pub struct Y {
    pub y: char,
}

#[rustc_clean(label="TypeckTables", cfg="rpass2")]
pub fn use_X() -> u32 {
    let x: X = X { x: 42 };
    x.x as u32
}

#[rustc_clean(label="TypeckTables", cfg="rpass2")]
pub fn use_EmbedX(x: EmbedX) -> u32 {
    let x: X = X { x: 42 };
    x.x as u32
}

#[rustc_clean(label="TypeckTables", cfg="rpass2")]
pub fn use_Y() {
    let x: Y = Y { y: 'c' };
}

pub fn main() {}
```
pass2 output:
```
$ rustc -Zquery-dep-graph -Zincremental=inc -Zincremental-info src/struct_change_nothing.rs --cfg=rpass2
incremental: session directory: 4 files hard-linked
incremental: session directory: 0 files copied
incremental: module WorkProductId("struct_change_nothing") is dirty because HirBody("struct_change_nothing/8cd878b::{{impl}}[0]::dbl[0]") changed or was removed
error: expected module named `struct_change_nothing` to be Reused but is Translated
  --> src/struct_change_nothing.rs:21:1
   |
21 | #![rustc_partition_reused(module="struct_change_nothing", cfg="rpass2")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

incremental: 23693 nodes in dep-graph
incremental: 39644 edges in dep-graph
incremental: 1080 nodes in reduced dep-graph
incremental: 3646 edges in serialized dep-graph
incremental: 686 hashes in serialized dep-graph
incremental: re-using 0 out of 1 modules
error: aborting due to previous error(s)
```

```
$ rustc --version
rustc 1.19.0-nightly (76242aebb 2017-06-06)
$ cargo --version
cargo 0.20.0-nightly (38ca9b702 2017-05-14)
```

**Comment by MageSlayer** [comment] 2017-06-09 16:00
@nikomatsakis 
Can it related somehow to #37121?

**Comment by nikomatsakis** [comment] 2017-06-09 21:33
It might be because the spans changed -- and the `+` operation may panic (on overflow). In other words, something *did* change in between the two copies of the impl.

**Comment by MageSlayer** [comment] 2017-06-13 07:02
@nikomatsakis 
As the original author does not respond, may I ask - what do mean by saying "something _did_ change"?

Personally, I fail to see any differences between two "impl X". 
Or maybe you mean something internal has changed? Due to changed line numbers, invisible formatting, etc?

**Comment by nikomatsakis** [comment] 2017-06-13 16:25
@MageSlayer 

> Due to changed line numbers, invisible formatting, etc?

Yes, precisely. The **code we have to generate** has changed, since the line numbers are different. This isn't always true, but it is true for things that may panic (e.g., `+`).

**Comment by steveklabnik** [comment] 2019-01-09 20:11
Triage: i was going to try to reproduce this, but ran into https://github.com/rust-lang/rust/issues/57479

The file is still living in the same place, at least.

**Comment by cjgillot** [comment] 2021-11-07 10:09
Closing as intended behaviour: the generated code must include the span of the panic, which indeed changes.

**Closed by cjgillot** 2021-11-07 10:09 UTC
Labels: C-enhancement, A-incr-comp
