### ISSUE TITLE
"lint level defined here" note mostly useless

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#31004] opened 2016-01-18 19:34 UTC
E.g.

```
liblrsb/parser/lib.rs:7:9: 7:23 note: lint level defined here
liblrsb/parser/lib.rs:7 #![warn(unused_results)]
                                ^~~~~~~~~~~~~~
liblrsb/parser/lib.rs:336:9: 336:30 warning: unused result
liblrsb/parser/lib.rs:336         path.shrink_to_fit();
                                  ^~~~~~~~~~~~~~~~~~~~~
liblrsb/parser/lib.rs:7:9: 7:23 note: lint level defined here
liblrsb/parser/lib.rs:7 #![warn(unused_results)]
                                ^~~~~~~~~~~~~~
liblrsb/parser/lib.rs:373:17: 373:35 warning: unused result
liblrsb/parser/lib.rs:373                 self.lexer.next();
                                          ^~~~~~~~~~~~~~~~~~
liblrsb/parser/lib.rs:7:9: 7:23 note: lint level defined here
liblrsb/parser/lib.rs:7 #![warn(unused_results)]
                                ^~~~~~~~~~~~~~
liblrsb/parser/lib.rs:374:17: 374:35 warning: unused result
liblrsb/parser/lib.rs:374                 self.lexer.next();
                                          ^~~~~~~~~~~~~~~~~~
liblrsb/parser/lib.rs:7:9: 7:23 note: lint level defined here
liblrsb/parser/lib.rs:7 #![warn(unused_results)]
                                ^~~~~~~~~~~~~~
liblrsb/parser/lib.rs:384:17: 384:35 warning: unused result
liblrsb/parser/lib.rs:384                 self.lexer.next();
                                          ^~~~~~~~~~~~~~~~~~
liblrsb/parser/lib.rs:7:9: 7:23 note: lint level defined here
liblrsb/parser/lib.rs:7 #![warn(unused_results)]
                                ^~~~~~~~~~~~~~
liblrsb/parser/lib.rs:385:17: 385:35 warning: unused result
liblrsb/parser/lib.rs:385                 self.lexer.next();
                                          ^~~~~~~~~~~~~~~~~~
liblrsb/parser/lib.rs:7:9: 7:23 note: lint level defined here
liblrsb/parser/lib.rs:7 #![warn(unused_results)]
                                ^~~~~~~~~~~~~~
```

At least 5 of those 6 notes add nothing but noise to the output.

**Comment by nagisa** [comment] 2016-01-19 13:03
Duplicate of https://github.com/rust-lang/rust/issues/24690, I think.

**Closed by nagisa** 2016-01-19 13:03 UTC
Labels: A-diagnostics

**Comment by basantsd** [comment] 2022-01-22 18:37
#![allow(unused_results)]
