### ISSUE TITLE
compiler ICE after useful error message

### ISSUE THREAD

**Issue by cardoe** [rust-lang/rust#32857] opened 2016-04-09 18:27 UTC
So I think the error message made the situation clear what I had done wrong but to me it feels awkward that the compiler threw an ICE after the telling me the issue.

```
$ ~/work/rust/x86_64-unknown-linux-gnu/stage1/bin/rustc -o json-test json-test.rs
json-test.rs:5:1: 5:24 error: the crate `serialize` has been compiled with rustc 1.7.0-dev (c6e520edb 2016-04-08), which is incompatible with this version of rustc [E0514]
json-test.rs:5 extern crate serialize;
               ^~~~~~~~~~~~~~~~~~~~~~~
json-test.rs:5:1: 5:24 help: consider removing the compiled binaries and recompiling with your current version of rustc
ERROR:rbml::reader: failed to find block with tag 275
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', src/librbml/lib.rs:437
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by cardoe** [comment] 2016-04-09 18:31
Not sure if there's a generic way to make this happen but the way I made it happen is pretty corner case so its ok if this is closed with a "don't do that".

steps to reproduce:
1. built rust on a branch based off of 1.x.0
2. switch to a branch based off of 1.y.0
3. `make rustc-stage1`
4. use that compiler for something

**Comment by jonas-schievink** [comment] 2016-04-30 20:15
There might just be an `abort_if_errors` missing here

**Comment by arielb1** [comment] 2016-05-01 14:39
duplicate of #33015.

**Closed by arielb1** 2016-05-01 14:39 UTC
Labels: A-metadata, I-ICE
