### ISSUE TITLE
Regression in itertools

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#33587] opened 2016-05-12 13:44 UTC
```
141 brian@ip-10-234-25-118:~/dev/rustup.rs⟫ cargo build
   Compiling pipeline v0.5.0
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.7
   Compiling unicode-normalization v0.1.2
   Compiling utf8-ranges v0.1.3
   Compiling unicode-width v0.1.3
   Compiling regex-syntax v0.3.1
   Compiling rustup-dist v0.1.11 (file:///mnt/dev/rustup.rs/src/rustup-dist)
   Compiling strsim v0.4.1
   Compiling gcc v0.3.28
   Compiling itertools v0.4.13
   Compiling rustc-serialize v0.3.19
/home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218:1: 224:2 error: type mismatch resolving `<<J as std::iter::IntoIterator>::IntoIter as std::iter::Iterator>::Item == <I as std::iter::IntoIterator>::Item`:
 expected type parameter,
    found associated type [E0271]
/home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218 pub fn merge<I, J>(i: I, j: J) -> Merge<I::IntoIter, J::IntoIter>
                                                                                             ^
/home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218:1: 224:2 help: run `rustc --explain E0271` to see a detailed explanation
/home/brian/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.13/src/free.rs:218:1: 224:2 note: required by `adaptors::Merge`
```

**Comment by nikomatsakis** [comment] 2016-05-12 15:15
probably dup of https://github.com/rust-lang/rust/issues/33586

**Comment by bluss** [comment] 2016-05-12 19:54
Fwiw, itertools 0.4.14 has been released which has a workaround, so it compiles without any functional change.Workaround is to use the full `<I as IntoIterator>::IntoIter` syntax.

**Comment by bluss** [comment] 2016-05-12 20:01
Closing as duplicate of #33586. Itertools itself has released a workaround too.

**Closed by bluss** 2016-05-12 20:01 UTC
Labels: regression-from-stable-to-nightly
