### ISSUE TITLE
Macro in extern crate fails to resolve when imported with another macro

### ISSUE THREAD

**Issue by kylewlacy** [rust-lang/rust#33101] opened 2016-04-20 00:46 UTC
# What works

If I have a `hello!` macro in a module...

```rust
// src/hello.rs
macro_rules! hello {
    () => {
        println!("Hello, wrold!");
    }
}
```

I can use it like this:

```rust
// src/main.rs
#[macro_use] mod hello;

fn main() {
    hello!();
}

// $ cargo run
// Hello, wrold!
```

I can also, if I so choose, extract this into *another* macro that actually does the importing (a sort of "prelude macro"), then I can use the `hello!` macro as normal:

```rust
// src/main.rs
macro_rules! prelude {
    () => {
        #[macro_use] mod hello;
    }
}

prelude!();

fn main() {
    hello!();
}

// $ cargo run
// Hello, wrold!
```

(see [kylewlacy/rust-macro-include/macro-include-mod](https://github.com/kylewlacy/rust-macro-include/tree/master/macro-include-mod) for a complete cargo project)

# What doesn't work

Now, I want to work with an external library that exposes a macro, called `hola!`:

```rust
// lib/hola/src/lib.rs
#[macro_export]
macro_rules! hola {
    () => {
        println!("Hola, wrold!");
    }
}
```

I can, as normal, use it like this:

```rust
// src/main.rs
#[macro_use] extern crate hola;

fn main() {
    hola!();
}

// $ cargo run
// Hola, wrold!
```

But, if I try to use another "prelude macro" to import *this* macro, I get an error:

```rust
// src/main.rs
macro_rules! prelude {
    () => {
        #[macro_use] extern crate hola;
    }
}

prelude!();

fn main() {
    hola!();
}

// $ cargo run
//    Compiling macro-include-crate v0.1.0 (...)
// src/main.rs:10:5: 10:9 error: macro undefined: 'hola!'
// src/main.rs:10     hola!();
//                    ^~~~
// error: aborting due to previous error
// error: Could not compile `macro-include-crate`.
```

(see [kylewlacy/rust-macro-include/macro-include-crate](https://github.com/kylewlacy/rust-macro-include/tree/master/macro-include-crate) for a complete cargo project)

------

So, is the above behavior expected, or is it a bug?

# Rust version

Tested on the stable (`rustc 1.8.0 (db2939409 2016-04-11)`), beta (`rustc 1.9.0-beta.1 (37a2869af 2016-04-12)`), and nightly (`rustc 1.10.0-nightly (ed7c56796 2016-04-17)`) compiler channels on OS X (10.11.4)

**Comment by kylewlacy** [comment] 2016-04-20 05:57
I also noticed that this issue happens when using `include!`:

```rust
// lib/bonjour/src/lib.rs
#[macro_export]
macro_rules! bonjour {
    () => {
        println!("Bonjour, wrold!");
    }
}
```

```rust
// src/prelude.rs
#[macro_use] extern crate bonjour;
```

```rust
// src/main.rs
include!("prelude.rs");

fn main() {
    bonjour!();
}

// $ cargo run
//    Compiling macro-include-prelude v0.1.0 (...)
// src/main.rs:4:5: 4:12 error: macro undefined: 'bonjour!'
// src/main.rs:4     bonjour!();
//                   ^~~~~~~
// error: aborting due to previous error
// error: Could not compile `macro-include-prelude`.
```

(see [kylewlacy/rust-macro-include/macro-include-prelude](https://github.com/kylewlacy/rust-macro-include/tree/master/macro-include-prelude))

**Comment by durka** [comment] 2016-04-20 15:53
In both cases public items from the crate are accessible, so it seems like it is dropping the `#[macro_use]` attribute.

**Comment by durka** [comment] 2016-04-20 15:56
duplicate of #28071

**Closed** 2016-04-20 16:36 UTC
Labels: A-macros
