### ISSUE TITLE
Nightly regression: `panic::set_hook()` signature incompatible if used with core::panic::PanicInfo

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#126766] opened 2024-06-20 22:38 UTC
### Code

I tried this code:

```rust
#![no_std]

// Yes, this is `no_std` + `extern crate std`, which happens a lot in
// crates that are `cfg(not(something), no_std)`

extern crate std;
extern crate alloc;
use alloc::boxed::Box;

fn main() {
    
    std::panic::set_hook(Box::new(panic_handler));
}

fn panic_handler(info: &core::panic::PanicInfo) {

}
```

[playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=3fc8c1e9d147250c243c177be29521b9)

I expected to see this happen: It compiles just fine

Instead, this happened: I get the following error:

```
error[E0631]: type mismatch in function arguments
  --> src/main.rs:9:26
   |
9  |     std::panic::set_hook(Box::new(panic_handler));
   |                          ^^^^^^^^^^^^^^^^^^^^^^^ expected due to this
...
12 | fn panic_handler(info: &core::panic::PanicInfo) {
   | ----------------------------------------------- found signature defined here
   |
   = note: expected function signature `for<'a, 'b> fn(&'a PanicHookInfo<'b>) -> _`
              found function signature `fn(&PanicInfo<'_>) -> _`
   = note: required for the cast from `Box<for<'a, 'b> fn(&'a PanicInfo<'b>) {panic_handler}>` to `Box<(dyn for<'a, 'b> Fn(&'a PanicHookInfo<'b>) + Send + Sync + 'static)>`
```

On nightly `PanicInfo` is a type alias for `PanicHookInfo`, however the alias only exists in the `std` crate. If you reference `PanicInfo` from `core`, that is now a different type that does not unify with `PanicHookInfo`.

It is relatively common in crates that support `no_std` to always use the lowest possible crate to reference for any reexported type, which is why our code was referencing `core::panic` even though this particular snippet of code needs `std` to work overall.

### Version it worked on

It most recently worked on: Rust 1.79, Rust 1.80-beta3

### Version with regression

`rustc --version --verbose`:
```
1.81.0-nightly (2024-06-19 d8a38b00024cd7156dea)
```

**Comment by asquared31415** [comment] 2024-06-21 14:12
It doesn't even need to be a `no_std` crate, simply using `use core::panic::PanicInfo;` and using that `PanicInfo` in the panic hook signature reproduces this error.

**Comment by bjorn3** [comment] 2024-06-21 14:46
https://github.com/rust-lang/rust/pull/115974 was merged under the assumption that std crates are unlikely to use `core::panic::PanicInfo` instead of `std::panic::PanicInfo` when referring to the type of the panic hook argument.

**Comment by Manishearth** [comment] 2024-06-21 14:46
Nice catch!

**Comment by asquared31415** [comment] 2024-06-21 15:04
> #115974 was merged under the assumption that std crates are unlikely to use `core::panic::PanicInfo` instead of `std::panic::PanicInfo` when referring to the type of the panic hook argument. It is expected that `core::panic::PanicInfo` for the panic hook doesn't work after that PR.

rust-analyzer has a setting for "prefer `core` over `std` for imports" that myself and i assume many others use, in all projects (also at this point I use `core` when possible by habit).  If it's assumed that users should be using the `std` version when `std` is available, at the *least* the error should provide a fix that changes the import, and rust-analyzer should know how to exclude some imports from its setting.

**Comment by apiraino** [comment] 2024-10-15 09:01
Closing since regression is mentioned in the release notes

**Closed by apiraino** 2024-10-15 09:01 UTC
Labels: A-diagnostics, T-libs-api, relnotes, regression-from-stable-to-stable, C-bug
