### ISSUE TITLE
regression: no rules expected the token `.`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#121611] opened 2024-02-25 21:06 UTC
https://crater-reports.s3.amazonaws.com/beta-1.77-3/beta-2024-02-18/reg/gen-nested-iter-yield-0.1.3/log.txt

```
[INFO] [stdout] error: no rules expected the token `.`
[INFO] [stdout]   --> tests/tests.rs:45:13
[INFO] [stdout]    |
[INFO] [stdout] 45 |             nested_iter_yield!(input_vector.iter(), 2, .clone())
[INFO] [stdout]    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
[INFO] [stdout]    |
[INFO] [stdout]    = note: while trying to match end of macro
[INFO] [stdout]    = note: this error originates in the macro `nested_iter_yield` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error: no rules expected the token `.`
[INFO] [stdout]   --> tests/tests.rs:67:13
[INFO] [stdout]    |
[INFO] [stdout] 67 |             nested_iter_yield!(input_vector.iter(), 2, .clone(), ::)
[INFO] [stdout]    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
[INFO] [stdout]    |
[INFO] [stdout]    = note: while trying to match end of macro
[INFO] [stdout]    = note: this error originates in the macro `nested_iter_yield` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by compiler-errors** [comment] 2024-02-26 01:19
More regressions from #120227

cc @nnethercote @petrochenkov 

---

searched nightlies: from nightly-2024-01-01 to nightly-2024-02-26
regressed nightly: nightly-2024-02-01
searched commit range: https://github.com/rust-lang/rust/compare/cb4d9a1902b3ea17e93872dafb76d24aa6295c47...11f32b73e0dc9287e305b5b9980d24aecdc8c17f
regressed commit: https://github.com/rust-lang/rust/commit/80deabd0987201e1b8d060400f50e03309a0105e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.7</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2024-01-01 -- test
```
</details>

**Comment by nnethercote** [comment] 2024-02-26 03:42
gen-nested-iter-yield-0.1.3 was one of the expected cases failure cases for #120227, due to relying on the exact whitespace used by pretty-printing: see [this comment](https://github.com/rust-lang/rust/pull/120227#issuecomment-1911163178) summarizing the crater run. And [this comment](https://github.com/rust-lang/rust/pull/120227#issuecomment-1919127567) mentions relnotes.

**Comment by apiraino** [comment] 2024-02-26 11:59
WG-prioritization removing prioritization label ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23121611.20regression.3A.20no.20rules.20expected.20the.20token.20.60.2E.60)).

If I understand, this breakage was abundantly discussed and approved, so there is no further actionable for us (besides the `relnotes`). Thanks @nnethercote for the thoroughness in #120227 

@rustbot label -I-prioritize

**Comment by apiraino** [comment] 2024-10-15 08:59
Closing since regression is mentioned in the release notes

**Closed by apiraino** 2024-10-15 08:59 UTC
Labels: A-parser, T-compiler, regression-from-stable-to-stable
