### ISSUE TITLE
Doctests aren't running for documentation of macros

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38219] opened 2016-12-07 12:14 UTC
I noticed that in a branch on Diesel where I had forgotten to update a few doctests, our builds were passing on nightly but failing on stable and beta. It appears that the doctests on macros are not being run on the current nightly. https://travis-ci.org/diesel-rs/diesel/builds/181708974

**Comment by alexcrichton** [comment] 2016-12-08 01:44
cc @jseyfried, does this ring a bell for you?

**Comment by jseyfried** [comment] 2016-12-08 11:10
This was caused by #37890, fixed in #38239.

**Comment by alexcrichton** [comment] 2016-12-09 01:44
Thanks for the quick fix @jseyfried!

**Closed** 2016-12-10 22:03 UTC
Labels: regression-from-stable-to-nightly, T-tools
