### ISSUE TITLE
Build issue: recent MacOS builds don't run because of missing dylib

### ISSUE THREAD

**Issue by remram44** [rust-lang/rust#37889] opened 2016-11-20 00:04 UTC
I'm using rustup.rs.

While the stable toolchain runs fine, the nightlies give me this:
```
$ rustup run nightly cargo
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/remirampin/.multirust/toolchains/nightly-x86_64-apple-darwin/bin/cargo
  Reason: image not found
```
I do not have a `/usr/local/opt` or a local install of openssl anywhere. I don't have homebrew installed.

This looks like the build machine is linking against the wrong openssl?

**Comment by sfackler** [comment] 2016-11-20 02:13
Duplicate of https://github.com/rust-lang/cargo/issues/3303

**Closed by sfackler** 2016-11-20 02:13 UTC
