### ISSUE TITLE
False never used function warning

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#101699] opened 2022-09-11 18:49 UTC
I'm not sure if this is expected. In this code I've used a const test function, and I call it inside a const assert:

```rust
macro_rules! const_assert {
    ($x:expr $(,)?) => {
        const _: () = assert!($x);
    };
}

fn main() {
    const fn test(n: u32) -> bool {
        n > 0
    }
    const N: u32 = 100;
    const_assert!(test(N));
    dbg!(N);
}
```

This code works correctly, but rusts gives a "warning: function `test` is never used".

**Comment by est31** [comment] 2022-09-11 19:48
Smaller reproduction:
```Rust
    const fn test() {}
    const _: () = test();
```
It works if you replace the `_` with `FOO` and print the `FOO` somewhere else. I guess what's missing is the special treatment of `_`.

**Comment by ehuss** [comment] 2022-09-11 22:52
I think this is nearly a duplicate of #96952. See also #101532.

I think it's very possible that when using `const _`, the compiler assumes the value is never "used", and thus evaluating the const expression has no effect. However, that is no longer true since #89508 where panic support was added. (Just an idle speculation.)

**Comment by est31** [comment] 2022-09-11 23:02
Oh yeah it's a duplicate. That's why it was so familiar to me. I guess this issue should be closed as dupe.

**Closed** 2022-09-12 06:33 UTC
Labels: C-bug
