### ISSUE TITLE
ICE

### ISSUE THREAD

**Issue by smallB007** [rust-lang/rust#93958] opened 2022-02-13 07:57 UTC
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```
![ICE](https://user-images.githubusercontent.com/3456691/153744324-271850c5-b674-4f50-8a17-0fdeeab752b7.png)

</p>
</details>

**Comment by fanninpm** [comment] 2022-02-15 03:46
- Are you able to provide some code that reproduces this problem? It's completely understandable if the code causing this ICE is proprietary/closed-source/NDA, but please understand that it's often easier for the rust-lang devs to isolate and reproduce this ICE if they have enough clues to find out how it happened. Often, an [MCVE](https://dba.stackexchange.com/help/minimal-reproducible-example) will be sufficient, but don't worry about minimizing something that feels daunting to minimize.
- Does the problem persist after running `cargo clean`? (This is the telltale sign of an _incremental_ compilation error. You might want to save the state of your `target/` directory before doing this.)
- Are you able to reproduce this using the latest nightly compiler? (`rustup toolchain install nightly` and/or `rustup update`)

**Comment by smallB007** [comment] 2022-02-16 16:18
Hi and thank you for the reply.
>> Does the problem persist after running cargo clean
No, after running cargo clean project compiles

If you interested in the source code, it is just my home project that I'm using to learn rust, I'm OK with sending it to you.

**Comment by Nilstrieb** [comment] 2022-03-03 07:13
This is a known issue with incremental compilation and should be fixed on nightly.

**Comment by Enselic** [comment] 2024-03-01 04:26
Triage: Since there were no protests, let's close.

**Closed by Enselic** 2024-03-01 04:26 UTC
Labels: I-ICE, T-compiler, C-bug
