### ISSUE TITLE
rustc panicked

### ISSUE THREAD

**Issue by L117** [rust-lang/rust#40607] opened 2017-03-17 16:58 UTC
rustc panicked while building string_cache v0.2.29

I tried to build (in debug mode) empty binary project created with
`cargo new --bin`
and containing follwing in `Cargo.toml`:
```
[package]
name = "rustc_bug"
version = "0.1.0"

[dependencies]
string_cache="0.2.29"
```

## Meta

`rustc --version --verbose`:
```
rustc 1.17.0-nightly (0aeb9c129 2017-03-15)
binary: rustc
commit-hash: 0aeb9c12979e6da753701a798d04105b6b1a8c28
commit-date: 2017-03-15
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9
```

Backtrace:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
stack backtrace:
   0:     0x7f33a523c5d3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::hf9ed9ccfd9f14c2b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f33a5236dd4 - std::sys_common::backtrace::_print::hd8a1b72dcf3955ef
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x7f33a524a27c - std::panicking::default_hook::{{closure}}::h5ff605bba7612658
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x7f33a5249de4 - std::panicking::default_hook::h9bc4f6dfee57d6bd
                               at /checkout/src/libstd/panicking.rs:365
   4:     0x7f33a524a6cb - std::panicking::rust_panic_with_hook::hdc01585dc2bf7122
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x7f33a524a5a4 - std::panicking::begin_panic::hf84f4975d9f9b642
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x7f33a524a4d9 - std::panicking::begin_panic_fmt::hcc3f360b2ba80419
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x7f33a524a467 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x7f33a5286e7d - core::panicking::panic_fmt::h795d9a9608ddc2bb
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x7f33a5286db4 - core::panicking::panic::hcab3e0dfa81beee9
                               at /checkout/src/libcore/panicking.rs:49
  10:     0x7f33a42180ab - rustc_metadata::cstore::CStore::get_crate_data::h879080fff9bbb3d5
  11:     0x7f33a4205927 - rustc_metadata::cstore_impl::<impl rustc::middle::cstore::CrateStore for rustc_metadata::cstore::CStore>::def_key::h722fd01bb31cc402
  12:     0x7f33a46d5161 - rustc_resolve::build_reduced_graph::<impl rustc_resolve::Resolver<'a>>::macro_def_scope::h64af5bb83cf290b0
  13:     0x7f33a46f9ee9 - rustc_resolve::Resolver::resolve_path::h63fab10e0cfbb6fc
  14:     0x7f33a46f9060 - rustc_resolve::Resolver::resolve_qpath::h63cc31d10ed7302d
  15:     0x7f33a46f3b18 - rustc_resolve::Resolver::smart_resolve_path_fragment::hf4768a8cd6c64027
  16:     0x7f33a46f381f - rustc_resolve::Resolver::smart_resolve_path::h54fc78b3bdf498cb
  17:     0x7f33a46fcf76 - rustc_resolve::Resolver::resolve_expr::h31f6347449d9bccf
  18:     0x7f33a46f25dc - rustc_resolve::Resolver::resolve_block::h5402b786b8a2e291
  19:     0x7f33a46e3332 - <rustc_resolve::Resolver<'a> as syntax::visit::Visitor<'tcx>>::visit_fn::h10590b36e88a5d43
  20:     0x7f33a46b00f4 - syntax::visit::walk_impl_item::h9e905cd253120eb8
  21:     0x7f33a46ecf1e - rustc_resolve::Resolver::with_type_parameter_rib::h50196cd17155f1d0
  22:     0x7f33a46ee4f6 - rustc_resolve::Resolver::with_current_self_type::hdebf41bd682adcc3
  23:     0x7f33a46ef000 - rustc_resolve::Resolver::with_self_rib::hae368e64b0482109
  24:     0x7f33a46ee915 - rustc_resolve::Resolver::with_optional_trait_ref::h11086ed007ecfff2
  25:     0x7f33a46ef294 - rustc_resolve::Resolver::with_self_rib::hede7e0c7d2332115
  26:     0x7f33a46eb098 - rustc_resolve::Resolver::resolve_item::h35deef5172cd354b
  27:     0x7f33a46b2c9f - syntax::visit::walk_item::h3d4ddccfd6fae893
  28:     0x7f33a46ebdf4 - rustc_resolve::Resolver::resolve_item::h35deef5172cd354b
  29:     0x7f33a46e5adf - rustc_resolve::Resolver::resolve_crate::h4a3ecd764c3f806f
  30:     0x7f33a55b73f5 - rustc_driver::driver::phase_2_configure_and_expand::he6c4ccfa0c800248
  31:     0x7f33a55ae1d5 - rustc_driver::driver::compile_input::hc1b147f99450510e
  32:     0x7f33a55f68bb - rustc_driver::run_compiler::h3b24af557ae194d3
  33:     0x7f33a551cfab - std::panicking::try::do_call::hc1fa4f624bc07e15
  34:     0x7f33a525372a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  35:     0x7f33a5538982 - <F as alloc::boxed::FnBox<A>>::call_box::h2ece23b89111995d
  36:     0x7f33a5249054 - std::sys::imp::thread::Thread::new::thread_start::h75b208405df6dcf1
                               at /checkout/src/liballoc/boxed.rs:650
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  37:     0x7f339cf53423 - start_thread
  38:     0x7f33a4f049be - __clone
  39:                0x0 - <unknown>
```

My system is Debian Stretch / Experimental
```
$ uname -a
Linux cloud 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
```

**Comment by arielb1** [comment] 2017-04-07 10:36
duplicate of #40469.

**Closed by arielb1** 2017-04-07 10:36 UTC
