### ISSUE TITLE
Confusing error message with conservative impl trait

### ISSUE THREAD

**Issue by iopq** [rust-lang/rust#39722] opened 2017-02-10 18:30 UTC
```
#![feature(conservative_impl_trait)]

fn main() {
    let mut x = &mut 1i32;
    let closure = return_closure(x);
    closure();
}


fn return_closure(x: &mut i32) -> impl Fn() {
    move || println!("{}", x)
}
```

this gives the error message

```
error[E0564]: only named lifetimes are allowed in `impl Trait`, but `` was found in the type `[closure@<anon>:11:5: 11:30 x:&mut i32]`
  --> <anon>:10:35
   |
10 | fn return_closure(x: &mut i32) -> impl Fn() {
   |                                   ^^^^^^^^^
```

but that's wrong, if we amend the code to

```
#![feature(conservative_impl_trait)]

fn main() {
    let mut x = &mut 1i32;
    let closure = return_closure(x);
    closure();
}


fn return_closure<'a>(x: &'a mut i32) -> impl Fn() {
    move || println!("{}", x)
}
```

it compiles and runs just fine, so the previous error message is incorrect

**Comment by gnzlbg** [comment] 2017-08-30 13:32
Duplicate of #38615

**Comment by cramertj** [comment] 2018-01-05 20:56
This is fixed.

**Closed** 2019-12-05 23:59 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
