### ISSUE TITLE
rustdoc not recognizing stability attributes on foreign functions

### ISSUE THREAD

**Issue by jcmoyer** [rust-lang/rust#18971] opened 2014-11-15 06:13 UTC
`rustdoc` is not recognizing stability attributes on functions inside of `extern` blocks. Minimal example:

```rust
// lib.rs
#![unstable]
#![crate_type="lib"]
extern {
  pub fn f();
}
pub fn g() {
}

```

```bash
$ rustdoc lib.rs
```

If you open the generated documentation you'll find that the crate and `g` are marked as unstable, but `f` is unmarked. If you check the stability index, 66% of the crate is considered unstable, and 33% is unmarked. Even if you explicitly add a stability attribute to `f` it remains unmarked in the generated documentation.

~~[Here's another example of it occurring in `core::intrinsics`.](http://doc.rust-lang.org/core/intrinsics/index.html)~~ **2015-03-15:** seems to be fixed here but I can still reproduce it locally

**Comment by alexcrichton** [comment] 2015-04-07 02:08
I believe there was a recent round of improvements to the handling of extern functions by @tomjakubowski, so I'm going to close this as "I think this is done"

**Closed by alexcrichton** 2015-04-07 02:08 UTC
Labels: A-rustdoc

**Comment by tomjakubowski** [comment] 2015-04-07 02:46
The OP can probably still reproduce because of the `staged_api` feature, which is now required for the current stability attributes to do anything.

**Comment by jcmoyer** [comment] 2015-04-07 02:55
Confirming that I can still reproduce the problem.

**Comment by tomjakubowski** [comment] 2015-04-07 02:57
Can you reproduce if you add this:

```rust
#![feature(staged_api)]
#![staged_api]
```

To the head of the file? I cannot with: rustdoc 1.0.0-nightly (d8be84eb4 2015-03-29) (built 2015-03-30)

**Comment by alexcrichton** [comment] 2015-04-07 02:59
To be clear, this code:

```rust
#![feature(staged_api)]
#![staged_api]

#![unstable(feature = "foo")]

extern {
    pub fn foo();
}
```

Generates this documentation:

![https://i.imgur.com/ZvowA8m.png](https://i.imgur.com/ZvowA8m.png)

**Comment by jcmoyer** [comment] 2015-04-07 03:54
Thanks, those were the attributes I needed. It works as expected now.
