### ISSUE TITLE
Confusing output for signature mismatch in Fn trait with GAT lifetime parameter

### ISSUE THREAD

**Issue by skyzh** [rust-lang/rust#93342] opened 2022-01-26 16:57 UTC
I tried this code:

```rust
#![feature(generic_associated_types)]

use std::marker::PhantomData;

pub trait Scalar: 'static {
    type RefType<'a>: ScalarRef<'a>;
}

pub trait ScalarRef<'a>: 'a {}

impl Scalar for i32 {
    type RefType<'a> = i32;
}

impl Scalar for String {
    type RefType<'a> = &'a str;
}

impl Scalar for bool {
    type RefType<'a> = i32;
}

impl<'a> ScalarRef<'a> for bool {}

impl<'a> ScalarRef<'a> for i32 {}

impl<'a> ScalarRef<'a> for &'a str {}

fn str_contains(a: &str, b: &str) -> bool {
    a.contains(b)
}

pub struct BinaryExpression<A: Scalar, B: Scalar, O: Scalar, F>
where
    F: Fn(A::RefType<'_>, B::RefType<'_>) -> O,
{
    f: F,
    _phantom: PhantomData<(A, B, O)>,
}

impl<A: Scalar, B: Scalar, O: Scalar, F> BinaryExpression<A, B, O, F>
where
    F: Fn(A::RefType<'_>, B::RefType<'_>) -> O,
{
    pub fn new(f: F) -> Self {
        Self {
            f,
            _phantom: PhantomData,
        }
    }
}

fn fail_case() {
    //     error[E0631]: type mismatch in function arguments
    //   --> src/main.rs:58:54
    //    |
    // 33 | fn str_contains(a: &str, b: &str) -> bool {
    //    | ----------------------------------------- found signature of `for<'r, 's> fn(&'r str, &'s str) -> _`
    // ...
    // 58 |     BinaryExpression::<String, String, bool, _>::new(str_contains);
    //    |     ------------------------------------------------ ^^^^^^^^^^^^ expected signature of `for<'r, 's> fn(<String as Scalar>::RefType<'r>, <String as Scalar>::RefType<'s>) -> _`
    //    |     |
    //    |     required by a bound introduced by this call
    //    |
    // note: required by a bound in `BinaryExpression::<A, B, O, F>::new`
    //   --> src/main.rs:47:8
    //    |
    // 47 |     F: Fn(A::RefType<'_>, B::RefType<'_>) -> O,
    //    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `BinaryExpression::<A, B, O, F>::new`
    // 48 | {
    // 49 |     pub fn new(f: F) -> Self {
    //    |            --- required by a bound in this

    BinaryExpression::<String, String, bool, _>::new(str_contains);
}

fn success_case() {
    BinaryExpression::<String, String, bool, _> {
        f: str_contains,
        _phantom: PhantomData,
    };
}

fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen:

Both functions compile.

Instead, this happened:

If I directly call `new`,

```
expected signature of `for<'r, 's> fn(<String as Scalar>::RefType<'r>, <String as Scalar>::RefType<'s>) -> _`
```

... but if I manually construct the struct, it succeeds.

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (8cdb3cd94 2022-01-25)
binary: rustc
commit-hash: 8cdb3cd94efece1e17cbd8f6edb1dc1a482779a0
commit-date: 2022-01-25
host: aarch64-apple-darwin
release: 1.60.0-nightly
LLVM version: 13.0.0
```

Thanks for investigating!

**Comment by skyzh** [comment] 2022-01-26 17:00
... and the interesting thing is that, once I used a trait to "prove" `str_contains` is actually `Fn(A::RefType<'_>, B::RefType<'_>) -> O`, it compiles 🤣🤣🤣

(which is exactly the technique I used in https://github.com/skyzh/type-exercise-in-rust when I was implementing expression vectorization in safe, nightly Rust without any macro)

```rust
#![feature(generic_associated_types)]

use std::marker::PhantomData;

pub trait Scalar: 'static {
    type RefType<'a>: ScalarRef<'a>;
}

pub trait ScalarRef<'a>: 'a {}

impl Scalar for i32 {
    type RefType<'a> = i32;
}

impl Scalar for String {
    type RefType<'a> = &'a str;
}

impl Scalar for bool {
    type RefType<'a> = i32;
}

impl<'a> ScalarRef<'a> for bool {}

impl<'a> ScalarRef<'a> for i32 {}

impl<'a> ScalarRef<'a> for &'a str {}

fn str_contains(a: &str, b: &str) -> bool {
    a.contains(b)
}

pub struct BinaryExpression<A: Scalar, B: Scalar, O: Scalar, F>
where
    F: BinaryExprFunc<A, B, O>,
{
    f: F,
    _phantom: PhantomData<(A, B, O)>,
}

impl<A: Scalar, B: Scalar, O: Scalar, F> BinaryExpression<A, B, O, F>
where
    F: BinaryExprFunc<A, B, O>,
{
    pub fn new(f: F) -> Self {
        Self {
            f,
            _phantom: PhantomData,
        }
    }
}

pub trait BinaryExprFunc<A: Scalar, B: Scalar, O: Scalar> {
    fn eval(&self, a: A::RefType<'_>, b: B::RefType<'_>) -> O;
}

impl<A: Scalar, B: Scalar, O: Scalar, F> BinaryExprFunc<A, B, O> for F
where
    F: Fn(A::RefType<'_>, B::RefType<'_>) -> O,
{
    fn eval(&self, a: A::RefType<'_>, b: B::RefType<'_>) -> O {
        self(a, b)
    }
}

fn success_case_1() {
    BinaryExpression::<String, String, bool, _>::new(str_contains);
}

fn success_case_2() {
    BinaryExpression::<String, String, bool, _> {
        f: str_contains,
        _phantom: PhantomData,
    };
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by compiler-errors** [comment] 2022-01-27 03:46
I'd like to take a look at this.

@rustbot claim

**Comment by jackh726** [comment] 2022-03-08 03:20
I think this was fixed in #90887, but needs to be confirmed.

**Comment by skyzh** [comment] 2022-03-08 03:21
Thanks a lot! I'll have a try on the latest nightly.

**Comment by compiler-errors** [comment] 2022-03-08 03:41
@skyzh you probably need to try on tomorrow's nightly (or the day after), since #90887 just landed very recently.

**Comment by compiler-errors** [comment] 2022-03-08 04:00
@jackh726, I manually checked this compiles on master.

**Closed** 2022-03-08 05:20 UTC
Labels: C-bug, F-generic_associated_types
