### ISSUE TITLE
#[derive(Clone)] places unnecessary Clone constraint on type parameter

### ISSUE THREAD

**Issue by iitalics** [rust-lang/rust#54514] opened 2018-09-23 21:41 UTC
Consider we make a parameterize type which references an associated type but not the parameter itself.

```rust
trait Actor {
  type Msg;
  fn send(&self, m: Self::Msg);
}

#[derive(Clone)]
struct TwoMsgs<A: Actor>(A::Msg, A::Msg);

fn thing<A>(ac: &A, tm: &TwoMsgs<A>)
where A: Actor, A::Msg: Clone {
    let tm2: TwoMsgs<A> = tm.clone();
    ac.send(tm2.0);
    ac.send(tm2.1);
}
```

The line `tm.clone()` dispatches incorrectly, because `TwoMsgs<A>: Clone` is not satisfied. It turns out that the way to satisfy it is to add the trait bound `A: Clone`.

```rust
fn thing<A>(ac: &A, tm: &TwoMsgs<A>)
where A: Actor, A: Clone, A::Msg: Clone {
    let tm2: TwoMsgs<A> = tm.clone();
    ac.send(tm2.0);
    ac.send(tm2.1);
}
```

However, this does not make sense -- we do not wish to clone the actor, so requiring `A: Clone` is unnecessarily restrictive! There is no reason that the bound `A: Clone` should be required, since `TwoMsgs<A>` does not contain any `A` in its fields.

**Expected behavior**: The derived `Clone` instance should look something like:
```rust
impl<A> Clone for TwoMsgs<A>
where A: Actor, A::Msg: Clone {
    fn clone(&self) -> Self {
        TwoMsgs(self.0.clone(), self.1.clone())
    }
}
``` 

That is, it does not require `A: Clone`.

**Comment by jonas-schievink** [comment] 2018-09-23 21:46
Duplicate of https://github.com/rust-lang/rust/issues/26925, I believe

**Comment by iitalics** [comment] 2018-09-23 21:48
Ah. I'll close this.

**Closed** 2018-09-23 21:48 UTC
