### ISSUE TITLE
Nightly segfaults in release mode on armv7-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by a-rodin** [rust-lang/rust#64355] opened 2019-09-10 16:26 UTC
Building any binary in release mode on `armv7-unknown-linux-gnueabihf` with `nightly-2019-09-09`  results in segmentation fault:

```sh
$ cargo new foo && cd foo && cargo +nightly build --release
     Created binary (application) `foo` package
   Compiling foo v0.1.0 (/tmp/foo)
error: Could not compile `foo`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name foo src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=c0380bb0b35d3d4d -C extra-filename=-c0380bb0b35d3d4d --out-dir /tmp/foo/target/release/deps -L dependency=/tmp/foo/target/release/deps` (signal: 11, SIGSEGV: invalid memory reference)
```

Rust compiler version:
```
rustc 1.39.0-nightly (0b36e9dea 2019-09-09)
```

The operating system is Raspbian Buster with fresh updates running on Raspberry Pi 4.

It looks like the issue is with the optimizer because building in release mode but with `opt-level=0` succeeds:

```sh
$ RUSTFLAGS=-Copt-level=0 cargo +nightly build --release
   Compiling foo v0.1.0 (/tmp/foo)
    Finished release [optimized] target(s) in 4.43s
```

**Comment by memoryruins** [comment] 2019-09-10 19:15
Potentially a duplicate of #62896 
Does the `RUSTFLAGS='-Ccodegen-units=1'` workaround mentioned in that issue help?

**Comment by a-rodin** [comment] 2019-09-10 19:26
@memoryruins `RUSTFLAGS='-Ccodegen-units=1'` helps, the compilation succeeds using it.

**Comment by sanxiyn** [comment] 2019-10-03 13:01
Closing as a duplicate.

**Closed by sanxiyn** 2019-10-03 13:01 UTC
Labels: C-bug, I-crash, O-ARM, T-compiler
