### ISSUE TITLE
Hang on GATE code

### ISSUE THREAD

**Issue by wxie7** [rust-lang/rust#132672] opened 2024-11-06 02:19 UTC
### Code

```rs
#![feature(generic_associated_types_extended)]
#![feature(feature(type_alias_impl_trait))]
trait HealthCheck {
    async fn check<const N: usize>();
}
fn do_health_check_par()
where
    HealthCheck: HealthCheck,
{
}
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [x] Current Nightly

### Rust Version

$ rustc -Vv
rustc 1.84.0-nightly (bc5cf994d 2024-11-05)
binary: rustc
commit-hash: bc5cf994db9fb46712cefd89f78ad7fc51f184a2
commit-date: 2024-11-05
host: x86_64-unknown-linux-gnu
release: 1.84.0-nightly
LLVM version: 19.1.3

### Anything else?

When using `--edition 2021`, the compiler does not hang.

**Comment by fmease** [comment] 2024-11-06 02:44
I can reproduce the hang without any of the provided compiler flags.

**Comment by fmease** [comment] 2024-11-06 02:47
Smaller:

```rs
#![feature(generic_associated_types_extended)]
#![crate_type = "lib"]

trait Trait { fn meth<T>() -> impl Iterator; }
fn func() where dyn Trait: Trait {}
```

**Comment by fmease** [comment] 2024-11-06 07:11
Likely same root cause but I-hang ≠ I-ICE, so I think we want to keep it.

It's true that applying the following change makes it I-ICE with the same message as #131538:

```diff
- trait Trait { fn meth<T>() -> impl Iterator; }
+ trait Trait { fn meth<const N: usize>() -> impl Sized; }
```

Also note that the MCVE I provided in https://github.com/rust-lang/rust/issues/132672#issuecomment-2458621652 doesn't contain any *const parameters* at all and therefore can't possibly lead to any *const placeholders* (`!idx_univ`) getting generated during type inference. So the symptoms are truly disparate.

**Comment by fmease** [comment] 2024-11-06 12:52
Ah, you noted the hang thingy in https://github.com/rust-lang/rust/issues/131538#issuecomment-2407054924. Okay, let's close this one then.

Duplicate of #131538.

**Closed by fmease** 2024-11-06 12:52 UTC
Labels: T-compiler, C-bug, I-hang, F-generic_associated_types_extended, requires-incomplete-features
