### ISSUE TITLE
1.53 build fails

### ISSUE THREAD

**Issue by voncloft** [rust-lang/rust#86980] opened 2021-07-08 16:12 UTC
I tried the instructions both on this README.md file on this repo and the instructions here: https://www.linuxfromscratch.org/blfs/view/svn/general/rust.html

substituting 1.52 with 1.53

```rust
<code>
```

I expected to see this happen: to compile

Instead, this happened: it failed

### Meta

`rustc --version --verbose`: 
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-07-08 16:20
duplicate of https://github.com/rust-lang/rust/issues/86981

**Closed by jonas-schievink** 2021-07-08 16:20 UTC
Labels: C-bug
