### ISSUE TITLE
fn's can be used as const generics

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#84238] opened 2021-04-16 09:33 UTC
The following code fails to compile, because using function pointers as const generics is forbidden:
```Rust
#![feature(const_generics)]

struct A<const F: fn()>;
```

However, if the function pointer is inside an array, it suddenly compiles:
```Rust
#![feature(const_generics)]

struct B<const F: [fn(); 1]>;
```

Is this intentional, or should it also be forbidden?

**Comment by RalfJung** [comment] 2021-04-18 08:17
This is definitely intentional. `fn()` have an unstable notion of equality, in particular if they point to instances of generic functions: two entirely independent functions might have "equal" function pointers if they happen to compile to the same assembly code, and two identical instances of the same generic function in different crates (or even just different codegen units) might compare "inequal".

**Comment by RalfJung** [comment] 2021-04-18 08:18
The second is a bug, this should not work in arrays -- I assume this would be fixed by properly moving to valtrees.
Cc @rust-lang/wg-const-eval

**Comment by lcnr** [comment] 2022-06-28 16:34
```rust
#![feature(adt_const_params)]

struct B<const F: [fn(); 1]>;
```
still compiles, the issue is that function pointers are currently considered to be structural match. I intend to work on structural equality in the near (not that near) future, going to assign this to myself.

@rustbot claim

**Comment by DutchGhost** [comment] 2022-07-02 19:09
Same issue with raw pointers (both `*const _` and `*mut _`):

```Rust
#![feature(adt_const_params)]

struct Works<const F: [*mut (); 1]>;

struct DoesNotWork<const F: *mut ()>;
```

**Comment by lcnr** [comment] 2024-01-09 21:20
this happens as const generics now relies on `ConsParamTy` instead of simply using structural match.

**Closed** 2024-07-02 22:25 UTC
Labels: E-needs-test, T-compiler, C-bug, A-const-generics, F-adt_const_params
