### ISSUE TITLE
async fn should not require temporary variable to be `Send` if it won't be accessed across await

### ISSUE THREAD

**Issue by BusyJay** [rust-lang/rust#82796] opened 2021-03-05 10:33 UTC
I tried this code:

```rust
use std::future::*;
use std::pin::Pin;
use std::task::*;

struct SendFuture {
    ptr: *mut (),
}
unsafe impl Send for SendFuture {}
impl Future for SendFuture {
    type Output = ();
    fn poll(self: Pin<&mut Self>, ctx: &mut Context) -> Poll<()> {
        Poll::Ready(())
    }
}

struct UnSendPromise {
     ptr: *mut (),
}

fn consume(_s: UnSendPromise) {
    unimplemented!()
}

fn pair() -> (SendFuture, UnSendPromise) {
    unimplemented!()
}

async fn temporary_variable_unsend() {
    let (f, p) = pair();
    consume(p);
    f.await
}

fn test_temporary_variable_unsend() {
    let c = async move {
        temporary_variable_unsend().await
    };
    std::thread::spawn(move || {
        drop(c)
    });
}
```

I expected to see this happen:

It compiles.

The async fn `temporary_variable_unsend` consumes the temporary variable `p` directly. Hence it doesn't matter if its type `UnSendPromise` is not `Send` as it will never be accessed after await.

Instead, this happened:

It fails to compile.
```
error: future cannot be sent between threads safely
   --> src/lib.rs:38:5
    |
38  |     std::thread::spawn(move || {
    |     ^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
    |
    = help: within `[closure@src/lib.rs:38:24: 40:6]`, the trait `Send` is not implemented for `*mut ()`
note: future is not `Send` as this value is used across an await
   --> src/lib.rs:31:5
    |
29  |     let (f, p) = pair();
    |             - has type `UnSendPromise` which is not `Send`
30  |     consume(p);
31  |     f.await
    |     ^^^^^^^ await occurs here, with `p` maybe used later
32  | }
    | - `p` is later dropped here
```

After changing `temporary_variable_unsend` to following code, it compiles.
```
fn temporary_variable_unsend() -> impl Future<Output=()> {
    let (f, p) = pair();
    consume(p);
    f
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: aarch64-apple-darwin
release: 1.50.0
```

**Comment by jonas-schievink** [comment] 2021-03-05 11:38
duplicate of https://github.com/rust-lang/rust/issues/57478

**Closed by jonas-schievink** 2021-03-05 11:38 UTC
Labels: C-bug
