### ISSUE TITLE
Built-in derives don't work when specifying associated types with a fully qualified path.

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#133232] opened 2024-11-20 06:16 UTC
Note: This issue was initially discovered by @lcnr, and mentioned at https://github.com/rust-lang/reference/issues/540#issuecomment-2236155515. However, I think that this is a bug in the derive macro, and not in the documentation. Therefore, I am filing this issue.

I tried this code:

```rust
trait Trait {
    type Assoc;
}

#[derive(Clone)]
struct Foo<T: Trait> {
    value: T::Assoc, // ok, gets a `T::Assoc: Clone` bound
}

#[derive(Clone)]
struct Bar<T: Trait> {
    value: <T as Trait>::Assoc, // error
}

#[derive(Clone)]
struct Baz<T: Trait> {
    value: <T>::Assoc, // error
}
```

I expected the code to compile. Instead, the `Foo` struct compiles fine, but the `Bar` and `Baz` structs don't compile, producing the following error:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `<T as Trait>::Assoc: Clone` is not satisfied
  --> src/lib.rs:12:5
   |
10 | #[derive(Clone)]
   |          ----- in this derive macro expansion
11 | struct Bar<T: Trait> {
12 |     value: <T as Trait>::Assoc, // error
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `<T as Trait>::Assoc`
   |
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `<T as Trait>::Assoc: Clone` is not satisfied
  --> src/lib.rs:17:5
   |
15 | #[derive(Clone)]
   |          ----- in this derive macro expansion
16 | struct Baz<T: Trait> {
17 |     value: <T>::Assoc, // error
   |     ^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `<T as Trait>::Assoc`
   |
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (lib) due to 2 previous errors
```

The same issue also happens when deriving `Debug`, `Default`, `PartialEq`, or `Hash`.

### Meta
Reproduces on the playground on stable rust version 1.82.0, and on nightly rust version `1.84.0-nightly (2024-11-19 ee612c45f00391aff71e)`

**Comment by fmease** [comment] 2024-11-20 06:42
Duplicate of https://github.com/rust-lang/rust/issues/50730

**Closed** 2024-11-20 06:51 UTC
Labels: C-bug
