### ISSUE TITLE
Multiple crates can't find pkg_config in 1.17

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40183] opened 2017-03-01 19:07 UTC
due to: https://github.com/rust-lang/cargo/pull/3361

- rusqlite-0.7.3 -- can't find crate for pkg_config
- schemamama_rusqlite-0.5.0 -- can't find crate for pkg_config
- sphinxad-0.1.1 -- can't find crate for pkg_config
- sphinxad-sys-0.1.2 -- can't find crate for pkg_config

cc @jgallagher @TrionProg

**Comment by brson** [comment] 2017-03-01 19:08
Found in https://internals.rust-lang.org/t/cargobomb-report-stable-v-nightly-2017-02-17/4829/14

**Comment by jgallagher** [comment] 2017-03-01 19:18
This has been fixed in later releases of rusqlite (specifically >= 0.9.0). Is proper crates.io hygiene to go back and publish point releases that fix this for older versions? If so, how far back should I go?

**Comment by nikomatsakis** [comment] 2017-03-02 19:51
@jgallagher what was the problem exactly? 

And, I would say it is very kind of you to upgrade your point releases, definitely! The question of how far back to go is a good one. In this case, the problem is that some dependency likes 0.7.3, which is something you can't easily *control*...

**Comment by jgallagher** [comment] 2017-03-02 20:07
@nikomatsakis No problem exactly - there was just a leftover `build.rs` at the project root that got committed by accident a long time ago. I don't think it was ever referenced by the project or Cargo.toml, but the changes to Cargo linked above made it problematic.

If https://crates.io/crates/rusqlite/reverse_dependencies is the right picture, looks like I should update back to 0.6.x?

**Comment by jgallagher** [comment] 2017-03-02 20:32
@brson I pushed rusqlite 0.6.1, 0.7.4, and 0.8.1 which should fix this. 0.9 and up was already fixed.

**Comment by TrionProg** [comment] 2017-03-02 22:57
Hello, and what I should to do to avoid it? I am author of sphinxad.

**Comment by brson** [comment] 2017-03-09 17:26
Seems like this is expected breakage and we just need to help people adapt.

**Comment by steveklabnik** [comment] 2017-03-09 17:26
I'll look at sending PRs to these crates.

**Comment by steveklabnik** [comment] 2017-03-09 18:44
So for these four crates:

- rusqlite-0.7.3: looks like @jgallagher has it handled. 
- schemamama_rusqlite-0.5.0 this failed (because of `rusqlite0.6`](https://brson.github.io/cargobomb-reports/stable-v-nightly-2017-02-17/res/nightly/reg/schemamama_rusqlite-0.5.0/log.txt), and now pulls in 0.6.1, as it had a `^` dependency, so it's good to go.
- sphinxad-0.1.1 @TrionProg's comment above seems strange; @alexcrichton, maybe you know what's going on? It seems odd that `0.1.2` works in one context and not another.
- sphinxad-sys-0.1.2 see above

**Comment by alexcrichton** [comment] 2017-03-09 22:57
@TrionProg sorry for the slow response! It looks like you've [already taken care of this](https://github.com/TrionProg/sphinxad-sys/commit/50f5d087bb3c7e101a01f58782426b38b3216f32) and it looks like you've also published, so I don't think there's anything left to be done!

@TrionProg if you're still having trouble locally, could you gist the full error you're seeing and I'll help you debug?

**Closed by alexcrichton** 2017-03-09 22:57 UTC
Labels: regression-from-stable-to-nightly
