### ISSUE TITLE
Configure does not detect valgrind properly

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#24025] opened 2015-04-03 20:37 UTC
I do not yet have valgrind installed after a fresh Arch install and simple `./configure` followed by `make check-stage1` will either fail to compile jemalloc or 

```
run rpass [x86_64-unknown-linux-gnu]: x86_64-unknown-linux-gnu/stage1/bin/compiletest
thread '<main>' panicked at 'Can't find Valgrind to run Valgrind tests', /home/nagisa/Documents/rust/rust/src/compiletest/compiletest.rs:50
/home/nagisa/Documents/rust/rust/mk/tests.mk:727: recipe for target 'tmp/check-stage1-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rpass.ok' failed
make: *** [tmp/check-stage1-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rpass.ok] Error 101
```

depending on your luck.

**Comment by brson** [comment] 2015-04-15 20:15
Dupe of https://github.com/rust-lang/rust/issues/18588

**Closed by brson** 2015-04-15 20:15 UTC
Labels: A-build
