### ISSUE TITLE
`test/run-make-fulldeps/pgo-branch-weights` fails occasionally on CI

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#67746] opened 2019-12-31 04:12 UTC
You can see this test fails occasionally in some pull requests: https://github.com/rust-lang/rust/pulls?utf8=%E2%9C%93&q=is%3Apr+pgo-branch-weights

I don't think this is due to PR changes. Could we modify, or just remove this for now?

**Comment by Centril** [comment] 2019-12-31 04:23
cc @Zoxc @michaelwoerister

**Comment by michaelwoerister** [comment] 2020-01-02 09:12
If the test fails, it indicates that there's a bug to be fixed. I'll try to reproduce.

**Comment by pnkfelix** [comment] 2020-01-02 13:59
triage: P-high

**Comment by michaelwoerister** [comment] 2020-01-13 14:15
Has this issue occurred since the potential fix in #67829 landed?

**Comment by JohnTitor** [comment] 2020-01-13 14:17
I've not seen the failure recently.

**Comment by michaelwoerister** [comment] 2020-01-13 14:27
I think that's in order, yes. We can re-open if the issue re-appears.

**Closed by michaelwoerister** 2020-01-13 14:27 UTC
Labels: A-spurious, A-testsuite, C-bug, P-high, T-compiler
