### ISSUE TITLE
Build artifact privacy

### ISSUE THREAD

**Issue by leo-lb** [rust-lang/rust#65378] opened 2019-10-13 14:21 UTC
Hello,

I am looking into a compile time option (`-Zsource-info-strip` ?) that would strip away from any built artifact information (especially panic debug strings) about the source code and the machine that was used to build.

Which would mean making `core:module_path!()`, `core::stringify!()`, `core::file!()`, `core::line!()` and `core::column!()` return an empty string.

I could not find where these rustc builtin macros are implemented.

Thanks.

**Comment by bluss** [comment] 2019-10-13 14:30
They are here:

https://github.com/rust-lang/rust/blob/29b6e0f0a1d1a37f8dc729484a64e59bf0b9a0a3/src/libsyntax_ext/source_util.rs#L19-L51

**Comment by the8472** [comment] 2019-10-13 15:57
Is the reproducibility tag appropriate? Path stripping seems overkill for that instead of relativizing them to the project root.

**Comment by jonas-schievink** [comment] 2019-10-13 16:14
@the8472 Yeah, and I thought we had something like that already but couldn't find it first. It's `--remap-path-prefix`.

This issue seems to be for hiding info about the compiled *source code* though, which is something different than hiding info about the build environment.

`stringify!` probably doesn't need to be changed in any case, it would probably break a lot of crates and doesn't interact with any filesystem paths.

**Comment by leo-lb** [comment] 2019-10-13 20:30
@jonas-schievink In the official documentation for `stringify!` it explicitly warns about it's output changing in the future, are you certain it would cause such damage?

**Comment by jonas-schievink** [comment] 2019-10-13 20:46
@leo-lb Hmm, not sure I understand the problem you're trying to solve with this... The documentation only warns about the output not being stable between Rust versions, I'm not sure how that would cause issues here.

> My main concern is some crates using it to expose internal source code information that's not intended to leak into built artifacts.

That's a fair point, but I don't know why this causes an issue. All it does is turning some Rust tokens into a string, so you'd have to invoke a macro with something to leak in the first place. `type_name` can also leak similar info.

**Comment by leo-lb** [comment] 2019-10-13 21:15
> That's a fair point, but I don't know why this causes an issue. All it does is turning some Rust tokens into a string, so you'd have to invoke a macro with something to leak in the first place. `type_name` can also leak similar info.

Yes, some libraries might call `stringify!` on symbols in order to embed unsolicited debug messages inside binaries?

**Comment by Mark-Simulacrum** [comment] 2019-10-13 21:18
I don't think there's an automated way of preventing leakage of that sort -- after all, stringify! could be mostly implemented as a proc macro these days, which are just arbitrary code. Not to mention that you can always embed arbitrary strings into the final binary. I suspect that stating your specific desires, instead of the more vague "strip source code information" would be helpful. Generally speaking remap-path-prefix is probably good enough, I'd imagine?

**Comment by leo-lb** [comment] 2019-10-13 21:24
> I don't think there's an automated way of preventing leakage of that sort -- after all, stringify! could be mostly implemented as a proc macro these days, which are just arbitrary code. Not to mention that you can always embed arbitrary strings into the final binary. I suspect that stating your specific desires, instead of the more vague "strip source code information" would be helpful. Generally speaking remap-path-prefix is probably good enough, I'd imagine?

Being able to produce binaries that do not hint back to the source code, e.g. to not help a reverse engineering effort.

**Comment by Mark-Simulacrum** [comment] 2019-10-13 21:32
I don't think that sort of obfuscation would really be in the domain of rustc itself; are there examples of similar options in clang/gcc?

**Comment by leo-lb** [comment] 2019-10-13 21:37
> I don't think that sort of obfuscation would really be in the domain of rustc itself; are there examples of similar options in clang/gcc?

MSVC compiler and linker does not leave such strings inside binaries in release mode. It's not obfuscation, rather, I consider that release mode should not leave debugging information inside binaries but with Rust it does so I was looking towards modifying that behavior!

**Comment by Mark-Simulacrum** [comment] 2019-10-13 21:46
It's confusing to me that you make that assertion -- can you point to examples of such strings being left in Rust-compiled binaries? To my knowledge, the MSVC compiler does not do anything special here. It might be that C++ code is less prone to including source strings from e.g. `assert!` or similar, due to instead depending on gdb or similar debuggers for tracking down sources of exceptions (somewhat akin to panic, in some sense). But we'd need an RFC I suspect to stop emitting this information into assert! or similar facilities.

The Rust macros you mention in your original comment though could probably be changed by a compiler flag, though I would personally resist such a change, since it is unlikely to prevent all sources of leakage and is likely to have false positives. I expect that (all? most?) C++ compilers have similar unstable extensions to get line number, column number, etc. and that `#define` can be used to "stringify" source code as well in a similar fashion...

**Comment by leo-lb** [comment] 2019-10-13 22:47
> It's confusing to me that you make that assertion -- can you point to examples of such strings being left in Rust-compiled binaries? To my knowledge, the MSVC compiler does not do anything special here. It might be that C++ code is less prone to including source strings from e.g. `assert!` or similar, due to instead depending on gdb or similar debuggers for tracking down sources of exceptions (somewhat akin to panic, in some sense). But we'd need an RFC I suspect to stop emitting this information into assert! or similar facilities.
> 
> The Rust macros you mention in your original comment though could probably be changed by a compiler flag, though I would personally resist such a change, since it is unlikely to prevent all sources of leakage and is likely to have false positives. I expect that (all? most?) C++ compilers have similar unstable extensions to get line number, column number, etc. and that `#define` can be used to "stringify" source code as well in a similar fashion...

The issue is caused by the std rather than rustc here. I am aware other compilers do offer similar functionality it's just that the std impls don't leak information from the project source code, the Rust std does leak information.

**Comment by Mark-Simulacrum** [comment] 2019-10-13 23:52
Our standard library doesn't leak downstream source code (unless you mean the expression passed to e.g. assert, but that seems expected for any such facility), to my knowledge. A concrete example (i.e., a playground example) would be really helpful, I think.

**Comment by leo-lb** [comment] 2019-10-14 00:55
@Mark-Simulacrum Result::unwrap() which is very common causes stuff to be included, in any compiled Rust binary today you will find dozens of hints to source code and a path to the build user's home directory

**Comment by Mark-Simulacrum** [comment] 2019-10-14 01:20
Unwrap doesn't include anything directly from the calling crate? Can you show how you're determining it includes this information?

**Comment by leo-lb** [comment] 2019-10-14 08:45
> Unwrap doesn't include anything directly from the calling crate? Can you show how you're determining it includes this information?

https://asciinema.org/a/wUf988JJcogJheM1XgGjbOqZF

but this can be made not working by stripping the binary even though it's built in release mode.

Another example, installing `cargo-edit` (`cargo install` uses release mode by default):

https://asciinema.org/a/t5KXAehBumwN7YYMJymQTNw5S

**Comment by Mark-Simulacrum** [comment] 2019-10-14 12:29
The backtrace information is obtained at runtime, and function names are currently not mangled away; I believe it may be possible to remove the symbol table as well, but I'm uncertain exactly of how to do so. Maybe `strip` can help there. Regardless, if that's the "leakage" you are referring to, then it is not something rustc itself will help with. A similar backtrace can be found in a exception-throwing or segfaulting C++ program when run under gdb (IIRC, C++ standard library does not have built-in backtraces, though I could be wrong).

**Comment by Mark-Simulacrum** [comment] 2019-10-18 13:30
I'm going to close this as I believe this is not a bug / won't fix.

**Closed by Mark-Simulacrum** 2019-10-18 13:30 UTC
Labels: C-feature-request, T-compiler

**Comment by leo-lb** [comment] 2019-11-06 06:51
@Mark-Simulacrum It's a feature request rather

**Comment by Mark-Simulacrum** [comment] 2019-11-06 13:15
People concerned with binary size are likely to want to work to reduce them by e.g. stripping them and such, but the exact tradeoffs are highly dependent on the application, so we likely can't do it for you. If you're interested in pursuing this further, I would recommend going through the RFC process, which would be the right route for a bigger feature like this one.
