### ISSUE TITLE
Slice equality is slow

### ISSUE THREAD

**Issue by nham** [rust-lang/rust#16913] opened 2014-09-01 01:55 UTC
If I run the following code with `rustc -O --test src/slice_equality_slow.rs && ./slice_equality_slow --bench`:

```
extern crate test;

fn eq<'a, T: PartialEq>(a: &'a [T], b: &'a [T]) -> bool {
    if a.len() != b.len() {
        return false;
    }

    for i in range(0, a.len()) {
        if a[i] != b[i] {
            return false;
        }
    }

    true
}

#[cfg(test)]
mod bench {
    use test::Bencher;

    #[bench]
    fn builtin_eq(b: &mut Bencher) {
        let mut u = vec!();
        let mut v = vec!();
        for i in range(0u, 1_000_000) {
            u.push(i);
            v.push(i);
        }

        let x = u.as_slice();
        let y = v.as_slice();

        b.iter(|| {
            assert!(x == y);
        })
    }

    #[bench]
    fn custom_eq(b: &mut Bencher) {
        let mut u = vec!();
        let mut v = vec!();
        for i in range(0u, 1_000_000) {
            u.push(i);
            v.push(i);
        }

        let x = u.as_slice();
        let y = v.as_slice();

        b.iter(|| {
            assert!(super::eq(x, y));
        })
    }
}

fn main() {}
```

Then I get:

```
running 2 tests
test bench::builtin_eq ... bench:  12513842 ns/iter (+/- 64900)
test bench::custom_eq  ... bench:   7303767 ns/iter (+/- 304090)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```

I ran into this because I was able to speed up the naive string matching algorithm in `core::str` by replacing the slice equality with a `for` loop and comparing each component manually.

**Comment by ranma42** [comment] 2015-09-16 08:15
Is this fixed by #26884 ?

**Comment by bluss** [comment] 2015-09-16 11:56
It seems to be fixed in the sense of the original reporter?

But, slice equality still doesn't vectorize properly or compare well to glibc's memcmp (for byte slices), so improvements remain.

**Comment by bluss** [comment] 2015-09-16 11:57
@dotdash Not sure why it doesn't vectorize in nightly:

https://play.rust-lang.org/?gist=38c5ef4ccf66898cc261&version=nightly

```rust
pub fn compare(a: &[u8], b: &[u8]) -> bool {
    a == b
}
```

**Comment by arthurprs** [comment] 2016-01-23 18:20
As of today this is still true.

**Comment by ranma42** [comment] 2016-01-23 18:36
Related bug in LLVM: https://llvm.org/bugs/show_bug.cgi?id=16332

Basically the problem is that the LLVM vectoriser does not know how to optimise loops with multiple exits or (which is the same) with termination guards that are not simple constraints on the index variable.

**Comment by nagisa** [comment] 2017-03-14 21:09
Seems to be fixed now with some specialisation (the slow comparison, not LLVM bug)

```
▪./memcmp --bench

running 2 tests
test bench::builtin_eq ... bench:     393,159 ns/iter (+/- 28,862)
test bench::custom_eq  ... bench:     581,997 ns/iter (+/- 42,720)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```

**Comment by aturon** [comment] 2017-03-14 21:23
Thanks @nagisa, closing!

**Closed by aturon** 2017-03-14 21:23 UTC
Labels: A-codegen, A-LLVM, I-slow
