### ISSUE TITLE
rustc on Mingw64(MSYS2) fails to build

### ISSUE THREAD

**Issue by Teapot4195** [rust-lang/rust#108628] opened 2023-03-01 22:51 UTC
When trying to run any `./x.py` subcommand, bootstrap panics trying to canonicalize the path returned by the git command.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', config.rs:910:74```

**Comment by ChrisDenton** [comment] 2023-03-02 17:10
Is this using a git installed via the msys2 package manager? I believe that has been patched to use msys2 style paths which the Rust build system does not support.

**Comment by Teapot4195** [comment] 2023-03-02 20:15
It is installed

**Comment by Teapot4195** [comment] 2023-03-03 22:10
well, i think that we should change the README so that we do not instruct people to install the git provided by msys2

as of right now it instructs users to run `pacman -S git` which is very misleading

**Comment by workingjubilee** [comment] 2023-03-04 01:11
Agreed. What would be the correct advisory regarding installing git, here?

**Comment by Teapot4195** [comment] 2023-03-04 02:06
The instructions should tell users to not install the msys version of git, instead users should install the regular version using chocolatey or otherwise and to add the path to msys.

**Comment by mati865** [comment] 2023-03-04 10:11
Duplicate of https://github.com/rust-lang/rust/issues/105696

**Comment by workingjubilee** [comment] 2023-03-04 23:44
Ah! Closing then.

**Closed by workingjubilee** 2023-03-04 23:44 UTC
Labels: O-windows-gnu, A-docs
