### ISSUE TITLE
Types cannot refer to persistent data from generic elements

### ISSUE THREAD

**Issue by denisandroid** [rust-lang/rust#64077] opened 2019-09-01 21:15 UTC
This is a pseudo-code of a part of my library, it has not been compiled, because types, for some reason not clear to me, cannot refer to persistent data from generalized elements.

```
rustc 1.39.0-nightly (4295eea90 2019-08-30)
```

```rust

trait CheckErr {
	const U: usize = 0;
	
	type T;
}

impl<A, B> CheckErr for (A, B) where A: CheckErr, B: CheckErr {
	const U: usize = A::U + B::U;
	
	type T = [u8; <A as CheckErr>::U];
}

/*
error[E0599]: no associated item named `U` found for type `A` in the current scope
  --> examples/test_err.rs:11:19
   |
11 |     type T = [u8; A::U];
   |                      ^ associated item not found in `A`
   |
   = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `U`, perhaps you need to restrict type parameter `A` with it:
   |
8  | impl<A: CheckErr, B> CheckErr for (A, B) where A: CheckErr, B: CheckErr {
   |      ^^^^
*/

/*
Or

Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `A: CheckErr` is not satisfied
  --> src/main.rs:11:16
   |
11 |     type T = [u8; <A as CheckErr>::U];
   |                   ^^^^^^^^^^^^^^^^^^ the trait `CheckErr` is not implemented for `A`
   |
   = help: consider adding a `where A: CheckErr` bound

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

*/

fn main() {

}
```

Play: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e53731a572040d54df9094a012130cb8

**Comment by jonas-schievink** [comment] 2019-09-01 21:18
Duplicate of https://github.com/rust-lang/rust/issues/43408

**Closed by jonas-schievink** 2019-09-01 21:18 UTC
