### ISSUE TITLE
Purely-diverging functions cannot return `impl Trait`.

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#44923] opened 2017-09-29 15:23 UTC
Originally reported in https://github.com/rust-lang/rust/issues/34511#issuecomment-322340401, separated out to make it easier to track.  #43869 and #44731 are examples caused by this issue.

If a function is purely diverging, any part of the return type cannot contain `impl Trait`, e.g.

```rust
fn do_it_later_but_cannot() -> impl Iterator<Item=u8> { //~ ERROR E0227
    unimplemented!()
}
```

this fails because `!` does not implement `Iterator`. But I think this should be allowed even without the explicit impl, since `!` can be coerced to any concrete type.

**Comment by malbarbo** [comment] 2017-09-29 17:15
@kennytm Do you know where the issue of general diverging functions cannot return `impl Trait` are being tracked?

**Comment by kennytm** [comment] 2017-09-29 17:23
@malbarbo there’s no problem returning “general diverging functions”, if you mean something like this:

```rust
fn foo() -> impl Bar {
    if bar() {
        Baz::new()
    } else {
        panic!(“diverge”)
    }
}
```

**Comment by malbarbo** [comment] 2017-09-29 18:01
@kennytm Yes, I mean that. But I asked because I remembered vaguely some limitations that I had encountered in the past. Looking at my old code, the limitation was not that... sorry. The limitation is this:

```rust
fn g<T>(t: T) -> Result<impl Iterator<Item=u32>, T> {
    Err(t)
}
```

fails to compile with error:

```
fn g<T>(t: T) -> Result<impl Iterator<Item=u32>, T>
                        ^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for `_`
```

If we change the type to `impl Clone`, the error changes to:

```
fn g<T>(t: T) -> Result<impl Clone, T>
                        ^^^^^^^^^^
note: the return type of a function must have a statically known size
```

It this a know issue? Is this expected?

**Comment by Aaron1011** [comment] 2017-10-09 03:17
I'd like to work on this.

**Comment by rkruppe** [comment] 2018-04-01 17:21
this and #36375 are duplicates of each other

**Comment by ishitatsuyuki** [comment] 2018-04-09 11:38
I think we can close this as duplicate of #36375?

**Closed by ishitatsuyuki** 2018-04-09 11:38 UTC
Labels: A-impl-trait, C-bug, T-lang
