### ISSUE TITLE
[1.30 beta] Test suite of the jemalloc-ctl crate is failing

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54478] opened 2018-09-22 14:17 UTC
This is not a spurious failure (the test output is consistent between runs), but we need to investigate why this is happening.

* [jemalloc-ctl](https://crates.io/crates/jemalloc-ctl) `0.2.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/jemalloc-ctl-0.2.0/log.txt)) cc @sfackler

**Comment by sfackler** [comment] 2018-09-23 17:55
Those errors seem to imply that global allocator registration may have broken?

**Comment by sfackler** [comment] 2018-09-23 18:00
It seems like it may specifically be a problem with rustdoc tests - a normal library test passes as expected.

**Comment by pnkfelix** [comment] 2018-10-08 12:04
Bisection over nightly builds indicates that bug was injected between nightly-2018-08-06-x86_64-unknown-linux-gnu (73c78734b) and nightly-2018-08-14-x86_64-unknown-linux-gnu (d5a448b3f).

Here are the bors commits from that range:

% git log --author bors 73c78734b..d5a448b3f --format=oneline
d5a448b3f47b22c9cb010198bdcc49d4392b090b Auto merge of #53270 - petrochenkov:macuse-regr, r=alexcrichton
a78ae85e5942b5d41c7bddf8243ede7f350d4886 Auto merge of #53161 - michaelwoerister:cstrings, r=wesleywiser
147ca2d2a6662993cee56db8c971f4f0ac73783a Auto merge of #53238 - nrc:update, r=kennytm
ab93561b5fa54954159480ddc10bbb69f015e539 Auto merge of #53051 - varkor:trait-method-pattern-arguments-error, r=petrochenkov
5a0d2961ce88f7db90b13771d1e8fc3b50ded7b1 Auto merge of #53297 - GuillaumeGomez:rollup, r=GuillaumeGomez
0aa8d0320266b5579428312095fe49af05ada972 Auto merge of #53177 - nikomatsakis:nll-redundant-borrows-and-escaping-values, r=pnkfelix
a77dfcc79fe3e7e1a10ae4dccfd4b2e5e0e49195 Auto merge of #53131 - davidtwco:issue-52663-thread-local-static, r=nikomatsakis
f6d43ed84207c7e58f363f46e5a438ff40f2b311 Auto merge of #53124 - davidtwco:issue-52742, r=nikomatsakis
db1acaac7f8c84d8fb46211f5e96f678c28628a8 Auto merge of #53073 - Mark-Simulacrum:data-structures, r=pnkfelix
fb65d7563c93509c343a98e5cccf8e5ab4506924 Auto merge of #52788 - LukasKalbertodt:improve-index-mut-error, r=estebank
8958ed672298148841b3b8d6371ce301e1cbbac1 Auto merge of #53216 - kennytm:rollup, r=kennytm
b73535f1e9c46a698527fab51b1cc9fad3f53412 Auto merge of #53031 - michaelwoerister:cross-lto, r=alexcrichton
fbb6275f4fd6cf774e1789fabfacae7248c45021 Auto merge of #53108 - RalfJung:mutex, r=alexcrichton
76b69a604ee0d70be1edfa2828c769dc1b148d13 Auto merge of #53100 - VPashkov:issue-52456-improper_ctypes, r=eddyb
80caa7f9f46097d5442d525aea29a435d5daa328 Auto merge of #53186 - mikhail-m1:master, r=nikomatsakis
62e4e08f4c00b8ae7a26d6aa792657f0fd846cec Auto merge of #53163 - oli-obk:const_prop_ice, r=nikomatsakis
376b60da8b65d7c4392f0a5e2b45c42e84bd01ce Auto merge of #53192 - oli-obk:clippyup, r=kennytm
63fe441db8a441bc68c754c33a04f57f0f8a8b77 Auto merge of #53088 - matthewjasper:closure-region-spans, r=nikomatsakis
ebe8df41d70d8763e0a15aefe078b035d3519214 Auto merge of #52872 - faern:use-modern-alignment-libc, r=TimNN
ffb09dfb3a9b252e26cd4f6570e9ff1b8a742edc Auto merge of #53053 - petrochenkov:custattr, r=alexcrichton
52c785bfc24e43c668c9022cc1e79edcd6dcfd7c Auto merge of #53141 - nrc:update, r=nrc
26d7b64237c6daa66064c8583b7aecf534c2a9ae Auto merge of #52993 - alexcrichton:fix-some-vis, r=michaelwoerister
3f4f18f098183bf60820e4304433c4c4d9cceaaa Auto merge of #52397 - estebank:println-comma, r=oli-obk
e90dc6f80d76c94a5b1b13d464d1de7e18a05d05 Auto merge of #52911 - Mark-Simulacrum:visibility-hirid, r=oli-obk
ccb550fb455eac46098b352875ba387eb982919d Auto merge of #53109 - nikomatsakis:nll-escaping-into-return-revert, r=nikomatsakis
39e95165323f76042dfab65772a8411dd85fe088 Auto merge of #51990 - oli-obk:unstable_union, r=nikomatsakis
18925dee25ce649562d203e72068e3a57b60b153 Auto merge of #53150 - kennytm:rollup, r=kennytm
9e472c2acea2b7714985390abb6b7fe420a4f346 Auto merge of #52450 - PramodBisht:issue/52413, r=estebank
11a902431b8e66da8486b3b9a2d8527746c6ab1a Auto merge of #51007 - AstralSorcerer:master, r=nagisa
f9b9b6e078aa81c0faa064bf861e88001684765c Auto merge of #53134 - alexcrichton:tweak-travis, r=Mark-Simulacrum
45a9d410f934247256812eda55ca66dd6999b3de Auto merge of #53016 - scottmcm:impl-header-lifetime-elision, r=nikomatsakis
cf84056149baf649f0c297b02afdde7db2187f46 Auto merge of #53115 - davidtwco:issue-52739, r=nikomatsakis
b2397437530eecef72a1524a7e0a4b42034fa360 Auto merge of #52644 - varkor:lib-feature-gate-2, r=withoutboats
4b8089daf8046d7999310d44e5c68ccff4ab255a Auto merge of #52990 - Aaron1011:fix/rustdoc-auto-trait-static, r=eddyb
78ec12df020453836c3b8990c0a8dd859b774e84 Auto merge of #53045 - pnkfelix:issue-53026-migrate-never-looser-than-ast-borrowck, r=estebank
7c98d2e63f732682b057c8c453b08f9e12b262e6 Auto merge of #52332 - zackmdavis:dead_code_lint_should_say_2_electric_boogaloo, r=pnkfelix
aa1e6db70900cf5d11a843bc4234de0548677aba Auto merge of #53002 - QuietMisdreavus:brother-may-i-have-some-loops, r=pnkfelix
e9fa9f5a6a7dede07b71987b893065f290b7acf7 Auto merge of #52997 - llogiq:tiny-list-opt, r=varkor

**Comment by pnkfelix** [comment] 2018-10-09 13:49
Okay I bisected this and identified the bug as being injected by #52993

**Comment by pnkfelix** [comment] 2018-10-09 14:05
Adding @alexcrichton to the assignee list in case they have some special insight into how best to address it. (But, as I noted on #52993, I am hoping we can get away with just undoing one small part of that PR, rather than backing out the whole thing, which seems like it might cause more trouble than it would resolve)

**Comment by pnkfelix** [comment] 2018-10-09 14:07
(also, tagging with both T-compiler and T-libs for now, though either team is free to untag the other if they want to take responsibility for resolving this.)

**Comment by alexcrichton** [comment] 2018-10-09 16:20
Thanks for the cc @pnkfelix! The issue here can be reduced to the following:

```rust
use std::alloc::*;

#[global_allocator]
static ALLOC: A = A;

static mut HIT: bool = false;

struct A;

unsafe impl GlobalAlloc for A {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        HIT = true;
        System.alloc(layout)
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        System.dealloc(ptr, layout);
    }
}

fn main() {
    assert!(unsafe { HIT });
}
```

compiled and run as...

```
$ rustc +stable -C prefer-dynamic x.rs && rustup run stable ./x
$ rustc +beta -C prefer-dynamic x.rs && rustup run beta ./x
thread 'main' panicked at 'assertion failed: unsafe { HIT }', x.rs:21:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

So specifically the bug here comes with the `-C prefer-dynamic` flag which, by default, rustdoc passes when compiling tests (which I'm surprised has lasted this long!). This is actually a bug that we accepted this code before! There are two active allocators here, one in the dynamic standard library and also one in the test that we're compiling. I... thought that `rustc` would reject this but apparently not!

The test actually has always failed on Windows (where the symbols don't trump one another). The regression here is Linux (and probably OSX?) specific. I think the "real fix" here is to not compile tests dynamically but compile them the same way as basically 99% of the compiles in Rust, statically.

**Comment by alexcrichton** [comment] 2018-10-09 16:36
Er sorry, I misspoke! Turns out I saw the regression on Linux and not on Windows because during process startup we allocate memory but don't allocate memory on Windows (wow!). If you amend the program to do `Box::new(3);` just before the assert then it fails on Windows as well.

Digging more into this it's still, however, a bug that the compiler ever accepted this code. For example consider:

```rust
use std::alloc::*;
use std::process::Command;
use std::env;

#[global_allocator]
static ALLOC: A = A;

static mut HITS: usize = 0;

struct A;

unsafe impl GlobalAlloc for A {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        HITS += 1;
        System.alloc(layout)
    }
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        System.dealloc(ptr, layout);
    }
}

fn main() {
    unsafe {
        let start = HITS;
        Box::new(2); // our own crate makes an allocation
        assert_eq!(HITS, start + 1);
        drop(env::var("X")); // force libstd itself to make an allocation
        assert!(HITS > start + 1);
    }
}
```

This test will pass with and without `-C prefer-dynamic` on stable Rust on Linux, but it fails on Windows with `-C prefer-dynamic`. 

What's happening here is that on stable Rust the executable, with `-C prefer-dynamic`, contains an *exported* `__rust_alloc` symbol. The dynamic standard library, however, also has a `__rust_alloc` symbol. We strive in rustc to make this never happen, we don't want these sort of symbol conflicts due to their platform-specific behavior. As seen here on Linux the executable effectively shadows the standard library, meaning there's actually two jemalloc allocators here (one in the executable and one in the standard library) and it just magically avoids the standard library's jemalloc allocator.

On Windows, however, symbols can't shadow one another so you've actually got *two* allocators here. The executable has its own allocator as does the standard library, which can very quickly lead to segfaults as memory is passed between them (if they're not both wired up to `System` like I have above).

All in all **tl;dr;** the compiler should have rejected this test previously due to rustdoc compiling tests dynamically. We should enact two changes from this discovery:

* The compiler should be fixed to actually reject this situation where there's two allocators linked into one program.
* We should update rustdoc to compile tests statically, not dynamically.

The first one is... "just sort of somewhere in the compiler add a check" and the second one is [right here](https://github.com/rust-lang/rust/blob/e1643a8968753226dab7ab3c9fee826f097550f2/src/librustdoc/test.rs#L223).

**Comment by pnkfelix** [comment] 2018-10-09 20:51
@alexcrichton hmm...

I'm curious whether either of the changes you describe should be targetted toward the beta channel.

I suspect the change to the compiler to detect two allocators linked into one program is not a high priority item for beta.

The change to rustdoc ... *seems* like it should go into the beta (in order to address regressions like the one flagged here on the jemalloc-ctl crate) ... but I worry that its such a *severe* change that it is more risky to put into beta than to just let the regressions happen to jemalloc-ctl and other crates doing similar things in their rustdoc....

I suppose the best thing would be to do a crater run dedicated to just the rustdoc change and see what comes of that.

**Comment by pnkfelix** [comment] 2018-10-09 20:56
Also, talk about an ancient bit of code:

https://github.com/rust-lang/rust/blob/6c9c045064bd74a00d9d98add6cb66a4bf2ad76e/src/librustdoc/test.rs#L99-L106

**Comment by pietroalbini** [comment] 2018-10-09 20:59
> I suppose the best thing would be to do a crater run dedicated to just the rustdoc change and see what comes of that.

We need to be fast to do that though, full Crater run now take up to 5 days.

**Comment by pnkfelix** [comment] 2018-10-09 21:00
@pietroalbini let me see if I can get a PR up

**Comment by pnkfelix** [comment] 2018-10-09 21:09
Filed as PR #54939.

I Put it up now because I don't know if my local test run will finish before I hit the sack.

Also, that PR does not yet have a unit test for the regression.

But it should be enough to throw into crater, I hope

**Comment by alexcrichton** [comment] 2018-10-09 22:01
@pnkfelix right yeah changing the compiler to have new errors shouldn't be backported, and I would also be very wary of backporting changes to `rustdoc --test`, which have historically been notoriously brittle. A crater run looks to be a good start!

(sorry I was waiting for a local build to see the viability of a PR but kept forgetting to go back to it)

**Comment by pietroalbini** [comment] 2018-10-18 19:47
Fixed and backported, should work in the next beta release.

**Comment by pnkfelix** [comment] 2018-10-19 20:39
I hate to ask, but: @pietroalbini , I think we still need a regression test, right?

**Comment by pietroalbini** [comment] 2018-10-19 20:42
Ugh, there was no regression test in that PR.

**Comment by pnkfelix** [comment] 2018-10-19 20:45
(But the lack of a regression test does not need to block the release, of course)

**Comment by pietroalbini** [comment] 2018-10-19 20:55
Manually checked the issue is actually fixed, just to be sure.

**Closed** 2018-10-25 17:45 UTC
Labels: A-allocators, C-bug, E-needstest, I-nominated, T-rustdoc, regression-from-stable-to-beta
