### ISSUE TITLE
Remove the `Sync` requirement for `#[thread_local]` statics.

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust#35035] opened 2016-07-25 18:10 UTC
This restriction can be very bothersome, and has no real purpose. `thread_local`s always belongs to a single thread, thus interior mutability won't cause data races.

**Comment by ticki** [comment] 2016-07-27 08:42
Here's a temporary workaround:

```rust
#![feature(const_fn, thread_local)]

use std::{ops, marker};

/// Add `Sync` to an arbitrary type.
///
/// This primitive is used to get around the `Sync` requirement in `static`s (even thread local
/// ones! see rust-lang/rust#35035). Due to breaking invariants, creating a value of such type is
/// unsafe, and care must be taken upon usage.
///
/// In general, this should only be used when you know it won't be shared across threads (e.g. the
/// value is stored in a thread local variable).
pub struct Syncify<T>(T);

impl<T> Syncify<T> {
    /// Create a new `Syncify` wrapper.
    ///
    /// # Safety
    ///
    /// This is invariant-breaking and thus unsafe.
    const unsafe fn new(inner: T) -> Syncify<T> {
        Syncify(inner)
    }
}

impl<T> ops::Deref for Syncify<T> {
    type Target = T;

    fn deref(&self) -> &T {
        &self.0
    }
}

unsafe impl<T> marker::Sync for Syncify<T> {}

/// Declare a thread-local static variable.
///
/// TLS works by copying the initial data on every new thread creation. This allows access to a
/// variable, which is only available for the current thread, meaning that there is no need for
/// syncronization.
///
/// For this reason, in contrast to other `static`s in Rust, this need not thread-safety, which is
/// what this macro "fixes".
macro_rules! tls {
    (static $name:ident: $ty:ty = $val:expr) => { tls!(#[] static $name: $ty = $val); };
    (#[$($attr:meta),*] static $name:ident: $ty:ty = $val:expr) => {
        $(#[$attr])*
        #[thread_local]
        static $name: Syncify<$ty> = unsafe { Syncify::new($val) };
    }
}

use std::cell::Cell;

tls!(static CELL: Cell<u32> = Cell::new(2));
tls!(static CELL2: Cell<&'static str> = Cell::new("a"));

fn main() {
    CELL.set(3);
}
```

**Comment by ticki** [comment] 2016-07-27 08:56
@steveklabnik the `A-libs` tag is wrong.

**Comment by nikomatsakis** [comment] 2016-08-04 21:46
This seems related to the RFC around signal handlers. Are signal handlers the main reason that there is a sync requirement? I agree it can be burdensome and *seems* unnecessary, except for that.

cc @alexcrichton

**Comment by nikomatsakis** [comment] 2016-08-04 21:47
cc @rust-lang/lang -- thoughts on whether thread-local values must be sync?

**Comment by alexcrichton** [comment] 2016-08-05 06:07
I think this is kinda a duplicate of https://github.com/rust-lang/rust/issues/17954, I believe the `Sync` behavior has been brought up there.

AFAIK the `Sync` requirement is because `static` variables require `Sync`, and no one ever got around to making that check conditional on whether `#[thread_local]` was present or not. That is, I don't believe it's intentional. It makes sense to me to remove it, but it still doesn't make the feature sound (ala https://github.com/rust-lang/rust/issues/17954)

**Comment by nikomatsakis** [comment] 2016-08-06 09:30
Ah yeah I'd forgotten completely about #17954.

**Comment by ticki** [comment] 2016-08-06 09:34
https://github.com/rust-lang/rfcs/pull/1705

**Comment by Mark-Simulacrum** [comment] 2017-05-10 19:54
So I think discussion above seems to indicate that we should close this as a somewhat-duplicate of #17954, so I'm going to close in favor of it.

**Comment by eddyb** [comment] 2017-05-11 06:44
It's not a duplicate though.

**Comment by alexcrichton** [comment] 2017-08-27 02:23
Closed by https://github.com/rust-lang/rust/pull/43746

**Closed by alexcrichton** 2017-08-27 02:23 UTC
Labels: C-feature-request, T-lang
