### ISSUE TITLE
Bounds on associated types ignored

### ISSUE THREAD

**Issue by bgamari** [rust-lang/rust#20979] opened 2015-01-12 05:14 UTC
In,
```rust
trait BitIter {
    type Iter: Iterator<Item=bool>;
    pub fn bit_iter(self) -> <Self as BitIter>::Iter;
}

pub fn test_bad<Sym: BitIter>(sym: Sym) {
    let i = sym.bit_iter();
}

pub fn test_good<Sym: BitIter>(sym: Sym)
    where <Sym as BitIter>::Iter: Iterator<Item=bool> {
    let i = sym.bit_iter();
}

pub fn main() {}
```
`test_bad` fails to compile, despite the bounds on `BitIter::Iter` with, 
```
hi.rs:7:17: 7:27 error: type mismatch resolving `<<Sym as BitIter>::Iter as core::iter::Iterator>::Item == bool`: expected associated type, found bool
hi.rs:7     let i = sym.bit_iter();
                        ^~~~~~~~~~
```

**Comment by tomjakubowski** [comment] 2015-01-12 05:34
Is this related to #20890?

**Comment by bgamari** [comment] 2015-01-12 05:46
Yep, sounds like the same issue.

**Comment by Aatch** [comment] 2015-01-12 06:40
Closing as duplicate of #20890

**Closed by Aatch** 2015-01-12 06:40 UTC
Labels: A-associated-items
