### ISSUE TITLE
Request: `add`, `sub`, and `offset` for NonNull

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#90549] opened 2021-11-03 23:40 UTC
Currently, offsetting a non-null pointer is quite cumbersome. It would be better if these pointer methods were provided directly on the NonNull type instead of having to get the inner pointer, do the change, and then call NonNull::new_unchecked on that output.

**Comment by fee1-dead** [comment] 2021-11-04 12:18
`offset`ting/`sub`tracting a NonNull pointer needs to return an `Option<NonNull>`, since the offset could make the pointer null again. e.g. `0x1.offset(-1)` should return `None`.

I think `add` is fine, though.

**Comment by hkratz** [comment] 2021-11-04 12:35
`add` is not fine either:
```rust
let ptr = usize::MAX as *const u8;
unsafe {
    assert_eq!(ptr.add(1), core::ptr::null());
}
```

**Comment by Lokathor** [comment] 2021-11-04 13:24
The standard rules of add/sub/offset would still apply, specifically that the calculation does not go outside of an allocation or one byte past the end of an allocation, and also that the calculation does not wrap within the address space.

So it would already be UB to `sub` or `offset` to 0, separate from the non-null element. Similarly it would already be UB to `add` or `offset` past the end of the address space, so wrapping around to 0 is also not a concern.

**Comment by antoyo** [comment] 2023-06-09 01:05
Seems to be a duplicate of https://github.com/rust-lang/rust/issues/72429.

**Comment by Dylan-DPC** [comment] 2023-12-25 18:36
Closing this as duplicate of #72429

**Closed by Dylan-DPC** 2023-12-25 18:36 UTC
Labels: C-feature-request
