### ISSUE TITLE
Implied bounds by associated types as function parameters are inconsistent in an unsound way.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#91068] opened 2021-11-20 02:47 UTC
Taking a simple trait
```rs
trait Trait {
    type Type;
}

impl<T> Trait for T {
    type Type = ();
}
```
the type `<&'a &'b () as Trait>::Type` as a function argument gives rise to a `'a: 'b` bound, as can be demonstrated by e.g.
```rs
fn f<'a, 'b>(s: &'b str, _: <&'a &'b () as Trait>::Type) -> &'a str {
    s
}
```

However, this bound is apparently not really enforced. I suppose the compiler “simplifies” such a function to `f<'a, 'b>(s: &'b str, _: ()) -> &'a str` for the caller? So

```rs
fn main() {
    let x = String::from("Hello World!");
    let y = f(&x, ());
    drop(x);
    println!("{}", y);
}
```
compiles fine and produces UB. ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=991cb887042777298e28f80d0bace5d5))

Another implication of the same kind of issue is that a function like
```rs
type Type<T> = <T as Trait>::Type;

fn g<'a>(_: Type<&'a ()>) -> &'a str {
    ""
}
```
fails to compile with a weird error message.
```
   Compiling playground v0.0.1 (/playground)
error[E0581]: return type references lifetime `'a`, which is not constrained by the fn input types
  --> src/lib.rs:11:30
   |
11 | fn g<'a>(_: Type<&'a ()>) -> &'a str {
   |                              ^^^^^^^

For more information about this error, try `rustc --explain E0581`.
```
The error code 581 only talks about `fn`-**pointer** types ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2d2269d70f16f47fd2f74be3cfda22f3))

@rustbot label T-compiler, A-lifetimes, A-typesystem, A-traits, A-associated-items, I-unsound

Originally discovered in a [discussion on URLO](https://users.rust-lang.org/t/how-can-i-write-a-generic-matcher/67621/5?u=steffahn).

**Comment by ecstatic-morse** [comment] 2021-11-20 04:54
Another dupe of #25860?

**Comment by Cyborus04** [comment] 2021-11-20 05:11
> Another dupe of #25860?

I knew I had seen something like this before, I was just searching through my history to see if I could find it haha

**Comment by steffahn** [comment] 2021-11-20 11:19
> Another dupe of #25860?

No, not a dupe of #25860. This issue has nothing to do with variance.

**Comment by danielhenrymantilla** [comment] 2021-11-20 14:09
I can confirm this doesn't have to do with variance:

```rust
trait Trait { type T; }
impl Trait for &'_ &'_ () { type T = (); }

/// Invariant
struct Inv<'lt>(fn(&()) -> &mut &'lt ());

fn transmute_lt<'src : 'src, 'dst : 'dst> (
    s: Inv<'src>,
    // `'src : 'dst` i.e. `'src ⊇ 'dst`
    _dst_implied_smaller: <&'dst &'src () as Trait>::T,
    // `'dst : 'src` i.e. `'dst ⊇ 'src`
    _dst_implied_greater: <&'src &'dst () as Trait>::T,
) -> Inv<'dst> {
    // => `'src = 'dst` => does typecheck
    s
}

/// Typechecks!
fn enlarge<'short, 'long : 'short> (
    it: Inv<'short>,
) -> Inv<'long>
{
    // signature of transmute_lt:
    let f: fn(Inv<'short>, (), ()) -> Inv<'long> = transmute_lt::<'short, 'long>;
    f(it, (), ())
}
```

  - [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7ec0fe5821403779e1e7dc55d584a111)

**Comment by steffahn** [comment] 2021-11-20 14:09
To demonstrate the point that this has nothing to do with variance or double-references, here's the same thing with a custom invariant struct
```rs
struct S<'a: 'static>(*mut &'a ());

fn f<'a>(s: &'a str, _: <S<'a> as Trait>::Type) -> &'static str {
    s
}

// same main function…
```

**Comment by steffahn** [comment] 2021-11-20 22:52
The same bug can (not too surprisingly) also be used to write trait implementations that (unsoundly) have additional implied bounds available in the method body. E.g.
```rs
trait Trait<Dummy> {
    type Type;
}

impl<T, Dummy> Trait<Dummy> for T {
    type Type = T;
}

struct StrRef<'a>(&'a str);

impl<'a, 'b> From<&'a str> for StrRef<'b> {
    fn from(s: <&'a str as Trait<&'b &'a str>>::Type) -> StrRef<'b> {
        Self(s)
    }
}

fn main() {
    let x = String::from("Hello World!");
    let y = StrRef::from(x.as_str()).0;
    drop(x);
    println!("{}", y);
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=124beb335969970e9a0ff52298cff21d))

**Comment by apiraino** [comment] 2021-11-22 16:52
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2391068.20Implied.20bounds.20by.20types.20of.20associated.20items.20are.20inco.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical

**Comment by steffahn** [comment] 2021-11-22 17:20
Just checked what rust versions are affected. My original example only works from 1.56, so the latest rust version.

@rustbot label regression-from-stable-to-stable

**Comment by steffahn** [comment] 2021-11-22 17:32
searched nightlies: from nightly-2021-05-01 to nightly-2021-11-22
regressed nightly: nightly-2021-08-30
searched commit range: https://github.com/rust-lang/rust/compare/5eacec9ec7e112a0de1011519a57c45586d58414...2f662b14033c4369b0a7b5c2656592ef08edf434
regressed commit: https://github.com/rust-lang/rust/commit/59ce76548484806ac4970c57c0bb6ad9e53b80f6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --regress non-error --access github --start 2021-05-01 
```
</details>

@rustbot label -E-needs-bisection

**Comment by steffahn** [comment] 2021-11-22 17:34
That’s
* #88312

cc @jackh726, @nikomatsakis

**Comment by steffahn** [comment] 2021-11-22 17:39
> _Edit:_ Same goes for the example involving `From` above, as well as @danielhenrymantilla's example or my invariant example.

Double-checked, they’re all regressing at #88312

**Comment by jackh726** [comment] 2021-11-22 18:08
Well...shoot.

I guess we can either just revert #88312 for now *or* change the rule to be something like "if all the parameters of an associated type are well formed, then the associated type is", which should solve this.

**Comment by steffahn** [comment] 2021-11-22 18:34
I suppose #88312 was only fixing a problem observable on nightly, correct? If reverting (for now) is done easily (i.e. no subsequent changes rely on #88312), then I suppose by reverting, we could get a fix out quickly and perhaps even get it beta-backported so that 1.57 is no longer affected? (I assume doing anything other than a revert is not really possible anymore time-wise until 1.57 release next week.)

**Comment by steffahn** [comment] 2021-11-22 18:38
> change the rule to be something like "if all the parameters of an associated type are well formed, then the associated type is"

I can't comment on the alternative you lay out here, since I'm not at all familiar with the details of what's going on here. If this is just an oversight in  #88312 / easily fixed / not a fundamental problem with that PR; and if it seems _very_ unlikely to introduce any other issues, then that other approach might also work for inclusion in 1.57? A revert might be easier though.

**Comment by steffahn** [comment] 2021-11-22 18:43
@jackh726 

> change the rule to be something like "if all the parameters of an associated type are well formed, then the associated type is

would this imply that 
``````rs
trait Trait {
    type Type;
}

impl<T> Trait for T {
    type Type = ();
}

fn f<'a, 'b>(_: <&'a &'b () as Trait>::Type) where 'a: 'a, 'b: 'b {}
fn g<'a, 'b>() {
    f::<'a, 'b>(());
}
``````
no longer compiles? (Because if _yes_, that would be a regression for code that works since Rust `1.0`!)

**Comment by steffahn** [comment] 2021-11-22 19:06
> Only the problem with
> 
> ```rust
> type Type<T> = <T as Trait>::Type;
> 
> fn g<'a>(_: Type<&'a ()>) -> &'a str {
>     ""
> }
> ```
> 
> not compiling appears to be older.

Looks like this observation might be an instance of #47511.

**Comment by jackh726** [comment] 2021-11-22 19:20
> I suppose #88312 was only fixing a problem observable on nightly, correct?

This is correct.

> then I suppose by reverting, we could get a fix out quickly

Also correct.

> would this imply that ... no longer compiles?

I'm not sure yet; probably this should still compile. Really, the point of #88312 was to recognize that if an associated type is created, then the where clauses/bounds on that associated type must have been met. Well, the wrinkle here is that in `<&'a &'b () as Trait>::Type`, we don't necessarily have to create a `&'a &'b` to create a  `<&'a &'b () as Trait>::Type`.

**Comment by Aaron1011** [comment] 2021-11-26 17:02
PRs https://github.com/rust-lang/rust/pull/91243 and https://github.com/rust-lang/rust/pull/91242 have been opened to fix this on nightly and beta (by partially reverting https://github.com/rust-lang/rust/pull/88312)

**Comment by pnkfelix** [comment] 2021-12-02 15:25
Addressed by PR #91243 and PR #91361, fixed in 1.57 release. Closing.

**Closed by pnkfelix** 2021-12-02 15:25 UTC
Labels: A-typesystem, A-lifetimes, A-traits, A-associated-items, T-compiler, regression-from-stable-to-stable, I-unsound, C-bug, P-critical

**Comment by steffahn** [comment] 2021-12-02 15:50
It might make sense to also add a test for the case I listed above, i.e.
```rs
trait Trait {
    type Type;
}

impl<T> Trait for T {
    type Type = ();
}

fn f<'a, 'b>(_: <&'a &'b () as Trait>::Type) where 'a: 'a, 'b: 'b {}
fn g<'a, 'b>() {
    f::<'a, 'b>(());
}
```

to make sure future updates don't break code like that?

**Comment by jackh726** [comment] 2021-12-02 16:08
@steffahn any way I can convince you to make a PR for that and I'll review?

**Comment by steffahn** [comment] 2021-12-02 16:10
I can make the PR. I just don’t know where exactly the test should go.

**Comment by jackh726** [comment] 2021-12-02 16:11
Probably just `src/test/ui/fn/implied-bounds-unnorm-associated-type-2.rs`

**Comment by yshui** [comment] 2023-03-06 22:45
Hi, I randomly tried to compile the examples in this issue, looks like 1.65.0 has regressed and https://github.com/rust-lang/rust/issues/91068#issuecomment-974655559 type checks again.
