### ISSUE TITLE
Duplicated display of items under "Implementations on Foreign Types" is confusing.

### ISSUE THREAD

**Issue by rljacobson** [rust-lang/rust#72748] opened 2020-05-29 18:26 UTC
Consider this example of the [Extend trait](https://doc.rust-lang.org/std/iter/trait.Extend.html#impl-Extend%3C(%26%27a%20K%2C%20%26%27a%20V)%3E-for-HashMap%3CK%2C%20V%2C%20S%3E) which lists `HashSet<T, S>` and `HashMap<K, V, S>` twice each:
<img width="202" alt="Screen Shot 2020-05-29 at 1 58 47 PM" src="https://user-images.githubusercontent.com/1412598/83291819-f97c1580-a1b6-11ea-94cf-52c48dc45383.png">
There *should* be two instances of the implementation of the `Extend` trait, as the trait is implemented for two different sets of trait bounds. The problem is that they are displayed identically, which in my view is clearly confusing. 

A solution, if one is deemed necessary, will probably need some discussion. Could the trait bounds be included if and only if omitting them would result in duplicated entries in a section?

**Comment by ehuss** [comment] 2020-05-29 18:29
Thanks for the report.  This looks like an issue for rustdoc which lives in the rust-lang/rust repository, so I have transferred it over there.

**Comment by Dylan-DPC** [comment] 2023-03-29 11:42
This now works as intended:
![image](https://user-images.githubusercontent.com/99973273/228524460-13d326dd-2549-45d9-866e-ec7fb97aafd3.png)
 and 
 
![image](https://user-images.githubusercontent.com/99973273/228524787-b06d03f6-f90e-4c26-93eb-6b1963d7834f.png)

**Closed by Dylan-DPC** 2023-03-29 11:42 UTC
Labels: T-rustdoc, C-bug
