### ISSUE TITLE
unused type params on fn lead to difficult to deciper errors at call site

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#28153] opened 2015-09-01 13:37 UTC
Consider code like this ([playpen](http://is.gd/PxabmK)):

```rust
fn add3<T>(x: i32) -> i32 { x + 3 }

fn main() {
    println!("add3(4): {}", add3(4));
}
```

The Rust compiler currently rejects the above, because it cannot infer what type to assign to the type parameter `T` in the above invocation `add3(4)`.

The problematic thing is the message:
```
<anon>:4:29: 4:33 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
<anon>:4     println!("add3(4): {}", add3(4));
                                     ^~~~
```

 1. This message complains about `_`, rather than referencing the parameter `T` of `fn add3`.
 2. It might be nice if, when we encounter this error, if we also did an additional check for the function itself and see if the type parameter in question is unused in the signature of `fn add` (since in such a situation, there is no way that the callsite will be able to supply the information via type annotation -- the only option is the generic parameter binding form like `add3::<(f64,i8)>(4)`, and it is *likely* (though not assured) that the actual bug is in the definition of `fn add3` itself, rather than at the call site.

**Comment by arielb1** [comment] 2015-09-01 17:08
Tracking the origin of type-variables to improve the "unable to infer enough type information about `_`" message would certainly we nice (we do it for defaults today).

**Comment by sanxiyn** [comment] 2015-10-26 06:44
See also #25871, which is about a lint for unused type parameters.

**Comment by nagisa** [comment] 2016-01-19 19:07
Duplicate of #25633

**Closed by nagisa** 2016-01-19 19:07 UTC
Labels: A-diagnostics
