### ISSUE TITLE
regression: can't call method `abs` on ambiguous numeric type `{float}`

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#125198] opened 2024-05-17 01:18 UTC
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/puffpastry-0.1.0/log.txt

```
[INFO] [stdout] error[E0689]: can't call method `abs` on ambiguous numeric type `{float}`
[INFO] [stdout]    --> src/activation.rs:206:39
[INFO] [stdout]     |
[INFO] [stdout] 206 |         assert!((res[0] - 0.08192506).abs() < 0.001);
[INFO] [stdout]     |    
```

**Comment by compiler-errors** [comment] 2024-05-17 01:20
This was probably regressed w/ some `f16`/`f128` stuff cc @tgross35

**Comment by tgross35** [comment] 2024-05-17 01:30
Hm, when did this last work? I can't get it to compile successfully even on older versions https://rust.godbolt.org/z/ExcMY36bf

**Comment by zachs18** [comment] 2024-05-17 01:42
The `puffpastry` crate's bound includes `T: ValidNumber<T>`, which includes `T: ... + From<f64> + ...`. Adding `T: Copy + From<f64>` to the example makes it compile on stable https://rust.godbolt.org/z/EbKTjzM9v

**Comment by tgross35** [comment] 2024-05-17 01:51
Ah, then  #123830 also should have removed this line https://github.com/rust-lang/rust/pull/123830/files#diff-154dff23a2c2f4fb97915229fd9c27d73293940250088020bfd2074094186ce4L173, which was added in https://github.com/rust-lang/rust/pull/122470.

Was this crate the only regression of this kind? If that is the case, maybe we would be okay leaving it based on discussion at https://github.com/rust-lang/rust/issues/123831.

**Comment by tgross35** [comment] 2024-05-21 21:07
@apiraino I think the only things maybe relevant for release notes would be conversions that involve a stable type, which could have an effect on inference. These would be:

1. `From<f16> for f64` added in #122470, removed in #12380, added back in #12473 (1.80 current nightly). Already had a crater run, no regressions
2. `From<f32> for f128`, added in #122470 (1.79 current beta). No known regressions
3. `From<f64> for f128`, added in #122470 (1.79 current beta). Regressions

Item 3 is the subject of this issue, we'll need a decision about whether to accept the regression or remove the impl.

The remaining conversions from #122470 shouldn't affect anything without nightly so I don't think they need release notes.

**Comment by apiraino** [comment] 2024-05-28 11:07
probably adding t-libs then. Opened a topic for increased visibility [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Regression.20from.20.23122470.20.28f16.20and.20f64.20support.29)

@rustbot label T-libs

**Comment by tgross35** [comment] 2024-06-05 00:25
Per https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings/topic/Meeting.202024-05-29/near/441273130, this regression is accepted. I submitted a PR to the regressed crate here https://github.com/uek-1/puffpastry/pull/4

**Comment by apiraino** [comment] 2024-08-05 10:34
I think this can be now closed as _accepted_, correct? cc @BoxyUwU

**Comment by tgross35** [comment] 2024-08-05 16:49
(I feel like we should have something like a regression-accepted label to make the status of these issues clear)

**Comment by apiraino** [comment] 2024-10-15 09:01
Closing since regression is mentioned in the release notes

**Closed by apiraino** 2024-10-15 09:01 UTC
Labels: T-compiler, regression-from-stable-to-stable, T-libs
