### ISSUE TITLE
Panic when piping rustc output to a non existent program

### ISSUE THREAD

**Issue by colonelmo** [rust-lang/rust#33433] opened 2016-05-05 14:30 UTC
```
$rustc --version
rustc 1.8.0
```
Here is the problem:
```
$rustc --explain E0308 | lessw
zsh: command not found: lessw
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread '<main>' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:626
```

**Comment by alexcrichton** [comment] 2016-05-05 16:09
I believe this is a dupe of https://github.com/rust-lang/rust/issues/30972 closed in favor of https://github.com/rust-lang/rust/issues/14505 which is [fixed on nightly](https://github.com/rust-lang/rust/issues/14505#issuecomment-196380065)

**Closed by alexcrichton** 2016-05-05 16:09 UTC
