### ISSUE TITLE
Error while compiling Ethcore Parity 

### ISSUE THREAD

**Issue by int03h** [rust-lang/rust#38829] opened 2017-01-04 20:38 UTC
I've been trying to get parity to compile for a few days now .. and I keep getting this error, I have tried, stable, beta and nightly ..  this is the error I get : ( I cut the top of the output off and left just the part where it breaks ) - I have not looked to see if this has been logged already .. there are way too many issues to wade through to see if this is a duplicate ) 

Compiling ethcrypto v0.1.0 (file:///files/src/parity/ethcrypto)
   Compiling parity-reactor v0.1.0 (file:///files/src/parity/util/reactor)
   Compiling rocksdb v0.4.5 (https://github.com/ethcore/rust-rocksdb#64c63ccb)
   Compiling reqwest v0.2.0
   Compiling docopt v0.6.80
   Compiling semver-parser v0.6.1
   Compiling igd v0.5.1
   Compiling env_logger v0.3.3
   Compiling fetch v0.1.0 (file:///files/src/parity/util/fetch)
   Compiling semver v0.5.1
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:395: node 37599 is inlined but not present in map

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: Could not compile `ethcore-util`.

This is the build script I use .. if you do this it should get the same error since I've done it on 3 different machines and it does the same .. ( nightly is uncommented .. and generates the above error  - but if you uncomment any of the others you will get something similar ) ...

clear
echo Deleting Rust
sleep 1
rm -rf ~/.multirust
rm -rf ~/.cargo

echo Installing New Rust
curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
#curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain beta -y
#curl https://sh.rustup.rs -sSf | sh -s --

export PATH="~/.cargo/bin:$PATH"

echo Updating Parity.. from GIT
sleep 1
rm -rf /files/src/parity
git clone --recursive https://github.com/ethcore/parity

echo Building release version of parity
cd /files/src/parity
~/.cargo/bin/cargo build --release

**Comment by int03h** [comment] 2017-01-04 21:10
Compiling fetch v0.1.0 (file:///files/src/parity/util/fetch)
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:395: node 37599 is inlined but not present in map

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423

**Comment by int03h** [comment] 2017-01-04 21:22
Last one.. 

This was compiled with STABLE rust .. 

Compiling rocksdb v0.4.5 (https://github.com/ethcore/rust-rocksdb#64c63ccb)
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:395: node 37599 is inlined but not present in map

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by alexcrichton** [comment] 2017-01-04 22:13
Some of these crates sound like they'd be a great candidate for cargotest in-tree to ensure that changes to the compiler don't ever regress them again!

**Comment by int03h** [comment] 2017-01-04 22:50
@alexcrichton I assume this is a general comment to the team ?  Is there anything I need to do to help/provide?

**Comment by alexcrichton** [comment] 2017-01-04 22:57
@int03h oh it's sort of both a general comment and something that anyone can help provide! In part of our CI for rust-lang/rust itself we take some projects and add them to [cargotest](https://github.com/rust-lang/rust/blob/master/src/tools/cargotest/main.rs). That means that for a change to land against rust-lang/rust the compiler must be able to check out all those repos and run `cargo test`.

If a regression like this could have been prevented by adding a new project to that list then we'd be more than glad to add a project there! That way all future changes can be sure to continue compiling the crate.

**Comment by int03h** [comment] 2017-01-04 23:13
Oh I c ... well .. parity pulls in a F$CKload of crates and stuff .. it would most definitely be a great project to add to your regression testing. I am not affiliated with the project at all .. I am just some random dude that happens to use the compiled version of parity as my ethereum client/wallet.  I think @gavofyork is a senior member/leader for parity .. I would have imagined he has been here before ? .. either way .. I am by no means a competent coder, so I the amount of help I could provide here is extremely limited.

**Comment by int03h** [comment] 2017-01-04 23:19
root@debby:/files/src/parity# cargo -V
cargo 0.17.0-nightly (740f9c0 2016-12-29)

Compiling ethcore-stratum v1.5.0 (file:///files/src/parity/stratum)
     Running `/files/src/parity/target/debug/build/ethcore-stratum-2db126478cc7e718/build-script-build`
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:395: node 37599 is inlined but not present in map

and ..  here's a WHOLE bunch more .. I ran cargo build --verbose and I did and export RUST_BACKTRACE=1 .. ( If that is how you set it !?! ?) .. anyway ... heres the full output :

Compiling ethcore-stratum v1.5.0 (file:///files/src/parity/stratum)
     Running `/files/src/parity/target/debug/build/ethcore-stratum-2db126478cc7e718/build-script-build`
error: internal compiler error: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:395: node 37599 is inlined but not present in map

       Fresh ethabi v0.2.2
     Running `/files/src/parity/target/debug/build/ethcore-ipc-tests-7dbfe4f9161e4a64/build-script-build`
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423
stack backtrace:
   1:     0x7f92daddec2c - std::sys::imp::backtrace::tracing::imp::write::h2a972e172776bc73
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f92dadecf5e - std::panicking::default_hook::{{closure}}::h3350be9abe4c8496
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7f92dadecb03 - std::panicking::default_hook::h255964940ef72e84
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:361
   4:     0x7f92daded407 - std::panicking::rust_panic_with_hook::ha02a85ff57cdb669
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7f92d37548ea - std::panicking::begin_panic::h063125b7da6f1fca
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7f92d376979d - rustc_errors::Handler::bug::h563da3c520e22a27
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:423
   7:     0x7f92d813c9f1 - rustc::session::opt_span_bug_fmt::{{closure}}::h5c454616325c5e52
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:788
   8:     0x7f92d813c4ce - rustc::session::opt_span_bug_fmt::h3659754ea96d3141
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:1021
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:784
   9:     0x7f92d813c132 - rustc::session::bug_fmt::haeec79526b0fafd5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/session/mod.rs:768
  10:     0x7f92d805897f - rustc::hir::map::Map::read::h0dd82ac56c35db58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:395
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:288
  11:     0x7f92d80590b4 - rustc::hir::map::Map::body::hb9371f9755e96bac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/map/mod.rs:473
  12:     0x7f92d84c0fd4 - rustc_const_eval::eval::eval_const_expr_partial::h5722325983da1967
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_const_eval/eval.rs:904
  13:     0x7f92d84c39a8 - rustc_const_eval::eval::eval_const_expr_partial::h5722325983da1967
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_const_eval/eval.rs:768
  14:     0x7f92d953e020 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h85d01a7eaaa7ac4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:222
  15:     0x7f92d953dec5 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h85d01a7eaaa7ac4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/<walk_list macros>:2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:254
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:968
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:214
  16:     0x7f92d953dec5 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h85d01a7eaaa7ac4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/<walk_list macros>:2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:254
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:968
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:214
  17:     0x7f92d953db30 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h85d01a7eaaa7ac4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:962
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:214
  18:     0x7f92d953d9fe - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h85d01a7eaaa7ac4a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/<walk_list macros>:2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:254
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:986
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:214
  19:     0x7f92d953bc79 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h87ecaaaf26707b47
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:402
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:220
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:141
  20:     0x7f92d953eed2 - rustc_passes::consts::check_crate::hefa7ba1bb2019f02
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/intravisit.rs:293
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/itemlikevisit.rs:89
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/dep_graph/visit.rs:64
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/hir/mod.rs:465
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/dep_graph/visit.rs:75
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/mod.rs:2660
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_passes/consts.rs:440
  21:     0x7f92db18795e - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h21a6521e909907a7
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:891
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/util/common.rs:34
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:889
  22:     0x7f92db17aded - rustc_driver::driver::phase_3_run_analysis_passes::h20919355616dc567
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:992
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:253
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:989
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:976
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:253
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:973
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/ty/context.rs:743
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:859
  23:     0x7f92db16a111 - rustc_driver::driver::compile_input::hc831e6818a12286f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/driver.rs:163
  24:     0x7f92db1b07d8 - rustc_driver::run_compiler::ha4de160a9d909b83
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:221
  25:     0x7f92db0bcd28 - std::panicking::try::do_call::h2ff0d6696d3add9d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:1117
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:137
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_driver/lib.rs:1051
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  26:     0x7f92dadf626a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  27:     0x7f92db0e6e7b - <F as alloc::boxed::FnBox<A>>::call_box::h81baf0e61cbf35f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:302
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  28:     0x7f92dadebdc4 - std::sys::imp::thread::Thread::new::thread_start::h27fa49fe81f658e4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  29:     0x7f92d2f006a9 - start_thread
  30:     0x7f92daaa613c - __clone
  31:                0x0 - <unknown>

error: Could not compile `ethcore-util`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ethcore_util util/src/lib.rs --crate-type lib -g --cfg feature="default" -C metadata=1d5921a30039d660 -C extra-filename=-1d5921a30039d660 --out-dir /files/src/parity/target/debug/deps --emit=dep-info,link -L dependency=/files/src/parity/target/debug/deps --extern crypto=/files/src/parity/target/debug/deps/libcrypto-84c1bd1acc23cedb.rlib --extern vergen=/files/src/parity/target/debug/deps/libvergen-f4d1784ffca5370d.rlib --extern lru_cache=/files/src/parity/target/debug/deps/liblru_cache-2b7d03af29d0b249.rlib --extern time=/files/src/parity/target/debug/deps/libtime-02018c58facc89ee.rlib --extern table=/files/src/parity/target/debug/deps/libtable-d10b2403a7590532.rlib --extern elastic_array=/files/src/parity/target/debug/deps/libelastic_array-76c7d18bdb1ab8c0.rlib --extern itertools=/files/src/parity/target/debug/deps/libitertools-c611d01ca9f11451.rlib --extern log=/files/src/parity/target/debug/deps/liblog-1ce22d3a92f37841.rlib --extern tiny_keccak=/files/src/parity/target/debug/deps/libtiny_keccak-912f10d04717b632.rlib --extern rlp=/files/src/parity/target/debug/deps/librlp-0a9b69548f7fe9eb.rlib --extern rocksdb=/files/src/parity/target/debug/deps/librocksdb-4610773f70548b2d.rlib --extern ansi_term=/files/src/parity/target/debug/deps/libansi_term-a16cb51797899298.rlib --extern ethcore_devtools=/files/src/parity/target/debug/deps/libethcore_devtools-385d831303c0ca7f.rlib --extern ethcore_bigint=/files/src/parity/target/debug/deps/libethcore_bigint-d5795da4ef5ddb39.rlib --extern rustc_serialize=/files/src/parity/target/debug/deps/librustc_serialize-7afcde5ec1806fb9.rlib --extern using_queue=/files/src/parity/target/debug/deps/libusing_queue-41f98ebaf021b73a.rlib --extern rand=/files/src/parity/target/debug/deps/librand-a266d0434ee969c4.rlib --extern regex=/files/src/parity/target/debug/deps/libregex-40fac7c1de4f07cd.rlib --extern lazy_static=/files/src/parity/target/debug/deps/liblazy_static-1b77b520c29e5601.rlib --extern env_logger=/files/src/parity/target/debug/deps/libenv_logger-8d599e137f4b61eb.rlib --extern libc=/files/src/parity/target/debug/deps/liblibc-8c7226756bef4c8b.rlib --extern arrayvec=/files/src/parity/target/debug/deps/libarrayvec-f895db3c9dd92920.rlib --extern ethcore_bloom_journal=/files/src/parity/target/debug/deps/libethcore_bloom_journal-87e01edf5945e962.rlib --extern target_info=/files/src/parity/target/debug/deps/libtarget_info-699acdb356524e63.rlib --extern sha3=/files/src/parity/target/debug/deps/libsha3-3537757725c038c7.rlib --extern heapsize=/files/src/parity/target/debug/deps/libheapsize-ff63dc1fee64e153.rlib --extern secp256k1=/files/src/parity/target/debug/deps/libsecp256k1-8f4f97d88d5a5434.rlib --extern parking_lot=/files/src/parity/target/debug/deps/libparking_lot-568d257331396c45.rlib -L native=/files/src/parity/target/debug/build/rust-crypto-c0f524fa795e4be8/out -L native=/files/src/parity/target/debug/build/rocksdb-sys-a7b4c59ac47296f6/out -L native=/files/src/parity/target/debug/build/rocksdb-sys-a7b4c59ac47296f6/out -L native=/files/src/parity/target/debug/build/sha3-428e03d3118958a6/out -L native=/files/src/parity/target/debug/build/eth-secp256k1-4244243ecb0de896/out` (exit code: 101)

**Comment by NookSF** [comment] 2017-01-04 23:32
Dupe of #38790

**Comment by int03h** [comment] 2017-01-04 23:33
cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/ethcore/rust-ctrlc.git`
    Updating git repository `https://github.com/ethcore/jsonrpc.git`
    Updating git repository `https://github.com/ethcore/mio`
    Updating git repository `https://github.com/ethcore/nanomsg.rs.git`
    Updating git repository `https://github.com/ethcore/rust-secp256k1`
    Updating git repository `https://github.com/ethcore/rust-rocksdb`
    Updating git repository `https://github.com/ethcore/elastic-array`
    Updating git repository `https://github.com/ethcore/mio`
    Updating git repository `https://github.com/ethcore/hyper`
    Updating git repository `https://github.com/ethcore/rotor`
    Updating git repository `https://github.com/ethcore/ws-rs.git`
    Updating git repository `https://github.com/ethcore/mio`
    Updating git repository `https://github.com/carllerche/bytes`
    Updating git repository `https://github.com/carllerche/slab`
    Updating git repository `https://github.com/ethcore/js-precompiled.git`
    Updating aho-corasick v0.5.1 -> v0.5.3
    Updating ansi_term v0.7.2 -> v0.7.5
    Updating arrayvec v0.3.16 -> v0.3.20
    Removing aster v0.25.0
    Updating bigint v1.0.0 -> v1.0.1
    Removing blastfig v0.3.3
    Updating bytes v0.4.0-dev (https://github.com/carllerche/bytes#6529f639) -> #93c08064
    Updating cookie v0.2.4 -> v0.2.5
    Updating ctrlc v1.1.1 (https://github.com/ethcore/rust-ctrlc.git#f4927770) -> #b5230171
    Updating daemonize v0.2.2 -> v0.2.3
    Updating docopt v0.6.80 -> v0.6.86
    Updating env_logger v0.3.3 -> v0.3.5
      Adding error-chain v0.7.2
    Updating eth-secp256k1 v0.5.4 (https://github.com/ethcore/rust-secp256k1#a9a0b1be) -> #f998f9a8
    Updating ethabi v0.2.2 -> v0.2.3
    Updating futures v0.1.6 -> v0.1.7
    Updating gcc v0.3.35 -> v0.3.41
    Updating heapsize v0.3.6 -> v0.3.7
    Updating httparse v1.1.2 -> v1.2.1
    Updating igd v0.5.1 -> v0.5.2
    Updating isatty v0.1.1 -> v0.1.3
    Updating itertools v0.4.13 -> v0.4.19
    Updating jsonrpc-core v4.0.0 (https://github.com/ethcore/jsonrpc.git#33262d62) -> #ea14081c
    Updating jsonrpc-http-server v6.1.1 (https://github.com/ethcore/jsonrpc.git#33262d62) -> #ea14081c
    Updating jsonrpc-ipc-server v0.2.4 (https://github.com/ethcore/jsonrpc.git#33262d62) -> #ea14081c
    Updating jsonrpc-macros v0.1.0 (https://github.com/ethcore/jsonrpc.git#33262d62) -> #ea14081c
    Updating jsonrpc-tcp-server v0.1.0 (https://github.com/ethcore/jsonrpc.git#33262d62) -> #ea14081c
    Updating lazy_static v0.2.1 -> v0.2.2
    Updating libc v0.2.16 -> v0.2.19
    Updating matches v0.1.2 -> v0.1.4
      Adding metadeps v1.1.1
    Updating mime v0.2.0 -> v0.2.2
    Updating mime_guess v1.6.1 -> v1.8.1
    Updating mio v0.6.1 (https://github.com/ethcore/mio#ef182bae) -> #15a57703
    Updating mio v0.6.1 -> v0.6.2
    Updating miow v0.1.3 -> v0.1.5
    Updating nanomsg v0.5.1 (https://github.com/ethcore/nanomsg.rs.git#c40fe442) -> #04feb1b4
    Updating nanomsg-sys v0.5.0 (https://github.com/ethcore/nanomsg.rs.git#c40fe442) -> #04feb1b4
    Updating net2 v0.2.23 -> v0.2.26
    Updating nix v0.5.0 -> v0.5.1
    Updating nodrop v0.1.6 -> v0.1.8
    Updating nom v1.2.2 -> v1.2.4
    Updating num v0.1.32 -> v0.1.36
    Updating num-bigint v0.1.32 -> v0.1.35
    Updating num-complex v0.1.32 -> v0.1.35
    Updating num-rational v0.1.32 -> v0.1.35
    Updating num-traits v0.1.32 -> v0.1.36
    Removing num_cpus v0.2.11
    Removing num_cpus v1.2.0
      Adding num_cpus v0.2.13
      Adding num_cpus v1.2.1
    Updating number_prefix v0.2.5 -> v0.2.7
    Updating odds v0.2.12 -> v0.2.25
    Updating openssl v0.9.3 -> v0.9.5
    Updating openssl-sys v0.9.3 -> v0.9.5
    Updating phf v0.7.14 -> v0.7.20
    Updating phf_codegen v0.7.14 -> v0.7.20
    Updating phf_generator v0.7.14 -> v0.7.20
    Updating phf_shared v0.7.14 -> v0.7.20
    Updating primal-sieve v0.2.5 -> v0.2.6
    Removing quasi v0.18.0
    Removing quasi_codegen v0.18.0
    Updating quine-mc_cluskey v0.2.2 -> v0.2.4
      Adding quote v0.3.10
    Updating rand v0.3.14 -> v0.3.15
    Removing rayon v0.4.2
      Adding rayon v0.4.3
      Adding rayon v0.5.0
    Updating regex v0.1.68 -> v0.1.80
    Updating regex-syntax v0.3.1 -> v0.3.9
    Updating rocksdb v0.4.5 (https://github.com/ethcore/rust-rocksdb#64c63ccb) -> #8579e896
    Updating rocksdb-sys v0.3.0 (https://github.com/ethcore/rust-rocksdb#64c63ccb) -> #8579e896
    Updating rpassword v0.2.2 -> v0.2.3
    Updating rustc-serialize v0.3.19 -> v0.3.22
    Updating schannel v0.1.1 -> v0.1.2
    Updating security-framework v0.1.9 -> v0.1.10
    Updating security-framework-sys v0.1.9 -> v0.1.10
    Updating semver-parser v0.6.1 -> v0.6.2
    Updating serde v0.8.19 -> v0.8.21
    Updating serde_codegen v0.8.4 -> v0.8.21
    Updating serde_codegen_internals v0.7.0 -> v0.11.3
    Updating serde_json v0.8.1 -> v0.8.4
    Updating siphasher v0.1.1 -> v0.1.3
    Removing stable-heap v0.1.0 (https://github.com/carllerche/stable-heap?rev=3c5cd1ca47#3c5cd1ca)
    Updating strsim v0.3.0 -> v0.5.2
      Adding syn v0.10.5
    Updating syntex v0.42.2 -> v0.52.0
    Updating syntex_errors v0.42.0 -> v0.52.0
    Updating syntex_pos v0.42.0 -> v0.52.0
    Updating syntex_syntax v0.42.0 -> v0.52.0
    Updating thread_local v0.2.5 -> v0.2.7
    Updating tiny-keccak v1.0.5 -> v1.1.1
    Removing toml v0.1.28
    Removing toml v0.2.0
      Adding toml v0.1.30
      Adding toml v0.2.1
    Updating unicode-bidi v0.2.3 -> v0.2.4
    Updating unicode-normalization v0.1.2 -> v0.1.3
    Updating url v1.2.0 -> v1.2.4
    Updating vergen v0.1.0 -> v0.1.1
    Updating xml-rs v0.3.4 -> v0.3.5
    Updating zip v0.1.18 -> v0.1.19

**Comment by int03h** [comment] 2017-01-04 23:35
@NookSF
> Dupe of  #38790

This fails on stable,beta and nightly. There's succeeds on stable. So I am not so sure about that.

**Comment by NookSF** [comment] 2017-01-04 23:52
Same error: `librustc/hir/map/mod.rs:395: node xxx is inlined but not present in map`

**Comment by alexcrichton** [comment] 2017-01-04 23:59
@int03h additionally, is this a regression from some previous stable version?

**Comment by int03h** [comment] 2017-01-05 00:14
@alexcrichton I am just pulling whatever is in the ethcore repo .. it did work before .. I am not sure why it doesn't now.  I came here first because rustc told me to ;) ..  
" note: the compiler unexpectedly panicked. this is a bug.
  note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports"

**Comment by steveklabnik** [comment] 2018-12-10 18:56
Given that nobody else has seen this ICE since then, and Parity keeps building today, I'm going to assume that this ended up being fixed. @int03h if this is incorrect, please let me know!

**Closed by steveklabnik** 2018-12-10 18:56 UTC
Labels: C-bug, I-ICE
