### ISSUE TITLE
Sort items in rustdoc with integers in their names more naturally

### ISSUE THREAD

**Issue by clarcharr** [rust-lang/rust#39596] opened 2017-02-06 21:11 UTC
Right now, `Trait10` will be shown before `Trait2` in rustdoc. It'd be nice if this could be changed to sort numbers in order by value whenever they're encountered.

**Comment by phungleson** [comment] 2017-02-11 04:14
Hey guys, wanted to help with this, but this is the first time i look into rustdoc, any suggestion where i can start?

**Comment by clarcharr** [comment] 2017-02-11 04:18
When I took a look myself, it was just a call to `slice::sort` that did the sorting, so, if you make a slice sorting function that works and give it a few tests, someone should be able to point you to the place to call it.

**Comment by phungleson** [comment] 2017-02-11 04:23
Thanks @clarcharr any place in the code you can link here so that I can add in?

I tried to search the whole project for `Trait10` `Trait2` and `slice::sort` but couldn't find anything.

**Comment by phungleson** [comment] 2017-02-11 04:24
Perhaps you mean add sort function into `libcore/slice.rs`?

**Comment by keeperofdakeys** [comment] 2017-02-12 00:03
I suspect the sorting is done here (https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render.rs#L1707), but I may be wrong.

**Comment by phungleson** [comment] 2017-02-12 09:07
Yep thanks @keeperofdakeys looks like so, i will try to make changes around it.

Thanks again ;)

**Comment by clarcharr** [comment] 2017-02-20 01:57
So, I found out a relatively easy way to do this type of sorting and decided to make a crate for it, which I've added to [clarcharr/version-sort]. I'm not sure how we'd add this type of functionality to rustdoc specifically, but I figured that I'd mention that I have created the code that would do this sort of sorting. (heh)

**Comment by phungleson** [comment] 2017-02-20 09:41
Hehe I think this functionality can be used for more than just in version number, but file name etc.., not sure how to call it though

**Comment by Boddlnagg** [comment] 2017-02-20 15:09
This is known as ["natural sort order"](https://en.wikipedia.org/wiki/Natural_sort_order), and there are at least [two](https://crates.io/crates/natord) [crates](https://crates.io/crates/natural_sort) for this, though I don't know about their quality.

**Comment by ranma42** [comment] 2017-02-20 15:50
Notice that although for human-written code the suggested order would in general be better, it might be a regression if the "number" is not decimal (which might happen for example for machine-generated types) as `T000` `T010` `T0A0` `T110` would then not be considered sorted.

**Comment by clarcharr** [comment] 2017-02-20 15:52
@ranma42 Check out the crate I linked; I specifically track leading zeroes so that 001 comes before 01, before 1, before 10.

**Comment by clarcharr** [comment] 2017-02-20 15:55
Floating point strings don't sort by value (i.e. 2.2 < 2.10) which is why I'd consider this a version sort, not a numerical sort. For rustdoc this doesn't matter either way because periods can't be in identifiers.

**Comment by ranma42** [comment] 2017-02-20 18:15
@clarcharr The issue is not with leading zeros, but with non-digit characters. For example, would `T100` sort before `T1A0`? (if you interpret the numbers in hexadecimal, i.e. as 0x100 and 0x1A0, this is the obvious sorting, but if you split at every non-digit, then it is not).

**Comment by clarcharr** [comment] 2017-02-21 02:31
Digits come before letters lexically, so, that'd still work as expected. Although I think that automatically coercing `a-f` as numbers has the ability for too many false positives.

For example, `"String1" < "StringArgument" < "String10" just doesn't make any sense visually, and doesn't make sense to me.

**Comment by ranma42** [comment] 2017-02-21 08:30
Even though digits come before letters in the lexicographic order, this breaks when you group them. Specifically, the version-sort crate seem to tokenize the strings in numeric/non-numeric parts depending on *decimal* digits. This is generally useful, but it might not always be the correct choice. For example, according to version-sort, ` Version::new("T010") < Version::new("T0A0")` is false.

I agree that the comparison `"String1" < "StringArgument" < "String10"` is meaningless, but the comparison `"T000" < "T010" < "T0A0" < "T110"` is rather reasonable to me, especially under the assumption that the 3-digit hexadecimal number has not been written by a human but automatically emitted by some code generator.

A better way to choose how the items should be sorted would involve looking at all of them together and trying to understand which patterns have been used to construct them, but this is obviously much more complicated than just comparing them in a pairwise fashion.

**Comment by ranma42** [comment] 2017-02-21 08:37
My concern might actually not be much of a problem in practice (especially if it only affects auto-generated code, as that will often miss documentation).

So far, the main example of documentation that would be affected by this change (that I know of) are the 8/16/32/64 types in the std docs; they would certainly benefit from being sorted naturally.

**Comment by keeperofdakeys** [comment] 2017-02-21 10:46
If this is only for `Trait1`, `Trait2`, etc. Could it work with these rules?

1. Only apply to numbers at the end of a string
2. The prefix must match
3. Don't apply to numbers starting with `0`

This would mean `T1A0` and `T120` would compare the same as they do today, but `T140` and `T8` would compare naturally.

**Comment by ranma42** [comment] 2017-02-21 14:22
@keeperofdakeys yes, your ruleset would definitely work (at least it would cover both my examples and the ones by the OP), assuming that it is applied to all the items as a whole. Otherwise you would end up using two different comparison functions when sorting `T1A0` `T120` and `T140`.

**Comment by clarcharr** [comment] 2017-02-21 18:30
@keeperofdakeys I like this idea! It would also make the sorting substantially easier to implement:

```
fn sort_key(s: &str) -> (&str, u64) {
    let split = s.bytes().rposition(|b| b < b'0' || b'9' < b).unwrap_or(0);
    let strkey = &s[..split];
    let intkey = s[split..].parse().unwrap_or(0);
    (strkey, intkey)
}
```

**Comment by GuillaumeGomez** [comment] 2017-04-14 12:08
Seems this issue has been fixed. Closing it.

**Closed by GuillaumeGomez** 2017-04-14 12:08 UTC
Labels: A-rustdoc, I-enhancement, T-tools
