### ISSUE TITLE
Rust linker crashes on Apple's M1 MAX processors.

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust#91082] opened 2021-11-20 09:46 UTC
Hi, I've got a new computer and Rust is not working here :( 
The machine is MacBook Pro with Apple M1 MAX. I'm using `rustc 1.58.0-nightly (46b8e7488 2021-11-07)`. I'm running the following command:

```
cargo stable install wasm-pack
```

And I got a linker error:
```
error: linking with `cc` failed: exit status: 1
[...]
  = note: 0  0x100314224  __assert_rtn + 128
          1  0x1003197e8  ld::tool::OutputFile::addressAndTarget(ld::Internal const&, ld::Fixup const*, ld::Atom const**) (.cold.1) + 0
          2  0x100253104  ld::tool::OutputFile::addressOf(ld::Internal const&, ld::Fixup const*, ld::Atom const**) + 252
          3  0x100254dfc  ld::tool::OutputFile::applyFixUps(ld::Internal&, unsigned long long, ld::Atom const*, unsigned char*) + 4004
          4  0x100259540  ld::tool::OutputFile::writeAtoms(ld::Internal&, unsigned char*) + 356
          5  0x100250fa4  ld::tool::OutputFile::writeOutputFile(ld::Internal&) + 408
          6  0x100249adc  ld::tool::OutputFile::write(ld::Internal&) + 216
          7  0x1001d71d8  main + 584
          A linker snapshot was created at:
                /tmp/wasm_pack-62a4d5a4ac8d1c70-2021-10-20-103913.ld-snapshot
          ld: Assertion failed: (_mode == modeFinalAddress), function finalAddress, file ld.hpp, line 1190.
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: failed to compile `wasm-pack v0.10.1`, intermediate artifacts can be found at `/var/folders/v9/4h68z3857tvbn5fc2ftkh36c0000gn/T/cargo-installmletYr`
```

[Click here to see the full output](https://pastebin.com/ZfgQDvLN)

**Comment by hkratz** [comment] 2021-11-20 10:09
@rusbot label O-macos O-arm

**Comment by hkratz** [comment] 2021-11-20 10:13
Caused by #90342. As a workaround use `MACOSX_DEPLOYMENT_TARGET=10.7 cargo +stable install wasm-pack`

**Comment by wdanilo** [comment] 2021-11-20 10:36
It works, thank you!!

**Comment by nagisa** [comment] 2021-11-20 23:30
Looks like a…

Duplicate of #90499

**Closed by nagisa** 2021-11-20 23:30 UTC
Labels: O-macos, I-ICE, O-ARM, T-compiler, C-bug
