### ISSUE TITLE
Inclusive ranges (..=) slower than exclusive range + 1 (..n + 1)

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust#131333] opened 2024-10-06 16:36 UTC
I'm not sure why this happens, but ..= generates more instructions than ..n + 1. We should figure out which one is more performant and make both equal. (This question sprouted from rust-lang/rust-clippy#8317)

[Godbolt](https://rust.godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahSAVyVFyKxqiIEh1ZpgDC6embZMQAJnLOAGQImbAA5TwAjbFIQADZyAAd0JWIHJjcPL19E5NShIJDwtiiY%2BJtsOzSRIhZSIgzPbz9yyqFq2qICsMjouOsauoas5oHO4O7i3tiASmt0M1JUTi4AUh8AZhWAVgAhJnQAfTZjYEZtgBEVrQBBBLMIgGoaJif0dAgqB7N1n2mHlYA7DsrtcHmDXqQHi9gg8tAA6OEEf4%2BHY8f5AkEJUjBIj0JhgSBrHyAvaAy4%2BX4rdbAm7g9GXG5krizejcLb8by8fjobgAJQsRAeSnmi2wyPWfHIRG0zNmAGsQFstIZuNJ%2BGxFcrOTpyDyuPwlCBldKuDpZnBYCgMDh8MQyJRqHRGKwONxJYJhGIJJwZHJhMo1JpTXpskYTCBzJZrNhbPZHBBnEMmv4mJgukUSn0kik4%2Bl3I1stm8kx0z1StHY1VRknsi1c%2B06qXJuXLB0ayMOk3MzM5gsltw1ptdvsjiczlsGbd7k8XoJ3p9vr90TTQeDBJDoS94XCqeckSTMdjhHiCRAiSSmGSidMqSu6VfGQDzsyVVx2eRtdy%2BQKhSKluKfH4E0zVmJBsBYHAYggFlVXVTUPxlXVuANI0pRlaZ5Xg1kuHWDlEL1ID0PIC1kDQdA2ASBhogdCAMAoqiYiYAhgCQXEAE8BAYIhokNCAIkQiJglqNi3X4QTWFINiAHkIl0CoTUlOiOGEKSmHoETg3IHAIjMYAXAkehDS5LTsGOExJE0whSHkggADdsCMnVsHUCozG40TKGEGNEPoAgIlIYS3BwRCiGxDVjPs0gImSbBzlMsdglAYNZhoIxgCUAA1AhsAAdykhJmA8j1RHESRfWKgMNEQ/QeEME4IwFQw/MNSBZnQBJcyMgBaNwOq6xh7PoXdcN1SLsRwFqoBdThsEIXNyFsiQzGWHwtB8PgMIrGz40TfNhniQJxgzXpfSLXN23iM60i7E7ZDrKs2z2poyhjbamAbMZCjLKQ7urJ7fDKUYbpiGRZmFPsfRgt88M0vUHkjIhUChZjWPUh4IFtEhIUHHhpkI5LMJ8LZXzVBDYeQ6xUOAl8SIgK1yMoxgKCoWiGYYkAmJY9jOPobjSF4/jNPE4SPOFySZLkuwPKU5giFU9TEO03T9PoQyPJwMzTmWHUrJs%2BzHP4ZzXPc4ycW8zTfP8wKsG1oCwo8yLopUOLNd88NkoENLMuyvKCs5d15C9MrZAqlQqs0/Q/DDUxGstya2o6tJut6oh%2BuwQbhu5MaCAm%2BAIGmkBZuLBalpWtaNrB17Wm8BNUxrWrDq%2B5sDCuoR65yHNrqO77avuto/sybxe6r%2Bsge75ve4HgtJ87cfM1x3tRV8KH30/JCuHhgUkc51G2PRzGyAAvG0IJ8gwIg3poPIBUiZJmGdQIynjXQqHALJh%2BKepzbIpSRxpCAA%3D%3D)

<details><summary>..n + 1</summary>

```asm
foo:
        cmp     edi, -1
        je      .LBB0_4
        push    rbp
        push    r15
        push    r14
        push    r13
        push    r12
        push    rbx
        sub     rsp, 72
        mov     ebx, edi
        inc     ebx
        xor     ebp, ebp
        lea     r13, [rip + .L__unnamed_1]
        lea     r15, [rsp + 8]
        lea     r14, [rsp + 24]
        mov     r12, qword ptr [rip + std::io::stdio::_print::h560473ec6c8cb59b@GOTPCREL]
.LBB0_2:
        mov     dword ptr [rsp + 4], ebp
        inc     ebp
        lea     rax, [rsp + 4]
        mov     qword ptr [rsp + 8], rax
        mov     rax, qword ptr [rip + core::fmt::num::imp::<impl core::fmt::Display for u32>::fmt::hc9449d7f3b1b8610@GOTPCREL]
        mov     qword ptr [rsp + 16], rax
        mov     qword ptr [rsp + 24], r13
        mov     qword ptr [rsp + 32], 2
        mov     qword ptr [rsp + 56], 0
        mov     qword ptr [rsp + 40], r15
        mov     qword ptr [rsp + 48], 1
        mov     rdi, r14
        call    r12
        cmp     ebx, ebp
        jne     .LBB0_2
        add     rsp, 72
        pop     rbx
        pop     r12
        pop     r13
        pop     r14
        pop     r15
        pop     rbp
.LBB0_4:
        ret

.L__unnamed_2:
        .byte   10

.L__unnamed_1:
        .quad   1
        .zero   8
        .quad   .L__unnamed_2
        .asciz  "\001\000\000\000\000\000\000"

```

</details>

<details><summary>..=n</summary>

```asm
foo:
        push    rbp
        push    r15
        push    r14
        push    r13
        push    r12
        push    rbx
        sub     rsp, 72
        mov     ebx, edi
        xor     ebp, ebp
        lea     r15, [rsp + 8]
        lea     r14, [rsp + 24]
        mov     r12, qword ptr [rip + std::io::stdio::_print::h560473ec6c8cb59b@GOTPCREL]
.LBB0_1:
        mov     r13d, ebp
        cmp     ebp, ebx
        adc     ebp, 0
        mov     dword ptr [rsp + 4], r13d
        lea     rax, [rsp + 4]
        mov     qword ptr [rsp + 8], rax
        mov     rax, qword ptr [rip + core::fmt::num::imp::<impl core::fmt::Display for u32>::fmt::hc9449d7f3b1b8610@GOTPCREL]
        mov     qword ptr [rsp + 16], rax
        lea     rax, [rip + .L__unnamed_1]
        mov     qword ptr [rsp + 24], rax
        mov     qword ptr [rsp + 32], 2
        mov     qword ptr [rsp + 56], 0
        mov     qword ptr [rsp + 40], r15
        mov     qword ptr [rsp + 48], 1
        mov     rdi, r14
        call    r12
        cmp     r13d, ebx
        jae     .LBB0_3
        cmp     ebp, ebx
        jbe     .LBB0_1
.LBB0_3:
        add     rsp, 72
        pop     rbx
        pop     r12
        pop     r13
        pop     r14
        pop     r15
        pop     rbp
        ret

.L__unnamed_2:
        .byte   10

.L__unnamed_1:
        .quad   1
        .zero   8
        .quad   .L__unnamed_2
        .asciz  "\001\000\000\000\000\000\000"

```

</details>

**Comment by saethlin** [comment] 2024-10-06 17:00
This is a duplicate of https://github.com/rust-lang/rust/issues/45222.

**Closed by saethlin** 2024-10-06 17:00 UTC
Labels: needs-triage, C-optimization
