### ISSUE TITLE
rustdoc prints types in traits different than rustc

### ISSUE THREAD

**Issue by ralfjung-e** [rust-lang/rust#22000] opened 2015-02-06 11:58 UTC
The syntax that rustdoc uses to refer to types declared internally within a trait ("associated types"), is different from what rustc expects. This is fairly confusing for a newbie, who tries to learn the language by example - in particular, by looking at how the standard API does things.

For example, the documentation of the Iterator trait <http://doc.rust-lang.org/std/iter/trait.Iterator.html> refers to the type "Item" simply by "Item", but I have to write "Self::Item" for this code to actually compile.

**Comment by tomjakubowski** [comment] 2015-02-06 12:33
This is a dupe of #21445, sort of (see https://github.com/rust-lang/rust/issues/21145#issuecomment-70048958).

In any case this specific aspect of #21445 will be closed by #21999.

**Comment by alexcrichton** [comment] 2015-02-06 16:35
Closing as a dupe of #21145

**Closed by alexcrichton** 2015-02-06 16:35 UTC
