### ISSUE TITLE
New c_str/ffi makes error buffer operations harder than necessary

### ISSUE THREAD

**Issue by viraptor** [rust-lang/rust#20928] opened 2015-01-11 07:42 UTC
After the c_str/ffi interface changed in https://github.com/rust-lang/rust/issues/20444 operations which return strings into preallocated buffer are harder to handle.

Specifically calls like `prctl` can take form `prctl(int, char[16])`. This could be handled by:
```
let mut name = [0 as u8; 17];
let res = prctl(PrctlOption::PR_GET_NAME as c_int, name.as_mut_ptr() as c_ulong, 0, 0, 0);
(res, CString::from_slice(name.as_slice()))
```

But the name is likely to contain zeros and there's no simple "construct CString until the first zero" function. This shouldn't be a big issue in case of a simple CString type, but since this one is meant specifically for FFI, I think such constructor should be supported.

(rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800))

**Comment by shepmaster** [comment] 2015-01-11 22:37
Related to #20475?

**Comment by viraptor** [comment] 2015-01-12 00:33
I think it's close. The same function could probably satisfy both issues.
The operation could construct the cstring from a slice/vec up to the first
zero, or until `max_length` - whichever happens first.

**Comment by alexcrichton** [comment] 2015-01-12 16:58
It sounds like you don't necessarily want to return a `CString` but rather a `Vec<u8>`. are you later passing the string back into other C functions? I'd be thinking of something like:

```rust
let mut name = [0 as u8; 17];
let res = prctl(PrctlOption::PR_GET_NAME as c_int, name.as_mut_ptr() as c_ulong, 0, 0, 0);
(res, ffi::c_str_to_bytes(name.as_ptr()).to_vec())
```

**Comment by viraptor** [comment] 2015-01-16 20:43
I think it's better for the interface if I return a cstring, since that's
exactly what I get back. Vec would suggest some binary data. I can't make
it a proper string since the caller will know the encoding.
I think the interface would need more comments about the nulls, length,
etc. in my library, instead of just providing cstring.
Am I mistaken here?

**Comment by alexcrichton** [comment] 2015-01-16 20:52
> Vec would suggest some binary data.

To rust, however, C strings *are* just binary data. The `CString` type is basically just a type that derefs to `[u8]`. The only added benefit of `CString` over `Vec<u8>` is a static guarantee that there are no interior nul bytes (which might be useful if you're handing the data right back to C).

**Comment by alexcrichton** [comment] 2015-01-19 00:22
Looking back at this, I'm going to close this as a dupe of #20475 as a `from_slice_truncate` method looks to be what'd fit the ticket here.

**Closed by alexcrichton** 2015-01-19 00:22 UTC
Labels: A-ffi, A-libs
