### ISSUE TITLE
linker error "undefined symbol: __aeabi_uidiv" for target thumbv6m-none-eabi

### ISSUE THREAD

**Issue by starblue** [rust-lang/rust#60782] opened 2019-05-13 12:29 UTC
Beginning with nightly-2019-05-10 I get the following linker error:
```
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "-L" "/home/juergen/.rustup/toolchains/nightly-2019-05-10-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "/home/juergen/rust/dust/dust-test/target/thumbv6m-none-eabi/release/deps/test_uart-988eaff94921fb1c.test_uart.67ne5b40-cgu.0.rcgu.o" "-o" "/home/juergen/rust/dust/dust-test/target/thumbv6m-none-eabi/release/deps/test_uart-988eaff94921fb1c" "--gc-sections" "-L" "/home/juergen/rust/dust/dust-test/target/thumbv6m-none-eabi/release/deps" "-L" "/home/juergen/rust/dust/dust-test/target/release/deps" "-L" "/home/juergen/.rustup/toolchains/nightly-2019-05-10-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib" "--start-group" "--end-group" "-Bstatic" "/home/juergen/.rustup/toolchains/nightly-2019-05-10-x86_64-unknown-linux-gnu/lib/rustlib/thumbv6m-none-eabi/lib/libcompiler_builtins-afe13c5355265d4c.rlib" "-Tldscripts/lpc802m001.ld" "-Lldscripts" "-Map=output/lpc802m001_test-uart.map" "-Bdynamic"
  = note: rust-lld: error: undefined symbol: __aeabi_uidiv
          >>> referenced by num.rs:204 (src/libcore/fmt/num.rs:204)
          >>>               /home/juergen/rust/dust/dust-test/target/thumbv6m-none-eabi/release/deps/test_uart-988eaff94921fb1c.test_uart.67ne5b40-cgu.0.rcgu.o:(core::fmt::num::imp::fmt_u32::h2131a43fb24cc589)
```

**Comment by jonas-schievink** [comment] 2019-05-13 13:04
Please post a way to reproduce this. What code are you trying to build?

**Comment by starblue** [comment] 2019-05-13 13:27
This is test-code for microcontrollers using my own framework called dust.
I now uploaded it to https://github.com/starblue/dust .
To reproduce go into the `dust-test` subdirectory and run `make clean && make test-uart` with some version of nightly (nightly is needed due to inline assembly). For example, I did
```
rustup run nightly-2019-05-10-x86_64-unknown-linux-gnu bash -c "make clean && make test-uart"
```

**Comment by hellow554** [comment] 2019-05-13 14:41
Maybe these two are related? https://github.com/rust-lang/rust/issues/60747

**Comment by jonas-schievink** [comment] 2019-05-13 14:46
(removing regression label since this never built on stable)

**Comment by mati865** [comment] 2019-05-13 14:46
https://github.com/rust-lang/rust/pull/60491 was merged on 2019-05.09 and modifies `compiler-builtins`.

cc @alexcrichton

**Comment by alexcrichton** [comment] 2019-05-14 19:30
Thanks for the report @starblue and the cc @mati865, this should be fixed in https://github.com/rust-lang-nursery/compiler-builtins/pull/290.

**Comment by pnkfelix** [comment] 2019-05-16 11:33
triage: P-high. (I'm not 100% sure that prioritization is warranted for this target, but given that it may already be fixed, I don't mind err'ing on the side of too-high a priority.)

**Closed** 2019-05-17 19:00 UTC
Labels: A-linkage, C-bug, O-ARM, P-high, T-compiler
