### ISSUE TITLE
include! doesn't work with inner attributes

### ISSUE THREAD

**Issue by Nugine** [rust-lang/rust#75475] opened 2020-08-13 01:52 UTC
I tried this code:

```rust
// main.rs
include!("./lints");

fn main(){
	dbg!("hello");
}
```

```
// lints
#![forbid(unsafe_code)]
```

I expected to see this happen: lints should take effect.

Instead, this happened: compile errors.

```
error: an inner attribute is not permitted in this context
 --> ./lints:1:1
  |
1 | #![forbid(unsafe_code)]
  | ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: inner attributes, like `#![no_std]`, annotate the item enclosing them, and are usually found at the beginning of source files. Outer attributes, like `#[test]`, annotate the item following them.

error: expected item after attributes
 --> ./lints:1:1
  |
1 | #![forbid(unsafe_code)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.2 (d3fb005a3 2020-07-31)
binary: rustc
commit-hash: d3fb005a39e62501b8b0b356166e515ae24e2e54
commit-date: 2020-07-31
host: x86_64-unknown-linux-gnu
release: 1.45.2
LLVM version: 10.0
```

**Comment by petrochenkov** [comment] 2020-08-13 12:31
Duplicate of https://github.com/rust-lang/rust/issues/66920.

**Closed by petrochenkov** 2020-08-13 12:31 UTC
Labels: C-bug
