### ISSUE TITLE
`#[deriving(Clone)]` et al. should ask for `Clone` bounds on fields, not on generic parameters

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#19839] opened 2014-12-14 15:03 UTC
For example:

``` rust
#[deriving(Clone)]
struct Filter<A, I, P> where I: Iterator<A>, P: FnMut(&A) -> bool {
    it: I,
    p: P,
}
```

expands to:

``` rust
impl<A: Clone, I: Clone, P: Clone> Clone for Filter<A, I, P> where /* .. */ { /* .. */ }
```

The `A: Clone` bound is incorrect. Instead `deriving` should expand to:

``` rust
impl<A, I, P> Clone for Filter<A, I, P> where
    I: Clone,
    P: Clone,
    /* .. */ { /* .. */ }
```

This requires generalized `where` clauses to handle more complex fields like `&'a T: Clone`.

@nikomatsakis Are where clauses like `&'a int: Clone` (note: no generic parameter) going to be allowed? If not, writing the syntax extension is going to be harder.

**Comment by goffrie** [comment] 2015-02-06 01:37
FWIW, this bug is basically the same as #7671.

**Comment by alexcrichton** [comment] 2015-02-09 17:27
I believe @goffrie is right in that this is a dupe of #7671

**Closed by alexcrichton** 2015-02-09 17:27 UTC
Labels: A-syntaxext

**Comment by apasel422** [comment] 2015-03-28 21:22
This isn't really a dupe of #7671, because this is specifically about fields. For example, the following does not work:

foo.rs:
```rust
#[derive(Clone)]
pub struct Foo<'a, T: 'a>(&'a T);

pub struct Bar;

fn main() {
    let foo = Foo(&Bar);
    foo.clone();
}
```
Output:
```
> rustc --version
rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-27)
> rustc foo.rs
foo.rs:8:9: 8:16 error: type `Foo<'_, Bar>` does not implement any method in scope named `clone`
foo.rs:8     foo.clone();
                 ^~~~~~~
foo.rs:8:16: 8:16 help: methods from traits can only be called if the trait is implemented and in scope; the following trait defines a method `clone`, perhaps you need to implement it:
foo.rs:8:16: 8:16 help: candidate #1: `core::clone::Clone`
```
Supporting this would reduce a lot of boilerplate, especially for by-reference iterators.

**Comment by P1start** [comment] 2015-06-01 10:19
I think this should be reopened—even though #7671 is fixed, @apasel422’s example still doesn’t work, although it should.

**Comment by Eh2406** [comment] 2017-09-03 14:12
The FIXME refers to this issue: https://github.com/rust-lang/rust/blob/master/src/liballoc/binary_heap.rs#L929

If this is fixed, we can remove the FIXME. If we can't remove the FIXME, than we should reopen the issue.

**Comment by eddyb** [comment] 2017-09-03 14:21
@Eh2406 I believe the current issue is #26925.
