### ISSUE TITLE
Mac M1 LD_DYLD_PATH= causes execution to fail killed, dtrust failed to execute /tmp/main: Malformed Mach-o file

### ISSUE THREAD

**Issue by exfly** [rust-lang/rust#134303] opened 2024-12-14 12:11 UTC
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}
```

I expected to see this happen: *explanation*

```bash
export LD_DYLD_PATH=
rustc main.rs && ./main

Hello, world!
```

Instead, this happened: *explanation*

```bash
export LD_DYLD_PATH=
rustc main.rs && ./main

zsh: killed     ./main
```

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: aarch64-apple-darwin
release: 1.83.0
LLVM version: 19.1.1
```

```bash
./dtrust.sh ./main
dtrace: system integrity protection is on, some features will not be available

dtrace: failed to execute /tmp/main: Malformed Mach-o file
```

**Comment by unsurmisingan914** [comment] 2024-12-14 13:00
cn blog here https://exfly.github.io/rustc-compiled-bin-killed-on-mac-m1/

**Comment by exfly** [comment] 2024-12-14 13:01
cn blog here https://exfly.github.io/rustc-compiled-bin-killed-on-mac-m1/

**Comment by haoqixu** [comment] 2024-12-14 15:42
I think this is caused by the old linker of macOS. The linker will set `LC_LOAD_DYLINKER` command as the value of the `LD_DYLD_PATH` environment variable (see https://github.com/apple-oss-distributions/ld64/blob/main/src/ld/Options.cpp#L4676-L4678).

I can reproduce this with both `clang` and `gcc` with the old linker:
```
@(#)PROGRAM:ld  PROJECT:ld64-857.1
BUILD 23:13:24 May  7 2023
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 14.0.3, (clang-1403.0.22.14.1) (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 14.0.3 (tapi-1403.0.5.1)
```

**Comment by haoqixu** [comment] 2024-12-14 15:55
Also, the problem I reproduced using the old linker was on an Intel MacBook, so this issue is unrelated to M1.

**Comment by madsmtm** [comment] 2024-12-15 01:11
Yeah, this is outside the scope of `rustc`. You're explicitly telling the linker to overwrite the dynamic linker path to something invalid, which will of course fail.

It looks like you're using nixpkgs? I'm not very good at reading shell scripts, but I find it feasible that something is wrong [here](https://github.com/NixOS/nixpkgs/blob/e4cef11b7889c3dd0ff200d8467f16c993f8b5e7/pkgs/build-support/bintools-wrapper/default.nix#L287), perhaps file an issue with them instead?

**Comment by jieyouxu** [comment] 2024-12-15 18:24
Closing as not-actionable.

**Closed** 2024-12-15 18:25 UTC
Labels: O-macos
