### ISSUE TITLE
Internal compiler error during compilation - a nice message with compiler sourcecode line number

### ISSUE THREAD

**Issue by Pand9** [rust-lang/rust#80321] opened 2020-12-23 03:39 UTC
I got the error below. The compiled project is pretty big, there is no way to include it. The compiled code has started compiling again after `cargo clean`. I'm submitting because of a nice log message encouraging me to do so.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (0f6f2d681 2020-12-06)
binary: rustc
commit-hash: 0f6f2d681b39c5f95459cd09cb936b6ceb27cd82
commit-date: 2020-12-06
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_middle/src/ty/query/mod.rs:235:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (0f6f2d681 2020-12-06) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

UPDATE:
Got this problem again, this time there is some more:
```
query stack during panic:
end of query stack
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `LLVMing`,
 right: `Codegenning`', /rustc/0f6f2d681b39c5f95459cd09cb936b6ceb27cd82/compiler/rustc_codegen_ssa/src/back/write.rs:1425:21
```

I'm updating to today's nightly now.

**Comment by Aaron1011** [comment] 2020-12-23 04:03
This looks like a duplicate of https://github.com/rust-lang/rust/issues/80054, and should be fixed in the latest nightly.

**Comment by camelid** [comment] 2020-12-23 04:38
Actually I think it's a duplicate of #79661. I'm closing the issue, but definitely re-open if it happens again!

**Closed by camelid** 2020-12-23 04:38 UTC
Labels: C-bug, I-ICE, T-compiler
