### ISSUE TITLE
ICE： NLL bug?

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang/rust#49616] opened 2018-04-03 08:07 UTC
```rust
#![feature(nll)]

use std::cell::RefCell;

fn main() {
    let s = RefCell::new(Some(10));
    if let Some(n) = *(s.borrow_mut()) {
        println!("num: {}", n);
    }
}
```

I thought the code should be compiled  with nll feature ,

but got the following errors:

```rust
Compiling playground v0.0.1 (file:///playground)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (06fa27d7c 2018-04-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

[play](https://play.rust-lang.org/?gist=83af984369c22f865285a181d7d6a2d2&version=nightly)

the following code is good:

```rust
#![feature(nll)]

use std::cell::RefCell;

fn main() {
    let s = RefCell::new(Some(10));
    if let Some(n) = *(s.borrow_mut()) {
        println!("num: {}", n);
    }
    ;
}
```

**Comment by nikomatsakis** [comment] 2018-04-10 13:35
Maybe fixed by @spastorino in https://github.com/rust-lang/rust/pull/49808

**Comment by spastorino** [comment] 2018-04-10 14:09
#49808 fixes this issue.

The output you get is ...

```
[santiago@archlinux tmp]$ rustc +stage1 test.rs 
error[E0597]: `s` does not live long enough
  --> test.rs:7:24
   |
7  |     if let Some(n) = *(s.borrow_mut()) {
   |                       -^--------------
   |                       ||
   |                       |borrowed value does not live long enough
   |                       borrow may end up in a temporary, created here
...
10 | }
   | -
   | |
   | borrowed value only lives until here
   | temporary later dropped here, potentially using the reference

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

**Comment by ZhangHanDong** [comment] 2018-04-10 14:40
@spastorino 

Why is it still error with NLL ?

**Comment by spastorino** [comment] 2018-04-10 19:03
@ZhangHanDong I was just paying attention to the thing not ICEing :). Seems like there's something wrong /cc @nikomatsakis

**Comment by spastorino** [comment] 2018-04-10 19:14
@ZhangHanDong @nikomatsakis explained here the bug https://github.com/rust-lang/rust/issues/46413#issuecomment-362331690 so besides from the ICE there's something else going on :)

**Comment by ZhangHanDong** [comment] 2018-04-11 01:39
@nikomatsakis 

Why is it still error with NLL in [#49808](https://github.com/rust-lang/rust/pull/49808)?
Can you help me explain the puzzle？

**Comment by KiChjang** [comment] 2018-04-30 10:52
@ZhangHanDong I'm inclined to believe that this is the drop check rule in action again, because if you add a semicolon right after your if-let statement, the code compiles:

```rust
#![feature(nll)]

use std::cell::RefCell;

fn main() {
    let s = RefCell::new(Some(10));
    if let Some(n) = *(s.borrow_mut()) {
        println!("num: {}", n);
    };
}
```

In other words, the `BorrowMut` that the `borrow_mut` call generates does not _strictly outlive_ the `n` variable binding (they are dropped at the same time). See further details [here](https://doc.rust-lang.org/beta/nomicon/dropck.html).

**Comment by KiChjang** [comment] 2018-04-30 10:55
Closing as a duplicate of #22321.

**Closed by KiChjang** 2018-04-30 10:55 UTC
Labels: A-NLL, A-destructors, I-ICE, NLL-complete, WG-compiler-nll

**Comment by pnkfelix** [comment] 2018-09-21 13:50
(it is more specifically a duplicate of #21114)

**Comment by pnkfelix** [comment] 2019-09-20 10:02
(or really, at this point I might argue its a duplicate of #46413 ...)
