### ISSUE TITLE
Transient bug. Error asked I submit as bug.

### ISSUE THREAD

**Issue by jreindel** [rust-lang/rust#87929] opened 2021-08-10 21:12 UTC
Doing a cross compile build of several included KubOS service and got an error while building one.
entered:
`cargo build -p telemetry-service --target arm-unknown-linux-gnueabihf --release` 
as part of a script that runs the build for 11 crates.
stdout:
```sh
   Compiling syn v1.0.7
   Compiling libsqlite3-sys v0.16.0
   Compiling filetime v0.2.7
   Compiling xattr v0.2.2
   Compiling tar v0.4.26
   Compiling synstructure v0.12.1
   Compiling serde_derive v1.0.102
   Compiling failure_derive v0.1.6
   Compiling diesel_derives v1.4.1
   Compiling failure v0.1.6
   Compiling serde v1.0.102
   Compiling diesel v1.4.3
   Compiling log v0.4.8
   Compiling indexmap v1.3.0
   Compiling serde_json v1.0.41
   Compiling serde-value v0.5.3
   Compiling serde_yaml v0.8.11
   Compiling serde_urlencoded v0.6.1
   Compiling toml v0.4.10
   Compiling tokio-io v0.1.12
   Compiling mio v0.6.19
   Compiling log v0.3.9
   Compiling tokio-threadpool v0.1.16
   Compiling want v0.2.0
   Compiling tungstenite v0.9.1
   Compiling juniper v0.11.1
   Compiling mime v0.2.6
   Compiling tokio-codec v0.1.1
   Compiling h2 v0.1.26
   Compiling tokio-reactor v0.1.10
   Compiling mio-uds v0.6.7
   Compiling tokio-fs v0.1.6
   Compiling log4rs v0.8.3
   Compiling mime_guess v1.8.7
   Compiling tokio-tcp v0.1.3
   Compiling tokio-uds v0.2.5
   Compiling tokio-udp v0.1.5
   Compiling multipart v0.16.1
   Compiling tokio v0.1.22
   Compiling log4rs-syslog v3.0.3
   Compiling hyper v0.12.35
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=z -C panic=abort -C codegen-units=1 -C linker=/usr/bin/bbb_toolchain/usr/bin/arm-linux-gcc --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `log4rs-syslog`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Ran the build again and it compiled fine. Did a cargo clean and then built again. Still fine.
### Meta
Using the latest stable version

`rustc --version --verbose`:
```
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-unknown-linux-gnu
release: 1.39.0
LLVM version: 9.0
```

### Backtrace
Ran again with RUST_BACKTRACE=1 set to get the backtrace and it completed successfully; no error. So good for me, bad for bug reporting.
Ran cargo clean and the build command again, but it was successful again.

**Comment by asquared31415** [comment] 2021-08-11 00:48
That is not the latest stable version, that version is over a year and a half old.  The latest stable version is 1.54.0, released on 2021-07-29.  Try updating with `rustup update` and seeing if the bug persists.

**Comment by jyn514** [comment] 2021-08-16 04:28
@asquared31415 well, since it's transient, it won't reproduce either way.

I'm going to close this since it's not clear what went wrong, and we wouldn't know even if it had been fixed. Feel free to re-open if it happens again.

**Closed by jyn514** 2021-08-16 04:28 UTC
Labels: C-bug
