### ISSUE TITLE
Wrong program interpreter on musl targets with cc

### ISSUE THREAD

**Issue by Yuri6037** [rust-lang/rust#94864] opened 2022-03-11 20:31 UTC
When a cargo project, which depends on the cc crate and a C++ runtime, is built on an musl target, the generated binary is broken: the program interpreter is set to "/lib/ld-linux-aarch64.so.1" instead of "/lib/ld-musl-aarch64.so.1".

After having posted an issue in cc crate (https://github.com/alexcrichton/cc-rs/issues/635) it appears the problem is rustc choosing the wrong linker.

**Comment by nagisa** [comment] 2022-07-14 20:38
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/82519. `rustc` has no heuristics to select a target specific linker and today it is the responsibility of the invoker to set up the environment, the flags and their build system accordingly to point them at the appropriate tools, including the linker.

There are some people who think adding such heuristics is a good idea. I don’t necessarily agree, but either way it would be a change worth an RFC.

**Closed by nagisa** 2022-07-14 20:38 UTC
