### ISSUE TITLE
regression: the size for values of type `T` cannot be known

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#125195] opened 2024-05-17 01:17 UTC
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/cycle_map-0.2.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/sharded-0.2.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Zersya.invoice-billing-server/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/alvarotolentino.docmanager-rust/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/pykulytsky.kvs/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/thalber.bronze_loop/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/scherben-map-0.1.10/log.txt

```
[INFO] [stdout] error[E0277]: the size for values of type `T` cannot be known at compilation time
[INFO] [stdout]   --> src/group_map.rs:52:11
[INFO] [stdout]    |
[INFO] [stdout] 51 | pub(crate) fn right_with_right_id<T: PartialEq + ?Sized>(id: ID) -> impl Fn(&RightItem<T>) -> bool {
[INFO] [stdout]    |                                   - this type parameter needs to be `Sized`
[INFO] [stdout] 52 |     move |x| x.id == id
[INFO] [stdout]    |           ^ doesn't have a size known at compile-time
[INFO] [stdout]    |
```

probably #123531, cc @compiler-errors should be intended breakage

**Comment by compiler-errors** [comment] 2024-05-17 01:22
Surprisingly more breakage than #123531, perhaps we should be doing craterbot-test instead of cratebot-check for types PRs. I don't think we should unland the PR tho.

**Comment by lqd** [comment] 2024-05-17 06:38
> perhaps we should be doing craterbot-test instead of cratebot-check

You mean, because you want explicitly codegen to happen in case there are errors late? Or because these cases were missing from #123531's results? It seems at least the first error was present (but invisible) in the crater run. 

I wonder if cycle_map-0.2.0 may have denied warnings or something. In #123531's results, it failed to build both before and after, but failed with a new E0277. No status change, so it wasn't flagged as a regression:

```json
{       
            "name": "cycle_map-0.2.0",
            "url": "https://crates.io/crates/cycle_map/0.2.0",
            "krate": {
                "Registry": {
                    "name": "cycle_map",
                    "version": "0.2.0"
                }
            },  
            "status": "",
            "res": "build-fail",
            "runs": [
                {
                    "res": "build-fail:compiler-error(unused_imports)",
                    "log": "master%2330840c53f414b753cb08f14620906572f88dda4b/reg/cycle_map-0.2.0"
                },
                {
                    "res": "build-fail:compiler-error(E0277, unused_imports)",
                    "log": "try%2318fb860b8a8e7ca508746882328061d0fe352543/reg/cycle_map-0.2.0"
                }
            ]
        },  
```

Beta crater runs cap lints while most crater runs don't, maybe doing that would slightly widen the reach in t-types runs.

(I gotta run but I'll check the other crates later today.)

**Comment by lqd** [comment] 2024-05-17 09:31
- `sharded-0.2.1`: known and errs opened a PR to fix it
- `Zersya.invoice-billing-server`: marked build-fail for unknown reason, both before and after; but was actually failing because of `proc-macro2-1.0.46`, before reaching the PR's change. I think it may be because of the nightly feature detection? I'm imagining this: if the PR run was seen as a nightly, proc-macro2 enabled the `proc_macro_span_shrink` nightly feature flag and that caused the failure; while this didn't happen for the beta run, proc-macro2 successfully built, and we reached the PR's change.
- `alvarotolentino.docmanager-rust`: marked build-fail for unknown reason, both before and after; didn't build on nightly when https://github.com/rust-lang/rust/pull/123531 landed (a few "implementation is not general enough" errors in sqlx models) and these errors bisect to https://github.com/rust-lang/rust/pull/119820 instead, and was in that PR's crater regressions.
- `pykulytsky.kvs`: I believe this is nightly feature detection again, with `ahash-0.7.7` enabling `feature(stdsimd)`, causing the build to fail in the PR crater run.
- `thalber.bronze_loop`: same as the above, with `ahash-0.7.6`.
- `scherben-map-0.1.10`: marked as build fail for unknown reason, but the failure is actually in a dependency: `sharded-0.1.0`, a different rev of the first known item above.

**Comment by apiraino** [comment] 2024-10-15 09:01
Closing since regression is mentioned in the release notes

**Closed by apiraino** 2024-10-15 09:01 UTC
Labels: T-compiler, regression-from-stable-to-stable
