### ISSUE TITLE
Remove TLS dependency from async/await

### ISSUE THREAD

**Issue by cavedweller** [rust-lang/rust#62918] opened 2019-07-23 23:32 UTC
Futures currently have a dependency on TLS for storing a pointer to` Context<'_>`.
https://github.com/rust-lang/rust/blob/master/src/libstd/future.rs#L116

This makes usage in `no_std` environments quite difficult.

**Comment by cavedweller** [comment] 2019-07-23 23:33
I would like to tackle this since it's blocking a personal project.

cc/ @cramertj @eddyb @nikomatsakis @Zoxc

**Comment by xurtis** [comment] 2019-07-24 21:15
Duplicate of rustasync/team#42

**Comment by xurtis** [comment] 2019-07-24 21:25
There's also some additional [background discussion](https://internals.rust-lang.org/t/pre-rfc-generator-resume-args/10011/4) on the rust-internals discourse.

**Comment by cramertj** [comment] 2019-07-24 21:45
> Duplicate of rustasync/team#42

Not sure if you were suggesting this, but I don't think we should be using other repo's issues to track changes to rustc.

**Comment by xurtis** [comment] 2019-07-24 22:00
I mean, nor do I but that is where most of the existing discussion is. It may be worth closing the other thread to try and avoid splitting the discussion over two issues on separate repos.

**Comment by TomCrypto** [comment] 2019-07-25 14:24
I'm running into this as well. You can work around it and get things working using a hack akin to this https://github.com/SunriseOS/core-futures-tls but it requires overriding libcore for every crate that needs `#![feature(async_await)]` which makes it difficult to do in library crates. TLS-free `async fn`s would be cool.

(I'm sure this workaround is well-known but just posting for future readers that might come across this issue)

**Comment by phil-opp** [comment] 2019-09-15 10:29
@cavedweller

> I would like to tackle this since it's blocking a personal project.

Are you still working on this? I don't have much experience with the Rust compiler, but maybe there is still a way I can help?

**Comment by cavedweller** [comment] 2019-09-15 15:09
Not actively working on it, but i'm interested in giving it a go again, it's a gnarly one. Just moved cross-country and only now just returning to a somewhat stable life pattern.

That being said, if you want to do it and have the time, give it a go please!!

**Comment by phil-opp** [comment] 2019-09-16 20:20
@cavedweller I took a detailed look at your work-in-progress implementation at https://github.com/cavedweller/rust/commit/11c94220a62cd937090e9e6a04e50bb5f434ba6e today. I think the next step would be to adjust the MIR transformation in `librustc_mir/transform/generator.rs`, which transforms generators into "normal" state machines. I assume that we would need to adjust the code generated for `yield` and `resume` to take the new arguments into account. Unfortunately, I have no experience with MIR transformations, so I fear that this is over my head. I'll try to read up about MIR and see if I can understand this transformation, but I can't promise anything.

**Comment by jonas-schievink** [comment] 2020-01-23 19:16
This is essentially a duplicate of https://github.com/rust-lang/rust/issues/56974, so closing in favor of that.

**Closed by jonas-schievink** 2020-01-23 19:16 UTC
Labels: A-async-await, AsyncAwait-Triaged, C-enhancement, T-libs
