### ISSUE TITLE
"failed to build archive" with ImDisk ram disk

### ISSUE THREAD

**Issue by superblaubeere27** [rust-lang/rust#90780] opened 2021-11-10 20:20 UTC
### Problem

Cargo fails to compile on ImDisk ram disk

### Steps

1. Install ImDisk on Windows
2. Create a ramdisk and a cargo package on it
3. Try to compile the package

### Notes

The resulting log of cargo will look like:
```
PS R:\kss> cargo run
warning: could not canonicalize path: 'R:\kss'
warning: could not canonicalize path: 'R:\'
   Compiling autocfg v1.0.1
   Compiling cfg-if v1.0.0
   Compiling winapi v0.3.9
   Compiling bitflags v1.3.2
   Compiling proc-macro2 v1.0.32
   Compiling lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.5
   Compiling syn v1.0.81
   Compiling crossbeam-epoch v0.9.5
error: failed to build archive: function not supported

error: could not compile `bitflags` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
```

**Comment by ehuss** [comment] 2021-11-10 20:34
I have transferred this to rust-lang/rust, as this error is being generated by rustc when generating the archive.

**Comment by ChrisDenton** [comment] 2021-11-10 21:07
ImDisk ram disks cause a lot of problems because they don't implement essential kernel interfaces. Usually it's `canonicalize` that's the problem but the error would be different in that case. Hm... the error message comes from [here](https://github.com/rust-lang/rust/blob/3013b26947e956352f95edfa39251319520cb06c/compiler/rustc_codegen_llvm/src/back/archive.rs#L145) which suggests the error originates in LLVM?

**Comment by ChrisDenton** [comment] 2021-11-10 21:38
On further investigation this does seem to be an LLVM issue. The "function not supported" error seems to be what LLVM maps [`ERROR_INVALID_FUNCTION`](https://github.com/llvm/llvm-project/blob/6c96ceabaf84d149244a15916ce53df95aac3660/llvm/lib/Support/ErrorHandling.cpp#L268) to. Which is indeed what I'd expect from calling `GetFinalPathNameByHandleW` on a driver that doesn't implement the interface.

**Comment by the8472** [comment] 2021-11-11 21:20
To ask the obvious: since people keep stumbling over this every now and then, has anyone reported the issue to ImDisk?

**Comment by ChrisDenton** [comment] 2021-11-11 21:42
It seems like a fundamental issue that they're aware of https://www.ltr-data.se/opencode.html/#ImDisk

> It runs on very old versions of Windows NT as well as modern Windows versions. However, because of this compatibility design and because it emulates disk volumes rather than complete disks, it is not always compatible with all applications and drivers. For instance, you cannot manage things like mount points, drive letters and similar for ImDisk drives using mountvol command line tool or in Disk Management in Windows. As another example, you cannot create or access shadow copies on ImDisk drives. So, applications that use similar Windows features as Disk Management dialog to enumerate disks and disk volumes to find disk properties like sector sizes and similar, might possibly not work as expected with ImDisk drives.
> ...
> If you need full disk emulation, including integration with Disk Management, Volume Shadow Copy Services, mountvol and diskpart command line tools as well as better compatibility with applications, we provide another open source virtual disk project, called Arsenal Image Mounter.

Other than the aforementioned Arsenal Image Mounter there's also free (as in price) software such as Radeon Ramdisk. However, ImDisk has the name recognition so I suspect we'll continue seeing these issues crop up.

**Comment by MolotovCherry** [comment] 2022-11-12 18:43
> It seems like a fundamental issue that they're aware of https://www.ltr-data.se/opencode.html/#ImDisk
> 
> > It runs on very old versions of Windows NT as well as modern Windows versions. However, because of this compatibility design and because it emulates disk volumes rather than complete disks, it is not always compatible with all applications and drivers. For instance, you cannot manage things like mount points, drive letters and similar for ImDisk drives using mountvol command line tool or in Disk Management in Windows. As another example, you cannot create or access shadow copies on ImDisk drives. So, applications that use similar Windows features as Disk Management dialog to enumerate disks and disk volumes to find disk properties like sector sizes and similar, might possibly not work as expected with ImDisk drives.
> > ...
> > If you need full disk emulation, including integration with Disk Management, Volume Shadow Copy Services, mountvol and diskpart command line tools as well as better compatibility with applications, we provide another open source virtual disk project, called Arsenal Image Mounter.
> 
> Other than the aforementioned Arsenal Image Mounter there's also free (as in price) software such as Radeon Ramdisk or Ultra RAMDisk lite. However, ImDisk has the name recognition so I suspect we'll continue seeing these issues crop up.

Thanks to the above comment, I was able to find a solution to these problems.

Download and install the driver for arsenal image mounter, then go to [this page](https://github.com/ArsenalRecon/Arsenal-Image-Mounter/tree/master/Command%20line%20applications) and download aim_ll.zip, then you can create a volume (as a startup script even) like so

```
%~dp0\aim_ll -a -t vm -s 3G -p "/fs:ntfs /q /y" -o rw,fix,hd -m R:
label R: RamDisk
```
See the cmdline details for more info, but with `-s` you can set the size, format as ntfs, make it a hd, etc

This does work with cargo, cause I just tested it!

**Comment by Enselic** [comment] 2023-08-28 07:36
Triage: Closing as duplicate of #48249 since the root cause is the same.

**Closed by Enselic** 2023-08-28 07:36 UTC
Labels: O-windows
