### ISSUE TITLE
"./configure --libdir=/usr/lib64 ; make" fails to build correctly (and install)

### ISSUE THREAD

**Issue by shlomif** [rust-lang/rust#32261] opened 2016-03-15 13:19 UTC
Hi all!

Running ./configure --libdir=/usr/lib64 and make fails to build rustc-1.7.0-src correctly (and I need to do that and other parameters for build Mageia x86-64 v6 RPMs). The following tentative patch fixes the problem.

```
--- rustc-1.7.0/mk/main.mk.fix-rel-lib	2016-03-01 21:18:54.000000000 +0200
+++ rustc-1.7.0/mk/main.mk	2016-03-15 14:13:30.741991672 +0200
@@ -389,17 +389,17 @@
 HLIB_RELATIVE$(1)_H_$(3) = bin
 TROOT$(1)_T_$(2)_H_$(3) = $$(HROOT$(1)_H_$(3))/$$(CFG_LIBDIR_RELATIVE)/rustlib/$(2)
 # Remove the next 3 lines after a snapshot
-ifeq ($(1),0)
-RUSTFLAGS_STAGE0 += -L $$(TROOT$(1)_T_$(2)_H_$(3))/lib
-endif
+#ifeq ($(1),0)
+#RUSTFLAGS_STAGE0 += -L $$(TROOT$(1)_T_$(2)_H_$(3))/lib
+#endif
 
 else
 
-ifeq ($(1),0)
-HLIB_RELATIVE$(1)_H_$(3) = lib
-else
+#ifeq ($(1),0)
+#HLIB_RELATIVE$(1)_H_$(3) = lib
+#else
 HLIB_RELATIVE$(1)_H_$(3) = $$(CFG_LIBDIR_RELATIVE)
-endif
+#endif
 TROOT$(1)_T_$(2)_H_$(3) = $$(HLIB$(1)_H_$(3))/rustlib/$(2)
 
 endif

```

Thanks to eddyb on #rust-internals on irc.mozilla.org for some diagnosis and help.

**Comment by alexcrichton** [comment] 2016-03-15 18:23
@shlomif can you gist what errors you were seeing as part of the build? I just checked out master, ran `./configure --libdir=/usr/lib64 --prefix=/usr`, and the build succeeded.

**Comment by eddyb** [comment] 2016-03-15 18:28
@alexcrichton From IRC:
http://www.shlomifish.org/Files/files/text/log.rust.txt

http://www.shlomifish.org/Files/files/text/rustc-1.7.0-make-VERBOSE-output.txt

http://www.shlomifish.org/Files/files/text/rustc.strace.txt

**Comment by eddyb** [comment] 2016-03-15 18:30
Specifically, this shows that the snapshot compiler is looking in `lib64/rustlib` but it finds only 2 entries (`.` and `..`, presumably):
```
14191 open("/home/shlomif/Download/unpack/Mageia/TO_DEL/rust/BUILD/rustc-1.7.0/x86_64-unknown-linux-gnu/stage0/lib64/rustlib/x86_64-unknown-linux-gnu/lib", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
14191 fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
14191 getdents(3, /* 2 entries */, 32768) = 48
14191 getdents(3, /* 0 entries */, 32768) = 0
14191 close(3)                          = 0
```

**Comment by alexcrichton** [comment] 2016-03-16 16:47
That looks like a [previous bug](https://github.com/rust-lang/rust/issues/27254) where the `lib64` directory in the snapshot directory should not exist, but the configure script created it by accident.  That was fixed in https://github.com/rust-lang/rust/pull/31074 and looks like it may have not made it out to a release yet

**Comment by alexcrichton** [comment] 2016-03-19 00:20
Ah I meant to close this as I think it's a dupe of #27254, but feel free to reopen if it happens on nightly!

**Closed by alexcrichton** 2016-03-19 00:20 UTC
