### ISSUE TITLE
Can't refer to enum variant via Self keyword

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/rust#44299] opened 2017-09-03 21:19 UTC
Since this works:
```rust
match *self {
    MyEnum::Variant1 => (),
    MyEnum::Variant2 => (),
}
```

I expected this to work, when in the context of that enum's implementation:
```rust
match *self {
    Self::Variant1 => (),
    Self::Variant2 => (),
}
```

but instead you get the error: ```error[E0599]: no associated item named `Variant1` found for type `MyEnum` in the current scope``` which seems to suggest the compiler is indeed looking at `MyEnum` but is one step away from making the association.

[Playpen link](https://play.rust-lang.org/?gist=ecf6ce30084523e4e1a983adea86497b&version=stable)

**Comment by petrochenkov** [comment] 2017-09-03 21:35
Duplicate of https://github.com/rust-lang/rust/issues/26264

**Closed by petrochenkov** 2017-09-03 21:35 UTC
