### ISSUE TITLE
Const in impl block requires static lifetime annotation

### ISSUE THREAD

**Issue by maxuuell** [rust-lang/rust#77535] opened 2020-10-04 17:21 UTC
Details are reflected in [this sub](https://www.reddit.com/r/rust/comments/j4qtnt/declare_a_constant_string/), but the gist is that the compiler seems to require a static lifetime annotation for a constant, inside an implementation block.

This seems to go against what the [docs describe](https://doc.rust-lang.org/std/keyword.const.html):

> "Thanks to static lifetime elision, you usually don't have to explicitly use 'static:"

Here is a simple [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%23!%5Ballow(unused)%5D%0Astruct%20M%3B%0Aimpl%20M%20%7B%0Aconst%20WORDS%3A%20%26str%20%3D%20%22hello%20convenience!%22%3B%0A%7D), created and shared by afc11hn, in the sub.

**Comment by jonas-schievink** [comment] 2020-10-04 17:47
Duplicate of https://github.com/rust-lang/rust/issues/51370

**Closed by jonas-schievink** 2020-10-04 17:47 UTC
