### ISSUE TITLE
Previously working declarative macro accepting function as input fails to compile on 1.47

### ISSUE THREAD

**Issue by JanBerktold** [rust-lang/rust#78629] opened 2020-11-01 14:10 UTC
We have a testing framework that uses a declarative macro to take in a test method and "surrounds" it with all the required setup+teardown logic. After the upgrade to `Rust 1.47`, this setup fails to compile.

### Code

```rust
#[macro_export]
macro_rules! integration_test {
    ($name:ident, $f:item) => {
        #[tokio::test]
        async fn $name() {
            // lots of setup here

            // The actual test method is passed in as $f, this creates it.
            $f

            async fn test_runner(address: String) -> GenericResult {
                // do some more setup

                test(&mut client).await
            }

            // run stuff
        }
    };
}
```

Macro is used like this:
```rust
integration_test!(
    test_bootstrapping,
    async fn test(
        _client: &mut SomeProtoClient<tonic::transport::Channel>,
    ) -> GenericResult {
        // do something with client
    }
);
```

I expected to see this happen: I expected the tests to compile and run, just like they had done with Rust 1.46.

Instead, this happened: The compile failed with this error:
```
error: unexpected token
  --> the-file-where-the-macro-is-defined.rs:68:13
   |
68 |               async fn test_runner(address: String) -> GenericResult {
   |               ^^^^^
   |
  ::: the-file-where-the-macro-is-used.rs:63:5
   |
63 | /     integration_test!(
64 | |         test_create_can_only_be_called_once,
65 | |         async fn test(
66 | |             client: &mut SomeProtoClient<tonic::transport::Channel>,
...  |
80 | |         }
81 | |     );
   | |______- in this macro invocation
   |
```

### Version it worked on
It most recently worked on: Rust 1.46

### Version with regression

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```

### Backtrace
n/a

**Comment by Aaron1011** [comment] 2020-11-01 16:48
This is caused by `syn` failing to handle the `None`-delimited group `$f`, and will require an upstream fix.

**Comment by Aaron1011** [comment] 2020-11-01 17:12
Opened https://github.com/dtolnay/syn/issues/916

**Comment by camelid** [comment] 2020-11-01 18:23
This doesn't seem to be a rustc issue, so closing. If it is indeed a rustc issue, feel free to reopen.

**Closed by camelid** 2020-11-01 18:23 UTC
Labels: A-macros, I-prioritize, T-compiler, regression-from-stable-to-stable

**Comment by camelid** [comment] 2020-11-01 20:12
This was fixed upstream.
