### ISSUE TITLE
Diagnostics should mention loop iteration

### ISSUE THREAD

**Issue by aochagavia** [rust-lang/rust#21752] opened 2015-01-29 15:11 UTC
The code:
```
fn main() {
    let v: Vec<i32> = Vec::new();
    loop {
        drop(v);
    }
}
```
The error message:
```
<anon>:4:14: 4:15 error: use of moved value: `v`
<anon>:4         drop(v);
                      ^
<anon>:4:14: 4:15 note: `v` moved here because it has type `collections::vec::Vec<i32>`, which is non-copyable
<anon>:4         drop(v);
                      ^
```

In this simple example, it is pretty easy to notice that the error happens in the next iteration. However, usually the code is more complicated than this and the error is very confusing (see [this reddit thread](http://www.reddit.com/r/rust/comments/2u2koa/confusing_use_of_moved_value_error/)). Maybe we could add something like `move happens in the next iteration of the loop`.

**Comment by sinistersnare** [comment] 2015-01-29 15:29
I dont know, I feel like the error message makes perfect sense. This is just a case of learning the language and not knowing all (or a good amount of) error cases, in my opinion. 

If we had error messages for everything like this, then compiler output would be inundated with crap that no one reads anyways.

**Comment by kmcallister** [comment] 2015-01-30 03:20
Seems worth looking into improving these messages.

**Comment by birkenfeld** [comment] 2016-05-02 12:09
Duplicate of #10876.

**Closed** 2016-06-30 10:15 UTC
Labels: A-diagnostics
