### ISSUE TITLE
Some os  errors should contain context info.

### ISSUE THREAD

**Issue by ch41** [rust-lang/rust#90419] opened 2021-10-30 15:27 UTC
For example: 
```rust
fn main() -> std::io::Result<()> {
    let mut file = File::open("foo.txt")?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    Ok(())
}
```
current error output: 
```rust
Os {
    code: 2,
    kind: NotFound,
    message: "No such file or directory",
}
```

expect something like this:
```rust
Os {
    code: 2,
    // may be another field name.
    path: "foo.txt",
    kind: NotFound,
    message: "No such file or directory",
}

**Comment by jfrimmel** [comment] 2021-10-30 16:51
Duplicate of #79634 and possibly others.

**Closed** 2021-10-30 20:11 UTC
