### ISSUE TITLE
`Clone` and `Default` derive macros have seemingly useless constraints

### ISSUE THREAD

**Issue by TurtlePU** [rust-lang/rust#80871] opened 2021-01-10 13:11 UTC
I am toying with algebra and Rust, with abelian groups in particular. I tried this code:

```rust
/// A helper trait to describe Z/n.
pub trait Fin {
    type Value;
    const N: Self::Value;
}

#[derive(Clone, Default)]
struct ZN<F: Fin>(F::Value);

// ... implementations of addition, negation and so on for ZN ...

struct N99;

impl Fin for N99 {
    type Value = u8;
    const N: u8 = 99;
}

type Z99 = ZN<N99>;

fn main() {
    let x = Z99::default();
    let y = x.clone();
}
```

I expected the code to compile successfully.

Instead, `rustc` complained that `N99` is missing implementation for `Default` (see Backtrace for exact message). But, logically, `<N99 as Fin>::Value` being `Default` is enough for deriving.

The same problem occurs with `Clone`: current derive macro requires `N99: Clone`, but `<N99 as Fin>::Value: Clone` should suffice.

Bug is present on stable, beta and nightly versions of Rust.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

<details><summary>Backtrace</summary>
<p>

```
error[E0599]: no function or associated item named `default` found for struct `ZN<N99>` in the current scope
  --> main.rs:22:18
   |
8  | struct ZN<F: Fin>(F::Value);
   | ----------------------------
   | |
   | function or associated item `default` not found for this
   | doesn't satisfy `ZN<N99>: std::default::Default`
...
12 | struct N99;
   | ----------- doesn't satisfy `N99: std::default::Default`
...
22 |     let x = Z99::default();
   |                  ^^^^^^^ function or associated item not found in `ZN<N99>`
   |
   = note: the method `default` exists but the following trait bounds were not satisfied:
           `N99: std::default::Default`
           which is required by `ZN<N99>: std::default::Default`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `default`, perhaps you need to implement it:
           candidate #1: `std::default::Default`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-01-10 13:13
duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2021-01-10 13:13 UTC
Labels: C-bug
