### ISSUE TITLE
Big file size regression on Windows

### ISSUE THREAD

**Issue by BlaCoiso** [rust-lang/rust#99143] opened 2022-07-11 04:20 UTC
Binary sizes on the latest nightlies are significantly larger than on stable and some previous nightly versions. This is caused by some extra sections in the binary and also an increase in the text and data sections
Stable (1.62.0):
```
nth paddr          size vaddr          vsize perm name
――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000400  0x19e00 0x140001000  0x1a000 -r-x .text
1   0x0001a200   0x7600 0x14001b000   0x8000 -r-- .rdata
2   0x00021800    0x200 0x140023000   0x1000 -rw- .data
3   0x00021a00   0x1200 0x140024000   0x2000 -r-- .pdata
4   0x00022c00    0x400 0x140026000   0x1000 -r-- .reloc
```
Nightly (1.64.0-nightly c396bb3b8):
```
nth paddr          size vaddr          vsize perm name
――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000400  0x7d200 0x140001000  0x7e000 -r-x .text
1   0x0007d600  0x29c00 0x14007f000  0x2a000 -r-- .rdata
2   0x000a7200    0x200 0x1400a9000   0x1000 -rw- .data
3   0x000a7400   0x5c00 0x1400aa000   0x6000 -r-- .pdata
4   0x000ad000    0xc00 0x1400b0000   0x1000 -r-- .debug_a
5   0x000adc00  0x9d000 0x1400b1000  0x9d000 -r-- .debug_i
6   0x0014ac00   0x9000 0x14014e000   0x9000 -r-- .debug_a_1
7   0x00153c00  0x68c00 0x140157000  0x69000 -r-- .debug_r
8   0x001bc800  0xe8e00 0x1401c0000  0xe9000 -r-- .debug_s
9   0x002a5600  0x5a000 0x1402a9000  0x5a000 -r-- .debug_p
10  0x002ff600    0x200 0x140303000   0x1000 -r-- .debug_p_1
11  0x002ff800  0x3a200 0x140304000  0x3b000 -r-- .debug_l
12  0x00339a00  0x21400 0x14033f000  0x22000 -r-- .reloc
```
### Code

I tried this code:

```rust
fn main() {}
```

I expected to see this happen: small binary size (143 360 bytes on 1.62.0)

Instead, this happened: extremely large binary size (3 517 952 bytes)

### Version it worked on

It most recently worked on: Rust 1.64.0 (nightly) ddcbba036aee08f0709f98a92a342a278eae5c05 

### Version with regression

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (c396bb3b8 2022-07-10)
binary: rustc
commit-hash: c396bb3b8a16b1f2762b7c6078dc3e023f6a2493
commit-date: 2022-07-10
host: x86_64-pc-windows-msvc
release: 1.64.0-nightly
LLVM version: 14.0.6
```

**Comment by ehuss** [comment] 2022-07-11 16:43
This seems to be due to #98350, cc @pcwalton.

**Comment by BlaCoiso** [comment] 2022-07-12 14:00
> How was this built? `cargo build` (i.e. without `--release`) would enable debuginfo, but plain `rustc hello.rs` wouldn't.
This was built with `rustc +nightly main.rs -C opt-level=3 -C target-cpu=native`, although the same thing happens with `cargo +nightly build --release`

**Comment by BlaCoiso** [comment] 2022-07-12 15:02
Just checked, this regressed between `nightly-2022-07-09` and `nightly-2022-07-10`

**Comment by eddyb** [comment] 2022-07-12 18:47
That's pretty worrying, because [we don't set e.g. `Debug Info Version` with debuginfo disabled](https://godbolt.org/z/KE85Wz6zG), and the plausible bug that #98350 introduced is that `Dwarf Version` would always be set *when debuginfo is enabled* (i.e. it's exactly as unconditional as `Debug Info Version`).

<hr/>

> Just checked, this regressed between `nightly-2022-07-09` and `nightly-2022-07-10`

Took a look through the PRs that landed in the latter, and aside from #98350, only #98328 could possibly affect output binaries at this level (but I fail to see how it can have any effect for windows).

The only other thing I can think of to try would be [`cargo-bisect-rustc` (in interactive mode)](https://github.com/rust-lang/cargo-bisect-rustc/blob/master/TUTORIAL.md#testing-interactively) - you should be able to pass `--start=2022-07-09 --end=2022-07-10` to it, and then guide it based on how the resulting binary looks like.

**Comment by ehuss** [comment] 2022-07-12 19:01
I already ran cargo-bisect-rustc, that's how I came to the conclusion in https://github.com/rust-lang/rust/issues/99143#issuecomment-1180634053 that it was #98350. Sorry if that wasn't clear.

**Comment by apiraino** [comment] 2022-07-13 09:30
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2399143.20Big.20file.20size.20regression.20on.20Windows)).

@rustbot label -I-prioritize +P-medium +I-heavy

**Comment by eddyb** [comment] 2022-07-14 16:46
Btw as per https://github.com/rust-lang/rust/pull/98350#discussion_r919321117 a quick fix would be to make the (unconditional after #98350) `LLVMRustAddModuleFlag` call for `Dwarf Version` be conditional on `!is_like_msvc` (basically the opposite of the `Code View` one).

This should be perfectly backwards compatible as all MSVC targets had `None` in their target spec, for the DWARF version, before #98350 (so they never got the LLVM `Dwarf Version` set).

If someone can make a PR and test it on windows, I'll r+ p=10 it just to get it out sooner.

**Comment by lqd** [comment] 2022-07-14 17:50
I have access to a windows machine and can do that, but I wonder about the debuginfo sizes:

```console
$ cargo clean && cargo +stable build -q && ls -lh target/debug/helloworld.*
-rw-r--r-- 1 lqd 197121  117 Jul 14 19:40 target/debug/helloworld.d
-rwxr-xr-x 2 lqd 197121 156K Jul 14 19:40 target/debug/helloworld.exe*
-rw-r--r-- 2 lqd 197121 1.2M Jul 14 19:40 target/debug/helloworld.pdb

$ cargo clean && cargo +nightly-2022-07-08 build -q && ls -lh target/debug/helloworld.*
-rw-r--r-- 1 lqd 197121  117 Jul 14 19:41 target/debug/helloworld.d
-rwxr-xr-x 2 lqd 197121 157K Jul 14 19:41 target/debug/helloworld.exe*
-rw-r--r-- 2 lqd 197121 1.3M Jul 14 19:41 target/debug/helloworld.pdb

$ cargo clean && cargo +nightly build -q && ls -lh target/debug/helloworld.*
-rw-r--r-- 1 lqd 197121  117 Jul 14 19:41 target/debug/helloworld.d
-rwxr-xr-x 2 lqd 197121 3.4M Jul 14 19:41 target/debug/helloworld.exe*
-rw-r--r-- 2 lqd 197121 2.7M Jul 14 19:41 target/debug/helloworld.pdb

$ cargo clean && cargo +stage1 build -q && ls -lh target/debug/helloworld.*
-rw-r--r-- 1 lqd 197121  117 Jul 14 19:41 target/debug/helloworld.d
-rwxr-xr-x 2 lqd 197121 167K Jul 14 19:41 target/debug/helloworld.exe*
-rw-r--r-- 2 lqd 197121 596K Jul 14 19:41 target/debug/helloworld.pdb
```

`stage1` is my local build of your suggestion. I wonder if #98350 impacted differently the stdlib debuginfo: the pdb would be half the size it was before the PR landed, on `nightly-2022-07-08` or stable.

I can open the PR if it unblocks clippy and possibly others. We could also revert #98350 if we don't want to risk removing those 600K of debuginfo.

Actually, cc windows and debugging experts @wesleywiser @michaelwoerister for an opinion on the above.

**Comment by eddyb** [comment] 2022-07-14 18:03
Since you're doing a local build, that will be highly impacted by `debuginfo-level-std` AFAICT.

https://github.com/rust-lang/rust/blob/24699bcbadff59693a89a5184afed87f6416cdea/src/ci/run.sh#L72-L75

Okay yeah looks like dist builds always set `debuginfo-level-std=1`.

**Comment by lqd** [comment] 2022-07-14 18:28
Indeed, forcing this setting as @eddyb mentions, *and* doing the same build as https://github.com/rust-lang/rust/issues/99143#issuecomment-1181797800 instead of a debug build, it's looking good now.

I'll open a PR.

**Comment by eddyb** [comment] 2022-07-14 20:33
Out of curiosity, I also checked the MinGW target (`-windows-gnu`) which *does* use DWARF:
<details>
<summary>(click to expand <code>llvm-dwarfdump</code> output for <code>-windows-gnu</code> <code>rustc.exe</code>/<code>rustc_driver-*.dll</code>)</summary>

```console
$ rustup toolchain install nightly-x86_64-pc-windows-gnu
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain as the default.
warning: toolchain 'nightly-x86_64-pc-windows-gnu' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64-pc-windows-gnu` instead?
info: syncing channel updates for 'nightly-x86_64-pc-windows-gnu'
info: latest update on 2022-07-14, rust version 1.64.0-nightly (87588a2af 2022-07-13)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-mingw'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 18.7 MiB /  18.7 MiB (100 %)   4.4 MiB/s in  5s ETA:  0s
info: installing component 'rust-mingw'
info: installing component 'rust-std'
 28.1 MiB /  28.1 MiB (100 %)   8.0 MiB/s in  3s ETA:  0s
info: installing component 'rustc'
 69.5 MiB /  69.5 MiB (100 %)   7.4 MiB/s in  9s ETA:  0s
info: installing component 'rustfmt'

  nightly-x86_64-pc-windows-gnu installed - (rustc does not exist)

$ llvm-dwarfdump --show-section-sizes ~/.rustup/toolchains/nightly-x86_64-pc-windows-gnu/bin/rustc.exe
----------------------------------------------------
file: /home/eddy/.rustup/toolchains/nightly-x86_64-pc-windows-gnu/bin/rustc.exe
----------------------------------------------------
SECTION         SIZE (b)
--------------  --------
.debug_aranges        80 (0.15%)
.debug_info         7657 (14.01%)
.debug_abbrev        303 (0.55%)
.debug_line          546 (1.00%)
.debug_frame          72 (0.13%)

 Total Size: 8658  (15.84%)
 Total File Size: 54656
----------------------------------------------------
$ llvm-dwarfdump --show-section-sizes ~/.rustup/toolchains/nightly-x86_64-pc-windows-gnu/bin/rustc_driver-*.dll 
----------------------------------------------------
file: /home/eddy/.rustup/toolchains/nightly-x86_64-pc-windows-gnu/bin/rustc_driver-3ff33b521bc8cb0c.dll
----------------------------------------------------
SECTION          SIZE (b)
---------------  --------
.debug_aranges        128 (0.00%)
.debug_pubnames    363860 (0.16%)
.debug_pubtypes        18 (0.00%)
.debug_info        198952 (0.09%)
.debug_abbrev         789 (0.00%)
.debug_line         92971 (0.04%)
.debug_frame           48 (0.00%)
.debug_str         556999 (0.24%)
.debug_loc            329 (0.00%)
.debug_ranges      255808 (0.11%)

 Total Size: 1469902  (0.64%)
 Total File Size: 230200250
----------------------------------------------------
```

</details>

So they were able to use untrucated section names - a quick check with a hex viewer confirms that it is the COFF format described in the docs (`/` + an ASCII decimal encoding of a string table offset):

![image](https://user-images.githubusercontent.com/77424/179077469-86aa3ed5-4b0a-4201-92c2-187698b91a65.png)

**Closed** 2022-07-14 21:50 UTC
Labels: P-medium, regression-from-stable-to-nightly, C-bug, I-heavy

**Comment by apiraino** [comment] 2022-07-14 22:09
> This kills the Clippy Windows CI, because it is running out of disk space

thanks for the ping @flip1995 I have re-read this issue and you're right, this is much more impacting than I (mistakenly) understood. Even if the issue should be now solved I'll bump up the prioritization for historical records to `P-critical` to signal that it must have not progressed in the release cycle.

@rustbot label P-critical -P-medium
