### ISSUE TITLE
`cargo doc` failing to document impl for a struct

### ISSUE THREAD

**Issue by ivan0051** [rust-lang/rust#86504] opened 2021-06-21 02:28 UTC
Hello, I am now in the process of learning how to use `cargo doc` for documentation, and it all seemed extremely smooth until I was around halfway through documenting my lib.rs file. I cannot think of anything out of place, but I have a struct `pub struct DataRow {}` and three functions in an `impl DataRow {}` block. Running `cargo doc` collects everything else that I am aware of, yet ignores all `DataRow` implementations. I have another struct with essentially the same layout which I can use to compare, and it works perfectly fine.

Working struct:
```rust
/// Docs docs docs...
pub struct Config {
    pub language: Lang,
    pub filename: String,
}

/// Otherdocs otherdocs...
pub enum Lang {
    EN,
    FR,
}

impl Config {
    ...
}
```

NON-working struct:
```rust
/// A data row object (struct) used to manipulate stored data from file.
/// 
/// A `DataRow` has an output function for each available presentation language, as well as a 
/// constructor function `new(line: Vec<&str>)`.
pub struct DataRow {
    pruid: isize,
    prname: String,
    prname_fr: String,
    date: String,
    numconf: isize,
    numprob: isize,
    numdeaths: isize,
    numtotal: isize,
    numtoday: isize,
    ratetotal: f64,
}

impl DataRow {
    ...
}
```

Honestly, there's no remarkable difference here. They both involve a struct with documentation, and an impl block with no documentation in it. I'd even consider the first struct more likely to have encountered a failure, since there's an enum between it and the implementation block (since I was not sure how hard cargo doc would search for a connection). As you can see, I'm at somewhat of a loss. When I visit the docs web UI, it works perfectly, with nothing strange aside from the missing implementations. Specifically, the entire implementations section is not there.

I am open to the possibility that this isn't a bug, but it does smell like a bug.

IMPORTANT NOTE: I am particularly aware of this issue, which seems very similar:  #67904
However, I can confirm I am not having the same issue, as far as I am able to see. If this is a bug or anybody can help otherwise, that would be great.

**Comment by jyn514** [comment] 2021-06-21 02:40
@ivan0051 can you please post the full code that doesn't work? `impl { ... }` is invalid syntax.

**Comment by ivan0051** [comment] 2021-06-21 02:42
Actually the full code? It's not sensitive, it's just an awkwardly long block. So not just the function signatures+scopes?

**Comment by ivan0051** [comment] 2021-06-21 02:44
```rust
impl DataRow {
    /// A function for creating new `DataRow` structs from a vector.
    fn new(line: Vec<&str>) -> DataRow {
        DataRow {
            pruid: if line[0] == "" {0} else {line[0].parse().unwrap()},
            prname: String::from(line[1]),
            prname_fr: String::from(line[2]),
            date: String::from(line[3]),
            numconf: if line[4] == "" {0} else {line[4].parse().unwrap()},
            numprob: if line[5] == "" {0} else {line[5].parse().unwrap()},
            numdeaths: if line[6] == "" {0} else {line[6].parse().unwrap()},
            numtotal: if line[7] == "" {0} else {line[7].parse().unwrap()},
            numtoday: if line[8] == "" {0} else {line[8].parse().unwrap()},
            ratetotal: if line[9] == "" {0.00} else {line[9].parse().unwrap()},
        }
    }

    /// A function for outputting the formatted English-language version of the data.
    fn output_en(&self) -> String {
        let mut line = String::new();

        line.push_str(&col_spacing(self.pruid.to_string(), 8));
        line.push_str(&col_spacing(self.prname.clone(), 30));
        line.push_str(&col_spacing(self.date.clone(), 15));
        line.push_str(&col_spacing(self.numconf.to_string(), 10));
        line.push_str(&col_spacing(self.numprob.to_string(), 10));
        line.push_str(&col_spacing(self.numdeaths.to_string(), 10));
        line.push_str(&col_spacing(self.numtotal.to_string(), 10));
        line.push_str(&col_spacing(self.numtoday.to_string(), 10));
        line.push_str(&col_spacing(self.ratetotal.to_string(), 10));

        line
    }

    /// A function for outputting the formatted French-language version of the data.
    fn output_fr(&self) -> String {
        let mut line = String::new();

        line.push_str(&col_spacing(self.pruid.to_string(), 8));
        line.push_str(&col_spacing(self.prname_fr.clone(), 30));
        line.push_str(&col_spacing(self.date.clone(), 15));
        line.push_str(&col_spacing(self.numconf.to_string(), 10));
        line.push_str(&col_spacing(self.numprob.to_string(), 10));
        line.push_str(&col_spacing(self.numdeaths.to_string(), 10));
        line.push_str(&col_spacing(self.numtotal.to_string(), 10));
        line.push_str(&col_spacing(self.numtoday.to_string(), 10));
        line.push_str(&col_spacing(self.ratetotal.to_string(), 10));

        line
    }
}
```

**Comment by ivan0051** [comment] 2021-06-21 02:45
There's the full impl section. It compiles/runs just fine, but cargo doc ignores it.

**Comment by jyn514** [comment] 2021-06-21 03:51
@ivan0051 those functions are private. Rustdoc only documents public functions by default. You can override that with `cargo rustdoc -- --document-private-items`.

**Comment by ivan0051** [comment] 2021-06-21 04:06
Oh, I see. That makes sense, I suppose it's just unfortunate that Rust is young enough that researching it didn't pop up any meaningful results. I suppose that's the main downside of Rust currently - a relatively low amount of online discussion to search. With Java for example, about any question I can conceive of has dozens of answers. With Rust, there are no guarantees. Hopefully his improves over the next 5 years!

**Comment by jyn514** [comment] 2021-06-21 04:12
I'm going to close this since it's not a bug.

**Comment by jyn514** [comment] 2021-06-21 04:12
You can find more documentation about rustdoc here: https://doc.rust-lang.org/stable/rustdoc/

**Closed by jyn514** 2021-06-21 04:12 UTC
Labels: A-rustdoc, C-discussion

**Comment by ivan0051** [comment] 2021-06-21 04:22
Thank you! I will keep this page in mind, though the main problem about researching Rust is not knowing what I should be looking up or where I should be looking (what someone on Reddit referred to as "unknown unknowns" (you can't know that you don't know...) contrasted with "known unknowns" (you know what you're missing knowledge on)).

Anyway, thanks!
