### ISSUE TITLE
ICE produces by a simple warp example.

### ISSUE THREAD

**Issue by KaiserKarel** [rust-lang/rust#78672] opened 2020-11-02 15:01 UTC
Running the below example produces an ICE using `warp = "0.2"`.

### Code

```Rust
use warp::Filter;

#[tokio::main]
async fn main() {
    // GET /hello/warp => 200 OK with body "Hello, warp!"
    let hello = warp::path!("hello" / String)
        .map(|name| async { format!("Hello, {}!", name) });

    warp::serve(hello)
        .run(([127, 0, 0, 1], 3030))
        .await;
}
```

### Meta
`rustc --version --verbose`:

```
rustc 1.49.0-nightly (dd7fc54eb 2020-10-15)
binary: rustc
commit-hash: dd7fc54ebdca419ad9d3ab1e9f5ed14e770768ea
commit-date: 2020-10-15
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

### Error output

```
compiler/rustc_middle/src/ty/sty.rs:2124:18: tuple_fields called on non-tuple

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:945:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (dd7fc54eb 2020-10-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
```

**Comment by jonas-schievink** [comment] 2020-11-02 15:32
Duplicate of https://github.com/rust-lang/rust/issues/77993 – it should be fixed on the newest nightly

**Closed by jonas-schievink** 2020-11-02 15:32 UTC
Labels: C-bug, I-ICE, T-compiler
