### ISSUE TITLE
Using extra lifetime parameter when implementing a trait is allowed

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#61888] opened 2019-06-16 09:00 UTC
```rust
trait Abc {
    fn abc<'tcx>(&self);
}

struct MyAbc;

impl Abc for MyAbc {
    //     vv this lifetime parameter doesn't exist in the original trait
    fn abc<'a, 'tcx>(&self) {}
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b09ac8d49071a6c425b204a0fd0c4ddd))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: struct is never constructed: `MyAbc`
 --> src/lib.rs:5:1
  |
5 | struct MyAbc;
  | ^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.40s

```

**Comment by jonas-schievink** [comment] 2019-06-16 10:04
This might be expected. Methods in an impl are matched with the trait method using subtyping, so effectively there's these two method types:
* `for<'self, 'tcx> fn(&'self Self)`
* `for<'self, 'a, 'tcx> fn(&'self Self)`

And to me it doesn't look terribly wrong to consider those compatible (or even equivalent).

**Comment by bjorn3** [comment] 2019-06-16 10:32
> And to me it doesn't look terribly wrong to consider those compatible (or even equivalent).

It's just surprising :)

**Comment by pnkfelix** [comment] 2019-06-20 13:40
T-compiler triage: assuming this is nominated for T-lang. Leaving unprioritized.

**Comment by eddyb** [comment] 2019-06-20 13:44
It's linted by `unused_lifetimes` (if you turn that lint on, e.g. `#![deny(unused_lifetimes)]`), at least.

**Comment by pnkfelix** [comment] 2019-06-27 13:38
pre-triage: removing T-compiler under assumption that this is the lang teams issue, not compiler's.

**Comment by nikomatsakis** [comment] 2019-07-11 22:37
this is indeed intended behavior. I am therefore closing in favor of this bug on the reference repository https://github.com/rust-lang-nursery/reference/issues/637. Thanks!

**Closed by nikomatsakis** 2019-07-11 22:37 UTC
Labels: C-bug, I-nominated, T-lang
