### ISSUE TITLE
RawVec should round capacity to jemalloc bucket size

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#40058] opened 2017-02-23 13:29 UTC
By inspection of source code, it seems that `RawVec` is unaware of jemalloc bucket sizes. This is unfortunate, because it's wasteful to reallocate when the required capacity would fit within the current jemalloc allocation but `RawVec` just doesn't know.

As far as abstraction leakage goes, it would be better to let the leakage stop at `RawVec` than to have [higher-level code try to second-guess `RawVec` with assumptions about the underlying allocator](https://github.com/hsivonen/encoding_rs/issues/6).

I suggest that the allocator crate provide a rounding function for rounding up to the largest allocation size that would consume as much space in the underlying allocator as the requested size and `RawVec` use it to round up capacity. For jemalloc, the rounding function would round to the jemalloc bucket size.

**Comment by nagisa** [comment] 2017-02-23 14:33
Duplicate of #29931 and #32075

**Comment by Mark-Simulacrum** [comment] 2017-05-24 16:34
Closing in favor of #29931.

**Closed by Mark-Simulacrum** 2017-05-24 16:34 UTC
