### ISSUE TITLE
`x.py build` fails to find bootstrap if global cargo config has target set

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#44914] opened 2017-09-29 01:41 UTC
```
$ cat ~/.cargo/config 
[build]
target = "x86_64-unknown-linux-gnu"
...

$ ./x.py build --help
   Compiling build_helper v0.1.0 (file:///mnt/src/git/rust/src/build_helper)
   Compiling bootstrap v0.0.0 (file:///mnt/src/git/rust/src/bootstrap)
    Finished dev [unoptimized] target(s) in 33.65 secs
Traceback (most recent call last):
  File "./x.py", line 20, in <module>
    bootstrap.main()
  File "/mnt/src/git/rust/src/bootstrap/bootstrap.py", line 756, in main
    bootstrap()
  File "/mnt/src/git/rust/src/bootstrap/bootstrap.py", line 747, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/mnt/src/git/rust/src/bootstrap/bootstrap.py", line 143, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Similar to https://github.com/DanielKeep/cargo-script/issues/37

Like in cargo-script, the correct way is probably to set taret explicitly and/or request JSON output from Cargo to find the actual bootstrap executable location.

**Comment by jyn514** [comment] 2022-06-27 05:58
I can reproducing by writing the config to ~/.cargo/config (I had to also run `rm -r build/bootstrap/debug` to clear the cache). I think the fix would be to use `--output-format json` and look for `executable` in the output.

But I also think this isn't really worth fixing - having any custom flags in .cargo/config isn't supported, which is why we delete the version in-tree: https://github.com/rust-lang/rust/blob/7702ae16a23407cdd909ff9174294563ae1f4ba3/src/bootstrap/bootstrap.py#L854-L855

We obviously don't want to do that for the global config, but that doesn't mean it's supported ...

**Comment by jyn514** [comment] 2023-05-24 23:40
I'm going to close this since changes in ~/.cargo/config aren't supported.

**Closed by jyn514** 2023-05-24 23:40 UTC
Labels: T-bootstrap, C-bug

**Comment by Houtamelo** [comment] 2024-11-10 23:19
> I'm going to close this since changes in ~/.cargo/config aren't supported.

I understand not supporting the changes, but couldn't the global configs at least be ignored? 
This makes it harder to contribute to the compiler while having other projects on the same machine, not to mention finding the source of the errors caused by this can waste a lot of time.

**Comment by onur-ozkan** [comment] 2024-11-11 02:11
> > I'm going to close this since changes in ~/.cargo/config aren't supported.
> 
> I understand not supporting the changes, but couldn't the global configs at least be ignored? 
> This makes it harder to contribute to the compiler while having other projects on the same machine, not to mention finding the source of the errors caused by this can waste a lot of time.

You could override them with another .cargo/config in rust project directory.
