### ISSUE TITLE
Rust compiler takes over 26 hours to compile on iMac i5 2012 edition

### ISSUE THREAD

**Issue by vikrantrathore** [rust-lang/rust#83869] opened 2021-04-05 03:28 UTC
Rust compiler is extremely slow and takes over 15 hours to compile on iMac 2012 with i5 processor and 20 GB RAM

```
brew upgrade --verbose
```

The dependency which triggered the compilation of rust on iMac is rav1e used by formula of ffmpeg.

Because of rust dependency the rust compiler updates to 1.51. 0 version and needs over 26 hours and 23 minuted to compile on iMac and then subsequently update the curl.

Is there any plan to make rust compiler fast? 

Right now due to extremely slow speed of compilation it feels like transported back to 1994 compiling linux kernel on a 486 machine.

Is there something missing in rustc given go language new versions compiles in few minutes on the same iMac.

Note: Changed the details as it's due to ffmpeg which uses rav1e as depedency and not the upgrade of curl

**Comment by eggyal** [comment] 2021-04-05 06:15
Homebrew's [curl formula](https://formulae.brew.sh/formula/curl) certainly doesn't depend on Rust—but even if it did, there are official Rust binaries for MacOS so building from source is something only compiler developers typically need to do...

Can you provide some more information around what exactly is taking place here?  If Rust is genuinely being built from source: how is it being bootstrapped, what stage is being built, etc?  Perhaps share the build command(s), `config.toml`, any output?

**Comment by vikrantrathore** [comment] 2021-04-05 06:53
This has been running for more than 8 hours now and still ongoing similar to last time when it took over 26 hours.

This is due to brew formula of other software which requires rust compiler.

This kind of rust compiler upgrade is automatically triggered by some of the brew formula which needs rust. As I do not control the brew formula's cannot make that change myself. Although I do not use rust myself for development it makes dependent brew formula extremely slow to upgrade.

Its really frustrating that a simple brew upgrade of a software taking over 24 hours to finish due to rustc compiler compilation as it also needs to be upgraded as dependency.  Below is the rust formula triggered by brew as dependency.

Same behaviour is for some of the go language formula but the overall compilation go compiler is a breeze. It takes few minutes to complete on the same machine.

```
class Rust < Formula
  desc "Safe, concurrent, practical language"
  homepage "https://www.rust-lang.org/"
  license any_of: ["Apache-2.0", "MIT"]

  stable do
    url "https://static.rust-lang.org/dist/rustc-1.51.0-src.tar.gz"
    sha256 "7a6b9bafc8b3d81bbc566e7c0d1f17c9f499fd22b95142f7ea3a8e4d1f9eb847"

    resource "cargo" do
      url "https://github.com/rust-lang/cargo.git",
          tag:      "0.52.0",
          revision: "43b129a20fbf1ede0df411396ccf0c024bf34134"
    end
  end

  bottle do
    sha256 cellar: :any, arm64_big_sur: "194906f669b54ba323143a02595dbdec6788236b52099e4145e4fac2340c27ce"
    sha256 cellar: :any, big_sur:       "f792ca45d01d474f51a4b2261713aa36d55a9b0ce60329d5a563f9a761f26dd8"
    sha256 cellar: :any, catalina:      "680b81ddcee5049e511b1d5b5da7e8be74df351de96317d033f81c01ab7858cb"
    sha256 cellar: :any, mojave:        "d33f8c8aac0b0d6e3527048fd7f687074046d5ce2d5f84af4c741af5e601e517"
  end

  head do
    url "https://github.com/rust-lang/rust.git"

    resource "cargo" do
      url "https://github.com/rust-lang/cargo.git"
    end
  end

  depends_on "cmake" => :build
  depends_on "ninja" => :build
  depends_on "python@3.9" => :build
  depends_on "libssh2"
  depends_on "openssl@1.1"
  depends_on "pkg-config"

  uses_from_macos "curl"
  uses_from_macos "zlib"

  resource "cargobootstrap" do
    on_macos do
      # From https://github.com/rust-lang/rust/blob/#{version}/src/stage0.txt
      if Hardware::CPU.arm?
        url "https://static.rust-lang.org/dist/2021-02-11/cargo-1.50.0-aarch64-apple-darwin.tar.gz"
        sha256 "19d526ef3518fb0322f809deddbd4208a27d08efa41d2188348f1be8d3bcfe5e"
      else
        url "https://static.rust-lang.org/dist/2021-02-11/cargo-1.50.0-x86_64-apple-darwin.tar.gz"
        sha256 "45640bb1cef40f25ecb4bd2a3bb34fdf884c418e625d4f9c9595d2aca84fad78"
      end
    end

    on_linux do
      # From: https://github.com/rust-lang/rust/blob/#{version}/src/stage0.txt
      url "https://static.rust-lang.org/dist/2021-02-11/cargo-1.50.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3456cfd9be761907a4d3aae475bd79d93662b7aee4541f28df3d1f7c7d71a034"
    end
  end

  def install
    ENV.prepend_path "PATH", Formula["python@3.9"].opt_libexec/"bin"

    # Fix build failure for compiler_builtins "error: invalid deployment target
    # for -stdlib=libc++ (requires OS X 10.7 or later)"
    ENV["MACOSX_DEPLOYMENT_TARGET"] = MacOS.version

    # Ensure that the `openssl` crate picks up the intended library.
    # https://crates.io/crates/openssl#manual-configuration
    ENV["OPENSSL_DIR"] = Formula["openssl@1.1"].opt_prefix

    # Fix build failure for cmake v0.1.24 "error: internal compiler error:
    # src/librustc/ty/subst.rs:127: impossible case reached" on 10.11, and for
    # libgit2-sys-0.6.12 "fatal error: 'os/availability.h' file not found
    # #include <os/availability.h>" on 10.11 and "SecTrust.h:170:67: error:
    # expected ';' after top level declarator" among other errors on 10.12
    ENV["SDKROOT"] = MacOS.sdk_path

    args = ["--prefix=#{prefix}"]
    if build.head?
      args << "--disable-rpath"
      args << "--release-channel=nightly"
    else
      args << "--release-channel=stable"
    end

    system "./configure", *args
    system "make"
    system "make", "install"

    resource("cargobootstrap").stage do
      system "./install.sh", "--prefix=#{buildpath}/cargobootstrap"
    end
    ENV.prepend_path "PATH", buildpath/"cargobootstrap/bin"

    resource("cargo").stage do
      ENV["RUSTC"] = bin/"rustc"
      args = %W[--root #{prefix} --path . --features curl-sys/force-system-lib-on-osx]
      system "cargo", "install", *args
      man1.install Dir["src/etc/man/*.1"]
      bash_completion.install "src/etc/cargo.bashcomp.sh"
      zsh_completion.install "src/etc/_cargo"
    end

    (lib/"rustlib/src/rust").install "library"
    rm_rf prefix/"lib/rustlib/uninstall.sh"
    rm_rf prefix/"lib/rustlib/install.log"
  end

  def post_install
    Dir["#{lib}/rustlib/**/*.dylib"].each do |dylib|
      chmod 0664, dylib
      MachO::Tools.change_dylib_id(dylib, "@rpath/#{File.basename(dylib)}")
      chmod 0444, dylib
    end
  end

  test do
    system "#{bin}/rustdoc", "-h"
    (testpath/"hello.rs").write <<~EOS
      fn main() {
        println!("Hello World!");
      }
    EOS
    system "#{bin}/rustc", "hello.rs"
    assert_equal "Hello World!\n", `./hello`
    system "#{bin}/cargo", "new", "hello_world", "--bin"
    assert_equal "Hello, world!",
                 (testpath/"hello_world").cd { `#{bin}/cargo run`.split("\n").last }
  end
end
```

![image](https://user-images.githubusercontent.com/6446997/113545256-6bfe2300-961c-11eb-9686-0c231c076b62.png)

**Comment by vikrantrathore** [comment] 2021-04-05 07:00
It's due to upgrade of ffmpeg which uses rav1e as dependency which triggers rust compiler upgrade.

```
class Rav1e < Formula
  desc "Fastest and safest AV1 video encoder"
  homepage "https://github.com/xiph/rav1e"
  url "https://github.com/xiph/rav1e/archive/v0.4.1.tar.gz"
  sha256 "b0be59435a40e03b973ecc551ca7e632e03190b5a20f944818afa3c2ecf4852d"
  license "BSD-2-Clause"
  head "https://github.com/xiph/rav1e.git"

  livecheck do
    url :stable
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end

  bottle do
    sha256 cellar: :any, arm64_big_sur: "e5dd3ae4c9492d6984dbc4f67a0b0fac23b4bd9294f6ba80a6621c94e841f70c"
    sha256 cellar: :any, big_sur:       "7c9ead158025ca4faa1236a5a14194dfc849ef5e199abf87e9d63cbef70b44ae"
    sha256 cellar: :any, catalina:      "360c7d268a838420b20b7c59cf7df38d37b50a3f5b75d02ea326f4a4de96b433"
    sha256 cellar: :any, mojave:        "a9d58a74c083653d4cdbde52224b8aecf01d30a60d9c11b8fc4cfc78b89e9ab3"
  end

  depends_on "cargo-c" => :build
  depends_on "nasm" => :build
  depends_on "rust" => :build

  resource "bus_qcif_7.5fps.y4m" do
    url "https://media.xiph.org/video/derf/y4m/bus_qcif_7.5fps.y4m"
    sha256 "1f5bfcce0c881567ea31c1eb9ecb1da9f9583fdb7d6bb1c80a8c9acfc6b66f6b"
  end

  def install
    system "cargo", "install", *std_cargo_args
    system "cargo", "cinstall", "--prefix", prefix
  end

  test do
    resource("bus_qcif_7.5fps.y4m").stage do
      system "#{bin}/rav1e", "--tile-rows=2",
                                   "bus_qcif_7.5fps.y4m",
                                   "--output=bus_qcif_15fps.ivf"
    end
  end
end


```

**Comment by eggyal** [comment] 2021-04-05 07:35
Looks like that formula will build LLVM from scratch, and then compile to stage-2 (so basically compiles Rust three times)?  Perhaps Homebrew should tweak their formula.  That said, they provide bottles (pre-built binaries) for Big Sur, Catalina and Mojave—so I presume you're on an older version of MacOS than that?  Upgrading would help.  Alternatively, you could try [installing Rust from Rustup](https://www.rust-lang.org/tools/install) and `brew link`ing it.  But none of this is really an issue with Rust itself?

**Comment by vikrantrathore** [comment] 2021-04-05 07:58
> Looks like that formula will build LLVM from scratch, and then compile to stage-2 (so basically compiles Rust three times)? Perhaps Homebrew should tweak their formula. That said, they provide bottles (pre-built binaries) for Big Sur, Catalina and Mojave—so I presume you're on an older version of MacOS than that? Upgrading would help. Alternatively, you could try [installing Rust from Rustup](https://www.rust-lang.org/tools/install) and `brew link`ing it. But none of this is really an issue with Rust itself?

iMac 2012 with i5 and 20GB RAM is a reasonably powerful machine and rust takes over 24 hours to compile. So if compilation speed of rust is not an issue it's fine, let me know and will close the issue.

I believe rust should have a good developer experience, but it seems the compilation speed is among the slowest.

**Comment by slightlyoutofphase** [comment] 2021-04-05 08:15
Do you have an SSD in there? Or is it just running the 5400 RPM HDD that iMacs shipped with at that time? `rustc` certainly writes a heck of a lot to disk very often, so mechanical storage of that kind would not exactly be helping the issue in general. Also I believe the i5 in question is an [i5-3330](https://ark.intel.com/content/www/us/en/ark/products/65510/intel-core-i5-3330s-processor-6m-cache-up-to-3-20-ghz.html), for reference.

**Comment by eggyal** [comment] 2021-04-05 08:17
Compiling LLVM from scratch and then bootstrapping to a stage-2 compiler is a significant task, one that's only really necessary in rare situations (basically, if you're a compiler developer or are using a platform for which there aren't any pre-built binaries). In those circumstances, it's expected that a build will take some time—although I agree 24 hours seems rather excessive (but there are already some relevant open issues regarding slow compilation on MacOS).

I think, in your case, a pre-built binary is all you need.

**Comment by vikrantrathore** [comment] 2021-04-05 08:40
Not sure if compiling from scratch is reserved for compiler developer. I am a user of GNU Guix (https://guix.gnu.org/), and many of my scheme files for building and updating system requires compiling from scratch regularly. Indeed it's very common to compile go or Python in my workflow from sources to produce container images with the philosophy of reproducible computations (http://guix.gnu.org/en/blog/2020/reproducible-computations-with-guix/). It takes on an average 2 minutes 46 seconds to compile go language with its dependent libraries on the same hardware. Rust is really slow  to compile for securing updates and reproducible computations, where things need to be built from sources. 

Opened this ticket because I feel in order to be really a good systems programming language rust needs to be able to compile fast on a reasonable hardware. But if it's not an issue or priority for rust I or you can close this issue.

**Comment by vikrantrathore** [comment] 2021-04-05 08:44
> Do you have an SSD in there? Or is it just running the 5400 RPM HDD that iMacs shipped with at that time? `rustc` certainly writes a heck of a lot to disk very often, so mechanical storage of that kind would not exactly be helping the issue in general. Also I believe the i5 in question is an [i5-3330S](https://ark.intel.com/content/www/us/en/ark/products/65510/intel-core-i5-3330s-processor-6m-cache-up-to-3-20-ghz.html), for reference.

I am on 7200 RPM HDD, but feel if go language takes 2 min 46 seconds, python with all its libraries takes 8-9 minutes, nodejs takes 13 minutes, dart takes 13-15 minutes to compile. Rust should be able to compile in a similar way.

**Comment by the8472** [comment] 2021-04-05 09:52
If you compile your software from source I assume you already have an LLVM build compiled. You can in principle reuse that for building rust (assuming it's recent enough), but then you'll risk miscompilations since a vanilla LLVM may be lacking backported fixes.

Additionally you can cut some corners by building a stage1 compiler instead of stage2, that'll significantly reduce compile times.

For reference, I ran a stage 1 build on my linux laptop with a i7-8565U:

* LLVM: 30 minutes
* stage 1 rustc: 11 minutes
* stage 1 std and rustdoc: 2 minutes

So if you can use a pre-built LLVM you can probably shave off most of the build time.

**Comment by vikrantrathore** [comment] 2021-04-05 10:39
> If you compile your software from source I assume you already have an LLVM build compiled. You can in principle reuse that for building rust (assuming it's recent enough), but then you'll risk miscompilations since a vanilla LLVM may be lacking backported fixes.
> 
> Additionally you can cut some corners by building a stage1 compiler instead of stage2, that'll significantly reduce compile times.
> 
> For reference, I ran a stage 1 build on my linux laptop with a i7-8565U:
> 
>     * LLVM: 30 minutes
> 
>     * stage 1 rustc: 11 minutes
> 
>     * stage 1 std and rustdoc: 2 minutes
> 
> 
> So if you can use a pre-built LLVM you can probably shave off most of the build time.

Correct pre-compiled LLVM and Rust will reduce the time, but this is a workaround for a problem of slow compilation in Rust. 

Given rust focus on reproducible builds they needs very specific LLVM version to avoid bugs and this will mean that to have reproducible binary using rust, it's a necessary to spend a lot of money in beefy hardware to compile. It will still take longer than competing systems programming language for develop-compile-debug-compile-deploy cycle. 

It's ok for this compromise as focus of Rust is safety, not speed, if you feel this ticket needs to be closed as there are workarounds just close it. I understand the dichotomy of safety vs speed.

**Comment by slightlyoutofphase** [comment] 2021-04-05 14:18
>it's a necessary to spend a lot of money in beefy hardware to compile.

I think that concretely arriving at what actually constitutes "beefy hardware" is quite difficult, for what it's worth. For example, I do the majority of my development in both C++ and Rust (including building both C++ compilers and `rustc` from source relatively often as I like to "stay on top of things") on a custom-built desktop PC from 2013 (so not much newer than what you're running) that has the following specs currently:  
  
- i7-4790K
- 16GB DDR3-2400 CL10
- 512GB SSD for Windows 10 and a selection of "important apps", 2TB HDD for general storage of everything else.

Arguably a "beefy" setup eight years ago when I put it together, but far from it in the grand scheme of things these days. Building the entire LLVM toolchain (including Clang, LLD, LLDB, the extra tools, etc) plus `rustc` doesn't take me more than like a couple of hours tops.

There's really a lot of factors that could be impacting things for you. Probably it would be particularly useful to hear from someone else who builds `rustc` on iMac hardware from around the same era as yours to see how their build times compare, for starters.

**Comment by nagisa** [comment] 2022-04-02 20:38
> Do you have an SSD in there? Or is it just running the 5400 RPM HDD that iMacs shipped with at that time? rustc certainly writes a heck of a lot to disk very often, so mechanical storage of that kind would not exactly be helping the issue in general.

FWIW I develop rustc on a mechanical storage too, and while it doesn't help the build times in general, it doesn't make them that terrible either.

---

26 hours definitely seems excessive, but it is also true that:

1. rustc developers largely never fully bootstrap the compiler, much like gcc developers don't bootstrap their compiler fully either;
  * `python` build in particular isn't a comparable workload as it is an interpreter, not a bootstrapping compiler.
2. While rust in general strives to stay accessible, and we don't really focus much on the bootstrap times, we pay a lot of attention to the speed at which rustc can build programs in the ecosystem in general.
  * This does reflect in significant improvements to the bootstrap times [in the end](https://perf.rust-lang.org/bootstrap.html?start=2018-01-01&end=2022-04-01).

I'm not able to check the way homebrew builds rustc right now, but the amount of time spent building would suggest to me that homebrew optimizes building for distribution and not for build time. This may or may not mean using link time optimization (notoriously expensive thing to do) and maybe even profile-guided optimization (which would mean even more rebuilds of the compiler than the 3 hinted.)

---

Sadly, I don't believe this issue as written is all that actionable. It doesn't appear to point out any specific function as a major bottleneck we could work on, and so there isn't much we can do for you here to quickly improve the experience on that particular setup. It is quite unlikely that there is a rustc developer who has that particular hardware to attempt reproduction with.

Perf work in general is an outstanding long-term initiative that is tracked by other means, so I'm going to close this issue. Thanks for taking time to report it.

**Closed by nagisa** 2022-04-02 20:38 UTC
