### ISSUE TITLE
Type inference works incorrectly with HRTB and closures

### ISSUE THREAD

**Issue by uHOOCCOOHu** [rust-lang/rust#50973] opened 2018-05-22 17:45 UTC
I'm trying to make an alias for a trait with HRTB. But it causes type (lifetime of the argument) mismatch when working with closures. 

Weirdly, when I write the hint `_: &_`, which seems hint nothing about lifetimes, it works again.

Here's the detail.

https://play.rust-lang.org/?gist=0fb0af047d432f2aa06782152661507a&version=nightly&mode=debug

**Comment by vitalyd** [comment] 2018-05-22 22:41
See https://github.com/rust-lang/rust/issues/41078

**Comment by uHOOCCOOHu** [comment] 2018-05-23 02:41
Yeah, the compiler inferred some lifetime but not forall lifetime. 

But it confused me that if I move the bound out of trait, like `check2()`, all of them work well.

**Comment by Mark-Simulacrum** [comment] 2018-05-24 01:12
Yes, I believe this is a duplicate of #41078. Thanks!

**Closed by Mark-Simulacrum** 2018-05-24 01:12 UTC
