### ISSUE TITLE
Compiler panics when given invalid Box type

### ISSUE THREAD

**Issue by takanuva** [rust-lang/rust#77113] opened 2020-09-23 15:47 UTC
So, I was fiddling with code generation (playing with boxes), and this happened.

### Code

```Rust
#![no_std]
#![feature(box_syntax, box_patterns, rustc_private, lang_items)]
extern crate libc;

#[lang = "owned_box"]
// I tried adding an Option here, just to see what would happen!
pub struct Box<T>(Option<*mut T>);

#[inline(always)]
#[lang = "exchange_malloc"]
unsafe fn allocate(size: usize, _align: usize) -> *mut u8 {
    let p = libc::malloc(size as libc::size_t) as *mut u8;
    return p;
}

#[inline(always)]
#[lang = "box_free"]
unsafe fn box_free<T: ?Sized>(ptr: *mut T) {
    libc::free(ptr as *mut libc::c_void);
}

pub fn foo(a: Box<i32>, b: Box<i32>) -> Box<i32> {
    let box va = a;
    let box vb = b;
    return box (va + vb);
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (0da580074 2020-09-22) running on x86_64-unknown-linux-gnu
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/0da58007451a154da2480160429e1604a1f5f0ec/compiler/rustc_middle/src/ty/layout.rs:2074:17
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
thread 'rustc' panicked at 'assertion failed: i < this.fields.count()', /rustc/0da58007451a154da2480160429e1604a1f5f0ec/compiler/rustc_middle/src/ty/layout.rs:2074:17
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::ty::layout::<impl rustc_target::abi::TyAndLayoutMethods<C> for &rustc_middle::ty::TyS>::field
   2: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::scalar_pair_element_llvm_type
   3: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::scalar_pair_element_llvm_type
   4: <rustc_target::abi::TyAndLayout<&rustc_middle::ty::TyS> as rustc_codegen_llvm::type_of::LayoutLlvmExt>::llvm_type
   5: <rustc_target::abi::call::FnAbi<&rustc_middle::ty::TyS> as rustc_codegen_llvm::abi::FnAbiLlvmExt>::llvm_type
   6: rustc_codegen_llvm::mono_item::<impl rustc_codegen_ssa::traits::declare::PreDefineMethods for rustc_codegen_llvm::context::CodegenCx>::predefine_fn
   7: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
   8: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
   9: rustc_codegen_llvm::base::compile_codegen_unit
  10: rustc_codegen_ssa::base::codegen_crate
  11: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  12: rustc_interface::passes::QueryContext::enter
  13: rustc_interface::queries::Queries::ongoing_codegen
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: rustc_interface::interface::create_compiler_and_run
  17: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-09-23 15:55
Thanks for the report! This looks like a duplicate of https://github.com/rust-lang/rust/issues/9307, however, so closing in favor of that.

Please leave a comment on that issue if you have more information to contribute.

**Closed by jonas-schievink** 2020-09-23 15:55 UTC
Labels: C-bug, I-ICE, T-compiler
