### ISSUE TITLE
libstd docs of re-exported macros are unformatted

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#26560] opened 2015-06-25 03:24 UTC
One example is the `unreachable!` macro, though I think I've seen it elsewhere. The documention of the macro [in libcore](http://doc.rust-lang.org/stable/core/macro.unreachable!.html) is fine, but the docs of the same macro [in libstd](http://doc.rust-lang.org/std/macro.unreachable!.html) have the source formatting all weird, and the actual `[src]` link is broken.

**Comment by durka** [comment] 2015-06-25 03:30
Of course you don't _need_ the `[src]` link for a macro, but that's [another issue!](https://github.com/rust-lang/rust/issues/17616)

**Comment by sfackler** [comment] 2015-06-25 05:26
The formatting issue's a dup of #20923. Not sure if the src link being broken's been filed.

**Comment by durka** [comment] 2015-12-16 01:34
The src link at the re-exported macro is gone, so closing.

**Comment by cbreeden** [comment] 2017-01-09 23:47
I think this issue is relevant again.  The solution for the dup was to refactor error reporting system, which doesn't solve the formatting issues in the docs.

**Comment by cbreeden** [comment] 2017-01-10 00:33
I suspect that a quick solution to this problem may be to remove (or replace with  `' '`) all `\n` here <https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/mod.rs#L2813>

**Comment by durka** [comment] 2017-01-10 00:43
I don't think that's a great fix. I think the problem is that re-exported macros are stored into metadata in tokenized form, losing the original source formatting.

**Comment by QuietMisdreavus** [comment] 2017-01-10 19:25
It looks more like that line you found is what prints each rule. Digging further, it seems to go through a [ToSource trait](https://github.com/rust-lang/rust/blob/cbf88730e755d099c854f84dd0f1990490bf0088/src/librustdoc/clean/mod.rs#L2677) which eventually calls [`span_to_snippet`](https://github.com/rust-lang/rust/blob/master/src/libsyntax/codemap.rs#L632), which is where I would expect the formatting to come from.

**Comment by cbreeden** [comment] 2017-01-10 20:13
I'm a little surprised that the highlighting doesn't work correctly, after looking at [https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/highlight.rs#L245](this).  I don't believe there is much we can do about the formatting that comes from `span_to_snippet` given how macros are re-exported; though this might change once Macros 2.0 is here and so macros are given a bona fide path.

Until then I think the solution would be to manually handle the formatting given a TokenStream.  Last night I was going to try to do some debugging to see what the `$` formatting given in the docs above didn't trigger, but didn't get around to it.

**Comment by lukaramu** [comment] 2017-04-13 20:20
I ran across another manifestation of this today: [the reexported version of Entry in std::collections::btree_map::Entry][0] uses `where` clauses for lifetime bounds, while [the original version of Entry in collections::btree_map][1] doesn't; it seems like this is not strictly limited to macros.

[0]: https://doc.rust-lang.org/nightly/std/collections/btree_map/enum.Entry.html
[1]: https://doc.rust-lang.org/nightly/collections/btree_map/enum.Entry.html

**Comment by steveklabnik** [comment] 2018-10-31 15:59
Triage: the formatting is still a bit strange; the src links work great though.

**Comment by jyn514** [comment] 2021-03-25 19:26
I think this may be a duplicate of https://github.com/rust-lang/rust/issues/36722.

**Comment by jyn514** [comment] 2021-04-08 18:33
This is fixed on master. 
![image](https://user-images.githubusercontent.com/23638587/114078798-5cc6e180-9877-11eb-81c3-50dd83f09588.png)

**Closed by jyn514** 2021-04-08 18:33 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
