### ISSUE TITLE
Setting fields of moved values

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#36313] opened 2016-09-07 02:16 UTC
We've talked about this before, and I know its currently 'correct' behavior, but I wanted to submit this as a UX papercut. Writing to the fields of moved values should be treated as a use after move.

I was trying to demonstrate to a newer Rust user how it won't allow you to create cyclic structures without shared ownership constructs. I wrote this code, to create a linked list loop:

```rust
struct Node {
    next: Option<Box<Node>>,
}

fn main() {
    let mut first = Node { next: None };
    let second = Node { next: Some(Box::new(first)) };
    first.next = Some(Box::new(second));
}
```

Of course, this currently compiles. This was surprising to me at first, and I modified it to examine the type to figure out what was going on:

```rust
#[derive(Debug)]
struct Node {
    next: Option<Box<Node>>,
}

fn main() {
    let mut first = Node { next: None };
    let second = Node { next: Some(Box::new(first)) };
    first.next = Some(Box::new(second));
    println!("{:?}", first);
}
```

This didn't compile, because the println was a use after move.

To a user who doesn't already know this quirk of Rust, this sequence of events would be completely baffling. How does the println use after move when the field setting doesn't? I really think assigning fields on moved values should be a use after move.

**Comment by sfackler** [comment] 2016-09-07 04:03
Duplicate of #21232.

**Closed** 2016-09-07 04:33 UTC
