### ISSUE TITLE
Can't build old pull request for Cargo with current nightly Rust.

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#32185] opened 2016-03-11 00:25 UTC
```
$ git fetch https://github.com/rust-lang/cargo refs/pull/2013/head
$ git checkout FETCH_HEAD
$ rustc --version
rustc 1.7.0 (a5d1e7a59 2016-02-29)
$ cargo build
...
src/bin/bench.rs:64:25: 64:32 warning: private type in public interface, #[warn(private_in_public)] on by default
src/bin/bench.rs:64:25: 64:32 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
...
(success)
```

It builds, although with a deprecation warning.

Now trying with nightly:

```
$ multirust override nightly
multirust: using existing install for 'nightly'
multirust: override toolchain for '/mnt/src/git/cargo' set to 'nightly'
$ rustc --version
rustc 1.9.0-nightly (eabfc160f 2016-03-08)
$ cargo build
/home/vi/.multirust/toolchains/nightly/cargo/registry/src/github.com-48ad6e4054423464/regex-0.1.41/src/prefix.rs:46:12: 46:24 error: private type in public interface [E0446]
```

That's more or less expected,

```
$ rm Cargo.lock
$ cargo build
...
src/bin/cargo.rs:63:15: 63:20 error: Cannot declare a non-inline module inside a block unless it has a path attribute
src/bin/cargo.rs:63         $mac!(bench);
                                  ^~~~~
src/bin/cargo.rs:63:15: 63:20 note: Maybe `use` the module `bench` instead of redeclaring it
src/bin/cargo.rs:63         $mac!(bench);
...
```

but this is not. There was no warning about modules with stable. Also error message does not show macro context correctly (there is [X macro](https://en.wikipedia.org/wiki/X_Macro) `each_subcommand!` in use).

In up-to-date there are 3 invocations (one of which explicitly to declare a module) in use instead of two, so it is expected to work there, but maybe it has been turned into a hard error a bit too eagerly?

**Comment by alexcrichton** [comment] 2016-03-11 01:34
Out of curiosity, did this turn out to be a problem? This was the only crate which regressed with this new error, so it was thought that we could just locally fix Cargo and call it a day.

**Comment by alexcrichton** [comment] 2016-03-11 01:34
cc @jseyfried @nikomatsakis

**Comment by vi** [comment] 2016-03-11 02:58
Not a big problem, since stable Rust works.

> This was the only crate which regressed

Which only crate? Regex (about privacy)? Cargo (about modules)?

Shall the issue be specified to some one of three issues:

1. regex module and privacy (probably not needed)
2. modules and paths and blocks
3. missing context when error is macro substitution

, with the other one extracted to a separate issue?

**Comment by alexcrichton** [comment] 2016-03-11 04:46
Oh sorry I missed that error, the one I was talking about was the macro-defining-a-module one.

**Comment by nikomatsakis** [comment] 2016-03-14 12:03
In general, we make a best effort to issue a warning/deprecation period for every change, but it's not a **guarantee**. Maintaining those warning periods takes significant engineering effort so we can't do it for every change. In this case, since this was a small bugfix with very small impact, we opted to forego the warning period. This does mean though that the older version of crates.io will not build with nightly, since it doesn't have the fix applied. (Note that the seem would eventually be true even *with* a deprecation period, since that deprecation period eventually expires.)

**Comment by nikomatsakis** [comment] 2016-03-14 12:04
@vi did you need to build with that specific version of cargo for some reason? Or were you just alerting us to the regression?

**Comment by vi** [comment] 2016-03-14 13:36
Mostly the second. On IRC they say "If it builds with stable, not now with nightly then it may be mistake and should generally be reported".

Cargo uses Stable Rust (without `#![feature]`), so it I expected "once it builds, it will build" behaviour.

> very small impact

I expect things that implements doing multiple commands in one tool the same style as in Cargo (basically copied old version of Cargo and retooled to do something else) may also break.

Maybe there should be at least special acknowledgement in the warning message static in which version did the breacking changed occured, like

```
error: Cannot declare a non-inline module inside a block unless it has a path attribute
note: It was valid before Rust 1.8
```

Without this one cannot easily see if a given code snipped no _longer_ compiles or just doesn't and didn't compile.

**Comment by nikomatsakis** [comment] 2016-03-15 21:07
> I expect things that implements doing multiple commands in one tool the same style as in Cargo (basically copied old version of Cargo and retooled to do something else) may also break. 

Perhaps. I believe though that we did measure with crater though and did not observe breakage in the wild, apart from cargo. (Obviously crater is an imperfect tool, though, so the measurements must be taken with a grain of salt.)

**Comment by nikomatsakis** [comment] 2016-03-15 21:08
I'm marking this as relnotes, but I think we'll close the issue as working as expected. @vi, thanks for the report in any case (we do indeed like to be alerted to regressions).

**Closed by nikomatsakis** 2016-03-15 21:08 UTC
Labels: relnotes
