### ISSUE TITLE
Trait bound on associated type is not recognized, fails to accept valid code

### ISSUE THREAD

**Issue by oliver-giersch** [rust-lang/rust#73927] opened 2020-07-01 15:33 UTC
```rust
#![feature(trait_alias)]

// associated base trait
trait AssocBase {}
// associated extension trait
trait Assoc: AssocBase {}

// base trait
trait Base {
    type AssocBase: AssocBase;
}

// trait alias using stable syntax (variant A)
trait AliasA: Base where <Self as Base>::AssocBase: Assoc {}

// could be blanket implemented
// impl<U> AliasA for U
// where
//     U: Base, <U as Base>::AssocBase: Assoc
// {}

// trait alias using nightly syntax (variant B)
trait AliasB = Base where <Self as Base>::AssocBase: Assoc;

fn uses_alias_a<U: AliasA>() {}  // <----- this version does not compile
// fn uses_alias_a<U: AliasA>()
// where
//     <U as Base>::AssocBase: Assoc
// {}                            // <----- this version compiles, but the bound
//                                         has to be repeated
fn uses_alias_b<U: AliasB>() {}  // <----- this version compiles as expected
```
In this code excerpt ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=817773325f8d65445defee2f6fe95fee)) the bound on the associated type of the base trait (`trait AliasA`) is not actually recognized at the site where the trait is itself used as a bound, which results in this trait being unusable as a trait bound without further bounding the associated type again, rendering it in fact useless.
Interestingly, using the nightly `trait_alias` feature (variant B), the bound is correctly inferred.
This behavior can be observed on the current stable (variant A) and nightly (A & B).

**Comment by jonas-schievink** [comment] 2020-07-01 15:40
Duplicate of https://github.com/rust-lang/rust/issues/20671

**Closed by jonas-schievink** 2020-07-01 15:40 UTC
Labels: C-bug
