### ISSUE TITLE
nightly-2020-11-29 fails to compile ring

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rust#79535] opened 2020-11-29 14:38 UTC
### Code

Unable to compile gotham because it's ring dependency failed to build. Relevant CI run: https://travis-ci.com/github/gotham-rs/gotham/jobs/450258121#L866

### Meta

```
$ rustc +nightly-2020-11-29 --version --verbose
rustc 1.50.0-nightly (e37f25aa3 2020-11-28)
binary: rustc
commit-hash: e37f25aa3f356546ab851e394d5598fc575eabda
commit-date: 2020-11-28
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
$ cargo +nightly-2020-11-29 test --all
......

thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:1306 ~ ring[4704]::digest::sha2::)`,
 right: `DefId(0:1307 ~ ring[4704]::digest::sha2::::GFp_sha256_block_data_order)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e37f25aa3f356546ab851e394d5598fc575eabda/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/e37f25aa3f356546ab851e394d5598fc575eabda/library/core/src/panicking.rs:92:14
   2: rustc_middle::hir::map::collector::NodeCollector::insert_entry
   3: rustc_hir::intravisit::walk_item
   4: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   5: rustc_hir::intravisit::walk_item
   6: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   7: rustc_hir::intravisit::walk_item
   8: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   9: rustc_middle::hir::map::index_hir
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::get_query_impl
  13: core::ops::function::FnOnce::call_once
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::get_query_impl
  17: rustc_middle::hir::map::Map::expect_item
  18: rustc_middle::hir::map::Map::visit_item_likes_in_module
  19: rustc_passes::hir_id_validator::check_crate
  20: rustc_interface::passes::analysis
  21: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::get_query_impl
  25: rustc_interface::passes::QueryContext::enter
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  27: rustc_span::with_source_map
  28: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (e37f25aa3 2020-11-28) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [index_hir] index HIR
#1 [hir_owner] HIR owner of `{misc#0}`
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `ring`

```

**Comment by jonas-schievink** [comment] 2020-11-29 14:40
duplicate of https://github.com/rust-lang/rust/issues/79487

**Closed by jonas-schievink** 2020-11-29 14:40 UTC
Labels: C-bug, I-ICE, T-compiler
