### ISSUE TITLE
Using inference to coerce a closure to a trait object on the result of a match causes segfault

### ISSUE THREAD

**Issue by renato-zannon** [rust-lang/rust#20717] opened 2015-01-07 21:49 UTC
Now that's a convoluted title :)

This was reported by user krdln [on reddit](http://www.reddit.com/r/rust/comments/2rnak6/clusure_types_in_match_arms_cannot_be_unified/cnhhlg1).

I'm using:
```
rustc 1.0.0-nightly (ea6f65c5f 2015-01-06 19:47:08 +0000)
binary: rustc
commit-hash: ea6f65c5f1a3f84e010d2cef02a0160804e9567a
commit-date: 2015-01-06 19:47:08 +0000
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```

Minimal example:

```rust
fn main() {
    let _f: Box<Fn()> = match 0 { 
        0 => box || {}, 
        _ => box || {}
    };  
}
```

GDB backtrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x00005555555592f0 in Box$LT$core..ops..Fn$LP$$RP$$GT$::glue_drop.1074::h5c0bbc43321199cc ()
#2  0x0000555555558e32 in bug::main () at bug.rs:2
#3  0x0000555555564239 in rust_try_inner ()
#4  0x0000555555564226 in rust_try ()
#5  0x0000555555561bcf in rt::lang_start::h50187c8fd9c16c7bLaz ()
#6  0x0000555555558fa5 in main ()
```

Interestingly, this (AFAIU) semantically equivalent program doesn't segfault:

```rust
fn main() {
    let _f = match 0 {
        0 => (box || {}) as Box<Fn()>,
        _ => (box || {}) as Box<Fn()>
    };  
}
```

**Comment by huonw** [comment] 2015-01-07 22:29
Dupe of https://github.com/rust-lang/rust/issues/20419. Thanks for filing!

**Closed by huonw** 2015-01-07 22:29 UTC

**Comment by renato-zannon** [comment] 2015-01-07 22:32
Oops, sorry about the dupe!
