### ISSUE TITLE
Incremental(?) ICE with BorrowMutError

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/rust#86585] opened 2021-06-23 20:13 UTC
This ICE appeared when I switched branches from https://github.com/rust-lang/stdsimd/pull/139 to https://github.com/rust-lang/stdsimd/pull/138/files and ran `cargo check`. It disappeared as soon as I tapped `cargo clean`, so I suspect it's related to incremental compilation somehow. Alas, I didn't think to do anything to get a good backtrace. 

### Meta

`rustc --version --verbose`:
```
rustc 1.54.0-nightly (6c2dd251b 2021-06-05)
binary: rustc
commit-hash: 6c2dd251bbff03c7a3092d43fb5b637eca0810e3
commit-date: 2021-06-05
host: x86_64-pc-windows-msvc
release: 1.54.0-nightly
LLVM version: 12.0.1
```

### Error output

```
> cargo check
thread 'rustc' panicked at 'already borrowed: BorrowMutError', /rustc/6c2dd251bbff03c7a3092d43fb5b637eca0810e3\compiler\rustc_data_structures\src\sync.rs:423:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (6c2dd251b 2021-06-05) running on x86_64-pc-windows-msvc


note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `core_simd`

Caused by:
  process didn't exit successfully: `rustc --crate-name core_simd --edition=2018 crates\core_simd\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"std\"" -C metadata=b0e59160fd03a692 -C extra-filename=-b0e59160fd03a692 --out-dir ${PATH}\stdsimd\target\debug\deps -C incremental=${PATH}\stdsimd\target\debug\incremental -L dependency=${PATH}\stdsimd\target\debug\deps` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

**Comment by Enselic** [comment] 2023-09-09 10:07
Triage: Since there currently is no known way for others to reproduce this ICE, I will close this issue. Without a way for others to reproduce, not much can be done. Feel free to re-open if a way to reproduce is found.

**Closed by Enselic** 2023-09-09 10:07 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
