### ISSUE TITLE
HKL-bound associated type's associated type as return makes function call's temporary receiver not live through its statement

### ISSUE THREAD

**Issue by soltanmm** [rust-lang/rust#30583] opened 2015-12-28 05:38 UTC
```Rust
trait A<'self_> {
    type Foobar; // : 'self_; // <-- adding this doesn't help
    fn i_work(&'self_ self) -> &'self_ usize;
    fn i_fail(&'self_ self) -> Self::Foobar;
}
trait B<'self_> {
    type MyA: for<'s> A<'s>;
    fn my_a(&'self_ self) -> Self::MyA;
    fn do_stuff(&'self_ self) {
        self.my_a().i_work();
        self.my_a().i_fail();
    }
}

fn main() {
}
```

[play-pen](http://is.gd/vlSI0s)

The `i_work` function is there to emphasize that associated types coming from traits with lifetimes seem to be getting treated weirdly. I don't know what's happening, but I'd have expected that if `i_fail` failed, so'd `i_work`...

### Error
```
<anon>:11:9: 11:20 error: borrowed value does not live long enough
<anon>:11         self.my_a().i_fail();
                  ^~~~~~~~~~~
<anon>:11:9: 11:30 note: reference must be valid for the destruction scope surrounding statement at 11:8...
<anon>:11         self.my_a().i_fail();
                  ^~~~~~~~~~~~~~~~~~~~~
<anon>:11:9: 11:30 note: ...but borrowed value is only valid for the statement at 11:8
<anon>:11         self.my_a().i_fail();
                  ^~~~~~~~~~~~~~~~~~~~~
<anon>:11:9: 11:30 help: consider using a `let` binding to increase its lifetime
<anon>:11         self.my_a().i_fail();
                  ^~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by arielb1** [comment] 2015-12-28 20:27
This is a duplicate of #22323.

**Closed by arielb1** 2015-12-28 20:27 UTC
