### ISSUE TITLE
A big regression in tokio-webpush-simple-opt

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#58368] opened 2019-02-11 09:40 UTC
On Jan 19th the [tokio-webpush-simple-opt/patched incremental: println-opt](https://perf.rust-lang.org/compare.html?start=1bc6baec76f4540c87b23ef349c664fd427d0f53&end=c87144f3caf9a1580e8734d4d1604e723a5bd6e6&stat=instructions%3Au) benchmark regressed by 88.5% in the instruction count.

I was able to narrow the source of the regression down to this [commit diff](https://github.com/rust-lang/rust/compare/1bc6baec76f4540c87b23ef349c664fd427d0f53...c87144f3caf9a1580e8734d4d1604e723a5bd6e6).

**Comment by michaelwoerister** [comment] 2019-02-11 12:39
Thanks for opening the issue, @ljedrz! That is a big regression indeed.

**Comment by michaelwoerister** [comment] 2019-02-11 12:39
cc @rust-lang/wg-compiler-performance

**Comment by dotdash** [comment] 2019-02-11 16:27
Local testing suggests that this is due to commit https://github.com/rust-lang/rust/commit/ff19a53ef07566aa30860023f6eac6e75ffaf900 "Querify entry_fn", which seems to cause inc.comp. to hand more code to LLVM. Reverting that patch brings performance back to the old level.

This fits the fact that the regression only hits benchmarks that have a patch that affects main() and didn't already require pretty much a full rebuild with that patch anyway, i.e. the patched incremental time already matched the baseline time.

**Comment by dotdash** [comment] 2019-02-11 16:27
cc @Xanewok

**Comment by Xanewok** [comment] 2019-02-12 09:30
I'm looking at the diff again and can't find an obvious culprit - we do a HIR walk and find and return a stable defid + type, which is cheap to copy and called rarely..

@michaelwoerister  unless changes to `main` body changes its DefId and possibly invalidates [monorphization](https://github.com/rust-lang/rust/commit/ff19a53ef07566aa30860023f6eac6e75ffaf900#diff-484fc819e81dce826e702d5223abc827R78) or [typeck](https://github.com/rust-lang/rust/commit/ff19a53ef07566aa30860023f6eac6e75ffaf900#diff-1d1b0d29a2e8da97c6bfb6e364d920c7R1167) due to newly introduced data dependency?

Simple `main` changes in `coercions` and `deep-vector`, and `hello-word` induce small, almost-constant increase in instruction count as opposed to the tokio one, where it almost doubles.

I'll try profiling this by hand and will come back with the results.

**Comment by jonas-schievink** [comment] 2019-03-27 00:08
Has anyone had time to look into this more deeply?

**Comment by spastorino** [comment] 2020-07-09 14:51
This was [discussed in today's weekly meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-07-09.20.2354818/near/203392994). Removing nomination.

**Comment by nikomatsakis** [comment] 2020-07-16 14:39
I wonder if we should just close this issue by now. I guess there is *potentially* still usefully information in here. cc @rust-lang/wg-incr-comp -- I think y'all should make the call of whether to investigate this! :)

**Comment by pnkfelix** [comment] 2022-12-16 16:43
I think we've long missed our window to extract useful data from this; there isn't even a tokio-webpush-simple-opt benchmark up on perf.rust-lang.org anymore

closing

**Closed by pnkfelix** 2022-12-16 16:43 UTC
Labels: I-compiletime, P-high, T-compiler, regression-from-stable-to-stable, A-incr-comp, C-bug, WG-incr-comp

**Comment by nnethercote** [comment] 2022-12-19 00:42
`tokio-webpush-simple` was moved earlier this year to the "stable" category, which means it's now only used for the long-term tracking done on [the dashboard](https://perf.rust-lang.org/dashboard.html), not for the day-to-day tracking.

I agree closing this issue is the right thing to do.
