### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by dlaronson** [rust-lang/rust#20571] opened 2015-01-05 10:43 UTC
While updating some of my code to compile under the new updates to rust-nightly, I caused the compiler to panic. Here is the output of rustc -v:

src/lib.rs:420:1: 434:2 error: internal compiler error: impl `VtableImpl(impl_def_id=DefId { krate: 0, node: 2045 }:Items<'a, T>.Iterator, substs=Substs[types=[[_];[];[]], regions=[['_#0r];[];[]]], nested=[[Obligation(predicate=Binder(TraitPredicate(TraitRef(T, core::kinds::Sized))),depth=1)];[];[]])` did not contain projection for `Obligation(predicate=<Items<'a, T> as TraitRef(Items<'a, T>, core::iter::Iterator)>::Item,depth=0)`
src/lib.rs:420 impl<'a, T> Iterator for Items<'a, T> {
src/lib.rs:421     #[inline]
src/lib.rs:422     fn next(&mut self) -> Option<&'a T> {
src/lib.rs:423         if self.tail + self.gtail - self.ghead == self.buff.len() { return None };
src/lib.rs:424         let tail = get_idx(self.tail, self.gtail - self.ghead, self.ghead);
src/lib.rs:425         self.tail += 1;
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123

**Comment by oakes** [comment] 2015-01-05 17:06
Possible duplicate of #20347

**Comment by huonw** [comment] 2015-01-06 11:36
Looks like a dupe; thanks for filing!

In this case the fix is writing `type Item = &'a T;` in the body of the impl.

**Closed by huonw** 2015-01-06 11:36 UTC
Labels: I-ICE
