### ISSUE TITLE
Use link rel="canonical" to doc.rust-lang.org in HTML docs

### ISSUE THREAD

**Issue by geofft** [rust-lang/rust#18558] opened 2014-11-03 00:25 UTC
I'm fairly often finding old versions of Rust docs from other sites when I Google things. For instance, searching for 'rust macro_rules' finds me http://web.mit.edu/rust-lang_v0.9/doc/guide-macros.html (as the second result, after the [Rust by Example page](http://rustbyexample.com/staging/macros.html)), and the rust-lang.org page is nowhere to be found. Googling 'ContravariantLifetime' finds me http://www.contrib.andrew.cmu.edu/~acrichto/doc/std/kinds/marker/struct.ContravariantLifetime.html .

One way to avoid this going forward would be for the documentation included in release tarballs to use a `<link rel="canonical">` tag pointing to the corresponding doc.rust-lang.org URL for that documentation page. This would allow the pages to be viewed directly without redirects (preserving local use), but any search engine juice would be repointed at the official URL.

See the following pages for discussion on canonical links:
- https://support.google.com/webmasters/answer/139066#2
- https://developer.mozilla.org/en-US/docs/Web/HTTP/www_and_non-www_URLs#Using_link_with_the_attirbute_rel.3D.22canonical.22
- https://www.mattcutts.com/blog/canonical-link-tag/
- http://moz.com/blog/complete-guide-to-rel-canonical-how-to-and-why-not

The other option would be to include `<meta name="robots" content="noindex">` in the documentation in tarballs, which would completely prevent them from getting indexed. This tag would of course need to not be in the doc.rust-lang.org version; I don't know if this would be difficult.

I could probably create a PR if that would be helpful, but I'm not at all familiar with the doc generation and release tarball creation process.

**Comment by steveklabnik** [comment] 2016-11-15 20:35
Triage: no change.

**Comment by luser** [comment] 2018-03-01 16:05
Duplicate of https://github.com/rust-lang/rust/issues/9461 ?

**Comment by jsha** [comment] 2021-11-30 02:17
I think this issue has largely resolved itself - doc.rust-lang.org now ranks rather high. For instance, `[rust macro_rules]`, the starting example here, now shows doc.rust-lang.org as the top two results.

**Comment by camelid** [comment] 2022-01-09 02:17
Should this issue be closed then?

**Closed** 2022-01-09 14:52 UTC
Labels: T-rustdoc, C-enhancement, T-dev-tools
