### ISSUE TITLE
Codegen forgets array size when used with iterators

### ISSUE THREAD

**Issue by orlp** [rust-lang/rust#63552] opened 2019-08-14 11:58 UTC
Consider these three functions:

```
pub fn in_range1(x: [usize; 3], m: usize) -> bool {
    (x[0] < m) && (x[1] < m) && (x[2] < m)
}

pub fn in_range2(x: [usize; 3], m: usize) -> bool {
    for k in &x {
        if *k >= m {
            return false;
        }
    }

    true
}

pub fn in_range3(x: [usize; 3], m: usize) -> bool {
    x.iter().cloned().all(|k| k < m)
}
```

I'd expect all of them to generate roughly the same code since our array `x` has a fixed compile-time size. With rustc 1.27.1 [it does](https://rust.godbolt.org/z/zbmg8p), but after that it seems there was a regression that causes the compiler to forget the size of the array and generate [generic code](https://rust.godbolt.org/z/zFhGI5) rather than code specific for the array size when an iterator is used.

Particularly damning is that the compiler generates an unrolled loop which is dead code as our array isn't large enough to ever qualify for unrolling.

**Comment by andjo403** [comment] 2019-08-15 22:13
have bisected this regression and it is the PR rust-lang/llvm#115 that causes the regression.
maybe @nikic knows what can cause this regression.

**Comment by nikomatsakis** [comment] 2019-08-29 15:26
Going to mark this as P-medium. Would be great however if @nikic, @nagisa, @rkruppe or some other LLVM expert could weigh in on likely causes and whether we can fix it. Thanks to @andjo403 both for isolating the issue and bisecting it!

**Comment by nikic** [comment] 2019-11-01 20:42
It looks like this problem is resolved in nightly: https://rust.godbolt.org/z/txaVfL The generated code is quite similar now. Don't know what is responsible for this though.

**Closed** 2022-08-02 19:48 UTC
Labels: A-LLVM, I-slow, P-medium, T-compiler, regression-from-stable-to-stable, C-bug, WG-codegen, A-iterators
