### ISSUE TITLE
ICE compiling `objc v0.2.1` on current nightly

### ISSUE THREAD

**Issue by TyOverby** [rust-lang/rust#36898] opened 2016-10-01 18:15 UTC
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:        0x1126ec938 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x1126fa0af - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x1126f75ad - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x1126f7c46 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x1126f7ae4 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x1126f7a02 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x1126f7967 - rust_begin_unwind
   8:        0x112737c20 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x112737b24 - core::panicking::panic::h1a2d1a6b50eaa468
  10:        0x10eca8033 - rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor::visit_invoc::h1ffde3beaeda5557
  11:        0x10eca0922 - rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver<'a>>::visit_expansion::ha1f7cee58f82f9da
  12:        0x11232e5eb - syntax::ext::expand::MacroExpander::collect_invocations::hac509c4490fb88f2
  13:        0x11232c3a2 - syntax::ext::expand::MacroExpander::expand::h737d7f1635448d5d
  14:        0x11232adc5 - syntax::ext::expand::MacroExpander::expand_crate::hd89d06b7a6333976
  15:        0x11233552d - syntax::ext::expand::expand_crate::h80012253cfa7f1f5
  16:        0x10e5ac23b - rustc_driver::driver::phase_2_configure_and_expand::{{closure}}::hc795707fb140075e
  17:        0x10e564844 - rustc_driver::driver::phase_2_configure_and_expand::h04526112c643cb41
  18:        0x10e55f222 - rustc_driver::driver::compile_input::h5b63ccd49eeeb98b
  19:        0x10e587579 - rustc_driver::run_compiler::h98c7274e7cb1d11d
  20:        0x10e4c8e98 - std::panicking::try::do_call::h99ed0da044e497c3
  21:        0x1126fa66a - __rust_maybe_catch_panic
  22:        0x10e4e86df - <F as alloc::boxed::FnBox<A>>::call_box::hbdd5a14cd8e33b97
  23:        0x1126f6864 - std::sys::thread::Thread::new::thread_start::h50b05608a499d2b2
  24:     0x7fff8bf2299c - _pthread_body
  25:     0x7fff8bf22919 - _pthread_start

Build failed, waiting for other jobs to finish...
error: Could not compile `objc`.
```

**Comment by TimNN** [comment] 2016-10-01 18:26
Looks like a duplicate of #36816, should be fixed by #36819 in the next nightly.

**Closed** 2016-10-01 21:40 UTC
