### ISSUE TITLE
Automatically implementing Sync for all types with Sync members considered harmful

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/rust#43981] opened 2017-08-18 19:14 UTC
So, I had [an interesting side-discussion with vitalyd today](https://users.rust-lang.org/t/thread-synchronization-performance-issues/12380/15) on users.rust-lang.org regarding what it truly means for a type to be Sync in Rust.

According to the Nomicon, ["A type is Sync if it is safe to share between threads"](https://doc.rust-lang.org/nomicon/send-and-sync.html). To most people, one implication of this statement is that operations on this type should be thread-safe, in the sense that it should be impossible for one thread to mutate an object of this type and for another thread to concurrently observe the object in a half-modified, inconsistent state.

This requirement is trivially met for all types which cannot be mutated through a shared reference, i.e. any type which doesn't exhibit interior mutability. However, for those remaining types, I think we might currently automatically derive Sync a bit too eagerly.

Consider the following very silly type definition, which you should never use at home, but which every multi-threading beginner has written a variant of at some point in their life:

```rust
use std::sync::atomic::{AtomicU8, AtomicU16, Ordering};

struct SillyDate {
    day: AtomicU8,
    month: AtomicU8,
    year: AtomicU16,
}

impl SillyDate {
    fn set(&self, day: u8, month: u8, year: u16) {
        self.day.store(day, Ordering::Relaxed);
        self.month.store(month, Ordering::Relaxed);
        self.year.store(year, Ordering::Relaxed);
    }

    fn get(&self) -> (u8, u8, u16) {
        let day = self.day.load(Ordering::Relaxed);
        let month = self.month.load(Ordering::Relaxed);
        let year = self.year.load(Ordering::Relaxed);
        (day, month, year)
    }
}
```

In rustc's current automatic trait derivation rules, [this type is Sync](https://play.rust-lang.org/?gist=3b39e17c5948fabb7dbb5c8713fedb9f&version=nightly). However, if get() and set() are called from different threads, it can quite obviously result in get() potentially observing the object in an inconsistent state. So this type is not really "safe to share between multiple threads" in the sense where most people would understand that expression.

One possible observation would be that this is not strictly speaking a data race, and therefore not something which rustc's definition of Sync should guard against. To this argument, I will contend that if we only cared about not being able to cause data races from Safe Rust code, raw pointers could just as well be made Sync, since safe code cannot use them to cause a data race and with unsafe, all bets are off anyway.

The Nomicon itself exposes some doubt that data race freedom should be all that matters in order to consider a type Sync:

> TODO: better explain what can or can't be Send or Sync. Sufficient to appeal only to data races?

As an alternative, I would propose that the automatic derivation rules for Sync be changed so that this trait be not automatically derived for a given type if that type contains at least two objects with interior mutability.

This change could break some existing code, so if we end up agreeing that it is a good idea in principle, it would be important to check how much existing crates rely on Sync being automatically derived for types with two or more internally mutable members.

What do you think?

**Comment by sfackler** [comment] 2017-08-18 22:30
Is `SillyDate` intended to be thread safe? If not, why is it using `AtomicU8` in the first place? If it is intended to be thread safe, then it's just a buggy type, and having to type `unsafe impl Sync for SillyDate {}` doesn't seem like it would do much to inform the author that their code is wrong.

**Comment by vitalyd** [comment] 2017-08-18 23:06
@sfackler, I think that's just an example of a struct auto deriving to Sync purely because it's composed of Sync components.  The example is trivial and isn't real code one would write (I think @HadrienG2 said that).  But one can imagine someone "accidentally" getting Sync-derived but using it inappropriately, maybe even unintentionally behind layers of abstraction that obscures the code.

I'd have to agree that OIBIT for Sync is dangerous.  There's no "lint" speed bump to make an author pause to ensure they maintain proper invariants across individual Sync values.  I get why it was designed like this (mostly for anon compiler structs? i.e. closures).  But it being auto derived and thus hidden from source is worrisome.

**Comment by HadrienG2** [comment] 2017-08-19 08:13
Exactly. My point was that (internally mutable) Sync types do not necessarily compose well with each other, and that automatically deriving Sync for types which are made of combinations of other Sync types may be inappropriate in the "Sync means thread-safe" interpretation.

Having to type `unsafe impl Sync for SillyDate {}` means that the author needs to pause and wonder "Hey, wait a minute, why isn't this type considered Sync by the compiler by default?". The unsafe impl signals that there is an underlying interface contract (thread-safety) which the compiler cannot check, but which should be honored before implementing Sync for a type.

**Comment by HadrienG2** [comment] 2017-08-19 08:42
@rkruppe : Thanks for your very detailed analysis! It does clear up a number of things to me.

In this case, it seems to me that a better way to approach the problem that @vitalyd and I described above would be to have a collection of _safe_ marker traits which represent the thread safety properties of a type, _in addition_ to the Sync trait which merely means "data-race free" (i.e. UB is avoided, and that's it).

For example, one could imagine a basic Consistent marker which means that a type can be concurrently modified and observed without any inconsistent state leaking out (which is a weaker property than linearizability, since the type can go through N different consistent state over the process of being modified instead of one).

Do you think that this would be a more interesting design direction to explore?

**Comment by rkruppe** [comment] 2017-08-19 09:21
Yes, separate marker traits seem a more viable approach. I immediately have two questions, though:

1. Are they supposed to be auto traits? Then the usual rules (auto trait is implemented if all fields implement it) don't suffice, as noted in the issue description, and adding support for a kind of auto trait that fits would have to be justified.
2. How would linters identify "using something from multiple threads"? Off the top of my head, the only criterion I can think of would be if a `T: Sync` obligation is generated, e.g. from calling a function like `std::thread::spawn` or `rayon::join`. However, that seems hard to implement and prone to false positives (because it's so broad). Do you have other ideas?

**Comment by HadrienG2** [comment] 2017-08-19 09:57
Concerning your first question, I think it is safe to say that not all useful thread-safety properties could be automatically proven by a Rust compiler today, and that at least some of them will need to be manually checked by developers.

For example, elaborating on my consistency notion above, I would understand a consistent state as a state that fulfills all of a type's invariants. But in today's Rust, these invariants are not spelled anywhere out in code, and are only known to the developer. So how should a compiler tell whether they are maintained or not? Consider the following strawman code, for example:

```rust
struct OptionMutex {
    wrapping: Mutex<Option<i32>>,
}

impl OptionMutex {
    fn new(data: i32) -> Self {
        Self {
            wrapping: Mutex::new(Some(data)),
        }
    }

    fn set(&self, data: i32) {
        *self.wrapping.lock().unwrap() = None;
        // ...some slow computation...
        *self.wrapping.lock().unwrap() = Some(data);
    }

    fn get(&self) -> i32 {
        self.wrapping.lock().unwrap().expect("Oh no!")
    }
}
```

Is None a consistent state for the internal mutex-protected data? The fact that get() panics if it is encountered suggests that it is not the case. But should a compiler need to understand error reporting in order to decide whether a certain trait should be automatically derived or not? And if not, how should it know that this None should not have been exposed to the outside world?

I would thus leave at least some thread-safety properties as something which a developer must manually check at this point in time.

**Comment by HadrienG2** [comment] 2017-08-19 13:17
Your second question is more difficult for me to answer, mostly because I do not understand the current Rust implementation well enough yet. Looking at the documentation for std::thread::spawn, I see that it only requires the inner functor to be Send, so it is not immediately obvious to me how the compiler is about to tell that every piece of data used by the functor is Sync.

My intuitive understanding is that this property implicitly emerges from the fact that the functor can only be Send if all the data that it manipulates by reference is Sync, because &T is only Send if T is Sync. Is this understanding correct?

**Comment by rkruppe** [comment] 2017-08-19 13:29
That is roughly correct, though closures are not really special in this regard. See http://huonw.github.io/blog/2015/05/finding-closure-in-rust/ and http://huonw.github.io/blog/2015/05/defaulting-to-thread-safety/

**Comment by vitalyd** [comment] 2017-08-19 14:48
Thanks for the good discussion @rkruppe and @HadrienG2.

It's nice to confirm, really, that Sync is purely about data races - nothing more.  I suspect part of the issue is the way Sync is commonly taught and statements like "fearless concurrency".  I've heard people compare, say, Java to Rust and say how Rust is better because you can't just share any random object across threads - "there's Sync the compiler enforces" they say.  While the Sync part is true, Java doesn't define data races as UB.  You get undefined *results*, not behavior.  So looking at it from that angle, Rust and Java are about the same.  Rust makes data races UB and adds Sync to prevent that; Java doesn't have UB for data races, and therefore doesn't need Sync.

I do think Sync probably shouldn't have been an OIBIT.  It could've been a #[derive(Sync)] type of marker (doesn't work for closures, I know), where the user requests the type to be checked for data race freedom.  I think concurrency is too subtle to be easily enabled.  There are too many hazards beyond simply data races (where those are UB); their absence is merely a prerequisite to even talk about concurrency.  As I mentioned in the rust users thread, memory ordering of Sync structures needs to be understood by users because they need to know how surrounding code will behave.  To reinforce my point, lack of a data race against a single memory location is just a way to prevent UB in Rust - it's nothing more.  So perhaps the issue, as mentioned, is that this stuff needs to be spelled out more and people should be clearly aware of what they get with Sync, and maybe more importantly, what they don't.

**Comment by HadrienG2** [comment] 2017-08-19 16:11
@rkruppe : Thanks for the explanations and links! Let me try to summarize a bit the discussion so far, both as a way to make things easier to new readers and as a sanity check that I didn't misunderstand some aspect of the problem:

* As of today, T: Sync pretty much means "Operations on &T are data race free".
* Being data-race free is a necessary, but not sufficient condition to being thread-safe in the sense that most people think. In particular, one basic constituent of thread safety is the non-observability of inconsistent type states, which Sync does not guarantee on its own.
* We don't want Sync to be extended to mean "thread-safe", for at least two reasons. It would break too much existing code, and it would unpleasantly increase the scope of "unsafe" in Rust.
* Nevertheless, descriptions of Sync can sometimes get uncomfortably close to "Sync means thread-safe", showing that there is a desire for stronger thread-safety guarantees being expressed through the type system, allowing Rust to deliver more of its [fearless concurrency](https://blog.rust-lang.org/2015/04/10/Fearless-Concurrency.html) promise.
* Unfortunately, it seems pretty clear that even a property as simple as consistency can not easily be automatically proven by a Rust compiler (due to lack of developer input on what _is_ a consistent state for a given type) and will need to be manually checked by a human.
* This raises the following question: once this guarantee has been manually proven for a given type, can it reliably be "bubbled up" the call chain in order to detect when potentially thread-unsafe Sync types end up shared (or shareable) between threads, and warn the user about it through a lint?

As we discussed, the way in which a Rust implementation asserts that a thread will only share Sync data with other threads is through the combination of the following three rules:

* The callable that a thread will execute must be Send
* A type will only be automatically inferred to be Send if it is composed of Send data
* A shared reference to a Sync object is Send

Clearly, the third rule plays a central role here. If we were to introduce, for example, a Consistent marker trait which says that a given type provides a consistency guarantee during multi-threaded use, we would somehow need to propagate this guarantee when a reference to this type is taken, and later brought into a more complex compound type (like a closure object that is passed into thread::spawn).

The first part is easy, we could just follow in the footsteps of the Send/Sync relationship and do something like this:

```rust
impl<'a, T> ConsistentRef for &'a T
    where T: Consistent + ?Sized
```

On the other hand, the second part seems nontrivial. As shown in the beginning of this discussion, a type composed of consistent members may not be consistent itself, and the same consideration applies to types composed of references to consistent objects: they might well do something silly that breaks the consistency guarantee. For example, the inconsistent OptionMutex type above might as well be rewritten in terms of a `&Mutex<Option<i32>>` reference instead of a `Mutex<Option<i32>>` value, it would still be inconsistent even though the underlying Mutex type is consistent because the OptionMutex has an additional type invariant with respect to its Mutex implementation.

Moreover, proving the consistency of types which only hold *references* to consistent objects seems even more difficult than proving the consistency of types which hold consistent *values* (for which I already wouldn't have a good solution), because with references there is a risk of some unknown piece of code in the distance also messing with the referenced data behind our back.

I guess that unless I missed something, this means that properties like consistency cannot be conveniently checked by the Rust type system as of today, and will need to remain a fully manual affair at this point... 😞

**Comment by rkruppe** [comment] 2017-08-19 16:21
@vitalyd I can't say I agree with your analysis of data races in Rust vs Java, or of Sync being an auto trait. But let's not delve further into such philosophical debates&mdash;Rust is not going to change in these respects (as that would be backwards incompatible). So we're left with the suggestion that the intrincacies of `Sync` should be documented better, which is pretty unobjectionable. If you (or anyone else) knows specific places that cold be improved, I'd recommend opening an issue.

**Comment by rkruppe** [comment] 2017-08-19 16:30
@HadrienG2 Sounds about right.

I feel compelled to point out, though, that interior mutability is necessary to have any cross-thread mutation. (The huge subset of data *without* interior mutability is, incidentially, one reason why I am opposed to making `Sync` opt-in.) An auto trait for absence of interior mutability is conceivable, and would probably supply a decent baseline for any attempt to encode stronger guarantees in traits (whether automatically-inferred or not).

**Comment by sfackler** [comment] 2017-08-19 16:32
A long time ago, such a trait existed (`Freeze`). It was removed IIRC because it wasn't ever really used in practice.

**Comment by vitalyd** [comment] 2017-08-19 16:43
@rkruppe, what specifically do you disagree with? I was relaying what I've heard people say after reading about Sync and hearing the "fearless concurrency" mantra. I'm curious because I might be missing something here.  I also realize that status quo isn't changing, but it's an interesting discussion nonetheless because it can inform how to teach/document Sync.

For the record, I do think Rust provides a better threadsafety story than the likes of Java, just not because of Sync.  Instead, I'm quite fond of the way types like Mutex wrap the interior value and don't let you mistakenly operate on it outside the lock.  This is a very nice programming model, as opposed to data and the lock being separate fields (pretty much all other languages).

**Comment by rkruppe** [comment] 2017-08-19 17:06
@vitalyd I don't want to derail this thread, but very briefly put, I believe Rust shines in the absence of interior mutability, which is quite common even in concurrent code. You don't slap atomics or locks on data just because (if for no other reasons than how much line noise that would cause). Therefore, a large portion of data is trivially "thread-safe" in the strongest sense, and that the rest can be accessed concurrently at all is a conscious decision by someone (using atomics or locks, rather than `Cell` et al. or `&mut`).

There's no compiler-checked guarantee the human who made that decision picked the guarantees that you might want, let alone implemented them correctly, but it's a far better default than the equivalent of atomics with `unordered` loads and stores everywhere.

**Comment by vitalyd** [comment] 2017-08-19 17:15
Well, the lack of interior mutability is still an interesting case.  Suppose I construct a value, mutate some state and then publish an immutable reference to other threads via some Sync channel.  Unless that Sync channel provides the proper ordering guarantees of stores that occurred prior to the publication, the consumers (other threads) may see a partially initialized object.  Of course the onus is on the Sync channel implementer to do the correct thing, but the immutable reference itself doesn't actually guarantee anything for this case.

**Comment by rkruppe** [comment] 2017-08-19 17:22
Precisely because of the "mutate and publish" cases (which cover practically every instance of sharing data across threads, if you include initalization in "mutating"), anything which publishes data to other threads needs to establish happens-before between writes in the source thread and reads in the destination threads. Not guaranteeing that causes not just race conditions, but data races as well. A channel that does not do so is simply unsound.

**Comment by vitalyd** [comment] 2017-08-19 19:07
Agreed.  My point was mostly that an immutable reference on its own doesn't necessarily guarantee anything - other types must provide additional guarantees to avoid races.  I'm not sure the example qualifies as a *data* race though, but it's a race condition - the reader may see valid written values just not in the right order.

The reason I'm harping on this is because Java has the notion of final fields in an object.  If your object consists purely of final fields, then there's no way to publish it unsafely - readers either see a fully constructed object or null, nothing in between.  They accomplish this via a memory model rule that requires JVMs to put additional fences, either compiler only or cpu as well depending on target arch, that prevent reordering of assignment to a reference with the initializing stores.  People with a Java background may misinterpret Sync as being something similar, which obviously it's not.

This all comes back to documentation and how Sync is taught.  There's nothing wrong with it, per se, and it's an improvement over languages like C and C++.  But, there needs to be very clear documentation on what it provides and doesn't provide, as mentioned.  I found the nomicon and rust std docs not comprehensive enough in this regard.  There's room for improvement, IMO.

**Comment by rkruppe** [comment] 2017-08-19 19:33
> I'm not sure the example qualifies as a data race though, but it's a race condition - the reader may see valid written values just not in the right order.

I'd have to double check (or better, consult someone who has a better grasp of LLVM memory model) to be sure, but I believe channels and the like **must** guarantee that *all* writes that happened in the source thread happen-before the threads they are now granting access to, and thus those threads may only see the last (in program order) value written by the source thread. If this is not given, it seems easy to construct cases where other threads can observe invalid states in ways that cause UB (e.g., after a `Vec::push`, seeing the updated `len` but not the write of the element).

In any case, we're rapidly moving away from the topic of this issue. If you want to discuss further, please open a separate issue (e.g., asking that the behavior you describe is documented), a thread on one of the forums, or ping me on IRC.

**Comment by HadrienG2** [comment] 2017-08-20 12:21
As for the original topic, I think we've pretty much went around it, unless someone else has something interesting to say on this topic (e.g. has more background in formal proof and disagrees with my statement that consistency is hard to automatically prove).

**Comment by Mark-Simulacrum** [comment] 2017-08-20 18:49
I'm going to go ahead and close this in favor of discussion elsewhere: an issue on rust-lang/rfcs or internals.rust-lang.org. We try to keep the issue tracker solely for bugs, while this is more of a discussion issue.

**Closed by Mark-Simulacrum** 2017-08-20 18:49 UTC
Labels: A-typesystem, I-needs-decision, T-lang
