### ISSUE TITLE
Generic to determine size at compile time

### ISSUE THREAD

**Issue by Wmaxlees** [rust-lang/rust#26865] opened 2015-07-07 20:26 UTC
It would be nice to be able to make a datatype like the following:

```
type tname<N> = Vec<[int; N]>;
```

Where N is not a type but an integer. So, for example:

```
let instance = tname::<5>::new();
```

would create an instance of `Vec<int; 5]>`

**Comment by steveklabnik** [comment] 2015-07-07 20:50
We do have http://doc.rust-lang.org/std/mem/fn.size_of.html to determine size at compile time, but it doesn't seem this is exactly what you're talking about.

To put a `5` in a type position like this, we would need https://github.com/rust-lang/rfcs/issues/1038 , I think, and so this feels like a duplicate of that to me.

**Comment by Wmaxlees** [comment] 2015-07-07 20:56
Yeah I think that it is a duplicate of that other issue.

**Closed** 2015-07-07 22:01 UTC
