### ISSUE TITLE
Public tuple structs give dead_code warnings on nightly

### ISSUE THREAD

**Issue by djkato** [rust-lang/rust#127735] opened 2024-07-14 21:07 UTC
### Code

```Rust
use serde::Serialize; // 1.0.203
#[derive(Serialize, Debug, Clone)]
#[serde(transparent)]
pub struct OrderCalculateTaxes(CheckoutCalculateTaxesResponse);

#[derive(Serialize, Debug, Clone)]
#[serde(transparent)]
pub struct ShippingListMethodsForCheckout(Vec<ShippingListMethodsForCheckoutVec>);

#[derive(Serialize, Debug, Clone)]
pub struct ShippingListMethodsForCheckoutVec {
    pub id: String,
    pub currency: String,
    pub maximum_delivery_days: Option<i32>,
}

#[derive(Serialize, Debug, Clone)]
pub struct CheckoutCalculateTaxesResponse {
    pub some_value: String,
}
```

### Current output

```Shell
warning: struct `OrderCalculateTaxes` is never constructed
 --> src/lib.rs:4:12
  |
4 | pub struct OrderCalculateTaxes(CheckoutCalculateTaxesResponse);
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: struct `ShippingListMethodsForCheckout` is never constructed
 --> src/lib.rs:8:12
  |
8 | pub struct ShippingListMethodsForCheckout(Vec<ShippingListMethodsForCheckoutVec>);
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `playground` (lib) generated 2 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.50s
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.72s
```

### Rationale and extra context

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a317497cf4017ba3f7b5d963270b032e
Nightly version gives dead code errors on public tuple structs, and on stable it doesn't.

### Rust Version

```Shell
(master)> rustc --version --verbose
rustc 1.81.0-nightly (d8a38b000 2024-06-19)
binary: rustc
commit-hash: d8a38b00024cd7156dea4ce8fd8ae113a2745e7f
commit-date: 2024-06-19
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7

AND

On playground https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a317497cf4017ba3f7b5d963270b032e
```

### Anything else?

Not sure where to put this issue, if I labelled baldy, then I'm sorry :pray:

**Comment by eggyal** [comment] 2024-07-14 21:35
Because the fields are private, they can't be constructed by downstream crates and therefore the compiler is correct that they are unused.

If you make the fields public, the warning goes away: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=83d9eb9d0cf35ee0a919b61b17acb168

**Comment by workingjubilee** [comment] 2024-07-14 22:10
They also go away if you add constructor functions:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a317497cf4017ba3f7b5d963270b032e

**Comment by djkato** [comment] 2024-07-14 22:42
Ooh, thanks @eggyal & @workingjubilee for explaining. Sorry, my mistake! So this means nightly is actually the new correct warning and stable is not correct?

**Comment by workingjubilee** [comment] 2024-07-14 22:58
Yes, previously the Clone implementations were suppressing the lint.

**Comment by workingjubilee** [comment] 2024-07-14 23:07
Closing due to "working as intended", but feel free to reopen if you find something else odd here!

**Closed by workingjubilee** 2024-07-14 23:07 UTC
Labels: A-diagnostics, T-compiler
