### ISSUE TITLE
internal compiler error: unexpected vtable type

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#33956] opened 2016-05-30 05:05 UTC
`error: internal compiler error: ../src/librustc_const_eval/eval.rs:1052: resolve_trait_associated_const: unexpected vtable type`

Playground link: https://is.gd/89hb8e

**Comment by sanmai-NL** [comment] 2016-05-30 18:29
Could you provide more information? See https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md

**Comment by yongqli** [comment] 2016-05-30 19:09
The error can be reproduced by going to the playground link and clicking Run.

**Comment by nagisa** [comment] 2016-05-30 20:17
Duplicate of https://github.com/rust-lang/rust/issues/29924. Thanks for the report.

**Closed by nagisa** 2016-05-30 20:17 UTC
Labels: I-ICE
