### ISSUE TITLE
On Windows, winapi no longer builds with latest pc-windows-gnu nightlies

### ISSUE THREAD

**Issue by Osspial** [rust-lang/rust#65387] opened 2019-10-13 17:16 UTC
This error seems to have been introduced by `rust version 1.40.0-nightly (6767d9b90 2019-10-11)`. To reproduce, clone https://github.com/retep998/winapi-rs.git on a Windows system and build with `nightly-2019-10-11-x86_64-pc-windows-gnu`. Building with `nightly-2019-10-10-x86_64-pc-windows-gnu` seems to work fine, though.

This was discovered with Winit's Appveyor builds started failing on the latest nightlies. [This is the latest working build log](https://ci.appveyor.com/project/Osspial/winit/builds/28056303/job/hpa177vwi8cyhkp1), and [this is the first failing build log](https://ci.appveyor.com/project/Osspial/winit/builds/28064160/job/4psg9kurxb7dfajr)

For reference, here is the relevant error:

```
   Compiling winapi v0.3.8
 0651e182d9.exe" "C:\\projects\\winit\\target\\debug\\build\\winapi-i686-pc-windows-gnu-c863180651e182d9\\build_script_build-c863180651e182d9.1dauco0fgj24pype.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\projects\\winit\\target\\debug\\deps" "-L" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libstd-d0bf6b84273155d7.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libpanic_unwind-68cebc1f5a91b0ea.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libhashbrown-941b71b3cac1cf75.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-384899e40f06e6e6.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libbacktrace-854375a285306767.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libbacktrace_sys-c1755aeb8fa11602.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_demangle-579144285cb80d57.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libunwind-c2806ccb478b3a20.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcfg_if-65fc01038edbe751.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liblibc-92e015ddde9d0a69.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc-3465a9beb3406152.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_std_workspace_core-687f6def4492b905.rlib" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcore-0e0f8b6dff870c49.rlib" "-Wl,--end-group" "C:\\Users\\appveyor\\.rustup\\toolchains\\nightly-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcompiler_builtins-f883bba0a403afe6.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "rsend.o"
  = note: gcc.exe: error: crt2.o: No such file or directory
          gcc.exe: error: rsbegin.o: No such file or directory
          gcc.exe: error: rsend.o: No such file or directory
```

**Comment by jonas-schievink** [comment] 2019-10-13 17:20
duplicate of https://github.com/rust-lang/rust/issues/65335

**Closed by jonas-schievink** 2019-10-13 17:20 UTC
