### ISSUE TITLE
Bounds on associated types of super-traits not propagated

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#44656] opened 2017-09-17 15:07 UTC
[MWE on the playground:](https://play.rust-lang.org/?gist=308084f1b4ace26ead6e5f387988c290&version=stable)

```rust
pub trait WithAssoc {
  type Assoc;
  fn wa(&self) {}
}

pub trait Baz {}

pub trait Moo: WithAssoc
  where Self::Assoc: Baz // this is allowed
{}

pub trait Foo: Moo
// where Self::Assoc: Baz // but bound is not propagated
{
  fn foo(&self) {
    self.wa();
  }
}

fn main() {}
```

**Comment by arielb1** [comment] 2017-09-17 15:11
duplicate of #20671

**Closed** 2017-09-17 15:10 UTC

**Comment by gnzlbg** [comment] 2017-09-17 15:32
@arielb1 I want to write a trait like this:

```rust
pub trait Point: std::ops::Index<usize> where Self::Output: Float {};
```

but if I do that I need to repeat that where clause everywhere where I use the trait.

If I could write my own index trait I would just do:

```rust
pub trait Index<T> {
  type Output: Float;
  fn index...
}
```

and then I can just require that and never have to write the bound. Is there a way to add that bound externally so that I don't have to repeat it everywhere?

**Comment by arielb1** [comment] 2017-09-17 16:29
> and then I can just require that and never have to write the bound. Is there a way to add that bound externally so that I don't have to repeat it everywhere?

Not that I know of. The implied bounds RFC *might* improve the situation in the future - got to talk about that with @nikomatsakis .

**Comment by gnzlbg** [comment] 2017-09-17 16:39
The following works:

```rust
pub trait Point: std::ops::Index<usize, Output = <Self as Point>::Output>{
 type Output: Float;
}
```
