### ISSUE TITLE
Resolving static method on a type is not consistent in macros

### ISSUE THREAD

**Issue by wigy-opensource-developer** [rust-lang/rust#58731] opened 2019-02-25 16:17 UTC
It is a bit counter-intuitive that I can call an inherent method inside a macro expansion, but I cannot do so on a type that was deduced by a macro expansion. (rustc 1.32.0)

```rust
macro_rules! choose_type {
    (a) => { Concrete };
}

macro_rules! create_type {
    ($some:ident) => { $some::create() }
}

struct Concrete {}

impl Concrete {
    fn create() -> Self {
        println!("Concrete::execute was called");
        Concrete {}
    }
}

fn main() {
    let _t1 = create_type!(Concrete);
    let _t2 = choose_type!(a)::create();
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4dc98f42a5b2962597943087c437cff5))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `.`, `;`, `?`, or an operator, found `::`
  --> src/main.rs:20:30
   |
20 |     let _t2 = choose_type!(a)::create();
   |                              ^^ expected one of `.`, `;`, `?`, or an operator here
...
```

How is the `create_type` macro more hygienic than the `choose_type` one?

**Comment by jonas-schievink** [comment] 2019-02-25 16:36
You have to do `<choose_type!(a)>::create();` to parse the macro as a type.

**Comment by petrochenkov** [comment] 2019-02-25 16:58
Duplicate of https://github.com/rust-lang/rust/issues/52307.

For some reason the note recommending to rewrite things like `[x; N]::method()` into `<[x; N]>::method` is not reported for `mac!(x)::method()`.

**Closed by petrochenkov** 2019-02-25 16:58 UTC

**Comment by wigy-opensource-developer** [comment] 2019-02-25 18:09
Wow. Thanks for the prompt answers. So basically I can use the more verbose <Type>::method() format anywhere and in some cases even the Type::method() works, but that is more like an exception than the rule :wink: 

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=083a2c442599bf86910de81ba032dd1f)
