### ISSUE TITLE
crater run to estimate impact of full NLL transition

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#60680] opened 2019-05-09 20:00 UTC
In the @rust-lang/lang meeting today, we were saying it'd be a good idea to do a crater run against full NLL just to get a rough idea of how many affected crates there will be.

There are two ways we could do this and both have some value:

- change the "warning lints" to "deny" and then do the crater run. This has the benefit that if crate X fails to compile, dependencies of crate X will still be tested, giving a more accurate overall picture.
- change default borrowck mode to NLL. This has the advantage that some errors (notably regionck errors) that are no longer relevant are disabled. However, I think we will overall get an underestimate this way, plus there are still (maybe) some soundness holes.

**Comment by Centril** [comment] 2019-05-09 20:03
I would suggest that we do both of the two ways since it's an important ticket.

**Comment by pnkfelix** [comment] 2019-05-16 10:49
cc #43234

**Comment by pnkfelix** [comment] 2019-05-16 10:52
triage:  this is an important task, but not one that I find should be prioritized over the various bugs currently plaguing the compiler.

Marking as P-medium.

I'm not sure why @Centril nominated it. Its possible that they nominated it solely for prioritization. Or its possible they wanted it to get attention from the compiler team. I'm going to leave the nomination tag on for now, with the understanding, that if we do discuss it at the T-compiler meeting and manage to assign it to someone, then we can remove the nomination tag.

**Comment by lqd** [comment] 2019-05-16 21:07
I will try to help @pnkfelix with this.

**Comment by pnkfelix** [comment] 2019-05-17 09:18
@lqd looks like the easiest way to go is to open two distinct PR's corresponding to the two avenues outlined in the description, right?

**Comment by lqd** [comment] 2019-05-17 12:26
(we talked about this in this [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/122657-t-compiler.2Fwg-nll/topic/.2360680.20full.20NLL.20crater.20runs)) yes and I opened #60911 and #60914 for these 2 avenues

**Comment by lqd** [comment] 2019-05-23 06:47
Copying triage results over from each PR:

#### #60914:
[These 87 crates](https://gist.github.com/lqd/aca30ac14e7f8c6b429a87af25c465c8#file-report-deps-md) caused 1859 crates to fail downstream, while [these 54 crates](https://gist.github.com/lqd/aca30ac14e7f8c6b429a87af25c465c8#file-report-crates-md) themselves failed to build.

There is some overlap between these 2 categories: so this PR impacted around 130 root crates. I remember a lot of those from the previous crater runs, with legit errors — some of them fixed in more recent versions of the crates (including semver-compatible releases only requiring a `cargo update` to fix the NLL errors) .


#### #60911:

Here as well, these [99 crates](https://gist.github.com/lqd/36f62e379ae0d39c3f96c449aaef0042#file-report-deps-md) caused 1892 failures downstream, while these [140 crates](https://gist.github.com/lqd/36f62e379ae0d39c3f96c449aaef0042#file-report-crates-md) themselves failed to build. 

That's 220 crates in total (all the 131 in #60914 + [these 89 new ones](https://gist.github.com/lqd/74378ebba533a228f622adc894cb548f)).

**Comment by Centril** [comment] 2019-05-23 06:52
Nominating for lang team (possibly also compiler team for execution) to discuss ^-- and how to proceed with that data.

**Comment by Centril** [comment] 2019-05-23 22:13
We did not get to discuss this on the language team meeting. Revisiting next time.

**Comment by Centril** [comment] 2019-05-30 21:07
Sadly, we did not have enough time to discuss this on the language team meeting this week either, rescheduling for next time.

**Comment by pnkfelix** [comment] 2019-06-20 19:50
discussed in lang team meeting.

One trend we noted with the listed regressions is that a lot of the problems are coming from ... "old crates", and the main point will be "yep, someone needs to update their dependencies."

So, as part of that, is that we want to write a blog post discussing the overall plan here. in particular, we want to discuss the overall migration to NLL, stating that NLL is coming for every Rust edition, and then saying that the final transition (to hard errors) is fixing soundness bugs. So, part of that post will present a representative sample of real world code with bugs that are being detected by NLL.

(I am taking on the job of writing the aforementioned post; @nikomatsakis is going to provide guidance about *where* the post will end up being published; i.e. what forum is most appropriate for it. I plan to have the post ready in time for the next Rust release.)

**Comment by Centril** [comment] 2019-06-20 20:12
(With my release team hat on, we will need to talk about NLL in 2015 in the 1.35.0 blog post in any case, and so linking to the aforementioned to-write blogpost would be a ideal).

**Comment by Stargateur** [comment] 2019-07-04 14:29
Can you only list crate `>= 1.0.0` ? Maybe sort by last update too.

I mean if I understand correctly, these crates "should" not compile, there are probably not maintains. Do we really have the ressource to keep them working for almost no gain ?

**Closed** 2019-09-05 16:17 UTC
Labels: A-NLL, P-medium, T-compiler, T-lang
