### ISSUE TITLE
Cargo in docker can't find Cargo.toml

### ISSUE THREAD

**Issue by jhfrontz** [rust-lang/rust#65711] opened 2019-10-22 22:56 UTC
As of `nightly-2019-10-21`, *cargo* seems to be unable to find the `Cargo.toml` file in the current working directory of a docker-based gitlab CI job:

```
$ pwd
/builds/jhf/functionary
$ head -1 /builds/jhf/functionary/Cargo.toml
###
$ CARGO_LOG="trace" cargo build
[2019-10-22T20:16:20Z DEBUG cargo] exit_with_error; err=CliError { error: Some(ErrorMessage { msg: "could not find `Cargo.toml` in `/builds/jhf/functionary` or any parent directory" }), unknown: false, exit_code: 101 }
error: could not find `Cargo.toml` in `/builds/jhf/functionary` or any parent directory
```

(maybe related to https://github.com/rust-lang/rust/issues/65662 ?)

**Comment by jonas-schievink** [comment] 2019-10-23 09:23
Can you run this with `strace` to find out whether this is due to `statx`?

**Comment by jhfrontz** [comment] 2019-10-23 15:07
> Can you run this with `strace` to find out whether this is due to `statx`?

I ran with `strace` but I'm not sure what I'm looking for -- I don't see any `statx` calls in the trace, but I do see a bunch of `ENOENT` (and other failures).  It's hard to tell which are happening "normally" as part of checking for things.  I'll work on sanitizing a trace to post.

**Comment by sfackler** [comment] 2019-10-23 16:04
syscall_332 is statx, so this is a duplicate of #65662

**Closed by sfackler** 2019-10-23 16:04 UTC
