### ISSUE TITLE
Rust shows internal lifetime repr

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#40632] opened 2017-03-18 11:55 UTC
https://github.com/bjorn3/rust_blogpost_ui/tree/fb560c78a6e737561ef769673ddc39515df4a77b fails to compile with
```
$ cargo run
   Compiling rust_blogpost_ui v0.1.0 (~/Documents/rust_blogpost_u
i)
error[E0281]: type mismatch: the type `[closure@src/main.rs:25:20: 28:10]` implemen
ts the trait `for<'r> std::ops::Fn<(&'r mut cursive::Cursive, &'r post::Post)>`, bu
t the trait `for<'r, 'r> std::ops::Fn<(&'r mut cursive::Cursive, &'r _)>` is requir
ed (expected concrete lifetime, found bound lifetime parameter )
  --> src/main.rs:25:10
   |
25 |         .on_submit(|s, post: &post::Post| {
   |          ^^^^^^^^^

error[E0271]: type mismatch resolving `for<'r, 'r> <[closure@src/main.rs:25:20: 28:
10] as std::ops::FnOnce<(&'r mut cursive::Cursive, &'r _)>>::Output == ()`
  --> src/main.rs:25:10
   |
25 |         .on_submit(|s, post: &post::Post| {
   |          ^^^^^^^^^ expected bound lifetime parameter , found concrete lifetime
   |
   = note: concrete lifetime that was found is lifetime ReSkolemized(1, BrAnon(1))

error: aborting due to 2 previous errors

error: Could not compile `rust_blogpost_ui`.

To learn more, run the command again with --verbose.
```

Notice the `ReSkolemized(1, BrAnon(1))`

rust info:
```
$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
beta-2016-12-20-x86_64-apple-darwin
nightly-2016-04-14-x86_64-apple-darwin
nightly-2016-04-25-x86_64-apple-darwin
nightly-2016-09-29-x86_64-apple-darwin
nightly-2016-09-30-x86_64-apple-darwin
nightly-2016-12-29-x86_64-apple-darwin
nightly-x86_64-apple-darwin
nightly-x86_64-pc-windows-gnu

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.16.0 (30cf806ef 2017-03-10)
```

**Comment by estebank** [comment] 2017-03-21 01:17
Duplicate of #13998. ([librustc/infer/error_reporting/mod.rs](https://github.com/rust-lang/rust/blob/b671c32ddc8c36d50866428d83b7716233356721/src/librustc/infer/error_reporting/mod.rs#L219-L229))

**Closed** 2017-03-21 05:39 UTC
Labels: A-diagnostics
