### ISSUE TITLE
rustc 1.65.0 crashes (SIGSEGV) when compiling with --release. Looks like a corner case.

### ISSUE THREAD

**Issue by rewik** [rust-lang/rust#104520] opened 2022-11-17 07:47 UTC
Error happens on 1.65.0, only in release mode.
Code below crashes the compiler on cargo test --release

### Code

```Rust
use std::cmp;

fn main() {
    println!("Hello World");
}


// bug is triggered when menu is a tuple with an even number of elements. Tuples with an
// odd numer of elements seem to work fine.
// Tested up to size 8
pub struct InternalValue {
    menu: (u8, u8)
}
impl InternalValue {
    pub fn new(menu: u8) -> InternalValue {
        InternalValue { menu: (menu, 2) }
    }
}


#[derive(Debug, Copy, Clone, PartialEq)]
pub enum EmulatedSize {
    Reduced,
    Full,
}
// if MAX_PARAMS is 4, 8 or 16 the bug is not triggered
const MAX_PARAMS:u8 = 3;
// if Reduced and Full are converted to the same value, the bug is no longer triggered
impl From<EmulatedSize> for u8 {
    fn from(et: EmulatedSize) -> Self {
        match et {
            EmulatedSize::Reduced => MAX_PARAMS-1,
            EmulatedSize::Full => MAX_PARAMS,
        }
    }
}


pub struct EmulatedComponent {
    values: [InternalValue; MAX_PARAMS as usize],
}
impl EmulatedComponent {
    pub fn init(id: u8) -> Self {
        EmulatedComponent {
            values: [
                InternalValue::new(id),
                InternalValue::new(id),
                InternalValue::new(id),
            ]
        }
    }
}


pub struct EmulatedDevice {
    variant: EmulatedSize,
    components: Vec<EmulatedComponent>,
}
impl EmulatedDevice {
    pub fn init_with_components(i: u8, variant:Option<EmulatedSize>) -> Self {
        let mut components = Vec::with_capacity(8);

        for x in 0..i {
            components.push(EmulatedComponent::init(x));
        }

        EmulatedDevice{
            variant: variant.unwrap_or(EmulatedSize::Full),
            components,
        }
    }

    pub fn to_0xDC(&self, count: u8, first_id: u8) -> Vec<u8> {
        let max_values_per_component: u8 = self.variant.into();
        let first_component = (first_id / max_values_per_component) as usize;

        let mut no_values_read = 0;
        // commenting out any part of the code in this loop stops the bug from being triggered
        for (curr_id, _) in self.components.iter().enumerate() {
            if curr_id < first_component {
                continue;
            }
            else if count - no_values_read <= 0 {
                break;
            }

            let first_param_id = if curr_id == first_component { first_id % max_values_per_component } else { 0 };
            let params_to_fetch = cmp::min(max_values_per_component - first_param_id, count - no_values_read);
            // code reading the params removed, didn't affect triggering the bug

            no_values_read += params_to_fetch;
        }

        vec![no_values_read, 0x01]
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cause_compiler_sigsegv_on_release() {
        let device = EmulatedDevice::init_with_components(8, None);

        let first_id: u8 = 0;
        let count: u8 = 0xFF;

        let expected: usize = 2;
        let actual: usize = device.to_0xDC(count, first_id).len();

        assert_eq!(expected, actual);
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

1.64.0 debug: OK
1.64.0 release: OK
1.65.0 debug: OK
1.65.0 release: SEGMENTATION FAULT
1.66.0-beta.1 debug: OK
1.66.0-beta.1 release: OK
1.67.0-nightly debug: OK
1.67.0-nightly release: OK

### Error output

```
   Compiling rustc-1_65_0-sigsegv v0.1.0 (/home/REDACTED/Projects/rustc-1_65_0-sigsegv)
warning: field `menu` is never read
  --> src/main.rs:11:5
   |
10 | pub struct InternalValue {
   |            ------------- field in this struct
11 |     menu: (u8, u8)
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field `values` is never read
  --> src/main.rs:42:5
   |
41 | pub struct EmulatedComponent {
   |            ----------------- field in this struct
42 |     values: [InternalValue; MAX_PARAMS as usize],
   |     ^^^^^^

warning: method `to_0xDC` should have a snake case name
  --> src/main.rs:79:12
   |
79 |     pub fn to_0xDC(&self, count: u8, first_id: u8) -> Vec<u8> {
   |            ^^^^^^^ help: convert the identifier to snake case: `to_0x_dc`
   |
   = note: `#[warn(non_snake_case)]` on by default

/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x27d8ea3)[0x7fbadf1d8ea3]
/usr/lib/libc.so.6(+0x38a00)[0x7fbadc6cea00]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(+0x2b55fba)[0x7fbad9d55fba]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(+0x2af197b)[0x7fbad9cf197b]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm15InstCombinePass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE+0x308e)[0x7fbad9cecdfe]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(+0x2ae9d5d)[0x7fbad9ce9d5d]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm11PassManagerINS_8FunctionENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x52d)[0x7fbad965f24d]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm26CGSCCToFunctionPassAdaptor3runERNS_13LazyCallGraph3SCCERNS_15AnalysisManagerIS2_JRS1_EEES5_RNS_17CGSCCUpdateResultE+0x639)[0x7fbada3a35e9]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(+0x31a2f9d)[0x7fbada3a2f9d]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm11PassManagerINS_13LazyCallGraph3SCCENS_15AnalysisManagerIS2_JRS1_EEEJS4_RNS_17CGSCCUpdateResultEEE3runERS2_RS5_S4_S7_+0x698)[0x7fbada17c578]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm21DevirtSCCRepeatedPass3runERNS_13LazyCallGraph3SCCERNS_15AnalysisManagerIS2_JRS1_EEES5_RNS_17CGSCCUpdateResultE+0x3d8)[0x7fbada179b58]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm33ModuleToPostOrderCGSCCPassAdaptor3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0xc4f)[0x7fbada29d38f]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(+0x309c72d)[0x7fbada29c72d]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x156)[0x7fbada4490e6]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm24ModuleInlinerWrapperPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE+0x198)[0x7fbada448c18]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(+0x3248a6d)[0x7fbada448a6d]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libLLVM-15-rust-1.65.0-stable.so(_ZN4llvm11PassManagerINS_6ModuleENS_15AnalysisManagerIS1_JEEEJEE3runERS1_RS3_+0x156)[0x7fbada4490e6]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x2439341)[0x7fbadee39341]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x24357ca)[0x7fbadee357ca]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x2434815)[0x7fbadee34815]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x225f72b)[0x7fbadec5f72b]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x225dc38)[0x7fbadec5dc38]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/librustc_driver-a21dfa8672cc0cdd.so(+0x2238738)[0x7fbadec38738]
/home/REDACTED/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/libstd-05737cf45bd30456.so(rust_metadata_std_71cb4861428b0c25+0xfe003)[0x7fbadc97b003]
/usr/lib/libc.so.6(+0x868fd)[0x7fbadc71c8fd]
/usr/lib/libc.so.6(+0x108a60)[0x7fbadc79ea60]
warning: `rustc-1_65_0-sigsegv` (bin "rustc-1_65_0-sigsegv" test) generated 3 warnings
error: could not compile `rustc-1_65_0-sigsegv`; 3 warnings emitted

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_1_65_0_sigsegv --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --test -C metadata=832711d0ff56b38f -C extra-filename=-832711d0ff56b38f --out-dir /home/REDACTED/Documents/Projects/rustc-1_65_0-sigsegv/target/release/deps -L dependency=/home/REDACTED/Documents/Projects/rustc-1_65_0-sigsegv/target/release/deps` (signal: 11, SIGSEGV: invalid memory reference)
```
also tested on Windows (different machine):
```
   Compiling rustc-1_65_0-sigsegv v0.1.0 (C:\Users\REDACTED\Documents\Projects\rustc-1_65_0-sigsegv)
warning: field `menu` is never read
  --> src\main.rs:11:5
   |
10 | pub struct InternalValue {
   |            ------------- field in this struct
11 |     menu: (u8, u8)
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field `values` is never read
  --> src\main.rs:42:5
   |
41 | pub struct EmulatedComponent {
   |            ----------------- field in this struct
42 |     values: [InternalValue; MAX_PARAMS as usize],
   |     ^^^^^^

warning: method `to_0xDC` should have a snake case name
  --> src\main.rs:79:12
   |
79 |     pub fn to_0xDC(&self, count: u8, first_id: u8) -> Vec<u8> {
   |            ^^^^^^^ help: convert the identifier to snake case: `to_0x_dc`
   |
   = note: `#[warn(non_snake_case)]` on by default

warning: `rustc-1_65_0-sigsegv` (bin "rustc-1_65_0-sigsegv" test) generated 3 warnings
error: could not compile `rustc-1_65_0-sigsegv`; 3 warnings emitted

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_1_65_0_sigsegv --edition=2021 src\main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --test -C metadata=2573ed0a4e436104 -C extra-filename=-2573ed0a4e436104 --out-dir C:\Users\REDACTED\Documents\Projects\rustc-1_65_0-sigsegv\target\release\deps -L dependency=C:\Users\REDACTED\Documents\Projects\rustc-1_65_0-sigsegv\target\release\deps` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

setting RUST_BACKTRACE=1 does not change the output, looks like it crash originates somewhere in llvm code.
</p>
</details>

**Comment by saethlin** [comment] 2022-11-17 18:38
This is an LLVM assertion. If I checkout the 1.65.0 tag and build with LLVM assertions, I get this:
```
rustc: /checkout/src/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = llvm::PHINode, From = llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void>, false, false>]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
warning: `scratch` (bin "scratch" test) generated 3 warnings
error: could not compile `scratch`; 3 warnings emitted

Caused by:
  process didn't exit successfully: `rustc --crate-name scratch --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --test -C metadata=b0e11864599800ac -C extra-filename=-b0e11864599800ac --out-dir /tmp/scratch/target/release/deps -C linker=clang -L dependency=/tmp/scratch/target/release/deps -C link-arg=-fuse-ld=lld` (signal: 6, SIGABRT: process abort signal)
```

@rustbot label +I-prioritize

**Comment by saethlin** [comment] 2022-11-17 20:04
@rustbot lablel +A-llvm

It looks like this assertion is no longer hit. Is that because a bug was fixed, or codegen was altered in a way that just doesn't hit the bad code path anymore?

**Comment by apiraino** [comment] 2022-11-23 12:50
If I bisected this correctly, it _stopped_ erroring in commit 8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6, where we updated LLVM, which seems to confirm the previous comments.


searched nightlies: from nightly-2022-09-01 to nightly-2022-11-22
regressed nightly: nightly-2022-10-01
searched commits: from https://github.com/rust-lang/rust/commit/9c56d9d6fec6262bbb1549cfe466a812ae2c6523 to https://github.com/rust-lang/rust/commit/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6
regressed commit: https://github.com/rust-lang/rust/commit/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc ./script.sh --start 2022-09-01 --preserve --regress non-error 
```
</details>

**Comment by apiraino** [comment] 2022-11-23 12:57
just for me to understand: is there any actionable, anything we want to track in this issue or can we assume this won't resurface and therefore this issue can be closed? thanks

cc @saethlin @rewik

**Comment by saethlin** [comment] 2022-11-23 15:33
Yes exactly. I have no idea if the next stable actually contains a fix, or if for this Rust code we no longer generate LLVM IR that hits this assertion. Someone could investigate this which would require knowledge of LLVM that I do not have, or I'm hoping there is some standard procedure here.

**Comment by apiraino** [comment] 2022-11-29 11:12
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23104520.20rustc.201.2E65.2E0.20crashes.20.28SIGSEGV.29.20when.20compiling.20with.20.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by nikic** [comment] 2022-12-07 17:30
Given that this was fixed by an LLVM update, I don't think there is anything left to investigate here. The relevant fix was most likely https://github.com/rust-lang/llvm-project/commit/be1669163f67dcb517c3053b90fa2fe26e564db4.

**Closed by nikic** 2022-12-07 17:30 UTC
Labels: A-LLVM, I-ICE, P-medium, T-compiler, C-bug
