### ISSUE TITLE
Derivable traits do not work for `PhantomData<T>` if `T` does not impl them as well

### ISSUE THREAD

**Issue by Evrey** [rust-lang/rust#52079] opened 2018-07-05 17:00 UTC
```
My laptop:
rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
nightly-i686-pc-windows-msvc (default)
----
Playpen:
rustc 1.27.0-stable
```

Minimal not working example:
```Rust
use std::marker::PhantomData;

#[derive(Copy, Clone, Eq, PartialEq, Debug)]
struct X<T> {
    data:   u8,
    marker: PhantomData<T>,
}

struct NonDerive(u8);

fn main() {
    let x: X<NonDerive> = X { data: 0, marker: PhantomData };

    let  x2 = x.clone(); // No clone?
    let _x3 = x;         // No copy?
    
    assert_eq!(x, x2);   // No eq? No debug?
    
    drop(x);             // Moved?! (Comment out the `x2` lines.)
}
```
[Playpen Link](https://play.rust-lang.org/?gist=3c28efed757d867734bc2ef23f3265c0&version=stable&mode=debug&edition=2015)

`u8` and friends all implement the standard derivable traits, and [the docs](https://doc.rust-lang.org/nightly/core/marker/struct.PhantomData.html#implementations) state the same thing for `PhantomData<T>`, no matter what `T` is. So... myeah, this should work. Perhaps it is the trait bound resolution of `rustc` who's to blame?

Doesn't quite look like a bug in `#[derive(...)]` itself, as code like this, makes the compiler punch you in the face right away, not needing any usage code to break.
```Rust
struct NonClone(u8);

#[derive(Clone)]
struct What(NonClone); // `rustc`: Wtf R U Doing?! `NonClone` is not `Clone`!
```
Make the `fn main()` above empty and it compiles.

Only caused by `PhantomData`, our little special snowflake. =)

**Comment by pmarcelll** [comment] 2018-07-05 17:23
This is working as intended.

In the first example, `NonDerive` is a newtype, which makes it possible to redefine what traits the underlying type (in this case `u8`) implements. So since `NonDerive` doesn't implement the traits `u8` implements, the deriving is not possible.

And the second example fails to compile. ([playpen link](https://play.rust-lang.org/?gist=789d0008f6da87a65a4afe9a8aa5faca&version=stable&mode=debug&edition=2015))

**Comment by Evrey** [comment] 2018-07-05 17:43
I don't quite see how that might be intended.

The docs say right away that `PhantomData<T>` implements all the standard derivable traits, no matter what `T` is. It states `impl<T: ?Sized> Clone for PhantomData<T>`, not `impl<T: ?Sized + Clone> Clone for PhantomData<T>`. The second example fails to compile, because that's actually what I expect it to do.

In case it wasn't clear enough, I added code snippet 2 to show that code snippet 1 does *(seemingly?)* not fail to `#[derive]`, but fails much later when resolving the trait bounds in usage code. Hence the note about clearing the `fn main()` of snippet 1.

**Comment by pmarcelll** [comment] 2018-07-05 18:15
I see, you're right, so the compiler only sees `X<NonDerive>`, and doesn't see the `PhantomData`. I think it's most probably a bug in `#[derive()]`.
And I misunderstood "Make the fn main() above empty and it compiles.", I thought you were referring to the second example.

**Comment by pmarcelll** [comment] 2018-07-05 18:18
I think this is a duplicate of #26925.

**Comment by Evrey** [comment] 2018-07-05 18:32
This does indeed look like it. Didn't seem like it to me judging by the title alone when I first looked for potential duplicates.

**Comment by dtolnay** [comment] 2018-07-05 20:50
Let's continue to track this in #26925.

**Closed by dtolnay** 2018-07-05 20:50 UTC
