### ISSUE TITLE
asm-src-loc-codegen-units test fails spuriously

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31521] opened 2016-02-09 19:57 UTC
The test may fail spuriously due to interleaved output:

```
error: error pattern ' build without -C codegen-units for more exact errors' not found!
status: exit code: 101
command: x86_64-unknown-linux-gnu/stage2/bin/rustc /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/test/compile-fail/asm-src-loc-codegen-units.rs -L x86_64-unknown-linux-gnu/test/compile-fail/ --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage2-x86_64-unknown-linux-gnu.compile-fail.libaux -C prefer-dynamic -o x86_64-unknown-linux-gnu/test/compile-fail/asm-src-loc-codegen-units.stage2-x86_64-unknown-linux-gnu --cfg rtopt -C rpath -O -L x86_64-unknown-linux-gnu/rt -C codegen-units=2
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'error: codegen-1<inline asm>:1:2: error: invalid instruction mnemonic 'nowayisthisavalidinstruction'
        nowayisthisavalidinstruction
        ^
' panicked at 'Box<Any>', 
../src/libsyntax/errors/mod.rs:note607: 
build without -C codegen-units for more exact errorsnote: Run with `RUST_BACKTRACE=1` for a backtrace.

error: aborting due to previous error
error: aborting due to worker thread panic

------------------------------------------

thread '[compile-fail] compile-fail/asm-src-loc-codegen-units.rs' panicked at 'explicit panic', /buildslave/rust-buildbot/slave/auto-linux-64-opt/build/src/compiletest/runtest.rs:1527
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [compile-fail] compile-fail/asm-src-loc-codegen-units.rs
```

Note how a bunch of actual diagnostics are interleaved and thus the error message we’re looking for gets broken.

**Comment by alexcrichton** [comment] 2016-02-09 21:01
This was a problem long ago and was fixed via 013d47b19b25b94e9740f725425bc836bac6efde, but perhaps some stuff around how we output errors has changed? The fix is likely still similar.

**Comment by nagisa** [comment] 2016-02-09 21:07
cc @nrc likely a regression from the structural errors refactoring.

**Comment by nrc** [comment] 2016-02-09 22:24
More likely the other work I've been doing on handling errors without panicking.

**Comment by Mark-Simulacrum** [comment] 2017-04-29 18:12
Closing. I don't think we've seen this for a while (at least not on Travis/AppVeyor). Please reopen if you see this issue. I'm unable to reproduce locally based on ~1000 runs of this test.

**Closed by Mark-Simulacrum** 2017-04-29 18:12 UTC
Labels: A-testsuite
