### ISSUE TITLE
rustc-ap-rustc_index Fails to compile on ARM with the gcc linker

### ISSUE THREAD

**Issue by nitsuga5124** [rust-lang/rust#76397] opened 2020-09-06 00:43 UTC
### Code
Crate
`rustc-ap-rustc_index`

### Meta

`cross -Vv`
```
cargo 1.47.0-nightly (51b66125b 2020-08-19)
release: 1.47.0
commit-hash: 51b66125ba97d2906f461b3f4e0408f206299bb6
commit-date: 2020-08-19
```

`rustc -Vv` (idk how to get this from cross)
```
rustc 1.47.0-nightly (bf4342114 2020-08-25)
binary: rustc
commit-hash: bf4342114e357f2934d59e12e31e94532ddb2adf
commit-date: 2020-08-25
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 11.0
```

### Error output

`cross build --target armv7-unknown-linux-gnueabihf --release`
```
thread 'rustc' panicked at 'src/librustc_resolve/imports.rs:907:25: inconsistent resolution for an import', /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/src/librustc_middle/util/bug.rs:34:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (bf4342114 2020-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C linker=arm-linux-gnueabihf-gcc --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `rustc-ap-rustc_index`.

Caused by:
  process didn't exit successfully: `rustc --crate-name rustc_ap_rustc_index --edition=2018 /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_index-677.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembed-bitcode=no -C debuginfo=2 -C metadata=bd04023e3f851ad0 -C extra-filename=-bd04023e3f851ad0 --out-dir /target/armv7-unknown-linux-gnueabihf/release/deps --target armv7-unknown-linux-gnueabihf -C linker=arm-linux-gnueabihf-gcc -L dependency=/target/armv7-unknown-linux-gnueabihf/release/deps -L dependency=/target/release/deps --extern arrayvec=/target/armv7-unknown-linux-gnueabihf/release/deps/libarrayvec-b98c7414863e3e8a.rmeta --extern rustc_macros=/target/release/deps/librustc_ap_rustc_macros-37d33213fa5718ca.so --extern rustc_serialize=/target/armv7-unknown-linux-gnueabihf/release/deps/librustc_ap_rustc_serialize-492d61b717736015.rmeta --cap-lints allow` (exit code: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'src/librustc_resolve/imports.rs:907:25: inconsistent resolution for an import', /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/src/librustc_middle/util/bug.rs:34:26
stack backtrace:
   0:     0x7fd4774be5a0 - std::backtrace_rs::backtrace::libunwind::trace::ha1eabb142084ea37
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x7fd4774be5a0 - std::backtrace_rs::backtrace::trace_unsynchronized::hbb8825661d997281
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x7fd4774be5a0 - std::sys_common::backtrace::_print_fmt::h26d850e2f7183914
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/sys_common/backtrace.rs:79
   3:     0x7fd4774be5a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3834b06f68a2b012
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/sys_common/backtrace.rs:58
   4:     0x7fd47752cfac - core::fmt::write::h3a043650ba7bf668
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/core/src/fmt/mod.rs:1082
   5:     0x7fd4774b08c7 - std::io::Write::write_fmt::h9c0c8944a1898139
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/io/mod.rs:1514
   6:     0x7fd4774c3260 - std::sys_common::backtrace::_print::h693c0c2cc41d4d10
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/sys_common/backtrace.rs:61
   7:     0x7fd4774c3260 - std::sys_common::backtrace::print::h213be73e5670b8ea
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/sys_common/backtrace.rs:48
   8:     0x7fd4774c3260 - std::panicking::default_hook::{{closure}}::h2d49a3361cc4e7ea
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/panicking.rs:200
   9:     0x7fd4774c2fac - std::panicking::default_hook::hd41fbdeba93207ba
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/panicking.rs:219
  10:     0x7fd477d3a7b9 - rustc_driver::report_ice::hb57fcf9c0f585ed3
  11:     0x7fd46c33afa6 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h6266408c201df9dd
                               at /rust/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1056
  12:     0x7fd46c31b905 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h1418fcce10178c43
                               at /rust/lib/rustlib/src/rust/library/proc_macro/src/bridge/client.rs:319
  13:     0x7fd4774c3a08 - std::panicking::rust_panic_with_hook::hcab398664b4bd473
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/panicking.rs:573
  14:     0x7fd478b97aab - std::panicking::begin_panic::{{closure}}::hcbf98e7e9fdeeac8
  15:     0x7fd478b978ac - std::sys_common::backtrace::__rust_end_short_backtrace::hba30732d061d338c
  16:     0x7fd478bf8110 - std::panicking::begin_panic::h620d5a1713ff6c0a
  17:     0x7fd478bdfb7d - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::hdc635877327d3225
  18:     0x7fd478bdfa2e - rustc_middle::ty::context::tls::with_opt::{{closure}}::h3b13b6a674f8ff55
  19:     0x7fd478bdf99f - rustc_middle::ty::context::tls::with_opt::hb7eb80fa36344309
  20:     0x7fd478bdfac9 - rustc_middle::util::bug::opt_span_bug_fmt::hd9a4bf46d432d99d
  21:     0x7fd478bdfa83 - rustc_middle::util::bug::span_bug_fmt::h15d5e2dce604b6f2
  22:     0x7fd478cc7a66 - rustc_resolve::imports::ImportResolver::finalize_import::h739d4c9a68ee7b62
  23:     0x7fd478cc55c2 - rustc_resolve::imports::ImportResolver::finalize_imports::h2a68cdf7e6235a28
  24:     0x7fd478c70269 - rustc_resolve::Resolver::resolve_crate::h791eba8e77922c6d
  25:     0x7fd47806254a - rustc_interface::passes::configure_and_expand_inner::hd880720adede20b1
  26:     0x7fd47802a239 - rustc_interface::passes::configure_and_expand::{{closure}}::h0e29c4151fbcfea0
  27:     0x7fd47801f6bf - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::hdfd7dbb0b9eb862c
  28:     0x7fd478060e25 - rustc_interface::passes::configure_and_expand::h0561e619d3ea6666
  29:     0x7fd4780ac358 - rustc_interface::queries::Queries::expansion::h03c4340e7e1e4bec
  30:     0x7fd477d5e127 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h037edd44e25c852a
  31:     0x7fd477cf3ad7 - rustc_span::with_source_map::h8bee9729eacaf0e5
  32:     0x7fd477d5fdb3 - rustc_interface::interface::create_compiler_and_run::hca1ea19f87aad490
  33:     0x7fd477d3e4da - scoped_tls::ScopedKey<T>::set::h98a472b48acc2e14
  34:     0x7fd477d529b7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0fbaefb3a51451a7
  35:     0x7fd477cde0be - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7a49202ee8dc3a27
  36:     0x7fd4774d2fba - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8a8db08de617a605
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/alloc/src/boxed.rs:1042
  37:     0x7fd4774d2fba - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hddfcff0ffd25c0c4
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/alloc/src/boxed.rs:1042
  38:     0x7fd4774d2fba - std::sys::unix::thread::Thread::new::thread_start::h8e648f9ee2e9cb3a
                               at /rustc/bf4342114e357f2934d59e12e31e94532ddb2adf/library/std/src/sys/unix/thread.rs:87
  39:     0x7fd4772166ba - start_thread
  40:     0x7fd476b4041d - clone
  41:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (bf4342114 2020-08-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C linker=arm-linux-gnueabihf-gcc --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rustc-ap-rustc_index`.
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2020-09-06 11:35
Duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2020-09-06 11:35 UTC
Labels: C-bug, I-ICE, T-compiler
