### ISSUE TITLE
rustdoc: search results show promising result, but referent page doesn't contain the named method.

### ISSUE THREAD

**Issue by nathan-at-least** [rust-lang/rust#66164] opened 2019-11-06 16:58 UTC
**Summary:** I search API docs, see a promising result, follow that result to a page, that page does not have the method nor description text that was in the search result. Verified in local docs and officially hosted `docs.rs` docs.

**Details:**

I originally filed this issue in the `tokio` repo thinking it was an API doc bug on their part. Someone suggested it's a rust-doc bug, so here I am. The original issue has a fair amount of detail: https://github.com/tokio-rs/tokio/issues/1738

**Reproduction:**

I haven't literally tested this yet, but I believe it's on the right track:

```bash
$ cargo new docbugdemo
$ cd ./docbugdemo
$ echo 'tokio = "0.2.0-alpha.6" >> Cargo.toml
$ cargo doc --open
```

-then search for `next` or `_::next`, and follow the top hit. On the resulting page use browser find-in-page-search for "next". Observe 0 hits. View the source of that module, use browser find-in-page for "next". Observe 0 hits.

**Investigation:**

I'm missing a lot of context here with both rust-doc and `tokio` API, but I wonder if some of these could be contributors to the bug:

- `tokio` re-exports a lot.
- Maybe `tokio` defines multiple different `_` traits or types in different modules?
- Maybe the name `_` happens to confuse `rust-doc`.

**Related Issues:**
I searched this repo with [`label:T-rustdoc search`](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AT-rustdoc+search) and scanned for duplicates/related items. I believe this bug is unique.

Two relevant results:

- https://github.com/rust-lang/rust/issues/24305 - umbrella issue about re-exports which may encompass this bug. I know `tokio` has many re-exports but I'm not certain yet if that's an issue here.
- https://github.com/rust-lang/rust/issues/63435 - maybe this bug has a similar cause but slightly different conditions?

**Comment by jonas-schievink** [comment] 2019-11-06 17:07
This might be a duplicate of https://github.com/rust-lang/rust/issues/66046. What's the method in the search results you clicked on?

**Comment by nathan-at-least** [comment] 2019-11-07 00:50
In the linked original issue, https://github.com/tokio-rs/tokio/issues/1738, there are screen shots that show the highlighted result I followed, which is to `tokio::prelude::_::next`.

To me it doesn't sound like #66046 is a duplicate, because when I view the source link of the referent page, there's literally no "next" anywhere in the source, so this doesn't seem like a case of a hidden / folded doc item.

**Comment by nathan-at-least** [comment] 2019-11-07 00:51
Hey, I just realized there are multiple extension traits imported `as _`, starting with this line: https://docs.rs/tokio/0.2.0-alpha.6/src/tokio/prelude.rs.html#14

Could it be that this confuses the search indexing?

**Comment by jyn514** [comment] 2021-04-08 17:58
Duplicate of https://github.com/rust-lang/rust/issues/61592, fixed by https://github.com/rust-lang/rust/pull/80267.

**Closed by jyn514** 2021-04-08 17:58 UTC
Labels: C-bug, T-rustdoc
