### ISSUE TITLE
Regression in Beta/Nightly: implementation of `Trait` is not general enough

### ISSUE THREAD

**Issue by msrd0** [rust-lang/rust#106630] opened 2023-01-09 12:22 UTC
### Code

I tried this code:

https://github.com/gotham-rs/gotham/tree/3da82b63e36db81f73f0d88b7610a3979c62289a/examples/handlers/simple_async_handlers_await

I expected to see this happen: Code compiles (as it does on stable: https://github.com/gotham-rs/gotham/actions/runs/3873554934/jobs/6603712754)

Instead, this happened: Code fails to compile (on beta: https://github.com/gotham-rs/gotham/actions/runs/3873554934/jobs/6603712995 and nightly: https://github.com/gotham-rs/gotham/actions/runs/3873554934/jobs/6603713263)

### Version it worked on

It most recently worked on: 1.66.0 (69f9c33d7 2022-12-12)

### Version with regression

1.67.0-beta.6 (51b03459a 2022-12-31) and rustc 1.68.0-nightly (cc47b0699 2023-01-08)

@rustbot modify labels: +regression-from-stable-to-beta

**Comment by albertlarsan68** [comment] 2023-01-09 12:42
searched nightlies: from nightly-2022-10-29 to nightly-2022-12-10
regressed nightly: nightly-2022-12-10
searched commit range: https://github.com/rust-lang/rust/compare/7632db0e87d8adccc9a83a47795c9411b1455855...dfe3fe710181738a2cb3060c23ec5efb3c68ca09
regressed commit: https://github.com/rust-lang/rust/commit/7701a7e7d4eed74a106f39fa64899dffd1e1025f (#105456)

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --access=github --start=1.66.0 --end=2022-12-10 -- build -p=gotham_examples_handlers_simple_async_handlers_await
```
</details>

**Comment by lqd** [comment] 2023-01-09 13:04
@albertlarsan68  The rollup can itself be bisected with [these artifacts](https://github.com/rust-lang/rust/pull/105456#issuecomment-1343907798). I'm pretty sure it's going to be #105255 again.

**Comment by albertlarsan68** [comment] 2023-01-09 14:05
- [ ] #105441
- [ ] #105434
- [ ] #105433
- [ ] #105423
- [ ] #105408
- [ ] #105405
- [ ] #105317
- [ ] #105255
- [ ] #105120
- [ ] #104922

**Comment by albertlarsan68** [comment] 2023-01-09 16:09
It is in fact #105255 that makes this error, cc @cjgillot @compiler-errors

**Comment by apiraino** [comment] 2023-02-15 12:42
Can this be closed since #106759 or it needs more work?

**Comment by wesleywiser** [comment] 2023-02-16 15:51
I think we still would like an mcve and regression test to be added. Lowering priority since this was reverted.

**Comment by msrd0** [comment] 2023-02-16 16:40
Here's a smaller version that fails to compile on `nightly-2023-01-08` but compiles on `rustc 1.67.1 (d5a82bbd2 2023-02-07) (Arch Linux rust 1:1.67.1-1)`:

```rust
mod gotham {
	use std::future::Future;

	pub struct State;

	pub trait IntoResponse {}

	pub struct Response;

	impl IntoResponse for Response {}

	mod private {
		use super::*;

		pub trait HandlerMarker {}

		pub trait AsyncHandlerFn<'a> {
			type Res;
		}

		impl<'a, Fut, R, F> AsyncHandlerFn<'a> for F
		where
			F: FnOnce(&'a mut State) -> Fut,
			Fut: Future<Output = R> + Send + 'a
		{
			type Res = R;
		}

		impl<F, R> HandlerMarker for F
		where
			R: IntoResponse + 'static,
			for<'a> F: AsyncHandlerFn<'a, Res = R> + Send
		{
		}
	}

	pub fn to_async_borrowing<F>(handler: F)
	where
		F: private::HandlerMarker
	{
		_ = handler;
	}
}

use gotham::*;

async fn sleep_handler(_: &mut State) -> impl IntoResponse {
	Response
}

fn main() {
	to_async_borrowing(sleep_handler);
}
```

**Comment by Mark-Simulacrum** [comment] 2023-03-03 16:15
Untagging as a regression since I believe we expect this to already be fixed on beta + nightly as of https://github.com/rust-lang/rust/pull/106759 (and its backport).

**Comment by msrd0** [comment] 2023-03-03 21:33
I managed to get the code that triggers the regression even shorter:

```rust
use std::future::Future;

trait AsyncCallback<'a> {
    type Out;
}

impl<'a, Fut, T, F> AsyncCallback<'a> for F
where
    F: FnOnce(&'a mut ()) -> Fut,
    Fut: Future<Output = T> + Send + 'a,
{
    type Out = T;
}

trait CallbackMarker {}
impl<F, T> CallbackMarker for F
where
    T: 'static,
    for<'a> F: AsyncCallback<'a, Out = T> + Send,
{
}

fn do_sth<F: CallbackMarker>(_: F) {}

async fn callback(_: &mut ()) -> impl Send {}

fn main() {
    do_sth(callback);
}
```

Do you want me to create a PR that adds a test for this code? If so, is there some guide on how to add regression tests?

**Comment by kpreid** [comment] 2023-12-25 16:46
Triage: this has got a MCVE.
@rustbot label -E-needs-mcve

> Do you want me to create a PR that adds a test for this code? If so, is there some guide on how to add regression tests?

@msrd0 I'm not a compiler dev but I believe you simply add a test case file to `tests/ui/` like in [this commit for example](https://github.com/rust-lang/rust/commit/677afb4b4571cc32154f340c26908baa9e1a2540).

**Closed** 2023-12-28 19:58 UTC
Labels: E-needs-test, P-medium, T-compiler, C-bug
