### ISSUE TITLE
[ICE] adding a def'n for node-id NodeId(130468) and def kind AnonConst but a previous def'n exists

### ISSUE THREAD

**Issue by jrose-signal** [rust-lang/rust#129336] opened 2024-08-20 22:23 UTC
### Summary

Running `cargo +nightly check --workspace --all-features --all-targets` in https://github.com/signalapp/libsignal/tree/v0.55.1 produced

> thread 'rustc' panicked at compiler/rustc_ast_lowering/src/lib.rs:505:9:
adding a def'n for node-id NodeId(130468) and def kind AnonConst but a previous def'n exists: DefKey { parent: Some(DefIndex(3382)), disambiguated_data: DisambiguatedDefPathData { data: AnonConst, disambiguator: 0 } }

(sorry for not reducing it)

[rustc-ice-2024-08-20T22_23_14-62651.txt](https://github.com/user-attachments/files/16682943/rustc-ice-2024-08-20T22_23_14-62651.txt)

### Version

```text
rustc 1.82.0-nightly (636d7ff91 2024-08-19)
binary: rustc
commit-hash: 636d7ff91b9847d6d43c7bbe023568828f6e3246
commit-date: 2024-08-19
host: aarch64-apple-darwin
release: 1.82.0-nightly
LLVM version: 19.1.0
```

**Comment by jrose-signal** [comment] 2024-08-20 22:38
Did some bisecting, this was introduced in 2024-07-20. (Also, oops, thanks, I started with Clippy before reproducing with plain check.)

**Comment by jrose-signal** [comment] 2024-08-20 22:47
Very possibly the same as https://github.com/rust-lang/rust/issues/128016.

**Comment by compiler-errors** [comment] 2024-08-20 22:49
Yeah, this is just a duplicate of that. Thanks for the report, but I'd prefer if we track this issue in fewer places.

**Closed by compiler-errors** 2024-08-20 22:49 UTC
Labels: I-ICE, C-bug, needs-triage
