### ISSUE TITLE
Summary issue - stabilization of `!`

### ISSUE THREAD

**Issue by canndrew** [rust-lang/rust#48950] opened 2018-03-12 05:52 UTC
## What is being stabilized

* `!` is now a full-fledged type and can now be used in any type position (eg. [RFC 1216](https://github.com/rust-lang/rfcs/pull/1216)). The `!` type can coerce into any other type, see https://github.com/rust-lang/rust/tree/master/src/test/run-fail/adjust_never.rs for an example.
* Type inference will now default unconstrained type variables to `!` instead of `()`. The [`resolve_trait_on_defaulted_unit`](https://github.com/rust-lang/rust/issues/39216) lint has been retired. An example of where this comes up is if you have something like:

    ```rust
    // We didn't specify the type of `x`. Under some circumstances, type inference
    // will pick a type for us rather than erroring
    let x = Deserialize::deserialize(data);
    ```

  Under the old rules this would deserialize a `()`, whereas under the new rules it will deserialize a `!`.

* The `never_type` feature gate is stable, although some of the behaviours it used to gate now live behind the new `exhaustive_patterns` feature gate (see below).

## What is *not* being stabilized

* Exhaustive pattern-matching for uninhabited types. eg.

    ```rust
    let x: Result<u32, !> = ...;
    let Ok(y) = x;
    ```

  This code will still complain that `Ok(_)` is a refutable pattern. This can be fixed by using the `exhaustive_patterns` feature gate. See [RFC 1872](https://github.com/rust-lang/rfcs/pull/1872) for progress on this issue. See https://github.com/rust-lang/rust/tree/master/src/test/ui/feature-gate-exhaustive-patterns.rs for the testcase which confirms that this behaviour is still gated.

**Comment by nikomatsakis** [comment] 2018-03-12 16:24
Note [decision was made to stabilize here](https://github.com/rust-lang/rust/issues/35121#issuecomment-366372239).

**Comment by scottmcm** [comment] 2018-03-12 21:26
I had a thought that I think needs to be resolved in the same release as this stabilization: Is there an existing stable uninhabited type in `core`/`std` that we want to make an alias for `!`?  (AFAIK we could only do this one one of them, since coherence.)

The one that comes to mind for me is `std::string::ParseError`...

**Comment by nikomatsakis** [comment] 2018-03-13 15:33
@scottmcm I don't think there's a *ton* of motivation to do that -- I believe that, when all is said and done, empty enums and `!` will behave quite similarly in most ways, apart from coercions. Notably in matches.

**Comment by nikomatsakis** [comment] 2018-03-13 15:34
Still, interesting thought. Maybe nicer just for simplicity?

cc @rust-lang/libs -- see @scottmcm's [suggestion above](https://github.com/rust-lang/rust/issues/48950#issuecomment-372468319) about making uninhabited types like `string::ParseError` an alias for `!`

**Comment by sfackler** [comment] 2018-03-13 16:18
I had always assumed that all of the void errors would turn into type aliases for `!` but I hadn't thought of the coherence issue. How many do we actually have? It seems like it may not be worth changing just one of many.

**Comment by alexcrichton** [comment] 2018-03-13 22:07
Yeah I was also personally under the impression that we'd change the types to be aliases and run crater to see if it actually had any fallout (as at the time I don't think we expected much)

**Comment by nikomatsakis** [comment] 2018-03-14 21:24
Well, I just r+'d the `!` stabilization PR, so we have until the next release. =)

**Comment by scottmcm** [comment] 2018-03-15 06:57
Well I only found 3 (ParseError, unstable Infallible, and new-for-1.26 ParsePathError) so PR up: https://github.com/rust-lang/rust/pull/49039

**Comment by mitsuhiko** [comment] 2018-04-10 21:38
Not sure if this is a regression you care about but the findshlibs crate now fails compiling on beta and nightly as a result of this stabilization: https://travis-ci.org/gimli-rs/findshlibs/jobs/364806360

The code in question:

```rust
        match panic::catch_unwind(|| { TargetSharedLibrary::each(|_| panic!("uh oh")); }) {
            Ok(()) => panic!("Expected a panic, but didn't get one"),
            Err(any) => {
                assert!(any.is::<&'static str>(), "panic value should be a &'static str");
                assert_eq!(*any.downcast_ref::<&'static str>().unwrap(), "uh oh");
            }
        }
```

Error message:

```
error[E0277]: the trait bound `IterationControl: std::convert::From<!>` is not satisfied
   --> src/lib.rs:326:40
    |
326 |         match panic::catch_unwind(|| { TargetSharedLibrary::each(|_| panic!("uh oh")); }) {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<!>` is not implemented for `IterationControl`
    |
    = help: the following implementations were found:
              <IterationControl as std::convert::From<()>>
    = note: required because of the requirements on the impl of `std::convert::Into<IterationControl>` for `!`
note: required by `SharedLibrary::each`
   --> src/lib.rs:296:5
    |
296 | /     fn each<F, C>(f: F)
297 | |     where
298 | |         F: FnMut(&Self) -> C,
299 | |         C: Into<IterationControl>;
    | |__________________________________^
error: aborting due to previous error
```

**Comment by SimonSapin** [comment] 2018-04-11 21:36
For what it’s worth the fallback change caused some previously-valid `unsafe` code to go Very Wrong: https://github.com/tomaka/winit/pull/428, https://github.com/servo/servo/pull/20474#issuecomment-379802897.

In short: generic FFI bindings in the `objc` crate end up returning `Ok(x: R)` where `R` is an unconstrained type parameter whose inference changed from `()` to `!`. So now (to simplify) the `Result<!, String>::Ok` value is incorrectly assumed to be `Err`, and on drop we deallocate a `String` whose pointer is made of padding bytes. jemalloc is not amused. The fix is changing statements like `send!(…);` to force the return type: `let () = send!(…);`

**Comment by nikomatsakis** [comment] 2018-04-11 21:49
@SimonSapin ah yes thanks for raising that

**Comment by nikomatsakis** [comment] 2018-04-12 12:41
Cross-posted my question to [the main tracking issue](https://github.com/rust-lang/rust/issues/35121#issuecomment-380790789), and added a few details. That seems like a better place to have this conversation.

**Comment by SimonSapin** [comment] 2018-12-20 19:53
Should this be closed? The last comment pre-dates https://github.com/rust-lang/rust/pull/50121 and now https://github.com/rust-lang/rust/issues/57012.

**Comment by Ericson2314** [comment] 2018-12-20 19:56
```rust
for<E> E: From<!>
```
Is nice for error handling, but I recall there are orphan/overlapping issues adding it later. I think this is because that impl is technically an overlapping impl with `for<A> A: From<A>`, so downstream impls that would overlap with it aren't orpans. But if we somehow hack that into `core`, then the downstream impls can't exist.

**Comment by pnkfelix** [comment] 2018-12-21 12:18
closing since we have started a new round of stabilization in #57012 and so we should try to capture all concerns and other threads of conversation there.

**Closed by pnkfelix** 2018-12-21 12:18 UTC
Labels: A-inference, A-typesystem, C-tracking-issue, T-lang
