### ISSUE TITLE
Intra-doc links should implicitly add `Self::` prefix as needed

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#98270] opened 2022-06-20 01:50 UTC
It's extremely common to reference methods on the same type when writing docs. For example, [`Vec::reserve_exact`](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.reserve_exact) mentions [`Vec::reserve`](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.reserve).

In almost all of these cases, the method being linked doesn't include the full type or `Self::` in the actual text, and has to resort to copying the method name with `Self::` in the link destination.

It would be nice if rustdoc automatically resolved these links without the need to add the extra `Self::` prefix. For example, writing ``[`reserve`]`` should automatically resolve to `Self::reserve` if a `reserve` item doesn't exist on its own. If both the method and the standalone item exist, we could add a lint to point out the ambiguity, requiring the user to clarify either `self::reserve` or `Self::reserve`; this feels like the best move to avoid changing the existing behaviour.

Either way, this pattern feels very common and seems like a papercut that makes documentation just a little bit harder to write.

**Comment by jyn514** [comment] 2022-06-20 04:23
Duplicate of https://github.com/rust-lang/rust/issues/59039

**Closed by jyn514** 2022-06-20 04:23 UTC
Labels: A-intra-doc-links
