### ISSUE TITLE
Rustdoc doesn't use re-exported type aliases in function signatures

### ISSUE THREAD

**Issue by fleabitdev** [rust-lang/rust#80557] opened 2020-12-31 14:03 UTC
The `glsp` crate publicly re-exports everything from the `glsp_engine` crate:

```rust
//in lib.rs for the glsp crate
pub use glsp_engine::*;
```

The root of the `glsp_engine` crate defines a type alias, `GResult`. (This type alias is actually re-exported from a private module within the `glsp_engine` crate, but if I replace it with an inline definition, the bug doesn't change.)

```rust
//in lib.rs for the glsp_engine crate
type GResult<T> = Result<T, GError>;
```

When documenting the `glsp_engine` crate directly, Rustdoc will [correctly document functions with a `GResult` return value](https://docs.rs/glsp-engine/0.1.0/glsp_engine/fn.bind_global.html).

However, when those functions are re-exported by the `glsp` crate, although [the type alias itself](https://docs.rs/glsp/0.1.0/glsp/type.GResult.html) is defined, the type alias is [missing from function signatures](https://docs.rs/glsp/0.1.0/glsp/fn.bind_global.html).

**Comment by GuillaumeGomez** [comment] 2022-04-09 12:21
It's a duplicate of https://github.com/rust-lang/rust/issues/15823 so closing.

**Closed by GuillaumeGomez** 2022-04-09 12:21 UTC
Labels: T-rustdoc, C-bug, A-cross-crate-reexports
