### ISSUE TITLE
ICE: impossible struct constructor

### ISSUE THREAD

**Issue by petertodd** [rust-lang/rust#56835] opened 2018-12-14 22:57 UTC
Example:

```
pub struct Foo {}

impl Foo {
    fn bar(Self(foo): Self) {
    }   
}

fn main() {
}
```

Backtrace:

```
$ rustc impossible-struct-constructor.rs 
error: internal compiler error: src/librustc/hir/def.rs:316: impossible struct constructor

thread 'main' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (f4a421ee3 2018-12-13) running on x86_64-unknown-linux-gnu
```

**Comment by alexreg** [comment] 2018-12-15 04:35
Already fixed in https://github.com/rust-lang/rust/pull/56225, I'm glad to say. I've gone and added a regression test for this issue however. It's due to be r+'ed soon, with any luck.

**Comment by davidtwco** [comment] 2019-01-20 21:47
Closing this as #56850 has fixed it.

**Closed by davidtwco** 2019-01-20 21:47 UTC
Labels: I-ICE, T-compiler, regression-from-stable-to-stable
