### ISSUE TITLE
internal compiler error: librustc/ty/subst.rs:493: Type parameter `T/#0` (T/0) out of range when substituting

### ISSUE THREAD

**Issue by losfair** [rust-lang/rust#50446] opened 2018-05-04 15:31 UTC
```rust
fn foo<T>() {
    let _: [u8; ::std::mem::size_of::<*mut T>()] = [ 0; ::std::mem::size_of::<*mut T>() ];
}
```

This code doesn't compile with either the latest stable or nightly, with an ICE:

```
error: internal compiler error: librustc/ty/subst.rs:493: Type parameter `T/#0` (T/0) out of range when substituting (root type=Some(fn() -> usize {std::mem::size_of::<*mut T>})) substs=[]

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:499:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (e82261dfb 2018-05-03) running on x86_64-unknown-linux-gnu
```

**Comment by eddyb** [comment] 2018-05-04 21:46
This is a duplicate of... I don't even know where we're tracking this. Dependence on type parameters is broken in array length constants - we're sadly stuck with pretty crappy errors until lazy normalization.
cc @nikomatsakis

**Comment by oli-obk** [comment] 2018-10-22 15:19
duplicate of https://github.com/rust-lang/rust/issues/43408

**Closed by oli-obk** 2018-10-22 15:19 UTC
Labels: A-typesystem, C-bug, I-ICE, T-compiler
