### ISSUE TITLE
ICE: 'index out of bounds: the len is 0 but the index is 478'

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#35422] opened 2016-08-06 14:59 UTC
I get the following ICE when I try to compile faulty inline assembly:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 478', ../src/libcollections/vec.rs:1265
stack backtrace:
   1:     0x7f094034f85d - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:     0x7f09403605b1 - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:     0x7f094035ea8f - std::panicking::default_hook::hbbe7fa36a995aca0
   4:     0x7f094035f1fa - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:     0x7f094035f0b2 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:     0x7f094035efe0 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:     0x7f094035ef61 - rust_begin_unwind
   8:     0x7f09403ca76c - core::panicking::panic_fmt::h19323e466869c656
   9:     0x7f09403ca713 - core::panicking::panic_bounds_check::ha883fe1527ce6884
  10:     0x7f0938586999 - syntax::parse::token::InternedString::new_from_name::hcb1855d97bd504d3
  11:     0x7f09384565e7 - _<syntax..ast..Name as core..fmt..Display>::fmt::h40efdc852eb5e792
  12:     0x7f09403d6517 - core::fmt::write::h955c581c22098b7a
  13:     0x7f0940368340 - collections::fmt::format::h7ce9e885e67335e3
  14:     0x7f0938489349 - syntax::codemap::CodeMap::macro_backtrace::hf57d3986470bee83
  15:     0x7f093848967e - _<syntax..codemap..CodeMap as rustc_errors..CodeMapper>::macro_backtrace::h078d230910a860e7
  16:     0x7f0938187725 - rustc_errors::emitter::EmitterWriter::render_macro_backtrace_old_school::h9f96ffbaa1ad3024
  17:     0x7f0938184997 - rustc_errors::emitter::EmitterWriter::emit_message_default::hee6b169a58199b13
  18:     0x7f093817e9bd - _<rustc_errors..emitter..EmitterWriter as rustc_errors..emitter..Emitter>::emit::hb6bf465c9fd02120
  19:     0x7f0938190108 - rustc_errors::Handler::emit::h3ea04463a0a06d86
  20:     0x7f093f228bec - rustc::session::Session::span_err::h612784f93ea5f9a1
  21:     0x7f093f265355 - rustc_trans::back::write::report_inline_asm::h1f77ab7503333593
  22:     0x7f093f265453 - rustc_trans::back::write::inline_asm_handler::hd6faec2821c52425
  23:     0x7f093aa93f46 - _ZN12_GLOBAL__N_19AsmParser11DiagHandlerERKN4llvm12SMDiagnosticEPv
  24:     0x7f093acf2ccd - _ZNK4llvm9SourceMgr12PrintMessageERNS_11raw_ostreamENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS8_INS_7SMFixItEEEb
  25:     0x7f093acf2e8b - _ZNK4llvm9SourceMgr12PrintMessageENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS6_INS_7SMFixItEEEb
  26:     0x7f093aa89b1e - _ZN12_GLOBAL__N_19AsmParser5ErrorEN4llvm5SMLocERKNS1_5TwineENS1_8ArrayRefINS1_7SMRangeEEE
  27:     0x7f0939e14951 - _ZN12_GLOBAL__N_112X86AsmParser26MatchAndEmitATTInstructionEN4llvm5SMLocERjRNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS6_EEEERNS1_10MCStreamerERmb
  28:     0x7f093aaa028a - _ZN12_GLOBAL__N_19AsmParser14parseStatementERNS_18ParseStatementInfoEPN4llvm23MCAsmParserSemaCallbackE
  29:     0x7f093aaa11ee - _ZN12_GLOBAL__N_19AsmParser3RunEbb
  30:     0x7f093a1b9694 - _ZNK4llvm10AsmPrinter13EmitInlineAsmENS_9StringRefERKNS_15MCSubtargetInfoERKNS_15MCTargetOptionsEPKNS_6MDNodeENS_9InlineAsm10AsmDialectE
  31:     0x7f093a1b9e93 - _ZNK4llvm10AsmPrinter13EmitInlineAsmEPKNS_12MachineInstrE
  32:     0x7f093a1b6972 - _ZN4llvm10AsmPrinter16EmitFunctionBodyEv
  33:     0x7f0939e1fccd - _ZN4llvm13X86AsmPrinter20runOnMachineFunctionERNS_15MachineFunctionE
  34:     0x7f093a36c3ca - _ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE
  35:     0x7f093ac48766 - _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE
  36:     0x7f093ac487aa - _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE
  37:     0x7f093ac4a37e - _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE
  38:     0x7f09396edfa5 - LLVMRustWriteOutputFile
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rustllvm/PassWrapper.cpp:430
  39:     0x7f093f263e83 - rustc_trans::back::write::write_output_file::h20a888cdcf5e64a6
  40:     0x7f093f368069 - rustc_trans::back::write::optimize_and_codegen::_{{closure}}::h2f71df715612ebcd
  41:     0x7f093f26c5fe - rustc_trans::back::write::execute_work_item::ha5e725090b02026b
  42:     0x7f093f26668f - rustc_trans::back::write::run_passes::h45c122dc65dd4c1d
  43:     0x7f09408e7bbf - rustc_driver::driver::phase_5_run_llvm_passes::h44a6e789f001637f
  44:     0x7f09408ce94f - rustc_driver::driver::compile_input::hb4cc34cf85dc1edf
  45:     0x7f09408f9e82 - rustc_driver::run_compiler::h50f95674bd902ab5
  46:     0x7f09408458fd - std::panicking::try::call::h4577500a5284c6ff
  47:     0x7f094036ea56 - __rust_maybe_catch_panic
  48:     0x7f094085d351 - _<F as alloc..boxed..FnBox<A>>::call_box::h24f3eb0b42327962
  49:     0x7f094035cd72 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  50:     0x7f093786f6f9 - start_thread
  51:     0x7f093ff9fb5c - clone
  52:                0x0 - <unknown>
```

```
> rustc --version
rustc 1.12.0-nightly (b30eff7ba 2016-08-05)
```

I could not find a minimal example yet.

The biggest problem is that no inline assembly error is shown. Just the above ICE.

Older nightlies (e.g. `rustc 1.12.0-nightly (b6c1ef374 2016-07-14)`) do it better. They throw the same ICE, but they also output an inline assembly error:

```
error: <inline asm>:1:2: error: unknown use of instruction mnemonic without a size suffix
        add rsp, 8; iretq
        ^

  --> src/interrupts/mod.rs:83:17
   |>
83 |>                 asm!("add rsp, 8; iretq");
   |>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(Using intel syntax without specifying the `intel` option.)

This error message is completely missing in newer nighlties.

**Comment by parched** [comment] 2016-09-10 13:28
I believe I've hit this too or something related. With this
```
#![feature(asm)]

macro_rules! dsb {
($i:ident) => {asm!(concat!("isb ", stringify!($i)))};
}

fn main() {
    unsafe { dsb!(SY) };
}
```
I get almost the same BT.

**Comment by cbiffle** [comment] 2016-09-25 16:41
Hitting this on the `x86_64-unknown-linux-gnu` backend with `asm!` inside a `macro_rules` macro, as in @parched's example.

Interestingly, the same code works fine on the `thumbv7em-none-eabi` backend.

Backtrace:

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 218', ../src/libcollections/vec.rs:1307
stack backtrace:
   1:     0x7ff481a51313 - std::sys::backtrace::tracing::imp::write::h4b09e6e8c01db097
   2:     0x7ff481a61f4d - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:     0x7ff481a604ee - std::panicking::default_hook::h96c288d728df3ebf
   4:     0x7ff481a60bd8 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:     0x7ff481a60a72 - std::panicking::begin_panic::hfbeda5aad583dc32
   6:     0x7ff481a609b0 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   7:     0x7ff481a60931 - rust_begin_unwind
   8:     0x7ff481acb09f - core::panicking::panic_fmt::h4395919ece15c671
   9:     0x7ff481acb043 - core::panicking::panic_bounds_check::he139831fe8feb00a
  10:     0x7ff47a771222 - syntax::parse::token::InternedString::new_from_name::h4e84b67e8eab9873
  11:     0x7ff47a633efc - <syntax::ast::Name as core::fmt::Display>::fmt::h2e63739f57aaa2a4
  12:     0x7ff481ad6a45 - core::fmt::write::hd60e09e1e0026aa8
  13:     0x7ff481a6a1e0 - collections::fmt::format::h326044acb8129e34
  14:     0x7ff47a66ae1a - syntax::codemap::CodeMap::macro_backtrace::h7ddebad11eae3ade
  15:     0x7ff47a66b13e - <syntax::codemap::CodeMap as rustc_errors::CodeMapper>::macro_backtrace::h2c1478630d665a2b
  16:     0x7ff47a37cd97 - rustc_errors::emitter::EmitterWriter::fix_multispan_in_std_macros::h646f7d9bec7cf7cc
  17:     0x7ff47a37a4cc - <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit::h239b7341f013ef82
  18:     0x7ff47a389698 - rustc_errors::Handler::emit::hc4c60aa4cff99ef6
  19:     0x7ff4812a27d2 - rustc::session::Session::span_err::h2ccbbfd099a81eb3
  20:     0x7ff4812d49a0 - rustc_trans::back::write::report_inline_asm::hc0d9501a16d7aadf
  21:     0x7ff4812d4a93 - rustc_trans::back::write::inline_asm_handler::hd1c2ab2401f4a876
  22:     0x7ff47c9b9a16 - _ZN12_GLOBAL__N_19AsmParser11DiagHandlerERKN4llvm12SMDiagnosticEPv
  23:     0x7ff47cc1879d - _ZNK4llvm9SourceMgr12PrintMessageERNS_11raw_ostreamENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS8_INS_7SMFixItEEEb
  24:     0x7ff47cc1895b - _ZNK4llvm9SourceMgr12PrintMessageENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS6_INS_7SMFixItEEEb
  25:     0x7ff47c9af5ee - _ZN12_GLOBAL__N_19AsmParser5ErrorEN4llvm5SMLocERKNS1_5TwineENS1_8ArrayRefINS1_7SMRangeEEE
  26:     0x7ff47c9d7bfb - _ZN4llvm11MCAsmParser8TokErrorERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEE
  27:     0x7ff47c9b4b96 - _ZN12_GLOBAL__N_19AsmParser16parsePrimaryExprERPKN4llvm6MCExprERNS1_5SMLocE
  28:     0x7ff47c9b5f3b - _ZN12_GLOBAL__N_19AsmParser15parseExpressionERPKN4llvm6MCExprERNS1_5SMLocE
  29:     0x7ff47c9b4cf1 - _ZN12_GLOBAL__N_19AsmParser16parsePrimaryExprERPKN4llvm6MCExprERNS1_5SMLocE
  30:     0x7ff47c9b5f3b - _ZN12_GLOBAL__N_19AsmParser15parseExpressionERPKN4llvm6MCExprERNS1_5SMLocE
  31:     0x7ff47bd338d8 - _ZN12_GLOBAL__N_112X86AsmParser15ParseMemOperandEjN4llvm5SMLocE
  32:     0x7ff47bd3470c - _ZN12_GLOBAL__N_112X86AsmParser15ParseATTOperandEv
  33:     0x7ff47bd40dd4 - _ZN12_GLOBAL__N_112X86AsmParser16ParseInstructionERN4llvm20ParseInstructionInfoENS1_9StringRefENS1_5SMLocERNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS8_EEEE
  34:     0x7ff47b7c6f11 - _ZN4llvm17MCTargetAsmParser16ParseInstructionERNS_20ParseInstructionInfoENS_9StringRefENS_8AsmTokenERNS_15SmallVectorImplISt10unique_ptrINS_18MCParsedAsmOperandESt14default_deleteIS7_EEEE
  35:     0x7ff47c9c4180 - _ZN12_GLOBAL__N_19AsmParser14parseStatementERNS_18ParseStatementInfoEPN4llvm23MCAsmParserSemaCallbackE
  36:     0x7ff47c9c6cbe - _ZN12_GLOBAL__N_19AsmParser3RunEbb
  37:     0x7ff47c0dea24 - _ZNK4llvm10AsmPrinter13EmitInlineAsmENS_9StringRefERKNS_15MCSubtargetInfoERKNS_15MCTargetOptionsEPKNS_6MDNodeENS_9InlineAsm10AsmDialectE
  38:     0x7ff47c0df223 - _ZNK4llvm10AsmPrinter13EmitInlineAsmEPKNS_12MachineInstrE
  39:     0x7ff47c0dbd22 - _ZN4llvm10AsmPrinter16EmitFunctionBodyEv
  40:     0x7ff47bd4547d - _ZN4llvm13X86AsmPrinter20runOnMachineFunctionERNS_15MachineFunctionE
  41:     0x7ff47c29175a - _ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE
  42:     0x7ff47cb6e236 - _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE
  43:     0x7ff47cb6e27a - _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE
  44:     0x7ff47cb6fe4e - _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE
  45:     0x7ff47b5a7775 - LLVMRustWriteOutputFile
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/rustllvm/PassWrapper.cpp:489
  46:     0x7ff4812d34eb - rustc_trans::back::write::write_output_file::hdb4b691f4323c380
  47:     0x7ff481385fd0 - rustc_trans::back::write::optimize_and_codegen::{{closure}}::h81be959d30d696f6
  48:     0x7ff4812db33f - rustc_trans::back::write::execute_work_item::hb51afc6495293b14
  49:     0x7ff4812d5d69 - rustc_trans::back::write::run_passes::h56d72398bc66cc68
  50:     0x7ff481e1f38f - rustc_driver::driver::phase_5_run_llvm_passes::h09bb1c97ec3e74c9
  51:     0x7ff481e07d18 - rustc_driver::driver::compile_input::hc0edbed7edb3eb18
  52:     0x7ff481e337b6 - rustc_driver::run_compiler::h22d678d32fb7c300
  53:     0x7ff481d71683 - std::panicking::try::do_call::h4d040997e2efdaf3
  54:     0x7ff481a69e66 - __rust_maybe_catch_panic
  55:     0x7ff481d8f109 - <F as alloc::boxed::FnBox<A>>::call_box::hba0b436c79e56b23
  56:     0x7ff481a5ea20 - std::sys::thread::Thread::new::thread_start::h022e3887023c6290
  57:     0x7ff479b1f483 - start_thread
  58:     0x7ff4816aa6dc - clone
  59:                0x0 - <unknown>
```

**Comment by japaric** [comment] 2016-09-25 17:25
@cbiffle That's probably because the involved assembly is ARM specific (e.g. `bkpt`) so using that asm on a x86 would normally generate an error but because of this bug instead it generates an ICE.

**Comment by cbiffle** [comment] 2016-09-25 17:30
@japaric I can confirm that I can reproduce the ICE on `thumbv7em` if I use invalid-for-ARM asm.  It is not specific to `x86_64`.  (Which makes sense given the backtrace.)

**Comment by Dentosal** [comment] 2016-10-17 05:47
@cbiffle @japaric Having same problem with `rustc 1.14.0-nightly (098d22845 2016-10-13)` on Ubuntu 14.04. Trying to compile following "simple" macro:

    macro_rules! int {
        ($num:expr) => ({
            asm!(concat!("int", " ", stringify!(num)) :::: "volatile", "intel");
        });
    }

Invocated with `int!(3)` or `int!(0)`, both give the same error.

Gives:

    thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 107', ../src/libcollections/vec.rs:1306 and similar backtrace. Using xargo, custom x86_64 target with redzone and sse disabled.


This works:

    macro_rules! int {
        ($x:expr) => ({
            asm!(concat!("int ", $x) :::: "intel");
        });
    }


This crashes rustc:

    macro_rules! int {
        ($num:expr) => ({
            asm!(concat!("int ", stringify!(num)) :::: "intel");
        });
    }

But this works (added missing $-sign):

    macro_rules! int {
        ($num:expr) => ({
            asm!(concat!("int ", stringify!($num)) :::: "intel");
        });
    }

**Comment by Mark-Simulacrum** [comment] 2017-05-15 00:01
I cannot reproduce today, so I'm going to close this. I don't see an example here that would make a good cross-platform test case, so not marking E-needstest.

**Closed by Mark-Simulacrum** 2017-05-15 00:01 UTC
