### ISSUE TITLE
Specialization doesn't work when an impl has an associated type bound

### ISSUE THREAD

**Issue by kylewlacy** [rust-lang/rust#36587] opened 2016-09-19 21:50 UTC
(Originally reported in [this comment](https://github.com/rust-lang/rust/issues/31844#issuecomment-221131352) in #31844)

In the following, we have a `Child` trait to represent a "parent-child" relationship between two types. `Alice` is a child of `()` and `Bob` is a child of `Alice`. Then, we have a trait `Foo` that we want to implement for `Alice`, and for all types that are children of a `Foo` (so `Alice` and `Bob` should both implement `Foo`):

``` rust
#![feature(specialization)]

trait Child {
    type Parent;
}

struct Alice;

impl Child for Alice {
    type Parent = ();
}

struct Bob;

impl Child for Bob {
    type Parent = Alice;
}



trait Foo { fn foo(&self); }

impl Foo for Alice {
    fn foo(&self) { println!("Alice foo!"); }
}

// Implement for all children with parents that implement `Foo`
impl<T> Foo for T
    where T: Child, T::Parent: Foo
{
    default fn foo(&self) { println!("Descendant foo!"); }
}



fn main() {
    Alice.foo();
    Bob.foo();
}
```

([playpen](https://play.rust-lang.org/?gist=ac401d9be2957b207a6a59b87cab385c&version=nightly))
## Expected output

The program should print "Alice foo!" and "Descendant foo!"
## Actual output

The program fails to compile:

```
error[E0119]: conflicting implementations of trait `Foo` for type `Alice`:
  --> <anon>:28:1
   |
23 | impl Foo for Alice {
   | - first implementation here
...
28 | impl<T> Foo for T
   | ^ conflicting implementation for `Alice`

error: aborting due to previous error
```
## Version info

```
$ rustc --version
rustc 1.13.0-nightly (55bf6a4f8 2016-09-18)
```
## Other notes

There are two workarounds I've found to fix the error above.

The first is to just remove the `T::Parent: Foo` clause (which works in this case, but not so much for my actual usecase).

The second workaround is to introduce another trait, `FooChild`, which is implemented for all types where `Self::Parent: Foo`. We can then use `FooChild` in the `where` clause instead:

``` rust
trait FooChild { }

impl<T> FooChild for T
    where T: Child, T::Parent: Foo
{
}

// Implement for all children with parents that implement `Foo`
impl<T> Foo for T
//  where T: Child, T::Parent: Foo
    where T: FooChild
{
    default fn foo(&self) { println!("Descendant foo!"); }
}

// ...
```

([playpen](https://play.rust-lang.org/?gist=657cb3a68ec12db229bc216b271868ce&version=nightly))

Interestingly, the second workaround doesn't work when `Child` is moved into a separate crate ([example repo](https://github.com/kylewlacy/rust-conflicting-impl-specialization))

**Comment by apasel422** [comment] 2016-09-28 16:37
The original example exhibits conflicting implementations even without specialization (because `()` doesn't implement `Foo`, the generic impl doesn't apply to `Alice`), which makes me think this is related to or a duplicate of #23341.

**Comment by Mark-Simulacrum** [comment] 2017-05-14 14:39
I'm going to close in favor of #23341.

**Closed by Mark-Simulacrum** 2017-05-14 14:39 UTC
Labels: A-specialization
