### ISSUE TITLE
Release build causes Illegal instruction: 4

### ISSUE THREAD

**Issue by garyemerson** [rust-lang/rust#58340] opened 2019-02-10 03:25 UTC
The following program causes an `Illegal instruction: 4` error on macOS when built as release but not when built as debug.

```rust
fn main() {
    use std::thread;
    let child = thread::spawn(move || {
        loop {}
    });
    child.join().expect("join");
}
```

Meta
---

```bash
$ rustc --version --verbose
rustc 1.32.0 (9fda7c223 2019-01-16)
binary: rustc
commit-hash: 9fda7c2237db910e41d6a712e9a2139b352e558b
commit-date: 2019-01-16
host: x86_64-apple-darwin
release: 1.32.0
LLVM version: 8.0
```

**Comment by sfackler** [comment] 2019-02-10 03:52
Duplicate of #28728.

**Closed by sfackler** 2019-02-10 03:52 UTC
