### ISSUE TITLE
Drop ordering breaks macro hygiene

### ISSUE THREAD

**Issue by JaniM** [rust-lang/rust#63157] opened 2019-07-31 11:23 UTC
Macro hygiene implies any objects created in the macro should be dropped before any code run after it executes. This does not happen in latest stable or nightly.

I tried this code:

```rust
use std::io::Write;

macro_rules! out {
    ($content:expr $(, $vars:expr)*) => {
        let stdout = std::io::stdout();
        let mut out = std::io::BufWriter::with_capacity(2 * 1024 * 1024, stdout.lock());
        write!(out, $content $(, $vars)*).unwrap()
    }
}

fn main() {
    out!("hi\n");
    out!("bye\n");
}
```

Playground link https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0ddca23a27a8f6cd6c5af3251c503ff4

I expected to see this happen: stdout

```
hi
bye
```

Instead, this happened: stdout

```
bye
hi
```

## Meta

`rustc --version --verbose`:

```

rustc 1.38.0-nightly (311376d30 2019-07-18)
binary: rustc
commit-hash: 311376d30dc1cfa622142a9f50317b1e0cb4608a
commit-date: 2019-07-18
host: x86_64-pc-windows-gnu
release: 1.38.0-nightly
LLVM version: 9.0
```

Reproducible on the rust playground on nightly and stable.

**Comment by jonas-schievink** [comment] 2019-07-31 11:27
> Macro hygiene implies any objects created in the macro should be dropped before any code run after it executes.

I don't see why this should be the case. Hygiene only governs name resolution.

**Comment by Nemo157** [comment] 2019-07-31 12:00
The current behaviour is relied on a lot in the ecosystem to allow injecting variables that will be dropped at the end of the current scope, fix is to just put the macro-generated code into an explicit block, this is why you will commonly see macro expansions wrapped in `{{ ... }}` instead of just `{ ... }` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6a08638e6f6be1176de1c202194e7b59)).

**Comment by Mark-Simulacrum** [comment] 2019-07-31 12:35
I tend to agree this is not a bug, cc @petrochenkov but closing.

**Closed by Mark-Simulacrum** 2019-07-31 12:35 UTC
Labels: A-destructors, A-macros, T-lang
