### ISSUE TITLE
Bors did not report a merge conflict

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/rust#78007] opened 2020-10-16 07:06 UTC
#77981 has made three very small changes, one of those made #77187 unmergable. Previously, bors reported, if a pull request got unmergable.

@rustbot modify labels: +T-infra

**Comment by RalfJung** [comment] 2020-10-17 12:35
Also see https://github.com/rust-lang/homu/issues/88.

**Comment by camelid** [comment] 2020-10-18 22:08
Duplicate of rust-lang/homu#88.

**Closed by camelid** 2020-10-18 22:08 UTC
Labels: C-bug, T-infra
