### ISSUE TITLE
Confusing first/second mutable borrow occurs here diagnostic in NLL

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#57528] opened 2019-01-11 20:49 UTC
After https://github.com/rust-lang/rust/pull/56113 we figured with @nikomatsakis that the output of `src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs` in NLL is not ideal.

```rust
fn main() {
    let mut x = 1;
    let mut addr = vec![];
    loop {
        match 1 {
            1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
            //[mir]~^ ERROR [E0499]
            2 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
            //[mir]~^ ERROR [E0499]
            _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
            //[mir]~^ ERROR [E0499]
        }
    }
}
```

outputs:

```
error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> $DIR/borrowck-mut-borrow-linear-errors.rs:13:30
   |
LL |             1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
   |                    ----      ^^^^^^ second mutable borrow occurs here
   |                    |
   |                    first borrow later used here
...
LL |             _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
   |                              ------ first mutable borrow occurs here

error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> $DIR/borrowck-mut-borrow-linear-errors.rs:15:30
   |
LL |             1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
   |                    ---- first borrow later used here
LL |             //[mir]~^ ERROR [E0499]
LL |             2 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
   |                              ^^^^^^ second mutable borrow occurs here
LL |             //[mir]~^ ERROR [E0499]
LL |             _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
   |                              ------ first mutable borrow occurs here

error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> $DIR/borrowck-mut-borrow-linear-errors.rs:17:30
   |
LL |             _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
   |                              ^^^^^^ mutable borrow starts here in previous iteration of loop

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0499`.
```

in NLL mode.

In particular the mention of first and second is weird. Why the `_ =>` arm is the first one?. Is that clear to the user?. There are several errors in the test also. Is it better to mix the fact that you're mutably borrowing something in `_ =>` and the mutably borrowing in `1 =>`? or is it better and easier to just state that both borrows are inside of the loop?.

**Comment by pnkfelix** [comment] 2019-03-20 15:36
triage: I suspect this is a duplicate of #57526 . Double-checking with @spastorino

**Comment by pnkfelix** [comment] 2019-03-20 19:30
closing as duplicate of #57526

**Closed by pnkfelix** 2019-03-20 19:30 UTC
Labels: A-NLL, NLL-diagnostics
