### ISSUE TITLE
1.79 regression in `const` temporary lifetime extension

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#126562] opened 2024-06-16 19:23 UTC
### Code

I tried this code: [[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d9afadf105a20fb204b94f6a3e893f1c) [[godbolt]](https://rust.godbolt.org/z/6hnhPMqjT)

```rust
pub struct Dir<'a>(&'a [File<'a>]);
impl<'a> Dir<'a> {
    pub const fn new(x: &'a [File<'a>]) -> Self {
        Self(x)
    }
}

pub struct File<'a>(&'a str);
impl<'a> File<'a> {
    pub const fn new(x: &'a str) -> Self {
        Self(x)
    }
}

pub static OK: Dir<'static> = Dir::new(&[File::new("")]);
pub static ERR: Dir<'static> = if true {
    Dir::new(&[File::new("")]) //~ ERROR: temporary value dropped while borrowed
} else {
    unreachable!()
};
```

I expected to see this happen: code compiles: temporary is promoted to `&'static` due to the `const` evaluation context.

Instead, this happened: code errors: temporary value dropped while borrowed.

### Version it worked on

It most recently worked on: 1.78

### Version with regression

`rustc --version --verbose`:
```
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-pc-windows-msvc
release: 1.79.0
LLVM version: 18.1.7
```

### Meta

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

Bisects to #121557 

Initially reported on urlo: https://users.rust-lang.org/t/code-compiles-in-1-78-0-but-not-in-1-79-0/113038?u=cad97

**Comment by CAD97** [comment] 2024-06-16 19:37
@rustbot claim

I think I found what needs to be fixed. Just claiming the fix; I don't know how handling the regression should go.

**Comment by RalfJung** [comment] 2024-06-16 20:09
We recently changed our rules for promotion of function calls, quite deliberately: https://github.com/rust-lang/rust/pull/121557. This seems to me to be expected fall-out from that change?

**Comment by RalfJung** [comment] 2024-06-16 20:11
Cc @rust-lang/wg-const-eval

**Comment by CAD97** [comment] 2024-06-16 20:14
That does look to be more directly relevant than #121346, although the two might still interact in some manner.

@rustbot release-assignment

The thread I was pulling on didn't go anywhere and I don't know enough to determine much more on my own

**Comment by RalfJung** [comment] 2024-06-16 20:24
`Dir::new(&[File::new("")])` is exactly the kind of code we'd like to not compile since it moves a function call (`File::new`) into a promoted. However for backwards compatibility reasons, we currently still let it compile. However, once that kind of function call is inside a conditional, having it implicitly promoted becomes *really sketchy*, and crater showed that this pattern is very rare in the wild (crater found [zero regressions](https://crater-reports.s3.amazonaws.com/pr-121557-1/index.html)). So we moved to rejecting that code, finally making tangible progress on https://github.com/rust-lang/rust/issues/80619.

The intended way to write such code is `Dir::new(const { &[File::new("")] })`.

**Comment by CAD97** [comment] 2024-06-16 20:28
So that it's mentioned directly here: the urlo source looks like

```rust
pub static ASSETS_DIR: Option<include_dir::Dir<'_>> = if cfg!(target_arch = "wasm32") {
    Some(include_dir::include_dir!("$CARGO_MANIFEST_DIR/assets"))
} else {
    None
};
```

and cannot introduce a `const` block to make it compile, as the correct place to introduce it is inside of the [`include_dir!`](https://docs.rs/include_dir/latest/include_dir/) macro. (Although in fairness OOP likely wants `cfg_match!` rather than `if cfg!` anyway.)

**Comment by RalfJung** [comment] 2024-06-16 20:29
The const block should be inside that included file then.

**Comment by lqd** [comment] 2024-06-16 20:49
> We recently changed our rules for promotion of function calls, quite deliberately: #121557.

(The OP does bisect to #121557)

**Comment by apiraino** [comment] 2024-07-11 09:44
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23126937.20Rust.201.2E81-nightly.20slower.20than.20Rust.201.2E79.20.3Fhttps://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23126937.20Rust.201.2E81-nightly.20slower.20than.20Rust.201.2E79.20.3F)).

@rustbot label -I-prioritize +P-mdium

**Comment by RalfJung** [comment] 2024-07-11 09:47
This is now fixed upstream in include_dir, see https://github.com/Michael-F-Bryan/include_dir/issues/99.

**Comment by CAD97** [comment] 2024-08-16 20:09
Closing as deliberate and expected breakage.

**Closed** 2024-08-16 20:09 UTC
Labels: A-lifetimes, P-medium, T-compiler, regression-from-stable-to-stable, C-bug, A-const-eval
