### ISSUE TITLE
use of possibly uninitialized variable

### ISSUE THREAD

**Issue by oddcoder** [rust-lang/rust#41186] opened 2017-04-10 15:02 UTC
```
use std::fs::*;
use std::io::*;
pub struct FileHandler {
    path: String,
    buf: BufReader<File>,
}
impl FileHandler {
    pub fn new(path: String) -> FileHandler {
        let file = File::open(&path).unwrap();
        let f = BufReader::new(file);
        return FileHandler {
            path: path,
            buf: f,
        };
    }
    fn scrap_comment (&mut self) -> Result<String> {
        let mut line: String;
        let mut done = false;
        while !done {
            let commented_line;
            match (&mut self.buf).lines().nth(0).unwrap() {
                Err(e) => return Err(e),
                Ok(s) => commented_line = s,
            }
            line = commented_line.split(".").nth(0).unwrap().trim().to_string();
            if !line.is_empty(){
                done = true;
            }
        }
        return Ok (line);
    }
}
```
gives error
```
|         return Ok (line);
|                          ^^^^ use of possibly uninitialized `line`
```
however when switching to loop instead of while
```
    fn scrap_comment (&mut self) -> Result<String> {
        let mut line: String;
        loop {
            let commented_line;
            match (&mut self.buf).lines().nth(0).unwrap() {
                Err(e) => return Err(e),
                Ok(s) => commented_line = s,
            }
            line = commented_line.split(".").nth(0).unwrap().trim().to_string();
            if !line.is_empty(){
                break;
            }
        }
        return Ok (line);
    }
```
the error disappears, given that both Functions do exactly the same logic and there is no path that would result in an uninitialized `line`

**Comment by Mark-Simulacrum** [comment] 2017-06-20 21:31
The problem here is that rustc doesn't utilize const eval to determine validity of code in such cases ( that is, `while true` != `loop`) so this is expected behavior. I'm going to close this -- to my knowledge, const eval is always intended purely as an optimization, not an enabler of different behavior.

**Closed by Mark-Simulacrum** 2017-06-20 21:31 UTC
