### ISSUE TITLE
 let mut a = [];   

### ISSUE THREAD

**Issue by cuckookernel** [rust-lang/rust#23961] opened 2015-04-02 01:16 UTC
This code crashes the compiler 

```rust
fn main() {
    let mut a = [];    
}
```

```
rustc --version
rustc 1.0.0-nightly (d754722a0 2015-03-31) (built 2015-04-01)
```

On windows 7 (64 bit) 

```
a.rs:7:19: 7:21 error: internal compiler error: cat_expr Errd
a.rs:7     let mut a = [];
                                    ^~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', C:/bot/slave/nightly-dist-rustc-win-64/build/src/libsyntax\diagnostic.rs:130

stack backtrace:
   1:         0x7121c7d3 - sys::backtrace::write::h26f3dfa5607ee31dCMD
   2:         0x71231b3a - rt::unwind::register::he2da75234a8bfeefOjJ
   3:         0x71183130 - rt::unwind::begin_unwind_inner::ha4ed1cd24d71fc5fYgJ
   4:           0x7b5af9 - diagnostic::SpanHandler::span_bug::hbab7d9e8f930b2a0BcB
   5:           0x7b5ac3 - diagnostic::SpanHandler::span_bug::hbab7d9e8f930b2a0BcB
   6:           0xdd24e2 - session::Session::span_bug::h3f7ba5dcfb8c2b2buto
   7:          0x1759011 - check::regionck::Rcx<'a, 'tcx>.Visitor<'v>::visit_item::h549cc8f76dffe18bGDd
   8:          0x1759afa - check::regionck::Rcx<'a, 'tcx>.Visitor<'v>::visit_local::h20a6c72e4c7a864epEd
   9:          0x17540f6 - check::regionck::Rcx<'a, 'tcx>.Visitor<'v>::visit_expr::hbd7455afe8974b7fVDd
  10:          0x17e9f13 - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_ty::h516be61f8f1ab04ccOn
  11:          0x17e1e41 - check::CheckItemTypesVisitor<'a, 'tcx>.Visitor<'tcx>::visit_item::h38e34fdef076473eQNn
  12:          0x18b6598 - check_crate::h13ec7eeead4478a1BxC
  13:          0x18b081c - check_crate::h13ec7eeead4478a1BxC
  14:         0x652df73b - driver::phase_3_run_analysis_passes::hfb4b6f3296e77e2coGa
  15:         0x652c2a65 - driver::compile_input::h99ce08289465395eQba
  16:         0x65376ad3 - run_compiler::h0bba6b17cd7f9dddp2b
  17:         0x65374990 - run::hd86bbfcbe6b9750a51b
  18:         0x65373b9a - run::hd86bbfcbe6b9750a51b
  19:         0x7126a75c - rust_try
  20:         0x7126a739 - rust_try
  21:         0x65373f08 - run::hd86bbfcbe6b9750a51b
  22:         0x71225804 - sys::tcp::TcpListener::bind::h673da3c0fc98ee2diIH
  23:     0x7ffb63a013d2 - BaseThreadInitThunk
```

**Comment by huonw** [comment] 2015-04-02 02:01
Duplicate of https://github.com/rust-lang/rust/issues/22897, thanks for filing nonetheless!

**Closed by huonw** 2015-04-02 02:01 UTC
Labels: I-ICE
