### ISSUE TITLE
ICE: "aliasability violation with closure" in Boxed FnMut

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#21216] opened 2015-01-16 00:07 UTC
The specific error occurs in [this commit](https://github.com/alexchandel/conrod/commit/b27fb8c7b58f1b67d9d4f963312bab8b3c53d1bf) on [my bugfix fork](https://github.com/alexchandel/conrod) of [conrod](https://github.com/PistonDevelopers/conrod).

An FnMut is created, boxed, and passed to a function that takes a Box<FnMut(bool) + 'a>. The closure modifies its environment:

```rust
conrod/examples/all_widgets.rs:318:36: 318:97 error: internal compiler error: aliasability violation with closure
conrod/examples/all_widgets.rs:318                 .callback(Box::new(|&mut: new_val: bool| {demo.bool_matrix[col][row] = new_val;}))
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tamird** [comment] 2015-04-21 23:13
@alexchandel could you reduce this to a self-contained test case?

**Comment by alexchandel** [comment] 2015-04-29 15:19
No idea, it occurred deep in the conrod example, which has been extensively refactored since then. If you're capable of Boxing a non-moving FnMut that modifies its environment, and passing it to a function that takes a Box, at least 5 times in one function, then it may have been fixed in rustc since then.

**Comment by tamird** [comment] 2015-04-29 19:16
Something like this?
```rust
fn invoke_fn<F>(f: &mut Box<&mut F>) where F: FnMut() {
  (*f)()
}

fn main() {
  let mut option = None;
  let mut fn_mut = || {
    option = Some(7)
  };
  let mut boxed_fn = Box::new(&mut fn_mut);

  invoke_fn(&mut boxed_fn);
  invoke_fn(&mut boxed_fn);
}
```
This compiles without error.

**Comment by tamird** [comment] 2015-04-29 19:25
Alternatively:
```rust
fn attach_fn(opt_fn: &mut Box<FnMut()>) {
  let mut option = None;
  *opt_fn = Box::new(|| { option = Some(7) });
}

fn main() {
  let mut optional_fn = Box::new(|| {});
  attach_fn(&mut optional_fn);
}
```
Attempts to leak an environment-mutating closure out of its closure, and fails without ICE:
```
$ rustc main.rs
main.rs:8:13: 8:29 error: mismatched types:
 expected `&mut Box<core::ops::FnMut()>`,
    found `&mut Box<[closure main.rs:7:34: 7:39]>`
(expected trait core::ops::FnMut,
    found closure) [E0308]
main.rs:8   attach_fn(&mut optional_fn);
                      ^~~~~~~~~~~~~~~~
error: aborting due to previous error
```

I think this issue should be closed; it's unlikely to yield anything actionable. @steveklabnik?

**Comment by arielb1** [comment] 2015-07-08 21:09
Seems like a duplicate of #21390, and unlikely to be reproduced. Closing.

**Closed by arielb1** 2015-07-08 21:09 UTC
Labels: I-ICE
