### ISSUE TITLE
Extension traits (blanket impls) not showing up in docs

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#19394] opened 2014-11-29 06:57 UTC
[`IteratorExt`](http://doc.rust-lang.org/core/iter/trait.IteratorExt.html) is now impl'd on all `Iterator`s:

```
impl<A, I> IteratorExt<A> for I where I: Iterator<A>
```

However, it doesn't show up on any given `Iterator`: eg [`Map`](http://doc.rust-lang.org/core/iter/struct.Map.html)

This makes it even more confusing. For any newbie who doesn't know of the existence of this extension trait, all the useful methods will be hidden.

**Comment by tomjakubowski** [comment] 2015-04-04 01:04
I think it's tough, or maybe intractable, for rustdoc in its current form to do this the "right way". As best as I can tell, if rustdoc would need to take every trait implementation which has a type parameter, and walk all documented types to check which ones fall under the blanket implementation. It gets worse when you consider generic types like `Vec<T>` (`Vec<i32>` might fall under a blanket impl, but not `Vec<u32>`, for example).

A workable solution might be some kind of rustdoc-specific attribute that indicates a trait is an extension trait, with a (Rust) path indicating where the docs for that trait's methods should be inlined. That way at least the common extension traits in the standard library would be documented on the types they extend.

**Comment by Manishearth** [comment] 2015-04-04 05:06
That works, IMO

**Comment by tomjakubowski** [comment] 2015-04-04 05:23
I do wonder - what are the remaining blanket impls in `std`? With the relaxed object safety rules it's harder to find them these days. In fact, all I can find are deprecated ones in `old_io` and the `AsPath` blanket impl.

**Comment by alexcrichton** [comment] 2015-04-07 03:09
I agree with @tomjakubowski's analysis in that this is probably not possible to solve in the general case, but some specialization of attributes could perhaps help us here. I also agree with @Manishearth that this is all working as intended today.

We don't have too too many more blanket impls in the standard library beyond conversion traits, so I don't think the need for this is so great any more. I'm going to close this for now due to it working as intended, and we can reopen in the future if the need is great enough with a specialized attribute like @tomjakubowski showed perhaps.

**Closed by alexcrichton** 2015-04-07 03:09 UTC
Labels: A-rustdoc

**Comment by troplin** [comment] 2016-04-11 07:56
Sorry to resurrect such an old and closed issue, but shouldn't blanket impls at least be documented on the doc page of the *trait*?
