### ISSUE TITLE
rustdoc and reexported types

### ISSUE THREAD

**Issue by DarkEld3r** [rust-lang/rust#45373] opened 2017-10-18 19:46 UTC
Example (lib.rs):
```rust
extern crate serde;

pub mod reexport {
    pub use serde::Serialize;
    pub use serde::ser::Error as SerError;
}
```
In the generated documentation for the `reexport::SerError` type there is a reference to the `serde::Serialize`, but this reference is broken (`target/doc/reexport_test/trait.Serialize.html` instead of `target/doc/reexport_test/reexport/trait.Serialize.html`).

**Comment by Freyskeyd** [comment] 2017-10-19 07:53
Hey @DarkEld3r 

thank's for the report, can you provide a rust version please?

**Comment by DarkEld3r** [comment] 2017-10-19 09:07
I have used `rustc 1.20.0 (f3d6973f4 2017-08-27)`, but on the latest stable (`rustc 1.21.0 (3b72af97e 2017-10-09)`) there is the same problem.

**Comment by Freyskeyd** [comment] 2017-10-19 10:44
I can't reproduce on `rustc 1.21.0 (3b72af97e 2017-10-09)`

**Comment by Freyskeyd** [comment] 2017-10-19 10:51
Yeah, I see. But I think it's a serde error.

https://docs.serde.rs/src/serde/ser/mod.rs.html#107

Anyway, I don't know if it's a doc generation error.

**Comment by DarkEld3r** [comment] 2017-10-19 15:03
I'm also not sure if it is rustdoc bug: reexporting is specific case, but I prefer to create an issue to make sure if it is a problem or not. :sweat_smile: 

On the other hand, documentation works correctly for serde (https://docs.serde.rs/serde/trait.Serialize.html) itself, so it cannot (shouldn't) be fixed inside this crate.

**Comment by ollie27** [comment] 2017-10-19 16:55
#43466 should fix issues like this.

**Comment by TimNN** [comment] 2017-10-22 19:07
This is currently expected behaviour since `rustdoc` doesn't do any kind of link rewriting currently. As @ollie27 noted, there are plans to support this in `rustdoc` so I'm gonna close this issue.

**Closed by TimNN** 2017-10-22 19:07 UTC
