### ISSUE TITLE
rustdoc: Syntax highlighting doesn't work for TOML and YAML

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76685] opened 2020-09-13 21:26 UTC
Here are some examples:

### Rendered

![image](https://user-images.githubusercontent.com/37223377/93028888-e8bba800-f5cb-11ea-9fab-e2f87c6ed769.png)

### DOM

```html
<pre><code class="language-toml">[dependencies]
structopt = { version = &quot;0.3&quot;, features = [ &quot;paw&quot; ] }
paw = &quot;1.0&quot;
</code></pre>
```

### Rendered

![image](https://user-images.githubusercontent.com/37223377/93028903-f1ac7980-f5cb-11ea-930c-ed6bf13471be.png)

### DOM

```html
<pre><code class="language-yaml">name: myapp
version: &quot;1.0&quot;
author: Kevin K. &lt;kbknapp@gmail.com&gt;
about: Does awesome things
args:
    - config:
        short: c
        long: config
        value_name: FILE
        help: Sets a custom config file
        takes_value: true
    - INPUT:
        help: Sets the input file to use
        required: true
        index: 1
    - verbose:
        short: v
        multiple: true
        help: Sets the level of verbosity
subcommands:
    - test:
        about: controls testing features
        version: &quot;1.3&quot;
        author: Someone E. &lt;someone_else@other.com&gt;
        args:
            - debug:
                short: d
                help: print debug information
</code></pre>
```

---

@rustbot modify labels: T-rustdoc C-bug

**Comment by camelid** [comment] 2020-09-13 21:28
Based on the DOM, it seems like it's being propagated as the correct language (not plaintext or something), but it's not actually being highlighted.

**Comment by ollie27** [comment] 2020-09-14 20:43
Duplicate of #43165

**Closed by ollie27** 2020-09-14 20:43 UTC
Labels: C-bug, T-rustdoc
