### ISSUE TITLE
std::mem::size_of::<type> is non-const

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#32021] opened 2016-03-03 03:45 UTC
It is sort of surprising and makes a little harder to generate code using macros like:

``` rust
macro_rules! read_buf {
    ($ty: ty) => ({
        let mut buf = [0; std::mem::size_of::<$ty>()];
     
     ....
```

**Comment by huonw** [comment] 2016-03-03 03:51
This is a dupe of https://github.com/rust-lang/rfcs/issues/1144. Unfortunately, the feature has some (possibly) surprising subtleties that make it trickier than one might hope.

Thanks for filing!

**Closed by huonw** 2016-03-03 03:51 UTC
