### ISSUE TITLE
iter::Zip is now invariant

### ISSUE THREAD

**Issue by Stebalien** [rust-lang/rust#35727] opened 2016-08-16 19:32 UTC
The following compiles on stable but not beta:

```rust
use std::iter::Zip;

fn test<'a, A, B>(iter: Zip<&'static A, &'static B>) -> Zip<&'a A, &'a B> { iter }

fn main() {}
```

**Comment by Stebalien** [comment] 2016-08-16 19:35
(also a regression from stable to beta)

**Comment by brson** [comment] 2016-08-16 23:24
If this is a beta regression that means it is going to hit stable thursday.

**Comment by brson** [comment] 2016-08-16 23:27
If somebody fixed and landed this _right now_ and we started a stable build _tonight_ we might be able to manage getting this into a Thursday release.

**Comment by brson** [comment] 2016-08-16 23:29
... or we could just end up flubbing and missing our date.

**Comment by alexcrichton** [comment] 2016-08-16 23:41
I don't think this is a serious enough regression to halt the release. @Stebalien this was just manufactured, right? There's no code that actually hit this?

**Comment by Stebalien** [comment] 2016-08-17 00:26
@brson. The fix is to either revert the zip specializations (simplest) or put the extra fields needed by specialization into the main `Zip` struct. We can keep the enumerate specialization as-is (it doesn't need extra specialized fields).

@alexcrichton Not *my* code.

**Comment by rkruppe** [comment] 2016-08-17 08:34
@alexcrichton `Zip` may or may not be hit by actual code, but FYI the similar variance regression in `vec::IntoIter` (#35721) breaks `vec_map` which is a transitive dependency of a couple of popular crates.

**Comment by bluss** [comment] 2016-08-17 10:01
Ah this is troublesome, indeed it's the associated types/struct field specialization that causes this, not just the regular "behavioral" specialization isn't it. I can't think of a workaround, we could back out the whole optimization, or just the associated type part?

**Comment by alexcrichton** [comment] 2016-08-23 05:39
Discussed at @rust-lang/libs triage today, we concluded that we're likely to revert but we're not sure. @aturon wasn't present unfortunately and he'll likely also have opinions on this as well. We'll discuss again soon.

Our other conclusion was that this wasn't *super* urgent because it's already hit stable.

**Comment by aturon** [comment] 2016-09-12 21:13
cc @nikomatsakis This is a pretty interesting tradeoff -- using specialization on representation destroys any variance.

**Comment by nikomatsakis** [comment] 2016-09-12 21:35
That is an interesting dilemma! I don't see an obvious solution though except maybe for explicit variance annotations on traits (that could then be checked by its implementors). i.e., you could say "all values of `<T as Foo<'a>>::Type` must be covariant w/r/t `'a'` and `T` of something". That seemed like a big pain when we last visited this question.

**Comment by aturon** [comment] 2016-09-12 21:50
@nikomatsakis That pretty much echos my thoughts as well.

**Comment by nikomatsakis** [comment] 2016-09-12 21:56
@aturon there is a general desire for being able to prevent variance regressions (as expressed by e.g. @brson). I had thought about solving this in various ways (including as part of a more general semver checker), but this may tilt the balance in favor of adding some way to declare variance (even if it is optional).

**Comment by alexcrichton** [comment] 2016-09-12 22:17
Decision at the libs team triage today was that we should **revert** the specialization of the structure of `Zip`. @bluss would you be interested in backing out just that particular piece? (taking the strategy of `Fuse`)

**Comment by bluss** [comment] 2016-09-13 13:37
Sure. What do you mean by the Fuse strategy? Just no specialization of the data, only the methods?

**Comment by alexcrichton** [comment] 2016-09-13 15:29
Ah yeah sorry I mean to just specialize the methods, not the struct representation (which we believe fixes this bug)

**Closed** 2016-09-17 19:02 UTC
Labels: A-libs, E-help-wanted, regression-from-stable-to-beta, T-libs
