### ISSUE TITLE
const fn can have little a phantom data

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#67649] opened 2019-12-27 00:13 UTC
```rust
use std::marker::PhantomData;

fn main() {}

const fn foo() -> PhantomData<fn()> {
   PhantomData
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=321cc2827c18564c52e42ad86653333d)

```
   Compiling playground v0.0.1 (/playground)
error[E0723]: function pointers in const fn are unstable
 --> src/main.rs:7:19
  |
7 | const fn foo() -> PhantomData<fn()> {
  |                   ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see issue https://github.com/rust-lang/rust/issues/57563
  = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

We should probably not restrict the phantom datas a const fn is allowed to construct

cc @oli-obk

**Comment by oli-obk** [comment] 2019-12-27 00:29
cc @rust-lang/wg-const-eval

**Comment by Centril** [comment] 2019-12-27 00:34
> We should probably not restrict the phantom datas a const fn is allowed to construct

I don't see anything special about `PhantomData`'s type parameter as opposed to other ones for other types in terms of what the meaning of `fn()` is and whether it would conditionally mean e.g. `const fn()`. At any rate, I don't think we should be adding special allowances for this type before we holistically consider everything else.

**Comment by oli-obk** [comment] 2019-12-27 00:34
All the type based limitations of `const fn` are things that we plan to resolve. Right now we have a very simple check
https://github.com/rust-lang/rust/blob/3e0a1c09108b52e41113520c7fa516480a8b67f9/src/librustc_mir/transform/qualify_min_const_fn.rs#L79-L122
adding a `PhantomData` exception will make this check more complex. A real world example that makes this feature useful would be good as motiviation to do this change.

**Comment by Manishearth** [comment] 2019-12-27 00:44
@Centril right, I'm talking about types which transitively use phantom data as well. I believe there are other similar exceptions in the compiler for PhantomData.

As for a real world use case, @hawkw hit this but I don't recall the specifics

**Comment by Dylan-DPC** [comment] 2022-11-01 08:39
Closing this as the issue is fixed

**Closed by Dylan-DPC** 2022-11-01 08:39 UTC
Labels: T-lang, A-const-fn, C-feature-request
