### ISSUE TITLE
Associated type bindings are not allowed here, unexpected panic

### ISSUE THREAD

**Issue by SnareChops** [rust-lang/rust#21840] opened 2015-02-01 13:55 UTC
I see my error here, but to support rust I will submit this bug as requested.

MacBookPro - OSX 10.10 - x64 intel - 

       Fresh log v0.2.1
       Fresh libc v0.1.1
       Fresh bitflags v0.1.0
       Fresh gcc v0.1.7
       Fresh unsafe-any v0.2.1
       Fresh rustc-serialize v0.2.10
       Fresh pkg-config v0.1.7
       Fresh matches v0.1.2
       Fresh mucell v0.1.12
       Fresh unicase v0.0.3
       Fresh mime v0.0.7
       Fresh url v0.2.17
       Fresh time v0.1.15
       Fresh openssl-sys v0.2.18
       Fresh openssl v0.2.18
       Fresh cookie v0.1.9
       Fresh hyper v0.1.9
       Fresh websocket v0.10.3
   Compiling testlib v0.0.1 (file:///Users/scott/repos/test_app)
     Running `rustc src/main.rs --crate-name test_app --crate-type bin -g --out-dir /Users/scott/repos/test_app/target --emit=dep-info,link -L dependency=/Users/scott/repos/test_app/target -L dependency=/Users/scott/repos/test_app/target/deps --extern rustc-serialize=/Users/scott/repos/test_app/target/deps/librustc-serialize-181d5959361aa206.rlib --extern websocket=/Users/scott/repos/test_app/target/deps/libwebsocket-e2d678e8a9089abd.rlib --extern livesocket=/Users/scott/repos/test_app/target/libtestlib-b1f31b9645bad55b.rlib -L native=/Users/scott/repos/test_app/target/build/time-2215e3ac75eaa2c7/out`

src/main.rs:19:16: 19:25 error: parenthesized parameters may only be used with a trait [E0214]
src/main.rs:19     let words: Vec(&str) = input.words().collect();

src/main.rs:19:19: 19:25 error: associated type bindings are not allowed here [E0229]
src/main.rs:19     let words: Vec(&str) = input.words().collect();
                                 ^~~~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: !generic_bounds.has_escaping_regions()', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/librustc_typeck/check/mod.rs:1826

stack backtrace:
   1:        0x109d28947 - sys::backtrace::write::he402374d097c734cvbu
   2:        0x109d4edfc - failure::on_fail::hed9b34e067ca7da1qbB
   3:        0x109cb0208 - rt::unwind::begin_unwind_inner::h7c63803321d7204cmTA
   4:        0x10687d94c - rt::unwind::begin_unwind::h8602087355689510853
   5:        0x1068daaa0 - check::FnCtxt<'a, 'tcx>::add_obligations_for_parameters::h7f082a14921c02246Nm
   6:        0x10691b4d3 - check::wf::BoundsChecker<'cx, 'tcx>.TypeFolder<'tcx>::fold_ty::ha55680a6ab46ecc2Fxj
   7:        0x10693b9e5 - check::GatherLocalsVisitor<'a, 'tcx>.Visitor<'v>::visit_local::hd09d95956c7da86886k
   8:        0x106922286 - check::check_fn::h4985f8d75a08ff763dl
   9:        0x10693a77f - check::check_bare_fn::h995c71688f4975c3v3k
  10:        0x106932287 - check::check_item::ha4b08dad0c8499ae8ll
  11:        0x106a01cf3 - check_crate::closure.32081
  12:        0x1069fd24f - check_crate::h89c36ac38cf567e2DNy
  13:        0x1063c316b - driver::phase_3_run_analysis_passes::h5a89a1160de7ae6eNFa
  14:        0x1063a96dc - driver::compile_input::h4f8de4738327a360Bba
  15:        0x106471c9e - run_compiler::hfa201cb78154d87an9b
  16:        0x10646edaf - thunk::F.Invoke<A, R>::invoke::h11184981586525590284
  17:        0x10646da40 - rt::unwind::try::try_fn::h2812590929445923530
  18:        0x109dc52a9 - rust_try_inner
  19:        0x109dc5296 - rust_try
  20:        0x10646e104 - thunk::F.Invoke<A, R>::invoke::h9675590542894749928
  21:        0x109d394b3 - sys::thread::thread_start::h63de676196642ba2J3w
  22:     0x7fff9a7b12fc - _pthread_body
  23:     0x7fff9a7b1279 - _pthread_body

Could not compile `test_app`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name test_app --crate-type bin -g --out-dir /Users/scott/repos/test_app/target --emit=dep-info,link -L dependency=/Users/scott/repos/test_app/target -L dependency=/Users/scott/repos/test_app/target/deps --extern rustc-serialize=/Users/scott/repos/test_app/target/deps/librustc-serialize-181d5959361aa206.rlib --extern websocket=/Users/scott/repos/test_app/target/deps/libwebsocket-e2d678e8a9089abd.rlib --extern testlib=/Users/scott/repos/test_app/target/libtestlib-b1f31b9645bad55b.rlib -L native=/Users/scott/repos/test_app/target/build/time-2215e3ac75eaa2c7/out` (status=101)

**Comment by tamird** [comment] 2015-04-22 00:52
@SnareChops can you include the code you were attempting to compile?

**Comment by arielb1** [comment] 2015-06-18 21:10
Seems like a duplicate of #25389.
```
 let words: Vec(&str) = input.words().collect();
```

**Closed by arielb1** 2015-06-18 21:10 UTC
Labels: A-associated-items, I-ICE
