### ISSUE TITLE
Closure-to-fn coercion does not work for `unsafe fn`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#58478] opened 2019-02-15 08:20 UTC
Given that non-capturing closures coerce to `fn`, and `fn` coerces to `unsafe fn`, I would expect the transitive step to also happen -- but it does not:
```rust
fn coerce(_x: fn()) {}
fn coerce_unsafe(_x: unsafe fn()) {}

fn foo() {}

fn main() {
    coerce(|| panic!()); // works
    coerce_unsafe(foo); // works
    coerce_unsafe(|| panic!()); // fails
}
```
```
error[E0308]: mismatched types
 --> src/main.rs:9:19
  |
9 |     coerce_unsafe(|| panic!());
  |                   ^^^^^^^^^^^ expected unsafe fn, found normal fn
  |
  = note: expected type `unsafe fn()`
             found type `[closure@src/main.rs:9:19: 9:30]`
```
This is particularly annoying when instantiating `RawWakerVTable`, because it means one cannot just use closure syntax there.

**Comment by hellow554** [comment] 2019-02-15 08:28
https://doc.rust-lang.org/stable/reference/type-coercions.html#coercion-types

> T_1 to T_3 where T_1 coerces to T_2 and T_2 coerces to T_3 (transitive case)
>
> Note that this is not fully supported yet

I guess this is one of the not supported cases? I ask myself why this is generally not supported? What's missing here?

**Comment by Centril** [comment] 2019-02-15 15:34
Duplicate of https://github.com/rust-lang/rust/issues/57883.

**Closed by Centril** 2019-02-15 15:34 UTC
Labels: A-coercions
