### ISSUE TITLE
`nightly-2024-09-11` `#[test]` code complains about `missing_docs` when `missing-docs = "deny"` lint is configured

### ISSUE THREAD

**Issue by ytmimi** [rust-lang/rust#130240] opened 2024-09-11 18:51 UTC
When trying to run tests with `cargo +nightly-2024-09-11 test` I'm seeing errors when the `missing-docs = "deny"` lint is configured in Cargo.toml.

[I've put together this minimal repo that reproduces the issue](https://github.com/ytmimi/deny_missing_docs):

I tried running:
```
cargo +nightly-2024-09-11 test                                       
```

I believe this is happening because of the [test macro expansion](https://github.com/rust-lang/rust/blob/f7f8bdf2e03918cc3742db3bb37b7cfe9994dbec/library/core/src/macros/mod.rs#L1656-L1661) and the recent changes to emit missing_doc lints during tests (https://github.com/rust-lang/rust/commit/33855f80d4393bff5d1226eabf8e61f348179cee)

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (0ee7cb5e3 2024-09-10)
binary: rustc
commit-hash: 0ee7cb5e3633502d9a90a85c3c367eccd59a0aba
commit-date: 2024-09-10
host: aarch64-apple-darwin
release: 1.83.0-nightly
LLVM version: 19.1.0
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling deny_missing_docs v0.1.0 (deny_missing_docs)
error: missing documentation for the crate
 --> src/main.rs:1:1
  |
1 | / fn main() {
2 | |     println!("Hello, world!");
3 | | }
  | |_^
  |
  = note: requested on the command line with `-D missing-docs`

error: missing documentation for the crate
 --> tests/integration.rs:1:1
  |
1 | / #[test]
2 | | fn do_nothing() {}
  | |__________________^
  |
  = note: requested on the command line with `-D missing-docs`

error: could not compile `deny_missing_docs` (bin "deny_missing_docs") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: missing documentation for a constant
 --> tests/integration.rs:2:1
  |
1 | #[test]
  | ------- in this procedural macro expansion
2 | fn do_nothing() {}
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `deny_missing_docs` (bin "deny_missing_docs" test) due to 1 previous error
error: could not compile `deny_missing_docs` (test "integration") due to 2 previous errors
```

</p>
</details>

**Comment by Urgau** [comment] 2024-09-11 18:56
Duplicate of https://github.com/rust-lang/rust/issues/130216, which will be fixed by 130219

**Closed by Urgau** 2024-09-11 18:56 UTC
Labels: C-bug, needs-triage
