### ISSUE TITLE
Can't link static library in /usr/local/lib

### ISSUE THREAD

**Issue by dragostis** [rust-lang/rust#31419] opened 2016-02-04 23:41 UTC
I'm trying to build a library with a `#[link]`ed static library which lies in `/usr/local/lib`, but `rustc` can't seem to find it. I haven't been able to find the default paths that it looks through.

The command is this:
```
rustc src/lib.rs --crate-name mrusty --crate-type lib -g --out-dir
/Users/dragos/Documents/Rust/mrusty/target/debug --emit=dep-info,link -L
dependency=/Users/dragos/Documents/Rust/mrusty/target/debug -L
dependency=/Users/dragos/Documents/Rust/mrusty/target/debug/deps --extern
libc=/Users/dragos/Documents/Rust/mrusty/target/debug/deps/liblibc-47e3aae331d291a4.rlib
```

The error is this:
```
error: could not find native static library `mruby`, perhaps an -L flag is missing?
```

**Comment by dragostis** [comment] 2016-02-05 00:09
If I like it dynamically by not providing any `kind`, it seems to use `ld` instead of `rustc` to link it which is working.

**Comment by retep998** [comment] 2016-02-05 06:48
`kind=static` means that `rustc` is responsible for finding the library and bundling it in, which means it _completely_ ignores the standard paths where the linker would look for libraries. I really ought to write an RFC to add a `kind` for non-bundled static libraries.

**Comment by retep998** [comment] 2016-02-05 07:21
And I wrote an RFC. https://github.com/rust-lang/rfcs/pull/1489

**Comment by dragostis** [comment] 2016-02-05 10:57
The question is, is there a way to link an external library statically so I can have a portable executable?

**Comment by alexcrichton** [comment] 2016-02-05 18:58
Ah yes this happens because the lookup paths for the compiler aren't initialized to have system directories (as they vary *widely* between systems). To get rustc to pick it up you'll want to pass `-L native=/usr/lib` (or wherever else it is).

This is intended behavior, however, so I'm going to close this. Thanks for the report @dragostis!

**Closed by alexcrichton** 2016-02-05 18:58 UTC
