### ISSUE TITLE
Confusing "type mismatch" error report: the types might differ while pretty-printer prints them in exactly the same way

### ISSUE THREAD

**Issue by golddranks** [rust-lang/rust#23252] opened 2015-03-10 13:43 UTC
I just encountered this error: (newlines added to hightlight the sameness of the pretty-printer result)

```
error: type mismatch:
the type `fn(&mut iron::request::Request<'_>) -> core::result::Result<iron::response::Response, iron::error::IronError> {frontpage}` implements the trait
`for<'r,'r> core::ops::Fn<(&'r mut iron::request::Request<'r>,)>`, but the trait
`for<'r,'r> core::ops::Fn<(&'r mut iron::request::Request<'r>,)>` is required (expected struct
`iron::request::Request`, found a different struct 
`iron::request::Request`) [E0281]
```

This happened to me, because I had my own debugging version of Iron linked in my Cargo.toml. However, I also had the vanilla straight-from-cargo version of Iron extension, Router, linked. Thus, my own code referenced different "iron" crate than the Router code. This made the error report confusing: it looks like the type is the exactly same, although it's from different crate.

I think there's a very simple fix: just check if the traits pretty-prints are exactly the same, and if they are, provide additional information why they are different: i.e. print the paths of the crates they are from.

**Comment by jakub-** [comment] 2015-03-10 14:09
A dupe of https://github.com/rust-lang/rust/issues/22750 but the test case is a tad different so I'll leave this open.

**Comment by dotdash** [comment] 2016-04-13 18:26
Comparing the pretty printed names is not necessarily enough. if you use `extern crate foo` once at the top-level and once within `mod bar`, you'll get `expected foo::Type found bar::foo::Type`, which in some way is even more confusing, but regardless of that, should also have a hint, that it's the same crate but in different versions.

**Comment by Mark-Simulacrum** [comment] 2017-05-02 23:37
I'm going to close in favor of #22750 since that issue has more discussion and this issue doesn't have a specific test case that I can see.

**Closed by Mark-Simulacrum** 2017-05-02 23:37 UTC
Labels: A-diagnostics
