### ISSUE TITLE
Documentation for `[T; N]` lacks "Methods from Deref<Target = [T]>" section

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#76124] opened 2020-08-30 20:38 UTC
For example, see [that section for `Vec`](https://doc.rust-lang.org/std/vec/struct.Vec.html#deref-methods). The section is missing from [the array docs](https://doc.rust-lang.org/nightly/std/primitive.array.html).

**Comment by robojumper** [comment] 2020-08-30 22:53
`[T; N]` does not implement `Deref`. `[T; N]` coerces to `[T]` through Unsizing.

**Comment by LukasKalbertodt** [comment] 2020-08-31 09:21
Ohhh right. Would it make sense to include the methods of `[T]` anyway? I mean for most programmers, the only thing that matters is "what I can call with the dot method syntax", I guess?

**Comment by robojumper** [comment] 2020-08-31 14:10
I feel like it'd make sense. `rustdoc` currently doesn't seem to have any knowledge about the automatic `Unsize` implementations (empty [Implementors list](https://doc.rust-lang.org/core/marker/trait.Unsize.html)).

**Comment by ollie27** [comment] 2020-09-02 16:56
Duplicate of #62992

**Closed by ollie27** 2020-09-02 16:56 UTC
Labels: T-rustdoc
