### ISSUE TITLE
NLL Regressions in 1.40

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#66517] opened 2019-11-18 14:34 UTC
* [thrussh](https://crates.io/crates/thrussh): point release needed with a fix: 0.19.6; [broken](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/async-ssh-0.1.2/log.txt)
* [vek](https://crates.io/crates/vek): verify that more recent versions build, 0.9.4 is [broken](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/LEARAX.red_rim/log.txt)
* [florima/agents](https://github.com/floriama/agents): fix master, [broken](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/floriama.agents/log.txt)
* https://github.com/johshoff/find-tempo-rust-backend: https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/johshoff.find-tempo-rust-backend/log.txt
* https://github.com/mfontanini/rpki-validator: https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/mfontanini.rpki-validator/log.txt
* https://github.com/fernandobatels/blitz-money: https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/fernandobatels.blitz-money/log.txt

root: capnp - 4 (1 gh, 3 crates.io) detected crates which regressed due to this:
<details>

 * capnp-gj-0.2.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/capnp-gj-0.2.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/capnp-gj-0.2.1/log.txt)
 * leaf-0.2.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/leaf-0.2.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/leaf-0.2.1/log.txt)
 * rotor-capnp-0.1.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/rotor-capnp-0.1.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/rotor-capnp-0.1.0/log.txt)
 * dmichiels/temp_rustfbp: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/gh/dmichiels.temp_rustfbp/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/dmichiels.temp_rustfbp/log.txt)

</details>

* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/chiisai-0.1.6/log.txt

root: epub - 4 (2 gh, 2 crates.io) detected crates which regressed due to this
<details>

 * epub-1.2.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/epub-1.2.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/epub-1.2.0/log.txt)
 * mdbook-epub-0.3.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/mdbook-epub-0.3.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/mdbook-epub-0.3.0/log.txt)
 * Michael-F-Bryan/mdbook-epub: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/gh/Michael-F-Bryan.mdbook-epub/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/Michael-F-Bryan.mdbook-epub/log.txt)
 * cthwaite/pulp: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/gh/cthwaite.pulp/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/cthwaite.pulp/log.txt)

</details>

* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/tigertoes.fe2o3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/AuroransSolis.fractions_and_matrices/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/galvanize-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/remram44.vigilant-steel/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/genco-0.3.30/log.txt

root: gfx-hal - 4 (2 gh, 2 crates.io) detected crates which regressed due to this
<details>

 * bvh_anim-0.4.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/bvh_anim-0.4.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/bvh_anim-0.4.0/log.txt)
 * imagine-0.0.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/reg/imagine-0.0.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/imagine-0.0.1/log.txt)
 * lcnr/wgpu_err: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/gh/lcnr.wgpu_err/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/lcnr.wgpu_err/log.txt)
 * vitvakatu/cubes: [start](https://crater-reports.s3.amazonaws.com/beta-1.40-1/1.39.0/gh/vitvakatu.cubes/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/vitvakatu.cubes/log.txt)

</details>

root: gltf - 10 (6 gh, 4 crates.io) detected crates which regressed due to this:
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/gltf-importer-0.10.1/log.txt

* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/osprey-0.4.4/log.txt

root: gstreamer - 3 (3 gh, 0 crates.io) detected crates which regressed due to this
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/man0lis.ascii-star/log.txt

* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/hpack_codec-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/Gopiandcode.html_gen/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/ilp-packet-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/crazymerlyn.kilo-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/ethowitz.life/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/liner-0.4.4/log.txt

root: liquid-value - 6 (4 gh, 2 crates.io) detected crates which regressed due to this
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/amethyst_tools-0.9.0/log.txt

* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/nero-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/sarahlim.parcheesi/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/quickercheck-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/rental-0.5.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/koba-e964.rust-number-theory/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/SpinResearch.RustySecrets/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/SiegeEngine.siege-example-client/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/smoltcp-0.5.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/c7x43t.hello_cargo2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/cucumber-0.3.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/Askannz.icosphere/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/espota-server-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/alexjeffries.yams/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/leguichet-0.1.8/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/reg/redox_pkgutils-0.1.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/RustyVolley.RustyVolleySrc/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/achankf.game-project/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/u59u75u65.lihkgbox-rs/log.txt

**Comment by Centril** [comment] 2019-11-19 10:20
Is there anything actionable here?

**Comment by Mark-Simulacrum** [comment] 2019-11-19 13:15
I am hopeful that we can patch crates on crates.io at least, ideally we'd go out and fix all of the above (i.e., PRs, or better yet releases where applicable) in time for the release.

**Comment by pnkfelix** [comment] 2019-11-21 13:49
triage: P-high

**Comment by pnkfelix** [comment] 2019-11-21 14:01
nominating for discussion at triage meeting, to see if we can get a subset of developers to divvy up the work here.

**Comment by lqd** [comment] 2019-11-21 15:03
I took a look at
1) `chiisai-0.1.6`: the [repository](https://github.com/mgattozzi/chiisai) has been archived 
2) the `capnp` root:
- `capnp-gj-0.2.1` depends on `capnp-0.7.5`: the [repository](https://github.com/dwrensha/capnp-gj) was marked deprecated in 2017
- `leaf-0.2.1` depends on `capnp-0.6.2`: the [project](https://github.com/autumnai/leaf) has been abandoned in 2016
- `rotor-capnp-0.1.0` depends on `capnp-0.6.2`: the [repository](https://github.com/0x1997/rotor-capnp) looks inactive since 2016
- `dmichiels.temp_rustfbp` depends on `capnp-0.7.5`: the [repository](https://github.com/dmichiels/temp_rustfbp) looks like a test, inactive since 2016

**Comment by pnkfelix** [comment] 2019-11-28 14:05
discussed this in [last week's T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/38419weeklymeeting2019112154818.html#181315922).

Removing nomination and self-assigning to push through remainder of review.

**Comment by Mark-Simulacrum** [comment] 2019-11-28 14:09
I think I actually finished most of the bullets in the hackmd, mostly concluding that there's no need to take any particular action. I believe there's a few unchecked bullets left that probably warrant some deeper investigation (perhaps a PR).

**Comment by lqd** [comment] 2019-11-29 13:51
As another update, there was also coordination in [this zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/122657-t-compiler.2Fwg-nll/topic/regressions.20in.20.2366517). 

We've gone over the list, sent a few PRs where we could (many thanks to @djc for helping with this as well), and it seems like we're in an OK place.

**Comment by lqd** [comment] 2019-11-29 20:48
also, many thanks to @P-E-Meunier for publishing the semver-compatible updates `0.19.6` and `0.20.8` to `thrussh` :tada:

**Comment by Mark-Simulacrum** [comment] 2019-11-29 21:10
I believe we are now ready to close this issue, deeming the rest of the regressions as either won't fix (due to the crate/repository in question being deprecated or otherwise unmaintained) or fixable via `cargo update` (and we don't have the resources to send hundreds of PRs doing so).

**Closed** 2019-11-29 22:43 UTC
Labels: A-NLL, P-high, T-compiler, T-release, regression-from-stable-to-beta
