### ISSUE TITLE
15% regression in compiler memory usage for `inflate` crate

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#43834] opened 2017-08-13 02:54 UTC
[According to perf.rust-lang.org](https://perf.rust-lang.org/graphs.html?start=2017-06-10T00%3A00%3A00%2B00%3A00&end=2017-08-05T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22List%22%2C%22content%22%3A%5B%22inflate-0.1.0%22%5D%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=rss&yaxis=pct) the `inflate-0.1.0` benchmark regressed 15% in memory usage over the past few weeks.

There was an initial big regression due to https://github.com/rust-lang/rust/pull/39409 and https://github.com/rust-lang/rust/pull/43576 recovered most of it but unfortunately there's still a 15% overall regression from before :(

**Comment by alexcrichton** [comment] 2017-08-13 02:59
A similar, but not as large [regression can be seen](https://perf.rust-lang.org/graphs.html?start=2017-06-10T00%3A00%3A00%2B00%3A00&end=2017-08-05T00%3A00%3A00%2B00%3A00&crates=%7B%22list%22%3A%22List%22%2C%22content%22%3A%5B%22issue-20936-deep-vector%22%5D%7D&phases=%7B%22list%22%3A%22All%22%2C%22content%22%3Anull%7D&group_by=crate&type=rss&yaxis=pct) for the deep vector benchmark

**Comment by arielb1** [comment] 2017-08-17 20:50
Looks expected, but someone should run a profiler to confirm it's what it looks like.

**Comment by nikomatsakis** [comment] 2017-08-17 20:50
Believed to be fallout from `EndRegion`. In that case, we can probably just close as "expected", if unfortunate. Those are however likely to go away with the migration to NLL, so hopefully we will recover eventually. It'd be nice to do a quick profile to double check.

**Comment by nikomatsakis** [comment] 2017-08-24 20:23
triage: P-medium

**Comment by alexcrichton** [comment] 2017-08-28 14:22
1.21 is now in beta

@nikomatsakis should this *not* be on the milestone for 1.21?

**Comment by nikomatsakis** [comment] 2017-08-31 20:23
@alexcrichton we were hoping to verify the results and make sure we at least know the cause. @pnkfelix has done some of the legwork here but I think we're still not clear that `EndRegion` is to blame, yet.

**Comment by pnkfelix** [comment] 2017-09-01 16:18
Just some quick data to supply here: I switched to `extern crate alloc_system;` in`rustc` in order to get `massif` working.

When using `valgrind --tool=massif`, I was getting peak memory numbers for inflate like this:

Skip `EndRegion` | Emit `EndRegion` | ratio
------------------|------------------|--------
198.1 MB             |  207.2 MB             |   1.046

This led me to think that there might be some other issue causing the regression being reported.

But after @nikomatsakis pushed back a little, I switched to using `/bin/time`, which on Linux includes peak memory usage in its report. The numbers then bounced around some, but on average they looked like this:

Skip `EndRegion` | Emit `EndRegion` | ratio
-------------------|--------------------|------
259.4 MB              | 329.4 MB                  | 1.27

That was a lot scarier, and let me to thus file PR #44249.

(I don't know why the massif report is *so* different from the one I get from `/bin/time`. I have found myself repeating the phrase "'tis an ill workman that quarrels with his own tools" a lot over the past few days...)

**Comment by alexcrichton** [comment] 2017-09-01 16:36
Hm that is indeed very odd! I would have thought that massif wouldn't tamper too much with the output... I wonder if thats something like really bad heap fragmentation where massif sums up literal allocation sizes whereas `/bin/time` sums up the actual pages being used?

**Comment by nikomatsakis** [comment] 2017-09-08 12:13
Looking at perf, I see that the regression has been fixed by #44249. We'll have to wrangle this when it comes to switch to MIR borrowck, but we'll worry about then.

**Closed by nikomatsakis** 2017-09-08 12:13 UTC
Labels: C-tracking-issue, I-compilemem, P-medium, regression-from-stable-to-beta, T-compiler
