### ISSUE TITLE
Consider improving layout of this enum

### ISSUE THREAD

**Issue by carllerche** [rust-lang/rust#24041] opened 2015-04-04 03:22 UTC
I think the following snippet should be possible (but it fails currently). Since `&'static MyTrait` can't be 0, if the first half of the layout is 0, then the enum must be the `Boxed` variant.

``` rust
use std::mem;

pub trait MyTrait {
    fn zomg(&self);
}

enum Foo {
    Inline(&'static MyTrait, [usize; 2]),
    Boxed(Box<MyTrait>),
}

pub fn main() {
    assert_eq!(2 * mem::size_of::<&'static MyTrait>(), mem::size_of::<Foo>());
}
```

**Comment by cybergeek94** [comment] 2015-04-12 21:16
I'm not sure I follow. `&MyTrait` and `Box<MyTrait>` are the same width, neither can be zero, and the second half of the enum could be `[0us; 2]` or empty space. I don't see a way to deduce the variant without a discriminator. Maybe I'm missing something.

**Comment by Diggsey** [comment] 2015-04-12 21:31
The layout of the Boxed variant could theoretically be altered such that `Box<MyTrait>` occupies the same space as the `[usize; 2]` from the Inline variant. The first `usize` bytes could then be used as the discriminator, where 0 => Boxed, _ => Inline.

I'm not sure how worthwhile this is, since it's very specific, and the algorithm to calculate the best layout for every possible scenario is at the very least non-obvious. If there is ever a rust ABI, then it would be preferable to have layouts controlled by predictable, easy to describe rules.

**Comment by dotdash** [comment] 2015-04-12 21:31
If you put the box in the same space as the array, i.e. in the second half,
then you can identify the Boxed variant by the first half being set to zero.
Am 12.04.2015 23:17 schrieb "Austin Bonander" <notifications@github.com>:

**Comment by Marwes** [comment] 2015-06-27 10:45
Its not necessarily a strictly better idea to put the box in the same space as the array though.

```rust
fn zomg(foo: &Foo)
    match *foo {
        Inline(ref t, _) => t.zomg(),
        Boxed(ref t) => t.zomg()
}
```

In a function such as above, since the the data and vtable are in the same position it could be optimized to just load those positions and call the function, avoiding the discriminant test completely. I don't know if llvm performs that sort of optimization though.

**Comment by steveklabnik** [comment] 2016-11-29 21:36
Triage: `thread 'main' panicked at 'assertion failed: `(left == right)` (left: `32`, right: `40`)',`

**Comment by nox** [comment] 2018-04-01 17:51
This could be done with @eddyb's niche-filling optimisation. It currently only applies to enums with a single dataful variant, but we could make it apply to the largest variant of the enum instead. I am pretty sure this would also improve the layout of a bunch of enums in Stylo.

I've thought about this a bit and I think the niche-filling optimisation should apply to the largest variant of any `repr(Rust)` enum, if there is no other variant that is as large.

Cc @rust-lang/wg-codegen

**Comment by eddyb** [comment] 2018-04-10 12:10
This seems to (now) be a duplicate of #46213.

**Comment by dtolnay** [comment] 2019-07-15 03:00
Closing in favor of the more general #46213.

**Closed by dtolnay** 2019-07-15 03:00 UTC
Labels: A-codegen, C-enhancement
