### ISSUE TITLE
Error help for ambiguous associated type introduces unstable fixing.

### ISSUE THREAD

**Issue by Evian-Zhang** [rust-lang/rust#82657] opened 2021-03-01 13:55 UTC
I tried this code:

```rust
trait A {
    type Foo;
}

trait B {
    type Foo;
}

trait C: A + B {}

trait D {
    type E: C<Foo = Foo>;
}

struct Foo {}
```

It is true that the trait bound  `C<Foo = Foo>` of associated type `E` in `D` is ambiguous, since supertrait `A` and `B` both have `Foo` associated type.

However, the error report is

```plaintext
error[E0222]: ambiguous associated type `Foo` in bounds of `C`
  --> src/main.rs:12:15
   |
2  |     type Foo;
   |     --------- ambiguous `Foo` from `A`
...
6  |     type Foo;
   |     --------- ambiguous `Foo` from `B`
...
12 |     type E: C<Foo = Foo>;
   |               ^^^^^^^^^ ambiguous associated type `Foo`
   |
   = help: consider introducing a new type parameter `T` and adding `where` constraints:
               where
                   T: C,
                   T: B::Foo = Foo,
                   T: A::Foo = Foo
```

Adding a `where` clause for associated type `E` is unstable, but the error help suggests us to do so.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-apple-darwin
release: 1.50.0
```

**Comment by fmease** [comment] 2023-11-19 11:21
Closing in favor of the slightly newer #97583 which explains the problem more succinctly (the issue is about the equality bound not the where-clause on assoc types which is stable by now).

**Closed by fmease** 2023-11-19 11:21 UTC
Labels: A-diagnostics, A-traits, A-associated-items, T-compiler, C-bug, D-invalid-suggestion
