### ISSUE TITLE
Recent 12% perf regression in unused-warnings

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#52092] opened 2018-07-06 01:11 UTC
A [recent perf regression](https://perf.rust-lang.org/compare.html?start=a739c51d108b1958a1c3e145588035c580e7973a&end=0ad8f9e5b1950e4ac09950def4231c8d5875de57&stat=instructions:u) showed up somewhere in [this range](https://github.com/rust-lang/rust/compare/a739c51d108b1958a1c3e145588035c580e7973a...0ad8f9e5b1950e4ac09950def4231c8d5875de57). I don't think perf has enough data to narrow it down further yet to a particular PR, but of the PRs in that list https://github.com/rust-lang/rust/pull/51895 looks the most suspect.

@nikomatsakis or @tmandry y'all may be interested in this!

**Comment by alexcrichton** [comment] 2018-07-06 01:12
The [wall time measurements](https://perf.rust-lang.org/compare.html?start=a739c51d108b1958a1c3e145588035c580e7973a&end=0ad8f9e5b1950e4ac09950def4231c8d5875de57&stat=wall-time) look a bit more severe :(

also cc @nnethercote

**Comment by nnethercote** [comment] 2018-07-09 01:54
perf.rust-lang.org now clearly points to PR #51895:
https://github.com/rust-lang/rust/compare/a739c51d108b1958a1c3e145588035c580e7973a...8dd715ee5e462384668e3c83c17ee641e9776b64

**Comment by pnkfelix** [comment] 2018-07-12 14:39
visiting for triage. Assigning to @nikomatsakis for now, under assumption that he is best person to investigate this in the very short term.

**Comment by pnkfelix** [comment] 2018-07-12 14:41
also making P-high for now. (I'm not 100% clear on how important the efficiency of this particular benchmark is, but it is probably worth treating it as high until someone can provide an argument for deprioritization.)

**Comment by pnkfelix** [comment] 2018-07-26 14:10
visiting for triage, assigning to self in hopes I find time to look at this during next week.

**Comment by pnkfelix** [comment] 2018-08-02 14:11
unassigning self since I will be absent for three weeks after end of day tomorrow.

**Comment by arielb1** [comment] 2018-08-26 17:02
The relevant test file mainly consists of 20,000 `use` statements without any content.

I had looked at this, and it is at least 90% accountable to the addition of 2*20,000 query calls during the processing:

1. The new `predicates_defined_on` query: https://github.com/rust-lang/rust/pull/51895/files#diff-4ed25c00aceb84666fca639cf8101c7cR1313
2. `explicit_predicates_of` at https://github.com/rust-lang/rust/pull/51895/files#diff-4ed25c00aceb84666fca639cf8101c7cR1316 being changed from a function call to a query

This does feel like an edge-case to me - in most cases I can think of, the query overhead of actually collecting an item - which is just a few microseconds per item - is far below the overhead of actually processing that item.

However, if we want to just "get rid of the regression", it might be a good idea to add a bypass to `param_env` on items that lack generics (at least, `use` items) that avoids the entire query mechanism. This might speed up artificial code that has a lot of generic-free items.

And of course it's always a good idea to speed up queries.

**Comment by arielb1** [comment] 2018-08-26 17:25
I would lower this issue to P-medium unless someone actually cares about this case, this code is going to get refactored to death anyway.

**Comment by pnkfelix** [comment] 2018-08-30 14:33
downgrading to P-medium on basis on analysis and arguments presented by @arielb1 above.

**Comment by Mark-Simulacrum** [comment] 2024-01-16 00:06
Given it's been 5(!) years I don't think there's value in keeping this open -- at best, this is tracking "can we make unused-warnings faster?" which feels like not a useful thing to track.

**Closed by Mark-Simulacrum** 2024-01-16 00:06 UTC
Labels: A-lint, P-medium, I-compiletime, T-compiler, regression-from-stable-to-stable
