### ISSUE TITLE
Using font size greater than 16 cause docs to render oddly

### ISSUE THREAD

**Issue by iamsauravsharma** [rust-lang/rust#93171] opened 2022-01-17 10:28 UTC
Changing default font size from 16 to 17 on Firefox makes docs.rs page to render oddly. 

### Default font size: 17
![Screenshot_20220117_160326](https://user-images.githubusercontent.com/38726015/149751591-ad86464d-0bd2-409e-9ec1-e98cc46b0661.png)

### Default font size: 16
![Screenshot_20220117_160350](https://user-images.githubusercontent.com/38726015/149751666-0c967495-003f-40f3-8da1-742b4cdbeec3.png)

**Comment by Nemo157** [comment] 2022-01-21 19:52
@jsha transferred

**Comment by jsha** [comment] 2022-01-22 00:38
@cynecx The `width: 100%` thing you posted _works_, but it's unsatisfying. If the issue is lack of an explicit `width: 100%`, why does this only show up on font sizes >16px?

Here's another possible fix: set `font-size: 16px` on `div.nav-container`. The page was previously inheriting `font-size: 16px` from rustdoc's CSS, which sets that on `body`. When rustdoc's CSS changes to `font-size: 1rem` (i.e. respect what the user set), that also affected the font size in the topbar. Since the docs.rs topbar has a fixed height of 33px, this caused some of the elements to overflow the topbar, at which point they interfered with `<main>`'s ability to automatically grow as far as it needed.

What I like about this solution is it doesn't layer tweaks on top of tweaks. Instead, it's adding back in something explicit that docs.rs was implicitly depending on, but that it shouldn't have been.

**Comment by jsha** [comment] 2022-01-31 11:07
This is fixed in rust-lang/docs.rs#1614.

**Closed by jsha** 2022-01-31 11:07 UTC
Labels: T-rustdoc, A-rustdoc-ui

**Comment by jam1garner** [comment] 2022-03-16 18:56
Since this fix won't retroactively apply to old docs, if anyone else runs into this thread, here's a ublock origin filter that has worked for me:

```css
docs.rs###rustdoc_body_wrapper:style(width: 100% !important;)
```

(Coincidentally it uses the same hack-fix as cynecx mentioned)

I should note that I observe this issue for non-font reasons (I believe, inspector could be lying to me about font calculations) due to the fact I always view docs in a vertical window (half split (left/right) of a 1080p monitor).

And here's also an untested attempt at using built-in firefox userstyles:
 
```css
@-moz-document domain(docs.rs) {
    #rustdoc_body_wrapper {
        width: 100% !important;
    }
}
```

([how to use if you're not familiar with userstyles](https://superuser.com/a/319322))

And if you want to check if it works, [here's a crate+version](https://docs.rs/owo-colors/3.2.0/owo_colors/index.html) which is affected.
