### ISSUE TITLE
rustc panics when trying to get session directory when building project on ramdisk

### ISSUE THREAD

**Issue by jamclema** [rust-lang/rust#62631] opened 2019-07-12 20:00 UTC
Seems similar to #52440, but no cross platform weirdness is in play. Project builds fine on a normal C drive on windows, but when the same repo is cloned to a ramdisk (created by imdisk driver) on windows, rustc panics. 
First incremental compilation gives an error so it appears to be handled, but then the compiler panics. 

`
error: incremental compilation: error canonicalizing path <path>: Incorrect function. (os error 1)

thread 'rustc' panicked at 'src\librustc\session\mod.rs:813: Trying to get session directory from IncrCompSession `NotInitialized`', src\librustc\util\bug.rs:37:26
`

Platform info:
`
rustc 1.36.0-nightly (50a0defd5 2019-05-21) running on x86_64-pc-windows-msvc
compiler flags: -C debuginfo=2 -C incremental --crate-type bin
`

**Comment by jscarrott** [comment] 2019-08-05 14:48
I'm also getting this issue using imdisk

**Comment by Stzx** [comment] 2020-09-03 15:04
Is there any progress?

**Comment by Enselic** [comment] 2023-08-28 07:34
Triage: Closing as duplicate of #48249

**Closed by Enselic** 2023-08-28 07:34 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
