### ISSUE TITLE
Segmentation fault compiling inline assembly using function address

### ISSUE THREAD

**Issue by IsaacWeintraub** [rust-lang/rust#70596] opened 2020-03-31 02:52 UTC
### Code
This was compiled targeting ARM Cortex-A53 with `opt-level=3`.
```
#![feature(asm)]
extern "C" fn foo() {}

fn main() {
  unsafe {
    asm!("mov x0, $0"
      :: "r"(foo)
      :: "volatile");
  }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.37.0-nightly (0af8e872e 2019-06-30)
binary: rustc
commit-hash: 0af8e872ea5ac77effa59f8d3f8794f12cb8865c
commit-date: 2019-06-30
host: x86_64-unknown-linux-gnu
release: 1.37.0-nightly
LLVM version: 8.0
```

### Error output

```
Segmentation fault (core dumped)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

Even re-running the command I invoked previously with RUST_BACKTRACE=1, the only output I get is 
```
Segmentation fault (core dumped)
```

</p>
</details>

**Comment by Amanieu** [comment] 2020-05-08 13:09
Duplicate of #68136. As a workaround you can use `foo as usize`.

**Closed** 2020-05-08 13:09 UTC
Labels: A-inline-assembly, C-bug, I-ICE, P-low, T-compiler, glacier, requires-nightly
