### ISSUE TITLE
Internal Compiler Error: Nightly, Rocket, Diesel

### ISSUE THREAD

**Issue by casperin** [rust-lang/rust#83523] opened 2021-03-26 18:29 UTC
Played around with Rocket yesterday, and today when I tried to run/compile the same program, I got a compiler error. It is my first time on Nightly and I don't really know what to look for when searching if others have already reported it. Just reporting this, in case it is helpful for you in some way.

### Code

In the error it refers to line 17. That's the `#[database("postgres")]` line. The db is running, and I have not made any changes to it since the program was running last time.

```Rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use]
extern crate rocket;
#[macro_use]
extern crate diesel;

mod schema;

use crate::schema::companies;
use diesel::prelude::*;
use diesel::{Insertable, Queryable};
use rocket_contrib::databases::{database, diesel::PgConnection};
use rocket_contrib::json::Json;
use serde_derive::{Deserialize, Serialize};

#[database("postgres")]
struct DbConn(PgConnection);

#[derive(Queryable, Serialize, Deserialize)]
struct Company {
    id: i32,
    name: String,
}

#[derive(Insertable, Deserialize)]
#[table_name = "companies"]
struct NewCompany {
    name: String,
}

#[get("/", format = "application/json")]
fn get_companies(conn: DbConn) -> Json<Vec<Company>> {
    let companies = companies::table
        .order(companies::id.desc())
        .load::<Company>(&*conn)
        .unwrap();
    Json(companies)
}

#[post("/", data = "<new_company>", format = "application/json")]
fn create_company(conn: DbConn, new_company: Json<NewCompany>) -> Json<Company> {
    let result = diesel::insert_into(companies::table)
        .values(&new_company.0)
        .get_result(&*conn)
        .unwrap();
    Json(result)
}

#[put("/", data = "<company>", format = "application/json")]
fn edit_company(conn: DbConn, company: Json<Company>) -> Json<Company> {
    let target = companies::table.find(company.id);
    //.filter(companies::columns::id.eq(company.id));
    let result = diesel::update(target)
        .set(companies::columns::name.eq(&company.name))
        .get_result(&*conn)
        .unwrap();
    Json(result)
}

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

#[get("/<name>")]
fn hello(name: String) -> String {
    format!("Hello, {}!", name)
}

fn main() {
    rocket::ignite()
        .attach(DbConn::fairing())
        .mount("/hello", routes![index, hello])
        .mount(
            "/companies",
            routes![get_companies, create_company, edit_company],
        )
        .launch();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.
```

### Error output

```
   Compiling movei v0.1.0 (/home/g/code/movei/rust_01)
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::ops::deref::Deref): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::Deref>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:64:1: 64:16 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::Deref`
#1 [check_item_well_formed] checking that `<impl at src/main.rs:17:1: 17:24>` is well-formed
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::ops::deref::DerefMut): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::Deref>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:170:21: 170:26 (#0)), (Binder(TraitPredicate(<Self as std::ops::DerefMut>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:170:1: 170:26 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::DerefMut`
#1 [check_item_well_formed] checking that `<impl at src/main.rs:17:1: 17:24>` is well-formed
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::marker::Sized): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Sized>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/marker.rs:92:1: 92:16 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::marker::Sized`
#1 [check_item_well_formed] checking that `_impl_queryable_for_company::<impl at src/main.rs:20:10: 20:19>` is well-formed
end of query stack
error: could not compile `movei`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   Compiling movei v0.1.0 (/home/g/code/movei/rust_01)
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::ops::deref::Deref): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::Deref>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:64:1: 64:16 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:435:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   6: rustc_trait_selection::traits::wf::WfPredicates::nominal_obligations
   7: rustc_trait_selection::traits::wf::WfPredicates::compute_trait_ref
   8: rustc_trait_selection::traits::wf::trait_obligations
   9: rustc_infer::infer::InferCtxtBuilder::enter
  10: rustc_typeck::check::wfcheck::check_item_well_formed
  11: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_query_system::query::plumbing::force_query_with_job
  14: rustc_query_system::query::plumbing::get_query_impl
  15: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_item_well_formed
  16: <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor as rustc_hir::intravisit::Visitor>::visit_item
  17: rustc_data_structures::sync::par_for_each_in
  18: rustc_hir::hir::Crate::par_visit_all_item_likes
  19: rustc_session::session::Session::track_errors
  20: rustc_typeck::check_crate
  21: rustc_interface::passes::analysis
  22: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  24: rustc_data_structures::stack::ensure_sufficient_stack
  25: rustc_query_system::query::plumbing::force_query_with_job
  26: rustc_query_system::query::plumbing::get_query_impl
  27: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  28: rustc_interface::passes::QueryContext::enter
  29: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  30: rustc_span::with_source_map
  31: rustc_interface::interface::create_compiler_and_run
  32: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::Deref`
#1 [check_item_well_formed] checking that `<impl at src/main.rs:17:1: 17:24>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::ops::deref::DerefMut): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::Deref>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:170:21: 170:26 (#0)), (Binder(TraitPredicate(<Self as std::ops::DerefMut>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:170:1: 170:26 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:435:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   6: rustc_trait_selection::traits::wf::WfPredicates::nominal_obligations
   7: rustc_trait_selection::traits::wf::WfPredicates::compute_trait_ref
   8: rustc_trait_selection::traits::wf::trait_obligations
   9: rustc_infer::infer::InferCtxtBuilder::enter
  10: rustc_typeck::check::wfcheck::check_item_well_formed
  11: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  12: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  13: rustc_query_system::query::plumbing::force_query_with_job
  14: rustc_query_system::query::plumbing::get_query_impl
  15: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_item_well_formed
  16: <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor as rustc_hir::intravisit::Visitor>::visit_item
  17: rustc_data_structures::sync::par_for_each_in
  18: rustc_hir::hir::Crate::par_visit_all_item_likes
  19: rustc_session::session::Session::track_errors
  20: rustc_typeck::check_crate
  21: rustc_interface::passes::analysis
  22: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  24: rustc_data_structures::stack::ensure_sufficient_stack
  25: rustc_query_system::query::plumbing::force_query_with_job
  26: rustc_query_system::query::plumbing::get_query_impl
  27: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  28: rustc_interface::passes::QueryContext::enter
  29: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  30: rustc_span::with_source_map
  31: rustc_interface::interface::create_compiler_and_run
  32: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::DerefMut`
#1 [check_item_well_formed] checking that `<impl at src/main.rs:17:1: 17:24>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::marker::Sized): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::marker::Sized>)), /home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/marker.rs:92:1: 92:16 (#0))] }', /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/compiler/rustc_query_system/src/query/plumbing.rs:593:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:435:5
   2: rustc_query_system::query::plumbing::incremental_verify_ich
   3: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   4: rustc_query_system::query::plumbing::get_query_impl
   5: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::predicates_of
   6: rustc_trait_selection::traits::wf::WfPredicates::nominal_obligations
   7: rustc_trait_selection::traits::wf::WfPredicates::compute_trait_ref
   8: rustc_trait_selection::traits::wf::predicate_obligations
   9: rustc_typeck::check::wfcheck::check_where_clauses
  10: rustc_infer::infer::InferCtxtBuilder::enter
  11: rustc_typeck::check::wfcheck::check_item_well_formed
  12: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  13: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  14: rustc_query_system::query::plumbing::force_query_with_job
  15: rustc_query_system::query::plumbing::get_query_impl
  16: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::check_item_well_formed
  17: <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor as rustc_hir::intravisit::Visitor>::visit_item
  18: rustc_data_structures::sync::par_for_each_in
  19: rustc_hir::hir::Crate::par_visit_all_item_likes
  20: rustc_session::session::Session::track_errors
  21: rustc_typeck::check_crate
  22: rustc_interface::passes::analysis
  23: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::force_query_with_job
  27: rustc_query_system::query::plumbing::get_query_impl
  28: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis
  29: rustc_interface::passes::QueryContext::enter
  30: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  31: rustc_span::with_source_map
  32: rustc_interface::interface::create_compiler_and_run
  33: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (07e0e2ec2 2021-03-24) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::marker::Sized`
#1 [check_item_well_formed] checking that `_impl_queryable_for_company::<impl at src/main.rs:20:10: 20:19>` is well-formed
#2 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `movei`

To learn more, run the command again with --verbose.

```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-03-26 18:40
@casperin: Can you share your full repository (or at least `schema.rs` and your `Cargo.toml`)?

**Comment by casperin** [comment] 2021-03-26 18:45
There is no repo. It's just me playing around locally. Here is schema and cargo.toml

```rust
table! {
    companies (id) {
        id -> Int4,
        name -> Varchar,
    }
}
```

```toml
[package]
name = "movei"
version = "0.1.0"
authors = ["..."]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
serde = "1.0"
diesel = { version = "1.4", features = ["postgres"] }

[dependencies.serde_derive]
version = "1.0"

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json", "diesel_postgres_pool"]
```

**Comment by Aaron1011** [comment] 2021-03-26 18:50
@casperin: Thanks! If this crash is still happening, could you zip and upload your entire `target` directory?

Do you remember what types of changes you were making before this crash happened? This kind of issue is caused by the state of the incremental cache, so this can only be reproduced by compiling the project multiple times (with some modifications).

**Comment by casperin** [comment] 2021-03-26 19:01
It is definitely still happening. I can't get it to compile at all anymore. It's not a problem as such (I'm just testing out various web frameworks to get a feel for them) but it has me looking for something that does not require nightly now.

I was following [this tutorial](https://www.youtube.com/watch?v=tjH0Mye8U_A) with slight changes yesterday. I did not encounter any compiler error then.

Today when running vim again I noticed rust-analyser (coc) was crashing, so I updated it to the newest. That's really the only change I can think of. That, and changing my xterm colors and fontsize :)

Actually, I was also changing the code a bit.. let me see if I can redo them... nope.. but it went to something like this (it will not compile, I was just trying to return `Result` instead of whatever the return type currently says)

```rust
#[post("/", data = "<new_company>", format = "application/json")]
fn create_company(conn: DbConn, new_company: Json<NewCompany>) -> Json<Company> {
    let result = diesel::insert_into(companies::table)
        .values(&new_company.0)
        .get_result(&*conn);
    result.map(Json)
}
```

**Comment by Aaron1011** [comment] 2021-03-26 19:33
> It's not a problem as such

I've had a lot of trouble reproducing this issue, and it's been affecting some other people as well. Any help in reproducing this would be very much appreciated :)

If the crash is still happening, could you create a zip file with your entire project directory (e.g. your `Cargo.toml`, the `src`, and `target` directories)? I've been unable to reproduce this locally, so that would be a huge help in getting this fixed.

**Comment by casperin** [comment] 2021-03-26 19:40
The file is 250mb ... how do I get it to you?

**Comment by Aaron1011** [comment] 2021-03-26 19:46
@casperin: Can you upload it to this Google drive folder: https://drive.google.com/drive/folders/1mRdlADbVaVnxUbF0oBcz8gGi1cuMyQm6?usp=sharing

**Comment by casperin** [comment] 2021-03-26 19:59
Done. Let me know if there is anything else I can do. We can do a zoom call if that would help. Just know that I'm in CET (it's 9pm here)

**Comment by Aaron1011** [comment] 2021-03-26 20:09
Thanks - I'm now able to reproduce it!

**Comment by casperin** [comment] 2021-03-26 20:14
Sweet! Have fun :-)

... this totally made my day btw. My very first (very small) contribution to the greatest language.

**Comment by Aaron1011** [comment] 2021-03-26 21:17
This is related to the presence of the `rust-src` component. When this component is present, rustc is able to 'remap' standard library filenames (this is how you get paths like `/home/g/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/deref.rs:64:1: 64:16 (#0)` which point into your local filesystem.

If I remove the `rustc-src` component when compiling the 'bad' `target` directory, I can no longer reproduce the crash. I'm not sure why this isn't showing up more, but I believe the fix is to only hash the 'virtualized' path (not the 'remapped' path).

**Comment by Aaron1011** [comment] 2021-05-02 02:42
Duplicate of https://github.com/rust-lang/rust/issues/84341. This is fixed in the latest nightly

**Closed by Aaron1011** 2021-05-02 02:42 UTC
Labels: C-bug, I-ICE, T-compiler
