### ISSUE TITLE
thread 'rustc' panicked at 'Box<dyn Any>', on Nightly Rust for a few days now

### ISSUE THREAD

**Issue by octavonce** [rust-lang/rust#111386] opened 2023-05-09 10:00 UTC
Hi, our CI builds have been consistently failing and we cannot build a docker image with the latest nightly. You can find the CI run [here](https://github.com/purpleprotocol/purplecoin/actions/runs/4921527517/jobs/8791450140).

### Meta
```
2023-05-09, rust version 1.71.0-nightly (2f2c438dc 2023-05-08)
```

### Error output

```
 #12 386.6 query stack during panic:
#12 386.6 #0 [collect_and_partition_mono_items] collect_and_partition_mono_items
#12 386.6 end of query stack
#12 386.6 error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:1038:9: no MIR available for DefId(29:2585 ~ wgpu_core[0d9b]::track::texture::{impl#2}::change)
#12 386.6 
#12 386.6 thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/compiler/rustc_errors/src/lib.rs:1650:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
#12 386.6 query stack during panic:
#12 386.6 #0 [collect_and_partition_mono_items] collect_and_partition_mono_items
#12 386.6 end of query stack
#12 386.6 error: internal compiler error: compiler/rustc_monomorphize/src/collector.rs:1038:9: no MIR available for DefId(29:2585 ~ wgpu_core[0d9b]::track::texture::{impl#2}::change)
#12 386.6 
#12 386.6 thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/compiler/rustc_errors/src/lib.rs:1650:9
#12 386.6 stack backtrace:
#12 386.6    0:     0x7f5e658ad361 - std::backtrace_rs::backtrace::libunwind::trace::he9e9030cf5bcddaa
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
#12 386.6    1:     0x7f5e658ad361 - std::backtrace_rs::backtrace::trace_unsynchronized::hb5e44a77ff0586eb
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
#12 386.6    2:     0x7f5e658ad361 - std::sys_common::backtrace::_print_fmt::h38e8723c5d83f22f
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:65:5
#12 386.6    3:     0x7f5e658ad361 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5e394c4b1f1cb045
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:44:22
#12 386.6    4:     0x7f5e6590d6ff - core::fmt::rt::Argument::fmt::ha5dde4cb71578cc2
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/rt.rs:138:9
#12 386.6    5:     0x7f5e6590d6ff - core::fmt::write::hb1413899fd777907
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/core/src/fmt/mod.rs:1094:21
#12 386.6    6:     0x7f5e658a05c1 - std::io::Write::write_fmt::h08b4eac68313bb0d
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/io/mod.rs:1712:15
#12 386.6    7:     0x7f5e658ad175 - std::sys_common::backtrace::_print::h2bb25f41b1777226
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:47:5
#12 386.6    8:     0x7f5e658ad175 - std::sys_common::backtrace::print::ha21981aa5a1c5802
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys_common/backtrace.rs:34:9
#12 386.6    9:     0x7f5e658afe07 - std::panicking::default_hook::{{closure}}::h603ce04329232051
#12 386.6   10:     0x7f5e658afbf4 - std::panicking::default_hook::hd4285764fbdb24e1
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/panicking.rs:288:9
#12 386.6   11:     0x7f5e68b0294b - <rustc_driver_impl[27c68de0ac55b06a]::install_ice_hook::{closure#0} as core[3afeaedfb140cde7]::ops::function::FnOnce<(&core[3afeaedfb140cde7]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
#12 386.6   12:     0x7f5e658b0527 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h401f21a7538313bc
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1999:9
#12 386.6   13:     0x7f5e658b0527 - std::panicking::rust_panic_with_hook::h2322eda2481f33bc
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/panicking.rs:695:13
#12 386.6   14:     0x7f5e68ff1031 - std[53b54636b4f52653]::panicking::begin_panic::<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>::{closure#0}
#12 386.6   15:     0x7f5e68fed7e6 - std[53b54636b4f52653]::sys_common::backtrace::__rust_end_short_backtrace::<std[53b54636b4f52653]::panicking::begin_panic<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>::{closure#0}, !>
#12 386.6   16:     0x7f5e68fed6d6 - std[53b54636b4f52653]::panicking::begin_panic::<rustc_errors[2afb0e2cc7c4c42d]::ExplicitBug>
#12 386.6   17:     0x7f5e68fe8264 - <rustc_errors[2afb0e2cc7c4c42d]::HandlerInner>::bug::<alloc[a4f318becb59a05]::string::String>
#12 386.6   18:     0x7f5e68fe7d76 - <rustc_errors[2afb0e2cc7c4c42d]::Handler>::bug::<alloc[a4f318becb59a05]::string::String>
#12 386.6   19:     0x7f5e69074bac - rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt::<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}
#12 386.6   20:     0x7f5e6907437a - rustc_middle[232bd29a687eeda3]::ty::context::tls::with_opt::<rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}, !>::{closure#0}
#12 386.6   21:     0x7f5e6907434a - rustc_middle[232bd29a687eeda3]::ty::context::tls::with_context_opt::<rustc_middle[232bd29a687eeda3]::ty::context::tls::with_opt<rustc_middle[232bd29a687eeda3]::util::bug::opt_span_bug_fmt<rustc_span[811089187935bcb6]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
#12 386.6   22:     0x7f5e66d0bf8d - rustc_middle[232bd29a687eeda3]::util::bug::bug_fmt
#12 386.6   23:     0x7f5e67984845 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_neighbours
#12 386.6   24:     0x7f5e67974676 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
#12 386.6   25:     0x7f5e67974ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
#12 386.6   26:     0x7f5e67974ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
#12 386.6   27:     0x7f5e67974ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
#12 386.6   28:     0x7f5e67974ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
#12 386.6   29:     0x7f5e67974ae7 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_items_rec
#12 386.6   30:     0x7f5e67f5e250 - rustc_data_structures[fba7df231146955e]::sync::par_for_each_in::<alloc[a4f318becb59a05]::vec::Vec<rustc_middle[232bd29a687eeda3]::mir::mono::MonoItem>, rustc_monomorphize[6a4925edab24b3f4]::collector::collect_crate_mono_items::{closure#1}::{closure#0}>
#12 386.6   31:     0x7f5e67f5df74 - <rustc_session[f2a4139b8ec92988]::session::Session>::time::<(), rustc_monomorphize[6a4925edab24b3f4]::collector::collect_crate_mono_items::{closure#1}>
#12 386.6   32:     0x7f5e67f5d050 - rustc_monomorphize[6a4925edab24b3f4]::collector::collect_crate_mono_items
#12 386.6   33:     0x7f5e67f5b8f7 - rustc_monomorphize[6a4925edab24b3f4]::partitioning::collect_and_partition_mono_items
#12 386.6   34:     0x7f5e6831f5dc - rustc_query_system[8be5ea0cc4c28ea6]::query::plumbing::try_execute_query::<rustc_query_impl[94005537e54250be]::queries::collect_and_partition_mono_items, rustc_query_impl[94005537e54250be]::plumbing::QueryCtxt>
#12 386.6   35:     0x7f5e6831f2bd - rustc_query_impl[94005537e54250be]::get_query::collect_and_partition_mono_items
#12 386.6   36:     0x7f5e67fc439c - rustc_codegen_ssa[4e498a107e2a3c27]::base::codegen_crate::<rustc_codegen_llvm[f9a4b87b46d3b0ee]::LlvmCodegenBackend>
#12 386.6   37:     0x7f5e67fc4182 - <rustc_codegen_llvm[f9a4b87b46d3b0ee]::LlvmCodegenBackend as rustc_codegen_ssa[4e498a107e2a3c27]::traits::backend::CodegenBackend>::codegen_crate
#12 386.6   38:     0x7f5e67d14590 - rustc_interface[1005215f39c21569]::passes::start_codegen
#12 386.6   39:     0x7f5e67d100d7 - <rustc_middle[232bd29a687eeda3]::ty::context::GlobalCtxt>::enter::<<rustc_interface[1005215f39c21569]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<alloc[a4f318becb59a05]::boxed::Box<dyn core[3afeaedfb140cde7]::any::Any>, rustc_span[811089187935bcb6]::ErrorGuaranteed>>
#12 386.6   40:     0x7f5e67d0f84d - <rustc_interface[1005215f39c21569]::queries::Queries>::ongoing_codegen
#12 386.6   41:     0x7f5e67d0ece3 - <rustc_interface[1005215f39c21569]::interface::Compiler>::enter::<rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}::{closure#2}, core[3afeaedfb140cde7]::result::Result<core[3afeaedfb140cde7]::option::Option<rustc_interface[1005215f39c21569]::queries::Linker>, rustc_span[811089187935bcb6]::ErrorGuaranteed>>
#12 386.6   42:     0x7f5e67d0c33b - std[53b54636b4f52653]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1005215f39c21569]::util::run_in_thread_pool_with_globals<rustc_interface[1005215f39c21569]::interface::run_compiler<core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>, rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}>::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>
#12 386.6   43:     0x7f5e683dbf55 - <<std[53b54636b4f52653]::thread::Builder>::spawn_unchecked_<rustc_interface[1005215f39c21569]::util::run_in_thread_pool_with_globals<rustc_interface[1005215f39c21569]::interface::run_compiler<core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>, rustc_driver_impl[27c68de0ac55b06a]::run_compiler::{closure#1}>::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[3afeaedfb140cde7]::result::Result<(), rustc_span[811089187935bcb6]::ErrorGuaranteed>>::{closure#1} as core[3afeaedfb140cde7]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
#12 386.6   44:     0x7f5e658ba9d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h20fe0a24dda744f1
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1985:9
#12 386.6   45:     0x7f5e658ba9d5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb11b4529d66356f4
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/alloc/src/boxed.rs:1985:9
#12 386.6   46:     0x7f5e658ba9d5 - std::sys::unix::thread::Thread::new::thread_start::h896be1b4ceadbc98
#12 386.6                                at /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c/library/std/src/sys/unix/thread.rs:108:17
#12 386.6   47:     0x7f5e6560fb43 - <unknown>
#12 386.6   48:     0x7f5e656a0bb4 - __clone
#12 386.6   49:                0x0 - <unknown>
```

</p>
</details>

**Comment by virtualritz** [comment] 2023-05-09 10:08
I see this issue with `wgpu-15.1` and `v1.71.0-nightly` while building `fj-app-0.46`.

**Comment by Nilstrieb** [comment] 2023-05-09 10:40
This is a duplicate of #111320

**Closed** 2023-05-09 18:11 UTC
Labels: I-ICE, T-compiler, C-bug
