### ISSUE TITLE
Compile bug when installing cargo-update

### ISSUE THREAD

**Issue by Zartr0n** [rust-lang/rust#128654] opened 2024-08-04 16:29 UTC
sorry my first bug report and not sure what to give, so here is the terminal output & my hardware info.

cargo install cargo-update
    Updating crates.io index
  Installing cargo-update v13.4.0
    Updating crates.io index
     Locking 95 packages to latest compatible versions
      Adding bitflags v1.3.2 (latest: v2.6.0)
      Adding clap v3.2.25 (latest: v4.5.13)
      Adding clap_lex v0.2.4 (latest: v0.7.2)
      Adding embed-resource v1.8.0 (latest: v2.4.3)
      Adding git2 v0.18.3 (latest: v0.19.0)
      Adding hashbrown v0.12.3 (latest: v0.14.5)
      Adding hermit-abi v0.1.19 (latest: v0.4.0)
      Adding hermit-abi v0.3.9 (latest: v0.4.0)
      Adding idna v0.5.0 (latest: v1.0.2)
      Adding indexmap v1.9.3 (latest: v2.3.0)
      Adding io-lifetimes v1.0.11 (latest: v2.0.3)
      Adding libgit2-sys v0.16.2+1.7.2 (latest: v0.17.0+1.8.1)
      Adding linux-raw-sys v0.3.8 (latest: v0.6.4)
      Adding os_str_bytes v6.6.1 (latest: v7.0.0)
      Adding rustix v0.37.27 (latest: v0.38.34)
      Adding strsim v0.10.0 (latest: v0.11.1)
      Adding terminal_size v0.2.6 (latest: v0.3.0)
      Adding toml v0.5.11 (latest: v0.8.19)
      Adding windows-sys v0.48.0 (latest: v0.59.0)
      Adding windows-sys v0.52.0 (latest: v0.59.0)
      Adding windows-targets v0.48.5 (latest: v0.52.6)
      Adding windows_aarch64_gnullvm v0.48.5 (latest: v0.52.6)
      Adding windows_aarch64_msvc v0.48.5 (latest: v0.52.6)
      Adding windows_i686_gnu v0.48.5 (latest: v0.52.6)
      Adding windows_i686_msvc v0.48.5 (latest: v0.52.6)
      Adding windows_x86_64_gnu v0.48.5 (latest: v0.52.6)
      Adding windows_x86_64_gnullvm v0.48.5 (latest: v0.52.6)
      Adding windows_x86_64_msvc v0.48.5 (latest: v0.52.6)
      Adding winreg v0.10.1 (latest: v0.52.0)
   Compiling libc v0.2.155
   Compiling pkg-config v0.3.30
   Compiling vcpkg v0.2.15
   Compiling serde v1.0.204
   Compiling semver v1.0.23
   Compiling io-lifetimes v1.0.11
   Compiling rustix v0.37.27
   Compiling tinyvec_macros v0.1.1
   Compiling proc-macro2 v1.0.86
   Compiling tinyvec v1.8.0
   Compiling unicode-ident v1.0.12
   Compiling bitflags v1.3.2
   Compiling linux-raw-sys v0.3.8
   Compiling autocfg v1.3.0
   Compiling indexmap v1.9.3
   Compiling percent-encoding v2.3.1
   Compiling unicode-bidi v0.3.15
   Compiling memchr v2.7.4
   Compiling quote v1.0.36
   Compiling unicode-normalization v0.1.23
   Compiling form_urlencoded v1.2.1
   Compiling jobserver v0.1.32
   Compiling aho-corasick v1.1.3
   Compiling cc v1.1.7
   Compiling idna v0.5.0
thread 'rustc' panicked at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/compiler/rustc_mir_dataflow/src/impls/initialized.rs:694:45:
index out of bounds: the len is 129 but the index is 32852
stack backtrace:
   0:     0x7f4922a24f05 - std::backtrace_rs::backtrace::libunwind::trace::h58eed11393533053
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f4922a24f05 - std::backtrace_rs::backtrace::trace_unsynchronized::h6af9bae28ebb6388
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4922a24f05 - std::sys_common::backtrace::_print_fmt::hb6748916642a4fb2
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f4922a24f05 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3692694645b1bb6a
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4922a75c4b - core::fmt::rt::Argument::fmt::h7aa93977ba74ae0f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/fmt/rt.rs:165:63
   5:     0x7f4922a75c4b - core::fmt::write::h5131d80b4c69b88d
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/fmt/mod.rs:1168:21
   6:     0x7f4922a19bdf - std::io::Write::write_fmt::h1fb327a7d8b0eb36
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/io/mod.rs:1835:15
   7:     0x7f4922a24cde - std::sys_common::backtrace::_print::he6ebb7b9d89f4456
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f4922a24cde - std::sys_common::backtrace::print::h998d75b840f75a73
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f4922a27719 - std::panicking::default_hook::{{closure}}::h18ec7fe6a38b9da0
  10:     0x7f4922a274ba - std::panicking::default_hook::hfb3f22c2e4075a6a
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:298:9
  11:     0x7f491f41e731 - std[dece285a2424a0b]::panicking::update_hook::<alloc[1cfb511ed242f20]::boxed::Box<rustc_driver_impl[aab422d80b3fe9fb]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f4922a27e4b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb8210adad49183e7
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2077:9
  13:     0x7f4922a27e4b - std::panicking::rust_panic_with_hook::h51af00bcb4660c4e
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:799:13
  14:     0x7f4922a27bc4 - std::panicking::begin_panic_handler::{{closure}}::h39f76aa863fbe8ce
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:664:13
  15:     0x7f4922a253c9 - std::sys_common::backtrace::__rust_end_short_backtrace::h4d10fc2251b89840
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys_common/backtrace.rs:171:18
  16:     0x7f4922a278f7 - rust_begin_unwind
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
  17:     0x7f4922a721e3 - core::panicking::panic_fmt::h319840fcbcd912ef
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:72:14
  18:     0x7f4922a723f7 - core::panicking::panic_bounds_check::ha28980b0cc493af1
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:274:5
  19:     0x7f49216eed35 - rustc_borrowck[3c8cb68a8f1455cf]::do_mir_borrowck
  20:     0x7f49216af33b - rustc_query_impl[e1fdd24b038f677d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e1fdd24b038f677d]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[806dc37a95cc1433]::query::erase::Erased<[u8; 8usize]>>
  21:     0x7f49209981ab - rustc_query_system[181e9214754b2580]::query::plumbing::try_execute_query::<rustc_query_impl[e1fdd24b038f677d]::DynamicConfig<rustc_query_system[181e9214754b2580]::query::caches::VecCache<rustc_span[6fd0e9f3c9cf86ed]::def_id::LocalDefId, rustc_middle[806dc37a95cc1433]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[e1fdd24b038f677d]::plumbing::QueryCtxt, false>
  22:     0x7f4920997d0d - rustc_query_impl[e1fdd24b038f677d]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  23:     0x7f492120a204 - rustc_interface[e93a829871290abb]::passes::analysis
  24:     0x7f4921209ae5 - rustc_query_impl[e1fdd24b038f677d]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e1fdd24b038f677d]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[806dc37a95cc1433]::query::erase::Erased<[u8; 1usize]>>
  25:     0x7f4921535d62 - rustc_query_system[181e9214754b2580]::query::plumbing::try_execute_query::<rustc_query_impl[e1fdd24b038f677d]::DynamicConfig<rustc_query_system[181e9214754b2580]::query::caches::SingleCache<rustc_middle[806dc37a95cc1433]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e1fdd24b038f677d]::plumbing::QueryCtxt, false>
  26:     0x7f4921535b0f - rustc_query_impl[e1fdd24b038f677d]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7f492142b7cd - rustc_interface[e93a829871290abb]::interface::run_compiler::<core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>, rustc_driver_impl[aab422d80b3fe9fb]::run_compiler::{closure#0}>::{closure#1}
  28:     0x7f492153cc69 - std[dece285a2424a0b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[e93a829871290abb]::util::run_in_thread_with_globals<rustc_interface[e93a829871290abb]::interface::run_compiler<core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>, rustc_driver_impl[aab422d80b3fe9fb]::run_compiler::{closure#0}>::{closure#1}, core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>>
  29:     0x7f492153ca6a - <<std[dece285a2424a0b]::thread::Builder>::spawn_unchecked_<rustc_interface[e93a829871290abb]::util::run_in_thread_with_globals<rustc_interface[e93a829871290abb]::interface::run_compiler<core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>, rustc_driver_impl[aab422d80b3fe9fb]::run_compiler::{closure#0}>::{closure#1}, core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[8d9e01cfbf9cd659]::result::Result<(), rustc_span[6fd0e9f3c9cf86ed]::ErrorGuaranteed>>::{closure#2} as core[8d9e01cfbf9cd659]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f4922a31e3b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3af90da315d4b185
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
  31:     0x7f4922a31e3b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e7f3b3405b4b88b
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/alloc/src/boxed.rs:2063:9
  32:     0x7f4922a31e3b - std::sys::pal::unix::thread::Thread::new::thread_start::h3b8e81128811868f
                               at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/sys/pal/unix/thread.rs:108:17
  33:     0x7f491c2a6507 - start_thread
  34:     0x7f491c32a40c - __GI___clone3
  35:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.80.0 (051478957 2024-07-21) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debug-assertions=off -C strip=debuginfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `command_helpers::<impl at /var/home/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cc-1.1.7/src/command_helpers.rs:101:1: 101:21>::forward_available`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `cc` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-update v13.4.0`, intermediate artifacts can be found at `/tmp/cargo-installG0DPCl`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

# System Details Report
---

## Report details
- **Date generated:**                              2024-08-04 12:27:02

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad X13 Yoga Gen 1
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-10610U × 8
- **Graphics:**                                    Intel® UHD Graphics
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            N2UET71W (1.51 )
- **OS Name:**                                     Fedora Linux 40.20240803.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.9.12-202.fsync.fc40.x86_64

**Comment by saethlin** [comment] 2024-08-04 17:48
Duplicate of https://github.com/rust-lang/rust/issues/128652

**Closed by saethlin** 2024-08-04 17:48 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
