### ISSUE TITLE
Command::new() doesn't expand %dp0 correctly in nightly

### ISSUE THREAD

**Issue by vvanders** [rust-lang/rust#43273] opened 2017-07-16 22:00 UTC
Currently the GCC crate fails to build with emscripten on nightly due to issues running the emcc.bat in emscripten:

```
@echo off
python "%~dp0\emcc" %*
```

Logging %~dp0 in nightly shows it pointing to the current directory of the crate while in stable it points to the path of the batch file(Ex: C:\Program Files\Emscripten\emscripten\incoming).

Tested between 

nightly-x86_64-pc-windows-msvc unchanged - rustc 1.20.0-nightly (086eaa78e 2017-07-15)

and

 stable-x86_64-pc-windows-msvc unchanged - rustc 1.18.0 (03fc9d622 2017-06-06)

**Comment by vvanders** [comment] 2017-07-16 22:16
From looking at https://github.com/rust-lang/rust/blob/beta/src/libstd/sys/windows/process.rs it doesn't seem like there's any difference between stable and nightly so not sure exactly where this is getting introduced.

Happy to dig into it more with some pointers if anyone has an idea where this could be coming from.

**Comment by vvanders** [comment] 2017-07-16 22:20
Also, modifying GCC crate with the fill path ahead of the command("emcc.bat" vs "C:\Program Files\Emscripten\emscripten\incoming\emcc.bat") gets the bat file to find the correct path for %~dp0. Obviously this isn't a good long-term fix but might be why the behavior here has changed.

**Comment by ollie27** [comment] 2017-07-17 03:36
dupe of #42791

**Comment by Mark-Simulacrum** [comment] 2017-07-19 16:06
Closing as duplicate of #42791.

**Closed by Mark-Simulacrum** 2017-07-19 16:06 UTC

**Comment by kuviman** [comment] 2017-09-06 13:50
Hello,
So I guess this is the reason I cannot build targeting asmjs-unknown-emscripten on stable now on Windows.

I also had to fix some of my build scripts but I am not sure if I can fix this:
```
   Compiling my_project v0.1.0 (file:///P:/my_project)
error: linking with `emcc.bat` failed: exit code: 2
  |
  = note: "emcc.bat" "-s" ...
  = note: python: can't open file 'P:\my_project\\emcc': [Errno 2] No such file or directory
          

error: aborting due to previous error

error: Could not compile `my_project`.

To learn more, run the command again with --verbose.
```
