### ISSUE TITLE
Can't compile core for msp430 - AtomicPtr

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#45834] opened 2017-11-07 16:18 UTC
### STR

``` console
$ rustup default nightly

$ rustup component add rust-src

$ cp -r $(rustc --print sysroot)/lib/rustlib/src/rust/src .

$ cd src/libcore

$ cargo build --target msp430-none-elf
   Compiling core v0.0.0 (file:///home/japaric/tmp/src/libcore)
error[E0412]: cannot find type `AtomicPtr` in this scope
   --> sync/atomic.rs:931:26
    |
931 | impl<T> From<*mut T> for AtomicPtr<T> {
    |                          ^^^^^^^^^ not found in this scope

error: aborting due to previous error

error: Could not compile `core`.
```

### Metadata

``` console
$ rustc -V
rustc 1.23.0-nightly (bd0e45a32 2017-11-06)
```

**Comment by kennytm** [comment] 2017-11-07 16:27
Duplicate of #45802.

**Closed by kennytm** 2017-11-07 16:27 UTC
