### ISSUE TITLE
Calling ".join().unwrap()" on a JoinHandle does not work

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#22707] opened 2015-02-23 10:26 UTC
I would expect the following code to compile:

```{rust}
use std::thread;
pub fn spawn_and_wait_nothing() {
    std::thread::spawn(||{ let i = 3*4; }).join().unwrap();
}
```

However, compilation fails, complaining about ```unwrap``` not being found. As ```.ok().unwrap()``` works, the problem is probably that no implementation for Debug could be found. (#19950 tracks the unhelpful error message.)

**Comment by alexcrichton** [comment] 2015-02-23 18:03
Dupe of https://github.com/rust-lang/rust/issues/21291, but thanks!

**Closed by alexcrichton** 2015-02-23 18:03 UTC
Labels: A-libs
