### ISSUE TITLE
Shall we add a `for` for `macro_rules`?

### ISSUE THREAD

**Issue by abbychau** [rust-lang/rust#57986] opened 2019-01-30 07:52 UTC
By now, we have `macro_rules` act like functions.
```rust
    macro_rules! k {
        ($t:expr) => {
            $t.to_string()
        };
    }

let a = k!("test");
```

However, if it can act like a trait then it will be more convenient for coding in many cases like `"test".k!().do_sth();`.;

Shall we have a `macro_rules` that takes in a `for`?
that:
```rust
macro_rules! l for T {
        ($self:expr) => {
            $self.to_string()
        };
}
```

**Comment by petrochenkov** [comment] 2019-01-30 08:41
This is a duplicate of this RFC issue - https://github.com/rust-lang/rfcs/pull/2442.

**Closed by petrochenkov** 2019-01-30 08:41 UTC
