### ISSUE TITLE
Many links in google for old docs

### ISSUE THREAD

**Issue by ahupp** [rust-lang/rust#56700] opened 2018-12-11 01:04 UTC
Many rust-related search terms in google return documentation that's out-of-date.  The docs do make clear that they are old, but don't link to the newest version.   Some examples:

"rust rc" returns this as the 3rd link:

https://doc.rust-lang.org/book/second-edition/ch15-04-rc.html

"rust types of closure" returns this as the first link:

https://doc.rust-lang.org/book/first-edition/closures.html

IMO, the best option is to remove these from the index entirely; if anyone really wants docs for old versions of the language they can probably find them manually.  

To do this, I believe you can either put:

    <meta name="robots" content="noindex" /> 

per https://support.google.com/webmasters/answer/93710?hl=en, or hide them with robots.txt.

**Comment by steveklabnik** [comment] 2018-12-11 02:48
I believe this is a psuedo-duplicate of a bunch of other issues.

**Comment by spacejam** [comment] 2018-12-13 11:02
I hit this a few times per week, and just did an issue search to see what the conversation was like around this. 

This has been an issue since before 1.0 (especially before 1.0 since things changed far more drastically and frequently back then) and some work has been done to address it over time:
https://github.com/rust-lang/rust/issues/12466 

At the time, the fixes addressed the biggest blocker issues but fell short of adding canonicalization, which I believe is the main way to address this that has been brought up, but not implemented to my knowledge. 

A concrete proposal that hasn't received much attention, but I think may be worth considering:
https://github.com/rust-lang/rust/issues/9461#issuecomment-369661516

**Comment by kornelski** [comment] 2019-01-28 17:20
Related/dupe: https://github.com/rust-lang/rust/issues/44894

**Comment by ahupp** [comment] 2019-01-28 17:31
The bulk of the issues I run into are due to links to https://doc.rust-lang.org/book/second-edition.  There's a lot of other issues around canonical urls and such, I think we'd get 50% of the value by just putting "<meta name="robots" content="noindex">" in each page of second-edition, so that the up-to-date version of the book will be the top link.

It doesn't look like that's something I could fix with a pull request.

**Comment by kornelski** [comment] 2020-03-14 02:24
This is still a problem, and it still hurts new users ([today's example](https://users.rust-lang.org/t/demo-of-a-viable-beginners-process-for-constructing-a-simple-functional-program/39448/10?u=kornel))

**Comment by kornelski** [comment] 2020-04-20 09:08
Still in progress #68677

**Comment by Dylan-DPC** [comment] 2024-09-01 18:45
Closing this as it's a closely related to of #44894 and that issue can track both

**Closed by Dylan-DPC** 2024-09-01 18:45 UTC
Labels: P-low, A-docs, T-infra
