### ISSUE TITLE
Use correct generic names when printing error messages

### ISSUE THREAD

**Issue by zrneely** [rust-lang/rust#29315] opened 2015-10-26 02:35 UTC
I'm sure the title is far too generic (no pun intended), but I'm not sure what else to call it.

Here's an example of the issue: http://is.gd/SpT2Db

It would be nice for new Rust users if we could see, in the error message, the name of the generic whose type could not be inferred, either like this:

    error: unable to infer enough type information about `A`; type annotations or generic parameter binding required [E0282]

or like this:

     Foo::<A>::baz();

or even this:

    Foo::<_>::baz();

I think any of these would be useful for a new Rust user - as it is, it's easy to get frustrated - "Where's my use of _? There's nothing to fix!"

**Comment by nagisa** [comment] 2016-01-19 19:08
Duplicate of #25633

**Closed by nagisa** 2016-01-19 19:08 UTC
Labels: A-diagnostics
