### ISSUE TITLE
call to print!() only executes at the end of the program

### ISSUE THREAD

**Issue by ab-hamza** [rust-lang/rust#78891] opened 2020-11-09 06:35 UTC
`cat /etc/os-release`:
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.1
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-musl
release: 1.47.0
LLVM version: 11.0
```

I tried this code:

```rust
use std::io;

fn main() {
    let mut user_input = String::new();
    print!("Enter input: ");
    io::stdin()
        .read_line(&mut user_input)
        .expect("failed to read line");
    println!("Your input: {}", user_input);
}
```

I expected the program to first print a string to stdout, read a string from stdin, then print again to stdout.

Instead, this happened:
The program reads from stdin first, then prints the two messages.

I noticed this only happens when using `print!`.
With `println!` the order is respected.

**Comment by hyd-dev** [comment] 2020-11-09 07:07
I think this is #23818?

**Comment by jonas-schievink** [comment] 2020-11-09 11:41
Yeah, closing as a duplicate of that

**Closed by jonas-schievink** 2020-11-09 11:41 UTC
