### ISSUE TITLE
SIGFPE when compiling with opt-level 2

### ISSUE THREAD

**Issue by meiamsome** [rust-lang/rust#37471] opened 2016-10-29 21:19 UTC
Hello,

I have written a [prime sieve in Rust](https://gist.github.com/meiamsome/2d59da4f65da016e07cdcfb3cc743aba), and tried to run it in release mode, but got a SIGFPE upon execution. I am compiling with `rustc -o target/release/rust_testing -g -C opt-level=2 src/main.rs`. I have added signal catching to be able to print a backtrace of the problem which is included here:  [backtrace.txt](https://github.com/rust-lang/rust/files/560161/backtrace.txt). 

I tried to look at the library source, but the error appears to be when adding one, which confuses me greatly.

My `rustc -V` is here:
`rustc 1.12.1 (d4f39402a 2016-10-19)`

I am currently running Ubuntu 16.10 on kernel `4.8.0-26-generic`

**Comment by meiamsome** [comment] 2016-10-29 22:35
Hello Again,

I appear to have found the source of the issue. The compiler appears to think it is a prime oracle. At compile time it already knows all possible primes and so optimises out line 27. For whatever reason, it decides zero is a prime and so plugs it into line 28, where there is promptly a divide by zero.

In order to prove this, I have added a unoptimised condition to the if (Flushing stdout) and this resolves the issue: `if self.data[num] && stdout().flush().is_ok()`

**Comment by alexcrichton** [comment] 2016-10-30 10:29
This looks like either an LLVM optimization bug or a bug in what we tell LLVM. Unfortunately the smallest I could get this was:

```rust
struct Sieve {
    limit: Option<usize>,
    data: Vec<bool>,
    current: usize,
}

impl Sieve {
    fn new() -> Sieve {
        Sieve {
            limit: None,
            data: vec![false, false],
            current: 0,
        }
    }
    fn clear(&mut self, num: usize) {
        if self.data[num] {
            for j in 2 .. self.data.len() / num {
                if num * j < self.data.len() {
                    self.data[num * j] = false
                }
            }
        }
    }
}

impl Iterator for Sieve {
    type Item = usize;
    fn next(&mut self) -> Option<usize> {
        while self.limit.map_or(true, |_| loop {}) {
            self.current += 1;
            self.data.push(true);
            for i in 0 .. self.current {
                self.clear(i);
            }
        }
        None
    }
}

fn main() {
    Sieve::new().next();
}
```

cc @rust-lang/compiler, seems worrisome?

**Comment by arielb1** [comment] 2016-10-30 17:31
duplicate of #28728

**Closed by arielb1** 2016-10-30 17:31 UTC
Labels: I-nominated, T-compiler

**Comment by Stebalien** [comment] 2016-10-30 23:49
@arielb1 The minimized version may be but I can't find any infinite loops in the original. Unlike the minimized version, the original one terminates when compiled without optimizations.

**Comment by alexcrichton** [comment] 2016-10-31 02:02
Hm I'm inclined to agree, @arielb1 do you think this is still a dupe of the infinite loop bug in that case? This didn't look like any existing known "this is a weird LLVM thing" issue I've seen before.
