### ISSUE TITLE
Packed&aligned structs?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#73988] opened 2020-07-03 11:08 UTC
Here they explain the need for repr(C) structs that are both aligned and packed:
https://immunant.com/blog/2020/06/kernel_modules/

Their solution:
```rust
#[repr(C, align(64))]
pub struct xregs_state(pub xregs_state_Inner);
#[repr(C, packed)]
pub struct xregs_state_Inner {
  // ...
}
```

Perhaps it's worth supporting this directly.

**Comment by RalfJung** [comment] 2023-12-12 20:46
Closing as duplicate of https://github.com/rust-lang/rust/issues/59154

**Closed by RalfJung** 2023-12-12 20:46 UTC
Labels: C-feature-request, A-layout
