### ISSUE TITLE
Type inference fails if less specific call appears before more specific call

### ISSUE THREAD

**Issue by illicitonion** [rust-lang/rust#57009] opened 2018-12-20 14:56 UTC
In this code:
```rust
fn main() {
    let v = vec![""].into_iter().collect();
    println!("{}", v.len());
    consume_vec(&v);
}

fn consume_vec<T>(_v: &Vec<T>) {}
```

`v` _must_ be a `Vec`, because it's passed to `consume_vec`. This is properly inferred if there is no call to `.len()` before the call to `consume_vec`, or if the call to `.len()` happens after the call to `consume_vec`.

The call to `.len()` doesn't refute `v` being a `Vec`, because `Vec` has a `len` method, so I would expect this code to work without additional type ascriptions.

**Comment by jonas-schievink** [comment] 2018-12-20 15:12
Duplicate of https://github.com/rust-lang/rust/issues/56952

**Comment by Enselic** [comment] 2023-11-18 21:19
Triage: Closing as duplicate of https://github.com/rust-lang/rust/issues/56952.

**Closed by Enselic** 2023-11-18 21:19 UTC
Labels: A-inference
