### ISSUE TITLE
unsafe_op_in_unsafe_fn suggestion overlaps when used in a macro

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#123304] opened 2024-03-31 22:41 UTC
The following example triggers the `unsafe_op_in_unsafe_fn` lint twice in the same position:

```rust
#![warn(unsafe_op_in_unsafe_fn)]

macro_rules! foo {
    ($x:ident) => {
        pub unsafe fn $x() {
            let _ = String::new().as_mut_vec();
        }
    };
}

foo!(a);
foo!(b);
```

This causes `cargo fix` to apply both suggestions which ends up with:

```rust
// ...snip
pub unsafe fn $x() { unsafe { unsafe {
    let _ = String::new().as_mut_vec();
}}}
// ...snip
```

which triggers the `unused_unsafe` lint.

Would it be possible to avoid duplicate suggestions when used in a macro?
cc @asquared31415

I suspect this may be encountered frequently with the 2024 edition migration (crater run is pending in #122960). Although it isn't too much of a problem to repair, a frequently used macro could have many unsafe blocks, which could be confusing.

```
rustc 1.79.0-nightly (8df7e723e 2024-03-30)
binary: rustc
commit-hash: 8df7e723ea729a7f917501cc2d91d640b7021373
commit-date: 2024-03-30
host: aarch64-apple-darwin
release: 1.79.0-nightly
LLVM version: 18.1.2
```

**Comment by ehuss** [comment] 2024-03-31 22:53
Another option I am considering is to have rustfix ignore a top-level diagnostic if all of its suggestions are identical to another top-level diagnostic. That might take a bit of reworking of how rustfix collects suggestions, though. I'm also trying to think of what problems that might introduce, though I think it should be safe.

**Comment by weihanglo** [comment] 2024-04-09 21:14
Just looked into the given reproduction. It seems that the duplications happens between different diagnostic messages. I am not sure if such a fix should be in rustfix. Rustfix only deal with one diagnostic at a time. Perhaps we need to get it done at a higher level like [here in Cargo](https://github.com/rust-lang/cargo/blob/bd1cf584af2c356eeb3980c3c9bb0fea190ed633/src/cargo/ops/fix.rs#L736-L746)? Alternatively, we can have `rustfix::CodeFix` aware of duplications and skip applying those. Do you have any preference?

**Comment by weihanglo** [comment] 2024-04-09 21:21
Is there any situation that we'll get identical machine applicable suggestions, and they are all necessary not duplicated?

**Comment by ehuss** [comment] 2024-04-10 04:01
> Is there any situation that we'll get identical machine applicable suggestions, and they are all necessary not duplicated?

I brought this up in https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/overlapping.20suggestions, and I and others couldn't think of any concerns with that.

**Comment by ehuss** [comment] 2024-04-10 04:03
> Rustfix only deal with one diagnostic at a time. Perhaps we need to get it done at a higher level like [here in Cargo](https://github.com/rust-lang/cargo/blob/bd1cf584af2c356eeb3980c3c9bb0fea190ed633/src/cargo/ops/fix.rs#L736-L746)? Alternatively, we can have `rustfix::CodeFix` aware of duplications and skip applying those. Do you have any preference?

It looks like in https://github.com/rust-lang/cargo/pull/13728 that you maybe figured this out? The `rustfix` library handles collecting multiple diagnostics all at once, and that is where it should be able to filter things.

**Comment by weihanglo** [comment] 2024-04-10 04:38
> The rustfix library handles collecting multiple diagnostics all at once

I didn't fully get it. Did you mean [`get_suggestions_from_json`](https://docs.rs/rustfix/latest/rustfix/fn.get_suggestions_from_json.html#)? Cargo doesn't use that API and instead calls [`collect_suggestions`](https://docs.rs/rustfix/latest/rustfix/fn.collect_suggestions.html), which collects from one top-level diagnostics at a time.

https://github.com/rust-lang/cargo/pull/13728 addresses it on Cargo side, not inside `rustfix` crate. I feel it more nature for rustfix being as dumb as possible, and let Cargo handle business logic. Let me know if you have other thought :)

**Comment by weihanglo** [comment] 2024-04-10 17:52
<https://github.com/rust-lang/cargo/pull/13728> has been merged. `rustfix@0.8.3` should contain a similar fix when it gets released.

**Comment by tmandry** [comment] 2024-04-17 18:07
@asquared31415 is this something you can pick up?

**Comment by tmandry** [comment] 2024-04-17 21:39
Sorry, I just caught up on the discussion here. It looks like this can be closed then, now that https://github.com/rust-lang/cargo/pull/13728 is merged?

**Comment by tmandry** [comment] 2024-05-01 00:31
I've verified that the reported issue no longer occurs, and the migration behaves correctly with `cargo fix`.

**Closed by tmandry** 2024-05-01 00:31 UTC
Labels: T-compiler, C-bug, D-invalid-suggestion, A-edition-2024
