### ISSUE TITLE
It seems rustc failed to compile a sound code?

### ISSUE THREAD

**Issue by zylthinking** [rust-lang/rust#88738] opened 2021-09-08 09:19 UTC
Hello, I have the following code, which fails to compile directly.
showing
```
33  |     let h1 = tokio::spawn(f1);
    |              ^^^^^^^^^^^^ `std::sync::MutexGuard<'_, Box<ListHead>>` cannot be sent between threads safely
    | 
   ::: /home/zylthinking/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:61:43
    |
61  | pub const fn from_generator<T>(gen: T) -> impl Future<Output = T::Return>
    |                                           ------------------------------- within this `impl Future`
    | 
   ::: /home/zylthinking/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.11.0/src/task/spawn.rs:127:21
    |
127 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::spawn`
    |
    = help: within `impl Future`, the trait `Send` is not implemented for `std::sync::MutexGuard<'_, Box<ListHead>>`
    = note: required because it appears within the type `for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r Autex, Result<i32, i32>, autex::autex<'s>, std::sync::MutexGuard<'t0, Box<ListHead>>, &'t1 mut autex::autex<'t2>, ()}`
    = note: required because it appears within the type `[static generator@Autex::lock::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r Autex, Result<i32, i32>, autex::autex<'s>, std::sync::MutexGuard<'t0, Box<ListHead>>, &'t1 mut autex::autex<'t2>, ()}]`
    = note: required because it appears within the type `from_generator::GenFuture<[static generator@Autex::lock::{closure#0} for<'r, 's, 't0, 't1, 't2> {ResumeTy, &'r Autex, Result<i32, i32>, autex::autex<'s>, std::sync::MutexGuard<'t0, Box<ListHead>>, &'t1 mut autex::autex<'t2>, ()}]>`
    = note: required because it appears within the type `impl Future`
    = note: required because it appears within the type `impl Future`
    = note: required because it appears within the type `for<'r, 's, 't0> {ResumeTy, &'r Autex, Autex, impl Future, (), Guard<'t0>, u64, Duration, Sleep}`
    = note: required because it appears within the type `[static generator@tests/tokio.rs:8:20: 17:6 for<'r, 's, 't0> {ResumeTy, &'r Autex, Autex, impl Future, (), Guard<'t0>, u64, Duration, Sleep}]`
    = note: required because it appears within the type `from_generator::GenFuture<[static generator@tests/tokio.rs:8:20: 17:6 for<'r, 's, 't0> {ResumeTy, &'r Autex, Autex, impl Future, (), Guard<'t0>, u64, Duration, Sleep}]>`
    = note: required because it appears within the type `impl Future`
```

Noticed there is a MutexGuard as a generated parameter, I put it into another fn a(), and  it compiles.
Is it a compiler bug?

```rust
    fn a(&self, autx: &mut autex) {
        let mut g0 = self.mux.lock().unwrap();
        unsafe {
            g0.list_add_tail(&mut autx.ent);
        }
        drop(g0);
    }

    pub async fn lock<'a>(&'a self) -> Guard<'a> {
        let r = self
            .hold
            .atomic_compare_exchange(0, 1, Ordering::Relaxed, Ordering::Relaxed);
        if r.is_ok() {
            return Guard(self);
        }

        let mut autx = autex::new(self);

       // this line will compiles
        self.a(&mut autx);

        // but the following is not
        // let mut g0 = self.mux.lock().unwrap();
        // unsafe {
        //     g0.list_add_tail(&mut autx.ent);
        // }
        // drop(g0);

        let g1 = (&mut autx).await;
        let g2 = self.mux.lock().unwrap();
        unsafe {
            autx.ent.list_del();
        }
        drop(g2);
        g1
    }
```

the compiler is rustc 1.53

**Comment by CryZe** [comment] 2021-09-08 10:49
This is because you have a MutexGuard, which can't be sent to another thread, as a local variable as part of an async function, which generally tries to store all local variables as part of its state. Technically you dropped it early, before ever reaching any await, so it doesn't actually need to store the MutexGuard as part of the async state, but it seems like Rust doesn't seem to understand / optimize this yet. (Maybe instead wrapping it in a { ... } block helps?)

**Comment by jonas-schievink** [comment] 2021-09-08 12:46
Duplicate of https://github.com/rust-lang/rust/issues/57478

**Closed by jonas-schievink** 2021-09-08 12:46 UTC
Labels: C-bug
