### ISSUE TITLE
Regression in type inference from Iterator.sum

### ISSUE THREAD

**Issue by untitaker** [rust-lang/rust#25094] opened 2015-05-04 10:38 UTC
The following used to work (around the time where `AdditiveIterator` still existed):

```
fn main() {
    let content = vec!["a","aa","aaa","aaaa"];
    let lens = content.iter().map(|x| x.len());
    println!("{}", lens.sum());
}
```

http://is.gd/2jQlp7

The error message:

```
<anon>:4:25: 4:30 error: unable to infer enough type information about `_`; type annotations required [E0282]
<anon>:4     println!("{}", lens.sum());
                                 ^~~~~
```

**Comment by mitaa** [comment] 2015-06-08 18:40
`Iterator::sum` and `Iterator::product` use defaulted type parameters, which, I think, are not yet implemented for functions. (RFC 0213 https://github.com/rust-lang/rust/issues/21939)

**Comment by mitaa** [comment] 2015-07-29 04:36
Testing with the shiny new [Default Type Parameter Fallback](#26870):
```rust
#![feature(default_type_parameter_fallback)]
#![feature(iter_arith)]

fn main() {
    let a = [1, 2, 3, 4, 5];
    let it = a.iter();
    assert_eq!(it.sum(), 15);
}
```

```
test_defty.rs:7:19: 7:24 error: the trait `core::ops::Add<&i32>` is not implemented for the type `<core::slice::Iter<'_, i32> as core::iter::Iterator>::Item` [E0277]
test_defty.rs:7     assert_eq!(it.sum(), 15);
```

**Comment by untitaker** [comment] 2016-08-24 21:45
@mitaa It appears that your example currently fails with the same exact message as OP: https://is.gd/eA5RJ0

**Comment by Mark-Simulacrum** [comment] 2017-05-12 23:13
Nominating for compiler team discussion since this is a regression that slipped through a while back.

**Comment by Mark-Simulacrum** [comment] 2017-05-12 23:15
Copying over #36201 to close that:

``` rust
fn total1(a: &[u32]) -> u32 { // OK
    a.iter().sum()
}

fn total3(a: &[u32]) -> u32 { // Error
    a.iter().sum() + 5u32
}
```

``` rust
fn f() -> f64 { // Ok
   0.0f64 +  vec![1.0f64].into_iter().sum::<f64>()
}

fn f2() -> f64 { // Error
   0.0f64 +  vec![1.0f64].into_iter().sum()
}
```

**Comment by nikomatsakis** [comment] 2017-05-25 17:37
I believe this changed when `sum()` was stabilized -- it was rewritten to be generic over the sum type, which implies that it must be specified and cannot be inferred from context. Therefore, I think this is "not a bug" (nor, technically, a regression). I could be wrong though, maybe some details of our type inference changed -- if so, they seem likely to be bug fixes, though, since I think we are (correctly) refusing to guess types here.

**Comment by nikomatsakis** [comment] 2017-05-25 17:37
I'm inclined to close myself.

**Comment by StefanoD** [comment] 2017-05-25 17:41
@nikomatsakis 
This is a good example, that you don't have to "guess" types:
```rust
fn total3(a: &[u32]) -> u32 { // Error
    a.iter().sum() + 5u32
}
```
Everything is u32. So why doesn't this work?

**Comment by jimblandy** [comment] 2017-05-25 17:52
I'm having a hard time understanding why it's inappropriate to infer `usize` here:
```
fn main() {
    let v: Vec<usize> = vec![1,2,3,4];
    assert_eq!(v.iter().sum(), 10_usize);
}
```

Rust says:
```
rustc 1.19.0-nightly (5b13bff52 2017-05-23)
error[E0282]: type annotations needed
 --> <anon>:3:25
  |
3 |     assert_eq!(v.iter().sum(), 10_usize);
  |                         ^^^ cannot infer type for `S`

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment] 2017-05-25 17:58
@StefanoD 

> Everything is u32. So why doesn't this work?

Because other things are addable to `u32` besides `u32`. For example, there is an impl of `Add<&u32> for u32` (and vice versa).

**Comment by nikomatsakis** [comment] 2017-05-25 18:00
@jimblandy 

> I'm having a hard time understanding why it's inappropriate to infer usize here:

Similarly, there are many `PartialEq` impls. Basically, sum results in a variable `V`, and we have to infer `V: PartialEq<usize>`. **At the moment**, we *always* refuse to guess the "self" type, so we just stop there. For other type parameters, if `Self` is known, we will sometimes infer them based on `Self`. I am not happy with these rules, but there are many things at play -- if anything, I'd like to infer *less* in many cases, because it leads to regressions when new impls are added. (Also, none of this is specific to `sum()`.)

**Comment by nikomatsakis** [comment] 2017-05-25 20:40
Closing since this is behaving as expected, for better or worse. =)

**Closed by nikomatsakis** 2017-05-25 20:40 UTC
Labels: A-typesystem, I-nominated, T-compiler

**Comment by nikomatsakis** [comment] 2017-05-25 20:46
Oh, just some additional notes: the problem that @jimblandy highlighted is basically a dup of #20297 (so in some sense you could consider this issue a dup of that issue). You can see the effect of `Self` in that if you reverse the order of the `assert_eq!` arguments, [things work again](https://is.gd/quojB6):

```rust
fn main() {
    let v: Vec<usize> = vec![1,2,3,4];
    assert_eq!(10_usize, v.iter().sum());
}
```

**Comment by tshepang** [comment] 2017-07-23 10:29
@nikomatsakis it's weird that if you swap the arguments, inference works again. Is that ok?

**Comment by dimo414** [comment] 2019-08-01 04:58
Stumbled upon this bug via #36201; I appreciate (now) why "*the sum type ... must be specified and cannot be inferred from context*", but the error message seems like it could still be more helpful. In particular, could it suggest a likely annotation, e.g. "Did you mean `.sum::<u32>()`?"

FWIW in 1.36.0 the error message from the `total3()` example above is now:

    error[E0283]: type annotations required: cannot resolve `_: std::iter::Sum<&u32>`
