### ISSUE TITLE
Impls for associated types misidentified as conflicting

### ISSUE THREAD

**Issue by djkoloski** [rust-lang/rust#100028] opened 2022-08-01 17:27 UTC
This issue came up when a downstream user attempted to implement an [rkyv trait](https://docs.rs/rkyv/0.7.39/rkyv/rel_ptr/trait.Offset.html) for their own types. It appears that using an associated type as the target of an impl is not treated as a conflicting impl in the defining crate, but is treated as a conflicting impl in any downstream crates.

I tried this code:

```rust
// upstream/mod.rs

pub trait Associate {
    type Associated;
}

impl Associate for () {
    type Associated = ();
}

pub trait Upstream {}

impl Upstream for <() as Associate>::Associated {}

// downstream/mod.rs

use upstream::Upstream;

pub struct MyType;

impl Upstream for MyType {}
```

I expected to see this happen: the code compiles.

Instead, this happened:

```
error[E0119]: conflicting implementations of trait `upstream::Upstream` for type `MyType`
 --> downstream/src/lib.rs:5:1
  |
5 | impl Upstream for MyType {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `upstream`:
          - impl Upstream for <() as Associate>::Associated;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.62.1 (e092d0b6b 2022-07-16)
binary: rustc
commit-hash: e092d0b6b43f2de967af0887873151bb1c0b18d3
commit-date: 2022-07-16
host: x86_64-apple-darwin
release: 1.62.1
LLVM version: 14.0.5
```

Credit to @Kixiron for discovering this issue.

**Comment by veber-alex** [comment] 2022-08-01 19:30
I believe this is a duplicate of #99940

**Comment by lcnr** [comment] 2022-08-01 19:42
yes, this is a duplicate of #99940, closing.

still thinks for opening this PR :sweat_smile: how can a bug existing since at least version 1.30 (which is the oldest one i have locally) get discovered twice in the span of 3 days.

i can't remember ever seeing this bug before #99940 :sweat_smile:

**Closed by lcnr** 2022-08-01 19:42 UTC
Labels: C-bug
