### ISSUE TITLE
Compiler Error on numeric type inference

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#25917] opened 2015-05-31 02:57 UTC
When compiling a section of code that works similar to this

    trait something
    {
        fn do_the_thing(&self) -> Magic
    }

    impl something for i64

    impl something for f64

    fn do_something< T :something > ( x :T) 

    fn main()
    {
         do_something( 0 ); //compiler errors out
    }

The compiler throws a huge hissy. It basically told me to come here and report this. Version is 1.0.0 (a59de37e9 2015-05-13)

**Comment by valarauca** [comment] 2015-05-31 02:58
Issue disappears if 0 is cast to a type. Issue I'm assuming is with type inference. Likely change the error message?

**Comment by huonw** [comment] 2015-05-31 03:11
The code you have posted doesn't compile due to syntax errors. I made some adjustments to make it be syntactically valid, but this [compiles and runs fine](https://play.rust-lang.org/?gist=e2535867ee9c190c72ce&version=stable&run=1). 
```rust
trait something
{
    fn do_the_thing(&self) {}
}

impl something for i64 {}

impl something for f64 {}

fn do_something< T :something > ( x :T)  {}

fn main()
{
     do_something( 0 ); //compiler errors out
}
```

It would be helpful if:
- you could include the compiler output, and
- you could post an example that demonstrates the exact problem (E.g. it should be possible to copy-paste the code into http://play.rust-lang.org and click Run to get the same error.)

**Comment by valarauca** [comment] 2015-05-31 03:17
Apologies for messy code. 

Line 34 and 35 outline where the error is created. Remove "as i64" error will appear. 

https://github.com/valarauca/Rust-Trait-Example/blob/4667f966d19c274993eab16fba5f3e3d7f724bc4/trait_example.rs

**Comment by steveklabnik** [comment] 2015-05-31 15:33
Yes, 0 is an i32, 0.0 is an i64

**Comment by eddyb** [comment] 2015-05-31 16:13
@steveklabnik did you mean `f64`?

@valarauca to expand on what @steveklabnik is saying here, `0` is an **integer** literal, which means it can be any of the `{i,u}{8,16,32,64,size}` types, but not `f32` and `f64`.
Conversely, `0.0` is a **floating-point** literal, so it can be `f32` or `f64`, but none of the integer types.

**Comment by steveklabnik** [comment] 2015-05-31 16:14
Yes, I did, sorry :(

**Comment by steveklabnik** [comment] 2015-06-08 22:12
As mentioned in this thread, this is not a bug, it's intended behavior. So I'm closing.

**Closed by steveklabnik** 2015-06-08 22:12 UTC
