### ISSUE TITLE
Support for both packed and aligned (in repr(C)

### ISSUE THREAD

**Issue by koverstreet** [rust-lang/rust#118018] opened 2023-11-17 21:09 UTC
bcachefs uses types that are both packed and aligned (to 4 or 8 bytes). We're looking to expand our use of Rust, and we need these types available via bindgen - they're our on disk format, so not easily changed.

Right now we're making this work via a bindgen patch that strips off aligned when packed is specified; however, this is incorrect and a lurking bug since specifying the alignment of at type can change the size - thus, Rust and C may end up disagreeing about the size and layout of these types.

Additionally, specifying aligned may give rustc additional useful information - in a packed, aligned(4) type, members up to 4 byte alignment may still be aligned correctly (depending on struct layout), whereas in a packed type rustc would not be able to assume that.

**Comment by RalfJung** [comment] 2023-12-12 20:46
Closing as duplicate of https://github.com/rust-lang/rust/issues/100743

**Closed by RalfJung** 2023-12-12 20:46 UTC
Labels: T-lang, T-compiler, C-feature-request, T-opsem
