### ISSUE TITLE
Encountered errors resolving bounds after type-checking

### ISSUE THREAD

**Issue by rocurley** [rust-lang/rust#44123] opened 2017-08-28 05:50 UTC
When trying to build a project with matrixmultiply as a dependency, I get a compiler panic.

On my machine (running Linux Mint 18.2) this is sufficient to reproduce it:
```
$ cargo new --bin debug
     Created binary (application) `debug` project
$ cd debug
$ echo 'matrixmultiply = "0.1.13"' >> Cargo.toml 
$ cargo build --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling matrixmultiply v0.1.13
   Compiling rawpointer v0.1.0
     Running `rustc --crate-name build_script_build /home/roger/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.1.13/build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=0ef7d613c0f98393 -C extra-filename=-0ef7d613c0f98393 --out-dir /home/roger/debug/target/debug/build/matrixmultiply-0ef7d613c0f98393 -L dependency=/home/roger/debug/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name rawpointer /home/roger/.cargo/registry/src/github.com-1ecc6299db9ec823/rawpointer-0.1.0/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=840b89b6576fe2a2 -C extra-filename=-840b89b6576fe2a2 --out-dir /home/roger/debug/target/debug/deps -L dependency=/home/roger/debug/target/debug/deps --cap-lints allow`
     Running `/home/roger/debug/target/debug/build/matrixmultiply-0ef7d613c0f98393/build-script-build`
     Running `rustc --crate-name matrixmultiply /home/roger/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.1.13/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=ce7f19c27c9cbf9b -C extra-filename=-ce7f19c27c9cbf9b --out-dir /home/roger/debug/target/debug/deps -L dependency=/home/roger/debug/target/debug/deps --extern rawpointer=/home/roger/debug/target/debug/deps/librawpointer-840b89b6576fe2a2.rlib --cap-lints allow`
error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<K as kernel::GemmKernel>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (c417ee9ae 2017-07-25) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `matrixmultiply`.

Caused by:
  process didn't exit successfully: `rustc --crate-name matrixmultiply /home/roger/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.1.13/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=ce7f19c27c9cbf9b -C extra-filename=-ce7f19c27c9cbf9b --out-dir /home/roger/debug/target/debug/deps -L dependency=/home/roger/debug/target/debug/deps --extern rawpointer=/home/roger/debug/target/debug/deps/librawpointer-840b89b6576fe2a2.rlib --cap-lints allow` (exit code: 101)
$ rustc --version
rustc 1.21.0-nightly (c417ee9ae 2017-07-25)

```

I expected to see this happen: The project builds.

Instead, this happened: The compiler panics.

Rerunning the command that causes the crash in verbose mode, with backtrace enabled, gives:
```
$ RUST_BACKTRACE=full rustc --verbose --crate-name matrixmultiply /home/roger/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.1.13/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=ce7f19c27c9cbf9b -C extra-filename=-ce7f19c27c9cbf9b --out-dir /home/roger/debug/target/debug/deps -L dependency=/home/roger/debug/target/debug/deps --extern rawpointer=/home/roger/debug/target/debug/deps/librawpointer-840b89b6576fe2a2.rlib --cap-lints allow
error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<K as kernel::GemmKernel>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (c417ee9ae 2017-07-25) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
stack backtrace:
   0:     0x7fd5bcea9da3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h13518b3df32d2a8c
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7fd5bcea4484 - std::sys_common::backtrace::_print::h1ce5d0972f329053
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x7fd5bceb7c23 - std::panicking::default_hook::{{closure}}::h905b6049ef9e7824
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:380
   3:     0x7fd5bceb7918 - std::panicking::default_hook::hb623160e38c63537
                               at /checkout/src/libstd/panicking.rs:390
   4:     0x7fd5bceb8127 - std::panicking::rust_panic_with_hook::h32de8766955e8783
                               at /checkout/src/libstd/panicking.rs:611
   5:     0x7fd5b9b7dee8 - std::panicking::begin_panic_new::h3dd551d4f3665035
   6:     0x7fd5b9b682f1 - rustc_errors::Handler::span_bug::h48440b8c3355f883
   7:     0x7fd5b9da54b3 - rustc::session::opt_span_bug_fmt::{{closure}}::h5656c0b1c7d6b866
   8:     0x7fd5b9da5392 - rustc::session::opt_span_bug_fmt::h60fcaea9a57382c4
   9:     0x7fd5b9da5263 - rustc::session::span_bug_fmt::hd72c22c82de57ccb
  10:     0x7fd5b9e5d8af - <&'gcx rustc::ty::TyS<'gcx> as rustc::infer::TransNormalize<'gcx>>::trans_normalize::h4c717a4d65093941
  11:     0x7fd5b9d1f1ed - rustc::infer::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'tcx>>::normalize_associated_type_in_env::hb763306edb36c222
  12:     0x7fd5b9dff831 - rustc::ty::layout::Layout::compute_uncached::h6644981ff2e31dc9
  13:     0x7fd5b9e2396a - rustc::ty::util::layout_raw::he39bdfba1f1dee36
  14:     0x7fd5b9ecac79 - rustc::ty::maps::<impl rustc::ty::maps::queries::layout_raw<'tcx>>::try_get::hb682938dbb66e84f
  15:     0x7fd5b9ed7a5f - rustc::ty::maps::TyCtxtAt::layout_raw::h32ec73a8f83d3a54
  16:     0x7fd5b9ed2b6d - rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::layout_raw::hf1cf0950cf5c774a
  17:     0x7fd5ba742784 - rustc_const_eval::eval::eval_const_expr_partial::{{closure}}::h5f3d98b97334b581
  18:     0x7fd5ba73c933 - rustc_const_eval::eval::eval_const_expr_partial::h7f4f8f837d53e6ae
  19:     0x7fd5ba73c5fb - rustc_const_eval::eval::eval_const_expr_partial::h7f4f8f837d53e6ae
  20:     0x7fd5ba73c5fb - rustc_const_eval::eval::eval_const_expr_partial::h7f4f8f837d53e6ae
  21:     0x7fd5ba73ff72 - rustc_const_eval::eval::eval_const_expr_partial::h7f4f8f837d53e6ae
  22:     0x7fd5ba73bca0 - rustc_const_eval::eval::ConstContext::eval::h585a306be0e38bee
  23:     0x7fd5bc5fe520 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h077728ee3d50e3eb
  24:     0x7fd5bc5fe3b5 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h077728ee3d50e3eb
  25:     0x7fd5bc5fe008 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h077728ee3d50e3eb
  26:     0x7fd5bc5fe3b5 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h077728ee3d50e3eb
  27:     0x7fd5bc5fe097 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h077728ee3d50e3eb
  28:     0x7fd5bc5fe1a7 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr::h077728ee3d50e3eb
  29:     0x7fd5bc5fce99 - <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body::h9dd08db119324822
  30:     0x7fd5bc5febbc - rustc_passes::consts::check_crate::h7de7b6147325a4e4
  31:     0x7fd5bd25b325 - rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}::h6ede77aa4352120d
  32:     0x7fd5bd24e9c3 - rustc_driver::driver::phase_3_run_analysis_passes::hdb0f289eb7bba9de
  33:     0x7fd5bd22fca0 - rustc_driver::driver::compile_input::hc1c922cfc1e6167b
  34:     0x7fd5bd275095 - rustc_driver::run_compiler::h2c0041c7d640cbf7
  35:     0x7fd5bd18e497 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4cebd4e9dc3a542c
  36:     0x7fd5bcee766c - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  37:     0x7fd5bd1c6030 - <F as alloc::boxed::FnBox<A>>::call_box::h2501f9190c680a0d
  38:     0x7fd5bceb6b1b - std::sys::imp::thread::Thread::new::thread_start::h711a568605f11f7c
                               at /checkout/src/liballoc/boxed.rs:661
                               at /checkout/src/libstd/sys_common/thread.rs:21
                               at /checkout/src/libstd/sys/unix/thread.rs:84
  39:     0x7fd5b804e6b9 - start_thread
  40:     0x7fd5bcb643dc - clone
  41:                0x0 - <unknown>
```

**Comment by arielb1** [comment] 2017-08-28 10:22
Looks like a duplicate of #43357.

You are using an old nightly compiler. Updating to the newest nightly should fix your problem.

**Closed by arielb1** 2017-08-28 10:22 UTC
