### ISSUE TITLE
Memory not freed on container of allocated objects on recent compilers

### ISSUE THREAD

**Issue by pinconquentin** [rust-lang/rust#58943] opened 2019-03-05 16:26 UTC
Hello,

Here is a sample code, simply filling a Vec by Vecs of integer.

```
fn test() {
	let mut vec = Vec::new();
	for x in 0..10000000 {
		vec.push(vec![1,2,3,4]);
	}
	println!("{}", vec.capacity() * vec[0].capacity());
}

fn main() {
	test();
	std::thread::sleep(std::time::Duration::from_millis(1000000));
}
```
With recent versions of rustc (> 1.31), the allocated memory seems to not be freed from the system at the end of the test function, as top displays a memory usage of ~300Mo, which is coherent with the memory used by this sample code.

With lower versions of rustc (I used 1.30 and 1.31), this problem does not appear (the process system memory is close to 0, as intended). 

However, using the system allocator, the behaviour is the same for all versions : the memory is not available from the system.
Calling twice the test function however does not increase the memory consumption, which probably means that the allocator effectively freed the memory internally, but not from the system.
The same thing happens if the vector is dropped manually by calling std::mem::drop().

I am writing a long running process that does a lot of allocations and deallocations at startup, and once initialization is finished I'm looking for a way to release temporary memory to the OS. Is there any low-level mechanism (such as `malloc_trim` in C) that asks/hints the allocator to do that ?

Any idea of why this happens ? Thank you !

**Comment by jonas-schievink** [comment] 2019-03-05 16:55
>  Calling twice the test function however does not increase the memory consumption, which probably means that the allocator effectively freed the memory internally, but not from the system.

This is exactly what happens. Generally Rust cannot guarantee anything about the allocator's behaviour in this regard (when and how it does caching like this), so this isn't considered a bug.

You can switch back to jemalloc using [jemallocator](https://github.com/gnzlbg/jemallocator) if it behaves better for your application.

Closing since this is an expected consequence of the switch to the system allocator.

**Closed by jonas-schievink** 2019-03-05 16:55 UTC

**Comment by antoinep92** [comment] 2019-03-05 17:20
> Generally Rust cannot guarantee anything about the allocator's behavior in this regard

True (and also true for most programming languages). The exact interaction with the OS is undefined behavior. But, if rust chose to ship and use jemalloc by default, it proves that even if there are no guarantees, there is some interest to optimizing that.

In this spirit it seems interesting to note a regression in the default behavior introduced with rust 1.32. For one of our services, this translates to reserved memory growing from ~1Gb to ~4Gb,  so for now we are sticking with rust 1.31.

Nevertheless I understand that this might be outside of the scope of the issues to investigate. But then this is more of a feature request I guess: is there a way to control the (system or jemalloc) memory allocator options, like CPU/memory tradeoffs ? If not I believe it would be valuable given the low-level / systems programming target of rust. If a crate for that does not exist for that, we may be willing to contribute it if there is some interest.

**Comment by jonas-schievink** [comment] 2019-03-05 17:26
Yes, the global allocator can be swapped out, and alongside jemallocator there's a few community crates that provide either fully custom allocators or instrumentation around the existing allocator. Feel free to explore that and provide your own if you want!
