### ISSUE TITLE
Derive breaks visibility order

### ISSUE THREAD

**Issue by kurnevsky** [rust-lang/rust#61520] opened 2019-06-04 15:33 UTC
Compilation of the following example depends on the derive existence. It will compile without it and will break with it. Also it will work with derive if `use crate::b::*;` is replaced by `use crate::b::{*, A};` inside `c` mod.

```rust
mod a {
    pub struct A;
}

mod b {
    use crate::a::*;

    #[derive(Clone)]
    struct A;

    fn f(a: A) {}

    mod c {
        use crate::b::*;

        fn x() {
            f(A)
        }
    }
}

fn main() { }
```

```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
  --> src/main.rs:17:15
   |
17 |             f(A)
   |               ^ expected struct `b::A`, found struct `a::A`
   |
   = note: expected type `b::A`
              found type `a::A`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

Playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5e896cad4b839beefe6ff7cc5bf491f0

**Comment by treere** [comment] 2019-06-08 10:03
Just to be sure I tested this code with a custom (and empty) derive macro.
The error is the same.

**Comment by petrochenkov** [comment] 2019-06-08 10:25
Looks very similar to https://github.com/rust-lang/rust/issues/56593

**Comment by treere** [comment] 2019-06-22 18:11
Same error with a normal macro:
```rust
macro_rules! a {
    () => {
        struct A;
    }
}
mod a {
    pub struct A;
}

mod b {
    use crate::a::*;

    a!();

    fn f(a: A) {}

    mod c {
        use crate::b::*;

        fn x() {
            f(A)
        }
    }
}

fn main() { }
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c12c524522f850a1c7aa19b52db060ae

**Comment by dtolnay** [comment] 2020-12-29 21:57
Closing as a duplicate of #56593.

**Closed by dtolnay** 2020-12-29 21:57 UTC
Labels: A-macros, A-resolve, C-bug, T-compiler, T-lang
