### ISSUE TITLE
Generic param requires bounds on call to function that is already required for calls to the caller

### ISSUE THREAD

**Issue by sharnoff** [rust-lang/rust#102611] opened 2022-10-03 04:06 UTC
Seems like this behavior has existed for a while, so apologies in advance if this is already a settled matter. If so, I still think the failure coulld use a better error message.

In short, the following code fails to compile:
```rust
pub struct Foo<'a, A>(&'a A);

impl<'a, A> Foo<'a, A> {
    pub fn foo() {}
    
    pub fn call_foo() {
        Self::foo();
    }
}
```
([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8c6adca96101697aaee5c75621a35eb4))

Error message:
```
error[E0309]: the parameter type `A` may not live long enough
 --> src/lib.rs:7:9
  |
7 |         Self::foo();
  |         ^^^^^^^^^ ...so that the type `A` will meet its required lifetime bounds
  |
help: consider adding an explicit lifetime bound...
  |
3 | impl<'a, A: 'a> Foo<'a, A> {
  |           ++++
```

In `call_foo`, the compiler (correctly) requires that `A: 'a`, but fails to realize that this bound is already satisfied (because this is also required for callers of `call_foo`).

To me, this seems like a bug. However, this behavior seems to have been present in stable for long enough that it seems highly unlikely it hasn't already been discussed at length - I couldn't find any issues referencing it though. (closest seems to be #84021).

Happy to help where I can (would need some direction).

**Comment by lcnr** [comment] 2022-10-03 12:09
```rust
pub struct Foo<'a, A>(&'a A);

impl<'a, A> Foo<'a, A> {
    pub fn foo() {
        Self::foo();
    }
}
```
yeah, implied bounds from the impl header are ignored while typechecking a function body but apparently still required somewhere :grin: i am currently working on this and should hopefully be able to fix this in the somewhat near future

@rustbot claim

**Comment by aliemjay** [comment] 2022-10-03 12:16
> but apparently still required somewhere grin

They're required for the WF-check of `Self` in borrowck. This is a duplicate of #98852.

**Closed** 2024-01-17 04:40 UTC
Labels: T-compiler, C-bug
