### ISSUE TITLE
Making a function `pub` can cause it to fail to compile

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#72336] opened 2020-05-18 20:09 UTC
I don't know if this is necessarily a bug, but it's certainly surprising:

```rust
trait Test {
    type Result;
}

impl Test for u32 {
    type Result = Foo<u32>;
}

struct Foo<T: Test> {
    foo: Option<T::Result>,
    bar: T,
}

fn make<T: Default + Test>() -> Foo<T> {
    Foo {
        foo: None,
        bar: Default::default(),
    }
}

/*pub */fn test() {
    make::<u32>();
}
```
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c9368fd4dfa72edefe79b1e6e4ee1ae1)

Uncommenting the `pub` keyword will cause it to fail to compile with the error:
```
error[E0391]: cycle detected when computing layout of `Foo<u32>`
  |
  = note: ...which requires computing layout of `std::option::Option<Foo<u32>>`...
  = note: ...which again requires computing layout of `Foo<u32>`, completing the cycle
```

**Comment by jonas-schievink** [comment] 2020-05-18 20:38
It also happens when renaming the function to `main`, so visiblity is not the issue. Instead, mentioning the invalid type in any place where it needs to be code-gen'd will cause the error. I believe monomorphization errors due to conditionally-infinite types are expected though.

**Comment by RalfJung** [comment] 2020-05-20 19:31
Yeah, private unused functions (except for `main` of a bin crate) are not codegen'd, so you won't get any monomorphization-time errors.

**Comment by jonas-schievink** [comment] 2020-05-20 20:24
Closing as expected behavior.

**Closed by jonas-schievink** 2020-05-20 20:24 UTC
