### ISSUE TITLE
edition lint: modules shadowing extern crates

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#52040] opened 2018-07-03 23:52 UTC
AFAIK, we don't have a plan for how to handle this. We should make one!

cc @rust-lang/compiler

**Comment by alexcrichton** [comment] 2018-07-11 18:47
@nrc do you have thoughts on @oli-obk's comment? I'm trying to see what I could do to help move this a long but it's not clear to me what it is!

**Comment by Mark-Simulacrum** [comment] 2018-07-16 02:55
```rust
mod serde;
use crate::serde::Serialize;
```

This is I believe ambiguous as implemented today because of implicit prelude; both `extern crate serde` and `mod serde` are defined in the "root" namespace so the import will fail or behave unexpectedly. I wasn't able to quickly reproduce on the playground; haven't tried locally. But I think something along these lines is possibly at least a problem.

**Comment by alexcrichton** [comment] 2018-07-16 14:02
@Mark-Simulacrum I don't think there's an implicit prelude of `extern crate` declarations though? `use crate::serde` always uses the `mod serde;` or `extern crate serde` *if defined explicitly`, and `use serde::...` always uses an external crate

**Comment by nikomatsakis** [comment] 2018-07-16 14:04
The issue I believe is not that there is some inherent ambiguity -- e.g., with @Mark-Simulacrum's example, in fact, the `use` can only refer to the module (in particular, with relative paths, the prelude doesn't even come into play at all).

A more interesting case is a case like this:

```rust
mod serde;
mod foo {
    // In Rust 2015, this comes from the module at crate root.
    //
    // In Rust 2018, this comes from the crate `serde` (presuming there is one), or otherwise
    // is an error.
    use serde::bar;
}
```

I believe our fear was that we would sometimes make incorrect rewrite suggestions in the migration lints. I can think of a few possibilities.

### Incorrect use

This may not be an issue, actually, but the idea would be that you have a use like this which currently refers to the **serde crate**:

```rust
mod serde;

mod bar {
    extern crate serde;
    use self::serde::Foo;
}
```

If we were to try and rewrite this path to `use serde::Foo`, then we'd have a problem, but I don't think we attempt that now. I think we will only rewrite a `use` in the case where the extern crate is at the root, in which case module shadowing is a non-issue -- well, that is true for the current proposal. @aturon was talking about extending things last I heard.

### Outside of a use

```rust
extern crate serde;

mod foo {
mod serde;

fn foo() -> ::serde::Foo { }
}
```

I don't recall what kind of rewrites we do in these cases, but perhaps we would rewrite `::serde::Foo` to `serde::Foo`? If so, that'd be bad.

**Comment by nikomatsakis** [comment] 2018-07-16 14:06
(On a related note, we will currently suggest removing `extern crate` in some cases, but shadowing is an example of the kind of case where we have to be a bit careful.)

**Comment by alexcrichton** [comment] 2018-07-17 15:07
@nikomatsakis I fear I'm left even more confused after reading your comment than before :(

For your "incorrect use" example we don't currently lint anything starting with `self` or `super`, only paths that *don't* start with one of those (and they don't start with an `extern crate`).

For the "outside of a use" example I'm not really sure what's going on, but we [don't make any suggestions today](https://play.rust-lang.org/?gist=0bd5d11c26889a84d970e884c13204a4&version=nightly&mode=debug&edition=2015).

It sounds like this issue is mostly "if we get aggressive about suggestions we'll have problems", but I don't think we're that aggressive today? It's today just a pure "your code will stop compiling, please fix it" lint rather than "your code isn't idiomatic, please let me help you" lint

**Comment by aturon** [comment] 2018-08-21 18:13
This issue is not currently actionable. I've removed from the milestone but tagged for @rust-lang/lang team discussion.

**Comment by joshtriplett** [comment] 2018-08-23 18:53
We do need to fix the edition lints and rustfix suggestions for the edition, especially with `uniform_paths`.

**Comment by nikomatsakis** [comment] 2018-08-23 19:34
Nobody can tell what this was about. Maybe it doesn't apply. We're going to close it for now until we have some actionable bug.

**Closed by nikomatsakis** 2018-08-23 19:34 UTC
Labels: A-edition-2018-lints, I-nominated, T-lang
