### ISSUE TITLE
rustc panicked at stable_hash_impls.rs: unwrap on None

### ISSUE THREAD

**Issue by DerickEddington** [rust-lang/rust#122576] opened 2024-03-15 23:45 UTC
### Reproduction
```shell
$ git clone --branch=tool-bug/rustc/1 https://github.com/DerickEddington/sailce.git \
  && cd sailce

$ cargo +nightly-2024-03-15 check --workspace --all-targets --all-features
```

### Meta
`rustc +nightly-2024-03-15 --version --verbose`:
```
rustc 1.78.0-nightly (f4b771bf1 2024-03-14)
binary: rustc
commit-hash: f4b771bf1fb836392e1c510a625cdc81be09c952
commit-date: 2024-03-14
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Error output
```
thread 'rustc' panicked at /rustc/f4b771bf1fb836392e1c510a625cdc81be09c952/compiler/rustc_hir/src/stable_hash_impls.rs:97:35:
called `Option::unwrap()` on a `None` value
...
```

### Backtrace
See attached file:
[rustc-ice-2024-03-15T23_33_23-4426.txt](https://github.com/rust-lang/rust/files/14621600/rustc-ice-2024-03-15T23_33_23-4426.txt)

**Comment by jieyouxu** [comment] 2024-03-16 00:00
Thanks for the report. You are running into #122508 which is fixed in the next nightly. In the mean time, you can work around this by https://github.com/rust-lang/rust/issues/122508#issuecomment-1999016195

> A workaround to this issue should be to use cargo check --release or cargo build --release which should disable incremental compilation.

Closing as a duplicate of #122508.

**Closed by jieyouxu** 2024-03-16 00:00 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
