### ISSUE TITLE
GCNO files contain path which are neither absolute nor relative

### ISSUE THREAD

**Issue by calixteman** [rust-lang/rust#54792] opened 2018-10-03 17:19 UTC
When profiling this code:
```
fn main() {
    println!("hello");
}
```

the generated gcno contains the following paths:
```
llvm-cov-7 gcov -dump plop-12b91b0bdcb3e9a4.gcno 2>1 | rg 'File .*/'
1:File 'libcore/fmt/mod.rs'
5:File 'libcore/ops/function.rs'
9:File 'libcore/ptr.rs'
13:File 'libstd/process.rs'
17:File 'libstd/rt.rs'
21:File 'libstd/sys/unix/process/process_common.rs'
25:File 'src/main.rs'
```

The 6 first paths are neither absolute nor relative.
So it's pretty hard to do something with them.

**Comment by Enselic** [comment] 2023-11-18 22:38
Triage: Looks like this is fixed now? I get this:

```console
$ rustc -Zprofile -Cdebuginfo=2 main.rs
$ llvm-cov-14 gcov -dump main.gcno 2>&1 | grep File
File '/rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/std/src/sys_common/backtrace.rs'
File '/rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/std/src/rt.rs'
File '/rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/core/src/fmt/mod.rs'
File '/rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/core/src/ops/function.rs'
File '/rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/core/src/ptr/mod.rs'
File '/rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/std/src/process.rs'
File 'src/main.rs'
```

**Comment by Enselic** [comment] 2024-11-08 18:50
Triage: It would be good to use `cargo bisect-rustc` to find the fix and make sure a regression test was added.

**Comment by workingjubilee** [comment] 2024-11-09 06:09
this is about gcov-based profiling, which we now no longer support.

**Closed by workingjubilee** 2024-11-09 06:09 UTC
Labels: T-compiler, C-bug, E-needs-bisection
