### ISSUE TITLE
Strange JSON output from x.py / rustbuild

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#71613] opened 2020-04-27 16:03 UTC
Since recently, the following line started to appear in `x.py` output, for example when invoking `./x.py test src/test/ui --stage 1 -j 4 --test-args con`:
```
{"reason":"build-finished","success":true}
```
Showing this between the otherwise human-readable output was presumably not intentional. :)

Cc @Mark-Simulacrum

**Comment by jonas-schievink** [comment] 2020-04-27 16:13
Duplicate of https://github.com/rust-lang/rust/issues/71561

**Closed by jonas-schievink** 2020-04-27 16:13 UTC
Labels: A-rustbuild, C-bug
