### ISSUE TITLE
Why doesn't `let (&x, &y) = &(t, t,)` work?

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#71730] opened 2020-05-01 03:00 UTC
I'm not sure whether this is a bug or not, feel free to close if it's not.
I tried this code:

```rust
fn foo1() {
    let c = 1i32;
    let &x = &c;
}

fn foo2() {
    let c = (1i32, 2i32);
    let (&x, &y) = &c;
}
```
I expected to see this happen: Everything compiles fine, since components of the tuple are all `Copy`.

Instead, this happened: The second case fails with bad diagnostics.

**Comment by lcnr** [comment] 2020-05-01 08:19
Afaik this is intended behavior. You don't have a tuple of references but a reference to a tuple.
I don't think match ergonomics should allow this.

```rust
fn foo2() {
    let c = (1i32, 2i32);
    let &(x, y) = &c;
    // This works
}
```

**Comment by crlf0710** [comment] 2020-05-01 10:51
Thanks.

**Comment by crlf0710** [comment] 2020-05-06 13:12
Thinking more about this, i still think it's a little weird that this doesn't work.
```rust
// this works fine
fn foo3((a, b): &(i32, i32)) {
}

// this doesn't
fn foo4((&a, &b): &(i32, i32)) {                                                                                                                                                                                                                } 
```
I think this should work for consistency, because there should only be one meaning for `&` within patterns: matching reference and dereference it.

**Comment by lzutao** [comment] 2020-05-06 13:22
But this does work:
```rust
fn foo4(&(a, b): &(i32, i32)) {}
```

I think pattern matching is consistent here.

**Comment by memoryruins** [comment] 2020-05-06 13:31
I agree; the current behavior is consistent. `foo3` compiles with `a` and `b` now having the type `&i32`. The only dereference pattern that is applicable is on the outer tuple, seen in Izutao's and lcnr's examples.

Some additional variations with explicit types if it helps make the current behavior clearer:
```rust
fn main() {
    let c: (u8, u8) = (0, 1);
    //
    let (x, y): &(u8, u8) = &c;
    let _: (&u8, &u8) = (x, y);
    //
    let (ref x, ref y): &(u8, u8) = &c;
    let _: (&u8, &u8) = (x, y);
    //
    let &(x, y): &(u8, u8) = &c;
    let _: (u8, u8) = (x, y);
    //
    let (x, y): &(u8, u8) = &c;
    let (&x, &y): (&u8, &u8) = (x, y);
    let _: (u8, u8) = (x, y);
    //
    let &(x, ref y): &(u8, u8) = &c;
    let _: (u8, &u8) = (x, y);
}

fn foo3((a, b): &(i32, i32)) {
    let _: &i32 = a;
    let _: &i32 = b;
}

fn foo3_2((ref a, ref b): &(i32, i32)) {
    let _: &i32 = a;
    let _: &i32 = b;
}

// fn foo4(&(a, b): &(i32, i32)) {}

fn foo4_2(&(a, b): &(i32, i32)) {
    let _: i32 = a;
    let _: i32 = b;
}
```

**Comment by crlf0710** [comment] 2020-05-06 16:23
Sorry, i still feel i'm missing something important here, i'm not finding a way to express myself, but just examining the rules and design goals. Let me list my way of thinking and assumptions :(
a. Match ergonomics can and should be able to fully replace all old usages of `ref` keyword. If it covers most cases but leave some corner cases behind, it's a design flaw.
b. 
```rust
fn foo3(&(a, ref b): &(i32, i32)) {
}
```
currently works.
c.
```rust
fn foo3((&a, b): &(i32, i32)) {
}
```
Conceptually should work exactly as the previous program. However it doesn't.
d.
There's nothing really stopping us for mending this flaw, other than amount of work.

**Comment by Nadrieril** [comment] 2023-12-01 02:12
Closing as a duplicate of https://github.com/rust-lang/rust/issues/64586 (feel free to reopen if I misunderstood)

**Closed by Nadrieril** 2023-12-01 02:12 UTC
Labels: C-bug, A-patterns
