### ISSUE TITLE
does not have a "fn_arg_names"

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/rust#130340] opened 2024-09-14 06:27 UTC
### Code

the project is still not open source, also I can't trigger the ICE manually, it is triggered by RustRover codes analyses

### Meta

`rustc --version --verbose`:
```
rustc 1.83.0-nightly (0609062a9 2024-09-13)
binary: rustc
commit-hash: 0609062a91c8f445c3e9a0de57e402f9b1b8b0a7
commit-date: 2024-09-13
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0
```

### Error output

I only got the ICE log file **rustc-ice-2024-09-14T03_55_39-41227.txt**

```
thread 'rustc' panicked at compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:244:1:
DefId(38:1373 ~ wiresquirrel_core[9f9e]::config::ApplyConfig::Error) does not have a "fn_arg_names"
stack backtrace:
   0:     0x76043043dbe5 - std::backtrace::Backtrace::create::h47c5ac21bc5295ff
   1:     0x76042ea62695 - std::backtrace::Backtrace::force_capture::h22d7360fb10c606e
   2:     0x76042db7d337 - std[b495ad0c4617e146]::panicking::update_hook::<alloc[a0425571c9a9acf]::boxed::Box<rustc_driver_impl[f22662736fcaf763]::install_ice_hook::{closure#0}>>::{closure#0}
   3:     0x76042ea79d18 - std::panicking::rust_panic_with_hook::h0dd05eda4407feb9
   4:     0x76042ea79ae7 - std::panicking::begin_panic_handler::{{closure}}::hff4951198a9049be
   5:     0x76042ea774c9 - std::sys::backtrace::__rust_end_short_backtrace::hae232f20e82e2c44
   6:     0x76042ea797b4 - rust_begin_unwind
   7:     0x76042b894523 - core::panicking::panic_fmt::h6dddd3310fdcb8b7
   8:     0x76042e135c72 - rustc_metadata[f09f1bff9e284ebb]::rmeta::decoder::cstore_impl::provide_extern::fn_arg_names::{closure#2}
   9:     0x76042e135afe - rustc_metadata[f09f1bff9e284ebb]::rmeta::decoder::cstore_impl::provide_extern::fn_arg_names
  10:     0x7604306756b1 - rustc_query_impl[484dcaccf014b2f3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[484dcaccf014b2f3]::query_impl::fn_arg_names::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7cca7f2870ea52e7]::query::erase::Erased<[u8; 16usize]>>.cold
  11:     0x76042f3a4c15 - <rustc_query_impl[484dcaccf014b2f3]::query_impl::fn_arg_names::dynamic_query::{closure#2} as core[7f44e8b513577cf8]::ops::function::FnOnce<(rustc_middle[7cca7f2870ea52e7]::ty::context::TyCtxt, rustc_span[45f656ad9ccc3ab8]::def_id::DefId)>>::call_once
  12:     0x76042f61cacf - rustc_query_system[a8532041af820499]::query::plumbing::try_execute_query::<rustc_query_impl[484dcaccf014b2f3]::DynamicConfig<rustc_query_system[a8532041af820499]::query::caches::DefIdCache<rustc_middle[7cca7f2870ea52e7]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[484dcaccf014b2f3]::plumbing::QueryCtxt, true>
  13:     0x76042f61b07b - rustc_query_impl[484dcaccf014b2f3]::query_impl::fn_arg_names::get_query_incr::__rust_end_short_backtrace
  14:     0x76042f6225a3 - rustc_middle[7cca7f2870ea52e7]::query::plumbing::query_get_at::<rustc_query_system[a8532041af820499]::query::caches::DefIdCache<rustc_middle[7cca7f2870ea52e7]::query::erase::Erased<[u8; 16usize]>>>
  15:     0x76042e67e110 - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor>::try_lookup_name_relaxed
  16:     0x76042e676941 - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor>::smart_resolve_report_errors
  17:     0x76042c0dea2c - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor>::smart_resolve_path_fragment::{closure#0}
  18:     0x76042fda73d6 - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor>::smart_resolve_path_fragment
  19:     0x76042c0d622f - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor as rustc_ast[127b06bb4fb6fbee]::visit::Visitor>::visit_ty
  20:     0x76042c1fecc9 - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor as rustc_ast[127b06bb4fb6fbee]::visit::Visitor>::visit_item
  21:     0x76042fd92953 - rustc_ast[127b06bb4fb6fbee]::visit::walk_assoc_item::<rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor, rustc_ast[127b06bb4fb6fbee]::ast::ItemKind>
  22:     0x76042c2057d6 - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor as rustc_ast[127b06bb4fb6fbee]::visit::Visitor>::visit_item
  23:     0x76042fd92953 - rustc_ast[127b06bb4fb6fbee]::visit::walk_assoc_item::<rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor, rustc_ast[127b06bb4fb6fbee]::ast::ItemKind>
  24:     0x76042c2057d6 - <rustc_resolve[4a042f4811ed53f0]::late::LateResolutionVisitor as rustc_ast[127b06bb4fb6fbee]::visit::Visitor>::visit_item
  25:     0x76043040612f - <rustc_resolve[4a042f4811ed53f0]::Resolver>::resolve_crate::{closure#0}
  26:     0x760430400500 - <rustc_resolve[4a042f4811ed53f0]::Resolver>::resolve_crate
  27:     0x76042f6fcb3e - rustc_interface[1ce9087adc29d20e]::passes::resolver_for_lowering_raw
  28:     0x76042f6fbd5b - rustc_query_impl[484dcaccf014b2f3]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[484dcaccf014b2f3]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[7cca7f2870ea52e7]::query::erase::Erased<[u8; 16usize]>>
  29:     0x76042f6fbd49 - <rustc_query_impl[484dcaccf014b2f3]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[7f44e8b513577cf8]::ops::function::FnOnce<(rustc_middle[7cca7f2870ea52e7]::ty::context::TyCtxt, ())>>::call_once
  30:     0x76043025b77b - rustc_query_system[a8532041af820499]::query::plumbing::try_execute_query::<rustc_query_impl[484dcaccf014b2f3]::DynamicConfig<rustc_query_system[a8532041af820499]::query::caches::SingleCache<rustc_middle[7cca7f2870ea52e7]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[484dcaccf014b2f3]::plumbing::QueryCtxt, true>
  31:     0x76043025b20a - rustc_query_impl[484dcaccf014b2f3]::query_impl::resolver_for_lowering_raw::get_query_incr::__rust_end_short_backtrace
  32:     0x76042ff3a830 - rustc_interface[1ce9087adc29d20e]::interface::run_compiler::<core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>, rustc_driver_impl[f22662736fcaf763]::run_compiler::{closure#0}>::{closure#1}
  33:     0x76043003fc50 - std[b495ad0c4617e146]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1ce9087adc29d20e]::util::run_in_thread_with_globals<rustc_interface[1ce9087adc29d20e]::util::run_in_thread_pool_with_globals<rustc_interface[1ce9087adc29d20e]::interface::run_compiler<core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>, rustc_driver_impl[f22662736fcaf763]::run_compiler::{closure#0}>::{closure#1}, core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>>::{closure#0}, core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>>
  34:     0x7604300402ba - <<std[b495ad0c4617e146]::thread::Builder>::spawn_unchecked_<rustc_interface[1ce9087adc29d20e]::util::run_in_thread_with_globals<rustc_interface[1ce9087adc29d20e]::util::run_in_thread_pool_with_globals<rustc_interface[1ce9087adc29d20e]::interface::run_compiler<core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>, rustc_driver_impl[f22662736fcaf763]::run_compiler::{closure#0}>::{closure#1}, core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>>::{closure#0}, core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[7f44e8b513577cf8]::result::Result<(), rustc_span[45f656ad9ccc3ab8]::ErrorGuaranteed>>::{closure#1} as core[7f44e8b513577cf8]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  35:     0x7604300406ab - std::sys::pal::unix::thread::Thread::new::thread_start::hdd18e2f9323a466b
  36:     0x76042a4a339d - <unknown>
  37:     0x76042a52849c - <unknown>
  38:                0x0 - <unknown>


rustc version: 1.83.0-nightly (0609062a9 2024-09-13)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [fn_arg_names] looking up function parameter names for `wiresquirrel_core::config::ApplyConfig::Error`
#1 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
```

**Comment by fmease** [comment] 2024-09-14 12:04
Duplicate of #130015

**Closed by fmease** 2024-09-14 12:04 UTC
Labels: I-ICE, T-compiler, C-bug
