### ISSUE TITLE
Lifetime regression in kick 0.1.2

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#38390] opened 2016-12-15 17:33 UTC
[Original report](https://internals.rust-lang.org/t/regression-report-stable-2016-11-08-vs-beta-2016-12-10/4461).

```
error[E0309]: the parameter type `T` may not live long enough

   --> src/signal/variable.rs:114:5

    |

114 |     fn listen<F>(&self, f: F) -> Self::Listen


    |     ^

    |

    = help: consider adding an explicit lifetime bound `T: 'a`...

note: ...so that the type `T` will meet its required lifetime bounds

   --> src/signal/variable.rs:114:5

    |

114 |     fn listen<F>(&self, f: F) -> Self::Listen


    |     ^


error: aborting due to previous error
```

It's not clear what the change was here but @nagisa remembers something about:

```
09:28 < nagisa> so, the error for kick seems legit to me
09:28 < acrichto> brson: ok kaws is benign
09:28 < acrichto> nondeterministic cargo crate graph resolution
09:28 < acrichto> first build just happened to get a working crate graph
09:28 < acrichto> second build didn't
09:28 < nagisa> it has `where F: Into<Slot<'a, 'a, T, Tr>>` and no `T:'a`
09:29 < acrichto> brson: tl;dr; kaws is a standard legit cargo error, no regression
09:29 < nagisa> I mildly remember a pr or something along the lines
09:29 <~brson> ugh
09:30 <~brson> nagisa: that's for kick?
09:30 < nagisa> yes
09:30 < nagisa> though I might be remembering incorrectly too
09:30 < nagisa> would be best to ask nmatsakis if he wasn’t on a vacation
09:31  * brson still filing bugs
09:32 < nagisa> I would fill a bug for kick too, pink nmatsakis and revisit a week later
```

cc @nikomatsakis @rust-lang/lang

**Comment by nagisa** [comment] 2016-12-15 17:37
Namely the signature of failing function looks like this;

```rust
pub enum Slot<'a, 'b: 'a, T: 'a, Tr: Transaction<'b> + 'b> {
    Nothing,
    Ref(&'a SlotFn<'a, 'b, T, Tr>),
    SRef(Rc<SlotFn<'a, 'b, T, Tr>>),
    WRef(Weak<SlotFn<'a, 'b, T, Tr>>),
    Mut(&'a mut SlotFnMut<'a, 'b, T, Tr>),
    Boxed(Box<SlotFnMut<'a, 'b, T, Tr>>),

    #[cfg(feature="nightly")]
    Once(Box<SlotFnBox<'a, 'b, T, Tr>>),
}

impl<'a, T, Tr: Transaction<'a> + 'a> Stream<'a, Tr> for Variable<'a, T, Tr>
    where T: Clone
{
    type Output = T;
    type Listen = <Event<'a, T, Tr> as Stream<'a, Tr>>::Listen;

    fn listen<F>(&self, f: F) -> Self::Listen
        where F: Into<Slot<'a, 'a, T, Tr>>
    {
        self.updates.listen(f)
    }
}
```

Note the `T:'a` bound on `Slot` but lack of any such requirement for the `listen` bound (or I’m not seeing one, anyway).

**Comment by nikomatsakis** [comment] 2016-12-22 22:12
triage: P-high

**Comment by nikomatsakis** [comment] 2016-12-22 22:12
I'll investigate, but seems like it is likely expected behavior.

**Comment by nikomatsakis** [comment] 2017-01-03 21:49
I agree with @nagisa that this is expected behavior, though I'm not sure what caused it to change.

**Comment by brson** [comment] 2017-01-03 21:52
Seems like we just need to add the test case.

**Comment by nikomatsakis** [comment] 2017-01-03 21:53
Yeah, I'll have to try and minimize it though.

**Comment by alexcrichton** [comment] 2017-01-04 01:24
If this is expected behavior and just needs a test case, I'll also remove the regression tag.

**Comment by nikomatsakis** [comment] 2017-01-04 21:12
Can anyone verify that this used to work? It seems like if we are going to make a test case, we'd also want to verify that the test case *used* to pass...

**Comment by Dylan-DPC** [comment] 2020-04-13 22:26
Closing this, since it is no longer applicable.

**Closed by Dylan-DPC** 2020-04-13 22:26 UTC
Labels: C-bug, E-needs-test, T-compiler
