### ISSUE TITLE
Rustdoc --test and error messages

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#16303] opened 2014-08-06 14:47 UTC
Often, when explaining something, I want to show some code that errors, and then show the error. Because it errors, I have to mark it ignore. It'd be nice if Rustdoc could understand that something is supposed to error, and then make sure the error message matches the one displayed.

**Comment by alexcrichton** [comment] 2015-04-06 23:48
I'm gonna close as a dupe of #12335 as the decision of that issue will decide if it's possible to test error messages from the compiler in general.

**Closed by alexcrichton** 2015-04-06 23:48 UTC
Labels: A-rustdoc
