### ISSUE TITLE
rustdoc: Notable traits shows wrong type parameter

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80737] opened 2021-01-06 00:19 UTC
The "Notable traits" popup for [`Entry::or_insert`] shows notable traits for `&'_ mut I` when it should show `&'a mut V` (or at least `&'_ mut V`):

![image](https://user-images.githubusercontent.com/37223377/103713542-76ebdd80-4f71-11eb-8611-3c8d13323096.png)

Note that this happens for other functions on `Entry`. Another example is [`Entry::key`] which shows `&'_ mut I` when it should show `&'a K`.

I'm not 100% sure this is a bug, but the behavior is definitely confusing: I'm not sure what the notable traits popup is referring to when it references an `I` type parameter (`mut I` doesn't even appear in the file that `Entry` is defined in...).

[`Entry::or_insert`]: https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.or_insert
[`Entry::key`]: https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.key

**Comment by jyn514** [comment] 2021-01-06 03:35
I think this is a duplicate of https://github.com/rust-lang/rust/issues/14072.

**Comment by camelid** [comment] 2021-01-06 03:48
Hmm, that seems possible.

Wow, that issue is so old: it refers to `uint`! Off-topic: is there a way to see what the docs from then look like?

**Comment by jyn514** [comment] 2021-01-07 18:39
> Off-topic: is there a way to see what the docs from then look like?

Yes, you can manually type the version number in the URL: https://doc.rust-lang.org/1.0.0/std/

**Comment by camelid** [comment] 2021-01-07 20:26
Thanks! I forgot about that. However, I meant for the docs pre-1.0. Do you know of any way to view those?

**Closed** 2021-12-12 09:57 UTC
Labels: T-rustdoc, A-traits, C-bug

**Comment by camelid** [comment] 2021-12-12 19:35
> Thanks! I forgot about that. However, I meant for the docs pre-1.0. Do you know of any way to view those?

Followup: 0.11.0 is the earliest version I could find docs for: https://doc.rust-lang.org/0.11.0/std/
