### ISSUE TITLE
Unable to find crate `proc_macro` on musl target

### ISSUE THREAD

**Issue by golddranks** [rust-lang/rust#40174] opened 2017-03-01 11:32 UTC
Using procedural derive macros on musl seems to work just fine for the most of the cases, but there is one pitfall; in some cases like this https://github.com/dtolnay/proc-macro-hack/issues/6 build fails because not only the crate that implements the macro (crate marked with `proc-macro = true`), but also another, normal crate links to the `proc_macro` crate. "Normal" crates are unable to find `proc_macro` when built on musl target:

```
Compiling proc-macro-hack v0.3.0
error[E0463]: can't find crate for `proc_macro`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-hack-0.3.0/src/lib.rs:1:1
  |
1 | extern crate proc_macro;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `proc-macro-hack`.
```

**Comment by alexcrichton** [comment] 2017-03-01 15:09
Yes this is currently intentional. The proc_macro crate is only a dynamic library which the musl target currently doesn't support. I unfortunately don't think this will be easy to fix...

**Comment by golddranks** [comment] 2017-03-01 15:25
I understand why the proc macro crates need to be dynamic: they are loaded and run dynamically by the compiler. However what I don't understand is why the `proc_macro` crate isn't allowed to be linked both dynamically and statically? I'd imagine someone may want to use the types defined in `proc_macro` in some helper crate, outside the dynamically linked macro crate, as is the case here.

**Comment by golddranks** [comment] 2017-03-01 15:28
Is there some technical hurdle that makes it hard to do, or is it just not done because it's such a minor case?

**Comment by golddranks** [comment] 2017-03-01 16:44
The simplest test for this seems to be:

`test.rs` with just single line:
```
extern crate proc_macro;
```

build with (succeeds):
```
rustc test.rs --crate-type lib
```
and with (fails):
```
rustc test.rs --crate-type lib --target=x86_64-unknown-linux-musl
```

When RUST_LOG=info is enabled, the library probes can be seen.

**Comment by golddranks** [comment] 2017-03-01 23:28
Okay, I did some testing.

I `git clone`d the Rust source, edited away the `crate-type = ["dylib"]` annotation in `libproc_macro`, `librustc_data_structures`, `librustc_errors`, `libsyntax` and `libsyntax_pos`. (Transitive deps of `libproc_macro`)

After that, I built a `rlib` of `libproc_macro` with `cargo build --target=x86_64-unknown-linux-musl --verbose`. (This is on the newest nightly.)

After that, I copied the build artefacts from `~/rust/src/target/x86_64-unknown-linux-musl/debug/deps/` to `~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib`.

After that, I try to compile the things that failed before with musl target → it works.

So, it seems that there isn't any real *technical* hurdles. (or there is, but I haven't encountered them yet)

@alexcrichton, what do you think of distributing `rlibs` of aforementioned libraries with musl target?

**Comment by golddranks** [comment] 2017-03-01 23:34
Btw. I did this work on a Linux host. Tried to do the same on macOS (with musl target of course), but on macOS the linking fails with `ld: unknown option: --as-needed`. The linker is passed a flag `--as-needed` which seems to be supported on GNU linker only.

**Comment by golddranks** [comment] 2017-03-01 23:37
Ah, okay, the `--as-needed` behaviour is explained here: https://github.com/rust-lang/rust/issues/34282

**Comment by alexcrichton** [comment] 2017-03-02 17:20
Yes there are technical hurdles in terms of build system of doing that. This is also rarely what you want because there's no reason to have a full Rust parser linked into a binary (when it's not used).

**Comment by golddranks** [comment] 2017-03-02 17:38
I see, that's a convincing argument.

**Comment by drozdziak1** [comment] 2018-01-10 14:10
Hello,
sorry to dig up a closed issue, but I'm experiencing the same problem during an OpenWrt cross build (`i686-unknown-linux-musl` is the Rust target and VirtualBox is the OpenWrt one). My compiler is `rustc 1.25.0-nightly (61452e506 2018-01-09)`. I've got a couple questions regarding this:
* **Is the root cause known? What is it?**
* **Is there a solution out there?**
* **If not, where can I go to help solve this?**

**Comment by lisbakke** [comment] 2018-11-21 18:16
Hello! I've got this issue, as well -- deps relying on `proc-macro2` which do not use `default-features = false` so `proc-macro` crate is not found because my target does not have it.

I'm currently compiling rustc for my target and it seems easiest to create `proc-macro` lib when I'm building. Is there any documentation on how to do this?

**Comment by mmastrac** [comment] 2019-10-06 21:43
For those following various links to this issue, it is important to note that *you can compile code using `proc_macro` to statically-linked `musl` binaries, BUT you need to cross-compile from a platform that _does_ support dynamic linking.*

`cargo build --target x86_64-unknown-linux-musl` should be sufficient, but you'll need to run that on something like Ubuntu, Fedora, or another full system.

**Comment by jonas-schievink** [comment] 2019-11-13 16:32
Reopening as this seems to still be a significant issue for people building from musl systems

**Comment by masonk** [comment] 2019-12-30 20:20
`--target x86_64-unknown-linux-musl` doesn't work for me and shouldn't be considered a sufficient workaround.

Many important crates like OpenSSL need to be vendored and cross-compiled to musl (e.g., https://github.com/sfackler/rust-openssl/issues/980#issuecomment-415548838), but when I tried to do that, complications like feature flags not working with workspaces (e.g, https://github.com/rust-lang/cargo/issues/5015) started cropping up, and I threw up my hands and gave up on musl.

Even if there aren't plans to work on it in the near term, I don't think this issue should be considered fixed until either (1) It is easy to cross-compile apps to musl or (2) it is possible to cis-compile proc_macro targets on musl.

**Comment by Aaron1011** [comment] 2020-01-31 19:05
Would it make sense to have `--crate-type proc-macro` imply `-C target-feature=-crt-static` (maybe only on musl)? AFAIK, the precise output of `--crate-type proc-macro` is essentially an implementation detail, since they should only be used as compiler plugins by `rustc`.

**Comment by Ekleog** [comment] 2020-04-16 13:19
There are likely much better solutions, but… I've just come across https://github.com/dtolnay/watt ; and… would integrating this into rustc as a secondary backend for use only on platforms where regular proc macros aren't supported be a solution? It wouldn't support all the use cases I think, due to regular proc macros being allowed to eg. interact with the FS, but it should already support a number of use cases. And maybe, with time, the API could be extended so that proc macros could all be compiled with wasm, and the current dylib approach could be dropped, thus making porting rustc to a new architecture a lot easier?

**Comment by mati865** [comment] 2020-04-16 13:44
@Ekleog is it still an issue after https://github.com/rust-lang/rust/pull/69519?

**Comment by Ekleog** [comment] 2020-04-16 17:19
@mati865 I'm not sure, I've pinged here following a message from IRC that said this happened just today -- don't know for sure the version of the compiler used, so I've just pinged them

**Comment by breard-r** [comment] 2020-04-24 12:48
@mati865 If it's part of the brand new Rust 1.43, then yes, it is still an issue.

On Alpine, the [heavily patched](https://git.alpinelinux.org/aports/tree/community/rust?h=3.11-stable) rust package (1.39) can compile without any trouble. However, on the very same machine, any version of Rust (including 1.39 and 1.43) installed via rustup (and therefore without those patches) is subject to this issue.

**Comment by 12101111** [comment] 2020-04-24 13:11
@breard-r Rust 1.43 don't include this patch and you can try 1.44 beta from rustup.

**Comment by breard-r** [comment] 2020-04-24 13:24
@12101111 Thank you! I've just installed 1.44.0-beta via rustup and it builds! :smiley:

**Comment by jonas-schievink** [comment] 2020-04-24 13:47
Great! Closing as fixed then.

**Closed by jonas-schievink** 2020-04-24 13:47 UTC
Labels: A-linkage, A-macros, C-bug, O-musl, T-compiler

**Comment by jyn514** [comment] 2020-05-23 00:45
This is still broken for me using `rustc 1.44.0-beta.3 (0f0d70055 2020-05-11)`.

```
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
```

<details><summary>Full linker arguments</summary>

```
/rcc # cargo build
   Compiling thiserror-impl v1.0.19
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-m64" "-L" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.0.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.1.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.10.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.11.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.12.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.13.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.14.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.15.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.2.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.3.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.4.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.5.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.6.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.7.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.8.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.9.rcgu.o" "-o" "/rcc/target/debug/deps/libthiserror_impl-c05c536330366b8e.so" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.1x6px3h632f37ynj.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.2thl14zymh2c935g.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/rcc/target/debug/deps" "-L" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/rcc/target/debug/deps/libsyn-fe2290862b758c2c.rlib" "/rcc/target/debug/deps/libquote-afe91c35027afeba.rlib" "/rcc/target/debug/deps/libproc_macro2-0913bab1357133a2.rlib" "/rcc/target/debug/deps/libunicode_xid-8b9fbfbf3102211f.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libproc_macro-84e8be3f2684e30a.rlib" "-Wl,--start-group" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-5ee1781929f9655d.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-e2ec5d2aca499f1c.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-81740b8a57dba39b.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-eb99f2d2958ad0d9.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace-84349410b417ab27.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace_sys-b3c09d3262227e0b.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-c58a107a6842bb60.rlib" "/tmp/rustc3EmKiY/libunwind-33abd88ac2c901d5.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-c210a18d812061d6.rlib" "/tmp/rustc3EmKiY/liblibc-2b136be5748c5959.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-150a1e69c064728f.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-e390c28232836237.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-1cdf993f577c22fa.rlib" "-Wl,--end-group" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-9211daa04cc43fa3.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-shared"
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `thiserror-impl`.
```

</details>

**Comment by 12101111** [comment] 2020-05-23 05:33
> This is still broken for me using `rustc 1.44.0-beta.3 (0f0d70055 2020-05-11)`.
> 
> ```
>   = note: /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
> ```
> 
> Full linker arguments
> ```
> /rcc # cargo build
>    Compiling thiserror-impl v1.0.19
> error: linking with `cc` failed: exit code: 1
>   |
>   = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-m64" "-L" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.0.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.1.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.10.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.11.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.12.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.13.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.14.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.15.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.2.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.3.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.4.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.5.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.6.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.7.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.8.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.thiserror_impl.7sf2w6hc-cgu.9.rcgu.o" "-o" "/rcc/target/debug/deps/libthiserror_impl-c05c536330366b8e.so" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.1x6px3h632f37ynj.rcgu.o" "/rcc/target/debug/deps/thiserror_impl-c05c536330366b8e.2thl14zymh2c935g.rcgu.o" "-Wl,--gc-sections" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/rcc/target/debug/deps" "-L" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/rcc/target/debug/deps/libsyn-fe2290862b758c2c.rlib" "/rcc/target/debug/deps/libquote-afe91c35027afeba.rlib" "/rcc/target/debug/deps/libproc_macro2-0913bab1357133a2.rlib" "/rcc/target/debug/deps/libunicode_xid-8b9fbfbf3102211f.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libproc_macro-84e8be3f2684e30a.rlib" "-Wl,--start-group" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-5ee1781929f9655d.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-e2ec5d2aca499f1c.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-81740b8a57dba39b.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-eb99f2d2958ad0d9.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace-84349410b417ab27.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace_sys-b3c09d3262227e0b.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-c58a107a6842bb60.rlib" "/tmp/rustc3EmKiY/libunwind-33abd88ac2c901d5.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-c210a18d812061d6.rlib" "/tmp/rustc3EmKiY/liblibc-2b136be5748c5959.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-150a1e69c064728f.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-e390c28232836237.rlib" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-1cdf993f577c22fa.rlib" "-Wl,--end-group" "/usr/local/rustup/toolchains/beta-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-9211daa04cc43fa3.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-shared"
>   = note: /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
>           collect2: error: ld returned 1 exit status
>           
> 
> error: aborting due to previous error
> 
> error: could not compile `thiserror-impl`.
> ```

It seems you don't install musl-dev

**Comment by jyn514** [comment] 2020-05-23 13:43
That fixed it, thank you!

**Comment by WhyNotHugo** [comment] 2021-11-24 23:34
If you're bumping into this in 2021, it's likely that you need to run `apk add --no-cache musl-dev`.
