### ISSUE TITLE
Failure to compile causes a pop-up (Nightly Windows MSVC 32bit d5e229057)

### ISSUE THREAD

**Issue by valarauca** [rust-lang/rust#30775] opened 2016-01-08 00:15 UTC
Issue:
When compiler fails to compile. I.E.: Syntax, wrong variables, type errors, etc, etc. The windows dialog box for program failure pops up and asks if you'd like to Debug, Close, or Search online for a solution. This is really annoying.

How to reproduce:
1) Create project in cargo
2) Write code that can't compile
3) Try to compile code
4) See pop up.

**Comment by retep998** [comment] 2016-01-08 00:28
This is a known issue with 32-bit msvc. Unwinding has not been implemented yet so it crashes instead of exiting gracefully.

Dupe of https://github.com/rust-lang/rust/issues/25869

https://github.com/rust-lang/rust/pull/30448 will fix this

**Comment by huonw** [comment] 2016-01-09 01:35
Thanks for filing!

**Closed by huonw** 2016-01-09 01:35 UTC
