### ISSUE TITLE
Strange behaviour while resoving modules placed in constants

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#54525] opened 2018-09-24 08:32 UTC
There is a strange/inconsistent behaviour in the name resolution of models placed in constants. 
In detail placing a module inside of a constant works. 
Referring directly to types inside the module also works. 
```rust
const _DUMMY: () = {
    mod some_mod {
        pub struct Bar;
    }
    
    fn foo(_: some_mod::Bar) {}
};
```
compiles successfully.

Trying to use `use` statements or starting the path otherwise with `self::` results in compiler errors that `some_mod` is not found:

```rust
const _DUMMY: () = {
    mod some_mod {
        pub struct Bar;
    }
    // This fails
    use self::some_mod::Bar;    

    // This also fails
    fn foo(_: self::some_mod::Bar) {}
};
```

This behaviour  seems inconsistent for me. Either it should not be allowed to place modules inside of constants, or it should be possible to use relative paths to reference items inside of such modules (in scope of the constant block).

I would guess that the scope of self is not associated with the inner scope of the constant, but with the current module. From there the module inside of the constant is not visible.

This happens on all channels. 

Playground links:
* [Working](https://play.rust-lang.org/?gist=71ac1b7d208d2552ef2354f7f8f6d46a&version=stable&mode=debug&edition=2015)
* [Not working](https://play.rust-lang.org/?gist=b00b6071c02b2c6a8821ffdf50fc4d4d&version=stable&mode=debug&edition=2015)

**Comment by csmoe** [comment] 2018-09-24 08:43
Possibly Duplicate of https://github.com/rust-lang/rust/issues/18084

**Comment by Havvy** [comment] 2018-09-25 05:15
`self` refers to the module that the path is in, not the scope it is in.

Personally, I think of the place of that module in the constant to be `self::_DUMMY::$0::some_mod` and we cannot refer to `$n` paths.

This is definitely also a duplicate of that issue.

**Comment by petrochenkov** [comment] 2018-11-18 10:30
`self` means "current `mod`" and cannot be changed backward-compatibly, but https://github.com/rust-lang/rust/pull/55884 provides an alternative solution, on 2018 edition import paths are resolved in current scope and
```rust
const _DUMMY: () = {
    mod some_mod {
        pub struct Bar;
    }
    use some_mod::Bar;
};
```
"just works".

**Closed by petrochenkov** 2018-11-18 10:30 UTC
