### ISSUE TITLE
GAT : internal compiler error

### ISSUE THREAD

**Issue by ZiCog** [rust-lang/rust#66734] opened 2019-11-25 11:24 UTC
This code:
```
#![feature(generic_associated_types)]

trait Foo {
    type Bar<'a>;
    fn baz<'a>(&self, val: Self::Bar) -> Self::Bar;
}

struct Qux {
    x: i32,
    y: i32,
}

impl Foo for Qux {
    type Bar<'a> = &'a [u8];
    fn baz<'a>(&self, val: Self::Bar) -> Self::Bar {
        val
    }
}

fn main () {
}
```
Produces this compiler crash:
```
$ rustc junk.rs
warning: the feature `generic_associated_types` is incomplete and may cause the compiler to crash
 --> junk.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

error: internal compiler error: src/librustc_mir/borrow_check/nll/universal_regions.rs:741: cannot convert `ReEarlyBound(0, 'a)` to a region vid

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:643:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0-nightly (760226733 2019-08-22) running on x86_64-unknown-linux-gnu
```

**Comment by hellow554** [comment] 2019-11-25 14:17
Most likely a dup of #49362
What do you think @jonas-schievink

**Comment by jonas-schievink** [comment] 2019-11-25 14:20
Hmm, the message looks quite different. It looks very similar to https://github.com/rust-lang/rust/issues/62521, actually, so maybe it's a dupe of *that*.

**Comment by hellow554** [comment] 2019-11-25 14:21
Oh wow... I tried to reduce the code and missed that I encountered a different ICE. Sorry for that :/

**Comment by ZiCog** [comment] 2019-11-25 14:42
Sorry if this reporting a known issue. 

Somebody on the rust-lang forum was trying to explain GAT to me and presented this code as an example:
```
trait Foo {
    type Bar<'a>;
    fn baz<'a>(&self, val: Self::Bar<'a>);
}
impl Foo for Qux {
    type Bar<'a> = &'a [u8];
    fn baz<'a>(&self, val: &'a [u8]) {}
}
```
That did not compile, complaining about  <'a> in the wrong place so I started playing with it and ended up with what you see my report. Entirely my own creation in that respect.

**Comment by hellow554** [comment] 2019-11-25 14:49
> Sorry if this reporting a known issue.

No worries. I'm sorry if I sounded rude to you.
I/we really appreciate that you reported the ICE so we can fix the issue (at some time).
It's just to keep the issue tracker clean, that's nothing against you at all.

**Comment by jonas-schievink** [comment] 2019-11-25 14:51
Yeah, no worries, we have so many open issues that it's hard to figure out whether something is a duplicate or not. In any case, closing this in favor of #62521.

**Closed by jonas-schievink** 2019-11-25 14:51 UTC
Labels: A-NLL, C-bug, F-generic_associated_types, I-ICE, T-compiler
