### ISSUE TITLE
compiler panic impl Trait

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#43021] opened 2017-07-03 04:47 UTC
## Trying to Compile

```rust
fn derp (cfg: &ControlFlowGraph) -> impl Iterator<Item = &ControlFlowTarget> {
    cfg.vertices().filter_map(|vx| cfg.vertex_label(vx))
}
```

## Panic

```
-*- mode: compilation; default-directory: "~/projects/panopticon/core/src/" -*-
Compilation started at Sun Jul  2 21:45:03

cargo check
   Compiling panopticon-core v0.16.0 (file:///home/m4b/projects/panopticon/core)
error: internal compiler error: /checkout/src/librustc_typeck/check/mod.rs:614: escaping regions in predicate Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { trait_ref: <_ as std::iter::Iterator>, item_def_id: DefId { krate: CrateNum(2), node: DefIndex(1612) => core/640b678::iter[0]::iterator[0]::Iterator[0]::Item[0] } }, &function::ControlFlowTarget)),depth=0)
  --> function.rs:93:37
   |
93 | fn derp (cfg: &ControlFlowGraph) -> impl Iterator<Item = &ControlFlowTarget> {
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (69c65d296 2017-06-28) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:426
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `panopticon-core`.

To learn more, run the command again with --verbose.

Compilation exited abnormally with code 101 at Sun Jul  2 21:45:05
```

**Comment by PlasmaPower** [comment] 2017-07-03 15:53
Minimal code to reproduce (that should compile and run fine):

```rust
struct Example {}

const CONST: &'static Example = &Example {};

fn example(_: &Example) -> impl Iterator<Item = &Example> {
    ::std::iter::once(CONST)
}
```

This appears to be a bug with inferring lifetimes, as this works:

```rust
struct Example {}

const CONST: &'static Example = &Example {};

fn example<'a>(_: &'a Example) -> impl Iterator<Item = &'a Example> {
    ::std::iter::once(CONST)
}
```

**Comment by hawkw** [comment] 2017-07-03 16:33
I'm having the same issue, trying to compile the following code using the `futures` library:

```rust
fn run<T>(socket: TcpStreamNew, test: &T)
         -> impl Future<Item=Status, Error=Error>
where T: Test {
//where A: ToSocketAddrs
//    , A: fmt::Debug {
//
//    // first, create the client socket...
//    let socket = future::result(parse_addr(addr))
//        .and_then(|addr| TcpStream::connect(&addr, &handle));

    // send the HTTP request for this test...
    let request = socket.and_then(move |socket|
        io::write_all(socket, T::request().as_bytes()));

    // when we recieve a response, parse the response with httparse...
    let response = request
        .and_then(|(socket, _req)| io::read_to_end(socket, Vec::new()) )
        .and_then(|(_socket, bytes)| {
            // TODO: this is more than we'll need  – i should find a more
            //       reasonable way to determine the number of empty
            //       headers to allocate...
            //          - eliza, 07/02/2017
            let mut headers = [EMPTY_HEADER; MAX_HEADERS];
            let mut response = Response::new(&mut headers);
            future::result(
                response.parse(&bytes)
                    .map(|_| response)
                    .map_err(|e| Error::new(ErrorKind::Other, e)))
        });

    // check if the response passes this test...
    let status = response.map(T::check);

    // ...and we're done!
    status
}
```

Backtrace: https://gist.github.com/hawkw/f69c536918266225c70402458ad867f2

**Comment by PlasmaPower** [comment] 2017-07-03 16:37
@hawkw I'm assuming either `Status` or `Error` is a typedef to a borrowed type? If you explicitly specify the borrow lifetimes, then it shouldn't ICE (as a temporary fix).

**Comment by m4b** [comment] 2017-07-03 18:14
@PlasmaPower Interesting, I tried your example, and it doesn't ICE, but it won't compile with:

```rust
fn derp<'a> (cfg: &'a ControlFlowGraph) -> impl Iterator<Item = &'a ControlFlowTarget> {
    cfg.vertices().filter_map(|vx| cfg.vertex_label(vx))
}
```

```
cargo check
   Compiling panopticon-core v0.16.0 (file:///home/m4b/projects/panopticon/core)
error[E0564]: only named lifetimes are allowed in `impl Trait`, but `` was found in the type `std::iter::FilterMap<std::iter::Map<std::collections::hash_map::Keys<'_, panopticon_graph_algos::adjacency_list::AdjacencyListVertexDescriptor, function::ControlFlowTarget>, fn(&panopticon_graph_algos::adjacency_list::AdjacencyListVertexDescriptor) -> panopticon_graph_algos::adjacency_list::AdjacencyListVertexDescriptor>, [closure@function.rs:448:31: 448:56 cfg:&&'a panopticon_graph_algos::AdjacencyList<function::ControlFlowTarget, il::Guard>]>`
   --> function.rs:447:44
    |
447 | fn derp<'a> (cfg: &'a ControlFlowGraph) -> impl Iterator<Item = &'a ControlFlowTarget> {
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0564]: only named lifetimes are allowed in `impl Trait`, but `` was found in the type `std::iter::FilterMap<std::iter::Map<std::collections::hash_map::Keys<'_, panopticon_graph_algos::adjacency_list::AdjacencyListVertexDescriptor, function::ControlFlowTarget>, fn(&panopticon_graph_algos::adjacency_list::AdjacencyListVertexDescriptor) -> panopticon_graph_algos::adjacency_list::AdjacencyListVertexDescriptor>, [closure@function.rs:448:31: 448:56 cfg:&&'a panopticon_graph_algos::AdjacencyList<function::ControlFlowTarget, il::Guard>]>`
   --> function.rs:447:44
    |
447 | fn derp<'a> (cfg: &'a ControlFlowGraph) -> impl Iterator<Item = &'a ControlFlowTarget> {
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

but this may be an unrelated error, haven't thought too much about it, though the error message doesn't really make sense to me

**Comment by m4b** [comment] 2017-07-03 18:16
Like this just seems still symptomatic of the bug:

```
only named lifetimes are allowed in `impl Trait`, but ``
```

the double tick after but has nothing in it...

Note: `ControlFlowGraph` is a typedef, and `ControlFlowtarget` is a regular enum (with no typedefs)

**Comment by PlasmaPower** [comment] 2017-07-03 18:20
@m4b Do `ControlFlow` or `ControlFlowtarget` include borrowing or references in their definitions? There may be additional implicit borrowing.

**Comment by m4b** [comment] 2017-07-03 18:22
`ControlFlowTarget` has a Cow.

```rust
/// Node of the function graph.
#[derive(Serialize,Deserialize,Debug,Clone)]
pub enum ControlFlowTarget {
    /// A basic block
    Resolved(BasicBlock),
    /// An unresolved indirect jump
    Unresolved(Rvalue),
    /// An error occured while disassembling
    Failed(u64, Cow<'static, str>),
}

/// Graph of basic blocks and jumps
pub type ControlFlowGraph = AdjacencyList<ControlFlowTarget, Guard>;
```

```rust
#[derive(Clone, Debug, Serialize,Deserialize)]
pub struct AdjacencyList<N, E> {
    vertex_labels: HashMap<AdjacencyListVertexDescriptor, N>,
    edge_labels: HashMap<AdjacencyListEdgeDescriptor, E>,
    out_edges: HashMap<AdjacencyListVertexDescriptor, Vec<AdjacencyListEdgeDescriptor>>,
    in_edges: HashMap<AdjacencyListVertexDescriptor, Vec<AdjacencyListEdgeDescriptor>>,
    edges: HashMap<AdjacencyListEdgeDescriptor, (AdjacencyListVertexDescriptor, AdjacencyListVertexDescriptor)>,
    next_edge: AdjacencyListEdgeDescriptor,
    next_vertex: AdjacencyListVertexDescriptor,
}
```

**Comment by PlasmaPower** [comment] 2017-07-03 18:28
Interesting, I think that should compile (but it fails, probably due to the `'static`). It would appear that lifetime handling with `impl Trait` has a number of problems.

**Comment by PlasmaPower** [comment] 2017-07-03 19:54
Oh wait, nevermind. The error message is deceiving, but here's the solution:

```rust
fn derp<'a> (cfg: &'a ControlFlowGraph) -> impl Iterator<Item = &'a ControlFlowTarget> {
    cfg.vertices().filter_map(move |vx| cfg.vertex_label(vx))
}
```

It needs to be a move closure to work.

**Comment by m4b** [comment] 2017-07-03 19:59
Ah yea of course! The error message definitely is totally wrong though, hehe :)

There's still some work to do for lifetimes and this feature I think

**Comment by PlasmaPower** [comment] 2017-07-03 20:06
We could name the implicit lifetime as the closure, instead of just ``. Past that, we couldn't make the error message better without resolving implicit lifetimes for `impl Trait`, which would ironically obsolete the error in the first place.

We could add in a `help:` note specifically for closures, though.

**Comment by m4b** [comment] 2017-07-03 20:15
Yea the error message needs to be improved.  Ftr, this will compile:

```rust
fn derp<'a> (cfg: &'a ControlFlowGraph) -> impl Iterator<Item = &'a ControlFlowTarget> + 'a {
    cfg.vertices().filter_map(move |vx| cfg.vertex_label(vx))
}
```

(note the additional `'a` requirement).

This is exactly the same definition as the Boxed version I wrote, because I didn't want to write the type, so this is a perfect usecase for `impl Trait`.

Consequently, I think this is as @PlasmaPower you suggest, a problem with lifetime inference.

However, @hawkw example is a bit puzzling, because, afaik, you can't typedef a ref unless the lifetime is  also exposed in the typedef, _or_ it's `'static` - so this could be combination of lifetimes + typedefs + static?

**Comment by PlasmaPower** [comment] 2017-07-03 23:47
> I think the error message for impl Trait should be mutatis mutandis basically the same

As I said earlier,

> Past that, we couldn't make the error message better without resolving implicit lifetimes for impl Trait, which would ironically obsolete the error in the first place

The best we can do now is to identify the currently unnamed lifetime. The compiler doesn't currently know the constraints on the lifetime, so it can't output a message similar to the one above (generated when using a box).

**Comment by PlasmaPower** [comment] 2017-07-04 21:14
Interesting. If run with `RUST_LOG=debug`, the compiler gives a different error:

```
error[E0391]: unsupported cyclic reference between types/traits detected
 --> impl-trait-lifetime-inference.rs:8:32
  |
8 | fn example(input: &Example) -> impl Iterator<Item = &Example> {
  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cyclic reference
  |
note: the cycle begins when processing `example::{{impl-Trait}}`...
 --> impl-trait-lifetime-inference.rs:8:32
  |
8 | fn example(input: &Example) -> impl Iterator<Item = &Example> {
  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which then again requires processing `example::{{impl-Trait}}`, completing the cycle.

```

**Comment by pietroalbini** [comment] 2018-04-03 09:51
This seems to be fixed now (the snippet in https://github.com/rust-lang/rust/issues/43021#issuecomment-312681415 works fine on the latest nightly). Closing.

**Closed by pietroalbini** 2018-04-03 09:51 UTC
Labels: A-impl-trait, C-bug, I-ICE
