### ISSUE TITLE
enum discriminant should be picked to make enum `NonZero`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#43537] opened 2017-07-29 05:44 UTC
I would expect the following program to demonstrate that `Test` is `NonZero`:
```rust
#![allow(dead_code)]
use std::mem;

enum Test { A(i32), B(i32) }

fn main() {
    println!("{} {}", mem::size_of::<Test>(), mem::size_of::<Option<Test>>());
}
```
The reasoning is that `Test` itself can never use the `NonZero` discriminant optimization itself, so it should use discriminants 1 and 2 to guarantee that it is itself never all-zero. This should be backwards-compatible as AFAIK safe code cannot observe, and unsafe code is not allowed to rely on, the concrete values of the discriminants.

(Not sure if an issue is enough for this or if it needs an RFC, so I started with the simpler-to-do one. ;)

**Comment by kennytm** [comment] 2017-07-29 10:40
I don't think it should use the NonZero trick, but "[compress nested enum variant IDs](https://github.com/rust-lang/rfcs/issues/1230#issuecomment-171149132)" i.e.

```rust
    Option<Test>
==  enum {
        Some(enum {
            A(i32),   // <- discriminant = 0
            B(i32),   // <- discriminant = 1
        }),
        None,  // <- discriminant = 2
    }

**Comment by eddyb** [comment] 2017-07-29 19:36
Closing as duplicate of rust-lang/rfcs#1230.

**Closed by eddyb** 2017-07-29 19:37 UTC
