### ISSUE TITLE
Content of *.d file doesn’t match actual outputs

### ISSUE THREAD

**Issue by bzEq** [rust-lang/rust#110589] opened 2023-04-20 09:33 UTC
For code
```rust
// foo.rs
pub fn foo() {}
```
compiled with `rustc --crate-type=lib foo.rs  --emit=metadata,dep-info,link`, we have output files
```
foo.d  foo.rs  libfoo.rlib  libfoo.rmeta
```
`libfoo.rmeta` doesn't match what's inside `foo.d`
```
foo.rmeta: foo.rs

libfoo.rlib: foo.rs

foo.d: foo.rs

foo.rs:
```
This can be reproduced by
```
rustc 1.71.0-nightly (39c6804b9 2023-04-19)
binary: rustc
commit-hash: 39c6804b92aa202369e402525cee329556bc1db0
commit-date: 2023-04-19
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

**Comment by bjorn3** [comment] 2023-04-20 09:41
I think https://github.com/rust-lang/rust/blob/23a76a8ab5f7b29a1eb7aca5f3e4c4a9b866d5b7/compiler/rustc_session/src/config.rs#L689 is wrong for the metadata output.

**Comment by ehuss** [comment] 2023-04-20 14:49
I believe this is a duplicate of #68839.

**Comment by bjorn3** [comment] 2023-04-21 09:22
Looks like it.

**Closed by bjorn3** 2023-04-21 09:22 UTC
Labels: A-metadata, T-compiler, C-bug
