### ISSUE TITLE
Compiler thinks variable needs to be mutable when getting an owned slice

### ISSUE THREAD

**Issue by grantslatton** [rust-lang/rust#46265] opened 2017-11-25 20:38 UTC
https://play.rust-lang.org/?gist=be40620b431766ae921d89b3e2c0b9e5&version=nightly

    fn main() {
        let vec_a: Vec<u32> = vec![];
        let mut vec_b: Vec<u32> = vec![];
        vec_b.append(&mut vec_a[..].to_owned());
    }

    error[E0596]: cannot borrow immutable local variable `vec_a` as mutable
     --> src/main.rs:4:23
      |
    2 |     let vec_a: Vec<u32> = vec![];
      |         ----- consider changing this to `mut vec_a`
    3 |     let mut vec_b: Vec<u32> = vec![];
    4 |     vec_b.append(&mut vec_a[..].to_owned());
      |                       ^^^^^ cannot borrow mutably

**Comment by jonas-schievink** [comment] 2017-11-25 21:17
This is correct - you aren't getting an owned slice, you're getting a `&mut [u32]`, a mutable slice. Since the data the slice points to is owned by `vec_a`, you can only mutably refer to it if you have a mutable reference to `vec_a` itself.

**Comment by jonas-schievink** [comment] 2017-11-25 21:18
You can also use `&vec_a` instead of `&mut vec_a`, since the mutability isn't needed here (only `vec_b` needs to be mutable, since you append to it).

**Comment by grantslatton** [comment] 2017-11-25 21:26
@jonas-schievink but as far as I know, I getting an immutable slice. `&mut` should apply to the `Vec<u32>` returned by `to_owned`. Additional parentheses to clarify this don't help:

https://play.rust-lang.org/?gist=266b22ca7d45c52200c068fa34bb5b61&version=nightly

    fn main() {
        let vec_a: Vec<u32> = vec![];
        let mut vec_b: Vec<u32> = vec![];
        vec_b.append(&mut (vec_a[..].to_owned()));
    }

In the above code, `vec_a[..]` should be a `&[u32]`, right? And `(vec_a[..].to_owned())` should be a `Vec<u32>`, right? Why can't I get a `&mut` of the owned `Vec`?

And why does splitting it into 2 lines work?

https://play.rust-lang.org/?gist=1600e7488b3de8e7ed489828af1c6727&version=nightly

    fn main() {
        let vec_a: Vec<u32> = vec![];
        let mut vec_b: Vec<u32> = vec![];
        let mut owned = vec_a[..].to_owned();
        vec_b.append(&mut owned);
    }

The above code compiles, but all I've done is introduce an intermediate variable `owned`.

**Comment by grantslatton** [comment] 2017-11-25 21:34
@jonas-schievink 

> You can also use &vec_a instead of &mut vec_a, since the mutability isn't needed here (only vec_b needs to be mutable, since you append to it).

`append`s type signature is `fn append(&mut self, other: &mut Vec<T>)`

See https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append

**Comment by bluss** [comment] 2017-11-25 21:40
The compiler is calling IndexMut here, and that's wrong. `vec_a[..].to_vec()` only needs `Index`

**Comment by jonas-schievink** [comment] 2017-11-25 22:07
Ah, right, that's an actual bug, of course: https://github.com/rust-lang/rust/issues/28935

**Comment by bluss** [comment] 2017-11-25 22:21
Thanks both! This is a duplicate of #28935 and it seems like an exact match.

**Closed by bluss** 2017-11-25 22:21 UTC
