### ISSUE TITLE
Miscompilation in lalrpop 0.19.6 causes LLVM error in nightly 2021-08-15/16

### ISSUE THREAD

**Issue by ThePuzzlemaker** [rust-lang/rust#88102] opened 2021-08-17 02:12 UTC
### Code

Create an empty binary project, and add `lalrpop = "=0.19.6"` to the `Cargo.toml`. No additional code is necessary.

I expected to see this happen: Program builds.

Instead, this happened: Compiler crashes:
```shell
$ cargo +nightly build
   ... snip ...
   Compiling lalrpop v0.19.6
Basic Block in function '_ZN7lalrpop3tok9Tokenizer10take_until17h0e5828b8a9330eebE' does not have terminator!
label %9
in function _ZN7lalrpop3tok9Tokenizer10take_until17h0e5828b8a9330eebE
LLVM ERROR: Broken function found, compilation aborted!
error: could not compile `lalrpop`
```

This is reproducible with a clean build environment. (I originally spotted this in my CI and was luckily able to reproduce it on my laptop). I apologize that I cannot give a better MCVE at the moment.

### Version it worked on

It most recently worked on: 
Note that this is `nighty-2021-08-14`, I'm unsure why it says 2021-08-13.
`rustc --version --verbose`:
```
rustc 1.56.0-nightly (5a19ffe1c 2021-08-13)
binary: rustc
commit-hash: 5a19ffe1c2b99d9e09706cc286aad1ec0868eddb
commit-date: 2021-08-13
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Version with issue

This issue also occurs with nightly-2021-08-16.

Note that this is `nightly-2021-08-15`, as with the previous I'm unsure why it says 2021-08-14.
`rustc --version --verbose`:
```
rustc 1.56.0-nightly (8007b506a 2021-08-14)
binary: rustc
commit-hash: 8007b506ac5da629f223b755f5a5391edd5f6d01
commit-date: 2021-08-14
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

I cannot currently bisect further at this point.

@rustbot modify labels: +T-compiler +requires-nightly +A-LLVM +C-bug +E-needs-bisection

**Comment by jamestmartin** [comment] 2021-08-17 04:55
I was able to reproduce this bug with a toolchain that reports itself correctly.

```
$ rustc +nightly --version --verbose
rustc 1.56.0-nightly (0035d9dce 2021-08-16)
binary: rustc
commit-hash: 0035d9dcecee49d1f7349932bfa52c05a6f83641
commit-date: 2021-08-16
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

**Comment by SNCPlay42** [comment] 2021-08-17 07:39
Duplicate of #88043?

**Closed** 2021-08-17 17:48 UTC
Labels: A-LLVM, T-compiler, C-bug, E-needs-bisection, requires-nightly
