### ISSUE TITLE
ICE when passing format!() to doc_comment!()

### ISSUE THREAD

**Issue by DoubleHyphen** [rust-lang/rust#66854] opened 2019-11-28 22:57 UTC
[Example code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=af9a487e0ff60cc5cf81efb0aac42769):

```
macro_rules! doc_comment {
    ($x:expr) => {
        #[doc = $x]
        extern {
}};}

macro_rules! some_macro {
    ($t1: ty) => {
        doc_comment!{format!("{coor}", coor = stringify!($t1)).as_str()
}}}

fn main() {
    some_macro!(u8);
}
```

Expected result: The compiler does not crash.
Actual result: The compiler crashes, and asks for the crash to be reported as a bug.
Workaround: Using concat!() instead of format!()
Likely cause: concat!() returns a &str, whereas format!() returns a String.

**Comment by jonas-schievink** [comment] 2019-11-28 23:02
Duplicate of https://github.com/rust-lang/rust/issues/66804

**Closed by jonas-schievink** 2019-11-28 23:02 UTC
