### ISSUE TITLE
Destructuring boxes into multiple mutable references seems broken

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#30104] opened 2015-11-29 16:13 UTC
This fails with "cannot mutably borrow more than once" errors

``` rust
fn push(mut node: Box<(i32, i32)>) {
    let (ref mut left, ref mut right) = *node;
}
```

Same here:

``` rust
fn push(mut node: Box<(i32, i32)>) {
    let box (ref mut left, ref mut right) = node;
}
```

This works:

``` rust
fn push(mut node: Box<(i32, i32)>) {
    let (ref mut left, ref mut right) = *&mut *node;
}
```

This also works:

``` rust
fn push(node: &mut (i32, i32)) {
    let (ref mut left, ref mut right) = *node;
}
```

Same behavior with structs instead of tuples. Boxes are weird, destructuring into mutable borrows is weird, so I have no idea what is going on there.

**Comment by jethrogb** [comment] 2016-02-16 06:02
#![feature(box_patterns)]

box pattern

There. Now other people can find this bug.

**Comment by aidanhs** [comment] 2016-06-02 00:43
More keywords: match, if let.
(no, they don't work either)

Two workarounds are to either a) use `*&mut *x` or b) bring `std::ops::DerefMut` in and use `*x.deref_mut()`:
```
use std::ops::DerefMut;
fn main() {
    let mut x = Box::new((1, 2));
    { let (ref mut a, ref mut b) = *&mut *x; }
    { let (ref mut a, ref mut b) = *x.deref_mut(); }
}
```

**Comment by jonhoo** [comment] 2017-10-31 01:09
Is this a dupe of #16223?

**Comment by Mark-Simulacrum** [comment] 2017-10-31 02:15
I don't think so, but am uncertain. Might have the same underlying cause, though -- hard to tell.

**Comment by arielb1** [comment] 2017-10-31 09:55
This is defined by RFC rust-lang/rfcs#130

**Comment by jethrogb** [comment] 2017-10-31 21:48
I don't fully understand it, but that RFC sounds like it was intended to make Box *more* like other types. This issue is pointing out a discrepancy between `Box` and other types.

e.g., compare the code from the original issue with
```
fn push(mut node: ::std::panic::AssertUnwindSafe<(i32, i32)>) {
    let (ref mut left, ref mut right) = *node;
}
```
This sounds to me like `Box<T>` is *still* getting special treatment and the RFC has not been fully implemented yet.

**Comment by arielb1** [comment] 2017-11-01 11:24
@jethrogb 

So the RFC was just poorly-defined. I think the solution to mutating in `match` should be able to be extended to handle this.

**Comment by shepmaster** [comment] 2018-05-08 20:47
3 of these 4 cases fail with Rust 1.25.0. The good news is that *with NLL*, all 4 work! 🎉 

```rust
use std::ops::{Deref, DerefMut};

// Fails
fn smart_two_field(v: &mut Wrap<(i32, i32)>) {
    let _a = &mut v.0;
    let _b = &mut v.1;
}

fn smart_destructure(v: &mut Wrap<(i32, i32)>) {
    let (ref mut _head, ref mut _tail) = **v;
}

// Fails
fn box_two_field(v: &mut Box<(i32, i32)>) {
    let _a = &mut v.0;
    let _b = &mut v.1;
}

// Fails
fn box_destructure(v: &mut Box<(i32, i32)>) {
    let (ref mut _head, ref mut _tail) = **v;
}

// My own smart pointer
struct Wrap<T>(T);

impl<T> Deref for Wrap<T> {
    type Target = T;
    fn deref(&self) -> &T {
        &self.0
    }
}

impl<T> DerefMut for Wrap<T> {
    fn deref_mut(&mut self) -> &mut T {
        &mut self.0
    }
}

fn main() {}
```

**Closed** 2019-04-22 15:06 UTC
Labels: A-borrow-checker, C-bug, E-needstest, NLL-fixed-by-NLL
