### ISSUE TITLE
Cannot use associated const to specify static array length

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#52070] opened 2018-07-05 04:37 UTC
pub trait Foo {
        const SIZE: usize;
        fn whatever() {
            // compiles fine
            let _x = [Self::SIZE, 3usize];
            // fails with error[E0599]: no associated item named `SIZE` found for type `Self` in the current scope
            let _y = [3usize; Self::SIZE];
        }
    }

This looks like a bug to me - I believe both rows should compile just fine.
It exists in both stable and nightly.

**Comment by vitalyd** [comment] 2018-07-30 13:04
This is essentially a dupe of https://github.com/rust-lang/rust/issues/43408

**Closed** 2019-01-28 11:53 UTC
Labels: A-associated-items, A-const-eval

**Comment by tarcieri** [comment] 2023-08-14 16:05
#60551 is a similar issue specific to associated constants
