### ISSUE TITLE
ICE during building rocket.rs as a dependency

### ISSUE THREAD

**Issue by krojew** [rust-lang/rust#81637] opened 2021-02-01 19:12 UTC
### Code

Available at https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/logger.rs:94:68 - revision c24f15c18f02319be83af4f3c1951dc220b52c5e

### Meta

```
note: rustc 1.51.0-nightly (0e63af5da 2021-01-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
```

### Error output

```
error: internal compiler error: failed to process buffered lint here
  --> /home/runner/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/logger.rs:94:68
   |
94 | macro_rules! info_ { ($($args:expr),+) => { log_!(info: $($args),+); }; }
   |                                                                    ^
   | 
  ::: /home/runner/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/server.rs:85:23
   |
85 |             Ok(()) => info_!("{}", Paint::green("Response succeeded.")),
   |                       ------------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
  --> /home/runner/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/logger.rs:92:70
   |
92 | macro_rules! error_ { ($($args:expr),+) => { log_!(error: $($args),+); }; }
   |                                                                      ^
   | 
  ::: /home/runner/.cargo/git/checkouts/rocket-8bf16d9ca7e90bdc/c24f15c/core/lib/src/server.rs:86:23
   |
86 |             Err(e) => error_!("Failed to write response: {:?}.", e),
   |                       --------------------------------------------- in this macro invocation
   |
   = note: delayed at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
0: rust_begin_unwind
             at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-01 19:26
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-01 19:26 UTC
Labels: C-bug, I-ICE, T-compiler
