### ISSUE TITLE
Use unqualified names in type errors when possible

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#19792] opened 2014-12-13 00:57 UTC
> error: mismatched types: expected `core::option::Option<alloc::arc::Arc<std::collections
> ::hash::map::HashMap<&'static str, alloc::arc::Arc<collections::vec::Vec<item::Item>>>>>`,
> found `core::option::Option<alloc::arc::Arc<std::collections::hash::map::HashMap<&str,
> alloc::arc::Arc<collections::vec::Vec<&generator::Job>>>>>`

would be much more readable as

> error: mismatched types: expected `Option<Arc<HashMap<&'static str, Arc<Vec<Item>>>>>`,
> found `Option<Arc<HashMap<&str, Arc<Vec<&Job>>>>>`

One possibility is to use the names in scope where the type error appears.  In any event, we should make sure none of the unqualified names in a given error are ambiguous.

**Comment by freebroccolo** [comment] 2015-03-03 20:04
cc me

**Comment by steveklabnik** [comment] 2016-03-24 21:11
Triage: no change.

**Comment by estebank** [comment] 2017-09-21 19:37
Duplicate of https://github.com/rust-lang/rust/issues/19792

**Closed by estebank** 2017-09-21 19:37 UTC
Labels: A-diagnostics, C-enhancement, T-compiler
