### ISSUE TITLE
Reference not updated to describe disjoint capture in closures

### ISSUE THREAD

**Issue by pali6** [rust-lang/rust#97451] opened 2022-05-27 12:41 UTC
The [Capture Modes](https://doc.rust-lang.org/stable/reference/types/closure.html#capture-modes) section of the Rust reference seems to predate the implementation of the [capture disjoint fields RFS](https://github.com/rust-lang/rfcs/blob/master/text/2229-capture-disjoint-fields.md) and says that composite types are always captured entirely which is no longer the case.

---
@rustbot modify labels: A-docs

**Comment by pali6** [comment] 2022-05-27 12:50
Whoops, I guess I should have made this in https://github.com/rust-lang/reference instead. Apologies, I was not aware it's a separate repo.

**Comment by ehuss** [comment] 2022-05-27 14:04
Thanks for the report!  There is open work at https://github.com/rust-lang/reference/pull/1059 to add the new information. Closing as a duplicate of https://github.com/rust-lang/reference/issues/1066.

**Closed by ehuss** 2022-05-27 14:04 UTC
Labels: A-docs
