### ISSUE TITLE
Fix invalid primitive's methods link generation in core and alloc crate

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#89628] opened 2021-10-07 14:04 UTC
There are some broken links when generating primitives' methods using intra-doc links from the `core` and `alloc` crate. The list is [here](https://github.com/rust-lang/rust/pull/87073/files#diff-e2299a56a57d89081c522ddf93fad2f60ca4bf86e6b5a9f902b85e4231cec9f2R46-R53). It was introduced in #87073. At the time we merged because the change was really important and far outweighed this problem. But it would be nice to finish it. :)

**Comment by jyn514** [comment] 2021-10-07 15:46
@GuillaumeGomez that's what broke it in the first place. Relative links can never work for both the original item and the re-export.

**Comment by jyn514** [comment] 2021-10-30 18:43
I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/32130, I don't think we need multiple issues tracking the linkcheck exceptions.

**Closed by jyn514** 2021-10-30 18:43 UTC
Labels: T-rustdoc, C-bug, A-intra-doc-links
