### ISSUE TITLE
rustc_args_required_const on parameter not treated as constant in argument

### ISSUE THREAD

**Issue by nlewycky** [rust-lang/rust#63020] opened 2019-07-26 19:10 UTC
This implementation of wasm32's v8x16.shuffle intrinsic does not build (add to stdarch/crates/core_arch/src/wasm32/simd128.rs):

```
#[inline]
#[cfg(not(only_node_compatible_functions))]
#[cfg_attr(test, assert_instr("v8x16.shuffle"))]
#[rustc_args_required_const(2)]
pub fn v8x16_shuffle(a: v128, b: v128, idx: [u32; 16]) -> v128 {
    unsafe { transmute(simd_cast::<i8x16, v128>(simd_shuffle16(a.as_i8x16(), b.as_i8x16(), idx))) }
}
```

with the error `error[E0526]: shuffle indices are not constant`. I expected that `rustc_args_required_const(2)` would be sufficient to make the argument to `simd_shuffle16` const. It looks like this is supposed to happen in `src/librustc_mir/transform/qualify_consts.rs`:
```
            if self.mode != Mode::Static && self.mode != Mode::Const {
                let constant_args = callee_def_id.and_then(|id| {
                    args_required_const(self.tcx, id)
                }).unwrap_or_default();
                for (i, arg) in args.iter().enumerate() {
                    if !(is_shuffle && i == 2 || constant_args.contains(&i)) {
                        continue;
                    }
```
The arg is indeed marked with args_required_const (that function checks for `sym::rustc_args_required_const` on the given `DefId`). I'm not sure why this isn't already working.

**Comment by oli-obk** [comment] 2019-07-31 12:24
That's intended. Please use const generics if you want to have const arguments. The attribute only exists for the basic SIMD instructions, not for wrappers or abstractions

**Comment by Mark-Simulacrum** [comment] 2019-08-10 02:22
Closing as won't fix/intended behavior.

**Closed by Mark-Simulacrum** 2019-08-10 02:22 UTC
Labels: A-const-eval, A-simd, C-bug, T-compiler
