### ISSUE TITLE
Unhelpful "cannot infer type" error for ? in async block with unclear Result Err type

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#77880] opened 2020-10-13 00:02 UTC
Minimal reproduction:

```rust
fn may_error() -> Result<(), ()> { unimplemented!() }

fn main() {
    async {
        may_error()?;
        Ok(())
    };
}
```

1.47.0 gives the following error:

```
error[E0282]: type annotations needed
 --> src/main.rs:5:9
  |
5 |         may_error()?;
  |         ^^^^^^^^^^^^ cannot infer type
```

Nightly gives a *marginally* more useful error:

```
error[E0282]: type annotations needed
 --> src/main.rs:5:20
  |
5 |         may_error()?;
  |                    ^ cannot infer type
```

I would expect an explanation of what type precisely couldn't be inferred, along with a pointer to the containing async block as the thing whose type couldn't be inferred.

`rustc --version --verbose` (for 1.47.0):
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```

`rustc --version --verbose` (for nightly):
```
rustc 1.49.0-nightly (c71248b70 2020-10-11)
binary: rustc
commit-hash: c71248b70870960af9993de4f31d3cba9bbce7e8
commit-date: 2020-10-11
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by jyn514** [comment] 2020-10-13 01:28
[Turning this into a closure](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b73cd14c273d0100b0c0a421b1b8151a) gives a more helpful error:
```
error[E0282]: type annotations needed for the closure `fn() -> std::result::Result<(), _>`
 --> src/lib.rs:5:9
  |
5 |         may_error()?;
  |         ^^^^^^^^^^^^ cannot infer type
  |
help: give this closure an explicit return type without `_` placeholders
  |
4 |     let g = || -> std::result::Result<(), _> {
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by joshtriplett** [comment] 2020-10-13 02:21
@jyn514 Yeah, I found that several different code changes led to better errors.

I'd guess *part* of the issue is that there's no stable way to add a type annotation directly to an async block.

**Comment by hameerabbasi** [comment] 2020-10-16 08:30
I'm willing to take a shot at this.

@rustbot claim

**Comment by tmandry** [comment] 2020-12-03 19:39
@hameerabbasi Are you still planning to work on this?

**Comment by hameerabbasi** [comment] 2020-12-03 19:50
Yes, I am, it fell off my radar.

**Comment by hameerabbasi** [comment] 2020-12-06 17:01
Ah, I recall what happened here. Here's the Zulip stream: https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/Picking.20up.20issue.20.20.2377880

Basically, I wasn't familiar enough with the internals of the compiler to fix this, unfortunately.

**Comment by hameerabbasi** [comment] 2020-12-06 17:04
I'm willing to work on this, but I'll unassign myself so it's more discoverable.

@rustbot release-assignment

**Comment by wabain** [comment] 2020-12-20 19:37
It looks like there are a few factors here. One is that `impl Trait` bindings can't have types annotated explicitly. With `#![feature(impl_trait_in_bindings)]` we can get [at least some details](https://github.com/rust-lang/rust/blob/2ad5292aea6328113b55968b4322528d48261316/src/test/ui/inference/cannot-infer-async-enabled-impl-trait-bindings.stderr) in the error, although not as much as would be desirable:

```
error[E0282]: type annotations needed for `impl Future`
  --> $DIR/cannot-infer-async-enabled-impl-trait-bindings.rs:13:20
   |
LL |     let fut = async {
   |         --- consider giving `fut` the explicit type `impl Future`, with the type parameters specified
LL |         make_unit()?;
   |                    ^ cannot infer type
```

The other is that the diagnostics code is oriented around identifying the type of a local variable or function parameter which can be annotated, even though for closures other annotations might be suggested, like specifying the return type. It's possible to get [a similar uninformative error message](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0130830f7c43a36d64eab260ae640be2) with a closure:

```rust
fn may_error() -> Result<(), ()> { Err(()) }

fn consume_closure<T, F: Fn() -> T>(_: F) {}

fn f() {
    consume_closure(|| {
        may_error()?;
        Ok(())
    });
}
```

Gives:

```
error[E0282]: type annotations needed
 --> src/lib.rs:7:20
  |
7 |         may_error()?;
  |                    ^ cannot infer type
```

If the closure is assigned to a local variable before being passed to `consume_closure`, the error is much better:

```
error[E0283]: type annotations needed for the closure `fn() -> std::result::Result<(), _>`
  --> src/lib.rs:14:20
   |
14 |         may_error()?;
   |                    ^ cannot infer type
   |
   = note: cannot satisfy `_: From<()>`
   = note: required by `from`
help: give this closure an explicit return type without `_` placeholders
   |
13 |     let v = || -> std::result::Result<(), _> {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm interested in trying to clean this up a bit. @rustbot claim.

**Comment by wabain** [comment] 2020-12-28 23:16
I’d assumed fixing this would involve making the diagnostics aware of generators, but I can’t actually see how much that could be leveraged for async blocks. After looking at this some more I can think of two things we can do here, neither of which are actually specific to async blocks.

First, I think it could be helpful to have an additional note in general when inference fails for the `?` operator return, explaining the `From` conversion applied; I think this is probably a fairly common source of confusion for people learning Rust. We can print the partially inferred `From` bound which needs to be satisfied. (I haven’t looked at exactly how to implement this, but I’m imagining that we’d check the desguaring kind for the primary span and then walk the HIR to recover the pre-coercion type, in this case the return of `may_error()`.) There might be some work needed to keep it from being too redundant or verbose (or maybe too terse, if the error type of the value `?` is invoked on isn't inferred) but I think it would be doable.

Where possible, we can also suggest annotating another expression which would disambiguate the return type. This is actually already supported in some cases, like if a Result returned without `?`-coercion is first bound to a local variable, or if the error type occurs as a parameter in a [method](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3ceb29d79b4f59c4cac4445303fd0ab7) (but not function!) call. It should be possible to give a similar suggestion to annotate an `Ok` constructor with the error type.

Putting the suggestions together, the output for the initial example in this issue could be something like:

```
error[E0282]: type annotations needed
 --> src/main.rs:5:21
  |
5 |         may_error()?;
  |                    ^ cannot infer type of `?` return
  |
  = note: The `?` operator can convert the error value to any type which implements `From<std::io::Error>`
help: consider specifying the type arguments when constructing `std::result::Result::Ok`
  |
6 |         Ok::<T, E>(())
  |           ^^^^^^^^
```

**Comment by wabain** [comment] 2020-12-28 23:27
It looks like there are some good [mismatched type diagnostics](https://github.com/rust-lang/rust/blob/2987785df3d46d5ff144a5c67fbb8f5cca798d78/src/test/ui/try-block/try-block-bad-type.stderr#L7) to piggyback off of.

**Comment by tmandry** [comment] 2020-12-29 01:43
Both of these suggestions sound really nice, I hope we can implement them!

**Comment by tmandry** [comment] 2021-01-28 19:57
Triage: nightly now gives

```
error[E0282]: type annotations needed
 --> src/main.rs:5:20
  |
5 |         may_error()?;
  |                    ^ cannot infer type of error for `?` operator
  |
  = note: `?` implicitly converts the error value into a type implementing `From<()>`
```

thanks to #80517 (thanks @wabain)! I think this means the issue is fixed.

**Closed by tmandry** 2021-01-28 19:57 UTC
Labels: A-async-await, A-diagnostics, A-inference, AsyncAwait-Triaged, C-bug, D-terse, E-help-wanted, E-medium, E-mentor, T-compiler
