### ISSUE TITLE
"Renaming of the library `C` was specified" error only on nightly

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#38850] opened 2017-01-05 16:23 UTC
This appears to be caused by a change in https://github.com/rust-lang/rust/issues/37403.

This appears to be causing a breaking change on nightly from stable. I'm compiling an (unreleased) FFI library that handles the linking to certain static libraries in a build script (so the `extern "C"` block is unannotated). It depends on the libc crate. Other than that it does nothing out of the ordinary. I'm compiling using the windows msvc x64 toolchain. On nightly, but not on stable, I get the error message:

```text
error: renaming of the library `C` was specified, however this crate contains no #[link(...)] attributes referencing this library.
```

Is this library `C` referring to libc? My crate has an entirely unrelated name.

**Comment by dylanede** [comment] 2017-01-05 16:25
cc @vadimcn

**Comment by vadimcn** [comment] 2017-01-05 17:49
@dylanede, are you putting the full library path behind `-l` by any chance? 
(i.e. `-l C:\foo\bar\baz.lib`)

**Comment by dylanede** [comment] 2017-01-09 10:02
Ah, yes I am. The path is constructed using the `CARGO_MANIFEST_DIR` environment variable. The lib is stored in a crate subdirectory.

**Comment by vadimcn** [comment] 2017-01-10 06:50
Hmm, I was under impression that `-l` takes just the library name.  
@alexcrichton, how is `-l` supposed to work?

**Comment by alexcrichton** [comment] 2017-01-10 19:36
@vadimcn that was the intention, yes, but it looks like it works with paths as well I guess?

**Comment by alexcrichton** [comment] 2017-01-10 19:38
I believe the relevant PR (https://github.com/rust-lang/rust/pull/37973) is on beta, so I'm going to tag this as a stable-to-beta regression.

**Comment by vadimcn** [comment] 2017-01-10 19:58
@alexcrichton: We have code in rustc that [assumes that it's given just the library name](https://github.com/rust-lang/rust/blob/7bffede97cf58f7159e261eac592f9cf88ce209d/src/librustc_trans/back/linker.rs#L112).  If you invoke `ld -l/foo/libbar.a`, it won't find the library.   The proper way is this: `ld -L/foo -lbar`.  

The full path works with [MSVC](https://github.com/rust-lang/rust/blob/7bffede97cf58f7159e261eac592f9cf88ce209d/src/librustc_trans/back/linker.rs#L357) (if you omit the `.lib` extension), but only by accident.

**Comment by alexcrichton** [comment] 2017-01-11 23:55
The tools team discussed this during triage today and the conclusion was that this interpretation of `-l` was an unintended consequence and the current interpretation is working as intended. As a result I'm going to close this, but @dylanede if you need help updating your code please just let me know and I'd be more than willing to help out!

**Closed by alexcrichton** 2017-01-11 23:55 UTC
Labels: regression-from-stable-to-beta, T-tools

**Comment by hone** [comment] 2017-08-09 03:07
I'm not sure if this is related, but I'm seeing the same error message while playing around with [neon](https://github.com/neon-bindings/neon). This only happens on Windows. I'm on rust 1.19.0. This is the error message I'm seeing.

```
renaming of the library `C` was specified, however this crate contains no #[link(...)]
```

Just running `cargo build` on [this sample repo](https://github.com/hone/heroku-cli-neon-hello-world/tree/node-pre-gyp/native) triggers it. Here's a [link](https://ci.appveyor.com/project/hone/heroku-cli-neon-hello-world) to an Appveyor build demonstrating it. I'm not sure how to work around the issue. Thanks for any help.
