### ISSUE TITLE
Documentation tests don't give accurate line numbers

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#115262] opened 2023-08-27 03:40 UTC
I couldn't find a proper issue filed for this, so I'm going to open one and am fine with being redirected to an existing one if that's the case.

Right now, documentation tests don't give accurate line numbers when reporting panics. For example, take this code: [(playground link)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2c7a0aafc6cdb3c4825e37d2f8fe8090)

```rust
struct SomeThing;

fn some_other_thing() {}

/// ```
/// // this line is fine
/// // so is this one
/// // but the below one will panic
/// panic!("oh no");
/// ```
struct OtherThing;
```

If we run `cargo test` here, we get the resulting output:

```
---- src/lib.rs - OtherThing (line 5) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'oh no', src/lib.rs:6:1
```

Note that here, the failure is able to correctly locate the position of the doc test being run (line 5), but the line that actually failed in the test (line 9) is being identified as line 6 in the backtrace. In this particular example, since it's just a playground link, both the name of the file containing the test  (`src/lib.rs`) and the file reported by the backtrace are the same, but in general, the backtrace will always refer to the test being run as `src/lib.rs` and the line will refer to the actual line in the generated documentation test code, not the actual file where it's located.

This is frustrating when debugging, because it means someone has to do two things:

1. Locate the doc test, making sure that they read the correct location for it
2. Identify the failing line by adding the correct offset from the backtrace
3. When identifying the line, mentally subtract 2 from the offset since rustdoc will add an `extern crate` line and an implicit `fn main() {` line before the actual code.
4. Only do the above step if not explicit `extern crate` or `fn main()` lines are actually added in the test itself.

I'm sure that the infrastructure currently doesn't exist in the compiler to automatically map the file name and line numbers from the doc tests to the actual file and lines the code is located in, but it would be ideal if it could.

**Comment by ehuss** [comment] 2023-08-27 17:32
Thanks for the report!  I believe this is a duplicate of #73469, so closing in favor of that.

**Closed by ehuss** 2023-08-27 17:32 UTC
Labels: C-bug, needs-triage
