### ISSUE TITLE
Type ascription typo yields unclear error message

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#60933] opened 2019-05-18 08:01 UTC
The following code does not guide the user towards the problem. Especially considering the fact that there's no type ascription feature gate active.

```rust
fn main() {
    let u: usize = std::mem:size_of::<u32>();
    //                     ^ note the single colon instead of double
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=17a23068f90f2e62cdf7fde4c5592953))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unnecessary path disambiguator
 --> src/main.rs:2:36
  |
2 |     let u: usize = std::mem:size_of::<u32>();
  |                                    ^^ try removing `::`

error: expected one of `!`, `::`, or `;`, found `(`
 --> src/main.rs:2:43
  |
2 |     let u: usize = std::mem:size_of::<u32>();
  |                                           ^ expected one of `!`, `::`, or `;` here

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by estebank** [comment] 2019-05-18 22:43
Cc https://github.com/rust-lang/rust/issues/47666, https://github.com/rust-lang/rust/issues/54516, https://github.com/rust-lang/rust/issues/34255 and https://github.com/rust-lang/rust/pull/59150

**Comment by estebank** [comment] 2019-07-18 20:48
Duplicate of https://github.com/rust-lang/rust/issues/54516

**Closed** 2019-07-23 23:37 UTC
Labels: A-diagnostics, T-compiler
