### ISSUE TITLE
Warn about duplicated trait bounds like Send + Send

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#92410] opened 2021-12-29 17:36 UTC
[Given the following code: playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d9deba3199038ac6f81c6288cbffaf82)

```rust
fn _foo(_: impl Fn() + Send + Send) {}
```

There's no warning.

The bug is in `Send` specified twice, instead of one of them being a `Sync`. It would be nice to warn about this, e.g.:

```
warning: `Send` bound specified more than once
```

A `+ Send + Send` has no useful purpose, but it looks very similar to a common `+ Send + Sync`.

**Comment by ibraheemdev** [comment] 2021-12-29 19:56
Duplicate of #88013

**Closed** 2021-12-29 22:55 UTC
Labels: A-diagnostics, T-compiler
