### ISSUE TITLE
couldn't read src/main.rs in reustmann-0.1.2, Rust 1.17

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40185] opened 2017-03-01 19:19 UTC
```
brian@ip-10-145-43-250:~/dev/reustmann⟫ git remote -v
origin  https://github.com/Kerollmops/reustmann (fetch)
origin  https://github.com/Kerollmops/reustmann (push)
brian@ip-10-145-43-250:~/dev/reustmann⟫ git log -1
commit b1a1577667ca5e6e883dba603c13ef789723fb7c
Author: Geoffroy Couprie <geo.couprie@gmail.com>
Date:   Thu Nov 24 17:43:26 2016 +0100

    fix nom upgrade
```

```
brian@ip-10-145-43-250:/mnt2/dev/strcursor⟫ rustc +nightly -Vv
rustc 1.17.0-nightly (be760566c 2017-02-28)
binary: rustc
commit-hash: be760566cf938d11d34c2f6bd90d8fd0f67c2344
commit-date: 2017-02-28
host: x86_64-unknown-linux-gnu
release: 1.17.0-nightly
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/reustmann⟫ cargo +nightly test
   Compiling libc v0.2.20
   Compiling unicode-width v0.1.4
   Compiling encode_unicode v0.1.3
   Compiling bitflags v0.4.0
   Compiling colorify v0.2.2
   Compiling nom v2.1.0
   Compiling nix v0.5.1
   Compiling rustyline v0.2.3
   Compiling reustmann v0.1.2 (file:///mnt2/dev/reustmann)
warning: unused import: `memory::OpCodes`
 --> src/program.rs:1:5
  |
1 | use memory::OpCodes;
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused variable: `endl`
  --> src/program.rs:27:17
   |
27 |             let endl = '\n' as u8;
   |                 ^^^^
   |
   = note: #[warn(unused_variables)] on by default

warning: unused variable: `endl`
  --> src/program.rs:28:26
   |
28 |             if let Some(&endl) = instructions.last() { // FIXME '\r\n' for windows
   |                          ^^^^
   |
   = note: #[warn(unused_variables)] on by default

warning: method is never used: `trunc`
   --> src/interpreter.rs:121:5
    |
121 |       fn trunc(&self, val: u8) -> u8 {
    |  _____^ starting here...
122 | |         val & ((1 << self.arch_width) - 1)
123 | |     }
    | |_____^ ...ending here
    |
    = note: #[warn(dead_code)] on by default

warning: unused import: `memory::OpCodes`
 --> src/program.rs:1:5
  |
1 | use memory::OpCodes;
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused variable: `endl`
  --> src/program.rs:27:17
   |
27 |             let endl = '\n' as u8;
   |                 ^^^^
   |
   = note: #[warn(unused_variables)] on by default

warning: unused variable: `endl`
  --> src/program.rs:28:26
   |
28 |             if let Some(&endl) = instructions.last() { // FIXME '\r\n' for windows
   |                          ^^^^
   |
   = note: #[warn(unused_variables)] on by default

warning: method is never used: `trunc`
   --> src/interpreter.rs:121:5
    |
121 |       fn trunc(&self, val: u8) -> u8 {
    |  _____^ starting here...
122 | |         val & ((1 << self.arch_width) - 1)
123 | |     }
    | |_____^ ...ending here
    |
    = note: #[warn(dead_code)] on by default

error: couldn't read "src/main.rs": No such file or directory (os error 2)

error: Could not compile `reustmann`.
Build failed, waiting for other jobs to finish...
error: build failed
```

Not on 1.16

cc @Kerollmops

**Comment by brson** [comment] 2017-03-01 19:20
Also affects xmas-elf cc @nrc

**Comment by nrc** [comment] 2017-03-02 20:06
@brson how did you repro for xmas-elf? `cargo build` works fine for me

**Comment by nikomatsakis** [comment] 2017-03-02 21:28
triage: P-high

This is a regression, hence P-high, but it's unclear if it is a true regression or an artifact of cargobomb.

**Comment by nikomatsakis** [comment] 2017-03-09 21:15
@alexcrichton is this `T-compiler` or something else?

**Comment by alexcrichton** [comment] 2017-03-09 22:30
@nikomatsakis my guess is Cargo, I'm not sure though (I'll have to investigate)

**Comment by alexcrichton** [comment] 2017-03-10 05:22
cc @ehiggs I think this may have been caused by https://github.com/rust-lang/cargo/pull/3004, mind taking a look?

**Comment by ehiggs** [comment] 2017-03-10 10:59
Running a `git bisect`, I found that this was broken in either 8c40d891e2d770fac47b440d95ac31cb5d83f120 (which seems to have broken the build) or e3edc064761b75a0d9a8dfcd4ce46e9294e43f06 (more likely, imo).

https://github.com/rust-lang/cargo/pull/3609

**Comment by ehiggs** [comment] 2017-03-10 13:35
This is a cargo bug. I've entered https://github.com/rust-lang/cargo/issues/3814 to handle it.

**Comment by alexcrichton** [comment] 2017-03-10 15:32
gah sorry @ehiggs, but thanks for the diagnosis!

**Comment by ehiggs** [comment] 2017-03-10 15:53
No worries. Glad to help.

**Comment by alexcrichton** [comment] 2017-03-14 03:00
Fixed in https://github.com/rust-lang/cargo/pull/3818

**Closed by alexcrichton** 2017-03-14 03:00 UTC
Labels: P-high, regression-from-stable-to-nightly, T-compiler
