### ISSUE TITLE
Performance regression in pattern matching

### ISSUE THREAD

**Issue by pmarcelll** [rust-lang/rust#36283] opened 2016-09-05 14:04 UTC
I discovered the cause of a fairly big performance regression (from ~22s to ~29s in a specific benchmark) in my small BF interpreter and I succesfully minified the code:

``` rust
#[derive(Clone, Copy)]
enum Inner {
    A,
    B,
    C,
}

enum Outer {
    X(u32),
    Y(Inner)
}

#[inline(never)]
fn print(x: &Outer) {
    match *x {
        Outer::X(num) => println!("{:?}", num),
        // Replace this...
        Outer::Y(i) => {
            match i {
                Inner::A => println!("A"),
                Inner::B => println!("B"),
                Inner::C => println!("C"),
            }
        }
        // ...with this
        // Outer::Y(ref i) => {
        //     match *i {
        //         Inner::A => println!("A"),
        //         Inner::B => println!("B"),
        //         Inner::C => println!("C"),
        //     }
        // }
    }
}

fn main(){
    let x = Outer::Y(Inner::B);

    print(&x);
}
```

On stable, both version of this code compiles to the exact same binary (and also on 1.9.0 and 1.10.0, both old-trans and MIR on each version respectively). On beta and nightly, the commented out code becomes slower. My understanding is that this should compile to the same binary, so this is incorrect behavior.

The last correct version is `rustc 1.12.0-nightly (7333c4ac2 2016-07-31)`, right before the update to LLVM 3.9.

EDIT: I noticed that the minified example does compile to the same binary (I somehow got confused) so I added the `#[inline(never)]`.

**Comment by Aatch** [comment] 2016-09-05 21:49
The timing suggests this might be an LLVM issue. We're getting more and more of these lately, which is concerning.

**Comment by brson** [comment] 2016-09-13 16:44
Needs a P-tag.

**Comment by nikomatsakis** [comment] 2016-09-13 16:47
@nagisa also theorized that this was an LLVM problem (aliasing?). Do we have an easy way to test for that?

**Comment by nikomatsakis** [comment] 2016-09-15 16:18
Hmm. So I popped these examples into play and built the resulting assembly (with optimizations enabled). They came out pretty similar:

```
lunch-box. diff ~/tmp/print-{ok,ref}
1c1
< .text
---
>     .text
12a13
>     andb    $3, %sil
```

**Comment by nikomatsakis** [comment] 2016-09-15 16:24
Same results for beta:

```diff
--- /home/nmatsakis/tmp/print-ok-beta   2016-09-15 12:22:36.604531321 -0400
+++ /home/nmatsakis/tmp/print-ref-beta  2016-09-15 12:23:04.984530867 -0400
@@ -10,6 +10,7 @@
     .cfi_def_cfa_offset 80
     cmpb    $1, %dil
     jne    .LBB0_1
+    andb    $3, %sil
     cmpb    $1, %sil
     je    .LBB0_7
     cmpb    $2, %sil
```

**Comment by nikomatsakis** [comment] 2016-09-15 16:24
Is it possible we fixed this? I know we did some LLVM fixing.

cc @eddyb, I think you managed most of that.

**Comment by nikomatsakis** [comment] 2016-09-15 16:26
That said, stable builds are **identical**. Though I find it hard to imagine that the `andb` is really responsible for a massive performance drop.

**Comment by eddyb** [comment] 2016-09-15 16:29
It could easily be something else, identical binaries are no guarantee, so the reduction could be unrelated.
Using `perf record` on the original benchmark *could* pinpoint that an `andb` instruction is responsible.

**Comment by nikomatsakis** [comment] 2016-09-15 16:29
Also, stable vs nightly look quite different, even if  changing between the two versions of the arms makes no difference.

**Comment by nikomatsakis** [comment] 2016-09-15 16:33
@pmarcelll how confident are you that this reduction is accurate? can you make a version of the original benchmark available?

**Comment by pmarcelll** [comment] 2016-09-15 16:51
Here's the code: [link](https://gist.github.com/pmarcelll/8a277849ed0aac1ac10d2b427b8126a9).
[This BF code](http://esoteric.sange.fi/brainfuck/utils/mandelbrot/mandelbrot.b) is used for benchmarking.

**Comment by pmarcelll** [comment] 2016-09-15 16:58
The problematic part is in the hottest code path, so the slowdown is really noticable.

**Comment by pmarcelll** [comment] 2016-09-15 17:08
Also, if the enum is not `Copy` or `Clone`, the `ref` version must be used, that compiles to the slightly slower version.

**Comment by nrc** [comment] 2016-09-15 20:13
Discussed at compiler team meeting, but we didn't have a good answer for priority since investigation seems to be ongoing. P-high for now, feel free to downgrade if we get new info.

**Comment by pnkfelix** [comment] 2016-09-20 16:21
Results of some investigation: I can reproduce *a* regression for this benchmark at the same point in the history, though its not as severe a regression.

Gist with the (slightly modified, self-contained) bf interpreter benchmark, and the transcript + summary of my runs: https://gist.github.com/pnkfelix/9e727884890b1ec867d58bd280cbbf82

Interestingly, other small perturbations also remove the regression. In particular, even just pulling the body of that match arm into a separate method and marking that method `#[inline(always)]` also removes the regression.

**Comment by eddyb** [comment] 2016-09-20 16:39
If anyone has access to LLVM 3.8 that they can build Rust with, it would help to confirm that this is *yet another* LLVM 3.9 perf regression.
AFAICT, what `#[inline(always)]` ends up doing at the LLVM level is change the order and number of passes ran on the IR of the callee.

**Comment by petevine** [comment] 2016-09-20 17:48
@eddyb You're in luck today! I finished building the same `aarch64` nightly a little earlier against `3.9` and `3.8`, and can confirm the difference: `2m41` vs `2m15` respectively.

BTW, `make install` doesn't work any longer, probably due to `--disable-docs` and this [line](https://github.com/rust-lang/rust/blob/master/mk/install.mk#L16)

**Comment by eddyb** [comment] 2016-09-20 17:56
@petevine Really useful, thanks! And so LLVM 3.9 delivers, yet another perf regression.

**Comment by pnkfelix** [comment] 2016-09-21 14:35
As a followup note regarding the gist I posted: I have done a little digging into the generated assembly for the `Tape::run` code, comparing the manually inlined to the LLVM-inlined codes (since those seem to end up being the most similar in output while retaining the bulk of the regression), and the main difference between the code for the two versions of `Tape::run` seems quite similar to the one that @nikomatsakis noted [above](https://github.com/rust-lang/rust/issues/36283#issuecomment-247378037).

```
.LBB7_2:                             |.LBB7_2:
        cmpb    $1, (%r14)           |        cmpb    $1, (%r14)
        je      .LBB7_5              |        je      .LBB7_31
        movb    4(%r14), %al         |        movl    4(%r14), %eax
        andb    $31, %al             |        addl    $-45, %eax
        addb    $-13, %al            |        cmpl    $17, %eax
        movzbl  %al, %eax            |        ja      .LBB7_5
        cmpb    $17, %al             |        movslq  (%r15,%rax,4), %rax
        ja      .LBB7_8              |        addq    %r15, %rax
        movslq  (%r15,%rax,4), %rax  |        jmpq    *%rax
        addq    %r15, %rax           |.LBB7_7:
        jmpq    *%rax                | 
.LBB7_12:                            | 
```

In particular: the slower version on the left has an extra `andb` instruction. (It also has that `movzbl` and is using the `b` suffixed instructions rather than `l` suffixed ones.)

----

Anyway, at this point I'm inclined to agree with @eddyb that this is probably an LLVM issue, not a Rust compiler one. We could investigate the order and number of passes, or we could try to file an LLVM bug, but either way, I think we should downgrade the priority of this ticket.

**Comment by nikomatsakis** [comment] 2016-09-21 16:56
Inclined to agree.

triage: P-medium

**Comment by pnkfelix** [comment] 2016-09-22 16:32
> this is probably an LLVM issue, not a Rust compiler one. We could investigate the order and number of passes, or we could try to file an LLVM bug

I think the path forward is to file an LLVM bug.

Next steps:

 1. Create isolated test case suitable for reporting to LLVM
 2. File bug there, ask LLVM devs for assistance

@eddyb notes that majnemer is often willing to do bisect against LLVM code base on small self-contained test case.

**Comment by nagisa** [comment] 2016-09-23 16:24
Filled https://llvm.org/bugs/show_bug.cgi?id=30505

**Comment by Boscop** [comment] 2017-08-30 20:42
Any update on this? :)

**Comment by pmarcelll** [comment] 2017-09-01 22:34
It wasn't fixed in LLVM 4.0, but it might be fixed in 5.0, I'll check when the support is merged. The ergonomics improvements in pattern matching might also improve on this.

**Comment by Boscop** [comment] 2018-04-22 17:26
Is it fixed now? :)

**Comment by pmarcelll** [comment] 2018-04-24 15:20
I tried it a couple of days ago with the BF interpreter I linked earlier and it was slow no matter what compiler flag I used. As I wrote in the first comment, the benchmark completed just under 22 seconds, now it ran for 30 seconds with only a `--release` flag, and I couldn't push it under 25 seconds with other compiler flags. I didn't have time to further investigate, but I reran the tests today and I noticed that the nightly compiler produced identical binaries for both the slow and the fast version, so I [put the code into the Godbolt assembly analyzer](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAViAIzkA2AhgHaikCuAzkeT3RdSqbCADkAUgBMAZjBhJAVgBCqUiyLYA%2BkQCeAB2wBqSbIAip6dKYEARjOnLzkgAwBBN57nKVOUgQAbtgQAMJM6GzY5Mah6AZ6AJTOXjKyvqTYBqQQXLLSyUouHthsXAC2xgDyBgAqhiaSAOwqXsbtxgCSbKimFsZgUtIqg8YsPMZ50uRtHebYvWaWgwC0o%2BOT%2BTMeHcYACgFsRH3L4gB06xNT2%2B67ALLowQfYgScDUrKhl5vTs%2B0PwQActgAB7HJbvMy4b7XVJNYqeEplSo1UwtP7GQGRAAy6HiEBq9SMiRuu1x%2BJU6BBZlCvhqKVkuBJcIRXj43FQx1qLCMaNaOw6BnQPBAkx4BAAXtEMUQeWJjAA1BY0gjiqVQm7NVkeAjlAxMYzc3nNfm3DoAMzYxiiAHcIIljCsoYa5XyMbsjY10QLdr7jEKRcZXKS/b7ZUZRcFUApfK5nCG/VqMUmfcZLcZgNgiBAZAA2HjYJjmh1OxnGVWSr2m0PGAtFs7h7C%2BOvms4BlKplNm9rpzNEVA56T5wvFx3O1BIFikN2p3Yts59%2B1jK4ADmXxgnU%2BT8Ix6YIPUHufKXGOLYdJvdHXnjebI7bwucVla/XoZmrHS7u3TOAHeePp5Hc9vW7X1rzlW963bIoxxfN9twRL8rXKR5tAMQ9/1rQCZxAuc7wDGDLFfWR33aT8LSQlC2HQk9MKLICSNAvDhSfCEiIY3YCHNWjW3wpYITAowziYUolwvWdQwE7A214JAIFcZJiMvUid07FTERA9NuCov8aJbGJsnQYANHKUU8zpAxnHopSxRMPhMBAEACHQByTT04wAHUAi0JNFPE9peBMQkGgcgAqOCPGs80yGMeJyytAyjJYSoxJw0Nyk0CdjBC2KUprGsagc8k0MyLiEuM88LGdXK8pqm0kAIYTuIXLMlxjfpXGwmquqvO8tIgMqkoU9juo/NSRtGhDxuMAB6abjAAMXGY5glIcVImsmtZoKkAsTYIqIHQCqXDLarxtm3Z0v7JAYs6qbzoAZQiG1jBWta2A20Ntt2/aSpio6quAqbfUuzLstuoG/W6RZKrLed9wHZk/Ih%2BZoeO3Amp/e0Ewh3YDn3cEYfR06cdDbJ8YUQcnHRHdrBiec%2BwRoaPpxpyHLsoRs0SM5zSYGT7TOLg2BtDQ0KZpGgbIkmOgBbBnlePjYbvZDAlQrHmZGmXgTBE5nXnZXtCoxHUvGyWRtNmtzYm%2BCWVSDx0wMKcCxpTpRU6LQNBIUhna0ZL%2Bk3L3GShCBiFMocMM6EtnUpalPnMhkicBjoAuqOpgpAMLfJA4TjgwuwuC4iElVQBzbXtcKQLqhqTGz4x7vQcoQlQI7yyIM4ojBUTE79POeL5kHrsWLu8sGGQRnEHWyy%2BnE8TQqGje61ZRgV9Gp72meIBR%2BeusGC5x%2BXlOHO%2B9e8aOLeapHz4l8Jg%2Bdun/EZbls/h4%2BaE9%2Bv1f9s10EiCfmsR9UK%2BaMb77QdqtEIxBEi/1DP/cwgDnR2EyCwAA1tjGs2gJ7owwEcfcXBpRIy1GLECpse5nHxugbQdgqTYEwNoHgthRBlwimpNkRAOTHAOIZYy4MYoGEDNHGkccigahthFHUeoDQcMSslIe6ZS4YBwKKe6rD9zAEjmWSRXDia41IJwpKfIeGBlAQWaixx5FSX9jwe0QFJrKRsWmK0fUzzcN2DXDCjY3iehLtgO0hCayNjOH1PM854g8F8VbJh2p3AGC4HYexxgtIUPNJ3Biyc7IOXNCKEA80q7l12Kkog9kQAOyICgEAexNBIFyUnAstYCkOVZkUzIvMFHpyqf5GpaSQClECOXDENcpzAHoG8bpDkBmWK5kcWS9AuaC2FjyMumcXFZn9BUt45SSleLtHmAZ0y2nGFcbpN4SjDigBAKXMJ7QDnHHNFXN42ThIOXiCJPMxSkAzKFiLBZDEbnCQCdgFgNCSC0OURwExtZ3lzNFnsmuA1faWA0UlTZEBQl7NhQEwWXyRHuHECSJgEglDiHIGwCQrhCXOXEAAJV4KeIQIhGhyHoISogJKcXkAgCgDAeoq4UCoBATlBhuUgFIPQOQwYfnuxFBAOwLLyB2H3FOPQEhGXkE5Q3I4VQ2BMEVeIUl5AcDpQ4A8nVhLCCZE5EEbAIpjXkFBAsE8YhxDKvxoWGVyiTLGtxewTg1LmD2BFJAEk8QiBOTYFalYcQDBEBWMJYITAliyEdKEMxmY2ArEFsQHgSxlWCGEKIBguL8WEuJda8l3A%2BC9HoGcOQZwOoQHwMQaKaRGCxHrgK4S04m0OipXwJlLLIHkCQP8/w1ASRIJAEoStE7ZD0CUE0FcABOAALE0WQuYVyLuYBIRdhKTL0FcMGYturyWEpFMGZlHq2WIHZWgLAeBCCe0oNQOg0xWAcCFT6nNdKJBpBjKodQmgdD6GNP0RwtgHDWA7OpNIvh/AWrCBEKIMQI1JEg9B1QmRsi5HyIUBEpQKgpyJFWDEUM3gj2GDCLYGIUakfEGsceGxYSphPgTU4u91yMZAg/TI8t%2BgXy%2BPRq4lHUxf21hCC%2Br92NCc8MwpE%2BHUTEyPviIKxJsb7X4bHVQ9IhGMiNl2FhbCXTGiHgGUUvBKzY0bKKIuKo1RNkZJqGT7hdT6kM0R1MsjvFLlLOjT0ziOi%2Ba0aTYUopgzq0sy9BYv6VBxiKKg8JRCxrkQzC1IJWFvPlls359okkII8QfEI1SdjexZl/EOJx6X/ZZaaouB0DG1wbH9tbdzVp4ZgqcYF7Ld4byqHnFBSwo9WJ7NNt%2BBYbWsIdaat1lQvX8uWFLIRIbiWewURVmhHSAE6JVZmxMebxg2JNY0itg2Y3NsTe2yxWCizQycSarxGGlhJJCRElZcWPV6z%2BOiTwWS8k9m7FNnp5r8SMXre4vpHRUjQ65kEeYF7xsbK1MKQ01yI4YieWIE2HcV2/TJ2U2IVpmdIrRVivuf04PNFDxrP3LKOUKddW2j9bApUyeDQwVV7qldGr0xag6NqlgOoTaBvOPqsKLkQ0tjVcXeVzqLT4BF1aIb1a7A/uvQ6rOBddSp%2BgNnoYHpPTl29RXHQtoGEPnfYqjO/pq9pzVc6HQqdg3V%2BNEj%2B84YHigTjajLu7yY3dxDZjVvhpS3aGTI4FNHAXhptMarJWrG/aD%2B0Bp7MTz8x5nzCFnzRdS0l0DLjLxWd6xQqLOLOMRMsd1krSiatXsS6W2bWvFt6/xb%2B8wxz9tHZ2dCC7Lo7tNBkG9tgOFG5JwB1wEHEOVgjw0QjjBdG6naSaYstphOKSam49CtC5Zud85vCLki0XHPq7LLrg3PlzdiBt2/sk6yJDPuySp4PQPvoyNj1Z8r/Ec9i9P9o3AyeJvb5r3xE3k/12B3h/xXj/0UzQmY19xAI%2BH41fwgLNwgFz0CBgI6HEzAJvkgOQMeGwC1h/mAPQKkAATfiAXp3XiMXAR/jQPaBgUwIQX%2BRQXVnQX3iwWDTKDwThwIUWzsRITIQoSoRoToQIAYWSAiVtncHZC4E5H2GZ2kQYhCVFDn2h2EXENESc3EVkN0XkN3CtDkVvUURBVURny0KkSqwRXkIMVFEoLBTMTOAsSsTRDsWGwcQxXa2t32U3xoncQhE8TOU80zw6H8UCTKzvBCVFz00c2iViU0kFkSSv1THyUKQyQcnuTsxX1sjqSKQqQcnWUqSx3h06QaWyELC4BaQzgyIRwcm6V6VTH6VIEGWGTYECFGQaPGTbhKQgGmQFg%2BXmVFxhVWQhDyKRW2QaN2QKKuVrCOSML3w3xzhoh%2BUaH6DSMeSMG0iHFeXTz6L2UWL%2BQBV0HIXZBUTay2KhQmOWVhTWTkKRRRQKLRT6kIS7FZTxXEAJSJRlXJW7RpVzXpXyF7QvWvX5W5UfT5VbUFWFVFXIHFWwFWmoGlWtTlTYAVSVUJVVVKCIA1S1RlX1S9SNV1VNQWGDWCCtV1VtVQHtRRMoCOBdWtTdT7WYC9XfT4F9TsH9SxiDRDTDQjSjRjULHjUTWTVKDTTYAzSzRPVpTzQKE3VeKLQ%2BIkDLX7D2yrVkBrWMDrXvUbTkCjziC5XbSsGw2MC%2BP%2BNJX7UHQBRhJHXIDHUXRXDOBtLXUXWkD3SUCHGnSaGlO3XIF3X3XeJLQkBPRADPT7QLXEGkB3XHQPTlPEGNNZTgFgBQEIHNHNBBKYCQBFEYFIDTJAClJeLeMPTJQkHME4i4gVIrWVNVMCAmFLKVOrV1XPRNJJDNOHSxheM9JMiUEjL9OjIEEDPIHrJxRDNkFlK7JjP7VehDRAEXSAA%3D). According to the analysis, rustc 1.23.0 was the last compiler that produced different binaries, after that, **the fast version regressed**, and now it's identical to the slow version.

**Comment by Boscop** [comment] 2018-09-30 17:33
Any update on this?

**Comment by pmarcelll** [comment] 2018-10-01 23:55
I tried it when `rustc` was updated to LLVM 8 (so fairly recently), and now with the latest nightly. A plain release build produces a binary that completes the benchmark just under 27 second on my machine, with LTO it's close to 26, but reducing the number of codegen units or aborting on panic negatively impacts performance, it confuses the optimizer in LLVM somehow (it's not really a bug, fine-tuning an optimizer is hard), and because this program is basically a loop that performs a small set of operations over and over, every missed optimization is magnified.

All in all, `rustc` became slightly better recently, so the plain release version is fast, but this bug still slows down the test program.

**Comment by pmarcelll** [comment] 2018-12-28 16:41
I just checked it on nightly and it seems to be fixed (even on the latest beta). I don't know what changed, but I looked at the assembly on Godbolt and the previously slow part is now equivalent to the old version.

I even managed to get the lowest runtime so far, only 19.543 seconds, with
`cargo rustc --release -- -Clto=fat -Ccodegen-units=1 -Ctarget-cpu=sandybridge -Cpanic=abort` (for some reason, usually Rust binaries optimized for Sandy Bridge by LLVM run really fast on Haswell CPUs).

If this regression is unlikely to return and it was indeed fixed in LLVM then it can be closed.

**Comment by pmarcelll** [comment] 2018-12-29 18:47
I tried to bisect it, my program became fast again right after #55835 was merged, so it looks like it was indeed fixed by an LLVM upgrade. @nagisa can you confirm it by checking the LLVM bug report? Thanks.

**Comment by nikic** [comment] 2018-12-29 23:08
The LLVM issue has been fixed by https://github.com/llvm-mirror/llvm/commit/238b8867a8e7a18e9cdf1c72b049d8bed200ee7a, which has tests and comments to prevent this from regression without corresponding backend fixes. As such, I think we can consider this resolved...

**Closed by nikic** 2018-12-29 23:08 UTC
Labels: A-LLVM, C-enhancement, I-slow, P-medium, T-compiler, regression-from-stable-to-stable
