### ISSUE TITLE
why  havn't  implemented Error trait for std::option::NoneError ?

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang/rust#46871] opened 2017-12-20 10:10 UTC
Forgot it? Still for other reasons.

**Comment by kennytm** [comment] 2017-12-20 10:49
See also: https://internals.rust-lang.org/t/should-noneerror-implement-the-error-trait/6312

**Comment by ZhangHanDong** [comment] 2017-12-20 12:52
@kennytm thanks

**Comment by dlight** [comment] 2018-12-13 10:59
It seems to me that if `NoneError` should exist at all, then it should implement `Error`, otherwise `Box<Error>` doesn't work.

**Comment by aminroosta** [comment] 2019-06-23 11:28
Facing the same issue in 2019 :/

**Comment by Coder-256** [comment] 2019-08-12 01:19
@kennytm After looking through the discussion on #42526, I’m getting the impression that it is indeed an oversight that there is no way to convert `NoneError` to `Box<Error>` so that you can use `optional?` on a function that returns `Result<T, Box<Error>>`.

**Comment by skade** [comment] 2019-09-20 06:33
This becomes a prevalent problem in the trainings I give, when people learn about:

`Box<dyn std::error::Error>`

**Comment by bbqsrc** [comment] 2019-10-18 16:46
Can this be prioritised? It would be upsetting if this were to be forgotten, particularly since `std::error::Error` is quite useful now.

**Comment by Mark-Simulacrum** [comment] 2019-10-18 19:34
I don't believe this has been forgotten or de-prioritized -- at the very least, based on me re-read of https://github.com/rust-lang/rust/issues/42327, I get the impression that the general feeling is that the Try trait design is not ready and `Option` being convertible to `Result` via `?` is not something we are sure we want.

In particular, these comments are relevant:
 * https://github.com/rust-lang/rust/issues/42327#issuecomment-366840247
 * https://github.com/rust-lang/rust/issues/42327#issuecomment-376772143

**Comment by Coder-256** [comment] 2019-10-18 19:39
I actually changed my mind on this one. Now that I think about it, it only really makes sense to use `?` on an `Option` if the enclosing function returns an `Option`. Otherwise if you want to return a `Result` you can use `.ok_or("message")` to indicate what went wrong. The error message could be much better though.

**Comment by scottmcm** [comment] 2019-10-18 19:45
I agree about the error message.  I think one thing we missed in the Try trait design discussion was what the errors for _mixing_ should look like -- right now you get the note about `NoneError`, but with the other possible design you would have explicitly gotten something about `Result: Try<Option>`.

**Comment by bbqsrc** [comment] 2019-10-18 19:47
I'll note that I think the existence of a `NoneError` is a bit strange and a bit of a code smell, and another design should be considered. But if it isn't considered, make sure `std::error::Error` is implemented at least, haha.

**Comment by nixpulvis** [comment] 2020-02-25 19:06
If `NoneError` is to exist, then it should implement `Error`, otherwise a better name should be chosen for the `?` try trait result.

**Comment by ZhangHanDong** [comment] 2020-04-19 11:50
I don't think  should implement `Try` for `Option<T>`.

`None` is not an error, it is just a state that may cause errors. 

If Option<T> does not implement `Error`, then `try` block does not need `Ok-wrapping`.

> If you don't have any ? inside, then with ok-wrapping there is no real information about what the "wrapper type" should be (i.e., should try { 3 } have the type Option<i32> or Result<i32, _>, and what should _ be?)
from [niko](https://github.com/rust-lang/rust/issues/70941#issuecomment-612167041)

**Comment by ZhangHanDong** [comment] 2020-04-19 11:57
Should NoneError implement the Error trait?

[ Niko ](https://github.com/rust-lang/rust/issues/42327#issuecomment-366840247 ) 

Just a note

**Comment by skade** [comment] 2020-04-22 09:49
I see the issue that Try for Error is already on stable.

**Comment by scottmcm** [comment] 2020-04-23 05:28
Note that as of right now, it's absolutely by design that `NoneError` doesn't implement `Error`.

It's also unstable for a reason.  We have a meeting planned about redesigning the current `Try` approach, which will likely remove `NoneError` from being involved in `?`-on-`Option`.

I strongly discourage anyone from trying to hack around this restriction.  Just use `.ok_or(GoodReason)` if you want to early-return on `None` in a `Result`-returning function.

**Comment by mburszley** [comment] 2020-12-01 23:24
@scottmcm Make any progress this year on the issue?  You've mentioned "we have a meeting planned", just following up here.

**Comment by scottmcm** [comment] 2021-04-26 19:56
@Halkcyon Sorry for replying super-late here.

The meeting was https://blog.rust-lang.org/inside-rust/2020/04/10/lang-team-design-meetings.html#try-blocks-try-traits-functions-that-try-oh-my, though I'm not able to find minutes from there.

But https://github.com/rust-lang/rfcs/pull/3058 merged last week, which explicitly blocks the `?`-on-`Option`-in-`Result`-functions possibility, and (as it obviates RFC 1859) will likely result in `NoneError` being deleted from nightly.

**Closed** 2021-05-21 16:30 UTC
Labels: A-error-handling, C-feature-request, T-libs

**Comment by nhooey** [comment] 2021-06-02 01:20
What was the resolution for this?

If it was resolved, what version of Rust contains the fix and how do we use it in our projects?

Is there a convenient workaround that works before the fix?

Forgive my questions, I'm really new to Rust and just trying to get it working.

**Comment by scottmcm** [comment] 2021-06-02 02:27
The resolution of this is that it's expected that mixing them does not compile.  `NoneError` has been deleted.

As such, the fix is to call [`ok_or_else`](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or_else) or `ok_or` to provide a value implementing `Error` that includes the information about what went wrong, or to change the context to return `Option` instead of `Result`.
