### ISSUE TITLE
Assertion DISubprogram(Scope).describes(MF->getFunction()) failed

### ISSUE THREAD

**Issue by valenting** [rust-lang/rust#24220] opened 2015-04-09 03:18 UTC
I get this error:
```
src/lib.rs:57:7: 57:10 warning: unused variable: `enc`, #[warn(unused_variables)] on by default
src/lib.rs:57   let enc = EncodingOverride::lookup("ascii".as_bytes());
                    ^~~
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/CodeGen/LexicalScopes.cpp:179: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(llvm::MDNode*): Assertion `DISubprogram(Scope).describes(MF->getFunction())' failed.
Could not compile `rust_url_capi`.
```

It seems to be a compiler bug.
It occurs at this line, since commenting it seems to fix the problem:
https://github.com/valenting/rust-url-capi/blob/64c0a049bbffdb2676d39e0bc97ba0c5abb66ba6/src/lib.rs#L57

My guess is that the problem occurs because from rust_url_capi lib.rs:57-> rust-url encoding.rs:44 -> rust-encoding label.rs:13

**Comment by Aatch** [comment] 2015-04-09 03:25
What happens if you use 'enc'. It's probably related to that.

**Comment by valenting** [comment] 2015-04-09 03:28
Still fails. I tried to use it in a large number of ways, thinking I was doing something wrong. Didn't work.
You can clone https://github.com/valenting/rust-url-capi to see it happening.

**Comment by dotdash** [comment] 2015-04-09 10:52
Looks like a dupe of #23566. Can you confirm that it doesn't happen if you disable LTO?

**Comment by valenting** [comment] 2015-04-09 13:54
Yes, it only happens with LTO enabled.

**Comment by dotdash** [comment] 2015-04-09 14:41
Thanks! Closing as a duplicate of #23566 then.

**Closed by dotdash** 2015-04-09 14:41 UTC
Labels: I-ICE
