### ISSUE TITLE
error: internal compiler error: this path should not cause illegal move

### ISSUE THREAD

**Issue by ville-h** [rust-lang/rust#22042] opened 2015-02-07 09:49 UTC
fn main() {
}

struct X;

impl X {
  unsafe fn xevent_cast<T>(buffer: &[u8; 256]) -> T {
    return *(buffer.as_ptr() as *const T);
  }
}

**Comment by jdm** [comment] 2015-02-07 11:18
Duplicate of #20801.

**Closed by jdm** 2015-02-07 11:18 UTC
