### ISSUE TITLE
The todo! macro causes a `not yet implemented` panic message?

### ISSUE THREAD

**Issue by beyarkay** [rust-lang/rust#96131] opened 2022-04-16 21:42 UTC
Not sure if this is the correct place for this question, but what is the reasoning behind the `todo!` docs making the difference between `todo!` and `unimplemented!`, but then the `todo!` macro results in an error like:

```
thread 'main' panicked at 'not yet implemented', ...
```

It seems really counter intuitive to me. Is there a reason why the panic message is not:

```
thread 'main' panicked at 'still to do', ...
```

or a different panic message that's without a doubt not related to the `unimplemented` macro? (for consistency with how much the docs stress the difference between them)

For reference, [here's the paragraph](https://doc.rust-lang.org/nightly/core/macro.unimplemented.html) for the difference between `unimplemented!` and `todo!`:

> The difference between [unimplemented!](https://doc.rust-lang.org/nightly/core/macro.unimplemented.html) and todo! is that while todo! conveys an intent of implementing the functionality later and the message is “not yet implemented”, unimplemented! makes no such claims. Its message is “not implemented”. Also some IDEs will mark todo!s.

**Comment by gimbles** [comment] 2022-04-18 08:27
"Not _yet_ implemented" implies the same message as "still to do"? IMO

**Comment by jyn514** [comment] 2023-04-26 16:06
I'm going to close this as not a bug, the current error and documentation seem fine to me.

**Closed by jyn514** 2023-04-26 16:06 UTC
Labels: T-libs, C-discussion
