### ISSUE TITLE
Using type parameters in trait bounds doesn't count for error[E0392]: "parameter `A1` is never used".

### ISSUE THREAD

**Issue by roSievers** [rust-lang/rust#41083] opened 2017-04-05 15:17 UTC
I have a struct with a bunch of type parameters. Some of them are used for members and some of them are used to nail down the other type parameters.

```rust
pub struct MapStatistic<A1, A2, B, Stat, Pre>
    where Stat: Statistic<A2, B>,
          Pre: Fn(A1) -> A2
{
    preprocessor: Pre,
    statistic: Stat,
}
```
This uses all five type parameters but still triggers error[E0392] complaining about unused type parameters. I can fix it by adding `phantom: PhantomData<(A1, A2, B)>`, but I believe that shouldn't be necessary.

This issue looks related: https://github.com/rust-lang/rust/issues/35146
And now that I read it again after posting this comment it might even be the same thing. The lack of `where` is something I didn't see before.

**Comment by Mark-Simulacrum** [comment] 2017-05-10 01:47
Duplicate of #35146, closing.

**Closed by Mark-Simulacrum** 2017-05-10 01:47 UTC
Labels: A-diagnostics, T-compiler
