### ISSUE TITLE
Identity operation enforced by compiler?

### ISSUE THREAD

**Issue by emabee** [rust-lang/rust#56923] opened 2018-12-17 18:22 UTC
```rust

fn main() {
    println!("> {}",type_code(true));
    println!("> {}",type_code(false));
}

fn type_code(switch: bool) -> u8 {
    // why is the leading "0_u8 + " necessary? Compiler bug?
    0_u8 + if switch { 128 } else { 0 } + base_type_code()
}

fn base_type_code() -> u8 {
    111
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=79bd100b3e7d4c41a23c75c37d1e8b7d))

Output:

```
> 239
> 111

```

Shouldn't the above code also compile without the "0_u8 + "?
Note that clippy even complains about this identity operation.

**Comment by zackmdavis** [comment] 2018-12-17 18:50
Parentheses work:

```rust
fn type_code(switch: bool) -> u8 {
    (if switch { 128 } else { 0 }) + base_type_code()
}
```

I'm not sure how the parser determines when conditionals-as-expressions need parentheses; I agree that it's very counterintuitive for a leading `0 +` to determine whether a subsequent expression even parses (!).

**Comment by emabee** [comment] 2018-12-17 19:23
Not yet good, but already much better ;-)
Thanks!

**Comment by nagisa** [comment] 2018-12-17 21:58
This is an expected behaviour of semi-colon insertion for semi-statements.

https://github.com/rust-lang/rust/issues/29071
https://github.com/rust-lang/rust/issues/49865

At best this is a diagnostics issue.

**Comment by hellow554** [comment] 2018-12-20 12:12
https://github.com/rust-lang/rust/issues/54186

**Comment by nagisa** [comment] 2018-12-20 13:55
I‘m gonna close this as a duplicate of #54186 as that seems to be pretty much exactly the same thing, with a different operator.

**Closed by nagisa** 2018-12-20 13:55 UTC
Labels: A-diagnostics, A-grammar
