### ISSUE TITLE
meta: Lint against items that have stability attributes but are private

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#83396] opened 2021-03-22 23:20 UTC
Adding this would likely have prevented https://github.com/rust-lang/rust/pull/83372#issuecomment-804135923.

**Comment by jyn514** [comment] 2021-03-23 01:34
Duplicate of https://github.com/rust-lang/rust/issues/83380.

**Closed by jyn514** 2021-03-23 01:34 UTC
Labels: A-lint, A-meta, A-stability, C-enhancement
