### ISSUE TITLE
How to create a custom attribute ?

### ISSUE THREAD

**Issue by yanishoss** [rust-lang/rust#54506] opened 2018-09-23 14:48 UTC
# How to create a custom attribute ?

Hello, i want to know how to create custom attributes like this:
```rust
#[my_attribute()]
struct Something {
...
}
```

Could you help me ?

**Comment by abonander** [comment] 2018-09-23 16:36
Since proc macros have recently been stabilized it seems that the guide I wrote for them in the Unstable Book has disappeared, and now we don't really have any public documentation for them. That's unfortunate.

**Comment by abonander** [comment] 2018-09-23 16:38
@steveklabnik should we just move the old Unstable Book entry for the `proc_macro` feature to TRPL or something?

**Comment by steveklabnik** [comment] 2018-09-23 22:43
I’ll be writing the chapter this week.

**Comment by steveklabnik** [comment] 2018-09-24 19:03
Closing as a duplicate of https://github.com/rust-lang/book/issues/1283

**Closed by steveklabnik** 2018-09-24 19:03 UTC
