### ISSUE TITLE
Rustdoc source code is not displayed next to line numbers

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#56230] opened 2018-11-26 10:13 UTC
I observed it in my documentation that is generated on docs.rs but also on my local builds.

If you look at https://docs.rs/logical/0.2.1/src/logical/logicbit/ieee1164.rs.html then you will see, that there are line numbers and after the last number the real source code starts appearing. Observeable on FF, Chrome and IE.

![grafik](https://user-images.githubusercontent.com/921462/49007640-3d2e3300-f16c-11e8-86ad-597df8d532aa.png)

Funny enough, in the version 0.2.0 it is all normal https://docs.rs/logical/0.2.0/src/logical/logicbit/ieee1164.rs.html

**Comment by steveklabnik** [comment] 2018-11-26 10:53
Which versions? Iirc this was a bug that should have been fixed.

**Comment by hellow554** [comment] 2018-11-26 12:18
Seems to be the 20181115-1.32.0-nightly -ish. If it has been fixed (seems so after an rustup update) is it possible that `docs.rs` documentations will be rebuilt that has been built in that date region?

**Comment by pietroalbini** [comment] 2018-11-26 12:44
Duplicate of https://github.com/rust-lang/docs.rs/issues/264.

**Closed by pietroalbini** 2018-11-26 12:44 UTC
