### ISSUE TITLE
rustc crashed

### ISSUE THREAD

**Issue by zxxunkxzhx** [rust-lang/rust#73329] opened 2020-06-13 21:18 UTC
rustc crashed on compiling following code:

```rust
fn main() {
    let mut names = vec!["Bob", "Frank", "Ferris"];

    for name in names.iter_mut() {
        *name = match name {
            &mut "Ferris" => "There is a rustacean among us!",
            _ => "Hello",
        }
    }

    println!("names: {:?}", names);
}
```
```
thread 'rustc' panicked at 'internal error: entered unreachable code', src\librustc_metadata\rmeta\mod.rs:282:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0 (49cae5576 2020-06-01) running on x86_64-pc-windows-msvc
```

**Comment by lzutao** [comment] 2020-06-14 02:14
cannot reproduce in playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e56fbb27b4aec7b1d1424710bf7d00cb

**Comment by bugadani** [comment] 2020-06-14 12:22
can't reproduce using either `stable-i686-pc-windows-msvc unchanged - rustc 1.44.0 (49cae5576 2020-06-01)` or `nightly-i686-pc-windows-msvc unchanged - rustc 1.46.0-nightly (826cb062a 2020-06-05)`

**Comment by JohnTitor** [comment] 2020-06-26 10:48
I also cannot reproduce any ICE with rustc 1.46.0-nightly (50fc24d8a 2020-06-25) on nightly-x86_64-pc-windows-msvc. I'm going to close this issue as wontfix, please double-check whether the issue still occurs after `cargo clean` or not and feel free to re-open if needed. Thanks for the report!

**Closed by JohnTitor** 2020-06-26 10:48 UTC
Labels: C-bug, I-ICE, T-compiler

**Comment by shutton** [comment] 2020-08-28 03:35
This issue occurs on FreeBSD 10.4 with the 1.46.0 (stable) compiler.  Downgrading to 1.45.2 resolves it.

**Comment by lzutao** [comment] 2020-08-28 03:43
> This issue occurs on FreeBSD 10.4 with the 1.46.0 (stable) compiler. Downgrading to 1.45.2 resolves it.

Please open a new issue for this bug because your comment may get lost. 
Beware that FreeBSD is tier-2 target, not many developer have machine
to test on. So including more details is really helpful You could like back to this issue if you want.

**Comment by shutton** [comment] 2020-08-28 05:04
After downgrading and upgrading, and then starting over with a fresh cargo environment, I'm no longer able to get a repro.  I'll open a new issue if I see it again.
