### ISSUE TITLE
Prost broken afer nightly-2017-12-31 (due to memchr change?)

### ISSUE THREAD

**Issue by jedisct1** [rust-lang/rust#47192] opened 2018-01-04 19:35 UTC
Prost code generation fails after (but not including) nightly-2017-12-31: https://github.com/danburkert/prost/issues/66

    panicked at 'byte index 1 is not a char boundary; it is inside '\u{1}' (bytes 0..1)

Repository with a minimal test case for that issue: https://github.com/jedisct1/prostate

Maybe due to b65f0bedd2f22d9661ecb7092f07746dc2ccfb0d ?

**Comment by danburkert** [comment] 2018-01-04 21:28
Likely a dupe of #47175.

**Comment by kennytm** [comment] 2018-01-04 21:42
Closing as duplicate for #47175.

**Closed by kennytm** 2018-01-04 21:42 UTC
