### ISSUE TITLE
Cargo fails to build

### ISSUE THREAD

**Issue by kstenerud** [rust-lang/rust#24788] opened 2015-04-24 22:12 UTC
### System:
Macbook pro running OSX 10.9.5

### Rust version:
1.0.0-beta.2 (Mac installer)

### Meta:
    $ rustc --version --verbose
    rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)
    binary: rustc
    commit-hash: e9080ec39d9a44eb0773d648b348575b19f655e5
    commit-date: 2015-04-16
    build-date: 2015-04-16
    host: x86_64-apple-darwin
    release: 1.0.0-beta.2

### Steps to reproduce:

1. Generate simple .rs file as per (http://doc.rust-lang.org/1.0.0-beta.2/book/hello-world.html)
2. Generate Cargo.toml file as per (http://doc.rust-lang.org/1.0.0-beta.2/book/hello-cargo.html)
3. Run `cargo build`

### Expected result:
Cargo builds `target/debug/hello_world`

### Actual result:
Cargo fails with the following error:

    $ cargo build
    failed to parse manifest at `/Users/karl/Projects/rust/hello/Cargo.toml`

    Caused by:
      either a [lib] or [[bin]] section must be present

### Note also:
If I put "1.0" in the version field of `Cargo.toml`, it fails with the following error:

    $ cargo build
    failed to parse manifest at `/Users/karl/Projects/rust/hello/Cargo.toml`

    Caused by:
      cannot parse '1.0' as a semver for the key `package.version`

**Comment by alexcrichton** [comment] 2015-04-24 22:50
Could you gist the contents of the `Cargo.toml` you wrote? It looks like the `version` key needs to be updated with an extra numeric component (e.g. the book's version is `0.0.1`)

**Comment by kstenerud** [comment] 2015-04-24 22:53
It's very simple so I'll post it here. The first error was caused by this `Cargo.toml` (copied from the book):

    [package]

    name = "hello_world"
    version = "0.0.1"
    authors = [ "somebody" ]

The second error (the parse error) was caused by this `Cargo.toml`:

    [package]

    name = "hello_world"
    version = "1.0"
    authors = [ "somebody" ]

**Comment by alexcrichton** [comment] 2015-04-24 22:58
Is that second `Cargo.toml` in the book? Otherwise this is a legitimate error that Cargo is saying.

**Comment by kstenerud** [comment] 2015-04-24 23:00
I just copied from (http://doc.rust-lang.org/1.0.0-beta.2/book/hello-cargo.html), where it says:

Put this inside:

    [package]

    name = "hello_world"
    version = "0.0.1"
    authors = [ "Your name <you@example.com>" ]

**Comment by kstenerud** [comment] 2015-04-24 23:01
Oh sorry the second one. No, for the second one I had just assumed that you could put any dotted number like `1.0` in the version field. It seems to only work if the first digit is `0`.

**Comment by steveklabnik** [comment] 2015-04-24 23:02
What about "1.0.0"?

**Comment by alexcrichton** [comment] 2015-04-24 23:02
Ah so the version field is required to be a valid [semver](http://semver.org/) which requires three components (period separated). Other than that though it looks like everything is working as intended here, so closing, but thanks for the report!

**Closed by alexcrichton** 2015-04-24 23:02 UTC

**Comment by kstenerud** [comment] 2015-04-24 23:08
OK cool, but what do I need to put in the original `Cargo.toml` file to make it work? The book doesn't say.

**Comment by alexcrichton** [comment] 2015-04-24 23:11
@steveklabnik's suggestion of using "1.0.0" as the version should do the trick!

**Comment by kstenerud** [comment] 2015-04-24 23:16
Oh yes, that solves the version issue, but there's still the main issue that it fails with this:

    Caused by:
        either a [lib] or [[bin]] section must be present

So I'm guessing that rust has changed since this section of the book was written, but as a result, I don't know what to put in a `lib` or `bin` section.

**Comment by alexcrichton** [comment] 2015-04-24 23:28
Ah that just means you need to have either `src/lib.rs` or `src/main.rs` to build.

**Comment by kstenerud** [comment] 2015-04-24 23:28
Oh I think I found the problem:

I hadn't created the `src` directory, and instead had everything at the top level:

    $ tree
    .
    ├── Cargo.toml
    └── main.rs

    0 directories, 2 files

If you do this, it gives a misleading error:

    $ cargo build
    failed to parse manifest at `/Users/karl/Projects/rust/hello/Cargo.toml`

    Caused by:
      either a [lib] or [[bin]] section must be present

But move `main.rs` into a `src` subdir, and everything works:

	$ tree
	.
	├── Cargo.toml
	└── src
	    └── main.rs

	1 directory, 2 files
	$ cargo build
	   Compiling hello v0.1.0 (file:///Users/karl/Projects/rust/hello)

**Comment by bombless** [comment] 2015-04-24 23:50
Normally you have a `src/lib.rs` for your library.
If you don't, you need `[[bin]]` or `[lib]` otherwise cargo doesn't know what to build.

**Comment by skynetdev** [comment] 2015-05-26 22:39
Please somebody fix this in the book  and also show tree of directories how is should be.
├── Cargo.toml
└── src
    └── main.rs

**Comment by kstenerud** [comment] 2015-05-26 22:47
Yes, it's important to be very explicit in an introductory book. I have 20 years professional experience covering more than 10 languages, and this stopped me dead in the water. Even worse: the error message cargo spits out doesn't even come close to explaining what's actually wrong. It feels like the bad old days of cryptic C compilers.

**Comment by skynetdev** [comment] 2015-05-27 07:40
Ahh I forgot about one important moment
you should to set version to ```0.1.0```  in ```Cargo.toml```
cuz if you will try to run this command  ```cargo new hello_world --bin```  then you will notice in Cargo.toml the correct version and it will be ```0.1.0```  according with current version of *Rust*

**Comment by JosueTorresM** [comment] 2015-05-31 07:06
Just create an empty src/lib.rs

**Comment by jdungan** [comment] 2015-06-17 12:36
Thanks for this issue and comments. I'm really looking forward to working through the book but this shut me down quickly.  So I'm echoing @kstenerud on the need for explicit docs.

**Comment by javaperl** [comment] 2015-08-02 08:12
The book obviously has this part wrong, as it should explicitly say to put Cargo.html into the root directory.  Please fix it.  Thanks.

**Comment by ishankhare07** [comment] 2015-08-07 20:20
just for my knowledge
what if i don't want to name my file as `main.rs`
is there a flag/variable in `Cargo.toml` that i can set
in order to let cargo know that which file to build
and not just the default `src/main.rs` file

**Comment by alexcrichton** [comment] 2015-08-10 16:28
@ishankhare07 yeah you can have something like:

```toml
[[bin]]
name = "foo"
path = "src/some-random-path.rs"
```

**Comment by ishankhare07** [comment] 2015-08-13 12:47
@alexcrichton thanks, that worked
