### ISSUE TITLE
"type annotations required" errors in 1.28 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#51844] opened 2018-06-27 13:17 UTC
A bunch of crates failed to compile in 1.28 beta with error messages like these:

```
type annotations required: cannot resolve `std::io::Error: std::convert::From<_>`
type annotations required: cannot resolve `std::borrow::Cow<'_, str>: std::convert::From<&_>`'`
type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
```

* [ ] [mles-client](https://crates.io/crates/mles-client) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/mles-client-1.0.6/log.txt)) cc @jq-rs
* [ ] [ogrep](https://crates.io/crates/ogrep) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/ogrep-0.2.1/log.txt)) cc @kriomant
* [x] [openml](https://crates.io/crates/openml) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/openml-0.1.1/log.txt)) cc @mbillingr
* [ ] [screeps-api](https://crates.io/crates/screeps-api) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/screeps-api-0.4.1/log.txt)) cc @daboross
* [x] [tokio-dns-unofficial](https://crates.io/crates/tokio-dns-unofficial) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/tokio-dns-unofficial-0.1.1/log.txt)) cc @sbstp
* [x] [topgrade](https://crates.io/crates/topgrade) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/topgrade-0.5.0/log.txt)) cc @r-darwish
* [ ] [travis](https://crates.io/crates/travis) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/travis-0.1.1/log.txt)) cc @softprops

~~Also, the following crates are failing because they depend on `tokio-dns-unofficial`:~~

* ~~[tokio-postgres](https://crates.io/crates/tokio-postgres) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/tokio-postgres-0.3.0/log.txt))~~
* ~~[tokio-tungstenite](https://crates.io/crates/tokio-tungstenite) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/tokio-tungstenite-0.5.1/log.txt))~~
* ~~GitHub repo [grotsev/http_port](https://github.com/grotsev/http_port) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/gh/grotsev.http_port/log.txt))~~

**Comment by mbillingr** [comment] 2018-06-27 14:39
I fixed this in openml by changing `Cow::from(self.as_ref())` to `Cow::from(self.as_str())` (`self` is of type `String`). This is probably how it should have been written anyway.

**Comment by sbstp** [comment] 2018-06-27 15:54
I don't see any errors in the build log of my crate. The fold issue was spotted and fixed a few weeks ago [here](https://github.com/sbstp/tokio-dns/pull/10). It seems like the issue in other crates is because they depend on old versions.

Any clue why this breaking change started happening? I don't think I can release a `0.1.2`.

**Comment by pietroalbini** [comment] 2018-06-27 16:00
> I don't see any errors in the build log of my crate.

Copy-pasted the link for the wrong version, sorry. [This is the one for 0.1.1](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/tokio-dns-unofficial-0.1.1/log.txt).

> Any clue why this breaking change started happening? I don't think I can release a 0.1.2.

I haven't investigated this yet. If it's a bug in the compiler we'll get this fixed before 1.28 reaches stable.

**Comment by sbstp** [comment] 2018-06-27 16:04
Is it possible to backport the fix? The current version is `0.3.1`, is cargo able to publish a `0.1.2` version that's semver compatible with the broken version? I guess I could yank that version, but the existing dependencies will still continue to break.

**Comment by sfackler** [comment] 2018-06-27 16:05
You can publish a 0.1.2

**Comment by r-darwish** [comment] 2018-06-27 17:05
I also changed my code to `as_str` as it makes more sense.

@pietroalbini this process of checking the beta compiler by compiling actual crates is awesome. Is there any place in which I can read more about how it works?

**Comment by mbillingr** [comment] 2018-06-27 17:16
@r-darwish I think [crater](https://github.com/rust-lang-nursery/crater) is the tool in use.

**Comment by Mark-Simulacrum** [comment] 2018-06-27 21:00
This is caused by b559710e58427213d6f82008206c22cf3d76b4c4, probably https://github.com/rust-lang/rust/pull/50170. cc @rust-lang/libs, I've closed https://github.com/rust-lang/rust/issues/50954 as a duplicate of this bug.

**Comment by pietroalbini** [comment] 2018-07-10 17:16
Ping @rust-lang/libs, any news on this?

**Comment by alexcrichton** [comment] 2018-07-10 20:50
We'll be discussing this in this week's triage meeting

**Comment by alexcrichton** [comment] 2018-07-12 18:03
The conclusion of said discussion is that we're going to leave this as-is, but if any crates have difficulty updating we're more than willing to help!

**Closed by alexcrichton** 2018-07-12 18:03 UTC
Labels: I-nominated, T-libs, regression-from-stable-to-beta

**Comment by jq-rs** [comment] 2018-07-12 19:12
Mles-client build is failing due to dependencies, thus it should work now as the dependencies are fixed. Just made a build with nightly, runs smoothly. So it was just miscategorized here.
