### ISSUE TITLE
1.19.0 and nightly ICE: panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/librustc_metadata/creader.rs:1217:17 

### ISSUE THREAD

**Issue by zhendongsu** [rust-lang/rust#43926] opened 2017-08-17 07:09 UTC
```bash
$ rustc-nightly --version
rustc 1.21.0-nightly (f25c2283b 2017-08-15)
$ 
$ rustc-nightly tmp.rs
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (f25c2283b 2017-08-15) running on i686-unknown-linux-gnu

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/librustc_metadata/creader.rs:1217:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ 
$ cat tmp.rs
#[link(name="foo", cfg())] 
extern {}
$ 
```

**Comment by arielb1** [comment] 2017-08-17 19:22
Quasi-duplicate of #42925.

**Comment by topecongiro** [comment] 2018-01-12 12:49
#42925 -> #43925.

**Closed** 2018-01-15 15:37 UTC
Labels: C-bug, I-ICE
