### ISSUE TITLE
Wrong path statement warning with constant implementing Drop

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#71837] opened 2020-05-03 11:47 UTC
This program prints `dropped` as the constant is copied and dropped.
```rust
struct S;
impl Drop for S {
    fn drop(&mut self) {
        println!("dropped")
    }
}
const C: S = S;
fn main() {
    C;
}
```
That means that the statement `C;` does have an effect: it prints `dropped`. But the compiler warns that the statement has no effect:
```
warning: path statement with no effect
 --> src/main.rs:9:5
  |
9 |     C;
  |     ^^
  |
  = note: `#[warn(path_statements)]` on by default
```

(Reproduced on stable 1.43.0 and nightly 2020-05-02.)

**Comment by jonas-schievink** [comment] 2020-05-03 11:50
Duplicate of https://github.com/rust-lang/rust/issues/48852

**Closed by jonas-schievink** 2020-05-03 11:50 UTC
Labels: C-bug
