### ISSUE TITLE
More unused feature warnings?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#43998] opened 2017-08-20 16:10 UTC
I've noticed that several new Nightly features give this error message if you ask for them but you don't use them in your code:

`warning: unused or unknown feature`

While some other features don't give the "unused or unknown feature" warning if you don't use them:

```
#![feature(slice_patterns)]
#![feature(inclusive_range_syntax)]
#![feature(type_ascription)]
#![feature(asm)]
#![feature(stmt_expr_attributes)]
#![feature(conservative_impl_trait)]
#![feature(const_fn)]
fn main() {}
```

Is it possible and a good idea to generate that warning for them too?

**Comment by Mark-Simulacrum** [comment] 2017-08-20 16:33
Duplicate of https://github.com/rust-lang/rust/issues/23528.

**Closed by Mark-Simulacrum** 2017-08-20 16:33 UTC
