### ISSUE TITLE
ICE with proc_macro, attribute on crate

### ISSUE THREAD

**Issue by gmorenz** [rust-lang/rust#41331] opened 2017-04-16 16:10 UTC
Code:

```rust
#![feature(proc_macro)]
#![fake]

fn main() {
    println!("Hello world!");
}
```

Output:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:329
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: syntax::ext::expand::MacroExpander::expand_crate
   1: rustc_driver::driver::phase_2_configure_and_expand::{{closure}}
   2: rustc_driver::driver::phase_2_configure_and_expand
   3: rustc_driver::driver::compile_input
   4: rustc_driver::run_compiler
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
   7: <F as alloc::boxed::FnBox<A>>::call_box
   8: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
   9: start_thread
  10: clone
```

Meta:

```
$ rustc --version --verbose
rustc 1.18.0-nightly (d5cf1cb64 2017-04-15)
binary: rustc
commit-hash: d5cf1cb64cd1948a8c289e29838716f03d49d5aa
commit-date: 2017-04-15
host: x86_64-unknown-linux-gnu
release: 1.18.0-nightly
LLVM version: 3.9
```

**Comment by Mark-Simulacrum** [comment] 2017-04-16 16:27
Duplicate of #41211.

**Closed by Mark-Simulacrum** 2017-04-16 16:27 UTC
