### ISSUE TITLE
if let in block expression position borrow check mismatch

### ISSUE THREAD

**Issue by Zalastra** [rust-lang/rust#41495] opened 2017-04-24 05:43 UTC
I've ran into a borrowing issue using try_borrow() in an if let statement.

The problem occurs when it's the last expression of the scope and is resolved by making it a statement.
I'm not sure if this is a bug or limitation in the borrow checker, but either way the error message is confusing.

[rust play link](https://is.gd/0UL2Uv)

```Rust
fn does_not_compile() {
    let container = RefCell::new(0);
    if let Ok(_) = container.try_borrow() { }
}

fn compiles() {
    let container = RefCell::new(0);
    if let Ok(_) = container.try_borrow() { };
}
```

> rustc 1.16.0 (30cf806ef 2017-03-10)
> error: `container` does not live long enough
>  --> <anon>:6:1
>   |
> 5 |     if let Ok(_) = container.try_borrow() { }
>   |                    --------- borrow occurs here
> 6 | }
>   | ^ `container` dropped here while still borrowed
>   |
>   = note: values in a scope are dropped in the opposite order they are created
>
> error: aborting due to previous error

**Comment by Havvy** [comment] 2017-04-24 05:51
My own findings show that this does not happen with `if`, only with `if let`.

[Playpen](https://is.gd/PIpgLZ)

```rust
#![allow(dead_code)]
use std::cell::RefCell;

fn passes_compile() {
    let container = RefCell::new(0);
    if container.try_borrow().is_ok() { }
}

fn fails_compile_if_let_true() {
    let container = RefCell::new(0);
    if let true = container.try_borrow().is_ok() { }
}

fn fails_compile_match() {
    let container = RefCell::new(0);
    match container.try_borrow().is_ok() {
        true => (),
        _ => ()
    }
}
```

```
rustc 1.16.0 (30cf806ef 2017-03-10)
error: `container` does not live long enough
  --> <anon>:12:1
   |
11 |     if let true = container.try_borrow().is_ok() { }
   |                   --------- borrow occurs here
12 | }
   | ^ `container` dropped here while still borrowed
   |
   = note: values in a scope are dropped in the opposite order they are created

error: `container` does not live long enough
  --> <anon>:20:1
   |
16 |     match container.try_borrow().is_ok() {
   |           --------- borrow occurs here
...
20 | }
   | ^ `container` dropped here while still borrowed
   |
   = note: values in a scope are dropped in the opposite order they are created

error: aborting due to 2 previous errors
```

Furthermore, the Rust reference says that [An `if let` expression is semantically equivalent to an `if` expression](https://doc.rust-lang.org/nightly/reference/expressions.html#if-let-expressions), so the mismatch between the first and second functions in this comment has to be a bug.

**Comment by eddyb** [comment] 2017-04-25 05:39
Closing as duplicate of https://github.com/rust-lang/rust/issues/21114#issuecomment-228331214. The reference is just wrong, only syntax is similar.

**Closed by eddyb** 2017-04-25 05:39 UTC
