### ISSUE TITLE
Trait not implemented with lifetimes and async code

### ISSUE THREAD

**Issue by traxys** [rust-lang/rust#74815] opened 2020-07-27 09:35 UTC
I tried this code:
[playgroud](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=33a114f65e2288f9529bd2624b0c5568)
```rust
use std::future::Future;

pub struct Producer {
    params: Vec<String>,
}

fn spawn<T>(_: T) where
    T: Future + Send + 'static,
    T::Output: Send + 'static,
{}

impl Producer {
    async fn update(&self) {
        let _fetched = self
            .fetch(self.params.iter().map(|s| -> &str { s }))
            .await;
    }
    
    pub async fn fetch(&self, params: impl IntoIterator<Item = &str>) {
        self.inner_fetch(params.into_iter()).await
    }

    pub async fn inner_fetch(&self, params: impl Iterator<Item = &str>) {
        todo!()
    }
}

fn main() {
    let producer = Producer {
        params: Vec::new(),
    };

    spawn(async move { producer.update().await });
}

```

I expected to see this happen: code compiling, or some error showing how could I fix this

Instead, this happened: 

```
error: implementation of `std::iter::Iterator` is not general enough
    --> src/main.rs:33:5
     |
33   |       spawn(async move { producer.update().await });
     |       ^^^^^ implementation of `std::iter::Iterator` is not general enough
     |
     = note: `std::iter::Iterator` would have to be implemented for the type `std::slice::Iter<'0, std::string::String>`, for any lifetime `'0`...
     = note: ...but `std::iter::Iterator` is actually implemented for the type `std::slice::Iter<'1, std::string::String>`, for some specific lifetime `'1`

```

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
binary: rustc
commit-hash: 346aec9b02f3c74f3fce97fd6bda24709d220e49
commit-date: 2020-07-11
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

**Comment by Marwes** [comment] 2020-10-15 11:41
Seeing this when using https://docs.rs/futures/0.3.6/futures/stream/trait.StreamExt.html#method.buffered in some instances.

**Comment by dtolnay** [comment] 2021-01-27 02:39
Closing as a duplicate of #64552.

**Closed by dtolnay** 2021-01-27 02:39 UTC
Labels: C-bug
