### ISSUE TITLE
should_panic doesn't allow static string slices as expected messages

### ISSUE THREAD

**Issue by Pacheco95** [rust-lang/rust#115846] opened 2023-09-14 16:13 UTC
I tried this code:

```rust
const INVALID_DIMENSIONS_ERROR: &'static str = "Rows and cols must not be zero";

#[derive(Debug, Clone, Copy)]
pub struct Matrix<T, const ROWS: usize, const COLS: usize>([[T; COLS]; ROWS]);

impl<T, const ROWS: usize, const COLS: usize> Matrix<T, ROWS, COLS> {
    pub fn new(elements: [[T; COLS]; ROWS]) -> Self {
        assert!(ROWS * COLS != 0, "{}", INVALID_DIMENSIONS_ERROR);
        Self(elements)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    #[should_panic(expected = INVALID_DIMENSIONS_ERROR.a)]
    fn it_should_deny_zero_row_dimension() {
        Matrix::<u32, 0, 1>::new([]);
    }
}

```

I expected test to compile and succeed.

Instead, this compiler error happened:

```
error: expected unsuffixed literal or identifier, found `INVALID_DIMENSIONS_ERROR`
  --> src/lib.rs:41:31
   |
41 |     #[should_panic(expected = INVALID_DIMENSIONS_ERROR)]
   | 
```

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0 (5680fa18f 2023-08-23)
binary: rustc
commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
commit-date: 2023-08-23
host: x86_64-unknown-linux-gnu
release: 1.72.0
LLVM version: 16.0.5
```

<details><summary>Backtrace</summary>
<p>

```
➜ RUST_BACKTRACE=1 cargo test
   Compiling matrix v0.1.0 (/home/michael/repositories/playground/rust/matrix)
error: expected unsuffixed literal or identifier, found `INVALID_DIMENSIONS_ERROR`
  --> src/lib.rs:41:31
   |
41 |     #[should_panic(expected = INVALID_DIMENSIONS_ERROR)]
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `matrix` (lib test) due to previous error
warning: build failed, waiting for other jobs to finish... 
```

</p>
</details>

**Comment by saethlin** [comment] 2023-09-15 00:16
Unlike functions, macros operate on the AST, so it matters that this is not a literal, as the error says. You'll get such behavior from any macro that accepts a string literal. This program doesn't compile for the same reason:
```rust
const HELLO: &'static str = "hello";
pub fn make_str() -> &'static str {
    concat!(HELLO, " world")
}
```

**Comment by saethlin** [comment] 2023-09-15 22:03
I'm closing this because it's not a bug or a feature request. Feel free to correct me if I got that wrong.

**Closed by saethlin** 2023-09-15 22:03 UTC
