### ISSUE TITLE
PathBuf set_extension returns bool, builder pattern impossible

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rust#27506] opened 2015-08-03 22:38 UTC
I think that returning bool when calling  `set_extension` is weird because it breaks the builder pattern that you have with most other methods.

For example I wanted to use it in my project, I have to change the extension from `.md` to `.html`. 
My first try was to do it like this:

```rust
base_path.join(
    PathBuf::from(path_to_markdown_file) // path_to_markdown_file as string
        .set_extension("html") // <-- Error
)
```
But that is not possible because `set_extension` returns `bool` instead of `&self` so I have to split this line in two. 

If you use `with_extension` from `Path` it does work with the builder pattern

```rust
base_path.join(
    Path::new(path_to_markdown_file) // path_to_markdown_file as string
        .with_extension("html")
)
```

Is there any reason to return `bool` and loose the convenience of the builder pattern?

**Comment by nagisa** [comment] 2015-08-03 23:31
First of all, neither of them are supposed to be builders. `with_extension` returns another `PathBuf` for a reason: `Path` is a functional equivalent of slice, therefore you cannot resize the underlying buffer to accommodate for all possible new extensions. `set_extension` returns `bool` because it needs to tell you whether it could set the extension at all (as documentation claims; I personally think it should’ve been Result<(), ()> or something). 

Since `PathBuf` auto-derefs to `Path`, you can easily do something like

```rust
fn main() {
    println!("{:?}", PathBuf::from("hello.md").with_extension("html"))
}
```

therefore there’s no convenience loss either?

**Comment by azerupi** [comment] 2015-08-04 00:04
I understand why Path returns a PathBuf and I didn't know that PatBuf auto-derefs, that's nice. 

I also didn't post this issue because I was inconvenienced either because obviously their are already two alternatives that are as easy. 

But that boolean just seems weird and I wanted to know if it was a conscious design decision or if it was a relic of the past or something like that. :)

> I personally think it should’ve been Result<(), ()> or something).

Indeed a Result would have been more coherent with the rest of std

**Comment by alexcrichton** [comment] 2015-08-04 16:34
As @nagisa points out there are alternate methods available if you would like chaining and otherwise this is all working as intended, so I'm going to close this. Thanks for the report though!

**Closed by alexcrichton** 2015-08-04 16:34 UTC
