### ISSUE TITLE
[NLL] Possible proptest-arbitrary-0.2.2 regression

### ISSUE THREAD

**Issue by lqd** [rust-lang/rust#53789] opened 2018-08-29 14:32 UTC
Filing for investigation.

The recent crater run found an interesting case in `proptest-arbitrary` 0.2.2, which used to compile with AST borrowck.

[Crater logs.](https://crater-reports.s3.amazonaws.com/pr-53426/a5d98b025f62ace80fe9d2a15781f900fc42515e-alt/reg/proptest-arbitrary-0.2.2/log.txt)

There are 2 reproductions: 
- the first collates the necessary parts from `proptest-arbitrary` and `proptest` and reproduces faithfully the messages from the crater run. [Playground](https://play.rust-lang.org/?gist=c990af931ab56d93207efcade0ffd01b&version=nightly&mode=debug&edition=2015).
- the second is a bit more minimal, while still being accepted by AST borrowck. It is however, in an effort to simplify the code, partially automatically reduced to focus on only one of these two identical errors. [Playground](https://play.rust-lang.org/?gist=1f1d03d4f8280b8843594cba668c9db4&version=nightly&mode=debug&edition=2015).

**Comment by nikomatsakis** [comment] 2018-08-29 15:59
I believe this is likely a duplicate of https://github.com/rust-lang/rust/issues/53121

**Comment by lqd** [comment] 2018-08-29 16:38
@nikomatsakis they might be sharing the same cause, but lacking the specific conditions that only fail with --crate-type lib in #53121

**Comment by nikomatsakis** [comment] 2018-09-11 15:26
Adding to the RC 2 milestone. Hopefully a dup of #53121. Assigning to myself as I am investigating both of them now.

**Comment by nikomatsakis** [comment] 2018-09-21 23:34
Fix in #54453

**Closed** 2018-09-26 20:48 UTC
Labels: A-NLL, NLL-complete
