### ISSUE TITLE
Smarter derive(Default) for PhantomData

### ISSUE THREAD

**Issue by ark0f** [rust-lang/rust#69037] opened 2020-02-10 18:40 UTC
```rust
use std::marker::PhantomData;

struct TypeWithoutDefault;

#[derive(Default)]
struct NewType<T>(PhantomData<T>);

fn main() {
    let _ = NewType::<TypeWithoutDefault>::default();
    // ^ E0599
    // no function or associated item named `default` found 
    // for type `NewType<TypeWithoutDefault>` in the current scope
}
```
But if we implement `Default` without derive:
```rust
impl<T> Default for NewType<T> {
    fn default() -> Self {
        Self(PhantomData)
    }
}
```
Then code compiles successfully.

Can `derive(Default)` be smarter for cases like this?

**Comment by jonas-schievink** [comment] 2020-02-10 18:41
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2020-02-10 18:41 UTC
