### ISSUE TITLE
Compiler told me to report bug: "can't determine value for sysroot"

### ISSUE THREAD

**Issue by logicchains** [rust-lang/rust#16229] opened 2014-08-04 00:48 UTC
I encountered the following output when trying to compile a simple program (well, any simple program) with rustc:

```
error: internal compiler error: unexpected failure
note: the compiler hit an unexpected failure path. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
task 'rustc' failed at 'can't determine value for sysroot', /build/rust/src/rust-nightly/src/librustc/metadata/filesearch.rs:179
```

And so I'm duly reporting it. My OS is the latest ARMv7 ArchLinux build, running on a Galaxy SIII (in a chroot). It was working previously, but then I rebooted the phone and attempted to run rustc before I had properly mounted sysfs, proc and devpts. If I mount those, it works fine. So the bug isn't an actual hindrance, but nevertheless I'm reporting it as requested by the compiler.

**Comment by steveklabnik** [comment] 2015-04-21 00:21
Triage bump. @logicchains , does this still ICE in this situation?

**Comment by logicchains** [comment] 2015-04-22 14:13
Unfortunately I don't have that ARM system setup now. I could test it in an
x86 chroot Arch Linux without mounting sysfs and proc, would that be any
use?

**Comment by steveklabnik** [comment] 2015-04-22 14:56
It depends. This was filed a long time ago, and we haven't heard of anything from anyone since, so maybe just giving it a close is appropriate, since it no longer affects you?

**Comment by logicchains** [comment] 2015-04-23 09:01
Sure, closing it would be fine with me. I only opened it because the
compiler told me to.

**Comment by bryteise** [comment] 2015-10-20 17:23
Just as a bump, I still see this on an x86_64 in a chroot without proc, sys and dev mounted trying to build 1.3.0.

**Comment by thegatsbylofiexperience** [comment] 2017-01-29 07:36
1.14.0 error string: thread 'rustc' panicked at '../src/librustc/session/filesearch.rs:164: can't determine value for sysroot', ../src/librustc/session/mod.rs:771

**Comment by thegatsbylofiexperience** [comment] 2017-01-29 14:20
I managed to get all working again after upgrading my container host os and rebooting. Not sure which part of the two fixed it. Thanks, and sorry for wasting time.

**Comment by Mark-Simulacrum** [comment] 2017-05-20 03:04
Not a waste of time! Seems like this isn't really reproducible in most cases; closing.

**Closed by Mark-Simulacrum** 2017-05-20 03:04 UTC
Labels: I-ICE
