### ISSUE TITLE
std::f32 impl Float is duplicated

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#22025] opened 2015-02-06 22:40 UTC
[`std::f32`](http://doc.rust-lang.org/nightly/std/primitive.f32.html) doc page has `impl Float for f32` at the top and at the bottom.
* The bottom one seems to have more elements though it's not clear why.
* Their styling is the same so it's not obvious if they should mean 2 different things.

Something should change so either they don't look like misshapen clones or it's clear what they mean.

**Comment by nagisa** [comment] 2015-03-01 20:28
Possibly a dupe of https://github.com/rust-lang/rust/issues/21474

**Comment by mdinger** [comment] 2015-03-01 21:07
Perhaps but this doesn't use globs as far as I can tell which is the requirement for that other bug.

**Comment by nagisa** [comment] 2015-03-01 21:10
Ah ritgh, one is `core::num::Float` and another is `std::num::Float`. Two distinct traits.

**Comment by mdinger** [comment] 2015-03-01 21:22
I'm not sure what can be done here then. Since `core` is in general not recommended to be used, maybe external linking (from outside of `core`) to it should be opt-in, not opt out. Then these links would only appear where an author decides it's useful.

**Closed** 2015-04-10 19:17 UTC
Labels: A-rustdoc
