### ISSUE TITLE
Missing tokens in custom derive input generated by macro

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#51331] opened 2018-06-03 17:45 UTC
The script below has a macro_rules macro that expands to:

```rust
#[derive(Print)]
pub struct S(<MyDispatch as $crate::Dispatch>::Call);
```

But inside of the `derive(Print)` custom derive the tokens received are:

```rust
pub struct S(<MyDispatch as ::repro_dispatch>::Call);
```

The `::Dispatch` seems to be missing.

Originally reported in https://github.com/serde-rs/serde/issues/1306.

---

rustc 1.28.0-nightly (4ecf12bf0 2018-06-02)
Repro script:

```bash
#!/bin/sh

cargo new --lib repro
cargo new --lib repro_dispatch
cargo new --lib repro_derive

echo >repro/src/lib.rs '
#[macro_use]
extern crate repro_dispatch;

#[macro_use]
extern crate repro_derive;

pub struct MyDispatch;

impl repro_dispatch::Dispatch for MyDispatch {
    type Call = ();
}

problem!();
'

echo >>repro/Cargo.toml '
repro_dispatch = { path = "../repro_dispatch" }
repro_derive = { path = "../repro_derive" }
'

echo >repro_dispatch/src/lib.rs '
pub trait Dispatch {
    type Call;
}

#[macro_export]
macro_rules! problem {
    () => {
        #[derive(Print)]
        pub struct S(<MyDispatch as $crate::Dispatch>::Call);
    }
}
'

echo >repro_derive/src/lib.rs '
extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_derive(Print)]
pub fn derive(input: TokenStream) -> TokenStream {
    println!("\n\n{}\n\n", input);
    "".parse().unwrap()
}
'

echo >>repro_derive/Cargo.toml '
[lib]
proc-macro = true
'

cargo build --manifest-path repro/Cargo.toml
```

**Comment by dtolnay** [comment] 2018-06-03 17:48
The behavior is correct with rustc 1.15.0 but the current incorrect behavior exists since 1.16.0.

**Comment by nikomatsakis** [comment] 2018-06-07 14:28
Also, how does it come to happen that `$crate` is still in there and not replaced during macro expansion...? Maybe I'm unclear on the phasing of how `$crate` works.

**Comment by nikomatsakis** [comment] 2018-06-07 14:28
Marking as P-high but don't have an assignee yet, will revisit next week when we've hopefully had a chance to bisect.

**Comment by Mark-Simulacrum** [comment] 2018-06-07 15:15
2016-12-06 has the odd result of `pub struct S(<MyDispatch as ::::Dispatch>::Call);`.

2016-12-27 is the first nightly to have `pub struct S(<MyDispatch as ::repro_dispatch>::Call);` as the result; the previous nightly 2016-12-23 has the (correct, I presume) `pub struct S(<MyDispatch as ::repro_dispatch::Dispatch>::Call);` result.

**Comment by Mark-Simulacrum** [comment] 2018-06-07 20:47
I was.. largely unsuccessful at running git bisect. Maybe someone else will have more luck.

**Comment by ExpHP** [comment] 2018-06-08 11:46
I figure it's easier to bisect the Bors commits which are sure to build correctly, rather than to run `git bisect`.  Overnight I ran a build of 467a7f049, and got the erroneous output, cutting it down to these:

467a7f0 Auto merge of #38533 - jseyfried:legacy_custom_derive_deprecation, r=nrc
00b4019 Auto merge of #38529 - nrc:save-sig, r=nikomatsakis
ce4461f Auto merge of #38511 - Mark-Simulacrum:drop-glue, r=eddyb
99913c5 Auto merge of #38401 - redox-os:redox_cross, r=brson
82611a0 Auto merge of #38232 - jseyfried:refactor_global_paths, r=nrc
c8e7ec4 Auto merge of #38562 - brson:rm-llvm-lock, r=brson

**Comment by ExpHP** [comment] 2018-06-08 19:16
Okay, I have confirmed that 82611a0 exhibits the issue, and c8e7ec4 does not, so it is #38232. cc @jseyfried

**Comment by ExpHP** [comment] 2018-06-10 19:33
The following test case (replacing the similarly-named macro in the OP) helps clarify the nature of the bug.  It is not "overwriting" the `Dispatch` path component, but rather, it is missing the entire last path component (with type parameters):

```
#[macro_export]
macro_rules! problem {
    () => {
        #[derive(Print)]
        pub struct S(<MyDispatch as $crate::Dispatch::Second<Test>>::Call);
    }
}
```
The `::Second<Test>` is dropped:
```
pub struct S(<MyDispatch as ::repro_dispatch::Dispatch>::Call);
```

(**Note:** tested on nightly, because I foolishly did not keep my build of 82611a0)

---

The PR is largely one refactoring commit.  I've been reading through looking for the kinds of things that might cause a bug like this, but haven't found the culprit.

**Comment by ExpHP** [comment] 2018-06-10 22:02
**I have a theory.**  I believe this was buggy prior to jseyfried's PR, but the PR caused the bug to affect this specific test case.

---

The following function in `libsyntax_ext` uses a `Folder` to normalize `$crate` away from paths:

https://github.com/jseyfried/rust/blob/f10f50b42639718b2580d10802f05f2b6ff209d5/src/librustc_resolve/macros.rs#L102-L123

However, the trait path is stored in a `QSelf`, which stores a `position` field indicating the end of the trait path.  The method linked above only overrides `fold_path`, but the default definitions for `fold_ty`, `fold_expr`, and `fold_pat` all simply [fold the path and keep the old `position`](https://github.com/jseyfried/rust/blob/f10f50b42639718b2580d10802f05f2b6ff209d5/src/libsyntax/fold.rs#L375-L383).

Prior to the PR, a path segment was deleted if (and only if) the macro was local.  After the PR, a path segment is inserted if (and only if) the macro was from another crate.  In each of these cases, the QSelf position field is invalidated.

---

If my theory is correct, then prior to #38232, it should have manifested as printing *extra* tokens if the definition of `problem!` is moved from `repro_dispatch` to `repro`.  (However I no longer have the c8e7ec4 build, and I'm not sure where @Mark-Simulacrum is successfully downloading ancient nightlies from!)

**Comment by Mark-Simulacrum** [comment] 2018-06-10 22:09
I'm downloading nightlies via cargo-bisect-rustc's bisection; I also found that for some reason rustup itself refuses to install those nightlies.

**Comment by ExpHP** [comment] 2018-06-10 22:55
Thanks!

I was able to verify my prediction; `nightly-2016-12-23` handles the original test case correctly, but duplicates the `::Call` when the macro is defined locally:

```rust
#[nonlocal]
pub struct S(<MyDispatch as ::repro_dispatch::Dispatch::Second<Test>>::Call);

#[local]
pub struct S(<MyDispatch as ::Dispatch::Second<Test>::Call>::Call);
```

<details>
<summary>Repro with local and nonlocal macros</summary>

```
#!/bin/sh

# set the linked toolchain here
TOOLCHAIN=bisector-nightly-2016-12-23-x86_64-unknown-linux-gnu

rm -rf repro
rm -rf repro_dispatch
rm -rf repro_derive
cargo new --lib repro
cargo new --lib repro_dispatch
cargo new --lib repro_derive

echo >repro/src/lib.rs '
#[macro_use]
extern crate repro_dispatch;

#[macro_use]
extern crate repro_derive;

pub struct MyDispatch;

impl repro_dispatch::Dispatch for MyDispatch {
    type Call = ();
}

#[macro_export]
macro_rules! problem_local {
    () => {
        #[derive(Print)]
        #[local]
        pub struct S(<MyDispatch as $crate::Dispatch::Second<Test>>::Call);
    }
}

problem!();
problem_local!();
'

echo >>repro/Cargo.toml '
repro_dispatch = { path = "../repro_dispatch" }
repro_derive = { path = "../repro_derive" }
'

echo >repro_dispatch/src/lib.rs '
pub trait Dispatch {
    type Call;
}

#[macro_export]
macro_rules! problem {
    () => {
        #[derive(Print)]
        #[nonlocal]
        pub struct S(<MyDispatch as $crate::Dispatch::Second<Test>>::Call);
    }
}
'

echo >repro_derive/src/lib.rs '
#![feature(proc_macro, proc_macro_lib)]
extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_derive(Print)]
pub fn derive(input: TokenStream) -> TokenStream {
    println!("\n\n{}\n\n", input);
    "".parse().unwrap()
}
'

echo >>repro_derive/Cargo.toml '
[lib]
proc-macro = true
'

CARGO_INCREMENTAL=0 cargo +$TOOLCHAIN build --manifest-path repro/Cargo.toml
CARGO_INCREMENTAL=0 cargo +$TOOLCHAIN rustc --manifest-path repro/Cargo.toml -- --version
```

</details>

---

I'll start working on a PR.

**Comment by ExpHP** [comment] 2018-06-10 23:20
Silly question: Would adding an AST type like

```rust
pub struct QPath(Option<QSelf>, Path);
```
be overkill? This pattern describes all appearances of `QSelf` in the AST, and I feel the most principled solution to this bug would be to add a `fold_qpath` method.

**Comment by ExpHP** [comment] 2018-06-11 23:12
Since I wasn't sure about the above, I wrote two possible fixes, both of which I am now testing:

* A self-contained fix that makes `EliminateCrateVar` override `fold_{expr,ty,pat}`, but it's messy
* A cleaner fix that involves adding the following method to `syntax::fold::Folder`:
  ```rust
  fn fold_qpath(&mut self, Option<QSelf>, Path) -> (Option<QSelf, Path)
  ```

**Comment by petrochenkov** [comment] 2018-06-12 06:19
@ExpHP 
New `fold_qpath` delegating to `fold_path` by default (without changing qpaths in AST) looks like a good solution.

**Comment by ExpHP** [comment] 2018-06-12 13:02
Thanks for the feedback! [PR is up](https://github.com/rust-lang/rust/pull/51519).

**Closed** 2018-06-12 17:37 UTC
Labels: A-macros, C-bug, P-high, T-compiler, regression-from-stable-to-stable
