### ISSUE TITLE
Guide:mismatched types ->E0380 when cargo run in guess_game 

### ISSUE THREAD

**Issue by chunaife** [rust-lang/rust#28883] opened 2015-10-07 11:21 UTC
i wrote the code ,but error occured when cargo run,this error is :mismatched types  E0380,i know why this occured,because rust book have tell me,the point is :why i wrote code as like rust book,it can't cargo run success?
i wrote this code follow the example:
let guess: u32 = guess.trim().parse()
     .ok()
     .expect("Please type a number!");

Thanks

**Comment by apasel422** [comment] 2015-10-07 11:59
Can you provide the entirety of the code that you tried to compile?

**Comment by chunaife** [comment] 2015-10-07 12:13
extern crate rand;
use std::io;
use rand::Rng;
use std::cmp::Ordering;


fn main() {
    println!("Guessing game!");

    let secret_number = rand::thread_rng().gen_range(1,101);
    println!("The sercet number {}",secret_number);

    println!("Please enter number!");
    let mut guess = String::new();

    io::stdin().read_line(&mut guess)
        .ok()
        .expect("Faile to read line!");

    let guess: i33 = guess.trim().parse()
        .ok()
        .expect("Please type a number!");

    println!("You enter number {}",guess);

    match guess.cmp(&secret_number)
    {
         Ordering::Less =>("Too small!"),
         Ordering::Greater =>("Too big!"),
         Ordering::Equal =>("You win!"),
    }
}

That's all,where is worry?thanks

**Comment by apasel422** [comment] 2015-10-07 12:20
Did you just type that in instead of copy-pasting? There's no such thing as `i33`. [The real text](https://doc.rust-lang.org/book/guessing-game.html) uses `u32` and compiles and runs successfully with Cargo.

This issue is not a bug and can be closed.

**Comment by apasel422** [comment] 2015-10-07 12:27
After you change `i33` to `u32`, the other error is that the `match` needs to be changed to:
```rust
match guess.cmp(&secret_number) {
     Ordering::Less => println!("Too small!"),
     Ordering::Greater => println!("Too big!"),
     Ordering::Equal => println!("You win!"),
}
```

**Comment by chunaife** [comment] 2015-10-07 12:45
oh!,that's right,i did not notice that,thanks very much!!!!

**Comment by apasel422** [comment] 2015-10-07 12:55
@chunaife Can you close this issue then?

**Closed** 2015-10-07 14:11 UTC
