### ISSUE TITLE
"borrow of possibly uninitialized variable" instead of "use of moved value"

### ISSUE THREAD

**Issue by stephaneyfx** [rust-lang/rust#52669] opened 2018-07-24 17:53 UTC
NLL combined with a struct field assignment gives an error mentioning the use/borrow of an uninitialized variable instead of the use/borrow of a moved variable.

# Reproduction example

*Simplified code based on @Yatekii's question on IRC*
[Playground](https://play.rust-lang.org/?gist=3458f67aa4fb164d002ad105c6d6d497&version=nightly&mode=debug&edition=2015)
```rust
#![feature(nll)]

struct A {
    b: B,
}

#[derive(Clone)]
struct B;

fn foo(_: A) {}

fn bar(mut a: A) -> B {
    // Commenting the line below gives a move error instead of uninitialized
    // error.
    a.b = B;
    foo(a);
    a.b.clone()
}

fn main() {}
```

# Expected behavior

The compiler gives an error about using a moved value, similar to the following:

Without NLL:
```
error[E0382]: use of moved value: `a.b`
  --> src/main.rs:17:5
   |
16 |     foo(a);
   |         - value moved here
17 |     a.b.clone()
   |     ^^^ value used here after move
   |
   = note: move occurs because `a` has type `A`, which does not implement the `Copy` trait
```

With NLL but without the field assignment:
```
error[E0382]: borrow of moved value: `a.b`
  --> src/main.rs:17:5
   |
16 |     foo(a);
   |         - value moved here
17 |     a.b.clone()
   |     ^^^ value borrowed here after move
   |
   = note: move occurs because `a` has type `A`, which does not implement the `Copy` trait
```

# Actual behavior

The error mentions an uninitialized value instead of a moved value:

```
error[E0381]: borrow of possibly uninitialized variable: `a.b`
  --> src/main.rs:17:5
   |
17 |     a.b.clone()
   |     ^^^ use of possibly uninitialized `a.b`
```

**Comment by nikomatsakis** [comment] 2018-08-21 18:54
I would classify this as a "minor diagnostic improvement". I'm moving to the Milestone and marking as E-needs-mentor.

**Comment by csmoe** [comment] 2018-08-22 12:01
this issue may caused by `Place` checking I guess:
https://github.com/rust-lang/rust/blob/71a1ef181683615f1c8da5efb3d8617c0b743009/src/librustc_mir/borrow_check/mod.rs#L1620
the comment reasons why the `uninitialized` lint emitted here: for place `a.b`, if `a` is moved, then the usage of projection `a.b` will be marked as `uninitialized`, let's take an experiment:
https://play.rust-lang.org/?gist=12d7880fc733e74b5bac20119465ada3&version=nightly&mode=debug&edition=2015
```rust
fn bar(mut a: A) -> B {
    a.b = B;
    foo(a);
    a.b
}
```
=> 
```
error[E0381]: use of possibly uninitialized variable: `a.b`
  --> src/main.rs:16:5
   |
16 |     a.b
   |     ^^^ use of possibly uninitialized `a.b`
```

==========

instead of using place `a.b`, we return `a`:
```rust
```rust
fn too(mut a: A) -> A {
    a.b = B;
    foo(a);
    a
}
```
=> 
```
error[E0382]: use of moved value: `a`
  --> src/main.rs:16:5
   |
15 |     foo(a);
   |         - value moved here
16 |     a
   |     ^ value used here after move
   |
   = note: move occurs because `a` has type `A`, which does not implement the `Copy` trait

```

**Comment by nikomatsakis** [comment] 2018-09-06 18:43
Clearly not an RC blocker

**Comment by nikomatsakis** [comment] 2018-09-11 14:43
[Still occurs](https://play.rust-lang.org/?gist=f0e4e60402093181825d9e06991995e0&version=nightly&mode=debug&edition=2015)

**Comment by nikomatsakis** [comment] 2018-09-11 14:43
Seems worth fixing to me for RC2 — this could be a "new user stumbling point".

**Comment by nikomatsakis** [comment] 2018-09-11 14:44
Might be a good fit for @spastorino, who recently did https://github.com/rust-lang/rust/issues/46590, which is touching the same code that produces this error. Thoughts @spastorino ?

**Closed** 2018-09-20 11:48 UTC
Labels: A-NLL, A-diagnostics, C-enhancement, E-needs-mentor, NLL-diagnostics
