### ISSUE TITLE
Calling read_to_string and passing in a &Vec causes a compiler panic on beta / nightly

### ISSUE THREAD

**Issue by ChrisMacNaughton** [rust-lang/rust#33616] opened 2016-05-13 16:43 UTC
https://is.gd/00IdzU

**Comment by durka** [comment] 2016-05-13 17:45
Actually it panics on stable too, but manages to print the error first.

**Comment by TimNN** [comment] 2016-05-14 11:20
Another duplicate of #31964.

**Closed** 2016-05-16 17:30 UTC
