### ISSUE TITLE
Regression on beta for trait bounds on supertrait's associated items

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#26813] opened 2015-07-05 23:39 UTC
The following playpen works on 1.0, Stable(1.1) and Nightly(1.3 bf3c979ec 2015-06-30) but fails to compile on current Beta (1.2). 

http://is.gd/cQJ1Xk

It would be good if we could backport whatever fixed the behavior for 1.3.

cc @nagisa

**Comment by huonw** [comment] 2015-07-08 20:35
triage: I-nominated

Seems to be a regression.

**Comment by nikomatsakis** [comment] 2015-07-09 17:10
It's unclear what's changed here. @nrc do you think this could be the DST coercion stuff? It wasn't obvious to me that it was, but it's a possible candidate, in which case @eddyb was perhaps right ;P.

**Comment by nikomatsakis** [comment] 2015-07-09 17:10
triage: P-high (regression)

**Comment by nikomatsakis** [comment] 2015-07-09 17:12
Not sure who to assign this one too! I'll take it for now.

**Comment by nrc** [comment] 2015-07-09 19:11
Seems unlikely to be DST-related to me

**Comment by brson** [comment] 2015-09-11 17:41
@nikomatsakis Any new insight into this one? I believe this is about to hit stable in 1.3.

**Comment by eddyb** [comment] 2015-09-11 18:44
@brson It works on beta and nightly on the playpen, but not stable, so presumably it will work again in 1.3.

**Comment by brson** [comment] 2015-09-11 19:57
@eddyb Oh, so this is fixed? Can we close?

**Comment by eddyb** [comment] 2015-09-12 14:24
cc @nikomatsakis Can you confirm? I'm not entirely sure what the story was here.

**Comment by nikomatsakis** [comment] 2015-09-14 16:56
I'm not 100% sure what happened here. It sure *appears* that there was a transient bug which was fixed, but I'm not sure what that bug was. The code appears legit at first glance.

**Comment by nikomatsakis** [comment] 2015-09-14 16:56
So basically I think yes we can close.

**Closed** 2015-09-14 17:51 UTC
Labels: I-stable-regression, P-high, relnotes, T-lang
