### ISSUE TITLE
Improve error message when using Self in impl enum

### ISSUE THREAD

**Issue by 0xrgb** [rust-lang/rust#56104] opened 2018-11-20 16:00 UTC
```rust
#[derive(Debug)]
enum MainError {
    IO(std::io::Error),
    Parse(std::num::ParseIntError),
}

impl From<std::io::Error> for MainError {
    fn from(e: std::io::Error) -> Self {
        Self::IO(e)
    }
}

impl From<std::num::ParseIntError> for MainError {
    fn from(e: std::num::ParseIntError) -> Self {
        Self::Parse(e)
    }
}
```

Compiling above code give errors,

```
error[E0599]: no variant named `IO` found for type `MainError` in the current scope
  --> src\main.rs:12:9
   |
5  | enum MainError {
   | -------------- variant `IO` not found here
...
12 |         Self::IO(e)
   |         ^^^^^^^^ variant not found in `MainError`
   |
   = note: did you mean `MainError::IO`?
```

The error message is helpful (it indicates correct code, `MainError::IO`). However, the first line of message is confusing, and [E0599](https://doc.rust-lang.org/error-index.html#E0599) does not help much to understand why this code is not working.

Can we improve error messages for such situations?

**Comment by csmoe** [comment] 2018-11-21 06:52
enum variants through `Self` is not allowed right now
cc https://github.com/rust-lang/rust/issues/51994#issuecomment-437641038
@Centril  is there any plan to make it possible?

**Comment by Centril** [comment] 2018-11-21 06:58
@csmoe  Yes; `Self::Variant(...)` should become legal eventually but this is https://github.com/rust-lang/rust/issues/49683.

**Comment by estebank** [comment] 2019-04-29 21:01
Current output:

```
error: enum variants on type aliases are experimental
  --> src/lib.rs:10:9
   |
10 |         Self::IO(e)
   |         ^^^^^^^^
   |
   = help: add `#![feature(type_alias_enum_variants)]` to the crate attributes to enable

error: enum variants on type aliases are experimental
  --> src/lib.rs:16:9
   |
16 |         Self::Parse(e)
   |         ^^^^^^^^^^^
   |
   = help: add `#![feature(type_alias_enum_variants)]` to the crate attributes to enable
```
Duplicate of https://github.com/rust-lang/rust/issues/52118

**Closed by estebank** 2019-04-29 21:01 UTC
Labels: A-diagnostics, A-resolve
