### ISSUE TITLE
Ownership violation not caught 

### ISSUE THREAD

**Issue by jmalima69** [rust-lang/rust#45796] opened 2017-11-05 22:28 UTC
The following code compiles with no errors, although it violates the ownership rules.

struct Image {
	length: u16,
	height: u16,
}

fn main() {
	let mut img = Image{length: 1200, height: 800};
	print_image(img);
	img.length = 1024;
	//let l = img.length;
}

fn print_image(i: Image) {
	println!("Image size {} x {}", i.length, i.height);
}

Surprisingly uncommenting the line that takes the value of img.length triggers the compiler error, but assigning a new value to img,length doesn't, even though both happen after ownership has been transfered to print_image().
Is this a bug or am I missing something?
Thanks.

**Comment by jonas-schievink** [comment] 2017-11-05 22:31
This is known behaviour. It isn't really a dangerous bug (the compiler still denies uses of uninitialized data, as you found out), it's just odd.

Duplicate of https://github.com/rust-lang/rust/issues/21232 in any case, read that issue for more information.

**Closed** 2017-11-05 22:35 UTC
