### ISSUE TITLE
Probably incorrect E0282, but diagnostics too bad for me to tell

### ISSUE THREAD

**Issue by daniel-vainsencher** [rust-lang/rust#32295] opened 2016-03-16 19:35 UTC
As issue #25633 mentions, there is very little information given for this error. In my case I get:

```
src/lib.rs:181:29: 181:38 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
src/lib.rs:181         let x_no_j = xdiffs.submatrix(&all_sample_diffs, &all_but_j);
                                           ^~~~~~~~~
src/lib.rs:181:29: 181:38 help: run `rustc --explain E0282` to see a detailed explanation
```

Not sure why, this information is given twice, which is pretty common in my experience. This is separate from the diagnostics issue mentioned above because the signature for submatrix is:
`fn submatrix(self, rows: &Vec<Ix>, columns: &Vec<Ix>) -> MA` 
(fixed, had written without code escaping: fn submatrix(self, rows: &Vec<Ix>, columns: &Vec<Ix>) -> Self;)

where Ix = usize. In other words, to my knowledge, there aren't any unbound type parameters...

when trying to verify this by inserting a line, I get:

```
src/lib.rs:182:13: 182:15 error: mismatched types:
 expected `ndarray::ArrayBase<collections::vec::Vec<f64>, (usize, usize)>`,
    found `()`
(expected struct `ndarray::ArrayBase`,
    found ()) [E0308]
src/lib.rs:182         let () = xdiffs.submatrix(&all_sample_diffs, &all_but_j);
                           ^~
```

which also does not show any unbounded type parameters.

Any help welcome. Sorry the repo where I get this is private, I hope the above information helps.

**Comment by jonas-schievink** [comment] 2016-03-16 19:57
The signature of `submatrix` seems wrong, `Vec`'s type parameters are gone (I'm assuming it's a copy-paste error). I also can't see where you used `Ix` (might be related).

**Comment by daniel-vainsencher** [comment] 2016-03-16 19:57
Ok, found the problem in my code. The definition for submatrix comes from:

````
trait Mat<D: NdFloat> {
    fn submatrix(self, rows: &Vec<Ix>, columns: &Vec<Ix>) -> Self;
}

impl<D: NdFloat> Mat<D> for MA {
    fn submatrix(self, rows: &Vec<Ix>, columns: &Vec<Ix>) -> MA {
        let mut x = MA::zeros((rows.len(), columns.len()));
        for ((i,&io),(j,&jo)) in rows.iter().enumerate().zip(columns.iter().enumerate()) {
            x[(i,j)] = self[(io,jo)];
        }
        x
    }
}
````
where `pub type MA = OwnedArray<f64, (Ix,Ix)>`.
Then the missing type parameter is not in the trait method at all; removing the parameter D from the impl (since MA is already specify the float is an f64) fixes the problem.

**Comment by daniel-vainsencher** [comment] 2016-03-16 20:00
Specifically what works is `impl Mat<f64> for MA {`.

So it turns out the question is whether we can get an error message at the implementation site, instead of at the call site?

**Comment by jonas-schievink** [comment] 2016-03-16 20:02
The implementation is fine, the compiler just can't figure out which type to use for type parameter `D` (since any type implementing `NdFloat` would work)

**Comment by daniel-vainsencher** [comment] 2016-03-16 20:04
I fixed the escaping issue in the original comment. 

Well, the implementation was declaring parameter D and not using it anywhere, removing the parameter D from it fixed the problem. Why would I suspect this from an error that focuses on a particular function call, for a function that does not mention this type parameter?

**Comment by daniel-vainsencher** [comment] 2016-03-16 20:12
Looks like A-Diagnostics after all.

**Comment by jonas-schievink** [comment] 2016-03-16 20:25
Oh yeah I absolutely agree that the diagnostic is bad, but the impl is not at fault here (the impl is perfectly usable if you use UFCS: `<MA as Mat<f64>>::submatrix`). However, I don't think there are many uses for an impl like this. That said, this does look like a duplicate of #25633

**Comment by daniel-vainsencher** [comment] 2016-03-18 01:40
The fact that the impl is usable by fully specifying parameters that it does not depend on does not make it correct IMO. 

Is it ever correct for a trait to include a function that uses less than all of its type parameters? If so, what are the expectations when calling this function?

Either we can call it without specifying parameters it does not rely on, despite those parameters being part of the trait, or we have to recognize and explain to the user that the trait instance is not fully specified, regardless of the particular function that is being called.

If anyone ever looks into improving messages for E0282, they should definitely see both #25633 and this problem, they are completely different cases in terms of the information the user should receive.

**Comment by Mark-Simulacrum** [comment] 2017-05-05 22:54
I'm going to close this in favor of #25633. I have re-read the discussion here, and I don't see anything actionable here aside from what's noted in that issue.

**Closed by Mark-Simulacrum** 2017-05-05 22:54 UTC
