### ISSUE TITLE
No way to get to docs for previous versions of std

### ISSUE THREAD

**Issue by plumenator** [rust-lang/rust#67345] opened 2019-12-16 07:35 UTC
# Content Bug Report

## Page(s) Affected
https://doc.rust-lang.org/std/index.html

## What needs to be fixed?
Missing a drop down to select the version of `std`

## Workaround
Edit the URL directly like so:
```
https://doc.rust-lang.org/<version>/std/index.html
```

## Suggested Improvement
Like at docs.rs, it would be great if we could switch between versions of the documentation.

**Comment by plumenator** [comment] 2019-12-16 07:36
Moved from rust-lang/www.rust-lang.org#965

**Comment by lzutao** [comment] 2019-12-16 08:39
It does, for example https://doc.rust-lang.org/1.37.0/std/index.html

**Comment by plumenator** [comment] 2019-12-16 09:04
Sorry, I meant to say that there's no way from the UI. One has to already know (or guess) the URL to access it

**Comment by plumenator** [comment] 2019-12-16 09:05
Updated to description with the workaround

**Comment by jonas-schievink** [comment] 2019-12-16 10:13
This doesn't really belong in this repo either as rustdoc documents one crate at a time and doesn't know about other versions. docs.rs already does something like this for ecosystem crates, maybe that's something to look into for libstd too?

**Comment by plumenator** [comment] 2019-12-16 11:57
I think it would be less of an issue if we could generate it locally with cargo. For `std`, the local docs send you to the website.

**Comment by lzutao** [comment] 2019-12-16 12:29
What are the uses of rustdoc for specific Rust version? Since Rust is really good at
keeping backward compatibility.

**Comment by ehuss** [comment] 2019-12-16 15:55
I think this is a duplicate of #44687 (RFC 1826 which includes a version selector) and #30062.

**Comment by jonas-schievink** [comment] 2019-12-16 15:57
Closing in favor of https://github.com/rust-lang/rust/issues/30062

**Closed by jonas-schievink** 2019-12-16 15:57 UTC
Labels: C-feature-request, T-doc
