### ISSUE TITLE
Unexpected panic: Box<Any>

### ISSUE THREAD

**Issue by kazimuth** [rust-lang/rust#23088] opened 2015-03-05 21:27 UTC
Error while compiling tomaka/glutin@7154ea5 on OS X Yosemite:
```sh
$ RUST_BACKTRACE=1 cargo build --verbose
[...dependency updates...]
   Compiling glutin v0.0.6 (file:///path/to/glutin)
[...various warnings...]
/Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/sync/mutex.rs:177:37: 180:2 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 20967, node: ExprStruct(Path { span: Span { lo: BytePos(4847499), hi: BytePos(4847510), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(1770102), hi: BytePos(1770106), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 20968, node: ExprPath(None, Path { span: Span { lo: BytePos(4847523), hi: BytePos(4847538), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4847523), hi: BytePos(4847538), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4847517), hi: BytePos(4847538), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(1770129), hi: BytePos(1770135), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 20969, node: ExprPath(None, Path { span: Span { lo: BytePos(4847552), hi: BytePos(4847569), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4847552), hi: BytePos(4847569), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4847544), hi: BytePos(4847569), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(4847499), hi: BytePos(4847572), expn_id: ExpnId(4294967295) } })
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libsyntax/diagnostic.rs:129

stack backtrace:
   1:        0x111897b52 - sys::backtrace::write::h6b0889bc971c1ad3IDA
   2:        0x1118c6844 - panicking::on_panic::h0fcd1d74630df38dKsJ
   3:        0x1117e4c67 - rt::unwind::begin_unwind_inner::h56b969a14fc61916gbJ
   4:        0x110f6b95e - rt::unwind::begin_unwind::h7097931347514503270
   5:        0x110f6b90b - diagnostic::SpanHandler::span_bug::hd809ae68b3d05ee6h0D
   6:        0x10e73ed7c - session::Session::span_bug::h5bc4aa3cff230a98ISp
   7:        0x10e467134 - trans::debuginfo::scope_metadata::hbc8249b53299cdbdSjE
   8:        0x10e371fb9 - trans::debuginfo::set_source_location::h27a07f90a8aeec578MD
   9:        0x10e323925 - trans::expr::trans_into::h4a29f680db4b3526znh
  10:        0x10e323c45 - trans::expr::trans_into::h4a29f680db4b3526znh
  11:        0x10e38a2c0 - trans::expr::trans_uniq_expr::h9953b7ba5686a321ukj
  12:        0x10e38b053 - trans::expr::trans_unary::h112ae451f6aff215Jgj
  13:        0x10e3746fc - trans::expr::trans_unadjusted::h66feeb4ce59b408dz4h
  14:        0x10e323f79 - trans::expr::trans_into::h4a29f680db4b3526znh
  15:        0x10e3a9220 - trans::expr::trans_adt::h73a11f7497464a42O6i
  16:        0x10e3abd52 - trans::expr::trans_struct::closure.42052
  17:        0x10e3953cb - trans::expr::trans_struct::h4294120fb3439252K2i
  18:        0x10e3766be - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  19:        0x10e323f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  20:        0x10e324e29 - trans::controlflow::trans_block::h26a308528bb95051b5d
  21:        0x10e403da9 - trans::base::trans_closure::h1e78b4450eb13a03Kkt
  22:        0x10e30c645 - trans::base::trans_fn::h31c9353b85ff9dd9Dvt
  23:        0x10e30e1c3 - trans::monomorphize::monomorphic_fn::h8c4abbed98c102adusd
  24:        0x10e35658b - trans::callee::trans_fn_ref_with_substs::heb22ab8904f67bf64kg
  25:        0x10e354b0e - trans::callee::trans_fn_ref::hb2be9d8aec49d9c4E9f
  26:        0x10e3521d0 - trans::callee::trans::ha12ccf10898e9b03VYf
  27:        0x10e36924d - trans::callee::trans_call_inner::h11221320451677754653
  28:        0x10e376bec - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  29:        0x10e323f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  30:        0x10e3a9220 - trans::expr::trans_adt::h73a11f7497464a42O6i
  31:        0x10e3abd52 - trans::expr::trans_struct::closure.42052
  32:        0x10e3953cb - trans::expr::trans_struct::h4294120fb3439252K2i
  33:        0x10e3766be - trans::expr::trans_rvalue_dps_unadjusted::hca2c07ae951484c14zi
  34:        0x10e323f59 - trans::expr::trans_into::h4a29f680db4b3526znh
  35:        0x10e43dd26 - trans::_match::mk_binding_alloca::h3448676421097350985
  36:        0x10e323280 - trans::base::init_local::h08a9fcff749ad013czs
  37:        0x10e324b02 - trans::controlflow::trans_block::h26a308528bb95051b5d
  38:        0x10e403da9 - trans::base::trans_closure::h1e78b4450eb13a03Kkt
  39:        0x10e30c645 - trans::base::trans_fn::h31c9353b85ff9dd9Dvt
  40:        0x10e308aa6 - trans::base::trans_item::h8ce277cc13b040a3vTt
  41:        0x10e3088a7 - trans::base::trans_item::h8ce277cc13b040a3vTt
  42:        0x10e40cecb - trans::base::trans_crate::hb69c466e59630a14GPu
  43:        0x10dd3fec7 - driver::phase_4_translate_to_llvm::he4e045cdc3897b4crNa
  44:        0x10dd1b7f2 - driver::compile_input::h25d96a14ec26932cIba
  45:        0x10dded72e - run_compiler::h15c3ea085a111a6fH5b
  46:        0x10ddeaac7 - thunk::F.Invoke<A, R>::invoke::h11905936354613679413
  47:        0x10dde960f - rt::unwind::try::try_fn::h4025213131938170097
  48:        0x111943628 - rust_try_inner
  49:        0x111943615 - rust_try
  50:        0x10dde9e48 - thunk::F.Invoke<A, R>::invoke::h13725635537516470714
  51:        0x1118af0a2 - sys::thread::thread_start::h1120d6d2e105321012E
  52:     0x7fff9557e267 - _pthread_body
  53:     0x7fff9557e1e4 - _pthread_start

Could not compile `glutin`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name glutin --crate-type lib -g --cfg feature="default" --cfg feature="window" -C metadata=6425255afb8a758e -C extra-filename=-6425255afb8a758e --out-dir /path/to/glutin/target --emit=dep-info,link -L dependency=/path/to/glutin/target -L dependency=/path/to/glutin/target/deps --extern core_foundation=/path/to/glutin/target/deps/libcore_foundation-df9d60bb8553a7f7.rlib --extern gl_common=/path/to/glutin/target/deps/libgl_common-ec39142a57c733b7.rlib --extern cocoa=/path/to/glutin/target/deps/libcocoa-0ab2cb870a6d387c.rlib --extern libc=/path/to/glutin/target/deps/liblibc-8d21de95f4de7169.rlib --extern core_graphics=/path/to/glutin/target/deps/libcore_graphics-2ddc84c21f1f2a32.rlib` (exit
```
```sh
$ rustc --version --verbose
rustc 1.0.0-nightly (3b3bb0e68 2015-03-04) (built 2015-03-04)
binary: rustc
commit-hash: 3b3bb0e682c2d252e9f62dd9df5cff9552af91ad
commit-date: 2015-03-04
build-date: 2015-03-04
host: x86_64-apple-darwin
release: 1.0.0-nightly

**Comment by jdm** [comment] 2015-03-05 21:35
Duplicate of #23075.

**Closed by jdm** 2015-03-05 21:35 UTC
Labels: A-debuginfo, I-ICE
