### ISSUE TITLE
ICE with clippy and futures

### ISSUE THREAD

**Issue by Razican** [rust-lang/rust#50683] opened 2018-05-12 11:29 UTC
Not sure if this is a rustc bug or a clippy bug, but running `cargo clippy` on one library, the compiler panicked.

I tried the code in the `develop` branch of this repo: https://github.com/Razican/bittrex-rs

I expected to see the clippy linting results, but instead, the compiler panicked.

## Meta

`rustc --version --verbose`:

```
rustc 1.27.0-nightly (e5f80f2a4 2018-05-09)
binary: rustc
commit-hash: e5f80f2a4f016bf724a1cfb580619d71c8fd39ec
commit-date: 2018-05-09
host: x86_64-unknown-linux-gnu
release: 1.27.0-nightly
LLVM version: 6.0
```

Backtrace:

```
   Compiling nodrop v0.1.12
   Compiling libc v0.2.40
   Compiling cfg-if v0.1.3
   Compiling byteorder v1.2.2
   Compiling memoffset v0.2.1
   Compiling version_check v0.1.3
   Compiling lazy_static v1.0.0
   Compiling scopeguard v0.3.3
   Compiling slab v0.4.0
   Compiling futures v0.1.21
   Compiling lazycell v0.6.0
   Compiling pkg-config v0.3.11
   Compiling cc v1.0.15
   Compiling siphasher v0.2.2
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.9.24
   Compiling scoped-tls v0.1.2
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /$HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.197/src/utils/higher.rs:76:32
   Compiling typenum v1.10.0
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:467
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   7: rust_begin_unwind
             at libstd/panicking.rs:328
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic_bounds_check
             at libcore/panicking.rs:58
  10: clippy_lints::utils::higher::range
  11: <clippy_lints::ranges::Pass as rustc::lint::LateLintPass<'a, 'tcx>>::check_expr
  12: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  13: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
  14: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  15: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
  16: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  17: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
  18: rustc::hir::intravisit::walk_impl_item
  19: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_impl_item
  20: rustc::hir::intravisit::walk_impl_item_ref
  21: rustc::hir::intravisit::walk_item
  22: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  23: rustc::hir::intravisit::walk_mod
  24: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  25: rustc::hir::intravisit::walk_item
  26: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  27: rustc::hir::intravisit::walk_mod
  28: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  29: rustc::hir::intravisit::walk_item
  30: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  31: rustc::hir::intravisit::walk_mod
  32: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
  33: rustc::lint::context::check_crate
  34: rustc::ty::context::tls::enter_context
  35: <std::thread::local::LocalKey<T>>::with
  36: rustc::ty::context::TyCtxt::create_and_enter
  37: rustc_driver::driver::compile_input
  38: rustc_driver::run_compiler_impl
  39: <scoped_tls::ScopedKey<T>>::set
  40: syntax::with_globals
  41: rustc_driver::run_compiler
  42: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  43: std::panicking::try::do_call
  44: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  45: rustc_driver::run
  46: clippy_driver::main
  47: std::rt::lang_start::{{closure}}
  48: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  49: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  50: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  51: main
  52: __libc_start_main
  53: _start
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (e5f80f2a4 2018-05-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `futures`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by kennytm** [comment] 2018-05-12 11:34
This is a duplicate of rust-lang-nursery/rust-clippy#2727, which will be fixed in the next clippy release.

**Closed by kennytm** 2018-05-12 11:34 UTC
