### ISSUE TITLE
same functions are not merged in library

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#91490] opened 2021-12-03 12:01 UTC
I tried this code:

```rust
pub fn a(c: char) -> bool {
    c == 's' || c == 'm' || c == 'h' || c == 'd' || c == 'w'
}

pub fn b(c: char) -> bool {
    matches!(c, 's' | 'm' | 'h' | 'd' | 'w')
}
```

When compiled with the latest stable version and look at the objdump, I see a combined version of a and b, because they are optimized to the same instructions and then merged in the library.
On nightly (already bisected) two copies are stored and it takes the double amount of space (3.9kIB vs 4.1kIB).

Here's a godbolt link: https://rust.godbolt.org/z/zWovojdEE

### Version it worked on
It most recently worked on: 1.57.0
Doesn't work since: 63cc2bb3d07d6c726dfcdc5f95cbe5ed4760641a cc #88243 @nikic 

@rustbot modify labels: +regression-from-stable-to-nightly +I-heavy

**Comment by camelid** [comment] 2021-12-03 19:08
> It most recently worked on: 1.57.0
> Doesn't work since: 63cc2bb cc #88243 @nikic

I'm confused: #88243 landed _in_ 1.57.0.

**Comment by camelid** [comment] 2021-12-03 19:09
Marking as regression-untriaged for now until we figure out which version this actually affects. That PR is in the latest stable (1.57.0).

**Comment by nikic** [comment] 2021-12-03 19:43
@camelid The change was reverted for the release.

The issue sounds like MergeFuncs doesn't run -- looking at https://github.com/llvm/llvm-project/blob/f178a05f220403f2a9d73c7640bfcc7dc2d7be72/llvm/lib/Passes/PassBuilderPipelines.cpp#L1194 I seem to have misscheduled the pass due to some unfortunate code structure: The passes are added in the middle of OptimizePM construction, but the OptimizePM is only actually scheduled afterwards, which means that MergeFuncs will run close to the start of the module pipeline, not the end. The same seems to have happened to IR outlining and hot-cold splitting.

**Comment by nikic** [comment] 2021-12-04 14:10
Test: https://github.com/llvm/llvm-project/commit/5b94037a304eb88809f86d8b9235426976061009
Fix: https://reviews.llvm.org/D115098

**Comment by apiraino** [comment] 2021-12-09 12:48
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2391490.20same.20functions.20are.20not.20merged.20in.20library) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by MSxDOS** [comment] 2022-01-02 04:32
This is fixed on nightly, apparently by https://github.com/rust-lang/rust/pull/91657

**Comment by camelid** [comment] 2022-01-02 04:56
Ok, closing then. That PR also added a test for this issue.

**Closed by camelid** 2022-01-02 04:56 UTC
Labels: P-medium, regression-from-stable-to-nightly, C-bug, I-heavy
