### ISSUE TITLE
sudo error when installing

### ISSUE THREAD

**Issue by bkazemi** [rust-lang/rust#32533] opened 2016-03-27 17:56 UTC
In the installation process of rust, the `install.mk` makefile attempts to invoke sudo as the root user; However, I have a rule that disallows sudo to be run under root, causing the installation to fail. A better option might be `su` as it is on nearly every *nix system while `sudo` isn't.

Rust version 1.7.0
File in question: rustc-1.7.0/mk/install.mk

**Comment by nodakai** [comment] 2016-03-27 20:32
You may want to try Rustup

- https://www.rustup.rs/

which can install Rust toolchains under `$HOME` and keep them updated

**Comment by bkazemi** [comment] 2016-03-28 18:58
Well, in my case Rust was being installed as a dependency, so I'd prefer to stick with my package manager's version for patches and whatnot. If the Rust team wants to keep `sudo` I can close this and take it up with my OS.

**Comment by durka** [comment] 2016-03-28 20:51
I don't think `su` is a better option than `sudo` because for the former you need the root password, which users are much less likely to know, and is even nonexistent on some systems (OSX).

**Comment by bkazemi** [comment] 2016-03-28 21:21
Correct me if I'm wrong, but isn't `sudo` used in `install.mk` to run the prepare_install target _from_ (effective) root? Because in that case you are already elevated and do not need to enter a password.

**Comment by durka** [comment] 2016-03-28 21:26
Oh I see, it uses `sudo -u` to drop privileges. And only if `$SUDO_USER` is set, so platforms that don't have sudo probably aren't a concern :) I still wonder why this would be prohibited by your distribution.

**Comment by bkazemi** [comment] 2016-03-28 22:10
It is actually a compile time knob to prevent accidental usage of `sudo` as root (since `sudo` is usually used to _become_ root) that may cause strange problems. `git blame` shows me that commit 23c2661 introduces this logic, and that switching to `su` would be still be a good solution to work around the issue the original commit was trying to solve without running into the issue I'm having.

**Comment by nodakai** [comment] 2016-03-29 05:59
@bkazemi I see two possible issues here

1. (I'm not knowledgeable about this) `su(1)` isn't readily usable on OS X by default
2. Your distro (I don't know which is it) seems to be enforcing a broken policy. `sudoers(5)` should be able to specifically forbid becoming `root` from `root` only.

**Comment by bkazemi** [comment] 2016-03-29 19:07
@nodakai 

1. I don't use OS X either so I can't say definitely, but I'd think that as *root* `su` can be used without user interaction on nearly _any_ Unix (it's been around in some form since V1 AT&T UNIX).
2. Forgive me for not clarifying earlier, but disabling the use of `sudo` as root was an _optional_ compile time knob that I set. This compile time option is part of vanilla `sudo` as `NO_ROOT_SUDO`. As far as I can tell, this can be reversed at runtime. My original problem is Rust doesn't check if this rule is set and thus, `sudo` fails as root when trying to substitute the user identity. A possible solution to this might be to check the return value of `sudo` in a sub-shell, and if it returns non-zero, then fallback to `su`.

**Comment by Mark-Simulacrum** [comment] 2017-05-12 00:48
This feels like a rustup issue, then? Can someone comment on whether this should be refiled onto rustup's repo?

**Comment by durka** [comment] 2017-05-12 15:26
I was the only one who mentioned rustup. The issue is about the makefiles, but those are gone. It doesn't look like bootstrap invokes sudo at all.

**Comment by Mark-Simulacrum** [comment] 2017-05-12 15:56
Grepping for sudo in rust source produces results that lead me to believe this is no longer an issue, at least for rust-lang/rust. Closing.

**Closed by Mark-Simulacrum** 2017-05-12 15:56 UTC
Labels: A-infrastructure, P-low
