### ISSUE TITLE
Rustdoc should show [src] link for trait impls

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#15744] opened 2014-07-17 14:23 UTC
Currently it shows a `[src]` link for traits and for types and lists the impls with either, but you don't generally know just where the impl is defined, so getting from the documentation to the definition of some trait methods for a concrete type is tricky.

**Comment by alexcrichton** [comment] 2015-04-06 23:04
Closing as a dupe of #12932

**Closed by alexcrichton** 2015-04-06 23:04 UTC
Labels: A-rustdoc
