### ISSUE TITLE
Constraints on associated types declared in subtraits do not propagate.

### ISSUE THREAD

**Issue by brendanzab** [rust-lang/rust#32722] opened 2016-04-04 09:37 UTC
Pretty bad title - sorry. Somebody who knows the type checker might be able to do better.

Here is a minimal example:

``` rust
pub trait Real {}

pub trait VectorSpace {
    type Scalar;
}

pub trait InnerSpace: VectorSpace where
    <Self as VectorSpace>::Scalar: Real,
{
    fn dot(self, other: Self) -> Self::Scalar;
}

pub fn dot<V: InnerSpace>(a: V, b: V) -> V::Scalar {
    V::dot(a, b)
}
```

```
<anon>:13:1: 15:2 error: the trait `Real` is not implemented for the type `<V as VectorSpace>::Scalar` [E0277]
<anon>:13 pub fn dot<V: InnerSpace>(a: V, b: V) -> V::Scalar {
<anon>:14     V::dot(a, b)
<anon>:15 }
<anon>:13:1: 15:2 help: see the detailed explanation for E0277
<anon>:13:1: 15:2 note: required by `InnerSpace`
```

http://is.gd/vjIVwO

**Comment by apoelstra** [comment] 2016-07-23 23:23
Another example:
```
trait SomeBound {}

trait A {
    type Type;
}

trait B: A where Self::Type: SomeBound {
}

trait C: B {}

fn main() {}
```

**Comment by CasualX** [comment] 2016-10-01 16:06
I ran into this when creating a trait that requires `FromStr` and constrains `FromStr::Err: 'static + Error`. Anything that uses this trait must repeat the associated type constraint or I get this error.

**Comment by brendanzab** [comment] 2016-10-02 03:11
cc. @sebcrozet

**Comment by Popog** [comment] 2016-10-26 18:42
Is this the same issue as #20671?

**Comment by estebank** [comment] 2019-11-05 01:15
Current output suggests code that would be accepted today:

```
error[E0277]: the trait bound `<V as VectorSpace>::Scalar: Real` is not satisfied
  --> src/lib.rs:13:1
   |
7  | / pub trait InnerSpace: VectorSpace where
8  | |     <Self as VectorSpace>::Scalar: Real,
9  | | {
10 | |     fn dot(self, other: Self) -> Self::Scalar;
11 | | }
   | |_- required by `InnerSpace`
12 | 
13 |   pub fn dot<V: InnerSpace>(a: V, b: V) -> V::Scalar {
   |   ^                                                 - help: consider further restricting the associated type: `where <V as VectorSpace>::Scalar: Real`
   |  _|
   | |
14 | |     V::dot(a, b)
15 | | }
   | |_^ the trait `Real` is not implemented for `<V as VectorSpace>::Scalar`
```

```
error[E0277]: the trait bound `<Self as A>::Type: SomeBound` is not satisfied
  --> src/main.rs:10:1
   |
7  | trait B: A where Self::Type: SomeBound {
   | -------------------------------------- required by `B`
...
10 | trait C: B {}
   | ^^^^^^^^^^-^^
   | |         |
   | |         help: consider further restricting the associated type: `where <Self as A>::Type: SomeBound`
   | the trait `SomeBound` is not implemented for `<Self as A>::Type`
```

```
error[E0277]: the trait bound `<<Self as SessionType>::Dual as SessionType>::Dual: Recv` is not satisfied
  --> src/main.rs:5:1
   |
5  | / trait Recv: SessionType
6  | |     where Self::Dual: Send {
   | |                           - help: consider further restricting the associated type: `, <<Self as SessionType>::Dual as SessionType>::Dual: Recv`
7  | | }
   | |_^ the trait `Recv` is not implemented for `<<Self as SessionType>::Dual as SessionType>::Dual`
8  | 
9  | / trait Send: SessionType
10 | |     where Self::Dual: Recv {
11 | | }
   | |_- required by `Send`

error[E0277]: the trait bound `<<Self as SessionType>::Dual as SessionType>::Dual: Send` is not satisfied
  --> src/main.rs:9:1
   |
5  | / trait Recv: SessionType
6  | |     where Self::Dual: Send {
7  | | }
   | |_- required by `Recv`
8  | 
9  | / trait Send: SessionType
10 | |     where Self::Dual: Recv {
   | |                           - help: consider further restricting the associated type: `, <<Self as SessionType>::Dual as SessionType>::Dual: Send`
11 | | }
   | |_^ the trait `Send` is not implemented for `<<Self as SessionType>::Dual as SessionType>::Dual`
```

**Comment by CasualX** [comment] 2019-11-05 09:43
@estebank Rust error messages have come a long way :)

In this particular case however it would be nice if Rust knew how to propagate the where clause on traits. Another similar demonstration looks like this:

    use std::str::FromStr;
    use std::error::Error;
    
    trait Parse: FromStr where Self::Err: 'static + Error {}
    
    fn parse<T: Parse>(s: &str) -> Result<T, T::Err> {
        s.parse()
    }

Results in the compiler complaining that just because T must implement `Parse` doesn't mean that `T::Err` implements `std::error::Error`. Which is dumb as there are no types which implement `Parse` which have their `Err` associated type not implement std error trait.

So even though the Rust compiler now makes a suggestion this is still painful as you must repeat the bounds everywhere (perhaps the entire point to make this trait was to imply a whole bunch of traits in a single name).

**Comment by estebank** [comment] 2019-11-05 15:21
That feature work is likely to happen at some point and it is widely requested. I haven't closed this ticket because the feature work is not done, but at least we have a mitigation in place.

**Comment by jonas-schievink** [comment] 2020-04-22 21:16
Duplicate of https://github.com/rust-lang/rust/issues/20671. Also see https://github.com/rust-lang/rust/issues/44491.

**Closed by jonas-schievink** 2020-04-22 21:16 UTC
Labels: A-associated-items, A-traits, A-typesystem, C-bug, F-associated_type_bounds, T-lang
