### ISSUE TITLE
swallowed output line visible only upon second compile invocation

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#48940] opened 2018-03-11 21:43 UTC
While encountering [this](https://github.com/rust-lang/rust/issues/48910) issue, I've noticed a discrepancy in the ouput while compiling Rust:
The compile error was referencing `rustc_driver` but the previous output contained no line(within a decent range from the error) saying `Compiling rustc_driver v0.0.0`, as if that line was somehow lost due to some kind of output buffer not being flushed, or something.

**I expected to see this happen:**
```
Compiling rustc_passes v0.0.0 (file:///home/xftroxgpx/build/2nonpkgs/rust.stuff/rust/rust/src/librustc_passes)
Compiling rustc_driver v0.0.0 (file:///home/xftroxgpx/build/2nonpkgs/rust.stuff/rust/rust/src/librustc_driver)
fragment covers entire variable
```

**Instead, this happened:**
```
Compiling rustc_passes v0.0.0 (file:///home/xftroxgpx/build/2nonpkgs/rust.stuff/rust/rust/src/librustc_passes)
fragment covers entire variable
```

Now, there is one `Compiling rustc_driver` line [here](https://gist.github.com/xftroxgpx/5eef3141eab2e4ccdfe0fa3255ff921d/212fababd444b3caa8cfde7971a6e79867c61383#file-console-rs-L4954) however that line is so far from the compile error that it doesn't seem to make any sense that that line is then the [first](https://gist.github.com/xftroxgpx/5eef3141eab2e4ccdfe0fa3255ff921d/d05bc152c4c4c02c4e241a60a278a940bb0549db#file-console-rs-L5069-L5071) and only line on the subsequent compilation attempt.

<details><summary>In other words:</summary>

Why is the line with `Compiling rustc_driver` missing in the first compilation attempt here:
https://gist.github.com/xftroxgpx/5eef3141eab2e4ccdfe0fa3255ff921d/d05bc152c4c4c02c4e241a60a278a940bb0549db#file-console-rs-L5015-L5018

but it's there in the second compilation attempt:
https://gist.github.com/xftroxgpx/5eef3141eab2e4ccdfe0fa3255ff921d/d05bc152c4c4c02c4e241a60a278a940bb0549db#file-console-rs-L5069-L5072

I even tried the above for a second time:
* missing on first time compilation:
https://gist.github.com/xftroxgpx/5eef3141eab2e4ccdfe0fa3255ff921d/212fababd444b3caa8cfde7971a6e79867c61383#file-console-rs-L4996-L4999

* visible on second time compilation:
https://gist.github.com/xftroxgpx/5eef3141eab2e4ccdfe0fa3255ff921d/212fababd444b3caa8cfde7971a6e79867c61383#file-console-rs-L5049-L5052

</details>

<details><summary>rustc used to compile (probably)</summary>

```
$ ~/.cargo/bin/rustc -vV
rustc 1.26.0-nightly (2789b067d 2018-03-06)
binary: rustc
commit-hash: 2789b067da2ac921b86199bde21dd231ace1da39
commit-date: 2018-03-06
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```
</details>

**Comment by jyn514** [comment] 2023-02-03 07:45
Duplicate of https://github.com/rust-lang/cargo/issues/8889

**Closed by jyn514** 2023-02-03 07:45 UTC
Labels: C-enhancement, T-bootstrap
