### ISSUE TITLE
Promotion creates invalid constants that are never used in invalid ways

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#67534] opened 2019-12-22 19:31 UTC
Namely, we can have promoteds with interior mutable types but in an immutable allocation.
#67000 makes this explicit by introducing the `ignore_interior_mut_in_const_validation` field on the const interner.

We should instead rewrite such promoteds to just contain the parts of the promoted that is accessed. So

```rust
let x: &'static i32 = &[(Cell::new(42), 1), Cell::new(42), 2)][runtime_index].1;
```

currently produces

```rust
const PROMOTED: &[(Cell<i32>, i32); 2] = &[(Cell::new(42), 1), Cell::new(42), 2)];
let x: &'static i32 = &PROMOTED[runtime_index].1;
```

And we should be producing

```rust
const PROMOTED: &[i32; 2] = &[1, 2];
let x: &'static i32 = &PROMOTED[runtime_index];
```

This is definitely a nontrivial transformation, especially since it needs to be done on the generic promoted and not the computed final value (generic e.g. if we had `T::CELL_VALUE` instead of `Cell::new(42)`).
The reason it needs to be done on the MIR is that we also need to change the projection for obtaining the value of `x`, which we have no control over if we did it on the final constant.

**Comment by RalfJung** [comment] 2019-12-22 19:55
Also see [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/promoteds.20are.20not.20places).

I am still not 100% of the soundness of this -- the UB in code like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e4d683463eb85f63a74cef59a7aaf8a3) relies on subtle and unstable details of current Stacked Borrows. In other words, assuming that what we currently do is sound makes some very strong statement about Rust semantics that @rust-lang/lang never signed off.

How hard would it be to make rustc reject such (IMO) broken promoteds, and use crater to determine how widely this pattern is used? The examples you showed so far are all extremely niche.

**Comment by oli-obk** [comment] 2019-12-22 20:02
> How hard would it be to make rustc reject such (IMO) broken promoteds, and use crater to determine how widely this pattern is used? The examples you showed so far are all extremely niche.

I *think* it would be fine, but I feel like the motivation to do so is weak. This is completely sane from a user perspective, and feels like the zero cost magic that Rust gives us.

**Comment by oli-obk** [comment] 2019-12-22 20:04
[this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8b03a52507a050aecf75acc4db0b2952) is the more realistic example that I would expect to see out there.

**Comment by RalfJung** [comment] 2019-12-22 20:06
> This is completely sane from a user perspective,

I can't see anything sane about this from any perspective.^^ "This seems fine" is how we got ourselves in lots of trouble with promotion...

> I feel like the motivation to do so is weak

The burden of motivation is on whoever writes an RFC to add support for this to rustc, IMO. That this didn't happen is an accident.

**Comment by RalfJung** [comment] 2019-12-22 20:15
I also don't think "this is unsound in all but our most complex Rust semantics" is a pretty strong motivation for *not* doing this. ;)

**Comment by oli-obk** [comment] 2019-12-22 20:36
> The burden of motivation is on whoever writes an RFC to add support for this to rustc, IMO. That this didn't happen is an accident.

This didn't happen by accident, this is entirely by design afaict (cc @eddyb). Though I'm not sure how much of that was RFCed. Implicit promotion is definitely not our proudest moment in RFCing and stabilizing.

**Comment by RalfJung** [comment] 2019-12-23 09:18
> This didn't happen by accident, this is entirely by design afaict (cc @eddyb).

In that design, what was the soundness argument? Because as far as I can see, one can trivially break soundness of this scheme by doing some pointer arithmetic outside the bounds of the reference one gets. Yes, Stacked Borrows currently disallows this, but (a) Stacked Borrows didn't exist yet when this was designed, so that cannot have been the argument, and (b) this is one of the Stacked Borrows properties that people semi-regularly run into and complain about (e.g. [here](https://github.com/Gilnaa/memoffset/pull/21) and [here](https://internals.rust-lang.org/t/rc-and-internal-mutability/11463/11)).

**Comment by eddyb** [comment] 2020-01-16 19:21
What is being proposed, in terms of potentially breaking changes?
If you replace the `i` with a constant, then the question becomes about the difference between:
* `&CONST.1`
* `&{CONST.1}`

It's unreasonable to assume that you can access any other fields through the latter, so do we want to force people through that?

I'm bringing this up because it's easy for us to treat them like equivalent, or a lot easier than the runtime indexing case, at least.
But it *is* a can of worms that we've opened up, I agree with @RalfJung on that.

<hr/>

I think the reason for the *original* behavior (before the runtime indexing special-case, and even before MIR) was that accessing a field *always* cleared "qualifications" that didn't apply to the field type, even if in the borrow itself - that is, `&A.1` and `&(A.1 + B.1)` had similar treatment of all the `.1` field accesses, despite the `+` *copying out* the values from the fields (which the borrow doesn't do).

AFAICT, this was kept during the move the MIR, and only slightly tweaked later.
We *do* require `A` in `&A.1` has no destructor, so we could do the same for interior mutability.
All it would take (for promotion, not sure about const-checking) is commenting this out: https://github.com/rust-lang/rust/blob/117ceeba400e69aa7b8ba5155acd1c8c0cdf7f7f/src/librustc_mir/transform/promote_consts.rs#L323-L341

**Comment by RalfJung** [comment] 2020-01-18 12:00
> It's unreasonable to assume that you can access any other fields through the latter

Not sure which part of our semantics you are basing that on, other than Stacked Borrows. Not being able to access stuff "outside" of where the pointer points to is a frequent issue [with raw pointers](https://github.com/rust-lang/unsafe-code-guidelines/issues/134).

**Comment by eddyb** [comment] 2020-01-19 15:13
@RalfJung "the latter" refers to `&{CONST.1}`, which borrows a temporary copy of the `.1` field - even for something like `&{x.1}`, there's none of the other fields of `x` left around, so raw pointer hacks wouldn't ever work (on top of being UB because they access outside the allocation of the temporary copy).

**Comment by RalfJung** [comment] 2020-01-19 15:21
Oh I see... because that evaluated `{CONST.1}` to a value, and then creates a temporary with that and a pointer to it? Makes sense.

**Comment by Dylan-DPC** [comment] 2020-06-12 23:33
Marking it as p-high based on the [wg-prioritisation discussion](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2367534.20Promotion.20creates.20invalid.20constants.20that)

**Comment by oli-obk** [comment] 2020-06-13 07:25
I was doing such a good job of ignoring this issue, and now it's P-high :laughing: 

We can't really write a forward compat lint for this, as the user may not be using the promoted in a `'static` way, so if we warn them we'd be warning on perfectly fine code. So the only path forward is to remove the snippet linked above and run crater.

**Comment by RalfJung** [comment] 2020-08-12 12:57
Here's another horrible thing we could do: we could change the type of the promoted to replace all `UnsafeCell<T>` by `T`...

Or does this also work for custom struct constructors, not just with tuples like in the example?

**Comment by oli-obk** [comment] 2020-08-12 13:35
Yea this will also work for your own structs. We can wrap the entire thing in a `MaybeUninit` :D

**Comment by RalfJung** [comment] 2020-08-12 13:47
That does nothing with `UnsafeCell`...

**Comment by RalfJung** [comment] 2020-10-25 16:59
> `let x: &'static i32 = &[(Cell::new(42), 1), Cell::new(42), 2)][runtime_index].1;`

FWIW, this code is currently not even accepted inside a function, I think? It only works inside another `const`/`static`, because there we still permit promotion of arbitrary `const fn`.

**Closed** 2020-12-09 11:31 UTC
Labels: A-const-eval, C-bug, I-unsound 💥, P-high, T-compiler
