### ISSUE TITLE
More suggestions for misspelled names

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#38166] opened 2016-12-04 21:56 UTC
Some ideas from: https://gcc.gnu.org/gcc-7/changes.html

    const MAX_ITEM: usize = 10;
    fn foo_bar() {}
    fn foo(c: esize) {} // Misspelled type name.
    enum Bar { First, Second }
    fn main() {
        let v = [0u32; MAXITEM]; // Misspelled constant name.
        foobar(); // Misspelled function name.
        let b: Bar = Bar::second; // Misspelled enum variant.
    }

In all four cases I'd like the Rust compiler to suggest the closest names (usize/isize, MAX_ITEM, foo_bar, Bar::Second).

**Comment by nagisa** [comment] 2016-12-05 07:10
Duplicate of https://github.com/rust-lang/rust/issues/30197

**Comment by leonardo-m** [comment] 2016-12-05 12:27
Thank you. The text of this issue is short enough, so I've copied it all, I think it can't hurt much.
I have used Bugzilla a lot in past. How do I close this issue? How can I find duplicated issues before submitting it? How can I add tags to my issues?

**Comment by nagisa** [comment] 2016-12-05 12:37
> How do I close this issue?

There should be a button near the one that says “Comment”.

> How can I find duplicated issues before submitting it? 

Using the [issue search](https://github.com/rust-lang/rust/issues) with smartly crafted queries. In case of ICE the message of ICE or function name in backtrace works well. In case of issues like yours you can simply rely on other people noticing a duplicate.

> How can I add tags to my issues?

You cannot. It is, unlike in (Mozilla’s) Bugzilla, something that only people in a list of some sort can do.

**Closed** 2016-12-05 13:16 UTC
