### ISSUE TITLE
Tracking issue for RFC 1682: field init shorthand

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#37340] opened 2016-10-22 05:21 UTC
[RFC](https://github.com/rust-lang/rfcs/pull/1682).

Before stabilizing:

- [x] Needs documentation (https://github.com/rust-lang/rust/issues/38830)

**Comment by Havvy** [comment] 2016-10-22 07:44
Once we have this syntax, we'll want to clean up the compiler where it's useful. Since this would be almost a rote cleanup, we'd either want a mentored issue or a tool to detect it.

**Comment by steveklabnik** [comment] 2016-10-22 07:51
>  a tool to do it.

I wonder if @killercup 's `rustfix` could do this

**Comment by eddyb** [comment] 2016-10-22 07:54
@steveklabnik `rustfmt` doing it by default has also been mentioned. cc @nrc

**Comment by nrc** [comment] 2016-10-24 23:59
Yeah, Rustfmt could def. do this.

**Comment by killercup** [comment] 2016-10-25 18:25
I haven't read that RFC; if you can write a lint that suggests the new
syntax (with a concrete and valid code suggestion), rustfix will be able to
fix this. (If this is only a syntactic change though it might indeed make
more sense to add this to rustfmt.)


Eduard-Mihai Burtescu <notifications@github.com> schrieb am Sa. 22. Okt.
2016 um 09:54:

**Comment by est31** [comment] 2016-10-25 18:47
I think that the compiler shouldn't lint for this, suggesting sugar features is more a thing for clippy.

**Comment by chriskrycho** [comment] 2016-12-23 01:36
What's the current status on this—in nightly, it looks like, via https://github.com/rust-lang/rust/issues/11994? Do we know when it's expected to land?

**Comment by matthew-piziak** [comment] 2016-12-23 23:30
@chriskrycho Confirmed—it works in nightly. I'm using the feature in my nightly project right now.

**Comment by Havvy** [comment] 2016-12-25 05:30
The new documentation required RFC means we need to figure out how to document it, I think?

* The [grammar](https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md#structure-expressions) needs updating
* as would adding a section to [the book](https://github.com/rust-lang/rust/blob/master/src/doc/book/structs.md) and the new book. 
* The [reference](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md) would need a paragraph explaining the sugar.
* Additionally, we may want to add examples to Rust By Example showing the syntax.

We also need changelog entries? I propose the following for the short entry. I don't have the energy right now to try a long entry.

> Added field init shorthand syntax when the field and variable names match.

**Comment by matthew-piziak** [comment] 2016-12-25 20:57
Rustfmt also needs support for this feature. [The tracking issue is here](https://github.com/rust-lang-nursery/rustfmt/issues/1215). I'm planning to tackle that eventually but I'm not going to lick the cookie just yet.

**Comment by nikomatsakis** [comment] 2017-01-04 20:46
I opened https://github.com/rust-lang/rust/issues/38830 to specifically track adding docs.

**Comment by brson** [comment] 2017-01-11 01:36
Can we nominate this for FCP now in expectation that it will be finished in time to branch 1.16 on Feb 2?

**Comment by nikomatsakis** [comment] 2017-01-11 17:13
@rfcbot fcp merge

I propose that we stabilize field init shorthand. It's handy and uncomplicated. One remaining work item is documentation, which is being tracked by #38830, but work has already begun.

**Comment by nrc** [comment] 2017-01-11 18:29
Reluctantly, and assuming documentation is finished before we stabilise.

**Comment by withoutboats** [comment] 2017-01-11 23:23
@rfcbot reviewed

@nrc [RFC 1636](https://github.com/rust-lang/rfcs/blob/master/text/1636-document_all_features.md) *requires* that we document every feature before we actually stabilize it.

**Comment by pnkfelix** [comment] 2017-01-12 13:05
@rfcbot concern documentation-unfinished

(Despite the point just made by @withoutboats, I see no reason to put my check mark on something whose required documentation is unfinished.)

**Comment by est31** [comment] 2017-01-12 13:42
@pnkfelix 

> I see no reason to put my check mark on something whose required documentation is unfinished.)

There has been some discussion about this question in the thread to stabilize [custom derive](https://github.com/rust-lang/rust/issues/35900#issuecomment-269187265).

quoting @steveklabnik :

> My imagining of this was always that the decision to stabilize and the actual stabilization are separate. That is, @rust-lang/lang can say "this can be made stable", but the commit to remove the gate also ensures the documentation exists.
>
> Given that we just had a release, my plan was to do something like this:
>
> 1. Wait for this to leave FCP
>  2. Land some docs. (I was planning on writing them in this case)
>  3. Make the stabilization PR.
>
> Possibly combining two and three.

In my opinion, it would make sense to separate the two decisions as it allows for a cleaner transition. E.g. you can't merge a docs PR if you don't know whether something will be stabilized (docs are intended for the users, no? They should, in the best case, always match what is actually stable), but if there is no FCP, how do you know whether it will actually be stabilized.

**Comment by aturon** [comment] 2017-01-12 16:31
@est31 I entirely agree. The review here is purely to go *into FCP*, which still leaves several weeks before stabilization could even occur; the check for documentation should happen separately, later. That will give us the highest throughput.

**Comment by pnkfelix** [comment] 2017-01-12 21:52
I can see the throughput argument.

But I am having difficulty making this argument jibe in my head with the fact that RFC's now have a section on "how this will be taught to new users" ... so I thought we were transitioning to a world where docs were required earlier on before we make final decisions on them.

Anyway, fine, I don't actually care enough to hold up the process.

**Comment by pnkfelix** [comment] 2017-01-12 21:52
@rfcbot resolved documentation-unfinished

**Comment by pnkfelix** [comment] 2017-01-12 21:52
@rfcbot reviewed

**Comment by aturon** [comment] 2017-01-13 18:41
Manually marking for FCP.

**Comment by lfairy** [comment] 2017-02-12 04:18
Now that #39459 has landed, I think there's nothing blocking stabilization at this point.

**Comment by est31** [comment] 2017-02-12 05:39
@lfairy I'm not sure, #38830 is still open, no?

**Comment by est31** [comment] 2017-02-12 09:22
Hmm... seems @lfairy is right: the [documentation RFC](https://github.com/rust-lang/rfcs/blob/master/text/1636-document_all_features.md#new-requirement-to-document-changes-before-stabilizing) doesn't require that the feature is documented in Rust by example. So all the points required for stabilisation are done (see the list in #38830), which means we can stabilize it!

**Comment by aturon** [comment] 2017-02-15 23:54
We're ready to go forward with stabilization!

**Comment by chriskrycho** [comment] 2017-02-16 00:41
Easy enough to [add an example anyway](https://github.com/rust-lang/rust-by-example/pull/844). I needed a little win today!

**Closed** 2017-02-16 05:52 UTC
Labels: A-lang, B-RFC-approved, B-unstable, final-comment-period, T-lang
