### ISSUE TITLE
Compiler bug with misspelt enum name

### ISSUE THREAD

**Issue by ns-sundar** [rust-lang/rust#35645] opened 2016-08-13 08:40 UTC
enum Token {
   Num(i32),
   AddSub(char),
   MulDiv(char),
   LeftParen(char),
   RightParen(char)
}

fn main() {
    println!("Hello World\n");

}

#[allow(dead_code)]
fn postfix_from_infix(infix: Vec<Token>) -> Vec<Token> {
   let postfix = Vec::<Token>::new();

   for token in infix {
      match token {
         Toekn::LeftParen(_) => break,
         _                   => {}
      }
   }

   postfix
}

```
C:\UserData\Tech\Rust\expr\src>cargo run -- "527 + 35*2"
   Compiling expr v0.1.0 (file:///C:/UserData/Tech/Rust/expr)
main.rs:20:10: 20:26 error: failed to resolve. Use of undeclared type or module
`Toekn` [E0433]
main.rs:20          Toekn::LeftParen(_) => break,
                    ^~~~~~~~~~~~~~~~
main.rs:20:10: 20:26 help: run `rustc --explain E0433` to see a detailed explana
tion
main.rs:20:10: 20:29 error: internal compiler error: ../src/librustc\middle\mem_
categorization.rs:1262: enum pattern didn't resolve to enum or struct None
main.rs:20          Toekn::LeftParen(_) => break,
                    ^~~~~~~~~~~~~~~~~~~
**note: the compiler unexpectedly panicked. this is a bug.**
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
aster/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax\errors/mod.rs:545
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `expr`.

To learn more, run the command again with --verbose.

###################
I misspelt the enum Token as Toekn. The compiler panics.
C:\UserData\Tech\Rust\expr\src>rustc --version
rustc 1.10.0 (cfcb716cf 2016-07-03)

**Comment by petrochenkov** [comment] 2016-08-13 09:40
Fixed on beta/nightly.

Working/minimized reproduction:
```
enum Token {
    LeftParen(char),
    RightParen(char),
}

#[allow(dead_code)]
fn postfix_from_infix(infix: Vec<Token>) {
    for token in infix {
        match token {
            Toekn::LeftParen(_) => {},
            _ => {}
        }
    }
}

fn main() {}
```

**Comment by nagisa** [comment] 2016-08-13 20:08
Duplicate of https://github.com/rust-lang/rust/issues/33293.

**Closed** 2016-08-13 20:21 UTC
