### ISSUE TITLE
ICE with 1/8/15 nightly

### ISSUE THREAD

**Issue by spacejam** [rust-lang/rust#20842] opened 2015-01-10 00:44 UTC
```
rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800)
binary: rustc
commit-hash: 44a287e6eb22ec3c2a687fc156813577464017f7
commit-date: 2015-01-08 17:03:40 -0800
host: x86_64-unknown-linux-gnu
release: 1.0.0-nightly
```
OS: Gentoo Linux (I can also try with OSX 10.10 if that would be useful for anyone), using the nightly pre-compiled binary rustc.
```
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123

stack backtrace:
   1:     0x7faf7b695850 - sys::backtrace::write::h5b05e7b061a35107Czt
   2:     0x7faf7b6b7a60 - failure::on_fail::h1e9b7e3de59488d1aPz
   3:     0x7faf7b6255e0 - rt::unwind::begin_unwind_inner::h23dcfb4c37870bd62tz
   4:     0x7faf76438460 - rt::unwind::begin_unwind::h8180555736548804672
   5:     0x7faf764383f0 - diagnostic::SpanHandler::span_bug::h3246a6ab77068eb1nQF
   6:     0x7faf797a9140 - session::Session::span_bug::hcecc3d60de53fc8aYQq
   7:     0x7faf7ae3de00 - middle::expr_use_visitor::ExprUseVisitor<'d, 't, 'tcx, TYPER>::walk_expr::h9715073354066643046
   8:     0x7faf7ae3d900 - middle::expr_use_visitor::ExprUseVisitor<'d, 't, 'tcx, TYPER>::walk_block::h137601184139970644
   9:     0x7faf7ae36f50 - check::upvar::AdjustBorrowKind<'a, 'tcx>::analyze_fn::h86c65d51df7da555vji
  10:     0x7faf7ae62360 - check::check_bare_fn::h12b646cb07f4b492H3j
  11:     0x7faf7ae59ad0 - check::check_item::h45ea87c7d5c5cf84umk
  12:     0x7faf7ae62010 - visit::walk_mod::h3476682974713590759
  13:     0x7faf7af27b30 - check_crate::unboxed_closure.30617
  14:     0x7faf7af22670 - check_crate::hdbcb36eaa379a57c23x
  15:     0x7faf7bbe49c0 - driver::phase_3_run_analysis_passes::h8c55e45fcfc1c7aegwa
  16:     0x7faf7bbcd350 - driver::compile_input::h04aea004c559b910xba
  17:     0x7faf7bc9cfe0 - monitor::unboxed_closure.22497
  18:     0x7faf7bc9ce40 - thunk::F.Invoke<A, R>::invoke::h11849311349984608396
  19:     0x7faf7bc9bbc0 - rt::unwind::try::try_fn::h13617610205470131813
  20:     0x7faf7b71d6c0 - rust_try_inner
  21:     0x7faf7b71d6b0 - rust_try
  22:     0x7faf7bc9beb0 - thunk::F.Invoke<A, R>::invoke::h14452289732390470265
  23:     0x7faf7b6a5910 - sys::thread::thread_start::h93b0d38960a9fcacqrw
  24:     0x7faf75c56120 - start_thread
  25:     0x7faf7b2db589 - clone
  26:                0x0 - <unknown>

Could not compile `rocksdb`.

Caused by:
  Process didn't exit successfully: `rustc /home/tan/code/rust-rocksdb/src/lib.rs --crate-name rocksdb --crate-type lib -g -C metadata=1b4bf2eed014cc48 -C extra-filename=-1b4bf2eed014cc48 --out-dir /home/tan/code/rust-rocksdb/target --emit=dep-info,link -L dependency=/home/tan/code/rust-rocksdb/target -L dependency=/home/tan/code/rust-rocksdb/target/deps` (status=101)
8762 pts/2 code/rust-rocksdb
```
offending code: https://github.com/spacejam/rust-rocksdb/tree/tan_ICE

**Comment by steveklabnik** [comment] 2015-04-21 14:48
This code sample no longer compiles due to changes in Rust. Do you have a smaller reproduction maybe, @spacejam ?

**Comment by arielb1** [comment] 2015-07-08 20:53
Seems like a dupe of #20862.

**Comment by arielb1** [comment] 2015-07-08 20:54
also, code missing. closing.

**Closed by arielb1** 2015-07-08 20:54 UTC
Labels: I-ICE
