### ISSUE TITLE
Replacing match branch with nothing via a macro causes unhelpful diagnostic

### ISSUE THREAD

**Issue by ctz** [rust-lang/rust#36716] opened 2016-09-25 10:34 UTC
Sample code:

```
macro_rules! warn (
    ($($tt:tt)*) => ()
);

fn main() {
    match 5 {
        5 => warn!("foo"),
        _ => (),
    };
}
```

Experienced behaviour: this causes this diagnostic and no other output:

```
error: expected expression, found `<eof>`
```

Expected behaviour: diagnostic with line/column information pointing to warn! expansion site. For example, if I manually expand the macro the diagnostic is:

```
error: expected expression, found `,`
 --> <anon>:7:14
  |>
7 |>         5 => ,
  |>              ^

error: aborting due to 2 previous errors
```

Version:
```
$ rustc --version --verbose
rustc 1.11.0 (9b21dcd6a 2016-08-15)
binary: rustc
commit-hash: 9b21dcd6a89f38e8ceccb2ede8c9027cb409f6e3
commit-date: 2016-08-15
host: x86_64-unknown-linux-gnu
release: 1.11.0
```

**Comment by TimNN** [comment] 2016-09-25 11:09
Duplicate of #30128.

**Comment by bluss** [comment] 2016-09-25 12:51
Thank you, closed as dup.

**Closed by bluss** 2016-09-25 12:51 UTC
