### ISSUE TITLE
Make #![deny(warnings)] intercept all warnings

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#21755] opened 2015-01-29 17:54 UTC
Currently it only turns warnings from lints into errors. It should work like -Werror and replace all warnings by errors.

**Comment by eddyb** [comment] 2015-01-29 17:56
We could remove any way to produce warnings other than through lints. And maybe dump recorded lints when we hit a fatal error (no, wait, can we remove *those*?) or we stop due to accumulated errors.

**Comment by nagisa** [comment] 2015-01-29 18:01
Duplicate of #21204

**Closed** 2015-01-29 18:02 UTC
