### ISSUE TITLE
`super` doesn't work with `use … as …` syntax

### ISSUE THREAD

**Issue by Twey** [rust-lang/rust#66743] opened 2019-11-25 14:38 UTC
## Expected behaviour
I would expect `super` and `self` to behave the same as other module identifiers in all places.

## Actual behaviour
It seems that `super` is not interpreted before the `use … as …` module-renaming syntax, resulting in an error about `super` being undefined:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b06a2575fe28666b4298baa79816448b

**Comment by petrochenkov** [comment] 2019-11-25 19:04
Duplicate of one of these - https://github.com/rust-lang/rust/issues/37156, https://github.com/rust-lang/rust/issues/35612, https://github.com/rust-lang/rust/issues/29036.
Yeah, this should work, but the fix is low priority.

**Closed** 2019-11-25 19:09 UTC
