### ISSUE TITLE
sepcomp-lib-lto.rs test failed on Rust 1.4.0 built with --enable-debug

### ISSUE THREAD

**Issue by nick-korsakov** [rust-lang/rust#29739] opened 2015-11-10 04:35 UTC
Rust 1.4.0. built with --enable-debug causes next error on tests (make check):

    failures:
    
    ---- [run-pass] run-pass/sepcomp-lib-lto.rs stdout ----
    	
    error: compilation failed!
    status: signal: 6
    command: x86_64-unknown-linux-gnu/stage2/bin/rustc /home/nick/rust/1.0.4/source/src/test/run-pass/sepcomp-lib-lto.rs -L x86_64-unknown-linux-gnu/test/run-pass/ --target=x86_64-unknown-linux-gnu -L x86_64-unknown-linux-gnu/test/run-pass/sepcomp-lib-lto.stage2-x86_64-unknown-linux-gnu.run-pass.libaux -o x86_64-unknown-linux-gnu/test/run-pass/sepcomp-lib-lto.stage2-x86_64-unknown-linux-gnu -O -L x86_64-unknown-linux-gnu/rt -C lto
    stdout:
    ------------------------------------------
    
    ------------------------------------------
    stderr:
    ------------------------------------------
    rustc: /home/nick/rust/1.0.4/source/src/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp:713: llvm::DIE* llvm::DwarfUnit::getOrCreateTypeDIE(const llvm::MDNode*): Assertion `Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."' failed.
    
    ------------------------------------------
    
    thread '[run-pass] run-pass/sepcomp-lib-lto.rs' panicked at 'explicit panic', /home/nick/rust/1.0.4/source/src/compiletest/runtest.rs:1501
    
    
    
    failures:
        [run-pass] run-pass/sepcomp-lib-lto.rs
    
    test result: FAILED. 2228 passed; 1 failed; 3 ignored; 0 measured
    
    thread '<main>' panicked at 'Some tests failed', /home/nick/rust/1.0.4/source/src/compiletest/compiletest.rs:248
    make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-rpass.ok] Error 101

**Comment by apasel422** [comment] 2015-11-10 12:22
Duplicate of #25270. Thanks for the report though!

**Closed by apasel422** 2015-11-10 12:22 UTC
