### ISSUE TITLE
`lifetime may not live long enough` may not be a right reason in invariant case

### ISSUE THREAD

**Issue by xmh0511** [rust-lang/rust#118938] opened 2023-12-14 13:12 UTC
### Code

```Rust
struct B<'a>(&'a i32,PhantomData<* mut &'a i32>);
fn foo<'a,'b>(_:&'b i32,x:&'a i32)->B<'b> where 'a:'b{
    let c:B<'a> = B(x,PhantomData);
    c
}
```

### Current output

```Shell
lifetime may not live long enough
consider adding the following bound: `'b: 'a`
requirement occurs because of the type `B<'_>`, which makes the generic argument `'_` invariant
the struct `B<'a>` is invariant over the parameter `'a`
see <https://doc.rust-lang.org/nomicon/subtyping.html> for more information about variance
```

### Desired output

```Shell
`B<'a>` cannot be coerced to `B<'b>` since the struct `B<'a>` is invariant over the parameter `'a`
```

### Rationale and extra context

As explicitly predicated by the where clause, the lifetime `'a` outlives the lifetime `'b`, so saying lifetime may not live long enough does not make sense here. The reason should be `B<'a>` cannot be coerced to `B<'b>` because `B<'x>` is invariant over the `'x`.

**Comment by QuineDot** [comment] 2024-01-21 05:47
Arguably a dupe of #108636, see also #119419

**Comment by fmease** [comment] 2024-01-21 16:05
Closing as duplicate.

**Closed by fmease** 2024-01-21 16:05 UTC
Labels: A-diagnostics, T-compiler
