### ISSUE TITLE
Const generics, the trait bound is not satisfied

### ISSUE THREAD

**Issue by tamasfe** [rust-lang/rust#68385] opened 2020-01-20 14:59 UTC
I would expect the following code to work with different const values just as it does with different types:

```rust
trait Trait<const PARAM: &'static str> {
    fn do_stuff(&self);
}

struct Struct;

impl Trait<"param"> for Struct {
    fn do_stuff(&self) {}
}

impl Trait<"another_param"> for Struct {
    fn do_stuff(&self) {}
}

fn stuff() {
    let s = Struct;

    <Struct as Trait<"param">>::do_stuff(&s);
}
```

However it fails with:

```
the trait bound `Struct: Trait<"param">` is not satisfied
the following implementations were found:
  <Struct as Trait<"another_param">>
  <Struct as Trait<"param">> rustc(E0277)
```

If implemented with only one value, the compiler infers it correctly (_universal function call still doesn't work however_), also adding brackets anywhere makes no difference.

```
rustc 1.40.0-nightly (4a8c5b20c 2019-10-23)
binary: rustc
commit-hash: 4a8c5b20c7772bc5342b83d4b0696ea216ef75a7
commit-date: 2019-10-23
host: x86_64-unknown-linux-gnu
release: 1.40.0-nightly
LLVM version: 9.0
```

**Comment by varkor** [comment] 2020-04-08 21:56
This now appears to be working.

**Comment by varkor** [comment] 2020-04-08 23:52
Closing as a duplicate of https://github.com/rust-lang/rust/issues/66596.

**Closed by varkor** 2020-04-08 23:52 UTC
Labels: A-const-generics, C-bug, E-needs-test, F-const_generics, T-compiler, requires-nightly
