### ISSUE TITLE
error: failed to run custom build command for `winapi-x86_64-pc-windows-gnu v0.4.0`

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#74474] opened 2020-07-18 09:57 UTC
error: failed to run custom build command for `winapi-x86_64-pc-windows-gnu v0.4.0`

rust version:

```rust
1.45.0
```
error: failed to run custom build command for `winapi-x86_64-pc-windows-gnu v0.4.0`

Caused by:
  could not execute process `D:\RustProject\cf\target\debug\build\winapi-x86_64-pc-windows-gnu-373993d98adf607f\build-script-build` (never executed)

Caused by:
  该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。 (os error 216)

**Comment by zhuxiujia** [comment] 2020-07-18 13:20
error: failed to run custom build command for `log v0.4.11`

**Comment by zhuxiujia** [comment] 2020-07-18 13:23
error: failed to run custom build command for `proc-macro2 v1.0.18`

Caused by:
  could not execute process `D:\RustProject\rbatis\target\debug\build\proc-macro2-9f1eb5eb98a8fc0c\build-script-build` (never executed)

Caused by:
  该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。 (os error 216)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by mati865** [comment] 2020-07-18 15:30
Windows docs say it's due to a virus: https://support.microsoft.com/en-gb/help/259279/error-message-runtime-error-216

**Comment by JohnTitor** [comment] 2020-07-18 15:41
I'm going to close this as it seems to be more of an issue with your environment than with Rust itself I think. If we have any actions we can take here, please feel free to comment with reproducible steps, thanks!

**Closed by JohnTitor** 2020-07-18 15:41 UTC
Labels: C-bug

**Comment by zhuxiujia** [comment] 2020-07-18 17:08
> I'm going to close this as it seems to be more of an issue with your environment than with Rust itself I think. If we have any actions we can take here, please feel free to comment with reproducible steps, thanks!

now,we use windows cmd  run command
```rust
cargo run 
```

It pops up a dialog saying 16-bit applications are not supported

**Comment by zhuxiujia** [comment] 2020-07-18 17:08
> Windows docs say it's due to a virus: https://support.microsoft.com/en-gb/help/259279/error-message-runtime-error-216


It pops up a dialog saying 16-bit applications are not supported

**Comment by zhuxiujia** [comment] 2020-07-18 20:33
> Windows docs say it's due to a virus: https://support.microsoft.com/en-gb/help/259279/error-message-runtime-error-216

216 is ERROR_EXE_MACHINE_TYPE_MISMATCH. The build script should always match the host architecture of the compiler, so if the compiler is able to run in the first place to build the build script then there's no reason the build script itself shouldn't be able to run... What a bizarre issue.

What I do know however is that this is not winapi's fault. winapi's build script just happens to be one of the first things that gets linked and run in most projects so if your toolchain or environment is misconfigured then winapi is one of the first to notice.
