### ISSUE TITLE
The variant of an enumeration has the same name as the function implemented for it, but this does not conflict and cannot call this function

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust#113503] opened 2023-07-09 11:45 UTC
The variant of an enumeration has the same name as the function implemented for it, but this does not conflict and cannot call this function

## Example
```rust
fn main() {
    let _x = Foo::Value(0, ());
    //let _y = Foo::Value(0); // error
}
pub enum Foo {
    Value(usize, ()),
    Nil
}
impl Foo {
    /// It cannot be used, and no errors!!
    #[allow(non_snake_case)]
    pub fn Value(num: usize) -> Self {
        Self::Value(num, ())
    }
}
```
## Info
- `cargo check` no errors and warnings.
- `rustc --version`: `rustc 1.70.0 (90c541806 2023-05-31)`
- `rustc +nightly --version`: `rustc 1.72.0-nightly (fe7454bf4 2023-06-19)`

## Expected
`error[E0592]: duplicate definitions with name 'Value'` or this function can be called

**Comment by saethlin** [comment] 2023-07-10 00:05
This is similar to https://github.com/rust-lang/rust/issues/76347 which reports the same problem with associated constants.

**Comment by petrochenkov** [comment] 2024-08-01 15:55
Closing as a duplicate of https://github.com/rust-lang/rust/issues/48758.

**Closed by petrochenkov** 2024-08-01 15:55 UTC
Labels: A-lint, T-compiler
