### ISSUE TITLE
Apparent miscompilation when building typenum on raspbian buster.

### ISSUE THREAD

**Issue by plugwash** [rust-lang/rust#60019] opened 2019-04-16 20:15 UTC
While building typenum on raspbian buster (rust target arm-linux-gnueabihf) in relase mode I get a failure. This happens when building typenum seperately and also happened as part of the raspbian package builds for cargo and librsvg (I have now worked around it in those two packages).

Rustc in raspbian buster is currently at version 1.32.0

To reproduce, do the following in a raspbian buster environment

    apt-get install rustc cargo
    git clone https://github.com/paholg/typenum
    cargo build --release

The failure is a bunch of errors like.

error[E0428]: the name `N1000` is defined multiple times
    --> /typenum/target/release/build/typenum-da1991768bfa4481/out/consts.rs:2119:35

The problem appears to be caused by incorrect behaviour of the following code in build/main.rs

    let highest: u64 = 1024;
    
    let first2: u32 = (highest as f64).log(2.0).round() as u32 + 1;                                                   
    let first10: u32 = (highest as f64).log(10.0) as u32 + 1;                                                         
    let uints = (0..(highest + 1))                                                                                    
        .chain((first2..64).map(|i| 2u64.pow(i)))                                                                     
        .chain((first10..20).map(|i| 10u64.pow(i)));

From investigating the output file it seems that "first2" and "first10" are being miscalculated. First10 appears to be coming out as zero resulting in duplicates while first2 eppears to be coming out as a sufficiently large number to prevent generation of power of two types at all.

When I replace the calculation of first2 and first10 with hardcoded values I can build the crate successfully in release mode. I used this workaround in the raspbian cargo and librsvg packages.

**Comment by sanxiyn** [comment] 2019-04-17 01:17
I tried to reproduce this on Scaleway C1(cloud ARM server) with rustup binaries and failed. In particular, 1.32.0-arm, 1.32.0-armv7, 1.34.0-arm, 1.34.0-armv7 all worked without errors.

@plugwash, in order to diagnose where the problem is, can you try with rustup binaries?

**Comment by plugwash** [comment] 2019-04-18 12:04
I tried installing rustc with rustup, I selected version 1.32.0 and host triplet arm-linux-gnueabihf and was unable to reproduce the bug with it.

I'm suspecting this may be a llvm issue, do you know what version of llvm the rustup 1.32.0 binaries are built against (the raspbian ones are built against the system llvm-toolchain-7).

**Comment by jonas-schievink** [comment] 2019-04-18 12:20
Closing as this looks like a packaging issue in raspbian/debian.

@plugwash I think the LLVM version used by that is a patched 8.0 - https://github.com/rust-lang/llvm-project/tree/rustc/8.0-2019-01-16

**Closed by jonas-schievink** 2019-04-18 12:20 UTC
Labels: A-LLVM, A-codegen, C-bug, O-ARM, T-compiler

**Comment by matthijskooijman** [comment] 2019-07-11 08:35
I also ran into this issue and traced it a bit more. I've found https://github.com/paholg/typenum/pull/115 which seems related, but is not (symptoms are different and the patch does not help). I've also found that replacing the `libllvm7` package with the [one from Debian](https://packages.debian.org/buster/libllvm7) fixes the problem, so this is *probably* a Raspbian-specific problem.

**Comment by matthijskooijman** [comment] 2019-07-11 12:43
I reported a bug at https://bugs.launchpad.net/raspbian/+bug/1836203

**Comment by plugwash** [comment] 2019-07-17 02:17
For the record I finally got to the bottom of this as the result of another issue.

It seems that when built for armv6 llvm 7 defaults to no FPU (this doesn't seem to be an issue with llvm 6 or 8). When building code with the hard float ABI selected but no FPU selected LLVM miscompiles the code. Specifically it tags the binaries as using the hard float ABI, but actually uses what appears to be the baseline soft float ABI.

Fixing our LLVM builds in raspbian to actually use the FPU fixed the issue with rust miscompiling typenum. 

rust seems to override the llvm defaults, so binaries built by our rust did (at least for the most part) follow the ABI. However the llvm package in Debian/Raspbian is built with it's own clang, so llvm itself was miscompiled. I believe that the failure described in this bug report most likely happened when the llvm optimiser tried to call into the C standard library to calculate the logarithm value.
