### ISSUE TITLE
Switch rustc/std/etc ("Rust") to an anarchy-based development model

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#60339] opened 2019-04-27 18:06 UTC
Mozilla appears to be moving to a hostile management structure, as such it seems reasonable to explore alternative development models for rust so as to decouple it from mozilla.

My personal proposal, and the only one I know of (I don't know anything else that works like this), is the use of [GAnarchy](https://ganarchy.autistic.space/). GAnarchy is a "project page generator", written in Python, designed to encourage anarchy-based development models.

Rather than having pull requests coming from "peripheral" repos into a "central" repo, and issues that only make sense on the "central" repo, GAnarchy proposes a development model where there is no "central" repo and no pull requests, instead having every repo owner pull from random other repos as they see fit.

Anyone can become a repo owner and be listed on a GAnarchy instance. This means the project loses the idea of a "vision" (as defined by the developers) and instead becomes need-driven (or user-driven).

[This paragraph refers to a future, unpublished, work-in-progress version of GAnarchy] Issues are not tracked in a central location, either, but are instead aggregated from multiple fediverse instances. Anyone on the fediverse (also erroneously referred to as "mastodon") can open issues. Any GAnarchy instance may include these issues, or they may exclude these issues, and the issues are sorted by activity so as to prevent off-topic issues from sticking around.

Obviously, GAnarchy isn't the only tool that can do this. Or rather, it actually may be. I don't know of another tool like GAnarchy but I'd love to be proven wrong! GAnarchy should not be the *only* way to run a project using an anarchy-based development model.

In any case, this kind of development model, with the help of GAnarchy or any other tool or just a strong community willing to make it work, would throw a wrench in the parent company's hostility plans. Anyway this got too long and now I'm lost, but, to put it simple, I believe this "alternative" development model would make things a lot better for Rust. All it really requires is a "project commit": an empty commit that defines the project title and description. See [the GAnarchy README](https://cybre.tech/SoniEx2/ganarchy#usage) for what the commit message should look like.

Please don't let mozilla throw Rust in the bin. If it's what it takes, give it back to the community instead.

**Comment by Centril** [comment] 2019-04-27 18:52
Rust is a project independent from Mozilla. For example, the language team consists to 5/9 of people that are not Mozilla employees. Of the core team, only 3 of 9 are Mozilla employees. I don't think Mozilla has even the most employees in the world that program Rust. That title probably belongs to Google by now. The suggestion that Rust is coupled to Mozilla is therefore just wrong.

Rust uses a deliberative process where designs are proposed, discussed in the wider community, and teams then reach consensus. This is by design and is necessary both for efficiency and to end up with an internally coherent language. If anything, we are moving towards a more deliberative process by using working groups to plan and work on different subsystems.

I know of no notable programming language in the world that operates in the model you've described and I think it's safe to say that Rust is not going to adopt your model of development. As such, and to spare everyone from a discussion which is of no use, at least here, I will close this issue.

**Closed by Centril** 2019-04-27 18:52 UTC

**Comment by SoniEx2** [comment] 2019-04-27 18:58
lock the issue?
