### ISSUE TITLE
ICE while compiling `redis-0.16.0`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#81606] opened 2021-01-31 19:52 UTC
### Code

CI in `teloxide` project failed with ICE: 
- PR: https://github.com/teloxide/teloxide/pull/335
- failed CI: https://github.com/teloxide/teloxide/pull/335/checks?check_run_id=1802208287

I don't have much time to research this, so I'm providing the error as is.

### Meta

```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
```

### Error output

```
error: internal compiler error: failed to process buffered lint here
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.16.0/src/macros.rs:5:54
    |
5   |           return Err(::std::convert::From::from($expr));
    |                                                        ^
    | 
   ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/redis-0.16.0/src/aio.rs:377:18
    |
377 |               _ => fail!((
    |  __________________-
378 | |                 ErrorKind::ResponseError,
379 | |                 "Redis server refused to switch database"
380 | |             )),
    | |______________- in this macro invocation
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
```

**Comment by jonas-schievink** [comment] 2021-01-31 19:54
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-01-31 19:54 UTC
Labels: C-bug, I-ICE, T-compiler
