### ISSUE TITLE
Trait impl detection fails when using associated types aliased to eachother

### ISSUE THREAD

**Issue by Osspial** [rust-lang/rust#54375] opened 2018-09-20 02:46 UTC
When attempting to compile the following code, the compiler mistakenly rejects it, complaining that the `Point` type returned by `max` doesn't implement `Sub<Self::D::Vector>`. However, `Point` *does* implement the trait - it's just that `EuclideanSpace::Diff` is being aliased through `Dimensionality::Vector`.

[Playground link](https://play.rust-lang.org/?gist=ecda6ac4c470809bd450c0d012a080b5&version=stable&mode=debug&edition=2015)
```rust
use std::ops::*;

pub trait Geometry {
    type D: Dimensionality;

    fn min(&self) -> <Self::D as Dimensionality>::Point {
        self.max() - self.dims()
    }

    fn max(&self) -> <Self::D as Dimensionality>::Point;
    
    fn dims(&self) -> <Self::D as Dimensionality>::Vector;
}

pub trait Dimensionality {
    type Point: EuclideanSpace<Diff=Self::Vector>;
    type Vector;
}

pub trait EuclideanSpace:
    Copy + Clone +
    Add<<Self as EuclideanSpace>::Diff, Output = Self> +
    Sub<<Self as EuclideanSpace>::Diff, Output = Self>
{
    type Diff;
}
```

Redefining `fn dims` as follows so that it directly returns the requested type *also* fails to compile, with the same error:

[Playground link](https://play.rust-lang.org/?gist=d9969b09a46b0d651ad2567ca64406aa&version=stable&mode=debug&edition=2015)
```rust
fn dims(&self) -> <<Self::D as Dimensionality>::Point as EuclideanSpace>::Diff;
```

It seems the only way to make that code compile is to redefine `Dimensionality` as follows, removing the alias between `EuclideanSpace::Diff` and `Dimensionality::Vector`:

[Playground link](https://play.rust-lang.org/?gist=af3499b85fd4db091bb79ed5d34dd788&version=stable&mode=debug&edition=2015)
```rust
pub trait Dimensionality {
    type Point: EuclideanSpace;
    type Vector;
}
```

This is happening on all versions of the compiler I've tested, one of those being stable 1.29.0.

**Comment by rkarp** [comment] 2018-10-07 13:11
This is another duplicate of #24159, which I know all too well by now. Here's how to fix your first example:

[Playground Link](https://play.rust-lang.org/?gist=8c5de39349361a641a1c493ab9e8fa1d&version=stable&mode=debug&edition=2015)

**Comment by jonas-schievink** [comment] 2019-04-21 22:35
Closing as a duplicate of #24159

**Closed by jonas-schievink** 2019-04-21 22:35 UTC
