### ISSUE TITLE
SIGILL while running the test suite of a few crates

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#47616] opened 2018-01-20 19:21 UTC
The test suites of a few crates are crashing with a SIGILL in the latest beta.

* Crate [byond](https://crates.io/crates/byond) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/byond-0.3.2/log.txt)).
* Crate [consistenttime](https://crates.io/crates/consistenttime) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/consistenttime-0.2.0/log.txt)).
* Crate [mujs](https://crates.io/crates/mujs) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/mujs-0.0.3/log.txt)).
* Crate [seckey](https://crates.io/crates/seckey) regressed from stable to beta ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/seckey-0.6.1/log.txt)).

cc @PJB3005

**Comment by pietroalbini** [comment] 2018-01-20 20:02
Crate [consistenttime](https://crates.io/crates/consistenttime) also regressed ([crater log](http://cargobomb-reports.s3.amazonaws.com/1.23.0-1.24.0-beta.3/beta-2018-01-13/reg/consistenttime-0.2.0/log.txt)).

cc @valarauca

**Comment by PJB3005** [comment] 2018-01-20 20:28
It might be related to my crate not being thread safe. This is because the library is intended to be invoked from a proprietary C++ program (BYOND) using FFI, and said program isn't threaded at all, so I saw no need to make it thread safe and just used a mutable static.

I don't test the crate directly, but a library I made using the crate does and I did both `RUST_TEST_THREADS=1` and `--jobs 1` on the cargo test job for it: https://github.com/vgstation-coders/vgstation13/blob/2edf31f9d0aeea4045240571090156a8a6c88254/.travis.yml#L43

**Comment by pietroalbini** [comment] 2018-01-20 20:59
I tested your crate again with just one thread and it still crashes. Can you please manually test it?

Be sure to use the beta channel though: the error doesn't appear on stable (only beta and nightly), and the travis configuration you linked just tests on stable.

**Comment by PJB3005** [comment] 2018-01-20 22:20
Ok yeah I can definitely confirm it's crashing due to a `SIGILL` on beta. How strange...

**Comment by PJB3005** [comment] 2018-01-20 22:43
Ok I figured it out. Seems like panicking across an `extern "C"` causes the `SIGILL`. Example code causing it:

```rust
extern "C" fn foo() {
    panic!("uh oh");
}

#[test]
fn does_it_break() {
    foo()
}
```

Now whether or not this *should* be legal I'm not sure of, so if this was just an implementation detail I'll just remove the bad tests.

**Comment by durka** [comment] 2018-01-21 01:04
Panicking across FFI boundaries is [definitely undefined behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html).

**Comment by PJB3005** [comment] 2018-01-21 01:06
Yeah I don't doubt it, but on the other hand none of this is explicitly marked unsafe so I don't know how that fits in here.

**Comment by sfackler** [comment] 2018-01-21 01:16
This is caused by #46833 protecting from undefined behavior by aborting instead.

**Comment by durka** [comment] 2018-01-21 01:39
Huh... I would've thought you'd need `unsafe` to call any `extern "C"` function.

**Comment by bluss** [comment] 2018-01-21 11:51
No reason to worry — abort is violent but memory safe. And it is now mentioned in the reference https://github.com/rust-lang-nursery/reference/pull/196

**Comment by nagisa** [comment] 2018-01-21 13:17
`extern "C"` only specifies the calling convention to use¹. I’m not sure we want to call that a "FFI boundary", as both caller and callee are both (safe) Rust code, but it is also something that was never specified to *not* be a FFI boundary, so breakage seems fine.

[¹]: using a different calling convention does not make the code/function unsafe.

**Comment by pietroalbini** [comment] 2018-01-21 17:20
Crate [mujs](https://crates.io/crates/mujs) is also affected. cc @hean01

**Comment by pietroalbini** [comment] 2018-01-21 17:46
Crate [seckey](https://crates.io/crates/seckey) is also affected. cc @quininer

**Comment by Mark-Simulacrum** [comment] 2018-01-31 17:51
I believe this is expected -- @rust-lang/lang can you confirm that we are okay with this regression? To be clear, https://github.com/rust-lang/rust/pull/46833 made it so that we do not unwind across FFI boundaries, and instead abort. Currently inclined to close as these crates were depending on UB.

**Comment by joshtriplett** [comment] 2018-01-31 17:58
How hard would it be, in debug mode, to provide more detailed panic information in this case rather than just an abort?

**Comment by PJB3005** [comment] 2018-01-31 18:01
FWIW, I'm fine with this being "regressed".

**Comment by Mark-Simulacrum** [comment] 2018-01-31 22:29
@joshtriplett @diwic or @nikomatsakis can probably comment on providing more information in debug mode. I think that sounds like something we could improve and add to... seems simple in theory, but may have implications I'm not aware of. There's some comments on #46833 I think.

**Comment by nikomatsakis** [comment] 2018-02-01 15:17
This is expected behavior. The idea roughly is that specifying the ABI *does indeed* specify whether a panic is allowed -- it's not so much about the FFI boundary, as about the fact taht `extern "C"` functions don't have a defined way to propagate unwinding (particularly since our panic mechanism is an undefined impl detail, and hence specific to the Rust ABI).

Obviously it'd be nice to give a better error message.

**Comment by nikomatsakis** [comment] 2018-02-01 15:17
Closing as "expected behavior" in this case =)

**Closed by nikomatsakis** 2018-02-01 15:17 UTC
Labels: T-lang, regression-from-stable-to-beta

**Comment by diwic** [comment] 2018-02-01 18:26
The easy answer is that the `extern C` ABI does not support unwinding and therefore it must be stopped. But that is not entirely accurate, because we do have a few `extern C` function that can start unwinding. These are marked with the `#[unwind]` attribute (this attribute is only available on nightly). If the `unwind` attribute is not present on an `extern C` function (and some other ABIs as well, such as e g `stdcall`), we tell LLVM that the function is a "nounwind" function, and unwinding from a function that is "nounwind" - that is, my friends, undefined behaviour.

Now, we could have just told LLVM that no functions are "nounwind". But - apart from possible negative impact on optimisations and/or code size - that would be a against the **practical** goal here, which is to avoid as many panics into FFI land as possible, where the panic could cause all sorts of unexpected problems.
