### ISSUE TITLE
`use super::*` importing private members from parent module

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#38176] opened 2016-12-05 14:39 UTC
Reproduction script: https://is.gd/qvbF0b

This code compiles on stable and beta but fails to compile on nightly. `use super::*` previously did not include private members. On nightly it is reported that "`Foo` is ambiguous"

**Comment by bluss** [comment] 2016-12-05 15:06
It's an intentional change, but everything that makes stable code stop compile is classed as a regression initially.

**Comment by sgrif** [comment] 2016-12-05 15:19
Figured as much. I believe technically this is a "minor breaking change" since code can be forwards compatibly changed to handle this by not using glob imports, right? Is it still a regression in that case? Either way a release where this warns instead of erroring would definitely be nice.

**Comment by jseyfried** [comment] 2016-12-06 06:03
@sgrif right, there can only be a regression when [these conditions](https://github.com/rust-lang/rust/issues/35120#issuecomment-253050153) are met.

We landed this change #37127 without a warning cycle because Crater found no breakage. It would be feasible to implement a warning cycle as detailed in https://github.com/rust-lang/rust/issues/35120#issuecomment-253050153.

cc @nrc

**Comment by sgrif** [comment] 2016-12-06 11:24
As an aside, I don't think that Crater finding no breakage should be used as justification for skipping warning cycles. It does not examine all available Rust code, or even all code on crates.io

**Comment by nikomatsakis** [comment] 2016-12-08 21:21
Discussed in @rust-lang/compiler meeting. Indeed *some* fallout from these changes was expected but a warning cycle is still appropriate. The only reason to skip a warning cycle is supposed to be if a warning cycle is technically infeasible -- in which case we are to use crater to make a best effort to have all affected crates get updated beforehand.

**Comment by nikomatsakis** [comment] 2016-12-08 21:25
triage: P-high

Specifically, high priority to add a warning cycle.

**Closed** 2016-12-20 22:02 UTC
Labels: P-high, regression-from-stable-to-nightly, T-compiler, T-lang
