### ISSUE TITLE
rustc is generating dll files to incorrect folder on Windows (?)

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#49086] opened 2018-03-16 13:37 UTC
I have
```toml
[lib]
name = "foo"
crate-type = ["cdylib"]
```
to build a dll. This used to work (last year) but not anymore. It doesn't build a .dll (there is not a single dll file in `target/**/*`), only builds a 0 kb `foo.rmeta` and a 1kb `foo.d` file.

Any idea what's wrong?

Win 8.1
nightly-x86_64-pc-windows-msvc (default)
rustc 1.26.0-nightly (2789b067d 2018-03-06)

**Comment by Boscop** [comment] 2018-03-16 13:44
Nevermind, I was accidentally using `cargo check` instead of `build` in my editor..
So it generates the dll now, but what's weird is that in one project it generates the dll in `target\i686-pc-windows-msvc\debug` but in the other project, it generates it in `target\debug\examples` instead of in `target\i686-pc-windows-msvc\debug\examples`, even though both projects have the same `.cargo/config`:
```toml
[build]
target = "i686-pc-windows-msvc"
```
The first one in the main project dir, the second one in `examples`.
So why isn't the second one writing the dll to `target\i686-pc-windows-msvc\debug\examples`?
(That folder exists but it has the old dll files from last year, so it **used** to generate to that folder correctly.)

**Comment by pietroalbini** [comment] 2018-03-20 22:40
cc @retep998

**Comment by retep998** [comment] 2018-03-20 23:38
>The first one in the main project dir, the second one in examples.

This was entirely the issue. The second `.cargo/config` was not actually applying because it wasn't in the set of paths that cargo searches for it.

**Comment by Boscop** [comment] 2018-03-21 00:46
But that's unintuitive. IMO cargo should be changed to use the `.cargo/config` in `examples` folder only for examples.

Also because currently there is no way to apply a cargo config only to the examples..

**Comment by retep998** [comment] 2018-03-21 02:52
Doing something like `target = "i686-pc-windows-msvc"` for just the `examples` folder doesn't really make sense, as building the examples for that target requires also building the crate and all its dependencies for that target too. `.cargo/config` currently affects the *entire build*. You can't just affect a specific crate with it.

As far as I can tell Cargo is working as designed here, and at worst the bug is a failure of the documentation to properly explain how `.cargo/config` applies to builds.

**Comment by jonas-schievink** [comment] 2020-04-20 20:18
This should be filed over at https://github.com/rust-lang/cargo, so closing

**Comment by jonas-schievink** [comment] 2020-04-20 20:18
Actually this is properly documented now: https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure

**Closed by jonas-schievink** 2020-04-20 20:18 UTC
Labels: C-bug, O-windows
