### ISSUE TITLE
Non-lexical lifetimes has different behavior for Vec<&i32> and Vec<&String>

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#46953] opened 2017-12-22 21:38 UTC
With 1.24.0-nightly (2017-12-21 250b492052e94d76bd318a4b932159395da55981):

This compiles:

```rust
#![feature(nll)]

fn main() {
    let mut vec = Vec::new();

    let a = 1;
    vec.push(&a);

    let b = 2;
    vec.push(&b);

    println!("{:?}", vec);
}
```

But this does not:

```rust
#![feature(nll)]

fn f() {
    let mut vec = Vec::new();

    let a = String::from("");
    vec.push(&a);

    let b = String::from("");
    vec.push(&b);

    println!("{:?}", vec);
}

fn main() {}
```

```
error[E0597]: `a` does not live long enough
  --> src/main.rs:7:14
   |
7  |     vec.push(&a);
   |              ^^ borrowed value does not live long enough
...
13 | }
   |  - borrowed value only lives until here
   |
   = note: borrowed value must be valid for lifetime '_#11r...
```

/cc @arielb1 @nikomatsakis

**Comment by Ryman** [comment] 2017-12-23 00:03
The first example has constant propagation (or whatever that's called these days) occurring, you can add `let _: Vec<&'static i32> = vec;` to the end and it still compiles which shows they're getting promoted to statics. 

In the second, if you bring `a` and `b` to be above `vec` then the example works. Isn't this necessary due to destructor ordering? I'm not up to date on NLL enough to know if that's intended to work.

**Comment by CryZe** [comment] 2017-12-23 00:49
This seems to be a duplicate of #46935

**Comment by nikomatsakis** [comment] 2017-12-23 12:51
I have a suspicion what this might be but will investigate. On Dec 22, 2017 4:39 PM, Jake Goulding <notifications@github.com> wrote:With 1.24.0-nightly (2017-12-21 250b492):
This compiles:
#![feature(nll)]

fn main() {
    let mut vec = Vec::new();

    let a = 1;
    vec.push(&a);

    let b = 2;
    vec.push(&b);

    println!("{:?}", vec);
}
But this does not:
#![feature(nll)]

fn f() {
    let mut vec = Vec::new();

    let a = String::from("");
    vec.push(&a);

    let b = String::from("");
    vec.push(&b);

    println!("{:?}", vec);
}

fn main() {}
error[E0597]: `a` does not live long enough
  --> src/main.rs:7:14
   |
7  |     vec.push(&a);
   |              ^^ borrowed value does not live long enough
...
13 | }
   |  - borrowed value only lives until here
   |
   = note: borrowed value must be valid for lifetime '_#11r...

/cc @arielb1 @nikomatsakis

**Comment by nikomatsakis** [comment] 2018-01-04 10:34
Both versions compile now: https://play.rust-lang.org/?gist=79c56c0a2310df3880212d7124be65cd&version=nightly

Fixed by https://github.com/rust-lang/rust/pull/46984

**Closed by nikomatsakis** 2018-01-04 10:34 UTC
Labels: A-NLL, C-bug, T-compiler, WG-compiler-nll
