### ISSUE TITLE
Iterator.cloned() doesn't work for Iterator.Item = &mut T

### ISSUE THREAD

**Issue by wintersm1th** [rust-lang/rust#93199] opened 2022-01-22 13:17 UTC
I suggest to implement method .cloned for Iterator<Item = &mut T>. Currently this method only works for iterators with Item = &T.

```rust
let mut source = ["a", "b", "c", "d"].map(String::from);
let mut iter = source.iter_mut();
let sp: Vec<String> = iter.by_ref().take(2).map(|x| x.clone()).collect(); // works correctly
let fp: Vec<String> = iter.by_ref().take(2).cloned().collect(); // error[E0271]
```

Error message:
```
error[E0271]: type mismatch resolving `<std::iter::Take<&mut std::slice::IterMut<'_, String>> as Iterator>::Item == &_`
note:
    expected reference `&_`
    found mutable reference `&mut String`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-unknown-linux-gnu
release: 1.58.1
LLVM version: 13.0.0
```

**Comment by compiler-errors** [comment] 2022-01-23 03:41
I believe this behavior is expected. 

In the working example `sp` is coerced from `&mut T` to `&T` by autoref. 
In contrast, for `fp`, `Iterator::cloned` only takes iterators of `&T`, not iterators of things that coerce into `&T`.

**Comment by fmease** [comment] 2024-01-24 11:03
Closing as works as intended. Please speak up if I should reopen this issue.

**Closed by fmease** 2024-01-24 11:03 UTC
Labels: T-compiler, A-coercions
