### ISSUE TITLE
A bug in rustc compiler !!

### ISSUE THREAD

**Issue by Harshil-Jani** [rust-lang/rust#114592] opened 2023-08-07 17:53 UTC
I tried this code:

```rust
cargo test --features="compiler serde"
```

I expected to see this happen: All the test cases being compiled successfully.

Instead, this happened: A jargon of bugs which I cannot understand.
```
thread 'rustc' panicked at 'index out of bounds: the len is 12582912 but the index is 13408274727185679497', /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/compiler/rustc_serialize/src/leb128.rs:83:1
stack backtrace:
   0:     0x7ff3b8b6731a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff3b8b6731a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff3b8b6731a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7ff3b8b6731a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7ff3b8bcab6e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x7ff3b8b5a2c5 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x7ff3b8b670e5 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7ff3b8b670e5 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7ff3b8b69e5f - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x7ff3b8b69b9b - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x7ff3bbdcb8b5 - <rustc_driver_impl[fb92b3e21ac03dce]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[911a585bea10363d]::ops::function::FnOnce<(&core[911a585bea10363d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7ff3b8b6a69d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6507bddc3eebb4a5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
  12:     0x7ff3b8b6a69d - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
  13:     0x7ff3b8b6a419 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  14:     0x7ff3b8b67786 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7ff3b8b6a122 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  16:     0x7ff3b8bc6ec3 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  17:     0x7ff3b8bc70b2 - core::panicking::panic_bounds_check::haf06fefb23eba82d
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:159:5
  18:     0x7ff3bb07c5fe - <rustc_query_impl[a4bd04fc7a0236b8]::on_disk_cache::OnDiskCache as rustc_middle[1a4ce3311a146f18]::ty::context::OnDiskCache>::new
  19:     0x7ff3bb02240c - rustc_incremental[80eb23617c4b1afb]::persist::load::load_query_result_cache::<rustc_query_impl[a4bd04fc7a0236b8]::on_disk_cache::OnDiskCache>
  20:     0x7ff3bb021696 - rustc_interface[bd8390756bd7a52a]::passes::create_global_ctxt
  21:     0x7ff3bb01f654 - <rustc_interface[bd8390756bd7a52a]::queries::Queries>::global_ctxt
  22:     0x7ff3bb01cc44 - rustc_span[fab0eb11f1fed58d]::with_source_map::<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  23:     0x7ff3bb0143cc - std[685882fd5f6d52e5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bd8390756bd7a52a]::util::run_in_thread_pool_with_globals<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>
  24:     0x7ff3bb013dfa - <<std[685882fd5f6d52e5]::thread::Builder>::spawn_unchecked_<rustc_interface[bd8390756bd7a52a]::util::run_in_thread_pool_with_globals<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_driver_impl[fb92b3e21ac03dce]::run_compiler::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#1} as core[911a585bea10363d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7ff3b8b74593 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39990b24eedef2ab
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  26:     0x7ff3b8b74593 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h01a027258444143b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  27:     0x7ff3b8b74593 - std::sys::unix::thread::Thread::new::thread_start::ha4f1cdd9c25884ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7ff3b890544b - <unknown>
  29:     0x7ff3b8988e40 - <unknown>
  30:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `miniscript`
warning: build failed, waiting for other jobs to finish...
warning: execution failed: cargo test --features="compiler serde"
You can fix the problem, and then run

  git rebase --continue



```

### Solution I know

`rustup update` and then re-run the command and it worked.

**Comment by AaronKutch** [comment] 2023-08-07 19:04
If this is a incremental compilation bug or some other bug that still exists in the current `rustc`, you need to give reproduction steps using the current compiler, 1.69.0 is old and can tell us nothing, besides you haven't given any reproduction steps with the old compiler and all we have to work with is an obscure backtrace in formatting code.

**Comment by saethlin** [comment] 2023-08-10 01:54
I recently closed a number of issues just like this one with the following message:

> I am closing this because it is an incremental compilation ICE related to a component of rustc that has gotten a fair few tweaks recently; it is entirely possible that the root cause of this issue has been fixed.
> 
> If you see a crash like this again on Rust 1.70 or later please do not hesitate to open a new issue.

So I am going to close this one as well.

----

That being said...

>  1.69.0 is old and can tell us nothing, besides you haven't given any reproduction steps with the old compiler and all we have to work with is an obscure backtrace in formatting code.

That is wrong. These reports are useful on their own without steps to reproduce, because they let us know that there is (or was) a problem. Such reports encouraged me to clean up some odd-looking code, and right around that time the reports like this stopped appearing. The backtrace is in formatting code because it is formatting the panic message.

> A backtrace by itself can sometimes give enough information, but an "index out of bounds" usually means some runtime problem that can only be debugged after knowing the steps to reproduce.

People who know the compiler better than I sometimes debug these reports entirely from the backtrace. The index out of bounds message here is meaningful to me because I know a thing or two about the exact code path here that hit the panic.

Please don't discourage people from reporting bugs. The ICE message says "we would appreciate a bug report", that is not by accident.

**Closed** 2023-08-10 01:54 UTC
Labels: I-ICE, A-incr-comp, C-bug
