### ISSUE TITLE
Program fails to compile with new trait implementation

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#41812] opened 2017-05-07 15:34 UTC
playpen: https://is.gd/asNxA7

```rust
#![allow(dead_code)]

struct Point {
    x: f32,
    y: f32,
}

/// Bounding box
struct Bbox {
    pub xmin: f32,
    pub xmax: f32,
    pub ymin: f32,
    pub ymax: f32,
}

impl Bbox {
    fn intersects(&self, bbox: &Bbox) -> bool {
        if bbox.contains(&self) {
            false
        } else {
            (self.xmin >= bbox.xmin && self.xmin <= bbox.xmax || self.xmax >= bbox.xmin && self.xmax <= bbox.xmax) &&
            (self.ymin >= bbox.ymin && self.ymin <= bbox.ymax || self.ymax >= bbox.ymin && self.ymax <= bbox.ymax)
        }
    }
}

pub trait Contains<Rhs = Self> {
    fn contains(&self, rhs: &Rhs) -> bool;
}

// If you uncomment this `impl` the program no longer compiles
/*
impl Contains<Point> for Bbox {
    fn contains(&self, p: &Point) -> bool {
        p.x >= self.xmin && p.x <= self.xmax && p.y >= self.ymin && p.y <= self.ymax
    }
}
*/

impl Contains<Bbox> for Bbox {
    fn contains(&self, bbox: &Bbox) -> bool {
        self.xmin <= bbox.xmin && self.xmax >= bbox.xmax && self.ymin <= bbox.ymin &&
        self.ymax >= bbox.ymax
    }
}

fn main() {}
```

If you uncomment that trait implementation, here's the error:

```
rustc 1.19.0-nightly (f4209651e 2017-05-05)
error[E0277]: the trait bound `Bbox: Contains<&Bbox>` is not satisfied
  --> <anon>:18:17
   |
18 |         if bbox.contains(&self) {
   |                 ^^^^^^^^ the trait `Contains<&Bbox>` is not implemented for `Bbox`
   |
   = help: the following implementations were found:
             <Bbox as Contains<Point>>
             <Bbox as Contains>

error: aborting due to previous error
```

**Comment by arielb1** [comment] 2017-05-07 16:09
That's to be expected. We only use traits to advance inference when we can resolve to an impl.

**Comment by frewsxcv** [comment] 2017-05-07 16:11
Can you expand on that? I'm confused how adding a new trait implementation can cause seemingly unrelated breakage

**Comment by kennytm** [comment] 2017-05-07 16:19
You should write `bbox.contains(self)`, not `bbox.contains(&self)`. (`&self` has type `&&BBox`.)

**Comment by frewsxcv** [comment] 2017-05-07 16:21
@kennytm I can understand that part, but then why does it compile at all without uncommenting that block?

**Comment by arielb1** [comment] 2017-05-07 16:50
@frewsxcv 

The problem is that rustc has to figure out how much autoderefs to insert in order to make the program valid. That's an "ambiguity" - the type of the expression `&self` (aka `& $0`) is `&&Bbox`, so either 0 or 1 derefs can be inserted (+1 reborrow) looking only at the type.

Because of the predicate `Bbox: Contains<$0>` must hold, having 0 derefs is not "globally" valid. However, when resolving "ambiguities", rustc always considers only type information and not trait information, so it does not see that predicate, picks 0 derefs (because coercion always "eagerly" picks the smallest # of derefs possible), and reports an error.

I think this is required when evaluating trait *predicates* because it allows us to consider 1 trait predicate at a time and avoid getting into deep "rabbit holes", but at the "top-level" I think this is mostly a performance feature, and that we could get the extra performance with better caching (aka Chalk, through Chalk's "better caching" is currently pixie dust).

So why does this work if there is only one impl? rustc has a feature that if it can narrow down impl selection to one impl, it can add the requirements of that impl.

**Comment by frewsxcv** [comment] 2017-05-10 01:35
You lost me on the specifics, but I mostly understand at a high level.

The particular frustration here is that as a maintainer/release-manager for crate, I would have expected adding a new `impl` to _not_ be a breaking change. The fact that we do these sorts of optimizations in some cases, but not others makes it hard to understand what exactly constitutes a breaking change.

**Comment by frewsxcv** [comment] 2017-05-10 01:37
@arielb1 also, forgot to thank you for putting the effort into your previous message, so thanks, I really do appreciate it 🙇

**Comment by Mark-Simulacrum** [comment] 2017-06-22 18:47
I believe that this isn't really a bug in rustc -- that is, it's a side effect of current trait selection, but not something that we'd directly change because of this issue. As such, closing.

**Closed by Mark-Simulacrum** 2017-06-22 18:47 UTC
