### ISSUE TITLE
Rustdoc: Omit default generic arguments

### ISSUE THREAD

**Issue by trolleyman** [rust-lang/rust#82097] opened 2021-02-14 12:31 UTC
I think it'd be nice to omit generic arguments that are equal to the default. This would be mainly to stop things like `Box<T, Global>` in the `std` docs, which I think leads them to be unnecessarily noisy.

![image](https://user-images.githubusercontent.com/4435960/107876791-1d57c680-6ec0-11eb-9eb2-700345668fe5.png)

The strange thing is, it happens inconsistently - sometimes the argument is given and sometimes it isn't.

e.g.: https://doc.rust-lang.org/stable/std/boxed/struct.Box.html
![image](https://user-images.githubusercontent.com/4435960/107876838-85a6a800-6ec0-11eb-866f-a01c514c9a51.png)

**Comment by sfackler** [comment] 2021-02-14 13:21
Duplicate of #80379

**Closed by sfackler** 2021-02-14 13:21 UTC

**Comment by trolleyman** [comment] 2021-02-15 00:50
Thanks, sorry for the duplication.
