### ISSUE TITLE
Move `rustc_passes::liveness` to MIR

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#68419] opened 2020-01-21 17:14 UTC
Discussion in https://discordapp.com/channels/442252698964721669/443151243398086667/669220265821077535.

The liveness linting code in `rustc_passes::liveness` works on HIR using backwards dataflow. The code is quite complicated and imprecise. Moving it to `rustc_mir::transform` as a new pass could simplify the compiler, improve maintainability, as well as improve precision (e.g., sub-binding level precision for tuples, structs, and arrays).

cc @oli-obk cc @eddyb cc https://github.com/rust-lang/rust/issues/65467 cc https://github.com/rust-lang/rust/issues/51003

**Comment by eddyb** [comment] 2020-01-27 21:12
Isn't this a duplicate of #51003? cc @nikomatsakis @pnkfelix

**Comment by nikomatsakis** [comment] 2020-01-28 07:27
I believe it is, closing as duplicate of #51003.

**Closed by nikomatsakis** 2020-01-28 07:27 UTC
Labels: A-mir, C-cleanup, C-enhancement, E-hard, E-medium, T-compiler
