### ISSUE TITLE
NLL / MIR-borrowck regression in serde

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#48179] opened 2018-02-13 08:36 UTC
On `nightly-2018-02-13` 16362c737, `RUSTFLAGS=-Zborrowck=mir cargo build` causes the first error below and `RUSTFLAGS=-Znll cargo build --all-features` causes the second one. I don’t know if they’re related.

```rust
   Compiling serde v1.0.27 (file:///home/simon/projects/servo-deps/serde/serde)
error[E0505]: cannot move out of `self` because it is borrowed
    --> serde/src/private/de.rs:1152:22
     |
1151 |                 Content::Map(ref v) if v.is_empty() => visitor.visit_unit(),
     |                              ----- borrow of `self.content.0` occurs here
1152 |                 _ => self.deserialize_any(visitor),
     |                      ^^^^ move out of `self` occurs here

error: aborting due to previous error

error: Could not compile `serde`.
```
```rust
error: internal compiler error: unresolved type in dtorck

error: aborting due to previous error

error: Could not compile `serde`.
```

CC @nikomatsakis

**Comment by Aaron1011** [comment] 2018-02-15 20:28
@SimonSapin: While I can reproduce the second error (`unresolved type in dtorck`), I can't reproduce the first. Is it fixed on the latest nightly for you as well?

**Comment by SimonSapin** [comment] 2018-02-15 22:38
No, I can still reproduce both on rustc 1.25.0-nightly (3ec5a99aa 2018-02-14).

**Comment by Aaron1011** [comment] 2018-02-16 00:18
@SimonSapin: Oops, I misread your first comment. I didn't see that it took two sets of flags to produce the errors.

My understanding is that the combination of `-Z nll -Z borrowck=mir -Z nll` is what will eventually be made default (and is what is currently set by `#![feature(nll)]`. Since the first error goes away when adding `-Z nll`, I think it should be considered 'fixed'.

`unresolved type in dtorck` occurs with all flags, however, so it's definitely a bug.

**Comment by SimonSapin** [comment] 2018-02-16 01:34
Doesn’t NLL imply MIR borrow-checking?

Isn’t `-Znll` the same as `feature(nll)`? (Except that `RUSTFLAGS` applies to dependencies too.)

I’m not sure what you mean by "two sets of flags". The two full, independent commands I run in the serde repo are:

* `RUSTFLAGS=-Zborrowck=mir cargo build`
* `RUSTFLAGS=-Znll cargo build --all-features`

**Comment by Aaron1011** [comment] 2018-02-16 22:06
@SimonSapin: `#![feature(nll)]` and `-Z nll` are two different things. `#![feature(nll)]` is equivalent to `-Z borrowck=mir -Z nll -Z two-phase-borrows`. Using `-Z nll` implies `-Z borrowck=mir`, but not `-Z two-phase-borrows`.

For more details, see the code that handles it: https://github.com/rust-lang/rust/blob/29c8276cee4a0eab7e0634ff25c6b47bd9f87c6c/src/librustc/session/mod.rs#L448-L488
as well as this comment: https://github.com/rust-lang/rust/issues/48070#issuecomment-364160628

**Comment by Aaron1011** [comment] 2018-02-16 22:21
I'd like to work on this.

**Comment by SimonSapin** [comment] 2018-02-17 00:38
@Aaron1011 Good to know, thanks. If I only test one set of flags, which one should that be?

**Comment by Aaron1011** [comment] 2018-02-17 00:52
I suspect that it should be all of them: `-Z borrowck=mir -Z nll -Z two-phase-borrows`.

@nikomatsakis: Can you confirm this?

**Comment by Aaron1011** [comment] 2018-02-17 21:55
Here's an initial minimization (can probably be improved on):

```rust
pub struct Container<T: Iterator> {
    value: Option<T::Item>,
}

impl<T: Iterator> Container<T> {
    pub fn new(iter: T) -> Self {
        panic!()
    }
}


pub struct Wrapper<'a> {
    content: &'a Content,
}

impl<'a, 'de> Wrapper<'a> {
    pub fn new(content: &'a Content) -> Self {
        Wrapper {
            content: content,
        }
    }
}


pub struct Content;

fn crash_it(content: Content) {
    let items = vec![content];
    let map = items.iter().map(|ref o| Wrapper::new(o));

    let mut map_visitor = Container::new(map);

}

fn main() {}
```

**Comment by Aaron1011** [comment] 2018-02-19 01:57
Looking at this further, this issue seems to be similar to the problem in https://github.com/rust-lang/rust/pull/47920.

With NLL, [TypeChecker#fully_perform_op](https://github.com/rust-lang/rust/blob/27a046e9338fb0455c33b13e8fe28da78212dedc/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L669) is used to wrap many inference-related operations, including projection normalization. However, `fully_perform_op` clears out any generated lifetime constraints from the infcx when it returns. This prevents the projection cache from working properly, since a fresh set of inference variables will be generated every time a given projection is normalized.

Here's how I believe this causes the current issue:

Both `ast-borrowck` and NLL call `dtorck_constraint_for_ty` in a loop - normalizing the returned types, and feeding them back to `dtorck_constraint_for_ty`. `ast-borrowck` ends up storing an inference variable in the projection cache, which at some point is equated to the proper type (here, `Wrapper`).

With NLL, the projection cache is unable to work properly, since inference variables will never be properly re-used. Every time a particular projection is resolved, a new inference variable will be generated, which will never be equated with the proper type. This means that `add_drop_live_constraint` has no choice but to pass an inference variable to `dtorck_constraint_for_ty`, 

I'm not sure how best to resolve this - from what I understand, clearing out the constraints from the infcx (at some point in time) is important to the correctness of the implementation of NLL. One idea I have is to apply the 'type freshener' used for the selection cache to the projection cache - but only when using NLL. However, I'm not certain if this would be sound.

**Comment by nikomatsakis** [comment] 2018-02-19 15:36
@Aaron1011 I'll take a look. I've got a PR that is making some progress towards refactoring how the `dtorck_constraint_for_ty` works.

**Comment by SimonSapin** [comment] 2018-02-19 19:02
This might be the same as https://github.com/rust-lang/rust/issues/48132?

**Comment by Aaron1011** [comment] 2018-02-19 20:18
@SimonSapin: I think it is - @FraGag's explanation of their repro is almost identical to mine.

**Comment by nikomatsakis** [comment] 2018-02-27 21:31
This works with https://github.com/rust-lang/rust/pull/48411

**Comment by SimonSapin** [comment] 2018-02-27 21:54
@nikomatsakis That seems to contradict what you wrote there:

> this entire branch ought to be a "pure refactoring", I believe, not changing anything about external behavior

**Comment by nikomatsakis** [comment] 2018-02-28 16:56
@SimonSapin true. That was realy meant to apply to code that does not have NLL enabled. With NLL, it fixes (obviously) some bugs.

**Closed** 2018-03-13 18:21 UTC
Labels: A-NLL, C-bug, WG-compiler-nll
