### ISSUE TITLE
GAT cannot infer implicit lifetime bounds.

### ISSUE THREAD

**Issue by oxalica** [rust-lang/rust#62265] opened 2019-07-01 09:27 UTC
I'm trying to simulate closures returning mutable captured variable with GAT-version `FnMut`.

It cannot infer implicit bound `'a: 'r` here and emit an error. But there is `self: &'r mut Self` alive while `Self` contains `&'a mut i32`.

```rust
#![feature(generic_associated_types)]

trait MyFnMut<Arg> {
    type Output<'a>;
    fn call_mut(&mut self, arg: Arg) -> Self::Output;
}

struct Closure1<'a>(&'a mut i32);

impl<'a> MyFnMut<()> for Closure1<'a> {
    type Output<'r> = &'r mut i32;
    fn call_mut(&mut self, _: ()) -> Self::Output {
        self.0 // error
    }
}
```

The same type signature without GAT works well:
```rust
// This works
impl<'a> Closure1<'a> {
    fn call_mut(&mut self, _: ()) -> &mut i32 {
        self.0
    }
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=76e50c3e75c37f932c57f6a00e3b0613)

BTW: Returning `unimplemented!()` in `call_mut` (the first one) will cause an ICE. Don't know if it is expected.

**Comment by hellow554** [comment] 2019-07-01 12:40
> BTW: Returning unimplemented!() in call_mut (the first one) will cause an ICE. Don't know if it is expected.

an **ICE** is never expected. If you haven't, please search for similar issues and then if none is applicable, open an issue and report the ICE (with a small example).

**Comment by csmoe** [comment] 2019-07-01 13:54
Duplicate of https://github.com/rust-lang/rust/issues/56445#issuecomment-502041778
cc @pnkfelix

**Comment by JohnTitor** [comment] 2019-10-04 16:02
Cannot see the ICE with the above playground link.

**Closed** 2019-10-04 16:36 UTC
Labels: A-NLL, A-associated-items, A-lifetimes, C-bug, F-generic_associated_types, I-ICE, T-compiler, requires-nightly
