### ISSUE TITLE
rustc allows crates compiled against different versions of a parent crate to be linked

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30709] opened 2016-01-04 23:12 UTC
I'm not sure if this is intentional, but it's certainly problematic. If you have four crates A, B, C, D with the following dependency tree:

```
        +---+
        | A |
        +---+
       /  |  \
      /   |   \
   +---+  |    |
   | B |  |    |
   +---+  |    |
        \ |    |
         \|    |
        +---+  |
        | C |  |
        +---+  |
             \ |
              \|
             +---+
             | D |
             +---|
```

then rustc allows B, which was compiled against an older version of A, to be linked with C and D, which were compiled against a newer version of A.

**Comment by huonw** [comment] 2016-01-04 23:55
Being able to link multiple versions of a crate into a single binary is by design (e.g. the hashes in symbol names are for this purpose). They're treated as completely different crates.

I.e. the graph looks more like

```
A-old  
  |    
  B  A-new
   \ / |
    C  |
     \ |
       D
```
It is definitely an issue if a value of a type defined in `A`-new is used in as type defined in `A`-old, but I suspect this isn't happening?

**Comment by huonw** [comment] 2016-01-05 00:05
(I suppose it's also an issue if the linking step uses `A`-new only, i.e. substituting that binary library for the `A`-old one, but this would almost surely fail with link errors due to the symbol naming I mentioned above.)

**Comment by mahkoh** [comment] 2016-01-05 00:49
>I.e. the graph looks more like

The thing is that A-old doesn't exist anymore. It has been overwritten with A-new. Is this still by design?

**Comment by retep998** [comment] 2016-01-05 01:25
If A-old doesn't exist anymore then you'll get linking errors due to references to A-old that aren't in A-new.

**Comment by mahkoh** [comment] 2016-01-05 01:32
There was no error from rustc. The only error came at a later stage from ld. Maybe if A-new and A-old are completely identical, except that A-new was compiled later, it doesn't produce an error?

**Comment by huonw** [comment] 2016-01-05 01:34
Isn't this a problem with whatever build process you're using (e.g. maybe it's a cargo bug?)? Rustc doesn't ever automatically build a crate, so there must've been an opt-in to building `A` again on the part of you or some tool.

**Comment by mahkoh** [comment] 2016-01-05 01:39
The error was that the B reference in C wasn't behind a #[cfg]. This has been fixed now, however, before it was fixed it caused the ld error mentioned above. I rebuilt everything (but not B because the build system was working correctly) multiple times because I didn't realize that there was a missing #[cfg] and because I expected a rebuild of A to cause an error when linking B so I excluded the possibility of B being linked as the error source.

**Comment by huonw** [comment] 2016-01-05 02:01
Oh, ok, so it sounds like the problem is specifically modifying the file B is expecting to link against, and the compiler not detecting this. However... I can't seem to reproduce an issue, I get a diagnostic from rustc pointing to the exact problem. Maybe you could try to create an example?

```rust
// A.rs
#![crate_type = "lib"]

pub fn foo() {
    // println!("hi");
}
```
```rust
// B.rs
#![crate_type = "lib"]
extern crate A;

pub fn bar() {
    A::foo()
}
```

```rust
// C.rs
#![crate_type = "lib"]
extern crate A;
extern crate B;

pub fn baz() {
    B::bar();
}
```
```rust
// D.rs
extern crate A;
extern crate C;

fn main() {
    A::foo();
    C::baz();
}
```

```text
$ rustc A.rs
$ rustc B.rs -L .
$ rustc C.rs -L .
$ rustc D.rs -L .
$ ./D # runs fine
$ $EDITOR A.rs # uncomment `println!`
$ rustc A.rs
$ rustc C.rs -L .
C.rs:2:1: 2:16 error: found possibly newer version of crate `A` which `B` depends on [E0460]
C.rs:2 extern crate B;
       ^~~~~~~~~~~~~~~
C.rs:2:1: 2:16 note: perhaps this crate needs to be recompiled?
C.rs:2 extern crate B;
       ^~~~~~~~~~~~~~~
C.rs:2:1: 2:16 note: crate `A` path #1: /home/huon/tmp/libA.rlib
C.rs:2:1: 2:16 note: crate `B` path #1: /home/huon/tmp/libB.rlib
error: aborting due to previous error
```

**Comment by mahkoh** [comment] 2016-01-05 02:16
You're modifying A. In my case A was not modified. It was merely recompiled.

**Comment by mahkoh** [comment] 2016-01-05 02:19
Actually A was compiled with different --cfg flags but they are not used in A itself.

**Comment by mahkoh** [comment] 2016-01-05 02:25
```rust
///////
// A.rs
///////

#![crate_type = "lib"]

pub trait A { }

///////
// B.rs
///////

#![crate_type = "lib"]

extern crate A;

pub struct X;

impl A::A for X { }

#[link_name = "xyz"]
extern { }

///////
// C_wrong.rs
///////

#![crate_type = "lib"]

extern crate A;
extern crate B;

///////
// C_fixed.rs
///////

#![crate_type = "lib"]

extern crate A;
#![cfg(b)] extern crate B;
```

If --cfg b is not passed, then the build system compiled A.rs and C.rs. Otherwise it also compiles B.rs. If --cfg b is not passed, then I'd expect C_wrong.rs to not compile because B.rs is outdated. The ld error comes from the extern block.

**Comment by huonw** [comment] 2016-01-05 03:29
You need to give more information. The following sequence of commands runs fine for me (with both 1.5.0 and nightly), but I'm just guessing what invocations you used.

```
rustc A.rs --cfg b 
rustc B.rs -L . --cfg b
rustc C_wrong.rs -L . --cfg b
rustc A.rs
rustc C_wrong.rs -L .
```

**Comment by mahkoh** [comment] 2016-01-05 11:09
Runs fine is the problem. Like I said: "I'd expect C_wrong.rs to not compile because B.rs is outdated. "

**Comment by huonw** [comment] 2016-01-05 12:22
Oh, sorry, I didn't parse the "I'd expect" properly.

In any case, B is not outdated? The A library didn't change at all (as you said, the `--cfg` flags aren't used), so the new or old version are the same. If the A library changes in some way, the error I demonstrated above will be emitted.

> Runs fine is the problem

Well... I'm still missing something, because what error is "The ld error comes from the extern block." talking about? As I said above, we need more info (e.g. an example that actually shows these errors) about:

> but it's certainly problematic

So far everything seems to be work exactly as expected/designed.

**Comment by mahkoh** [comment] 2016-01-05 14:59
>In any case, B is not outdated? The A library didn't change at all (as you said, the --cfg flags aren't used), so the new or old version are the same.

I already asked if this was the behavior in https://github.com/rust-lang/rust/issues/30709#issuecomment-168864016. This definition of "outdated" which is based on the contents of the file and not on the build time isn't clear from the error message. "found possibly newer version of crate" suggests that once a newer version of `A` has been compiled, `B` becomes incompatible. But given what you've just said, one can just undo the changes to `A`, recompile `A`, and suddenly `B` is compatible again. The error doesn't seem to have anything to do with "newer" and "older" but to be based on some undocumented requirements.

Maybe changing the error massage to say "found incompatible version of crate" is good enough to avoid this confusion.

**Comment by mahkoh** [comment] 2016-01-05 15:01
>What error is "The ld error comes from the extern block."?

B conditionally links to an extern library based on cfg flags. Since B was not recompiled with the correct flags but still linked, ld complained that it couldn't find said extern library.

**Comment by steveklabnik** [comment] 2020-02-08 18:29
Triage: given no comments by others since 2016, and the very specific details needed to trigger this, and so much changing over the last years, I'm going to close this one.

**Closed by steveklabnik** 2020-02-08 18:29 UTC
Labels: A-linkage, C-bug
