### ISSUE TITLE
Duplicate entries in trait std::clone::Clone implementors

### ISSUE THREAD

**Issue by WiSaGaN** [rust-lang/rust#31431] opened 2016-02-05 14:14 UTC
In [std::clone::Clone](http://doc.rust-lang.org/nightly/std/clone/trait.Clone.html),
we see there are duplicate entries,
`impl<T> Clone for Box<T> where T: Clone`
`impl<T: Clone> Clone for Box<T>`
`impl<T> Clone for Box<T> where T: Clone`
@bluss suggested

> probably something related to the multiple crate structure of std

Not sure if this is related to #26384, but it's still in nightly doc.

**Comment by jonas-schievink** [comment] 2016-02-08 19:49
Duplicate of #25061?

**Comment by steveklabnik** [comment] 2016-02-08 21:15
yes, it would seem so.

**Closed by steveklabnik** 2016-02-08 21:15 UTC
Labels: A-rustdoc
