### ISSUE TITLE
Servo compilation fails with multiple codegen units enabled

### ISSUE THREAD

**Issue by bholley** [rust-lang/rust#38938] opened 2017-01-09 03:11 UTC
STR (on linux64):
(1) Clone git@github.com:servo/servo.git
(2) Check out revision 183c4772e7b93bd6cd9b48a729a043421eb6bc65
(3) export RUSTFLAGS=-Ccodegen-units=16 (I'm on a 16-cpu linux machine, presumably the bug reproduces with other numbers of codegen units)
(4) ./mach build -d

On my machine, this produces the link error in https://github.com/servo/servo/issues/14916

Clearing the env var makes the build succeed.

CC @Manishearth

**Comment by Manishearth** [comment] 2017-01-09 03:15
In particular, it's interesting that it's trying to link to `<Root<T>>::downcast()`, which is a generic function and should never find its way to the linker without being monomorphized.

**Comment by est31** [comment] 2017-01-09 03:19
This looks quite similar to #38254

**Comment by Manishearth** [comment] 2017-01-09 04:34
cc @nikomatsakis

**Comment by michaelwoerister** [comment] 2017-01-09 14:14
PR https://github.com/rust-lang/rust/pull/38822 (which has landed only recently) might help here.

**Comment by SimonSapin** [comment] 2017-01-12 22:48
I could reproduce this issue with rustc 6f1ae663e 2017-01-06, but not in 2782e8f8f 2017-01-12. So I think this is fixed, possibly by #38822.

**Comment by Mark-Simulacrum** [comment] 2017-05-19 15:56
Closing since it wasn't reproducible a while back (see above comment).

**Closed by Mark-Simulacrum** 2017-05-19 15:56 UTC
Labels: A-codegen, I-ICE
