### ISSUE TITLE
"type annotations required: cannot resolve <_ as futures::IntoFuture>::Future == _" depending on presence of irrelevant captured variable

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/rust#41491] opened 2017-04-24 02:32 UTC
````
extern crate futures;
use futures::*;
use futures::future::*;
pub fn blah() {
    let c = || {
        let v = 9;
        let s = futures::stream::empty::<i32, ()>()
            .map(move |_: i32| -> Box<Future<Item = i32, Error = ()>> {
                ok(v).boxed()
            });
        s.buffered(1)
    };
}
````
produces
````
error[E0284]: type annotations required: cannot resolve `<_ as futures::IntoFuture>::Future == _`
````
The error report selects the entire closure `c`, which is not very useful.

The error seems to be induced by the use of `buffered`, since if you remove that the error goes away. It appears the compiler can't figure out the type of the future returned by the inner closure ... which seems like a bug since it's given explicitly.

What's weird is that if you remove the use of `v`, e.g. by replacing it with `9`, then the code compiles OK. In fact the presence of any captured variable in the inner closure triggers the failure of type inference.

Writing `c`'s body inline in the function makes the problem go away.

**Comment by Mark-Simulacrum** [comment] 2017-06-22 01:53
I cannot reproduce today, closing. If you can still reproduce please let us know and we'll reopen.

**Closed by Mark-Simulacrum** 2017-06-22 01:53 UTC
Labels: A-inference
