### ISSUE TITLE
Crate timely 0.1.15 regressed

### ISSUE THREAD

**Issue by Zoxc** [rust-lang/rust#44146] opened 2017-08-29 05:26 UTC
It works on `rustc 1.19.0-nightly (cfb5debbc 2017-06-12)`, `rustc 1.19.0 (0ade33941 2017-07-17)`.

Broken on `rustc 1.20.0-beta.3 (dcf532bcd 2017-08-23)`, `rustc 1.21.0-nightly (e26688824 2017-08-27)`:
```
error: no rules expected the token `EventStreamLogger<OperatesEvent, File>`
   --> C:\Users\John\.cargo\registry\src\github.com-1ecc6299db9ec823\timely-0.1.15\src\logging.rs:160:35
    |
160 |               __thread_local_inner!($t, $init);
    |                                     ^^
...
164 | / thread_local!{
165 | |     /// Logs operator creation.
166 | |     pub static OPERATES: EventStreamLogger<OperatesEvent, File> = EventStreamLogger::new();
167 | |     /// Logs channel creation.
...   |
178 | |     pub static GUARDED_PROGRESS: EventStreamLogger<bool, File> = EventStreamLogger::new();
179 | | }
    | |_- in this macro invocation

error: Could not compile `timely`.
```

**Comment by sfackler** [comment] 2017-08-29 06:03
Duplicate of #43681

**Closed by sfackler** 2017-08-29 06:03 UTC
