### ISSUE TITLE
Document associated type bound in the book

### ISSUE THREAD

**Issue by KalitaAlexey** [rust-lang/rust#39209] opened 2017-01-20 19:40 UTC
Created because of [the thread on Reddit](https://www.reddit.com/r/rust/comments/5p5t2k/im_having_a_problem_with_expressing_signature_of/).

The book doesn't mention that something generic can have a bound to a associated type bound.

For case like:
```rust
fn foo<I>(iter: I)
    where I: Iterator<Item=u32>
{
}
```

**Comment by steveklabnik** [comment] 2017-01-22 18:25
This is a duplicate of https://github.com/rust-lang/rust/issues/39217, or rather, it's a duplicate of this issue; as I said over there:

> I would happily accept a PR for this, but we're not updating the current book, since we're working on the second one. As such, I'm going to give this a close, but if you or anyone else wants to make this change, please go ahead and send a PR in! Thank you!

**Closed by steveklabnik** 2017-01-22 18:25 UTC
