### ISSUE TITLE
rustdoc renders re-exported types' field types differently from their definitions

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#89712] opened 2021-10-09 19:54 UTC
For example, with `MatchExpressionArmCause`. Note `Vec<Span>` in the definition vs `Vec<Span, Global>` in the re-export, and `Ty<'tcx>` in the definition vs `&'tcx TyS<'tcx>` in the re-export.

### Definition

![image](https://user-images.githubusercontent.com/37223377/136672160-d87181ca-34c6-4259-bb9b-03674c101760.png)

### Re-export

![image](https://user-images.githubusercontent.com/37223377/136672165-451af028-9224-45be-9c5b-0e996caed942.png)

-----

#### Note

I'm labeling this as `A-cross-crate-reexports`, but it may happen with intra-crate re-exports too.

**Comment by jyn514** [comment] 2021-10-10 01:29
Duplicate of https://github.com/rust-lang/rust/issues/80379

**Closed by jyn514** 2021-10-10 01:29 UTC
Labels: T-rustdoc, C-bug, I-prioritize, A-cross-crate-reexports
