### ISSUE TITLE
Compiler crash related to static variables, pointers and const functions

### ISSUE THREAD

**Issue by Nakrez** [rust-lang/rust#29251] opened 2015-10-23 15:30 UTC
I managed to make the rustc compiler crash using this code: http://is.gd/ZecY5i
It is not directly related to const functions, but they allow this code to be valid.

It was on a nightly build : rustc 1.5.0-nightly (20a6938c0 2015-10-16)

**Comment by jonas-schievink** [comment] 2015-10-23 15:50
Minified version (http://is.gd/cSuM1u):

```rust
#![feature(const_fn)]

const fn f(t: *const u8) {}

extern {
    static A: *const u8;
}

static B: () = f(*&A);

fn main() {}
```

```
Segmentation fault (core dumped)
playpen: application terminated with error code 139
```

**Comment by arielb1** [comment] 2015-10-23 17:35
duplicate of #28324.

**Closed by arielb1** 2015-10-23 17:35 UTC
