### ISSUE TITLE
Inconsistency between primitive type and user-defined type in Vec AddAsign

### ISSUE THREAD

**Issue by tamuhey** [rust-lang/rust#72257] opened 2020-05-16 06:13 UTC
From [this stackoverflow question](https://stackoverflow.com/questions/61732690/why-is-it-allowed-to-have-both-immutable-and-mutable-borrows-of-a-vector-of-nume).

`a` is a `Vec<i32>` which can be mutably and immutably referenced in one expression:

```rust
fn main() {
    let mut a = vec![0, 1];
    a[0] += a[1]; // OK
}
```

I thought this compiled because `i32` implements `Copy`, so I created another type that implements `Copy` and compiled it like the first example, but it fails:

```rust
use std::ops::AddAssign;

#[derive(Clone, Copy, PartialEq, Debug, Default)]
struct MyNum(i32);

impl AddAssign for MyNum {
    fn add_assign(&mut self, rhs: MyNum) {
        *self = MyNum(self.0 + rhs.0)
    }
}

fn main() {
    let mut b = vec![MyNum(0), MyNum(1)];
    b[0] += b[1];
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d8ad987a94f1c70092fb8b45e536152d)

```none
error[E0502]: cannot borrow `b` as immutable because it is also borrowed as mutable
  --> src/main.rs:14:13
   |
14 |     b[0] += b[1];
   |     --------^---
   |     |       |
   |     |       immutable borrow occurs here
   |     mutable borrow occurs here
   |     mutable borrow later used here
```

According to the answer in [this stackoverflow question](https://stackoverflow.com/questions/61732690/why-is-it-allowed-to-have-both-immutable-and-mutable-borrows-of-a-vector-of-nume), this inconsistency is caused by compiler optimization.

I think this behavior should be fully controlled by Trait. What do you think?

**Comment by DutchGhost** [comment] 2020-05-16 14:35
Dupe of https://github.com/rust-lang/rust/issues/72199

**Closed** 2020-05-16 15:01 UTC
