### ISSUE TITLE
Consider adding notifications of progress

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#16343] opened 2014-08-08 04:04 UTC
For example, when compiling a larger crate (say, librustc): you get:

```
$ rustc foo.rs
```

and you wait... you're not entirely sure if your compilation is going to succeed or fail. You sweat with the tension, wanting to alt-tab over to reddit but not certain if you have an impending error to fix.

We could print out a helpful message before trans that this crate is going to compile, possibly in the same situations we emit color. It's a bit non-traditional for a compiler to print anything in the case of success, though.

**Comment by steveklabnik** [comment] 2015-04-30 21:01
Triage: no change.

**Comment by pnkfelix** [comment] 2015-04-30 22:54
this is a dupe of ~~#22227~~ #24335, right?

(normally we resolve dupes by letting the one with lower issue number take precedence, but in this case I suspect it would be best to close this Issue in favor of #24335, which has a lot of concrete ideas in its proposal.)

**Comment by steveklabnik** [comment] 2015-05-01 15:54
Agreed, for sure.

**Closed by steveklabnik** 2015-05-01 15:54 UTC
Labels: A-driver, I-papercut
