### ISSUE TITLE
Documentation for flush() function of Write trait is incorrect

### ISSUE THREAD

**Issue by qdot** [rust-lang/rust#34999] opened 2016-07-23 20:25 UTC
The flush() function to the write trait is documented (at https://doc.rust-lang.org/std/io/trait.Write.html) as

``` Rust
fn flush(&mut self) -> Result<()>
```

However this results in the following error in code:

```
error: wrong number of type arguments: expected 2, found 1 [E0243]
```

The return value is expected to be Result<(), std::io::Error>.

**Comment by jonas-schievink** [comment] 2016-07-23 20:28
That's a `std::io::Result<()>`, not `std::result::Result<(), ?>`

**Comment by retep998** [comment] 2016-07-23 21:21
If you click on the `Result` it will take you to the page for `std::io::Result`  where you will see that it is defined as `type Result<T> = Result<T, Error>;`. Therefore not a bug, although it is confusing.

**Comment by frewsxcv** [comment] 2016-07-23 21:36
If we changed the function signature in the source from:

```rust
fn write(&mut self, buf: &[u8]) -> Result<usize>;
```

to:

```rust
fn write(&mut self, buf: &[u8]) -> io::Result<usize>;
```

would it display the `io::` prefix in the documentation? In my opinion, I think it would make sense to do this if so.

**Comment by frewsxcv** [comment] 2016-07-24 03:47
```rust
fn write(&mut self, buf: &[u8]) -> io::Result<usize>;
```

I'm actually not sure if this is even possible since this line comes straight from `libstd/io/mod.rs`.

**Comment by sfackler** [comment] 2016-07-24 04:24
rustdoc does not pay attention to the way items are declared in that way.

**Comment by steveklabnik** [comment] 2020-03-28 18:11
Triage: no changes here. Not entirely sure this should be fixed, but it's up to the rustdoc team.

**Comment by GuillaumeGomez** [comment] 2020-04-26 17:50
#42066 is more global so let's close this one.

**Closed by GuillaumeGomez** 2020-04-26 17:50 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
