### ISSUE TITLE
Calling std::mem::size_of::<T> in a generic constexpr context errors.

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust#45598] opened 2017-10-28 18:12 UTC
This code fails to build right now, while it should succeed (as `std::mem::size_of::<T>` is `const`):

```rust
use std::mem;
use std::marker::PhantomData;
struct U<T>([u8; mem::size_of::<T>()], PhantomData<T>);
fn main() {}
```

**Comment by mystor** [comment] 2017-10-28 18:14
```
   Compiling playground v0.0.1 (file:///playground)
error[E0277]: the trait bound `T: std::marker::Sized` is not satisfied
 --> src/main.rs:3:18
  |
3 | struct U<T>([u8; mem::size_of::<T>()], PhantomData<T>);
  |                  ^^^^^^^^^^^^^^^^^ `T` does not have a constant size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `T`
  = help: consider adding a `where T: std::marker::Sized` bound
  = note: required by `std::mem::size_of`

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Comment by frewsxcv** [comment] 2017-10-28 18:19
Duplicate of https://github.com/rust-lang/rust/issues/43408?

**Closed** 2017-10-28 18:25 UTC
Labels: A-const-fn, I-compiletime
