### ISSUE TITLE
Impl specialization behaves inconsistently when combined with lifetimes.

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust#65950] opened 2019-10-30 00:44 UTC
Hi, consider this code:

```rust
#![feature(specialization)]

enum Str {
    Owned(String),
    Borrowed(&'static str)
}

trait ToStr {
    fn to_str(self) -> Str;
}

impl<T: AsRef<str>> ToStr for T {
    default fn to_str(self) -> Str { 
        Str::Owned(self.as_ref().to_string()) 
    }
}

impl ToStr for &'static str {
    fn to_str(self) -> Str { 
        Str::Borrowed(self) 
    }
}
```

Then this compiles fine:
```rust
fn main() {
    let a = "foo".to_string();
    let b = &a;
    let c = b.to_str();
}
```

But this does not:
```rust
fn main() {
    let a = "foo".to_string();
    let b: &str = &a;
    let c = b.to_str();
}
```

Neither this one:
```rust
fn main() {
    let a = "foo".to_string();
    let b = a.as_str();
    let c = b.to_str();
}
```

Playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=02445624f226d0d95d52c521370f6555

Thank you, Globi::<!>, for help tracking it down!

**Comment by wdanilo** [comment] 2019-10-30 01:57
Actually the issue is invalid. As pointed out on Discord, the type inferred in the first case is `&String`, not `&str`, so other impl gets picked than I initially thought. Anyway, I understand that we will not be able to specialize functions based on lifetimes in Rust? (Separate impl for `'static` and "non-static`)

**Comment by pnkfelix** [comment] 2019-10-30 10:21
> Anyway, I understand that we will not be able to specialize functions based on lifetimes in Rust? (Separate impl for `'static` and "non-static`)
> 
> If making it impossible is done by design, we can close this issue. If not, then we currently cannot express that.

My understanding is that we do not want, by design, to be able to specialize functions based on lifetimes.

Closing.

**Closed by pnkfelix** 2019-10-30 10:21 UTC
