### ISSUE TITLE
Fat pointers with same data part, but different vtables

### ISSUE THREAD

**Issue by rom1v** [rust-lang/rust#48795] opened 2018-03-06 23:12 UTC
I did not manage to reproduce in a minimal sample, but in my application, I ended up with:

    let x = …;
    let y = …;
    println!("{:p} == {:p} ? {}", x, y, ptr::eq(x, y));

printing:

    0x7f87a8c3a618 == 0x7f87a8c3a618 ? false

After investigations (and discussion on freenode/##rust), it appeared that `x` and `y` were fat pointers having the same data part (the 64 first bits), but a different vtable (the last 64 bits).

I applied this patch to my application, which solves the reported issue: https://github.com/Genymobile/gnirehtet/commit/c36fa4d1a1086aa03e56aabae12669f8b1a1a1c4

But I can't understand how two fat pointers for the same objects may have different vtables. Is it expected?

**Comment by sfackler** [comment] 2018-03-06 23:57
We don't guarantee that vtables are unique. For example, a separate copy could be generated in multiple codegen units, or multiple crates.

**Comment by rom1v** [comment] 2018-03-07 06:01
OK.

In that case, shouldn't `ptr::eq()` ignore the vtable part?

**Comment by rom1v** [comment] 2018-03-07 10:15
This also affects [slices](https://github.com/rust-lang/rust/pull/48814#issuecomment-371085916):

```rust
use std::ptr;
fn main() {
    let array = [1, 2, 3, 4];
    let slice1 = &array[0..1];
    let slice2 = &array[0..3];
    println!("{:p} == {:p} ? {}", slice1, slice2, ptr::eq(slice1, slice2));
}
```

    0x7fff0a6595b8 == 0x7fff0a6595b8 ? false

**Comment by rom1v** [comment] 2018-05-29 19:07
In fact, comparing the data part only would be unsound in some cases:

```rust
struct X {}
impl SomeTrait for X { ... }

struct Y { x: X }
impl SomeTrait for Y { ... }

let y = Y { x: X {} }

let a = &y as *const SomeTrait;
let b = &y.x as *const SomeTrait;

println!("{:?} == {:?} : {}", a, b, a == b);
```

(from [here](https://www.reddit.com/r/rust/comments/8mtp7j/exploring_rust_fat_pointers/dzrr2eb/))

Here, `a` and `b` have the same data part, but they should not be equal. The current behavior is correct:

    0x7ffe1131c0e0 == 0x7ffe1131c0e0 : false

**Comment by njaard** [comment] 2018-12-27 19:17
I'm being bit by this problem also. It's causing `ptr::eq` to fail which is breaking my program.

**Comment by RalfJung** [comment] 2020-03-07 08:13
Closing as duplicate of https://github.com/rust-lang/rust/issues/46139.

**Closed by RalfJung** 2020-03-07 08:13 UTC
Labels: A-codegen, A-traits, C-enhancement, T-compiler
