### ISSUE TITLE
Windows build instructions fetch gcc 5.x, resulting in segfault during build

### ISSUE THREAD

**Issue by SingingTree** [rust-lang/rust#29202] opened 2015-10-21 08:33 UTC
I believe the Windows build instructions will currently lead to a segfault as outlined in these issues: #28260 #28445 #28962. Previously when running `pacman -S mingw-w64-i686-toolchain` or `pacman -S mingw-w64-x86_64-toolchain` MSYS2's pacman would fetch a 4.x version of gcc. However, the packages have been bumped, now giving gcc 5.2. This results in the issues outlined above.

This can be worked around by using MSYS2 but obtaining an alternative version of gcc. I've had success using MSYS2 but putting gcc 4.9 from [mingw-w64](http://mingw-w64.org/doku.php) on the path.

I imagine it may be possible to remedy this by passing different args when using gcc 5.2, but have not experimented with this. I'd be interested in if anyone has had any success with this method.

Should the Windows build instructions be updated to reflect a work around for the above issues? I'd be happy to do so, but would like to have some discussion about the best direction to go with this.

This is a possible dupe of #28843, but I believe it is a separate issue.

**Comment by NobbZ** [comment] 2015-10-21 10:24
I'd prefer if the build process could distinguish between older and newer versions of `gcc`, but I could live with installing an older version of `gcc` until the build process has catched up and builds with current version of `gcc`.

Still I do think, that this should be mentioned in the README, so that noone wastes his time by hunting bugs on his system where actually is none (as I did the last 4 hours).

**Comment by alexcrichton** [comment] 2015-10-21 16:24
Yeah for now I'm going to close this as a dupe of https://github.com/rust-lang/rust/issues/28260, but I'd be totally fine updating the build instructions temporarily, so feel free to send a PR!

**Closed by alexcrichton** 2015-10-21 16:24 UTC
