### ISSUE TITLE
ICE: `rustc --print crate-name` on WSL2

### ISSUE THREAD

**Issue by tedbyron** [rust-lang/rust#109828] opened 2023-04-01 07:18 UTC
Getting this ICE on WSL2 in any rust repo I open
OS: Debian
kernel: 5.15.90.1-microsoft-standard-WSL2

### Code

```shell
# (shell)
rustc --print crate-name
```

### Meta

`rustc --version --verbose`:
```
└ $ rustc -vV
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: x86_64-unknown-linux-gnu
release: 1.68.2
LLVM version: 15.0.6
```

### Error output

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_driver/src/lib.rs:627:44

### Backtrace
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   3: rustc_driver::print_crate_info
   4: rustc_span::with_source_map::<(), rustc_interface::interface::run_compiler<(), rustc_driver::run_compiler::{closure#0}>::{closure#0}::{closure#0}>
   5: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<(), rustc_driver::run_compiler::{closure#0}>::{closure#0},()>
```

**Comment by Nilstrieb** [comment] 2023-04-01 08:25
Duplicate of #107822, which was fixed on nightly.

**Closed by Nilstrieb** 2023-04-01 08:25 UTC
Labels: I-ICE, T-compiler, C-bug
