### ISSUE TITLE
Complier panic: "error: internal compiler error: this path should not cause illegal move"

### ISSUE THREAD

**Issue by drewcrawford** [rust-lang/rust#21712] opened 2015-01-28 02:31 UTC
I make no claims about whether or not the code below should compile.  But the compiler probably shouldn't panic.

```rust
use std::sync::mpsc::channel;
use std::io::timer::Timer;
use std::time::Duration;
use std::thread::Thread;
use std::sync::{Arc,Semaphore, SemaphoreGuard, TryLockResult};


pub struct SemaphoreTimeout {
    #[experimental]
    pub semaphore: Semaphore
}

impl SemaphoreTimeout {
    pub fn try_acquire(&self, duration: Duration) -> TryLockResult<SemaphoreGuard> {
        let (tx,rx) = channel::<()>();
        let mut timer = Timer::new().unwrap();
        let timeout = timer.oneshot(duration);
        let mut itemPtr : *mut Semaphore;
        unsafe {
            let itemPtr : *mut Semaphore = std::mem::transmute(self.semaphore);
        }
        let itemSendablePtr = std::ptr::Unique(itemPtr);

        let mut guard : Option<SemaphoreGuard> = None;
        let guardPtr : *mut Option<SemaphoreGuard> = &mut guard;
        let sendablePtr = std::ptr::Unique(guardPtr);
        Thread::spawn(move |:| {
            unsafe {
                let sema = *(itemSendablePtr.0);
                *(sendablePtr.0) = Some(sema.access());
            }
            tx.send(()).unwrap();
        });


        loop {
            select! {
                val = rx.recv() => {
                    return Ok(guard.unwrap());
                },
                _ = timeout.recv() => {
                    return Err(std::sync::TryLockError::WouldBlock);
                }
            }
        }

    }
}

#[test]
fn it_works() {
    let total_time = std::time::duration::Duration::span(|| {
            let sema = SemaphoreTimeout{ semaphore: Semaphore::new(0)};
            sema.try_acquire(Duration::seconds(10));
    }).num_seconds();
    assert!(total_time > 9);

}
```

```
$ RUST_BACKTRACE=1 rustc --crate-type rlib src/lib.rs
src/lib.rs:20:64: 20:68 error: cannot move out of borrowed content
src/lib.rs:20             let itemPtr : *mut Semaphore = std::mem::transmute(self.semaphore);
                                                                             ^~~~
src/lib.rs:30:41: 30:45 error: `sema` does not live long enough
src/lib.rs:30                 *(sendablePtr.0) = Some(sema.access());
                                                      ^~~~
note: reference must be valid for the static lifetime...
src/lib.rs:28:13: 31:14 note: ...but borrowed value is only valid for the block at 28:12
src/lib.rs:28             unsafe {
src/lib.rs:29                 let sema = *(itemSendablePtr.0);
src/lib.rs:30                 *(sendablePtr.0) = Some(sema.access());
src/lib.rs:31             }
src/lib.rs:29:28: 29:49 error: internal compiler error: this path should not cause illegal move
src/lib.rs:29                 let sema = *(itemSendablePtr.0);
                                         ^~~~~~~~~~~~~~~~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/drew/Code/rust/src/libsyntax/diagnostic.rs:130

stack backtrace:
   1:        0x111354dbc - sys::backtrace::write::h3b1687d123840745dbu
   2:        0x111378cef - failure::on_fail::h4f27fcb787f34dcb8aB
   3:        0x1112e2c0e - rt::unwind::begin_unwind_inner::h1d4bab16a9a9da184SA
   4:        0x110a83f8f - rt::unwind::begin_unwind::h4217311381055978755
   5:        0x110a83f24 - diagnostic::SpanHandler::span_bug::hd5501efc6390fb73vYE
   6:        0x10e3f5995 - session::Session::span_bug::h4a1e9356937820aeTxo
   7:        0x10e3720e4 - borrowck::build_borrowck_dataflow_data::hd89794399b269c02lPe
   8:        0x10e36d9b8 - borrowck::borrowck_fn::hf2a6eb5420fa3465IMe
   9:        0x10e36fee9 - visit::walk_expr::h2260093690797296160
  10:        0x10e36f96b - visit::walk_expr::h2260093690797296160
  11:        0x10e36e22d - borrowck::borrowck_fn::hf2a6eb5420fa3465IMe
  12:        0x10e370c28 - visit::walk_method_helper::h8676194234672418769
  13:        0x10e36eccc - borrowck::borrowck_item::h58249352ae407815GLe
  14:        0x10e36ee9f - borrowck::check_crate::h88841bf41bd69ee3yGe
  15:        0x10db0354a - driver::phase_3_run_analysis_passes::h875fa1a74376223cVFa
  16:        0x10dae84e6 - driver::compile_input::h2c7c782afbb2d5e3Bba
  17:        0x10dba7216 - run_compiler::h134233be72a5f033R8b
  18:        0x10dba4563 - thunk::F.Invoke<A, R>::invoke::h11706971136093431084
  19:        0x10dba33c8 - rt::unwind::try::try_fn::h10954395397093774028
  20:        0x1113f0d09 - rust_try_inner
  21:        0x1113f0cf6 - rust_try
  22:        0x10dba3a06 - thunk::F.Invoke<A, R>::invoke::h15388688857395276920
  23:        0x111364681 - sys::thread::thread_start::h75057efc72f2c7edr3w
  24:     0x7fff8d1e62fc - _pthread_body
  25:     0x7fff8d1e6279 - _pthread_body
```

```
 $ rustc --version
rustc 1.0.0-dev (d15192317 2015-01-25 16:09:48 +0000)
```

**Comment by japaric** [comment] 2015-01-28 02:40
Likely a duplicate of #20801

**Comment by pnkfelix** [comment] 2015-02-10 13:59
yes, duplicate of #20801.

**Closed by pnkfelix** 2015-02-10 13:59 UTC
Labels: I-ICE
