### ISSUE TITLE
rustbuild: x86_64-unknown-linux-musl is not installed.

### ISSUE THREAD

**Issue by fzgregor** [rust-lang/rust#39809] opened 2017-02-14 08:31 UTC
Hi,

I ran into some issues trying to build and install Rust with a customized musl c library. In short it seams the musl `std` crate is build during `make all` but not installed in the subsequent `make install`. Manually copying the rlibs from the build directory solves the issue and rustc is able to build for the `x86_64-unknown-linux-musl` target.

I wonder if that is an issue of the build system or me using it.

The longer story is on [stackoverflow](http://stackoverflow.com/questions/42192850/how-do-i-build-the-rust-standard-library-with-a-custom-musl).

My build environment is [here](https://github.com/fzgregor/docker-rust-musl).

**Comment by est31** [comment] 2017-02-14 09:01
The best tool to build std right now is xargo: https://github.com/japaric/xargo

In the future hopefully cargo will be std aware and can build std on demand.

**Comment by fzgregor** [comment] 2017-02-14 10:01
`xargo` look appealing. But I can't find to much documentation.

How would I go about using it with my customized musl library?

**Comment by alexcrichton** [comment] 2017-02-14 15:26
I believe this is a dupe of https://github.com/rust-lang/rust/issues/39235, but thanks for the report!

**Closed by alexcrichton** 2017-02-14 15:26 UTC
