### ISSUE TITLE
Rustup cannot update nightly 2018-12-05

### ISSUE THREAD

**Issue by norru** [rust-lang/rust#56774] opened 2018-12-13 12:40 UTC
```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-08, rust version 1.32.0-nightly (4a45578bc 2018-12-07)
error: some components unavailable for download: 'clippy', 'rls', 'rustfmt'
info: checking for self-updates

       stable-x86_64-unknown-linux-gnu unchanged - rustc 1.31.0 (abe02cefd 2018-12-04)
  nightly-x86_64-unknown-linux-gnu update failed - rustc 1.32.0-nightly (14997d56a 2018-12-05)
```

**Comment by jonas-schievink** [comment] 2018-12-13 12:51
Duplicate of https://github.com/rust-lang/rust/issues/56667

**Closed** 2018-12-13 13:11 UTC
