### ISSUE TITLE
ICE moving struct via unsafe deref

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#21220] opened 2015-01-16 03:43 UTC
`rustc 1.0.0-dev (00b112c45 2015-01-08 18:40:04 +0000)`
```rust
struct JSVal(u8);

fn main() {
    let mut jsval = JSVal(0);
    let p: *mut JSVal = &mut jsval;
    unsafe {
        let _v = *p;
    }
}
```
```
godot2:servo jdm$ ./mach rustc /tmp/badmove.rs
/tmp/badmove.rs:7:18: 7:20 error: internal compiler error: this path should not cause illegal move
/tmp/badmove.rs:7         let _v = *p;
                                   ^~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /Users/larsberg/rust/src/libsyntax/diagnostic.rs:123
```

**Comment by dignati** [comment] 2015-01-16 13:25
I think this is a duplicate of #20801

**Closed** 2015-01-16 15:17 UTC
Labels: I-ICE
