### ISSUE TITLE
azure: Investigate seemingly spurious failures on CI

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#61301] opened 2019-05-29 02:56 UTC
## Git checkout failures

* ~~[arm-android git checkout failure](https://dev.azure.com/rust-lang/rust/_build/results?buildId=298)~~
* ~~[armhf-gnu git checkout failure](https://dev.azure.com/rust-lang/rust/_build/results?buildId=298)~~
* ~~[dist-various-2 git checkout failure](https://dev.azure.com/rust-lang/rust/_build/results?buildId=298)~~
* ~~[even more git checkout failures](https://dev.azure.com/rust-lang/rust/_build/results?buildId=297)~~

## Submodule weirdness on Windows

* https://dev.azure.com/rust-lang/rust/_build/results?buildId=295
* https://dev.azure.com/rust-lang/rust/_build/results?buildId=287

## Other

* [OSX connection lost during a try build](https://dev.azure.com/rust-lang/rust/_build/results?buildId=333)
* [Build failed to start but marked as successful](https://dev.azure.com/rust-lang/rust/_build/results?buildId=345)

**Comment by pietroalbini** [comment] 2019-05-29 15:13
* [even more git checkout failures](https://dev.azure.com/rust-lang/rust/_build/results?buildId=297)

```
fatal: reference is not a tree: 3b109e51cc8d9a3a833cf7e28db7911a8a0aa503
##[warning]Git checkout failed on shallow repository, this might because of git fetch with depth '2' doesn't include the checkout commit '3b109e51cc8d9a3a833cf7e28db7911a8a0aa503'. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=829603)
##[error]Git checkout failed with exit code: 128
```

This doesn't seem to be a spurious failure: these jobs started after bors marked the PR as failed due to other failures on Travis/AppVeyor, so the `auto` branch was already force-pushed to the next PR. We shouldn't see these anymore once we start gating on Azure.

**Comment by pietroalbini** [comment] 2019-05-29 16:41
For the submodules weirdness I opened https://github.com/rust-lang/rust/pull/61322 to investigate.

For the git checkout failures ([logs](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/298/logs/128)) it seems the error is happening on the Azure side, and there is not much we can do on our end. Any idea on what could have caused it, or what steps we can take to investigate it @rylev @johnterickson?

**Comment by alexcrichton** [comment] 2019-05-31 14:16
[OSX connection lost during a try build](https://dev.azure.com/rust-lang/rust/_build/results?buildId=333)

**Comment by johnterickson** [comment] 2019-05-31 16:37
I see two trends - let me know if I'm missing another:

This looks like the auth to GitHub is not working and so git is falling back to a command prompt for creds.  Hmm...
```
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=2 origin
fatal: could not read Username for 'https://github.com': terminal prompts disabled
##[warning]Git fetch failed with exit code 128, back off 4.338 seconds before retry.
```

This sounds vaguely like a [race](https://twitter.com/youhanaNaseim/status/1134230335435235330) we were seeing where we are getting a notification from GitHub before the commit has been replicated everywhere.
```
fatal: reference is not a tree: 3b109e51cc8d9a3a833cf7e28db7911a8a0aa503
##[warning]Git checkout failed on shallow repository, this might because of git fetch with depth '2' doesn't include the checkout commit '3b109e51cc8d9a3a833cf7e28db7911a8a0aa503'. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=829603)
##[error]Git checkout failed with exit code: 128
```

**Comment by pietroalbini** [comment] 2019-05-31 17:22
> This sounds vaguely like a race we were seeing where we are getting a notification from GitHub before the commit has been replicated everywhere.

@johnterickson I'm pretty sure that's our fault and "expected behavior".

Every time a new build needs to start bors force-pushes the merge commit on the auto branch, thus deleting the previous build's merge commit. If the new build is started shortly after the previous one (for example if someone cancels the build on the bors side to let an higher priority one start) the checkout step of the previous one might have not started yet and it will try to get the old HEAD, causing that error.

I've also seen the error only on builds that ran for ~5 minutes before being killed by our cancelbot because a newer build started, confirming the hypothesis.

**Comment by pietroalbini** [comment] 2019-06-01 12:55
There is another spurious failure which is pretty bad: [this build failed to "prepare"](https://dev.azure.com/rust-lang/rust/_build/results?buildId=345) but was marked [as successful](https://github.com/rust-lang/rust/runs/139880730) on the GitHub Checks.

**Comment by johnterickson** [comment] 2019-06-03 05:16
@pietroalbini I raised that "succeeded but actually failed" build with the right team - definitely concerning and I appreciate you reporting it.

**Comment by alexcrichton** [comment] 2019-06-04 14:35
Another two that have come up:

* msvc-tools and gnu-tools on https://dev.azure.com/rust-lang/rust/_build/results?buildId=398  show:

```
+ /tmp/checktools.sh ../x.py /tmp/toolstates.json linux
fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

  @pietroalbini or @kennytm do y'all know what might be causing that?

* All of a sudden our script to enable ipv6 in docker is [failing](https://dev.azure.com/rust-lang/rust/_build/results?buildId=399). I don't know why this changed all of a sudden but it shouldn't be the hardest thing to work around (testing something on `try` now)

**Comment by kennytm** [comment] 2019-06-04 14:47
Maybe the HEAD commit did not have a parent commit? Is the commit 322afaf9384e6fecb84007287a48e5439b9ac80f associated to any branch?

**Comment by mati865** [comment] 2019-06-04 14:47
For IPv6 error `/etc/docker` seems to not exist.

**Comment by alexcrichton** [comment] 2019-06-04 14:56
Ah ok @kennytm that's probably it. It sounds like a specific git history is expected and/or fetch depth, but I'm just pushing up raw commits which probably breaks the script's assumption. For the failing builds I'm just making manual commits and pushing them to `try`. Seems like an expected failure.

**Comment by johnterickson** [comment] 2019-06-04 16:31
For what it's worth, I had "fixed" this in my original branch in that it would swallow this error.

**Comment by pietroalbini** [comment] 2019-06-11 16:07
@ethomson said on Discord the checkout issues are now fixed :tada: 	

> On a related note, GitHub has deployed some fixes that they think will mitigate your sporadic build failures.  Could you please @ ping me if you see another beginning today?
> Yes, GitHub thinks that they've resolved the issue, but if not, I think that we can add some logic on our side as well.

**Comment by ethomson** [comment] 2019-06-11 20:03
Thanks for linking me to this issue, @pietroalbini.  Looking at the topic, I'm looking at this section:

> Submodule weirdness on Windows
> https://dev.azure.com/rust-lang/rust/_build/results?buildId=295
> https://dev.azure.com/rust-lang/rust/_build/results?buildId=287

Naive question: what is the weirdness that you're describing?  It's not obvious from the logs, because I don't really know what I'm looking for.

**Comment by alexcrichton** [comment] 2019-06-11 20:11
Ah yeah sorry I should have been more descriptive there! On build 287 the x86_64-msvc-2 build fails the build due to an odd error message (presumably a submodule missing) and the logs for the "Check out submodules (windows)" step, while successful, are sort of funny. I'm not sure if this is really an Azure issue though, it may have been a case that we got a bad tarball from GitHub and swallowed the error by accident (this is what https://github.com/rust-lang/rust/pull/61322 was hoping to help diagnose).

The 295 build is similar except for just a different windows builder (dist-x86_64-msvc)

I haven't seen these happen again myself, though, so it may have been just a transient issue. AFAIK most issues we've listed here have been addressed one way or another, so it may actually be time to close this!

**Comment by pietroalbini** [comment] 2019-06-11 20:21
By the way, since I couldn't reproduce that failure locally I also added [some extra debug info](https://github.com/rust-lang/rust/pull/61322) to see what's actually happening there. Didn't get a chance to see the output when the spurious failure happens yet.

**Comment by pietroalbini** [comment] 2019-06-15 07:23
@ethomson fyi, [those "could not read Username" checkout failures happened again](https://dev.azure.com/rust-lang/rust/_build/results?buildId=790).

**Comment by ethomson** [comment] 2019-06-15 17:48
@pietroalbini :(  Thanks.  Let me see where the fix for that is in the deployment queue and if we expect that your account has it ...

**Comment by ethomson** [comment] 2019-06-17 12:36
@pietroalbini Update on 403's ("could not read Username") - that fix was still making its way through progressive deployment.  We explicitly enabled it on your account.  Please let me know if you see it again, as that means our fix wasn't actually a fix for the issue.

**Comment by steveklabnik** [comment] 2020-08-28 19:44
Triage: given that we're not longer using Azure pipelines, I imagine this issue can be closed. Anyone from @rust-lang/infra who can confirm?

**Comment by Mark-Simulacrum** [comment] 2020-08-28 19:51
Indeed! Closing.

We're still using macOS on Azure, but I don't think we've seen these failures there recently at least.

**Closed by Mark-Simulacrum** 2020-08-28 19:51 UTC
Labels: T-infra, azure-evaluation
