### ISSUE TITLE
Possible beta to nightly regression (from 

### ISSUE THREAD

**Issue by cpcloud** [rust-lang/rust#65022] opened 2019-10-02 21:03 UTC
Possible regression from beta-1.39 to nightly-1.40, exposed by [`tonic`](https://github.com/hyperium/tonic)

I tried this code (using the [rust nix overlay](https://github.com/mozilla/nixpkgs-mozilla/blob/master/rust-overlay.nix)):

```
$ cd tonic
$ nix-shell -p latest.rustChannels.nightly.rust rls cargo openssl pkg-config
$ cargo build
```

I expected to see this happen: a successful build

Instead, this happened: a build error

## Meta

`rustc --version --verbose`:

```
$ rustc --version --verbose                                                                      101 ↵
rustc 1.40.0-nightly (702b45e40 2019-10-01)
binary: rustc
commit-hash: 702b45e409495a41afcccbe87a251a692b0cefab
commit-date: 2019-10-01
host: x86_64-unknown-linux-gnu
release: 1.40.0-nightly
LLVM version: 9.0
```

Backtrace:

```
$ cargo build
   Compiling serde_json v1.0.40
   Compiling prost-build v0.5.0
   Compiling tonic v0.1.0-alpha.1 (/home/cloud/Documents/code/rust/tonic/tonic)
error: internal compiler error: src/librustc/ich/impls_ty.rs:100: StableHasher: unexpected region '_#0r

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (702b45e40 2019-10-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `tonic`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by mati865** [comment] 2019-10-02 21:05
Duplicate of https://github.com/rust-lang/rust/issues/64964

**Comment by nagisa** [comment] 2019-10-02 21:05
Duplicate of https://github.com/rust-lang/rust/issues/64964

**Comment by cpcloud** [comment] 2019-10-02 21:05
Thanks!

**Closed by nagisa** 2019-10-02 21:05 UTC
