### ISSUE TITLE
Compiler panic in stable_hash_impls.rs

### ISSUE THREAD

**Issue by Anivie** [rust-lang/rust#122554] opened 2024-03-15 15:20 UTC
### Meta

`rustc --version --verbose`:
```
rustc 1.78.0-nightly (f4b771bf1 2024-03-14)
binary: rustc
commit-hash: f4b771bf1fb836392e1c510a625cdc81be09c952
commit-date: 2024-03-14
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at /rustc/f4b771bf1fb836392e1c510a625cdc81be09c952/compiler/rustc_hir/src/stable_hash_impls.rs:97:35:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4b771bf1fb836392e1c510a625cdc81be09c952/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/f4b771bf1fb836392e1c510a625cdc81be09c952/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/f4b771bf1fb836392e1c510a625cdc81be09c952/library/core/src/panicking.rs:145:5
   3: core::option::unwrap_failed
             at /rustc/f4b771bf1fb836392e1c510a625cdc81be09c952/library/core/src/option.rs:1985:5
   4: rustc_query_system::dep_graph::graph::hash_result::<core::option::Option<&rustc_hir::hir::OwnerNodes>>
   5: rustc_ty_utils::assoc::feed_hir
   6: rustc_ty_utils::assoc::associated_type_for_impl_trait_in_trait
      [... omitted 1 frame ...]
   7: <dyn rustc_hir_analysis::astconv::AstConv>::ast_ty_to_ty_inner
   8: <dyn rustc_hir_analysis::astconv::AstConv>::ty_of_fn
   9: rustc_hir_analysis::collect::fn_sig
      [... omitted 2 frames ...]
  10: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
  11: <rustc_hir_analysis::variance::constraints::ConstraintContext>::build_constraints_for_item
  12: rustc_hir_analysis::variance::crate_variances
      [... omitted 1 frame ...]
  13: rustc_hir_analysis::variance::variances_of
      [... omitted 1 frame ...]
  14: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 16]>>>
  15: rustc_hir_analysis::check::wfcheck::check_variances_for_type_defn
  16: rustc_hir_analysis::check::wfcheck::check_well_formed
      [... omitted 1 frame ...]
  17: rustc_hir_analysis::check::wfcheck::check_mod_type_wf
      [... omitted 1 frame ...]
  18: rustc_hir_analysis::check_crate
  19: rustc_interface::passes::analysis
      [... omitted 1 frame ...]
  20: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
```

</p>
</details>

**Comment by Anivie** [comment] 2024-03-15 15:24
I can't ascertain the precise part of the code where the error occurred. I've been crafting code for a private repository, consistently compiling it successfully. However, since a submission today, I can no longer compile it successfully. Even when I revert to a previous version that compiled correctly, I face the same issue. It might be due to an upgrade in the dependency library, but I can't be sure. Up to now, I haven't been able to successfully compile my code. Here is the full error message：
[rustc-ice-2024-03-15T15_09_53-11212.txt](https://github.com/rust-lang/rust/files/14617451/rustc-ice-2024-03-15T15_09_53-11212.txt)

**Comment by compiler-errors** [comment] 2024-03-15 15:30
Duplicate of #122508

**Closed by compiler-errors** 2024-03-15 15:31 UTC
Labels: C-bug, needs-triage
