### ISSUE TITLE
Add a dedicated search page to Rustdoc

### ISSUE THREAD

**Issue by Gankra** [rust-lang/rust#18168] opened 2014-10-19 20:33 UTC
Search is lazily loaded after the rest of the content on a given page. This makes searches, especially ones using in-browser search utilities, or jumping through search history really sluggish and unresponsive. A dedicated empty page optimized for this usecase would be _greatly_ appreciated.

**Comment by steveklabnik** [comment] 2016-02-02 17:49
Triage: no change.

**Comment by steveklabnik** [comment] 2018-09-24 17:35
@rust-lang/rustdoc is this a feature we plan to implement?

**Comment by GuillaumeGomez** [comment] 2018-09-24 19:10
Isn't the search efficient enough now? If more search functionalities are wanted, we can always add them though.

**Comment by kzys** [comment] 2018-09-28 05:30
+1 for resolving. Rustdoc is not that slow (or our machines are faster, compared to 2014).

For the standard library, [the landing page](https://doc.rust-lang.org/nightly/) now has a small search box.

**Comment by camelid** [comment] 2022-01-09 02:12
I'm not quite sure what this issue is requesting, and it does seem like the issue is resolved now. Shall we close the issue?

**Comment by GuillaumeGomez** [comment] 2022-01-09 12:08
Funnily enough, we will end up with something like that once our plan started with https://github.com/rust-lang/rust/pull/90630 will be done.
 So yes, closing.

**Closed by GuillaumeGomez** 2022-01-09 12:08 UTC
Labels: T-rustdoc, T-dev-tools, C-feature-request
