### ISSUE TITLE
ICE on proc macro --extern import

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust#80946] opened 2021-01-12 16:23 UTC
### Code

```sh
echo | rustc --crate-type proc-macro --crate-name p -
echo '#![no_core] use p;' | rustc --target msp430-none-elf --edition 2018 --extern p -L . -
```

  - Use a non-installed target or a target spec file.
  - `#![no_core]` is there to avoid having to build `core` etc. in the repro.
  - Explicit paths (`--extern p=libp.so`) or `extern crate p;` do not trigger the issue.

### Meta

Latest stable (1.49.0) and nightly break.

### Error output

```
panicked at 'compiler/rustc_resolve/src/imports.rs:1049:33: inconsistent resolution for an import'
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: std::panicking::begin_panic
   1: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
   2: rustc_middle::ty::context::tls::with_opt::{{closure}}
   3: rustc_middle::ty::context::tls::with_opt
   4: rustc_middle::util::bug::opt_span_bug_fmt
   5: rustc_middle::util::bug::span_bug_fmt
   6: rustc_resolve::imports::ImportResolver::finalize_import::{{closure}}
   7: rustc_resolve::imports::ImportResolver::finalize_import
   8: rustc_resolve::imports::ImportResolver::finalize_imports
   9: rustc_resolve::Resolver::resolve_crate
  10: rustc_interface::passes::configure_and_expand_inner
  11: rustc_interface::passes::configure_and_expand::{{closure}}
  12: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  13: rustc_interface::passes::configure_and_expand
  14: rustc_interface::queries::Queries::expansion
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: rustc_interface::interface::create_compiler_and_run
  18: rustc_span::with_session_globals
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-01-12 16:25
Duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2021-01-12 16:25 UTC
Labels: C-bug, I-ICE, T-compiler
