### ISSUE TITLE
[MSVC] Rustc is producing inappropriate filetypes w/ `--crate-type=dylib` && `--crate-type=staticlib`.

### ISSUE THREAD

**Issue by DiamondLovesYou** [rust-lang/rust#28025] opened 2015-08-26 20:20 UTC
For example:

```sh
/C/msys64/home/Richard/rust-build/x86_64-pc-windows-msvc/stage2/bin/rustc.exe --out-dir /C/msys64/home/Richard/rust-build/x86_64-pc-windows-msvc/test/run-make/output-type-permutations -L /C/msys64/home/Richard/rust-build/x86_64-pc-windows-msvc/test/run-make/output-type-permutations foo.rs --crate-type=staticlib
```

produces just `libbar.a`.

```sh
 /C/msys64/home/Richard/rust-build/x86_64-pc-windows-msvc/stage2/bin/rustc.exe --out-dir /C/msys64/home/Richard/rust-build/x86_64-pc-windows-msvc/test/run-make/output-type-permutations -L /C/msys64/home/Richard/rust-build/x86_64-pc-windows-msvc/test/run-make/output-type-permutations foo.rs --crate-type=dylib
```

produces `bar.dll`, `bar.exp`, and `bar.lib`.

Note `rlib` output works as expected. See `output-type-permutations` from `run-make`.

**Comment by nagisa** [comment] 2015-08-26 21:56
What’s the issue here? Is the test failing, are the files not accepted by the `LINK.EXE` or it is simply extensions being not as expected?

`.lib` may also be an [import library](https://en.wikipedia.org/wiki/Dynamic-link_library#Import_libraries) without which `.dll` is pretty much useless. This is probably a reason why `dylib` emits both `.lib` and `.dll` at once. `.exp` [appears to have a similar purpose](https://msdn.microsoft.com/en-us/library/se8y7dcs.aspx).

`.a` should probably be `.lib`, but then it is ambiguous in case of flag like `--crate-type=staticlib,dylib` which should produce both and if we try to emit `.lib` in both cases, we will simply either not emit the static library, or emit an useless dynamic library.

**Comment by DiamondLovesYou** [comment] 2015-08-26 22:04
> What’s the issue here? Is the test failing, are the files not accepted by the LINK.EXE or it is simply extensions being not as expected?

See https://github.com/rust-lang/rust/pull/27938#issuecomment-134040584. I don't really know the cause, I use Linux or ssh into a Linux box when I'm on my Surface (my only windows machine) and thus aren't familiar with MSVC's conventions. Whatever the real issue, the test is failing, so I just made the test a no-op on MSVC and filed this issue.

**Comment by alexcrichton** [comment] 2015-08-27 18:23
Ok, I've got a branch with this test passing, so I'm going to close this as "working as intended"

**Closed by alexcrichton** 2015-08-27 18:23 UTC

**Comment by retep998** [comment] 2015-08-27 18:26
The msvc conventions are:

* When building a DLL, emit `foo.lib` and `foo.dll`. Downstream code will link to `foo.lib` and acquire a runtime dependency on `foo.dll`.
* When building a static library, emit `foo.lib`. Downstream code will link to `foo.lib`.
* `foo.exp` is used when you create `foo.lib` and `foo.dll` as two separate steps. `foo.exp` will be created alongside `foo.lib` and `foo.exp` is then passed to the linker to create `foo.dll`. Beyond that you don't need the `foo.exp` file.
