### ISSUE TITLE
Broken links in `String` documentation from `Deref` impl

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#32129] opened 2016-03-08 21:00 UTC
There are a bunch of links in the [`String` documentation](http://doc.rust-lang.org/nightly/std/string/struct.String.html) page which are broken. The reason for this is that most links are drawn from the documentation of the `str` type at `/std/primitive.str.html` but the `String` page is located at `/std/string/struct.String.html`. This mismatch in depth of paths causes a number of broken links, for example on the [`String::split`](http://doc.rust-lang.org/nightly/std/string/struct.String.html#method.split) method.

Not sure of the best way to fix this, but needs a tracking issue.

**Comment by durka** [comment] 2016-03-08 23:34
It would be most awesome if there were some way to link to an item in Rustdoc, not just putting in a link URL, but that's perhaps out of scope for now. Maybe just some basic variable substitution, so you could write `[foo]($htmlroot/bar/baz/foo.html)`?

**Comment by alexcrichton** [comment] 2016-03-08 23:59
Yeah I suspect some basic substitution could work especially because we control the markdown rendering. I'd be a little wary to add API surface area to rustdoc, but it seems minorly well motivated?

**Comment by durka** [comment] 2016-03-09 00:02
It seems pretty much required to put in some facility for linking without relative URLs, because Deref copies and pastes things around.

**Comment by steveklabnik** [comment] 2016-03-09 04:39
It would be nice if we could follow the work CommonMark is doing here, so we're not totally just inventing a new thing.

http://talk.commonmark.org/t/generic-directives-plugins-syntax/444 seems to be at least one relevant discussion.

**Comment by mitaa** [comment] 2016-03-10 08:59
That seems like a nice long-term solution, that'd have to be implemented in hoedown however.

There is an _old_ issue regarding this on their repo: https://github.com/hoedown/hoedown/issues/99

**Comment by steveklabnik** [comment] 2016-03-10 09:02
yes, I would like to move from hoedown to pulldown-cmark, personally.

**Comment by frewsxcv** [comment] 2016-12-15 23:21
Opened an issue for moving to pulldown-cmark: https://github.com/rust-lang/rust/issues/38400

**Comment by MaloJaffre** [comment] 2017-12-13 20:03
This seems to be blocking testing of compiler docs: ref #46278

**Comment by ollie27** [comment] 2018-11-07 16:04
This needs to be reopened. There are still broken links (e.g. #55666) and this issue can't be closed until the whitelist in linkchecker is removed: https://github.com/rust-lang/rust/blob/8315b11b6352cbd91ee096571c31ae7d3ac9613d/src/tools/linkchecker/main.rs#L134-L148

**Comment by mglax** [comment] 2018-11-08 18:44
There are indeed, a HUGE amount of broken links

**Comment by Dylan-DPC** [comment] 2019-12-22 14:25
This is fixed, closing it. Thanks :)

**Comment by estebank** [comment] 2019-12-22 17:47
@Dylan-DPC I don't think it was (unless the nightly docs haven't been updated with the fix yet). In the [`String::split`](https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.split) section, if you click on [`DoubleEndedIterator`](https://doc.rust-lang.org/nightly/std/string/iter/trait.DoubleEndedIterator.html) you end up in a 404.

**Comment by ehuss** [comment] 2019-12-22 19:19
It might be useful to have a tracking issue for all of the causes of broken links (maybe reuse this one?), because there are dozens of broken links, and I think some are for different reasons.  It'd be nice to have a goal to remove the linkchecker whitelist.  I'd guess most of them are waiting for intra-rustdoc-links to handle all the appropriate scenarios?  It's not really clear what needs to be done.

**Comment by ehuss** [comment] 2020-07-18 17:58
Reopening until the exclusions in the link checker can be removed.

**Comment by jyn514** [comment] 2020-11-04 06:20
I think this was fixed in https://github.com/rust-lang/rust/pull/74485? Should this be closed?

**Comment by ehuss** [comment] 2020-11-04 17:20
Considering that all the String links seem to be fixed, I think it is good to close. It looks like there are plenty of other tracking issues for the last remaining broken links (like #63351 and #74481), so I think those are adequately tracked.  Thanks everyone for putting all the work into intra-doc-links!

**Closed by ehuss** 2020-11-04 17:20 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
