### ISSUE TITLE
rustdoc: "Methods from Deref" appears inconsistently

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#91400] opened 2021-11-30 20:03 UTC
I tried this code:

```rust
pub struct Bar(Baz);
impl std::ops::Deref for Bar {
    type Target = Baz;
    fn deref(&self) -> &Baz { &self.0 }
}

pub struct Baz {}
impl Baz {
    /// [prim@str]
    pub fn foo() {}
}
```

I expected to see this happen: Rustdoc generates a "Methods from Deref" section, the way it does if the struct derefs to Path: 
![image](https://user-images.githubusercontent.com/23638587/144119374-124a645f-aed6-4ecf-826b-acedea7fad77.png)

Instead, this happened: Rustdoc doesn't generate the section: 
![image](https://user-images.githubusercontent.com/23638587/144119424-25969ccb-67e4-4ec5-8f6e-bbbaf88c7b3f.png)

### Meta

`rustdoc --version`: rustdoc 1.58.0-nightly (936f2600b 2021-11-22)

cc @GuillaumeGomez

**Comment by jyn514** [comment] 2021-11-30 20:04
I thought originally this was related to `Baz` being in the current crate, but I moved it to an inner crate and that still didn't generate the right section.

**Comment by jyn514** [comment] 2021-11-30 20:09
Relevant code: https://github.com/rust-lang/rust/blob/207c80f105282245d93024c95ac408c622f70114/src/librustdoc/html/render/mod.rs#L1035-L1076

**Comment by GuillaumeGomez** [comment] 2021-11-30 21:04
This is surprising. I'll take a look tomorrow.

**Comment by GuillaumeGomez** [comment] 2021-12-01 10:03
This is the expected behaviour because they are not methods (they don't have a `self` argument). We call the function to check it [here](https://github.com/rust-lang/rust/blob/2446a215954a99f9d33019fad7d415ef9c083502/src/librustdoc/html/render/mod.rs#L1347) and the function itself is [here](https://github.com/rust-lang/rust/blob/2446a215954a99f9d33019fad7d415ef9c083502/src/librustdoc/html/render/mod.rs#L1209).

This behaviour is tested in [this test](https://github.com/rust-lang/rust/pull/90183/files#diff-bb8afd515a8bdd6a265bc21162ce49eea651080fa67a3f44a26e621f722a0105R49). Since this is the expected result, I'll close the issue.

**Closed by GuillaumeGomez** 2021-12-01 10:03 UTC
Labels: T-rustdoc, A-traits, C-bug
