### ISSUE TITLE
`#[path]` does not accept macro-generated paths

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#118312] opened 2023-11-26 11:52 UTC
I tried this code:

```rust
#[path = concat!(env!("OUT_DIR"), "/zbus_xmlgen_output.rs")]
mod generated;
```

I expected to see this happen: the module is loaded from the expanded path

Instead, this happened:

```
error: malformed `path` attribute input
 --> src/main.rs:1:1
  |
1 | #[path = concat!(env!("OUT_DIR"), "/zbus_xmlgen_output.rs")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: must be of the form: `#[path = "file"]`
```

(Attempted as a workaround for https://github.com/rust-lang/rust/issues/117464 as `zbus-xmlgen` generates inner doc attributes).

### Meta
`rustc --version --verbose`:
```
rustc 1.76.0 (a1a37735c 2023-11-23)
binary: rustc
commit-hash: a1a37735cbc3db359d0b24ba9085c9fcbe1bc274
commit-date: 2023-11-23
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.5
```

**Comment by ehuss** [comment] 2023-11-26 16:09
Thanks for the report! I'm going to close as a duplicate of #87681. I'm not sure how feasible it would be to implement eager expansion in that position due to the way `#[path]` works during expansion.

**Closed by ehuss** 2023-11-26 16:09 UTC
Labels: A-attributes, A-macros, T-compiler, C-bug, needs-triage

**Comment by Nemo157** [comment] 2023-11-26 17:04
Ah thanks, I was sure this would have been reported before and spent a while searching but failed to find that issue.
