### ISSUE TITLE
Error : linking with `cc` failed: exit status: 1 in Rust 

### ISSUE THREAD

**Issue by VyomPatel0109** [rust-lang/rust#124880] opened 2024-05-08 08:26 UTC
Error : linking with cc failed: exit status: 1

I got above error when I tried to run my rust project using Cargo run command on free tier EC2 instance of AWS. How to resolve it?

**Comment by jieyouxu** [comment] 2024-05-13 11:55
We need more information than that to even try to understand what is wrong.

- What's the rustc version? (`rustc --version --verbose`)
- Please post the *complete* error message. `Error : linking with cc failed: exit status: 1` is incredibly vague. Do you have a dependency that has a build script that assumes some library is available to link to (e.g. some `*-sys` crate)?
- How can we reproduce your issue? Do you have a cargo project that reproduces the linking failed issue *without* being in the EC2 environment?

**Comment by WyntersN** [comment] 2024-05-13 15:20
> 我们需要更多的信息才能尝试了解问题所在。
> 
> * rustc 版本是什么？( `rustc --version --verbose`)
> * 请发布_完整的_错误消息。`Error : linking with cc failed: exit status: 1`非常模糊。您是否有一个依赖项，该依赖项具有一个构建脚本，该脚本假设可以链接到某些库（例如某些`*-sys`板条箱）？
> * 我们如何重现您的问题？_您是否有一个货物项目可以在不_处于 EC2 环境中的情况下重现链接失败的问题？


release: 1.78.0
LLVM version: 18.1.2


could not compile `rust-i18n-macro` (lib) due to 1 previous error
>>> Error: Cargo build failed from Linux

**Comment by jieyouxu** [comment] 2024-05-13 15:31
Please also post your `Cargo.toml`. "linking with cc failed" usually indicates that one or more of your dependencies assumes or requires some library to be available on your system, but that said library is not available to the linker for one reason or another.

**Comment by WyntersN** [comment] 2024-05-13 15:41
> Please also post your `Cargo.toml`. "linking with cc failed" usually indicates that one or more of your dependencies assumes or requires some library to be available on your system, but that said library is not available to the linker for one reason or another.

Is there any way? I'm using Docker

docker rust:alpine3.19

**Comment by WyntersN** [comment] 2024-05-14 05:58
alpine3.19  build success
apk add --no-cache -U build-base
apk add --no-cache -U musl-dev
apk add --no-cache -U libgcc

**Comment by MiniOcean404** [comment] 2024-08-02 07:56
I'm using `zune-jpeg` but it has the same error and the platform it's built for is `armv7-unknown-linux-gnueabihf `

**Comment by Noratrieb** [comment] 2024-11-09 21:09
closing as unactionable

**Closed by Noratrieb** 2024-11-09 21:09 UTC
Labels: C-discussion
