### ISSUE TITLE
measure impact of MIR on compilation times and time to run tests across crates.io

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#34506] opened 2016-06-27 17:15 UTC
Before enabling MIR by default, we'd like to have some broad sense of how it impacts average compilation times. This could be done by running across all of crates.io and taking the average. It'd also be nice to measure the time to run tests. I've got a script for doing this but haven't been able to finish the collation part of the script, or gather complete results.

The script is here:

https://github.com/nikomatsakis/cratesio_perf

cc @rust-lang/compiler

**Comment by retep998** [comment] 2016-06-27 18:00
Don't forget Windows specific crates!

**Comment by alexcrichton** [comment] 2016-07-21 02:04
@brson I believe you "ran crater on Windows", right? Could you post the results here as well?

**Comment by brson** [comment] 2016-07-21 18:33
Here's the link: https://internals.rust-lang.org/t/enabling-mir-by-default/3555/48?u=brson. TL;DR Of the crates I compiled and tested on x86_64-pc-windows-msvc I found no functional regressions. Didn't test perf. I didn't have an OpenSSL build so there were some failures due to that, but I was able to build perhaps ~2500 crates.

**Comment by Mark-Simulacrum** [comment] 2017-05-07 14:22
MIR has been launched -- so keeping this open isn't all that helpful. Closing.

**Closed by Mark-Simulacrum** 2017-05-07 14:22 UTC
Labels: A-mir, T-compiler
