### ISSUE TITLE
Error for `for _ in HashMap::new().iter().cloned() { }` doesn't provide enough context

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#33941] opened 2016-05-29 08:24 UTC
[Playpen](https://play.rust-lang.org/?gist=ad9cef83fedfb5006dfc5271827796f6&version=nightly&backtrace=0)

``` rust
use std::collections::HashMap;

fn main() {
    for _ in HashMap::new().iter().cloned() { }
}
```

`.cloned()` failing is normal since the iterator's items are `(&K, &V)` and `.cloned()` expects `&T`, but the number of errors is strange.

```
error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:36
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>                                    ^^^^^^

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`
note: required by `std::iter::IntoIterator::into_iter`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`
note: required by `std::iter::IntoIterator::into_iter`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`
note: required because of the requirements on the impl of `std::iter::IntoIterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`
note: required by `std::iter::Iterator::next`

error: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`:
 expected tuple,
    found &-ptr [--explain E0271]
 --> <anon>:4:5
4 |>     for _ in HashMap::new().iter().cloned() { }
  |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`

error: aborting due to 9 previous errors
```

**Comment by DoumanAsh** [comment] 2016-05-29 08:41
I also think the error should be improved.
Especially because you bluntly show user API that cannot be compiled.
I'm ofc talking about HashMap's iter docs

**Comment by estebank** [comment] 2017-09-30 01:33
Current output:

```
error[E0271]: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`
 --> src/main.rs:4:36
  |
4 |     for _ in HashMap::new().iter().cloned() { }
  |                                    ^^^^^^ expected tuple, found reference
  |
  = note: expected type `(&_, &_)`
             found type `&_`

error[E0271]: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`
 --> src/main.rs:4:5
  |
4 |     for _ in HashMap::new().iter().cloned() { }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected tuple, found reference
  |
  = note: expected type `(&_, &_)`
             found type `&_`
  = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`
~~~~~~~8<~~~~~~~
```

---

There are two problems here that can be tackled independently:

1) The duplicated E0271 type mismatch errors can be fixed by [modifying `report_projection_error` to _not_ emit the diagnostic immediately](https://github.com/rust-lang/rust/blob/master/src/librustc/traits/error_reporting.rs#L222-L228), but rather [to modify InferCtxt](https://github.com/rust-lang/rust/blob/master/src/librustc/infer/mod.rs#L75) to keep a hashset of `(expected_type, found_type, Span)` so that the same error isn't emitted multiple times. All the duplicated errors (from the second onwards) seem to be caused by the implicit handling of iterators. Bonus points for collecting all the `obligation`s and emitting them all together in the same diagnostic, instead of just losing the latter ones (requires either finding a method that gets called always at the end, or adding one).

2) The error itself is not very illuminating and should have extra information provided in order to be helpful. For the case in particular of `hash_map::Iter`, it would be great if we could suggest the following, as that would actually do what the user expects (other than a missing type definition for the `HashMap`, on real code the `HashMap` would have been created before so that it would have had a chance to be populated), but I don't know how we could accomplish that in a clean way:
```
 --> src/main.rs:4:5
  |
4 |     for _ in HashMap::new().iter().cloned() { }
  |     ^^^^^^^^^^^^^^^^^^^^^^^-------^^^^^^^^^^^^^ expected tuple, found reference
  |                             |
  |                             help: did you mean to use `values()` here?
```

In general, it would probably be nice to have something along the lines of the following output on cases where type errors are propagated down a method call chain, but it's non-trivial to do and would still add little help here, so it should be out of scope of this issue:
```
error[E0271]: type mismatch resolving `<std::collections::hash_map::Iter<'_, _, _> as std::iter::Iterator>::Item == &_`
 --> src/main.rs:4:5
  |
4 |     for _ in HashMap::new().iter().cloned() { }
  |     ^^^^^^^^^--------------^------^--------^^^^ expected tuple, found reference
  |              |              |      |
  |              |              |      found `&_` here
  |              |              found `std::collections::hash_map::Iter<'_, _, _>` here
  |              found `std::collections::HashMap<_, _>` here
  |
  = note: expected type `(&_, &_)`
             found type `&_`
  = note: required because of the requirements on the impl of `std::iter::Iterator` for `std::iter::Cloned<std::collections::hash_map::Iter<'_, _, _>>`
```

**Comment by estebank** [comment] 2020-01-22 18:51
Triage: no change.

**Comment by yihuang** [comment] 2020-06-14 06:30
I wonder is there handy utils to convert `(&K, &V)` into `(K, V)` without writing a closure?

**Closed** 2022-12-16 01:46 UTC
Labels: C-enhancement, A-diagnostics, T-compiler, WG-diagnostics, D-confusing, D-papercut
