### ISSUE TITLE
Rust 1.18 regression, hamt-0.2.2, sigill

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41798] opened 2017-05-07 00:25 UTC
https://github.com/michaelwoerister/hamt-rs

```
101 brian@ip-10-145-43-250:~/dev/hamt-rs⟫ git log -1
commit 7bb893a2e4e5258b9bfcef46355a1dedfe0fc596
Author: Michael Woerister <michaelwoerister@posteo.net>
Date:   Tue Oct 25 14:18:54 2016 -0400

    Bump version
```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.18.0-beta.1 (4dce67253 2017-04-25)
binary: rustc
commit-hash: 4dce67253d67785c74c8d270c38d774edd0deed8
commit-date: 2017-04-25
host: x86_64-unknown-linux-gnu
release: 1.18.0-beta.1
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/hamt-rs⟫ cargo +beta test
   Compiling libc v0.2.18
   Compiling rand v0.3.15
   Compiling hamt-rs v0.2.2 (file:///mnt2/dev/hamt-rs)
warning: use of deprecated item: use `std::collections::hash_map::DefaultHasher` instead
  --> src/hamt.rs:41:5
   |
41 | use std::hash::SipHasher as StdHasher;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: use `std::collections::hash_map::DefaultHasher` instead
    --> src/hamt.rs:1162:48
     |
1162 | pub struct HamtMap<K, V, IS=ShareStore<K,V>, H=StdHasher> {
     |                                                ^^^^^^^^^
     |
     = note: #[warn(deprecated)] on by default

warning: use of deprecated item: use `std::collections::hash_map::DefaultHasher` instead
  --> src/hamt.rs:41:5
   |
41 | use std::hash::SipHasher as StdHasher;
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default

warning: use of deprecated item: use `std::collections::hash_map::DefaultHasher` instead
    --> src/hamt.rs:1162:48
     |
1162 | pub struct HamtMap<K, V, IS=ShareStore<K,V>, H=StdHasher> {
     |                                                ^^^^^^^^^
     |
     = note: #[warn(deprecated)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 5.48 secs
     Running target/debug/deps/hamt_rs-03bacaf30144cdeb

running 18 tests
test hamt::tests::test_default_copy ... ok
test hamt::tests::test_eq_empty_copy ... ok
test hamt::tests::test_get_index ... ok
test hamt::tests::test_insert_ascending_copy ... FAILED
thread panicked while panicking. aborting.
error: process didn't exit successfully: `/mnt2/dev/hamt-rs/target/debug/deps/hamt_rs-03bacaf30144cdeb` (signal: 4, SIGILL: illegal instruction)

To learn more, run the command again with --verbose.
```

cc @michaelwoerister

**Comment by Mark-Simulacrum** [comment] 2017-05-08 02:56
da32752d92589e99feab80921b9eecb6090cf310 -- rollup PR https://github.com/rust-lang/rust/pull/41237

Most likely caused by struct reordering: https://github.com/rust-lang/rust/pull/40377.

**Comment by michaelwoerister** [comment] 2017-05-08 09:29
> Most likely caused by struct reordering

Yes, that seems very likely. I'll try if `repr(C)` will fix this before the next triage meeting.

**Comment by michaelwoerister** [comment] 2017-05-08 10:10
This was indeed caused by struct reordering and is not a regression since the code relies on C memory layout but did not specify `repr(C)`. Closing.

**Closed by michaelwoerister** 2017-05-08 10:10 UTC
Labels: regression-from-stable-to-beta, T-compiler
