### ISSUE TITLE
Make "cannot move out of borrowed content" more beginner friendly

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#55153] opened 2018-10-17 15:25 UTC
The following code emits "cannot move out of borrowed content" without any hint about the reason whatsoever. I think we should add a "help" pointing to the `self` argument of `talk` and stating something along the lines of "because of consuming argument here". If it's in the same crate, maybe even suggest to change it to a reference.

```rust
struct Sheep {
    message: String
}

impl Sheep {
    fn talk(self) {
        println!("{}", self.message);
    }
}

fn main()
{
    let sheep = &Sheep { message: "Määh".into() };
    sheep.talk();
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=fb8b0d2febff333aca5a681fdf837f0a))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0507]: cannot move out of borrowed content
  --> src/main.rs:14:5
   |
14 |     sheep.talk();
   |     ^^^^^ cannot move out of borrowed content

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by csmoe** [comment] 2018-10-18 07:10
as I mentioned in [zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/misc_question) when talked about https://github.com/rust-lang/rust/issues/53882, the borrowck should have something like `borrower/mover(consumer)`, etc to help the users find out where the behaviors occurs:
```rust
struct Sheep {
    message: String
}

impl Sheep {
    fn talk(self) {
       ^^^^^^^^^ moved here
        println!("{}", self.message);
    }
}

fn main()
{
    let sheep = &Sheep { message: "Määh".into() };
    sheep.talk();
    ^^^^^ moved by `Sheep::talk`
}
```

**Comment by ibraheemdev** [comment] 2021-07-27 16:40
Duplicate of #43161

**Closed** 2021-07-28 00:11 UTC
Labels: A-diagnostics, C-enhancement, D-newcomer-roadblock, NLL-diagnostics, T-compiler
