### ISSUE TITLE
Compiler doesn't realize that all match cases are covered

### ISSUE THREAD

**Issue by amab8901** [rust-lang/rust#129354] opened 2024-08-21 12:42 UTC
I tried this code:

```rust
fn main() {
    let a = 10.0_f64;
    let b = 20.0_f64;
    match a {
        a if a > b => {}
        a if a < b => {}
        a if a == b => {}
    };
}

```
I expected the compiler to realize that all cases have been covered, but instead the compiler says that "pattern `_` not covered"

### Meta

`rustc --version --verbose`:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.7
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling nice v0.1.0 (/home/amir/src/nice)
error[E0004]: non-exhaustive patterns: `_` not covered
 --> src/main.rs:4:11
  |
4 |     match a {
  |           ^ pattern `_` not covered
  |
  = note: the matched value is of type `f64`
  = note: match arms with guards don't count towards exhaustivity
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
  |
7 ~         a if a == b => {},
8 +         _ => todo!()
  |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `nice` (bin "nice") due to 1 previous error
```

</p>
</details>

**Comment by wesleywiser** [comment] 2024-08-21 13:47
Not all match cases are covered:

```rust
fn main() {
    let a = f64::NAN;
    let b = 20.0_f64;
    match a {
        a if a > b => {println!("a > b")}
        a if a < b => {println!("a < b")}
        a if a == b => {println!("a == b")}
        _ => {println!("other")}
    };
}
```

```
other
```

**Comment by matthiaskrgr** [comment] 2024-08-21 14:01
I think you can use https://doc.rust-lang.org/std/cmp/enum.Ordering.html here

**Comment by compiler-errors** [comment] 2024-08-21 14:24
This is not a bug for several reasons. Firstly, it's not a bug because of floating semantics as Wesley shared above. Secondly, Rust does not consider the *guard* of a match arm to participate in exhaustiveness, and I don't think that's something we should (or will) fix, so this doesn't work for integers either.

Thanks for the issue report! But I'll close this.

**Closed by compiler-errors** 2024-08-21 14:24 UTC
