### ISSUE TITLE
Strange auto derive behaviour with associated types

### ISSUE THREAD

**Issue by CasualX** [rust-lang/rust#33711] opened 2016-05-18 10:58 UTC
Auto deriving impls for a generic struct which only contains instances of associated types (not the generics themselves) unnecessarily constrains the impl for the struct.

I tried this code: https://is.gd/V6mqWI

```rust
pub trait Trait: Clone {
    type Type: Copy + Clone;
}

#[derive(Copy, Clone)]
pub struct ImplT;
impl Trait for ImplT {
    type Type = i32;
}

// Here is the problem, auto derive for `Copy` does nothing.
// What I believe is happening is that impl for `Copy` is unnecessarily constraining `T` itself must be `Copy`.
#[derive(Copy, Clone)]
pub struct NewT<T: Trait>(pub T::Type);
// Workaround:
//impl<T: Trait> Copy for NewT<T> where T::Type: Copy {}

#[derive(Clone)]
pub struct Foo<T: Trait>(T::Type);
impl<T: Trait> Foo<T> {
    pub fn get_if<F>(&self, f: F) -> Option<NewT<T>>
        where F: FnOnce(NewT<T>) -> bool {
        let newt = NewT(self.0);
        if f(newt) {
            Some(newt)
        }
        else {
            None
        }
    }
}

fn main() {
    let foo = Foo::<ImplT>(42);
    foo.get_if(|newt| true);
}
```

I expected to see this happen: `NewT<T>` is copyable.

Instead this happened:

	<anon>:25:18: 25:22 error: use of moved value: `newt` [E0382]
	<anon>:25             Some(newt)
	                           ^~~~
	<anon>:25:18: 25:22 help: see the detailed explanation for E0382
	<anon>:24:14: 24:18 note: `newt` moved here because it has type `NewT<T>`, which is non-copyable
	<anon>:24         if f(newt) {
	                       ^~~~
	error: aborting due to previous error
	playpen: application terminated with error code 101

Workaround: Instead of auto deriving `Copy` for `NewT<T>`, manually implement it like so:

```rust
#[derive(Clone)]
pub struct NewT<T: Trait>(pub T::Type);
impl<T: Trait> Copy for NewT<T> where T::Type: Copy {}
```

## Meta

I used playpen; Debug, Stable, but the same error happens with every option I select.

**Comment by apasel422** [comment] 2016-05-18 12:42
Similar to #23575.

**Comment by durka** [comment] 2016-05-18 14:41
Duplicate of #31518 (and others) I believe.

**Comment by durka** [comment] 2016-05-18 14:43
The built-in derives always add bounds for the derived trait on all type parameters, regardless of what's contained in the struct/enum. You can run with `--pretty=expanded` to see what it generates.

**Comment by CasualX** [comment] 2016-05-18 15:28
Thanks, my search query for [derive associated type](https://github.com/rust-lang/rust/search?utf8=%E2%9C%93&q=derive+associated+type&type=Issues) only found #23575 which talks about some fixes but I guess that's older, unrelated stuff.

**Comment by apasel422** [comment] 2016-05-26 17:23
Closing as duplicate.

**Closed by apasel422** 2016-05-26 17:23 UTC
