### ISSUE TITLE
Using associated constant as array size leads to ICE

### ISSUE THREAD

**Issue by rizakrko** [rust-lang/rust#53067] opened 2018-08-04 17:49 UTC
This is a repro case for [#52462](https://github.com/rust-lang/rust/issues/52462).
Following code:
```rust
trait T {
    const SIZE: usize;
    fn convert(self) -> [u8; T::SIZE];
}

impl T for u64 {
    const SIZE: usize = 8;
    fn convert(self) -> [u8; u64::SIZE] {
        unimplemented!()
    }
}
fn main() {}
```
causes compilation error:
```
error[E0283]: type annotations required: cannot resolve `_: T`
 --> src/main.rs:3:30
  |
3 |     fn convert(self) -> [u8; T::SIZE];
  |                              ^^^^^^^
  |
note: required by `T::SIZE`
 --> src/main.rs:2:5
  |
2 |     const SIZE: usize;
  |     ^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
However, change from
```rust
fn convert(self) -> [u8; u64::SIZE] {
```
to
```rust
fn convert(self) -> [u8; T::SIZE] {
```
causes following ICE:
```
error: internal compiler error: librustc/traits/codegen/mod.rs:63: Encountered ambiguity selecting `Binder(<[type error] as T>)` during codegen, presuming due to overflow

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
```
This can be reproduced on stable, beta and nightly. [Playground](http://play.rust-lang.org/?gist=28de71fb45badac1b18812f273a94c0a&version=stable&mode=debug&edition=2015)

## Meta
rustc 1.30.0-nightly (3edb355b7 2018-08-03)
binary: rustc
commit-hash: 3edb355b75a2c8315da5942f6a4d40c5d9b5ccbf
commit-date: 2018-08-03
host: x86_64-unknown-linux-gnu
release: 1.30.0-nightly
LLVM version: 7.0
<details>
<summary>
Backtrace
</summary>
```
thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::bug_fmt
  14: rustc::ty::context::tls::with_related_context
  15: rustc::traits::codegen::codegen_fulfill_obligation
  16: rustc::ty::query::__query_compute::codegen_fulfill_obligation
  17: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::codegen_fulfill_obligation<'tcx>>::compute
  18: rustc::ty::context::tls::with_context
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc::ty::context::tls::with_related_context
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  23: rustc::ty::instance::Instance::resolve
  24: <rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::resolve
  25: <rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::const_to_value
  26: rustc_mir::transform::const_prop::ConstPropagator::eval_constant
  27: <rustc_mir::transform::const_prop::ConstPropagator<'b, 'a, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_statement
  28: <rustc_mir::transform::const_prop::ConstProp as rustc_mir::transform::MirPass>::run_pass
  29: rustc_mir::transform::optimized_mir::{{closure}}
  30: rustc_mir::transform::optimized_mir
  31: rustc::ty::query::__query_compute::optimized_mir
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::optimized_mir<'tcx>>::compute
  33: rustc::ty::context::tls::with_context
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: rustc::ty::context::tls::with_related_context
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_query
  38: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::maybe_optimized_mir
  39: <rustc_mir::interpret::eval_context::EvalContext<'a, 'mir, 'tcx, M>>::load_mir
  40: rustc_mir::interpret::const_eval::eval_body_using_ecx
  41: rustc_mir::interpret::const_eval::const_eval_provider
  42: rustc::ty::query::__query_compute::const_eval
  43: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_eval<'tcx>>::compute
  44: rustc::ty::context::tls::with_context
  45: rustc::dep_graph::graph::DepGraph::with_task_impl
  46: rustc::ty::context::tls::with_related_context
  47: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  48: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  49: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_const
  50: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::TyS<'tcx>>::super_fold_with
  51: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
  52: <rustc_data_structures::accumulate_vec::AccumulateVec<A> as core::iter::traits::FromIterator<<A as rustc_data_structures::array_vec::Array>::Element>>::from_iter
  53: rustc::ty::fold::TypeFoldable::fold_with
  54: rustc::infer::InferCtxt::partially_normalize_associated_types_in
  55: rustc::ty::context::tls::with_related_context
  56: rustc::infer::InferCtxtBuilder::enter
  57: rustc_typeck::check::wfcheck::check_associated_item
  58: rustc_typeck::check::wfcheck::check_impl_item
  59: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::check_impl_item_well_formed<'tcx>>::compute
  60: rustc::ty::context::tls::with_context
  61: rustc::dep_graph::graph::DepGraph::with_task_impl
  62: rustc::ty::context::tls::with_related_context
  63: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  64: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  65: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  66: rustc::session::Session::track_errors
  67: rustc::util::common::time
  68: rustc_typeck::check_crate
  69: rustc::ty::context::tls::enter_context
  70: <std::thread::local::LocalKey<T>>::with
  71: rustc::ty::context::TyCtxt::create_and_enter
  72: rustc_driver::driver::compile_input
  73: rustc_driver::run_compiler_with_pool
  74: <scoped_tls::ScopedKey<T>>::set
  75: syntax::with_globals
  76: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  77: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  78: rustc_driver::run
  79: rustc_driver::main
  80: std::rt::lang_start::{{closure}}
  81: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  82: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  83: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  84: main
  85: __libc_start_main
  86: <unknown>
query stack during panic:
#0 [codegen_fulfill_obligation] checking if `T` fulfills its obligations
#1 [optimized_mir] processing `<u64 as T>::convert::{{constant}}`
#2 [const_eval] const-evaluating `<u64 as T>::convert::{{constant}}`
#3 [check_impl_item_well_formed] processing `<u64 as T>::convert`
end of query stack
```
</details>

**Comment by dtolnay** [comment] 2018-08-13 07:37
Duplicate of #48027.

**Closed by dtolnay** 2018-08-13 07:37 UTC
Labels: A-associated-items, I-ICE
