### ISSUE TITLE
carboxyl_time-0.0.2 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43658] opened 2017-08-05 12:30 UTC
[carboxyl_time](https://crates.io/crates/carboxyl_time) version 0.0.2 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/carboxyl_time-0.0.2/log.txt)):

```
 error: type `signal::FuncSignal<A>` is private
   --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/carboxyl-0.1.2/src/lift.rs:80:28
    |
 80 |             SignalFn::Func(_) => SignalFn::from_fn(move || f(sample_raw(&pclone))),
    |                            ^
 
```

**Comment by est31** [comment] 2017-08-05 12:30
cc @aepsil0n

**Comment by petrochenkov** [comment] 2017-08-05 12:40
This is a known regression (see https://github.com/rust-lang/rust/pull/42125#issuecomment-304301659).
The issue was actually in `carboxyl`, not `carboxyl_time`, and it was [fixed](https://github.com/aepsil0n/carboxyl/commit/a57fc7feb695b992cecff480b2fdea66292c1642) in Feb 2016, but `carboxyl_time` still uses outdated version of `carboxyl`.

**Comment by aepsil0n** [comment] 2017-08-05 18:20
Ah, this is actually fixed on master and the tagged 0.0.3 version, but I think it has not been published yet to crates.io. Let me do that right away.

**Comment by aepsil0n** [comment] 2017-08-05 18:38
Uhm… okay, this is a bit unfortunate, but I am blocked on rust-lang/cargo#4264. Now I remember why I did not publish this in the first place: same issue, but I did not have time to look into it and forgot about later.

**Comment by alexcrichton** [comment] 2017-08-12 22:06
@aepsil0n an issue like https://github.com/rust-lang/cargo/issues/4264 is pretty unlikely to be indicative of a bug in Cargo, are you sure this happens persistently over time? If so would you able to help debug that issue?

**Comment by aepsil0n** [comment] 2017-08-13 15:52
It does happen persistently at least on my machine. (Tried it for the third time now.) I am glad to help out with debugging, if you can tell me what to look for. Meanwhile I should probably try this on another machine.

**Comment by alexcrichton** [comment] 2017-08-14 04:04
Hm could you try to attach a debugger when Cargo looks like it hanging and see what the backtrace is? Also, can you try setting `RUST_LOG=debug` and see if Cargo prints anything useful to know where it's publishing to?

**Comment by aepsil0n** [comment] 2017-08-14 09:27
Uhm, that's weird… I just tried publishing at work and it went fine. I'm starting to suspect that my wifi network at home has an issue. Need to look into this further.

Anyway, the regression should be fixed now.

**Comment by alexcrichton** [comment] 2017-08-14 23:16
Thanks @aepsil0n!

**Closed by alexcrichton** 2017-08-14 23:16 UTC
Labels: C-bug, regression-from-stable-to-beta, T-compiler
