### ISSUE TITLE
macros(like vec!) cannot parse `const { 1 }` block as valid expressions.

### ISSUE THREAD

**Issue by Neutron3529** [rust-lang/rust#130217] opened 2024-09-11 07:58 UTC
I tried this code:

```rust
let _ = vec![const { 1 }; 0];
```

I expected to see this happen: Compiles.

Instead, this happened: 

error: no rules expected the token `const`
 --> src/main.rs:3:18
  |
3 |     let _ = vec![const { 1 }; 0];
  |                  ^^^^^ no rules expected this token in macro call
  |
  = note: while trying to match end of macro

### Meta
`rustc --version --verbose`:
```
rustc 1.82.0-nightly (0d634185d 2024-08-29)
binary: rustc
commit-hash: 0d634185dfddefe09047881175f35c65d68dcff1
commit-date: 2024-08-29
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

It seems that, macro could not recognize `const { 1 }` as a block expression, which leads to the error.

What's more, with adding an unnecessary bracket, `let _ = vec![(const { 1 }); 0];`, the code compiles, but an warning about unnecessary bracket generated, which suggests me delete the *unnecessary* bracket and facing the error directly.

**Comment by zirconium-n** [comment] 2024-09-11 08:23
Kind of duplicate of #126459

**Comment by ehuss** [comment] 2024-09-11 13:49
Indeed this looks like a duplicate of the two above linked issues, so closing in favor of them. If there is a reason to keep this open separately, let us know! Thanks!

**Closed by ehuss** 2024-09-11 13:49 UTC
Labels: C-bug, needs-triage
