### ISSUE TITLE
find at fmt code

### ISSUE THREAD

**Issue by SmiteWindows** [rust-lang/rust#79763] opened 2020-12-06 13:26 UTC
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_middle\src\ty\query\mod.rs:235:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (e792288d 2020-12-05)

**Comment by jonas-schievink** [comment] 2020-12-06 13:29
Duplicate of https://github.com/rust-lang/rust/issues/79661, presumably

**Closed by jonas-schievink** 2020-12-06 13:29 UTC
Labels: C-bug, I-ICE, T-compiler
