### ISSUE TITLE
rustc panicked at 'attempted to read from stolen value'

### ISSUE THREAD

**Issue by alex-caelus** [rust-lang/rust#89197] opened 2021-09-23 06:00 UTC
### Code

I don't know what triggered the error so I can't do a MVE. The error appears to be in `clap-2.33.3/src/macros.rs:349:9: 356:10` though, see error output below.

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (ac2d9fc50 2021-09-21)
binary: rustc
commit-hash: ac2d9fc509e36d1b32513744adf58c34bcc4f43c
commit-date: 2021-09-21
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### Error output

```
thread 'rustc' panicked at 'attempted to read from stolen value', /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/compiler/rustc_data_structures/src/steal.rs:37:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (ac2d9fc50 2021-09-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C target-cpu=native --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [unsafety_check_result] unsafety-checking `attack::rapl::profiledecapsulation::options::<impl at /home/alexander/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/macros.rs:349:9: 356:10>::variants::{constant#0}`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `oqs-afw`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0:     0x7fb9de01651c - std::backtrace_rs::backtrace::libunwind::trace::h2ab374bc2a3b7023
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fb9de01651c - std::backtrace_rs::backtrace::trace_unsynchronized::h128cb5178b04dc46
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fb9de01651c - std::sys_common::backtrace::_print_fmt::h5344f9eefca2041f
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fb9de01651c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h213003bc5c7acf04
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fb9de0747dc - core::fmt::write::h78bf85fc3e93663f
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/core/src/fmt/mod.rs:1126:17
   5:     0x7fb9de007405 - std::io::Write::write_fmt::he619515c888f21a5
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/io/mod.rs:1667:15
   6:     0x7fb9de019a80 - std::sys_common::backtrace::_print::hf706674f77848203
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fb9de019a80 - std::sys_common::backtrace::print::hf0b6c7a88804ec56
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fb9de019a80 - std::panicking::default_hook::{{closure}}::h2dde766cd83a333a
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:210:50
   9:     0x7fb9de019637 - std::panicking::default_hook::h501e3b2e134eb149
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:227:9
  10:     0x7fb9de7fbe11 - rustc_driver::DEFAULT_HOOK::{{closure}}::{{closure}}::h8ff5de92123cb8fd
  11:     0x7fb9ccc34163 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hef4e78308da69372
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/alloc/src/boxed.rs:1650:9
  12:     0x7fb9ccc330cd - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h611e70ceecc8b723
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/proc_macro/src/bridge/client.rs:320:21
  13:     0x7fb9de01a299 - std::panicking::rust_panic_with_hook::hc09e869c4cf00885
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:628:17
  14:     0x7fb9de019d22 - std::panicking::begin_panic_handler::{{closure}}::hc2c6d70142458fc8
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:519:13
  15:     0x7fb9de0169c4 - std::sys_common::backtrace::__rust_end_short_backtrace::had58f7c459a1cd6e
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys_common/backtrace.rs:141:18
  16:     0x7fb9de019cb9 - rust_begin_unwind
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:517:5
  17:     0x7fb9ddfdf861 - core::panicking::panic_fmt::hf443e5eeb6cc9eab
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/core/src/panicking.rs:103:14
  18:     0x7fb9dfaccef1 - rustc_mir_transform::check_unsafety::unsafety_check_result::h2855d05d664d09ed
  19:     0x7fb9dfac89ca - core::ops::function::FnOnce::call_once::h3ce14a99508d3a8a
  20:     0x7fb9df161396 - rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps::h937ab00b40b06c46
  21:     0x7fb9e0900aaf - rustc_query_system::query::plumbing::try_load_from_disk_and_cache_in_memory::h94349bd7dfa11621
  22:     0x7fb9dff132bb - rustc_query_system::query::plumbing::try_execute_query::hab979f6c36b68b4b
  23:     0x7fb9dff7ca4f - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::unsafety_check_result::h267ac8e757c55ecb
  24:     0x7fb9dfacd3d0 - rustc_mir_transform::check_unsafety::check_unsafety::haadf2ef16c6d2871
  25:     0x7fb9df9cf15a - rustc_session::utils::<impl rustc_session::session::Session>::time::ha41db64aea0b06e5
  26:     0x7fb9e03b1900 - rustc_interface::passes::analysis::hb918b02982537851
  27:     0x7fb9e09b8a6f - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h347feb22cb0d1ecf
  28:     0x7fb9e095c539 - rustc_data_structures::stack::ensure_sufficient_stack::h4b6ffa4a2dfebaef
  29:     0x7fb9e08a0dbb - rustc_query_system::query::plumbing::try_execute_query::h784269645558384c
  30:     0x7fb9e09768d2 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::analysis::ha8ab0b7748e9a5d1
  31:     0x7fb9e03a8749 - rustc_interface::passes::QueryContext::enter::h805836b6c10e023c
  32:     0x7fb9e038f724 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::hded9061889acb733
  33:     0x7fb9e037ca45 - rustc_span::with_source_map::hce3a664e96079636
  34:     0x7fb9e038f04c - scoped_tls::ScopedKey<T>::set::h033dd5b45ac9d9cd
  35:     0x7fb9e037da7d - std::sys_common::backtrace::__rust_begin_short_backtrace::hc72d766e7b5b424b
  36:     0x7fb9e037b2e5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdbb85447b47f9f9d
  37:     0x7fb9de026e33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h59eef3b9c8a82350
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/alloc/src/boxed.rs:1636:9
  38:     0x7fb9de026e33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb5bbe017c347469c
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/alloc/src/boxed.rs:1636:9
  39:     0x7fb9de026e33 - std::sys::unix::thread::Thread::new::thread_start::h62931528f61e35f5
                               at /rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys/unix/thread.rs:106:17
  40:     0x7fb9ddf4c609 - start_thread
                               at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  41:     0x7fb9dde60293 - clone
  42:                0x0 - <unknown>
```

</p>
</details>

**Comment by LingMan** [comment] 2021-09-23 09:12
Looks like a duplicate of https://github.com/rust-lang/rust/issues/89178.

**Comment by kpreid** [comment] 2023-12-25 17:25
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by Noratrieb** [comment] 2024-11-09 21:15
An old issue without a reproduction, closing.

**Closed by Noratrieb** 2024-11-09 21:15 UTC
Labels: I-ICE, T-compiler, C-bug, S-needs-repro
