### ISSUE TITLE
Lang items are not checked for well-formedness

### ISSUE THREAD

**Issue by FabianWolff** [rust-lang/rust#86247] opened 2021-06-12 12:37 UTC
For instance, one can write:
```rust
#![feature(no_core)]
#![no_core]
#![feature(lang_items)]

#[lang = "sized"]
trait Sized {}

#[lang = "start"]
fn start() {}

fn main() {}
```
which leads to:
```
Incorrect number of arguments passed to called function!
  call void @_ZN10playground5start17h74a17c08fe33779bE(i8** bitcast (void ()* @_ZN10playground4main17ha7cb2a96f9beaebbE to i8**), i64 %4, i8** %1)
SExt only operates on integer
  %5 = sext void <badref> to i32
in function main
LLVM ERROR: Broken function found, compilation aborted!
error: could not compile `playground`
```
This can also cause ICEs (such as #83471, whose specific cause I have addressed in #86246 without solving the general problem), and it allows for all kinds of nonsensical lang items to be defined.

**Comment by jonas-schievink** [comment] 2021-06-12 12:46
duplicate of https://github.com/rust-lang/rust/issues/9307

**Closed by jonas-schievink** 2021-06-12 12:46 UTC

**Comment by FabianWolff** [comment] 2021-06-12 15:55
> duplicate of #9307

Thanks! I did search for existing issues, which turned up mostly ICEs, but apparently I did not go back far enough.
