### ISSUE TITLE
Backtrace filled with `<unknown>` for arm-linux-androideabi

### ISSUE THREAD

**Issue by marctrem** [rust-lang/rust#42889] opened 2017-06-25 07:48 UTC
Similar to #33985.

The same program built for x86_64 yields complete backtrace when meeting panic condition.

file 
```
ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, with debug_info, not stripped
```

cargo -vV
```
cargo 0.19.0 (28d1d60d4 2017-05-16)
release: 0.19.0
commit-hash: 28d1d60d4b634b70d7ceb0808144f2337c83ab95
commit-date: 2017-05-16
```

rustc -vV
```
rustc 1.18.0 (03fc9d622 2017-06-06)
binary: rustc
commit-hash: 03fc9d622e0ea26a3d37f5ab030737fcca6928b9
commit-date: 2017-06-06
host: x86_64-unknown-linux-gnu
release: 1.18.0
LLVM version: 3.9
```

arm-linux-androideabi-gcc --version (provided in the latest NDK)
```
arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)
```

***Edit 1***:

Same result with clang:

clang --version (provided in the latest NDK)
```
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: armv7a-none-linux-android
Thread model: posix
InstalledDir: /opt/android-tcs/v7a/bin
```

Backtrace:

```
101|dream2qltesq:/data/local/tmp $ RUST_BACKTRACE=1 ./r1                                          
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddrParseError(())', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
```

**Comment by roblabla** [comment] 2017-07-22 17:15
Duplicate of https://github.com/rust-lang/rust/issues/17520

**Comment by Mark-Simulacrum** [comment] 2017-07-22 17:16
Yep, closing as a duplicate. Thanks for filing!

**Closed by Mark-Simulacrum** 2017-07-22 17:16 UTC
Labels: O-android
