### ISSUE TITLE
Rustdoc paragraphs are sometimes individually scrollable

### ISSUE THREAD

**Issue by danielkeller** [rust-lang/rust#92400] opened 2021-12-29 11:40 UTC
On Firefox and MacOS, the individual paragraphs in item documentation sometimes scroll internally. This appears to happen when the cursor is on the top or bottom row of pixels of the paragraph, right where the cursor changes to a text cursor. If I remove the overflow-x: auto set on the paragraphs, the problem goes away.

**Comment by GuillaumeGomez** [comment] 2021-12-29 12:45
Do you have a URL so I can test it locally (and also a screenshot to see where precisely)?

**Comment by ehuss** [comment] 2022-01-14 19:53
I have bisected this to #88824.  There are a lot of rustdoc changes in that rollup, though.

It only seems to happen for me in Firefox (96.0.1).  It doesn't seem to happen in Safari or Chrome.

Here is a screen capture:

![rustdoc-scroll](https://user-images.githubusercontent.com/43198/149576640-46d13a48-ee6e-42e2-961a-4f45ac50bf13.gif)

**Comment by GuillaumeGomez** [comment] 2022-01-14 19:54
I see, thanks!

**Comment by ehuss** [comment] 2022-01-14 20:40
FWIW, this is possibly a Firefox bug.  I also notice this happening in the GitHub diff viewer.  I tried searching for an issue related to this, but I couldn't find one. However, I am not very familiar with Firefox issue tracking.

I also tried Firefox 98.0a1 (2022-01-14) nightly, and it is still happening.

It's hard to explain what triggers it. The mouse cursor has to be at certain positions, but I can't tell what is special about them.

**Comment by Funky185540** [comment] 2022-02-08 07:36
I noticed this behavior, too. I can reproduce it on:

- Firefox, version 96.0.3
- Tor, version 11.0.4 (based on Firefox 91.5.0esr)

It does not happen on:

- Epiphany, version 41.3 (i.e. GNOME Web)

Which makes a Bug in Firefox all the more likely.

**Comment by robjtede** [comment] 2022-02-08 07:49
I did notice this but it seems to be fixed in the latest nightly Firefox build. I can reproduce on stable Firefox on the `walkdir` page that @ehuss referenced but not on nightly.

Regardless, it can be prevented pretty easily with `overflow-y: hidden`.

**Comment by GuillaumeGomez** [comment] 2022-10-27 20:09
I can't reproduce it so I assume it was fixed. Please don't hesitate to reopen with an URL where it can be checked if it's not the case.

**Closed by GuillaumeGomez** 2022-10-27 20:09 UTC
Labels: T-rustdoc, C-bug, A-rustdoc-ui
