### ISSUE TITLE
Nightly regression in borrow checker

### ISSUE THREAD

**Issue by msullivan** [rust-lang/rust#28936] opened 2015-10-09 22:00 UTC
```
pub type Session = i32;
pub struct StreamParser<'a, T> {
    _tokens: T,
    _session: &'a mut Session,
}

impl<'a, T> StreamParser<'a, T> {
    pub fn thing(&mut self) -> bool { true }
}

pub fn parse_stream<T: Iterator<Item=i32>, U, F>(
        _session: &mut Session, _tokens: T, _f: F) -> U
    where F: Fn(&mut StreamParser<T>) -> U { panic!(); }

pub fn thing(session: &mut Session) {
    let mut stream = vec!(1, 2, 3).into_iter();

    let _b = parse_stream(session,
                          stream.by_ref(),
                          // replacing the above with the following fixes it
                          //&mut stream,
                          |p| p.thing());

}

fn main() {}
```
compiles on 1.3 stable and 1.4 beta but not on current nightly. It did compile on nightly 6e5a32547. Replacing the `.by_ref()` in the call to `parse_stream` fixes it.

Potentially related to/a dupe of #28934.

**Comment by msullivan** [comment] 2015-10-09 22:08
(Probably want these lables: A-lifetimes T-compiler regression-from-stable-to-nightly)

**Comment by alexcrichton** [comment] 2015-10-09 22:18
May be similar or the same as https://github.com/rust-lang/rust/issues/28853, https://github.com/rust-lang/rust/issues/28854, or https://github.com/rust-lang/rust/issues/28934, but seems good to track regardless!

**Comment by arielb1** [comment] 2015-10-10 12:37
This looks like a closure inference issue: annotating the closure type fixes it.

**Comment by nikomatsakis** [comment] 2015-10-14 22:41
I believe this was fixed by https://github.com/rust-lang/rust/pull/29006

**Comment by arielb1** [comment] 2015-10-15 20:10
This was indeed fixed by #29006.

**Comment by nikomatsakis** [comment] 2015-10-15 20:15
triage: P-medium

**Comment by nikomatsakis** [comment] 2015-10-15 20:15
triage: P-low

**Comment by nikomatsakis** [comment] 2015-10-20 14:21
Removing regression tag since the core issue is fixed.

**Closed** 2015-10-21 19:26 UTC
Labels: A-lifetimes, E-needstest, P-low, T-compiler
