### ISSUE TITLE
Rust generates bad debug info for panics

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#44465] opened 2017-09-09 20:47 UTC
We're getting crashes in webrender that look like this:

8 	XUL 	webrender::frame_builder::{{impl}}::build 	src/libcore/option.rs:0
However webrender::frame_builder::{{impl}}::build is not found at option.rs:0

In https://bugzilla.mozilla.org/show_bug.cgi?id=1398171 @luser elaborates the problem with debug info that rust is generating.

**Comment by Mark-Simulacrum** [comment] 2017-09-09 23:42
cc @michaelwoerister

**Comment by arielb1** [comment] 2017-11-20 19:57
So #46101 made me get into this, and it appears that at least that problem is caused by libbacktrace giving us the line-number of the `unreachable` instruction after the call, rather than the call itself:


```
        .loc    12 302 0
        leaq    str.k.llvm.133BC46B(%rip), %rdi
.Ltmp34:
        movl    $22, %esi
        callq   _ZN4core6option13expect_failed17hfad3c6cc869d0a50E@PLT
.Ltmp35:
        .loc    12 0 0 is_stmt 0
        ud2
```

**Comment by arielb1** [comment] 2017-11-20 22:18
So this is actually an LLVM bug that was apparently fixed in https://github.com/llvm-mirror/llvm/commit/5c088820badb6a40eb0f76ca52c52c90a7776e53 - a commit contained in LLVM 5.0. So this should be fixed when we upgrade to that.

That commit is somewhat big, so I'm not sure how safe it is to apply to 4.0.

**Comment by michaelwoerister** [comment] 2017-11-21 09:09
Thank you so much for investigating, @arielb1!

**Comment by steven-michaud** [comment] 2019-11-05 15:11
Did the upgrade to LLVM 5.0 happen? Did this bug get fixed?

**Comment by alecmocatta** [comment] 2019-11-05 15:22
@steven-michaud Rust's currently on LLVM 9.0

**Comment by steven-michaud** [comment] 2019-11-05 16:07
Thanks for the info. So this bug should have been fixed. Does anyone know if it was?

**Comment by pnkfelix** [comment] 2022-12-19 15:57
visiting for wg-debugging triage

closing; presumed fixed.

please reopen if you have evidence that this is still a problem

**Closed by pnkfelix** 2022-12-19 15:57 UTC
Labels: A-debuginfo, T-compiler, C-bug
