### ISSUE TITLE
Optimizing for size somehow doubles?

### ISSUE THREAD

**Issue by isiahmeadows** [rust-lang/rust#66725] opened 2019-11-25 00:09 UTC
I tried compiling a library optimizing for max speed and max size, using the latest nightly Godbolt uses.

- [`-C opt_level=3`](https://godbolt.org/z/h8-9M7): 5724 total, 587 with assembler directives stripped out
- [`-C opt_level=z`](https://godbolt.org/z/EpEwYv): 8961 total, 1192 with assembler directives stripped out

I got similar from using the latest stable, too, although I didn't check the numbers.

It seems a bit odd that optimizing for speed results in about half the code you'd get from optimizing for size in something somewhat non-trivial...

(This was in the middle of me toying around with a WIP proposal unrelated to Rust.)

**Comment by jonas-schievink** [comment] 2019-11-25 01:02
Duplicate of https://github.com/rust-lang/rust/issues/54026

**Closed by jonas-schievink** 2019-11-25 01:02 UTC
