### ISSUE TITLE
box_syntax allowed in generated function

### ISSUE THREAD

**Issue by mathall** [rust-lang/rust#20882] opened 2015-01-10 16:25 UTC
```rust
macro_rules! gen_test {
  () => (
    fn test() {
      println!("{}", box 1);
    }
  );
}

gen_test!();

fn main() {
  test();
  //println!("{}", box 1);  // error, requires #![feature(box_syntax)]
}
```

**Comment by sfackler** [comment] 2015-01-10 17:35
Dup of #20661

**Comment by mathall** [comment] 2015-01-10 18:05
I don't think that's a proper dup. My bad for not writing a truly minimal test case, I suppose.
```rust
macro_rules! gen_test {
  () => (
    fn test() {
      box 1;
    }
  );
}

gen_test!();

fn main() {
  test();
  //box 1;  // error, requires #![feature(box_syntax)]
}
```

**Comment by sfackler** [comment] 2015-01-10 18:40
Ah, sorry about that! Nominating.

**Comment by alexcrichton** [comment] 2015-01-11 04:51
While not a dupe of #20661, I think this is a dupe of https://github.com/rust-lang/rust/issues/12122

**Closed by alexcrichton** 2015-01-11 04:51 UTC
Labels: I-nominated
