### ISSUE TITLE
Internal Compiler Error logging in an async fn

### ISSUE THREAD

**Issue by fluffysquirrels** [rust-lang/rust#81638] opened 2021-02-01 19:48 UTC
### Code

```Rust
use log::error;

pub struct Foo {}

impl Foo {
    pub async fn bar(&self) {
        error!("ICE")
    }
}
```

`Cargo.toml`:
```
[dependencies]
log = "0.4.8"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (0e63af5da 2021-01-31)
binary: rustc
commit-hash: 0e63af5da3400ace48a0345117980473fd21ad73
commit-date: 2021-01-31
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
error: internal compiler error: failed to process buffered lint here
 --> src/lib.rs:7:9
  |
7 |         error!("ICE")
  |         ^^^^^^^^^^^^^
  |
  = note: delayed at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/compiler/rustc_lint/src/early.rs:384:18
  = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/0e63af5da3400ace48a0345117980473fd21ad73/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (0e63af5da 2021-01-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-01 19:53
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-01 19:53 UTC
Labels: C-bug, I-ICE, T-compiler
