### ISSUE TITLE
Impl trait in type aliases: defining use via struct

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#66980] opened 2019-12-03 08:33 UTC
Sub-issue of https://github.com/rust-lang/rust/issues/63063

It should be possible for the *defining implementation* of Type-Alias-Impl-Trait (aka TAIT) to be a struct usage:
```rust
#![feature(type_alias_impl_trait)]
type A = impl Drop;

struct S {
    a: A,
}

fn foo() -> S {
    S { a: Box::new(1) }
}
```

First issue: currently, non-defining uses of TAIT in the defining scope are not allowed; see [this comment](https://github.com/rust-lang/rust/issues/63063#issuecomment-556789645).

Second issue: defining usage via a struct field.

Related cases:

-   compound type aliases are already supported: `type B = (A, ());` where `A` is TAIT (also applies to array types)
-   `enum` usages usually (when N>1) do not involve all variants and often do not involve all type-components, so extension to `enum` would only be possible in very limited circumstances: [already supported for Option](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=80aa375ec0ed077caff9c1aff72a7a30) but [not other enums](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bb140f83c2c03435bd62251202f87f15)

**Comment by jackh726** [comment] 2021-02-04 00:09
Current errors on master:
```
error[E0308]: mismatched types
 --> src/main.rs:9:12
  |
2 | type A = impl Drop;
  |          --------- the expected opaque type
...
9 |     S { a: Box::new(1) }
  |            ^^^^^^^^^^^ expected opaque type, found struct `Box`
  |
  = note: expected opaque type `impl Drop`
                  found struct `Box<{integer}>`

error: could not find defining uses
 --> src/main.rs:2:10
  |
2 | type A = impl Drop;
  |          ^^^^^^^^^

error: aborting due to 2 previous errors
```

**Comment by oli-obk** [comment] 2021-02-19 15:25
This is a duplicate of https://github.com/rust-lang/rust/issues/64445

**Closed by oli-obk** 2021-02-19 15:25 UTC
Labels: F-type_alias_impl_trait, T-lang
