### ISSUE TITLE
cargo-profiler fails to compile on nightly 

### ISSUE THREAD

**Issue by isaacg1** [rust-lang/rust#43394] opened 2017-07-21 20:06 UTC
I tried to install [cargo-profiler](https://github.com/kernelmachine/cargo-profiler), and during the installation, rustc crashed.

I ran this in bash:

    cargo install cargo-profiler -f

and this was the output:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing cargo-profiler v0.1.6
   Compiling rawpointer v0.1.0
   Compiling regex-syntax v0.3.9
   Compiling winapi v0.2.8
   Compiling semver v0.1.20
   Compiling lazy_static v0.2.8
   Compiling unicode-segmentation v1.1.0
   Compiling strsim v0.6.0
   Compiling winapi-build v0.1.1
   Compiling unicode-width v0.1.4
   Compiling rustc-serialize v0.3.24
   Compiling vec_map v0.8.0
   Compiling itertools v0.4.19
warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> /home/isaac/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.19/src/lib.rs:123:1
    |
123 | pub type MapFn<I, B> where I: Iterator = iter::Map<I, fn(I::Item) -> B>;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling num-traits v0.1.40
   Compiling matrixmultiply v0.1.13
   Compiling ansi_term v0.9.0
   Compiling bitflags v0.9.1
   Compiling utf8-ranges v0.1.3
   Compiling libc v0.2.26
   Compiling rustc_version v0.1.7
   Compiling kernel32-sys v0.2.2
   Compiling num-complex v0.1.39
   Compiling atty v0.2.2
   Compiling memchr v0.1.11
   Compiling term_size v0.3.0
   Compiling ndarray v0.5.2
error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<K as kernel::GemmKernel>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (ae98ebfcb 2017-07-20) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:437:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `matrixmultiply`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-profiler v0.1.6`, intermediate artifacts can be found at `/tmp/cargo-install.YqoGra1CcPC0`

Caused by:
  build failed
```

## Meta:

`rustc --version --verbose`:

```
rustc 1.20.0-nightly (ae98ebfcb 2017-07-20)
binary: rustc
commit-hash: ae98ebfcb9ad5a5384fd229a6ee91315b02ca969
commit-date: 2017-07-20
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0
```

**Comment by SpaceManiac** [comment] 2017-07-22 07:00
Repro:
```rust
trait Foo {
    type Bar;
}
fn foo<T: Foo>() {
    std::mem::size_of::<T::Bar>();
}
fn main() {}
```

**Comment by Mark-Simulacrum** [comment] 2017-07-27 17:00
cc @eddyb -- I think this is a duplicate of the other similar bugs, right?

**Comment by Mark-Simulacrum** [comment] 2017-07-27 17:04
Closing as duplicate of https://github.com/rust-lang/rust/issues/43357#issuecomment-317189619.

**Closed by Mark-Simulacrum** 2017-07-27 17:04 UTC
Labels: C-bug, I-ICE, P-high, regression-from-stable-to-nightly, T-compiler
