### ISSUE TITLE
Conflict when implementing trait on associated  type

### ISSUE THREAD

**Issue by ilslv** [rust-lang/rust#89356] opened 2021-09-29 13:24 UTC
Given the following code:

```rust
// provider crate

pub struct Wrapper<T>(T);

pub trait Marker {}

pub trait Unpacked {
    type Inner;
}

impl<T: Marker> Unpacked for T {
    type Inner = T;
}

impl<T: Marker> Unpacked for Wrapper<T> {
    type Inner = T;
}
```

```rust
// another crate which depends on provider

use provider::{Marker, Unpacked, Wrapper};

struct Marked;

impl Marker for Marked {}

struct Into;

impl From<<Wrapper<Marked> as Unpacked>::Inner> for Into {
    fn from(_: <Wrapper<Marked> as Unpacked>::Inner) -> Self {
        Self
    }
}
```

The current output is:

```
error[E0119]: conflicting implementations of trait `std::convert::From<Into>` for type `Into`
 --> src/lib.rs:9:1
  |
9 | impl From<<Wrapper<Marked> as Unpacked>::Inner> for Into {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T> From<T> for T;
  = note: upstream crates may add a new impl of trait `provider::Marker` for type `provider::Wrapper<Marked>` in future versions
```

Basically I'm trying to work around not having specialisation by using `Wrapper` type: one behaviour for `Marker` implementors and second one for the `Wapper<T> where T: Marker`. Then I try to describe trait, which will `Unpack` `Wrapper` or resolve `Marker` itself. Everything is fine, until I try to use those traits in another crate.

I vaguely do understand, that compiler may look at `impl<T: Marker> Unpacked for T { .. }` blanket impl and figure out that `Marker` implementation theoretically may be added in the future. But clearly these can't be done because of already existing impl `impl<T: Marker> Unpacked for Wrapper<T> { .. }`. Is this an ok behaviour of the compiler or a bug? And if this is a valid error where I can find more info about restrictions?

**Comment by QuineDot** [comment] 2022-06-28 02:14
Dupe of #51445, at least at the surface level.

**Closed** 2022-06-28 04:39 UTC
