### ISSUE TITLE
Unhelpful compiler error message

### ISSUE THREAD

**Issue by hoo7i** [rust-lang/rust#37968] opened 2016-11-23 19:00 UTC
Minor issue, but confusing to someone new to Rust. Lets iterate over a borrowed vector:

```rust
fn example(vector_ref: &Vec<i64>) {

    for i in vector_ref {

        if i > 0 {

               println!("{}", i);

              }
}
```

Produces the following error message:
```
if i > 0 {
   |   ^ expected &i64, found integral variable
   |
   = note: expected type `&i64`
   = note:    found type `{integer}`
```

It's an obvious error, just de-reference: `*i > 0`. Or for extra weirdness ` i > &0` is an option.

Someone new to Rust wouldn't be crazy to assume that the iterator does that already, so I think this might be a common one for beginners as they start passing around vectors.

 The error points to 0, which isn't the problem here.

**Fix**: Ideally a note suggesting de-referencing `i` in these situations could be added, with error pointed at `i`.

**Comment by nagisa** [comment] 2016-11-23 23:38
Duplicate of https://github.com/rust-lang/rust/issues/34562

**Closed** 2016-11-24 06:33 UTC
Labels: A-diagnostics
