### ISSUE TITLE
regression 1.49: rustdoc runs indented documentation immediately after a header as a doctest

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#79911] opened 2020-12-10 18:49 UTC
* https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/gh/bes.google-datastore1-generated/log.txt

My guess is that rustdoc's behavior on parsing doc attributes has changed or something like that -- I recall seeing a PR changing how we handle things. Maybe for example previously \n in an attribute worked and now doesn't?

cc @rust-lang/rustdoc

**Comment by jyn514** [comment] 2020-12-10 18:52
Is there a way to see the full source for this? The error sounds like it's a doctest or something, not documentation directly.

**Comment by Mark-Simulacrum** [comment] 2020-12-10 18:55
It's a public repo, https://github.com/bes/google-datastore1-generated/blob/master/src/lib.rs#L1

**Comment by Mark-Simulacrum** [comment] 2020-12-10 19:04
https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/reg/auto-0.0.8/log.txt might also be related (that one is on crates.io)

**Comment by jyn514** [comment] 2020-12-10 19:10
The bug is that this is being interpreted as a doctest instead of normal documentation. Not sure why yet.

**Comment by Mark-Simulacrum** [comment] 2020-12-10 19:12
https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/reg/glutin-0.25.1/log.txt also seems to do the same

**Comment by jyn514** [comment] 2020-12-10 19:18
I think this was https://github.com/rust-lang/rust/pull/77519/commits/fa1b15f6279a95923b8a19046f45f27f243d49d2.

**Comment by jyn514** [comment] 2020-12-10 19:25
MCVE:

```rust
//!# Header
//!    x
```
Stable ignores it, beta runs `x` as a doctest.

**Comment by jyn514** [comment] 2020-12-10 19:26
For context,
```rust
//!# Header
//!
//!    x
```
*is* run on a doctest on stable. So maybe newlines are getting discarded somewhere?

**Comment by jyn514** [comment] 2020-12-10 20:17
```
searched toolchains nightly-2020-10-01 through nightly-2020-12-01


********************************************************************************
Regression in nightly-2020-11-05
********************************************************************************

fetching https://static.rust-lang.org/dist/2020-11-04/channel-rust-nightly-git-commit-hash.txt
ERROR: Tarball not found at https://static.rust-lang.org/dist/2020-11-04/channel-rust-nightly-git-commit-hash.txt
```
I confirmed locally that reverting https://github.com/rust-lang/rust/pull/78400/ fixes the issue.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment] 2020-12-10 20:46
It's because the header starts with `//!# Header`. Because there is no space before `//!`, everything is aligned to this, making `//!    x` a doctest because there are 4 spaces. So this is the expected behavior, it was just buggy before. :)

**Comment by rylev** [comment] 2020-12-10 22:23
@GuillaumeGomez can you clarify why this is expected behavior (not sure I fully follow your explanation above). This seems very unexpected to me.

**Comment by GuillaumeGomez** [comment] 2020-12-10 22:28
So I wrote a whole blog post explaining this change [here](https://blog.guillaume-gomez.fr/articles/2020-11-11+New+doc+comment+handling+in+rustdoc). TLDR:

Since the minimum indent is "0" because of `//!# Header` (where there is no whitespace before `#`), the line `//!    x` has an indent of 4, making it a code block based on the markdown spec.

If you don't want `x` to be a code block, add a whitespace before `# Header` or remove a whitespace from `//!    x`.

**Comment by Mark-Simulacrum** [comment] 2020-12-11 15:08
Will close as won't fix, but we should include in release notes.

**Comment by Mark-Simulacrum** [comment] 2020-12-18 17:41
@XAMPPRocky Can we add an entry to the 1.49 release notes for this issue? It sounds like roughly

* Leading whitespace is stripped more uniformly in documentation comments, which may change behavior. Read [this post](https://blog.guillaume-gomez.fr/articles/2020-11-11+New+doc+comment+handling+in+rustdoc) for more details.

**Comment by GuillaumeGomez** [comment] 2020-12-18 17:48
That'd be a good idea indeed!

**Comment by XAMPPRocky** [comment] 2020-12-20 15:07
Closing, as it's now in relnotes.

**Closed by XAMPPRocky** 2020-12-20 15:07 UTC
Labels: T-rustdoc, regression-from-stable-to-beta, relnotes
