### ISSUE TITLE
#[no_mangle] lint should be removed

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30811] opened 2016-01-10 16:48 UTC
The no_mangle lint warns when a private function has the no_mangle attribute. The assumption seems to be that no_mangle functions are only called from outside the current crate, but it is possible to call them from the same crate in an assembly block.

**Comment by mahkoh** [comment] 2016-01-10 17:05
It looks like private no_mangle function are removed when compiling with optimization. This is incorrect for the same reason.

**Comment by huonw** [comment] 2016-01-11 07:46
In terms of linkage, a non-public item in Rust is like a `static` item in C, there's no guarantees of it existing in any form other than the source (i.e. it can be compiled away completely). For example, this code fails to compile with `gcc -O`, because the `foo` symbol gets optimised out:

```c
static void foo() {}

int main() {
    asm("call foo");
    return 0;
}
```
```
/tmp/ccThqfOT.o: In function `main':                                                                    
static.c:(.text+0x1): undefined reference to `foo'                                                      
collect2: error: ld returned 1 exit status 
```

We won't want to change this for arbitrary items, but I guess I could imagine `#[no_mangle]` ensuring its item stays around. However that seems unfortunate to me, since, I believe, it would either mean all non-`pub` `#[no_mangle]`s are exposed as external symbols, or would mean symbols that should be exposed (e.g. writing a Rust library to be used in C) are not exposed, with no warning i.e. the problem this lint is trying to solve becomes effectively unsolvable. 

I would think that having an explicit `#[used]` ala https://github.com/rust-lang/rust/issues/30817 would be better. (FWIW, C++ doesn't do what you are implying is correct either: one just cannot have something that is both private (`static`) and `extern "C"`, so maybe Rust could also disallow `#[no_mangle]` on non-`pub` items.)

**Comment by huonw** [comment] 2016-01-18 11:21
Closing as not a bug, for the reasons mentioned above, but thanks for filing anyway.

**Closed by huonw** 2016-01-18 11:21 UTC
Labels: A-lint
