### ISSUE TITLE
File I/O routines should return the filename in error cases

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-lang/rust#82735] opened 2021-03-03 22:10 UTC
Excuse me if this has been asked 100 times before; I looked in the GH issues for a bit but couldn't come up with a relevant issue so feel free to close as a dupe.

I tried this code:

```rust
fn main() {
    std::fs::read("/etc/jasper").unwrap();
}
```

I expected to see this happen: 

I would /love/ to see the filename of the file or directory that was tried to access to be able to diagnose problems more easily

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
Os { code: 2, kind: NotFound, message: "No such file or directory: /etc/jasper" }', src/main.rs:2:34
```

Instead, this happened: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:2:34
```

This provides no relevant information, debugging information, and it's quite useless to an end-user as well.

**Comment by ehuss** [comment] 2021-03-03 23:26
Indeed it has been brought up quite a bit.  The most recent is https://github.com/rust-lang/rfcs/pull/3084 where there is plenty of discussion about the problems and tradeoffs here.  I think there are some crates on https://crates.io that provide wrappers, or you can roll your own.

**Comment by nagisa** [comment] 2021-03-04 01:08
Thank you. I'm going to close this as  a duplicate of the referenced RFC, since its proposing pretty much exactly this.

**Closed by nagisa** 2021-03-04 01:08 UTC
Labels: C-bug
