### ISSUE TITLE
ATC-like for<'a> Fn(<X as Trait<'a>>::Type) does not consistently normalize (and can ICE).

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#52812] opened 2018-07-28 19:09 UTC
([try on playground](http://play.rust-lang.org/?gist=fd0bbf89589d2d79beb3d68263a547d8&version=stable&mode=debug&edition=2015))
```rust
trait ATC<'a> {
    type Type: Sized;
}

trait WithDefault: for<'a> ATC<'a> {
    fn with_default<F: for<'a> Fn(<Self as ATC<'a>>::Type)>(f: F);
}

fn call<'b, T: for<'a> ATC<'a>, F: for<'a> Fn(<T as ATC<'a>>::Type)>(
    f: F,
    x: <T as ATC<'b>>::Type,
) {
    f(x);
}

impl<'a> ATC<'a> for () {
    type Type = Self;
}

impl WithDefault for () {
    fn with_default<F: for<'a> Fn(<Self as ATC<'a>>::Type)>(f: F) {
        // Errors with a bogus type mismatch.
        //f(());
        // Going through another generic function works fine.
        call(f, ());
    }
}

fn main() {
    // <()>::with_default(|_| {});
}
```

As you can see, calling `f` directly doesn't instantiate the HRTB (even though it *needs to* AFAIK) or if it does it doesn't normalize the resulting bound, whereas going through `call` normalizes the instantiated argument types of `call`, while `call`'s definition can be type-checked as-is.

**EDIT**: you can also get an ICE by uncommenting the use in `main`:
```rust
error: internal compiler error: librustc/traits/trans/mod.rs:68: Encountered error `OutputTypeParameterMismatch(
    Binder(<[closure@src/main.rs:30:24: 30:30] as std::ops::Fn<(<() as ATC<'_>>::Type,)>>),
    Binder(<[closure@src/main.rs:30:24: 30:30] as std::ops::Fn<((),)>>),
    Sorts(ExpectedFound { expected: (), found: <() as ATC<'_>>::Type })
)` selecting `Binder(<[closure@src/main.rs:30:24: 30:30] as std::ops::Fn<((),)>>)` during trans
```

cc @nikomatsakis (this *might* be a duplicate)

**Comment by earthengine** [comment] 2018-09-13 03:10
Duplicate of #53420 (at least the ICE case)?

**Comment by eddyb** [comment] 2018-11-03 12:10
This is a probably a duplicate of #29997 and/or #33364?

**Comment by pnkfelix** [comment] 2019-07-10 10:11
closing as duplicate of #62529, which is where I will try to track future instances of this field of ICE.

**Closed by pnkfelix** 2019-07-10 10:11 UTC
Labels: I-ICE
