### ISSUE TITLE
Two function generic type bounds creates nonsense

### ISSUE THREAD

**Issue by sanboxrunner** [rust-lang/rust#64701] opened 2019-09-23 05:33 UTC
This is rather silly --
```
pub fn poll_events<F: FnMut(Event)>(input_component: &mut Input, window: &mut Window, callback: F)
where
    F: FnMut(Event, &mut Window),
{
```
This function will compile except that no one can call it. If you only put in one parameter, it yells to have two, if you put in two, it yells to have one.

This doesn't seem like good behavior

**Comment by stephaneyfx** [comment] 2019-09-23 05:57
[This is possible to call it on nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6fa4720ff7adb9524d2b1604458642c9):
```rust
#![feature(fn_traits, unboxed_closures)]

struct A;
struct B;

// Equivalent to `fn foo<F>(_: F) where F: FnOnce(A) + FnOnce(A, B),`
fn foo<F: FnOnce(A)>(_: F)
where
    F: FnOnce(A, B),
{}

struct C;

impl FnOnce<(A,)> for C {
    type Output = ();
    extern "rust-call" fn call_once(self, _: (A,)) {}
}

impl FnOnce<(A, B)> for C {
    type Output = ();
    extern "rust-call" fn call_once(self, _: (A, B)) {}
}

fn main() {
    foo(C);
}
```

**Comment by jonas-schievink** [comment] 2019-09-23 10:12
This is expected behavior and can also be caused by using `Copy + Drop` as a bound. We could emit a lint for this, but new lints need to go through the RFC process, or should be added to Clippy instead, so closing.

**Closed by jonas-schievink** 2019-09-23 10:12 UTC
