### ISSUE TITLE
Methods from deref in rustdoc cause clashes in method anchors

### ISSUE THREAD

**Issue by netvl** [rust-lang/rust#25674] opened 2015-05-21 10:06 UTC
Example is [here](http://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html#method.new) - there is `new` method on `PathBuf` and `new` method on `Path` which is shown as if available through Deref.

If you click on `new()` in the Deref section, you will get to `new()` in the main impl section.

**Comment by steveklabnik** [comment] 2015-05-21 15:44
This issue got opened twice, closing in favor of N-1 :)

**Comment by netvl** [comment] 2015-05-22 07:53
Hmm, you don't mean #25673, do you? They are different.

**Comment by huonw** [comment] 2015-05-22 08:58
Oh, actually, closing as a dupe of https://github.com/rust-lang/rust/issues/25001 (thanks for filing!).

**Closed by huonw** 2015-05-22 08:58 UTC
Labels: A-rustdoc
