### ISSUE TITLE
regression: doctest failure display-as-0.4.4

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61562] opened 2019-06-05 21:28 UTC
* display-as-0.4.4: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-1/1.35.0/reg/display-as-0.4.4/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-1/beta-2019-05-30/reg/display-as-0.4.4/log.txt); cc @droundy

Behavior change from stable to beta but I have not investigated or tried to narrow down to anything more specific. Possibly a rustdoc problem (failure is in a doc test) so tagging with T-rustdoc.

**Comment by QuietMisdreavus** [comment] 2019-06-06 19:13
This is strange; it looks like the behavior for detecting doctests changed? What's the commit range for `stable...beta`? I don't remember any major changes to doctest detection, but i haven't looked into that yet.

```console
[misdreavus@tonberry display-as]$ cargo +stable test --doc                                                                                    [17/1140]
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
   Doc-tests display-as

running 8 tests
test src/lib.rs -  (line 113) ... ok
test src/lib.rs -  (line 149) ... ignored
test src/lib.rs -  (line 100) ... ok
test src/lib.rs -  (line 127) ... ok
test src/html.rs - display_floats_as (line 78) ... ok
test src/lib.rs -  (line 58) ... ok
test src/lib.rs -  (line 72) ... ok
test src/lib.rs -  (line 85) ... ok

test result: ok. 7 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

[misdreavus@tonberry display-as]$ cargo +local test --doc
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
   Doc-tests display-as

running 12 tests                                                                                                                                       test src/lib.rs -  (line 104) ... ok
test src/lib.rs -  (line 156) ... ignored                                                                                                              test src/lib.rs -  (line 178) ... ignored
test src/lib.rs -  (line 183) ... ignored
test src/lib.rs -  (line 188) ... ignored
test src/lib.rs -  (line 133) ... ok
test src/lib.rs -  (line 118) ... ok
test src/html.rs - display_floats_as (line 78) ... ok
test src/lib.rs -  (line 74) ... ok
test src/lib.rs -  (line 59) ... ok
test src/lib.rs -  (line 88) ... ok
test src/lib.rs -  (line 193) ... FAILED

failures:

---- src/lib.rs -  (line 193) stdout ----
thread 'src/lib.rs -  (line 193)' panicked at 'test executable failed:

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"<title>PH365: Templates</title>\n<html>\n  <ul><li><span class=\"student\">Name: David</span>\n\n</li><li><span class=\"student\">Name: Joel<
/span>\n\n</li></ul>\n</html>\n\n\n"`,
 right: `"<title>PH365: Templates</title>\n<html>\n  <ul>\n\n  // This is buggy:  I want to iterate, but it fails!\n  for s in self.students.iter() {\n
    \"<li>\" s \"</li>\"\n  }\n\n  </ul>\n</html>\n\n\n"`', src/lib.rs:18:1
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

', src/librustdoc/test.rs:342:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    src/lib.rs -  (line 193)

test result: FAILED. 7 passed; 1 failed; 4 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

The doctest in question (the one at the very end of the crate docs) seems like it's not being run at all on stable. When i extracted the doctest into a standalone crate, it failed in the same way when i built it with stable.

**Comment by QuietMisdreavus** [comment] 2019-06-06 19:56
It looks like this was caused by https://github.com/rust-lang/rust/pull/60140 giving pulldown the ability to detect more doctests. It looks like this doctest was accidentally ignored by the older version of pulldown, which the crate author didn't notice before publishing. (The repo also hasn't been touched after the new pulldown was enabled, which is probably why this wasn't noticed.)

@rust-lang/rustdoc Since this doesn't seem to have affected many crates, it's possible we can let this slide, but the alternative is we roll back the pulldown upgrade and have another warning period. Just like when we introduced pulldown in the first place.

**Comment by GuillaumeGomez** [comment] 2019-06-06 20:35
It's a fix so I wonder if this applies the same way...

**Comment by droundy** [comment] 2019-06-10 18:50
Any idea why it isn't being run in the stable compiler, and how I could fix that? The comment indicates that I expected a bug (it's vague in my memory) but I'd like to fix the test.

**Comment by QuietMisdreavus** [comment] 2019-06-10 19:09
@droundy It looks like the code blocks where you linked in the template files are empty when `--features docinclude` is missing, which might have confused rustdoc. I changed the `ignore` to `text` and stable rustdoc was able to skip past those and run the doctest at the end of the crate docs.

**Comment by pnkfelix** [comment] 2019-07-11 13:09
@Mark-Simulacrum does this need to be tagged T-compiler? Seems like a pure rustdoc issue to me, but maybe I misunderstand?

**Comment by jyn514** [comment] 2020-08-25 16:15
> It looks like this doctest was accidentally ignored by the older version of pulldown, which the crate author didn't notice before publishing.

So this isn't a bug in rustdoc at all, right? This is a bug that we fixed, and the failure was pre-existing?

**Comment by jyn514** [comment] 2020-11-12 02:09
> Any idea why it isn't being run in the stable compiler, and how I could fix that? The comment indicates that I expected a bug (it's vague in my memory) but I'd like to fix the test.

Since the change is fixing a bug and the backwards incompatible change landed almost 18 months ago, I'm going to close this.

**Closed by jyn514** 2020-11-12 02:09 UTC
Labels: A-doctests, T-rustdoc, regression-from-stable-to-stable
