### ISSUE TITLE
Regression in hexplay-0.1.3, Rust 1.16

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40957] opened 2017-03-31 17:17 UTC
https://github.com/tmoers/hexplay

```
101 brian@ip-10-145-43-250:~/dev/hexplay⟫ git log -1
commit 59e4473db3e80c17e7baa872daed1133bd1fd554
Author: Tom Moers <Tom Moers tmoers@users.noreply.github.com>
Date:   Sun Mar 5 20:24:19 2017 +0100

    [chore] Bump version to v0.1.4

```

```
brian@ip-10-145-43-250:/mnt2/dev/hexplay⟫ rustc +beta -Vv
rustc 1.17.0-beta.1 (408d49e60 2017-03-14)
binary: rustc
commit-hash: 408d49e6087f87371e96277c5ff428fa22cb84e6
commit-date: 2017-03-14
host: x86_64-unknown-linux-gnu
release: 1.17.0-beta.1
LLVM version: 3.9

```

```
brian@ip-10-145-43-250:~/dev/hexplay⟫ cargo +beta test
   Compiling hexplay v0.1.4 (file:///mnt2/dev/hexplay)
    Finished dev [unoptimized + debuginfo] target(s) in 1.78 secs
     Running target/debug/deps/hexplay-413e5547d6724b01

running 11 tests
test format::tests::a_full_line_is_formatted_as_expected ... ok
test format::tests::an_incomplete_line_is_padded_on_the_right ... ok
test format::tests::an_unaligned_address_causes_padded_on_the_left ... ok
test format::tests::all_characters_can_be_printed ... ok
test format::tests::an_unaligned_incomplete_line_causes_padding_on_both_sides ... ok
test format::tests::test_begin_padding ... ok
test format::tests::decreasing_the_row_width_increases_the_total_character_count ... FAILED
test format::tests::the_address_offset_increases_by_the_row_width_for_each_row ... ok
test format::tests::the_address_offset_is_used_when_given ... ok
test format::tests::the_address_offset_is_zero_by_default ... ok
test format::tests::the_row_width_is_16_by_default ... ok

failures:

---- format::tests::decreasing_the_row_width_increases_the_total_character_count stdout ----
        thread 'format::tests::decreasing_the_row_width_increases_the_total_character_count' panicked at 'a formatting trait implementation returned an error: Error', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    format::tests::decreasing_the_row_width_increases_the_total_character_count

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

cc @hexplay

**Comment by arielb1** [comment] 2017-04-04 16:59
Regression caused by #40117, seemingly intentionally.

**Comment by alexcrichton** [comment] 2017-04-12 22:05
Ok we discussed this during libs triage the other day, and the conclusion was to close this. The known regressions have been fixed and we'd otherwise categorize this under "known breakage".

If this comes up over time though please let us know as we're always interested in understanding when changes like this cause problems!

**Closed by alexcrichton** 2017-04-12 22:05 UTC
Labels: I-nominated, regression-from-stable-to-beta, T-libs
