### ISSUE TITLE
Assertion failed while type-casting

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#21073] opened 2015-01-13 01:49 UTC
While trying to write an offsetof that works in a constant expr, the compiler gets a low-level assertion failure.

```rust
struct Foo {
    a: u64,
    b: u32,
    c: u8
}

macro_rules! offset_of {
  ($t:ty, $field:ident) => {
    unsafe {
      (&(*(0 as *const $t)).$field) as *const _ as *const _
    }
  }
}

const OFFSET_OF_C: *const () = offset_of!(Foo, c);

fn main() {
  println!("offset of c: {}" , OFFSET_OF_C as usize);
}
```

With rust-nightly 201501120407~4bed1e8~trusty:
```
$rustc test.rs 
test.rs:2:5: 2:11 warning: struct field is never used: `a`, #[warn(dead_code)] on by default
test.rs:2     a: u64,
              ^~~~~~
test.rs:3:5: 3:11 warning: struct field is never used: `b`, #[warn(dead_code)] on by default
test.rs:3     b: u32,
              ^~~~~~
rustc: /build/buildd/rust-nightly-201501120407~4bed1e8~trusty/src/llvm/include/llvm/Support/Casting.h:237: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::GlobalVariable; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::GlobalVariable*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Aborted
```

Via @nathan7

**Comment by tamird** [comment] 2015-04-21 23:01
Triage: still ICEs. Reproduces without using macros:

```rust
struct Foo;

const OFFSET_OF_C: *const () = unsafe {
    &*(0 as *const Foo)as *const _ as *const _
};

fn main() {
    println!("offset of c {}" , OFFSET_OF_C as usize)
}
```

**Comment by IvanUkhov** [comment] 2015-05-18 15:59
[Here](http://is.gd/RRcc4J) is another example:

```rust
const TAG: &'static [u8] = b"ABCD";

macro_rules! tag(
    ($value:expr) => (unsafe {
        let value: [u8; 4] = ::std::mem::transmute($value);
        &vec![value[3], value[2], value[1], value[0]][..]
    })
);

fn main() {
    match tag!(42) {
        TAG => println!("Yes."),
        _ => println!("No."),
    }
}
```

```
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/llvm/include/llvm/Support/Casting.h, line 237.
```

Regards,
Ivan

**Comment by arielb1** [comment] 2015-07-08 21:01
Simpler:
```Rust
const TAG: &'static [u8] = b"ABCD";

fn main() {
    match unsafe {
        &::std::mem::transmute::<_,[u8; 4]>(42)[..]
    } {
        TAG => println!("Yes."),
        _ => println!("No."),
    }
}
```

**Comment by jethrogb** [comment] 2015-10-01 21:58
The first two examples no longer ICE. The last two still do (SIGILL on stable, LLVM assertion failed on nightly).

**Comment by jonas-schievink** [comment] 2016-06-09 22:37
Still ICEs on `rustc 1.11.0-nightly (34505e222 2016-06-08)`, but not with `-Zorbit`, so it looks like this will be fixed with MIR trans

**Comment by DemiMarie** [comment] 2016-08-02 05:34
Is this undefined behavior?

**Comment by steveklabnik** [comment] 2016-08-08 18:29
This ICE seems to be fixed on

```
rustc 1.12.0-nightly (b30eff7ba 2016-08-05)
```

I have a hunch that this is due to MIR being turned on, though I'm not sure. Please let me know if this still ICEs for you, but closing for now :confetti_ball:

**Closed by steveklabnik** 2016-08-08 18:29 UTC
Labels: A-llvm, I-ICE
