### ISSUE TITLE
rustdoc should hide stability information when crate doesn't use staged_api feature

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#24136] opened 2015-04-07 02:59 UTC
If a crate doesn't opt-in to the stability attributes feature (currently `staged_api`), i.e. most or all non-official crates, then stability information shouldn't be included in the crate's documentation. It's just taking up space (visual + disk) for those crates.

**Comment by alexcrichton** [comment] 2015-04-07 18:26
Closing as a dupe of #21674

**Closed by alexcrichton** 2015-04-07 18:26 UTC
