### ISSUE TITLE
regression: constants cannot refer to interior mutable data

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123281] opened 2024-03-31 17:09 UTC
```
[INFO] [stdout] error[E0492]: constants cannot refer to interior mutable data
[INFO] [stdout]    --> src/lib.rs:583:43
[INFO] [stdout]     |
[INFO] [stdout] 583 |     const VTABLE: &'static Self::VTable = &(*Lhs::VTABLE, *Rhs::VTABLE);
[INFO] [stdout]     |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this borrow of an interior mutable value may end up in the final value
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0492]: constants cannot refer to interior mutable data
[INFO] [stdout]    --> src/lib.rs:587:43
[INFO] [stdout]     |
[INFO] [stdout] 587 |     const VTABLE: &'static Self::VTable = &(*Lhs::VTABLE, *Rhs::VTABLE);
[INFO] [stdout]     |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this borrow of an interior mutable value may end up in the final value
[INFO] [stdout] 
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/equator-0.1.6/log.txt

**Comment by Nilstrieb** [comment] 2024-03-31 20:26
probably relevant to @oli-obk @RalfJung

**Comment by RalfJung** [comment] 2024-03-31 21:45
Yeah I think this is a duplicate of https://github.com/rust-lang/rust/issues/121250, which was filed by the author of the affected crate. Cc @sarah-ek

**Comment by RalfJung** [comment] 2024-03-31 21:46
This got FCP'd by t-lang as acceptable breakage [here](https://github.com/rust-lang/rust/issues/121250#issuecomment-1969425887).

**Comment by Mark-Simulacrum** [comment] 2024-03-31 21:48
Sounds good. I'll leave this open in case we decide to include some future-compat release note for it but untag for now.

**Comment by apiraino** [comment] 2024-04-02 12:31
I'll preemptively label this breaking change (see [prev. comment](https://github.com/rust-lang/rust/issues/123281#issuecomment-2028912812)) for release notes and nominate for T-lang to discuss if these changes should be mentioned in the release notes.

@rustbot label +relnotes +I-lang-nominated

**Comment by tmandry** [comment] 2024-05-01 17:56
We discussed this in the lang team meeting and agreed that we should mention it in the release notes, since it is a compatibility change that could affect someone.

@rustbot label -I-lang-nominated

**Comment by p-avital** [comment] 2024-05-02 16:56
> We discussed this in the lang team meeting and agreed that we should mention it in the release notes, since it is a compatibility change that could affect someone.
> 
> @rustbot label -I-lang-nominated

I confirm, `stabby` is impacted and not having `core::marker::Freeze` available means there's no way for me to fix it either :(

**Comment by RalfJung** [comment] 2024-05-02 17:23
Which versions of stabby are affected? Why did this not show up in crater?

**Comment by p-avital** [comment] 2024-05-02 17:28
> Which versions of stabby are affected? Any idea why did this not show up in crater?

All of them, but `stabby` would detect that it's being compiled in `nightly` and use `core::marker::Freeze` to be usable in `nightly`.

**Comment by RalfJung** [comment] 2024-05-02 17:31
Ah... it's bad practice to automatically use nightly features (Cc https://github.com/rust-lang/rust/issues/120804), and this is one example why.

**Comment by RalfJung** [comment] 2024-05-02 17:34
I don't know any work-arounds beyond what was discussed in https://github.com/rust-lang/rust/issues/121250 (adding  indirections to avoid reborrowing unknown data). This used to work by accident (we never wanted code like yours to compile), and we fixed that accident. `Freeze` is the intended way to be able to write such code in the future.

**Comment by p-avital** [comment] 2024-05-02 17:36
Yeah, I was a bit overly optimistic about this fix being stabilized in a similar timeframe to `core::marker::Freeze`... Any ETA on that one?

**Comment by RalfJung** [comment] 2024-05-02 17:39
We don't really have ETAs for nightly features. I currently don't have the capacity to try and push for this feature. No blocking concerns are listed but also this wasn't really widely discussed, so it's possible that there should be an RFC first.

**Comment by p-avital** [comment] 2024-05-02 17:40
Doesn't crater also run on `beta`? I was hoping this would let `crater` catch it when the time would come, since `beta` disables nightly features.

**Comment by RalfJung** [comment] 2024-05-02 17:42
I don't know how the beta crater runs are done, but stabby doesn't show up in https://crater-reports.s3.amazonaws.com/beta-1.78-3/index.html.

**Comment by p-avital** [comment] 2024-05-02 17:55
I was just gonna report that `stabby` indeed doesn't build on `beta`.

So `crater` ran on an obsolete version of `stabby` (which predated the `u128` ABI change), that explains why it didn't show up as regression :(

**Comment by RalfJung** [comment] 2024-05-02 18:01
Yeah no idea why crater picked up stabby-abi 2.0.1. I can't even find stabby itself.

**Comment by p-avital** [comment] 2024-05-02 18:01
Could be because `stabby` depends on `stabby-abi`, so if the later doesn't compile, no use checking the former?

**Comment by RalfJung** [comment] 2024-05-02 18:02
```
    {
      "name": "stabby-2.0.1",
      "url": "https://crates.io/crates/stabby/2.0.1",
      "krate": {
        "Registry": {
          "name": "stabby",
          "version": "2.0.1"
        }
      },
      "status": "",
      "res": "skipped",
      "runs": [
        null,
        null
      ]
    },
```
Looks like it.

**Comment by p-avital** [comment] 2024-05-02 23:03
Well, I'm gonna work around it with a static map of vtables. It's not ideal because it'll make any construction of a new trait object search/insert the corresponding vtable in a set, but it'll do until `core::marker::Freeze` gets stabilized.

**Comment by apiraino** [comment] 2024-10-15 09:00
Closing since regression is mentioned in the release notes

**Closed by apiraino** 2024-10-15 09:00 UTC
Labels: T-lang, T-compiler, relnotes, regression-from-stable-to-stable, A-const-eval
