### ISSUE TITLE
Docs: & in colored method signatures not rendered correctly on chrome in windows 10

### ISSUE THREAD

**Issue by mschwaig** [rust-lang/rust#27589] opened 2015-08-07 23:17 UTC
When rendering [the documentation to any standard library class](https://doc.rust-lang.org/std/collections/struct.LinkedList.html) with Chrome Version 44.0.2403.130 m (64-bit) - the latest release on Windows 10, the & character is obviously not rendered correctly, as demonstrated by [this picture](http://imgur.com/RsVvnJg).

Is there any more information I can provide to help fix this issue?

**Comment by mschwaig** [comment] 2015-08-07 23:20
Sorry I think this belongs in the website project. I will close this, and open an issue there instead.

**Comment by steveklabnik** [comment] 2015-08-08 01:06
Nope, this repo is correct! `doc.rust-lang.org` is generated from `src/doc` in this repo.

Also, wow, yeah, that's.... bad.

**Comment by steveklabnik** [comment] 2015-08-08 01:06
You may want to try uninstalling and reinstalling that web font, I wonder if it got corrupted.

**Comment by mschwaig** [comment] 2015-08-08 01:31
I don't know how to reinstall a web font, can you point me towards some information so I can try that?
I was able to reproduce the issue on a different PC with Windows 8.1 and the same Version of Chrome.

**Comment by steveklabnik** [comment] 2015-08-08 03:16
I don't use Windows, so I'm not sure. Maybe someone else will have an idea.

**Comment by ericye16** [comment] 2015-08-08 05:13
Works for me.

![image](https://cloud.githubusercontent.com/assets/1618487/9149173/a4d8c538-3d6a-11e5-90cb-8eba27ffdadf.png)

Also Windows 10, chrome 44.0.2403.130 m

**Comment by Eljay** [comment] 2015-08-08 07:47
Duplicate of #24355.

**Comment by retep998** [comment] 2015-08-10 02:20
Also duplicate of https://github.com/rust-lang/rust/issues/16372

**Comment by steveklabnik** [comment] 2016-02-01 20:44
Closing as it's a duplicate, as @Eljay mentions

**Closed by steveklabnik** 2016-02-01 20:44 UTC
Labels: A-rustdoc
