### ISSUE TITLE
Assertion in rustc nightly rustc 1.13.0-nightly (91f057de3 2016-09-04)

### ISSUE THREAD

**Issue by norru** [rust-lang/rust#36297] opened 2016-09-06 14:26 UTC
```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:263: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```
Repro steps:
- get nightly 1.13.0-nightly (91f057de3 2016-09-04) via rustup
- Clone rust-oids at the following tag: https://github.com/itadinanta/rust-oids/tree/tags/rustc_issue_36297
- ```rustup run nightly cargo build```

**Comment by TimNN** [comment] 2016-09-06 19:03
First occurs in `nightly-2016-08-03` which turns on mir by default, does not occure on `nightly-2016-08-03` with `-Z orbit=off`.

**Comment by TimNN** [comment] 2016-09-06 19:04
Duplicate of #35546 I believe.

**Comment by brson** [comment] 2016-09-07 22:48
Closing in favor of #35546

**Closed** 2016-09-07 22:48 UTC
