### ISSUE TITLE
Bootstrap deletes the sysroot directory when alternating between check and build, breaking --keep-stage

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/rust#52565] opened 2018-07-20 12:59 UTC
If I run `x.py build` without `--keep-stage` or `--stage` and then in subsequent builds use only `--keep-stage 0` then bootstrap runs as expected. 

However, it seems though that if I switch to using `x.py check` (still with `--keep-stage 0`) then any subsequent `x.py build`s with `--keep-stage 0` will fail with the below error unless I do a full build without `--keep-stage 0` again.

```
thread 'main' panicked at 'File::open(stamp) failed with No such file or directory (os error 2)', bootstrap/lib.rs:1109:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by jyn514** [comment] 2023-05-24 21:17
I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/34279, which has some more discussion.

**Closed by jyn514** 2023-05-24 21:17 UTC
Labels: T-bootstrap
