### ISSUE TITLE
Syntax needed to disambiguate associated types in trait object bounds

### ISSUE THREAD

**Issue by zombiezen** [rust-lang/rust#48822] opened 2018-03-07 16:33 UTC
Context: https://stackoverflow.com/questions/49143625/how-to-disambiguate-associated-types-in-trait-object-bounds

While [fully qualified syntax](https://doc.rust-lang.org/book/second-edition/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation) allows me to disambiguate associated types in parameter and return types, I can't seem to use it for disambiguating associated types in trait object bounds.  This came up while I tried to use a boxed [`IEvent`](https://docs.rs/stdweb/*/stdweb/traits/trait.IEvent.html) from `stdweb`, which has supertraits of `TryFrom<Value>` and `TryFrom<Reference>`.  For example, with the following code:

```rust
use stdweb::private::ConversionError;
use stdweb::web::event::IEvent;

struct Foo {
    bar: Box<IEvent<Error = ConversionError>>,
}
```

I get an error like:

```
error[E0221]: ambiguous associated type `Error` in bounds of `stdweb::traits::IEvent`
 --> src/main.rs:7:21
  |
7 |     bar: Box<IEvent<Error = ConversionError>>,
  |                     ^^^^^^^^^^^^^^^^^^^^^^^ ambiguous associated type `Error`
  |
note: associated type `stdweb::traits::IEvent` could derive from `stdweb::unstable::TryFrom<stdweb::Reference>`
 --> src/main.rs:7:21
  |
7 |     bar: Box<IEvent<Error = ConversionError>>,
  |                     ^^^^^^^^^^^^^^^^^^^^^^^
note: associated type `stdweb::traits::IEvent` could derive from `stdweb::unstable::TryFrom<stdweb::Value>`
 --> src/main.rs:7:21
  |
7 |     bar: Box<IEvent<Error = ConversionError>>,
  |                     ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0221"
```

I would expect to be able to disambiguate it with something like:

```rust
use stdweb::{Reference, Value};
use stdweb::private::ConversionError;
use stdweb::unstable::TryFrom;
use stdweb::web::event::IEvent;

struct Foo {
    bar: Box<IEvent<<<IEvent as TryFrom<Reference>>::Error = ConversionError, <IEvent as TryFrom<Value>>::Error = ConversionError>>,
}
```

But this emits a syntax error:

```
error: expected one of `(`, `::`, `<`, `>`, or `as`, found `=`
 --> src/main.rs:9:60
  |
9 |     bar: Box<IEvent<<<IEvent as TryFrom<Reference>>::Error = ConversionError, <IEvent as TryFrom<Value>>::Error = ConversionError>>,
  |                                                            ^ expected one of `(`, `::`, `<`, `>`, or `as` here
```

## Meta

`rustc --version --verbose`:

```
rustc 1.26.0-nightly (2789b067d 2018-03-06)
binary: rustc
commit-hash: 2789b067da2ac921b86199bde21dd231ace1da39
commit-date: 2018-03-06
host: x86_64-apple-darwin
release: 1.26.0-nightly
LLVM version: 6.0
```

**Comment by zombiezen** [comment] 2018-03-07 23:28
Also, to be clear: this makes it impossible for me to store an `IEvent` in a `Box`.

**Comment by oli-obk** [comment] 2018-03-08 07:57
minimal repro:

```rust
trait Foo {
    type Error;
}

trait Bar {
    type Error;
}

trait Cake : Foo + Bar {}

struct S {
    f: Box<Cake<Error = i32>>,
}

fn main() {
}
```

**Comment by syntacticsugarglider** [comment] 2020-05-01 18:20
This seems to be a duplicate of #48285. Moreover, has there been any momentum on this since filing? I see that it's marked WG-compiler-traits but there's no further discussion here and this issue has been around for a couple years at this point.

**Comment by oli-obk** [comment] 2020-05-02 06:27
duplicate of #48285

**Closed by oli-obk** 2020-05-02 06:27 UTC
Labels: A-associated-items, A-traits, A-typesystem, C-enhancement, T-lang, WG-compiler-traits
