### ISSUE TITLE
VS debugging and missing u8/i8

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#40407] opened 2017-03-10 01:50 UTC
I've been working through a better way to visualise Rust std lib structs in the VS debugger, and I noticed that u8 and i8 values currently don't show up in the debugger.  We seem to work fine for values of i16 or u32, so it seems specific to u8 and i8.

I'm guessing that they're just not making it to the pdb, but I'm not sure.

**Comment by retep998** [comment] 2017-03-10 03:10
Duplicate of https://github.com/rust-lang/rust/issues/36646

**Closed by retep998** 2017-03-10 03:10 UTC
