### ISSUE TITLE
regression: unaligned references to packed fields are now an error

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#109745] opened 2023-03-30 00:26 UTC
This is an expected strengthening of a future compatibility lint, mostly filing an issue for tracking purposes (i.e., release notes). I believe no action is expected.

* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/Adam-Gleave.multiboot2-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/ColonelPhantom.fe_chess/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/NilSet.dnsclient/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/Olangu.bindgen-bug/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/SevenCubedLabs._64_gfx/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/SheSnake.game_client/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/TomBebb.looa/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/chengzhycn.rself/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/coeuvre.handmade-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/ctsrc.persistence/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/evan-brass.osu-graphics/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/focus-zhaos.UringForStratoVirt/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/ican2002.stratorvirt/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/jthornber.lvm-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/mars-research.binunpack-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/mataha.gunz-replay/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/mickvangelderen.fins-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/mrandri19.opengl-compute-shaders/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/nishalkulkarni.btrfs-walk-tut/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/numerodix.pcitools/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/project-serum.governance-registry/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/pudh4418.udfstd/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/rbreslow.jpi-parser/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/svenslaggare.stackjit-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/tlent.learn-opengl-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/tyler569.tcp/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/gh/vbendeb.exifgeo/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/SOEM-sys-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/aeron-rs-0.1.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/apricot-client-0.15.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/autd3-soem-link-1.10.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/bebop-2.4.9/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/blake2b-rs-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/brash-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/btrfs-1.2.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/btrfs2-1.2.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/dbs-utils-0.2.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/ejdb-sys-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/elrond-1.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/wavetable-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/vuk-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/vec-2-10-10-10-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/v4l2-sys-1.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/v4l2-sys-mit-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/usrsctp-sys-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/usb-host-0.1.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/uhid-virt-0.0.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/uhid-sys-1.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/uhid-fs-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/uefi-ffi-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/typeinfo-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/tokio-linux-uhid-0.3.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/tmux_plugin-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/sprint-dir-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/solo5-sys-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/simple_bitfield-0.1.8/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/rplidar_drv-0.6.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/rdisk_shared-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/pfctl-0.4.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/elrond-1.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/enet-sys-1.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/ethercat-soem-sys-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/evoke-core-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/freeimage-0.2.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/gjio-0.1.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/hactool-sys-0.4.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/hdf5-derive-0.8.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/hydrogen-0.1.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/iwlib_sys-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/j2534-0.3.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/libdvb-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/lightway-sys-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/linux-loader-0.8.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/linux-nvme-sys-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/lwext4-sys-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/nfq-0.2.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/pe-0.1.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/persistence-0.0.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.69-3/beta-2023-03-18/reg/pfctl-0.4.5/log.txt

**Comment by apiraino** [comment] 2023-03-30 11:09
ok, then I will remove the I-prioritize flag, too. IIUC, these changes will be in the release notes and crates will need to adapt to the new lints

@rustbot  label -I-prioritize

**Comment by glandium** [comment] 2023-04-05 05:51
Having hit this one in https://github.com/mozilla/authenticator-rs/blob/abde4645a4711e29f1a481802776d5079c559eb1/src/windows/winapi.rs#L224, I'm wondering if this new error is not too restrictive.
Here is a smaller testcase that is not x86 windows specific:
```
#[repr(packed)]
pub struct Foo {
    a: usize,
    b: [u16; 1],
}

pub fn foo(f: &Foo) {
    bar(f.b.as_ptr());
}

pub fn bar(_ptr: *const u16) {}
```
How can accessing the `b` field ever be unaligned?

**Comment by Mark-Simulacrum** [comment] 2023-04-05 06:13
Cc @RalfJung @rust-lang/lang (also nominated for lang discussion; this will hit stable in ~2 weeks)

FWIW it seems like that example is a little misleading, the as_ptr call takes &self, so just &f.b as the argument is equivalent.

repr(packed) doesn't alter field reordering by itself I think (and the [reference](https://doc.rust-lang.org/reference/type-layout.html#the-alignment-modifiers)  seems to agree), so the [u16; 1] could be at the front of the struct.

But adding repr(C) doesn't prevent the error, and I think with that this would only be unaligned on 8-bit platforms (which I'm not sure we support; I'm also not sure if this error is target specific, I assume so). My guess is that the implementation isn't trying to be smart about this, just always errors on any field with lowered alignment requirements as a result of packed.

**Comment by glandium** [comment] 2023-04-05 06:23
> so just &f.b as the argument is equivalent.

it's actually not, because bar takes a `*const u16`, and `&f.b` is a `[u16; 1]`. `.as_ptr()` returns a `*const u16` (per https://doc.rust-lang.org/std/primitive.slice.html#method.as_ptr)

FWIW the original error happens on x86 windows only because that's windows specific code, and only x86 has repr(packed) on the relevant struct. It also does have a `#[repr(C)]` that was hidden in a macro in winapi, which I had missed.

**Comment by Mark-Simulacrum** [comment] 2023-04-05 06:34
The return type doesn't seem relevant? as_ptr has &self, so for the purposes of the error what happens after that doesn't matter; bar isn't relevant. (It would change the type of the expression to move to &, and stop compiling if that's the only change made)

**Comment by scottmcm** [comment] 2023-04-05 06:46
> How can accessing the `b` field ever be unaligned?

I'm not following what you mean by this example.

I switched the `&` to `addr_of` to make it compile, put a read of the pointer in `bar` as a way to test alignment, then wrote some basic entirely safe code to demonstrate that it absolutely can end up unaligned:
```rust
error: Undefined Behavior: accessing memory with alignment 1, but alignment 2 is required
  --> src/main.rs:13:14
   |
13 |     unsafe { ptr.read() };
   |              ^^^^^^^^^^ accessing memory with alignment 1, but alignment 2 is required
```
<https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=246744a5d3066b205afeb097bbcf053e>

**Comment by glandium** [comment] 2023-04-05 06:52
> The return type doesn't seem relevant? as_ptr has &self, so for the purposes of the error what happens after that doesn't matter; bar isn't relevant. (It would change the type of the expression to move to &, and stop compiling if that's the only change made)

Sure, for E0793, the return type is irrelevant.



> > How can accessing the `b` field ever be unaligned?
> 
> I'm not following what you mean by this example.
> 
> I switched the `&` to `addr_of` to make it compile, put a read of the pointer in `bar` as a way to test alignment, then wrote some basic entirely safe code to demonstrate that it absolutely can end up unaligned:
> 
> ```rust
> error: Undefined Behavior: accessing memory with alignment 1, but alignment 2 is required
>   --> src/main.rs:13:14
>    |
> 13 |     unsafe { ptr.read() };
>    |              ^^^^^^^^^^ accessing memory with alignment 1, but alignment 2 is required
> ```
> 
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=246744a5d3066b205afeb097bbcf053e

Add `repr(C)` to the struct as mentioned in the more recent messages.

**Comment by glandium** [comment] 2023-04-05 06:53
Interestingly, miri doesn't barf if you use `addr_of!(f.b[0])`.

**Comment by scottmcm** [comment] 2023-04-05 06:55
> Add `repr(C)` to the struct as mentioned in the more recent messages.

Can you give a playground link with *exactly* what you mean?  I added `repr(C)` to `Foo` and it's still unaligned: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2b904e588e84c7eee280194f56766c57>

**Comment by JakobDegen** [comment] 2023-04-05 07:02
@glandium in this example:

```rust
#[repr(packed)]
pub struct Foo {
    a: usize,
    b: [u16; 1],
}

pub fn foo(f: &Foo) {
    bar(f.b.as_ptr());
}

pub fn bar(_ptr: *const u16) {}
```

The alignment of `Foo` is 1. This might be a bit counterintuitive since it's not how alignment usually works. If you make the alignment 8 then you indeed [don't get an error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b27afc555d7f5fcc8c665fd6a55f7d27).

```rust
#[repr(packed(8))]
pub struct Foo {
    a: usize,
    b: [u16; 1],
}

pub fn foo(f: &Foo) {
    bar(f.b.as_ptr());
}

pub fn bar(_ptr: *const u16) {}
```

**Comment by glandium** [comment] 2023-04-05 07:02
I might have hit the wrong button. I see what's going on in your example. It's actually surprising that repr(packed) also means repr(align(1)). Considering that, yes, E0793 is unfortunately right...

**Comment by RalfJung** [comment] 2023-04-06 01:54
Wow that's a long list of regressions, in particular given that we did a crater run before ramping up the warning to an error.

> It's actually surprising that repr(packed) also means repr(align(1)). 

I agree, but this has been the case since Rust 1.0. AFAIK this is to be compatible with the corresponding annotation provided by C compilers.

**Comment by tmandry** [comment] 2023-04-11 19:08
@rust-lang/lang team [discussed](https://hackmd.io/WdsnQgNFRKSsAjAsqQW7BA?both#%E2%80%9Cregression-unaligned-references-to-packed-fields-are-now-an-error%E2%80%9D-rust109745).

We don't have blocking concerns and trust the people involved in this that it's time to ship: from what we could tell, the future incompat lint has been around for over 2 years, and the original issue was from 2015, and it's a deny-by-default lint on stable. (In the future, we'd prefer to have links to the relevant history for nominated issues like this.) The breaking changes are justified by this and the fact that the code was already UB anyway.

**Comment by RalfJung** [comment] 2024-04-25 05:51
There's nothing actionable here as far as I can tell, and the regressions are an expected part of fixing the soundness bug. Thus, closing.

**Closed by RalfJung** 2024-04-25 05:51 UTC
Labels: T-compiler, regression-from-stable-to-stable
