### ISSUE TITLE
tests/ui/lifetimes/issue-95023.rs fails on PowerPC systems because of `B` type in AltiVec

### ISSUE THREAD

**Issue by awilfox** [rust-lang/rust#128447] opened 2024-07-31 17:25 UTC
I tried this code:

```rust
python3 x.py test -j 64 tests/ui
```

I expected to see this happen: all tests to pass.

Instead, this happened:

```
diff of stderr:

54	  --> $DIR/issue-95023.rs:8:44
55	   |
56	LL |     fn foo<const N: usize>(&self) -> Self::B<{ N }>;
-	   |                                            ^ help: `Self` has the following associated type: `Output`
+	   |                                            ^ there is an associated type `B` in the trait `core::core_arch::powerpc::altivec::sealed::VectorRl`
58	
59	error: aborting due to 7 previous errors
60	
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (249cf71f1 2024-07-30) (Adélie 1.82.0 EXPERIMENTAL)
binary: rustc
commit-hash: 249cf71f11a29b3fb68e8a35969569d8bb7958ee
commit-date: 2024-07-30
host: powerpc64-foxkit-linux-musl
release: 1.82.0-nightly
LLVM version: 18.1.8
```

**Comment by Thewsthews** [comment] 2024-07-31 17:37
Perhaps there is a mismatch between the associated tupe and whats actually defined

**Comment by tgross35** [comment] 2024-07-31 17:56
Could you post your system info and the current commit of `rust-lang/rust` you are working from? We test ppc in CI so it seems unusual that something like this would happen.

**Comment by Thewsthews** [comment] 2024-07-31 18:11
Currently not working from any commit
I thought maybe that could be the problem just from a point of view

**Comment by tgross35** [comment] 2024-07-31 18:21
It looks like this is a duplicate of https://github.com/rust-lang/rust/issues/126260. Thanks for the report, feel free to follow up on that issue.

**Closed by tgross35** 2024-07-31 18:21 UTC
Labels: C-bug, needs-triage
