### ISSUE TITLE
Rustdoc: incorrect item indentation in trait declaration

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#61617] opened 2019-06-07 11:20 UTC
For example, in the [docs for `Sub`](https://doc.rust-lang.org/std/ops/trait.Sub.html):

<img width="1005" alt="Screen Shot 2019-06-07 at 7 18 44 AM" src="https://user-images.githubusercontent.com/831192/59100589-88cc5100-88f4-11e9-8ef9-8c5a7ea33232.png">

`Sub::sub()` is not correctly indented.

**Comment by GuillaumeGomez** [comment] 2019-06-11 17:41
This is a duplicate of #60042 and was fixed by #60093. It's not stable yet though. Closing it then.

**Closed by GuillaumeGomez** 2019-06-11 17:41 UTC
Labels: C-bug, T-rustdoc
