### ISSUE TITLE
error: internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by epandurski** [rust-lang/rust#34548] opened 2016-06-29 13:48 UTC
I use rustc 1.9.0 (e4e8b6668 2016-05-18)

Trying to compile gives me this:
``` 
$ RUST_BACKTRACE=1 cargo build --verbose
       Fresh winapi v0.2.7
       Fresh lazy_static v0.2.1
       Fresh libc v0.2.11
       Fresh regex-syntax v0.3.3
       Fresh memchr v0.1.11
       Fresh rand v0.3.14
       Fresh aho-corasick v0.5.2
       Fresh utf8-ranges v0.1.3
       Fresh winapi-build v0.1.1
       Fresh kernel32-sys v0.2.2
       Fresh thread-id v2.0.0
       Fresh thread_local v0.2.6
       Fresh regex v0.1.71
   Compiling alcibiades v0.1.0 (file:///home/evgeni/src/alcibiades)
     Running `rustc src/main.rs --crate-name alcibiades --crate-type bin -g --out-dir /home/evgeni/src/alcibiades/target/debug --emit=dep-info,link -L dependency=/home/evgeni/src/alcibiades/target/debug -L dependency=/home/evgeni/src/alcibiades/target/debug/deps --extern rand=/home/evgeni/src/alcibiades/target/debug/deps/librand-c724acb3942597d1.rlib --extern lazy_static=/home/evgeni/src/alcibiades/target/debug/deps/liblazy_static-a81b08a56ec46bff.rlib --extern regex=/home/evgeni/src/alcibiades/target/debug/deps/libregex-a3ad4db16bc20e1f.rlib`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'index out of bounds: the len is 68 but the index is 70', ../src/libcollections/vec.rs:1166
stack backtrace:
   1:     0x7fcf9640c570 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7fcf96419c6b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7fcf9641980c - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7fcf963de79f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7fcf963e0888 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7fcf96409d81 - rust_begin_unwind
   7:     0x7fcf9646385f - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7fcf96463a42 - core::panicking::panic_bounds_check::hc30e971884568c27
   9:     0x7fcf9093b77d - _<rustc_data_structures..unify..UnificationTable<K>>::get::he21ecf90e8e4f73a
  10:     0x7fcf908d1590 - rustc::infer::InferCtxt::shallow_resolve::he47cdea6677f40d2
  11:     0x7fcf90a32a60 - rustc::traits::fulfill::process_predicate::h8bbef05b37cf149a
  12:     0x7fcf90a317d7 - _<rustc_data_structures..obligation_forest..ObligationForest<O, T>>::process_obligations::h824becaa5c013776
  13:     0x7fcf90a2cdff - rustc::traits::fulfill::FulfillmentContext::select_where_possible::hf3fc6484c301b5bb
  14:     0x7fcf916a6e41 - rustc_typeck::check::FnCtxt::select_obligations_where_possible::h623b6ae6ad660b2d
  15:     0x7fcf916b85d3 - rustc_typeck::check::FnCtxt::resolve_type_vars_if_possible::ha2a2b0468a33b7be
  16:     0x7fcf916cd0a6 - rustc_typeck::check::demand::coerce::hd43013069440cf8a
  17:     0x7fcf916ca7b6 - rustc_typeck::check::check_argument_types::ha726e4d47c9cf6ca
  18:     0x7fcf916c97ef - rustc_typeck::check::check_method_argument_types::he368f9d4a41d1052
  19:     0x7fcf916cfcf9 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::h76666174c4b17386
  20:     0x7fcf917058d6 - rustc_typeck::check::check_stmt::h90d31dcbe73b93a2
  21:     0x7fcf916ac758 - rustc_typeck::check::check_block_with_expected::h17e4ec74708f2b9a
  22:     0x7fcf916cd863 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::h76666174c4b17386
  23:     0x7fcf916dfb55 - rustc_typeck::check::_match::check_match::h663ea413d198c72f
  24:     0x7fcf916cdac1 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::h76666174c4b17386
  25:     0x7fcf916ac937 - rustc_typeck::check::check_block_with_expected::h17e4ec74708f2b9a
  26:     0x7fcf916df36a - rustc_typeck::check::check_block_no_value::habc9ac13b558c874
  27:     0x7fcf916cd8c9 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::h76666174c4b17386
  28:     0x7fcf916dfb55 - rustc_typeck::check::_match::check_match::h663ea413d198c72f
  29:     0x7fcf916cdac1 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::h76666174c4b17386
  30:     0x7fcf917055ba - rustc_typeck::check::check_decl_initializer::h130cfba0c1b76b7a
  31:     0x7fcf91705681 - rustc_typeck::check::check_decl_local::he651fa13100c1d0f
  32:     0x7fcf91705971 - rustc_typeck::check::check_stmt::h90d31dcbe73b93a2
  33:     0x7fcf916ac758 - rustc_typeck::check::check_block_with_expected::h17e4ec74708f2b9a
  34:     0x7fcf916cd863 - rustc_typeck::check::check_expr_with_expectation_and_lvalue_pref::h76666174c4b17386
  35:     0x7fcf91705911 - rustc_typeck::check::check_stmt::h90d31dcbe73b93a2
  36:     0x7fcf916ac758 - rustc_typeck::check::check_block_with_expected::h17e4ec74708f2b9a
  37:     0x7fcf916a43e9 - rustc_typeck::check::check_fn::hab7334b30b5aec4a
  38:     0x7fcf916a1c9c - rustc_typeck::check::check_bare_fn::h85926feaf1e6659d
  39:     0x7fcf916b0fef - rustc_typeck::check::check_method_body::h51a0074463d9594f
  40:     0x7fcf9169ccfe - rustc_typeck::check::check_item_body::h1895344155d5b2b2
  41:     0x7fcf91694a31 - rustc_typeck::check::check_item_bodies::h525c1aa0e1abb529
  42:     0x7fcf9168bf9f - rustc_typeck::check_crate::h0ef96f4043e1e69a
  43:     0x7fcf9695dff0 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hc699330eb6f2bc1e
  44:     0x7fcf9695c0d8 - rustc::ty::context::TyCtxt::create_and_enter::h656b2d3a4956519e
  45:     0x7fcf96958aee - rustc_driver::driver::phase_3_run_analysis_passes::h83da042ec4b8ea10
  46:     0x7fcf9692af9f - rustc_driver::driver::compile_input::h6491aaddd9e61258
  47:     0x7fcf969114e4 - rustc_driver::run_compiler::h80b2ba5e4d787c5f
  48:     0x7fcf9690e941 - std::sys_common::unwind::try::try_fn::h34e27823ddd1d5e9
  49:     0x7fcf96409d0b - __rust_try
  50:     0x7fcf96409c9d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  51:     0x7fcf9690f18a - _<F as std..boxed..FnBox<A>>::call_box::h3d5d78986dfac5b2
  52:     0x7fcf96417e04 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  53:     0x7fcf8edf50a3 - start_thread
  54:     0x7fcf9606d87c - clone
  55:                0x0 - <unknown>

error: Could not compile `alcibiades`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name alcibiades --crate-type bin -g --out-dir /home/evgeni/src/alcibiades/target/debug --emit=dep-info,link -L dependency=/home/evgeni/src/alcibiades/target/debug -L dependency=/home/evgeni/src/alcibiades/target/debug/deps --extern rand=/home/evgeni/src/alcibiades/target/debug/deps/librand-c724acb3942597d1.rlib --extern lazy_static=/home/evgeni/src/alcibiades/target/debug/deps/liblazy_static-a81b08a56ec46bff.rlib --extern regex=/home/evgeni/src/alcibiades/target/debug/deps/libregex-a3ad4db16bc20e1f.rlib` (exit code: 101)

```

To try to reproduce the bug checkout this:

https://github.com/epandurski/alcibiades/tree/kill_movesink

then run `cargo build`

**Comment by nagisa** [comment] 2016-06-29 14:06
Looks like a duplicate of https://github.com/rust-lang/rust/issues/34428 from the backtrace.

**Comment by nagisa** [comment] 2016-06-29 14:11
It indeed works on nightly.

**Closed** 2016-06-29 17:02 UTC
Labels: I-ICE
