### ISSUE TITLE
Tracking Issue for `assert_eq` in constants

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#74925] opened 2020-07-29 19:38 UTC
In order to use `assert_eq!` in constants, we first need to have `panic!` with formatting (#51999) and `const fn` `PartialEq::eq` implementations (#67792) implemented and stabilized. If you look at the desugaring of `assert_eq!`, this quickly becomes obvious:

```rust
assert_eq!(a, b);
```

desugars to

```rust
        match (&a, &b) {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    // The reborrows below are intentional. Without them, the stack slot for the
                    // borrow is initialized even before the values are compared, leading to a
                    // noticeable slow down.
                    panic!(r#"assertion failed: `(left == right)`
  left: `{:?}`,
 right: `{:?}`"#, &*left_val, &*right_val)
                }
            }
        }
``` 

where the `==` operation will desugar to `PartialEq::eq(left_val, right_val)` for all non-primites. If we want to, we can support `assert_eq!` for primitives (integers, chars, bools) with only panicking with formatting.

**Comment by mental32** [comment] 2020-08-24 14:06
@oli-obk does this only apply to `assert_eq` or does it cover all of `assert`/`assert_eq`/`assert_ne`/`debug_*` variants?

**Comment by oli-obk** [comment] 2020-08-26 11:09
It covers all of these unless there's no formatting in `assert` or `debug_assert`, then those will work even without the formatting part of https://github.com/rust-lang/rust/issues/51999

**Comment by lcnr** [comment] 2022-09-16 14:52
discussed in a compiler meeting: https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202022-09-16.20JIT.20backlog.20b'za/near/299173821

closing as the information provided here is also part of the const-eval skill tree where it's probably more discoverable: https://rust-lang.github.io/const-eval/

**Closed by lcnr** 2022-09-16 14:52 UTC
Labels: C-tracking-issue

**Comment by alexschrod** [comment] 2023-10-23 07:17
1) For some reason, this "const-eval skill tree" is presented so small as to be basically unreadable:
![image](https://github.com/rust-lang/rust/assets/767490/ee0f975c-ef1a-4e52-b998-16bff3cdded1)
2) There's no instructions on how to read this thing anyway, so even if I could read the text in the dark orange/brown boxes, I'm not sure what it's supposed to be telling me about why I can't use `assert_eq!` in a `const` context.
3) As far as I can tell, based on the error you get, the problem is that there's a call to a non-const function `core::panicking::assert_failed`, and although this issue was closed over a year ago, it's still happening in Rust today.

**Comment by ChrisDenton** [comment] 2023-10-23 08:13
As the OP says, this is requires const traits (#67792).
