### ISSUE TITLE
Rustdoc: where bounds order in synthetic impls is not deterministic

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#49123] opened 2018-03-17 23:03 UTC
Unrelated changes to the standard library can cause `src/test/rustdoc` to fail until a change like this is applied:

```diff
diff --git a/src/test/rustdoc/synthetic_auto/no-redundancy.rs b/src/test/rustdoc/synthetic_auto/no-redundancy.rs
index 0b37f2ed31..9f860f4226 100644
--- a/src/test/rustdoc/synthetic_auto/no-redundancy.rs
+++ b/src/test/rustdoc/synthetic_auto/no-redundancy.rs
@@ -20,7 +20,7 @@ where
 
 // @has no_redundancy/struct.Outer.html
 // @has - '//*[@id="synthetic-implementations-list"]/*[@class="impl"]/*/code' "impl<T> Send for \
-// Outer<T> where T: Copy + Send"
+// Outer<T> where T: Send + Copy"
 pub struct Outer<T> {
     inner_field: Inner<T>,
 }
```

CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment] 2018-03-18 15:45
I don't think the issue comes from rustdoc. I tried to get this issue and wasn't able to... Last example:

```rust
use std::fmt::Debug;

struct Foo<T>(T);

unsafe impl<T> Send for Foo<T>
where T: Copy + Send + Clone + Debug {}
```

The generated docs have the correct output. No clue where it could come from...

**Comment by SimonSapin** [comment] 2018-03-18 16:46
The generated output sometimes changes when the standard library changes. This has happened that I know of in:

* https://github.com/rust-lang/rust/pull/48265 (but not anymore after a recent rebase)
* https://github.com/rust-lang/rust/pull/48810
* https://github.com/rust-lang/rust/pull/49038

**Comment by Phlosioneer** [comment] 2018-03-19 02:35
I suspect it may be something in #47833. I'm investigating, since one of the affected PR's is mine, so I can reproduce it.

**Comment by QuietMisdreavus** [comment] 2018-03-19 20:26
This test is running the "synthetic impls" functionality of rustdoc, where it will create an impl of Send/Sync if there is not an explicit one. This is entirely defined in `src/librustdoc/clean/auto_trait.rs`, so it's possible we can sort any where-clauses this generates.

**Comment by QuietMisdreavus** [comment] 2018-03-19 22:03
If i understand it correctly, the generics are handled in this section in that file. Sorting the collections in the resulting `Generics` will make the output deterministic.

https://github.com/rust-lang/rust/blob/a04b88d1941644df01fa5e31dd43e0f57c13d938/src/librustdoc/clean/auto_trait.rs#L135-L167

The key would be figuring out a proper sort, because with where clauses you can get arbitrary types in there, so we'd effectively need to be able to sort those somehow. I'm building something right now to test a hunch.

**Comment by kennytm** [comment] 2018-03-19 22:18
Reminder. The `rustdoc/synthetic_auto/no-redundancy.rs` test will be ignored after  #49058. If #49058 landed first (likely due to p=100), please make sure to remove the `// ignore` header from that test in the fix.

**Comment by Phlosioneer** [comment] 2018-03-20 01:43
@QuietMisdreavus I was under the impression that all impls are sorted, after the auto-generated ones are added to the list. That's why I mentioned #47833, which is the commit that added sorting of the impls for deterministic outputs.

If more stuff is being added to the list after that sort, _that_ is our bug. Otherwise, it should already be handled, and therefore the bug is within the sorting function.

**Comment by QuietMisdreavus** [comment] 2018-03-20 01:50
@Phlosioneer Looking at that PR again, it looks like it does sort the where predicates. However, it looks like the issue is about sorting the conditions within a single predicate, which the last commit in that PR doesn't address. That should help the implementation some.

(Also, thanks for pointing that out; i didn't realize that was there `>_>`)

**Comment by Phlosioneer** [comment] 2018-03-20 02:11
Ah, okay then, I think I found the error: make_final_bounds does a .collect() on an .into_iter() on a FxHashMap. The output vec of make_final_bounds just needs to be sorted.

https://github.com/rust-lang/rust/blob/ddfbf2b0f4726f11bc8e857274ae1a0f8343a73f/src/librustdoc/clean/auto_trait.rs#L1017-L1025
https://github.com/rust-lang/rust/blob/ddfbf2b0f4726f11bc8e857274ae1a0f8343a73f/src/librustdoc/clean/auto_trait.rs#L1097-L1099

I'll make a PR that adds a sort to that method.

**Comment by QuietMisdreavus** [comment] 2018-03-20 02:16
I don't think that will affect it. Like i said, it's not a matter of sorting between `WherePredicate`s, it's about sorting the bounds within a predicate. It would be worth seeing how that function creates those predicates to sort within the `flat_map`, not after the final `collect`.

**Comment by Phlosioneer** [comment] 2018-03-20 02:26
Oh, so really we need to sort the `bounds` within that function:

https://github.com/rust-lang/rust/blob/ddfbf2b0f4726f11bc8e857274ae1a0f8343a73f/src/librustdoc/clean/auto_trait.rs#L1084-L1096

Because `bounds` is also a `FxHashMap`.

**Comment by QuietMisdreavus** [comment] 2018-03-20 02:44
Yes, that's what i think the culprit is. Now that https://github.com/rust-lang/rust/pull/49058 is merged, re-enabling the test should make it fail, so whatever you add to librustdoc should either make it pass or make it stop toggling whenever a new type or impl is added to libstd.

**Closed** 2018-03-21 01:06 UTC
Labels: A-rustdoc, A-spurious, C-bug
