### ISSUE TITLE
Better error message when attempting to instantiate tuple structs with private fields

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#58017] opened 2019-01-31 02:10 UTC
[Given](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d7253040c69f885b3a45c3b95e204ad7)

```
mod a {
    pub struct Error(usize);
}

fn main(){
    let x = a::Error(3);
}
```

we emit

```
error[E0603]: tuple struct `Error` is private
 --> src/main.rs:6:16
  |
6 |     let x = a::Error(3);
  |                ^^^^^
```

which is confusing and inconsistent with the same error in a regular struct:

```
error[E0451]: field `a` of struct `a::Error` is private
 --> src/main.rs:6:23
  |
6 |     let x = a::Error {a: 3};
  |                       ^^^^ field `a` is private
```

This has [confused users](https://users.rust-lang.org/t/how-should-this-error-message-be-improved/22138/2) in the past. CC #57951 and #52144, which are somewhat related.

**Comment by csmoe** [comment] 2019-01-31 15:31
in addition to @Centril 's proposal, it should locate the exact position of the private fields:
```rust
struct Foo(pub i32, i32, pub i32, i32);
                    ^^^           ^^^
```

**Comment by lnicola** [comment] 2019-01-31 20:35
Is there a good reason why the three test cases give completely different error messages?

**Comment by estebank** [comment] 2019-01-31 21:52
This is actually a regression from 1.16:

```
error[E0450]: cannot invoke tuple struct constructor with private fields
 --> <source>:6:13
  |
2 |     pub struct Error(usize);
  |                      ------ private field declared here
...
6 |     let x = a::Error(3);
  |             ^^^^^^^^ cannot construct with a private field
```

**Comment by cramertj** [comment] 2019-07-08 21:52
ping on this, which still reproduces.

**Comment by estebank** [comment] 2019-07-16 01:07
cc @petrochenkov as this overlaps with a lot of the work he's been doing.

**Comment by pnkfelix** [comment] 2019-10-03 13:56
triage: I personally don't think this should be P-high, as in I don't think it should be part of the triage docket for T-compiler every week.

But I won't downgrade it yet.

First, lets tag it as E-needs-mentor, and see if anyone steps up to provide instructions for a solution here.

**Comment by da-x** [comment] 2019-10-06 07:16
Posted a PR to fix this - #65153.

**Comment by jonas-schievink** [comment] 2019-10-06 13:00
Duplicate of https://github.com/rust-lang/rust/issues/39703

**Closed** 2019-10-10 23:43 UTC
Labels: A-diagnostics, D-papercut, E-needs-mentor, P-high, T-compiler, regression-from-stable-to-stable
