### ISSUE TITLE
AFIT: incorrect "method not compatible with trait"

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#103457] opened 2022-10-24 01:10 UTC
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=812782f71fb464b085573c6ccd731e52)

```rust
pub trait SpiDevice {
    async fn transaction<'a, F: 'a>(&'a mut self, f: F);
}

impl SpiDevice for () {
    async fn transaction<'a, F: 'a>(&'a mut self, f: F) {}
}
```

gives the following error:

```
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): method not compatible with trait
 --> src/lib.rs:9:5
  |
9 |     async fn transaction<'a, F: 'a>(&'a mut self, f: F) {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ lifetime mismatch
  |
note: while checking the return type of the `async fn`
 --> src/lib.rs:9:57
  |
9 |     async fn transaction<'a, F: 'a>(&'a mut self, f: F) {}
  |                                                         ^ checked the `Output` of this `async fn`, expected opaque type
note: while checking the return type of the `async fn`
 --> src/lib.rs:9:57
  |
9 |     async fn transaction<'a, F: 'a>(&'a mut self, f: F) {}
  |                                                         ^ checked the `Output` of this `async fn`, found opaque type
  = note: expected fn pointer `fn(&'a mut (), _) -> impl Future<Output = ()>`
             found fn pointer `fn(&'a mut (), _) -> impl Future<Output = ()>`
note: the lifetime `'a` as defined here...
 --> src/lib.rs:9:26
  |
9 |     async fn transaction<'a, F: 'a>(&'a mut self, f: F) {}
  |                          ^^
  = note: ...does not necessarily outlive the static lifetime
```

The equivalent without `async` works.

**Comment by compiler-errors** [comment] 2022-10-24 04:53
I've got a root cause identified for this, but still working out some weird lifetime issues that fall out after the fix.

**Comment by oli-obk** [comment] 2022-11-30 16:03
This was fixed by https://github.com/rust-lang/rust/pull/103491

**Closed by oli-obk** 2022-11-30 16:03 UTC
Labels: C-bug, requires-nightly, F-async_fn_in_trait
