### ISSUE TITLE
Document that casting &mut T to &mut MaybeUninit<T> is not safe

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/rust#66699] opened 2019-11-24 13:28 UTC
[As discussed on Reddit](https://www.reddit.com/r/rust/comments/e0pivs/psa_casting_from_mut_t_to_mut_maybeuninitt_is_not/), it turns out that casting `&mut T` to `&mut MaybeUninit<T>` is not a safe operation, since it allows UB in safe code.

Playground example demonstrating the UB: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=93dd41cf851bfc0de2233e0a83b4b778

It is probably a good idea to explicitly point that out in MaybeUninit docs.

**Comment by jannickj** [comment] 2019-11-24 14:04
In the example you are already required to wrap the code in `unsafe` so I am curious why it's necessary to state explicitly for `MaybeUninit<T>`? transmute is unsafe for most types not just `MaybeUninit`.

**Comment by Kixunil** [comment] 2019-11-24 17:22
@jannickj if you try to write a safe wrapper around `MaybeUninit<T>`, then the fact that `T` can be soundly transmuted into `MaybeUninit<T>` does not mean that you can transmute `&mut T` into `&mut MaybeUninit<T>` and expose the resulting reference to safe code. That's something easily overlooked.

FWIW, there's at least one [crate](https://docs.rs/uninit/0.1.0/uninit/trait.AsUninitSliceMut.html) in the wild that is unsound because of this mistake. Hey @danielhenrymantilla you probably want to fix it. I wrote you an e-mail regarding other stuff, no reply yet.

**Comment by danielhenrymantilla** [comment] 2019-11-24 17:37
@Kixunil yes, thanks for the e-mail, I've been quite busy lately so I have not had much time to address this (or answer the e-mail 😉), but I'll try to have it fixed by tomorrow, with the previous versions being yanked (and the repo being published).

___

So, to summarize the issue, it turns out that `&'a mut MaybeUninit<T>` is far stronger than an `OutRef<'a, T>`, since it allows writing garbage. If we had an `OutRef<'a, T>` abstraction that only allowed to write a `T` into the pointee, then downgrading a `&'a mut T` to an `OutRef<'a, T>` should be sound, right?

Thanks @Shnatsel and @Kixunil for reporting this!

**Comment by Kixunil** [comment] 2019-11-25 07:57
Yes, I believe that's sound. Since I didn't get the answer to the e-mail I started creating a new crate from scratch that's addressing my needs. :) It's not published yet, but has bunch of other cool stuff. (Solves the same problem for slices, has tons of helper methods, iterator, safe cursor...) We can still cooperate if you want.

**Comment by Kixunil** [comment] 2019-11-25 20:15
FYI, here's the crate: https://crates.io/crates/possibly_uninit I hope it will help prevent these kinds of bugs.

**Comment by Kixunil** [comment] 2019-11-27 19:13
Interestingly `BytesMut` from `bytes` crate is also unsound. I fear that stabilizing `MaybeUninit` without having safe (or at least sound) abstractions for most common stuff was a major footgun.

**Comment by Kixunil** [comment] 2019-11-27 20:29
How hard would it be to add some basic abstractions into `core` to avoid others screwing up? Does it require RFC? Maybe just something for slices and mutable references, not stabilizing too many methods yet.

**Comment by RalfJung** [comment] 2019-11-28 11:14
To me this looks like someone mistakenly assumed `&mut T` to be covariant in `T`: in some sense, `MaybeUninit<T>` is a supertype of `T`, but that doesn't mean you can convert them below an `&mut`.

But, sure, if someone has a good suggestions for where in the `MaybeUninit` docs to put this, that seems fine.

**Comment by RalfJung** [comment] 2019-11-28 11:25
@Kixunil Having a user-defined `OutRef` type seems like a reasonable approach. However, it looks like you are still using "uninit" terminology in your crate. I am particularly worried about [this type](https://docs.rs/possibly_uninit/0.1.0-preview/possibly_uninit/slice/struct.MaybeUninitSlice.html). An "out ref" and a "reference to `MybeUninit`" are *two fundamentally different concepts* as this issue shows, so please be careful in picking terminology that conveys that difference! Your current names, I am afraid, will only make things worse. A "MaybeUninitSlice" should be just `&mut [MaybeUninit<T>]`, by using the same term for the totally different concept of an `OutSlice` you might cause confusion.

> How hard would it be to add some basic abstractions into core to avoid others screwing up? Does it require RFC? Maybe just something for slices and mutable references, not stabilizing too many methods yet.

See https://github.com/rust-lang/rust/issues/63569. However, what you are asking for is *not* "something for slices and mutable references to `MaybeUninit`"; what you are asking for is something entirely distinct, namely write-only references for initialization purposes.

**Comment by Kixunil** [comment] 2019-11-28 12:14
Thanks for recommendation, good point, I will change it (that's why I called it "preview" :)). Is the name `OutRef`  something standard and widely understood or just a suggestion? I didn't hear such thing before.

**Comment by RalfJung** [comment] 2019-11-28 12:26
I think `&out` as complement to `&mut` has come up discussions again and again over the years. This is related to in-place initialization / "placement new", which [has a looooooong history in Rust](https://github.com/rust-lang/rust/issues/27779#issuecomment-378416911). Swift has "in" and "inout" references; "out" seems like a natural name for this pattern.

However, note that there is AFAIK no way to implement safe `&out` as a library. The issue is that you need to somehow *force* a write to happen. (Well there might be tricks you can play with generative lifetimes but it's going to not be very ergonomic.) The [`BufMut` issue](https://github.com/tokio-rs/bytes/issues/328) is special because the safety of the problematic API relies on things already being initialized to begin with. So, I think there are very few cases where `OutSlice` actually makes an API *safe*. That type is not truly an out-reference as it doesn't *enforce* initialization. Hm.

**Comment by Kixunil** [comment] 2019-11-28 12:40
OK, I will rename it to `OutRef` and `OutSlice`.

Yes, the lack of enforcing is something I noticed. It's the primary reason I added [`Cursor`](https://docs.rs/possibly_uninit/0.1.0-preview/possibly_uninit/slice/struct.Cursor.html) for slices and I was thinking about doing something similar for `Sized` types (call it `Slot`? IDK).

It is totally true that "`OutSlice`" is not very useful in itself as the code interacting with it will be mostly `unsafe` (it can be nicely seen in `Cursor` impls). However, I do think that preventing footguns in `unsafe` code still has a value. At least documentation value that could prevent mistakes like these.

**Comment by danielhenrymantilla** [comment] 2020-10-15 11:33
By the way, this issue is related to another interesting one: for `&T -> &MaybeUninit<T>` to be sound, we need to express that `UnsafeCell` and `MaybeUninit` do not commute! More info in the docs of [`::uninit`](https://docs.rs/uninit): https://docs.rs/uninit/0.4.0/uninit/out_ref/struct.Out.html#interior-mutability

**Comment by lzutao** [comment] 2020-10-17 09:46
Isn't it a transmute and not a cast ?

**Comment by Kixunil** [comment] 2020-10-17 17:53
Is `&mut *(foo as *mut _ as *mut MaybeUninit<T>)` considered transmute?
Anyway, the title should (also) `s/safe/sound/`. The fact it's `unsafe` is already obvious.

**Comment by thomcc** [comment] 2020-10-30 01:24
It's not always unsound, just sometimes. The usual way of describing this is unsafe.

**Comment by ojeda** [comment] 2021-01-19 20:04
Something cannot be sometimes unsound -- it is either unsound or not. Unsafe does not imply unsound or sound.

**Comment by thomcc** [comment] 2021-01-19 20:09
It's unsound if you write MaybeUninit::uninit to it, or expose it to safe code (that can do this trivially). It's sound otherwise.

**Comment by ojeda** [comment] 2021-01-19 20:26
That means it is unsound. It doesn't matter that sometimes there may not be code triggering the UB.

**Comment by Kixunil** [comment] 2021-01-19 20:27
So the title should be "Document that casting &mut T to &mut MaybeUninit<T> and exposing it to safe code is not sound"

**Closed** 2024-12-23 04:14 UTC
Labels: C-enhancement, T-lang, A-docs
