### ISSUE TITLE
async dyn Trait type deduction

### ISSUE THREAD

**Issue by no111u3** [rust-lang/rust#64869] opened 2019-09-28 09:14 UTC
For standart functions rust deduct conversion from `Box::new(something)` to `Box<dyn Trait_name>`, but in async we need use `as Box<dyn Trait_name>`:
```rust
pub trait Trait: Send {}

#[derive(Default)]
struct Test;

impl Trait for Test {}

pub fn test() -> Box<dyn Trait> {
    Box::new(Test::default())
}

pub async fn test_async() -> Box<dyn Trait> {
    Box::new(Test::default()) as Box<dyn Trait>
}
```
So I think it's may be better without `as Box...`

**Comment by memoryruins** [comment] 2019-09-28 10:18
Duplicate of #60424

**Closed** 2019-09-28 11:06 UTC
