### ISSUE TITLE
apt-get install rustc

### ISSUE THREAD

**Issue by hartsantler** [rust-lang/rust#28307] opened 2015-09-08 23:24 UTC
Isn't about time we have DEB and RPM packages for rustc?
I hate the installer script.

Its not too hard to make these packages with FPM
https://github.com/jordansissel/fpm

**Comment by steveklabnik** [comment] 2015-09-09 02:38
Well, there's more to `apt-get install` than just having a package, Debian has a lot of process. That said, there are people working on it.

I believe we already have a ticket for this, but I'm not sure. @edunham ?

**Comment by Aatch** [comment] 2015-09-11 00:11
@steveklabnik I couldn't find an issue related to this.

This is being worked on though. As @steveklabnik says, there more to it than just having a package. We could have our own repository, but that's a lot of effort given that we'd expect it to be temporary anyway.

It's not about the difficulty of making a package, I mean, rustc compiles in a 3-stage bootstrap process, any packaging set up is going to be trivial compared to *that*. It's that both Debian and Fedora have quite strict policies and processes for getting packages into the official repositories.

Anyway, I'm happy to keep this issue open to track the progress of getting official packages in the bigger distributions.

**Comment by edunham** [comment] 2015-09-11 00:13
The conversation is in progress over at https://internals.rust-lang.org/t/perfecting-rust-packaging/2623 -- @brson is taking the lead on coordinating packaging across distributions.

**Comment by hartsantler** [comment] 2015-09-11 01:45
It could take a long time to get into the official repos.  In the meantime, why not just have a direct download to two deb packages, that users could install with:
```bash
sudo dpkg -i rustc.deb cargo.deb
```

**Comment by brson** [comment] 2015-09-11 18:07
@hartsantler I agree this is worth considering. It's one of the (numerous) topics in the previously-mentioned thread!

I've been wondering how valuable it would be for us to provide a highly-compatible deb/rpm, like many proprietary products (like Chrome) do.

If we do this it will probably be part of https://github.com/rust-lang/rust-packaging.

Thanks for the link to FPM. Do you know how it compares to [Alien](http://joeyh.name/code/alien/) (which appears to be unmaintained...)?

**Comment by hartsantler** [comment] 2015-09-11 18:34
FPM is great, i have used it a couple of times before, and i was able to package my own transpiler "Rusthon" in a matter of minutes with a simple shell script, see link below.  I haven't tried Alien, but i don't think you need to use it because FPM works great and is still maintained.
https://github.com/rusthon/Rusthon/blob/master/make-linux-packages.sh

**Comment by wsdjeg** [comment] 2015-12-19 14:53
can you provide PPA source,such as neovim 
https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

**Comment by hartsantler** [comment] 2015-12-20 13:45
https://github.com/jordansissel/fpm

**Comment by Fiedzia** [comment] 2016-01-12 01:09
It seems to me that rust got it backward. Having rust packaged by various distros may be desirable,
but first of all rust should maintain its own official repository providing *recent* rust version for popular distributions. Current situation is bad - there are recent no packages for debian/ubuntu whatsoever.
If debian/ubuntu maintainers will provide it, debian users will end up with rust version that is several years old, making it totally useless for development. In that case they will either have to download binary from site (if we wat them to do so, why bother with packaging rust?) or will use rust repository. Which should exist.

**Comment by TamaHobbit** [comment] 2016-06-11 14:01
So, how do I install rustc ? I'm on debian and at this point I'd even take a pastebin install script. Or, do I have to compile from source?

**Comment by steveklabnik** [comment] 2016-06-11 14:32
@TamaHobbit it's in Stretch and Sid, but not Jessie https://packages.debian.org/search?keywords=rustc&searchon=names&suite=all&section=all

**Comment by edunham** [comment] 2016-08-22 23:18
Help wanted: Extend the rust-packaging project to produce .debs

**Comment by ncm** [comment] 2016-09-09 06:23
It might be both easier and more directly useful to package rustup.  The Debian project is pretty quick at getting released rustc (including cargo) into Sid.

**Comment by brson** [comment] 2016-09-14 17:07
@ncm Agree that rustup packaging is a worthy pursuit.

Debian proper does have good support for Rust, but debs are useful for more than just Debian. Our builds are already compatible with almost every Linux and we can provide them in a format that is useful for every distro that uses apt but doesn't have the manpower to keep debs up to date.

**Comment by athulappadan** [comment] 2016-09-16 13:44
I don't know how difficult this task is. Can anyone explain the steps to be done..?

**Comment by infinity0** [comment] 2016-09-24 08:48
I already have up-to-date debs of [nightly](https://launchpad.net/~infinity0/+archive/ubuntu/rust-nightly) and [beta](https://launchpad.net/~infinity0/+archive/ubuntu/rust-beta) which are derived directly from Debian's rustc package. (In fact I also maintain the latter and these days I usually just import the rust-beta from my PPA, more-or-less.)

The problem is the tests break more often than I have spare time to fix, so any help on that would be appreciated. You can see the test failures here:

https://launchpad.net/~infinity0/+archive/ubuntu/rust-nightly/+packages

I didn't link directly to the build logs because they change whenever my cron job uploads new packages.

**Comment by brson** [comment] 2016-09-27 19:10
@infinity0 are your debs built to be compatible with all debian derivitives? Do they e.g. statically link llvm?

**Comment by infinity0** [comment] 2016-09-27 20:09
@brson They dynamically link LLVM, so they should be compatible with most Debian derivatives that stay reasonably close to Debian, including Ubuntu, TAILS, Kali, etc. It's fairly easy to tweak it to statically link LLVM however - just remove `debian/patches/dynamic-link-llvm.patch` and this filename from `debian/patches/series`.

**Comment by lilred** [comment] 2016-12-05 17:50
Can Rust please get an apt server some time soon :(

**Comment by steveklabnik** [comment] 2016-12-06 20:15
@lilred today, rustc is already in many distro's package management systems. Which linux are you using?

**Comment by lilred** [comment] 2016-12-07 00:52
I'm specifically asking for an apt server because the packages included in distro repositories tend to be very outdated. A Rust apt server could serve up-to-date stable binaries, and even betas and nightlies.

**Comment by ncm** [comment] 2016-12-07 01:43
On 12/06/2016 07:53 PM, Carl Patenaude Poulin wrote:
> I'm specifically asking for an apt server because the packages included
> in distro repositories tend to be very outdated. A Rust apt server could
> serve up-to-date stable binaries, and even betas and nightlies.

If you point your apt.sources file at "sid", you will get up-to-date
releases almost immediately when they are released.  If you install
rustup, you can have nightlies and cross compilers and everything.
What more do you want?

**Comment by tomjakubowski** [comment] 2016-12-07 04:08
> If you point your apt.sources file at "sid", you will get up-to-date
> releases almost immediately when they are released.

Won't this make sid updates available for *all* packages? That could be a heavy price to pay to have shiny new Rust.

**Comment by ncm** [comment] 2016-12-07 05:35
On 12/06/2016 11:08 PM, Tom Jakubowski wrote:
>     If you point your apt.sources file at "sid", you will get up-to-date
>     releases almost immediately when they are released.
>
> Won't this make sid updates available for /all/ packages? That could be
> a heavy price to pay to have shiny new Rust.

Most of us who use Debian for development use Sid routinely
for our daily work, for the up-to-date versions of everything,
most notably kernel drivers.  Debian "official releases" are
geared to people running server farms, competing with (e.g.)
RHEL.  Sid is no less stable, despite the name, than, say,
Fedora releases.

In any case, there is no difficulty in switching the config
file to point at Sid just long enough to install rustc and
its dependencies, and then back again. The only likely problem
is if you want to deploy Rust programs you built with Sid to
run on released Debian targets.  Then, if you really prefer
not to use rustup, what you probably want is to have rustc
distributed in an official "backports" repository:
   https://backports.debian.org/ .

**Comment by infinity0** [comment] 2016-12-07 09:58
It's also possible to "pin" repositories so that "sid" is at a low priority and things only get installed from there manually. Something like

~~~~
printf "Package: *\nPin: release n=sid\nPin-Priority: 50\n" \
  | sudo tee /etc/apt/preferences.d/unstable-low-priority
~~~~

but anyway, the main constraint here is people's time. This

> the packages included in distro repositories tend to be very outdated

is as true as YOU want it to be. Debian is an open volunteer project, and Mozilla setting up an APT repo won't magically put more manpower and resources onto the long-term maintenance of these packages.

**Comment by lilred** [comment] 2016-12-07 21:18
My use case is about Ubuntu, so all this stuff about Debian Sid doesn't apply :c

**Comment by ncm** [comment] 2016-12-07 21:35
On 12/07/2016 04:19 PM, Carl Patenaude Poulin wrote:
> My use case is about Ubuntu, so all this stuff about Debian Sid doesn't
> apply :c

Requesting special treatment for a community project like Debian
could have merit, until it turned out (as it did) to be unnecessary.
Requesting special treatment here for a commercial product is
wholly misplaced.  Ask Canonical, instead.  Supporting Ubuntu users
is their whole job.  It is bad form to ask unpaid volunteers for
things that someone is collecting a salary to provide.

Anyway, what is inadequate about rustup?

**Comment by lilred** [comment] 2016-12-13 02:46
rustup doesn't do system-wide installs as far as I know. Something my sysadmin cares a whole lot about.

**Comment by infinity0** [comment] 2017-04-19 14:09
We the Debian rust packaging team need help with this. The first step is to update cargo, then cross-compile it to arm and ppc architectures. See http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860116 for more details.

**Comment by ishitatsuyuki** [comment] 2017-04-26 11:28
Feel free to take what I use for Arch:

https://gist.github.com/ishitatsuyuki/956152c9ee2562e949f55c0181a0c5ee

I'm currently building on master, which can be a little bit different from stable.

**Comment by thejpster** [comment] 2017-08-17 09:44
So Raspbian Stretch is out now, and I see Debian have 1.14 available, but only for i386, amd64 and arm64 (so not for the Raspberry Pi). Testing has 1.18, including for armhf (so I guess whatever build issues they had have been fixed). Does anyone know if there's anything we can do to get Stretch updated to a version that does build for armhf? I'd love people to be able to ship Rust applications for the Raspberry Pi (or Debian in general) that depend on libstd-rust-1.14 (making them smaller than a static binary).

**Comment by ishitatsuyuki** [comment] 2017-08-17 09:47
You can only wait or use rustup. Debian's stable channel rarely contains latest upstream releases, and in fact I use sid and am having quite good experience.

**Comment by thejpster** [comment] 2017-08-17 09:54
Well I can use rustup, yes (and I do). But I'm hoping to get libstd-rust available to aid the distribution of binary applications written in Rust, especially on a low-power low-memory platform where the compile times really hurt.

**Comment by infinity0** [comment] 2017-08-17 10:34
Linking against `libstd-rust` seems to have been the original intention of the people that first packaged `rustc` for Debian, but it is going to be hard to achieve because it will require a re-build of all rust programs every 6 weeks and a [library transition](https://wiki.debian.org/Teams/ReleaseTeam/Transitions). I definitely won't be able to do that by myself, but maybe it would be possible if more people help. We also need to figure out how to actually do it, the current [Rust packaging policy](https://wiki.debian.org/Teams/RustPackaging/Policy) written by @JoshTriplett doesn't take this into account. We should probably also move the `librustc_*.so` stuff to a separate package since most user programs won't need it.

**Comment by thejpster** [comment] 2017-08-17 13:35
@infinity0 Given the ABI issues I wouldn't expect any given OS release to change stable Rust versions.

**Comment by infinity0** [comment] 2017-08-17 13:52
I'm the (only currently-active) Debian rustc maintainer. Firstly, you should only use Debian stable rustc to build other stuff in Debian stable, not for non-Debian packages that want or expect a newer rustc.

Then, it is true that Debian stable changes very rarely but the vast majority Debian maintainers don't usually touch Debian stable, that is only for the release team. To get stuff into Debian stable, involves maintaining it in Debian unstable (sid) first. Stuff migrates from Debian unstable to Debian testing then it gets frozen every ~2 years and released as Debian stable. Debian unstable is supposed to track what's up-to-date in the world (as long as maintainers have time), it wouldn't be great for other packages that might depend on Rust libraries, to purposefully let things go out-of-date.

Once Debian stable is frozen, rust-not-having-a-stable-ABI really does not affect that, since stuff doesn't get upgraded in there except for bugfixes that don't change the ABI.

Rust having a stable ABI would help with maintaining rust in Debian unstable - specifically, it would avoid us having to rebuild stuff against each newer `libstd-rust`. Also the fact that rust 1.x requires rust 1.x-1 to build, if this were relaxed then we could avoid having to packaging each rustc version every 6 weeks, and skip some versions.

**Comment by thejpster** [comment] 2017-08-17 13:56
Makes sense. Thanks for the clarification.

**Comment by joshtriplett** [comment] 2017-08-17 17:45
@infinity0 The Rust packaging policy does take that into account; in particular, it says "Application packages may require bin-NMUs to rebuild with newer versions of Rust libraries."

**Comment by infinity0** [comment] 2017-08-17 18:34
Yes, but it doesn't mention the other concrete steps we should take e.g. whether we should add `-C prefer-dynamic` during a build or not. I haven't tried it with enough crates to be confident that it would actually work as a global default, though it would be in line with Debian policy, and the last time I tried for `rustc` itself it caused the build to fail. Also there's the question of whether cargo should link against `std` or not, it might make bootstrapping / upgrades a lot harder.

**Comment by joshtriplett** [comment] 2017-08-17 19:56
@infinity0 Fair enough; I don't know if it makes sense to dynamically link to libstd or not. Either way we'd still need to bin-NMU after each rustc release.

**Comment by lilred** [comment] 2018-04-27 15:40
LGTM!

**Comment by dragostis** [comment] 2018-05-04 15:32
Is there any reason why we don't have fresher Rust releases on Debian? Since Rust releases so often and has this solid stabilization process, it creates a disadvantage for the compiler since there is no big bundle of features that gets released and can be included, rather, they get released slowly, in trickles.

**Comment by infinity0** [comment] 2018-06-24 10:01
Use Debian testing, not Debian stable, if you want up-to-date software on Debian.

**Comment by sanxiyn** [comment] 2019-03-19 18:20
Debian Rust packaging is in good shape. Closing.

**Closed by sanxiyn** 2019-03-19 18:20 UTC
Labels: C-feature-request, E-help-wanted, P-low, T-infra
