### ISSUE TITLE
rustdoc source links for `std_detect` macros are broken

### ISSUE THREAD

**Issue by clubby789** [rust-lang/rust#107367] opened 2023-01-27 13:46 UTC
Clicking the 'source' link on these pages:
https://doc.rust-lang.org/nightly/std/arch/macro.is_x86_feature_detected.html
https://doc.rust-lang.org/nightly/std/macro.is_x86_feature_detected.html
takes you to https://doc.rust-lang.org/nightly/src/std_detect/detect/arch/x86.rs.html#18-197, but this page does not exist.

This also occurs on std and beta

@rustbot label +T-rustdoc

**Comment by jyn514** [comment] 2023-02-13 09:43
Duplicate of https://github.com/rust-lang/rust/issues/96506

**Closed by jyn514** 2023-02-13 09:43 UTC
Labels: T-rustdoc, C-bug
