### ISSUE TITLE
Compilation error when proxying a function call via closure

### ISSUE THREAD

**Issue by ivan770** [rust-lang/rust#84190] opened 2021-04-14 15:00 UTC
I tried this code:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1478c821bdd7d9e135ef3c752c1e2250

I expected to see this happen: code compiles successfully, just like it does without closure:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bd2d963a5d0241a6272e9a39ac29aa0c

Instead, this happened: compilation error

**Comment by jyn514** [comment] 2021-04-14 15:10
Changing `let to_call = |n| {` to `let to_call = |n: &mut _| {` makes it compile, so this is a duplicate of https://github.com/rust-lang/rust/issues/41078.

**Closed by jyn514** 2021-04-14 15:10 UTC
Labels: C-bug
