### ISSUE TITLE
The error message signalling mismatched types gives wrong types

### ISSUE THREAD

**Issue by VinithKrishnan** [rust-lang/rust#41538] opened 2017-04-25 15:46 UTC
fn main() {
    let x = subtract_one(4);
    println!("X = {}", x);
}

fn subtract_one(x: i32) -> i32 {
    x - 1;
}

Error message:
error[E0308]: mismatched types
 --> main.rs:6:32
  |
6 |   fn subtract_one(x: i32) -> i32 {
  |  ________________________________^ starting here...
7 | |     x - 1;
8 | | }
  | |_^ ...ending here: expected (), found i32
  |
  = note: expected type `()`
             found type `i32`
Shouldn't the error message say expected i32,found ()?

rust version:
rustc 1.18.0-nightly (3b5754e5c 2017-04-10)

**Comment by durka** [comment] 2017-04-25 15:57
Duplicate of #41425.

**Comment by VinithKrishnan** [comment] 2017-04-25 16:03
Yep,seems like the same issue.Is anyone working on this?

**Closed** 2017-04-25 17:09 UTC
