### ISSUE TITLE
item-bodies checking very slow when compiling lalrpop incrementally 

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rust#47803] opened 2018-01-27 11:27 UTC
When compiling the lalrpop (https://github.com/nikomatsakis/lalrpop) crate rustc spends a very long time in item-bodies checking. This only happens when compiling incrementally for the first time but while incremental compilation is expected to increase initial compile times I don't believe a 30x increase can be expected.

## CARGO_INCREMENTAL=1
```
  time: 313.236; rss: 491MB	item-bodies checking
```

## CARGO_INCREMENTAL=0
```
  time: 13.881; rss: 430MB      item-bodies checking
```

For reference, LALRPOP generates parsers into files like this https://raw.githubusercontent.com/lalrpop/lalrpop/5246910e7e656c56f0b77c4f8c3cf33862b1c493/lalrpop-snap/src/newparser.rs which are the most likely culprit.

Original report at https://github.com/lalrpop/lalrpop/issues/260

cc @nikomatsakis

**Comment by nikomatsakis** [comment] 2018-01-29 17:21
@Marwes ah, interesting

cc @michaelwoerister 

It'd be good to do some basic perf runs here.

**Comment by nikomatsakis** [comment] 2018-01-29 17:21
We should make some kind of standalone test file too....

**Comment by nikomatsakis** [comment] 2018-01-29 17:21
Nominating for compiler team meeting for prioritization. 30x hit for incremental seems like something worth investigating.

**Comment by nikomatsakis** [comment] 2018-01-29 17:22
Put another way: now that incremental is going to be enabled by default, this is a serious compile-time regression.

**Comment by ahmedcharles** [comment] 2018-01-31 12:00
I'm using `rustc 1.23.0 (766bd11c8 2018-01-01)` without `CARGO_INCREMENTAL` set. Is incremental compilation on for this setup?

**Comment by Marwes** [comment] 2018-01-31 12:05
@ahmedcharles If you want to test with or without incremental compilation you can set it explicitly for either case `=0`/`=1`.

**Comment by ahmedcharles** [comment] 2018-01-31 12:15
Sure, I knew that. I'm wondering what the current default is.

**Comment by nikomatsakis** [comment] 2018-02-08 15:35
triage: P-medium

But I plan to do a bit of investigation.

**Comment by michaelwoerister** [comment] 2018-02-12 12:06
Interesting. 

@ahmedcharles, incremental compilation is not the default for that release yet.

**Comment by nikomatsakis** [comment] 2018-02-15 15:35
triage: P-high

Calling P-high to get *some* idea what the problem is. Plan is for me to reproduce the results on latest Nightly and get a standalone test case. Then @michaelwoerister and I can discuss next steps.

**Comment by nikomatsakis** [comment] 2018-02-15 17:37
Huh. Maybe I didn't do this right, but I am not observing these slowdowns. I'm just building LALRPOP itself, which I think is what @Marwes was testing. In fact, I generally see `CARGO_INCREMENTAL=0` leading to big *slowdowns*. This is a bit confusing. Maybe the problem is that incremental is getting used? (I'm trying to avoid that with appropriate cleans...)

This is the commands I ran and the output:

```bash
> cargo clean -p lalrpop; CARGO_INCREMENTAL=0 cargo +nightly rustc --; 
   Compiling lalrpop-intern v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop-intern)
   Compiling lalrpop-util v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop-util)
   Compiling lalrpop-snap v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop-snap)
   Compiling lalrpop v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop)
    Finished dev [unoptimized + debuginfo] target(s) in 78.38 secs
> cargo clean -p lalrpop; CARGO_INCREMENTAL=0 cargo +nightly rustc --
   Compiling lalrpop v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop)
    Finished dev [unoptimized + debuginfo] target(s) in 50.37 secs
> cargo clean -p lalrpop; CARGO_INCREMENTAL=1 cargo +nightly rustc --; 
   Compiling lalrpop-intern v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop-intern)
   Compiling lalrpop-util v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop-util)
   Compiling lalrpop-snap v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop-snap)
   Compiling lalrpop v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop)
    Finished dev [unoptimized + debuginfo] target(s) in 30.30 secs
> cargo clean -p lalrpop; CARGO_INCREMENTAL=1 cargo +nightly rustc --; 
   Compiling lalrpop v0.14.0 (file:///Users/nmatsakis/versioned/lalrpop/lalrpop)
    Finished dev [unoptimized + debuginfo] target(s) in 20.57 secs
```

I ran each command twice since, after switching modes, cargo seems to want to rebuild everything in the local workspace (weird).

**Comment by Marwes** [comment] 2018-02-15 18:28
I am not able to reproduce this anymore, so either it got fixed after updating nightly (need to test the older nightly I originally used to check) or I made a mistake somehow. I definitely got the 300s pass a few times though...

On the most recent nightly (`rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)`) I get another strange problem though. When I disable incremental compilation the `borrow checking` pass takes ~60s (vs < 1 on incremental).

**Comment by Marwes** [comment] 2018-02-15 18:54
The slow `item-bodes checking` reproduces on `nightly-2018-01-19` but not on the current nightly so it seems to be fixed.

**Comment by nikomatsakis** [comment] 2018-02-19 16:47
@Marwes awesome! I'm going to close this then. There were a number of improvements made to hashing, so I guess one of them affected this as well.

**Comment by nikomatsakis** [comment] 2018-02-19 16:48
@Marwes 

> On the most recent nightly (`rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)`) I get another strange problem though. ~When I disable incremental compilation the `borrow checking` pass takes about 60s (vs < 1 on incremental).~ It occurs both with and without incremental compilation, but `cargo clean -p lalrpop` appears to not clean all incremental compilation artifcats for the `lalrpop` crate,

Er, I can't tell -- what's the bug here?

**Closed by nikomatsakis** 2018-02-19 16:47 UTC
Labels: A-incr-comp, C-enhancement, I-compiletime, P-high, T-compiler, regression-from-stable-to-nightly

**Comment by Marwes** [comment] 2018-02-19 17:50
@nikomatsakis I originally thought it was only non-incremental builds that were slow which would definitely be a bug (though a different from this issue). Since it is equally slow on both incremental and non-incremental builds it might not be a bug, but taking 60 seconds seems unexpectedly long?
