### ISSUE TITLE
Internal compile error after warnings from unused imports

### ISSUE THREAD

**Issue by hgotur** [rust-lang/rust#85004] opened 2021-05-06 20:02 UTC
### Code

```Rust
use ferris_says::say;
use std::io::{stdout, BufWriter};

fn main() {
    println!("Hello World!");
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0 (88f19c6da 2021-05-03)
binary: rustc
commit-hash: 88f19c6dab716c6281af7602e30f413e809c5974
commit-date: 2021-05-03
host: x86_64-pc-windows-msvc
release: 1.52.0
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[bd3a]::ops::function::Fn): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::ops::FnMut<Args>>)), C:\Users\Harsha\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:67:21: 67:32 (#0)), (Binder(TraitPredicate(<Args as std::marker::Sized>)), C:\Users\Harsha\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:67:14: 67:18 (#0)), (Binder(TraitPredicate(<Self as std::ops::Fn<Args>>)), C:\Users\Harsha\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\function.rs:67:1: 67:32 (#0))] }', /rustc/88f19c6dab716c6281af7602e30f413e809c5974\compiler\rustc_query_system\src\query\plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::Fn`
#1 [vtable_methods] finding all methods for trait std::ops::Fn
#2 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-05-06 22:45
Duplicate of https://github.com/rust-lang/rust/issues/84341. This is fixed in the latest nightly

**Closed by Aaron1011** 2021-05-06 22:45 UTC
Labels: C-bug, I-ICE, T-compiler

**Comment by Aaron1011** [comment] 2021-05-06 22:49
As a workaround, you can run `cargo clean -p <your_package_name>` or `cargo clean`.
