### ISSUE TITLE
Exhaustive match of number treated as non-exhaustive

### ISSUE THREAD

**Issue by ebiggers** [rust-lang/rust#12483] opened 2014-02-23 00:58 UTC
The following function does not compile because rustc determines that the patterns in the match statement are non-exhaustive.  However, the pattern matches every possible value of the integer type, and the compiler should be able to detect this.
 
```rust
fn wont_compile(x : u8) { 
    match (x) {
        0x00 .. 0xff => { }
    }
}
```

**Comment by steveklabnik** [comment] 2015-01-23 02:45
The compiler is never going to be able to fully determine these kinds of things, as they would involve evaluating certain things at compile time. For example:

```
0x00 ... (0xff + 1 - 1) => { }
```

This arm would be equivalent, but would report as non-exhaustive, too.

As such, I'm giving this a close. I don't think we can improve this.

**Comment by chris-morgan** [comment] 2015-07-22 14:12
@steveklabnik I disagree with your closing of this issue; could you please open it again? The issue is entirely genuine, is blocking correct code (though admittedly there is an easy workaround: change the last pattern to an `_`) and is a nuisance.

Moreover, your fabricated example is invalid, because you can’t do arithmetic in patterns.

@jkleint Your example is a completely different issue and is *not* solvable. `n > 0 || n < 0 || n == 0` is not necessarily true, though it is declared by the programmer to be true if `Eq` and `Ord` are implemented for the type.

**Comment by steveklabnik** [comment] 2015-07-22 14:30
@chris-morgan I'm not understanding how this issue is solvable. To grok the range, we need to evaluate code at compile time, it can't work.

**Comment by chris-morgan** [comment] 2015-07-22 21:08
@steveklabnik it’s a pattern, so the numbers are literals or constants. No additional evaluation required. The compiler needs to know them in order to compile the code anyway.

**Comment by jkleint** [comment] 2015-07-25 01:48
@chris-morgan aren't `Eq` and `Ord` implemented for integers?  My example was an integer.  :)

**Comment by aarzee** [comment] 2015-09-18 19:17
I've written a POC script that compares a set of ranges with 1 or more exhaustive ranges and outputs any ranges that are not covered: https://gist.github.com/aarzee/4395cb34eef31ea4e5c4

**Comment by jonas-schievink** [comment] 2015-09-24 22:33
Implementing this would cause the following to fail to compile since the last arm is unreachable:
```rust
match 0u8 {
    0...255 => {}
    _ => {}
}
```

Should a warning be emitted first? Is an RFC needed? Should this be ignored without warning, like it is now? Make it a deny-by-default Lint to prevent breaking dependencies? So many questions!

**Comment by chris-morgan** [comment] 2015-09-24 23:23
To be sure, implementing this will cause certain existing code to cease to compile, but it was bad code to begin with and a bug in the compiler *is* being fixed. And it is very unlikely to actually affect anyone in practice. Thus it fits easily inside the stability-retention guidelines. I do not believe any RFC is required, nor any ability to disable the new behaviour.

**Comment by jonas-schievink** [comment] 2015-09-24 23:37
> I doubt that anyone has actually written such code

Not this exact code, sure. But maybe an opcode dispatch switch that handles all possible byte values? Or one that handles all undefined opcodes with an arm like `0xab ... 0xff => panic!("invalid")`, and an additional `_ => unreachable!()` (because this is currently required).
Maybe some people match on the high bit of a byte like this: `0 ... 127 => "high bit clear", 128 ... 255 => "high bit set", _ => unreachable!()`
All of these would stop compiling if this is implemented, so I think the impact should at least be evaluated.

**Comment by chris-morgan** [comment] 2015-09-25 00:23
Hmm, good point. I myself have just changed the last branch into `_`, preferring not to put an extra and superfluous `unreachable!()` into the code, but I can see that someone could easily have gone the other way.

**Comment by jonas-schievink** [comment] 2015-09-28 15:18
I wrote a bit of code that at least seems to work semi-correctly for a few test cases: https://play.rust-lang.org/?gist=f3d4e2e9559d84319432&version=stable

It's `O(n²)` in the number of literal matches (or ranges) for each variable matched against, but I haven't actually measured if there's any impact (there are never too many literal or range patterns for a single variable - 256 seems still useful for matching all `u8` values, but I doubt there's much code with more than that).

Feel free to ~~break it~~ play with it using the examples at the bottom!

**Comment by petrochenkov** [comment] 2015-09-28 15:28
For reference, @quantheory wrote an RFC about this - https://github.com/rust-lang/rfcs/pull/880, it was postponed. He wrote some implementation too https://github.com/quantheory/int_range_check.

**Comment by comex** [comment] 2015-11-05 18:26
FWIW, GCC can do this: https://goo.gl/4f1i6H (no warning, but a warning appears if you change 255 to something else).  Clang can't tell the difference.

**Comment by steveklabnik** [comment] 2015-11-12 19:31
I'm going to close this in favor of an RFC, as this would be a pretty big change. @quantheory's might be a good starting point!

**Closed by steveklabnik** 2015-11-12 19:31 UTC
Labels: I-enhancement
