### ISSUE TITLE
Few LLVM lint "Unusual"

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#48229] opened 2018-02-15 10:05 UTC
In Issue #48227 I've seen code compiled with "-C passes=lint", I've used it on some of my code and I've found few problems, reduced below:

--------------------

```
fn foo(_: &u32, _: &u32) {}
fn main() {
    let a = 0;
    foo(&a, &a);
}


...>rustc -C passes=lint test1.rs
Unusual: noalias argument aliases another argument
  call void @_ZN4bug13foo17h2a852a9d6b40f8a0E(i32* noalias readonly dereferenceable(4) %1, i32* noalias readonly dereferenceable(4) %1)
```

--------------------

```
fn main() {
    (1 .. 9).take_while(|i| i * i <= 10).any(|_| true);
}


...>rustc -C passes=lint test2.rs
Unusual: noalias argument aliases another argument
  %3 = call i32 @"_ZN86_$LT$$RF$$u27$b$u20$i32$u20$as$u20$core..ops..arith..Mul$LT$$RF$$u27$a$u20$i32$GT$$GT$3mul17hdb3638dfdb52b819E"(i32* noalias readonly dereferenceab
le(4) %1, i32* noalias readonly dereferenceable(4) %1)
```

--------------------

```
fn main() {
    (1 .. 9).filter(|_| true).sum::<u32>();
}


...>rustc -C passes=lint test3.rs
Unusual: Return statement in function with noreturn attribute
  ret void

```
--------------------

**Comment by leonardo-m** [comment] 2018-02-15 10:24
```
rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)
binary: rustc
commit-hash: 3ec5a99aaa0084d97a9e845b34fdf03d1462c475
commit-date: 2018-02-14
host: x86_64-pc-windows-gnu
release: 1.25.0-nightly
LLVM version: 6.0
```

**Comment by nagisa** [comment] 2018-02-16 08:55
Duplicate of https://github.com/rust-lang/rust/issues/7463

**Comment by nagisa** [comment] 2018-02-16 08:58
I guess I’ll reopen, since this contains minimal and actionable code samples.

**Comment by RalfJung** [comment] 2018-03-28 15:05
This seems like the LLVM lint disagrees with the statement somewhere in the compiler sources saying that `noalias` on read-only data is fine even if thins alias -- because we can still reorder them?

**Comment by rkruppe** [comment] 2018-03-28 15:54
Doesn't `noalias` also factor into optimizing pointer comparisons?

**Comment by RalfJung** [comment] 2018-03-28 15:56
Well whoever wrote that code strongly things that is not the case...

Also, depending on what exactly clang does, that would be unsound:
```C
int foo(restrict int *x, restrict int *y) {
  (x == y) ? 1 : 0
}
```
This can *not* be optimized to return `0`.

**Comment by rkruppe** [comment] 2018-03-28 16:05
Hm, you're right, and indeed I couldn't find any such optimization in a quick skim of instcombine.

**Comment by cuviper** [comment] 2019-04-05 18:30
>     Unusual: Return statement in function with noreturn attribute

This case is fixed by #59639 as of nightly-2019-04-05.

**Comment by jonas-schievink** [comment] 2019-12-10 16:50
Removing `I-unsound` label. The remaining 2 cases ("noalias argument aliases another argument") seem to be caused by the LLVM lint being a bit overzealous. Maybe we should close this altogether?

**Comment by cuviper** [comment] 2019-12-10 16:56
Those `noalias` lints should be relaxed by [D60239](https://reviews.llvm.org/D60239), which is in LLVM 9. I will try to do a new rustc build with lints enabled to see if anything remains.

**Comment by jonas-schievink** [comment] 2019-12-10 17:03
Can confirm they're gone on `rustc 1.41.0-nightly (797fd9262 2019-11-26)` with `-Cpasses=lint`. In some other code, some of these have shown up:

```
Unusual: unreachable immediately preceded by instruction without side effects
  unreachable, !dbg !112
```

This shouldn't really be an issue and is just a bit sloppy codegen by rustc.

**Closed by jonas-schievink** 2019-12-10 17:03 UTC
Labels: A-LLVM, A-codegen, C-bug, T-compiler
