### ISSUE TITLE
rustdoc: `doc(hidden)` methods from traits show up on implementors

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#86145] opened 2021-06-08 17:19 UTC
The __iterator_get_unchecked method on `Iterator` is `doc(hidden)`: https://doc.rust-lang.org/nightly/src/core/iter/traits/iterator.rs.html#3425-3437, and it is correctly hidden in the main part of `Iterator`'s page. However, it still shows up in the Implementations section of structs that implement the trait, like `std::str::Bytes`:

https://doc.rust-lang.org/1.52.0/std/str/struct.Bytes.html#method.__iterator_get_unchecked

The method should be hidden in all contexts.

**Comment by jsha** [comment] 2021-06-08 17:48
Looking at implementations of __iterator_get_unchecked in std, it looks like about half have `doc(hidden)` on the implementation too. So for now I'm going to fix my immediate issue by making sure all implementations have `doc(hidden)`. Maybe that's the overall solution too - say that `doc(hidden)` only applies to the trait item, and if implementations want to hide their copy, they have to do that manually.

**Comment by jyn514** [comment] 2021-07-02 10:33
Duplicate of https://github.com/rust-lang/rust/issues/36035

**Closed by jyn514** 2021-07-02 10:33 UTC
Labels: A-rustdoc-ui, C-bug, T-rustdoc
