### ISSUE TITLE
Bounds check are added for array when they should not (most likely)

### ISSUE THREAD

**Issue by SRaimondi** [rust-lang/rust#103528] opened 2022-10-25 15:52 UTC
### Code

I tried this code:

```rust
#[derive(Copy, Clone)]
pub enum Test {
    A = 0,
    B = 1,
    C = 2,
}

pub fn test(arr: [u32; 3], t: Test) -> u32 {
    arr[t as usize]
}
```

and checked the generated code for Rust 1.64 and 1.63, see [here](https://godbolt.org/z/PvdoYoThP).

I expected the compiler to omit the bounds check on the array since the values of the enum are known and it's not possible to have a value outside of the allowed range of indices (unless you use `transmute` but that would be unsafe).

This is generated as expected for Rust 1.63.0 but the bounds check is added for Rust 1.64.0.

Is this expected behaviour?

### Version it worked on

It most recently worked on: 1.63.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
Compiler returned: 0
```

**Comment by saethlin** [comment] 2022-10-25 15:59
I think this is a duplicate of https://github.com/rust-lang/rust/issues/102303

**Closed** 2022-10-25 16:01 UTC
Labels: C-bug, I-prioritize, regression-untriaged
