### ISSUE TITLE
rustc enters infinite loop during compillation of an incomplete program

### ISSUE THREAD

**Issue by WiSaGaN** [rust-lang/rust#31933] opened 2016-02-27 05:34 UTC
Compilation of a simple incomplete program

    fn main() {
        match
    }

makes the nightly `rustc` to enter an infinite loop of printing

> src/main.rs:3:1: 3:2 error: unexpected token: `<eof>`
src/main.rs:3 }
              ^
src/main.rs:3:1: 3:2 error: unexpected token: `<eof>`
src/main.rs:3 }
              ^

This only happens in nightly. Stable and beta are fine as of Feb 27, 2016.
This can be reproduced in https://play.rust-lang.org/?gist=3cff960d21a553727434&version=nightly
This may be related to https://github.com/rust-lang/rust/issues/30128

**Comment by durka** [comment] 2016-02-27 05:38
likely the same as #31804

**Comment by Aatch** [comment] 2016-02-27 20:49
Duplicate of #31804

**Closed by Aatch** 2016-02-27 20:49 UTC
