### ISSUE TITLE
ICE probably connected to const generics

### ISSUE THREAD

**Issue by MikailBag** [rust-lang/rust#66987] opened 2019-12-03 14:47 UTC
Playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e37f6d10c9fa79a691d84a3042c3fcb6
AFAIU, there is out-of-bounds-panic connected with `good_transmute` fn. Probably, compiler fails on `buf` array, because it's length is size_of() generic type.

**Comment by jonas-schievink** [comment] 2019-12-03 14:57
Backtrace:

```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/fdc0011561c6365c596dfd8fa1ef388162bc89c7/src/libcore/slice/mod.rs:2797:10
stack backtrace:
<snip>
  14: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:60
  15: rustc_mir::borrow_check::nll::type_check::type_check
  16: rustc_mir::borrow_check::nll::compute_regions
  17: rustc_mir::borrow_check::do_mir_borrowck
<snip>
```

**Comment by jonas-schievink** [comment] 2019-12-03 14:57
Duplicate of https://github.com/rust-lang/rust/issues/62456

**Closed by jonas-schievink** 2019-12-03 14:57 UTC
