### ISSUE TITLE
ToOwned is implemented for all reference types

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust#27993] opened 2015-08-25 11:36 UTC
This occurred while trying to convert instances of `str.to_string()` to `to_owned()`. When the receiver is of type `&&str` (or `&&&str`, etc.) this will "mysteriously" fail to work since you get back a `&str`.

The reason seems to be that the general implementation of `ToOwned` for all `Clone` types applies to references which are `Clone`. This is probably unintended.

I'm not sure this can be changed at all, but I'd like to raise it as an issue nevertheless, since having `to_owned` available on reference types producing anything but an owned value, is quite confusing.

**Comment by alexcrichton** [comment] 2015-08-25 16:41
This is actually currently intentional because one of the key points of `ToOwned` is that it works generically for everything that's `Clone` as well. The primary purpose of this trait is for generic consumers, not necessarily literal callers.

Regardless, though, this isn't something that can change now as it's a key point of the `ToOwned` trait, so I'm going to close this as "working as intended"

**Closed by alexcrichton** 2015-08-25 16:41 UTC
Labels: A-libs

**Comment by birkenfeld** [comment] 2015-08-25 16:44
I suspected as much. Thanks!
