### ISSUE TITLE
#[allow(unused_variables)] doesn't work on nightly

### ISSUE THREAD

**Issue by yongqli** [rust-lang/rust#30889] opened 2016-01-14 00:46 UTC
#![feature(stmt_expr_attributes)]
    fn main() { 
        #[allow(unused_variables)]
        let m = vec![0, 1, 2, 3];
    }

https://play.rust-lang.org/?gist=046284812e585e8331d0&version=nightly

**Comment by huonw** [comment] 2016-01-14 00:55
Duplicate of https://github.com/rust-lang/rust/issues/30326, but thanks for filing!

**Closed by huonw** 2016-01-14 00:55 UTC
