### ISSUE TITLE
API docs have broken links for contents under liballoc

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#21226] opened 2015-01-16 06:50 UTC
For example,
[struct Weak](http://doc.rust-lang.org/std/rc/struct.Weak.html)
[struct Rc](http://doc.rust-lang.org/std/rc/struct.Rc.html)
[struct Box](http://doc.rust-lang.org/std/boxed/struct.Box.html)
The [src] link at the top-right corner on these pages redirect to 404 page.

Other pages like [enum Option](http://doc.rust-lang.org/std/option/enum.Option.html) seems to be fine.

**Comment by bombless** [comment] 2015-01-16 15:30
cc @steveklabnik

**Comment by steveklabnik** [comment] 2015-01-16 15:52
I think there are other bugs open for this, but I'm not sure.

**Comment by lifthrasiir** [comment] 2015-01-16 16:26
Duplicate of #15309, as @steveklabnik said.

**Closed** 2015-01-16 16:33 UTC
Labels: A-rustdoc
