### ISSUE TITLE
Test process::tests::test_inherit_env fails when environment variable contains non-ascii characters

### ISSUE THREAD

**Issue by anta-** [rust-lang/rust#40171] opened 2017-03-01 10:33 UTC
Result of `./x.py test src/libstd/`:

```
failures:

---- process::tests::test_inherit_env stdout ----
        thread 'process::tests::test_inherit_env' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [82, 85, 83, ... <snip> ... ], error: Utf8Error { valid_up_to: 2674 } }', src\libcore\result.rs:860
```

My environment variable contains "ChocolateyLastPathUpdate=水 12 14 19:40:40 2016" and which is the cause of this.

* Rust version: current HEAD.
* Host: x86_64-pc-windows-gnu

Note: Environment variables are OsStr but output encoding of `cmd /c set` depends on the environment (ShiftJIS on my computer).

**Comment by petrochenkov** [comment] 2017-03-01 11:02
Duplicate of https://github.com/rust-lang/rust/issues/25268
The solution is to run change the console code page to UTF-8 before running tests:
```cmd
cmd /c "chcp 65001"
```

The old build system [issued a warning](https://github.com/rust-lang/rust/pull/25654/files) for this specific case, but it was lost in rustbuild.

**Comment by Mark-Simulacrum** [comment] 2017-05-24 17:33
I've been working on a rework of compiletest that fixes the underlying cause, but I'm going to close this since we do warn to change the code page as @petrochenkov notes above today I believe.

**Closed by Mark-Simulacrum** 2017-05-24 17:33 UTC
Labels: A-testsuite, A-windows
