### ISSUE TITLE
Panic during build

### ISSUE THREAD

**Issue by A4-Tacks** [rust-lang/rust#110517] opened 2023-04-19 02:51 UTC
### Code

```Rust
// my crate timg@2.0.0 to timg@2.0.1
```

### Meta

`rustc --version --verbose`:
```
rustc 1.68.0 (2c8cc3432 2023-03-06)
binary: rustc
commit-hash: 2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74
commit-date: 2023-03-06                                                                                               host: aarch64-unknown-linux-gnu
release: 1.68.0
LLVM version: 15.0.6
```

This seems to be an accident, I don't know how to reproduce it, I just tried to submit it.

### Error output

```
lrne@localhost[/home/lrne/Project/Rust/timg/]                                                                         [000] 10:35:44
    $ cargo build --release
   Compiling timg v2.0.1 (/home/lrne/Project/Rust/timg)
    Finished release [optimized] target(s) in 3.45s
lrne@localhost[/home/lrne/Project/Rust/timg/]                                                                         [000] 10:35:51
    $ cargo build
warning: Failed to garbage collect finalized incremental compilation session directory `/home/lrne/Project/Rust/timg/target/debug/incremental/timg-l42gz9zalivh/s-gk693ol6d6-4h7luj-2deeqmhvmgc96`: No such file or directory (os error 2)

warning: `timg` (lib) generated 1 warning
   Compiling timg v2.0.1 (/home/lrne/Project/Rust/timg)
thread 'rustc' panicked at 'failed to open bitcode file `/home/lrne/Project/Rust/timg/target/debug/incremental/timg-31inqbvbag9er/s-gk697u0c8z-1bmdhar-working/stvq58nujdg7h3b.pre-lto.bc`: Too many levels of symbolic links (os error 40)', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/compiler/rustc_codegen_ssa/src/back/write.rs:1984:29
stack backtrace:
   0:       0x74f01a6150 - std::backtrace_rs::backtrace::libunwind::trace::hf81ef7bc29176a13
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:       0x74f01a6150 - std::backtrace_rs::backtrace::trace_unsynchronized::hbcc34bc9228962ba
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:       0x74f01a6150 - std::sys_common::backtrace::_print_fmt::hd7350ba89771d084
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:       0x74f01a6150 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80e28c03bf3f7004
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:       0x74f01fe010 - core::fmt::write::ha3c8cc7259c6778a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:       0x74f0199064 - std::io::Write::write_fmt::h3c3a78d0b1b246d8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:       0x74f01a5f5c - std::sys_common::backtrace::_print::h5e2c574a03bf8fe5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:       0x74f01a5f5c - std::sys_common::backtrace::print::ha07f31ed8bf6af57
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:       0x74f01a8938 - std::panicking::default_hook::{{closure}}::he83ac16ee3e760fb
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:       0x74f01a867c - std::panicking::default_hook::h792f0fa710d37630
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:       0x74f0edccb4 - rustc_driver[9f1b6a52b0dd68ae]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:       0x74f01a9098 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he8874e7b8a257780
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
  12:       0x74f01a9098 - std::panicking::rust_panic_with_hook::hf03f9c40f035795c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
  13:       0x74f01a8e50 - std::panicking::begin_panic_handler::{{closure}}::hcf42400a9d790530
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  14:       0x74f01a65e0 - std::sys_common::backtrace::__rust_end_short_backtrace::h2342dc9732bac816
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  15:       0x74f01a8b9c - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  16:       0x74f0173c6c - core::panicking::panic_fmt::hb5a3bb4964b0c3e5
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  17:       0x74f107e9d0 - rustc_codegen_ssa[74fc1c3c5b71e5ab]::back::write::submit_pre_lto_module_to_llvm::<rustc_codegen_llvm[1b908d8bc8097a4d]::LlvmCodegenBackend>
  18:       0x74f1093424 - rustc_codegen_ssa[74fc1c3c5b71e5ab]::base::codegen_crate::<rustc_codegen_llvm[1b908d8bc8097a4d]::LlvmCodegenBackend>
  19:       0x74f114749c - <rustc_codegen_llvm[1b908d8bc8097a4d]::LlvmCodegenBackend as rustc_codegen_ssa[74fc1c3c5b71e5ab]::traits::backend::CodegenBackend>::codegen_crate
  20:       0x74f0f99a9c - <rustc_session[ea50cdf2329050f6]::session::Session>::time::<alloc[468a75449262db6e]::boxed::Box<dyn core[b03a23c0b1ad7c0f]::any::Any>, rustc_interface[3aa2fa5c68d4a204]::passes::start_codegen::{closure#0}>
  21:       0x74f0f840e8 - rustc_interface[3aa2fa5c68d4a204]::passes::start_codegen
  22:       0x74f0f8933c - <rustc_interface[3aa2fa5c68d4a204]::queries::Queries>::ongoing_codegen
  23:       0x74f0eb7af0 - rustc_span[66e0f95f086a3269]::with_source_map::<core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>, rustc_interface[3aa2fa5c68d4a204]::interface::run_compiler<core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>, rustc_driver[9f1b6a52b0dd68ae]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  24:       0x74f0e78ba0 - std[7feb15765dd04eb9]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[3aa2fa5c68d4a204]::util::run_in_thread_pool_with_globals<rustc_interface[3aa2fa5c68d4a204]::interface::run_compiler<core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>, rustc_driver[9f1b6a52b0dd68ae]::run_compiler::{closure#1}>::{closure#0}, core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>>
  25:       0x74f0e59938 - <<std[7feb15765dd04eb9]::thread::Builder>::spawn_unchecked_<rustc_interface[3aa2fa5c68d4a204]::util::run_in_thread_pool_with_globals<rustc_interface[3aa2fa5c68d4a204]::interface::run_compiler<core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>, rustc_driver[9f1b6a52b0dd68ae]::run_compiler::{closure#1}>::{closure#0}, core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[b03a23c0b1ad7c0f]::result::Result<(), rustc_errors[28c301a58c9647e]::ErrorGuaranteed>>::{closure#1} as core[b03a23c0b1ad7c0f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:       0x74f01b2244 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfe25f74c518ac12a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  27:       0x74f01b2244 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b0378ef6e4cba7b
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  28:       0x74f01b2244 - std::sys::unix::thread::Thread::new::thread_start::hb538de1aed212c9a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  29:       0x74effcd5c8 - <unknown>
  30:       0x74f0035d1c - <unknown>
  31:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0 (2c8cc3432 2023-03-06) running on aarch64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=1 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `timg`
lrne@localhost[/home/lrne/Project/Rust/timg/]                                                                         [101] 10:35:55
    $
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by saethlin** [comment] 2023-06-12 01:31
I am closing this because it is an incremental compilation ICE related to a component of rustc that has gotten a fair few tweaks recently; it is entirely possible that the root cause of this issue has been fixed.

If you see a crash like this again on Rust 1.70 or later please do not hesitate to open a new issue.

**Closed by saethlin** 2023-06-12 01:31 UTC
Labels: I-ICE, T-compiler, A-incr-comp, C-bug
