### ISSUE TITLE
Cant install rust-analysis-x86_64-pc-windows-msvc after moving from rust stable to nightly

### ISSUE THREAD

**Issue by JohnKinyanjui** [rust-lang/rust#90593] opened 2021-11-04 22:31 UTC
info: downloading component 'rust-analysis'
info: installing component 'rust-analysis'
info: rolling back changes
error: failed to install component: 'rust-analysis-x86_64-pc-windows-msvc', detected conflict: 'lib/rustlib/x86_64-pc-windows-msvc/analysis/libaddr2line-0f12a58279e7246b.json'

**Comment by jyn514** [comment] 2021-11-05 16:53
cc @kinnison - I think the issue is that the toolchain directory doesn't have the channel in it?

**Comment by kinnison** [comment] 2021-11-08 12:23
This kind of thing happens from time to time - but we have yet to catch it in action and thus understand *how* the manifest can go missing.  The "easy" fix for this is to uninstall and reinstall the toolchain, I'm sorry that I don't have a good answer right now.

**Comment by JohnKinyanjui** [comment] 2021-11-08 20:04
@kinnison to reproduce its mostly happens when you change from rust stable to nightly, it tool chain works properly but the error shows up when updating the rust language server

**Comment by Dylan-DPC** [comment] 2023-02-20 07:55
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks

**Closed by Dylan-DPC** 2023-02-20 07:55 UTC
