### ISSUE TITLE
enum discriminants have problems with `const_eval` and truncation

### ISSUE THREAD

**Issue by jld** [rust-lang/rust#9837] opened 2013-10-13 20:38 UTC
```Rust
static S: i16 = 0x12345678;
enum E { V = S }
fn main() { assert_eq!(S as u64, V as u64); }
```
Result:
```
task '<unnamed>' failed at 'assertion failed: `(left == right) && (right == left)` (left: `22136u64`, right: `305419896u64`)', testcase.rs:3`
```

Currently blocking #9613, because 32-bit `std::int::min_value` is `0xffffffff7fffffff` (if you use all the bits of the `const_eval` result and not just the low 32) and so the discriminant is auto-sized to `u64`, meaning that `0x7fffffff` does not match any of its variants.

I'm thinking that `check_enum_variants` needs to do whatever `const_eval` would do if the expression had an `as u64` around it.

**Comment by steveklabnik** [comment] 2015-01-23 01:15
Triage: wow, I used to be a noob :)

```
static S: isize = 0x12345678;

enum E { V = S }

fn main() { assert_eq!(S as u64, E::V as u64); }
```

This now error swith:

```
hello.rs:3:14: 3:15 error: expected constant: non-constant path in constant expr [E0080]
hello.rs:3 enum E { V = S }
                        ^
```

So it seems like this is still an issue?

**Comment by steveklabnik** [comment] 2015-01-23 01:16
marking as 'typesystem' because it would seem like a `const` should be usable here.

**Comment by jld** [comment] 2015-01-26 00:46
I thought the `enum` stuff used `const_eval`, and that ought to work on `const`s/`static`s, so I'm not sure why that's failing — might be worth filing as its own bug?

**Comment by P1start** [comment] 2015-01-26 00:55
@steveklabnik That example uses a `static`, which isn’t a valid constant expression. The following is the closest I could get to the original example:

```rust
const S: i16 = 0x12345678;

enum E { V = S as isize }

fn main() { assert_eq!(S as u64, E::V as u64); }
```

And it still panics with the error in the original post (so this is still an issue).

**Comment by pnkfelix** [comment] 2015-03-31 17:17
cc #23897

**Comment by eefriedman** [comment] 2015-06-30 16:59
This is fixed in nightly.

**Comment by eefriedman** [comment] 2015-06-30 17:00
Err, wait, nevermind, wrong bug; sorry about the noise.

**Comment by oli-obk** [comment] 2015-12-18 09:57
note that this has a warning now:

```
<anon>:1:16: 1:26 warning: literal out of range for i16, #[warn(overflowing_literals)] on by default
<anon>:1 const S: i16 = 0x12345678;
```

**Comment by jld** [comment] 2015-12-21 18:59
The warning definitely helps, but here's an interesting variation:

```Rust
const C1: i32 = 0x12345678;
const C2: isize = C1 as i16 as isize;
enum E { V = C2 }
fn main() { assert_eq!(C2 as u64, E::V as u64); }
```

No warnings on stable or nightly, but still panics.

**Comment by pmarcelll** [comment] 2016-09-18 16:15
I cannot reproduce the panic on nightly.

**Comment by frewsxcv** [comment] 2016-09-18 17:02
Added a regression test in https://github.com/rust-lang/rust/pull/36566.

**Closed** 2016-09-24 04:15 UTC
Labels: A-typesystem
