### ISSUE TITLE
Beta Regression: cannot reference Self from where clause for inherent impl

### ISSUE THREAD

**Issue by bytwise** [rust-lang/rust#24944] opened 2015-04-29 14:35 UTC
The following code compiles with `rustc 1.0.0-beta (9854143cb 2015-04-02) (built 2015-04-02)` but does not compile with `rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)`

``` rust
trait Foo {
    fn foo(&self);
}

struct Bar<T>(T);

impl<T> Bar<T> where Self: Foo {}

fn main() {}
```

**Comment by pnkfelix** [comment] 2015-04-29 14:39
Specifically, the error message one gets (at least with my beta build) is:
```
% ./x86_64-apple-darwin/stage1/bin/rustc /tmp/r.rs
/tmp/r.rs:7:22: 7:26 error: use of undeclared type name `Self`
/tmp/r.rs:7 impl<T> Bar<T> where Self: Foo {}
                                 ^~~~
error: aborting due to previous error
```

**Comment by pnkfelix** [comment] 2015-04-29 14:41
However, this may be deliberate.  At least, I don't remember what the rules are about when `Self` is in scope, if at all, within `impls` -- I tend to only use it within `trait` definitions, myself.

**Comment by bombless** [comment] 2015-04-29 14:50
No way, this is definitely wrong.
`Self` is a keyword, the compiler should never print error message like that.

**Comment by pnkfelix** [comment] 2015-04-29 14:56
@bombless there's a difference nonetheless between a poor error message and a regression in the compiler itself.  I'm trying to identify exactly what this is.

**Comment by pnkfelix** [comment] 2015-04-29 14:58
(I have a strong suspicion that this change was injected by PR #23998, which was a fix for #23909.  I am doing some builds to try to verify that suspicion now.)

**Comment by pnkfelix** [comment] 2015-04-29 15:58
(no, from locally building at 926f38e it seems like PR #23998 is *not* the source of the "regression" here.)

**Comment by Stebalien** [comment] 2015-04-29 17:43
It is according to rust-lang/rfcs#522.

**Comment by pnkfelix** [comment] 2015-04-29 18:07
@Stebalien it is (what) according to rust-lang/rfcs#522 ?   Supposed to be allowed?  Behaving as specified?

**Comment by arielb1** [comment] 2015-04-29 18:45
@bombless 

This is just the standard error message you get when you try to use `Self` outside of a trait, e.g.
```Rust
fn foo(_: Self) {}
```

**Comment by Stebalien** [comment] 2015-04-29 18:53
> @Stebalien it is (what) according to rust-lang/rfcs#522 ? Supposed to be allowed? Behaving as specified?

IMHO, it should be allowed.

**Comment by pnkfelix** [comment] 2015-04-29 20:37
cc @nrc : was this an intentional side-effect of  #23998, or is this an inadvertent bug that we should fix?

(If its a bug, I'm assuming we can prioritizing fixing it based on how much breakage we observe on crates.io ?)

**Comment by bombless** [comment] 2015-04-29 23:35
@arielb1 
You're right, filed an issue https://github.com/rust-lang/rust/issues/24968

**Comment by nrc** [comment] 2015-04-30 04:26
@pnkfelix it was not deliberate. I don't really have an opinion on whether it is right or wrong as stands, I guess if you can write a bound on the concrete version of `Self`, you should be able to use `Self` itself.

**Comment by pnkfelix** [comment] 2015-04-30 09:52
triage: I-nominated

I want to figure out how important it is to fix this.

I *suspect* we can get away with just treating it as "just a bug" -- that is, I have not found a way to utilize it in a way that it would be a breaking-change to fix it.  For example, something like this, where `Self` might be referring to an outer type, does not compile today (and thus gives me confidence that we can fix this tomorrow):

```rust
    trait A { fn foo(&self) { } }
    struct S;
    struct T;
    impl A for S { }
    impl S {
        fn foo(&self) {
            impl T where Self: A { }
        }
    }
```

**Comment by pnkfelix** [comment] 2015-04-30 21:49
triage: P-medium

**Comment by steveklabnik** [comment] 2016-06-27 22:15
Triage: these examples still error, though with slightly different messages.

**Comment by Mark-Simulacrum** [comment] 2017-06-19 23:00
Re-nominating: The issue description compiles, though as far as I can tell, it probably shouldn't, since `Self: Foo` isn't being met -- and cannot be met, I think, due to coherence. Perhaps this is working as intended though. We should decide and either close this (if yes) or keep it open if no.

```rust
trait Foo {
    fn foo(&self);
}

struct Bar<T>(T);

impl<T> Bar<T> where Self: Foo {}

fn main() {}
```

**Comment by nikomatsakis** [comment] 2017-07-06 19:51
Behaving as expected. At some point we decided that `Self`, in an inherent impl, referred to the type on which the impl is defined, which is what is happening here. It's ok that the where-clause cannot be fulfilled -- it might be implemented in a downstream crate, for eample.

**Closed by nikomatsakis** 2017-07-06 19:51 UTC
Labels: I-nominated, P-medium, T-lang
