### ISSUE TITLE
docs: Inaccessible/private types are shown under `Show` implementors

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#18278] opened 2014-10-24 15:02 UTC
Head to [`Show`](http://doc.rust-lang.org/std/fmt/trait.Show.html) doc page. You'll see the following implementors:

- Flavor (sync::mutex)
- Failure (sync::comm::sync)

The former is a private type and the latter is inaccessible (`comm::sync` is private). These two shouldn't show in the docs.

**Comment by alexcrichton** [comment] 2015-04-07 02:06
This may be fixed, but needs more investigation. I believe this is a dupe of #14586, however.

**Closed by alexcrichton** 2015-04-07 02:06 UTC
Labels: A-rustdoc
