### ISSUE TITLE
Drop glue is always inlined into caller crate

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#64140] opened 2019-09-04 02:47 UTC
I was investigating the compile time of a crate recently and came across a surprising aspect of the compiler. It looks like the drop glue, or rather the code necessary to drop a type, is inlined unconditionally into the caller crate, even if there are no generics in play.

This program:

```rust
pub fn a(_: std::process::Command) {}
```

[generates a whopping 15 thousand lines of LLVM IR](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4be3849f90cf68d7c84e953ffae35251). Now `Command` certainly is a large type and I think it's fine that its drop glue is that big, but this is a concrete type and *every single crate which uses `Command` is generating this 15 thousand lines of IR*. 

At least in debug mode we shouldn't be doing this for concrete types, but rather the destructor of `Command` should be compiled into the standard library and then crates which use it should link against this precompiled copy. I would go as far as to argue that this should almost always happen and only when instructed otherwise should the compiler inline destructors across crates (same as for all other methods).

cc @michaelwoerister, do you know if this was a deliberate decision, and is this perhaps something that's relatively easily fixed or something that would be much more intrusive to experiment with?

**Comment by alexcrichton** [comment] 2019-09-04 02:49
For a smaller reproduction of this:

```
$ cat bar.rs
pub struct A(String);
$ cat foo.rs
pub fn a(_: bar::A) {}
$ rustc bar.rs --crate-type rlib
$ rustc foo.rs --crate-type rlib --extern bar=libbar.rlib --emit llvm-ir
$ wc -l foo.ll
980 foo.ll
```

where [this is the generated LLVM IR](https://gist.github.com/alexcrichton/c6b06c18c73654371de88a6d675fc10c)

**Comment by michaelwoerister** [comment] 2019-09-04 08:35
I remember that @arielb1 was tuning `inline` attributes for drop-glue at some point. It might have been deliberate but I don't remember anything that would make it necessary for correctness. It was probably just easier to implement that way. Seems like something that we should fix though.

**Comment by michaelwoerister** [comment] 2020-01-30 15:08
It seems like #68414 might help fixing this but is not sufficient on its own because `libstd` is compiled with `-Zshare-generics=no`. I'll do experiments with changing that.

**Comment by jonas-schievink** [comment] 2020-01-31 22:58
This seems like a duplicate of https://github.com/rust-lang/rust/issues/38827

**Comment by Mark-Simulacrum** [comment] 2022-02-23 14:12
Closing in favor of https://github.com/rust-lang/rust/issues/38827, I agree this is a duplicate.

**Closed by Mark-Simulacrum** 2022-02-23 14:12 UTC
Labels: A-codegen, I-compiletime, T-compiler
