### ISSUE TITLE
Compile time bounds checking doesn't work anymore for passed array references

### ISSUE THREAD

**Issue by bluec0re** [rust-lang/rust#114840] opened 2023-08-15 07:16 UTC
### Code

I tried this code:

```rust
fn bar(a: &mut [usize; 5]) {
    a[5] = 7;
}

pub fn main() {
    let mut a = [0usize; 5];
    bar(&mut a);
}
```

I expected to see this happen (as it did with 1.60):
```
error: this operation will panic at runtime
 --> <source>:2:5
  |
2 |     a[5] = 7;
  |     ^^^^ index out of bounds: the length is 5 but the index is 5
  |
  = note: `#[deny(unconditional_panic)]` on by default
```

Instead, this happened:

Compiles and than fails at runtime
```
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5', /app/example.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version it worked on

It most recently worked on: [1.60](https://godbolt.org/z/cKf3E1evP)

### Version with regression

[1.61 onwards](https://godbolt.org/z/PeMhbGecE)

Looks similar to this older bug report: #98444

**Comment by apiraino** [comment] 2023-08-15 09:18
Yeah, I think it's a duplicate of #98444 (which IIUC was never completely solved).

I'm closing this as duplicate and reopening the former (in case it's not the correct procedure, feel free to reopen)

@rustbot label -I-prioritize -needs-triage

**Closed** 2023-08-15 09:25 UTC
Labels: C-bug, regression-untriaged
