### ISSUE TITLE
LALRPOP doc source is broken.

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#57491] opened 2019-01-10 12:51 UTC
https://docs.rs/lalrpop/0.16.2/src/lalrpop/api/mod.rs.html should have source code.

@QuietMisdreavus

**Comment by jonas-schievink** [comment] 2019-01-10 13:08
Yeah this happened on all crates at the time. Newly published versions render fine though, so this might be fixed already.

**Comment by QuietMisdreavus** [comment] 2019-01-10 14:58
Duplicate of https://github.com/rust-lang/docs.rs/issues/280. I've rebuilt the docs for that version of lalrpop and the issue is fixed.

Individual crates need to be rebuilt by hand to fix problems introduced by rustdoc itself. Docs.rs does not actively rebuild old documentation with new compilers.

**Closed by QuietMisdreavus** 2019-01-10 14:58 UTC
