### ISSUE TITLE
mutably captured default int emits type inference error in closure

### ISSUE THREAD

**Issue by blaenk** [rust-lang/rust#21347] opened 2015-01-18 05:08 UTC
Really had no idea what to call this, feel free to change. As soon as I annotate the type of `i` when I create it or when I add to it, it works. I of course intended to annotate the type, but I did notice this and figured I'd post it in case it's not intentional.

``` rust
extern crate libc;

fn main() {
    fn f<F>(f: F) where F: FnMut(&str) {
      let down = &f as *const _ as *mut libc::c_void;
      let up = down as *mut F;
      let s = "lol what";
      unsafe { (*up)(s); }
    }
    
    let mut i = 3;
    
    f(|&mut: data: &str| {
        println!("data is: {}", data);
        i += 3;
    });
    
    println!("i is now: {}", i);
}
```

Error:

```
<anon>:13:5: 13:6 error: unable to infer enough type information about `closure[<anon>:13:7: 16:6]`; type annotations required
<anon>:13     f(|&mut: data: &str| {
              ^
error: aborting due to previous error
playpen: application terminated with error code 101
```

[playpen](http://is.gd/mi7QaJ)

**Comment by blaenk** [comment] 2015-01-18 05:09
Nevermind. @Aatch confirmed that it's a known bug.

**Comment by Aatch** [comment] 2015-01-18 05:11
Dupe of #20558

**Closed by Aatch** 2015-01-18 05:11 UTC
