### ISSUE TITLE
Can't cross-build rustc for aarch64-apple-darwin anymore

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#76733] opened 2020-09-15 03:47 UTC
With the following config.toml:
```
[build]
build = "x86_64-apple-darwin"
host = ["aarch64-apple-darwin"]
target = ["aarch64-apple-darwin"]
```
when building on a Apple Silicon DTK, you'd get an aarch64-apple-darwin rustc and libstd. That's not the case since #76415, where you only end up with an x86_64-apple-darwin compiler and libstd. There isn't even a build/aarch64-apple-darwin directory at all.

**Comment by glandium** [comment] 2020-09-15 04:24
For the record, since multiple commits are involved in #76415, bisect points to 3193d52a21576b8c93f00132c784cce1159f733e

**Comment by jyn514** [comment] 2020-09-15 12:17
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment] 2020-09-15 13:18
How are you invoking x.py?

I've just run src/ci/docker/run.sh dist-arm-linux, which has an almost-identical configuration, just targeting arm-unknown-linux-gnueabi instead of aarch64-apple-darwin, which runs `x.py dist --host arm-unknown-linux-gnueabi --target arm-unknown-linux-gnueabi`.

That gets me the following in build/dist:

```
cargo-nightly-arm-unknown-linux-gnueabi.tar.gz
cargo-nightly-arm-unknown-linux-gnueabi.tar.xz
clippy-nightly-arm-unknown-linux-gnueabi.tar.gz
clippy-nightly-arm-unknown-linux-gnueabi.tar.xz
llvm-tools-nightly-arm-unknown-linux-gnueabi.tar.gz
llvm-tools-nightly-arm-unknown-linux-gnueabi.tar.xz
miri-nightly-arm-unknown-linux-gnueabi.tar.gz
miri-nightly-arm-unknown-linux-gnueabi.tar.xz
rls-nightly-arm-unknown-linux-gnueabi.tar.gz
rls-nightly-arm-unknown-linux-gnueabi.tar.xz
rust-analysis-nightly-arm-unknown-linux-gnueabi.tar.gz
rust-analysis-nightly-arm-unknown-linux-gnueabi.tar.xz
rust-analyzer-nightly-arm-unknown-linux-gnueabi.tar.gz
rust-analyzer-nightly-arm-unknown-linux-gnueabi.tar.xz
rust-dev-nightly-arm-unknown-linux-gnueabi.tar.gz
rust-dev-nightly-arm-unknown-linux-gnueabi.tar.xz
rust-nightly-arm-unknown-linux-gnueabi.tar.gz
rust-nightly-arm-unknown-linux-gnueabi.tar.xz
rust-src-nightly.tar.gz
rust-src-nightly.tar.xz
rust-std-nightly-arm-unknown-linux-gnueabi.tar.gz
rust-std-nightly-arm-unknown-linux-gnueabi.tar.xz
rustc-dev-nightly-arm-unknown-linux-gnueabi.tar.gz
rustc-dev-nightly-arm-unknown-linux-gnueabi.tar.xz
rustc-nightly-arm-unknown-linux-gnueabi.tar.gz
rustc-nightly-arm-unknown-linux-gnueabi.tar.xz
rustfmt-nightly-arm-unknown-linux-gnueabi.tar.gz
rustfmt-nightly-arm-unknown-linux-gnueabi.tar.xz
```

I also see a build/aarch64-apple-darwin/stage2 directory and it contains a stage2 compiler, as expected.


x.py build doesn't work (still) in the sense that it doesn't assemble a compiler for you, but it does build all the components. This is due to the (prior) change in defaults where --stage 1 for a cross-compilation build doesn't really make a lot of sense, but is what we default to now.

**Comment by glandium** [comment] 2020-09-15 21:58
`x.py build --stage 2` is what I was running, and before 3193d52, I'd get a build/aarch64-apple-darwin/stage2 directory. After, I don't get a build/aarch64-apple-darwin at all.

**Comment by glandium** [comment] 2020-09-15 23:42
`x.py dist` creates a `build/aarch64-apple-darwin/stage2` tree but fails before actually filling it with
```
error: failed to test example in lint docs for `ill_formed_attribute_input` in /Users/glandium/rust/compiler/rustc_session/src/lint/builtin.rs:12: did not find lint `ill_formed_attribute_input` in output of example, got:
error[E0463]: can't find crate for `std`


error: aborting due to previous error


For more information about this error, try `rustc --explain E0463`.



command did not execute successfully: "/Users/glandium/rust/build/x86_64-apple-darwin/stage0-tools-bin/lint-docs" "--src" "/Users/glandium/rust/compiler" "--out" "/Users/glandium/rust/build/aarch64-apple-darwin/md-doc/rustc/src/lints" "--rustc" "/Users/glandium/rust/build/x86_64-apple-darwin/stage2/bin/rustc"
expected success, got: exit code: 1


failed to run: /Users/glandium/rust/build/bootstrap/debug/bootstrap dist
```

**Comment by Mark-Simulacrum** [comment] 2020-09-15 23:56
Hm, and that's on latest master? I guess I can try to reproduce this on a DTK, but I find it pretty odd that you're seeing different behavior than I am for essentially equivalent configurations, just different concrete targets...

Do you have anything else in config.toml?

**Comment by glandium** [comment] 2020-09-16 00:14
It was on latest master or close when I filed, which was 9b4154193e8471f36b1a9e781f1ef7d492fc6a6c. My config.toml is literally what I pasted (didn't copy from config.toml.example).

**Comment by glandium** [comment] 2020-09-16 00:32
I can reproduce on current master (6af1bdda54abc9e919fc1137411dfc4311e05649) on Linux with the following config.toml:
```
[build]
build = "x86_64-unknown-linux-gnu"
host = ["i686-unknown-linux-gnu"]
target = ["i686-unknown-linux-gnu"]
```
(no build/i686-unknown-linux-gnu) and if I revert 3193d52, it works again.

**Comment by Mark-Simulacrum** [comment] 2020-09-16 14:32
Okay, I've been able to reproduce. I guess something about the docker container (dist-arm-linux) is different perhaps? Or I wasn't building on the right commit before -- not sure.

Looking at fixing now.

**Comment by Mark-Simulacrum** [comment] 2020-09-16 16:55
Both bugs should be fixed by https://github.com/rust-lang/rust/pull/76799.

**Comment by spastorino** [comment] 2020-09-16 18:19
This looks more like `T-infra` than `T-compiler`, I guess I'd leave it up to @Mark-Simulacrum in case they want to prioritize it.

**Closed** 2020-09-22 08:11 UTC
Labels: A-cross, A-rustbuild, C-bug, I-prioritize, T-infra, regression-from-stable-to-nightly
