### ISSUE TITLE
Clients of the new path need to be updated for non-utf8 paths

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#9639] opened 2013-10-01 00:17 UTC
The new Path module (coming soon) represents POSIX paths as vectors (#7225) of non-NUL bytes instead of as `~str`. This is because Linux allows for non-unicode paths.

Unfortunately, there are a lot of clients of `Path`, including related functionality like `Process` arguments and environment variables, that still use `&str`. These need to be updated to handle `&[u8]` so they can represent non-unicode `Path`s.

All of the known locations where this is an issue are marked up by `// FIXME` lines referencing this issue. Note that in the case of `Process` args and environments, these comments are at the usage locations rather than the implementation.

Sub-tasks that have been filed for various components:
- [ ] #11916 `glob("*")` does not support matching non-utf8 filenames
- [x] #11650 `Process::new` and `dynamic_library::open_external` should take `&[u8]`s, not `Path`s or `~strs`

**Comment by alexcrichton** [comment] 2015-01-05 08:28
This has largely been accomplished since this was written both in terms of an implementation strategy as well as propagating throughout the libraries. The stabilization passes we've been doing will turn up any more related clients, and I've requested that the remaining issue, #11916, be transferred to the rust-lang/rust repo, so closing.

**Closed by alexcrichton** 2015-01-05 08:28 UTC
Labels: A-unicode

**Comment by Eh2406** [comment] 2017-09-03 20:27
There is a FIXME related to this issue,
https://github.com/rust-lang/rust/blob/master/src/test/run-make/relocation-model/Makefile#L538
https://github.com/rust-lang/rust/blob/master/src/test/run-make/relocation-model/Makefile#L641
https://github.com/rust-lang/rust/blob/master/src/test/run-make/relocation-model/Makefile#L1497
Now that the issue is closed can the FIXME be fix, or made more specific?
