### ISSUE TITLE
Don't require Valgrind for tests by default

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#20580] opened 2015-01-05 16:36 UTC
```
$ make check-stage2-pretty-rpass
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: enabling more debugging (CFG_ENABLE_DEBUG)
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: good valgrind for x86_64-unknown-linux-gnu is 1
cfg: using CC=gcc (CFG_CC)
cfg: enabling valgrind run-pass tests (CFG_ENABLE_VALGRIND_RPASS)
cfg: no pandoc found, omitting PDF and EPUB docs
cfg: including test rules
cfg: valgrind-path set to 
cfg: valgrind-path set to 
cfg: valgrind-path set to 
cfg: valgrind-path set to 
cfg: javac not available, skipping lexer test...
rustc: x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/bin/compiletest
cp: x86_64-unknown-linux-gnu/stage2/bin/compiletest
run pretty-rpass [x86_64-unknown-linux-gnu]: x86_64-unknown-linux-gnu/stage2/bin/compiletest
thread '<main>' panicked at 'Can't find Valgrind to run Valgrind tests', /home/manishearth/Mozilla/rust/src/compiletest/compiletest.rs:45
make: *** [tmp/check-stage2-T-x86_64-unknown-linux-gnu-H-x86_64-unknown-linux-gnu-pretty-rpass.ok] Error 101
```

We don't need Valgrind for `rpass-pretty`, we probably shouldn't crash on that.

**Comment by brson** [comment] 2015-01-07 03:02
Dupe of https://github.com/rust-lang/rust/issues/18588

**Closed by brson** 2015-01-07 03:02 UTC
Labels: A-testsuite
