### ISSUE TITLE
Regression in Error conversion from Infallible

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#66757] opened 2019-11-25 21:15 UTC
The following code:

```rust
use std::convert::{TryFrom, Infallible};

struct E;

impl From<Infallible> for E {
    fn from(_: Infallible) -> E {
        E
    }
}

fn foo() -> Result<(), E> {
    u32::try_from(1u32)?;
    Ok(())
}
```

[compiles on stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=497c2032a83849e5cf80c81e32eccf9c) but [fails to compile on nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=497c2032a83849e5cf80c81e32eccf9c) with:

```
error[E0277]: `?` couldn't convert the error to `E`
  --> src/lib.rs:13:24
   |
13 |     u32::try_from(1u32)?;
   |                        ^ the trait `std::convert::From<()>` is not implemented for `E`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <E as std::convert::From<!>>
   = note: required by `std::convert::From::from`
```

This was discovered through https://github.com/bytecodealliance/wasmtime/issues/633

**Comment by alexcrichton** [comment] 2019-11-25 21:17
Bisection reveals https://github.com/rust-lang/rust/pull/66607 as the cause, likely https://github.com/rust-lang/rust/pull/65355

**Comment by SimonSapin** [comment] 2019-11-25 21:49
Reduced:

```rust
struct E;

impl From<!> for E {
    fn from(_: !) -> E {
        E
    }
}

#[allow(unreachable_code)]
fn foo(never: !) {
    <E as From<!>>::from(never);  // Ok
    <E as From<_>>::from(never);  // Inference fails here
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dd24db4d6822f64baf3c8fbf0684f89b))

**Comment by Centril** [comment] 2019-11-25 21:53
(Adding `#![feature(never_type_fallback)]` resolves the issue.)

**Comment by SimonSapin** [comment] 2019-11-25 21:53
The above went through this doc-comment of the desugaring of `foo?`, which wasn’t easy to find:

https://github.com/rust-lang/rust/blob/91642e3ac0120c8e9cdd5f3c85ad03f3bf1b8b69/src/librustc/hir/lowering/expr.rs#L1199-L1209

**Comment by SimonSapin** [comment] 2019-11-25 22:11
> (Adding `#![feature(never_type_fallback)]` resolves the issue.)

That explains where the `()` comes from, thanks. But it’s not clear to me why fallback should happen in the first place in this code.

**Comment by Centril** [comment] 2019-11-25 22:15
Unclear to me also; cc @nikomatsakis and @arielb1 -- also cc #65992

**Comment by acfoltzer** [comment] 2019-11-26 21:09
The same result also occurs when the desired error type is transitively `From<!>`, which seems to come up pretty commonly in the wild since std errors like `TryFromIntError` are `From<!>`:

```rust
use std::convert::{TryFrom};

struct E;

impl From<!> for E {
    fn from(_: !) -> E {
        E
    }
}

struct F;

impl From<E> for F {
    fn from(_: E) -> F {
        F
    }
}

fn foo() -> Result<(), F> {
    u32::try_from(1u32)?;
    Ok(())
}
```

```
error[E0277]: `?` couldn't convert the error to `F`
  --> src/lib.rs:20:24
   |
20 |     u32::try_from(1u32)?;
   |                        ^ the trait `std::convert::From<()>` is not implemented for `F`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <F as std::convert::From<E>>
   = note: required by `std::convert::From::from`
```

**Comment by SimonSapin** [comment] 2019-11-26 21:37
@acfoltzer Your example legitimately does not compile, although the error message is wrong in Nightly because of this bug. `From` conversions have never worked transitively. The `impl From<!> for E` does not affect your example, you get the same results without it. The `!` here comes from `<u32 as TryFrom<u32>>::Error`

**Comment by acfoltzer** [comment] 2019-11-26 21:53
@SimonSapin Hmm, that wasn't the change I was expecting would make the example compile, but the fact that it doesn't change the behavior is a surprise.

What I thought was the telling change is whether it compiles after removing the `impl From<E> for F` rather than `impl From<!> for E`. But it looks like that happens regardless of the `From<!>`:

```rust
use std::convert::TryFrom;

struct E;

struct F;

impl From<E> for F {
    fn from(_: E) -> F {
        F
    }
}

fn foo() -> Result<(), F> {
    u32::try_from(1u32)?;
    Ok(())
}
```

```
error[E0277]: `?` couldn't convert the error to `F`
  --> src/lib.rs:14:24
   |
14 |     u32::try_from(1u32)?;
   |                        ^ the trait `std::convert::From<()>` is not implemented for `F`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following implementations were found:
             <F as std::convert::From<E>>
   = note: required by `std::convert::From::from`
```

vs the following, which compiles fine:

```rust
use std::convert::TryFrom;

struct F;

fn foo() -> Result<(), F> {
    u32::try_from(1u32)?;
    Ok(())
}
```

Maybe this is a distinct issue?

**Comment by SimonSapin** [comment] 2019-11-26 22:48
Oooh that’s interesting! Adapting this to the reduced failure from https://github.com/rust-lang/rust/issues/66757#issuecomment-558355460: *removing* the `impl From<!> for E` makes that code compile:

```rust
pub struct E;

#[allow(unreachable_code)]
pub fn foo(never: !) {
    <E as From<_>>::from(never);
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e0aab0984eb4933294c42bce707afbbc))

I *think* what happens in the code that compiles is that the only `From<_>` trait implemented by `E` is `From<E>`, the identity conversion. So the call is `<E as From<E>>::from` which expects an argument of type `E`. It works out because `!` auto-coerces to `E` (or anything).

If we add `impl From<!> for E` (back), now `E as From<_>` becomes ambiguous. We have a type variable, not fully resolved in type inference, which is then unified with the argument expression passed to `from()`. That argument has type `!`, so the type variable is unified with the type `!`.

Presumably, the compiler then ends up here somehow:

https://github.com/rust-lang/rust/blob/797fd92628842c1f5face9fb93b0fe4f1f9d297f/src/librustc/ty/context.rs#L2442-L2449

**Comment by dtolnay** [comment] 2019-11-27 04:58
https://github.com/heim-rs/heim/issues/182 is hitting a variation of this which minimizes to:

```rust
fn from(e: std::convert::Infallible) -> Box<dyn std::error::Error> {
    Box::new(e)
}
```

Fine on stable/beta, fails on nightly with:

```console
error[E0277]: the trait bound `(): std::error::Error` is not satisfied
  --> src/main.rs:18:5
   |
18 |     Box::new(e)
   |     ^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `()`
   |
   = note: required for the cast to the object type `dyn std::error::Error`
```

**Comment by SimonSapin** [comment] 2019-11-27 15:33
So ideally we’d like the type variable `_` to unify with `!` in cases like this:

```rust
struct E;
impl From<!> for E {
    fn from(x: !) -> E { x }
}
fn foo(never: !) {
    <E as From<_>>::from(never);
}
```

And:

```rust
fn foo(e: !) -> Box<dyn std::error::Error> {
    Box::<_>::new(e)
}
```

But not in the case of older https://crates.io/crates/objc versions where that causes UB:

```rust
fn unconstrained_return<T>() -> Result<T, String> {
    let ffi: fn() -> T = transmute(some_pointer);
    Ok(ffi())
}
fn foo() {
    match unconstrained_return::<_>() {
        Ok(x) => x,  // `x` has type `_`, which is unconstrained
        Err(s) => panic!(s),  // … except for unifying with the type of `panic!()`
        // so that both `match` arms have the same type.
        // Therefore `_` resolves to `!` and we "return" an `Ok(!)` value.
    };
}
```

But in a world where `!` is a proper type, is there any fundamental difference between these examples? Or are they all cases of  https://github.com/rust-lang/rust/issues/65992?

I’m afraid that the answer is no, there’s no real difference. Which would mean that we can’t have all three of:

* Make `Infallible` an alias for `!`
* Not yet make the inference fallback change https://github.com/rust-lang/rust/issues/65992 (because `objc` mitigations are not ready yet)
* Not have the regressions in this issue.

… at the same time. And as we know, if `Infallible` is to ever be an alias for `!` we need to do it in the same release cycle as stabilizing the never type.

**Comment by pnkfelix** [comment] 2019-11-28 13:14
triage: P-high. Leaving nomination tag on this, since it seems like we'll need to discuss what action to take on it either this week or next week.

**Comment by pnkfelix** [comment] 2019-11-28 16:03
also, tagging this as T-lang: my interpretation of the [analysis above](https://github.com/rust-lang/rust/issues/66757#issuecomment-559136943) is that where it says "... [we cannot have all three of  ] 1. Make `Infallible` an alias for `!` ...", Simon mean more generally the idea that empty enums are all aliases for `!`. And deciding whether or not to keep that as a feature of `never_type` seems like a definite T-lang issue.

**Comment by SimonSapin** [comment] 2019-11-28 16:05
No, I mean defining `Infallible` specifically as a `type` item instead of an `enum` item. This change landed in the same PR as stabilization of the never type:

 https://github.com/rust-lang/rust/pull/65355/commits/089229a1935fa9795cfdefa518c8f8c3beb66db8#diff-da707dc4d90c85e7074dbdecebfe8785R643

**Comment by est31** [comment] 2019-11-28 16:08
Why should `Infallible` be ever made an alias for `!`? Why not just deprecate it without doing that? Everyone can switch to `!` instead.

**Comment by SimonSapin** [comment] 2019-11-28 16:11
@est31 `impl<T, U> TryFrom<U> for T where U: Into<T>` and `impl FromStr for String` use `Infallible` for their associated error type and are `#[stable]`.

**Comment by faern** [comment] 2019-11-28 17:39
That's what happens when things are rushed before they are done. We'll either have to 1) wait with things like `TryFrom` until they are ready. Or 2) be ready to make somewhat breaking changes later, or 3) settle for a forever suboptimal language. I'm in the break everything for the sake of a bright future camp.

**Comment by SimonSapin** [comment] 2019-11-28 17:50
“Rushed” is an interesting choice of word for a feature that was [stabilized](https://github.com/rust-lang/rust/pull/58302#event-2163312262) almost three years after it was [formally proposed](https://github.com/rust-lang/rfcs/pull/1542#issue-62653140).

**Comment by faern** [comment] 2019-11-28 18:05
If it had already waited three years a few more releases would not have made a large difference, relatively.

**Comment by pnkfelix** [comment] 2019-11-29 09:22
> also, tagging this as T-lang: my interpretation of the [analysis above](https://github.com/rust-lang/rust/issues/66757#issuecomment-559136943) is that where it says "... [we cannot have all three of ] 1. Make `Infallible` an alias for `!` ...", Simon mean more generally the idea that empty enums are all aliases for `!`. And deciding whether or not to keep that as a feature of `never_type` seems like a definite T-lang issue.

Oh, whoops, I totally misinterpreted the situation about what is going on with `Infallible` then. Sorry!

So ... its possible this is not a T-lang issue then? Is the T-libs team considering "just" reverting the definition of `Infallible` to be an empty enum again?

**Comment by SimonSapin** [comment] 2019-11-29 12:14
T-libs has not collectively discussed this issue yet. Every comment on mine in this thread so far (including this one) is from me individually.

I think we (the Rust project) have a number of possible ways to proceed here, and some of them do involve T-lang. As far as I can tell this is all options including bad ones:

1. We do nothing and ship 1.41.0 with the regressions in this issue. This is likely not acceptable under our stability promise.

2. We complete the mitigations for UB in old `objc` versions and land the inference fallback change https://github.com/rust-lang/rust/issues/65992, all in time for Rust 1.41.0. This fixes the regressions here.

3. We land the fallback change in 1.41 (fixing the regressions) without blocking on mitigations being complete, and either try to add mitigations later or give up on them.

4. We find some other way to fix the regressions while keeping `type Infallible = !;` and without introducing UB in old `objc` versions. I don’t know if this is possible. https://github.com/rust-lang/rust/issues/66757#issuecomment-559136943 is saying I’m afraid it’s not. **I’d appreciate input from T-lang or T-compiler on this.** In particular: what does “fallback” mean exactly? Is it possible and would it help to tweak that definition so that it happens in fewer cases?

5. We revert `Infallible` to an empty enum and give up on ever making it an alias of `!`. This would be unfortunate. `Infallible` was introduced in the first place on the basis that we could avoid this scenario. This fixes the regressions literally as reported here, but **new code would still be affected** if it uses similar patterns with `!` instead of `Infallible`. IMO it seems too easy to write reasonable-looking code that would be affected for `!` to be considered truly first-class in the language.

6. We revert `Infallible` to an empty enum in 1.41 and plan to make it an alias of `!` in a later release. T-libs discussed this before and considers it not acceptable under the stability promise since it would break stable code that separately implements a given trait for both `!` and `Infallible`.

7. We revert `Infallible` to an empty enum **and the stabilization of the never type**, effectively going back to the state of 1.40 as far as this issue is concerned, to give ourselves more time to complete one of the other options (ideally 2 or 4).

That’s it. I can’t think of anything else.

**Comment by nikomatsakis** [comment] 2019-12-02 19:09
A few quick thoughts:

@SimonSapin asked [in this comment](https://github.com/rust-lang/rust/issues/66757#issuecomment-559136943) whether there was a difference between the fallback used in a case like `<T as From<_>>::from(never)` (where `never: !`) and the fallback from the `objc` example. It seems to me that there *is* -- the fallback in the former case arises from a reference to a value of type `!`, whereas the fallback in the latter case arises from the result of an "abrupt" expression (e.g., `return` etc). 

I've not gone digging into the code but I believe that at first glance it should be possible to separate the two, so that `let x: _ = never` winds up with `x: !` but `let x: _ = return;` winds up with `x: ()`. In fact, it seems quite *surprising* to have `let x: _ = never` wind up with `x: ()`.

This would basically mean that the type of an abrupt expression like `return` is not `!` but rather a fresh type variable that falls back to `()`.

**Comment by dtolnay** [comment] 2019-12-02 19:25
From https://github.com/rust-lang/rust/issues/66757#issuecomment-559771169 I agree that 1 (shipping as is) is not acceptable. With holidays and ~2 weeks remaining in 1.41 we likely wouldn't have time for 2 (mitigations for the objc style inference change).

If Niko's suggestion of differentiating between references to an existing value of type `!` vs results of "abrupt" expressions would be possible to implement, that seems way better than option 5 (giving up on every making Infallible = !). So I would recommend option 7 -- revert back to the state as of 1.40 except now knowing what still needs to be fixed, implementing Niko's approach as soon as we get to it, and then moving forward with stabilization of `!` and Infallible=! in the same future release.

**Comment by SimonSapin** [comment] 2019-12-02 19:36
@dtolnay  That plan sounds good to me.

@nikomatsakis 
> In fact, it seems quite _surprising_ to have `let x: _ = never` wind up with `x: ()`.

I agree! Though right now that seems to cause an inference error:

```rust
#[allow(unreachable_code)]
pub fn foo(never: !) {
    let x: _ = never;
    // Access non-existent field to make the compiler print
    // an error message with the type of `x`
    x.bar;
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=be010bcb95bfabe1541ab1c8ae85bace)) Errors:

```rust
   Compiling playground v0.0.1 (/playground)
error[E0282]: type annotations needed
 --> src/lib.rs:6:5
  |
3 |     let x: _ = never;
  |         - consider giving `x` a type
...
6 |     x.bar;
  |     ^ cannot infer type
  |
  = note: type must be known at this point
```

**Comment by nikomatsakis** [comment] 2019-12-02 20:32
I agree with @dtolnay as well -- I think a revert is probably the most prudent step right now.

**Comment by nikomatsakis** [comment] 2019-12-02 20:40
@SimonSapin in your example, the problem has to do with when fallback occurs. When you see `x.bar`, fallback has not yet occurred, and so the type is not (yet) known. Field access (and the `.` operator in general) requires that the type be known, so you get an error.

However, code like this does compile, and I believe it is being assigned a type of `()` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=23ecc7b74c78205cb5f90525cd32c5cd)):

```rust
#![allow(unreachable_code)]

// Uncomment and you will get an error:
// #![feature(never_type_fallback)]

fn foo(never: !) {
    let x: _ = never;
    bar(x);
}

fn bar<T: Bar>(t: T) { }
trait Bar { }
impl Bar for u32 { }
impl Bar for () { }

fn main() { }
```

Trait resolution can wait until the end, after fallback has occurred.

**Comment by nikomatsakis** [comment] 2019-12-05 21:07
We discussed in [today's lang-team meeting](https://github.com/rust-lang/lang-team/blob/master/minutes/2019-12-05.md) and decided that the most prudent step is to revert. @Centril asked if someone else could prepare the PR -- any volunteers? 

We would like after that to pursue the mitigations a bit more actively, since it seems better to have a uniform fallback to `!` than to introduce the "split fallback" that I proposed in my previous comments. @llogiq you had previously expressed an interest, not sure if others are interested, but we may want to up the priority on that work (I can try to dedicate a bit more time to getting it started, too).

**Comment by llogiq** [comment] 2019-12-06 11:26
@nikomatsakis Sorry, I was swamped with other work. Also some pointers to the infer functions I need to use – how do I find out if a type comes from fallback? Or how do I set the fallback? – would be really helpful.

**Comment by nikomatsakis** [comment] 2019-12-06 14:22
@llogiq Not a problem at all! Happy to discuss further the fallback question on Zulip.

**Comment by pnkfelix** [comment] 2019-12-12 14:14
visiting for T-compiler triage. I think we can remove the nomination label; the immediate fire is being put out via PR #67224

**Closed** 2019-12-15 01:28 UTC
Labels: P-high, T-compiler, T-lang, T-libs, regression-from-stable-to-nightly
