### ISSUE TITLE
rustdoc cannot inline associated data type

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [rust-lang/rust#124596] opened 2024-05-01 21:13 UTC
I tried this code:

```rust
// `cargo +stable doc`
pub struct Buffer<const N: usize>([u8; N]);

impl<'a, const N: usize> TryFrom<&'a [u8]> for Buffer<N> {
    type Error = <[u8; N] as TryFrom<&'a [u8]>>::Error;

    fn try_from(slice: &'a [u8]) -> Result<Self, Self::Error> {
        <[u8; N]>::try_from(slice).map(Self)
    }
}
```

I expected to see this happen: rustdoc can resolve `type Error` as `std::array::TryFromSliceError`

Instead, this happened: rustdoc can't inline type (i.e. it shows `type Error = <[u8; N] as TryFrom<&'a [u8]>>::Error`)

### Meta

`rustc --version --verbose`:
```
rustc 1.77.2 (25ef9e3d8 2024-04-09)
binary: rustc
commit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04
commit-date: 2024-04-09
host: x86_64-unknown-linux-gnu
release: 1.77.2
LLVM version: 17.0.6
```

**Comment by fmease** [comment] 2024-05-02 14:13
Closing as dupe of #82692.

**Closed by fmease** 2024-05-02 14:13 UTC
Labels: T-rustdoc, C-discussion
