### ISSUE TITLE
ICE: unstable fingerprints for optimized_mir(rustc_middle)

### ISSUE THREAD

**Issue by torhovland** [rust-lang/rust#83817] opened 2021-04-03 17:43 UTC
This is happening when building Rust on WSL2 on Windows. `./x.py build` completes successfully, but `./x.py install` fails.

My `config.toml` looks like this:

```
# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[install]
prefix = "/home/tor/projects/rust/install"
```

### Error output

```
./x.py install                                                                   Sat 03 Apr 2021 05:05:30 PM UTC
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.11s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling rustc_codegen_ssa v0.0.0 (/home/tor/projects/rust/compiler/rustc_codegen_ssa)
   Compiling rustc_codegen_llvm v0.0.0 (/home/tor/projects/rust/compiler/rustc_codegen_llvm)
   Compiling rustc_interface v0.0.0 (/home/tor/projects/rust/compiler/rustc_interface)
   Compiling rustc_driver v0.0.0 (/home/tor/projects/rust/compiler/rustc_driver)
   Compiling rustc-main v0.0.0 (/home/tor/projects/rust/compiler/rustc)
    Finished release [optimized] target(s) in 13.91s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling cc v1.0.60
   Compiling core v0.0.0 (/home/tor/projects/rust/library/core)
   Compiling libc v0.2.88
   Compiling std v0.0.0 (/home/tor/projects/rust/library/std)
   Compiling compiler_builtins v0.1.39
   Compiling unwind v0.0.0 (/home/tor/projects/rust/library/unwind)
   Compiling rustc-std-workspace-core v1.99.0 (/home/tor/projects/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/home/tor/projects/rust/library/alloc)
   Compiling cfg-if v0.1.10
   Compiling adler v0.2.3
   Compiling rustc-demangle v0.1.18
   Compiling panic_abort v0.0.0 (/home/tor/projects/rust/library/panic_abort)
   Compiling rustc-std-workspace-alloc v1.99.0 (/home/tor/projects/rust/library/rustc-std-workspace-alloc)
   Compiling panic_unwind v0.0.0 (/home/tor/projects/rust/library/panic_unwind)
   Compiling gimli v0.23.0
   Compiling hashbrown v0.11.0
   Compiling miniz_oxide v0.4.0
   Compiling object v0.22.0
   Compiling addr2line v0.14.0
   Compiling rustc-std-workspace-std v1.99.0 (/home/tor/projects/rust/library/rustc-std-workspace-std)
   Compiling term v0.0.0 (/home/tor/projects/rust/library/term)
   Compiling proc_macro v0.0.0 (/home/tor/projects/rust/library/proc_macro)
   Compiling unicode-width v0.1.8
   Compiling getopts v0.2.21
   Compiling test v0.0.0 (/home/tor/projects/rust/library/test)
    Finished release [optimized] target(s) in 1m 09s
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling autocfg v1.0.0
   Compiling libc v0.2.88
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.65
   Compiling lazy_static v1.4.0
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.6.1
   Compiling log v0.4.11
   Compiling cc v1.0.60
   Compiling cfg-if v1.0.0
   Compiling maybe-uninit v2.0.0
   Compiling instant v0.1.6
   Compiling bitflags v1.2.1
   Compiling hashbrown v0.9.1
   Compiling getrandom v0.1.14
   Compiling typenum v1.12.0
   Compiling pin-project-lite v0.2.4
   Compiling version_check v0.9.1
   Compiling rustc-hash v1.1.0
   Compiling either v1.6.0
   Compiling rustc-rayon-core v0.3.1
   Compiling ppv-lite86 v0.2.8
   Compiling remove_dir_all v0.5.3
   Compiling arrayvec v0.5.1
   Compiling stable_deref_trait v1.2.0
   Compiling opaque-debug v0.3.0
   Compiling rustc_graphviz v0.0.0 (/home/tor/projects/rust/compiler/rustc_graphviz)
   Compiling cpuid-bool v0.1.2
   Compiling unicode-width v0.1.8
   Compiling scoped-tls v1.0.0
   Compiling termcolor v1.1.0
   Compiling annotate-snippets v0.8.0
   Compiling rustc_fs_util v0.0.0 (/home/tor/projects/rust/compiler/rustc_fs_util)
   Compiling datafrog v2.0.1
   Compiling serde_derive v1.0.125
   Compiling serde v1.0.125
   Compiling memchr v2.3.3
   Compiling tinyvec v0.3.4
   Compiling regex-syntax v0.6.22
   Compiling byteorder v1.3.4
   Compiling ryu v1.0.5
   Compiling serde_json v1.0.59
   Compiling itoa v0.4.6
   Compiling snap v1.0.1
   Compiling ansi_term v0.12.1
   Compiling fixedbitset v0.2.0
   Compiling build_helper v0.1.0 (/home/tor/projects/rust/src/build_helper)
   Compiling unicode-script v0.5.2
   Compiling rustc-demangle v0.1.18
   Compiling punycode v0.4.1
   Compiling pathdiff v0.2.0
   Compiling rustc_error_codes v0.0.0 (/home/tor/projects/rust/compiler/rustc_error_codes)
   Compiling tracing-core v0.1.17
   Compiling thread_local v1.0.1
   Compiling sharded-slab v0.1.1
   Compiling lock_api v0.4.1
   Compiling crossbeam-utils v0.7.2
   Compiling indexmap v1.6.0
   Compiling memoffset v0.5.5
   Compiling crossbeam-epoch v0.8.2
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling itertools v0.9.0
   Compiling generic-array v0.14.4
   Compiling getopts v0.2.21
   Compiling rustc_lexer v0.1.0 (/home/tor/projects/rust/compiler/rustc_lexer)
   Compiling psm v0.1.11
   Compiling stacker v0.1.12
   Compiling unicode-normalization v0.1.13
   Compiling rustc_llvm v0.0.0 (/home/tor/projects/rust/compiler/rustc_llvm)
   Compiling unicode-security v0.0.5
   Compiling ena v0.14.0
   Compiling polonius-engine v0.12.1
   Compiling tracing-log v0.1.2
   Compiling rustc_apfloat v0.0.0 (/home/tor/projects/rust/compiler/rustc_apfloat)
   Compiling quote v1.0.7
   Compiling parking_lot_core v0.8.3
   Compiling num_cpus v1.13.0
   Compiling perf-event-open-sys v1.0.1
   Compiling memmap v0.7.0
   Compiling jobserver v0.1.21
   Compiling atty v0.2.14
   Compiling termize v0.1.1
   Compiling memmap2 v0.2.1
   Compiling aho-corasick v0.7.13
   Compiling regex-automata v0.1.9
   Compiling rustc_serialize v0.0.0 (/home/tor/projects/rust/compiler/rustc_serialize)
   Compiling petgraph v0.5.1
   Compiling crossbeam-queue v0.2.3
   Compiling parking_lot v0.11.1
   Compiling cstr v0.2.8
   Compiling rand_core v0.5.1
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling regex v1.4.3
   Compiling crossbeam-deque v0.7.3
   Compiling matchers v0.0.1
   Compiling measureme v9.1.0
   Compiling synstructure v0.12.4
   Compiling rand_chacha v0.2.2
   Compiling chrono v0.4.19
   Compiling sha2 v0.9.1
   Compiling sha-1 v0.9.1
   Compiling md-5 v0.9.1
   Compiling rand v0.7.3
   Compiling tracing-attributes v0.1.13
   Compiling rustc_macros v0.1.0 (/home/tor/projects/rust/compiler/rustc_macros)
   Compiling chalk-derive v0.55.0
   Compiling rustc-rayon v0.3.1
   Compiling tempfile v3.1.0
   Compiling rustc_index v0.0.0 (/home/tor/projects/rust/compiler/rustc_index)
   Compiling tracing v0.1.25
   Compiling chalk-ir v0.55.0
   Compiling rustc_data_structures v0.0.0 (/home/tor/projects/rust/compiler/rustc_data_structures)
   Compiling rustc_arena v0.0.0 (/home/tor/projects/rust/compiler/rustc_arena)
   Compiling rustc_type_ir v0.0.0 (/home/tor/projects/rust/compiler/rustc_type_ir)
   Compiling rustc_span v0.0.0 (/home/tor/projects/rust/compiler/rustc_span)
   Compiling rustc_ast v0.0.0 (/home/tor/projects/rust/compiler/rustc_ast)
   Compiling rustc_target v0.0.0 (/home/tor/projects/rust/compiler/rustc_target)
   Compiling rustc_feature v0.0.0 (/home/tor/projects/rust/compiler/rustc_feature)
   Compiling rustc_parse_format v0.0.0 (/home/tor/projects/rust/compiler/rustc_parse_format)
   Compiling rustc_lint_defs v0.0.0 (/home/tor/projects/rust/compiler/rustc_lint_defs)
   Compiling rustc_ast_pretty v0.0.0 (/home/tor/projects/rust/compiler/rustc_ast_pretty)
   Compiling rustc_hir v0.0.0 (/home/tor/projects/rust/compiler/rustc_hir)
   Compiling rustc_errors v0.0.0 (/home/tor/projects/rust/compiler/rustc_errors)
   Compiling rustc_session v0.0.0 (/home/tor/projects/rust/compiler/rustc_session)
   Compiling rustc_attr v0.0.0 (/home/tor/projects/rust/compiler/rustc_attr)
   Compiling rustc_query_system v0.0.0 (/home/tor/projects/rust/compiler/rustc_query_system)
   Compiling rustc_parse v0.0.0 (/home/tor/projects/rust/compiler/rustc_parse)
   Compiling rustc_hir_pretty v0.0.0 (/home/tor/projects/rust/compiler/rustc_hir_pretty)
   Compiling rustc_ast_lowering v0.0.0 (/home/tor/projects/rust/compiler/rustc_ast_lowering)
   Compiling rustc_middle v0.0.0 (/home/tor/projects/rust/compiler/rustc_middle)
   Compiling rustc_ast_passes v0.0.0 (/home/tor/projects/rust/compiler/rustc_ast_passes)
   Compiling rustc_expand v0.0.0 (/home/tor/projects/rust/compiler/rustc_expand)
   Compiling tracing-serde v0.1.2
   Compiling rls-span v0.5.3
   Compiling gsgdt v0.1.2
   Compiling rustc_builtin_macros v0.0.0 (/home/tor/projects/rust/compiler/rustc_builtin_macros)
   Compiling rls-data v0.19.1
   Compiling tracing-subscriber v0.2.16
   Compiling tracing-tree v0.1.9
   Compiling chalk-solve v0.55.0
   Compiling chalk-engine v0.55.0
   Compiling rustc_infer v0.0.0 (/home/tor/projects/rust/compiler/rustc_infer)
   Compiling rustc_metadata v0.0.0 (/home/tor/projects/rust/compiler/rustc_metadata)
   Compiling rustc_symbol_mangling v0.0.0 (/home/tor/projects/rust/compiler/rustc_symbol_mangling)
   Compiling rustc_incremental v0.0.0 (/home/tor/projects/rust/compiler/rustc_incremental)
   Compiling rustc_query_impl v0.0.0 (/home/tor/projects/rust/compiler/rustc_query_impl)
   Compiling rustc_save_analysis v0.0.0 (/home/tor/projects/rust/compiler/rustc_save_analysis)
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Some(Fingerprint(17085791684156926648, 13748150228338284063))`,
 right: `Some(Fingerprint(6887644492105035959, 15270603150060181438))`: found unstable fingerprints for optimized_mir(rustc_middle[e4db]::dep_graph::dep_node::_DERIVE_rustc_serialize_Decodable_D_FOR_DepKind::{impl#0}::decode::{closure#0}::{closure#0}): Body { basic_blocks: [BasicBlockData { statements: [], terminator: Some(Terminator { source_info: SourceInfo { span: /home/tor/projects/rust/compiler/rustc_middle/src/dep_graph/dep_node.rs:222:70: 222:79 (#4244), scope: scope[0] }, kind: switchInt(_3) -> [0_usize: bb2, 1_usize: bb3, 2_usize: bb4, 3_usize: bb5, 4_usize: bb6, 5_usize: bb7, 6_usize: bb8, 
...
(loads of output snipped)
...
fo { span: /home/tor/projects/rust/compiler/rustc_middle/src/dep_graph/dep_node.rs:222:70: 222:79 (#4244), scope: scope[0] }, value: _2 }, VarDebugInfo { name: "__variant_idx", source_info: SourceInfo { span: /home/tor/projects/rust/compiler/rustc_middle/src/dep_graph/dep_node.rs:222:70: 222:79 (#4244), scope: scope[0] }, value: _3 }], span: /home/tor/projects/rust/compiler/rustc_middle/src/dep_graph/dep_node.rs:222:70: 222:79 (#4244), required_consts: [], is_polymorphic: true, predecessor_cache: PredecessorCache { cache: OnceCell(Uninit) }, is_cyclic: GraphIsCyclicCache { cache: OnceCell(Uninit) } }', /home/tor/projects/rust/compiler/rustc_query_system/src/query/plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z macro-backtrace -Z tls-model=initial-exec -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `rustc_middle::dep_graph::dep_node::_DERIVE_rustc_serialize_Decodable_D_FOR_DepKind::<impl rustc_serialize::Decodable<__D> for rustc_middle::dep_graph::DepKind>::decode::{closure#0}::{closure#0}`
#1 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack
error: internal compiler error: trimmed_def_paths constructed
  |
  = note: delayed at    0: rustc_errors::Handler::delay_good_path_bug
             1: rustc_middle::ty::print::pretty::trimmed_def_paths
             2: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::trimmed_def_paths>::compute
             3: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
             4: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
             5: rustc_data_structures::stack::ensure_sufficient_stack
             6: rustc_query_system::query::plumbing::force_query_with_job
             7: rustc_query_system::query::plumbing::get_query_impl
             8: rustc_query_system::query::plumbing::get_query
             9: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
            10: rustc_middle::ty::print::Printer::default_print_def_path
            11: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
            12: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::pretty::PrettyPrinter>::generic_delimiters
            13: rustc_middle::ty::print::Printer::default_print_def_path
            14: <rustc_middle::ty::print::pretty::FmtPrinter<F> as rustc_middle::ty::print::Printer>::print_def_path
            15: rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_const_value
            16: rustc_middle::ty::print::pretty::PrettyPrinter::pretty_print_const
            17: rustc_middle::mir::pretty_print_const
            18: core::fmt::write
            19: <core::fmt::Formatter as core::fmt::Write>::write_fmt
            20: <rustc_middle::mir::Constant as core::fmt::Debug>::fmt
            21: core::fmt::write
            22: <core::fmt::Formatter as core::fmt::Write>::write_fmt
            23: <rustc_middle::mir::Operand as core::fmt::Debug>::fmt
            24: core::fmt::write
            25: <core::fmt::Formatter as core::fmt::Write>::write_fmt
            26: rustc_middle::mir::terminator::TerminatorKind::fmt_head
            27: <rustc_middle::mir::terminator::TerminatorKind as core::fmt::Debug>::fmt
            28: core::fmt::builders::DebugStruct::field
            29: <rustc_middle::mir::terminator::Terminator as core::fmt::Debug>::fmt
            30: core::fmt::builders::DebugTuple::field
            31: <&T as core::fmt::Debug>::fmt
            32: core::fmt::builders::DebugStruct::field
            33: <rustc_middle::mir::BasicBlockData as core::fmt::Debug>::fmt
            34: core::fmt::builders::DebugInner::entry
            35: core::fmt::builders::DebugList::entry
            36: core::fmt::builders::DebugList::entries
            37: <[T] as core::fmt::Debug>::fmt
            38: core::fmt::builders::DebugStruct::field
            39: <rustc_middle::mir::Body as core::fmt::Debug>::fmt
            40: core::fmt::write
            41: <core::fmt::Arguments as core::fmt::Debug>::fmt
            42: core::fmt::write
            43: core::fmt::Write::write_fmt
            44: <std::panicking::begin_panic_handler::PanicPayload as core::panic::BoxMeUp>::get
            45: std::panicking::rust_panic_with_hook
            46: std::panicking::begin_panic_handler::{{closure}}
            47: std::sys_common::backtrace::__rust_end_short_backtrace
            48: rust_begin_unwind
            49: core::panicking::panic_fmt
            50: core::panicking::assert_failed_inner
            51: core::panicking::assert_failed
            52: rustc_query_system::query::plumbing::incremental_verify_ich
            53: rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
            54: rustc_data_structures::stack::ensure_sufficient_stack
            55: rustc_query_system::query::plumbing::get_query_impl
            56: rustc_query_system::query::plumbing::get_query
            57: rustc_middle::ty::<impl rustc_middle::ty::context::TyCtxt>::instance_mir
            58: rustc_mir::monomorphize::collector::collect_neighbours
            59: rustc_data_structures::stack::ensure_sufficient_stack
            60: rustc_mir::monomorphize::collector::collect_items_rec
            61: rustc_mir::monomorphize::collector::collect_items_rec
            62: rustc_mir::monomorphize::collector::collect_items_rec
            63: rustc_mir::monomorphize::collector::collect_items_rec
            64: rustc_mir::monomorphize::collector::collect_items_rec
            65: rustc_mir::monomorphize::collector::collect_items_rec
            66: rustc_mir::monomorphize::collector::collect_items_rec
            67: rustc_mir::monomorphize::collector::collect_items_rec
            68: rustc_mir::monomorphize::collector::collect_items_rec
            69: rustc_mir::monomorphize::collector::collect_items_rec
            70: rustc_mir::monomorphize::collector::collect_items_rec
            71: rustc_mir::monomorphize::collector::collect_items_rec
            72: rustc_mir::monomorphize::collector::collect_items_rec
            73: rustc_mir::monomorphize::collector::collect_items_rec
            74: rustc_mir::monomorphize::collector::collect_items_rec
            75: rustc_mir::monomorphize::collector::collect_items_rec
            76: rustc_mir::monomorphize::collector::collect_items_rec
            77: rustc_mir::monomorphize::collector::collect_items_rec
            78: rustc_mir::monomorphize::collector::collect_items_rec
            79: rustc_mir::monomorphize::collector::collect_items_rec
            80: rustc_mir::monomorphize::collector::collect_items_rec
            81: rustc_mir::monomorphize::collector::collect_items_rec
            82: rustc_mir::monomorphize::collector::collect_items_rec
            83: rustc_mir::monomorphize::collector::collect_items_rec
            84: rustc_mir::monomorphize::collector::collect_items_rec
            85: rustc_mir::monomorphize::collector::collect_items_rec
            86: rustc_mir::monomorphize::collector::collect_items_rec
            87: rustc_mir::monomorphize::collector::collect_items_rec
            88: rustc_session::utils::<impl rustc_session::session::Session>::time
            89: rustc_mir::monomorphize::collector::collect_crate_mono_items
            90: rustc_mir::monomorphize::partitioning::collect_and_partition_mono_items
            91: rustc_query_impl::<impl rustc_query_system::query::config::QueryAccessors<rustc_query_impl::plumbing::QueryCtxt> for rustc_query_impl::queries::collect_and_partition_mono_items>::compute
            92: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
            93: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
            94: rustc_data_structures::stack::ensure_sufficient_stack
            95: rustc_query_system::query::plumbing::force_query_with_job
            96: rustc_query_system::query::plumbing::get_query_impl
            97: rustc_query_system::query::plumbing::get_query
            98: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::collect_and_partition_mono_items
            99: rustc_codegen_ssa::base::codegen_crate
           100: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
           101: rustc_session::utils::<impl rustc_session::session::Session>::time
           102: rustc_interface::passes::start_codegen
           103: rustc_interface::passes::QueryContext::enter
           104: rustc_interface::queries::Query<T>::compute
           105: rustc_interface::queries::Queries::ongoing_codegen
           106: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
           107: rustc_span::with_source_map
           108: rustc_interface::interface::create_compiler_and_run
           109: scoped_tls::ScopedKey<T>::set
           110: rustc_span::with_session_globals
           111: std::sys_common::backtrace::__rust_begin_short_backtrace
           112: std::panicking::try
           113: core::ops::function::FnOnce::call_once{{vtable.shim}}
           114: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
           115: std::sys::unix::thread::Thread::new::thread_start
           116: start_thread
           117: clone


thread 'rustc' panicked at 'no warnings or errors encountered even though `delayed_good_path_bugs` issued', compiler/rustc_errors/src/lib.rs:1010:13
stack backtrace:
   0:     0x7f6d06b63191 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3f2aa2e9e6ad60dd
   1:     0x7f6d06bf4ca7 - core::fmt::write::h46cd67537b009e96
   2:     0x7f6d06b6e263 - std::io::Write::write_fmt::h3cfd51fa1e1eb983
   3:     0x7f6d06b6301f - std::sys_common::backtrace::print::ha3e324d311b1ce1c
   4:     0x7f6d06b61a07 - std::panicking::default_hook::{{closure}}::h4acabe588932fb37
   5:     0x7f6d06b617c6 - std::panicking::default_hook::hdd5420dfcbaaf61b
   6:     0x7f6d0718830d - rustc_driver::report_ice::h2da317b706e579d9
   7:     0x7f6d06b61ed9 - std::panicking::rust_panic_with_hook::h741ff14d310e8682
   8:     0x7f6d06b588f7 - std::panicking::begin_panic_handler::{{closure}}::he948be64cc77afec
   9:     0x7f6d06b5885c - std::sys_common::backtrace::__rust_end_short_backtrace::h653fe4140b4c364c
  10:     0x7f6d06b61b02 - rust_begin_unwind
  11:     0x7f6d06b61abb - std::panicking::begin_panic_fmt::hbee4e4c13812a23e
  12:     0x7f6d09272d44 - rustc_errors::HandlerInner::flush_delayed::hb45bd72db3e37491
  13:     0x7f6d0925eeb0 - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::hc2b6e7715ed38804
  14:     0x7f6d071c70aa - core::ptr::drop_in_place<rustc_errors::Handler>::hcd631d5fe79eb073
  15:     0x7f6d071cffc5 - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::h4b8dc0ac1ee43f21
  16:     0x7f6d071dd12f - core::ptr::drop_in_place<alloc::rc::Rc<rustc_session::session::Session>>::hdbb6842e998506df
  17:     0x7f6d071d3ac1 - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::h1b8d5afe43927d1b
  18:     0x7f6d071ae1c7 - rustc_span::with_source_map::h67529ab6bae7a32a
  19:     0x7f6d0719769c - rustc_interface::interface::create_compiler_and_run::h6b7fb2eb6a3826d9
  20:     0x7f6d0718e82b - scoped_tls::ScopedKey<T>::set::hd1bb724abaf2bd29
  21:     0x7f6d071ae897 - rustc_span::with_session_globals::had12124901b5c526
  22:     0x7f6d0719224b - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a2c2491e869e3d1
  23:     0x7f6d071a6479 - std::panicking::try::h286af9f9d5284326
  24:     0x7f6d07282dea - core::ops::function::FnOnce::call_once{{vtable.shim}}::h145164f12491f309
  25:     0x7f6d06b72cbb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h212ce3f0f30c9d47
  26:     0x7f6d06b80c6a - std::sys::unix::thread::Thread::new::thread_start::hfa29c1959650d865
  27:     0x7f6d01534ea7 - start_thread
  28:     0x7f6d06a01def - clone
  29:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z macro-backtrace -Z tls-model=initial-exec -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
rustc exited with signal: 4
error: could not compile `rustc_incremental`

Caused by:
  process didn't exit successfully: `/home/tor/projects/rust/build/bootstrap/debug/rustc --crate-name rustc_incremental --edition=2018 compiler/rustc_incremental/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=99f89c2bf0395021 -C extra-filename=-99f89c2bf0395021 --out-dir /home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C incremental=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/incremental -L dependency=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps --extern rand=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librand-4bf2ca76d4781a9f.rmeta --extern rustc_ast=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_ast-a71752acfd70bb88.rmeta --extern rustc_data_structures=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_data_structures-694249313f2ec774.rmeta --extern rustc_fs_util=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_fs_util-34af3a65da5cac39.rmeta --extern rustc_graphviz=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_graphviz-5d7de2ef8195eadc.rmeta --extern rustc_hir=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_hir-66881fe15d61d118.rmeta --extern rustc_macros=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/librustc_macros-bc31a5639247655e.so --extern rustc_middle=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_middle-b75f6bff02ebd53c.rmeta --extern rustc_serialize=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_serialize-d889830b0259ac6c.rmeta --extern rustc_session=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_session-cc60d5bf24945c7a.rmeta --extern rustc_span=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_span-7940a9113a28381d.rmeta --extern tracing=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps/libtracing-1c9fa13581117120.rmeta -Zmacro-backtrace '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Ztls-model=initial-exec -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Cllvm-args=-import-instr-limit=10 -Z binary-dep-depinfo -L native=/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/build/psm-eeb5e78a19d15932/out` (exit code: 254)
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/home/tor/projects/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "6" "--release" "--features" " llvm" "--manifest-path" "/home/tor/projects/rust/compiler/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /home/tor/projects/rust/build/bootstrap/debug/bootstrap install
Build completed unsuccessfully in 0:05:21
```

**Comment by jyn514** [comment] 2021-04-03 18:28
@torhovland as a workaround, you could set `incremental = false` in config.toml.

**Comment by torhovland** [comment] 2021-04-03 19:00
@jyn514 Thanks, that works!

**Comment by jyn514** [comment] 2021-05-19 09:35
Duplicate of https://github.com/rust-lang/rust/issues/85197

**Closed by jyn514** 2021-05-19 09:35 UTC
Labels: A-incr-comp, A-rustbuild, C-bug, I-ICE, T-compiler
