### ISSUE TITLE
Can't destructure a boxed struct without an intermediate let binding

### ISSUE THREAD

**Issue by charliesome** [rust-lang/rust#47376] opened 2018-01-12 06:58 UTC
This code fails to compile:

```rust
struct Foo;

struct Bar {
    a: Foo,
    b: Foo,
}

fn main() {
    let bar = Box::new(Bar { a: Foo, b: Foo });

    let Bar { a, b } = *bar;
}
```

```
error[E0382]: use of moved value: `bar`
  --> x.rs:11:18
   |
11 |     let Bar { a, b } = *bar;
   |               -  ^ value used here after move
   |               |
   |               value moved here
   |
   = note: move occurs because `bar.a` has type `Foo`, which does not implement the `Copy` trait
```

However inserting an intermediate let binding in between the box deref and the destructure fixes it:

```rust
fn main() {
    let bar = Box::new(Bar { a: Foo, b: Foo });

    let Bar { a, b } = { let intermediate = *bar; intermediate };
}
```

This feels like a bug.

Affected versions:

* `rustc 1.23.0 (766bd11c8 2018-01-01)`

* `rustc 1.25.0-nightly (73ac5d6a8 2018-01-11)`

**Comment by nagisa** [comment] 2018-01-12 09:09
Also happens with box patterns.

```rust
#![feature(box_patterns)]

struct Foo;

struct Bar {
    a: Foo,
    b: Foo,
}

fn main() {
    let bar = Box::new(Bar { a: Foo, b: Foo });

    let box Bar { a, b } = bar;
}
```

**Comment by goffrie** [comment] 2018-01-20 21:05
This is a dupe of https://github.com/rust-lang/rust/issues/16223.

**Comment by steveklabnik** [comment] 2019-12-16 13:25
Triage: this is fixed!

**Closed by steveklabnik** 2019-12-16 13:25 UTC
Labels: C-bug, T-compiler
