### ISSUE TITLE
UFCS: incorrect "multiple applicable methods in scope" error

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#24382] opened 2015-04-13 17:45 UTC
### STR

``` rust
#![no_implicit_prelude]

use cast::From as _0;
use convert::From;

// minimal version of `std::convert::From`
mod convert {
    pub trait From<Src> {
        fn from(Src) -> Self;
    }

    // more concrete version of `impl<T> From<T> for T`
    impl From<u16> for u16 {
        fn from(src: u8) -> u8 {
            src
        }
    }
}

mod cast {
    pub trait From<Src> {
        type Output;

        fn from(Src) -> Self::Output;
    }

    // integer promotion
    impl From<u8> for u16 {
        type Output = u16;

        fn from(src: u8) -> u16 {
            src as u16
        }
    }
}

fn main() {
    // This error is wrong, because only `cast::From` can be "selected". Or in other words
    // `<u16 as convert::From<u16>>::from(0u8)` is not a valid candidate (see function signature)
    let x = u16::from(0u8);
    //~^ error: multiple applicable methods in scope
    //~| note: candidate #1 is defined in an impl of the trait `convert::From` for the type `u16`
    //~| note: candidate #2 is defined in an impl of the trait `cast::From` for the type `u16`
}
```

I'm not familiar with how UFCS is implemented, but my wild guess is that the compiler is not using the type of the `0u8` argument to discard the `convert::From<u16>` candidate. I also find suspicious that the note message reports `cast::From`/`convert::From` instead of `cast::From<u8>`/`convert::From<u16>`, might be related.

### Workaround

rename `cast::From::from` to `cast::From::from_`

### Version

```
rustc 1.0.0-nightly (47def3ef2 2015-04-13) (built 2015-04-13)
```

cc @eddyb @nikomatsakis

**Comment by bltavares** [comment] 2015-11-04 22:37
This is still an issue.
```
rustc 1.6.0-nightly (1a2eaffb6 2015-10-31)
```

I've updated the code example as it was not compiling on the `convert::from` implementation.

```rust
#![no_implicit_prelude]

use cast::From as _0;
use convert::From;

// minimal version of `std::convert::From`
mod convert {
    pub trait From<Src> {
        fn from(Src) -> Self;
    }

    // more concrete version of `impl<T> From<T> for T`
    impl From<u16> for u16 {
        fn from(src: u16) -> u16 {
            src
        }
    }
}

mod cast {
    pub trait From<Src> {
        type Output;

        fn from(Src) -> Self::Output;
    }

    // integer promotion
    impl From<u8> for u16 {
        type Output = u16;

        fn from(src: u8) -> u16 {
            src as u16
        }
    }
}

fn main() {
    // This error is wrong, because only `cast::From` can be "selected". Or in other words
    // `<u16 as convert::From<u16>>::from(0u8)` is not a valid candidate (see function signature)
    let x = u16::from(0u8);
    //~^ error: multiple applicable methods in scope
    //~| note: candidate #1 is defined in an impl of the trait `convert::From` for the type `u16`
    //~| note: candidate #2 is defined in an impl of the trait `cast::From` for the type `u16`
}
```

It seems that the compiler is getting confused as the `u8` could be casted as `u16` safely, and that leaves both functions as good candidates, even tho there is one signature that is more specific without implicit castings.

**Comment by nikomatsakis** [comment] 2015-11-05 17:32
I see this as "not a bug". Not because the analysis is incorrect, but because this is a known limitation of how we handle UFCS/method-calls/projections that I don't think we will lift in the short-term. In particular, there are certain points in the compiler where we require a base amount of type information. For example, `x.foo(...)` requires that we can select what trait (if any) the method `foo` derives from *without knowing the types of the arguments*. Similarly, we must be able to expand a projection like `u16::from` to the complete `<u16 as ...>::from` *without knowing* the types of the arguments. This in turn is important because we need to have resolved this information to coerce the arguments and so forth. In principle, we can lift these restrictions by restructuring the type checker to be much less "ordered". But this is effectively a ground-up rewrite, and so I think currently out of scope (it would probably require, among other things, an RFC clarifying how it will work, etc). Therefore, I'm going to close this issue.

**Closed by nikomatsakis** 2015-11-05 17:32 UTC
Labels: A-typesystem
