### ISSUE TITLE
rustdoc: `--document-private-items` does not document non-exported macros

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78091] opened 2020-10-18 22:56 UTC
With `--document-private-items`:

- private `fn`s are documented
- public `fn`s are documented
- `#[macro_export] macro_rules!` are **documented**
- non-exported `macro_rules!` are **not documented**

I'm not sure if this is intended behavior, but it's not very intuitive and kind of frustrating.

### Code

```rust
macro_rules! foo_macro {
    () => { };
}

#[macro_export]
macro_rules! exported_foo_macro {
    () => { };
}

fn foo_fn() {}

pub fn pub_foo_fn() {}
```

### Command

`cargo doc --document-private-items`

### Output

![image](https://user-images.githubusercontent.com/37223377/96387900-55413e00-115a-11eb-991b-5696f128961c.png)

### Version

```console
$ rustdoc -vV
rustdoc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustdoc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-apple-darwin
release: 1.47.0
LLVM version: 11.0
```

**Comment by jonas-schievink** [comment] 2020-10-18 23:02
Duplicate of https://github.com/rust-lang/rust/issues/73754

**Comment by camelid** [comment] 2020-10-18 23:03
Dang, I searched for it, but the title confused me.

**Closed by jonas-schievink** 2020-10-18 23:02 UTC
Labels: A-macros, C-bug, T-rustdoc
