### ISSUE TITLE
LLVM misoptimization causes segfault

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#30816] opened 2016-01-11 02:27 UTC
Consider the following code:

```rust
#[no_mangle]
pub unsafe extern fn memset(mut s: *mut u8, c: c_int, n: usize) -> *mut u8 {
    let end = s.add(n);
    let c = c as u8;
    while s != end {
        *s = c;
        s = s.add(1);
    }
    end.sub(n)
}
```

LLVM misoptimizes this function into an infinite recursion because it recognizes that the inner loop can be replaced by a call to memset. Normally this optimization is disabled inside functions called `memset` but since the body of the function is moved to a function with rust abi, this check doesn't work.

**Comment by rphmeier** [comment] 2016-01-11 03:26
Confirmed here on stable, beta, and nightly using libc 0.2.4. I rewrote your function to use offset instead of "add", along with a relatively minimal test case.

```
extern crate libc;
#[no_mangle]
pub unsafe extern fn memset(mut s: *mut u8, c: libc::c_int, n: usize) -> *mut u8 {
    let end = s.offset(n as isize);
    let c = c as u8;
    while s != end {
        *s = c;
        s = s.offset(1);
    }
    s
}

fn main() {
    let mut arr = [0u8; 32];
    unsafe { memset(&mut arr[0], 1, arr.len()); }
    assert_eq!(arr, [1u8; 32]);
}
```

**Comment by huonw** [comment] 2016-01-11 03:31
Dupe of https://github.com/rust-lang/rust/issues/10116 and https://github.com/rust-lang/rust/issues/18785, but thanks for filing! You may be interested in the [`no_builtins`](https://github.com/alexcrichton/rlibc/blob/4fbdfce79e9164f5ca56cef212f368603f389615/src/lib.rs#L27-L29) attribute (as a work-around until #10116 is fixed).

**Closed by huonw** 2016-01-11 03:31 UTC
