### ISSUE TITLE
Conflicting impls if type parameter is bounded by associated types

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#41680] opened 2017-05-01 20:55 UTC
When implementing trait for generic type the compiler fails with "conflicting impls" message if the bounds for the type parameter differ in associated type.

[Minimalistic example](https://play.rust-lang.org/?gist=75eb4ded7afd001dec1a7b7e1b9488fb&version=stable&backtrace=0)

I expected this to pass because if the associated types differ, then types implementing such trait must differ too.

The compiler message:
```
rustc 1.17.0 (56124baa9 2017-04-24)
error[E0119]: conflicting implementations of trait `Foo` for type `Bar<_>`:
```

**Comment by Diggsey** [comment] 2017-05-01 21:06
Duplicate of #20400

**Comment by Kixunil** [comment] 2017-05-01 21:17
Sorry, I tried to find it but failed. :(

**Comment by Mark-Simulacrum** [comment] 2017-06-22 12:42
Closing in favor of #20400. No worries about not finding the duplicate.

**Closed by Mark-Simulacrum** 2017-06-22 12:42 UTC
