### ISSUE TITLE
Compiler suggests use of non-existent macro

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#57588] opened 2019-01-14 06:30 UTC
I'm quite puzzled by the compiler guidance here:

```rust
use std::env;

fn main() {
    env::vav_os("PATH");
}
```

```
error[E0423]: expected function, found macro `env::vav_os`
 --> src/main.rs:4:5
  |
4 |     env::vav_os("PATH");
  |     ^^^^^------
  |     |    |
  |     |    did you mean `var_os`?
  |     did you mean `env::vav_os!(...)`?
```

Why does it think `env::vav_os` is a macro?

**Comment by petrochenkov** [comment] 2019-01-14 09:40
Duplicate of https://github.com/rust-lang/rust/issues/47361, diagnostics check whether the *first* segment of the path is a macro, and it its (`env!(...)`).

**Comment by petrochenkov** [comment] 2019-01-14 09:41
Suggestions for macros were written before all the macro modularization reforms.

**Comment by jethrogb** [comment] 2019-01-14 09:44
This can be closed as a duplicate if the description of #47361 is updated to be more generic.

**Comment by estebank** [comment] 2019-05-07 23:28
Current output:

```
error[E0423]: expected function, found macro `env::vav_os`
 --> src/main.rs:4:5
  |
4 |     env::vav_os("PATH");
  |     ^^^^^^^^^^^
help: a function with a similar name exists
  |
4 |     env::var_os("PATH");
  |          ^^^^^^
help: use `!` to invoke the macro
  |
4 |     env::vav_os!("PATH");
  |     ^^^^^^^^^^^^
```

Closing as duplicate of #47361.

**Closed by estebank** 2019-05-07 23:28 UTC
Labels: A-diagnostics, A-macros
