### ISSUE TITLE
Forced to repeat inherited trait constraints on things other `Self`

### ISSUE THREAD

**Issue by LLFourn** [rust-lang/rust#71251] opened 2020-04-17 16:19 UTC
Putting inherited constraints on things other than `Self` causes problems:
```rust
use std::ops::Mul;

trait CanMul: Sized
where
    u32: Mul<Self>,
{}

fn do_mul<T: CanMul>(a: T) -> u32
{
    unimplemented!();
}

fn main() {}
```
Gives the error:

```
error[E0277]: cannot multiply `T` to `u32`
 --> src/main.rs:9:14
  |
3 | trait CanMul: Sized
  |       ------
4 | where
5 |     u32: Mul<Self>,
  |          --------- required by this bound in `CanMul`
...
9 | fn do_mul<T: CanMul>(a: T) -> u32 {
  |              ^^^^^^ no implementation for `u32 * T`
  |
  = help: the trait `std::ops::Mul<T>` is not implemented for `u32`

```
The compiler has turned what should a property of `T: CanMul` into a constraint on `T`.
You can work around the issue by repeating the constraint:

```rust
fn do_mul<T: CanMul>(a: T) -> u32
where
    u32: Mul<T>,
{
    unimplemented!();
}
```
But obviously you shouldn't have to because you've already told the compiler that this is true.

Another example using a HRTB:
```rust
use std::ops::Mul;

trait CanMul: Sized
where
    for<'a> &'a Self: Mul<u32>,
{
}

fn do_mul<T: CanMul>(a: T) -> u32 {
    unimplemented!()
}

fn main() {}

```

### Meta
```
$ rustc --version
rustc 1.44.0-nightly (7f3df5772 2020-04-16)
```

**Comment by jonas-schievink** [comment] 2020-04-17 16:22
Duplicate of https://github.com/rust-lang/rust/issues/20671

**Closed by jonas-schievink** 2020-04-17 16:22 UTC
Labels: C-bug
