### ISSUE TITLE
type annotations required in a guard when evaluating to the same thing

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rust#59888] opened 2019-04-11 19:01 UTC
I couldn't see an obvious duplicate, sorry if I missed one.

I get this error with git 3750348daff89741e3153e0e120aa70a45ff5b68
```
C:\Users\robertc\Documents\src\rust>py x.py build --stage 1 src/libtest
Updating only changed submodules
Submodules updated in 0.93 seconds
    Finished dev [unoptimized] target(s) in 1.16s
Building stage0 std artifacts (x86_64-pc-windows-msvc -> x86_64-pc-windows-msvc)
   Compiling std v0.0.0 (C:\Users\robertc\Documents\src\rust\src\libstd)
error[E0284]: type annotations required: cannot resolve `<_ as core::str::FromStr>::Err == _`
  --> src\libstd\io\util.rs:48:28
   |
48 |             Ok(val) if val.parse().is_ok() => val.parse().unwrap(),
   |                            ^^^^^

error: aborting due to previous error
```

From this code:
<details>
<summary>io::copy variant</summary>
<p>
```
#[stable(feature = "rust1", since = "1.0.0")]
pub fn copy<R: ?Sized, W: ?Sized>(reader: &mut R, writer: &mut W) -> io::Result<u64>
    where R: Read, W: Write
{
    let mut buf = unsafe {
        let mut buf_size: usize = match env::var("RUST_COPY_BUF_SIZE") {
            Ok(val) if val.parse::().is_ok() => val.parse().unwrap(),
            _ => 0
        };
        if buf_size == 0 {
            buf_size = super::DEFAULT_BUF_SIZE
        }

        let mut buf = Vec::with_capacity(buf_size);
        buf.set_len(buf_size);
        reader.initializer().initialize(&mut buf);
        buf
    };

    let mut written = 0;
    loop {
        let len = match reader.read(&mut buf) {
            Ok(0) => return Ok(written),
            Ok(len) => len,
            Err(ref e) if e.kind() == ErrorKind::Interrupted => continue,
            Err(e) => return Err(e),
        };
        writer.write_all(&buf[..len])?;
        written += len as u64;
    }
}```

</p>
</details>


Changing the match clause to:
```
            Ok(val) if val.parse::<usize>().is_ok() => val.parse().unwrap(),
```
permitted it to compile - it can clearly infer the type of the resulting expression; but the use of the leadin of the same expression (`val.parse()`) in the guard isn't - anyhow, it would be delightful if I didn't need to hint to the guard that it should match the same type that the resulting expression will be using for the parse call.

**Comment by rodrimati1992** [comment] 2019-04-11 21:04
The problem is that the `.parse()` in the match guard could be for any other type.

You could just as easily have written:
```
Ok(val) if val.parse::<f32>().is_ok() => val.parse().unwrap(),
```
and it would be valid code that Rust would accept.

**Comment by jonas-schievink** [comment] 2019-04-11 21:12
This looks like an expected behaviour, so closing.

**Closed by jonas-schievink** 2019-04-11 21:12 UTC

**Comment by rbtcollins** [comment] 2019-04-17 23:10
Sorry for taking a bit to come back to this; I understand its expected behaviour, but its still awkward for developers.

Perhaps if there was some way of capturing the processed expression:

```
Ok(val) if val.parse::<usize>() as size.is_ok() => size.unwrap(),
```
?

**Comment by jonas-schievink** [comment] 2019-04-17 23:13
@rbtcollins you can do something similar with [type ascription](https://rust-lang.github.io/rfcs/0803-type-ascription.html)

**Comment by rbtcollins** [comment] 2019-04-29 22:52
Thanks @jonas-schievink  - I don't quite see how the repetition is eliminated there, which was my main critique: the ergonomic issue is having to specify the desired type twice, and ascription would, as I understand it, just provide a different syntax for doing that on the match expression; whereas the issue is that there is no constraint holding the type of the guard expression and the type of the result together.

**Comment by rodrimati1992** [comment] 2019-04-30 00:48
Like I said in my previous comment,there is a feature in progress that would cover this particular case,[rfc 2294:if let guards](https://github.com/rust-lang/rfcs/blob/master/text/2294-if-let-guard.md).
Once that RFC is implemented you can rewrite:
`Ok(val) if val.parse::<usize>().is_ok() => val.parse().unwrap(),
` 
to
`Ok(val) if let Ok(len)=val.parse() { len }`

If you want to create an RFC which proposes a syntax for creating variables inside if conditions,usable in the then branch,you might want examples not easily expressible with if let guards.

**Comment by rbtcollins** [comment] 2019-04-30 07:19
@rodrimati1992 ah I missed that line! thank you <3
