### ISSUE TITLE
ICE assertion failed: prev_const.is_none() || prev_const == Some(llconst)

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#25748] opened 2015-05-24 12:34 UTC
[rust-encoding](https://github.com/lifthrasiir/rust-encoding/tree/3af92a299757bcb07e64ae326dbeef4cdbfaa80f) builds fine in the previous nightly, but it triggers an ICE in rustc 1.2.0-nightly (0fc0476e6 2015-05-24) (built 2015-05-24)

This looks similar to #24644, but it started more recently.

```
$ RUST_BACKTRACE=1 cargo build --verbose
       Fresh encoding_index_tests v0.1.4 (file:///home/simon/projects/rust-encoding)
   Compiling encoding v0.2.32 (file:///home/simon/projects/rust-encoding)
     Running `rustc src/lib.rs --crate-name encoding --crate-type lib -g --out-dir /home/simon/projects/rust-encoding/target/debug --emit=dep-info,link -L dependency=/home/simon/projects/rust-encoding/target/debug -L dependency=/home/simon/projects/rust-encoding/target/debug/deps --extern encoding_index_tradchinese=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_tradchinese-9031d0a206975cd9.rlib --extern encoding_index_singlebyte=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_singlebyte-80fddc2d153c158e.rlib --extern encoding_index_simpchinese=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_simpchinese-06c5fe5964f3071e.rlib --extern encoding_index_korean=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_korean-bb2701334d42f010.rlib --extern encoding_index_japanese=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_japanese-5e92eb13c020e4d8.rlib`
       Fresh libc v0.1.6
       Fresh encoding-index-singlebyte v1.20141219.5 (file:///home/simon/projects/rust-encoding)
       Fresh encoding-index-simpchinese v1.20141219.5 (file:///home/simon/projects/rust-encoding)
       Fresh encoding-index-korean v1.20141219.5 (file:///home/simon/projects/rust-encoding)
       Fresh encoding-index-japanese v1.20141219.5 (file:///home/simon/projects/rust-encoding)
       Fresh encoding-index-tradchinese v1.20141219.5 (file:///home/simon/projects/rust-encoding)
       Fresh log v0.3.1
       Fresh getopts v0.2.10
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: prev_const.is_none() || prev_const == Some(llconst)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_trans/trans/consts.rs:291

stack backtrace:
   1:     0x7f38ec7687e9 - sys::backtrace::write::he19dad14fe2b97b1w6r
   2:     0x7f38ec7707a9 - panicking::on_panic::h330377024750b34dHMw
   3:     0x7f38ec731482 - rt::unwind::begin_unwind_inner::h7703fc192c11eec8Rrw
   4:     0x7f38eb4d782e - rt::unwind::begin_unwind::h7587717121668466740
   5:     0x7f38eb549830 - trans::consts::const_expr::h6a02570a980db0cdhNs
   6:     0x7f38eb5a1aea - trans::consts::get_const_expr_as_global::h8d682e42aa0c00a1pKs
   7:     0x7f38eb51bf3f - trans::expr::trans::h063786072022aec6izA
   8:     0x7f38eb5b80ce - trans::expr::trans_into::h0995470e7b548e00ZsA
   9:     0x7f38eb53d9d2 - trans::expr::trans_adt::h7fc068c005b70b7fv8B
  10:     0x7f38eb5e38b2 - trans::expr::trans_rvalue_dps_unadjusted::he15a7fa64af631b8MCB
  11:     0x7f38eb5b831c - trans::expr::trans_into::h0995470e7b548e00ZsA
  12:     0x7f38eb53ba66 - trans::controlflow::trans_block::h6757ec40476ddde4slv
  13:     0x7f38eb5e3bbd - trans::expr::trans_rvalue_dps_unadjusted::he15a7fa64af631b8MCB
  14:     0x7f38eb5b831c - trans::expr::trans_into::h0995470e7b548e00ZsA
  15:     0x7f38eb53ba66 - trans::controlflow::trans_block::h6757ec40476ddde4slv
  16:     0x7f38eb53a381 - trans::base::trans_closure::hdcc3c01c9bca642e7Uh
  17:     0x7f38eb53c05a - trans::base::trans_fn::hf52d8c0c091fdef5P5h
  18:     0x7f38eb53ee27 - trans::base::trans_item::he4dc60caaf1684eajui
  19:     0x7f38eb53f738 - trans::base::trans_item::he4dc60caaf1684eajui
  20:     0x7f38eb54ccfc - trans::base::trans_crate::hb11747a7cf1143a4sjj
  21:     0x7f38eccc14a4 - driver::phase_4_translate_to_llvm::h29a0d7314fcd3b41nOa
  22:     0x7f38ecc9d226 - driver::compile_input::h16cddbb7992cbbbaQba
  23:     0x7f38ecd52f21 - run_compiler::h74084e004617dcdcb6b
  24:     0x7f38ecd50772 - boxed::F.FnBox<A>::call_box::h10784738899208612549
  25:     0x7f38ecd4ff49 - rt::unwind::try::try_fn::h5235027869346842134
  26:     0x7f38ec7e9498 - rust_try_inner
  27:     0x7f38ec7e9485 - rust_try
  28:     0x7f38ec75c247 - rt::unwind::try::inner_try::hb6f04bd1baacc20eKnw
  29:     0x7f38ecd5017a - boxed::F.FnBox<A>::call_box::h17245911238432039576
  30:     0x7f38ec76f471 - sys::thread::Thread::new::thread_start::h285dd80d49b81cf50xv
  31:     0x7f38e6798373 - start_thread
  32:     0x7f38ec3c127c - clone
  33:                0x0 - <unknown>

Could not compile `encoding`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name encoding --crate-type lib -g --out-dir /home/simon/projects/rust-encoding/target/debug --emit=dep-info,link -L dependency=/home/simon/projects/rust-encoding/target/debug -L dependency=/home/simon/projects/rust-encoding/target/debug/deps --extern encoding_index_tradchinese=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_tradchinese-9031d0a206975cd9.rlib --extern encoding_index_singlebyte=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_singlebyte-80fddc2d153c158e.rlib --extern encoding_index_simpchinese=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_simpchinese-06c5fe5964f3071e.rlib --extern encoding_index_korean=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_korean-bb2701334d42f010.rlib --extern encoding_index_japanese=/home/simon/projects/rust-encoding/target/debug/deps/libencoding_index_japanese-5e92eb13c020e4d8.rlib` (exit code: 101)

**Comment by Manishearth** [comment] 2015-05-26 09:05
cc @eddyb

**Comment by lifthrasiir** [comment] 2015-05-26 14:17
Minimized:

```rust
pub struct UTF8Encoding;
pub const UTF_8: &'static UTF8Encoding = &UTF8Encoding;
pub trait Encoding {}
impl Encoding for UTF8Encoding {}
pub fn f() -> &'static Encoding { UTF_8 as &'static Encoding }
```

**Comment by eddyb** [comment] 2015-05-26 14:18
Duplicate of #24644, closing.

**Closed by eddyb** 2015-05-26 14:18 UTC
Labels: I-ICE
