### ISSUE TITLE
broken MIR (NoSolution) in closure with a parameter whose type is an alias for a reference to an associated type

### ISSUE THREAD

**Issue by purpleposeidon** [rust-lang/rust#68090] opened 2020-01-10 11:18 UTC
```rust
pub fn main() {
    |_: ARef| ();
}

type ARef<'a> = &'a <() as ArrayLength>::ArrayType;

trait ArrayLength {
    type ArrayType;
}

impl ArrayLength for () {
    type ArrayType = u8;
}
```

([Playground (+ comments)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9339ff775645ba87a5ec4edf56002389))

```
error: internal compiler error: broken MIR in DefId(0:13 ~ playground[a34e]::main[0]::{{closure}}[0]) (bb0[0]): equate_normalized_input_or_output: `&[closure@src/main.rs:5:5: 5:17]==&[closure@src/main.rs:5:5: 5:17]` failed with `NoSolution`
 --> src/main.rs:5:17
  |
5 |     |_: ARef| ();
  |                 ^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:391:17
```

In prior versions, this error used to happen only very rarely, but now it happens every time.

**Comment by purpleposeidon** [comment] 2020-01-10 23:46
Rustc bisect says no commits between 31a75a172859d906d8e6a34af4afff9830af495c and 6d599337fa7047307ba72786bbabe6b9c9e4daac within last 167 days.

It appears to have happened between 1.35 and 1.36.

**Comment by pnkfelix** [comment] 2020-01-16 04:02
Specifically:

```
% git log 31a75a172..6d599337f --author=bors --format=oneline
6d599337fa7047307ba72786bbabe6b9c9e4daac Auto merge of #60168 - varkor:tidy-leading-newline, r=alexcrichton
c21fbfe7e310b9055ed6b7c46b7d37b831a516e3 Auto merge of #59114 - matthewjasper:enable-migate-2015, r=pnkfelix
a850a426491e14186af2250549bf41256b5938d2 Auto merge of #60133 - phansch:deny_rust_2018_idioms, r=Centril
8f06188991e8e7c764f0775a35432d39e2596c9a Auto merge of #60053 - Xanewok:serde-save-analysis, r=nrc
247b505099ce96b0fbf686249ff410a893793ed7 Auto merge of #60158 - Xanewok:update-clippy, r=matthiaskrgr
```

Its because of the NLL migration in #59114 

If you rerun the test with `--edition 2018` to enable NLL, you'll hit the ICE earlier than  31a75a1

**Comment by pnkfelix** [comment] 2020-01-16 04:02
T-compiler triage: P-high, removing nomination, adding A-NLL.

**Comment by pnkfelix** [comment] 2020-01-16 04:08
(I do wonder whether #65989 would address this...)

**Comment by pnkfelix** [comment] 2020-01-16 14:32
(or it might just be another case where we need lazy normalization ...)

**Comment by jackh726** [comment] 2021-08-29 13:10
Closing since there's a similar regression test in#85499

**Closed by jackh726** 2021-08-29 13:10 UTC
Labels: I-ICE, P-high, T-compiler, A-mir, regression-from-stable-to-stable, A-NLL, C-bug, A-lazy-normalization, glacier
