### ISSUE TITLE
On Linux, You Have To Manually Change The Shebang On x.py From Python To Python3

### ISSUE THREAD

**Issue by nishantc1527** [rust-lang/rust#75034] opened 2020-08-02 02:23 UTC
Currently, this is the first line in ```x.py```.

    #!/usr/bin/env python

However, on linux since it is ```python3``` by default when you install python (at least on centos), I have to manually change it to this every time I clone this repository.

    #!/usr/bin/env python3

Is there some way that there is an automated way to detect this? If not, maybe you can update the docs because it took me a while to figure out what was going wrong.

**Comment by lzutao** [comment] 2020-08-02 02:42
Do you mean that by default CentOS use python as python3?

**Comment by Mark-Simulacrum** [comment] 2020-08-02 03:01
There is unfortunately not a universal python shebang - windows never has python3 IIRC, and Ubuntu at least doesn't by default have a python these days.

If you have concrete proposals on how to make this work, I would love to hear them - a compiler team MCP is the way to go to propose such a change.

**Comment by mati865** [comment] 2020-08-02 08:12
@nishantc1527 You can either use `python3 x.py` or set python3 as the default version using this official guide: https://developers.redhat.com/blog/2018/11/14/python-in-rhel-8/

**Comment by K900** [comment] 2020-08-02 08:24
`#!/usr/bin/env python3` should be a universal shebang for Python 3 specifically - I'm not aware of any distributions that actively _remove_ the `python3` symlink, and the Windows launcher [understands it as well](https://docs.python.org/3/using/windows.html#shebang-lines).

**Comment by mati865** [comment] 2020-08-02 08:27
@K900 Rust supports both Python 2 and Python 3.

**Comment by nishantc1527** [comment] 2020-08-02 19:57
If there isn't an automated way to detect this (at least I can't thing of anything), then can the team update the documentation on how to install rust from source? It took me a while to figure out what was happening, and I believe someone smarter than me (which includes a lot of people) can get confused to.

**Comment by RalfJung** [comment] 2020-08-07 12:01
Cc https://github.com/rust-lang/rust/issues/71818: latest Ubuntu also does not have `python` any more by default, it seems.

So longer-term, I think it is clear that this should become `python3` eventually, as more and more distros no longer install Python 2 by default. The question is when is the right time for Rust to switch its shebang.

**Comment by K900** [comment] 2020-08-07 12:08
An alternative option would be to provide some sort of a wrapper script (`./x.sh`?) that effectively just does

```bash
PYTHON=`which python3 || which python2 || which python` 2>/dev/null
"${PYTHON}" ./x.py $@
```

**Comment by jyn514** [comment] 2020-08-18 13:11
Closing as duplicate of https://github.com/rust-lang/rust/issues/71818

**Closed by jyn514** 2020-08-18 13:11 UTC
Labels: A-rustbuild
