### ISSUE TITLE
Detect internal implementation usage that leads to infinite recursion

### ISSUE THREAD

**Issue by TotalKrill** [rust-lang/rust#74714] opened 2020-07-24 13:49 UTC
We found a simple way to cause infinite recursion in a sneaky way, it would be great to be able to have this as a warning or something. 

When implementing a trait, that trait can be invoked inside the trait implementation. Causing hard to detect bugs.

Simplest example: 
```rust
use std::fmt;
pub struct S;
impl fmt::Display for S {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self)
    }
}
fn main() {
    print!("{}", S);
}

```

[link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d05eb1e8dab2f7720c29e48fca6d8b80l)

**Comment by jonas-schievink** [comment] 2020-07-24 13:51
Duplicate of https://github.com/rust-lang/rust/issues/57965

**Comment by jonas-schievink** [comment] 2020-07-24 13:52
or rather, #58035

**Closed by jonas-schievink** 2020-07-24 13:51 UTC
