### ISSUE TITLE
bootstrap crashes in debug mode

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#54158] opened 2018-09-12 20:01 UTC
repo is at a2b991b5305b770c7d5288ab3aa231428511c530

this is my config.toml:
````toml
[llvm]
[build]
full-bootstrap = true
extended = true
tools = ["cargo", "rls", "rustfmt", "analysis", "src"]
sanitizers = true
profiler = true
low-priority = true
[install]
[rust]
debug = true
debug-assertions = true
debuginfo = true
debuginfo-lines = true
backtrace = true
verbose-tests = true
lld = true
llvm-tools = true
lldb = true
backtrace-on-ice = true
verify-llvm-ir = true
[target.x86_64-unknown-linux-gnu]
[dist]
````
while buidling, rustc crashed

````
Assembling stage2 compiler (x86_64-unknown-linux-gnu)
Building stage2 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling cc v1.0.22
   Compiling core v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/libcore)
   Compiling unwind v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/libunwind)
   Compiling build_helper v0.1.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/build_helper)
   Compiling compiler_builtins v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/rustc/compiler_builtins_shim)
   Compiling cmake v0.1.33
   Compiling profiler_builtins v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/libprofiler_builtins)
   Compiling alloc_jemalloc v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/liballoc_jemalloc)
   Compiling std v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/libstd)
   Compiling rustc_tsan v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/librustc_tsan)
   Compiling rustc_msan v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/librustc_msan)
   Compiling rustc_lsan v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/librustc_lsan)
warning: ../libcompiler_builtins/compiler-rt/lib/profile/InstrProfilingMerge.c:87:48: warning: unused parameter 'ProfileSize' [-Wunused-parameter]
warning:                                       uint64_t ProfileSize) {
warning:                                                ^
warning: 1 warning generated.
warning: ../libcompiler_builtins/compiler-rt/lib/profile/InstrProfilingUtil.c:128:3: warning: implicit declaration of function 'flock' is invalid in C99 [-Wimplicit-function-declaration]
warning:   flock(fd, LOCK_EX);
warning:   ^
warning: ../libcompiler_builtins/compiler-rt/lib/profile/InstrProfilingUtil.c:153:3: warning: implicit declaration of function 'flock' is invalid in C99 [-Wimplicit-function-declaration]
warning:   flock(fd, LOCK_UN);
warning:   ^
warning: 2 warnings generated.
warning: ../libcompiler_builtins/compiler-rt/lib/profile/InstrProfilingValue.c:108:60: warning: unused parameter 'Data' [-Wunused-parameter]
warning: static ValueProfNode *allocateOneNode(__llvm_profile_data *Data, uint32_t Index,
warning:                                                            ^
warning: ../libcompiler_builtins/compiler-rt/lib/profile/InstrProfilingValue.c:108:75: warning: unused parameter 'Index' [-Wunused-parameter]
warning: static ValueProfNode *allocateOneNode(__llvm_profile_data *Data, uint32_t Index,
warning:                                                                           ^
warning: ../libcompiler_builtins/compiler-rt/lib/profile/InstrProfilingValue.c:109:48: warning: unused parameter 'Value' [-Wunused-parameter]
warning:                                       uint64_t Value) {
warning:                                                ^
warning: 3 warnings generated.
   Compiling rustc_asan v0.0.0 (file:///home/matthias/vcs/github/rust_debug_assertions/src/librustc_asan)
error: internal compiler error: librustc/ty/context.rs:273: node unknown node (id=651354) with HirId::owner DefId(0/0:0 ~ core[5756]) cannot be placed in TypeckTables with local_id_root DefId(0/0:1807 ~ core[5756]::panicking[0]::panic_fmt[0])
thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:587:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   4: std::panicking::default_hook
             at libstd/panicking.rs:227
   5: core::ops::function::Fn::call
             at ./libcore/ops/function.rs:78
   6: rustc::util::common::panic_hook
             at librustc/util/common.rs:51
   7: core::ops::function::Fn::call
             at ./libcore/ops/function.rs:78
   8: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:481
   9: std::panicking::begin_panic
             at ./libstd/panicking.rs:411
  10: rustc_errors::Handler::bug
             at librustc_errors/lib.rs:587
  11: rustc::util::bug::opt_span_bug_fmt::{{closure}}
             at librustc/util/bug.rs:46
  12: rustc::ty::context::tls::with_opt::{{closure}}
             at librustc/ty/context.rs:2065
  13: rustc::ty::context::tls::with_context_opt
             at librustc/ty/context.rs:2002
  14: rustc::ty::context::tls::with_opt
             at librustc/ty/context.rs:2065
  15: rustc::util::bug::opt_span_bug_fmt
             at librustc/util/bug.rs:42
  16: rustc::util::bug::bug_fmt
             at librustc/util/bug.rs:22
  17: rustc::ty::context::validate_hir_id_for_typeck_tables::{{closure}}
             at librustc/ty/context.rs:273
  18: rustc::ty::context::tls::with::{{closure}}
             at librustc/ty/context.rs:2057
  19: rustc::ty::context::tls::with_context::{{closure}}
             at librustc/ty/context.rs:2011
  20: rustc::ty::context::tls::with_context_opt
             at librustc/ty/context.rs:2002
  21: rustc::ty::context::tls::with_context
             at librustc/ty/context.rs:2011
  22: rustc::ty::context::tls::with
             at librustc/ty/context.rs:2057
  23: rustc::ty::context::validate_hir_id_for_typeck_tables
             at librustc/ty/context.rs:270
  24: rustc::ty::context::TypeckTables::node_id_to_type_opt
             at librustc/ty/context.rs:556
  25: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_formals
             at librustc_save_analysis/dump_visitor.rs:280
  26: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_foreign_item::{{closure}}
             at librustc_save_analysis/dump_visitor.rs:1708
  27: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_tables
             at librustc_save_analysis/dump_visitor.rs:137
  28: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_foreign_item
             at librustc_save_analysis/dump_visitor.rs:1706
  29: syntax::visit::walk_item
             at ./libsyntax/visit.rs:166
  30: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
             at librustc_save_analysis/dump_visitor.rs:1529
  31: syntax::visit::walk_stmt
             at ./libsyntax/visit.rs:636
  32: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_stmt
             at librustc_save_analysis/dump_visitor.rs:1682
  33: syntax::visit::walk_block
             at ./libsyntax/visit.rs:166
  34: syntax::visit::Visitor::visit_block
             at ./libsyntax/visit.rs:66
  35: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_fn::{{closure}}::{{closure}}
             at librustc_save_analysis/dump_visitor.rs:436
  36: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_scope
             at librustc_save_analysis/dump_visitor.rs:121
  37: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_fn::{{closure}}
             at librustc_save_analysis/dump_visitor.rs:436
  38: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_tables
             at librustc_save_analysis/dump_visitor.rs:134
  39: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_fn
             at librustc_save_analysis/dump_visitor.rs:436
  40: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
             at librustc_save_analysis/dump_visitor.rs:1450
  41: syntax::visit::walk_mod
             at ./libsyntax/visit.rs:166
  42: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item::{{closure}}
             at librustc_save_analysis/dump_visitor.rs:1466
  43: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_scope
             at librustc_save_analysis/dump_visitor.rs:121
  44: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
             at librustc_save_analysis/dump_visitor.rs:1466
  45: syntax::visit::walk_mod
             at ./libsyntax/visit.rs:166
  46: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_mod::{{closure}}
             at librustc_save_analysis/dump_visitor.rs:1409
  47: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::nest_scope
             at librustc_save_analysis/dump_visitor.rs:121
  48: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_mod
             at librustc_save_analysis/dump_visitor.rs:1409
  49: syntax::visit::walk_crate
             at ./libsyntax/visit.rs:181
  50: <rustc_save_analysis::DumpHandler<'a> as rustc_save_analysis::SaveHandler>::save
             at librustc_save_analysis/lib.rs:1089
  51: rustc_save_analysis::process_crate::{{closure}}
             at ./librustc_save_analysis/lib.rs:1140
  52: rustc::dep_graph::graph::DepGraph::with_ignore::{{closure}}::{{closure}}
             at ./librustc/dep_graph/graph.rs:167
  53: rustc::ty::context::tls::enter_context::{{closure}}
             at ./librustc/ty/context.rs:1927
  54: rustc::ty::context::tls::set_tlv
             at ./librustc/ty/context.rs:1866
  55: rustc::ty::context::tls::enter_context
             at ./librustc/ty/context.rs:1926
  56: rustc::dep_graph::graph::DepGraph::with_ignore::{{closure}}
             at ./librustc/dep_graph/graph.rs:166
  57: rustc::ty::context::tls::with_context::{{closure}}
             at ./librustc/ty/context.rs:2011
  58: rustc::ty::context::tls::with_context_opt
             at ./librustc/ty/context.rs:2002
  59: rustc::ty::context::tls::with_context
             at ./librustc/ty/context.rs:2011
  60: rustc::dep_graph::graph::DepGraph::with_ignore
             at ./librustc/dep_graph/graph.rs:160
  61: rustc_save_analysis::process_crate
             at ./librustc_save_analysis/lib.rs:1126
  62: rustc_driver::enable_save_analysis::{{closure}}::{{closure}}
             at librustc_driver/lib.rs:979
  63: rustc::util::common::time_ext
             at ./librustc/util/common.rs:163
  64: rustc::util::common::time
             at ./librustc/util/common.rs:157
  65: rustc_driver::enable_save_analysis::{{closure}}
             at librustc_driver/lib.rs:978
  66: rustc_driver::driver::compile_input::{{closure}}::{{closure}}
             at librustc_driver/driver.rs:311
  67: rustc::dep_graph::graph::DepGraph::with_ignore::{{closure}}::{{closure}}
             at ./librustc/dep_graph/graph.rs:167
  68: rustc::ty::context::tls::enter_context::{{closure}}
             at ./librustc/ty/context.rs:1927
  69: rustc::ty::context::tls::set_tlv
             at ./librustc/ty/context.rs:1866
  70: rustc::ty::context::tls::enter_context
             at ./librustc/ty/context.rs:1926
  71: rustc::dep_graph::graph::DepGraph::with_ignore::{{closure}}
             at ./librustc/dep_graph/graph.rs:166
  72: rustc::ty::context::tls::with_context::{{closure}}
             at ./librustc/ty/context.rs:2011
  73: rustc::ty::context::tls::with_context_opt
             at ./librustc/ty/context.rs:2002
  74: rustc::ty::context::tls::with_context
             at ./librustc/ty/context.rs:2011
  75: rustc::dep_graph::graph::DepGraph::with_ignore
             at ./librustc/dep_graph/graph.rs:160
  76: rustc_driver::driver::compile_input::{{closure}}
             at librustc_driver/driver.rs:299
  77: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
             at librustc_driver/driver.rs:1349
  78: rustc::ty::context::tls::enter_global::{{closure}}::{{closure}}
             at ./librustc/ty/context.rs:1959
  79: rustc::ty::context::tls::enter_context::{{closure}}
             at ./librustc/ty/context.rs:1927
  80: rustc::ty::context::tls::set_tlv
             at ./librustc/ty/context.rs:1866
  81: rustc::ty::context::tls::enter_context
             at ./librustc/ty/context.rs:1926
  82: rustc::ty::context::tls::enter_global::{{closure}}
             at ./librustc/ty/context.rs:1958
  83: rustc::ty::context::tls::with_thread_locals::{{closure}}::{{closure}}
             at ./librustc/ty/context.rs:1916
  84: <std::thread::local::LocalKey<T>>::try_with
             at ./libstd/thread/local.rs:294
  85: <std::thread::local::LocalKey<T>>::with
             at ./libstd/thread/local.rs:248
  86: rustc::ty::context::tls::with_thread_locals::{{closure}}
             at ./librustc/ty/context.rs:1908
  87: <std::thread::local::LocalKey<T>>::try_with
             at ./libstd/thread/local.rs:294
  88: <std::thread::local::LocalKey<T>>::with
             at ./libstd/thread/local.rs:248
  89: rustc::ty::context::tls::with_thread_locals
             at ./librustc/ty/context.rs:1900
  90: rustc::ty::context::tls::enter_global
             at ./librustc/ty/context.rs:1938
  91: rustc::ty::context::TyCtxt::create_and_enter
             at ./librustc/ty/context.rs:1244
  92: rustc_driver::driver::phase_3_run_analysis_passes
             at librustc_driver/driver.rs:1257
  93: rustc_driver::driver::compile_input
             at librustc_driver/driver.rs:285
  94: rustc_driver::run_compiler_with_pool
             at librustc_driver/lib.rs:563
  95: rustc_driver::run_compiler::{{closure}}
             at librustc_driver/lib.rs:485
  96: rustc_driver::driver::spawn_thread_pool::{{closure}}
             at librustc_driver/driver.rs:74
  97: <scoped_tls::ScopedKey<T>>::set
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  98: rustc_driver::driver::spawn_thread_pool
             at librustc_driver/driver.rs:73
  99: rustc_driver::run_compiler
             at librustc_driver/lib.rs:484
query stack during panic:
end of query stack
error: aborting due to previous error
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.30.0-dev running on x86_64-unknown-linux-gnu
note: compiler flags: -Z save-analysis -Z force-unstable-if-unmarked -Z verify-llvm-ir -C debug-assertions=off -C overflow-checks=on -C incremental -C target-cpu=native -C prefer-dynamic -C debug-assertions=y -C link-args=-Wl,-rpath,$ORIGIN/../lib --crate-type lib
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `core`.
Caused by:
  process didn't exit successfully: `/home/matthias/vcs/github/rust_debug_assertions/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C debug-assertions=off -C overflow-checks=on -C metadata=7c64d87825e1c0b3 -C extra-filename=-7c64d87825e1c0b3 --out-dir /home/matthias/vcs/github/rust_debug_assertions/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/home/matthias/vcs/github/rust_debug_assertions/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/home/matthias/vcs/github/rust_debug_assertions/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/matthias/vcs/github/rust_debug_assertions/build/x86_64-unknown-linux-gnu/stage2-std/debug/deps -C target-cpu=native` (exit code: 101)
command did not execute successfully: "/home/matthias/vcs/github/rust_debug_assertions/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--features" "panic-unwind debug-jemalloc jemalloc backtrace profiler" "--manifest-path" "/home/matthias/vcs/github/rust_debug_assertions/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1155:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /home/matthias/vcs/github/rust_debug_assertions/build/bootstrap/debug/bootstrap build
Build completed unsuccessfully in 12:15:19
````

**Comment by matthiaskrgr** [comment] 2018-09-12 20:01
Is this a duplicate to #54150  or #43982 ?

**Comment by o01eg** [comment] 2018-10-02 21:01
Got same without sanitizers and with debug-assertions only on 1c5e9c68ea6c76fe400528de17ebe03e338bac68 :

config.toml:
```toml
[llvm]
optimize = true
release-debuginfo = false
assertions = false
targets = "X86"
link-jobs = 3
[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu"]
docs = true
submodules = false
python = "python2.7"
locked-deps = true
vendor = false
verbose = 2
sanitizers = false
extended = true
tools = ["clippy","src",]
[install]
prefix = "/usr"
libdir = "lib64/rust-9999"
docdir = "share/doc/rust-9999"
mandir = "share/rust-9999/man"
[rust]
optimize = true
debuginfo = false
debug-assertions = true # false
use-jemalloc = true
default-linker = "x86_64-pc-linux-gnu-gcc"
rpath = false
ignore-git = false
lld = false
llvm-tools = true
[target.x86_64-unknown-linux-gnu]
cc = "x86_64-pc-linux-gnu-gcc"
cxx = "x86_64-pc-linux-gnu-g++"
linker = "x86_64-pc-linux-gnu-gcc"
ar = "x86_64-pc-linux-gnu-ar"
```

```
   Compiling core v0.0.0 (/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libcore)
     Running `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --color always --error-format jso
n --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=7430e8604190d953 -C extra-filename=-7430e8604190d953 --out-dir /tmp/portage/dev-lang/rust-9
999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/tmp/por
tage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/tmp/portage/dev-lang/
rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps -L /usr/lib64/rust-1.29.0/ -L /usr/lib64/rust-1.29.0/rustlib//lib/`
rustc command: "LD_LIBRARY_PATH"="/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1/lib:/tmp/portage/dev-lang/rust-9999/
work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps:/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stag
e0/lib" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "--crate-name" "core" "libcore/lib.rs" "--color" "
always" "--crate-type" "lib" "--emit=dep-info,link" "-C" "opt-level=2" "-C" "metadata=7430e8604190d953-rustc" "-C" "extra-filename=-7430e8604190d953" "--out-d
ir" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps" "--target" "x86_64-unk
nown-linux-gnu" "-L" "dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/
deps" "-L" "dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps" "-L" "/usr/lib64/rust-1.29.0/
" "-L" "/usr/lib64/rust-1.29.0/rustlib//lib/" "--cfg" "stage1" "--sysroot" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/s
tage1" "-Cprefer-dynamic" "-Clinker=x86_64-pc-linux-gnu-gcc" "-C" "debug-assertions=y" "-Zsave-analysis" "-Z" "force-unstable-if-unmarked" "-Dwarnings" "-Dbar
e_trait_objects"
sysroot: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1"
libdir: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1/lib"
error: internal compiler error: librustc/ty/context.rs:273: node unknown node (id=651901) with HirId::owner DefId(0/0:0 ~ core[565c]) cannot be placed in Type
ckTables with local_id_root DefId(0/0:1817 ~ core[565c]::panicking[0]::panic_fmt[0])

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:599:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc::ty::context::validate_hir_id_for_typeck_tables::{{closure}}
  15: rustc::ty::context::tls::with::{{closure}}
  16: rustc::ty::context::tls::with_context::{{closure}}
  17: rustc::ty::context::tls::with_context_opt
  18: rustc::ty::context::tls::with_context
  19: rustc::ty::context::tls::with
  20: rustc::ty::context::TypeckTables::node_id_to_type_opt
  21: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O>>::process_formals
  22: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_foreign_item
  23: syntax::visit::walk_item
  24: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
  25: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_item
  26: <rustc_save_analysis::dump_visitor::DumpVisitor<'l, 'tcx, 'll, O> as syntax::visit::Visitor<'l>>::visit_mod
  27: syntax::visit::walk_crate
  28: <rustc_save_analysis::DumpHandler<'a> as rustc_save_analysis::SaveHandler>::save
  29: rustc::ty::context::tls::with_context
  30: rustc_save_analysis::process_crate
  31: rustc_driver::enable_save_analysis::{{closure}}::{{closure}}
  32: rustc::util::common::time
  33: rustc_driver::enable_save_analysis::{{closure}}
  34: rustc::ty::context::tls::with_context
  35: rustc_driver::driver::compile_input::{{closure}}
  36: rustc::ty::context::tls::enter_context
  37: <std::thread::local::LocalKey<T>>::with
  38: rustc::ty::context::TyCtxt::create_and_enter
  39: rustc_driver::driver::compile_input
  40: rustc_driver::run_compiler_with_pool
  41: rustc_driver::driver::spawn_thread_pool
  42: rustc_driver::run_compiler
  43: syntax::with_globals
  44: __rust_maybe_catch_panic
  45: std::panicking::try
  46: rustc_driver::run
  47: rustc_driver::main
  48: std::rt::lang_start::{{closure}}
  49: std::panicking::try::do_call
  50: __rust_maybe_catch_panic
  51: std::panicking::try
  52: std::rt::lang_start_internal
  53: main
  54: __libc_start_main
  55: _start
query stack during panic:
end of query stack
error: aborting due to previous error

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-dev (1c5e9c68e 2018-10-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis -Z force-unstable-if-unmarked -C opt-level=2 -C prefer-dynamic -C linker=x86_64-pc-linux-gnu-gcc -C debug-assertions=y --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=7430e8604190d953 -C extra-filename=-7430e8604190d953 --out-dir /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage1-std/release/deps -L /usr/lib64/rust-1.29.0/ -L /usr/lib64/rust-1.29.0/rustlib//lib/` (exit code: 101)
command did not execute successfully: "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "1" "-v" "--release" "--locked" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1112:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
             at libstd/panicking.rs:411
   6: bootstrap::compile::run_cargo
             at bootstrap/compile.rs:1112
   7: <bootstrap::compile::Std as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:115
   8: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:1215
   9: <bootstrap::compile::Test as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:356
  10: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:1215
  11: <bootstrap::compile::Rustc as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:478
  12: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:1215
  13: <bootstrap::compile::Assemble as bootstrap::builder::Step>::run
             at bootstrap/compile.rs:970
  14: bootstrap::builder::Builder::ensure
             at bootstrap/builder.rs:1215
  15: bootstrap::builder::Builder::compiler
             at bootstrap/builder.rs:580
  16: <bootstrap::compile::Std as bootstrap::builder::Step>::make_run
             at bootstrap/compile.rs:55
  17: bootstrap::builder::StepDescription::maybe_run
             at bootstrap/builder.rs:191
  18: bootstrap::builder::StepDescription::run
             at bootstrap/builder.rs:215
  19: bootstrap::builder::Builder::run_step_descriptions
             at bootstrap/builder.rs:572
  20: bootstrap::builder::Builder::execute_cli
             at bootstrap/builder.rs:562
  21: bootstrap::Build::build
             at bootstrap/lib.rs:485
  22: bootstrap::main
             at bootstrap/bin/main.rs:29
  23: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  24: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  25: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  26: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  27: std::rt::lang_start
             at libstd/rt.rs:74
  28: main
  29: __libc_start_main
  30: _start
Traceback (most recent call last):
  File "./x.py", line 20, in <module>
    bootstrap.main()
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 855, in main
    bootstrap(help_triggered)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 841, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/tmp/portage/dev-lang/rust-9999/work/rust-git-src/src/bootstrap/bootstrap.py", line 151, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/portage/dev-lang/rust-9999/work/rust-git-src/build/bootstrap/debug/bootstrap build --verbose --config=/tmp/portage/dev-lang/rust-9999/work/rust-git-src/config.toml -j1 --exclude src/tools/miri
```

**Comment by jonas-schievink** [comment] 2019-08-25 13:16
This seems to be a direct duplicate of https://github.com/rust-lang/rust/issues/50328, so closing in favor of that

**Closed by jonas-schievink** 2019-08-25 13:16 UTC
Labels: C-bug, I-ICE, T-compiler
