### ISSUE TITLE
Poor error message from try! or ? and type-mismatch

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#36988] opened 2016-10-05 22:27 UTC
For `try!` we used to give a type mismatch message when the type of the value did not match the function type (see example below). We now give a message about the `Carrier` trait, which the user should not know about, e.g., `error[E0277]: the trait bound `(): std::ops::Carrier` is not satisfied` for the below example.

I removed the following from doc/error-index.md

```
Another situation in which this occurs is when you attempt to use the `try!`
macro inside a function that does not return a `Result<T, E>`:

```compile_fail,E0308
use std::fs::File;

fn main() {
    let mut f = try!(File::create("foo.txt"));
}
```

This code gives an error like this:

```text
<std macros>:5:8: 6:42 error: mismatched types:
 expected `()`,
     found `core::result::Result<_, _>`
 (expected (),
     found enum `core::result::Result`) [E0308]
```

`try!` returns a `Result<T, E>`, and so the function must. But `main()` has
`()` as its return type, hence the error.
```

**Comment by durka** [comment] 2016-10-06 16:15
Yeah, the error about Carrier is even worse than before (which even then was not enough to get users all the way to "I need to change this function to return a Result"). Should we make Carrier a lang item so it can be special-cased here?

**Comment by nikomatsakis** [comment] 2016-10-11 13:45
This feels like a serious problem. This is an area where user confusion is common and it's a particular stumbling block for new users (the old message itself was a problem). I agree with @durka that it is probably worth special-casing here!

cc @wycats @jonathandturner

**Comment by jonathandturner** [comment] 2016-10-11 16:27
Is the special case here that it expects () as the output but sees a Result?

**Comment by durka** [comment] 2016-10-11 16:43
@jonathandturner we should be able to go further than that, since the message says "in this expansion of `try`" (at least it used to -- in nightly this info has been lost in favor of "macro outside of the current crate"), e.g. it knows about the macro. In the case of `?` the compiler obviously knows about that too.

**Comment by jonathandturner** [comment] 2016-10-11 21:10
@durka - sounds good

The macro backtrace should still be there for the `try!` case, so you could detect the type mismatch and before reporting it check the backtrace to see if we're calling through a `try!`

**Comment by durka** [comment] 2016-10-11 21:12
If someone can give me a pointer on how to get the macro backtrace during error reporting, I can work on this.

**Comment by jonathandturner** [comment] 2016-10-11 21:19
@durka - you can check `macro_backtrace` in `src/libsyntax/codemap.rs`.  Looks like it starts at about line 806.

Looks like E0308 is coming from `report_and_explain_type_error` in `src/librustc/infer/error_reporting.rs`.  I *think* you should be able to dig through `self.tcx.gcx.sess` to get the codemap for the backtrace.

**Comment by carols10cents** [comment] 2016-10-11 22:13
Is this the same as #35946?

**Comment by durka** [comment] 2016-10-11 22:16
@carols10cents yes.

**Comment by jonathandturner** [comment] 2016-10-11 22:26
Close as a dupe of #35946

**Closed by jonathandturner** 2016-10-11 22:26 UTC
Labels: A-diagnostics
