### ISSUE TITLE
BufRead::read_line() takes the newline character as well.

### ISSUE THREAD

**Issue by Plasticcaz** [rust-lang/rust#23636] opened 2015-03-23 12:15 UTC
I find it annoying to continually have to take into account that read_line() includes the newline character as part of it's input. I cannot see any real reason for this to be the case, and it creates more of a hassle for the programmer to handle.

If there is a good reason for this behavior, I cannot see it.

**Comment by steveklabnik** [comment] 2015-03-23 12:39
This is explicitly intended behavior of a stable method, and so isn't likely to change. Thoughts @alexcrichton ?

**Comment by Plasticcaz** [comment] 2015-03-23 12:44
May I know the reasoning behind this? I can't see a reason for the new line, as it seems a far more common scenario where you don't care about the newline than when you do care.

If there's a valid reason for this, then fair enough, just though I should put my 2 cents in. :)

**Comment by pnkfelix** [comment] 2015-03-23 14:31
One reason one might want this behavior (of retaining the newline charater), though I do not know if it was the original motivation:

I believe you can always reconstruct the original input based on the results yielded by a series of calls to `read_line`, even if the last "line" in a file terminates with EOF (that is, without a newline).

If it did not include the newline character, then an attempt to reconstruct the input would fail to distinguish inputs where the last line ended in EOF versus newline followed by EOF.

**Comment by GuillaumeGomez** [comment] 2015-03-23 15:49
A question about the newline character: is it platform dependent ? So under Windows,, it will be "\r\n", under linux it will be "\n" and under OSX it will be "\r" ? If so, is there a non-platform dependent const defined in Rust for this newline character ?

**Comment by alexcrichton** [comment] 2015-03-23 17:45
@pnkfelix put it well, the purpose of this is to allow you to reconstruct the original input with simply calls to `read_line`. The `lines` iterator will chop off the trailing newline if you need to. This is intended behavior, though, so closing.

**Closed by alexcrichton** 2015-03-23 17:45 UTC
Labels: A-libs
