### ISSUE TITLE
Compiler panic when calling map in a const expression

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#23828] opened 2015-03-29 10:16 UTC
http://is.gd/zCNViG
```
const VV: Vec<&'static str> =
    vec!("A" , "B").drain().map(|s| s).collect::<Vec<&'static str>>();
```

Obviously it is intended that this code produce a compiler error, but it also causes the compiler to panic with this message:
```
thread 'rustc' panicked at 'assertion failed: self.mode == Mode::Var',
/home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/check_const.rs:232
```

**Comment by jakub-** [comment] 2015-05-14 11:27
More likely than not a dupe of https://github.com/rust-lang/rust/issues/25180 but I'll leave open as it's slightly different.

**Comment by arielb1** [comment] 2015-06-18 09:18
This does seem like a duplicate. Closing.

**Closed by arielb1** 2015-06-18 09:18 UTC
Labels: I-ICE
