### ISSUE TITLE
Misleading documentation for str::match_indices

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#103232] opened 2022-10-19 09:03 UTC
### Location

https://doc.rust-lang.org/std/primitive.str.html#method.match_indices
### Summary

```rust
fn main() {
    let v: Vec<_> = "abababa".match_indices("aba").collect();
    assert_eq!(v, [(0, "aba"), (4, "aba")]);
}
```

**Comment by ehuss** [comment] 2022-10-19 12:27
I'm going to close, assuming this was an unintentional duplicate of #103235. Feel free to reopen in case I misinterpreted.

**Closed by ehuss** 2022-10-19 12:27 UTC
Labels: A-docs
