### ISSUE TITLE
toolchain 'nightly-x86_64-pc-windows-gnu' does not have the binary `rust-gdb.exe`

### ISSUE THREAD

**Issue by norru** [rust-lang/rust#54615] opened 2018-09-27 16:46 UTC
This is the affected toolchain:

```
nightly-x86_64-pc-windows-gnu unchanged - rustc 1.30.0-nightly (ae7fe84e8 2018-09-26)
```

Can this be worked around effectively?

**Comment by tromey** [comment] 2019-01-17 16:09
I think the problem is just that `dist.rs` does not install this script on Windows?  See https://github.com/rust-lang/rust/blob/master/src/bootstrap/dist.rs#L591-L614

**Comment by norru** [comment] 2019-01-17 16:49
Not sure. This bug relates to the `windows-gnu` toolchain rather than `windows-msvc`.

**Comment by mati865** [comment] 2019-03-05 09:53
I think it's an issue with rustup proxies:
```
$ rust-gdb
error: 'rust-gdb.exe' is not installed for the toolchain 'nightly-x86_64-pc-windows-gnu'

$ /c/Users/mateusz/.rustup/toolchains/nightly-x86_64-pc-windows-gnu/bin/rust-gdb
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) q
```

**Comment by Enselic** [comment] 2023-11-16 01:00
Triage: closing since rust-gdb was not missing. This might be a rustup bug, but that should be reported to rustup in that case.

**Closed by Enselic** 2023-11-16 01:00 UTC
Labels: O-windows-gnu, T-dev-tools
