### ISSUE TITLE
Unergonomic pub(in path) error message

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#40691] opened 2017-03-21 00:29 UTC
The pub(in path) error message is very unergonomic when it comes to paths that don't exist, or don't exist yet. Take this example, its how the error was intented:

```rust
pub mod baa {}
pub mod boo {
	pub (in baa) fn foo() {}
}
```
gives an error "visibilities can only be restricted to ancestor modules". Now take this example:

```rust
pub mod boo {
	pub (in baa) fn foo() {}
}
pub mod baa {}
```

This gives an error "cannot find module `baa` in the crate root".

And this code:

```rust
pub mod boo {
	pub (in baa::baa) fn foo() {}
}
```
even gives an error "failed to resolve. Maybe a missing `extern crate baa;`?".

What should happen instead is that in the second and third case, it should output an error similar to the first one. As it seems to not know about modules declared after the code yet (see second case), adding a note to the existing error is not enough, as clearly an error "cannot find module `baa` in the crate root" is misleading in this case. So unless it can be taught to know modules declared after the current code, I'd suggest to have an error similar to the first case in all three cases.

**Comment by est31** [comment] 2017-03-21 01:02
Seems this is already pointed out in `src/test/compile-fail/resolve-bad-visibility.rs`. Still, I consider this a bug.

**Comment by petrochenkov** [comment] 2017-03-21 08:46
Duplicate of https://github.com/rust-lang/rust/issues/40066

**Closed by petrochenkov** 2017-03-21 08:46 UTC
