### ISSUE TITLE
compiler abort in LLVM code when using a newtype-wrapper as an argument

### ISSUE THREAD

**Issue by TethysSvensson** [rust-lang/rust#15402] opened 2014-07-04 05:52 UTC
The following program will cause an abort in llvm/lib/IR/InlineAsm.cpp:

``` rust
#![feature(asm)]

pub struct Wrapper(uint);

fn main() {
    let mut value: Wrapper = Wrapper(7);
    unsafe {
        asm!("mov %eax, $0" : "+r"(value));
    }
}
```

The error message I get is:

```
rustc: /build/buildd/rust-nightly-201407030406~67776ba~utopic/src/llvm/lib/IR/InlineAsm.cpp:47: llvm::InlineAsm::InlineAsm(llvm::PointerType*, const string&, const string&, bool, bool, llvm::InlineAsm::AsmDialect): Assertion `Verify(getFunctionType(), constraints) && "Function type not legal for constraints!"' failed.
Aborted (core dumped)
```

I am using the rust nightly build version 201407030406~67776ba~utopic.

**Comment by richo** [comment] 2015-04-06 08:23
Just ran into this again, however for a lot of this year this worked, as I [wrote some code that does this][code].

[code]: https://github.com/richo/rs-beef/blob/master/src/jit.rs#L122-L124

**Comment by tamird** [comment] 2015-04-21 21:49
This once again does not ICE:
```rust
#![feature(asm)]

pub struct Wrapper(u32);

fn main() {
    let mut value: Wrapper = Wrapper(7);
    unsafe {
        asm!("mov %eax, $0" : "+r"(value));
    }
}
```
@steveklabnik E-needstest?

**Comment by jooert** [comment] 2015-05-11 20:44
With LLVM assertions enabled, this still fails with the same error message.

**Comment by jethrogb** [comment] 2016-01-26 00:24
The error depends on the exact asm invocation. 

```rust
#![feature(asm)]

#[repr(packed)]
struct Bitfield<T>(T);

fn test()->(Bitfield<u32>,Bitfield<u32>) {
	let mut out=(Bitfield(0),Bitfield(0));
	unsafe{asm!("" : "={eax}"(out.0), "={ebx}"(out.1))};
	out
}

fn main() {
    test();
}
```
yields:
```
Unknown type!
UNREACHABLE executed at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/ValueTypes.cpp:253!
```

While this

```rust
#![feature(asm)]

#[repr(packed)]
struct Bitfield<T>(T);

fn test()->(Bitfield<u32>,Bitfield<u32>) {
	let mut out=(Bitfield(0),Bitfield(0));
	unsafe{asm!("" : "={eax}"(out.0))};
	out
}

fn main() {
    test();
}
```
yields:
```
rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/InlineAsm.cpp:47: llvm::InlineAsm::InlineAsm(llvm::PointerType*, const string&, const string&, bool, bool, llvm::InlineAsm::AsmDialect): Assertion `Verify(getFunctionType(), constraints) && "Function type not legal for constraints!"' failed.
```

**Comment by lukaramu** [comment] 2017-08-13 20:43
Triage: [still reproduces](https://play.rust-lang.org/?gist=72ea51fc477c80fa9bd574a7177268da&version=nightly)

<details>

```
rustc: /checkout/src/llvm/lib/IR/InlineAsm.cpp:46: llvm::InlineAsm::InlineAsm(llvm::FunctionType*, const string&, const string&, bool, bool, llvm::InlineAsm::AsmDialect): Assertion `Verify(getFunctionType(), constraints) && "Function type not legal for constraints!"' failed.
error: Could not compile `playground`.
```

</details>

**Comment by steveklabnik** [comment] 2017-11-19 11:58
This no longer ICEs!

**Comment by petrochenkov** [comment] 2017-11-19 12:35
Because LLVM assertions were disabled on nightly https://github.com/rust-lang/rust/pull/45810

**Comment by pnkfelix** [comment] 2019-06-03 12:42
ICE is dependent on `feature(asm)` (cc #29722), which is not on the 2019 roadmap. Marking as P-medium until we get an overall plan for asm in Rust. (Although the fact that this can cause rustc itself to segfault, presumably via a problem internal to LLVM, does lead me to wonder if I should up the priority to P-high anyway.)

**Comment by Amanieu** [comment] 2020-05-22 19:08
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which has stricter checks on the types that can be used as asm operands.

The legacy `llvm_asm!` is deprecated and is no longer maintained.

**Closed by Amanieu** 2020-05-22 19:08 UTC
Labels: A-inline-assembly, C-bug, I-ICE, P-medium, glacier, requires-nightly
