### ISSUE TITLE
 internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by ChenLongxi666** [rust-lang/rust#85062] opened 2021-05-08 01:40 UTC
```
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[bd3a]::ops::arith::Add): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Rhs as std::marker::Sized>)), C:\DevTool\Rust\Rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\arith.rs:75:15: 75:18 (#0)), (Binder(TraitPredicate(<Self as std::ops::Add<Rhs>>)), C:\DevTool\Rust\Rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\ops\arith.rs:75:1: 75:26 (#0))] }', /rustc/88f19c6dab716c6281af7602e30f413e809c5974\compiler\rustc_query_system\src\query\plumbing.rs:593:5
stack backtrace:
   0:     0x7fffbdf681fe - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3ee8647f7e1079db
   1:     0x7fffbdf932fc - core::fmt::write::h37cf99794c5c88ee
   2:     0x7fffbdf5bc58 - <std::io::IoSliceMut as core::fmt::Debug>::fmt::hbb31fdd82c487bf0
   3:     0x7fffbdf6c39d - std::panicking::take_hook::he8d839f36ebc5025
   4:     0x7fffbdf6be69 - std::panicking::take_hook::he8d839f36ebc5025
   5:     0x7fff92d1d9c7 - rustc_driver::report_ice::hc57d4e141f91d8a8
   6:     0x7fffbdf6cbf5 - std::panicking::rust_panic_with_hook::h82b4e4f3be46852c
   7:     0x7fffbdf6c761 - rust_begin_unwind
   8:     0x7fffbdf68b4f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3ee8647f7e1079db
   9:     0x7fffbdf6c6b9 - rust_begin_unwind
  10:     0x7fffbdfc4dec - std::panicking::begin_panic_fmt::h3cee835f7be6e70f
  11:     0x7fff958ddffc - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  12:     0x7fff95905b44 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  13:     0x7fff95b3a91b - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  14:     0x7fff9581a290 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  15:     0x7fff95a5c18d - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  16:     0x7fff96d51c11 - rustc_middle::ty::generics::GenericPredicates::instantiate_own::h51d523cc130602b9
  17:     0x7fff96d51617 - rustc_middle::ty::generics::GenericPredicates::instantiate::he2f245abffd92c7a
  18:     0x7fff953b3633 - rustc_typeck::check::method::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::lookup_method_in_trait::h262c595ae062c836
  19:     0x7fff95395cba - rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_user_unop::h05003250915c4aa6
  20:     0x7fff95391217 - rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_binop::hca6dbec0ddb6bae1
  21:     0x7fff95390c00 - rustc_typeck::check::op::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_binop::hca6dbec0ddb6bae1
  22:     0x7fff9535a8c7 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  23:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  24:     0x7fff9535d0e6 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  25:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  26:     0x7fff95572c95 - rustc_lint::context::LintStore::get_lints::h121906fa46b88a25
  27:     0x7fff955071d9 - <rustc_typeck::variance::terms::InferredIndex as core::fmt::Debug>::fmt::hccc481d056661463
  28:     0x7fff9535bd76 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  29:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  30:     0x7fff95340e65 - rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match::h9f626a622567ce73
  31:     0x7fff9533e08e - rustc_typeck::check::_match::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_match::h9f626a622567ce73
  32:     0x7fff9535984d - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  33:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  34:     0x7fff9535d0e6 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  35:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  36:     0x7fff95378c24 - rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::structurally_resolved_type::h2915508e7488dab4
  37:     0x7fff953451ce - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call::hf8989828e38eb91c
  38:     0x7fff95342c66 - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call::hf8989828e38eb91c
  39:     0x7fff95359cd5 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  40:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  41:     0x7fff95378c24 - rustc_typeck::check::fn_ctxt::_impl::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::structurally_resolved_type::h2915508e7488dab4
  42:     0x7fff953451ce - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call::hf8989828e38eb91c
  43:     0x7fff95342c66 - rustc_typeck::check::callee::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_call::hf8989828e38eb91c
  44:     0x7fff95359cd5 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  45:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  46:     0x7fff9537c62f - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt::h24e664f26b14ece2
  47:     0x7fff9537d041 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_no_value::h04dadce00f98d3e8
  48:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  49:     0x7fff9537c62f - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt::h24e664f26b14ece2
  50:     0x7fff9537d041 - rustc_typeck::check::fn_ctxt::checks::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_no_value::h04dadce00f98d3e8
  51:     0x7fff953592df - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  52:     0x7fff95366534 - rustc_typeck::check::expr::<impl rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation::ha3f484f82cb4a6ff
  53:     0x7fff95508cd1 - rustc_typeck::check::check::check_wf_new::h9c32b11c71de1be8
  54:     0x7fff95494488 - <rustc_typeck::astconv::ConvertedBindingKind as core::fmt::Debug>::fmt::h5519b26bf4527d33
  55:     0x7fff95525641 - <rustc_typeck::check::fixup_opaque_types::FixupFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty::hd4ce30df61a3cf38
  56:     0x7fff95b22379 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  57:     0x7fff95a89989 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  58:     0x7fff95b4bc88 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  59:     0x7fff9588b3ea - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  60:     0x7fff957f1958 - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  61:     0x7fff95a60082 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  62:     0x7fff9541862b - <rustc_typeck::bounds::Bounds as core::fmt::Debug>::fmt::h5859ca23977fa056
  63:     0x7fff95526ff3 - <rustc_typeck::check::CheckItemTypesVisitor as rustc_hir::itemlikevisit::ItemLikeVisitor>::visit_item::h979a7c3a154b2bcd
  64:     0x7fff95b23ef9 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  65:     0x7fff95a8de3f - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  66:     0x7fff95b5d56a - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  67:     0x7fff958a937b - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  68:     0x7fff957e38db - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  69:     0x7fff95a5ffc2 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  70:     0x7fff95419389 - <rustc_typeck::bounds::Bounds as core::fmt::Debug>::fmt::h5859ca23977fa056
  71:     0x7fff95445ed7 - rustc_typeck::check_crate::ha5af7191d683cc6d
  72:     0x7fff92e70f2e - rustc_interface::passes::BoxedResolver::to_resolver_outputs::h7a1a389ffa8b4ef1
  73:     0x7fff95b23509 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  74:     0x7fff95a90b76 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  75:     0x7fff95b527c7 - <rustc_query_impl::plumbing::QueryCtxt as rustc_query_system::query::QueryContext>::store_diagnostics_for_anon_node::h5397f0d33c4b219c     
  76:     0x7fff958b5cca - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  77:     0x7fff9581774e - <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_foreign_item::h8a641d9769f09835
  78:     0x7fff95a5bfd2 - <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::try_print_query_stack::hcfeb9e88469194a3
  79:     0x7fff92d89809 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::he9bb74d196e6a2c3
  80:     0x7fff92d36a2b - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::hcb9f176ea80c3032
  81:     0x7fff92d206cc - <rustc_driver::Compilation as core::fmt::Debug>::fmt::h5d81a6d2c7da3faa
  82:     0x7fff92d38637 - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::hcb9f176ea80c3032
  83:     0x7fff92d27de4 - rustc_driver::pretty::print_after_hir_lowering::hfe86111045a339ee
  84:     0x7fff92d39bbf - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::hcb9f176ea80c3032
  85:     0x7fff92d5929d - <rustc_middle::ty::SymbolName as core::fmt::Display>::fmt::hcb9f176ea80c3032
  86:     0x7fffbdf7bc9a - std::sys::windows::thread::Thread::new::h171cad5aadd5b51e
  87:     0x7ffff54e7034 - BaseThreadInitThunk
  88:     0x7ffff6182651 - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0 (88f19c6da 2021-05-03) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::ops::Add`
#1 [typeck] type-checking `main`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by Aaron1011** [comment] 2021-05-08 01:53
See issue https://github.com/rust-lang/rust/issues/84970

**Comment by wesleywiser** [comment] 2021-05-10 14:22
Thanks for filing the bug report! We are currently triaging issues related to #84970 to ensure each underlying problem gets resolved. Since this appears to be a duplicate of #83259 so I'm going to close in favor of that issue.

**Closed by wesleywiser** 2021-05-10 14:22 UTC
Labels: C-bug, I-ICE, T-compiler
