### ISSUE TITLE
Macros are not propagated through `pub extern crate`.

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rust#51530] opened 2018-06-13 05:09 UTC
As of Rust 1.26.2 stable if I define an exported macro in crate `foo` then `pub extern crate foo` in another crate `bar` then consumers of the `bar` crate cannot use the macro in `foo` even if there is a `#[macro_use]` on the `pub extern crate foo` and a `#[macro_use]` on the `extern crate bar` in the consumers code.

I would expect the macros to be propagated similarly to the other items in the `foo` crate.

This can be worked around by having the consumer of `bar` depend on `foo` directly, but that defeats the purpose of the `pub extern crate` imo.

**Comment by Mark-Simulacrum** [comment] 2018-06-13 17:48
cc @jseyfried @petrochenkov

I'm also nominating for compiler team discussion -- this feels like it might be somewhat related to recent movement on the use extern macros feature?

**Comment by nikomatsakis** [comment] 2018-06-21 14:28
This is tagged as a regression, but did this ever work? Maybe my memory is faulty, but I didn't think that `#[macro_use]` worked across crates (no matter the privacy of the extern crate in question).

**Comment by nikomatsakis** [comment] 2018-06-21 14:30
Put another way, the behavior @Xaeroxe describes is the behavior I expect. I think that this was the purpose of `#[macro_reexport]` (https://github.com/rust-lang/rust/issues/29638) which was never stabilized (and indeed was recently removed). We expect `pub use` to eventually play this role, modulo the resolution of the various issues around it.

**Comment by nikomatsakis** [comment] 2018-06-21 14:45
triage: P-high 

Marking as P-high so that we revisit next week. But I'm not convinced this is a bug (as I wrote earlier). 

Thoughts @rust-lang/compiler ?

**Comment by petrochenkov** [comment] 2018-06-21 14:53
Yes, this isn't supposed to work.
`#[macro_use] extern crate ...` adds macros to the prelude, but not reexports them in any way.
As @nikomatsakis said `#[macro_reexport]` was used for reexporting and now it's subsumed by `pub use`.

**Comment by nikomatsakis** [comment] 2018-06-28 14:15
Closing as not a bug, thanks @petrochenkov.

**Closed by nikomatsakis** 2018-06-28 14:15 UTC
Labels: P-high, T-compiler, regression-from-stable-to-stable

**Comment by MightyPork** [comment] 2019-08-26 08:38
I'm currently trying to use this feature and it doesn't work with `pub use`. Is there currently a working mechanism to reexport macros?

My use case is caused by the lack of workspace-wide dependency config in Cargo.toml, so I made a crate "deps" that was meant to reexport dependencies that need special feature flags or versions. It works fine, except for macros.

I tried `pub use`, `pub extern crate`, both with `#[macro_use]` and `#[macro_export]`, and import it with `#[macro_use]`. Nothing got the macro into scope ("cannot find macro `doc!` in this scope")

**Comment by petrochenkov** [comment] 2019-08-26 08:47
@MightyPork 
Could you give some example / reproduction?
`pub use` generally works for macros and is actively used (e.g. for reexporting macros from libcore in libstd).

**Comment by MightyPork** [comment] 2019-08-26 19:56
here is a minimal reproduction (tested with current stable):

[debug-macro-reexport.zip](https://github.com/rust-lang/rust/files/3542704/debug-macro-reexport.zip)

**Comment by petrochenkov** [comment] 2019-08-26 22:55
@MightyPork 
That example is supposed to use `pub use bson::doc;`
