### ISSUE TITLE
Windows refuses install rust

### ISSUE THREAD

**Issue by ayianadarko** [rust-lang/rust#60600] opened 2019-05-07 09:17 UTC
Windows protected your PC
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
App: rustup-init.exe
Publisher: Unknown publisher

**Comment by jonas-schievink** [comment] 2019-05-07 09:31
Duplicate of https://github.com/rust-lang/rustup.rs/issues/1568

**Closed by jonas-schievink** 2019-05-07 09:31 UTC
