### ISSUE TITLE
Why could mutable and immutable reference are simultaneously allowed when passed as arguments.

### ISSUE THREAD

**Issue by eadren** [rust-lang/rust#60232] opened 2019-04-24 09:08 UTC
When reading [the Chapter04-02 references and borrowing of The Rust Programming Language Book](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html), I know that it cannot be allowed to exits mutable reference and immutable reference simultaneously. 

Here is the official demo:

```rust
let mut s = String::from("hello");

let r1 = &s; // no problem
let r2 = &s; // no problem
let r3 = &mut s; // BIG PROBLEM

println!("{}, {}, and {}", r1, r2, r3);
```
Here is error:
```
error[E0502]: cannot borrow `s` as mutable because it is also borrowed as immutable
 --> src/main.rs:6:14
  |
4 |     let r1 = &s; // no problem
  |              -- immutable borrow occurs here
5 |     let r2 = &s; // no problem
6 |     let r3 = &mut s; // BIG PROBLEM
  |              ^^^^^^ mutable borrow occurs here
7 |
8 |     println!("{}, {}, and {}", r1, r2, r3);
  |                                -- immutable borrow later used here
```

But when changing variable to function parameter, ***it is allowed!!!!***

```rust
fn main() {
    let mut s = String::from("demo");

    let len1 = cal_len_immut(&s);
    let len2 = cal_len_mut(&mut s);

}
fn cal_len_immut(s: &String) -> usize {
    s.len()
}

fn cal_len_mut(s: &mut String) -> usize {
    s.push_str(", world!");
    s.len()
}
```
As a result, when in multithreads, it will lead to race condition if the immutable reference passing to cal_len_immut in a read thread, while the mutable reference passing to cal_len_mut in a write thread.

**Comment by vainiovano** [comment] 2019-04-24 09:46
The value can't be used in multiple threads simultaneously because the ownership will be transferred to the first thread.

**Comment by jonas-schievink** [comment] 2019-04-24 09:55
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Closed by jonas-schievink** 2019-04-24 09:55 UTC

**Comment by eadren** [comment] 2019-04-24 10:40
To be more concretely, I want to say a fact(may be a design pitfall for compiler) that when using a mutable borrowed/reference after immutable borrowed/reference, if not using the immutable reference again, the compiler will not show error.

Here is the demo of when executing `rustc --explain E0502`

```rust
This error indicates that you are trying to borrow a variable as mutable when it
has already been borrowed as immutable.

Example of erroneous code:

```
fn bar(x: &mut i32) {}
fn foo(a: &mut i32) {
    let ref y = a; // a is borrowed as immutable.
    bar(a); // error: cannot borrow `*a` as mutable because `a` is also borrowed
            //        as immutable
}
```

To fix this error, ensure that you don't have any other references to the
variable before trying to access it mutably:

```
fn bar(x: &mut i32) {}
fn foo(a: &mut i32) {
    bar(a);
    let ref y = a; // ok!
}

```

**Comment by jonas-schievink** [comment] 2019-04-24 11:03
That's just non-lexical lifetimes working as intended
