### ISSUE TITLE
Investigate making the buildbots network-access-free

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#35002] opened 2016-07-23 22:17 UTC
Currently, the Rust buildbots (bors) all clone LLVM and other libs from Github. This seems to occasionally hang and cause mysterious spurious failures, possibly due to rate-limiting.

It could be better if we would do the `git submodule update` once and push the updated directory to the buildbots. We need to figure out how this interacts with lazy LLVM recompilation, but it should be possible.

cc @rust-lang/tools

**Comment by rkruppe** [comment] 2016-07-24 13:54
This is not only messing with PRs, it also killed the last three nightlies.

**Comment by alexcrichton** [comment] 2016-07-25 04:43
I'd love to do this! I also have no idea how to do this easily though :(

I have no idea why LLVM clones are timing out so much, I sent mail to GitHub but haven't gotten much of a response...

**Comment by arielb1** [comment] 2016-07-25 18:11
You can clone and `git submodule update` on a dedicated machine and push the result directory to the buildbots.

**Comment by alexcrichton** [comment] 2016-12-30 06:04
Buildbots are almost gone now, so closing.

**Comment by arielb1** [comment] 2017-01-04 20:04
Still an issue with travis.

**Comment by alexcrichton** [comment] 2017-03-23 20:12
Fundamentally I believe this is unfortunately just impossible for us. We will always be required to perform network requests on Travis/AppVeyor and I don't see an end in sight to that. 

That being said there are mitigation strategies for problems caused by this:

* Caching - we can leverage Travis/AppVeyor caching where possible as that's typically a more reliable connection
* Retries - we can just retry network requests on error
* Mirror in reliable locations - some servers are unreliable over time but S3 is pretty reliable.

We've implemented a lot of this (mirroring on S3, retrying **everything**, etc), so I'm going to close this. Other general spurious network errors should be tracked at https://github.com/rust-lang/rust/issues/40474 and we can investigate fixing those as they come up.

**Closed by alexcrichton** 2017-03-23 20:12 UTC
Labels: A-spurious
