### ISSUE TITLE
[ER] Missed Vec allocation elision

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#92035] opened 2021-12-17 12:29 UTC
This code compiled in release mode (1.59.0-nightly 5531927e8 2021-12-16):

```rust
#![feature(box_syntax)]

pub fn foo(_n: usize) -> u32 {
    let a =  box [0_u32; 1001];
    a[0]
}
```

Optimizes nicely:
 
```asm
example::foo:
        xor     eax, eax
        ret
```

While similar code with a run-time length vec:

```rust
pub fn foo(n: usize) -> u32 {
    let a = vec![0_u32; n + 1];
    a[0]
}
```

Isn't optimized well enough:

```asm
core::ptr::drop_in_place<alloc::vec::Vec<u32>>:
        mov     rsi, qword ptr [rdi + 8]
        test    rsi, rsi
        je      .LBB0_2
        shl     rsi, 2
        test    rsi, rsi
        je      .LBB0_2
        mov     rdi, qword ptr [rdi]
        mov     edx, 4
        jmp     qword ptr [rip + __rust_dealloc@GOTPCREL]
.LBB0_2:
        ret

example::foo:
        push    r15
        push    r14
        push    rbx
        sub     rsp, 32
        mov     r15, rdi
        add     r15, 1
        mov     ecx, 4
        xor     ebx, ebx
        mov     rax, r15
        mul     rcx
        mov     r14, rax
        setno   al
        jo      .LBB1_12
        mov     bl, al
        shl     rbx, 2
        test    r14, r14
        je      .LBB1_2
        mov     rdi, r14
        mov     rsi, rbx
        call    qword ptr [rip + __rust_alloc_zeroed@GOTPCREL]
        test    rax, rax
        je      .LBB1_13
.LBB1_5:
        mov     rcx, r14
        shr     rcx, 2
        mov     qword ptr [rsp + 8], rax
        mov     qword ptr [rsp + 16], rcx
        mov     qword ptr [rsp + 24], r15
        test    r15, r15
        je      .LBB1_6
        mov     ebx, dword ptr [rax]
        test    r14, r14
        je      .LBB1_10
        mov     edx, 4
        mov     rdi, rax
        mov     rsi, r14
        call    qword ptr [rip + __rust_dealloc@GOTPCREL]
.LBB1_10:
        mov     eax, ebx
        add     rsp, 32
        pop     rbx
        pop     r14
        pop     r15
        ret
.LBB1_2:
        mov     rax, rbx
        test    rax, rax
        jne     .LBB1_5
.LBB1_13:
        mov     rdi, r14
        mov     rsi, rbx
        call    qword ptr [rip + alloc::alloc::handle_alloc_error@GOTPCREL]
        ud2
.LBB1_6:
        lea     rdx, [rip + .L__unnamed_1]
        xor     edi, edi
        xor     esi, esi
        call    qword ptr [rip + core::panicking::panic_bounds_check@GOTPCREL]
        ud2
.LBB1_12:
        call    qword ptr [rip + alloc::raw_vec::capacity_overflow@GOTPCREL]
        ud2
        mov     rbx, rax
        lea     rdi, [rsp + 8]
        call    core::ptr::drop_in_place<alloc::vec::Vec<u32>>
        mov     rdi, rbx
        call    _Unwind_Resume@PLT
        ud2

.L__unnamed_2:
        .ascii  "/app/example.rs"

.L__unnamed_1:
        .quad   .L__unnamed_2
        .asciz  "\017\000\000\000\000\000\000\000\003\000\000\000\005\000\000"

DW.ref.rust_eh_personality:
        .quad   rust_eh_personality
```

**Comment by mlodato517** [comment] 2021-12-17 16:34
I know nothing of this space so feel free to ignore this but is it possible that `n + 1` wraps around to zero and then `a[0]` panics? And is it also possible that [`n + 1 > isize::MAX` and so causes a failure](https://doc.rust-lang.org/nomicon/vec/vec-alloc.html) to allocate?

**Comment by leonardo-m** [comment] 2021-12-17 18:39
You're right that my problem wasn't minimal, so I've tried to replace the vec![0_u32; n + 1] with vec![0_u32; n] and the problem is unchanged.

**Comment by leonardo-m** [comment] 2021-12-17 18:44
This should be simpler to optimize:

```rust
pub fn foo(n: usize) -> u32 {
    if n > 0 && n < 1001 {
        let a = vec![0_u32; n];
        a[0]
    } else {
        0
    }
}
```

Gives:

```asm
example::foo:
        push    rbp
        push    rbx
        push    rax
        lea     rax, [rdi - 1]
        xor     ebp, ebp
        cmp     rax, 999
        ja      .LBB0_3
        mov     rbx, rdi
        shl     rbx, 2
        mov     esi, 4
        mov     rdi, rbx
        call    qword ptr [rip + __rust_alloc_zeroed@GOTPCREL]
        test    rax, rax
        je      .LBB0_4
        mov     ebp, dword ptr [rax]
        mov     edx, 4
        mov     rdi, rax
        mov     rsi, rbx
        call    qword ptr [rip + __rust_dealloc@GOTPCREL]
.LBB0_3:
        mov     eax, ebp
        add     rsp, 8
        pop     rbx
        pop     rbp
        ret
.LBB0_4:
        mov     esi, 4
        mov     rdi, rbx
        call    qword ptr [rip + alloc::alloc::handle_alloc_error@GOTPCREL]
        ud2
```

**Comment by mlodato517** [comment] 2021-12-17 19:04
Ah thank you for the updated example! If I try [this in the playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=df533bfa9ca3120ead4e98cb277d61df):

```rust
#![feature(box_syntax)]

fn main() {
    let a =  box [0_u32; u32::MAX as usize];
    println!("{}", a[0]);
}
```
 it fails to allocate:
```
memory allocation of 17179869180 bytes failed
```

However if I try [this in the playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=0166d2b3b1d8f68f249777a0d7d62b83):

```rust
#![feature(box_syntax)]

pub fn foo() -> u32 {
    let a =  box [0_u32; u32::MAX as usize];
    a[0]
}

fn main() {
    println!("{}", foo());
}
```
it succeeds (presumably because it optimized away the actual allocation).

I don't know much about the Rust compiler and if/when it's valid to not allocate so I will leave this up to someone more knowledgeable!

**Comment by leonardo-m** [comment] 2021-12-17 19:22
As far as I know, in Rust it's OK to optimize away an useless memory allocation. This means a memory overflow error isn't deterministic, it happen on the base of how much memory you have and other details of the physical machine.

**Comment by nikic** [comment] 2021-12-17 19:35
Duplicate of #90032.

**Closed by nikic** 2021-12-17 19:35 UTC
