### ISSUE TITLE
rustdoc: Provide information on Send/Sync/Sized, variance, pointer indirection, ...

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#41537] opened 2017-04-25 15:40 UTC
There are some properties of types that are part of the "publicly visible interface" in the sense that they can be observed by other crates using these types, but they are not shown by rustdoc and usually can only be figured out by hunting through the implementation source code (potentially through many layers).

This is includes the information of when the type satisfies `Send` or `Sync` ("when" in the sense of "which bounds are needed on `T` to make `Foo<T>` be `Send`), when it is sized, what is the variance of lifetime and/or type parameters, and whether type parameters are occurring exclusively below a pointer indirection. (The latter is relevant to know whether `struct Foo { f: T<Foo> }` is legal.)

I recently hit this when I wanted to figure out when exactly `MutexGuard`, `RwLockReadGuard` and `RwLockWriteGuard` are `Send` or `Sync` -- I started chasing the source code, but actually it turns out to be much easier to "probe" these types by writing little programs that test whether the bounds are satisfied. Needless to say, that's not great. Ideally, rustdoc should present this information somewhere.

**Comment by QuietMisdreavus** [comment] 2017-04-25 18:40
Possibly a duplicate of #33772?

**Comment by ollie27** [comment] 2017-04-25 19:46
I'd say this is a dupe of #17606.

**Comment by Mark-Simulacrum** [comment] 2017-04-25 20:59
Closing in favor of #17606. #33772 is similar (and perhaps a duplicate of #17606), but I think that #17606 is closer to what this specific issue is asking for.

**Closed by Mark-Simulacrum** 2017-04-25 20:59 UTC

**Comment by SOF3** [comment] 2023-10-15 12:33
It seems the mentioned issues only track marker traits. Is the "variance" part duplicated anywhere or shall I create a new issue?

**Comment by RalfJung** [comment] 2023-10-15 14:10
I'm not aware of one, so feel free to open one. :)
