### ISSUE TITLE
[rustc] Can't compile aurelius

### ISSUE THREAD

**Issue by Kaegell** [rust-lang/rust#32728] opened 2016-04-04 14:36 UTC
Hello, everyone.

So, I wanred to install the neovim-plugin "Vim-Markdown-Composer", but the installation process stopped unexpetedly. Then I tried to run the command :
>cargo build --release --verbose
And this was the output :

  Compiling aurelius v0.1.8
     Running `rustc /home/kaegell/.cargo/registry/src/github.com-88ac128001ac3a9a/aurelius-0.1.8/src/lib.rs --crate-name aurelius --crate-type lib -C opt-level=3 -C metadata=746275a8cd0bc1b5 -C extra-filename=-746275a8cd0bc1b5 --out-dir /home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps --emit=dep-info,link -L dependency=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps -L dependency=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps --extern hoedown=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libhoedown-61a36a6d94b45d2d.rlib --extern url=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/liburl-f4663200346a2ff2.rlib --extern chan=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libchan-a6b72f7762033ebd.rlib --extern log=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/liblog-30192c322738a5ea.rlib --extern porthole=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libporthole-7b53c893e5ad8313.rlib --extern nickel=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libnickel-59388253e7765304.rlib --extern websocket=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libwebsocket-5b822b5557dc6ec6.rlib --cap-lints allow -L native=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/build/hoedown-1430ba668b5e5841/out -L native=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/build/openssl-e24763c245f66d1b/out -L native=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/build/openssl-sys-extras-068ec43a65a823e4/out -L native=/usr/lib`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'assertion failed: declare::get_defined_value(ccx, &symbol).is_none()', ../src/librustc_trans/monomorphize.rs:94
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `aurelius`.

Caused by:
  Process didn't exit successfully: `rustc /home/kaegell/.cargo/registry/src/github.com-88ac128001ac3a9a/aurelius-0.1.8/src/lib.rs --crate-name aurelius --crate-type lib -C opt-level=3 -C metadata=746275a8cd0bc1b5 -C extra-filename=-746275a8cd0bc1b5 --out-dir /home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps --emit=dep-info,link -L dependency=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps -L dependency=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps --extern hoedown=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libhoedown-61a36a6d94b45d2d.rlib --extern url=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/liburl-f4663200346a2ff2.rlib --extern chan=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libchan-a6b72f7762033ebd.rlib --extern log=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/liblog-30192c322738a5ea.rlib --extern porthole=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libporthole-7b53c893e5ad8313.rlib --extern nickel=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libnickel-59388253e7765304.rlib --extern websocket=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/deps/libwebsocket-5b822b5557dc6ec6.rlib --cap-lints allow -L native=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/build/hoedown-1430ba668b5e5841/out -L native=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/build/openssl-e24763c245f66d1b/out -L native=/home/kaegell/.config/nvim/plugged/vim-markdown-composer/target/release/build/openssl-sys-extras-068ec43a65a823e4/out -L native=/usr/lib` (exit code: 101)

Does anyone has similar issues with this package? What do you think could be a good solution, or at least a workaround? I tried reinstalling rust via rustup, and it did nothing.

**Comment by dotdash** [comment] 2016-04-04 14:40
Dupe of #32530 which has been fixed recently. Should be fixed in the next nightly.

**Closed by dotdash** 2016-04-04 14:40 UTC
