### ISSUE TITLE
Panic with -v or --verbose without additional params.

### ISSUE THREAD

**Issue by dmilith** [rust-lang/rust#35544] opened 2016-08-09 07:21 UTC
FreeBSD 11.0, x86_64, Rust 1.10.0, Cargo 0.11.0 sha, It's release, so stack is useless.. but still:

```
[1470727096] bh:~/.sofin/git-cache/cargo-1.x-master.git λ RUST_BACKTRACE=1 rustc -v
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:785
stack backtrace:
   1:        0x801de9ac5 - <unknown>
   2:        0x801dfe9a7 - <unknown>
   3:        0x801dfe514 - <unknown>
   4:        0x801db1666 - <unknown>
   5:        0x801dfef89 - <unknown>
   6:        0x801db3fcf - <unknown>
   7:        0x801dfec11 - <unknown>
   8:        0x801e432ac - <unknown>
   9:        0x8062ca94a - <unknown>
  10:        0x8066007b5 - <unknown>
  11:        0x8065f9071 - <unknown>
  12:        0x8065f7b64 - <unknown>
  13:        0x80162a5a3 - <unknown>
  14:        0x80162c710 - <unknown>
  15:        0x80163e038 - <unknown>
  16:        0x801e100f3 - <unknown>
  17:        0x80163ec88 - <unknown>
  18:        0x801dfc8a5 - <unknown>
  19:        0x8074ecae4 - <unknown>

zsh: exit 101   RUST_BACKTRACE=1 rustc -v
```

**Comment by Mark-Simulacrum** [comment] 2017-05-10 22:03
I cannot reproduce locally, closing. Please let us know if you can still reproduce, preferably on nightly so we can get a better stacktrace.

**Closed by Mark-Simulacrum** 2017-05-10 22:03 UTC
