### ISSUE TITLE
confusing error message in for-loop with duplicate `in`

### ISSUE THREAD

**Issue by Emerentius** [rust-lang/rust#52964] opened 2018-08-01 22:54 UTC
When accidentally writing `for x in in iter` with a duplicate `in`, the error message will point to the first thing beneath the loop body with a confusing error message.

Example:
```rust
fn main() {
    let i = ();
    for x in in 0..1 {}
    i;
}
```
results in
```
error: expected one of `{` or an operator, found `i`
 --> src/main.rs:4:5
  |
3 |     for x in in 0..1 {}
  |                         - expected one of `{` or an operator here
4 |     i;
  |     ^ unexpected token
```

This is probably because `in 0..1 {}` is parsed as the old emplacement syntax (`in PLACE { BLOCK }`). And because the block has been parsed as part of the emplacement, the loop is seen as having no block.

When another block is added (`for x in in 0..1 {} {}`), the error message tells us that this emplacement syntax is obsolete.

**Comment by estebank** [comment] 2018-09-19 23:17
Duplicate of https://github.com/rust-lang/rust/issues/36611

**Closed by estebank** 2018-09-19 23:17 UTC
Labels: A-diagnostics
