### ISSUE TITLE
[rustbuild] --target without --host runs no host tests

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#39194] opened 2017-01-19 23:04 UTC
Running UI tests seems to not be working for some reason?

```
$ python x.py test src/test/ui/ --stage=1 --target=x86_64-unknown-linux-gnu --verbose
    Finished debug [unoptimized] target(s) in 0.0 secs
finding compilers
CC_x86_64-unknown-linux-gnu = "clang"
AR_x86_64-unknown-linux-gnu = "ar"
CXX_x86_64-unknown-linux-gnu = "clang++"
running sanity check
collecting channel variables
updating submodules
running: "git" "submodule" "sync"
Synchronizing submodule url for 'src/compiler-rt'
Synchronizing submodule url for 'src/jemalloc'
Synchronizing submodule url for 'src/liblibc'
Synchronizing submodule url for 'src/llvm'
Synchronizing submodule url for 'src/rt/hoedown'
Synchronizing submodule url for 'src/rust-installer'
running: "git" "reset" "--hard"
HEAD is now at a8fc4c16 Merge pull request #28 from xen0n/preprocessor-firefighting
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at e058ca6 Change how the default zone is found
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at 7d57bdcdb Auto merge of #484 - eddyb:dox-unops, r=alexcrichton
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at ceb177eeefa Merge pull request #60 from japaric/gh38406
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at a3736a0 Merge pull request #6 from intelfx/patch-1
running: "git" "clean" "-fdx"
running: "git" "reset" "--hard"
HEAD is now at 4f99485 Merge pull request #54 from brson/docdir
running: "git" "clean" "-fdx"
learning about cargo
bootstrap top targets:
bootstrap build plan:
Build completed in 0:00:01
```

**Comment by alexcrichton** [comment] 2017-01-19 23:20
Have you tried not passing `--target` or passing `--host` instead?

**Comment by nagisa** [comment] 2017-01-19 23:26
I have to pass `--target` because my `config.toml` contains just about every possible target by now and `host` doesn’t quite have the intended behaviour most of the time. Leaving out `--target` will start buildng every target specified in that list and not having targets in the config.toml makes it pretty obnoxious to deal with stuff when I need different targets.

So no, I do not think either of those are an option.

**Comment by TimNN** [comment] 2017-01-20 14:38
From a quick look at the rustbuild sources, the problem *may* be the trailing slash in `src/test/ui/`, see

* https://github.com/rust-lang/rust/blob/master/src/bootstrap/step.rs#L365
* https://github.com/rust-lang/rust/blob/master/src/bootstrap/step.rs#L945-L948
* https://github.com/rust-lang/rust/blob/master/src/bootstrap/flags.rs#L211-L213

**Comment by nagisa** [comment] 2017-01-20 16:17
pretty sure it didn't work without a slash or with test subdirectory like
src/test/ui/test-dir

**Comment by TimNN** [comment] 2017-01-20 16:49
Alright, I tried it and it seems to work if you specify both `--host` and `--target`, due to [this snippet](https://github.com/rust-lang/rust/blob/master/src/bootstrap/step.rs#L967-L982) from rustbuild, to quote a comment:

> **If `--target` was specified but `--host` wasn't specified, don't run any host-only tests** 

(`check-ui` is host-only as far as I can tell).

**Comment by nagisa** [comment] 2017-01-20 18:10
@TimNN does it work if `target` and `host` are different? For example `--target=i686-unknown-linux-gnu --host=x86_64-unknown-linux-gnu`?

**Comment by TimNN** [comment] 2017-01-20 19:15
`../rust-src/x.py test src/test/ui --stage=1 --target=i686-unknown-linux-gnu --host=x86_64-unknown-linux-gnu` builds / tests something, however it doesn't pick up the correct target (which isn't that surprising I guess, since the test is marked as host-only, I think):

```
target: x86_64-unknown-linux-gnu
host: x86_64-unknown-linux-gnu
```

And one test fails (`ui/custom-derive/issue-36935.rs`):

```
/home/logic/build-tmp/rust-build/build/x86_64-unknown-linux-gnu/stage1/bin/rustc: symbol lookup error: /home/logic/build-tmp/rust-build/build/x86_64-unknown-linux-gnu/test/ui/custom-derive/issue-36935.stage1-x86_64-unknown-linux-gnu.ui.libaux/libplugin.so: undefined symbol: _ZN3std9panicking20rust_panic_with_hook17h41032d5e499b5299E
```

**Comment by alexcrichton** [comment] 2017-01-20 22:15
Yes I believe the filtering logic pointed out by @TimNN is the cause for this. I believe the error @TimNN saw may be a missing dependency edge in the test suite.

You should be able to pass `--host` and `--target` and have it work as expected, even if they're different. (that's the intention at least)

**Comment by Mark-Simulacrum** [comment] 2019-08-19 23:16
I think this is basically works as intended currently (even if I personally think it's a bit gnarly, this is basically the behavior we're ~stuck with).

**Closed by Mark-Simulacrum** 2019-08-19 23:16 UTC
Labels: A-rustbuild, C-bug, I-needs-decision
