### ISSUE TITLE
std::boxed::Box documentation source link broken

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#20229] opened 2014-12-25 21:11 UTC
Clicking [src] on http://doc.rust-lang.org/std/boxed/struct.Box.html will redirect to http://doc.rust-lang.org/alloc/boxed/undefined which is 404.

**Comment by tomjakubowski** [comment] 2015-02-10 13:26
This is a dupe of #15309

**Closed** 2015-02-10 13:30 UTC
Labels: A-rustdoc
