### ISSUE TITLE
Spurious CI failures on x86_64-msvc-ext: "failed to remove file `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe`"

### ISSUE THREAD

**Issue by GrigorenkoPV** [rust-lang/rust#128291] opened 2024-07-27 23:27 UTC
Some examples:
- https://github.com/rust-lang/rust/pull/128246#issuecomment-2253659715
- https://github.com/rust-lang/rust/pull/128270#issuecomment-2254265585
- I think I've seen more

@rustbot label A-ci O-windows

**Comment by ehuss** [comment] 2024-07-27 23:43
Thanks for the report! Closing as a duplicate of #127883.

**Closed by ehuss** 2024-07-27 23:43 UTC
Labels: O-windows, needs-triage, A-ci
