### ISSUE TITLE
Unexpected region for local data ReStatic

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#49579] opened 2018-04-02 05:59 UTC
```
#![feature(nll)]

fn fibs(n: u32) -> impl Iterator<Item=u128> {
    (0 .. n)
    .scan((0, 1), |st, _| {
        *st = (st.1, st.0 + st.1);
        Some(*st)
    })
    .map(&|(f, _)| f)
}

fn main() {
    println!("{:?}", fibs(10).collect::<Vec<_>>());
}
```

```
error: internal compiler error: unexpected region for local data ReStatic
 --> ...\test.rs:9:11
  |
9 |     .map(&|(f, _)| f)
  |           ^^^^^^^^^^

error: aborting due to previous error
```

```
rustc 1.26.0-nightly (06fa27d7c 2018-04-01)
binary: rustc
commit-hash: 06fa27d7c84a21af8449e06f3c50b243c4d5a7ad
commit-date: 2018-04-01
host: x86_64-pc-windows-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

**Comment by nikomatsakis** [comment] 2018-07-03 19:19
Still an ICE. Adding as Preview 2 but I'm not sure the cause yet.

**Comment by nikomatsakis** [comment] 2018-07-17 12:08
I see, I see. Yes, that is expected to be exposed to the user.

**Comment by nikomatsakis** [comment] 2018-07-17 12:09
I guess we can close this then as Working as Expected. Nice job @spastorino, you get the credit for fixing this one :)

**Comment by nikomatsakis** [comment] 2018-07-17 12:09
Er, I'll leave open because (as @matthewjasper noted) we still need a test

**Closed** 2018-08-01 22:06 UTC
Labels: A-NLL, E-needstest, NLL-complete, T-lang, WG-compiler-nll
