### ISSUE TITLE
host rustdocs for librustc and so forth on forge

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#42359] opened 2017-06-01 20:28 UTC
It would be great to have the rustdocs for the compiler's crates hosted on `forge` to help with onboarding new contributors.

**Comment by mgattozzi** [comment] 2017-06-01 20:30
As I mentioned before I have a branch [here](https://github.com/mgattozzi/rust-forge/tree/compiler-docs) that works and it's just a matter of tweaking travis to have the right tools to actually be able to build the compiler so it can make the docs. It should work after that's done. Then we can setup a cron job or something to run the master branch daily to update the docs.

**Comment by est31** [comment] 2017-06-01 20:48
cc @Manishearth

**Comment by steveklabnik** [comment] 2017-06-01 22:11
This is a duplicate of https://github.com/rust-lang/rust/issues/29893

**Closed by steveklabnik** 2017-06-01 22:11 UTC
Labels: T-compiler, T-infra
