### ISSUE TITLE
make install doesn't install target's rustlibs

### ISSUE THREAD

**Issue by sezaru** [rust-lang/rust#40416] opened 2017-03-10 14:12 UTC
When compiling rust with targets for both `x86_64-unknown-linux-gnu` and `i686-unknown-linux-gnu`, both `rustlibs` will be compiled and stored inside `stage2-std`, but only `x86_64` ones will be installed when issuing the `make install` command.

Here are the steps I'm doing:
```
./configure --prefix="$(pwd)/image/usr" \
            --libdir="$(pwd)/image/usr/lib64/rust-1.15.1" \
            --mandir="$(pwd)/image/usr/share/rust-1.15.1/man" \
            --release-channel=stable \
            --disable-manage-submodules \
            --default-linker=x86_64-pc-linux-gnu-gcc \
            --default-ar=x86_64-pc-linux-gnu-ar \
            --python=python2.7 \
            --disable-rpath \
            --enable-local-rust \
            --local-rust-root="../stage0" \
            --target=x86_64-unknown-linux-gnu,i686-unknown-linux-gnu \
            --enable-clang \
            --enable-optimize \
            --enable-optimize-cxx \
            --enable-optimize-llvm \
            --enable-optimize-tests \
            --enable-libcpp \
            --llvm-root=/usr \
            --enable-llvm-link-shared
make dist
make install
```

Note the `--target=x86_64-unknown-linux-gnu,i686-unknown-linux-gnu` on the `configure` command.

Here is the `stage2-std` `rustlib` directory:

```
$ ls ./build/tmp/dist/rust-std-1.15.1-i686-unknown-linux-gnu/rust-std-i686-unknown-linux-gnu/lib/rustlib
    i686-unknown-linux-gnu

$ ls ./build/x86_64-unknown-linux-gnu/stage2-std
    i686-unknown-linux-gnu
    release
    x86_64-unknown-linux-gnu
```

Here is the `rustlibs` directory after `make install`

```
$ ls ./image/usr/lib64/rust-1.15.1/rustlib/
    components
    manifest-rustc
    rust-installer-version
    etc
    manifest-rust-docs
    uninstall.sh
    install.log
    manifest-rust-std-x86_64-unknown-linux-gnu
    x86_64-unknown-linux-gnu
```

**Comment by alexcrichton** [comment] 2017-03-10 19:13
I believe this is a dupe of https://github.com/rust-lang/rust/issues/39235 but thanks for the report!

**Closed by alexcrichton** 2017-03-10 19:13 UTC
