### ISSUE TITLE
rustc crash compiling version-check

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#49136] opened 2018-03-18 13:35 UTC
Something similar happened before, but succeeded at the next attempt. This one seems to be reproducable though.

Running this on a Raspberry Pi Zero W:

```
  ...
   Compiling version_check v0.1.3
thread 'rustc' panicked at 'index out of bounds: the len is 4845282 but the index is 4845282', /checkout/src/libserialize/opaque.rs:259:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (adf2135ad 2018-03-17) running on arm-unknown-linux-gnueabihf

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `version_check`.

```

**Comment by kennytm** [comment] 2018-03-18 13:37
Hi, thanks for the report! This is a duplicate of #49113, so I'm closing this one.

**Closed by kennytm** 2018-03-18 13:37 UTC
