### ISSUE TITLE
ICE on nightly with associated constants

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/rust#54814] opened 2018-10-04 13:39 UTC
I've got an array defined as:-
```
impl<'a> GenerateFunctionBody<'a>
{
const Size: usize = 256;
const Array: [u8; Self::Size] =
[
...
];
}

This definition causes the ICE below. Replacing `Self::Size` with `256` causes the ICE to go away. Because this array is a very large constant, I've defined it in a separate file which is `include!("GenerateFunctionBody.constants.rs"); from a file which also contains a `impl<'a> GenerateFunctionBody<'a>` block. Rust is edition 2015.

```

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(NodeId(4154))`,
 right: `None`: free_scope: DefId(0/0:177 ~ REDACTED[8e96]::REDACTED2[0]::{{impl}}[21]) not recognized by the region scope tree for None / Some(DefId(0/0:184 ~ REDACTED[8e96]::REDACTED2[0]::{{impl}}[21]::FirstUtf8ByteValidationStateTable[0]))', librustc/middle/region.rs:678:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: std::panicking::begin_panic_fmt
   8: rustc::middle::region::ScopeTree::early_free_scope
   9: rustc::middle::free_region::RegionRelations::is_subregion_of
  10: rustc::infer::lexical_region_resolve::resolve
  11: rustc::infer::InferCtxt::resolve_regions_and_report_errors
  12: rustc_typeck::check::regionck::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::regionck_expr
  13: rustc::ty::context::tls::with_related_context
  14: rustc::infer::InferCtxtBuilder::enter
  15: rustc_typeck::check::typeck_tables_of
  16: rustc::ty::query::__query_compute::typeck_tables_of
  17: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::typeck_tables_of<'tcx>>::compute
  18: rustc::ty::context::tls::with_context
  19: rustc::dep_graph::graph::DepGraph::with_task_impl
  20: rustc::ty::context::tls::with_related_context
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  22: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  23: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::typeck_tables_of
  24: rustc_mir::const_eval::const_eval_provider
  25: rustc::ty::query::__query_compute::const_eval
  26: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_eval<'tcx>>::compute
  27: rustc::ty::context::tls::with_context
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::context::tls::with_related_context
  30: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  31: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  32: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_const
  33: rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::TyS<'tcx>>::super_fold_with
  34: <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
  35: rustc::infer::InferCtxt::partially_normalize_associated_types_in
  36: rustc::ty::context::tls::with_context::{{closure}}
  37: rustc::ty::context::GlobalCtxt::enter_local
  38: rustc_typeck::check::wfcheck::check_associated_item
  39: rustc_typeck::check::wfcheck::check_impl_item
  40: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::check_impl_item_well_formed<'tcx>>::compute
  41: rustc::ty::context::tls::with_context
  42: rustc::dep_graph::graph::DepGraph::with_task_impl
  43: rustc::ty::context::tls::with_related_context
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  45: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  46: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  47: rustc::session::Session::track_errors
  48: rustc_typeck::check_crate
  49: rustc::ty::context::tls::enter_context
  50: <std::thread::local::LocalKey<T>>::with
  51: rustc::ty::context::TyCtxt::create_and_enter
  52: rustc_driver::driver::compile_input
  53: rustc_driver::run_compiler_with_pool
  54: rustc_driver::driver::spawn_thread_pool
  55: rustc_driver::run_compiler
  56: syntax::with_globals
  57: __rust_maybe_catch_panic
  58: rustc_driver::run
  59: rustc_driver::main
  60: std::rt::lang_start::{{closure}}
  61: std::panicking::try::do_call
  62: __rust_maybe_catch_panic
  63: std::rt::lang_start_internal
  64: main
query stack during panic:
#0 [typeck_tables_of] processing `REDACTED2::GenerateFunctionBody::FirstUtf8ByteValidationStateTable::{{constant}}`
#1 [const_eval] const-evaluating `REDACTED2::GenerateFunctionBody::FirstUtf8ByteValidationStateTable::{{constant}}`
#2 [check_impl_item_well_formed] processing `REDACTED2::GenerateFunctionBody::FirstUtf8ByteValidationStateTable`
end of query stack
error: aborting due to 2 previous errors

Some errors occurred: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (5597ee8a6 2018-10-03) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `mqtt-topic-filtering`.

Caused by:
  process didn't exit successfully: `rustc --crate-name REDACTED REDACTED/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata -C debuginfo=2 -C metadata=51725fafe02a691a -C extra-filename=-51725fafe02a691a REDACTED` (exit code: 101)

Process finished with exit code 101
```

**Comment by oli-obk** [comment] 2019-01-28 13:42
Note that this only occurs if the struct has lifetimes: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=52955da75939853f8c56fefb16cbb2b1

**Comment by oli-obk** [comment] 2019-01-28 13:43
Duplicate of #54038

**Closed by oli-obk** 2019-01-28 13:43 UTC
Labels: A-associated-items, A-const-eval, I-ICE
