### ISSUE TITLE
Requires `Copy` constraint on parametrized struct that is already known to #[derive(Copy)]

### ISSUE THREAD

**Issue by marcianx** [rust-lang/rust#32872] opened 2016-04-11 02:10 UTC
``` rust
pub trait MetaAssocTypes {
    type AssocType;
}

#[derive(Clone, Copy)]
struct IterBase<'a, Meta: MetaAssocTypes>
    where Meta::AssocType: 'a
{
    val: &'a Meta::AssocType
}

#[derive(Clone, Copy)]
pub struct FwdIter<'a, Meta: MetaAssocTypes>
    where Meta::AssocType: 'a
{
    iter: IterBase<'a, Meta>
}

fn main() {}
```

[Playground](https://play.rust-lang.org/?gist=db40b6463d50c5fbc1d9ca127bc4679f&version=nightly&backtrace=0)

Private struct `IterBase` is known to implement `Copy` for all types it supports. However, `#[derive(Copy)]` for public struct `FwdIter` (which simply wraps `IterBase`) gives the following error:

```
<anon>:12:17: 12:21 error: the trait `Copy` may not be implemented for this type; field `iter` does not implement `Copy` [E0204]
<anon>:12 #[derive(Clone, Copy)]
                          ^~~~
<anon>:12:17: 12:21 note: in this expansion of #[derive_Copy] (defined in <anon>)
<anon>:12:17: 12:21 help: see the detailed explanation for E0204
error: aborting due to previous error
playpen: application terminated with error code 101
```

One workaround is to make `IterBase` public and explicitly add `IterBase<'a, Meta>: Copy` to the `where` clause of `FwdIter` (and all its `impl`s).

**Comment by Aatch** [comment] 2016-04-11 02:51
This is a limitation of derive, you can just do `impl Copy for FwdIter` (with the appropriate type params added) instead.

**Comment by marcianx** [comment] 2016-04-11 03:25
I just tried that:
```
impl<'a, Meta: MetaAssocTypes> Copy for FwdIter<'a, Meta>
    where Meta::AssocType: 'a {}
```
but I received the same error on this impl line.

**Comment by Aatch** [comment] 2016-04-11 03:33
Ah, right, that's because the same limitation affects `IterBase`, it's requiring that `Meta` be `Copy` too.

**Comment by bluss** [comment] 2016-04-11 07:38
And both Copy and Clone need manual implementations here. (Clone can reuse Copy though).

**Comment by marcianx** [comment] 2016-04-12 00:41
It's strange that `IterBase` requires `Meta` to be copy as `IterBase` it only contains a shared reference.

But sure enough, as it says https://doc.rust-lang.org/std/marker/trait.Copy.html

> There is a small difference between the two: the derive strategy will also place a Copy bound on type parameters, which isn't always desired.

Thanks for the clarification.

**Comment by huonw** [comment] 2016-04-12 00:57
Duplicate of https://github.com/rust-lang/rust/issues/26925, thanks for filing!

**Comment by marcianx** [comment] 2016-04-12 01:03
@huonw My last message is related to the bug you marked this as a dupe of. But isn't the original bug reported here different? The error says

```
`Copy` may not be implemented for this type; field `iter` does not implement `Copy`
```

But it is implement right above it in my example up top. So some information is not being propagated correctly.

**Comment by huonw** [comment] 2016-04-21 02:12
@marcianx, oh, sorry, you are correct that this seems different!

**Comment by Mark-Simulacrum** [comment] 2017-05-03 17:53
So looking at the expanded code, it looks like the problem is with the impl of Copy for `FwdIter`. The current implementation only requires that `Meta: Copy`, but that doesn't mean that `Meta::AssocType: Copy`, which leads to this error. I think this is a bug in the derive code, but I'm not sure it's all that easy to fix--if even possible--because in order to know whether `Meta::AssocType: Copy` is required, you need to inspect the `IterBase` type to see if it uses `AssocType` as a field, which I don't think is possible.

I'm thinking we should close this as not really possible to fix, but since I'm uncertain, I'll leave open for the time being. Perhaps someone more familiar with this code could comment? Otherwise, I'll close in a week or two.

```rust
// current impl
impl<'a, Meta: Copy + MyTrait> Copy for FwdIter<'a, Meta>
    where Meta::AssocType: 'a { }

// required impl
impl<'a, Meta: Copy + MyTrait> Copy for FwdIter<'a, Meta>
    where Meta::AssocType: Copy + 'a { }
```

**Comment by Mark-Simulacrum** [comment] 2017-05-07 13:55
Closing in favor of #26925.

**Closed by Mark-Simulacrum** 2017-05-07 13:55 UTC
