### ISSUE TITLE
regression: panic in a function that should not panic

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128900] opened 2024-08-09 17:32 UTC
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/klimoza.lab3-klimoza-hex-game/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/outfoxxed.mock-gl/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/qir-alliance.qir-runner/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/ic-wasi-polyfill-0.4.1/log.txt

```
[INFO] [stderr] thread 'tests::test_default' panicked at library/core/src/panicking.rs:221:5:
[INFO] [stderr] panic in a function that cannot unwind
[INFO] [stderr] stack backtrace:
```

**Comment by compiler-errors** [comment] 2024-08-09 18:18
This is due to changes falling out of the stabilization of the C-unwind ABI #116088 cc @nbdd0121 @Amanieu @RalfJung

**Comment by nbdd0121** [comment] 2024-08-09 18:40
All of them seem to be not using -unwind ABIs when unwinding across FFI and the breakage is intended.

> * https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/klimoza.lab3-klimoza-hex-game/log.txt

trying to unwind past `extern "C"` in near_sdk 4.0.0 (not latest version)

>  * https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/outfoxxed.mock-gl/log.txt

trying to unwind past `extern "system"` in the crate itself: https://github.com/outfoxxed/mock-gl/blob/5fd7c575162dd5edd43470482529c320a440eaeb/src/function_mapping.rs#L34.

> * https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/qir-alliance.qir-runner/log.txt

trying to unwind past `extern "C"` function in the crate itself: https://github.com/qir-alliance/qir-runner/blob/7b41f9313609f8309317ce91afccf0a2c7fe5a6f/stdlib/src/lib.rs#L83.

> * https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/ic-wasi-polyfill-0.4.1/log.txt

trying to unwind past `extern "C"` function in the crate itself: https://github.com/wasm-forge/ic-wasi-polyfill/blob/0e0858cb2c3dd89b586527f9271cdd338022d814/src/lib.rs#L1048

**Comment by apiraino** [comment] 2024-10-07 14:28
I think I can close this as the regressions were accepted

**Closed by apiraino** 2024-10-07 14:28 UTC
Labels: T-compiler, regression-from-stable-to-beta, I-prioritize
