### ISSUE TITLE
Compiling xcb: internal compiler error: anonymous bound region BrAnon(0) in return but not args

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/rust#43734] opened 2017-08-08 09:18 UTC
Trying to compile xcb (dependency of [unixbar](https://github.com/myfreeweb/unixbar)), with `cargo build` inside the unixbar directory.

```
   Compiling xcb v0.7.6
error: internal compiler error: /checkout/src/librustc_typeck/astconv.rs:1267: anonymous bound region BrAnon(0) in return but not args
    --> /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.7.6/src/ffi/xproto.rs:5654:16
     |
5654 |             -> xcb_depth_iterator_t;
     |                ^^^^^^^^^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.21.0-nightly (ba1d065ff 2017-08-06) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:434:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:610
   5: std::panicking::begin_panic
   6: rustc_errors::Handler::span_bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::span_bug_fmt
   9: <rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o>::ty_of_fn
  10: rustc_typeck::collect::fn_sig
  11: rustc::dep_graph::graph::DepGraph::with_task
  12: rustc::ty::maps::<impl rustc::ty::maps::queries::fn_sig<'tcx>>::try_get
  13: rustc::ty::maps::TyCtxtAt::fn_sig
  14: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::fn_sig
  15: <rustc_typeck::collect::CollectItemTypesVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
  16: rustc_typeck::check_crate::{{closure}}::{{closure}}
  17: rustc_typeck::check_crate
  18: rustc::ty::context::TyCtxt::create_and_enter
  19: rustc_driver::driver::compile_input
  20: rustc_driver::run_compiler

error: Could not compile `xcb`.

```

Version:

```
$ rustc --version --verbose
rustc 1.21.0-nightly (ba1d065ff 2017-08-06)
binary: rustc
commit-hash: ba1d065ffa3606b61201ef69fec3ad0bfc5b2f7b
commit-date: 2017-08-06
host: x86_64-unknown-linux-gnu
release: 1.21.0-nightly
LLVM version: 4.0
```

**Comment by kennytm** [comment] 2017-08-08 09:23
Duplicate of #43567.

**Comment by Mark-Simulacrum** [comment] 2017-08-10 15:03
Closing in favor of https://github.com/rust-lang/rust/issues/43567.

**Closed by Mark-Simulacrum** 2017-08-10 15:03 UTC
