### ISSUE TITLE
coherence failed to report ambiguity

### ISSUE THREAD

**Issue by reads** [rust-lang/rust#25456] opened 2015-05-15 21:19 UTC
I'm a newbie messing about so I couldn't say if this has been reported before or not (certainly similar ones has been.) 

```rust

use std::sync::{Arc, Mutex};
use std::thread;
use std::sync::mpsc::channel;


fn main() {
    
    let channel_collector = Arc::new(Mutex::new(vec!()));
    
    thread::spawn(move || {
        
        let (tx, rx) = channel();
        
        {
            let mut cc = channel_collector.lock().unwrap();
            cc.push(rx); // or tx
        }
        
    });
}
```

```
<anon>:11:5: 11:18 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `core::marker::Send` for the type `[closure <anon>:11:24: 20:6]`
<anon>:11     thread::spawn(move || {
```

http://is.gd/zmtsnG

**Comment by arielb1** [comment] 2015-05-16 15:18
seems to be a duplicate of #25368

**Closed** 2015-05-17 04:36 UTC
