### ISSUE TITLE
LLVM Assertion : Type Unsized

### ISSUE THREAD

**Issue by kmcguire3413** [rust-lang/rust#22465] opened 2015-02-17 22:17 UTC
```
rustc 1.0.0-dev (e29f42025 2015-02-11 17:59:37 +0000)
```
```
rustc: /mnt/host/kmcg3413.net/rust/src/llvm/lib/IR/DataLayout.cpp:655: unsigned int llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed.
```

**Comment by dotdash** [comment] 2015-02-17 22:24
I can't tell for sure because there's no code sample, but this might be the same problem as #21533

**Comment by kmcguire3413** [comment] 2015-02-18 00:15
I do not have time at the moment to further reduce this, and I hate to link a ton of code, but just because it might really be useful to someone to reproduce this error I am linking the source that will produce the error on my machine.

https://www.dropbox.com/s/x0fz07ywt8wh12j/droid_ffi_21.rs?dl=0

The offending line is 1250. If you comment that out it will not abort. Also, that line is incorrect. I was generating the bindings incorrectly, so this problem is no longer holding my project up!

But, like I said, if someone really needs to fix this bug that there should reproduce it.

**Comment by GyrosOfWar** [comment] 2015-02-18 10:47
I've encountered the same error myself, commenting out line 111 in that file stops it from happening:
https://github.com/GyrosOfWar/sickness-sim-rs/blob/master/src/quadtree.rs#L111

**Comment by tamird** [comment] 2015-04-22 01:35
Hi @kmcallister, @GyrosOfWar - do you guys have an example of this with otherwise-compiling code?

**Comment by arielb1** [comment] 2015-10-27 20:15
looks like a duplicate of #19001

**Closed by arielb1** 2015-10-27 20:15 UTC
Labels: I-ICE
