### ISSUE TITLE
cargo: when running an example with a required feature, the feature should automatically be enabled

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#91612] opened 2021-12-06 23:34 UTC
If an example has a required feature
```toml
[[example]]
name = "demo"
required-features = ["alloc"]
```

Then when you try to run the example with the usual command:
```
cargo run --example demo
```

cargo errors out with the following:
```
error: target `demo` in package `my_crate` requires the features: `alloc`
Consider enabling them by passing, e.g., `--features="alloc"`
```

Instead, cargo should just run the demo with the required features enabled. Possibly an output note could be given that the feature was activated automatically, but either way it should "just work".

**Comment by ehuss** [comment] 2021-12-07 01:57
I believe this is a duplicate of https://github.com/rust-lang/cargo/issues/4663, so closing in favor of that.

**Closed by ehuss** 2021-12-07 01:57 UTC
