### ISSUE TITLE
error_index_generator: error while loading shared libraries: libLLVM-11-rust-1.50.0-nightly.so

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#80096] opened 2020-12-16 23:11 UTC
Steps:

* Checkout commit b32e6e6ac8921035177256ab6806e6ab0d4b9b94
* Have `profile = "library"` in `config.toml`. In particular, this implies `download-ci-llvm = "if-available"`
* Run `./x.py doc`

Output (on the second run):

```
Updating only changed submodules
Submodules updated in 0.06 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
Generating unstable book md files (x86_64-unknown-linux-gnu)
Building stage0 tool unstable-book-gen (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.12s
Building stage0 tool rustbook (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.16s
Rustbook (x86_64-unknown-linux-gnu) - unstable-book
Documenting standalone (x86_64-unknown-linux-gnu)
Documenting book redirect pages (x86_64-unknown-linux-gnu)
Documenting stage0 std (x86_64-unknown-linux-gnu)
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.19s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.24s
    Finished release [optimized] target(s) in 0.27s
    Finished release [optimized] target(s) in 0.21s
    Finished release [optimized] target(s) in 0.19s
    Finished release [optimized] target(s) in 0.20s
Documenting stage0 compiler (x86_64-unknown-linux-gnu)
	skipping - compiler/librustdoc docs disabled
Documenting stage0 rustdoc (x86_64-unknown-linux-gnu)
	skipping - compiler/librustdoc docs disabled
Documenting error index (x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.21s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 tool error_index_generator (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.16s
/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator: error while loading shared libraries: libLLVM-11-rust-1.50.0-nightly.so: cannot open shared object file: No such file or directory


command did not execute successfully: "/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator" "html" "/home/simon/projects/rust/build/x86_64-unknown-linux-gnu/doc/error-index.html" "1.50.0"
expected success, got: exit code: 127


failed to run: /home/simon/projects/rust/build/bootstrap/debug/bootstrap doc
```

**Comment by camelid** [comment] 2020-12-16 23:25
cc @Mark-Simulacrum

**Comment by SimonSapin** [comment] 2020-12-16 23:28
For what it’s worth b32e6e6ac8921035177256ab6806e6ab0d4b9b94 is just what I happened to get after running `git pull` today. I mentioned it in case something changes later, it’s a coincidence that that commit happens to be related to downloading LLVM from Rust CI.

**Comment by jyn514** [comment] 2021-01-01 04:51
I think this is a duplicate of https://github.com/rust-lang/rust/issues/78778.

**Comment by nnethercote** [comment] 2022-01-05 23:51
> I think this is a duplicate of #78778.

That issue is closed, and its final comment points to this issue.

**Comment by nnethercote** [comment] 2022-01-05 23:54
I just hit this on the following sequence.
- Do a fresh clone of `rust-lang/rust`
- Run `./x.py setup`
- Select option (b) "compiler: Contribute to the compiler itself"
- Run `./x.py test`

The build finished like so:
```
Building stage0 tool error_index_generator (x86_64-unknown-linux-gnu)
   Compiling same-file v1.0.6
   Compiling walkdir v2.3.1
   Compiling error_index_generator v0.0.0 (/home/njn/dev/rust/src/tools/error_index_generator)
    Finished release [optimized] target(s) in 2.85s
/home/njn/dev/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator: error while loading shared libraries: libLLVM-13-rust-1.59.0-nightly.so: cannot open shared object file: No such file or directory

command did not execute successfully: "/home/njn/dev/rust/build/x86_64-unknown-linux-gnu/stage0-tools-bin/error_index_generator" "html" "/home/njn/dev/rust/build/x86_64-unknown-linux-gnu/doc/error-index.html" "1.59.0"
expected success, got: exit status: 127

Build completed unsuccessfully in 0:20:41
```

**Comment by jyn514** [comment] 2022-01-06 00:08
IMO the proper fix for this is to remove error-index's dependency on rustdoc, either by moving the relevant code out into a library that doesn't use rustc_private, or by duplicating the code altogether. There are other ways to solve this but they'll be more complicated and take longer to compile for no real benefit.

**Comment by camelid** [comment] 2022-01-06 00:19
...or by making it invoke rustdoc-the-binary (through `rustdoc foo.md`), rather than using rustdoc-the-library.

**Comment by jyn514** [comment] 2022-03-13 16:05
@conradludgate you should be able to work around this by adding --stage 2 I think.

**Comment by conradludgate** [comment] 2022-03-13 18:38
> @conradludgate you should be able to work around this by adding --stage 2 I think.

Thanks, that worked

**Comment by jyn514** [comment] 2022-03-27 17:38
> ...or by making it invoke rustdoc-the-binary (through rustdoc foo.md), rather than using rustdoc-the-library.

@camelid I think you're right that the binary will be easier - parsing the markdown requires parsing doctests so that it can generate the "Run" button, and parsing doctests requires all of `rustc_parse`.

**Closed** 2022-04-08 08:13 UTC
Labels: A-linkage, A-LLVM, T-compiler, A-rustbuild, T-infra, C-bug
