### ISSUE TITLE
unexpected panic

### ISSUE THREAD

**Issue by aWeinzierl** [rust-lang/rust#82368] opened 2021-02-21 12:52 UTC
I accidentally broke the compilation. 
The compiler output asked me to report this here:

### Code

https://github.com/aWeinzierl/minesweeper-rs/tree/uwp

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (9b471a3f5 2021-02-19)
binary: rustc
commit-hash: 9b471a3f5fe57e5c6e08acf665f2094422415a3d
commit-date: 2021-02-19
host: x86_64-pc-windows-msvc
release: 1.52.0-nightly
LLVM version: 11.0.1
```

Windows 10 Pro
`[System.Environment]::OSVersion.Version`:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19042  0
```

### Error output

```
cargo +nightly build -Z build-std=std,panic_abort --target x86_64-uwp-windows-msvc --verbose
       Fresh core v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core)
       Fresh cc v1.0.60
       Fresh rustc-std-workspace-core v1.99.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\rustc-std-workspace-core)
       Fresh compiler_builtins v0.1.39
       Fresh libc v0.2.85
       Fresh alloc v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc)
       Fresh cfg-if v0.1.10
       Fresh adler v0.2.3
       Fresh rustc-demangle v0.1.18
       Fresh rustc-std-workspace-alloc v1.99.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\rustc-std-workspace-alloc)
       Fresh unwind v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\unwind)
       Fresh panic_abort v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\panic_abort)
       Fresh gimli v0.23.0
       Fresh panic_unwind v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\panic_unwind)
       Fresh miniz_oxide v0.4.0
       Fresh hashbrown v0.9.0
       Fresh object v0.22.0
       Fresh windows_gen_macros v0.3.1 (https://github.com/microsoft/windows-rs#b434fcbd)
       Fresh addr2line v0.14.0
       Fresh std v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std)
       Fresh windows_macros v0.3.1 (https://github.com/microsoft/windows-rs#b434fcbd)
       Fresh proc_macro v0.0.0 (C:\Users\andre\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\proc_macro)
       Fresh unicode-xid v0.2.1
       Fresh cfg-if v1.0.0
       Fresh squote v0.1.2
       Fresh const-sha1 v0.2.0
       Fresh ppv-lite86 v0.2.10
       Fresh proc-macro2 v1.0.24
       Fresh getrandom v0.1.16
       Fresh quote v1.0.9
       Fresh rand_core v0.5.1
   Compiling bindings v0.1.0 (C:\Users\andre\Documents\git\minesweeper-rs\bindings)
       Fresh syn v1.0.60
       Fresh rand_chacha v0.2.2
     Running `rustc --crate-name build_script_build --edition=2018 bindings\build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=097f88ba7eab2419 -C extra-filename=-097f88ba7eab2419 --out-dir C:\Users\andre\Documents\git\minesweeper-rs\target\debug\build\bindings-097f88ba7eab2419 -C incremental=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\incremental -L dependency=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\deps --extern windows=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\deps\libwindows-a72a5da5bba2a488.rlib`
   Compiling windows_gen v0.3.1 (https://github.com/microsoft/windows-rs#b434fcbd)
       Fresh rand v0.7.3
     Running `rustc --crate-name windows_gen --edition=2018 C:\Users\andre\.cargo\git\checkouts\windows-rs-4d19330348d493fa\b434fcb\crates\gen\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=126354ab8196f32b -C extra-filename=-126354ab8196f32b --out-dir C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps --target x86_64-uwp-windows-msvc -L dependency=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps -L dependency=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\deps --extern noprelude:alloc=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\liballoc-1c720ad92a79ac7c.rmeta --extern noprelude:compiler_builtins=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libcompiler_builtins-28ef1b19865644e8.rmeta --extern noprelude:core=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libcore-b7fa275f21a821cd.rmeta --extern noprelude:panic_abort=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libpanic_abort-617f4bea3487a087.rmeta --extern noprelude:panic_unwind=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libpanic_unwind-3d35921e14f399ac.rmeta --extern proc_macro2=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libproc_macro2-7210dfdb6c064202.rmeta --extern noprelude:proc_macro=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libproc_macro-df3d93ddc773e7e8.rmeta --extern quote=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libquote-49053c1e439dd738.rmeta --extern squote=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libsquote-e0a353cef6914aa0.rmeta --extern noprelude:std=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libstd-f721172c72481471.rmeta --extern syn=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libsyn-b005640ee08a89f3.rmeta --extern macros=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\deps\windows_gen_macros-c9bd239a78e34f67.dll -Z unstable-options --cap-lints allow`
thread 'rustc' panicked at 'compiler\rustc_resolve\src\imports.rs:903:25: inconsistent resolution for an import', /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d\library\std\src\panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (9b471a3f5 2021-02-19) running on x86_64-pc-windows-msvc

note: compiler flags: -Z unstable-options -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `windows_gen`

Caused by:
  process didn't exit successfully: `rustc --crate-name windows_gen --edition=2018 C:\Users\andre\.cargo\git\checkouts\windows-rs-4d19330348d493fa\b434fcb\crates\gen\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=126354ab8196f32b -C extra-filename=-126354ab8196f32b --out-dir C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps --target x86_64-uwp-windows-msvc -L dependency=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps -L dependency=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\deps --extern noprelude:alloc=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\liballoc-1c720ad92a79ac7c.rmeta --extern noprelude:compiler_builtins=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libcompiler_builtins-28ef1b19865644e8.rmeta --extern noprelude:core=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libcore-b7fa275f21a821cd.rmeta --extern noprelude:panic_abort=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libpanic_abort-617f4bea3487a087.rmeta --extern noprelude:panic_unwind=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libpanic_unwind-3d35921e14f399ac.rmeta --extern proc_macro2=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libproc_macro2-7210dfdb6c064202.rmeta --extern noprelude:proc_macro=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libproc_macro-df3d93ddc773e7e8.rmeta --extern quote=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libquote-49053c1e439dd738.rmeta --extern squote=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libsquote-e0a353cef6914aa0.rmeta --extern noprelude:std=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libstd-f721172c72481471.rmeta --extern syn=C:\Users\andre\Documents\git\minesweeper-rs\target\x86_64-uwp-windows-msvc\debug\deps\libsyn-b005640ee08a89f3.rmeta --extern macros=C:\Users\andre\Documents\git\minesweeper-rs\target\debug\deps\windows_gen_macros-c9bd239a78e34f67.dll -Z unstable-options --cap-lints allow` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```
No stacktrace is provided - tried setting `RUST_BACKTRACE` to `1` and `1 cargo build`

</p>

</details>

**Comment by jonas-schievink** [comment] 2021-02-21 13:47
duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2021-02-21 13:47 UTC
Labels: C-bug, I-ICE, T-compiler
