### ISSUE TITLE
rustdoc can't handle existential types

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#58624] opened 2019-02-21 21:37 UTC
```rust
#![feature(existential_type)]

pub trait SomeTrait {
    fn some_fn(&self) {}
    
    type SomeType;
}

struct SomeStruct;

impl SomeTrait for SomeStruct {
    type SomeType = String;
}

pub existential type Asdf: SomeTrait;
pub fn asdf() -> Asdf { SomeStruct }
```

[This sample compiles just fine](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=725c7465d86ff6ae50e5e4ef6ab87bed), but when you run it in rustdoc...

```console
$ rustdoc +nightly c.rs
error[E0277]: the trait bound `(): SomeTrait` is not satisfied
  --> c.rs:15:1
   |
15 | pub existential type Asdf: SomeTrait;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `SomeTrait` is not implemented for `()`
   |
   = note: the return type of a function must have a statically known size

error: Compilation failed, aborting rustdoc

$ rustdoc +nightly --version
rustdoc 1.34.0-nightly (f66e4697a 2019-02-20)
```

My personal guess is that the fact that rustdoc runs `everybody_loops` on the function that defines this type means that it no longer returns the actual type - instead it returns `!`, though the compiler picks up `()` for the error message.

**Comment by QuietMisdreavus** [comment] 2019-02-21 21:43
cc https://github.com/rust-lang/rust/issues/34511

**Comment by oli-obk** [comment] 2019-02-21 21:58
The same thing happens for plain impl trait:

```rust
trait Foo {}

fn foo() -> impl Foo {
    loop {}
}
```

gives 

```
error[E0277]: the trait bound `(): Foo` is not satisfied
 --> src/lib.rs:3:13
  |
3 | fn foo() -> impl Foo {
  |             ^^^^^^^^ the trait `Foo` is not implemented for `()`
  |
  = note: the return type of a function must have a statically known size
```

I'm not sure how to handle this, even if I turn on `#![feature(never_type)]`, I get

```
error[E0277]: the trait bound `!: Foo` is not satisfied
 --> src/lib.rs:5:13
  |
5 | fn foo() -> impl Foo {
  |             ^^^^^^^^ the trait `Foo` is not implemented for `!`
  |
  = note: the return type of a function must have a statically known size
```

**Comment by alecmocatta** [comment] 2019-08-26 10:03
see also https://github.com/rust-lang/rust/issues/58011

**Comment by varkor** [comment] 2020-01-12 17:19
Closing as a duplicate of https://github.com/rust-lang/rust/issues/65863 (which has more information).

**Closed by varkor** 2020-01-12 17:19 UTC
Labels: A-impl-trait, F-type_alias_impl_trait, T-compiler, T-rustdoc, requires-nightly
