### ISSUE TITLE
"access to extern crates through prelude is experimental" in rustdoc

### ISSUE THREAD

**Issue by goffrie** [rust-lang/rust#51449] opened 2018-06-09 00:03 UTC
Current rustdoc nightly errors when trying to document `h2-0.1.9`:
```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  |
  = help: add #![feature(extern_prelude)] to the crate attributes to enable
```

Annoyingly, I can't actually figure out what triggers the error. But it's a regression from stable.

Ref #44660.

**Comment by Mark-Simulacrum** [comment] 2018-06-09 02:41
cc @GuillaumeGomez @QuietMisdreavus @rust-lang/rustdoc

**Comment by QuietMisdreavus** [comment] 2018-06-09 02:44
Duplicate of https://github.com/rust-lang/rust/issues/50561?

**Comment by Mark-Simulacrum** [comment] 2018-06-09 02:49
Looks like it, thanks!

**Closed by Mark-Simulacrum** 2018-06-09 02:49 UTC
Labels: I-nominated, T-rustdoc, regression-from-stable-to-nightly
