### ISSUE TITLE
UFCS ignoring unstable library feature requirements?

### ISSUE THREAD

**Issue by iliekturtles** [rust-lang/rust#36399] opened 2016-09-11 17:56 UTC
In the context of `#![no_std]` libraries the `core::num::Float` trait is marked as unstable but has stable methods, including `powi`. To use the stable methods glob imports or UFCS both work:

Glob import members of the `num` module:
```rust
#![no_std]
#![crate_type="lib"]

use core::num::*;
//use core::num::Float; // error: use of unstable library feature 'core_float': stable
                        // interface is via `impl f{32,64}` in later crates (see issue #32110)

fn foo() -> f32 {
    3.0f32.powi(2)
}
```

Use UFCS:
```rust
#![no_std]
#![crate_type="lib"]

fn bar() -> f32 {
    <f32 as core::num::Float>::powi(3.0f32, 2)
}
```

Shouldn't the UFCS variant give the unstable library feature error? Is there another way to use the member call syntax without the glob import?

**Comment by rkruppe** [comment] 2016-09-11 18:04
The latter (UFCS) is particularly nasty because it allows stable code to depend on there being a trait at that path with that method.

**Comment by alexcrichton** [comment] 2016-09-11 18:20
Thanks for the report! I think this may e a duplicate of https://github.com/rust-lang/rust/issues/30209, though, so closing in favor of that.

**Closed by alexcrichton** 2016-09-11 18:20 UTC

**Comment by rkruppe** [comment] 2016-09-11 18:25
Ugh how did I miss that before telling @iliekturtles to file this issue? =/
