### ISSUE TITLE
"reached the recursion limit during monomorphization" error occured

### ISSUE THREAD

**Issue by hebiyan** [rust-lang/rust#21460] opened 2015-01-21 07:37 UTC
I tried writing tarai function with Rust, version info is:
```
$ rustc --version
rustc 1.0.0-dev (3d5fbae33 2015-01-13 01:08:03 +0000)
```
written code is:
```rust
#![feature(unboxed_closures)]

fn tarai<F:Fn() -> i32>(x:i32, y:i32, z:F) -> i32 {
    if x <= y {
        y
    }
    else {
        let fz = z();
        let nx = tarai(x - 1, y, z);
        let ny = tarai(y - 1, fz, |&:| { x });
        let nz = |&:|  { tarai(fz - 1, x, |&:| { y }) };

        tarai(nx, ny, nz)
    }
}

fn main() {
    println!("{}", tarai(12, 6, |&:| { 0 }));
}

```

but compiling this code, occurs an error like this:
```
$ rustc ./21-161505.rs
21-161505.rs:3:1: 15:2 error: reached the recursion limit during monomorphization
21-161505.rs:3 fn tarai<F:Fn() -> i32>(x:i32, y:i32, z:F) -> i32 {
21-161505.rs:4     if x <= y {
21-161505.rs:5         y
21-161505.rs:6     }
21-161505.rs:7     else {
21-161505.rs:8         let fz = z();
               ...
```
Why my code is wrong? And what should I do for pass compiling without errors?
Please show me these. Sorry for poor my english. Thank you.

**Comment by Aatch** [comment] 2015-01-21 07:52
This is a duplicate of #19596.

The solution is to take a boxed closure and avoid the recursive instantiation: `fn tarai(x: i32, y: i32, z: &Fn() -> i32) -> i32`

**Closed by Aatch** 2015-01-21 07:52 UTC

**Comment by hebiyan** [comment] 2015-01-21 08:13
@Aatch Thank you for showing the solution and the link to existing issue.
Sorry for duplicating issue.
