### ISSUE TITLE
Build fails with external LLVM with ARM backend disabled

### ISSUE THREAD

**Issue by pcercuei** [rust-lang/rust#23971] opened 2015-04-02 14:52 UTC
When compiling with an external LLVM toolchain (using --llvm-root) that does not support the ARM backend, the compilation of the Rust compiler will fail.

I traced it to mk/main.mk:270:
```
LLVM_COMPONENTS=x86 arm aarch64 mips powerpc ipo bitreader bitwriter linker asmparser mcjit interpreter instrumentation
```

This causes the link step to fail, as "llvm-config" issues an error as it does not recognize the "arm" and "aarch64" components.

**Comment by pcercuei** [comment] 2015-04-02 19:29
Actually this is not enouch since the LLVM_LIBS_* and LLVM_LDFLAGS_* are set in mk/main.mk but don't seem to be used elsewhere.
When adding those variables inside mk/target.mk for the linking step, I still get errors as Rustc seems to use ARM-specific symbols from the LLVM libraries.

**Comment by tamird** [comment] 2015-06-01 17:17
Dupe of #14729?

**Comment by alexcrichton** [comment] 2015-06-01 18:15
Looks like it!

**Closed by alexcrichton** 2015-06-01 18:15 UTC
Labels: A-build, A-llvm
