### ISSUE TITLE
format!, println!, and panic! macros cannot handle "super :: ..." and "self :: ..." paths

### ISSUE THREAD

**Issue by erickt** [rust-lang/rust#19075] opened 2014-11-18 17:23 UTC
The format macros seem to be having some trouble parsing an argument that contains `super :: ` and `self :: ` paths, where the white space is significant. Here's an example:

```rust
fn bar() -> int { 5 }

mod foo {
    pub fn foo1() { let _ = format!("{}", super :: bar()); }
    pub fn foo2() { println!("{}", super :: bar()); }
    pub fn foo3() { panic!("{}", super :: bar()); }
    pub fn foo4() { 5 }
    pub fn foo5() { panic!("{}", self :: foo4()); }
}

fn main() {
    foo::foo1();
    foo::foo2();
    foo::foo3();
    println!("{}", foo :: foo4())
}
```

Errors with:

```
test.rs:4:43: 4:48 error: expected identifier, found keyword `super`
test.rs:4     pub fn foo1() { let _ = format!("{}", super :: bar()); }
                                                    ^~~~~
test.rs:5:36: 5:41 error: expected identifier, found keyword `super`
test.rs:5     pub fn foo2() { println!("{}", super :: bar()); }
                                             ^~~~~
test.rs:6:34: 6:39 error: expected identifier, found keyword `super`
test.rs:6     pub fn foo3() { panic!("{}", super :: bar()); }
                                           ^~~~~
test.rs:8:21: 8:50 error: expected token: `,`
test.rs:8     pub fn foo5() { panic!("{}", self :: foo4()); }
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Notice that a regular module paths work, but the special `super` and `self` tokens do not.

**Comment by Toby-S** [comment] 2015-11-10 14:05
@steveklabnik duplicate of #14109

**Comment by steveklabnik** [comment] 2015-11-10 15:52
Yes, this seems to be true. thanks @Toby-S !

**Closed by steveklabnik** 2015-11-10 15:52 UTC
Labels: A-macros
