### ISSUE TITLE
ICE running `cargo doc` on nightly

### ISSUE THREAD

**Issue by vitiral** [rust-lang/rust#46351] opened 2017-11-28 23:05 UTC
Happened while developing [this library at this commit](https://github.com/vitiral/stdcli/commit/7a706bf9ee1af249fcf9c46835ef1fd8893c0488) and running `cargo doc --open -p loggerv`

```
 Documenting atty v0.2.3                                                                      
error: internal compiler error: /checkout/src/librustc/hir/map/mod.rs:298: called HirMap::read() with invalid NodeId
                                       
note: the compiler unexpectedly panicked. this is a bug.                   
                                                            
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                        
note: rustc 1.24.0-nightly (560a5da9f 2017-11-27) running on x86_64-unknown-linux-gnu     
                                              
note: run with `RUST_BACKTRACE=1` for a backtrace                                              
                                                                             
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:501:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:                                                                           
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                   
   1: std::sys_common::backtrace::print             
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: _ZN3std9panicking12default_hook28_$u7b$$u7b$closure$u7d$$u7d$17h46e987905301ae22E.llvm.9A227FD4
             at /checkout/src/libstd/panicking.rs:381    
   3: _ZN3std9panicking12default_hook17hb2b8a14db1b46882E.llvm.9A227FD4
       at /checkout/src/libstd/panicking.rs:391                                                                                                                 
   4: std::panicking::rust_panic_with_hook   
             at /checkout/src/libstd/panicking.rs:577    
   5: std::panicking::begin_panic                       
   6: rustc_errors::Handler::bug                        
   7: <std::thread::local::LocalKey<T>>::with                                                                       
   8: rustc::ty::context::tls::with_opt                
   9: _ZN5rustc7session16opt_span_bug_fmt17h4e7498e3ba9a7835E.llvm.2CC54D85
  10: rustc::session::bug_fmt
  11: rustc::hir::map::Map::read                                                                                 
  12: rustc::hir::map::Map::span
  13: _ZN5rustc9dep_graph5graph8DepGraph14with_task_impl17h2c32cdaa2271bd66E.llvm.9A11F13B
  14: rustc_errors::Handler::track_diagnostics
  15: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::cycle_check
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::def_span<'tcx>>::force                                                                                                                                        17: rustc::ty::maps::<impl rustc::ty::maps::queries::def_span<'tcx>>::try_get  
18: rustc::ty::maps::TyCtxtAt::def_span                                              
  19: rustc::ty::maps::<impl rustc::ty::maps::queries::extern_mod_stmt_cnum<'tcx>>::try_get
  20: rustc::ty::maps::TyCtxtAt::extern_mod_stmt_cnum
  21: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::extern_mod_stmt_cnum
  22: rustc_typeck::check_unused::check_crate
  23: rustc_typeck::check_crate
  24: <std::thread::local::LocalKey<T>>::with
             at /checkout/src/librustc_driver/driver.rs:1041                                                     
             at /checkout/src/librustc/ty/context.rs:1453
             at /checkout/src/libstd/thread/local.rs:377                                  
             at /checkout/src/libstd/thread/local.rs:288
  25: <std::thread::local::LocalKey<T>>::with                                                  
             at /checkout/src/librustc/ty/context.rs:1450                                                                                                                                                                       at /checkout/src/libstd/thread/local.rs:377                                                                                                              
             at /checkout/src/libstd/thread/local.rs:288                               
  26: rustc::ty::context::TyCtxt::create_and_enter                                         
  27: rustc_driver::driver::phase_3_run_analysis_passes
             at /checkout/src/librustc_driver/driver.rs:1018                                  
  28: rustdoc::core::run_core                
             at /checkout/src/librustdoc/core.rs:182
                                             
error: Could not document `atty`.                           
                                                         
Caused by:                                              
  process didn't exit successfully: `rustdoc --crate-name atty /home/garrett/.cargo/registry/src/github.com-1ecc6299db9ec823/atty-0.2.3/src/lib.rs -o /home/garrett/src/ruststuff/stdcli/target/doc -L dependency=/
home/garrett/src/ruststuff/stdcli/target/debug/deps --extern libc=/home/garrett/src/ruststuff/stdcli/target/debug/deps/liblibc-132ba9c0c047b946.rlib` (exit code: 101)

```

**Comment by Mark-Simulacrum** [comment] 2017-11-29 01:19
Duplicate of https://github.com/rust-lang/rust/issues/46271.

**Closed** 2017-11-29 01:20 UTC
Labels: A-rustdoc
