### ISSUE TITLE
Warning message formatting: unused const

### ISSUE THREAD

**Issue by dawirstejeck** [rust-lang/rust#37355] opened 2016-10-22 18:24 UTC
Hello!
I noticed the following behaviour: if I insert a line break into my `const` definition, the highlighting and "underlining" behaviour of the "unused" warning changes. It confused me for the first moment, since I thought I spelled `const` wrong.
```
warning: constant item is never used: `IND_TOP_RIGHT`, #[warn(dead_code)] on by default
   --> src/lib.rs:191:1
    |
191 | const IND_TOP_RIGHT: usize    =
    | ^
```
vs.
```
warning: constant item is never used: `IND_TOP_RIGHT`, #[warn(dead_code)] on by default
   --> src/lib.rs:191:1
    |
191 | const IND_TOP_RIGHT: usize    = 5;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Wouldn't it be better if only the constants name was highlighted anyway?

**Comment by nagisa** [comment] 2016-10-22 22:47
Duplicate of https://github.com/rust-lang/rust/issues/33961

**Comment by dawirstejeck** [comment] 2016-10-23 07:06
Oh you are right. I couldn't find this issue before.

**Closed** 2016-10-23 07:08 UTC
