### ISSUE TITLE
Exponential performance cliff compiling associated types with equality constraints 

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#22204] opened 2015-02-12 02:21 UTC
This was first observed due to a bunch of `chain` calls in rustdoc (#21694). @huonw provided a minimal test case:

``` rust
struct Pair<A, B>(A, B);

trait Foo: Sized {
    type Item = ();
    fn foo<B>(self, other: B) -> Pair<Self, B> {
        Pair(self, other)
    }
}
impl Foo for () {
    type Item = ();
}
#[cfg(equality)]
impl<A: Foo, B: Foo<Item = A::Item>> Foo for Pair<A, B> {
    type Item = A::Item;
}
#[cfg(not(equality))]
impl<A: Foo, B: Foo> Foo for Pair<A, B> {
    type Item = A::Item;
}

fn main() {
    ().foo(())
        .foo(())
        .foo(())
        .foo(())
        .foo(())
        .foo(())
        .foo(())
        .foo(())
        .foo(())
        ;
}
```

**Comment by huonw** [comment] 2015-02-12 02:38
This also applies for trait bounds, e.g. replacing the `equality` `impl` with

```rust
trait X<T> {}

impl X<()> for () {}

#[cfg(equality)]
impl<A: Foo, B: Foo> Foo for Pair<A, B>
        where A::Item: X<B::Item> {
    type Item = A::Item;
}
```

gives similar results.

**Comment by darinmorrison** [comment] 2015-02-12 03:48
cc me

**Comment by jdm** [comment] 2015-02-12 12:30
cc me

**Comment by brson** [comment] 2015-02-12 20:17
Nominating because this seems to impact servo.

**Comment by pnkfelix** [comment] 2015-02-12 21:37
1.0 beta, P-high.

**Comment by larsbergstrom** [comment] 2015-02-13 00:00
I am not 100% sure we are hitting this - I believe that when we were investigating the perf regressions we suspected this, but I am not certain. Is there something we can do to verify we're hitting it? (assuming you would postpone it if it's not an issue for Servo).

**Comment by Gankro** [comment] 2015-02-13 20:30
https://github.com/rust-lang/rust/issues/21694 demonstrates that if you're hitting it, it should show up in the type checking phase, which is otherwise quite lean. Should show up pretty clearly.

**Comment by gereeter** [comment] 2015-02-22 22:13
A slightly more minimal test case:

```rust
struct A<X>(X);

trait Foo: Sized {
    type Item;
    fn go(self) -> A<Self> {
        A(self)
    }
}

impl Foo for () {
    type Item = ();
}

#[cfg(equality)]
impl<X: Foo<Item=()>> Foo for A<X> {
    type Item = ();
}

#[cfg(not(equality))]
impl<X: Foo> Foo for A<X> {
    type Item = ();
}

fn main() {
    ().go().go().go().go()
      .go().go().go().go()
      .go().go().go().go()
      .go().go().go().go();
}
```

**Comment by pnkfelix** [comment] 2015-03-26 21:41
1.0 polish (if anything; definitely puntable if we cannot fix in time).

**Comment by arielb1** [comment] 2015-06-02 21:35
There are 2 problems here:
    1) evaluate_predicates_recursively doesn't do memoization (this can easily be fixed).
    2) we don't memoize associated types. this is harder to fix as they could have inferred and infer-skolemized contents, and generate nested obligations (esp. region obligations). I kind-of want to fix this already for trans, but trans doesn't have these difficulties.

**Comment by Ralle** [comment] 2015-10-20 04:54
All of us using this crate ( https://github.com/Marwes/combine ) are waiting for this to get fixed. My compile time for a 500 line program is over 2 minutes. The maintainer of combine has helped people try to optimize their code for the compiler to run faster, not the result. I would very much like to see this ticket on any milestone, so I can look forward to Rust being usable in my parser project.

**Comment by mrZalli** [comment] 2016-02-24 19:14
Same as Ralle, I came here from combine. It seems like a really nice parsing library for my project, but even the simple demonstration test that was in their docs took alarmingly long to compile, so I hope this gets fixed soon.

**Comment by asajeffrey** [comment] 2016-02-25 17:58
Ditto, coming here from perf issues with my parser library (https://github.com/rust-lang/rust/issues/31849). My minimal example is just chaining iterators (https://play.rust-lang.org/?gist=a0c05fbf5c43234fb7c3):
```rust
fn main() {
    let iter = (0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2)
        .chain(0..2);
    for i in iter { println!("{:?}", i); }
}
```
On my machine, chaining 15 iterators takes 1min to typecheck, and uses about 500M of memory.

**Comment by asajeffrey** [comment] 2016-02-25 21:51
Separating out the projection trait (`HasItem`) as a separate trait seems to be a work-around... https://play.rust-lang.org/?gist=1cf9886dd074e073cd6a
```rust
trait HasItem {
    type Item;
}

trait TDIterator<Item> {
    fn next(&mut self) -> Option<Item>;
}

trait BUIterator: HasItem + TDIterator<<Self as HasItem>::Item> {
}
```

**Comment by asajeffrey** [comment] 2016-03-01 19:26
The work-around does scale up to the Parsell parser library (see, e.g. http://asajeffrey.github.io/parsell/target/doc/parsell/trait.StatefulInfer.html). It may be that combine can use a similar work-around? cc @Marwes.

**Comment by Marwes** [comment] 2016-03-01 19:48
@asajeffrey It would unfortunately be a backwards incompatible change so I am afraid I cannot do it at the moment for combine. I may do it for 2.0 though I am not inclinded to rush towards that at the moment.

(I did test compiling a branch I already had where combine's `Input` type is a parameter instead of associated and it cut compiling the tests into half 1m10s -> 32s)

**Comment by asajeffrey** [comment] 2016-03-01 20:04
@Marwes indeed, Parsell has the luxury of still being at v0.x.x so I can make changes like this more easily.

**Comment by nikomatsakis** [comment] 2016-03-21 21:30
Just FYI, my projection caching branch (PR coming soon) totally solves this problem, from what I can tell.

**Comment by nikomatsakis** [comment] 2016-03-21 21:31
hmm, although actually maybe it's already been solved.  At least stage0 seems to run fine too.

**Comment by nikomatsakis** [comment] 2016-03-21 21:33
I take it back, the [chained iterator case is still quite slow](https://github.com/rust-lang/rust/issues/22204#issuecomment-188904689).

**Comment by arielb1** [comment] 2016-06-09 20:01
This looks fixed with the projection cache.

**Comment by ishitatsuyuki** [comment] 2018-04-02 15:02
#48296 should have solved this completely. Closing as obsolete.

**Closed by ishitatsuyuki** 2018-04-02 15:03 UTC
Labels: A-associated-items, C-enhancement, E-needstest, I-compiletime, P-medium, T-compiler
