### ISSUE TITLE
rustc panic with inline asm

### ISSUE THREAD

**Issue by anderspapitto** [rust-lang/rust#56991] opened 2018-12-19 19:25 UTC
I hit a compiler panic with some inline asm (which is likely itself buggy at the moment, but of course that shouldn't crash the compiler)

```
note: rustc 1.33.0-nightly (d99a320cb 2018-12-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 --crate-type lib
```

```
error: internal compiler error: src/librustc_codegen_ssa/mir/operand.rs:135: not immediate: OperandRef(Ref((%Node*:  %43 = load %Node*, %Node** %42, align 64), None, Align { pow2: 6 }) @ TyLayout { ty: Node, details: LayoutDetails { variants: Single { index: 0 }, fields: Arbitrary { offsets: [Size { raw: 0 }], memory_index: [0] }, abi: Aggregate { sized: true }, align: AbiAndPrefAlign { abi: Align { pow2: 6 }, pref: Align { pow2: 6 } }, size: Size { raw: 64 } } })
```

```
thread 'main' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:72
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:60
             at src/libstd/panicking.rs:210
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:225
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:492
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc_codegen_llvm::asm::<impl rustc_codegen_ssa::traits::asm::AsmBuilderMethods<'tcx> for rustc_codegen_llvm::builder::Builder<'a, 'll, 'tcx>>::codegen_inline_asm
  15: rustc_codegen_ssa::mir::codegen_mir
  16: rustc_codegen_ssa::base::codegen_instance
  17: rustc_codegen_ssa::mono_item::MonoItemExt::define
  18: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  19: rustc::dep_graph::graph::DepGraph::with_task
  20: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  21: rustc_codegen_ssa::base::codegen_crate
  22: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  23: rustc::util::common::time
  24: rustc_driver::driver::phase_4_codegen
  25: rustc_driver::driver::compile_input::{{closure}}
  26: rustc::ty::context::tls::enter_context
  27: <std::thread::local::LocalKey<T>>::with
  28: rustc::ty::context::TyCtxt::create_and_enter
  29: rustc_driver::driver::compile_input
  30: rustc_driver::run_compiler_with_pool
  31: <scoped_tls::ScopedKey<T>>::set
  32: rustc_driver::run_compiler
  33: syntax::with_globals
  34: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  35: rustc_driver::run
  36: rustc_driver::main
  37: std::rt::lang_start::{{closure}}
  38: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:307
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  40: std::rt::lang_start_internal
             at src/libstd/panicking.rs:286
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  41: main
  42: __libc_start_main
  43: <unknown>
query stack during panic:
end of query stack
```

**Comment by nikic** [comment] 2018-12-19 19:56
Could you please also provide the inline asm that triggered this panic?

**Comment by anderspapitto** [comment] 2018-12-19 20:47
@nikic the asm block looks like this

```
            asm!("
                mov rcx, QWORD PTR [$1]
                \tmov rcx, QWORD PTR [rcx]
                \tmov QWORD PTR [$1], rcx\n\t"
                : "+m"(*x)
                : "r"(x)
                : "rcx"
                : "intel"
```

**Comment by workingjubilee** [comment] 2020-04-26 11:22
Fussed with variations on this but could not reproduce the ICE, got many interesting (correctly handled) compiler errors though.

**Comment by Amanieu** [comment] 2020-05-22 19:28
Closing since this can't be reproduced and `llvm_asm!` is deprecated an no longer maintained.

**Closed by Amanieu** 2020-05-22 19:28 UTC
Labels: A-inline-assembly, C-bug, I-ICE, T-compiler, requires-nightly
