### ISSUE TITLE
ICE: building gfx_device_gl 0.8.2 with nightly 03-18-2016 on OSX El Capitan

### ISSUE THREAD

**Issue by olsonjeffery** [rust-lang/rust#32336] opened 2016-03-18 14:46 UTC
Like it says on the tin.

OSX El Capitan. Latest rust installed from multirust:
```
bash-3.2$ rustc --version
rustc 1.9.0-nightly (b12b4e4e3 2016-03-17)
```

To repro:

```
cd ~/your/src/workspace
multirust default nightly-2016-03-18
git clone https://github.com/gfx-rs/gfx
cd gfx/src/backend/gl
RUST_BACKTRACE=1 cargo build --verbose
```

Output:
```
bash-3.2$ RUST_BACKTRACE=1 cargo build --verbose
   Compiling gfx_device_gl v0.8.2 (file:///Users/jeff/src/gfx/src/backend/gl)
   Running `rustc src/lib.rs --crate-name gfx_device_gl --crate-type lib -g --out-dir /Users/jeff/src/gfx/src/backend/gl/target/debug --emit=dep-info,link -L dependency=/Users/jeff/src/gfx/src/backend/gl/target/debug -L dependency=/User
s/jeff/src/gfx/src/backend/gl/target/debug/deps --extern gfx_core=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps/libgfx_core-92df53d9ae04f09f.rlib --extern log=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps/liblog-0ec442df0ecb
416b.rlib --extern gfx_gl=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps/libgfx_gl-eed872f0f37bdbbe.rlib`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
stack backtrace:
   1:        0x104993998 - sys::backtrace::tracing::imp::write::h3153bab3099b48114Zu
   2:        0x10499ceb9 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43920
   3:        0x10499c9d7 - panicking::default_handler::h1183b2a11c8682560zz
   4:        0x104963fc6 - sys_common::unwind::begin_unwind_inner::h1f97bc9e4cfe0396LZt
   5:        0x104965bde - sys_common::unwind::begin_unwind_fmt::hda8646f04aa67d8aRYt
   6:        0x104991267 - rust_begin_unwind
   7:        0x1049d6100 - panicking::panic_fmt::h40f5ec0cdc3fc429FRL
   8:        0x1049d6cfc - panicking::panic::hf105884501521a8dcQL
   9:        0x1013bba2d - middle::traits::specialize::specialization_graph::Graph::parent::h713e7817b3824c97Dj0
  10:        0x1013bbd5c - middle::traits::specialize::specialization_graph::Ancestors<'a, 'tcx>.Iterator::next::hef4c71337b607036yp0
  11:        0x1013bbf92 - iter::FlatMap<I, U, F>.Iterator::next::h17071612212236951353
  12:        0x101392f23 - middle::traits::project::assoc_ty_def::h54f9c8393ffeceb5QMV
  13:        0x10138eca6 - middle::traits::project::opt_normalize_projection_type::hf8d1da3156c0f1a6ySU
  14:        0x10137ad20 - middle::traits::project::normalize_projection_type::h874da303c815a568nRU
  15:        0x1012b3600 - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>.TypeFolder<'tcx>::fold_ty::h1eeeec880b5082734OU
  16:        0x101364bf1 - middle::ty::fold::TypeFolder::fold_substs::h15562033972663033001
  17:        0x101364768 - middle::ty::structural_impls::ty..Predicate<'tcx>.TypeFoldable<'tcx>::super_fold_with::h1253006924916156103
  18:        0x1013b59ed - middle::traits::project::AssociatedTypeNormalizer<'a, 'b, 'tcx>::fold::h7150300406040149710
  19:        0x1013b55fd - middle::traits::select::SelectionContext<'cx, 'tcx>::impl_or_trait_obligations::_$u7b$$u7b$closure$u7d$$u7d$::closure.94302
  20:        0x1013b4c3b - iter::FlatMap<I, U, F>.Iterator::next::h8853686016495372949
  21:        0x1013b42ea - vec::Vec<T>.FromIterator<T>::from_iter::h14657226624535963680
  22:        0x1013af32d - middle::traits::select::SelectionContext<'cx, 'tcx>::impl_or_trait_obligations::hab16b4fea86ac6c95YZ
  23:        0x1013afc40 - middle::traits::select::SelectionContext<'cx, 'tcx>::vtable_impl::he1c794762aa855d3QjZ
  24:        0x1013af8d9 - middle::infer::InferCtxt<'a, 'tcx>::commit_if_ok::h7037753687171629328
  25:        0x10139e63a - middle::traits::select::SelectionContext<'cx, 'tcx>::confirm_candidate::he1604437ab419381vRY
  26:        0x1013a4028 - middle::traits::select::SelectionContext<'cx, 'tcx>::evaluate_candidate::_$u7b$$u7b$closure$u7d$$u7d$::closure.93879
  27:        0x1013a3c7a - middle::traits::select::SelectionContext<'cx, 'tcx>::evaluate_stack::h435e79885805edaePcX
  28:        0x1013a2dce - middle::traits::select::SelectionContext<'cx, 'tcx>::evaluate_predicate_recursively::h44cd0f87db087ae523W
  29:        0x1012adf6d - middle::traits::type_known_to_meet_builtin_bound::hc61f7642f1e8ae84cg2
  30:        0x1013e573c - middle::ty::util::ty..TyS<'tcx>::impls_bound::h93815121b1c2f2b9Tw8
  31:        0x1012ae3b0 - middle::ty::util::ty..TyS<'tcx>::moves_by_default::h006110b40bcd7ebaaz8
  32:        0x1011ffc78 - middle::infer::InferCtxt<'a, 'tcx>::type_moves_by_default::hbe4b0519d279e6a6r3D
  33:        0x1013e2bdd - middle::ty::util::ParameterEnvironment<'a, 'tcx>::can_type_implement_copy::h148960d97ed2e457L57
  34:        0x100f0b66e - coherence::CoherenceChecker<'a, 'tcx>::check_implementations_of_copy::_$u7b$$u7b$closure$u7d$$u7d$::closure.47275
  35:        0x100e08c6b - coherence::check_coherence::h3c7554163b347120qeB
  36:        0x100e01d7d - check_crate::h70a3f53b44b86a656KC
  37:        0x10046c6d1 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.30102
  38:        0x10046ad09 - middle::ty::context::TyCtxt<'tcx>::create_and_enter::h1239698422812857229
  39:        0x1004676cd - driver::phase_3_run_analysis_passes::h4265638487230740945
  40:        0x10043a6de - driver::compile_input::hbe344176ee080f49Pca
  41:        0x100427f96 - run_compiler::h513ed7ebfac4786dJPc
  42:        0x100425542 - sys_common::unwind::try::try_fn::h18146670127766281356
  43:        0x1049911fb - __rust_try
  44:        0x104991183 - sys_common::unwind::inner_try::hdf6affff6fc30ecdNWt
  45:        0x100425dd9 - boxed::F.FnBox<A>::call_box::h16832868406443570230
  46:        0x10499bd2c - sys::thread::Thread::new::thread_start::he33a0e5f2597fcdejOy
  47:     0x7fff95564c12 - _pthread_body
  48:     0x7fff95564b8f - _pthread_start

error: Could not compile `gfx_device_gl`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name gfx_device_gl --crate-type lib -g --out-dir /Users/jeff/src/gfx/src/backend/gl/target/debug --emit=dep-info,link -L dependency=/Users/jeff/src/gfx/src/backend/gl/target/debug -L dependency=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps --extern gfx_core=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps/libgfx_core-92df53d9ae04f09f.rlib --extern log=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps/liblog-0ec442df0ecb416b.rlib --extern gfx_gl=/Users/jeff/src/gfx/src/backend/gl/target/debug/deps/libgfx_gl-eed872f0f37bdbbe.rlib` (exit code: 101)
```

**Comment by alexcrichton** [comment] 2016-03-18 16:14
Thanks for the report! I think this is a dupe of https://github.com/rust-lang/rust/issues/32324, however, so I'm gonna close in favor of that.

**Closed by alexcrichton** 2016-03-18 16:14 UTC
