### ISSUE TITLE
--remap-path-prefix no longer works for compiler messages

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust#87745] opened 2021-08-03 23:04 UTC
### Code

Create a directory and put a Rust file with bad syntax in it:
```
mkdir src
echo bad > src/test.rs
```

Then compile it with:

```
rustc --remap-path-prefix=src=MODIFIED src/test.rs
```

I expected to see output like this:

```
error: expected one of `!` or `::`, found `<eof>`
 --> MODIFIED/test.rs:1:1
[snip]
```

Instead, the path is not modified and I get:

```
error: expected one of `!` or `::`, found `<eof>`
 --> src/test.rs:1:1
[snip]
```

### Version it worked on

rustc 1.53.0 (53cb7b09b 2021-06-17)

### Version with regression

rustc 1.54.0 (a178d0322 2021-07-26)

**Comment by nicholasbishop** [comment] 2021-08-03 23:14
Bisected:

searched nightlies: from nightly-2021-03-17 to nightly-2021-08-03
regressed nightly: nightly-2021-05-13
searched commits: from https://github.com/rust-lang/rust/commit/5c029265465301fe9cb3960ce2a5da6c99b8dcf2 to https://github.com/rust-lang/rust/commit/21e92b97309e15b16bc6b8dd4509d5e3ad4c430d
regressed commit: https://github.com/rust-lang/rust/commit/e1ff91f439bc09f566da211c6449821b4e949279

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2021-03-17 --preserve --script=./bisect-check.py 
```
</details>

**Comment by apiraino** [comment] 2021-08-05 09:37
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387745.20--remap-path-prefix.20no.20longer.20works.20for.20compiler.20mes.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by inquisitivecrystal** [comment] 2021-08-07 02:22
After further discussion, there appears to be a consensus in the Prioritization Working Group that this should be `P-medium` for the moment. Sorry for the noise!

**Comment by dtolnay** [comment] 2021-08-18 18:09
FYI @cbeuw @michaelwoerister, since this bisects to #83813. Would one of you be able to take a look?

**Comment by cbeuw** [comment] 2021-08-18 19:18
I thought this is the intended behaviour? The local path is not embedded into a compilation output. Compiler diagnostics should give you the local path

**Comment by dtolnay** [comment] 2021-08-18 19:27
For Buck's use case of `--remap-path-prefix`, I believe we want the remapped path in the diagnostic, rather than original.

Before:

```console
  --> eden/mononoke/commit_rewriting/megarepo/src/history_fixup_delete.rs:55:13
```

After regression:

```console
  --> buck-out/dev/bin/aab7ed39/eden/mononoke/commit_rewriting/megarepo/megarepolib#platform009-clang,rlib-pic/eden/mononoke/commit_rewriting/megarepo/src/history_fixup_delete.rs:55:13
```

Context: in a monorepo codebase, all the source files have a canonical path relative to the root of the monorepo. Those are the files that the engineer edits as part of day-to-day development. For rustc invocations though, the paths fed into the compiler are nested somewhere inside a buck-managed directory. This is necessary for example in order to overlay generated sources into that directory side by side with the handwritten sources.

**Comment by inquisitivecrystal** [comment] 2021-08-19 02:49
> I thought this is the intended behaviour? The local path is not embedded into a compilation output. Compiler diagnostics should give you the local path

wg-prioritization got confused about this too, which is part of why we had so much trouble prioritizing this correctly. @nicholasbishop pointed out to us that the old behavior was intentional. It's actually part of the documentation for the flag:

```
--remap-path-prefix FROM=TO
                        Remap source names in all output (compiler messages
                        and output files)
```

**Comment by jsgf** [comment] 2021-08-19 03:34
> I thought this is the intended behaviour? The local path is not embedded into a compilation output. Compiler diagnostics should give you the local path

No it's a regression. The original intended behavior is to remap diagnostic paths as well.

**Comment by michaelwoerister** [comment] 2021-08-19 12:52
I also thought that the intended behavior has changed after https://github.com/rust-lang/rust/pull/70642 and the consensus was that diagnostics should _not_ be remapped, so that one gets "real" file system paths in error messages that one can click on / copy & paste, etc.

I'm wondering if we need to make this behavior configurable. It looks like there is no solution that is correct in all use cases. @cbeuw, does your RFC cover this already maybe?

**Comment by jsgf** [comment] 2021-08-19 16:26
@michaelwoerister In our use case, the one @dtolnay [presented above](https://github.com/rust-lang/rust/issues/87745#issuecomment-901372202), we're using `--remap-path-prefix` to map from temporary build locations to the real location that users can cut'n'paste, edit, open, etc, and also normalize out the cwd (which #87320 would also address).

I believe the idea to remap diagnostic paths came from me in https://github.com/rust-lang/rust/issues/38322#issuecomment-295959049 and you implemented this in https://github.com/rust-lang/rust/pull/41508 specifically noting that it also covers error messages.

So as far as this issue goes, not mapping error paths is a regression from the designed behaviour of `--remap-path-prefix`, and maybe we need to add some other mechanism to deal with #73167 though I admit I haven't fully grokked the details of the issue  yet. My initial impression is that it's the question of whether `--remap-path-prefix` should remap paths embedded in other crate's metadata as part of diagnostics? Or does that already happen? Or is it that we should have some well-defined meta-path-prefixes to logically refer to sources which are "elsewhere" (which @infinity0 somewhat hinted at in https://github.com/rust-lang/rust/issues/38322#issuecomment-274262078).

(I'd really like to avoid having two distinct subtly-interacting features covering the same area.)

**Comment by cbeuw** [comment] 2021-08-19 22:13
@michaelwoerister My original RFC doesn't cover this (as it was solely to do with Cargo). In response to the RFC feedback, my https://github.com/rust-lang/rfcs/pull/3127#issuecomment-869199458 suggested that we have two extra remapping flags for rustc, one controlling only debuginfo and one controlling only `std::file!()` expansion (for panic messages). This is basically the set up in Clang and GCC. I still haven't finished the amended RFC with those additions because writing is hard :(

For now, if we are set that printing remapped path in diagnostics is the right behaviour for `--remap-path-prefix`, we should be able to do it just by replacing calls to `prefer_local` to `prefer_remapped` in here https://github.com/rust-lang/rust/blob/master/compiler/rustc_errors/src/emitter.rs. As a longer term solution I suppose we could add a third extra flag that controls the remapping of only compiler diagnostics? 


@jsgf `--remap-path-prefix` does not affect paths coming from an external crate. Nothing in here does remapping on the path of an imported file (except for some hacks on sysroot paths to make some tests consistent when different config was used for rustc bootstrapping) https://github.com/rust-lang/rust/blob/7960030d6915a771f5ab72c3897a7ed50c3ed4bd/compiler/rustc_metadata/src/rmeta/decoder.rs#L1767-L1863

When rustc exports metadata for the current crate, paths not affected by `--remap-path-prefix` will have the actual local paths exported; paths affected by `--remap-path-prefix` will _only_ have the remapped path exported. Those are what another rustc session will see if it imports it.
https://github.com/rust-lang/rust/blob/7960030d6915a771f5ab72c3897a7ed50c3ed4bd/compiler/rustc_span/src/lib.rs#L200-L204

**Comment by michaelwoerister** [comment] 2021-08-20 08:13
@jsgf Yes, I think I have read too much into the changes in #70642. I think this is a regression and I would consider it `P-high`.

I am wondering what to do about the `rust-src` case though. Since #70642 the compiler will detect if the source code of the standard library is available and remap paths into from the "virtual path" (i.e. `/rustc/$rustc_sha`) to the actual file system path. If the `rust-src` rustup component is not installed (as I imagine it is not on your build machines) then you get the virtual paths -- so that case should be fine in practice. But I wonder if this `rust-src` remapping should be disabled as soon as _any_ `--remap-path-prefix` is present for the given compiler invocation. Or if there should be a flag to explicitly control this behavior.

@cbeuw, would you be up for working with me on fixing the regression? If we are quick, we might still be able backport it to the current beta.

**Comment by cbeuw** [comment] 2021-08-20 22:15
@michaelwoerister Regarding #70642, could we just drop the virtual path on sysroot files when `rust-src` is available, and emit the local path everywhere by default unless they have been remapped by an explicit `--remap-path-prefix`? This will address #85463 as well. I'm happy to open an MCP on this if you think this is a big enough change

**Comment by michaelwoerister** [comment] 2021-08-23 09:37
> Regarding #70642, could we just drop the virtual path on sysroot files when rust-src is available, and emit the local path everywhere by default unless they have been remapped by an explicit --remap-path-prefix?

@cbeuw, I'm afraid that that would effectively re-introduce https://github.com/rust-lang/rust/issues/73167. Code instantiated from the standard library would again refer to the local path, even in debuginfo and panic messages, and there would be no way to opt-out of that short of uninstalling the `rust-src` component, right?

**Comment by michaelwoerister** [comment] 2021-08-23 10:15
Let's pull in @rust-lang/wg-diagnostics for feedback on the intended behavior here. Here is a summary of the problem:
- https://github.com/rust-lang/rust/pull/70642 implemented a feature in the compiler that makes it emit file paths to the actual source files in the standard library if the `rust-src` rustup component is installed. So instead of emitting 
  - `/rustc/881c1ac408d93bb7adaa3a51dabab9266e82eee8/library/std/src/panicking.rs:493:5`, the compiler would emit
  - `/home/mw/.rustup/toolchains/nightly/lib/rustlib/src/rust/library/std/src/panicking.rs:493:5`.
  
  This is convenient when working locally because the path points to the actual file on disk. But it broke the `--remap-path-prefix` feature (used e.g. for privacy, reproducible builds) because there we really want to avoid local file system paths ending up in the produced binary -- and there was no way to opt out of this behavior.
 - For this reason @cbeuw implemented a fix in https://github.com/rust-lang/rust/pull/83813 that made sure we emit the remapped paths (`/rustc/{sha}/library/...`) into output artifacts, while still emitting local file system paths for diagnostic messages.
 - However, it turns out that sometimes (as evidenced by this issue) it is preferable to emit remapped paths _for diagnostic messages too_.

To me it seems that both use cases make a valid claim for either remapped or local paths to be emitted in diagnostic messages. The question is: how do we support both? 

RFC https://github.com/rust-lang/rfcs/pull/3127 will probably make this behavior configurable via commandline flags like `--remap-debuginfo-prefix`, `--remap-macro-prefix`, and `--remap-diagnostics-prefix`. But we don't know when that RFC will be merged and in which form exactly. So for addressing this regression, I don't think we want to wait for that.

So my question is: What should we do here? The options I see are:
- Fix the regression by unconditionally emitting remapped paths in diagnostic messages (implemented in https://github.com/rust-lang/rust/pull/88191). This will essentially undo the `rust-src` functionality until the behavior has been made configurable via the RFC.
- Leave things as they are now until the behavior has been made configurable via the RFC.
- Try to automatically choose the right behavior by disabling the `rust-src` functionality if any `--remap-path-prefix` option (even one that does not target standard library paths) is provided to `rustc`. That way, one can create reproducible/privacy-enabled builds even in the presence of `rust-src` ; but would still get real file system paths in diagnostics for the regular local workflow. This would be the compiler's behavior until the RFC defines something explicit.

I'm personally in favor of the last option as it should provide a good temporary mitigation of the problem.

**Comment by cbeuw** [comment] 2021-08-23 10:18
> there would be no way to opt-out of that short of uninstalling the rust-src component

@michaelwoerister user would have to manually supply a `--remap-path-prefix` that remaps the sysroot to something of their preference.

We could provide a special codeword in `--remap-path-prefix` which expands to the sysroot path, similar to the CWD proposal here https://github.com/rust-lang/compiler-team/issues/450

**Closed** 2021-09-03 03:13 UTC
Labels: P-medium, T-compiler, regression-from-stable-to-stable, C-bug

**Comment by michaelwoerister** [comment] 2021-09-06 08:00
https://github.com/rust-lang/rust/pull/88363 has landed and is on nightly. @nicholasbishop, @jsgf, @dtolnay, can you all take a look if it fixes your respective use cases?

**Comment by nicholasbishop** [comment] 2021-09-07 19:49
Looks good to me, thanks for the fix!
