### ISSUE TITLE
using rustbuild breaks compiling against system llvm when linked against libffi

### ISSUE THREAD

**Issue by hussamT** [rust-lang/rust#39880] opened 2017-02-16 10:52 UTC
I get the following error:
rust  undefined reference to `ffi_type_double'

There was a workaround that helped in the past but it doesn't anymore.

**Comment by nagisa** [comment] 2017-02-16 11:43
That’s most likely because your system `llvm-config` does not print `-lffi` in

```
$ llvm-config --system-libs
-lrt -ldl -lcurses -lpthread -lz -lm -lffi
```

**Comment by hussamT** [comment] 2017-02-16 12:03
I will try that now. Than you.

**Comment by kyrias** [comment] 2017-03-03 09:44
Yeah, I'm currently trying to build rust 1.15.1 for Arch, and I've tried both the old setting `RUSTFLAGS` to `-C link-args=-lffi` approach, and making llvm-config a wrapper script that adds it, but neither works anymore.  Not sure how it decides the `CFLAGS` it uses now.

**Comment by hussamT** [comment] 2017-03-03 12:18
I noticed Fedora is using --disable-rustbuild http://pkgs.fedoraproject.org/cgit/rpms/rust.git/tree/rust.spec#n260

**Comment by kyrias** [comment] 2017-03-03 12:27
Just discovered that it's a regression in llvm(-config).  On e.g. debian it is included in llvm-config, and if I download the Arch package for the same llvm version it also outputs `-lffi` there, so seems to have been a regression between LLVM 3.5 and 3.9.  Would need help from some LLVM people to figure out what changed though.

**Comment by cuviper** [comment] 2017-03-03 17:54
> I noticed Fedora is using --disable-rustbuild http://pkgs.fedoraproject.org/cgit/rpms/rust.git/tree/rust.spec#n260 which retains the old behavior.

For 1.15, yes, as I haven't transitioned yet.  I hope to use rustbuild for 1.16.

Fedora doesn't normally use static linking, but it's an option, and you can see my ffi workaround here:
http://pkgs.fedoraproject.org/cgit/rpms/rust.git/tree/rust.spec#n233

I still think `llvm-config --link-static --system-libs` ought to output `-lffi` itself though.  It was mentioned in https://github.com/rust-lang/rust/issues/34486#issuecomment-257139448 that llvm-config has a FIXME about this, which is still there in the latest sources.

**Comment by Mark-Simulacrum** [comment] 2017-09-15 01:27
I take it this isn't a problem on Rust's side, so closing. If I'm wrong please let us know!

**Closed by Mark-Simulacrum** 2017-09-15 01:27 UTC
Labels: A-rustbuild, C-bug

**Comment by tmccombs** [comment] 2019-03-16 07:17
is there an llvm issue open for this?
