### ISSUE TITLE
`proc_macro::SourceFile::path()` returns a non-public type

### ISSUE THREAD

**Issue by mystor** [rust-lang/rust#47077] opened 2017-12-30 19:18 UTC
This function currently returns a `syntax_pos::FileName`, which is not exported from the `proc_macro` crate. 

A good solution may be to export a `struct FileName(syntax_pos::FileName)` object which implements `Display`.

cc @jseyfried

**Comment by dtolnay** [comment] 2018-04-29 19:58
Still a problem. [`proc_macro::SourceFile::path`](https://doc.rust-lang.org/nightly/proc_macro/struct.SourceFile.html#method.path)

**Comment by abonander** [comment] 2018-04-30 06:05
Caused by https://github.com/rust-lang/rust/commit/d732da813bac73d2c81caddd06df3df3d9609e3d

**Comment by inquisitivecrystal** [comment] 2021-07-22 05:52
I believe that this was fixed by #52552.

**Closed** 2021-07-22 05:55 UTC
Labels: A-macros-2.0, C-enhancement, T-libs-api
