### ISSUE TITLE
Const generic ICE: constant in type had an ignored error: TooGeneric

### ISSUE THREAD

**Issue by qwerty19106** [rust-lang/rust#66962] opened 2019-12-02 15:17 UTC
Environment:
```
note: rustc 1.41.0-nightly (4007d4ef2 2019-12-01) running on x86_64-unknown-linux-gnu
note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin
```

The code:
```
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
struct Config {
    arr_size: usize
}

struct B<const CFG: Config> {
    arr: [u8; {CFG.arr_size}]
}

fn main() {
}
```
gives ICE:
```
error: internal compiler error: constant in type had an ignored error: TooGeneric
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=65de0456c6982ba362efa1fbc8b0446b)

**Comment by Centril** [comment] 2019-12-03 04:56
Reproduces without the feature gate enabled.

**Comment by hellow554** [comment] 2019-12-03 08:22
It is noteworthy (and probably a bug too), that it only works if you use `#[derive(PartialEq, Eq)]`.

My code below does ICE on stable, but not on nightly, but emits an error:

```rust
#![feature(const_generics)]

struct Config(usize);

impl std::cmp::Eq for Config {}
impl std::cmp::PartialEq for Config {
    fn eq(&self, _: &Self) -> bool { false }
}

struct B<const CFG: Config> {
    arr: [u8; {CFG.0}]
}

fn main() {}
```

```text
error[E0741]: the types of const generic parameters must derive `PartialEq` and `Eq`
  --> src/main.rs:10:21
   |
10 | struct B<const CFG: Config> {
   |                     ^^^^^^ `Config` doesn't derive both `PartialEq` and `Eq`
```

-----

The ICE seems to come from a `match` inside the `eq` method. This code does ICE:

```rust
#![feature(const_generics)]

struct Config(usize);

impl std::cmp::Par
impl std::cmp::PartialEq for Config {
    fn eq(&self, _: &Self) -> bool {
        match self {
            _ => false
        }
    }
}

struct B<const CFG: Config> {
    arr: [u8; {CFG.0}]
}

fn main() {}
```

**Comment by slightlyoutofphase** [comment] 2019-12-03 17:25
Just for the sake of maybe helping to drill down the bug by nature of comparison, here's an example of similar code that's somewhat more complex but that interestingly _does_ work fine:

    #![allow(incomplete_features)]
    #![feature(const_fn)]
    #![feature(const_generics)]
    #![feature(const_if_match)]
    
    use std::fmt::{self, Debug, Formatter};
    
    struct CFG<const OPT_A: char, const OPT_B: bool> {}
    
    impl<const OPT_A: char, const OPT_B: bool> CFG<OPT_A, OPT_B> {
        const LEN: usize = match OPT_A {
            'A' => 64,
            'B' => 128,
            'C' => 256,
            'D' => 512,
            _ => 512,
        };
        const IS_TRUE: bool = OPT_B;
    }
    
    struct CFGBuilder<const A: char, const B: bool> {}
    
    type Options = (usize, bool);
    
    impl<const A: char, const B: bool> CFGBuilder<A, B> {
        const RESULT: Options = (CFG::<A, B>::LEN, CFG::<A, B>::IS_TRUE);
    }
    
    const DEFAULT_CFG: Options = CFGBuilder::<'A', true>::RESULT;
    const ALT_CFG: Options = CFGBuilder::<'B', false>::RESULT;
    
    struct B1 {
        arr: [u8; DEFAULT_CFG.0],
    }
    
    impl B1 {
        const CAP: usize = DEFAULT_CFG.0;
        const IS_TRUE: bool = DEFAULT_CFG.1;
        const fn new(val: u8) -> Self {
            Self {
                arr: [val; Self::CAP],
            }
        }
    }
    
    impl Debug for B1 {
        fn fmt(&self, f: &mut Formatter) -> fmt::Result {
            write!(f, "B1 IS_TRUE: {}\n{:?}", Self::IS_TRUE, unsafe {
                // Not actually unsafe, because it can't go out of bounds.
                self.arr.get_unchecked(..)
            })
        }
    }
    
    struct B2 {
        arr: [u8; ALT_CFG.0],
    }
    
    impl B2 {
        const CAP: usize = ALT_CFG.0;
        const IS_TRUE: bool = ALT_CFG.1;
        const fn new(val: u8) -> Self {
            Self {
                arr: [val; Self::CAP],
            }
        }
    }
    
    impl Debug for B2 {
        fn fmt(&self, f: &mut Formatter) -> fmt::Result {
            write!(f, "B2 IS_TRUE: {}\n{:?}", Self::IS_TRUE, unsafe {
                // Not actually unsafe, because it can't go out of bounds.
                self.arr.get_unchecked(..)
            })
        }
    }
    
    const ONE: B1 = B1::new(1);
    const TWO: B2 = B2::new(2);
    
    fn main() {
        println!("{:?}", ONE);
        println!("{:?}", TWO);
    }

**Comment by osa1** [comment] 2019-12-04 07:44
The backtrace is not too useful as it shows the reporting code rather than the code that raised the error. I did a little bit of debugging and I think `rustc_mir::interpret::operand` raises the error in this code:

```rust
    crate fn eval_const_to_op(
        &self,
        val: &'tcx ty::Const<'tcx>,
        layout: Option<TyLayout<'tcx>>,
    ) -> InterpResult<'tcx, OpTy<'tcx, M::PointerTag>> {
        let tag_scalar = |scalar| match scalar {
            Scalar::Ptr(ptr) => Scalar::Ptr(self.tag_static_base_pointer(ptr)),
            Scalar::Raw { data, size } => Scalar::Raw { data, size },
        };
        // Early-return cases.
        let val_val = match val.val {
            ty::ConstKind::Param(_) =>
                throw_inval!(TooGeneric), // <--------------------
            ...
```

**Comment by osa1** [comment] 2019-12-04 07:51
Adding some debug prints, I see that the `ParamConst` is something like `ParamConst { index: 0, name: "CFG" }`. Is there a way to resolve this "CFG" to the actual const `Config` struct so that I can select the field?

**Comment by eddyb** [comment] 2019-12-19 15:50
`TooGeneric` shouldn't really cause an error, it should be silent and simply leave the constant unevaluated (until a later situation in which the const parameter is replaced with an actual value).

**Comment by sebastiencs** [comment] 2019-12-23 14:32
I have the same panic `constant in type had an ignored error: TooGeneric` but with a different code:

```rust
struct MyStruct<const SIZE: usize> {
    bitfield: [usize; SIZE / 64]
}
```

Backtrace:
```
error: internal compiler error: constant in type had an ignored error: TooGeneric
  --> src/test_const.rs:27:5
   |
27 |     bitfields: [usize; SIZE / 64]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:347:17
stack backtrace:
   0:     0x7f6ac90892e4 - backtrace::backtrace::libunwind::trace::he29c1eef22099f24
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7f6ac90892e4 - backtrace::backtrace::trace_unsynchronized::ha36b80e516498eae
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7f6ac90892e4 - std::sys_common::backtrace::_print_fmt::hb70f67b9deb9591b
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x7f6ac90892e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf6ea30c21a2e486e
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7f6ac90c176c - core::fmt::write::hfd06ed55ab82c6c1
                               at src/libcore/fmt/mod.rs:1057
   5:     0x7f6ac907d717 - std::io::Write::write_fmt::h8c600764d032d6f3
                               at src/libstd/io/mod.rs:1426
   6:     0x7f6ac908d78e - std::sys_common::backtrace::_print::h2ccb403bde2af48d
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7f6ac908d78e - std::sys_common::backtrace::print::hde1d2976285bb6d7
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7f6ac908d78e - std::panicking::default_hook::{{closure}}::h5f8dbaddde324745
                               at src/libstd/panicking.rs:193
   9:     0x7f6ac908d481 - std::panicking::default_hook::h353c9f7e159c6169
                               at src/libstd/panicking.rs:210
  10:     0x7f6ac9610b23 - rustc_driver::report_ice::h1312d9253207031a
  11:     0x7f6abb348b88 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::hd34b6e757f60fcb9
                               at /rustc/9b98af84c4aa66392236fff59c86da2130d46d46/src/liballoc/boxed.rs:1036
  12:     0x7f6abb34f204 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h78bcbeb91c63709f
                               at /rustc/9b98af84c4aa66392236fff59c86da2130d46d46/src/libproc_macro/bridge/client.rs:305
  13:     0x7f6ac908df40 - std::panicking::rust_panic_with_hook::h2106ae29891f5da1
                               at src/libstd/panicking.rs:475
  14:     0x7f6acb7a5a05 - std::panicking::begin_panic::h93fe85ac6a0e3437
  15:     0x7f6acb7d691c - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h55cf2ea02b0742fd
  16:     0x7f6ac95dd986 - core::ptr::real_drop_in_place::h392a37dbd6e46951
  17:     0x7f6ac95f46f3 - core::ptr::real_drop_in_place::hea055a76d2f2dbd0
  18:     0x7f6ac95f417c - core::ptr::real_drop_in_place::he6fe08f725a1ff55
  19:     0x7f6ac95d7044 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h73894470eb0ec5df
  20:     0x7f6ac95b46b2 - std::thread::local::LocalKey<T>::with::h495fb06c01f6023a
  21:     0x7f6ac95a620e - scoped_tls::ScopedKey<T>::set::h472b490a2228a3c9
  22:     0x7f6ac962e264 - syntax::with_globals::hc9ab57e6f4791057
  23:     0x7f6ac95a69a0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65d85a8a2939bf16
  24:     0x7f6ac909ea6a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  25:     0x7f6ac95beeb9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h603ca4a944c4f841
  26:     0x7f6ac906ef6f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h480530d6a186f051
                               at /rustc/9b98af84c4aa66392236fff59c86da2130d46d46/src/liballoc/boxed.rs:1022
  27:     0x7f6ac909d490 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h45ae71d65ffe3628
                               at /rustc/9b98af84c4aa66392236fff59c86da2130d46d46/src/liballoc/boxed.rs:1022
  28:     0x7f6ac909d490 - std::sys_common::thread::start_thread::h9d0d044e93c04e51
                               at src/libstd/sys_common/thread.rs:13
  29:     0x7f6ac909d490 - std::sys::unix::thread::Thread::new::thread_start::h59144ad61d4caeef
                               at src/libstd/sys/unix/thread.rs:80
  30:     0x7f6ac8fe64c0 - start_thread
  31:     0x7f6ac8f04553 - __clone
  32:                0x0 - <unknown>
```

rustc version: `rustc 1.42.0-nightly (9b98af84c 2019-12-22) running on x86_64-unknown-linux-gnu`

**Comment by djugei** [comment] 2019-12-31 14:31
i built a [minimal test case](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=246ff15491b86ac5686459b214bdf8f3). it seems like doing _any_ calculation in array sizes causes that ICE.

**Comment by djugei** [comment] 2019-12-31 14:58
as a workaround you can do the calculations outside of the array and encapsulate the array in a different type, like in this [example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=df763e486c50ec636c87c3fcc5a858bb).

**Comment by eddyb** [comment] 2020-01-18 15:09
This is a legitimate error, but it shouldn't have been ICEing. I'm sorry I didn't notice it earlier!

The reason the original example shouldn't compile is because it can cause post-monomorphization const-eval failures!

The `struct` should have a bound which effectively forces all use sites to evaluate the constant and ensure it has no errors (but this is not yet implemented - the syntax `where [u8; {CFG.arr_size}]:,` should do this).

**Comment by eddyb** [comment] 2020-01-18 15:23
Given the lack of const expression unification, this is what it would take:
```rust
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
struct Config {
    arr_size: usize
}

type CfgArray<T, const CFG: Config> = [T; {CFG.arr_size}];

struct B<const CFG: Config>
    where CfgArray<u8, CFG>:,
{
    arr: CfgArray<u8, CFG>,
}
```
Note that the `where` bound doesn't need to use `u8` as the element type, as long as it passes the same `Config` parameter as the actual use in a field type.

This might require coordination with @rust-lang/wg-traits to make sure the WF semantics here are coherent with the rest of WF.

**Comment by djugei** [comment] 2020-01-20 13:03
Thanks for showing a way forward @eddyb
The previous pull request did in fact not resolve the issue for me.

So we need to construct a wrapper around the arr_size? i don't quite understand why/what that does. Is there somewhere to read up on it? just to avoid cargo culting.

**Comment by eddyb** [comment] 2020-01-20 14:44
@djugei So there's a few things going on:
* we have a bit of a messaging issue (cc @varkor @yodaldevoid), you never have to write braces around the array length expression, `[T; N]` works just as well (the braces aren't for const generic params specifically, they're for expressions in paths, e.g. `Foo<T, {N+M}>`)
* `[T; N]` (or `[T; {N}]`, same thing) and `Foo<T, {N}>`, where `N` is a const generic parameter name, will *not* rely on a const expression, but let the typesystem see that a const parameter is used there, so `CfgArray` in your example isn't useful
* OTOH, an expression like `N+1` or `CFG.arr_size` is currently treated opaquely (because we have no algorithm to unify two such expressions), so if you write it twice, the compiler doesn't know it's the same one, hence using a type alias to write it only once

**Comment by varkor** [comment] 2020-01-20 15:23
This issue should be addressed in https://github.com/rust-lang/rust/pull/68388 (though the code in the original post will not be accepted).

**Comment by djugei** [comment] 2020-01-20 16:20
@eddyb
so its kinda like my [workaround example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=df763e486c50ec636c87c3fcc5a858bb)?
the rules around when you need to be using brackets are kinda... [inconsistent](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c82cc4b3821f0d323b4dcbc29f7cb198), but thats probably a different issue all together.

**Comment by varkor** [comment] 2020-01-20 16:27
> the rules around when you need to be using brackets are kinda... inconsistent, but thats probably a different issue all together.

Yes, this is https://github.com/rust-lang/rust/issues/68257. These examples should all work (and hopefully will do soon!).

**Closed** 2020-01-23 03:47 UTC
Labels: A-const-generics, F-const_generics, I-ICE, I-nominated, P-medium, T-compiler, glacier
