### ISSUE TITLE
Missing API documentation for sort_by

### ISSUE THREAD

**Issue by rudib** [rust-lang/rust#24115] opened 2015-04-06 16:51 UTC
1.0.0-beta web API docs don't contain the ```sort_by``` slice method, even though it is documented in the sources:

https://github.com/rust-lang/rust/blob/9edbf42a342ced7357fe5ec225975f214d872fbc/src/libcollections/slice.rs#L245

It certainly can't be found when searching in the docs search widget, but it might be hidden somewhere in the std module docs, but I can't find it. Looks like a documentation build bug?

**Comment by steveklabnik** [comment] 2015-04-06 16:52
This is a duplicate of another bug, yes. primitive impls don't show up in rustdoc right now

**Closed by steveklabnik** 2015-04-06 16:52 UTC
