### ISSUE TITLE
stabilize #[alloc_error_handler]

### ISSUE THREAD

**Issue by eloraiby** [rust-lang/rust#74797] opened 2020-07-26 23:19 UTC
Currently, nostd+custom alloc is failing to build on stable with the following message:

```
error[E0658]: the `#[alloc_error_handler]` attribute is an experimental feature
  --> src/main.rs:46:1
   |
46 | #[alloc_error_handler]
   | ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #51540 <https://github.com/rust-lang/rust/issues/51540> for more information

error: aborting due to previous error
```
Please fix this ASAP since liballoc is now stable.

**Comment by jonas-schievink** [comment] 2020-07-26 23:28
duplicate of https://github.com/rust-lang/rust/issues/66740

**Closed by jonas-schievink** 2020-07-26 23:28 UTC

**Comment by eloraiby** [comment] 2020-07-26 23:39
You didn't not provide a timeline

**Comment by jonas-schievink** [comment] 2020-07-26 23:40
I am under no obligation to do so.

**Comment by eloraiby** [comment] 2020-07-27 00:23
@alexcrichton
