### ISSUE TITLE
rust-gdb can't show string/&str variables

### ISSUE THREAD

**Issue by Right2Left** [rust-lang/rust#69764] opened 2020-03-06 09:18 UTC
(gdb) p host
Python Exception <type 'exceptions.TypeError'> Could not convert Python object: <gdb.Field object at 0x7f09e53ed1e0>.: 
$1 = 
(gdb) p host_v6
Python Exception <type 'exceptions.TypeError'> Could not convert Python object: <gdb.Field object at 0x7f09e53ed1b0>.: 
$2 = 
(gdb) p a
$3 = 95
(gdb)

set python print-stack full

then:
(gdb) p host
$1 = Traceback (most recent call last):
  File "/usr/local/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 265, in to_string
    (length, data_ptr) = rustpp.extract_length_and_ptr_from_slice(self.__val)
  File "/usr/local/lib/rustlib/etc/debugger_pretty_printers_common.py", line 373, in extract_length_and_ptr_from_slice
    length = slice_val.get_child_at_index(length_field_index).as_integer()
  File "/usr/local/lib/rustlib/etc/gdb_rust_pretty_printing.py", line 77, in get_child_at_index
    child = GdbValue(self.gdb_val[gdb_field])
TypeError: Could not convert Python object: <gdb.Field object at 0x7fcc3cfaf1e0>.

(gdb)

demo code:

```rust
fn main() {
    let a = 100 - 10 / 2;
    info!("result:{}", a);

    let host = "[3e80:a178:b18f:c5dd:250:56ff:fe9d:a351]";
    let host_v6 = host.replace('[', "").replace(']', "");
}
```

**Comment by Right2Left** [comment] 2020-03-06 09:20
if i just use gdb, not rust-gdb, it's normal:

(gdb) p host
$1 = {data_ptr = 0x5555556b5867 "[3e80:a178:b18f:c5dd:250:56ff:fe9d:a351]src/main.rsparse ipv6 error.3e80", length = 40}
(gdb) p host_v6
$2 = {vec = {buf = {ptr = {pointer = 0x55555594c6c0 "3e80:a178:b18f:c5dd:250:56ff:fe9d:a351", _marker = {<No data fields>}}, cap = 38, a = {<No data fields>}}, len = 38}}
(gdb) p a
$3 = 95
(gdb)

**Comment by contrun** [comment] 2020-03-10 02:58
Can not reproduce. I am using the `rust-gdb` bundled with `rustup-1.21.1`. rust-gdb version is GNU gdb (GDB) 8.3.1. My rustc is
```
rustc 1.43.0-nightly (75cf41afb 2020-03-04)
binary: rustc
commit-hash: 75cf41afb468152611212271bae026948cd3ba46
commit-date: 2020-03-04
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

The code I ran is
```
fn main() {
    let a = 100 - 10 / 2;
    let host = "[3e80:a178:b18f:c5dd:250:56ff:fe9d:a351]";
    let host_v6 = host.replace('[', "").replace(']', "");
    println!("{}, {}, {}", a, host, host_v6);
}
```

**Comment by Enselic** [comment] 2023-12-10 14:23
Triage: I can't reproduce either. Closing as not reproducible.

<details>

<summary>Working gdb session</summary>

```
$ rustc -g main.rs




martin @ martins-dator 2023-12-10 15:20:49
/home/martin/src/bin/src
30a7fdf wip  2023-12-10T14:28:29+01:00  master  U
$ rust-gdb --args main
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from main...
(gdb) b main.rs:4
Breakpoint 1 at 0xbb05: file main.rs, line 4.
(gdb) r
Starting program: /home/martin/src/bin/src/main
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main::main () at main.rs:4
4           let host_v6 = host.replace('[', "").replace(']', "");
(gdb) p host
$1 = "[3e80:a178:b18f:c5dd:250:56ff:fe9d:a351]"
(gdb) n
5           println!("{}, {}, {}", a, host, host_v6);
(gdb) p host_v6
$2 = "3e80:a178:b18f:c5dd:250:56ff:fe9d:a351"
(gdb) ptype host_v6
type = struct alloc::string::String {
  vec: alloc::vec::Vec<u8, alloc::alloc::Global>,
}
(gdb) ptype host
type = struct &str {
  data_ptr: *mut u8,
  length: usize,
}
(gdb)
```

</details>

**Closed by Enselic** 2023-12-10 14:23 UTC
Labels: T-compiler, C-bug
