### ISSUE TITLE
Since 2023-04-21 (`fec9adcdb`), nightly fails to compile `geo` crate in release mode with [E0275]

### ISSUE THREAD

**Issue by tim3z** [rust-lang/rust#110776] opened 2023-04-24 17:08 UTC
I tried the following:

```bash
git clone https://github.com/georust/geo.git && cd geo # main or latest release (tag 0.24.1) both have the issue
rustup run nightly-2023-04-22 cargo build --release
```

I expected to see this happen: It compiles 🤷‍♂️ 

Instead, I get the following compiler error:

```
error[E0275]: overflow evaluating the requirement `[closure@geo/src/algorithm/map_coords.rs:855:69: 855:72]: Fn<(geo_types::Coord<T>,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`geo`)
  = note: required for `&[closure@geo/src/algorithm/map_coords.rs:855:69: 855:72]` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&[closure@geo/src/algorithm/map_coords.rs:855:69: 855:72]` to implement `Fn<(geo_types::Coord<T>,)>`

For more information about this error, try `rustc --explain E0275`.
error: could not compile `geo` (lib) due to previous error
```

Adding the suggested `#![recursion_limit = "256"]` does not help. I checked up to `#![recursion_limit = "1024"]` but it started getting veeeery slow.

However, all of the following work just fine:

```bash
rustup run nightly-2023-04-22 cargo build # no --release
rustup run nightly-2023-04-21 cargo build # one day before
rustup run stable cargo build --release # stable 1.69
```

**Comment by saethlin** [comment] 2023-04-25 03:52
It looks like the code in question: https://github.com/georust/geo/blob/c31ac453ac6565cf17f9d983ab16a892b8b1e451/geo/src/algorithm/map_coords.rs#L851 is trivially recursive?

I think this has the same root cause as https://github.com/rust-lang/rust/issues/110475 if nothing else it looks incredibly similar.

**Comment by tim3z** [comment] 2023-04-25 06:49
Yeah, seems pretty much like exactly that.

**Comment by jyn514** [comment] 2023-04-26 15:34
I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/110475.

**Closed by jyn514** 2023-04-26 15:34 UTC
Labels: C-bug, E-needs-bisection
