### ISSUE TITLE
Function inlined despite inline(never)

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#105319] opened 2022-12-05 18:08 UTC
I tried this code:

[Godbolt](https://rust.godbolt.org/z/GfhbThTWP)
```rust
#[no_mangle]
#[inline(never)]
pub fn get_script() -> &'static str {
    "foo bar"
}

#[no_mangle]
pub extern "C" fn update() {
    unsafe { foo(get_script()) }
}

extern "C" {
    fn foo(x: &str);
}
```

I expected to see this happen: The function is not being inlined.

Instead, this happened: The function is inlined and the string is directly passed to foo.

```asm
update:
        i32.const       .L__unnamed_1
        i32.const       7
        call    foo
        end_function
```

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-pc-windows-msvc
release: 1.65.0
LLVM version: 15.0.0
```

This reproduces on fairly old versions of rustc and nightly as well.

**Comment by ChrisDenton** [comment] 2022-12-05 18:41
Despite the name, I don't think `inline(never)` actually guarantees never inlining. From [the reference](https://doc.rust-lang.org/reference/attributes/codegen.html#the-inline-attribute):

> `#[inline(never)]` *suggests* that an inline expansion should never be performed.

**Comment by erikdesjardins** [comment] 2022-12-06 04:43
Beyond that, there are other optimizations besides inlining that can delete function calls.

In this case, IPSCCP\* notices that `get_script` returns a constant, and replaces usages of its return value with that constant. Then, a later pass deletes the unused, side-effect-free call to `get_script`.

You can see this using using `-Cllvm-args="-print-changed"`, e.g. https://rust.godbolt.org/z/ro6e3WqeT

<sup>\* Interprocedural Sparse Conditional Constant Propagation</sup>

**Comment by jyn514** [comment] 2023-04-27 03:28
I'm going to close this as not a bug. The behavior here is unfortunate, but behaving as documented.

**Closed by jyn514** 2023-04-27 03:28 UTC
Labels: C-bug
