### ISSUE TITLE
Eliminate $crate in --pretty=expanded

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#38016] opened 2016-11-26 16:24 UTC
Similar to #37637 so cc @jseyfried.

**`cat src/main.rs`**

> ```rust
> fn main() {
>     println!("rust");
> }
> ```

**`rustc --pretty=expanded -Zunstable-options src/main.rs`**

> ```rust
> #![feature(prelude_import)]
> #![no_std]
> #[prelude_import]
> use std::prelude::v1::*;
> #[macro_use]
> extern crate std as std;
> fn main() {
>     $crate::io::_print(::std::fmt::Arguments::new_v1({
>                                                          static __STATIC_FMTSTR:
>                                                                 &'static [&'static str]
>                                                                 =
>                                                              &["rust\n"];
>                                                          __STATIC_FMTSTR
>                                                      },
>                                                      &match () {
>                                                           () => [],
>                                                       }));
> ```

The `$crate` prevents the expanded code from being parsed by rustfmt.

**`rustc --pretty=expanded -Zunstable-options src/main.rs | rustfmt`**

> ```
> error: expected expression, found `$`
>  --> stdin:8:5
>   |
> 8 |     $crate::io::_print(::std::fmt::Arguments::new_v1({
>   |     ^
> ```

This breaks [`cargo expand`](https://github.com/dtolnay/cargo-expand) which runs the code through rustfmt by default.

I think `--pretty=expanded` should produce valid Rust code which means either eliminate `$crate` like we did for #37637, or allow rustfmt to parse it.

**Comment by nagisa** [comment] 2016-11-26 17:30
Why are you relying on unstable features for, umm, stable tooling? `--pretty` et al by now are only used for debugging purposes and won’t be stabilised.

**Comment by bluss** [comment] 2016-11-26 17:36
I don't think expand can produce valid Rust code (how does it handle hygiene?)

**Comment by dtolnay** [comment] 2016-11-26 17:41
Before the `$crate` change, it produced syntactically valid Rust code even if the semantics were different in the case of hygiene collisions. This was useful for debugging purposes as @nagisa points out.

Since the `$crate` change, it produces syntactically invalid code which I consider a bug.

**Comment by jseyfried** [comment] 2016-12-21 07:13
Fixed in #38232 (https://github.com/rust-lang/rust/pull/38232#issuecomment-268453076).
After that lands, we will pretty-print `$crate::io::_print` as `::io::_print`.

**Comment by xiaoniu-578fa6bff964d005** [comment] 2019-01-20 09:41
`$crate` show up again!

`rustc +nightly-2018-06-13-x86_64-unknown-linux-gnu --pretty=expanded -Zunstable-options main.rs`
```
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;
fn main() {
    ::io::_print(::std::fmt::Arguments::new_v1(&["rust\n"],
                                               &match () { () => [], }));
}
```
`rustc +nightly --pretty=expanded -Zunstable-options main.rs`
```
#![feature(prelude_import)]
#![no_std]
#[prelude_import]
use ::std::prelude::v1::*;
#[macro_use]
extern crate std;
fn main() {
    {
        $crate::io::_print($crate::fmt::Arguments::new_v1(&["rust\n"],
                                                          &match () {
                                                               () => [],
                                                           }));
    };
}
```
`rustc +nightly --version`
```
rustc 1.33.0-nightly (0c0c58528 2019-01-19)
```

**Comment by petrochenkov** [comment] 2019-01-20 09:44
Caused by https://github.com/rust-lang/rust/pull/57155.
Reopening and assigning to myself.

**Comment by petrochenkov** [comment] 2019-01-26 14:45
Fixed in https://github.com/rust-lang/rust/pull/57915

**Closed** 2019-01-29 07:51 UTC
Labels: A-macros-1.2, C-bug, T-compiler
