### ISSUE TITLE
libstd gets rebuilt unconditionally

### ISSUE THREAD

**Issue by flo-l** [rust-lang/rust#33990] opened 2016-05-31 19:52 UTC
For reference, the [reddit thread](https://www.reddit.com/r/rust/comments/4l7l6x/how_do_you_compile_rustc/), where the discussion started.

### My goal
I want to hack on rustc. So I want to make a change, recompile as fast as possible and test the new binary with some input.rs.

### The Problem
```make``` rebuilds libstd even if it's unchanged. This takes ages and can't be skipped.

### How to reproduce
I'm on Fedora Linux 23, fully updated.

I started with a clone of the rust repo, in which I already compiled rustc more than once (so LLVM was already built etc.).

    git reset --hard 298730e   # this is the commit I used for this test
    git clean -df

```
./configure --enable-debug
```
[output](https://gist.github.com/flo-l/5071682c95af0d5320c7b153bf841732)

```
make rustc-stage1 NO_REBUILD=1
```

[output](https://gist.github.com/flo-l/32a9dff2816141733dc2c820d2d84a9d)
```
touch src/librustc_mir/lib.rs
```

```
make rustc-stage1 NO_REBUILD=1
```

[output](https://gist.github.com/flo-l/965e2bd30d84b52578fe5a4cbbb0fb99)

As you can see in the output of the second make command libstd, libcore etc. get rebuilt.

**Comment by flo-l** [comment] 2016-05-31 19:58
cc @alexcrichton

**Comment by alexcrichton** [comment] 2016-05-31 20:13
Ah sorry, I believe I have misunderstood! The rebuilding as part of the second make command is actually the stage 1 set of libraries. These are the ones which are produced by the stage0 artifacts. That is, the chain of dependencies is:

1. You modified src/librustc_mir/lib.rs
2. This file is a dependency of `x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_mir`
3. Transitively, that's a dependency of `x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc`, the final stage0 artifact.
4. That file is a dependency of `x86_64-unknown-linux-gnu/stage1/bin/rustc`, the stage1 compiler.

The stage1 compiler has changed (as part of librustc_mir changing), so its dependants need to be rebuilt as well. These include the stage1 libraries (e.g. libcore + libstd).

Does that make sense? I'm gonna close this as it's intended behavior, but I'll of course answer any questions you may have!

**Closed by alexcrichton** 2016-05-31 20:13 UTC

**Comment by flo-l** [comment] 2016-05-31 20:19
Ah ok I understand, thanks for clarifying!

As mentioned above I'd like to build just rustc with some changed I made. Which make target corresponds to that and where will the binary be?

**Comment by alexcrichton** [comment] 2016-05-31 20:27
If all you want is the compiler itself, then this should suffice:

```
make x86_64-unknown-linux-gnu/stage1/bin/rustc
```

There may be a more ergonomic way to type that, although I don't recall off the top of my head...

Note though that this compiler won't be too too useful as it won't have a standard library to link against.

**Comment by flo-l** [comment] 2016-05-31 20:42
That does what it should! Thank you so much! :grin: 

And about that libstd thing: Could the `--disable-inject-std-version` option of the configure script help?

**Comment by alexcrichton** [comment] 2016-05-31 20:46
Wow I had no idea that option even still existed... I think that's from an era long since passed and no longer actually does anything!

**Comment by flo-l** [comment] 2016-05-31 21:13
I just checked, `make x86_64-unknown-linux-gnu/stage1/bin/rustc` seems to work, the produced binary reuses the previously built libstd. :tada:

Thank you very much, I was fighting with this for days!

**Comment by alexcrichton** [comment] 2016-05-31 23:24
Glad I could help!
