### ISSUE TITLE
Box::new() performance regression between 1.18 and 1.19 beta

### ISSUE THREAD

**Issue by rom1v** [rust-lang/rust#42562] opened 2017-06-09 11:53 UTC
It seems there is a performance regression related to `Box::new()` between 1.18 and 1.19 beta.

```rust
use std::time::Instant;

fn main() {
    let timer = Instant::now();
    for _ in 0..100000 {
        Box::new([0; 1000]);
    }
    println!("{:?}", timer.elapsed());
}
```

In Release/Stable:
```
rustc 1.18.0 (03fc9d622 2017-06-06)

Duration { secs: 0, nanos: 107624 }
```

In Release/Beta, it's ~200× slower:
```
rustc 1.19.0-beta.1 (a87984118 2017-06-06)

Duration { secs: 0, nanos: 22355940 }
```

https://is.gd/AaDx3A

**Comment by crumblingstatue** [comment] 2017-06-09 11:58
I tested on nightly, it's about 140 times slower than 1.18 stable on my system.

**Comment by jonas-schievink** [comment] 2017-06-09 13:20
You're not measuring `Box::new`, you're measuring the compiler's ability to remove unnecessary allocations. For some reason 1.19+ isn't able to eliminate the allocations, while 1.18 is.

**Comment by wesleywiser** [comment] 2017-06-09 15:17
I think this is related https://github.com/rust-lang/rust/issues/24194#issuecomment-305546904

**Comment by jonas-schievink** [comment] 2017-06-09 15:32
Fix is https://github.com/rust-lang/rust/pull/42410

**Comment by joshlf** [comment] 2017-06-09 20:59
> You're not measuring `Box::new`, you're measuring the compiler's ability to remove unnecessary allocations. For some reason 1.19+ isn't able to eliminate the allocations, while 1.18 is.

You could use `test::black_box` to prevent this optimization to make sure that that's really the issue.

**Comment by nagisa** [comment] 2017-06-09 22:16
Closing as a duplicate of https://github.com/rust-lang/rust/issues/24194

**Closed by nagisa** 2017-06-09 22:16 UTC
Labels: I-slow
