### ISSUE TITLE
[Clippy] internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by Kibouo** [rust-lang/rust#48579] opened 2018-02-27 10:53 UTC
<short summary of the bug>

[I tried this code](https://github.com/Kibouo/particles/tree/8df6789cfba0726f644b76097239652ab59d5bbb)

Reproduce: clone repo, then in the root run `cargo clippy`

I expected to see this happen: clippy to run over my code

Instead, this happened: unexpected panic of compiler

```
bin: particles
   Compiling either v1.4.0
   Compiling winapi-build v0.1.1
   Compiling scopeguard v0.3.3
   Compiling bitflags v0.9.1
   Compiling lazy_static v1.0.0
   Compiling typenum v1.9.0
   Compiling matrixmultiply v0.1.14
   Compiling adler32 v1.0.2
   Compiling memoffset v0.2.1
   Compiling siphasher v0.2.2
   Compiling dtoa v0.4.2
   Compiling vulkano v0.7.2
   Compiling bitflags v1.0.1
   Compiling cfg-if v0.1.2
   Compiling cc v1.0.4
   Compiling libc v0.2.36
   Compiling rawpointer v0.1.0
   Compiling winapi v0.2.8
   Compiling lazy_static v0.2.11
   Compiling color_quant v1.0.0
   Compiling pkg-config v0.3.9
   Compiling serde v0.9.15
   Compiling quote v0.3.15
   Compiling unicode-xid v0.0.4
   Compiling lzw v0.10.0
   Compiling half v1.0.2
   Compiling crossbeam v0.3.2
   Compiling scoped_threadpool v0.1.8
   Compiling num-traits v0.2.0
   Compiling bitflags v0.7.0
   Compiling smallvec v0.4.4
   Compiling fnv v1.0.6
   Compiling nodrop v0.1.12
   Compiling rustc-serialize v0.3.24
   Compiling approx v0.1.1
   Compiling rayon-core v1.4.0
   Compiling itoa v0.3.4
   Compiling byteorder v1.2.1
   Compiling vk-sys v0.3.3
   Compiling kernel32-sys v0.2.2
   Compiling xml-rs v0.6.1
   Compiling inflate v0.3.4
   Compiling phf_shared v0.7.21
   Compiling crossbeam-utils v0.2.2
   Compiling rand v0.4.2
   Compiling shared_library v0.1.8
   Compiling num_cpus v1.8.0
   Compiling cmake v0.1.29
   Compiling x11-dl v2.17.2
   Compiling syn v0.10.8
   Compiling gif v0.9.2
   Compiling num-integer v0.1.36
   Compiling num-traits v0.1.43
   Compiling arrayvec v0.4.7
   Compiling deflate v0.7.17
   Compiling num-complex v0.1.42
   Compiling wayland-scanner v0.9.10
   Compiling phf v0.7.21
   Compiling rand v0.3.22
   Compiling glsl-to-spirv v0.1.4
   Compiling num-iter v0.1.35
   Compiling num-rational v0.1.42
   Compiling serde_json v0.9.10
   Compiling enum_primitive v0.1.1
   Compiling crossbeam-epoch v0.3.0
   Compiling alga v0.5.2
thread 'rustc' panicked at 'assertion failed: `(left != right)`
  left: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([<Self as linear::vector::EuclideanSpace>::Coordinates, <Self as linear::vector::EuclideanSpace>::Real]), item_def_id: DefId(2/0:893 ~ core[4840]::ops[0]::arith[0]::Mul[0]::Output[0]) }, <Self as linear::vector::EuclideanSpace>::Coordinates)))`,
 right: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([<Self as linear::vector::EuclideanSpace>::Coordinates, <Self as linear::vector::EuclideanSpace>::Real]), item_def_id: DefId(2/0:893 ~ core[4840]::ops[0]::arith[0]::Mul[0]::Output[0]) }, <Self as linear::vector::EuclideanSpace>::Coordinates)))`', librustc/traits/project.rs:146:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (bedbad611 2018-02-26) running on x86_64-unknown-linux-gnu

error: Could not compile `alga`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Meta

`rustc --version --verbose`: 
```
rustc 1.26.0-nightly (bedbad611 2018-02-26)
binary: rustc
commit-hash: bedbad61195d2eae69b43eca49c6d3e2aee8f208
commit-date: 2018-02-26
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

Backtrace:
```
stack backtrace:
   0:     0x7f8bc7824ff3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h92c858273beca9db
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f8bc781c534 - std::sys_common::backtrace::_print::h6cb1e7663c70c510
                               at libstd/sys_common/backtrace.rs:71
   2:     0x7f8bc7821c7d - std::panicking::default_hook::{{closure}}::h46fa0787be3918b6
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:206
   3:     0x7f8bc7821979 - std::panicking::default_hook::h7dddf112a45a90f8
                               at libstd/panicking.rs:222
   4:     0x7f8bc897aa5d - core::ops::function::Fn::call::h3cb97c4162eec9f6
   5:     0x7f8bc7822119 - std::panicking::rust_panic_with_hook::h42848144b6747469
                               at libstd/panicking.rs:401
   6:     0x7f8bc7821f02 - std::panicking::begin_panic_fmt::h14c37c5e3685a2bb
                               at libstd/panicking.rs:347
   7:     0x7f8bc8c8ca22 - rustc::traits::project::ProjectionTyCandidateSet::push_candidate::h2672d39becc9aba3
   8:     0x7f8bc8c91012 - rustc::traits::project::opt_normalize_projection_type::h1fb7b886d286337f
   9:     0x7f8bc8c8ff83 - rustc::traits::project::normalize_projection_type::hfdd96356f7e979d2
  10:     0x7f8bc8c8f86c - <rustc::traits::project::AssociatedTypeNormalizer<'a, 'b, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty::h27356651973a3854
  11:     0x7f8bc8d16e7a - rustc::ty::subst::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::Slice<rustc::ty::subst::Kind<'tcx>>>::super_fold_with::hcb4c12f430c98df5
  12:     0x7f8bc8d3ddee - rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for rustc::ty::Predicate<'tcx>>::super_fold_with::h81d9e56dd0820402
  13:     0x7f8bc8cbc4dc - rustc::traits::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for rustc::traits::Obligation<'tcx, O>>::super_fold_with::h4c9a7f60e6f745db
  14:     0x7f8bc8c8e432 - rustc::traits::project::normalize_with_depth::h3d391e0ed1f21835
  15:     0x7f8bc8d19e82 - rustc::ty::wf::WfPredicates::normalize::{{closure}}::hc5c71bc5bb70f84c
  16:     0x7f8bc8ade979 - <core::iter::FlattenCompat<I, U> as core::iter::iterator::Iterator>::next::h7b6fc964cbd4c975
  17:     0x7f8bc8967bc7 - <alloc::vec::Vec<T>>::extend_desugared::h4a9cc89317e1b0b9
  18:     0x7f8bc8ad4782 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h09c60980fbd8ae5d
  19:     0x7f8bc8d19c74 - rustc::ty::wf::predicate_obligations::h74ece49687a4a4e1
  20:     0x7f8bc936b593 - rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_where_clauses::h343cb02e7c27c865
  21:     0x7f8bc93638b3 - rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor::check_item_well_formed::hd49e4e9035d32eeb
  22:     0x7f8bc936c788 - <rustc_typeck::check::wfcheck::CheckTypeWellFormedVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'v>>::visit_item::h2fd643ee2fb8da76
  23:     0x7f8bc93d4a68 - rustc_typeck::check_crate::{{closure}}::h65bc6b2cde8fc8d8
  24:     0x7f8bc93d077c - rustc_typeck::check_crate::h6a4b56b529504aab
  25:     0x7f8bc9afbe99 - rustc::ty::context::TyCtxt::create_and_enter::hc45b3a73dd46ae96
  26:     0x7f8bc9b6073e - rustc_driver::driver::compile_input::h60b5346f3903c44c
  27:     0x7f8bc9b7ce8a - rustc_driver::run_compiler::h606ede5b4fb41a6e
  28:     0x55c351d39332 - std::sys_common::backtrace::__rust_begin_short_backtrace::h05349bd197cb4a29
  29:     0x55c351d3cffb - std::panicking::try::do_call::h4ff3a0b63aa97ca1
  30:     0x7f8bc783abde - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  31:     0x55c351d3cded - <F as alloc::boxed::FnBox<A>>::call_box::he296a72685a7aca0
  32:     0x7f8bc7831f9b - std::sys::unix::thread::Thread::new::thread_start::h15b68dbc19e967f4
                               at /checkout/src/liballoc/boxed.rs:793
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  33:     0x7f8bc759f08b - start_thread
  34:     0x7f8bc70bfe7e - __GI___clone
  35:                0x0 - <unknown>
```

**Comment by ishitatsuyuki** [comment] 2018-02-27 11:35
Duplicate of #48551

**Closed by ishitatsuyuki** 2018-02-27 11:35 UTC
