### ISSUE TITLE
extern crate idioms

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51544] opened 2018-06-14 00:35 UTC
@wycats encountered a problem where a `use some_crate` line is being rewritten to `use crate::some_crate`. We have a test case just for this but the test seems to work. Here is the branch:

https://github.com/wycats/glimmer/tree/niko-repro

**Comment by alexcrichton** [comment] 2018-08-24 21:40
We've had a lot of fixes since this was opened, so I'm gonna close this

**Closed by alexcrichton** 2018-08-24 21:40 UTC
Labels: A-rust-2018-preview

**Comment by wycats** [comment] 2018-08-27 16:53
@alexcrichton is this particular repro fixed?

**Comment by alexcrichton** [comment] 2018-08-27 17:51
@wycats there aren't any reproduction steps in this issue, when checked out that branch doesn't build because dependencies are out of date, it also doesn't build due to features having been removed, and once all fixed there's only normal expected warnings. 

In that sense... probably? It's hard to know because it's not clear to me what this was repro'ing in the first place

**Comment by wycats** [comment] 2018-08-27 18:37
Sweet!
