### ISSUE TITLE
if let compound statement

### ISSUE THREAD

**Issue by dfarnham** [rust-lang/rust#83504] opened 2021-03-26 02:44 UTC
### Code

```Rust
fn main() {
    let jobj = json::parse(r#"{ "config": [ { "label": { "active": true } } ] }"#).unwrap();

    for obj in jobj["config"].members() {
        for (k, v) in obj.entries().take(1) {
            if let json::JsonValue::Boolean(state) = v["active"] && true {
                if state {
                    println!("{}", k)
                }
            }
        }
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build
   Compiling bug v0.1.0 (/private/tmp/bug)
error[E0658]: `let` expressions in this position are experimental
 --> src/main.rs:6:16
  |
6 |             if let json::JsonValue::Boolean(state) = v["active"] && true {
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(44),
)', compiler/rustc_ast_lowering/src/lib.rs:714:17
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_ast_lowering::LoweringContext::lower_res::{{closure}}::{{closure}}
   3: rustc_ast_lowering::LoweringContext::lower_node_id_generic
   4: rustc_ast_lowering::path::<impl rustc_ast_lowering::LoweringContext>::lower_qpath
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if
   7: rustc_data_structures::stack::ensure_sufficient_stack
   8: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   9: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  10: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  11: rustc_arena::cold_path
  12: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_if
  13: rustc_data_structures::stack::ensure_sufficient_stack
  14: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  15: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  16: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  17: rustc_arena::cold_path
  18: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_for
  19: rustc_data_structures::stack::ensure_sufficient_stack
  20: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  21: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  22: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  23: rustc_arena::cold_path
  24: rustc_ast_lowering::expr::<impl rustc_ast_lowering::LoweringContext>::lower_expr_for
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  27: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  28: <smallvec::SmallVec<A> as core::iter::traits::collect::Extend<<A as smallvec::Array>::Item>>::extend
  29: rustc_arena::cold_path
  30: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_block_expr_opt
  31: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_fn_body_block
  32: rustc_ast_lowering::item::<impl rustc_ast_lowering::LoweringContext>::lower_item
  33: rustc_ast_lowering::LoweringContext::with_hir_id_owner
  34: <rustc_ast_lowering::item::ItemLowerer as rustc_ast::visit::Visitor>::visit_mod
  35: rustc_ast_lowering::lower_crate
  36: rustc_interface::passes::BoxedResolver::access::{{closure}}
  37: rustc_interface::passes::configure_and_expand::{{closure}}
  38: rustc_interface::passes::BoxedResolver::access
  39: rustc_interface::queries::Queries::lower_to_hir
  40: rustc_interface::queries::Queries::global_ctxt
  41: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  42: rustc_span::with_source_map
  43: rustc_interface::interface::create_compiler_and_run
  44: rustc_span::with_session_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0 (2fd73fabe 2021-03-23) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bug`

To learn more, run the command again with --verbose.
```

</p>
</details>

**Comment by osa1** [comment] 2021-03-26 08:39
Thanks for reporting. If I try this using this Cargo.toml:

```rust
[package]
name = "issue83504"
version = "0.1.0"
edition = "2018"

[dependencies]
json = "0.12.4"
```

and with current `master` branch (7637fd588bf), I get a different panic:

```
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/omer/rust/rust/compiler/rustc_serialize/src/leb128.rs:79:1
```

<details>

<summary>Backtrace</summary>

```
   0: rust_begin_unwind
             at /home/omer/rust/rust/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /home/omer/rust/rust/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /home/omer/rust/rust/library/core/src/panicking.rs:69:5
   3: rustc_serialize::leb128::read_usize_leb128
             at /home/omer/rust/rust/compiler/rustc_serialize/src/leb128.rs:61:28
   4: <rustc_serialize::opaque::Decoder as rustc_serialize::serialize::Decoder>::read_usize
             at /home/omer/rust/rust/compiler/rustc_serialize/src/opaque.rs:597:9
   5: rustc_metadata::rmeta::decoder::__ty_decoder_impl::<impl rustc_serialize::serialize::Decoder for rustc_metadata::rmeta::decoder::DecodeContext>::read_usize
             at /home/omer/rust/rust/compiler/rustc_middle/src/ty/codec.rs:399:17
   6: rustc_serialize::serialize::Decoder::read_enum_variant
             at /home/omer/rust/rust/compiler/rustc_serialize/src/serialize.rs:244:20
   7: rustc_session::config::_DERIVE_rustc_serialize_Decodable_D_FOR_SymbolManglingVersion::<impl rustc_serialize::serialize::Decodable<__D> for rustc_session::config::SymbolManglingVersion>::decode::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_session/src/config.rs:250:21
   8: rustc_serialize::serialize::Decoder::read_enum
             at /home/omer/rust/rust/compiler/rustc_serialize/src/serialize.rs:236:9
   9: rustc_session::config::_DERIVE_rustc_serialize_Decodable_D_FOR_SymbolManglingVersion::<impl rustc_serialize::serialize::Decodable<__D> for rustc_session::config::SymbolManglingVersion>::decode
             at /home/omer/rust/rust/compiler/rustc_session/src/config.rs:250:21
  10: core::ops::function::FnOnce::call_once
             at /home/omer/rust/rust/library/core/src/ops/function.rs:227:5
  11: rustc_serialize::serialize::Decoder::read_struct_field
             at /home/omer/rust/rust/compiler/rustc_serialize/src/serialize.rs:293:9
  12: rustc_metadata::rmeta::_DERIVE_rustc_serialize_Decodable_DecodeContext_a_tcx_FOR_CrateRoot::<impl rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext> for rustc_metadata::rmeta::CrateRoot>::decode::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_metadata/src/rmeta/mod.rs:199:29
  13: rustc_serialize::serialize::Decoder::read_struct
             at /home/omer/rust/rust/compiler/rustc_serialize/src/serialize.rs:280:9
  14: rustc_metadata::rmeta::_DERIVE_rustc_serialize_Decodable_DecodeContext_a_tcx_FOR_CrateRoot::<impl rustc_serialize::serialize::Decodable<rustc_metadata::rmeta::decoder::DecodeContext> for rustc_metadata::rmeta::CrateRoot>::decode
             at /home/omer/rust/rust/compiler/rustc_metadata/src/rmeta/mod.rs:199:29
  15: rustc_metadata::rmeta::decoder::<impl rustc_metadata::rmeta::Lazy<T>>::decode
             at /home/omer/rust/rust/compiler/rustc_metadata/src/rmeta/decoder.rs:231:9
  16: rustc_metadata::rmeta::decoder::MetadataBlob::get_root
             at /home/omer/rust/rust/compiler/rustc_metadata/src/rmeta/decoder.rs:600:9
  17: rustc_metadata::locator::CrateLocator::crate_matches
             at /home/omer/rust/rust/compiler/rustc_metadata/src/locator.rs:621:20
  18: rustc_metadata::locator::CrateLocator::extract_one
             at /home/omer/rust/rust/compiler/rustc_metadata/src/locator.rs:545:42
  19: rustc_metadata::locator::CrateLocator::extract_lib
             at /home/omer/rust/rust/compiler/rustc_metadata/src/locator.rs:476:19
  20: rustc_metadata::locator::CrateLocator::find_commandline_library
             at /home/omer/rust/rust/compiler/rustc_metadata/src/locator.rs:711:12
  21: rustc_metadata::locator::CrateLocator::maybe_load_library_crate
             at /home/omer/rust/rust/compiler/rustc_metadata/src/locator.rs:360:20
  22: rustc_metadata::creader::CrateLoader::load
             at /home/omer/rust/rust/compiler/rustc_metadata/src/creader.rs:554:29
  23: rustc_metadata::creader::CrateLoader::maybe_resolve_crate
             at /home/omer/rust/rust/compiler/rustc_metadata/src/creader.rs:525:19
  24: rustc_metadata::creader::CrateLoader::resolve_crate
             at /home/omer/rust/rust/compiler/rustc_metadata/src/creader.rs:484:9
  25: rustc_metadata::creader::CrateLoader::process_path_extern
             at /home/omer/rust/rust/compiler/rustc_metadata/src/creader.rs:988:20
  26: rustc_resolve::Resolver::extern_prelude_get::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:3233:21
  27: core::option::Option<T>::and_then
             at /home/omer/rust/rust/library/core/src/option.rs:724:24
  28: rustc_resolve::Resolver::extern_prelude_get
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:3225:9
  29: rustc_resolve::Resolver::resolve_ident_in_lexical_scope
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:1944:40
  30: rustc_resolve::Resolver::resolve_path_with_ribs::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:2330:27
  31: rustc_resolve::Resolver::resolve_path_with_ribs
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:2354:33
  32: rustc_resolve::late::LateResolutionVisitor::resolve_path
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:743:9
  33: rustc_resolve::late::LateResolutionVisitor::resolve_qpath
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2105:28
  34: rustc_resolve::late::LateResolutionVisitor::resolve_qpath_anywhere
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2016:23
  35: rustc_resolve::late::LateResolutionVisitor::smart_resolve_path_fragment
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:1902:33
  36: rustc_resolve::late::LateResolutionVisitor::smart_resolve_path
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:1785:9
  37: rustc_resolve::late::LateResolutionVisitor::resolve_expr
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2251:17
  38: rustc_resolve::late::LateResolutionVisitor::resolve_expr
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2329:17
  39: rustc_resolve::late::LateResolutionVisitor::resolve_expr
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2321:17
  40: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_expr
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:448:9
  41: rustc_resolve::late::LateResolutionVisitor::resolve_local
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:1415:9
  42: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_local
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:461:9
  43: rustc_ast::visit::Visitor::visit_stmt
             at /home/omer/rust/rust/compiler/rustc_ast/src/visit.rs:106:9
  44: rustc_resolve::late::LateResolutionVisitor::resolve_block
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2214:13
  45: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_block
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:441:9
  46: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:541:45
  47: rustc_resolve::late::LateResolutionVisitor::with_label_rib
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:1131:9
  48: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:530:13
  49: rustc_resolve::late::LateResolutionVisitor::with_rib
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:780:19
  50: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_fn
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:528:9
  51: rustc_ast::visit::walk_item
             at /home/omer/rust/rust/compiler/rustc_ast/src/visit.rs:291:13
  52: rustc_resolve::late::LateResolutionVisitor::resolve_item::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:945:21
  53: rustc_resolve::late::LateResolutionVisitor::with_generic_param_rib
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:1123:9
  54: rustc_resolve::late::LateResolutionVisitor::resolve_item
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:944:17
  55: <rustc_resolve::late::LateResolutionVisitor as rustc_ast::visit::Visitor>::visit_item
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:433:9
  56: rustc_ast::visit::walk_crate
             at /home/omer/rust/rust/compiler/rustc_ast/src/visit.rs:238:5
  57: rustc_resolve::late::<impl rustc_resolve::Resolver>::late_resolve_crate
             at /home/omer/rust/rust/compiler/rustc_resolve/src/late.rs:2429:9
  58: rustc_resolve::Resolver::resolve_crate::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:1444:56
  59: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/omer/rust/rust/compiler/rustc_data_structures/src/profiling.rs:573:9
  60: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/omer/rust/rust/compiler/rustc_session/src/utils.rs:10:9
  61: rustc_resolve::Resolver::resolve_crate::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:1444:13
  62: rustc_data_structures::profiling::VerboseTimingGuard::run
             at /home/omer/rust/rust/compiler/rustc_data_structures/src/profiling.rs:573:9
  63: rustc_session::utils::<impl rustc_session::session::Session>::time
             at /home/omer/rust/rust/compiler/rustc_session/src/utils.rs:10:9
  64: rustc_resolve::Resolver::resolve_crate
             at /home/omer/rust/rust/compiler/rustc_resolve/src/lib.rs:1441:9
  65: rustc_interface::passes::configure_and_expand_inner
             at /home/omer/rust/rust/compiler/rustc_interface/src/passes.rs:412:5
  66: rustc_interface::passes::configure_and_expand::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/passes.rs:120:19
  67: alloc::boxed::<impl core::ops::generator::Generator<R> for core::pin::Pin<alloc::boxed::Box<G,A>>>::resume
             at /home/omer/rust/rust/library/alloc/src/boxed.rs:1668:9
  68: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
             at /home/omer/rust/rust/compiler/rustc_data_structures/src/box_region.rs:44:26
  69: rustc_interface::passes::BoxedResolver::new
             at /home/omer/rust/rust/compiler/rustc_data_structures/src/box_region.rs:101:41
  70: rustc_interface::passes::configure_and_expand
             at /home/omer/rust/rust/compiler/rustc_interface/src/passes.rs:116:30
  71: rustc_interface::queries::Queries::expansion::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/queries.rs:183:13
  72: rustc_interface::queries::Query<T>::compute
             at /home/omer/rust/rust/compiler/rustc_interface/src/queries.rs:40:28
  73: rustc_interface::queries::Queries::expansion
             at /home/omer/rust/rust/compiler/rustc_interface/src/queries.rs:179:9
  74: rustc_driver::run_compiler::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_driver/src/lib.rs:386:13
  75: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
             at /home/omer/rust/rust/compiler/rustc_interface/src/queries.rs:422:19
  76: rustc_driver::run_compiler::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_driver/src/lib.rs:334:22
  77: rustc_interface::interface::create_compiler_and_run::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/interface.rs:208:13
  78: rustc_span::with_source_map
             at /home/omer/rust/rust/compiler/rustc_span/src/lib.rs:788:5
  79: rustc_interface::interface::create_compiler_and_run
             at /home/omer/rust/rust/compiler/rustc_interface/src/interface.rs:202:5
  80: rustc_interface::interface::run_compiler::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/interface.rs:224:12
  81: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/util.rs:155:13
  82: scoped_tls::ScopedKey<T>::set
             at /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  83: rustc_span::with_session_globals
             at /home/omer/rust/rust/compiler/rustc_span/src/lib.rs:105:5
  84: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/util.rs:153:9
  85: rustc_interface::util::scoped_thread::{{closure}}
             at /home/omer/rust/rust/compiler/rustc_interface/src/util.rs:128:24
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `issue83504`

To learn more, run the command again with --verbose.
```

</details>

@rustbot label +E-needs-mcve

**Comment by osa1** [comment] 2021-03-26 08:42
I can't reproduce this with current master (7637fd588bf).

```
$ cargo +stage1 build
   Compiling issue83504 v0.1.0 (/home/omer/rust/issue83504)
error[E0658]: `let` expressions in this position are experimental
 --> src/main.rs:6:16
  |
6 |             if let json::JsonValue::Boolean(state) = v["active"] && true {
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
  = help: add `#![feature(let_chains)]` to the crate attributes to enable
  = help: you can write `matches!(<expr>, <pattern>)` instead of `let <pattern> = <expr>`

error: `let` expressions are not supported here
 --> src/main.rs:6:16
  |
6 |             if let json::JsonValue::Boolean(state) = v["active"] && true {
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: only supported directly without parentheses in conditions of `if`- and `while`-expressions, as well as in `let` chains within parentheses

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `issue83504`

To learn more, run the command again with --verbose.
```

My Cargo.toml:

```toml
[package]
name = "issue83504"
version = "0.1.0"
edition = "2018"

[dependencies]
json = "0.12.4"
```

@dfarnham could you share the `Cargo.toml` you used?

**Comment by osa1** [comment] 2021-03-26 08:48
Smaller repro, without deps:

```rust
use std::collections::HashMap;

enum JsonValue {
    Boolean(bool),
    Other,
}

fn main() {
    let v: HashMap<String, JsonValue> = Default::default();
    if let JsonValue::Boolean(state) = v["active"] && true {
        if state {
            println!("{}", k)
        }
    }
}
```

Panics with 1.51 as in the original report. Does not panic with nightly.

@rustbot label -E-needs-mcve

**Comment by SNCPlay42** [comment] 2021-03-26 16:20
Duplicate of  #82290, which is fixed on nightly.

**Comment by JohnTitor** [comment] 2021-04-05 14:01
Triage: Indeed this should be a duplicate of #82290, and #82308 has a regression test that should cover the issue, closing as fixed/duplicate.

**Closed by JohnTitor** 2021-04-05 14:01 UTC
Labels: C-bug, I-ICE, T-compiler
