### ISSUE TITLE
Cargo test can't find doc tests when `--format=json` option is presented

### ISSUE THREAD

**Issue by mchernyavsky** [rust-lang/rust#102957] opened 2022-10-12 10:13 UTC
### Code

I tried this command:

```bash
$ cargo test
```

on this code (`lib.rs`):

```rust
/// ```
/// ();
/// ```
fn _foo() {}
```

The result is:

```bash
   Compiling sandbox v0.1.0 (/Users/Mikhail.Chernyavsky/CLionProjects/sandbox)
    Finished test [unoptimized + debuginfo] target(s) in 0.13s
     Running unittests src/lib.rs (target/debug/deps/sandbox-c45f1323f0f92a37)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests sandbox

running 1 test
test src/lib.rs - _foo (line 1) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.17s
```

As expected, cargo found 1 doc test. But when I add `--format=json` option to the command line:

```bash
$ cargo test -- -Z unstable-options --format=json
```

I expected to see this:

```bash
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/lib.rs (target/debug/deps/sandbox-c45f1323f0f92a37)
{ "type": "suite", "event": "started", "test_count": 0 }
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.00002886 }
   Doc-tests sandbox
{ "type": "suite", "event": "started", "test_count": 1 }
{ "type": "test", "event": "started", "name": "src/lib.rs - _foo (line 1)" }
{ "type": "test", "name": "src/lib.rs - _foo (line 1)", "event": "ok" }
{ "type": "suite", "event": "ok", "passed": 1, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.171079421 }
```

Instead, I got this:

```bash
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/lib.rs (target/debug/deps/sandbox-c45f1323f0f92a37)
{ "type": "suite", "event": "started", "test_count": 0 }
{ "type": "suite", "event": "ok", "passed": 0, "failed": 0, "ignored": 0, "measured": 0, "filtered_out": 0, "exec_time": 0.000027173 }
```

### Version it worked on

It most recently worked on: `nightly-2022-10-02`

### Version with regression

`nightly-2022-10-08`

`rustc --version --verbose`:
```
rustc 1.63.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.63.0-dev
LLVM version: 14.0.4
```

**Comment by ehuss** [comment] 2022-10-12 11:04
Thanks for the report! This was a regression in cargo. There was a brief window between 10-05 and 10-08 with this issue. If you update to the latest nightly, it should work.

Closing as a duplicate of https://github.com/rust-lang/cargo/issues/11191. Feel free to comment if the latest nightly doesn't work.

**Closed by ehuss** 2022-10-12 11:04 UTC
Labels: C-bug, I-prioritize, regression-untriaged
