### ISSUE TITLE
error: incremental compilation: could not create session directory lock file: Input/output error (os error 5)

### ISSUE THREAD

**Issue by allenzhao64** [rust-lang/rust#76251] opened 2020-09-02 15:25 UTC
I tried this code:

```
$ cargo build
error: incremental compilation: could not create session directory lock file: Input/output error (os error 5)

thread 'rustc' panicked at 'trying to get session directory from `IncrCompSession`: NotInitialized', src/librustc_session/session.rs:840:48
stack backtrace:
   Compiling term v0.6.1
   Compiling rand v0.6.5
   0:     0x7f53f5fcd0d5 - backtrace::backtrace::libunwind::trace::h396c07d2071b43af
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x7f53f5fcd0d5 - backtrace::backtrace::trace_unsynchronized::h7aa0e4bb23d9c158
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x7f53f5fcd0d5 - std::sys_common::backtrace::_print_fmt::hd15ac5d4adcd355b
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x7f53f5fcd0d5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec5354be8ccc3ecc
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x7f53f600a7ec - core::fmt::write::h3d34909eeb4f225b
                               at src/libcore/fmt/mod.rs:1076
   5:     0x7f53f5fbf7e3 - std::io::Write::write_fmt::h1da287b3de55ed16
                               at src/libstd/io/mod.rs:1537
   6:     0x7f53f5fd20f0 - std::sys_common::backtrace::_print::h4d206838e1ace354
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x7f53f5fd20f0 - std::sys_common::backtrace::print::h1f778e9940ee5977
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x7f53f5fd20f0 - std::panicking::default_hook::{{closure}}::h704403a56cbf5783
                               at src/libstd/panicking.rs:198
   9:     0x7f53f5fd1e3c - std::panicking::default_hook::ha4567a10dec4ef8d
                               at src/libstd/panicking.rs:218
  10:     0x7f53f66fc5c3 - rustc_driver::report_ice::h162d93c732cfa263
  11:     0x7f53f5fd279c - std::panicking::rust_panic_with_hook::h88a1f16ec8a7bb20
                               at src/libstd/panicking.rs:490
  12:     0x7f53f5fd237b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  13:     0x7f53f5fd22eb - std::panicking::begin_panic_fmt::ha3ac96e620978458
                               at src/libstd/panicking.rs:342
  14:     0x7f53f91d81d3 - rustc_session::session::Session::incr_comp_session_dir::h15dc136056f816e8
  15:     0x7f53f7f768e2 - rustc_incremental::persist::fs::garbage_collect_session_directories::hc4ddf55a33fd9839
  16:     0x7f53f690dc10 - rustc_session::utils::<impl rustc_session::session::Session>::time::h559d22a69e3f6c89
  17:     0x7f53f68af60d - rustc_interface::queries::Queries::register_plugins::h618f60f3b86c029d
  18:     0x7f53f66c01f8 - rustc_interface::interface::run_compiler_in_existing_thread_pool::h71a70a633e2a927e
  19:     0x7f53f670b3bf - rustc_ast::attr::with_globals::hb004aafbc16d2612
  20:     0x7f53f671040e - std::sys_common::backtrace::__rust_begin_short_backtrace::h547683b640c7a8c7
  21:     0x7f53f66c3c2e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcb850442add305d8
  22:     0x7f53f5fe20fa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hcf205bcf9b46c587
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  23:     0x7f53f5fe20fa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2d53e2246128f5d8
                               at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/liballoc/boxed.rs:1076
  24:     0x7f53f5fe20fa - std::sys::unix::thread::Thread::new::thread_start::h3b6d8a0cd87a87c6
                               at src/libstd/sys/unix/thread.rs:87
  25:     0x7f53f5d49aa1 - start_thread
  26:     0x7f53f568aaad - __clone
  27:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0 (5c1f21c3b 2020-07-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

### Meta

`rustc --version --verbose`:
```
linux-2018.gtisoft.com:/Ydir/savesets/v2022/g/lib/gtchannel/gtchannel_core # rustc --version --verbose
rustc 1.45.0 (5c1f21c3b 2020-07-13)
binary: rustc
commit-hash: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
commit-date: 2020-07-13
host: x86_64-unknown-linux-gnu
release: 1.45.0
LLVM version: 10.0

```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by allenzhao64** [comment] 2020-09-02 15:26
some other observation:

The `cargo build`  works only when using a local device path. 

`cargo build --release` works fine,

The file is hosted on a NFS device

**Comment by ms140569** [comment] 2020-12-29 19:59
I'm still facing this issue when compiling anything hosted on my SAMBA/SMB Fileserver (rather than NFS) 

This is: 
Mac OSX 10.14.6
rustc 1.48.0 (7eac88abb 2020-11-16)

Stacktrace below:

```
   Compiling cynon v0.0.1 (/Volumes/server/data/Matthias/prj/rust/cynon)
     Running `rustc --crate-name build_script_build --edition=2018 build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f8228d0fe8773068 -C extra-filename=-f8228d0fe8773068 --out-dir /Volumes/server/data/Matthias/prj/rust/cynon/target/debug/build/cynon-f8228d0fe8773068 -C incremental=/Volumes/server/data/Matthias/prj/rust/cynon/target/debug/incremental -L dependency=/Volumes/server/data/Matthias/prj/rust/cynon/target/debug/deps --extern prost_build=/Volumes/server/data/Matthias/prj/rust/cynon/target/debug/deps/libprost_build-0de83129d3e4f190.rlib`
error: incremental compilation: could not create session directory lock file: Operation not supported (os error 45)

thread 'rustc' panicked at 'trying to get session directory from `IncrCompSession`: NotInitialized', compiler/rustc_session/src/session.rs:874:48
stack backtrace:
   0:        0x10981baa4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcfc48256a5ab8835
   1:        0x109882590 - core::fmt::write::haf3903118f694c48
   2:        0x10980d0a6 - std::io::Write::write_fmt::h7385463ac87804ed
   3:        0x10982046f - std::panicking::default_hook::{{closure}}::h91bd4c58cf71392b
   4:        0x10982013d - std::panicking::default_hook::h7bd29c87df967048
   5:        0x10eb0bc73 - rustc_driver::report_ice::h36110b17656cf994
   6:        0x109820b9e - std::panicking::rust_panic_with_hook::hae2b05f08a320721
   7:        0x1098206fb - std::panicking::begin_panic_handler::{{closure}}::h72d68d3a77e0b718
   8:        0x10981bf18 - std::sys_common::backtrace::__rust_end_short_backtrace::h7c5e286792f94edb
   9:        0x1098206ba - _rust_begin_unwind
  10:        0x1098a6e4b - std::panicking::begin_panic_fmt::h6826a3ebe3a95a51
  11:        0x113069e39 - rustc_session::session::Session::incr_comp_session_dir::h9e4df312765624b0
  12:        0x111fd4c20 - rustc_incremental::persist::fs::garbage_collect_session_directories::hc278153e85e5a69e
  13:        0x10ecd51e5 - rustc_session::utils::<impl rustc_session::session::Session>::time::hfb85c7a36ca241c4
  14:        0x10ed15384 - rustc_interface::passes::register_plugins::hcbb989c71900c709
  15:        0x10ed48eb8 - rustc_interface::queries::Queries::register_plugins::hbe269a7365ea56fb
  16:        0x10eb4a093 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::heacbf49337f5fb9d
  17:        0x10eb27321 - rustc_span::with_source_map::h3927afb6bcf6a169
  18:        0x10eb457c9 - scoped_tls::ScopedKey<T>::set::h5608e7cc9397961b
  19:        0x10eb4d644 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9b82f31f81e95856
  20:        0x10eae05bc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5baa2aca5ae17340
  21:        0x10982eb7d - std::sys::unix::thread::Thread::new::thread_start::he3e6719579180a65
  22:     0x7fff5a5cd2eb - __pthread_body
  23:     0x7fff5a5d0249 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.48.0 (7eac88abb 2020-11-16) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: aborting due to previous error

error: could not compile `cynon`

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build --edition=2018 build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=f8228d0fe8773068 -C extra-filename=-f8228d0fe8773068 --out-dir /Volumes/server/data/Matthias/prj/rust/cynon/target/debug/build/cynon-f8228d0fe8773068 -C incremental=/Volumes/server/data/Matthias/prj/rust/cynon/target/debug/incremental -L dependency=/Volumes/server/data/Matthias/prj/rust/cynon/target/debug/deps --extern prost_build=/Volumes/server/data/Matthias/prj/rust/cynon/target/debug/deps/libprost_build-0de83129d3e4f190.rlib` (exit code: 101)
```

The source for the panic is:
````
 871     pub fn incr_comp_session_dir(&self) -> cell::Ref<'_, PathBuf> {
 872         let incr_comp_session = self.incr_comp_session.borrow();
 873         cell::Ref::map(incr_comp_session, |incr_comp_session| match *incr_comp_session {
 874             IncrCompSession::NotInitialized => panic!(
 875                 "trying to get session directory from `IncrCompSession`: {:?}",
 876                 *incr_comp_session,
 877             ),
 878             IncrCompSession::Active { ref session_directory, .. }
 879             | IncrCompSession::Finalized { ref session_directory }
 880             | IncrCompSession::InvalidBecauseOfErrors { ref session_directory } => {
 881                 session_directory
 882             }
 883         })
 884     }
````

**Comment by ehuss** [comment] 2021-05-29 22:36
#85698 has changed it so that rustc does not panic in this situation, but it will still generate an error.

I'm going to close this as a duplicate of #49773 to consolidate the issues related to session locking.

**Closed by ehuss** 2021-05-29 22:36 UTC
Labels: A-incr-comp, C-bug, P-medium
