### ISSUE TITLE
ICE: uninterned StableCrateId: StableCrateId(6127172549132048186)

### ISSUE THREAD

**Issue by mu001999** [rust-lang/rust#118088] opened 2023-11-20 12:09 UTC
### Code

I am using `git bisect` to find error.

Firstly `./x.py build` on d55487d7e98, and then `./x.py build` on 34bc5716b53 without `./x.py clean`.

### Meta

`rustc --version --verbose`:
```
1.73.0-beta.1 (680cdf816 2023-08-21)
```

### Error output

See the attached file.

[rustc-ice-2023-11-20T11:59:22.923739Z-3687.txt](https://github.com/rust-lang/rust/files/13413795/rustc-ice-2023-11-20T11.59.22.923739Z-3687.txt)

**Comment by mu001999** [comment] 2023-11-20 12:25
Got `uninterned StableCrateId: StableCrateId(11946360728779904751)` again when `./x.py build` on 1516ca1bc01 (previously `./x.py build` on 34bc5716b53).
[rustc-ice-2023-11-20T12:21:36.356428Z-22412.txt](https://github.com/rust-lang/rust/files/13414381/rustc-ice-2023-11-20T12.21.36.356428Z-22412.txt)

**Comment by saethlin** [comment] 2023-11-20 15:40
If you're bisecting to try to figure out what rustc commit introduced the bug, you should use https://crates.io/crates/cargo-bisect-rustc which will bisect using the CI artifacts, so you don't have to recompile the compiler N times.

**Comment by mu001999** [comment] 2023-11-20 17:22
> If you're bisecting to try to figure out what rustc commit introduced the bug, you should use https://crates.io/crates/cargo-bisect-rustc which will bisect using the CI artifacts, so you don't have to recompile the compiler N times.

Got it! Thanks :)

**Comment by apiraino** [comment] 2023-11-20 17:52
@mu001999 based on [a really quick search](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+uninterned+StableCrateId%3A+StableCrateId), I *think* this could be a duplicate of an already reported issue caused by incremental compilation.

If you have a chance to confirm my suspicion, that would be helpful. thanks!

**Comment by mu001999** [comment] 2023-11-21 01:11
> @mu001999 based on [a really quick search](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+uninterned+StableCrateId%3A+StableCrateId), I _think_ this could be a duplicate of an already reported issue caused by incremental compilation.
> 
> If you have a chance to confirm my suspicion, that would be helpful. thanks!

I think it's a duplicate of #115835

**Comment by apiraino** [comment] 2023-11-21 08:49
Ok, thanks! I think we can close this and follow the conversation there

**Closed by apiraino** 2023-11-21 08:49 UTC
Labels: I-ICE, T-compiler, regression-from-stable-to-beta, C-bug, I-prioritize
