### ISSUE TITLE
On POSIX remove_file ignores read_only permission

### ISSUE THREAD

**Issue by timthelion** [rust-lang/rust#110159] opened 2023-04-10 20:20 UTC
```

/*
It seems that `remove_file` ignores permissions on Linux. If a file is read only, it should error out, not remove it.
*/

use std::fs::File;
use std::io::Write;
use std::fs::remove_file;
use std::fs::metadata;
use std::fs::Permissions;
use std::os::unix::fs::PermissionsExt;

fn main() {
    let mut file = File::create("test.txt").unwrap();
    file.write_all(b"Hello, world!").unwrap();
    println!("Is file read only? {:?}", metadata("test.txt").unwrap().permissions().readonly());
    file.set_permissions(std::fs::Permissions::from_mode(0o444)).unwrap();
    println!("Is file read only? {:?}", metadata("test.txt").unwrap().permissions().readonly());
    remove_file("test.txt").unwrap();
    println!("Does file exist? {:?}", metadata("test.txt").is_ok());
}
```

```
[nix-shell:~/pu/gradesta/manager/src/ageing_cellar]$ ./remove_file_ignores_permissions
Is file read only? false
Is file read only? true
Does file exist? false
```

**Comment by zachs18** [comment] 2023-04-10 21:18
AFAIK on POSIX, the relevant permissions to delete a file is based on the parent directory's permissions; the file's permissions are not relevant. (e.g. see https://stackoverflow.com/a/54622747/5142683 )

Therefore, I think that this behavior is consistent with the documentation (which lists that `remove_dir` will return an error if "The user lacks permissions to remove the file") and is not a bug. (And if this behavior *was* changed, some alternate way to remove files would need to be added that didn't perform this additional check.)

**Comment by jyn514** [comment] 2023-04-11 03:24
I'm going to close this as not a bug.

**Closed by jyn514** 2023-04-11 03:24 UTC
