### ISSUE TITLE
macro parser should back out of failed nonterminal parsing

### ISSUE THREAD

**Issue by paulstansifer** [rust-lang/rust#3232] opened 2012-08-20 22:03 UTC
Currently, the following macro argument grammar will not successfully parse anything, complaining of a "local ambiguity":

     $( $t:ty )* #

The problem is that if it were to use the Rust parser to try to parse a type and fail, the whole task would be killed. This is easy to fix after that problem is resolved. There are two options:

1. Break parsing into a separate task, and see whether it survives. However, parse.rs requires a `parse_sess`, which is mutable state, and can't be shared. So the second option is probably more doable:
2. Allow the parser to safely return instead of killing the task. This works much like the Error monad. Ordinarily, this would require a lot of tedious wrapping and unwrapping, but we have a macro system! It should be relatively easy to make a notation like Haskell's `do`, and the parser would be able to stay in the standard imperative style.

**Comment by steveklabnik** [comment] 2015-06-29 17:47
Given that this is mentioned in https://github.com/rust-lang/rfcs/issues/440, I'm going to be closing as 'not a bug' at this time, anyway. If we decide to improve macros, this is something that'd be nice to fix, for sure, but that RFC issue will be where that happens.

**Closed by steveklabnik** 2015-06-29 17:47 UTC
Labels: A-parser, A-syntaxext, I-wrong, P-low
