### ISSUE TITLE
Enable --remap-path-prefix for absolute paths by default

### ISSUE THREAD

**Issue by mzji** [rust-lang/rust#40552] opened 2017-03-15 18:30 UTC
According to #40374 , a part of private information is leaked by the path string living in the compiled binaries. To protect privacy and help debugging, I think we can let rustc to mangle the path. Here is my solution:

Basically, we can hide the 'insignificant' part of the path (which usually contains some private and/or unrelated info), leave 'significant' part untouched. Then what is the 'significant' part of a path? Here is an example: Assume that we have a project `foobar` which is in user's home directory (here I use a windows path, on *nix things work similarly):
```
C:\Users\username\Documents\foobar
```
In this case, the useful part is the crate name and the part after the crate name, i.e.
```
\foobar\lib.rs
```
Assuming we have a mod called 'somemod', then after mangling, the new path looks like:
```
[crate]\foobar\somemod\mod.rs
```
which not only saves the relatitionship information between sources files, but also protects the privacy of the user (since no more user name or aboslute path exists) !

The next question is how to process all paths under this rule. From what I know, all compiled code of a crate comes from 4 sources:
* crates.io or mirrors of crates.io, or some independent 3rd party repo, in which the code is cached and lives in the cargo cache directory
* remote git repositories
* local filesystem
* the crate itself (which may locate at any place)

We could specify different root names for these sources to indicate their origin:
* For code from crates.io or mirrors, the root name is `[crates.io]`. Example:
`C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.8\` will be mangled to `[crate.io]\winapi-0.2.8\`
* For code from remote git repository, the root name is `[username@git server name]`. Example: `https://github.com/rust-lang/rust` will be manged to `[rust-lang@github.com]/rust`
* For code from local filesystem, the root name is `[local]`. Example: `D:\workspaces\foobarng\` will be mangled to `[local]\foobarng\`
* For code from the crate itself, the root name is `crate`. Example: `C:\Users\username\Documents\foobar\` will be mangled to `[crate]\foobar\`

And for helping debuggers, all paths in debugging information won't be modified. Thus, users still know where the debugging code is, and won't worry about leaking privacy (just need stripping out debugging information before packaging on *nix, or not distributing .pdb files on windows).

**Comment by jmesmon** [comment] 2017-03-15 21:18
Related to #38322 & #39130 (which are for debuginfo). Likely makes sense to use the same mapping mechanism for filenames in strings too.

**Comment by mzji** [comment] 2017-03-15 21:37
We may need to record path mappings in a file if we want to process paths in debug information too.

**Comment by michaelwoerister** [comment] 2018-08-10 12:30
> Related to #38322 & #39130 (which are for debuginfo). Likely makes sense to use the same mapping mechanism for filenames in panics too.

`--remap-path-prefix` will also remap panic messages.

**Comment by mzji** [comment] 2018-08-10 14:37
Seems like we now have a working and stable solution. Closed.

**Comment by Boscop** [comment] 2018-08-11 20:32
So what's the current solution to not include the path in the exe (when building with cargo)?

**Comment by michaelwoerister** [comment] 2018-08-13 11:52
Try something like `RUSTFLAGS=--remap-path-prefix=<your-src-dir>=src cargo build`.

**Comment by michaelwoerister** [comment] 2018-08-14 08:31
I think this would need an RFC to come up with a solid solution that doesn't break debugging (which relies on these paths being contained in debuginfo). cc @rust-lang/core

**Comment by Boscop** [comment] 2018-09-03 14:14
@michaelwoerister But it should be stripped automatically from --release builds!

**Comment by michaelwoerister** [comment] 2018-09-03 14:54
An RFC would need to cover both debug and release builds.

**Comment by oxygencolony** [comment] 2020-09-15 14:39
> 
> 
> Try something like `RUSTFLAGS=--remap-path-prefix=<your-src-dir>=src cargo build`.

@michaelwoerister this didnt work for me and a username and full path was still present. and yes i also used the `--release` flag.  i also second @Boscop in that this should be automatic for release builds. why does the rfc need to include debug when we are talking about release specifically? @jimmycuadra is also right normal users shouldnt have to know this exists or be expected to manually specify the opts all the time since its so obscure.

if it helps you including user ids like this violates gdpr https://gdpr.eu/eu-gdpr-personal-data/ so this should be addressed by the rust team. in 2020 people care about privacy and this can be put off like https://github.com/rust-lang/mdBook/issues/847

cc @sneak who might also have some words about this

**Comment by dns2utf8** [comment] 2020-09-15 16:22
To be honest, I expected that release binaries do not contain information like this. Would this be an option to cut the string in these cases?

**Comment by oxygencolony** [comment] 2020-09-15 18:12
> 
> 
> To be honest, I expected that release binaries do not contain information like this. Would this be an option to cut the string in these cases?

@dns2utf8 

not sure if part of the message got dropped. what is the option you are suggesting? the provided RUSTFLAGS dont actually work. it seems the rust team thinks this is acceptable for release binaries for some reason. perhaps more attention on the issue may help given the push for privacy in 2020

**Comment by sneak** [comment] 2020-09-16 21:33
It seems to me that two different people building two identical programs on different systems should receive the same output binary regardless of the name in `$USER` or the string in `$HOME`, for all build types (but especially release).

I'm not going to weigh in on the privacy issue (I think that if you're privacy conscious, `$USER` should be `anonymous` or `user` or something already), just the principal of least surprise: what I would expect, not knowing the tooling, is that the same thing built on different systems would result in the same output.

This probably means stripping any mention of local environment, build time, and file paths before the root/prefix of the build.

**Comment by mindv0rtex** [comment] 2021-01-01 01:00
I really enjoy using Rust for personal side projects. It made me a better C++ developer. I'm excited about stabilized const generics to be able to speed up my linear algebra code.
This issue though prevents me from recommending Rust for closed source development to my colleagues.

**Comment by michaelwoerister** [comment] 2021-01-11 17:39
I think this might be more of an issue for the @rust-lang/core team rather than the @rust-lang/compiler team to discuss.

**Comment by unpavedmop** [comment] 2021-02-12 15:27
im with others. cant recommend rust with this and https://github.com/rust-lang/rust/issues/75263 why is @rust-lang/core ignoring this? seems people are concerned and dont have right skills, yet, to work on compiler or need help

**Comment by ssokolow** [comment] 2021-02-12 16:53
@unpavedmop The Rust developers only have so much time and a large portion of the user base either don't care or work around it by building release artifacts in Docker containers or on a CI service, so they (rightly) conclude that, barring more contributors showing up, it's more important to work on things that *don't* have such a simple workaround.

(For example, the long-awaited `min_const_generics` feature that got declared stable in `nightly` on December 27th and is currently making its way to `stable` channel.)

**Comment by unpavedmop** [comment] 2021-02-12 17:49
workaround doesnt work or isnt portable tho. guess im switching to a language who cares about privacy

**Comment by ssokolow** [comment] 2021-02-12 17:51
@unpavedmop Whatever you need to do. No programming language is the best tool for *every* job.

**Comment by chemsaf3** [comment] 2021-03-28 22:11
came to report tthe same

> 
> 
> Try something like `RUSTFLAGS=--remap-path-prefix=<your-src-dir>=src cargo build`.

this didnt work for me, user still in binary, and not flexible to use wildcard for src path

> 
> 
> @michaelwoerister But it should be stripped automatically from --release builds!

+1

**Comment by alercah** [comment] 2021-03-29 01:55
I was linked this issue from Reddit, and I got interested as personally having good privacy-preserving defaults is important to me. I spoke informally with some colleagues, and it sounds like:

- This particular issue is fundamentally about the default behaviour of the compiler in absence of controlling flags. It's a request to change that behaviour.
- If the `--remap-path-prefix` flag is not working, that needs to be a separate issue thread.
- Because the exact scope and nature of a solution is unclear, an RFC is required. It would be for the compiler and/or Cargo teams to handle depending on what exactly is proposed.
- It is worth engaging with the teams (especially cargo) on Zulip to figure out what they would like to see in such an RFC.

I'd love to see that happen, but I'm not personally in a position to follow up much on this at the moment.

**Comment by chemsaf3** [comment] 2021-04-03 14:24
@rust-lang/core & @rust-lang/compiler any chance of official comment on this? seems here and in reddit there is significant user interested in it being fixed. workarounds dont work, and using ci is not a solution as same issue is present there, even if different user name

@alercah also suggest rust team input on this which is absent. i dont think its reasonable to force community to fix this as many wont have nessesary compiler knowledge to do so. some maybe even new to rust and want to see a fix but cant help due to skills lacking

**Comment by recatek** [comment] 2021-04-03 17:48
This is a significant footgun for those just learning Rust, without extensive technical backgrounds. Windows explicitly prompts you to use your real name as your username, and includes that as part of your path, so it's a reasonable expectation that newer users of Rust will have a username containing personal information. Rust tutorializes users to build on their own machine by opening a terminal window and typing "cargo build". Doing these two things as-directed will create an unsafe binary by default -- safe code maybe, but not a safe user. If Rust intends to be a welcome and inviting first-language, something core to the Rust book and community, expecting them to protect themselves by pouring over docs and github issues and rfcs to find `--remap-path-prefix` or even understand what that means isn't the responsible way to go about this.

**Comment by jyn514** [comment] 2021-04-12 13:22
@recatek If you think symbols should be omitted by default, I'd recommend opening an RFC (see the instructions in https://github.com/rust-lang/rfcs/#readme). It should address at least the following drawbacks:

- Debugging with gdb/lldb/whatever windows uses should still work - AFAIK, these all require absolute paths. It sounds like there are some ideas for doing this in https://github.com/rust-lang/rust/issues/40552#issuecomment-809012730.
- Should the paths be relative to the workspace root or to the crate root? If it's relative to the crate, this will be regression for people using IDEs, because "jump to source" will no longer work for panic messages: https://github.com/rust-lang/rust/issues/47355. If it's relative to the workspace, cargo needs to support that somehow.
- How will the compiler know all the paths it should remap? Should it remap only the source directory? All of (the source directory, CARGO_HOME, and RUSTUP_HOME)? How will it know what those other values are - does it need cargo changes?
- All the other issues mentioned in https://github.com/rust-lang/rust/issues/40552#issuecomment-809012730.

I'm not a member of the compiler or core teams, but I'd speculate the reason they haven't responded is because they aren't stakeholders: their names are already public, so this feature doesn't help them. It would be great to have the RFC come from someone who plans to use this feature, not from a team member on behalf of someone else.

**Comment by chemsaf3** [comment] 2021-04-13 19:53
> 
> 
> @recatek If you think symbols should be omitted by default, I'd recommend opening an RFC (see the instructions in https://github.com/rust-lang/rfcs/#readme). It should address at least the following drawbacks:
> 
>     * Debugging with gdb/lldb/whatever windows uses should still work - AFAIK, these all require absolute paths. It sounds like there are some ideas for doing this in [#40552 (comment)](https://github.com/rust-lang/rust/issues/40552#issuecomment-809012730).
> 
>     * Should the paths be relative to the workspace root or to the crate root? If it's relative to the crate, this will be regression for people using IDEs, because "jump to source" will no longer work for panic messages: #47355. If it's relative to the workspace, cargo needs to support that somehow.
> 
>     * How will the compiler know all the paths it should remap? Should it remap only the source directory? All of (the source directory, CARGO_HOME, and RUSTUP_HOME)? How will it know what those other values are - does it need cargo changes?
> 
>     * All the other issues mentioned in [#40552 (comment)](https://github.com/rust-lang/rust/issues/40552#issuecomment-809012730).
> 
> 
> I'm not a member of the compiler or core teams, but I'd speculate the reason they haven't made an RFC is because they aren't stakeholders: their names are already public, so this feature doesn't help them. It would be great to have the RFC come from someone who plans to use this feature, not from a team member on behalf of someone else.

you miss his point. how can you expect new rust people to know about rfc or arcane options that dont work right. someone new cant rfc since they cant include how to fix due to not knowing rust or compiler.

there is too much expectation here for new people to fix a compiler when they likely dont have knowledge or skill to do so. this should be default, or easier to find/use like `-trimpath` in go which is dead simple and actually work

**Comment by sanxiyn** [comment] 2021-04-13 20:01
@chemsaf3 `trimpath` equivalent is easy to implement, I can do that if there is interest. The problem is that `trimpath` can't be the default because it breaks debuggers.

This issue is really about changing the default. If you want `trimpath`, I think it should be a separate issue.

**Comment by chemsaf3** [comment] 2021-04-13 20:05
> 
> 
> @chemsaf3 `trimpath` equivalent is easy to implement, I can do that if there is interest. The problem is that `trimpath` can't be the default because it breaks debuggers.
> 
> This issue is really about changing the default. If you want `trimpath`, I think it should be a separate issue.

i think default for `release` build is prob ok. but either way yeah should exist and likely would fix this issue if done right. even if flag its still easier to find/user than the hacks that only part work now

**Comment by ssokolow** [comment] 2021-04-13 22:38
> you miss his point. how can you expect new rust people to know about rfc or arcane options that dont work right. someone new cant rfc since they cant include how to fix due to not knowing rust or compiler.

From this, I get the impression there's been a miscommunication.

An RFC is the formal way to request a change to Rust, so there's no reason new people should need to know about it, any more than with any other RFC got accepted and resulted in a change to the compiler.

@jyn514 is just saying that the request should be written by someone who knows what matters most to them, rather than a team member who's just guessing.

**Comment by jyn514** [comment] 2023-06-16 16:37
I'm going to close this in favor of the tracking issue for the merged RFC: https://github.com/rust-lang/rust/issues/111540

**Closed by jyn514** 2023-06-16 16:37 UTC
Labels: T-compiler, C-feature-request
