### ISSUE TITLE
Regression in 1.62.0 with macro exports in doctests

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#98735] opened 2022-06-30 18:34 UTC
### Code

I tried this code (in a crate called `foo`):

```rust
/// ```
/// # #[macro_use] extern crate foo;
///
/// mockable! {}
/// ```
macro_rules! mockable {
    () => {};
}
```

and run

```console
$ cargo t --doc
```

I expected to see this happen: the doctest passes

Instead, this happened: the doctest fails to build with

```
running 1 test
test src/lib.rs - mockable (line 1) ... FAILED

failures:

---- src/lib.rs - mockable (line 1) stdout ----
error: cannot find macro `mockable` in this scope
 --> src/lib.rs:4:1
  |
5 | mockable! {}
  | ^^^^^^^^

error: aborting due to previous error
```

### Version it worked on

It most recently worked on: Rust 1.61.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: aarch64-unknown-linux-gnu
release: 1.62.0
LLVM version: 14.0.5
```

### Notes

It works if I add `#[macro_export]` above the `macro_rules!`. If intended, this feels like it should be listed in the [compatibility notes](https://github.com/rust-lang/rust/blob/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/RELEASES.md#compatibility-notes).

**Comment by steffahn** [comment] 2022-06-30 19:11
On my machine, on `1.61` or older it doesn’t appear to be running the doctest ***at all*** (i.e. it says `running 0 tests`, and the test could just as well be completely invalid code, or unconditionally failing); does that mirror what you’re observing?

**Comment by jonhoo** [comment] 2022-06-30 19:17
Oh, yes, good catch, that's what I observe on 1.61 and before too.

**Comment by jyn514** [comment] 2022-06-30 20:15
Duplicate of https://github.com/rust-lang/rust/issues/97030

**Closed by jyn514** 2022-06-30 20:15 UTC
Labels: C-bug, I-prioritize, regression-untriaged

**Comment by jonhoo** [comment] 2022-06-30 21:00
@jyn514 I left a comment over there. I think we should make sure to update the changelog with a note about this change then, and sooner rather than later since 1.62.0 is now out.

**Comment by jyn514** [comment] 2022-06-30 21:16
I'm not the one who approved the PR. Anyone is welcome to submit a change to the release notes.
