### ISSUE TITLE
30-60% perf regression in ctfe-stress

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#68967] opened 2020-02-08 21:23 UTC
This happened on 2020-01-11: https://perf.rust-lang.org/compare.html?start=bfd04876b93ad5c013d90bc46937e28b6ee1a3f4&end=1389494ac145a84dba025ff65969f7ab150c3f02&stat=instructions:u

Caused by https://github.com/rust-lang/rust/pull/67000

cc @oli-obk @spastorino 

(I could've sworn we already tracked this regression, but apparently not)

![screenshot-2020-02-09-00:03:41](https://user-images.githubusercontent.com/1786438/74093256-ada24500-4acf-11ea-8826-3b2747178469.png)

**Comment by oli-obk** [comment] 2020-02-10 13:47
We knew about this regression in the PR, maybe you remember that discussion. In https://github.com/rust-lang/rust/pull/67000#issuecomment-572584886 I finally came to the conclusion that the reason we regressed perf here is that before that PR we didn't actually evaluate the promoteds, we just created pointers to them. #67000 causes all promoteds to get evaluated immediately when their use site is evaluated. Basically any real program would already have done this work as `collect` would have evaluated the constant. Only if you have loads and loads of dead promoteds can you see the difference.

**Comment by jonas-schievink** [comment] 2020-02-13 11:50
Okay, that sounds much less alarming then. Thanks for the clarification!

**Comment by nikomatsakis** [comment] 2020-02-13 15:51
Visited during compiler-team triage. Based on @oli-obk's comment, going to close as "won't fix". Thanks @jonas-schievink!

**Closed by nikomatsakis** 2020-02-13 15:51 UTC
Labels: A-const-eval, C-bug, I-compiletime, I-nominated, T-compiler, regression-from-stable-to-beta
