### ISSUE TITLE
misleading ending in dining philosophers problem

### ISSUE THREAD

**Issue by bassmake** [rust-lang/rust#30515] opened 2015-12-21 23:36 UTC
in the end of dining philosophers sample there is mentioned that `Only two philosophers can eat at any one time, and so you’ll get some output like this:`.

But it doesn't work for me this way. `Only one philosopher can eat at one time in the provided solution.`

In the beginning everyone takes left fork. Then after 150ms only Emma Goldman can take right fork (because she is sitting next to Foucault). After Emma finished eating Karl Mark can start because his right fork is available and so on.

**Comment by durka** [comment] 2015-12-22 02:19
duplicate of #30471

**Comment by steveklabnik** [comment] 2015-12-22 15:00
Yes, closing as a duplicate, thanks!

**Closed by steveklabnik** 2015-12-22 15:00 UTC
