### ISSUE TITLE
ICE: `rustc` crashes in a `chroot` sandbox

### ISSUE THREAD

**Issue by ryzhyk** [rust-lang/rust#62353] opened 2019-07-03 20:03 UTC
This error happens when running `cargo` from `bazel`, which is in turn running in a `chroot` sandbox on Centos 7. Running with `RUST_BACKTRACE=1` unfortunately makes the error disappear, so we don't know why `rustc` needs to read `/proc/self/exe` and why only when compiling DD.

This is rustc 1.35

Note: the sandbox _does_  have `/proc` mounted in it, so this is not a duplicate of #56249

```
2019-07-03 00:10:30 gobuilds.Compile :    Compiling proc-macro2 v0.4.30
2019-07-03 00:10:30 gobuilds.Compile :    Compiling unicode-xid v0.1.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling unicode-xid v0.0.4
2019-07-03 00:10:30 gobuilds.Compile :    Compiling autocfg v0.1.4
2019-07-03 00:10:30 gobuilds.Compile :    Compiling quote v0.3.15
2019-07-03 00:10:30 gobuilds.Compile :    Compiling syn v0.15.39
2019-07-03 00:10:30 gobuilds.Compile :    Compiling serde v1.0.94
2019-07-03 00:10:30 gobuilds.Compile :    Compiling libc v0.2.58
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_core v0.4.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling unicode-width v0.1.5
2019-07-03 00:10:30 gobuilds.Compile :    Compiling winapi-build v0.1.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num-bigint v0.2.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling cc v1.0.37
2019-07-03 00:10:30 gobuilds.Compile :    Compiling abomonation v0.7.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling timely_logging v0.9.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling timely_bytes v0.9.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling backtrace v0.2.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling version_check v0.1.5
2019-07-03 00:10:30 gobuilds.Compile :    Compiling ryu v0.2.8
2019-07-03 00:10:30 gobuilds.Compile :    Compiling byteorder v1.3.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling winapi v0.2.8
2019-07-03 00:10:30 gobuilds.Compile :    Compiling memchr v2.2.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling timely_sort v0.1.6
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rustc-demangle v0.1.15
2019-07-03 00:10:30 gobuilds.Compile :    Compiling bitflags v0.4.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling cfg-if v0.1.9
2019-07-03 00:10:30 gobuilds.Compile :    Compiling fnv v1.0.6
2019-07-03 00:10:30 gobuilds.Compile :    Compiling itoa v0.4.4
2019-07-03 00:10:30 gobuilds.Compile :    Compiling encode_unicode v0.1.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling sequence_trie v0.3.6
2019-07-03 00:10:30 gobuilds.Compile :    Compiling libtool v0.1.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling lazy_static v0.2.11
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rustop v1.0.4
2019-07-03 00:10:30 gobuilds.Compile :    Compiling synom v0.11.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling getopts v0.2.19
2019-07-03 00:10:30 gobuilds.Compile :    Compiling kernel32-sys v0.2.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling dbghelp-sys v0.2.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_core v0.3.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_jitter v0.1.4
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num-traits v0.2.8
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num-integer v0.1.41
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_pcg v0.1.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_chacha v0.1.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num-iter v0.1.39
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num-complex v0.2.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num-rational v0.2.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand v0.6.5
2019-07-03 00:10:30 gobuilds.Compile :    Compiling nom v4.2.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling tinyset v0.2.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling main v0.1.0 (/build/.../main_ddlog)
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_xorshift v0.1.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_hc v0.1.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_isaac v0.1.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling backtrace-sys v0.1.29
2019-07-03 00:10:30 gobuilds.Compile :    Compiling syn v0.11.11
2019-07-03 00:10:30 gobuilds.Compile :    Compiling uuid v0.7.4
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rand_os v0.1.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling memmap v0.5.2
2019-07-03 00:10:30 gobuilds.Compile :    Compiling nix v0.5.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling time v0.1.42
2019-07-03 00:10:30 gobuilds.Compile :    Compiling quote v0.6.12
2019-07-03 00:10:30 gobuilds.Compile :    Compiling error-chain v0.5.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling cpuprofiler v0.0.3
2019-07-03 00:10:30 gobuilds.Compile :    Compiling graph_map v0.1.0 (https://github.com/frankmcsherry/graph-map.git#3d4de4e0)
2019-07-03 00:10:30 gobuilds.Compile :    Compiling twox-hash v1.4.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling synstructure v0.6.1
2019-07-03 00:10:30 gobuilds.Compile :    Compiling rustyline v1.0.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling serde_json v1.0.39
2019-07-03 00:10:30 gobuilds.Compile :    Compiling abomonation_derive v0.3.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling num v0.2.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling serde_derive v1.0.94
2019-07-03 00:10:30 gobuilds.Compile :    Compiling timely_communication v0.9.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling timely v0.9.0
2019-07-03 00:10:30 gobuilds.Compile :    Compiling differential-dataflow v0.9.0
2019-07-03 00:10:30 gobuilds.Compile : thread 'rustc' panicked at 'failed to get current_exe: no /proc/self/exe available. Is /proc mounted?', src/librustc/session/filesearch.rs:139:23
2019-07-03 00:10:30 gobuilds.Compile : note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : error: internal compiler error: unexpected panic
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : note: the compiler unexpectedly panicked. this is a bug.
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : note: rustc 1.35.0 running on x86_64-unknown-linux-gnu
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : note: compiler flags: -C opt-level=2 -C linker=/build/.../bazel/tools/cpp/toolchains/cayman/gcc/6/x86_64/x86_64-vmk-linux-gnu-gcc -C link-args=--sysroot=/build/.../cayman_glibc_2_17/sysroot/usr/include/../.. --crate-type lib
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : note: some of the compiler flags provided by cargo are hidden
2019-07-03 00:10:30 gobuilds.Compile : 
2019-07-03 00:10:30 gobuilds.Compile : error: Could not compile `differential-dataflow`.
```

**Comment by pnkfelix** [comment] 2019-07-04 13:38
triage: P-medium. Leaving nominated and unassigned for now.

Problem arises from this code:

https://github.com/rust-lang/rust/blob/b43eb4235ac43c822d903ad26ed806f34cc1a14a/src/librustc/session/filesearch.rs#L132-L140

(it seems like an interesting problem to resolve, in terms of figuring out better way for `rustc` to handle scenario where `std::env::current_exe` returns `Err`)

**Comment by pnkfelix** [comment] 2019-07-04 14:17
discussed at T-compiler meeting. Assigning to @nagisa to do some detective work with the issue filer to try to get to the bottom of this weirdness.

**Comment by eddyb** [comment] 2019-07-04 14:23
@ryzhyk Can you run `ls -l /proc/self/exe` from inside the sandbox?
Maybe there's an owner/permission mismatch or something simple like that.

**Comment by nagisa** [comment] 2019-07-04 14:36
So a few directed questions:

* What’s the kernel version?
* Is it really `proc` filesystem mounted under `/proc/` inside the chroot (check by running `mount` inside of chroot)?
* Are you sure some of the sandboxing mechanism do not prevent access to `/proc` in some way? I know that at least nix’s sandbox does isolate some of the `/proc`, for example;

Since this code is attempting to detect sysroot path, you can try to run `rustc` with `--sysroot` specified manually (e.g. via the `RUSTFLAGS` variable) as well. You can also attempt running `rustc --print sysroot` to see if that reproduces as well.

**Comment by ryzhyk** [comment] 2019-07-05 16:06
@eddyb , @nagisa , thanks for your help, and sorry about the delay.  I don't have direct access to this system, and need others' help to try these things out. Let me get back to you with answers to your specific questions as soon as I get them.

It turns out the setup is even more complicated: it's cargo invoked from bazel running on Centos 7.4, inside a VM, inside a chroot sandbox, on Cento 7.2.

I am being told that `/proc` is definitely mounted, and in fact the non-deterministic nature of the bug suggests that this is so.  We are already trying to set sysroot via `RUSTFLAGS`; will let you know how it goes.

Question: given that the problem is caused by an error returned by the `readlink` function from `glibc`, I'm wondering if it's possible that `rustc` calls this function from two concurrent threads, causing one of them to fail (I could not find any information on whether this function is thread safe).

**Comment by nagisa** [comment] 2019-07-05 17:41
> Question: given that the problem is caused by an error returned by the readlink function from glibc, I'm wondering if it's possible that rustc calls this function from two concurrent threads, causing one of them to fail (I could not find any information on whether this function is thread safe).

POSIX standard requires that all functions are thread-safe, except for a short list of exceptions as seen in [this subsection of the standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_09_01). `readlink` is not within a list of such functions.

**Comment by ryzhyk** [comment] 2019-07-14 22:44
Unfortunately, the issue disappeared and we have not been able to reproduce it. Shall I close this issue and reopen once we are able to reproduce?

Having said that, it would be great if `rustc` had a more robust implementation of `current_exe` that did not rely on `readlink`.

**Comment by nagisa** [comment] 2019-07-14 23:02
> Unfortunately, the issue disappeared and we have not been able to reproduce it. Shall I close this issue and reopen once we are able to reproduce?

Yes, because as things stands this is unactionable.

> Having said that, it would be great if rustc had a more robust implementation of current_exe that did not rely on readlink.

We are always open to concrete suggestions, however this function will always be fallible in weird corner cases due to the nature of the file systems.

**Closed by nagisa** 2019-07-14 23:02 UTC
Labels: C-bug, I-ICE, P-medium, T-compiler
