### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by darkstalker** [rust-lang/rust#25036] opened 2015-05-01 18:40 UTC
Got this error while trying to compile a simple program (https://gist.github.com/darkstalker/c8c605ddc56aa4d31fc8). It uses the num 0.1.24 crate.
```
  error: internal compiler error: Impl DefId { krate: 2, node: 24906 } was matchable against Obligation(predicate=Binder(TraitPredicate(core::ops::Mul<_>)),depth=1) but now is not
  note: the compiler unexpectedly panicked. this is a bug.
  note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
  note: run with `RUST_BACKTRACE=1` for a backtrace
  thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:209
```
The stack trace and rustc version are here: https://gist.github.com/darkstalker/f4ce878d18a4f5c489d7

**Comment by arielb1** [comment] 2015-10-23 21:17
duplicate of #22645.

**Closed by arielb1** 2015-10-23 21:17 UTC
Labels: I-ICE
