### ISSUE TITLE
Error converting Box<Error+Send> to &Error

### ISSUE THREAD

**Issue by emk** [rust-lang/rust#19279] opened 2014-11-24 21:09 UTC
I'm trying to write an `Error` implementation which supports a set of "important" error, plus a catch-all for various minor errors caused by low-level subsystems. The code looks something like this:

```rust
use std::error::Error;

pub enum DecodingError {
    EncodingUnknown,
    //...several named errors here...
    /// Other errors, the details of which are probably unimportant.
    Unexpected(Box<Error+Send>)
}

impl Error for DecodingError {
    fn description(&self) -> &str { "decoding error" }
    fn detail(&self) -> Option<String> { None }
    fn cause(&self) -> Option<&Error> {
        match self {
            &DecodingError::Unexpected(cause) => Some(&*cause),
            _ => None
        }
    }
}
```

This yields the following error in `cause`:

> <anon>:14:9: 17:10 error: mismatched types: expected `core::option::Option<&std::error::Error+'static>`, found `core::option::Option<&std::error::Error+Send>` (expected no bounds, found `Send`)

I should presumably be able to convert a `Box<Error+Send>` to an `&Error` safely, but I can't figure out a way to do it.

**Comment by steveklabnik** [comment] 2015-01-29 04:31
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/18524

**Closed by steveklabnik** 2015-01-29 04:31 UTC

**Comment by Guang1234567** [comment] 2019-11-22 06:00
@emk 

My solution:

```rust

#[derive(Debug)]
pub enum LibError {
    EmptyVec,
    DotEnvErr(Box<dyn Error>),
    LogErr(Box<dyn Error>),
    DatabaseErr(Box<dyn Error>),
}


impl Error for LibError {
    fn description(&self) -> &str {
        match self {
            EmptyVec => "empty vectors not allowed",
            DotEnvErr(e) => e.description(),
            LogErr(e) => e.description(),
            DatabaseErr(e) => e.description(),
        }
    }
    fn cause(&self) -> Option<&Error> {
        match self {
            EmptyVec => None,
            DotEnvErr(e) => Some(&**e),
            LogErr(e) => Some(&**e),
            DatabaseErr(e) => Some(&**e),   //<————————  here
        }
    }
}
```
