### ISSUE TITLE
nightly compiler crash when running udeps

### ISSUE THREAD

**Issue by numerodix** [rust-lang/rust#99313] opened 2022-07-16 08:34 UTC
### Code

```bash
$ cargo +nightly udeps
   Compiling libc v0.2.126
   Compiling proc-macro2 v1.0.40
   Compiling unicode-ident v1.0.1
   Compiling quote v1.0.20
    Checking cfg-if v1.0.0
   Compiling syn v1.0.98
    Checking once_cell v1.13.0
    Checking pin-project-lite v0.2.9
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling futures-core v0.3.21
   Compiling autocfg v1.0.1
    Checking futures-sink v0.3.21
   Compiling futures-task v0.3.21
   Compiling version_check v0.9.4
    Checking smallvec v1.9.0
   Compiling futures-util v0.3.21
    Checking itoa v1.0.2
    Checking bytes v1.1.0
    Checking slab v0.4.6
   Compiling parking_lot_core v0.9.3
   Compiling serde_derive v1.0.138
    Checking pin-utils v0.1.0
   Compiling serde v1.0.138
    Checking scopeguard v1.1.0
    Checking percent-encoding v2.1.0
   Compiling typenum v1.15.0
    Checking ppv-lite86 v0.2.16
    Checking fnv v1.0.7
   Compiling futures-channel v0.3.21
    Checking lazy_static v1.4.0
   Compiling crossbeam-utils v0.8.10
    Checking tinyvec_macros v0.1.0
   Compiling httparse v1.7.1
   Compiling serde_json v1.0.82
    Checking hashbrown v0.12.2
    Checking ryu v1.0.10
    Checking matches v0.1.9
   Compiling async-trait v0.1.56
    Checking alloc-no-stdlib v2.0.3
    Checking local-waker v0.1.3
   Compiling crc32fast v1.3.2
   Compiling zstd-safe v5.0.2+zstd.1.5.2
   Compiling encoding_rs v0.8.31
   Compiling regex-syntax v0.6.27
    Checking httpdate v1.0.2
    Checking adler v1.0.2
   Compiling paste v1.0.7
    Checking unicode-bidi v0.3.8
    Checking base64 v0.13.0
    Checking mime v0.3.16
    Checking cpufeatures v0.2.2
   Compiling time-macros v0.2.4
    Checking num_threads v0.1.6
   Compiling firestorm v0.5.1
    Checking bitflags v1.3.2
   Compiling convert_case v0.4.0
    Checking try-lock v0.2.3
    Checking language-tags v0.3.2
    Checking ansi_term v0.12.1
    Checking integer-encoding v3.0.4
    Checking byteorder v1.4.3
    Checking tower-service v0.3.2
    Checking ipnet v2.5.0
    Checking tracing-core v0.1.28
    Checking thread_local v1.1.4
   Compiling indexmap v1.9.1
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
    Checking lock_api v0.4.6
    Checking bytestring v1.1.0
    Checking http v0.2.8
   Compiling generic-array v0.14.5
   Compiling ahash v0.7.6
   Compiling cookie v0.16.0
    Checking sharded-slab v0.1.4
    Checking tinyvec v1.6.0
    Checking form_urlencoded v1.0.1
    Checking alloc-stdlib v0.2.1
    Checking actix-utils v3.0.0
    Checking miniz_oxide v0.5.3
    Checking brotli-decompressor v2.3.2
    Checking http-body v0.4.5
    Checking actix-service v2.0.2
    Checking want v0.3.0
    Checking tracing-log v0.1.3
    Checking unicode-normalization v0.1.21
    Checking aho-corasick v0.7.18
    Checking num_cpus v1.13.1
    Checking getrandom v0.2.7
    Checking mio v0.8.4
    Checking signal-hook-registry v1.4.0
    Checking socket2 v0.4.4
    Checking time v0.3.11
    Checking time v0.1.44
   Compiling jobserver v0.1.24
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 2', compiler/rustc_builtin_macros/src/format.rs:1001:28
stack backtrace:
   0:     0x7f1e494b0950 - std::backtrace_rs::backtrace::libunwind::trace::heeafe1f1ea6b4c2f
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f1e494b0950 - std::backtrace_rs::backtrace::trace_unsynchronized::hf08684e78cd6c167
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1e494b0950 - std::sys_common::backtrace::_print_fmt::had9e99c2c8763a1e
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f1e494b0950 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b4c432d2a1e6303
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f1e49509f2c - core::fmt::write::h87085de871a99231
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f1e494a2015 - std::io::Write::write_fmt::h7635d2f423aa55dc
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/io/mod.rs:1672:15
   6:     0x7f1e494b35e1 - std::sys_common::backtrace::_print::hc003bc1c22b7967b
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f1e494b35e1 - std::sys_common::backtrace::print::h1baa1ab7758e52b0
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f1e494b35e1 - std::panicking::default_hook::{{closure}}::he2f5e84c6ab77817
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/panicking.rs:295:22
   9:     0x7f1e494b32b3 - std::panicking::default_hook::h3f96069db270c68f
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/panicking.rs:314:9
  10:     0x7f1e49cdade4 - rustc_driver[1ce26eb46f30f4d]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f1e494b3db6 - std::panicking::rust_panic_with_hook::hed0c1597bbc695a6
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/panicking.rs:702:17
  12:     0x7f1e494b3c07 - std::panicking::begin_panic_handler::{{closure}}::h0fc9e6b3154da131
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/panicking.rs:588:13
  13:     0x7f1e494b0e34 - std::sys_common::backtrace::__rust_end_short_backtrace::hb9c2240a67931ff9
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f1e494b3932 - rust_begin_unwind
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/panicking.rs:584:5
  15:     0x7f1e49477c33 - core::panicking::panic_fmt::h6bda1b0556b509cd
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/core/src/panicking.rs:142:14
  16:     0x7f1e49477b72 - core::panicking::panic_bounds_check::hf8fc252dfbb36006
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/core/src/panicking.rs:84:5
  17:     0x7f1e4c115643 - rustc_builtin_macros[6a564b3b10d3c327]::format::expand_preparsed_format_args
  18:     0x7f1e4c10edac - rustc_builtin_macros[6a564b3b10d3c327]::format::expand_format_args_impl
  19:     0x7f1e4ba4dbed - <rustc_expand[ec7f7165620ca96d]::expand::MacroExpander>::fully_expand_fragment
  20:     0x7f1e4c5c294b - <rustc_expand[ec7f7165620ca96d]::expand::MacroExpander>::expand_crate
  21:     0x7f1e4bee7aa2 - <rustc_session[4ac326324d613686]::session::Session>::time::<core[32c218dbf3427c26]::result::Result<rustc_ast[f9ddef6e3c579104]::ast::Crate, rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_interface[694c7ab70a1d38bc]::passes::configure_and_expand::{closure#1}>
  22:     0x7f1e4bed1832 - rustc_interface[694c7ab70a1d38bc]::passes::configure_and_expand
  23:     0x7f1e4bede2c1 - <rustc_interface[694c7ab70a1d38bc]::queries::Queries>::expansion
  24:     0x7f1e4be9cfcc - <rustc_interface[694c7ab70a1d38bc]::interface::Compiler>::enter::<rustc_driver[1ce26eb46f30f4d]::run_compiler::{closure#1}::{closure#2}, core[32c218dbf3427c26]::result::Result<core[32c218dbf3427c26]::option::Option<rustc_interface[694c7ab70a1d38bc]::queries::Linker>, rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>>
  25:     0x7f1e4be991ff - rustc_span[717885ec7c6cd182]::with_source_map::<core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_interface[694c7ab70a1d38bc]::interface::create_compiler_and_run<core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_driver[1ce26eb46f30f4d]::run_compiler::{closure#1}>::{closure#1}>
  26:     0x7f1e4beb54b0 - rustc_interface[694c7ab70a1d38bc]::interface::create_compiler_and_run::<core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_driver[1ce26eb46f30f4d]::run_compiler::{closure#1}>
  27:     0x7f1e4bec95b2 - <scoped_tls[f235d80db834c386]::ScopedKey<rustc_span[717885ec7c6cd182]::SessionGlobals>>::set::<rustc_interface[694c7ab70a1d38bc]::interface::run_compiler<core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_driver[1ce26eb46f30f4d]::run_compiler::{closure#1}>::{closure#0}, core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>>
  28:     0x7f1e4be9b78f - std[167b23ae759531ff]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[694c7ab70a1d38bc]::util::run_in_thread_pool_with_globals<rustc_interface[694c7ab70a1d38bc]::interface::run_compiler<core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_driver[1ce26eb46f30f4d]::run_compiler::{closure#1}>::{closure#0}, core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>>::{closure#0}, core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>>
  29:     0x7f1e4beb5909 - <<std[167b23ae759531ff]::thread::Builder>::spawn_unchecked_<rustc_interface[694c7ab70a1d38bc]::util::run_in_thread_pool_with_globals<rustc_interface[694c7ab70a1d38bc]::interface::run_compiler<core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>, rustc_driver[1ce26eb46f30f4d]::run_compiler::{closure#1}>::{closure#0}, core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>>::{closure#0}, core[32c218dbf3427c26]::result::Result<(), rustc_errors[3b3e5bcd1e9c2834]::ErrorGuaranteed>>::{closure#1} as core[32c218dbf3427c26]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  30:     0x7f1e494bd803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h86b1834fb0da834b
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/alloc/src/boxed.rs:1934:9
  31:     0x7f1e494bd803 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h124d05192aaf60e0
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/alloc/src/boxed.rs:1934:9
  32:     0x7f1e494bd803 - std::sys::unix::thread::Thread::new::thread_start::h01e8d05fb6e030ea
                               at /rustc/c2f428d2f3340a0e7d995f4726223db91b93704c/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7f1e493c7609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
    Checking crossbeam-channel v0.5.5
    Checking flate2 v1.0.24
  34:     0x7f1e492ea133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  35:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (c2f428d2f 2022-07-14) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -Z binary-dep-depinfo

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `time`
warning: build failed, waiting for other jobs to finish...
```

I hope this helps someone :)

**Comment by lqd** [comment] 2022-07-16 10:08
This is a duplicate of #99261 and will be fixed by https://github.com/rust-lang/rust/pull/99263. I will close it as such. 
Thanks for opening an issue!

**Closed by lqd** 2022-07-16 10:08 UTC
Labels: I-ICE, T-compiler, C-bug
