### ISSUE TITLE
Wrongly named function parameter causes compiler panic

### ISSUE THREAD

**Issue by Redrield** [rust-lang/rust#45252] opened 2017-10-13 03:38 UTC
When trying to modularize some code I'd written using the D-Bus Rust bindings, I decided to extract closures from their DSL and put them into their own functions. The resulting files are in the included gist as handlers.rs, and main.rs

The crash seems to be caused from the parameter of the method being named info, while the code is expecting it to be named `m`. The full error log is in the attached gist named error.log

rustc --version --verbose output is in rustc-verison.log

https://gist.github.com/Redrield/cb11307cb6bd85e18f809d248f3ab595

(Note that the issue can be fixed by renaming the parameter to match what is expected.)

**Comment by kennytm** [comment] 2017-10-13 07:13
Hi. I noted that your rustc version is nightly at 2017-09-27. This issue may be a duplicate of #44814, which has been fixed by #44945 on Oct 2nd. Could you update the compiler to the latest nightly (2017-10-12) and check if the panic still exists? Thanks!

**Comment by Aaronepower** [comment] 2018-01-22 20:03
Closing due to inactivity, if this issue is still present feel free to reopen!

**Closed by Aaronepower** 2018-01-22 20:03 UTC
