### ISSUE TITLE
unic-idna-mapping-0.4.0 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43683] opened 2017-08-05 13:41 UTC
[unic-idna-mapping](https://crates.io/crates/unic-idna-mapping) version 0.4.0 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/unic-idna-mapping-0.4.0/log.txt)):

```
Aug 04 02:28:56.746 INFO kablam! error[E0560]: struct `__test::test::TestDesc` has no field named `allow_fail`
Aug 04 02:28:56.746 INFO kablam!   --> tests/unicode_version_tests.rs:17:1
Aug 04 02:28:56.746 INFO kablam!    |
Aug 04 02:28:56.746 INFO kablam! 17 | / fn test_version_against_ucd_core() {
Aug 04 02:28:56.746 INFO kablam! 18 | |     assert_eq!(
Aug 04 02:28:56.746 INFO kablam! 19 | |         unic_ucd_core::UNICODE_VERSION,
Aug 04 02:28:56.746 INFO kablam! 20 | |         unic_idna_mapping::UNICODE_VERSION
Aug 04 02:28:56.746 INFO kablam! 21 | |     );
Aug 04 02:28:56.746 INFO kablam! 22 | | }
Aug 04 02:28:56.746 INFO kablam!    | |_^ `__test::test::TestDesc` does not have this field
```
cc @behnam

**Comment by arielb1** [comment] 2017-08-05 14:44
what?

**Comment by arielb1** [comment] 2017-08-05 14:59
Looks like a dupe of #43684 - `rustc_test` is being used.

**Comment by arielb1** [comment] 2017-08-05 15:01
https://github.com/behnam/rust-unic/blob/v0.4.0/components/idna/Cargo.toml indeed uses `rustc-test` 0.1.

**Comment by alexcrichton** [comment] 2017-08-05 15:24
Closing in favor of https://github.com/rust-lang/rust/issues/43684

**Closed by alexcrichton** 2017-08-05 15:24 UTC
Labels: regression-from-stable-to-beta, T-compiler

**Comment by behnam** [comment] 2017-08-05 18:33
Thanks, @est31, for the report. Yes, it is a known problem that we need to maintain `rustc_test` for the beta/nightly to pass. For UNIC specifically, we want to drop the dependency and use an approach that works also on stable, with some extra goodies. Here's the issue I filed: https://github.com/behnam/rust-unic/issues/76
