### ISSUE TITLE
How about bundle clang with rust.

### ISSUE THREAD

**Issue by lygstate** [rust-lang/rust#77813] opened 2020-10-11 09:02 UTC
So when do cross compiling, or native compiling we doesn't need to install a native compiler anymore.
On windows. only need to install windows sdk.
On linux or osx, gcc doesn't need anymore, only need the headers

And clang also have the nature to specify the target-triple, that consistence with rust.
because on windows, clang are alreay as mature as msvc, and on linux
clang are already as mature as gcc.
and on osx, clang are default.

**Comment by jonas-schievink** [comment] 2020-10-11 12:56
Duplicate of https://github.com/rust-lang/rust/issues/56371

**Closed by jonas-schievink** 2020-10-11 12:56 UTC
Labels: A-cross, C-feature-request
