### ISSUE TITLE
Rust didn't optimize code for two same methods.

### ISSUE THREAD

**Issue by heckad** [rust-lang/rust#76841] opened 2020-09-17 15:45 UTC
https://godbolt.org/z/b1fdYh

**Comment by jonas-schievink** [comment] 2020-09-17 15:49
Please elaborate on what the issue is. `fun2` probably got merged into `fun`, so they are the same.

**Comment by heckad** [comment] 2020-09-17 16:06
Yes, but If I remove fun2 it will turn out https://godbolt.org/z/GcErv6

**Comment by wesleywiser** [comment] 2020-09-17 16:32
LLVM [provides](https://llvm.org/doxygen/namespacellvm_1_1InlineConstants.html#ac32c5e568abcce09107853ccf11fbab6) an inlining bonus to functions that are only called once. It's possible that bonus is required for `Iterator::collect()` to be inlined into `fun`. I'm not sure of the order of the passes in LLVM but if function merging occurs after inlining, that could be causing the difference.

**Comment by the8472** [comment] 2020-09-17 17:15
Note that `vec.into_iter().collect()` [is specialized](https://github.com/rust-lang/rust/blob/7bdb5dee7bac15458b10b148e9e24968e633053e/library/alloc/src/vec.rs#L2203-L2205). The assembly for `core::iter::traits::iterator::Iterator::collect` in the second godbolt link does look like it's using that specialization and should still pass through the vec as-is, most of the emitted instructions in that case are effectively dead code.

**Comment by oli-obk** [comment] 2020-09-20 10:49
I don't think there's anything actionable here, please open a new issue if you find any specific things that we could optimize for

**Closed by oli-obk** 2020-09-20 10:49 UTC
Labels: C-bug, I-slow, T-compiler

**Comment by heckad** [comment] 2020-09-20 11:05
@oli-obk, is it the expected behaviour that it does not perform optimization in [this](https://godbolt.org/z/b1fdYh) case?

**Comment by oli-obk** [comment] 2020-09-20 11:09
It does not perform inlining, as far as I can tell this has no effects on perf though. There are lots and lots of heuristics in optimizations. I'll happily take a tracking issue for a specific optimization, but here this is just a shift of what is being optimized. If there are actual calls to `fun` and `fun2` each of these calls would likely get inlined, even if it's body did not perform inlining. This just shifts the function call somewhere else without actually being worse code. I don't see any action we can perform here that would not just mean messing with LLVM optimizations to change a microbenchmark without any clear or measurable benefit

**Comment by heckad** [comment] 2020-09-20 19:51
Oh, thank you for the good explanation.
