### ISSUE TITLE
internal compiler error: unexpected panic

### ISSUE THREAD

**Issue by luyikk** [rust-lang/rust#94792] opened 2022-03-10 02:00 UTC
### Code

```Rust
    fn write(&self, now: &mut DeferredNow, record: &Record) -> std::io::Result<()> {
        let level = record.level();
        write!(
            std::io::stderr(),
            "[{} {} {}:{}] {}\r\n",
            now.format(TS_DASHES_BLANK_COLONS_DOT_BLANK),
            style(level).paint(level.to_string()),
            get_file_name(record.file()).unwrap_or("<unnamed>"),
            record.line().unwrap_or(0),
            record.args()
        )
    }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (f8abed9ed 2021-12-26)
```

### Error output

```
thread 'rustc' panicked at 'failed to lookup `SourceFile` in new context', compiler\rustc_query_impl\src\on_disk_cache.rs:500:22
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.59.0-nightly (f8abed9ed 2021-12-26) running on x86_64-pc-windows-msvc
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
#0 [typeck] type-checking `stdout_log::<impl at src\stdout_log.rs:21:1: 42:2>::write`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: 1 warning emitted

error: could not compile `websocket_gateway`; 2 warnings emitted
Process finished with exit code 101

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by ehuss** [comment] 2022-03-24 22:10
Thanks for the report! `1.59.0-nightly (f8abed9ed 2021-12-26)` is quite old.  Closing as a duplicate of #92163.  I suggest trying with the latest nightly.

**Closed by ehuss** 2022-03-24 22:10 UTC
Labels: I-ICE, T-compiler, C-bug
