### ISSUE TITLE
x.py doesn't chdir to its own directory

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#38447] opened 2016-12-18 03:10 UTC
`x.py` fails to chdir to its own directory.  Running it from elsewhere results in nonsense like re-downloading bootstrap compilers.

**Comment by sanxiyn** [comment] 2016-12-18 04:22
Isn't this an intended behavior? So that you can have multiple build directories which do not clobber each other.

I agree cache could be shared. If you agree, we can update the title of the issue.

**Comment by petrochenkov** [comment] 2016-12-18 11:55
I'm not even sure cache (= downloaded stage0 compiler/cargo) needs to be shared implicitly.
Now each build directory is nicely self-contained, and if you want to use a common stage0 compiler for several builds you can always specify it explicitly in `config.toml`.

**Comment by alexcrichton** [comment] 2016-12-18 18:11
Yes this is currently expected behavior to support out-of-tree builds. I don't think there's really any location for a shared cache as well as often the source tree can be read-only where the only writable directory is the build tree (current directory)

**Comment by Mark-Simulacrum** [comment] 2017-05-18 13:04
Closing as expected behavior -- I don't think we want to change this.

**Closed by Mark-Simulacrum** 2017-05-18 13:04 UTC
Labels: A-rustbuild
