### ISSUE TITLE
rust-lld corruption with Ctrl+C

### ISSUE THREAD

**Issue by Axel-Reactor** [rust-lang/rust#128860] opened 2024-08-09 01:25 UTC
When interrupting linking with rust-lld.exe it sometimes corrupts the target and the only recovery is `cargo clean`.
I'm getting tones of errors like this if I try `cargo build` again after:
` = note: rust-lld: error: undefined symbol: anon.8ff5a01038e5b419b80b5d238bffa21c.22.llvm.13741956020784447919 `
` rust-lld: error: undefined symbol: xx::xxxx::xxxx::GLOBAL::h22b2a472d7972d2f (.llvm.10192556018238492745)`
` rust-lld: error: undefined symbol: core::hint::unreachable_unchecked::precondition_check::h644ec5c1a75164f9 (.llvm.10192556018238492745)`

This isn't a good UX. Ctrl+C should be robust and not leave things in a bad state.

**Comment by bjorn3** [comment] 2024-08-09 15:16
Duplicate of https://github.com/rust-lang/rust/issues/81280. Recovering from this can also be done by clearing the incr comp cache using `rm -r target/debug/incremental`. The incr comp cache should only be finalized after it is fully written, but this bug seems to indicate that finalization of the incr comp cache is done just a bit too early.

**Comment by workingjubilee** [comment] 2024-08-10 02:32
closing as duplicate.

**Closed by workingjubilee** 2024-08-10 02:32 UTC
Labels: A-linkage, A-incr-comp, C-bug, needs-triage
