### ISSUE TITLE
ICE with -Z nll-facts on rustc-ap-serialize

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#54304] opened 2018-09-17 18:51 UTC
`rustc 1.30.0-nightly (cb6d2dfa8 2018-09-16)`
````
cargo new --bin crash
cd crash
echo rustc-ap-serialize = \"260.0.0\" >> Cargo.toml
RUST_BACKTRACE=full RUSTFLAGS=" -Z nll-facts" cargo check  
````
````
    Checking rustc-ap-serialize v260.0.0
error: internal compiler error: librustc_mir/borrow_check/nll/type_check/liveness/trace.rs:531: polonius liveness facts not implemented yet
thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:586:9
stack backtrace:
   0:     0x7f859798ce2e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::he3ea2af6595cbcfd
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x7f8597965ec6 - std::sys_common::backtrace::print::h9a6dc25b0b6db3e6
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x7f8597963aed - std::panicking::default_hook::{{closure}}::h9f9f4c00fc62ac12
                               at libstd/panicking.rs:211
   3:     0x7f8597963860 - std::panicking::default_hook::h86ebe853ecef0f3c
                               at libstd/panicking.rs:227
   4:     0x7f8594199bb1 - rustc::util::common::panic_hook::hcc2bf340b7bc1ced
   5:     0x7f8597964273 - std::panicking::rust_panic_with_hook::h6d3348b8dd4df56e
                               at libstd/panicking.rs:481
   6:     0x7f8592ea939e - std::panicking::begin_panic::hb9eb33f8e4bb6d23
   7:     0x7f8592ea3a5f - rustc_errors::Handler::bug::h525d7ec61edc479b
   8:     0x7f8593e8069c - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h348cbfaa2f47a43f
   9:     0x7f8593e7efc9 - rustc::ty::context::tls::with_opt::{{closure}}::h5d24da1cc39d5c33
  10:     0x7f8593dc547f - rustc::ty::context::tls::with_context_opt::h2fa75c0cbac706c7
  11:     0x7f8593e7e896 - rustc::ty::context::tls::with_opt::h4d348ca809a0fa56
  12:     0x7f8593e805a4 - rustc::util::bug::opt_span_bug_fmt::hefa9c446a73c2683
  13:     0x7f8593e80516 - rustc::util::bug::bug_fmt::hb57ec763933bcb1f
  14:     0x7f8594c87d4a - rustc::ty::structural_impls::<impl rustc::ty::fold::TypeFoldable<'tcx> for &'tcx rustc::ty::sty::RegionKind>::visit_with::h3f902610796cd3cf
  15:     0x7f8594c7a580 - <rustc::ty::fold::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::any_free_region_meets::RegionVisitor<F> as rustc::ty::fold::TypeVisitor<'tcx>>::visit_ty::h2712ab47af3ec604
  16:     0x7f8594c99607 - <core::slice::Iter<'a, T> as core::iter::iterator::Iterator>::try_fold::h42580b5642714614
  17:     0x7f8594c7a703 - <rustc::ty::fold::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::any_free_region_meets::RegionVisitor<F> as rustc::ty::fold::TypeVisitor<'tcx>>::visit_ty::h2712ab47af3ec604
  18:     0x7f8594cf8870 - rustc_mir::borrow_check::nll::type_check::liveness::generate::h2c9ece5236ebdb3e
  19:     0x7f8594e22adf - rustc_mir::borrow_check::nll::type_check::type_check::haafe9c468117c1e6
  20:     0x7f8594bbbd7c - rustc_mir::borrow_check::nll::compute_regions::h9226fb998af23ba8
  21:     0x7f8594d42f7b - rustc_mir::borrow_check::do_mir_borrowck::h86fa4d9286373173
  22:     0x7f8594b67e1d - rustc::infer::InferCtxtBuilder::enter::h54fa461261cabccd
  23:     0x7f8594d4272b - rustc_mir::borrow_check::mir_borrowck::hb647d08d41444262
  24:     0x7f8593e8d54d - rustc::ty::query::__query_compute::mir_borrowck::h793d740b50ff0a62
  25:     0x7f8593e935e4 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::mir_borrowck<'tcx>>::compute::hc3b516f7a2a36be6
  26:     0x7f8593bfc38c - rustc::dep_graph::graph::DepGraph::with_task_impl::he9c377c23b2ebf6b
  27:     0x7f8593e6c98e - rustc::ty::context::tls::with_related_context::he8421b9003c073e3
  28:     0x7f8593ed0804 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::had5aee8a3c434c4d
  29:     0x7f8593f552f6 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query::h30468e1e8ef6097c
  30:     0x7f85940220b2 - rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_borrowck::h938ea62cb03ab47e
  31:     0x7f8597dd4064 - rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::par_body_owners::h1e6540b541de1680
  32:     0x7f8597cf9b75 - rustc::util::common::time::hac7d5edb6bd57144
  33:     0x7f8597da7a74 - rustc::ty::context::tls::enter_context::h715a7c4ed3df78cd
  34:     0x7f8597d6c09a - <std::thread::local::LocalKey<T>>::with::hd95c45ddd7867e28
  35:     0x7f8597dd0132 - rustc::ty::context::TyCtxt::create_and_enter::hb18398e154946ffe
  36:     0x7f8597d0fd98 - rustc_driver::driver::compile_input::hc66c1c738ac7aaef
  37:     0x7f8597db576c - rustc_driver::run_compiler_with_pool::h6b4754955072f1bd
  38:     0x7f8597d0da04 - rustc_driver::driver::spawn_thread_pool::h0e0741ca8196fcad
  39:     0x7f8597db4781 - rustc_driver::run_compiler::hb629c8fa6de054ed
  40:     0x7f8597cfc39c - <scoped_tls::ScopedKey<T>>::set::hbe5c97e730f269eb
  41:     0x7f8597d386f1 - syntax::with_globals::h4ed1507b91395e86
  42:     0x7f85979a3a59 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  43:     0x7f8597db29dc - rustc_driver::run::h6b3d75b0c182df06
  44:     0x7f8597dc0a7a - rustc_driver::main::h99d62d512cf3f7b1
  45:     0x5587c64de952 - std::rt::lang_start::{{closure}}::h935a7f48c96225c4
  46:     0x7f8597963cb2 - std::panicking::try::do_call::h46a7bcf1f6152e5b
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  47:     0x7f85979a3a59 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  48:     0x7f859797a355 - std::rt::lang_start_internal::h221cb5896f5e061c
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  49:     0x5587c64de9b3 - main
  50:     0x7f8597726222 - __libc_start_main
  51:     0x5587c64de838 - <unknown>
query stack during panic:
#0 [mir_borrowck] processing `serialize::Encoder::emit_enum`
end of query stack
error: aborting due to previous error
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.30.0-nightly (cb6d2dfa8 2018-09-16) running on x86_64-unknown-linux-gnu
note: compiler flags: -Z nll-facts -C debuginfo=2 --crate-type lib
note: some of the compiler flags provided by cargo are hidden
error: Could not compile `rustc-ap-serialize`.
To learn more, run the command again with --verbose.
````

**Comment by matthewjasper** [comment] 2018-09-17 19:47
Duplicate of #54212

**Closed by matthewjasper** 2018-09-17 19:47 UTC
Labels: A-NLL, NLL-deferred

**Comment by matthiaskrgr** [comment] 2018-09-17 20:08
Ah, interesting. I only searched for tickets with `-Z nll-facts` and couldn't find anything related.
