### ISSUE TITLE
rustc panicked

### ISSUE THREAD

**Issue by rex4539** [rust-lang/rust#81644] opened 2021-02-01 21:34 UTC
### Steps
Compile https://github.com/nymtech/nym

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-apple-darwin
release: 1.51.0-nightly
LLVM version: 11.0.1
```

### Error output

```
% RUST_BACKTRACE=full cargo build --verbose
       Fresh cfg-if v0.1.10
       Fresh unicode-xid v0.2.1
       Fresh version_check v0.9.2
       Fresh autocfg v1.0.1
       Fresh lazy_static v1.4.0
       Fresh ppv-lite86 v0.2.9
       Fresh subtle v2.2.3
       Fresh opaque-debug v0.2.3
       Fresh subtle v1.0.0
       Fresh byte-tools v0.3.1
       Fresh regex-syntax v0.6.18
       Fresh opaque-debug v0.3.0
       Fresh cpuid-bool v0.1.2
       Fresh slab v0.4.2
       Fresh futures-core v0.3.9
       Fresh arrayref v0.3.6
       Fresh keystream v1.0.0
       Fresh bytes v0.5.6
       Fresh quick-error v1.2.3
       Fresh cc v1.0.59
       Fresh fnv v1.0.7
       Fresh fake-simd v0.1.2
       Fresh base64 v0.11.0
       Fresh termcolor v1.1.0
       Fresh signature v1.2.2
       Fresh bs58 v0.3.1
       Fresh constant_time_eq v0.1.5
       Fresh futures-sink v0.3.9
       Fresh arc-swap v0.4.7
       Fresh arrayvec v0.5.1
       Fresh pin-project-lite v0.1.7
       Fresh itoa v0.4.6
       Fresh once_cell v1.4.1
       Fresh futures-io v0.3.9
       Fresh pin-project-lite v0.2.4
       Fresh pin-utils v0.1.0
       Fresh semver-parser v0.7.0
       Fresh matches v0.1.8
       Fresh tinyvec v0.3.4
       Fresh percent-encoding v2.1.0
       Fresh remove_dir_all v0.5.3
       Fresh base64 v0.12.3
       Fresh hashbrown v0.9.0
       Fresh try-lock v0.2.3
       Fresh scopeguard v1.1.0
       Fresh tower-service v0.3.0
       Fresh maplit v1.0.2
       Fresh mime v0.3.16
       Fresh dtoa v0.4.6
       Fresh smallvec v1.4.2
       Fresh utf-8 v0.7.5
       Fresh ipnet v2.3.0
       Fresh unicode-width v0.1.8
       Fresh ucd-trie v0.1.3
       Fresh ansi_term v0.11.0
       Fresh quick-error v2.0.0
       Fresh strsim v0.8.0
       Fresh vec_map v0.8.2
       Fresh humantime v2.0.1
       Fresh instant v0.1.6
       Fresh unicode-xid v0.1.0
       Fresh dotenv v0.15.0
       Fresh array-init v0.1.1
       Fresh gimli v0.22.0
       Fresh adler v0.2.3
       Fresh object v0.20.0
       Fresh rustc-demangle v0.1.16
       Fresh thread_local v1.0.1
       Fresh tracing-core v0.1.15
       Fresh block-padding v0.1.5
       Fresh humantime v1.3.0
       Fresh ed25519 v1.0.1
       Fresh input_buffer v0.3.1
       Fresh futures-task v0.3.9
       Fresh futures-channel v0.3.9
       Fresh semver v0.9.0
       Fresh http v0.2.1
       Fresh dashmap v4.0.0-rc6
       Fresh unicode-bidi v0.3.4
       Fresh unicode-normalization v0.1.13
       Fresh lock_api v0.4.1
       Fresh lock_api v0.3.4
       Fresh pest v2.1.3
       Fresh textwrap v0.11.0
       Fresh libc v0.2.76
       Fresh proc-macro2 v1.0.24
       Fresh typenum v1.12.0
       Fresh miniz_oxide v0.4.1
       Fresh addr2line v0.13.0
       Fresh log v0.4.11
       Fresh memchr v2.3.3
       Fresh byteorder v1.3.4
       Fresh proc-macro-hack v0.5.19
       Fresh proc-macro-nested v0.1.6
       Fresh version-checker v0.1.0 (/Users/rex/nym/common/version-checker)
       Fresh idna v0.2.0
       Fresh core-foundation-sys v0.7.0
       Fresh bitflags v1.2.1
       Fresh ryu v1.0.5
       Fresh httparse v1.3.4
       Fresh http-body v0.3.1
       Fresh getrandom v0.1.14
       Fresh time v0.1.44
       Fresh atty v0.2.14
       Fresh iovec v0.1.4
       Fresh net2 v0.2.35
       Fresh num_cpus v1.13.0
       Fresh signal-hook-registry v1.2.1
       Fresh socket2 v0.3.12
       Fresh encoding_rs v0.8.24
       Fresh pest_meta v2.1.3
       Fresh dirs-sys v0.3.5
       Fresh maybe-uninit v2.0.0
       Fresh crc32fast v1.2.0
       Fresh fs2 v0.4.3
       Fresh parking_lot_core v0.8.0
       Fresh proc-macro2 v0.4.30
       Fresh parking_lot_core v0.7.2
       Fresh quote v1.0.7
       Fresh generic-array v0.14.4
       Fresh generic-array v0.12.3
       Fresh aho-corasick v0.7.13
       Fresh chacha v0.3.0
       Fresh num-traits v0.2.12
       Fresh tracing v0.1.19
       Fresh want v0.3.0
       Fresh fxhash v0.2.1
       Fresh ordered-buffer v0.1.0 (/Users/rex/nym/common/socks5/ordered-buffer)
       Fresh backtrace v0.3.50
       Fresh doc-comment v0.3.3
       Fresh url v2.1.1
       Fresh security-framework-sys v0.4.3
       Fresh core-foundation v0.7.0
       Fresh indexmap v1.6.0
       Fresh unicase v2.6.0
       Fresh memoffset v0.5.5
       Fresh crossbeam-utils v0.7.2
       Fresh error-chain v0.12.4
       Fresh rand_core v0.5.1
       Fresh mio v0.6.22
       Fresh clap v2.33.3
       Fresh syn v1.0.58
       Fresh digest v0.9.0
       Fresh digest v0.8.1
       Fresh crypto-mac v0.7.0
       Fresh block-cipher-trait v0.6.2
       Fresh block-buffer v0.9.0
       Fresh block-cipher v0.7.1
       Fresh stream-cipher v0.3.2
       Fresh crypto-mac v0.8.0
       Fresh block-buffer v0.7.3
       Fresh dirs v2.0.2
       Fresh parking_lot v0.11.0
       Fresh quote v0.6.13
       Fresh dirs v3.0.1
       Fresh parking_lot v0.10.2
       Fresh regex v1.3.9
       Fresh num-integer v0.1.43
       Fresh security-framework v0.4.4
       Fresh rand_chacha v0.2.2
       Fresh serde_derive v1.0.115
       Fresh synstructure v0.12.4
       Fresh mio-uds v0.6.8
       Fresh tokio-macros v0.2.5
       Fresh futures-macro v0.3.9
       Fresh pin-project-internal v0.4.23
       Fresh pest_generator v2.1.3
       Fresh crossbeam-epoch v0.8.2
       Fresh pin-project-internal v1.0.4
       Fresh hmac v0.7.1
       Fresh aes-soft v0.3.3
       Fresh blake2 v0.8.1
       Fresh ctr v0.3.2
       Fresh stream-cipher v0.4.1
       Fresh sha2 v0.8.2
       Fresh aes-soft v0.4.0
       Fresh sha2 v0.9.1
       Fresh hmac v0.8.1
       Fresh blake3 v0.3.6
       Fresh sha-1 v0.9.1
       Fresh syn v0.15.44
       Fresh rand v0.7.3
       Fresh serde v1.0.115
       Fresh zeroize_derive v1.0.0
       Fresh chrono v0.4.15
       Fresh pem v0.7.0
       Fresh env_logger v0.6.2
       Fresh tokio v0.2.22
       Fresh futures-util v0.3.9
       Fresh pin-project v0.4.23
       Fresh pest_derive v2.1.0
       Fresh lioness v0.1.2
       Fresh hkdf v0.8.0
       Fresh aes-ctr v0.3.0
       Fresh ctr v0.4.0
       Fresh hkdf v0.9.0
       Fresh sled v0.33.0
       Fresh sled v0.31.0
       Fresh pin-project v1.0.4
       Fresh zeroize v1.1.0
       Fresh rand_distr v0.2.2
       Fresh pretty_env_logger v0.3.1
       Fresh pemstore v0.1.0 (/Users/rex/nym/common/pemstore)
       Fresh tokio-util v0.3.1
       Fresh serde_json v1.0.57
       Fresh tempfile v3.1.0
       Fresh futures-executor v0.3.9
       Fresh serde_urlencoded v0.6.1
       Fresh mime_guess v2.0.3
       Fresh tungstenite v0.11.1
       Fresh toml v0.5.6
       Fresh nonexhaustive-delayqueue v0.1.0 (/Users/rex/nym/common/nonexhaustive-delayqueue)
       Fresh humantime-serde v1.0.1
       Fresh snafu-derive v0.4.4
       Fresh ipnetwork v0.17.0
       Fresh curve25519-dalek v3.0.0
       Fresh aes-ctr v0.4.0
       Fresh curve25519-dalek v2.1.0
       Fresh native-tls v0.2.4
       Fresh futures v0.3.9
       Fresh h2 v0.2.6
       Fresh tokio-tungstenite v0.11.0
       Fresh handlebars v3.4.0
       Fresh snafu v0.4.4
       Fresh sphinx v0.1.0 (https://github.com/nymtech/sphinx?rev=283dcc77dec8ee9ed3bed58c2b878e9c18320723#283dcc77)
       Fresh x25519-dalek v1.1.0
       Fresh ed25519-dalek v1.0.0
       Fresh tokio-tls v0.3.1
       Fresh hyper v0.13.7
       Fresh config v0.1.0 (/Users/rex/nym/common/config)
       Fresh publicsuffix v1.5.4
       Fresh nymsphinx-types v0.1.0 (/Users/rex/nym/common/nymsphinx/types)
       Fresh hyper-tls v0.4.3
       Fresh crypto v0.1.0 (/Users/rex/nym/common/crypto)
       Fresh reqwest v0.10.8
       Fresh nymsphinx-addressing v0.1.0 (/Users/rex/nym/common/nymsphinx/addressing)
       Fresh nymsphinx-params v0.1.0 (/Users/rex/nym/common/nymsphinx/params)
       Fresh metrics-client v0.1.0 (/Users/rex/nym/common/client-libs/metrics-client)
       Fresh topology v0.1.0 (/Users/rex/nym/common/topology)
       Fresh nymsphinx-forwarding v0.1.0 (/Users/rex/nym/common/nymsphinx/forwarding)
       Fresh nymsphinx-chunking v0.1.0 (/Users/rex/nym/common/nymsphinx/chunking)
       Fresh nymsphinx-framing v0.1.0 (/Users/rex/nym/common/nymsphinx/framing)
       Fresh socks5-requests v0.1.0 (/Users/rex/nym/common/socks5/requests)
       Fresh nymsphinx-acknowledgements v0.1.0 (/Users/rex/nym/common/nymsphinx/acknowledgements)
       Fresh nymsphinx-anonymous-replies v0.1.0 (/Users/rex/nym/common/nymsphinx/anonymous-replies)
       Fresh validator-client v0.1.0 (/Users/rex/nym/common/client-libs/validator-client)
       Fresh proxy-helpers v0.1.0 (/Users/rex/nym/common/socks5/proxy-helpers)
       Fresh nymsphinx-cover v0.1.0 (/Users/rex/nym/common/nymsphinx/cover)
       Fresh mixnode-common v0.1.0 (/Users/rex/nym/common/mixnode-common)
       Fresh nymsphinx v0.1.0 (/Users/rex/nym/common/nymsphinx)
   Compiling gateway-requests v0.1.0 (/Users/rex/nym/gateway/gateway-requests)
       Fresh websocket-requests v0.1.0 (/Users/rex/nym/clients/native/websocket-requests)
   Compiling mixnet-client v0.1.0 (/Users/rex/nym/common/client-libs/mixnet-client)
       Fresh nym-network-requester v0.9.2 (/Users/rex/nym/service-providers/network-requester)
     Running `rustc --crate-name gateway_requests --edition=2018 gateway/gateway-requests/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=9a1d3a08b488b5ec -C extra-filename=-9a1d3a08b488b5ec --out-dir /Users/rex/nym/target/debug/deps -C incremental=/Users/rex/nym/target/debug/incremental -L dependency=/Users/rex/nym/target/debug/deps --extern bs58=/Users/rex/nym/target/debug/deps/libbs58-8781077c0809a643.rmeta --extern crypto=/Users/rex/nym/target/debug/deps/libcrypto-89aadae1275909f2.rmeta --extern futures=/Users/rex/nym/target/debug/deps/libfutures-07f71501321c5f1d.rmeta --extern log=/Users/rex/nym/target/debug/deps/liblog-3f3a7bafc96d9436.rmeta --extern nymsphinx=/Users/rex/nym/target/debug/deps/libnymsphinx-84e2284b9b3cf24b.rmeta --extern pemstore=/Users/rex/nym/target/debug/deps/libpemstore-6a72abcb817f7fc7.rmeta --extern rand=/Users/rex/nym/target/debug/deps/librand-2c84c32739c6faf4.rmeta --extern serde=/Users/rex/nym/target/debug/deps/libserde-a63414a20bfdade5.rmeta --extern serde_json=/Users/rex/nym/target/debug/deps/libserde_json-0bd690e79db9d533.rmeta --extern tungstenite=/Users/rex/nym/target/debug/deps/libtungstenite-8757a3993f46104c.rmeta -L native=/Users/rex/nym/target/debug/build/blake3-42c8ddfa0ccf0ae9/out -L native=/Users/rex/nym/target/debug/build/blake3-42c8ddfa0ccf0ae9/out`
     Running `rustc --crate-name mixnet_client --edition=2018 common/client-libs/mixnet-client/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=809579f5e855bee1 -C extra-filename=-809579f5e855bee1 --out-dir /Users/rex/nym/target/debug/deps -C incremental=/Users/rex/nym/target/debug/incremental -L dependency=/Users/rex/nym/target/debug/deps --extern futures=/Users/rex/nym/target/debug/deps/libfutures-07f71501321c5f1d.rmeta --extern log=/Users/rex/nym/target/debug/deps/liblog-3f3a7bafc96d9436.rmeta --extern nymsphinx=/Users/rex/nym/target/debug/deps/libnymsphinx-84e2284b9b3cf24b.rmeta --extern tokio=/Users/rex/nym/target/debug/deps/libtokio-69a5f77417100d1c.rmeta --extern tokio_util=/Users/rex/nym/target/debug/deps/libtokio_util-e2cdea7867848036.rmeta -L native=/Users/rex/nym/target/debug/build/blake3-42c8ddfa0ccf0ae9/out -L native=/Users/rex/nym/target/debug/build/blake3-42c8ddfa0ccf0ae9/out`
warning: Error finalizing incremental compilation session directory `/Users/rex/nym/target/debug/incremental/mixnet_client-1vszuqjmeoj84/s-fvhdemef5w-7jqjv6-working`: No such file or directory (os error 2)

warning: 1 warning emitted

error: internal compiler error: failed to process buffered lint here
  --> common/client-libs/mixnet-client/src/forwarder.rs:71:17
   |
71 |                 debug!("failed to forward the packet - {}", err)
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0:        0x11487614c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd841328aa7dc06cc
   1:        0x1148da64d - core::fmt::write::hefe95a44532fe6ed
   2:        0x114868566 - std::io::Write::write_fmt::haeb49d4f9ecd789d
   3:        0x11487a019 - std::panicking::default_hook::{{closure}}::h465a961bccd4d390
   4:        0x114879ba9 - std::panicking::default_hook::h7e189743c9acab0a
   5:        0x10cb67b18 - rustc_driver::report_ice::h560f670b897314ed
   6:        0x11487a7fe - std::panicking::rust_panic_with_hook::he74e9eac8174d6dd
   7:        0x11487a305 - std::panicking::begin_panic_handler::{{closure}}::h122c1e0e85c150a9
   8:        0x114876608 - std::sys_common::backtrace::__rust_end_short_backtrace::he103784f07f740ac
   9:        0x11487a26a - _rust_begin_unwind
  10:        0x11490225b - std::panicking::begin_panic_fmt::h9385c4006b676237
  11:        0x1111601e6 - rustc_errors::HandlerInner::flush_delayed::ha814ae8fc66f459e
  12:        0x11115c3cb - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h604d573a9d19f76b
  13:        0x10cbaad0d - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::he1042ff96c3a2292
  14:        0x10cbb19a8 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hbbedb60f235c87aa
  15:        0x10cbac095 - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::h32ce24398f080a07
  16:        0x10cb970b1 - rustc_span::with_source_map::hb15b187d8726f95a
  17:        0x10cb18ed4 - rustc_interface::interface::create_compiler_and_run::h676e33808641f5cb
  18:        0x10cba3713 - std::sys_common::backtrace::__rust_begin_short_backtrace::h17f5da3f25073b11
  19:        0x10cb429a9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h099c825c1a0d0ef5
  20:        0x114887a0d - std::sys::unix::thread::Thread::new::thread_start::h23116ad77b076564
  21:     0x7fff205bb950 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-apple-darwin

note: compiler flags: -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `mixnet-client`

Caused by:
  process didn't exit successfully: `rustc --crate-name mixnet_client --edition=2018 common/client-libs/mixnet-client/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C metadata=809579f5e855bee1 -C extra-filename=-809579f5e855bee1 --out-dir /Users/rex/nym/target/debug/deps -C incremental=/Users/rex/nym/target/debug/incremental -L dependency=/Users/rex/nym/target/debug/deps --extern futures=/Users/rex/nym/target/debug/deps/libfutures-07f71501321c5f1d.rmeta --extern log=/Users/rex/nym/target/debug/deps/liblog-3f3a7bafc96d9436.rmeta --extern nymsphinx=/Users/rex/nym/target/debug/deps/libnymsphinx-84e2284b9b3cf24b.rmeta --extern tokio=/Users/rex/nym/target/debug/deps/libtokio-69a5f77417100d1c.rmeta --extern tokio_util=/Users/rex/nym/target/debug/deps/libtokio_util-e2cdea7867848036.rmeta -L native=/Users/rex/nym/target/debug/build/blake3-42c8ddfa0ccf0ae9/out -L native=/Users/rex/nym/target/debug/build/blake3-42c8ddfa0ccf0ae9/out` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
warning: Error finalizing incremental compilation session directory `/Users/rex/nym/target/debug/incremental/gateway_requests-bvflj9jxs0l4/s-fvhdemee3x-1dtkvdp-working`: No such file or directory (os error 2)

warning: 1 warning emitted

error: internal compiler error: failed to process buffered lint here
   --> gateway/gateway-requests/src/registration/handshake/state.rs:213:39
    |
213 | ...                   Err(_) => error!("Received a non-handshake message during the registration handshake! It's getting dropped."),
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> gateway/gateway-requests/src/registration/handshake/state.rs:215:30
    |
215 |                         _ => error!("Received non-text message during registration handshake"),
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0:        0x1014b414c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd841328aa7dc06cc
   1:        0x10151864d - core::fmt::write::hefe95a44532fe6ed
   2:        0x1014a6566 - std::io::Write::write_fmt::haeb49d4f9ecd789d
   3:        0x1014b8019 - std::panicking::default_hook::{{closure}}::h465a961bccd4d390
   4:        0x1014b7ba9 - std::panicking::default_hook::h7e189743c9acab0a
   5:        0x1080bcb18 - rustc_driver::report_ice::h560f670b897314ed
   6:        0x1014b87fe - std::panicking::rust_panic_with_hook::he74e9eac8174d6dd
   7:        0x1014b8305 - std::panicking::begin_panic_handler::{{closure}}::h122c1e0e85c150a9
   8:        0x1014b4608 - std::sys_common::backtrace::__rust_end_short_backtrace::he103784f07f740ac
   9:        0x1014b826a - _rust_begin_unwind
  10:        0x10154025b - std::panicking::begin_panic_fmt::h9385c4006b676237
  11:        0x10c6b51e6 - rustc_errors::HandlerInner::flush_delayed::ha814ae8fc66f459e
  12:        0x10c6b13cb - <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop::h604d573a9d19f76b
  13:        0x1080ffd0d - core::ptr::drop_in_place<rustc_session::parse::ParseSess>::he1042ff96c3a2292
  14:        0x1081069a8 - <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop::hbbedb60f235c87aa
  15:        0x108101095 - core::ptr::drop_in_place<rustc_interface::interface::Compiler>::h32ce24398f080a07
  16:        0x1080ec0b1 - rustc_span::with_source_map::hb15b187d8726f95a
  17:        0x10806ded4 - rustc_interface::interface::create_compiler_and_run::h676e33808641f5cb
  18:        0x1080f8713 - std::sys_common::backtrace::__rust_begin_short_backtrace::h17f5da3f25073b11
  19:        0x1080979a9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h099c825c1a0d0ef5
  20:        0x1014c5a0d - std::sys::unix::thread::Thread::new::thread_start::h23116ad77b076564
  21:     0x7fff205bb950 - __pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-apple-darwin

note: compiler flags: -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: build failed
```

**Comment by jonas-schievink** [comment] 2021-02-01 21:37
Duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-01 21:37 UTC
Labels: C-bug, I-ICE, T-compiler
