### ISSUE TITLE
Miscompilation of alacritty?

### ISSUE THREAD

**Issue by vorner** [rust-lang/rust#52900] opened 2018-07-31 11:33 UTC
Hello

When I try to compile alacritty (24a74d44882f89d16d197f2f2854208112938acb) with current nightly, the resulting binary crashes with SIGILL. It works well if compiled with stable or with nightly-2018-07-19.

Backtrace from gdb:

```
Program received signal SIGILL, Illegal instruction.
0x000055555571ce8a in winit::platform::platform::x11::xdisplay::XConnection::new () at /checkout/src/libcore/ptr.rs:59
59	/checkout/src/libcore/ptr.rs: No such file or directory.
(gdb) bt
#0  0x000055555571ce8a in winit::platform::platform::x11::xdisplay::XConnection::new ()
    at /checkout/src/libcore/ptr.rs:59
#1  winit::platform::platform::X11_BACKEND::__init ()
    at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/mod.rs:54
#2  0x000055555570c330 in <std::thread::local::LocalKey<T>>::with () at /checkout/src/libstd/thread/local.rs:255
#3  0x00005555556b4258 in alacritty::display::Display::new ()
    at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/mod.rs:437
#4  0x00005555558fd7d8 in alacritty::main () at src/main.rs:101
```

```$ rustc --version --verbose
rustc 1.29.0-nightly (54628c8ea 2018-07-30)
binary: rustc
commit-hash: 54628c8ea844956f3f4f416b82067c634eb09f7b
commit-date: 2018-07-30
host: x86_64-unknown-linux-gnu
release: 1.29.0-nightly
LLVM version: 7.0
```

I'm not sure if I should suspect error in rustc or somewhere around unsafe code in alacritty, but something must have changed in rustc that makes it manifest between the two versions.

Is there anything more I could try or some more info I could provide?

**Comment by nagisa** [comment] 2018-07-31 12:02
Most likely a duplicate of https://github.com/rust-lang/rust/issues/52875

**Comment by pnkfelix** [comment] 2018-08-02 14:47
visited for triage. Under the assumption that this is indeed a duplicate of #52875, closing this as non-actionable on our part.

**Closed by pnkfelix** 2018-08-02 14:47 UTC
Labels: T-compiler, regression-from-stable-to-nightly
