### ISSUE TITLE
[Optimization] Equivalent functions are not merged because their panic information differs.

### ISSUE THREAD

**Issue by LunarLambda** [rust-lang/rust#80021] opened 2020-12-14 10:14 UTC
I was playing around in the compiler explorer with APIs using `AsRef<T>` to provide more ergonomic interfaces. 
My example used `AsRef<[u8]>` to allow an API to use string literals, byte arrays, byte strings, etc.

I wanted to know if there was an elegant way to avoid monomorphization overhead for large functions that only differ by a `AsRef::as_ref` call at the very top, or if the compiler could do this for me in optmized builds.

My tests can be found here:

https://godbolt.org/z/5MzKMT

However, far more interestingly, I saw that `asref_inner` and `asref_direct` were not merged by the compiler in an optimized build, despite being 100% the same code.

The only difference is that they have different source location info for a potential panic.
Perhaps this is a contrived case, since fully equivalent functions are probably rare in real code,
however I still thought it was worth bringing up.

Perhaps the functions could be merged if the panic information was smuggled through a register or the stack at the call site instead?

**Comment by nagisa** [comment] 2020-12-14 23:14
Extremely unlikely to be actionable from the standpoint of code optimizations. If there's _any_ change made to improve this particular example, it'd have to be around how much panic information we preserve (or scrub), potentially exposed via some compiler flag. 

(Changes to how panic information is passed in has been rejected in multiple instances in the past, because it is optimised for amount of code generated and regressions there are undesirable).

Removing A-mir-opt for now, but also inclined to just close this issue.

**Comment by jyn514** [comment] 2020-12-15 03:17
> I wanted to know if there was an elegant way to avoid monomorphization overhead for large functions that only differ by a AsRef::as_ref call at the very top, or if the compiler could do this for me in optmized builds.

This is https://github.com/rust-lang/rust/issues/77960.

**Comment by LunarLambda** [comment] 2020-12-17 11:53
> Extremely unlikely to be actionable from the standpoint of code optimizations. If there's _any_ change made to improve this particular example, it'd have to be around how much panic information we preserve (or scrub), potentially exposed via some compiler flag.
> 
> (Changes to how panic information is passed in has been rejected in multiple instances in the past, because it is optimised for amount of code generated and regressions there are undesirable).
> 
> Removing A-mir-opt for now, but also inclined to just close this issue.

I see



> > I wanted to know if there was an elegant way to avoid monomorphization overhead for large functions that only differ by a AsRef::as_ref call at the very top, or if the compiler could do this for me in optmized builds.
> 
> This is #77960.

Thank you!

**Comment by Enselic** [comment] 2023-12-16 10:03
Triage: This was proposed to be closed as "not feasible". Let's close it now.

**Closed by Enselic** 2023-12-16 10:03 UTC
Labels: I-heavy
