### ISSUE TITLE
ICE: librustc/traits/codegen/mod.rs:68: Encountered error `OutputTypeParameterMismatch`

### ISSUE THREAD

**Issue by earthengine** [rust-lang/rust#53420] opened 2018-08-16 06:48 UTC
I was attempt to apply the trick of [this blog post](https://lukaskalbertodt.github.io/2018/08/03/solving-the-generalized-streaming-iterator-problem-without-gats.html#workaround-b-hrtbs--the-family-trait-pattern) to improve my named closures crate. But I run into this ICE, which is unfortunately in stable.

https://play.rust-lang.org/?gist=22299e701c9bdb472a5fc8fe303b7fa1&version=stable&mode=debug&edition=2015

```rust
use std::marker::PhantomData;

trait Lt<'a> {
    type T;
}
struct Id<T>(PhantomData<T>);
impl<'a,T> Lt<'a> for Id<T> {
    type T = T;
}

struct Ref<T>(PhantomData<T>) where T: ?Sized;
impl<'a,T> Lt<'a> for Ref<T>
where T: 'a + Lt<'a> + ?Sized
{
    type T = &'a T;
}
struct Mut<T>(PhantomData<T>) where T: ?Sized;
impl<'a,T> Lt<'a> for Mut<T>
where T: 'a + Lt<'a> + ?Sized
{
    type T = &'a mut T;
}

struct C<I,O>(for<'a> fn(<I as Lt<'a>>::T) -> O) where I: for<'a> Lt<'a>;


fn main() {
    let c = C::<Id<_>,_>(|()| 3);
    c.0(());

}
```

This is freshly occur so I didn't simplify the code.

**Comment by earthengine** [comment] 2018-08-16 06:54
[Simplified](https://play.rust-lang.org/?gist=b751b1b95c3bc41b5ed06effd9dc02fb&version=stable&mode=debug&edition=2015):

```rust
trait Lt<'a> {
    type T;
}
struct Id<T>(T);
impl<'a,T> Lt<'a> for Id<T> {
    type T = T;
}

struct C<I>(for<'a> fn(<I as Lt<'a>>::T)) where I: for<'a> Lt<'a>;


fn main() {
    C::<Id<_>>(|()| {});
}
```

**Comment by earthengine** [comment] 2018-08-17 02:40
[Simplified more](https://play.rust-lang.org/?gist=fd141276544e7973243542e1a78fb2d0&version=stable&mode=debug&edition=2015):

```rust
trait Lt<'a> {
    type T;
}
struct Id<T>(T);
impl<'a,T> Lt<'a> for Id<T> {
    type T = T;
}

fn main() {
    let _: for<'a> fn(<Id<()> as Lt<'a>>::T) = |()| {};
}
```

**Comment by earthengine** [comment] 2018-08-17 05:03
Manually desugaring `FnOnce` in nightly works, but not with the sugared stable `FnOnce`:

```rust
//Working
let _:&FnOnce<(<() as Lt<'_>>::T,),Output=()> = &|_|{};
//Not working
let _:&FnOnce(<() as Lt<'_>>::T) = &|_|{};
```

Suggests the problem is in desugaring `FnXXX` traits.

**Comment by earthengine** [comment] 2018-08-17 06:35
A more scary ICE: unexpected panic

```rust
#![feature(unboxed_closures)]
trait Lt<'a> {
    type T;
}
impl<'a> Lt<'a> for () {
    type T = ();
}

fn main() {
    let v:<() as Lt<'_>>::T = ();
    let f:&mut FnMut<(_,),Output=()> = &mut |_:<() as Lt<'_>>::T|{};
    f(v);
}
```

**Comment by earthengine** [comment] 2018-08-22 11:01
Please add "nll" tag as this is emmited by `rustc_mir::borrow_check::nll::type_check::TypeChecker::typeck_mir`

r? @matthewjasper

**Comment by earthengine** [comment] 2018-09-04 22:37
@alexreg 

I need answer of the following question:

When should `<() as Lt<'_>>::T` being substituted to `()`? It seems like, for other kind of types (structs, enums, tuples etc), this substitution is done properly, except that in case of `fn` or `FnXXX` this is not.

So I suppose the fix would be in the monorphization. After monorphization the substitution should be done but it didn't, which causes problems in codegen.

**Comment by earthengine** [comment] 2018-09-04 23:27
Found the following code in "/src/librustc/traits/select.rs":

```rust
    /// In the case of closure types and fn pointers,
    /// we currently treat the input type parameters on the trait as
    /// outputs. This means that when we have a match we have only
    /// considered the self type, so we have to go back and make sure
    /// to relate the argument types too.  This is kind of wrong, but
    /// since we control the full set of impls, also not that wrong,
    /// and it DOES yield better error messages (since we don't report
    /// errors as if there is no applicable impl, but rather report
    /// errors are about mismatched argument types.
    ///
    /// Here is an example. Imagine we have a closure expression
    /// and we desugared it so that the type of the expression is
    /// `Closure`, and `Closure` expects an int as argument. Then it
    /// is "as if" the compiler generated this impl:
    ///
    ///     impl Fn(int) for Closure { ... }
    ///
    /// Now imagine our obligation is `Fn(usize) for Closure`. So far
    /// we have matched the self-type `Closure`. At this point we'll
    /// compare the `int` to `usize` and generate an error.
    ///
    /// Note that this checking occurs *after* the impl has selected,
    /// because these output type parameters should not affect the
    /// selection of the impl. Therefore, if there is a mismatch, we
    /// report an error to the user.
    fn confirm_poly_trait_refs(&mut self,
                               obligation_cause: ObligationCause<'tcx>,
                               obligation_param_env: ty::ParamEnv<'tcx>,
                               obligation_trait_ref: ty::PolyTraitRef<'tcx>,
                               expected_trait_ref: ty::PolyTraitRef<'tcx>)
                               -> Result<Vec<PredicateObligation<'tcx>>, SelectionError<'tcx>>
    {
        let obligation_trait_ref = obligation_trait_ref.clone();
        self.infcx
            .at(&obligation_cause, obligation_param_env)
            .sup(obligation_trait_ref, expected_trait_ref)
            .map(|InferOk { obligations, .. }| obligations)
            .map_err(|e| OutputTypeParameterMismatch(expected_trait_ref, obligation_trait_ref, e))
    }
```

seems like the following assumsion

```
    /// Note that this checking occurs *after* the impl has selected,
    /// because these output type parameters should not affect the
    /// selection of the impl. Therefore, if there is a mismatch, we
    /// report an error to the user.
```

didn't hold in this case so the error is reported.

**Comment by earthengine** [comment] 2018-09-05 00:54
Or, is the following (/src/librustc/traits/select.rs)

```rust
    fn confirm_fn_pointer_candidate(&mut self, obligation: &TraitObligation<'tcx>)
        -> Result<VtableFnPointerData<'tcx, PredicateObligation<'tcx>>, SelectionError<'tcx>>
    {
        debug!("confirm_fn_pointer_candidate({:?})",
               obligation);

        // ok to skip binder; it is reintroduced below
        let self_ty = self.infcx.shallow_resolve(*obligation.self_ty().skip_binder());
        let sig = self_ty.fn_sig(self.tcx());
        let trait_ref =
            self.tcx().closure_trait_ref_and_return_type(obligation.predicate.def_id(),
                                                         self_ty,
                                                         sig,
                                                         util::TupleArgumentsFlag::Yes)
            .map_bound(|(trait_ref, _)| trait_ref);

        let Normalized { value: trait_ref, obligations } =
            project::normalize_with_depth(self,
                                          obligation.param_env,
                                          obligation.cause.clone(),
                                          obligation.recursion_depth + 1,
                                          &trait_ref);

        self.confirm_poly_trait_refs(obligation.cause.clone(),
                                     obligation.param_env,
                                     obligation.predicate.to_poly_trait_ref(),
                                     trait_ref)?;
        Ok(VtableFnPointerData { fn_ty: self_ty, nested: obligations })
    }
```
correct? I mean the following assumsion:

```
// ok to skip binder; it is reintroduced below
```
given the fact that we have trouble to unify `<() as Lt<'_>>::T` with `()`?

**Comment by earthengine** [comment] 2018-09-07 00:28
@nikomatsakis 

I see you have been working on #18993 (HRTB). This issue seems to be in the concept "late bound regions" you introduced: `<() as Lt<'_>>::T` is a late bound region, but binding is way TOOOO late in this case and actually being never.

Can you please look into this and tell me when it is supposed to be bound?

(I can see the difficulty here: there is a lifetime but was never specified and no clue was given to infer it, making it hard to assume anything on it)

**Comment by pnkfelix** [comment] 2018-10-04 12:44
assigning self for preliminary investigation

**Comment by pnkfelix** [comment] 2018-10-04 12:46
Since this is an ICE and is not using any unstable features (and in fact, reproduces on the stable channel), I have tagged it as P-high for now.

That means we'll be visiting it regularly during the weekly compiler team meeting.

**Comment by pnkfelix** [comment] 2018-10-04 12:54
Also: Thank you @earthengine for your patience as well as your copious notes from your own investigations.

My current hypothesis is that normalization is supposed to be doing the substitution mapping  `<() as Lt<'_>>::T`  to `()`, but for some reason is missing the case(s) that you have identified here.

**Comment by pnkfelix** [comment] 2018-10-04 14:10
Discussed at T-compiler meeting. Seems to be duplicate of issue #29997. Closing as duplicate.

**Closed by pnkfelix** 2018-10-04 14:10 UTC
Labels: A-associated-items, A-typesystem, I-ICE, P-high, T-compiler

**Comment by pnkfelix** [comment] 2019-07-10 10:11
(duplicate of #62529, which is where I will try to track future instances of this field of ICE.)
