### ISSUE TITLE
Trait suggestions should use outermost candidates

### ISSUE THREAD

**Issue by AndiDog** [rust-lang/rust#31323] opened 2016-01-31 16:55 UTC
Beginning with issue #21405, Rust combines multiple identical candidates into one (in some way). Since crates typically `pub use` the traits on the outermost level (e.g. `module::TheTrait` instead of `module::inner::detail::TheTrait`), the outermost candidate should be displayed as suggestion.

Here's a real-life example:

``` rust
main.rs:44:21: 44:62 error: no method named `json_as` found for type `&'r mut nickel::request::Request<'mw, 'conn, _>` in the current scope
main.rs:44                let dir = request.json_as::<BlaBla>().unwrap().dir;
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<nickel macros>:24:12: 24:42 note: in this expansion of as_block! (defined in <nickel macros>)
<nickel macros>:10:1: 10:60 note: in this expansion of _middleware_inner! (defined in <nickel macros>)
main.rs:43:47: 48:3 note: in this expansion of middleware! (defined in <nickel macros>)
main.rs:44:21: 44:62 help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
main.rs:44:21: 44:62 help: candidate #1: use `nickel::json_body_parser::JsonBody`
```

However the trait "JsonBody" can be imported with just `use nickel::JsonBody`.

**Comment by Aatch** [comment] 2016-02-01 02:48
I'm not sure what the code is doing there, but using the shortest path version might be acceptable.

**Comment by steveklabnik** [comment] 2019-12-25 17:09
Triage: I can't reproduce this because there aren't good enough instructions; could you provide some example code that triggers this? Thanks!

**Comment by Dylan-DPC** [comment] 2023-05-28 13:53
Closing this as this issue is vague and there's no further updates on it.

**Closed by Dylan-DPC** 2023-05-28 13:53 UTC
Labels: C-enhancement, A-diagnostics, T-compiler
