### ISSUE TITLE
Cannot unify associated type bounds across traits

### ISSUE THREAD

**Issue by Pratyush** [rust-lang/rust#69640] opened 2020-03-02 17:39 UTC
Hi!

I tried this code:

```rust
trait Engine {
    type G: Curve<F = Self::F>;
    type F;
}

trait Curve: core::ops::MulAssign<<Self as Curve>::F> {
    type F;
}

fn should_work<E: Engine>(mut p: E::G, f: E::F) {
    p *= f
}

fn main() {
    println!("Hello, world!");
}
```

I expected this to compile, because I clearly specify that `G::F = Self::F`, but it seems that this unification doesn't occur, resulting in the following compiler error:
```
Compiling playground v0.0.1 (/playground)
error[E0277]: cannot multiply-assign `<E as Engine>::F` to `<E as Engine>::G`
  --> src/main.rs:11:7
   |
6  | trait Curve: core::ops::MulAssign<<Self as Curve>::F> {
   | ----------------------------------------------------- required by `Curve`
...
10 | fn test<E: Engine>(mut p: E::G, f: E::F) {
   |                                         - help: consider further restricting the associated type: `where <E as Engine>::G: std::ops::MulAssign<<E as Engine>::F>`
11 |     p *= f
   |       ^^ no implementation for `<E as Engine>::G *= <E as Engine>::F`
   |
   = help: the trait `std::ops::MulAssign<<E as Engine>::F>` is not implemented for `<E as Engine>::G`

error[E0308]: mismatched types
  --> src/main.rs:11:10
   |
11 |     p *= f
   |          ^ expected Curve::F, found Engine::F
   |
   = note: expected associated type `<<E as Engine>::G as Curve>::F`
              found associated type `<E as Engine>::F`
```
Here's a playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c008af6306a36b074e3704fe6b474c84

### Meta
This reproduces on the latest stable, beta, and nightly.

This might be related to #20775 and #48822, but not sure.

**Comment by jonas-schievink** [comment] 2020-03-02 18:01
It works with an additional `E::G: Curve<F = E::F>` bound on `test`. Therefore, closing as a duplicate of https://github.com/rust-lang/rust/issues/20671.

**Closed by jonas-schievink** 2020-03-02 18:01 UTC
Labels: C-bug
