### ISSUE TITLE
visibility modifiers ignored for method-defining macros

### ISSUE THREAD

**Issue by blaenk** [rust-lang/rust#21412] opened 2015-01-20 06:54 UTC
I created a macro that intended to define a public static method in an implementation. However, the `pub` modifier is essentially ignored. First, it's apparently not allowed within the macro definition, and then it's ignored if I put it outside and before the macro call:

``` rust
mod m {
    macro_rules! render_function {
        ($name:ident) => (
            fn $name(output: &mut i32, input: &i32) -> i32 {
                5i32
            }
        );
    }

    struct S;

    impl S {
        fn x() {}
    
        pub render_function!(test);
    }
}

fn main() {
    let x = m::S::test(&mut 3, &4);
}
```

```
<anon>:20:13: 20:23 error: static method `test` is private
<anon>:20     let x = m::S::test(&mut 3, &4);
```

[playpen](http://is.gd/DR85BI)

**Comment by blaenk** [comment] 2015-01-20 07:03
For completeness I should state what is probably already obvious, that as a workaround I ended up having to contain an entire `impl` within the macro definition which itself contained the function definition, like this:

``` rust
macro_rules! render_function {
    ($name:ident) => (
        impl S {
            pub fn $name(output: &mut i32, input: &i32) -> i32 {
                5i32
            }
        }
    );
}
```

**Comment by blaenk** [comment] 2015-01-20 21:54
If I change this to define a function in a module (instead of in a struct impl), it _does_ allow me to put `pub` before the `fn` within the macro definition and it _isn't_ ignored, whereas, as I said in the first post, if I put `pub fn` in the macro definition and then call the macro inside the struct impl, it would complain about a syntax error.

**Comment by shepmaster** [comment] 2015-01-22 01:50
Dupe of #17436 or #18317 or #14660?

**Comment by alexcrichton** [comment] 2015-01-22 05:23
I believe so, thanks @shepmaster!

**Closed by alexcrichton** 2015-01-22 05:23 UTC
Labels: A-macros
