### ISSUE TITLE
Use io::Result in prototype documentation

### ISSUE THREAD

**Issue by xavierd** [rust-lang/rust#62122] opened 2019-06-25 17:36 UTC
For a newcomer, there is no reason to expect the return value of any I/O function (ie: `std::io::Result`) to be any different from `std::result::Result` as they are both shown to be `Result` in the documentation.

One easy way to disambiguate this would be to show the prototype to use `io::Result` instead of `Result`. For instance, the `open` function is shown as being:

`pub fn open<P: AsRef<Path>>(path: P) -> Result<File>`

It should be:

`pub fn open<P: AsRef<Path>>(path: P) -> io::Result<File>`

**Comment by jyn514** [comment] 2020-08-27 03:38
Duplicate of https://github.com/rust-lang/rust/issues/74924

**Closed by jyn514** 2020-08-27 03:38 UTC
Labels: C-feature-request, T-rustdoc
