### ISSUE TITLE
panicked at 'assertion failed: self.is_collecting_in_band_lifetimes'

### ISSUE THREAD

**Issue by davidszotten** [rust-lang/rust#52676] opened 2018-07-24 20:35 UTC
main.rs:
```
#![feature(rust_2018_preview)]

#[derive(Debug)]
struct Foo<'_> {
    foo: &'a str,
}


fn main() {
}
```

## Meta

`rustc --version --verbose`:
```
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
binary: rustc
commit-hash: 6a1c0637ce44aeea6c60527f4c0e7fb33f2bcd0d
commit-date: 2018-07-23
host: x86_64-apple-darwin
release: 1.29.0-nightly
LLVM version: 7.0
```

Backtrace:
```
thread 'main' panicked at 'assertion failed: self.is_collecting_in_band_lifetimes', librustc/hir/lowering.rs:738:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc::hir::lowering::LoweringContext::lower_lifetime
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
   9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
  10: rustc::hir::lowering::LoweringContext::lower_generics
  11: rustc::hir::lowering::LoweringContext::lower_item
  12: <rustc::hir::lowering::LoweringContext::lower_crate::ItemLowerer<'lcx, 'interner> as syntax::visit::Visitor<'lcx>>::visit_item
  13: rustc::hir::lowering::lower_crate
  14: rustc::util::common::time
  15: rustc_driver::driver::phase_2_configure_and_expand
  16: rustc_driver::driver::compile_input
  17: rustc_driver::run_compiler_with_pool
  18: <scoped_tls::ScopedKey<T>>::set
  19: <scoped_tls::ScopedKey<T>>::set
  20: syntax::with_globals
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  22: __rust_maybe_catch_panic
  23: rustc_driver::run
  24: rustc_driver::main
  25: std::rt::lang_start::{{closure}}
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: main
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.29.0-nightly (6a1c0637c 2018-07-23) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

**Comment by zackmdavis** [comment] 2018-07-25 01:45
Likely duplicate of #52098.

**Closed** 2018-09-30 06:10 UTC
