### ISSUE TITLE
`expr` metavariable drops commas

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/rust#98906] opened 2022-07-04 22:09 UTC
When matching an expression in a `macro_rules`, trailing commas in argument lists and initializers disappear. 

```rust
macro_rules! compare {
    ($expr: expr) => {
        assert_eq!(stringify!($expr), "Foo { bar: 32, }");
    };
}

compare!(Foo { foo: 32, }); // fails
              // this ^ comma disappears
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fafdfe051f645148a4a5b9fa411f4657)

**Comment by robertbastian** [comment] 2022-07-04 22:19
(this is not an issue with `stringify`, I'm actually encountering this when I pass the expression into the `quote` macro)

**Comment by sffc** [comment] 2023-09-11 17:24
To be clear, the use case here is to check an arbitrary TokenStream, such as one generated by a derive macro, against code in `stringify!($expr)`. I understand that the stringified form of TokenStream is not stable, but two TokenStreams should have the same `ToString`.

**Comment by fmease** [comment] 2024-01-25 14:58
As already mentioned in this thread, the output of `stringify!` is not stable. Closing as wontfix / works as intended.

> To be clear, the use case here is to check an arbitrary TokenStream, such as one generated by a derive macro, against code in `stringify!($expr)`. I understand that the stringified form of TokenStream is not stable, but two TokenStreams should have the same `ToString`.

Please provide a concrete reproducer for this if you think it doesn't directly relate to `stringify`.

**Closed by fmease** 2024-01-25 14:58 UTC
Labels: A-macros, T-compiler, C-bug

**Comment by robertbastian** [comment] 2024-06-20 21:47
I did mention that this is not an issue with the `stringify!` macro, but with macro variables. Here's a reproduction using `quote!`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c168c46ac64ef031f0f9b3c271aa63ab
