### ISSUE TITLE
Invalid opcode generated with anonymous registers in inline assembly

### ISSUE THREAD

**Issue by negge** [rust-lang/rust#94370] opened 2022-02-25 20:03 UTC
I tried this code in the rust playground here (https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=05d8e52640801f67b600cef3e03fc6e8)

```rust
use std::arch::asm;

fn main() {
    let mut x: u64 = 4;
    let s: u8 = 1;
    unsafe {
        asm!(
            "mov {tmp}, {x}",
            "shl {tmp}, {s}",
            "shl {x}, 2",
            "add {x}, {tmp}",
            x = inout(reg) x,
            s = in(reg_byte) s,
            tmp = out(reg) _,
        );
    }
    println!("{}", x);
}
```

I expected to get the output `24`.

Instead, I got a compiler error as it tried to store `s` in `dl` register.

```
Compiling playground v0.0.1 (/playground)
error: invalid operand for instruction
 [--> src/main.rs:9:14
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=05d8e52640801f67b600cef3e03fc6e8#)  |
9 |             "shl {tmp}, {s}",
  |              ^
  |
note: instantiated into assembly here
 --> <inline asm>:3:1
  |
3 | shl rcx, dl
  | ^

error: could not compile `playground` due to previous error
```

The byte code generator for x86 needs to store `s` in `cl` and then it will generate correct code.

**Comment by Amanieu** [comment] 2022-02-25 20:08
You need to explicitly tell the compiler to put the value in the `cl` register:
```rust
use std::arch::asm;

fn main() {
    let mut x: u64 = 4;
    let s: u8 = 1;
    unsafe {
        asm!(
            "mov {tmp}, {x}",
            "shl {tmp}, cl",
            "shl {x}, 2",
            "add {x}, {tmp}",
            x = inout(reg) x,
            tmp = out(reg) _,
            in("cl") s,
        );
    }
    println!("{}", x);
}
```

**Comment by negge** [comment] 2022-02-25 20:20
> You need to explicitly tell the compiler to put the value in the `cl` register:

It seems like this is something the compiler should know how to do right? The instruction `shl {reg}, {reg8}` can only be generated if `{reg8} = cl`.

**Comment by Amanieu** [comment] 2022-02-25 20:24
The compiler does not know anything about the assembly code, it only does string substitution based on the constraints given to it. You specified the `reg_byte` register class which means "any single-byte x86 register".

**Comment by nagisa** [comment] 2022-02-27 15:01
The behaviour designed here is as designed/intended, so I'll take the liberty to close this as a not-a-bug.

**Closed by nagisa** 2022-02-27 15:01 UTC
Labels: C-bug
