### ISSUE TITLE
poor diagnostic for unused function parameter

### ISSUE THREAD

**Issue by rickycodes** [rust-lang/rust#48021] opened 2018-02-05 20:42 UTC
got this warning:

![](https://pbs.twimg.com/media/DU7CWG_XkAAjOFY.jpg)

and then following the diagnostic suggestion it broke:

![](https://pbs.twimg.com/media/DU7CXMPXcAA3tow.jpg)

using `..` suppresses the warning and works as intended, so perhaps that's what should be suggested?

this was done using `notify`'s `raw_watcher`

**Comment by zackmdavis** [comment] 2018-02-05 21:29
(A duplicate of #47390, this is being fixed in #47922, after which the suggestion would be `cookie: _`.)

**Comment by TimNN** [comment] 2018-02-06 18:17
Closing as duplicate.

**Closed by TimNN** 2018-02-06 18:17 UTC
Labels: A-diagnostics
