### ISSUE TITLE
Diagnostics for two-phase borrows are confusing and unhelpful

### ISSUE THREAD

**Issue by Rik-de-Kort** [rust-lang/rust#77826] opened 2020-10-11 18:26 UTC
When I have a struct with two methods on the impl, both borrowing self mutably, I cannot chain the functions, like `s.second(s.first())`: I get a borrow checker error. Instead, I have to assign `s.first()` to an auxiliary variable. Might be related to #21906 but could not find any other similar issues.

```rust
struct S{}

impl S{
    fn first(&mut self) -> bool{
        true
    }
    
    fn second(&mut self, b: bool) {
        if b { println!{"Hello, world!"}; }
    }
}

fn main() {
    let mut s = S{};
    s.second(s.first());
}
```

I expected to see this happen: a simple print of "hello world!"

Instead, this happened:
````
   Compiling playground v0.0.1 (/playground)
error[E0499]: cannot borrow `s` as mutable more than once at a time
  --> src/main.rs:15:14
   |
15 |     s.second(s.first())
   |     - ------ ^ second mutable borrow occurs here
   |     | |
   |     | first borrow later used by call
   |     first mutable borrow occurs here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0499`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
````

It works fine if we use an auxiliary variable, which looks quite ugly to my mind:

````rust
fn main() {
    let mut s = S{};
    let f = s.first();
    s.second(s.first());
}
````

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=035e09c6d4d9ea3ce1aef8df9fd7dd0c)

**Comment by jyn514** [comment] 2020-10-11 19:10
This is 'intended' behavior in that it's not a bug: your code desugars to
```rust
S::second(&mut s, S::first(&mut s))
```
and now you can see that it's borrowed for `second` before the call to `first`. That said, the behavior is definitely unintuitive; see https://github.com/rust-lang/rust/issues/56254.

**Comment by camelid** [comment] 2020-10-11 21:26
Implementing #77834 should fix this.

**Comment by Rik-de-Kort** [comment] 2020-10-12 07:06
> This is 'intended' behavior in that it's not a bug: your code desugars to
> 
> ```rust
> S::second(&mut s, S::first(&mut s))
> ```
> 
> and now you can see that it's borrowed for `second` before the call to `first`. That said, the behavior is definitely unintuitive; see #56254.

This means I can learn something here, because I thought Rust was call by value? So wouldn't (or shouldn't) the bytecode calculate `S::first(&mut s)` first before entering the function? Or is there some parallel evaluation of arguments magic going on so that the compiler can't guarantee this?

**Comment by jyn514** [comment] 2020-10-12 13:53
Rust borrows the arguments in order: because `&mut s` comes before the call to `first()`, it's mutably borrowed before and can't be borrowed again. 'call by value' doesn't have anything to do with it.

**Comment by jyn514** [comment] 2020-12-12 20:59
I'm going to close this as a duplicate of https://github.com/rust-lang/rust/issues/77834, but I agree the diagnostic here should be improved.

**Closed by jyn514** 2020-12-12 20:59 UTC
Labels: D-confusing, T-compiler, T-lang
