### ISSUE TITLE
Internal error when compiling updated dependencies (hir/map/collector.rs:227)

### ISSUE THREAD

**Issue by cpetig** [rust-lang/rust#79534] opened 2020-11-29 12:07 UTC
### Code

```
git clone https://github.com/zesterer/teloren
cd teloren
cargo update
cargo build
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (e37f25aa3 2020-11-28)
binary: rustc
commit-hash: e37f25aa3f356546ab851e394d5598fc575eabda
commit-date: 2020-11-28
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

### Error output

```
$ RUST_BACKTRACE=1 cargo build
   Compiling ring v0.16.18
   Compiling uvth v3.1.1
   Compiling mio v0.6.22
   Compiling inotify v0.8.3
   Compiling directories-next v2.0.0
   Compiling parking_lot v0.11.1
   Compiling clap v2.33.3
   Compiling syn v1.0.52
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:1268 ~ ring[e9bc]::digest::sha2::)`,
 right: `DefId(0:1269 ~ ring[e9bc]::digest::sha2::::GFp_sha256_block_data_order)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
```

<details><summary><strong>Backtrace</strong></summary>
<p>
```
   0: rust_begin_unwind
             at /rustc/e37f25aa3f356546ab851e394d5598fc575eabda/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/e37f25aa3f356546ab851e394d5598fc575eabda/library/core/src/panicking.rs:92:14
   2: rustc_middle::hir::map::collector::NodeCollector::insert_entry
   3: rustc_hir::intravisit::walk_item
   4: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   5: rustc_hir::intravisit::walk_item
   6: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   7: rustc_hir::intravisit::walk_item
   8: <rustc_middle::hir::map::collector::NodeCollector as rustc_hir::intravisit::Visitor>::visit_item
   9: rustc_middle::hir::map::index_hir
  10: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  11: rustc_data_structures::stack::ensure_sufficient_stack
  12: rustc_query_system::query::plumbing::get_query_impl
  13: core::ops::function::FnOnce::call_once
  14: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  15: rustc_data_structures::stack::ensure_sufficient_stack
  16: rustc_query_system::query::plumbing::get_query_impl
  17: rustc_middle::hir::map::Map::expect_item
  18: rustc_middle::hir::map::Map::visit_item_likes_in_module
  19: rustc_passes::hir_id_validator::check_crate
  20: rustc_interface::passes::analysis
  21: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  22: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  23: rustc_data_structures::stack::ensure_sufficient_stack
  24: rustc_query_system::query::plumbing::get_query_impl
  25: rustc_interface::passes::QueryContext::enter
  26: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  27: rustc_span::with_source_map
  28: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by Stupremee** [comment] 2020-11-29 12:12
Closing as duplicate of #79487, which is fixed in next nightly

**Closed by Stupremee** 2020-11-29 12:12 UTC
Labels: C-bug, I-ICE, T-compiler
