### ISSUE TITLE
SIGILLs when panicking

### ISSUE THREAD

**Issue by MageSlayer** [rust-lang/rust#48088] opened 2018-02-09 11:26 UTC
Hi

I am trying to debug some regression in compiler leading to triggering SIGILLs when raising exceptions/panicking. More precisely, SIGILLs happen at unwinding stage after drop_in_place calls in frame cleaning. Technically it's seen as a jump to ud2 instruction.

Quick bisecting using precompiled binaries resulted in finding nightly-2017-12-25-x86_64-unknown-linux-gnu as the first culprit. nightly-2017-12-24-x86_64-unknown-linux-gnu still works fine. 

Unfortunately, I cannot reproduce it in easy test-case.
I am under Linux x64, no optimization/debug build.

I'll try to bisect using git, but recompiling compiler is really slow, so results are not coming quickly.

**Comment by retep998** [comment] 2018-02-09 11:58
If you're getting a SIGILL because it executed a `ud2`, it is probably something deciding to call `intrinsics::abort()`.

**Comment by MageSlayer** [comment] 2018-02-09 12:03
Yes, I know that. 
I am trying to get the reason for that. And why it appeared in Dec25 build.

Moreover, it's not a user-code but exception frame clean-ups ("landing pads" or whatever it's called), so I have a strong suspicion that something changed/regressed in compiler.

**Comment by MageSlayer** [comment] 2018-02-09 12:12
@alexcrichton 
Do you happen to know how to determine which commits went to pre-built binaries on specific date?
It would reduce number of iterations for git bisect.

**Comment by nagisa** [comment] 2018-02-09 13:17
> And why it appeared in Dec25 build.

Sounds a lot like https://github.com/rust-lang/rust/pull/46833.

**Comment by MageSlayer** [comment] 2018-02-09 14:04
@nagisa 
Yes. It's definitely looks like those changes. And that's scary.
I have several questions (maybe you know the answers or somebody to invite for discussion):
1. Why was extern "[any calling convention]" now regarded as FFI boundary? I had quite a measurable speed-up changing hot functions into "fastcall"/"vectorcall". 
2. Maybe it's possible avoid marking them external and still have them use fastcall/vectorcall + proper unwind? Adding #[unwind] does not seem to help...
3. What about forward references for Rust functions declared as "extern" for some other crate to satisfy them? It's all Rust, no FFI, but now just mentioning "external" on them leads to unwind disable? That's definitively not good..

**Comment by nagisa** [comment] 2018-02-09 14:58
> Why is extern "[any calling convention]" now regarded as FFI boundary? I had quite a measurable speed-up changing hot functions into "fastcall"/"vectorcall".

`extern "foo"` where `foo` is not either `Rust` or `rust-call`, was never specified to not be a FFI bounary. We always informed LLVM that these "FFI boundary" functions were `nounwind` before, so the behaviour was always undefined. [See also this comment onwards](https://github.com/rust-lang/rust/issues/47616#issuecomment-359247761).

> Maybe it's possible avoid marking them external and still have them use fastcall/vectorcall + proper unwind? Adding #[unwind] does not seem to help...

`#[unwind]` not helping seems like a bug that should be reported separately. Maybe you’re unwinding past some other function that you forgot to annotate with `#[unwind]`? Can you minimise the test-case?

`#[unwind]` should definitely disable the trap, remove the `nounwind` annotation in generated code etc etc.

> What about forward references for Rust functions declared as "extern" for some other crate to satisfy them? It's all Rust, no FFI, but now just mentioning "extern" on them leads to unwind disable? That's definitively not good..

Those should work just fine, as `extern "Rust"` and `extern "rust-call"` are still not considered a "FFI boundary".

> Why compiler does not warn about using unwind function inside "now-non-unwinding" function?

Such lint would definitely be very false-positive happy, so it has no place in the compiler.

**Comment by MageSlayer** [comment] 2018-02-09 15:31
Ok, I got it.

Still #[unwind] does not work. What I did is:
forward declaration
```
#[allow(improper_ctypes)]
extern "fastcall" {
    #[unwind]
    pub fn eval(ast: &AST, interpreter: &Interpreter) -> AST;
 ...
```
and actual function definition
```
#[no_mangle]
#[unwind]
pub extern "fastcall" fn eval(ast: &AST, interpreter: &Interpreter) -> AST {
...
}
```
... for each function marked as "extern" and it still triggers UB.
I'll try to make a small example.

**Comment by diwic** [comment] 2018-02-09 18:54
Looking at [MSDN's docs for vectorcall](https://msdn.microsoft.com/en-us/library/dn375768.aspx) - which I assume is what "vectorcall" refers to - it does not mention how to handle exceptions, stack unwinding, etc. So I guess it's fair to say that exceptions/panics are not supported in this calling convention.

But if vectorcall is actually faster than rust-call, then we should create a new rust-vectorcall convention, which does support panics and uses registers/stack just as MS vectorcall does. (And then we could try switching to it by default, if the majority of calls are quicker with that.)

**Comment by retep998** [comment] 2018-02-09 19:21
At least for Windows, exceptions and stack unwinding are handled in a standardized way using SEH, and independent of the calling convention used. The only thing that gets in the way of unwinding across those function boundaries is the fact that Rust tells LLVM `nounwind` and that Rust emits code to catch an unwind if it does occur and abort. Unless you're actually doing FFI in which case the other language has to be equipped to handle unwinding using the same system.

Because the `rust-call` and `Rust` calling conventions do not have any ABI stability, we can easily change them to behave more like `vectorcall` if it was found to be beneficial in general.

**Comment by pietroalbini** [comment] 2018-02-10 10:52
Thanks for reporting this! We already knew about this problem, but [it was decided](https://github.com/rust-lang/rust/issues/47616#issuecomment-362297068) to keep sending SIGILLs when a panic occurs across `extern` functions. Closing this issue as expected behavior.

Please open another issue about `#[unwind]` though, so we can investigate it!

**Closed by pietroalbini** 2018-02-10 10:52 UTC
Labels: A-ffi
