### ISSUE TITLE
Please reconsider endorsing `dirs` and deprecating `std::env::home_dir`

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rust#71684] opened 2020-04-29 17:11 UTC
(Link for convenience: https://doc.rust-lang.org/std/env/fn.home_dir.html)

Recommending a user library in favor of the standard library is [not an action without precedent.](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-3.1)

However in this instance I think it's unwise. [The author of `dirs` has made it clear they are not interested in providing the level and variety of support expected by users of the Rust `std` library.](https://web.archive.org/web/20200430210634/https://github.com/soc/dirs-rs)

What I, and I suspect most of the Rust community, would prefer is fixing the behavior of `std::env::home_dir`, and bringing it back from deprecation. Choosing to deprecate it and recommend another crate implies that someone could be relying on the current incorrect behavior of `std::env::home_dir`. Do we have any reason to believe someone is relying on that behavior? Is there room for disagreement as to what correct behavior is? My own review of the discussion surrounding this didn't seem to ask those questions and just deprecated it seemingly without questioning that.

~~If nothing else, at this point it seems wise to remove the recommendation of the `dirs` crate, even if rust-lang wants to leave the deprecation intact.~~ EDIT: Removing the recommendation has been done.

**Comment by RalfJung** [comment] 2020-04-30 07:03
> The author of dirs has made it clear they are not interested in providing the level and variety of support expected by users of the Rust std library.

I do not see how the link here confirms that statement, it just shows the GH project index page?

**Comment by wareya** [comment] 2020-04-30 11:21
The archive doesn't show it, but the `dirs` repository currently has the `This repository has been archived by the owner. It is now read-only. ` marking on it.

**Comment by RalfJung** [comment] 2020-04-30 12:11
I see. But that doesn't say anything about "providing the level and variety of support expected by users of the Rust std library".

**Comment by Xaeroxe** [comment] 2020-04-30 21:04
@RalfJung I'm curious how marking the source repository read only could signal something other than "I'm not interested in maintaining this project anymore."

**Comment by RalfJung** [comment] 2020-04-30 21:07
That was not your claim. You made a very specific claim for the motivation for them not warning to maintain the project any more. I was asking why you think that "not interested providing the level and variety of support expected by users of the Rust std library" was the motivation.

You proved that they don't want to support this any more. You didn't prove your claim which said specifically *why* they don't want to support this any more.

**Comment by RalfJung** [comment] 2020-04-30 21:08
To be clear, I am entirely on board with the goals of this issue -- to stop recommending an unmaintained crate.

I am just disputing a particular statement on the original post, which I believed and still believe to be unfounded.

**Comment by Xaeroxe** [comment] 2020-04-30 21:11
"maintained", to me, is a subset of "the level and variety of support expected by users of the Rust `std` library."

**Comment by RalfJung** [comment] 2020-04-30 21:24
Most libraries are not maintained to the same standards as libstd. So I don't think "I don't want to maintain crate X any more" implies "I don't want to maintain crate X to the same standards as std".

But also, this is getting increasingly off-topic, so I will stop here.

**Comment by Xaeroxe** [comment] 2020-05-01 22:19
> To be clear, I am entirely on board with the goals of this issue -- to stop recommending an unmaintained crate.

Would opening a PR to remove the recommendation be appropriate at this time?

**Comment by RalfJung** [comment] 2020-05-02 00:12
I'll defer that question to @rust-lang/libs -- `dirs` is unmaintained ("archived" on GH), should we change/remove the deprecation message that recommends using it?

**Comment by BurntSushi** [comment] 2020-05-02 01:48
I think we should, at minimum, remove the recommendation for `dirs`. Probably just replacing it with text that says something like "use crates.io" would be fine. If we were compelled to provide a crate name, then probably [`home`](https://crates.io/crates/home) is the right answer. It's used by Cargo, for example.

It would be nice to un-deprecate and fix this, but this was certainly something that was considered. See:

* https://github.com/rust-lang/rust/issues/28940 for an initial description of the issue with `home_dir`.
* https://github.com/rust-lang/rust/issues/43321 is a duplicate of #28940.
* https://github.com/rust-lang/rust/issues/40320 is a tangential but related issue.
* #46799 is pretty much exactly this issue, but ~2.5 years ago. Namely, we started by trying to fix `home_dir`, but as that issue discusses, there are issues doing that because it's a breaking change. https://github.com/rust-lang/rust/pull/46799#issuecomment-361156935 summarized our decision there and a possible path forward.
* https://github.com/rust-lang/rust/pull/51656 deprecated `std::env::home_dir` and recommended the `dirs` crate as an alternative.

Personally, I'd like to see a working `home_dir` function in `std`, but it sounds like fixing the current function is probably not a good path toward it. So perhaps a new function is warranted that does the "right" thing, whatever that is. (If `home` is good enough for Cargo and rustup, then maybe it is good enough?)

**Comment by Xaeroxe** [comment] 2020-05-02 02:53
I've opened https://github.com/rust-lang/rust/pull/71784 to remove the recommendation for now. I don't intend to halt the discussion as to whether rust-lang should recommend a crate here, or if a function should be pulled into std from crates.io, but we can act on the decision we did make, which is to not recommend this crate.

**Comment by Xaeroxe** [comment] 2020-05-02 03:16
It's pretty clear the behaviour of this deprecated function is toeing the line between bug and feature. Were it a bug, the answer would be simple, fix the problem. No deprecation necessary. If alternatively it's a misguided feature, then deprecation seems like a reasonable approach.

Frequently during the discussions you linked I see concerns being raised that this is, perhaps to some, a feature, or at the very least that changing it may cause excessive breaking changes. I suppose I understand the caution, as gathering data on the usage of this API is nearly impossible, since most of its users are going to be bin users.

One approach to gathering the data necessary to answer that question might be building telemetry into rustc itself. As far as I know there's no such precedence for such telemetry in rustc though. That would probably be a risky and controversial move in and of itself. So a simpler approach honestly might be a poll/survey. Ask the community. Imprecise, but any data is better than no data? It's certainly an interesting problem. I can't help wondering how many users of Rust programs would actually experience an observable change in program behavior from this. How many of them would consider such a change fatal to their workflow?

Additionally, one might consider such breakage fine, because if the behaviour of the code using this is really that important, then the software shop probably has rigorous QA processes that would catch this kind of impact.

In the absence of a good dataset to draw from I suppose the most cautious approach is the only good one, and the most cautious approach is leaving the behaviour unchanged and deprecating the API.

**Comment by lzutao** [comment] 2020-05-02 08:24
Hi, I created @xdg-rs for taking care of maintaining dirs crate and its friends.
Currently we have @tbu- who has publishing permission on [crates.io](https://crates.io/crates/dirs).
I believe that Simon (soc) wouldn't remove him from crates.io owner.
But I agree that std should remove recommendation for specific crates.

**Comment by lzutao** [comment] 2020-05-02 09:19
Hey, a concern raised in deprecating std `home_dir` is that Python does considering
HOME var on Windows. It hasn't be like that since [python 3.8](https://docs.python.org/3/library/os.path.html#os.path.expanduser):
> Changed in version 3.8: No longer uses HOME on Windows.

**Comment by wareya** [comment] 2020-05-02 11:49
As a windows user, it bothers me a *lot* when applications check for standard configuration/environment features in nonstandard ways. The worst one I run into is applications looking for UI language grabbing it from the system locale instead of from the, uh, system UI language. Using environment variables to find the "home" folder on windows is essentially the same; someone might want to check environment variables to find the home folder on windows, but doing so is essentially wrong in 99%+ of cases, just like interpreting the system locale as UI language. Of course, checking the USERPROFILE environment variable is forgivable since it's hardly ever going to be wrong, but HOME just isn't set by default on Windows in the first place (at least not the version I run), so checking it is just *begging* to have things magically misbehave in strange environments.

Problems like this just kind of tend to happen when porting unix applications to win32 or vice versa, but, you know, windows doesn't give you all the necessary tools to work around badly-behaving applications that unix systems generally do.

Of course, I'm not trying to resurrect old issues, but I wanted to throw in an argument in favor of the current std::env::home_dir staying deprecated, since someone threw in an argument that it may be considered a featurebug.

**Comment by cedricgrothues** [comment] 2020-05-20 19:57
>  If we were compelled to provide a crate name, then probably home is the right answer.

@BurntSushi, it seems as if `home` uses `env::home_dir()` internally at least on unix (I'm pretty sure it calls the same methods on windows, too).

**Comment by BurntSushi** [comment] 2020-05-21 18:55
@cedricgrothues Hmm, doesn't look like it uses `env::home_dir()` on Windows at least: https://github.com/brson/home/blob/master/src/windows.rs

**Comment by Timmmm** [comment] 2020-06-01 16:13
I would be ok with `std::env::home_dir2()`. It's ugly but only in proportion to this situation. :-)

**Comment by Boscop** [comment] 2020-06-01 22:51
@Timmmm Or `std::env::home_directory()` so that in a future edition, `std::env::home_dir` could be removed without leaving its successor with a weird name.

**Comment by BurntSushi** [comment] 2020-06-01 23:01
@Boscop Editions can't remove APIs from std.

**Comment by Timmmm** [comment] 2020-06-02 09:13
> I'd prefer something like `std::env::home_directory()`

I think that would just lead to more confusion (given that `home_dir` can't be removed). What is the difference between `home_dir` and `home_directory`? They sound like they're the same thing - which one should I use? With `home_dir` and `home_dir2` it is much more obvious. I agree `home_dir2` is an ugly name.

**Comment by RalfJung** [comment] 2020-06-02 09:15
That confusion is something documentation can solve. There is precedent for picking a new but sensible name: [`before_exec`](https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html#method.before_exec) got deprecated and replaced by `pre_exec`.

**Comment by haug1** [comment] 2020-11-17 21:05
Would be nice to get this sorted

```
  #![allow(deprecated)] // Deprecated because of Windows compatibility (I think)
  let path = std::env::home_dir()...
  ...
```

**Comment by Coding-Badly** [comment] 2021-03-11 08:41
`SHGetKnownFolderPath` can fail.  Ironically with an `E_FAIL` error code.  Though I've never seen it fail.

Thoughts on this path forward...
* Leave `std::env::home_dir` marked as deprecated to give fair warning to everyone using it.
* At the end of the deprecation period change `pub fn home_dir() -> Option<PathBuf>` to `pub fn home_dir() -> Result<PathBuf, std::io::Error>` to reflect the fact that it can fail and give the programmer a way to act on why it failed.
* And, obviously, fix it with the interface change.

That gives everyone using `std::env::home_dir` ample time to plan for the change.  That forces everyone who has ignored the deprecation warning to deal with the change when it comes.  That gives those of us who want it to work correctly hope that it will someday work correctly.

**Comment by BurntSushi** [comment] 2021-03-11 09:05
@Coding-Badly That's a non-starter. It's a breaking change. Deprecation or not, it's a violation of our API stability guarantees.

**Comment by ChrisDenton** [comment] 2021-03-11 15:58
> Thoughts on this path forward...

I think it's worth asking what the use case for `home_dir` is meant to be. I don't think most people really care where the root directory of the user's profile is. Why would they? What they actually want is some place to put some files without having to think about platform differences.

So (imho) if `home_dir` were to be soft replaced with a single function, I'd suggest `std::env::data_dir` or similar. A better API would be to allow platforms to distinguish between cache, config, and data directories. But that's probably better exposed in a third party crate rather than the standard library. At least until there is a clear consensus on what such an API must look like.

**Comment by Coding-Badly** [comment] 2021-03-11 18:59
@BurntSushi Fixing the behaviour of `std::env::home_dir` is a breaking change.  In which case the path forward is clear and is the path we're on. `std::env::home_dir` gets deprecated then removed.

Why is this issue still open?

**Comment by Coding-Badly** [comment] 2021-03-11 21:52
Are breaking changes acceptable?

> That's a non-starter. It's a breaking change.

No.  Got it.

> Deprecation or not, it's a violation of our API stability guarantees.

That would be the reason you consider my idea to be a breaking change.  Which is nice to know but not especially important.

**Comment by Xaeroxe** [comment] 2021-03-11 21:59
I'm not sure there's much to be gained from rehashing this discussion at this point. A decision was already made in https://github.com/rust-lang/rust/pull/46799#issuecomment-361156935. In order to provide a compelling argument to reverse that decision one would have to do a pretty comprehensive analysis of rust code on `crates.io` and `github.com` and categorize the usage of this function. The rust-lang maintainers have made their stance clear. Let's set this aside until someone has usage data.

**Comment by BurntSushi** [comment] 2021-03-11 22:02
@Xaeroxe I'm on the library team and I outlined a path forward here. I think std should have a homedir function.

**Comment by Xaeroxe** [comment] 2021-03-11 22:03
Alright, my bad I guess I was reading too quickly.

**Comment by BurntSushi** [comment] 2021-03-11 22:04
Specifically, this comment: https://github.com/rust-lang/rust/issues/71684#issuecomment-622651337

**Comment by Anshrk** [comment] 2021-08-05 07:36
Does env::home_dir do the same thing as env::vars("HOME")?

**Comment by wareya** [comment] 2021-08-05 13:14
No.

**Comment by sambiak** [comment] 2021-09-22 13:54
Is there a consensus on reccomending the [home crate](https://crates.io/crates/home) ? If yes, the documentation should reflect that. In its current state the documentation is [confusing](https://stackoverflow.com/questions/64918731/how-do-i-find-the-path-to-the-home-directory-for-linux).


If there is no consensus, maybe the documentation should present a set of alternatives ?

**Comment by soc** [comment] 2021-09-23 12:00
In my experience, people asking for the home directory are usually asking the wrong question to start with. A 1:1 replacement isn't doing them any good.

**Comment by Xaeroxe** [comment] 2021-09-23 15:51
That statement is going to require a lot of explanation. Saying "you shouldn't have that need" and then not providing alternative options or justification only serves to make people feel dumb.

**Comment by ChrisDenton** [comment] 2021-09-23 15:53
> That statement is going to require a lot of explanation. Saying "you shouldn't have that need" and then not providing alternative options or justification only serves to make people feel dumb.

What is the use case for getting the "home" directory?

**Comment by Xaeroxe** [comment] 2021-09-23 16:00
Myriad, off the top of my head:

1. Storing user preferences
2. Running a program installation in environments that don't provide administrator access
3. Making a file easily accessible by putting it in "Documents" or similar

On my computer right now I counted 20 programs storing files in my home directory, or my Documents folder.

**Comment by BurntSushi** [comment] 2021-09-23 16:03
I use `$HOME` a lot: https://github.com/BurntSushi/dotfiles/search?q=%24HOME

A lot of those are shell scripts, but it's not that uncommon for shell scripts to "evolve" into programs in other languages (like Rust).

**Comment by ChrisDenton** [comment] 2021-09-23 16:08
So what we'd want is an `app_directory()` and/or `documents_directory()` function that can conform to platform conventions? Not one that assumes a "home" directory exists and that there's a folder called "Documents", etc which applications should use.

Don't get me wrong. `$HOME` is great if you on Linux or on, say, Windows and don't care about platform conventions. That's fine. But ignoring platform conventions is probably not something that Rust itself should be endorsing.

**Comment by Xaeroxe** [comment] 2021-09-23 16:37
That addresses the needs I listed, however I'm not the only one who needs this and we should wait for others to chime in.

**Comment by fmarier** [comment] 2021-09-23 17:08
> * Storing user preferences

My personal use case was to read a config file in the standard place (i.e. `~/.config/appname.conf`), but I also needed to read the legacy config file from before `~/.config/` became a standard on Linux (i.e. `.appname.conf` in my case). The first would be covered by something like `config_directory()`, but the latter probably wouldn't.

(FWIW, I ended up [using the non-portable `$HOME` envvar](https://git.launchpad.net/safe-rm/tree/src/main.rs#n201) to avoid the extra dependency.)

**Comment by Timmmm** [comment] 2021-09-23 20:20
Yes it would be nice if the final solution provides all the directories that `dirs` did but it's ridiculous to assert that there are no use cases for getting the home directory.

**Comment by Coding-Badly** [comment] 2022-05-13 04:57
Hello all.  [Like](https://github.com/rust-lang/rust/issues/71684#issuecomment-729213325) @haug1 I'd like to get this sorted.  [Like](https://github.com/rust-lang/rust/issues/71684#issuecomment-925950210) @BurntSushi I often need to know where HOME is.  Like everyone else I want to use Rust.

From rereading this thread I believe the conclusion is that `home_dir` has to be left untouched.  Is that correct?

**Comment by Coding-Badly** [comment] 2022-05-13 04:59
Is creating a new function the best choice?

**Comment by soc** [comment] 2022-05-13 19:14
>> What is the use case for getting the "home" directory?

> Myriad, off the top of my head:
> 
>     1. Storing user preferences

So `config_dir(<APP_INFO>)`, not `home_dir()`?

>     2. Running a program installation in environments that don't provide administrator access

So `config_dir(<APP_INFO>)`/`data_dir(<APP_INFO>)`/`executable_dir()`, not `home_dir()`?

>     3. Making a file easily accessible by putting it in "Documents" or similar

So `download_dir()`, not `home_dir()`?

**Comment by Coding-Badly** [comment] 2022-05-13 20:05
The counter argument is that several programs on both Linux and Windows store files under the home directory.  For example, if I want to automatically update my SSH config file, which I do, I have to know where home is.

`config_dir`, `data_dir`, etcetera being useful does not equate to `home_dir` being useless.

**Comment by ChrisDenton** [comment] 2022-05-13 20:12
Right but something isn't in the standard library just because it could be useful. That's what third party crates are for.

And in this case there's also a significant argument against having it the standard library. It may encourage Rust applications to use it as the default place for storing all files, regardless of platform conventions.

**Comment by Coding-Badly** [comment] 2022-05-13 22:26
`home_dir` has been in the standard library for years.  Plenty of time for evidence of "encourage Rust applications to use it as the default place for storing all files" to surface.  Please provide examples.

**Comment by wareya** [comment] 2022-05-14 01:08
> So config_dir(<APP_INFO>), not home_dir()?

If you're creating non-utility software, it is perfectly reasonable to need to store user preferences in locations other than the 'config' dir. This other location is often user-defined (in a separate config space, like a registry) and is furthermore often *relative to the user's home directory* (because people still believe in the illusion of the multi-user desktop PC).

> So download_dir(), not home_dir()?

No???? What in the *world* does the downloads directory have to do with documents???? Please do not pollute my downloads folders with random crud. The downloads folder is for files that originate on other machines connected via network and nothing else *ever*.

> Right but something isn't in the standard library just because it could be useful. That's what third party crates are for.
> And in this case there's also a significant argument against having it the standard library. It may encourage Rust applications to use it as the default place for storing all files, regardless of platform conventions.

Things are in the standard library because they are *primitive*, not because they are desirable. Using `String`/`str`s for filesystem access is generally bad, but the standard library does not prevent you from working with plain `&str`s etc with the Path API directly, because that would be dumb. It is useful and valuable to provide programmers with the tools they need to *do what they **intend** to do in an acceptable way* without pulling their hair out trying to integrate a dead (possibly malicious) third-party library into their application for basic functionality.

If you're worried about that creating more dumb wrong code in this case, uh, I'm pretty sure if someone is looking for the home dir they're going to try to get it, they're just going to get it wrong (by accessing the HOME variable) and have an even more wrong program than they would have written if they had a correct `home_dir`-like function. In other words, this isn't like other standard path misuses. The home directory is too easy to (attempt to) get directly, and is too primitive. You can't fix stupid programmers doing the wrong primitive thing by providing them with fewer tools, you can only fix them by teaching them better.

At this point I would like to re-point-out that `home_dir` is deprecated because it's *defined* wrong, not because it's *used* wrong, in case anyone is reading the recent discussion without the rest of the thread in their memory (it's been over a year, after all).

**Comment by soc** [comment] 2022-05-14 23:22
>> So config_dir(<APP_INFO>), not home_dir()?

> it is perfectly reasonable to need to store user preferences in locations other than the 'config' dir

My comment – before your creative citation approach – reflects that.

> No???? What in the world does the downloads directory have to do with documents????

Calm down. It was simply a mixup (that I corrected now). I'd expect that most people where able to get the gist of the comment, regardless of that oversight though.

**Comment by wareya** [comment] 2022-05-15 03:56
> My comment – before your creative citation approach – reflects that.

I do not see anything to that effect. "In my experience, people asking for the home directory are usually asking the wrong question to start with." does not reflect what I said. What I said encompasses the fact that it is perfectly normal for developers to *derive other paths from the home directory*, using it as a primitive, and that they are not wrong in doing so. In fact this is literally how `dirs-rs` derives some standard osx paths.

What exactly are you insinuating with the wording "creative citation approach"?

> Calm down. It was simply a mixup (that I corrected now). I'd expect that most people where able to get the gist of the comment, regardless of that oversight though.

Well, no, if you seem to give inappropriate directory usage advice *while in a position of prescribing directory usage*, it's perfectly normal to get a flummoxed response. What you say is all people know. People aren't psychic.

**Comment by Timmmm** [comment] 2022-05-15 13:08
There are plenty of legitimate use cases for getting the home directory on desktop platforms. I don't think we need to discuss that any more. But I suppose there are some platforms that don't really have a home directory (e.g. Android & iOS). Perhaps it should just be more platform specific, like

```
pub fn get_standard_directory(dir_type: DirType) -> Result<PathBuf> { ... }

#[cfg(unix)]
pub enum DirType {
  Home,
  Config,
  Downloads,
}

#[cfg(windows)]
pub enum DirType {
  Home,
  Downloads,
  Documents,
  AppData,
}

#[cfg(android)]
pub enum DirType {
  ExternalStorage,
  Downloads,
  Data,
}

#[cfg(ios)]
pub enum DirType {
}
```

It seems like the `dirs` crate avoids this issue by only supporting desktop platforms. `std` seems to support mobile platforms but [all it does is check `HOME`](https://doc.rust-lang.org/src/std/sys/unix/os.rs.html#578).

**Comment by soc** [comment] 2022-05-15 17:20
> What I said encompasses the fact that it is perfectly normal for developers to derive other paths from the home directory, using it as a primitive, and that they are not wrong in doing so.

Judging from the code out there, they are overwhelmingly wrong.

Most struggle to get it right on one platform, let alone the three major ones (Linux, Windows, macOS).

If people could be bothered to do things correctly, some third-party crates would not need to exist.

**Comment by wareya** [comment] 2022-05-15 17:33
> Judging from the code out there, they are overwhelmingly wrong.

OK, do you have a formal review with statistics?

**Comment by Coding-Badly** [comment] 2022-05-15 19:08
@Timmmm, your proposal would preclude even `HOME` for the android platform.  Is that the right choice?  Is there really no such thing was a home directory on the android platform?

**Comment by deltragon** [comment] 2022-05-15 19:44
@Coding-Badly Android apps have access to either app-specific storage (which would map to either `config_dir(<APP_INFO>)` or `data_dir(<APP_INFO>)`) or shared storage, which is split into `Media` and `Documents`. None of these map cleanly to the concept of a home directory afaik.
According to this, a `home_dir` function does not really make sense on android.

See https://developer.android.com/training/data-storage

**Comment by soc** [comment] 2022-05-15 20:16
> OK, do you have a formal review with statistics?

Do a global GitHub issue search for "XDG support".

This should give you a good impression of the state of support for one standard (out of three).

**Comment by yujiri8** [comment] 2022-08-14 13:48
Hey folks, the current state of this issue is quite bad. The deprecation notice currently doesn't specify which crate you should use, and if you search for "home_dir" on crates.io, the top result is a crate that just calls the deprecated function.

**Comment by cbeuw** [comment] 2022-08-14 19:38
Since this function has been deprecated for 4 years (yes, 2018 is 4 years ago), it might be fine to change its edge case broken behaviours now since most users have probably moved off it...

**Comment by Timmmm** [comment] 2022-08-14 21:20
I'd be a bit surprised if most users *have* moved off it. I still use it precisely because it's in the standard library and not going to be abandoned like `dirs` was, and because the reasons for deprecation is just incredibly minor (it gives *arguably* unexpected results on mingw and cygwin). So minor that I would be inclined to agree that it could just be fixed... except that the broken behaviour is clearly documented.

By the way it's pretty bad that the docs don't say *why* it is deprecated. The current docs make it sound much worse than it is.

**Comment by seahurt** [comment] 2022-08-15 05:29
It's really funny to retire a std function and let user choose a third-party lib.

**Comment by yujiri8** [comment] 2022-08-15 10:18
I don't think it's *always* inappropriate to do that, but in this case I think it's definitely functionality that should be in std. And if it isn't, there should *at least* be a specific crate blessed as the official solution, and it should be named in the deprecation notice, and it should be a crate that is >=1.0, and does not call the deprecated function itself.

**Comment by Timmmm** [comment] 2022-09-10 11:46
☝️ I added a PR to at least document why it is deprecated so users can make up their own minds. I definitely care less about Cygwin and Mingw results being possibly unexpected than having to add a whole third party crate just for this.

**Comment by utkarshgupta137** [comment] 2023-04-22 01:35
> Now that the [`home`](https://crates.io/crates/home) crate is maintained by the cargo & rustup teams, would it be okay to recommend it instead?

I've created a PR to do the same: https://github.com/rust-lang/rust/pull/110665

**Comment by tmccombs** [comment] 2023-04-23 17:42
I'd rather have a new function in std that does what the home crate does. Also, the home crate calls the std home_dir function on Unix.

**Comment by utkarshgupta137** [comment] 2023-04-23 17:51
Me too, but there is obviously some contention regarding that (especially around naming), so I would at least point people to a small & suitable crate in the meanwhile.

**Comment by soc** [comment] 2023-04-23 19:44
@utkarshgupta137 but what does it accomplish?

If you are fine with the incorrectness in `env::home_dir`, it would be more straightforward to un-deprecate `env::home_dir` instead of recommending a crate that literally calls `env::home_dir` itself.

**Comment by utkarshgupta137** [comment] 2023-04-23 19:47
> @utkarshgupta137 but what does it accomplish?
> 
> If you are fine with the incorrectness in `env::home_dir`, it would be more straightforward to un-deprecate `env::home_dir` instead of recommending a crate that literally calls `env::home_dir` itself.

The home crate fixes the incorrectness.

**Comment by soc** [comment] 2023-04-23 19:50
> The home crate fixes the incorrectness.

![home](https://user-images.githubusercontent.com/42493/233861990-9c7414fa-5d1a-4ba6-89c2-53edcecc2655.png)

Where?

**Comment by utkarshgupta137** [comment] 2023-04-23 19:54
> > The home crate fixes the incorrectness.
> 
> ![home](https://user-images.githubusercontent.com/42493/233861990-9c7414fa-5d1a-4ba6-89c2-53edcecc2655.png)
> 
> Where?

The 2 lines above it:
https://github.com/rust-lang/cargo/blob/master/crates/home/src/lib.rs#L68-L69

According to the documentation, the problem is that the `HOME` variable is respected on Windows, which the home crate doesn't.

**Comment by soc** [comment] 2023-04-23 20:04
> the problem is that the HOME variable is respected on Windows

The problems on Windows where far from the only reasons why the function was deprecated.

> According to the [documentation](https://doc.rust-lang.org/std/env/fn.home_dir.html#deprecation)

I guess another case of "incomplete documentation is worse than no documentation". :shrug:

**Comment by utkarshgupta137** [comment] 2023-04-23 20:10
> > the problem is that the HOME variable is respected on Windows
> 
> The problems on Windows where far from the only reasons why the function was deprecated.
> 
> > According to the [documentation](https://doc.rust-lang.org/std/env/fn.home_dir.html#deprecation)
> 
> I guess another case of "incomplete documentation is worse than no documentation". 🤷

I must've missed some previous discussion, can you elaborate? Since cargo & rustup teams now maintain the home crate, I'm sure they would want to fix it.

**Comment by wareya** [comment] 2023-04-23 20:42
>I must've missed some previous discussion, can you elaborate? Since cargo & rustup teams now maintain the home crate, I'm sure they would want to fix it.

soc deprecated `home_dir` and added a recommendation for the `dirs` crate in the documentation (what this issue thread was originally mainly about, before the recommendation was removed) in this PR: https://github.com/rust-lang/rust/pull/51656 - the two main issues at the time were: one, it's wrong to use `HOME` on windows, and two, confusing behavior on unix systems when `HOME` is blank (whatever the source). The conversations around these two main issues leading up to soc's PR are scattered across the issue tracker in several different issue threads, as well as rust forum threads (like the one soc links as the first comment on their PR).

**Comment by Timmmm** [comment] 2023-04-23 20:43
> The problems on Windows where far from the only reasons why the function was deprecated.

I wrote that updated documentation and I may have got it wrong, but I *did* look back through the discussion that was had when it was deprecated and I don't recall seeing any other reason. Can you perhaps post a link?

I think recommending the `home` crate is very reasonable. It's just a recommendation. It can be changed in future if the situation evolves.

**Comment by utkarshgupta137** [comment] 2023-04-24 01:03
> > I must've missed some previous discussion, can you elaborate? Since cargo & rustup teams now maintain the home crate, I'm sure they would want to fix it.
> 
> soc deprecated `home_dir` and added a recommendation for the `dirs` crate in the documentation (what this issue thread was originally mainly about, before the recommendation was removed) in this PR: #51656 - the two main issues at the time were: one, it's wrong to use `HOME` on windows, and two, confusing behavior on unix systems when `HOME` is blank (whatever the source). The conversations around these two main issues leading up to soc's PR are scattered across the issue tracker in several different issue threads, as well as rust forum threads (like the one soc links as the first comment on their PR).

Yikes, the empty `HOME` seems like a genuine problem. I'll raise a PR for the home crate & see what they think.

**Comment by tmccombs** [comment] 2023-04-24 04:22
Regarding the name for a new function, I wonder if a better way to handle it would be to move it to a different module. Perhaps `std::path` or `std::fs`?  Or perhaps even better create a `std::env::dirs` module which has a new, better `home` fn, as well as  `config_dir`, `data_dir`, `cache_dir`, etc. functions.

**Closed** 2024-06-07 17:58 UTC
Labels: C-enhancement, T-libs-api, A-docs, A-process

**Comment by ehuss** [comment] 2024-06-07 18:54
For more context, a replacement is being proposed in https://github.com/rust-lang/libs-team/issues/372.
