### ISSUE TITLE
Compiler plugins with a private plugin_registrar function should not compile

### ISSUE THREAD

**Issue by dcrewi** [rust-lang/rust#19368] opened 2014-11-28 03:10 UTC
```
rustc 0.13.0-dev (fac5a0767 2014-11-26 22:37:06 +0000)
binary: rustc
commit-hash: fac5a07679cac21a580badc84b755b8df0f975cf
commit-date: 2014-11-26 22:37:06 +0000
host: x86_64-unknown-linux-gnu
release: 0.13.0-dev
```

On this build, I'm seeing cargo successfully compile such a plugin without any error message. Crates that attempt to load the plugin then fail with a confusing "undefined symbol" error, which provides little assistance in locating the root of the problem.

I suggest that such a plugin should not even compile.

**Comment by steveklabnik** [comment] 2015-12-31 20:00
Can confirm that this is still an issue. To reproduce, do https://github.com/rust-lang/rust/issues/14841#issuecomment-168230133 and remove the `pub`.

That issue seems like a more general version of this one, but since it's not an exact duplicate, let's keep it open, I guess.

**Comment by Mark-Simulacrum** [comment] 2017-06-25 20:46
Closing in favor of https://github.com/rust-lang/rust/issues/14841 -- I think that tracks the underlying cause here and as such is the problem; we don't need to track this separately.

**Closed by Mark-Simulacrum** 2017-06-25 20:46 UTC
Labels: A-syntaxext
