### ISSUE TITLE
panic during rustdoc on hyper

### ISSUE THREAD

**Issue by eminence** [rust-lang/rust#34554] opened 2016-06-29 16:06 UTC
Possible dup of #34222, but that issue is about invalid code, which I don't think is the case here.

Everything builds cleanly.  Then running cargo doc:

```
d:\users\lxd\devel\rust_libs\scm_utils>cargo doc --verbose
       Fresh semver v0.1.20
       Fresh winapi-build v0.1.1
       Fresh ansi_term v0.7.4
       Fresh matches v0.1.2
       Fresh typeable v0.1.2
       Fresh unicode-normalization v0.1.2
       Fresh rustc-serialize v0.3.19
       Fresh winapi v0.2.7
       Fresh vec_map v0.6.0
       Fresh httparse v1.1.2
       Fresh utf8-ranges v0.1.3
       Fresh bitflags v0.7.0
       Fresh xml-rs v0.3.4
       Fresh kernel32-sys v0.1.4
       Fresh xmltree v0.3.2
       Fresh libc v0.2.13
       Fresh strsim v0.4.1
       Fresh yaml-rust v0.3.3
       Fresh num_cpus v0.2.13
       Fresh unicode-bidi v0.2.3
       Fresh traitobject v0.0.1
       Fresh kernel32-sys v0.2.2
       Fresh idna v0.1.0
       Fresh sma_utils v0.1.0 (ssh://lxd@gitsrvsim/usr/abaqus60/GITrepo/sma_rust.git#3975eedf)
       Fresh time v0.1.35
       Fresh thread-id v2.0.0
       Fresh glob v0.2.11
       Fresh bitflags v0.5.0
       Fresh thread_local v0.2.6
       Fresh log v0.3.6
       Fresh memchr v0.1.11
       Fresh regex-syntax v0.3.3
       Fresh url v1.1.1
       Fresh hpack v0.2.0
       Fresh mime v0.2.1
       Fresh cookie v0.2.5
       Fresh num-traits v0.1.32
       Fresh ktmw32-sys v0.1.0
       Fresh solicit v0.4.4
       Fresh language-tags v0.2.2
       Fresh num-integer v0.1.32
       Fresh aho-corasick v0.5.2
       Fresh advapi32-sys v0.1.2
       Fresh rustc_version v0.1.7
       Fresh num-iter v0.1.32
       Fresh winreg v0.3.5
       Fresh regex v0.1.71
       Fresh rand v0.3.14
       Fresh num v0.1.32
       Fresh unicode-width v0.1.3
       Fresh chrono v0.2.22
       Fresh unicase v1.4.0
       Fresh tempfile v2.1.4
       Fresh clap v2.7.0
 Documenting hyper v0.9.9
       Fresh tempdir v0.3.4
     Running `rustdoc C:\Users\lxd\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.9.9\src\lib.rs --crate-name hyper -o D:\users\lxd\devel\rust_libs\scm_utils\target\d
oc -L dependency=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps -L dependency=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps --extern language_tags=D:\user
s\lxd\devel\rust_libs\scm_utils\target\debug\deps\liblanguage_tags-abe5f88450030754.rlib --extern language_tags=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\liblan
guage_tags-abe5f88450030754.rlib --extern unicase=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --extern unicase=D:\users\lxd\devel
\rust_libs\scm_utils\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --extern time=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtime-750bfdd52feafcb7.rlib --
extern time=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtime-750bfdd52feafcb7.rlib --extern traitobject=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\dep
s\libtraitobject-516160771d9db60e.rlib --extern traitobject=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtraitobject-516160771d9db60e.rlib --extern url=D:\users
\lxd\devel\rust_libs\scm_utils\target\debug\deps\liburl-4690728b1e11fab3.rlib --extern url=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\liburl-4690728b1e11fab3.rli
b --extern log=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\liblog-bf16bb9a4912b11d.rlib --extern log=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libl
og-bf16bb9a4912b11d.rlib --extern httparse=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libhttparse-36b96d90ffbce562.rlib --extern httparse=D:\users\lxd\devel\rust
_libs\scm_utils\target\debug\deps\libhttparse-36b96d90ffbce562.rlib --extern typeable=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtypeable-ad302c7c6ce39362.rli
b --extern typeable=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtypeable-ad302c7c6ce39362.rlib --extern num_cpus=D:\users\lxd\devel\rust_libs\scm_utils\target\
debug\deps\libnum_cpus-9256729e2e3ab66d.rlib --extern num_cpus=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libnum_cpus-9256729e2e3ab66d.rlib --extern rustc_serial
ize=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\librustc_serialize-3561541d79c18212.rlib --extern rustc_serialize=D:\users\lxd\devel\rust_libs\scm_utils\target\de
bug\deps\librustc_serialize-3561541d79c18212.rlib --extern cookie=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libcookie-1f264fccb02ef6c6.rlib --extern cookie=D:\u
sers\lxd\devel\rust_libs\scm_utils\target\debug\deps\libcookie-1f264fccb02ef6c6.rlib --extern mime=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libmime-40ee41a2f2e
225b0.rlib --extern mime=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libmime-40ee41a2f2e225b0.rlib --extern solicit=D:\users\lxd\devel\rust_libs\scm_utils\target\
debug\deps\libsolicit-b1e7a1a373a16061.rlib --extern solicit=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libsolicit-b1e7a1a373a16061.rlib`
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:325
stack backtrace:
   0:         0x6f2802bc - <unknown>
   1:         0x6f27f7d3 - <unknown>
   2:         0x6f244774 - <unknown>
   3:         0x6f281375 - <unknown>
   4:         0x6f2466c5 - <unknown>
   5:         0x6f280fdc - <unknown>
   6:         0x6f294855 - <unknown>
   7:         0x6f295360 - <unknown>
   8:         0x6608e863 - <unknown>
   9:         0x6608d56d - <unknown>
  10:         0x6608adaf - <unknown>
  11:         0x66084084 - <unknown>
  12:         0x6f2c16ca - <unknown>
  13:         0x6603cbfd - <unknown>
  14:         0x6607c19b - <unknown>
  15:         0x65fa4f94 - <unknown>
  16:         0x65f864e9 - <unknown>
  17:         0x65f82209 - <unknown>
  18:         0x6f28f918 - <unknown>
  19:         0x65f82694 - <unknown>
  20:         0x6f27d709 - <unknown>
  21:         0x776f59bc - <unknown>
error: Could not document `hyper`.

Caused by:
  Process didn't exit successfully: `rustdoc C:\Users\lxd\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.9.9\src\lib.rs --crate-name hyper -o D:\users\lxd\devel\rust_
libs\scm_utils\target\doc -L dependency=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps -L dependency=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps --exter
n language_tags=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\liblanguage_tags-abe5f88450030754.rlib --extern language_tags=D:\users\lxd\devel\rust_libs\scm_utils\t
arget\debug\deps\liblanguage_tags-abe5f88450030754.rlib --extern unicase=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --extern uni
case=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libunicase-87c5f8ba3db67fd3.rlib --extern time=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtime-7
50bfdd52feafcb7.rlib --extern time=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtime-750bfdd52feafcb7.rlib --extern traitobject=D:\users\lxd\devel\rust_libs\scm
_utils\target\debug\deps\libtraitobject-516160771d9db60e.rlib --extern traitobject=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtraitobject-516160771d9db60e.rli
b --extern url=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\liburl-4690728b1e11fab3.rlib --extern url=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libu
rl-4690728b1e11fab3.rlib --extern log=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\liblog-bf16bb9a4912b11d.rlib --extern log=D:\users\lxd\devel\rust_libs\scm_utils
\target\debug\deps\liblog-bf16bb9a4912b11d.rlib --extern httparse=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libhttparse-36b96d90ffbce562.rlib --extern httparse=
D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libhttparse-36b96d90ffbce562.rlib --extern typeable=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtypeab
le-ad302c7c6ce39362.rlib --extern typeable=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libtypeable-ad302c7c6ce39362.rlib --extern num_cpus=D:\users\lxd\devel\rust
_libs\scm_utils\target\debug\deps\libnum_cpus-9256729e2e3ab66d.rlib --extern num_cpus=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libnum_cpus-9256729e2e3ab66d.rli
b --extern rustc_serialize=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\librustc_serialize-3561541d79c18212.rlib --extern rustc_serialize=D:\users\lxd\devel\rust_l
ibs\scm_utils\target\debug\deps\librustc_serialize-3561541d79c18212.rlib --extern cookie=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libcookie-1f264fccb02ef6c6.rl
ib --extern cookie=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libcookie-1f264fccb02ef6c6.rlib --extern mime=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\d
eps\libmime-40ee41a2f2e225b0.rlib --extern mime=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libmime-40ee41a2f2e225b0.rlib --extern solicit=D:\users\lxd\devel\rust
_libs\scm_utils\target\debug\deps\libsolicit-b1e7a1a373a16061.rlib --extern solicit=D:\users\lxd\devel\rust_libs\scm_utils\target\debug\deps\libsolicit-b1e7a1a373a16061.rlib`
(exit code: 101)

d:\users\lxd\devel\rust_libs\scm_utils>


```

```
rustc 1.11.0-nightly (ad7fe6521 2016-06-23)
binary: rustc
commit-hash: ad7fe6521b8a59d84102113ad660edb21de2cba6
commit-date: 2016-06-23
host: x86_64-pc-windows-gnu
release: 1.11.0-nightly
```

**Comment by eminence** [comment] 2016-06-29 18:38
Here's the stack trace on Linux:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:     0x7f0e26e7adef - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f0e26e88ddb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f0e26e88a0f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f0e26e4e67e - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:     0x7f0e26e89021 - std::panicking::begin_panic::he426e15a3766089a
   6:     0x7f0e26e506da - std::panicking::begin_panic_fmt::hdddb415186c241e7
   7:     0x7f0e26e88fbe - rust_begin_unwind
   8:     0x7f0e26ed1fef - core::panicking::panic_fmt::hf4e16cb7f0d41a25
   9:     0x7f0e26ed2ae8 - core::panicking::panic::h907815f47e914305
  10:     0x7f0e274826f3 - rustdoc::html::render::render_impl::doctraititem::h32eec0f432e5269b
  11:     0x7f0e27481186 - rustdoc::html::render::render_impl::h8405bc03794cc756
  12:     0x7f0e2747eb74 - rustdoc::html::render::render_assoc_items::h4704ada9fa7cc3e3
  13:     0x7f0e274774fa - _<rustdoc..html..render..Item<'a> as core..fmt..Display>::fmt::h9c0a28f83547182c
  14:     0x7f0e26efc73a - core::fmt::write::hdac96890aec66a9a
  15:     0x7f0e2742e722 - std::io::Write::write_fmt::h8f7bba2797a77d53
  16:     0x7f0e2746fe8f - rustdoc::html::render::Context::item::render::h4dbcafd1a53d9010
  17:     0x7f0e27394ade - rustdoc::html::render::run::h804448c4d17b6d11
  18:     0x7f0e27375185 - rustdoc::main_args::h92ed2068a7dd9783
  19:     0x7f0e27370b6a - std::panicking::try::call::ha3f28c009d90b0a9
  20:     0x7f0e26e9729b - __rust_try
  21:     0x7f0e26e9723e - __rust_maybe_catch_panic
  22:     0x7f0e27371022 - _<F as alloc..boxed..FnBox<A>>::call_box::hb90cf37bd6edcde3
  23:     0x7f0e26e86f04 - std::sys::thread::Thread::new::thread_start::h9c883b6d445ece46
  24:     0x7f0e1f0d5aa0 - start_thread
  25:     0x7f0e26ae393c - clone
  26:                0x0 - <unknown>
error: Could not document `hyper`.
```

```
rustc 1.11.0-nightly (ad7fe6521 2016-06-23)
binary: rustc
commit-hash: ad7fe6521b8a59d84102113ad660edb21de2cba6
commit-date: 2016-06-23
host: x86_64-unknown-linux-gnu
release: 1.11.0-nightly
```

**Comment by alexcrichton** [comment] 2016-06-29 20:22
cc @ollie27

**Comment by ollie27** [comment] 2016-06-29 20:29
I believe this is a dupe of #34423, so already fixed in master just waiting on nightlies...

**Comment by alexcrichton** [comment] 2016-06-29 20:37
Ah excellent, thanks!

**Closed by alexcrichton** 2016-06-29 20:37 UTC
