### ISSUE TITLE
Compiled program crashes with a SIGSEGV/SIGILL

### ISSUE THREAD

**Issue by rtkrruvinskiy** [rust-lang/rust#20508] opened 2015-01-04 05:53 UTC
Rust playpen: http://is.gd/Js3ScV

This variant triggers a SIGILL, but variations can also result in a SIGSEGV. The `match` seems to be necessary for this to occur.

**Comment by alexcrichton** [comment] 2015-01-04 05:57
This looks like a dupe of https://github.com/rust-lang/rust/issues/20419, but thanks!

**Closed by alexcrichton** 2015-01-04 05:57 UTC
