### ISSUE TITLE
`mips64` crashes or hangs on 128 bit division

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#116440] opened 2023-10-05 03:23 UTC
This target either crashes or hangs with different arguments to a 128 bit division
```rust
#[inline(never)]
fn test(x: u128, y: u128) -> u128 {
    x.wrapping_div(y)
}

fn main() {
    dbg!(test(123 << 64, (32 << 64) | 65));
    //dbg!(test(1 << 96,  1 << 64));
}
```
this happens with `cross run --target mips64-unknown-linux-gnuabi64 -Z build-std=core,alloc,proc_macro,std`, but I don't know how to get the version that `cross` is using, also https://github.com/rust-lang/rust/issues/115218 .

**Comment by saethlin** [comment] 2023-10-05 04:23
Is this a duplicate of https://github.com/rust-lang/rust/issues/116177?

**Comment by AaronKutch** [comment] 2023-10-05 04:26
yes shifts are used internally, but when I saw that issue I assumed it only applied to the 32 bit version, if 64 bit MIPS is also affected it should be noted

**Comment by saethlin** [comment] 2023-10-05 13:01
I ran the reproducer for https://github.com/rust-lang/rust/issues/116177 and as far as I can tell it succeeds on `mips64-unknown-linux-gnuabi64`. So I think this is a separate codegen bug?

**Comment by AaronKutch** [comment] 2023-10-05 22:06
maybe the reproducer needs to have its widths doubled to a 128 bit shift, a 64 bit shift would need a single instruction on mips64

**Comment by saethlin** [comment] 2023-10-06 13:51
I adjusted the reproducer for the other issue a bit into this, which does not pass the assert with your `cross`  invocation:
```rust
use std::hint::black_box;

const SHIFTVALUE: i128 = u64::MAX as i128;

fn main() {
    fn shiftleft(a: i128, b: i128) -> i128 {
        a << b
    }

    assert_eq!(
        shiftleft(black_box(SHIFTVALUE), black_box(2)),
        SHIFTVALUE << 2
    );
}
```
So I now think this is a duplicate of https://github.com/rust-lang/rust/issues/116177. Do you agree?

**Comment by AaronKutch** [comment] 2023-10-07 00:54
yes, this should be closed then and the 64 bit version mentioned in the other thread?

**Closed** 2023-10-07 01:15 UTC
Labels: A-LLVM, O-MIPS, T-compiler, I-unsound, C-bug, I-prioritize
