### ISSUE TITLE
cargo install/build failing with latest nightly

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#40631] opened 2017-03-18 10:50 UTC
On Windows, trying to do a cargo install:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:323
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: git_openssl_set_locking
```

Seems to be okay with nightly-2017-03-03 but recent nightly seems to have issues.

**Comment by SirDoctors** [comment] 2017-03-18 11:27
Seems to be completly broken, for example our travis builds for nightly crash on [cargo --version](https://travis-ci.org/mgattozzi/alchemist/jobs/212423130#L241).

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: cargo::version
             at /checkout/src/libcore/macros.rs:21
             at /checkout/cargo/src/cargo/lib.rs:263
   1: cargo::execute
             at /checkout/cargo/src/bin/cargo.rs:156
   2: cargo::call_main_without_stdin
             at /checkout/cargo/src/cargo/lib.rs:128
   3: cargo::main
             at /checkout/cargo/src/bin/cargo.rs:91
             at /checkout/cargo/src/bin/cargo.rs:84
5.34s$ ./ci/install_job_specific_deps.sh
cargo-update not found in cache, installing...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: cargo::version
             at /checkout/src/libcore/macros.rs:21
             at /checkout/cargo/src/cargo/lib.rs:263
   1: cargo::ops::registry::http_handle
             at /checkout/cargo/src/cargo/ops/registry.rs:227
   2: <cargo::sources::registry::remote::RemoteRegistry<'cfg> as cargo::sources::registry::RegistryData>::update_index
             at /checkout/cargo/src/cargo/sources/registry/remote.rs:63
   3: cargo::sources::registry::RegistrySource::do_update
             at /checkout/cargo/src/cargo/sources/registry/mod.rs:309
   4: <cargo::sources::registry::RegistrySource<'cfg> as cargo::core::source::Source>::update
             at /checkout/cargo/src/cargo/sources/registry/mod.rs:353
   5: cargo::ops::cargo_install::install
             at /checkout/cargo/src/cargo/core/source.rs:64
             at /checkout/cargo/src/cargo/ops/cargo_install.rs:273
             at /checkout/cargo/src/cargo/ops/cargo_install.rs:80
   6: cargo::try_execute_builtin_command
             at /checkout/cargo/src/bin/install.rs:148
             at /checkout/cargo/src/cargo/lib.rs:128
             at /checkout/cargo/src/bin/cargo.rs:259
   7: cargo::execute
             at /checkout/cargo/src/bin/cargo.rs:223
   8: cargo::call_main_without_stdin
             at /checkout/cargo/src/cargo/lib.rs:128
   9: cargo::main
             at /checkout/cargo/src/bin/cargo.rs:91
             at /checkout/cargo/src/bin/cargo.rs:84
```

**Comment by devunt** [comment] 2017-03-18 13:33
Same error occured in nightly on Windows.
Occured when running `cargo +nightly install`

Detailed traceback:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:323
stack backtrace:
   0:     0x7ff752fbf995 - <unknown>
   1:     0x7ff752fcd9a7 - <unknown>
   2:     0x7ff752fcd289 - <unknown>
   3:     0x7ff752fcdf01 - <unknown>
   4:     0x7ff752fcdd68 - <unknown>
   5:     0x7ff752fcdcc1 - <unknown>
   6:     0x7ff752fcdc39 - <unknown>
   7:     0x7ff752fd7e47 - <unknown>
   8:     0x7ff752fd7d8c - <unknown>
   9:     0x7ff752e511a0 - <unknown>
  10:     0x7ff752dc8fbd - <unknown>
  11:     0x7ff752e01c2e - <unknown>
  12:     0x7ff752e05ad8 - <unknown>
  13:     0x7ff752cdfc01 - <unknown>
  14:     0x7ff752cac23d - <unknown>
  15:     0x7ff752d6f73e - <unknown>
  16:     0x7ff752d6999b - <unknown>
  17:     0x7ff752d68e44 - <unknown>
  18:     0x7ff752da2e68 - <unknown>
  19:     0x7ff752d21269 - <unknown>
  20:     0x7ff752d3340e - <unknown>
  21:     0x7ff752b92ec3 - <unknown>
  22:     0x7ff752b7d24b - <unknown>
  23:     0x7ff752b732ab - <unknown>
  24:     0x7ff752b7ba80 - <unknown>
  25:     0x7ff752fcf2b1 - <unknown>
  26:     0x7ff752fce4fa - <unknown>
  27:     0x7ff7530d0378 - git_openssl_set_locking
  28:     0x7ff9e4d28363 - BaseThreadInitThunk
```

**Comment by devunt** [comment] 2017-03-18 13:36
Looks like duplication of #40607.

**Comment by 46bit** [comment] 2017-03-18 15:19
This seems not to be a Windows issue - I'm seeing this on Arch Linux as well.

**Comment by devunt** [comment] 2017-03-18 15:28
Using `nightly-2017-03-16` seems to be solving the problem. I guess only `nightly-2017-03-17` is broken.

```
$ cargo +nightly --version
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ cargo +nightly-2017-03-16 --version
cargo 0.18.0-nightly (4a3c0a63b 2017-03-12)
```

**Comment by devunt** [comment] 2017-03-18 15:31
Found a issue in cargo repo here: rust-lang/cargo#3844.
It indicates the issue was fixed: https://github.com/rust-lang/cargo/issues/3844#issuecomment-287514022

**Comment by alexcrichton** [comment] 2017-03-18 16:20
Duplicate of https://github.com/rust-lang/cargo/issues/3844, but thanks for the report!

**Closed by alexcrichton** 2017-03-18 16:20 UTC
