### ISSUE TITLE
Diagnostic when using moved value in loop{} could be clearer

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#31874] opened 2016-02-24 23:44 UTC
Consider this error message:

```rust
struct Qqq;
fn consume(_:Qqq){}
fn main() {
    let a = Qqq;
    consume(a);
    consume(a);
}
```

<pre>
&lt;anon>:6:13: 6:14 error: use of moved value: `a` [E0382]
&lt;anon>:6     consume(a);
                     ^
<b>&lt;anon>:5:13: 5:14</b> note: `a` moved <b>here</b> because it has type `Qqq`, which is non-copyable
<b>&lt;anon>:5     consume(a);</b>
</pre>

It look more or less clear. But if we move and try to use on the same line:

```rust
struct Qqq;
fn consume(_:Qqq){}
fn main() {
    let a = Qqq;
    loop {
        consume(a);
    }
}
```

the diagnostic looks less clear:

<pre>
&lt;anon>:6:17: 6:18 error: use of moved value: `a` [E0382]
&lt;anon>:6         consume(a);
                         ^
&lt;anon>:6:17: 6:18 help: see the detailed explanation for E0382
note: `a` was previously moved <b>here</b> <i>(where?)</i> because it has type `Qqq`, which is non-copyable
</pre>

Note the absence of filename and line number.

Maybe it should point to the same line `<anon>:6` or there should dedicated message mentioning the loop...

**Comment by jonas-schievink** [comment] 2016-04-03 21:53
How about:
```
<anon>:6:17: 6:18 note: `a` was possibly moved here earlier because this expression may be evaluated multiple times
<anon>:6:17: 6:18 note: `a` was moved because it has type `Qqq`, which is non-copyable
```

Special-casing loops seems hard to do, but this might be enough to clarify what's going on.

**Comment by birkenfeld** [comment] 2016-05-02 12:08
Duplicate of #10876.

**Comment by estebank** [comment] 2016-06-18 19:37
This was fixed in 5b150cf0.

**Comment by arielb1** [comment] 2016-06-18 21:07
Fixed? The error message is the same modulo formatting.

**Comment by arielb1** [comment] 2016-06-18 21:10
Closing the moveck issue.

**Closed by arielb1** 2016-06-18 21:10 UTC
Labels: A-diagnostics
