### ISSUE TITLE
Impl search fails in case of generalized trait inheritance

### ISSUE THREAD

**Issue by rntz** [rust-lang/rust#10950] opened 2013-12-13 08:25 UTC
The following program fails to compile:

``` rust
trait Foo { fn foo(&self, x: &Self); }
trait Bar<A: Foo> { fn bar(&self) -> A; }

struct Wrap<T>(T);

impl<A, B: Bar<A>> Wrap<B> {
    fn test(&self, x: &A) {
        (*self).bar().foo(x);
    }
}

fn main() {}
```

With the following error:

```
implsearch.rs:8:8: 8:22 error: failed to find an implementation of trait Foo for A
implsearch.rs:8         (*self).bar().foo(x);
                        ^~~~~~~~~~~~~~
```

Given that `B: Bar<A>`, we know `A: Foo` because of the definition of the trait Bar. This can be seen as a generalized case of trait inheritance (trait B inheriting from A lets us know that if `X:B`, then `X:A`, because `X:B` requires `X:A`; similarly, `B:Bar<A>` requires `A:Foo`, so we know `A:Foo`). Indeed, in Haskell there is no distinction between the two forms of inheritance:

``` haskell
{-# LANGUAGE MultiParamTypeClasses #-}
class Foo b where foo :: b -> b -> ()
class Foo b => Bar a b where bar :: a -> b

test :: Bar a b => a -> b -> ()
test x y = foo (bar x) y
```

The order of arguments to Bar could be switched and the program above would still be valid.

**Comment by steveklabnik** [comment] 2015-01-23 02:17
Triage: same error, but with extra message:

```
hello.rs:11:29: 11:34 error: type `Wrap<B>` does not implement any method in scope named `bar`
hello.rs:11                     (*self).bar().foo(x);
                                        ^~~~~
hello.rs:11:34: 11:34 help: methods from traits can only be called if the trait is implemented and in scope; the following trait defines a method `bar`, perhaps you need to implement it:
hello.rs:11:34: 11:34 help: candidate #1: `Bar`
hello.rs:11:41: 11:41 help: methods from traits can only be called if the trait is implemented and in scope; the following trait defines a method `foo`, perhaps you need to implement it:
hello.rs:11:41: 11:41 help: candidate #1: `Foo`

```

Also, you need the old impl check here:

```
#![feature(old_impl_check)]

trait Foo { fn foo(&self, x: &Self); }
trait Bar<A: Foo> { fn bar(&self) -> A; }

struct Wrap<T>(T);

#[old_impl_check]
impl<A, B: Bar<A>> Wrap<B> {
        fn test(&self, x: &A) {
                    (*self).bar().foo(x);
                        }
}

fn main() {}

```

**Comment by apasel422** [comment] 2015-07-20 16:45
Even without the old impl check, this example no longer makes sense, because it uses the old unary tuple dereferencing syntax. Today, the compiler is correct that type `Wrap<B>` does not implement any method in scope named `bar`, because the type of `(*self)` is `Wrap<B>`. That line should now read `self.0.bar().foo(x)`. Updating the trait to use an associated type:

```rust
trait Foo {
    fn foo(&self, x: &Self);
}

trait Bar {
    type A: Foo;
    fn bar(&self) -> Self::A;
}

struct Wrap<T>(T);

impl<B: Bar> Wrap<B> {
    fn test(&self, x: &B::A) {
        self.0.bar().foo(x);
    }
}

fn main() {}
```

compiles successfully. I think this issue can be closed.

**Comment by talchas** [comment] 2015-08-31 05:44
Well this still fails, and seems like morally still at least somewhat similar.

```rust
trait Foo { fn foo(&self, x: &Self); }
trait Bar<A: Foo> { fn bar(&self) -> A; }
struct Wrap<T>(T);

fn test<A, B: Bar<A>>(wrap: Wrap<B>, x: &A) {
    wrap.0.bar().foo(x);
}

fn main() {}
```

**Comment by arielb1** [comment] 2015-09-28 21:01
This is intentional - non-supertrait bounds are not elaborated.

**Comment by nikomatsakis** [comment] 2017-03-23 16:34
Closing as a duplicate of https://github.com/rust-lang/rust/issues/20671, which has a better explanation.

**Closed by nikomatsakis** 2017-03-23 16:34 UTC
Labels: A-traits, A-typesystem, T-lang
