### ISSUE TITLE
[1.30 beta] Macros recursion limit detection changed

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54464] opened 2018-09-22 12:43 UTC
In the 1.30 beta the counter of macro recursions is increased by one compared to the 1.29 stable release. This causes build failures for crates with a macro with exactly 64 recursions.

* [polish_notation](https://crates.io/crates/polish_notation) `0.1.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/polish_notation-0.1.0/log.txt)) cc @firba1

**Comment by petrochenkov** [comment] 2018-09-22 12:52
Oh god.

This most likely happens due to `#[test]` being (correctly) counted as a macro expansion (https://github.com/rust-lang/rust/pull/53410).

**Comment by petrochenkov** [comment] 2018-09-22 12:56
This turns out to be a known regression https://github.com/rust-lang/rust/pull/53410#issuecomment-417416734, so I assume wontfix.

**Comment by nikomatsakis** [comment] 2018-09-27 14:47
I'd probably be ok with calling this a WONTFIX for now, though I'd like to think about possible ways to "future proof" things like the recursion depth better. It's worth pointing out that this **particular** regression won't affect **consumers** of the crate, right? Only its original author?

**Comment by pnkfelix** [comment] 2018-09-27 14:50
discussed at T-compiler meeting. Team is generally leaning towards closing as WONTFIX.

We did discuss various work-arounds (e.g. increasing the limit by +1 or x2... and generalizations thereof, like applying that transform also to user-provided recursion limits).

But in general no one seemed too eager to actually deploy any such "fix", and its not clear whether a better solution is available.

So, if this is still open next week in the same state with no objections, we'll close as WONTFIX.

**Comment by pnkfelix** [comment] 2018-09-27 14:51
(leaving priority unassigned since the priority is somewhat fuzzy, given our leaning towards WONTFIX)

**Comment by petrochenkov** [comment] 2018-09-28 10:43
Please no, this cure would be much worse than the disease.
Recursion limit is hit in `polish_notation 0.1.0` in a test that's specifically testing recursion limit, it didn't happen accidentally.

**Comment by pnkfelix** [comment] 2018-10-04 15:00
closing as wontfix.

**Closed by pnkfelix** 2018-10-04 15:00 UTC
Labels: C-bug, T-compiler, regression-from-stable-to-beta
