### ISSUE TITLE
Error while following Rust getting started.

### ISSUE THREAD

**Issue by Konglomneshued** [rust-lang/rust#107496] opened 2023-01-31 00:54 UTC
### Location

https://www.rust-lang.org/learn/get-started

### Summary

Following the getting started.

1. `cargo new hello-rust`
2. Open hello-rust in IDE (I use Webstorm)
3. `cargo run` in the terminal (probably unnecessary step)
4. Add `ferris-says = "0.3.1"` dependency
5. `cargo build`
6. Paste code (to get exact copy)

```
use ferris_says::say; // from the previous step
use std::io::{stdout, BufWriter};

fn main() {
   let stdout = stdout();
   let message = String::from("Hello fellow Rustaceans!");
   let width = message.chars().count();

   let mut writer = BufWriter::new(stdout.lock());
   say(message.as_bytes(), width, &mut writer).unwrap();
}
    
```

![image](https://user-images.githubusercontent.com/94726665/215630717-f9582f22-0f4d-414a-91d0-6a802a5468fe.png)

**Comment by ehuss** [comment] 2023-01-31 01:32
Thanks for the report!

The example should work if the `Cargo.toml` file has `ferris-says = "0.2"`, which the getting started page should instruct adding.  A new (SemVer breaking) release of `ferris-says` 0.3 was released, but you should not use that version for the example code to run as-is. 

I'm going to close as a duplicate of https://github.com/rust-lang/www.rust-lang.org/issues/1750, which is tracking updating to the newer version.

**Closed by ehuss** 2023-01-31 01:32 UTC
Labels: A-docs
