### ISSUE TITLE
Cannot move out of boxed value during deconstruction

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#34859] opened 2016-07-16 19:49 UTC
On stable, the following code does not compile:

```rust
enum X {
    A(String, Box<X>),
}

fn foo(x: Box<X>) {
    let X::A(a, b) = *x;
}
```

The compiler says that extracting `b` is a "use of moved value: `x`", and that `x` was moved when extracting `a`. The issue also occurs if using `match`, or when using the `box_patterns` feature. However, this clearly should be legal to do.

The following code also breaks in a similar way, but with a different error message ("use of collaterally moved value: `(x:X::A).1`"; which is not even mentioned by `--explain E0382`):
```rust
enum X {
    A(String, Box<X>),
    C,
}

fn foo(x: Box<X>) {
    if let X::A(a, b) = *x {
    }
}
```

It was pointed out on IRC that this can be worked around by writing `{*x}` instead of `*x`, but that's not particularly satisfactory. Someone then said that this was likely a bug with the deref-move special case for `Box`, where it doesn't handle partial moves correctly.

**Comment by jonhoo** [comment] 2016-07-16 19:54
Should also mention that the code works correctly is `s/String/i32/`, presumably because `i32` is `Copy`, and so only `b` is really moved.

**Comment by apasel422** [comment] 2016-07-18 00:38
Thanks for the report! Closing as duplicate of #30564 (and a few other closed issues, e.g. #33550).

**Closed by apasel422** 2016-07-18 00:38 UTC
