### ISSUE TITLE
Bad `use` suggestion for `RawFloat`

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#56385] opened 2018-11-30 19:12 UTC
```rust
fn main() {
 let _ = f32::INFINITY;
}
```

will error with

```
  |
3 |  let _ = f32::INFINITY;
  |          ^^^^^^^^^^^^^ associated item not found in `f32`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
  |
2 | use core::num::dec2flt::rawfp::RawFloat;
```

The suggestion is both unhelpful and wrong at the same time. Using `use core::num::dec2flt::rawfp::RawFloat;` would cause a name-error. What we really want here is simply

```rust
use std::f32;
```

**Comment by estebank** [comment] 2019-04-12 20:47
Closing as duplicate of #26760.

**Closed by estebank** 2019-04-12 20:47 UTC
Labels: A-diagnostics, WG-compiler-errors
