### ISSUE TITLE
Proc macro doesn't take target architecture into account

### ISSUE THREAD

**Issue by Nordgaren** [rust-lang/rust#120154] opened 2024-01-20 02:15 UTC
Proc macro does not take target arch into consideration when running

[I tried this code (small project made to recreate issue):](https://github.com/Nordgaren/rust-target-demo)
command: `cargo test --package proc-macro --lib tests::import_test  --target=i686-pc-windows-msvc `
the gist:
```rust
pub fn proc_macro_impl(args: TokenStream) -> TokenStream {
    #[cfg(target_arch = "x86")]
    quote!{
        const TEST_STRING: &str = "Hello, fom x86!";
    }

    #[cfg(target_arch = "x86_64")]
    quote!{
        const TEST_STRING: &str = "Hello, fom x86_64!";
    }
}
```

**I expected to see this happen**: I was expecting the code path to be different, because that target arch is changed.

**Instead, this happened**: Everything is ran as `x86_64`
### Meta

`rustc --version --verbose`:
```
rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: x86_64-pc-windows-msvc
release: 1.74.1
LLVM version: 17.0.4
```

No backtrace. Code exits just fine.
<details><summary>Backtrace</summary> 
<p>

```

```

</p>
</details>

This also causes somethings to fail, like library calls for C libraries that should be x86. I have a proxy macro crate, and the `LoadLibraryA` call that I use to let the Windows loader get the DLL we are proxying, calls from 64 bit windows, and fails to load the library, I can get around this (by manually opening the file), but, this might be a wider issue, as anyone using a proc macro that generates arch specific code (or maybe any other type of macro. I haven't tested, yet.), may need to run it ON the target arch they are compiling for, for it to work properly. 

I also understand that this may also break some things, because you have to run the macro code on that arch for this fix, most likely. Is it possible to specify a flag to compile and run macros on the target architecture? 

Thank you.
Nordgaren

**Comment by Nilstrieb** [comment] 2024-01-20 09:00
Proc macros are run on the host, do their cfg must be that of the host.

**Comment by Nilstrieb** [comment] 2024-01-20 09:01
You might be able to access the cargo environment variables at runtime in the proc macro.

**Comment by Nordgaren** [comment] 2024-01-20 14:11
> You might be able to access the cargo environment variables at runtime in the proc macro.

 `CARGO_CFG_TARGET_ARCH` is telling me it's not defined at compile time, and it doesn't show up from `std:env:var`.
 
 Is there another environment variable?

The problem is that for dll proxies, I need it to run in 32 bit mode. I need to know if the user is proxying a 32 bit dll. The windows loader will resolve differently. The symbols are different and I do not have ANY of that information because that is 32 bit specific functionality, and it requires that I have the headers to be able to calculate the name mangling (32 bit windows has name mangling for symbols)

32 and 64 bit are different architectures, at the end of the day, and there are things I cannot account for on 64 bit arch.
 
 Seems like a huge oversight to not be able to detect target architecture at all in a proc macro, because there are arch specific things that may need to be accounted for. There is no way for me to just define a second export with the right name mangling, because there is no way for me to know the function arguments just by reading the PE header.

**Comment by Nilstrieb** [comment] 2024-01-20 14:17
I see. What you're supposed to do here is to put the `cfg` *inside* the `quote`, this way it will be applied to the actual target in the code. This is not always that simple, but it's what you're supposed to do
```rust
    quote!{
        #[cfg(target_arch = "x86")]
        const TEST_STRING: &str = "Hello, fom 

        #[cfg(target_arch = "x86_64")]
        const TEST_STRING: &str = "Hello, fom x86_64!";
    }
```

**Comment by Nordgaren** [comment] 2024-01-20 14:21
> I see. What you're supposed to do here is to put the `cfg` _inside_ the `quote`, this way it will be applied to the actual target in the code. This is not always that simple, but it's what you're supposed to do
> 
> ```rust
>     quote!{
>         #[cfg(target_arch = "x86")]
>         const TEST_STRING: &str = "Hello, fom x86!";
> 
>         #[cfg(target_arch = "x86_64")]
>         const TEST_STRING: &str = "Hello, fom x86_64!";
>     }
> ```

I wish you would have read what I said.

> The symbols are different and I do not have ANY of that information because that is 32 bit specific functionality, and it requires that I have the headers to be able to calculate the name mangling (32 bit windows has name mangling for symbols)

**Comment by Nordgaren** [comment] 2024-01-20 14:21
Not to mention that in 32 bit windows, I will have a different path to take. So if someone tries to use this macro and compile on a 32 bit windows machine, it will break. Because they don't have a syswow64 folder. They just have system32. How would I detect that?

**Comment by Nordgaren** [comment] 2024-01-20 14:27
CARGO_BUILD_TARGET is also not present.

**Comment by Nordgaren** [comment] 2024-01-20 14:32
I can get the right symbol information if I read the right version of the dll, but the only way to do that is to know what arch I am compiling for.

The best way to do that is to just let the windows loader resolve it, because that is the functionality that is being used, here. The functionality is part of the windows loader. dll proxies are about the search path the windows loader takes to get there, and re-exporting the symbols so that they match the original DLLs, so that they can be forwarded to the right function.

**Comment by Nordgaren** [comment] 2024-01-20 14:37
And the reason to use the target archs loader, is because paths are not only arch dependent, but system dependent.

the paths to get to a dll on 64 bit windows and NATIVE 32 bit windows are different. So if I just check for architecture, I also have to somehow check if I am natively on windows, or not, because I need to change the path.

Windows loader won't have this issue.

The only other way to do this would be to write a program that write the rust files for me, and that's basically what we do in C++, and that is the kind thing I moved to Rust for. Not to have to be bothered with terrible toolchains.

**Comment by Nilstrieb** [comment] 2024-01-20 14:43
There are probably nicer ways to do this, but I can't think of them off the top of my head.
I recommend visiting https://users.rust-lang.org and asking people there how to do this, you will probably get nicer answers. If the result from there is that there is no way to solve your problem nicely today, I recommend going to https://internals.rust-lang.org where you can discuss possible solutions instead.

This issue tracker is not really for language feature requests like that or helping with Rust code, so I'm going to close this issue.

**Closed by Nilstrieb** 2024-01-20 14:43 UTC
Labels: A-proc-macros, C-discussion

**Comment by Nordgaren** [comment] 2024-01-20 14:47
Alright, well, it's upsetting that you respond this way when I expressed that I don't think you understand the issue.

I already asked the community about this. They told me it could be a bug. It's at the very least an oversight, as there is no way for a proc macro to account for arch specific things, including paths that have to be resolved by architecture. That sounds like a bug.

I can't even get this data from the environment variables, as you suggested.

**Comment by Nilstrieb** [comment] 2024-01-20 15:08
I'm sorry that I upset you, I did indeed not read your comment correctly.

The fact that a `cfg` in a proc macro applies to the host is definitely not a bug, that's intended and good, and it would be very bad if it was changed, as you may need it, especially in dependencies of proc macros.

Another thing to consider here is that it's desirable to have proc macros be more pure and target-independent, which could help with caching in the future (you can find discussions about wasm-based proc macros about this).

From what I've gathered, it seems like the right tool for the job here isn't a proc macro but a build script instead. Build scripts can read target information from cargos environment variables and act on them. They're intended for these sort of "build specific code generation" use cases, while proc macros are generally mode intended for "pure code transformations".

If you can't use build scripts for some reason, I recommend going to https://internals.rust-lang.org to present your use case and possible solutions you can think of, in the hope of designing something that can work for you.

**Comment by Nordgaren** [comment] 2024-01-20 16:40
> I'm sorry that I upset you, I did indeed not read your comment correctly.
> 
> The fact that a `cfg` in a proc macro applies to the host is definitely not a bug, that's intended and good, and it would be very bad if it was changed, as you may need it, especially in dependencies of proc macros.
> 
> Another thing to consider here is that it's desirable to have proc macros be more pure and target-independent, which could help with caching in the future (you can find discussions about wasm-based proc macros about this).
> 
> From what I've gathered, it seems like the right tool for the job here isn't a proc macro but a build script instead. Build scripts can read target information from cargos environment variables and act on them. They're intended for these sort of "build specific code generation" use cases, while proc macros are generally mode intended for "pure code transformations".
> 
> If you can't use build scripts for some reason, I recommend going to https://internals.rust-lang.org to present your use case and possible solutions you can think of, in the hope of designing something that can work for you.

Yea. I will try to make a build script, I guess. It's just not as packageable as a proc macro, as I am not sure how else to include the generated code in the final output.

I guess maybe I could do some linker magic. I think the winresource or some other crate might do something where it adds things to the linker somewhere. Like write assembly (in their case they compile a c header) and link it kinda think.

I really appreciate you re-reading my question to understand what I was trying to say. Thank you! 

Have a good weekend!

**Comment by glandium** [comment] 2024-01-26 01:47
This was discussed in the past: https://internals.rust-lang.org/t/procedure-macros-should-have-access-to-some-basic-compilation-information/17517
This is definitely a use-case rust should cater for, albeit this would be a cargo thing rather than rustc. And I got here because I was looking to do something similar just now.

**Comment by Nordgaren** [comment] 2024-01-28 19:54
> This was discussed in the past: https://internals.rust-lang.org/t/procedure-macros-should-have-access-to-some-basic-compilation-information/17517 This is definitely a use-case rust should cater for, albeit this would be a cargo thing rather than rustc. And I got here because I was looking to do something similar just now.

Yea, I don't understand why we can't just run the entire compilation process on the target architecture with a flag (or specified after the flag). I don't know the compiler code base, so, it could be an issue with running the compiler as a 32 bit executable, as I was also unsuccessful in finding a 32 bit version of the compiler. 

If this is possible, should I submit a language feature request to https://internals.rust-lang.org/ still? I still just haven't sat down to check if these suggested solutions even work.
