### ISSUE TITLE
Regression in quick-error-1.1.0, Rust 1.18

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40961] opened 2017-03-31 17:34 UTC
https://github.com/tailhook/quick-error

```
101 brian@ip-10-145-43-250:~/dev/quick-error⟫ git log -1
commit 5e59eb822cb01a5c33323c3dc919793a178bdf8e
Author: Paul Colomiets <paul@colomiets.name>
Date:   Sat Jun 4 13:20:37 2016 +0300

    Version bumped to v1.1.0

```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +nightly -Vv
rustc 1.18.0-nightly (5c94997b6 2017-03-30)
binary: rustc
commit-hash: 5c94997b6b1cca3e65ecfc5ba40c033d6838019b
commit-date: 2017-03-30
host: x86_64-unknown-linux-gnu
release: 1.18.0-nightly
LLVM version: 3.9

```

```
brian@ip-10-145-43-250:~/dev/quick-error⟫ cargo +nightly test
   Compiling quick-error v1.1.0 (file:///mnt2/dev/quick-error)
    Finished dev [unoptimized + debuginfo] target(s) in 2.12 secs
     Running target/debug/deps/quick_error-f0698c10c56700da

running 16 tests
test test::bare_item_trait ... ok
test test::bare_item_direct ... ok
test test::parse_float_error ... ok
test test::parse_int_error ... ok
test test::path_context ... FAILED
test test::debug_context ... ok
test test::struct_wrapper_err ... ok
test test::struct_wrapper_excess_comma ... ok
test test::struct_wrapper_struct_from ... ok
test test::tuple_wrapper_discard ... ok
test test::tuple_wrapper_custom_from ... ok
test test::tuple_wrapper_singleton ... ok
test test::tuple_wrapper_from ... ok
test test::tuple_wrapper_err ... ok
test test::tuple_wrapper_trait_str ... ok
test test::tuple_wrapper_trait_two_fields ... ok

failures:

---- test::path_context stdout ----
        thread 'test::path_context' panicked at 'assertion failed: `(left == right)` (left: `"Path error at \"/etc\": invalid utf-8 sequence of 1 bytes from index 1"`, right: `"Path error at \"/etc\": invalid utf-8: invalid byte near index 1"`)', src/lib.rs:1122
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test::path_context

test result: FAILED. 15 passed; 1 failed; 0 ignored; 0 measured

error: test failed

```

cc @tailhook

**Comment by tailhook** [comment] 2017-04-01 08:26
Fixed in master. This was just too strict error handling. Thanks!

**Comment by alexcrichton** [comment] 2017-04-01 14:33
@tailhook do you know if this was just a local problem, or was it caused by a change in rust-lang/rust?

**Comment by tailhook** [comment] 2017-04-01 18:44
@alexcrichton, the error message (i.e. `Display`) of `Utf8Error` was changed. I don't think this counts as a backwards incompatibility.

**Comment by alexcrichton** [comment] 2017-04-01 22:21
Ah ok, sounds good to me!

**Closed by alexcrichton** 2017-04-01 22:21 UTC
Labels: regression-from-stable-to-nightly
