### ISSUE TITLE
Illegal instruction generation for unreachable code

### ISSUE THREAD

**Issue by Yuhanun** [rust-lang/rust#69682] opened 2020-03-03 22:16 UTC
Illegal instructions get generated when unreachable code is found, but it can be reached if a loop / whatever gets optimized out. Only happens in release.

```rust
// Run in release

fn nothin() -> u8 {
    loop{ };
    5
}

fn main() {
    nothin();
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=4939c0893b2493f2b7e87601fd4534c0))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unreachable expression
 --> src/main.rs:5:5
  |
4 |     loop{ };
  |     ------- any code following this expression is unreachable
5 |     5
  |     ^ unreachable expression
  |
  = note: `#[warn(unreachable_code)]` on by default

    Finished release [optimized] target(s) in 0.39s
     Running `target/release/playground`
timeout: the monitored command dumped core
/playground/tools/entrypoint.sh: line 11:     7 Illegal instruction     timeout --signal=KILL ${timeout} "$@"

```

**Comment by jonas-schievink** [comment] 2020-03-03 22:25
Duplicate of https://github.com/rust-lang/rust/issues/28728. The undefined instruction is a stopgap inserted by LLVM's TrapUnreachable feature.

**Closed by jonas-schievink** 2020-03-03 22:25 UTC
