### ISSUE TITLE
ICE in debuginfo when compiling openssl-sys for hyper

### ISSUE THREAD

**Issue by pwoolcoc** [rust-lang/rust#22533] opened 2015-02-19 12:25 UTC
```
$ RUST_BACKTRACE=1 cargo build
   Compiling url v0.2.20
   Compiling openssl-sys v0.4.1
/home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.4.1/src/lib.rs:1:1: 1:1 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 5326, node: ExprStruct(Path { span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 5327, node: ExprPath(Path { span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 5328, node: ExprPath(Path { span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(0), hi: BytePos(0), expn_id: ExpnId(4294967295) } })
/home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.4.1/src/lib.rs:1 #![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
                                                                                          ^
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129

stack backtrace:
   1:     0x7f5d5e9fbc20 - sys::backtrace::write::h82ddea1b95a85a4eEmB
   2:     0x7f5d5ea24590 - panicking::on_panic::h85aea1a0a8a00914oPK
   3:     0x7f5d5e96ba10 - rt::unwind::begin_unwind_inner::h0140173b3afd86ddJtK
   4:     0x7f5d5be34700 - rt::unwind::begin_unwind::h12705787916117446333
   5:     0x7f5d5be34690 - diagnostic::SpanHandler::span_bug::h9a2a76211bbae4f474E
   6:     0x7f5d5c9c4450 - session::Session::span_bug::h863b1ac2a3b0dc6df3s
   7:     0x7f5d5d757aa0 - trans::debuginfo::scope_metadata::hde26f0dc2a3c3e3b1FF
   8:     0x7f5d5d67c0c0 - trans::debuginfo::set_source_location::h68067f2f98bebfc6f8E
   9:     0x7f5d5d632ca0 - trans::expr::trans_into::hd59cc12ccbbd4bf1jGh
  10:     0x7f5d5d632ca0 - trans::expr::trans_into::hd59cc12ccbbd4bf1jGh
  11:     0x7f5d5d633810 - trans::controlflow::trans_block::h9b90284861c45f6eXee
  12:     0x7f5d5d6ffb50 - trans::base::trans_closure::h19dd2d794846819fFiu
  13:     0x7f5d5d6b28f0 - trans::closure::trans_closure_expr::heee6a176e804f75faqy
  14:     0x7f5d5d6e21b0 - trans::consts::const_expr_unadjusted::hd9b803a715935cf5amo
  15:     0x7f5d5d67c800 - trans::consts::get_const_expr_as_global::hc84cc3eabdeb1b49d6n
  16:     0x7f5d5d634350 - trans::expr::trans::h4351eca289d0e2e0BMh
  17:     0x7f5d5d66eba0 - trans::callee::trans_args::h1b18e06944a6c332rjh
  18:     0x7f5d5d6762c0 - trans::callee::trans_call_inner::h12072071618592006439
  19:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  20:     0x7f5d5d67db90 - trans::expr::trans_unadjusted::h5fd02bfb11a2d416mqi
  21:     0x7f5d5d634350 - trans::expr::trans::h4351eca289d0e2e0BMh
  22:     0x7f5d5d66eba0 - trans::callee::trans_args::h1b18e06944a6c332rjh
  23:     0x7f5d5d6762c0 - trans::callee::trans_call_inner::h12072071618592006439
  24:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  25:     0x7f5d5d67db90 - trans::expr::trans_unadjusted::h5fd02bfb11a2d416mqi
  26:     0x7f5d5d634350 - trans::expr::trans::h4351eca289d0e2e0BMh
  27:     0x7f5d5d66eba0 - trans::callee::trans_args::h1b18e06944a6c332rjh
  28:     0x7f5d5d674c60 - trans::callee::trans_call_inner::h5363918025704867457
  29:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  30:     0x7f5d5d632ca0 - trans::expr::trans_into::hd59cc12ccbbd4bf1jGh
  31:     0x7f5d5d735870 - trans::_match::mk_binding_alloca::h7260740157907718876
  32:     0x7f5d5d632370 - trans::base::init_local::h2a9485fc351fb28bSst
  33:     0x7f5d5d633810 - trans::controlflow::trans_block::h9b90284861c45f6eXee
  34:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  35:     0x7f5d5d632ca0 - trans::expr::trans_into::hd59cc12ccbbd4bf1jGh
  36:     0x7f5d5d633810 - trans::controlflow::trans_block::h9b90284861c45f6eXee
  37:     0x7f5d5d6ffb50 - trans::base::trans_closure::h19dd2d794846819fFiu
  38:     0x7f5d5d6b28f0 - trans::closure::trans_closure_expr::heee6a176e804f75faqy
  39:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  40:     0x7f5d5d67db90 - trans::expr::trans_unadjusted::h5fd02bfb11a2d416mqi
  41:     0x7f5d5d634350 - trans::expr::trans::h4351eca289d0e2e0BMh
  42:     0x7f5d5d66eba0 - trans::callee::trans_args::h1b18e06944a6c332rjh
  43:     0x7f5d5d6762c0 - trans::callee::trans_call_inner::h12072071618592006439
  44:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  45:     0x7f5d5d632ca0 - trans::expr::trans_into::hd59cc12ccbbd4bf1jGh
  46:     0x7f5d5d633810 - trans::controlflow::trans_block::h9b90284861c45f6eXee
  47:     0x7f5d5d67e750 - trans::expr::trans_rvalue_dps_unadjusted::hc36eeb7ee35234732Wi
  48:     0x7f5d5d632ca0 - trans::expr::trans_into::hd59cc12ccbbd4bf1jGh
  49:     0x7f5d5d633810 - trans::controlflow::trans_block::h9b90284861c45f6eXee
  50:     0x7f5d5d6ffb50 - trans::base::trans_closure::h19dd2d794846819fFiu
  51:     0x7f5d5d61f170 - trans::base::trans_fn::h44ba13a2cfb2d0cfWtu
  52:     0x7f5d5d61a7e0 - trans::base::trans_item::hc65485bf5afce36ePSu
  53:     0x7f5d5d7070b0 - trans::base::trans_crate::he871fef56c723b19fQv
  54:     0x7f5d5f067d40 - driver::phase_4_translate_to_llvm::h937508f260695223iPa
  55:     0x7f5d5f040d70 - driver::compile_input::h29175af5e0449232Eba
  56:     0x7f5d5f111340 - run_compiler::ha7fa41fc095a8c1dRbc
  57:     0x7f5d5f10f8a0 - thunk::F.Invoke<A, R>::invoke::h3106264713772749256
  58:     0x7f5d5f10e780 - rt::unwind::try::try_fn::h10764603828269452490
  59:     0x7f5d5ea910f0 - rust_try_inner
  60:     0x7f5d5ea910e0 - rust_try
  61:     0x7f5d5f10ea30 - thunk::F.Invoke<A, R>::invoke::h2636586800316248066
  62:     0x7f5d5ea0ff20 - sys::thread::thread_start::h90514f7c092cf9a6tWF
  63:     0x7f5d58ae00c0 - start_thread
  64:     0x7f5d5e5e2fd9 - __clone
  65:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
Could not compile `openssl-sys`.
```

**Comment by jdm** [comment] 2015-02-19 14:22
cc @michaelwoerister

**Comment by alexcrichton** [comment] 2015-02-19 15:35
Dupe of #22432

**Closed by alexcrichton** 2015-02-19 15:35 UTC
Labels: A-debuginfo
