### ISSUE TITLE
std library can not build for openwrt  mt7688

### ISSUE THREAD

**Issue by xiepenghe** [rust-lang/rust#43503] opened 2017-07-27 09:11 UTC
we use the openwrt  and the cpu is mt7688 ,we need to compile mipsel-unknown-linux-uclibc,when we build ,the error occure

```
native=/tmp/xargo.zHB2jKHFb0sK/target/mipsel-unknown-linux-uclibc/release/build/compiler_builtins-2512e083bf2db9eb/out`
error[E0432]: unresolved import `sys::net::netc::IPV6_ADD_MEMBERSHIP`
  --> /home/yangjie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/net.rs:33:5
   |
33 | use sys::net::netc::IPV6_ADD_MEMBERSHIP;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `IPV6_ADD_MEMBERSHIP` in the root. Did you mean to use `IP_ADD_MEMBERSHIP`?

error[E0432]: unresolved import `sys::net::netc::IPV6_DROP_MEMBERSHIP`
  --> /home/yangjie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/net.rs:43:5
   |
43 | use sys::net::netc::IPV6_DROP_MEMBERSHIP;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `IPV6_DROP_MEMBERSHIP` in the root. Did you mean to use `IP_DROP_MEMBERSHIP`?

error[E0308]: mismatched types
   --> /home/yangjie/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys/unix/stack_overflow.rs:129:27
    |
129 |         action.sa_flags = SA_SIGINFO | SA_ONSTACK;
    |                           ^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
    |
    = help: here are some functions which might fulfill your needs:
            - .count_ones()
            - .count_zeros()
            - .leading_zeros()
            - .trailing_zeros()

error: aborting due to 3 previous errors

error: Could not compile `std`.
```

**Comment by nagisa** [comment] 2017-08-04 19:29
As mipsel-*-ulibc is a obscure platform without a full-time maintainer, the fastest way to have this fixed would be to send the necessary fixes as a PR.

**Comment by jinks** [comment] 2017-08-17 21:36
Just for completeness' sake, the same problem exists on mips-*-ulibc.
I know it's an obscure platform that the rust team can't devote much time on, but OpenWRT routers are pretty popular with the tinkerer crowd for obvious reasons and rust would be a pretty good fit for the low power restricted hardware.

**Comment by terwey** [comment] 2017-11-05 21:08
I was confronted with this error too. Any updates to this?

**Comment by bochaco** [comment] 2018-03-14 14:51
I just ran into this as well trying to cross compile rust libs for Arduino-Yun (mips-*-uclibc). If anyone has some hints it'll be appreciated.

**Comment by sanxiyn** [comment] 2019-03-20 10:10
Fix for this was attempted in 2018-09. Please re-test with the latest Rust to check whether the issue is still present.

**Comment by Mark-Simulacrum** [comment] 2019-12-10 14:24
Closing -- if this hasn't been fixed, then a PR is the right way to do it.

**Closed by Mark-Simulacrum** 2019-12-10 14:24 UTC
Labels: C-bug, O-MIPS, T-libs
