### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /checkout/src/libcore/result.rs:906: 4

### ISSUE THREAD

**Issue by huangwenjun06** [rust-lang/rust#46149] opened 2017-11-21 07:52 UTC
when i build gecko-dev code. i have error.
error info: 
[sigbus_error.txt](https://github.com/rust-lang/rust/files/1490441/sigbus_error.txt)

bt info : 
[sigbus_error_bt.txt](https://github.com/rust-lang/rust/files/1490442/sigbus_error_bt.txt)

hardware: loongson3a (mips64el)
OS: fedora21
gcc: 4.9.3
rustc: 1.21.0 (download binary from rustup.rs)

**Comment by jackh726** [comment] 2022-10-24 23:49
Closing since nobody has been able to reproduce this is roughly 5 years.

**Closed by jackh726** 2022-10-24 23:49 UTC
Labels: C-bug
