### ISSUE TITLE
Shadowed variable isn't droped until the end of outer scope

### ISSUE THREAD

**Issue by arthurprs** [rust-lang/rust#26701] opened 2015-07-01 03:40 UTC
```
struct Test {
	n: usize
}

impl Drop for Test {
	fn drop(&mut self) {
		println!("dropping {}", self.n);
	}
}

fn main() {
    println!("Hello, world!");
    let a = Test { n: 1};
    println!("Hello, world 2.0!");
    let a = Test { n: 2};
    println!("Hello, world 3.0!");
}
```

produces

```
Hello, world!
Hello, world 2.0!
Hello, world 3.0!
dropping 2
dropping 1
```

I think most people would expect "dropping 1" to appear just before "Hello, world 3.0!"

Is this expected?

If yes, what's the reasoning? This is totally unexpected. I stumbled across this just now trying to understand why one of my tests were failing. After baning my head into a wall for some time I tried to insert a drop() just before the shadowing and voilà.

**Comment by remram44** [comment] 2015-07-01 05:59
I don't feel like this is unexpected at all. There is no reason for the accidental collision in names to change the semantics of anything. And how would you expect this to work?
```rust
fn main() {
    let a = Test { n: 1 };
    {
        let a = Test { n: 2};
        println!("Hello, world!");
    }
    // Nothing here, should the first a have already been dropped?
}
```
You also have the case where the first a might be borrowed somewhere (or even, by the new a).
```rust
struct Test<'a> {
    n: usize,
    r: Option<&'a Test<'a>>,
}

impl<'a> Drop for Test<'a> {
    fn drop(&mut self) {
        println!("dropping {}", self.n);
    }
}

fn main() {
    println!("Hello, world!");
    let a = Test { n: 1, r: None};
    println!("Hello, world 2.0!");
    let a = Test { n: 2, r: Some(&a) };
    println!("Hello, world 3.0!");
}
```
Guards are used this way, and it would be awkward if they were destroyed before you leave the scope. I can't think of an example for this, but things on the stack are destroyed in reverse order of creation, and I don't think you should expect otherwise.

**Comment by Gankro** [comment] 2015-07-01 20:04
This is 100% expected behaviour as far as I'm concerned. Especially if you consider

```
let y = bar;
let x = foo;
...
```

To be sugar for

```
{
  let y = bar;
  {
    let x = foo;
    ...
  }
}
```

**Comment by huonw** [comment] 2015-07-01 20:10
This makes code like the following work:

```rust
// make some string that isn't necessarily exactly what you want
let s: String = foo();
// convert it into the form you need, borrowing out of the original
let s: &str = s.trim();
```

The key point being the second `s` borrows out of the first, so the first needs to live for long enough to be useful. I find this pattern useful, because it ensures I use the correct/"processed" version always: it's literally impossible to access the first raw `s`.

**Comment by huonw** [comment] 2015-07-01 20:11
Closing since it's not a bug (and 1.0 has been released), but feel free to continue the discussion (here is fine, but users.rust-lang.org or internals.rust-lang.org might be more appropriate).

**Closed by huonw** 2015-07-01 20:11 UTC

**Comment by arthurprs** [comment] 2015-07-01 21:08
Kinda unexpected but it does make sense. Thank you all.

**Comment by pnkfelix** [comment] 2015-07-01 21:42
@arthurprs BTW maybe you meant to write this instead, which does drop the first instance of `Test` before saying Hello 3.0: http://is.gd/E3aZ9X

**Comment by arthurprs** [comment] 2015-07-01 22:47
That's a fairly good idea. I will probably use that instead of the drop and
then redeclaring.
Em 01/07/2015 18:43, "Felix S Klock II" <notifications@github.com> escreveu:
