### ISSUE TITLE
1.38: internal compiler error running `cargo clippy` on project with `mysql_common` dependency

### ISSUE THREAD

**Issue by eddrift** [rust-lang/rust#64832] opened 2019-09-27 06:29 UTC
```
...
Checking mysql_common v0.18.0
error: internal compiler error: src/librustc/ty/context.rs:516: node_type: no type for node `expr 5 (hir_id=HirId { owner: DefIndex(228), local_id: 255 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:644:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.38.0 (625451e37 2019-09-23) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `mysql_common`.

To learn more, run the command again with --verbose.
```

**Comment by eddrift** [comment] 2019-09-27 06:32
This is on macOS 10.14.6. The stack trace with `RUST_BACKTRACE=1` is pretty content-free:

```
    Checking mysql_common v0.18.0
error: internal compiler error: src/librustc/ty/context.rs:516: node_type: no type for node `expr 5 (hir_id=HirId { owner: DefIndex(228), local_id: 255 })`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:644:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
...
```
for 69 frames

**Comment by eddrift** [comment] 2019-09-27 06:34
cargo clippy worked on this project with rust 1.37, and non-clippy builds seem to be fine with 1.38

**Comment by matthiaskrgr** [comment] 2019-09-27 06:51
Duplicate of https://github.com/rust-lang/rust-clippy/issues/4579

**Closed** 2019-09-27 10:57 UTC
