### ISSUE TITLE
Allow the import of type-associated consts

### ISSUE THREAD

**Issue by Ben-Lichtman** [rust-lang/rust#86129] opened 2021-06-08 06:28 UTC
Currently there is no way to bring an associated const for a type into the current scope in the same way as pretty much anything else that is namespaced in rust can be.

- Enum variants may be brought into scope (such as Some, None, Ok and Err)
- consts may be brought into scope from modules

This poses an issue for things like bindings libraries where the library consumer does not have much choice over the naming of consts or other variables.

The following code should compile:

```rust
struct VeryLongNamedFlagsStruct(u32);

impl VeryLongNamedFlagsStruct {
    pub const SUPER_LONG_NAMED_CONST: Self = Self(5);
}

use VeryLongNamedFlagsStruct::SUPER_LONG_NAMED_CONST;

fn main() {
    // Using const name to avoid having to type very long type name also
    let x = SUPER_LONG_NAMED_CONST;
    
    println!("{}", x.0);
}
```

Currenly this code fails to compile with: 

> `VeryLongNamedFlagsStruct` is a struct, not a module

This has resulted in ergonomics issues for the windows-rs crate: https://github.com/microsoft/windows-rs/issues/835 - this crate has MANY "flag" type structs with consts, and these must be placed in the parent module to the type definition, resulting in more challenging library usage since each one of these consts must be both bound-to using the compile-time codegen, and brought into scope to be used in consuming libraries.

I propose allowing the import of assocated consts.

**Comment by steffahn** [comment] 2021-06-08 07:57
@rustbot label C-feature-request, A-associated-items, T-lang
related / duplicate: #44665

**Comment by jonas-schievink** [comment] 2021-06-08 09:30
Yeah this looks like a dupe of https://github.com/rust-lang/rust/issues/44665, so closing in favor of that. Personally I think this should be closed as a wontfix.

**Closed by jonas-schievink** 2021-06-08 09:30 UTC
Labels: A-associated-items, C-feature-request, T-lang

**Comment by Ben-Lichtman** [comment] 2021-06-08 09:42
Is there any particular reason that this is a wontfix? Seems like it would be a useful feature unless there's some technical reason that it can not be done...

**Comment by jonas-schievink** [comment] 2021-06-08 09:56
Mostly because, depending on how exactly the semantics are supposed to work, this might require making name resolution depend on type checking, which is a huge can of worms.

Given that you can just move or copy the consts to the containing module, I'm also not really convinced that this would add much.

**Comment by Ben-Lichtman** [comment] 2021-06-08 10:05
Ah, that's really a shame, and kinda counterintuitive - To me it seems like you could treat type names in the same way as module names and not need worry about type checking until later (I guess Self types might pose a problem though) - though I'm definitely speaking out of ignorance here.
