### ISSUE TITLE
HIR item node was not preallocated

### ISSUE THREAD

**Issue by xurtis** [rust-lang/rust#69369] opened 2020-02-22 11:02 UTC
I replaced a type variable with a concrete type across my 

I tried this change: https://github.com/xurtis/autumn/compare/e0554e8...00f2386

I expected the code to compile.

Instead, the compiler produced this error:

```
error: internal compiler error: src/librustc/dep_graph/graph.rs:680: DepNode Hir(autumn[d837]::location[0]::Location[0]::character[0]) should have been pre-allocated but wasn't.

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:905:9
```

### `rustc` version 

* rustc 1.41.0 (5e1a79984 2020-01-27)
* binary: rustc
* commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
* commit-date: 2020-01-27
* host: x86_64-unknown-linux-gnu
* release: 1.41.0
* LLVM version: 9.0

### Backtrace

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
  12: std::panicking::begin_panic
  13: rustc_errors::HandlerInner::bug
  14: rustc_errors::Handler::bug
  15: rustc::util::bug::opt_span_bug_fmt::{{closure}}
  16: rustc::ty::context::tls::with_opt::{{closure}}
  17: rustc::ty::context::tls::with_opt
  18: rustc::util::bug::opt_span_bug_fmt
  19: rustc::util::bug::bug_fmt
  20: rustc::dep_graph::graph::DepGraph::try_mark_previous_green
  21: rustc::dep_graph::graph::DepGraph::try_mark_green
  22: rustc::dep_graph::graph::DepGraph::try_mark_green_and_read
  23: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  24: <rustc_typeck::outlives::implicit_infer::InferVisitor as rustc::hir::itemlikevisit::ItemLikeVisitor>::visit_item
  25: rustc::hir::Crate::visit_all_item_likes
  26: rustc_typeck::outlives::inferred_outlives_crate
  27: rustc::ty::query::__query_compute::inferred_outlives_crate
  28: rustc::dep_graph::graph::DepGraph::with_task_impl
  29: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  30: rustc_typeck::outlives::inferred_outlives_of
  31: rustc::ty::query::__query_compute::inferred_outlives_of
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::inferred_outlives_of>::compute
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
  34: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  35: rustc_typeck::collect::predicates_defined_on
  36: rustc::ty::query::__query_compute::predicates_defined_on
  37: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::predicates_defined_on>::compute
  38: rustc::dep_graph::graph::DepGraph::with_task_impl
  39: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::force_query
  40: rustc::ty::query::plumbing::force_from_dep_node
  41: rustc::dep_graph::graph::DepGraph::try_mark_previous_green
  42: rustc::dep_graph::graph::DepGraph::try_mark_green
  43: rustc::dep_graph::graph::DepGraph::try_mark_green_and_read
  44: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  45: <rustc_typeck::collect::CollectItemTypesVisitor as rustc::hir::intravisit::Visitor>::visit_item
  46: rustc::hir::map::Map::visit_item_likes_in_module
  47: rustc_typeck::collect::collect_mod_item_types
  48: rustc::ty::query::__query_compute::collect_mod_item_types
  49: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::collect_mod_item_types>::compute
  50: rustc::dep_graph::graph::DepGraph::with_task_impl
  51: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  52: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::ensure_query
  53: rustc_typeck::check_crate::{{closure}}::{{closure}}
  54: rustc::util::common::time
  55: rustc_typeck::check_crate
  56: rustc_interface::passes::analysis
  57: rustc::ty::query::__query_compute::analysis
  58: rustc::dep_graph::graph::DepGraph::with_task_impl
  59: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  60: rustc::ty::context::tls::enter_global
  61: rustc_interface::interface::run_compiler_in_existing_thread_pool
  62: std::thread::local::LocalKey<T>::with
  63: scoped_tls::ScopedKey<T>::set
  64: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.41.0 (5e1a79984 2020-01-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [type_of] processing `location::Location::character`
#1 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
#2 [inferred_outlives_of] processing `combinators::Multiple`
#3 [predicates_defined_on] processing `combinators::Multiple`
#4 [predicates_of] processing `combinators::Multiple`
#5 [collect_mod_item_types] collecting item types in module `combinators`
#6 [analysis] running analysis passes on this crate
end of query stack
```

**Comment by xurtis** [comment] 2020-02-22 11:17
Does not appear to be an issue on nightly rustc.

**Comment by xurtis** [comment] 2020-02-22 11:32
The following changes still cause the same errors but compile and pass all of my tests in nightly: https://github.com/xurtis/autumn/compare/e0554e8...321478d

Nightly version:

* rustc 1.43.0-nightly (8aa9d2014 2020-02-21)
* binary: rustc
* commit-hash: 8aa9d2014f4e5258f83b907e8431c59a33acdae7
* commit-date: 2020-02-21
* host: x86_64-unknown-linux-gnu
* release: 1.43.0-nightly
* LLVM version: 9.0

The following beta also builds and runs tests without issue:

* rustc 1.42.0-beta.3 (86f329b41 2020-02-07)
* binary: rustc
* commit-hash: 86f329b419dbac59da59e2ac7d6e21e5eb679ec7
* commit-date: 2020-02-07
* host: x86_64-unknown-linux-gnu
* release: 1.42.0-beta.3
* LLVM version: 9.0

**Comment by jonas-schievink** [comment] 2020-02-22 12:09
Duplicate of https://github.com/rust-lang/rust/issues/62649

**Closed by jonas-schievink** 2020-02-22 12:09 UTC
