### ISSUE TITLE
liftime analysis error when return mutable reference

### ISSUE THREAD

**Issue by Sherlock-Holo** [rust-lang/rust#86842] opened 2021-07-03 15:25 UTC
I tried this code:

```rust
use std::collections::HashMap;

fn main() {}

struct St {
    map: HashMap<i32, String>,
}

impl St {
    pub fn ttt(&mut self) -> &mut String {
        if let Some(s) = self.map.values_mut().find(|s| *s == "123") {
            return s;
        }

        if let Some(s) = self.map.values_mut().find(|s| *s == "456") {
            return s;
        }

        todo!()
    }
}
```

I expected to see this happen: `cargo check` won't report error

Instead, this happened: 
```
   |
10 |     pub fn ttt(&mut self) -> &mut String {
   |                - let's call the lifetime of this reference `'1`
11 |         if let Some(s) = self.map.values_mut().find(|s| *s == "123") {
   |                          -------- first mutable borrow occurs here
12 |             return s;
   |                    - returning this value requires that `self.map` is borrowed for `'1`
...
15 |         if let Some(s) = self.map.values_mut().find(|s| *s == "456") {
   |                          ^^^^^^^^ second mutable borrow occurs here
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

**Comment by kvinwang** [comment] 2021-07-03 16:09
Looks like a duplicate of https://github.com/rust-lang/rust/issues/58910

**Comment by crlf0710** [comment] 2021-07-03 16:16
Indeed, let's close this in favor of that one.

**Closed by crlf0710** 2021-07-03 16:16 UTC
Labels: C-bug, NLL-polonius
