### ISSUE TITLE
SIGABRT ICE in proc macro

### ISSUE THREAD

**Issue by K4rakara** [rust-lang/rust#100257] opened 2022-08-08 02:41 UTC
This is a really weird one... and it might be a bit of a mess to debug. I honestly wish I could tell you more, but this is beyond my knowledge of the compiler.

### Code

This requires multiple crates, due to it being a proc macro issue. [Here](https://github.com/rust-lang/rust/files/9278216/repo.zip) is the smallest reproducible case I was able to create.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (d394408fb 2022-08-07)
binary: rustc
commit-hash: d394408fb38c4de61f765a3ed5189d2731a1da91
commit-date: 2022-08-07
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 14.0.6

```

### Error output

```
   Compiling big_mac v0.1.0 (/tmp/repo/macro)
   Compiling lib v0.1.0 (/tmp/repo/lib)
fatal runtime error: failed to initiate panic, error 5
error: could not compile `lib`

Caused by:
  process didn't exit successfully: `rustc --crate-name lib --edition=2021 lib/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a2786eed45a16c47 -C extra-filename=-a2786eed45a16c47 --out-dir /tmp/repo/target/debug/deps -C incremental=/tmp/repo/target/debug/incremental -L dependency=/tmp/repo/target/debug/deps --extern big_mac=/tmp/repo/target/debug/deps/libbig_mac-47b147c1d91db7e1.so` (signal: 6, SIGABRT: process abort signal)
```

There is no backtrace, since it failed to initiate a panic, and therefore failed to initiate a stack unwind.

**Comment by K4rakara** [comment] 2022-08-08 02:42
Worth noting: this happens both on nightly and on stable.

**Comment by luqmana** [comment] 2022-08-08 04:18
I believe this is a dupe of https://github.com/rust-lang/rust/issues/63804. Sticking proc_macro types in TLS is not supported (which is what `memoize!` is doing in your repro).

**Comment by K4rakara** [comment] 2022-08-08 04:37
This isn't holding the generated token streams outside the lifetime of the macro invocation though, so shouldn't it be fine?

**Comment by luqmana** [comment] 2022-08-08 05:00
The `MEMO` thread local generated in each function `memoize!` is applied to (just `generics_and_tuples` in this case) will stick around until it is cleaned up at thread destruction. What's happening here is it seems that that cleanup occurs after the proc macro server disconnects and so when the proc_macro types in your thread local go to notify the server to clean up the corresponding data, it hits this panic: https://github.com/rust-lang/rust/blob/93ab13b4e894ab74258c40aaf29872db2b17b6b4/library/proc_macro/src/bridge/client.rs#L313

As for why the error is so opaque (`failed to initiate panic`) that's a separate bug with TLS dtors + panics: https://github.com/rust-lang/rust/issues/24479

**Comment by bjorn3** [comment] 2022-08-09 11:23
Should this issue be closed as not a bug?

**Closed** 2022-08-09 13:31 UTC
Labels: I-ICE, T-compiler, C-bug
