### ISSUE TITLE
Intermittent panic on `old_io::process::tests::test_kill`

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#23440] opened 2015-03-17 13:23 UTC
```
thread '<unnamed>' panicked at 'assertion failed: !p.wait().unwrap().success()', /Users/rustbuild/src/rust-buildbot/slave/auto-mac-64-opt/build/src/libstd/old_io/process.rs:1137
test old_io::process::tests::test_kill ... FAILED
```

For example, http://buildbot.rust-lang.org/builders/auto-mac-64-opt/builds/4096 failed, but the rollup containing that PR [passed on the same builder](http://buildbot.rust-lang.org/builders/auto-mac-64-opt/builds/4097)

**Comment by alexcrichton** [comment] 2015-03-17 16:47
Dupe of https://github.com/rust-lang/rust/issues/19120 (listed on there), but it is indeed unfortunate :(

**Closed by alexcrichton** 2015-03-17 16:47 UTC
