### ISSUE TITLE
Trait object implicit coercions through a `match` are incorrectly codegen'd

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#20419] opened 2015-01-02 06:18 UTC
```rust
trait Foo {}
impl Foo for () {}

#[cfg(not(good))]
fn foo(x: bool) -> Box<Foo+'static> {
    match x {
        true => box() (),
        false => box() ()
    }
}
#[cfg(good)]
fn foo(x: bool) -> Box<Foo+'static> {
    match x {
        true => box() () as Box<Foo>,
        false => box() () as Box<Foo>
    }
}

fn main() {
    foo(true);
    foo(false);
}
```

Compiling with `--cfg good` (i.e. explicit casts) runs 100% fine, compiling without it (i.e. implicit coercions) segfaults/crashes. This also runs fine on 0.12 on the playpen, and with `if x {` instead of `match` .

cc @nick29581 (maybe?)

**Comment by shepmaster** [comment] 2015-01-02 20:22
Perhaps duplicate of #20097?

**Comment by alexcrichton** [comment] 2015-01-20 06:07
Closing as a dupe of https://github.com/rust-lang/rust/issues/20097

**Closed by alexcrichton** 2015-01-20 06:07 UTC
Labels: I-crash
