### ISSUE TITLE
Recursive generic function with std::fmt::Borrow bound expects the same generic type for recursive call

### ISSUE THREAD

**Issue by timvermeulen** [rust-lang/rust#58510] opened 2019-02-16 11:44 UTC
```rust
fn f<T: ?Sized>(_: &T)
where
    String: std::borrow::Borrow<T>,
{
    // doesn't compile:
    f("");
    
    // compiles:
    f::<str>("");
}
```
```
error[E0308]: mismatched types
 --> src/lib.rs:6:7
  |
6 |     f("");
  |       ^^ expected type parameter, found str
  |
  = note: expected type `&T`
             found type `&'static str`
```

**Comment by ExpHP** [comment] 2019-02-19 14:30
See https://github.com/rust-lang/rust/issues/24066

**Comment by Enselic** [comment] 2023-11-20 09:52
Triage: Closing as duplicate of https://github.com/rust-lang/rust/issues/24066 because the root cause is likely the same.

**Closed by Enselic** 2023-11-20 09:52 UTC
Labels: A-typesystem, T-compiler
