### ISSUE TITLE
error when compiler\rustc_builtin_macros\src\format.rs

### ISSUE THREAD

**Issue by yxdxx** [rust-lang/rust#99326] opened 2022-07-16 12:48 UTC
### Code

```Rust
just run cargo install bottom
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (23e21bdd2 2022-07-15)
binary: rustc
commit-hash: 23e21bdd25026e2839ebe946c2a937c1904887d2
commit-date: 2022-07-15
host: x86_64-pc-windows-msvc
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
Compiling time v0.3.11
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 2', compiler\rustc_builtin_macros\src\format.rs:1001:28
stack backtrace:
   0:     0x7ffa28229d4f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h307917635c002872
   1:     0x7ffa282654aa - core::fmt::write::h7c145a3ad923bd2a
   2:     0x7ffa2821cbaa - <std::io::IoSlice as core::fmt::Debug>::fmt::h6f1e6f75cd82fad9
   3:     0x7ffa2822d74b - std::panicking::default_hook::h93058762785c9b20
   4:     0x7ffa2822d377 - std::panicking::default_hook::h93058762785c9b20
   5:     0x7ffa220dd234 - <rustc_session[546c491e9b4e1412]::options::WasiExecModel as rustc_session[546c491e9b4e1412]::config::dep_tracking::DepTrackingHash>::hash
   6:     0x7ffa2822e12c - std::panicking::rust_panic_with_hook::hd52b3c7b82c3f7ee
   7:     0x7ffa2822dead - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h136700dfa82d6086
   8:     0x7ffa2822aa47 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h307917635c002872
   9:     0x7ffa2822db80 - rust_begin_unwind
  10:     0x7ffa2829b475 - core::panicking::panic_fmt::h8fdb7c372ffbd9c8
  11:     0x7ffa2829b397 - core::panicking::panic_bounds_check::hd441d9d239650abe
  12:     0x7ffa2026c11b - <rustc_builtin_macros[aefb6e13cf890c81]::source_util::expand_include::ExpandResult as rustc_expand[e608cf44d42461c8]::base::MacResult>::make_items
  13:     0x7ffa20264877 - <rustc_builtin_macros[aefb6e13cf890c81]::source_util::expand_include::ExpandResult as rustc_expand[e608cf44d42461c8]::base::MacResult>::make_items
  14:     0x7ffa21c15172 - <rustc_expand[e608cf44d42461c8]::expand::MacroExpander>::fully_expand_fragment
  15:     0x7ffa20753bc7 - <rustc_expand[e608cf44d42461c8]::expand::MacroExpander>::expand_crate
  16:     0x7ffa1fad25ba - <rustc_interface[d287fd77f9e86d82]::queries::Linker>::link
  17:     0x7ffa1fae43a7 - <rustc_interface[d287fd77f9e86d82]::passes::LintStoreExpandImpl as rustc_expand[e608cf44d42461c8]::base::LintStoreExpand>::pre_expansion_lint
  18:     0x7ffa1facda5b - <rustc_interface[d287fd77f9e86d82]::queries::Queries>::expansion
  19:     0x7ffa1faa5cd4 - <unknown>
  20:     0x7ffa1fabdf97 - rustc_driver[ac76e66f7f3697ae]::args::arg_expand_all
  21:     0x7ffa1faa77f9 - <unknown>
  22:     0x7ffa1faa82fd - <rustc_middle[e680d5079948de0d]::ty::SymbolName as core[1f034e7b5c60c27c]::fmt::Debug>::fmt
  23:     0x7ffa2823f04c - std::sys::windows::thread::Thread::new::h864ff1b78a448a0f
  24:     0x7ffa9e1d54e0 - BaseThreadInitThunk
  25:     0x7ffa9fb0485b - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (23e21bdd2 2022-07-15) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=3 -C linker-plugin-lto -C codegen-units=1 -C debuginfo=0

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `time`
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bottom v0.6.8`, intermediate artifacts can be found at `C:\Users\yx\AppData\Local\Temp\cargo-installt7JnUM`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by humb1t** [comment] 2022-07-16 13:01
Same issue in different project when using fresh niightly toolchain

**Comment by Nilstrieb** [comment] 2022-07-16 13:53
Appears to be a duplicate of #99261

**Comment by compiler-errors** [comment] 2022-07-16 17:02
This should be fixed on tomorrow's nightly

**Closed by compiler-errors** 2022-07-16 17:02 UTC
Labels: I-ICE, T-compiler, C-bug
