### ISSUE TITLE
Type inference: weird behavior of compiler missing type info in unambiguous test case

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-lang/rust#47709] opened 2018-01-24 14:44 UTC
Hi, I found a weird looking inference behavior.

I have a piece of code (reduced the best I could) that doesn't compile even though it seems that there are no type ambiguities.
But what's even weirder is that removing some code that shouldn't have any effects (an identity `map()`) makes the code compile. This does, however, proves (AFAIK) that type inference in this example is unambiguous and that rustc is indeed capable of solving it.

Here is the code:
```rust
#[derive(PartialEq)]
struct Foo {
    bar: u64
}

fn test() -> Option<Foo> {
    vec![Foo{bar:0}].into_iter()
        .fold(None, |acc, o| {
            if let Some(acc) = acc {
                if o.bar == acc.bar {
                    return Some(acc)
                }
            }
            Some(o)
        }).map(|o| {
            o
        })
}

fn main() {
    test();
}
```
The compilation will fail:
```
error[E0619]: the type of this value must be known in this context
  --> src/main.rs:10:29
   |
10 |                 if o.bar == acc.bar {
   |                             ^^^^^^^

```
However, it will compile if you do any of those things:
- replace `None` by `None::<Foo>`
- remove the last useless identity `map()`
- replace `o.bar == acc.bar` by `o == acc`

So for instance, this seemingly identical code will compile:
```rust
#[derive(PartialEq)]
struct Foo {
    bar: u64
}

fn test() -> Option<Foo> {
    vec![Foo{bar:0}].into_iter()
        .fold(None, |acc, o| {
            if let Some(acc) = acc {
                if o.bar == acc.bar {
                    return Some(acc)
                }
            }
            Some(o)
        })/*.map(|o| {  // only this part was removed
            o
        })*/
}

fn main() {
    test();
}
```
and this one will also compile fine but thanks to a completely different kind of change:
```rust
#[derive(PartialEq)]
struct Foo {
    bar: u64
}

fn test() -> Option<Foo> {
    vec![Foo{bar:0}].into_iter()
        .fold(None, |acc, o| {
            if let Some(acc) = acc {
                if o/*.bar*/ == acc/*.bar*/ { // now I compare the whole struct instead of the bar member
                    return Some(acc)
                }
            }
            Some(o)
        }).map(|o| {
            o
        })
}

fn main() {
    test();
}
```

**Playground**:
https://play.rust-lang.org/?gist=6934d0a3d56d305c8638fd446cdd1d70&version=nightly

@mbrubeck : because we spoke about it on IRC.

**Comment by skade** [comment] 2018-01-27 08:49
This seems to be another instance of this issue.

https://github.com/AndyBarron/app-dirs-rs/issues/28

**Comment by nikomatsakis** [comment] 2018-02-27 18:04
Is this a regression? (i.e., did it used to work in some prior version of rustc?)

**Comment by mbrubeck** [comment] 2018-02-27 18:08
I tested as far back as 1.12.0 and got the same error, so if it's a regression it's not a very recent one.

**Comment by nikomatsakis** [comment] 2018-02-27 18:09
I don't really think this is a bug. The proper fix is probably to annotate the closure type parameter:

```rust
#[derive(PartialEq)]
struct Foo {
    bar: u64
}

fn test() -> Option<Foo> {
    vec![Foo{bar:0}].into_iter()
        .fold(None, |acc: Option<Foo>, o| {
            if let Some(acc) = acc {
                if o.bar == acc.bar {
                    return Some(acc)
                }
            }
            Some(o)
        }).map(|o| {
            o
        })
}
```

Let me explain what's going on in the compiler anyway:

- In the code as written, we know that the type of `acc` is `Option<_>` because it was initialized from `None`, but we don't know what the "inner" type is. So that means we can't figure out the field lookup in the expression `acc.bar`.
- Why then does it work when the `map` is removed? The reason is that, in that case, we have a direct connection from the return type of `fold` to the return type of the surrounding function. We have some special inference that will try to glean information from the return type and apply it to the parameters; so in that case we are able to see that the type of `ann` is `Option<Foo>`.

If we sever the connection between the `fold` and the return, then we get an error again:

```rust
fn test() -> Option<Foo> {
    let r = vec![Foo{bar:0}].into_iter()
        .fold(None, |acc, o| {
            if let Some(acc) = acc {
                if o.bar == acc.bar {
                    return Some(acc)
                }
            }
            Some(o)
        });
    r
}
```

So, I think I would close this as "working as designed, unfortunately". That is, we'd always like to do better.

**Comment by PaulGrandperrin** [comment] 2018-02-27 18:09
For info, I hit this bug by writing new code, not by upgrading rustc.
But maybe this would have worked on an older rustc.. I don't know.

**Comment by PaulGrandperrin** [comment] 2018-02-27 18:15
Ok, I just thought that type information was expected to "flow" infinitely but it seems to be a reasonable limitation as it's a very convoluted piece of code and it's kind of easy to fix.

**Comment by nikomatsakis** [comment] 2018-02-27 18:23
@PaulGrandperrin ideally it would flow infinitely :) but there are some operations (field access is one of them) where we currently give errors if we do not know the type information at the time we need it (versus waiting until it is available). I'm going to go ahead and close then, thanks for the bug report!

**Closed by nikomatsakis** 2018-02-27 18:23 UTC
Labels: A-inference, C-bug

**Comment by nikomatsakis** [comment] 2018-02-27 22:30
I just wanted to note that, thanks to @csmoe, on nightly the error message tells you where to add the type annotation:

```
error[E0282]: type annotations needed
 --> src/main.rs:8:22
  |
8 |         .fold(None, |acc, o| {
  |                      ^^^ consider giving this closure parameter a type

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment] 2018-02-27 22:31
it'd be nice if it could explain just a bit more *why* that is needed, though :(

**Comment by PlasmaPower** [comment] 2018-03-02 02:14
This is a regression. As seen in [this Travis build](https://travis-ci.org/PlasmaPower/ghcl/builds/347998640), `app_dirs` fails to build for MacOS with beta and nightly but it works fine on stable.

**Comment by mbrubeck** [comment] 2018-03-02 14:33
That app_dirs error must be a different bug, then. Can you file a separate issue for it, please?

**Comment by PlasmaPower** [comment] 2018-03-02 14:41
Done: https://github.com/rust-lang/rust/issues/48668
