### ISSUE TITLE
Compiling to Shared Library doesn't always expose reexported symbols

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#50007] opened 2018-04-16 19:38 UTC
Consider the following:

We have 2 crates, rlib `helper` and the shared library `foo` that depends on the `helper` crate. The helper crate's lib.rs looks like this:
```rust
#[no_mangle]
pub extern fn bla() -> i32 {
    5
}
```
The shared library's lib.rs looks like this:
```rust
extern crate helper;

pub use helper::bla;
```

The code is then compiled to a shared library. The bla symbol is not exported. That does not seem intentional.

**Comment by dbrgn** [comment] 2018-05-15 08:44
Maybe a duplicate of #36342?

**Comment by thomcc** [comment] 2018-11-08 22:11
It's not a duplicate of #36342, which is about reexporting functions defined in C AFAICT. We've been struggling with this in https://github.com/mozilla/application-services.

This doesn't seem to happen with all targets. In particular, `x86_64-apple-darwin` seems unaffected, while `i686-linux-android` is effected (really all android targets seem to be affected).

I have a simple reproducable case at https://github.com/thomcc/megazord/tree/simple-bug-repro (e.g. the simple-bug-repro branch of that repository). An explanation for how to use it to reproduce the issue is in the README.md.

**Comment by ncalexan** [comment] 2018-11-08 22:14
> This doesn't seem to happen with all targets. In particular, `x86_64-apple-darwin` seems unaffected, while `i686-linux-android` is effected (really all android targets seem to be affected).

For more context: the Android toolchains are all specifying a stand-alone Android NDK toolchain, in particular a clang-based toolchain.  I believe our Desktop targets (like `x86_64-apple-darwin`) are GCC based.  So we may just be seeing a `clang`-ism as it passes linking through to an Android NDK toolchain GNU `ld`.  I haven't tried `lld` to get to the bottom of this.

**Comment by thomcc** [comment] 2019-06-10 20:48
This seems to have gotten worse. In the past, the re-exported functions would be exposed so long as they were at least *used* (by publicly visible extern "C" functions in the crate re-exporting things).

Now it seems that no matter what they aren't (note: this is only on some platforms, like android).

**Comment by Mark-Simulacrum** [comment] 2019-08-10 10:44
The right fix here might be that the relevant extern blocks should get `kind = "static"` on the link attributes, per https://github.com/rust-lang/rust/issues/62088#issuecomment-505694818.

**Comment by thomcc** [comment] 2019-08-10 19:27
@Mark-Simulacrum This issue is about no_mangle symbols from another crate that get brought in by `use`. There are no `extern` blocks.

**Comment by kvark** [comment] 2020-02-12 21:24
Heads up - this hits us in https://github.com/gfx-rs/wgpu as well. Very annoying and inconvenient, would very much appreciate any progress here!

**Comment by hansihe** [comment] 2020-05-14 21:35
Hitting this issue as well.

My use-case is exporting some functions from my executable, then loading a dynamic library that needs to link to those symbols.

**Comment by DethRaid** [comment] 2021-10-09 16:58
I'm running into this trying to use wgpu-native on Android. Is there any workaround for this issue?

**Comment by hansihe** [comment] 2021-10-09 17:11
My workaround was to make sure the symbols are exported from the root crate being built.

**Closed** 2022-04-25 18:58 UTC
Labels: A-linkage, T-compiler, C-bug
