### ISSUE TITLE
Wasm with lto and use of f32::sin() gets an unknown reference to `env` module

### ISSUE THREAD

**Issue by rodrigorc** [rust-lang/rust#72758] opened 2020-05-29 20:31 UTC
This bug was wrongly posted at [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen/issues/2160), but it looks like it is a compiler issue.

The following example fails to create a proper module, with either:
* rustc 1.44.0-beta.4 (02c25b359 2020-05-23)
* rustc 1.45.0-nightly (a74d1862d 2020-05-14)
(stable rustc 1.43.1 works fine).

### `Cargo.toml`
```
[package]
name = "wasm-env-issue"
version = "0.1.0"
edition = "2018"

[lib]
crate-type=["cdylib"]

[profile.release]
lto = true
panic = "abort"

[dependencies]
wasm-bindgen = "0.2.55"
```
### `src/lib.rs`
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn wasm_sin(key: i32) -> i32 {
    (key as f32).sin() as i32
}
```
With this command to compile:
```
wasm-pack build --no-typescript --target no-modules
```
produces this error:
> error: cannot import from modules (env) with --no-modules

Looking at the compiled `wasm`, with `wasm-dis`, there is this line that doesn't seem correct.
```
(import "env" "_ZN4core9panicking18panic_bounds_check17hadfb911a22557eccE" (func $_ZN4core9panicking18panic_bounds_check17hadfb911a22557eccE (param i32 i32 i32)))
```

Switching `lto` to `false` or changing the `sin()` to `asin()`, for example, make the `"env"` disappear.

**Comment by alexcrichton** [comment] 2020-05-29 20:46
For some more background on this issue, this is a standalone reproduction:

```rust
#[no_mangle]
pub extern "C" fn wasm_sin(key: i32) -> i32 {
    (key as f32).sin() as i32
}
```

where the issue can be seen with:

```sh
$ rustc +stable foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O
$ wasm2wat foo.wasm | rg import
$ rustc +stable foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O -C lto
$ wasm2wat foo.wasm | rg import
$ rustc +beta foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O
$ wasm2wat foo.wasm | rg import
$ rustc +beta foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O -C lto
$ wasm2wat foo.wasm | rg import
  (import "env" "_ZN4core9panicking18panic_bounds_check17hadfb911a22557eccE" (func $_ZN4core9panicking18panic_bounds_check17hadfb911a22557eccE (type 0)))
```

Here the bug is that, in beta (and onwards) with LTO turned on there's an unresolved symbol.

Bisection pointed out https://github.com/rust-lang/rust/pull/70846 as the cause of the bug here. The problem appears to be that previously compiler-builtins was optimized enough such that llvm removed all panics and bounds checks, but with a codegen unit reshuffling of compiler-builtins this did not happen and a bounds check was still in there.

It's intended that compiler-builtins cannot panic, and we [even have a test that this is the case](https://github.com/rust-lang/compiler-builtins/blob/4bf8cad593c06c7996cf4e25834bef159d59f48b/ci/run.sh#L83-L104). Unfortunately though WebAssembly wasn't tested on CI which notably activates the libm intrinsics, which is where the panic was coming from here (the sin function). I expanded testing to include wasm in https://github.com/rust-lang/compiler-builtins/pull/360, and the first few commits failed showing lots of references to panics.

I fixed the implementation in libm at https://github.com/rust-lang/libm/pull/244. Most of those changes were so in *debug* mode there weren't panic checks. In release mode there was [only one panic check](https://github.com/rust-lang/libm/pull/244/files#diff-e4a29385c2889a35eaa8f27b9334911fL245) which needed fixing, but fixing them all was needed for compiler-builtins's CI.

I've submitted a fix for this in https://github.com/rust-lang/rust/pull/72759 by updating compiler-builtins.

**Closed** 2020-05-31 13:39 UTC
Labels: C-bug, I-prioritize, O-wasm, regression-from-stable-to-beta
