### ISSUE TITLE
ICE: thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1', /usr/src/rustc-1.32.0/src/libcore/slice/mod.rs:2463:10

### ISSUE THREAD

**Issue by teythoon** [rust-lang/rust#60821] opened 2019-05-14 10:55 UTC
This has never happened to me before, but now it happens if I run `cargo test` a second time.  Unfortunately, I don't know what causes it, I'm just working on my project as usual.  This is rustc 1.32 as packaged by Debian/testing as of May.

Running `cargo clean -p sequoia-openpgp` didn't help, only removing the target directory helps.

```
-*- mode: compilation; default-directory: "~/repos/pep/sequoia/" -*-
Compilation started at Tue May 14 12:46:50

cd ~/repos/pep/sequoia &&
                      RUST_BACKTRACE=1 cargo test -p sequoia-openpgp -- &&

   Compiling sequoia-openpgp v0.7.0 (/home/teythoon/repos/pep/sequoia/openpgp)
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1', /usr/src/rustc-1.32.0/src/libcore/slice/mod.rs:2463:10
stack backtrace:
   0: rust_metadata_std_e38910ff5ff1fe246e3ccfc03798ae3
   1: rust_metadata_std_e38910ff5ff1fe246e3ccfc03798ae3
   2: rust_metadata_std_e38910ff5ff1fe246e3ccfc03798ae3
   3: rust_metadata_std_e38910ff5ff1fe246e3ccfc03798ae3
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: rust_metadata_std_e38910ff5ff1fe246e3ccfc03798ae3
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: <rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x> as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode
  11: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  12: <rustc::ty::query::on_disk_cache::CacheDecoder<'a, 'tcx, 'x> as serialize::serialize::SpecializedDecoder<syntax_pos::span_encoding::Span>>::specialized_decode
  13: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  14: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  15: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  16: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  17: <unknown>
  18: <unknown>
  19: <rustc::ty::query::queries::optimized_mir<'tcx> as rustc::ty::query::config::QueryDescription<'tcx>>::try_load_from_disk
  20: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  21: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::instance_mir
  22: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  23: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  24: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  25: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  26: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  27: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  28: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  29: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  30: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  31: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  32: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  33: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  34: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  35: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  36: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  37: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  38: rust_metadata_rustc_mir_314d36b72e10fa2fd1d6459fcca09475
  39: <unknown>
  40: <unknown>
  41: rustc_mir::monomorphize::collector::collect_crate_mono_items
  42: <unknown>
  43: <unknown>
  44: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  45: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  46: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  47: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  48: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  49: rust_metadata_rustc_446f41f00d320d51dc333420d4f784f1
  50: <unknown>
  51: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  52: <unknown>
  53: rustc_driver::driver::phase_4_codegen
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
  58: rustc_driver::driver::compile_input
  59: <unknown>
  60: <unknown>
  61: rustc_driver::run_compiler
  62: <unknown>
  63: __rust_maybe_catch_panic
  64: <unknown>
  65: rustc_driver::main
  66: <unknown>
  67: rust_metadata_std_e38910ff5ff1fe246e3ccfc03798ae3
  68: __rust_maybe_catch_panic
  69: std::rt::lang_start_internal
  70: <unknown>
  71: __libc_start_main
  72: <unknown>
query stack during panic:
#0 [collect_and_partition_mono_items] collect_and_partition_mono_items
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0 running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `sequoia-openpgp`.
warning: build failed, waiting for other jobs to finish...
error: build failed

Compilation exited abnormally with code 101 at Tue May 14 12:47:01
```

**Comment by jonas-schievink** [comment] 2019-05-14 11:06
Thanks for the report! Your Rust version is quite a few releases behind, I'd be helpful if you can switch to the current nightly distributed by rustup and try to reproduce with that (eg. using `rustup override add nightly` in your project directory).

The backtrace you posted also looks a bit incomplete which doesn't normally happen on Linux. Maybe that's due to the Debian packaging and will also be fixed by switching to the official nightly.

**Comment by teythoon** [comment] 2019-05-14 12:04
> Your Rust version is quite a few releases behind, I'd be helpful if you can switch to the current nightly distributed by rustup and try to reproduce with that

I know that it is behind, and I appreciate that it would be helpful for debugging to reproduce it with a newer version.  However, this is the version that will ship with Debian 10 (Buster), and will have to be supported for the lifetime of Debian 10 (I guess two to four years).

> The backtrace you posted also looks a bit incomplete which doesn't normally happen on Linux.

I'm sorry about that.  I didn't have the debugging symbols installed (`rustc-dbgsym`).  I should have installed it immediately, and rerun rustc while I had the chance, but didn't, and now I cannot seem to reproduce it.  Again, I'm sorry.

Feature request:  If the above backtrace did include the addresses that failed to resolve, I could have annotated the trace after the fact.

**Comment by jonas-schievink** [comment] 2019-05-14 12:30
> I know that it is behind, and I appreciate that it would be helpful for debugging to reproduce it with a newer version. However, this is the version that will ship with Debian 10 (Buster), and will have to be supported for the lifetime of Debian 10 (I guess two to four years).

True, but Rust upstream doesn't offer support for older stable releases. If we know that this is still an issue on nightly, we know that it has to be fixed for all users, not just those on Debian, and once it's fixed in nightly Debian can backport the fix if they want.

> I'm sorry about that. I didn't have the debugging symbols installed (rustc-dbgsym). I should have installed it immediately, and rerun rustc while I had the chance, but didn't, and now I cannot seem to reproduce it. Again, I'm sorry.

No worries! For some reason there's still a few symbol in the backtrace, so I didn't think it was because the package was missing.

---

For reference, this problem seems to occur on https://gitlab.com/sequoia-pgp/sequoia at current master (0e74cf1b).

**Comment by pnkfelix** [comment] 2019-05-16 11:20
triage: I'm not sure how to prioritize this. It sounds like the reporter is having a lot of difficulty reproducing the issue (something that is not surprising given that it is an incremental compilation bug). I would personally be inclined to either mark this as P-medium, or just close it and mark that there are a number of other index-out-of-bounds issues that are suspected to be related to incremental compilation (Well, maybe), and thus our attention is best spent on them.

Having said that, the [most recent comment](https://github.com/rust-lang/rust/issues/60821#issuecomment-492216879) says that the problem occurs on sequioa-pgp/sequoia with the current master ... so maybe that *is* something actionable on our end...?

**Comment by pnkfelix** [comment] 2019-05-16 11:21
... triage: Leaving nominated and unprioritized. Hopefully we can discuss at T-compiler triage meeting today.

**Comment by teythoon** [comment] 2019-05-16 11:40
It did occur on Sequoia, but I was developing a patch.  I tried to incrementally apply the patch, trying to recreate whatever condition that triggered the bug, but failed.

**Comment by pnkfelix** [comment] 2019-05-16 14:56
discussed at T-compiler meeting. We don't have enough information here to try to address the bug as described; we are hopeful that this is actually a duplicate of one of the other A-incr-comp bugs that we *do* have enough info to close.

**Closed** 2019-05-16 15:18 UTC
Labels: A-incr-comp, A-metadata, C-bug, I-ICE, I-nominated, T-compiler

**Comment by chrissound** [comment] 2019-11-02 17:12
I just ran into this error (sorry I barely no anything about rust!) but in the event it is useful:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /build/rustc-1.32.0-src/src/libcore/slice/mod.rs:2463:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: zoneinfo_compiled::CompiledData::from_file
   8: exa::options::view::<impl exa::output::View>::deduce
   9: exa::options::Options::parse
  10: exa::main
  11: std::rt::lang_start::{{closure}}
  12: main
  13: __libc_start_main
  14: _start
czsh: abort (core dumped)  exa -l --group-directories-first --sort=extension
```

**Comment by jonas-schievink** [comment] 2019-11-02 17:19
@chrissound That looks like an issue in the `zoneinfo` crate, not the compiler

**Comment by NoCtrlZ** [comment] 2019-11-14 12:30
The same error showed up.
I started up my application server and when I accessed via Chrome browser the error showed up.
My repository is following.
I was successful in accessing via `curl` but it couldn't be accessed via browser.
https://github.com/NoCtrlZ/rust-ordinary-web-framework

**Comment by jonas-schievink** [comment] 2019-11-14 13:05
@NoCtrlZ The backtrace shows that this is an issue in your application, not in rustc. If you need help fixing the bug, feel free to post in https://users.rust-lang.org/

**Comment by NoCtrlZ** [comment] 2019-11-14 13:21
@jonas-schievink 
lol
Thank you!
