### ISSUE TITLE
Add an expect intrinsic to the stdlib.

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#22805] opened 2015-02-25 14:13 UTC
```rust
extern {
    #[link_name = "llvm.expect.i8"]
    fn expect(val: u8, expected_val: u8) -> u8;
}
```

**Comment by pnkfelix** [comment] 2015-02-25 14:53
For those not famililar with LLVM, here's the spec for what this does:
 * http://llvm.org/docs/LangRef.html#llvm-expect-intrinsic

(i.e. its a hint to LLVM that the expression passed in for `val` is likely to be the value `expected_val`.)

**Comment by dotdash** [comment] 2015-02-25 14:58
We're already using that internally, just needs to be exposed (does that need an RFC?). The relevant places are `declare_intrinsics`, `get_simple_intrinsic` and the `extern "rust-intrinsic"` block in `src/libcore/intrinsics.rs`.

**Comment by steveklabnik** [comment] 2015-02-25 14:59
> (does that need an RFC?)

The rules are very... in-flux now, but adding new public things will soon, yes. I _almost_ closed this and suggested the RFCs repo, but I'm leaving it for now since it's gray area.

**Comment by nagisa** [comment] 2015-02-28 14:04
Duplicate of https://github.com/rust-lang/rust/issues/20579. Also see https://github.com/rust-lang/rust/pull/17317

**Closed** 2015-02-28 18:29 UTC
Labels: A-libs, E-easy
