### ISSUE TITLE
extern crate foo; defined locally within function

### ISSUE THREAD

**Issue by yadaniel** [rust-lang/rust#45478] opened 2017-10-23 18:51 UTC
extern crate foo; 
within function compiles OK

however when used 
use foo::{bar};

it gives an error

  --> src\main.rs:68:9
   |
68 |     use foo::{bar};
   |         ^^^^^^^^ Maybe a missing `extern crate foo;`?

adding extern crate foo; outside of function resolves the error

Is this by design?

**Comment by steveklabnik** [comment] 2017-10-23 18:55
It's true, this is not a bug. I suggest you post to users.rust-lang.org to discuss why; we try to keep the issue tracker for bugs only, and so talking about it here creates noise.

Thank you for filing! It is expected behavior though, so I'm going to close it.

**Closed by steveklabnik** 2017-10-23 18:55 UTC
