### ISSUE TITLE
Rustc asks for Reflect, which is unstable, when it could be asking for Any which is stable

### ISSUE THREAD

**Issue by tinco** [rust-lang/rust#33807] opened 2016-05-23 08:23 UTC
Hi,

I had a latenight coding session and ran into this error:

```
src/components/mod.rs:35:69: 35:83 error: the trait `core::marker::Reflect` is not implemented for the type `T` [E0277]
src/components/mod.rs:35 	let component_list : &'static SharedMutex<T> = *component_list_any.downcast_ref().expect("Invalid type for components list");
                         	                                                                   ^~~~~~~~~~~~~~
```

Seems like an easy fix, add Reflect to the type constraint of the T, but that yields this exception:

```
src/components/mod.rs:12:5: 12:25 error: use of unstable library feature 'reflect_marker': requires RFC and more experience (see issue #27749)
src/components/mod.rs:12 use std::marker::Reflect;
                             ^~~~~~~~~~~~~~~~~~~~
```

That #27749 looks like it won't soon be solved and probably #31844 will supersede it in some way. So this advice from the compiler of adding Reflect is not very nice.

Perhaps we could have it recommend implementing Any instead? Or at least mention Any would do it as well? Most rookies won't know that Any is basically Reflect+'static.

[Here](https://users.rust-lang.org/t/downcasting-box-any-to-t-or-working-around/5935)'s my forum question about this topic with the code that threw the error.

**Comment by durka** [comment] 2016-05-26 01:27
There is supposed to be a note: https://github.com/rust-lang/rust/blob/34fd68668152530dcd1d00865fa8514461b895d7/src/libcore/marker.rs#L456-L457

But it's not triggering. It used to work on stable. cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment] 2016-05-26 07:45
@durka: @arielb1 removed my implementation. I'll try to fix this case.

**Comment by GuillaumeGomez** [comment] 2016-06-03 22:58
@tinco: Do you have a shorter code sample by any chance?

**Comment by jonas-schievink** [comment] 2016-06-23 17:53
Reproduction:
```rust
use std::any::Any;

fn log<T>(value: &T) {
    let value_any = value as &Any;

    // try to convert our value to a String.  If successful, we want to
    // output the String's length as well as its value.  If not, it's a
    // different type: just print it out unadorned.
    match value_any.downcast_ref::<String>() {
        Some(as_string) => {
        }
        None => {
        }
    }
}

fn main() {}
```

```
<anon>:4:21: 4:26 error: the trait bound `T: std::marker::Reflect` is not satisfied [E0277]
<anon>:4     let value_any = value as &Any;
                             ^~~~~
<anon>:4:21: 4:26 help: see the detailed explanation for E0277
<anon>:4:21: 4:26 help: consider adding a `where T: std::marker::Reflect` bound
<anon>:4:21: 4:26 note: required for the cast to the object type `std::any::Any + 'static`
error: aborting due to previous error
```

Looks like it *does* mention `Any`.

**Comment by GuillaumeGomez** [comment] 2016-06-23 18:14
That's what I got as well so I concluded it wasn't what he did. But maybe this is already solved in nightly?

**Comment by durka** [comment] 2016-06-27 18:01
It _mentions_ `Any` but the help says to add a `T: Reflect` bound which is unstable and the subject of this issue. There's a `rustc_on_unimplemented` note about it that isn't getting printed (see my source link above).

**Comment by durka** [comment] 2016-06-27 18:06
This was tagged **regression-from-stable-to-beta** but that was a cycle ago so it is now a **regression-from-stable-to-stable** (albeit a quite minor one).

rustc 1.8.0 prints this in response to @jonas-schievink's code:

```
foo.rs:4:21: 4:26 error: the trait `core::marker::Reflect` is not implemented for the type `T` [E0277]
foo.rs:4     let value_any = value as &Any;
                             ^~~~~
foo.rs:4:21: 4:26 help: run `rustc --explain E0277` to see a detailed explanation
foo.rs:4:21: 4:26 note: `T` does not implement `Any`; ensure all type parameters are bounded by `Any`
foo.rs:4:21: 4:26 note: required for the cast to the object type `core::any::Any + 'static`
error: aborting due to previous error
```

The fifth line (first note) is not printed by 1.9.0 or later versions.

**Comment by GuillaumeGomez** [comment] 2016-06-27 20:36
@durka: I updated the tag.

**Comment by nrc** [comment] 2016-08-18 05:52
@rust-lang/compiler and/or @durka is this likely to get fixed or should we give up on this? Does seem a shame to live with this regression, but given that it's been on stable for a while (and Reflect will probably disappear anyway) perhaps it is not worth fixing?

**Comment by eddyb** [comment] 2016-08-18 06:02
@nrc It's good idea to track the underlying diagnostics regression (@jonathandturner may be interested).

**Comment by durka** [comment] 2016-08-18 16:11
`Reflect` is going to disappear but there is some underlying problem here with the `#[rustc_on_unimplemented]` getting dropped on the floor.

**Comment by nikomatsakis** [comment] 2016-08-18 20:10
Do we have any code that actually reproduces the problem?

**Comment by arielb1** [comment] 2016-08-18 20:10
current error message:
```
error[E0277]: the trait bound `T: std::marker::Reflect` is not satisfied
 --> <anon>:6:21
  |
6 |     let value_any = value as &Any;
  |                     ^^^^^
  |
  = help: consider adding a `where T: std::marker::Reflect` bound
  = note: required because of the requirements on the impl of `std::any::Any` for `T`
  = note: required for the cast to the object type `std::any::Any + 'static`
```

**Comment by nikomatsakis** [comment] 2016-08-18 20:11
Conclusion for @rust-lang/compiler meeting: current behavior *appears* to be correct, so we *believe* problem is fixed, can call this I-needs-test.

**Comment by nikomatsakis** [comment] 2016-08-18 20:11
triage: P-low

**Comment by nikomatsakis** [comment] 2016-08-18 20:13
Actually, this was misunderstood. The problem is that at some point we decided (perhaps incorrectly) that this kind of message we see now is higher priority that `#[rustc_on_unimplemented]` messages, and that is why we do not see the custom message anymore. I am not convinced this is correct, but it *was* deliberate.

**Comment by durka** [comment] 2016-08-18 20:26
OK, that's weird to me (why not print both), but if it was deliberate then this can be closed.

**Comment by brson** [comment] 2016-09-13 16:16
Closing per previous comments.

**Closed by brson** 2016-09-13 16:16 UTC
Labels: A-diagnostics, E-needstest, regression-from-stable-to-stable, T-compiler
