### ISSUE TITLE
Second panicking custom derive has bad span

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#36935] opened 2016-10-03 17:56 UTC
Inlined from https://github.com/rust-lang/rust/issues/35900#issuecomment-246127402

---

Another issue. If a struct has two different custom derives on it and the second one panics, the error span will point to the first one, not the one which panicked.

Reproduction Script

**Comment by alexcrichton** [comment] 2016-10-03 17:57
@sgrif was "Reproduction Script" supposed to be a link? I'm spinning this off from https://github.com/rust-lang/rust/issues/35900#issuecomment-246127402 as I don't think it's going to block stabilization and/or closing that issue.

**Comment by sgrif** [comment] 2016-10-03 22:08
Reproduction script there is a summary tag

**Comment by sgrif** [comment] 2016-10-03 22:08
<details>
<summary>Reproduction Script</summary>
In a crate called `demo_plugin`
```rust
#![feature(rustc_macro, rustc_macro_lib)]

extern crate rustc_macro;

use rustc_macro::TokenStream;

#[rustc_macro_derive(Foo)]
pub fn derive_foo(input: TokenStream) -> TokenStream {
    input
}

#[rustc_macro_derive(Bar)]
pub fn derive_bar(input: TokenStream) -> TokenStream {
    panic!("lolnope");
}
```

In another crate

```rust
#![feature(rustc_macro)]

#[macro_use] extern crate demo_plugin;

#[derive(Foo, Bar)]
struct Baz {
    a: i32,
    b: i32,
}
```

The error will highlight `Foo` even though `Bar` panicked.
</details>

**Comment by keeperofdakeys** [comment] 2016-11-08 09:06
This seems to be fixed now, so this issue can be closed.

**Comment by keeperofdakeys** [comment] 2016-11-16 08:55
I ran this as a test, and got the following output:

```
   Compiling b v0.1.0 (file:///tmp/b)
error: custom derive attribute panicked
 --> src/lib.rs:5:15
  |
5 | #[derive(Foo, Bar)]
  |               ^^^
  |
  = help: message: lolnope

error: Could not compile `b`.
```

**Closed** 2017-01-10 16:36 UTC
Labels: E-needstest
