### ISSUE TITLE
hashconsing-0.3.0 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43669] opened 2017-08-05 13:06 UTC
[hashconsing](https://crates.io/crates/hashconsing) version 0.3.0 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/hashconsing-0.3.0/log.txt)):

```
Aug 03 05:13:21.041 INFO blam! |============================|
Aug 03 05:13:21.041 INFO blam! |
Aug 03 05:13:21.041 INFO blam! | Synced
Aug 03 05:13:21.041 INFO blam! |
Aug 03 05:13:21.041 INFO blam! | Running with 4 threads
Aug 03 05:13:21.041 INFO blam! |
Aug 03 05:13:21.041 INFO blam! | 0 | [ 5] app = v3.v0
Aug 03 05:13:21.041 INFO blam! | Thread 1 is done.
Aug 03 05:13:21.041 INFO blam! | 0 | [ 6] app = (v3).v3.v0
Aug 03 05:13:21.041 INFO blam! | Thread 2 is done.
Aug 03 05:13:21.041 INFO blam! | 0 | [ 7] app = (v3).(v3).v3.v0
Aug 03 05:13:21.041 INFO blam! | Thread 4 is done.
Aug 03 05:13:21.041 INFO blam! | 0 | [ 8] app = (v3).v0.(v3).(v3).v3.v0
Aug 03 05:13:21.041 INFO blam! | Thread 3 is done.
Aug 03 05:13:21.041 INFO blam! thread 'synced' panicked at 'assertion failed: `(left == right)`
Aug 03 05:13:21.041 INFO blam!   left: `8`,
Aug 03 05:13:21.041 INFO blam!  right: `7`', src/main.rs:250:4
Aug 03 05:13:21.041 INFO blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
cc @AdrienChampion

**Comment by arielb1** [comment] 2017-08-05 13:29
#42541: the format of `assert_eq` messages changed. I don't think this is something we are going to guarantee stability on, or revert.

**Comment by AdrienChampion** [comment] 2017-08-05 17:59
The hashconsing crate actually had some serious problems before 0.4.0, I strongly suggest you update to the latest version.

**Comment by alexcrichton** [comment] 2017-08-22 21:21
Closing as likely a spurious failure due to @AdrienChampion's comment

**Closed by alexcrichton** 2017-08-22 21:21 UTC
Labels: C-bug, I-nominated, regression-from-stable-to-beta, T-libs

**Comment by AdrienChampion** [comment] 2017-09-14 05:48
I replied too fast, sorry.

The failure is spurious indeed, in the sense that this version of hashconsing is buggy.

For future reference, the problem is that it was using hash for hashconsed term equality, which makes no sense. The failure comes from a hash collision causing two different terms to be equal.
