### ISSUE TITLE
Spurious `unsized` error on resolution error

### ISSUE THREAD

**Issue by oli-cosmian** [rust-lang/rust#64088] opened 2019-09-02 09:34 UTC
the `bar` function does not exist, so its return type is implicitly inferred to be whatever type is consumed further down. If the inferred type is unsized, we may get additional errors though. I think we should find a way to silence that additional error.

```rust
fn foo() {
    let x = bar();
    meh(&x);
}

fn meh(_: &[i32]) {}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b0253a3a06201f009084e401adae036))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0425]: cannot find function `bar` in this scope
 --> src/lib.rs:2:13
  |
2 |     let x = bar();
  |             ^^^ not found in this scope

error[E0277]: the size for values of type `[i32]` cannot be known at compilation time
 --> src/lib.rs:2:9
  |
2 |     let x = bar();
  |         ^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `[i32]`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: all local variables must have a statically known size
  = help: unsized locals are gated as an unstable feature

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0425.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by Mark-Simulacrum** [comment] 2019-09-15 13:53
Closing as duplicate of https://github.com/rust-lang/rust/issues/33575.

**Closed by Mark-Simulacrum** 2019-09-15 13:53 UTC
Labels: A-diagnostics, T-compiler
