### ISSUE TITLE
Implement AsRef<Path> for Arc<PathBuf>

### ISSUE THREAD

**Issue by vitiral** [rust-lang/rust#58469] opened 2019-02-14 19:31 UTC
Possibly also implement `Borrow` and `Deref`.

I would like to use `Arc<PathBuf>` to be the equivalent of `PathBuf` for traits in my library, `path_abs`.

However, I get errors like this:

```
751 | impl PathMut for Arc<PathBuf> {
    |      ^^^^^^^ the trait `std::convert::AsRef<std::path::Path>` is not implemented for `alloc::sync::Arc<std::path::PathBuf>`
    |
    = help: the following implementations were found:
              <alloc::sync::Arc<T> as std::convert::AsRef<T>>
    = note: required because of the requirements on the impl of `PathInfo` for `alloc::sync::Arc<std::path::PathBuf>`
```

**Comment by abonander** [comment] 2019-02-15 03:26
You can also get `Arc<Path>` via `.into()` on `&Path` or `PathBuf`.

**Comment by vitiral** [comment] 2019-02-15 05:10
Of course, but that doesn't let you generalize for trait bounds in a library.

**Comment by JanBeh** [comment] 2022-07-20 17:01
Would be solved by #45742 (which is difficult), so maybe this can be closed?

**Comment by Enselic** [comment] 2024-04-07 08:38
Triage: There were no objections to close as duplicate, so let's do that.

Duplicate of #45742

**Closed by Enselic** 2024-04-07 08:38 UTC
Labels: T-libs-api
