### ISSUE TITLE
Varargs extern functions are Copy but not Clone

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#34874] opened 2016-07-17 00:40 UTC
Varargs extern functions are `Copy` but not `Clone`.  This causes problems when trying to use bindgen on a C header file that contains stucts that contain extern function pointers.

**Comment by nagisa** [comment] 2016-07-17 01:18
Duplicate of https://github.com/rust-lang/rust/issues/28229.

**Closed** 2016-07-19 06:20 UTC
