### ISSUE TITLE
casting negative number to usize crashes program without backtrace in debug mode

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#53739] opened 2018-08-27 16:48 UTC
I stumbled upon this while working on my [cargo cache](https://github.com/matthiaskrgr/cargo-cache) crate.
````rustc 1.30.0-nightly (721913067 2018-08-26)````
Essentially I cast a negative ````int```` to ````usize```` and pass it to ````String.repeat()```` but there is no compiler warning and no backtrace when crashing, even in debug mode.

````rust
fn pad_strings(indent_lvl: i8, beginning: &str) -> String {
    const MAX_WIDTH: i8 = 37;
    let len_padding: i8 = (MAX_WIDTH + indent_lvl * 2) - (beginning.len() as i8);
    println!("padding: {}", len_padding);
    let mut formatted_line = beginning.to_string();
    // here we cast a negative value to usize
    formatted_line.push_str(&String::from(" ").repeat(len_padding as usize));
    formatted_line
}

fn main() {
        pad_strings(2, "Size of 1938493989 crate source checkouts: ").to_string();
}
````
when running:
````
   Compiling cargo-cache v0.1.0 (file:///home/matthias/vcs/github/cargo-cache)
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/cargo-cache`
padding: -2
memory allocation of 18446744073709551614 bytes failed[1]    18030 abort (core dumped)  cargo --color=always run
````

Debugging this would have been MUCH easier with a proper backtrace :)

**Comment by matthiaskrgr** [comment] 2018-08-27 17:01
Much simpler example:
````rust
fn main() {
    let x = -2;
    let _a =  String::new().push_str(&String::from(" ").repeat(x as usize));
}
````

**Comment by matthiaskrgr** [comment] 2018-08-27 17:04
Crashes on nightly, beta and stable:
````
   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.28.0 (9634041f0 2018-07-30)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.29.0-beta.7 (49720ea9c 2018-08-26)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.30.0-nightly (721913067 2018-08-26)
````

**Comment by jonas-schievink** [comment] 2018-08-27 17:32
Even simpler, you just need the `repeat`:

```rust
fn main() {
    " ".repeat((-2i8) as usize);
}
```

Isn't this just what happens when an allocation is too large, though? `vec![0u8; (-2i8) as usize];` does the same thing.

**Comment by nagisa** [comment] 2018-08-28 11:51
Yeah, seems to be working as intended (`str::repeat` returns a `String`). Closing.

Complain if you feel otherwise and I’ll reopen.

**Closed by nagisa** 2018-08-28 11:51 UTC

**Comment by matthiaskrgr** [comment] 2018-08-28 12:01
@nagisa  is there no way to display a backtrace in this case?
Trying to find the underlying issue in a program of a couple thousand lines is not that easy if you don't know what to look for.

**Comment by nagisa** [comment] 2018-08-28 12:28
You can obtain a backtrace with a debugger of your choice. OOM errors are not panics for a good reason. That might change in a future as support for handing OOM gets added/stabilised.

**Comment by matthiaskrgr** [comment] 2018-08-28 12:36
Alright, thanks for the clarification :+1:
