### ISSUE TITLE
ICE on mismatched trait impl types on nightly

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#35952] opened 2016-08-23 21:45 UTC
https://is.gd/IOhgyC

```rust
struct S;

trait Trait {
    fn bar(f: fn() -> &'static u8);
}

impl Trait for S {
    fn bar(_: fn() -> u8) {}
}

fn main() {}
```

```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x7fe5cd00bde9 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fe5cd01c4dc - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fe5cd01a7e7 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fe5cd01aff8 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fe5cd01ae92 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fe5cd01adc0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fe5cd01ad41 - rust_begin_unwind
   8:     0x7fe5cd08640f - core::panicking::panic_fmt::hc5789f4e80194729
   9:     0x7fe5cd08633b - core::panicking::panic::h1953378f4b37b561
  10:     0x7fe5cb7270dc - rustc_typeck::check::compare_method::compare_impl_method::_{{closure}}::h08bef90d287aed42
  11:     0x7fe5cb6830f9 - rustc_typeck::check::compare_method::compare_impl_method::he3538453c2efe177
  12:     0x7fe5cb698082 - rustc_typeck::check::check_impl_items_against_trait::hb105ca8bb42a0b3d
  13:     0x7fe5cb695602 - rustc_typeck::check::check_item_type::hba3733559d49be1e
  14:     0x7fe5cb68de4b - _<rustc_typeck..check..CheckItemTypesVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'tcx>>::visit_item::h369cacffbaa18923
  15:     0x7fe5cb68fd4b - rustc_typeck::check::check_item_types::h81e44a5d40f450fd
  16:     0x7fe5cb7074c3 - rustc_typeck::check_crate::h8ec8b2f490f5dc28
  17:     0x7fe5cd3fbb03 - rustc_driver::driver::phase_3_run_analysis_passes::_{{closure}}::h45e03cee16dcf298
  18:     0x7fe5cd3c8546 - rustc_driver::driver::phase_3_run_analysis_passes::hc0de40cea97d81a1
  19:     0x7fe5cd3b4f02 - rustc_driver::driver::compile_input::hd9ecc57abd3cba85
  20:     0x7fe5cd3e7756 - rustc_driver::run_compiler::h184264500271cc39
  21:     0x7fe5cd32d8c2 - std::panicking::try::do_call::h17a7a17ad7240c5c
  22:     0x7fe5cd02a846 - __rust_maybe_catch_panic
  23:     0x7fe5cd34726a - _<F as alloc..boxed..FnBox<A>>::call_box::h93f9128277b2964a
  24:     0x7fe5cd018bb2 - std::sys::thread::Thread::new::thread_start::he0bf102845911132
  25:     0x7fe5c5358453 - start_thread
  26:     0x7fe5ccc687de - __GI___clone
  27:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace
```

Happens on the current nightly, but not the beta/stable rustc installed on the playpen.

**Comment by KiChjang** [comment] 2016-08-24 00:27
Duplicate of #35869.

**Closed** 2016-08-24 06:05 UTC
