### ISSUE TITLE
Add a toc to each std lib generated pages

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust#28056] opened 2015-08-28 01:39 UTC
Long pages such as in [regex](http://doc.rust-lang.org/regex/regex/index.html) have many examples but it's difficult to know at a glance what the documentation contains without scanning the entire document. Having a table of contents would help a lot with this.

Here is a list of links to different TOC styles from various places for ways it could be done:
- [Python 2.7](https://docs.python.org/2/tutorial/introduction.html) has one in the sidebar. Stays with you as you scroll.
- [Python 3.5](https://docs.python.org/3.5/tutorial/introduction.html) seems to be slightly cleaner but similar. Doesn't stay with you.
- [mozilla javascript docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions): is nicely in the sidebar. Follows you down the page (requires the window to be wide enough).
- [wikipedia](https://en.wikipedia.org/wiki/Cat): in the middle of the page. Doesn't scroll with you. 
- [gitbook](http://rustbyexample.com/): stays with you. provides scrolling.
- [perl](http://perldoc.perl.org/perl.html): looks like it's formatted like a man page.

I looked for some more but didn't find other good examples.

Of these, I like the mozilla, python 2, and gitbook TOCs best with the mozilla probably the best among them (probably because it's small and clean). However, I think the gitbook style is probably the most appropriate fit to the std libs style.

I've also provided a mockups of what a TOC could look like in that style which is similar to a [different thread](https://internals.rust-lang.org/t/rustdoc-mockup-for-including-more-structured-content/2540). Clearly, something would need to be done with the current sidebar to use this format.

Mockup:

![toc](https://cloud.githubusercontent.com/assets/4156987/9537217/e8e5fac2-4d03-11e5-9015-64ca37e752f1.png)

**Comment by steveklabnik** [comment] 2016-11-15 20:46
Triage: no change.

**Comment by steveklabnik** [comment] 2018-09-24 16:03
Triage: no changes. @rust-lang/rustdoc is this a feature we're interested in pursuing?

**Comment by GuillaumeGomez** [comment] 2018-09-24 19:21
This would be very nice to have but I currently don't know how we could do it... The problem is that our pages are already very loaded and that'd add even more content to be able to go through content. Also, not sure the information would be more accessible like this. It'd force to have a very clean documentation through meaningful titles.

**Comment by jyn514** [comment] 2021-07-02 10:45
Duplicate of https://github.com/rust-lang/rust/issues/14475

**Closed by jyn514** 2021-07-02 10:45 UTC
Labels: C-enhancement, T-dev-tools, T-rustdoc
