### ISSUE TITLE
x86_64-gnu-aux/x86_64-msvc-cargo: xsv test appears to fail spuriously

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#98068] opened 2022-06-13 20:21 UTC
Instances of this occurring:

https://github.com/rust-lang/rust/pull/95542#issuecomment-1120237681
https://github.com/rust-lang/rust/pull/95897#issuecomment-1153206866
https://github.com/rust-lang/rust/pull/94272#issuecomment-1060116375
https://github.com/rust-lang/rust/pull/92589#issuecomment-1006363237

Not sure if a xsv problem or bors problem, but here goes: cc @BurntSushi.

(NB: it appears that we're pulling in a master of `xsv` because the commit we had locked on has disappeared...)

**Comment by ehuss** [comment] 2022-06-13 21:40
See also #73514.

**Comment by RalfJung** [comment] 2022-07-22 13:02
Duplicate of https://github.com/rust-lang/rust/issues/73514

**Closed by RalfJung** 2022-07-22 13:02 UTC
Labels: A-testsuite
