### ISSUE TITLE
Invalid "help: try adding a return type" message

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#48554] opened 2018-02-26 20:16 UTC
While investigating a Deref coercion issue:
```rust
struct S;
struct T;

impl std::ops::Deref for S {
    type Target = T;
    fn deref(&self) -> &T {
        &T
    }
}

fn a(_: &T) {}

fn b() {
    a(&{let x = S; x});
}
```

```
error[E0308]: mismatched types
  --> src/main.rs:14:20
   |
13 | fn b() {
   |        - help: try adding a return type: `-> S`
14 |     a(&{let x = S; x});
   |                    ^ expected struct `T`, found struct `S`
   |
   = note: expected type `T`
              found type `S`
```
Appeared in Rust 1.20.0

**Comment by Badel2** [comment] 2018-02-28 00:44
It looks like the problem is using `{}` inside the function call (why would anyone do that?). Also in the main() function it complains about the return type:

```rust
struct A;
struct B;
fn a(_: A) {}
fn main() {
    a({B});
}
```

```
  |
4 | fn main() {
  |           - expected `()` because of default return type
5 |     a({B});
  |        ^ expected struct `A`, found struct `B`
  |
  = note: expected type `A`
             found type `B`
```

**Comment by skinny121** [comment] 2018-03-04 05:59
Can I pick up this one, If no one else is working on it?

**Comment by skinny121** [comment] 2018-03-04 08:47
This seems to not only happen in function calls.
```rust
struct A;

fn bar() {
    let a:A = {
        2
    };
}
```
Produces
```
4 | fn bar() {
  |          - possibly return type missing here?
5 |     let a:A = {
6 |         2
  |         ^ expected struct `A`, found integral variable
  |
  = note: expected type `A`
             found type `{integer}`
```

After digging into the rustc `FnCtxt.suggest_mismatched_types_on_tail` assumes the type error is related to the function return type if the tail expression isn't in a loop. Firstly a solution to the original bug would be to also check if it's inside a function call. But this wouldn't fix the situation above, which would require the fact that a tail expression returns from the function to be propagated down the syntax tree.

**Comment by estebank** [comment] 2019-03-26 00:03
This has been fixed in the current stable.

**Closed by estebank** 2019-03-26 00:03 UTC
Labels: A-diagnostics, A-typesystem, C-bug, T-compiler
