### ISSUE TITLE
#[derive(Default)] fails when type parameters do not implement Default

### ISSUE THREAD

**Issue by nwn** [rust-lang/rust#74462] opened 2020-07-17 21:18 UTC
The `derive(Default)` macro fails when applied to a type with a non-`Default` type parameter.

I tried this code: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ce408b26f83b822e7bbba18f26ca2840))

```rust
use core::marker::PhantomData;

struct NoDefault;

#[derive(Default)]
struct X<T> {
    phantom: PhantomData<T>,
}

fn main() {
    let _: X<NoDefault> = Default::default();
}
```

I expected this to compile with `Default` being implemented using `PhantomData`'s `Default` implementation.

Instead, the following error was produced:
```
error[E0277]: the trait bound `NoDefault: std::default::Default` is not satisfied
  --> src/main.rs:11:27
   |
11 |     let _: X<NoDefault> = Default::default();
   |                           ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `NoDefault`
   |
   = note: required because of the requirements on the impl of `std::default::Default` for `X<NoDefault>`
   = note: required by `std::default::Default::default`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

The same problem occurs when any field of the type implements `Default`, but is parameterized by a type that doesn't. For example, the following produces the same error: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=de5f9dff3077be1bbd658ca6a1cb7e45))
``` rust
struct NoDefault;

#[derive(Default)]
struct X<T> {
    option: Option<T>,
}

fn main() {
    let _: X<NoDefault> = Default::default();
}
```

This can be worked around by manually implementing `Default` for the type: ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4f4df482445f7116b17ce4f7920ea814))
``` rust
struct NoDefault;

struct X<T> {
    option: Option<T>,
}

impl<T> Default for X<T> {
    fn default() -> Self {
        Self {
            option: Default::default(),
        }
    }
}

fn main() {
    let _: X<NoDefault> = Default::default();
}
```

While this may be intentional, the [documentation](https://doc.rust-lang.org/stable/std/default/trait.Default.html#derivable) suggests that it should work since the fields themselves all implement `Default`.

### Meta
The code above was tested on the stable (1.45.0), beta (1.46.0-beta.1), and nightly (1.46.0-nightly) channels available on the Rust Playground, with the same results.

**Comment by jonas-schievink** [comment] 2020-07-17 21:26
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2020-07-17 21:26 UTC
Labels: C-bug
