### ISSUE TITLE
Non-literal arguments to `unreachable!()` are rejected starting with v1.59.0

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/rust#94475] opened 2022-03-01 05:44 UTC
### Code

I tried this code:

```rust
fn main() {
    let blah = "foobar";
    unreachable!(format!("{}", blah));
}
```

In 2021 edition.

On 1.58.1 this compiles, but on 1.59.0 and later it fails to build:

```
error: format argument must be a string literal
 --> src/main.rs:3:18
  |
3 |     unreachable!(format!("{}", blah));
  |                  ^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you might be missing a string literal to format with
  |
3 |     unreachable!("{}", format!("{}", blah));
  |                  +++++

error: could not compile `format-test` due to previous error
```

### Version it worked on

It most recently worked on: 1.58.1

### Version with regression

[1.59.0 stable on Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a7af35253e6777e7ae6efadeedc40548), as well as the following nightly version:

```
rustc 1.61.0-nightly (4ce374923 2022-02-28)
binary: rustc
commit-hash: 4ce3749235fc31d15ebd444b038a9877e8c700d7
commit-date: 2022-02-28
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

**Comment by PatchMixolydic** [comment] 2022-03-01 07:33
This appears to have been an intentional bugfix to bring `unreachable!` in line with other panic macros. See also #92137, the original report of this macro exhibiting Rust 2015-like behaviour in Rust 2021.

**Comment by camelid** [comment] 2022-03-03 20:08
Closing this issue as intended behavior.

**Closed by camelid** 2022-03-03 20:08 UTC
Labels: T-compiler, regression-from-stable-to-stable, C-bug, I-prioritize
