### ISSUE TITLE
error: internal compiler error: /rustc/ab654863c3d50482f260cf862647f1fe0ff5e010/compiler/rustc_infer/src/infer/outlives/env.rs:145:26: add_outlives_bounds: unexpected regions

### ISSUE THREAD

**Issue by justice-asare** [rust-lang/rust#109227] opened 2023-03-16 17:16 UTC
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by lqd** [comment] 2023-03-16 17:23
While this issue is a little light on details, I'm 100% sure this is a duplicate of https://github.com/rust-lang/rust/issues/109199 so I'll close it as such. This has already been fixed on master, but too late to appear in today's nightly. The fix will be available in tomorrow's nightly though.

Thanks for opening an issue!

**Closed by lqd** 2023-03-16 17:23 UTC
Labels: I-ICE, T-compiler, C-bug
