### ISSUE TITLE
Does not fail on multiple methods definition

### ISSUE THREAD

**Issue by rom1v** [rust-lang/rust#58942] opened 2019-03-05 15:40 UTC
This obviously fails to compile:
```rust
struct X;
impl X { 
   fn f(&self) {}
}
impl X {
   fn f(&self) {}
}
```
```
error[E0592]: duplicate definitions with name `f`
 --> a.rs:3:4
  |
3 |    fn f(&self) {}
  |    ^^^^^^^^^^^^^^ duplicate definitions for `f`
...
6 |    fn f(&self) {}
  |    -------------- other definition for `f`
```

But this does not:
```rust
struct X;
impl X {
   fn f(&self) {}
}
macro_rules! do_impl {
    ($name: ident) => {
        impl $name {
            fn f(&self) {}
        }
    }
}
do_impl!(X);
```
unless you use it:
```rust
fn main() {
    X.f()
}
```
```
error[E0034]: multiple applicable items in scope
  --> a.rs:14:7
   |
14 |     X.f()
   |       ^ multiple `f` found
   |
note: candidate #1 is defined in an impl for the type `X`
  --> a.rs:3:4
   |
3  |    fn f(&self) {}
   |    ^^^^^^^^^^^
note: candidate #2 is defined in an impl for the type `X`
  --> a.rs:8:13
   |
8  |             fn f(&self) {}
   |             ^^^^^^^^^^^
...
12 | do_impl!(X);
   | ------------ in this macro invocation
```

I think it should fail even when we don't use the duplicate function.

**Comment by Centril** [comment] 2019-03-05 16:49
cc @petrochenkov 

This compiles all the way back to 1.0.0 (tested with godbolt).

**Comment by petrochenkov** [comment] 2019-03-05 17:02
Ugh, `fn check_for_common_items_in_impls` compares `Ident`s (which are not equal if they come from different macros).

I would actually check the intermediate versions of Rust between 1.0 and 1.33, IIRC this error should be impossible in some version range due to how identifiers worked back then.

Slightly more minimized reproduction:
```rust
struct X;

impl X {
   fn f() {}
}

macro_rules! do_impl { () => {
    impl X {
       fn f() {}
    }
}}
do_impl!();

fn main() {}
```

**Comment by petrochenkov** [comment] 2019-03-05 20:14
Fixed in https://github.com/rust-lang/rust/pull/58948

**Comment by petrochenkov** [comment] 2019-03-05 20:20
The regression was introduced in Rust 1.29, the error was reported before that.
(This case *became* an error in Rust 1.18 after a long deprecation lint period.)

**Closed** 2019-03-21 23:42 UTC
Labels: C-bug, T-compiler, regression-from-stable-to-stable
