### ISSUE TITLE
The compiler sets bad krate span for plugins

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#23964] opened 2015-04-02 02:35 UTC
``` rust
// bad_plugin_span.rs
#![crate_type="dylib"]
#![feature(plugin_registrar, rustc_private)]

extern crate rustc;

#[plugin_registrar]
pub fn plugin_registrar(reg: &mut rustc::plugin::Registry) {
    println!("{:?}", reg.krate_span);
    reg.sess.span_err(reg.krate_span, "should point to `#[plugin(...)]`");
}
```

``` rust
// bad_plugin_span_demo.rs
#![feature(plugin)]
#![plugin(bad_plugin_span)]

fn main() {}
```

```
$ rustc bad_plugin_span.rs && rustc -L . bad_plugin_span_demo.rs
Span { lo: BytePos(27), hi: BytePos(87), expn_id: ExpnId(4294967295) }
bad_plugin_span_demo.rs:2:1: 5:12 error: should point to `#[plugin(...)]`
bad_plugin_span_demo.rs:2 #![feature(plugin)]
bad_plugin_span_demo.rs:3 #![plugin(bad_plugin_span)]
bad_plugin_span_demo.rs:4 
bad_plugin_span_demo.rs:5 fn main() {}
error: aborting due to previous error
```

The `krate_span` field of the registry should be pointing to the place that introduces the plugin, i.e. the `#[plugin(...)]` but it is instead pointing to the whole file (at least, from the start of the first token to the end of the last).

**Comment by brson** [comment] 2016-12-01 17:32
Is this still reproducible?

**Comment by brson** [comment] 2016-12-01 17:33
Whatever. Closing because you're old, bug.

**Closed by brson** 2016-12-01 17:33 UTC
Labels: A-diagnostics, A-plugin, I-wrong, P-low, T-compiler
