### ISSUE TITLE
Error: internal compiler error: unexpected panic for rustc 1.50.0-nightly (6a889570e 2020-11-27)

### ISSUE THREAD

**Issue by rainliu** [rust-lang/rust#79513] opened 2020-11-28 18:13 UTC
### Code

```Rust
https://github.com/webrtc-rs/webrtc/runs/1467868517
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (6a889570e 2020-11-27)
```

### Error output

```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `DefId(0:1268 ~ ring[401c]::digest::sha2::)`,
 right: `DefId(0:1269 ~ ring[401c]::digest::sha2::::GFp_sha256_block_data_order)`', compiler/rustc_middle/src/hir/map/collector.rs:227:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (6a889570e 2020-11-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z profile -Z panic_abort_tests -C embed-bitcode=no -C debuginfo=2 -C codegen-units=1 -C opt-level=0 -C link-dead-code -C overflow-checks=off -C panic=abort -C debug-assertions=off --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [index_hir] index HIR
#1 [hir_owner] HIR owner of `{misc#0}`
end of query stack
error: could not compile `ring`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by rainliu** [comment] 2020-11-28 18:14
The same code passed for rustc 1.50.0-nightly (72da5a9d8 2020-11-26)

https://github.com/webrtc-rs/webrtc/runs/1465943689?check_suite_focus=true

**Comment by jonas-schievink** [comment] 2020-11-28 18:29
duplicate of https://github.com/rust-lang/rust/issues/79487

**Closed by jonas-schievink** 2020-11-28 18:29 UTC
Labels: C-bug, I-ICE, T-compiler
