### ISSUE TITLE
Basic coercion of String to &str is incorrect

### ISSUE THREAD

**Issue by donaldcallen** [rust-lang/rust#37223] opened 2016-10-16 20:02 UTC
I realize a new book is being written, but I just wasted a lot of time because I believed this:

Strings will coerce into &str with an &:

fn takes_slice(slice: &str) {
    println!("Got: {}", slice);
}

fn main() {
    let s = "Hello".to_string();
    takes_slice(&s);
}

This is not true (account.commodity_guid is a String):

match &(account.commodity_guid) {                                                                |obals), accountCommodityGuid=SQLNull, accountFlags=(rootFlags globals)} 0 globals  
                    "" => ()

results in

40 |                     "" => (),
   |                     ^^ expected struct `std::string::String`, found str
   |
   = note: expected type `&std::string::String`
   = note:    found type `&'static str`

match account.commodity_guid.as_str() {

fixes it.

**Comment by steveklabnik** [comment] 2016-10-16 21:11
that section was intended to talk about arguments only; Deref coercions don't kick in everywhere.

This should be clarified for sure.

**Comment by donaldcallen** [comment] 2016-10-16 22:02
Are you saying that if foo is a String, the type of the expression &foo is
an &str if used as an argument, like so

bar(&foo)

where bar expects an &str as its only argument, but not if used in match,
like so

match &foo {
"" => something
}

??????

If that's the case, then the language is broken.

**Comment by jonas-schievink** [comment] 2016-10-16 22:42
@donaldcallen [Here's](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md) the RFC specifying coercions. If `foo` has type `String`, `&foo` always has type `&String`, it's just that the compiler applies a deref-coercion when calling the function.

**Comment by donaldcallen** [comment] 2016-10-16 23:05
On Sun, Oct 16, 2016 at 6:42 PM, Jonas Schievink <notifications@github.com>
wrote:

> @donaldcallen <https://github.com/donaldcallen> Here's
> <https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md>
> the RFC specifying coercions. If foo has type String, &foo always has
> type &String,
>

That's what I would expect.


> it's just that the compiler applies a deref-coercion when calling the
> function.
>
I understand that. The problem is that "The Book" says "Strings will coerce
into &str with an &" without qualification. This is completely mis-leading.

**Comment by Mark-Simulacrum** [comment] 2017-05-14 23:59
We're no longer tracking problems with the old book, though PRs are happily taken. As such, I'm going to close this.

**Closed by Mark-Simulacrum** 2017-05-14 23:59 UTC
