### ISSUE TITLE
regression - nightly 2023-03-30 -> 2023-03-31 causes linker error when importing wasm_bindgen::JsValue in a proc_macro

### ISSUE THREAD

**Issue by finnbear** [rust-lang/rust#111888] opened 2023-05-23 22:05 UTC
#### (2023-07-19)

1. stylist-rs has been updated with a workaround, so the reproduction described below will need adapting (e.g. check out that repo from around https://github.com/futursolo/stylist-rs/commit/fbd788f0a9a63ccadf6a25e028829a25224140eb or earlier, since that will not include the workaround added in https://github.com/futursolo/stylist-rs/pull/123 )

2. This problem exhibits itself only with certain numbers of codegen-units. The default setting for codegen-units is host dependent (the default is chosen, in part, as a function of the number of cores the host has available, in order to parallelize the code-generation performed by LLVM). In my own experiments, the problem is masked (does not arise) for codegen-units={1,2,4,8}, and the problem *does* arise for codegen-units={16,32,64,128,256}. You are best off passing `-Ccodegen-units` explicit when investigating this, just to ward against that being an invisible factor in the experiments.

(bug report follows below)

### Code

I tried this code:

```toml
[package]
name = "nightly_stylist"
version = "0.1.0"
edition = "2021"

[dependencies]
stylist-macros = "0.12"
```

```rust
fn main() {}
```

[stylist-macros](https://docs.rs/stylist-macros/0.12.0/stylist_macros/)

I expected to see this happen: `cargo check` succeeds in debug mode.

Instead, this happened: `cargo check` fails in debug mode.

```console
  = note: /usr/bin/ld: __wbindgen_realloc: undefined version: 
          /usr/bin/ld: __wbindgen_malloc: undefined version: 
          /usr/bin/ld: __wbindgen_free: undefined version: 
          /usr/bin/ld: __wbindgen_exn_store: undefined version: 
          /usr/bin/ld: failed to set dynamic section sizes: bad value
          collect2: error: ld returned 1 exit status
```

### Version it worked on

```
rustc 1.70.0-nightly (ec2f40c6b 2023-03-30)
binary: rustc
commit-hash: ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b
commit-date: 2023-03-30
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Version with regression

```
rustc 1.70.0-nightly (5e1d3299a 2023-03-31)
binary: rustc
commit-hash: 5e1d3299a290026b85787bc9c7e72bcc53ac283f
commit-date: 2023-03-31
host: x86_64-unknown-linux-gnu
release: 1.70.0-nightly
LLVM version: 16.0.0
```

### Cargo bisect-rustc

```
searched toolchains ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b through 5e1d3299a290026b85787bc9c7e72bcc53ac283f


********************************************************************************
Regression in 22a7a19f9333bc1fcba97ce444a3515cb5fb33e6
********************************************************************************
```
*isn't immediately obvious why [this change](https://github.com/rust-lang/rust/commit/22a7a19f9333bc1fcba97ce444a3515cb5fb33e6) would cause the problem

searched nightlies: from nightly-2023-03-27 to nightly-2023-04-02
regressed nightly: nightly-2023-04-01
searched commit range: https://github.com/rust-lang/rust/compare/ec2f40c6b04f0e9850dd1f454e8639d319f4ed9b...5e1d3299a290026b85787bc9c7e72bcc53ac283f
regressed commit: https://github.com/rust-lang/rust/commit/22a7a19f9333bc1fcba97ce444a3515cb5fb33e6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-03-27 --end 2023-04-02 
```
</details>

**Comment by finnbear** [comment] 2023-05-24 04:40
I forked `stylist` and minimized the reproducible example down to simply importing `wasm_bindgen::JsValue` in a `proc_macro` crate.

You can find it here: https://github.com/finnbear/stylist-rs/tree/rustc (just run `cargo check` in `packages/stylist`)

**Comment by apiraino** [comment] 2023-05-24 09:25
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23111888.20regression.20-.20nightly.202023-03-30.20-.3E.202023-03-31.20cause.E2.80.A6)).

@rustbot label -I-prioritize +P-high +T-compiler

**Comment by lqd** [comment] 2023-05-29 13:14
TBH it's not clear to me how alignment checks would end up causing linker errors, but since this seems bisected to #98112, let's at the very least notify the PR's author @saethlin.

**Comment by saethlin** [comment] 2023-05-29 13:36
I already looked over this and was also mystified. I suppose I could take another look? I know almost completely nothing about wasm so I'm not hopeful.

**Comment by saethlin** [comment] 2023-05-29 18:38
Builds fine:
```
RUSTFLAGS=-Zmir-enable-passes=-CheckAlignment cargo +nightly build
```
Same linker error:
```
RUSTFLAGS=-Zmir-enable-passes=-CheckAlignment cargo +nightly build -Zbuild-std --target=x86_64-unknown-linux-gnu
```

As a mitigation for the linker error, users may put this in their Cargo.toml (for the workspace!)
```
[profile.dev.package.wasm-bindgen]
debug-assertions = false
```
That only helps with the alignment checks, `-Zbuild-std` is still not going to work.

**Comment by saethlin** [comment] 2023-05-29 18:47
I can build the reproducer, unmodified, if I use LLD.
```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
```
Or
```
RUSTFLAGS="-Clinker=clang -Clink-arg=-fuse-ld=lld" cargo +nightly build
```

**Comment by saethlin** [comment] 2023-06-10 14:41
@JohnTheCoolingFan reported this same linker error from `tealr_derive`. It can be reproduced by creating an empty Cargo project, then running `cargo add tealr_derive@0.9.0-alpha4 --features=embed_compiler_from_download` then `cargo build`. I have not managed to minimize this reproducer.

The errant symbol is `bz_internal_error` which is defined as:
```rust
#[no_mangle]
pub fn bz_internal_error(errcode: c_int) {
    panic!("bz internal error: {}", errcode);
}
```
This has the same sort of shape as the non-unwinding panics from the alignment checks and from the standard library UB-detecting assertions.

searched nightlies: from nightly-2023-01-01 to nightly-2023-06-09
regressed nightly: nightly-2023-03-12
searched commit range: https://github.com/rust-lang/rust/compare/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13...8a73f50d875840b8077b8ec080fa41881d7ce40d
regressed commit: https://github.com/rust-lang/rust/commit/e350fe4e608b653da47e8012d13ef701613e717b

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-01-01 --end 2023-06-09 --script script --regress=error 
```
</details>

So this bisects to a rollup then can't find the unrolled perf builds. Manual trials identifies https://github.com/rust-lang/rust/pull/108017 as the source of the regression.

**Comment by kurtbuilds** [comment] 2023-07-10 22:21
Wanted to add, that I also ran into this issue. For me, it also occurred while compiling a macro crate. I originally thought it was an issue with `libc`, as it happened after I ran a `cargo update`, and the issue was fixed by pinning `libc` to a slightly older version: https://github.com/rust-lang/libc/issues/3297

There was a bunch of weird behavior I encountered when trying to uncover the issue. The `libc` issue was one. When I made other library upgrade changes, it would cause or fix the breakage.

I didn't dive too deeply, but it *seems* like I was still encountering this issue even when I set the compiler to 1.67. (See this Github Actions build and associated commit: https://github.com/kurtbuilds/oasgen/actions/runs/5513164141 ) So it's possible that going to an old version simply *hid* the issue, but didn't actually pinpoint where the issue was introduced.

Let me know if there's any other information I can provide to help isolate the issue.

**Comment by pnkfelix** [comment] 2023-07-19 17:33
One MCVE for the stylist-macros build issue looks like this: Just a stylist-macros crate, with this `Cargo.toml` and `lib.rs`:

```toml
# Cargo.toml
[package]
name = "mcve-stylist"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
wasm-bindgen = "0.2.83"
```

```rust
// lib.rs
extern crate wasm_bindgen;
```

So now I'm switching gears to see if I reduce wasm_bindgen to something smaller, so that we can have a small set of crates to talk about on their own here.

**Comment by pnkfelix** [comment] 2023-07-20 15:21
Okay got a pretty impressively tiny MCVE for wasm-bindgen too:

```toml
[package]
name = "wasm-bindgen"
version = "0.2.87"
```

```rust
![no_std]

#[no_mangle]
pub extern "C" fn __wbindgen_malloc(_size: usize, _align: usize) -> *mut u8 {
    loop {}
}

#[no_mangle]
pub unsafe extern "C" fn __wbindgen_realloc(
    _ptr: *mut u8,
    _old_size: usize,
    _new_size: usize,
    _align: usize,
) -> *mut u8 {
    loop {}
}

#[no_mangle]
pub unsafe extern "C" fn __wbindgen_free(_ptr: *mut u8, _size: usize, _align: usize) {
    loop {}
}

#[no_mangle]
pub unsafe extern "C" fn __wbindgen_exn_store(_idx: u32) {
    loop {}
}
```

In case its not clear, this seems like a pretty simple example that should easily work out of the box. (The use of `proc-macro` from the mcve-stylist part of the story seems like an important part of the reproduction.)

Still looking.

**Comment by pnkfelix** [comment] 2023-07-20 19:23
@saethlin [wrote](https://github.com/rust-lang/rust/issues/111888#issuecomment-1585690896):

> So this bisects to a rollup then can't find the unrolled perf builds. Manual trials identifies #108017 as the source of the regression.

As an addendum to this: #108017 (which was in a rollup, as mentioned) added the future-proofing safe-guard of adding `--no-undefined-version` to the linker invocation. We can add that same link-arg ourselves as part of further bisection that acts prior to PR #108017.

In my own MCVE, when I add that link-arg, I find that the code *did* compile circa 1.63 even with that `--no-undefined-version` flag. The flag *stopped* working sometime between nightly-2022-08-01 and nightly-2022-08-02. (I have not yet tracked down further than that, since its too old to have per-commit prebuilds archived.)

**Comment by pnkfelix** [comment] 2023-08-04 14:19
See related discussion in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/linker.20errs.20from.20wasm.20exposed.20by.20mir.20align.20checks.20.23111888

(I have a branch with a commit that seems to fix this here: https://github.com/pnkfelix/rust/tree/dont-export-no-mangle-from-proc-macros-issue-99978 ; I hope to have a PR up today, once I get a regression test into place.)

**Closed** 2023-08-09 03:14 UTC
Labels: A-linkage, P-high, T-compiler, regression-from-stable-to-stable, C-bug
