### ISSUE TITLE
thread 'rustc' panicked at 'found unstable fingerprints for optimized_mir

### ISSUE THREAD

**Issue by HCastano** [rust-lang/rust#85064] opened 2021-05-08 02:21 UTC
First of all, thanks for all your hard work on the compiler!

I ran into the following issue while doing a `cargo build` of the following repo: [`parity-bridges-common`](https://github.com/paritytech/parity-bridges-common). I'd been `check`-ing and `build`-ing my code fine but at one point just got stuck in this state where it would panic with this message on every build.

I wasn't able to figure out how to produce a minimal example. I also wasn't able to reproduce it by just building the offending packages (e.g `millau-bridge-node` or `rialto-bridge-node` based off the error output) individually.

Unfortunately (or maybe fortunately?) I wasn't able to reproduce by building with the nightly compiler.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.52.0 (88f19c6da 2021-05-03)
binary: rustc
commit-hash: 88f19c6dab716c6281af7602e30f413e809c5974
commit-date: 2021-05-03
host: x86_64-unknown-linux-gnu
release: 1.52.0
LLVM version: 12.0.0
```

```
$ rustc +nightly --version --verbose
rustc 1.54.0-nightly (bacf770f2 2021-05-05)
binary: rustc
commit-hash: bacf770f2983a52f31e3537db5f0fe1ef2eaa874
commit-date: 2021-05-05
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.0
```

### Error output

I captured the [following error output](https://gist.github.com/HCastano/945935054c167647795fe7e4d4f9e3c5) after running `RUST_BACKTRACE=1 cargo build`. Since the output is so large I thought it would be best to put it in a Gist.

**Comment by wesleywiser** [comment] 2021-05-10 15:58
Thanks for filing the bug report! We just shipped a [patch release to work around this issue](https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html) and are currently triaging related issues related to ensure each underlying problem gets resolved. Since this appears to be a duplicate of #84960, I'm going to close in favor of that issue.

**Closed by wesleywiser** 2021-05-10 15:58 UTC
Labels: C-bug, I-ICE, T-compiler
