### ISSUE TITLE
internal compiler error: failed to process buffered lint here

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#81531] opened 2021-01-29 19:47 UTC
### Code

I don't have a minimal example yet, but here's [the code](https://cs.opensource.google/fuchsia/fuchsia/+/master:src/sys/pkg/lib/omaha-client/src/state_machine.rs;l=539;drc=135c122764c96cb5132d4d1bbb51bb75b2f12a92). Sample:

```Rust
    async fn report_check_interval(&mut self, install_source: InstallSource) {
        let now = self.time_source.now();

        match self.context.schedule.last_update_check_time {
            Some(PartialComplexTime::Wall(t)) => match now.wall_duration_since(t) {
                Ok(interval) => self.report_metrics(Metrics::UpdateCheckInterval {
                    interval,
                    clock: ClockType::Wall,
                    install_source,
                }),
                Err(e) => warn!("Last check time is in the future: {}", e),  // <-- ICE
            },

            Some(PartialComplexTime::Complex(t)) => match now.mono.checked_duration_since(t.mono) {
                Some(interval) => self.report_metrics(Metrics::UpdateCheckInterval {
                    interval,
                    clock: ClockType::Monotonic,
                    install_source,
                }),
                None => error!("Monotonic time in the past"),  // <-- ICE
            },

            _ => {}
        }

        self.context.schedule.last_update_check_time = now.into();
    }
```

The ICE happens on the `warn!` and `error!` macros, which are both from the `log` crate.

### Meta

This began with commit 74500b99783d126e330184f0392a78f8b93b73ef.

### Error output

```
error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:539:27
    |
539 |                 Err(e) => warn!("Last check time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:552:25
    |
552 |                 None => error!("Monotonic time in the past"),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:997:27
    |
997 |                 Err(e) => warn!("Update first seen time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
 RUST_BACKTRACE=1 ../../prebuilt/third_party/rust/linux-x64/bin/rustc --color=always --crate-name omaha_client ../../src/sys/pkg/lib/omaha-client/src/lib.rs --crate-type rlib --emit=dep-info=obj/sr…
error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:539:27
    |
539 |                 Err(e) => warn!("Last check time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:552:25
    |
552 |                 None => error!("Monotonic time in the past"),
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> ../../src/sys/pkg/lib/omaha-client/src/state_machine.rs:997:27
    |
997 |                 Err(e) => warn!("Update first seen time is in the future: {}", e),
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /b/s/w/ir/x/w/rust/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: rust_begin_unwind
             at /b/s/w/ir/x/w/rust/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /b/s/w/ir/x/w/rust/library/std/src/panicking.rs:435:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (b12290861 2021-01-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z dep-info-omit-d-target -Z allow-features= -Z panic_abort_tests -C linker=/b/s/w/ir/x/w/fuchsia/prebuilt/third_party/clang/linux-x64/bin/lld -C link-arg=--sysroot=gen/zircon…

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by camelid** [comment] 2021-01-29 19:49
> I don't have a minimal example yet, but here's [the code](https://osscs.corp.google.com/fuchsia/fuchsia/+/master:src/sys/pkg/lib/omaha-client/src/state_machine.rs;l=539;drc=135c122764c96cb5132d4d1bbb51bb75b2f12a92). Sample:

FYI, I think that link is only accessible to Googlers:

![image](https://user-images.githubusercontent.com/37223377/106320676-0d858480-6228-11eb-8ff2-54542a44779e.png)

**Comment by tmandry** [comment] 2021-01-29 19:55
Sorry, [fixed](https://cs.opensource.google/fuchsia/fuchsia/+/master:src/sys/pkg/lib/omaha-client/src/state_machine.rs;l=539;drc=135c122764c96cb5132d4d1bbb51bb75b2f12a92).

**Comment by Aaron1011** [comment] 2021-01-29 20:29
Minimized:

```rust
macro_rules! foo {
    () => { true; }
}

async fn func() {
    let _ = foo!();
}

fn main() {}
```

Caused by https://github.com/rust-lang/rust/pull/79819

**Comment by Aaron1011** [comment] 2021-01-29 23:26
When we run `DefCollector` on the AST, we create a definition for the desugared closure body inside an `async fn`:

https://github.com/rust-lang/rust/blob/b122908617436af187252572ed5db96850551380/compiler/rustc_resolve/src/def_collector.rs#L124-L130

As a result, the `invocation_parents` entry for our macro call will have the `DefId` of the desugared closure. However, this desugared closure does not actually exist in the AST (it is created during lowering), so we will never check for lints with its `NodeId` when we emit buffered early lints.

**Comment by jethrogb** [comment] 2021-02-01 18:22
Nightly has been broken for 3 days, if there's disagreement on how to fix the issue, can we revert #79819 while the fix is being worked on?

**Comment by Aaron1011** [comment] 2021-02-02 00:36
This will be fixed by Pr https://github.com/rust-lang/rust/pull/81541

**Comment by jethrogb** [comment] 2021-02-03 07:45
I'm still hitting this bug with the latest nightly.

```rust
use futures::prelude::*;
use failure::bail;

fn main() {
    let _: std::pin::Pin<Box<dyn futures::Future<Output = Result<(), failure::Error>>>> = (async move {
        bail!("")
    }).boxed_local();
}
```

**Closed** 2021-02-03 14:30 UTC
Labels: C-bug, I-ICE, I-prioritize, T-compiler, regression-from-stable-to-nightly
