### ISSUE TITLE
New error on nightly 'overflow evaluating the requirement'

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#123622] opened 2024-04-08 05:54 UTC
### Code

I tried this code: https://github.com/diesel-rs/diesel/commit/9fe91c3ce6124ef86f714a3928e0db3db803c64e

```
git clone https://github.com/diesel-rs/diesel/
cd diesel
git checkout 9fe91c3ce6124ef86f714a3928e0db3db803c64e
cargo check --all-targets -p diesel_tests --features "sqlite"
```

I expected to see this happen: Compilation succeeds as on stable/beta/older nightlies.

Instead, this happened: New "overflow evalualing the requirement" errors are emitted:

```
error[E0275]: overflow evaluating the requirement `(&_, &_, &_, ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...): diesel::Insertable<...>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "2048"]` attribute to your crate (`integration_tests`)
  = note: required for `&(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)` to implement `diesel::Insertable<schema::trees::table>`
  = note: 1023 redundant requirements hidden
  = note: required for `(&..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...)` to implement `diesel::Insertable<schema::trees::table>`
  = note: the full name for the type has been written to '/tmp/diesel/target/debug/deps/integration_tests-f4624868b3b3c56d.long-type-14619293875363383290.txt'
  = note: consider using `--verbose` to print the full type name to the console

error[E0275]: overflow evaluating the requirement `(&_, &_, &_, ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...): diesel::Insertable<...>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "2048"]` attribute to your crate (`integration_tests`)
  = note: required for `&(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)` to implement `diesel::Insertable<schema::users::table>`
  = note: 1023 redundant requirements hidden
  = note: required for `(&..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...)` to implement `diesel::Insertable<schema::users::table>`
  = note: the full name for the type has been written to '/tmp/diesel/target/debug/deps/integration_tests-f4624868b3b3c56d.long-type-14619293875363383290.txt'
  = note: consider using `--verbose` to print the full type name to the console

error[E0275]: overflow evaluating the requirement `(&_, &_, &_, ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...): diesel::Insertable<...>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "2048"]` attribute to your crate (`integration_tests`)
  = note: required for `&(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)` to implement `diesel::Insertable<schema::with_keywords::table>`
  = note: 1023 redundant requirements hidden
  = note: required for `(&..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...)` to implement `diesel::Insertable<schema::with_keywords::table>`
  = note: the full name for the type has been written to '/tmp/diesel/target/debug/deps/integration_tests-f4624868b3b3c56d.long-type-14619293875363383290.txt'
  = note: consider using `--verbose` to print the full type name to the console

error[E0275]: overflow evaluating the requirement `(&_, &_, &_, ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...): diesel::Insertable<...>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "2048"]` attribute to your crate (`integration_tests`)
  = note: required for `&(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _)` to implement `diesel::Insertable<has_time_types::table>`
  = note: 1023 redundant requirements hidden
  = note: required for `(&..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...)` to implement `diesel::Insertable<has_time_types::table>`
  = note: the full name for the type has been written to '/tmp/diesel/target/debug/deps/integration_tests-f4624868b3b3c56d.long-type-14619293875363383290.txt'
  = note: consider using `--verbose` to print the full type name to the console

```

### Version it worked on

It most recently worked on: nightly-2024-04-05

### Version with regression

`rustc --version --verbose`:
```
rustc 1.79.0-nightly (9d5cdf75a 2024-04-07)
binary: rustc
commit-hash: 9d5cdf75aa42faaf0b58ba21a510117e8d0051a3
commit-date: 2024-04-07
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3

```

I've run `cargo bisect-rustc` and got back the following report:

********************************************************************************
Regression in 9d79cd5f79e75bd0d2083260271307ce9acd9081
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment

searched nightlies: from nightly-2024-04-05 to nightly-2024-04-08
regressed nightly: nightly-2024-04-06
searched commit range: https://github.com/rust-lang/rust/compare/385fa9d845dd326c6bbfd58c22244215e431948a...9d79cd5f79e75bd0d2083260271307ce9acd9081
regressed commit: https://github.com/rust-lang/rust/commit/9d79cd5f79e75bd0d2083260271307ce9acd9081

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2024-04-05 --script script.sh --regress error 
```
</details>

cc @Urgau as author of the relevant PR.

@rustbot modify labels: +regression-from-nightly-to-nightly -regression-untriaged

**Comment by Urgau** [comment] 2024-04-08 05:56
Duplicate of https://github.com/rust-lang/rust/issues/123573

**Closed** 2024-04-08 08:24 UTC
Labels: C-bug, I-prioritize, regression-untriaged, needs-triage
