### ISSUE TITLE
coyoneda-0.5.2 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43659] opened 2017-08-05 12:32 UTC
[coyoneda](https://crates.io/crates/coyoneda) version 0.5.2 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/coyoneda-0.5.2/log.txt)):

```
error: type `morphism::Void` is private
   --> src/lib.rs:142:35
    |
142 |         Coyoneda{point: x, morph: Morphism::new()}
    |                                   ^^^^^^^^^^^^^
                        ^ 
```
cc @srijs

**Comment by petrochenkov** [comment] 2017-08-05 12:43
This is a known regression as well (see https://github.com/rust-lang/rust/pull/42125#issuecomment-304301659).
The issue was actually in `morphism`, not `coyoneda`, and I sent a [PR](https://github.com/freebroccolo/morphism.rs/pull/20) to fix it in May, but it was ignored.

**Comment by nikomatsakis** [comment] 2017-08-17 20:34
Closing since there is a pending PR to fix, and no particular further action for us to take at this time.

**Closed by nikomatsakis** 2017-08-17 20:34 UTC
Labels: C-bug, regression-from-stable-to-beta, T-compiler
