### ISSUE TITLE
With the edition enabled, `proc_macro_path_invoc` feature causes bugs with `tool_attributes` feature

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#51940] opened 2018-06-30 09:26 UTC
With `#![feature(rust_2018_preview)]` and `#![feature(tool_attributes)]`. correct attributes give errors, e.g.,

```
error[E0658]: paths of length greater than one in macro invocations are currently unstable (see issue #38356)
  --> src/sealed.rs:28:3
   |
28 | #[rustfmt::skip]
   |   ^^^^^^^^^^^^^
   |
   = help: add #![feature(proc_macro_path_invoc)] to the crate attributes to enable
```

enabling `proc_macro_path_invoc` gives

```
error[E0433]: failed to resolve. Use of undeclared type or module `rustfmt`
  --> src/sealed.rs:28:3
   |
28 | #[rustfmt::skip]
   |   ^^^^^^^ Use of undeclared type or module `rustfmt`
```

Expected behaviour: no errors and the attribute is ignored by the compiler

Reported in https://github.com/rust-lang-nursery/rustfmt/issues/2815

cc @gnzlbg @rust-lang/compiler @petrochenkov

**Comment by oli-obk** [comment] 2018-06-30 09:42
dupe of https://github.com/rust-lang/rust/issues/51277

**Closed** 2018-07-05 20:21 UTC
Labels: A-attributes, A-macros, A-rust-2018-preview, P-high, T-dev-tools
