### ISSUE TITLE
LLVM ERROR for huge ZST array

### ISSUE THREAD

**Issue by Qwaz** [rust-lang/rust#90511] opened 2021-11-02 19:18 UTC
I tried this code:

```rust
fn main() {
    let t = [(); isize::MAX as usize + 1];
    println!("Len: {}", t.len());
}
```

I expected to see this happen:
Works as expected or rustc explains the error.

Instead, this happened:
I get an LLVM error
```
invalid subrange count
!378 = !DISubrange(count: -9223372036854775808, lowerBound: 0)
invalid subrange count
!378 = !DISubrange(count: -9223372036854775808, lowerBound: 0)
LLVM ERROR: Broken module found, compilation aborted!
```

### Meta

`rustc --version --verbose` (same error on the latest nightly):
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

### Non-ZST arrays
`let t = [123; isize::MAX as usize + 1];`

```
error: values of the type `[i32; 9223372036854775808]` are too big for the current architecture

error: could not compile `playground` due to previous error
```
This error message can be possibly improved too.

`let t = &[123; isize::MAX as usize + 1];`
```
error[E0080]: values of the type `[i32; 9223372036854775808]` are too big for the current architecture
 --> src/main.rs:2:14
  |
2 |     let t = &[123; isize::MAX as usize + 1];
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: erroneous constant used
 --> src/main.rs:2:13
  |
2 |     let t = &[123; isize::MAX as usize + 1];
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ referenced constant has errors
  |
  = note: `#[deny(const_err)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

For more information about this error, try `rustc --explain E0080`.
error: could not compile `playground` due to 2 previous errors
```
This is what I expect to see.

**Comment by Qwaz** [comment] 2021-11-02 19:27
Oh, interestingly it works in release mode.
```rust
fn main() {
    let t = [(); usize::MAX - 0x40];
    println!("Len: {:x}", t.len());
}
```

Output
```
Len: ffffffffffffffbf
```

**Comment by tmiasko** [comment] 2022-01-21 18:19
Duplicate of #34127

**Closed by tmiasko** 2022-01-21 18:19 UTC
Labels: C-bug
