### ISSUE TITLE
libtest - capture stderr from tests

### ISSUE THREAD

**Issue by NoraCodes** [rust-lang/rust#40298] opened 2017-03-06 16:23 UTC
I'm currently having a problem with testing libraries that use `log` with either `env_logger` or `flexi_logger` in their tests. In the "real world", they should log to `stderr`, but libtest (and, by extension Cargo) doesn't capture `stderr` from tests, so I have to jump through hoops to get these libraries to log to `stdout` instead, or sift through huge logdumps.

Would it be possible to capture `stderr` from tests?

I originally posted this on the Cargo repo, but was told to file here. Possibly related to #31983, but I've tried limiting the test threads (`RUST_TEST_THREADS=1`) with no result.

**Comment by martinlindhe** [comment] 2017-03-31 20:22
I agree on this.

For a little more detail;

Consider the following

```rust
#[macro_use]
extern crate log;
extern crate colog;

fn do_stuff() -> bool {
    println!("println");
    error!("error");
    true
}

#[test]
fn my_test() {
    assert_eq!(true, do_stuff());
}
```

run: `cargo test -- --nocapture`

actual output:
```
running 1 test
println
test my_test ... ok
```

expected output:
```
running 1 test
println
error
test my_test ... ok
```

**Comment by dpc** [comment] 2017-03-31 20:23
Using `slog-envlogger` one can easily have a logger that logs to `stderr` and if needed control it with `RUST_LOG` variable.

**Comment by martinlindhe** [comment] 2017-03-31 20:25
@dpc Not sure it would help, since it seems `cargo test`, even with the `--nocapture` swallows stderr. Only stdout is shown.

**Comment by dpc** [comment] 2017-03-31 20:27
@ martinlindhe ... Edited my original coment. Slog doesn't care. Log to stdout, stderr, file. Or even open new raw `1` file descriptor and circumvent `cargo test` jail.

**Comment by dpc** [comment] 2017-03-31 20:29
I actually should create `slog-test` crate specifically for that purpose... Ping me on slog gitter if you're interested. I guess it's enough of `slog` advertising. :D

**Comment by martinlindhe** [comment] 2017-03-31 20:36
@dpc, Okay.. so I can make a custom slog logger that outputs to stdout, thus allow cargo test to fetch the output. Gotcha.
But I think it would benefit the end user more if cargo test would display stderr, even if it is hidden behind a rather obscure flag as `--nocapture`.

**Comment by SilverWingedSeraph** [comment] 2017-03-31 20:37
Yes, I agree. Not everyone is in a position to use slog, as awesome as it
is.

**Comment by elichai** [comment] 2019-01-31 15:01
Any updates on this?
Does this mean that right now using rust `log` I can't see them in tests?

**Comment by vincentdephily** [comment] 2019-02-21 21:36
AFAIU libtest now captures "stderr" and "stdout" but does so in a way that isn't compatible with some loggers that try to use the standard stderr/stdout without using something like `println!()`. For example https://github.com/sebasmagri/env_logger/issues/107 is discussing workarounds but it has drawbacks.

Another minor issue is that while libtest does capture `println!()` and `eprintln!()` output, they are both output on and labeled as "stdout" only.

**Comment by Mark-Simulacrum** [comment] 2019-09-01 13:12
Closing as duplicate of https://github.com/rust-lang/rust/issues/42474.

**Closed by Mark-Simulacrum** 2019-09-01 13:12 UTC
Labels: A-libtest, C-feature-request
