### ISSUE TITLE
LLVM modules are deallocated before `after_llvm` phase controller is called

### ISSUE THREAD

**Issue by willcrichton** [rust-lang/rust#34432] opened 2016-06-23 17:57 UTC
The `CompileController`'s `after_llvm` phase should (I believe) allow the programmer to access the generated LLVM IR for the various modules. However, the `after_llvm` phase is [called after the end of phase 5](https://github.com/rust-lang/rust/blob/master/src/librustc_driver/driver.rs#L239-L242), and at the [end of phase 5](https://github.com/rust-lang/rust/blob/master/src/librustc_trans/back/write.rs#L619) the LLVM modules are deallocated. I'm not sure what the right solution is here, but it would be fabulous to have programmatic access to the LLVM IR.

**Comment by alexcrichton** [comment] 2016-06-23 20:53
cc @nrc

**Comment by willcrichton** [comment] 2016-06-24 00:02
I'll take a stab at it. Two questions for you @nrc: 
1. When you say pass the llvm modules to the callback, what do you mean? Aren't they already passed through the CrateTranslation object in the compile state?
2. Would you recommend moving the LLVM clean up code into a new phase (phase_6_cleanup_llvm) or to the top of the existing phase_6? The latter is kind of weird since that's not what the phase is for, but it's a relatively small amount for code for a new phase.

**Comment by nrc** [comment] 2016-06-24 01:20
@willcrichton great! Having looked closely at the code it is maybe not as easy as I first thought, but it still should be ok. THe issue is that we dispose of the llmod for each codegen unit as soon as we are done with it and instead we want to dispose of them all once we're done with all of them.

1. It turns out they are (I didn't realise because they are kind of deeply nested), so nothing to do here :-)
2. the 'phase' distinction is a bit of an historical artifact, it doesn't really matter whether a function has phase at the start of the name or not, really. So I wouldn't create a new phase 6, but I would insert a function call to cleanup_llvm after the after_llvm callback, in compile_input, before the call to phase_6.

**Comment by aravind-pg** [comment] 2016-07-07 23:29
I think this can be closed now that #34594 has landed?

**Closed** 2016-07-08 01:57 UTC
Labels: E-mentor
