### ISSUE TITLE
Support all ASCII escape characters

### ISSUE THREAD

**Issue by postmodern** [rust-lang/rust#34233] opened 2016-06-11 23:03 UTC
I noticed that rust only supports certain character escapes (`\n`, `\t`, `\r`, `\\`, `\0`). However, according to the [ASCII(7)](http://man7.org/linux/man-pages/man7/ascii.7.html) man page, ASCII defines the following character escapes:

* `\0` (supported)
* `\a`
* `\b`
* `\t` (supported)
* `\n` (supported)
* `\v`
* `\f`
* `\r` (supported)
* `\\` (supported)

If one attempts to use one of the unsupported character escape (ie `\a`) in a Rust program, they will receive the following error message:

<pre>
fn main()
{
	let c = '\a';

	println!("c = {}", c);
}
</pre>

<pre>
error: unknown character escape: a
</pre>

This is erroneous, as the ASCII man page and other languages recognize `\a` as a valid known character escape.

**Comment by sfackler** [comment] 2016-06-12 15:33
That man page documents the escape codes that C recognizes - I wouldn't call it the canonical source of escape sequences in arbitrary languages.

**Comment by nagisa** [comment] 2016-06-12 15:50
Duplicate of https://github.com/rust-lang/rfcs/issues/751.

**Closed by nagisa** 2016-06-12 15:50 UTC
