### ISSUE TITLE
Rust 2021 compile error on  WSL2 Unbuntu

### ISSUE THREAD

**Issue by baekhyunee7** [rust-lang/rust#91738] opened 2021-12-10 09:31 UTC
After I update  rust version to 2021, I got compile error on WSL2 Unbuntu:
```
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd/compiler/rustc_serialize/src/opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

**Comment by joIivier** [comment] 2021-12-10 09:40
It looks like a duplicate of #91663 , `cargo clean` might fix your issue as well.

**Comment by ehuss** [comment] 2021-12-10 16:10
Thanks for the report!  `cargo clean` should clear it up as long as you don't switch to older toolchains.  Closing as a duplicate of #91663.

**Closed by ehuss** 2021-12-10 16:10 UTC
Labels: I-ICE, T-compiler, C-bug
