### ISSUE TITLE
`[_; 33]` implements `Copy`, but not `Clone`

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#40796] opened 2017-03-24 15:16 UTC
From https://www.reddit.com/r/rust/comments/616rc8/rcpp_discusses_rust/dfcjk09/

The following code:

```rust
fn clone_copy_type<T: Copy>(t: T) -> T {
    t.clone()
}

fn main() {
    // [_; 33] implements Copy, but not Clone, violating trait inheritance
    clone_copy_type([(); 33]);
}
```

Causes the following crash in playpen, due to `[T; 33]` (where `T: Copy`) implementing `Copy`, but not `Clone`, but `Copy` trait requiring `Clone` implementation.

```
error: internal compiler error: /checkout/src/librustc_trans/monomorphize.rs:151: Encountered error `Unimplemented` selecting `Binder(<[(); 33] as std::clone::Clone>)` during trans

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:377
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by steveklabnik** [comment] 2017-03-24 15:23
It's well known that this doesn't implement the trait, but it shouldn't ICE.

**Comment by jonas-schievink** [comment] 2017-03-24 15:29
The ICE is also well known. Since `Clone` is a supertrait of `Copy`, but isn't implemented in this case, this is technically a prime example for unsoundness. The Compiler is basically correct in assuming this will never happen, hence the ICE.

Also see #24000 and #28229

**Comment by tbu-** [comment] 2017-03-24 16:55
Basically a duplicate of those.

**Comment by steveklabnik** [comment] 2017-03-24 17:37
Okay! Sorry about that @xfix , I didn't see those when I was looking.

**Closed by steveklabnik** 2017-03-24 17:37 UTC
Labels: I-ICE, T-compiler
