### ISSUE TITLE
(internal compiler error: unprintable span)

### ISSUE THREAD

**Issue by hank-der-hafenarbeiter** [rust-lang/rust#32090] opened 2016-03-07 03:09 UTC
When running "cargo test" on [this code ](https://github.com/hank-der-hafenarbeiter/Rust-Shannon-Fano/tree/compiler_bug) (reproducable for me when checking out the compiler_bug branch). The compiler outputs:

```
 Compiling SFCodec v0.1.0 (file:///home/kevin/Projects/Rust/SFCodec)
<std macros>:5:4: 84:20 error: mismatched types:
 expected `bool`,
    found `u8`
(expected bool,
    found u8) [E0308]
(internal compiler error: unprintable span)
src/utils.rs:84:9: 84:57 note: in this expansion of assert! (defined in <std macros>)
<std macros>:5:4: 84:20 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `SFCodec`.

To learn more, run the command again with --verbose.
```

This is the corresponding code snipped: 

```
fn test_byte_and_back() {
     extern crate rand;
     use self::rand::{thread_rng, Rng};

     let mut rng = thread_rng();
     for i in 0..20 {
         let mut num:u8 = 0;
         for i in 0..8 {
             num = rng.gen();
          } 

         assert!(num, bools_to_byte(byte_to_bools(num)));             //line 84
      }
 } 
```

rustc --version --verbose: 

```
 rustc 1.6.0 (c30b771ad 2016-01-19)
 binary: rustc
 commit-hash: c30b771ad9d44ab84f8c88b80c25fcfde2433126
 commit-date: 2016-01-19
 host: x86_64-unknown-linux-gnu
 release: 1.6.0
```

**Comment by nagisa** [comment] 2016-03-07 12:52
Works fine in both of

```
rustc 1.8.0-nightly (0ef8d4260 2016-02-24)
rustc 1.9.0-nightly (d31d8a9a9 2016-03-04)
```

**Comment by wesleywiser** [comment] 2016-03-08 19:25
Seems like a duplicate of #28308

**Comment by Mark-Simulacrum** [comment] 2017-05-01 12:29
I get the following. This isn't an ICE, so I'm going to go ahead and close. Please reopen if there's actually something wrong here!

```
error[E0308]: mismatched types
  --> src/utils.rs:84:9
   |
84 |         assert!(num, bools_to_byte(byte_to_bools(num)));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected bool, found u8
   |
   = note: this error originates in a macro outside of the current crate
```

**Closed by Mark-Simulacrum** 2017-05-01 12:29 UTC
Labels: I-ICE
