### ISSUE TITLE
Slice pattern matching not expressive enough

### ISSUE THREAD

**Issue by Ticki** [rust-lang/rust#30540] opened 2015-12-23 17:15 UTC
Following example do not work.

```rust
fn main() {
    let a = [1, 2, 3];
    match &a {
        [a.., 2, b..] => println!("It works"),
        _ => {},
    }
}
```

This results in the error:

```rust
main.rs:4:19: 4:21 error: expected one of `,` or `@`, found `..`
main.rs:4         [a.., 2, b..] => println!("It works"),
                            ^~
Could not compile `test`.

To learn more, run the command again with --verbose.
```

Even though, it should not.

**Comment by Ticki** [comment] 2015-12-23 17:20
Note that reachability checking is possible even though more than one wildcard is used in the same match arm (it's just not implemented yet).

**Comment by jonas-schievink** [comment] 2015-12-23 17:55
Since this requires a linear search through the whole slice, I'm assuming that this is by design and would need an RFC amendment (I haven't actually read the slice patterns RFC)

**Comment by sfackler** [comment] 2015-12-23 18:36
What would happen if there are multiple 2s?

**Comment by Ticki** [comment] 2015-12-23 18:51
> What would happen if there are multiple 2s?

All's fine, then. This is only related to variable bounds, obviously.

**Comment by Ticki** [comment] 2015-12-23 18:57
https://github.com/rust-lang/rust/blob/master/src/librustc/middle/check_match.rs#L538-L981

**Comment by sfackler** [comment] 2015-12-23 18:59
@Ticki I meant, which 2 is chosen as the split between a and b?

**Comment by Ticki** [comment] 2015-12-23 19:01
I see. Since it's just linear search, it would be the first `2` to find.

**Comment by lilred** [comment] 2015-12-27 04:18
Maybe post this as an RFC?

**Comment by Ticki** [comment] 2015-12-27 09:00
Yes, will look into it, @lilred

**Comment by arielb1** [comment] 2015-12-27 13:56
This should be an RFC. Closing.

**Closed by arielb1** 2015-12-27 13:56 UTC
