### ISSUE TITLE
Regression in type parameter defaults in types and impls

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#30123] opened 2015-11-30 20:01 UTC
This regression is only visible in cross-crate code; NOTE it's very likely it's due to an actual rustc **bug fix**.

[Here is some playpen code](https://play.rust-lang.org/?gist=f4d2181b9414719c41ed&version=stable) for illustration anyway.

Given a struct with default parameters and two constructor functions:

```rust
pub struct Graph<N, E, Ty = Directed, Ix: IndexType = DefIndex> {
    nodes: Vec<Node<N, Ix>>,
    edges: Vec<Edge<E, Ix>>,
    ty: PhantomData<Ty>,
}


impl<N, E> Graph<N, E, Directed> {
    pub fn new() -> Self {
        Graph{nodes: Vec::new(), edges: Vec::new(), ty: PhantomData}
    }
}

impl<N, E> Graph<N, E, Undirected> {
    pub fn new_undirected() -> Self {
        Graph{nodes: Vec::new(), edges: Vec::new(), ty: PhantomData}
    }
}
```

In **Rust 1.4 or later (current stable and current nightly)**, both must be called like this to compile:

```rust
    let g = Graph::<i32, i32>::new();
    let ug = Graph::<i32, i32, _>::new_undirected();
```

In **current stable Rust 1.4**, the following compiles if you import `Graph` across crates!

```rust
let ug = Graph::<i32, i32>::new_undirected();
```

This is **invalid in current nightly Rust ~1.6**, [see travis build example](https://travis-ci.org/bluss/petulant-avenger-graphlibrary/builds/94011263); the testcases are in their own crates.

```
tests/ograph.rs:1018:18: 1018:48 error: no associated item named `new_undirected` found for type `petgraph::graph::Graph<_, ()>` in the current scope
tests/ograph.rs:1018     let mut gr = Graph::<_, ()>::new_undirected();
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by nikomatsakis** [comment] 2015-12-17 21:22
This does seem more like a bug *fix*, but I'm not sure what would have triggered it.

**Comment by nikomatsakis** [comment] 2015-12-17 21:22
triage: P-high

It's important to decide if this is now doing the correct thing.

**Comment by bluss** [comment] 2015-12-17 21:49
I'm sure it's an acceptable fix, but I think we want issues for all regressions, no matter why they happen.

I was mostly amused that there was no way to write a type hinted call too `Graph::new_undirected()` that would compile with Rust 1.4 (requires 2 type params) and Rust 1.6 (requires three); you have to hint the types through the returned value instead.

**Comment by arielb1** [comment] 2015-12-21 20:42
The 2-type-param version was working only by a bug - we have no plans of working around that.

**Comment by nikomatsakis** [comment] 2016-01-06 21:23
@arielb1 do you think you know what fixed it? maybe something in metadata got corrected?

**Comment by brson** [comment] 2016-01-08 23:54
I'm trying to bisect to find out what changed, then write a test case.

**Comment by bluss** [comment] 2016-01-11 05:54
See the issue link ^ I'm not crazy, the issue has now appeared somewhere else too :smile:

**Comment by brson** [comment] 2016-01-11 23:23
Bisecting is proceeding slowly...

**Comment by brson** [comment] 2016-01-14 19:15
My bisection attempt failed.

**Comment by nikomatsakis** [comment] 2016-01-14 20:38
@brson :( if you like, I can try tracing through the relevant code paths with `git blame` to try and find likely candidates

**Comment by bluss** [comment] 2016-01-14 21:38
I looked and my guess landed on a metadata change that @arielb1 did, would explain the cross crate only behavior.

**Comment by nikomatsakis** [comment] 2016-01-14 21:39
@bluss seems likely, I agree.

**Comment by bluss** [comment] 2016-01-14 22:11
The commit was db817ceda4fe204261c9d1773dc137830e58e225

**Comment by arielb1** [comment] 2016-01-14 22:20
This commit should not have changed anything.

**Comment by brson** [comment] 2016-01-16 01:30
@nikomatsakis nah that's ok. It's not a huge deal. I did start another bisect though. I'm having a hard time summarizing this change for the release notes. There are a lot of technical pieces here. Can somebody try?

**Comment by bluss** [comment] 2016-01-16 01:41
@arielb1 My guess could have landed totally wrong. Don't know why I tried. You all know this better than me. For example, as the ImageBuffer example shows, type parameter defaults don't have to be involved, which has me a bit confounded.

**Comment by brson** [comment] 2016-01-18 01:21
I am still trying to bisect.

**Comment by brson** [comment] 2016-01-19 20:44
f5fbefa3af48ed44b002a7423d6cbd74e4018c9c  caused it.

**Comment by brson** [comment] 2016-01-19 20:44
cc @arielb1

**Comment by arielb1** [comment] 2016-01-19 22:16
I *think* the culprit is that I added the
```Rust
child_name_bindings.define_type(def, DUMMY_SP, modifiers);
```

**Comment by arielb1** [comment] 2016-01-19 22:27
That indeed seems to be the change (commenting it out makes things compile again).

Could someone who understands `resolve` tell me how the change could cause that kind of effects?

**Comment by nikomatsakis** [comment] 2016-01-21 21:13
I'm going to close this issue then as "not a bug", since we know that commit caused it.

**Closed by nikomatsakis** 2016-01-21 21:13 UTC
Labels: P-high, regression-from-stable-to-beta, relnotes, T-compiler

**Comment by eddyb** [comment] 2016-02-21 16:19
@arielb1 Coming back to this, I remember that you removed some metadata code for saving inherent methods: wouldn't they be picked up by resolve, instead of letting typeck do UFCS resolution?

**Comment by hatahet** [comment] 2016-02-27 22:25
@brson:

> My bisection attempt failed.

What caused it to fail the first time?
