### ISSUE TITLE
Suggest that a method exist with a different self type

### ISSUE THREAD

**Issue by ogoffart** [rust-lang/rust#79352] opened 2020-11-23 16:38 UTC
Consider this code:

```rust
use std::pin::Pin;
struct Hello;
impl Hello {
    pub fn foo(self: Pin<&Self>) { }
}

fn main() {
    let h = Box::pin(Hello);
    h.foo();
}
```

As of Rust 1.48 we get the following (expected) error (and the same error is in nightly)

```
error[E0599]: no method named `foo` found for struct `Pin<Box<Hello>>` in the current scope
 --> src/main.rs:9:7
  |
9 |     h.foo();
  |       ^^^ method not found in `Pin<Box<Hello>>`
```

Ideally, it would be great if the method exist with a different self type, the compiler would tell us that this method exist

Suggestion:
```
  help: there is an associated function of the same name with a different self type: `Pin<&Hello>`
```

Even better would be if the compiler would know how to hint to use `Pin::as_ref()` in this case to fix the error. (A bit similar to #65409)

**Comment by SNCPlay42** [comment] 2020-11-23 20:11
Duplicate of #57994

**Closed** 2020-11-24 00:36 UTC
Labels: C-bug
