### ISSUE TITLE
 Recursion depth too shallow on Mac OS X

### ISSUE THREAD

**Issue by tioover** [rust-lang/rust#20809] opened 2015-01-09 16:28 UTC
use std::io::stdio::flush;

    fn recu(n: int) {
        println!("{}", n);
        recu(n+1);
        flush();
    }

    fn main() {
        recu(0)
    }   

    
Output :

    ...
    2924
    2925
    2926
    2927
    2928
    2929
    2930
    2931
    
    thread '<main>' has overflowed its stack
    [1]    23873 illegal hardware instruction  ./test

Infomation:
> rustc 1.0.0-nightly (ea6f65c5f 2015-01-06 19:47:08 +0000)
> 
> MacBook Pro
> 
> 2.2 GHz Intel Core i7

In other machine(Linux 64):

    ...
    11668
    11669
    11670
    
    thread '<main>' has overflowed its stack
    [1]    18070 illegal hardware instruction (core dumped)  ./test

**Comment by darinmorrison** [comment] 2015-01-09 17:57
There isn't a good fix for this unless Rust gets guaranteed tail-call optimization. You can use trampolines with a bit of effort though if you really need recursion.

**Comment by kmcallister** [comment] 2015-01-09 21:13
The default stack size and the size of any given stack frame can vary by platform, so the mere difference between these numbers is not a bug.

If you have more specific information about why the default stack size on OS X should be higher, and/or evidence that the OS X version uses more stack space per call than it needs to, please open a new issue with that additional information.

(Also, were you building with optimization?)

**Closed by kmcallister** 2015-01-09 21:13 UTC
