### ISSUE TITLE
Error diagnostic suggests syntactically invalid code

### ISSUE THREAD

**Issue by cdisselkoen** [rust-lang/rust#64388] opened 2019-09-11 22:36 UTC
For the following code ([Playground link]):

```rust
fn foo<'a>(u: &'a usize) -> impl IntoIterator<Item = usize> + 'a {
    std::thread::spawn(move || {
        println!("{}", u);
    });
    vec![]
}
```

`rustc` provides the following error and suggestion:
```
error: cannot infer an appropriate lifetime
 --> src/lib.rs:2:24
  |
2 |       std::thread::spawn(move || {
  |  _____------------------_^
  | |     |
  | |     this return type evaluates to the `'static` lifetime...
3 | |         println!("{}", u);
4 | |     });
  | |_____^ ...but this borrow...
  |
note: ...can't outlive the lifetime 'a as defined on the function body at 1:8
 --> src/lib.rs:1:8
  |
1 | fn foo<'a>(u: &'a usize) -> impl IntoIterator<Item = usize> + 'a {
  |        ^^
help: you can add a constraint to the return type to make it last less than `'static` and match the lifetime 'a as defined on the function body at 1:8
  |
2 |     std::thread::spawn + 'a(move || {
  |     ^^^^^^^^^^^^^^^^^^^^^^^
```

But applying this suggestion results in a syntax error:
```
error: expected `:`, found `(`
 --> src/lib.rs:2:28
  |
2 |     std::thread::spawn + 'a(move || {
  |                            ^ expected `:`
```

Using the [Playground link], I reproduced this invalid suggestion on Rust 1.37.0 stable, 1.38.0-beta.2, and 1.39.0-nightly 2019-08-23. 

[Playground link]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2dbf323f7157be293221f68f87c3961f

**Comment by jbg** [comment] 2019-10-27 15:09
appears to be a duplicate of #62097

**Comment by csmoe** [comment] 2019-10-29 12:41
Close as duplicate.

**Closed by csmoe** 2019-10-29 12:41 UTC
Labels: A-diagnostics, A-suggestion-diagnostics, C-bug, D-invalid-suggestion, T-compiler
