### ISSUE TITLE
On mac the unmangled symbol is not being visible at the time of linking

### ISSUE THREAD

**Issue by ckkashyap** [rust-lang/rust#21097] opened 2015-01-13 15:48 UTC
Somethings has changed in Rust (Mac) in the last month that is affecting how the symbols get exposed in the generated static library. When I compile my kernel on Linux things work fine. However on mac - the libkernel.a that gets generated under the kernel directory does not seem to contain the "cmain" symbol - which is clearly there in kernel.rs

**Comment by ckkashyap** [comment] 2015-01-14 05:47
Just realized that I did not provide the path - https://github.com/ckkashyap/unix

**Comment by alexcrichton** [comment] 2015-07-13 17:04
I believe that this is just an artifact of platform differences. On OSX symbols get a leading underscore where on Linux they don't:

```
# on OSX
$ rustc foo.rs && nm -g libfoo.rlib
libfoo.rlib(foo.o):
                 U ___morestack
0000000000000000 T _foo

# on linux
$ rustc foo.rs && nm -g libfoo.rlib

foo.o:
0000000000000000 T foo
                 U __morestack

```

As a result I'm going to close this as not a bug.

**Closed by alexcrichton** 2015-07-13 17:04 UTC
Labels: A-linkage, A-mac-osx
