### ISSUE TITLE
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:974:13

### ISSUE THREAD

**Issue by yutiansut** [rust-lang/rust#82604] opened 2021-02-27 19:10 UTC
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
   Compiling actix-testing v1.0.1
error: internal compiler error: failed to process buffered lint here
   --> C:\Users\yutiansut\.cargo\registry\src\github.com-1ecc6299db9ec823\redis-async-0.6.3\src\client\pubsub.rs:267:23
    |
267 |             Err(e) => log::error!("Pub/Sub error: {:?}", e),
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877\compiler\rustc_lint\src\early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `redis-async`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-27 19:41
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-27 19:41 UTC
Labels: C-bug, I-ICE, T-compiler
