### ISSUE TITLE
Set transmute from fn item to type fn lint a hard error

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#19925] opened 2014-12-16 16:22 UTC
**Original title:** Fn item types should be zero-sized

Per [RFC 401](https://github.com/rust-lang/rfcs/blob/master/text/0401-coercions.md#function-type-polymorphism), every fn in Rust should have its own unique, zero-sized type. This fits with the overall design of closures, which also have their own unique types (but those types are not zero-sized, as they carry the environment). None of these types have any explicit syntax at present. This has been a longstanding plan, but until recently it was not fully implemented. This is changing with PR #31710, which means that some existing code will need to be adjusted to account for the new behavior. This issue attempts to summarize how things work and describe what needs to be changed.
### Zero-sized fn types

What all of this means is that, if you have a function declaration `foo`:

``` rust
// for the purposes of this discussion, all of these different kinds of `fn` declarations are equivalent:
fn foo(x: i32) { ... }
extern "C" fn foo(x: i32);
impl i32 { fn foo(x: self) { ... } }
```

the type of `foo` is **not** `fn(i32)`, as one might expect. Rather, it is a unique, zero-sized marker type that I will just write as `typeof(foo)`. However, `typeof(foo)` can be _coerced_ to a function pointer `fn(i32)`, so you rarely notice this:

``` rust
let x: fn(i32) = foo; // OK, coerces
```

The reason that this matter is that the type `fn(i32)` is not specify to any particular function: it's a function _pointer_. So calling `x()` results in a virtual call, whereas `foo()` is statically dispatched, because the type of `foo` tells us precisely what function is being called. 
### Impact on users

As noted above, coercions mean that most code will continue to work just fine before and after this issue is fully fixed. However, you can tell the difference in a few scenarios. Perhaps the most prominent is using **transmute** to convert a fn item into a fn pointer. This is often done as part of an FFI:

``` rust
extern "C" fn foo(userdata: Box<i32>) {
   ...
}

let f: extern "C" fn(*mut i32) = transmute(foo);
callback(f);
```

Here, transmute is being used to convert the types of the fn arguments. This pattern is now incorrect because, because the type of `foo` is a function **item** (`typeof(foo)`), which is zero-sized, and the target type (`fn()`) is a function pointer, which is not zero-sized. For now, this pattern still works due to some special-cased code in the compiler, but that code is expected to be removed. For future compatibility, this pattern should be rewritten. There are a few possible ways to do this:
- change the original fn declaration to match the expected signature, and do the cast in the fn body (perhaps the best);
- cast the fn item fo a fn pointer before calling transmute, as shown here:
  - `let f: extern "C" fn(*mut i32) = transmute(foo as extern "C" fn(_))`
  - `let f: extern "C" fn(*mut i32) = transmute(foo as usize) /* works too */`

The same applies to transmutes to `*mut fn()`, which were observed frequently in practice. Note though that use of this type is generally incorrect. The intention is typically to describe a function pointer, but just `fn()` alone suffices for that. `*mut fn()` is a pointer to a fn pointer. (Since these values are typically just passed to C code, however, this rarely makes a difference in practice.)
### Current status and implementation trail
- [x] PR #19891 laid the groundwork with fresh, unique types per fn item, but left the back-end work undone
- [x] PR #31710 completes the work.

**Comment by nikomatsakis** [comment] 2015-01-27 20:36
Nominating. Not sure how important this is.

**Comment by pnkfelix** [comment] 2015-01-29 21:12
P-high, not 1.0 milestone.

**Comment by nikomatsakis** [comment] 2015-04-01 22:22
On a related note, the subtyping relation is not quite right. [This code](http://is.gd/UkkqF2) should not type check: 

```rust
fn foo<A>(_: A, _: A) { }

fn bar<B>() { }

fn main() {
    let x = bar::<u32>;
    let y = bar::<i32>;
    foo(x, y);
}
```

**Comment by nikomatsakis** [comment] 2015-04-01 22:23
To elaborate, the type of `x` and `y` should be enough to precisely identify the code that's about to run, but here the types of two distinct versions of `bar` are considered compatible. Not good! This works out ok because we're still encoding the fn pointer anyway.

**Comment by nikomatsakis** [comment] 2015-04-01 22:24
Put another way, the type of a fn item ought to have the values for all of its substs (sort of like `bar<u32>` vs `bar<i32>`). But the compiler is currently representing them as something like `fn() {bar}` -- that is, the fn signature plus a def-id.

**Comment by nikomatsakis** [comment] 2015-04-01 22:26
Nominating. Not sure how seriously to take this (but probably not that hard to fix).

**Comment by pnkfelix** [comment] 2015-04-02 21:16
Classifying even the type-system issue as a "bug that needs fixing" -- thus we can afford to leave this as P-high, not a 1.0-blocker.

**Comment by nikomatsakis** [comment] 2015-04-02 21:22
Tagging as P-backcompat-lang since compiler incorrectly accepts things it shouldn't accept.

**Comment by nikomatsakis** [comment] 2016-01-14 21:11
Another example from #23733: https://github.com/rust-lang/rust/issues/23733#issue-64556029

**Comment by nikomatsakis** [comment] 2016-06-09 20:48
re-opening to serve as a B-unstable issue

**Comment by brson** [comment] 2016-06-25 01:43
@nikomatsakis Changing the lint to deny seems smart. If I understand, then people building their own stuff will get a more aggressive admonition, but their deps won't fail. Do we also have the ability to get the change in that displays future-incompatible lints despite --cap-lints? That would make sure both types of user see the problem.

**Comment by nikomatsakis** [comment] 2016-07-01 15:55
>  Do we also have the ability to get the change in that displays future-incompatible lints despite --cap-lints?

Yes, we should open an issue about this. It's just a matter of writing a PR.

**Comment by brson** [comment] 2016-07-14 16:14
Triage: still blocked on turning the lint to deny https://github.com/rust-lang/rust/issues/34198

**Comment by alexcrichton** [comment] 2016-07-14 16:15
Updated title to reflect pending work to be done

**Comment by brson** [comment] 2016-09-13 17:04
Deny by default now. Only waiting to make it a non-lint.

**Comment by eddyb** [comment] 2017-01-05 01:33
I've [done a new crater run](https://github.com/rust-lang/rust/pull/34198#issuecomment-270539076) and it looks better. Also it's been a while, might as well wrap this up.
@rfcbot fcp merge

**Comment by nikomatsakis** [comment] 2017-01-05 19:02
I have to admit that I I continue to wonder if we should just define the behavior of `transmute` in this case to be that it reifies into a fn ptr. It's a very useful kind of conversion. Alternatively, is there some other more concise syntax we could use for it? In those cases where I've needed to re-ify into a fn-ptr, I've been annoyed that the existing syntax requires (e.g.) naming the number of arguments that the fn takes (though I think there are some conversions, such as casting to a ptr, that work?)

**Comment by eddyb** [comment] 2017-01-05 19:11
@nikomatsakis You shouldn't need to transmute if you set up your FFI proxies correctly.
As for the casts, I'd like `fn(...) -> _` but it sort of requires a minimum level of support for variadic generics (in the compiler, not necessarily exposed to the language).

**Comment by pnkfelix** [comment] 2017-01-05 21:27
@eddyb what does it mean to fcp merge this issue? Does it mean we are closing it but declaring the work done? (as opposed to the usual "close" which usually means "we are not going to do this proposed thing right now")?

**Comment by eddyb** [comment] 2017-01-05 22:06
Closing it as in "this has been fully implemented".

**Comment by glaebhoerl** [comment] 2017-01-06 10:34
> I have to admit that I I continue to wonder if we should just define the behavior of transmute in this case to be that it reifies into a fn ptr. It's a very useful kind of conversion. 

The latter point may be true, but `transmute` doing anything besides actual bit-for-bit transmuting feels very wrong to me.

**Comment by nikomatsakis** [comment] 2017-01-07 01:07
> The latter point may be true, but transmute doing anything besides actual bit-for-bit transmuting feels very wrong to me.

Yeah...I know.

**Comment by nikomatsakis** [comment] 2017-01-10 18:28
cc @pnkfelix and @withoutboats -- your thoughts here?

**Comment by withoutboats** [comment] 2017-01-10 21:11
@nikomatsakis can't you always `as` cast? Is making `transmute` just about convenience? I wouldn't like to add special cases to something as unsafe as `transmute` just for convenience.

**Comment by nikomatsakis** [comment] 2017-01-10 22:08
@withoutboats you can, indeed. In any case, the proposal is to *remove* the special case from transmute (and hence you will get a hard error).

What I am saying is merely that I would like a more concise syntax here, since when you actually have to write (e.g.) `x as fn(_, _) -> _` that is pretty long and annoying. My particular problem arose in a macro, where I also didn't have the type readily on hand. 

-----

@eddyb -- one thing, though it has more to do w/ the PR than this, I think we should make sure to give a very clear error message, along with a suggestion of what to write instead.

**Comment by withoutboats** [comment] 2017-01-10 22:34
@rfcbot reviewed

> you can, indeed. ... What I am saying is merely that I would like a more concise syntax here

Sounds reasonable, just wanted to make sure I understand that this special case is just about concision & not expressibility.

**Comment by eddyb** [comment] 2017-01-10 23:15
@nikomatsakis In that case, we have to keep the special-casing code where we're not emitting the lint.
At least it'd still be an error and trans would stay clean.

**Comment by nikomatsakis** [comment] 2017-01-11 17:18
@eddyb 

> In that case, we have to keep the special-casing code where we're not emitting the lint.

Yes, such is life. I left a comment in the PR.

**Comment by nikomatsakis** [comment] 2017-01-11 17:18
Basically nice errors == special-case code. =)

**Comment by pnkfelix** [comment] 2017-01-12 22:17
@rfcbot reviewed

**Comment by nikomatsakis** [comment] 2017-01-17 16:18
It seems that @rfcbot went on vacation. I will put this into Final Comment Period manually:

### 🔔 Hear ye, hear ye! This issue is now entering final comment period. 🔔 

The intention is to convert this forward compatibility warning into a hard error.

**Comment by nikomatsakis** [comment] 2017-02-17 22:49
Although the FCP is complete, the change has not been finalized, and I want to float one possible tweak to the rules that might go a long way to eliminating the annoyance that these rules can cause. Each function has a unique type, but we could make the unique types for `extern "C"` functions have he size of a pointer, and only make `extern "Rust"` functions be zero-sized. After all, a common time to send pointers is in FFI.

**Comment by wycats** [comment] 2017-02-17 22:59
I raised this with @nikomatsakis privately because this broke a significant amount of code I wrote that I just came back to after a number of months.

In my view `extern "C" fn` is more or less equivalent to `repr(C)`, and means something like: "a function intended to be called using the C ABI." In general, C code is calling functions using the C ABI, and C code also requires an actual pointer in order to work.

While there may be some cases of extern "C" functions that are only ever called from Rust, this seems exceedingly rare compared to extern "C" functions meant to be called from C. I think of `extern "C"` as more or less the `#[repr(C)]` of functions, and pointers are part of the C representation in such an exceedingly large % of cases that the extra type-cast we're imposing here seems inappropriate.

**Comment by eddyb** [comment] 2017-02-17 23:15
@wycats You should never need the `transmute` in the first place, except when dealing with variadics (and we could even add coercions for those!).

**Comment by wycats** [comment] 2017-02-18 00:07
@eddyb you don't need the transmute because you can do a manual cast?

**Comment by eddyb** [comment] 2017-02-18 00:17
`transmute` is not something you should *ever* touch, unless there is no other way.

I suppose we should've been stricter and not allow many type combinations, where a better option exists.

**Closed** 2017-03-01 11:59 UTC
Labels: A-codegen, B-unstable, final-comment-period, P-medium, T-compiler, T-lang

**Comment by nikomatsakis** [comment] 2017-03-02 18:07
My take on this [proposal that I floated earlier](https://github.com/rust-lang/rust/issues/19925#issuecomment-280787992):

I still think it's worth considering making `extern "C"` fn types not be zero-sized, but it seems like it ought to go through an RFC, and there is no reason for that decision to affect the FCP of this particular issue.

**Comment by wagenet** [comment] 2017-04-11 21:17
The main thing that makes me sad about this is that it seems like a regression. Code that used to work now breaks without a major version change. At least there is a workaround.
