### ISSUE TITLE
ICE: Generic type alias to invalid type crashes during type check on latest stable

### ISSUE THREAD

**Issue by RustyYato** [rust-lang/rust#62742] opened 2019-07-17 05:04 UTC
This also crashes on the latest nightly

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0d49e84d11fd24aa8d24c1da1be6a428)

```rust
use std::marker::PhantomData;

fn _alias_check() {
    WrongImpl::foo(0i32);       // crash
    WrongImpl::<()>::foo(0i32); // fine
    CorrectImpl::foo(0i32);     // fine
}

pub trait Raw<T: ?Sized> {
    type Value;
}

pub type WrongImpl<T> = SafeImpl<T, RawImpl<T>>;

pub type CorrectImpl<T> = SafeImpl<[T], RawImpl<T>>;

pub struct RawImpl<T>(PhantomData<T>);

impl<T> Raw<[T]> for RawImpl<T> {
    type Value = T;
}

pub struct SafeImpl<T: ?Sized, A: Raw<T>>(PhantomData<(A, T)>);

impl<T: ?Sized, A: Raw<T>> SafeImpl<T, A> {
    pub fn foo(value: A::Value) {}
}

```

**Comment by hellow554** [comment] 2019-07-17 09:14
Backtrace: 

```

**Comment by lqd** [comment] 2019-07-17 12:09
This started ICE-ing in 1.27. The first nightly where it's present seems to be `nightly-2018-04-28` (there were a lot of missing nightlies in april 2018). Unfortunately there are no available CI artifacts for these old commits to automatically bisect to a PR.

<details>
<summary>Backtrace on nightly-2018-04-28</summary>

```
error: internal compiler error: librustc/traits/select.rs:3121: Impl DefId(0/0:10 ~ foo[9294]::{{impl}}[0]) was matchable against Obligation(predicate=Binder(TraitPredicate(<RawImpl<_> as Raw<_>>)),depth=0) but now is not

thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:546:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:205
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:461
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::session::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::session::opt_span_bug_fmt
  13: rustc::session::bug_fmt
  14: rustc::traits::select::SelectionContext::confirm_candidate
  15: rustc::traits::select::SelectionContext::select
  16: <rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
  17: <rustc::traits::fulfill::FulfillmentContext<'tcx> as rustc::traits::engine::TraitEngine<'tcx>>::select_where_possible
  18: rustc_typeck::check::FnCtxt::select_obligations_where_possible
  19: rustc_typeck::check::FnCtxt::structurally_resolved_type
  20: rustc_typeck::check::FnCtxt::check_expr_kind
  21: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  22: rustc_typeck::check::FnCtxt::check_block_with_expected
  23: rustc_typeck::check::FnCtxt::check_expr_kind
  24: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_needs
  25: rustc_typeck::check::FnCtxt::check_return_expr
  26: rustc_typeck::check::check_fn
  27: rustc::ty::context::tls::with_related_context
  28: rustc::infer::InferCtxtBuilder::enter
  29: rustc_typeck::check::typeck_tables_of
  30: rustc::ty::maps::<impl rustc::ty::maps::config::QueryConfig<'tcx> for rustc::ty::maps::queries::typeck_tables_of<'tcx>>::compute
  31: rustc::ty::context::tls::with_context
  32: rustc::dep_graph::graph::DepGraph::with_task_impl
  33: rustc::ty::context::tls::with_related_context
  34: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  35: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  36: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::ensure_query
  37: rustc::session::Session::track_errors
  38: rustc_typeck::check::typeck_item_bodies
  39: rustc::ty::context::tls::with_context
  40: rustc::dep_graph::graph::DepGraph::with_task_impl
  41: rustc::ty::context::tls::with_related_context
  42: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  43: rustc::ty::maps::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  44: rustc_typeck::check_crate
  45: rustc::ty::context::tls::enter_context
  46: <std::thread::local::LocalKey<T>>::with
  47: rustc::ty::context::TyCtxt::create_and_enter
  48: rustc_driver::driver::compile_input
  49: rustc_driver::run_compiler_impl
  50: syntax::with_globals
query stack during panic:
#0 [typeck_tables_of] processing `_alias_check`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.27.0-nightly (686d0ae13 2018-04-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```
</details>

A somewhat liberal range of bors commits from April 26 to 27 (in order to avoid TZ differences as to when the nightly is cut), in reverse chronological order:

- commit ff65726ebf1d7d732e24175a41381e53f39ee892 - #50155 ('label can start expressions)
- commit 207bc403799e4a8a04f873be94834ccc09c1412b - #49826 (rustc_driver: Catch ICEs on the main thread too)
- commit 1eb0cef62b3e83bf7ce6bc7d1b99e130648a55e8 - #50149 (Added warning for unused arithmetic expressions)
- commit ede7f94794213187b7d8984fdd24be6eb6106b96 - #49822 (Access individual fields of tuples, closures and generators on drop)
- commit 686d0ae137b1d66711694903607750ad54f60f69 a rollup of 9 other PRs
  - #49858 (std: Mark `ptr::Unique` with `#[doc(hidden)]`)
  - #49968 (Stabilize dyn trait)
  - #50192 (Add some utilities to `libsyntax`)
  - #50251 (rustc: Disable threads in LLD for wasm)
  - #50263 (rustc: Emit `uwtable` for allocator shims)
  - #50269 (Update `parking_lot` dependencies)
  - #50273 (Allow #[inline] on closures)
  - #50284 (fix search load page failure)
  - #50257 (Don't ICE on tuple struct ctor with incorrect arg count)
- commit a9975254ee6510cd1360417d3d145b56fb70b2e7 - #50137 (Remove hack around comparisons of i1 values)
- commit 3c43aa5677e17dfb9f5004522745a02e21a604a4 - #50102 (Move query code outside macros and store query jobs separately from query results)
- commit 71d3dac4a86d192c2c80948621859da3b363fa50 - #50097 (Partial future-proofing for Box<T, A>)
- commit ada45fd49a2dfcf2a163e1f4641ac34f2803eb9b a rollup of 7 other PRs
  - #49707 (Add "the Rustc book")
  - #50222 (Bump bootstrap compiler to 2018-04-24)
  - #50227 (Fix ICE with erroneous `impl Trait` in a trait impl)
  - #50229 (Add setting to go to item if there is only one result)
  - #50231 (Add more doc aliases)
  - #50246 (Make dump_{alloc,allocs,local}() no-ops when tracing is disabled.)
  - #49894 (Rename InternedString to LocalInternedString and introduce a new thread-safe InternedString)
- commit 9822b5709ca78d6398e9ae609de0181116e8b0db - #49891 (compiletest: detect non-ICE compiler panics) 
- commit 8a09bc6a77a908b11120cb09e6d2bf0b7a13494e - #48995 (Create a canonical trait query for `evaluate_obligation` ) <- **this one looks interesting**
- commit e05b78daa628ad88952d856c68cb5708434fa934 - #49420 (Use ScalarPair for tagged enums)
- commit 7d8f0e22f574c7ffb4b6544cc96c066b7de3b6be - #50253 (drop elaboration should reveal all)
- commit 7f3444e1baf0d335b4bf379f845dbc28cdd0509c - #49513 (Treat repr(Rust) univariant fieldless enums as ZSTs)
- commit 949010d23e9f7037a8e6f323588873b3d2438fb1 - #50228 (Rename rustc_back to rustc_target and move ABI code to it)

In particular #48995 may be related, "a new canonical trait query for `evaluate_obligation` in the trait selector".

**Comment by pnkfelix** [comment] 2019-09-26 13:47
visiting for triage: @nikomatsakis do you plan to investigate or delegate in near term?

**Comment by pnkfelix** [comment] 2019-10-03 13:32
nominating for reassignment.

**Comment by nikomatsakis** [comment] 2019-10-03 13:56
I can look at it, although maybe @tmandry might be a good fit, too.

**Comment by nikomatsakis** [comment] 2019-10-09 15:50
OK, I put some work into investigation here. I at least see what is going wrong, and actually the fix I *suspect* is a refactoring that I've been considering for some time, but which I think has been blocked on getting rid of the leak-check (so cc https://github.com/rust-lang/rust/pull/65232).

The problem is that, the way our type checker works, when we have a subtyping relationship `$1 <: $2` between two inference variables, we record this in a kind of "side-table" called the `sub_relations`. The two type variables therefore are not *equated* exactly -- *but*, once we know one of them, we do learn a lot about the other. So what happens is that when we equate `$1` with some type (say `&'a u32`) then we go and instantiate `$2` to be equal to  *a variation* of `$1`. Specifically, a variation in which all lifetimes are replaced with variables: `&'b u32`, you might say. Then we relate `$1` and `$2`, which gives rise to a region constraint (in this case, `'a: 'b`). OK, so far so good.

Now the problem is that when we do our canonicalization, even though `$1` and `$2` are in some way related, we have to treat them as independent variables. So we canonicalize them to fresh independent variables. *Then* we go and evaluate which impl will apply. In this case, it's the impl providing `RawImpl<T>: Raw<[T]>`. So we get back a result that's like "yep there is only one option and it is `$1 = $3` and `$2 = [$3]`".

OK, so then we go and apply that result to our actual variables. But remember that we had a subtyping relationship between `$1` and `$2`. So now we wind up with:

```
$1 <: $2 (from before)
$1 = $3
$2 = [$3]
```

which together implies that `$3 <: [$3]`. This is, of course, impossible. 

As it happens, we (sort of) detect this when we are "generalizing" `$2`. We walk down the type we are generalizing from (`[$3]`) and we encounter the type variable `$3`, which we see is "related" to `$2` via some chain of equality and subtyping. We then fail because of our version of the occurs check. Thus unification fails, which then causes the ICE that we see (because we expected unification to succeed).

Here are some of the solutions I think we could do here:

* Instead of making unification fail we could generate a constraint that will eventually lead to an error.
* We could handle `$1 <: $2` constraints by generating an *obligation* instead -- but for this to work, we can't have the leak-check around (or, at least, we can only do it for variables in the root universe I think). This is because the obligation needs to be passed back out from unification. If we took that approach, though, we'd be able to successfully unify `$1` with `$3` and `$2` with `[$3]`, and we'd only fail *later* when we tried to make `$3` a subtype of `[$3]` (in the same way, with the occurs check).

I think I favor the second half. I've been steadily trying to maneuver our type system implementation into a combination of two things:

* Straight-up HM variables, that are instantiated once with firm equality.
* A list of pending obligations for things where we can't make progress immediately (e.g. because of ambiguity that may later be resolved).

The current "sub relations" list is basically a third bullet, and it's kind of a special case of the pending obligations. The ICE we're seeing *here* is precisely arising because of the "canonicalization" system assumes that it can treat unbound variables as independent things from one another. Right now, we can't because of these implicit links due to subtyping.

**Closed** 2022-03-30 07:45 UTC
Labels: I-ICE, A-traits, P-high, T-compiler, regression-from-stable-to-stable, C-bug, WG-traits, glacier
