### ISSUE TITLE
The Copy trait is not listed for numeric types in the docs

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#35587] opened 2016-08-11 08:20 UTC
The Copy trait is missing in the Trait Implementations list in the docs for numeric types.

**Comment by steveklabnik** [comment] 2016-08-11 16:56
This is a duplicate of https://github.com/rust-lang/rust/issues/25893, but thank you for filing!

**Closed by steveklabnik** 2016-08-11 16:56 UTC
