### ISSUE TITLE
internal compiler error on 1.4.0-dev for i686-pc-windows-gnu

### ISSUE THREAD

**Issue by hebiyan** [rust-lang/rust#28330] opened 2015-09-10 06:21 UTC
I tried the cross-compilation for windows following procedures on this page.
[Using Rust in Wine as a sort of cross-compiler](https://gist.github.com/vi/883cacf09b57a8efe5bf)
In procedure No.3, I got an internal compiler error, like that.

```bash
$ RUST_BACKTRACE=1 /opt/local/bin/rustc -C linker=~/bin/gccwrapper --target i686-pc-windows-gnu test_cross/src/main.rs
ERROR:rbml::reader: failed to find block with tag 42
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', src/librbml/lib.rs:395

stack backtrace:
   1:        0x10f6db7d0 - sys::backtrace::write::h0ea7f1ad16e01eccyws
   2:        0x10f6e3a11 - panicking::on_panic::h379fbd8c51aa2800zax
   3:        0x10f6a6dc2 - rt::unwind::begin_unwind_inner::hb3f98c57aa903034AFw
   4:        0x10d1e02b1 - rt::unwind::begin_unwind::h648568158182350437
   5:        0x10d1df2f4 - reader::get_doc::he259aa1da79cbfd9Uxa
   6:        0x10cb68e5d - metadata::decoder::maybe_find_item::hf4465569b8ff552eaNl
   7:        0x10c498389 - build_reduced_graph::GraphBuilder<'a, 'b, 'tcx>::build_reduced_graph_for_item::had31c837b6364e7dzTa
   8:        0x10c49162d - build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'tcx>.Visitor<'v>::visit_item::h9a84b2e6d58d436dZOb
   9:        0x10c4e385a - resolve_crate::hada88c87e9d82554lAi
  10:        0x10bf5924e - driver::phase_3_run_analysis_passes::h12044922019249132164
  11:        0x10bf41dbe - driver::compile_input::h6c18fff0f1b2d2f0Tba
  12:        0x10c01f4de - run_compiler::h8975c965a3c80d57C7b
  13:        0x10c01d0cb - boxed::F.FnBox<A>::call_box::h16703694798583564538
  14:        0x10c01ca22 - rt::unwind::try::try_fn::h4176919178098321010
  15:        0x10f6e35b8 - __rust_try
  16:        0x10f6cf720 - rt::unwind::try::inner_try::h2ffe5455c537fcc6tBw
  17:        0x10c01cbe2 - boxed::F.FnBox<A>::call_box::h17058068182401607193
  18:        0x10f6e286d - sys::thread::Thread::new::thread_start::h712a2cf4f5ecb71aOZv
  19:     0x7fff81505059 - _pthread_body
  20:     0x7fff81504fd6 - _pthread_start
```
(Directory named 'test_cross' made by "cargo new test_cross --bin")

I'm using Mac OS X Yosemite 10.10.5.

rustc version:
```bash
$ /opt/local/bin/rustc -vV
rustc 1.4.0-dev (5aca49c69 2015-08-10)
binary: rustc
commit-hash: 5aca49c693c9be3064d9e6db9473b1fa76834b79
commit-date: 2015-08-10
host: x86_64-apple-darwin
release: 1.4.0-dev
```

Sorry for poor my english. 
Thank you.

**Comment by alexcrichton** [comment] 2015-09-10 17:19
Currently the compiler can't link against artifacts produced by a different version of the compiler, so it may be the case that the libraries for `i686-pc-windows-gnu` are produced by a different version than `5aca49c69` (the host compiler). Syncing the two together should cause this to go away.

**Comment by alexcrichton** [comment] 2015-09-10 17:20
Otherwise though I believe this is a dupe of #27645 so closing in favor of that.

**Closed by alexcrichton** 2015-09-10 17:20 UTC
