### ISSUE TITLE
Cargo install failing in rustlang/rust:nightly image (1.83.0)

### ISSUE THREAD

**Issue by Vikari** [rust-lang/rust#130813] opened 2024-09-25 06:58 UTC
The compiler unexpectedly panicked. this is a bug. When running `cargo install --path .` in `rustlang/rust:nightly` image.

Error file attached.

[rustc-panic.txt](https://github.com/user-attachments/files/17126460/rustc-panic.txt)

```
compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C strip=debuginfo

error: could not compile `http-body` (lib)

Caused by:
  process didn't exit successfully: `/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name http_body --edition=2018 /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/http-body-0.4.6/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=281 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values())' -C metadata=82a59836d3af2aec -C extra-filename=-82a59836d3af2aec --out-dir /usr/src/app/target/release/deps -C strip=debuginfo -L dependency=/usr/src/app/target/release/deps --extern bytes=/usr/src/app/target/release/deps/libbytes-6e7a8737cc65033e.rmeta --extern http=/usr/src/app/target/release/deps/libhttp-6fcad499b8642d62.rmeta --extern pin_project_lite=/usr/src/app/target/release/deps/libpin_project_lite-919c6a70ea62ed97.rmeta --cap-lints allow` (exit status: 101)
```

**Comment by theemathas** [comment] 2024-09-25 06:59
Duplicate of #130769

**Closed** 2024-09-25 07:38 UTC
Labels: needs-triage
