### ISSUE TITLE
Error building rust with -g

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#20798] opened 2015-01-09 07:08 UTC
```
rustc: /home/rustbuild/src/rust-buildbot/slave/snap3-linux/build/src/llvm/lib/IR/DebugInfo.cpp:159: uint64_t llvm::DIVariable::getPieceOffset() const: Assertion `isVariablePiece()' failed.
Aborted (core dumped)
make: *** [x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_typeck] Error 134
```

(I was running ` RUSTFLAGS="-g" CFG_RUSTC_FLAGS="-g" make -j4`, since I forgot which flag works)

I get the same error even after a make clean.

**Comment by huonw** [comment] 2015-01-09 07:32
cc @michaelwoerister

**Comment by michaelwoerister** [comment] 2015-01-09 16:46
Seems to be something related to the recent LLVM updates. It's on my radar.

**Comment by michaelwoerister** [comment] 2015-02-04 12:57
Update: It's like that this particular assertion failure has been resolved by the recent LLVM update. However, I'm hitting a new error now, which seems to be a regression of https://github.com/rust-lang/rust/issues/17201. I'm looking into it right now.

**Comment by michaelwoerister** [comment] 2015-02-04 14:09
:clap: **Alright!** :+1:
With a quick and dirty fix assigning debug locations to lang-time call instructions the regression is gone and `isVariablePiece()` assertion too. It'll take some time to implement a clean fix but then this issue should be solved.

**Comment by steveklabnik** [comment] 2015-02-04 23:17
:confetti_ball:

**Closed** 2015-02-08 12:35 UTC
Labels: A-debuginfo
