### ISSUE TITLE
range notation with for expression `for i in 0 .. n {}` should be parsed as `for i in (0 .. n) {}`

### ISSUE THREAD

**Issue by mandel59** [rust-lang/rust#20921] opened 2015-01-11 05:43 UTC
The problem is that `for i in 0 .. n {}` is ambiguous between `for i in (0 .. n) {}` and `for i in 0 .. (n {})` for consistency.

```rust
fn main() {
    let n = 10;
    
    for i in 0..n {
        println!("{}", i);
    }
}
```

This code yields:

```
% rustc ambiguous.rs
ambiguous.rs:5:16: 5:17 error: expected `:`, found `!`
ambiguous.rs:5         println!("{}", i);
                              ^
```

While these codes pass:

```rust
fn main() {
    for i in 0..10 {
        println!("{}", i);
    }
}
```

```rust
fn main() {
    let mut n = 0..10;
    for i in n {
        println!("{}", i);
    }
}
```

**Comment by csouth3** [comment] 2015-01-11 06:23
possibly related to #20811?

**Comment by Gankro** [comment] 2015-01-11 15:54
Particularly nasty dupe of #20811

**Closed by Gankro** 2015-01-11 15:54 UTC
