### ISSUE TITLE
HashMap Entry lifetime and lookup issues

### ISSUE THREAD

**Issue by beefucurry** [rust-lang/rust#66977] opened 2019-12-03 00:28 UTC
I think the lifetime on the get() function of std::collections::hash_map::OccupiedEntry isn't right.  It is currently defined as

    impl<'a, K, V> OccupiedEntry<'a, K, V> {
        pub fn get(&self) -> &V {}
    }

but it should be 

     -> &'a V {}

because the returned value is owned by the table, not by the Entry.  It looks like the difficulty for this is deeper in the source code, in https://github.com/rust-lang/hashbrown/blob/master/src/rustc_entry.rs it shows

    pub struct RustcOccupiedEntry<'a, K, V> {
        key: Option<K>,
        elem: Bucket<(K, V)>,
       table: &'a mut RawTable<(K, V)>,
    }

    pub fn get(&self) -> &V {
        unsafe { &self.elem.as_ref().1 }
    }

This has to be some kind of problem, as it is returning data from 'elem:Bucket', but elem is not requiring a lifetime 'a.  The Bucket datatype is just a wrapper around a const raw pointer with no lifetime annotations.  And then there is this piece of code

    pub unsafe fn as_mut<'a>(&self) -> &'a mut T {
        &mut *self.as_ptr()
    }
    pub unsafe fn as_ptr(&self) -> *mut T {
        if mem::size_of::<T>() == 0 {
            // Just return an arbitrary ZST pointer which is properly aligned
            mem::align_of::<T>() as *mut T
        } else {
            self.ptr as *mut T
        }
    }
which is derereferencing the 'ptr' inside the bucket , then assigning a lifetime of 'a to that pointer somehow (how is this even allowed?)  .  Anyway this issue seems really deep; so, one would almost certainly need a maintainer of that library to look at, casuals like me would certainly break something if I tried.  Maybe I'm misunderstanding OccupiedEntry, I thought it was just supposed to be a pointer into the table where the data goes so you can modify it without rehashing and redoing the lookup.  All this extra stuff seems bizarrely unnecessary.

**Comment by rodrimati1992** [comment] 2019-12-03 07:31
The problem with changing it to `pub fn get(&self) -> &'a V` is demonstrated in this playground:

https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=03e8037b50759334b5d19045e9b0b679

You can cause a undefined behavior,because with that function signature nothing prevents you from getting both a `&mut V` and a `&'a V` to the same entry.

**Comment by jonas-schievink** [comment] 2019-12-03 10:31
This seems to be working as intended then?

**Comment by rodrimati1992** [comment] 2019-12-03 10:40
Yeah,it's working as intended.
You could sugest a wrapper type like `struct SharedEntry<'a,K,V>(OccupiedEntry<'a,K,V>)`,that doesn't allow you to call `get_mut` or `into_mut`,and in that case it would be sound to define such a method for the wrapper type.

**Comment by steveklabnik** [comment] 2020-10-30 18:02
Triage: it appears this isn't a bug, and so normally I'd close it, but it seems like @jonas-schievink has it tracked as a feature request, but it's not 100% clear to me what that feature would be.

**Comment by Dylan-DPC** [comment] 2023-12-14 14:37
Closing this as it's not a bug, and there's no clear proposal made (which may be better suited for another issue for easier traction)

**Closed by Dylan-DPC** 2023-12-14 14:37 UTC
Labels: A-collections, T-libs-api, C-feature-request

**Comment by SteveLauC** [comment] 2024-12-23 03:09
> The problem with changing it to `pub fn get(&self) -> &'a V` is demonstrated in this playground:
> 
> https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=03e8037b50759334b5d19045e9b0b679
> 
> You can cause a undefined behavior,because with that function signature nothing prevents you from getting both a `&mut V` and a `&'a V` to the same entry.


What if we change the lifetime of `&self` to `&'a self`:

```rust
use std::collections::hash_map::{Entry, HashMap, OccupiedEntry};

trait OccupiedEntryExt<'a>: 'a {
    type Value: 'a;
    fn get_ll(&'a self) -> &'a Self::Value;
}

impl<'a, K, V> OccupiedEntryExt<'a> for OccupiedEntry<'a, K, V> {
    type Value = V;

    fn get_ll(&'a self) -> &'a V 
    {
        self.get()
    }
}

fn main() {
    let mut map = HashMap::new();
    map.insert(0, vec![4]);

    let mut occupied = match map.entry(0) {
        Entry::Occupied(occupied) => occupied,
        Entry::Vacant { .. } => unreachable!(),
    };

    let reference = occupied.get_ll();
    let mut_reference = occupied.get_mut();
    // error[E0502]: cannot borrow `occupied` as mutable because it is also borrowed as immutable

    // Both a mutable reference and a regular reference to the same entry at the same time.
    assert_eq!(
        dbg!(mut_reference as *mut _ as usize),
        dbg!(reference as *const _ as usize),
    );
}
```
