### ISSUE TITLE
rustc will rapidly eat your memory with `#[tokio::main]` macro and `"\ "` on 1.50 stable

### ISSUE THREAD

**Issue by MarkDDR** [rust-lang/rust#82437] opened 2021-02-23 09:29 UTC
In `Cargo.toml`, add the following dependency
```toml
tokio = { version = "1.2.0", features = ["macros"] }
```

In `src/main.rs`, have the following

```rust
#[tokio::main]
async fn main() {
    let _backslash_space = "\ ";
}
```
Then try to compile with either `cargo check` or `cargo build`

Example repo here: https://github.com/MarkDDR/rustc_backslash_space

### I expected to see this happen:
Compiler ends with error about invalid escape sequence then exits

### Instead, this happened:
Compiler gives the error about invalid escape sequence but then hangs and rapidly eats memory until eventually OoM killer kills it (or you hit Ctrl+C). This eats at least 32GB of memory

### Meta
From my testing, only stable 1.50 is effected. Current beta and nightly channels don't experience this issue

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0

```

**Comment by camelid** [comment] 2021-02-24 04:05
I can reproduce this [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ce873fad3033cbcbf58afde809dab374); it exits after a few seconds with SIGKILL, presumably because the playground has limited memory.

Given this is fixed on beta and nightly, should this be a `T-release` issue rather than `T-compiler`? Probably this should just be closed since it will be fixed in the next release.

**Comment by camelid** [comment] 2021-02-24 04:07
Replacing `T-compiler` with `T-release`, nominating, and de-`I-prioritize`ing.

@rustbot label: -T-compiler +T-release, +I-nominated, -I-prioritize

**Comment by spastorino** [comment] 2021-02-27 13:17
> I can reproduce this [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ce873fad3033cbcbf58afde809dab374); it exits after a few seconds with SIGKILL, presumably because the playground has limited memory.
> 
> Given this is fixed on beta and nightly, should this be a `T-release` issue rather than `T-compiler`? Probably this should just be closed since it will be fixed in the next release.

we were discussing this issue with @apiraino and unless for some reason somebody considers this as `P-critical` or there's some severe implication on this as you've said this is fixed on beta. We were not able with @apiraino to reproduce this using cargo-bisect-rustc because this doesn't reproduce on any nightly. I guess some condition on stable + some stable backport is what causes this behavior.

**Comment by Mark-Simulacrum** [comment] 2021-03-12 16:36
Yes, I'm going to go ahead and close as fixed.

**Closed by Mark-Simulacrum** 2021-03-12 16:36 UTC
Labels: A-proc-macros, C-bug, E-needs-bisection, I-compilemem, I-hang
