### ISSUE TITLE
ICE when referencing associated const within struct itself.

### ISSUE THREAD

**Issue by Mr-Byte** [rust-lang/rust#26246] opened 2015-06-12 15:48 UTC
The following code on the current nightly produces an ICE:

```rust
#![feature(associated_consts)]

struct Test {
    _x: [u32; Test::ARRAY_SIZE]
}

impl Test {
    const ARRAY_SIZE: usize = 4;
}

fn main() {}
```

The compiler outputs the following:
```
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'path not fully resolved: PathResolution { base_def: DefTy(DefId { krate: 0, node: 4 }, false), last_private: LastMod(AllPublic), depth: 1 }', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc/middle/def.rs:81
```

**Comment by quantheory** [comment] 2015-06-18 17:51
Duplicate of #25145, I think. The recursion here is actually not necessary to trigger an error.

**Closed** 2015-06-18 20:58 UTC
Labels: I-ICE
