### ISSUE TITLE
Error: implementation of `std::iter::Iterator` is not general enough

### ISSUE THREAD

**Issue by andreytkachenko** [rust-lang/rust#72167] opened 2020-05-13 08:27 UTC
I tried this code:
```rust
use futures::stream::StreamExt; 
async fn test() {
    let data = std::sync::Arc::new(vec![1i32,2,3,4]);
    
    tokio::spawn(async move {
        futures::stream::iter(data.iter())
            .map(|_| async move {
                12i32
            })
            .buffer_unordered(32usize)
            .collect::<Vec<_>>()
            .await;
    });
}
```

I expected to see this happen:  compiled

Instead, this happened: compilation failed with error:
```
error: implementation of `std::iter::Iterator` is not general enough
    --> src/main.rs:9:5
     |
9    |       tokio::spawn(async move {
     |       ^^^^^^^^^^^^ implementation of `std::iter::Iterator` is not general enough
     |
     = note: `std::iter::Iterator` would have to be implemented for the type `std::slice::Iter<'0, i32>`, for any lifetime `'0`...
     = note: ...but `std::iter::Iterator` is actually implemented for the type `std::slice::Iter<'1, i32>`, for some specific lifetime `'1`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-unknown-linux-gnu
release: 1.43.0
LLVM version: 9.0

```
<details>
<summary>Notes</summary>
<p>
This code compiles:

```rust
use futures::stream::{Stream, StreamExt};
use std::future::Future;

fn make_stream<'a>(i: std::slice::Iter<'a, i32>) -> impl Future<Output = Vec<i32>> + 'a {
    futures::stream::iter(i)
        .map(|_| async move { 12i32 })
        .buffer_unordered(32usize)
        .collect::<Vec<i32>>()
}

async fn test() {
    tokio::spawn(async move {
        let data = vec![1i32, 2, 3, 4];
        make_stream(data.iter()).await;
    });
}
```
</p>
</details>

**Comment by jonas-schievink** [comment] 2020-05-13 09:44
Duplicate of https://github.com/rust-lang/rust/issues/71671

**Closed by jonas-schievink** 2020-05-13 09:44 UTC
Labels: C-bug
