### ISSUE TITLE
compile async await function error

### ISSUE THREAD

**Issue by Brooooooklyn** [rust-lang/rust#53989] opened 2018-09-06 10:54 UTC
Error message:
`error: internal compiler error: librustc/infer/region_constraints/mod.rs:659: cannot relate bound region: ReLateBound(DebruijnIndex(1), BrAnon(2)) <= '_#0r`

Backtrace:

```bash
thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:525:9
query stack during panic:
#0 [evaluate_obligation] evaluating trait selection obligation `impl std::future::Future: std::marker::Send`
#1 [typeck_tables_of] processing `main`
#2 [typeck_tables_of] processing `main::{{closure}}`
#3 [type_of] processing `main::{{closure}}`
end of query stack
error: aborting due to previous error
```

**Comment by cramertj** [comment] 2019-02-22 16:14
Closing as duplicate of #57084.

**Closed by cramertj** 2019-02-22 16:14 UTC
Labels: A-async-await, I-ICE
