### ISSUE TITLE
Compiler error while building matrixmultiply with rust 1.20 nightly

### ISSUE THREAD

**Issue by delehef** [rust-lang/rust#43452] opened 2017-07-24 13:19 UTC
Compiler error while building [matrixmultiply](https://crates.io/crates/matrixmultiply) 0.1.13

I tried to compile a project having `matricmultuply` in its dependencies using rust 1.20 nightly

This happened:

```
   Compiling matrixmultiply v0.1.13
error: internal compiler error: /checkout/src/librustc/infer/mod.rs:573: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<K as kernel::GemmKernel>)),depth=0),Unimplemented)]` resolving bounds after type-checking

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.20.0-nightly (afe145d22 2017-07-23) running on x86_64-unknown-linux-gnu

note: run with `RUST_BACKTRACE=1` for a backtrace
```

## Meta

`rustc --version --verbose`:
```
rustc 1.20.0-nightly (afe145d22 2017-07-23)
binary: rustc
commit-hash: afe145d227c5739ec5305f6b5352230a58ebb029
commit-date: 2017-07-23
host: x86_64-unknown-linux-gnu
release: 1.20.0-nightly
LLVM version: 4.0
```

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:438:8
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:390
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
   6: rustc_errors::Handler::span_bug
   7: rustc::session::opt_span_bug_fmt::{{closure}}
   8: rustc::session::opt_span_bug_fmt
   9: rustc::session::span_bug_fmt
  10: <&'gcx rustc::ty::TyS<'gcx> as rustc::infer::TransNormalize<'gcx>>::trans_normalize
  11: rustc::infer::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'tcx>>::normalize_associated_type_in_env
  12: rustc::ty::layout::Layout::compute_uncached
  13: rustc::ty::util::layout_raw
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::layout_raw<'tcx>>::try_get
  15: rustc::ty::maps::TyCtxtAt::layout_raw
  16: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::layout_raw
  17: rustc_const_eval::eval::eval_const_expr_partial::{{closure}}
  18: rustc_const_eval::eval::eval_const_expr_partial
  19: rustc_const_eval::eval::eval_const_expr_partial
  20: rustc_const_eval::eval::eval_const_expr_partial
  21: rustc_const_eval::eval::eval_const_expr_partial
  22: rustc_const_eval::eval::ConstContext::eval
  23: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  24: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  25: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  26: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  27: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  28: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
  29: <rustc_passes::consts::CheckCrateVisitor<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
  30: rustc_passes::consts::check_crate
  31: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  32: rustc_driver::driver::phase_3_run_analysis_passes
  33: rustc_driver::driver::compile_input
  34: rustc_driver::run_compiler
```

**Comment by Mark-Simulacrum** [comment] 2017-07-24 13:22
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/43357.

**Closed by Mark-Simulacrum** 2017-07-24 13:22 UTC
