### ISSUE TITLE
from_str_radix_float gives incorrect (/imprecise) results on beta and nightly

### ISSUE THREAD

**Issue by spaolacci** [rust-lang/rust#25895] opened 2015-05-30 07:59 UTC
`str::parse("2.99")` correctly parses to `2.99` in stable branch, but less correctly to `2.9899999999999998` on both beta and nightly.

**Comment by sfackler** [comment] 2015-05-30 22:09
Is it parsing incorrectly or choosing a different representation when printing? 2.99 and 2.9899999999999998 have the same floating point representation. The floating to decimal logic was rewritten in #24612. cc @lifthrasiir

**Comment by lifthrasiir** [comment] 2015-05-31 03:26
@sfackler No, they have different floating point representations:

    2.989999999999999769073610877967439591884613037109375 = 0x4007 eb85 1eb8 51eb
    2.9899999999999998 (rounds down)
    2.99 (rounds up)
    2.9900000000000002131628207280300557613372802734375 = 0x4007 eb85 1eb8 51ec

This is very slight, but 2.99 should round up (absolute error of 2.13e-16 for up vs. 2.31e-16 for down) while it doesn't seem so. I believe this is more like #24557.

**Comment by huonw** [comment] 2015-05-31 03:44
Closing as a dupe of #24557. Thanks for filing.

**Closed by huonw** 2015-05-31 03:44 UTC

**Comment by spaolacci** [comment] 2015-05-31 09:21
Thanks.
