### ISSUE TITLE
internal compiler error matching std::env in static variable initializer.

### ISSUE THREAD

**Issue by wehjin** [rust-lang/rust#36071] opened 2016-08-28 14:04 UTC
`rustc` panics while compiling and matching an environment variable in static variable initializer.

I tried this code:
```
use std::env;

static A_STATIC_VARIABLE: bool = match env::var("HOME") {
    Ok(val) => {
        if val.starts_with("/User/") {
            false
        } else {
            true
        }
    },
    Err(e) => true
};

fn main() {
}
```

It returns a note saying the compiler unexpectedly panicked.

```
examples/compiler_crash.rs:4:8: 4:11 error: internal compiler error: src/librustc_typeck/check/dropck.rs:288: no enclosing scope found for scope: CodeExtent(5/Misc(26))
examples/compiler_crash.rs:4     Ok(val) => {
                                    ^~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
```

## Meta
rustc --version --verbose:
```
rustc 1.11.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.11.0
```

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:580
stack backtrace:
   1:        0x113078bcb - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:        0x113085a9a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:        0x1130855cb - std::panicking::default_hook::heb8b6fd640571a4f
   4:        0x11304af78 - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:        0x10f2059db - std::panicking::begin_panic::h3e029d5f110b4661
   6:        0x10f20586d - rustc::session::opt_span_bug_fmt::_$u7b$$u7b$closure$u7d$$u7d$::h11fa08f71c1e9d84
   7:        0x10f205652 - rustc::session::span_bug_fmt::he71d3b772c0a8595
   8:        0x10f28a46f - rustc_typeck::check::dropck::check_safety_of_destructor_if_necessary::h37d16cd456294c84
   9:        0x10f2a22cf - rustc::hir::Pat::walk_::h8304510acb0ac05c
  10:        0x10f2a237e - rustc::hir::Pat::walk_::h8304510acb0ac05c
  11:        0x10f2a36e6 - rustc::hir::intravisit::walk_expr::h967bdbfdd516da48
  12:        0x10f29e2da - _<rustc_typeck..check..regionck..RegionCtxt<'a, 'gcx, 'tcx> as rustc..hir..intravisit..Visitor<'v>>::visit_expr::h5db5517cdc833831
  13:        0x10f285686 - rustc_typeck::check::regionck::_<impl rustc_typeck..check..FnCtxt<'a, 'gcx, 'tcx>>::regionck_expr::h8c9a520a57564034
  14:        0x10f237fc9 - rustc_typeck::check::FnCtxt::check_const_with_ty::h605b29837ba52f41
  15:        0x10f22cbbc - rustc_typeck::check::check_const::h1d29ba88db6ab65b
  16:        0x10f212ce0 - rustc_typeck::check::check_item_type::h56c0a050d7325a0d
  17:        0x10f21235f - _<rustc_typeck..check..CheckItemTypesVisitor<'a, 'tcx> as rustc..hir..intravisit..Visitor<'tcx>>::visit_item::h74a5bade95a254e7
  18:        0x10f210fcd - rustc_typeck::check::check_item_types::h2bb988f247afedcf
  19:        0x10f206d85 - rustc_typeck::check_crate::h1d947f5c8edea4a9
  20:        0x10ef564c0 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::hded790081e457a76
  21:        0x10ef54790 - rustc::ty::context::TyCtxt::create_and_enter::h7622c0f52ea2e7fe
  22:        0x10ef116d9 - rustc_driver::driver::compile_input::hdfe4405d66704c31
  23:        0x10eefe9c4 - rustc_driver::run_compiler::h581448fb74257353
  24:        0x10eefba0f - std::panicking::try::call::hf081e8ea5e252d1a
  25:        0x11308cbcb - __rust_try
  26:        0x11308cb65 - __rust_maybe_catch_panic
  27:        0x10eefc51b - _<F as alloc..boxed..FnBox<A>>::call_box::h2d5dcb354b3ff8db
  28:        0x113084518 - std::sys::thread::Thread::new::thread_start::hf2eed4b6f7149599
  29:     0x7fff9dd9f99c - _pthread_body
  30:     0x7fff9dd9f919 - _pthread_start

```

**Comment by nagisa** [comment] 2016-08-28 15:38
Duplicate of https://github.com/rust-lang/rust/issues/31577

**Closed** 2016-08-28 18:01 UTC
