### ISSUE TITLE
readonly variable warning on Azure pipelines

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#68671] opened 2020-01-30 14:07 UTC
Overwriting readonly task variable 'RUST_CONFIGURE_ARGS'. This behavior will be disabled in the future. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.

**Comment by aidanhs** [comment] 2020-02-12 15:11
- e.g. see https://dev.azure.com/rust-lang/rust/_build/results?buildId=20796&view=results
 - no precise timeline known

**Comment by nellshamrell** [comment] 2020-02-19 15:09
I can take a look at this this week

**Comment by pietroalbini** [comment] 2020-02-26 15:07
We're waiting on a timeline from Microsoft on the removal.

**Comment by nellshamrell** [comment] 2020-03-06 21:32
Sent a follow up email to GitHub today:

Hello there and greetings from Mozilla!

I'd like to follow up on the [transition to read only variables](https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md) (and away from overwriting read only variables) in Azure pipelines. We are now seeing a warning about this in [our Azure pipeline output](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20796&view=results). Do you have any timeline on when the behavior of overwriting readonly variables will be removed? We'd love to have this information so we know how to prioritize our backlog of work.

**Comment by nellshamrell** [comment] 2020-03-09 22:01
Hello all - turning my attention to this this week.

I wrote up what I believe the problem is - could someone confirm that this is correct?


RUST_CONFIG_ARGS is initially set in [src/ci/azure-pipelines/auto.yml](https://github.com/rust-lang/rust/blob/7760cd0fbbbf2c59a625e075a5bdfa88b8e30f8a/src/ci/azure-pipelines/auto.yml) for the various platforms we build on.

Let's first focus on windows x86_64-msvc-2

**src/ci/azure-pipeines/auto.yml**
```
- job: Windows
  timeoutInMinutes: 600
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: steps/run.yml
  strategy:
    matrix:
      # 32/64 bit MSVC tests
      (...)
       x86_64-msvc-2:
        RUST_CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc --enable-profiler
        SCRIPT: make ci-subset-2
```

Now let's look at the template used in [src/ci/azure-pipeines/steps/run.yml](https://github.com/rust-lang/rust/blob/7760cd0fbbbf2c59a625e075a5bdfa88b8e30f8a/src/ci/azure-pipelines/steps/run.yml)

There are a number of scripts called - but let's take a closer look at this one:

```
- bash: src/ci/scripts/install-clang.sh
  displayName: Install clang
  condition: and(succeeded(), not(variables.SKIP_JOB))
```

It calls the [install-clang script](https://github.com/rust-lang/rust/blob/59eb49d0da83fff01ae3c63f2e282b953e5f88df/src/ci/scripts/install-clang.sh) - let's take a closer look at it.

```
elif isWindows && [[ ${CUSTOM_MINGW-0} -ne 1 ]]; then
    (...)
    mkdir -p citools
    cd citools
    curl -f "${MIRRORS_BASE}/LLVM-9.0.0-win64.tar.gz" | tar xzf -
    ciCommandSetEnv RUST_CONFIGURE_ARGS \
        "${RUST_CONFIGURE_ARGS} --set llvm.clang-cl=$(pwd)/clang-rust/bin/clang-cl.exe"
fi
```

Notice how it is overwriting RUST_CONFIGURE_ARGS? This is the reason we are getting [this warning about overwriting read only variables](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20796&view=logs&j=c9ea9f88-3fea-5145-c269-3bbafa17f0d5&t=7c6b0740-c49d-56d9-aba9-276293a77ad7&l=45) (among many others).

**Comment by pietroalbini** [comment] 2020-03-09 22:05
That sounds correct!

**Comment by pietroalbini** [comment] 2020-03-10 08:53
@nellshamrell a quick fix for this would be to set in the job definition something like `INITIAL_RUST_CONFIGURE_ARGS` and then set `RUST_CONFIGURE_ARGS` to it from a script.

**Comment by vtbassmatt** [comment] 2020-03-10 16:57
👋 PM from Azure Pipelines here. @nellshamrell and @pietroalbini you have it exactly correct. We  intended that matrix variables would become read-only, but I didn't do a good job communicating about that. So sorry that you got caught out by this (and further sorry that we didn't get right people looped in until the change took effect!).

**Closed** 2020-03-24 12:42 UTC
Labels: P-high, T-infra
