### ISSUE TITLE
rustc beta (1.28.0) generates unnecessary call instruction

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#52651] opened 2018-07-23 20:51 UTC
For this code:
```rust
pub struct A([i32; 4]);
impl A {
    pub fn foo(self) -> Self { self }
    pub fn bar(self) -> Self { self }
}
```
rustc beta (1.28.0) with `opt-level=3` generates:
```asm
example::A::bar:
        movups  xmm0, xmmword ptr [rsi]
        movups  xmmword ptr [rdi], xmm0
        mov     rax, rdi
        ret

example::A::foo:
        push    rbx
        mov     rbx, rdi
        call    example::A::bar@PLT
        mov     rax, rbx
        pop     rbx
        ret
```
rustc 1.27.1 and rustc beta with `opt-level=s` generates:
```asm
example::A::foo:
        movups  xmm0, xmmword ptr [rsi]
        movups  xmmword ptr [rdi], xmm0
        mov     rax, rdi
        ret

example::A::bar:
        movups  xmm0, xmmword ptr [rsi]
        movups  xmmword ptr [rdi], xmm0
        mov     rax, rdi
        ret
```
The beta with `opt-level=3` seems to be anti-inlining the identical functions.

**Comment by Mark-Simulacrum** [comment] 2018-07-23 20:57
cc @rust-lang/compiler 

(I've not attempted a reproduction locally)

**Comment by rkruppe** [comment] 2018-07-23 21:14
This might be due to #49479, the time frame seems right and the code change observed here is precisely what MergeFunctions does. Some bullet points:

- it's counter intuitive that this doesn't happen with `opt-level=s`
- it's silly that it doesn't generate a tail call, wonder why that happens
- if we decided that distinct source-level functions are allowed to have identical addresses and told LLVM about it with the `unnamed_addr` attribute, MergeFunctions could turn one function into a link-time alias for the other instead of creating a thunk that calls

**Comment by rkruppe** [comment] 2018-07-23 21:15
cc @nox

**Comment by eddyb** [comment] 2018-07-31 16:01
@rkruppe Huh, I thought we used `unnamed_addr` already, and didn't make any promises?

**Comment by hermord** [comment] 2018-08-08 01:28
Interestingly, the LLVM IR the sample code [results in](https://play.rust-lang.org/?gist=594be6c7e69ec469cd04000397df514f&version=nightly&mode=release&edition=2018) appears to be using both  `unnamed_addr` and `tail_call`:
```llvm
define void @bar(%A* noalias nocapture sret dereferenceable(16), %A* noalias nocapture readonly dereferenceable(16) %self) unnamed_addr #0 {
 ; ...
}
; ...
define void @foo(%A* noalias nocapture sret dereferenceable(16), %A* noalias nocapture readonly dereferenceable(16)) unnamed_addr #0 {
  tail call void @bar(%A* noalias nocapture sret dereferenceable(16) %0, %A* noalias nocapture readonly dereferenceable(16) %1) #0
  ret void
}
```

**Comment by hermord** [comment] 2018-08-08 01:57
This seems to be related to the fact that `foo` and `bar` have return type `void` in LLVM IR. Making `bar` return a dummy `i32` value [generates a proper tail call](https://gist.github.com/hermord/38f37ef318e9d7a0cee24d60eea37417).

**Comment by hermord** [comment] 2018-08-08 02:05
This appears to be caused by the `sret` attribute. Removing it (with no other changes!) from both functions [generates a proper tail call](https://gist.github.com/hermord/38f37ef318e9d7a0cee24d60eea37417).

**Comment by hermord** [comment] 2018-08-08 05:35
`unnamed_addr` doesn't have the expected effect because [here](https://llvm.org/doxygen/MergeFunctions_8cpp_source.html#l00767) the only possible outcomes are: 
1. If `bar` has local linkage, then it is erased (all uses are replaced with `foo`).
2. If creating a thunk is profitable, `bar` becomes a thunk (tail-)calling `foo` (which isn't lowered as an actual tail call because of `sret`, as above).
3. Otherwise, `foo` and `bar` remain unchanged (all local uses of `bar` are replaced with `foo`, but the definition is kept for external linkage).

There is no attempt to alias `bar` with `foo`. Two things should probably be fixed in LLVM code:

1. `isThunkProfitable` should be less optimistic (currently it returns true for all functions longer than 2 instructions).
2. `writeThunkOrAlias` as described [here](https://llvm.org/docs/MergeFunctions.html#if-f-could-not-be-overridden-fix-it) should replace `writeThunk`.

I will look into submitting a patch.

**Comment by nikic** [comment] 2018-11-05 13:30
For the record, I've submitted a couple of patches for MergeFuncs to improve handling in some cases and add alias support. They're accepted, but not landed yet:

https://reviews.llvm.org/D53262
https://reviews.llvm.org/D53271
https://reviews.llvm.org/D53285

The alias functionality will be behind a `-mergefunc-use-aliases` flag, because historically there have been issues here with lacking linker support. We can try enabling this flag for rust and see if there are any issues.

**Comment by nikic** [comment] 2018-11-22 13:37
The patches have all landed upstream. After the next LLVM update, we can enable use of aliases by passing `-mergefunc-use-aliases` in https://github.com/rust-lang/rust/blob/f1d61837d1cf058cfbd0902b0bf79a2657b81187/src/librustc_codegen_llvm/llvm_util.rs#L54

**Closed** 2018-12-03 04:52 UTC
Labels: I-slow, P-medium, T-compiler, regression-from-stable-to-stable
