### ISSUE TITLE
The floor method gives wrong results

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#32109] opened 2016-03-08 00:05 UTC
Hello.
It seems the `floor` method returns wrong results.
The following code:

```rust
println!("{}", -15.6_f64.floor());
println!("{}", 15.6_f64.floor());
```

prints:

```
-15
15
```

The documentation says "Returns the largest integer less than or equal to a number.".
`-15` is not less than `-15.6`.

If the documentation is wrong, it should be noted that currently, `floor` seems to behave exactly like `trunc`. So, in this case, a method is useless.

In some languages, e.g. Python, floor behaves as such:

```python
>>> floor(-15.6)
-16
```

Thanks to fix this issue.

**Comment by Aatch** [comment] 2016-03-08 02:00
Yeah, this is just wrong. `floor` should be round towards negative infinity, `ceil` should be round towards positive infinity, `trunc` should be round towards zero and `round` should be round to nearest (with `0.5` rounding away from zero).

**Comment by durka** [comment] 2016-03-08 02:22
`ceil` is also wrong for negative floats then (`-15.6f64.ceil()` is -16).

**Comment by durka** [comment] 2016-03-08 02:29
Actually it's just a confusing precedence issue. We have `-15.6_f64.floor()` which looks like `(-15.6_f64).floor()` but actually it is `-(15.6_f64.floor())`. The former gives the expected result.

**Comment by alexcrichton** [comment] 2016-03-08 02:36
Ah yeah this looks like intended behavior due to the precedence of `-`, so closing as working as intended. Thanks for the report though @antoyo!

**Closed by alexcrichton** 2016-03-08 02:36 UTC
Labels: A-libs

**Comment by Qix-** [comment] 2023-08-11 22:31
I'm not arguing with the semantics here at all, just prefacing. However from a language theory perspective, is there a reason why it was chosen not to parse `-12.34f32` as a singular token and instead parsing it as `{-, 12.34f32}`? It is just because it simplifies the unary arithmetic negate operator implementation? Or is there some clear benefit from a theory standpoint?

This behavior was really unexpected, to say the least 😅 However I can't think of another major language that does math operations as member functions (I'm sure there _are_ languages that do but none come to mind), so I can't think of a precedent here to begin with.
