### ISSUE TITLE
Incorrect method selection with trait objects

### ISSUE THREAD

**Issue by cmf028** [rust-lang/rust#24756] opened 2015-04-24 02:19 UTC
The following code compiles fine, but crashes with an illegal instruction:
```rust
trait VisitorBase<T> {
    fn visit(&mut self, node: &T);
}

trait Visitor : VisitorBase<Num> + VisitorBase<Add> {}
impl<T> Visitor for T where T: VisitorBase<Num> + VisitorBase<Add> {}

trait Node {
    fn accept(&self, visitor: &mut Visitor );
}

struct Add {
    lhs: Box<Node>,
    rhs: Box<Node>
}

impl Node for Add {
    fn accept(&self, visitor: &mut Visitor) {
        println!("accept Add");
        visitor.visit(self);
    }
}

struct Num {
    val: i32
}

impl Node for Num {
    fn accept(&self, visitor: &mut Visitor) {
        println!("accept Num");
        visitor.visit(self);
    }
}

struct EvalVisitor {
    result: i32
}

impl VisitorBase<Add> for EvalVisitor {
    fn visit(&mut self, node: &Add) {
        println!("visit Add");
        node.lhs.accept(self);
        let temp = self.result;
        node.rhs.accept(self);
        self.result = temp + self.result;
    }
}

impl VisitorBase<Num> for EvalVisitor {
    fn visit(&mut self, node: &Num) {
        println!("visit Num");
        self.result = node.val;
    }
}

fn main() {
    let root = Num{val: 5};
    let mut visitor = EvalVisitor{result: 0};
    root.accept(&mut visitor);
    println!("value: {}", visitor.result);
}
```
output:
```
accept Num
visit Add
<segfault>
```
rustc 1.0.0-beta.2 (e9080ec39 2015-04-16) (built 2015-04-16)

**Comment by huonw** [comment] 2015-04-24 02:20
cc @nikomatsakis

**Comment by nikomatsakis** [comment] 2015-04-24 09:39
Argh. The problem is that our vtable generation is apparently still making the assumption that it only needs to track the trait, not the type parameters to the trait.

**Comment by nikomatsakis** [comment] 2015-04-24 09:39
triage: P-medium 

Rationale: Definitely should be fixed ASAP, but nobody could rely on this behavior.

**Comment by apasel422** [comment] 2015-09-29 14:05
This no longer segfaults on nightly and prints
```
accept Num
visit Num
value: 5
```

**Comment by steveklabnik** [comment] 2015-09-29 14:06
:confetti_ball:

**Closed by steveklabnik** 2015-09-29 14:06 UTC
Labels: A-traits, I-crash, P-medium
