### ISSUE TITLE
`cargo doc` panic on Polkadot build

### ISSUE THREAD

**Issue by NukeManDan** [rust-lang/rust#98032] opened 2022-06-12 20:53 UTC
### Meta

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

### Error output

```
Documenting polkadot-node-subsystem v0.9.23 (./polkadot/node/subsystem)
thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:977:16
stack backtrace:
   0:     0x7ff97869e1cd - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7ff97869e1cd - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff97869e1cd - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7ff97869e1cd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7ff9786f801c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x7ff97868f7c1 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x7ff9786a12b5 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7ff9786a12b5 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7ff9786a12b5 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x7ff9786a0f69 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x7ff978ead1d1 - rustc_driver[413d55b6344850e3]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7ff9786a1a00 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
  12:     0x7ff9786a1837 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
  13:     0x7ff97869e684 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7ff9786a1569 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
  15:     0x7ff9786656b3 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
  16:     0x7ff9786f4e31 - core::panicking::panic_display::hd3e89d99fb893792
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:72:5
  17:     0x7ff9786f4ddb - core::panicking::panic_str::h98ed104b0c03a108
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:56:5
  18:     0x7ff978665526 - core::option::expect_failed::h58d487f78ae9d247
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:1874:5
  19:     0x55bbb44799c9 - rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::resolve_associated_trait_item
  20:     0x55bbb44781de - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  21:     0x55bbb44753c5 - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector>::resolve
  22:     0x55bbb447b6ae - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_item
  23:     0x55bbb44872ca - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_inner_recur
  24:     0x55bbb447e880 - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_item
  25:     0x55bbb44872ca - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_inner_recur
  26:     0x55bbb447e880 - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_item
  27:     0x55bbb44872ca - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_inner_recur
  28:     0x55bbb447e880 - <rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2368e8ab35c11ae8]::visit::DocVisitor>::visit_item
  29:     0x55bbb4473bbc - rustdoc[2368e8ab35c11ae8]::passes::collect_intra_doc_links::collect_intra_doc_links
  30:     0x55bbb42ccf54 - <rustc_session[8df92abe178df33c]::session::Session>::time::<rustdoc[2368e8ab35c11ae8]::clean::types::Crate, rustdoc[2368e8ab35c11ae8]::core::run_global_ctxt::{closure#8}>
  31:     0x55bbb452d90d - rustdoc[2368e8ab35c11ae8]::core::run_global_ctxt
  32:     0x55bbb42cd3c2 - <rustc_session[8df92abe178df33c]::session::Session>::time::<(rustdoc[2368e8ab35c11ae8]::clean::types::Crate, rustdoc[2368e8ab35c11ae8]::config::RenderOptions, rustdoc[2368e8ab35c11ae8]::formats::cache::Cache), rustdoc[2368e8ab35c11ae8]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#0}>
  33:     0x55bbb4588be6 - <rustc_interface[550884b2b179878f]::passes::QueryContext>::enter::<rustdoc[2368e8ab35c11ae8]::main_options::{closure#0}::{closure#0}::{closure#1}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  34:     0x55bbb448e41b - rustc_interface[550884b2b179878f]::interface::create_compiler_and_run::<core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>, rustdoc[2368e8ab35c11ae8]::main_options::{closure#0}>
  35:     0x55bbb43007d3 - rustdoc[2368e8ab35c11ae8]::main_options
  36:     0x55bbb4313d2b - <scoped_tls[7ed3ce20ede545d8]::ScopedKey<rustc_span[7238ca7210ca999e]::SessionGlobals>>::set::<rustdoc[2368e8ab35c11ae8]::main_args::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  37:     0x55bbb445d93f - std[3b302b3c9093c22]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[550884b2b179878f]::util::run_in_thread_pool_with_globals<rustdoc[2368e8ab35c11ae8]::main_args::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>
  38:     0x55bbb454c869 - <<std[3b302b3c9093c22]::thread::Builder>::spawn_unchecked_<rustc_interface[550884b2b179878f]::util::run_in_thread_pool_with_globals<rustdoc[2368e8ab35c11ae8]::main_args::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>::{closure#0}, core[a3420257622cd381]::result::Result<(), rustc_errors[a7dbbf867eaca825]::ErrorGuaranteed>>::{closure#1} as core[a3420257622cd381]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  39:     0x7ff9786abbf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha99802c2c52ada61
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
  40:     0x7ff9786abbf3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha39aea1c57e28a15
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
  41:     0x7ff9786abbf3 - std::sys::unix::thread::Thread::new::thread_start::h9f8e3d72b1f7662f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7ff978385b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  43:     0x7ff978417a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  44:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https./github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0 (fe5b13d68 2022-05-18) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `polkadot-node-subsystem`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name polkadot_node_subsystem node/subsystem/src/lib.rs -o ./polkadot/target/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=49b872d20c6cb053 -L dependency=./polkadot/target/debug/deps --extern polkadot_node_jaeger=./polkadot/target/debug/deps/libpolkadot_node_jaeger-7a85134452f9ab9b.rmeta --extern polkadot_node_subsystem_types=./polkadot/target/debug/deps/libpolkadot_node_subsystem_types-ee48f2698c5c4dc1.rmeta --extern polkadot_overseer=./polkadot/target/debug/deps/libpolkadot_overseer-891b0bfc52420e3b.rmeta --crate-version 0.9.23` (exit status: 101)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
same as above
```

</p>
</details>

**Comment by bkchr** [comment] 2022-06-13 06:12
Did you try the latest nightly?

**Comment by GuillaumeGomez** [comment] 2022-06-17 12:58
cc @petrochenkov

**Comment by VictorKoenders** [comment] 2022-07-05 16:19
This seems to still be an issue in `rustc 1.62.0 (a8314ef7d 2022-06-27) running on x86_64-pc-windows-msvc`

**Comment by petrochenkov** [comment] 2022-10-16 13:23
I cannot reproduce this issue on Rust 1.62.1 or on Rust Nightly, closing the issue.
I didn't bisect in more detail because polkadot requires enormous amount of time to document (its dependency tree is about 2000 crates).

If you have a specific commit of polkadot and Rust version that reproduce this issue, please reopen it (or create a new one).

**Closed** 2022-10-16 13:23 UTC
Labels: T-rustdoc, I-ICE, C-bug, A-intra-doc-links

**Comment by mattheworris** [comment] 2023-06-02 15:54
Seeing this error again after trying to upgrade to polkadot v0.9.38
Active toolchain:
nightly-2022-11-15-aarch64-apple-darwin (overridden by '/Users/mattheworris/projects/frequency-main/rust-toolchain.toml')
rustc 1.67.0-nightly (96ddd32c4 2022-11-14)

thread 'rustc' panicked at 'no entry found for key', src/librustdoc/passes/collect_intra_doc_links.rs:782:16
stack backtrace:
   0:        0x105c6ec54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h05fe749630fb84b2
   1:        0x105cc0308 - core::fmt::write::h56044356168713ba
   2:        0x105c61c7c - std::io::Write::write_fmt::h3d9d452c064ba6ce
   3:        0x105c6ea68 - std::sys_common::backtrace::print::h81a1d22b45459df7
   4:        0x105c71510 - std::panicking::default_hook::{{closure}}::h7b8c781baeb88c58
   5:        0x105c71268 - std::panicking::default_hook::ha6ccbf40949f92a7
   6:        0x10dc6ae3c - rustc_driver[430a680fc88a5df1]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:        0x105c71c10 - std::panicking::rust_panic_with_hook::h705114c6359d32c5
   8:        0x105c71a08 - std::panicking::begin_panic_handler::{{closure}}::h29fe5f1cfa68c1a6
   9:        0x105c6f0bc - std::sys_common::backtrace::__rust_end_short_backtrace::h99c66c40f43a73b4
  10:        0x105c7175c - _rust_begin_unwind
  11:        0x105cebef8 - core::panicking::panic_fmt::h984f8f19a87290dd
  12:        0x105cbd588 - core::panicking::panic_display::hab522972d10c42f6
  13:        0x105cbd54c - core::panicking::panic_str::h879d7a8b16cf2918
  14:        0x105cebec4 - core::option::expect_failed::h963b8297cebb38d4
  15:        0x1049ee214 - rustdoc[2b0e45de692993a]::passes::collect_intra_doc_links::resolve_associated_trait_item
  16:        0x1049ed348 - <rustdoc[2b0e45de692993a]::passes::collect_intra_doc_links::LinkCollector>::resolve_associated_item
  17:        0x1049ec054 - <rustdoc[2b0e45de692993a]::passes::collect_intra_doc_links::LinkCollector>::resolve
  18:        0x1049ef940 - <rustdoc[2b0e45de692993a]::passes::collect_intra_doc_links::LinkCollector as rustdoc[2b0e45de692993a]::visit::DocVisitor>::visit_item
  19:        0x1049eac70 - rustdoc[2b0e45de692993a]::passes::collect_intra_doc_links::collect_intra_doc_links
  20:        0x104a22e24 - <rustc_session[80e440121b2ed8b]::session::Session>::time::<rustdoc[2b0e45de692993a]::clean::types::Crate, rustdoc[2b0e45de692993a]::core::run_global_ctxt::{closure#7}>
  21:        0x1049d3d88 - rustdoc[2b0e45de692993a]::core::run_global_ctxt
  22:        0x104a231b0 - <rustc_session[80e440121b2ed8b]::session::Session>::time::<(rustdoc[2b0e45de692993a]::clean::types::Crate, rustdoc[2b0e45de692993a]::config::RenderOptions, rustdoc[2b0e45de692993a]::formats::cache::Cache), rustdoc[2b0e45de692993a]::main_args::{closure#1}::{closure#0}::{closure#1}::{closure#0}>
  23:        0x104a79c1c - <rustc_interface[b18b68b4c454af3d]::passes::QueryContext>::enter::<rustdoc[2b0e45de692993a]::main_args::{closure#1}::{closure#0}::{closure#1}, core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>>
  24:        0x10491eba4 - <rustc_interface[b18b68b4c454af3d]::interface::Compiler>::enter::<rustdoc[2b0e45de692993a]::main_args::{closure#1}::{closure#0}, core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>>
  25:        0x1049b97d0 - std[105242c46289980]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[b18b68b4c454af3d]::util::run_in_thread_pool_with_globals<rustc_interface[b18b68b4c454af3d]::interface::run_compiler<core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>, rustdoc[2b0e45de692993a]::main_args::{closure#1}>::{closure#0}, core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>>
  26:        0x104ae4630 - <<std[105242c46289980]::thread::Builder>::spawn_unchecked_<rustc_interface[b18b68b4c454af3d]::util::run_in_thread_pool_with_globals<rustc_interface[b18b68b4c454af3d]::interface::run_compiler<core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>, rustdoc[2b0e45de692993a]::main_args::{closure#1}>::{closure#0}, core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[5c9e9337aa2c35a6]::result::Result<(), rustc_errors[2faad687c8ae036a]::ErrorGuaranteed>>::{closure#1} as core[5c9e9337aa2c35a6]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  27:        0x105c79f50 - std::sys::unix::thread::Thread::new::thread_start::h44a49daaeab56bd1
  28:        0x191d1bfa8 - __pthread_joiner_wake

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.67.0-nightly (96ddd32c4 2022-11-14) running on aarch64-apple-darwin

note: compiler flags: --crate-type lib -Z unstable-options

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `frequency-runtime`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name frequency_runtime runtime/frequency/src/lib.rs -o /Users/mattheworris/projects/frequency-main/target/doc --cfg 'feature="default"' --cfg 'feature="frequency"' --cfg 'feature="serde"' --cfg 'feature="std"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=27e22d483cacacb7 -L dependency=/Users/mattheworris/projects/frequency-main/target/debug/deps --extern common_primitives=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcommon_primitives-1679737f1a8d52bf.rmeta --extern common_runtime=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcommon_runtime-93b370dfeb84e588.rmeta --extern cumulus_pallet_aura_ext=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcumulus_pallet_aura_ext-f4dff152c4f06670.rmeta --extern cumulus_pallet_parachain_system=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcumulus_pallet_parachain_system-57f8a9aa9a51d153.rmeta --extern cumulus_pallet_session_benchmarking=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcumulus_pallet_session_benchmarking-a5f40ca571fc69b3.rmeta --extern cumulus_primitives_core=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcumulus_primitives_core-f70e79c583b07b8c.rmeta --extern cumulus_primitives_timestamp=/Users/mattheworris/projects/frequency-main/target/debug/deps/libcumulus_primitives_timestamp-e688e3d2dc0da029.rmeta --extern frame_executive=/Users/mattheworris/projects/frequency-main/target/debug/deps/libframe_executive-0d72be76a13a3a31.rmeta --extern frame_support=/Users/mattheworris/projects/frequency-main/target/debug/deps/libframe_support-c8365936deb7b81e.rmeta --extern frame_system=/Users/mattheworris/projects/frequency-main/target/debug/deps/libframe_system-ad42cb4ea6598e03.rmeta --extern frame_system_rpc_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libframe_system_rpc_runtime_api-174fe2d463524b2a.rmeta --extern log=/Users/mattheworris/projects/frequency-main/target/debug/deps/liblog-75c16a66914e162d.rmeta --extern pallet_aura=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_aura-391b061e16e0b1bc.rmeta --extern pallet_authorship=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_authorship-6fb15793c41a14f4.rmeta --extern pallet_balances=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_balances-3d57c86cb5b0e342.rmeta --extern pallet_capacity=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_capacity-9f0928c645d87ef2.rmeta --extern pallet_collator_selection=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_collator_selection-648b3668b59449b9.rmeta --extern pallet_collective=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_collective-b993598556d90522.rmeta --extern pallet_democracy=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_democracy-6e571a8122de6dc0.rmeta --extern pallet_frequency_tx_payment=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_frequency_tx_payment-6f4e8779f57876ff.rmeta --extern pallet_handles=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_handles-292f13640ed416ea.rmeta --extern pallet_handles_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_handles_runtime_api-ad969daf699fbeed.rmeta --extern pallet_messages=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_messages-dbf29d5c303183ce.rmeta --extern pallet_messages_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_messages_runtime_api-e8defeba12911fd1.rmeta --extern pallet_msa=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_msa-ac72344918fde0a6.rmeta --extern pallet_msa_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_msa_runtime_api-4c7e1259c72c4df4.rmeta --extern pallet_multisig=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_multisig-5bbaf95b4f5eab7b.rmeta --extern pallet_preimage=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_preimage-08a7713b96083657.rmeta --extern pallet_scheduler=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_scheduler-d8e7097e984eb2c7.rmeta --extern pallet_schemas=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_schemas-06dbb031709d8e6f.rmeta --extern pallet_schemas_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_schemas_runtime_api-40dc894deff3672e.rmeta --extern pallet_session=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_session-918091a40d160a9a.rmeta --extern pallet_stateful_storage=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_stateful_storage-4fe15977ee30620a.rmeta --extern pallet_stateful_storage_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_stateful_storage_runtime_api-45ca7b7ff73a6571.rmeta --extern pallet_sudo=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_sudo-b80a9d8e00ec7745.rmeta --extern pallet_time_release=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_time_release-e2dffae88a45f2c5.rmeta --extern pallet_timestamp=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_timestamp-1a03d625051d6701.rmeta --extern pallet_transaction_payment=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_transaction_payment-64d695295a82108f.rmeta --extern pallet_transaction_payment_rpc_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_transaction_payment_rpc_runtime_api-67b1b48f87c6a8f6.rmeta --extern pallet_treasury=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_treasury-463e808253fe83b9.rmeta --extern pallet_utility=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpallet_utility-f8d9e0ae7e5424a0.rmeta --extern parachain_info=/Users/mattheworris/projects/frequency-main/target/debug/deps/libparachain_info-b4b3c88740d94bd6.rmeta --extern codec=/Users/mattheworris/projects/frequency-main/target/debug/deps/libparity_scale_codec-ddb8a35687f1a678.rmeta --extern polkadot_parachain=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpolkadot_parachain-c5a875472bd56c6a.rmeta --extern polkadot_runtime_common=/Users/mattheworris/projects/frequency-main/target/debug/deps/libpolkadot_runtime_common-7cbfbe5c441312e6.rmeta --extern scale_info=/Users/mattheworris/projects/frequency-main/target/debug/deps/libscale_info-a8ca02e74d926c7b.rmeta --extern serde=/Users/mattheworris/projects/frequency-main/target/debug/deps/libserde-8dbbd6430b807c78.rmeta --extern smallvec=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsmallvec-6a390beaa141f00e.rmeta --extern sp_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_api-37c108eb6072cefd.rmeta --extern sp_block_builder=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_block_builder-81e4c83ccf21f1a4.rmeta --extern sp_consensus_aura=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_consensus_aura-f1ed1634b568f2d4.rmeta --extern sp_core=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_core-aea7bf9402cf4131.rmeta --extern sp_inherents=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_inherents-1653bffeb7eb1b56.rmeta --extern sp_io=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_io-1d2ddf7ff348dd47.rmeta --extern sp_offchain=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_offchain-53834d5b0c2ac780.rmeta --extern sp_runtime=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_runtime-59b713b1b704bc97.rmeta --extern sp_session=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_session-9a760d4b37f5c002.rmeta --extern sp_std=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_std-05ae93e1b5f9cd86.rmeta --extern sp_transaction_pool=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_transaction_pool-a81cab12015bdb50.rmeta --extern sp_version=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsp_version-909560b2f96a909f.rmeta --extern system_runtime_api=/Users/mattheworris/projects/frequency-main/target/debug/deps/libsystem_runtime_api-aa68b04a0adee94b.rmeta --enable-index-page --check -Zunstable-options --crate-version 0.0.0` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:75: lint] Error 101
