### ISSUE TITLE
thread 'rustc' panicked at 'const fn has no result expression', ../src/libcore/option.rs:699

### ISSUE THREAD

**Issue by tupshin** [rust-lang/rust#34281] opened 2016-06-15 01:56 UTC
Very easy to [reproduce](https://is.gd/PSTVmh) this error with rustc 1.11.0-nightly (ab0b87458 2016-06-13)

Play link above. Entire code below:

`#![feature(const_fn)]

const fn test_const() -> bool {}

fn main() {
    test_const();
}`

**Comment by oli-obk** [comment] 2016-06-15 10:45
duplicate of #33031

**Comment by Mark-Simulacrum** [comment] 2017-05-04 18:33
Closing as duplicate (and #33031 is also closed now).

**Closed by Mark-Simulacrum** 2017-05-04 18:33 UTC
