### ISSUE TITLE
`macro_rules!` thinks `use` is an `ident`. It isn't.

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#40569] opened 2017-03-16 13:42 UTC
This code should fail to compile, giving the same error message as `fn use()` would give, but it compiles successfully.

```
macro_rules! foo {
    ($foo:ident) => {}
}

fn main() {
    foo!(use);
}
```

This code should compile successfully. However, it fails complaining that it can't decide whether `use` is an ident or not (hint: it isn't). It also shouldn't be trying to match `use` as an ident because of the semicolon, but that's a broader/deeper issue with `macro_rules!`

```
macro_rules! foo {
    ($(use ;)* $foo:ident) => {}
}

fn main() {
    foo!(use ; use ; bar);
}
```

**Comment by petrochenkov** [comment] 2017-03-16 14:06
`ident` matcher accepts keywords (and also reserved keywords) by design (see very similar issue about `self` - https://github.com/rust-lang/rust/issues/27899#issuecomment-211602385 cc @nrc).

**Comment by sgrif** [comment] 2017-03-16 14:11
From that issue:

> I suppose, ident can be backward compatibly restricted to reject keywords and reserved identifiers with exception of path segment keywords super, self and Self (because you may want to write things like $seg: ident => $seg::foo::bar), but I don't see much benefit from such restriction.

The second case is a very concrete benefit from that restriction. :smile:

**Comment by sgrif** [comment] 2017-03-16 15:11
It looks like repeaters can pretty easily confuse `macro_rules!` even in more ridiculous cases. e.g.

```rust
macro_rules! my_struct {
    ($(#[$meta:meta])* $ident:ident) => {
        $(#[$meta])* struct $ident;
    }
}

my_struct!(#[derive(Debug)] Foo);
```

causes it to complain that it doesn't know if `#` is supposed to be an ident or not

**Comment by durka** [comment] 2017-03-16 16:48
The repetition thing is because `macro_rules` just doesn't attempt any backtracking. It's obviously not backwards compatible to change the definition of `ident` now...

**Comment by dtolnay** [comment] 2017-03-16 21:42
One specific common macro that this would break is Serde's [`forward_to_deserialize`](https://docs.serde.rs/serde/macro.forward_to_deserialize.html) which accepts "struct" and "enum" as idents.

**Comment by petrochenkov** [comment] 2019-08-14 16:50
Closing as works-as-expected and cannot-be-changed.

**Closed by petrochenkov** 2019-08-14 16:50 UTC
Labels: A-macros, C-bug
