### ISSUE TITLE
Spurious unused variable lint warning on enum with no variants

### ISSUE THREAD

**Issue by czipperz** [rust-lang/rust#62083] opened 2019-06-23 17:00 UTC
Code:

```
pub enum E {}

pub fn f() -> E {
    let sb = e();
    sb
}

fn e() -> E {
    unimplemented!()
}
```

Generates warning:

```
warning: unused variable: `sb`
 --> src/lib.rs:4:9
  |
4 |     let sb = e();
  |         ^^ help: consider prefixing with an underscore: `_sb`
  |
  = note: #[warn(unused_variables)] on by default
```

If you add a variant to the enum, the warning goes away.

The bug is also present when the enum is inside a struct:

```
pub struct S { e: E }

enum E {}

pub fn f() -> S {
    let sb = s();
    sb
}

fn s() -> S {
    unimplemented!()
}
```

**Comment by czipperz** [comment] 2019-06-23 17:08
@estebank

**Comment by cramertj** [comment] 2019-06-24 16:43
I don't think this is a bug-- that variable is uninhabited, so that code must be unreachable, meaning that the variable is unused.

**Comment by czipperz** [comment] 2019-06-24 17:02
We have precedence for unused variables causing warnings in the presence of `unimplemented!()`

**Comment by pnkfelix** [comment] 2019-07-12 10:43
I think the compiler should be given a lot of freedom about how much it takes control-flow into account when it performs its linting analyses.

So I would be fine with the compiler emitting the warning here, or not emitting the warning here.

But others may have differing opinions. I'm going to nominate this for discussion at the T-compiler meeting.
 * (Perhaps we can try to draw up some sort of formal policy on the matter that we could point at. Or maybe we already have such a document and I am simply ignorant of it.)

**Comment by nagisa** [comment] 2019-07-18 14:52
Bought this up for a discussion at the T-compiler meeting. There weren’t any objections to closing this as this appears to work as intended.

**Closed by nagisa** 2019-07-18 14:52 UTC
Labels: A-lint, C-bug, I-nominated, T-compiler
