### ISSUE TITLE
ICE: "no entry found for key" while building stage0 tools

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#88488] opened 2021-08-30 12:40 UTC
Checked out the latest version of the compiler today to write a patch, but ran into an ICE when doing `py check`. I haven't changed anything recently, so not sure what's causing this.

### Code

Compiling the compiler at commit 13edc17f65bcad7fe9046720a16fc192e810970e

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-beta.1 (739f8f0a8 2021-07-28) running on x86_64-pc-windows-gnu
```

### Error output

```
thread 'rustc' panicked at 'no entry found for key', compiler\rustc_query_impl\src\on_disk_cache.rs:175:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md    

note: rustc 1.55.0-beta.1 (739f8f0a8 2021-07-28) running on x86_64-pc-windows-gnu

note: compiler flags: -Z macro-backtrace -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C llvm-args=-import-instr-limit=10 --crate-type dylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `common::FunctionCx`       
#1 [check_item_well_formed] checking that `abi::comments::add_arg_comment` is well-formed
end of query stack
error: could not compile `rustc_codegen_cranelift`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
PS C:\Users\yoshu\Code\rust> py .\x.py check
Updating only changed submodules
Submodules updated in 0.11 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 2.15s
Checking stage0 std artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.59s
Checking stage0 std test/bench/example targets (x86_64-pc-windows-gnu 
-> x86_64-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.59s
Checking stage0 compiler artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
warning: library kind `static-nobundle` has been superseded by specifying `-bundle` on library kind `static`. Try `static:-bundle`

warning: `rustc_llvm` (lib) generated 1 warning
warning: `rustc_llvm` (lib test) generated 1 warning (1 duplicate)    
    Finished release [optimized] target(s) in 1.97s
Checking stage0 rustdoc artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.98s
Checking stage0 cranelift artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
    Checking rustc_codegen_cranelift v0.1.0 (C:\Users\yoshu\Code\rust\compiler\rustc_codegen_cranelift)
thread 'rustc' panicked at 'no entry found for key', compiler\rustc_query_impl\src\on_disk_cache.rs:175:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md    

note: rustc 1.55.0-beta.1 (739f8f0a8 2021-07-28) running on x86_64-pc-windows-gnu

note: compiler flags: -Z macro-backtrace -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C incremental -C llvm-args=-import-instr-limit=10 --crate-type dylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `common::FunctionCx`       
#1 [check_item_well_formed] checking that `abi::comments::add_arg_comment` is well-formed
end of query stack
error: could not compile `rustc_codegen_cranelift`

Caused by:
  process didn't exit successfully: `C:\Users\yoshu\Code\rust\build\bootstrap/debug/rustc --crate-name rustc_codegen_cranelift --edition=2018 src\lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type dylib --emit=dep-info,metadata -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=46f7e1b0fd3f3e68 -C extra-filename=-46f7e1b0fd3f3e68 --out-dir C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps --target x86_64-pc-windows-gnu -C incremental=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\incremental -L dependency=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps -L dependency=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\release\deps --extern ar=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libar-008c953fc1022421.rmeta --extern cranelift_codegen=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libcranelift_codegen-e3f012bff9079dc3.rmeta --extern cranelift_frontend=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libcranelift_frontend-70b32e62a9b56945.rmeta --extern cranelift_module=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libcranelift_module-a02560616de272a2.rmeta --extern cranelift_native=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libcranelift_native-69d1bf02ade6427b.rmeta --extern cranelift_object=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libcranelift_object-8c36e952eceda322.rmeta --extern gimli=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libgimli-8c830305f513e434.rmeta --extern indexmap=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libindexmap-509c3c26a3c04416.rmeta --extern 
object=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libobject-b937931e2b43b5fb.rmeta --extern smallvec=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libsmallvec-bf0557f61df3ef35.rmeta --extern target_lexicon=C:\Users\yoshu\Code\rust\build\x86_64-pc-windows-gnu\stage0-codegen\x86_64-pc-windows-gnu\release\deps\libtarget_lexicon-d1e221e5b1c4e96c.rmeta --cfg=bootstrap -Zmacro-backtrace -Cllvm-args=-import-instr-limit=10 -Z binary-dep-depinfo` (exit code: 0x80000003)
Build completed unsuccessfully in 0:00:20
```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-08-30 20:54
It looks like old incremental compilation data is getting reused. I believe that this should be fixed by `https://github.com/rust-lang/rust/pull/86641`.

In the meantime, running `./x.py clean` should fix this.

**Comment by jyn514** [comment] 2022-03-30 13:50
Duplicate of https://github.com/rust-lang/rust/issues/76720.

**Comment by jyn514** [comment] 2023-03-18 17:03
This is not actually a duplicate. This happens in stage0, not stage1, so it's not related to sharing the version string between different dev builds. It might be the case that we're not clearing the cache when we update the beta compiler, but that will have a different fix and should be tracked separately.

(It happened to me this morning)
```
Building tool rustdoc (stage0 -> stage1)
   Compiling rustdoc v0.0.0 (/home/jyn/src/rust2/src/librustdoc)
thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:639:9
```

**Comment by jyn514** [comment] 2023-03-18 17:08
The strange thing to me is that we shouldn't *need* to clear the stage0 cache - beta should just be ignoring incremental artifacts that don't match the version hash. @cjgillot @michaelwoerister do you know what could be going on here?

**Comment by jyn514** [comment] 2023-03-18 17:08
I do think this is a purely *incremental* bug because `rm -r build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/incremental/` fixed the issue, I didn't need to clear any .rmeta files.

**Comment by michaelwoerister** [comment] 2023-03-20 09:38
@jyn514, it looks you are able to reproduce this with a current toolchain. Can you provide some instructions on how to trigger the ICE?

**Comment by jyn514** [comment] 2023-03-21 14:39
@michaelwoerister unfortunately I deleted the directory and didn't record the steps to reproduce the error :( but @BoxyUwU managed to reproduce a similar error by checking out the first commit after the 1.70 version bump, running `x build rustdoc`, then checking out the latest commit and rebuilding - maybe that will work here?

**Comment by jyn514** [comment] 2023-03-25 21:16
@michaelwoerister I ran into this again today. Here are the replication steps:
```
rm -rf build
echo 'profile = "compiler"
changelog-seen = 2

[rust]
codegen-backends = ["cranelift"]' > config.toml
git checkout 9a24e2fee95 # might need to fetch from my remote: https://github.com/jyn514/rust/commit/9a24e2fee959fa9a7c3493489dba0223bfbc8928
x build rustc_codegen_cranelift
git checkout 2d429f3064cb67710fe64dee293329089871d92b
x build rustc_codegen_cranelift
```

**Comment by jyn514** [comment] 2023-03-25 21:36
... apparently that replicated the error the very first time I did it and then never again :facepalm:

**Comment by jyn514** [comment] 2023-03-25 21:45
ok, this actually replicates it:
```
rm -rf build/host/stage0-std
echo 'profile = "library"' > config.toml
git checkout eb34b82d1a3
x b --stage 0 core
git checkout 2d429f3064c
x b --stage 0 core
```

**Comment by jyn514** [comment] 2023-03-26 15:14
https://github.com/rust-lang/rust/issues/108481 looks related.

**Comment by michaelwoerister** [comment] 2023-03-27 11:33
> ok, this actually replicates it:

Nice! I reserved some time to take a look at this later this week.

**Comment by michaelwoerister** [comment] 2023-03-29 07:31
Update: https://github.com/rust-lang/rust/issues/108481 might indeed be the same issue and I spent most of yesterday finding out more about that. The issue seems to be caused by (sometimes) not recording dependency edges for query results that are directly fed. 

However, that means that https://github.com/rust-lang/rust/issues/108481 is not the same as the original issue reported by Yosh because query feeding was only implemented a few months ago. It's unclear if the original issue still exists.

**Comment by jyn514** [comment] 2023-03-29 12:55
> The issue seems to be caused by (sometimes) not recording dependency edges for query results that are directly fed.

cc @oli-obk

**Comment by jyn514** [comment] 2023-07-02 00:12
ran into the same thing myself

<details>

```
Checking stage0 rustdoc artifacts (x86_64-unknown-linux-gnu)
    Checking rustdoc v0.0.0 (/home/jyn/src/rust/src/librustdoc)
error: internal compiler error: compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:595:32: uninterned StableCrateId: StableCrateId(10044191383301396090)

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/eff24c06d8f4397802b546aa2e52450e1022fc02/compiler/rustc_errors/src/lib.rs:1651:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: <rustc_errors::HandlerInner>::bug::<alloc::string::String>
   2: <rustc_errors::Handler>::bug::<alloc::string::String>
   3: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>::{closure#0}
   4: rustc_middle::ty::context::tls::with_opt::<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}
   5: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_metadata::creader::CStore as rustc_session::cstore::CrateStore>::stable_crate_id_to_crate_num
   8: <rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
   9: <rustc_middle::ty::generics::GenericPredicates as rustc_serialize::serialize::Decodable<rustc_middle::query::on_disk_cache::CacheDecoder>>::decode
  10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::DefId, rustc_middle::query::erase::Erased<[u8; 24]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, true>
  11: <rustc_trait_selection::traits::wf::WfPredicates>::compute
  12: <rustc_trait_selection::traits::fulfill::FulfillProcessor as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
  13: <rustc_data_structures::obligation_forest::ObligationForest<rustc_trait_selection::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection::traits::fulfill::FulfillProcessor>
  14: <rustc_trait_selection::traits::engine::ObligationCtxt>::select_all_or_error
  15: rustc_hir_analysis::check::wfcheck::check_item_fn
  16: rustc_hir_analysis::check::wfcheck::check_well_formed
  17: rustc_data_structures::sync::par_for_each_in::<&[rustc_hir::hir_id::OwnerId], <rustc_middle::hir::map::Map>::par_for_each_module<rustc_hir_analysis::check_crate::{closure#5}::{closure#0}::{closure#0}>::{closure#0}>
  18: <rustc_session::session::Session>::track_errors::<rustc_hir_analysis::check_crate::{closure#5}, ()>
  19: rustc_hir_analysis::check_crate
  20: rustc_interface::passes::analysis
  21: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}>
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  23: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.71.0-beta.1 (eff24c06d 2023-05-29) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Z unstable-options -C incremental=[REDACTED] -C symbol-mangling-version=v0 -Z unstable-options -Z macro-backtrace -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C split-debuginfo=off -C llvm-args=-import-instr-limit=10 -Z unstable-options -Z binary-dep-depinfo -Z tls-model=initial-exec

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
thread panicked while processing panic. aborting.
rustc exited with signal: 6 (SIGABRT) (core dumped)
```

</details>

**Comment by jyn514** [comment] 2023-07-02 00:13
cc @Mark-Simulacrum this is likely a real regression that's going to end up in 1.71 - unclear which PR caused it so probably not much to do at this point but thought you'd want to know since the release is going out soon

**Comment by Mark-Simulacrum** [comment] 2023-07-02 01:56
Tagging for prioritization. It's not clear to me how impactful this is; I know I've seen and heard about other(?) incremental problems in 1.70 as well -- I think there's been some issues filed. Unfortunately I don't think we've found solutions that eliminate the problem at the root so just need to hope we don't introduce new ones :/

**Comment by hameerabbasi** [comment] 2023-07-02 05:21
> michaelwoerister unfortunately I deleted the directory and didn't record the steps to reproduce the error :( but BoxyUwU managed to reproduce a similar error by checking out the first commit after the 1.70 version bump, running `x build rustdoc`, then checking out the latest commit and rebuilding - maybe that will work here?

I wrote a script based on this statement; intending to run a `git bisect --no-checkout`, but it didn't reproduce for me on macOS x86_64.

```bash
#!/usr/bin/env bash

set -e

./x.py clean
git checkout $(git rev-list 1.70.0..master -n 1)
./x.py build --stage 1 rustdoc
git checkout $BISECT_HEAD
./x.py build --stage 1 rustdoc
```

**Comment by jyn514** [comment] 2023-07-02 08:13
yes, sorry - there are several issues mixed into the history here and not all of them are the same. the one that's going to land in 1.71 is https://github.com/rust-lang/rust/issues/112700, which no one has been able to reliably reproduce. the one boxy ran into was *likely* fixed by https://github.com/rust-lang/rust/pull/109935 and no longer reproduces on master.

make sure that you do not rebase over any version bump. if the stage0 compiler changes, your testing is invalid (because they just won't read the same metadata files).

**Comment by hameerabbasi** [comment] 2023-07-02 08:39
If all issues mixed in here are tracked elsewhere cleanly, perhaps it makes sense to close this one?

**Comment by michaelwoerister** [comment] 2023-07-03 09:00
Closing this as a duplicate of https://github.com/rust-lang/rust/issues/108481 (which has been fixed by https://github.com/rust-lang/rust/pull/109935).

**Closed by michaelwoerister** 2023-07-03 09:00 UTC
Labels: I-ICE, T-compiler, regression-from-stable-to-beta, A-incr-comp, T-bootstrap, C-bug, I-prioritize
