### ISSUE TITLE
Compiler panic - coherence failed to report ambiguity

### ISSUE THREAD

**Issue by gchp** [rust-lang/rust#20756] opened 2015-01-08 15:53 UTC
Compiler panic when attempting to build https://github.com/reem/rust-error

```
       Fresh typeable v0.0.5
   Compiling error v0.0.3 (file:///home/gchp/github.com/reem/rust-error)
     Running `rustc /home/gchp/github.com/reem/rust-error/src/lib.rs --crate-name error --crate-type lib -g -C metadata=45f77992efd3bf02 -C extra-filename=-45f77992efd3bf02 --out-dir /home/gchp/github.com/reem/rust-error/target --emit=dep-info,link -L dependency=/home/gchp/github.com/reem/rust-error/target -L dependency=/home/gchp/github.com/reem/rust-error/target/deps --extern typeable=/home/gchp/github.com/reem/rust-error/target/deps/libtypeable-99b257d6c5d5d947.rlib`
/home/gchp/github.com/reem/rust-error/src/lib.rs:9:16: 9:19 warning: deprecated syntax; use the `self` keyword now
/home/gchp/github.com/reem/rust-error/src/lib.rs:9 use std::fmt::{mod, Show, Formatter};
                                                                  ^~~
/home/gchp/github.com/reem/rust-error/src/lib.rs:3:12: 3:23 warning: feature has been added to Rust, directive not necessary
/home/gchp/github.com/reem/rust-error/src/lib.rs:3 #![feature(macro_rules)]
                                                              ^~~~~~~~~~~
/home/gchp/github.com/reem/rust-error/src/lib.rs:3:12: 3:23 warning: feature has been added to Rust, directive not necessary
/home/gchp/github.com/reem/rust-error/src/lib.rs:3 #![feature(macro_rules)]
                                                              ^~~~~~~~~~~
/home/gchp/github.com/reem/rust-error/src/lib.rs:83:1: 85:2 error: internal compiler error: coherence failed to report ambiguity: cannot locate the impl of the trait `core::fmt::Show` for the type `Error + 'static`
/home/gchp/github.com/reem/rust-error/src/lib.rs:83 impl Show for Error {
/home/gchp/github.com/reem/rust-error/src/lib.rs:84     fn fmt(&self, f: &mut Formatter) -> fmt::Result { (*self).fmt(f) }
/home/gchp/github.com/reem/rust-error/src/lib.rs:85 }
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: http://doc.rust-lang.org/complement-bugreport.html
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:123

stack backtrace:
   1:     0x7fecf8f88410 - sys::backtrace::write::hb159f9850e834894l1s
   2:     0x7fecf8fad150 - failure::on_fail::hd4fb51e7b66e269fxgz
   3:     0x7fecf8f12f20 - rt::unwind::begin_unwind_inner::he95e3015bc1198c6tVy
   4:     0x7fecf3c69dd0 - rt::unwind::begin_unwind::h1691522525006698826
   5:     0x7fecf3c69d60 - diagnostic::SpanHandler::span_bug::h419846186c6e05bbkEF
   6:     0x7fecf739a360 - middle::traits::error_reporting::report_fulfillment_error::h23831a3c82b7aea8LKO
   7:     0x7fecf72752f0 - middle::traits::error_reporting::report_fulfillment_errors::h85e3379b4029c0b8gKO
   8:     0x7fecf8666950 - check::vtable::select_all_fcx_obligations_or_error::h019e719f5fe0b73dqkb
   9:     0x7fecf86e3f00 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>::with_fcx::h13038663566178139740
  10:     0x7fecf86e70d0 - check::wf::CheckTypeWellFormedVisitor<'ccx, 'tcx>.Visitor<'v>::visit_item::hb054f0eb679dabcaMqi
  11:     0x7fecf87f3ae0 - check_crate::unboxed_closure.40379
  12:     0x7fecf87ee720 - check_crate::h3f64d3a4a846d0b2Nrx
  13:     0x7fecf94c8cd0 - driver::phase_3_run_analysis_passes::had0a81b4c9f8a9cd6va
  14:     0x7fecf94b6b50 - driver::compile_input::h4f21f66f6761bb22vba
  15:     0x7fecf957f640 - thunk::F.Invoke<A, R>::invoke::h1208443586143045988
  16:     0x7fecf957e3f0 - rt::unwind::try::try_fn::h4735177180287591181
  17:     0x7fecf9011810 - rust_try_inner
  18:     0x7fecf9011800 - rust_try
  19:     0x7fecf957e740 - thunk::F.Invoke<A, R>::invoke::h6623100047367797814
  20:     0x7fecf8f993d0 - sys::thread::thread_start::h89f54a8cba556c09RSv
  21:     0x7fecf348a0c0 - start_thread
  22:     0x7fecf8bbaec9 - __clone
  23:                0x0 - <unknown>

Could not compile `error`.

Caused by:
  Process didn't exit successfully: `rustc /home/gchp/github.com/reem/rust-error/src/lib.rs --crate-name error --crate-type lib -g -C metadata=45f77992efd3bf02 -C extra-filename=-45f77992efd3bf02 --out-dir /home/gchp/github.com/reem/rust-error/target --emit=dep-info,link -L dependency=/home/gchp/github.com/reem/rust-error/target -L dependency=/home/gchp/github.com/reem/rust-error/target/deps --extern typeable=/home/gchp/github.com/reem/rust-error/target/deps/libtypeable-99b257d6c5d5d947.rlib` (status=101)
```

I'm on Ubunut 14.04 with `rustc 1.0.0-nightly (ea6f65c5f 2015-01-06 19:47:08 +0000)`

**Comment by huonw** [comment] 2015-01-11 08:02
Dupe of https://github.com/rust-lang/rust/issues/20595, thanks for filing!

**Closed by huonw** 2015-01-11 08:02 UTC
Labels: A-traits, I-ICE
