### ISSUE TITLE
Double-panic when thread local drop eprintlns (only with stable 1.43.0)

### ISSUE THREAD

**Issue by vakaras** [rust-lang/rust#71536] opened 2020-04-24 22:12 UTC
The example below double-panics (segfaults) with stable 1.43.0, but I cannot see any reason why this should happen.

I am not sure whether this is already fixed or not because I could reproduce it only with the latest stable version of the Rust compiler, but not with nightly or beta. However, I could not find any related issue on the issue tracker, so decided to open a new one.

I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=088b387ac500e4e989ff8e1fee9d1b70)):

```rust
struct TestCell {}

impl Drop for TestCell {
    fn drop(&mut self) {
        eprintln!("Dropping")
    }
}

thread_local! {
    static A: TestCell = TestCell {};
}

fn main() {
    A.with(|_| {});
    eprintln!("Continue main.")
}
```

I expected the program to print the following as it does with nightly and beta versions of the compiler:
```
Continue main.
Dropping
```

Instead, I get the following output:
```
Continue main.
thread panicked while processing panic. aborting.
fish: “./test” terminated by signal SIGILL (Illegal instruction)
```

### Meta

I can reproduce the bug only on the stable version of the compiler.

`rustc --version --verbose`:
```
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-unknown-linux-gnu
release: 1.43.0
LLVM version: 9.0
```

**Comment by Mark-Simulacrum** [comment] 2020-04-24 22:20
I expect this was fixed by either https://github.com/rust-lang/rust/pull/69959 or https://github.com/rust-lang/rust/pull/69955, most likely the latter. In any case, given that beta/nightly work I'm going to go ahead and close since it seems like it's not a bug any more at least.

**Closed by Mark-Simulacrum** 2020-04-24 22:20 UTC
Labels: C-bug

**Comment by vakaras** [comment] 2020-04-26 16:31
Thank you for pointing out the relevant PRs!
