### ISSUE TITLE
Rustdoc: Trait implementations for Debug, Copy, Clone etc. link to nightly/core, even on stable

### ISSUE THREAD

**Issue by chordowl** [rust-lang/rust#41000] opened 2017-04-01 17:12 UTC
When generating documentation for a type that implements Debug, Copy, Clone etc., the links regarding those traits in the Trait Implementations section link to, e.g., <https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html>.

I expected them to link to <https://doc.rust-lang.org/std/fmt/trait.Debug.html> etc.

To reproduce: `rustdoc test.rs`, where test.rs contains the following

```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Foo(u8);

// It's not dependant on it being derived, either
pub struct Bar(u8);

impl Clone for Bar {
    fn clone(&self) -> Bar {
        Bar(self.0)
    }
}
```

<details>
<summary>Meta</summary>

`rustdoc --version --verbose`:

rustdoc 1.16.0 (30cf806ef 2017-03-10)
binary: rustdoc
commit-hash: 30cf806ef8881c41821fbd43e5cf3699c5290c16
commit-date: 2017-03-10
host: x86_64-pc-windows-gnu
release: 1.16.0
LLVM version: 3.9
</details>

**Comment by durka** [comment] 2017-04-01 19:54
This has always been true and I believe it's due to [this line](https://github.com/rust-lang/rust/blob/master/src/libstd/lib.rs#L207) (and the corresponding one in core). Maybe that attribute should be made to be dependent on release channel, in the compiler build process?

**Comment by kzys** [comment] 2018-09-28 05:00
This line is the cause, as @durka wrote.

https://github.com/rust-lang/rust/blob/1e21c9a297a9fe668d62887a3a6a4add8e717b17/src/libstd/lib.rs#L215

**Comment by ollie27** [comment] 2020-10-10 09:54
Duplicate of #30693

**Closed by ollie27** 2020-10-10 09:54 UTC
Labels: C-bug, T-dev-tools, T-rustdoc
