### ISSUE TITLE
error: internal compiler error: encountered incremental compilation error with item_children(canvas[d547])

### ISSUE THREAD

**Issue by tawfik741** [rust-lang/rust#86872] opened 2021-07-04 20:08 UTC
This occured when trying to install servo using MSVC on windows:

```
error: internal compiler error: encountered incremental compilation error with item_children(canvas[d547])
  |
  = help: This is a known issue with the compiler. Run `cargo clean -p compositing` or `cargo clean` to allow your project to compile
  = note: Please follow the instructions below to create a bug report with the provided information
  = note: See <https://github.com/rust-lang/rust/issues/84970> for more information

thread 'rustc' panicked at 'Found unstable fingerprints for item_children(canvas[d547]): [Export { ident: raqote_backend#0, res: Def(Mod, DefId(285:5 ~ canvas[d547]::raqote_backend)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:12:1: 12:20 (#0), vis: Restricted(DefId(285:0 ~ canvas[d547])) }, Export { ident: canvas_data#0, res: Def(Mod, DefId(285:235 ~ canvas[d547]::canvas_data)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:16:1: 16:21 (#0), vis: Public }, Export { ident: canvas_paint_thread#0, res: Def(Mod, DefId(285:555 ~ canvas[d547]::canvas_paint_thread)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:17:1: 17:29 (#0), vis: Public }, Export { ident: webgl_limits#0, res: Def(Mod, DefId(285:645 ~ canvas[d547]::webgl_limits)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:18:1: 18:18 (#0), vis: Restricted(DefId(285:0 ~ canvas[d547])) }, Export { ident: webgl_mode#0, res: Def(Mod, DefId(285:687 ~ canvas[d547]::webgl_mode)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:19:1: 19:16 (#0), vis: Restricted(DefId(285:0 ~ canvas[d547])) }, Export { ident: webgl_thread#0, res: Def(Mod, DefId(285:810 ~ canvas[d547]::webgl_thread)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:20:1: 20:22 (#0), vis: Public }, Export { ident: bitflags#0, res: Def(Mod, DefId(39:0 ~ bitflags[84c8])), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:8:1: 8:23 (#0), vis: Restricted(DefId(285:0 ~ canvas[d547])) }, Export { ident: log#0, res: Def(Mod, DefId(14:0 ~ log[febc])), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:10:1: 10:18 (#0), vis: Restricted(DefId(285:0 ~ canvas[d547])) }, Export { ident: WebGLComm#0, res: Def(Struct, DefId(285:780 ~ canvas[d547]::webgl_mode::inprocess::WebGLComm)), span: C:\Users\Tawfik\dev\opensource\servo\components\canvas\lib.rs:14:9: 14:30 (#0), vis: Public }]', /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\compiler\rustc_query_system\src\query\plumbing.rs:619:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (3e99439f4 2021-05-17) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=lld-link.exe -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [item_children] collecting child items of `canvas`
#1 [visible_parent_map] calculating the visible parent map
end of query stack

```

**Comment by jonas-schievink** [comment] 2021-07-04 20:10
Presumably this is a duplicate of https://github.com/rust-lang/rust/issues/85019

**Closed by jonas-schievink** 2021-07-04 20:10 UTC
Labels: A-incr-comp, C-bug, I-ICE, T-compiler
