### ISSUE TITLE
Inconsistent derivation for type which stores associated type

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#115181] opened 2023-08-24 18:55 UTC
I tried this code:

```rust
#[derive(Debug)]
pub struct Foo<T: Iterator>(T::Item);

#[derive(Debug)]
pub struct Bar<T: Iterator>(<T as Iterator>::Item);
```

I expected to see this happen: either both structs cause a compilation error or neither do.

Instead, this happened: the first struct is accepted and the second causes a compilation error:
```
> cargo b
   Compiling foo v0.0.0 ([redacted])
error[E0277]: `<T as Iterator>::Item` doesn't implement `Debug`
 --> src/main.rs:5:29
  |
4 | #[derive(Debug)]
  |          ----- in this derive macro expansion
5 | pub struct Bar<T: Iterator>(<T as Iterator>::Item);
  |                             ^^^^^^^^^^^^^^^^^^^^^ `<T as Iterator>::Item` cannot be formatted using `{:?}` because it doesn't implement `Debug`
  |
  = help: the trait `Debug` is not implemented for `<T as Iterator>::Item`
  = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `foo` (bin "foo") due to previous error

```

### Meta

`rustc --version --verbose`:
```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.71.1
LLVM version: 16.0.5
```

**Comment by fmease** [comment] 2024-11-20 06:42
Duplicate of https://github.com/rust-lang/rust/issues/50730

**Closed by fmease** 2024-11-20 06:42 UTC
Labels: A-traits, A-macros, A-associated-items, T-compiler, C-bug
