### ISSUE TITLE
Rust doesn't pass -ldl when dladdr (and others) are used

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/rust#47714] opened 2018-01-24 16:16 UTC
Recently in Fedora we enabled `-z defs` which is turning on:

```
     defs
        Report unresolved symbol references from regular object files.
        This is done even if the linker is creating a non-symbolic
        shared library.  This option is the inverse of -z undefs.
```

I've tried to build librsvg which is making static library from crate and it fails with:

```
*** Warning: Linking the shared library librsvg-2.la against the
*** static library /home/brain/Projects/fedora/rpms/librsvg2/librsvg-2.42.1/rust/target/release/librsvg_internals.a is not portable!
/home/brain/Projects/fedora/rpms/librsvg2/librsvg-2.42.1/rust/target/release/librsvg_internals.a(rsvg_internals-b823acfb4918fe68.rsvg_internals0.rcgu.o): In function `std::sys::imp::backtrace::printing::dladdr::resolve_symname<closure>':
/builddir/build/BUILD/rustc-1.23.0-src/src/libstd/sys/unix/backtrace/printing/dladdr.rs:25: undefined reference to `dladdr'
/builddir/build/BUILD/rustc-1.23.0-src/src/libstd/sys/unix/backtrace/printing/dladdr.rs:25: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
```

It seems that rust doesn't pass `-ldl` when it's dl* functions are used.

**Comment by cuviper** [comment] 2018-01-24 22:03
Perhaps it needs something like `#[link(name = "dl"]`, but I think you'll still be missing something here when the shared library tries to link that `librsvg_internals.a` -- which is out of rustc's hands.

**Comment by fweimer** [comment] 2018-01-25 08:35
Does cargo produce `librsvg_internals.a`? Maybe it could emit two files, a linker script and the actual archive.

**Comment by cuviper** [comment] 2018-01-25 18:49
@fweimer Yes, cargo+rustc produced that.  Emitting a linker script sounds interesting -- do other toolchains do this automatically?

ISTR there used to be a message printed for static libraries, telling the user what libraries should be linked in the final product -- but I don't see anything like that in the full log that Igor provided to me.

**Comment by alexcrichton** [comment] 2018-01-26 04:55
We [should be linking](https://github.com/rust-lang/rust/blob/master/src/libstd/build.rs#L38) with `-ldl` do you have more logs for the error perhaps?

Also it's true yeah, I'm not sure how a static archive can be verified as it can't encode linking information?

**Comment by cgwalters** [comment] 2021-01-28 00:16
One of the things libtool does addresses this problem - there's no way I'd recommend we involve libtool :smile: but I don't see why rustc couldn't add extra metadata into the archives it produces and consume it, because in this case it can assume it's also the linker.

**Comment by fweimer** [comment] 2021-06-26 08:25
This will be fixed by upgrading to glibc 2.34—`libdl.a` is empty (so that `-ldl` keeps working), and `dlopen` etc. are always available.

**Comment by cgwalters** [comment] 2021-06-26 16:38
On Sat, Jun 26, 2021, at 4:25 AM, Florian Weimer wrote:
> 
> 
> This will be fixed by upgrading to glibc 2.34—`libdl.a` is empty (so 
> that `-ldl` keeps working), and `dlopen` etc. are always available.

Thanks!

**Comment by bjorn3** [comment] 2023-07-13 12:58
If you are producing a static library you need to link it with the arguments output by `--print native-static-libs` when compiling the static library. Static libraries unfortunately can't embed the linker arguments they need to successfully link.

**Comment by Mark-Simulacrum** [comment] 2024-01-14 23:35
I'm going to go ahead and close this as it sounds like this is largely expected behavior that we can't do much about.

**Closed by Mark-Simulacrum** 2024-01-14 23:35 UTC
Labels: A-linkage, C-enhancement, T-compiler
