### ISSUE TITLE
Attempting destructuring of struct reference to mutable variable results in partial moves of fields

### ISSUE THREAD

**Issue by cdmistman** [rust-lang/rust#102669] opened 2022-10-04 17:33 UTC
I tried this code:

```rust
struct Foo {
    bar: Bar,
}

struct Bar;

fn with_bar(bar: &Bar) {}

fn main() {
    let foo = Foo { bar: Bar };
    let Foo { mut bar } = &foo;
    with_bar(bar);
}

```

I expected to see this happen: The above should compile with `bar` being a mutable variable of type `&Bar`

Instead, this happened: The above fails to compile with `bar` being a mutable variable of type `Bar`.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (015a824f2 2022-08-22)
binary: rustc
commit-hash: 015a824f2dffe32707fceb59c47effaf7b73486c
commit-date: 2022-08-22
host: aarch64-apple-darwin
release: 1.65.0-nightly
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
error[[E0308]](https://doc.rust-lang.org/stable/error-index.html#E0308): mismatched types
  --> src/main.rs:12:14
   |
12 |     with_bar(bar);
   |     -------- ^^^
   |     |        |
   |     |        expected `&Bar`, found struct `Bar`
   |     |        help: consider borrowing here: `&bar`
   |     arguments to this function are incorrect
   |
note: function defined here
  --> src/main.rs:7:4
   |
7  | fn with_bar(bar: &Bar) {}
   |    ^^^^^^^^ ---------

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```

</p>
</details>

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ff607310b4fff61e520c992b0043e51f)

**Comment by Enselic** [comment] 2024-10-04 14:40
Triage: Addressed by https://github.com/rust-lang/rfcs/pull/3627 (see various referenced issues). Closing as duplicate.

**Comment by compiler-errors** [comment] 2024-10-04 14:49
I don't think this issue should be closed until the referenced RFC is stabilized. This issue still reproduces on all version of Rust, afaict?

**Comment by Enselic** [comment] 2024-10-04 14:54
Hmm, you are right. We should probably create a label to make it easy to track bugs related to the implememtation.

**Comment by compiler-errors** [comment] 2024-10-04 14:57
it's not a bug, it's just not stable behavior yet. It's gated behind a feature.

**Comment by traviscross** [comment] 2024-10-08 19:43
Tracking:

- https://github.com/rust-lang/rust/issues/123076

**Comment by Nadrieril** [comment] 2024-10-27 09:18
This _is_ a duplicate of https://github.com/rust-lang/rust/issues/105647 though

**Comment by traviscross** [comment] 2024-10-27 18:35
Closing in favor of:

- https://github.com/rust-lang/rust/issues/105647

**Closed by traviscross** 2024-10-27 18:35 UTC
Labels: T-compiler, C-bug, A-patterns
