### ISSUE TITLE
Internal compiler error when building docs in GH Actions

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/rust#84041] opened 2021-04-09 20:06 UTC
Using this GitHub Actions workflow file:

```
name: Docs

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  deploy_docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build Documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps --manifest-path ./core/Cargo.toml --target-dir ./docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doc
```

originally worked, but then started failing with the following error.

```
    Checking tide v0.16.0
error: internal compiler error: compiler/rustc_mir/src/transform/generator.rs:751:13: Broken MIR: generator contains type Pin<Box<dyn std::future::Future<Output = std::result::Result<response::Response, http_types::Error>> + std::marker::Send>> in MIR, but typeck only knows about for<'r, 's, 't0> {ResumeTy, &'r F, request::Request<State>, middleware::Next<'s, State>, Pin<Box<(dyn std::future::Future<Output = std::result::Result<response::Response, http_types::Error>> + std::marker::Send + 't0)>>, ()}
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.16.0/src/middleware.rs:35:89
   |
35 |       async fn handle(&self, req: Request<State>, next: Next<'_, State>) -> crate::Result {
   |  _________________________________________________________________________________________^
36 | |         (self)(req, next).await
37 | |     }
   | |_____^

thread 'rustc' panicked at 'Box<Any>', /rustc/2e495d2e845cf27740e3665f718acfd3aa17253e/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (2e495d2e8 2021-04-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `middleware::<impl at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.16.0/src/middleware.rs:24:1: 38:2>::handle::{closure#0}`
end of query stack
error: aborting due to previous error

error: could not compile `tide`

To learn more, run the command again with --verbose.
```

Downgrading to a previous nightly release fixed this for me.

**Comment by jonas-schievink** [comment] 2021-04-09 20:15
duplicate of https://github.com/rust-lang/rust/issues/83737

**Closed by jonas-schievink** 2021-04-09 20:15 UTC
Labels: C-bug, I-ICE, T-compiler
