### ISSUE TITLE
Infinite recursion returns random number in WASM

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust#68624] opened 2020-01-29 00:17 UTC
Hi guys, take a look at this funny code:

```rust
use std::rc::Rc;
use std::ops::Deref;

pub trait HasId {
    fn id(&self) -> usize;
}

pub trait AnyNodeOps {}
impl AnyNodeOps for () {}

pub struct AnyNode {
    rc: Rc<dyn AnyNodeOps>,
}

impl HasId for AnyNode {
    fn id(&self) -> usize {
        self.deref().id()
    }
}

pub fn main() {
    let node = AnyNode {rc: Rc::new(())};
    println!("{}", node.id())
}
```

It prints a random number when compiled to WASM.

By the way, I know that this is how traits work in Rust, but I find **extremely** unexpected / error-prone that an infinite loop can be caused by so innocent looking code. It happened to me when refactoring code when I accidentally removed `Deref` instance - everything still compiled fine but with different results every run. It was fun to debug 😬

**Comment by jonas-schievink** [comment] 2020-01-29 00:25
Duplicate of https://github.com/rust-lang/rust/issues/28728

**Comment by wdanilo** [comment] 2020-01-29 00:26
From 2015 ? ...

**Closed by jonas-schievink** 2020-01-29 00:25 UTC

**Comment by wdanilo** [comment] 2020-01-29 00:28
@jonas-schievink Are you sure it is the same issue? My example RETURNS `usize` from an infinite loop. It does not crash like described in the linked ticket.

**Comment by jonas-schievink** [comment] 2020-01-29 00:29
Infinite loops are undefined behavior in LLVM, which can result in anything
