### ISSUE TITLE
Broken MIR: Nested Match With Const Byte Slice

### ISSUE THREAD

**Issue by GGist** [rust-lang/rust#42289] opened 2017-05-28 21:28 UTC
I tried this code:

```
const MY_PROTOCOL: &'static [u8] = b"MyProtocol";

#[derive(Debug)]
enum Protocol {
    MyProtocol,
    Custom(Vec<u8>)
}

fn main() {
    let protocol = b"MyProtocol";
    
    println!("{:?}", parse_real_protocol(&protocol[..]));
}

fn parse_real_protocol(bytes: &[u8]) -> Option<Protocol> {
    match {
        match true {
            true  => Some(bytes),
            false => None
        }
    } {
        Some(MY_PROTOCOL) => Some(Protocol::MyProtocol),
        Some(custom)      => Some(Protocol::Custom(custom.to_vec())),
        None              => None
    }
}
```

I expected to see this happen: compiles fine

Instead, this happened:

```
$ cargo run
   Compiling testing v0.1.0 (file:///C:/users/amill/GitHub/testing)
error: internal compiler error: broken MIR (((_3 as Some).0: &'static [u8; 10])): bad field access (&[u8]: &'static [u8; 10]): Sorts(ExpectedFound { expected: [u8; 10], found: [u8] })
  --> src\main.rs:22:14
   |
22 |         Some(MY_PROTOCOL) => Some(Protocol::MyProtocol),
   |              ^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:421
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

## Meta

`rustc --version --verbose`:
```
rustc 1.19.0-nightly (28fd1e519 2017-05-27)
binary: rustc
commit-hash: 28fd1e519a3807c632d58d01e73b4948000639ba
commit-date: 2017-05-27
host: x86_64-pc-windows-msvc
release: 1.19.0-nightly
LLVM version: 4.0
```

Backtrace:
```
thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:421
stack backtrace:
   0: <std::time::SystemTimeError as core::fmt::Display>::fmt
   1: std::panicking::Location::line
   2: std::panicking::Location::line
   3: std::panicking::rust_panic_with_hook
   4: <unknown>
   5: <unknown>
   6: <rustc_mir::transform::type_check::TypeVerifier<'a, 'b, 'gcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_mir
   7: <rustc_mir::transform::type_check::TypeVerifier<'a, 'b, 'gcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_mir
   8: <rustc_mir::transform::type_check::TypeVerifier<'a, 'b, 'gcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_rvalue
   9: <rustc_mir::transform::type_check::TypeVerifier<'a, 'b, 'gcx, 'tcx> as rustc::mir::visit::Visitor<'tcx>>::visit_mir
  10: <rustc_mir::transform::type_check::TypeckMir as rustc::mir::transform::MirPass>::run_pass
  11: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::get_drop_flag
  12: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::get_drop_flag
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_const<'tcx>>::try_get
  14: rustc::ty::maps::TyCtxtAt::mir_const
  15: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_const
  16: <rustc_mir::shim::DropShimElaborator<'a, 'tcx> as rustc_mir::util::elaborate_drops::DropElaborator<'a, 'tcx>>::get_drop_flag
  17: rustc::ty::maps::<impl rustc::ty::maps::queries::mir_validated<'tcx>>::try_get
  18: rustc::ty::maps::TyCtxtAt::mir_validated
  19: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::mir_validated
  20: rustc_borrowck::borrowck::provide
  21: rustc::ty::maps::<impl rustc::ty::maps::queries::borrowck<'tcx>>::try_get
  22: rustc::ty::maps::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::borrowck
  23: rustc_borrowck::borrowck::check_crate
  24: rustc_driver::driver::count_nodes
  25: rustc_driver::driver::count_nodes
  26: rustc_driver::driver::compile_input
  27: rustc_driver::run_compiler
  28: <unknown>
  29: _rust_maybe_catch_panic
  30: <rustc_driver::derive_registrar::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor<'v>>::visit_trait_item
  31: std::sys::imp::thread::Thread::new
  32: BaseThreadInitThunk

error: Could not compile `testing`.
```

---

Indeed, subbing out the constant in the match for just ```b"MyProtocol"``` works as expected. Note that the above code is a bit nonsensical, but it was simplified from:
```
#[macro_use]
extern crate nom;

use nom::{be_u8, rest, IResult};

const MY_PROTOCOL: &'static [u8] = b"MyProtocol";

#[derive(Debug)]
enum Protocol {
    MyProtocol,
    Custom(Vec<u8>)
}

fn main() {
    let mut protocol = b"MyProtocol";
    
    println!("{:?}", parse_real_protocol(&protocol[..]));
}

fn parse_real_protocol(bytes: &[u8]) -> IResult<&[u8], Protocol> {
    switch!(bytes, rest,
        MY_PROTOCOL => value!(Protocol::MyProtocol) |
        custom      => value!(Protocol::Custom(custom.to_vec()))
    )
}
```

Where I ran ```cargo rustc -- -Z unstable-options --pretty=expanded``` to come up with a simplified version.

**Comment by eddyb** [comment] 2017-06-07 06:03
Reduced to:
```rust
const FOO: &'static [u8] = b"foo";

fn test(bytes: &[u8]) {
    match Some(bytes) {
        Some(FOO) => {}
        _ => {}
    }
}

fn main() {
    test(FOO);
}
```

**Comment by eddyb** [comment] 2017-06-07 06:03
cc @nikomatsakis @arielb1

**Comment by nikomatsakis** [comment] 2017-06-07 21:32
looks like there is some kind of unsize coercion that we are overlooking when handling matching on constants?

**Comment by nikomatsakis** [comment] 2017-06-08 20:25
triage: P-medium

**Comment by nikomatsakis** [comment] 2017-06-08 20:25
This doesn't appear to be a regression, so not P-high, but we should really see if we can fix it. Might be a good place to write up mentoring instructions.

**Comment by oli-obk** [comment] 2018-03-06 16:07
I think I fixed this in https://github.com/rust-lang/rust/pull/46882
I'll check once it's been merged

**Comment by oli-obk** [comment] 2018-04-05 14:43
Jup has been fixed

**Closed by oli-obk** 2018-04-05 14:43 UTC
Labels: A-mir, C-bug, P-medium, T-compiler
