### ISSUE TITLE
rustdoc fails

### ISSUE THREAD

**Issue by fulmicoton** [rust-lang/rust#46297] opened 2017-11-27 04:41 UTC
Since the last nightly release, `cargo doc` fails building tantivy's documentation.

This can be observed here with rustc (1.23.0 nightly -2017-11-25)
https://travis-ci.org/tantivy-search/tantivy/builds/307688630

The error message is as follows

```
 `Running `rustdoc --crate-name tantivy src/lib.rs -o /home/travis/build/tantivy-search/tantivy/target/doc --cfg 'feature="cc"' --cfg 'feature="default"' --cfg 'feature="libc"' --cfg 'feature="simdcompression"' -L dependency=/home/travis/build/tantivy-search/tantivy/target/debug/deps --extern time=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libtime-8237071fe8657a08.rlib --extern uuid=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libuuid-9403cb82c28076aa.rlib --extern lazy_static=/home/travis/build/tantivy-search/tantivy/target/debug/deps/liblazy_static-a979d65fa128a463.rlib --extern chan=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libchan-0b25d9a7f4503c8a.rlib --extern futures=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libfutures-54cd692c1689be85.rlib --extern fst=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libfst-56a834807aa0581b.rlib --extern lz4=/home/travis/build/tantivy-search/tantivy/target/debug/deps/liblz4-5ca3d6a6ba90cfb4.rlib --extern serde=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libserde-35e6d80dcc22e88a.rlib --extern combine=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libcombine-a178d80e728e70f2.rlib --extern atomicwrites=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libatomicwrites-b8d0e96009a1a846.rlib --extern tempdir=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libtempdir-13a97722ede069a3.rlib --extern regex=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libregex-c21a0aa18fe5a16f.rlib --extern serde_json=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libserde_json-5f68f5c24b0a5c11.rlib --extern itertools=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libitertools-4103a1b00dad63c9.rlib --extern serde_derive=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libserde_derive-821299eca585e76a.so --extern owning_ref=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libowning_ref-aee6bf529da98915.rlib --extern num_cpus=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libnum_cpus-e7fd59f6a071341b.rlib --extern libc=/home/travis/build/tantivy-search/tantivy/target/debug/deps/liblibc-11f5c817d6e936c6.rlib --extern version=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libversion-5cc498e2ee13c94f.rlib --extern bincode=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libbincode-3088a77b01cdac1e.rlib --extern error_chain=/home/travis/build/tantivy-search/tantivy/target/debug/deps/liberror_chain-30e76a5a999bdb61.rlib --extern memmap=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libmemmap-46a4d65ffe1a2c96.rlib --extern crossbeam=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libcrossbeam-32308a34852f5057.rlib --extern rust_stemmers=/home/travis/build/tantivy-search/tantivy/target/debug/deps/librust_stemmers-0598ca8c9208f021.rlib --extern stable_deref_trait=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libstable_deref_trait-a0c4d8436df6654c.rlib --extern log=/home/travis/build/tantivy-search/tantivy/target/debug/deps/liblog-aeba76529f3abcf2.rlib --extern tempfile=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libtempfile-f7be284bf769f18e.rlib --extern futures_cpupool=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libfutures_cpupool-6cb562b7d049e73c.rlib --extern byteorder=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libbyteorder-f17a8441808d68d1.rlib --extern bit_set=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libbit_set-6fc71ebc7e486e78.rlib --extern tinysegmenter=/home/travis/build/tantivy-search/tantivy/target/debug/deps/libtinysegmenter-9dc9ea03a45dcee5.rlib``

error: internal compiler error: /checkout/src/librustc/hir/map/mod.rs:298: called HirMap::read() with invalid NodeId
```

**Comment by kennytm** [comment] 2017-11-27 09:49
Duplicate of #46271.

**Closed by kennytm** 2017-11-27 09:49 UTC
