### ISSUE TITLE
`#[plugin(...)]` at the top level should cause an error; `#![plugin(...)]` is correct

### ISSUE THREAD

**Issue by apoelstra** [rust-lang/rust#24213] opened 2015-04-08 23:01 UTC
Right now if you write `#[plugin(...)]` to import some syntax extension, the import simply won't happen and other errors will occur. For example, if you write `#[plugin(serde_macros)]` and then later do `#[derive(Serialize)]` on a type you will get errors about `Serialize` not being implemented, as though the derive had done nothing.

This is extremely confusing since a user is basically being told "#derive had no effect" when the real problem is a missing exclamation mark in a totally different source file.

This should trigger an error to use `#![plugin(...)]` instead.

cc @erickt

**Comment by nagisa** [comment] 2015-04-09 12:59
Duplicate of https://github.com/rust-lang/rust/issues/2809

**Comment by jonas-schievink** [comment] 2015-08-17 10:08
The same works for `no_std` and probably all other gated attributes, since they are ignored by the `unused_attributes` lint. In other cases, the lint already prints "crate-level attribute should be an inner attribute: add an exclamation mark: #![foo]", but gated attributes cannot simultaneously be marked as `CrateLevel`.

**Closed** 2015-08-29 23:49 UTC
Labels: A-diagnostics, A-plugin
