### ISSUE TITLE
unimplemented macro doesnt compile with RPIT

### ISSUE THREAD

**Issue by 95th** [rust-lang/rust#63794] opened 2019-08-21 18:05 UTC
I believe the following should compile but doesn't.

```
trait Foo {}

fn bar() -> impl Foo {
    unimplemented!()
}
```

I get the following error:

```
 --> src/main.rs:7:13
  |
7 | fn bar() -> impl Foo {
  |             ^^^^^^^^ the trait `Foo` is not implemented for `()`
  |
  = note: the return type of a function must have a statically known size
```

However, this compiles:
```
fn bar<X: Foo>() -> X {
    unimplemented!()
}
```

Could anybody confirm if this is a bug or I am missing something very obvious?

**Comment by jonas-schievink** [comment] 2019-08-21 18:19
This isn't *really* a bug, at least. The type `impl Foo` stands for needs to be inferred somehow, and right now the compiler defaults to `()` in this situation. With `#![feature(never_type)]` it would default to `!`, with the same result (right now).

In the second example, the type is just a type parameter specified by the caller, so no issue occurs.

**Comment by 95th** [comment] 2019-08-22 08:12
@jonas-schievink The compiler shouldn't default to `()` for `impl Foo`. So doesn't that make it a bug? 
Also, with never type `!`, the trait bound `!: Foo` is not satisfied.

This would mean that you can't leave functions having `impl` trait return types unimplemented.

**Comment by jonas-schievink** [comment] 2019-08-22 11:46
What type *should* it choose, then? I don't think this is an easy question to answer in all cases.

Diverging control flow (which is what you get after a panic) can generally be of any type, since the code is unreachable. Rustc falls back to assigning `()` if there is no known, concrete type to assign (this has been the case since before 1.0, I believe). This doesn't really have much to do with `impl Trait`, specifically.

That said, it would be nice to get this example working *somehow*, since `unimplemented!()` would be quite useful.

**Comment by memoryruins** [comment] 2019-09-05 10:00
Duplicate of #55022 ?

**Comment by jonas-schievink** [comment] 2019-09-05 10:45
Yup, closing

**Closed by jonas-schievink** 2019-09-05 10:45 UTC
Labels: A-impl-trait, C-feature-request, T-lang
