### ISSUE TITLE
Rust osx packaging installs with wrong permissions

### ISSUE THREAD

**Issue by xasmx** [rust-lang/rust#20499] opened 2015-01-04 02:08 UTC
Tried the new (jan-3) nightly rust package for osx.
The permissions seem to be wrong after installation so can't run anything without su:

Samis-MacBook-Pro:~ sami$ ls -al /usr/local/bin/rust*
-rwx------  1 root  wheel   1226 Jan  3 18:14 /usr/local/bin/rust-lldb
-rwx------  1 root  wheel  13112 Jan  3 18:14 /usr/local/bin/rustc
-rwx------  1 root  wheel  13112 Jan  3 18:14 /usr/local/bin/rustdoc

Running on OSX Yosemite 10.10

**Comment by brson** [comment] 2015-01-04 06:01
Thanks for testing! I'll look into this tomorrow.

**Comment by nPix06mwh0w** [comment] 2015-01-05 05:51
For the sake of completeness, only the following files and folders are missing the correct permissions:
# find /usr/local \! -perm '+g+r'
/usr/local/bin/cargo
/usr/local/bin/rust-lldb
/usr/local/bin/rustc
/usr/local/bin/rustdoc
/usr/local/components
/usr/local/COPYRIGHT
/usr/local/etc
/usr/local/install.sh
/usr/local/lib
/usr/local/LICENSE-APACHE
/usr/local/LICENSE-MIT
/usr/local/manifest-cargo.in
/usr/local/manifest-rust-docs.in
/usr/local/manifest-rustc.in
/usr/local/README.md
/usr/local/rust-installer-version
/usr/local/share/doc
/usr/local/share/man/man1/cargo.1
/usr/local/share/man/man1/rustc.1
/usr/local/share/man/man1/rustdoc.1
/usr/local/share/zsh

Corrected applying the following command:
# for i in $(find /usr/local \! -perm '+g+r'); do sudo chmod -R go+rx $i; done
# rustc --version
rustc 0.13.0-nightly (c6c786671 2015-01-04 00:50:59 +0000)

**Comment by brson** [comment] 2015-01-05 19:14
@nPix06mwh0w Are you also on 10.10 Yosemite?

I can't reproduce this with the current nightly on 10.8.

@xasmx @nPix06mwh0w did this work correctly prior to last week?

**Comment by xasmx** [comment] 2015-01-05 19:24
Have installed the nightly several times within the last two weeks prior to the new jan-3 packaging and had no problems before it.

**Comment by nPix06mwh0w** [comment] 2015-01-05 19:26
I am indeed on Yosemite 10.10.
I can't answer if it worked before, as I just started using rust on Mac.

**Comment by brson** [comment] 2015-01-05 19:27
Are you two using the .pkg installers or the .tar.gz?

**Comment by nPix06mwh0w** [comment] 2015-01-05 19:28
I am using the .pkg installer.

**Comment by xasmx** [comment] 2015-01-05 19:28
Using .pkg here

**Comment by brson** [comment] 2015-01-05 19:28
Aha! A lead. Thanks.

**Comment by kballard** [comment] 2015-01-05 19:33
The .pkg installer definitely has the wrong permissions on the files.

**Comment by kballard** [comment] 2015-01-05 19:51
The root cause here is the nightly rustc-* tarballs that the package installer is created from have the wrong permissions. These permissions are propagated everywhere. Installing from the tarball works because the install script sets permissions. But the package installer pulls the permissions from the filesystem it's given as the package root, and therefore uses the same permissions that the nightly tarballs used.

**Comment by brson** [comment] 2015-01-05 21:54
Should be fixed by https://github.com/rust-lang/rust-packaging/commit/a20d18fd6a00240e27b618b6f435907bdd9fb19a. I'm building new nightlies now.

**Comment by brson** [comment] 2015-01-05 22:46
New nightlies are up that fix this.

**Closed by brson** 2015-01-05 22:46 UTC
Labels: A-build, A-mac-osx
