### ISSUE TITLE
Const function sized arrays fail to evaluate `Sized` bound

### ISSUE THREAD

**Issue by p-avital** [rust-lang/rust#63916] opened 2019-08-26 14:59 UTC
Hello,

I was trying to have generic arrays that occupy as much of a single cache line as possible, but get a compile error when trying to use `std::mem::size_of<T>()`, as the `T: Sized` constraint seems to be evaluated later than [T; N] seems to require the value.

Is this behaviour normal? Is there an alternative?
I've included an example of the behaviour.
Thanks.

```rust
// #[feature(const_generics)] // In case someone asks: tried it, doesn't help.
use std::mem::MaybeUninit;

const fn fit_array_into<T: Sized>(size: usize) -> usize{
    size / std::mem::size_of::<T>()
}

struct SmallArray<T: Sized>([MaybeUninit<T>; fit_array_into::<T>(64)]); // comment to build

#[derive(Copy, Clone, Debug)]
struct CopyArray<T: Copy>(pub [T; 3]);

pub fn main() {
    let test: [MaybeUninit<u64>; fit_array_into::<u64>(64)] = unsafe {std::mem::MaybeUninit::uninit().assume_init()};
    let test: SmallArray<u64> = unsafe {std::mem::MaybeUninit::uninit().assume_init()}; // comment to build
    let test: CopyArray<u64> = CopyArray([0, 1, 2]);
    let copy = test;
    println!("test: {:?}, copy: {:?}", test, copy);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b0e42fdf93b1bd804507174d9d4439c3))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `T` cannot be known at compilation time
 --> src/main.rs:8:46
  |
8 | struct SmallArray<T: Sized>([MaybeUninit<T>; fit_array_into::<T>(64-56)]);
  |                                              ^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `T`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = help: consider adding a `where T: std::marker::Sized` bound
note: required by `fit_array_into`
 --> src/main.rs:4:1
  |
4 | const fn fit_array_into<T: Sized>(size: usize) -> usize{
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by Centril** [comment] 2019-08-26 19:23
Reduced:
```rust
const fn fit_array_into<T>() -> usize {
    core::mem::size_of::<T>()
}

struct SmallArray<T: Sized>([core::mem::MaybeUninit<T>; fit_array_into::<T>()]);
```

Seems like the standard "anonymous constants cannot reference parameters" issue.

**Comment by stevecheckoway** [comment] 2019-10-01 15:14
Reduced further:
```rust
struct SmallArray<T: Sized>([u8; core::mem::size_of::<T>()]);
```

I don't know if this is an issue of the compiler help being wrong (as `T` has the `Sized` bound already) or if this is a bug in the compiler.

**Comment by jonas-schievink** [comment] 2019-10-01 15:21
Duplicate of https://github.com/rust-lang/rust/issues/43408

**Closed by jonas-schievink** 2019-10-01 15:21 UTC
Labels: A-const-eval, A-const-fn, A-traits, C-bug, T-compiler
