### ISSUE TITLE
compile cdylib is ok,but staticlib can't link to __cxxframehandler3

### ISSUE THREAD

**Issue by jamesvan2019** [rust-lang/rust#62795] opened 2019-07-19 04:16 UTC
env : windows10 
compile with cdylib is ok,just copy dll to windows path
but with staticlib , can build success , but can't link to __cxxframehandler3
panic="abort" didn't useful
nm xxx.lib                 
                 U __CxxFrameHandler3
                 U __CxxFrameHandler3
                 U __CxxFrameHandler3

**Comment by jonas-schievink** [comment] 2019-07-19 08:41
Might be a duplicate of https://github.com/rust-lang/rust/issues/54137

**Comment by Enselic** [comment] 2024-12-28 19:44
Triage: No objections to the suggestion that this is a duplicate. Closing as duplicate.

**Closed by Enselic** 2024-12-28 19:44 UTC
Labels: A-linkage, O-windows, T-compiler
