### ISSUE TITLE
Compiles without errors but fails on linking(no FFI)

### ISSUE THREAD

**Issue by Eilie** [rust-lang/rust#17610] opened 2014-09-28 16:09 UTC
Hello,

Code from https://gist.github.com/Eilie/76bca04969992e471f4d compiles just fine but fails at linking stage. Here's what I've got on #rust:

<pre>
 kimundi >>> ainieco: So, its probably a combination of bugs/misuse
  in cargo and rustc where it does 
 not recompile the library you depend on, and rustc does not do enough 
 version checking to notice that it links against a old version of the lib
 without that symbol
</pre>

**Comment by steveklabnik** [comment] 2015-09-03 15:45
Triage: this still happens. I've made a repo to make it a bit easier than the linked gist, with syntax updates. https://github.com/steveklabnik/rust-issue-17610

**Comment by jminer** [comment] 2015-12-30 20:59
Likely a dupe of #16734 (there's a [comment in #20201](https://github.com/rust-lang/rust/issues/20201#issuecomment-68196288) that explains that bug). In this case, it is a field instead of a method but otherwise looks the same.

**Comment by alexcrichton** [comment] 2016-01-11 21:39
Ah yeah I think this is a dupe of #16734, so closing in favor of that. Thanks @jminer!

**Closed by alexcrichton** 2016-01-11 21:39 UTC
Labels: A-linkage, I-compiletime
