### ISSUE TITLE
Rustdoc: No link to source for trait provided methods

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#79142] opened 2020-11-17 17:16 UTC
I tried this code:

```rust
pub trait Numbers {
    fn get_a_number(&self) -> i32;

    fn get_larger_number(&self) -> i32 {
        self.get_a_number() + 1
    }
}

pub struct NumberFive;

impl Numbers for NumberFive {
    fn get_a_number(&self) -> i32 {
        5
    }
}

```

I expected to see this happen: Provided method `Numbers::get_larger_number` has link to source

Instead, it doesnt.

![image](https://user-images.githubusercontent.com/28781354/99422817-d6c1f280-28f7-11eb-93b8-db86842f4636.png)

Interestingly on the docs for `impl Numbers for NumberFive` include the link, even though the impl is in the trait definition, not the block implementing the trait for `Numbers`.
![image](https://user-images.githubusercontent.com/28781354/99423003-04a73700-28f8-11eb-91cc-789c8548decd.png)

![image](https://user-images.githubusercontent.com/28781354/99423551-92832200-28f8-11eb-9178-a32e366c488a.png)

### Meta

`rustc --version --verbose`:
```

rustc --version --verbose
rustc 1.50.0-nightly (f5230fbf7 2020-11-16)
binary: rustc
commit-hash: f5230fbf76bafd86ee4376a0e26e551df8d17fec
commit-date: 2020-11-16
host: x86_64-apple-darwin
release: 1.50.0-nightly
```

**Comment by jyn514** [comment] 2020-11-17 20:24
Duplicate of https://github.com/rust-lang/rust/issues/45150

**Closed by jyn514** 2020-11-17 20:24 UTC
Labels: C-bug, T-rustdoc
