### ISSUE TITLE
Operands of "non-regular" versions of arithmetic ops don't infer whereas regular ops operands do

### ISSUE THREAD

**Issue by DustinByfuglien** [rust-lang/rust#72526] opened 2020-05-24 07:46 UTC
For programmer point of view there is no visible reason that operands of "non-regular" versions of arithmetic operators (saturating, overflowing, ...) can't be inferred in some situations when "regular" do it.

```rust
fn main() {
    let mut sum = 0;
    sum = sum + 1_usize;                // Ok
    let mut sum = 0;
    sum = sum.saturating_add(1_usize);  // Error
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a702893dab3a9b6a5086ac8d11fceb4f))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0689]: can't call method `saturating_add` on ambiguous numeric type `{integer}`
 --> src/main.rs:5:15
  |
5 |     sum = sum.saturating_add(1_usize);  // Error
  |               ^^^^^^^^^^^^^^
  |
help: you must specify a type for this binding, like `i32`
  |
4 |     let mut sum: i32 = 0;
  |         ^^^^^^^^^^^^

```

It could be nice if saturating version of ```sum``` can be inferred to ```usize``` too.

**Comment by bluss** [comment] 2020-05-24 09:25
Hi, this issue has already been reported.

Duplicate of #24124

**Closed by bluss** 2020-05-24 09:25 UTC
