### ISSUE TITLE
ICE: no terminator on block

### ISSUE THREAD

**Issue by djrodgerspryor** [rust-lang/rust#46902] opened 2017-12-21 11:05 UTC
I found an ICE when playing around with statics and result matching.

Minimal example:

```rust
extern crate reqwest;

static RESULT: bool = match reqwest::get("https://google.com/") {
    Ok(res) => res.status().is_success(),
    Err(_) => panic!("Oh no!"),
};

fn main() {
}
```

Output from rust playground:
```
   Compiling playground v0.0.1 (file:///playground)
error: internal compiler error: /checkout/src/librustc_mir/build/mod.rs:534: no terminator on block 10
 --> src/main.rs:3:1
  |
3 | / static RESULT: bool = match reqwest::get("https://google.com/") {
4 | |     Ok(res) => res.status().is_success(),
5 | |     Err(_) => panic!("Oh no!"),
6 | | };
  | |__^

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-nightly (7eb64b86c 2017-12-20) running on x86_64-unknown-linux-gnu

thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:449:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Comment by arielb1** [comment] 2017-12-21 12:03
Duplicate of #46843.

**Closed by arielb1** 2017-12-21 12:03 UTC
