### ISSUE TITLE
[regression] 1.52 and 1.53 link to recursive methods in the sidebar, but those methods are not documented

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#85037] opened 2021-05-07 14:47 UTC
### Code

I don't have time to make an MCVE right now.

Stable and beta: ![image](https://user-images.githubusercontent.com/23638587/117466657-f8a04780-af20-11eb-8beb-211e64fee77f.png)

Nightly and 1.51: 
![image](https://user-images.githubusercontent.com/23638587/117466819-1ec5e780-af21-11eb-8caa-f74321f7a608.png)

1.50: 
![image](https://user-images.githubusercontent.com/23638587/117467158-6e0c1800-af21-11eb-88c1-52786d9a9d4a.png)

Either the methods should be documented, or they shouldn't be linked to.

cc @pnkfelix I suspect this is regression from the backports of https://github.com/rust-lang/rust/pull/84867.

**Comment by Stupremee** [comment] 2021-05-14 18:40
First of all, here's an MVCE:
```rust
use std::ops::Deref;

pub struct A {}
impl A { pub fn foo_a(&self) {} }

pub struct B {}
impl B { pub fn foo_b(&self) {} }

pub struct C {}
impl C { pub fn foo_c(&self) {} }

impl Deref for A {
    type Target = B;
    fn deref(&self) -> &B { todo!() }
}

impl Deref for B {
    type Target = C;
    fn deref(&self) -> &C { todo!() }
}
```

What should the correct behavior be? Since you marked this as a regression, I guess the version in 1.50 is "correct"?

**Comment by pietroalbini** [comment] 2021-06-14 14:28
Removed `regression-from-stable-to-beta`, this is not a 1.53 regression.

**Comment by jyn514** [comment] 2021-06-14 14:31
@pietroalbini sure, then it's a stable-to-stable regression then. It first regressed in 1.52.

**Closed** 2021-06-18 10:34 UTC
Labels: A-rustdoc, C-bug, I-prioritize, regression-from-stable-to-stable
