### ISSUE TITLE
Macro import does not bring dependent macros in scope in 2018 edition

### ISSUE THREAD

**Issue by starkat99** [rust-lang/rust#53811] opened 2018-08-30 01:44 UTC
Importing a macro from a crate in 2018 edition that invokes other macros does not bring those macros in scope. It's easy enough to make work by importing the other macros of course, but surprising behavior anyway, especially when it involves importing macros that won't actually be referenced anywhere in the file itself, only through invocations.

Example (using clap 2.32):
```rust
use clap::app_from_crate;
fn main() {
    let _args = app_from_crate!().get_matches();
}
```
will produce the following error
```
error: cannot find macro `crate_name!` in this scope
 --> src\main.rs:5:17
  |
5 |     let _args = app_from_crate!().get_matches();
  |                 ^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by Arnavion** [comment] 2018-08-31 00:03
I believe this is by design for `macro_rules` macros. Macros 2.0 are the only ones that have def-site-scoped dependencies.

**Comment by jonas-schievink** [comment] 2019-04-21 22:54
`local_inner_macros` seems to fix this, so closing.

**Closed by jonas-schievink** 2019-04-21 22:54 UTC
