### ISSUE TITLE
linking with gcc failed

### ISSUE THREAD

**Issue by Jojoshua** [rust-lang/rust#21656] opened 2015-01-26 14:31 UTC
This has bugged me enough to post an issue. I've got some code on a network drive and sometimes when I build it using rustc I will get this error. If I retry rustc a few times it eventually compiles. This does not happen when I move the code to my local C: drive. 

error: linking with `gcc` failed: exit code: 1
note: gcc '-Wl,--enable-long-section-names' '-fno-use-linker-plugin' '-Wl,--nxco
mpat' '-static-libgcc' '-m64' '-L' 'C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\li
b' '-o' 'MyProgram.exe' 'MyProgram.o' '-Wl,--gc-sections' 'C:\Rust\bin\rustlib
\x86_64-pc-windows-gnu\lib\libstd-4e7c5e5c.rlib' 'C:\Rust\bin\rustlib\x86_64-pc-
windows-gnu\lib\libcollections-4e7c5e5c.rlib' 'C:\Rust\bin\rustlib\x86_64-pc-win
dows-gnu\lib\libunicode-4e7c5e5c.rlib' 'C:\Rust\bin\rustlib\x86_64-pc-windows-gn
u\lib\librand-4e7c5e5c.rlib' 'C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\liba
lloc-4e7c5e5c.rlib' 'C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\liblibc-4e7c5
e5c.rlib' 'C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\libcore-4e7c5e5c.rlib'
'-L' 'C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib' '-L' 'U:\RustProjects\Block
Solve\src\.rust\bin\x86_64-pc-windows-gnu' '-L' 'U:\RustProjects\MyProgram\src\
bin\x86_64-pc-windows-gnu' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-
archive' '-Wl,-Bdynamic' '-lws2_32' '-lcompiler-rt'
note: ld: cannot open output file MyProgram.exe: Permission denied

**Comment by retep998** [comment] 2015-01-26 16:00
Does this issue only occur when you try to build a program when an existing binary is already there, or can it occur when you are building something for the first time?
When building something again, rustc has to delete the original and deleting a file returns immediately while the actual deletion may finish some time later. This is especially pronounced on network drives with high latency. As a result, by the time rustc tries to output the new binary the old binary might not be deleted yet, thus resulting in this error.

**Comment by Jojoshua** [comment] 2015-01-26 16:13
Yes, it only happens when there is an existing binary. If I delete the binary before compiling it works everytime.

**Comment by retep998** [comment] 2015-02-11 01:20
I believe the issue would be solved by Rust checking if an old binary exists, deleting it, and then blocking the linking stage on a polling loop asking the OS if the file still exists.

**Comment by retep998** [comment] 2015-06-08 00:30
A similar issue occurs when creating rlibs sometimes. In fact, it even occurs after a `cargo clean` so its not a matter of an old file not being deleted yet.
```
error: "ar" "crs" "C:\msys64\home\Peter\winapi-rs\target\debug\deps\libmpr-3fc99212b55b9740.rlib" "mpr-3fc9921
2b55b9740.o" "rust.metadata.bin" "mpr-3fc99212b55b9740.0.bytecode.deflate" failed with: exit code: 1
note: stdout ---

note: stderr ---
ar: C:\msys64\home\Peter\winapi-rs\target\debug\deps\libmpr-3fc99212b55b9740.rlib: Permission denied
```
It appears that for whatever reason there's still a handle on the rlib by the time `ar` tries to write to it which causes it to error since it is presumably trying to open it exclusively.

**Comment by larsbergstrom** [comment] 2015-06-11 00:42
In my experience, most cases where users encountered these were caused by either indexing services or anti-virus programs that are looped into the filesytem change and still have an open handle even after you've called delete (and the deleting process has terminated!), and this problem is probably just exacerbated over a slow(-er) network connection. Unfortunately, AFAIK, there's no good clean way to handle that. Certainly, the only public info I'm aware of on this problem confirms:
http://blogs.msdn.com/b/oldnewthing/archive/2012/09/07/10347136.aspx

**Comment by alexcrichton** [comment] 2015-09-03 20:54
It looks like this is an expected error and there's not a huge amount we can do about it, so closing as working as intended.

**Closed by alexcrichton** 2015-09-03 20:54 UTC
Labels: A-linkage, A-windows
