### ISSUE TITLE
dropck seems overconservative when dealing with matches at the end of a block

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#22252] opened 2015-02-13 03:02 UTC
```rust
#![feature(unsafe_destructor)]
struct A;

impl Drop for A {
    fn drop(&mut self) {}
}

struct B<'a> {
    a: &'a A,
}

#[unsafe_destructor]
impl<'a> Drop for B<'a> {
    fn drop(&mut self) {}
}

impl A {
    fn b(&self) -> B {
        B { a: self }
    }
}

fn main() {
    let a = A;
    match a.b() {
        _ => {}
    }
}
```

```
test.rs:25:11: 25:12 error: `a` does not live long enough
test.rs:25     match a.b() {
                     ^
test.rs:23:11: 28:2 note: reference must be valid for the destruction scope surrounding block at 23:10...
test.rs:23 fn main() {
test.rs:24     let a = A;
test.rs:25     match a.b() {
test.rs:26         _ => {}
test.rs:27     }
test.rs:28 }
test.rs:24:14: 28:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 24:13
test.rs:24     let a = A;
test.rs:25     match a.b() {
test.rs:26         _ => {}
test.rs:27     }
test.rs:28 }
error: aborting due to previous error
```

Adding anything after the match (like `;` or `()`) causes the error to go away.

cc @pnkfelix

**Comment by sfackler** [comment] 2015-02-13 03:05
This may be a dup of #21114

**Comment by ebfull** [comment] 2015-02-13 11:20
I think I'm having a similar issue:

```rust
use std::collections::HashMap;
use std::sync::Mutex;

fn i_used_to_be_able_to(foo: &Mutex<HashMap<usize, usize>>) -> Vec<(usize, usize)> {
    let mut foo = foo.lock().unwrap();

    foo.drain().collect()
}

fn but_after_nightly_update_now_i_gotta(foo: &Mutex<HashMap<usize, usize>>) -> Vec<(usize, usize)> {
    let mut foo = foo.lock().unwrap();

    return foo.drain().collect();
}

fn main() {}
```

**Comment by pnkfelix** [comment] 2015-02-14 09:15
I think this might be a consequence of our rules for r-value temporaries, where the temporaries in the expression at the end of a block are assigned a lifetime longer than that of the `let`-bindings within the block itself.

But then again, that answer is not very satisfying without an example of what kind of unsoundness this is supposedly preventing.  (I do not have an example ready on hand, but you've given me a place to start.)

**Comment by pnkfelix** [comment] 2015-02-14 09:16
cc #22321

**Comment by pnkfelix** [comment] 2015-02-14 10:00
also, cc #12032 ;)

**Comment by theemathas** [comment] 2015-02-23 03:40
The problem does not require a `match`

Simpler reproduction code:
```rust
#![feature(unsafe_destructor)]

struct Foo;
struct FooRef<'a>(&'a Foo);

impl<'a> FooRef<'a> {
    fn borrow(&self) {}
}

#[unsafe_destructor]
impl<'a> Drop for FooRef<'a> {
    fn drop(&mut self) {}
}

fn main() {
    let x = Foo;
    FooRef(&x).borrow()
}
```
[playpen](http://is.gd/HWxDTH)

The error:
```rust
<anon>:17:13: 17:14 error: `x` does not live long enough
<anon>:17     FooRef(&x).borrow()
                      ^
<anon>:15:11: 18:2 note: reference must be valid for the destruction scope surrounding block at 15:10...
<anon>:15 fn main() {
<anon>:16     let x = Foo;
<anon>:17     FooRef(&x).borrow()
<anon>:18 }
<anon>:16:16: 18:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 16:15
<anon>:16     let x = Foo;
<anon>:17     FooRef(&x).borrow()
<anon>:18 }
```

**Comment by steveklabnik** [comment] 2016-05-24 20:34
Triage: no change, at least for the example provided by @theemathas

**Comment by arielb1** [comment] 2016-05-24 21:34
This looks like a duplicate of #33490

**Closed** 2016-05-24 21:36 UTC
Labels: A-destructors

**Comment by sfackler** [comment] 2016-05-24 22:01
@arielb1 This is a bug about a compilation error, not a runtime failure, so I don't think this is a duplicate of that issue (which was also filed a year and a half after this one).

**Comment by arielb1** [comment] 2016-06-11 13:40
@sfackler 

The issues have the same root cause - borrowck/MIR have a notion of destruction order that makes this code obviously wrong. Trans uses a different destruction order, but that is problematic.

**Comment by mbrubeck** [comment] 2016-09-14 16:47
#33490 is closed but this issue still exists in nightly.  Without the `unsafe_destructor` flags, the test case above still generates the same compiler error.  The similar cases from #31439 and https://github.com/rust-lang/rust/issues/21114#issuecomment-228331214 also still fail to compile in nightly. Should this be re-opened?

**Comment by sfackler** [comment] 2016-09-14 16:48
#33490 seems open to me?

**Comment by mbrubeck** [comment] 2016-09-14 16:56
Oops, I meant that comments like https://github.com/rust-lang/rust/issues/33490#issuecomment-218382664 claimed that MIR now behaves correctly and that only old trans was still broken.
