### ISSUE TITLE
regression: assertion `left == right` failed but it depends on library-unstable details

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#128899] opened 2024-08-09 17:31 UTC
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/chubei.project_euler/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/bbarker.bevy_serde_macros/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/tommarek.MPCHomeControl/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/lht102.coding-problems-practice/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/rainhead.rust-anagrams/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/atrocious_sort-0.1.2/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/gaffer-0.2.0/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/hopscotch-0.1.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/proxmox-api-0.1.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/rwini-0.1.1/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/reg/workpool-0.2.1/log.txt

```
[INFO] [stdout] thread 'tests::test_primie_factorization' panicked at src/lib.rs:132:9:
[INFO] [stdout] assertion `left == right` failed
[INFO] [stdout]   left: [PrimeFactor { prime: 2, power: 2 }, PrimeFactor { prime: 5, power: 3 }]
[INFO] [stdout]  right: [PrimeFactor { prime: 5, power: 3 }, PrimeFactor { prime: 2, power: 2 }]
```

**Comment by workingjubilee** [comment] 2024-08-10 00:32
It is probably the case that these are all incorrect sort algorithm impls.

I am bringing these to the attention of @orlp and @Voultapher if they wish to inspect the regressions further.

**Comment by workingjubilee** [comment] 2024-08-10 00:46
No sorting appears to occur in https://github.com/survemobility/gaffer/blob/fd1cc240414bb5ee61c840538e0ed4f83e5d58dd/tests/integration.rs or the rest of the library at a glance, so I believe that's instead a concurrency bug.

**Comment by Voultapher** [comment] 2024-08-10 07:59
> coding-problems-practice has a now-failing-tests solution, but it actually is still correct according to the original problem.
> the tests seem to rely on sort_unstable_by having sorted things a certain way,

`sort_unstable*` is unstable as the name says and the new implementation is deterministic as the previous one was, but it produces a different equal element ordering than the one before, so a test that relies on one specific order but uses `sort_unstable` is only valid for one version of Rust.

> however, the original problem specifically mentions that it's okay to get either "eert" or "eetr"

I think the correct to test that would be to do stable sort or `assert_matches!(val, "eert" | "eetr")`.

**Comment by Voultapher** [comment] 2024-08-10 08:03
> atrocious_sort: appears to be failing in a sort, yes, but is specifically failing on sleep_sort only. did we change something about concurrency? https://github.com/Chromfalke/AtrociousSort/blob/main/src/algorithms/sleep_sort.rs

Looking at the implementation, it sleeps for milliseconds, I fail to see how that could ever work reliably. The OS can decide to wake the threads up whenever. Plus it doesn't use latches, so it's spawn + sleep before the next thread is spawned. IMO that implementation is just plain broken.

**Comment by Voultapher** [comment] 2024-08-10 08:25
I'm a little surprised by how many instances there are of relying on the order of hashmaps, the order is randomized with the default hasher. Looking at the linked code they seem to be using the default hasher, how come these tests ever reliably work during local development? What am I missing here?

**Comment by Voultapher** [comment] 2024-08-10 09:58
> gaffer
> Other initial hypothesis is that the library is doing panic recovery. Perhaps some other library in its dep tree is sorting but then panic recovery occurs? https://github.com/survemobility/gaffer/commit/f238bae67739f0df4ef4a97b245e8554c8aff6f2

I suspect it's just racy. I checked the project out locally and ran `cargo t`, on my initial run I got:

```
test source::test::queued_resets_recurring ... FAILED

failures:

---- source::test::queued_resets_recurring stdout ----
thread 'source::test::queued_resets_recurring' panicked at src/source.rs:320:9:
assertion `left == right` failed
  left: [Tester(3), Tester(2), Tester(1)]
 right: [Tester(2)]


failures:
    source::test::queued_resets_recurring

test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```

Which is a completely different test, and the one in the crater run passed. Second run all tests pass.

**Comment by orlp** [comment] 2024-08-10 10:03
@workingjubilee I find the `proxmox-api` case very strange: <https://github.com/datdenkikniet/proxmox-api/blob/7d7540839371e3a58837b049997fe5fb8816d0cf/proxmox-api/src/types/multi.rs#L241-L255>

Note that the portion of the `serde` output that was changed is actually a `BTreeMap`, not a `HashMap`.

**Comment by workingjubilee** [comment] 2024-08-10 21:52
@orlp Thanks for catching that! I retract my comments re: "iterating over a hashmap", but it still seems very odd.

**Comment by workingjubilee** [comment] 2024-08-10 21:58
Somewhat shockingly, the Project Euler code is also operating with a hashmap: https://github.com/chubei/project_euler/blob/d100bed4c6b7c417276ccba051567c53ed869d40/src/lib.rs#L39-L48

**Comment by workingjubilee** [comment] 2024-08-10 21:59
> I'm a little surprised by how many instances there are of relying on the order of hashmaps, the order is randomized with the default hasher. Looking at the linked code they seem to be using the default hasher, how come these tests ever reliably work during local development? What am I missing here?

There is a certain sort of person who only ever writes and runs a test once.

**Comment by workingjubilee** [comment] 2024-08-10 22:36
I downloaded workpool and reran its tests a few times. It's another racy case. I think we've correctly identified racy library tests in:
- atrocious_sort
- gaffer
- workpool

And what seem to be definitely hashmap problems:
- chubei/project-euler
- rainhead/rust-anagrams
- rwini

Unless these are fixed promptly, we should ignore those in future crater runs which cover tests.

Correctly root-caused to the sort impl, but known accepted breakage:
- lht102/coding-problems-practice

I didn't really know where to start with [MPCHomeControl's log](https://crater-reports.s3.amazonaws.com/beta-1.81-2/beta-2024-07-26/gh/tommarek.MPCHomeControl/log.txt) so I have not examined it closely. That leaves the following as still open questions as to why the test is failing to begin with:
- bevy_serde_macros
- hopscotch
- tommarek/MPCHomeControl
- proxmox-api

**Comment by workingjubilee** [comment] 2024-08-10 22:40
Ah, MPCHomeControl is a float problem, actually. I'll bring it to https://github.com/rust-lang/rust/issues/128898

**Comment by saethlin** [comment] 2024-08-11 03:03
I haven't looked at these crates carefully.

I know there are quite a few crates which are tested by crater that have test suites that are designed in various ways such that they are incompatible with multiple tests running at once. This would be fixed once and for all if crater would set the number of CPUs in each container to 1.

**Comment by Voultapher** [comment] 2024-08-11 08:03
> I know there are quite a few crates which are tested by crater that have test suites that are designed in various ways such that they are incompatible with multiple tests running at once. This would be fixed once and for all if crater would set the number of CPUs in each container to 1.

It's a little off topic and if this turns into a bigger discussion let's please find a better place for it. My 2 cents, if your tests are order dependent and or can't be run in parallel they are broken. I'd rather tell these libraries you choose to break the tooling's expectations, so you can't expect us to care for your use-case.

Specifically with the racy libraries here I'm not sure it would even help:

- atrocious_sort: Broken impl, single-core testing won't help.
- gaffer: Docs say: "some of the tests are very dependent on timing and will fail if run slowly", so not sure how single-core testing would help.
- workpool: No docs whatsoever, sporadic test failure, not sure how single-core testing would help.

**Comment by Voultapher** [comment] 2024-08-11 09:31
- bevy_serde_macros

<img width="1474" alt="image" src="https://github.com/user-attachments/assets/b6eda4f6-ebdd-4da6-abca-485019ac0c2f">

I think it's our good friend hashmap order [see](https://github.com/bbarker/bevy_serde_macros/blob/main/src/lib.rs#L264), which constructs two hashmaps and does `assert_eq!`. Beware this is `hashbrown::HashMap` with a `PartialEq` implementation [like this](https://docs.rs/hashbrown/0.14.5/src/hashbrown/map.rs.html#2182). Which is order dependent. The stdlib one has the same [impl](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#1286-1292). Now that I think of it, isn't that quite the big footgun that `PartialEq` is implemented that way?

**Comment by Voultapher** [comment] 2024-08-11 09:43
- proxmox-api

Is once again also hashmap order, the `main` branch defines `Names` as:

```rust
#[derive(Debug, Deserialize, Serialize, PartialEq)]
struct Names {
    #[serde(
        flatten,
        deserialize_with = "super::deserialize_multi_btree::<'_, NumberedNames, _>",
        serialize_with = "super::serialize_multi_btree::<NumberedNames, _>"
    )]
    names: BTreeMap<u32, String>,
    #[serde(
        flatten,
        deserialize_with = "super::deserialize_additional_data::<'_, Names, _, _>"
    )]
    additional_data: HashMap<String, String>,
}
```

Where the field `additional_data` is a hashmap. But in the test it only accounts for the `name_2` key and not for `name1` or `name2` which are the ones that swap place in the produced JSON string. However if look at the v0.1.1 tag `Names` has a different definition:

```rust
#[derive(Debug, Deserialize, Serialize, PartialEq)]
struct Names {
    #[serde(
        flatten,
        deserialize_with = "super::deserialize_multi::<'_, NumberedNames, _>",
        serialize_with = "super::serialize_multi::<NumberedNames, _>"
    )]
    names: HashMap<u32, String>,
    #[serde(
        flatten,
        deserialize_with = "super::deserialize_additional_data::<'_, Names, _, _>"
    )]
    additional_data: HashMap<String, String>,
}
```

Now the fields `names` *and* `additional_data` are `HashMap`s. This is the version that was tested by the crater run. Mystery solved 😄

**Comment by Nemo157** [comment] 2024-08-11 10:32
> I think it's our good friend hashmap order [see](https://github.com/bbarker/bevy_serde_macros/blob/main/src/lib.rs#L264), which constructs two hashmaps and does `assert_eq!`. Beware this is `hashbrown::HashMap` with a `PartialEq` implementation [like this](https://docs.rs/hashbrown/0.14.5/src/hashbrown/map.rs.html#2182). Which is order dependent. The stdlib one has the same [impl](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#1286-1292). Now that I think of it, isn't that quite the big footgun that `PartialEq` is implemented that way?

Equality doesn't care about which order you check the keys in, the debug output is different but that shouldn't affect the comparison result.

**Comment by Voultapher** [comment] 2024-08-11 10:47
- hopscotch

This is not a regression. Locally the tests `partial_ord_correct` and `ord_correct` fail with some chance both on stable and nightly. I've seen all 4 combinations of success and fail on for both versions of Rust. I think it depends on wether quickcheck finds a code path where the properties don't hold, which I assume depends on randomness.

Digging into why it fails, as example input that fails let's take `left = [(66, 1)]` and `right = [(66, 0), (0, 0)]`. The tests compare `partial_cmp` and `cmp` results. `compare_as_iters` answers what the keys compared via the the [`iterator::cmp`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.cmp) method yields. In this case `[66].iter().cmp([66, 0].iter()) == Ordering::Less`. In contrast the `hopscotch::Queue::cmp` method uses completely different logic and does offset and tag comparisons before going over to value, not key, iter comparison. In this specific instance tag comparison yields `Ordering::Greater` which causes the mismatch and test failure.

In my opinion either the test does not test what the author wanted it to test, or the implementation does not do what the author intended it to do.

**Comment by Voultapher** [comment] 2024-08-11 10:48
Given the lack of active maintenance and sub 10k downloads, it might make sense to deny-list some of these crates that fail because of broken tests and or implementations.

**Comment by Voultapher** [comment] 2024-08-11 11:31
> Equality doesn't care about which order you check the keys in

My bad, indeed the `other.get` call makes it order independent.

**Comment by orlp** [comment] 2024-08-11 13:00
Would it be possible to add a `clippy` warning to some code patterns which attempt to `assert` an expression that depends on hashmap iteration order?

**Comment by workingjubilee** [comment] 2024-08-11 21:16
I guess I retract my retraction regarding proxmox-api???

**Comment by workingjubilee** [comment] 2024-08-11 21:18
I guess we should test a revert of https://github.com/rust-lang/rust/pull/125174

**Comment by workingjubilee** [comment] 2024-08-11 21:24
Hm, #125174 was cratered.

**Comment by workingjubilee** [comment] 2024-08-11 22:27
The proxmox-api tests may work on the next crater run, so let's not exclude those.

I've opened some PRs and issues:
- https://github.com/lht102/coding-problems-practice/pull/6
- https://github.com/zerodegress/rwini-rs/issues/1
- https://github.com/rainhead/rust-anagrams/pull/1
- https://github.com/chubei/project_euler/pull/1
- https://github.com/Chromfalke/AtrociousSort/issues/1
- https://github.com/survemobility/gaffer/issues/3
- https://github.com/ggriffiniii/lateral/issues/2

It seems unlikely these will all be resolved by the next beta crater run.

In particular, the gaffer tests seem to be completely insoluble as it is an issue in essentially all the tests, so let's just skip that crate's tests from now on.

**Comment by workingjubilee** [comment] 2024-08-11 23:00
I have opened some followups:
- https://github.com/rust-lang/rust/issues/128948
- https://github.com/rust-lang/rust/issues/128992
- https://github.com/rust-lang/crater/pull/732

Everything else is accepted breakage, or (hopefully) will be published and fixed for the next beta crater, so I think we're done here.

**Closed by workingjubilee** 2024-08-11 23:00 UTC
Labels: T-compiler, regression-from-stable-to-beta, I-prioritize

**Comment by workingjubilee** [comment] 2024-08-11 23:08
Thank you for playing, everyone!
