### ISSUE TITLE
indoc ICE: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32

### ISSUE THREAD

**Issue by Be3y4uu-K0T** [rust-lang/rust#133176] opened 2024-11-18 15:48 UTC
### Code

```Rust
use {indoc::formatdoc, std::fmt};

#[derive(Default, Clone, Copy, PartialEq, Eq)]
pub enum Item {
    #[default]
    None,
    Key,
}

impl fmt::Display for Item {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        use Item::*;
        match self {
            None => write!(f, "{}", " "),
            Key => write!(f, "{}", "🔑"),
        }
    }
}

pub const SIZE: usize = 9;

#[derive(Default)]
pub struct Inventory([Item; SIZE]);

impl fmt::Display for Inventory {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let frame = formatdoc! { r#"
            ╔═══════╦═══════╦═══════╗
            ║       ║       ║       ║
            ║{  :^7}║{  :^7}║{  :^7}║
            ║       ║       ║       ║
            ╠═══════╬═══════╬═══════╣
            ║       ║       ║       ║
            ║{  :^7}║{  :^7}║{  :^7}║
            ║       ║       ║       ║
            ╠═══════╬═══════╬═══════╣
            ║       ║       ║       ║
            ║{  :^7}║{  :^7}║{  :^7}║
            ║       ║       ║       ║
            ╚═══════╩═══════╩═══════╝"#,
            self.0[0], self.0[1], self.0[2],
            self.0[3], self.0[4], self.0[5],
            self.0[6], self.0[7], self.0[8],
        };
        writeln!(f, "\x1Bc{frame}")
    }
}

fn main() {
    println!("{}", Inventory::default());
}
```

Cargo.toml
```
[package]
name = "rust-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.5"
```

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0 (f6e511eec 2024-10-15)
binary: rustc
commit-hash: f6e511eec7342f59a25f7c0534f1dbea00d01b14
commit-date: 2024-10-15
host: aarch64-apple-darwin
release: 1.82.0
LLVM version: 19.1.1
```

### Error output

```
$ cargo run
   Compiling rust-bug v0.1.0 (/Users/nikita/Desktop/rust-bug)
thread 'rustc' panicked at compiler/rustc_span/src/lib.rs:2027:17:
assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
stack backtrace:
   0:        0x10cb70bdc - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x10a13d770 - core::fmt::write::ha36a8060c13608ea
   2:        0x10cb64b0c - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x10cb732a4 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x10cb72ef8 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x10acaeafc - <alloc[764fc8c78a1bb3e1]::boxed::Box<rustc_driver_impl[d9f1096c2de14668]::install_ice_hook::{closure#0}> as core[fafc87a594706398]::ops::function::Fn<(&dyn for<'a, 'b> core[fafc87a594706398]::ops::function::Fn<(&'a std[d8d90c69e022292b]::panic::PanicHookInfo<'b>,), Output = ()> + core[fafc87a594706398]::marker::Sync + core[fafc87a594706398]::marker::Send, &std[d8d90c69e022292b]::panic::PanicHookInfo)>>::call
   6:        0x10cb74428 - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   7:        0x10cb73818 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   8:        0x10cb71084 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   9:        0x10cb73514 - _rust_begin_unwind
  10:        0x10f1efb60 - core::panicking::panic_fmt::h410d3f147658259b
  11:        0x10f1efbcc - core::panicking::panic::hee236ca94fc05047
  12:        0x10c5d4624 - <rustc_span[12a1c67e1f6abb]::SourceFile>::lookup_file_pos_with_col_display
  13:        0x10ad54334 - <rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan>::from_span_full::<core[fafc87a594706398]::iter::sources::from_fn::FromFn<<rustc_span[12a1c67e1f6abb]::span_encoding::Span>::macro_backtrace::{closure#0}>>
  14:        0x10ad540a0 - <rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan>::from_span_label
  15:        0x10ad2c98c - <alloc[764fc8c78a1bb3e1]::vec::Vec<rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan> as alloc[764fc8c78a1bb3e1]::vec::spec_from_iter::SpecFromIter<rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan, core[fafc87a594706398]::iter::adapters::map::Map<alloc[764fc8c78a1bb3e1]::vec::into_iter::IntoIter<rustc_error_messages[6db17c92cd4de685]::SpanLabel>, <rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan>::from_multispan::{closure#0}>>>::from_iter
  16:        0x10ad53598 - <rustc_errors[8ca33d4576cff18c]::json::Diagnostic>::from_errors_diagnostic
  17:        0x10ad52f80 - <rustc_errors[8ca33d4576cff18c]::json::JsonEmitter as rustc_errors[8ca33d4576cff18c]::emitter::Emitter>::emit_diagnostic
  18:        0x10ad3712c - <rustc_errors[8ca33d4576cff18c]::DiagCtxtInner>::emit_diagnostic::{closure#3}
  19:        0x10b544d1c - rustc_interface[8c972d485a8e2aa0]::callbacks::track_diagnostic::<core[fafc87a594706398]::option::Option<rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  20:        0x10ad36a74 - <rustc_errors[8ca33d4576cff18c]::DiagCtxtInner>::emit_diagnostic
  21:        0x10ad7e6fc - <rustc_errors[8ca33d4576cff18c]::diagnostic::Diag>::emit_producing_error_guaranteed
  22:        0x10a87a97c - rustc_builtin_macros[b635d0a9cd627de0]::format::make_format_args
  23:        0x10a87ddd0 - rustc_builtin_macros[b635d0a9cd627de0]::format::expand_format_args_impl
  24:        0x10add9090 - <rustc_expand[8c719bd15d3ec090]::expand::MacroExpander>::fully_expand_fragment
  25:        0x10add855c - <rustc_expand[8c719bd15d3ec090]::expand::MacroExpander>::expand_crate
  26:        0x10b4e4c94 - rustc_interface[8c972d485a8e2aa0]::passes::resolver_for_lowering_raw
  27:        0x10c154488 - rustc_query_impl[d98edaeb063d7c4c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d98edaeb063d7c4c]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1486d011505b3441]::query::erase::Erased<[u8; 16usize]>>
  28:        0x10c1a12d4 - <rustc_query_impl[d98edaeb063d7c4c]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[fafc87a594706398]::ops::function::FnOnce<(rustc_middle[1486d011505b3441]::ty::context::TyCtxt, ())>>::call_once
  29:        0x10c0b8f3c - rustc_query_system[1bcdf744069b5f02]::query::plumbing::try_execute_query::<rustc_query_impl[d98edaeb063d7c4c]::DynamicConfig<rustc_query_system[1bcdf744069b5f02]::query::caches::SingleCache<rustc_middle[1486d011505b3441]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[d98edaeb063d7c4c]::plumbing::QueryCtxt, true>
  30:        0x10c1cbeb4 - rustc_query_impl[d98edaeb063d7c4c]::query_impl::resolver_for_lowering_raw::get_query_incr::__rust_end_short_backtrace
  31:        0x10acef42c - <rustc_middle[1486d011505b3441]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}::{closure#1}::{closure#3}, &rustc_data_structures[4379925a6ea25aa8]::steal::Steal<(rustc_middle[1486d011505b3441]::ty::ResolverAstLowering, alloc[764fc8c78a1bb3e1]::rc::Rc<rustc_ast[7c0a23a770356630]::ast::Crate>)>>
  32:        0x10ac8f780 - <rustc_interface[8c972d485a8e2aa0]::interface::Compiler>::enter::<rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}::{closure#1}, core[fafc87a594706398]::result::Result<core[fafc87a594706398]::option::Option<rustc_interface[8c972d485a8e2aa0]::queries::Linker>, rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  33:        0x10aca4200 - <scoped_tls[db9af8800088675c]::ScopedKey<rustc_span[12a1c67e1f6abb]::SessionGlobals>>::set::<rustc_interface[8c972d485a8e2aa0]::util::run_in_thread_with_globals<rustc_interface[8c972d485a8e2aa0]::interface::run_compiler<core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>, rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}>::{closure#1}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  34:        0x10aca09fc - std[d8d90c69e022292b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8c972d485a8e2aa0]::util::run_in_thread_with_globals<rustc_interface[8c972d485a8e2aa0]::interface::run_compiler<core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>, rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}>::{closure#1}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  35:        0x10acad0c0 - <<std[d8d90c69e022292b]::thread::Builder>::spawn_unchecked_<rustc_interface[8c972d485a8e2aa0]::util::run_in_thread_with_globals<rustc_interface[8c972d485a8e2aa0]::interface::run_compiler<core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>, rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}>::{closure#1}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#1} as core[fafc87a594706398]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:        0x10cb7ed44 - std::sys::pal::unix::thread::Thread::new::thread_start::hd88bc8e95f2ca709
  37:        0x195b132e4 - __pthread_deallocate

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.82.0 (f6e511eec 2024-10-15) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
error: could not compile `rust-bug` (bin "rust-bug")
```

<details><summary><strong>Backtrace: RUST_BACKTRACE=1 cargo build</strong></summary>
<p>

```
$ RUST_BACKTRACE=1 cargo build
   Compiling rust-bug v0.1.0 (/Users/nikita/Desktop/rust-bug)
thread 'rustc' panicked at compiler/rustc_span/src/lib.rs:2027:17:
assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_span::SourceFile>::lookup_file_pos_with_col_display
   4: <rustc_errors::json::DiagnosticSpan>::from_span_full::<core::iter::sources::from_fn::FromFn<<rustc_span::span_encoding::Span>::macro_backtrace::{closure#0}>>
   5: <rustc_errors::json::DiagnosticSpan>::from_span_label
   6: <alloc::vec::Vec<rustc_errors::json::DiagnosticSpan> as alloc::vec::spec_from_iter::SpecFromIter<rustc_errors::json::DiagnosticSpan, core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<rustc_error_messages::SpanLabel>, <rustc_errors::json::DiagnosticSpan>::from_multispan::{closure#0}>>>::from_iter
   7: <rustc_errors::json::Diagnostic>::from_errors_diagnostic
   8: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   9: <rustc_errors::DiagCtxtInner>::emit_diagnostic::{closure#3}
  10: rustc_interface::callbacks::track_diagnostic::<core::option::Option<rustc_span::ErrorGuaranteed>>
  11: <rustc_errors::DiagCtxtInner>::emit_diagnostic
  12: <rustc_errors::diagnostic::Diag>::emit_producing_error_guaranteed
  13: rustc_builtin_macros::format::make_format_args
  14: rustc_builtin_macros::format::expand_format_args_impl
  15: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  16: <rustc_expand::expand::MacroExpander>::expand_crate
  17: rustc_interface::passes::resolver_for_lowering_raw
      [... omitted 2 frames ...]
  18: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}::{closure#3}, &rustc_data_structures::steal::Steal<(rustc_middle::ty::ResolverAstLowering, alloc::rc::Rc<rustc_ast::ast::Crate>)>>
  19: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.82.0 (f6e511eec 2024-10-15) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
error: could not compile `rust-bug` (bin "rust-bug")
```

</p>
</details>

<details><summary><strong>Backtrace: RUST_BACKTRACE=full cargo build</strong></summary>
<p>

```
$ RUST_BACKTRACE=full cargo build
   Compiling rust-bug v0.1.0 (/Users/nikita/Desktop/rust-bug)
thread 'rustc' panicked at compiler/rustc_span/src/lib.rs:2027:17:
assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32
stack backtrace:
   0:        0x10d788bdc - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x10ad55770 - core::fmt::write::ha36a8060c13608ea
   2:        0x10d77cb0c - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x10d78b2a4 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x10d78aef8 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x10b8c6afc - <alloc[764fc8c78a1bb3e1]::boxed::Box<rustc_driver_impl[d9f1096c2de14668]::install_ice_hook::{closure#0}> as core[fafc87a594706398]::ops::function::Fn<(&dyn for<'a, 'b> core[fafc87a594706398]::ops::function::Fn<(&'a std[d8d90c69e022292b]::panic::PanicHookInfo<'b>,), Output = ()> + core[fafc87a594706398]::marker::Sync + core[fafc87a594706398]::marker::Send, &std[d8d90c69e022292b]::panic::PanicHookInfo)>>::call
   6:        0x10d78c428 - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   7:        0x10d78b818 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   8:        0x10d789084 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   9:        0x10d78b514 - _rust_begin_unwind
  10:        0x10fe07b60 - core::panicking::panic_fmt::h410d3f147658259b
  11:        0x10fe07bcc - core::panicking::panic::hee236ca94fc05047
  12:        0x10d1ec624 - <rustc_span[12a1c67e1f6abb]::SourceFile>::lookup_file_pos_with_col_display
  13:        0x10b96c334 - <rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan>::from_span_full::<core[fafc87a594706398]::iter::sources::from_fn::FromFn<<rustc_span[12a1c67e1f6abb]::span_encoding::Span>::macro_backtrace::{closure#0}>>
  14:        0x10b96c0a0 - <rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan>::from_span_label
  15:        0x10b94498c - <alloc[764fc8c78a1bb3e1]::vec::Vec<rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan> as alloc[764fc8c78a1bb3e1]::vec::spec_from_iter::SpecFromIter<rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan, core[fafc87a594706398]::iter::adapters::map::Map<alloc[764fc8c78a1bb3e1]::vec::into_iter::IntoIter<rustc_error_messages[6db17c92cd4de685]::SpanLabel>, <rustc_errors[8ca33d4576cff18c]::json::DiagnosticSpan>::from_multispan::{closure#0}>>>::from_iter
  16:        0x10b96b598 - <rustc_errors[8ca33d4576cff18c]::json::Diagnostic>::from_errors_diagnostic
  17:        0x10b96af80 - <rustc_errors[8ca33d4576cff18c]::json::JsonEmitter as rustc_errors[8ca33d4576cff18c]::emitter::Emitter>::emit_diagnostic
  18:        0x10b94f12c - <rustc_errors[8ca33d4576cff18c]::DiagCtxtInner>::emit_diagnostic::{closure#3}
  19:        0x10c15cd1c - rustc_interface[8c972d485a8e2aa0]::callbacks::track_diagnostic::<core[fafc87a594706398]::option::Option<rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  20:        0x10b94ea74 - <rustc_errors[8ca33d4576cff18c]::DiagCtxtInner>::emit_diagnostic
  21:        0x10b9966fc - <rustc_errors[8ca33d4576cff18c]::diagnostic::Diag>::emit_producing_error_guaranteed
  22:        0x10b49297c - rustc_builtin_macros[b635d0a9cd627de0]::format::make_format_args
  23:        0x10b495dd0 - rustc_builtin_macros[b635d0a9cd627de0]::format::expand_format_args_impl
  24:        0x10b9f1090 - <rustc_expand[8c719bd15d3ec090]::expand::MacroExpander>::fully_expand_fragment
  25:        0x10b9f055c - <rustc_expand[8c719bd15d3ec090]::expand::MacroExpander>::expand_crate
  26:        0x10c0fcc94 - rustc_interface[8c972d485a8e2aa0]::passes::resolver_for_lowering_raw
  27:        0x10cd6c488 - rustc_query_impl[d98edaeb063d7c4c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[d98edaeb063d7c4c]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1486d011505b3441]::query::erase::Erased<[u8; 16usize]>>
  28:        0x10cdb92d4 - <rustc_query_impl[d98edaeb063d7c4c]::query_impl::resolver_for_lowering_raw::dynamic_query::{closure#2} as core[fafc87a594706398]::ops::function::FnOnce<(rustc_middle[1486d011505b3441]::ty::context::TyCtxt, ())>>::call_once
  29:        0x10ccd0f3c - rustc_query_system[1bcdf744069b5f02]::query::plumbing::try_execute_query::<rustc_query_impl[d98edaeb063d7c4c]::DynamicConfig<rustc_query_system[1bcdf744069b5f02]::query::caches::SingleCache<rustc_middle[1486d011505b3441]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[d98edaeb063d7c4c]::plumbing::QueryCtxt, true>
  30:        0x10cde3eb4 - rustc_query_impl[d98edaeb063d7c4c]::query_impl::resolver_for_lowering_raw::get_query_incr::__rust_end_short_backtrace
  31:        0x10b90742c - <rustc_middle[1486d011505b3441]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}::{closure#1}::{closure#3}, &rustc_data_structures[4379925a6ea25aa8]::steal::Steal<(rustc_middle[1486d011505b3441]::ty::ResolverAstLowering, alloc[764fc8c78a1bb3e1]::rc::Rc<rustc_ast[7c0a23a770356630]::ast::Crate>)>>
  32:        0x10b8a7780 - <rustc_interface[8c972d485a8e2aa0]::interface::Compiler>::enter::<rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}::{closure#1}, core[fafc87a594706398]::result::Result<core[fafc87a594706398]::option::Option<rustc_interface[8c972d485a8e2aa0]::queries::Linker>, rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  33:        0x10b8bc200 - <scoped_tls[db9af8800088675c]::ScopedKey<rustc_span[12a1c67e1f6abb]::SessionGlobals>>::set::<rustc_interface[8c972d485a8e2aa0]::util::run_in_thread_with_globals<rustc_interface[8c972d485a8e2aa0]::interface::run_compiler<core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>, rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}>::{closure#1}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  34:        0x10b8b89fc - std[d8d90c69e022292b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[8c972d485a8e2aa0]::util::run_in_thread_with_globals<rustc_interface[8c972d485a8e2aa0]::interface::run_compiler<core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>, rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}>::{closure#1}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>
  35:        0x10b8c50c0 - <<std[d8d90c69e022292b]::thread::Builder>::spawn_unchecked_<rustc_interface[8c972d485a8e2aa0]::util::run_in_thread_with_globals<rustc_interface[8c972d485a8e2aa0]::interface::run_compiler<core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>, rustc_driver_impl[d9f1096c2de14668]::run_compiler::{closure#0}>::{closure#1}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[fafc87a594706398]::result::Result<(), rustc_span[12a1c67e1f6abb]::ErrorGuaranteed>>::{closure#1} as core[fafc87a594706398]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:        0x10d796d44 - std::sys::pal::unix::thread::Thread::new::thread_start::hd88bc8e95f2ca709
  37:        0x195b132e4 - __pthread_deallocate

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.82.0 (f6e511eec 2024-10-15) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C split-debuginfo=unpacked -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [resolver_for_lowering_raw] getting the resolver for lowering
end of query stack
error: could not compile `rust-bug` (bin "rust-bug")
```

</p>
</details>

**Comment by cyrgani** [comment] 2024-11-18 18:08
Probably duplicate of #114865.

**Comment by fmease** [comment] 2024-11-19 03:25
> Probably duplicate of https://github.com/rust-lang/rust/issues/114865.

Checks out, closing as such.

**Closed by fmease** 2024-11-19 03:25 UTC
Labels: I-ICE, A-macros, T-compiler, C-bug
