### ISSUE TITLE
ICE compiling docopt v1.1.0 with rustc f509b26a7 2020-03-18 with sanitizer=address

### ISSUE THREAD

**Issue by spacejam** [rust-lang/rust#70192] opened 2020-03-20 16:46 UTC
I will fill out more info if I have time, but at the moment I do not, and I'd prefer not to lose track of this.

   Compiling docopt v1.1.0
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z sanitizer=address -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `docopt`.

**Comment by jonas-schievink** [comment] 2020-03-20 17:18
duplicate of https://github.com/rust-lang/rust/issues/70041

**Closed by jonas-schievink** 2020-03-20 17:18 UTC
Labels: C-bug, I-ICE, T-compiler
