### ISSUE TITLE
rustc fails with "Assertion `Ty == resolve(Ty->getRef()) && "type was not uniqued, possible ODR violation."

### ISSUE THREAD

**Issue by apanda** [rust-lang/rust#34649] opened 2016-07-04 20:49 UTC
Hi
When trying to build a project with Rust nightly (rustc 1.11.0-nightly (696b703b5 2016-07-03)), I get the LLVM ODR violation exception. 

For my project I set `lto=true` and `debug=true`, turning either of them off seems to resolve the issue (i.e., any case where only `lto=true` or only `debug=true` builds fine). Furthermore, building rust from scratch using flags `--enable-optimize --disable-valgrind --disable-docs` produces a rustc that does not suffer from this failure.

I am happy to run any diagnostics that might help. I have also packaged a reproducible version at https://hub.docker.com/r/apanda/rustc-build-fail/, to hit the failure just use the following steps (assuming you are on Linux and have Docker installed, this can be adopted to both OS X and Windows as appropriate):

```
sudo docker pull apanda/rustc-build-fail
sudo docker run -ti apanda/rustc-build-fail # At this time a bash shell should show up
cd /opt/netbricks/test/framework-test
cargo build --release
```

I tried debugging this but the fact that it doesn't show up when I build rust made that a bit hard.

Thank you!!

Panda

**Comment by jonas-schievink** [comment] 2016-07-04 21:52
Looks like #25270

**Comment by apanda** [comment] 2016-07-04 21:54
Ah, sorry I mistakenly throught #25270 was closed, sorry for the duplicate bug.

**Comment by luqmana** [comment] 2016-07-05 19:01
Closing as dupe of #25270. Feel free to reopen if it's not.

**Closed by luqmana** 2016-07-05 19:01 UTC
