### ISSUE TITLE
`x.py build` fails on NixOS in a `--pure` shell

### ISSUE THREAD

**Issue by humancalico** [rust-lang/rust#80815] opened 2021-01-08 14:04 UTC
```
Updating only changed submodules
Submodules updated in 0.03 seconds
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/home/humancalico/code/rust/src/bootstrap/bootstrap.py", line 1101, in main
    bootstrap(help_triggered)
  File "/home/humancalico/code/rust/src/bootstrap/bootstrap.py", line 1074, in bootstrap
    build.build_bootstrap()
  File "/home/humancalico/code/rust/src/bootstrap/bootstrap.py", line 833, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/home/humancalico/code/rust/src/bootstrap/bootstrap.py", line 148, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/nix/store/v72cj06nk69cynckz2s12rhar25k1h7v-python3-3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/v72cj06nk69cynckz2s12rhar25k1h7v-python3-3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/humancalico/code/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo'
```

This is failing since most pre-compiled binaries don't work directly on NixOS. If there are any NixOS users here is there any workaround for this?

**Comment by jyn514** [comment] 2021-01-08 14:23
I think @matklad uses NixOS. I'm not sure if it's supported though - that looks like you're missing the dynamic linker, which seems hard to solve in general.

**Comment by nagisa** [comment] 2021-01-08 14:31
We generally patch the binaries for NixOS transparently. Seems like one of the binaries or libraries isn't since some recent change. See https://github.com/rust-lang/rust/blob/master/src/bootstrap/bootstrap.py#L504-L593

**Comment by nagisa** [comment] 2021-01-08 14:37
I'm unable to reproduce:

```
$ git clean -xdff
$ nix-shell -p gcc9 binutils cmake ninja openssl pkgconfig python27 --run './x.py build'
Updating only changed submodules
Submodules updated in 0.08 seconds
downloading https://static.rust-lang.org/dist/2020-12-30/rust-std-beta-x86_64-unknown-linux-gnu.tar.gz
################################################################################################################# 100.0%
extracting /sb/d/rust/build/cache/2020-12-30/rust-std-beta-x86_64-unknown-linux-gnu.tar.gz
downloading https://static.rust-lang.org/dist/2020-12-30/rustc-beta-x86_64-unknown-linux-gnu.tar.gz
################################################################################################################# 100.0%
extracting /sb/d/rust/build/cache/2020-12-30/rustc-beta-x86_64-unknown-linux-gnu.tar.gz
downloading https://static.rust-lang.org/dist/2020-12-30/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
################################################################################################################# 100.0%
extracting /sb/d/rust/build/cache/2020-12-30/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/bin/rustc
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/bin/rustdoc
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/libchalk_derive-568bc6ffcda80739.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/libstd-7444fd17919e9af0.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/librustc_driver-5cca296db1ada831.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/libserde_derive-3c2d48eb0beac455.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/libtest-c99ebba9851136ef.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/libtracing_attributes-51c2223d70bb3634.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/librustc_macros-f9f4f0a9ad2ffc8a.so
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/lib/libLLVM-11-rust-1.50.0-beta.so
downloading https://static.rust-lang.org/dist/2020-11-19/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
################################################################################################################# 100.0%
extracting /sb/d/rust/build/cache/2020-11-19/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt
info: you seem to be running NixOS. Attempting to patch /sb/d/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo-fmt
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.38
   Compiling version_check v0.9.1
   Compiling autocfg v1.0.0
   Compiling memchr v2.3.3
   Compiling serde_derive v1.0.118
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling libc v0.2.79
   Compiling serde v1.0.118
   Compiling log v0.4.11
   Compiling ryu v1.0.5
   Compiling regex-syntax v0.6.18
   Compiling serde_json v1.0.59
   Compiling fnv v1.0.7
   Compiling same-file v1.0.6
   Compiling unicode-width v0.1.8
   Compiling itoa v0.4.6
   Compiling bootstrap v0.0.0 (/sb/d/rust/src/bootstrap)
   Compiling cc v1.0.60
   Compiling build_helper v0.1.0 (/sb/d/rust/src/build_helper)
   Compiling opener v0.4.1
   Compiling thread_local v1.0.1
   Compiling walkdir v2.3.1
   Compiling getopts v0.2.21
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling crossbeam-utils v0.7.2
   Compiling num-traits v0.2.12
   Compiling cmake v0.1.44
   Compiling aho-corasick v0.7.13
   Compiling bstr v0.2.13
   Compiling quote v1.0.7
   Compiling filetime v0.2.12
   Compiling time v0.1.43
   Compiling num_cpus v1.13.0
   Compiling regex v1.3.9
   Compiling globset v0.4.5
   Compiling ignore v0.4.16
   Compiling merge_derive v0.1.0
   Compiling merge v0.1.0
...
```

**Comment by humancalico** [comment] 2021-01-08 14:47
@nagisa Can you try it with the pure flag?

**Comment by nagisa** [comment] 2021-01-08 16:02
So:

```
$ git clean -xdff
$ nix-shell --keep NIX_PATH -p gcc9 binutils cmake ninja openssl pkgconfig python27 git curl cacert patchelf nix --pure --run './x.py build'
```

works and starts building. However if you do something like this:

```
$ git clean -xdff
$ nix-shell -p gcc9 binutils cmake ninja openssl pkgconfig python27 git curl cacert patchelf nix --pure --run './x.py build'
$ nix-shell --keep NIX_PATH -p gcc9 binutils cmake ninja openssl pkgconfig python27 git curl cacert patchelf nix --pure --run './x.py build'
```

The first command will fail to patch the solibs/executables and the 2nd and further invocations won't attempt to do it again (even if those fix `NIX_PATH`).

Not clear to me if this is actionable, as `NIX_PATH` being filtered out (by e.g. `--pure` usage) seems super rare.

**Comment by jyn514** [comment] 2022-09-19 02:41
I'm going to close this since it looks like bootstrap doesn't have enough information in a `--pure` shell to do its job.

**Closed by jyn514** 2022-09-19 02:41 UTC
Labels: A-bootstrap, O-NixOS
