### ISSUE TITLE
Function used in anonymous constant is not considered used

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#104084] opened 2022-11-07 03:01 UTC
I have the [following code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f615be9eaa32894a0c44a4effdbd6a1d):

```rust
fn foo() {}
const fn bar() {}

fn main() {
    let _ = foo();
    const _: () = bar();
}
```

Even though both `foo` and `bar` are used, I get an unused warning for `bar`:

```text
warning: function `bar` is never used
 --> src/main.rs:2:10
  |
2 | const fn bar() {}
  |          ^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

## Version

Rust 1.65.0

**Comment by compiler-errors** [comment] 2022-11-07 05:20
So unlike `foo`, which has (possibly) a side-effect even its return type is not assigned, `const _: ()` is unused in the program, so anything that it uniquely references is considered unused as well. 

Giving the constant a name and using the constant suppresses the error:

```rust
fn foo() {}
const fn bar() {}

fn main() {
    let _ = foo();
    const A: () = bar();
    let _ = A;
}
```

Do you have a more detailed explanation if you hit this in production and was confused by the warning?

**Comment by joshlf** [comment] 2022-11-07 05:29
> Do you have a more detailed explanation if you hit this in production and was confused by the warning?

Sure: I'm using it in a test that runs at compile time. The code doesn't need to actually produce anything (in other words, there's no const value that's used by another part of the program), it just needs to compile successfully.

The code is [here](https://github.com/google/zerocopy/pull/126/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R2778-R2788) if you're curious.

We also (in our zerocopy-derive crate) emit code of the form `const _: () = { ... }` inside of derive-generated `impl` blocks in order to make sure that safety invariants are satisfied - the emitted code fails to compile if the invariants are not satisfied (source code [here](https://github.com/google/zerocopy/blob/a728cb9ecc5eef30462969da09820f0053bc0d62/zerocopy-derive/src/lib.rs#L599-L602)). We haven't run into this particular issue with zerocopy-derive because all of the items we use are either defined inside of the `{ ... }` or in another crate; I mention this just to illustrate that there is a class of use cases where you want to consider something "used" even if it's just inside of an anonymous constant.

**Comment by jruderman** [comment] 2022-11-07 14:11
FWIW, you [can suppress](https://github.com/rust-lang/rust/blob/391ba78ab442610a63310b9a3d24646082628081/compiler/rustc_passes/src/dead.rs#L497-L504) the warning by putting `#[allow(dead_code)]` on the `const` item which you want to consider a "use":

```rust
const fn bar() {}

fn main() {
    #[allow(dead_code)]
    const _: () = bar();
}
```

**Comment by Dylan-DPC** [comment] 2023-01-06 07:25
Closing this as it is intended behaviour for dead code

**Closed** 2023-01-06 07:25 UTC
