### ISSUE TITLE
SIGSEGV with beta/nightly compiler with i686-unknown-freebsd target

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/rust#130677] opened 2024-09-21 21:31 UTC
When running the Tokio test suite through CI using the beta/nightly compiler, the FreeBSD 32-bit build encounters a segmentation fault. After running CI with a few different configurations, I've found two different cases of the failure. The first segfault is in the [`compile_fail_full`](https://github.com/tokio-rs/tokio/blob/master/tests-build/tests/macros.rs) test. The [`path_read_write`](https://github.com/tokio-rs/tokio/blob/master/tokio/tests/fs.rs) test also encounters a segfault.
```
running 1 test
error: test failed, to rerun pass `-p tests-build --test macros`

Caused by:
  process didn't exit successfully: `/tmp/cirrus-ci-build/target/i686-unknown-freebsd/debug/deps/macros-4f8b28e5ec17a589` (signal: 11, SIGSEGV: invalid memory reference)

Exit status: 101
```
Please see https://github.com/tokio-rs/tokio/pull/6856 for more output from the CI runs. Both failures happen in tests that interact with the file system. There are other tests that pass and don't touch the file system (e.g. all unit tests in `tokio/src/` pass). As Tokio has no special logic for using the file system and just calls std, and as the `compile_fail_full` test is not calling into any Tokio code at all, this looks an awful lot like a bug somewhere in std's filesystem handling code. But that is just a guess. I don't have access to a FreeBSD machine, so it is difficult for me to investigate further.

The 64-bit FreeBSD build does not encounter these failures. There also are no problems when using the latest stable compiler. Note that the 32-bit binaries in question are cross-compiled from and executed on a 64-bit FreeBSD host machine.

Failing toolchains:
```
rustc 1.82.0-beta.3 (4976ae480 2024-09-09)
binary: rustc
commit-hash: 4976ae480e2b29cc46f44e1b9914469cc384fcc9
commit-date: 2024-09-09
host: x86_64-unknown-freebsd
release: 1.82.0-beta.3
LLVM version: 19.1.0
```
```
rustc 1.83.0-nightly (da889684c 2024-09-20)
binary: rustc
commit-hash: da889684c80508036ff036db8c159ffdcf27648a
commit-date: 2024-09-20
host: x86_64-unknown-freebsd
release: 1.83.0-nightly
LLVM version: 19.1.0
```
Passing toolchains:
```
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-freebsd
release: 1.81.0
LLVM version: 18.1.7
```

**Comment by Darksonn** [comment] 2024-09-21 21:43
I can try to bisect it to a specific nightly next week. If it's useful, you all are welcome to use our CI to debug this - you can open a PR to Tokio to run our CI setup.

**Comment by lolbinarycat** [comment] 2024-09-21 21:50
> the compile_fail_full test is not calling into any Tokio code at all

it calls various tokio macros, doesn't it?? also, it doesn't seem to call anything in std besides `std::time::Instant::now`, so i'm not sure how this could be a path handling bug?

**Comment by workingjubilee** [comment] 2024-09-21 22:47
@Darksonn Is this *our* compiler or is it the one from FreeBSD ports?

They modded the target.

**Comment by Darksonn** [comment] 2024-09-22 09:56
I have bisected the issue. It succeeds on nightly-2024-08-20 and fails on nightly-2024-08-21.

@lolbinarycat The `compile_fail_full` test calls into the [`trybuild`](https://docs.rs/trybuild) crate, which uses `std::fs` to probe which build tests exists.

@workingjubilee I got the compiler from rustup, so I assume it's your compiler. Our ci script runs the following commands:
```
pkg install -y bash
curl https://sh.rustup.rs -sSf --output rustup.sh
sh rustup.sh -y --profile minimal --default-toolchain $TOOLCHAIN
. $HOME/.cargo/env
rustup target add i686-unknown-freebsd
rustc --version --verbose
cargo test -p tests-build --all-features --target i686-unknown-freebsd
```
with `$TOOLCHAIN` normally set to `stable`, but under these tests I set it to `beta` or `nightly-xxxx-xx-xx` for testing other compilers. This is happening on a `x86_64-unknown-freebsd` host.

**Comment by workingjubilee** [comment] 2024-09-22 18:24
Yep, that's *our* sigsegv, comrade!

**Comment by saethlin** [comment] 2024-09-22 19:16
Minimized:
```rust
fn main() {
    std::fs::File::open("Cargo.toml").unwrap().metadata();
}
```
(any file that exists will do)

**Comment by saethlin** [comment] 2024-09-22 19:25
Bisection points to https://github.com/rust-lang/rust/pull/129226
Which notes https://github.com/rust-lang/libc/pull/3723

**Comment by workingjubilee** [comment] 2024-09-22 19:29
Hello @asomers there seems to be a bit of confusion afoot!

**Comment by asomers** [comment] 2024-09-22 21:40
I've reproduced the problem locally, and I'll take a look.

**Comment by asomers** [comment] 2024-09-22 22:21
I'm pretty sure that this is a bug in libc.  While I work on a patch, could one of you toolchain experts please suggest to me how I might compile an arbitrary crate using a patched version of libc for std?

**Comment by workingjubilee** [comment] 2024-09-22 23:01
> I'm pretty sure that this is a bug in libc. While I work on a patch, could one of you toolchain experts please suggest to me how I might compile an arbitrary crate using a patched version of libc for std?

It should be sufficient to use `[patch.crates-io]` in `library/Cargo.toml` for `libc`, with presumably overriding to a `path` or a `git` repo. That will let you build a patched std, the new path should be reflected in the lock file.

**Comment by asomers** [comment] 2024-09-22 23:03
Sorry @workingjubilee but I need more help than that.  I also need to know how to build, for example, Tokio using the patched std.

**Comment by workingjubilee** [comment] 2024-09-22 23:10
uhh honestly I would just build the entire stage 1 compiler with the patched std and then build tokio with that. I can look up the incantation for using the stage 0 std with an existing nightly if that would take forever, though.

**Comment by workingjubilee** [comment] 2024-09-22 23:12
Ah here we go, you want to do this:

`rustup toolchain link stage0 build/host/stage0-sysroot`

**Comment by asomers** [comment] 2024-09-23 17:37
@workingjubilee that almost works.  But I can't cross-compile from x86_64 to x86.  Could you please tell what I must do to enable that?  When I try, I get this:
```
somers@methionine ~/s/r/i386-fbsd-segfault (master)> cargo +stage0 run --target i686-unknown-freebsd
   Compiling i386-fbsd-segfault v0.1.0 (/usr/home/somers/src/rust/i386-fbsd-segfault)
error[E0463]: can't find crate for `std`
  |
  = note: the `i686-unknown-freebsd` target may not be installed
  = help: consider downloading the target with `rustup target add i686-unknown-freebsd`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `i386-fbsd-segfault` (bin "i386-fbsd-segfault") due to 1 previous error
somers@methionine ~/s/r/i386-fbsd-segfault (master) [101]> rustup target add --toolchain stage0 i686-unknown-freebsd
error: error: invalid value 'stage0' for '--toolchain <toolchain>': invalid toolchain name: 'stage0'

For more information, try '--help'.
: invalid toolchain name: 'stage0'
somers@methionine ~/s/r/i386-fbsd-segfault (master) [1]> cargo +stage0 run --target i686-unknown-freebsd -Zbuild-std
error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `beta` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
```

**Comment by lolbinarycat** [comment] 2024-09-23 19:56
@asomers you should be able to use `-Z build-std` to cross-compile the standard library.

**Comment by lolbinarycat** [comment] 2024-09-23 20:31
you can `export RUSTC_BOOTSTRAP=1` to allow using nightly features on a beta compiler (yes it's a hack, but it's probably fine for a quick repro)

**Comment by lolbinarycat** [comment] 2024-09-23 20:31
also, `stage0` *is* a beta compiler, if you want an actual nightly, you need to build stage1

**Comment by asomers** [comment] 2024-09-23 20:58
With help from @lolbinarycat and @workingjubilee I have a working patch in review at https://github.com/rust-lang/libc/pull/3939 .  HOWEVER, it only fixes `struct stat` on the libc-0.2 branch.  I'll need to prepare a separate PR for the main branch.  Also, I haven't tested on 32-bit architectures other than i386.  I'm still trying to get access to some.  Finally, I found some additional errors in other structures that require fixing.  But they're all pretty obscure structures that the standard library doesn't use.

**Comment by workingjubilee** [comment] 2024-09-24 23:57
Oh, the way to do that without `-Zbuild-std` is to add this to the config.toml:
```toml
[build]
target = ["host-target-string", "cross-target-string"]
```

**Comment by workingjubilee** [comment] 2024-09-24 23:58
@asomers Thank you for taking care of this!

**Comment by apiraino** [comment] 2024-09-25 10:38
WG-prioritization assigning priority ([Zulip discussion](https://github.com/rust-lang/libc/pull/3939)).

@rustbot label -I-prioritize +P-high

**Comment by asomers** [comment] 2024-10-17 21:14
libc has released.  So if you update rust to use libc 0.2.160 or later this bug should be fixed.

**Comment by workingjubilee** [comment] 2024-10-18 23:14
@rust-lang/libs, relevant facts:
- i686-unknown-freebsd's libstd builds but its filesystem API (`std::fs`) is made useless/unsound by this bug.
- The fix was landed in libc 0.2.160 and then merged as part of https://github.com/rust-lang/rust/pull/131823 thanks to @asomers and @thesummer[^0].
- Unfortunately this means it has missed both the 1.83 beta and 1.82 stable releases.
- i686-unknown-freebsd is a tier 2 "without host tools" target[^1] so "libstd builds, but is ineffectual" is within the bounds of our platform support requirements, thus one can argue there is no requirement to act. However, it would be unusual for us to not beta-backport a soundness fix, tier 2 or no, so I would recommend a beta backport.
- The main question is whether we should request a stable backport at the discretion of T-release.

[^1]: https://doc.rust-lang.org/nightly/rustc/platform-support.html
[^0]: I thought it was autumn?

**Comment by cuviper** [comment] 2024-10-18 23:26
The PR is what needs the backport nomination label -- I've added beta there, but you can add stable too if you want to argue for that. I expect the stable disposition will probably be something like "accepted but does not warrant a point release on its own."

**Comment by Amanieu** [comment] 2024-10-23 16:28
In the libs meeting we discussed https://github.com/rust-lang/rust/pull/131823#issuecomment-2432788998 we accepted the beta backport but rejected the stable backport due to the large potential impact of a libc bump on other targets.

**Closed by Amanieu** 2024-10-23 16:28 UTC
Labels: P-high, regression-from-stable-to-stable, O-freebsd, C-bug, T-libs, I-libs-nominated
