### ISSUE TITLE
[E0015] Signs of constant return value are lost when "impl" is used.

### ISSUE THREAD

**Issue by denisandroid** [rust-lang/rust#66439] opened 2019-11-15 09:59 UTC
```
rustc 1.41.0-nightly (ded5ee001 2019-11-13)
```

Play: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=99f578dfc7ea70cf59bc59fe86485cd6

```
#![feature(const_fn)]
use core::mem::ManuallyDrop;

const fn check() -> impl Fn() {
	const fn my_function() {
		
	}
	
	my_function
}

const fn main() {
	let function = check();
	function(); //<--- error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
	
	let _e = ManuallyDrop::new(function);
}
```

**Comment by ecstatic-morse** [comment] 2019-11-17 04:50
I believe this is a duplicate of #63997. `const` function pointers are not yet supported.

**Comment by jonas-schievink** [comment] 2019-12-11 11:00
Closing as duplicate / "working as currently intended"

**Closed by jonas-schievink** 2019-12-11 11:00 UTC
Labels: F-const_fn, T-compiler, requires-nightly
