### ISSUE TITLE
Built-in derive macros require that all generics are bound to the derived trait even when not necessary

### ISSUE THREAD

**Issue by 4lDO2** [rust-lang/rust#67958] opened 2020-01-07 02:08 UTC
The following code fails to compile because all built-in derive macros seem to require that every generic type parameter is bound to the trait that the derive macro implements.

```rust
use std::fmt::Debug;

trait Trait {
    type AssociatedType: Debug;
}

#[derive(Debug)]
enum Enum<T: Trait> {
    A {
        thing: T::AssociatedType,
    }
}

// No Debug impl
struct S;

impl Trait for S {
    type AssociatedType = u8;
}

fn main() {
    let e = Enum::<S>::A { thing: 255u8 };
    println!("{:?}", e); // Enum<S> doesn't impl Debug because S doesn't
}
```
In this case, since a field of type `T` isn't stored directly in the enum, but simply an associated type from it, it would be logical for the impl to not require `T: Debug`. Instead, it seems like all built-in derive macro implementations require that every generic type parameter is also bound to the trait itself.

The same thing happens to structs as well, and for  `Clone` (and probably all of the other built-in derive macros).
```rust
trait Trait {
    type Type: Clone;
}

#[derive(Clone)]
struct Struct<T: Trait> {
    field: T::Type,
}

// No Clone impl
struct Implementer;
impl Trait for Implementer {
    type Type = u8;
}

fn main() {
    let s = Struct::<Implementer> { field: 42u8 };
    let s2 = s.clone(); // And hence no clone impl for Struct<Implementer>.
}
```

If I'm correct, the error seems to come from `rustc_builtin_macros::deriving::genric::TraitDef::create_derive_impl`, where
```rust
                    self.additional_bounds.iter().map(|p| {
                        cx.trait_bound(p.to_path(cx, self.span, type_ident, generics))
                    }).chain(
                        // require the current trait
                        iter::once(cx.trait_bound(trait_path.clone()))
                    ).chain(
                        // also add in any bounds from the declaration
                        param.bounds.iter().cloned()
                    ).collect();
```
where the current trait is required. The solution would probably be that a proof that `T` is actually used by directly by implementation is needed, before it is added as a trait bound in the implementation provided by the built-in derive macro.
## Meta
```
rustc 1.40.0 (73528e339 2019-12-16)
binary: rustc
commit-hash: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
commit-date: 2019-12-16
host: x86_64-unknown-linux-gnu
release: 1.40.0
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment] 2020-01-07 10:11
Duplicate of https://github.com/rust-lang/rust/issues/26925

**Closed by jonas-schievink** 2020-01-07 10:11 UTC
