### ISSUE TITLE
Rust logo in std docs settings page links back to the test crate

### ISSUE THREAD

**Issue by veber-alex** [rust-lang/rust#85488] opened 2021-05-19 23:15 UTC
https://doc.rust-lang.org/settings.html
https://doc.rust-lang.org/nightly/settings.html

Click on the Rust logo on the left, it takes you to the docs of the test crate.
Happens in stable and nightly std docs.

**Comment by jyn514** [comment] 2021-05-20 02:34
Duplicate of https://github.com/rust-lang/rust/issues/81986.

**Closed by jyn514** 2021-05-20 02:34 UTC
