### ISSUE TITLE
proc_macro! expansion can refer to items defined in the root w/o importing them

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#50504] opened 2018-05-07 14:30 UTC
Apologies if this has already been reported; I didn't search too hard.

### STR

``` rust
// bar/src/lib.rs

#![feature(proc_macro)]

extern crate proc_macro;
#[macro_use]
extern crate quote;

use proc_macro::TokenStream;

#[proc_macro]
pub fn bar(_: TokenStream) -> TokenStream {
    quote!(mod __bar {
        // NOTE `Foo` is never imported in this module
        static mut BAR: Option<Foo> = None;
    }).into()
}
```

``` rust
// foo/src/lib.rs

#![feature(proc_macro)]

extern crate bar;

use bar::bar;

struct Foo;

bar!();
```

This code compiles but I would expect it not to because the expanded form doesn't compile:

``` rust
// foo/src/lib.rs -- `cargo expand`-ed and cleaned up
struct Foo;

mod __bar {
    static mut BAR: Option<Foo> = None;
}
```

``` console
$ cargo build
error[E0412]: cannot find type `Foo` in this scope
 --> src/lib.rs:4:28
  |
4 |     static mut BAR: Option<Foo> = None;
  |                            ^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
  |
4 |     use Foo;
  |

error: aborting due to previous error
```

### Meta

```
$ rustc -V
rustc 1.27.0-nightly (428ea5f6b 2018-05-06)
```

cc @jseyfried

**Comment by alexcrichton** [comment] 2018-05-07 20:48
@petrochenkov do you know if this might be related to https://github.com/rust-lang/rust/issues/50050? The hygiene here is indeed quite suspicious

**Comment by petrochenkov** [comment] 2018-05-07 21:42
This looks like a different issue to me at a first glance (but we need to check on older releases whether this is a regression or not).
Or even two issues?
First, isn't `quote` supposed to have def-site hygiene? Here it exhibits something call-site-like.
Second, the call-site location (in module system), in which `Foo` is in scope, is mixed up with call-site hygienic context.
At least `quote!` is not stabilized.

**Comment by alexcrichton** [comment] 2018-05-08 02:36
@petrochenkov oh this is using the `quote` crate, not the one in `proc_macro`

**Comment by alexcrichton** [comment] 2018-05-08 15:04
Looks like this is a bug on stable Rust --

```rust
// foo.rs
#![crate_type = "proc-macro"]

extern crate proc_macro;

use proc_macro::*;

#[proc_macro_derive(Foo)]
pub fn foo1(a: TokenStream) -> TokenStream {
    drop(a);
    "mod __bar { static mut BAR: Option<Something> = None; }".parse().unwrap()
}
```

```rust
// bar.rs
#[macro_use]
extern crate foo;

struct Something;

#[derive(Foo)]
struct Another;

fn main() {}
```

```
$ rustc +stable foo.rs && rustc +stable bar.rs -L .
... only warnings printed
```

**Comment by alexcrichton** [comment] 2018-05-08 15:08
cc @nrc, you may want to take a look at this as well, especially because it's a bug on stable Rust which fixing may cause a lot of regressions

**Comment by nrc** [comment] 2018-05-09 00:40
This looks correct to me - aiui we use call-site hygiene for proc macros, and so we're using the hygiene context from where `bar!` is written to resolve the name `Foo`, and it does exist there. Long term, we should be using def-site hygiene here and so it wouldn't compile because there is no `Foo` where `bar` is defined.

**Comment by alexcrichton** [comment] 2018-05-09 01:07
@nrc hm but we've been advocating that "hygiene" in expanded macros for 1.1/1.2 is basically "copy/paste" hygiene, but in this case it's not?

**Comment by nrc** [comment] 2018-05-09 02:28
No, this is very much a limitation of the hygiene algorithm here - in the proper hygiene setup when you create a new scope in a macro, you get a combination of the hygiene info for the new scope plus the 'base scope'. The intuition you want is that the base scope is the call-site (that gives 'copy and paste' hygiene). However, the macros 1.1/1.2 algorithm is essentially the base scope everywhere (i.e., we ignore any scopes introduced by the macro) and the base scope is the call site.

**Comment by petrochenkov** [comment] 2018-05-09 12:34
@nrc 
How do you plan to move to the "proper hygiene setup" from the current scheme (which looks incorrect/underimplemented to me) if `proc_macro`/`proc_macro_attribute` are stabilized now?

**Comment by petrochenkov** [comment] 2018-05-09 13:16
Even more alarming example:
```rust
// foo.rs
#![crate_type = "proc-macro"]
extern crate proc_macro;
use proc_macro::*;

#[proc_macro_derive(Foo)]
pub fn foo1(_: TokenStream) -> TokenStream {
    "
    struct Outer;
    mod inner {
        type Inner = Outer; // `Outer` shouldn't be available from here
    }
    ".parse().unwrap()
}
```
```rust
// bar.rs
#![allow(unused)]

#[macro_use]
extern crate foo;

#[derive(Foo)] // OK?!
struct Dummy;

fn main() {}
```
I.e. the current implementation of call-site hygiene effectively flattens any module structures existing inside the macro.

**Comment by petrochenkov** [comment] 2018-05-09 13:39
Perhaps we need to add some extra feature gate for macros generating modules?
(Possibly retroactively affecting `proc_macro_derive`).
Non-module scoping is not affected as far as I can conclude from some quick experiments.

**Comment by alexcrichton** [comment] 2018-05-09 22:25
I've posted https://github.com/rust-lang/rust/pull/50587 to help evaluate the impact of forbidding modules from being generated by procedural derive macros

**Comment by alexcrichton** [comment] 2018-05-17 03:35
Given the [crater results](https://cargobomb-reports.s3.amazonaws.com/pr-50587/index.html) it seems clear that we cannot retroactively prevent custom derive from generating modules. Current "offenders" are:

* `pest_derive` - `#[derive(Parser)]`
* `vulkano-shader-derive` - `#[derive(VulkanoShader)]`
* `diesel` - `#[derive(QueryId)]`
* `soa_derive` - `#[derive(StructOfArray)]`
* `enumflags_derive` - `#[derive(EnumFlags)]`
* `robin-derives` - `#[derive(Builder)]`
* `juniper_codegen` - `#[derive(GraphQLEnum)]`
* `prost-derive` - `#[derive(Message)]`
* `ethabi-derive` - ??

My [PR](https://github.com/rust-lang/rust/pull/50587) purely disallowed `mod` items being generated and did not fix hygiene or anything like that. It's unknown what the fallout would be if we were to fix issues like [mentioned above](https://github.com/rust-lang/rust/issues/50504#issuecomment-387734625).

I'd still like to gate such features by default for maros 1.2 (attributes and bang macros) as I'd like to avoid worsening this problem further

**Comment by alexcrichton** [comment] 2018-05-17 03:46
I've opened https://github.com/rust-lang/rust/pull/50820 to separately gate procedural bang and attribute macros, and will leave custom derive alone for now.

**Comment by petrochenkov** [comment] 2018-06-14 08:14
Looks like this issue is going to be fixed as well as a part of https://github.com/rust-lang/rust/issues/50050.

**Comment by petrochenkov** [comment] 2018-06-30 19:36
Fixed in https://github.com/rust-lang/rust/pull/51952

**Closed** 2018-07-11 21:54 UTC
Labels: A-macros-1.2, A-macros-2.0, C-bug

**Comment by alexcrichton** [comment] 2018-08-01 15:09
@vityafx unfortunately as a user you can't do anything to fix that error, the fix would need to be in diesel's `Insertable` custom derive. In the meantime you can allow the lint though.

**Comment by lukedupin** [comment] 2018-08-05 20:55
How do we "allow the lint through" in the mean time?

**Comment by lukedupin** [comment] 2018-08-05 21:39
Nm, I found it: 
export RUSTFLAGS="-Aproc-macro-derive-resolution-fallback"

Thanks

**Comment by apiraino** [comment] 2018-08-12 13:05
Nitpicking on @lukedupin solution; maybe better adding:
```
#[allow(proc_macro_derive_resolution_fallback)]
```
at the top of your files that trigger the warning.

Setting an env variable somehow invalidates the compiler cache, therefore:
```
$ cargo check
```
and:
```
$ RUSTFLAGS="-Aproc-macro-derive-resolution-fallback" cargo check
```
are not the same and running one or the another will trigger a full (lenghy) rebuild; f.e. your IDE may use `cargo check` for linting without setting that env var.

**Comment by xpe** [comment] 2018-09-09 04:45
@apiraino I'd like to add correction. Here is the proper syntax to use at the top of a file to disable the warning:

```rs
#![allow(proc_macro_derive_resolution_fallback)]
```

Note the `#!`, per https://doc.rust-lang.org/reference/attributes.html.

**Comment by Boscop** [comment] 2018-09-24 00:45
Btw, I'm getting these kind of warnings also for diesel's AsChangeset, Insertable, Associations, Identifiable, Queryable and QueryableByName.

**Comment by kotauskas** [comment] 2020-11-06 17:58
I feel like there's a bug with the lint itself. My proc macro expands to the following (example taken from its unit test, slightly modified to demonstrate the problem):
```rust
// Not a part of actual macro output, but is instead present at call site. I'm parsing the input struct's type
// specificially (the macro is a derive macro), so it's fine to avoid fully qualifying it, since use super::*;
// will take care of everything.
use std::time::SystemTime; 
mod entries {
    use super::*;
    #[doc = "The entry identifier type for the `field` field in the `MyConfigTable` config table."]
    pub enum Field {}
    impl ::snec::Entry for Field {
        type Data = SystemTime; // This is not in the prelude 
        const NAME: &'static str = "field";
    }
};
...
```
The `use super::*;` there is what is expected to make the name resolution work correctly instead of failing because of the module. The macro's output compiles just fine, but produces the lint.

Even though I'm completely not familiar with the implementation of the lint itself, I suspect that the culprit is that it simply checks for relative names which would are valid outside the module. I don't know whether it's implemented like this though, that's just a wild guess.
