### ISSUE TITLE
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued'

### ISSUE THREAD

**Issue by Nonius** [rust-lang/rust#81624] opened 2021-02-01 13:28 UTC
### Code

https://github.com/bolcom/Rust_bug_report

### Error output

➜  bug_report git:(master) RUST_BACKTRACE=1 cargo build
   Compiling bug_report v0.1.0 (/Users/.../bug_report)
warning: Error finalizing incremental compilation session directory `/Users/.../bug_report/target/debug/incremental/bug_report-q9q8kckyvbau/s-fvgzxe1lfy-v4s6o6-working`: No such file or directory (os error 2)

warning: 1 warning emitted

error: internal compiler error: failed to process buffered lint here
  --> /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/macros.rs:12:40
   |
10 | / macro_rules! bail {
11 | |     ($e:expr) => {
12 | |         return Err($crate::err_msg($e));
   | |                                        ^
13 | |     };
...  |
16 | |     };
17 | | }
   | |_- in this expansion of `failure::bail!`
   | 
  ::: src/main.rs:20:22
   |
20 |           async move { failure::bail!("compiler bug") }
   |                        ------------------------------ in this macro invocation
   |
   = note: delayed at /rustc/b122908617436af187252572ed5db96850551380/compiler/rustc_lint/src/early.rs:384:18

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: rustc_interface::interface::create_compiler_and_run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (b12290861 2021-01-29) running on x86_64-apple-darwin

note: compiler flags: -Z macro-backtrace -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

### Details

If I change the `rust-toolchain` to `nightly-2021-01-29` then it works.

**Comment by jonas-schievink** [comment] 2021-02-01 13:42
duplicate of https://github.com/rust-lang/rust/issues/81531

**Closed by jonas-schievink** 2021-02-01 13:42 UTC
Labels: C-bug, I-ICE, T-compiler
