### ISSUE TITLE
Unexpected difference in -1i32.abs() vs (-1i32).abs()

### ISSUE THREAD

**Issue by econoplas** [rust-lang/rust#25374] opened 2015-05-13 16:34 UTC
Unexpected difference in -1i32.abs() vs (-1i32).abs()

I tried this code:

fn main() {
    println!("{} {} {} {}", -1i8.abs(), -1i16.abs(), -1i32.abs(), -1i64.abs());
    println!("{} {} {} {}", (-1i8).abs(), (-1i16).abs(), (-1i32).abs(), (-1i64).abs());
}

I expected to see this happen:
1 1 1 1
1 1 1 1

Otherwise I expected a compiler error indicating -1i32.abs() is invalid syntax?

Instead, this happened:
-1 -1 -1 -1
1 1 1 1

## Meta

`rustc --version --verbose`:
rustc 1.0.0-dev (built 2015-05-13)
binary: rustc
commit-hash: unknown
commit-date: unknown
build-date: 2015-05-13
host: x86_64-unknown-linux-gnu
release: 1.0.0-dev
commit-date: 2015-05-11
build-date: 2015-05-11
host: x86_64-pc-windows-gnu
release: 1.0.0-beta.5

Backtrace:
None

**Comment by alexcrichton** [comment] 2015-05-13 16:37
This has to do with when the `-` prefix operator is bound to an expression, and in this case it has lower precedence than method calls. For example the first expressions you have are parsed as `-(1i32.abs())`, which is why the printed value is -1.

I believe this is all working as expected, though, so closing as working as intended.

**Closed by alexcrichton** 2015-05-13 16:37 UTC
