### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#33477] opened 2016-05-07 00:58 UTC
Here's the output of the compiler

I'll upload the code I'm working on and link it here.

```
   Compiling graphql v0.1.0 (file:///home/rdodd/devel/work/graphql-rs)
tests/language/lexer.rs:23:25: 23:30 error: unresolved enum variant, struct or const `Token` [E0419]
tests/language/lexer.rs:23                         Token(TokenKind::Name(String::from("foo")), 3, 5) => {},
                                                   ^~~~~
tests/language/lexer.rs:23:25: 23:30 help: run `rustc --explain E0419` to see a detailed explanation
tests/language/lexer.rs:23:31: 23:46 error: unresolved enum variant, struct or const `Name` [E0419]
tests/language/lexer.rs:23                         Token(TokenKind::Name(String::from("foo")), 3, 5) => {},
                                                         ^~~~~~~~~~~~~~~
tests/language/lexer.rs:23:31: 23:46 help: run `rustc --explain E0419` to see a detailed explanation
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'RefCell<T> already borrowed', ../src/libcore/cell.rs:445
stack backtrace:
   1:     0x7f0d44979330 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x7f0d4498268b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x7f0d449821e3 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x7f0d449469ac - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x7f0d44947448 - sys_common::unwind::begin_unwind_fmt::h8b491a76ae84af35m0t
   6:     0x7f0d44976d91 - rust_begin_unwind
   7:     0x7f0d449c97af - panicking::panic_fmt::h98b8cbb286f5298alcM
   8:     0x7f0d449ca2a8 - panicking::panic::h4265c0105caa1121SaM
   9:     0x7f0d43f2c063 - check::resolve_ty_and_def_ufcs::h3de55b264fbcb010iLs
  10:     0x7f0d43f77d30 - check::_match::check_pat_enum::h72e323bec9027ddcKrb
  11:     0x7f0d43f00a25 - check::_match::check_pat::h3f6e9b70759430c51Sa
  12:     0x7f0d43f77c01 - check::_match::check_pat_enum::h72e323bec9027ddcKrb
  13:     0x7f0d43f00a25 - check::_match::check_pat::h3f6e9b70759430c51Sa
  14:     0x7f0d43f77c01 - check::_match::check_pat_enum::h72e323bec9027ddcKrb
  15:     0x7f0d43f00a25 - check::_match::check_pat::h3f6e9b70759430c51Sa
  16:     0x7f0d43f3116f - check::_match::check_match::h566da3fd8c23ab55Thb
  17:     0x7f0d43f4ada2 - check::check_expr_with_unifier::h1043101995598655204
  18:     0x7f0d43f0290e - check::check_block_with_expected::hc4a627a63732f3b0jXs
  19:     0x7f0d43f54549 - check::check_expr_with_unifier::h4225028942422043672
  20:     0x7f0d43f796bc - check::_match::check_match::_$u7b$$u7b$closure$u7d$$u7d$::closure.39392
  21:     0x7f0d43f312d2 - check::_match::check_match::h566da3fd8c23ab55Thb
  22:     0x7f0d43f4ada2 - check::check_expr_with_unifier::h1043101995598655204
  23:     0x7f0d43f0290e - check::check_block_with_expected::hc4a627a63732f3b0jXs
  24:     0x7f0d43f54549 - check::check_expr_with_unifier::h4225028942422043672
  25:     0x7f0d43f796bc - check::_match::check_match::_$u7b$$u7b$closure$u7d$$u7d$::closure.39392
  26:     0x7f0d43f312d2 - check::_match::check_match::h566da3fd8c23ab55Thb
  27:     0x7f0d43f4ada2 - check::check_expr_with_unifier::h1043101995598655204
  28:     0x7f0d43f0290e - check::check_block_with_expected::hc4a627a63732f3b0jXs
  29:     0x7f0d43ef92b9 - check::check_fn::h6fb1443d16d6d1a1hOo
  30:     0x7f0d43ef69cf - check::check_bare_fn::h846d602fffbab51bLDo
  31:     0x7f0d43ef1876 - check::check_item_body::h1bc79a321f78eb96h3o
  32:     0x7f0d43ee832b - check::check_item_bodies::h5671f35c802ef7c1yBo
  33:     0x7f0d43edfbb3 - check_crate::h7bb847abc9f256eeeCC
  34:     0x7f0d44ea5667 - driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::closure.28550
  35:     0x7f0d44ea3c04 - middle::ty::context::ctxt<'tcx>::create_and_enter::h16192426302205697189
  36:     0x7f0d44ea06ef - driver::phase_3_run_analysis_passes::h10920926650053012691
  37:     0x7f0d44e73a15 - driver::compile_input::h7ae6a86e23de0774Hca
  38:     0x7f0d44e62b47 - run_compiler::hb0408bcf47642fe6mPc
  39:     0x7f0d44e602c1 - sys_common::unwind::try::try_fn::h7614151098073783683
  40:     0x7f0d44976d1b - __rust_try
  41:     0x7f0d4496f1fd - sys_common::unwind::inner_try::hadd81c754a64f07ciYt
  42:     0x7f0d44e60b10 - boxed::F.FnBox<A>::call_box::h18261575856772421581
  43:     0x7f0d44980c59 - sys::thread::Thread::new::thread_start::h9bc812305b5e01feFPy
  44:     0x7f0d3dc410a3 - start_thread
  45:     0x7f0d445ef87c - clone
  46:                0x0 - <unknown>

```

**Comment by Mark-Simulacrum** [comment] 2017-05-03 23:15
The code for this was never linked, as far as I can tell, so I'm going to close this issue since reproducing and as such fixing this is likely impossible.

**Closed by Mark-Simulacrum** 2017-05-03 23:15 UTC
Labels: I-ICE
