### ISSUE TITLE
(1<<64) can not be precisely represent by f64  in rust (in c, it is ok)

### ISSUE THREAD

**Issue by H-ZeX** [rust-lang/rust#64399] opened 2019-09-12 08:08 UTC
```rust
fn main() {
    let a: f64 = 2.0f64.powi(64);
    println!("{}", a); 
    let a: f64 = 18446744073709551616.0f64;
    println!("{}", a);

    // wii output 
    // 18446744073709552000
    // 18446744073709552000
}
```

```c
#include <stdio.h>

int main() {
    double a = 18446744073709551616.0;
    float b = 18446744073709551616.0;
    printf("%lf, %f\n", a, b);

    // will output 
    //18446744073709551616.000000, 18446744073709551616.000000
}
```
`(1<<64) == 18446744073709551616`, so IEEE754 can represent it use 64 or 32 float number

**Comment by scottmcm** [comment] 2019-09-14 05:47
Closing a duplicate of the issue that @ExpHP mentioned.

You can use https://evanw.github.io/float-toy/ to see that both strings mentioned are the same float.

**Closed by scottmcm** 2019-09-14 05:47 UTC
Labels: C-bug, T-libs
