### ISSUE TITLE
compiletest: may truncate compiler output before trying to parse it as json

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#96229] opened 2022-04-19 23:36 UTC
Running a `ui` test will eventually invoke the following function:

https://github.com/rust-lang/rust/blob/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/src/tools/compiletest/src/read2.rs#L48-L57

through

https://github.com/rust-lang/rust/blob/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/src/tools/compiletest/src/runtest.rs#L1772-L1780

which can truncate a long output from the compiler. The problem is that UI tests ask the compiler to output its output as json and then attempts to parse it later, for example here:

https://github.com/rust-lang/rust/blob/4ca19e09d302a4cbde14f9cb1bc109179dc824cd/src/tools/compiletest/src/runtest.rs#L3114

which can fail due to truncation and output very difficult to investigate output in e.g. CI.

Reference: https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/Legacy.20PM.20removal/near/279479951

**Comment by ehuss** [comment] 2022-04-20 01:31
I think this is somewhat a duplicate of #94322 and #92211.

It might be good to consolidate these issues, and come up with a specific suggestion on how to improve it. The limit needs to be there to prevent OOM, and also as a indicator that perhaps rustc is emitting too much data (as #94327 resolved).  So I suspect what is desired is a better way to display the error. I haven't thought about it myself, but I think that should be easy to improve.

**Comment by nagisa** [comment] 2022-04-20 01:43
Got it, removed E-easy.

I feel like at least a part of this problem is in the fact that the truncation happens indiscriminately at a byte boundary. And another part is that the failure mode is non-deterministic (paths and such can have varying lengths.)

If the intent is to make “too much output” a failure mode, then we should just straight up fail the test, I feel. Possibly kill/SIGPIPE the compilation process when it exceeds the amount of output bytes but don't truncate the output itself when showing it to the user…?

Alternatively, for JSONL(ines) truncating on line boundaries would make things not fail as terribly. Not to mention, the rendered output is duplicated among other information with JSON output and a test will likely be interested in only parts of it, which will make truncation kick in earlier in some instances than others, so maybe giving an opportunity to `map` the output in a streaming fashion would help?

**Comment by pietroalbini** [comment] 2022-04-28 11:32
Also hit this due to https://github.com/rust-lang/rust/issues/96362#issuecomment-1108609893 on my local machine...

**Closed** 2023-09-13 03:41 UTC
Labels: A-testsuite
