### ISSUE TITLE
OpAssign traits are not implemented for rhs reference types

### ISSUE THREAD

**Issue by Kingsquee** [rust-lang/rust#34437] opened 2016-06-23 21:36 UTC
```rust
fn main() {
    let mut a: i8 = 4;
    let     b: i8 = a;
    
    let c = &b;
    
    // works
    a = a | &b;
    
    // not implemented
    //a |= &b;
}
```
Not a biggie, seems like an oversight.

**Comment by apasel422** [comment] 2016-07-02 22:44
Is this a duplicate of #32094?

**Comment by arielb1** [comment] 2016-07-03 08:54
Yeah, it is.

**Closed by arielb1** 2016-07-03 08:54 UTC
Labels: A-libs
