### ISSUE TITLE
Allow by-move binding for patterns with guards that don't reference the bindings

### ISSUE THREAD

**Issue by kmcallister** [rust-lang/rust#14252] opened 2014-05-16 22:27 UTC
I have

~~~ .rs
match token {
    DoctypeToken(dt) if mode == Initial => ...,
    DoctypeToken(dt) => ...,

    TagToken(x) => ...,
    CommentToken(x) => ...,
    // other cases
~~~

This gives

~~~
error: cannot bind by-move into a pattern guard
~~~

In this situation it should be fine to defer the move until the guard has succeeded.

It's a bit frivolous because I could instead do

~~~ .rs
match token {
    DoctypeToken(dt) => if mode == Initial {
        ...
    } else {
        ...
    },

    TagToken(x) => ...,
    CommentToken(x) => ...,
    // other cases
~~~

But I like having all the branching in one construct, especially when I'm implementing a spec which is written that way.  And I don't want to add `mode` to the match scrutinee because none of the other cases care about it.

See also #4649.

**Comment by durka** [comment] 2015-11-26 19:31
Triage: still annoying.

**Comment by huonw** [comment] 2016-01-05 13:10
(Foward-)dupe of https://github.com/rust-lang/rust/issues/15287, closing.

**Closed by huonw** 2016-01-05 13:10 UTC
Labels: I-enhancement
