### ISSUE TITLE
Compiler panics internally on "cargo run hello"

### ISSUE THREAD

**Issue by bcpeinhardt** [rust-lang/rust#83710] opened 2021-03-31 17:14 UTC
### Code

```Rust
use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        println!("Commands: create | complete | remove | view ");
    }

    if let Some(arg) = args.get(1) {
        match arg {
            _ => {
                println!("No errs yet");
            }
        }
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (5e65467ef 2021-03-26)
binary: rustc
commit-hash: 5e65467eff3d1da4712586d8402d1d2e1d6654bc
commit-date: 2021-03-26
host: x86_64-pc-windows-msvc
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
Compiling global_to_do v0.1.0 (C:\Users\benja\Dropbox\My PC (DESKTOP-F02B0UR)\Desktop\Development_Projects\global_to_do)
thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[f48f]::iter::traits::iterator::Iterator): GenericPredicates { parent: None, predicates: [(Binder(TraitPredicate(<Self as std::iter::Iterator>)), C:\Users\benja\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\iter\traits\iterator.rs:98:1: 98:19 (#0))] }', /rustc/5e65467eff3d1da4712586d8402d1d2e1d6654bc\compiler\rustc_query_system\src\query\plumbing.rs:593:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (5e65467ef 2021-03-26) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [predicates_of] computing predicates of `std::iter::Iterator`
#1 [typeck] type-checking `main`
end of query stack
error: could not compile `global_to_do`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Aaron1011** [comment] 2021-05-02 02:41
Duplicate of https://github.com/rust-lang/rust/issues/84341. This is fixed in the latest nightly

**Closed by Aaron1011** 2021-05-02 02:41 UTC
Labels: A-incr-comp, C-bug, I-ICE, T-compiler
