### ISSUE TITLE
infinite loop in a background thread turns into a segfault when building with cargo 1.21.0 --release mode

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#45248] opened 2017-10-12 23:07 UTC
Example:

```rust
fn main() {
    let handle = std::thread::spawn(|| loop {});
    handle.join().unwrap();
}
```

Output:

```
$ rustup run 1.21.0 cargo run --release
   Compiling scratch v0.1.0 (file:///tmp/tmp.24DOIzzSMO/scratch)
    Finished release [optimized] target(s) in 0.49 secs
     Running `target/release/scratch`
zsh: segmentation fault (core dumped)  rustup run 1.21.0 cargo run --release
```

This doesn't repro on 1.20, beta, or nightly. In all the other compiler versions I've tried, the loop seems to get optimized out, and the program exits immediately. (In all the debug builds I've tried, including 1.21, the infinite loop stays in and the program pegs a core forever.)

**Comment by sfackler** [comment] 2017-10-12 23:15
Duplicate of #28728?

**Comment by oconnor663** [comment] 2017-10-12 23:23
Feels related, yeah. It seems like the difference here is that if you do the same thing that issue demonstrates, but on a background thread, the panic becomes a segfault. Not sure if that's one issue or two.

**Comment by cuviper** [comment] 2017-10-13 01:06
The symptom can be arbitrary for UB.  In cases I've seen before, LLVM doesn't generate code for the "unreachable" loop at all, which means when you do reach that loop it just falls through to whatever code happens to be next in memory.

**Comment by oconnor663** [comment] 2017-10-13 02:38
Out of curiosity, does anyone know why none of this repros on beta or nightly?

**Comment by sfackler** [comment] 2017-10-13 04:17
A different revision of LLVM or the way we talk to LLVM probably.

**Comment by nagisa** [comment] 2017-10-13 13:59
LLVM IR shows clear indications of the https://github.com/rust-lang/rust/issues/28728, so closing as a duplicate.

**Closed by nagisa** 2017-10-13 13:59 UTC
