### ISSUE TITLE
Search bar not working with `cargo doc --open`

### ISSUE THREAD

**Issue by icy-ux** [rust-lang/rust#70781] opened 2020-04-04 15:26 UTC
**Problem**
The search bar isn't working when I do `cargo doc --open` using Firefox. Normally I can type in method or struct name in the search bar at the top, and it will search the libraries associated with the project (as well as the project) and return links to appropriate documentation. Instead, when I click the search bar nothing happens, and I can't type anything in the search bar.

The  browser dev tools indicate this is because of a `ReferenceError: E is not defined` in the javascript in target/doc/search-index.js:16

This does not happen with every project. A test project created with very few dependencies resulted the search bar working fine, and I haven't been able to determine whether it is a particular dependency which is causing the problem

**Steps**
1. Execute `cargo doc --open`
2. Switch to the (newly-opened) Firefox window
3. Try to use the search bar

**Possible Solution(s)**
Unknown

**Notes**

Output of `cargo version`:
```
$ cargo version
cargo 1.42.0 (86334295e 2020-01-31)
$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
$ rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)

```

**Comment by ehuss** [comment] 2020-04-04 18:08
Transferring to the rust-lang/rust repository, as this is likely a rustdoc issue.

**Comment by jonas-schievink** [comment] 2020-04-04 18:25
Please retry on nightly, it might be fixed there

**Comment by icy-ux** [comment] 2020-04-04 20:37
On Sat, Apr 04, 2020 at 11:25:27AM -0700, Jonas Schievink wrote:
>Please retry on nightly, it might be fixed there

Thanks for the suggestion. I did 
```
rustup install nightly && cargo +nightly doc --open
```
but that did not fix the issue, the resulting webpage shows the same 
problem and the `ReferenceError` comes from the same line of 
`search-index.js`.

**Comment by icy-ux** [comment] 2020-04-12 09:10
The `cargo doc --open` generated HTML started working again 
mysteriously. I'm not sure why. Maybe another package on my system was 
updated?

**Comment by jonas-schievink** [comment] 2020-04-12 13:30
Odd, closing as fixed then

**Comment by icy-ux** [comment] 2020-04-12 18:51
On Sun, Apr 12, 2020 at 06:31:08AM -0700, Jonas Schievink wrote:
>Odd, closing as fixed then

I don't think it's fixed. I had this happen before a few months ago and 
didn't pay much attention as it seemed to "fix itself." Then when it 
came back just now I decided it was worth opening the issue.

**Comment by GuillaumeGomez** [comment] 2020-05-04 19:30
Sorry but unless you provide an error (from the browser console), I'll just assume that there is no bug but maybe an issue specific to your machine. Don't hesitate to re-open it if you have more information!

**Closed by GuillaumeGomez** 2020-05-04 19:30 UTC
Labels: C-bug, T-rustdoc

**Comment by ehuss** [comment] 2020-05-08 19:56
I just ran into this. A reproduction is to run `cargo +1.40.0 doc` on a project with some dependencies, and then run `cargo doc --no-deps` with a version of 1.41 or newer.  This causes the `search-index.js` file to retain the old format (from 1.40) mixed with the new format (presumably from #66828).

@GuillaumeGomez is it intended that shared, persistent files (like `search-index.js`) are not necessarily compatible between releases?  If so, I can probably look at adding something to Cargo to flush the `doc/` directory if it detects a different version has been used.

**Comment by GuillaumeGomez** [comment] 2020-05-11 08:21
It's not supposed to be compatible between versions, indeed. Cleaning the `doc` repository would be a great idea!
