### ISSUE TITLE
#[derive(Clone)] always require generic arguments to be Clone, which is too restrictive

### ISSUE THREAD

**Issue by VFLashM** [rust-lang/rust#32673] opened 2016-04-02 01:36 UTC
#[derive(Clone)] should not require generic arguments to be Clone if it's not necessary.

```
use std::rc::Rc;

struct S;

#[derive(Clone)]
struct Works(Rc<S>);

#[derive(Clone)]
struct Fails<T>(Rc<T>);

fn main() {
    let w = Works(Rc::new(S));
    w.clone(); // ok
    
    let f = Fails(Rc::new(S));
    f.clone(); // fails
}
```

**Comment by Stebalien** [comment] 2016-04-02 04:07
Duplicate of #26925

**Comment by bluss** [comment] 2016-04-02 12:24
Thank you @VFLashM; closing as a dup.

**Closed by bluss** 2016-04-02 12:24 UTC
