### ISSUE TITLE
Rustdoc generates invalid links for reexported types

### ISSUE THREAD

**Issue by bugadani** [rust-lang/rust#74920] opened 2020-07-29 17:33 UTC
Rustdoc is able to generate docs for types reexported from an external crate. However, links on that page point to the current crate and are thus invalid.

An example that shows this issue: https://docs.rs/embedded-text/0.0.3/embedded_text/prelude/struct.TextStyleBuilder.html

This page is the documentation generated for embedded-graphics' TextStyleBuilder struct that is reexported in embedded-text's prelude. Note that links to e-g types that are NOT re-exported (for example, `Text` or the `text_style!` macro) point to nonexistent pages in e-t.

**Comment by bugadani** [comment] 2020-07-29 18:18
In fact, I believe the real issue here is that reexports from an external crate show up as types provided by the current crate instead of re-exports: https://docs.rs/embedded-text/0.0.3/embedded_text/prelude/index.html shows this, all types in this module are re-exports.

**Comment by jyn514** [comment] 2020-07-30 02:15
This looks like different parts of rustdoc are disagreeing on whether the docs should be inlined. `collect_intra_doc_links` thinks they should and `html::href()` thinks they shouldn't. Not yet sure which is right.

**Comment by bugadani** [comment] 2020-07-30 08:45
Why are external docs inlined into the current crate? It looks like rustdoc is perfectly capable of linking to other crate's documentations. Types in fields, impls and such seem to link to the external crate, and I think reexports should be handled the same way.

**Comment by ollie27** [comment] 2020-07-30 15:53
rustdoc will inline reexports from external crates unless you add `#[doc(no_inline)]` to the `pub use` statement. I'd recommend doing that here and for preludes in general.

As for the broken links that's just because they're relative URLs: https://docs.rs/embedded-graphics/0.6.2/src/embedded_graphics/style/text_style.rs.html#121-128 and the page is being generated in a different location. Using `#[doc(no_inline)]` would avoid the issue but using [intra-doc links](https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#linking-to-items-by-name) should allow rustdoc to generate working links in this case.

**Comment by bugadani** [comment] 2020-07-30 15:58
> rustdoc will inline reexports from external crates unless you add `#[doc(no_inline)]` to the `pub use` statement. I'd recommend doing that here and for preludes in general.

Thanks, didn't know about this

> As for the broken links that's just because they're relative URLs

I know but they could still be transformed maybe?

> using [intra-doc links](https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#linking-to-items-by-name) should allow rustdoc to generate working links in this case.

Indeed, but it's still unstable.

**Comment by jyn514** [comment] 2020-07-30 16:24
Oh I missed that these are manually written links. This isn't a bug in rustdoc then.

**Comment by jyn514** [comment] 2020-07-30 16:26
> they could still be transformed maybe?

I don't think that rustdoc should make assumptions about what you meant to link to. You could know about a page that rustdoc didn't generate. If you want things to 'just work' you should use intra-doc links.

**Comment by bugadani** [comment] 2020-07-30 16:28
> You could know about a page that rustdoc didn't generate

True, but that page will not be inlined into the re-exporting crate. I think the assumption that ". refers to the source crate and links relative to . refer to pages in that crate" is a valid one to make.

**Comment by jyn514** [comment] 2020-08-08 06:34
I'm going to close this because it's not a bug in rustdoc. Rustdoc does not guarantee the relative paths of URLs, if you want links to always work use intra-doc-links.

**Closed by jyn514** 2020-08-08 06:34 UTC
Labels: C-bug, T-rustdoc
