### ISSUE TITLE
Unclear diagnostics for async callback that takes a reference

### ISSUE THREAD

**Issue by panstromek** [rust-lang/rust#76609] opened 2020-09-11 19:42 UTC
This code..

```rust
pub async fn foo() {
    wrapper(callback).await
}

pub async fn callback(buf: &mut [u8]) {}

pub async fn wrapper< Fun, Fut>(cb: Fun)
    where
        Fun: Fn(& mut [u8]) -> Fut ,
        Fut: Future<Output=()>
{
    let mut buf = [8; 8];
    cb(&mut buf).await
}
```
...triggers this diagnostic:

```
error: implementation of `std::ops::FnOnce` is not general enough
   --> tests/src/main.rs:8:5
    |
8   |       wrapper(callback).await
    |       ^^^^^^^ implementation of `std::ops::FnOnce` is not general enough
    | 
   ::: /home/matyas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:219:1
    |
219 | / pub trait FnOnce<Args> {
220 | |     /// The returned type after the call operator is used.
221 | |     #[lang = "fn_once_output"]
222 | |     #[stable(feature = "fn_once_output", since = "1.12.0")]
...   |
227 | |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
228 | | }
    | |_- trait `std::ops::FnOnce` defined here
    |
    = note: `std::ops::FnOnce<(&'0 mut [u8],)>` would have to be implemented for the type `for<'_> fn(&mut [u8]) -> impl std::future::Future {callback}`, for some specific lifetime `'0`...
    = note: ...but `std::ops::FnOnce<(&mut [u8],)>` is actually implemented for the type `for<'_> fn(&mut [u8]) -> impl std::future::Future {callback}`

```
and it's completely unclear to me how to fix it. Well, obviously the problem is that the callback takes a reference, but even that took me some time to realize (longer than I'd like to admit). In the end I just removed it and did it differently.

This code came from refactoring of some non-async code, so I for some time I didn't realize that I was doing something fishy. I don't have much experience with async rust, so I don't know if this is even possible to fix while still keeping the reference there (maybe with some clever bounds?). If not, it should probably suggest you to rewrite it to not use that reference.

**Comment by tmandry** [comment] 2020-09-15 17:17
For the original error, the function signature needs a lifetime parameter like:

```rust
pub async fn wrapper<'a, Fun, Fut>(cb: Fun)
    where
        Fun: Fn(&'a mut [u8]) -> Fut ,
        Fut: Future<Output=()> + 'a
```

Adding this leads to an error caused by returning a future with a reference to a local (`buf` in this case), which also needs to be fixed. Thankfully this error message is a bit clearer.

**Comment by tmandry** [comment] 2020-09-15 17:19
Possible duplicate of #71671

**Comment by tmandry** [comment] 2020-09-16 00:27
On second glance this is the same issue as #68521, closing in favor of it.

**Closed by tmandry** 2020-09-16 00:27 UTC
Labels: A-async-await, A-diagnostics, A-lifetimes, AsyncAwait-Triaged, D-confusing, T-compiler
