### ISSUE TITLE
<f64 as FromStr> produces incorrect results in some cases

### ISSUE THREAD

**Issue by JRoush** [rust-lang/rust#23505] opened 2015-03-19 03:12 UTC
In at least one case (and presumably more), `FromStr::from_str()` produces a result that is off by one ulp.

Example:

    pub fn main() {
        use std::str::FromStr;    
        let literal: f64 = 0.123f64;
        let fromstr: f64 = FromStr::from_str("0.123").unwrap();
        println!("Literal: {:16X}", as_int(literal)); // Literal: 3FBF7CED916872B0
        println!("FromStr: {:16X}", as_int(fromstr)); // FromStr: 3FBF7CED916872B1
        println!("Equal: {}", literal == fromstr);    // Equal: false
    }

    pub fn as_int(f: f64) -> u64 {
        unsafe{ std::mem::transmute::<f64,u64>(f) }
    }

Here the compiler produces the correct result for the literal value but the runtime parsing function produces a different, incorrect result.  The difference is tiny, but of course it is enough to cause problems :)

For the record, here is the output of `rustc --version --verbose` on my system:

    rustc 1.0.0-nightly (30e1f9a1c 2015-03-14) (built 2015-03-15)
    binary: rustc
    commit-hash: 30e1f9a1c2bf7134135800bc9afd082773defadc
    commit-date: 2015-03-14
    build-date: 2015-03-15
    host: x86_64-unknown-linux-gnu
    release: 1.0.0-nightly

**Comment by lifthrasiir** [comment] 2015-03-19 04:32
I assume this is a duplicate of #7648. We have really hairy decimal to floating point routine right now.

**Comment by JRoush** [comment] 2015-03-19 15:57
@lifthrasiir Whoops, looks like you are right.

**Comment by steveklabnik** [comment] 2015-03-19 19:16
closing as duplicate

**Closed by steveklabnik** 2015-03-19 19:16 UTC
