### ISSUE TITLE
Rustc 1.12.0 Windows build of `ethcore` crate fails with LLVM error

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/rust#36924] opened 2016-10-03 10:32 UTC
Error produced:
```
EH pad must be jumped to via an unwind edge
  %cleanuppad13 = cleanuppad within none []
  br i1 %1927, label %bb99, label %bb102_cleanup_trampoline_bb99, !dbg !719592
```

As seen here: https://ci.appveyor.com/project/NikolayVolf/parity-g802m/build/1.3.0+1997#L640
Triggered by this update from 1.10.0 to 1.12.0: https://github.com/ethcore/parity/pull/2423

Either LLVM is broken or the generated IR is.
Feel free to change the title to something more descriptive. Unfortunately I haven't got a windows machine for testing, just the one broken appveyor build.

**Comment by alexcrichton** [comment] 2016-10-03 16:12
Historically most of these have been LLVM bugs, unfortunately, which are notoriously hard to track down. @rphmeier do you know if it'd be possible to minimize the test case at all?

**Comment by rphmeier** [comment] 2016-10-03 16:19
@alexcrichton yikes, I have no idea to be honest. Like I said, I haven't got a windows machine to test with and the test case as it stands is about 10-15k LoC on its own...

**Comment by nikomatsakis** [comment] 2016-10-04 09:29
This may well be related to MIR, as well. 

cc @rust-lang/compiler

**Comment by rphmeier** [comment] 2016-10-04 14:48
Confirmed a MIR issue: build succeeds with `RUSTFLAGS= -Zorbit=off`

**Comment by nikomatsakis** [comment] 2016-10-04 17:42
@rphmeier I am trying to get a windows setup up and going to test this and other reported problems (my previous Windows VM recently mysteriously lost its Network Driver and I've never been able to figure out how to get it back...). Any tips you can give me for reproducing it?  I guess just a vanilla x86_64 MSVC configuration?

**Comment by rphmeier** [comment] 2016-10-04 18:20
@nikomatsakis Thanks for looking into this. A vanilla x86_64 MSVC setup sounds right. The appveyor.yml contains a few additional setup steps which you might find useful: https://github.com/ethcore/parity/blob/master/appveyor.yml

**Comment by arkpar** [comment] 2016-10-04 18:30
@nikomatsakis the latest master has `debug = false` in Cargo.toml to work around this issue. Set it back to `true` or use this commit to reproduce:
`b1d8b84eb96ebd8a8fe4da1014a344fcd8b43085`

**Comment by nikomatsakis** [comment] 2016-10-05 14:40
So I am able to reproduce this. Interestingly, debug builds don't seem to encounter the issue.

**Comment by nikomatsakis** [comment] 2016-10-05 15:31
Huh, somewhat frustratingly, this...stopped reproducing for now. Not sure what is different now!

**Comment by nikomatsakis** [comment] 2016-10-05 17:11
Ah, I see, cargo build must be run from the `parity` directory, not `parity/parity`. This probably affects some relevant `Cargo.toml` settings...

**Comment by arielb1** [comment] 2016-10-05 19:30
Compiling `parity` takes a very long amount of time and does not seem to reproduce the bug - are there any good STR?

**Comment by nikomatsakis** [comment] 2016-10-05 22:14
@arielb1 and I discussed on IRC -- I am definitely able to reproduce, but I think @arielb1 was testing with 1.14, not 1.12. So this is quite possibly a bug that has been fixed in the meantime.

**Comment by arielb1** [comment] 2016-10-06 06:41
The problematic function seems to be `_ZN93_$LT$ethcore..evm..interpreter..Interpreter$LT$Cost$GT$$u20$as$u20$ethcore..evm..evm..Evm$GT$4exec17h1655a9f21f79ac34E"(%"2.std::result::Result<evm::evm::GasLeft, evm::evm::Error>"* noalias nocapture sret dereferenceable(64), %"evm::interpreter::Interpreter<usize>`, and LLVM seems to be chocking on it. I'm running a dump of simplifycfg to see whether something pops up (should have done that earlier).

I think dropping zeroing might have fixed it - it makes some of the control flow simpler (after inlining).

**Comment by arielb1** [comment] 2016-10-06 06:48
The code that is optimized wrong looks like this, basically:
```

bb111:                                            ; preds = %bb112
  store i8 0, i8* %tmp191
  cleanupret from %cleanuppad7 unwind label %bb110

bb112:                                            ; preds = %bb113, %bb113, %bb113
  %497 = load i8, i8* %tmp191, !range !3
  %498 = trunc i8 %497 to i1
  br i1 %498, label %bb111, label %bb112_cleanup_trampoline_bb110

bb113:                                            ; preds = %bb114
  %499 = getelementptr inbounds %"evm::interpreter::InstructionResult<usize>", %"evm::interpreter::InstructionResult<usize>"* %result, i32 0, i32 0
  %500 = load i64, i64* %499, !range !12
  switch i64 %500, label %bb113_cleanup_trampoline_bb110 [
    i64 0, label %bb112
    i64 1, label %bb112
    i64 6, label %bb112
  ]
```

Somehow, it is optimized into this (that is not only simplifycfg, but also a fair bunch of other passes):
```
bb113:                                            ; preds = %bb114
  %1427 = icmp ult i64 %result.sroa.0.1, 7
  br i1 %1427, label %bb110, label %bb113_cleanup_trampoline_bb110
```

**Comment by arielb1** [comment] 2016-10-06 06:59
Crashing IR available at `https://dl.dropboxusercontent.com/u/35340625/ethcore-rust-1.12.ll.xz` (huge, un-minified). `opt` output available at `https://dl.dropboxusercontent.com/u/35340625/verify-report.xz`.

**Comment by majnemer** [comment] 2016-10-06 17:40
Reduced IR:
```
target datalayout = "e-m:w-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-windows-msvc"

declare void @throw()

define void @bad_fn(i64 %val) personality i32 (...)* @__CxxFrameHandler3 {
entry:
  invoke void @throw()
          to label %unreachable unwind label %cleanup1

unreachable:
  unreachable

cleanup1:
  %cleanuppad1 = cleanuppad within none []
  switch i64 %val, label %cleanupdone2 [
    i64 0, label %cleanupdone1
    i64 1, label %cleanupdone1
    i64 6, label %cleanupdone1
  ]

cleanupdone1:
  cleanupret from %cleanuppad1 unwind label %cleanup2

cleanupdone2:
  cleanupret from %cleanuppad1 unwind label %cleanup2

cleanup2:
  %phi = phi i1 [ true, %cleanupdone1 ], [ true, %cleanupdone2 ]
  %cleanuppad2 = cleanuppad within none []
  call void @throw() [ "funclet"(token %cleanuppad2) ]
  unreachable
}

declare i32 @__CxxFrameHandler3(...)
```

The bug can be reproduced using opt -simplifycfg

**Comment by majnemer** [comment] 2016-10-06 17:56
The following patch fixes the reduced testcase, could you please test it?
```
diff --git a/lib/Transforms/Utils/SimplifyCFG.cpp b/lib/Transforms/Utils/SimplifyCFG.cpp
index 90ce672..2702b76 100644
--- a/lib/Transforms/Utils/SimplifyCFG.cpp
+++ b/lib/Transforms/Utils/SimplifyCFG.cpp
@@ -4503,7 +4503,8 @@ GetCaseResults(SwitchInst *SI, ConstantInt *CaseVal, BasicBlock *CaseDest,
        ++I) {
     if (TerminatorInst *T = dyn_cast<TerminatorInst>(I)) {
       // If the terminator is a simple branch, continue to the next block.
-      if (T->getNumSuccessors() != 1)
+      const auto *BI = dyn_cast<BranchInst>(T);
+      if (!BI || !BI->isUnconditional())
         return false;
       Pred = CaseDest;
       CaseDest = T->getSuccessor(0);
```

**Comment by arielb1** [comment] 2016-10-06 20:22
@majnemer

Is there an LLVM issue/PR for it?

**Comment by arielb1** [comment] 2016-10-06 20:27
Patch appears to fix problem (on Linux at least).

**Comment by majnemer** [comment] 2016-10-07 01:48
Fixed in LLVM r283517.

**Comment by nikomatsakis** [comment] 2016-10-11 20:16
This should be fixed on nightly builds now, right? I think we're just waiting on a backport?

**Comment by arielb1** [comment] 2016-10-13 20:09
Sure.

**Comment by brson** [comment] 2016-10-14 18:16
I believe https://github.com/rust-lang/rust/pull/37030 is the PR that fixes this. Not backported yet.

**Comment by arielb1** [comment] 2016-10-14 19:31
This is fixed by the SimplifyCfg PR, which *was* backported.

**Closed** 2016-10-20 16:17 UTC
Labels: A-mir, P-high, regression-from-stable-to-stable, T-compiler
