### ISSUE TITLE
Attributes on item macros are ignored

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#28284] opened 2015-09-07 11:55 UTC
This compiles and runs without warnings:

```rust
macro_rules! m {
    () => ( fn f(){} );
}

#[test]
m!();

fn main() {
    f();
}
```

I at least expected the unused attribute lint to catch this

**Comment by Eljay** [comment] 2015-09-07 18:07
They are not ignored, it's just that attributes on item macros apply to the macro expansion rather than the resultant item, e.g this errors as expected as the macro isn't expanded.
```rust
macro_rules! m {
    () => ( fn f(){} );
}

#[cfg(test)]
m!();

fn main() {
    f();
}
```

**Comment by jonas-schievink** [comment] 2015-09-07 18:10
Ah, and they're removed when the macro is expanded, which is why the lint doesn't pick them up.

**Comment by alexcrichton** [comment] 2015-09-08 18:07
Yeah as @Eljay noted this is actually working as intended, so closing.

**Closed by alexcrichton** 2015-09-08 18:07 UTC

**Comment by jonas-schievink** [comment] 2015-09-08 22:55
I still feel uneasy about the lint missing these attributes, but I guess that cannot be fixed unless the attribute system is rewritten
