### ISSUE TITLE
Initializing a zero-length array leaks the initializer

### ISSUE THREAD

**Issue by smarnach** [rust-lang/rust#74836] opened 2020-07-27 20:14 UTC
This bug was [reported on StackOverflow today](https://stackoverflow.com/questions/63104426/creating-an-array-of-size-0-consumes-value-forgetting-it). Filipe Rodrigues noticed that the initializer of a zero-length array is leaked:

```rust
#[derive(PartialEq, Debug)]
struct A;

impl Drop for A {
    fn drop(&mut self) {
        println!("Dropping A");
    }
}

fn main() {
    let vec: Vec<A> = vec![];
    let a = A;
    assert_eq!(vec, [a; 0]);
}
```
The code above does not run `drop()` for `a`, while I'd expect that it should. According to a comment by @mcarton, this regression occurred between Rust 1.11.0 and 1.12.0, i.e. when MIR code generation was enabled by default.

**Comment by LeSeulArtichaut** [comment] 2020-07-27 20:38
Minimized:
```rust
struct A;

impl Drop for A {
    fn drop(&mut self) {
        println!("Dropping A");
    }
}

fn main() {
    let a = A;
    let _ = [a; 0];
}
```

**Comment by Dylan-DPC** [comment] 2020-07-27 22:49
Marked as p-low as per the [discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374836.20Initializing.20a.20zero-length.20array.20leaks.20.E2.80.A6)

**Comment by Aaron1011** [comment] 2020-07-27 23:20
This is a really weird corner case. If we modify the example slightly:

```rust
struct A;

impl Drop for A {
    fn drop(&mut self) {
        println!("Dropping A");
    }
}

fn foo() -> [A; 0] {
    let a = A;
    [a; 0]
}

fn main() {
    foo();
}
```

them `[a; 0]` still moves `a` (`a` cannot be used again). However, the storage for `a` is destroyed once `foo` returns, so we would have to run the destructor when `foo` returns, *not* when `[a; 0]` is dropped. Effectively, the borrow-checker and the MIR drop logic disagree about who owns `a`.

**Comment by Aaron1011** [comment] 2020-07-27 23:25
Regardless of what we end up doing, I think we should add a lint for this kind of scenario, as I think whatever behavior we use is going to be surprising.

**Comment by SimonSapin** [comment] 2020-07-28 09:39
> However, the storage for `a` is destroyed once `foo` returns, so we would have to run the destructor when `foo` returns, _not_ when `[a; 0]` is dropped.

I would *not* expect a destructor to run when `foo` returns and `a` goes out of scope, because the value in `a` has been moved. If we did not have array literal syntax and used a constructor instead, the value in `a` would clearly be moved in the call and its ownership transferred to the constructor:

```rust
fn foo() -> [A; 0] {
    let a = A;
    <[A; 0]>::new(a)
}
```

When the array length is zero the repeating array "constructor" happens not to use the repeated value so it should be responsible for dropping it.

**Comment by RalfJung** [comment] 2020-07-28 20:51
> When the array length is zero the repeating array "constructor" happens not to use the repeated value so it should be responsible for dropping it.

Agreed. Dropping should happen at the location of `[expr; 0]`.

I am not sure a lint is the right solution here? If we want to change MIR building (this looks like a clear bug to me), I do not see what a lint would achieve.

**Comment by RalfJung** [comment] 2020-08-17 12:55
Hm, why does this even build? Usually array initializers only work for `Copy` types.

Is there a special case for when the array length is <= 1? I guess then we also need a special case during drop elaboration (or so) for when the array length is exactly 0?

Cc @matthewjasper @nikomatsakis (not sure who else to ping for MIR stuff)

**Comment by Lucretiel** [comment] 2020-10-14 18:59
> Hm, why does this even build? Usually array initializers only work for `Copy` types.
> 
> Is there a special case for when the array length is <= 1? I guess then we also need a special case during drop elaboration (or so) for when the array length is exactly 0?
> 
> Cc @matthewjasper @nikomatsakis (not sure who else to ping for MIR stuff)

Yup, it appears that `[value; 1]` is allowed to simply move a non-copy into an array: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0fb70a88ba96585cd6ed42b8c0259352). Definitely a bit odd but I can certainly understand why this'd be the case.

**Comment by tmiasko** [comment] 2020-12-02 15:28
I looked into fixing this by teaching parts of compiler that perform move based reasoning about special status of `Rvalue::Repeat` where length evaluates to zero. I had to change the move data gather to fix drop elaboration; transfer function used by const qualification so that it detects drop of a temporary in `const fn g() -> [String; 0] { [String::new(); 0] }`. Also, a few data flow analysis likely require changes as well, in particular `MaybeInitializedLocals` and `MaybeRequiresStorage`.

Though, maybe that particular case of repeat should be lower differently when building MIR so that it can be treated more uniformly later on?

**Comment by RalfJung** [comment] 2020-12-02 15:45
@tmiasko thanks for looking into this!

Once we are past drop elaboration, no special cases should be needed any more. But I am not sure how early/late in the pipeline that happens. Your list is somewhat concerning though, this sounds like it'd be very easy to miss a place and introduce a subtle bug.

OTOH, we cannot really use different MIR for this -- with const generics, `[expr; N]` has to work. Though actually... that can only compile when `expr: impl Copy`. So maybe we *can* have a special case. Maybe we can make `Rvalue::Repeat` *require* `Copy`, and use a different, more specialized primitive for the non-`Copy` case? I wonder how that interacts with `[const_expr; N]` though.

**Comment by tmiasko** [comment] 2020-12-02 18:11
To give a little more context to earlier comment, consider a MIR that before the drop elaboration looks as follows:

```rust
 _0 = [move _1; 0];
 drop(_1) -> bb2;
```

Currently, the local `_1` is considered to be moved from and the drop elaboration removes the `drop(_1)`. The fix explored in https://github.com/rust-lang/rust/issues/74836#issuecomment-737303412, was to change move data so that the drop remains. This is not sufficient though, because `Operand::Move` remains and some analysis assign a special meaning to it. Consequently they require similar adjustments. For example, in const qualification `Operand::Move`ed locals are assumed not to need a drop. In `MaybeRequiresStorage` they are assumed not to require a storage if they have not been borrowed.

**Comment by Aaron1011** [comment] 2020-12-02 18:19
I wonder if it would be simpler to modify the THIR -> MIR lowering to treat `[foo; 0]` as `{ foo; [] }`, and require that the MIR `Rvalue::Repeat` have a non-zero const value.

**Comment by RalfJung** [comment] 2020-12-02 18:40
> to treat [foo; 0] as { foo; [] }

Yeah, I wondered the same -- so this sounds like a promising idea.

> and require that the MIR Rvalue::Repeat have a non-zero const value.

That cannot work; for `Copy` types `N` might be a const generic so during THIR -> MIR lowering we cannot say if it is 0.
But we could require that non-`Copy` `Rvalue::Repeat` have a non-zero const value (except const array repeat expressions might break this so they could be another exception).

**Comment by tmiasko** [comment] 2020-12-02 18:40
I wondered about that too. So far I noticed that it would require additional changes to take into account lifetime extension / promotion, as direct implementation would allow:

```rust
fn main() {
    let _: &'static [String; 0] = &[String::new(); 0];
}
```

**Comment by RalfJung** [comment] 2020-12-02 18:43
Ah, interesting. We could probably allow this if we really wanted, or we could use a slightly different desugaring such as `(foo, []).1`.

**Comment by MikailBag** [comment] 2020-12-19 21:46
Shouldn't this be `I-unsound` as similar to #47949?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=aa5afcbb47e59595dc6ced846671c47f
is an adaptation of https://github.com/rust-lang/rust/issues/47949#issuecomment-616087084 for this bug.

**Comment by sivizius** [comment] 2021-01-22 14:23
Is a `[ T; 0 ]` of any use anyway? I mean, the size is `0 * sizeof(T) = 0`, so effectively a `()` or `struct U`. `[ T; 0 ]` might be a result of typo in `[ T; 10 ]` ore something like that, so why not a hard error for that?

**Comment by SimonSapin** [comment] 2021-01-22 14:58
The `[T; 0]` type *can* be very useful (for example to unsize it to an empty slice of type `&[T]`), but it’s typically created with a `[]` expression.

This issue is about `[sub_expression; 0]` expressions which are indeed much less useful, but introducing new hard errors is a very big hammer and not necessary here. We only need to change such expressions from behaving like `{ std::mem::forget(sub_expression); [] }` to behaving like `{ std::mem::drop(sub_expression); [] }`.

**Comment by steffahn** [comment] 2021-12-09 23:17
I’m unfamiliar with the compiler-internal mechanisms that are relevant here. From a user-perspective, the situation is – in my opinion – as follows
* for `[CONST; N]`, it feels unintuitive that the case `N == 0` would be special in instantiating the constant a different number than exactly `N` times. I.e. I _don’t_ think, `[CONST; 0]` should create an instance of `CONST` (with the effect of calling the destructor once, too, if it has one).
* considering the case with constants described above, it does feel wrong that `[x; 0]` would move and drop `x`. It if did, wouldn’t it also have to do this with constants to be consistent? I feel like it’s hard to find a convincing consistend approach here in general.
* afaict, the fact that `[EXPR; 0]` and `[EXPR; 1]` work with non-`Copy`-and-non-`const` expressions it entirely useless in practice. You could always also write `[]` or `[EXPR]` instead!
  * The only use-case of this  that I can think of is an elsewhere-defined `const`-item `FOO` that’s specified to be either zero or one, but you don’t want to rely on which one of the two values it has, e.g. because the defining crate wouldn’t consider a change a breaking change. Then `[EXPR; FOO]` could make sense and can’t easily be replaced by `[]` or `[EXPR]`; however `match FOO { 0 => [], 1 => [EXPR], _ => unreachable!() }` would still be a valid fix/replacement in this rare situation. Or `match FOO { 0 => {drop(EXPR); []}, 1 => [EXPR], _ => unreachable!() }` if that’s the intended behavior of the author.
  
My personal conclusion would be to entirely remove the special capabilities of `[EXPR; 0]` and `[EXPR; 1]` and make sure they only compile successfully whenever `[EXPR; 2]` would do so, too.

In order to avoid breakage, one could
* introduce a warning in the current edition for any usage of `[EXPR; 0]` or `[EXPR; 1]` (or `[EXPR; N]` where `N` is a constant that’s zero or one)
  * whenever `EXPR` has a non-`Copy` type _**and**_ is not the path of a `const` item
* make the warning a deny-by-default lint or a hard error in future editions
* also introduce a stronger (version of the) warning, that points our the concrete dangers of leaks, for the case of `[EXPR; 0]` (or `[EXPR; N]` where `N` is a constant that’s zero)
  * whenever `EXPR` has a non-`Copy` type _**and**_ is not the path of a `const` item
  * or alternatively, at least whenever `EXPR` has a type that is _**not**_ known to be free of drop-glue

**Closed** 2022-05-25 13:58 UTC
Labels: A-destructors, P-low, T-compiler, A-mir, regression-from-stable-to-stable, C-bug

**Comment by pwnorbitals** [comment] 2022-07-24 08:16
If this is closed, the warning update on this page might be outdated : https://doc.rust-lang.org/reference/expressions/array-expr.html
