### ISSUE TITLE
Generated docs on long pages render text on top of itself

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#88545] opened 2021-08-31 16:33 UTC
_I hope this is the right repo to report this, I wasn't sure if it should go in the main rust repo instead._

The generated docs for pages with a crazy number of items seem to give up on positioning and then just dump all subsequent entries on the same line past a certain point. It looks like it might be related to hardware acceleration, but I'm not sure.

For example, viewing https://doc.rust-lang.org/beta/core/arch/arm/index.html in Chrome 92 on Windows and hitting ctrl+pgdwn to go to the very bottom shows this:

![image](https://user-images.githubusercontent.com/606923/131541457-818982b5-447f-4c12-a0e2-dbbc99a26bb1.png)

**Comment by jyn514** [comment] 2021-08-31 21:10
@mqudsi no worries - rustdoc is used for both docs.rs and the main doc.rust-lang.org website, but docs.rs doesn't have control over the main site.

**Comment by jyn514** [comment] 2021-08-31 21:13
I can't reproduce this on mobile Chrome though - maybe it's related to the screen size?
![Screenshot_20210831-161236](https://user-images.githubusercontent.com/23638587/131576640-18919152-b28a-44a2-b7e3-6b8cb2b3b03d.png)

**Comment by Seadragon91** [comment] 2021-09-01 06:32
Can confirm that problem on my PC in Edge.
Also on my smartphone in Edge and Chrome, I need to change the view of the website to "Desktop website" then I see it there too.

**Comment by camelid** [comment] 2021-09-01 21:41
I can't reproduce this in Firefox on macOS, but I *can* in Chrome on macOS. So I'm guessing it's a bug specific to Blink because I think Chrome and Edge both use Blink, whereas Firefox does not.

**Comment by mqudsi** [comment] 2021-09-01 23:12
> It seems to be a bug with Blink's grid implementation. If I turn off the display: grid style it works (but obviously changes the layout).

I’m not saying it’s *not* grid, but just pointing out that changing the display completely changes the layout and so may avoid the problem even if it’s something else. In theory, anyway.

**Comment by ChrisDenton** [comment] 2021-09-01 23:26
Fair point. A minimal test case appears to show the same issue but I'll admit that does not necessarily determine the root cause:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Test display grid with lots of children</title>
</head>

<body style="display: grid;">
<script><!--//<![CDATA[
for (let i = 0; i < 600; i++) {
    document.write(`<div>Testing</div>`);
    document.write(`<div>Overtype</div>`);
}
//]]></script>
</body></html>
```

**Comment by mqudsi** [comment] 2021-09-01 23:50
I think your test case confirms the cause, at least from a black box perspective, sufficiently ;)

**Comment by dbalcomb** [comment] 2021-09-06 15:49
It looks like this issue was previously reported [here](https://github.com/rust-lang/rust/issues/87016) and there are some relevant links towards the end. Notably a confirmation that there is currently a 1000 row limit to grids in Blink. There is also a recent [reddit thread](https://www.reddit.com/r/rust/comments/piy00v/why_this_crate_document_doesnt_display_correctly/) on the issue.

**Comment by GuillaumeGomez** [comment] 2021-09-08 18:32
Do you have an idea @dns2utf8 ? The best would be to not use grid at all. If you have no idea, I'll send a fix in the next coming days.

**Comment by dns2utf8** [comment] 2021-09-09 11:11
I can confirm this with Chromium 93 and IE Edge 91. 
I tried adding a `<br>` after the grid-layout (works with floats sometimes) but will try some more.

It works with Firefox 91 and 92 so I assume it is a chrome render-engine bug.

**Comment by ChrisDenton** [comment] 2021-09-09 11:17
Yes it's a Blink bug: https://bugs.chromium.org/p/chromium/issues/detail?id=688640

**Comment by GuillaumeGomez** [comment] 2021-09-09 11:22
@dns2utf8 Which is why I think we should switch to another way of rendering which doesn't use the current grid at all.

**Comment by dns2utf8** [comment] 2021-09-09 12:02
Hm, ... I see your point.
Since it solves the viewport-scaling with mobile very nicely, what if we split the table into 1000 element chunks?
That would not make a difference on mobile and on desktop we would just loose the width consistency of the first column every 1000 element.

**Comment by GuillaumeGomez** [comment] 2021-09-09 12:06
I don't think this is a good idea. I'd really prefer to not rely on "limits" that could change independently outside of our control. I think we need to find another approach.

**Comment by dns2utf8** [comment] 2021-09-09 13:57
One idea I have is that we switch back to the table element if the table is too long.
This I would probably implement in the HTML generator.

Another one, we use the mobile layout on desktop too if the table is too long.
Here I would add a check in JavaScript to see if the last  two elements overlap and then add a class that switches the behaviour.

Or something else :relaxed:

**Comment by GuillaumeGomez** [comment] 2021-09-09 14:01
The annoying part is that the left column has to be the width of the largest element. Maybe we could rework that part so it doesn't need something so complicated and keep how it's displayed on mobile? If you have suggestions... :)

**Comment by mqudsi** [comment] 2021-09-09 14:04
*cough* tables *cough*. 

But seriously, if you use a css reset to remove all browser styling (are we already doing that?) you can use the table layout in the renderer to create code like our current grid (because we are barely using any of the actual grid features). A little bit of css to the cell classes makes it responsive.

**Comment by GuillaumeGomez** [comment] 2021-09-09 14:06
Or maybe we can do even simpler and just set width to both parts to 50% (or 30-70, well up to debate). Like this, the alignment for the right part will work and we don't need to worry about grid or table anymore.

**Comment by dns2utf8** [comment] 2021-09-09 15:14
In the upcoming CSS Grid-2 spec (https://www.w3.org/TR/css-grid-2/#overlarge-grids) there is this sentence:
```
...  in the range [-10000, 10000]), dropping all lines outside that limit.
```
So we would run into trouble if a table gets longer than 10k entries.

However:
```
... if a UA only supported grids with at most 1000 tracks in each dimension, the following placement properties:
  grid-row:
  grid-column:
```

To me the spec reads as, the UA (User Agent aka Browser) is free to enforce lower limits if there is not enough memory available. 

I would like to look at the `display: table*` because that would allow us to keep the automatic layout switching on mobile (and support for it looks good) https://caniuse.com/?search=table

**Comment by jyn514** [comment] 2021-09-15 21:23
This was fixed by https://github.com/rust-lang/rust/pull/88776, right?

**Comment by GuillaumeGomez** [comment] 2021-09-15 21:27
I'm waiting for #88816 before closing it.

**Comment by camelid** [comment] 2021-09-16 01:00
@GuillaumeGomez Can you add "Closes <this issue number>" to the PR description then, to make sure the issue is closed on merge?

**Closed** 2021-10-05 09:45 UTC
Labels: T-rustdoc, C-bug, A-rustdoc-ui
