### ISSUE TITLE
install.sh not marked executable in windows rustup packages

### ISSUE THREAD

**Issue by rillian** [rust-lang/rust#42205] opened 2017-05-24 21:46 UTC
Trying to repackage today's nightly rust I hit a permission error because the `install.sh` script included with the published packages used by rustup is no longer marked executable for windows targets. It's still executable for macOS.

I an work around by passing it to `/bin/sh` but the inconsistency surprised me and I wanted to make sure it was intentional. The documentation still refers to invoking `install.sh` directly.

**Comment by rillian** [comment] 2017-05-24 21:47
@Keruspe Thanks for fixing the sysconfdir issue. Any idea what's changed with this one?

**Comment by alexcrichton** [comment] 2017-05-25 03:11
I believe this is a dupe of https://github.com/rust-lang/rust/issues/42121, so closing in favor of that, but thanks for the report of course!

**Closed by alexcrichton** 2017-05-25 03:11 UTC
