### ISSUE TITLE
Stabilize proc_macro Span::source_text

### ISSUE THREAD

**Issue by jam1garner** [rust-lang/rust#101991] opened 2022-09-18 17:58 UTC
In the interest of improving error/diagnostic quality for macros I'd like to try and get some of the `proc_macro_span` feature stabilized. 

While some of these APIs don't seem to have consensus on their effect on IDE/language server support, the `source_text` API seems both well-tested and to have consensus that its result only being invalidated by edits to the contents of the macro makes it a non-issue for IDE support (as [noted by niko](https://github.com/rust-lang/rust/issues/54725) in #54725).

#### API

```rust
impl Span {
    pub fn source_text(&self) -> Option<String>;
}
```

@rustbot label +T-libs-api +A-macros +A-proc-macros

**Comment by joshtriplett** [comment] 2022-09-19 20:43
Nominating to consider for partial stabilization.

I remember we had a lot of conversation about some of the proc_macro APIs in the past. I don't remember this one in particular being of concern.

Does anyone on @rust-lang/libs-api know of any blockers for stabilizing this?

**Comment by jhpratt** [comment] 2022-09-20 00:05
Most of the discussion was related to either user-defined diagnostics or the line/column information being exposed. I see no reason this can't be stabilized.

**Comment by joshtriplett** [comment] 2022-09-20 13:35
@rfcbot merge

**Comment by BurntSushi** [comment] 2022-09-23 12:13
> While some of these APIs don't seem to have consensus on their effect on IDE/language server support, the `source_text` API seems both well-tested and to have consensus that its result only being invalidated by edits to the contents of the macro makes it a non-issue for IDE support (as [noted by niko](https://github.com/rust-lang/rust/issues/54725) in #54725).

@matklad Do you have thoughts here?

**Comment by BurntSushi** [comment] 2022-09-23 12:15
It would be nice to have an example in the docs for this API, if possible.

One other thing that pops out at me is the return type of `Option<String>`. My guess is that perf isn't generally a huge concern in this context, and therefore it's okay. But I don't know that for sure. Otherwise, this return type is going to force a clone/allocation on every call. I don't know enough about proc macro internals to judge whether that's reasonable or not.

**Comment by dtolnay** [comment] 2022-09-24 21:42
> There's also a question of line-endings. Does the returned text preserve original line-endings, or is it allowed to normalize to `\n`? I'd prefer to not expose original line endings.

@rfcbot concern a question of line-endings

**Comment by dtolnay** [comment] 2022-09-24 21:45
> What _could_ problematic is the macro somehow getting a span which "escapes" the macro (so, eg, the span for the whole file containing the macro) and querying the source of _that_, but I assume that's not possible.

Not the whole file, but it can certainly escape a single macro call, and can include totally unrelated items. It sounds similarly problematic as getting a span for the whole file.

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true
```

```rust
// src/lib.rs
#![feature(proc_macro_span)]

use proc_macro::TokenStream;

#[proc_macro]
pub fn source_text(input: TokenStream) -> TokenStream {
    let mut iter = input.into_iter();
    let begin = iter.next().unwrap().span();
    let end = iter.next().unwrap().span().resolved_at(begin);
    let joined = begin.join(end).unwrap();
    let source_text = joined.source_text().unwrap();
    format!("{source_text:?}").parse().unwrap()
}
```

```rust
// src/main.rs

macro_rules! source_text {
    ($end:ident) => {
        repro::source_text!(start $end)
    };
}

// huh
fn sick_fn_bro() {}

fn main() {
    println!("{}", source_text!(end));
}
```

```console
$ cargo run
start $end)
    };
}

// huh
fn sick_fn_bro() {}

fn main() {
    println!("{}", source_text!(end
```

@rfcbot concern span which escapes the macro

Is `join` supposed to return `None` here? Is `source_text` supposed to return `None`?

**Comment by jam1garner** [comment] 2022-09-25 23:18
I would personally expect that to fail at the source_text call (good find), unless we want to make more stringent guarantees about external spans being impossible to construct. (Personally my expectations of Span::join are that failures are about spans impossible to represent (from incompatible sources), not ones we choose not to let the user do things with)

**Comment by est31** [comment] 2022-09-26 13:50
I wonder whether one should do [`indoc`](https://github.com/dtolnay/indoc) style removals of indentation before returning the source text, or whether to not do that. Ideally, adding indentation to a macro invocation / struct declaration should not issue a recompilation.

**Comment by est31** [comment] 2022-09-26 14:05
(FTR, @dtolnay 's example above is using `join` which is unstable, but there are hacks to do [`join` with stable code](https://github.com/rust-lang/rust/issues/54725#issuecomment-649038464) as well)

**Comment by jam1garner** [comment] 2022-09-26 15:05
I think modifying whitespace outside of newline normalization is a bad idea. I'm not sure what usecase the API would be useful for if that were the case. Even for diagnostics/errors, changing the code formatting is detrimental?

**Comment by joshtriplett** [comment] 2022-10-04 15:31
I don't think we should do any modification to the source text, even newline normalization. I think we should just return the source text verbatim. If a user wants to normalize it, they can do so (or use any number of crates to do so); however, a user can't *un*-normalize it if we've normalized it.

**Comment by matklad** [comment] 2022-10-04 15:39
To clarify why normalizing might be a good idea: 

What line endings are used is already somewhat ill-defined. The source code of the same git project checked out on Linux and on Windows would typically have different line-endings. 

If we don't normalize line-endings and expose them to proc-macros, that opens another avenue why, eg, `cargo build --target wasm32-unknown-unknown` might give different results depending on the host OS the project is compiled on. 

I don't think that *in practice* there will be a lot of these sorts of problems, but if we are committed to reproducible builds *in principle*, it seems worthwhile to not add fundamental non-determinism, if we can help it.

**Comment by Amanieu** [comment] 2022-10-04 15:46
I think that differing newlines will already cause issues with reproducible builds since all of the spans will have different offsets, the debuginfo will be different, etc. I think it's reasonable to require configuring git to preserve line endings if you want reproducible builds.

**Comment by dtolnay** [comment] 2022-10-04 19:42
I don't feel that either of these warrants blocking the stabilization of `source_text`:

@rfcbot resolve a question of line-endings
@rfcbot resolve span which escapes the macro

For line endings, either normalizing or not is okay with me. For spans that cross boundaries of a macro invocation, I'd probably prefer if `join` would return `None` in this situation but it's pretty far down the list of things wrong/broken with macros already, so I don't find it concerning for this stabilization.

**Comment by est31** [comment] 2022-10-14 20:23
> For spans that cross boundaries of a macro invocation, I'd probably prefer if `join` would return `None` in this situation but it's pretty far down the list of things wrong/broken with macros already, so I don't find it concerning for this stabilization.

@dtolnay how would you deal with join being already exposed on stable, without an Option like interface? I've pointed that out above in the thread, linking to a comment that links to a [join primitive in your syn crate](https://docs.rs/syn/1.0.23/src/syn/error.rs.html#219-238). Given that the API is already stable and doesn't return an Option, it should IMO be `source_text` that returns a None if a span is unhygienic. Maybe spans could contain a bool param on whether they are hygienic or not, which is set by join as well as join-like primitives. Then `source_text` checks that bool and makes its descision based on that. This stuff can I think be done after `source_text` stabilization, too.

**Comment by est31** [comment] 2022-10-18 14:54
@m-ou-se good point. I've tried building a similar primitive that joins spans in a similar fashion, but it doesn't work:

```Rust
fn join_spans(sp1: Span, sp2: Span) -> Span {
    let begin = TokenTree::Ident(Ident::new("A", sp1));
    let end = TokenTree::Ident(Ident::new("B", sp2));
    let group = Group::new(Delimiter::None, [begin, end].into_iter().collect());
    group.span()
}
```

If you try that on the example from dtolnay given above, you get as output:

```
        repro::source_text!(start $end)
```

It's I think because the group wholly ignores the spans of its children and instead assumes the span of the macro invocation that created it. I guess this combination trick can only be used to issue compilation errors. So things work differently than I thought they would work. I'm sorry for having brought this up. Case rested :).

**Comment by est31** [comment] 2022-10-18 15:11
Stabilization PR: #103197

**Closed** 2022-10-20 16:20 UTC
Labels: A-macros, T-libs-api, disposition-merge, finished-final-comment-period, A-proc-macros, to-announce
