### ISSUE TITLE
Compier crash when compiling serde_json v1.0.72

### ISSUE THREAD

**Issue by psionic12** [rust-lang/rust#91785] opened 2021-12-11 12:19 UTC
### Code

```Rust
cargo expand
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0

```

### Error output

```
   Compiling serde_json v1.0.72
thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/0b42deaccc2cbe17a68067aa5fdb76104369e1fd\compiler\rustc_serialize\src\opaque.rs:669:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
note: rustc 1.59.0-nightly (0b42deacc 2021-12-09) running on x86_64-pc-windows-msvc
note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
note: some of the compiler flags provided by cargo are hidden
query stack during panic:
end of query stack
error: could not compile `serde_json`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by matthiaskrgr** [comment] 2021-12-11 13:01
duplicate of https://github.com/rust-lang/rust/issues/91663

**Closed** 2021-12-11 14:42 UTC
Labels: I-ICE, T-compiler, C-bug
