### ISSUE TITLE
cannot borrow as mutable because it is also borrowed as immutable (likely regression)

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#60136] opened 2019-04-20 15:50 UTC
From a crater run:

```
 Compiling web-dom v0.0.8
[INFO] [stderr]    Compiling webcomponent v0.3.3 (/opt/crater/workdir)
[INFO] [stderr] error[E0502]: cannot borrow `*controller` as mutable because it is also borrowed as immutable
[INFO] [stderr]   --> src/lib.rs:27:13
[INFO] [stderr]    |
[INFO] [stderr] 27 |             (controller.processor)(controller, &tag, el);
[INFO] [stderr]    |             ----------------------^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]    |             |
[INFO] [stderr]    |             mutable borrow occurs here
[INFO] [stderr]    |             immutable borrow occurs here
[INFO] [stderr]    |             immutable borrow later used by call
[INFO] [stderr] 
[INFO] [stderr] error: aborting due to previous error
```

crate(s) affected: webcomponent (0.3)
author: @richardanaya
log: https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/webcomponent-0.3.3/log.txt

**Comment by matthewjasper** [comment] 2019-04-20 18:33
cc #59500

This can be fixed by using `(*controller.processor)` to avoid the new implementation in that PR.

**Comment by nikomatsakis** [comment] 2019-04-25 14:04
@matthewjasper can you elaborate a bit on how #59500 is related here?

**Comment by nagisa** [comment] 2019-04-25 14:20
Would be great to have a bisection and/or reduction of the reproducer. Cursory look at the contents of the web-dom crate indicates that it should be fairly easy to make a reproducer here.

**Comment by lqd** [comment] 2019-04-25 15:03
Reduction — [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=0264234238f23c284494b1b35d47066a)

```rust
struct CustomElements {
    processor: Box<fn(&mut CustomElements)>,
}

fn main() {
    move |controller: &mut CustomElements| {
        (controller.processor)(controller);
    };
}

```

**Comment by nikomatsakis** [comment] 2019-04-25 16:20
OK, wait, I didn't read #59500 closely enough. I can see why this regression occurred. We didn't used to consider `Box<fn(...)>` to implement `Fn`, but we do now (because of the impls added in #59500). This means that `(controller.processor)` winds up being desugared as a call through `Fn` to the `Box<..>`, instead of inserting an auto-deref. This is the sort of breakage we typically accept (for better or worse) as a result of adding new impls.

**Comment by nikomatsakis** [comment] 2019-04-25 16:22
The workaround is to change to `(*controller.processor)`, although I suspect the *better* fix is to remove the `Box` altogether and just store the `fn(&mut CustomElements)` directly. =) (but maybe there's another reason to have the `Box`)

**Comment by pnkfelix** [comment] 2019-05-02 14:18
Closing, as the code breakage described here was an expected consequence of teh `impl` that were added in PR #59500.

**Comment by nikomatsakis** [comment] 2019-05-02 14:18
[Discussed at the compiler meeting today](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-05-02.20.2354818/near/164711496). We are closing this as a permissible regression -- as I [noted earlier](https://github.com/rust-lang/rust/issues/60136#issuecomment-486741573), adding the impl caused the `()` operator to insert fewer dereferences than is used to, which leads to a compiler error. This is unfortunate but it is the sort of breakage that we current permit.

**Closed by pnkfelix** 2019-05-02 14:18 UTC
Labels: P-high, T-compiler, regression-from-stable-to-beta
