### ISSUE TITLE
It is possible to write to a filed of uninitialized struct

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#31947] opened 2016-02-28 08:17 UTC
It is impossible to read a filed of uninitialized struct, but for some reason the write is allowed (but you can't read it back later):

```Rust
struct S {x: i32, y: i32}

fn main() {
    let mut s: S;
    s.x = 32;           // why I don't get an error here,
    s.y = 12;
    println!("{}", s.x) // but get it here instead?
}
```

Originally reported at https://users.rust-lang.org/t/use-of-possibly-uninitialized-variable-on-an-initialized-variable/4799/4

**Comment by Aatch** [comment] 2016-02-28 08:34
This is fundamentally the same issue as #21237, as the analysis treats uninitialized variables and moved ones essentially the same way.

Closing as a duplicate of that.

**Closed by Aatch** 2016-02-28 08:34 UTC

**Comment by lilianmoraru** [comment] 2016-02-28 09:57
@matklad I think you should probably paste your code example in the original issue since it's a lot more simple than what is in that issue.
