### ISSUE TITLE
Documentation links are difficult

### ISSUE THREAD

**Issue by matthew-piziak** [rust-lang/rust#36417] opened 2016-09-12 14:56 UTC
# Workflow criteria

An efficient workflow must satisfy one of two criteria:
- _Determinism_: the change of success per attempt is high.
- _Iteration Speed_: the frequency of attempts is high.

Composing links in documentation does not currently satisfy either of these criteria. The rules for linking are mysterious enough that a contributor cannot be confident that they will work without running `make docs`. 
# Examples of pain

https://github.com/rust-lang/rust/issues/32130: a struct can be viewed from two locations, at varying depths of links; sometimes links to methods refer to the wrong modules.
https://github.com/rust-lang/rust/pull/35880: doc entities are replicated between `std` and `core`.
https://github.com/rust-lang/rust/pull/35759: directory links are confusing; anchors are case sensitive and do not match rendered content.
[#rust-docs logs](https://botbot.me/mozilla/rust-docs/2016-09-09/?msg=72755803&page=1): Linkchecker is not always reliable (or potentially has usability problems).
[#rust-docs logs](https://botbot.me/mozilla/rust-docs/2016-09-14/?msg=73036621&page=2): If a URL is present in both item description and short description, in the second case it won't work.
# Potential resolutions

My hope is that this problem is procedural. It's entirely likely that I'm just wrong! If that's the case, then this issue can be resolved with documentation that either: 1) specifies a fast way to programmatically check docs locally, or 2) specifies a deterministic set of rules (a checklist) that allows a contributor to verify that their links will be successful _without_ compiling them.

If I'm _not_ wrong, then the problem becomes more difficult, which is why I created this issue. I appreciate any insight from more experienced members of the community.

**Comment by ollie27** [comment] 2016-09-12 16:45
> #rust-docs logs: Linkchecker is not always reliable (or potentially has usability problems).

There seems to have been some confusion here. linkchecker needs to be run on the doc output directory, not the source code directory. So assuming you're using the Makefiles the full instructions would look something like:

```
$ ./configure
$ make docs
$ cd src/tools/linkchecker
$ cargo run --release -- ../../../doc

**Comment by durka** [comment] 2016-09-12 17:24
3) Make up a real syntax for linking to Rust items (requires a Markdown extension or pre/postprocessor). See https://github.com/rust-lang/rfcs/pull/1661

**Comment by steveklabnik** [comment] 2017-04-24 11:52
https://github.com/rust-lang/rfcs/pull/1946 should help with this!

**Comment by steveklabnik** [comment] 2017-08-30 19:19
RFC was merged, closing as a duplicate of https://github.com/rust-lang/rust/issues/43466

**Closed by steveklabnik** 2017-08-30 19:19 UTC
Labels: C-feature-request, T-dev-tools, T-doc
