### ISSUE TITLE
.. syntax copies lifetime

### ISSUE THREAD

**Issue by DzenanJupic** [rust-lang/rust#91219] opened 2021-11-25 13:07 UTC
I tried this code [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=20323306116c8ab342d6a5ce9fee05e2):

```rust
use std::borrow::Cow;

struct S<'a> {
    cow: Cow<'a, str>,
    owned: String,
}

fn make_owned(s: S<'_>) -> S<'static> {
    S {
        cow: Cow::Owned(s.cow.into_owned()),
        owned: s.owned,
    }
}

// does not work
// fn make_owned2(s: S<'_>) -> S<'static> {
//     S {
//         cow: Cow::Owned(s.cow.into_owned()),
//         ..s
//     }
// }
```

### I expected to see this happen: 

Since all fields with a lifetime were replaced by owned values I expected `make_owned2` to compile. 

### Instead, this happened: 

The compiler is unable to understand, that the remaining fields don't influence the lifetime of the struct.

```
error[E0621]: explicit lifetime required in the type of `s`
  --> src/lib.rs:18:5
   |
18 | /     S {
19 | |         cow: Cow::Owned(s.cow.into_owned()),
20 | |         ..s
21 | |     }
   | |_____^ lifetime `'static` required
```

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (65f3f8b22 2021-11-21)
binary: rustc
commit-hash: 65f3f8b220f020e562c5dd848ff7319257a7ba45
commit-date: 2021-11-21
host: x86_64-pc-windows-msvc
release: 1.58.0-nightly
LLVM version: 13.0.0
```

**Comment by fmease** [comment] 2021-11-25 16:46
In the current version of Rust, this works as intended: The type cannot change with the struct update syntax. On nightly with `#![feature(type_changing_struct_update)]`, your second function compiles successfully. See #86555.

**Comment by nagisa** [comment] 2021-11-25 16:49
Closing as…

Duplicate of #86555

**Closed by nagisa** 2021-11-25 16:49 UTC
Labels: C-bug
