### ISSUE TITLE
Compiler doesn't optimise away memory allocation.

### ISSUE THREAD

**Issue by norpadon** [rust-lang/rust#94109] opened 2022-02-18 02:38 UTC
In the following code rustc nightly (but not 1.58!) can successfully remove memory allocation and directly inline the answer: https://godbolt.org/z/s8G33jWEv
```rust
pub struct BBox {
    top: i32,
    left: i32,
    height: i32,
    width: i32
}

fn fiddle(bbox: &BBox) -> Box<BBox> {
    Box::new(BBox {
        top: bbox.top * 2,
        ..*bbox
    })
}

pub fn main() {
    let bbox = Box::new(BBox {
            top: 551,
            left: 100,
            height: 200,
            width: 180,
    });
    let bbox = fiddle(&bbox);
    let bbox_top = bbox.top;
    println!("{}", bbox_top)
}
```
But if I replace
```rust
let bbox_top = bbox.top;
println!("{}", bbox_top)
```
with 
```rust
println!("{}", bbox.top)
```
it stops applying this optimisation: https://godbolt.org/z/oY8WrvfE7

Both clang and GCC can easily optimise equivalent C code:
https://godbolt.org/z/be9zPvYMj

**Comment by nikic** [comment] 2022-02-18 08:41
Duplicate of #50519. This is a general problem with `println!()` captures, not really related to allocations.

**Closed by nikic** 2022-02-18 08:41 UTC
