### ISSUE TITLE
ICE: escaping regions in predicate Obligation(...)

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#43718] opened 2017-08-07 17:19 UTC
```rust
#![feature(conservative_impl_trait)]


fn iter_values(a: &[u32]) -> impl Iterator<Item=&u32>{
    a.iter().map(|a| &a)
}
```

([playpen](https://play.rust-lang.org/?gist=7743b4fa5ae2cbd45d0a70f71cec4a41&version=nightly) )

throws

```
   Compiling playground v0.0.1 (file:///playground)
error: internal compiler error: /checkout/src/librustc_typeck/check/mod.rs:618: escaping regions in predicate Obligation(predicate=Binder(ProjectionPredicate(ProjectionTy { substs: Slice([_]), item_def_id: DefId { krate: CrateNum(2), node: DefIndex(1591) => core/e78183f::iter[0]::iterator[0]::Iterator[0]::Item[0] } }, &u32)),depth=0)
  --> src/main.rs:21:30
   |
21 |     fn iter_values(&self) -> impl Iterator<Item=&u32>{
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^

note: the compiler unexpectedly panicked. this is a bug.
```

**Comment by Manishearth** [comment] 2017-08-07 17:23
cc @nikomatsakis @eddyb

**Comment by kennytm** [comment] 2017-08-20 13:51
Duplicate of #42479

**Closed** 2017-12-23 12:40 UTC
Labels: A-impl-trait, C-bug, I-ICE
