### ISSUE TITLE
llvm: Stored value type does not match pointer operand type!

### ISSUE THREAD

**Issue by yorkie** [rust-lang/rust#30494] opened 2015-12-20 10:29 UTC
Hey Rust Team,

I got this error at compiling time:

```
Stored value type does not match pointer operand type!
  store { i64 } %0, i64* %2, align 8
 i64LLVM ERROR: Broken function found, compilation aborted!
Could not compile `rustjs`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name rustjs --crate-type lib -g --out-dir /Users/yorkieliu/workspace/rust.js/target/debug --emit=dep-info,link -L dependency=/Users/yorkieliu/workspace/rust.js/target/debug -L dependency=/Users/yorkieliu/workspace/rust.js/target/debug/deps --extern clap=/Users/yorkieliu/workspace/rust.js/target/debug/deps/libclap-b681d5dfd49166f9.rlib --extern rustc_serialize=/Users/yorkieliu/workspace/rust.js/target/debug/deps/librustc_serialize-3c33cb2a40992011.rlib --extern libc=/Users/yorkieliu/workspace/rust.js/target/debug/deps/liblibc-dd3420cb049117bb.rlib --extern env_logger=/Users/yorkieliu/workspace/rust.js/target/debug/deps/libenv_logger-2fedde90a22290a6.rlib -l rustjs_deps` (exit code: 1)
make: *** [rustjs] Error 101
```

With my personal rust module: https://github.com/yorkie/rust.js, I found the same issue at https://github.com/rust-lang/rust/issues/19571.

I used the latest 1.5.0, however it worked at 1.0.0.

**Comment by eddyb** [comment] 2015-12-21 01:51
This seems unrelated to #19571.
Can you try other versions? If your code compiles on them, that is.
If you have `multirust`, it should be trivial to switch between versions.

I could try to reduce rust.js myself, it looks like a moderately sized project.

**Comment by eddyb** [comment] 2015-12-21 03:14
[Minimal reproduction](https://play.rust-lang.org/?gist=d90352ede36ed7f5d77e&version=stable):
```rust
struct Foo;
impl Foo {
    extern fn foo(_: [u8; 1]) {}
}
```
It appears that `extern` methods (not free functions) have their arguments incorrectly translated.
cc @dotdash @Aatch

**Comment by yorkie** [comment] 2015-12-21 03:17
Thanks @eddyb for that so detailed reply, do you think it's related to this commit https://github.com/yorkie/rust.js/commit/9525af074e61b84266bb178adbe4e0af20ccba78?

**Comment by eddyb** [comment] 2015-12-21 03:36
No, not really.
The problem stems from the fact that you're passing structures by value in arguments, e.g.:
```rust
#[repr(C)]
pub struct FunctionCallbackInfo(*mut *mut FunctionCallbackInfo);

...

impl StringBytes {
  extern fn New(arguments: v8::FunctionCallbackInfo) {
    arguments.GetReturnValue().SetWithBool(true);
  }
}
```
One way you might be able to work around this bug would be to remove one level of indirection, e.g.

```rust
extern {
  fn v8_function_callback_info_get_return_value(this: &mut FunctionCallbackInfo) -> &mut ReturnValue;
}

// Doesn't really matter what's inside, can still pretend there's a pointer there.
#[repr(C)]
pub struct FunctionCallbackInfo(*mut u8);
#[repr(C)]
pub struct ReturnValue(*mut u8);

impl FunctionCallbackInfo {
  pub fn GetReturnValue(&mut self) -> &mut ReturnValue {
    unsafe { v8_function_callback_info_get_return_value(self) }
  }
}

impl StringBytes {
  extern fn New(arguments: &mut v8::FunctionCallbackInfo) {
    arguments.GetReturnValue().SetWithBool(true);
  }
}
```

And on the C++ side:
```cpp
ReturnValue<Value> v8_function_callback_info_get_return_value(FunctionCallbackInfo<Value> *callbackInfo) {
  return callbackInfo->GetReturnValue();
}
```

It would be a pretty big change, but it should make your code compile.

**Comment by eddyb** [comment] 2015-12-21 04:10
@yorkie Sorry, I was overthinking this, you should be able to get away with just moving `extern fn` methods out of `impl` blocks (and make them free functions).

This issue is also related to #30235.

**Comment by arielb1** [comment] 2016-04-27 15:34
duplicate of #30235.

**Closed by arielb1** 2016-04-27 15:34 UTC
Labels: A-codegen
