### ISSUE TITLE
ICE: Cannot fill in a NT

### ISSUE THREAD

**Issue by alex** [rust-lang/rust#30005] opened 2015-11-23 17:36 UTC
Code that causes this is the commit: https://github.com/alex/rust-asn1/commit/01fb3a46fb175b9d18a8eee54ec21236d3ff9b1c

```
~/p/h/rust-asn1 (macros!) $ cargo --version
cargo 0.7.0-nightly (fb73974 2015-11-18)
~/p/h/rust-asn1 (macros!) $ rustc --version
rustc 1.6.0-nightly (9303055f3 2015-11-19)

~/p/h/rust-asn1 (macros!) $ env RUST_BACKTRACE=1 cargo test
   Compiling asn1 v0.2.0 (file:///Users/alex_gaynor/projects/hacks/rust-asn1)
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'Cannot fill in a NT', ../src/libsyntax/ext/tt/macro_parser.rs:231
stack backtrace:
   1:        0x10e7882d8 - sys::backtrace::tracing::imp::write::hed3a593bad2e5fa3Hqt
   2:        0x10e78e3bf - panicking::log_panic::_<closure>::closure.39899
   3:        0x10e78de85 - panicking::log_panic::hb58e0c0eab041fc722w
   4:        0x10e756cb6 - sys_common::unwind::begin_unwind_inner::h04a0f5a988ff29c8fus
   5:        0x10bfd80d4 - sys_common::unwind::begin_unwind::begin_unwind::h1899476532851499354
   6:        0x10c2d4dcf - ext::tt::macro_parser::nameize::n_rec::h56397634fcbac352mEg
   7:        0x10c2d3efa - ext::tt::macro_parser::nameize::n_rec::h56397634fcbac352mEg
   8:        0x10c2d3955 - ext::tt::macro_parser::nameize::hc7d832db29639b76ZDg
   9:        0x10c013e45 - ext::tt::macro_parser::parse::h9a85e2200cdb2da0OIg
  10:        0x10c00f9e2 - ast::_<impl>::parse::h98551a9249185112crm
  11:        0x10c2d76b5 - ext::tt::macro_rules::_<impl>::expand::h861ff4d0eb6ebabeIjh
  12:        0x10c25d2eb - ext::expand::expand_stmt::hb259bbc2eb566d2dWnc
  13:        0x10c25fcc4 - iter::_<impl>::next::next::h17671416924187637066
  14:        0x10c25f717 - util::small_vector::_<impl>::from_iter::h7967959137598168227
  15:        0x10c25e510 - ext::expand::expand_stmt::hb259bbc2eb566d2dWnc
  16:        0x10c25fcc4 - iter::_<impl>::next::next::h17671416924187637066
  17:        0x10c25f717 - util::small_vector::_<impl>::from_iter::h7967959137598168227
  18:        0x10c25e510 - ext::expand::expand_stmt::hb259bbc2eb566d2dWnc
  19:        0x10c26663e - ext::expand::expand_block_elts::_<closure>::_<closure>::closure.70820
  20:        0x10c26637a - iter::_<impl>::next::next::h5102132128357539218
  21:        0x10c265a67 - vec::_<impl>::from_iter::from_iter::h3566966524861020544
  22:        0x10c26565f - ext::expand::expand_block_elts::_<closure>::closure.70815
  23:        0x10c2486c4 - ext::expand::expand_block_elts::hf2bb11c32c2b3837wzc
  24:        0x10c2652ad - ext::expand::expand_block::hec874702bbd0e2e6Ryc
  25:        0x10c242ac9 - ext::expand::expand_and_rename_fn_decl_and_block::hc79451ded6095dbdWWc
  26:        0x10c24e4fb - ext::expand::expand_item_underscore::h3fd8e962bcef5439ldc
  27:        0x10c2838da - fold::noop_fold_item_simple::h8625582316750043535
  28:        0x10c283479 - fold::noop_fold_item::h4560102753294209906
  29:        0x10c24c4da - ext::expand::expand_annotatable::hb456f734932d5478IJc
  30:        0x10c248878 - ext::expand::expand_item::h73368fbef9f27f94Kcc
  31:        0x10c254459 - iter::_<impl>::next::next::h17003945266231609005
  32:        0x10c253d99 - vec::_<impl>::from_iter::from_iter::h2332205991289285955
  33:        0x10c253c8a - fold::noop_fold_mod::h15298307300304803159
  34:        0x10c24ed59 - ext::expand::expand_item_underscore::h3fd8e962bcef5439ldc
  35:        0x10c2838da - fold::noop_fold_item_simple::h8625582316750043535
  36:        0x10c283479 - fold::noop_fold_item::h4560102753294209906
  37:        0x10c24d774 - ext::expand::expand_annotatable::hb456f734932d5478IJc
  38:        0x10c248878 - ext::expand::expand_item::h73368fbef9f27f94Kcc
  39:        0x10c254459 - iter::_<impl>::next::next::h17003945266231609005
  40:        0x10c253d99 - vec::_<impl>::from_iter::from_iter::h2332205991289285955
  41:        0x10c253c8a - fold::noop_fold_mod::h15298307300304803159
  42:        0x10c24ed59 - ext::expand::expand_item_underscore::h3fd8e962bcef5439ldc
  43:        0x10c2838da - fold::noop_fold_item_simple::h8625582316750043535
  44:        0x10c283479 - fold::noop_fold_item::h4560102753294209906
  45:        0x10c24d774 - ext::expand::expand_annotatable::hb456f734932d5478IJc
  46:        0x10c248878 - ext::expand::expand_item::h73368fbef9f27f94Kcc
  47:        0x10c254459 - iter::_<impl>::next::next::h17003945266231609005
  48:        0x10c253f6c - vec::_<impl>::from_iter::from_iter::h2332205991289285955
  49:        0x10c253c8a - fold::noop_fold_mod::h15298307300304803159
  50:        0x10c24ed59 - ext::expand::expand_item_underscore::h3fd8e962bcef5439ldc
  51:        0x10c2838da - fold::noop_fold_item_simple::h8625582316750043535
  52:        0x10c283479 - fold::noop_fold_item::h4560102753294209906
  53:        0x10c24d774 - ext::expand::expand_annotatable::hb456f734932d5478IJc
  54:        0x10c248878 - ext::expand::expand_item::h73368fbef9f27f94Kcc
  55:        0x10c28cb30 - ext::expand::expand_crate::h1df31f72279c7409M7c
  56:        0x10a9edb63 - driver::phase_2_configure_and_expand::_<closure>::closure.30653
  57:        0x10a9832ac - driver::phase_2_configure_and_expand::h7422c866975e0e21rxa
  58:        0x10a963058 - driver::compile_input::h8d4b0785a6db2adecca
  59:        0x10a957010 - run_compiler::hd87e09e88aee8063zvc
  60:        0x10a953f74 - sys_common::unwind::try::try_fn::try_fn::h15673213591594754549
  61:        0x10e785df8 - __rust_try
  62:        0x10e77edee - sys_common::unwind::try::inner_try::h8d045a0856c3c0c6Nqs
  63:        0x10a954357 - boxed::_<impl>::call_box::call_box::h17214083893843285296
  64:        0x10e78d75d - sys::thread::_<impl>::new::thread_start::h91ae880d71f644c2WCw
  65:     0x7fff99eb99b0 - _pthread_body
  66:     0x7fff99eb992d - _pthread_start

Could not compile `asn1`.

To learn more, run the command again with --verbose.
```

**Comment by alex** [comment] 2015-11-23 17:42
Note that this is triggered by a bug in my code if I add the necessary `:ty` it works again. Obviously the compiler shouldn't ICE though :-)

**Comment by jonas-schievink** [comment] 2015-11-23 17:52
This is supposed to say "missing fragment specifier". [Repro](http://is.gd/X0fza4):

```rust
macro_rules! m {
    ( $( any_token $field_rust_type )* ) => {};
}

fn main() {
    m!();
}
```

**Comment by jonas-schievink** [comment] 2015-11-23 17:52
Possible duplicate of #27092

**Comment by alex** [comment] 2015-11-23 18:04
The backtraces don't look identical, but I don't know if the differences are relevant.

**Closed** 2015-11-26 00:20 UTC
Labels: A-macros, I-ICE
