### ISSUE TITLE
Error performing operation: fully_perform

### ISSUE THREAD

**Issue by thomasyonug** [rust-lang/rust#126091] opened 2024-06-06 18:51 UTC
### Code

```Rust

#![deny(rustdoc::broken_intra_doc_links)]
#![feature(no_core, lang_items, rustc_attrs, rustdoc_internals)]
#![no_core]
#![rustc_coherence_is_core]
#![crate_type = "rlib"]
#[rustc_doc_primitive = "char"]
mod char {}
impl char {
    pub fn len_utf8(self) -> usize {
        unsafe {
            let num: *const usize = &42;
            *num
        }
    }
}
#[lang = "sized"]
pub trait Sized {}
#[lang = "clone"]
pub trait Clone: Sized {}
#[lang = "copy"]
pub trait Copy: Clone {}
fn main() {}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.80.0-nightly (debd22da6 2024-05-29)
binary: rustc
commit-hash: debd22da66cfa97c74040ebf68e420672ac8560e
commit-date: 2024-05-29
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.6
```

### Error output

```
[<output>](error: internal compiler error: error performing operation: fully_perform)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_mir_build/src/build/custom/mod.rs:122:17:
Box<dyn Any>
stack backtrace:
   0:     0x7f7fad49fdf5 - std::backtrace_rs::backtrace::libunwind::trace::h90edf881e325b8a6
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7f7fad49fdf5 - std::backtrace_rs::backtrace::trace_unsynchronized::h50a92732fba3c474
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f7fad49fdf5 - std::backtrace::Backtrace::create::he9f1866b659d60fe
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/std/src/backtrace.rs:331:13
   3:     0x7f7fad49fd45 - std::backtrace::Backtrace::force_capture::h2ae0a04b4f80a856
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/std/src/backtrace.rs:312:9
   4:     0x7f7fb0670e26 - std[9d83bd0e50f0e1cd]::panicking::update_hook::<alloc[c6e8cd8d3db589af]::boxed::Box<rustc_driver_impl[c903d310d0b65222]::install_ice_hook::{closure#0}>>::{closure#0}
   5:     0x7f7fad4bac0b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc73dfd93ee0f7266
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/alloc/src/boxed.rs:2077:9
   6:     0x7f7fad4bac0b - std::panicking::rust_panic_with_hook::h2209cb47b146c46d
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/std/src/panicking.rs:799:13
   7:     0x7f7fb06a0e14 - std[9d83bd0e50f0e1cd]::panicking::begin_panic::<rustc_errors[34f4f8fe0a9126a8]::ExplicitBug>::{closure#0}
   8:     0x7f7fb069dbc6 - std[9d83bd0e50f0e1cd]::sys_common::backtrace::__rust_end_short_backtrace::<std[9d83bd0e50f0e1cd]::panicking::begin_panic<rustc_errors[34f4f8fe0a9126a8]::ExplicitBug>::{closure#0}, !>
   9:     0x7f7fb069d8a6 - std[9d83bd0e50f0e1cd]::panicking::begin_panic::<rustc_errors[34f4f8fe0a9126a8]::ExplicitBug>
  10:     0x7f7fb06aa451 - <rustc_errors[34f4f8fe0a9126a8]::diagnostic::BugAbort as rustc_errors[34f4f8fe0a9126a8]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7f7fb0bb8ba8 - <rustc_errors[34f4f8fe0a9126a8]::DiagCtxt>::span_bug::<rustc_span[dae7ad9294c1830]::span_encoding::Span, alloc[c6e8cd8d3db589af]::string::String>
  12:     0x7f7fb0bcdbcd - rustc_middle[1fe6d5e38895052f]::util::bug::opt_span_bug_fmt::<rustc_span[dae7ad9294c1830]::span_encoding::Span>::{closure#0}
  13:     0x7f7fb0bcdd1a - rustc_middle[1fe6d5e38895052f]::ty::context::tls::with_opt::<rustc_middle[1fe6d5e38895052f]::util::bug::opt_span_bug_fmt<rustc_span[dae7ad9294c1830]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7f7fb0bc679b - rustc_middle[1fe6d5e38895052f]::ty::context::tls::with_context_opt::<rustc_middle[1fe6d5e38895052f]::ty::context::tls::with_opt<rustc_middle[1fe6d5e38895052f]::util::bug::opt_span_bug_fmt<rustc_span[dae7ad9294c1830]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7f7fb002e617 - rustc_middle[1fe6d5e38895052f]::util::bug::span_bug_fmt::<rustc_span[dae7ad9294c1830]::span_encoding::Span>
  16:     0x7f7fb1dc0ab0 - rustc_mir_build[fc528618a40f350d]::build::mir_build
  17:     0x7f7fb1db9d0e - rustc_query_impl[1766610d02d5b99c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1766610d02d5b99c]::query_impl::mir_built::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 8usize]>>
  18:     0x7f7fb1cedeae - rustc_query_system[b83bd47e643a06b7]::query::plumbing::try_execute_query::<rustc_query_impl[1766610d02d5b99c]::DynamicConfig<rustc_query_system[b83bd47e643a06b7]::query::caches::VecCache<rustc_span[dae7ad9294c1830]::def_id::LocalDefId, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1766610d02d5b99c]::plumbing::QueryCtxt, false>
  19:     0x7f7fb1ced9cd - rustc_query_impl[1766610d02d5b99c]::query_impl::mir_built::get_query_non_incr::__rust_end_short_backtrace
  20:     0x7f7fb1b50d8e - rustc_mir_transform[7292b1860bcd2ce8]::ffi_unwind_calls::has_ffi_unwind_calls
  21:     0x7f7fb1b50857 - rustc_query_impl[1766610d02d5b99c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1766610d02d5b99c]::query_impl::has_ffi_unwind_calls::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 1usize]>>
  22:     0x7f7fb1daeabf - rustc_query_system[b83bd47e643a06b7]::query::plumbing::try_execute_query::<rustc_query_impl[1766610d02d5b99c]::DynamicConfig<rustc_query_system[b83bd47e643a06b7]::query::caches::VecCache<rustc_span[dae7ad9294c1830]::def_id::LocalDefId, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1766610d02d5b99c]::plumbing::QueryCtxt, false>
  23:     0x7f7fb1dae781 - rustc_query_impl[1766610d02d5b99c]::query_impl::has_ffi_unwind_calls::get_query_non_incr::__rust_end_short_backtrace
  24:     0x7f7faf6d594c - rustc_mir_transform[7292b1860bcd2ce8]::mir_promoted
  25:     0x7f7fb1cd3320 - rustc_query_impl[1766610d02d5b99c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1766610d02d5b99c]::query_impl::mir_promoted::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 16usize]>>
  26:     0x7f7fb1cd35e1 - rustc_query_system[b83bd47e643a06b7]::query::plumbing::try_execute_query::<rustc_query_impl[1766610d02d5b99c]::DynamicConfig<rustc_query_system[b83bd47e643a06b7]::query::caches::VecCache<rustc_span[dae7ad9294c1830]::def_id::LocalDefId, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 16usize]>>, false, false, false>, rustc_query_impl[1766610d02d5b99c]::plumbing::QueryCtxt, false>
  27:     0x7f7fb29abd9e - rustc_query_impl[1766610d02d5b99c]::query_impl::mir_promoted::get_query_non_incr::__rust_end_short_backtrace
  28:     0x7f7fb29abe91 - rustc_query_impl[1766610d02d5b99c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1766610d02d5b99c]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 8usize]>>
  29:     0x7f7fb1cedeae - rustc_query_system[b83bd47e643a06b7]::query::plumbing::try_execute_query::<rustc_query_impl[1766610d02d5b99c]::DynamicConfig<rustc_query_system[b83bd47e643a06b7]::query::caches::VecCache<rustc_span[dae7ad9294c1830]::def_id::LocalDefId, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[1766610d02d5b99c]::plumbing::QueryCtxt, false>
  30:     0x7f7fb1ced90d - rustc_query_impl[1766610d02d5b99c]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  31:     0x7f7fb24bae84 - rustc_interface[ae16de42642863e5]::passes::analysis
  32:     0x7f7fb24ba01b - rustc_query_impl[1766610d02d5b99c]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[1766610d02d5b99c]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 1usize]>>
  33:     0x7f7fb28b7725 - rustc_query_system[b83bd47e643a06b7]::query::plumbing::try_execute_query::<rustc_query_impl[1766610d02d5b99c]::DynamicConfig<rustc_query_system[b83bd47e643a06b7]::query::caches::SingleCache<rustc_middle[1fe6d5e38895052f]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[1766610d02d5b99c]::plumbing::QueryCtxt, false>
  34:     0x7f7fb28b748f - rustc_query_impl[1766610d02d5b99c]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  35:     0x7f7fb2728cdc - rustc_interface[ae16de42642863e5]::interface::run_compiler::<core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>, rustc_driver_impl[c903d310d0b65222]::run_compiler::{closure#0}>::{closure#1}
  36:     0x7f7fb270b4c9 - std[9d83bd0e50f0e1cd]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ae16de42642863e5]::util::run_in_thread_with_globals<rustc_interface[ae16de42642863e5]::util::run_in_thread_pool_with_globals<rustc_interface[ae16de42642863e5]::interface::run_compiler<core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>, rustc_driver_impl[c903d310d0b65222]::run_compiler::{closure#0}>::{closure#1}, core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>>::{closure#0}, core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>>
  37:     0x7f7fb270b272 - <<std[9d83bd0e50f0e1cd]::thread::Builder>::spawn_unchecked_<rustc_interface[ae16de42642863e5]::util::run_in_thread_with_globals<rustc_interface[ae16de42642863e5]::util::run_in_thread_pool_with_globals<rustc_interface[ae16de42642863e5]::interface::run_compiler<core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>, rustc_driver_impl[c903d310d0b65222]::run_compiler::{closure#0}>::{closure#1}, core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>>::{closure#0}, core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[2eaa0139eedd536f]::result::Result<(), rustc_span[dae7ad9294c1830]::ErrorGuaranteed>>::{closure#2} as core[2eaa0139eedd536f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  38:     0x7f7fad4c4bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd6f696d9a5b925df
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/alloc/src/boxed.rs:2063:9
  39:     0x7f7fad4c4bfb - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h94ad61c1e5c5a0cd
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/alloc/src/boxed.rs:2063:9
  40:     0x7f7fad4c4bfb - std::sys::pal::unix::thread::Thread::new::thread_start::h1856dc47c9451b83
                               at /rustc/debd22da66cfa97c74040ebf68e420672ac8560e/library/std/src/sys/pal/unix/thread.rs:108:17
  41:     0x7f7fad3be609 - start_thread
                               at /build/glibc-LcI20x/glibc-2.31/nptl/pthread_create.c:477:8
  42:     0x7f7fad2e1353 - clone
                               at /build/glibc-LcI20x/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  43:                0x0 - <unknown>


rustc version: 1.80.0-nightly (debd22da6 2024-05-29)
platform: x86_64-unknown-linux-gnu

query stack during panic:
#0 [mir_built] building MIR for `test`
#1 [has_ffi_unwind_calls] checking if `test` contains FFI-unwind calls
#2 [mir_promoted] promoting constants in MIR for `test`
#3 [mir_borrowck] borrow-checking `test`
#4 [analysis] running analysis passes on this crate
end of query stack

```

</p>
</details>

**Comment by fmease** [comment] 2024-06-06 19:00
Any uncaught misuses of *internal feature* are considered to be the fault of the user and not a bug in rustc. I'm closing this as works as intended / not planned as per [MCP 620](https://github.com/rust-lang/compiler-team/issues/620).

**Closed by fmease** 2024-06-06 19:00 UTC
Labels: I-ICE, T-compiler, C-bug, needs-triage
