### ISSUE TITLE
SIGILL when statically linking with libc++.a on MacOS

### ISSUE THREAD

**Issue by basvandijk** [rust-lang/rust#64612] opened 2019-09-19 15:37 UTC
I've a Rust project that dynamically links to `libc++` which I'm trying to statically link. Unfortunately building this project on MacOS results in a SIGILL error.

I've simplified the project to the following minimal test case:

https://github.com/basvandijk/sigill-error/

Building it on MacOS results in a: 
```
cargo build
...
(signal: 4, SIGILL: illegal instruction)
```

The crash disappears when I either comment out [`use failure;`](https://github.com/basvandijk/sigill-error/blob/master/src/main.rs#L1) or [`use serde_derive;`](https://github.com/basvandijk/sigill-error/blob/master/src/main.rs#L2). The crash also disappears when I remove the [`-lstatic=c++`](https://github.com/basvandijk/sigill-error/blob/master/.cargo/config#L2) option in `.carg/config`

Note this happens with stable (1.37) and nightly (1.39.0-nightly (eceec57f7 2019-09-18)) rust.

**Comment by madsmtm** [comment] 2024-10-10 07:40
Triage: Tried this today with Rust 1.81.0, and could not reproduce the crash.

**Comment by jieyouxu** [comment] 2024-10-10 09:50
Closing on the basis that we can't repro now, root cause unknown.

**Closed by jieyouxu** 2024-10-10 09:50 UTC
Labels: A-linkage, O-macos, T-compiler, C-bug
