### ISSUE TITLE
Depgraph: ICE with RUST_LOG=debug

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#31859] opened 2016-02-24 11:52 UTC
```
DEBUG:rustc::dep_graph: About to start task CollectItem(DefId { krate: 0, node: DefIndex(2)error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'read/write but no current task; see src/librustc/dep_graph/README.md for more information', src/librustc/dep_graph/thread.rs:151
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Mark-Simulacrum** [comment] 2017-05-06 00:02
Since there are no reproduction instructions, I'm going to go ahead and close this. I suspect that there's likely still a bug here, but I can't get an ICE when testing locally on rustc itself. I still get errors, but I have no real idea why, and this issue isn't the place to track that.

**Closed** 2017-05-06 00:02 UTC
Labels: I-ICE
