### ISSUE TITLE
Borrow checker works wrongly with returned values.

### ISSUE THREAD

**Issue by loyd** [rust-lang/rust#37407] opened 2016-10-25 18:36 UTC
Unfortunately I haven't found an open bug on this subject.

I tried this code:

``` rust
struct A(Vec<u32>);

impl A {
    fn drain(self) -> Vec<u32> {
        let mut nums = self.0;
        nums.drain(..).collect()          // error: `nums` does not live long enough

        // but it works fine:
        // return nums.drain(..).collect();
    }
}
```

[Try it](https://is.gd/RTw5Vs)

**Comment by jonas-schievink** [comment] 2016-10-25 18:55
I think this is #21114

**Comment by TimNN** [comment] 2016-10-25 19:15
Essentially the same issue as #31723, I think.

**Comment by Mark-Simulacrum** [comment] 2017-04-30 19:32
Closing in favor of #21114. Please reopen if that's incorrect, but from what I can tell this is a duplicate of that issue.

**Closed by Mark-Simulacrum** 2017-04-30 19:32 UTC
Labels: A-borrow-checker
