### ISSUE TITLE
ICE - mir/interpret/validity.rs -  nightly v1.45.0

### ISSUE THREAD

**Issue by TomArbuckle** [rust-lang/rust#71786] opened 2020-05-02 07:36 UTC
ICE from mir/interpret/validity.rs compiling v0.5.4 of crate memoffset

I tried compiling the crate memoffset v0.5.4 with the rust release v1.45.0-nightly of 2020-04-30:

I expected to see normal compilation.

Instead, this happened:

Compiling memoffset v0.5.4
     Running `/Users/tom/.cargo/bin/sccache rustc --crate-name build_script_build /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.5.4/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -Cbitcode-in-rlib=no -C codegen-units=8 -C debug-assertions=on --cfg 'feature="default"' -C metadata=114e38b235f2da39 -C extra-filename=-114e38b235f2da39 --out-dir /Users/tom/Documents/GIT/veloren/target/debug/build/memoffset-114e38b235f2da39 -L dependency=/Users/tom/Documents/GIT/veloren/target/debug/deps --extern autocfg=/Users/tom/Documents/GIT/veloren/target/debug/deps/libautocfg-29877b643c723681.rlib --cap-lints allow`
error: internal compiler error: src/librustc_mir/interpret/validity.rs:396: Unexpected error during ptr inbounds test: cannot read from foreign (extern) static DefId(0:34 ~ dispatch[bc51]::ffi[0]::[0]::_dispatch_queue_attr_concurrent[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (7ced01a73 2020-04-30) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 -C panic=abort -C bitcode-in-rlib=no -C codegen-units=8 -C debug-assertions=on --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `dispatch`.

Caused by:
  process didn't exit successfully: `/Users/tom/.cargo/bin/sccache rustc --crate-name dispatch /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/dispatch-0.1.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -Cbitcode-in-rlib=no -C codegen-units=8 -C debug-assertions=on -C metadata=4b5bbb8cce6afd8f -C extra-filename=-4b5bbb8cce6afd8f --out-dir /Users/tom/Documents/GIT/veloren/target/debug/deps -L dependency=/Users/tom/Documents/GIT/veloren/target/debug/deps --cap-lints allow` (exit code: 101)

## Meta

`rustc --version --verbose`:

Backtrace:
rustc +nightly --version --verbose
rustc 1.45.0-nightly (7ced01a73 2020-04-30)
binary: rustc
commit-hash: 7ced01a730e8fc1bae2f8d4369c26812c0484da4
commit-date: 2020-04-30
host: x86_64-apple-darwin
release: 1.45.0-nightly
LLVM version: 9.0

## Full Backtrace

error: internal compiler error: src/librustc_mir/interpret/validity.rs:396: Unexpected error during ptr inbounds test: cannot read from foreign (extern) static DefId(0:34 ~ dispatch[bc51]::ffi[0]::[0]::_dispatch_queue_attr_concurrent[0])

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:907:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: rustc_driver::report_ice
   6: std::panicking::rust_panic_with_hook
   7: std::panicking::begin_panic
   8: rustc_errors::HandlerInner::bug
   9: rustc_errors::Handler::bug
  10: rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}
  11: rustc_middle::ty::context::tls::with_opt::{{closure}}
  12: rustc_middle::ty::context::tls::with_opt
  13: rustc_middle::util::bug::opt_span_bug_fmt
  14: rustc_middle::util::bug::bug_fmt
  15: rustc_mir::interpret::validity::ValidityVisitor<M>::check_safe_pointer
  16: rustc_mir::interpret::validity::ValidityVisitor<M>::try_visit_primitive
  17: rustc_mir::interpret::validity::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::validate_operand_internal
  18: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  19: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  20: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  21: rustc_query_system::query::plumbing::get_query
  22: rustc_mir::const_eval::eval_queries::const_eval_validated_provider
  23: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::const_eval_validated>::compute
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  25: rustc_query_system::query::plumbing::get_query
  26: rustc_middle::mir::interpret::queries::<impl rustc_middle::ty::context::TyCtxt>::const_eval_poly
  27: <rustc_lint::BuiltinCombinedLateLintPass as rustc_lint::passes::LateLintPass>::check_item
  28: rustc_hir::intravisit::Visitor::visit_nested_item
  29: rustc_hir::intravisit::walk_item
  30: rustc_hir::intravisit::Visitor::visit_nested_item
  31: rustc_hir::intravisit::walk_crate
  32: rustc_lint::late::late_lint_crate
  33: rustc_data_structures::sync::join
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  35: rustc_session::utils::<impl rustc_session::session::Session>::time
  36: rustc_interface::passes::analysis
  37: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  38: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
  39: rustc_query_system::query::plumbing::get_query
  40: rustc_middle::ty::context::tls::enter_global
  41: rustc_interface::interface::run_compiler_in_existing_thread_pool
  42: scoped_tls::ScopedKey<T>::set
  43: rustc_ast::attr::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.45.0-nightly (7ced01a73 2020-04-30) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 -C panic=abort -C bitcode-in-rlib=no -C codegen-units=8 -C debug-assertions=on --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [const_eval_validated] const-evaluating + checking `ffi::DISPATCH_QUEUE_CONCURRENT`
#1 [const_eval_validated] const-evaluating + checking `ffi::DISPATCH_QUEUE_CONCURRENT`
#2 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

error: could not compile `dispatch`.

Caused by:
  process didn't exit successfully: `/Users/tom/.cargo/bin/sccache rustc --crate-name dispatch /Users/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/dispatch-0.1.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -Cbitcode-in-rlib=no -C codegen-units=8 -C debug-assertions=on -C metadata=4b5bbb8cce6afd8f -C extra-filename=-4b5bbb8cce6afd8f --out-dir /Users/tom/Documents/GIT/veloren/target/debug/deps -L dependency=/Users/tom/Documents/GIT/veloren/target/debug/deps --cap-lints allow` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by lcnr** [comment] 2020-05-02 07:50
probably caused by #71140 and will be fixed by #71751 :thinking: cc @oli-obk

**Comment by oli-obk** [comment] 2020-05-02 07:52
Yes, this is a duplicate of https://github.com/rust-lang/rust/issues/71612

**Comment by TomArbuckle** [comment] 2020-05-02 07:53
Wow. That was fast. Thanks for looking into this guys. Good luck.

**Closed by oli-obk** 2020-05-02 07:52 UTC
