### ISSUE TITLE
keyring-0.1.1 beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#43671] opened 2017-08-05 13:10 UTC
[keyring](https://crates.io/crates/keyring) version 0.1.1 regressed from stable to beta ([full log](https://cargobomb-reports.s3.amazonaws.com/stable-1.19-beta-1.20.0-beta.1/beta-2017-07-18/reg/keyring-0.1.1/log.txt)):

```
Aug 03 07:41:19.865 INFO kablam! error: type `rand::gmp_randstate_struct` is private
Aug 03 07:41:19.865 INFO kablam!   --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/rust-gmp-0.2.10/src/mpz.rs:90:5
Aug 03 07:41:19.865 INFO kablam!    |
Aug 03 07:41:19.865 INFO kablam! 90 |     fn __gmpz_urandomb(rop: mpz_ptr, state: gmp_randstate_t, n: mp_bitcnt_t);
Aug 03 07:41:19.865 INFO kablam!    |  
```
cc @hwchen

**Comment by petrochenkov** [comment] 2017-08-05 13:26
Caused by old version of `rust-gmp`, see https://github.com/rust-lang/rust/pull/42125#issuecomment-307556502

**Comment by arielb1** [comment] 2017-08-05 14:33
duplicate of #43679.

**Comment by alexcrichton** [comment] 2017-08-05 15:18
Closing in favor of https://github.com/rust-lang/rust/issues/43679

**Closed by alexcrichton** 2017-08-05 15:18 UTC
Labels: regression-from-stable-to-beta, T-compiler
