### ISSUE TITLE
Resolve intra-doc-links on Self for method

### ISSUE THREAD

**Issue by xliiv** [rust-lang/rust#70802] opened 2020-04-05 08:24 UTC
I tried this code:

```rust
#![deny(intra_doc_link_resolution_failure)]


/// [Self::bar]
pub struct Works;

impl Works {
    pub fn bar() {}
}

pub struct Broken;

impl Broken {
    /// [Self::bar]
    pub fn bar() {}
}

```

I expected to see this happen:
Docs for `Broken::bar` is generated correctly by running `cargo +nightly doc` 

Instead, this happened:
I'm getting this error
```
> cargo +nightly doc
 Documenting rust-playground v0.1.0 (/home/xliiv/workspace/rust-playground)
error: `[Self::bar]` cannot be resolved, ignoring it.
  --> src/lib.rs:14:10
   |
14 |     /// [Self::bar]
   |          ^^^^^^^^^ cannot be resolved, ignoring
   |
note: the lint level is defined here
  --> src/lib.rs:1:9
   |
1  | #![deny(intra_doc_link_resolution_failure)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

error: aborting due to previous error

error: Could not document `rust-playground`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rust_playground src/lib.rs -o /home/xliiv/workspace/rust-playground/target/doc --error-format=json --json=diagnostic-rendered-ansi -L dependency=/home/xliiv/workspace/rust-playground/target/debug/deps` (exit code: 1)
```

### Meta

`rustc --version --verbose`:
```
> rustc --version --verbose
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0

```

**Comment by ehuss** [comment] 2020-04-05 14:46
This seems to be a duplicate of #70484 (though this issue contains more useful detail), and is also an unchecked item in the tracking issue #43466.

**Comment by xliiv** [comment] 2020-04-06 15:46
If anyone could help me start with it, I'd be happy to resolve it.
Since I have no idea where to start I'm going to follow these clues
* this file: https://github.com/rust-lang/rust/blob/bd18bc9a4c142100a7230e1fd1cfe6be08214693/src/test/rustdoc/intra-link-self.rs
* some history merge request related to intra-doc-links or [RFC 1946](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md)

**Comment by xliiv** [comment] 2020-05-13 11:01
Block by (or at least related to) https://github.com/rust-lang/rust/issues/54172

**Closed** 2020-05-23 10:46 UTC
Labels: A-intra-doc-links, C-bug, T-rustdoc
