### ISSUE TITLE
rustdoc macro rendering is totally borked

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#25955] opened 2015-06-02 04:06 UTC
See e.g. https://doc.rust-lang.org/nightly/std/macro.vec!.html

**Comment by alexcrichton** [comment] 2015-06-02 04:17
Dupe of https://github.com/rust-lang/rust/issues/20923 (macros are encoded across crates in.. interesting fashions)

**Closed by alexcrichton** 2015-06-02 04:17 UTC
Labels: A-rustdoc
