### ISSUE TITLE
Please use PROC_THREAD_ATTRIBUTE_HANDLE_LIST in std::process::Command on Windows Vista and later

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/rust#73281] opened 2020-06-12 12:55 UTC
On Windows Vista and later, `PROC_THREAD_ATTRIBUTE_HANDLE_LIST` can be used to programmatically control which handles are inherited, and the mutex [here](https://github.com/rust-lang/rust/blob/59493917be3e87e1dfb44a9ccb66a9f9b17228e6/src/libstd/sys/windows/process.rs#L186) can be removed.
An example from Chromium: https://github.com/chromium/chromium/blob/2175a6f74e264dd7d540e5c59e73a9460a716727/base/process/launch_win.cc#L233.
There is a blog about it: https://devblogs.microsoft.com/oldnewthing/20111216-00/?p=8873.

**Comment by retep998** [comment] 2020-06-13 04:24
Duplicate of https://github.com/rust-lang/rust/issues/38227 but yes we should absolutely do this.

**Closed by retep998** 2020-06-13 04:24 UTC
Labels: C-enhancement, O-windows, libs-impl

**Comment by hyd-dev** [comment] 2020-06-13 07:27
Sorry for duplicating it. However, the origin issue seems to be inactive.
