### ISSUE TITLE
#[cfg (feature = "XXX ")] doesn't work     in #[test]method   for        mac os. but windows system is success.

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#74903] opened 2020-07-29 09:48 UTC
```rust
#[cfg(all(feature = "runtime-tokio", feature = "runtime-async-std"))]
compile_error!("only one of 'runtime-async-std' or 'runtime-tokio' features must be enabled");
```

fn main() {} run success(windows system)

#[test]
#[cfg (feature = "XXX ")]
 fn test() {}     run success(windows system)

 fn main() {} run success(mac os  system)

#[test]
#[cfg (feature = "XXX ")]
 fn test() {}     run fail (mac os system)
```rust
error: only one of 'runtime-async-std' or 'runtime-tokio' features must be enabled
```

**Comment by jonas-schievink** [comment] 2020-07-29 10:30
Duplicate of https://github.com/rust-lang/rust/issues/74901 – please provide detailed instructions to reproduce the issue there.

**Closed by jonas-schievink** 2020-07-29 10:30 UTC
Labels: C-bug
