### ISSUE TITLE
[test] Output of subprocesses is lost when not using RUST_TEST_NOCAPTURE=1

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#42814] opened 2017-06-21 23:55 UTC
With the following example:
```rust
extern crate libc;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        match unsafe { libc::fork() } {
            0 => {
                println!("Some stdout");
                unsafe { libc::exit(0) };
            },
            child => {
                let mut status = 0;
                unsafe { libc::waitpid(child, &mut status, 0) };
                println!("Child exited with exit code {}", status);
                panic!("Trigger a failure so that captured output is displayed");
            },
        }
    }
}
```

Running with `cargo test` doesn't show the `Some stdout` text, while running with `RUST_TEST_NOCAPTURE=1 cargo test` outputs it. Thus some output is lost when not running in `RUST_TEST_NOCAPTURE=1` mode, which makes some complex tests less convenient to debug.

**Comment by alexcrichton** [comment] 2017-06-25 18:36
I believe this is a dupe of https://github.com/rust-lang/rust/issues/12309, but thanks for the report!

**Closed by alexcrichton** 2017-06-25 18:36 UTC
Labels: A-libtest, T-libs

**Comment by Ekleog** [comment] 2017-06-25 18:45
Oh indeed it's a subset of this other bug (which I didn't manage to find, likely because the example uses no-longer-existent std::task, I guess).

Sorry for the noise and thanks!
