### ISSUE TITLE
still os error 122 on the memory file system z:\ when compiling with cargo

### ISSUE THREAD

**Issue by jeppeter** [rust-lang/rust#65374] opened 2019-10-13 13:23 UTC
i found a bug on the cargo .the code in windows 7 x64 platform with rust-1.37.0-msvc

main.rs 
########main.rs fle start
use regex::Regex;

fn main() {
    let re = Regex::new(r"(?x)
(?P<year>\d{4})
-
(?P<month>\d{2})
-
(?P<day>\d{2})
").unwrap();
    let caps = re.captures("2010-03-14").unwrap();

    assert_eq!("2010", &caps["year"]);
    assert_eq!("03", &caps["month"]);
    assert_eq!("14", &caps["day"]);
}
########main.rs file end

Cargo.toml
########Cargo.toml file start

[package]
name = "regtest"
version = "0.1.0"
authors = ["jeppeter"]
edition = "2018"

[dependencies]
regex = "1"
########Cargo.toml file end

when i set environment CARGO_INCREMENTAL=0
and i use command line

**cargo build --release --verbose**

i got the output 

########output file start
       Fresh lazy_static v1.4.0
       Fresh regex-syntax v0.6.12
   Compiling memchr v2.2.1
   Compiling thread_local v0.3.6
     Running `Z:\rustlib\test\regtest\target\release\build\memchr-633c9e703931685a\build-script-build`
     Running `rustc --crate-name thread_local C:\Users\wrc\.cargo\registry\src\github.com-1ecc6299db9ec823\thread_local-0.3.6\src\lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=e4025c17eeddf6c1 -C extra-filename=-e4025c17eeddf6c1 --out-dir Z:\rustlib\test\regtest\target\release\deps -L dependency=Z:\rustlib\test\regtest\target\release\deps --extern lazy_static=Z:\rustlib\test\regtest\target\release\deps\liblazy_static-4ea98a74b899f1a8.rlib --cap-lints allow`
     Running `rustc --crate-name memchr C:\Users\wrc\.cargo\registry\src\github.com-1ecc6299db9ec823\memchr-2.2.1\src\lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg "feature=\"default\"" --cfg "feature=\"use_std\"" -C metadata=79b0e42c9f2166f1 -C extra-filename=-79b0e42c9f2166f1 --out-dir Z:\rustlib\test\regtest\target\release\deps -L dependency=Z:\rustlib\test\regtest\target\release\deps --cap-lints allow --cfg memchr_runtime_simd --cfg memchr_runtime_sse2 --cfg memchr_runtime_sse42 --cfg memchr_runtime_avx`
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 122, kind: Other, message: "ERROR_INSUFFICIENT_BUFFER" }', src\libcore\result.rs:999:5
stack backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: <(rustc::hir::def_id::DefId, rustc::hir::def_id::DefId) as rustc::ty::query::keys::Key>::default_span
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: <(rustc::hir::def_id::CrateNum, rustc::hir::def_id::DefId) as rustc_metadata::cstore_impl::IntoArgs>::into_args
   9: rustc_metadata::locator::Context::report_errs
  10: rustc_metadata::locator::Context::maybe_load_library_crate
  11: rustc_metadata::creader::CrateLoader::new
  12: rustc_metadata::creader::CrateLoader::new
  13: rustc_metadata::creader::CrateLoader::process_extern_crate
  14: ZN13rustc_resolve19build_reduced_graph197_$LT$impl$u20$rustc_resolve..ToNameBinding$u20$for$u20$$LP$$RF$rustc_resolve..ModuleData$C$$u20$rustc..ty..Visibility$C$$u20$syntax_pos..span_encoding..Span$C$$u20$syntax_pos..hygiene..Mark$RP$$GT$15to_name_binding
  15: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as syntax::visit::Visitor>::visit_item
  16: <rustc_resolve::macros::<impl rustc_resolve::Resolver>::early_resolve_ident_in_lexical_scope::Flags as core::fmt::UpperHex>::fmt
  17: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as syntax::visit::Visitor>::visit_item
  18: <rustc_resolve::CrateLint as core::fmt::Debug>::fmt
  19: rustc_resolve::macros::<impl syntax::ext::base::Resolver for rustc_resolve::Resolver>::visit_ast_fragment_with_placeholders
  20: syntax::ext::expand::MacroExpander::expand_crate
  21: syntax::ext::expand::MacroExpander::expand_crate
  22: syntax::ext::expand::MacroExpander::expand_crate
  23: <rustc_interface::profile::trace::Query as core::fmt::Debug>::fmt
  24: <rustc_interface::profile::trace::Query as core::fmt::Debug>::fmt
  25: rustc_interface::passes::BoxedResolver::to_expansion_result
  26: <rustc_interface::util::ReplaceBodyWithLoop as syntax::mut_visit::MutVisitor>::visit_mac
  27: <rustc_interface::util::ReplaceBodyWithLoop as syntax::mut_visit::MutVisitor>::visit_mac
  28: <rustc_interface::proc_macro_decls::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor>::visit_trait_item
  29: <rustc_interface::proc_macro_decls::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor>::visit_trait_item
  30: <rustc_interface::proc_macro_decls::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor>::visit_trait_item
  31: <rustc_interface::proc_macro_decls::Finder as rustc::hir::itemlikevisit::ItemLikeVisitor>::visit_trait_item
  32: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::prepare_outputs
  33: rustc_driver::set_sigpipe_handler
  34: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  35: <env_logger::filter::inner::Filter as core::fmt::Display>::fmt
  36: <rustc_driver::Compilation as core::fmt::Debug>::fmt
  37: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  38: _rust_maybe_catch_panic
  39: rustc_driver::set_sigpipe_handler
  40: ZN244_$LT$std..error..$LT$impl$u20$core..convert..From$LT$alloc..string..String$GT$$u20$for$u20$alloc..boxed..Box$LT$dyn$u20$std..error..Error$u2b$core..marker..Send$u2b$core..marker..Sync$GT$$GT$..from..StringError$u20$as$u20$core..fmt..Display$GT$3fmt17
  41: std::sys::windows::thread::Thread::new
  42: BaseThreadInitThunk
  43: RtlUserThreadStart
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0 (eae3437df 2019-08-13) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `thread_local`.

Caused by:
  process didn't exit successfully: `rustc --crate-name thread_local C:\Users\wrc\.cargo\registry\src\github.com-1ecc6299db9ec823\thread_local-0.3.6\src\lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C metadata=e4025c17eeddf6c1 -C extra-filename=-e4025c17eeddf6c1 --out-dir Z:\rustlib\test\regtest\target\release\deps -L dependency=Z:\rustlib\test\regtest\target\release\deps --extern lazy_static=Z:\rustlib\test\regtest\target\release\deps\liblazy_static-4ea98a74b899f1a8.rlib --cap-lints allow` (exit code: 101)
warning: build failed, waiting for other jobs to finish...
error: build failed
########output file end

i have mention the bug on #65325 
and it will solved in the simple hello world program ,
but ,i found it not solved in the some complicated situation

i make sure the memory file system disk is 8G size ,so it has enough disk size to contain the temporary file
i make also sure that the code can be compile ok on the normal disk system, i compile it ok.

**Comment by jonas-schievink** [comment] 2019-10-13 13:38
Please use code fences so the issue is easier to read.

Based on the error message, this does not look like a duplicate of https://github.com/rust-lang/rust/issues/52377.

The compiler doesn't work very well on ramdisks and network shares on Windows, so to work around this bug you can develop on your local file system instead.

**Comment by jonas-schievink** [comment] 2019-10-13 13:40
Ah, nevermind, it is a duplicate of https://github.com/rust-lang/rust/issues/52377. Please don't open duplicate intentionally, there's no value in having multiple issues for the same bug.

**Closed by jonas-schievink** 2019-10-13 13:40 UTC
Labels: A-metadata, C-bug, T-compiler
