### ISSUE TITLE
`println!(123)` works, but `print!(123)` and `format!(123)` do not

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#31556] opened 2016-02-11 02:33 UTC
`println!` uses `concat!($fmt, "\n")` internally, which for literals converts `$fmt` into a string before concatenating. Because of this, `println!(123)` is accepted.

That said, rather than make `println!` as strict as `print!` and `format!`, it would be nice if `format_args!(foo)` could become shorthand for `format_args!("{}", foo)`, somewhat similar to what `panic!` does.

**Comment by durka** [comment] 2016-02-11 03:21
relevant #30143

**Comment by niconii** [comment] 2016-02-11 03:39
Oh, whoops, is this a dupe, then? That seems more about making a breaking change to `println!` (and `writeln!`), whereas I'd personally like `format_args!` to be _more_ permissive.

**Comment by durka** [comment] 2016-02-11 03:43
I guess it's a duplicate, but the opinion in the other issue seemed to be that strictifying would be better than loosening. Loosening wouldn't be a breaking change, though. I guess an RFC would be required.

**Comment by alexcrichton** [comment] 2016-02-11 04:18
Ah yeah I think this is a dupe of https://github.com/rust-lang/rust/issues/30143 so I'm going to close in favor of that (which was previously decided as a whelp-this-would-be-nice-to-fix-but-2.0 kind of thing)

**Closed by alexcrichton** 2016-02-11 04:18 UTC
