### ISSUE TITLE
Compiler panic on a macro invocation combined with invalid pub declaration

### ISSUE THREAD

**Issue by xl483** [rust-lang/rust#63223] opened 2019-08-02 17:47 UTC
The compiler panics when compiling the following code. I had been expecting to see syntax errors instead. Deleting either line causes the compiler not to panic and give expected error messages.

```rust
const FOO: &str = b!("foo");
 
pub struct Bar { pub(in ::a) x: u64 }

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c43d1f37cad49bb52a9ab01461792b11))

**Comment by Centril** [comment] 2019-08-02 21:31
Reduced:
```rust
foo!();

pub(in ::bar) struct Baz {}
```

cc @petrochenkov

**Comment by petrochenkov** [comment] 2019-08-02 21:49
Nice.
This is not even a regression, it requires `--edition 2018` and happens since 1.30 when the edition was stabilized.

**Comment by petrochenkov** [comment] 2019-08-09 11:16
Fixed in https://github.com/rust-lang/rust/pull/63400 (as a side effect of making `resolve_visibility` to use early resolution methods).

**Closed** 2019-08-10 17:19 UTC
Labels: A-macros, A-resolve, C-bug, I-ICE, T-compiler
