### ISSUE TITLE
Iterating through an unbounded range causes a panic

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#69066] opened 2020-02-11 17:34 UTC
I tried this code:

```rust
fn main() {
    for i in 2147483646.. {
        println!("{}", i);
    }
}
```

I expected to see this happen: The numbers `2147483646` and `2147483647` should be printed, then the program should exit.

Instead, this happened: The standard library panicked.

Note that it might make sense to panic on overflow instead, but at least 2147483647 should printed first, since it's within the range of `i32`.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d35d912c1c6abc015b06e2004ae55de7)

### Meta

Version: stable (1.41.0), but panic also occurs on nightly (1.43.0-nightly (2020-02-10 e6ec0d125eba4074122b))

<details><summary>Backtrace</summary>
<p>

```
... snip ...
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: <i32 as core::ops::arith::Add>::add
             at /rustc/e6ec0d125eba4074122b187032474b4174fb9d31/src/libcore/ops/arith.rs:94
  15: <i32 as core::iter::range::Step>::add_one
             at /rustc/e6ec0d125eba4074122b187032474b4174fb9d31/src/libcore/iter/range.rs:67
  16: core::iter::range::<impl core::iter::traits::iterator::Iterator for core::ops::range::RangeFrom<A>>::next
             at /rustc/e6ec0d125eba4074122b187032474b4174fb9d31/src/libcore/iter/range.rs:314
  17: playground::main
             at src/main.rs:2
... snip ...
```

</p>
</details>

**Comment by jyn514** [comment] 2020-02-11 17:41
Note that the following code works as expected:

```rust
    for i in 2147483646..=2147483647 {
        println!("{}", i);
    }
```

**Comment by timvermeulen** [comment] 2020-02-12 05:24
The `RangeFrom` docs specify that it will currently panic in debug mode, and that this behavior is subject to change.

I'm not sure how intentional it is that the last value is left out, but given that `RangeFrom` only has a `start` field, it can't currently represent the state of just having returned the maximum value from `next`.

**Comment by ollie27** [comment] 2020-02-12 18:49
Duplicate of #25708

**Closed by ollie27** 2020-02-12 18:49 UTC
Labels: C-bug
