### ISSUE TITLE
Rust Language Server crushes on start-up.

### ISSUE THREAD

**Issue by sisshiki1969** [rust-lang/rust#69951] opened 2020-03-12 16:51 UTC
RLS crushes on every VSCode start-up, after version-up of rustc to 1.43.0-nightly(2020-03-11).
The compiler says "cannot lex `source_file` without source: `.../.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.6/src/x86_64/mod.rs`", but this file exists in the folder.
The whole message output is as follows:
```
{"message":"cannot lex `source_file` without source: /Users/monochrome/.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.6/src/x86_64/mod.rs","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror: internal compiler error\u001b[0m\u001b[0m\u001b[1m: cannot lex `source_file` without source: /Users/monochrome/.cargo/registry/src/github.com-1ecc6299db9ec823/ppv-lite86-0.2.6/src/x86_64/mod.rs\u001b[0m\n\n"}
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:880:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (c20d7eecb 2020-03-11) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```
Thanks!

**Comment by jonas-schievink** [comment] 2020-03-12 17:02
Duplicate of https://github.com/rust-lang/rust/issues/69933

**Closed by jonas-schievink** 2020-03-12 17:02 UTC
