### ISSUE TITLE
Implicit return leads to "does not live long enough" error.

### ISSUE THREAD

**Issue by Gyscos** [rust-lang/rust#31439] opened 2016-02-06 01:06 UTC
Here is a simple function that tries to read all lines from input:
```rust
use std::io::{self,BufRead};

fn lines() -> Vec<String> {
    let stdin = io::stdin();
    let handle = stdin.lock();

    handle.lines().map(|line| line.unwrap()).collect()
}

fn main() {
}
```

As shown [here](http://is.gd/sgKoft), attempting to compile it (on stable 1.6, beta or nightly) gives a lifetime error:

```
<anon>:5:18: 5:23 error: `stdin` does not live long enough
<anon>:5     let handle = stdin.lock();
                          ^~~~~
<anon>:3:27: 8:2 note: reference must be valid for the destruction scope surrounding block at 3:26...
<anon>:3 fn lines() -> Vec<String> {
<anon>:4     let stdin = io::stdin();
<anon>:5     let handle = stdin.lock();
<anon>:6 
<anon>:7     handle.lines().map(|line| line.unwrap()).collect()
<anon>:8 }
<anon>:4:29: 8:2 note: ...but borrowed value is only valid for the block suffix following statement 0 at 4:28
<anon>:4     let stdin = io::stdin();
<anon>:5     let handle = stdin.lock();
<anon>:6 
<anon>:7     handle.lines().map(|line| line.unwrap()).collect()
<anon>:8 }
```

Making the return explicit fixes this:

```rust
use std::io::{self,BufRead};

fn lines() -> Vec<String> {
    let stdin = io::stdin();
    let handle = stdin.lock();

    return handle.lines().map(|line| line.unwrap()).collect();
}

fn main() {
}
```

Is this the expected behavior? I would have thought explicit and implicit returns would give the same result...

**Comment by steveklabnik** [comment] 2016-02-08 19:00
This does seem like a bug. I can't quite remember, but I _think_ there is a similar issue somewhere...

**Comment by arielb1** [comment] 2016-02-17 10:08
This looks like a destruction order problem to me.

**Comment by Thiez** [comment] 2016-02-18 09:52
Assigning the result to a local and then implicitly returning that local also solves this problem:

```rust
fn lines() -> Vec<String> {
    let stdin = io::stdin();
    let handle = stdin.lock();

    let result = handle.lines().map(|line| line.unwrap()).collect();
    result
}
```

Perhaps rustc sometimes incorrectly requires too many lifetimes in an implicit return expression to be valid until the end of the function, instead of looking only at the lifetimes mentioned in the result of the expression?

**Comment by Thiez** [comment] 2016-02-18 10:09
Here, a minimal example:

```rust
struct S{ n: u8 }
struct T<'a>{ s: &'a S }
impl<'a> Drop for T<'a> { fn drop(&mut self){} }

fn test_good() -> u8 { // this is fine
    let s = S{ n: 5 };
    return T{ s: &s}.s.n;
}

fn test_bad() -> u8 { // this is not
    let s = S{ n: 5 };
    T{ s: &s}.s.n
}

fn main(){}
```

**Comment by Ryman** [comment] 2016-05-09 03:24
Seems related to #22252

**Comment by arielb1** [comment] 2016-05-24 21:35
This looks like a duplicate of #33490 - on MIR it would be a segfault.

**Closed** 2016-05-24 21:36 UTC
Labels: A-lang, A-lifetimes
