### ISSUE TITLE
[Bug] "Could not compile `[...]`" without giving any error (not an ICE)

### ISSUE THREAD

**Issue by Ticki** [rust-lang/rust#30258] opened 2015-12-07 15:16 UTC
I'm unable to make a small reproduction of this bug. However, the code causing this problem can be found here: https://github.com/Ticki/b

Note that the above repo is only intended for debugging the new memory manager for Redox, hence it's a very ugly and bad code (since it's not intended for actual use).

Nevertheless, it outputs a bunch of warnings, but no errors.

Note that it's (since it's low-level code) using a lot of `unsafe`s, and I believe the bug is related to that.

I've tried the following:

1. Compile the code on another computer.
2. Use rustc directly.
3. Use release mode
4. Updating rust
5. Disabling all optimizations.
6. Not doing the LLVM codegen

But all of these fails.

It does not even produce an ICE, but just aborts with no reason given.

```rust
[...]
memory.rs:562     let mut ret = 1024 * 1024;
                      ^~~~~~~
memory.rs:563:5: 568:6 warning: unnecessary `unsafe` block, #[warn(unused_unsafe)] on by default
memory.rs:563     unsafe {
memory.rs:564         // Memory allocation must be atomic
memory.rs:565         // TODO
memory.rs:566 
memory.rs:567         // Memory allocation must be atomic
memory.rs:568     }
main.rs:14:17: 14:18 warning: unused variable: `b`, #[warn(unused_variables)] on by default
main.rs:14             let b = memory::alloc(i);
                           ^
Could not compile `b`.
```

**Comment by sanxiyn** [comment] 2015-12-08 07:57
`pub static mut MEMORY: [u8; 14082495496] = [0; 14082495496];` in memory.rs is enough to reproduce the issue. Closing as a duplicate of #23600.

**Closed by sanxiyn** 2015-12-08 07:57 UTC

**Comment by Ticki** [comment] 2015-12-08 21:07
Yeah, I figured that out. Thanks.
