### ISSUE TITLE
Undefined Behavior in safe code that unwinds out of `extern "C"` function

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#63943] opened 2019-08-27 08:24 UTC
**UPDATE**: this optimization is perfectly correct. It only breaks code that already has undefined behavior. This is however an issue since until #52652 is fixed we want to keep such code working.

**ORIGINAL TITLE**:  mis-compilation of noreturn extern "C" definitions that unwind on stable and nightly 

---

Originally reported here: https://github.com/rust-lang/rust/pull/63909#issuecomment-524905295 , which might contain a fix, but that has not been verified yet. 

The default behavior of the Rust language on nightly Rust was to abort when a panic tries to escape from functions using certain ABIs intended for FFI, like `"C"`. #62603 changed this behavior on nightly Rust to match the stable Rust behavior, which let the function unwind, while still applying the `nounwind` attribute to these functions. When these functions return `Never`, they are also `noreturn`, and this results in mis-compilations on stable and nightly Rust. MWE:  

```rust
extern "C" fn bar() -> ! { panic!("nounwind noreturn fn unwinds") }
extern "C" fn baz() -> i32 {
    if let Ok(_) = std::panic::catch_unwind(|| bar() ) {
        unsafe { std::hint::unreachable_unchecked() }  // makes IR nicer
    }
    42
}
fn main() { std::process::exit((baz() != 42) as i32); }
```

`cargo run --release` returns success, but `RUSTFLAGS="-C lto=fat" cargo run --release` returns failure.

_I think_ that since https://github.com/rust-lang/rust/pull/63909 removes the `nounwind` attribute, it should end up fixing this bug, but we should probably add a test for this somewhere.

---

The problem #62603 intended to solve is to allow Rust->C->Rust FFI where a Rust callback called from C can unwind through C back into Rust. This example can be adapted to this application, where the miscompilation persists:

```cpp
// foo.cpp
using fn_type = void(*)();
[[ noreturn ]] extern "C" void foo(fn_type x);
[[ noreturn ]] extern "C" void foo(fn_type x)  { x(); /* unreachable: */ throw 0; }
```

```rust
// main.rs
extern "C" { fn foo(x: extern "C" fn() -> !) -> !; }
extern "C" fn bar() -> ! { panic!("nounwind noreturn fn unwinds") }
extern "C" fn baz() -> i32 {
    if let Ok(_) = std::panic::catch_unwind(|| unsafe { foo(bar) }) {
        unsafe { std::hint::unreachable_unchecked() }
    }
    42
}
fn main() {
   std::process::exit((baz() != 42) as i32);
}
```

AFAICT this miscompilation has always existed for Rust->C-Rust FFI.

**Comment by nikomatsakis** [comment] 2019-08-29 13:48
Check-in from the @rust-lang/compiler meeting: I'm changing the nomination to nominate this issue for @rust-lang/lang. In particular, @joshtriplett, it'd be great if you can catch up on the comments here and in #63909 and give some kind of summary, since you've been spearheading this work.

**Comment by joshtriplett** [comment] 2019-09-05 18:57
I'm not sure why this was filed in addition to #63909; I think #63909 completely addresses this, assuming we either merge it or stabilize `#[unwind]` before the next beta. I'm going to close this issue as a duplicate of #63909. If you feel there's a distinct issue here that #63909 wouldn't address, please clarify that and we can always reopen it.

**Comment by gnzlbg** [comment] 2019-09-06 12:50
This issue was filled because #62603 re-introduced this soundness bug into nightly. Is this a duplicate of some other issue? #63909 is a PR.

**Comment by RalfJung** [comment] 2019-09-09 09:57
I agree with @gnzlbg, the existence of an unmerged PR does not usually suffice to close issues.

**Comment by joshtriplett** [comment] 2019-09-09 19:22
@RalfJung I tend to treat PRs and issues as synonymous (a PR is just an issue with commits attached) and thus potentially redundant, but your call.

**Comment by RalfJung** [comment] 2021-03-11 08:10
Can this be closed due to https://github.com/rust-lang/rust/pull/76570? Cc @cratelyn

**Comment by cratelyn** [comment] 2021-03-11 18:53
Yes, that sounds correct to me @RalfJung!

**Comment by RalfJung** [comment] 2021-03-11 19:49
Awesome, I love closing soundness issues. :)

**Closed by RalfJung** 2021-03-11 19:49 UTC
Labels: A-ffi, C-bug, I-unsound 💥, T-lang
