### ISSUE TITLE
bindeps compiler bug

### ISSUE THREAD

**Issue by aviramha** [rust-lang/rust#96739] opened 2022-05-05 16:44 UTC
### Code

```Rust
fn main() {
    let file = File::create(temp_dir.as_path().join("lolz")).unwrap();
    file.write(include_bytes!(env!("CARGO_CDYLIB_MIRRORD_LAYER")));
}
```

### Meta
`rustc --version --verbose`:
```
rustc 1.62.0-nightly (69a5d2481 2022-04-27)
binary: rustc
commit-hash: 69a5d2481e856a5a18885390b8cf6950b9ff8dd3
commit-date: 2022-04-27
host: aarch64-apple-darwin
release: 1.62.0-nightly
LLVM version: 14.0.1
```

### Error output

```
error: environment variable `CARGO_CDYLIB_FILE_MIRRORD_LAYER` not defined
  --> mirrord-cli/src/main.rs:34:31
   |
34 |     file.write(include_bytes!(env!("CARGO_CDYLIB_FILE_MIRRORD_LAYER")));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'DefId::expect_local: `DefId(1:2441 ~ std[288a]::env::temp_dir)` isn't local', /rustc/69a5d2481e856a5a18885390b8cf6950b9ff8dd3/compiler/rustc_span/src/def_id.rs:283:43
stack backtrace:
   0:        0x1010c7e30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5766446765602b2f
   1:        0x101119730 - core::fmt::write::h1454cf4bd27645af
   2:        0x1010bae88 - std::io::Write::write_fmt::h6d4bd601dc063fa4
   3:        0x1010cab30 - std::panicking::default_hook::{{closure}}::he3278aaa6dd4ffe3
   4:        0x1010ca80c - std::panicking::default_hook::h83712f1c80d5cc94
   5:        0x1083d359c - rustc_driver[ab005e2210e4776d]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:        0x1010cb20c - std::panicking::rust_panic_with_hook::hb3ff747d28bd5b62
   7:        0x1010cb064 - std::panicking::begin_panic_handler::{{closure}}::h0855075d03830cc5
   8:        0x1010c830c - std::sys_common::backtrace::__rust_end_short_backtrace::hce44ea057571d05d
   9:        0x1010cadbc - _rust_begin_unwind
  10:        0x101147c28 - core::panicking::panic_fmt::hdc2fb6dcaa6cdad6
  11:        0x10a7f1ce4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::report_method_error
  12:        0x10a80d4b8 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_kind
  13:        0x10a7d18c4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  14:        0x10a80d3d4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_kind
  15:        0x10a7d18c4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  16:        0x10a7e3bfc - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_argument_types::{closure#0}
  17:        0x10a7de154 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_argument_types
  18:        0x10a7c1cc8 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  19:        0x10a7bfaa0 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_call
  20:        0x10a80d8f0 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_kind
  21:        0x10a7d18c4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  22:        0x10a80d3d4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_kind
  23:        0x10a7d18c4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  24:        0x10a7e4864 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_decl_initializer
  25:        0x10a7e496c - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_decl
  26:        0x10a7e4b30 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_stmt
  27:        0x10a7e5314 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  28:        0x10a80dae8 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_kind
  29:        0x10a7d18c4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  30:        0x10a7d21f4 - <rustc_typeck[2f58a6a90e714c00]::check::fn_ctxt::FnCtxt>::check_return_expr
  31:        0x10a84db14 - rustc_typeck[2f58a6a90e714c00]::check::check::check_fn
  32:        0x10a8eac94 - <rustc_infer[a88a0486846388cc]::infer::InferCtxtBuilder>::enter::<&rustc_middle[5d8aa501df07cd8a]::ty::context::TypeckResults, <rustc_typeck[2f58a6a90e714c00]::check::inherited::InheritedBuilder>::enter<rustc_typeck[2f58a6a90e714c00]::check::typeck_with_fallback<rustc_typeck[2f58a6a90e714c00]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[5d8aa501df07cd8a]::ty::context::TypeckResults>::{closure#0}>
  33:        0x10a87d3a8 - rustc_typeck[2f58a6a90e714c00]::check::typeck
  34:        0x10b36b188 - <rustc_query_system[c392b6a7d21fca56]::dep_graph::graph::DepGraph<rustc_middle[5d8aa501df07cd8a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[5d8aa501df07cd8a]::ty::context::TyCtxt, rustc_span[cfdc8e2acaf4a144]::def_id::LocalDefId, &rustc_middle[5d8aa501df07cd8a]::ty::context::TypeckResults>
  35:        0x10b16fd34 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::try_execute_query::<rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt, rustc_query_system[c392b6a7d21fca56]::query::caches::DefaultCache<rustc_span[cfdc8e2acaf4a144]::def_id::LocalDefId, &rustc_middle[5d8aa501df07cd8a]::ty::context::TypeckResults>>
  36:        0x10b23df34 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::get_query::<rustc_query_impl[8e3d7c3e64684d85]::queries::typeck, rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt>
  37:        0x10a87d5c0 - rustc_typeck[2f58a6a90e714c00]::check::typeck
  38:        0x10b36b188 - <rustc_query_system[c392b6a7d21fca56]::dep_graph::graph::DepGraph<rustc_middle[5d8aa501df07cd8a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[5d8aa501df07cd8a]::ty::context::TyCtxt, rustc_span[cfdc8e2acaf4a144]::def_id::LocalDefId, &rustc_middle[5d8aa501df07cd8a]::ty::context::TypeckResults>
  39:        0x10b16fd34 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::try_execute_query::<rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt, rustc_query_system[c392b6a7d21fca56]::query::caches::DefaultCache<rustc_span[cfdc8e2acaf4a144]::def_id::LocalDefId, &rustc_middle[5d8aa501df07cd8a]::ty::context::TypeckResults>>
  40:        0x10b23df34 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::get_query::<rustc_query_impl[8e3d7c3e64684d85]::queries::typeck, rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt>
  41:        0x10a9bd2c0 - <rustc_middle[5d8aa501df07cd8a]::hir::map::Map>::par_body_owners::<rustc_typeck[2f58a6a90e714c00]::check::typeck_item_bodies::{closure#0}>
  42:        0x10a88148c - rustc_typeck[2f58a6a90e714c00]::check::typeck_item_bodies
  43:        0x10b3929a8 - <rustc_query_system[c392b6a7d21fca56]::dep_graph::graph::DepGraph<rustc_middle[5d8aa501df07cd8a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[5d8aa501df07cd8a]::ty::context::TyCtxt, (), ()>
  44:        0x10b1b0400 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::try_execute_query::<rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt, rustc_query_system[c392b6a7d21fca56]::query::caches::DefaultCache<(), ()>>
  45:        0x10b210b74 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::get_query::<rustc_query_impl[8e3d7c3e64684d85]::queries::typeck_item_bodies, rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt>
  46:        0x10a8c2398 - <rustc_session[cb45daf2430bcebe]::session::Session>::time::<(), rustc_typeck[2f58a6a90e714c00]::check_crate::{closure#7}>
  47:        0x10a8a2424 - rustc_typeck[2f58a6a90e714c00]::check_crate
  48:        0x1084924b4 - rustc_interface[1aaaf20b10225d55]::passes::analysis
  49:        0x10b38a180 - <rustc_query_system[c392b6a7d21fca56]::dep_graph::graph::DepGraph<rustc_middle[5d8aa501df07cd8a]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[5d8aa501df07cd8a]::ty::context::TyCtxt, (), core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>
  50:        0x10b1a5f98 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::try_execute_query::<rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt, rustc_query_system[c392b6a7d21fca56]::query::caches::DefaultCache<(), core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>>
  51:        0x10b23e388 - rustc_query_system[c392b6a7d21fca56]::query::plumbing::get_query::<rustc_query_impl[8e3d7c3e64684d85]::queries::analysis, rustc_query_impl[8e3d7c3e64684d85]::plumbing::QueryCtxt>
  52:        0x108398b04 - <rustc_interface[1aaaf20b10225d55]::passes::QueryContext>::enter::<rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>
  53:        0x10838014c - <rustc_interface[1aaaf20b10225d55]::interface::Compiler>::enter::<rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}::{closure#2}, core[30328a0cdeb81e9a]::result::Result<core[30328a0cdeb81e9a]::option::Option<rustc_interface[1aaaf20b10225d55]::queries::Linker>, rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>
  54:        0x1083d8464 - rustc_span[cfdc8e2acaf4a144]::with_source_map::<core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>, rustc_interface[1aaaf20b10225d55]::interface::create_compiler_and_run<core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>, rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}>::{closure#1}>
  55:        0x108380720 - rustc_interface[1aaaf20b10225d55]::interface::create_compiler_and_run::<core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>, rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}>
  56:        0x1083798f0 - <scoped_tls[726aaecfe4f649cb]::ScopedKey<rustc_span[cfdc8e2acaf4a144]::SessionGlobals>>::set::<rustc_interface[1aaaf20b10225d55]::interface::run_compiler<core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>, rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}>::{closure#0}, core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>
  57:        0x1083c686c - std[288a9308ea2c3692]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[1aaaf20b10225d55]::util::run_in_thread_pool_with_globals<rustc_interface[1aaaf20b10225d55]::interface::run_compiler<core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>, rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}>::{closure#0}, core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>::{closure#0}, core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>
  58:        0x1083a0520 - <<std[288a9308ea2c3692]::thread::Builder>::spawn_unchecked_<rustc_interface[1aaaf20b10225d55]::util::run_in_thread_pool_with_globals<rustc_interface[1aaaf20b10225d55]::interface::run_compiler<core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>, rustc_driver[ab005e2210e4776d]::run_compiler::{closure#1}>::{closure#0}, core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>::{closure#0}, core[30328a0cdeb81e9a]::result::Result<(), rustc_errors[300f3d566adbb64d]::ErrorGuaranteed>>::{closure#1} as core[30328a0cdeb81e9a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  59:        0x1010d3adc - std::sys::unix::thread::Thread::new::thread_start::ha367c009d033f6c1
  60:        0x1b31fa26c - __pthread_deallocate

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (69a5d2481 2022-04-27) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck] type-checking `main::{closure#0}`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis p
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: environment variable `CARGO_CDYLIB_FILE_MIRRORD_LAYER` not defined
  --> mirrord-cli/src/main.rs:34:31
   |
34 |     file.write(include_bytes!(env!("CARGO_CDYLIB_FILE_MIRRORD_LAYER")));
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'DefId::expect_local: `DefId(1:2441 ~ std[288a]::env::temp_dir)` isn't local', /rustc/69a5d2481e856a5a18885390b8cf6950b9ff8dd3/compiler/rustc_span/src/def_id.rs:283:43
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <rustc_typeck::check::fn_ctxt::FnCtxt>::report_method_error
   3: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
   4: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
   5: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
   6: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
   7: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types::{closure#0}
   8: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_argument_types
   9: <rustc_typeck::check::fn_ctxt::FnCtxt>::confirm_builtin_call
  10: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_call
  11: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  12: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  13: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  14: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  15: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_decl_initializer
  16: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_decl
  17: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_stmt
  18: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_block_with_expected
  19: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_kind
  20: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  21: <rustc_typeck::check::fn_ctxt::FnCtxt>::check_return_expr
  22: rustc_typeck::check::check::check_fn
  23: <rustc_infer::infer::InferCtxtBuilder>::enter::<&rustc_middle::ty::context::TypeckResults, <rustc_typeck::check::inherited::InheritedBuilder>::enter<rustc_typeck::check::typeck_with_fallback<rustc_typeck::check::typeck::{closure#0}>::{closure#1}, &rustc_middle::ty::context::TypeckResults>::{closure#0}>
  24: rustc_typeck::check::typeck
  25: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  26: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  27: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck, rustc_query_impl::plumbing::QueryCtxt>
  28: rustc_typeck::check::typeck
  29: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>
  30: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<rustc_span::def_id::LocalDefId, &rustc_middle::ty::context::TypeckResults>>
  31: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck, rustc_query_impl::plumbing::QueryCtxt>
  32: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_typeck::check::typeck_item_bodies::{closure#0}>
  33: rustc_typeck::check::typeck_item_bodies
  34: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), ()>
  35: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), ()>>
  36: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::typeck_item_bodies, rustc_query_impl::plumbing::QueryCtxt>
  37: <rustc_session::session::Session>::time::<(), rustc_typeck::check_crate::{closure#7}>
  38: rustc_typeck::check_crate
  39: rustc_interface::passes::analysis
  40: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  41: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  42: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  43: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  44: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  45: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  46: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  47: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.62.0-nightly (69a5d2481 2022-04-27) running on aarch64-apple-darwin

note: compiler flags: --crate-type bin -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C incremental

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `main`
#1 [typeck] type-checking `main::{closure#0}`
#2 [typeck_item_bodies] type-checking all item bodies
#3 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `mirrord-cli` due to previous error
```

</p>
</details>

**Comment by SNCPlay42** [comment] 2022-05-05 19:25
I can't reproduce this ICE on the playground from the source given (even with `use std::io::Write; use std::fs::File;` added).

That said, given the panic message + backtrace (`DefId::expect_local` panic in `report_method_error`), this is *probably* a duplicate of #96738.

**Comment by gimbles** [comment] 2022-05-06 06:51
![image](https://user-images.githubusercontent.com/93856041/167081332-fc5c118c-8524-4031-9be8-c0b31067c127.png)

I was not able to reproduce this ICE

# Meta
```
cargo 1.60.0 (d1fd9fe 2022-03-01)
release: 1.60.0
commit-hash: d1fd9fe2c40a1a56af9132b5c92ab963ac7ae422
commit-date: 2022-03-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1m)
os: Pop!_OS 22.04 (jammy) [64-bit]
```

**Comment by JohnTitor** [comment] 2022-05-08 02:11
The correct MCVE is:

```rs
use std::env::temp_dir;
use std::fs::File;
fn main() {
    let file = File::create(temp_dir.as_path().join("lolz")).unwrap();
}
```

and confirmed that the latest nightly no longer causes an ICE, so yes, this is a duplicate of https://github.com/rust-lang/rust/issues/96738. Closing as duplicate/fixed.

**Closed by JohnTitor** 2022-05-08 02:11 UTC
Labels: I-ICE, T-compiler, C-bug
