### ISSUE TITLE
Trivial duplicate code paths are not always merged

### ISSUE THREAD

**Issue by Tobba** [rust-lang/rust#26496] opened 2015-06-22 07:37 UTC
Long winded test case using libcore: (build with --crate-type staticlib and --emit asm)

``` rust
#![feature(no_std, lang_items, asm, core)]
#![no_std]

use core::fmt;

#[macro_use]
extern crate core;

#[lang="panic_fmt"]
extern fn panic_fmt(msg: &fmt::Arguments, file: &'static str, line: u32) -> ! {
    loop { }
}

#[lang="stack_exhausted"]
extern fn stack_exhausted() {
    loop { }
}

#[lang="eh_personality"]
extern fn eh_personality() {
    loop { }
}

#[inline(always)]
fn foo() {
    panic!("Das Ist Nümberwang!");
}

fn black_box<T>(mut value: T) -> T {
    unsafe {
        asm!("" :: "r"(&mut value) :: "volatile");
    }
    value
}

pub fn main() {
    match black_box(5) {
        1 => foo(),
        48 => foo(),
        92 => foo(),
        23 => foo(),
        4 => foo(),
        70 => foo(),
        29 => foo(),
        36 => foo(),
        34 => foo(),
        58 => foo(),
        _ => { }
    }
}
```

This duplicates the following 3 times in the resulting code:

```
    leaq    _ZN3foo14_MSG_FILE_LINE20h7545777ae10911d4MaaE(%rip), %rdi
    callq   _ZN9panicking5panic20hefc2bd49b5114e0db7BE@PLT
```

This may not seem too bad, but in real world cases you can end up with something on the order of this: https://gist.github.com/Tobba/ab10d5644d3d4ef97917

**Comment by arielb1** [comment] 2015-06-22 10:01
LLVM IR?

**Comment by arielb1** [comment] 2015-06-22 10:02
```
; ModuleID = 'rust_out.0.rs'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%str_slice = type { i8*, i64 }
%"2.core::any::TypeId" = type { i64 }

@const818 = internal unnamed_addr constant i64 0
@const822 = internal unnamed_addr constant {}* inttoptr (i64 1 to {}*)
@const823 = internal unnamed_addr constant i8* inttoptr (i64 1 to i8*)
@const841 = internal unnamed_addr constant i8 0
@const853 = internal unnamed_addr constant i64 16
@const854 = internal unnamed_addr constant i32 0
@const874 = internal unnamed_addr constant i8* null
@vtable895 = internal unnamed_addr constant { void (i8*)*, i64, i64, i64 (%str_slice*)* } { void (i8*)* @_ZN2i88drop.87717h403a8fc59605337eE, i64 16, i64 8, i64 (%str_slice*)* @_ZN3any5T.Any11get_type_id21h12885816241882825830E }
@str896 = internal constant [20 x i8] c"Das Ist N\C3\BCmberwang!"
@const897 = internal unnamed_addr constant %str_slice { i8* getelementptr inbounds ([20 x i8], [20 x i8]* @str896, i32 0, i32 0), i64 20 }
@str898 = internal constant [6 x i8] c"<anon>"
@_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE = internal constant { %str_slice, i32, [4 x i8] } { %str_slice { i8* getelementptr inbounds ([6 x i8], [6 x i8]* @str898, i32 0, i32 0), i64 6 }, i32 5, [4 x i8] undef }
@const899 = internal unnamed_addr constant i32 5

; Function Attrs: cold noinline noreturn uwtable
define internal void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly, i64, { %str_slice, i32 }* noalias readonly dereferenceable(24)) unnamed_addr #0 {
entry-block:
  %x.i = alloca %str_slice
  %msg = alloca %str_slice
  %file_line = alloca { %str_slice, i32 }*
  %3 = alloca %str_slice*
  %__coerce_target = alloca { i8*, void (i8*)** }
  %4 = insertvalue %str_slice undef, i8* %0, 0
  %5 = insertvalue %str_slice %4, i64 %1, 1
  store %str_slice %5, %str_slice* %msg, align 8
  store { %str_slice, i32 }* %2, { %str_slice, i32 }** %file_line, align 8
  %6 = getelementptr inbounds %str_slice, %str_slice* %msg, i32 0, i32 0
  %7 = load i8*, i8** %6
  %8 = getelementptr inbounds %str_slice, %str_slice* %msg, i32 0, i32 1
  %9 = load i64, i64* %8
  %10 = insertvalue %str_slice undef, i8* %7, 0
  %11 = insertvalue %str_slice %10, i64 %9, 1
  store %str_slice %11, %str_slice* %x.i, align 8, !noalias !0
  %12 = call i8* @_ZN4heap15exchange_malloc20hfce529015c376a6aJeaE(i64 16, i64 8)
  %13 = bitcast i8* %12 to %str_slice*
  %14 = bitcast %str_slice* %x.i to i8*
  %15 = bitcast %str_slice* %13 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %15, i8* %14, i64 16, i32 8, i1 false)
  store %str_slice* %13, %str_slice** %3, align 8
  %16 = load %str_slice*, %str_slice** %3, align 8, !nonnull !3
  %17 = bitcast %str_slice* %16 to i8*
  %18 = getelementptr inbounds { i8*, void (i8*)** }, { i8*, void (i8*)** }* %__coerce_target, i32 0, i32 0
  store i8* %17, i8** %18
  %19 = getelementptr inbounds { i8*, void (i8*)** }, { i8*, void (i8*)** }* %__coerce_target, i32 0, i32 1
  store void (i8*)** getelementptr inbounds ({ void (i8*)*, i64, i64, i64 (%str_slice*)* }, { void (i8*)*, i64, i64, i64 (%str_slice*)* }* @vtable895, i32 0, i32 0), void (i8*)*** %19
  %20 = getelementptr inbounds { i8*, void (i8*)** }, { i8*, void (i8*)** }* %__coerce_target, i32 0, i32 0
  %21 = load i8*, i8** %20
  %22 = getelementptr inbounds { i8*, void (i8*)** }, { i8*, void (i8*)** }* %__coerce_target, i32 0, i32 1
  %23 = load void (i8*)**, void (i8*)*** %22
  %24 = load { %str_slice, i32 }*, { %str_slice, i32 }** %file_line, align 8, !nonnull !3
  call void @_ZN2rt6unwind18begin_unwind_inner20h30a8282e6074626cKPwE(i8* noalias nonnull %21, void (i8*)** nonnull %23, { %str_slice, i32 }* noalias readonly dereferenceable(24) %24)
  unreachable
}

; Function Attrs: cold noinline noreturn
declare void @_ZN2rt6unwind18begin_unwind_inner20h30a8282e6074626cKPwE(i8* noalias nonnull, void (i8*)** nonnull, { %str_slice, i32 }* noalias readonly dereferenceable(24)) unnamed_addr #1

; Function Attrs: inlinehint uwtable
define internal i8* @_ZN4heap15exchange_malloc20hfce529015c376a6aJeaE(i64, i64) unnamed_addr #2 {
entry-block:
  %sret_slot = alloca i8*
  %size = alloca i64
  %align = alloca i64
  %ptr = alloca i8*
  %2 = alloca i8
  store i64 %0, i64* %size, align 8
  store i64 %1, i64* %align, align 8
  %3 = load i64, i64* %size, align 8
  %4 = icmp eq i64 %3, 0
  br i1 %4, label %then-block-143-, label %else-block

then-block-143-:                                  ; preds = %entry-block
  store i8* inttoptr (i64 1 to i8*), i8** %sret_slot, align 8
  br label %join

else-block:                                       ; preds = %entry-block
  %5 = load i64, i64* %size, align 8
  %6 = load i64, i64* %align, align 8
  %7 = call i8* @_ZN4heap8allocate20hf1bef14c645992daLcaE(i64 %5, i64 %6)
  store i8* %7, i8** %ptr, align 8
  %8 = load i8*, i8** %ptr, align 8
  %9 = call zeroext i1 @"_ZN3ptr14_$BP$mut$u20$T7is_null20h7112856530873119315E"(i8* %8)
  %10 = zext i1 %9 to i8
  store i8 %10, i8* %2, align 1
  %11 = load i8, i8* %2, align 1, !range !4
  %12 = trunc i8 %11 to i1
  br i1 %12, label %then-block-161-, label %next-block

then-block-161-:                                  ; preds = %else-block
  call void @_ZN3oom20hd47d86e88c71d41b96aE()
  unreachable

next-block:                                       ; preds = %else-block
  %13 = load i8*, i8** %ptr, align 8
  store i8* %13, i8** %sret_slot, align 8
  br label %join

join:                                             ; preds = %next-block, %then-block-143-
  %14 = load i8*, i8** %sret_slot, align 8
  ret i8* %14
}

; Function Attrs: inlinehint uwtable
define internal i8* @_ZN4heap8allocate20hf1bef14c645992daLcaE(i64, i64) unnamed_addr #2 {
entry-block:
  %size.i = alloca i64
  %align.i = alloca i64
  %size = alloca i64
  %align = alloca i64
  store i64 %0, i64* %size, align 8
  store i64 %1, i64* %align, align 8
  %2 = load i64, i64* %size, align 8
  %3 = load i64, i64* %align, align 8
  store i64 %2, i64* %size.i, align 8
  store i64 %3, i64* %align.i, align 8
  %4 = load i64, i64* %size, align 8
  %5 = load i64, i64* %align, align 8
  %6 = call i8* @_ZN4heap3imp8allocate20h372b1d8e33193ef6JhaE(i64 %4, i64 %5)
  ret i8* %6
}

; Function Attrs: inlinehint uwtable
define internal i8* @_ZN4heap3imp8allocate20h372b1d8e33193ef6JhaE(i64, i64) unnamed_addr #2 {
entry-block:
  %a.i.i = alloca i64
  %2 = alloca i32
  %sret_slot.i = alloca i32
  %align.i = alloca i64
  %size = alloca i64
  %align = alloca i64
  %flags = alloca i32
  %3 = alloca i8*
  %__arg = alloca i64
  %__arg1 = alloca i32
  store i64 %0, i64* %size, align 8
  store i64 %1, i64* %align, align 8
  %4 = load i64, i64* %align, align 8
  store i64 %4, i64* %align.i, align 8
  %5 = load i64, i64* %align.i, align 8
  %6 = icmp ule i64 %5, 16
  br i1 %6, label %then-block-387-.i, label %else-block.i

then-block-387-.i:                                ; preds = %entry-block
  store i32 0, i32* %sret_slot.i, align 4
  br label %_ZN4heap3imp14align_to_flags20hfe908204913a411erhaE.exit

else-block.i:                                     ; preds = %entry-block
  %7 = load i64, i64* %align.i, align 8
  store i64 %7, i64* %a.i.i, align 8
  %8 = load i64, i64* %a.i.i, align 8
  %9 = call i32 @_ZN3num5usize14trailing_zeros20hbd091b9958e3c3a5d7gE(i64 %8)
  store i32 %9, i32* %2, align 4
  %10 = load i32, i32* %2, align 4
  store i32 %10, i32* %sret_slot.i, align 4
  br label %_ZN4heap3imp14align_to_flags20hfe908204913a411erhaE.exit

_ZN4heap3imp14align_to_flags20hfe908204913a411erhaE.exit: ; preds = %then-block-387-.i, %else-block.i
  %11 = load i32, i32* %sret_slot.i, align 4
  store i32 %11, i32* %flags, align 4
  %12 = load i64, i64* %size, align 8
  %13 = load i32, i32* %flags, align 4
  store i64 %12, i64* %__arg, align 8
  %14 = load i64, i64* %__arg
  store i32 %13, i32* %__arg1, align 4
  %15 = load i32, i32* %__arg1
  %16 = call i8* @je_mallocx(i64 %14, i32 %15)
  store i8* %16, i8** %3, align 8
  %17 = load i8*, i8** %3, align 8
  ret i8* %17
}

; Function Attrs: inlinehint uwtable
define internal i32 @_ZN3num5usize14trailing_zeros20hbd091b9958e3c3a5d7gE(i64) unnamed_addr #2 {
entry-block:
  %self = alloca i64
  %1 = alloca i64
  store i64 %0, i64* %self, align 8
  %2 = load i64, i64* %self, align 8
  %3 = call i64 @llvm.cttz.i64(i64 %2, i1 false)
  store i64 %3, i64* %1, align 8
  %4 = load i64, i64* %1, align 8
  %5 = trunc i64 %4 to i32
  ret i32 %5
}

; Function Attrs: nounwind readnone
declare i64 @llvm.cttz.i64(i64, i1) unnamed_addr #3

declare noalias i8* @je_mallocx(i64, i32) unnamed_addr #4

; Function Attrs: inlinehint uwtable
define internal zeroext i1 @"_ZN3ptr14_$BP$mut$u20$T7is_null20h7112856530873119315E"(i8*) unnamed_addr #2 {
entry-block:
  %self = alloca i8*
  store i8* %0, i8** %self, align 8
  %1 = load i8*, i8** %self, align 8
  %2 = icmp eq i8* %1, null
  %3 = zext i1 %2 to i8
  %4 = trunc i8 %3 to i1
  ret i1 %4
}

; Function Attrs: cold noinline noreturn
declare void @_ZN3oom20hd47d86e88c71d41b96aE() unnamed_addr #1

; Function Attrs: nounwind
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture, i8* nocapture readonly, i64, i32, i1) unnamed_addr #5

define internal void @_ZN2i88drop.87717h403a8fc59605337eE(i8*) unnamed_addr #4 {
entry-block:
  ret void
}

; Function Attrs: uwtable
define internal i64 @_ZN3any5T.Any11get_type_id21h12885816241882825830E(%str_slice* noalias readonly dereferenceable(16)) unnamed_addr #6 {
entry-block:
  %sret_slot = alloca %"2.core::any::TypeId"
  %self = alloca %str_slice*
  store %str_slice* %0, %str_slice** %self, align 8
  %1 = call i64 @_ZN3any6TypeId2of21h11046524029874202962E()
  %2 = bitcast %"2.core::any::TypeId"* %sret_slot to i64*
  store i64 %1, i64* %2, align 8
  %3 = bitcast %"2.core::any::TypeId"* %sret_slot to i64*
  %4 = load i64, i64* %3, align 8
  ret i64 %4
}

; Function Attrs: uwtable
define internal i64 @_ZN3any6TypeId2of21h11046524029874202962E() unnamed_addr #6 {
entry-block:
  %sret_slot = alloca %"2.core::any::TypeId"
  %0 = getelementptr inbounds %"2.core::any::TypeId", %"2.core::any::TypeId"* %sret_slot, i32 0, i32 0
  store i64 8802261786977977801, i64* %0, align 8
  %1 = bitcast %"2.core::any::TypeId"* %sret_slot to i64*
  %2 = load i64, i64* %1, align 8
  ret i64 %2
}

; Function Attrs: uwtable
define internal void @_ZN4main20h84a5f37e14972344RaaE() unnamed_addr #6 {
entry-block:
  %const.i.36 = alloca %str_slice
  %0 = alloca { %str_slice, i32 }*
  %const.i.34 = alloca %str_slice
  %1 = alloca { %str_slice, i32 }*
  %const.i.32 = alloca %str_slice
  %2 = alloca { %str_slice, i32 }*
  %const.i.30 = alloca %str_slice
  %3 = alloca { %str_slice, i32 }*
  %const.i.28 = alloca %str_slice
  %4 = alloca { %str_slice, i32 }*
  %const.i.26 = alloca %str_slice
  %5 = alloca { %str_slice, i32 }*
  %const.i.24 = alloca %str_slice
  %6 = alloca { %str_slice, i32 }*
  %const.i.22 = alloca %str_slice
  %7 = alloca { %str_slice, i32 }*
  %const.i.20 = alloca %str_slice
  %8 = alloca { %str_slice, i32 }*
  %const.i = alloca %str_slice
  %9 = alloca { %str_slice, i32 }*
  %10 = alloca i32
  %match = alloca i32
  %11 = call i32 @_ZN9black_box20h6949009075146505277E(i32 5)
  store i32 %11, i32* %10, align 4
  %12 = load i32, i32* %10, align 4
  store i32 %12, i32* %match, align 4
  %13 = load i32, i32* %match, align 4
  switch i32 %13, label %match_else [
    i32 1, label %match_case
    i32 48, label %match_case11
    i32 92, label %match_case12
    i32 23, label %match_case13
    i32 4, label %match_case14
    i32 70, label %match_case15
    i32 29, label %match_case16
    i32 36, label %match_case17
    i32 34, label %match_case18
    i32 58, label %match_case19
  ]

case_body:                                        ; preds = %match_case
  %14 = bitcast %str_slice* %const.i to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %14, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %15 = getelementptr inbounds %str_slice, %str_slice* %const.i, i32 0, i32 0
  %16 = load i8*, i8** %15
  %17 = getelementptr inbounds %str_slice, %str_slice* %const.i, i32 0, i32 1
  %18 = load i64, i64* %17
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %9, align 8
  %19 = load { %str_slice, i32 }*, { %str_slice, i32 }** %9, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %16, i64 %18, { %str_slice, i32 }* noalias readonly dereferenceable(24) %19)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit:              ; No predecessors!
  br label %join

case_body1:                                       ; preds = %match_case11
  %20 = bitcast %str_slice* %const.i.20 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %20, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %21 = getelementptr inbounds %str_slice, %str_slice* %const.i.20, i32 0, i32 0
  %22 = load i8*, i8** %21
  %23 = getelementptr inbounds %str_slice, %str_slice* %const.i.20, i32 0, i32 1
  %24 = load i64, i64* %23
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %8, align 8
  %25 = load { %str_slice, i32 }*, { %str_slice, i32 }** %8, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %22, i64 %24, { %str_slice, i32 }* noalias readonly dereferenceable(24) %25)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit21:            ; No predecessors!
  br label %join

case_body2:                                       ; preds = %match_case12
  %26 = bitcast %str_slice* %const.i.22 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %26, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %27 = getelementptr inbounds %str_slice, %str_slice* %const.i.22, i32 0, i32 0
  %28 = load i8*, i8** %27
  %29 = getelementptr inbounds %str_slice, %str_slice* %const.i.22, i32 0, i32 1
  %30 = load i64, i64* %29
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %7, align 8
  %31 = load { %str_slice, i32 }*, { %str_slice, i32 }** %7, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %28, i64 %30, { %str_slice, i32 }* noalias readonly dereferenceable(24) %31)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit23:            ; No predecessors!
  br label %join

case_body3:                                       ; preds = %match_case13
  %32 = bitcast %str_slice* %const.i.24 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %32, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %33 = getelementptr inbounds %str_slice, %str_slice* %const.i.24, i32 0, i32 0
  %34 = load i8*, i8** %33
  %35 = getelementptr inbounds %str_slice, %str_slice* %const.i.24, i32 0, i32 1
  %36 = load i64, i64* %35
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %6, align 8
  %37 = load { %str_slice, i32 }*, { %str_slice, i32 }** %6, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %34, i64 %36, { %str_slice, i32 }* noalias readonly dereferenceable(24) %37)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit25:            ; No predecessors!
  br label %join

case_body4:                                       ; preds = %match_case14
  %38 = bitcast %str_slice* %const.i.26 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %38, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %39 = getelementptr inbounds %str_slice, %str_slice* %const.i.26, i32 0, i32 0
  %40 = load i8*, i8** %39
  %41 = getelementptr inbounds %str_slice, %str_slice* %const.i.26, i32 0, i32 1
  %42 = load i64, i64* %41
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %5, align 8
  %43 = load { %str_slice, i32 }*, { %str_slice, i32 }** %5, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %40, i64 %42, { %str_slice, i32 }* noalias readonly dereferenceable(24) %43)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit27:            ; No predecessors!
  br label %join

case_body5:                                       ; preds = %match_case15
  %44 = bitcast %str_slice* %const.i.28 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %44, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %45 = getelementptr inbounds %str_slice, %str_slice* %const.i.28, i32 0, i32 0
  %46 = load i8*, i8** %45
  %47 = getelementptr inbounds %str_slice, %str_slice* %const.i.28, i32 0, i32 1
  %48 = load i64, i64* %47
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %4, align 8
  %49 = load { %str_slice, i32 }*, { %str_slice, i32 }** %4, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %46, i64 %48, { %str_slice, i32 }* noalias readonly dereferenceable(24) %49)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit29:            ; No predecessors!
  br label %join

case_body6:                                       ; preds = %match_case16
  %50 = bitcast %str_slice* %const.i.30 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %50, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %51 = getelementptr inbounds %str_slice, %str_slice* %const.i.30, i32 0, i32 0
  %52 = load i8*, i8** %51
  %53 = getelementptr inbounds %str_slice, %str_slice* %const.i.30, i32 0, i32 1
  %54 = load i64, i64* %53
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %3, align 8
  %55 = load { %str_slice, i32 }*, { %str_slice, i32 }** %3, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %52, i64 %54, { %str_slice, i32 }* noalias readonly dereferenceable(24) %55)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit31:            ; No predecessors!
  br label %join

case_body7:                                       ; preds = %match_case17
  %56 = bitcast %str_slice* %const.i.32 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %56, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %57 = getelementptr inbounds %str_slice, %str_slice* %const.i.32, i32 0, i32 0
  %58 = load i8*, i8** %57
  %59 = getelementptr inbounds %str_slice, %str_slice* %const.i.32, i32 0, i32 1
  %60 = load i64, i64* %59
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %2, align 8
  %61 = load { %str_slice, i32 }*, { %str_slice, i32 }** %2, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %58, i64 %60, { %str_slice, i32 }* noalias readonly dereferenceable(24) %61)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit33:            ; No predecessors!
  br label %join

case_body8:                                       ; preds = %match_case18
  %62 = bitcast %str_slice* %const.i.34 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %62, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %63 = getelementptr inbounds %str_slice, %str_slice* %const.i.34, i32 0, i32 0
  %64 = load i8*, i8** %63
  %65 = getelementptr inbounds %str_slice, %str_slice* %const.i.34, i32 0, i32 1
  %66 = load i64, i64* %65
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %1, align 8
  %67 = load { %str_slice, i32 }*, { %str_slice, i32 }** %1, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %64, i64 %66, { %str_slice, i32 }* noalias readonly dereferenceable(24) %67)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit35:            ; No predecessors!
  br label %join

case_body9:                                       ; preds = %match_case19
  %68 = bitcast %str_slice* %const.i.36 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* %68, i8* bitcast (%str_slice* @const897 to i8*), i64 16, i32 8, i1 false)
  %69 = getelementptr inbounds %str_slice, %str_slice* %const.i.36, i32 0, i32 0
  %70 = load i8*, i8** %69
  %71 = getelementptr inbounds %str_slice, %str_slice* %const.i.36, i32 0, i32 1
  %72 = load i64, i64* %71
  store { %str_slice, i32 }* bitcast ({ %str_slice, i32, [4 x i8] }* @_ZN3foo10_FILE_LINE20h45522c5a40a253aeqaaE to { %str_slice, i32 }*), { %str_slice, i32 }** %0, align 8
  %73 = load { %str_slice, i32 }*, { %str_slice, i32 }** %0, align 8, !nonnull !3
  call void @_ZN2rt6unwind12begin_unwind21h15563644326691858274E(i8* noalias nonnull readonly %70, i64 %72, { %str_slice, i32 }* noalias readonly dereferenceable(24) %73)
  unreachable

_ZN3foo20h19ea02efff3ae1b1eaaE.exit37:            ; No predecessors!
  br label %join

case_body10:                                      ; preds = %match_else
  br label %join

match_else:                                       ; preds = %entry-block
  br label %case_body10

match_case:                                       ; preds = %entry-block
  br label %case_body

match_case11:                                     ; preds = %entry-block
  br label %case_body1

match_case12:                                     ; preds = %entry-block
  br label %case_body2

match_case13:                                     ; preds = %entry-block
  br label %case_body3

match_case14:                                     ; preds = %entry-block
  br label %case_body4

match_case15:                                     ; preds = %entry-block
  br label %case_body5

match_case16:                                     ; preds = %entry-block
  br label %case_body6

match_case17:                                     ; preds = %entry-block
  br label %case_body7

match_case18:                                     ; preds = %entry-block
  br label %case_body8

match_case19:                                     ; preds = %entry-block
  br label %case_body9

join:                                             ; preds = %case_body10, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit37, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit35, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit33, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit31, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit29, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit27, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit25, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit23, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit21, %_ZN3foo20h19ea02efff3ae1b1eaaE.exit
  ret void
}

; Function Attrs: uwtable
define internal i32 @_ZN9black_box20h6949009075146505277E(i32) unnamed_addr #6 {
entry-block:
  %value = alloca i32
  store i32 %0, i32* %value, align 4
  call void asm sideeffect "", "r,~{dirflag},~{fpsr},~{flags}"(i32* %value), !srcloc !5
  %1 = load i32, i32* %value, align 4
  ret i32 %1
}

define i64 @main(i64, i8**) unnamed_addr #4 {
top:
  %2 = call i64 @_ZN2rt10lang_start20hdadb5fc58c5eeff334wE(i8* bitcast (void ()* @_ZN4main20h84a5f37e14972344RaaE to i8*), i64 %0, i8** %1)
  ret i64 %2
}

declare i64 @_ZN2rt10lang_start20hdadb5fc58c5eeff334wE(i8*, i64, i8**) unnamed_addr #4

attributes #0 = { cold noinline noreturn uwtable "split-stack" }
attributes #1 = { cold noinline noreturn "split-stack" }
attributes #2 = { inlinehint uwtable "split-stack" }
attributes #3 = { nounwind readnone "split-stack" }
attributes #4 = { "split-stack" }
attributes #5 = { nounwind "split-stack" }
attributes #6 = { uwtable "split-stack" }

!0 = !{!1}
!1 = distinct !{!1, !2, !"_ZN5boxed12Box$LT$T$GT$3new20h1497791211319906357E: argument 0"}
!2 = distinct !{!2, !"_ZN5boxed12Box$LT$T$GT$3new20h1497791211319906357E"}
!3 = !{}
!4 = !{i8 0, i8 2}
!5 = !{i32 4}
```

**Comment by arielb1** [comment] 2015-06-22 10:05
This seems like an LLVM issue (maybe it tries to preserve traceback line numbers?).

**Comment by dylanmckay** [comment] 2015-10-27 14:21
The problem is that LLVM does not implement duplicate basic block merging (see bug [24220](https://llvm.org/bugs/show_bug.cgi?id=24220)).

I have written a pass (and in the process of submitting it) which correctly deduplicates switch case blocks if they are identical.

**Comment by dylanmckay** [comment] 2015-10-27 14:22
An even shorter reproduction case:

``` llvm

declare void @foo();

; Function Attrs: uwtable
define external void @main() unnamed_addr #6 {
entry-block:
  %value.i = alloca i32, align 4
  %0 = bitcast i32* %value.i to i8*
  store i32 5, i32* %value.i, align 4
  
  call void asm "", "r,~{dirflag},~{fpsr},~{flags}"(i32* nonnull %value.i) #7

  %1 = load i32, i32* %value.i, align 4
  switch i32 %1, label %join [
    i32 1, label %match_case
    i32 48, label %match_case11
    i32 92, label %match_case12
    i32 23, label %match_case13
    i32 4, label %match_case14
    i32 70, label %match_case15
    i32 29, label %match_case16
    i32 36, label %match_case17
    i32 34, label %match_case18
    i32 58, label %match_case19
  ]

match_case:                                       ; preds = %entry-block
  call void @foo()
  unreachable

match_case11:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case12:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case13:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case14:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case15:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case16:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case17:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case18:                                     ; preds = %entry-block
  call void @foo()
  unreachable

match_case19:                                     ; preds = %entry-block
  call void @foo()
  unreachable

join:                                             ; preds = %entry-block
  ret void
}
```

**Comment by ranma42** [comment] 2015-12-31 11:16
This problem affects the `Eq` code for enums as per comments in #13623

**Comment by Mark-Simulacrum** [comment] 2017-04-15 17:29
With `rustc --crate-type lib --emit asm -O`, the `leaq` is only seen once in the output. Closing as fixed.

**Closed by Mark-Simulacrum** 2017-04-15 17:29 UTC
Labels: A-codegen, A-LLVM
