### ISSUE TITLE
Error reporting when using enum variants of Self is not making any sense

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#48743] opened 2018-03-05 02:46 UTC
Take the following code:
```rust
pub enum Foo { A }

impl Foo {
    pub fn new() -> Self {
        Self::A
    }
}
```

This is known to not work (I don't know if it's on file or not, but will report separately), but the error reported is really not helping developers:

```
error[E0599]: no variant named `A` found for type `Foo` in the current scope
 --> <source>:5:9
  |
1 | pub enum Foo { A }
  | ------------ variant `A` not found here
...
5 |         Self::A
  |         ^^^^^^^ variant not found in `Foo`
error: aborting due to previous error
Compiler returned: 101
```

Not only is it reporting the right type, but it's also pointing to the definition where the variant *is* defined.

This actually got worse in 1.24. 1.23 and older versions only reported the following, which was already bad, but the new message is significantly worse:
```
error[E0599]: no associated item named `A` found for type `Foo` in the current scope
 --> <source>:5:9
  |
5 |         Self::A
  |         ^^^^^^^
error: aborting due to previous error
Compiler returned: 101
```

**Comment by glandium** [comment] 2018-03-05 07:40
> This is known to not work (I don't know if it's on file or not, but will report separately)

Found it in issue #26264. Which means it's been pending for very long, and the error should be changed rather than wait some more for that to be implemented.

**Comment by estebank** [comment] 2019-04-29 21:01
Current error:

```
error: enum variants on type aliases are experimental
 --> src/lib.rs:5:9
  |
5 |         Self::A
  |         ^^^^^^^
  |
  = help: add `#![feature(type_alias_enum_variants)]` to the crate attributes to enable
```

Duplicate of https://github.com/rust-lang/rust/issues/56104 and https://github.com/rust-lang/rust/issues/52118

**Closed by estebank** 2019-04-29 21:01 UTC
Labels: A-diagnostics, C-enhancement
