### ISSUE TITLE
non-exhaustive patterns: type ! is non-empty

### ISSUE THREAD

**Issue by Sh4rK** [rust-lang/rust#36011] opened 2016-08-26 13:34 UTC
Hi!

I'm trying out `feature(never_type)` and getting an error on the simplest example possible.
Rustc is `rustc 1.13.0-nightly (3c5a0fa45 2016-08-22)` on `x86_64-pc-windows-msvc`.

The code:

``` rust
#![feature(never_type)]

fn main() {
    let never: !;
    match never {};
}
```

And the error I get:

```
error[E0002]: non-exhaustive patterns: type ! is non-empty
 --> src\main.rs:5:5
  |
5 |     match never {};
  |     ^^^^^^^^^^^^^^
  |
help: Please ensure that all possible cases are being handled; possibly adding wildcards or more match arms.
 --> src\main.rs:5:5
  |
5 |     match never {};
  |     ^^^^^^^^^^^^^^
```

Which is quite bad, as the point of `!` is that it is empty.

If I replace it with an empty enum, it works. (It errors on the uninitialized variable, but that's not the point.)

**Comment by Sh4rK** [comment] 2016-08-26 13:54
Related to #35162 (`feature(never_type)`)

**Comment by Sh4rK** [comment] 2016-08-27 13:11
I'm guessing @canndrew or @eddyb might know what's going on?

**Comment by canndrew** [comment] 2016-08-27 13:30
[This function here](https://github.com/rust-lang/rust/blob/099b9fdb1a170b57ffd7174b3c3042cc86b7fe91/src/librustc/ty/sty.rs#L916) is the one that checks whether a type is empty but it currently only works on empty enums. I tried to extend it to also handle `!` (and all other empty types) but @eddyb and @nikomatsakis were worried about that change because the function was originally only written with empty enums in mind. They know a lot more about the compiler than I do but I hope they reconsider (or at least clarify what the potential breakages might be) because `!` is kinda broken without it, plus, as it says in the comments, I've tested that change and it *seems* to work (or at least it doesn't break the compiler test suites).

**Comment by Sh4rK** [comment] 2016-08-27 15:45
That seems a bit unfortunate, but I understand it might not be a trivial change.

So to safely unwrap a `Result<T, !>` for example, currently I should do something like this, or is there a better way?
```rust
match res {
    Ok(v) => v,
    Err(e) => e,
}
```

**Comment by canndrew** [comment] 2016-08-27 15:57
Yes, that's how you have to do it.

**Comment by Mark-Simulacrum** [comment] 2017-05-13 00:15
I'm not sure whether it's me or the code, but I cannot reproduce this, since I can't figure out a way to get `!` in a variable without having either unreachable code or the uninitialized variable warning, which both mask (if it even is still a problem) the error this issue reports, so closing.

```
error[E0381]: use of possibly uninitialized variable: `never`
 --> test.rs:5:11
  |
5 |     match never {};
  |           ^^^^^ use of possibly uninitialized `never`

error: aborting due to previous error
```

**Closed by Mark-Simulacrum** 2017-05-13 00:15 UTC

**Comment by glaebhoerl** [comment] 2017-05-14 12:03
@Mark-Simulacrum A way to do it is `fn foo(never: !)` instead of a `let`. But the bug does seem to be fixed.
