### ISSUE TITLE
Beta regression with lifetime inference

### ISSUE THREAD

**Issue by Ryman** [rust-lang/rust#29979] opened 2015-11-22 05:01 UTC
I'm unsure if this issue is specifically related to `Borrow` or `HashMap::get` but [this playpen](http://is.gd/Ca16OJ) works on current stable (1.4), but fails on both beta and nightly.

The issue can be fixed with a type annotation in the simple case, as shown on playpen if you uncomment the line above the failure, so I assume failure is not intended by some change in lifetime rules. (Additionally, the error message itself doesn't help lead a user to the solution here :( )

But, I've got a more complicated manifestation which I've been unable to solve with type-hints so I think it's worth a look at: https://github.com/seanmonstar/unicase/pull/6

[Travis outputs for linked PR](https://travis-ci.org/seanmonstar/unicase/builds/92516667)

cc @nikomatsakis @brson

**Comment by bluss** [comment] 2015-11-22 06:27
This must be the same as #28853

**Comment by arielb1** [comment] 2015-11-22 07:24
@Ryman 

This is a known regression that is the same as #28853. The old code compiled for dubious reasons. Due to the evil nature of `find`, it is unclear how to get it to compile usefully, except by aggressive use of `transmute`.

**Comment by Ryman** [comment] 2015-11-23 00:33
@arielb1 Okay, should we close as duplicate?

**Comment by brson** [comment] 2015-11-23 20:57
Closing per @arielb1 as dupe.

**Closed by brson** 2015-11-23 20:57 UTC
Labels: I-nominated, regression-from-stable-to-beta, T-compiler
