### ISSUE TITLE
Generic Trait restrictions don't seem to work when accessing a constant from the trait

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#69553] opened 2020-02-28 14:27 UTC
```rust
trait Foo {
    const X: usize;
}

pub struct Bar<T: Foo, U>([U; T::X]);
pub struct Bar2<T: Foo, U>([U; T::X], core::marker::PhantomData<T> );
pub struct Bar3<T: Foo, U>([U; <T as Foo>::X] );
pub struct Bar4<T: Foo, U>([U; <T as Foo>::X], core::marker::PhantomData<T> );
```

I expected to see this happen: Compile.

Instead, this happened: 

The error message is pretty awkward too, recommending to  add a restriction on T that is already present, and it winds up recommending `T: Foo + Foo`.

```
  Compiling playground v0.0.1 (/playground)
error[E0599]: no associated item named `X` found for type `T` in the current scope
 --> src/lib.rs:5:34
  |
5 | pub struct Bar<T: Foo, U>([U; T::X]);
  |                                  ^ associated item not found in `T`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `X`, perhaps you need to restrict type parameter `T` with it:
  |
5 | pub struct Bar<T: Foo + Foo, U>([U; T::X]);
  |                ^^^^^^^^

error[E0392]: parameter `T` is never used
 --> src/lib.rs:5:16
  |
5 | pub struct Bar<T: Foo, U>([U; T::X]);
  |                ^ unused parameter
  |
  = help: consider removing `T`, referring to it in a field, or using a marker such as `std::marker::PhantomData`

error[E0599]: no associated item named `X` found for type `T` in the current scope
 --> src/lib.rs:6:35
  |
6 | pub struct Bar2<T: Foo, U>([U; T::X], core::marker::PhantomData<T> );
  |                                   ^ associated item not found in `T`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `X`, perhaps you need to restrict type parameter `T` with it:
  |
6 | pub struct Bar2<T: Foo + Foo, U>([U; T::X], core::marker::PhantomData<T> );
  |                 ^^^^^^^^

error[E0277]: the trait bound `T: Foo` is not satisfied
 --> src/lib.rs:7:32
  |
2 |     const X: usize;
  |     --------------- required by `Foo::X`
...
7 | pub struct Bar3<T: Foo, U>([U; <T as Foo>::X] );
  |                 --             ^^^^^^^^^^^^^ the trait `Foo` is not implemented for `T`
  |                 |
  |                 help: consider further restricting this bound: `T: Foo +`

error[E0392]: parameter `T` is never used
 --> src/lib.rs:7:17
  |
7 | pub struct Bar3<T: Foo, U>([U; <T as Foo>::X] );
  |                 ^ unused parameter
  |
  = help: consider removing `T`, referring to it in a field, or using a marker such as `std::marker::PhantomData`

error[E0277]: the trait bound `T: Foo` is not satisfied
 --> src/lib.rs:8:32
  |
2 |     const X: usize;
  |     --------------- required by `Foo::X`
...
8 | pub struct Bar4<T: Foo, U>([U; <T as Foo>::X], core::marker::PhantomData<T> );
  |                 --             ^^^^^^^^^^^^^ the trait `Foo` is not implemented for `T`
  |                 |
  |                 help: consider further restricting this bound: `T: Foo +`

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0277, E0392, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

### Meta
Reproduces on current nightly, beta and stable.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=00f2f308b1e5a37c926e2a8cf30bd030

**Comment by jonas-schievink** [comment] 2020-02-28 14:32
Duplicate of https://github.com/rust-lang/rust/issues/43408

**Closed by jonas-schievink** 2020-02-28 14:32 UTC
Labels: C-bug
