### ISSUE TITLE
hidden type for `impl Trait` captures lifetime that does not appear in bounds

### ISSUE THREAD

**Issue by eloff** [rust-lang/rust#87632] opened 2021-07-30 16:57 UTC
Reproduction of issue:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4b48a9611f760226b37832138691e1d

See also the stackoverflow question I asked about it:
https://stackoverflow.com/questions/68591843/hidden-type-for-impl-trait-captures-lifetime-that-does-not-appear-in-bounds

This appears to be a long-standing limitation of the rust compiler with a mechanical fix available: https://crates.io/crates/fix-hidden-lifetime-bug

The author of that crate appears to have given up on seeing a fix for this in the rust compiler itself: https://users.rust-lang.org/t/lifetimes-in-smol-executor/59157/8?u=yandros

I'm opening this issue because I agree with him, it seems to be a compiler flaw, and it seems fixable. You can close this as won't fix, but it'd be nice at least to spell out the reasoning for that here for others who encounter this issue.

**Comment by jonas-schievink** [comment] 2021-07-30 17:11
duplicate of https://github.com/rust-lang/rust/issues/63033

**Closed by jonas-schievink** 2021-07-30 17:11 UTC
Labels: C-bug

**Comment by ttappr** [comment] 2021-07-31 01:50
The 'static lifetime applied to the parameter is not meaningfully used within the method - it's unnecessary. I personally prefer that the compiler not allow this and it not be considered a bug. However, the compiler error message could be more exact.
