### ISSUE TITLE
`forbid` overwritten by later `allow` on the same "scope level"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#70819] opened 2020-04-05 17:09 UTC
`forbid` is not honored when it is followed by an `allow` on the same "scope level". This compiles, but should fail:
```rust
#![forbid(unused)]
#![allow(unused)]

fn square(num: i32) -> i32 {
    num * num
}
```

If we move the `allow` down to the function level, it fails to compile as expected:

```rust
#![forbid(unused)]

#[allow(unused)]
fn square(num: i32) -> i32 {
    num * num
}
```

The same issue also arises with CLI arguments, which all share the "scope level". That was worked around with in https://github.com/rust-lang/rust/pull/70918, but once the above is fixed, that hack can likely be removed.

### Original description

According to my understanding, the purpose of `-F`/`forbid` for lints is that they can not be allowed any more. Thus I would expect that calling rustc with `-Funused -Aunused` will fail when there is unused code in the file.

However, that is not the case: with that sequence of arguments, unused code is silently accepted.

Cc https://github.com/laumann/compiletest-rs/issues/216

**Comment by RalfJung** [comment] 2020-04-05 17:11
This is in fact a stable-to-beta regression: with Rust 1.42, the code [still gets rejected as expected](https://godbolt.org/z/7fEHUj).

**Comment by RalfJung** [comment] 2020-04-05 17:16
Likely regression candidate: https://github.com/rust-lang/rust/pull/67885

**Comment by RalfJung** [comment] 2020-04-05 17:19
Interestingly, doing the same via flags in the source code *also* does not work as expected -- the `allow` overwrites the `forbid`!
```rust
#![forbid(unused)]
#![allow(unused)]

fn square(num: i32) -> i32 {
    num * num
}
```
This part is *not* a regression, but still looks like a bug.

**Comment by spastorino** [comment] 2020-04-08 18:32
According to @RalfJung this has possibly regressed on #67885.
I guess this needs confirmation ...

@rustbot ping cleanup

**Comment by spastorino** [comment] 2020-04-08 18:36
Assigning `P-medium` and removing nomination. This was [discussed as part of pre-triage meeting in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/pre-meeting.20triage.202020-04-09.20.2354818/near/193360163).

**Comment by spastorino** [comment] 2020-04-08 18:41
Nominating also according to what was discussed during the meeting to `T-lang` for discussion.

**Comment by RalfJung** [comment] 2020-04-08 18:42
Note that there are two separate regressions going on:
- The CLI argument regression in the original post, which I noticed first. I am reasonably sure that one stems from https://github.com/rust-lang/rust/pull/67885, though of course it can never hurt to double-check.
- The regression in the handling of inline attributes that I described in https://github.com/rust-lang/rust/issues/70819#issuecomment-609450864. That one is somewhere between the 1.20 and 1.21 release, and pinning this down more precisely would be very useful indeed.

**Comment by AminArria** [comment] 2020-04-08 21:43
Bisect of CLI arguments:

searched nightlies: from nightly-2020-02-04 to nightly-2020-02-18
regressed nightly: nightly-2020-02-17
searched commits: from https://github.com/rust-lang/rust/commit/61d9231ff2604a0467987042d9ebf9ff9ea739b5 to https://github.com/rust-lang/rust/commit/5e7af4669f80e5f682141f050193ab679afdb4b1
regressed commit: https://github.com/rust-lang/rust/commit/5e7af4669f80e5f682141f050193ab679afdb4b1

Indeed it seems the issue comes from #67885

**Comment by tobithiel** [comment] 2020-04-08 21:49
I opened #70918 to address the CLI argument regression

**Comment by AminArria** [comment] 2020-04-08 23:09
Bisect of inline attributes:

```
searched toolchains nightly-2017-07-27 through nightly-2017-10-09
regression in nightly-2017-08-11
```

Checking for commit hashes in that nightly and the one before
```
$> rustc +nightly-2017-08-11 -vV
rustc 1.21.0-nightly (13d94d5fa 2017-08-10)
binary: rustc
commit-hash: 13d94d5fa8129a34f5c77a1bcd76983f5aed2434

$> rustc +nightly-2017-08-10 -vV
rustc 1.21.0-nightly (f14249953 2017-08-09)
binary: rustc
commit-hash: f142499539d038ef60f4e22cafe11ecdd8a29a1d
```

Commits by bors in that range:
```
$> git log --author=bors --format=oneline f142499539d038ef60f4e22cafe11ecdd8a29a1d..13d94d5fa8129a34f5c77a1bcd76983f5aed2434
13d94d5fa8129a34f5c77a1bcd76983f5aed2434 Auto merge of #43559 - Nashenas88:nll-region-renumberer, r=arielb1
b6179602bea71607a9ea63197eca423fcce5f7b0 Auto merge of #43720 - pornel:staticconst, r=petrochenkov
2400ebfe76225745d1591c8a63c54570174ab22c Auto merge of #43522 - alexcrichton:rewrite-lints, r=michaelwoerister
d21ec9b4efd1da012979b050bc0a0426fe45fcdf Auto merge of #43582 - ivanbakel:unused_mut_ref, r=arielb1
2ac5f7d249e29ee48737359e0e6dd9e59701a568 Auto merge of #43737 - GuillaumeGomez:duplicate-method, r=eddyb
16268a88fc0cfe3657439139c63913ffb904b2fa Auto merge of #43735 - est31:master, r=alexcrichton
57e720d2cd09b6befc5b6eed66b65352fc9ff537 Auto merge of #43730 - nrc:driver-shim, r=eddyb
875bcf5c5f7efcbf72e000d256b24293555edf53 Auto merge of #43627 - Aaronepower:master, r=alexcrichton
```

**Comment by RalfJung** [comment] 2020-04-09 07:15
@AminArria thanks a lot! I would guess the most likely regression candidate is https://github.com/rust-lang/rust/pull/43522, then.

My guess would be that [somewhere around here](https://github.com/rust-lang/rust/pull/43522/files#diff-e520b564624a0691c0a4a66932d8c7feR239), lint groups are not handled properly. This code looks different from [the previous `forbid` handling](https://github.com/rust-lang/rust/pull/43522/files#diff-771d6215d1fb5e7f5503514f9895f7bdL756), though why one would treat lint groups properly and one would not is beyond me.

Cc @alexcrichton @michaelwoerister (PR author and reviewer)... but this is from 2017 so I doubt they will remember many details. ;) Cc @rust-lang/wg-diagnostics for people with lint knowledge.

**Comment by alexcrichton** [comment] 2020-04-09 16:26
I'm not sure I have a ton to add here myself, this definitely feels like a bug (both CLI and attribute handling) and seems reasonable to fix, and the fix is likely the same for both.

**Comment by RalfJung** [comment] 2020-04-10 09:08
Turns out the problem is not about lint groups, it is about `forbid` being on the same "scope level" as `allow`. The following behaves as expected (i.e., it fails to compile):
```rust
#![forbid(unused)]

#[allow(unused)]
fn square(num: i32) -> i32 {
    num * num
}
```

**Comment by Centril** [comment] 2020-04-10 10:36
Hmm... It feels clear to me that this is a bug (the attributes part, the command line aspect is up to T-compiler). So to potentially save the language team meeting some time (we didn't get to this issue on yesterday's meeting), I wonder if @pnkfelix could clarify what aspect the language team should discuss and provide feedback on here.

**Comment by pnkfelix** [comment] 2020-04-10 16:32
The reason @rust-lang/wg-prioritization added T-lang was because figured that the semantics of the attribute-based control of the lints was part of the language, not the tooling. (The fact that the command-line controls was changed to match that of the attribute-based control *is* in the domain of T-compiler.)


However, it seems likely that this is "just a bug" in how lint controls in the same "scope level" are handled, and so I would be fine with treating this as solely the domain of T-compiler, not T-lang.

(Given that the attribute based controls have had this behavior since the middle of 2017, I figure it would still be reasonable to float this up to the lang team; not as something to debate, but more of a "general notice, here's a deep bug we recently discovered...")

**Comment by pnkfelix** [comment] 2020-04-10 18:59
(anyway, we discussed this at today's [ad hoc triage meeting](https://zulip-archive.rust-lang.org/131828tcompiler/35095adhoctriagemeeting2020041054818.html#193575606)). I suspect at this point we can remove the nomination tag; its looking like everyone agree that this is "just a bug" that needs to be fixed, not even a terribly high priority one.)

**Comment by nikomatsakis** [comment] 2020-05-07 14:27
@pnkfelix mentioned in the compiler-team meeting today that P-medium didn't seem high enough for this bug. I'm inclined to agree. I think we ought to fix this. I wouldn't call it *P-critical*, but seems like P-high?

**Comment by LeSeulArtichaut** [comment] 2020-05-07 19:24
(Added `I-prioritize` to discuss this issue with the Prioritization WG)

**Comment by pnkfelix** [comment] 2020-05-22 18:27
One thing that I should have brought up sooner:

Should this bug be reclassified as a stable-to-stable regression rather than a stable-to-beta one, given that the underlying problem as identified by @RalfJung [up above](https://github.com/rust-lang/rust/issues/70819#issuecomment-611950730) has been present since version 1.21 in 2017?

**Comment by pnkfelix** [comment] 2020-05-22 18:36
To be clear, reclassifying as a stable-to-stable regression would reduce the pressure to resolve this in time for the release on June 4th.

(The stable-to-beta regression at hand was the CLI behavior regression, which was already addressed by PR #70918 )

It would also mean that

**Comment by RalfJung** [comment] 2020-05-22 20:14
Yeah I guess it makes sense, given that current stable already contains the regression.

**Comment by petrochenkov** [comment] 2020-10-04 16:10
The PR fixing this (https://github.com/rust-lang/rust/pull/73379) was closed due to inactivity.
Could someone rebase it, update clippy tests and resubmit?

**Comment by Mark-Simulacrum** [comment] 2020-10-04 16:45
I can do that.

**Comment by SparrowLii** [comment] 2021-05-10 07:46
@RalfJung  The [FIXME](https://github.com/rust-lang/rust/blob/master/compiler/rustc_session/src/config.rs#L1166-L1168) here links to this closed issue. I think it can be removed?

**Comment by RalfJung** [comment] 2021-05-10 13:30
Maybe? It is worth trying, but I don't know that code very well.

**Comment by FabianWolff** [comment] 2021-05-12 20:15
Unfortunately not, it seems. With the following input file:
```rust
fn main() {
    let a = 5;
}
```
I get, on current nightly with `-F unused -A unused`:
```
error: unused variable: `a`
 --> t1.rs:2:9
  |
2 |     let a = 5;
  |         ^ help: if this is intentional, prefix it with an underscore: `_a`
  |
  = note: `-F unused-variables` implied by `-F unused`

error: aborting due to previous error
```
which is actually suboptimal, because there is no warning about the `-A` being overwritten by the `-F` (with crate attributes `#![forbid(unused)]` and `#![allow(unused)]`, there is a warning, and it even mentions that this will become a hard error in the future).

In any case, with the following patch applied and the same command line arguments:
```diff
diff --git a/compiler/rustc_session/src/config.rs b/compiler/rustc_session/src/config.rs
index f517c483758..436afad11b8 100644
--- a/compiler/rustc_session/src/config.rs
+++ b/compiler/rustc_session/src/config.rs
@@ -1161,15 +1161,7 @@ pub fn get_cmd_lint_options(
     let mut describe_lints = false;
 
     for &level in &[lint::Allow, lint::Warn, lint::Deny, lint::Forbid] {
-        for (passed_arg_pos, lint_name) in matches.opt_strs_pos(level.as_str()) {
-            let arg_pos = if let lint::Forbid = level {
-                // HACK: forbid is always specified last, so it can't be overridden.
-                // FIXME: remove this once <https://github.com/rust-lang/rust/issues/70819> is
-                // fixed and `forbid` works as expected.
-                usize::MAX
-            } else {
-                passed_arg_pos
-            };
+        for (arg_pos, lint_name) in matches.opt_strs_pos(level.as_str()) {
             if lint_name == "help" {
                 describe_lints = true;
             } else {
```
I get no warnings and no errors (incorrectly, because `-F` should not be overwritten by `-A`).

**Comment by RalfJung** [comment] 2021-05-12 20:24
> I get no warnings and no errors (incorrectly, because -F should not be overwritten by -A).

Yeah that's wrong... so the FIXME is still accurate, though I am not sure why.

**Comment by nikomatsakis** [comment] 2021-05-13 10:01
I'm going to briefly re-open this issue -- I don't remember what we decided about `-F` and `-A`, but I bet @Mark-Simulacrum does =)

**Comment by pnkfelix** [comment] 2022-12-16 16:32
Arguably this shouldn't be assigned to me anymore.

Its possible we may want to close this and open a fresh issue dedicated to the command line interactions between -F and -A

**Comment by jieyouxu** [comment] 2024-11-22 15:39
Visited during [T-compiler P-high review](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202024-11-22.20P-high.20review/near/483935050): closing this issue as the original issue is resolved, opened #133346 for the `-F` and `-A` cli interactions.

**Closed by jieyouxu** 2024-11-22 15:39 UTC
Labels: A-frontend, A-lint, P-high, T-compiler, regression-from-stable-to-stable, C-bug, WG-diagnostics, ICEBreaker-Cleanup-Crew

**Comment by RalfJung** [comment] 2024-11-22 15:42
The original issue was in fact "According to my understanding, the purpose of -F/forbid for lints is that they can not be allowed any more. Thus I would expect that calling rustc with -Funused -Aunused will fail when there is unused code in the file.", as can be seen in the issue description. That issue is unresolved.

But we can move it to a new issue, sure. 🤷

**Comment by jieyouxu** [comment] 2024-11-22 15:58
Ah right, I think when I visited this issue I focused on the recent comments then forgot about the issue description, sorry 😅

**Comment by jieyouxu** [comment] 2024-11-22 16:21
I tried to transcribe the inconsistency issue in the new issue #133346.
