### ISSUE TITLE
Derived `PartialEq` for Box<dyn Trait> is incorrect.

### ISSUE THREAD

**Issue by davidli2010** [rust-lang/rust#74284] opened 2020-07-13 03:32 UTC
```rust
pub trait T {}

impl PartialEq for dyn T {
    fn eq(&self, _other: &Self) -> bool {
        todo!()
    }
}

#[derive(PartialEq)]
pub struct A {
    child: Box<dyn T>,
}

impl T for A {}

// impl PartialEq for A {
//     fn eq(&self, other: &Self) -> bool {
//         *self.child == *other.child
//     }
// }

fn main() {}

```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2901dd55c3c436ec01fe007b146ceb09))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0507]: cannot move out of `*__self_1_0` which is behind a shared reference
  --> src/main.rs:11:5
   |
11 |     child: Box<dyn T>,
   |     ^^^^^^^^^^^^^^^^^ move occurs because `*__self_1_0` has type `std::boxed::Box<dyn T>`, which does not implement the `Copy` trait
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by davidli2010** [comment] 2020-07-13 03:34
If I remove `#[derive(PartialEq)]` and impl it manually:

```Rust
impl PartialEq for A {
    fn eq(&self, other: &Self) -> bool {
        *self.child == *other.child
    }
}
```

It works.

**Comment by sfackler** [comment] 2020-07-13 11:16
Duplicate of #39128.

**Closed by sfackler** 2020-07-13 11:16 UTC
