### ISSUE TITLE
Confusing error message due to elided lifetimes on traits (?)

### ISSUE THREAD

**Issue by waywardmonkeys** [rust-lang/rust#33981] opened 2016-05-31 14:18 UTC
When I compile this code:

``` rust
use std::fmt;

pub struct Arg<'a, T: 'a + fmt::Display + ?Sized> {
    name: &'a str,
    value: &'a T,
    prev: Option<&'a Args<'a>>,
}

pub fn arg<'a, T: 'a + fmt::Display + ?Sized>(name: &'a str, value: &'a T) -> Arg<'a, T> {
    Arg {
        name: name,
        value: value,
        prev: None,
    }
}

pub trait Args<'a> {
    fn arg<T: 'a + fmt::Display + ?Sized>(&'a self, name: &'a str, value: &'a T) -> Arg<'a, T>
        where Self: Sized
    {
        Arg {
            name: name,
            value: value,
            prev: Some(self),
        }
    }

    fn fmt_value(&self, f: &mut fmt::Formatter) -> fmt::Result;

    fn get(&'a self, name: &str) -> Option<&'a Args<'a>>;
}

impl<'a, T> Args<'a> for Arg<'a, T>
    where T: std::fmt::Display
{
    fn fmt_value(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.value.fmt(f)
    }

    fn get(&'a self, name: &str) -> Option<&'a Args<'a>> {
        if self.name == name {
            Some(self)
        } else if let Some(prev) = self.prev {
            prev.get(name)
        } else {
            None
        }
    }
}

impl<'a> fmt::Display for Args<'a> {
    /// Forward `fmt::Display` to the underlying value.
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.fmt_value(f)
    }
}

fn dbg<'d>(args: &Args<'d>) {
  println!("Help! {}", args);
}

fn main() {
  dbg(&arg("name", &"John").arg("city", &"Philadelphia"));
}
```

The errors that I get aren't obviously related to the actual / underlying problem (to me at least):

```
use std::fmt;
pub struct Arg<'a, T: 'a + fmt::Display + ?Sized> {
    name: &'a str,
    value: &'a T,
    prev: Option<&'a Args<'a>>,
}
pub fn arg<'a, T: 'a + fmt::Display + ?Sized>(name: &'a str, value: &'a T) -> Arg<'a, T> {
    Arg {
        name: name,
        value: value,
        prev: None,
    }
}
pub trait Args<'a> {
    fn arg<T: 'a + fmt::Display + ?Sized>(&'a self, name: &'a str, value: &'a T) -> Arg<'a, T>
        where Self: Sized
    {
        Arg {
            name: name,
            value: value,
            prev: Some(self),
        }
<std macros>:3:11: 3:36 error: cannot infer an appropriate lifetime due to conflicting requirements [E0495]
<std macros>:3 print ! ( concat ! ( $ fmt , "\n" ) , $ ( $ arg ) * ) ) ;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<anon>:59:3: 59:30 note: in this expansion of println! (defined in <std macros>)
<anon>:59:24: 59:28 note: first, the lifetime cannot outlive the expression at 59:23...
<anon>:59   println!("Help! {}", args);
                                 ^~~~
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<anon>:59:3: 59:30 note: in this expansion of println! (defined in <std macros>)
<anon>:59:24: 59:28 note: ...so that auto-reference is valid at the time of borrow
<anon>:59   println!("Help! {}", args);
                                 ^~~~
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<anon>:59:3: 59:30 note: in this expansion of println! (defined in <std macros>)
<std macros>:3:11: 3:36 note: but, the lifetime must be valid for the match at 3:10...
<std macros>:3 print ! ( concat ! ( $ fmt , "\n" ) , $ ( $ arg ) * ) ) ;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<anon>:59:3: 59:30 note: in this expansion of println! (defined in <std macros>)
<anon>:1:1: 1:1 note: ...so that variable is valid at time of its declaration
<anon>:1 use std::fmt;
         ^
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
<anon>:59:3: 59:30 note: in this expansion of println! (defined in <std macros>)
error: aborting due to previous error
playpen: application terminated with error code 101
Compilation failed.
```

The fix as described by @kimundi on IRC:

> <kimundi> brucem: found the issue
> <kimundi> `impl<'a> fmt::Display for Args<'a> {`
> <kimundi> this implements for trait object `Args`
> <kimundi> BUT!, trait objects have a lifetime bound for the type behind them, and if it is elided it defaults to `'static`
> <kimundi> so you actually had
> <kimundi> `impl<'a> fmt::Display for Args<'a> + 'static {`
> <kimundi> In other words, the `fmt::Display` impl is only applicable if the type `Args<'a>` has a `'static` bound
> <kimundi> `fn dbg(args: &(Args+'static)) {` would have also fixed it, but then the call to `dbg()` would complain
> <kimundi> The real fix is `impl<'a, 'b> fmt::Display for Args<'a> + 'b {`

**Comment by leodasvacas** [comment] 2017-01-29 18:09
Triage: Errors in macro expansion are now shown in call site so the original example is no longer valid and this is mostly a dupe of #29849 so this should be closed.

**Comment by steveklabnik** [comment] 2017-01-30 19:35
Closing as duplicate. Thanks!

**Closed by steveklabnik** 2017-01-30 19:35 UTC
Labels: A-diagnostics
