### ISSUE TITLE
Bad syntax in macro_rules! macro definition causes an ICE in beta and nightly, but not stable

### ISSUE THREAD

**Issue by niconii** [rust-lang/rust#30669] opened 2016-01-01 05:38 UTC
[This code](http://is.gd/rmExrn):
```rust
macro_rules! foo {
    $($t:tt)* => (1);
}

fn main() {
    foo!();
}
```
gives the following error on 1.5 stable (which is correct, though where it points is perhaps a little odd):
```
<anon>:6:5: 6:12 error: malformed macro lhs
<anon>:6     foo!();
             ^~~~~~~
```
but this error on 1.6 beta and the current nightly:
```
<anon>:6:5: 6:12 error: internal compiler error: malformed macro lhs
<anon>:6     foo!();
             ^~~~~~~
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', ../src/libsyntax/diagnostic.rs:175
```

**Comment by jonas-schievink** [comment] 2016-01-01 14:44
The culprit seems to be cce7b8bd25484a882a2be5472d6a2aadd84e9539, which changes the check from `span_fatal` to `span_bug`

cc @sanxiyn

**Comment by GuillaumeGomez** [comment] 2016-01-04 20:22
I'll take a look if no one is on it.

**Comment by Sean1708** [comment] 2016-01-05 14:33
Possibly related, [this code](http://is.gd/jxf5uC) causes an ICE on nightly, but not on beta or stable.

**Comment by jonas-schievink** [comment] 2016-01-05 14:35
@Sean1708 Looks like a different bug to me

**Comment by Sean1708** [comment] 2016-01-05 14:37
@jonas-schievink Thanks, I'll open a new issue then.

**Comment by brson** [comment] 2016-01-07 22:41
@Sean1708 When you do can you link it from here? It needs to be tagged as a regression.

**Comment by jonas-schievink** [comment] 2016-01-07 22:44
@brson It was #30715, which was already fixed in #30723

**Comment by GuillaumeGomez** [comment] 2016-01-07 22:56
@jonas-schievink: I just fixed the regression and added a test, not the supposed improvement.

**Comment by brson** [comment] 2016-01-08 19:15
Thanks @GuillaumeGomez!

**Comment by brson** [comment] 2016-01-08 19:16
Oh, wait, this hasn't been backported yet. I'll leave it open a bit.

**Comment by nikomatsakis** [comment] 2016-02-04 21:15
What precisely should be backported here? I cant' figure out through all the comments :)

**Comment by nikomatsakis** [comment] 2016-02-04 21:16
Seems like #30708 has been backported?

**Comment by nikomatsakis** [comment] 2016-02-04 21:18
(In https://github.com/rust-lang/rust/issues/30853.)

So I think we can close?

**Comment by GuillaumeGomez** [comment] 2016-02-04 21:20
@nikomatsakis: I think as well. The purpose here was to fix the regression, which is done. Unless @brson has another reason?

**Closed** 2016-02-05 23:47 UTC
Labels: A-macros, regression-from-stable-to-beta
