### ISSUE TITLE
rustdoc: Show methods from the whole Deref/DerefMut chain instead of only one level

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#71640] opened 2020-04-28 14:06 UTC
See for example https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer/message/struct.Message.html#deref-methods.

The type it derefs to also has another deref impl that would be useful to include here, see https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer/miniobject/struct.GstRc.html#impl-Deref .

In this case the expected result would be that the methods of both `GstRc` and `MessageRef` would be shown in the docs of `Message`.

CC @GuillaumeGomez @kinnison @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment] 2020-04-28 14:08
I think that all non-direct elements should be listed with no docs and just a link to their original items' page. Just adding a title before them to say that they come from the deref type.

What do you think?

**Comment by sdroege** [comment] 2020-04-28 14:10
Non-direct meaning that also e.g. the docs of `Vec<T>` wouldn't show the methods from `&[T]` anymore? IMHO it would make sense to show all levels. Can't become much longer than the docs of `Vec<T>` right now already :)

**Comment by kinnison** [comment] 2020-04-28 19:37
One option would be to show the direct deref target as we do now, and pre-collapsed indirect deref targets all the way down.

**Comment by Nemo157** [comment] 2020-05-25 08:46
Dup of https://github.com/rust-lang/rust/issues/53038 and https://github.com/rust-lang/rust/issues/26207

**Comment by jyn514** [comment] 2021-01-03 15:55
Duplicate of https://github.com/rust-lang/rust/issues/26207.

**Closed by jyn514** 2021-01-03 15:55 UTC
Labels: C-enhancement, T-rustdoc
