### ISSUE TITLE
ICE on 1.26.0-nightly (29f5c699b 2018-02-27)

### ISSUE THREAD

**Issue by martinlindhe** [rust-lang/rust#48601] opened 2018-02-28 01:40 UTC
tried compile a toy project that ran fine with nightly from Feb 8

## Meta

```
rustc 1.26.0-nightly (29f5c699b 2018-02-27)
binary: rustc
commit-hash: 29f5c699b11a6a148f097f82eaa05202f8799bbc
commit-date: 2018-02-27
host: x86_64-apple-darwin
release: 1.26.0-nightly
LLVM version: 6.0
```

Backtrace:

```
$ RUST_BACKTRACE=full cargo run
   Compiling cgmath v0.14.1
   Compiling gfx_core v0.8.2
   Compiling cocoa v0.9.2
   Compiling image v0.18.0
   Compiling piston2d-drag_controller v0.21.0
   Compiling piston-ai_behavior v0.22.0
   Compiling pistoncore-window v0.30.0
   Compiling camera_controllers v0.23.0
   Compiling gl v0.7.0
   Compiling gfx_gl v0.4.0
   Compiling gleam v0.4.20
   Compiling pistoncore-event_loop v0.35.0
   Compiling piston2d-sprite v0.41.0
   Compiling piston v0.35.0
thread 'rustc' panicked at 'assertion failed: `(left != right)`
  left: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([S, S]), item_def_id: DefId(2/0:885 ~ core[57bc]::ops[0]::arith[0]::Add[0]::Output[0]) }, S)))`,
 right: `ParamEnv(Binder(ProjectionPredicate(ProjectionTy { substs: Slice([S, S]), item_def_id: DefId(2/0:885 ~ core[57bc]::ops[0]::arith[0]::Add[0]::Output[0]) }, S)))`', librustc/traits/project.rs:146:17
stack backtrace:
   0:        0x1056902e3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hb6f8d0aeb0f47560
   1:        0x105687a52 - std::sys_common::backtrace::_print::h1b3826a3b2f8d3a0
   2:        0x10568d0cd - std::panicking::default_hook::{{closure}}::h80eddd6b117c6636
   3:        0x10568cd58 - std::panicking::default_hook::h85ae65f26641d43e
   4:        0x103c7ae50 - core::ops::function::Fn::call::hf9b1b53f8b573479
   5:        0x10568d590 - std::panicking::rust_panic_with_hook::h8542d5e1bb0b8b72
   6:        0x10568d38a - std::panicking::begin_panic_fmt::hc2da8703f849b9fe
   7:        0x103fa814f - rustc::traits::project::ProjectionTyCandidateSet::push_candidate::h1467863ec6a3b6c9
   8:        0x103facd09 - rustc::traits::project::opt_normalize_projection_type::h4a7d3508be9054da
   9:        0x103fa8652 - rustc::traits::project::poly_project_and_unify_type::{{closure}}::h927c895dc0422f62
  10:        0x103fa8246 - rustc::traits::project::poly_project_and_unify_type::h03d7597eec6d2c11
  11:        0x103fa5d23 - <rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation::hb553c4c52aa43526
  12:        0x103fa4b78 - rustc::traits::fulfill::FulfillmentContext::select::h5fc9a48b16ed05a5
  13:        0x103fa3b76 - rustc::traits::fulfill::FulfillmentContext::select_all_or_error::h270cf226427decd6
  14:        0x102f325f0 - rustc_typeck::check::compare_method::compare_predicate_entailment::h921f14ea7dc5fdb7
  15:        0x102f50622 - rustc_typeck::check::check_impl_items_against_trait::h7cc96a5312c75037
  16:        0x102f49adf - rustc_typeck::check::check_item_type::hd47e2157a1a13f54
  17:        0x102f94bfc - rustc_typeck::check_crate::{{closure}}::h228b8b03d3995d3d
  18:        0x102f90382 - rustc_typeck::check_crate::h669063c9d654e7a5
  19:        0x10292b414 - rustc::ty::context::TyCtxt::create_and_enter::h8717108c733d64e7
  20:        0x1029968e2 - rustc_driver::driver::compile_input::h181a45f93f81cbc6
  21:        0x1029b282e - rustc_driver::run_compiler::hac7bf7fe110e8411
  22:        0x1028dd045 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9ea79736da67733b
  23:        0x1056a7ffe - __rust_maybe_catch_panic
  24:        0x102918705 - <F as alloc::boxed::FnBox<A>>::call_box::h5dc7c132865c823c
  25:        0x10569cd7b - std::sys::unix::thread::Thread::new::thread_start::h0bcb80c1fa3bebdb
  26:     0x7fff588e86c0 - _pthread_body
  27:     0x7fff588e856c - _pthread_start

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.26.0-nightly (29f5c699b 2018-02-27) running on x86_64-apple-darwin

error: Could not compile `cgmath`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by martinlindhe** [comment] 2018-02-28 01:56
Both sides of the failing assert seems equal to me, which is weird.

Also, forgot to mention the code compiles and runs as expected on stable channel.

**Comment by shssoichiro** [comment] 2018-02-28 03:11
Duplicate of #48551. Should be fixed in the next nightly.

**Closed** 2018-02-28 03:24 UTC
Labels: A-traits, I-ICE, regression-from-stable-to-nightly
