### ISSUE TITLE
TRPL 2nd Edition, Chapter 14.3 (Cargo Workspaces) - add-one

### ISSUE THREAD

**Issue by vozeldr** [rust-lang/rust#46491] opened 2017-12-04 13:11 UTC
I think this issue should be labeled A-Book

While following through this chapter on Windows 10, using add-one (with a hyphen) would not work for me. I had to change it to use underscores in the folder and package names for some reason.

```
$ cargo build
   Compiling add-one v0.1.0 (file:///C:/src/playground/rust_workspaces/add-one)
   Compiling rust_workspaces v0.1.0 (file:///C:/src/playground/rust_workspaces)
error: expected one of `;` or `as`, found `-`
 --> src\main.rs:1:17
  |
1 | extern crate add-one;
  |                 ^ expected one of `;` or `as` here
```

**Comment by kennytm** [comment] 2017-12-04 13:31
Hi, book issues should be filed to https://github.com/rust-lang/book/issues.

A hyphen cannot be used in an `extern crate` statement because `add-one` is not a single identifier, but the word "add", followed by a minus sign, followed by "one". Because of this, cargo will replace all `-` with `_` when used as a crate name. [This is by design](https://github.com/nox/rust-rfcs/blob/master/text/0940-hyphens-considered-harmful.md). 

Therefore, the compilation error of `extern crate add-one;` is expected, though the book may need a short paragraph explaining why the package is named `add-one` but imported as `add_one`.

Closing as out-of-scope.

**Closed by kennytm** 2017-12-04 13:31 UTC
