### ISSUE TITLE
rustc fails to compile when -L /usr/local/lib (on Linux, at least)

### ISSUE THREAD

**Issue by rrichardson** [rust-lang/rust#20342] opened 2014-12-30 19:14 UTC
rust-bindgen sets cargo:rustc -L to /usr/local/lib via build.rs  

When this happens, linking fails because duplicate candidate dylibs are found in the bootstrap libs: (/usr/local/lib) and the rustlib (/usr/local/lib/rustlib/../lib) 

Specific errors below:

**Comment by jmesmon** [comment] 2015-08-05 15:32
I've run into this same issue in meta-rust: https://github.com/jmesmon/meta-rust/issues/6 (and it's recently caused me issues again).

Causes build failures for me fairly often, as bitbake likes to rebuild things that are already installed sometimes.

As I mentioned in #19767, using prioritization of paths passed to the compiler (rather than searching all of them) is an easy fix for this.

Adding a "compiler hash" will not fix things for my case as I require builds to be reproducible (randomness is a problem) and in some cases will be rebuilding the same exact compiler.

**Comment by brson** [comment] 2016-06-27 22:48
Still seems to be an issue. Adding `-L` prioritization would fix it. @alexcrichton does prioritizing `-L` make sense to you still?

**Comment by alexcrichton** [comment] 2016-06-27 23:55
@brson could you elaborate on what you mean by prioritization? Do you mean that if we hit multiple candidates we just pick the first one?

**Comment by brson** [comment] 2016-06-28 00:51
@alexchricton crates loaded from later `-L` directories win over crates loaded from earlier `-L` directories.

**Comment by jmesmon** [comment] 2016-06-28 14:43
@brson I don't think that order solves things. I'd recommend searching in the order that the `-L` options are added instead. This both matches with how `ld` works and allows us to keep using the target rust libs instead of accidentally linking in the host rust libs.

**Comment by alexcrichton** [comment] 2016-06-28 17:06
Hm it's certainly a possibility, yes. I've personally always found it to be a bug whenever this check trips and am generally glad it trips, but it has been annoying from time to time.

**Comment by brson** [comment] 2016-06-28 17:33
> This both matches with how ld works and allows us to keep using the target rust libs instead of accidentally linking in the host rust libs.

Thanks for the correction.

**Comment by steveklabnik** [comment] 2018-12-10 18:50
Triage: has anyone seen this since 2016?

**Comment by jyn514** [comment] 2022-06-27 04:51
Triage: this is working today:
```
$ rustc build.rs -L $(rustc --print sysroot)/lib
$ file build
build: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=6deeda9153facaf71b74025e6759bbad4614ba4e, for GNU/Linux 3.2.0, with debug_info, not stripped
```
Looks like rustc_metadata now arbitrarily picks one of the two since they have the same crate hash:
```
 INFO rustc_metadata::creader resolving crate `std`
 INFO rustc_metadata::creader falling back to a load
 INFO rustc_metadata::locator lib candidate: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.so
 INFO rustc_metadata::locator lib candidate: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-061c02acc74ada37.rlib
 INFO rustc_metadata::locator lib candidate: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.rlib
 INFO rustc_metadata::locator lib candidate: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.so
 INFO rustc_metadata::locator rlib reading metadata from: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.rlib
 INFO rustc_metadata::locator dylib reading metadata from: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.so
 INFO rustc_metadata::locator dylib reading metadata from: /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.so
 INFO rustc_metadata::creader register crate `std` (cnum = 1. private_dep = false)
```

**Closed by jyn514** 2022-06-27 04:51 UTC
Labels: A-linkage, A-rustbuild, C-bug
