### ISSUE TITLE
[ICE] LLVM error: Instruction does not dominate all uses

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rust#30451] opened 2015-12-17 23:30 UTC
Attempting to build [uutils/coreutils](https://github.com/uutils/coreutils/commit/328597334b26d476cff6b7c3a1d9557003334a8c) on OSX.11.1 for x86_64-apple-darwin with `rustc 1.7.0-nightly (110df043b 2015-12-13)` sees the following unusual error:

```llvm
rustc src/fmt/main.rs --crate-name fmt --crate-type bin -C opt-level=3 -C lto --out-dir /Users/alex/GitHub/coreutils/target/release/deps --emit=dep-info,link -L dependency=/Users/alex/GitHub/coreutils/target/release/deps -L dependency=/Users/alex/GitHub/coreutils/target/release/deps --extern uucore=/Users/alex/GitHub/coreutils/target/release/deps/libuucore-06f907898dfc427e.rlib --extern getopts=/Users/alex/GitHub/coreutils/target/release/deps/libgetopts-852fe11dd444cf81.rlib --extern unicode_width=/Users/alex/GitHub/coreutils/target/release/deps/libunicode_width-97d72792528d9733.rlib --extern libc=/Users/alex/GitHub/coreutils/target/release/deps/liblibc-e1ce3d27f1683fe3.rlib --extern uu_fmt=/Users/alex/GitHub/coreutils/target/release/deps/libuu_fmt-972a1cedb42cfd9a.rlib --verbose
Instruction does not dominate all uses!
  %oldret2 = insertvalue %str_slice %oldret, i64 %newret1, 1
  %.sink.i.i = phi %str_slice [ %oldret2, %"_ZN6string13_$LT$impl$GT$5index20heceb03ca720936cc74fE.exit.i.i" ], [ %oldret6, %"_ZN6string13_$LT$impl$GT$5index20heceb03ca720936cc74fE.exit63.i.i" ]
Instruction does not dominate all uses!
  %oldret6 = insertvalue %str_slice %oldret4, i64 %newret5, 1
  %.sink.i.i = phi %str_slice [ %oldret2, %"_ZN6string13_$LT$impl$GT$5index20heceb03ca720936cc74fE.exit.i.i" ], [ %oldret6, %"_ZN6string13_$LT$impl$GT$5index20heceb03ca720936cc74fE.exit63.i.i" ]
Instruction does not dominate all uses!
  %123 = invoke fastcc { i8*, i64 } @"_ZN3str13_$LT$impl$GT$9trim_left20hb60f33d6a3043710VefE"(i8* noalias nonnull readonly %.pre-phi.i.i.60.i.i, i64 %122)
          to label %join5.i.i unwind label %unwind_ast_3343_.loopexit.split-lp.i
  %newret3 = extractvalue { i8*, i64 } %123, 0
Instruction does not dominate all uses!
  %123 = invoke fastcc { i8*, i64 } @"_ZN3str13_$LT$impl$GT$9trim_left20hb60f33d6a3043710VefE"(i8* noalias nonnull readonly %.pre-phi.i.i.60.i.i, i64 %122)
          to label %join5.i.i unwind label %unwind_ast_3343_.loopexit.split-lp.i
  %newret5 = extractvalue { i8*, i64 } %123, 1
Instruction does not dominate all uses!
  %114 = invoke fastcc { i8*, i64 } @"_ZN3str13_$LT$impl$GT$9trim_left20hb60f33d6a3043710VefE"(i8* noalias nonnull readonly %.pre-phi.i.i.i.i, i64 %113)
          to label %join5.i.i unwind label %unwind_ast_3343_.loopexit.split-lp.i
  %newret = extractvalue { i8*, i64 } %114, 0
Instruction does not dominate all uses!
  %114 = invoke fastcc { i8*, i64 } @"_ZN3str13_$LT$impl$GT$9trim_left20hb60f33d6a3043710VefE"(i8* noalias nonnull readonly %.pre-phi.i.i.i.i, i64 %113)
          to label %join5.i.i unwind label %unwind_ast_3343_.loopexit.split-lp.i
  %newret1 = extractvalue { i8*, i64 } %114, 1
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by dotdash** [comment] 2015-12-18 02:25
Does this also happen without LTO?

**Comment by sanxiyn** [comment] 2015-12-18 07:22
This seems same as #28066. If so, it's an LLVM bug, and the fix landed upstream.

**Comment by alexchandel** [comment] 2015-12-18 21:12
@sanxiyn Can we update our LLVM then and test whether it's fixed?

**Comment by huonw** [comment] 2016-01-05 23:58
Closing as a dupe of #28066.

**Closed by huonw** 2016-01-05 23:58 UTC
Labels: I-ICE
