### ISSUE TITLE
Compiler panic

### ISSUE THREAD

**Issue by aleksander** [rust-lang/rust#32602] opened 2016-03-30 08:56 UTC
Compiler unexpected panic while compiling eventual v.0.1.5

## Meta:

`rustc --version --verbose`:

```
rustc 1.9.0-nightly (d5a91e695 2016-03-26)
binary: rustc
commit-hash: d5a91e69582b63f19192ad860df0f7a9a8530f56
commit-date: 2016-03-26
host: x86_64-unknown-linux-gnu
release: 1.9.0-nightly
```

Backtrace:

```
thread 'rustc' panicked at 'internal error: entered unreachable code: Unexpected tail in unsized_info_ty: usize for ty=process::Core<isize, isize, isize>', ../src/librustc_trans/type_of.rs:135
stack backtrace:
   1:     0x7f371c5f5300 - std::sys::backtrace::tracing::imp::write::h63529ecac330b5bc
   2:     0x7f371c6029db - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0e99487804ecdaa3
   3:     0x7f371c602577 - std::panicking::default_hook::h1f0a2403a716c4a6
   4:     0x7f371c5c62ff - std::sys_common::unwind::begin_unwind_inner::heae36551373e36bd
   5:     0x7f371c5c83e8 - std::sys_common::unwind::begin_unwind_fmt::hfdca93605af5caca
   6:     0x7f371b99536b - rustc_trans::type_of::unsized_info_ty::hea231a6642f86fa0
   7:     0x7f371b86272c - rustc_trans::type_of::sizing_type_of::h9809f855f7757d48
   8:     0x7f371b8b67c2 - rustc_trans::base::trans_crate::h5d7d0ab38cd208e7
   9:     0x7f371cb4d078 - rustc_driver::driver::phase_4_translate_to_llvm::hc60a4fd01d59eaae
  10:     0x7f371cb4b905 - rustc_driver::driver::compile_input::_$u7b$$u7b$closure$u7d$$u7d$::h96aedfca5f48d7d6
  11:     0x7f371cb484e8 - rustc_driver::driver::phase_3_run_analysis_passes::_$u7b$$u7b$closure$u7d$$u7d$::h1d5b5af335ae8126
  12:     0x7f371cb4249b - rustc::ty::context::TyCtxt::create_and_enter::h2656c85b5a638887
  13:     0x7f371cb3ef19 - rustc_driver::driver::phase_3_run_analysis_passes::h432eb92c0e12df32
  14:     0x7f371cb11807 - rustc_driver::driver::compile_input::hb8958b270f32a505
  15:     0x7f371caff324 - rustc_driver::run_compiler::h146dabfc96bf3a5a
  16:     0x7f371cafc8a1 - std::sys_common::unwind::try::try_fn::h847694ac14db1c2b
  17:     0x7f371c5f295b - __rust_try
  18:     0x7f371c5f28ed - std::sys_common::unwind::inner_try::h790ed072af125c7c
  19:     0x7f371cafd0ea - _<F as alloc..boxed..FnBox<A>>::call_box::h64418c3ccdc3072e
  20:     0x7f371c600ba4 - std::sys::thread::Thread::new::thread_start::hdaf9c8e3f2f1c46e
  21:     0x7f371475f423 - start_thread
  22:     0x7f371c25ecbc - clone
  23:                0x0 - <unknown>
```

**Comment by euclio** [comment] 2016-04-02 15:14
Duplicate of #32377.

**Closed** 2016-04-02 23:28 UTC
Labels: I-ICE
