### ISSUE TITLE
Placing constant expressions in statics can result in unnecessary huge memcpy's

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#28398] opened 2015-09-14 09:08 UTC
``` rust
pub enum MyEnum {
    A(u32),
    B([u8; 65536]),
}

pub fn slow(e: &mut MyEnum) {
    *e = MyEnum::A(32);
}

pub fn fast(e: &mut MyEnum, x: u32) {
    *e = MyEnum::A(x);
}
```

The optimised IR is:

``` llvm
; ModuleID = 'rust_out.0.rs'
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%MyEnum = type { i8, [3 x i8], [16384 x i32] }

@const746 = internal unnamed_addr constant { i8, i32, [65532 x i8] } { i8 0, i32 32, [65532 x i8] undef }

; Function Attrs: nounwind uwtable
define void @_ZN4slow20h2f035c1295a6ea67oaaE(%MyEnum* noalias nocapture dereferenceable(65540)) unnamed_addr #0 {
entry-block:
  %1 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 0
  tail call void @llvm.memcpy.p0i8.p0i8.i64(i8* %1, i8* getelementptr inbounds ({ i8, i32, [65532 x i8] }, { i8, i32, [65532 x i8] }* @const746, i64 0, i32 0), i64 65540, i32 4, i1 false)
  ret void
}

; Function Attrs: nounwind
declare void @llvm.memcpy.p0i8.p0i8.i64(i8* nocapture, i8* nocapture readonly, i64, i32, i1) unnamed_addr #1

; Function Attrs: nounwind uwtable
define void @_ZN4fast20h4b4f8c2fd333501fCaaE(%MyEnum* noalias nocapture dereferenceable(65540), i32) unnamed_addr #0 {
entry-block:
  %2 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 0
  store i8 0, i8* %2, align 4
  %3 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 2, i64 0
  store i32 %1, i32* %3, align 4
  ret void
}

attributes #0 = { nounwind uwtable "split-stack" }
attributes #1 = { nounwind "split-stack" }
```

i.e. `slow` does a 64K memcpy, while `fast` does two small stores.

Presumably caused by:
- https://github.com/rust-lang/rust/blob/4d6dc7f9ba9fe61e38d737b29bfe490e835f6921/src/librustc_trans/trans/expr.rs#L135
- https://github.com/rust-lang/rust/blob/4d6dc7f9ba9fe61e38d737b29bfe490e835f6921/src/librustc_trans/trans/expr.rs#L223

(Noticed in https://users.rust-lang.org/t/setting-a-4-byte-enum-variant-results-in-a-64k-memcopy/2858 .)

**Comment by arielb1** [comment] 2015-09-14 11:26
We probably need some heuristic here - if the data is truly big, we should memcpy it completely rather than skipping fragments. Maybe we should find a partialmemcpy intrinsic in LLVM?

**Comment by huonw** [comment] 2015-09-14 12:05
Could you clarify what you mean? The IR in the issue has a single memcpy with no skipped fragments.

**Comment by arielb1** [comment] 2015-09-14 18:29
@huonw 

In the example, we want to do
```C
    char *buf = e;
    buf[0]  = 0;
    *(uint32_t*)(buf+4) = 32;
```

This sets bytes 0, 4, 5, 6, and 7.

If, instead, we had
```
pub fn slow_2(e: &mut (MyEnum, u32)) {
    *e = (MyEnum::A(32), 42);
}
```
we would want to set bytes 0, 4, 5, 6, 7, 65540, 65541, 65542, and 65543. In LLVM terms, we set the other bytes to undefs (this makes LLVM leave them as they were before). It would be nice if we could tell LLVM that and have it find the best lowering strategy.

**Comment by huonw** [comment] 2015-09-15 03:35
Ah, I think my confusion is because your initial comment inverted partial and complete?

In any case, note that the dynamic case *does* what you are suggesting---just set specific fields---while the static case is explicitly creating a whole static instance and then assigning it to the local (i.e. doing a memcpy). Are you just saying that our assignments/loads in general should be more precise about what bytes they copy?

**Comment by pmarcelll** [comment] 2017-03-05 15:32
Triage: this is the current output from the playground (stable, release mode):
 ```llvm
; ModuleID = 'rust_out.cgu-0.rs'
source_filename = "rust_out.cgu-0.rs"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%MyEnum = type { i8, [3 x i8], [16384 x i32] }

; Function Attrs: norecurse nounwind uwtable
define void @_ZN8rust_out4slow17h69b71af2db2df8c0E(%MyEnum* nocapture dereferenceable(65540)) unnamed_addr #0 {
entry-block:
  %1 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 0
  store i8 0, i8* %1, align 1
  %2 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 2, i64 0
  store i32 32, i32* %2, align 4
  ret void
}

; Function Attrs: norecurse nounwind uwtable
define void @_ZN8rust_out4fast17hd831faf6e2383adeE(%MyEnum* nocapture dereferenceable(65540), i32) unnamed_addr #0 {
entry-block:
  %2 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 0
  store i8 0, i8* %2, align 1
  %3 = getelementptr inbounds %MyEnum, %MyEnum* %0, i64 0, i32 2, i64 0
  store i32 %1, i32* %3, align 4
  ret void
}

attributes #0 = { norecurse nounwind uwtable }
```

The memcopy disappeared.

**Comment by Mark-Simulacrum** [comment] 2017-05-26 23:37
I'm going to close as fixed since it seems this is now fixed -- the IR is identical for both slow and fast, and neither case has a memcpy. If that's incorrect, please provide a reproducible example.

**Closed by Mark-Simulacrum** 2017-05-26 23:37 UTC
Labels: A-codegen, I-slow, T-compiler
