### ISSUE TITLE
Are floats really dependency free?

### ISSUE THREAD

**Issue by xaviershay** [rust-lang/rust#29390] opened 2015-10-27 03:52 UTC
As mentioned in http://blog.phil-opp.com/rust-os/setup-rust.html

> The core library is added implicitly when using #![no_std] and provides basic standard library features like Option or Iterator. According to the documentation it is “dependency-free”. But it actually has some dependencies, for example on fmod and fmodf.

This strikes me as a bug, either in the core library or in the documentation.

Previously reported at https://github.com/phil-opp/phil-opp.github.io/issues/7, moving here.

**Comment by huonw** [comment] 2015-10-27 04:06
This is a dupe of https://github.com/rust-lang/rust/issues/27200 (and somewhat related to https://github.com/rust-lang/rust/issues/27701 and https://github.com/rust-lang/rust/issues/26449).

Thanks for filing!

**Closed by huonw** 2015-10-27 04:06 UTC

**Comment by alexcrichton** [comment] 2015-10-27 06:10
In general, however, I don't necessarily consider `fmod` and `fmodf` as dependencies of libcore that need to be worried about. Linking with `--gc-sections` will eliminate them and otherwise you still have to deal with basic dependencies like `memcpy` and `memmove`, so having a few small "very well known" functions being unimplemented I think is fine (although they should obviously be minimized where possible).

If we could I'd love to only provide `Div`/`Rem` on floats in the standard library, but coherence forces our hand of putting them in libcore, and it's not necessarily the end of the world.

**Comment by steveklabnik** [comment] 2015-10-27 12:38
I'm still not sure that we should describe `libcore` as 'dependency free' if there are dependencies, though. Shouldn't that be a doc issue?
