### ISSUE TITLE
there should be warning or error when mutating const

### ISSUE THREAD

**Issue by abbychau** [rust-lang/rust#59307] opened 2019-03-20 06:18 UTC
https://gist.github.com/08f01df0252e9fa272ad5dd0e4bb70e7

please refer to `S.x += 1;` to the above code.

**Comment by petrochenkov** [comment] 2019-03-20 07:08
Similar issues - https://github.com/rust-lang/rust-clippy/issues/829, https://github.com/rust-lang/rust/issues/55721, https://github.com/rust-lang/rust/issues/40543

**Comment by jonas-schievink** [comment] 2019-03-20 10:13
Seems like a duplicate of https://github.com/rust-lang/rust/issues/55721

**Closed** 2019-03-20 12:52 UTC
