### ISSUE TITLE
Incorrect dead-code-warning on enum when using Self

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rust#69018] opened 2020-02-10 13:02 UTC
The following code produces an incorrect dead code warning ("warning: variant is never constructed: `Variant`"), when using the `Self` keyword. When using the enumeration name (`E`), there is no warning.
```rust
// rustc --edition 2018 --crate-type rlib warning.rs
enum E {
    Variant { _unused: () }
}
impl E {
    fn new() -> Self {
        Self::Variant { _unused: () }
        // E::Variant { _unused: () } // <-- warning vanishes
    }
}
 
pub struct S(E);
impl S {
    pub fn new() -> Self {
        Self(E::new())
    }
}
```

Tested versions:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
rustc 1.42.0-nightly (212b2c7da 2020-01-30)
rustc 1.43.0-nightly (58b834344 2020-02-05)
```

This issue has been assigned to @matprec via [this comment](https://github.com/rust-lang/rust/issues/69018#issuecomment-584134027).

**Comment by Lonami** [comment] 2020-02-10 14:09
Possible duplicate of # #64362.

**Comment by davidvartan** [comment] 2020-04-24 18:29
Seeing this as well (warning occurs with `Self::`, does not occur when name of enum is used.)

**Comment by Lonami** [comment] 2020-04-24 19:13
Looks like #71026 fixed it, I can't reproduce the issue in the current Nightly.

**Closed** 2020-08-05 17:33 UTC
Labels: A-lint, C-bug, T-compiler
