### ISSUE TITLE
panic when building docs of input.rs

### ISSUE THREAD

**Issue by cmeissl** [rust-lang/rust#108091] opened 2023-02-15 18:03 UTC
### Code

Building docs of [input.rs](https://github.com/Smithay/input.rs) on nightly panics

```sh
cargo +nightly doc
```

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0-nightly (0416b1a6f 2023-02-14)
binary: rustc
commit-hash: 0416b1a6f6d5c42696494e1a3a33580fd3f669d8
commit-date: 2023-02-14
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Error output

```
thread 'rustc' panicked at 'no resolution for "x" MacroNS DefId(0:0 ~ input_sys[5956])', src/librustdoc/passes/collect_intra_doc_links.rs:391:32
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0:     0x7f497d16a9ea - std::backtrace_rs::backtrace::libunwind::trace::hbdb546ca92cb6d78
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f497d16a9ea - std::backtrace_rs::backtrace::trace_unsynchronized::hc6fce42db22bfc5e
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f497d16a9ea - std::sys_common::backtrace::_print_fmt::h81df7bc0b23e5237
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f497d16a9ea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc59be13e437abc01
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f497d1caafe - core::fmt::write::h52ae72821e51c26c
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f497d15b005 - std::io::Write::write_fmt::hd87c8dd79580982c
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/io/mod.rs:1684:15
   6:     0x7f497d16a7b5 - std::sys_common::backtrace::_print::h20f47bfc31ead101
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f497d16a7b5 - std::sys_common::backtrace::print::ha898201a02f1983d
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f497d16d54f - std::panicking::default_hook::{{closure}}::h53f82cfee6bbc6bc
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:267:22
   9:     0x7f497d16d28b - std::panicking::default_hook::ha6709b03b61260ba
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:286:9
  10:     0x7f49804c9e94 - <rustc_driver_impl[e0927287439ac92b]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[a4f442881c2ef06d]::ops::function::FnOnce<(&core[a4f442881c2ef06d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f497d16dd8a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2eed0239097b069b
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:2002:9
  12:     0x7f497d16dd8a - std::panicking::rust_panic_with_hook::h1feda37d03dc2311
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:692:13
  13:     0x7f497d16db09 - std::panicking::begin_panic_handler::{{closure}}::h04d1fa7b2fbcb101
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:579:13
  14:     0x7f497d16ae8c - std::sys_common::backtrace::__rust_end_short_backtrace::hd635f2032b0cab87
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f497d16d812 - rust_begin_unwind
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:575:5
  16:     0x7f497d1c74a3 - core::panicking::panic_fmt::h5d8c50f99f6f87ff
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/core/src/panicking.rs:64:14
  17:     0x55d2d16c0cec - <rustdoc[8533c19cc74d22c1]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  18:     0x55d2d16c0e8f - <rustdoc[8533c19cc74d22c1]::passes::collect_intra_doc_links::LinkCollector>::resolve
  19:     0x55d2d16c59d9 - <rustdoc[8533c19cc74d22c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[8533c19cc74d22c1]::visit::DocVisitor>::visit_item
  20:     0x55d2d16cf28a - <rustdoc[8533c19cc74d22c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[8533c19cc74d22c1]::visit::DocVisitor>::visit_inner_recur
  21:     0x55d2d16c8784 - <rustdoc[8533c19cc74d22c1]::passes::collect_intra_doc_links::LinkCollector as rustdoc[8533c19cc74d22c1]::visit::DocVisitor>::visit_item
  22:     0x55d2d16bf83f - rustdoc[8533c19cc74d22c1]::passes::collect_intra_doc_links::collect_intra_doc_links
  23:     0x55d2d1681dee - <rustc_session[5f5732a9ce5d58bc]::session::Session>::time::<rustdoc[8533c19cc74d22c1]::clean::types::Crate, rustdoc[8533c19cc74d22c1]::core::run_global_ctxt::{closure#7}>
  24:     0x55d2d174812c - rustdoc[8533c19cc74d22c1]::core::run_global_ctxt
  25:     0x55d2d1682079 - <rustc_session[5f5732a9ce5d58bc]::session::Session>::time::<(rustdoc[8533c19cc74d22c1]::clean::types::Crate, rustdoc[8533c19cc74d22c1]::config::RenderOptions, rustdoc[8533c19cc74d22c1]::formats::cache::Cache), rustdoc[8533c19cc74d22c1]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  26:     0x55d2d14d1377 - <rustc_middle[db7416be43adeac6]::ty::context::GlobalCtxt>::enter::<rustdoc[8533c19cc74d22c1]::main_args::{closure#1}::{closure#0}::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>
  27:     0x55d2d1441e81 - <rustc_interface[da2bca27cf188e3c]::interface::Compiler>::enter::<rustdoc[8533c19cc74d22c1]::main_args::{closure#1}::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>
  28:     0x55d2d168138b - rustc_span[b67a18860b098bfc]::with_source_map::<core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>, rustc_interface[da2bca27cf188e3c]::interface::run_compiler<core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>, rustdoc[8533c19cc74d22c1]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  29:     0x55d2d15d7782 - <scoped_tls[7e7c0fc199c1fd10]::ScopedKey<rustc_span[b67a18860b098bfc]::SessionGlobals>>::set::<rustc_interface[da2bca27cf188e3c]::interface::run_compiler<core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>, rustdoc[8533c19cc74d22c1]::main_args::{closure#1}>::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>
  30:     0x55d2d1657870 - std[c4719229b53c8129]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[da2bca27cf188e3c]::util::run_in_thread_pool_with_globals<rustc_interface[da2bca27cf188e3c]::interface::run_compiler<core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>, rustdoc[8533c19cc74d22c1]::main_args::{closure#1}>::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>
  31:     0x55d2d176f53f - <<std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_<rustc_interface[da2bca27cf188e3c]::util::run_in_thread_pool_with_globals<rustc_interface[da2bca27cf188e3c]::interface::run_compiler<core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>, rustdoc[8533c19cc74d22c1]::main_args::{closure#1}>::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[a4f442881c2ef06d]::result::Result<(), rustc_errors[138a5dc35f5b9460]::ErrorGuaranteed>>::{closure#1} as core[a4f442881c2ef06d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  32:     0x7f497d177d23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h16d50f6a791b9ecf
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:1988:9
  33:     0x7f497d177d23 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcb8a06476f463180
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:1988:9
  34:     0x7f497d177d23 - std::sys::unix::thread::Thread::new::thread_start::hf9921b6eef74fae1
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys/unix/thread.rs:108:17
  35:     0x7f497cf1712d - start_thread
  36:     0x7f497cf98bc0 - clone3
  37:                0x0 - <unknown>
```

</p>
</details>

**Comment by megakorre** [comment] 2023-02-20 14:09
This no longer fails on latest nightly (2023-02-19)
Seems to have been fixed in https://github.com/rust-lang/rust/pull/108129 which fixed the reported issue: https://github.com/rust-lang/rust/issues/107995

**Comment by Enselic** [comment] 2024-05-20 18:40
Thanks. Closing as

Duplicate of https://github.com/rust-lang/rust/issues/107995

**Closed by Enselic** 2024-05-20 18:40 UTC
Labels: I-ICE, T-compiler, C-bug
