### ISSUE TITLE
Possible undefined value with advanced slice pattern

### ISSUE THREAD

**Issue by jorendorff** [rust-lang/rust#31271] opened 2016-01-28 21:34 UTC
#![feature(slice_patterns)]
    #![feature(advanced_slice_patterns)]
    
    fn main() {
        println!("{:?}",
            match [3, 4, 5] {
                [3, [x, y..]..] => (x, y),
                _ => panic!("fail")
            }
        );
    }

[In the Rust Playground](http://is.gd/LE93fR), outputs:

    (1970220846, [])

That doesn't seem right.

**Comment by bluss** [comment] 2016-01-29 02:03
Note: Only `feature(slice_patterns)` is needed for this testcase.

**Comment by bluss** [comment] 2016-01-29 02:04
This is a duplicate of #26158 *Nested slice pattern incorrectly considered irrefutable*

**Closed by bluss** 2016-01-29 02:04 UTC
