### ISSUE TITLE
Internal compiler error when compiling an example from "windows" crate

### ISSUE THREAD

**Issue by ancwrd1** [rust-lang/rust#82512] opened 2021-02-25 08:37 UTC
### Code

When building any of the examples from https://github.com/microsoft/windows-rs/tree/master/examples using cross compilation (from Linux to Windows x86_64-pc-windows-gnu target) the compiler panics.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0

```

### Error output

```
thread 'rustc' panicked at 'compiler/rustc_resolve/src/imports.rs:904:25: inconsistent resolution for an import', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/compiler/rustc_middle/src/util/bug.rs:34:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0 (cb75ad5db 2021-02-10) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=x86_64-w64-mingw32-gcc -C incremental -C link-args=-lstdc++ --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `windows_gen`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_middle::ty::context::tls::with_opt
   2: rustc_middle::util::bug::opt_span_bug_fmt
   3: rustc_middle::util::bug::span_bug_fmt
   4: rustc_resolve::imports::ImportResolver::finalize_import
   5: rustc_resolve::imports::ImportResolver::finalize_imports
   6: rustc_resolve::Resolver::resolve_crate
   7: rustc_interface::passes::configure_and_expand_inner
   8: rustc_interface::passes::configure_and_expand::{{closure}}
   9: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
  10: rustc_interface::passes::configure_and_expand
  11: rustc_interface::queries::Queries::expansion
  12: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  13: rustc_span::with_source_map
  14: rustc_interface::interface::create_compiler_and_run
```

</p>
</details>

**Comment by jonas-schievink** [comment] 2021-02-25 13:14
duplicate of https://github.com/rust-lang/rust/issues/56935

**Closed by jonas-schievink** 2021-02-25 13:14 UTC
Labels: C-bug, I-ICE, T-compiler
