### ISSUE TITLE
ICE with rls in rustc_save_analysis

### ISSUE THREAD

**Issue by yuyoyuppe** [rust-lang/rust#60557] opened 2019-05-05 11:18 UTC
Environment:
- VS Code 1.33.1
- `rustc 1.34.1 (fc50f328b 2019-04-24)
binary: rustc
commit-hash: fc50f328b0353b285421b8ff5d4100966387a997
commit-date: 2019-04-24
host: x86_64-pc-windows-msvc
release: 1.34.1
LLVM version: 8.0`
- stable channel(it also happens on nightly though)

Steps to reproduce:
- initialize new cargo package and add `syntect = "3.2"` to dependencies
- observe output from rls:
```
{"message":"src\\librustc\\ty\\context.rs:541: node_type: no type for node `expr <Self>::REGEX_OPTION_NONE (id=9237)`","code":null,"level":"error: internal compiler error","spans":[],"children":[],"rendered":"error: internal compiler error: src\\librustc\\ty\\context.rs:541: node_type: no type for node `expr <Self>::REGEX_OPTION_NONE (id=9237)`\n\n"}
thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:620:9
stack backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_predicate
   4: std::panicking::rust_panic_with_hook
   5: <rustc_errors::emitter::ColorConfig as core::fmt::Debug>::fmt
   6: rustc_errors::Handler::bug
   7: rustc::util::bug::bug_fmt
   8: rustc::ty::wf::object_region_bounds
   9: rustc::ty::wf::object_region_bounds
  10: rustc::ty::wf::object_region_bounds
  11: rustc::util::bug::bug_fmt
  12: rustc::util::bug::bug_fmt
  13: rustc::ty::context::TypeckTables::node_type
  14: rustc::ty::context::TypeckTables::expr_ty_adjusted
  15: rustc_save_analysis::SaveContext::get_expr_data
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <rustc_save_analysis::DumpHandler<'a> as rustc_save_analysis::SaveHandler>::save
  24: <env_logger::fmt::WriteStyle as core::default::Default>::default
  25: rustc_driver::enable_save_analysis
  26: rustc_driver::enable_save_analysis
  27: <env_logger::fmt::WriteStyle as core::default::Default>::default
  28: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  29: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  30: <env_logger::fmt::WriteStyle as core::default::Default>::default
  31: rustc_driver::driver::compile_input
  32: rustc_driver::run_compiler
  33: <rustc_driver::CompilationFailure as core::fmt::Debug>::fmt
  34: rustc_driver::run_compiler
  35: git_libgit2_opts
  36: git_libgit2_opts
  37: _rust_maybe_catch_panic
  38: git_libgit2_opts
  39: std::sys::windows::thread::Thread::new
  40: BaseThreadInitThunk
  41: RtlUserThreadStart
query stack during panic:
end of query stack
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}```

**Comment by jonas-schievink** [comment] 2019-05-05 11:20
Duplicate of https://github.com/rust-lang/rust/issues/59134

**Closed by jonas-schievink** 2019-05-05 11:20 UTC
