### ISSUE TITLE
[beta API Doc] Broken links in `fmt` module

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#30477] opened 2015-12-19 13:28 UTC
The formatting trait links are broken (except for `Display` and `UpperExp`): https://doc.rust-lang.org/nightly/std/fmt/#formatting-traits

**Update:** It seems like this was fixed on nighly. But the [beta docs](https://doc.rust-lang.org/beta/std/fmt/#formatting-traits) still have this issue.

And the link to `debug_struct` in the `core::Debug` doc seems broken, too: https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html#examples (source: https://doc.rust-lang.org/nightly/src/core/fmt/mod.rs.html#359)

**Comment by shahn** [comment] 2015-12-20 21:43
This is an issue that affects beta as well, looking for the cause/a fix.

**Comment by sfackler** [comment] 2015-12-20 22:19
This appears to be a rustdoc issue rather than a docs issue - documentation for all but two of the formatting traits have disappeared.

**Comment by petrochenkov** [comment] 2015-12-21 00:38
If something disappeared from the docs, then it may be related to https://github.com/rust-lang/rust/issues/30213

**Comment by phil-opp** [comment] 2015-12-23 23:15
It seems like the formatting trait links were fixed in nightly. But the beta docs still have this issue. I will update the description.

**Comment by steveklabnik** [comment] 2015-12-24 04:11
@brson @alexcrichton is this severe enough to justify a backport fix to beta? I'm not sure.

**Comment by sfackler** [comment] 2015-12-24 04:14
This seems like a case where we'd want to backport the fix, but does anyone know exactly what that is yet?

**Comment by brson** [comment] 2015-12-28 17:53
I'm ok backporting if somebody finds the fix.

**Comment by brson** [comment] 2016-01-06 21:13
Could do a bisection to figure out what patch fixed it on nightly.

**Comment by shahn** [comment] 2016-01-09 08:47
I'm running a bisect now, let me know if you've already started doing that and I'll stop. Otherwise if you want I can take this off of you.

**Comment by shahn** [comment] 2016-01-09 19:34
Hrm, since I cannot reproduce that nightly actually fixes this issue for me locally, I have to retract my offer of fixing this. Currently looking for someone who would be able to tell me how exactly the docs on rust-lang are built and deployed :/

**Comment by shahn** [comment] 2016-01-10 01:31
Ouch, this is annoying. Whether the files get built depends on configure arguments. Compiling the current nightly code with ./configure without --release-channel argument (default is dev) or using =beta means this bug is present, building it with --release-channel=nightly fixes it.

Building the current beta code with --release-channel=nightly also produces the files in std, which explains why my bisect attempts led to only "bad" commits. I'm currently bisecting between stable and beta, to figure out when using --release-channel=beta stopped producing the files.

**Comment by shahn** [comment] 2016-01-10 20:16
Ok, I'm not getting further here. The bisect gives non-deterministic results, at least in the way I'm doing my testing. This is what I did:

git checkout . && git clean -fdx && git submodule update
./configure --disable-valgrind --release-channel=beta && make -j8 doc
ls doc/std/fmt/trait.Octal.html

depending on the output of find (whether the file exists or not) I'm declaring a revision to be good or bad. But following this exact procedure, I have gotten both a "good" and a "bad" result for the commits 8bc43ed and 1099af7. I wonder if the current situation with beta being broken and nightly being fixed is mere coincidence.

**Comment by brson** [comment] 2016-01-11 23:32
So it might be that this bug is not fixed on nightly and it's just non-deterministic. @shahn was doing builds with -j so I wonder if parallelism is introducing something non-deterministic.

**Comment by shahn** [comment] 2016-01-12 18:38
I retried without -j now. I built the beta tag with --release-channel=beta for configure and a plain 'make'. Once I had the extra docs made. I ran the same thing again, they did not get created.

**Comment by shahn** [comment] 2016-01-12 18:49
Another observation, if they weren't built the first time even an explicit "make doc" does not build them

**Comment by Eljay** [comment] 2016-01-12 22:28
Seeing as this is seems to be a problem with the rustdoc binary, I tried bisecting by installing nightlies through multirust and running rustdoc on libstd manually. Each build seems deterministic by itself, but which files are omitted changes between builds (I don't understand why only `fmt` seems to be affected though).

It seems that everything is fine up until 2015-11-26 and then 2015-11-27 onwards is broken. So the problem is likely somewhere in the range 1805bba3...1727dee1. That includes #30043 though so there are quite a lot of changes.

**Closed** 2016-01-14 00:17 UTC
Labels: A-rustdoc, regression-from-stable-to-beta
