### ISSUE TITLE
Flash of dark theme in rustdoc

### ISSUE THREAD

**Issue by ruuda** [rust-lang/rust#50063] opened 2018-04-18 20:45 UTC
Currently, for every page I load on https://doc.rust-lang.org/std, there is a “flash of dark theme” for almost a second, as you can see in this timeline:

![flash-of-dark](https://user-images.githubusercontent.com/506953/38956821-074ada8e-4359-11e8-976d-b6eaf7b4a62d.png)

Furthermore, the entire docs load very slowly, even with a primed cache. (You can also see fonts kicking in very late.) I suspect part of the reason is that all resources are served with `cache-control: max-age=0, no-store, no-cache, must-revalidate`, including fonts and style sheets. I don’t know if this is done on purpose because the docs are updated frequently? If so, using an etag would probably be a better solution.

**Comment by ruuda** [comment] 2018-04-18 20:49
I can only reproduce this in Chromium, not in Firefox.

**Comment by varkor** [comment] 2018-04-18 21:08
This is a duplicate of https://github.com/rust-lang/rust/issues/49648. The bug _has_ been fixed, but the fix will unfortunately take a little time to get into the live version of the docs!

**Closed by varkor** 2018-04-18 21:08 UTC
