### ISSUE TITLE
Rustdoc search fails when navigating directly to search url: crateSearchDropDown is null

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/rust#82986] opened 2021-03-10 20:26 UTC
Navigating directly to the following url:

https://docs.rs/tokio/1.3.0/tokio/index.html?search=Sleep

will fail to show any results and emit the following Javascript error:

```
Uncaught TypeError: crateSearchDropDown is null
    setupSearchLoader https://docs.rs/main-20210308-1.52.0-nightly-8f349be27.js:8
    <anonymous> https://docs.rs/main-20210308-1.52.0-nightly-8f349be27.js:8
    <anonymous> https://docs.rs/main-20210308-1.52.0-nightly-8f349be27.js:8
main-20210308-1.52.0-nightly-8f349be27.js:8:1189
    setupSearchLoader https://docs.rs/main-20210308-1.52.0-nightly-8f349be27.js:8
    <anonymous> https://docs.rs/main-20210308-1.52.0-nightly-8f349be27.js:8
    <anonymous> https://docs.rs/main-20210308-1.52.0-nightly-8f349be27.js:8
```
This is using firefox.

**Comment by Nemo157** [comment] 2021-03-12 08:38
Probably related to https://github.com/rust-lang/rust/pull/82310; seems to be docs.rs specific though, https://doc.rust-lang.org/nightly/std/?search=vec works

**Comment by Nemo157** [comment] 2021-03-12 08:42
Ohh, docs.rs passes `--disable-per-crate-search`, it probably reproduces with that locally.

**Comment by GuillaumeGomez** [comment] 2021-03-13 20:03
The problem is on docs.rs side: there is a missing file (crates.js).

**Comment by GuillaumeGomez** [comment] 2021-03-13 20:12
But even without `crates.js`, it should work. Sending a fix.

**Comment by GuillaumeGomez** [comment] 2021-04-01 15:27
The problem doesn't occur on the new tokio version so I think we can now close this.

**Closed by GuillaumeGomez** 2021-04-01 15:27 UTC
Labels: C-bug, T-rustdoc
