### ISSUE TITLE
function calls in statics cause internal compiler error

### ISSUE THREAD

**Issue by sj6219** [rust-lang/rust#26643] opened 2015-06-29 00:28 UTC
Source is very simple.

//
//
static F : Box< Fn(i32) -> i32 > = Box::new(move |x:i32| x);

fn main() {
}
//
//

this code generate fault as follows.

src\main.rs:2:34: 2:58 error: function calls in statics are limited to struct an
d enum constructors [E0015]
src\main.rs:2 static F : Box<Fn(i32) -> i32> = Box::new(move |x:i32| x);
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/m
aster/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'assertion failed: self.mode == Mode::Var', C:/bot/sl
ave/beta-dist-rustc-win-64/build/src/librustc\middle\check_const.rs:232

Could not compile `hello_world`.

To learn more, run the command again with --verbose.

**Comment by frewsxcv** [comment] 2015-06-30 04:57
This causes an ICE on 1.1.0. This does not cause in ICE on 1.2.0 beta.

I assume this caused by the use of a static closure. If so, this is a duplicate of https://github.com/rust-lang/rust/issues/25180

**Comment by arielb1** [comment] 2015-06-30 14:23
Duplicate of #25180.

**Closed by arielb1** 2015-06-30 14:23 UTC
Labels: I-ICE
