### ISSUE TITLE
Optimizer believes vector's length field may alias with its own buffer

### ISSUE THREAD

**Issue by NieDzejkob** [rust-lang/rust#80921] opened 2021-01-11 17:51 UTC
Consider the following code:

```rust
pub fn treat_vec(v: &mut Vec<usize>) {
    if v.len() == 1 && v[0] == 42 {
        assert!(v.pop() == Some(42))
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=0934f95f6f633219828056919b0a9a83))

I'd expect the assertion to get optimized-out. However, the following assembly is generated:

```asm
	pushq	%rax
	cmpq	$1, 16(%rdi)
	jne	.LBB0_4
# %bb.1:
	movq	(%rdi), %rax
	cmpq	$42, (%rax)
	jne	.LBB0_4
# %bb.2:
	movq	$0, 16(%rdi)
	cmpq	$42, (%rax)
	jne	.LBB0_3

.LBB0_4:
	popq	%rax
	retq

.LBB0_3:
	leaq	.L__unnamed_1(%rip), %rdi
	leaq	.L__unnamed_2(%rip), %rdx
	movl	$37, %esi
	callq	*core::panicking::panic@GOTPCREL(%rip)
	ud2
```

The only instruction between the two `cmpq $42, (%rax)` comparisons is a write to `16(%rdi)`. Thus, LLVM seems to believe that these two locations may alias.

**Comment by nagisa** [comment] 2021-01-11 18:41
Duplicate of https://github.com/rust-lang/rust/issues/54878. Thanks!

**Closed by nagisa** 2021-01-11 18:41 UTC
Labels: A-LLVM, C-enhancement, I-slow

**Comment by nagisa** [comment] 2021-01-11 18:44
And/or https://github.com/rust-lang/rust/issues/71354

**Comment by jrmuizel** [comment] 2021-03-31 20:33
Yep, this is fixed in Nightly
