### ISSUE TITLE
current_exe return \\\?\\ prefix symbols

### ISSUE THREAD

**Issue by bmiyuan** [rust-lang/rust#99931] opened 2022-07-30 02:53 UTC
**Background：**
I use current_exe() on Windows, but std::env::current_exe() return "\\\\?\\D:\\code\\test\\target\\debug\\test.exe"

**Steps to Reproduce:**
fn main() {
    let program_dir=std::env::current_exe().unwrap();
    println!("program_dir {:?}",&program_dir);
}

**Rust Version:**
rustc 1.62.1 (e092d0b6b 2022-07-16)

**Expected Behavior:**
I would expect to get:
"D:\\code\\test\\target\\debug\\test.exe"

**Actual Behavior:**
"\\\\?\\D:\\code\\test\\target\\debug\\test.exe"

**Comment by bjorn3** [comment] 2022-07-30 11:39
libstd uses `GetModuleFileNameW` to get the executable name: https://github.com/rust-lang/rust/blob/e50ff9b4521234e56ff46f8ed0372d5cb5689654/library/std/src/sys/windows/os.rs#L239 This function seems to indeed return `\\?\` prefixed paths. libstd can handle these paths just fine, and they are mandatory when the path gets too long. Not a windows expert, but I did say not a bug.

**Comment by the8472** [comment] 2022-07-30 12:44
These are [valid paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces). If you need to pass them to an application which can't handle them you can try using the [dunce](https://crates.io/crates/dunce) crate, but it's not guaranteed that this will work for all paths because verbatim paths can refer to files that are unnamable by non-verbatim ones. Not only due to lengths but also due to some parsing that happens.

**Comment by mati865** [comment] 2022-07-31 16:27
There is also unstable [`absolute`](https://doc.rust-lang.org/std/path/fn.absolute.html) function.

**Comment by nagisa** [comment] 2022-08-01 00:08
Duplicate of https://github.com/rust-lang/rust/issues/59117

**Closed by nagisa** 2022-08-01 00:08 UTC
Labels: O-windows

**Comment by Zoxc** [comment] 2023-03-25 01:26
https://github.com/rust-lang/rust/issues/59117 seems to be a separate issue about turning paths absolute.
