### ISSUE TITLE
thread 'rustc' panicked at 'Box<dyn Any>' lib.rs:973:33

### ISSUE THREAD

**Issue by axaluss** [rust-lang/rust#105856] opened 2022-12-18 01:45 UTC
Don't know what rust code caused this issue...

Running windows 10 WSL:  Ubuntu 22.04.1 LTS.

Update: I reverted to some nightly from last month `nightly-2022-11-11` and it's compiling fine.

using: 
```
[dependencies]
rusqlite = { version = "0.28.0", features = ["bundled"] }
diesel = { version = "2.0.0", features = ["sqlite", "r2d2"]}
tokio = { version = "1.23.0", features = ["full"] }
dotenvy = "0.15"
askama = { version = "0.11.1", features = [ "serde-yaml" ,"with-rocket", "mime", "mime_guess"] }
askama_escape = "0.10.3"
askama_rocket = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.66"
rocket = "0.5.0-rc.2"
rocket_anyhow = "0.1.1"
chrono = { version = "0.4.23", features = ["serde"] }
serde_yaml = "0.9"
serde_with = { version = "2.1.0", features = ["macros", "std", "chrono", "json"] }
either = { version = "1.8.0", features = ["serde"] }
derive_builder = "0.11.2"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
```

Error:
```

error: internal compiler error: compiler/rustc_codegen_llvm/src/context.rs:969:13: failed to get layout for `&mut Pin<&mut hyper::server::shutdown::Grac
eful<rocket_http::listener::Incoming<rocket::ext::CancellableListener<rocket::shutdown::Shutdown, L>>, hyper::service::make::MakeServiceFn<[closure@rock
et::server::<impl rocket::rocket::Rocket<rocket::phase::Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::shutdown::Shutdown, hyper::common::
exec::Exec>>`: unable to determine layout for `&mut Pin<&mut hyper::server::shutdown::Graceful<rocket_http::listener::Incoming<rocket::ext::CancellableL
istener<rocket::shutdown::Shutdown, L>>, hyper::service::make::MakeServiceFn<[closure@rocket::server::<impl rocket::rocket::Rocket<rocket::phase::Orbit>
>::http_server<L>::{closure#0}::{closure#2}]>, rocket::shutdown::Shutdown, hyper::common::exec::Exec>>` because `&mut Pin<&mut hyper::server::shutdown::
Graceful<rocket_http::listener::Incoming<rocket::ext::CancellableListener<rocket::shutdown::Shutdown, L>>, hyper::service::make::MakeServiceFn<[closure@
rocket::server::<impl rocket::rocket::Rocket<rocket::phase::Orbit>>::http_server<L>::{closure#0}::{closure#2}]>, rocket::shutdown::Shutdown, hyper::comm
on::exec::Exec>>` cannot be normalized

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/9c07efe84f28a44f3044237696acc295aa407ee5/compiler/rustc_errors/src/lib.rs:973:33
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
   3: <rustc_errors::Handler>::span_bug::<rustc_span::span_encoding::Span, &alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::
span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::span_bug_fmt::<rustc_span::span_encoding::Span>
   7: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::LayoutOfHelpers>::handle_layout_err
   8: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::LayoutOf>::spanned_layout_of::{closure#0}
   9: <rustc_codegen_llvm::context::CodegenCx as rustc_middle::ty::layout::LayoutOf>::layout_of
  10: <rustc_codegen_ssa::mir::place::PlaceRef<&rustc_codegen_llvm::llvm_::ffi::Value>>::project_type::<rustc_codegen_llvm::builder::Builder>
  11: <rustc_codegen_ssa::mir::FunctionCx<rustc_codegen_llvm::builder::Builder>>::codegen_place
  12: <rustc_codegen_ssa::mir::FunctionCx<rustc_codegen_llvm::builder::Builder>>::codegen_block
  13: rustc_codegen_ssa::mir::codegen_mir::<rustc_codegen_llvm::builder::Builder>
  14: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  15: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, rustc
_span::symbol::Symbol, rustc_codegen_ssa::ModuleCodegen<rustc_codegen_llvm::ModuleLlvm>>
  16: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  17: rustc_codegen_ssa::base::codegen_crate::<rustc_codegen_llvm::LlvmCodegenBackend>
  18: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  19: <rustc_session::session::Session>::time::<alloc::boxed::Box<dyn core::any::Any>, rustc_interface::passes::start_codegen::{closure#0}>
  20: rustc_interface::passes::start_codegen
  21: <rustc_interface::passes::QueryContext>::enter::<<rustc_interface::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core::result::Res
ult<alloc::boxed::Box<dyn core::any::Any>, rustc_errors::ErrorGuaranteed>>
  22: <rustc_interface::queries::Queries>::ongoing_codegen
  23: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<ru
stc_interface::queries::Linker>, rustc_errors::ErrorGuaranteed>>
  24: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Resu
lt<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  25: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGu
aranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (9c07efe84 2022-12-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
[Finished running. Exit status: 1]

```

**Comment by trevyn** [comment] 2022-12-18 05:54
Probably a dupe of #105809

**Comment by jackh726** [comment] 2022-12-19 13:43
Closing as duplicate.

**Closed by jackh726** 2022-12-19 13:43 UTC
Labels: I-ICE, T-compiler, C-bug
