### ISSUE TITLE
Float expressions confusing with trait method calls

### ISSUE THREAD

**Issue by lgvz** [rust-lang/rust#27629] opened 2015-08-10 07:32 UTC
```
fn main() {
    // Both asserts give:
    // 'assertion failed: `(left == right)` (left: `-2`, right: `-3`)'
    assert_eq!( -2.4_f32.floor(), (-2.4_f32).floor() );
    assert_eq!( -2.4_f64.floor(), (-2.4_f64).floor() );
}
```

rustc 1.2.0 (082e47636 2015-08-03)
binary: rustc
commit-hash: 082e4763615bdbe7b4dd3dfd6fc2210b7773edf5
commit-date: 2015-08-03
host: x86_64-unknown-linux-gnu
release: 1.2.0

**Comment by TimNN** [comment] 2015-08-10 14:43
Integer literals exhibit the same behaviour:

```rust
fn main() {
    // assertion failed: `(left == right)` (left: `-2`, right: `2`)
    assert_eq!(-2i32.abs(), (-2i32).abs());
}

**Comment by barosl** [comment] 2015-08-10 15:28
This is also a bit surprising to me, but I searched the issue tracker and found #25564. So, it is a known problem and won't be fixed.

On the other hand, according to [the reference](https://doc.rust-lang.org/nightly/reference.html#number-literals), number literals do *not* start with minus signs in the first place. The minus sign in `-123.abs()` will never be a part of the number literal, so it will always be parsed just like `-x.abs()` would. In this aspect, `-x.abs()` being `-(x.abs())` seems to be quite intuitive to me.

That said, some lint might be useful in this case.

**Comment by TimNN** [comment] 2015-08-10 16:00
I just wrote such a lint, do you think it would be desirable available directly in rustc or should it be added to one of the external lint plugins?

Anyway, I'll think I'll just do a pull request and see what kind of response it gets. In the meantime, the results currently look like this:
```
lintlit.rs:2:13: 2:26 warning: unary minus has lower precedence than method call, #[warn(unary_minus_literal_method)] on by default
lintlit.rs:2     let _ = -0.0f32.abs();
                         ^~~~~~~~~~~~~
```

**Comment by lgvz** [comment] 2015-08-10 19:23
Ah of course, thanks y'all. I think as part of expression like `5.0-0.2f32.abs()` it's actually pretty clear, but not when there's nothing to subract from.

To clarify it I think even a space after the minus is enough because literals never have spaces:
`- 0.2f32.abs()`

**Comment by TimNN** [comment] 2015-08-10 19:29
Ah, but in `5.0-0.2f32.abs()` it's a **binary** minus, we were talking about a **unary** minus earlier

**Comment by lgvz** [comment] 2015-08-10 19:33
@TimNN sure. I wasn't thinking about the linter when I wrote that sentence, just about what's clear.

**Comment by TimNN** [comment] 2015-08-10 19:35
I wasn't thinking about the linter either :) just that unary and binary minus can have different precedences

**Comment by alexcrichton** [comment] 2015-08-10 20:27
As @barosl pointed out this is a duplicate of #25564 which [was closed](https://github.com/rust-lang/rust/issues/25564#issuecomment-103073839), so I'm going to close this as well. A lint can perhaps be discussed in a separate RFC issue.

**Closed by alexcrichton** 2015-08-10 20:27 UTC
