### ISSUE TITLE
Can't use an associated type of a generic param in other generic param's default value

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust#129701] opened 2024-08-28 19:18 UTC
I tried this code:

```rust
trait Trait {
    type Assoc;
}

struct Struct<A: Trait, B = A::Assoc> {
    field_1: A::Assoc,
    field_2: B,
}
```

I expected it it compile.

Instead, a compile error was returned:
```log
error[E0220]: associated type `Assoc` not found for `A`
 --> crates/sandbox/src/lib.rs:5:32
  |
5 | struct Struct<A: Trait, B = A::Assoc> {
  |                                ^^^^^ there is an associated type `Assoc` in the trait `Trait`
  |
```

Instead, I need to write explicitly `<A as Trait>::Assoc` for this to work (although the error message doesn't suggest exactly this). This compiles:
```rust
trait Trait {
    type Assoc;
}

struct Struct<A: Trait, B = <A as Trait>::Assoc> {
    field_1: A::Assoc,
    field_2: B,
}
```

### Why is this a problem?

This emerged in the context of my proc-macro crate [`bon`](https://github.com/elastio/bon). It is a crate that generates builders from functions. It literally takes all the generics and where clause from the original function/method and generates a builder struct that allows you to fill the parameters of the function and eventually invoke it.

The builder then stores the type state in a generic parameter, and the initial builder's type state is assigned as the default value for its state generic parameter, where it contains all the type expressions from the function's parameters.

Can we make it work in Rust?

### Meta

`rustc --version --verbose`:
```
rustc 1.82.0-nightly (515395af0 2024-08-26)
binary: rustc
commit-hash: 515395af0efdbdd657ff08a1f6d28e553856654f
commit-date: 2024-08-26
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

It also reproduces on stable `1.80.1`.

**Comment by fmease** [comment] 2024-08-28 19:44
Duplicate of #87682.

**Closed by fmease** 2024-08-28 19:44 UTC
Labels: C-bug, needs-triage
