### ISSUE TITLE
async/await: Potentially incorrect lifetime handling when structs with lifetimes are referenced

### ISSUE THREAD

**Issue by Matthias247** [rust-lang/rust#58884] opened 2019-03-03 00:18 UTC
The following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=679f4e943b7c216dac7d9134e632e856)) produces a compiler error, even if there doesn't seem to be an obvious lifetime issue:

```rust
#![feature(futures_api, async_await, await_macro)]

struct Ctx<'a> {
    a: &'a str,
}

async fn read_loop<'a>(
    ctx: &'a mut Ctx<'a>,
) -> Result<(), ()>
{
    loop {
        await!(read_single(ctx))?;
    }
    Ok(())
}

async fn read_single<'a>(
    ctx: &'a mut Ctx<'a>,
) -> Result<(), ()>
{
    let _ = ctx.a;
    Ok(())
}
```

The error message is:
```
error[E0499]: cannot borrow `*ctx` as mutable more than once at a time
  --> src/lib.rs:12:28
   |
8  |     ctx: &'a mut Ctx<'a>,
   |     --- lifetime `'1` appears in the type of `ctx`
...
12 |         await!(read_single(ctx))?;
   |                ------------^^^-
   |                |           |
   |                |           mutable borrow starts here in previous iteration of loop
   |                argument requires that `*ctx` is borrowed for `'1`
```

That seems very confusing (or wrong), given that the function doesn't return anything with a lifetime. It works without the loop. An additional scope doesn't help.

I tried to work around it by introducing another lifetime for `ctx`, but doesn't work, since async/await doesn't support it yet.

I got another hint to write an explicit `impl Future` signature, which allows compiling this simplified example: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f006c176dea64435e984cb46bcfef56d
But I feel the more basic variant should work too.

**Comment by nikomatsakis** [comment] 2019-03-05 18:49
The problem here is because of the signature:

```rust
async fn read_loop<'a>(
    ctx: &'a mut Ctx<'a>,
) -> Result<(), ()>
```

This signature is too strong -- it forces the compiler to assume that when you call `read_single`, it may continue using `*ctx` for the remainder of `'a`. (This is because the `'a` appears *under* the `mut` qualifier, making it invariant.) The signature that we need is really:

```rust
async fn read_loop<'a>(
    ctx: &'a mut Ctx<'_>,
) -> Result<(), ()>
```

but I think this will cause problems because of the errors around having multiple lifetimes in an `async fn` (https://github.com/rust-lang/rust/issues/56238).

I'm going to close this issue as **expected behavior**, and effectively a duplicate of https://github.com/rust-lang/rust/issues/56238.

**Closed by nikomatsakis** 2019-03-05 18:49 UTC
Labels: A-async-await
