### ISSUE TITLE
E0119 errors are unhelpful when doing things involving types from another crate

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#36162] opened 2016-08-31 08:44 UTC
I was trying to do something like this:

``` rust
use std::io;

enum Foo<T> {
    Bar(T),
    Qux,
}

impl<T: PartialEq> PartialEq for Foo<T> {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (&Foo::Bar(ref a), &Foo::Bar(ref b)) => a == b,
            (&Foo::Qux, &Foo::Qux) => true,
            (_, _) => false,
        }
    }
}

impl PartialEq for Foo<io::Error> {
    fn eq(&self, other: &Self) -> bool {
        unimplemented!()
    }
}
```

And got the following error as a result:

```
error: conflicting implementations of trait `std::cmp::PartialEq` for type `Foo<std::io::Error>`: [--explain E0119]
  --> <anon>:18:1
   |>
18 |> impl PartialEq for Foo<io::Error> {
   |> ^
note: conflicting implementation is here:
 --> <anon>:8:1
  |>
8 |> impl<T: PartialEq> PartialEq for Foo<T> {
  |> ^

error: aborting due to previous error
```

In and of itself, there is no straightforward explanation as to why this is happening, since io::Error _doesn't_ implement PartialEq.

**Comment by gnzlbg** [comment] 2016-11-14 13:31
I ran into this and it took me a while to figure out what is wrong with my code: 

```rust
trait A {}
trait B {}

trait Foo<T> { } 

impl<T, U> Foo<T> for U: A { ... }
impl<T, U> Foo<T> for U: B { ... }
```

The only information that the error gives is that there are two conflicting implementations.

I would have understood the problem faster if the error message would tell me _why_ are these two implementations conflicting.

**Comment by qnighy** [comment] 2017-07-23 13:56
Seems to be a duplicate of #23980.

**Comment by Mark-Simulacrum** [comment] 2017-07-26 00:35
Closing as a duplicate of #23980. (Thanks @qnighy!)

**Closed by Mark-Simulacrum** 2017-07-26 00:35 UTC
Labels: A-diagnostics, C-bug
