### ISSUE TITLE
borrowck freaks out with patterns in closure args

### ISSUE THREAD

**Issue by Gankro** [rust-lang/rust#45346] opened 2017-10-17 18:12 UTC
The following (valid) program fails to compile with a borrowck error.

```rust
fn main() {
    struct Foo(String, u32);
    
    let input: Vec<Foo> = vec![];
    let query: Vec<String> = vec![];
    
    let mut func = |&Foo(ref name, val)| {
        for (idx, other_name) in query.iter().enumerate() {
            if other_name == name { 
                return (idx, val) 
            }
        }
        unreachable!()
    };
    
    for _ in 0..10 {
        let _result: Vec<_> = input.iter().map(&mut func).collect();
    }
}
```

```
error[E0597]: borrowed value does not live long enough
  --> src/main.rs:18:67
   |
8  |     let mut func = |&Foo(ref name, val)| {
   |                          -------- borrow occurs here
9  |         for (idx, other_name) in query.iter().enumerate() {
10 |             if other_name == name { 
   |                                 - borrowed value needs to live until here
...
18 |         let _result: Vec<_> = input.iter().map(&mut func).collect();
   |                                                                   ^ borrowed value dropped here while still borrowed
```

Removing the pattern match from the closure arguments removes the problem (which doesn't make sense?):

```rust
fn main() {
    struct Foo(String, u32);
    
    let input: Vec<Foo> = vec![];
    let query: Vec<String> = vec![];
    
    let mut func = |input: &Foo| {
        for (idx, other_name) in query.iter().enumerate() {
            if other_name == &input.0 { 
                return (idx, input.1) 
            }
        }
        unreachable!()
    };
    
    for _ in 0..10 {
        let _result: Vec<_> = input.iter().map(&mut func).collect();
    }
}
```

Random Notes: 

* Whether func is passed `&mut` or `&` doesn't matter. 
* Whether `for query.iter().enumerate() { ... }` or `query.iter().position(|| { ... })` is used doesn't matter.
* Same on stable and nightly (playground versions)

**Comment by Gankro** [comment] 2017-10-17 18:13
cc @kvark

**Comment by Gankro** [comment] 2017-10-17 18:15
Similar program from @kvark 

```rust
struct Foo(String);

fn main() {
    let foo_names = vec!["".to_string()];
    let foos = vec![Foo("xx".to_string())];
    let foo_pos = |&Foo(ref name)| {
        foo_names.iter().position(|s| s == name).unwrap()
    };

    let mut temp = Vec::new();
    for _ in 0 .. 3 {
        let fs = foos
            .iter()
            .map(&foo_pos)
            .collect::<Vec<_>>();
        temp.push(fs)
    }
}
```

**Comment by Gankro** [comment] 2017-10-17 18:20
Further reduced:

```rust
fn main() {
    struct Foo(String);
    let _ = |&Foo(ref name)| {
        name.len()
    };
}
```

```
error[E0597]: borrowed value does not live long enough
 --> src/main.rs:4:19
  |
4 |     let _ = |&Foo(ref name)| {
  |                   ^^^^^^^^ does not live long enough
5 |         name.len()
  |                  - borrowed value needs to live until here
  |
  = note: ...but borrowed value is only valid for the empty lifetime
```

**Comment by Gankro** [comment] 2017-10-17 18:23
Adding a type annotation makes it compile(???):

```rust
fn main() {
    struct Foo(String);
    let _ = |&Foo(ref name): &Foo| {
        name.len()
    };
}
```

**Comment by nikomatsakis** [comment] 2017-10-18 15:30
The borrow check is correct, in a sense. The problem is, presumably, regionck. Essentially, without the type annotation, we wind up inferring that the signature of the closure is `fn(&'a Foo)` for *some* region `'a` in the parent scope. Since the function is never called, this region winds up being considered unconstrained, and gets inferred to `'empty`. The borrowck then gets unhappy, because `'empty` does not include the call site.

When there is the explicit type annotation, we instead infer a signature of `for<'a> fn(&'a Foo)` -- in other words, the region is bound, not free, and hence can be different for every call. This is a better signature for this particular function. 

The ideal fix would be for us to "generalize" signatures -- presumably using something like let-generalization from ML inference. This has long been on the "to do" list.

Short of that, another alternative might be to add a kind of constraint that pushes the region to not be `'empty`. But it's not clear what that should be: we already add a constraint at each call, which seems sorta like the right thing.

Overall the treatment of regions in closures is annoyingly hacky. It's one of those things that I've been hoping to revisit as part of the move to NLL -- i.e., if we are doing region checking post MIR construction, then closures are much more explicit and I *hope* that makes things easier.

**Comment by Gankro** [comment] 2017-10-18 15:34
The closure is used in the original example; is the issue there that inference can never create a `for<'a>`, only actual type annotations can?

**Comment by Gankro** [comment] 2017-10-18 15:43
Addendum: is it possible to do something like "try the hack, and then if that fails, also try `for<'a>`"?(assuming the hacky behaviour is desirable in some cases?)

**Comment by pnkfelix** [comment] 2018-05-29 23:49
(FYI all of the tests in this issue appear to compile when I run them under `#![feature(nll)`.)

**Comment by pnkfelix** [comment] 2019-04-29 11:28
NLL (migrate mode) is enabled in all editions as of PR #59114. Verified that test case compiled in Nightly 2015 edition; closing as fixed.

**Closed by pnkfelix** 2019-04-29 11:28 UTC
Labels: A-borrow-checker, C-bug, NLL-fixed-by-NLL, T-compiler
