### ISSUE TITLE
Empty match for references to uninhabitable enums fails

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust#70829] opened 2020-04-06 00:19 UTC
In the below code, `&Void` is incorrectly treated as inhabitable:

```rust
enum Void {}
impl PartialEq<()> for Void {
    fn eq(&self, _: &()) -> bool {
        match self {}
    }
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7cce3b5cbedef78c6700c6f3a0cd41de))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0004]: non-exhaustive patterns: type `&Void` is non-empty
 --> src/lib.rs:4:15
  |
1 | enum Void {}
  | ------------ `Void` defined here
...
4 |         match self {}
  |               ^^^^
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms

error: aborting due to previous error

For more information about this error, try `rustc --explain E0004`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Comment by sfackler** [comment] 2020-04-06 02:38
Duplicate of #24885.

**Closed** 2020-04-06 08:34 UTC

**Comment by clarfon** [comment] 2020-04-06 12:16
Oops, guess my search wasn't thorough enough.
