### ISSUE TITLE
Copy button on docs is inaccessible, no tooltips

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#84986] opened 2021-05-06 11:56 UTC
On https://doc.rust-lang.org/nightly/std/future/trait.Future.html

We kept clicking the button beside "Trait std::future::Future" and we couldn't tell what it did. Seemed pretty useless. So we asked around and apparently it copies the `use std::future::Future;`. Anyway, this should really have a tooltip tbh.

### Meta

Public nightly rustdoc, as of the time of posting this issue.

**Comment by Nemo157** [comment] 2021-05-06 12:02
Duplicate of https://github.com/rust-lang/rust/issues/84639

**Closed by Nemo157** 2021-05-06 12:02 UTC
Labels: A-rustdoc-ui, C-bug
