### ISSUE TITLE
std::io::copy does not copy

### ISSUE THREAD

**Issue by 2909081** [rust-lang/rust#95756] opened 2022-04-07 07:31 UTC
### issue
Specified that the std::io::[copy](https://doc.rust-lang.org/std/io/fn.copy.html) function should copy the data. But the data is not copied and transferred.

### Code
```rust
// std::io::copy 
use std::io;

fn main() {
    let mut reader: &[u8] = b"hello";
    let mut writer: Vec<u8> = vec![];

    io::copy(&mut reader, &mut writer).unwrap();

    println!("reader: {:?}", &reader); // reader: []
    println!("writer: {:?}", &writer); // writer: [104, 101, 108, 108, 111]
}
```

### Meta
`rustc --version --verbose`:

```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-unknown-linux-gnu
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by CryZe** [comment] 2022-04-07 10:08
It seems to copy the data into the writer just fine. The problem is that the the Read trait internally needs to track where it is, and in case of the Read implementation on immutable slice references, it simply moves the beginning of the slice forward. So here the Read trait consumes your entire reader binding. The underlying slice however is entirely immutable, so it's really just your reader binding that got messed with.

**Comment by 2909081** [comment] 2022-04-07 10:15
I did not understand so deeply. I'm just learning Rust. Thanks for the explanation.

**Comment by RalfJung** [comment] 2022-04-10 02:21
Specifically, here's how to avoid that:
```rust
use std::io;

fn main() {
    let reader: &[u8] = b"hello";
    let mut writer: Vec<u8> = vec![];

    io::copy(&mut {reader}, &mut writer).unwrap();

    println!("reader: {:?}", &reader); // reader: []
    println!("writer: {:?}", &writer); // writer: [104, 101, 108, 108, 111]
}
```
prints
```
reader: [104, 101, 108, 108, 111]
writer: [104, 101, 108, 108, 111]
```
Note the `&mut {reader}`, which *copies* `reader` into a fresh temporary and then passes a mutable reference to that. (The fact that you lad to `let mut reader` in your example was a hint that something a bit odd was going on.)

**Comment by 2909081** [comment] 2022-04-10 16:01
But the instructions say that you need to use arguments in the form:
```rust
pub fn copy<R: ?Sized, W: ?Sized>(reader: &mut R, writer: &mut W) -> Result<u64> 
where
    R: Read,
    W: Write, 
```

**Comment by RalfJung** [comment] 2022-04-10 16:06
Yes, and that's what I did, didn't I? The code actually compiles and works, try it out. :)

**Comment by 2909081** [comment] 2022-04-10 17:01
Yes it works. I'm new to Rust and I wouldn't have guessed. I'm just reading the documentation and there is an example of how a method works that doesn't work. std::io::[copy](https://doc.rust-lang.org/std/io/fn.copy.html)

**Comment by jtmoon79** [comment] 2023-01-14 04:21
Agree with @2909081 that this is non-obvious.

[Current documentation](https://archive.ph/KlfE0) reads

> Copies the entire contents of a reader into a writer.
> This function will continuously read data from reader and then write it into writer in a streaming fashion until reader returns EOF.
> On success, the total number of bytes that were copied from reader to writer is returned.

I recommend a sentence like

> `copy` moves data from the passed _reader_ into the _writer_.

The necessity of the word "_moves_" reveals that this function is either misnamed or incorrectly implemented.

[Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b43c01dca7f22ae9dc28fe3255208809)

**Comment by RalfJung** [comment] 2023-01-14 10:35
> On Linux (including Android), this function uses copy_file_range(2), sendfile(2) or splice(2) syscalls to move data directly between file descriptors if possible.

That use of the word "move" has nothing to do with the Rust concept of "moving" as in "transferring ownership". It also has nothing to do with this issue.

The surprising behavior here really is not specific to `io::copy`, it is all about the `impl Read for &mut &[u8]` that you are using. Directly calling `read` on that has the same behavior:
```rust
use std::io::Read;

fn main() {
    let mut reader: &[u8] = b"hello";
    let mut out = [0u8; 16];
    while reader.read(&mut out).unwrap() > 0 {}
    
    println!("{reader:?}"); // []
}
```

**Comment by the8472** [comment] 2023-07-10 11:35
This [is documented](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#impl-Read-for-%26%5Bu8%5D) on `impl Read for &[u8]`:

> Read is implemented for &[u8] by copying from the slice.
> Note that reading updates the slice to point to the yet unread part. The slice will be empty when EOF is reached.

I don't think there's anything to do here.

**Closed by the8472** 2023-07-10 11:35 UTC
Labels: T-libs-api
