### ISSUE TITLE
== fails to match types on associated type with two PartialEq<A / B> bounds

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#34792] opened 2016-07-12 20:43 UTC
rustc 1.12.0-nightly (47b3a9834 2016-07-10)

``` rust
pub struct A;
pub struct B;

pub trait Foo {
    type T: PartialEq<A> + PartialEq<B>;
}

pub fn generic<F: Foo>(t: F::T, a: A, b: B) -> bool {
    t == a && t == b
}
```

``` rust
error: mismatched types [--explain E0308]
  --> a.rs:12:10
   |>
12 |>     t == a && t == b
   |>          ^ expected struct `B`, found struct `A`
note: expected type `B`
note:    found type `A`

error: aborting due to previous error
```

Changing the order of bounds in the associated type declaration changes which `==` causes a spurious "mismatched types" error.

Using UFCS works around the issue:

``` rust
    PartialEq::<A>::eq(&t, &a) && t == b
```

---

The same issue exists with bounds like `type T: PartialEq + PartialEq<B>` to compare `T` with itself as well as another type.

**Comment by rkruppe** [comment] 2016-07-13 21:11
cf. #24066

**Comment by eddyb** [comment] 2016-07-16 19:25
Looks like this is caused by [using `find`](https://github.com/rust-lang/rust/blob/d5b9850d79beb87c0e498e0a0b8097e4a11bfae6/src/librustc/traits/select.rs#L1221) on the set of bounds from the trait, but that is just find the first one (in the order they are internally stored), this needs to filter and produce a vector of bounds or something similar.

cc @rust-lang/compiler

**Comment by doomrobo** [comment] 2016-07-18 04:24
Update: using filter and then calling `candidates.extend` on all matching bounds does not fix this issue.

**Comment by eddyb** [comment] 2016-07-18 09:24
@doomrobo I believe your problem is [this logic](https://github.com/rust-lang/rust/blob/34f35ed29c8acdbe1e3c172786fc41d6f4fb6090/src/librustc/traits/select.rs#L1706-L1708).
Right now it works fine because the `if victim.candidate == other.candidate` above would trigger for `ObjectCandidate` vs `ObjectCandidate` or `ParamCandidate` vs `ParamCandidate`.

However, it's incorrect with your changes as `ParamCandidate(bound_a)` is dropped in favor of `ParamCandidate(bound_b)` even if `bound_a` and `bound_b` are not equal.
The correct form would be more like this:
```rust
                // Arbitrarily give param candidates priority
                // over projection and object candidates.
                ObjectCandidate => true,
                ProjectionCandidate(_) => {
                    if let ProjectionCandidate(_) = other.candidate {
                        false
                    } else {
                        true
                    }
                },
```

**Comment by nikomatsakis** [comment] 2016-07-18 23:24
I guess that you didn't just call `filter`, but are also packaging up the specific bound that was matched? Anyway, not having seen the full diff, the general direction of these changes make sense to me.

**Comment by nikomatsakis** [comment] 2016-07-21 20:15
Related: https://github.com/rust-lang/rust/pull/34912

**Comment by pnkfelix** [comment] 2016-07-21 20:15
triage: P-medium

**Comment by estebank** [comment] 2019-05-14 00:17
Triage: [no change](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=437781479a408d2a0f90436aa69897df):

```
error[E0308]: mismatched types
 --> src/lib.rs:9:10
  |
9 |     t == a && t == b
  |          ^ expected struct `B`, found struct `A`
  |
  = note: expected type `B`
             found type `A`
```

**Comment by ldm0** [comment] 2020-12-18 22:06
This is fixed on current master. Should be closed.

**Comment by humancalico** [comment] 2021-01-02 20:23
@estebank I would like to work on this issue if its still relevant?

**Comment by SimonSapin** [comment] 2021-01-03 01:12
As @ldm0 mentioned the original code now compiles: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=106d275bc9d5ae878cc0c28c038dcec7

Closing as there doesn’t seem to be anything left to do here.

**Comment by estebank** [comment] 2021-01-08 00:20
@SimonSapin so we have any `// check-pass` regression test? I couldn't see any.

**Comment by SimonSapin** [comment] 2021-01-08 08:01
Oh good point. Sorry I missed the label.

@humancalico Yes, feel free to work on adding a regression test!

**Closed** 2021-01-16 23:15 UTC
Labels: A-associated-items, A-typesystem, C-bug, E-easy, E-needs-test, P-medium, T-compiler
