### ISSUE TITLE
rustc fails to produce lifetime and closure related compiler error.

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#29793] opened 2015-11-12 02:44 UTC
We ran into this in conrod, where one of the widgets would produce different behaviour depending on whether it was compiled in debug or release.

The related conrod issue is [here](https://github.com/PistonDevelopers/conrod/issues/619).

[This](https://github.com/PistonDevelopers/conrod/issues/619#issuecomment-155974672) comment describes the strange behaviour more precisely.

[This](https://github.com/PistonDevelopers/conrod/issues/619#issuecomment-155977384) comment demonstrates the fix used.

@huonw and @Aatch helped to point out that the difference in behaviour seemed to be due to the fact that rustc was failing to produce an error relating to the lifetimes of the `demo`, `col` and `row` values.

@Aatch shared a simplified example of what error we *should* have received [here](https://play.rust-lang.org/?gist=c490d7550c8cfc310612&version=stable).

Edit: I should mention, this bug was found in:
- `rustc 1.4.0 (8ab8581f6 2015-10-27)`
- `rustc 1.6.0-nightly (5b4986fa5 2015-11-08)`
- `rustc 1.5.0-beta.2 (b0f440163 2015-10-28)`

on both windows and osx.

**Comment by Aatch** [comment] 2015-11-12 02:46
I'm looking into this, trying to get a reasonably accurate reproduction and have come across this:

```rust
fn main() {
    let x = Some(|x: usize, y: usize| {
        |t: bool| if t { x } else { y }
    });
    
    // If the following line is uncommented, it doesn't compile
    //use_(x);
}

fn use_<G, F: FnMut(usize, usize) -> G>(f: Option<F>) {
    if let Some(mut f) = f {
        let _ = f(1, 2);
    }
}
```

https://play.rust-lang.org/?gist=b4a25867408e0056c8f3&version=stable

Which I believe is related.

**Comment by Aatch** [comment] 2015-11-12 03:28
Woo! Took me a while, but here is a minimal(-ish) reproduction (while still being similar to the original example):

```rust
struct WrapA<F>(Option<F>);

impl<F> WrapA<F> {
    fn new() -> WrapA<F> {
        WrapA(None)
    }
    fn set(mut self, f: F) -> Self {
        self.0 = Some(f);
        self
    }
}

struct WrapB<F>(Option<F>);

impl<F> WrapB<F> {
    fn new() -> WrapB<F> {
        WrapB(None)
    }
    fn set(mut self, f: F) -> Self {
        self.0 = Some(f);
        self
    }
}

trait DoStuff : Sized {
    fn handle(self);
}

impl<F, T> DoStuff for WrapA<F> 
where F: FnMut(usize, usize) -> T, T: DoStuff {
    fn handle(mut self) {
        if let Some(ref mut f) = self.0 {
            let x = f(1, 2);
            let _foo = [0usize; 16];
            x.handle();
        }
    }
}

impl<F> DoStuff for WrapB<F> where F: FnMut(bool) -> usize {
    fn handle(mut self) {
        if let Some(ref mut f) = self.0 {
            println!("{}", f(true));
        }
    }
}

impl<F, T> WrapA<F> 
where F: FnMut(usize, usize) -> T, T: DoStuff {
    fn handle_ref(&mut self) {
        if let Some(ref mut f) = self.0 {
            let x = f(1, 2);
        }
    }
}

fn main() {
    let mut w = WrapA::new().set(|x: usize, y: usize| {
        WrapB::new().set(|t: bool| if t { x } else { y })
    })
    w.handle(); // This works
    // w.handle_ref(); // This doesn't
}
```
https://play.rust-lang.org/?gist=330b4ee92fecd1c8f499&version=stable

I think the move of the wrapping type has something to do with it, given that `handle_ref` doesn't work, while `handle` does.

**Comment by Aatch** [comment] 2015-11-12 03:43
I decided to go back to my simple case:

```rust
fn main() {
    let _x = |x: usize, y: usize| {
        |t: bool| if t { x } else { y }
    };
```

This compiles (and probably shouldn't), while the following doesn't (which is expected):


```rust
fn main() {
    let _x = |x: usize, y: usize| {
        let x = x;
        let y = y;
        |t: bool| if t { x } else { y }
    };
```

This suggests to me that the lifetimes associated with the `x` and `y` variables are slightly too long.

Also /cc @rust-lang/compiler

**Comment by nikomatsakis** [comment] 2015-11-12 14:03
agreed, seems wrong. sigh.

**Comment by nikomatsakis** [comment] 2015-11-12 14:03
triage: P-high

**Comment by arielb1** [comment] 2015-11-15 14:00
The issue is that:
    * Closure signatures are not required to be well-formed.
    * That would not be regularly a problem, as regions in closure signatures are supposed to always outlive the closure.
    * However, parameters are regarded as being "outside" the closure, so they pass this check.

I am not sure of the best way to fix this.

**Comment by pnkfelix** [comment] 2015-11-19 21:24
assigning to self to try to help niko with his plate of stuff

**Comment by pnkfelix** [comment] 2015-12-10 18:40
Okay, I've done something much like what @arielb1 described, namely adding a new `Scope` variant that outlives the `ParameterScope` and then using that for these lifetimes, rather than `DestructionScope`.

I should have a PR up shortly, assuming my `make check` run passes...

**Closed** 2015-12-17 01:22 UTC
Labels: A-compiler, A-lifetimes, I-unsound, P-high, T-compiler
