### ISSUE TITLE
cdylib doesn't include unmangled symbols from dependencies even when explicitly re-exported.

### ISSUE THREAD

**Issue by sadmac7000** [rust-lang/rust#82922] opened 2021-03-09 00:55 UTC
I tried this code:

in foo.rs:
```rust
#[no_mangle]
pub unsafe extern "C" fn foo() {}
```

in bar.rs:
```rust
extern crate foo;

pub use foo::*;
```

On the console:
```
$ rustc --crate-type=rlib foo.rs
$ rustc --crate-type=cdylib bar.rs -L.
$ readelf -s libbar.so |grep foo
```

I expected to see this happen:
readelf should show my unmangled symbol.

Instead, this happened:
the symbol is missing from the crate.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

**Comment by gheoan** [comment] 2021-07-30 22:42
Is this a duplicate of https://github.com/rust-lang/rust/issues/50007?

@rustbot modify labels: +A-linkage, +T-compiler

**Comment by tmandry** [comment] 2021-08-07 01:25
Looks like it is (other issues mentioning cdylib explicitly have been closed as duplicates of it), thanks. Closing as a duplicate of #50007.

**Closed by tmandry** 2021-08-07 01:25 UTC
Labels: A-linkage, T-compiler, C-bug
