### ISSUE TITLE
E0282 Cannot infer type for type parameter None when trait wrapped in an Option

### ISSUE THREAD

**Issue by glennpierce** [rust-lang/rust#96244] opened 2022-04-20 08:38 UTC
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c6854c9ab5cbec3fd53e788876b7fe08

```
pub trait Output {
    fn name(&self) -> String;
}

pub fn run(mut output_override: Option<Box<impl Output>>) -> () {

}

fn main() {
    // run(None::<Box<outputs::console_output::ConsoleOutput>>)
    run(None)
}
```

The current output is:

```
error[[E0282]](https://doc.rust-lang.org/stable/error-index.html#E0282): type annotations needed
  [--> src/main.rs:11:5
](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c6854c9ab5cbec3fd53e788876b7fe08#)   |
11 |     run(None)
   |     ^^^ cannot infer type for type parameter `impl Output` declared on the function `run`

For more information about this error, try `rustc --explain E0282`.
```

I had a few implementations of the Output trait I was confused that I could not just pass None as I felt the compiler should
detect the Option None value before looking at the trait for the run parameter

In the end I had to just pick one of my implementations to pass to run as a default which makes for unclear code
like

```
run(None::<Box<outputs::console_output::ConsoleOutput>>)
```

**Comment by fmease** [comment] 2022-04-20 11:17
This looks like intended behavior to me: As Rust is a statically typed language, every value has to have a type (known at compile time). This includes the value `None` here. Its type is `Option<Box<T>>` for some type parameter `T` that has to implement `Output`. This `T` however cannot be inferred. There is possibly an infinite amount of types that can be used for `T`. `T` has to be filled in with a concrete type.

I suspect you wanted to write `Option<Box<dyn Output>>`. With `dyn` instead of `impl`, [the code compiles](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a95b16604988170c0b2ddc85f8176ce9) because `dyn Output` is a concrete type, it is a trait object type.

---

However I'd be interested to know from the compiler team if we can detect this case and offer the suggestion to replace `impl` with `dyn` here.

**Comment by zirconium-n** [comment] 2022-04-20 15:51
I would recommend create a ZST and use that, similar to:

```rust
trait Output {
    fn name(&self) -> String;
}

fn no_output() -> Option<impl Output> {
    struct NoOutput;

    impl Output for NoOutput {
        fn name(&self) -> String {
            unimplemented!()
        }
    }

    Option::<NoOutput>::None
}


// ...  run(no_output())
```

**Comment by fmease** [comment] 2022-04-20 16:13
If you decide to go down the route of using a zero-sized dummy implementor as @zirconium-n suggests, I will advice to reach for uninhabited types to get rid of the call to `unimplemented!()`. E.g. `std::convert::Infallible`, `!` or a custom type:

```rust
fn no_output() -> Option<impl Output> {
    enum Void {}

    impl Output for Void {
        fn name(&self) -> String {
            match *self {}
        }
    }

    Option::<Void>::None
}
```

**Comment by fmease** [comment] 2023-09-06 15:45
Closing as wontfix on the basis of https://github.com/rust-lang/rust/issues/96244#issuecomment-1103815732.
Feel free to raise objections

**Closed by fmease** 2023-09-06 15:45 UTC
Labels: A-diagnostics, T-compiler
