### ISSUE TITLE
Unused variable warning is emitted on trait method with default implementation

### ISSUE THREAD

**Issue by boustrophedon** [rust-lang/rust#64723] opened 2019-09-24 01:09 UTC
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1229cc645454ceb61ca781b7ad4a6116

If you have a default implementation of a trait inline with the declaration, in which you don't use a parameter, the compiler will warn about the unused variable and suggest that you add an underscore.

However, the underscore in this case is undesirable because it will appear in your documentation.

**Comment by hellow554** [comment] 2019-09-24 09:52
In that case you can use `#[allow(unused_variables)]` (although I see your point here)...

**Comment by xiaotianrandom** [comment] 2020-05-22 14:35
This is a duplicate of #14027 and #26487, which were closed: https://github.com/rust-lang/rust/issues/26487#issuecomment-169828205

**Comment by rylev** [comment] 2021-01-14 17:56
Closing as the behavior is correct and has already been discussed [here](https://github.com/rust-lang/rust/issues/26487#issuecomment-169828205)

**Closed by rylev** 2021-01-14 17:56 UTC
Labels: A-lint, C-enhancement, T-lang
