### ISSUE TITLE
Default Associated Consts cannot use `Self::`

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#32241] opened 2016-03-14 07:37 UTC
```rust
#![feature(associated_consts)]

trait Boop {
    const X: fn() = Self::x;
    fn x();
}
```
errors with
```
<anon>:4:21: 4:28 error: failed to resolve. Use of undeclared type or module `Self` [E0433]
<anon>:4     const X: fn() = Self::x;
                             ^~~~~~~
<anon>:4:21: 4:28 help: see the detailed explanation for E0433
<anon>:4:21: 4:28 error: unresolved name `Self::x` [E0425]
<anon>:4     const X: fn() = Self::x;
                             ^~~~~~~
<anon>:4:21: 4:28 help: see the detailed explanation for E0425
```

**Comment by petrochenkov** [comment] 2016-03-14 08:18
Duplicate of https://github.com/rust-lang/rust/issues/28809
(It's not only `A-resolve`, type checker support is also required.)

**Closed** 2016-03-14 16:42 UTC
Labels: A-resolve
