### ISSUE TITLE
ICE mutable allocation in constant   ui/associated-type-bounds/union-bounds.rs with  -Zmir-opt-level=2

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#68296] opened 2020-01-16 23:38 UTC
` RUST_BACKTRACE=1 rustc ui/associated-type-bounds/union-bounds.rs  -Zmir-opt-level=2`

````
error: internal compiler error: mutable allocation in constant

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:346:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  12: std::panicking::begin_panic
  13: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
  14: core::ptr::real_drop_in_place
  15: core::ptr::real_drop_in_place
  16: core::ptr::real_drop_in_place
  17: rustc_interface::interface::run_compiler_in_existing_thread_pool
  18: scoped_tls::ScopedKey<T>::set
  19: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (3291ae339 2020-01-15) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z mir-opt-level=2

query stack during panic:
end of query stack
````

somewhat reduced:
````rust
#![feature(associated_type_bounds)]
#![feature(untagged_unions)]

#![allow(unused_assignments)]

trait Tr1: Copy { type As1: Copy; }
trait Tr4<'a>: Copy { type As4: Copy; }
impl Tr1 for &str { type As1 = bool; }
impl Tr1 for () { type As1 = (usize,); }
impl<'a> Tr4<'a> for (usize,) { type As4 = u8; }

union Un4<'x1, T: Tr1<As1: for<'l> Tr4<'l>>> {
    f1: &'x1 <T::As1 as Tr4<'x1>>::As4,
}

fn main() {
    let f1 = (1,);
    let _ = Un4::<()> { f1: &f1.0 };
}
````

rustc @ 9fe05e9456b84996637c2f29b35c37960e537540

**Comment by matthiaskrgr** [comment] 2020-01-16 23:43
`src/test/ui/consts/dangling_raw_ptr.rs` is another example:

````rust
const FOO: *const u32 = { //~ ERROR any use of this value will cause an error
    let x = 42;
    &x
};

fn main() {
    let x = FOO;
}
````

**Comment by matthiaskrgr** [comment] 2020-02-01 21:45
While the original example no longer panics for me on `rustc 1.42.0-nightly (cd1ef390e 2020-01-31)`, the dangling_raw_ptr one still does.

**Comment by jonas-schievink** [comment] 2020-04-06 21:20
Caused/Uncovered by the copy propagation pass

**Comment by jonas-schievink** [comment] 2020-04-06 22:06
It turns the constant into this, so probably the issue is that it removes the storage markers:

```rust
// MIR for `FOO` after CopyPropagation

const FOO: *const u32 = {
    let mut _0: *const u32;              // return place in scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:1:12: 1:22
    let _1: u32;                         // in scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:2:9: 2:10
    let _2: &u32;                        // in scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:3:5: 3:7
    scope 1 {
        debug x => _1;                   // in scope 1 at src/test/ui/consts/dangling_raw_ptr.rs:2:9: 2:10
    }

    bb0: {
        nop;                             // bb0[0]: scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:2:9: 2:10
        _1 = const 42u32;                // bb0[1]: scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:2:13: 2:15
                                         // ty::Const
                                         // + ty: u32
                                         // + val: Value(Scalar(0x0000002a))
                                         // mir::Constant
                                         // + span: src/test/ui/consts/dangling_raw_ptr.rs:2:13: 2:15
                                         // + literal: Const { ty: u32, val: Value(Scalar(0x0000002a)) }
        StorageLive(_2);                 // bb0[2]: scope 1 at src/test/ui/consts/dangling_raw_ptr.rs:3:5: 3:7
        _2 = &_1;                        // bb0[3]: scope 1 at src/test/ui/consts/dangling_raw_ptr.rs:3:5: 3:7
        _0 = &raw const (*_2);           // bb0[4]: scope 1 at src/test/ui/consts/dangling_raw_ptr.rs:3:5: 3:7
        nop;                             // bb0[5]: scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:4:1: 4:2
        StorageDead(_2);                 // bb0[6]: scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:4:1: 4:2
        return;                          // bb0[7]: scope 0 at src/test/ui/consts/dangling_raw_ptr.rs:1:1: 4:3
    }
}
```

(aside: the pass didn't actually optimize anything here, it *just* removed the markers, which is not very helpful)

**Comment by RalfJung** [comment] 2020-04-14 11:11
@matthiaskrgr 
this example
```rust
const FOO: *const u32 = { //~ ERROR any use of this value will cause an error
    let x = 42;
    &x
};

fn main() {
    let x = FOO;
}
```
Just looks like wrong code to me, the pointer is dangling as it refers to a local that does out of scope. I don't see a bug.

Since it seems like the example in the OP got fixed, could you describe expected and actual behavior with latest rustc to explain what the bug is that we are tracking here?

Cc @rust-lang/wg-const-eval

**Comment by JohnTitor** [comment] 2020-05-17 12:17
I think the ICE from this snippet (https://github.com/rust-lang/rust/issues/68296#issuecomment-575399123) has been fixed by #71665.

**Comment by RalfJung** [comment] 2020-05-17 12:53
Yeah that PR entirely removes the `delay_span_bug` in question, so let's close this.

**Closed by RalfJung** 2020-05-17 12:53 UTC
Labels: A-mir, A-mir-opt, C-bug, I-ICE, T-compiler, glacier, requires-nightly

**Comment by matthiaskrgr** [comment] 2020-05-17 13:02
Can confirm that all the snippets mentioned no longer ICE with `-Zmir-opt-level=2` :+1:
