### ISSUE TITLE
Between opt-level=1 and opt-level=2, LLVM deoptimizes the output of ptr::addr, if it ptr::addr is #[inline]

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#103285] opened 2022-10-20 04:22 UTC
godbolt demo: https://godbolt.org/z/51o3hYjvv

This code:
```rust
#[inline]
fn inline_addr<T>(ptr: *const T) -> usize {
    unsafe {
        core::mem::transmute(ptr)
    }
}

pub fn inline_is_nonoverlapping(src: *const u8, dst: *const u8) -> usize {
    let src_usize = inline_addr(src);
    let dst_usize = inline_addr(dst);
    if src_usize > dst_usize { let _ = src_usize - dst_usize; }
    src_usize
}
```
At `opt-level=2` compiles to this:
```asm
example::inline_is_nonoverlapping:
        cmp     rdi, rsi
        jbe     .LBB0_3
        jb      .LBB0_2
.LBB0_3:
        mov     rax, rdi
        ret
.LBB0_2:
        push    rax
        lea     rdi, [rip + str.0]
        lea     rdx, [rip + .L__unnamed_1]
        mov     esi, 33
        call    qword ptr [rip + core::panicking::panic@GOTPCREL]
        ud2
```
Decreasing to `opt-level=1` or removing the `#[inline]` on the transmute wrapper function causes the panic path to go away.

As far as I can tell, this doesn't happen on stable but it happens on beta and nightly. This code pattern is used in the standard library here:
https://github.com/rust-lang/rust/blob/cb9467515b5a9b15aaa905683c6b4dd9e851056c/library/core/src/intrinsics.rs#L2234-L2238

@rustbot label +A-LLVM +regression-from-stable-to-beta

**Comment by MSxDOS** [comment] 2022-10-20 08:30
Caused by mir inlining, `-Z inline-mir=no` removes the panic.

**Comment by nikic** [comment] 2022-10-20 10:19
Works fine with LLVM 16: https://llvm.godbolt.org/z/67WPE19xa Presumably due to https://github.com/llvm/llvm-project/commit/926e7312b2f20f2f7b0a3d5ddbd29da5625507f3.

Assigning to myself to check back on this after the next LLVM update.

**Comment by nikic** [comment] 2022-10-20 10:50
Eh, we might as well fix this on the rustc side: https://github.com/rust-lang/rust/pull/103299

**Comment by apiraino** [comment] 2022-10-20 12:53
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103285.20Between.20opt-level.3D1.20and.20opt-level.3D2.2C.20LLVM.20deoptimiz.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Closed** 2022-10-30 20:25 UTC
Labels: A-LLVM, P-medium, T-compiler, regression-from-stable-to-beta
