### ISSUE TITLE
Cargo.toml manifest parsing error for missing README since nightly 2020-06-09

### ISSUE THREAD

**Issue by timvisee** [rust-lang/rust#73279] opened 2020-06-12 11:15 UTC
I'm seeing `Cargo.toml` manifest parsing errors using the latest Rust nightly. This started showing up in CI today. It seems this is caused by a missing README file when configured in `Cargo.toml` of the respective crates.

Here are three of those errors:

```
  Downloaded rustls v0.17.0
error: failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.17.0/Cargo.toml`
Caused by:
  readme file with name '../README.md' was not found
```

```
  Downloaded bitvec v0.16.2
error: failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.16.2/Cargo.toml`
Caused by:
  readme file with name 'README.md' was not found
```

```
  Downloaded remove_dir_all v0.5.2
error: failed to parse manifest at `/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/remove_dir_all-0.5.2/Cargo.toml`
Caused by:
  readme file with name 'README.md' was not found
```

Maybe this should just show a warning instead, to prevent breaking existing crates? Quite a few crates on `crates.io` seem to suffer from this problem.

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (a37c32e2d 2020-06-11)
cargo 1.46.0-nightly (1ec223eff 2020-06-09)
```

Here are the CI logs I'm seeing these errors in:
- https://gitlab.com/timvisee/ffsend-api/-/jobs/592712334
- https://gitlab.com/timvisee/pokoebox/-/jobs/592713822#L1662
- https://gitlab.com/timvisee/ffsend/-/jobs/592712179
- https://gitlab.com/timvisee/copypasta-ext/-/jobs/592714533
- https://gitlab.com/timvisee/wikitrans/-/jobs/592798987

**Comment by jonas-schievink** [comment] 2020-06-12 11:16
Duplicate of https://github.com/rust-lang/cargo/issues/8351

**Comment by sfackler** [comment] 2020-06-12 11:17
This should probably be filed on the https://github.com/rust-lang/cargo repository.

**Closed by jonas-schievink** 2020-06-12 11:16 UTC
Labels: C-bug

**Comment by timvisee** [comment] 2020-06-12 11:19
You're right. Should have posted this in the cargo repository. I'll follow the progress on this there.

Thanks for the quick response.
