### ISSUE TITLE
error: could not compile `tracing-subscriber`

### ISSUE THREAD

**Issue by czh12138git** [rust-lang/rust#95106] opened 2022-03-19 06:37 UTC
### Code

```Rust
<code>  This error occurred when building the bevy project .  the application panicked for no apparent reason
```

### Meta

`rustc --version --verbose`:1.61.0-nightly (58f11791a 2022-03-17) running on x86_64-pc-windows-msvc
```
<version>    1.61.0-nightly (58f11791a 2022-03-17) running on x86_64-pc-windows-msvc
```

### Error output

```
<output> thread 'rustc' panicked at 'assertion failed: !value.has_escaping_bound_vars()', /rustc/58f11791af4f97572e7afd83f11cffe04bbbd12f\compiler\rustc_middle\src\ty\sty.rs:1089:9
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.61.0-nightly (58f11791a 2022-03-17) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2 -C linker=rust-lld.exe -Z share-generics=n

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [is_sized_raw] computing whether `dyn std::io::Write` is `Sized`
#1 [layout_of] computing layout of `*const dyn std::io::Write`
#2 [layout_of] computing layout of `core::ptr::unique::Unique<dyn std::io::Write>`
#3 [layout_of] computing layout of `alloc::boxed::Box<dyn std::io::Write>`
end of query stack
```

</p>
</details>

**Comment by jackh726** [comment] 2022-03-19 12:27
Duplicate of #94998. Fixed in latest nightly.

**Closed by jackh726** 2022-03-19 12:27 UTC
Labels: I-ICE, T-compiler, C-bug
