### ISSUE TITLE
`std::file` claims that it returns the name of a file, but it returns a relative path

### ISSUE THREAD

**Issue by bonsairobo** [rust-lang/rust#117605] opened 2023-11-05 09:37 UTC
### Location

https://doc.rust-lang.org/std/macro.file.html

### Summary

The docs say:

> Expands to the file **name** in which it was invoked.

But in fact, a relative path is returned. For example, if we have `src/main.rs`:

```rust
fn main() {
    println!("{}", std::file!())
}
```

This prints "src/main.rs" (on GNU/Linux).

I believe this will be a path relative to the workspace root, though an expert should confirm this.

**Comment by bjorn3** [comment] 2023-11-05 16:55
> I believe this will be a path relative to the workspace root, though an expert should confirm this.

Cargo will invoke rustc for local crates with the workspace root as working directory and for dependencies from crates.io with their source directory as working directory. For local crates it then passes a relative path as filename and for crates.io dependencies the absolute path as filename to rustc. `file!()` is relative based on the original filename that was passed to rustc.

**Comment by bonsairobo** [comment] 2023-11-05 20:37
> file!() is relative based on the original filename that was passed to rustc.

I'm not sure I understand this part. Could you give an example?

**Comment by bjorn3** [comment] 2023-11-05 20:39
If you pass `src/lib.rs` to rustc as filename and you have a module `foo` at `src/foo.rs`, then `file!()` will return `src/foo.rs` when invoked inside that module. If you pass `/path/to/lib.rs` then it will return `/path/to/foo.rs` when invoked inside the `foo` module.

**Comment by bonsairobo** [comment] 2023-11-05 21:04
Is there any way to test the crates.io behavior without first publishing the crate?

**Comment by bonsairobo** [comment] 2023-11-05 21:11
And can I assume that the path would depend on the operating system? E.g. on Windows you would get an absolute path as `C:\\path\to\crate\src\lib.rs`?

**Comment by bjorn3** [comment] 2023-11-05 21:32
> Is there any way to test the crates.io behavior without first publishing the crate?

Yes, same behavior applies to git dependencies AFAIK, so you could create a git repo somewhere and depend on it.

> And can I assume that the path would depend on the operating system? E.g. on Windows you would get an absolute path as C:\\path\to\crate\src\lib.rs?

Yes

**Comment by Dylan-DPC** [comment] 2024-07-21 14:31
Closing this as it's not an issue and it works as intended

**Closed by Dylan-DPC** 2024-07-21 14:31 UTC
Labels: A-docs, T-libs

**Comment by bonsairobo** [comment] 2024-07-22 05:34
@Dylan-DPC Can you tell me why it's "not an issue and working as intended"? I find the documentation to be both factually incorrect and lacking a thorough explanation of how the macro actually behaves.
