### ISSUE TITLE
canonicalizing paths on RAM disks fails

### ISSUE THREAD

**Issue by xNxExOx** [rust-lang/rust#59107] opened 2019-03-11 17:18 UTC
I was trying to build tokio example but I encountered these errors. I tried both discord for Rust Programming Language, and tokio gitter, where I was told it is compiler error.
I have Windows 10 1803 in Czech language, so "Nesprávná funkce." would be something like "Invalid function." in English.

code example from:
https://github.com/tokio-rs/tokio/blob/master/examples/chat.rs

## Meta

`rustc --version --verbose`:
```
rustc 1.33.0 (2aa4c46cf 2019-02-28)
binary: rustc
commit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858
commit-date: 2019-02-28
host: x86_64-pc-windows-msvc
release: 1.33.0
LLVM version: 8.0
```

Backtrace:
https://pastebin.com/NTMDxvD2

**Comment by xNxExOx** [comment] 2019-03-11 17:27
`A:\` is my RAM drive, why output folder can not be on RAM drive?

**Comment by retep998** [comment] 2019-03-11 22:46
Rust currently insists on canonicalizing paths, which unfortunately does not work on certain types of drives. To fix this libstd would need to gain a way of normalizing paths *without* canonicalizing them, and then rustc would be updated to use that everywhere.

**Comment by Enselic** [comment] 2023-08-21 04:32
Triage: Duplicate of #48249

**Closed by Enselic** 2023-08-21 04:32 UTC
Labels: O-windows, I-ICE, T-compiler, C-bug
