### ISSUE TITLE
Explicit `Self: Sized` bounds missing from generated documentation.

### ISSUE THREAD

**Issue by jswrenn** [rust-lang/rust#62899] opened 2019-07-23 15:21 UTC
Nearly every method of `Iterator` has an explicit `Self: Sized` bound. These bounds are **present in libcore**'s documentation (e.g., [`Iterator::count`](https://doc.rust-lang.org/1.36.0/core/iter/trait.Iterator.html#method.count)), but are **missing in libstd**'s documentation (e.g., [`Iterator::count`](https://doc.rust-lang.org/1.36.0/std/iter/trait.Iterator.html#method.count)).

**Comment by dwrensha** [comment] 2019-07-24 23:39
This looks like a dupe of #24183.

**Comment by Mark-Simulacrum** [comment] 2019-08-31 21:52
Indeed. Closing as duplicate.

**Closed by Mark-Simulacrum** 2019-08-31 21:52 UTC
Labels: C-bug, T-rustdoc
