### ISSUE TITLE
write_volatile fails in miri for non-scalar types

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rust#58645] opened 2019-02-22 14:04 UTC
Minimal reproducible example:

```rust
pub struct S(u8, u8);

fn main() {
    let mut dst = S(0, 0);
    unsafe {
        std::ptr::write_volatile(&mut dst, S(10, 20));
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bd62fc19a1412d57ece242d7ce0709ab))

When tried in the playground with Miri, produces:

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc_mir/interpret/operand.rs:82: Got a fat pointer where a scalar was expected

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.0-nightly (633d75ac1 2019-02-21) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z always-encode-mir -Z mir-emit-retag -Z mir-opt-level=0 -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Comment by Centril** [comment] 2019-02-22 16:03
cc @oli-obk @RalfJung

**Comment by RalfJung** [comment] 2019-02-22 16:04
I think the correct bug description is "fails for non-scalar values".

**Comment by Centril** [comment] 2019-02-22 16:15
Somewhat reduced further:
```rust
fn main() {
    unsafe {
        struct S(u8, u8);
        std::ptr::write_volatile(&mut S(0, 0), S(0, 0));
    }
}
```

**Comment by oli-obk** [comment] 2019-02-22 16:19
Code :golf: 

```rust
fn main() {
    unsafe {
        std::ptr::write_volatile(&mut (0, 0), (0, 0));
    }
}
```

**Comment by oli-obk** [comment] 2019-02-22 16:19
Why is this marked as a regression from stable?

**Comment by Centril** [comment] 2019-02-22 16:21
@oli-obk huh... I swore I saw it working on stable but apparently not =P

**Comment by oli-obk** [comment] 2019-02-22 16:24
miri runs on the playground don't distinguish between "stable" and "nightly". They are all on nightly.

**Comment by RalfJung** [comment] 2019-02-22 16:40
This should be quite easy to fix: At <https://github.com/rust-lang/miri/blob/76138c56575c347207039bdeafb8456bd72116ad/src/intrinsic.rs#L54>, move `volatile_load` to a separate branch that, instead of going through a scalar, uses `copy_op` directly. Same for `volatile_store`.

**Comment by RReverser** [comment] 2019-02-22 17:06
> I think the correct bug description is "fails for non-scalar values".

Maybe, but it works for struct with a single field, so that's as close as I got to describe the issue.

**Comment by RalfJung** [comment] 2019-02-22 17:14
It works for structs with single fields where that field is a scalar. :)

But it's okay, these are compiler internals. They just help us understand what the actual cause of the issue is.

**Comment by rchaser53** [comment] 2019-02-24 14:38
I'm interested in miri, so I would like to do this.

**Comment by RalfJung** [comment] 2019-02-24 17:32
@rchaser53 it's yours! You'll not have to change rustc for this, just Miri, and the starting point in the code is https://github.com/rust-lang/miri/blob/76138c56575c347207039bdeafb8456bd72116ad/src/intrinsic.rs#L54 as mentioned above. You'll want to use `copy_op` there, similar to [this](https://github.com/rust-lang/miri/blob/76138c56575c347207039bdeafb8456bd72116ad/src/intrinsic.rs#L297).

(What the hell is the `move_val_init` intrinsic anyway?^^)

**Comment by oli-obk** [comment] 2019-03-12 21:07
Has been fixed in miri

**Closed by oli-obk** 2019-03-12 21:07 UTC
Labels: A-miri, E-easy, E-mentor, I-ICE
