### ISSUE TITLE
Link to source in docs gives 'not found' page

### ISSUE THREAD

**Issue by rookwood101** [rust-lang/rust#23390] opened 2015-03-15 12:20 UTC
When clicking the [src] link at the top right of the page of all of the rust docs pages, you are taken to the 'not found' page instead of being taken to the relevant source file.

**Comment by GuillaumeGomez** [comment] 2015-03-15 16:58
Which page are talking about ? and which link please ?

**Comment by iKevinY** [comment] 2015-03-15 18:55
This is related to #23192.

**Comment by steveklabnik** [comment] 2015-03-18 23:59
Yes, closing as a duplicate of that issue.

**Closed by steveklabnik** 2015-03-18 23:59 UTC
